### ISSUE TITLE
DetailsList: NVDA+Chrome - Column header values read twice in scan mode

### ISSUE THREAD

**Issue by JllyGrnGiant** [OfficeDev/office-ui-fabric-react#10002]
### Bug Report

- __Package version(s)__: Latest used on sample site (2019.7.29.6)
- __Browser and OS versions__: Chrome

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal 

Products/sites affected: Azure DevOps

#### Describe the issue:

1. Navigate to https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/basic in Google Chrome
2. Start NVDA screen reader
3. Tab to the DetailsList sample on the page
4. Switch NVDA to scan mode
5. Press ctrl+left/ctrl+right to move back and forth between the name and value column headers

#### Actual behavior:

The first time each cell is visited in the column headers NVDA correctly says just, for example, "Name column 2 clickable Name". But subsequent times through NVDA reads "Name Name column 2 clickable Name Name".

![image](https://user-images.githubusercontent.com/1325800/62226992-fb473380-b36f-11e9-8237-352f820d4476.png)

#### Expected behavior:

Column header values are only read once.

**Comment by JllyGrnGiant** [comment]
Something of note is sometimes when I used the scan mode 'T' shortcut to jump to the details list table instead of tabbing to the table in app mode then switching to scan mode, focus outlines weren't showing in the DetailsList even though NVDA says I'd reached the table. In this state, I could not reproduce the issue. So there might be something wrong with how DetailsList is controlling focus.

**Comment by marygans** [comment]
Hi @JllyGrnGiant can you confirm that are you only experiencing this with NVDA? DetailsList seems to works fine with Narrator/Edge. Looking back on some previous issues submitted in the past, this is a bug that might be in the works of getting fixed on their end.

**Comment by JllyGrnGiant** [comment]
Hi @marygans I can confirm that between Narrator+Edge/Chrome and NVDA+Chrome I only experience this issue with NVDA.

Is there an issue in NVDA you'd be able to point me to?
Our team has to point to external issues in order to resolve our team's accessibility bugs as external.

**Comment by marygans** [comment]
Hi @JllyGrnGiant!

Here is a link to a previous [issue](https://github.com/OfficeDev/office-ui-fabric-react/issues/9887). 

I'd suggest submitting an issue with NVDA [here](https://github.com/nvaccess/nvda/issues).

**Comment by JllyGrnGiant** [comment]
Thanks, @marygans.
Filed an issue with NVDA.
https://github.com/nvaccess/nvda/issues/10066

I'm not yet confident the issue lies with them since regular tables don't seem to exhibit this behavior with NVDA, but we'll see what they say.

Thanks again!

**Comment by marygans** [comment]
Awesome, I will soft close the issue with `Not an issue` label. If you have more questions, feel free to to ask and I will reopen it. Thanks for submitting the issue!
