### ISSUE TITLE
SelectionMode is exported from multiple files and is causing jest errors

### ISSUE THREAD

**Issue by sushruth** [OfficeDev/office-ui-fabric-react#10017]
### Environment Information 
 
- __Package version(s)__: 7.19.0 
- __Browser and OS versions__: `enzyme` render environment within jest on Windows 10 insiders

### Please provide a reproduction of the bug in a codepen:

Jest shows an error when trying to mount using enzyme. I am unable to make this sound less gibberish so please allow me to explain - In short, this seems to be the issue for the module resolver - 

- `SelectionMode` is exported in both `packages/office-ui-fabric-react/src/utilities/selection/SelectionZone.tsx` and `packages/office-ui-fabric-react/src/utilities/selection/interfaces.ts` but both files are exported entirely from `packages/office-ui-fabric-react/src/utilities/selection/index.ts`

- This is causing the following error  (given below in Actual Behavior section) when running `react-scripts test` (when using a component that uses `DetailsList`)

#### Actual behavior:

An error is thrown -  

```
TypeError: Cannot redefine property: SelectionMode
        at Function.defineProperty (<anonymous>)
 
      at node_modules/office-ui-fabric-react/lib/utilities/src/utilities/selection/index.ts:3:1
          at Array.forEach (<anonymous>)
      at Object.<anonymous> (node_modules/office-ui-fabric-react/lib/utilities/src/utilities/selection/index.ts:3:1)
      at Object.<anonymous> (node_modules/office-ui-fabric-react/lib/components/src/components/DetailsList/index.ts:1:1)
      at Object.<anonymous> (node_modules/office-ui-fabric-react/src/DetailsList.ts:1:1)
```

#### Expected behavior:
 
No error is expected

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: High
 
Products/sites affected: NA

**Comment by cliffkoh** [comment]
This looks like a duplicate of #9661 ...

**Comment by cliffkoh** [comment]
I've sent an email to escalate the visibility of this problem. 

I am going to mark this as a duplicate and let #9661 be the main issue tracking a resolution.

**Comment by sushruth** [comment]
Sounds good. Will track the original. Thanks!
