### ISSUE TITLE
Spin button label inconsistent formatting

### ISSUE THREAD

**Issue by HarryGifford** [OfficeDev/office-ui-fabric-react#10015]
### Environment Information 
 
- __Package version(s)__: 7.18.1 
- __Browser and OS versions__: Chrome 76.0.3809.87 (Official Build) (64-bit), Windows 10.

### Please provide a reproduction of the bug in a codepen:

Go to [this codepen](https://codepen.io/hegi/pen/NQgjxN).

#### Actual behavior:
 
The alignment of the labels for spin buttons doesn't match the alignment for other controls such as the ComboBox or TagField. 
 
#### Expected behavior:
 
Alignment should match. Additionally the alignment should match when the label is aligned left or when there's no label at all.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal

Products/sites affected: N/A

**Comment by marygans** [comment]
Hi @HarryGifford, thank you for submitting this issue! 

I am checking out your [codepen](https://codepen.io/khmakoto/pen/NJVPjM) and I don't see the use of the `SpinButton` in your example. Would you like to update the CodePen with the actual behavior you are experiencing? Can you also clarify your alignment expectations? (e.g. Are you referring to the spacing?)

Thanks!

**Comment by HarryGifford** [comment]
Is there some action needed from me?

**Comment by marygans** [comment]
Not at the moment!

**Comment by marygans** [comment]
Hi @HarryGifford the PR referenced should solve this issue you submitted. Please let me know if you have further questions!
