### ISSUE TITLE
TagPicker support for adding new tags

### ISSUE THREAD

**Issue by panigrah** [OfficeDev/office-ui-fabric-react#1001]
Does TagPicker have support for adding new tags? I was expecting to see a event handlers such as "onNewTag()" and "onRemoveTag()" in the api.

**Comment by panigrah** [comment]
I worked it out so that the `onResolveSuggestions` handler adds and returns the filter text in the array. e.g.

        <TagPicker onResolveSuggestions={this._onResolveSuggestions} />

        _onResolveSuggestions(filterText, currentSelected, limitResults?) {
            let tags = ... //get list of tags from server or redux store or state
            tags.splice(0, 0, {key: filterText, name: filterText, state: 'new'})
            return  tags
        }

the `onChange` handler can then add or remove tags from the store by looking at the `tags` with a `state` of `new`

**Comment by leoseccia** [comment]
I want to do the same thing but not quite sure how to go about it... I added a bounty on [this StackOverflow question](https://stackoverflow.com/questions/50451984/office-ui-fabric-react-tagpicker-new-item) in the hope that someone will help...
