### ISSUE TITLE
Documentation for DetailsList with custom row rendering handler needs modification

### ISSUE THREAD

**Issue by elmarsto** [OfficeDev/office-ui-fabric-react#10012]
#### Environment Information 
 
- __Package version(s)__:  Office UI Fabric React 6.189.2, Typescript 3.5.2

#### Actual behavior:
On my local, a lightly-modified version of the code example given at [the official documentation](https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/customitemrows) yields a typescript error:

```
Type '(props: IDetailsRowProps) => Element | null' is not assignable to type 'IRenderFunction<IDetailsRowProps>'. 
Types of parameters 'props' and 'props' are incompatible.
Type 'IDetailsRowProps | undefined' is not assignable to type 'IDetailsRowProps'.
 Type 'undefined' is not assignable to type 'IDetailsRowProps'.
```
 
#### Expected behavior:

I expect the example used here to work on my local without modification. 

#### Solution:

The example as given needs the line `if (!props) return null` immediately before the return statement shown. If it is not present, the above error is thrown. 

I believe this pertains to some change in the type signature `IRenderFunction`. 

Requested priority: Low

**Comment by marygans** [comment]
Hi @elmarsto, thanks for submitting this issue! Im not able to repro locally. @KevinTCoughlin or @kenotron any ideas?

**Comment by KevinTCoughlin** [comment]
@elmarsto, is [strictFunctionTypes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-6.html#strict-function-types) enabled for your TSC?

If so, this is possibly another instance of https://github.com/OfficeDev/office-ui-fabric-react/issues/9581.
