### ISSUE TITLE
CommandBar: Hover and disabled states are styled incorrectly

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#1002]
### Bug Report

- __Package version(s)__: Latest
- __Browser and OS versions__: All

#### Describe the issue:

Disabled buttons shouldn't have a hover state. There's also this issue with the dark grey on top of the light grey:

![image](https://cloud.githubusercontent.com/assets/1382445/22940315/4f9bc506-f296-11e6-8af6-5e3257d45cfd.png)

**Comment by micahgodbolt** [comment]
both fixed in 2.0.1
