### ISSUE TITLE
need a way on split menu button to exclude props to pass on container

### ISSUE THREAD

**Issue by pagaur** [OfficeDev/office-ui-fabric-react#10028]
#### Describe the feature that you would like added
On a split menu button the split menu container <div gets all the props except 'disabled' are passed which also gets applied on splitButtonMenuButton. But user might want to only apply it to the button and not the container.

#### What component or utility would this be added to
BaseButton

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots
```
<div data-automation-type="RibbonSplitButton" data-automation-id="BulletLibrary" data-unique-id="TellMe-BulletLibrary" data-nav="true" aria-label="Bullets" aria-disabled="false" data-is-focusable="true" aria-pressed="false" role="button" aria-haspopup="true" aria-expanded="false" class="splitButtonContainer-349" tabindex="0"><span style="display: flex;">

<button type="button" data-automation-type="RibbonSplitButton" data-automation-id="BulletLibrary" data-unique-id="TellMe-BulletLibrary" data-nav="true" class="splitPrimaryButton root-339" aria-label="Bullets" aria-disabled="false" data-is-focusable="false" aria-pressed="false" tabindex="-1"><div class="flexContainer-336"><i data-icon-name="Bullets_20" role="presentation" aria-hidden="true" class="icon-198"><svg ...></path></svg></i><div class="textContainer-337">
...</div>
```

**Comment by pagaur** [comment]
I have created a PR for this issue https://github.com/OfficeDev/office-ui-fabric-react/pull/10030

**Comment by marygans** [comment]
Hi @pagaur thanks for submitting this issue + the PR, that't Lets keep this issue open until its approved and merged 💃
