### ISSUE TITLE
Button: Use spans instead of divs to fix validation issues

### ISSUE THREAD

**Issue by jvkrishna** [OfficeDev/office-ui-fabric-react#10021]
### Issue:
[HTML Validator](https://validator.w3.org/nu/about.html) for the button components are failing, for invalid nesting of **div** elements inside the **button**.

From the W3C specifications, **div** elements are not allowed as child of **button**. 

### Codepen:
https://codepen.io/anon/pen/WVExLK

![image](https://user-images.githubusercontent.com/18074161/62320575-60c12000-b455-11e9-891e-9c63a7b49bbe.png)

#### Reproduce:
Go to button documentaion page, https://developer.microsoft.com/en-us/fabric#/controls/web/button, and validate the buttons with the Html validator (https://validator.w3.org/nu/about.html)

**Comment by LukeGaylor13** [comment]
@micahgodbolt the problem here is that this is a accessibility issue for anyone using this particular feature. This should be considered a bug and of high priority.

**Comment by micahgodbolt** [comment]
i understand that it fails a particular validator test, but can you point to an accessibility issue that it actually causes? Are screen readers affected?

**Comment by micahgodbolt** [comment]
it appears that buttons can take 'phrasing' content. So is changing all of the divs to spans an effective way to resolve this?

**Comment by xWiiLLz** [comment]
Also facing this issue as part of our compliance process (W3C HTML validator). I believe that changing `div`s to `span`s will fix the problem, as they are proper [Phrasing content](https://html.spec.whatwg.org/multipage/dom.html#phrasing-content-2).

**Comment by dzearing** [comment]
We have agreed to merge this fix in current v7 builds, but will avoid a backport to v6, as this may be a disruptive change for many.

**Comment by davallen** [comment]
Can we get more understanding of why this is only getting fixed in v7 and not v6? How would it disrupt others as it is internal to the button rendering? We are unable to upgrade to v7 at this time as  we are coupled to other Microsoft products that remain on v6 (and I assume they may not be accessible when leveraging the button component).

**Comment by micahgodbolt** [comment]
I think backporting this would be fine. I think the original goal was to keep it isolated as to have the least amount of disruption. If we find that this change didn't cause many issues to users, I think porting it to 6 shouldn't be too difficult.

**Comment by davallen** [comment]
Micah - Thanks for the flexibility in getting this backported. As I already know my leadership will ask when we can expect this task to happen. 😊 Do you have an approximate timeframe?
