### ISSUE TITLE
[Accessibility] Keytips: Contain 'aria-describedby' values that don't correspond to existing IDs

### ISSUE THREAD

**Issue by HalcyonPride** [OfficeDev/office-ui-fabric-react#10038]
### Environment Information

- **Package version(s)**: 7.19.1
- **Browser and OS versions**: Doesn't matter
- **Screen reader(s)**: N.A.

### Describe the issue:

As described; screenshot below shows errors highlighted by Accessibility Insights for Web:

![image](https://user-images.githubusercontent.com/8681794/62389988-1653a800-b516-11e9-8111-815bbb8831e3.png)

![image](https://user-images.githubusercontent.com/8681794/62390127-5d419d80-b516-11e9-8d64-62f99b61bc24.png)

### Please provide a reproduction of the issue in a codepen:

https://fabricweb.z5.web.core.windows.net/oufr/7.19.1/#/examples/keytips

#### Actual behavior:

As described.

#### Expected behavior:

We need to either remove the 'aria-describedby' attributes, or map them correctly to elements that exist.

### Documentation describing expected behavior

See screenshot above.

**Comment by marygans** [comment]
Hi @HalcyonPride, thank you for submitting this issue! I believe I was able to repro this using Accessibility Insights for Web but I got a different result (see below). However, I used automated tests. Can you specify which automated tests you used so I can use the same one? 
<img width="910" alt="Screen Shot 2019-08-02 at 4 07 03 PM" src="https://user-images.githubusercontent.com/38991459/62403130-1f596f00-b540-11e9-8688-0e0ce80798ab.png">

**Comment by kelseyyoung** [comment]
How does this tool work? When you inspect the DOM manually you'll see the elements with the IDs at the very bottom in a Layer (this is right after a page reload)

![image](https://user-images.githubusercontent.com/4252452/62563101-1d8cf580-b837-11e9-8c75-5fccbbf6295a.png)

**Comment by kelseyyoung** [comment]
As you can see I've linked a PR which I think was the root of the problem; the demo page itself didn't work correctly because those elements weren't present. After this gets merged, can you re-run your tool again?

**Comment by HalcyonPride** [comment]
Hi @kelseyyoung and @marygans: Ahh, yeah, that was it 😅 thank you so much for the quick fix!

**Comment by HalcyonPride** [comment]
How can I remove the "Needs: Attention" and "Needs: Author Feedback" tags? 🤔

**Comment by marygans** [comment]
I can remove them :)
