### ISSUE TITLE
Value is not populated when we click in the combo box in area where no checkbox is selected.

### ISSUE THREAD

**Issue by shivangi-ksolves** [OfficeDev/office-ui-fabric-react#10031]
### Environment Information

- **Package version(s)**: 6.187.2
- **Browser and OS versions**: Linux / 18.04.2

#### Actual behavior:

When we don't select anything from dropdown list & click on outside of list, nothing visible in select area.

#### Expected behavior:

Already selected value should be populated even if we didn't select any checkbox.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Blocking

**Comment by marygans** [comment]
Hi @shivangi-ksolves thank you for submitting this issue! Can you provide a codepen example or something similar to show the problem you are having in more detail? You can also do so by clicking the "export to codepen" button on this [combobox example](https://fabricweb.z5.web.core.windows.net/oufr/7.18.0/#/examples/ComboBox).
