### ISSUE TITLE
Blazor Components

### ISSUE THREAD

**Issue by chadcampbell** [OfficeDev/office-ui-fabric-react#10036]
#### Describe the feature that you would like added

Previously, there was [a request](https://github.com/OfficeDev/office-ui-fabric-react/issues/4357) for Office Fabric UI controls to be ported as Blazor components. That request was [closed over one year ago](https://github.com/OfficeDev/office-ui-fabric-react/issues/4357#issuecomment-377321345). However, [Blazor is now officially part of .NET Core 3.0](https://devblogs.microsoft.com/aspnet/blazor-now-in-official-preview/). For that reason, I wanted to create a new request to port the Office UI Fabric to Blazor.

The reality is, this would be a valuable addition to the .NET community. Some developers prefer dynamic languages, others prefer static languages. A port of this library would serve the needs of both communities.

#### What component or utility would this be added to

The entire Office Fabric UI.

#### Have you discussed this feature with our team, and if so, who

I have not. However, I'm open to discussing it. I believe there is a significant need here and I'm happy to articulate why this port is necessary.

**Comment by marygans** [comment]
Hi @chadcampbell, thanks for submitting this feature request. 
@dzearing correct me if Im wrong but there are still no plans for this right?  @kenotron didn't you do some eval/research on this as well?

**Comment by micahgodbolt** [comment]
Hey @chadcampbell. While this sounds like it'd be an amazing project, it is not within the scope of the UI Fabric React project. We'd love to build out Angular, Vue, Web Component and Blazor versions of all of our controls, but that is far outside of our current charter, and wouldn't have the resources needed to do that work. 

So while the focus of this repo will remain on React for the foreseeable future, we'd love to help support any open source effort to create Fabric/Fluent controls in other languages.

**Comment by darraghjones** [comment]
+1

**Comment by danroth27** [comment]
For folks looking for a community solution, check out https://github.com/limefrogyank/BlazorFabric.
