### ISSUE TITLE
PeoplePicker select people on blur

### ISSUE THREAD

**Issue by rhalaly** [OfficeDev/office-ui-fabric-react#10049]
### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**: Edge beta 77.0.237.0 and latest Chrome on Windows 10

### Please provide a reproduction of the bug in a codepen:

https://fabricweb.z5.web.core.windows.net/oufr/7.19.1/#/examples/peoplepicker

1. Type 'A' in the people picker
2. Blur the people picker by clicking with the mouse anywhere.

#### Actual behavior:

`Anny Lindqvist` is selected automatically

#### Expected behavior:

The changes will be discard.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: Normal

**Comment by jdhuntington** [comment]
Hi @rhalaly - thanks for the report.

I'm afraid the existing behavior of the people picker is the intended behavior. Though using some of the callbacks the PeoplePicker provides, it should be possible to achieve the behavior you would like instead.

Can you tell me more about how you are using the picker? I might be able to offer more useful workarounds if so. Thanks!

**Comment by rhalaly** [comment]
Hi,

I'm actually Microsoft employee and I'm working on 1st party app. Our customers report this issue. They reported that this behavior causing them some unexpected issues that they add peoples in this way by mistake. After I tested it manually I also saw that this is the behavior of the PeoplePicker, and it is really very confusing - the user dose not expect that this behavior will select people.

In my personal opinion, if our users report this as an issue and got confusing (and actually I also think that is confusing) maybe there are more end-users that think that this behavior is confusing but can't reach you. So I think that you should consider this feedback :).
 
Any way, I would like to get an example of how to change this so blur will not trigger a selection because we want to turn it off in our product.

**Comment by jdhuntington** [comment]
There are 2 examples at https://codepen.io/jdh-msft/pen/vodXwy?editors=0011 

The `NormalPeoplePicker` doesn't auto-select on blur out of the box, the behavior was a side effect of some of the options used in the example.

Another option to consider is the `FloatingPeoplePicker`, which provides much more customizability.
