### ISSUE TITLE
[Accessibility] Escape should close the callout. 

### ISSUE THREAD

**Issue by sandeepchads** [OfficeDev/office-ui-fabric-react#1004]
#### Describe the issue:

Currently, we are unable to dismiss the call out control by clicking ESCAPE

#### Actual behavior:

Pressing ESCAPE for call out controls does nothing. 

#### Expected behavior:

ESCAPE should close the call out controls

**Comment by dzearing** [comment]
The callout is a presentational component which doesn't render content or steal focus. Technically you can host 2 callouts on the screen at the same time.  This is actually the default behavior. You can make this work though:

Example:
http://codepen.io/dzearing/pen/JEVdmP

1. make sure you have `onDismiss` wired up.
2. make sure something is focusable within the callout. In the codepen I set `tabIndex=0` attribute on the container within the callout, and set the style rule `outline: 0` so default focus rects don't show.
3. `setInitialFocus = true`. The focus needs to be set within the callout for it to act on the keyboard event.
