### ISSUE TITLE
DetailsList - With SelectionMode.multiple, unable to select row text

### ISSUE THREAD

**Issue by Ralms** [OfficeDev/office-ui-fabric-react#10046]
#Environment Information

- **Package version(s)**: 7.19.0

### Please provide a reproduction of the bug in a codepen:
https://fabricweb.z5.web.core.windows.net/oufr/7.19.1/#/examples/detailslist/basic

#### Actual behavior:

When selectionMode is set to SelectionMode.multiple, we are unable to select the text on the list rows.
This is verified all examples of Detailed list.

#### Expected behavior:

Text to be selectable to allow copy paste. 

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes, changing the CSS property "user-select" from 'none' to 'text' would fix this;

Requested priority: Low

Products/sites affected: In development portal, not in production yet.

**Comment by jdhuntington** [comment]
Hi @Ralms - at the moment, the selection behavior that exists when multi select is true is intentional in favor of selecting rows. Would a work-around work for your use-case? I put together this example that shows how to override this particular property when rendering at https://codepen.io/jdh-msft/pen/BXJjdw

The important lines are:

```jsx
  public render() {
    return (
      <DetailsList
        items={this._items}
        setKey="set"
        onRenderRow={this._onRenderRow}
        checkButtonAriaLabel="Row checkbox"
      />
    );
  }

  private _onRenderRow = (props: IDetailsRowProps): JSX.Element => {
    const customStyles: Partial<IDetailsRowStyles> = { root: {} };
    (customStyles.root as any).userSelect = 'any';
    return <DetailsRow {...props} styles={customStyles} />;
  };
```

**Comment by Ralms** [comment]
Hi @jdhuntington,

I apreciate the work-around, however I'm getting this error on "onRenderRow" property from Typescript:
```
Type '(props: IDetailsRowProps) => Element' is not assignable to type 'IRenderFunction<IDetailsRowProps>'.
  Types of parameters 'props' and 'props' are incompatible.
    Type 'IDetailsRowProps | undefined' is not assignable to type 'IDetailsRowProps'.
      Type 'undefined' is not assignable to type 'IDetailsRowProps'.ts(2322)
DetailsList.types.d.ts(136, 5): The expected type comes from property 'onRenderRow' which is declared here on type 'IntrinsicAttributes & IDetailsListProps & { children?: ReactNode; }'
```
Do you know why this could be happening?


Have you tried this css override?
```
.ms-DetailsRow-fields {
  user-select: text !important;
}

```
I found this simple override to allow text to be selectable and preserves all funcionality.
I'm able to select with mouse, keyboard and even use MarqueeSelection. 
Tested with Opera 62.0.3331.72, Firefox 68.0.1 and Edge 44.18362.1.0

The only problems I found where that double-click action will cause the text to auto-select as expected, but Opera and Edge has diferent behavior from Firefox, that only happens if I literally click on top of the text. With Firefox it will always select the word besides the mouse even if the double-click didn't happen on the text itself. 

Another problem with MarqueeSelection in Firefox and Edge that have a diferent behavior, is that when I start to drag the mouse, it auto-selects all text from the bottom half where the mouse clicked, don't really understand why. But withouth MarqueeSelection it works fine. 

Thanks

**Comment by KevinTCoughlin** [comment]
> Do you know why this could be happening?

@Ralms, do you have `strictFunctionTypes` enabled in your `tsconfig`?

The above compiler error is letting you know the signature does not match `IRenderFunction`'s API: https://github.com/OfficeDev/office-ui-fabric-react/blob/22ee7d15235c177a2a549c1387b07aa847d6fc9f/packages/utilities/src/IRenderFunction.ts#L7

You'll need to handle the `undefined` case(s). That error should then go away.

Let's keep this thread to a single issue. If you have found multiple legitimate bugs then we may want to open separate issues for each to help with triage and debug.

**Comment by Ralms** [comment]
> > Do you know why this could be happening?
> 
> @Ralms, do you have `strictFunctionTypes` enabled in your `tsconfig`?
> 
> The above compiler error is letting you know the signature does not match `IRenderFunction`'s API:
> 
> https://github.com/OfficeDev/office-ui-fabric-react/blob/22ee7d15235c177a2a549c1387b07aa847d6fc9f/packages/utilities/src/IRenderFunction.ts#L7
> 
> You'll need to handle the `undefined` case(s). That error should then go away.
> 
> Let's keep this thread to a single issue. If you have found multiple legitimate bugs then we may want to open separate issues for each to help with triage and debug.

Hi @KevinTCoughlin, 

I feel I'm being miss understood, I never claimed the error I mentioned on my previous to be a bug.
I simply reported back what I'm getting from a work-around provided by a Collaborator of this repository. And the reason I did was because I don't understand where is the possibility of the function returning undefined, the function never seems to do so. 

Eitherway, I'm more concerned with the text not being selectable.

**Comment by jdhuntington** [comment]
@Ralms I believe you're seeing a typescript error due to strict mode. This function (in place of the previous) should handle the undefined case.

```jsx
  private _onRenderRow: IRenderFunction<IDetailsRowProps> = (
    props?: IDetailsRowProps
  ): JSX.Element => {
      if (!props) {
          return <DetailsRow item={undefined} itemIndex={-1}/>;
      }
    const customStyles: Partial<IDetailsRowStyles> = { root: {} };
    (customStyles.root as any).userSelect = "any";
    return <DetailsRow {...props} styles={customStyles} />;
  };
```

What text selection mode are you hoping to get working? Is MarqueeSelection `on` a requirement?

**Comment by Ralms** [comment]
Hi @jdhuntington,

Yes I do have strict on. 
Thank you for helping out with the workaround and getting it to work with strict mode.

As this is clearly not considered an issue to the Office Fabric team, I will proceed and close it.
