### ISSUE TITLE
Picker: Show all available options without text input

### ISSUE THREAD

**Issue by nipunja** [OfficeDev/office-ui-fabric-react#1005]
Picker control (https://fabricreact.azurewebsites.net/fabric-react/master/#/examples/pickers) does not have a way to see all the picker items. It only shows suggestions based on user text input. However, in some of the scenarios, user might not even know what to type. This will be the default case when picker items are filled dynamically by some webservice call. It would be good to show all the pickers items may be on Enter or some other equivalent experience.

**Comment by nipunja** [comment]
Is there any closure over here ? This ask basically prevents the usage of picker control if list is populated dynamically.

**Comment by kristoferbrown** [comment]
@nipunja, the onEmptyInputFocus prop of pickers can be used to accomplish this. See the peoplePicker (https://developer.microsoft.com/en-us/fabric#/components/peoplepicker) for an example of this being done.
