### ISSUE TITLE
Dropdown Items wrapper issue in Office Word add-in 

### ISSUE THREAD

**Issue by rake93** [OfficeDev/office-ui-fabric-react#10051]
I'm facing Drop down items wrapper issue in Office Word-addin even the values are lesser OR more. Dropdown values are not properly aligning when I tried to expand it.  Options are displaying as in the attached Actual results snapshot, even-though I applied the following style,.
```
const dropdownStyles: Partial<IDropdownStyles> = {
    dropdown: { width: 300, marginTop: "5px"},
    dropdownItemsWrapper: { maxHeight: "500px" }
};

```
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: No browser, since its an Office Word plug-in.

### Please provide a reproduction of the bug in a codepen:
Not available in codepen , since its an Office Word plug-in.

#### Actual behavior:
![image](https://user-images.githubusercontent.com/823725/62449837-0ec01900-b739-11e9-8933-632b2aa6e1db.png)

#### Expected behavior:
![image](https://user-images.githubusercontent.com/823725/62449874-213a5280-b739-11e9-89b2-a94094dac10b.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
Yes
Requested priority: (Blocking, High, Normal, Low)
High
Products/sites affected: (if applicable)
NA

**Comment by jdhuntington** [comment]
Hi @rake93 - Unfortunately I'm not able to assist with Word add-ins in this project, only Fabric itself. However, if this issue exists in Fabric and we can make it happen in a codepen I'm more than happy to take a look!
