### ISSUE TITLE
Rating control reading out incorrectly when using Edge +  Narrator

### ISSUE THREAD

**Issue by Hardhik** [OfficeDev/office-ui-fabric-react#10068]
### Environment Information

- **Package version(s)**: Latest ( @7)
- **Browser and OS versions**: Edge, Chrome
- **Screen reader(s)**: Narrator

### Describe the issue:
Incorrectly reading the Rating component in read only setting

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/anon/pen/LweeLY

#### Actual behavior:

Pasting from Narrator buddy:

Large Stars:
Rating value is 1 of 5, group, 
1 of 5 stars selected 
2 of 5 stars selected 
3 of 5 stars selected 
4 of 5 stars selected 
5 of 5 stars selected 
Half star in readOnly mode:, 
group, 
2.5 of 5 stars selected, 
2.5 of 5 stars selected, 
2.5 of 5 stars selected, 
2.5 of 5 stars selected, 
2.5 of 5 stars selected, 
Custom icons:, 
Rating value is 2.5 of 5, group, 

#### Expected behavior:

For read only control for rating stars. Reading the number of stars once should be enough.

### Documentation describing expected behavior

It's confusing to users using only screen readers.

**Comment by jdhuntington** [comment]
Hi @Hardhik - thanks for the report. I'm afraid I'm not seeing the same behavior when using edge and narrator; I'm only hearing the count of stars read a single time. I've tried in 3 browsers (ie11, edge, edge dev) and all exhibit the correct behavior. Are there other steps you may have taken to jump into a different mode?

**Comment by Hardhik** [comment]
Hi @jdhuntington thanks for looking into this.

I just tried it again and I see the behavior mentioned in the bug report. ( Microsoft Edge 44.18362.267.0 + Narrator ( I couldn't find the exact version number of Narrator other than "Released in 2019)

Here's a screenshot of the Narrator settings page:
![image](https://user-images.githubusercontent.com/2673006/62769377-74543280-bab6-11e9-9874-b5a4056eb459.png)

Please let me know if I can provide any other info that can help with debugging this issue

**Comment by jdhuntington** [comment]
Thanks @Hardhik - I still don't hear narrator reading through all the star values on load. I *do* hear things like "3 of 5 stars selected" after selecting a different rating manually on non-read-only controls, but it requires interaction.

Are you able to share a screen capture of what you're hearing?
