### ISSUE TITLE
Trigger DropDown expansion

### ISSUE THREAD

**Issue by danmarshall** [OfficeDev/office-ui-fabric-react#10062]
#### Describe the feature that you would like added

Have a dropdown be expanded from an external event.

#### What component or utility would this be added to

Drowdown

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

We have text rendered in WebGL, when clicked we would like to present the list of items in a dropdown, already dropped down.

**Comment by danmarshall** [comment]
Possibly related to #6348

**Comment by jdhuntington** [comment]
Hi @danmarshall - there's an example on https://fabricweb.z5.web.core.windows.net/oufr/7.20.0/#/examples/dropdown showing how to trigger this event - look for the heading `Required Dropdown` that shows how to invoke the dropdown programatically.

**Comment by danmarshall** [comment]
thanks @jdhuntington ! I will take a look and see if that works for my use case 👍
