### ISSUE TITLE
People Picker: long people card overflows in narrow people picker

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#1006]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: any

#### Describe the issue:

In some scenarios, people resolved from people picker will have a long name. Sometimes the people picker can be narrow (small width). Then the people card will overflow the people picker container which looks bad.

#### Actual behavior:

The people card overflows outside the people picker container.

#### Expected behavior:

The people card is totally inside people picker, the text should somehow truncated.

### If applicable, please provide a codepen repro:

http://codepen.io/ipip2005/pen/WRmEbb

Repro steps:
1. Type anything in the people picker.
2. Select the only people "Annie Lindqvist Dough Linda Steel"
3. See the people card is wider than people picker which looks bad.

**Comment by micahgodbolt** [comment]
.ms-PeoplePicker-Persona is min width of 180px, and with the button padding of 20px on each side, the min width of the people picker suggestion will be 220px. 

The question is, what is the minimum width we can expect the people picker to be?  Then update documentation to specify that. Is 220px too wide? If so, then what number should we go with?

**Comment by joschect** [comment]
@ipip2005 It looks like the codepen does not have the latest version of fabric-react. I'll see if I can't get it updated.

**Comment by lijunle** [comment]
Hi, @joschect The codepen is *always* using the latest version of fabric-react from

>  http://spoppe-a.akamaihd.net/files/fabric/office-ui-fabric-react/latest/office-ui-fabric-react.min.js

I slightly change the code to make it easier to understand the issue: http://codepen.io/lijunle/pen/OpLzPm

Repro steps are the same as mention in https://github.com/OfficeDev/office-ui-fabric-react/issues/1006#issue-207782521

1. Type anything in the people picker.
2. Select the only people "Annie Lindqvist Dough Linda Steel"
3. See the people card is wider than people picker which looks bad.

**Comment by MirandaGe** [comment]
I think this issue is duplicated with https://github.com/OfficeDev/office-ui-fabric-react/issues/1024

**Comment by lijunle** [comment]
> .ms-PeoplePicker-Persona is min width of 180px, and with the button padding of 20px on each side, the min width of the people picker suggestion will be 220px.

@micahgodbolt I could prefer no limit about the width here. It is in *BasePicker* [file](https://github.com/OfficeDev/office-ui-fabric-react/blob/7030f284c3684d6012d8ad65abff158235bc9019/packages/office-ui-fabric-react/src/components/pickers/BasePicker.scss#L9). It makes more reasonable that, each subclass has its own width limitation.

**Comment by joschect** [comment]
@lijunle We can remove the limit on the ms-peoplepicker-persona. 

The codepen is not always using the latest version. I built the latest locally and created a codepen with the office-ui-fabric-react.min.js content and then linked that to a fork of your codpen. As you can see it behaves as expected.

http://codepen.io/slimemold/pen/WpQMOd

**Comment by gitjain** [comment]
Solution has been merged so updating the status.
