### ISSUE TITLE
DetailsList's checkboxes look like radio buttons

### ISSUE THREAD

**Issue by cc0rk** [OfficeDev/office-ui-fabric-react#10073]
### Environment Information

- **Package version(s)**: Current
- **Browser and OS versions**: Irrelevant
- **Screen reader(s)**: Are probably better off

### Describe the issue:

The checkboxes in the detailslist component look like radio buttons. The checkboxes used in this component don't look like the checkboxes in the checkbox component, which is unintuitive and *super* weird. 

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/c8_c0rk/pen/mNXRbG

Detailslist checkboxes are on the left, radio buttons are on the right.

#### Actual behavior:

Checkboxes in the detailslist look like radio buttons.

#### Expected behavior:

Checkboxes in the detailslist look like checkboxes.

### Documentation describing expected behavior

Um... Fabric's checkboxes look like this: https://uifabric.azurewebsites.net/#/controls/web/checkbox
They're squares. Like normal checkboxes. Like everyone's expectation of what a checkbox looks like. A check....In a box.... A checkbox.

It doesn't make sense to have 2 controls that do the same thing, but look different (checkboxes and dl checkboxes) and it DEFINITELY doesn't make sense to have 2 components that look the same but do different things (dl checkboxes and radio buttons).

Additionally, as described in #8047, using a custom render function to make the actually checkboxes look like checkboxes has bugs, so that's extra not great. 

Either fix the custom render function... or better yet, make the checkboxes look like checkboxes.

**Comment by jdhuntington** [comment]
I will dig into #8047 and see what I can do there. Also tagging @betrue-final-final in case he has comments on the specific design.

**Comment by KevinTCoughlin** [comment]
> I will dig into #8047 and see what I can do there. Also tagging @betrue-final-final in case he has comments on the specific design.

@jdhuntington, you _may_ find the following useful https://github.com/OfficeDev/office-ui-fabric-react/issues/9598#issuecomment-511618122.

**Comment by jdhuntington** [comment]
@cc0rk There's a workaround for the custom render function at https://github.com/OfficeDev/office-ui-fabric-react/issues/8047#issuecomment-521003228 . Let's keep this issue open to discuss the design question though.

**Comment by cc0rk** [comment]
Thanks @jdhuntington!
