### ISSUE TITLE
Scroll bar of ScrollablePane is missing on Excel task-pane

### ISSUE THREAD

**Issue by mm90849491** [OfficeDev/office-ui-fabric-react#10074]
### Environment Information

- **Package version(s)**: "office-ui-fabric-react": "^7.10.0"
- **Browser and OS versions**: Windows 10 (ver. 1903) & Excel 365 (ver. 1907)

### Please provide a reproduction of the bug in a codepen:
I put your documentation page (https://developer.microsoft.com/en-us/fabric#/controls/web/scrollablepane) in Excel, and the following screen-shot is the result:
![2019-08-06 13_09_26-](https://user-images.githubusercontent.com/10732375/62574627-c7777c80-b84d-11e9-9128-256ff0f3e6f4.png)

It does not behave exactly like my problem, but sufficient enough to show there are some problems when the component is rendered inside Excel, such as: missing horizontal scroll bar,  Sticky component is covering the vertical scroll bar.
The only different is my ScrollablePane is inside of a Modal, with
```
        styles={{
          root: {
            boxSizing: 'border-box',
            padding: '12px'
          },
          main: {
            width: '100%',
            height: '100%'
          },
        }}
```
This problem only presents inside of Excel with Edge, the component works perfectly fine even inside Excel with IE and all browsers (including Edge) shown in following screen-shot:
![2019-08-06 11_36_33-Win10_Office2016 on WRK-IT-156 - Virtual Machine Connection](https://user-images.githubusercontent.com/10732375/62575348-6650a880-b84f-11e9-8387-1cd786c06efd.png)

#### Actual behavior:
Vertical scroll bar is missing in Excel with Edge.

#### Expected behavior:
Vertical scroll bar shall present.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Office JS Add-ins

**Comment by jdhuntington** [comment]
Hi @mm90849491 - thanks for reporting this issue. Unfortunately we're not able to help with office add-ins in this repo. If you can recreate this same issue in a standalone context (such as in codepen) I'm more than happy to take a look though!

**Comment by mm90849491** [comment]
Hi @jdhuntington , thank you for the reply. I understand the problem is more of Excel's team's responsibility, as it only happens in a specific version of Excel. I was hopping there is a little chance you guys know the setup of embedded browser of Excel and can tweak it.
I guess I will report to Office.JS repo and see if they want to investigate this thing.
