### ISSUE TITLE
Facepile control is throwing color contrast is not sufficient

### ISSUE THREAD

**Issue by abheyhanda** [OfficeDev/office-ui-fabric-react#10084]
### Environment Information

- **Package version(s)**: 6.190.1
- **Browser and OS versions**: chrome  76.0.3809.87 and windows 10
- **Screen reader(s)**: using keros chrome extension

### Describe the issue:

To repro the issue we can use chrome extension KEROS and its quick fast pass options
When you run the tool, for facepiles we are given issues related to contrast ratio in it.
One of the example color for which its thrown is 00aba9, 99b433, 2D89EF  

#### Actual behavior:

Color contrast not sufficient error is thrown via keros tool

#### Expected behavior:

Color contrast error should not be thrown

**Comment by jdhuntington** [comment]
Thanks for the report @abheyhanda . Are you able to share the specific context in which you saw this issue? I ran a report against https://fabricweb.z5.web.core.windows.net/oufr/7.21.0/#/examples/facepile (the most recent version of the facepile) and see no warnings about the control itself.

**Comment by abheyhanda** [comment]
We are using version # 6.190.1 which has these colors, some sample like 00aba9, 99b433, 2D89EF. 
In latest versions have new set of colors so the issue might is not reproing on those. 

Can we back port the new colors to #6 or atleast fix the colors which cause contrast issue?

**Comment by jdhuntington** [comment]
Opened #10139 with the requested change; want to sync with designers first and make sure this doesn't violate any promises with the theme shipped in v6.

Alternatively, is there anything blocking you from upgrading to 7?

**Comment by abheyhanda** [comment]
We are close to our planned release and changing a major version at this stage, may bring up more issues. So we need the fix in version 6 for now.

We would later have plan to upgrade fabric version in our product

**Comment by micahgodbolt** [comment]
seems this didn't close properly
