### ISSUE TITLE
Panels: how to display panels side by side

### ISSUE THREAD

**Issue by taranlabana** [OfficeDev/office-ui-fabric-react#10099]
Hi, I am looking for a way to show two panels side by side. 
the first panel opens from right. and on click of a button, the 2nd panel opens on the left of 1st.

The following pic should make it clear:
![image](https://user-images.githubusercontent.com/41966566/62735168-95eee480-b9f8-11e9-9862-1f276bef0a56.png)

Can you please suggest a way to implement it using fabric react panel?

**Comment by jdhuntington** [comment]
Hi @taranlabana - thanks for the question. I'm afraid the Panel control isn't built to be used side-by-side. There are several decisions made in the styling that depend on only 1 panel existing (most of these relate to smaller screen sizes, eg for phones).

It might be possible to use the `Overlay` control that Fabric exports and create your own that would accommodate your design, but unfortunately would require a fair bit of work to get the look and feel in place.
