### ISSUE TITLE
[DetailsList]: Extra column div added when selection mode set as none because of which Aria announces wrong column header for contents.

### ISSUE THREAD

**Issue by akashperfect** [OfficeDev/office-ui-fabric-react#1011]
### Bug Report

- __Package version(s)__: 1.9.0
- __Browser and OS versions__: Internet Explorer, Windows 10
- __Narrator__: Windows 10 Narrator

#### Describe the issue:

[DetailsList]: On providing SelectionMode parameter in DetailsList as SelectionMode.none. An extra div is still added (maybe corresponding to the selection tick) with role as columnHeader. 

Problem because of that is:
* Narrator announcement of column headers for each cell is shifted by one. 

As given in the image example, the narrator says contents of column **_key_** but says the column header as **_thumbnail_** and so on for rest of the columns.
ColumnHeader being read for any cell content is that of previous column.

#### Actual behavior:
On setting Selection Mode as None, the extra div is getting added.
(The highlighted div is the extra div getting added)

#### Expected behavior:
On setting Selection Mode as None, the extra div shouldn't be added.

### Code example used:

``` typescript
public render() {
    let { items, selectionDetails } = this.state;

    return (
      <div>
        <div>{ selectionDetails }</div>
        <TextField
          label='Filter by name:'
          onChanged={ text => this.setState({ items: text ? _items.filter(i => i.name.toLowerCase().indexOf(text) > -1) : _items }) }
        />
        <MarqueeSelection selection={ this._selection }>
          <DetailsList
            items={ items }
            setKey='set'
            selectionMode={ SelectionMode.none }
            selectionPreservedOnEmptyClick={ true }
            onItemInvoked={ (item) => alert(`Item invoked: ${item.name}`) }
            onRenderItemColumn={ this._onRenderItemColumn }
          />
        </MarqueeSelection>
      </div>
    );
  }
```

![image](https://cloud.githubusercontent.com/assets/2953096/23014001/28cdc2a8-f453-11e6-9368-5d265e04b4bf.png)

**Comment by sulabh-msft** [comment]
Any updates on this?

**Comment by gitjain** [comment]
Closing the issue and updates has been merged.
