### ISSUE TITLE
Pivot Control not following Microsoft guidelines for navigation (Responsiveness Issue)

### ISSUE THREAD

**Issue by SumitKanchan4** [OfficeDev/office-ui-fabric-react#10110]
Hi,

As per the guidelines by Microsoft on https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/navigationview

Pivot control is not responsive and following the guidelines. As I can see in the examples as well these are not responsive.

### Environment Information

- SharePoint Online
- Using in SPFx with version "office-ui-fabric-react": "6.143.0",

### Please provide a reproduction of the bug in a codepen:
 
```sh
 <div className={styles.grid}>
            <div className={styles.row}>
              <div className={`${styles.tabHeader}`}>
                {
                  <Pivot headersOnly={true} onLinkClick={(item) => this.tabClicked(item)} selectedKey={this.state.selectedTab}>
                    {
                      Object.keys(tabInfo).map(name => (
                        <PivotItem key={`pivotItemKey_${name}`} style={{ backgroundColor: 'aliceblue' }} headerText={tabInfo[Number(name)].title} itemKey={tabInfo[Number(name)].guid} ></PivotItem>
                      ))
                    }
                    {
                      this.props.isEditMode ?
                        <PivotItem itemKey={TabConstants.ADD_TAB_GUID} itemIcon={`BoxAdditionSolid`} title={`Add new tab`} ></PivotItem>
                        :
                        <div></div>
                    }
                  </Pivot>
                }
              </div>
            </div>
          </div>
```

#### Actual behavior:

No responsiveness of the control in the different screen size

#### Expected behavior:

Should be responsive and adjust by itself in the different screen size

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: Blocking

Products/sites affected: (if applicable)

![image](https://user-images.githubusercontent.com/26162613/62776047-1b40ca80-bac7-11e9-9ebd-65a21539307a.png)

**Comment by SumitKanchan4** [comment]
Code:

 <div className={styles.grid}>
            <div className={styles.row}>
              <div className={`${styles.tabHeader}`}>
                {
                  <Pivot headersOnly={true} onLinkClick={(item) => this.tabClicked(item)} selectedKey={this.state.selectedTab}>
                    {
                      Object.keys(tabInfo).map(name => (
                        <PivotItem key={`pivotItemKey_${name}`} style={{ backgroundColor: 'aliceblue' }} headerText={tabInfo[Number(name)].title} itemKey={tabInfo[Number(name)].guid} ></PivotItem>
                      ))
                    }
                    {
                      this.props.isEditMode ?
                        <PivotItem itemKey={TabConstants.ADD_TAB_GUID} itemIcon={`BoxAdditionSolid`} title={`Add new tab`} ></PivotItem>
                        :
                        <div></div>
                    }
                  </Pivot>
                }
              </div>
            </div>
          </div>

**Comment by jdhuntington** [comment]
Hi @SumitKanchan4 - thanks for the issue!
You're right that the pivot control is not responsive. We are tracking this issue at #4066 , though unfortunately it's not in active development at the moment.
If the current behavior of the pivot is blocking, I would recommend detecting when the screen size changes below the threshold you are interested in and swap to another style of component at that point. Sorry I don't have a better answer for the immediate term!
