### ISSUE TITLE
No margin being applied to Pivot text (with Icon)

### ISSUE THREAD

**Issue by martellaj** [OfficeDev/office-ui-fabric-react#10114]
### Environment Information

- **Package version(s)**: 7.22.1

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/jdh-msft/pen/EqdPoK?&editable=true (link fixed)

#### Actual behavior:
No spacing between icon and label for Pivot component.

#### Expected behavior:
Spacing between icon and label for Pivot component.

### Priorities and help requested:

Are you willing to submit a PR to fix? No (not sure the right fix)

Requested priority: Medium (I checked in a mitigation into OWA)

Products/sites affected: OWA

**Comment by martellaj** [comment]
Offending change: https://github.com/OfficeDev/office-ui-fabric-react/commit/7f9f9ee1a7984a98a4a65c5f1eec392a4e1946ff#diff-4714de560076bfda4e0b0272d915f1ad

**Comment by jdhuntington** [comment]
@martellaj Thanks for reporting! Looks like your codepen link didn't come through -- are you seeing the same things as this codepen? https://codepen.io/jdh-msft/pen/EqdPoK?&editable=true

**Comment by martellaj** [comment]
@jdhuntington Woops. Yep, your link is the right one. Note how there's no spacing between the icon and the text.

**Comment by dzearing** [comment]
It seems like our screener tests don't validate this. We need to make sure they do.
