### ISSUE TITLE
Deprecations warnings in React 16.9

### ISSUE THREAD

**Issue by Renive** [OfficeDev/office-ui-fabric-react#10128]
### Environment Information

- **Package version(s)**: (latest, v7)
- **Browser and OS versions**: (fill this out if relevant)

### Describe the issue:

React 16.9 introduced new warnings if you use deprecated methods -  https://reactjs.org/blog/2019/08/08/react-v16.9.0.html

Using Fabric UI components cause spam of those warnings. Those lifecycle methods are used in most of the components in this toolkit.

#### Actual behavior:

Lots of warnings about incompatibility and unability work in React 17.

#### Expected behavior:

No warnings, deprecations taken care of.

**Comment by JasonGore** [comment]
We do have plans to eventually remove these methods and have already started as documented in #8743. I believe that issue should be reopened and I'm looking into it.

However, these warnings only occur when using React in development mode and should not impact production mode usage as [this CodePen](https://codepen.io/jasongore/pen/mNNjZM) shows.

**Comment by JasonGore** [comment]
The actual issue is #4613.

**Comment by JasonGore** [comment]
As an interim fix I think we can do a find-replace to `UNSAFE_` in the Fabric repo to minimize warnings for end users.

**Comment by Renive** [comment]
If you want, in my link ( https://reactjs.org/blog/2019/08/08/react-v16.9.0.html ) there is a code mod to do exactly that. Just need to do npx react-codemod rename-unsafe-lifecycles in project. But that way there is less pressure to modernize the framework. :P

**Comment by JasonGore** [comment]
Yep, that is exactly the codemod I'm using now. We fully intend on always adapting and removing deprecated features and have #4613 open to do just that. I think it's also worthwhile doing this interim codemod step to reduce the noise for end users in the interim.

**Comment by Kesshi** [comment]
Just found a warning that is raised from the Nav component. It would be nice if this could be fixed also.
>  Warning: A future version of React will block javascript: URLs as a security precaution. Use event handlers instead if you can. If you need to generate unsafe HTML try using dangerouslySetInnerHTML instead. React was passed "javascript:".

**Comment by JasonGore** [comment]
If you see anything else related to deprecated React methods please feel free to add it to #4613.
