### ISSUE TITLE
Allow TextField errorMessage field to remain aways in DOM to avoid Flickering Effect

### ISSUE THREAD

**Issue by ashitvora** [OfficeDev/office-ui-fabric-react#10124]
#### Describe the feature that you would like added
Currently, errorMessage property adds a span with an error message if something is set in the error messages property otherwise removes it from the DOM causing a flickering error. It would be nice to have the element in the DOM always to avoid such an annoying effect.

#### What component or utility would this be added to
All Input components like TextField, TextArea, etc

#### Have you discussed this feature with our team, and if so, who
No

#### Additional context/screenshots
None

**Comment by JasonGore** [comment]
I'm not sure what you mean by `flickering error`. Do you mean the error message should take up space in the DOM, even when not present?

**Comment by ashitvora** [comment]
Oops! I meant, flickering effect.
And yes, that's what I meant - error message should take up DOM even when not present. Of at least have an option to get that behavior.

**Comment by JasonGore** [comment]
I chatted a bit with @betrue-final-final about this issue. Our best practices around components and `TextField` is to conserve space wherever possible. Also, there is metadata and accessibility information contained within the error message, so making it part of the DOM when it does not having meaningful information will introduce other issues.

I think in this case if you have a requirement to preserve this extra DOM space, the best option is to make your own custom variant of TextField that puts it in a fixed container that preserves space for the error message.
