### ISSUE TITLE
Inconsistent link hover behavior in Breadcrumb

### ISSUE THREAD

**Issue by atneik** [OfficeDev/office-ui-fabric-react#10138]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/atneik/pen/JjPGZzY

Items with no link (no `onClick`), behave differently when collapsed as compared to not collapsed.

#### Actual behavior:

When `onClick` is not defined in an item of Breadcrumb, the hover behavior of item is different when collapsed vs when not collapsed. 

#### Expected behavior:

 The hover behavior should be same. It should follow the not collapsed behavior, i.e. no cursor change or background color change in Dropdown upon hover when `onClick` is not defined.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: SharePoint

**Comment by JasonGore** [comment]
I chatted with @atneik to verify that this is an issue with the component against its Fluent design spec. I will triage as a bug.

**Comment by ecraig12345** [comment]
I finally looked into this and there are a couple possible ways to fix it, but neither is great.

When generating the menu items, for "non-actionable" ones, we can do one of the following:

1. Set `disabled` on the menu item, then set the text color back to `bodyText` instead of `disabledBodyText` using `itemProps.styles`
  - Advantages:
    - item is not clickable by mouse or keyboard
    - fewer things to override
  - Disadvantages:
    - screen reader announces "disabled" for item
    - `rootDisabled` overrides aren't mixed in properly, so we have to manually override using `.is-disabled` instead

2. Set `itemProps.styles` to disable the focus, active, and pointer events styles
  - Advantages:
    - screen reader doesn't announce anything extra for item
  - Disadvantages:
    - item is still "clickable" with keyboard
    - more styles to override
    - `rootHovered` and `rootPressed` overrides aren't mixed in properly, so we have to manually override `:hover` and `:active` instead

3. Gross things involving adding even more `IContextualMenuItem` props :( :( :(

I'm kind of inclined to go with #1 but open to input.

Here's the code for the two main options:

```tsx
const nonActionableItemProps: Partial<IContextualMenuItemProps> = {
  styles: props => {
    const { theme } = props;
    return {
      root: {
        // Option 1
        selectors: {
          '.is-disabled': {
            color: theme.semanticColors.bodyText
          },
        },
        // Option 2
        pointerEvents: 'none',
        selectors: {
          ':hover, :active': {
            color: theme.semanticColors.bodyText,
            backgroundColor: 'transparent'
          }
        }
      }
    };
  }
};

// When generating overflow items
const contextualItems = renderedOverflowItems.map((item): IContextualMenuItem => {
  const isActionable = !!(item.onClick || item.href);
  return {
    // old props
    ...
    // Both
    // The item should not have hover styles if clicking it wouldn't do anything (per design)
    itemProps: isActionable ? undefined : nonActionableItemProps,
    // Option 1
    disabled: !isActionable
  };
});
```
