### ISSUE TITLE
Spin button labels don't align vertically with other control types

### ISSUE THREAD

**Issue by HarryGifford** [OfficeDev/office-ui-fabric-react#10132]
### Environment Information

- **Package version(s)**: 7.22.1
- **Browser and OS versions**: Chrome 76.0.3809.100 (Official Build) (64-bit), Windows 10.

### Please provide a reproduction of the bug in a codepen:

Go to https://codepen.io/hegi/pen/OKBMRv and observe the alignment.

#### Actual behavior:

The alignment of the Spin Button is a couple of pixels out of alignment with other fields.

#### Expected behavior:

Alignment should match.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable)

The alignment was mostly fixed by #10015 but not entirely.

**Comment by HarryGifford** [comment]
I should clarify that the vertical alignment is the issue, not the horizontal alignment.

**Comment by JasonGore** [comment]
Yep, I can see it. Thanks for the CodePen!

![image](https://user-images.githubusercontent.com/26070760/62896572-2f263f80-bd06-11e9-876f-556a8263942f.png)

**Comment by JasonGore** [comment]
@marygans noticed this while working on the other issue and was seeking design input. She offered to take this one over. Thanks!
