### ISSUE TITLE
MessageBar: React Warning

### ISSUE THREAD

**Issue by fantua** [OfficeDev/office-ui-fabric-react#1014]
### Bug Report

- __Package version(s)__: latest

#### Describe the issue:

Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the MessageBar component.

While using setTimeout in componentDidMount you need to cancel it in componentWillUnmount.

**Comment by dzearing** [comment]
This component is missing `BaseComponent` extends, and needs to use this._async.setTimeout. This will auto cancel.

**Comment by dzearing** [comment]
Thanks @fantua. If you would like to submit a PR, it's a very simple fix. (looking for more contributors!) :)

**Comment by fantua** [comment]
@dzearing ok :)

**Comment by fantua** [comment]
@dzearing can you take a look at my PR?
