### ISSUE TITLE
Referencing child elements within the mergeStyleSets scope failed

### ISSUE THREAD

**Issue by x73x63** [OfficeDev/office-ui-fabric-react#10144]
### Please provide a reproduction of the bug in a codepen:
[https://codepen.io/x73x63/pen/GRKoeBX?editors=0010](https://codepen.io/x73x63/pen/GRKoeBX?editors=0010)

#### Expected behavior:
[Reference wiki](https://github.com/OfficeDev/office-ui-fabric-react/wiki/mergeStyles#referencing-child-elements-within-the-mergestylesets-scope) 
when the parent is hovered, change the background of the child element to blue.

#### Actual behavior:
Failed

**Comment by JasonGore** [comment]
The wiki is out of date. Using this method is deprecated and has recently been removed. [This is the current recommended method.](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/merge-styles/README.md#referencing-child-elements-within-the-mergestylesets-scope)

I've [updated your CodePen](https://codepen.io/jasongore/pen/QWLNwev) to show the recommend method.

I will resolve this issue by updating the wiki. Thanks for reporting!
