### ISSUE TITLE
Question: How do I view the @uifabric/experiments demo app?

### ISSUE THREAD

**Issue by bt-88** [OfficeDev/office-ui-fabric-react#10158]
Can I view the @uifabric/experiments demo app somewhere online?

Or can I perhaps build the repository on my machine? If yes, how?

(Perhaps, we can add this information to the readme page on @uifabric/experiements)

**Comment by x73x63** [comment]
1. git clone https://github.com/OfficeDev/office-ui-fabric-react.git
2. cd packages/experiments
3. npm install && npm start

**Comment by bt-88** [comment]
`npm install` returns the following error:

```
600 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/@uifabric%2fbuild - Not found
600 verbose stack     at res.buffer.catch.then.body (C:\Users\Bas\AppData\Roaming\npm\node_modules\npm\node_modules\npm-registry-fetch\check-response.js:104:15)
600 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
601 verbose statusCode 404
602 verbose pkgid @uifabric/build@^7.0.0
603 verbose cwd C:\repos\office-ui-fabric-react\packages\experiments
604 verbose Windows_NT 10.0.18362
605 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Bas\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
606 verbose node v10.4.1
607 verbose npm  v6.10.2
608 error code E404
609 error 404 Not Found - GET https://registry.npmjs.org/@uifabric%2fbuild - Not found
610 error 404
611 error 404 '@uifabric/build@^7.0.0' is not in the npm registry.
612 error 404 You should bug the author to publish it (or use the name yourself!)
613 error 404 It was specified as a dependency of 'experiments'
614 error 404 Note that you can also install from a
615 error 404 tarball, folder, http url, or git url.
616 verbose exit [ 1, true ]
```

**Comment by cliffkoh** [comment]
Can you try using `yarn install`? I'm not sure if we actually support `npm install` (@jdhuntington  or @ecraig12345 , do you know?)

**Comment by JasonGore** [comment]
Fabric recently [switched over to yarn](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Build-Commands) for building.

The commands are:
1. git clone https://github.com/OfficeDev/office-ui-fabric-react.git
1. [yarn](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Build-Commands#yarn-install)
1. [yarn buildto experiments](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Build-Commands#yarn-buildto)
1. cd packages/experiments
1. yarn start

**Comment by bt-88** [comment]
Hmm, this isn't working. See the output below.

```
c:\repos\office-ui-fabric-react>yarn buildto experiments
yarn run v1.17.3
$ node ./scripts/monorepo/buildTo.js experiments
c:\repos\office-ui-fabric-react\scripts\monorepo\getAllPackageInfo.js:12
    .toString()
     ^

TypeError: Cannot read property 'toString' of null
    at getAllPackageInfo (c:\repos\office-ui-fabric-react\scripts\monorepo\getAllPackageInfo.js:12:6)
...
```

Which refers to 'getAllPackageInfo.js':

```
const { spawnSync } = require('child_process');
const { readConfig } = require('../read-config');
const path = require('path');
const findGitRoot = require('./findGitRoot');

module.exports = function getAllPackageInfo() {
  const gitRoot = findGitRoot();
  const results = spawnSync('git', ['ls-tree', '-r', '--name-only', '--full-tree', 'HEAD']);
  const packageInfo = {};

  results.stdout
    .toString()
```

**Comment by JasonGore** [comment]
Which version of Node do you have installed?

`node --version`

**Comment by bt-88** [comment]
> Which version of Node do you have installed?
> 
> `node --version`

v10.4.1

**Comment by JasonGore** [comment]
Actually I realized I missed a step, `cd office-ui-fabric-react` (edited comment above.) You have to run all of the commands from inside the repo after cloning. Can you confirm that's where you're running the commands from? Thanks.

**Comment by JasonGore** [comment]
Actually I see that you are. I'm thinking `findGitRoot` may be failing here but I will need @kenotron to help figure out why.

**Comment by kenotron** [comment]
@bt-88 - not sure about what the exact issue is with build. However, to answer your original question, you can reach a master copy of the exp site here:

http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/experiments/dist/index.html

**Comment by ecraig12345** [comment]
I've successfully used the experiments demo app recently, so I'm not sure why it wouldn't work for you. This is the full series of steps:
```
git clone <url>
cd office-ui-fabric-react
yarn
yarn buildto experiments
cd packages/experiments
yarn start
```

**Comment by kenotron** [comment]
> Can you try using `yarn install`? I'm not sure if we actually support `npm install` (@jdhuntington JD Huntington FTE or @ecraig12345 Elizabeth Craig FTE , do you know?)

`npm install` was supposed to error out but with an error message telling you to use yarn if this is the master branch. Not sure what the state of your repo is at this point. I'd recommend you to just use the URL I gave for experiment site as a reference.

**Comment by ecraig12345** [comment]
We should potentially also have a script for helping clean up people's repos that are in a bad state--normally I'd say just commit/stash any changes then run (from the root) `git clean -fdx`, but that has bad results if there are any symlinks hanging around from `rush link`.

**Comment by bt-88** [comment]
> @bt-88 - not sure about what the exact issue is with build. However, to answer your original question, you can reach a master copy of the exp site here:
> 
> http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/heads/master/experiments/dist/index.html
> 
> If this answers your question, feel free to close this issue.

Thanks a bunch.
