### ISSUE TITLE
PeoplePicker: items in suggestion list has a blank area under each item in IE

### ISSUE THREAD

**Issue by MirandaGe** [OfficeDev/office-ui-fabric-react#1015]
### Bug Report

- __Package version(s)__: any
- __Browser and OS versions__: IE11

#### Describe the issue:

1. open PeoplePicker in IE 11
2. input something to make suggestion list show

#### Actual behavior:

In chrome, suggested items are like:
![image](https://cloud.githubusercontent.com/assets/16030290/23029320/0bcd15da-f4a5-11e6-9cdb-70726bec67d2.png)
while in IE, the suggestion items are:
![image](https://cloud.githubusercontent.com/assets/16030290/23029362/3964c754-f4a5-11e6-99df-10578460ccbc.png)

#### Expected behavior:

I prefer the chrome one

### If applicable, please provide a codepen repro:

http://codepen.io/lingge/pen/MJBzjG

try the demo page: https://dev.office.com/fabric#/components/peoplepicker is the same.

**Comment by micahgodbolt** [comment]
Great detail on this issue @MirandaGe - Looks like a simple "padding on buttons" issue. I'll whip up a fix.
