### ISSUE TITLE
Picker Border color issue

### ISSUE THREAD

**Issue by sampascal** [OfficeDev/office-ui-fabric-react#10153]
### Environment Information

- **Package version(s)**: (fill this out)
Latest version, the issue persists on Fabric documentation as well
- **Browser and OS versions**: (fill this out if relevant)
Chrome, Win10

#### Actual behavior:

When adding items to the picker, the bottom border will display a different color (or different weight) with the unfilled border. It would be nice if it can be fixed to be the same color /weight.

#### Expected behavior:

Filled area should have the same color/weight with unfilled area.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by joschect** [comment]
@sampascal Could you clarify which picker you're referring to? And if possible provide a screenshot? I tested and wasn't able to get what I saw as a repro.

**Comment by sampascal** [comment]
@joschect 
![pickerColor](https://user-images.githubusercontent.com/5790129/63062033-3be49800-beac-11e9-8a91-7690b29b87ec.JPG)

**Comment by joschect** [comment]
@sampascal I can reproduce this, it seems to be related to screen dpi. There are some screens where it does not reproduce.

**Comment by joschect** [comment]
@sampascal it also seems to be related to the browser as I cannot reproduce it using safari.

**Comment by sampascal** [comment]
ok, I am using Chrome and win10, screen resolution is 3840*2160.

Do you think you can fix this issue so that all browsers and dpi can see the same correct picker? 

Thanks!

**Comment by dzearing** [comment]
@joschect I can repro on my 4k monitor. It's certainly a dpi chrome thing. I was able to work around it by assigning `background: transparent` to the input element.

Current:
![image](https://user-images.githubusercontent.com/1110944/63486633-344d6200-c45d-11e9-8dda-7fc34f2c3f55.png)

With transparent bg;
![image](https://user-images.githubusercontent.com/1110944/63486658-4c24e600-c45d-11e9-8486-5927eddb4bea.png)
