### ISSUE TITLE
Add new icon for School Data Sync

### ISSUE THREAD

**Issue by v-sole** [OfficeDev/office-ui-fabric-react#10157]
Hi, I work with O365 Admin team, we're using a lot of Fabric icons. We have a client School Data Sync that has a specific Icon that I need to show along with other Fabric icons. I just have a png file but it'd be great to be able to use from Fabric library. I've attached the icon. The person to reach out for more detail is Amisha(amisha@microsoft.com) or Venkat(Venkat.Narayanan@microsoft.com). Thank you
![schoolDataSyncIcon](https://user-images.githubusercontent.com/54126448/63066984-a81dc680-bec1-11e9-89d9-ebe9634e82d6.png)

**Comment by cliffkoh** [comment]
Please reach out to @Jahnp offline!
