### ISSUE TITLE
Controlled TextField component not accepting same (one character) input after clearing it

### ISSUE THREAD

**Issue by szmarci** [OfficeDev/office-ui-fabric-react#10182]
### Environment Information

- **Package version(s)**: 7.25.0
- **Browser and OS versions**: Chrome (latest)

### Please provide a reproduction of the bug in a codepen:

codesandbox reproduction:
[https://codesandbox.io/embed/nice-kirch-rldpx](https://codesandbox.io/embed/nice-kirch-rldpx)

#### Actual behavior:

When typing one character to the (controlled) input field and then hitting the button (recording the input value to an array and clearing it) the same character cannot be typed again into the field.

1. type the letter `a` to the input
2. hit record button
3. type the letter `a` to the input

#### Expected behavior:

Expected it to be the same behaviour as before clearing the input field.

**Comment by kenotron** [comment]
There is a bug in the intricate interaction with the `_lastChangeValue` member. @ecraig12345 knows most about this, so I'm assigning to her.
