### ISSUE TITLE
IconButton has fixed width which breaks contextual icon buttons

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#10191]
### Environment Information

- **Package version(s)**: (current)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/micahgodbolt/pen/YzKGxJv?editors=0010

![image](https://user-images.githubusercontent.com/1434956/63304995-07048680-c29a-11e9-91ec-2f02252d6eb5.png)

#### Actual behavior:

Button width is fixed to 32px

#### Expected behavior:
Button width should flex to fit contents

**Comment by kelseyyoung** [comment]
Was replacing width with min-width really the best fix here? Now all of our IconButtons (e.g. in ComboBoxes) are 32px because we hadn't overridden the min-width property...(after bumping to 7.27.1)

**Comment by micahgodbolt** [comment]
ComboBox seems to be working fine with this style change. Are you seeing any issues?

![image](https://user-images.githubusercontent.com/1434956/63620780-1e4bb880-c5a7-11e9-8473-fb28bff72ceb.png)

![image](https://user-images.githubusercontent.com/1434956/63620793-2572c680-c5a7-11e9-9ad1-66f41acf7321.png)

**Comment by kelseyyoung** [comment]
It's just for anyone wanting to override that style. Previously if you wanted to make it smaller you'd set the width property. Now however you have to set the min-width as well.

https://codepen.io/kelseyyoung/pen/PoYWLdz

Changing styling is part of using Fabric, but what I'm really asking if this was the -best- option given the issue (or least intrusive)

**Comment by micahgodbolt** [comment]
I believe a fixed width on the IconButton to be a bug. All other buttons are min width, and will scale to fit their content. I believe our problem was that we didn't give devs an easy way to change button width that wouldn't break if we needed to change something. That's the idea behind component tokens.

**Comment by kelseyyoung** [comment]
Alrighty, thanks for the explanation
