### ISSUE TITLE
Buttons should be right aligned in Teaching Callouts

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#10193]
We've had a coherence change where we are right aligning all buttons in callouts, dialogs and panels.
![image](https://user-images.githubusercontent.com/20363037/63306211-86945480-c29e-11e9-9347-436df75709db.png)

Teaching callouts still have left aligned buttons
![image](https://user-images.githubusercontent.com/20363037/63306245-a88dd700-c29e-11e9-9255-1e7e24ce0e02.png)

**Comment by kenotron** [comment]
@betrue-final-final - please look at this PR for the change: https://github.com/OfficeDev/office-ui-fabric-react/pull/10206
