### ISSUE TITLE
Color picker shows nothing instead of zero for channels being zero

### ISSUE THREAD

**Issue by reli-msft** [OfficeDev/office-ui-fabric-react#10195]
To reproduce:

- Create a color picker.
- Set color to black.
- "Red", "Green" and "Blue" channels shows empty. Correct value should be `0`.

![image](https://user-images.githubusercontent.com/50213618/63308473-b4ca6200-c2a7-11e9-877a-a1ad20d1ab0f.png)

**Comment by reli-msft** [comment]
The following code in ColorPickerBase.ts doesn't properly process `0` value for color components.

```ts
  private _getDisplayValue(component: keyof IColor): string {
    const { color, editingColor } = this.state;
    if (editingColor && editingColor.component === component) {
      return editingColor.value;
    }
    return String(color[component] || '');
  }
```

**Comment by kenotron** [comment]
@ecraig12345 - since you pinged offline to take this, here ya go :)
