### ISSUE TITLE
React "javascript:" warning using Nav component

### ISSUE THREAD

**Issue by Kesshi** [OfficeDev/office-ui-fabric-react#10201]
Using the forceAnchor option of the Nav component results in the follwing react warning:

> Warning: A future version of React will block javascript: URLs as a security precaution. Use event handlers instead if you can. If you need to generate unsafe HTML try using dangerouslySetInnerHTML instead. React was passed "javascript:".

Moved to separate issue from: https://github.com/OfficeDev/office-ui-fabric-react/issues/4613#issuecomment-522421471

### Environment Information

- **Package version(s)**:
  - office-ui-fabric-react 7.25.0
  - react 16.9.0

### Please provide a reproduction of the bug in a codepen:
https://jsfiddle.net/n7hu5yLo/

#### Actual behavior:

React shows a warning

#### Expected behavior:

React should not show a warning

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority:  Normal

**Comment by kenotron** [comment]
I think we can replace this with `href="#"` and an onclickhandler, but not sure if that's the best strategy. Alternatively we can generate this html bit with the "dangerouslySetInnerHTML" prop.
