### ISSUE TITLE
upgrade to office-ui-fabric-react v 7.25.1 I get Uncaught SyntaxError: Unexpected token export in app.build.js

### ISSUE THREAD

**Issue by bhedayatian** [OfficeDev/office-ui-fabric-react#10217]
after upgrading to the new office-ui I get this error in the console:
Uncaught SyntaxError: Unexpected token export in app.build.js

it happens on this line:

/***/ (function(module, exports) {

	export * from './components/MessageBar/index';
	//# sourceMappingURL=MessageBar.js.map

**Comment by kenotron** [comment]
The root cause is the same as #10215
