### ISSUE TITLE
Scrolling <List> with the keyboard stops if no item is selected

### ISSUE THREAD

**Issue by kokuda** [OfficeDev/office-ui-fabric-react#10228]
### Environment Information

- **Package version(s)**: 6
- **Browser and OS versions**: Chrome 75.0.3770.142 Windows 10 (does not occur on Edge)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/kokuda/pen/VwZmxBM?editors=1111

#### Actual behavior:

* Create a List component inside of a scrollable container
* Add enough items in the list to create many pages to scroll
* Scroll down a few pages (this is important since the List component always keeps the first page loaded so the bug will not happen on the first page)
* Click on an unselectable area (either an item or space between items) to give it focus.
* Use the arrow keys on the keyboard (or PgUp/PgDown) to scroll up or down.
* After a short time, the page will stop scrolling.

This appears to be due to the fact that the item or page of items that you click on will be unloaded as you scroll away from it.  The focus appears to go to the body when the focused item is deleted, so it is no longer within the scrollable container and scrolling stops.

#### Expected behavior:

When scrolling with the keyboard you should be able to continue to the top or bottom of the page.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal - This is almost an accessibility issue since it involves scrolling with the keyboard, however you must first click with the mouse, so it isn't clear what the priority might be.

Products/sites affected: (if applicable)

**Comment by kenotron** [comment]
Okay I couldn't repro this on Mac, but is an issue with Windows. It is a timing issue I think...

**Comment by kokuda** [comment]
Lol.  It was fixed with the Chome update I got just after I posted the issue.  We implemented an external workaround for this issue weeks ago (by forcing the focus to the parent component onClick), I just hadn't posted it until today.  Le sigh.

**Comment by kenotron** [comment]
Would you mind closing this one?
