### ISSUE TITLE
Breadcrumb render performance issues

### ISSUE THREAD

**Issue by andrezo** [OfficeDev/office-ui-fabric-react#10222]
### Environment Information

- **Package version(s)**: Latest
- **Browser and OS versions**: All

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/andrezo/pen/yLBVXep

Alternatively, go to [office.com](https://office.com) or your-tenant.sharepoint.com and issue a query that return mostly file results since file results are shown with a breadcrumb component containing various URL path parts.

![image](https://user-images.githubusercontent.com/26408269/63428987-2e359200-c419-11e9-8ea2-b9f5fcdf026c.png)

#### Actual behavior:

With profiling enabled, observe that the rendering time is dominated by the creation of breadcrumbs and a long chain of up to 15 _afterComponentRendered() handlers from ResizeGroupBase that blocks the first paint. Up to 50% of the total the rendering time on the search result pages are due to the breadcrumbs.

If you profile the codepen (or just put 15 breadcrumbs on a plain html page), you see the same behavior. Even on a high-end workstation, it takes 300-400ms before first paint. 

![image](https://user-images.githubusercontent.com/26408269/63428402-c6327c00-c417-11e9-896a-df7ab762c222.png)

#### Expected behavior:

1.  Creation of breadcrumbs should be much faster, at least half the current time so that they can be used in performance sensitive apps such as search result pages.
2. _afterComponentRendered() should run after render/first-paint. One possible fix is to do a setTimeout(_, 0) or another requestAnimationFrame inside the existing requestAnimationFrame handler so that the code runs after first render/paint.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: High

Products/sites affected: Search result pages on office.com and *.sharepoint.com

**Comment by kenotron** [comment]
Haven't looked at the code just yet but this looks like something needed to be placed inside a renderAnimationFrame or something... basically it sounds like spending enormous amount of time measuring width or something. I'm putting this on as a "bug" because this is really egregious perf

**Comment by kenotron** [comment]
We can't do first paint of that component without measurement as that's what ResizeGroup does for you... if you can forego the ellipsis, then I would think we can come up with a version of breadcrumb that doesn't do measurements - I think "afterComponentRendered" is a misnomer.. it is the rendering of the component inside an invisible measurement to see whether this item should be rendered or not.

If you can think of a pure CSS solution, perhaps that's the best way to tackle this - we should maybe have a really simple and fast version of breadcrumbs?

**Comment by kenotron** [comment]
This is a kind of solution but doesn't do the resizegroup thing where entire items are not rendered... just uses CSS to turn things into ellipses:

https://codepen.io/shippin/pen/YrwrYa 

Would that work?

**Comment by kenotron** [comment]
@jdhuntington - hey would you mind chiming in how we can maybe address the perf issue? I really think for a simple use case like the office.com, we should maybe avoid resizegroups maybe...

**Comment by andrezo** [comment]
I see that even the Fabric React documentation warns against using ResizeGroup in certain cases:

[resizegroup](https://developer.microsoft.com/en-us/fabric#/controls/web/resizegroup)
> This component queries the DOM for the dimensions of elements. Too many of these dimension queries will negatively affect the performance of the component and could cause poor interactive performance on websites. 

It would be good if there was a new prop on the Breadcrumb component that switches to a simpler/pure-CSS based solution if enabled. Alternatively, introduce a new separate Breadcrumb component.

If it makes more sense to just roll our own CSS-based breadcrumb and keep Fabric React as-is, please let us know.

**Comment by kenotron** [comment]
I would say you really should have max of 1 or 2 of these resize groups in your UI. If you find yourself in a list situation, I would think we should do something with CSS. The one I linked has a pretty good solution. Ideally we can keep this stuff in Fabric, we are definitely cool with accepting new components. I wonder if you can implement your own component in a way that can later be placed inside Fabric?

**Comment by andrezo** [comment]
Yes, we can probably start out by creating the component on our side and consider moving it into Fabric later.

**Comment by kenotron** [comment]
@andrezo - it isn't the best answer to leave you having to come up with a component but it seems to be the best course of action so far (love to have contrib!). Would you mind closing this issue when you get a chance? Otherwise, the bot will close it when it is stale and no action would be required.
