### ISSUE TITLE
DetailsList drop hints and the gripper bars displayed for all columns if reorder is enabled

### ISSUE THREAD

**Issue by ardallie** [OfficeDev/office-ui-fabric-react#10237]
### Environment Information

- **Package version(s)**: 7.25+ (incl. 7.27)
- **Browser and OS versions**: (fill this out if relevant) Win 10, Chrome, Firefox

### Please provide a reproduction of the bug in a codepen:
The issue can be observed in the demo provided with the official documentation. 
Is this working as intended? 

[https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/draganddrop ](https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/draganddrop )

#### Actual behavior:

Enabling the column reorder feature results in the markings displayed for every column. 

**Figure 1. Markings are displayed on every column.** 
![image](https://user-images.githubusercontent.com/25386097/63521435-54793180-c4ee-11e9-9c1f-dad950d47a3c.png)

After changing the position of a column, the drop hint icon for that column behaves as expected and appears on hover / during the drag and drop only. The gripper bar remains visible. (Figure 2)

**Figure 2. Drop hint for a "County" column behaves as expected after drag and drop**
![image](https://user-images.githubusercontent.com/25386097/63521525-84c0d000-c4ee-11e9-83d4-9ec6862283cf.png)

#### Expected behavior:

Markings should be visible on hover / during the drag and drop only
Thank you for looking into this.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) n/a

**Comment by KevinTCoughlin** [comment]
This is a bug possibly introduced by https://github.com/OfficeDev/office-ui-fabric-react/pull/10120 cc: @svaibhav @aditima. 

I didn't see this when reviewing the code but perhaps I used a different example. We'll have to take a look and fix it. The hints shouldn't _always_ be shown.

**Comment by kenotron** [comment]
@KevinTCoughlin - would you mind assigning to the person to address this issue?

**Comment by svaibhav** [comment]
@KevinTCoughlin While I was reviewing my changes, I found the following change:
https://github.com/OfficeDev/office-ui-fabric-react/pull/9884/files#diff-594035b9050cc429a57f0fceb24e63ba
Can this be because of this change? (using _display: 'inline-block'_ in Icon.styles.ts)

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin While I was reviewing my changes, I found the following change:
> https://github.com/OfficeDev/office-ui-fabric-react/pull/9884/files#diff-594035b9050cc429a57f0fceb24e63ba
> Can this be because of this change? (using _display: 'inline-block'_ in Icon.styles.ts)

It looks like this isn't related to any of our individual changes, but rather styles cascading from the "unified header" on the production documentation page.

![image](https://user-images.githubusercontent.com/706967/63548626-77eaaf00-c4e3-11e9-9a24-48173cc81c53.png)

cc: @micahgodbolt

**Comment by aditima** [comment]
Adding @Jahnp

**Comment by Jahnp** [comment]
To @KevinTCoughlin's point, this looks like the result of conflicts from `ms-Icon` definitions, one of which is in one of the external portals CSS (not technically UHF but also part of page infrastructure).

The second one stems from the copy of Fabric Core bundled with the site, invoked on this line: 
https://github.com/OfficeDev/office-ui-fabric-react/blob/6ff7873e60436513ce7c3e4f39982a461fa5c86f/apps/fabric-website/src/utilities/createSite.tsx#L135

I can repro this on the PR deploy page for the *website* in [this random build](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/10231/merge/fabric-website/dist/index.html?devhost#/controls/web/detailslist/draganddrop), though it doesn't repro for the *demo* site (inner loop).

Off the top of my head, options to fix include:
1.) Removing the bundled Fabric Core from the site, which likely has undesirable site-wide implications, AND asking the portals team to remove or scope their ms-Icon definition
2.) Adding overrides for this specific example

2 is probably easier though a bit grosser. 1 would take substantially more work and would likely have a ripple effect throughout the site. I'd suggest someone look at 2 as a short-term bugfix while 1 is investigated.

**Comment by svaibhav** [comment]
> > @KevinTCoughlin While I was reviewing my changes, I found the following change:
> > https://github.com/OfficeDev/office-ui-fabric-react/pull/9884/files#diff-594035b9050cc429a57f0fceb24e63ba
> > Can this be because of this change? (using _display: 'inline-block'_ in Icon.styles.ts)
> > If I remove this property using the developer tools, things work as expected!
> > CC: @ecraig12345
> 
> @svaibhav The `display: inline-block` here isn't new, just moved. So it shouldn't be the cause of this issue.

Yeah... Kevin explained that earlier, I was just exploring other piece of code :)

**Comment by kenotron** [comment]
Trying for what @Jahnp said for option 2 - for now using an UGGGGGGLY hack to override styles until we can move to not needing the leaky header styles
