### ISSUE TITLE
Checkbox: Miss Click in Edge and IE

### ISSUE THREAD

**Issue by Lijing29** [OfficeDev/office-ui-fabric-react#10232]
### Environment Information

- **Package version(s)**: V7
- **Browser and OS versions**: Microsoft Edge 44.18362.267.0 & Internet Explorer 11.295.18362.0

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/lijinglin29/pen/NWKrmyQ

#### Actual behavior: 
In Edge and IE, clicking checkbox misses some of the clicks. The performance of the Checkbox component is worse than that of the input tag. 
For the Edge, you could open the [codepen](https://codepen.io/lijinglin29/pen/NWKrmyQ) to do the test.
For the IE, you could open the[ Fabric UI Component website](https://developer.microsoft.com/en-us/fabric#/controls/web/checkbox) to do the test, as the codepen doesn`t support IE.

#### Expected behavior:
The performance of the Checkbox in Edge and IE should not be worse than that in Chrome.

### Priorities and help requested:

Are you willing to submit a PR to fix?: No

Requested priority: Blocking

Products/sites affected: Excel Insights

**Comment by kenotron** [comment]
This "misses" the input during an animation for Edge and IE. I think this is an external issue for Edge... not sure if it's worth pursuing as Edge on Chromiumn is coming very fast (on beta). I'll mark this a perf feature to investigate.

**Comment by khmakoto** [comment]
Hi @Lijing29, sorry for the long delay in replying! Since this is something that's happening because of the browsers and not the component itself I would recommend filing a bug in there as there is not much we can do about it. I'll be tagging this with `Resolution: External` for now. Please let us know if there is anything else we can do to help!
