### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getSuggestions' of undefined     at FloatingPeoplePicker.BaseFloatingPicker.renderSuggestions (BaseFloatingPicker.js?

### ISSUE THREAD

**Issue by bhedayatian** [OfficeDev/office-ui-fabric-react#10239]
I get this error when i use floatingPicker in my react page. the page loads first but then any event on the picker ( focus or enter) throws this error:

Uncaught TypeError: Cannot read property 'getSuggestions' of undefined
    at FloatingPeoplePicker.BaseFloatingPicker.renderSuggestions (BaseFloatingPicker.js?dcbe:200)

i have tried both 
class MyComponent extends BaseFloatingPeoplePicker 

class MyComponent extends React.Component 

I am not very familiar with typescript. can you please help with jsx code?

**Comment by kenotron** [comment]
jsx is fine, but it really would help if you can create a codepen for me to look at.

**Comment by bhedayatian** [comment]
I figured it out. thank you doe your help.
