### ISSUE TITLE
Invalid ARIA attribute value: aria-describedby for PrimaryButton component

### ISSUE THREAD

**Issue by zhr1130** [OfficeDev/office-ui-fabric-react#10235]
- **Package version(s)**: 7.26.0
- **Browser and OS versions**: Chrome

### Describe the issue:

Invalid ARIA attribute value: aria-describedby="id__86" for PrimaryButton

#### Actual behavior:

Invalid ARIA attribute value: aria-describedby="id__86" for PrimaryButton

#### Expected behavior:

Valid aria-describedby

### If applicable, please provide a codepen repro:
https://codepen.io/zhr1130/pen/eYOBwbQ 

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by kenotron** [comment]
Indeed a bug. Though, the use case is invalid really - PrimaryButton or DefaultButton do not render anything in secondaryText (or description). That's a prop only valid for CompoundButton.
