### ISSUE TITLE
Can we have a drop functionality after last index included as part of basic implementation?

### ISSUE THREAD

**Issue by gayathrisns** [OfficeDev/office-ui-fabric-react#10249]
#### Describe the feature that you would like added

In the basic component shown,an item could not be dropped at the last (or after the last index).Can we have that included or is it deliberately excluded?

#### What component or utility would this be added to

DetailsList DragAndDrop
#### Have you discussed this feature with our team, and if so, who

No

**Comment by kenotron** [comment]
That code you're referring to is actually inside the example. To get that effect you want, you'll actually need to modify the dragdropevents prop. Here's a modified example (note the onDrop event fires this `_insertBeforeItem()`):

https://codepen.io/kenotron/pen/ZEzLmQJ?editors=1111

```ts
 private _insertBeforeItem(item: IExampleItem): void {
    const draggedItems = this._selection.isIndexSelected(this._draggedIndex)
      ? (this._selection.getSelection() as IExampleItem[])
      : [this._draggedItem!];

    const draggedItemIndex = this.state.items.indexOf(draggedItems[0]);
    const items = this.state.items.filter(itm => draggedItems.indexOf(itm) === -1);
    let insertIndex = items.indexOf(item) ;

    if (insertIndex !== -1) {
      insertIndex = insertIndex >= draggedItemIndex ? insertIndex + draggedItems.length : insertIndex;
      console.log(insertIndex);
      items.splice(insertIndex, 0, ...draggedItems);
      this.setState({ items: items });
    }
  }
```

**Comment by kenotron** [comment]
this should illustrate how to do this - please close this issue if it addresses your question
