### ISSUE TITLE
PeoplePicker: delete button can't be seen when screen is narrow

### ISSUE THREAD

**Issue by MirandaGe** [OfficeDev/office-ui-fabric-react#1024]
### Bug Report

- __Package version(s)__: all
- __Browser and OS versions__: all

#### Describe the issue:

The persona card of selected people doesn't perform properly when the browser window width is narrow.

#### Actual behavior:

1. open the fabric-react people picker demo page, input 'a' and select a long name like: 'Another A Name (So Many A Names!)'.
2. narrow the window, make the width less than selected persona tag in input area
The outcome is like:
![image](https://cloud.githubusercontent.com/assets/16030290/23049664/8f1ac20e-f4f8-11e6-8178-a32fa80f027c.png)

The delete button cannot be seen and click;
The persona overlaps the input area. (in chrome it will be truncated, but there's also no way to see the delete button)

#### Expected behavior:

The delete button can be seen and can be use.
The border of the input area is complete.

### If applicable, please provide a codepen repro:

http://codepen.io/lingge/pen/MJBzjG

**Comment by joschect** [comment]
@MirandaGe it looks like the code pen is not using the latest version of office-ui-fabric-react. This should have been fixed in the latest version. I'll see if I can't get code-pen to use the latest.

**Comment by MirandaGe** [comment]
@joschect  I retested on latest version, it seems there is still problems for IE 11
![image](https://cloud.githubusercontent.com/assets/16030290/23202236/109784b6-f918-11e6-8342-da2a4dddb9d8.png)

**Comment by lijunle** [comment]
May I raise another concern, why do we have [180px limitation](https://github.com/OfficeDev/office-ui-fabric-react/blob/7030f284c3684d6012d8ad65abff158235bc9019/packages/office-ui-fabric-react/src/components/pickers/BasePicker.scss#L9) on the `.ms-BasePicker-text` class? I don't think we should have this in something with name **base**.

**Comment by micahgodbolt** [comment]
This appears to be resolved in 2.0.1

http://codepen.io/micahgodbolt/pen/jBBgYG?editors=1010

**Comment by lijunle** [comment]
Hi, @micahgodbolt 

I tried to play with your codepen and find a strange issue. After select `aaaaaa`, then input `bbbb` and select, it cannot see `bbbb` in input box. However, after click `x` on `aaaaa`, it shows the `bbbb` again. It seems that, the `bbbb` locates *behind* `aaaaa` label.

Browser: Chrome and Safari

**Comment by MirandaGe** [comment]
Hi @micahgodbolt , I tried your codepen and it's not resolved. The problem is for IE 11. Could you please reopen the issue?
Also I find the root cause of the problem. It is because the min-width is not correctly.
see my change in http://codepen.io/lingge/pen/MJBzjG
