### ISSUE TITLE
Teaching Bubble has no visible focus indicator in Windows 10 High Contrast in Firefox

### ISSUE THREAD

**Issue by SuperJade** [OfficeDev/office-ui-fabric-react#10256]
### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by maxwellred** [comment]
Hi @micahgodbolt - could you take a look at this issue

**Comment by micahgodbolt** [comment]
Does this work in High Contrast on edge?

**Comment by micahgodbolt** [comment]
When you focus on the the close button you do get this:

![image](https://user-images.githubusercontent.com/1434956/63627328-18ac9d80-c5bc-11e9-8418-d4fefa4dfc39.png)

**Comment by wisconsinsara** [comment]
It works in Windows 10 High Contrast IE and Edge, but not Firefox.

**Comment by SuperJade** [comment]
When I focus on the close button in high contrast Firefox, there is no outline/border around the teaching bubble.
