### ISSUE TITLE
Dropdown control always set the selected index to 0 in _onFocus if the current selection isn't in the options

### ISSUE THREAD

**Issue by marywang-office** [OfficeDev/office-ui-fabric-react#10255]
### Environment Information

- **Package version(s)**: (all versions)
- **Browser and OS versions**: (all browsers and OS)

### Please provide a reproduction of the bug in a codepen:
We have a Dropdown control with 4 options. In some scenarios, when the Dropdown associated object doesn't have valid option and sets the initial selected index to 5. The Dropdown shows blank which means nothing is selected, which is the correct behavior. But when user sets focus on it, the selected value changes to index 0 (this._moveIndex). This is incorrect as user hasn't actually changed it yet.   

office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx:

private _onFocus = (ev: React.FocusEvent<HTMLDivElement>): void => {
    const { isOpen, selectedIndices, hasFocus } = this.state;
    const { multiSelect, openOnKeyboardFocus } = this.props;

    const disabled = this._isDisabled();

    if (!disabled) {
      if (!isOpen && selectedIndices.length === 0 && !multiSelect) {
        // Per aria
        this._moveIndex(ev, 1, 0, -1);
      }

#### Actual behavior:
The dropdown selection changed to index 0 when the control has focus.

#### Expected behavior:
The dropdown selection stays same, which means no valid option is selected.

### Priorities and help requested:
High
Are you willing to submit a PR to fix? (Yes, No)
Yes
Requested priority: (Blocking, High, Normal, Low)
High
Products/sites affected: (if applicable)

**Comment by kenotron** [comment]
@marywang-office - since you have indicated that you're willing to submit a PR to fix, feel free to do so. I would advise to get in touch with the code owner before doing much of this work:  @joschect

**Comment by marywang-office** [comment]
I'm communicating with code owner and Working on the fix.
