### ISSUE TITLE
Contextual Menu: Navigation in contextual menu component doesn't loop back if one is at the first or the last menu item and presses up/down keys respectively.

### ISSUE THREAD

**Issue by piyusing** [OfficeDev/office-ui-fabric-react#1025]
### Bug Report

- __Package version(s)__: (1.2.2)
- __Browser and OS versions__: (fill this out if relevant)

#### Describe the issue:
Navigation in contextual menu component doesn't loop back if one is at the first or the last menu item and presses up/down keys respectively.
#### Actual behavior:
If one is at the last menu item and presses down arrow key while the focus is still on contextual popup menu the menu item under focus doesn't loop back to the first menu item, it remains there. And if the focus is at the last item and you press down arrow key, it doesn't loop back to the first item.
#### Expected behavior:
While navigating the menu items using keyboard if the focus reaches the end or the first element further keyups/downs should loop back and start the navigation from last/first element repectively.

**Comment by piyusing** [comment]
Hello,
Any tentative idea, when will the fix go in?

Thanks
Piyush

**Comment by gitjain** [comment]
Issue has been fixed so closing the status.
