### ISSUE TITLE
Is this library intended to be used by non-Office apps?

### ISSUE THREAD

**Issue by mshindal** [OfficeDev/office-ui-fabric-react#10251]
I'm confused by the direction of this project and what it's supposed to be used for. The README describes it as "The React-based front-end framework for building experiences for Office and Office 365." But the components seem to be usable outside of the Office ecosystem.

So my question is, even if it's technically possible to use these components in a standalone app, is that the intended use for them?

**Comment by kenotron** [comment]
We're actually in the middle of working with MSFT marketing team to somehow change this to not be branded as Office only. We are trying to become the primary way to create React (web) applications with the Fluent design language.

**Comment by kenotron** [comment]
If this answers your question, please close this issue.

**Comment by mshindal** [comment]
Thanks.
