### ISSUE TITLE
ChoiceGroup: Support image alt text

### ISSUE THREAD

**Issue by pankajkhanzode** [OfficeDev/office-ui-fabric-react#1026]
**Component**: https://fabricreact.azurewebsites.net/fabric-react/master/#/examples/**choicegroup**

**Requirement**: https://learn.microsoft.com/rgcontents/CONT15249/scormcontent/class/ms/non-text-content/alt-text/decorative-redundant.html#non-text-content_images_decorative-redundant_foreground

ChoiceGroup control supports passing imageSrc. It doesn't allow overriding the image alt text. Expose imageAlt as optional property in IChoiceGroupOption interface. Also allow it to be passed as "" (Empty) explicitly to meet above a11y requirement.

**Comment by battletoilet** [comment]
@pankajkhanzode Please link to the public website, http://dev.office.com/fabric/ when referring to issues because we do not update the website on the azure instance.

We are discussing the possibility of adding HTMLElement type to handle situations like this.
