### ISSUE TITLE
Dropdown focus method does not honor negative tabindex

### ISSUE THREAD

**Issue by dsosby** [OfficeDev/office-ui-fabric-react#10289]
### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**: All

### Describe the issue:

1) Create a Dropdown component with tabIndex of -1
2) Use componentRef to access the IDropdown component
3) Call IDropdown.focus()
Expected:
Dropdown component to receive focus
Observed:
Dropdown component ignores programmatic focus request. There is a condition in Dropdown.base.tsx's focus() method that ignores if tabindex === -1.

Negative tabindex denotes programmatic focus is available, but component is not part of standard keyboard navigation flow. -1 is not a defined constant and is only similar used. Use -2 achieves same effect, but without hitting this bug.

See notes on negative tabindex values:
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

Negative values are not covered in the W3C spec, only that 0+ values are in keyboard access flow.
https://www.w3.org/WAI/UA/TS/html401/cp0101/0101-TABINDEX.html

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/dsosby/pen/JjPNOrL?editors=1010

#### Actual behavior:

Programmatic focus of a Dropdown component is not possible with -1 tabindex.
This is only happening on Dropdown. For example, Button and TextField do not suffer from this problem. See attached CodePen exhibiting this.

#### Expected behavior:

tabindex of -1 on a dropdown keeps out of keyboard tab order (works) but still allows for programmatic access for accessibility improvements (e.g. automatic focus on certain events).

### Documentation describing expected behavior

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex

### Recommended fix

Remove the unnecessary condition for !== -1. Verify all test cases that the original code was intending to fix. The earliest version of this file in Github had this code so I'm not sure of the history on why this was added.

**Comment by cliffkoh** [comment]
I've done some research on the origin of this line and it was implemented in the same PR that introduced the `focus()` method and has not changed since. I sincerely do believe this is a bug as opposed to being intentional about fixing some scenario. 

All unit tests pass after removing this line.
