### ISSUE TITLE
[DetailsList] ariaLabelForSelectAllCheckbox but no ariaLabelForDeselectAllCheckbox

### ISSUE THREAD

**Issue by emkessle** [OfficeDev/office-ui-fabric-react#10288]
I noticed that there is an ariaLabelForSelectAllCheckbox property but there isn't an ariaLabelForDeselectAllCheckbox which would access the isAllSelected state and choose between the two. Is there another workaround for doing this? I don't think a general aria label for "Select or deselect all" would be that useful.

**Comment by maxwellred** [comment]
@emkessle Sorry for the wait! I've spoken with the expert and they say that it's alright that the Checkbox has that aria-description capability as long as it also conveys the state of the checkbox (true/false which it does). They also said that the description shouldn't change per state so it should stay something general like "Toggle checkbox for all items". If this helps resolve the issue it'd be a big help for you to close it, thanks and thanks again for raising the issue!

**Comment by emkessle** [comment]
That is good to know! I will use a general message then. Thank you for your help
