### ISSUE TITLE
Persona: Text cannot truncate in IE11

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#1028]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: IE11

#### Describe the issue:

In IE11, if the persona width is limited and the text content is a little long, it won't truncate the text.
In Chrome it behaves right.

#### Actual behavior:

Text not truncated in IE11
![image](https://cloud.githubusercontent.com/assets/7711735/23071411/3c990966-f569-11e6-8e63-945c89d88e4c.png)

#### Expected behavior:

Text truncated like it is in Chrome
![image](https://cloud.githubusercontent.com/assets/7711735/23071452/586b0e28-f569-11e6-8f78-00a5e2b480b8.png)

**Comment by joschect** [comment]
@ipip2005 is this an already selected item or in suggestions?

**Comment by ipip2005** [comment]
I can't found an codepen for persona so I just tried a repro step in demo page.

1. Go https://fabricreact.azurewebsites.net/fabric-react/master/#/examples/persona
2. Find any persona control.
3. In debugger, inspect this control, and find the element with classname "ms-Persona ms-Persona--xl ms-Persona--blocked"
4. modify style, add "width: 200px" (Or other number that will make the card shorter).

Actual: In IE, the text is not truncated, In Chrome it did.
Expected: In IE the text should also be truncated.

**Comment by aleksandrjPersonal** [comment]
https://github.com/OfficeDev/office-ui-fabric-react/pull/1219

**Comment by micahgodbolt** [comment]
fixed in #1219
