### ISSUE TITLE
Breadcrumb: Make the last item a Heading, for Accessibility?

### ISSUE THREAD

**Issue by HalcyonPride** [OfficeDev/office-ui-fabric-react#10286]
#### Describe the feature that you would like added

- Option to make the last item a heading.

#### What component or utility would this be added to

- Breadcrumb

#### Have you discussed this feature with our team, and if so, who

- No, but I'll actively participate in this thread.

#### Additional context/screenshots

- I'm willing to make the code changes, but I'd like to consult y'all first.

**Comment by maxwellred** [comment]
@HalcyonPride My mistake on the applying styles to give the affect of headings. @betrue-final-final Is there any design considerations that need to be made incorporating Headers into the breadcrumb component?

**Comment by betrue-final-final** [comment]
I agree, I think this should be a heading. I would make it an H1, but that is open to interpretation. There should be only one on a page.
