### ISSUE TITLE
Fabric Version Not Updated Since 6.185.0

### ISSUE THREAD

**Issue by SpencerLynn** [OfficeDev/office-ui-fabric-react#10297]
### Environment Information

- **Package version(s)**: 6.185.0 and newer
- **Browser and OS versions**: N/A

### Please provide a reproduction of the bug in a codepen:
The [version.ts](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/version.ts
) file in the office-ui-fabric-react package doesn't appear to have been updated since 6.185.0.

I've also verified with unpkg that every version (that I've checked at least) since 6.185 has the same version.

[Version 6.202.1 unpkg](https://unpkg.com/office-ui-fabric-react@6.202.1/lib-commonjs/version.js)
[Version 7.28.1 unpkg](https://unpkg.com/office-ui-fabric-react@7.28.1/lib-commonjs/version.js)

#### Actual behavior:
Version is indicating 6.185.0 for that version and all versions newer

#### Expected behavior:
Version should have correct version number

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: All

**Comment by kenotron** [comment]
Feel free to assign to me, I have to fix this likely, but it has several components to the fix (there might be a build job definition fix too)

**Comment by maxwellred** [comment]
Thanks, @kenotron !

**Comment by kenotron** [comment]
I think this is related to this issue: https://github.com/microsoft/beachball/issues/107 where change checks started failing or something during the release job somewhere. Once we tackle that one in `beachball`, I think we can re-enable the set-version task

**Comment by kenotron** [comment]
example fix to the issue: https://unpkg.com/browse/office-ui-fabric-react@7.29.2/lib/version.js

6.0 branch fix is forthcoming tonight.
