### ISSUE TITLE
GroupedList - linter says that isSelected is depreciated, but using selected in custom group header doesn't work

### ISSUE THREAD

**Issue by Terverok** [OfficeDev/office-ui-fabric-react#10295]
### Environment Information
- **Package version(s)**: 7.14.0

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/media-press/pen/QWLgwYQ

#### Actual behavior:
GroupedList, custom header render
Linter tells me that `isSelected` is depreciated, but using only `selected` prop does not work

#### Expected behavior:

Using only `selected` prop supplied to `onRenderHeader` should work and reflect correct selection of a group 

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

**Comment by maxwellred** [comment]
@Terverok Thank you for the issue an I'll look into it shortly!
