### ISSUE TITLE
Slider onChanged not triggered for Keyboard Event

### ISSUE THREAD

**Issue by mcdream331** [OfficeDev/office-ui-fabric-react#10292]
### Environment Information

- **Package version(s)**: 6.202.1
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
Slider onChanged not triggered for Keyboard Event - https://codepen.io/mcdream331/pen/yLBbEpd

#### Actual behavior:

In the console, if a mouse event trigger the value change, the mouse event will get logged. But when keyboard (up, down, left, right) used, the event does not get logged.

#### Expected behavior:

Keyboard event should get logged

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) Yes.  with some guideline

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: (if applicable)

**Comment by mcdream331** [comment]
Looks like only 6.x has this issue. 7.x added support for keyboard event.

**Comment by micahgodbolt** [comment]
good catch. do you need that in 6.x? if so you're welcome to cherry pick it back if needed.

**Comment by maxwellred** [comment]
Hi @mcdream331 would you be willing to cherry pick these changes in a PR?

**Comment by mcdream331** [comment]
Thanks for taking care of it. Sorry I lost track here.
