### ISSUE TITLE
Whats the purpose of SelectionDirection in Iselection interface?

### ISSUE THREAD

**Issue by bhushan2511** [OfficeDev/office-ui-fabric-react#10291]
https://github.com/OfficeDev/office-ui-fabric-react/blob/495d5291eed73e6578a8b62129b032bed61fc9b3/packages/utilities/src/selection/Selection.types.ts#L73

SelectionDirection ENUM is not being used anywhere, whats the purpose of having it here?

Also, selection :Iselection props is provided in DetailList, I assumed that if I set selectionDirection.vertical will enable column selection but Iselection doesn't even have any property to take SelectionDirection ENUM.

**Comment by maxwellred** [comment]
@bhushan2511 Does the above explanation from Thomas help move you in the right direction?
