### ISSUE TITLE
onClick is not available for Buttons

### ISSUE THREAD

**Issue by ellonimo** [OfficeDev/office-ui-fabric-react#10303]
### Environment Information

- **Package version(s)**: 5.135.3
- **Browser and OS versions**: Win 10 x64, Chrome latest. Used in SPFx solution for SharePoint On-Prem 2016

### Please provide a reproduction of the bug in a codepen:

import { DefaultButton } from 'office-ui-fabric-react/lib/Button';
...
<DefaultButton text='Cancel' onClick= { somefunction } />

#### Actual behavior:

Property 'onClick' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<DefaultButton> & IButtonProps & { children?: ReactNode; }

#### Expected behavior:

onClick is available as in examples at site

### Priorities and help requested:

Requested priority: (Blocking)

**Comment by maxwellred** [comment]
Hi @ellonimo I can't seem to repro the issue in my code or in a [codepen](https://codepen.io/CodeMax/pen/abowmma). From what I can see in the code you've provided you perhaps aren't importing in the IButtonProps in your actual code?

**Comment by ellonimo** [comment]
Hi @maxwellred I don't see onClick method in IButtonProps interface in Button.types.d.ts at all. I see your example, but I still have the same error. What information can I provide you for further investigation?

**Comment by khmakoto** [comment]
Hi @ellonimo, you can see that `IButtonProps` extends `React.AllHTMLAttributes`. That's where we get `onClick` from.

**Comment by KevinTCoughlin** [comment]
> Hi @ellonimo, you can see that `IButtonProps` extends `React.AllHTMLAttributes`. That's where we get `onClick` from.

More specifically the typing comes from: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/b4d70e1e77503b36d26ca5e0f35ea433c6b8bd29/types/react/index.d.ts#L1337
