### ISSUE TITLE
Coachmark and TeachingBubble anchors don't handle page resizing

### ISSUE THREAD

**Issue by orokanasaru** [OfficeDev/office-ui-fabric-react#10304]
#### Actual behavior:

At initial zoom, coachmark looks like:

![image](https://user-images.githubusercontent.com/5751627/63895173-3eaeb500-c9a3-11e9-8560-9d63d3c698b9.png)

After zooming out, coachmark looks like:

![image](https://user-images.githubusercontent.com/5751627/63895163-348cb680-c9a3-11e9-999e-192c1fd9cd31.png)

Similar results occur for TeachingBubble.

#### Expected behavior:

Callout elements remain anchored to their targets.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by maxwellred** [comment]
Thanks @orokanasaru I'll take a look at this shortly!

**Comment by maxwellred** [comment]
Hi @orokanasaru I've attempted to repro this issue by manipulated the [Fabric Site](https://developer.microsoft.com/en-us/fabric#/controls/web/coachmark) as well as creating a [codepen](https://codepen.io/CodeMax/pen/QWLgVJq) to try different Fabric versions but don't seem to be able to repro it. Could you take a look at the codepen and add any code that maybe contributing to this issue? Could you also tell me the version of Fabric you are using, Thanks!

**Comment by orokanasaru** [comment]
I've repro'd it on https://developer.microsoft.com/en-us/fabric#/controls/web/coachmark with Chrome, Edge, and Firefox.

Show coachmark at 100%, and start zooming out. 
It'll start shifting around 70%, and be disconnected from the button entirely around 40%.

The behavior does not appear in your codepen, so I'll continue looking for a minimal repro to help diagnose.

**Comment by orokanasaru** [comment]
Here's an easy repro: https://codesandbox.io/s/funny-dew-eihn2

**Comment by maxwellred** [comment]
Thank you @orokanasaru for the repro! I see it now and I'll check to see how Coachmark is calculating positioning and get back to you.
