### ISSUE TITLE
Dropdown box with AzureCustomizationsLight shows incorrect selection color

### ISSUE THREAD

**Issue by chenxinyanc** [OfficeDev/office-ui-fabric-react#10318]
### Environment Information

- **Package version(s)**: 7.28.2
- **Browser and OS versions**: Edge 78.0.249.1 dev

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/xinychen/pen/qBWjeog

#### Actual behavior:
![temp](https://user-images.githubusercontent.com/50703224/63996194-89f4cf00-cb2d-11e9-87c3-a14d61e59f11.gif)

#### Expected behavior:
The selected item in the drop-down box should be blue in the beginning, rather than gray.

### Priorities and help requested:
Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: N/A

**Comment by maxwellred** [comment]
Hi @chenxinyanc What a great find and thank you for offering to submit a PR! Please let me know if you need anything from my end, thanks!
