### ISSUE TITLE
Nav control is highlighting two link while clicked links are within the page

### ISSUE THREAD

**Issue by reshampal2010** [OfficeDev/office-ui-fabric-react#10311]
we have configured Url in nav control for same page , while clicking on current link the previously clicked link is also highlighting. The Expected functionality should highlight only currently clicked link.
please find below details to reproduce the issue
configure links on page with url pointing  within same page like bookmarks, these will be pointing to that bookmark (section of the page)-
![NavIssue](https://user-images.githubusercontent.com/48467727/63920153-d53fac80-ca5d-11e9-92a7-c5337fc11609.png)
`<Nav
                groups={[
                 {
                   links: [
                   {
                     name: 'Home',
                     url: '',
                     links: [
                     {
                       name: 'First ',
                       url: '#BookMarkID_second%20top%20bm',
                       key: 'key1'
                     },
                     {
                       name: 'Second ',
                       url: '#disclaimer',
                       key: 'key2'
                     },
                     { name: 'Third', url: '#disclaimer-1', key: 'key3' }
                     ],
                     isExpanded: true
                   },
                   { name: '
Bookmark', url: '#BookMarkID_top%20bookmark', key: 'key4' },
                   { name: 'Test', url: 'http://msn.com', key: 'key5' },
                   { name: 'Test1234', url: 'http://msn.com', key: 'key6' }
                   
                   ]
                 }
                 ]}
                 expandedStateText={'expanded'}
                 collapsedStateText={'collapsed'}
                />`

**Comment by maxwellred** [comment]
Hi @reshampal2010 I've attempted to repro the issue using the code provided in Codepen but don't seem to be getting a dual link highlight issue. Perhaps there's more code potentially causing this issue that hasn't been shared? Here's the [codepen](https://codepen.io/CodeMax/pen/GRKEXWR).

**Comment by reshampal2010** [comment]
Hi @maxwellred  I am using this code in SPFx webpart.same code is having highlighting issue in SPFx webpart code.

**Comment by reshampal2010** [comment]
I have resolved this issue by explicitly calling click function and set the value of key in set state , then getting the **selectedKey**  from set state.
