### ISSUE TITLE
getTheme() Does Not Return Current SharePoint Online Site Theme Colors

### ISSUE THREAD

**Issue by Arknev** [OfficeDev/office-ui-fabric-react#10313]
I have searched extensively for solutions to the issue in this question:
https://stackoverflow.com/questions/54768206/how-to-get-the-current-theme-in-a-spfx-webpart-using-the-new-ts-based-styling-ap

I've been following the guidance here:
  https://developer.microsoft.com/en-us/fabric#/styles/web/colors/theme-slots
and here:
  https://github.com/OfficeDev/office-ui-fabric-react/wiki/Component-Styling

All works well until the theme is changed. The colors that are returned are always the default.

Is there a minimum version for this functionality or is this experimental?

**Comment by maxwellred** [comment]
Thank you for the issue @Arknev! I'll look around and get back to you.

**Comment by cliffkoh** [comment]
cc @phkuo who likely knows...

**Comment by cliffkoh** [comment]
@Arknev can you please provide the SPFx version and UI Fabric version you're using?

**Comment by Arknev** [comment]
I think this is what you are looking for:

npm list office-ui-fabric-react
+-- @microsoft/sp-property-pane@1.8.2
| +-- @microsoft/office-ui-fabric-react-bundle@1.8.2
| | `-- office-ui-fabric-react@6.143.0
| `-- office-ui-fabric-react@6.143.0
+-- @microsoft/sp-webpart-base@1.8.2
| +-- @microsoft/sp-loader@1.8.2
| | `-- office-ui-fabric-react@6.143.0
| `-- office-ui-fabric-react@6.143.0
+-- @microsoft/sp-webpart-workbench@1.8.2
| +-- @uifabric/variants@6.14.0
| | `-- office-ui-fabric-react@6.202.0  deduped
| `-- office-ui-fabric-react@6.143.0
+-- @pnp/spfx-controls-react@1.13.2
| `-- office-ui-fabric-react@5.131.0
+-- @pnp/spfx-property-controls@1.15.0
| `-- office-ui-fabric-react@5.131.0
+-- @uifabric/fluent-theme@0.16.20
| +-- @uifabric/variants@6.15.1
| | `-- office-ui-fabric-react@6.202.0  deduped
| `-- office-ui-fabric-react@6.202.0  deduped
`-- office-ui-fabric-react@6.202.0

npm list @uifabric/styling
+-- @microsoft/sp-property-pane@1.8.2
| +-- @microsoft/office-ui-fabric-react-bundle@1.8.2
| | +-- @uifabric/icons@6.4.0
| | | `-- @uifabric/styling@6.50.5  deduped
| | `-- office-ui-fabric-react@6.143.0
| |   `-- @uifabric/styling@6.50.5  deduped
| `-- office-ui-fabric-react@6.143.0
|   `-- @uifabric/styling@6.50.5  deduped
+-- @microsoft/sp-webpart-base@1.8.2
| +-- @microsoft/sp-loader@1.8.2
| | `-- office-ui-fabric-react@6.143.0
| |   `-- @uifabric/styling@6.50.5  deduped
| `-- office-ui-fabric-react@6.143.0
|   `-- @uifabric/styling@6.50.5  deduped
+-- @microsoft/sp-webpart-workbench@1.8.2
| `-- office-ui-fabric-react@6.143.0
|   `-- @uifabric/styling@6.50.5  deduped
+-- @pnp/spfx-controls-react@1.13.2
| `-- office-ui-fabric-react@5.131.0
|   +-- @uifabric/icons@5.8.0
|   | `-- @uifabric/styling@5.37.0  deduped
|   `-- @uifabric/styling@5.37.0
+-- @pnp/spfx-property-controls@1.15.0
| `-- office-ui-fabric-react@5.131.0
|   +-- @uifabric/icons@5.8.0
|   | `-- @uifabric/styling@5.37.0  deduped
|   `-- @uifabric/styling@5.37.0
+-- @uifabric/fluent-theme@0.16.20
| `-- @uifabric/styling@6.50.5
`-- office-ui-fabric-react@6.202.0
  +-- @uifabric/foundation@0.8.2
  | `-- @uifabric/styling@6.50.5  deduped
  +-- @uifabric/icons@6.5.4
  | `-- @uifabric/styling@6.50.6  deduped
  `-- @uifabric/styling@6.50.6

**Comment by phkuo** [comment]
This is not a Fabric issue but an SPFX issue, you should ask on their forums instead.
In terms of common mistakes I see:
- Do not use getTheme(). That only returns the theme at the current time and doesn't update when the theme updates.
- Within components themselves, you should follow the Fabric patterns of "inheriting" the theme from props, so that you automatically get subscribed to theme updates. It sounds like you're already doing this?
- SPFX provides its own way to get the theme, you'll want to consult their documentation. The patterns and APIs laid out there take priority over the APIs recommended here in Fabric.

**Comment by phkuo** [comment]
Additionally I recently introduced a bug in v6.50.4 of @uifabric/styling that prevented theming from working, if you're using that version you'll want to update to at least v6.50.5.

**Comment by phkuo** [comment]
The buggy version of @uifabric/styling in v7 (master) was v7.4.1, fixed in v7.5.1.

**Comment by Arknev** [comment]
For anyone else who finds this, the best answer I found to get the theme in SPFx is here: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/supporting-section-backgrounds

Which uses the ThemeProvider service.
