### ISSUE TITLE
DatePicker - unable to set textfield styles/colors

### ISSUE THREAD

**Issue by matprzybyla** [OfficeDev/office-ui-fabric-react#10312]
### Environment Information

- **Package version(s)**: 7.27.1
- **Browser and OS versions**: Windows 10 Chrome 76.0.3809.100

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/matprzybyla/pen/LYPLXwB

#### Actual behavior:

When using DatePicker component I want to set its text field background setting style on `textField` area to `some color` to warn user if selected date is not valid. 
Currently DatePicker seems to ignore styles for textField background. 
Provided codepen shows that some of styles work:
- padding - works, 
- background - behaves odd, 
- color - does not work, 
- borderColor - does not work. 

Styles work perfectly on `icon` area without problems.

#### Expected behavior:

`textField` area of DatePicker responds to passed styles properly

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)
Requested priority: (Normal)

**Comment by maxwellred** [comment]
@matprzybyla Thank you for the issue and the codepen repro! I'll look into this shortly and get back to you.

**Comment by maxwellred** [comment]
Hi @matprzybyla I was able to get customizations to work in this [codepen](https://codepen.io/CodeMax/pen/mdbwaWb). Please let me know if this helps out and if it does it'd be great if you could close the issue, thanks!

**Comment by matprzybyla** [comment]
Hi @maxwellred. Thanks for addressing it.
 
This allowed to solve the issue.
Updated original codepen with comment - added the following - now it has background colored if anyone needs it. 

```
selectors:{
        "input": {
          backgroundColor: 'aqua'    
        }
      }
```
