### ISSUE TITLE
DatePicker/Calendar - onRenderDay 

### ISSUE THREAD

**Issue by matprzybyla** [OfficeDev/office-ui-fabric-react#10323]
#### Describe the feature that you would like added

It would be great if DatePicker/Calendar had options similar to some other components from Fabric React package. For example Dropdown allows for `onRenderTitle, onRenderLabel, etc.` 
In DatePicker/Calendar `onRenderDay` whould be called to allow customization of rendered day cell

#### What component or utility would this be added to

DatePicker/Calendar

#### Have you discussed this feature with our team, and if so, who

Asked on stackoverflow, no responses yet. https://stackoverflow.com/questions/57711454/fabricui-datepicker-calendar-days-highlighting-and-navigation-callback

#### Additional context/screenshots

Allows for better DatePicker/Calendar customization possibilities.

**Comment by maxwellred** [comment]
Hi @matprzybyla Ill look into to this and the other issue regarding DatePicker, thanks!

**Comment by lorejoh12** [comment]
This is a good feature request. Right now there's no way to customize styles for days that aren't restricted or "today", if the consumer wants to highlight specific days, for example. It also would not be that difficult to add, just have a new prop for onRenderDay that gets passed all the way down.

Are you willing to submit a PR for this? I'm in favor of adding it and it's not changing the default UI so I don't think our design team will have issue with it, it just becomes a matter of prioritizing the work.

**Comment by matprzybyla** [comment]
Hi @lorejoh12 . Thanks for feedback, really appreciate this. This change would be very welcome. 

I'm a bit fresh with fabric repo so I won't submit PR for this. 
Trying one with the second issue though.

**Comment by lorejoh12** [comment]
After looking at this more carefully, while it would be relatively straightforward to add a custom "onRenderCell" callback, there's a significant amount of logic that the consumer needs to have in order for that to work. Right now, the same place we apply the css that you want to be able to customize, is also where we apply onMouse* and onClick callbacks, and we'd require the consumer to make it a <td> for accessibility... It gets pretty messy and most likely not useful.

Alternatively, what if we provide a custom callback for just applying a className on the day cell itself? That way you get to do your own styling and don't have to worry about all the other potential issues.

**Comment by matprzybyla** [comment]
I think that adding custom class instead template right now would be enough. Still allows to change day view to that can grab user attention. Like the idea!

**Comment by maxwellred** [comment]
Hi @lorejoh12 I was wondering if you were willing to handle the new classname feature?

**Comment by lorejoh12** [comment]
Yeah, let me throw something together for this, might take a few days but should be ready to go next week.
