### ISSUE TITLE
DetailsList onClick event for each row (sans checkbox)

### ISSUE THREAD

**Issue by BrianD91** [OfficeDev/office-ui-fabric-react#10327]
#### Describe the feature that you would like added

I want to be able to click on any part of a row of DetailsList component, except for the checkbox on the far left and have it trigger an event.

#### What component or utility would this be added to

DetailsList

#### Have you discussed this feature with our team, and if so, who

No.

#### Additional context/screenshots

Think of this like how most email applications work. You can click anywhere in the row for one email and it will open that email, OR you can click on the checkbox to select it and other emails for mass actions (i.e. archive, delete, mark as read, etc...). I've tried tinkering around a lot with the DetailsList and cannot find a way to implement this feature without changes being made.

**Comment by maxwellred** [comment]
@BrianD91 Thank you for the feature request! I'll investigate and get back to you.

**Comment by maxwellred** [comment]
@BrianD91 Have you tried passing functionality through the onItemInvoked props (handles Enter key and double click)?
