### ISSUE TITLE
DatePicker/Calendar: ability to inform when month was changed

### ISSUE THREAD

**Issue by matprzybyla** [OfficeDev/office-ui-fabric-react#10322]
#### Describe the feature that you would like added

Callback function to execute when changing months like 'onMonthChanged' or similar

#### What component or utility would this be added to

DatePicker/Calendar

#### Have you discussed this feature with our team, and if so, who

Not yet, asked on stackOverflow but no responses yet. https://stackoverflow.com/questions/57711454/fabricui-datepicker-calendar-days-highlighting-and-navigation-callback

#### Additional context/screenshots

Need to get information if user navigated through months and what is the current one.

**Comment by lorejoh12** [comment]
This is a good suggestion that I've been meaning to get to. I actually did add that callback for the WeeklyDayPicker control because it's useful, just haven't gotten around to doing it for Calendar and DatePicker yet. This also isn't too much work to add, because we already have the internal function that gets called, would just need to expose that and test to make sure it's getting called in all the instances you expect it to.

Are you willing to submit a PR for this? I'm in favor of adding it and it's not changing the default UI so I don't think our design team will have issue with it, it just becomes a matter of prioritizing the work.

**Comment by matprzybyla** [comment]
Hi @lorejoh12 
Thanks for fast feedback and some inspiration to try.

Added some changes to address this issue on my fork of office-fabric-react.
Here is the PR: https://github.com/OfficeDev/office-ui-fabric-react/pull/10329

This is my first try to contribute here and I got some issues. Was not able to get change file using steps described in Development-Workflow and Setup wiki documents. Will appreciate any tips to fix this.

**Comment by cliffkoh** [comment]
ping @kenotron regarding the trouble you have with development workflow

**Comment by kenotron** [comment]
if you're having issues with this, it is likely because you don't have a local upstream of the main repo. try this:

```
git remote add upstream https://github.com/OfficeDev/office-ui-fabric-react.git
git fetch
```

**Comment by matprzybyla** [comment]
Hi @kenotron 
Tried doing so, already had upstream set before.
```
origin  https://github.com/matprzybyla/office-ui-fabric-react.git (fetch)
origin  https://github.com/matprzybyla/office-ui-fabric-react.git (push)
upstream        https://github.com/OfficeDev/office-ui-fabric-react.git (fetch)
upstream        https://github.com/OfficeDev/office-ui-fabric-react.git (push)
```

Still running `yarn change` outputs
```
yarn run v1.17.3
$ beachball change
Target branch is "upstream/master"
Checking for changes against "upstream/master"
fetching latest from remotes
No change files are needed
Done in 3.68s.
```

Not sure what I'm doing wrong or missed sth in setup?

**Comment by matprzybyla** [comment]
Hi @maxwellred. 
The first suggested option helped. The change file was generated and I was able to push it into PR.
Thanks a lot!

Currently waiting for answer from John Lorenz about some details I'm not sure. But at least one step forward was made :)

**Comment by maxwellred** [comment]
Adding Needs author feedback for soft close since the respective PR was closed per the author not having time to tackle the issue.
