### ISSUE TITLE
Performance: DetailsColumn.Base.tsx is violate lambda in jsx

### ISSUE THREAD

**Issue by LiangMingChen** [OfficeDev/office-ui-fabric-react#10341]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

https://github.com/OfficeDev/office-ui-fabric-react/blob/da5ebdc18277c19da090a9e5647acaa4efd58864/packages/office-ui-fabric-react/src/components/DetailsList/DetailsColumn.base.tsx#L112

These two line  to work with TooltipHost implementation , but these two line are create a function on every render :(

This is clearly violate no lambda in jsx (bind is create a functiuon.)
https://www.google.com/search?q=no+lambda+in+jsx

Which result in every render result in re-rendering (since every render is a new call back.)

#### Expected behavior:

consider to memoized the function or you need to base on event handler to derived the column.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by KevinTCoughlin** [comment]
Thanks @LiangMingChen, I'll take a look at a proper fix. Looks like we're using `bind` to augment function arguments here. Should be patch-able.

**Comment by KevinTCoughlin** [comment]
@LiangMingChen this PR should address the issue you reported: https://github.com/OfficeDev/office-ui-fabric-react/pull/10346. Luckily the methods in question were marked `private` and thus could be modified :).
