### ISSUE TITLE
Need Documentation on using “componentRef” IDropDown using Type Script.

### ISSUE THREAD

**Issue by 1011RKP** [OfficeDev/office-ui-fabric-react#10354]
I am trying to use Office UI Fabric Dropdown and i need help on using “componentRef” with Typescript and react. there is not documentation on these scenarios.

**Comment by KevinTCoughlin** [comment]
@1011RKP, I'd encourage you to take a look at existing examples in the repo which utilize `componentRef` such as https://github.com/OfficeDev/office-ui-fabric-react/blob/5bfcd8bea762210ce53b198961ccca609f917c92/packages/experiments/src/components/Toggle/examples/Toggle.Example.tsx#L46

Many of these examples use the result similar to `ref` to programmatically set focus. However, the type returned is the type of the component giving you access to its public API on the returned instance.

You can inspect the type signature here https://github.com/OfficeDev/office-ui-fabric-react/blob/5bfcd8bea762210ce53b198961ccca609f917c92/packages/utilities/src/BaseComponent.types.ts#L11

**Comment by 1011RKP** [comment]
> type

@KevinTCoughlin Thanks this will help a lot ...

**Comment by KevinTCoughlin** [comment]
Closing the above question as "answered".
