### ISSUE TITLE
data-* attribute is not applied to rendered CommandBar

### ISSUE THREAD

**Issue by chenxinyanc** [OfficeDev/office-ui-fabric-react#10353]
### Environment Information

- **Package version(s)**: 7.29.2
- **Browser and OS versions**: Edge 78.0.249.1 dev

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/xinychen/pen/eYOeBbP

#### Actual behavior:
Rendered button has `data-test`, but CommandBar does not have it.
```html
<div>
<div><button type="button" data-test="test data" class="ms-Button ms-Button--default root-49"
    data-is-focusable="true"><span class="ms-Button-flexContainer flexContainer-50"
      data-automationid="splitbuttonprimary"><span class="ms-Button-textContainer textContainer-51"><span
          class="ms-Button-label label-53" id="id__1">Hello World</span></span></span></button>
  <div>
    <div style="position: relative;">
      <div data-automation-id="visibleContent" style="">
        <div class="ms-FocusZone css-60 ms-CommandBar root-57" role="menubar" data-focuszone-id="FocusZone4">
          <div class="ms-OverflowSet ms-CommandBar-primaryCommand primarySet-61" role="presentation">
            <div class="ms-OverflowSet-item item-62"><button type="button" role="menuitem"
                class="ms-Button ms-Button--commandBar ms-CommandBarItem-link root-64" data-is-focusable="true"
                tabindex="0"><span class="ms-Button-flexContainer flexContainer-50"
                  data-automationid="splitbuttonprimary"><span class="ms-Button-textContainer textContainer-51"><span
                      class="ms-Button-label label-66" id="id__5">Item 1</span></span></span></button></div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
```

#### Expected behavior:
I should be able to see `data-*` applied to any of the rendered `<div>` element inside `CommandBar`.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) N/A

**Comment by KevinTCoughlin** [comment]
I can repro the report above with `CommandBar`. I'll need to debug further, but my guess is that only Button variants call `getNativeProps<T>` whereas `CommandBar` does not.

@chenxinyanc, would you expect the data attribute as you've supplied it be rendered on the root `FocusZone` element within the `CommandBar`?

Out of curiosity, what is the scenario which requires data-* attributes be rendered?

**Comment by chenxinyanc** [comment]
> would you expect the data attribute as you've supplied it be rendered on the root FocusZone element within the CommandBar?

I think so. Actually it can be on any layer of the commandbar container element. (I know there are multiple `<div>`s surrounding the commandbar buttons.)

> Out of curiosity, what is the scenario which requires data-* attributes be rendered?

We need this attribute for identifying an element from the root of DOM tree. This includes
1. restricting the scope (with `div[data-*=xxx]`) when selecting a commandbar button (with `button[name=xxx]`) in the DOM tree during UI testing. Usually the `name` of button is intended to be short and can be duplicate with buttons elsewhere / outside the toolbar.
2. identifying the region (e.g. inside toolbar) when sending telemetry regarding to user's action.

**Comment by chenxinyanc** [comment]
After taking a look at BaseButton.tsx, I'm thinking about passing all the attributes specified on the CommandBar, filtered by [`getNativeProps`](https://github.com/OfficeDev/office-ui-fabric-react/blob/2e9ee9fbd147196e970a1be19b8afbb5e17b6d87/packages/utilities/src/properties.ts#L392), so all of the `aria-` and `data-` attributes will have a chance to pass through.

https://github.com/OfficeDev/office-ui-fabric-react/blob/55fd98df3647b74c569cd65587a187c486f1d4a5/packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx#L154-L160
