### ISSUE TITLE
@uifabric.utilities.styled.tsx: _resolve is not exported but should be 

### ISSUE THREAD

**Issue by flavomulti** [OfficeDev/office-ui-fabric-react#10367]
In addition to the description for using styles, stylesets, etc. in @uifabric/merge-styles, there are various ways to allow a component author to create their components and the associated style. classNamesFunction and a few other conventions help make this easier. However, in order to resolve both your own `getStyles` and a component prop `styles:  IStyleFunctionOrObject<StyleProps, Styles>` more easily in your component, the _resolve function in styled.tsx is needed. styled.tsx uses _resolve internally for exactly this purpose. If you are not using styled and just want to keep component authoring a bit less abstract, say with simple function components, _resolve is an important helper function.

Simplified example showing the need for _resolve to be exported.
```ts
export interface Props {
  className?: string
  styles: IStyleFunctionOrObject<StyleProps, Styles>
}

export const MyComponent(props: Props): React.ReactElement {
   const cn = getClassNames(props.styles, props.className)
   return(
     <div classNam={cn.root}>
       hello world
     </div>
  )
}
export interface Styles {
    root?: IStyle
}

export interface StyleProps {
    className?: string
}

// produce a IStyleFunctionOrObject<StyleProps, Styles> => IProcessedStyleSet<Styles>
// which gives us strings for all the properties on Styles.
const _getClassNames = classNamesFunction<StyleProps, Styles>()

// our basic getStyles given StyleProps, we need to define this
export const getStyles = (props: StyleProps): Styles =>
    ({
        root: ["myapp-Application", {
            display: "flex",
            flexDirection: "column"
        }, props.className],
    })

// Merge props from the component above and our getStyles to get class names.
// We have both the style function from props and the default style function. However
// classNamesFunction produces a function that only takes a single
// IStyleFunctionOrObject and we can't compose IStyleFunction's smartly. 
// We need to use mergeStyleSets or concatStyleSets. 
//
// But it is easier if we have `_resolve` available to merge the results of our 
// style functions/objects.
function getClassNames(stylesFromApplicationProps: IStyleFunctionOrObject<StyleProps, Styles>, classNameFromApplicationProp?: string): IProcessedStyleSet<Styles> {
  
  // _getClassNames can't take 2 arguments up front 
  //return _getClassNames(stylesFromApplicationProps, { className: classNamFromApplicationProps }) // ignores default getStyles

  // this merges everything correctly and can combine the different parts.
  return mergeStyleSets(resolve({className:classNameFromApplicationProps}, 
                 getStyles, 
                 stylesFromApplicationProps))

  // you cannot call _getClassNames twice and merge those results correctly!
}
```
This touches on _resolve which is mentioned in #5860.

**Comment by KevinTCoughlin** [comment]
If I'm understanding the ask here properly, its that the `_resolve` function be hoisted to our public API. I'm less familiar with the inner-workings here and will need to dive in to see what problems this solves using the above as a starter.. @dzearing @kenotron @cliffkoh may have an opinion sooner than me.

**Comment by aappddeevv** [comment]
The key reason for this is when you have your own "default" getStyles but need to merge those results with those from a component's parameter getStyles. _resolve is a pre-existing function that helps.

**Comment by dzearing** [comment]
This sounds wrong, but am on my phone and beed to see the code to get more clarity on the scenario. Will look once im back to my desk. Hope i can provide an alternative because exporting more api surface here shouldnt include exporting private members

**Comment by aappddeevv** [comment]
That sounds great. Thanks for looking into it.

**Comment by aappddeevv** [comment]
@dzearing Thoughts?

**Comment by dzearing** [comment]
@aappddeevv Just submitted a PR. Let me know what you think.

**Comment by aappddeevv** [comment]
Looks like concatStyles was enhanced to take IStyleFunctionOrObject so that looks good. Thanks a bunch.
