### ISSUE TITLE
DetailListView layoutMode (default) with sort cause confusing user experience 

### ISSUE THREAD

**Issue by LiangMingChen** [OfficeDev/office-ui-fabric-react#10386]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

**Code Pen**
https://codepen.io/liangmingchen/pen/dybddwa

#### Actual behavior:

https://codepen.io/liangmingchen/pen/dybddwa

1. Move one of the column off the screen
2 Click on sort on various state column width.
3. Even worse when you use the ShimmerDetailsList #10351 since it always trigger this part of code path

![lostUserColumnWidth2](https://user-images.githubusercontent.com/3789716/64494324-2ca10200-d240-11e9-9b62-712756eaa2ff.gif)

This is even more strange when there are horizontal scroll bar (which out of the box should not be justified?  But it does 

![lostUserColumnWidth](https://user-images.githubusercontent.com/3789716/64481368-84336500-d18f-11e9-80ff-def678e77066.gif)

#### Expected behavior:
Detail List Sort is look and feels like a button click.  No User will expect the "justified happend" during on.  It is also very strange when "sort" state change along will cause column to adjust the width.

it should keep user set columns for all columns when possible, -- on sort or other then width change. 

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by LiangMingChen** [comment]
I try it on codepen, it seems that offui fabric expect us to change the sort order in place without give a new set of Columns

**Comment by LiangMingChen** [comment]
Sorry mean to insert the repro in codepen.io

**Comment by LiangMingChen** [comment]
Hmm, I can't repro in code pen. let me take a deeper look on the issue.

**Comment by LiangMingChen** [comment]
Change description and provide the code pen on justification happen on the sort expreience.
https://codepen.io/liangmingchen/pen/dybddwa

**Comment by natalieethell** [comment]
@LiangMingChen Ah interesting, thanks for reporting this! This behavior definitely looks like a bug to me. We'll take a closer look.

**Comment by natalieethell** [comment]
After initial investigation, it looks like this might be happening because `_getJustifiedColumnsAfterResize` gets called instead of `_getJustifiedColumns` here:

https://github.com/OfficeDev/office-ui-fabric-react/blob/e0209bd8938e9e729f2ef2cd674808051da75a3a/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.base.tsx#L782-L786

Looking into why the code path goes here.

**Comment by natalieethell** [comment]
Okay I see, `_getJustifiedColumnsAfterResize` is only called when a column is resized. When the column is sorted and the items are updated, DetailsList seems to be calling `_getJustifiedColumns` and resetting the column widths so that all columns fit in the window. We'll dig into this.

**Comment by LiangMingChen** [comment]
Sorry for been late, In general, it look like a lot of complexity come from LayoutMode=justified. (which is default)
That is if I change explicit force back to LayoutMode=fixedColumns, then a lot of strange behavior go away.   MHO, justified layoutMode seems to do it **always** which is most likely undesired unless in the initial load or right after one of the width adjustment.
