### ISSUE TITLE
how to trigger inputchange event manually for NormalPeoplePicker?

### ISSUE THREAD

**Issue by bhedayatian** [OfficeDev/office-ui-fabric-react#10385]
Hello

I would like to manually trigger inputChange manually in my function

      myFunction = (event) => 
          const  peoplePickerobj = get the people picker from its id
          const inputChangeEvent = new Event('inputchange', { bubbles: true, cancelable: false });
          **peoplePickerobj.dispatchEvent(inputChangeEvent);**
        }
    
    _onInputChange = (input) => {
       console.log('got here');
      }
    

I get dispatchEvent is not a function error.. how do I trigger the event?
this is my people picker

                                 <NormalPeoplePicker
                                    onResolveSuggestions={this._onFilterChanged}
                                    onEmptyInputFocus={this._returnMostRecentlyUsed}
                                    className={toClass}
                                    onInputChange={ this._onInputChange}
                                   componentRef={this._resolveRef('_to_picker')}
                                  
                                />

**Comment by bhedayatian** [comment]
Hello. any update on this please?

**Comment by natalieethell** [comment]
Hi @bhedayatian how are you setting the id on your peoplepicker? And how are getting the id from your peoplepicker?

Are you by chance using jquery and prototype on the same page? I see that [some folks](https://stackoverflow.com/questions/980697/element-dispatchevent-is-not-a-function-js-error-caught-in-firebug-of-ff3-0) with this error discovered that this conflict was causing their issue.

**Comment by bhedayatian** [comment]
@natalieethell not I am using react not jquery.  I am using 
<NormalPeoplePicker
componentRef={this._resolveRef('_to_picker')}
..> and can access it like  this[`_to_picker`].

**Comment by natalieethell** [comment]
What does your `_resolveRef` method do? Is there any way you could provide a CodePen repro for us? It'll help us debug this a little faster. Here's one to get started: https://codepen.io/natalieethell/pen/WNezvPw.

**Comment by bhedayatian** [comment]
@natalieethell Thanks for your prompt answer
Isnt this irrelevant to my question? I have a ref to normalPeoplePicker component (doesn't matter how its been created at this time since I see all the methods and properties of the picker). I just need to trigger the inputchage event manually from another method.

**Comment by bhedayatian** [comment]
@natalieethell  can you please tag somebody who can possibly help?

**Comment by natalieethell** [comment]
If you're looking for a more intuitive way to trigger the inputchange event manually, I would suggest using the floating people picker. Here's a code sandbox that can get you started: https://codesandbox.io/s/basic-floating-picker-w8je2.

**Comment by aneeshack4** [comment]
@bhedayatian Please answer @natalieethell's questions - she is asking very relevant questions.

**Comment by bhedayatian** [comment]
@natalieethell unfortunately we have restrictions to update office-ui-fabric and use floating-picker.
I will try to make a codepen from my problem tonight and we go from there.thanks for your help.

**Comment by bhedayatian** [comment]
> If you're looking for a more intuitive way to trigger the inputchange event manually, I would suggest using the floating people picker. Here's a code sandbox that can get you started: https://codesandbox.io/s/basic-floating-picker-w8je2.

@natalieethell  does it let me save my code in your project?

**Comment by natalieethell** [comment]
@bhedayatian You should be able to fork the code sandbox by clicking "Fork" in the top right!

**Comment by bhedayatian** [comment]
@natalieethell unfortunately I can't make the codepen to the stage I am with my project to show you the problem. just a quick question though
I am trying to show invalid emails with highlighted color( currently picker deletes invalid emails), so I am changing the behaviour of the picker. I create persona manually and then need to clear the user input
I have tried to clear the input box with these lines but they didn't work
 this[`_to_picker`].input.current.inputElement._valueTracker.setValue = ''
 this[`_to_picker`].input.current.inputElement.setValue = '';
 this[`_to_picker`].input.current.state.displayValue = '';

any tips? thank you.
