### ISSUE TITLE
Stack alignment 'evenly-spaced' does not work in Edge/IE11

### ISSUE THREAD

**Issue by ltrazak** [OfficeDev/office-ui-fabric-react#10382]
### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**: Edge/IE11

### Describe the issue:

For stack alignment; evenly-spaced does not work in Edge or IE11. You can reproduce this on the Fabric documentation site: https://developer.microsoft.com/en-us/fabric#/controls/web/stack

#### Actual behavior:

Items are are either top-aligned or left-aligned based on stack orientation

#### Expected behavior:

Items are evenly spaced like in Chrome

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

**Comment by ltrazak** [comment]
Apparently this is a known issue with Edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15947692/

**Comment by KevinTCoughlin** [comment]
> Apparently this is a known issue with Edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/15947692/

Hey @ltrazak, thanks for reporting this and for following up with the known Edge bug! With Edge Chromium progress being made I'm not sure this will be patched in old Edge. So we may have to close this as not actionable from the library side.

**Comment by KevinTCoughlin** [comment]
Closing this as it is a browser issue that will be addressed by Edge adopting Chromium engine.
