### ISSUE TITLE
Dialogs have incorrect initial focus

### ISSUE THREAD

**Issue by tiagomacarios** [OfficeDev/office-ui-fabric-react#10398]
Dialogs will focus the "X" by default. Usually, modal dialogs focus the input buttons. For people that work with the keyboard, this means having to tab a couple of times more.

Repro:
1 - Go to https://developer.microsoft.com/en-us/fabric#/controls/web/dialog
2 - Open the "Default Dialog"

The top X will be focused.

**Comment by natalieethell** [comment]
So by default, the Dialog focuses on the first focusable element in the DOM. In the case of the basic Dialog, the 'X' button comes first.

If you'd like to change this, you can actually customize which element in your dialog you'd like to focus on first by utilizing `modalProps.firstFocusableSelector`. Here's an example CodePen where I set the focus on the second action button on the bottom of the dialog: https://codepen.io/naethell/pen/GRKYXNz.

The code is roughly as follows:

```tsx
<Dialog
  ...
  modalProps={{
    ...
    firstFocusableSelector: 'ms-Button--default'
  }}
/>
```

Let me know if that helps!

**Comment by tiagomacarios** [comment]
@natalieethell Would it make sense to change the default? Most modal dialogs focus on the ok button.
