### ISSUE TITLE
[DatePicker] textField prop: onChange is never being called

### ISSUE THREAD

**Issue by watty888** [OfficeDev/office-ui-fabric-react#10406]
### Environment Information

- **Package version(s)**: 6.202.0
- **React**: 16.9.0 
- **Browser**: Chrome, Version 76.0.3809.132 (Official Build) (64-bit)
- **OS**: macOS Mojave 10.14.6 (18G95)

### Bug reproduction in [codesandbox](https://codesandbox.io/embed/fabric-starter-sandbox-kuoy5?fontsize=14):
**Steps**:
1) Check the `index.tsx` file
2) Clear console
3) Start typing in the textfield

#### Actual behavior:
Upon typing something in the text field, entered value is not being logged into console. 
`onChange` of the `textField` prop is never being called.

![Screen Recording 2019-09-10 at 14 44 00](https://user-images.githubusercontent.com/22498436/64615369-b4227880-d3da-11e9-8122-2467cae235f2.gif)

#### Expected behavior:
Input of the text field must appear in the console as you type. `onChange` should call `console.log`.

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (High)

**Comment by natalieethell** [comment]
Hey @watty888 thanks for opening an issue! It looks like this is happening, because the `onChange` method on the text field is actually always overridden by the `onChange` method in the DatePicker code itself (note lines 190 and 203 below). 

https://github.com/OfficeDev/office-ui-fabric-react/blob/72e835bd59d6c29b1a222fccdd5c57a339c73090/packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.base.tsx#L190-L203

@evlevy it looks like you made the changes to add the `textField` prop for increased customizability. Was this placement intentional? Also @lorejoh12 FYI.

Thank you also for providing a code sandbox for us, that makes it a lot easier to pinpoint and debug the issue much faster!

**Comment by evlevy** [comment]
@natalieethell at the time textFieldProps was introduced we didn't consider folks wanting to override onChange - it was more for customizing the UI of the textField and not the behaviour. If this is now required, we would need to consider which handler to call, or possibly integrate the supplied handler into [the existing one](https://github.com/OfficeDev/office-ui-fabric-react/blob/72e835bd59d6c29b1a222fccdd5c57a339c73090/packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.base.tsx#L328).

**Comment by evlevy** [comment]
(Sorry I accidentally closed this issue just now. Reopened.)

**Comment by natalieethell** [comment]
@evlevy Got it, maybe it would be good to integrate the supplied handler into the existing `onChange` handler. I'll take a closer look. Thanks!

**Comment by natalieethell** [comment]
@evlevy Opened a PR with those changes, feel free to take a look if you have a moment.

**Comment by watty888** [comment]
@natalieethell thanks for your rush reply! Can you also please specify for which version your fix will be applied? The project we are currently working at uses  6.202.0.

**Comment by watty888** [comment]
>  but we can also backport the changes to 6.x.x.

That would be great, as in the projects current state, we would prefer not to update for at least some time.

**Comment by watty888** [comment]
Hi Natalie! Great that it's fixed! However, are there any updates regarding 6.x.x version fix?

**Comment by natalieethell** [comment]
@watty888 Thanks for the reminder! I'll cherry pick into 6.0 right now.

**Comment by natalieethell** [comment]
You can follow the cherry-pick into 6.0 here: https://github.com/OfficeDev/office-ui-fabric-react/pull/10478.
