### ISSUE TITLE
[BasePicker] Allow programatic triggering of showing suggestions

### ISSUE THREAD

**Issue by richardtagger** [OfficeDev/office-ui-fabric-react#10409]
Design have asked to be able to trigger suggestions being visible after every item is selected - currently seems to require a new focus or click. I can't find a way to achieve this with the current API but may be overlooking something. An imperative interface such as `showSuggestions()` on the ref could work?

#### What component or utility would this be added to

BasePicker

#### Have you discussed this feature with our team, and if so, who

No

**Comment by natalieethell** [comment]
Hey @richardtagger so it looks like this functionality doesn't exist in base picker, but it does exist on floating picker. 

`IBaseFloatingPicker` has a property called `showPicker`, implemented by `BaseFloatingPicker`, which can be used to show the picker suggestions. Here's a code sandbox with an example of how to use that method with the FloatingPeoplePicker: https://codesandbox.io/s/floating-picker-opens-2uiqm. Floating.tsx contains most of the code.

Would using the floating picker work for your scenario?

**Comment by richardtagger** [comment]
Thanks @natalieethell - for some reason I didn't get an email for you reply. Investigating the floating picker option now
