### ISSUE TITLE
node_modules/office-ui-fabric-react/lib/Icon has no exported member 'FontIcon'

### ISSUE THREAD

**Issue by hoangvnguyenkms** [OfficeDev/office-ui-fabric-react#10402]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by natalieethell** [comment]
@hoangvnguyenkms What version of office-ui-fabric-react are you using?

**Comment by hoangvnguyenkms** [comment]
thanks for response, my version 6.189.2

Vào Thứ Tư, 11 tháng 9, 2019, Natalie Ethell <notifications@github.com> đã
viết:

**Comment by natalieethell** [comment]
@hoangvnguyenkms Gotcha, can you try upgrading your `office-ui-fabric-react` version and let us know if that fixes your issue? I don't see any references to FontIcon in 6.189.2.
