### ISSUE TITLE
Use selections with Basic List

### ISSUE THREAD

**Issue by AparnaPrasad** [OfficeDev/office-ui-fabric-react#10436]
#### Describe the feature that you would like added
I am using Basic List to display grid Items as given in the example here https://developer.microsoft.com/en-us/fabric#/controls/web/list
I have checkboxes and I want to be able to use selection to check. I have used selection zone and marquee zone

<MarqueeSelection selection={selection} isEnabled={true}>
                    <SelectionZone
                        selection={selection}>
                            <List 
                                key={`grid-list-${triggerChangeNew}`}
                                className='ms-ListGridExample'
                                items={this.props.job.files}
                                getItemCountForPage={this._getItemCountForPage}
                                getPageHeight={this._getPageHeight}
                                renderedWindowsAhead={2}
                                onRenderCell={this._onRenderCell}
                        />
                    </SelectionZone>
                    </MarqueeSelection>

Unless I trigger the entire list using key I don't see change in checkboxes. But this causes the entire list to reload.
  I want to be able to send selection object to List component like DetailsList  
#### What component or utility would this be added to

List (Basic List)

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

![Annotation 2019-09-12 150624](https://user-images.githubusercontent.com/1925970/64786554-f7155500-d56e-11e9-92e0-1d18e15666bf.png)

**Comment by natalieethell** [comment]
Hey @AparnaPrasad could you possibly provide a CodePen example for us demonstrating your scenario? Here's a basic List CodePen that has checkboxes but no Selection object, hopefully it can get you started: https://codepen.io/kevintcoughlin/pen/PoYyYqz. Thanks!

**Comment by AparnaPrasad** [comment]
That is a list of checkbox, which is what I have but I also want to be able to drag and select. MS office UI react provides <Selection> component which works with details list but not with basic list or atleast I am not able to find the documentation on how to use it

**Comment by natalieethell** [comment]
@AparnaPrasad why not use DetailsList?

**Comment by AparnaPrasad** [comment]
I need to use Basic list because I want to create a grid like view as below, and basic list provides support for that taking in height and width and adjusting automatically with screen width and height
![64786554-f7155500-d56e-11e9-92e0-1d18e15666bf](https://user-images.githubusercontent.com/1925970/65490712-eee1e180-dead-11e9-97b8-a02c66771baf.png)

**Comment by natalieethell** [comment]
@AparnaPrasad Got it. Have you checked out the implementation of TilesList? It's currently still in experiments, but it looks like it might be doing what you need, particularly with selection: http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/10546/merge/experiments/dist/index.html#/examples/tileslist. Check out the "TilesList with media tiles" example.

**Comment by AparnaPrasad** [comment]
> @AparnaPrasad Got it. Have you checked out the implementation of TilesList? It's currently still in experiments, but it looks like it might be doing what you need, particularly with selection: http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/10546/merge/experiments/dist/index.html#/examples/tileslist. Check out the "TilesList with media tiles" example.

Yes this is what I need.
