### ISSUE TITLE
Dropdown list item not correctly alligned in IE11

### ISSUE THREAD

**Issue by agtenr** [OfficeDev/office-ui-fabric-react#10437]
### Environment Information

- **Package version(s)**: "office-ui-fabric-react": "7.22.1"
- **Browser and OS versions**: IE11 / Windows 10

### Please provide a reproduction of the bug in a codepen:
https://fabricweb.z5.web.core.windows.net/oufr/7.22.1/#/examples/dropdown

#### Actual behavior:

When the drop down is opened in IE11 the text in the drop down items is not aligned correctly. The text is not centered vertically. In Chrome this works perfectly.

![Screenshot](https://i.ibb.co/ncwm6g6/2019-09-12-17-24-31.png)

#### Expected behavior:

When the drop down is opened in IE11 the text in the drop down items should be centered vertically.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by agtenr** [comment]
It seems that the problem can be fixed by setting the height of the buttons to 1vh instead of auto. (See screenshots below)
!["screenshot"](https://i.ibb.co/L9Hjyjs/2019-09-13-16-54-19.png)
!["screenshot"](https://i.ibb.co/9GKKhwk/2019-09-13-16-59-27.png)

**Comment by natalieethell** [comment]
Hey @agtenr thanks for reporting this - looks like a bug to me. We'll take a look at your proposed solution.
