### ISSUE TITLE
[Nested DetailsList] click on row of child list will trigger selection of row with same index in parent list

### ISSUE THREAD

**Issue by shiliangdn** [OfficeDev/office-ui-fabric-react#10454]
### Describe the issue:

I have a nested DetailsList, that in each row of the parent list, it has a child detail list there. The issue is when I click on one row of any child detail list, it will trigger the selection in the parent detail list for the row with the same item index.

For example, The parent list has 3 rows, and in the 3rd row, it has a child detail list which has 2 row, when I click on the 2nd row of the child list, the 2nd row of the parent list will be selected, which is not desired.

**Comment by aneeshack4** [comment]
@shiliangdn Hello! I started a DetailsList Codepen https://codepen.io/aneeshack4/pen/eYOLodR - would you mind changing it to show your scenario? This will help show what the problem is clearly.

**Comment by shiliangdn** [comment]
Created new one with my issue repro: https://codepen.io/liashi/pen/KKPGppy, you can click on each sub item to see what's going on.

**Comment by aneeshack4** [comment]
@shiliangdn Have you tried `selectionMode={SelectionMode.none}` and `disableSelectionZone={true}`?

**Comment by shiliangdn** [comment]
Yes, I have tried that option, you can see in my codepen repro, it doesn't work.

**Comment by shiliangdn** [comment]
Any update on this?

**Comment by aneeshack4** [comment]
@shiliangdn This is working as intended to the best of my knowledge. To add the ability to have it not select the parent will take additional feature work and we currently don't have a codeowner for this component so I'll add it to the backlog for review.

**Comment by asplem** [comment]
@shiliangdn Did you ever come up with a workaround for this issue?
