### ISSUE TITLE
TeachingBubble isWide not allowing content to flow in the container

### ISSUE THREAD

**Issue by known-as-bmf** [OfficeDev/office-ui-fabric-react#10452]
Setting `isWide` on a teaching bubble sets the container (`ms-TeachingBubble-content`) to a `maxWidth` of 456px but also sets the body (`ms-TeachingBubble-bodycontent`) to a `maxWidth` of 302px, leading to some empty space that could be used for the headline and body text.

example with `isWide: false`

![image](https://user-images.githubusercontent.com/11721166/64948245-f0405800-d876-11e9-80ea-80072cd57006.png)

example with `isWide: true`

![image](https://user-images.githubusercontent.com/11721166/64948269-fdf5dd80-d876-11e9-9413-1ba8ec4c2b4a.png)

It basically defeats the purpose of `isWide`.

This line seems to be the culprit : https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/TeachingBubble/TeachingBubble.styles.ts#L111

Maybe it should be 

```ts
      !isWide && {
        maxWidth: 302
      }
```

for now, there is a fix possible => passing custom styles to the TeachinBubble component:
```ts
<TeachingBubble
  styles={{ bodyContent: { maxWidth: 'none' } }} />
```

resulting in

![image](https://user-images.githubusercontent.com/11721166/64948789-1c100d80-d878-11e9-87fe-9fa91b87a4f3.png)

### Environment Information

- **Package version(s)**: 7.33.0
- **Browser and OS versions**: Tested on Chrome 76

### Please provide a reproduction of the bug in a codepen:

https://stackblitz.com/edit/react-ydusre?file=index.js

#### Actual behavior:

`isWide` making the conainer wider but not the content.

#### Expected behavior:

Allow the content to flow in the container.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

**Comment by aneeshack4** [comment]
@known-as-bmf Thank you for finding this bug & suggesting this fix! Feel free to chime in on the PR above that implements this.
