### ISSUE TITLE
[Screen reader - Azure Data Share - Sent Shares] In scan mode by narrator, extra tab is appearing inside 'Start time' calendar popup

### ISSUE THREAD

**Issue by sonimishra** [OfficeDev/office-ui-fabric-react#10450]
**User Experience:**
User who depends upon the narrator will be affected if extra tab is appearing on the screen when user navigate in scan mode of narrator so user cant interact with the control efficiently.

**Repro Steps:**
1-Navigate to Url:- https://portal.azure.com/?microsoft_azure_marketplace_ItemHideKey=DataShareExtensionHidden&feature.showassettypes=Microsoft_Azure_DataShare_InvitationsBrowse%2CMicrosoft_Azure_DataShare_DataShare#home
2-Sign in with valid credential.​
3-Navigate to search bar to search 'Data shares' and select it.​
4-Now, navigate and select already created 'Data Share'.​
5-Navigate to various left nav control and select 'Overview option.​
6-Navigate and select 'Sent Shares' control lying on Resource Overview blade.​
7-Now, navigate to 'Create' control and select it appearing under 'Sent Shares' option of Data Share.​
8-Navigate and select 'Settings' lying on Sent Shares blade.​
9-Naviagte to various control like Snapshot Schedule, Start time etc. and select 'continue' lying under 'Settings' section of Sent Shares.​
10-Turn on narrator and navigate 'Start time' calendar popup on scan mode
11-Verify that In scan mode by narrator, extra tab is appearing inside 'Start time' calendar popup or not.

**Actual Result:**
In scan mode by narrator, extra tab is appearing inside 'Start time' calendar popup. Also screen reader two times announces date and narrator focus doesn't appear when down arrow key is pressed for the first time.

**Expected Result:**
No extra tab should be taken inside 'Start time' calendar popup.

**Note:**
1. This issue doesn't exists under Chrome + JAWS.
2. This issue doesn't exists under Chrome + NVDA.

**MAS Reference:**
MAS 4.2.10 - Tracking of Focus and Selection Attributes
[MAS4.2.10_Extra focus.zip](https://github.com/OfficeDev/office-ui-fabric-react/files/3615069/MAS4.2.10_Extra.focus.zip)

Accessibility Insights! - Identify accessibility bugs before check-in and make bug fixing faster and easier.

**Comment by aneeshack4** [comment]
@sonimishra So is this reproing for you with Edge + Narrator only?
