### ISSUE TITLE
Cant download icon subsets from Office UI Fabric Icons Website

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-ui-fabric-react#10457]
The https://uifabricicons.azurewebsites.net website is not working anymore.
You can't download icon subsets. The getting subset spinner spins forever.

Tested in Chrome

**Comment by aneeshack4** [comment]
@barisbikmaz Can you provide more details on your environment? I just tried this on chrome and I was able to download instantly.

**Comment by aneeshack4** [comment]
This might actually be related to the latency issues @Jahnp mentioned in #10462 in this [comment](https://github.com/OfficeDev/office-ui-fabric-react/issues/10462#issuecomment-531941302).

**Comment by Jahnp** [comment]
Thanks for the heads-up @barisbikmaz , and for tagging me, @aneeshack4 . Please see my response in the linked issue:
> Short answer: I think I know the issue and can make a short-term patch to provide immediate relief.
>
> Longer answer: I'll need to investigate to verify, but I believe the tool has been hitting bottlenecks lately due to some infrastructure limitations. Essentially, the tool is likely hitting storage limits from leaving generated subsets directly on the server vs dropping them in something built for this purpose like blob storage. The symptoms of this limitation has been cropping up more frequently in the last month or so, which means we'll need to do some work to patch the storage/package generation issue.

**Comment by Jahnp** [comment]
Hey folks, sorry for the delay. Wanted to share that we've made the infrastructure improvements to the icons site, so we shouldn't be hitting these bottlenecks anymore. Please let me know if you hit any further issues with the site. Thanks again for reporting this one!
