### ISSUE TITLE
AMD bundling: strip out process.env.NODE_ENV which isn't automatically defined by bundling

### ISSUE THREAD

**Issue by aksingh** [OfficeDev/office-ui-fabric-react#10461]
https://github.com/OfficeDev/office-ui-fabric-react/commit/a9245feee547762f0c8c9935cbf39d737b86c519 clearly introduces a breaking change without bumping the major version.

If fabric folks intend to use the minor versions as breaking, then please add guidelines that consumers should be fixing their fabric versions precisely up to the patch version.

**Comment by dzearing** [comment]
@kenotron and @TheLarkInn for clarity.

This change did not change a single API surface. It did not modify a pixel, or change anything other than to remove the typedef check inside of code. I don't think this would be considered a breaking change.

Could you clarify how it broken you? Are you using a particular configuration that this broke?

**Comment by dzearing** [comment]
@kenotron and @TheLarkInn Are there things we could be doing better here? For example if the customer is using an older version of webpack, or is using another bundler, process is not guaranteed to be defined, which could likely break them.

**Comment by aksingh** [comment]
@dzearing We don't use webpack for one of our builds and that one just silently broke with this change. Basically everyone using AMD modules or non-bundled builds is likely to break silently on this.

**Comment by dzearing** [comment]
@aksingh Sorry for the trouble. This is not totally obvious on the best fix here. and AMD partners we knew about were able to add a process env definition to work around this.

Which project do you work on? I'd love to understand why you're still using AMD and not using any modern module system which supports building debug code, but more importantly would like a contact to talk about AMD needs.

Ultimately I think it's probably a mistake for us to export anything but ESM and potentially commonjs any more as there's no reason you couldn't just make an AMD bundle using a modern bundler like webpack to use within require.js loading.

@kenotron One idea would be to patch in process.env on boot if not defined. Or use a babel transform to strip out debug bits for AMD. Other ideas?

**Comment by kenotron** [comment]
There's an idea I had about post processing some of the code we transpile:

1. lib-commonjs code still requires "lib" from other libraries from our codebase (requiring our consumers to still run babel in jest)
2. lib-amd having their process.env stripped out

I am not against that post-transpile step. But have to think through what consequences are here.

**Comment by aksingh** [comment]
I work on the Planner team :) @dzearing we can chat offline reg other details

**Comment by dzearing** [comment]
We are looking at a fix to strip the process.env.NODE_ENV from amd build output to make this less janky. Sorry for the trouble.

I am going to rename this issue to reflect the true problem :)

**Comment by dzearing** [comment]
@kenotron assigned to you for now, a build step to find/replace probably would be good enough.

**Comment by dzearing** [comment]
@aksingh Please do reach out. It'd be great to have a contact so that we can run by any potential AMD impacting scenarios, but also we'd love to know sooner that we broke something unexpectedly!
