### ISSUE TITLE
When Virtualization is true, ScrollMode.bottom behaviour is being ignored

### ISSUE THREAD

**Issue by reficul31** [OfficeDev/office-ui-fabric-react#10473]
### Environment Information

- **Package version(s)**: 7.34.0 (Latest master branch)
- **Browser and OS versions**: Chrome Version 76.0.3809.132, Microsoft Edge 44.18362.329.0, Firefox Quantum 69.0 (64-bit) / Windows 10 Enterprise Edition

### Please provide a reproduction of the bug in a codepen:
Please find the [codepen link](https://codepen.io/reficul31/pen/eYOLyNW)
In order to reproduce the bug, use the PageUp and PageDown keys to see the functionality.

#### Actual behavior:
In the details list component I am encountering the behavior in chrome, wherein when I use focusIndex function of the componentRef and use ScrollMode.bottom or ScrollMode.top, it is being ignored. The item in focus is centered in the div and overwrites the ScrollMode argument provided to it.
But I am only observing this behavior when virtualization is true. When virtualization is false, this behavior is not encountered.

#### Expected behavior:
To see the expected behavior, use the codepen in Edge or Firefox. The expected behavior would be that the item should adhere to the ScrollMode argument provided to it.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

**Comment by aneeshack4** [comment]
@reficul31 So this is working as expected in Edge & Firefox but not in Chrome? Sounds like a browser issue - unless there's something you know of that we can do in the DetailsList code to add support for it in Chrome?

**Comment by reficul31** [comment]
Yes, if you have a look at the codepen I have submitted, Chrome behavior is different from other browsers. Even edge is behaving differently when using ScrollMode.top. Here is a summary of my findings regarding the same:
* In chrome ScrollMode is ignored completely and the element is always placed in the center of the div.
* In Edge and Firefox ScrollMode.bottom is followed but it ignores ScrollMode.top and places the element in the center of the div. Also there is some shaky selection when PageDown and PageUp is used multiple times.

Unfortunately, I will not be able to investigate this further. It is possible that I am not using the API as they are intended to be used. If that is the case, I would be grateful if someone could direct how I could emulate the same behavior using a different method which circumvents this bug.

**Comment by aneeshack4** [comment]
@reficul31 If chrome's ignoring ScrollMode I think that is a chrome issue... I think the scrolling behavior in edge is by design. @KevinTCoughlin might have more input into this.

**Comment by xugao** [comment]
@reficul31 - revisiting this issue. i tried [your codepen](https://codepen.io/reficul31/pen/eYOLyNW) and it's behaving the same in Edge/FF/Chrome on PageUp/PageDown. 
Is this still an issue to you? If so pls clarify what the expected behavior should be

**Comment by reficul31** [comment]
@xugao Thanks for revisiting this. In the codepen I am still encountering the same issue.
In the pen select the first item in the list and then press page down. Due to the usage of the ScrollMode.bottom we would expect that the next selected element be placed at the bottom of the list div but this is not the case. The selected item is placed in the middle of the list div. We would expect this behavior to be rectified in the case when virtualization is on.

**Comment by xugao** [comment]
@reficul31 - Sorry I still don't quite follow. Couple things with your codepen:
1. the `onKeyDown` handler you wrote is not getting invoked when first item in the list is selected AND you press page down. it's handled internally inside `DetailsList` (this is expected)
2.  It's behaving exactly the same in Edge/Chrome/FF on page down/up
3. are you trying to move focus to the very last item inside the list on Page down?
