### ISSUE TITLE
Typing to Scroll in Details List

### ISSUE THREAD

**Issue by reficul31** [OfficeDev/office-ui-fabric-react#10475]
#### Describe the feature that you would like added
An application that I was working on recently required the use of Details List. Previously the functionality being replaced by Details List was implemented using ```<select>``` element. Since ```<select>``` natively supports in Chrome the ability to type and scroll, I would really like to see this feature integrated in the base of Details List.

Type to scroll functionality here basically means: When we have the focus on the Details List component we cannot scroll to the item when we type its contents. For example, in a list of fruits when I type "gua" it should scroll down to the item Guava.

Since this feature is currently supported by HTML5 it would make sense to add support for it in this component as it can be used as a list of selectable items.

#### What component or utility would this be added to
Any feature requiring the replacement of the list of selectable items with Details List would find this feature very important. Specially those components in which the <select> element is being replaced by the Details List component.  

#### Have you discussed this feature with our team, and if so, who
Yes, I have discussed this feature with my team. Please reach out to me personally for any further discussions.

**Comment by aneeshack4** [comment]
@reficul31 Type to scrolls is a great feature but the specifics of this behavior will vary among all of the different use cases of DetailsList. For features like this, these differences make it hard to justify baking in just one specific variation into the shared Fabric control. This is likely achievable by using a combination of [`focusIndex`](https://github.com/OfficeDev/office-ui-fabric-react/blob/3682e4b101a264192d36d2a7ceb59ad877661e6f/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.types.ts#L50) and `scrollToIndex`.

**Comment by reficul31** [comment]
@aneeshack4 Yes currently this is being achieved using onKeyDown handlers on a ```<div>``` wrapping the DetailsList. We are making use of ```focusIndex``` and ```scrollToIndex``` among other APIs to emulate the functionality. The reason we reached out to Office UI Fabric React team was to find out if this could baked into the base component so that uniformity of user experience can be guaranteed across applications.

**Comment by reficul31** [comment]
Another behavior that I encountered while using the details list ```setIndexSelected``` and ```focusIndex``` functions.  

I have a function which based on certain computation calculates the next index which needs to be selected. If virtualization is true and the element is an un-rendered item then in the function ```focusIndex```, the ```scrollToIndex``` works but the focus is not set to the new item.

To clarify further, when the focus and selection are at index 0 and we use the ```focusIndex``` function to set focus to say index 160(which will be un-renderer if virtualization is true), then the item will be scrolled into view but the focus still remains on the item at index 0. You can check this since after using ```focusIndex``` using the arrow keys causes the focus to shift back to index 0.

Unfortunately, I was unable to reproduce this in the codepen.

**Comment by dzearing** [comment]
I like the functionality, but am not sure we'd want to bake this feature into the DetailsList because not every scenario needs this. Building huge monolithic components feels wrong, and DetailsList has certainly gone down this path. I wonder if there's a way we could have this feature be decoupled to allow a customer to opt into this without penalizing everyone.

Also minor thought, the SELECT element analogy is not completely comparable; it's more analogous to a TABLE which doesn't have word wheeling.

Having an adaptor might be a reasonable approach to keep the DetailsList from getting too big:

```tsx
const SelectableDetailsList = withWordWheeling(DetailsList);
```

**Comment by reficul31** [comment]
Hi @aneeshack4,
Any update on this? I again apologize I was not able to reproduce this in a codepen.

> Another behavior that I encountered while using the details list `setIndexSelected` and `focusIndex` functions.
> 
> I have a function which based on certain computation calculates the next index which needs to be selected. If virtualization is true and the element is an un-rendered item then in the function `focusIndex`, the `scrollToIndex` works but the focus is not set to the new item.
> 
> To clarify further, when the focus and selection are at index 0 and we use the `focusIndex` function to set focus to say index 160(which will be un-renderer if virtualization is true), then the item will be scrolled into view but the focus still remains on the item at index 0. You can check this since after using `focusIndex` using the arrow keys causes the focus to shift back to index 0.
> 
> Unfortunately, I was unable to reproduce this in the codepen.

**Comment by reficul31** [comment]
I wasn't able to fully reproduce the bug we are encountering but here is a code pen to show what we are encountering. [CodePen](https://codepen.io/reficul31/pen/bGbPKqv?editors=0011)

In the code pen you would see that on component mount I am selecting and setting the focus to the 100th element. But the list doesn't scroll to index 100 or even focus on that index.

In our functionality the list scrolls to the element but if the element is unrendered, then the focus is not passed to it. Are we using the APIs correctly? Is there some other way we can accomplish this?

**Comment by aneeshack4** [comment]
This is going to take some work beyond the scope of shield. Currently we don't have an owner for detailslist and we're in the middle of figuring out its future so for now, I'm going to unassign myself and add it to the backlog.
