### ISSUE TITLE
stopPropogation used in code doesn't allow key events to be handled outside the list

### ISSUE THREAD

**Issue by reficul31** [OfficeDev/office-ui-fabric-react#10474]
### Environment Information

- **Package version(s)**: 7.34.0 (Latest master branch)
- **Browser and OS versions**: Chrome Version 76.0.3809.132, Microsoft Edge 44.18362.329.0, Firefox Quantum 69.0 (64-bit) / Windows 10 Enterprise Edition

#### Actual behavior:
We are creating a functionality in our application where we render a list of items in a div. We would like to change the default key handlers of the list. But, as I see inside the Details List and List component, Office UI Fabric React uses ev.stopPropagation to stop the event from travelling up the DOM tree. This is causing difficulty in overwriting some of the keys which are essential for our functionality.

#### Expected behavior:
Specific keys that are blocked are the End key and the Esc key. The Esc key is handled inside the List component and ev.stopPropagation prevents the event to travel further up the DOM tree.

Is there another way that I can achieve this functionality? Currently I am wrapping the DetailsList in a ```<div>``` and adding onKeyDown listeners to its.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

**Comment by aneeshack4** [comment]
@KevinTCoughlin or @natalieethell Any thoughts on allowing users to overwrite the default key handlers?

**Comment by reficul31** [comment]
Hi @aneeshack4,
Any update? Or is there another way we can handle this?

**Comment by aneeshack4** [comment]
@reficul31 I'm not sure at this moment what we can do to overwrite the default key handlers - I'm going to add this to backlog for review. We currently don't have a codeowner for this component but we plan to overhaul it sometime in the future.
