### ISSUE TITLE
Stack with grow=true clips inner children

### ISSUE THREAD

**Issue by chenxinyanc** [OfficeDev/office-ui-fabric-react#10476]
### Environment Information

- **Package version(s)**: 7.31.0
- **Browser and OS versions**: Edge 78.0.268.3 Dev on Windows 10

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/xinychen/pen/rNBZJeQ

#### Actual behavior:
The heading gots clipped. In the actual scenario, it can be the tooltip of monaco-editor.
![image](https://user-images.githubusercontent.com/50703224/65035952-f02a8000-d97c-11e9-933e-e9805ab6700d.png)

#### Expected behavior:
If you override the root style of `<Stack>` with something like
```css
.my-stack {
  min-height: 0;
  overflow: visible;
}
```
You will get the expected behavior
![image](https://user-images.githubusercontent.com/50703224/65036067-27992c80-d97d-11e9-8f47-9a69c610d1d7.png)

The point is, you do not have to use `overflow: hidden` to restrict the size of flexbox children.

https://github.com/OfficeDev/office-ui-fabric-react/blob/47d134d6e3ecdcdfb8406c2ad581c2dc3fe57906/packages/office-ui-fabric-react/src/components/Stack/Stack.styles.ts#L160-L163

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: N/A

**Comment by aneeshack4** [comment]
@chenxinyanc Thanks for reporting this & suggesting a fix! I'm a bit confused, trying to get a full understanding of the issue: looking at all the squares - why did the heading get clipped in the first place? Because grow pushed the items to take up more of the container? That doesn't make sense though since the heading in your codepen is part of the overall stack with the grow = true.

**Comment by chenxinyanc** [comment]
I'm placing a monaco-editor inside the `<Stack>`, and the editor has auto-completion / tooltip etc. that is layoued with `position: relative`, like the `<h1>` here in the CodePen.

The heading here is intentionally applied with `position: relative` and an `left/top` offset to demonstrate my scenario: the tooltip of monaco-editor, because I couldn't properly set up such editor in CodePen.

You can see the effect of `overflow: hidden` with a real monaco-editor here: https://microsoft.github.io/monaco-editor/playground.html,
replacing `HTML` tab with
```html
<div id="container" style="width: 50%; height: 20%; overflow: hidden; border: 1px solid;"></div>
```
![test](https://user-images.githubusercontent.com/50703224/65095040-1fc79f80-d9f2-11e9-8e1e-74387a950a95.gif)

The floating tooltip will be clipped inside a `<Stack grow>` because it has `overflow: hidden`.

**Comment by aneeshack4** [comment]
Thank you @chenxinyanc for the detailed explanation!

**Comment by chenxinyanc** [comment]
Thanks for the change!

Then I think I will need to add a rule of `min-width: 0; min-height: 0` on my side because I have a scrollable `<div>` inside the stack container and I don't want the content of `<div>` to extend the stack container (itself is a flex-box item with `grow` enabled).
