### ISSUE TITLE
Tooltip not showing if content is truncated

### ISSUE THREAD

**Issue by rexkenley** [OfficeDev/office-ui-fabric-react#10480]
### Environment Information

- **Package version(s)**: 7.34.0
- **Browser and OS versions**: Windows 10 Chrome 76

### Describe the issue:

The tooltip will not show if the content is truncated in a column in a detailist row.

//< span>
//  <TooltipHost
//    content={contentText}
//    id={getId("tooltipHost")}
//    calloutProps={{ gapSpace: 0 }}
//   delay={TooltipDelay.zero}
//    directionalHint={DirectionalHint.leftCenter}
//    styles={{ root: { display: "inline-block" } }}>
//    {contentText}
//  </ TooltipHost>
// </ span>
#### Actual behavior:

Nothing shows for short column
![image](https://user-images.githubusercontent.com/10548251/65067850-7632d080-d955-11e9-8e9e-960a65fb94bf.png)

Tooltip shows if column is expanded
![image](https://user-images.githubusercontent.com/10548251/65067869-821e9280-d955-11e9-8b4c-be56a3cbbd10.png)

#### Expected behavior:

Tooltip should show with the content that is too long for column to display

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? I don't know how to do this yet.

Requested priority: Normal

**Comment by aneeshack4** [comment]
@rexkenley Thanks for reporting this! How did you wrap the items with the `<TooltipHost>`? I started a codepen with DetailsList that has items overflowing: https://codepen.io/aneeshack4/pen/NWKOWje could you add the Tooltip to it so I can get a repro? That'll help me debug why Tooltip isn't showing in this scenario.

**Comment by rexkenley** [comment]
Thank you aneeshack4.

https://codepen.io/rexkenley/pen/zYOmNyo

**Comment by rexkenley** [comment]
Well, I tinkered with the pen a bit and found that the cause of tooltip not showing is the enclosing span tags. Once I removed the span, the tooltip shows. 

Thanks for the quick response!
