### ISSUE TITLE
Documentation site is not loading

### ISSUE THREAD

**Issue by gogogadgetearl** [OfficeDev/office-ui-fabric-react#10500]
### Environment Information

- **Package version(s)**: n/a
- **Browser and OS versions**:
    - Chrome 76 (with & without uBlock enabled)
    - Edge 44 (with & without uBlock enabled)

### Please provide a reproduction of the bug in a codepen:

n/a

#### Actual behavior:

Spinner continues to spin with no result.

![image](https://user-images.githubusercontent.com/23261316/65184376-5eca1500-da33-11e9-87fc-acb59ffdc62b.png)

![image](https://user-images.githubusercontent.com/23261316/65184429-77d2c600-da33-11e9-9847-d7f3b1271b9a.png)

![image](https://user-images.githubusercontent.com/23261316/65184502-9fc22980-da33-11e9-9a0f-e9a99b9f0798.png)

#### Expected behavior:

Documentation site works.

### Priorities and help requested:

Are you willing to submit a PR to fix?
_If I could._

Requested priority:
_/shrug_

Products/sites affected:
 - https://developer.microsoft.com/en-us/fabric

**Comment by aneeshack4** [comment]
@gogogadgetearl Are you sure your internet connection/everything else in your environment is solid? It's loading for me on Chrome, Edge, and IE11 - not able to repro this. Also not sure what uBlock is - perhaps the presence of that on your system is causing this.

**Comment by gogogadgetearl** [comment]
Oof.  Same issue across multiple browsers from the same machine, which made me think it was either on the server end or at the OS level (DNS caching of a bad IP perhaps?).

After way too much troubleshooting on my own machine...a reboot seems to have fixed it.  /facepalm.

Sorry!
