### ISSUE TITLE
Customizations: perf requests

### ISSUE THREAD

**Issue by phkuo** [OfficeDev/office-ui-fabric-react#10513]
For the Customizations framework, I'd like to see two things:

1) A way to batch updates. For example, you can only apply one scoped setting at a time. If you do this in a for loop, then ever single iteration is triggering a forced update. On a SharePoint page this freezes the whole page for almost 1s on Chrome. So either a batchedUpdate() utility function, or a way to set multiple settings and scopedSettings at one time (similar to how you can do it in <Customizer>).
2) A way to set Customizations _without_ triggering an update. Since the forceUpdate can be very expensive, I might want to defer it to a later time to trigger manually, or not trigger one at all because I know the Customization won't affect anything that's currently rendered (but newly rendered components will pick it up).

**Comment by dzearing** [comment]
Let's talk about ideas. This makes sense; it's the eventing firing that you really want to debounce.

**Comment by phkuo** [comment]
I'm actually going to start working on the second one this week. The perf regerssion from applying the fluent-theme Customizations is too much to ignore.

**Comment by phkuo** [comment]
Point 2 is here: https://github.com/OfficeDev/office-ui-fabric-react/pull/10549

**Comment by phkuo** [comment]
Point 1 is actually covered by point 2, you just use suppressUpdates() and then say `Customizations.applySettings({})` which will trigger an update.
