### ISSUE TITLE
Axis Labels for LineChart does not display properly When the Y coordinate value is large

### ISSUE THREAD

**Issue by luckyrass** [OfficeDev/office-ui-fabric-react#10518]
### Environment Information

- **Package version(s)**: (@uifabric/charting 0.135.0)
- **Browser and OS versions**: (All browser)

#### Actual behavior:

- Y-axis label can only display up to five digits.

![image](https://user-images.githubusercontent.com/12230173/65209178-e2364580-dac9-11e9-8c84-53cf238cbf70.png)

- X-axis label can not display date properly when time format is '%m/%d/%Y'.

![image](https://user-images.githubusercontent.com/12230173/65209454-c54e4200-daca-11e9-89be-4545b2ff441d.png)

#### Expected behavior:

![image](https://user-images.githubusercontent.com/12230173/65209765-997f8c00-dacb-11e9-846d-9b9933810de7.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

**Comment by aneeshack4** [comment]
@srideshpande Where is the width of the axis labels set? I thought it would've been in LineChart.base.tsx [where the YAxis gets created](https://github.com/OfficeDev/office-ui-fabric-react/blob/490a18220819833643f33985926b060bac28732d/packages/charting/src/components/LineChart/LineChart.base.tsx#L288).
