### ISSUE TITLE
ContextualMenu: Bounds prop should align with CalloutBase

### ISSUE THREAD

**Issue by jspurlin** [OfficeDev/office-ui-fabric-react#10517]
#### Describe the feature that you would like added
CalloutContent was recently updated to allow creators to pass a function as bounds and it returns the bounding rect. The ContextMenuProps need to be updated to allow that same functionality

#### What component or utility would this be added to
ContextualMenu

#### Have you discussed this feature with our team, and if so, who
I discussed the Callout change with Jon when it was being made, but I haven't talked to anyone about the ContextualMenu aspect

#### Additional context/screenshots
The bounds just gets passed to Callout so the available types it can stake should align

**Comment by aneeshack4** [comment]
Thanks for already submitting a fix to this @jspurlin!!
