### ISSUE TITLE
[Accessibility][Suggestion][Keyboard navigation]: (ComboBox / Button ContextualMenu) List items should only be navigable through up/down arrow keys.

### ISSUE THREAD

**Issue by kenotron** [OfficeDev/office-ui-fabric-react#10514]
### Environment Information

- **Package version(s)**: 7.x
- **Browser and OS versions**: Chrome

### Describe the issue:

The contextual menu does not dismiss when pressing Tab key. This issue came from #6390. It is the last remaining issue.

### Repro Steps

1. Open 'https://developer.microsoft.com/en-us/fabric#/components/commandbar' in Edge.
2. Navigate to 'New control' under CommandBar with overflowing menu items' using tab key.
3. Observe the issue.

### Actual 

It navigates to the next item.

### Expected

Closes the contextual menu.

**Comment by kenotron** [comment]
@betrue-final-final Can you give us guidance here? What should the behavior be for the contextual menu when the tab key is pressed?

**Comment by kenotron** [comment]
@joschect - FYI had an question about this behavior. Please do chime in if you feel strongly one way or another.

**Comment by betrue-final-final** [comment]
Trying to understand the exact issue. You’re saying that when in the menu this suggests that tab should navigate to outside the menu?

In a menubar like the command bar, Tab should dismiss the menu and take you to the next item in the bar. 

Tab should do nothing in a context menu.

**Comment by jspurlin** [comment]
Overall, this is a usability/subjective bug.

More specifically, inputs in menus must use TAB to move focus out of them because we won't want arrow keys to move focus out of the input.

There's some potential things that could be done here in the future if we (Office/MS) take a different approach to these types of control

Closing this
