### ISSUE TITLE
Animations leave invisible element behind

### ISSUE THREAD

**Issue by phkuo** [OfficeDev/office-ui-fabric-react#10512]
Ran into an issue earlier using the animations, they fade out using opacity. However, with opacity:0, the element is still interactable. That means hover events were still triggering, and there were invisible clickable links. This should instead be changed to visibility:hidden (which can be animated) or display:none (which cannot be animated, afaik).

**Comment by phkuo** [comment]
I don't know if this was true of all animations, but definitely the slidingOut ones I was using.

**Comment by dzearing** [comment]
@Jahnp this one is interesting. I didn't think you could animate visibility.

**Comment by dzearing** [comment]
If it's a timeline, you can always set it at 100%

**Comment by dzearing** [comment]
Found it; in AnimationStyles.ts

```tsx
const FADE_OUT: string = keyframes({
  from: { opacity: 1 },
  to: { opacity: 0 }
});
```

**Comment by phkuo** [comment]
To hack around it, I used `transition: 'visibility ' + animationDuration + ' ' + animationDelay` and just used a switch to set it on/off.
