### ISSUE TITLE
Items in CommandBar that use commandBarButtonAs get re-mounted every time CommandBar re-renders.

### ISSUE THREAD

**Issue by smoak** [OfficeDev/office-ui-fabric-react#10523]
### Environment Information

- **Package version(s)**: 7.36.0
- **Browser and OS versions**: Firefox, Chromium, Arch Linux (doesn't seem browser or OS specific)

### Please provide a reproduction of the bug in a codepen:

Repro in codepen (make sure the codepen console is open). You'll see that "AttachmentsButton" and "AttachmentsButtonCommandBarButtonAs" are mounted every time CommandBar is re-rendered (forcing a re-render of CommandBar by having a 1 second timer that updates internal state).

https://codepen.io/smoakin/pen/XWrxxbY?editors=1001

#### Actual behavior:

commandBarButtonAs components get re-mounted every time CommandBar re-renders.

#### Expected behavior:

commandBarButtonAs components to be mounted only once.

### Priorities and help requested:

Are you willing to submit a PR to fix? Maybe? I don't really know the ins and outs of fabric.

Requested priority: High

Products/sites affected: Yammer

**Comment by aneeshack4** [comment]
@smoak CommandBar has to re-render every time it gets new props because it has to recalculate to see if it still fits which is why it remounts with each render. This is working as intended. You can see this behavior in the [`resizeGroup` code](https://github.com/OfficeDev/office-ui-fabric-react/blob/571720b685426426ab6079c2de02e0c93db43340/packages/office-ui-fabric-react/src/components/ResizeGroup/ResizeGroup.base.tsx#L344) which is what CommandBar uses under the hood.

**Comment by swese44** [comment]
@aneeshack4 can you help us understand why CommandBar needs to create a new component tree instead of allowing React to update the existing tree before it checks for resize?

**Comment by aneeshack4** [comment]
@swese44 I believe we have considering briefly making this only have seingle rendering @joschect @micahgodbolt are the component authors & might have more to say on this

**Comment by micahgodbolt** [comment]
i'd have to defer to @christiango - he ended up doing the majority of the work in the resize group. I'm not sure if it was possible to persist the measured copy through all of the mutations or not.

**Comment by christiango** [comment]
ResizeGroup used to work that way @swese44, but we got feedback from partners that they were seeing the screen flicker between states on some browsers (I think it was IE).

**Comment by aneeshack4** [comment]
@swese44 Haven't heard back from you in a while so I'm assuming you've got the information you need so I'll go ahead and close this but if you have any more follow ups please ping us.
