### ISSUE TITLE
[Accessibility][Programmatic access]:  Inappropriate name defined for All emails together dialog which appears on pressing enter on open dialog button under Default Dialog

### ISSUE THREAD

**Issue by jdhuntington** [OfficeDev/office-ui-fabric-react#10540]
Breakout from #8061

Tracking all of the issues brought up with the 2/20 accessibility pass on Dialog control
Details on individual bugs can be found on [Sharepoint](https://microsoft-my.sharepoint.com/:x:/r/personal/v-amaver_microsoft_com/_layouts/15/Doc.aspx?sourcedoc=%7B8704792b-ff92-40ce-969f-93c02c8b96a9%7D&action=default&uid=%7B8704792B-FF92-40CE-969F-93C02C8B96A9%7D&ListItemId=1824&ListId=%7B395E1ECB-5002-440E-81C5-6A090E98077C%7D&odsp=1&env=prodbubble)

**Comment by joschect** [comment]
This is working as intended, the demo page is showing how a hidden label can be used to add information to a dialog. The heading one is also then read. An issue appears to be that the description id is not read, but that is an issue with narrator as aria supports having both a label-id and described-by id.
