### ISSUE TITLE
[DetailsList] DetailsList Component does not follow Grid Role design pattern for keyboard accessibilty

### ISSUE THREAD

**Issue by adharpicstore** [OfficeDev/office-ui-fabric-react#1055]
#### Describe the issue:

DetailsList Component has  role as "Grid" but it does not follow Grid Design pattern for keyboard accessibility.

#### Actual behavior:
Pressing Up and down arrow selects the next or previous row.

#### Expected behavior:

Grid Design pattern works on cell. By Pressing Up and Down buttons user navigate to next or previous cell in the same column. But in our case we navigate to next row and no column is selected. 
Ref: https://www.w3.org/TR/wai-aria-practices-1.1/#grid

**Comment by dzearing** [comment]
We have discussed this internally and believe that we're doing the right thing. There are two types of  grid layouts; grid that are meant to be navigated by rows, and grids which can be navigated by cells. We're following the former. Our accessibility experts are working to refine the w3 definition for this particular case.
