### ISSUE TITLE
Color for tick mark in Checkbox seems to be incorrect in AzureCustomizationsLight

### ISSUE THREAD

**Issue by chenxinyanc** [OfficeDev/office-ui-fabric-react#10552]
### Environment Information

- **Package version(s)**: 7.31.0
- **Browser and OS versions**: 78.0.276.2 dev

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/xinychen/pen/jONQxdq

#### Actual behavior:
![image](https://user-images.githubusercontent.com/50703224/65315753-383ee200-dbcb-11e9-8b9d-a26b40a19574.png)

#### Expected behavior:
Comment out the `latest` part and uncomment the `v6` part in the HTML panel to see the behavior of the previous version.
![image](https://user-images.githubusercontent.com/50703224/65316749-19d9e600-dbcd-11e9-9c9c-5392243a4940.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: N/A

**Comment by c-ryan-k** [comment]
Hey @chenxinyanc - unfortunately our current azure-theme package is still based around Fabric 6 - the themes are not 100% ready to be used in Fabric 7 yet due to inconsistencies like these.

**Comment by aneeshack4** [comment]
@chenxinyanc So it sounds like it's best to wait until Azure revamps their themes before using them in Fabric 7. I'll resolve this as external as the Azure team is responsible for these.
