### ISSUE TITLE
ListPeoplePicker adds member unintentionally on suggestions pane dismissal.

### ISSUE THREAD

**Issue by 548661288** [OfficeDev/office-ui-fabric-react#10563]
### Environment Information

- **Package version(s)**: (6.195.1)

This is similar to https://github.com/OfficeDev/office-ui-fabric-react/issues/3349
I understand that it might be by design for a basic picker, but for people picker, this creates a security issue without user noticing his unintended action, which adds an irrelevant person to the team. This person can have all the privilege to the product.

For example, current user firstly wants to add Jane Doe to the team, he types "Jane", which gives him a list of people whose first name is Jane. He then realized something needs to be done before adding that person and dismissed the suggestions. This accidentally adds the person on the top of the suggestions to the team without his intention.

#### Actual behavior:

A person gets added when dismissing the suggestion pane. There's no way to deselect the suggested item

#### Expected behavior:
Provide a way to deselect the item on the suggestion pane. Or provide a boolean prop to disable auto adding functionality.

### Priorities and help requested:

Are you willing to submit a PR to fix? Maybe

Requested priority: Blocking

Affected Product: Microsoft Planner

**Comment by aneeshack4** [comment]
@548661288 Have you tried the [onDismiss callback solution](https://github.com/OfficeDev/office-ui-fabric-react/issues/3349#issuecomment-353143009) suggested in #3349?

**Comment by 548661288** [comment]
@aneeshack4 After another visit this worked for me. Thanks a ton. I tried onDismiss solution earlier but didn't trigger preventDefault() inside onDismiss. Also the name onDismiss confused me as it's under BasePicker, but overrides onSuggestionDismiss instead of onPickerDismiss.
Anyways, thanks. Closing.
