### ISSUE TITLE
Nav: Chevron button doesn't need backgrounds in any state

### ISSUE THREAD

**Issue by phkuo** [OfficeDev/office-ui-fabric-react#10565]
Nav's chevron button's background should be permanently set to transparent because it should always have the same bg color as the item. (This is just code cleanup, this does not currently manifest visually at all.)
Same with command bar menu button chevrons.

**Comment by joschect** [comment]
@phkuo it looks like Nav's chevron button background is already set to [transparent](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Nav/Nav.styles.ts#L168)

As for the command bar menu button chevrons, we could add that to their styling.
