### ISSUE TITLE
Narrator is not providing information about "no.of results found" after performing a will card search in Search Box"

### ISSUE THREAD

**Issue by SyedRehmanRazvi** [OfficeDev/office-ui-fabric-react#10577]
User Experience:
Users who rely on screen readers are getting affected as Narrator is not providing information about "no.of results found" displayed after performing search.

Test Environment:
OS: Win 10
OS Version: 1903 (OS Build 18323.1000)
Browser: Edge
URL: https://fabricweb.z5.web.core.windows.net/oufr/7.14.0/#/examples/searchbox
Screen Reader: Narrator

Repro Steps:
Step 1: Start Narrator
Step 2: Open above URL using EDGE browser
Step 3: Navigate to "SearchBox with fixed width and custom event handling" edit field.
Step 4: Verify narrator is providing information about "no.of results found" when searching

Actual:
Narrator is not providing information about "no.of results found" when searching

Expected:
Narrator should provide information about "no.of results found" when searching
![image](https://user-images.githubusercontent.com/53210862/65499216-e784fd00-deda-11e9-8a43-d9d9e0067348.png)

**Comment by dzearing** [comment]
This is not expected for the example code illustrating Searchbox usage with custom widths.
