### ISSUE TITLE
ChoiceGroup selected state is not centered in circle

### ISSUE THREAD

**Issue by StephenRiceMSFT** [OfficeDev/office-ui-fabric-react#10573]
### Environment Information

- **Package version(s)**: Fabric
- **Browser and OS versions**: Windows 10, Edge (Chromium)

#### Actual behavior:

Selected state in a Choice Group is off-center and varies based on implementation. See attached picture. Check the Choice Group page for details. 
<img width="342" alt="Choice Group Not Centered" src="https://user-images.githubusercontent.com/47989256/65464618-19309200-de0f-11e9-8ad7-b66f1c2295a6.png">

#### Expected behavior:

Selected state of Choice Group is centered

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low)
Normal

Products/sites affected: (if applicable)
OneDrive/SharePoint, all products using Choice Group in Fabric

**Comment by StephenRiceMSFT** [comment]
@Jahnp as FYI.

**Comment by joschect** [comment]
@StephenRiceMSFT is it only in the new Edge browser that you're seeing this?

**Comment by StephenRiceMSFT** [comment]
Looks like it. Both Chrome and Firefox appear to have it centered properly.

**Comment by micahgodbolt** [comment]
Chromium edge is looking fine now. There will always be some issues of subpixel rendering, especially if you are at different zoom levels. I don't believe this an addressable issue.

![image](https://user-images.githubusercontent.com/1434956/71744732-03bf0100-2e1d-11ea-9de2-7e9129810283.png)
