### ISSUE TITLE
[Accessibility][Programmatic access]: Selected state is not defined for controls under 'Nav bar of links each with unique keys and empty URLs’ section.

### ISSUE THREAD

**Issue by jdhuntington** [OfficeDev/office-ui-fabric-react#10595]
Tracking all of the issues brought up with the 1/25 accessibility pass on Nav control 
Details on individual bugs can be found on [SharePoint](https://microsoft-my.sharepoint.com/:x:/r/personal/v-amaver_microsoft_com/_layouts/15/Doc.aspx?sourcedoc=%7B8b59713f-87bb-4a5e-ad92-2b7b3a0ef589%7D&action=default&uid=%7B8B59713F-87BB-4A5E-AD92-2B7B3A0EF589%7D&ListItemId=1721&ListId=%7B395E1ECB-5002-440E-81C5-6A090E98077C%7D&odsp=1&env=prodbubble) 

This issue is tracking a single entry from #7803

**Comment by khmakoto** [comment]
The section described in this is no longer existing in our examples page, so I'll close this bug accordingly.
