### ISSUE TITLE
[Icon Tool] How can we use Fabric icons with JSON (needs to be used for View Formatting) button elements so that using the 'button' element doesn't turn the icon into a blank square? Thank you!!!!

### ISSUE THREAD

**Issue by marissasinai** [OfficeDev/office-ui-fabric-react#10603]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by micahgodbolt** [comment]
This is probably a question for @Jahnp

**Comment by Jahnp** [comment]
Thanks for the heads-up @micahgodbolt .

@marissasinai , could you clarify the question in the title a little? Do you have a codepen or other repro environment to demonstrate the issue you're having?

Just a note that the JSON produced by the icons tool is not meant to be used directly in an application, but instead checked in with your source code and used to update/maintain the subset.

**Comment by marissasinai** [comment]
This answers my question, and I was able to get everything working on our tenant! Thanks so much!

Marissa
