### ISSUE TITLE
Unable to set custom Overflow Icon in Breadcrumb component

### ISSUE THREAD

**Issue by matidomingues** [OfficeDev/office-ui-fabric-react#10612]
### Environment Information

- **Package version(s)**: 6.204.2
- **Browser and OS versions**: All

#### Actual behavior:

If the default icon library is not loaded, the result is button that contains no icon:

![Screen Shot 2019-09-24 at 7 09 52 PM](https://user-images.githubusercontent.com/816129/65563609-01d0d200-deff-11e9-8e53-7f9c13c565ea.png)

We generally avoid this issue by using an icon custom render function, but in the case of the Overflow Button there is none.

#### Expected behavior:

Being able to set a render function for the icon.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: Teams for Edu

**Comment by matidomingues** [comment]
Hey @khmakoto, we really need to get this fixed for a new feature, is there any way you can help me out by reviewing this bug and the attached pr?

Thanks!!

**Comment by dzearing** [comment]
@matidomingues are you unblocked here? I noticed we got a fix in for 6, but not for 7. Could you please cherrypick the change into master as well so that you don't lose the change on 7 updates later?

**Comment by matidomingues** [comment]
@dzearing sorry for the delay. Yup, we got everything working :) I just cherry-picked and opened the PR.

Thanks!!
