### ISSUE TITLE
Narrator is not reading label(description) field of choice group in Chrome browser.

### ISSUE THREAD

**Issue by HarkeshS** [OfficeDev/office-ui-fabric-react#10614]
<!--
Issue--Narrator is not reading label(description) field of choice group in Chrome browser. it was working fine in Edge
Same issue is repro at office fabric site
https://developer.microsoft.com/en-us/fabric#/controls/web/choicegroup 

### Environment Information
Issue occurred in chrome latest version

### Describe the issue:

Issue--Narrator is not reading label(description) field of choice group in Chrome browser. it was working fine in Edge

#### Actual behavior:

Narrator is not reading label(description) field of choice group in Chrome browser. 

#### Expected behavior:

Narrator should read label(description) field of choice group in Chrome browser.  as it is reading in Edge browser.

**Comment by joschect** [comment]
@HarkeshS To help us could you provide some more description? Are you talking about using the Microsoft narrator in edge?

**Comment by HarkeshS** [comment]
@joschect c--Yes we have checked in Microsoft narrator in edge. and it was reading description label properly for choice group, but not reading in chrome.
Kindly donot close this request.

**Comment by HarkeshS** [comment]
@joschect--So what will be the next course of action for Chrome support?

**Comment by joschect** [comment]
@HarkeshS Per our documentation, we do not support Chrome and Narrator. A bug can be filed against Chrome since Narrator works as intended with edge.
