### ISSUE TITLE
'TeachingBubble with Illustration' code example is incorrect

### ISSUE THREAD

**Issue by larnera** [OfficeDev/office-ui-fabric-react#10617]
The'TeachingBubble with Illustration' code example doesn't include 'illustrationImage' in the properties.

https://developer.microsoft.com/en-us/fabric#/controls/web/teachingbubble
https://codepen.io/pen/?&editable=true

Cheers!

**Comment by joschect** [comment]
@larnera thanks for submitting this! It's definitely a bug of some sort. I can see in that we do have that property present in the example and so it looks like we're just referencing the wrong file in that example. I'll get it fixed!

**Comment by larnera** [comment]
Thanks for fixing this guys.
