### ISSUE TITLE
[TextField][type="number"]: up/down arrows not visible on Edge browser.

### ISSUE THREAD

**Issue by neeraj-khanna** [OfficeDev/office-ui-fabric-react#10616]
### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**: 
  - **Browser:** MS Edge (44.18362.329.0)
  - **OS:** Windows 10 version 1903

### Describe the issue:

Use TextField control with type as `number` and observe.
Up and Down arrows not visible on Edge browser whereas they are visible on Chrome.

### Please provide a reproduction of the issue in a codepen:
<https://codepen.io/neeraj-khanna/pen/ExYMWzg>

#### Actual behavior:
Up and Down arrows not visible on Edge browser.

#### Expected behavior:
Up and Down arrows should be visible on Edge browser as in Chrome.

**Comment by joschect** [comment]
@neeraj-khanna This is a browser implementation detail that is unrelated to the fabric text box. You can see the same behavior if you look at a vanilla text field in this [codepen](https://codepen.io/slimemold/pen/NWKmQgw?&editable=true).

That being said, we have SpinButton already which is specifically meant to be used with the spin buttons.

It looks like it is possible to style the TextField such that it won't show those buttons. @ecraig12345 do you have an opinion about this?

**Comment by joschect** [comment]
@neeraj-khanna here's the [spinbutton](https://developer.microsoft.com/en-us/fabric#/controls/web/spinbutton) which might do what you want.

**Comment by ecraig12345** [comment]
I don't think we should add arrow support directly in the TextField. If you always want arrows, using SpinButton is the best solution.

**Comment by joschect** [comment]
@ecraig12345 Got it, I'll submit a pr to hide the arrow buttons that the browser is adding.

**Comment by xugao** [comment]
even though it makes our browser inconsistently display the control, i like the behavior with arrows we have in chrome. should we really remove that in exchange of consistent? I am curious what our user @neeraj-khanna thinks
