### ISSUE TITLE
[DetailsList][Header Navigation]: control goes to column with no header text

### ISSUE THREAD

**Issue by neeraj-khanna** [OfficeDev/office-ui-fabric-react#10622]
### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**:
  - **Browser:** all
  - **OS:** Windows 10 version 1903

### Describe the issue:
If we don't define the name property for a column and we traverse the header using keyboard, control goes to column header with no text. Since there is no visible focus, it seems to be confusing.

### Please provide a reproduction of the issue in a codepen:
<https://codepen.io/neeraj-khanna/pen/gOYEXRa>

#### Actual behavior:
Control goes to column with no header

#### Expected behavior:
Control should not go to blank column header or the focus should be visible.

### Documentation describing expected behavior
NA

**Comment by joschect** [comment]
This does look like a bug. Could you explain a bit more of your use case? Even if there is no header text it seems like focus should go to that header as there could be an aria-label. Could you explain your use case a bit more?

**Comment by neeraj-khanna** [comment]
We are using some columns to display actionable icons (or icon buttons) and these columns does not contain a header. Focus going to header of such columns is not expected and there is no way to skip the headers of such columns.
