### ISSUE TITLE
Documentation - IShimmeredDetailsListProps implementation missing

### ISSUE THREAD

**Issue by Ralms** [OfficeDev/office-ui-fabric-react#10629]
IShimmeredDetailsListProps implementation missing in documentation: 
https://developer.microsoft.com/en-us/fabric#/controls/web/shimmer#implementation

### Priorities and help requested (not applicable if asking question): Documentation issue, not critical as we can see in VS Code also, just inconvenient the first times. 

Requested priority: (Blocking, High, Normal, Low) Low

**Comment by dzearing** [comment]
I am seeing the list of props underneath the section header.

**Comment by Ralms** [comment]
Hi @dzearing ,

Please don't confuse IShimmerProps with IShimmeredDetailsListProps.

The one that is missing is the specific props to the DetailsList, which there is an example, but not the implementation with all the available props.

I've even validated with a simple page search (Ctrl + F).

**Comment by dzearing** [comment]
@Ralms oh thanks for the clarification!

**Comment by dzearing** [comment]
I wouldn't expect this to be in the shimmer docs, but probably on their own and linked from DetailsList.

**Comment by Ralms** [comment]
@dzearing 
Its a Shimmer specific interface, would make sense to be in the same location as the example on my point of view.

**Comment by xugao** [comment]
Documentation for `IShimmeredDetailsListProps`  is on page: https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist
