### ISSUE TITLE
[Accessibility][DropDown]: Alt + Up/Down Arrow does not opens and closes the list.

### ISSUE THREAD

**Issue by nikhilexe** [OfficeDev/office-ui-fabric-react#1062]
Hi,
As per [Aria design patter for DropDown](https://www.w3.org/TR/2016/WD-wai-aria-practices-1.1-20160317/#combobox), **Alt + Up/Down Arrow** opens and closes the list but currently it is changing the value in the dropdown.

Please look into the issue and do the needful.

Thanks,
Nikhil

**Comment by gitjain** [comment]
Issue has been fixed so updating the status.
