### ISSUE TITLE
Disabled TextField values are not shown on ios

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/office-ui-fabric-react#10633]
### Environment Information

- **Package version(s)**: 7.28.1
- **Browser and OS versions**: Safari on ios 12.4.1

### Please provide a reproduction of the bug in a codepen:

Go to the official [ui-fabric site](https://developer.microsoft.com/en-us/fabric#/controls/web/textfield) and look at the disabled textfields. Both should have text "I am disabled"

#### Actual behavior:
Disabled textfield shows no value

#### Expected behavior:

Disabled textfield shows value greyed out

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by joschect** [comment]
@barisbikmaz Thanks for your submission. I am able to reproduce this 
![image](https://user-images.githubusercontent.com/20801176/65807595-03d7a280-e144-11e9-933d-3cb50ed80acf.png)

It seems that the problem happens in regular safari too. From what I can tell, the disabled background color of the safari text field happens to just match the disabled text color that we assign.

![image](https://user-images.githubusercontent.com/20801176/65807832-58c7e880-e145-11e9-9908-55f550e8b50e.png)

@betrue-final-final Do we know what background and foreground text colors should be for disabled text fields? We might have to mark them explicitly

**Comment by dhiv-nitt** [comment]
Do we have a fix for this yet ?

**Comment by betrue-final-final** [comment]
The correct color would be Gray20 (#f3f2f1)
