### ISSUE TITLE
[Panel] When overriding onRenderBody and not calling defaultRender the confirm on close feature is broken

### ISSUE THREAD

**Issue by Friedrikovic** [OfficeDev/office-ui-fabric-react#10632]
I believe you handle the drawing of the confirm dialog in the default onRenderBody. That's bad as you're making it possible for the user to break the feature, especially when you could do the confirm dialog rendering anywhere else where the user can't override the default behavior.

**Comment by joschect** [comment]
@Friedrikovic Thanks for your submission. Could you provide a codepen that reproduces this issue? Here is a basic [panel codepen](https://codepen.io/slimemold/pen/oNvRXYZ?&editable=true) to help you get started. It doesn't look like the panel has or controls a popup dialog by default.

**Comment by Friedrikovic** [comment]
My bad, I've mistaken your lib with another one that's used by my project that exposes a very similar Panel component
