### ISSUE TITLE
[Panel] Footer not rendering in the footer area

### ISSUE THREAD

**Issue by riosn-n** [OfficeDev/office-ui-fabric-react#10655]
### Environment Information

- **Package version(s)**: 7.39.1
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/riosn/pen/yLBWyOK

#### Actual behavior:

Footer content is rendered where main content ends.

#### Expected behavior:

Footer content should be rendered at the bottom.

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (High)

Products/sites affected: (if applicable)

PowerApps, Dynamics CRM

**Comment by dzearing** [comment]
I believe this is by design. 

Footer content gets stuck at the end of content, but as the content grows, it does not exceed the boundaries of the panel and lets the content scroll.

This is what I'm observing currently.

@betrue-final-final can confirm.

**Comment by riosn-n** [comment]
I just realized that there is a new prop isFooterAtBottom={true}.

If I remember correctly, in Fabric 6 the default was to have the footer at the bottom. In that case, maybe having this prop be true by default would make more sense?
