### ISSUE TITLE
TooltipHost background color isn't set by theme

### ISSUE THREAD

**Issue by isabelacmor** [OfficeDev/office-ui-fabric-react#10679]
### Environment Information

- **Package version(s)**: 7.29.0
- **Browser and OS versions**: any

#### Actual behavior:
TooltipHost uses `theme.palette.neutral` for the root background color, despite accepting a theme as a prop, so the root's background color never changes.

#### Expected behavior:
TooltipHost should use a `theme.palette.neutral*` or `theme.semanticColors.*` color instead of `theme.palette.white` for the root background color. Otherwise, the content's colors are updated from the theme (`color: palette.neutralPrimary`), but the background color isn't, making the component inaccessible and styled incorrectly. 

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High for those using TooltipHost

**Comment by khmakoto** [comment]
Hi @isabelacmor, thanks for filing this issue! I can understand what you're saying here.

@phkuo @betrue-final-final I wonder, what should we do here, it definitely feels like the `Tooltip` background color should change with the theme.

**Comment by phkuo** [comment]
It should use bodyBackground or menuBackground, up to design whether it should follow default styles or menu styles.

**Comment by khmakoto** [comment]
I spoke with design and the decision was that we should use `menuBackground` for this. I'll have a PR for this shortly.
