### ISSUE TITLE
DetailsList component not showing boolean values in rows.

### ISSUE THREAD

**Issue by linkup89** [OfficeDev/office-ui-fabric-react#10671]
### Environment Information

- **Package version(s)**: 6.175.0
- **Browser and OS versions**: Chrome/Windows 10

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/linkup/pen/xxKoXeR

#### Actual behavior:

When one of the value types for DetailList is boolean the data is not shown in the table.

#### Expected behavior:

It should show, true/false accordingly

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) Dynamics 365 for Customer Insights.

**Comment by khmakoto** [comment]
Hi @linkup89, thanks for filing this issue! I'll take a look as soon as I can!

**Comment by linkup89** [comment]
That is a quick fix that i found for this issue. Hope it helps.
