### ISSUE TITLE
Dropdown component renderTitle not called when menu option is enable=true, selected=true

### ISSUE THREAD

**Issue by ashbadami** [OfficeDev/office-ui-fabric-react#10684]
### Environment Information

- **Package version(s)**: office-ui-fabric-react": "7.28.1",
- **Browser and OS versions**: Chrome 77.0.3865.90 , Windows 10

### Please provide a reproduction of the bug in a codepen:
Issue: dropdown doesn't call renderTitle() but only calls renderPlaceholder() 
<DropDown  options set to a state variable. Initially dropdown option is set with
{ key.....   , disable: true, selected=false} -> calls renderPlaceholder()
Then updated with 
{ key... , disable: false, selected=true } -> calls renderPlaceholder() instead of calling renderTitle().

As a result, the renderTitle is only called when explicitly toggle the dropdown option in UI.

#### Actual behavior:
renderTitle doesn't get called when option has array items with selected=true. As a result we cannot show custom title. It always calls renderPlaceholder().

#### Expected behavior:
renderTile is called when atleast one of the option items have selected=true and disabled=false.

### Priorities and help requested:

Are you willing to submit a PR to fix? ( No)

Requested priority: (Blocking, High)

Products/sites affected: (cannot disclose)

**Comment by khmakoto** [comment]
Hi @ashbadami, thanks for filing this issue! I'll take a look into it as soon as I can.
