### ISSUE TITLE
Can't set imageProps on an icon using @uifabric/file-type-icons

### ISSUE THREAD

**Issue by Toonshorty** [OfficeDev/office-ui-fabric-react#10686]
### Environment Information

- **Package version(s)**: 7.41.0 (office-ui-fabric-react); 7.1.1 (@uifabric/file-type-icons)

#### Actual behavior:

By default, the image is rendering using the inline display style. In my scenario, I am using the Icon as a column in a DetailsList component. The inline style is adding some white-space which means the image doesn't line up to the row correctly. This can be resolved by applying the `display: block;` property to the image. I have applied this using the imageProps property and the following object:

```
const imageProps: IImageProps = {
    styles: {
        image: { display: 'block' }
    }
};

<Icon {...getFileTypeIconProps({ extension: 'pdf' }) imageProps={imageProps} />
```

However, because imageProps property is set - the Icon component will render as an image which will then ignore the icon name of 'pdf16_svg' and won't render the file type icon.

#### Expected behavior:

When using file type icons, the icon should render irrespective of whether or not imageProps is set.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

**Comment by khmakoto** [comment]
Hi @Toonshorty, thanks for filing this issue! I'll take a look as soon as I can.

**Comment by khmakoto** [comment]
Hi @Toonshorty, if you pass the `styles` prop and specify `display: block` to the `root`, this should get passed down to the `img` tag below. You can check this out in [this codesandbox](https://codesandbox.io/s/icon-svg-with-imageprops-issue-10686-iwwo6). 

Let me know if this fixes your issue or if there's anything else I can do for you!
