### ISSUE TITLE
There's no way to set a tooltip on the overflow button on CommandBar

### ISSUE THREAD

**Issue by brandonthomas** [OfficeDev/office-ui-fabric-react#10692]
### Environment Information

- **Package version(s)**: any
- **Browser and OS versions**: any

### Describe the issue:
There is no way to set tool tip props on the overflow button within CommandBar (or OverflowSet). Ideally OverflowSet would allow for this, and then CommandBar would expose OverflowSet props to enable down level consumers to solve any future problems that OverflowSet fixes.

### Please provide a reproduction of the issue in a codepen:

User a command bar and reduce the size so items are pushed into the overflow menu. No tooltip shows up or is able to be set by consuming apps.

#### Actual behavior:
No tooltip on overflow menu button

#### Expected behavior:
Tooltip can be set on overflow menu button

### Documentation describing expected behavior
This is needed as only a graphical element is there to describe the function of the overflow button. Trying to find the specific WCAG requirement.

**Comment by khmakoto** [comment]
Hi @brandonthomas, thanks for filing this issue! There is already an issue tracking this in #9873 so I'll file this as a duplicate.
