### ISSUE TITLE
A11y_CustomerServiceInsights_AddWorkspace_FindCaseRecords_keyboard: On focus the check boxes get selected by default on keyboard navigation.

### ISSUE THREAD

**Issue by MayuriNaik** [OfficeDev/office-ui-fabric-react#10705]
**Environment Details:** 
Windows Version: Windows10
Browser Versions: 
Microsoft Edge 44.18963.1000.0
Chrome Version 76.0.3809.100
Screen Reader Version: NVDA 2019.2
MAS Violated: MAS 3.2.2

**Repro Steps**:
1. Home page should open for Customer Service Insights.
2. Navigate to Global Navigation Bar at the top of the screen and select "Workspaces Panel".
3. Hit on "+Workspace" link. Popup with "Connect Your Data" screen should appear.
4. Select any data source from the list. "Get customer service data" screen should appear.
5. Select the environment where your records are stored. After processing, "Map Your Data" screen appears.
6. Hit "Get Started" button. "Find Case Records" screen appears.
7. Verify that all the elements of "Add Workspace-Find Case Records" are accessible and MAS Compliant.

**Actual:**
When keyboard users navigate through the check-boxes and select any one of them and then try to navigate to the rest of the checkbox the other checkbox gets selected and the initial one get un-selected which is in correct.

**Expected:**
The check-boxes should be selected on interacting with it and not on navigation.

**User Impact:**
If the controls get selected on keyboard navigation then the keyboard users will get confused and wrong information will be conveyed.

**Comment by dzearing** [comment]
@MayuriNaik there are 2 issues here:

1. You're logging private product specific urls on a public github repo. Please don't do this.

2. You're logging application bugs that need to be investigated by the app developers who wrote the workflow. They need to fix these things, not the component library.

Could you please work with the app developers to have them investigate their accessibility concerns?

Thank you!
