### ISSUE TITLE
Tag picker doesn't show suggestions callout after item is selected

### ISSUE THREAD

**Issue by rutuja** [OfficeDev/office-ui-fabric-react#10719]
### Environment Information

- **Package version(s)**: "6.202.2"
- **Browser and OS versions**: All browsers

### Describe the issue:

On empty input, picker shows suggestion callout but after item is selected from suggestions, it doesn't render suggestion callout again. 

#### Actual behavior:
On empty input, picker shows suggestion callout but after item is selected from suggestions, it doesn't render suggestion callout again. 

#### Expected behavior:

Suggestions callout always shown when input string is empty

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Modern Project O365

**Comment by khmakoto** [comment]
Hi @rutuja, thanks for filing this issue! Can you provide a codepen example where this happens? I've tried reproing the issue but I can't seem able to do it.
