### ISSUE TITLE
Group of button component

### ISSUE THREAD

**Issue by mahendrakulkarni177** [OfficeDev/office-ui-fabric-react#10727]
#### Describe the feature that you would like added
group of button so user can toggle between then, like we have for option

#### Additional context/screenshots
![image](https://user-images.githubusercontent.com/16331616/66254285-e9c84080-e791-11e9-860f-9bb9ae7e0131.png)

**Comment by ecraig12345** [comment]
There's already a request for this component open under #10275. It's probably not something we plan to build in the near future, but you can watch that issue for any updates.

In the meantime, you can do something similar using a ChoiceGroup with custom styling/rendering. Here's a starting point (thanks @micahgodbolt!). 
https://codepen.io/ecraig12345/pen/BaaywqL?editors=0011
