### ISSUE TITLE
componentRef of IChoiceGroupOptionProps is not accessible in options of ChoiceGroup

### ISSUE THREAD

**Issue by rulyu** [OfficeDev/office-ui-fabric-react#10724]
### Environment Information

- **Package version(s)**: 7.43.2
- **Browser and OS versions**: (fill this out if relevant)

### Describe the issue:

When using the `ChoiceGroup` control, the componentRef prop is not accessible in `options` because `options` is of type `IChoiceGroupOption[]` instead of `IChoiceGroupOptionProps[]`. 

#### Expected behavior:

`componentRef` should be exposed in the `options` list so that individual options can be accessed through `componentref`
### If applicable, please provide a codepen repro:
Examples on the official sites are pretty easy to repro with.
https://developer.microsoft.com/en-us/fabric#/controls/web/choicegroup#IChoiceGroupOptionProps

```ts
<ChoiceGroup
    defaultSelectedKey={chosenEntityName}
    className='entityDetailsList'
    options={entities.map(x => ({ key: x.key, text: x.value}))}
    onChange={this.onChange}
/>
```

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment]
I'm curious, what are you trying to do where you need access to an instance of the `ChoiceGroupOption` class (which is what `componentRef` on an individual option would give you)? We don't typically make `componentRef`s available for individual items within a larger control.
