### ISSUE TITLE
Component positioning going off screen

### ISSUE THREAD

**Issue by andrewhwng** [OfficeDev/office-ui-fabric-react#10721]
### Environment Information

- **Package version(s)**: 7.43.1

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/slimemold/pen/bGGGdzY

Examples of repro's in OWA:
![image](https://user-images.githubusercontent.com/47833548/66241693-7270af00-e6b4-11e9-9721-af065d6dd93e.png)
![image](https://user-images.githubusercontent.com/47833548/66241743-97652200-e6b4-11e9-868e-337cfbee4dd4.png)

#### Actual behavior:

Components are rendering off the page when near the edges.

#### Expected behavior:

Component positioning should render the whole component on the page

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: OWA

**Comment by joschect** [comment]
This is a bug caused by the recent change #10562 I am working on a fix.

**Comment by dzearing** [comment]
@joschect can we back out your fix until this is resolved? I hit this this week and was wondering what went wrong.
