### ISSUE TITLE
[DetailsList]: Making DetailsList header disabled creates jitteriness in resizing columns

### ISSUE THREAD

**Issue by satishc2437** [OfficeDev/office-ui-fabric-react#1073]
Hi,
As part of accessibility change we wanted to avoid getting focus to the column headers in DetailsList control. We used the "columnActionsMode: DetailsListProps.ColumnActionsMode.disabled" prop of IColumn to achieve this. But, after this change we are seeing jitteriness while trying to resize columns.

The resize action is not smooth as compared to enabled headers.

Requesting you to please take a look.

Thanks,
Satish

**Comment by joschect** [comment]
@satishc2437 I definitely see the issue that you're talking about. Here is a codepen where it repros. http://codepen.io/slimemold/pen/ZezPRr .

**Comment by kristoferbrown** [comment]
@satishc2437, @joschect, this looks like it may have been fixed to me. Can either of you confirm that and if so close this bug?

**Comment by joschect** [comment]
This looks like it's fixed from what I remember. I believe we can close the bug. @satishc2437 if this is still an issue please let us know!
