### ISSUE TITLE
TooltipOverflowMode doesn't seem to have any effect

### ISSUE THREAD

**Issue by isabelacmor** [OfficeDev/office-ui-fabric-react#10732]
### Environment Information

- **Package version(s)**: ^7.29.0
- **Browser and OS versions**: any

#### Actual behavior:
`TooltipOverflowMode.Parent` and `TooltipOverflowMode.Self` don't seem to do anything.
[This is CodePen example](https://codepen.io/isabelacmor/pen/QWWwOqx?editors=0010), the the `p` with ellipsis should show the tooltip on hover and the other `p` should not show a tooltip. As you can see, regardless of what `TooltipOverflowMode` is used, the `p` with ellipsis never gets a tooltip on hover.

#### Expected behavior:
`TooltipOverflowMode.Parent` and `TooltipOverflowMode.Self` should do what the documentation says.

```
export declare enum TooltipOverflowMode {
    /** Only show tooltip if parent DOM element is overflowing */
    Parent = 0,
    /** Only show tooltip if tooltip host's content is overflowing */
    Self = 1
}
```

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: Any using Tooltip

**Comment by ecraig12345** [comment]
Sorry for the delay here--I started investigating this but didn't quite reach a conclusion before being sidetracked by other issues. I'll try and get back to it soon.

**Comment by ecraig12345** [comment]
Finally got to look into this. It's actually behaving as expected, but the expectations are not well-documented.

If the styling causing the overflow is limited to **inside the children**, the TooltipHost won't detect that overflow. It only checks for overflow on the TooltipHost element itself (with `Self` mode) or on the TooltipHost's parent element (with `Parent` mode).

Here's a codepen demonstrating the expected parent and self behavior. I'm going to add this example to our doc site, as well as clarifying the documentation for the `overflowMode` prop and the enums. https://codepen.io/ecraig12345/pen/KKKgepQ

Does that make sense? And given that explanation, will one of the overflow modes work for your real scenario?

**Comment by isabelacmor** [comment]
This makes sense, thank you! The updated docs would be super helpful - it wasn't apparent to me that the overflow prop worked only on the context prop, not on any children nested under the component.
