### ISSUE TITLE
Announced component's aria-live attribute should default to "polite"

### ISSUE THREAD

**Issue by martellaj** [OfficeDev/office-ui-fabric-react#10742]
**Reference:** https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions

When an aria-live region is set to "assertive", any message added to it will interrupt the user's context and read whatever is set. This is typically reserved for urgent messages, not something like "email deleted" as described in the Announced documentation.

Instead of defaulting to a very heavy-handed value, we should instead default to "polite" and allow consumers to override the value using props if they require their message to interrupt user flow (as  described in #843).

**Comment by martellaj** [comment]
@philipzloh FYI

**Comment by ecraig12345** [comment]
@natalieethell Since you worked on Announced, can you provide any background on why it uses `assertive` not `polite`?

**Comment by ecraig12345** [comment]
Also @martellaj could you provide more details on the scenario where this is causing problems for you?

**Comment by philipzloh** [comment]
> causing problems

It's wrong by spec, isn't it?

**Comment by ecraig12345** [comment]
No, I'm pretty sure Announced is intended for urgent announcements. Since Natalie wrote it, she'd know more background of the design. The component was written recently and I'm sure this was something they considered carefully when writing it.

**Comment by ecraig12345** [comment]
It's also pretty easy to customize the `aria-live` setting if you'd like it to be `polite` instead of `assertive`:
```tsx
<Announced aria-live="polite">message here</Announced>
```

**Comment by natalieethell** [comment]
Hey! Just discussed this with @ecraig12345 @betrue-final-final and @cschlechty offline, and we agree -  setting the default to "polite" makes sense. I'll open a PR with that change.

**Comment by martellaj** [comment]
Thanks for the quick fix!
