### ISSUE TITLE
Tag Picker items overflow input field

### ISSUE THREAD

**Issue by HarryGifford** [OfficeDev/office-ui-fabric-react#10744]
Tag pickers with long names overflow the input field.

### Environment Information

- **Package version(s)**: office-ui-fabric-react 7.45.1
- **Browser and OS versions**:
Version 77.0.3865.90 (Official Build) (64-bit)

### Please provide a reproduction of the bug in a codepen:

Codepen to repro the issue: https://codepen.io/hegi/pen/bGGddYE

#### Actual behavior:

What it looks like:
![image](https://user-images.githubusercontent.com/21968002/66428148-5b8acf00-e9ca-11e9-9b3e-9d262c907b6d.png)

#### Expected behavior:

Automatically prevent overflow of long names.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Dynamics 365 Field Service

### Possibly related issues
#1395

**Comment by ecraig12345** [comment]
Thanks for reporting this! @joschect What do you think the proper fix is here?

**Comment by ecraig12345** [comment]
Opened PR #10917 with the fix.
