### ISSUE TITLE
Dropdown: Using onRenderContainer only closes the container when clicking the dropdown parent.

### ISSUE THREAD

**Issue by dliu120** [OfficeDev/office-ui-fabric-react#10753]
### Environment Information

- **Package version(s)**: 7.x
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/dliu120/pen/wvvavJe?editors=1010

#### Actual behavior:

There appears to be no way to close the custom container without clicking on the dropdown again.

#### Expected behavior:

There should be some API to close the custom rendered container.

### Priorities and help requested:

No

Requested priority: High

Products/sites affected: https://flow.microsoft.com

We are building a new custom dropdown component and would like to re-use dropdown without having to build our own.

**Comment by khmakoto** [comment]
Hi @dliu120, you have to pass the `this._onDismiss` method to the `Callout` in `onRenderContainer`. I've modified your codepen to have this working and placed it [here](https://codepen.io/khmakoto/pen/rNNeWoM?editors=0010). Let me know if there is anything else I can do to help!

**Comment by dliu120** [comment]
Thanks! This unblocks us, but this API is also not publicly exposed or documented. Could you perhaps expose this in the interface and document it? Otherwise anyone using the custom renderContainer would have the same issue.

**Comment by khmakoto** [comment]
@dliu120 I think that's a fair ask. @joschect if you are ok with this change I can expose the method in the interface. What do you think?

**Comment by ecraig12345** [comment]
Not Jon :) but FWIW I agree we should expose `onDismiss` publicly somehow--either add it on the `IDropdown` interface (probably also `IComboBox`) or pass it as an additional parameter to `onRenderContainer`.

**Comment by joschect** [comment]
@khmakoto and @ecraig12345 ITT the correct fix is on line (305)[https://github.com/OfficeDev/office-ui-fabric-react/blob/17e5b97a8246761a10717072096888a192811109/packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx#L305] and what it should become is

` isOpen && onRenderContainer({...props, onDismiss: this._onDismiss})`

onRenderContainer already gets onDismiss as a prop, it just gets the wrong onDismiss.

**Comment by khmakoto** [comment]
Thanks @joschect! I'll have a PR shortly and I'll make a similar change in `ComboBox` as we discussed offline.
