### ISSUE TITLE
Panel A11y Pass: By default 'Option B' radio button is selected after activating the 'Open Panel' button

### ISSUE THREAD

**Issue by 999-Dev** [OfficeDev/office-ui-fabric-react#10762]
Track the Bug Details on [SharePoint](https://microsoft-my.sharepoint.com/:x:/r/personal/v-amaver_microsoft_com/_layouts/15/Doc.aspx?sourcedoc=%7B5afd015d-fc38-4e4b-ae9b-a0ad778c0ea7%7D&action=default&uid=%7B5AFD015D-FC38-4E4B-AE9B-A0AD778C0EA7%7D&ListItemId=1850&ListId=%7B395E1ECB-5002-440E-81C5-6A090E98077C%7D&odsp=1&env=prodbubble&cid=5bae63ae-f014-462e-a679-e706631598a6)

Bug19: [Functional: Panel Control]: By default 'Option B' radio button is selected after activating the 'Open Panel' button. 

**Test Environment:** 
OS: Version: RS5_Prerelease(1903 OS Build 18999.1) 
URL: https://developer.microsoft.com/en-us/fabric#/controls/web/panel
Edge Browser Version: 
Microsoft Edge: 44.18999.1.0
Microsoft EdgeHTML: 18.18999
Chrome Browser Version:
Chrome Version: 76.0.3809.132
 
### Repro Steps
1. Open https://developer.microsoft.com/en-us/fabric#/controls/web/panel in Edge.      
2. Navigate to 'Open Panel' under usages (Panel - Small Panel, Anchored Right, Fixed Width) by using Tab key and activate it.      
3. Panel - Small Panel, Anchored Right, Fixed Width pane will be appeared.      
4. Select Option A by using down arrow key.      
5. Navigate to Save button and activate it.      
6. Now again activate the ‘Open Panel’ button and verify the issue.

**Actual result**: Always ‘Option B’ radio button got selected by default even user save ‘Option A’ radio button.

**Expected result**: If user saves Option A radio button, then after activating the ‘Open Panel’ button, ‘Option A’ radio button should be selected.

**Comment by ecraig12345** [comment]
This is a very minor issue which is tangential to the point of the example (the example is about displaying a panel, not persisting selected choices within the panel). So I'm closing this as "won't fix."
