### ISSUE TITLE
Details List need to accept some rowCount props that can update for async data fetch instead of mandatory items props

### ISSUE THREAD

**Issue by shachau** [OfficeDev/office-ui-fabric-react#10766]
#### Describe the feature that you would like added

I am developing a feature where I will get the data async and the data is more than a million line of string. Also, i will be fetching only required lines of data on scroll instead of caching million lines of string in javascript.

Problem:
Currently the DetailsList component accept a mandatory prop named items. I have to atleast create an array with some value like ("something"/true) of the size equal to number of lines downloaded so that this component knows how many rows it has to render. Secondly, I use prop               onRenderRow where i pass a function to return Row component.

I want a prop like rowCount that can be used instead of items so that i don't have to create an unnecasry array of million size.

#### What component or utility would this be added to

DetailsList component

**Comment by ecraig12345** [comment]
@KevinTCoughlin Since you're more familiar with DetailsList, does this sound like something we reasonably could/should support? Or is there some other recommended way to handle this currently? I know internally we have scenarios where we fetch only a subset of items out of a large list of items, so there must be some way of handling it.

**Comment by KevinTCoughlin** [comment]
This Codepen uses `DetailsList` with async data fetching on scroll: https://codepen.io/dzearing/pen/EgqMZq. It utilizes `onRenderMissingItem` prop to determine when to fetch additional items. It then updates the underlying `items` array providing a new object reference causing the List to re-render.

Will an approach similar to that not support the above scenario?
