### ISSUE TITLE
SpinButton doesn't pass through other HTML attributes such as `data-testid`.

### ISSUE THREAD

**Issue by mattmazzola** [OfficeDev/office-ui-fabric-react#10768]
### Environment Information

- **Package version(s)**: 7.15.0
- **Browser and OS versions**: Chrome Version 77.0.3865.90 (Official Build) (64-bit)

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/s/spin-button-no-data-testid-attribute-31tzw

#### Actual behavior:

Other components forward the attribute on to their surrounding DOM element to make it reliably accessible by e2e tests

#### Expected behavior:

The attribute is not forwarded.

![image](https://user-images.githubusercontent.com/2856501/66523289-6a45b480-eaa4-11e9-8c6b-60a831d5caf0.png)

![image](https://user-images.githubusercontent.com/2856501/66523269-5d28c580-eaa4-11e9-99ef-d712a9bae724.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, **No**)

Requested priority: (Blocking, High, Normal, **Low**)

Products/sites affected: (if applicable)

Can likely just wrap it another `div` to work around, but it is inconsisten with other components.

Seem to be other issues with `SpinButton` related to label spacing, guessing this component is not used as much as others and doesn't get as much attention. 

On larger note, I making components testable would be helpful. For example, it took some digging but I noticed some controls like the `ChoiceGroup` have built in ways to pass testid's to the choices which was helpful. This ensures our tests will not be coupled to the DOM structure of a particular OFUI version only the test ids.

**Comment by dzearing** [comment]
@jspurlin can you help here for spinbutton?

**Comment by ecraig12345** [comment]
Most of our other components already pass through native HTML attributes (and data- attributes), so I agree it would make sense for SpinButton to do the same.
