### ISSUE TITLE
Ctrl-Alt-Space shortcut does not open contextual menu in a draggable Modal when focus is on a ComboBox

### ISSUE THREAD

**Issue by regisgaschy** [OfficeDev/office-ui-fabric-react#10775]
### Environment Information

- **Package version(s)**: office-ui-fabric-react v7.47.0
- **Browser and OS versions**: Chrome Version 77.0.3865.90 (Official Build) (64-bit) / Windows 7 Pro SP1

### Please provide a reproduction of the bug in a codepen:

See https://codepen.io/regisgaschy/pen/QWWjwQY where the bug can be reproduced.

#### Actual behavior:

When hitting Ctrl-Alt-Space while focus is on a ComboBox, in a draggable Modal, no menu appears.
Thus, the contextual menu is not accessible in that context, the keyboard can not be used to move the Modal, for example.

#### Expected behavior:

Hitting Ctrl-Alt-Space in a draggable Modal should show the contextual menu which allows moving or closing the Modal using the keyboard.
On https://codepen.io/regisgaschy/pen/QWWjwQY, when moving the focus to a button, hitting Ctrl-Alt-Space opens the contextual menu as expected.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment]
I can repro this too. It looks like the ComboBox is interpreting the control key event as a standard keystroke (not a modifier key) and stopping propagation when it shouldn't.

**Comment by xugao** [comment]
better codepen demoing the issue thanks for @ecraig12345 : https://codepen.io/ecraig12345/pen/NWWrxKR?editors=0010
