### ISSUE TITLE
CommandBar item with buttonStyles applied loses some of the styling

### ISSUE THREAD

**Issue by clmreimann** [OfficeDev/office-ui-fabric-react#10774]
### Environment Information

- **Package version(s)**: office-ui-fabric-react 7.47.0
- **Browser and OS versions**: Chrome 77.0.3865.90, Windows 10 Pro

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/creimann/pen/VwwLgRR

#### Actual behavior:

When the background color of a CommandBar item with iconOnly set to true is changed then the icon is aligned top and not vertically centered.

#### Expected behavior:

The icon should be vertically centered when iconOnly is set to true.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: -

**Comment by ecraig12345** [comment]
I'm not quite seeing this issue, sorry. Would you mind sharing a screenshot to help show what you mean? And I'm guessing it's only off by a fairly small amount? (still worth fixing but makes it harder to see)

**Comment by clmreimann** [comment]
Here is a screenshot:
![image](https://user-images.githubusercontent.com/16774153/66625265-d551d100-ebf3-11e9-9cc4-33aec00b255c.png)
You should also see it in the Codepen example.
I just changed the background color of the iconOnly items with the buttonStyles property.
```
const theme = getTheme();
const buttonStyles = {
  icon: { color: theme.palette.white },
  iconHovered: { color: theme.palette.white },
  root: {
    background: theme.palette.neutralPrimaryAlt,
    color: theme.palette.white
  },
  rootHovered: {
    background: theme.palette.neutralSecondaryAlt,
    color: theme.palette.white
  }
}

class CommandBarBasicExample extends React.Component<{}, {}> {
  public render(): JSX.Element {
    return (
      <div>
        <CommandBar
          items={this.getItems()}
          overflowItems={this.getOverlflowItems()}
          overflowButtonProps={{ ariaLabel: 'More commands' }}
          farItems={this.getFarItems()}
          ariaLabel={'Use left and right arrow keys to navigate between commands'}
        />
      </div>
    );
  }

  private getFarItems = () => {
    return [
     ...
      {
        key: 'tile',
        name: 'Grid view',
        ariaLabel: 'Grid view',
        iconProps: {
          iconName: 'Tiles'
        },
        buttonStyles: buttonStyles,
        iconOnly: true,
        onClick: () => console.log('Tiles')
      },
      {
        key: 'info',
        name: 'Info',
        ariaLabel: 'Info',
        iconProps: {
          iconName: 'Info'
        },
        buttonStyles: buttonStyles,
        iconOnly: true,
        onClick: () => console.log('Info')
      }
    ];
  };
}
```

**Comment by khmakoto** [comment]
Hi @clmreimann, I can reproduce your issue in the codepen you provided (thanks for that!). The main issue here is that in using `buttonStyles` you are overriding a style that sets the `height` of the `CommandBarItems` to `100%`. If you set the `height` again as I did in [this codepen](https://codepen.io/khmakoto/pen/PooNjvP?editors=0010) you'll see that the items are vertically centered again.

However, I agree that this is a bug since we should style this in a way that is more resilient to the styling people apply unless you are specifically overriding the `height` of the component. I'll have a PR shortly to fix this situation. Thanks!

**Comment by clmreimann** [comment]
Thanks for the clarification and the PR @khmakoto . This solved my issue.

**Comment by khmakoto** [comment]
@clmreimann no problem! Glad it helped!
