### ISSUE TITLE
className is not applied on DetailsHeader

### ISSUE THREAD

**Issue by woodreamz** [OfficeDev/office-ui-fabric-react#10783]
### Environment Information

- **Package version(s)**: 7.48.0
- **Browser and OS versions**: Chrome and macOS

### Please provide a reproduction of the bug in a codepen:

https://codesandbox.io/embed/office-ui-fabric-react-classname-issue-w3h5s

#### Actual behavior:

When styling the DetailsHeader with styled-component (or other lib using className), the className is not correctly applied on the DetailsHeader component. So the style is not applied.

#### Expected behavior:

className should be applied on the DetailsHeader.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes.

Requested priority: Normal

Products/sites affected: Not applicable

**Comment by woodreamz** [comment]
PR submitted!

**Comment by ecraig12345** [comment]
I agree this seems like a bug--thanks for submitting a PR!

**Comment by dzearing** [comment]
Thanks!
