### ISSUE TITLE
[DetailsList] Export functionality for DetailsList

### ISSUE THREAD

**Issue by shiliangdn** [OfficeDev/office-ui-fabric-react#10790]
#### Describe the feature that you would like added

Export functionality

#### What component or utility would this be added to

DetailsList

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

Just like the export function in the Angular UI-Grid

**Comment by ecraig12345** [comment]
While this would be nice to have, it's a pretty large feature and not something we're likely to get to any time soon.

**Comment by ecraig12345** [comment]
Just to clarify, I assume you mean export to CSV or something like that?

**Comment by dzearing** [comment]
Thank you for the suggestion!

I believe while interesting, is out of scope for the react component library.

It's entirely possible to write a javascript map function on your items to build a CSV file.
