### ISSUE TITLE
Screen reader is reading table details for first column twice, present at the top on the basic detail list page

### ISSUE THREAD

**Issue by HarkeshS** [OfficeDev/office-ui-fabric-react#10814]
### Environment Information

Package version(s): latest
Browser and OS versions: 
Browser: Edge
OS: Windows 10

### Describe the issue:

Screen reader is reading table details for first column twice, present at the top on the basic detail list page
Checked at-
https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/basic

#### Actual behavior:

Screen reader is reading table details for first column twice like number of rows and column in table, present at the top on the basic detail list page
This is issue is also Repro at--https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/basic 
#### Expected behavior:

Screen reader should read table details for first column only time, present at the top on the basic detail list page

**Comment by marygans** [comment]
Hi @HarkeshS thank you for submitting this issue! What screen reader are you experiencing this problem with? I am testing using Narrator + Edge, and hear for example,"Column Header, Column 2 of 3" for the Name column.

**Comment by HarkeshS** [comment]
I have also tested using Narrator + Edge. It is reading two times of table details for first column and first time. for rest column it is ok.

**Comment by cschlechty** [comment]
@HarkeshS please provide details on how you're navigating the table. Are you using table commands? Reading with scan mode? Something else? I'm not able to reproduce the issue.
