### ISSUE TITLE
SplitButton role should not be hardcoded

### ISSUE THREAD

**Issue by pagaur** [OfficeDev/office-ui-fabric-react#10817]
#### Describe the feature that you would like added

As of now the SplitButton has role attribute hard-coded to 'button', which is fine is almost all cases. But if someone wants to override it, similar to other controls and non-split flavor of baseButton one can override it.

We are putting SplitButton as part of suggestions list and want the narrator to announce its position in list, which happens well with role='option'.

#### What component or utility would this be added to

SplitButton

#### Have you discussed this feature with our team, and if so, who

No.

**Comment by marygans** [comment]
Hi @pagaur thank you for submitting this issue and a PR! 👍
