### ISSUE TITLE
On Click for button is called even when it is disabled

### ISSUE THREAD

**Issue by ankitk94** [OfficeDev/office-ui-fabric-react#1082]
### Bug Report

Currently using 1.7.2

#### Describe the issue:

On click for command button is called even when the button is disabled. Although the cursor is changed, but looks like pointer-events are not set to none.

#### Actual behavior:

On click is called even when the button is disabled

#### Expected behavior:

The on click should not have been called when the button is disabled

### If applicable, please provide a codepen repro:

http://codepen.io/ankhokha/pen/RpbVoJ

**Comment by mdahamiwal** [comment]
This seems native to html http://stackoverflow.com/questions/28213070/disabled-button-still-fires-using-click. you may be able to workaround it if you really want to avoid.

**Comment by ankitk94** [comment]
@mikewheaton Hi, have you looked into the issue? Is this issue due to some regression happened in 1.7.2?

**Comment by gitjain** [comment]
This has been fixed in master. See attached pen. http://codepen.io/reenajain/pen/BWrwOb?editors=0110
