### ISSUE TITLE
[Accessibility][Usable]: Focus is not landing on the first selection of the edit field under Tag Picker variant rather going to remove button. (Bug 5)

### ISSUE THREAD

**Issue by jdhuntington** [OfficeDev/office-ui-fabric-react#10824]
Breakout of issue #8655

**Comment by joschect** [comment]
I'm not sure that this is an issue, this works correctly if you select the first item. It seems that this is the way that default focus works when tabbing. If anything the "x" should not be a focusable tab stop.

**Comment by xugao** [comment]
i agree with @joschect here. I don't think this is a bug. whatever was on focus before leaving the picker, once the focus comes back to the picker, the focus will land on it
