### ISSUE TITLE
[Accessibility][Screen reader]: User is not able to access "Share w/split button " in scan mode. (Bug 11)

### ISSUE THREAD

**Issue by jdhuntington** [OfficeDev/office-ui-fabric-react#10837]
Tracking all of the issues brought up with the 08/24 accessibility pass on Contextual Menu  control
Details on individual bugs can be found on [SharePoint](https://microsoft-my.sharepoint.com/:x:/r/personal/v-amaver_microsoft_com/_layouts/15/Doc.aspx?sourcedoc=%7Bcef6201c-bd85-44b6-a2d3-3784248461e0%7D&action=default&uid=%7BCEF6201C-BD85-44B6-A2D3-3784248461E0%7D&ListItemId=1259&ListId=%7B395E1ECB-5002-440E-81C5-6A090E98077C%7D&odsp=1&env=prodbubble)

Breakout of issue #6360

**Comment by joschect** [comment]
Contextualmenu split button should probably open with alt arrow key in the same way that split button does. This works fine when not in scan mode.

**Comment by xugao** [comment]
![image](https://user-images.githubusercontent.com/1207059/70482653-e8b9d500-1a9a-11ea-888a-751fcf44f879.png)

Looks like this is caused by `aria-hidden` is set to `true`
