### ISSUE TITLE
Tooltip for disabled DropdownOption

### ISSUE THREAD

**Issue by phyllers** [OfficeDev/office-ui-fabric-react#10846]
#### Describe the feature that you would like added

I noticed that there is no tooltip support for DropdownOptions. We can use the title to show in the native browser rendering, but the disabled options don't show the title tooltips. I'd like this to be added.

#### What component or utility would this be added to

DropdownOption

**Comment by marygans** [comment]
HI @phyllers thank you for submitting this issue! The tooltip support for dropdown described above is using default browser title attribute. Are you requesting that the same default browser tooltip be applied to the disabled dropdown options? Or to have a [tooltip](https://developer.microsoft.com/en-us/fabric#/controls/web/tooltip) option for disabled dropdown options?

**Comment by phyllers** [comment]
I was suggesting that the tooltip be applied to disabled dropdown options, but I now realize why that might be a bad idea for accessibility. I will happily take a tooltip option for disabled dropdown options. If that's already possible, is there an example you can point me to?

**Comment by marygans** [comment]
Hi @phyllers this is a browser issue due to the browser deciding to not show the native tooltip on disabled controls. Unfortunately, there isn't much we can do about changing that, but we do include the `title` attribute on the disabled dropdown.
