### ISSUE TITLE
Documentation: Code Examples in Control-Documentation no longer scrollable using mouse wheel in Firefox

### ISSUE THREAD

**Issue by alex3683** [OfficeDev/office-ui-fabric-react#10865]
### Environment Information

- **Browser and OS versions**: Firefox 69.0.3 (64-Bit) on Windows 10

### Please provide a reproduction of the bug in a codepen:

- Open for example https://developer.microsoft.com/en-us/fabric#/controls/web/pickers in Firefox.
- Under "Usage" -> "Tag Picker" click on "Show Code"
- Try scrolling in the code div using the mouse wheel

#### Actual behavior:

The code does not scroll in Firefox. In Chrome for example, scrolling works.

#### Expected behavior:

The code is scrollable by mouse wheel in every major browser.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) Every Code Example

**Comment by marygans** [comment]
Hi @alex3683 thank you for submitting this issue! I was also able to confirm this issue in Firefox. 

It looks like this was an existing issue with the monaco editor as there was a recently closed issue [here](url). We will need to bump our [monaco version](https://github.com/OfficeDev/office-ui-fabric-react/blob/30384d21f414d50394e8ce1657c9bbc986f93c4c/yarn.lock#L10217)  `monaco-editor@0.17.1` to` 0.18.1 `to get the [ fix](https://yarnpkg.com/en/package/monaco-editor#changelog) which seems to [address the issue adequately] for folks (https://github.com/Microsoft/monaco-editor/issues/1353#issuecomment-534103112).

FYI @ecraig12345 and @kenotron

**Comment by ecraig12345** [comment]
At least last I looked at the latest monaco-editor version, bumping it introduced some other issue which would be impossible to work around (unfortunately don't remember what that was...). I'll have to check whether that's still the case. Either way I can deal with this one.

**Comment by ecraig12345** [comment]
Looked into this and probably the issue I ran into before was [this one](https://github.com/microsoft/monaco-editor/issues/1623) (though it's misleadingly named). I submitted a fix (https://github.com/microsoft/monaco-typescript/pull/49) and also found a workaround which will let us upgrade our Monaco version in the meantime.
