### ISSUE TITLE
Calendar is not closing after selected date with keyBoard 

### ISSUE THREAD

**Issue by MSYuanMei** [OfficeDev/office-ui-fabric-react#10864]
### Environment Information

- **Package version(s)**: v7.50.0
- **Browser and OS versions**: win32/MacOS

### Describe the issue:

I can replicate this issue on https://developer.microsoft.com/en-us/fabric#/controls/web/calendar
page for the **Calendar launched from a button** example. 

When I try to select a date with keyboard(enter key), it will not close the calendar.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/pen/?&editable=true
![test01](https://user-images.githubusercontent.com/42685233/66885223-79d36a80-ef88-11e9-8d80-3504d07fce80.gif)

#### Actual behavior:

It flashes and still open 

#### Expected behavior:
Should close the calendar

### Documentation describing expected behavior
Should close the calendar callout after selecting a date

**Comment by marygans** [comment]
Hi @MSYuanMei thank you for submitting this issue. I have repro'd the issue and will get it fixed!
