### ISSUE TITLE
Is there a way to disable overflow/ellipsis of specific columns in a DetailsList?

### ISSUE THREAD

**Issue by pierre-moire** [OfficeDev/office-ui-fabric-react#10878]
Hello,

Some columns may be more important than others and I would like to be sure they are not hidden partially (actions columns for instance). Is there a config setting for that? Otherwise can you add this functionality?

Thanks !

**Comment by marygans** [comment]
Hi @pierre-moire, thank you for submitting this issue! 

One thing I would suggest is utilizing [` minWidth ` ](https://github.com/OfficeDev/office-ui-fabric-react/blob/e41e8d4eb41455814412f0713c632da4ee511cfa/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.types.ts#L361) to show the full content of your important columns. See it utlized in this example [here](https://codepen.io/gwiz0210/pen/ZEEpKxZ?&editable=true) a few times. This way the ellipsis logic is not applied and your content is no longer hidden, even if the columns are resizable. 

If this is not what you are looking to achieve, a codepen would be helpful for me to better understand the problem. 

Thanks!
