### ISSUE TITLE
Demo website: Persona image is not loading for Persona example

### ISSUE THREAD

**Issue by MLoughry** [OfficeDev/office-ui-fabric-react#1087]
#### Describe the issue:

On the [demo website](http://dev.office.com/fabric#/components/persona), the image for the PErsona in the Persona demo page is not being loaded due to an HTTP 404

#### Actual behavior:

![image](https://cloud.githubusercontent.com/assets/20823465/23225793/053f3198-f8e8-11e6-9d5f-5f7ee491756a.png)

#### Expected behavior:

![image](https://cloud.githubusercontent.com/assets/20823465/23228602/065cd42c-f8f2-11e6-8b19-3577c1b6a88f.png)

**Comment by mikewheaton** [comment]
I think @battletoilet has been looking at this issue. It affects other components as well.

**Comment by gitjain** [comment]
It's been fixed so closing the issue.

**Comment by mikewheaton** [comment]
I'm still seeing the same issue:

![image](https://cloud.githubusercontent.com/assets/1382445/24265316/56297df4-0fc0-11e7-86ed-9946b61c738a.png)

**Comment by leddie24** [comment]
Looks like this is resolved now, image isn't 404'ing here

https://static2.sharepointonline.com/files/fabric/office-ui-fabric-react-assets/persona-female.png
