### ISSUE TITLE
ChoiceGroupOptioin with Icon

### ISSUE THREAD

**Issue by gbminnock** [OfficeDev/office-ui-fabric-react#10879]
### Environment Information

- **Package version(s)**: office-ui-fabric-react@16.189.2

codepen:
https://codepen.io/gbminnock/pen/zYYKKPa

#### Actual behavior:

When using ChoiceGroup with Icon and multiple text the text overflows and it cut off.
I tried resizing some stuff but it never come out correct. 

#### Expected behavior:
Text not truncated

### Priorities and help requested:
Requested priority: (High)

**Comment by marygans** [comment]
Hi @gbminnock thank you for submitting this issue! I am getting some feedback from a designer on how to proceed with this margin issue. I will get back to you soon!

**Comment by marygans** [comment]
Have you tried adjusting the size of the `width` and `height` props in `imageSize`? like in this [codepen](https://codepen.io/gwiz0210/pen/ZEEpePR?&editable=true). That might help to get the text to fit for your use case. I do think the spacing be more flexible for users based on the the text.

**Comment by gbminnock** [comment]
Hi @marygans, sorry I had assumed I needed to be using "image" for that to work. I can confirm that it does indeed work with "icon" also. Thank you. 
Gary
