### ISSUE TITLE
[DetailsList] Could you add a prop to disable the select event on the specified column? Or recommand a workaround?

### ISSUE THREAD

**Issue by jieqiu0129** [OfficeDev/office-ui-fabric-react#10875]
#### Describe the feature that you would like added

In the single page website, when I render a link in the details list and then click on the link, it always trigger the onSelectionChanged event, then trigger the link click event.
For some perf reasons, I need: when I click link, it doesn't trigger onSelectionChanged event...

So could you add a prop to disable the onSelect event on the specified column？Or some workaround you recommend? Thanks

#### What component or utility would this be added to

DetailsList

**Comment by KevinTCoughlin** [comment]
This may already be possible with the existing `SelectionZone` related props. Requires some testing.

**Comment by jieqiu0129** [comment]
> This may already be possible with the existing `SelectionZone` related props. Requires some testing.

Thanks for the reply. I didn't find a prop can resolve this problem: https://docs.microsoft.com/en-us/javascript/api/office-ui-fabric-react/iselectionzoneprops?view=office-ui-fabric-react-latest#oniteminvoked 
Could you tell me if you find? :)

**Comment by marygans** [comment]
> > This may already be possible with the existing `SelectionZone` related props. Requires some testing.
> 
> Thanks for the reply. I didn't find a prop can resolve this problem: https://docs.microsoft.com/en-us/javascript/api/office-ui-fabric-react/iselectionzoneprops?view=office-ui-fabric-react-latest#oniteminvoked
> Could you tell me if you find? :)

I believe @KevinTCoughlin is referring to the[ SelectionZone props](https://github.com/OfficeDev/office-ui-fabric-react/blob/1b9405b3b64839975e16ee1fad04d7868d9e3b99/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.types.ts#L90) within DetailsList

**Comment by jieqiu0129** [comment]
Any update?

**Comment by KevinTCoughlin** [comment]
> Any update?

@jieqiu0129, the following _selectable_ `DetailsList` example does not invoke `onSelectionChanged` when an anchor link rendered in a column cell is clicked: https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/variablerowheights

Can you employ the same strategy for your use-case?

I'm not sure a prop for this is something we want or have the capacity to add right now. If the above doesn't work for you and you wish to raise a PR, please do so.
