### ISSUE TITLE
Disabled Picker uses transparent border instead of same color as input

### ISSUE THREAD

**Issue by mattmazzola** [OfficeDev/office-ui-fabric-react#10884]
Minor - I believe this is a simple CSS fix.

For TextFields when it is disabled the grey color matches the input so the item doesn't change size.
However for Pickers the border goes to `transparent` which makes it look like it changes size.

Can be seen on the Office Fabric demo page, by toggling the checkbox:
https://developer.microsoft.com/en-us/fabric#/controls/web/pickers

![image](https://user-images.githubusercontent.com/2856501/67045743-bd8eb700-f0e3-11e9-9a9a-70675aff2736.png)

**Comment by betrue-final-final** [comment]
Yeah that's true. We should have a matching border with the background so it doesn't shrink
