### ISSUE TITLE
IRawStyleBase should include Ms* grid rules

### ISSUE THREAD

**Issue by brandonthomas** [OfficeDev/office-ui-fabric-react#10891]
#### Describe the feature that you would like added
In order to properly support grid in IE11 many props need to use the proprietary CSS rules. Currently, we don't have the typings for this.

#### What component or utility would this be added to

IRawStyleBase 

#### Have you discussed this feature with our team, and if so, who

Not yet

#### Additional context/screenshots

CSS Grid is super useful and is important for many of the upcoming WCAG requirements so having it supported without having to tsignore would be great.

**Comment by brandonthomas** [comment]
I'm currently using MsGridColumn, MsGridColumnSpan, MsGridRow,MsGridRowSpan, MsGridColumns but I know there are a few more. Additionally, I have to detect IE11 and then change my display rule based on that. I cannot provide two display rules like I normally would in CSS. If I TS ignore the double display it works in Chrome/FF but IE11 whines about duplicate keys in my object so conditionally constructing the object was the only way I found around that issue.

**Comment by marygans** [comment]
Hi @brandonthomas thanks for submitting this issue! We definitely will want this support as well as other things missing. We have similar open issues tracking the grid work and this has been coming up pretty frequently. FYI @paulgildea

**Comment by brandonthomas** [comment]
@paulgildea or @marygans are there other issues you can point me to for tracking?

**Comment by ecraig12345** [comment]
The most closely related discussion to this one is on #8195 about adding some other properties related to CSS grid. I'm not sure if the arguments against adding those props would apply here. @phkuo or @dzearing would be better people to ask about that.

(We also have an issue #5418 for adding a component that encapsulates CSS grid, but that's of course much larger than just adding properties.)

**Comment by phkuo** [comment]
#8195 would be the one to refer to. It's up to @dzearing whether we want to do the short term solution now. @micahgodbolt as FYI.

**Comment by brandonthomas** [comment]
@paulgildea I think this item is still valid and shouldn't be closed.

**Comment by xugao** [comment]
@brandonthomas - are you blocked on this? since Edge chromium has released, we are de-prioritizing work related to IE 11 and old edge unless it's blocking issues

**Comment by khmakoto** [comment]
FYI @xugao, there is also this issue already for this kind of work #6067.
