### ISSUE TITLE
TagPicker doesn't work well with narrator enabled.

### ISSUE THREAD

**Issue by CharlesgdHill** [OfficeDev/office-ui-fabric-react#10915]
### Environment Information

- **Package version(s)**: Current
- **Browser and OS versions**: Edge, Windows 10

### Describe the issue:
Picker

Issue is that with Narrator enabled on Edge, when you want to navigate the suggestions below the Picker, the narrator steals focus from the Picker text area and puts it into the suggestions drop down, but there's no way back into the Picker text area. You also can't cancel the selection of an item in the dropdown once you enter into it.

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/charlesgdhill/pen/pooNvqr

#### Actual behavior:

most functions of the picker don't work with keyboard navigation with narrator enabled. Typing and then attempting to select one of the options displayed doesn't work, and you can't close the suggested tag callout or slect a tag.

#### Expected behavior:

TagPicker should work with narrator enabled.

**Comment by marygans** [comment]
Hi @CharlesgdHill, thanks for submitting this issue! 
I am unable to repro this issue you mentioned of not having the ability to cancel the selection of an item. I am also able to move between tags (See below):
![tagpicker](https://user-images.githubusercontent.com/38991459/67133607-70cddd80-f1c2-11e9-8651-0889bb19d898.gif)

After activating the suggestions, the narrator moves focus back to the input box. 
 
![tagpicker2](https://user-images.githubusercontent.com/38991459/67133682-ca360c80-f1c2-11e9-871c-43ce2b9410d1.gif)

If there are other issues you noticed with the picker please share and we will be happy to help.

Thanks!

**Comment by CharlesgdHill** [comment]
@marygans Hey, I was able to repro this in the codepen provided. I've included a gif with the on-screen keyboard. Can you look at it and see if this should be reopened?
![TagPicker](https://user-images.githubusercontent.com/44102734/67422882-2795d900-f588-11e9-9ad4-e6a89f565c39.gif)

**Comment by marygans** [comment]
@CharlesgdHill thanks for sharing! I will take another stab at reproing this

**Comment by joschect** [comment]
@CharlesgdHill The issue is that the picker should have either automatically selected the first item or dismissed the suggestions. It looks like there was a problem in the codepen. I fixed the javascript error and now it works as [intended](https://codepen.io/slimemold/pen/xxxyEgN?editors=0011)
