### ISSUE TITLE
Button: padding moved from ms-Button to ms-Button-label

### ISSUE THREAD

**Issue by cschleiden** [OfficeDev/office-ui-fabric-react#1091]
Question, no bug: before the latest button refactoring, the button base class `ms-Button` provided padding in all directions:

![image](https://cloud.githubusercontent.com/assets/2201819/23239001/948a9bd6-f919-11e6-9ec9-d12fb19275f9.png)

This made it easy to render custom children

![image](https://cloud.githubusercontent.com/assets/2201819/23239029/b578d6fa-f919-11e6-8822-daad3734c799.png)

```
  <Button ...>
     <span>
        <i className="bowtie-icon bowtie-math-plus-light" />{this.props.label}
     </span
  </Button>
```

Now, the default padding/height is provided by the `ms-Button-label` class and the previous example results in this:

![image](https://cloud.githubusercontent.com/assets/2201819/23239070/e8ec4a8a-f919-11e6-96b2-16382c87bef1.png)

Potential solutions to restore the previous behavior might be:
- apply `ms-Button-label` class to the span, doesn't feel right and might break once that class isn't associated with any rules anymore
- have a separate class, that applies the same styling as `ms-Button-label`, feels like it might get out of sync easily

Any other suggestions?

**Comment by joschect** [comment]
@cschleiden We found in many places removing the span seemed to rectify a lot of the problems with the button. You can also pass the icon and label through to the button and it should render it properly as well.

**Comment by cschleiden** [comment]
@joschect the problem is sometimes I have two icons (left/right) which I think the button doesn't support :) For now I've added `height`/`line-height` `32px` to my own `span`, but maybe we could provide `min-height` on the button?
