### ISSUE TITLE
CommandBar items moving to overflow sometimes, working properly only on re render.

### ISSUE THREAD

**Issue by GayathriSNS123** [OfficeDev/office-ui-fabric-react#10919]
### Environment Information

- **Package version(s)**: ^6.208.0 || ^7.48.0
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

Menu items moving into overflow items when clicked again and again. 
#### Expected behavior:

Menu items and overflow items should be separate
### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

My code:

 function getMenuItems(): ICommandBarItemProps[] {
    return [
      {
        key: strings.'New'
        name:'New',
        iconProps: {
          iconName: 'NewFolder'
        },
        onClick: addClicked
      },
      {
        key:'Delete',
        name:'Delete',
        iconProps: {
          iconName: 'Delete'
        },
        onClick: deleteClicked
      }
    ];
  }

  function getOverFlowItems(): ICommandBarItemProps[] {
    return [
      {
        key: 'Import',
        name: 'Import',
        iconProps: {
          iconName: 'Import'
        },
        disabled: true
      },
      {
        key: 'Export',
        name: 'Export',
        iconProps: {
          iconName: 'Export'
        },
        disabled: true
      }
    ];
  }

return (
    <div className={styles.toolbar}>
      <CommandBar styles={{ root: { paddingLeft: '0px' } }} items={getMenuItems()} overflowItems={getOverFlowItems()} />
    </div>
  );

Behaviour:

![image](https://user-images.githubusercontent.com/56819364/67187643-4b321580-f408-11e9-9bbb-6e4352f95230.png)

On one click:

![image](https://user-images.githubusercontent.com/56819364/67187693-63099980-f408-11e9-850c-f8edf7ae645c.png)

On another click:

![image](https://user-images.githubusercontent.com/56819364/67187717-7452a600-f408-11e9-964d-359e2ec92619.png)

**Comment by jdhuntington** [comment]
Hi @GayathriSNS123 - Thanks for the report. I created a codepen with your code here ( https://codepen.io/jdh-msft/pen/gOOgMmX?editors=0010#0 ), but unfortunately I was unable to reproduce your issue. Would you be willing to fork, edit, then send a link? Thanks!

**Comment by GayathriSNS123** [comment]
Sure, I will get back to you in couple of days.
Thank you!
