### ISSUE TITLE
Multiple lines/description in ChoiceGroup

### ISSUE THREAD

**Issue by malmil** [OfficeDev/office-ui-fabric-react#10920]
#### Describe the feature that you would like added

It would be a really nice feature to have multiple lines on the radio group for use-cases where you need a description to the radio option. Personally I would prefer a solution where you can pass it with the options like this:

```
options: [
    {
      key: 'A',
      text: 'Ordinær registrering',
      description: 'Alle næringsdrivende som har omsetning som omfattes av merverdiavgiftsloven må registrere seg i Merverdiavgiftsregisteret.'
    },
    {
      key: 'B',
      text: 'Frivillig registrering',
      description: 'Enkelte virksomheter som i utgangspunktet ikke er mva-pliktig, kan søke om frivillig registrering. Eks. utleie av bygg og anlegg, bortforpaktere av landbrukseiendom, utbygger av vann- og avløpsanlegg, skogsveiforeninger, baneanlegg.'
    }
  ]
```

#### What component or utility would this be added to

ChoiceGroup

#### Additional context/screenshots
<img width="347" alt="radioButtonGroup" src="https://user-images.githubusercontent.com/37180955/67191251-98ef5380-f3f1-11e9-9fbd-ef6049775986.PNG">

**Comment by jdhuntington** [comment]
Hi @malmil - thanks for the request. This makes sense, and I think this would look good.

Are you interesting in submitting a PR which adds this feature?

Also cc'ing @betrue-final-final and @ecraig12345 for comments/context.

**Comment by malmil** [comment]
@jdhuntington 
Thanks for the quick response!
I'll gladly make a PR for a suggestion for this

**Comment by malmil** [comment]
How to solve the need for description is showed here:
https://github.com/OfficeDev/office-ui-fabric-react/pull/10930#issuecomment-547127835
