### ISSUE TITLE
In Multiline TextField screen reader not able to read the input text value

### ISSUE THREAD

**Issue by mahajanchetnaC** [OfficeDev/office-ui-fabric-react#10923]
Environment Information
It was repro at Chrome

Describe the issue:
In case of TextField is multiline, Narrator does not read textfield input value the way it reads in Basic TextFields

Repro Steps:
1. type any message and re-navigate on the text. 
2. Verify the speech of screen reader when focus lands on the text should read the value
-->

Actual behavior:
In case of TextField is multiline, Narrator does not read textfield input value the way it reads in Basic TextFields

Expected behavior:
 Verify the speech of screen reader when focus lands on the text should read the value

**Comment by jdhuntington** [comment]
Hi @mahajanchetnaC - Sorry you are encountering this issue. Unfortunately, I am unable to reproduce the behavior you are describing. I created this demo https://codepen.io/jdh-msft/pen/MWWJoKL and it seems that the native textarea and multiline text are behaving the same way. I've tried in both chrome and edge, and see consistent behavior.

If your scenario is different, would you be willing to fork this codepen and create a repro? Thanks!

**Comment by mahajanchetnaC** [comment]
Thank for responding back. And I agree in your codepen both of them are behaving same. But we have a bug opened in our part where the Text area screen reader should read the input value.
So  basically when you install JAWS screen reader on the machine and then go to below link:
https://developer.microsoft.com/en-us/fabric#/controls/web/textfield
Type text example "Test Screen Reader" in the standard Basic TExt Fields and then get the focus out of the text area and come back to the text area, the screen reader would read the input value "Test Screen Reader". But the similar experience is not happening in Multi Text Area. @jdhuntington

**Comment by jdhuntington** [comment]
Thanks @mahajanchetnaC - in your original issue you mentioned Narrator as well; can you confirm if this issue exists in JAWS, Narrator, or both? Also, would you be willing to make an example on Codepen.io that exhibits the issue? There are several factors on developer.microsoft.com that make triangulating issues more difficult.
