### ISSUE TITLE
Dropdown : Value of combo box control for required fields automatically selected while navigating first time by using Tab key.

### ISSUE THREAD

**Issue by 999-Dev** [OfficeDev/office-ui-fabric-react#10932]
**User Experience:**
It will impact the functionality if the combo box if, required field value is selected automatically while navigating the control first time by using Tab key.

**Test Environment:**
OS: Version: RS5_Prerelease(1903 OS Build 19005.1)
URL: https://developer.microsoft.com/en-us/fabric#/controls/web/dropdown
Edge Browser Version:
Microsoft Edge: 44.19005.1.0
Microsoft EdgeHTML: 18.19005
Chrome Browser Version:
Chrome: 77.0.3865.120

**Usages:**
Required Dropdown

**Repro Steps:**
1.https://developer.microsoft.com/en-us/fabric#/controls/web/dropdown in Edge.
2.Navigate to 'Basic input' button and activate it.
3.Navigate to 'Dropdown' link and activate it.
4.'Dropdown' pane will be appeared.
5.Navigate to controls under by using Tab key and verify the issue.

**Actual Result:**
Required field value automatically selected while navigating using Tab key. Required field values automatically get selected. 

**Expected Result:**
Required filed does not select automatically while navigating by using Tab key.

**Attachment:**
[Functional.zip](https://github.com/OfficeDev/office-ui-fabric-react/files/3754775/Functional.zip)

**Comment by jdhuntington** [comment]
Hi @999-Dev - I understand that the dropdown does not automatically select an option when first focused via tab. However, it seems like selecting an option at random makes the experience worse for keyboard users. Can you point to prior art or similar components where this is the expected behavior?
