### ISSUE TITLE
Callout unexpected behavior when use backdrop-filter attribute.

### ISSUE THREAD

**Issue by 104error** [OfficeDev/office-ui-fabric-react#10938]
### Environment Information

- **Package version(s)**:  7.34.0
- **Browser and OS versions**:  Version 77.0.3865.120 (Official Build) (64-bit)
Windows 10

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/104error/pen/dyyvMzL

#### Actual behavior:

Click button and move mouse at same time. Some time the menu turns solid black.
I tested this  backdrop-filter attribute in clean environment and proved it works with animation and visibility and display attributes so it could be related to how we deal with hover/focus in office react.
#### Expected behavior:

Fly out menu should stably have blurred effect and be semi transparent.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No I don't have root cause of it now.
Requested priority: (Blocking, High, Normal, Low)
Blocking
Products/sites affected: (if applicable)
PPTO Slide Show.

**Comment by jdhuntington** [comment]
Hi @104error - sorry you're hitting this issue. I am afraid I have been unable to reproduce in either Chrome or Edge.

Few questions:
- When you are clicking and moving the mouse at the same time, is the menu open or closed?
- Are you clicking menu items or the button itself?
- What browser are you using?

If you are able to post a short recording of the issue that would help as well.

**Comment by 104error** [comment]
Posting a gif

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: JD Huntington <notifications@github.com>
发送时间: Tuesday, October 22, 2019 4:22:39 PM
收件人: OfficeDev/office-ui-fabric-react <office-ui-fabric-react@noreply.github.com>
抄送: Bingyang Zhao <Bingyang.Zhao@microsoft.com>; Mention <mention@noreply.github.com>
主题: Re: [OfficeDev/office-ui-fabric-react] Callout unexpected behavior when use backdrop-filter attribute. (#10938)


Hi @104error<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2F104error&data=02%7C01%7Cbingyang.zhao%40microsoft.com%7C8b4a4360d79645e4393208d75746bb6c%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637073833619986672&sdata=03mqzlXY2d4C%2F37MbxcEAO5Mg%2BP%2FrlMOZ9VgJHe0WuY%3D&reserved=0> - sorry you're hitting this issue. I am afraid I have been unable to reproduce in either Chrome or Edge.

Few questions:

  *   When you are clicking and moving the mouse at the same time, is the menu open or closed?
  *   Are you clicking menu items or the button itself?
  *   What browser are you using?

If you are able to post a short recording of the issue that would help as well.

―

**Comment by 104error** [comment]
![demo4](https://user-images.githubusercontent.com/55766683/67344209-48a8ec00-f4ec-11e9-9ab8-f57def2d6cf2.gif)

**Comment by 104error** [comment]
Hi JD,
A gif is uploaded.

  1.  the menu is opened
  2.  the button itself
3. I was doing it in Chrome.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by jdhuntington** [comment]
Thanks for the gif - that's very helpful. I am able to repro in both chrome and edge beta.

Notes for myself: I am able to consistently repro by dragging across the button as if I am highlighting the text, then releasing while still on the button. I have discovered that the issue only exists when there is a `backdropFilter` specified; it does not appear to repro otherwise. 
Next steps: See if there is a repro with backdrop filter when using only native DOM.

**Comment by 104error** [comment]
I actually have several code pen testing in native DOM if you wanna reference to. With animation and changing display it appears to be pretty stable. Thats why I am curious if something special is happening in fabric.

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: JD Huntington <notifications@github.com>
发送时间: Tuesday, October 22, 2019 5:51:25 PM
收件人: OfficeDev/office-ui-fabric-react <office-ui-fabric-react@noreply.github.com>
抄送: Bingyang Zhao <Bingyang.Zhao@microsoft.com>; Mention <mention@noreply.github.com>
主题: Re: [OfficeDev/office-ui-fabric-react] Callout unexpected behavior when use backdrop-filter attribute. (#10938)


Thanks for the gif - that's very helpful. I am able to repro in both chrome and edge beta.

Notes for myself: I am able to consistently repro by dragging across the button as if I am highlighting the text, then releasing while still on the button. I have discovered that the issue only exists when there is a backdropFilter specified; it does not appear to repro otherwise.
Next steps: See if there is a repro with backdrop filter when using only native DOM.

―

**Comment by 104error** [comment]
https://codepen.io/104error/pen/GRRNJwE

**Comment by 104error** [comment]
Posted my code pen for native DOM.
Another strange thing:
backdrop filter should work when set to callout root or calloutMain.
But if I put this to calloutMain which is a child to callout root and set root to be transparent.
It does not apply blur at all.
See it in:
https://codepen.io/104error/pen/dyyvMzL

**Comment by 104error** [comment]
Ping

**Comment by jdhuntington** [comment]
Hi @104error - sorry for the delayed followup. After working with some folks from Edge who have provided a ton of help, it looks like this is an issue in Chromium. ( https://bugs.chromium.org/p/chromium/issues/detail?id=983252 , for example, is a similar issue)

Different versions of Chrome(+chromium) appear to have some rendering issues - some displaying a black backdrop and some not respecting the background blur property.

Unfortunately I don't believe there's anything we can change in the Fabric components to make this more reliable, it will likely need to be some experimentation on your end to find the right combination of filters to make it work in the right browsers.

**Comment by 104error** [comment]
Thanks JD!
Reported the situations to my managers.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
