### ISSUE TITLE
Dialog onDismiss swallows exceptions

### ISSUE THREAD

**Issue by rickyp-ms** [OfficeDev/office-ui-fabric-react#1093]
### Bug Report

- __Package version(s)__: 1.5.0
- __Browser and OS versions__: Chrome and Windows

#### Describe the issue:

If the onDismiss handler for the Dialog throws an exception, it doesn't get sent to the console

#### Actual behavior:

No exception

#### Expected behavior:

Exception to be fired

**Comment by micahgodbolt** [comment]
@rickyp-ms do you know of another component that does this properly?

**Comment by rickyp-ms** [comment]
No... I haven't done a full pass of exception handling for these components. Not a bad idea to add that as a requirement for your test suite for every component (It's how we found it).

**Comment by gitjain** [comment]
@rickyp-ms 

Tried to repro the issue in codepen and it seems to be working fine. 
Dialog does show the exception in console (developer's console) with and without try/catch.
Codepen consoles sometime don't show the actual results. So try developer's console.

Sharing the codepen:  http://codepen.io/reenajain/pen/PpXZOa

Let me know if you still facing the issue.

**Comment by rickyp-ms** [comment]
I should be able to verify it Wednesday as I'm on vacation until then.


Cheers,

Ricky


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by gitjain** [comment]
@rickyp-ms 
Can you please verify so that I can ahead and close the issue.

**Comment by rickyp-ms** [comment]
Looks good thanks!
