### ISSUE TITLE
Dropdown : After activating the 'Set Focus' button, focus moves to 'Required dropdown example' combo box.

### ISSUE THREAD

**Issue by 999-Dev** [OfficeDev/office-ui-fabric-react#10933]
**User Experience:**
User will be confused if after activating the 'Set Focus' button, focus directly moves to 'Required dropdown example'.

**Test Environment:**
OS: Version: RS5_Prerelease(1903 OS Build 19005.1)
URL: https://developer.microsoft.com/en-us/fabric#/controls/web/dropdown
Edge Browser Version:
Microsoft Edge: 44.19005.1.0
Microsoft EdgeHTML: 18.19005
Chrome Browser Version:
Chrome: 77.0.3865.120

**Usages:**
Required Dropdown

**Repro Steps:**
1.https://developer.microsoft.com/en-us/fabric#/controls/web/dropdown in Edge.
2.Navigate to 'Basic input' button and activate it.
3.Navigate to 'Dropdown' link and activate it.
4.'Dropdown' pane will be appeared.
5.Navigate to 'Required Dropdown' controls under by using Tab key and verify the issue.

**Actual Result:**
After activating the 'Set Focus' control, focus moves 'Required dropdown example' combo box button.

**Expected Result:**
There is no need for 'Set Focus' button. After activating the button, 'Required dropdown example' combo box get activated. At the same time we can navigate the control separately. 

**Attachment:**
[OneDrive_2019-10-22 (1).zip](https://github.com/OfficeDev/office-ui-fabric-react/files/3755360/OneDrive_2019-10-22.1.zip)

**Comment by jdhuntington** [comment]
Hi @999-Dev - The purpose of the "Set Focus" button is to demonstrate how to control focus programatically. Thank you for the feedback, but this control is working as intended.
