### ISSUE TITLE
Toggle content can render outside of its bounds if label is unbreakable and long

### ISSUE THREAD

**Issue by dPJinjo** [OfficeDev/office-ui-fabric-react#10936]
### Environment Information

- **Package version(s)**: "office-ui-fabric-react": "7.6.0"
- **Browser and OS versions**: Chrome Version 77.0.3865.120 (Official Build) (64-bit) - Windows 10 Enterprise 64-bit (10.0, Build 18363) (18362.19h1_release.190318-1202)

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/dPJinjo/pen/QWWpyGX

CSS
```
.skinny {
  width: 240px;
  background-color: cyan;
}
```

JS
```
let { Toggle } = window.Fabric;

const Content = () =>   
  <Toggle className="skinny" label="thisisareallylonglabelwithnobreakswhichforcesthetoggleout" onText="on" offText="off" inlineLabel defaultChecked />;

ReactDOM.render(
  <Content />, 
  document.getElementById("content")
);
```

Result
![image](https://user-images.githubusercontent.com/16249087/67332541-05428380-f4d4-11e9-8c56-797bb318a7e8.png)

#### Actual behavior:

It's possible to force parts of a Toggle outside of the bounds of the Toggle if the label is a very long unbreakable string

#### Expected behavior:

All Toggle contents should be rendered within the Toggle bounds and not overflow off of the end.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: (Normal)

Products/sites affected:

**Comment by jdhuntington** [comment]
Thanks for the concise repro @dPJinjo - will figure out the right way to resolve this.
