### ISSUE TITLE
Teams Brand icon not present in Fabric icons

### ISSUE THREAD

**Issue by sakulshr** [OfficeDev/office-ui-fabric-react#10947]
I see that there are brand icons for Word in fabric.css (.ms-BrandIcon--word.ms-BrandIcon--icon16). The same is true for Excel, PowerPoint, and Outlook. However, I do not find any Teams brand icons.

**Comment by jdhuntington** [comment]
Hi @sakulshr - Can you clarify if you are using office-ui-fabric-react and the react `<Icon>` control, or are you using fabric.css and pulling styles directly?

I believe the teams logo exists in the react package. If you are using fabric.css, it looks like that was recently added ( https://github.com/OfficeDev/office-ui-fabric-core/pull/1195 ), though it is developed in a different repository.

Please let me know if you aren't able to access it and I can help get things sorted out.

**Comment by larnera** [comment]
If you are pulling in the styles directly then use :
https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/10.1.0/css/fabric.min.css

This has the Teams logo.
