### ISSUE TITLE
Dialog not closing on escape button press

### ISSUE THREAD

**Issue by jtripathi226** [OfficeDev/office-ui-fabric-react#10942]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Describe the issue:

We have used dialog for recurrence and expect it to close when the user pressed escape. Currently escape in not handled in the component.

#### Actual behavior:
Dialog does not close on escape

#### Expected behavior:

Dialog should close on escape

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by jdhuntington** [comment]
Hi @jtripathi226 - Sorry you're encountering this issue. I believe the Dialog does handle escape and dismiss (as seen on https://fabricweb.z5.web.core.windows.net/oufr/7.54.1/#/examples/dialog ). Are you able to put a small repro of the issue you're encountering together and host it on codepen.io?
