### ISSUE TITLE
Office fabric DetailedList is not loading inside Accordion body in IE 11 browser on expanding

### ISSUE THREAD

**Issue by Sandhya-aluri** [OfficeDev/office-ui-fabric-react#10959]
![IE-History](https://user-images.githubusercontent.com/48669559/67478742-4d9ba600-f67a-11e9-983d-e036cee2d2d1.png)

### Environment Information

- **Package version(s)**:  "office-ui-fabric-core": "^9.6.1",
				        "office-ui-fabric-react": "~6.162.1",
- **Browser and OS versions**: IE 11 and windows

### Describe the issue:
Office fabric DetailedList is not loading inside Accordion body in IE 11 browser on expanding , working fine in other browsers.
Please find the attachments Chrome - History is expected behaviour , IE - History is actual behaviour

#### Actual behavior:
Office fabric DetailedList  should load on accordion expand in IE11 browser.

#### Expected behavior:
Office fabric DetailedList is not loading inside Accordion body in IE 11 browser on expanding

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) : 
![Chrome - History](https://user-images.githubusercontent.com/48669559/67478738-4a081f00-f67a-11e9-8ced-d4e951a37cd6.png)

Requested priority: (Blocking, High, Normal, Low) : 

Products/sites affected: (if applicable)

**Comment by jdhuntington** [comment]
Thanks @Sandhya-aluri !
