### ISSUE TITLE
Theme Designer - Default text colours are incorrect

### ISSUE THREAD

**Issue by Toonshorty** [OfficeDev/office-ui-fabric-react#10958]
When creating a new theme from the theme designer (https://aka.ms/themedesigner) the default text colour is set to #323130, but the other neutral colours are not being calculated correctly from this value.

#### Actual behavior:

If you create a new Fabric UI project and call the 'getTheme' function the following text colours are set by default:

```
black: "#000000"
neutralDark: "#201f1e"
neutralLight: "#edebe9"  
neutralLighter: "#f3f2f1"  
neutralLighterAlt: "#faf9f8"  
neutralPrimary: "#323130"  
neutralPrimaryAlt: "#3b3a39"  
neutralQuaternary: "#d2d0ce"
neutralQuaternaryAlt: "#e1dfdd"
neutralSecondary: "#605e5c"
neutralSecondaryAlt: "#8a8886"
neutralTertiary: "#a19f9d"
neutralTertiaryAlt: "#c8c6c4"
```

When loading the theme builder, the default text colour is set to `#323130` which is correct, however the other semantic colours aren't calculated correctly and the following values are returned:

```
black: "#494847"
neutralDark: "#605e5d"
neutralLight: "#eaeaea"  
neutralLighter: "#f4f4f4"  
neutralLighterAlt: "#f8f8f8"  
neutralPrimary: "#323130"  
neutralPrimaryAlt: "#8d8b8a"  
neutralQuaternary: "#d0d0d0"
neutralQuaternaryAlt: "#dadada"
neutralSecondary: "#a3a2a0"
neutralTertiary: "#bab8b7"
neutralTertiaryAlt: "#c8c8c8"
```

In some cases, the differences in colours are quite dramatic. The neutralSecondary palette for example is returned as `#a3a2a0` rather than `#605e5c`. Notably, the former is not actually WCAG compliant when used on a white background.

#### Expected behavior:

The theme builder should generate the same neutral colour palette as the Fabric default if the primary neutral colour is the same.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: Fabric UI Theme Generator

**Comment by jdhuntington** [comment]
Thanks for the report; will get this sorted out.

**Comment by aneeshack4** [comment]
@Toonshorty I think I might have a fix for this - working on getting a PR out soon, thanks for reporting it!
