### ISSUE TITLE
Dropdown keyboard selection in high contrast selection issues

### ISSUE THREAD

**Issue by jgage176** [OfficeDev/office-ui-fabric-react#10953]
Dropdown support for high contrast, specifically for selecting using the keyboard to select items does not make the selection clear. Here are some examples:

On the main site (https://developer.microsoft.com/en-us/fabric#/controls/web/dropdown) selection and current focus look like this:
![image](https://user-images.githubusercontent.com/29739628/67427686-7005c480-f591-11e9-86a3-6754965d5e4a.png)

On https://fabricweb.z5.web.core.windows.net/oufr/7.54.1/#/examples/dropdown it has a bit different look, but also has issues which we have seen on our own site:

![image](https://user-images.githubusercontent.com/29739628/67427742-93c90a80-f591-11e9-82ff-19c07a083c56.png)

Notice how it is very hard to see what item is selected. For a non multi-select example, using arrow keys to switch between Carrot and Lettuce look like this:

![image](https://user-images.githubusercontent.com/29739628/67427794-b529f680-f591-11e9-9cf1-3b76018e0569.png)

![image](https://user-images.githubusercontent.com/29739628/67427804-b8bd7d80-f591-11e9-9e9b-f686c6654ae5.png)

@gouthamigangu

**Comment by jdhuntington** [comment]
Thanks for the report. Will dig into this issue this week.
