### ISSUE TITLE
Fabric common-js files import es module files

### ISSUE THREAD

**Issue by HarryGifford** [OfficeDev/office-ui-fabric-react#10950]
### Environment Information

- **Package version(s)**: office-ui-fabric-react 7.54.1
- **Browser and OS versions**: Not relevant.

### Please provide a reproduction of the bug in a codepen:

Not a codepen repro, but see this [repo](https://github.com/HarryGifford/FabricJestTestImports) to demo this issue.

#### Actual behavior:

common-js files reference modules which causes Jest and Node to fail since they don't support modules. One fix is to run the fabric through babel, but this isn't an ideal fix.

Our tests were working until the latest update. In our case the issue comes from [`SuggestionsControl`](https://github.com/OfficeDev/office-ui-fabric-react/pull/9912/files). I haven't tested it, but I think importing from the root should fix the issue.

#### Expected behavior:

Module files should import modules and common-js should import common-js.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by jdhuntington** [comment]
Thanks for the concise repro. Will dig into this this week.

**Comment by ecraig12345** [comment]
@kenotron did some work in #10561 which I think should have addressed this, but maybe it's not fully working?

**Comment by KagamiChan** [comment]
@ecraig12345
I can repro this bug with Create React App, it happends since version 7.54.0, last known good version for me was 7.53.1

**Comment by KagamiChan** [comment]
@ecraig12345
I can repro this bug with Create React App, it happends since version 7.54.0, last known good version for me was 7.53.1

**Comment by KagamiChan** [comment]
Ping

BTW I think this should be a bug because it will block users using Jest or Create-React-App

**Comment by KagamiChan** [comment]
7.56.0 fixed the issue

**Comment by jdhuntington** [comment]
@KagamiChan Afraid this still requires a workaround. We plan to fix this out of the box, but haven't been able to prioritize fixing just yet.

For now, using common-js in jest requires modifying the `moduleNameMapper` directive of `jest.config.js`. This example from your example repo should do the trick:

```js
//@ts-check

/** @type { import("@jest/types").Config.GlobalConfig } */
module.exports = {
    clearMocks: true,
    moduleFileExtensions: ["ts", "tsx", "js"],
    transform: {
        "^.*\\.tsx?$": "ts-jest"
    },
    testPathIgnorePatterns: ["dist", "/build/", "/node_modules/"],
    globals: {
        "ts-jest": {
            packageJson: "package.json"
        }
    },
    moduleNameMapper: {
    "office-ui-fabric-react/lib/(.*)$": "office-ui-fabric-react/lib-commonjs/$1"
  }
};
```

**Comment by KagamiChan** [comment]
Thanks @jdhuntington. This configuration works.

A note for Create-React-App user: CRA only supports adding the config to the `package.json` file, and only adding the `moduleNameWrapper` will do the trick

```json
  "jest": {
    "moduleNameMapper": {
      "office-ui-fabric-react/lib/(.*)$": "office-ui-fabric-react/lib-commonjs/$1"
    }
  }
````

**Comment by kenotron** [comment]
I didn't enable it for fear that it'll break too many things. But maybe good to dig up now.

**Comment by dzearing** [comment]
There is a legit import problem here. I have this addressed in the PR here:

https://github.com/OfficeDev/office-ui-fabric-react/pull/11137

**Comment by dzearing** [comment]
@HarryGifford I pulled your git repo, fixed the import, linked my private oufr build to it, and now your jest example works correctly. Thank you for setting that up!

**Comment by dzearing** [comment]
The build is now published and this is now resolved in the example. Thanks for reporting.

**Comment by HarryGifford** [comment]
Thanks for the quick fix and the `moduleNameMapper` workaround is useful for other cases when this happens.
