### ISSUE TITLE
Extra call to onPendingValueChanged when making selection in combo box

### ISSUE THREAD

**Issue by romartinms** [OfficeDev/office-ui-fabric-react#10955]
Issue can be seen from this:
https://codepen.io/romartin/pen/yLLMwpR

I found the behavior stated in version 7.32.0, changing reference to 7.31.0 fixes the issue.

We have some code that responds to onChange and onPendingValueChanged callbacks

What I am observing is that after making a selection we get the onChange callback, immediately followed by onPendingValueChanged. This is regression from prior version. (the pen logs messages to console)

I expect there should be no call to onPendingValueChanged after the onChange callback is made.  When we see the onPendingValueChanged we disable a button until we see onChange again (basically whenever there is pending value in UI) But since we always recieve onPendingValueChanged immediately after onChange it is broken.

**Comment by jdhuntington** [comment]
Thanks for the description and the repro. Will look at a fix straight away.

**Comment by jdhuntington** [comment]
Note for myself: the transition from 31 -> 32 sees the `onPendingValueChanged` callback still invoked, but just _before_ the `onChange` callback. Ideal to put it back the way it was.
