### ISSUE TITLE
Tooltip opens too late using Edge

### ISSUE THREAD

**Issue by LukeOwlclaw** [OfficeDev/office-ui-fabric-react#10969]
### Environment Information

- **Package version(s)**:  7.55.0
- **Browser and OS versions**: Edge 44.18362.387.0 and IE11

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/LukeO/pen/rNNmoXM

This problem also happens with IE11 (but CodePen does not support IE11)

#### Actual behavior:

Tooltip opens when panel is visible.

#### Expected behavior:

Tooltip should only become visible when related button is visible.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by LukeOwlclaw** [comment]
Workaround: Disabled delay: `delay={TooltipDelay.zero}`

**Comment by kenotron** [comment]
In my testing, this happens in a race condition. It is a bug, but a slight one since it is relatively difficult to repro (at least on Edge, maybe more pronounced on IE11). Also, it looks like there's a workaround.

If the workaround is not sufficient, feel free to keep the bug open. Otherwise, please close this issue.

**Comment by LukeOwlclaw** [comment]
I find it very easy to reproduce using Edge: Move cursor to button, immediately click, do not move mouse. Works every time for me.

The workaround is not sufficient for me. A slightly better workaround (even though I do not know what side effects it has): `calloutProps={{ doNotLayer: true }}`

But even with this workaround (and also without it) a related problem persists:

- Open https://codepen.io/LukeO/pen/rNNmoXM using Edge
- Click "Open panel"
- Close panel
- Click Edge window in taskbar to minimize
- Click Edge window in taskbar to restore window

⇒ The tooltip opens (again)

**Comment by jdhuntington** [comment]
Sorry for the late followup, I am looking at this.
