### ISSUE TITLE
Separator in CommandBar missing for enabled actions

### ISSUE THREAD

**Issue by LukeOwlclaw** [OfficeDev/office-ui-fabric-react#10960]
### Environment Information

- **Package version(s)**: starting with office-ui-fabric-react@7.36.0
- **Browser and OS versions**: any

### Please provide a reproduction of the bug in a codepen:

Check out:
https://codepen.io/LukeO/pen/XWWRNXg

And load "office-ui-fabric-react@7.36.0" to see the difference.

#### Actual behavior:

Since office-ui-fabric-react@7.36.0 there is no separator/divider for split and enabled actions in the CommandBar. There is a separator for disabled actions, though.

#### Expected behavior:

There should either always be a divider or never. But not depending on the enable/disabled setting.
Even better would be an option to choose...

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

**Comment by jdhuntington** [comment]
Thanks for the repro. Will take a look at this.

**Comment by maxwellred** [comment]
@jdhuntington I can grab this one if you don't mind?
