### ISSUE TITLE
Dropdown: Options panel of Dropdown not consistently scrollable on mobile

### ISSUE THREAD

**Issue by marioliu** [OfficeDev/office-ui-fabric-react#10963]
### Environment Information

- **Package version(s)**: office-ui-fabric-react@7.52.0
- **Browser and OS versions**: Chrome, Windows/Android

#### Actual behavior:

When opening the Dropdown on a mobile browser (or in Chrome using the device toolbar) and trying to scroll the options left and right using your finger/mouse (not scroll wheel), it doesn't work all the time. The error Fabric throws in Chrome is:

`[Intervention] Ignored attempt to cancel a touchmove event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.`

In addition to this, the user doesn't even know that the panel can be scrolled left to right because the horizontal scrollbar is so thin and disappears so quickly on mobile Chrome.

I feel like this could be fixed if the options could be text-wrapped to multiple lines instead of being forced to stay on one line.

#### Expected behavior:

Scrolling left and right on a Dropdown should consistently work.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by jdhuntington** [comment]
Hi @marioliu - Sorry you're hitting this issue.

I believe the intent of the dropdown is the left-align the flyout and not allow scrolling. The behavior on mobile is an issue that should be fixed, but I don't think we want it to be scrollable.

I'm currently investigating to see if it's possible to pass overrides to the dropdown that will allow rendering of multiline options.

**Comment by marioliu** [comment]
That works for a desktop view, but not for mobile because the screen size is so limited. What about the scrolling bug? If left and right scrolling were implemented/fixed on mobile, that would solve the issue as well. But, if that can't be done and if it's non-trivial to implement multi-line options, then I guess we'll work on making our strings shorter so they'll fit in the Panel.

**Comment by jdhuntington** [comment]
Sorry for the late followup.

We prefer to avoid horizontal scrolling in all cases, as that's not expected of a dropdown.

I believe these CSS directives might help longer options work for mobile; it allows them to word break in-place. In limited testing it seems to work reasonably well.

```css
.ms-Panel-content .ms-Button.ms-Dropdown-item {
  height: unset;
}

.ms-Panel-content .ms-Button.ms-Dropdown-item .ms-Dropdown-optionText {
  white-space: unset;
}
```

In action: https://codepen.io/jdh-msft/pen/pooLWYK

Does that help?

**Comment by marioliu** [comment]
Looks like that'll work. Thanks for your help!
