### ISSUE TITLE
[Accessibility][ContextualMenu] This creates two elements parent and child with role as menuitem

### ISSUE THREAD

**Issue by vivekjilla** [OfficeDev/office-ui-fabric-react#1096]
#### ContextualMenu component , when rendered, in resultant html you can see a `li` element and a child `button` element both getting the `role` as `menuitem`, which I don't think is a right design pattern.

https://fabricreact.azurewebsites.net/fabric-react/master/#/examples/contextmenu
In the above link we can find examples, and we can look at html to see that there are two items with role menuitem

**Comment by mikewheaton** [comment]
Verified on the [Fabric documentation page for ContextualMenu](http://dev.office.com/fabric#/components/contextualmenu):
![image](https://cloud.githubusercontent.com/assets/1382445/23280579/9a16bac0-f9ce-11e6-9980-f7b95c10da31.png)
