### ISSUE TITLE
Narrator reads page title when dropdowns open inside of modal/dialog

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#10965]
Not sure why, but when you open a dropdown inside of a modal or dialog, it first reads off the page title (Codepen - Fabric Example Pen) and then reads the focused element. 

https://codepen.io/micahgodbolt/pen/oNNWdqw?editors=0010

**Comment by kenotron** [comment]
This appears to happen even without a dropdown (try replacing this codepen with a label and then focus on it)

**Comment by micahgodbolt** [comment]
hmm...in my example focusing on the dropdown is fine. it's opening the dropdown that reads the page title. is the focus set to the page momentarily before being placed onto the dropdown items?

**Comment by jdhuntington** [comment]
@micahgodbolt Can you try loading the debug view and see if it still repros? If I let the iframe gain focus before triggering the popup, I don't hear the title read.

**Comment by micahgodbolt** [comment]
Yeah, in debug mode, as soon as I hit enter to open the dropdown, it reads "Codepen - Fabric example"

**Comment by jdhuntington** [comment]
Which browser are you using?
