### ISSUE TITLE
Grouped list - Need to show parent items with 0 children. 

### ISSUE THREAD

**Issue by paridhiverma** [OfficeDev/office-ui-fabric-react#10971]
#### Describe the feature that you would like added

In a list there can be a scenario, where there is an item without a child node. Currently all such items are supposed to be grouped under one parent. This is adding one extra click + there is no logical groping possible for such items.

#### What component or utility would this be added to

Grouped list

#### Have you discussed this feature with our team, and if so, who

Not yet

#### Additional context/screenshots

![image](https://user-images.githubusercontent.com/47159459/67606237-82b8fe80-f735-11e9-9ec5-1784b26f10ea.png)

**Comment by jdhuntington** [comment]
Hi @paridhiverma - Do I understand correctly that you would like to support an additional group which contains no children? 

If so, that does make sense as a feature, though I'm afraid I'm not sure when we would be able to prioritize it. However, if you were to submit a pull request, I'm certain that we would be happy to merge it. Would also be happy to discuss implementation detail.

**Comment by paridhiverma** [comment]
Hi,
The scenario is where few items do not have any parent, but we do not want to group these “orphan” items under any parent.
Currently, the way it is implemented I have two options :
1. Group them under a generic group
2. Each item gets a dummy parent

What we need in this scenario is to have grouped and single items viewable in the same list. Please see the attachment for your reference.
[cid:image001.png@01D58D94.8DB2F710]

I am a designer and I can work with our dev team and see if can take this up.
Thanks
Paridhi

**Comment by jdhuntington** [comment]
Thanks @paridhiverma - that use case makes sense. If you do start designing and implementing, please reach back out and we can discuss what props/API would make sense.
