### ISSUE TITLE
Multi-select Dropdown title not visible on hover.

### ISSUE THREAD

**Issue by trblandford4** [OfficeDev/office-ui-fabric-react#10983]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)
Chrome, Firefox, Edge, Safari

### Please provide a reproduction of the bug in a codepen:

Visible in UI Fabric component example: https://developer.microsoft.com/en-us/fabric#/controls/web/dropdown

Exported to codepen:  https://codepen.io/trblandford4/pen/qBBPboE

#### Actual behavior:
![fabricDropdownBug](https://user-images.githubusercontent.com/10342337/67799632-f8c5aa00-fa42-11e9-8674-79dcf69413ec.gif)

Rendered HTML shows title applied : 
![Screen Shot 2019-10-29 at 11 51 05 AM](https://user-images.githubusercontent.com/10342337/67799672-0da23d80-fa43-11e9-96ef-88979084c99e.png)

#### Expected behavior:

As the code is written, I'd expect at least hovering the input field would have standard title behavior. 

In my opinion, the entire clickable area should have the title applied as this is how the basic example behaves and is more indicative of the content being selected. (ms-Dropdown-item)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by maxwellred** [comment]
Thank you @trblandford4, I'll be reviewing this shortly!
