### ISSUE TITLE
FocusZone is not resetting focus alignment when a descendant is set focus externally 

### ISSUE THREAD

**Issue by whykushal93** [OfficeDev/office-ui-fabric-react#10985]
### Environment Information

- **Package version(s)**: Latest
- **Browser and OS versions**: Tested on Chrome, but I think will repro on all browsers.

### Please provide a reproduction of the bug in a codepen:

We have menus with` SwatchColorPicker`s inside them and we have seen weird keyboarding inside them recently. We only noticed it now because the bug is aggravated when we use persisted menus but I think it has always existed. 

You can repro the buggy behavior here: https://codepen.io/kushal-yarlagadda/pen/MWWEbgR
To repro:
1. Open the menu. Press down arrow thrice and right arrow once.
2. Close the menu by clicking outside the menu. Open in again and press down arrow twice.
3. Notice that the color cell selected is in second column

#### Actual behavior:
![image](https://user-images.githubusercontent.com/2162858/67811652-819c1000-fa5a-11e9-9115-c9ee1fdca37d.png)

Color cell in second column and second row is focused

#### Expected behavior:
![image](https://user-images.githubusercontent.com/2162858/67811606-66310500-fa5a-11e9-8565-3094d42e37c4.png)

Color cell in first column and second row should be focussed.

Why is this happening ? 
I did some investigation as to why this is happening. When we press the first down arrow in a menu, the `ContextualMenu` tries to focus the first focussable element. This works fine and triggers the `_onFocus` method of the` FocusZone` callback. This callback sets the active element correctly, but fails to adjust the focus alignment to the new element. Note that because the menu is persisted, the `initialElementFocused` is false.

I also think this is a separate bug from https://github.com/OfficeDev/office-ui-fabric-react/issues/10133 which also deals with focusZone but is more concerned with how we loop around.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal, but since we have shipped persisted menus to all Office Online users, I think this buggy behavior could be seen by a lot of users.

Products/sites affected: (if applicable) All Office Online web apps.

**Comment by maxwellred** [comment]
Thank you, @whykushal93 ! I'll take a look and get back to you.

**Comment by dzearing** [comment]
I believe the error is in FocusZone ~  line 367 inside of `_onFocus`. When the FZ receives focus, it tries to reset focus:

```tsx
    // If the new active element is a child of this zone and received focus,
    // update alignment an immediate descendant
    if (newActiveElement && newActiveElement !== this._activeElement) {
      if (isImmediateDescendant || initialElementFocused) {
        this._setFocusAlignment(newActiveElement, initialElementFocused);
      }
```

Specifically this line:
```tsx
        this._setFocusAlignment(newActiveElement, initialElementFocused);
```

The second and third params should be true to reset focus. But in this case, we already have an initial focused element, so alignment doesn't get reset. I believe just always passing true in for 2nd (and 3rd) params here would make more sense and solve this bug.

I tested that it would solve the issue by using dev tools in @whykushal93 codepen to set up a conditional breakpoint  with this condition:

```tsx
(initialElementFocused = true) && false
```

Now if you try and repro, it will work as expected.
