### ISSUE TITLE
Uncaught TypeError: element.getAttribute is not a function from focus.ts

### ISSUE THREAD

**Issue by luhu** [OfficeDev/office-ui-fabric-react#1098]
### Bug Report

- __Package version(s)__: 1.9.0
- __Browser and OS versions__: Any

#### Describe the issue:

function isElementTabbable(element: HTMLElement) of focus.ts will raise error "Uncaught TypeError: element.getAttribute is not a function" when element is document. This is caused by the logic error in focus.ts at line 177 - 179.

#### Actual behavior:

When element is document, function isElementTabbable raise error 'Uncaught TypeError: element.getAttribute is not a function'. 

#### Expected behavior:

When element is document, function isElementTabbable runs correctly.

**Comment by mikewheaton** [comment]
Fixed by #1099
