### ISSUE TITLE
Cursor is overlapping the combobox in browser zoom 

### ISSUE THREAD

**Issue by poonam0025** [OfficeDev/office-ui-fabric-react#10990]
<!--

Repro steps :  
1.Go to link   :  https://developer.microsoft.com/en-us/fabric#/controls/web/combobox.  
2. Zoom the browser upto 200% and then minimize browser screen.

3. Click on combobox to see all available options. Now start typing in combobox. typing cursor
is overlapping with combo box option list.

![image](https://user-images.githubusercontent.com/37584638/67844207-5c270900-fb23-11e9-814c-b2033df3f129.png)

#### **Actual behavior:**

Cursor is overlapping the combobox

##**## Expected behavior:**

Cursor should not overlap the combobox options

**Comment by poonam0025** [comment]
Hi Maxwell ,  Issue is repro in Edge browser . Below are steps for repro in code pen .
1. Go to link  `https://codepen.io/poonam0025/pen/MWWOKaO?&editable=true`  .  Zoom browser in 200% . 
2. Now expand combo box  and also focus on to combo box for typing.   Combo box text cursor is overlapping with combo box options.

![image](https://user-images.githubusercontent.com/37584638/67917716-ecb32700-fbbf-11e9-9806-8cd1bbab8f2b.png)


3. Issue 2 : In Google chrome .Cursor is not showing on focus   and when user is typing  text  in combo box, typed text is not visible because of combo box option are  hiding  the typed text.

![image](https://user-images.githubusercontent.com/37584638/67917697-d6a56680-fbbf-11e9-8efa-cab90274e975.png)

**Comment by maxwellred** [comment]
Thank you for the codepen and repro instructions @poonam0025. I'll look into this issue and get back to you.

**Comment by maxwellred** [comment]
Hi @poonam0025 , I've spoken with the codeowner and he suggests passing the "directionalHintFixed: true" value through the Combobox's "calloutProps" props to aid with Issue 2
`<Combobox ... calloutProps={{directionalHintFixed: true}} ... >`. As for the first issue regarding the cursor bleed through, I suggest raising the issue with the Edge team.
