### ISSUE TITLE
The Skype logo got replaced with the Skype for Business logo

### ISSUE THREAD

**Issue by gabosom** [OfficeDev/office-ui-fabric-react#10995]
### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**: 

### Describe the issue:

The Skype logo was replaced with the Skype for Business logo. We need this change reverted to what it was before. 

#### Actual behavior:

Skype Logo 

#### Expected behavior:

Skype for business logo

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No- i don't have the right assets

Requested priority: High

Products/sites affected: (if applicable) - outlook.com and other sites who will be rollign out Skype chat in consumer.

**Comment by maxwellred** [comment]
Hi @gabosom thanks for filing an issue and I'll look into it soon!

**Comment by maxwellred** [comment]
Hello again @gabosom. I have spoken with an authority on the icon matter and have been told that the monochromatic monoline OR full color version of the Skype logo both represent Skype for consumer now
