### ISSUE TITLE
dropdown callout with double scroll bar

### ISSUE THREAD

**Issue by MSYuanMei** [OfficeDev/office-ui-fabric-react#10997]
### Environment Information

- **Package version(s)**: v7.56.1
- **Browser and OS versions**:  win10
https://codepen.io/ymei/pen/qBBVdWd?&editable=true
I want to have a maxHeight for the dropdown callout,
when i set a maxHeight(heigher than the window) for the dropdownItemsWrapper, it shows a double scrollbar. 

#### Actual behavior:
it shows a double scrollbar. 
![image](https://user-images.githubusercontent.com/42685233/67908958-a667b480-fb3a-11e9-8a8b-7d95e6a29d97.png)
I could not figure out a walk around to make it work

#### Expected behavior:
show just one scroll bar

**Comment by maxwellred** [comment]
Hi @MSYuanMei thank you for filing the issue! I'll take a look at this soon and get back to you.

**Comment by maxwellred** [comment]
Hi again, I simply removed the overflow-x/y (which generate scrollbars). That specific css rule, `dropdownItemsWrapper `, doesn't have those overflows originally so what happened is you added an extra scrollbar by doing the override.

**Comment by MSYuanMei** [comment]
I add that is because I want to set a maxHeight of the dropdown callout(if too long then show the scrollbar), is there any other way to do it?
Because I cannot overwrite callout height/overflow as it is in "style" set by js

**Comment by maxwellred** [comment]
@MSYuanMei Using your example and setting only the maxHeight rule of the container to something very small, 100px, you can see that the component will add the scrollbar by itself in order to scroll the rest of the content.

<img width="241" alt="maxHeight_scrollbars" src="https://user-images.githubusercontent.com/13246181/67981379-bd131780-fbdd-11e9-8752-5074c7b50010.PNG">

**Comment by maxwellred** [comment]
@MSYuanMei Using your example and setting only the maxHeight rule, the component will automatically implement scrollbars whether the component's maxHeight and content are taller than the viewport or the maxHeight has been set smaller than the height of the combined content inside.

#### maxHeight smaller than content height
<img width="241" alt="maxHeight_scrollbars" src="https://user-images.githubusercontent.com/13246181/67981827-b1742080-fbde-11e9-964a-fecf485cbfb6.PNG">

#### maxHeight and content height larger than viewport
<img width="270" alt="maxHeight_larger" src="https://user-images.githubusercontent.com/13246181/67981852-bdf87900-fbde-11e9-9072-cd88dfb9989a.PNG">

**Comment by MSYuanMei** [comment]
![image](https://user-images.githubusercontent.com/42685233/67994081-c3ff5180-fc00-11e9-9df3-ef346ce013c2.png)
https://codepen.io/ymei/pen/qBBVdWd
It shows blank with the changes. looks like there is no easy fix for it

**Comment by maxwellred** [comment]
I'm sorry for the delay @MSYuanMei. I'll have to get back to you on this custom styling.

**Comment by MSYuanMei** [comment]
@maxwellred do we have any update on this one? : )

**Comment by maxwellred** [comment]
Hi @MSYuanMei do you have an example of what an end result would like

**Comment by gridbox** [comment]
> ![image](https://user-images.githubusercontent.com/42685233/67994081-c3ff5180-fc00-11e9-9df3-ef346ce013c2.png)
> https://codepen.io/ymei/pen/qBBVdWd
> It shows blank with the changes. looks like there is no easy fix for it

This fix worked for me.  We were wanting to constrain the dropdown callout to a reasonable height since our dropdown has many options.  

@MSYuanMei I believe the reason your dropdown showed blank is that the height was set to `1600px` in your example.  Setting it to something smaller works.
