### ISSUE TITLE
Dropdowns/Combobox: Cannot scroll via touch when housed in Modal

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#10993]
Due to the [disableBodyScroll](https://github.com/OfficeDev/office-ui-fabric-react/blob/2894062b1d0515055c29061dfc6f586f918ca41c/packages/office-ui-fabric-react/src/components/Overlay/Overlay.base.tsx#L9) called in Overlay, any component housed in a modal/Dialog will have trouble scrolling via touch.

Check out this example. Wheel scroll works, but change to mobile device in inspector and scroll won't work.

Click on "fix scroll", which calls [enableBodyScroll](https://github.com/OfficeDev/office-ui-fabric-react/blob/09d5abf9a89b1f2ae31de5427e24279537eb9a4c/packages/utilities/src/scroll.ts#L112) and you'll be able to scroll again. 

not 100% sure how we want to resolve this, as i'm sure the functionality was well intentioned.

https://codepen.io/micahgodbolt/pen/NWWwKKM?editors=0010

**Comment by joschect** [comment]
@micahgodbolt this is the same problem as #8855 Both Katherine and I spent a fair amount of time investigating it and as far as we could tell there is no way to fix this without reverting the change that introduced it in the first place. At this point I think we should consider rolling back the change and allowing background scroll on ios. That seems to be the lesser of two evils in this case.

**Comment by maxwellred** [comment]
@micahgodbolt I've been coordinating with @joschect and @aneeshack4 on this #10982 issue and I feel it suffers from the same issue since Panel does not have touch scrolling either. I've noticed that when I change data-is-scrollable to false in the div surrounding the Panel's content (Panel.base.tsx), touch scrolling works. 

`<div ref={this._allowScrollOnPanel} className={_classNames.scrollableContent} data-is-scrollable={true}>
`

**Comment by micahgodbolt** [comment]
@joschect i am pretty certain this is a different issue. This one is related to the `disableBodyScroll` function that is called when Overlays are created.  `disableBodyScroll` adds some CSS to the body to hide all overflow (that's fine) but it also disables touchmove event (not good here). 

I'd be curious what effect removing the touchmove restriction would have, and if there was a less intrusive way to solve the scroll problem

**Comment by micahgodbolt** [comment]
ok. updated #8855 with my findings. I can close this one down.
