### ISSUE TITLE
[Accessibility][Functional] Incorrect label appears when no contacts available to add in 'People picker' combo box.

### ISSUE THREAD

**Issue by joschect** [OfficeDev/office-ui-fabric-react#11023]
Breakout of #6259

**Comment by joschect** [comment]
Only an issue with the "controlled picker example". The problem is that the "click to add a person" text doesn't flip once all options have been added.

**Comment by micahgodbolt** [comment]
Example is more generic now stating "suggested people", of which "no results found" is a valid response.

![image](https://user-images.githubusercontent.com/1434956/70751192-be5b5800-1ce4-11ea-8bfc-a1e3b43aff02.png)

**Comment by joschect** [comment]
Closed per @micahgodbolt s comment
