### ISSUE TITLE
Screen reader is not reading the “Expanded state” for “New page” menu item.

### ISSUE THREAD

**Issue by sagar17sep** [OfficeDev/office-ui-fabric-react#11029]
### Environment Information

- **Package version(s)**: 7.24.0
- **OS version:** 1903 (OS Build: 18326.295)
- **Browser:** Edge(Microsoft Edge 44.18362.267.0)

**User Experience:** 
If the Expanded  state is not defined for “New page” menu item than screen reader users will not be able to find out the state property of controls and will face difficulties while interacting with it.

**Repro steps:**
1. Open URL " https://make.test.powerapps.com " and login with valid credentials.
2. PowerApps Homepage will appear.
3. Navigate to template present at the bottom, then navigate to any already created portal app.
4. Navigate to context menu of portal app and select it. Select Edit (preview) from the context menu, portal will be opened on the screen.
5. Navigate to 'New Page' dropdown and expand it.
6. Navigate to all menu items appear under 'New page' dropdown.
7. Verify “Expanded state” is defined for “New Page” menu item or not.

**Actual behavior:**
Screen reader is not reading the “Expanded state” for “New page” menu item.

**Expected behavior:**
Screen reader should read the “Expanded state” for “New page” menu item.

**Please find the attachment**
[Downloads.zip](https://github.com/OfficeDev/office-ui-fabric-react/files/3792604/Downloads.zip)

Please reach out to Portal FX team for more details.

**Comment by maxwellred** [comment]
Hi @sagar17sep , This issue involves a product, PowerApps, our team neither builds nor maintains. For issues related to our product you are welcome to submit an official issue [here](https://github.com/OfficeDev/office-ui-fabric-react/issues/new/choose) and supplying a codepen demo of the respective control found [here](https://developer.microsoft.com/en-us/fabric#/controls/web) accompanied with the necessary repro steps. This issue will be labelled as "Resolution: External" and we would appreciate your help by closing this issue yourself. Thank you very much for your interest and support in the Office UI Fabric React project!
