### ISSUE TITLE
[ComboBox] Hidden options are visible using Up/Down keys for selection

### ISSUE THREAD

**Issue by neeraj-khanna** [OfficeDev/office-ui-fabric-react#11032]
### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**: All browsers

### Please provide a reproduction of the bug in a codepen:
<https://codepen.io/neeraj-khanna/pen/WNNXxXv>

#### Actual behavior:
Set focus on ComboBox and use Down key to change values. You will find 10 options (Option A to Option J).

Now expand ComboBox using mouse and you will see only 6 options (Option A, Option B, Option G, Option H, Option I, Option J) as rest 4 are hidden.

#### Expected behavior:
Hidden options should not be visible even when selection is made using Up/Down keys.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low)
High

Products/sites affected: (if applicable)

**Comment by maxwellred** [comment]
Hi @neeraj-khanna thank you for the codepen and I see the issue. I'll take a look into this and get back to you.
