### ISSUE TITLE
OverflowSet inside of CommandBar uses aria-orientation, even though role is set to 'presentation'

### ISSUE THREAD

**Issue by KyleBastien** [OfficeDev/office-ui-fabric-react#11039]
### Environment Information

- **Package version(s)**: office-ui-fabric-react v7.42.0
- **Browser and OS versions**: Microsoft Edge v79.0.305.0

### Describe the issue:

CommandBar currently creates an OverflowSet and passes in the role of "presentation", you can see this [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.base.tsx#L108).

OverflowSet though will set a aria-orientation tag of either vertical or horizontal, you can see this [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/OverflowSet/OverflowSet.base.tsx#L59).

Using aria-orientation with an element who's role is "presentation" is incorrect, as per this W3 document: https://www.w3.org/TR/wai-aria-1.1/#aria-orientation

aria-orientation should only be used with the following roles:

- scrollbar
- select
- separator
- slider
- tablist
- toolbar
- combobox
- listbox
- menu
- menubar
- radiogroup
- tree
- treegrid

This error get's flagged by axe-core, as breaking the aria-allowed-attr rule (https://dequeuniversity.com/rules/axe/3.3/aria-allowed-attr).

#### Actual behavior:

aria-orientation is used with role="presentation".

#### Expected behavior:

role should probably be the default role for an OverflowSet, i.e. "menubar".

### Documentation describing expected behavior

https://www.w3.org/TR/wai-aria-1.1/#aria-orientation

**Comment by maxwellred** [comment]
Thank you @KyleBastien! I'll look into this issue.

**Comment by dssharma** [comment]
What is update on this issue? When is the fix expected?

**Comment by maxwellred** [comment]
Hi @dssharma , sorry for the inconvenience, we are currently investigating an issue with the build of the repo involving this PR and will have it in as fast as we can.
