### ISSUE TITLE
Fabric 7: Button hidden:true does not hide button in IE11

### ISSUE THREAD

**Issue by ThreadPitt** [OfficeDev/office-ui-fabric-react#11034]
Please see: #10419

It still doesn't work with the latest Fabric 7 version, and no I can't provide a CodePen- CodePen does not work with IE11 - it would work with Chrome but that is again the point of this issue!

I am pretty sure this is a real bug, it all works fine in Chrome but NOT in IE11 (exactly the same code).

Did anyone ever look into this or did you just close #10419???

**Comment by ThreadPitt** [comment]
Here's the pen: https://codepen.io/ThreadPitt/pen/oNNEwLB

What I am seeing, that this also does NOT work in Chrome in the pen.

On the other hand, it does render the html with a hidden attribute:

<button type="button" role="menuitem" **hidden=""** class="ms-Button ms-Button--commandBar ms-Button--hasMenu ms-CommandBarItem-link root-57" data-is-focusable="true" aria-expanded="false" aria-haspopup="true" tabindex="0"><span class="ms-Button-flexContainer flexContainer-58" data-automationid="splitbuttonprimary"><i data-icon-name="Add" role="presentation" aria-hidden="true" class="ms-Icon root-37 css-65 ms-Button-icon icon-60"></i><span class="ms-Button-textContainer textContainer-59"><span class="ms-Button-label label-61" id="id__2">New</span></span><i data-icon-name="ChevronDown" role="presentation" aria-hidden="true" class="ms-Icon root-37 css-65 ms-Button-menuIcon menuIcon-62"></i></span></button>

Maybe it is a CSS issue?
Maybe there was a hidden property in Fabric 6?
When I look a the docs now: https://developer.microsoft.com/en-us/fabric#/controls/web/contextualmenu#IContextualMenuItem

I only see a hidden prop on IContextualMenu but NOT on IContextualMenuItem.

So something is a bit wrong here. **In the end, we just want to hide a menu button, i.e. a IContextualMenuItem. How do we do this properly in Fabric 7?**

**Comment by micahgodbolt** [comment]
items with hidden attribute that also have a display property will use the display property value (per spec). 

>Note: Changing the value of the CSS display property on an element with the hidden attribute overrides the behavior. For instance, elements styled display: flex will be displayed despite the hidden attribute's presence.

**Comment by micahgodbolt** [comment]
hidden is not actually part of the current contextualmenu/commandbaritem interface. it gets passed through because we pass everything through, but we don't really have a commitment to support it.

What are you trying to use hidden for? Would adding 'display: none' to the hidden items do the same? or can you simply filter your own items array before passing it in?

I'm not a fan of the current code fix as we're adding functionality for a prop we don't officially support.

**Comment by maxwellred** [comment]
@ThreadPitt I believe the best course of action would be to, as Micah says above, filter items out of the items array before passing it into CommandBar. In any case, please have a look at the other questions he asks and please let us know, thanks!

**Comment by ThreadPitt** [comment]
Ok, thanks guys for the help! We already implemented the filtering as a work-around.

Basically, we need some sort of functionality to show/hide command bar button based on conditions, in our case user roles (admin sees all buttons, a regular user does not see all buttons etc.). In the long run, a hidden prop seems to make sense, especially since a disabled prop is already there (and working fine!).

Cheers!

**Comment by micahgodbolt** [comment]
them HTML hidden attribute doesn't remove the element from the DOM, it only makes it not visible. This wouldn't be the best usecase for user roles necessarily as you might be exposing buttons and information to users that shouldn't be seeing that content. 

Filtering your data and only displaying the content that is appropriate for that user is going to always be your best bet
