### ISSUE TITLE
MarqueeSelection: doesn't support horizontal scrolling

### ISSUE THREAD

**Issue by alanlong9278** [OfficeDev/office-ui-fabric-react#11047]
### Environment Information

- **Package version(s)**:  `7.37.1`
- **Browser and OS versions**: Browser

#### Actual behavior:

When I try to select a bunch of nodes and they are off the screen, the selection doesn't 'scroll' to the right or left. It does allow scroll down, but not left or right.

#### Expected behavior:

It needs support not only scrolling `up & down`, but also `left & right`

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable)

**Comment by maxwellred** [comment]
Thank you @alanlong9278 I'll take a look!
