### ISSUE TITLE
Combobox: multi-select option cannot be selected by clicking the blank space next to the option

### ISSUE THREAD

**Issue by vasvi** [OfficeDev/office-ui-fabric-react#11041]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:
In multiselect combobox, the option is only selected if the cursor is directly over/clicks the text or the checkbox. 

#### Expected behavior:
If the option is highlighted, the entire highlighted field (including blank space) should also be clickable and allow the user to select the item.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No
Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by maxwellred** [comment]
Thank you @vasvi! I'll take a look at this and let you know.
