### ISSUE TITLE
DocumentCardActivity - descenders of characters are being cut off by 1 pixel

### ISSUE THREAD

**Issue by Rafaelki** [OfficeDev/office-ui-fabric-react#11043]
### Environment Information

- **Package version(s)**: current
- **Browser and OS versions**: All browsers

### Please provide a reproduction of the bug in a codepen:
The issue is present even in the documentation of DocumentCard:
https://developer.microsoft.com/en-us/fabric#/controls/web/documentcard 

#### Actual behavior:
One pixel of the characters g, j, q, p and y is missing both in the activity description and in the persona name.

![image](https://user-images.githubusercontent.com/24438807/67991091-f4aaaf80-fc2f-11e9-9d4a-67ae95d45b4e.png)

#### Expected behavior:
The whole character to be displayed. The heigh of the elements should be 16px instead of 15px.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

**Comment by maxwellred** [comment]
Thanks @Rafaelki ! I'm not seeing this issue on my devices (Dell monitors, Mac Book Pro, Surface Pro 3) or in different browsers. I've actually seen screens of varying resolutions and brands cause this type of text clipping or when zoomed in or out of the page.

![Screen Shot 2019-10-31 at 4 05 52 PM](https://user-images.githubusercontent.com/13246181/67992118-cf4e7f00-fbf8-11e9-8e6a-94bf2088a698.png)

**Comment by Rafaelki** [comment]
Thanks @maxwellred for your quick answer. I checked in different browsers and it was happening in all of them but today I have checked on my colleague's computer and there is no bug there. So definitely it is something in my machine. 
Sorry to waste your time and thanks for your good work :)
