### ISSUE TITLE
COLOR PICKER - Screen reader is reading the table information when focus is on edit field(Hex,red,blue,green,alpha)s but visually not appearing as table present under “text”pane.

### ISSUE THREAD

**Issue by sagaranandani17** [OfficeDev/office-ui-fabric-react#11059]
### Environment Information

- **Package version(s)**: 7.24.0
- **OS version:** 1903 (OS Build: 18326.295)
- **Browser:** Edge(Microsoft Edge 44.18362.267.0)
- **Screen Reader:** Narrator.

**User Experience:** 
If the screen reader is reading the table information while navigating on “Hex ,Red ,Green, Blue, Alpha” edit fields then screen reader dependent users might face difficulties to understand the data present  under “Text” pane.

**Actual behavior:**
Screen reader is reading the “Table” information while navigating in scan mode.

**Expected behavior:**
Screen reader shouldn’t read the table information while navigating on “Hex ,Red ,Green, Blue, Alpha” edit fields present under text pane. If table is defined for the design purpose then role="Presentation" should be defined.

![image](https://user-images.githubusercontent.com/57341535/68118521-3a17f700-ff26-11e9-9217-d71547397400.png)

**Comment by ecraig12345** [comment]
The area with the text fields shouldn't be a table, but changing it at this point runs the risk of breaking consumers' styling or tests. I actually just fixed this two days ago in #10882 by setting a role on the table.
