### ISSUE TITLE
TagPicker: Suggestion box footer (resultsFooter) in Picker (BasePicker) does not show after typing

### ISSUE THREAD

**Issue by hecerinc** [OfficeDev/office-ui-fabric-react#11054]
### Environment Information

- **Package version(s)**: 7.56.3
- **Browser and OS versions**: Firefox Nighty 71.0a1 on Windows 10

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/domicoh/pen/VwwyPWQ?editors=0011

#### Actual behavior:

Suggestion box footer appears on first mount + focus and then disappears as soon as I type something into the picker input and never comes back until component is unmounted/remounted.

#### Expected behavior:

Results footer should remain at all times when Suggestion box is open while typing, selecting, (at least when `isResultsFooterVisible` is `true`)

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: (Blocking, High, Normal, Low) Normal

**Comment by maxwellred** [comment]
Hi @hecerinc I've tried this codepen on the latest Nightly Build (72.0a1) and regular Firefox (70.0.1) on Win10 and I don't appear to be having this issue. Perhaps this bug was resolved in the latest nightly release?

![TagPicker](https://user-images.githubusercontent.com/13246181/68147662-6401f700-feef-11e9-8110-3bb4a284635e.gif)

**Comment by hecerinc** [comment]
Hi @maxwellred thanks for getting back. I actually can't see the footer in your example. Please see this image where the footer reads "**Hello world**"

![image](https://user-images.githubusercontent.com/7988472/68172105-26bb5a80-ff2b-11e9-8396-7a0495067abb.png)

**Comment by maxwellred** [comment]
@hecerinc Sorry about that! I've tested your supplied code in a locally spun up version of the repo (gif below) and don't see any problems making me think this is a bug with Codepen.

#### GIF Example
![TagPicker](https://user-images.githubusercontent.com/13246181/68236414-fb338100-ffb9-11e9-8037-bc7449c55b87.gif)
