### ISSUE TITLE
Why are the details for the Nav element not aligned on the UI Fabric web page?

### ISSUE THREAD

**Issue by rwinj** [OfficeDev/office-ui-fabric-react#11068]
I've been looking at Nav element details on the UI Fabric website (https://developer.microsoft.com/en-us/fabric#/controls/web/nav). The Nav element used on the left side of the UI Fabric site itself looks and behaves differently than the Usage example shown in the Nav article. (A blue bar and bold text used to show the current item in view in the Usage example. Also the expando chevrons are different sizes and behave differently.) See attached image.

Does the UI Fabric use it's own Fabric elements or something else going on? One of the things I'm trying to figure out is what's the correct way to indicate the current tab - this is not clear from the Figma file either. Is there a better place to direct questions?
![NavDetail-issues](https://user-images.githubusercontent.com/27970582/68163770-206bb500-ff10-11e9-80eb-291542fad69f.PNG)

**Comment by JasonGore** [comment]
The left nav on the UI Fabric site actually a custom implementationg using `CollapsibleSection`. We've previously identified need for a specific Sidebar/LeftNav control and have created [an issue](https://github.com/OfficeDev/office-ui-fabric-react/issues/6221) for it.
