### ISSUE TITLE
details list row columns are not resized when a details header column is resized for grouped details list

### ISSUE THREAD

**Issue by tharshada** [OfficeDev/office-ui-fabric-react#11062]
### Environment Information

- **Package version(s)**: **7.57.0** (- 7.53.0), 6.x 

https://fabricweb.z5.web.core.windows.net/oufr/7.53.0/#/examples/detailslist/customgroupheaders
and latest: https://fabricweb.z5.web.core.windows.net/oufr/7.57.0/#/examples/detailslist/customgroupheaders

https://fabricweb.z5.web.core.windows.net/oufr/6.209.0/#/examples/detailslist/customgroupheaders
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:
https://fabricweb.z5.web.core.windows.net/oufr/7.57.0/#/examples/detailslist/customgroupheaders
![image](https://user-images.githubusercontent.com/41147089/68123174-486c1000-ff32-11e9-8aed-e59f37d35faf.png)

https://fabricweb.z5.web.core.windows.net/oufr/6.209.0/#/examples/detailslist/customgroupheaders
![image](https://user-images.githubusercontent.com/41147089/68123356-b9132c80-ff32-11e9-9b74-8f3388aac568.png)

#### Expected behavior:
https://fabricweb.z5.web.core.windows.net/oufr/7.52.0/#/examples/detailslist/customgroupheaders
![image](https://user-images.githubusercontent.com/41147089/68122986-bc59e880-ff31-11e9-8139-0a68e01f444d.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? No
Requested priority: **Blocking**

Products/sites affected: Yes

**Comment by KevinTCoughlin** [comment]
This regression is most likely related to https://github.com/OfficeDev/office-ui-fabric-react/pull/10845 & https://github.com/OfficeDev/office-ui-fabric-react/pull/10819

It looks like we missed a scenario.

cc: @ThomasMichon

**Comment by ThomasMichon** [comment]
I am taking a look at this. It's likely that the change to the new `version` prop isn't propagating through to all the rows, leaving some stale.

**Comment by KevinTCoughlin** [comment]
Thanks for reporting @tharshada!
