### ISSUE TITLE
Request allow customized data field in ISelectableOption 

### ISSUE THREAD

**Issue by dan-lai** [OfficeDev/office-ui-fabric-react#11071]
#### Describe the feature that you would like added

Enable ISelectableOption to have customized data field. For example, it allows me to add data-test-hook into the element.

#### What component or utility would this be added to

It is the ISelectableOption in FabricDropdown component.

#### Have you discussed this feature with our team, and if so, who

Not yet.

#### Additional context/screenshots

![Capture](https://user-images.githubusercontent.com/47544352/68168676-6fb8e200-ff1e-11e9-83f9-82e4a4c586e6.PNG)

**Comment by JasonGore** [comment]
Unfortunately there [isn't really a way to specify patterns](https://github.com/microsoft/TypeScript/issues/6579) as part of an interface in TypeScript. TypeScript inherently supports `data-` attributes for components through compiler rules, but there is no way to explicitly specify them in types such as `ISelectableOption`. 

You could get around this by typing, but there is no guarantee that components will spread all attributes of `ISelectableOption`, and in fact, components such as `ComboBox` do not. That means arbitrary properties in `ISelectableOption` won't be forwarded to the element.

Can you use the `ISelectableDataOption` `data` attribute to store an arbitrary properties, such as `data-test-hook`? They don't appear as attributes in the HTML element, but I'm wondering if it's another option for your use case.
