### ISSUE TITLE
PrimaryIconButton

### ISSUE THREAD

**Issue by rhalaly** [OfficeDev/office-ui-fabric-react#11076]
## Component details

Not sure if this is a new component or a feature. An icon button with the primary color.

https://developer.microsoft.com/en-us/fabric#/controls/web/button
### Description

But like the `DefaultButton` and `PrimaryButton`, just a `PrimaryIconButton` which should be an `IconButton` but with the `PrimaryButton` style.

### Which product teams/scenarios need this control

Internal Microsoft products.

### Design assets

Just as described, an `IconButton` but with the `PrimaryButton` style.

### Component ownership

No

### Imports/Dependencies

Same as `IconButton`

### Exports/Component breakdown

Same as `IconButton`

## Component code
Same as `IconButton`
### Example code
Same as `IconButton`

### Props

Same as `IconButton`

### Todos

- [ ] Add Todos

### Steps

- [ ] Themable
- [ ] Unit tests
- [ ] Visual tests
- [ ] Documentation and examples
- [ ] Keyboard Accessible
- [ ] High Constrast Support
- [ ] RTL Support
- [ ] Design Review
- [ ] API review
- [ ] Public Preview
- [ ] Ready for Publishing

**Comment by kenotron** [comment]
We're probably not going to add more variants of a button at this time. I believe you can achieve what you want by replacing the component from "IconButton" to "PrimaryButton". If you prefer having a nice "PrimaryIconButton" - you can create a wrapper component that passes on the `iconProps` for the consumers.

https://codepen.io/kenotron/pen/VwwXKNR

```js
<PrimaryButton iconProps={emojiIcon} title="Emoji" ariaLabel="Emoji" styles={{root: {width: 32, minWidth: 32}}}/>
```
