### ISSUE TITLE
Office UI Fabric Developer Website Down

### ISSUE THREAD

**Issue by ChadiRachid** [OfficeDev/office-ui-fabric-react#11086]
### Environment Information

- **Package version(s)**: N/A
- **Browser and OS versions**: Edge, Chrome, Internet Explorer Firefox

#### Actual behavior:

The website for fabric UI https://developer.microsoft.com/en-us/fabric is not loading.

It appears the following linked scripts are not loading:
https://fabricweb.azureedge.net/fabric-website/v7_20191105.2/fabric-sitev5.min.js
https://fabricweb.azureedge.net/fabric-website/v7_20191105.2/fabric-sitev5.js

The returned error is

```xml
<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:bd8f84ba-c01e-00ed-1d21-94b340000000 Time:2019-11-05T21:41:00.1766453Z
</Message>
</Error>
```
#### Expected behavior:

The website for the fabric UI should load

### Priorities and help requested:

Are you willing to submit a PR to fix?NO

Requested priority: Blocking 

Products/sites affected: Fabric UI React, Core, Native

**Comment by JasonGore** [comment]
Looks like this was caused by the most recent publish of the website almost 2 hours ago.

**Comment by JasonGore** [comment]
We've rolled back so it should be working again now.
