### ISSUE TITLE
FocusZone should not have outline:none by default

### ISSUE THREAD

**Issue by mary92** [OfficeDev/office-ui-fabric-react#11093]
### Environment Information

- **Package version(s)**: not relevant
- **Browser and OS versions**: not relevant

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/marijacivovic/pen/JjjOLNO?editors=1111

#### Actual behavior:

The FocusZone element never has an outline when focused. This was introduced recently in PR https://github.com/OfficeDev/office-ui-fabric-react/pull/8768 

#### Expected behavior:

FocusZone should have an outline when focused, as any focusable element. 
It's very counter intuitive to have this as default.
I had some UX that had the FocusZone in focus, and then focus on inner elements when clicking Enter or space.
### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
Yes
Requested priority: (Blocking, High, Normal, Low)
Normal
Products/sites affected: (if applicable)
Microsoft Office

**Comment by JasonGore** [comment]
`FocusZone` itself is not a focusable element, it is an invisible DOM element that manages focus of other focusable items. A `FocusZone` must contain focusable elements, and those elements would get focus and have outlines. A `FocusZone` with no focusable elements is an indeterminate scenario. I don't think there is a reason for `FocusZone` itself to ever have focus, and thereofre ever have an outline.

**Comment by JasonGore** [comment]
I should have confirmed that if you want it to have a border, you certainly can. It's just not default behavior for the reasons I listed.

**Comment by mary92** [comment]
Thanks for clarifying the reasoning behind this update. 
We used FocusZone the following way - have the focus zone element receive focus and then have it's child elements receive focus with clicking enter/space, like a drill in experience. So if you can suggest another component that will enable us to have this or just have the outline:none setting configurable within the FocusZone?

**Comment by JasonGore** [comment]
It sounds like you want the capturing element to have focus itself, is that correct? Does it have an action associated with it when you hit space or enter? If it has no action associated with it, I think it may be confusing for users as focus is generally reserved for interactive elements.

Regardless, since FocusZone itself is not focusable, then you would need to have a div or other containing element that can receive focus and then pass it to FocusZone.

**Comment by mary92** [comment]
Hi Jason,
Yes, I need an element to take focus and then pass it to its children on hitting enter/space. FocusZone was handy for this, but I see it's not intended to be used like this.
Thanks for explaining!
