### ISSUE TITLE
File type icons don't support all sizes suggested by design guidelines

### ISSUE THREAD

**Issue by hjonasson** [OfficeDev/office-ui-fabric-react#11108]
#### Describe the feature that you would like added

File type icons have design guidelines [here](https://developer.microsoft.com/en-us/fabric#/styles/web/file-type-icons). In the paragraph _Format and sizes_ it says that mobile experiences should have 24pxX24px available. Looking at the available formats in `getFileTypeIconProps.ts` however [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/786714fc9dedc6a70ec10ebb61d1a7ecf3a6d696/packages/file-type-icons/src/getFileTypeIconProps.ts#L14) this size is not available. I want to ask Fabric to support this size as well as the other ones on the type.

#### What component or utility would this be added to

the `FileTypeIconSize` type in `getFileTypeIconProps.ts` file

#### Have you discussed this feature with our team, and if so, who

Mark Polak of Microsoft Norway.

**Comment by JasonGore** [comment]
I'm not sure whether the doc or the code is incorrect but we will clarify.

**Comment by hjonasson** [comment]
Thanks a lot for swift reactions! I just verified that the icon is on the CDN and it is all there.

**Comment by hjonasson** [comment]
Is there a way I can initialise and use the new icons without bumping Fabric?

And does [this](https://github.com/OfficeDev/office-ui-fabric-react/blob/b41b1561bb47731728a0e0c763c2011e8541157f/packages/file-type-icons/src/initializeFileTypeIcons.tsx#L9) not need to be changed as well to be able to initialise the new icon sizes?

**Comment by maxwellred** [comment]
Hi @hjonasson you'll have to bump the Fabric version to receive the updates and your second point was addressed in #11166 so you are all set!
