### ISSUE TITLE
ContextualMenu for other components

### ISSUE THREAD

**Issue by rhalaly** [OfficeDev/office-ui-fabric-react#11113]
#### Describe the feature that you would like added

Add an ability to use `ContextualMenu`s outside a buttons, like in `Link`s.

#### What component or utility would this be added to

`Link`, `TextField` (for "mention" tagging)

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

Honestly I would expect to get a standalone `ContextualMenu` component even for overriding Right Click event

**Comment by JasonGore** [comment]
There is a standalone `ContextualMenu` component, it's just not directly used in any of the [ContextualMenu examples](https://developer.microsoft.com/en-us/fabric#/controls/web/contextualmenu). Here is a [CodePen](https://codepen.io/jasongore/pen/Jjjvwgp) showing it applied to a link.

I think the example page could do with at least one example using `ContextualMenu` directly so I'll leave this issue open.

**Comment by rhalaly** [comment]
Thank you! That's what I'm looking for!

**Comment by rhalaly** [comment]
Hi, the code is not working when the `ref` element is a component. Like in this example: https://codepen.io/hraz/pen/ExxeVrr

**Comment by JasonGore** [comment]
[Link appears to overwrite `ref` with its own internal value](https://github.com/OfficeDev/office-ui-fabric-react/blob/fc1987c135c486f32262042337515a9c21443d37/packages/office-ui-fabric-react/src/components/Link/Link.base.tsx#L35). I think this could be an issue with Link that should be reported separately. Thanks!
