### ISSUE TITLE
When wrap and childrenGap simultaneously specified for Stack a horizontal scroll bar is shown

### ISSUE THREAD

**Issue by gsbelarus** [OfficeDev/office-ui-fabric-react#11117]
office-ui-fabric-react: 7.58.0
browser: Firefox 70.0.1
os: windows 10

If `wrap` and `childrenGap` properties simultaneously specified for `Stack` component horizontal scroll bar is shown even if there is enough space to display all items:
```ts
<Stack
  horizontal
  wrap
  tokens={{ childrenGap: '4px' }}
>
```
![image](https://user-images.githubusercontent.com/5175764/68411267-33de8080-019b-11ea-8792-eff680c49d25.png)

If we omit either `childrenGap` or `wrap` then `Stack` will be drawn as expected, i.e. without horizontal scroll bar.
```ts
<Stack
  horizontal
  wrap
>
```
![image](https://user-images.githubusercontent.com/5175764/68411408-7bfda300-019b-11ea-8dfc-4534a29a67d5.png)
```ts
<Stack
  horizontal
  tokens={{ childrenGap: '4px' }}
>
```
![image](https://user-images.githubusercontent.com/5175764/68411595-c4b55c00-019b-11ea-952f-6cff7d953bd2.png)

**Comment by khmakoto** [comment]
Hi @gsbelarus, I can't seem to be able to reproduce this. [Here](https://codepen.io/khmakoto/pen/RwwymbE) is a simple codepen I've made where I use `horizontal`, `wrap` and `childrenGap` without this behavior triggering it.

Could you fork and modify it so that it reproduces your case? That way we might be able to fix whatever is not working as expected here. Thanks!

**Comment by gsbelarus** [comment]
Strange, but I can't repeat it with CodePen. I have looked through CSS on the page. Horizontal scroll bar appears because of line `width: calc(100% + 4px);` in style `.ms-Stack-inner css-94`. Seems that this setting somehow interacts with overlying html elements and their styles. 

As for now, I will subdue scroll bar specifying:
```
styles={{
  root: { overflow: 'hidden' }
}}
```
for the `Stack` component.

I will close the issue until I have 100% reproducible example.
