### ISSUE TITLE
Panel Fabric component always overlays the full browser window, cannot set parent

### ISSUE THREAD

**Issue by ashbadami** [OfficeDev/office-ui-fabric-react#11115]
#### Describe the feature that you would like added
Should be able to set the parent component for Fabric Panel. Eg. Top navigation bar. 
So that the side panel doesn't overlap/cover certain parts of the page and its always accessible.

#### What component or utility would this be added to
Panel

#### Have you discussed this feature with our team, and if so, who
No

#### Additional context/screenshots
Current Behavior - it always overlaps the full screen.
![image](https://user-images.githubusercontent.com/17021104/68396923-3606f780-0127-11ea-9527-d11b4e0e81a8.png)

What we would like to have option for is to render the Panel as child of Top nav container. (Eg. black nav bar in the below screen shot).
![image](https://user-images.githubusercontent.com/17021104/68397089-7d8d8380-0127-11ea-8f9b-42328aac4a20.png)

**Comment by JasonGore** [comment]
Do you intend for header content to be interactive even when Panel is displayed?

You can control the host for `Panel` as shown in [this CodePen](https://codepen.io/jasongore/pen/VwwxRob) and the ['Using Customizer to control the default layer behavior' Layer example](https://developer.microsoft.com/en-us/fabric#/controls/web/layer#ILayerProps). However you can see that the rest of the page can still be interacted with when `Panel` is displayed.
