### ISSUE TITLE
Textarea rendered in ChoiceGroupOption is unclickable 

### ISSUE THREAD

**Issue by lancelodliu** [OfficeDev/office-ui-fabric-react#11110]
### Environment Information

- **Package version(s)**: 6.167.3
- **Browser and OS versions**: Chrome Version 77.0.3865.120 (Official Build) (64-bit)

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/lancelod/pen/zYYjdYr

This is caused by the `100% height` of `input`.

#### Actual behavior:
I cannot select and edit in the textarea.

#### Expected behavior:

I can select and edit in the textarea.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by JasonGore** [comment]
This isn't just a styling issue, `ChoiceGroup` has to manage focus as well. Even if you could click on the textarea, the keyboard navigation within `ChoiceGroup` is fundamentally broken. I think this has to be approached by rendering the textarea completely outside of the `ChoiceGroup`.

**Comment by lancelodliu** [comment]
If I replace `textarea` with `TextField`, this issue is fixed.

**Comment by JasonGore** [comment]
I think it's possible there could be issues with focus management, but if you have a CodePen, please feel free to share here with others.

I'm not sure what action is here, if any, so please close this issue if you are happy with the solution you found. Thanks!

**Comment by lancelodliu** [comment]
solution: https://codepen.io/lancelod/pen/vYYaqjE

**Comment by JasonGore** [comment]
Please note that the presence of the `TextField` breaks arrow key navigation within the `FocusZone` and makes it harder to break out to the next `ChoiceGroup` option. `TextField` also grabs focus when another option is highlighted. These should be considerations from a keyboard accessibility point of view.
