### ISSUE TITLE
Nav with Position Indicator (it already exists and is being used on your site)

### ISSUE THREAD

**Issue by clearwaterstream** [OfficeDev/office-ui-fabric-react#11132]
#### Describe the feature that you would like added

Hi, look at https://developer.microsoft.com/en-us/fabric#/controls/web/button

See the menu on the right? It's the one titled "On this page". Notice how the menu auto-highlights the current section that you are on, as you scroll down?

#### What component or utility would this be added to

Nav

#### Have you discussed this feature with our team, and if so, who

No, but you guys already built it and you are using it

#### Additional context/screenshots

![image](https://user-images.githubusercontent.com/25708965/68507440-e8c77a80-0239-11ea-9eb4-7dad251fb186.png)

Thank you!!!!

**Comment by JasonGore** [comment]
I don't think this would ever be a Fabric component, but I can point you to the [SideRail code](https://github.com/OfficeDev/office-ui-fabric-react/blob/b5c894b45127180a56bc29f0b7e4c0f8af3cb9af/packages/example-app-base/src/components/SideRail/SideRail.tsx#L85) and the [styling](https://github.com/OfficeDev/office-ui-fabric-react/blob/b5c894b45127180a56bc29f0b7e4c0f8af3cb9af/packages/example-app-base/src/components/SideRail/SideRail.styles.ts#L77) used to highlight the active section.

**Comment by clearwaterstream** [comment]
> 
> 
> I don't think this would ever be a Fabric component, but I can point you to the [SideRail code](https://github.com/OfficeDev/office-ui-fabric-react/blob/b5c894b45127180a56bc29f0b7e4c0f8af3cb9af/packages/example-app-base/src/components/SideRail/SideRail.tsx#L85) and the [styling](https://github.com/OfficeDev/office-ui-fabric-react/blob/b5c894b45127180a56bc29f0b7e4c0f8af3cb9af/packages/example-app-base/src/components/SideRail/SideRail.styles.ts#L77) used to highlight the active section.

Fair enough (re it never being a component). If the menu was simply tabs (Pivot) laid out vertically, I could argue you _could_ have introduced "tabs auto select  feature" where a particular tab would open, as you scroll. This would then highlight the current tab. You could borrow something from [ScrollablePane](https://developer.microsoft.com/en-us/fabric#/controls/web/scrollablepane).

Anyhow, thanks for the SideRail link, I've got what I needed :)
