### ISSUE TITLE
Dropdown incompatible with ReactDOM.createElement in Typescript

### ISSUE THREAD

**Issue by liang2zhu1b** [OfficeDev/office-ui-fabric-react#1113]
### Bug Report

- __Package version(s)__: 1.7.2 (React 15.3.2)
- __Browser and OS versions__: N/A

#### Describe the issue:

Dropdown control is not compatible with TypeScript React when use ReactDOM.createElement (than through tsx) 

#### Actual behavior:
Following code won't compile and error as  "*error TS2352: Build: Type 'typeof Dropdown' cannot be converted to type 'ComponentClass<IDropdownProps>'.*"

```javascript
import React = require("react");
import ReactDOM = require("react-dom");
import { IDropdownProps, Dropdown} from "OfficeFabric/Dropdown";
ReactDOM.render(
    React.createElement(
        Dropdown as React.ComponentClass<IDropdownProps>,
        props),
    this._element.find(".work-items-pane-filter")[0]);

```

The error was because Dropdown class defines *defaultProps* member variable which does not implement the IDropdownProps interface -  Putting the syntax of Typscript aside, logically I tend to think React is correct here - default props should be an instance of the IDropdownProps (or empty) while the definition in Dropdown control is not consistent with that principle 
From *office-ui-fabric-react/packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx*:

```javascript
  public static defaultProps = {
    options: []
  };
```

#### Expected behavior:

Set the defaultProps as empty (which most other office fabric component does) 

### If applicable, please provide a codepen repro:

N/A

**Comment by dzearing** [comment]
`defaultProps` is a standard React-ism, similar to `componentDidMount` and `render`. Technically these things should be protected. We make them public since React needs to access them. I'm not sure why you don't just do:

```
ReactDOM.render(<Dropdown { ...props } />, element);
```
TypeScript seems to understand the JSX component and seems to be able to cast properly. I'm not exactly sure what ComponentClass's definition is doing but it seems not quite right.
