### ISSUE TITLE
Search values & Clear button inside Dropdown

### ISSUE THREAD

**Issue by nsksaisaravana** [OfficeDev/office-ui-fabric-react#11139]
#### Describe the feature that you would like added

Able to search the dropdown values, so we need text box inside the dropdown and need a clear icon to clear the values.

#### What component or utility would this be added to

Dropdown

####  Screenshot

![image](https://user-images.githubusercontent.com/17681573/68552803-3e389d00-046f-11ea-8f5b-78df04ed0098.png)

**Comment by kenotron** [comment]
I think you might be looking for the ComboBox control:
https://developer.microsoft.com/en-us/fabric#/controls/web/combobox

**Comment by micahgodbolt** [comment]
Here's an example of how you can add a filter to a dropdown. We don't have any plans to add one permanently

https://codepen.io/micahgodbolt/pen/MNPLJe?editors=0010
