### ISSUE TITLE
Link tag text wrapping is not fluent

### ISSUE THREAD

**Issue by rhalaly** [OfficeDev/office-ui-fabric-react#11157]
### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**: Edge, Edge beta, Chrome, Windows 10

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/hraz/pen/MWWqYPM

#### Actual behavior:

When the `Link` text is too long (without `href`), the component gets a new line instead of regular text wrapping

![image](https://user-images.githubusercontent.com/8597700/68664376-f7b77100-0548-11ea-9ae0-3922a40f98fa.png)

#### Expected behavior:

The text wrapping should be fluent as normal text

![image](https://user-images.githubusercontent.com/8597700/68664324-e2424700-0548-11ea-8028-eeaaa7b5dc03.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: Internal Microsoft Product

**Comment by micahgodbolt** [comment]
Links without an href are rendered as buttons. Multiline buttons always do this. 

So the question is, should a Link render as an `a` tag even without an href?

Also wondering why you are using Link without an HREF and if this is really high priority.

**Comment by kenotron** [comment]
This is a bit of an edge case with a workaround:
https://codepen.io/kenotron/pen/rNNZyJE

The workaround is with the `as` attribute:

```jsx
<Link as='a'>test test</Link>
```

**Comment by kenotron** [comment]
@khmakoto - FYI as you're considering the new fluent link

**Comment by rhalaly** [comment]
@micahgodbolt Yes it is necessary. We are writing internal Microsoft product that supports text editing with links. We use the links as a triggers for open menus (not for `href` redirection). The reason we use `Link` is for getting Fabric look & feel for the links

**Comment by rhalaly** [comment]
@kenotron That's can work for us. Thank you very much!
