### ISSUE TITLE
ChoiceGroup: Borders visible by default in high contrast and no way to distinguish keyboard focus

### ISSUE THREAD

**Issue by prmittal** [OfficeDev/office-ui-fabric-react#1115]
In high contrast mode, choice group shows borders by default (as shown in below image).
As a result, when navigating via keyboard, user is not informed if the focus is on that element or not.

![image](https://cloud.githubusercontent.com/assets/11937034/23354454/4d3055b4-fcf7-11e6-86a8-d68d7fc244ae.png)

**Comment by mdahamiwal** [comment]
Good catch. Interestingly, we have a transparent border here to fix the focus behavior but it is resulting in visible border in High Contrast mode. @mikewheaton, can you think of a fix here or should we check with Edge team for why transparent borders are visible in high contrast mode?

**Comment by mikewheaton** [comment]
Can you try adding `-ms-high-contrast-adjust: none;` to it? That tells Edge to use our high contrast styles rather than applying its own. This will be set globally once we update Fabric React to use Fabric Core 6.0 (it was included in [this PR](https://github.com/OfficeDev/office-ui-fabric-core/pull/913)) but may need to be temporarily added for now.

**Comment by mdahamiwal** [comment]
Tried that already with no luck, it messes up other high contrast overrides for internal elements.

**Comment by aleksandrjPersonal** [comment]
Adding fieldIsDisabled rule to choiceField. Making borders dotted (greyed out)

**Comment by aleksandrjPersonal** [comment]
Made default border dotted, focus border solid.

**Comment by prmittal** [comment]
@aleksandrjPersonal I am not able to see any border at all now. Both with and without HC and keyboard focus. Can you please take a look once more.

**Comment by aleksandrjPersonal** [comment]
Hmm, can you send me a screen shot of what you are looking at? Make sure you have latest, and rebuild the project

-alek

**Comment by prmittal** [comment]
![image](https://cloud.githubusercontent.com/assets/11937034/25265734/122d5fde-268c-11e7-8e2c-a22d0018dbb2.png)

In above case, the focus is on the choice group but no border is visible.

The styling applied is 

![image](https://cloud.githubusercontent.com/assets/11937034/25265963/227e2dea-268d-11e7-95cc-c87baa897fe1.png)
Based on the highlighted field, it seems like it is the latest code

**Comment by prmittal** [comment]
A little more detail:

At the time of above styling, the component is 
![image](https://cloud.githubusercontent.com/assets/11937034/25266306/584331ae-268e-11e7-802a-57ac51792589.png)

@aleksandrjPersonal Let me know if the build I'm using is incorrect.

**Comment by aleksandrjPersonal** [comment]
Oh ok I can take a look at what was done for this

-alek

**Comment by prmittal** [comment]
@aleksandrjPersonal Were you able to look into this issue? Since this one is marked as closed, i'll file a new one to keep track.
