### ISSUE TITLE
Details List : Sort performance is bad in Edge if a column contains duplicated data

### ISSUE THREAD

**Issue by nanivijay** [OfficeDev/office-ui-fabric-react#11150]
### Environment Information

- **Package version(s)**: 7.58.0
- **Browser and OS versions**: Edge and Windows 10 64-bit

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/nanivijay/pen/XWWByLG?&editable=true

**Sort on the Modified By column and see the performance in Edge browser**

#### Actual behavior:

Sort is taking time and freezing the UI

#### Expected behavior:

Sort shouldn't freeze the UI

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: (if applicable)

**Comment by kenotron** [comment]
@aditima - assigning this DL perf bug to you. I think @KevinTCoughlin would be interested in this issue as well.

**Comment by kenotron** [comment]
Okay this is not a Fabric bug - it takes *2* seconds to sort the list of 10,000 items (with the duplicates). This is in the `columnClick` handler:

```
const time = performance.now();
  const key = columnKey as keyof T;
  const items = items.slice(0).sort((a: T, b: T) => ((isSortedDescending ? a[key] < b[key] : a[key] > b[key]) ? 1 : -1));

console.log(performance.now() - time);
```

It took 2s on my 9th gen intel cpu machine(!!!!!!)

But if I changed the comparator code to this:

```
const items = items.slice(0).sort((a: T, b: T) => a[key] === b[key] ? 0 : ((isSortedDescending ? a[key] < b[key] : a[key] > b[key]) ? 1 : -1));
```

The example would reduce to 0.5s! So, the difference here is that we're spending a lot of time moving items around in an array when the items are actually EQUAL in that previous example.

**Comment by kenotron** [comment]
So, the example code doesn't have repeating modified by names here, I think you can fix that sort function in your own code to benefit from this research. I'm closing this as it isn't really a problem of Fabric control itself.
