### ISSUE TITLE
Changing row height for DetailsList

### ISSUE THREAD

**Issue by donamj** [OfficeDev/office-ui-fabric-react#11152]
How can I change the height or padding of rows in DetailsList?

**Comment by kenotron** [comment]
For usage questions (for the benefit of other users of this library), please direct them here with the `office-ui-fabric` tag: 
https://stackoverflow.com/questions/tagged/office-ui-fabric

To answer quickly here: https://developer.microsoft.com/en-us/fabric/#/controls/web/detailslist/variablerowheights

If you want to take over the entirety of how to render the row item, then look at this:
https://developer.microsoft.com/en-us/fabric/#/controls/web/detailslist/customitemrows
