### ISSUE TITLE
Link appears to overwrite ref with its own internal value

### ISSUE THREAD

**Issue by rhalaly** [OfficeDev/office-ui-fabric-react#11158]
### Environment Information

- **Package version(s)**: Latest
- **Browser and OS versions**: Edge, Edge beta, Chrome, Windows 10

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/hraz/pen/ExxeVrr

It seems that the "ref" is not working on `Link` with `ContextualMenu` because [`Link` appears to overwrite `ref` with its own internal value. ](https://github.com/OfficeDev/office-ui-fabric-react/blob/fc1987c135c486f32262042337515a9c21443d37/packages/office-ui-fabric-react/src/components/Link/Link.base.tsx#L35)

#### Actual behavior:

The `ContextualMenu` is floating relatively to the `<body>` and not to the `Link`

#### Expected behavior:

The `ContextualMenu` will floating relatively to the `Link`

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: Internal Microsoft product

**Comment by micahgodbolt** [comment]
Have you tried using [componentRef](https://github.com/OfficeDev/office-ui-fabric-react/blob/2894062b1d0515055c29061dfc6f586f918ca41c/packages/office-ui-fabric-react/src/components/Link/Link.types.ts#L55)?

**Comment by rhalaly** [comment]
Yes, not working

**Comment by kenotron** [comment]
`ContextualMenu` doesn't take a component as its target. It needs a real DOM element to target. So, you'll need to actually access the link's root element with findDOMNode(). I've attached a workaround here:

https://codepen.io/kenotron/pen/LYYJyRj?editors=0011

**Comment by rhalaly** [comment]
Fair enough thanks!
