### ISSUE TITLE
Add a onRenderUpperContent property to ComboBox

### ISSUE THREAD

**Issue by Lachlan24** [OfficeDev/office-ui-fabric-react#11168]
#### Describe the feature that you would like added

Add a onRenderUpperContent property 

#### What component or utility would this be added to

The comboBox component

#### Additional context/screenshots

I am trying to add a searchBox to my comboBox and believe the feature will be the best way to achieve this.

**Comment by kenotron** [comment]
This is a small feature, and I have a PR - but I want to have someone who owns this component review this as well as creating a good example / test for this before merging!

@joschect - FYI... it seems your'e already marked codeowner so you're on the PR reviewers list :)
