### ISSUE TITLE
MaskedTextField adding extra mask character to value

### ISSUE THREAD

**Issue by ChristopherHaws** [OfficeDev/office-ui-fabric-react#11160]
### Environment Information

- **Package version(s)**: 7.58.0
- **Browser and OS versions**: EdgeDev/Chrome on Windows 10

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/chaws/pen/dyyqRmE

![image](https://user-images.githubusercontent.com/5934505/68703716-03eb0080-0540-11ea-9bfe-828f8e5ed2ba.png)

#### Actual behavior:
When using MaskedTextField, the value is adding an additional maskChar to the end of value.
![image](https://user-images.githubusercontent.com/5934505/68702406-a1910080-053d-11ea-99f7-dfa878bf59e1.png)

#### Expected behavior:
The value should match the `mask` value.

### Priorities and help requested:
Are you willing to submit a PR to fix? No
Requested priority: Blocking

**Comment by kenotron** [comment]
So, the value of onChange callback is meant to be using the "value" param:

![image](https://user-images.githubusercontent.com/34725/68721763-5d672580-0568-11ea-89ef-19836728f434.png)

I've forked your example to it:

https://codepen.io/kenotron/pen/eYYLVZN
