### ISSUE TITLE
Support new 24px icons in initializeIcon, follow up to #11119

### ISSUE THREAD

**Issue by hjonasson** [OfficeDev/office-ui-fabric-react#11165]
#### Describe the feature that you would like added

In the recent PR #11119 24px icons were added according to design spec on Fabric's website. You can verify that the icons exist on the CDN [here](https://spoprod-a.akamaihd.net/files/fabric/assets/item-types-fluent/24/docx.svg?refresh1). However if you try to call them from your code via initializeFileTypeIcon, the code breaks with the message that the icon hasn't been registered.

#### What component or utility would this be added to

This seems to live in [this line](https://github.com/OfficeDev/office-ui-fabric-react/blob/897fd55011a1c8e8e5243b55c39619fc7587d1b4/packages/file-type-icons/src/initializeFileTypeIcons.tsx#L9). These numbers reflect the interface [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/897fd55011a1c8e8e5243b55c39619fc7587d1b4/packages/file-type-icons/src/getFileTypeIconProps.ts#L14), but are missing the new value 24.

**Comment by kenotron** [comment]
I can add this, shouldn't be much work.
