### ISSUE TITLE
Dropdown menu items overflow without ellipse after Fabric 7 upgrade

### ISSUE THREAD

**Issue by msnyder-msft** [OfficeDev/office-ui-fabric-react#11176]
### Environment Information

- **Package version(s)**: 7.54.1
- **Browser and OS versions**: Seems to be common, Chromium Edge 80.0.320.5

### Description
We just upgraded from Fabric 6 to Fabric 7 and noticed this change in behavior that I would consider as a bug. I believe the actual issue is because of a change to button which is used to handle the dropdown menu items. It appears that a div was changed to a span (I believe as a result of this accessibility issue #10021).

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/Mitch7_26/pen/WNNavRm

#### Actual behavior:
In Fabric 6
![image](https://user-images.githubusercontent.com/57726991/68801427-ed60aa00-0610-11ea-981e-9f67ee4046d8.png)

In Fabric 7
![image](https://user-images.githubusercontent.com/57726991/68802181-4f6ddf00-0612-11ea-8c5d-c4b31069436d.png)

#### Expected behavior:
![image](https://user-images.githubusercontent.com/57726991/68801427-ed60aa00-0610-11ea-981e-9f67ee4046d8.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Microsoft MSX Portal

**Comment by kenotron** [comment]
This is interesting because this should have been backported to 6 according that the thread in that issue...

**Comment by kenotron** [comment]
I am wondering if you could live with the dropdown having auto width (the menu):
https://codepen.io/kenotron/pen/QWWZEmG

![image](https://user-images.githubusercontent.com/34725/68809899-c3fc4a00-0621-11ea-9d3d-e8125c1008c9.png)

If so, maybe you can just live with `dropdownWidth` option

**Comment by msnyder-msft** [comment]
Tha

> I am wondering if you could live with the dropdown having auto width (the menu):
> https://codepen.io/kenotron/pen/QWWZEmG
> 
> ![image](https://user-images.githubusercontent.com/34725/68809899-c3fc4a00-0621-11ea-9d3d-e8125c1008c9.png)
> 
> If so, maybe you can just live with `dropdownWidth` option
We actually ended up using ComboBox so that we could do that. I didn't realize that it was possible with dropdown itself. Unfortunately, that codepen seems to point to my own code and doesn't reflect your changes for me, is there a way I can see how you did that?

**Comment by kenotron** [comment]
there is a line that adds `dropdownWidth="auto"` as a prop - it's really easy to miss...
