### ISSUE TITLE
DetailsList: Support column re-arranging (drag and drop)

### ISSUE THREAD

**Issue by notgiorgi** [OfficeDev/office-ui-fabric-react#1117]
Is it possible to drag and drop `DetailsList` columns? It has `dragDropEvents` prop but there is no example in docs. Can you provide it?

**Comment by dzearing** [comment]
I assume you mean column re-arranging. Not currently, though it's been on our wishlist for a while.

**Comment by notgiorgi** [comment]
Also is it possible to add `onColumnResize` event to capture column widths?

**Comment by notgiorgi** [comment]
@dzearing is this feature going to be shipped soon? Is it even in a team schedule?

**Comment by isabelacmor** [comment]
Is there an update on this? Is this feature on the roadmap?

**Comment by KevinTCoughlin** [comment]
> Edit: It looks like this feature has been implemented, for anyone who stumbles on this issue:
> https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/draganddrop

Yes, this is supported by `DetailsList` in both Fabric 6 & 7.
