### ISSUE TITLE
TextField: Clearing the field does not fire onChanged event if onGetErrorMessage set

### ISSUE THREAD

**Issue by lszomoru** [OfficeDev/office-ui-fabric-react#1118]
I have the following TextField component:

```
<TextField
    onGetErrorMessage={(value: string) => { if (value.length > 0) return ""; else return "Please insert a title." }}
    onChanged={() => console.log("onChanged")} />
```

### Bug Report

- __Package version(s)__: 1.9.1
- __Browser and OS versions__: Chrome Version 56.0.2924.87 (64-bit)

#### Describe the issue:

Set up a page with the component listed above. Enter some text in the TextField to see that the onChanged event fires. Then clear the contents of the TextField and notice that the event does not fire. Removing the onGetErrorMessage property will resolve the problem.

Based on my tests, the onBeforeChange works as expected.

#### Actual behavior:

onChanged event does not fire when the contents of the TextField are cleared.

#### Expected behavior:

onChanged event should fire when the contents of the TextField are cleared.

**Comment by mdahamiwal** [comment]
Not sure why the onChanged is shielded behind errorMessage https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/TextField/TextField.tsx#L335-L337 ? Fix should be simple but would like @dzearing to confirm if it has some history behind it.
