### ISSUE TITLE
Option to disable tooltip for DropdownOption

### ISSUE THREAD

**Issue by LukeOwlclaw** [OfficeDev/office-ui-fabric-react#11187]
#### Describe the feature that you would like added

Currently for `multiSelect` mode in [`Dropdown.base.tsx`](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx) Checkbox.title is set to `title={item.title ? item.title : item.text}`. This title is used as tooltip for the dropdown option. This means that when not specifying `title`, `text` is used as tooltip. This is redundant. It would be good to have an option to disable that tooltip.

Note: For `!multiSelect ` CommandButton.title is set like: `title={title}`. Can we have the same for `multiSelect`?

#### What component or utility would this be added to

Dropdown

#### Additional context/screenshots

Redundant tooltip:
![image](https://user-images.githubusercontent.com/2737900/68860334-9bd81e00-06e9-11ea-8ab4-d703c9a2a04a.png)

Putting a space is only way to get rid of it, but not nice at all: 
![image](https://user-images.githubusercontent.com/2737900/68860518-f4a7b680-06e9-11ea-9099-648391cd0bc5.png)

**Comment by kenotron** [comment]
I'm teasing out the logic here in the title variable for the single select mode:

```jsx
const { title = item.text } = item;
<CommandButton title={title} />
```

vs the multiselect code

```jsx
<Checkbox title={item.title ? item.title : item.text} />
```

Seems like the code is DIFFERENT, but they have the similar behavior. The subtlety is in how the destruction assignment expression deal with null / undefined vs that ternary conditional operator. I'm creating a PR to fix this since it's a pretty easy fix.

**Comment by LukeOwlclaw** [comment]
Thanks @kenotron for the fix and also for teaching me something new:
I had to look up that default value syntax within the destructuring assignment.

And indeed, [according to the docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#Default_values_2) the default value is only assignment in case of ``undefined``, whereas the ternary operator also triggers on `null`.
