### ISSUE TITLE
How to get the value from the react fabric ui checkbox

### ISSUE THREAD

**Issue by amoghtelkar** [OfficeDev/office-ui-fabric-react#11184]
This is the JSX tag. I'm getting the status of the checkbox but not the value or the label name.

`<Checkbox label="Innovation" value="Innovation" onChange={this._onChange} />`

Below is the code that shows the status

`public _onChange(ev: React.FormEvent<HTMLElement>, isChecked: boolean) {
  console.log("The option has been changed to ${isChecked}.");`

I tried to pass the value but it didn't work.

**Comment by micahgodbolt** [comment]
Value isn't a prop that's used in the checkbox. it's inherited because we are still extending button properties. 

If you're still having trouble with label showing up, can you create a repro in codepen?

aka.ms/fabricpen

**Comment by kenotron** [comment]
This is the correct way to use the Checkbox component:

https://codepen.io/kenotron/pen/NWWOmJY

Please look at this and make sure your usage matches with the codepen.
