### ISSUE TITLE
[Accessibility] Dropdown: Doesn't say that it's a button

### ISSUE THREAD

**Issue by HalcyonPride** [OfficeDev/office-ui-fabric-react#11180]
### Environment Information

- **Package version(s)**: 7.60.1
- **Browser and OS versions**: Edge; Windows 10 Pro, Version 1909

### Describe the issue:

See title

### Please provide a reproduction of the issue in a codepen:
https://developer.microsoft.com/en-us/fabric#/controls/web/dropdown

### Documentation describing expected behavior
https://www.w3.org/TR/wai-aria-practices/examples/listbox/listbox-collapsible.html

**Comment by kenotron** [comment]
The example listed in the link above happened to be using the "button" tag for the listbox. We're not doing this, so it should not be called out as a button. So, our behavior is actually by design where we have a div that has a role of listbox.

**Comment by HalcyonPride** [comment]
Hi @kenotron,

Okay, I'm fine with that - thanks for the quick reply!

Josh
