### ISSUE TITLE
[Accessibility][Keyboard Navigation]: Disabled Combo box option 'Option J' is selectable using keyboard.

### ISSUE THREAD

**Issue by joschect** [OfficeDev/office-ui-fabric-react#11193]
Split out of issue #6920

**Comment by joschect** [comment]
The item is not just focusable, it is selectable. This is definitely a bug.

**Comment by joschect** [comment]
Occurs on ComboBox with toggleable autoComplete and allowFreeform when both are set to false.

**Comment by micahgodbolt** [comment]
@jspurlin can you confirm what is supposed to happen when disabled options are selected? If "option F" is disabled...

1. what happens on blur when disabled item is selected in the input

![image](https://user-images.githubusercontent.com/1434956/69375554-74d79a00-0c5d-11ea-9a74-e752f5324d66.png)

2. what happens on keypresses when disabled item is focused (enter, escape, click outside)

![image](https://user-images.githubusercontent.com/1434956/69375614-9cc6fd80-0c5d-11ea-959b-62d9ac4271e9.png)

**Comment by jspurlin** [comment]
1. it should go back to the previously selected item
2. This one is a little more interesting, it could either 1) no-op OR 2) close the menu and keep the disabled option in the input OR 3) close the menu and go back to the previously selected item. Option 3 feels the best/most consistent

**Comment by micahgodbolt** [comment]
3 is the easiest too :D it was a 1 line change
