### ISSUE TITLE
[Accessibility][Programmatic access]: Narrator speaks information of the 'Basic uncontrolled example (allowFreeform: F, AutoComplete: F)' combo box twice.

### ISSUE THREAD

**Issue by joschect** [OfficeDev/office-ui-fabric-react#11205]
Split out of issue #6920

**Comment by joschect** [comment]
Look to dropdown to see how this is fixed since a similar problem was recently fixed for dropdown.

**Comment by xugao** [comment]
repro steps:
1. Open 'https://developer.microsoft.com/en-us/fabric#/components/ComboBox' in Edge.   
2. Navigate to 'Basic uncontrolled example (allowFreeform: F, AutoComplete: F)' combo box using tab key.  
3. Press F12 to open developer tool and inspect the control.   
4. Observe the for, id and Aria-labelled by attribute.    
5. Observe the issue with screen reader open list and close it then renavigate the control.

**Comment by xugao** [comment]
it's unclear to me what's the bug here. the only possible redundant narration i hear is - on opening the combobox options, the label is read; on closing the combobox options (selected an option), the label is read again.  @joschect , do you know who i can confirm the bug with?
