### ISSUE TITLE
[Accessibility][Keyboard Navigation]: Keyboard tab focus goes to the disabled element inside 'Disabled uncontrolled example with defaultSelectedKey' combobox.

### ISSUE THREAD

**Issue by joschect** [OfficeDev/office-ui-fabric-react#11201]
Split out of issue #6920

**Comment by joschect** [comment]
Per the comment in the original issue, this is working as intended. Disabled element should still get focus so the user can receive information about what is disabled.

**Comment by tahoon-ms** [comment]
Please consider re-opening this issue. Several reasons:
1. This behavior is not consistent with other Fabric controls. In #4387, the decision was made to not focus disabled controls.
2. This is the default behavior on all browsers, as noted in #4387. Although the [WAI-ARIA spec](https://www.w3.org/TR/wai-aria-1.1/#aria-disabled) gives some wiggle room about whether an `aria-disabled` element can be navigated to by keyboard, the behavior of native `disabled` elements is consistent across browsers. For example, try `<input disabled tabindex="1" />` on any browser. It will not be reachable by TAB.
3. For screen reader users, they can always access disabled elements whether or not they are tabbable. TAB is not the only way to navigate a page. Users can reach disabled elements using other methods. Like arrow keys with scan mode in Narrator, or the number pad with NVDA.
4. It is annoying for sighted keyboard users to TAB to something that is not interactive.
