### ISSUE TITLE
Cannot fetch Microsoft Teams Icon from Brand Icons

### ISSUE THREAD

**Issue by akash21391** [OfficeDev/office-ui-fabric-react#11233]
I am unable to get **Microsoft Teams** icon from Office-UI-Fabric Brand Icons

https://developer.microsoft.com/en-us/fabric#/styles/web/office-brand-icons

Here is how I am trying to fetch it
https://codepen.io/jahnp/pen/ZeZBpg

Also I would like to ask is there any other way I can use Brand icon.
The documentation says to use it through **Icon** component, but it does not work.
Also the documentation does not provide proper sample code through which I can use them.
There is a mismatch between what is written in it and the sample code.

![image](https://user-images.githubusercontent.com/29160810/69007245-79503a00-0961-11ea-983b-dfe6767899dc.png)

**Comment by aneeshack4** [comment]
@akash21391 I see that you're using 6.0.0 in the url - have you tried grabbing from a more recent version of Fabric? @Jahnp who owns the icons part of Fabric might have more insights into this.

**Comment by akash21391** [comment]
@aneeshack4 I am able to fetch Teams Icon with latest version of office ui fabric core (10.1.0).

Coming back to question 2. @Jahnp  Is there any way I can use it directly with <Icon> component?
I cannot find it in IconNames.

**Comment by Jahnp** [comment]
Apologies for the confusion. I'm pretty sure this is a documentation bug + feature gap we've been planning to fix + add for some time, respectively, but haven't budgeted time for yet.

There are a few separate systems here that don't quite overlap. In this case, the brand icons you're referring to are only part of Fabric Core, and don't have a direct parallel in Fabric React. `IconNames` is only applicable to the MDL2 font icon (in other words, icons you can browse [here](https://developer.microsoft.com/en-us/fabric#/styles/web/icons)). You actually can't use the `<Icon>` component with the Fabric Core brand icons without some custom setup work, which hasn't been done yet. That's the docs bug—it should be something else altogether. I'm pretty sure what's there is a holdover from prior docs.

So unfortunately, today, your best route to use some of the newer assets is to either 1.) use the Brand Icon pieces from Fabric Core, on the page you linked above, or 2.) reference assets directly from the CDN (like [this Teams icon](https://static2.sharepointonline.com/files/fabric/assets/brand-icons/product/svg/teams_48x1.svg)).

We know this isn't great. It's on the backlog of issues to address in the coming sprints.

**Comment by akash21391** [comment]
@Jahnp Thanks for the information.

But I have seen a lot developers asking ways to use Brand icons on stackoverflow and github. I would love to see BrandIcons integrated with Office UI Fabric react in <Icon> component or maybe some separate component.
