### ISSUE TITLE
Border color added to CommandBar buttons in several tenants - SPFx extension

### ISSUE THREAD

**Issue by c-eiser13** [OfficeDev/office-ui-fabric-react#11246]
### Environment Information

- **Package version(s)**: 6.189.2
- **Browser and OS versions**: Chrome (latest), Edge Beta (Latest)
- SPFx extension v1.9.1

#### Actual behavior:

Starting this past Friday, in several of our tenants where this solution is installed, the CommandBar began displaying a border around the button items. The .root class of the button element is now using a border color of rgb(118,118,118), instead of transparent like it always did in the past. When we move to an application page, such as /_layouts/15/viewlsts.aspx, the issue is gone. Also, in some tenants, it displays correctly, until a few refreshes, where it eventually begins showing the border. If this is a change in CSS, I can account for that by removing the border, but wanted to verify first this is an actual expected change. 

![commandbar](https://user-images.githubusercontent.com/42096464/69157633-d1df1e80-0aaa-11ea-9b60-2498df856e76.PNG)

On Application page, shows correctly
![noborder](https://user-images.githubusercontent.com/42096464/69157328-672de300-0aaa-11ea-8a5f-01c5db5ba087.PNG)

On the homepage of the site, we have other SPFx web parts using many other OUIF components, so I created a blank page with just the extension to see if any of those components could be causing the border, but I still see it on a blank Site Page.

I also see the following two errors in the console only on pages where the border is displayed around the CommandBar:
![commandbarerror](https://user-images.githubusercontent.com/42096464/69157954-4d40d000-0aab-11ea-93a5-bdd120201450.PNG)

Not sure if it is related or not, but figured I send along in case it is. If this should be logged in the SP repo, I can do so as well.

#### Expected behavior:

CommandBar renders with a transparent border around button elements.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by aneeshack4** [comment]
@c-eiser13 I believe this might be because SharePoint is still using an older version of Fabric. Also the styles file of CommandBar hasn't been changed since Jul 22 so whatever change happened couldn't have just been last Friday at least on Fabric's end. Are you sure this isn't a problem with Sharepoint's migration onto Fabric 7?

**Comment by c-eiser13** [comment]
Thanks @aneeshack4  for the reply, and presume it is likely an issue on the SharePoint side but was not sure. It is very intermittent, whereas right now there is no border in one tenant and there is a border in another. Yesterday, there was no border most of the morning, then after a refresh around lunch, border was back. I also notice the "Allow debug scripts" popup when debugging an SPFx solution looks different when the border is present and this appears to be a fabric dialog control. I will close this issue here, but curious if this should be logged on the SharePoint side if they are undergoing a migration to fabric 7?
