### ISSUE TITLE
Row Number is not getting announced by screenreader(NVDA) for Component DetailsList when navigating using tab key

### ISSUE THREAD

**Issue by shsengar** [OfficeDev/office-ui-fabric-react#11245]
### Environment Information

- **Package version(s)**: Latest Office Fabric version

### Describe the issue:
Row Number for DetailsList is not getting announced by screen reader.

### Please provide a reproduction of the issue in a codepen:
1) Go to https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist
2) Start NVDA as screen reader
3) Navigate to DetailsList first row or any, using tab key.
4) Observe that the screen reader just annouces the details of a row with out announcing row number.

Attaching GIF for the above issue
![record2](https://user-images.githubusercontent.com/57530569/69122051-cea45c80-0ac3-11ea-8846-92a2003fa4e3.gif)

#### Actual behavior:

Row number is not getting announced.

#### Expected behavior:

Row number should get announced.

**Comment by aneeshack4** [comment]
Hi @shsengar, this does not repro on Narrator: 
![image](https://user-images.githubusercontent.com/4161791/69290158-f9c6a300-0bcc-11ea-92aa-a845c10c4e48.png)
You can see in this screenshot that even with scan mode on, it reads out the row # details - but make sure to try using ctrl + alt + arrow too.

**Comment by shsengar** [comment]
@aneeshack4 yes, this is an issue when accessing each row with NVDA on.

**Comment by aneeshack4** [comment]
@shsengar Yes, because if it's working with Narrator, it's likely a NVDA problem... you can file an issue with them on their repo: https://github.com/nvaccess/nvda
