### ISSUE TITLE
Tooltip should use same color system to describe its color

### ISSUE THREAD

**Issue by qianghuang94** [OfficeDev/office-ui-fabric-react#11256]
### Environment Information

- **Package version(s)**: 7.x

### See code here:
https://github.com/OfficeDev/office-ui-fabric-react/blob/13872671d45d1793700081d4cfab3e8f5b7fc5c3/packages/office-ui-fabric-react/src/components/Tooltip/Tooltip.styles.ts#L17

### and here:
https://github.com/OfficeDev/office-ui-fabric-react/blob/13872671d45d1793700081d4cfab3e8f5b7fc5c3/packages/office-ui-fabric-react/src/components/Tooltip/Tooltip.styles.ts#L41

in a single component, it's using a different color system to describle.

In one color system, it should be fine, however when you are mixing two color system, color contrast may not be enough.

in fabric 6, it's correct.

### why would i raise the question
I got some questions on the theme:

what's the relationship between palette and semantic color?

If palette is fixed, did you think consumer can modify part of the semantic color without modifying the palette?

from the code and its comment here:
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/styling/src/styles/theme.ts#L182

the mapping only existed when semantic color is not provided.

And my guesses are you will allow consumer to define their semantic color based on their understanding of the mapping between palette and semantic color, right?

If this is true, the questions is that if you mixed using palette and semantic color, how can customer define their own semantic color based on their understanding?

We can't analyze every component to make sure every combination of semantic color and palette work well. The only thing that we care is the combination in semantic color is good.

So i filed this PR to raise the problem. We should not mix-use the two color system.

Why did i use palette?

Because it was used in fabric 6.

**Comment by aneeshack4** [comment]
@qianghuang94 Thanks for reporting this & already opening up a PR with the code change!
