### ISSUE TITLE
People Picker: Expose a way to force resolve text

### ISSUE THREAD

**Issue by dliu120** [OfficeDev/office-ui-fabric-react#11255]
#### Describe the feature that you would like added

For the people picker, when emails are entered that aren't in the suggested list, users have to press 'Enter' or 'Tab' to force resolve the e-mail. This is confusing as some users will save the form, and the text in the field is not persisted.

![people-picker-commit](https://user-images.githubusercontent.com/2090090/69200523-4daf8a00-0af0-11ea-9af7-ea67cc64ebbd.gif)

#### What component or utility would this be added to

People Picker

#### Have you discussed this feature with our team, and if so, who

Yes, Jon Schectman

#### Additional context/screenshots

[8:13 AM] Jon Schectman (WEAVER OF FABRICS)
    David Liu (FLOW) There isn't a way that you can do this right now. You could take a look at the floating pickers instead, they provide A little more fine grain control. Alternatively, we could maybe expose a force resolve function. You can force the picker to complete a suggestion if there's one available with something like this https://codepen.io/slimemold/pen/pooGWaZ?editors=0010

**Comment by aneeshack4** [comment]
Hi @dliu120, it looks like you've already spoken with component owner @joschect. Thanks for filing this feature request - we'll add it to the backlog.

**Comment by dliu120** [comment]
Thanks for the fix! Any chance we could get the change cherry picked to V6?
