### ISSUE TITLE
When VoiceOver is on, in Details list, navigating with arrow keys, the focus is always on the top and sometimes focus will jump to the top. 

### ISSUE THREAD

**Issue by yumikohey** [OfficeDev/office-ui-fabric-react#11253]
### Environment Information

- **Package version(s)**: Both 6 and 7
- **Browser and OS versions**: Chrome, macOS Catalina

### Describe the issue:
In DetailsList, focus does not follow the active item, but stays on the top of the list container, when VoiceOver is on.

### Please provide a reproduction of the issue in a codepen:
This repros on example page.
https://developer.microsoft.com/en-us/fabric/#/controls/web/detailslist

#### Actual behavior:
In DetailsList, focus does not follow the active item, but stays on the top of the list container, when VoiceOver is on.

#### Expected behavior:
Focus window should follow the active item, and screen should not jump to the top.

### Documentation describing expected behavior

[detailsList-a11y.mov.zip](https://github.com/OfficeDev/office-ui-fabric-react/files/3866532/detailsList-a11y.mov.zip)

**Comment by aneeshack4** [comment]
Hi @yumikohey, thanks for reaching out to us! 
This didn't repro for me: 
![image](https://user-images.githubusercontent.com/4161791/69285866-bc4f1f00-0ba6-11ea-923b-08c883cb5b0d.png)
In your video I see that you're using a deploy site with fabric version 6.210.4 - please use the latest version of Fabric & the latest version of VoiceOver on Mac/iOS (so make sure you've updated the OS on your apple device too).

**Comment by yumikohey** [comment]
@aneeshack4 I tried it on the official website, it's the same. Are you using Catalina OS?

**Comment by aneeshack4** [comment]
@yumikohey Yes I am using Catalina - please make sure to use the latest version of Fabric then (again I see in your video URL that it's still on Fabric 6)
