### ISSUE TITLE
add `scrollSelectedToTop` to `List`

### ISSUE THREAD

**Issue by lzl124631x** [OfficeDev/office-ui-fabric-react#11260]
#### Describe the feature that you would like added

I can't use ComboBox because our selection experience is special, so I ended up using `List` to build our customized select experience. I found the `scrollSelectedToTop` in `ComboBox` is useful. But this feature is missing in `List`. 

We can probably add a prop `scrollToItem` or `scrollToIndex` so that we can show that item in the viewport of the list.

#### What component or utility would this be added to

`List`

#### Have you discussed this feature with our team, and if so, who

No.

#### Additional context/screenshots

![image](https://user-images.githubusercontent.com/5824517/69288248-d809f380-0bad-11ea-91ca-2e502abf7cf0.png)

I have one item selected. I want to show that item in the `List`. But currently I can only show the first page of the list.

**Comment by aneeshack4** [comment]
Hi @lzl124631x, thanks for reaching out to us. 

Like you said, `scrollToItem` or `scrollToIndex` are good candidates but also `focusIndex` on the `IDetailsList` interface - have you tried that? https://developer.microsoft.com/en-us/fabric/#/controls/web/detailslist
