### ISSUE TITLE
VirtualizedCombobox does not implement focus(shouldOpenOnFocus, asyncFocus)

### ISSUE THREAD

**Issue by obiwan007** [OfficeDev/office-ui-fabric-react#11263]
### Environment Information

- ^7.38.0
- all browser

#### Actual behavior:

If you retrieve a reference to the VirtualizedCombobox component, you will have only
ref.focus()
available.
If you get an instance ref to ComboBox you have the option to provide
ref.focus(shouldOpenOnFocus, asyncFocus)

Currently ther seems to be no way to open the dropdown element of the ComboBox.

#### Expected behavior:
Be in sync with the ComboBox class or ICombobox class.

### Priorities and help requested:

Are you willing to submit a PR to fix?
Maybe

Requested priority: High

Products/sites affected: (if applicable)
internal site

**Comment by aneeshack4** [comment]
@obiwan007, thanks for reaching out to us. Would you mind providing a codepen please? It'd help give more context to what you're trying to do with Combobox focus.

**Comment by obiwan007** [comment]
I just want to be able to trigger to open the dropdown. That is currently not possible if using the virtualized combobox.

**Comment by aneeshack4** [comment]
@obiwan007 You can see the [onRenderList](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ComboBox/VirtualizedComboBox.tsx#L41) in the VirtualizedComboBox.tsx. That's what triggers the dropdown.... I believe you just have to provide a list of options like in the [Virtualized ComboBox example](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ComboBox/examples/ComboBox.Virtualized.Example.tsx#L28).

**Comment by obiwan007** [comment]
The rendering of the combobox is not a problem as I could live with the default render method. OnRenderlist is not helping here as it just defines HOW the rendering is done, not WHEN.
I need to control the opening of the dropdown.
Here is a codepen based on the basic combobox example where exactly this kind of button was shown.

https://codepen.io/obiwan007/pen/JjjQxwv

The second buton should also open the second combobox which is based on Virtualized combobox.
Please just implement IComboBox also for VirtualizedCombobox.

`focus(shouldOpenOnFocus?: boolean, useFocusAsync?: boolean): boolean;`

The change should not be a big deal as the open method in VirtualizedCombobox is already there. Only the exposed focus function is not implemented as in ComboBox.

**Comment by aneeshack4** [comment]
@obiwan007 Spoke with the component owner - we're in agreement that the fix is reasonable. If it's an easy fix, would you be open to making it?

**Comment by obiwan007** [comment]
Hi, maybe but currently I a a bit busy. Getting into your publishing policies might take some time too. Getting the buildsystem up and running for fabric including tests would be a huge time consumer too...
I'm sure the person who wrote the component could fix it in a way shorter timeframe.
If that would be not possible in the next few weeks, I could take a look.

**Comment by aneeshack4** [comment]
@obiwan007 Sounds good, I spoke with @joschect the component owner and he's going to take it
