### ISSUE TITLE
Feature Request: Allow Fabric themes to be scoped to part of the DOM (without React)

### ISSUE THREAD

**Issue by qianghuang94** [OfficeDev/office-ui-fabric-react#11266]
#### Describe the feature that you would like added

SharePoint provide a framework to 3rd party devs, if their codes used the fabric-ui. Two instance of fabric-react will share some configurations, like theme. If their code has its own theme, it wont work well.

**Comment by aneeshack4** [comment]
@qianghuang94 Thanks for reaching out. Could you provide some more details on your use case? Are you looking for Fabric components to override Sharepoint theming to adopt the 3rd party theme? 

@jdhuntington on our team is working on some new theming infra with composed - perhaps that will allow for more flexible theming?

**Comment by micahgodbolt** [comment]
this is a dup of #11289. I'll close this one down as the other has a bit more context
