### ISSUE TITLE
React DND Drag and Drop Touch Events not working inside Dialog and Modal components

### ISSUE THREAD

**Issue by jyothsnag29** [OfficeDev/office-ui-fabric-react#11264]
### Environment Information

- **Package version(s)**: (6.189.0)
- **Browser and OS versions**: (Touch supported devices)

### Please provide a reproduction of the bug in a codepen:

https://github.com/jyothsnag29/ReactDnDMultiBackEndDialog

#### Use case about the mentioned repository
![image](https://user-images.githubusercontent.com/43003891/69328728-0b04c380-0c50-11ea-803c-a8c8c0735fb5.png)
If we drag the red/green/blue color box and drop it to the gray box we get an alert about which color has dropped. Open Pop up link opens the Dialog component having same drag and drop logic. Open
Model link open the Modal component having same drag and drop logic.

#### Actual behavior:
I was using [React dnd-multi-backend](https://github.com/LouisBrunner/dnd-multi-backend/tree/master/packages/react-dnd-multi-backend/examples) to make it work for both touch and mouse events. But unfortunately Drag and Drop Touch events are not working inside Dialog or Modal window even after setting the eventBubblingEnabled to true. However It works in normal screen.
Mouse events work in all scenarios.

#### Expected behavior:

When we try to do the color drag and drop from normal screen or inside the Dialog or inside Modal window it should work for both Mouse events and Touch events

**Comment by aneeshack4** [comment]
Hi @jyothsnag29, would you mind reproing this in a codepen and linking that? I see that you linked your repo but getting a repo in a sandbox environment like a codepen or on our docs site with one of our examples would help us investigate this further.

**Comment by jyothsnag29** [comment]
I couldn't find the react-dnd-multi-backend in codepen environment, so created in codesandbox. Hope it helps you to investigate it further.
https://codesandbox.io/s/reactdndmultibackendcolordrop-5216c

**Comment by aneeshack4** [comment]
@jyothsnag29 Thanks for providing this sandbox - they drag & drop is working for me in the modal & the dialog just as it outside on the page. I get this console output in all 3 areas when I'm on the browser on a non-touch device like my Mac but I see that it doesn't work on my iPhone - so this might be an iOS issue... it looks like TouchEvents are handled just like MouseEvents in the onDrag in [Modal.base.tsx](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Modal/Modal.base.tsx#L310) so I'm not sure what the problem is here. @JasonGore, any ideas?
![image](https://user-images.githubusercontent.com/4161791/69768919-77dbfa00-1137-11ea-9201-a2d8a12a3418.png).

**Comment by jyothsnag29** [comment]
Thank you for verifying the sandbox.
As already mentioned in the ticket its working perfectly fine for mouse events and the problem noticed was with Touch events. Like iPhone, you can even notice the issue in Touch enabled laptops like Surface Pro.

**Comment by JasonGore** [comment]
It's possible that touch events need to be added [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/b193e2a6f657123447e9a9b6955d14f57d027766/packages/office-ui-fabric-react/src/components/Layer/Layer.base.tsx#L166) and / or [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/b193e2a6f657123447e9a9b6955d14f57d027766/packages/office-ui-fabric-react/src/components/Layer/Layer.base.tsx#L195). If you've reproed the issue lets triage this as a bug for now.

**Comment by mrphannguyen** [comment]
Hi @jyothsnag29 @aneeshack4 

I have the same issue with react-dnd and Panel of Office Fabric, I have just upgraded to office-ui-fabric-react v7.76.0 for fixing the bug: touch on body of panel (https://github.com/OfficeDev/office-ui-fabric-react/pull/11339) but get the issue with drag/drop. 

The drag/drop with react-dnd work fine with v.6.55.0

Could you pls help to check.

**Comment by aneeshack4** [comment]
@JasonGore Is it possible that this actually a regression? Since it worked fine in previous versions.

**Comment by JasonGore** [comment]
We switched to using React Portals in v7.x which has [known and controversial event bubbling behavior](https://github.com/facebook/react/issues/11387). The links I provided above are workarounds for this behavior. I think the fix I mentioned above is pretty easy, it just needs some testing.

**Comment by jyothsnag29** [comment]
Hi @aneeshack4 
I have upgraded my sandbox office ui fabric react version to 7.77.0 and I still see the drag and drop not working with touch https://codesandbox.io/s/reactdndmultibackendcolordrop-5216c . Could you please suggest If I need to modify something. Even the branch you created not working for me(https://codesandbox.io/s/reactdndmultibackendcolordrop-6eel1)
Thank You

**Comment by aneeshack4** [comment]
@jyothsnag29 which device and OS and browser (and versions for all these) are you reproing this on? Because I tested it with touch on surface book and edge/chrome and they were fine with the new change.

**Comment by MRuimerman** [comment]
I tested it for @jyothsnag29  because I have a touch device.
I have Windows 10 (1809). I tested in on Chrome (Version 79.0.3945.88 (Official Build) (64-bit).
Drag and drop works on a normal page but inside a dialog or modal screen nothing happens. When I touch the box with my finger, nothing happens. No errors in developer tools.

**Comment by aneeshack4** [comment]
Hmm I'm not reproing this on Edge with Surface. Chrome for some reason isn't running on my Surface Book even after I re-installed it - @jdhuntington would you mind testing out https://codesandbox.io/s/reactdndmultibackendcolordrop-6eel1 on Chrome - Surface scenario for a repro?

**Comment by jyothsnag29** [comment]
Thank you @aneeshack4 for verifying.
We are not able to reproduce in Edge but for some reason its not working in Chrome and Edge Chromium. Could we re-open this issue as its not fully working in all browsers.

**Comment by jyothsnag29** [comment]
@aneeshack4 Do you have any update for me about this issue! We need this scenario to work for Chrome and Edge Chromium browsers.

**Comment by sortegamartin** [comment]
Hi, I'm also having the same problem using a drag and drog component inside a panel. On desktop it works correctly but on mobile it doesn't work. I leave the example in codesanbox and a gif of the problem:

https://codesandbox.io/s/sharp-glade-9v9be

![PanelTouchEvent](https://user-images.githubusercontent.com/33054287/73195657-87bf8c80-412e-11ea-9f3d-78a26a84f68a.gif)

**Comment by aneeshack4** [comment]
Sorry didn't see this til just now @jyothsnag29 will respond on the new issue you created (I think Github send me notifications on this one for some reason) @sortegamartin have you tried passing the `eventBubblingEnabled` prop? It should definitely work on Panel as is explained here https://github.com/OfficeDev/office-ui-fabric-react/issues/11599#issuecomment-570681054

**Comment by JasonGore** [comment]
Please note [the CodePen](https://codesandbox.io/s/sharp-glade-9v9be) @sortegamartin provided is using Fabric 6.x. We shouldn't have disparities in behavior between desktop and mobile with versions of Fabric after the merge of #11571. If we do, we should investigate them.

**Comment by sortegamartin** [comment]
I have changed the version of office ui fabric react to the last one (7.98.0) and it still doesn't work on mobile.
I am also using the layerProps = {{eventBubblingEnabled: true}} property in the panel.

You can test it in [this codesandbox](https://codesandbox.io/s/sweet-moon-3fdfy)

**Comment by aneeshack4** [comment]
@sortegamartin I see that it repros on safari and chrome on iOS with your codesandbox - this is the same issues as #12081 so I'll update that with investigation progress - please check there
