### ISSUE TITLE
Pass type to underlying TextField input

### ISSUE THREAD

**Issue by willtrking** [OfficeDev/office-ui-fabric-react#1127]
It would be nice to be able to pass a "type" prop to the underlying TextField input (say "number" to force the field to only allow numbers)

Not sure if this would break things with newer HTML5 input types like "color" or "range" however.

**Comment by dzearing** [comment]
@willtrking you can.

```tsx
<TextField defaultValue='foo' name='bar' type='number' />
```

Try it here:

http://codepen.io/dzearing/pen/ZBEVzw

**Comment by willtrking** [comment]
Awesome! Thanks!
