### ISSUE TITLE
ComboBox empty errorMessage creates whitespace

### ISSUE THREAD

**Issue by Wiklem** [OfficeDev/office-ui-fabric-react#11277]
### Environment Information

- **Package version(s)**:    "office-ui-fabric-react": "^7.56.3",
- **Browser and OS versions**: chrome 78.0

### Describe the issue:

ComboBox is rendering an empty div for errorMessage under the box, creating a space so it does not align with other components.

#### Actual behavior:

`<div role="region" aria-live="polite" aria-atomic="true" id="ComboBox91-error" class="css-180"></div>`  as seen on https://developer.microsoft.com/en-us/fabric#/controls/web/combobox#feedback

#### Expected behavior:

Hide the div if errorMessage is false or empty.

### Documentation describing expected behavior

{errorMessage && <ErrorMessage/>}

**Comment by aneeshack4** [comment]
It's not empty, the text of the error message is inside:
![image](https://user-images.githubusercontent.com/4161791/69470119-56e76380-0d49-11ea-8cef-e8386732a048.png)

**Comment by Wiklem** [comment]
> It's not empty, the text of the error message is inside:
> ![image](https://user-images.githubusercontent.com/4161791/69470119-56e76380-0d49-11ea-8cef-e8386732a048.png)

Yes, but the problem is when there is no text inside (if you inspect on of the other comboboxes, it creates spacing under the combobox) , so its hard to align with other components:
![fabric-ui](https://user-images.githubusercontent.com/3092176/69500180-29411c80-0ef9-11ea-935b-5243845c1200.png)

**Comment by micahgodbolt** [comment]
This is intentional so that any change to this div will be spoken through narrator. As a zero height item inside of the combo box, what layout problems are you having?

**Comment by Wiklem** [comment]
Thank you for fast answear.
The problem is when im using it with other components
![screenshot1320](https://user-images.githubusercontent.com/3092176/69857210-b8e72200-128f-11ea-93a6-0f09a11d495b.png)

**Comment by aneeshack4** [comment]
@Wiklem What exactly is the problem with that screenshot? It's not clear...

**Comment by Wiklem** [comment]
> @Wiklem What exactly is the problem with that screenshot? It's not clear...

I might be mistaking, but it looks like the whitespace from the div makes it "not aligned with the searchbar"

![image](https://user-images.githubusercontent.com/3092176/69994770-e4e3fb00-154e-11ea-8142-eb83241f165b.png)

**Comment by joschect** [comment]
@Wiklem The div needs to be there even if there is no text otherwise the aria-live region won't read the alert when the text changes. That being said, the alert div probably doesn't need a margin when there is no text. We'll get that removed.
