### ISSUE TITLE
Tooltip is not visible on IconButton on tabbing using Chrome browser

### ISSUE THREAD

**Issue by HarkeshS** [OfficeDev/office-ui-fabric-react#11298]
Tooltip is not visible on IconButton on tabbing using Chrome browser
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out)

### Describe the issue:

Tooltip is not visible on IconButton on tabbing using Chrome browser.

### Please provide a reproduction of the issue in a codepen:

![officefabric iconbutton](https://user-images.githubusercontent.com/53938674/69526270-d5354700-0f8f-11ea-9b38-40d27d68b613.png)

#### Actual behavior:

On tabbing, tooltip is not visible in chrome browser

#### Expected behavior:

On tabbing, tooltip should be visible in chrome browser

**Comment by micahgodbolt** [comment]
html tooltips (when you provide a button a title) aren't supposed to show on focus. This is just default HTML behavior, and why we have created our own tooltip controls. 

![image](https://user-images.githubusercontent.com/1434956/69562334-cdf84400-0f63-11ea-9e2e-e747d311e938.png)
