### ISSUE TITLE
Per-option styling for ComboBox Multiselect

### ISSUE THREAD

**Issue by JakeLunn** [OfficeDev/office-ui-fabric-react#11294]
#### Describe the feature that you would like added

Per-option styling for ComboBox Multiselect

#### What component or utility would this be added to

ComboBox

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

Currently per-option styling is supported on single-select combo boxes, but not multi-select combo boxes. Further, this is made confusing in the current documentation where it doesn't mention that this feature doesn't work for multiselect comboboxes.

Singleselect: 
![image](https://user-images.githubusercontent.com/11328029/69503858-afeaff00-0ee3-11ea-892a-a9252a84bd4c.png)

Multiselect:
![image](https://user-images.githubusercontent.com/11328029/69503870-c4c79280-0ee3-11ea-9cc6-f604fc9bd697.png)

**Comment by JakeLunn** [comment]
FYI as a workaround I made it work by using the "Selectors" property like so:
```
var option:IComboBoxOption = {
            key: mod.moduleId,
            text: mod.moduleName,
            styles: {
                root: {
                    selectors: {
                        [".ms-Checkbox-text"]: {
                          color: optionColor(mod)
                        }
                      }
                }
            }
        }
```

**Comment by khmakoto** [comment]
Hi @JakeLunn, thanks for filing this issue! I can confirm that I reproduce this and that it is a bug in the `ComboBox` component. I'll have a fix for it soon!
