### ISSUE TITLE
Dropdown open & close call back

### ISSUE THREAD

**Issue by Fadi2019** [OfficeDev/office-ui-fabric-react#11292]
#### Describe the feature that you would like added

I need a open and close callback, so a callback is called when the drop down is opened and when the dropdown is closed.

**Comment by micahgodbolt** [comment]
https://codepen.io/micahgodbolt/pen/KKKRJZm?editors=1010

there is already an onDismiss, and you can use onClick/onFocus/onKeyDown to track other interactions

**Comment by Fadi2019** [comment]
> https://codepen.io/micahgodbolt/pen/KKKRJZm?editors=1010
> 
> there is already an onDismiss, and you can use onClick/onFocus/onKeyDown to track other interactions

**Comment by khmakoto** [comment]
Hi @Fadi2019, thanks for filing this issue! I think you can achieve this via `calloutProps`/`panelProps` and `onDismiss`. I show how in [the following codepen](https://codepen.io/khmakoto/pen/MWWdNxa?&editable=true). Please let me know if there's anything non-intuitive in there!

**Comment by Fadi2019** [comment]
Hey khmakoto, helped! thx.

**Comment by khmakoto** [comment]
You're welcome @Fadi2019! Please let me know if you need help with anything else and feel free to close this issue if you don't. Thanks!
