### ISSUE TITLE
Fabric tooltip's content doesn't work with Link

### ISSUE THREAD

**Issue by sampascal** [OfficeDev/office-ui-fabric-react#11290]
### Environment Information

- **Package version(s)**: 6.208.1
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

https://codepen.io/zxpascal/pen/wvvZxeP
When you hover on the button, the link shows up, but it is not clickable. Fabric version 6.208.1. 

#### Expected behavior:

Link in the tooltip should be clickable.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by micahgodbolt** [comment]
This is probably due to the hidden layer we use to allow mouse travel between the button and the callout. We fixed this in 7. just need to backport the fix @aneeshack4

**Comment by sampascal** [comment]
Hi, can someone help backport the fix please?

**Comment by aneeshack4** [comment]
@sampascal I'm going to try to get to it this week - apologies for the delay, been focusing on accessibility issues.
