### ISSUE TITLE
CSS Modules: Choicegroup title margin incorrect

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#1130]
![image](https://cloud.githubusercontent.com/assets/1434956/23385148/f8fa7be4-fd02-11e6-8c8b-088cc8cb7be2.png)

**Comment by dzearing** [comment]
@micahgodbolt I can't repro this at all. Perhaps you could look at this if you can repro?

**Comment by micahgodbolt** [comment]
I'm taking a look

**Comment by micahgodbolt** [comment]
The difference is subtle. Seems we're using the actual Label component (which pulls in the label styles). The old implementation just used the class, but didn't pull in the Label css. So this isn't actually a bug, it's an indication that we fixed another bug :)

Closing this up. Working as intended. 

![image](https://cloud.githubusercontent.com/assets/1434956/23414664/9763da4e-fd91-11e6-9eb5-e34634345277.png)
