### ISSUE TITLE
Documentation: Localization RTL page unclear

### ISSUE THREAD

**Issue by HarryGifford** [OfficeDev/office-ui-fabric-react#11301]
### Environment Information

- **Package version(s)**: 7.64.2
- **Browser and OS versions**: Any

### Please provide a reproduction of the bug in a codepen:

Go to the docs page for [Localization](https://developer.microsoft.com/en-us/fabric#/styles/web/localization). It says to use an rtl stylesheet to enable RTL mode. It seems like this isn't supported now. Please could you update the docs to specify how this should be done now? Adding `dir="rtl"` to the html element doesn't reverse the icons on it's own. Do we need to flip the icons manually using `getRTL`?

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: (if applicable)

**Comment by khmakoto** [comment]
Hi @HarryGifford, thanks for filing this issue! I cannot reproduce this behavior in the page you suggested. If I add `dir="rtl"` to the `html` element everything is reversed correctly.

__dir="ltr"__

![image](https://user-images.githubusercontent.com/7798177/69587272-00bd2f00-0f9a-11ea-9db9-272d0016b738.png)

__dir="rtl"__

![image](https://user-images.githubusercontent.com/7798177/69587319-20545780-0f9a-11ea-9585-0a8ae8966e4b.png)

As you can see the icons are actually flipped, with the first icon being an arrow that points to the bottom right on ltr and an arrow that points to the bottom left on rtl. Can you elaborate, and maybe illustrate, how is this not working for you? Thanks!

**Comment by HarryGifford** [comment]
Sorry, I meant the documentation itself, not the website. There's no RTL CSS file any more. Can you update the documentation with the current way to handle RTL? In particular, adding `dir="rtl"` doesn't flip the icons themselves.

**Comment by micahgodbolt** [comment]
@HarryGifford seems you forgot to add the codepen.

**Comment by HarryGifford** [comment]
@micahgodbolt @khmakoto Oops, codepen: https://codepen.io/hegi/pen/RwwzwmK

**Comment by Jahnp** [comment]
Hi @HarryGifford , apologies for the confusion. This documentation applies specifically to Fabric Core, which I realize isn't clearly called out here. In order for this behavior to work, you need to include Fabric Core on your page. Here's a codepen showing how this works: https://codepen.io/jahnp/pen/MWWMqLW

It's also true that there isn't a dedicated RTL stylesheet, which Fabric Core used to have in the olden days. Instead it uses [mixins to add RTL-specific rules](https://github.com/OfficeDev/office-ui-fabric-core/blob/master/src/sass/mixins/_Directionality.Mixins.scss) for things like icon and grid-flipping.

Your scenario may not benefit from Fabric Core, though, so this may also be something of a feature gap for Fabric React. In the meantime, we'll look at updating the docs to clarify that this applies to Fabric Core.

**Comment by HarryGifford** [comment]
@Jahnp Thank you for the explanation. That's helpful to know. We're not using Fabric Core. Could we have a global function to automatically flip the icons so we don't have to have a bunch of places in our code with `getRTL() ? "BlahBlahIconRight" : "BlahBlahIconLeft"`?

**Comment by khmakoto** [comment]
@HarryGifford I'll change the documentation to reflect the current behavior and link that to this issue. I'll also create a separate issue to track the feature request for a global function.
