### ISSUE TITLE
Combobox: Drop down icon is replaced by ... in disabled combobox

### ISSUE THREAD

**Issue by tabansal** [OfficeDev/office-ui-fabric-react#11319]
When we use comboBox in disabled state the drop down caret is replaced by three dots (...). 

![image](https://user-images.githubusercontent.com/49181832/69695089-139e4380-1101-11ea-80c5-244f7e87d2c6.png)

We should display drop down caret even when it's disabled

**Comment by khmakoto** [comment]
Hi @tabansal, thanks for filing this issue! I can confirm that I can reproduce it on [the Fabric website](https://developer.microsoft.com/en-us/fabric#/controls/web/combobox). @joschect do you know if this is by design or if it is something we need to change?

**Comment by micahgodbolt** [comment]
i was curious about this as well. Seems to be because of text-overflow and something causing the root to overflow.

**Comment by tabansal** [comment]
I think, this is caused due to change in position property. For enabled drop down, the button is absolute positioned. But in case of disabled one, it's relative causing it to be displayed out of bound.

**Comment by joschect** [comment]
@khmakoto I don't believe that this is intended behavior. @tabansal appears to be correct, the disabled button doesn't have `position: absolute` even though it is in [its styling](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.styles.ts#L188-L243) For some reason it looks like the root styles aren't applied when the disabled styles are.
