### ISSUE TITLE
Narrator is reading "Editable" for non editable fields in the grid For DetailList control

### ISSUE THREAD

**Issue by GayatriDeviP** [OfficeDev/office-ui-fabric-react#11312]
**Describe the issue:**
![image](https://user-images.githubusercontent.com/58205918/69606758-b3989600-1049-11ea-8db8-e85892e6712e.png)

Narrator is reading columns as "Editable" for non editable fields in the grid for DetailList control. Provided the codepen url to repro the issue. To repro the issue, 
1. Start Narrator
2. Just expand the row :Color Red
3. Go to scan mode (Caps Lock + Right Arrow) 
4. Verify Narrator is reading Editable for each and every field in the grid 
**Note**: Working fine with NVDA

Please provide a reproduction of the issue in a codepen:
https://codepen.io/GayatriDeviP/pen/MWWMKqW

Actual behavior:
Narrator is reading the non editable fields as Editable  

Expected behavior:
Narrator shouldn't read the non editable columns as Editable

**Comment by khmakoto** [comment]
Hi @GayatriDeviP, I can confirm that I can reproduce this issue from your codepen. I'll work on a fix as soon as I can. Thanks!

**Comment by GayatriDeviP** [comment]
Hi @khmakoto, If we add “aria-readonly="true"” to the column div, the issue will resolve. As we don’t have provision to add that, I raised bug to you.
