### ISSUE TITLE
Contextual Menu can't be closed by Escape

### ISSUE THREAD

**Issue by KarynaLisniak12** [OfficeDev/office-ui-fabric-react#11313]
### Environment Information

- **Package version(s)**: office-ui-fabric-react 7.54.1
- **Browser and OS versions**: Version 78.0.3904.108 (Official Build) (64-bit)

### Describe the issue:

Contextual Menu can't be escaped out of when using keyboard navigation.

### Please provide a reproduction of the issue in a codepen:

Codepen to repro the issue: https://codepen.io/karynalisniak12/pen/ExxByQM

#### Actual behavior:

After Escape button was closed the Context Menu doesn't close.

#### Expected behavior:

The Context Menu can be closed by Escape button.

**Comment by micahgodbolt** [comment]
There was a bug for a few releases where this happened. It has since been fixed. Please upgrade to a newer version of Fabric.
