### ISSUE TITLE
[Keyboard Navigation - PipelineBuilderUX - logs] Keyboard focus moves twice on same control under 'Logs' tab.

### ISSUE THREAD

**Issue by sonimishra** [OfficeDev/office-ui-fabric-react#11321]
**User Experience:**
If keyboard focus moves twice on any section and functionality is same in both condition then it will increase one extra step to any user who depends upon keyboard.

**Repro-Steps:**
1. Open URL: https://master.ml.azure.com/pipelineruns/b416f0a6-d9b9-410d-854b-49f33a5970a6/graph?&wsid=/subscriptions/ee85ed72-2b26-48f6-a0e8-cb5bcf98fbd9/resourcegroups/MT/workspaces/zhanxiaAML&flight=all 
2. Pipeline run page will open.
3. Select any modal like(Import data, Split data etc.).
4. New pane will open. Now navigate to logs tab item and select it.
5. Navigate all 'expand collapse' button controls on 'Logs' tab.
6. Verify whether keyboard focus moves twice on all expand/collapse button(azureml-logs, logs, azureml) or not.

**Actual Result:**
Keyboard focus moves twice on all expand/collapse button(azureml-logs, logs, azureml) under 'Logs' tab and functionality is same for both condition.

**Expected Result:**
Keyboard focus should not move twice on all expand/collapse button(azureml-logs, logs, azureml) under 'Logs' tab, it should move only once at button controls.

**Note:**
1. Same issue exists under Chrome.

**MAS References:**
[MAS 2.4.3 - Focus Order](https://microsoft.sharepoint.com/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={0de7fbe1-ad7e-48e5-bcbb-8d986691e2b9})

Accessibility Insights! - Identify accessibility bugs before check-in and make bug fixing faster and easier.

**External Bug Process:** If this bug belongs to external team, mark it as resolved/done and assign it back to the tester with notes on where to file/route the bug. For more information please use this Link.
![MAS2 4 3_Logs tab](https://user-images.githubusercontent.com/30456910/69710870-25dea880-1126-11ea-9f38-7e49c624c552.jpg)

[MAS2.4.3_Logs_focus moves twice on same control.zip](https://github.com/OfficeDev/office-ui-fabric-react/files/3896090/MAS2.4.3_Logs_focus.moves.twice.on.same.control.zip)

**Comment by khmakoto** [comment]
Hi @sonimishra , I think what you're logging is an application bug that needs to be investigated by someone from the Azure Machine Learning studio team since it is not clear if this is indeed a Fabric bug. Please contact that team first and, if it is indeed a Fabric issue then we can start working on it. An isolated instance of this bug in a codepen would also help. Thanks!

**Comment by sonimishra** [comment]
We have discussed this issue with our accessibility SME Sarah Higley and after confirmation we have created bug for here.
Please let us know if you need any additional information.

**Comment by khmakoto** [comment]
Hi @sonimishra I can't access the page you're linking at all. It would be great if you could attach an isolated example of the issue you're facing in a codepen. Thanks!
