### ISSUE TITLE
MaskedTextField: non 'onChange enducing' keys presses moves cursor position to end

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#11323]
"put focus in masked text field, press 'g' twice, return focus, press 'backspace' twice"

When I dug into the bug: Keystrokes that don't change the input eventually stop  causing an onchange and browser moves focus to the end of the input.

![masked](https://user-images.githubusercontent.com/1434956/69746739-cb2f5780-10f9-11ea-85d8-b844bc16734f.gif)

**Comment by micahgodbolt** [comment]
@lambertwang are you still involved with this control? Are you familiar with this issue, or have thoughts?

**Comment by xugao** [comment]
@micahgodbolt - this is a default behavior from native input html element. this happens when `value` remains unchanged `onChange`. m not sure why it's this way though. see [my pen](https://codepen.io/xugao/pen/XWbXwPr)
