### ISSUE TITLE
In office fabric version 7.55.0 ESC is not working when command bar is opened.It worked in version 6.162.1

### ISSUE THREAD

**Issue by Sandhya-aluri** [OfficeDev/office-ui-fabric-react#11330]
### Environment Information 

- **Package version(s)**: office-ui-fabric-react- 7.55.0
- **Browser and OS versions**: Chrome and IE

### Describe the issue:
In office fabric version 7.55.0 ESC is not working when command bar is opened.It worked in version 6.162.1

#### Expected behavior:Open the Command bar  and press ESC or Alt+up arrow from keyboard,it should be closed.
<img width="923" alt="office fabric version ~6 162 1 " src="https://user-images.githubusercontent.com/48669559/69777928-58d97880-11c8-11ea-9c18-e9042bd73514.png">
<img width="912" alt="office fabric version ~7 55 0" src="https://user-images.githubusercontent.com/48669559/69777929-59720f00-11c8-11ea-85f7-e99753bdb7d3.PNG">

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by khmakoto** [comment]
Hi @Sandhya-aluri, thanks for filing this issue! Could you provide an isolated reproduction in a codepen? Because I'm not seeing this behavior in the `CommandBar` page in our website as you can see below:

![CommandBar](https://user-images.githubusercontent.com/7798177/69978973-3dc97a00-14e2-11ea-9162-9673d1fd2a81.gif)

**Comment by micahgodbolt** [comment]
this was resolved in #11087. Upgrade to v7.58.0

**Comment by Sandhya-aluri** [comment]
please confirm the below 
1. is this version accessibility compliant ?
2. is there any impact to other fabric controls ?

**Comment by Sandhya-aluri** [comment]
Worked with version update. Thank you. Closing the issue.
