### ISSUE TITLE
Server-side rendering styles loader 

### ISSUE THREAD

**Issue by tomaszbajor** [OfficeDev/office-ui-fabric-react#11335]
Hi,

I've tried to use Fabric styles loader to store styles in a variable that will be injected into a page but looks like no classes are generated on server side. I'm using the implementation in boot-server.tsx is as described in wiki.

```
import { configureLoadStyles } from '@microsoft/load-themed-styles';

// Store registered styles in a variable used later for injection.
let allStyles: string[] = [];

// Push styles into variables for injecting later.
configureLoadStyles((styles: string) => {
    allStyles.push(styles);
    });

params.domainTasks.then(() => {
   const body = renderToString(app);
   resolve({
       html: `<style>${allStyles.join('')}</style>${body}`,
       globals: {
            initialReduxState: store.getState(),
            translations: params.data.translations,
            config: params.data.config
        }
    });
}, reject);
```

#### Actual behavior:
- `allStyles` array is empty on server-side
- styles are rendered on client side and applied

#### Expected behavior:
- `allStyles` array contains generated classes on server-side

### Environment Information
.NET Core 2.2 application
`"webpack": "2.5.1",`
`"react": "^16.8.1",`
`"office-ui-fabric-react": "7.65.1"`

Thanks in advance.

**Comment by dzearing** [comment]
Terribly sorry; the SSR wiki has been out of date for some time. I've updated it a bit to reflect the current state. Can you read it and give feedback? I've also made a codesandbox to illustrate.

https://github.com/OfficeDev/office-ui-fabric-react/wiki/Server-side-rendering-and-browserless-testing

https://codesandbox.io/s/dazzling-montalcini-kv9bz

**Comment by tomaszbajor** [comment]
Hi,

thanks for great support. I have applied the changes described in wiki but unfortunately the `css` variable is still empty. I'm using .netcore 2.2 react application template and commonjs module resolution. The code after changes:

```
export default createServerRenderer(params => {
    return new Promise<RenderResult>((resolve, reject) => {
        try {
	    //server side state rendered here - not relevant for the case
	    const store = {};
			
            const routerContext: any = {};
            const App = () => {
                return <Provider store={store}>
                    <StaticRouter basename={basename} context={routerContext} location={params.location.path} children={routes} />
                </Provider>
            };
            
            params.domainTasks.then(() => {
                const { html, css } = renderStatic(() => ReactDOM.renderToString(
                    <Fabric>
                        <App/>
                    </Fabric>
                ));
                console.log("FABRIC_CSS:", css); //in ASP.NET Core Web Server output variable is empty
                resolve({
                    html: html,
                    globals: {
                        initialReduxState: store.getState(),
                        translations: params.data.translations,
                        config: params.data.config
                    }
                });
            }, reject);
        }
        catch (e) {
            reject(e);
        }
    });
});
```

I would be gratefull for any suggestions what could solve the issue.

**Comment by khmakoto** [comment]
@dzearing could you help here? Thanks!

**Comment by alekkowalczyk** [comment]
Hi, I'm working together with @tomaszbajor on the same project, tried an even more simplified version in the `boot-server.tsx` file used by the ASP.NET Core+React template, to rule out any issues on our site, so something like:

```
export default createServerRenderer(params => {
    return new Promise<RenderResult>((resolve, reject) => {
            const App = () => {
                return <Fabric>
                              //.. exactly same content as in the provided sample - https://codesandbox.io/s/lucid-smoke-1ghgk
                       </Fabric>
            };
            
            const { html, css } = renderStatic(() => ReactDOM.renderToString(<App />));
            console.log("css", css, "html", html);
    });
});
```

`html` is set as expected, but `css` is empty, looks like it works just in the browser, not in the node.js server environment.

**Comment by khmakoto** [comment]
Hi @alekkowalcyc, can you maybe share a github project with a minified repro of what you're experiencing so that I can try it? Thanks!
