### ISSUE TITLE
FocusZoneDirection.domOrder will break handleTabKey

### ISSUE THREAD

**Issue by Anschur** [OfficeDev/office-ui-fabric-react#11336]
In the FocusZone component I can use handleTabKey to get it to also control tab key actions. There is also direction attribute to control the direction of the arrow keys. These don't seem to affect each other with one exception: If I set direction={FocusZoneDirection.domOrder}, the arrow keys will follow the dom order int he same way as tab would usually do. But tab will no longer navigate inside the FocusZone.

### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: Chrome

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/svartn/pen/pooMZzE

#### Actual behavior:

Tab will not move between the list items when direction={FocusZoneDirection.domOrder}

#### Expected behavior:

Tab will not move between the list items in the same way as arrowign does.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by khmakoto** [comment]
Hi @Anschur, thanks for filing this issue! I can confirm that I can reproduce this behavior. @JasonGore do you know if this is by design? It looks like a bug to me but I don't want to rush a fix if it is intended to work this way.

**Comment by JasonGore** [comment]
If this is behaving by design, I'm not sure what the reasoning would be. Hopefully @dzearing can chime in.
