### ISSUE TITLE
Normal People Picker does not show up the generic text typed in input box

### ISSUE THREAD

**Issue by radhikakhetan** [OfficeDev/office-ui-fabric-react#11333]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior: The typed text in input field does not come up as a generic item in the picker

![image](https://user-images.githubusercontent.com/13445664/69782611-8aa60b80-11d7-11ea-9347-7380694fcca9.png)

#### Expected behavior:

![image](https://user-images.githubusercontent.com/13445664/69782531-50d50500-11d7-11ea-86b2-d1f48aad2943.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? NO

Requested priority: Blocking

Products/sites affected: (if applicable)

**Comment by khmakoto** [comment]
Hi @radhikakhetan, thank you for filing this issue! You can achieve this behavior via the use of the `noResultsFoundText` of the `suggestionsProp`:

![image](https://user-images.githubusercontent.com/7798177/69986896-2a72da80-14f3-11ea-9509-6d2b53af50f3.png)

![image](https://user-images.githubusercontent.com/7798177/69986899-2ba40780-14f3-11ea-80ab-9c0fc566ff7a.png)

You can check this behavior in the codepen [here](https://codepen.io/khmakoto/pen/QWwWQWx?&editable=true).

**Comment by radhikakhetan** [comment]
@khmakoto Thanks for replying. I tried this but what I see is a plain text which is not clickable. Can we make it clickable and also which event handler is called when this 'Use this name: ' option is clicked ?

**Comment by khmakoto** [comment]
Hi @radhikakhetan the text is not clickable, I was using the `Enter` key to input that option. Let me check if I can add click functionality and I'll come back to you.

**Comment by khmakoto** [comment]
Hi @radhikakhetan, I've updated the codepen with how this could be done, notice the use of `showForceResolve` and `forceResolveText` in the [codepen](https://codepen.io/khmakoto/pen/QWwWQWx?editors=0010).
