### ISSUE TITLE
Configurable Grid System Layout

### ISSUE THREAD

**Issue by DuncanFisher** [OfficeDev/office-ui-fabric-react#11334]
#### Describe the feature that you would like added

Office UI Grid classes are awesome, it allows easy implementations of Responsive grids but sometimes we need a little more than 12 columns with 1 unit space.

Using the ScrollablePane I was thinking on using the grid structure to display a large dataset of custom components (not a ListItems) and would need up to 38 columns.

Since the grid classes allows to match the columns easily, having a class that could allow to stact 12, 24, 36, 48 columns would be a plus for large information structures on ScrollablePanes.

#### What component or utility would this be added to

Office UI Fabric ms-grid classes.

#### Have you discussed this feature with our team, and if so, who

No.

#### Additional context/screenshots

I'm building a Calendar-like view of projects that will need a monthly view in tabular form.
I could do a <table/> but using the Div with the ms-grid classes is way easier and customizable as I can add custom, different rows to show "parent" row details.

**Comment by khmakoto** [comment]
Hi @DuncanFisher, this seems like a feature request that needs to be discussed with the team, I'll start a conversation internally and comment on what we decide on here.

**Comment by DuncanFisher** [comment]
Thank you

A segunda, 2 de dez de 2019, 20:49, Makoto Morimoto <
notifications@github.com> escreveu:

**Comment by Jahnp** [comment]
Hi @DuncanFisher , thanks for the request. First thing to note is that based on your description, it sounds like this applies to [Fabric Core](https://github.com/OfficeDev/office-ui-fabric-core/), not Fabric React (this repo). Unless there's a corresponding request for Fabric React, to better track this request, I'd suggest re-opening this issue there.

Second: We totally hear you on the use case for this kind of behavior. But unfortunately, we don't currently have plans for expanding Fabric Core's Grid functionality. However, you *can* nest grids within cells to create nested layouts that should come close to the behavior you're asking for.

Here's a simple example of what that could look like: https://codepen.io/jahnp/pen/qBEBYeE?editors=1100

**Comment by DuncanFisher** [comment]
I've seen the example, but I think you missed the point.
The issue is that the styles on the parent will fit the viewport the same, additionally rendering in nested grids for each row is a code nightmare.

The main idea underlying this request is to provide a way to overflow columns horizontally in scrollpanes so we can make use of the horizontal overflow to show large datasets without worrying too much about screensize too much.
