### ISSUE TITLE
In office fabric version 7.55.0  getting ARIA attribute is not allowed: aria-orientation="horizontal"​ in fast pass of accessibility insights. These are not listed in office fabric version 6.162.1

### ISSUE THREAD

**Issue by Sandhya-aluri** [OfficeDev/office-ui-fabric-react#11331]
### Environment Information

- **Package version(s)**: office-ui-fabric-react- 7.55.0
- **Browser and OS versions**: Chrome

### Describe the issue:
In office fabric version 7.55.0  getting ARIA attribute is not allowed: aria-orientation="horizontal"​ in fast pass of accessibility insights. These are not listed in office fabric version 6.162.1.

#### Actual behavior:
Getting ARIA attribute is not allowed: aria-orientation="horizontal"​ issues in fast pass of accessibility insights in the pages in 7.55.0 version. These are not listed in office fabric version 6.162.1

#### Expected behavior:
Getting ARIA attribute is not allowed: aria-orientation="horizontal"​ issues in fast pass of accessibility insights in the pages in 7.55.0 version, which should not be listed.
<img width="916" alt="accessibility fast pass in version 7 55 0" src="https://user-images.githubusercontent.com/48669559/69778394-26c91600-11ca-11ea-85ac-951271fe2ab0.PNG">

**Comment by khmakoto** [comment]
Hi @Sandhya-aluri, in which pages are you getting this `aria-orientation="horizontal"` error? Also, isn't this the same bug you filed in #11318?

**Comment by Sandhya-aluri** [comment]
i am getting the above error in all the pages as it is coming in the menu bar and command bar of office fabric controls of version 7.55(which are the common controls in all the pages).

**Comment by khmakoto** [comment]
Hi @Sandhya-aluri, please check my response in #11318 to see if it helps your case. Thanks!

**Comment by Sandhya-aluri** [comment]
in #11318 as you said role="presentation" will not support aria-orientation="horizontal", but that role comes with office fabric command bar control. we are using the control as below : 
import { CommandBar } from 'office-ui-fabric-react';
<CommandBar farItems={this.headerRightItems("username")} />

This issue only comes in 7.55 version of fabric. same piece of code works fine without issue in 6.162.1 version.

**Comment by Sandhya-aluri** [comment]
headerRightItems = (name) => {
        return [
            {
                key: "user-dropdown",
                name: name,
                iconProps: {
                    iconName: 'FollowUser'
                }
    }

**Comment by khmakoto** [comment]
Hi @Sandhya-aluri I've confirmed this issue on the version you've specified. This issue was fixed in Fabric version 7.64.2 (PR #11224), so please upgrade to that version or a later one for this problem to go away.

Please let me know if you need anything else, thanks!

**Comment by Sandhya-aluri** [comment]
Done version update solved aria-orientation=hotizontal issue. but getting other issues with the same command bar control. i.e 
aria-required-children: Certain ARIA roles must contain particular children. Please find the screen shot attached. 

<img width="917" alt="fast pass version 7 64 2" src="https://user-images.githubusercontent.com/48669559/70299083-de3cd880-1819-11ea-9ccb-ad6c5d9903d2.PNG">

**Comment by khmakoto** [comment]
Hi @Sandhya-aluri, it's great to hear that the issue has been resolved! In order to not get lost in context here could you file a new bug for the other issues you're encountering and close this one? Thanks!
