### ISSUE TITLE
Feature: Underlined prop to ComboBox and Dropdown components

### ISSUE THREAD

**Issue by jekaspekas** [OfficeDev/office-ui-fabric-react#11345]
#### Describe the feature that you would like added

Underlined prop to ComboBox and Dropdown components

#### What component or utility would this be added to

ComboBox and Dropdown

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

Location underlined and not underlined elements close does not look good. For example DatePicker component can be underlined.

**Comment by xugao** [comment]
#10694

**Comment by xugao** [comment]
Thank you for your feedback @jekaspekas . We have this feature in our backlog. I am checking on its progress/timeline. Pls do let me know how urgently you need this feature by.
