### ISSUE TITLE
Can I render Overlay above a Dialog?

### ISSUE THREAD

**Issue by gfafei** [OfficeDev/office-ui-fabric-react#11342]
For _how-to_ questions and other non-bugs, please use StackOverflow instead of Github issues. You can tag your questions with [office-ui-fabric](https://stackoverflow.com/questions/tagged/office-ui-fabric).

If you are a Microsoft employee you can also join the Microsoft UI Fabric teams channel.

I want to render a overlay to show a spinner above the Dialog, but not working. Why?

**Comment by jdhuntington** [comment]
Hi @gfafei - Are you able to share a sample of the code that's not working on codepen.io? Thanks!

**Comment by gfafei** [comment]
Actually, it's working, but spiner was covered by the overlay of dialog. I want the dialog to be covered.

https://codepen.io/gfafei/pen/zYxYmpx

**Comment by micahgodbolt** [comment]
@gfafei are you still having issues, or is this resolved?

**Comment by gfafei** [comment]
Maybe it's designed that nothing appears above overlay. I'm going to try another UI framework.Thank you.
