### ISSUE TITLE
Does DetailsList expose a callback to add more items to the list(pagination)

### ISSUE THREAD

**Issue by shyama1208** [OfficeDev/office-ui-fabric-react#11340]
I have a scenario where there are total of 150 items that we want to render, but server returns set of items - say 30 at a time.
We want to use DetailsList however, we did not find any prop that can be used to update(add to) the list of items when user scrolls to the bottom of present list.

I see that DetailsList handles UI virtualization , however it seems we need to pass the entire set of items at the beginning only.

**Comment by khmakoto** [comment]
@shyama1208 thanks for filing this issue! I don't think there's support for pagination baked in to the `DetailsList` component. @KevinTCoughlin or @dzearing can confirm.

There is an example, however, of how to use a `Shimmer` on the `DetailsList` component to provide a loading scenario while data is being retrieved from the server that you can find [here](https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/shimmer).
