### ISSUE TITLE
DefaultButton's primary attribute doesn't work on SPFx 1.8.0 and above

### ISSUE THREAD

**Issue by abhishek-raj** [OfficeDev/office-ui-fabric-react#11356]
### Environment Information

- **Package version(s)**: 6.189.2
- **Browser and OS versions**: Edge Dev 80.0.334.4 on Windows 10 1909 Build 18363.476

### Describe the issue:

When I am trying to use the `DefaultButton` in a SPFx webpart with `primary` atrribute set as `true` then it's not working. The button doesn't have primary color.
It might be as SPFx tries to scope the CSS between the webparts it doesn't load the CSS for Fabric UI in some cases. This code below might be the reason. It seems to be referring to a specific classname instead of applying styles using JS which might not work.
https://github.com/OfficeDev/office-ui-fabric-react/blob/34c2785efba9f52609bc80cca77a6d37d1d43ae3/packages/office-ui-fabric-react/src/components/Button/DefaultButton/DefaultButton.tsx#L23

#### Actual behavior:

`<DefaultButton primary />` doesn't have primary color.
#### Expected behavior:

`<DefaultButton primary />` should have primary color.

**Comment by xugao** [comment]
@abhishek-raj, I couldn't repro this in codesandbox: https://codesandbox.io/s/react-ts-kbkj3?fontsize=14&hidenavigation=1&theme=dark. Could you pls send me a minimal repro?

**Comment by abhishek-raj** [comment]
@xugao I have created a minimal repro here: https://github.com/abhishek-raj/UIFabricRepro1

This is the main file where the buttons are used: https://github.com/abhishek-raj/UIFabricRepro1/blob/master/src/webparts/helloWorld/components/HelloWorld.tsx#L20

I am unable to repro this in the local workbench but whenever I try to use the webpart in a Sharepoint Page, it doesn't have the primary color when DefaultButton  `primary` attribute is set but PrimaryButton works.

Here is a snapshot of the webpart(the second button is the DefaultButton with `primary` attribute and the third button is the PrimaryButton which has the correct color)
![image](https://user-images.githubusercontent.com/8985497/70142191-b08f4c80-16be-11ea-8ff7-8c3201087bfa.png)

**Comment by xugao** [comment]
@abhishek-raj , could you check something in your case of repro.
If you open the codesandbox link i sent above and inspect the 2 buttons:
![image](https://user-images.githubusercontent.com/1207059/70172501-a8ff8180-1685-11ea-8dd7-9c6f73abafc3.png)

As you can see they have the same classnames and hence the same styling. the `root--*` class gives the background color. Could you inspect your repro & non-repro buttons and see what differences are in styling? also does it repro if you use a higher version of Fabric 6 or Fabric 7?

**Comment by abhishek-raj** [comment]
@xugao I checked and the root-* are different. Repro(DefaultButton with primary set) is having root-192 and PrimaryButton is having root-200.

![image](https://user-images.githubusercontent.com/8985497/70229989-5c976d00-177d-11ea-8d25-227123a0f982.png)

**Comment by abhishek-raj** [comment]
I updated office-ui-fabric-react package to 6.210.5 and I am still seeing the issue.
I tried version 7.69.0 and it also has the issue.

I also checked that the DefaultButton with primary set and not set has different root-* too.
![image](https://user-images.githubusercontent.com/8985497/70232716-0c230e00-1783-11ea-8f31-70a059df2d1f.png)

**Comment by xugao** [comment]
@abhishek-raj - thanks for checking. could you also share in the repro case, which class is providing the wrong `backgroundColor`? in the non-repro case, `root-*` is the one setting the `backgroundColor` for the button.

**Comment by abhishek-raj** [comment]
@xugao I checked and the other `root-*`(`root-220` in this case) is providing the wrong `backgroundColor`.

Note: I had updated the office-ui-fabric-react to version 7.69.0 in this screenshot and that is why the root-* classes are different in this screenshot than the above ones.
![image](https://user-images.githubusercontent.com/8985497/70295487-33262200-180d-11ea-8a24-0d179bdd4ff3.png)

**Comment by xugao** [comment]
This is where the styles are defined for both ways of doing primary buttons:
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Button/ButtonThemes.ts#L154

The only "possible" way I can think of, which can make this happen is with `Customizer` and `ScopeSettings`. However i actually **can't** make it work: https://codepen.io/xugao/pen/PowPbvj

@abhishek-raj , just to confirm, you are not blocked on anything since you can just use `PrimaryButton`, correct?

@khmakoto , do you have any idea what can cause this?

**Comment by khmakoto** [comment]
Hi @abhishek-raj, is there any way this could be happening because the Sharepoint page is providing scoped customizations specifically to the DefaultButton and PrimaryButton variants that might be messing the styling here? Like @xugao said, I think this could be the only reason why this may be happening, especially if you've already tried with the latest version of Fabric.

**Comment by abhishek-raj** [comment]
@khmakoto @xugao Seems like this is a issue with Sharepoint specifically. I will add a issue there then. Thanks for the help. :)

**Comment by khmakoto** [comment]
@abhishek-raj thanks for checking if this was a Sharepoint issue! If there's anything else we can help with let us know, otherwise feel free to close this issue. Thanks again!
