### ISSUE TITLE
Primary buttons are smaller normal buttons because they have no border

### ISSUE THREAD

**Issue by johannes-z** [OfficeDev/office-ui-fabric-react#11355]
### Environment Information

- **Package version(s)**: latest commit 34c2785efba9f52609bc80cca77a6d37d1d43ae3
- **Browser and OS versions**: -

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/johannes-z/pen/QWwWXeE

#### Actual behavior:

Even though both compound buttons have the same content, their size is different, because the primary button has `border: none`, instead of setting the `borderColor` to `primaryButtonBackground`.

This is the line where this issues occurs: https://github.com/OfficeDev/office-ui-fabric-react/blob/34c2785efba9f52609bc80cca77a6d37d1d43ae3/packages/office-ui-fabric-react/src/components/Button/ButtonThemes.ts#L156

#### Expected behavior:

Both buttons should be the same size.

The line should read:

```ts
border: `1px solid ${s.primaryButtonBackground}`
```

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes - *I think this applies to all normal/primary button styles though*.

Requested priority: Low

Products/sites affected: (if applicable)

**Comment by xugao** [comment]
Thanks for reporting, @johannes-z ! I will look into fixing

**Comment by johannes-z** [comment]
I actually was thinking about this some more. the border color also has to change if the button is in a hover or checked state.
