### ISSUE TITLE
GroupedList - Default getGroupHeight ignores collapsed children, causes render issue

### ISSUE THREAD

**Issue by marwankhalili** [OfficeDev/office-ui-fabric-react#11359]
### Environment Information

- **Package version(s)**: `office-ui-fabric-react@7.68.0`

### Please provide a reproduction of the bug in a codepen:

The group height is miscalculated in GroupedList if the provided group is not collapsed but has children that are collapsed. This causes a rendering issue, see the following codepen example:
https://codepen.io/marwankhalili/pen/VwYYjWX

#### Actual behavior:
Expanding a group on level 0 with collapsed children causes issues with the virtualization / scrolling and subsequent groups on level 0 will not to be displayed.

#### Expected behavior:
Expanding a group on level 0 with collapsed children displays subsequent groups on level 0 if there is enough space. The scrolling / virtualization should end where the last item or collapsed group is displayed.

This can be fixed by providing a custom getGroupHeight function to the DetailsList / GroupedList. In the codepen example above [(link)](https://codepen.io/marwankhalili/pen/VwYYjWX), uncomment line 19 to see the expected behavior.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by xugao** [comment]
@marwankhalili - thanks a lot for contributing fix. i was the PR was unfinished due tot perf implications. do you have any update on this issue?

**Comment by marwankhalili** [comment]
@xugao  Hi! Unfortunately I have not had the time to fix perf implications in the PR. Hoping that someone else is able to fix this eventually.
