### ISSUE TITLE
Webpack `production ` mode packaging error

### ISSUE THREAD

**Issue by wang1212** [OfficeDev/office-ui-fabric-react#11354]
### Environment Information

- **Package version(s)**: 7.65.0
- **Browser and OS versions**: Chrome Dev 80.0/Windows 10

When using webpack for packaging, the `mode` in the configuration file is set to `production`, the packaging process is successfully completed, but the console reports an error when browsing the page:

`Cannot read property 'call' of undefined.`

However, when `mode` is set to `development`, everything works fine.

I used many other libraries such as React, React-Router, Redux, Lodash, etc. At first I thought it was a problem with Webpack or a library, and then I found that as long as the package does not include the code files related to `office-ui-fabric-react` (Even if it contains a file that only uses the `Stack` component), everything works fine.

**Comment by xugao** [comment]
@wang1212 , please send me a minimal repro in order for me to help :)

**Comment by wang1212** [comment]
Sorry, when I tried to build the minimized example, I found that the problem disappeared. It should not be a problem with `office-ui-fabric-react`. It may be caused by a plugin in the webpack configuration file.
