### ISSUE TITLE
Debounce for Textfield

### ISSUE THREAD

**Issue by rgurusankar** [OfficeDev/office-ui-fabric-react#11369]
Hi,

I am not able to add debounce functionality to the textfield. It does not give me the latest value user is entering in the text field

### Environment Information

- **Package version(s)**: 7.37.0
- **Browser and OS versions**: Windows 10, Chrome 78.0.3904.108 (Official Build) (64-bit)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by laiprorus** [comment]
@rgurusankar could you provide an example of what you are trying achieve? I have used onGetErrorMessage prop together with deferredValidationTime to limit the amount of onChange being fired. onGetErrorMessage gives you same value as onChange but only after deferredValidationTime milliseconds (default 200) have passed after last user input.

**Comment by xugao** [comment]
@rgurusankar , pls provide a codepen for the repro. i think the bug is most likely in your debouncing implementation rather than the component itself
