### ISSUE TITLE
TextField with character count

### ISSUE THREAD

**Issue by sonofsupersonicman** [OfficeDev/office-ui-fabric-react#11364]
#### Describe the feature that you would like added

TextField with a character count such as "500 characters left" that is decremented as the user types.

#### What component or utility would this be added to

TextField

#### Have you discussed this feature with our team, and if so, who

No

**Comment by xugao** [comment]
@sonofsupersonicman - Thank you for your feedback! 
this will be something the component users should implement on top of component. For instance, you would create a `TextFieldWithCharCount` component in your code which renders our `TextField` and the label for the char count. This variation is not suitable for the Fabric component to handle.

**Comment by laiprorus** [comment]
Here an example https://codepen.io/laiprorus/pen/jOEEQxO

**Comment by xugao** [comment]
@laiprorus - sorry for the delayed reply and thanks for the example. This is not a textfield variant we will support moving forward, especially given it's very easy to implement on your own using existing interface. Do let me know if you have further concern :)
