### ISSUE TITLE
DatePicker Format Issue

### ISSUE THREAD

**Issue by chriskim2311** [OfficeDev/office-ui-fabric-react#11363]
### Environment Information

- **Package version(s)**:  7.63.0
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:
            <DatePicker
                className={}
                label="Start Date:"
                isMonthPickerVisible={false}
                maxDate={}
                minDate={}
                today={}
                value={}
                showGoToToday={false}
                onSelectDate={}
                }}
            />

For the date picker that we are using it renders the datepicker dates all in line. Not in the correct format of the month. Its a single column with all the dates for the month in that column running vertically down.

#### Expected behavior:

Render the rows of dates correctly inline not vertically.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No
Requested priority: (Blocking, High, Normal, Low)
High/Normal

Products/sites affected: (if applicable)
Edge Product Development team/ edgeteam.ms

**Comment by xugao** [comment]
@chriskim2311 - could you pls provide a codepen for the repro case? thanks!

**Comment by chriskim2311** [comment]
@xugao Anyway we can connect on teams and I can show you some screenshots I have a lot of custom variables being sent to the date picker? I have the same use case of code working on a different dashboard but not on particular one for some reason.

**Comment by xugao** [comment]
@chriskim2311, happy to connect. are you MSFT employee? 
however, before that, here are some steps you can try and can be very helpful:
1. try see if you can create a repro in codepen with the same props you passed in your repro case
2. if #1 doesn't repro with, try compare the styles between repro vs non-repro cases to see if it's any styles from your app is affecting/overriding the styles of the Fabric component

**Comment by chriskim2311** [comment]
@xugao thank you! I am a contractor at Microsoft. My alias is “v-chrkim“ can you send me a message on teams and I can send you some screenshots. I can’t get it to repro on codepen

**Comment by xugao** [comment]
sync'ed with @chriskim2311 - this is caused by host app styles applied on table elements. He is going to fix this from the app side
