### ISSUE TITLE
CommandBar item.disabled still allows focus on disabled menu items

### ISSUE THREAD

**Issue by Pangamma** [OfficeDev/office-ui-fabric-react#11372]
Environment Information
Package version(s): 7.9.0
Browser and OS versions: Chrome 75 & Firefox 68, Windows 10 1903
Please provide a reproduction of the bug in a codepen:
Codepen: https://codepen.io/pangamma/pen/xxbbvdz

Actual behavior:
Disabled elements should not be focusable using arrow keys or tab or keyboard

Regular fabric shows this issue

Expected behavior:
Disabled items should not allow focusing. You should not be able to focus on disabled items. 

Priorities and help requested:
Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Microsoft meeting rooms

---------------------
![image](https://user-images.githubusercontent.com/1046026/70168998-c4b35980-167e-11ea-9f2f-3997154af0b3.png)
![image](https://user-images.githubusercontent.com/1046026/70169146-14922080-167f-11ea-8fe6-419e0e976b1e.png)
![image](https://user-images.githubusercontent.com/1046026/70169105-017f5080-167f-11ea-8209-b817ad7e5488.png)

**Comment by xugao** [comment]
@Pangamma - I checked your codepen and it's working as expected. I also double checked it does have the correct aria attribute:
![image](https://user-images.githubusercontent.com/1207059/70173211-3ee7dc00-1687-11ea-9f75-9bb657b18d65.png)

In your case of repro, do you see the `aria-disabled="true"` attribute on the disabled item?
