### ISSUE TITLE
SpinButton: Include `placeholder` attr

### ISSUE THREAD

**Issue by DigitalKrony** [OfficeDev/office-ui-fabric-react#11378]
### Environment Information

- **Package version(s)**: 7.31.0
- **Browser and OS versions**: n/a

As of now it doesn't appear that the `placeholder` prop actually adds a `placeholder` attribute to the input field when rendered.

**Comment by xugao** [comment]
@DigitalKrony  thanks for reporting

It does seem like SpinButton has no way to show placeholder right now because it's always default to "0" value if no min/defaultValue/Value is passed as prop.

Will look into fixing
