### ISSUE TITLE
Please update the project log to the new version

### ISSUE THREAD

**Issue by kriede** [OfficeDev/office-ui-fabric-react#11371]
#### Describe the feature that you would like added

With project for the web, in nov. 2019 a new project icon was introduced, please change the project icon of Office UI fabric to this new version.

#### What component or utility would this be added to

Office Icons

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

![project2019_96x1](https://user-images.githubusercontent.com/9135655/70163416-b76a8f00-16bf-11ea-8456-4529855493a8.png)

**Comment by Jahnp** [comment]
Thanks for reporting, @kriede . We're planning on updating this and many of the other icons that are getting a visual refresh.

**Comment by xugao** [comment]
@Jahnp - looks like this icon has not updated yet. could you give an ETA when it will land? Thanks!

**Comment by Jahnp** [comment]
Thanks for the reminder @xugao. I don't have an ETA for this yet—but I'd like to try to get to it soon.

**Comment by xugao** [comment]
tracking all new icon requests in #11886. closing this one as dup

**Comment by Jahnp** [comment]
Apologies for the delay. This will be updated in #12088.
