### ISSUE TITLE
Does fabric have an Icon Picker?

### ISSUE THREAD

**Issue by russgove** [OfficeDev/office-ui-fabric-react#11399]
Does Fabric have an Icon Picker that lets me code a component to let users select an icon from the fabric Icons? I'm working in SPFX.

**Comment by micahgodbolt** [comment]
nothing built in. You can use a dropdown with a custom item render to do that. I believe that's what they have in the office ribbon.

**Comment by russgove** [comment]
so how do i get  a list of the icon names.   seems the enum was deprecated?
https://github.com/OfficeDev/office-ui-fabric-react/issues/7110

**Comment by micahgodbolt** [comment]
the @uifabric/icons package should have something you can use

https://github.com/OfficeDev/office-ui-fabric-react/blob/ecbdfdb38009cede4aebb1052ed0aaea501b1f43/packages/icons/src/data/AllIconNames.json

**Comment by russgove** [comment]
Awesome, thanks! 
any idea if the fabric combo box has the ability to display the drop down options with more than one option per Row? like they show in https://github.com/OfficeDev/office-ui-fabric-react/issues/7110

**Comment by micahgodbolt** [comment]
you'd need to change the layout styles yourself. it doesn't support multi row content.
