### ISSUE TITLE
FabricBase not setting isFocusVisible for pointer events of type 'touch' or 'pen'

### ISSUE THREAD

**Issue by albertborges** [OfficeDev/office-ui-fabric-react#11396]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Describe the issue:

On pen down or touch down the callouts are not dismissed because isFocusVisible state of FabricBase is not set to false due to it not listening to other pointer events besides mousedown.

#### Actual behavior:

Callout remains visible.

#### Expected behavior:

Callout is dismissed.

### If applicable, please provide a codepen repro:

Change https://github.com/OfficeDev/office-ui-fabric-react/blob/ae503099db790f5df2f35c8969efb4f47bc88898/packages/office-ui-fabric-react/src/components/Fabric/Fabric.base.tsx

onComponentDidMount to handle pointerdown instead of mousedown:

  public componentDidMount(): void {
    const win = getWindow(this._rootElement.current);
    if (win) {
      this._disposables.push(on(win, '**pointerdown**', this.**_onPointerDown**, true), on(win, 'keydown', this._onKeyDown, true));
    }
    this._addClassNameToBody();
  }

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
Yes

Requested priority: (Blocking, High, Normal, Low)
Normal

Products/sites affected: (if applicable)
PowerPoint Online. We did a workaround but it is hacky.

**Comment by albertborges** [comment]
My microsoft alias is boalbe if you need to contact me directly.

**Comment by xugao** [comment]
@albertborges  - Thanks for reporting & willing to make a PR! Feel free to issue one :)

Only thing to note is `pointerdown` event is not supported by all browsers: https://caniuse.com/#search=pointerdown. so you cannot just replace `mousedown` w/ it

**Comment by albertborges** [comment]
Beginning work on this!

**Comment by xugao** [comment]
@albertborges - just checking how are things going. let me know if you need any help :)

**Comment by albertborges** [comment]
Will do. Got pulled off to finish something this week, but let me give it a
go today and get back to you.

Thanks,
Albert

**Comment by albertborges** [comment]
Will do. Got pulled off to finish something this week, but let me give it a go today and get back to you.

Thanks,
Albert

**Comment by albertborges** [comment]
Started pull request:
https://github.com/OfficeDev/office-ui-fabric-react/pull/11523
