### ISSUE TITLE
Detail List Locked Header

### ISSUE THREAD

**Issue by zombikzs** [OfficeDev/office-ui-fabric-react#11394]
Hello,

I've tried to evaluate the Detail List Locked sample code. I've got the following error messages:

return (
      <div className={classNames.wrapper}>
        <ScrollablePane scrollbarVisibility={ScrollbarVisibility.auto}>
          <Sticky stickyPosition={StickyPositionType.Header}>
            <TextField className={classNames.filter} label="Filter by name:" onChange={this._onFilterChange} />
          </Sticky>
          <Sticky stickyPosition={StickyPositionType.Header}>
            <h1 className={classNames.header}>Item list</h1>
          </Sticky>
          <MarqueeSelection selection={this._selection}>
            <DetailsList
              items={items}
              columns={this._columns}
              setKey="set"
              layoutMode={DetailsListLayoutMode.fixedColumns}
              constrainMode={ConstrainMode.unconstrained}
              onRenderDetailsHeader={onRenderDetailsHeader}
              onRenderDetailsFooter={onRenderDetailsFooter}
              selection={this._selection}
              selectionPreservedOnEmptyClick={true}
              ariaLabelForSelectionColumn="Toggle selection"
              ariaLabelForSelectAllCheckbox="Toggle selection for all items"
              onItemInvoked={_onItemInvoked}
            />
          </MarqueeSelection>
        </ScrollablePane>
      </div>
    );

error messages:

Type '(props: IDetailsHeaderProps, defaultRender?: IRenderFunction<IDetailsHeaderProps> | undefined) => Element' is not assignable to type 'IRenderFunction<IDetailsHeaderProps>'.
  Types of parameters 'props' and 'props' are incompatible.
    Type 'IDetailsHeaderProps | undefined' is not assignable to type 'IDetailsHeaderProps'.
      Type 'undefined' is not assignable to type 'IDetailsHeaderProps'.ts(2322)
DetailsList.types.d.ts(153, 5): The expected type comes from property 'onRenderDetailsHeader' which is declared here on type 'IntrinsicAttributes & IDetailsListProps & { children?: ReactNode; }'

function onRenderDetailsHeader(props: IDetailsHeaderProps, defaultRender?: IRenderFunction<IDetailsHeaderProps>): JSX.Element {
  return (
    <Sticky stickyPosition={StickyPositionType.Header} isScrollSynced={true}>
      {defaultRender!({
        ...props,
        onRenderColumnHeaderTooltip: (tooltipHostProps: ITooltipHostProps) => <TooltipHost {...tooltipHostProps} />
      })}
    </Sticky>
  );
}

error message:
Argument of type '{ onRenderColumnHeaderTooltip: (tooltipHostProps: ITooltipHostProps) => Element; columns: IColumn[]; selection: ISelection; selectionMode: SelectionMode; theme?: ITheme | undefined; ... 29 more ...; rowWidth?: number | undefined; }' is not assignable to parameter of type 'IDetailsHeaderProps'.
  Types of property 'onRenderColumnHeaderTooltip' are incompatible.
    Type '(tooltipHostProps: ITooltipHostProps) => Element' is not assignable to type 'IRenderFunction<ITooltipHostProps>'.
      Types of parameters 'tooltipHostProps' and 'props' are incompatible.
        Type 'ITooltipHostProps | undefined' is not assignable to type 'ITooltipHostProps'.
          Type 'undefined' is not assignable to type 'ITooltipHostProps'.ts(2345)

### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by xugao** [comment]
@zombikzs - do you mean the `DetailsList Locked Header` example in https://developer.microsoft.com/en-us/fabric#/controls/web/scrollablepane is giving you error?

Please provide detailed repro steps in order to help
