### ISSUE TITLE
Not all properties of headerClassName are considered

### ISSUE THREAD

**Issue by WhiteCyClop** [OfficeDev/office-ui-fabric-react#11401]
### Environment Information

- **Browser and OS versions**: Google Chrome Version 78.0.3904.108 (Official Build) (64-bit)

### The reproduction of the bug in a codepen:

https://codepen.io/Beliy_Cyclop/pen/xxbZJbN

#### Actual behavior:

The column header of DetailsList doesn't respect font-weight and font-size properties from headerClassName, but color property works fine

#### Expected behavior:

The header style (font-weight, font-size ) is set according to the specified values

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: -

**Comment by micahgodbolt** [comment]
The styles are passed through just, but there are styles on the enclosed span that take precedence. 

![image](https://user-images.githubusercontent.com/1434956/70481570-d8ecc180-1a97-11ea-989b-41a9c852f83f.png)

Unfortunatly, you can't even use !important. Let me see if there is a way to target the 'cellName' correctly.

**Comment by micahgodbolt** [comment]
Sadly there isn't an easy way to update cellName right now. I just created a PR to properly pass the styles prop through from the 'columns' array into the DetailsHeader. This will let you update your column definition to customize that 'cellName'.

```js
let columns = [
  {
    key: 'score',
    name: 'Score',
    fieldName: 'score',
    minWidth: 40,
    maxWidth: 40,
    isResizable: true,
    styles: {cellName: { color: 'red', fontWeight: 400, fontSize: '16px' }),
  },
]}
```
