### ISSUE TITLE
[Screen Reader - Microsoft Form Pro - Email] Certain ARIA roles must contain particular children.

### ISSUE THREAD

**Issue by sonimishra** [OfficeDev/office-ui-fabric-react#11410]
**User Experience:
![MAS1 3 1_Aria required children1](https://user-images.githubusercontent.com/30456910/70502640-65a28880-1b47-11ea-8831-514cf93d5f9d.png)
**
User depending on screen reader might get affected if aria role not contain particular children and user will not be able to identify the control while navigating on screen.

Note: User credentials should NOT be included in the bug.

**Repro Steps:**

1. Open URL: https://forms.office-int.com/ and login using valid credentials.
2. Navigate to any created survey and select it.
3. Navigate Send button present at the top and select it.
4. Navigate to Email tab and select it. Email screen will appear.

5. Verify the issue.
 
**Actual Result:**

Certain ARIA roles does not contain particular children.

**Expected Result:**

Certain ARIA roles must contain particular children.

MAS Reference:
MAS 1.3.1 - Info and Relationships
 

**Reference Links**
Accessibility Insights! - Identify accessibility bugs before check-in and make bug fixing faster and easier.
External Bug Process: If this bug belongs to external team, mark it as resolved/done and assign it back to the tester with notes on where to file/route the bug. For more information please use this Link. “HCL Staff should not log any third party external bugs. Should be routed to EDAD team”.
Please reach out to C&AI Teams channel for any process related queries.

**Test Environment**:
#URL:https://forms.office-int.com/
OS Version 1903 (OS Build 19018.1)
Tools: Accessibility insight tool

**Comment by micahgodbolt** [comment]
Can you please provide a reduced test case outside of the application? aka.ms/fabricpen is a good place to start. 

We need to know what controls are affected and under what condition.
