### ISSUE TITLE
Fabric tooltip in nav item

### ISSUE THREAD

**Issue by hrc7505** [OfficeDev/office-ui-fabric-react#11414]
#### Describe the feature that you would like added
In Nav component there is a way from where we can render custom icon and link text. But if Nav component has prop like ```tooltipProps``` or something more meaningful that can directly shows the fabric tooltip on hover of nav item.

Currently if we use ```onRenderLink``` to render ```TooltipHost``` it is rendered inside the nav item and there is nothing to manage tooltip of nav item. There is one issue (#11413 ) and i added it too.  

#### What component or utility would this be added to
Nav component

#### Have you discussed this feature with our team, and if so, who
No

**Comment by micahgodbolt** [comment]
The nav control is pretty close to deprecation. It's very old and difficult to update without breaking the API. How complex is your UI? You could easily build a similar, more flexible control out of CommandBarButtons and a vertical overflowSet.

**Comment by joschect** [comment]
@hrc7505 You might be able to use the `linkAs` property to provide your own complete renderer that will receive all the information necessary to implement the tooltip properly.

**Comment by hrc7505** [comment]
@joschect Do you have any example how to use ```linkAs``` prop? I am not understanding that prop good.

**Comment by micahgodbolt** [comment]
Oh yeah, linkAs works great. You can also use it to suppress the title.

https://codepen.io/micahgodbolt/pen/WNbxbGa?editors=0010

**Comment by hrc7505** [comment]
@micahgodbolt Thank for the demo!

**Comment by dandrei** [comment]
@micahgodbolt 
>The nav control is pretty close to deprecation.

I'm building a layout with `office-ui-fabric-react` now and the `Nav` is the first component I've added, as I need a sidebar. What should I use instead?
