### ISSUE TITLE
ColorPicker: Alpha slider does not have a dedicated aria label string

### ISSUE THREAD

**Issue by navkuma** [OfficeDev/office-ui-fabric-react#11415]
### Environment Information

- **Package version(s)**: 7.69.3 (or latest)
- **Browser and OS versions**:  Microsoft Edge 44.18362.449.0  and  Windows 10 Enterprise version 1903 OS build 18362.476

### Describe the issue:

User Impact:
People with Visual impairment will not be able to know how to access the sliders. 
In the Color picker control, Narrator should provide the instruction to the users how to access the sliders. 
For the horizontal sliders, users can access only using Right/Left arrow keys. So Narrator should provide the instruction. 

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/16f4cae9-74df-4efe-af3b-485541d4fa53/pen/wvBGByO?&editable=true

#### Actual behavior:
Narrator should provide the instruction to the users how to access the sliders. 
For the horizontal sliders, users can access only using Right/Left arrow keys. So Narrator should provide the instruction. 

#### Expected behavior:

Narrator should provide the instruction as 'Use right/left arrow keys to change the value' for horizontal sliders and 'Use Arrow keys to change the value' for slider.

**Comment by micahgodbolt** [comment]
Instructional strings are usually up to the user to provide. The hue slider works fine adding a descriptive string like this:

```
<ColorPicker
          color={color}
          onChange={this._updateColor}
          alphaSliderHidden={alphaSliderHidden}
          showPreview={showPreview}
          styles={colorPickerStyles}
          strings={{
            hue: ' Use left and right arrow keys to change hue. Hold shift for larger change'
          }}
        />
```

But the alpha ariaLabel shares its string with the 'Alpha' string down below:

![image](https://user-images.githubusercontent.com/1434956/70555570-2880cb00-1b34-11ea-82c2-e94cdd519166.png)

It looks like we need to make that alpha slider have a dedicated aria label like the hue slider already has.

I'll udpate the title of this issue to reflect that.
