### ISSUE TITLE
Breadcrumb is not responsive with flexbox

### ISSUE THREAD

**Issue by hrc7505** [OfficeDev/office-ui-fabric-react#11412]
### Environment Information

- **Package version(s)**: 7.69.2

### Please provide a reproduction of the bug in a codepen:
[Codepen](https://codepen.io/hardik-chaudhary/pen/JjoGQgK)

#### Actual behavior:
 With flexbox, if more items then screen width, body shows scrollbar. With ```flex:1``` it is fine initially but on window resize it is not working.

#### Expected behavior:
It should be responsive with flexbox.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

**Comment by micahgodbolt** [comment]
This issue is logged already under #4066. We're working on possible solutions for this as well.
