### ISSUE TITLE
Calendar: Narrator/NVDA is not reading the role for up/down arrows in calendar, reading as button only. Information about the change of how many years range should convey.

### ISSUE THREAD

**Issue by v-jashr** [OfficeDev/office-ui-fabric-react#11428]
![image](https://user-images.githubusercontent.com/50479173/70621805-6bc86000-1c40-11ea-9813-da953a17e178.png)

Actual Result:​​

Narrator/NVDA is reading the up/down arrows in calendar as button only

 

Expected Result:

Narrator/NVDA should read the up/down arrows in calendar as button with description.

 User Impact:​

Screen Reader users will face the issue as they will not understand the buttons (arrow keys) if the narrator/NVDA is reading them as buttons

**Comment by micahgodbolt** [comment]
In narrator i get "Go to previous year 2018. Button"

Are you expecting something else?

**Comment by v-jashr** [comment]
If just want to go on next and previous year , i mean single year increment it works fine. But when you use range then it increase and decrease years by 12. And that information NVDA won't convey. Expecting, NVDA should speak on click of next/previous button, 'range will increasing/decreasing  by 12years' .

**Comment by micahgodbolt** [comment]
Any strings read out are strings are provided by the component user. If you want the calendar to say something 'different' that is 100% customizable. If you want the buttons to describe how many years it will increase, you will need to provide that string. 

Check out the calendar strings to see if the support customizing the control in the way you want.

https://github.com/OfficeDev/office-ui-fabric-react/blob/2894062b1d0515055c29061dfc6f586f918ca41c/packages/office-ui-fabric-react/src/components/Calendar/Calendar.types.ts#L197-L266

**Comment by v-jashr** [comment]
I am not getting reference of this property in control.

can you please provide me specific version where this properties are available. On below office fabric official website also, i didn't found this properties.  

https://developer.microsoft.com/en-us/fabric#/controls/web/datepicker

**Comment by joschect** [comment]
Hi @v-jashr You can first click on 
![image](https://user-images.githubusercontent.com/20801176/70925484-2610ec00-1fe0-11ea-9452-ea3687a437aa.png)
Which takes you to some of the strings, then click on 
![image](https://user-images.githubusercontent.com/20801176/70925586-535d9a00-1fe0-11ea-9f11-831039686c03.png)


which takes you to [the calendar strings](https://developer.microsoft.com/en-us/fabric#/controls/web/calendar#ICalendarStrings)

**Comment by v-jashr** [comment]
Thanks for your help and response .Issue resolved
