### ISSUE TITLE
DropDown Type error when building with TypeScript version 3.63

### ISSUE THREAD

**Issue by zombikzs** [OfficeDev/office-ui-fabric-react#11429]
### Environment Information

- **Package version(s)**: 7.70.0
- **Browser and OS versions**: (fill this out if relevant)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: (if applicable)

When building a project using the Fabric Dropdown with TypeScript 3.63, there is a compilation error.
import * as React from 'react';
import { Dropdown, IDropdown, IDropdownStyles, IDropdownOption } from 'office-ui-fabric-react/lib/Dropdown';

//for local testing
const options: IDropdownOption[] = [
    { key: '1', text: 'Account'},
    { key: '2', text: 'Contact'}
    ];

    export interface IDropdownControlledExampleState {
        selectedItem?: { key: string | number | undefined };
      }

    export class EntitiesListDropDown extends React.Component<{}, IDropdownControlledExampleState>{

        public state: IDropdownControlledExampleState = {
            selectedItem: undefined
          };

        public render(): JSX.Element {
            const { selectedItem } = this.state;
            
            
            return(
                <Dropdown
                    placeholder="Select an Entity"
                    label="Entity"
                    selectedKey={selectedItem ? selectedItem.key : undefined}
                    onChange={this._onChange}
                    options={options}
                    disabled={false}
                    required={true}
                    styles={{ dropdown: { width: 300 } }}
                />
            );
        };
        private _onChange = (event: React.FormEvent<HTMLDivElement>, item: IDropdownOption): void => {
            console.log(`Selection change: ${item.text} ${item.selected ? 'selected' : 'unselected'}`);
            this.setState({ selectedItem: item });
          };
    
          
        
    }

Type '(event: FormEvent<HTMLDivElement>, item: IDropdownOption) => void' is not assignable to type '(event: FormEvent<HTMLDivElement>, option?: IDropdownOption | undefined, index?: number | undefined) => void'.
  Types of parameters 'item' and 'option' are incompatible.
    Type 'IDropdownOption | undefined' is not assignable to type 'IDropdownOption'.
      Type 'undefined' is not assignable to type 'IDropdownOption'.ts(2322)

**Comment by micahgodbolt** [comment]
@zombikzs are you saying this works for you with other typescript versions?

**Comment by micahgodbolt** [comment]
The second param is optional. Your second param is set as required.

![image](https://user-images.githubusercontent.com/1434956/70650078-3fdab980-1c03-11ea-9919-dd140f4ed8fb.png)

![image](https://user-images.githubusercontent.com/1434956/70650119-51bc5c80-1c03-11ea-9cd4-b4085c88263b.png)
