### ISSUE TITLE
Panel: Confirm light dismiss- No button in the Diaog doesnt work as expected

### ISSUE THREAD

**Issue by abdollahkahne** [OfficeDev/office-ui-fabric-react#11437]
In the case of Panel in office-ui-fabric-react example provided at following adress, The dialog doesnt behaive as expected
[Office UI Fabric](https://developer.microsoft.com/en-us/fabric/#/controls/web/panel)

#### Actual behavior:

When No Button on Dialog pressed, both of Dialog and Panel hide which is similar to Yes button but it is not as expected

#### Expected behavior:

When No Button on Dialog pressed, the dialog should hide but panel remains visible

**Comment by micahgodbolt** [comment]
can confirm, the panel closes when you hit 'no'

![image](https://user-images.githubusercontent.com/1434956/70670704-a75a2e80-1c2e-11ea-9c25-b83b9d5decb8.png)


This doesn't appear to be a demo problem, so it is probably a bug
