### ISSUE TITLE
Fabric datepicker: combobox text color is mapped to the Windows High Contrast disabled color

### ISSUE THREAD

**Issue by jlukosky** [OfficeDev/office-ui-fabric-react#11438]
### Environment Information

- **Edge/Windows 10**

### Describe the issue:

It is not obvious in Windows high contrast black but the color of the comboboxes are mapped to the *disabled* Windows high contrast color set by the user.

### The issue

It is not obvious in Windows high contrast black but the color of the comboboxes are mapped to the *disabled* Windows high contrast color set by the user.

#### Actual behavior:

Color of the normal comboboxes is the Windows high contrast color for disabled items

#### Expected behavior:

Color for the normal comboboxes should be mapped to the Windows high contrast color for **text**

If the disabled color is used by these items they will appear disabled and not usable. This will be confusing to the end-user.

**Comment by micahgodbolt** [comment]
not quite following

in high contrast black

![image](https://user-images.githubusercontent.com/1434956/70736952-51d16080-1cc6-11ea-879e-a048e4823786.png)

Combobox text color is the same as a standard input, and the disabled color is the same as the disabled color picked in settings.

Can you provide any screenshots or way to repro this issue.

**Comment by micahgodbolt** [comment]
You said DatePicker in the title, then combobox below, but either way, we use standard default `<input>` colors during high contrast mode. Disabled, enabled, placeholder. We render exactly what the browser says an input should render.

**Comment by jlukosky** [comment]
For some reason I was getting odd results while testing this. I've rebooted and everything looks fine! Great job.
