### ISSUE TITLE
[Grouped DetailsList] check button on the Group name misses the aria label

### ISSUE THREAD

**Issue by dli68** [OfficeDev/office-ui-fabric-react#11448]
### Environment Information

- **Package version(s)**: 7.72.0
- **Browser and OS versions**: Chrome

### Describe the issue:

Running Keros on the grouped DetailsList component shows that the group header row's select/check button doesn't have aria text. The api interface doesn't provide an entry point for it neither

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/wsmwwps/pen/JjoKabY?&editable=true 

#### Expected behavior:

Keros doesn't complain on the missing aria

**Comment by joschect** [comment]
@dli68 thanks for submitting this issue. It is possible to provide an aria-label for the text, although it is quite unintuitive. I modified your codepen [here](https://codepen.io/slimemold/pen/RwNGGEj?editors=1010). We'll get the example changed too to make it more obvious how to supply a value.

**Comment by dli68** [comment]
@joschect hey Jon, thanks for the quick reply and providing the solution. I've noticed two changes are specifically needed for it to work: one is to assign aria-label value under selectAllButtonProps of headerProps of groupProps; the other one is to assign value to ariaLabelForSelectAllCheckbox just under DetailsList component itself.

Both are needed for it to work seems, as you said, quite unintuitive. Would it be possible for the fix that defining just one place to work?

**Comment by joschect** [comment]
@dli68 For now we'll need to keep both to prevent regressing anything. Moving forward we could deprecate one of the props to ensure that only one is needed.
