### ISSUE TITLE
DetailList features

### ISSUE THREAD

**Issue by Bluhmanman** [OfficeDev/office-ui-fabric-react#11444]
#### Describe the feature that you would like added

I'd appreciate some features to make the DetailList usable for large bodies of data - our team was using Kendo React Table for our web app up until now, when we discovered Fabric had made some excellent progress on making its own table component. The ideas I had included:

- ~~Headers always at top~~: Long lists will usually be displayed within a scrolling view (500-1000 entries). When viewing entries deep in the list, the headers won't be visible unless you scroll back to its top. It'd be nice to perhaps bake scrolling funcitonality into the component itself, which in turn, would enable an option to keep column headers visible at the top of the component at all times.
_EDIT: After looking through the fabric documentation a bit further, I found out that this is possible by using a custom "RenderDetailsHeader" function that shows a Sticky element in a Scrollable Pane, that encompasses the DetailList. While the DetailList has its own section devoted to its features it's a little bit misleading that the only example of this is shown in the Scrollable Pane component section, especially when I see the use case for having always-visible headers on a list being fairly common for this component. There's also the fickle nature of the Scrollable Pane itself, how it requires containment inside specifically-sized components, but that's essentially a separate problem._
- **Pagination**: If the above isn't a feasible feature request, having the ability to create pages with the component based on a sample size would suffice.
- **Column Filters**: I'm looking into currently implementing column filters via the OnRenderDetailHeader prop - the examples show filters as text fields that exist _outside_ the table's layout, whereas what I'm looking for (because my use case also involves reordering columns and enabling/disabling them) requires having the filters coupled directly with the columns. Perhaps this is just a process of building an appropriate filter text field into the column's header manually - is this possible right now? If not, could it be?

#### What component or utility would this be added to

All of this is in the context of the **DetailList** component.

#### Have you discussed this feature with our team, and if so, who

no not yet.

#### Additional context/screenshots

Headers at top of list: note the scroll position on the right.
![image](https://user-images.githubusercontent.com/22921549/70736582-7a0c8f80-1cc5-11ea-925d-fbbfd49bd47f.png)

At the middle of the list, the headers for the columns are no longer visible.
![image](https://user-images.githubusercontent.com/22921549/70736622-90b2e680-1cc5-11ea-930e-7ccaf6c2a753.png)

**Comment by Bluhmanman** [comment]
Hi I've done a bit more experimenting with the component and discovered ways by which to implement always-visible headers, as well as _almost_ implementing filters in a sub-header (also always visible). However due to some of the idiosyncrasies of the component I'm running into some roadblocks:

From a base React component, the DetailsList has the function to render an extra DetailsHeader (onRenderDetailsHeader) as a prop. When the component is rendering itself, it's running within the context of its own component, thus it has access to its own props, state, and variables, as well as all the functions contained in the component.

Within the onRenderDetailsHeader function that gets called, I return a rendered JSX element that creates a DetailsRow. This has its _own_ properties, including one for what I'm using to attempt to render what'll eventually be my filter field. However at this point the function is _not_ run within the scope of the component's code itself - in other words, when I attempt to call a function or state change for the component I'm writing here, I will get an error because "this" is not defined when I attempt to call something such as "this.props.foo" or "this.setstate({...})". Specifically however this is for just rendering a details header, and the solution is to just define the function for this render outside the context of the component's class.

This is where I run into an issue, however: now I'm writing an unencapsulated function with a TextField that will attempt to serve as a filter for a component that has a state that _it has no context of._ So if I'm going to attempt doing this, having some way to pass down the parent component context reference to this function would be appreciated. Or maybe more conveniently not requiring the render functions to lose the context in the first place...

_Console screenshot of render function running without context to the original component._
![image](https://user-images.githubusercontent.com/22921549/70823679-5b75c980-1d95-11ea-801f-1b43e14f8a38.png)

**Comment by joschect** [comment]
@Bluhmanman You will not have access to `this` within an `onRender` function like the one used in details list. That would be changing the local this and that would produce undesirable effects, like if you pass a private method into onRender, it should still have the local instance of the class as this rather than the details list. 

You can still achieve what you're looking to do, however. You would just need to pass the callback into the render function. I've made a [codepen here](https://codepen.io/slimemold/pen/qBERdeP) that I believe does what you want it to. You could simplify it further by moving the renderFilterColumn into the actual class that's rendering the details list.

Also per your first comment: I agree that it is confusing that we don't have a sticky header example in the details list section. It would make sense to have one there or point to the sticky section.
