### ISSUE TITLE
select element is not tabbable inside FocusTrapZone if it precedes a textarea element.

### ISSUE THREAD

**Issue by stiboost** [OfficeDev/office-ui-fabric-react#11454]
### Environment Information

- **Package version(s)**: 7.72.0
- **Browser and OS versions**: Chrome Version 78.0.3904.108 (Official Build) (64-bit) on Ubuntu 18.04 

#### Actual behavior:
When a `textarea` comes directly after a `select` inside a `FocusTrapZone`, the `select` element is not tabbable.
https://codepen.io/utrolig/pen/yLyJrmL

#### Expected behavior:
The `select` element should be tabbable. This works when `tabIndex={0}` is set on the `select` element.
https://codepen.io/utrolig/pen/dyPXLLz

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable)

**Comment by joschect** [comment]
@stiboost Thanks for submitting this and including a codepen! I am a little confused, I am able to back tab (shift + tab) to the select from the textarea. It is interesting that the FocusTrapZone appears to preferentially focus the textarea. Is that the primary issue? That the FocusTrapZone will always focus the textarea instead of focusing the first element in the list?

**Comment by stiboost** [comment]
> @stiboost Thanks for submitting this and including a codepen! I am a little confused, I am able to back tab (shift + tab) to the select from the textarea. It is interesting that the FocusTrapZone appears to preferentially focus the textarea. Is that the primary issue? That the FocusTrapZone will always focus the textarea instead of focusing the first element in the list?

I am also able to back-tab to the select, but in the working example, I can tab in a loop inside the `FocusTrapZone`. That is the main issue here. So when `tabIndex` is not set, I can just tab once, and then the focus is trapped inside the `textarea`. 

This can be further tested by adding [more elements](https://codepen.io/utrolig/pen/vYEyYVB), which then shows the select not being included at all when tabbing inside the `FocusTrapZone`.

**Comment by joschect** [comment]
@stiboost That's a great codepen! I see exactly what you're talking about. It looks like we are missing a tag for 'select' in the focus utility. Should be a relatively easy change. See the lines here https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/utilities/src/focus.ts#L387-L395 . We'll get a pr in to get this fixed.

In the meantime you can add `data-is-focusable=true` to the select and will behave as expected. See this [codepen](https://codepen.io/slimemold/pen/gObLgzb) for the workaround.
