### ISSUE TITLE
Breadcrumb: Customize icon used

### ISSUE THREAD

**Issue by ujavai2s** [OfficeDev/office-ui-fabric-react#1145]
Respected All,  

is it anyway to change the ms-Icon--ChevronRight with any other Icon, for example ms-Icon--ChevronLeft
in Breadcrumb? According to my understanding,  there is no option to change the icon.

Best Regards

Umer Javaid

**Comment by micahgodbolt** [comment]
Could be solved with a new prop for divider icon, or new onRender function for overriding the Chevron with anything you want. 

Would there be any case where we'd want something other than an icon? Like a -,=>,| or image.
