### ISSUE TITLE
Is it possible to use colSpan like feature in DetailsList?

### ISSUE THREAD

**Issue by ymihir** [OfficeDev/office-ui-fabric-react#11458]
I am able to created DetailsList with less effort and which is very good. I wanted to know is there any way that I can implement colspan like feature so that i can have in between headings in the table. Is there any possibility?

**Comment by joschect** [comment]
There isn't something exactly like a colspan, but you could use a custom row renderer to render an entire row how you want. I believe it will allow you to do what you want. Here's a [codepen](https://codepen.io/slimemold/pen/jOEMMKX) that demonstrates how you could do it.

**Comment by ymihir** [comment]
Ok Thanks. I will try this in future projects
