### ISSUE TITLE
Fabric UI for React-native

### ISSUE THREAD

**Issue by Boussama** [OfficeDev/office-ui-fabric-react#11456]
Hello, 

First of all, I want to begin by expressing how much I am amazed by how it looks great on mobile.
I am working with many UI frameworks for react-native like elements or paper but Fabric is way better I have to say.
Is there any plan for making it available for react-native? 
I am planning on making it available for the opensource community but I want to know if there's something going on from your side.

Thank you again for this contribution to the open-source community, much appreciated.

**Comment by micahgodbolt** [comment]
We're already working on this, though we don't have anything public to share yet. Thanks for your interest! We'll be sure to announce when we have updates.

As this repo is focused on our React Web code, I'll close this issue.  Follow us on [Twitter for updates](https://twitter.com/OfficeUIFabric)
