### ISSUE TITLE
DetailsList: Ability to make header fixed

### ISSUE THREAD

**Issue by notgiorgi** [OfficeDev/office-ui-fabric-react#1146]
It would be convenient to have a prop `isHeaderFixed` on DetailsList component.

**Comment by willtrking** [comment]
+1

**Comment by russgove** [comment]
+2, should be able to fix the first column or two as well

**Comment by roger-green** [comment]
+1

**Comment by ndoiselet** [comment]
+1

**Comment by marlonbrgomes** [comment]
+1

**Comment by aappddeevv** [comment]
Related to #3378. You can make the header fixed but then the body does not render all the rows in the list when you scroll. There may be a way to do that so we have the sticky header before a fix is put in. If we can tell the underling list to render the rows correctly as it is scrolled, we would have a solution to this.

**Comment by oengusmacinog** [comment]
Scrollable Pane with Detail List resolves this issue. [https://developer.microsoft.com/en-us/fabric#/components/scrollablepane](https://developer.microsoft.com/en-us/fabric#/components/scrollablepane). Closing Issue.

**Comment by betrue-final-final** [comment]
This works in Detailslist now? I'm confused.

**Comment by aappddeevv** [comment]
Check out the example link that is listed in the comment. Essentially you wrap the header (using the header renderer) in a Sticky and wrap everything in a ScrollablePane. So composed together it becomes a solution.

**Comment by roger-green** [comment]
I've taken the example code and inserted into a simple create-react-app app. However, I just can't get the sticky's to stick inside the scroll area (they stick to the top of the page instead). This certainly looks like a CSS issue, but I am stumped. If anyone has any ideas, this would be really appreciated! I've uploaded a simpe test project here : 

https://rockgobyx@bitbucket.org/rockgobyx/fabric-react-test.git

![stickyish](https://user-images.githubusercontent.com/34266849/37701454-01c9894e-2ce7-11e8-91b1-7f79f3356f4e.png)

**Comment by brettinternet** [comment]
If you're following the `DetailsList` example from [ScrollablePane](https://developer.microsoft.com/en-us/fabric#/components/scrollablepane), I recommend you use a `position: fixed` on the sticky component via the provided `stickyClassName`. Otherwise, you'll get a scrollbar on the header that doesn't scroll in `overflow-x` with the rest of the `DetailsList` component.

**Comment by prabirshrestha** [comment]
Here is how I have implemented stick headers in detail list.


```ts
<ScrollablePane>
    <DetailsList
            items={items}
            compact={false}
            columns={columns}
            selectionMode={SelectionMode.single}
            layoutMode={DetailsListLayoutMode.fixedColumns }
            isHeaderVisible={true}
            selection={this._selection}
            enterModalSelectionOnTouch={false}
            onRenderDetailsHeader={
              // tslint:disable-next-line:jsx-no-lambda
              (detailsHeaderProps: IDetailsHeaderProps, defaultRender: IRenderFunction<IDetailsHeaderProps>) => (
                <Sticky>
                  {defaultRender(detailsHeaderProps)}
                </Sticky>
              ) }
               />
</ScrollablePane>
```
