### ISSUE TITLE
Tooltip host does not work well with touch

### ISSUE THREAD

**Issue by zoarif** [OfficeDev/office-ui-fabric-react#11466]
### Environment Information

- **Package version(s)**: 7.69.1
- **Browser and OS versions**: IPad/ Touch devices

### Please provide a reproduction of the bug in a codepen:
It is difficult to create a codepen for touch device but basically when you add tooltip host to a button, and then tap on IPad. It opens the tooltip. You have to double tap to execute the button functionality. 
I have been removing tooltips from touch devices as a workaround. 
#### Expected behavior:

A single tap should work with tooltip. 

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

**Comment by joschect** [comment]
@zoarif Thanks for submitting this. I'm having a little trouble reproducing this. I made this [codepen](https://codepen.io/slimemold/pen/dyPOJzo) and then tested it with both my android phone and the iOS simulator that apple ships and in both of those the button consistently fired the alert on one press not two. Maybe the codepen is missing something, could you take a look?

**Comment by micahgodbolt** [comment]
I also had zero issues with android, or actual ipad device

![IMG_20191218_111627](https://user-images.githubusercontent.com/1434956/71116036-24822800-2188-11ea-8127-3a6b5ea8d2a2.jpg)
