### ISSUE TITLE
[Visual Requirement-Data Explorer(iframe)] On the Data Explorer page, appearance of the "See more Cosmos DB documentation" button is just like link.

### ISSUE THREAD

**Issue by sonimishra** [OfficeDev/office-ui-fabric-react#11474]
Bug copied from Azure cosmos DB : https://msdata.visualstudio.com/CosmosDB/_workitems/edit/522777
**User Experience:**
If, the appearance of any button is not same as of other buttons available on the page, then the users who depends upon keyboard for navigation might get affected hence failed to identify the control properly.

**Pre-Requisite:**
Select "Core(SQL)" in API combo box while creating the Cosmos DB.

**Repro-Steps:**
1. Open URL: https://ms.portal.azure.com
2. Login via valid credentials
3. Navigate to "Azure Cosmos DB" from left pane and select it.
4. Navigate to any of the Azure Cosmos DB which is already created and select it.
5. Navigate to "Data Explorer" from the left and select it.
6. Navigate through all the controls under Data Explorer blade.
7. Navigate with the keyboard and reach "See more Cosmos DB documentation" button.
8. Verify, whether the appearance of button is just like link or not.

**Actual Result:**
On the Data Explorer page, appearance of the "See more Cosmos DB documentation" button is just like link, due to which keyboard user failed to identify the control. 

**Expected Result:**
On the Data Explorer page, appearance of the "See more Cosmos DB documentation" button should be same as of other button available on the page. So, that the keyboard user can able to differentiate between the link and button available on the page.

**Note:-**
1. Same issue exists with Chrome browser.

**MAS Reference:**

MAS 3.2.4 - Consistent Identification

Accessibility Insights! - Identify accessibility bugs before check-in and make bug fixing faster and easier

External Bug Process: If this bug belongs to external team, mark it as resolved/done and assign it back to the tester with notes on where to file/route the bug.
For more information please use this Link.
**Attachment:** ![MAS3 2 4-Appearance of the button is not same as of other button](https://user-images.githubusercontent.com/30456910/70848410-06ba7780-1e97-11ea-8eac-ea1e51d94f5e.png)

**Comment by ecraig12345** [comment]
Can you please provide an isolated reproduction of this bug? Without seeing how you're using the control, it's hard to say what's going wrong, and whether it's on the Fabric side or just an issue with how the control is being used. You can start from the "Export to CodePen" link on one of the [button examples](https://developer.microsoft.com/en-us/fabric#/controls/web/button).

Also, **please** remember that this is a public forum and refrain from posting private issue links and product screenshots in the future! If you need to provide more context, you can file the issue and wait for it to be assigned, then contact the assignee privately on Teams.

**Comment by micahgodbolt** [comment]
This is an external issue with the author of the azure application.
