### ISSUE TITLE
ChoiceGroup 'labelId' property does not apply the choice group items

### ISSUE THREAD

**Issue by maelgami** [OfficeDev/office-ui-fabric-react#11479]
#### Environment Information

- **Package version(s)**: 6.162.0
- **Browser and OS versions**: Edge and Chrome 78

#### Description:

When giving ChoiceGroup labelId to its items - the narrator doesn't read the custom label by the given label id.

see codepen: https://codepen.io/maelgami/pen/jOEVPNd

#### Actual behavior:
Aria-owns does not apply the ChoiceGroup items

#### Expected behavior:
Aria-owns should apply the ChoiceGroup items so Narrator can read the linked label and its 

#### Documentation describing expected behavior
Please look at the documnation regarding Label Id property in IChoiceGroupOption interface:

https://developer.microsoft.com/en-us/fabric#/controls/web/choicegroup

**Comment by ecraig12345** [comment]
ChoiceGroup doesn't automatically add `aria-owns` to any of its elements; the doc comment on `labelId` is only meant as an example of how that prop could be used. Also, applying the same ID to multiple options' labels results in invalid DOM, since an ID is supposed to be unique on the page.

Using the built-in `label` prop and removing `labelId` from the individual options results in reasonable reading behavior. https://codepen.io/ecraig12345/pen/jOEBRzm?editors=0010 Does something like that example work for your scenario?

**Comment by maelgami** [comment]
Thanks for your replay, yet i want to use labelId for the purpose of writing my own label.

In case i have created my own label and not used the `'label'` prop that ChoiceGroup provides - how can i add aria-labelledbyid prop to the ChoiceGroup items ?

Please take another look at my codepen example
https://codepen.io/maelgami/pen/jOEVPNd  - in such case i would expect that all the choiceGroup items would contain ` 'aria-labelledbyid'` prop which its value is the outside label Id of the label i've created.

**Comment by ecraig12345** [comment]
If the custom label applies to the ChoiceGroup all-up, you should use `<ChoiceGroup ariaLabelledBy={labelId} ...>` rather than trying to apply `labelId` to individual options. https://codepen.io/ecraig12345/pen/XWJeNKe

**Comment by ecraig12345** [comment]
Also, it's pretty uncommon that you'd need to use `aria-owns`. That's only for when the DOM elements aren't nested in a way that makes a parent/child relationship clear ([official reference](https://www.w3.org/TR/wai-aria/#aria-owns), [Q&A](https://stackoverflow.com/questions/34003530/what-is-the-difference-between-aria-owns-and-aria-controls)). I'm not sure why the ChoiceGroup docs explicitly mentioned it.

Re: `aria-labelledby` on individual options, each option must have **its own unique label**, *separate* from the parent ChoiceGroup's label. If you use the parent ChoiceGroup's label as every option's `aria-labelledby`, all the options would sound the same to a screen reader user and there would be no way to distinguish them.

**Comment by maelgami** [comment]
That is correct `aria-owns` is not what is need but `aria-labelledby` is. 

The solution is to concat the labelId to each option of the ChoiceGroup labels, along with their own id so that when the screen reader goes through this component it will read the custom label and then the inner option label.

At the moment i had to solve the issue so i used 'onLabelRender' and implemented the above logic to each option's label.

**Comment by ecraig12345** [comment]
Do you mean you're trying to render custom labels for the individual items?

**Comment by ecraig12345** [comment]
it would be helpful if you could update your codepen to be more like what your actual code is doing. From your descriptions, I'm still having a hard time understanding what you're trying to achieve and why it's not possible with the existing props.
