### ISSUE TITLE
Merge Styles - Extend definitions for vendor prefixes

### ISSUE THREAD

**Issue by savkelita** [OfficeDev/office-ui-fabric-react#11473]
### Environment Information

- **Package version(s)**: 7.27.0
- **Browser and OS versions**: Chrome Version 79.0.3945.79 (Official Build) (64-bit), Microsoft Windows [Version 10.0.18363.535]

### Describe the issue:

I'm using **MergeStyles** library and have a problem with TS definitions for some vendor prefixes.
For example `-webkit-filter` `-webkit-transform` `-webkit-background-size`: (also for _-o, -ms, -moz_)

```
mergeStyleSets({
        background: [{
                position: 'fixed',
                top: '-50%',
                left: '-50%',
                width: '200%',
                height: '200%',
                zIndex: -1,
                webkitFilter: 'blur(5px)', // Error, no definition.
                filter: 'blur(5px)',
                transform: 'scale(1.1)',
            }]
```
Are you have some limitations to put all of them inside `IRawStyleBase.ts`? 
It would be great to have all definitions not just few of them.

Also, can someone explain what does exactly mean `automatic vendor prefixing` from motivation section [here](https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/merge-styles#motivation). 

### Please provide a reproduction of the issue in a codepen:

[Codepen](https://codepen.io/savkelita/pen/qBEamqX).

**Comment by micahgodbolt** [comment]
Your codepen is trying to pass rotate into filter. Blur works properly, though you'll need to write your prefix as a string, which might mean casting the result to 'any'

https://codepen.io/micahgodbolt/pen/gObLmgL?editors=1010

**Comment by savkelita** [comment]
@micahgodbolt My mistake, sorry! Problem is still there:

**Example:**
```
const foo = mergeStyleSets({
  root: [
    {
      backgroundColor: '#f00',
      '-webkit-filter': 'blur(5px)'
    },
  ]
})
```

**Error:**
```
Argument of type '{ '-webkit-filter': string; }' is not assignable to parameter of type 'IStyle'.
  Object literal may only specify known properties, and ''-webkit-filter'' does not exist in type 'IRawStyle | IStyleBaseArray'.ts(2345)
```

Thank you!

**Comment by micahgodbolt** [comment]
Yeah, we haven't added all of those prefixes to avoid code bloat. You can always cast the return's object to 'any' and bypass that error.

**Comment by ecraig12345** [comment]
For somewhat improved type safety, you can do something like:
```
const foo = mergeStyleSets({
  root: [
    {
      backgroundColor: '#f00',
      ...({ '-webkit-filter': 'blur(5px)' } as any)
    },
  ]
})
```

Aside from the code bloat issue, I remember some previous discussions about philosophical reasons we didn't want to add lots of vendor-specific properties (but I don't remember the details). Unfortunately due to people being on vacation it may be hard to get more background on that until everybody is back in early January.

**Comment by savkelita** [comment]
@ecraig12345 Thank you!
