### ISSUE TITLE
@uifabric/utilities@^7.7.0 not available on npm

### ISSUE THREAD

**Issue by petersgiles** [OfficeDev/office-ui-fabric-react#11476]
# Environment Information

- **Package version(s)**: office-ui-fabric-react 

I get this error using `npm i office-ui-fabric-react`
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @uifabric/utilities@^7.7.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'office-ui-fabric-react'
npm ERR! notarget 
```
It hasn't been released on npm

#### Actual behavior:

fails to do npm install

#### Expected behavior:

install the package

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking)

Products/sites affected: just my develop at the moment

[2019-12-16T01_25_05_482Z-debug.log](https://github.com/OfficeDev/office-ui-fabric-react/files/3965732/2019-12-16T01_25_05_482Z-debug.log)

**Comment by ishi-0987** [comment]
Hey,
Even I am facing the same issue. Can someone please check on it ?

**Comment by dehypnosis** [comment]
Here too

**Comment by aashishvanand** [comment]
Last update in was 25 days ago in https://www.npmjs.com/package/@uifabric/utilities

**Comment by Kraviecc** [comment]
For me worked 7.73.0:

`npm i office-ui-fabric-react@7.73.0`

**Comment by Perneel** [comment]
same issue here with 7.74.0
works with 7.73.0

**Comment by nakah** [comment]
Same issue here with @uifabric/utilities^7.7.0
There is an issue with NPM registry as you can see in the screenshot:
![image](https://user-images.githubusercontent.com/10684049/70904618-1904f480-2002-11ea-8d63-24139c99d797.png)

The search bar says that the latest version is 7.7.0 but the package's view show 7.6.0

**Comment by ecraig12345** [comment]
Looking into it now. Thanks for reporting.

**Comment by ecraig12345** [comment]
This seems to have been fixed already--[npm page](https://www.npmjs.com/package/@uifabric/utilities) now shows the latest version, and I'm able to do `npm install office-ui-fabric-react` successfully. If anyone is still hitting this issue, please comment; otherwise I'll close it later today.
