### ISSUE TITLE
Pivot component:  if I change selectedKey via state, it does not change what pivot item is selected.

### ISSUE THREAD

**Issue by mikezimm** [OfficeDev/office-ui-fabric-react#11491]
### **Package version(s)**: (fill this out)
"@microsoft/sp-core-library": "1.9.1",
"office-ui-fabric-react": "6.189.2"
"react": "16.8.5",

This is an SPFx webpart in SharePoint online.

### Please provide a reproduction of the bug in a codepen:
Unfortunately I wasn't able to build a working codepen with both a pivot and toggle :(.

In my webpart, I have two independent sets of pivot headings and use a toggle component to tell which pivot heading set I want to show.  I then use the onLinkClick to filter items on the screen.  In the state, I also save the last pivot heading I clicked for each set so when I toggle back to a set of pivots, it resets the defaultKey... at least that's the goal.

**A simple scenario would be**
I have a toggle to change my PivotItems (headings) from Colors to Shapes.
- Toggle = OFF, Pivot Headings => Red, Yellow, Green.
- Toggle = ON, Pivot Headings => Square, Triangle, Circle.

1. Now say Toggle = OFF and I select Green
2. Then Toggle = ON and I select Triangle
3. If I then Toggle = OFF again I would expect Green to be selected

Unfortunately it shows Yellow because it is the same index as Triangle.

I'm not sure if issue #11427 is the same, but it might be related.

#### This is a trimmed down version of my code
```typescript
  public render(): React.ReactElement<ITrackMyTimeProps> {
    let setPivot = !this.state.projectType ? 
        this.state.projectMasterPriorityChoice :
        this.state.projectUserPriorityChoice ;
    return (

            <Pivot 
              style={{ flexGrow: 1, paddingLeft: '10px' }}
              linkSize= { pivotOptionsGroup.getPivSize(this.props.pivotSize) }
              linkFormat= { pivotOptionsGroup.getPivFormat(this.props.pivotFormat) }
              onLinkClick= { this.onLinkClick.bind(this) }  //{this.specialClick.bind(this)}
              selectedKey={ setPivot }
              headersOnly={true}>
                {this.createPivots(this.state,this.props)}
            </Pivot>

)}
```
#### Actual behavior:
The problem is that **the Pivot Headings update based on my state changing BUT the selectedKey does not**.  When I go into debugger and the pivot re-renders, my setPivot variable  is showing the correct value I want for selectedKey , but it does not automatically change which pivot is selected.  It just seems to remember the same pivot index... like the 2nd one for instance.

#### Expected behavior:
I would expect that on rendering, the pivot would show the correct item "isSelected" when I pass in that selectedKey.

NOTE that if I create 2 copies of the \<Pivot\>\<\/Pivot\> object in my code (shown like below), and in each one force display block or none, I get the desired behavior.  But it requires me to have 2 copies of the code when I really only need one.

```typescript
  public render(): React.ReactElement<ITrackMyTimeProps> {
    let setPivot = !this.state.projectType ? 
        this.state.projectMasterPriorityChoice :
        this.state.projectUserPriorityChoice ;
    return (

            <Pivot 

               //NOTE THIS IS THE ONLY LINE THAT IS DIFFERENT BEWTEEN PIVOTs
              style={{ flexGrow: 1, paddingLeft: '10px', display: (this.state.projectType === true ? "none" :"block")}}


              linkSize= { pivotOptionsGroup.getPivSize(this.props.pivotSize) }
              linkFormat= { pivotOptionsGroup.getPivFormat(this.props.pivotFormat) }
              onLinkClick= { this.onLinkClick.bind(this) }  //{this.specialClick.bind(this)}
              selectedKey={ setPivot }
              headersOnly={true}>
                {this.createPivots(this.state,this.props)}
            </Pivot>
            <Pivot 

               //NOTE THIS IS THE ONLY LINE THAT IS DIFFERENT BEWTEEN PIVOTs
              style={{ flexGrow: 1, paddingLeft: '10px', display: (this.state.projectType === true ? "block" :"none")}}


              linkSize= { pivotOptionsGroup.getPivSize(this.props.pivotSize) }
              linkFormat= { pivotOptionsGroup.getPivFormat(this.props.pivotFormat) }
              onLinkClick= { this.onLinkClick.bind(this) }  //{this.specialClick.bind(this)}
              selectedKey={ setPivot }
              headersOnly={true}>
                {this.createPivots(this.state,this.props)}
            </Pivot>

)}

```

### Help requested:
I'm building my first SPFx webpart so I'm not sure if this is a bug, limitation in the code, or operator error.

**Comment by micahgodbolt** [comment]
The issue you mention has to do with where focus is placed when returning to the pivot. If you are trying to modify the selectedKey via state, here is a simple example.

https://codepen.io/micahgodbolt/pen/RwNKBgq?editors=1010

Does this help?

**Comment by mikezimm** [comment]
@micahgodbolt , Thanks for the codepen.

I forked your pen and tried to put my logic in it.

Basically,
You press the pivot header, it should call the onLinkClick method and know the header it was on and update state including what pivot was clicked... that way when you toggle back to this pivot, it knows the right one to pick.

Then if you press the Toggle button, it would update a number of other states my Pivot is based on including the array with the pivot headings and what the default pivot was.

Unfortunately, I can't seem to get my function to work in code-pen... have not worked outside of my VS code project so I probably have the syntax a little off.

[my fork](https://codepen.io/MikeZimm/pen/jOEBrmO?editors=0011)

Thanks again for any help :)

**Comment by micahgodbolt** [comment]
This doesn't appear to be an issue with the control, so I'm going to close this issue until we can get a reduced repro of the issue.

**Comment by micahgodbolt** [comment]
@mikezimm I'd recommend starting from a simple, working state and continuing to add functionality until something doesn't work.
