### ISSUE TITLE
Screen reader reads the SearchBox placeholder twice

### ISSUE THREAD

**Issue by AbdelrhmanMagdy** [OfficeDev/office-ui-fabric-react#11503]
### Environment Information
- **Package version(s)**: 7.64.2
- **Browser and OS versions**: chrome / windows

### Description:
The screen reader read the place holder of the search box twice.

### reproduction in a codepen:
https://codepen.io/abdelrhmanmagdy/pen/BaypYbG

Run any screen reader tool and go to the search box and observe the issue.

### Observation:
The screen reader read both of aria-label and the place holder of the element ..
if there is no aria label provided for the search box it'll take the place holder value by default
so the screen reader read the aria-label and placeholder which is the same in this case

**Comment by micahgodbolt** [comment]
I can't repro this with Narrator on edge or chrome. The text is only spoken once. 

The question of "should placeholder text be replicated in aria-label" is totally valid though.

**Comment by micahgodbolt** [comment]
Yeah, a little more digging in and it seems quite redundant to have aria-label set to the placeholder value. This isn't consistent with other components that accept placeholder text either.
