### ISSUE TITLE
ContextualMenu Button: custom rendered menu items don't close menu

### ISSUE THREAD

**Issue by Divya-2307** [OfficeDev/office-ui-fabric-react#11505]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out)

### Describe the issue:
While using  commandbar with some overflowitems,  If the overflow menu is opened and one of the items is clicked, the focus doesn't return back to the overflow button if the menu items are rendered with CommandBarButton(using onRender)

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/dsru/pen/ZEYLeJR?editors=0010 
or
 https://codepen.io/micahgodbolt/pen/JjoEvJz?editors=0010

#### Actual behavior:

Menu is not closing when the 2nd item in the menu is selected which is rendering using CommandBarButton

#### Expected behavior:

Menu should close & focus should shift to the overflow button

**Comment by micahgodbolt** [comment]
not 100% sure if this is a bug, or if we need to document how onRendered items can dismiss menu.

**Comment by ecraig12345** [comment]
`ICommandBarItemProps.onRender` takes a second parameter `dismissMenu` which can be used to dismiss menus from custom-rendered items. Here's a simplified codepen where clicking the buttons dismisses the menu. https://codepen.io/ecraig12345/pen/rNaybqK?editors=0011

We could potentially add an example of this, but I'm not sure what a realistic case to use in the example would be (just rendering a plain button doesn't look very nice).

**Comment by Divya-2307** [comment]
This works!!
