### ISSUE TITLE
CSS Modules: People Picker Dropdown styles

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#1151]
some of the padding seems to be missing
![image](https://cloud.githubusercontent.com/assets/1434956/23439178/61aa07d2-fdca-11e6-9dcc-e3a33642874a.png)

LOTS of padding seems to be missing. 
![image](https://cloud.githubusercontent.com/assets/1434956/23439162/50652b1e-fdca-11e6-9e89-22bf3414fe6f.png)

**Comment by dzearing** [comment]
Fixed.
