### ISSUE TITLE
[Programmatic Access- Dual Write- Save] Name is not defined for control "expand and collapsed" error button.

### ISSUE THREAD

**Issue by Saurabh19Aug** [OfficeDev/office-ui-fabric-react#11518]
Bug copied from Dual write : https://msazure.visualstudio.com/OneAgile/_workitems/edit/5700035

**#URL** :https://tip.dataintegrator.trafficmanager.net/dualWrite?axenv=focdstest1envce1329c483fdc3a3devaos.cloudax.dynamics.com

Accessibility Insights! - Identify accessibility bugs before check-in and make bug fixing faster and easier.

External Bug Process: If this bug belongs to external team, mark it as resolved/done and assign it back to the tester with notes on where to file/route the bug. For more information please use this Link. 
“HCL Staff should not log any third party external bugs. Should be routed to EDAD team”.

Please reach out to C&AI Teams channel for any process related queries.

**User Experience:** 
User would find difficulty to identify the controls if name is not defined for controls as they won't get the context of that control and also they won't be able to perform functionality  relevant to that control. 

**Repro Steps:**
1. Launch the URL:https://tip.dataintegrator.trafficmanager.net/dualWrite?axenv=focdstest1envce1329c483fdc3a3devaos.cloudax.dynamics.com
2. Sign in with Valid credentials.
3. Dual Write entity Maps screen appearing.
4. Navigate to any entity and select context menu button.
5. Navigate to "Entity mapping" and select it .
6. Navigate to "Save" button on top of the screen and select it.
7. Open Developer tool using F12 key and navigate to double upper arrow icon button present in error message
8. Verify whether name is defined for the controls or not.

**Actual Result:**
Name is not defined for control ‘‘expand and collapsed" error icon button, present in error message which is appearing on the screen after activating save button, screen reader announcing only control type as "Button".

**Expected Result:**
Name should be define for control as “Error message button‘’ present in error message which is appearing on the screen after activating save button, so that user can get correct information about control. 

**Note:**
Similar issue exist with Chrome.
Tooltip also not defined for ‘‘expand and collapsed" error icon button.
This issue also exist on the following scenario:
Add entity map->Add entity dialog box

**MAS Reference:**
MAS 4.1.2 - Name, Role, Value

![MAS4 1 2_name error button](https://user-images.githubusercontent.com/59047554/71158577-320fde80-226a-11ea-8be6-013343d455c8.PNG)

**Comment by ecraig12345** [comment]
This is not an issue with Fabric, it's an issue with how you're using the control. As demonstrated in the [MessageBar documentation](https://developer.microsoft.com/en-us/fabric#/controls/web/messagebar), you need to set the MessageBar's `overflowButtonAriaLabel` property to an appropriate label in your code. For a more specific example, see https://codepen.io/ecraig12345/pen/vYExmoW?editors=0010

Also, **please** remember that this is a public forum and refrain from posting private issue links or product screenshots in the future! If you need to provide more context, you can file the issue and wait for it to be assigned, then contact the assignee privately on Teams.
