### ISSUE TITLE
Modal ignoreExternalFocusing props doesn't work

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#11514]
### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**: chrome windows 10

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/ipip2005/pen/JjoExPj

Click "Open dialog" button
Then click "Close" button in the dialog.

#### Actual behavior:

It focuses on the "Open dialog" button.

#### Expected behavior:

While I'm specifying `ignoreExternalFocusing` to `true`, I expect focus will be lost.

Modal ignoreExternalFocusing props doesn't work because it's not passing the corresponding props to Popup
Should it pass 
```
            shouldRestoreFocus={!this.props.ignoreExternalFocusing}
```
To Popup?

**Comment by ecraig12345** [comment]
Thanks for reporting this! Will have to confirm with some other team members, but I think the change you suggested makes sense.

**Comment by zoarif** [comment]
What is the ETA for this fix? I also need to use the prop ``ignoreExternalFocusing`` but it is not working as expected as mentioned in the bug.
