### ISSUE TITLE
Children inside modal component unmount after closing the modal. 

### ISSUE THREAD

**Issue by adityasadhu** [OfficeDev/office-ui-fabric-react#11529]
### Environment Information

- **Package version(s)**: ^7.71.0

### Describe the issue:

I have a modal with details list as a child component. every time I close the modal the children components inside the modal unmount. hence I cannot make any state changes and try to retain after closing it.  in this case details list component. 

#### Actual behavior:

the children components of the modal are unmounting when closing  

#### Expected behavior:

the children components of the modal should not be unmounted when closing  

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Blocking)

codepen link: https://codepen.io/adityasadhu/pen/wvBJERg

**Comment by micahgodbolt** [comment]
In our current design, the dialog (or modal it is based upon) is not at all rendered unless 'isOpen' is set to true

https://github.com/OfficeDev/office-ui-fabric-react/blob/10045d123d9bc892d1b99b1ff123111b40194ab8/packages/office-ui-fabric-react/src/components/Modal/Modal.base.tsx#L171-L173

This alleviates unnecessary DOM if a page contained multiple modals.

If you don't want the modal to actually unmount, you can avoid toggling 'isOpen' and just render the modal at page load with css style set to `display: none`

https://codepen.io/micahgodbolt/pen/LYEWawr

You could also go so far as to open it the first time with 'isOpen' and then hide it with CSS on close.

**Comment by adityasadhu** [comment]
thanks for the quick response.
