### ISSUE TITLE
Property 'Id' not working for SwatchColorPicker

### ISSUE THREAD

**Issue by LukeOwlclaw** [OfficeDev/office-ui-fabric-react#11520]
### Environment Information

- **Package version(s)**: 7.74.2

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/LukeO/pen/gObgVLp

#### Actual behavior:

`<SwatchColorPicker id={"someid"} ... ` has no effect. There is no component with id 'someid' (only the color fields will receive an id starting with 'someid-...'.

#### Expected behavior:

There is should be a component with id 'someid' which can be used to reference the picker, e.g. for [adding a label for the picker](https://github.com/OfficeDev/office-ui-fabric-react/issues/11480#event-2885588433).

**Comment by ecraig12345** [comment]
That definitely seems wrong--thanks for reporting! I'll work on a fix.
