### ISSUE TITLE
[Settings] Drop down is closed when the user tries to scroll the drop down menu of language settings (IE 11 Specific)

### ISSUE THREAD

**Issue by rudolf-testlio** [OfficeDev/office-ui-fabric-react#11522]
### Environment Information

OS: Windows 10 Home, 64 bit, 1903
Browser1: IE 11
Browser2: Chrome 78.0.3904.108
Screen resolution: 1920x1080
Testable App version: 2.6.0
Network: Wifi
Location: Germany
Reproducibility rate for browser 1: 3/3
Reproducibility rate for browser 2: 0/3

### Please provide a reproduction of the bug in a codepen:

1. Settings > Language > Try to scroll the drop down menu

#### Actual behavior:

Drop down is closed when the user tries to scroll the drop down menu of language settings

#### Expected behavior:

User should be able to scroll the language drop down menu and should be able to choose any other language

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low
[2019-11-23_22h59_03.mp4.zip](https://github.com/OfficeDev/office-ui-fabric-react/files/3983664/2019-11-23_22h59_03.mp4.zip)

Reference: https://alexanderplatz.visualstudio.com/To-Do/_workitems/edit/32034

**Comment by ecraig12345** [comment]
This panel doesn't appear to use Fabric components, so you'll need to contact the team that made the panel instead.
