### ISSUE TITLE
ChoiceGroupOption is exported in two places and that is causing errors

### ISSUE THREAD

**Issue by sushruth** [OfficeDev/office-ui-fabric-react#11534]
### Environment Information

- **Package version(s)**: 7.76.0
- **Browser and OS versions**: Any browser / Win 10

### Please provide a reproduction of the bug in a codepen: N/A

Related to #10017 and #9661 - 

Looks like ChoiceGroupOptions is exported twice in this hierarchy - 

```
office-ui-fabric-react/src/index.ts

    export * from './ChoiceGroup.ts';
    export * from './ChoiceGroupOption.ts';

office-ui-fabric-react/src/ChoiceGroupOption.ts

    export * from './components/ChoiceGroup/ChoiceGroupOption/index.tsx'; // here

office-ui-fabric-react/src/ChoiceGroup.ts

    export * from './components/ChoiceGroup/index.tsx';

office-ui-fabric-react/src/components/ChoiceGroup/index.ts

    export * from './ChoiceGroup.tsx';
    export * from './ChoiceGroup.base.tsx';
    export * from './ChoiceGroup.types.tsx';
    export * from './ChoiceGroupOption/index.tsx'; // here

office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroupOption/index.ts

    export * from './ChoiceGroupOption.tsx';
    export * from './ChoiceGroupOption.types.tsx';
```

This is leading to similar error as #10017 and #9661 - 

```
Uncaught TypeError: Cannot redefine property: ChoiceGroupOption
```

#### Actual behavior:

Error should not be present.

#### Expected behavior:

compile process shows errors.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: `jest` tests and `parcel` bundled projects.

**Comment by ecraig12345** [comment]
It's odd that we have a top-level file for ChoiceGroupOption. It's been there long enough (was added over a year ago in #6492) that I'm hesitant to remove it, but I can get rid of the export from it in the main index file.

**Comment by sushruth** [comment]
@ecraig12345 Thank you! There are actually multiple such exports within the whole codebase. Doing a pass for all such instances could be great for `jest` and `parcel` users and also IMO feels a tiny bit saner.

**Comment by ecraig12345** [comment]
Do you have a list of the duplicate exports or know how to find them? (This isn't something we've run into with our toolchain internally.)

**Comment by sushruth** [comment]
@ecraig12345  Maybe using parcel to build the dev page would expose those. I'll try to submit a PR if that works and if that's ok
