### ISSUE TITLE
IContextualMenuItem.onClick isn't being fired... onDismiss is instead

### ISSUE THREAD

**Issue by rickyp-ms** [OfficeDev/office-ui-fabric-react#1153]
### Bug Report

- __Package version(s)__: 1.13.00
- __Browser and OS versions__: N/A

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No - Already working on fix for dialog, don't have time

Requested priority: Normal

#### Describe the issue:

It seems the IContextualMenuItem.onClick isn't being called.

#### Actual behavior:

The IContextualMenu.onDismiss is called, not the onClick which means the action never fires.

#### Expected behavior:

Here is a test... you should be able to put it in ContextualMenu.test.tsx and see what I mean

    it('will call onClick and not onDismiss', () => {

      let onDismissSpyCalled = false;
      let onDismissSpy = () => { onDismissSpyCalled = true; };

      let onItemSpyCalled = false;
      let onItemSpy = () => { onItemSpyCalled = true; };

      const items: IContextualMenuItem[] = [
        {
          name: 'TestText 1',
          key: 'TestKey1',
          className: 'testkey1',
          onClick: onItemSpy
        },
      ];

      ReactTestUtils.renderIntoDocument<ContextualMenu>(
        <ContextualMenu
          items={ items }
          onDismiss={ onDismissSpy }
        />
      );

      expect(onItemSpyCalled).to.be.true;
      expect(onDismissSpyCalled).to.be.false;
    });

### If applicable, please provide a codepen repro:

n/A

**Comment by dzearing** [comment]
I would expect it to call onClick AND onDismiss... no?

**Comment by dzearing** [comment]
Just validated. We see onClick called and onDismissed called.

http://codepen.io/dzearing/pen/ryajrG?editors=1011

**Comment by dzearing** [comment]
Reopening just to give you a chance to maybe provide more info on the scenario you're trying

**Comment by rickyp-ms** [comment]
Closing...

Seems my test had issues. Looks like the issue is on my side. My apologies! That said, still no idea why on our product I'm only getting the onDismiss to fire...
