### ISSUE TITLE
Documentation: Failed to compile the example of DetailsList - Custom Item Rows

### ISSUE THREAD

**Issue by ytingyeu** [OfficeDev/office-ui-fabric-react#11546]
### Environment Information

- **Package version(s)**: 7.64.1

### Describe the issue:

Failed to compile the example code from [DetailsList - Custom Item Rows](https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/customitemrows)

#### Actual behavior:
Type check failed
```
Type '(props: IDetailsRowProps) => JSX.Element' is not assignable to type 'IRenderFunction<IDetailsRowProps>'.
  Types of parameters 'props' and 'props' are incompatible.
    Type 'IDetailsRowProps | undefined' is not assignable to type 'IDetailsRowProps'.
      Type 'undefined' is not assignable to type 'IDetailsRowProps'.ts(2322)
```

#### Other information
This issue was reported in https://github.com/OfficeDev/office-ui-fabric-react/issues/10012 and also relates to https://github.com/OfficeDev/office-ui-fabric-react/pull/10225. As @KevinTCoughlin suggested in https://github.com/OfficeDev/office-ui-fabric-react/issues/10012 I am able to solve the issue by setting `strictFunctionTypes: false`.

**Comment by micahgodbolt** [comment]
Is this issue fixed in a more current version of Fabric 6.x? 6.13.4 is quite old, and any fix applied to be applied to the current version of 6.

Please provide a codepen repro in a current version of Fabric (6 or 7) so that we can triage the issue.

**Comment by ytingyeu** [comment]
I guess somehow I misread the Fabric version as npm version, it should be 7.64.1. However even I upgrade to 7.76.2, type checking by vscode still raises a type check error. 

This [codepen ](https://codepen.io/ytingyeu/pen/xxbrBdw) is exported from the documentation and it works fine. But again I have to disable `strictFunctionTypes` to pass the type check locally.

**Comment by micahgodbolt** [comment]
@ytingyeu is this the only example you have issues with? Or do all of the details list examples have the same problem?

**Comment by micahgodbolt** [comment]
Nevermind, I get it. The typings were too loose and strictFunctionTypes picked it up. Fix coming
