### ISSUE TITLE
Can't tell if checkbox is checked in high-contrast-mode

### ISSUE THREAD

**Issue by omers4** [OfficeDev/office-ui-fabric-react#11540]
### Environment Information

- **Package version(s)**: 6.162.0
- **Browser and OS versions**: Edge 79, Windows 8

### Describe the issue:

When setting high contrast mode to "On" on Windows (black on white, white on black), it's impossible to tell if the checkbox is checked or not (it remains the same color and background). However, on hover the check mark is visible due to usage of -ms-high-contrast property.

### Please provide a reproduction of the issue in a codepen:

It's impossible to give a reproduction in codepen, since the high-contrast mode should be activated from windows settings. once you turn on high contrast mode, you will be able to see immediately that checkbox remains blank white/black when checking it, instead of showing the check mark.
For example, here
https://developer.microsoft.com/en-us/fabric#/controls/web/checkbox

#### Actual behavior:

When checking a checkbox in high contrast mode, it remains blank instead of showing the checkmark. (hover works, but the checking itself isn't)

#### Expected behaviour:

On high contrast mode, and when checkbox is checked, the check mark should be visible and the background should be inverted from what it was.

### Documentation describing expected behavior

https://developer.microsoft.com/en-us/fabric#/controls/web/checkbox

**Comment by cliffkoh** [comment]
Hi @omers4, I cannot repro with the traditional Microsoft Edge (I can repro with Chromium Edge - but Chromium Edge isn't quite at parity with high contrast handling yet). This is what I see..

![image](https://user-images.githubusercontent.com/1003246/71378235-faf84080-257b-11ea-91be-f9595879fb1b.png)

**Comment by omers4** [comment]
Hi, I did use Edge Chromium. Thought it will behave the same as Edge.
Thank you

**Comment by cliffkoh** [comment]
Hi @omers4, Edge Chromium does not have support for High Contrast at the same parity as Edge yet. It is something they're working on though... You could use file feedback to Edge Chromium for this issue you observed :)

**Comment by xugao** [comment]
possibly related to #11742
