### ISSUE TITLE
"DetailsList "  - Office fabric Control, Column Header don't have  is required option and  aria-label.

### ISSUE THREAD

**Issue by v-jashr** [OfficeDev/office-ui-fabric-react#11549]
When i am using "DetailsList "  - Office fabric Control

I want show particular , Column Header  is required and give proper aria label. But i have not found any option for column is required  and aria-label for column header.

**Expected:**  it should speak column header and it is required filed.

**Comment by micahgodbolt** [comment]
Do you need a single column header to be required, or the entire details list? Do you have a visual example/demo of what you're trying to do?

**Comment by v-jashr** [comment]
i want one feature that is , when i Should provide able to provide isrequired filed to specific column, only for that column asterisk sign should appear and aria label / narrator should read that column ,as required filed. can you please help for solution.

**Comment by micahgodbolt** [comment]
Details list is not meant for data entry. It is for selecting individual items from a list of detailed items. Its possible to add input fields to a cell, but that is not a scenario we optimize the control for. 

Adding support for passing HTML attributes to the header is possible, but i'm not sure if that alone would solve your problem. You might need to consider building a custom control out of a table and inputs.
