### ISSUE TITLE
TooltipHost hover box in dark mode does not have borders

### ISSUE THREAD

**Issue by mizeljko** [OfficeDev/office-ui-fabric-react#11541]
### Environment Information

- **Package version(s): 7.74.1
- **Browser and OS versions: Chrome

### Describe the issue

When going over the TooltipHost element in dark mode, the box blends with the environment and the borders are not visible.

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/mizeljko/pen/qBEmLNo

Example contains light color theme (which works ok) and dark colored theme that has a described issue

#### Actual behavior:

When going over the TooltipHost element in dark mode, the box blends with the environment and the borders are not visible.

#### Expected behavior:

Borders need to be light colored and visible in dark mode

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: Azure for Machine Learning

**Comment by micahgodbolt** [comment]
dup of #11542. Same issue, same solution/feature request.
