### ISSUE TITLE
 After activating "Go to today" button focus is moving to Previous and Next months buttons

### ISSUE THREAD

**Issue by SyedRehmanRazvi** [OfficeDev/office-ui-fabric-react#11551]
User Experience:
Users who rely on keyboard for navigating between elements are getting impacted as focus is moving to different control after activating "Go to today".

Repro Steps:
Step 1: Open https://fabricweb.z5.web.core.windows.net/oufr/7.76.1/#/examples/calendar in edge browser
Step 2: Navigate to "Click for Calendar" button and activate using keyboard.
Step 3: Change date in opened calendar
Step 4: Now "Go to today" and activate it.
Step 5: Verify focus after activating "Go to today" and activate it.

Actual: 
After activating "Go to today" button focus is moving to Previous and Next months buttons

Expected.
 After activating "Go to today" button focus should available on current date.

![image](https://user-images.githubusercontent.com/53210862/71414256-0e8ad080-267c-11ea-9f2b-f49a303f50c5.png)

**Comment by micahgodbolt** [comment]
This bug only appears in this 'calendar in a callout' example. The control itself works fine.

**Comment by micahgodbolt** [comment]
Also, this appears to be Old Edge only.
