### ISSUE TITLE
Screen reader repeats the Details list header column value tree times

### ISSUE THREAD

**Issue by AbdelrhmanMagdy** [OfficeDev/office-ui-fabric-react#11557]
### Environment Information

- **Package version(s)**: 7.75.0
- **Browser and OS versions**: Windows 10

### Issue description:

When navigating the header of the details list with NVDA narrator .. the narrator reads the header three times .. it's a confusing redundant information.

### Codepen reproduction:

[Bug Reproduction](https://codepen.io/abdelrhmanmagdy/pen/povwQLB?editors=0010)

Reproduction steps:
1- turn on NVDA or any screen reader
2- go to the table header name column using the tab and arrows
3- observe the issue

#### Actual behavior:

The narrator reads: "name name column two clickable name"

#### Expected behavior:

The narrator shouldn't reads any redundant information about the column name

**Comment by micahgodbolt** [comment]
I can't repro this in Edge/Narrator, which is our primary compatibility target. If you see a problem with the existing markup we're happy to correct it, but otherwise we can only assume it is a bug in NVDA.
