### ISSUE TITLE
Fabric Icons is missing MS Planner

### ISSUE THREAD

**Issue by gretchunkim** [OfficeDev/office-ui-fabric-react#11559]
### Environment Information

- **Package version(s)**: (fill this out) Fabric Icons  Web https://developer.microsoft.com/en-us/fabric#/styles/web/icons#available-icons
- **Browser and OS versions**: (fill this out if relevant)

### Describe the issue:

Fabric Icons is missing MS Planner icon (Group with checkmark on top of 3 people) -  MS Planner icon. See link for icon 
https://www.pcmag.com/review/356065/microsoft-planner

#### Actual behavior:

MS Planner icon is missing from Fabric Icons

#### Expected behavior:

MS Planner icon (Family) in Fabric Icons web. 

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) Y. 

Requested priority: (Blocking, High, Normal, Low). Normal

Products/sites affected: (if applicable): All sites using Fabric icon

**Comment by micahgodbolt** [comment]
Existing Planner Logo:

![image](https://user-images.githubusercontent.com/1434956/71492496-6fd1b180-27ec-11ea-9378-cfd45d6e0321.png)

New Planner Logo:

![image](https://user-images.githubusercontent.com/1434956/71492512-95f75180-27ec-11ea-89ac-5cee00a44239.png)

**Comment by gretchunkim** [comment]
@micahgodbolt so that's logo and not the MS Planner Fabric icon (black and white). [EBDA](url)

**Comment by khmakoto** [comment]
Hi @gretchunkim, if you use the `PlannerLogo` name in the `Icon` component I think you get what you're expecting:

![image](https://user-images.githubusercontent.com/7798177/71691632-838d9280-2d6d-11ea-8831-c22e9f7e8390.png)

Let me know if this is not your expectation.

**Comment by gretchunkim** [comment]
Now I see Plannerlogo.The Planner icon logo wasn't available 7 days ago, and closest one was Family icon.
