### ISSUE TITLE
[Screen Reader - Microsoft Form Pro - Email] Keyboard focus is going on disable controls i.e embed first question and default template using arrow keys

### ISSUE THREAD

**Issue by sonimishra** [OfficeDev/office-ui-fabric-react#11555]
**User Experience:**
Screen reader user will get confused with the control type if Keyboard focus is going on disable controls i.e embed first question, default template using arrow keys due to this screen reader user will not be able to get the state information of disabled control.

**Note:** User credentials should NOT be included in the bug.

**Repro Steps:**
1. Open URL: https://forms.office-int.com/ and login using valid credentials.
2. Navigate to any created survey and select it.
3. Navigate Send button present at the top and select it.
4. Navigate to Embed tab and select it. Email screen will appear.
5. Navigate to on Email screen.
6. Verify the issue.
 
**Actual Result:**
Keyboard focus is going on disable controls i.e embed first question, default template using arrow keys.

**Expected Result:**
Keyboard focus should not go on disable controls i.e embed first question, default template using arrow keys.

**Note:** 
Same issue exist with disabled controls 'Save, delete, edit' present on same page.

**MAS Reference:**
MAS 4.1.2 - Name, Role, Value
 
**Reference Links:**

    Accessibility Insights! - Identify accessibility bugs before check-in and make bug fixing faster and easier.
    **External Bug Process**: If this bug belongs to external team, mark it as resolved/done and assign it back to the tester with notes on where to file/route the bug. For more information please use this Link. “HCL Staff should not log any third party external bugs. Should be routed to EDAD team”.
    Please reach out to C&AI Teams channel for any process related queries.
![MAS4 1 2_Disable state not defined](https://user-images.githubusercontent.com/30456910/71465500-d4880e80-27e2-11ea-88a6-028948d48148.png)

Please find below details:
Fabric component is command bar, Please refer below link :
https://developer.microsoft.com/en-us/fabric#/controls/web/commandbar

**Comment by micahgodbolt** [comment]
I was able to decipher from your screenshot that your concern is that disabled command bar items recieve focus. 

This is 100% intention as per #912, and consistent with other disabled nav/list items
