### ISSUE TITLE
[Keyboard Navigation - Panel]: In forward navigation tooltip is not displaying for panel flyouts.

### ISSUE THREAD

**Issue by SyedRehmanRazvi** [OfficeDev/office-ui-fabric-react#11568]
User Experience:
Congnitive users who depends on keyboard are facing difficulty as tooltip is not displaying for panel flyouts.

Test Environment:
OS: Windows 10
Version: 2004(OS Build 19536.1000)
Browser: Microsoft Edge (44.19536.1000.0)
URL: https://fabricweb.z5.web.core.windows.net/oufr/7.76.2/#/examples/panel

Repro Steps:
Step 1: Open the above URL in Edge browser.
Step 2: Navigate to "Hidden in dismiss" panel element and activate it.
Step 3: Navigate in the flyout in forward navigation and verify whether tooltip is displaying for close button or not.

Actual:
In forward navigation tooltip is not displaying for panel flyouts.

Expected:
In forward navigation tooltip should display for panel flyouts.

MAS Reference
MAS1.3.3 Sensory Characteristics
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={1823da5a-e8fb-4e63-b881-7eccb312c358}
![image](https://user-images.githubusercontent.com/53210862/71509776-86dad700-28b2-11ea-9e36-21d1829bbdae.png)

**Comment by micahgodbolt** [comment]
The button's tooltip is due to a title attribute being passed in. Standard html title's do not display on buttons when focused, so there is no reason it should display here.
