### ISSUE TITLE
First lable should be icon insted of label in react breadcrumb

### ISSUE THREAD

**Issue by sankaryeturi** [OfficeDev/office-ui-fabric-react#11569]
I'm unable to change the label to the icon in fabric-ui react

**Comment by micahgodbolt** [comment]
Are you looking to custom onRender an item?

https://github.com/OfficeDev/office-ui-fabric-react/blob/3580653c25e620c3372e5788ed42bd363f7b3e5c/packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.types.ts#L64
