### ISSUE TITLE
Unable to set custom Icons on Calendar component

### ISSUE THREAD

**Issue by matidomingues** [OfficeDev/office-ui-fabric-react#11572]
### Environment Information

- **Package version(s)**: Current
- **Browser and OS versions**: All

#### Actual behavior:

If the default icon library is not loaded, this results into not having any icon rendered on the Calendar component:

<img width="224" alt="Screen Shot 2019-12-27 at 3 24 57 PM" src="https://user-images.githubusercontent.com/816129/71535745-16858300-28bd-11ea-9392-4ff9fc54af01.png">

We generally avoid this issue by using an icon custom render function, but in the case of the Calendar component there is none.

#### Expected behavior:

Being able to set a render function for the icon.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: Teams for Edu

**Comment by micahgodbolt** [comment]
You can also use `registerIcons` to change what we render for those up and down arrows. Often its easier to change the icons at the app level rather than having to change them on each and every component.

https://codepen.io/micahgodbolt/pen/PdeKEy?editors=0010

**Comment by micahgodbolt** [comment]
Looks like registerIcons resolved the issue for @matidomingues
