### ISSUE TITLE
Dark Theme Contrast Issue for MessageBar Icons

### ISSUE THREAD

**Issue by mizeljko** [OfficeDev/office-ui-fabric-react#11579]
### Environment Information

- **Package version(s)**: 7.74.1
- **Browser and OS versions**: Chrome

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/mizeljko/pen/bGNoErZ

#### Actual behavior:

MessageBar has icons that are unchanged when switching to dark theme. Text and background are changed and in some cases (success, error, blocked, severe warning) the contrast between background and icon is not that good and icon could be made brighter, and in case of warning it is almost invisible.

#### Expected behavior:

Icons for all types of messages are well visible in dark theme.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: Azure for Machine Learning

**Comment by jdhuntington** [comment]
Hi @mizeljko - I believe by specifying `isInverted` when calling `createTheme` several things will fall in to place. Additionally, it's possible to specify several more elements by overriding specific colors in the `semanticColors` aspect of the theme.

I've updated your codepen and shown a few examples here: https://codepen.io/jdh-msft/pen/gObGPVy?editors=0010#0

The specific semantic colors used by various message bar elements can be seen in code at https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/MessageBar/MessageBar.styles.ts#L54

**Comment by micahgodbolt** [comment]
Also note #11542 and that we don't make any promises about controls being fully accessible when you pass in an arbitrary 'dark' theme. We have semanticColors and per-component customizations available via [Customizer ](https://codepen.io/micahgodbolt/pen/wEMGZL)to allow you to ensure that your custom theme is accessible.

**Comment by mizeljko** [comment]
Ok, just to confirm, I should submit these as questions instead of bugs?

Also, in the example above, success icon is made different color by overwriting green in the overall Theme. I am able to do this, but this changes green in some other places too. Is there a way to change the icon color only for the MessageBar? I tried creating a theme and passing as theme prop to MessageBar but it doesn't seem to have effect.

**Comment by micahgodbolt** [comment]
Yeah, the green icon is a place where the component is pulling directly from the palette, so changing that green might affect a number of other things. 

In this case, it's much better to provide scopedSettings via customizer and supply some custom chosen colors that work well with that background. 

https://codepen.io/micahgodbolt/pen/bGNoerY?editors=0011

**Comment by jdhuntington** [comment]
> Ok, just to confirm, I should submit these as questions instead of bugs?

Either way is fine - both help us identify where docs should be improved!
