### ISSUE TITLE
multiple modals z-index 

### ISSUE THREAD

**Issue by adityasadhu** [OfficeDev/office-ui-fabric-react#11577]
### Environment Information

- **Package version(s)**: 7.71.0
- **Browser and OS versions**: (fill this out if relevant)

### Describe the issue:

when working with multiple modals. modal which is selected doesn't come on the top. kind of having multiple windows open and selecting one would push all the other windows behind it. 

#### Actual behavior:
working with multiple modals. modal which is selected doesn't come on the top.

#### Expected behavior:

working with multiple modals. modal which is selected should come on the top. pushing all the open modals behind it. somehow changing zindex of all the modals less than the selected modal

### If applicable, please provide a codepen repro:

https://codepen.io/adityasadhu/pen/rNaGVqv

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? ( No)

Requested priority: ( High)

**Comment by jdhuntington** [comment]
Hi @adityasadhu - I was able to modify your example to pass through specific `z-index` values to the underlying components https://codepen.io/jdh-msft/pen/qBEPbZR?editors=0010

While it does work presently, I would advise finding another way to implement your feature. Modals are designed to block all user interaction while they are the focus of user interaction, then be dismissed. With that in mind, only 1 should exist at a time. I suspect there are many edge cases with hosting multiple modals concurrently that will not work unfortunately, or could break in the future.

**Comment by adityasadhu** [comment]
That solves my issue. was having hard time passing zindex. Thanks.
