### ISSUE TITLE
Pass the original renderer to onRenderLabel in ChoiceGroupOption

### ISSUE THREAD

**Issue by dagoltz** [OfficeDev/office-ui-fabric-react#11575]
#### Describe the feature that you would like added

Currently, the ChoiceGroup component allows you to pass "onRenderLabel" property that is a function used to render the labels instead of the fabric function. This function currently is provided with the original properties but not the original renderer.
If we want to keep the original design but wrap it with another functionality/design - we will have to generate it on our own and even give it an internal class name (ms-ChoiceFieldLabel).

The expected behavior is a 2nd parameter sent to onRenderLabel that is the original renderer (_onRenderLabel) so you will be able to call it and wrap the original rendered label.

#### What component or utility would this be added to

ChoiceGroup / ChoiceGroupOption

#### Have you discussed this feature with our team, and if so, who

No, but this functionality is present in many onRender* functions in fabric. The best example for this is "**onRenderField**" this specific component (ChoiceGroupOption)

FYI @maelgami

**Comment by jdhuntington** [comment]
Hi @dagoltz - this request makes sense, thank you! Would you be interested in submitting a PR to add callback parameter?

**Comment by dagoltz** [comment]
Sure, I'll give it a try
