### ISSUE TITLE
Setup wiki is not specifying minimum yarn version (1.5.1)

### ISSUE THREAD

**Issue by dagoltz** [OfficeDev/office-ui-fabric-react#11589]
### Environment Information

- **Package version(s)**: current master wiki
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

Once trying to set up a development environment using yarn that is previous to 1.5.1, the "yarn" command is failing. (error: TypeError: patterns.map is not a function).
To fix this, you need to upgrade yarn to >=1.5.1.

#### Actual behavior:

The need for yarn>=1.5.1 is not documented here:
https://github.com/OfficeDev/office-ui-fabric-react/wiki/Setup#development-environment

#### Expected behavior:

Document this requirement.

#### Additional info:
similar bug:
https://github.com/apache/incubator-annotator/issues/27
yarn issues:
https://github.com/yarnpkg/yarn/issues/5089
https://github.com/yarnpkg/yarn/issues/5397

### Priorities and help requested:

Are you willing to submit a PR to fix? (**Yes**, No) - but I can't find where to fix wiki files.

Requested priority: (Blocking, High, **Normal**, Low)

Products/sites affected: (if applicable)

**Comment by jdhuntington** [comment]
Thanks for the issue @dagoltz ! Will update accordingly.

**Comment by jdhuntington** [comment]
Added check to verification steps at https://github.com/OfficeDev/office-ui-fabric-react/wiki/Setup#verify-your-environment-works
