### ISSUE TITLE
Windows narrator in IE not reading the combo box list items

### ISSUE THREAD

**Issue by PoojaOtari** [OfficeDev/office-ui-fabric-react#11583]
ReCreating issue as the previous bug was not completed with proper solution
https://github.com/OfficeDev/office-ui-fabric-react/issues/11567

Environment Information
React fabric Package version(s): both versions 6.210.3 and 7.56.1 and tried others as well
Browser and OS versions: IE 11, Windows 10
Describe the issue:
Toggle state (on, off, changes in state) is not read by screen readers in IE 11.

Please provide a reproduction of the issue in a code pen ( IE don't support codepen):
https://developer.microsoft.com/en-us/fabric#/controls/web/combobox

To repro, open the fabric controls demo page in IE 11 and use Narrator while navigating to the combo box and try to select the items. 
Actual behavior:
Narrator won't announce the selected items in the combo box.

Expected behavior:
Narrator should announce the selected items in the combo box.

Documentation describing the expected behavior
Combobox are not accessible if the user doesn't know what item is selected
https://www.w3.org/TR/wai-aria-1.1/#combobox

**Comment by jdhuntington** [comment]
@PoojaOtari Sorry the previous issue wasn't completed successfully. It looks like you opened this issue before the fix was published in a release; can you verify that the issue still persists in 7.77.0?

I am also going to close this issue and reopen #11567 since it is a continuation of the same issue.
