### ISSUE TITLE
In reference to 4020 pull request. 

### ISSUE THREAD

**Issue by ahsanzahid-se** [OfficeDev/office-ui-fabric-react#11590]
Could you please confirm that if  'pointer-events: none' will not show the title upon mouse hover, As I tried your solution but title didn't appear but with  'pointer-events: all' I was able to get the title on mouse hover in **command bar buttons**. Thank you.

https://github.com/OfficeDev/office-ui-fabric-react/pull/4020
 [office-ui-fabric](https://stackoverflow.com/questions/tagged/office-ui-fabric).

Best Regards,
Ahsan Zahid

**Comment by jdhuntington** [comment]
Hi @ahsanzahid-se - Could you clarify what behavior you would like to see, possibly with code on a site like codepen.io? Would help to see exactly what is not working correctly. https://aka.ms/fabricpen works great as a starting place and will let you start writing code straight away.

**Comment by ahsanzahid-se** [comment]
Hi @jdhuntington I have added a code snippet for you and also commented the situation. Please have a look. Thank you.
https://codepen.io/ahsanzahid-se/pen/VwYXKOj?editors=1111

**Comment by jdhuntington** [comment]
@ahsanzahid-se ah I see now. It looks like `pointer-events: all` is the correct solution for ensuring they exist on disabled items (if that was your specific question). 

I put together this example showing a few ways to resolve the pointer events:
https://codepen.io/jdh-msft/pen/NWPYeLa?editors=0110

Note that you were referencing version 5 in your demo which is beyond our support window, but the same principles apply. The ultimate answer is that you should attempt to use the `Customizer` control to override that specific setting. An ok, but less ideal solution is to target the element with the CSS you have and make sure it is specific enough to override the library's default rule.

**Comment by ahsanzahid-se** [comment]
@jdhuntington I think we are good to close this. Thank you for your time and efforts. 

Best Regards,
Ahsan Zahid
