### ISSUE TITLE
[Feature] expanded row

### ISSUE THREAD

**Issue by lvybriage** [OfficeDev/office-ui-fabric-react#11598]
#### Describe the feature that you would like added
when click this row, could see the expanded row. Expanded row to show some message.

#### What component or utility would this be added to
I try to use this example to implement this function [customitemrows](https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/customitemrows), but met some problems.

#### Have you discussed this feature with our team, and if so, who
...

#### Additional context/screenshots
like this picture:
![image](https://user-images.githubusercontent.com/35484733/71710169-e0ed1680-2e35-11ea-8888-dde829bce4b7.png)

**Comment by jdhuntington** [comment]
Hi @lvybriage - Thanks for the request. I will mark this as a feature request, but will also see if I can find a prior example of this working that you might be able to use in the meantime.

**Comment by jdhuntington** [comment]
I've created an example showing the rough basics to getting the custom row renderer to do what you'd like at https://codepen.io/jdh-msft/pen/PowORgm?editors=0010 . Does that help?

**Comment by lvybriage** [comment]
@jdhuntington 
Hi, jdhuntington  The example you provided had helped me so much. Thank you very much! I'll try to do this in my code.
And also, except the open row, I also need to select some rows. Could you do this in a table at the same time?
![image](https://user-images.githubusercontent.com/35484733/71792647-8097e800-3074-11ea-991a-193e73b8e401.png)

Thanks again for your reply. Happy new year!

**Comment by lvybriage** [comment]
> I've created an example showing the rough basics to getting the custom row renderer to do what you'd like at https://codepen.io/jdh-msft/pen/PowORgm?editors=0010 . Does that help?

I try this code in my repo. Met this question:
![image](https://user-images.githubusercontent.com/35484733/71800990-8ac9de80-3094-11ea-86e9-7bcdb962ff17.png)

Do you ever met similar problem?

**Comment by lvybriage** [comment]
When I try this code, it worked. But had some error: when I click one row, all row's expand row is open.

```
private _onRenderRow: IDetailsListProps['onRenderRow'] = props => {
        if (props) {
            const { isExpand } = this.state;
            return (
                <div>
                    <DetailsRow
                        {...props}
                        onRenderCheck={(props) => <div onClick={() => this.setState(() => ({isExpand: !isExpand}))}>＋</div>}
                    >
                    </DetailsRow>
                    {isExpand && <OpenRow trialId={props.item.id}/>}
                </div>
            );
        }
        return null;
    };
```

**Comment by jdhuntington** [comment]
@lvybriage It looks like you're setting `isExpand` on the control rendering the details list. I'd recommend creating a new component and keeping the state there instead.

**Comment by lvybriage** [comment]
@jdhuntington Had fixed this problem! Thanks again.
