### ISSUE TITLE
React dnd not working inside panel body.

### ISSUE THREAD

**Issue by srhyderabad** [OfficeDev/office-ui-fabric-react#11599]
I am trying to render react drag drop inside fabric panel. With dndprovider in panel body, dragSource and dropTargets does not work. Does anyone any suggestions or used a work around for this issue? Below is repro of the issue.

https://codesandbox.io/s/sharp-glade-9v9be

**Comment by jdhuntington** [comment]
Possibly related to #11264 . Will look into this more.

**Comment by jdhuntington** [comment]
@srhyderabad I was able to get the panel to work by passing the `eventBubblingEnabled` prop to the underlying `Layer` of the `Panel`. See this example: https://codesandbox.io/s/sad-sara-jbrmr?fontsize=14&hidenavigation=1&theme=dark

One note - this prop might not be in the version you have enabled in your example, but was introduced before Fabric v7, so there should be an upgrade path if you are not onboarded to fabric 7 yet.

**Comment by srhyderabad** [comment]
> @srhyderabad I was able to get the panel to work by passing the `eventBubblingEnabled` prop to the underlying `Layer` of the `Panel`. See this example: https://codesandbox.io/s/sad-sara-jbrmr?fontsize=14&hidenavigation=1&theme=dark
> 
> One note - this prop might not be in the version you have enabled in your example, but was introduced before Fabric v7, so there should be an upgrade path if you are not onboarded to fabric 7 yet.

Drag and drop still does not work in the example, also I do not see any prop added
