### ISSUE TITLE
Tooltip is not opened when focus is on through keyboard on IconButton of Chrome browser

### ISSUE THREAD

**Issue by HarkeshS** [OfficeDev/office-ui-fabric-react#11601]
Tooltip is not opened when focus is on through keyboard on IconButton of Chrome browser

### Environment Information

OS: Win 10
Browser: Chrome

### Describe the issue:

Tooltip is not opened when focus is on through keyboard on IconButton of Chrome browser

### Please provide a reproduction of the issue in a codepen:
Office app fabric link-https://developer.microsoft.com/en-us/fabric#/controls/web/button
Code pen link--https://codepen.io/Harkesh/pen/jOEawjp?&editable=true

#### Actual behavior:

Tooltip is not opened when focus is on through keyboard on IconButton of Chrome browser

#### Expected behavior:

Tooltip should open when focus is on through keyboard on IconButton of Chrome browser

**Comment by jdhuntington** [comment]
Hi @HarkeshS - unfortunately we can not control the browser's rendering of a tooltip based on a `title` attribute. 
However, Fabric _does_ provide a `TooltipHost` to build alternative tooltips which do work on keyboard focus. Please have a look at https://codepen.io/jdh-msft/pen/WNbXzdE?editors=0010 and let me know if it solves your problem.
