### ISSUE TITLE
Iterate controls of Pivot Tab and lack of documentation

### ISSUE THREAD

**Issue by dipesh-wadhwa** [OfficeDev/office-ui-fabric-react#11612]
Just came around a point where we are using SPFx with office-fabric-controls and I can see it is painful because of lack of documentation and example.

I need help or documentation regarding one issue. 
I need to iterate through controls/fields of Pivot Tab on button click. So, I am using componentRef to refer pivottab and then trying to access this.pivotcomponentRef.current.props.children. But props property is in-accessible.
If I am going through wrong way, please suggest correct way to get fields of Pivot Tab on button click.
![image](https://user-images.githubusercontent.com/46276877/71825093-1bb6af00-30c1-11ea-94bd-5aaf6696b949.png)

**Comment by khmakoto** [comment]
Hi @dipesh-wadhwa, to iterate over the `children` you should not use the `componentRef` property, but rather the `item` parameter that is passed as part of `onLinkClick`. I've created a codepen [here](https://codepen.io/khmakoto/pen/oNgpMJK?editors=0010) with what I think is your desired behavior. Please let me know if this works for you or if you need anything else. Thanks!

**Comment by dipesh-wadhwa** [comment]
@khmakoto Thanks it helped.
I believe you are getting pivot tabs on change event. That's not the objective.
**I want to get all fields from tab 1** _(Fields marked in green in the question)_ on button click instead of tab change event.

Simple Example is shown in below image:
On Click of Get Fields, We want to iterate on controls that are listed in tab 1 i.e., **Stage 1** in this case. So basically loop should give us Field 1, Field 2, Field 3 ..... Field N. (Items marked in green)
![image](https://user-images.githubusercontent.com/46276877/71877391-fff9ea00-314e-11ea-95c4-1861a11feeeb.png)

**Comment by khmakoto** [comment]
Alright, I understand your issue now. There's no baked in way of doing this in our pivot but you can easily do this yourself. I've modified [the codepen](https://codepen.io/khmakoto/pen/oNgpMJK?editors=0010) to reflect how to do this. Let me know if there is anything else I can do to help!

**Comment by dipesh-wadhwa** [comment]
Thanks a lot @khmakoto it helped.
One last question which is not related to this thread but it will be very helpful if you can guide.
Can we trigger "**onGetErrorMessage**" onSubmit or button click?

I know onGetErrorMessage gets trigger onFocusIn and onFocusOut. Is it possible to trigger onSubmit or buttonClick?
I will close thread once received response.

**Comment by khmakoto** [comment]
Hi @dipesh-wadhwa, you're welcome! For the `onGetErrorMessage` question, do you mean for the `TextField` component?
