### ISSUE TITLE
[DetailsList] datasource and part columns

### ISSUE THREAD

**Issue by lvybriage** [OfficeDev/office-ui-fabric-react#11610]
#### Describe the feature that you would like added

The data has 10 columns. But I want to show 5 columns' data. And other column could be added by dynamically.

So, when the table show 5 columns, the dataSource could still had 10 columns?

#### What component or utility would this be added to

I use the `DetailsList` component and find that if I set part columns the table will render nothing.

#### Have you discussed this feature with our team, and if so, who

I don't find thtis fucntion in [document](https://developer.microsoft.com/en-us/fabric#/controls/web)...

**Comment by JasonGore** [comment]
It is not clear to me what you are looking for. I'm not sure what `dataSource` is (it does not match a prop) and I'm not sure which function you can't find. Please cite specific prop names and function names. An example of what you would like to see with a CodePen would help immensely. Thanks!
