### ISSUE TITLE
Question: Including fabric components sass on sp framework

### ISSUE THREAD

**Issue by jonathanhotono** [OfficeDev/office-ui-fabric-react#1162]
I have successfully included and used fabric react on my sp framework general release however I couldn't get the ms-List components styling to come out unless I referenced the fabric components css from cdn. I tried to @import "~office-ui-fabric/dist/sass/Fabric.Components.scss"; however it still doesn't quite work as well. Is there any solution for this?

Thanks

**Comment by micahgodbolt** [comment]
The "List" component doesn't actually have any styles. It is purely a helper component. You're probably looking for something like the detail list https://dev.office.com/fabric#/components/detailslist ?

**Comment by jonathanhotono** [comment]
Hi @micahgodbolt , I am looking for something like the Inbox list https://dev.office.com/fabric#/components/list. I tried to load the css components manually from 2.6.1 version and it works fine, however I'm not quite sure with the versioning system here. What is the latest fabric components css version and where to get it?

**Comment by micahgodbolt** [comment]
Sorry for the delay. If you're still working on this, you can see the custom styles applied to that "Inbox List" example right here.

https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/List/examples/List.Mail.Example.scss

Point being that the List component makes no assumptions of styles. You'll need to apply custom styles like these, or use other styled components inside.

**Comment by kristoferbrown** [comment]
Question appears to be answered. Reopen if there are further questions on this topic.
