### ISSUE TITLE
Display 1st Pivot Item as disabled on page load

### ISSUE THREAD

**Issue by xyz92** [OfficeDev/office-ui-fabric-react#11636]
Question related to: https://github.com/OfficeDev/office-ui-fabric-react/issues/9247

Is it possible to display 1st Pivot Item as disabled on Page Load?

For example: (https://codepen.io/anon/pen/WBaVjq)

If I change the code of 1st Pivot Item as:

<PivotItem
            headerText="My Files"
            headerButtonProps={{
              'disabled': true,
              'style': {color: 'grey'}
            }}
          >

how can I make sure that Pivot 3 is focused on page load (not disabled Pivot Items 1 & 2) like this:

![image](https://user-images.githubusercontent.com/6519992/71939000-0b0c4480-3166-11ea-925e-d43d284993d8.png)

instead of:

![image](https://user-images.githubusercontent.com/6519992/71939032-2a0ad680-3166-11ea-9bb1-511e6ea9c49e.png)

**Comment by xugao** [comment]
@xyz92  - thank you for reporting, this is a bug. while we will fix it, here might be an immediate solution for you: https://codepen.io/xugao/pen/WNbzvxa by using `defaultSelectedKey`

**Comment by xugao** [comment]
@JasonGore helped pointed out that this is not a bug. the correct way to a
