### ISSUE TITLE
BaseButton leaks DOM Node due to closure capture of _this in event handlers

### ISSUE THREAD

**Issue by KevinTCoughlin** [OfficeDev/office-ui-fabric-react#11632]
# Environment Information

- **Package version(s)**: 7.78.2 (6.x & 7.x)
- **Browser and OS versions**: All

### Please provide a reproduction of the bug in a codepen:

After unmount, `BaseButton` retains references to `_this` within the event handlers assigned as props: https://github.com/OfficeDev/office-ui-fabric-react/blob/4c0791ef3bc500efa3ae66f30124aae702a9ed88/packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx#L199 This results in "Detached" DOM Nodes when components utilizing those components are rendered. The browser is unable to garbage-collect the associated memory.

#### Heap snapshot

![image](https://user-images.githubusercontent.com/706967/71923414-d8e8eb80-3141-11ea-8aa7-52257d9f55ff.png)

#### Source

![image](https://user-images.githubusercontent.com/706967/71923483-f027d900-3141-11ea-8d5b-0b34132c947a.png)

#### Actual behavior:

Components which utilize `BaseButton` report their DOM Node(s) as "Detached" on unmount and therefore are not able to be GC'ed.

To test this, perform the following:

1. Enable React production https://github.com/OfficeDev/office-ui-fabric-react/blob/4c0791ef3bc500efa3ae66f30124aae702a9ed88/packages/example-app-base/index.html#L40
1. Visit http://localhost:4322/#/examples/focustrapzone
1. In DevTools, force GC (click trash icon) and capture heap snapshot.
1. For "A  Dialog nested in a Panel", click "Open Panel"
1. Close the Panel
1. In DevTools, force GC (click trash icon) and capture heap snapshot.
1. Compare Snapshot 2 with Snapshot 1
1. Filter by "Detached" and expand `Detached HTMLDivElement`.

#### Expected behavior:

Components which utilize `BaseButton` should have their respective DOM Node(s) GC'ed when unmounted.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: OneDrive / SharePoint and most web properties using Fabric

cc: @JasonGore @dzearing @ecraig12345 @patmill

**Comment by khmakoto** [comment]
Just for visibility here, @KevinTCoughlin and I have been investigating this issue. We _might_ have a fix for this but we'll wait until Kevin verifies it before announcing it to a larger audience.

**Comment by khmakoto** [comment]
This seems to be an issue with React itself: https://github.com/facebook/react/issues/16087

**Comment by aneeshack4** [comment]
Closing as this has been logged with React
