### ISSUE TITLE
<Text>component cannot display 0 inside jsx but can display other numbers

### ISSUE THREAD

**Issue by AparnaPrasad** [OfficeDev/office-ui-fabric-react#11641]
### Environment Information

- **Package version(s)**: 7.78.3
- **Browser and OS versions**:Chrome Browser:79.0.3945.88 (Official Build) (64-bit), OS: Windows 10 Pro v1903

### Please provide a reproduction of the bug in a codepen:
import {Text} from "office-ui-fabric-react"
const x = 0;
<pre><code>
&lt;Text&gt;{x}&lt;/Text &gt;
</pre></code>
#### Actual behavior:
Does'nt display anything
#### Expected behavior:

Should display 0

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by JasonGore** [comment]
When I saw this I instantly knew it was a bug and what the reason for it was. I'm pretty sure [this check](https://github.com/OfficeDev/office-ui-fabric-react/blob/bb72494fc5de1273568f80d8f5b814825ff3c510/packages/office-ui-fabric-react/src/components/Text/Text.view.tsx#L7) is returning early when children is `0`. I created a [quick CodePen](https://codepen.io/jasongore/pen/LYEdYYe) to highlight the issue. Thanks for reporting!

**Comment by JasonGore** [comment]
In resolving this issue we should also just check the repo for any similar render checks and make sure they won't fail under similar circumstances.

**Comment by AparnaPrasad** [comment]
> When I saw this I instantly knew it was a bug and what the reason for it was. I'm pretty sure [this check](https://github.com/OfficeDev/office-ui-fabric-react/blob/bb72494fc5de1273568f80d8f5b814825ff3c510/packages/office-ui-fabric-react/src/components/Text/Text.view.tsx#L7) is returning early when children is `0`. I created a [quick CodePen](https://codepen.io/jasongore/pen/LYEdYYe) to highlight the issue. Thanks for reporting!

Oh yes, I see 0 is a falsy value, so it returns null.
