### ISSUE TITLE
Dropdown, Datepicker, Picker: Standardized way to validate and show errors

### ISSUE THREAD

**Issue by mdellano** [OfficeDev/office-ui-fabric-react#1164]
I had to wrap all these fields in order to make them work as the TextField, so I can have validations per field. It would be great to have an "onGetErrorMessage" and the corresponding UI reaction. 
It is annoying to have so different ways to treat them.
Just a suggestion

Thanks!!

**Comment by battletoilet** [comment]
@mdellano would you mind giving us a few use cases for this issue?

**Comment by tsekityam** [comment]
I want to show an error message on the date picker when a form is submitting, but I found no way to do so.

Here is my use case:

I am working on a SharePoint web part, which is a form for submitting booking requests. There is a `DataPicker` in the form, which is for the date that they want to pick up the items. This field is required but has no default value. I have to validate this field value before the request is sent to the server, such that no value is empty.

`isRequiredErrorMessage` works only when the field loses the focus with empty value.

However, if users never focus on the field, then I have no way to set message to the error label.

I wish that the DatePicker can have `errorMessage`, such that I that do something like
```
render() {
  return (
    <DatePicker
      label="Pick up date"
      isRequired={true}
      minDate={moment().toDate()}
      onSelectDate={this._onSelectDate}
      strings={DayPickerStrings}
      errorMessage={this.state.pickUpDateErrorMessage}
    />
  );
}

shouldSubmitForm() {
  if (isNaN(this.state.pickUpDate)) {
    this.setState({
      pickUpDateErrorMessage: "Can't be empty"
    })
  }
}
```

**Comment by micahgodbolt** [comment]
I think the main concern here is that adding validation to every control will add quite a bit of weight. If anything, we need to remove the built in validation that some components have, and provide a way to generate Forms with built in validation (including validation logic). 

We've already got a Form component in our backlog. I'll close this issue down as the work will be done there. #5582
