### ISSUE TITLE
[Dropdown] Required value indicator (asterisk) disappears on focus

### ISSUE THREAD

**Issue by dev-a11y** [OfficeDev/office-ui-fabric-react#11656]
Asterisk is not visible if required Dropdown without label is focused:
![image](https://user-images.githubusercontent.com/59690753/72065050-8a705400-32dd-11ea-8ed2-4f24c58f42a7.png)

Issue can be observed in the last example 'Required Dropdown' at demo page:
https://developer.microsoft.com/en-us/fabric#/controls/web/dropdown

### Environment Information

- **Package version(s)**: 7.79.0
- **Browser and OS versions**: Chrome 79, Win 10

#### Actual behavior:

asterisk disappears

#### Expected behavior:

asterisk is present regardless of border styling

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

**Comment by micahgodbolt** [comment]
Yeah, we just recently updated the focus border. Can repro.

**Comment by xugao** [comment]
this regressed since [this change](https://github.com/OfficeDev/office-ui-fabric-react/pull/10885/files)
both the focus border and the asterisk use `:after` content. `TextField` is working properly since it's using `:before` for the asterisk. will update to dropdown to align
