### ISSUE TITLE
how to reset CheckBoxs value

### ISSUE THREAD

**Issue by lvybriage** [OfficeDev/office-ui-fabric-react#11651]
### Describe the issue:
Thanks for the gread job. I see this demo [CheckBoxs](https://codepen.io/kkjeer/pen/EOzwYa). And can I reset this checkboxs' checked state? For example, I want to control some checkboxs to be checked and some checkboxs to be not checked in this demo.
Maybe a feature.

### Please provide a reproduction of the issue in a codepen:

[demo](https://codepen.io/kkjeer/pen/EOzwYa)

#### Expected behavior:

when page init, I wish some checkboxs are checked. Because the `CheckBox component` is created by array map rather than static. So, how to do this? Please refer to the `demo` environment...

**Comment by xugao** [comment]
@lvybriage - is this what you asking: https://codepen.io/xugao/pen/MWYVVyy ?

**Comment by lvybriage** [comment]
@xugao Thanks for your reply. It works. 
I think it's more helpful if writes these codePen demos into fabric document.

**Comment by xugao** [comment]
@lvybriage - you are very welcome.
