### ISSUE TITLE
[Dialog][Accessibility] Narrator CAPS + RIGHT to go to next item skips title in header

### ISSUE THREAD

**Issue by fsteffi** [OfficeDev/office-ui-fabric-react#11669]
Environment Details:​​
Browser Versions: Microsoft Edge 44.18362.387.0,Chrome Version 78.0.3904.97
ScreenReader:narrator, nvda2019.2
Windows Version: Windows10​​​

Repro Steps:​​
1. Hit the application URL
2. Repeat the same steps as ( Select application as "Sales hub" from the list of application--> From the change area which is present in the bottom select "App Settings"-->Navigate to "Site Map" and then Navigate to "Goal Management" and select "Forecast Configuration")
3. Fast Track Your Forecast Screen will appears.
4. Click on "Org chart forecast"
5. Forecast Configuration screen will appears
6. Fill all the mandatory field and click on "next button".
7. Again click on next button.
8. Layout and columns screen will appears and then click on +Add from option set button and from the options select "Forecast category" and click on "Choose selected"
9. Auto Configure popup will appears
10.Launch screen reader and navigate to cancel button.

Actual:​
Once navigated to cancel button , use caps+arrow again the announcement is made of the close button.

Same issue is observed in nvda+chrome

Same issue is observed in below screens:
1)Confirm delete popup
2)Delete the column.

Expected:​
The navigation after cancel should go to the heading and the n to the cancel button.

User Impact:​
Screen reader users will receive the information in the wrong sequence .
[A11y_D365ForecastConfiguration_Layoutandcolumns_Auto-configurecolumns_ScreenReader.pptx](https://github.com/OfficeDev/office-ui-fabric-react/files/4044801/A11y_D365ForecastConfiguration_Layoutandcolumns_Auto-configurecolumns_ScreenReader.pptx)

**Comment by xugao** [comment]
@fsteffi - your repro details are your application-specific. in general, pls make your repro simple and minimal, and demo the bug outside of the context of your application code

**Comment by fsteffi** [comment]
@xugao  
Reproduction of the issue in a codepen:
https://fabricweb.z5.web.core.windows.net/oufr/7.22.1/#/examples/dialog
and 
https://developer.microsoft.com/en-us/fabric#/controls/web/dialog

Steps to repro:
Launch screen reader as narrator and open the default dialog when navigating in the dialog using caps+right arrow key the heading is skipped.

[dialog.pptx](https://github.com/OfficeDev/office-ui-fabric-react/files/4052441/dialog.pptx)

**Comment by xugao** [comment]
it seems to be working with CAPS + LEFT arrow key. does repro with RIGHT

**Comment by xugao** [comment]
@fsteffi - this was a narrator issue and it has been fixed in the new Edge browser. since the old Edge is getting deprecated, this is likely something they won't be fixing. i'm going to close this issue since this is not an issue on our side. feel free to reopen if you have further questions
