### ISSUE TITLE
Textfield [type="number"] Edge, up/down keyboard arrow press scrolls whole page

### ISSUE THREAD

**Issue by SaumyaGargMS** [OfficeDev/office-ui-fabric-react#11670]
### Environment Information

- **Package version(s)**: latest
- **Browser and OS versions**: 44.18362.449.0

#### Actual behavior:

In chrome, when up/down keyboard arrows are used, only the numbers change the page does not scroll. But in edge the whole page scrolls with the arrow press.

#### Expected behavior:

Edge behavior should be same as Chrome

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: Bookings App

**Comment by xugao** [comment]
@SaumyaGargMS  - i can't seem to repro in latest Edge using our doc site page: https://developer.microsoft.com/en-us/fabric#/controls/web/textfield

can you double check the behavior you saw was not due to your application code logic?
