### ISSUE TITLE
DetailsList: unable to drag and drop item to the last row

### ISSUE THREAD

**Issue by hecerinc** [OfficeDev/office-ui-fabric-react#11675]
The drag and drop for rows (an example with 2 is enough) is very janky. Sometimes it works, sometimes it doesn't when dragging a row from bottom up. If you try to drag from top down that never works.

### Environment Information

- **Package version(s)**: latest 7
- **Browser and OS versions**: Windows 10. Firefox 73.0a1

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/dbi3j2934/pen/abzGJOG?editors=0010

#### Actual behavior:

Dragging row 2 to row 1 sometimes works, you have to place it in a very specific position for it to work. Dragging row 1 to row 2 (or slightly below or whatever) just doesn't work.

#### Expected behavior:

Whenever the rows overlap the dragged row should replace the destination row in true drag & drop fashion. 

### Priorities and help requested:

Are you willing to submit a PR to fix?  No

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: (if applicable) Mission Control

**Comment by khmakoto** [comment]
Hi @hecerinc, I can confirm that I can repro this behavior in your codepen. I'll start investigating. Thanks for filing the issue!

**Comment by xugao** [comment]
@hecerinc - there is no bug with the component itself, rather the example code we gave was bad.
 Try this: https://codepen.io/xugao/pen/oNXWRQp?editors=0010. Note you can control the insert behavior however you want in `_insertBeforeItem`
