### ISSUE TITLE
Styles are missing when rendering in window.top.document

### ISSUE THREAD

**Issue by FixRM** [OfficeDev/office-ui-fabric-react#11671]
### Environment Information

- **Package version(s)**: 7.1.4
- **Browser and OS versions**: any

#### Actual behavior:

Dialog is rendered without styles

#### Expected behavior:

Not sure if it is a supported scenario, but why not? I have widget that execute js code inside iframe under main page in the same domain. But I need Dialog to open over main window, not inside that iframe. I use window.top.document to point React to render component there and it's ok with that, but styles are injected into iframe's document and not to the top window.

Unfortunately I can't run out of this sandbox as I'm building some kind of widget/plugin for existing CMS. Is it possible to load styles to the same document as main component or directly point them to load to document of my choise?

### Priorities and help requested:

Are you willing to submit a PR to fix? (No, sorry, I'm new here)

Requested priority: (Blocking)

**Comment by xugao** [comment]
@FixRM - could you tell me how you pointed React to render in window.top.document? is it via React portal?

**Comment by FixRM** [comment]
@xugao, I just pass to React.render a reference to dom node in parent window. Yes, it rendered ok except styles

**Comment by FixRM** [comment]
Something like:
`var node = window.top.document.getElementById(someid);
React.render(<App/>, node);
`

**Comment by xugao** [comment]
@FixRM  -  I have confirmed that this is not supported as of today. 
this is essentially the same ask as #3724, I will follow up more on this and see if there is anything we can do in the short/long term

**Comment by FixRM** [comment]
Thanks @xugao, I believe it is the same issue, so we can close this one. I didn't know that React.createPortal exist, so didn't understand what portal you where talking about :)

**Comment by xugao** [comment]
@FixRM - will close this one as duplicate and continue to track your request in #3724
