### ISSUE TITLE
De-couple the library from the icons font

### ISSUE THREAD

**Issue by soryy708** [OfficeDev/office-ui-fabric-react#11672]
#### Describe the feature that you would like added

Allow using a different font for icons

#### What component or utility would this be added to

`<Font>` component and/or its interfaces

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

This library is tightly-coupled with the Microsoft icons font. This is great as long as the font has all the icons you need. However, if I'd like to use a different icons font, I have to build my own components.

A simple way to solve this issue would be to add a `onRender` prop to the Icon component or its interfaces, which would allow overwriting the rendering of the Icon. This will allow me to inject any arbitrary tags and styles in to existing components (e.g. `<i className="far fa-smile-beam"></i>`)

**Comment by xugao** [comment]
@soryy708 - https://github.com/OfficeDev/office-ui-fabric-react/wiki/Using-icons#registering-custom-icons this is how you use your own font.

**Comment by soryy708** [comment]
Oh, neat. I was going off the documentation at https://developer.microsoft.com/en-us/fabric#/controls/web and couldn't find anything about it.

**Comment by xugao** [comment]
@soryy708  - agreed. will look into improving the doc
