### ISSUE TITLE
Click by touch on touchscreens on color rectangle is not working in Safari/Firefox browsers.

### ISSUE THREAD

**Issue by bnslanuj** [OfficeDev/office-ui-fabric-react#11680]
### Environment Information

- **Package version(s)**: All
- **Browser and OS versions**: Safari, Firefox

#### Actual behavior:
For color picker component (https://developer.microsoft.com/en-us/fabric#/controls/web/colorpicker), Click by touch on touchscreens on color rectangle does not change the color in Safari/Firefox browsers, while it is working for Chrome/Edge Chromium browsers.

#### Expected behavior:
Click by touch on touch screens on color rectangle should change the color as this is doing in chrome/edge chromium browsers.

#### Expected fix:
This is because the way the handler (_onMouseMove ) for mouse event is implemented for color rectangle.There is below if condition in _onMouseMove handler code, where ev.buttons is coming as 1 (i.e. primary button usually left key is pressed) for touch event in browsers like Chrome/Edge Chromium whereas it is coming as 0 for Safari/Firefox browsers. 
It seems like this if condition is needed for debugging purpose and this if check should not be there.

Code:
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ColorPicker/ColorRectangle/ColorRectangle.base.tsx
    // If the primary button (1) isn't pressed, the user is no longer dragging, so turn off the
    // event handlers and exit. (this may only be relevant while debugging)
    // tslint:disable-next-line:no-bitwise
    if (!(ev.buttons & 1)) {
      this._disableEvents();
      return;
    }

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: Microsoft Word/Powerpoint Online

**Comment by xugao** [comment]
@bnslanuj - Thanks for opening this issue. I see you are willing to submit a PR. Pls go ahead to do so. We always appreciate bug fixes by any community members :)

**Comment by bnslanuj** [comment]
> @bnslanuj - Thanks for opening this issue. I see you are willing to submit a PR. Pls go ahead to do so. We always appreciate bug fixes by any community members :)

Sure, will raise PR. Thank!

**Comment by bnslanuj** [comment]
@xugao i was trying to push my changes, but i am getting access denied error. I also check the [development workflow](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Development-Workflow), i followed the same steps. Would you know about this error? Do i need any permission for same?

**Error:** 
_PS D:\officeUI\officefabric\office-ui-fabric-react> git push origin HEAD
remote: Permission to OfficeDev/office-ui-fabric-react.git denied to bnslanuj.
fatal: unable to access 'https://github.com/OfficeDev/office-ui-fabric-react.git/': The requested URL returned error: 403_

**Comment by xugao** [comment]
@bnslanuj - you need to create your own fork and make change there: https://github.com/OfficeDev/office-ui-fabric-react/wiki/Setup#creating-your-own-fork
