### ISSUE TITLE
Pivot: Font is overridden by browser default

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#1168]
### Bug Report

- __Package version(s)__: Latest on website
- __Browser and OS versions__: All

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

#### Describe the issue:

Pivot buttons are using the system default font rather than Segoe UI. The `font-family` is set on `ms-Pivot`, but the browser's default button styles later override it. We need to increase the specificity of our styles here to fight off the browser. We can also wait for Fabric React to update to Fabric Core 6.0, which includes some [normalization styles on the `ms-Fabric` wrapper](https://github.com/OfficeDev/office-ui-fabric-core/blob/master/src/sass/mixins/_General.Mixins.scss#L255) to ensure fonts are inherited.

![image](https://cloud.githubusercontent.com/assets/1382445/23531132/c485fa06-ff59-11e6-93dd-1418f8bf1fa0.png)

#### Actual behavior:

The Fabric font stack should be used on all text.

#### Expected behavior:

The browser's default font stack is being used.

**Comment by dzearing** [comment]
This is checked into module-css-updates, which will fix this when merged next Tuesday.
