### ISSUE TITLE
[Screen Reader- Dual Write- Dual Write Entities] In scan mode navigation, Extra tab applies in table header section of entities.

### ISSUE THREAD

**Issue by sonimishra** [OfficeDev/office-ui-fabric-react#11685]
Note: User credentials should NOT be included in the bug.

**Repro steps:**
1. Launch the URL:https://tip.dataintegrator.trafficmanager.net/dualWrite?axenv=focdstest1envce1329c483fdc3a3devaos.cloudax.dynamics.com
2. Sign in with Valid credentials.
3. Navigate to table header section.
4. Verify the narrator focus in table header section using arrow keys.

**Actual Result:**
In scan mode navigation, Extra tab applies in table header section I.e. 'Entity map'.
 
**Expected Result:**
In scan mode navigation, no extra tab should apply while navigating in table header section. Only one key stroke should be use for each element. 

**Note:**
1. This issue exists throughout the application.
2. This issue also exists with Chrome.

**Test Environment:**
OS: Windows 10, Version 1903 (OS build 18960.1000)
Browser:  Edge (44.18895.1000.0), Chrome(78.0.3904.87)
Screen Reader: Narrator, Jaws

**MAS Reference:**
MAS 2.4.3 - Focus Order

Accessibility Insights! - Identify accessibility bugs before check-in and make bug fixing faster and easier.

External Bug Process: If this bug belongs to external team, mark it as resolved/done and assign it back to the tester with notes on where to file/route the bug. For more information please use this Link.
“HCL Staff should not log any third-party external bugs. Should be routed to EDAD team”.

**Attachment**
[MAS2.4.3-Extra tab applies in table header section.zip](https://github.com/OfficeDev/office-ui-fabric-react/files/4053229/MAS2.4.3-Extra.tab.applies.in.table.header.section.zip)

Bug copied from Dual write : 
https://msazure.visualstudio.com/OneAgile/_workitems/edit/5693311

**Comment by xugao** [comment]
@sonimishra - the repro steps are too application-specific and we are not be able to follow along. Here is a good example on what an actionable bug description looks like: https://github.com/OfficeDev/office-ui-fabric-react/issues/11425
