### ISSUE TITLE
How to set sort function for each column in DetailsList(Custom Item Rows)

### ISSUE THREAD

**Issue by lvybriage** [OfficeDev/office-ui-fabric-react#11697]
### Environment Information

[demo](https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/customitemrows)

### Describe the issue:

I want to use `sort` function in `customitemrows` example , but don't know how to write code.

#### Expected behavior:

when click a column, this column's data will be sorted.

**Comment by xugao** [comment]
@lvybriage - you need to build and pass `columns` prop which contains sorting related fields. see code example "DetailsList with 500 documents, sorting, filtering, marquee selection, justified columns" in [here](https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist).
In there, it shows how it made `Name` column to be sortable:
```
      {
        key: 'column2',
        name: 'Name',
        fieldName: 'name',
        minWidth: 210,
        maxWidth: 350,
        isRowHeader: true,
        isResizable: true,
        isSorted: true,
        isSortedDescending: false,
        sortAscendingAriaLabel: 'Sorted A to Z',
        sortDescendingAriaLabel: 'Sorted Z to A',
        onColumnClick: this._onColumnClick,
        data: 'string',
        isPadded: true
      },
```

**Comment by lvybriage** [comment]
It works for me. Thank you @xugao :)
