### ISSUE TITLE
TextField support for maximum length

### ISSUE THREAD

**Issue by katiearriagam** [OfficeDev/office-ui-fabric-react#11691]
#### Describe the feature that you would like added

Currently, users of the TextField component need to restrict the input length manually on their events (see Additional context/screenshots section). The TextField component should expose a prop to support this restriction so users can leverage this and not have to add their own support.

Additionally, this should work with clipboard. For example, if the maxLength is 3 characters, and the user copies "Lorem", the TextField input should still have its value set to "Lor".

#### What component or utility would this be added to

TextField

#### Have you discussed this feature with our team, and if so, who

Yes, discussed this with @chang47. 

#### Additional context/screenshots

See the example in this CodePen: https://codepen.io/katiearriagam/pen/oNgydjy?editable=true - the TextField labeled "Controlled TextField limiting length of value to 5" has the length restriction functionality on its `onChange` even. Additionally, it doesn't work with clipboard if the text exceeds the maximum length, so other users might accidentally introduce this bug when they use the TextField component.

**Comment by xugao** [comment]
@katiearriagam - `maxLength` prop is available today since it's a `InputHTMLAttribute`: https://codepen.io/xugao/pen/abzKjoO

I think "Controlled TextField limiting length of value to 5" example we have is quite confusing, and I believe it's meant to demo using `onChange` prop. We should update the example to be better

**Comment by xugao** [comment]
@katiearriagam - per discussions, i don't think this is an issue. pls confirm
