### ISSUE TITLE
[Content on Hover or Focus- Card-Large Card-Donut]:Tooltips are not disappear by pressing Esc key.

### ISSUE THREAD

**Issue by shivasai09** [OfficeDev/office-ui-fabric-react#11699]
Repro Steps:

Step1: Mouse hover on “Donut Chart and pie chart graph” .
step2: Observe that tooltip is disappear or not after pressing Escape key,

Actual Result:
Tooltips are not disappearing after pressing Esc key.

Expected Result:
Tooltips must be disappear after pressing Esc key.

**Comment by xugao** [comment]
@shivasai09 - please provide repro details, more info above. i cannot repro the bug in our examples: https://developer.microsoft.com/en-us/fabric#/controls/web/tooltip

**Comment by brandonthomas** [comment]
@xugao you're looking at the wrong thing. This is about @uifabric/charting not office-ui-fabric-react. Can you please add the correct package tag? @shivasai09 should this be assigned to you or @Raghurk ?

**Comment by brandonthomas** [comment]
@Raghurk do you have permissions to add the `charting` tag to this so it doesn't get marked as stale and closed on accident?

**Comment by xugao** [comment]
@brandonthomas - i have adjusted the tags. will give another look

**Comment by xugao** [comment]
I agree here that the tooltip should be dismissed on ESC.

**Comment by Raghurk** [comment]
I have this sent to the right person. Will update this thread once it is fixed

**Comment by brandonthomas** [comment]
Thanks guys!

**Comment by shivasai09** [comment]
@Raghurk , i have raised the pull request(#11761 ) to solve this issue. could you please review.

FYI: @brandonthomas
