### ISSUE TITLE
Place holder is not displaying after clearing the Combo Box control selected value/key

### ISSUE THREAD

**Issue by sachin6107** [OfficeDev/office-ui-fabric-react#11701]
We have created the combo box using the below code

<ComboBox
       placeholder="Select Cedant Domicile"
       allowFreeform
       autoComplete="on"
       options={this.props.countryOptions}
       selectedKey={this.state.inputDecisioSecInfo._cedantDomicileSelectedValue}
      disabled={this.state.inputDecisioSecInfo._isCedantDomicile}
      onChange={(event,item:any)=>{this._OnCedantDomiceChange(item);}}
/>

When we are clearing the selected key then It's value has been clearing but the place holder is not displaying. 

**Clear Code:**

this.setState({
	  inputDecisioSecInfo:{
		...this.state.inputDecisioSecInfo,
		**_cedantDomicileSelectedValue:null**
});

![image](https://user-images.githubusercontent.com/16962399/72345227-2c86a680-36f9-11ea-8dbf-effa67d9acf2.png)

**Expected Behaviour:**
It should be clear/reset without clearing the place holder.

**Help Requested :**

Please suggest how to clear it.

**Comment by xugao** [comment]
@sachin6107 - i can't seem to repro. see [this codepen](https://codepen.io/xugao/pen/rNarjOX). if you still think we have a bug here, please provide a similar codepen which is able to repro

**Comment by sachin6107** [comment]
Thanks for replied. 
I have gone through the [codepen](https://codepen.io/sachin6107/pen/povZVaE) and tried to reproduce it by adding the button to clear the selected value.

 <PrimaryButton text="Clear" onClick={this._clearComboBox} />

private _clearComboBox = () =>
  {
    this.setState({
      selectedOptionKey: null,
    });
  }

On button click, the value is getting cleared and the place holder is also displaying. But it is not working on my development environment.

I am using "office-ui-fabric-react": "^7.48.0" version.

Is this version issue that currently I am using?

**Comment by xugao** [comment]
@sachin6107 - seems to be a bug in 7.48.0, i can repro: https://codesandbox.io/s/exciting-johnson-l5gyj
Pls upgrade to use the latest version to fix your issue

**Comment by sachin6107** [comment]
I have upgraded and it has fixed. Thanks 👍
