### ISSUE TITLE
Date field validation on mandatory filing is not triggered

### ISSUE THREAD

**Issue by marsbronson** [OfficeDev/office-ui-fabric-react#11700]
### Environment Information

- **Package version(s)**: 7.80.0
- **Browser and OS versions**: Chrome 79, Windows 10 v.1909

Reproduction of the bug in a codepen:
https://codepen.io/yaroslav-ignatenko/pen/jOEKgYM?editable=true

#### Bug 1:
Click inside the field, click outside.
Validation error is appeared.
Click on Calendar Icon, choose the date.

#### Actual behavior:
Validation error still exist.

#### Expected behavior:
Validation error must disappear when we choose date from Calendar.

#### Bug 2:
Choose DatePicker that allow text input.
Write invalidate date value.
Click on Calendar Icon, choose the date.

#### Actual behavior:
Validation error still exist.

#### Expected behavior:
Validation error must disappear when we choose date from Calendar.

**Comment by xugao** [comment]
@marsbronson - I can repro the issue. will work on a fix
