### ISSUE TITLE
Hyperlinks within custom tooltip content are not accessible

### ISSUE THREAD

**Issue by nkalpana** [OfficeDev/office-ui-fabric-react#11711]
### Environment Information

- **Package version(s)**: Latest version of Fabric used by "Export to codepen" from sampls
- **Browser and OS versions**: Chrome and Windows 10

### Describe the issue:
When TooltipHost's content prop is set to a JSX.Element which has focusable content, like a Hyperlink, despite setting the ariaLabel for the focusable content, user is not able to tab into it.
Only in the rare case of the cursor moves over the tooltip host's child content and is also on the automatically displayed tooltip content, can I tab into the hyperlink and hit enter to see it.
Also the ariaLabel of the hyperlink is not announced by Narrator/NVDA

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/nkalpana/pen/rNaKqpP

#### Actual behavior:
Tooltip content appears when user clicks on the tooltip host's child contorl or moves mouse over it. But, in that state if the user tabs or hits right arrow, the focus does not get to the hyperlink in the tooltip hosts' content

#### Expected behavior:
Tooltip content appears when user clicks on the tooltip host's child contorl or moves mouse over it. User hits tab key or left arrow key, and the focus moves over to the hyperlink.

**Comment by xugao** [comment]
@nkalpana - this is by design. tooltip widget should not be focusable, see [ARIA guidance here](https://www.w3.org/TR/wai-aria-practices-1.1/#tooltip)

**Comment by sonimishra** [comment]
@xugao Here in the doc it is mentioned that focus should not go to the tooltip widget outline but if the widget contains any interactive controls then focus should navigate to that particular control like in this case "click here" link which is interactive.

**Comment by khmakoto** [comment]
@sonimishra where in the ARIA doc does it say that? I explicitly states:

>Tooltip widgets do not receive focus. A hover that contains focusable elements can be made using a non-modal dialog.
