### ISSUE TITLE
Text is being clipped in certain Persona scenarios

### ISSUE THREAD

**Issue by helizabethwhite** [OfficeDev/office-ui-fabric-react#11719]
### Environment Information

- **Package version(s)**: at least 7.76.0+
- **Browser and OS versions**: n/a

#### Actual behavior:

![image](https://user-images.githubusercontent.com/11093219/72462590-3e625b00-3786-11ea-9e6b-2ed292a4ba46.png)

#### Expected behavior:

![image](https://user-images.githubusercontent.com/11093219/72462707-87b2aa80-3786-11ea-9d45-30d3d04f7d57.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: OWA (all browsers)

**Comment by xugao** [comment]
@helizabethwhite - per comments in the PR. are you good with closing this issue ? If so, pls do :)
