### ISSUE TITLE
About multiple column header in DetailsList

### ISSUE THREAD

**Issue by jinyu1122** [OfficeDev/office-ui-fabric-react#11712]
#### Describe the feature that you would like added
Multiple column headers in detailslist: 
Just like the following image. We can specify consecutive columns to groups, then we are actually having more than one level columns. Each level support drag&drop operation. And sort operation is only supported in lowest level. 
![image](https://user-images.githubusercontent.com/1931573/72406573-c13fe180-3797-11ea-8d12-e72371e2a8d7.png)

#### What component or utility would this be added to
DetailsList

#### Have you discussed this feature with our team, and if so, who
My team is migrating to Fabric. And our old grid support multiple column feature, so this is must-have for our team.

**Comment by xugao** [comment]
@jinyu1122  - you should be able to use `onRenderDetailsHeader` prop in `DetailList` to accomplish this. 
you can read more about the prop [here](https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist)

**Comment by jinyu1122** [comment]
Yes, we are doing this now. 
Also I wish to publish some PRs to extend DetailsList to make it naturely support multi-column header.
