### ISSUE TITLE
Documentation: TextField type prop

### ISSUE THREAD

**Issue by soryy708** [OfficeDev/office-ui-fabric-react#11729]
Following the change(s) that fix https://github.com/OfficeDev/office-ui-fabric-react/issues/490
It appears that the documentation at https://developer.microsoft.com/en-us/fabric#/controls/web/textfield does not mention the `type` prop of the `TextField` component.
I think the documentation should be updated.

**Comment by xugao** [comment]
@soryy708 - `type` is part of `React.AllHTMLAttributes<HTMLInputElement | HTMLTextAreaElement>`
In our doc you can see that it mentions:
```
ITextFieldProps interface
Extends  React.AllHTMLAttributes<HTMLInputElement | HTMLTextAreaElement>
```

Therefore we don't list such prop specifically.
If this solves your concern, please help close this issue
