### ISSUE TITLE
Going to 1.14.1 from 1.14.0 breaks <TextField>

### ISSUE THREAD

**Issue by carruthe** [OfficeDev/office-ui-fabric-react#1173]
### Bug Report

- __Package version(s)__: 1.14.1
- __Browser and OS versions__: Mac OS Sierra, Safari

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) Not comfortable with PR yet

Requested priority: (Blocking, High, Normal, Low) Blocking

#### Describe the issue:

I use a TextField component, with the OnChanged event, which I only want to be fired when the control loses focus (not after every character entered).

```
                        <TextField
                            value={newAliasVal}
                            placeholder='(add new alias here)'
                            ref={(input) => { this._newAliasInput = input }}
                            validateOnFocusOut={true}
                            onChanged={(text) => aliasPage._onNewAliasEntered(text)}
                            onGetErrorMessage={(value) => this._onGetErrorMessage(value)}
                        />
```

in 1.14.0 and before, it respected the `validateonFocusOut` prop and the `onChanged` event was only fired when the user left the field.  With 1.14.1, `onChanged` is fired after every keystroke, regardless of the `validateonFocusOut` prop.

**Comment by carruthe** [comment]
Rolling back to 1.14.0 fixes the problem.

**Comment by carruthe** [comment]
Here's a codePen report (My first codepen!  Go me!)

[http://codepen.io/tcarruthers/pen/zZBGvP](http://codepen.io/tcarruthers/pen/zZBGvP
)

It is initially referenced to `//unpkg.com/office-ui-fabric-react@1.14.0/dist/office-ui-fabric-react.min.js`, and works.

If you switch to`//unpkg.com/office-ui-fabric-react@1.14.1/dist/office-ui-fabric-react.min.js`
It breaks.

Thanks!

**Comment by dzearing** [comment]
@carruthe thanks! Will poke around and see what changed.

**Comment by dzearing** [comment]
@mdahamiwal Can you take a look and see if your recent changes caused this?

**Comment by micahgodbolt** [comment]
Diving into this a bit and it seems that the current implementation is correct. onChange fires on each keypress, and validateOnFocusOut only affects if validation is ran per keystroke. 

Would it be beneficial to have an onBlur function, or else we could have onChangeFocusOut/onChangeFocusIn set of props. I'm leaning towards on onBlur function, if that is what you are looking to do here.

**Comment by carruthe** [comment]
@micahgodbolt - Yes, an onBlur function would do the trick.  Thanks!

**Comment by micahgodbolt** [comment]
@carruthe I'd be adding this to the 2.X.X branch. Are you moving to this soon, or do you need the functionality backported?

**Comment by carruthe** [comment]
@micahgodbolt - that branch is fine, thanks.

On a related note, I 'manually' capture when the user hits the enter key so I know they are done...

```
 <TextField
...
 onKeyPress={(keyPressed) => this._onKeyPress(keyPressed)}
......
 />

    _onKeyPress(keyPressed) {
        if (keyPressed.key === "Enter") {
              // Process the input
        }
    }
```

Having something more formal would be nice, like a `loseFocusOnEnterKeyPress` or something like that, along with the `onBlur` function.

Thanks!

**Comment by micahgodbolt** [comment]
@carruthe even though you don't see them as props, we already support onBlur and onFocus events (they are HTML native so no need to add them to props). 

It looks like it returns the entire Event, but should be accessible to you without any change to code.
