### ISSUE TITLE
Narrator announces wrong information about selected value.

### ISSUE THREAD

**Issue by fsteffi** [OfficeDev/office-ui-fabric-react#11732]
Environment Details:​​
Application name: D365 Forecast Configuration
Browser Versions: Microsoft Edge 44.18362.387.0,
Chrome Version 77.0.3865.120 (Official Build) (64-bit)
Windows Version: Windows10​​​
NVDA 2019.2.1

Repro Steps:​​
1. Launch the application URL 
2. Select application as "Sales hub" from the list of application.
3. From the change area which is present in the bottom select "App Settings"
4. Navigate to "Site Map" and then Navigate to "Goal Management" and select "Forecast Configuration"
5. Fast Track Your Forecast Screen will appears.
6. Click on "Org chart forecast"
7. Forecast Configuration screen will appears
8. Start narrator and check how does narrator reads information when we select value from the top of hierarchy combo box

Actual:​
When we are selecting any value from the list (Top of hierarchy combo box) narrator announces wrong information "False object.." which is not correct.

Same issue is observed with NVDA.

Expected:​​
When we are selecting value from the list narrator should announce information about the selected value.

User Impact:​
Screen reader user will not be able to know proper information about the control.

![NewIssue1](https://user-images.githubusercontent.com/24580570/72524648-56ba9e80-3888-11ea-8027-cef9046474bf.png)

**Comment by sonali0927** [comment]
@xugao can you please provide update on this??
