### ISSUE TITLE
Narrator does not give info about the loading result as well as auto suggestions field

### ISSUE THREAD

**Issue by fsteffi** [OfficeDev/office-ui-fabric-react#11733]
Environment Details:​​
Browser Versions: Microsoft Edge 44.18362.387.0,
Chrome Version 77.0.3865.120 (Official Build) (64-bit)
Windows Version: Windows10​​

Screen reader: narrator, nvda2019.2
Windows Version: Windows10​​​

Repro Steps:​​
1. Launch application
2. Select any forecast from dropdown.​
3. Navigate till pipeline cell in forecast & select it.​
4. In launcher, navigate till Show as Kanban & hit enter.​
5. Select a card under any category from Kanban board.​
6 . Start screen reader as narrator.

Actual:​
Narrator does not give info about the loading result as well as auto suggestions field.

Expected:​
Narrator should give information about the Loading results and auto suggestions options.

Same issue is observed with nvda.

User Impact:​
Screen reader users will not be able to know information about the list item.

![NewIssue11](https://user-images.githubusercontent.com/24580570/72526734-190c4480-388d-11ea-9208-33b28c957fb5.png)

**Comment by sonali0927** [comment]
@xugao can you please check this bug??
