### ISSUE TITLE
Shimmer: High contrast issue

### ISSUE THREAD

**Issue by lrabinowicz** [OfficeDev/office-ui-fabric-react#11735]
### Environment Information

- **Package version(s)**: office-ui-fabric-react@7.78.0
- **Browser and OS versions**: Microsoft Chromium Edge, Windows 10

### Describe the issue:
When high contrast mode is on, shimmer is not working properly. 

#### Actual behavior:

Repro steps:
1- Turn on high contrast mode
2- Open Chromium Edge
3- Go to fabric UI and search for the shimmer (https://developer.microsoft.com/en-us/fabric#/controls/web/shimmer)
4- Go to any Shimmer example

![ShimmerBug](https://user-images.githubusercontent.com/12565958/72562422-47bff600-3860-11ea-86d0-40072c0a32e3.gif)

#### Expected behavior:

Same as in Microsoft Edge (no Chromium):
![ShimmerNoBug](https://user-images.githubusercontent.com/12565958/72562894-51962900-3861-11ea-8f96-042e5600e123.gif)

**Comment by xugao** [comment]
@lrabinowicz  -  i can repro the issue. though I am not sure if this is our bug or browser's. I will double check

**Comment by xugao** [comment]
@lrabinowicz - HC css doesn't seem to work new Edge browser in general. check out this pen i have: https://codepen.io/xugao/pen/RwNeVVm

**Comment by lrabinowicz** [comment]
Okay then I'll close this issue since is a browser bug. Thank you very much :)

**Comment by xugao** [comment]
@lrabinowicz  - I talked to the Edge team and figured out the problem. I opened an issue #11742 to track this. Will keep your issue closed since this is a duplicate. But will try to fix this as soon as possible
