### ISSUE TITLE
Documentation for &:hover and :hover, where can I read more about it?

### ISSUE THREAD

**Issue by DMZ011** [OfficeDev/office-ui-fabric-react#11740]
I am reading the docs, specifically this page: https://github.com/OfficeDev/office-ui-fabric-react/wiki/Component-Styling .. My understanding from this, is that :hover refers to the current component (either parent or child), but the &:hover always references the parent element. Is this correct? If any explanation can be added and clarification it would be great as it's not clear what's the usage of this. 

Thank you.

**Comment by xugao** [comment]
@DMZ011 - there is actually no difference between having/not having `&` in from of pseudo selectors.
For example:
Both
```
     {
        selectors: {
          ':hover .childElement, :active': { background: 'red' }
        }
      }
```
and
```
     {
        selectors: {
          '&:hover .childElement, &:active': { background: 'red' }
        }
      }
``` 
will create css such as the following:
```
.css-0:hover .childElement{background:red;}.css-0:active{background:red;}

I do agree our documentation is unclear. I will work on making it better.
```

**Comment by xugao** [comment]
@DMZ011 - I have updated [this wiki](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Component-Styling) to remove the unneeded `&` and made the example usages of pseudo selectors consistent. let me know if this resolves your question.

**Comment by xugao** [comment]
@DMZ011 - i will go ahead close this since it's resolved from my standpoint. if any further issue, feel free to reopen :)
