### ISSUE TITLE
Image: Should `componentWillReceiveProps()` check for loaded state?

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#1174]
### Bug Report

- __Package version(s)__: Current
- __Browser and OS versions__: All

#### Describe the issue:

Here is the current `componentWillReceiveProps()` for Image:

```
  public componentWillReceiveProps(nextProps: IImageProps) {
    if (this.state.loadState === ImageLoadState.loaded) {
      let { height: nextHeight, width: nextWidth } = nextProps;
      let { height, width } = this.props;

      if (height !== nextHeight || width !== nextWidth) {
        this._computeCoverStyle(nextProps);
      }
    }
  }
```

When trying to pass new `width` and `height` props to the component before the image is loaded, those props are ignored. Is it safe to remove this check for `loadState` before computing a new cover style?

**Comment by battletoilet** [comment]
@mikewheaton, the code has changed since asking this question so i will close this for now. Pleas reopen if the question is still valid.
