### ISSUE TITLE
Add pagination component for DetailsList

### ISSUE THREAD

**Issue by lvybriage** [OfficeDev/office-ui-fabric-react#11741]
#### Describe the feature that you would like added

Add pagination to DetailsList. It's common for list component.

#### What component or utility would this be added to

`DetailsList`

#### Have you discussed this feature with our team, and if so, who

no

**Comment by xugao** [comment]
@lvybriage - we had similar request #11123. We currently don't have any plan to spec/implement this.
See Jason's suggestion in #11123 and hopefully that works for you
