### ISSUE TITLE
Datepicker validates when textfield changes, not when it loses focus

### ISSUE THREAD

**Issue by chce** [OfficeDev/office-ui-fabric-react#11744]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/chce/pen/gObQWXJ?editable=true
Your export to codepen function seems to be broken, but I've basically just added "allowTextInput: true" to the "DatePicker with required field" example here from here:  https://developer.microsoft.com/en-us/fabric#/controls/web/datepicker

#### Actual behavior:

As soon as I begin entering a date, the field runs a required-validation, and shows an error.

#### Expected behavior:

"Validation will happen when Date Picker loses focus." - Stated on the example

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) Datepickers

### Caused by
Probably caused by the following function:
```
  private _onTextFieldChanged = (ev: React.FormEvent<HTMLInputElement | HTMLTextAreaElement>, newValue: string): void => {
    const { allowTextInput, textField } = this.props;

    if (allowTextInput) {
      if (this.state.isDatePickerShown) {
        this._dismissDatePickerPopup();
      }

      const { isRequired, value, strings } = this.props;

      this.setState({
        errorMessage: isRequired && !value ? strings!.isRequiredErrorMessage || ' ' : undefined,
        formattedDate: newValue
      });
    }

    if (textField && textField.onChange) {
      textField.onChange(ev, newValue);
    }
  };

```

**Comment by khmakoto** [comment]
Hi @chce, I can confirm that I can reproduce the behavior you are saying. I too believe that this is caused because of the code you highlighted above. I see that you said you're willing to submit a PR to fix this issue, it would be awesome if you did! If you can't I'll try to have a solution as soon as possible. Thanks!

**Comment by chce** [comment]
Hi @khmakoto, I'll create a PR. It looks like the issue is that it looks at props.value instead of newValue when validating in onTextFieldChanged. I'm thinking switching out !value with !newValue in the setState call will ensure, that it only warns you when:
_The text field blurs_ or _The user deletes the whole input, but doesn't blur_
If you approve, I'll create the PR

**Comment by khmakoto** [comment]
Hi @chce, thanks for creating the PR! I will review it as soon as possible!
