### ISSUE TITLE
Choice Group theme property is not working

### ISSUE THREAD

**Issue by chandu521Tech** [OfficeDev/office-ui-fabric-react#11749]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by khmakoto** [comment]
@chandu521Tech please fill out the issue template so that we can take action on this issue. Thanks!
