### ISSUE TITLE
DatePicker formatDate property doesn't work

### ISSUE THREAD

**Issue by pstakashi** [OfficeDev/office-ui-fabric-react#11757]
Datepicker formatDate property cannnot format date in the official [doc](https://developer.microsoft.com/en-us/fabric#/controls/web/datepicker) 'DatePicker allows dates to be formatted'.
Browser: Chrome 79.0.3945.130 64bit

**Comment by khmakoto** [comment]
Hi @pstakashi, this is a duplicate of #11750 that is already being tracked, so I'll be closing down this issue in favor of that one. Thanks!
