### ISSUE TITLE
DatePicker format date bug

### ISSUE THREAD

**Issue by marsbronson** [OfficeDev/office-ui-fabric-react#11750]
### Environment Information

- **Package version(s)**: 7.83.0
- **Browser and OS versions**: Chrome 79, Windows 10 v.1909

Cannot reproduce the bug in a codepen, but it can be reproduced in your Fabric UI site.
https://developer.microsoft.com/en-us/fabric#/controls/web/datepicker

#### Bug:
Scroll to 'DatePicker allows input date string' or 'DatePicker allows dates to be formatted'.
Click on Calendar Icon, choose the date.

#### Actual behavior:
The input value is empty.

#### Expected behavior:
The date is set when we choose it from Calendar.

**Comment by khmakoto** [comment]
Hi @marsbronson, thanks for filing this issue! I've been able to correctly repro the bug you're experiencing, I'll look into it to have a solution as soon as possible.

**Comment by onlyann** [comment]
@khmakoto The issue has been introduced by https://github.com/OfficeDev/office-ui-fabric-react/commit/5ca26b1bd53a3325bc385c53ee36041c718a8b0f#diff-8c4f1f7b505a2b21992c7e7af22c6837R442

The change causes `_validateTextInput` to not process the selected date anymore.
