### ISSUE TITLE
Drop-down accessibility issue

### ISSUE THREAD

**Issue by v-yikuli** [OfficeDev/office-ui-fabric-react#11752]
### Describe the issue:

Using tab navigation, dropdown will be filled in with the 1st item of list

#### Actual behavior:

Using tab navigation, when a dropdown is on focus, it will be automatically filled out with the 1st item from the expanded list

#### Expected behavior:

When drop-down is on focus, it should not change the current selection status.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by micahgodbolt** [comment]
this is by design #5473
