### ISSUE TITLE
[Accessibility-Keyboard-Navigation] Dropdown, key down causes scrolling of whole page

### ISSUE THREAD

**Issue by woofton** [OfficeDev/office-ui-fabric-react#11768]
### Environment Information

- **Package version(s)**: Latest version
- **Browser and OS versions**: Chrome, Edge, Firefox. Windows 10.

### Describe the issue:

Pressing the down key when the dropdown is not open, causes the whole page to scroll.

#### Actual behavior:

When I go to the examples for Dropdowns, tab to any dropdown that is not multi-select (for example the dropdown under "Controlled example"), press the down key till I get to the last item in the dropdown list and then click the down key one more time, the whole screen starts to scroll.  Now, if I do the reverse and I use the up key, the dropdown cycles through all the options.  Note that I have not opened the dropdown by clicking enter or using the mouse.

#### Expected behavior:

I expect the down key to cycle through all the options just like when I press the up key.

### If applicable, please provide a codepen repro:

https://fabricweb.z5.web.core.windows.net/oufr/7.84.0/#/examples/dropdown

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) I've looked through the code and I'm not sure where to begin to solve this issue, so no.

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

**Comment by khmakoto** [comment]
Hi @woofton, thanks for filing this issue! I can confirm that I was able to repro it, I'll work on a fix as soon as possible! Thanks again.

**Comment by woofton** [comment]
@khmakoto I think I found the solution.  Created a PR for the solution.
