### ISSUE TITLE
SpinButton is still focusable after being disabled

### ISSUE THREAD

**Issue by calderov** [OfficeDev/office-ui-fabric-react#11766]
### Environment Information

- **Package version(s)**: 6.210.5
- **Browser and OS versions**: All browsers, all OSs

### Please provide a reproduction of the bug in a codepen:
Repro steps.
1. Open https://codepen.io/ArturoCalderon/pen/ExarybR
2. Switch to the bottom section and press TAB

#### Actual behavior:
Disabled SpinButton component is still focusable by keyboard.

#### Expected behavior:
Disabled SpinButton component should no longer be focusable by keyboard, as stated in here: https://github.com/OfficeDev/office-ui-fabric-react/issues/4387

### Priorities and help requested:
Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: [Microsoft Project for the Web](project.microsoft.com/)

**Comment by khmakoto** [comment]
Hi @calderov, thanks for filing this issue! I can confirm that I can repro this behavior, I'll work on a fix as soon as possible!

**Comment by calderov** [comment]
Awesome! Thanks @khmakoto
