### ISSUE TITLE
[Screen Reader - Azure Iot explorer - Device Identity]Incorrect role property is defined for all controls under 'Device' on device identity.

### ISSUE THREAD

**Issue by kattepalli** [OfficeDev/office-ui-fabric-react#11777]
**Environment Information**
Package version(s): 7.84.0
Browser and OS versions: Desktop application(Azure IoT Explorer) win 10 1903(OS Build 19013.1122)

**Describe the issue:**
Incorrect role property like 'Hyperlink' is defined for all left pane controls under 'Device' on device identity.

**Steps:**
1. Launch 'Azure IoT explorer' app from start menu.
2. 'App Configurations' pop up appears, navigate all controls of it.
3. Enter valid connection string and select connect button.
4. 'Azure IoT explorer'  home page launched, navigate to the table and Select any Device added from Home page.
5. 'Device Identity' appears as default selected, Navigate all the controls appears.
6. Verify the issue. 

**Please provide a reproduction of the issue in a codepen:**
https://codepen.io/kattepalli/pen/rNaPKjV?editable=true

**Actual behavior:**
Incorrect role property is defined for all controls under 'Device' on device identity.
Role 'Link' is defined for all controls under device.

**Expected behavior:**
Correct role property like 'Tab item' should be define for all controls under 'Device' on device identity.

**Comment by khmakoto** [comment]
Hi @kattepalli, please provide a minified reproduction of your bug in a codepen since we can't go and check for bugs in applications as it is often hard to determine if it's Fabric's fault or the app's fault.
