### ISSUE TITLE
[Keyboard Navigation - Azure Iot explorer  - Digital Twins] Two time focus remain on same control under "Digital Twins".

### ISSUE THREAD

**Issue by kattepalli** [OfficeDev/office-ui-fabric-react#11776]
**Environment Information**
Package version(s): 7.84.0
Browser and OS versions: Desktop application(Azure IoT Explorer) win 10 1903(OS Build 19013.1122)

**Describe the issue:**
While navigating through keyboard, the keyboard focus is moving to first arrow button and after pressing down arrow key focus is moving to complete control(with arrow button also), but after pressing enter key on both arrow control and complete control the result are both same(Both controls are expanding/collapsing).
 
**Steps:**
1. Launch 'Azure IoT explorer' app from start menu.
2. 'App Configurations' pop up appears, navigate all controls of it.
3. Enter valid connection string and select connect button.
4. 'Azure IoT explorer'  home page launched, navigate to the table and Select any Device added from Home page.
5. Navigate to the 'Telemetry' and select it.
6. Navigate all the controls of 'Telemetry ' page and select 'Digital Twins' section shown on the left and expand it.
7. Verify the issue. 

**Please provide a reproduction of the issue in a codepen:**
https://codepen.io/kattepalli/pen/dyPaKGv?editable=true

**Actual behavior:**
While navigate on Digital Twins below controls focus remain two time on same controls.

**Expected behavior:**
While navigate on Digital Twins below controls focus should not remain two time on same controls, after tab is should move on next control.

**Comment by khmakoto** [comment]
Hi @kattepalli, please provide a minified reproduction of your bug in a codepen since we can't go and check for bugs in applications as it is often hard to determine if it's Fabric's fault or the app's fault.
