### ISSUE TITLE
autoAdjustHeight not working

### ISSUE THREAD

**Issue by joechung-msft** [OfficeDev/office-ui-fabric-react#1177]
### Bug Report

- __Package version(s)__: 1.14.1
- __Browser and OS versions__: All

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) Yes, pending CLA

Requested priority: (Blocking, High, Normal, Low) Normal

#### Describe the issue:

autoAdjustHeight property is not working in multiline TextField because of line 289 in /src/components/TextField/TextField.tsx, which refers to but does not actually call the function to adjust the height on text content change.

#### Actual behavior:

The TextField does not adjust its height based on its text content when autoAdjustHeight is enabled.

#### Expected behavior:

The TextField should adjust its height based on its text content when autoAdjustHeight is enabled.

### If applicable, please provide a codepen repro:

[http://codepen.io/anon/pen/PpzrvJ](http://codepen.io/anon/pen/PpzrvJ)

**Comment by dzearing** [comment]
Thanks @joechung-msft !
