### ISSUE TITLE
Teaching bubble body text is overlapping with close button when there is no headline.

### ISSUE THREAD

**Issue by zisu4** [OfficeDev/office-ui-fabric-react#11779]
### Environment Information

- **Package version(s)**: 6.210.6

### Please provide a reproduction of the bug in a codepen: 
https://codepen.io/alexsunms/pen/JjoxVPx?editable=true

#### Actual behavior:

1. Teaching bubble body text is overlapping with close button when there is no headline.
2. Body text is not centered there is no headline.

#### Expected behavior:

1. Teaching bubble body text should not overlapping with close button when there is no headline.
2. Body text is should be centered there is no headline.

**Comment by khmakoto** [comment]
Hi @zisu4, thanks for filing this issue! I've been able to repro the behavior you've explained above and I'll be looking into making a fix as soon as I can.
