### ISSUE TITLE
TeachingBubble: "calloutWidth" in "calloutProps" is not working

### ISSUE THREAD

**Issue by zisu4** [OfficeDev/office-ui-fabric-react#11780]
### Environment Information

- **Package version(s)**: 6.210.6

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/alexsunms/pen/xxbMeOB?editable=true

#### Actual behavior:

Passing `calloutWidth` in `calloutProps` is not working, but "beakWidth" is.

#### Expected behavior:

Passing `calloutWidth` in `calloutProps` should change the width of TeachingBubble.

**Comment by khmakoto** [comment]
Hi @zisu4, thanks for filing this issue! I've been able to repro the behavior you've explained above and I'll be looking into making a fix as soon as I can.
