### ISSUE TITLE
Panel onOpen prop does not work

### ISSUE THREAD

**Issue by kevinjkim** [OfficeDev/office-ui-fabric-react#11782]
### Environment Information

- **Package version(s)**: 7.84.0
- **Browser and OS versions**: (fill this out if relevant)

### Describe the issue:
The onOpen callback never gets called for Panels.

#### Actual behavior:
Other callbacks, like onDismiss and onOpened, do get called but not onOpen

#### Expected behavior:
onOpen prop gets called

### If applicable, please provide a codepen repro:
https://codepen.io/kevinjkim/pen/ExarzXK

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No
Requested priority: Normal/Low

Products/sites affected: (if applicable)

**Comment by khmakoto** [comment]
Hi @kevinjkim, thanks for filing this issue! I've been able to reproduce it and will work on a fix for it as soon as possible.
