### ISSUE TITLE
CSS Modules: Dropdown multi-line item style incorrect 

### ISSUE THREAD

**Issue by YusongLiu** [OfficeDev/office-ui-fabric-react#1179]
### Bug Report

- __Package version(s)__: beta

#### Describe the issue:

When we have got a multi-line dropdown item, the style for the item is incorrect.

#### Actual behavior:

![dropdown-actual](https://cloud.githubusercontent.com/assets/15144072/23597141/6393dd20-026b-11e7-96ce-4b470a21bd10.png)

#### Expected behavior:

![dropdown-expected](https://cloud.githubusercontent.com/assets/15144072/23597145/6c21bf48-026b-11e7-827e-d21f6555f026.png)

**Comment by dzearing** [comment]
Fixed

**Comment by dzearing** [comment]
fixed in beta8.

**Comment by YusongLiu** [comment]
Thanks!
