### ISSUE TITLE
isTrusted check to the dismiss on scroll handler

### ISSUE THREAD

**Issue by sabans-dev** [OfficeDev/office-ui-fabric-react#11800]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

Requirement is to add isTrusted check to the dismiss on scroll handler in calloutContent.base
The need to be able to stop the drop down menus getting closed when in a coauthoring environment a scroll event is received due to adjustment of the canvas in word online

Proposed change is to add a check to the if statement to not dismiss is ev.isTrusted == false on the file below at line# 264
https://github.com/OfficeDev/office-ui-fabric-react/blob/a5bbc76367eb01e993f20796955569f422a538b2/packages/office-ui-fabric-react/src/components/Callout/CalloutContent.base.tsx

#### Expected behavior:

The scroll handler should be able to define if the closing of the dropdowns is required or not. Also this should be handled for scroll per say and rather on change of focus

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) YES

Requested priority: (Blocking, High, Normal, Low) Blocking (Hi-Pri customer issue)

Products/sites affected: (if applicable)
Word Online

**Comment by khmakoto** [comment]
Hi @sabans-dev, thanks for filing this issue! If you are willing to and can make a PR please feel free to do so, it would be awesome! If not I'll take a look into this later this week. Thanks!

**Comment by sabans-dev** [comment]
Thanks a ton @khmakoto 
I created the pull request for the same. Please have a look and take appropriate action.
