### ISSUE TITLE
Text component does not inherit parent style definitions when no variant is supplied

### ISSUE THREAD

**Issue by singhshashi** [OfficeDev/office-ui-fabric-react#11801]
### Environment Information

- **Package version(s)**: 6.176.0
- **Browser and OS versions**: Firefox 72.0.2, MacOS Mojave 10.14.6
### Please provide a reproduction of the bug in a codepen:

https://codepen.io/singhshashi/pen/xxbBmzN?editable=true

#### Actual behavior:
Text component wrapped around by a div is not inheriting font weight bold from the div. 

#### Expected behavior:

Text component wrapped around a by a div and with no variant prop should inherit text styles from the parent as documented at https://developer.microsoft.com/en-us/fabric#/controls/web/text#overview

**Comment by khmakoto** [comment]
Hi @singhshashi, thanks for filing this issue! I can confirm the it is reproduceable on my end and I'll work to have a fix as soon as possible!

**Comment by khmakoto** [comment]
Hi @singhshashi, apparently this is expected and our documentation was outdated. I'll make another PR to update the docs.
