### ISSUE TITLE
PeoplePicker Form validation

### ISSUE THREAD

**Issue by yury-stepanov** [OfficeDev/office-ui-fabric-react#11803]
#### Describe the feature that you would like added

PeoplePicker Form validation

#### What component or utility would this be added to

PeoplePicker 

#### Have you discussed this feature with our team, and if so, who

It's already has been discussed on #3722
and I think it was unreasonably closed.

**Comment by khmakoto** [comment]
It was closed because there are already 2 issues tracking this #3620 and #7636. I'll close this in favor of those as well.
