### ISSUE TITLE
CSS Modules: Checkbox focus border style incorrect

### ISSUE THREAD

**Issue by YusongLiu** [OfficeDev/office-ui-fabric-react#1180]
### Bug Report

- __Package version(s)__: beta

#### Describe the issue:

To repro this bug please set a some margin-left to the Checkbox group in example page like:
![checkbox-to-repro](https://cloud.githubusercontent.com/assets/15144072/23598014/77856db0-0272-11e7-95d0-6e74c493805e.png)

#### Actual behavior:

![checkbox-actual](https://cloud.githubusercontent.com/assets/15144072/23598077/d0208f18-0272-11e7-9fe2-d8433e01f815.png)

#### Expected behavior:

![checkbox-expected](https://cloud.githubusercontent.com/assets/15144072/23598043/a69db832-0272-11e7-8ddb-0d777b71fbd1.png)

**Comment by dzearing** [comment]
Per discussion with design devs, by design. We don't expect the focus rect to exceed the control rendering area.

**Comment by YusongLiu** [comment]
I see. Thanks!
