### ISSUE TITLE
Error when OUFR is bundled in a library using tsdx - can't redefine non-configurable property "MAX_COLOR_SATURATION"

### ISSUE THREAD

**Issue by Wezea** [OfficeDev/office-ui-fabric-react#11802]
I've tried to build a library using [tsdx](https://github.com/jaredpalmer/tsdx) on top of `office-ui-fabric-react` to create reusable components made out of `OUFR` components.

Unfortunately, I get this error when running the sample project using the library:

`TypeError: can't redefine non-configurable property "MAX_COLOR_SATURATION" `

### Environment Information

- **Package version(s)**: 7.84.1

### Please provide a reproduction of the bug:

https://github.com/Wezea/fabriclib

```bash
npm i # or yarn

cd example
npm i # or yarn to install dependencies
npm start # or yarn start
```

#### Actual behavior:

```
TypeError: can't redefine non-configurable property "MAX_COLOR_SATURATION" index.ts:3
    ObjectOrReflectDefineProperty self-hosted:1801
    defineProperty self-hosted:1817
    parcelRequire<["../node_modules/office-ui-fabric-react/lib/utilities/color/index.js"]</< index.ts:3
    forEach self-hosted:235
    parcelRequire<["../node_modules/office-ui-fabric-react/lib/utilities/color/index.js"]< index.ts:3
    newRequire example.f69400ca.js:47
    localRequire example.f69400ca.js:53
    parcelRequire<["../node_modules/office-ui-fabric-react/lib/Color.js"]< Color.ts:1
    newRequire example.f69400ca.js:47
    localRequire example.f69400ca.js:53
    parcelRequire<["../node_modules/office-ui-fabric-react/lib/index.js"]< index.ts:13
    newRequire example.f69400ca.js:47
    localRequire example.f69400ca.js:53
    parcelRequire<["../dist/fabriclib.esm.js"]< example.f69400ca.js:118904
    newRequire example.f69400ca.js:47
    localRequire example.f69400ca.js:53
    parcelRequire<["index.tsx"]< index.tsx:4
    newRequire example.f69400ca.js:47
    parcelRequire example.f69400ca.js:81
    <anonym> example.f69400ca.js:120
```

#### Expected behavior:

The browser should render `FabricThing` component without error.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by Wezea** [comment]
Had a look at the OUFR code. I guess this is causing the problem, as `index.ts` is already exporting `./consts`.

https://github.com/OfficeDev/office-ui-fabric-react/blob/9e7b65719ad144fcbce97850140b0c703378d26e/packages/office-ui-fabric-react/src/utilities/color/colors.ts#L1

**Comment by khmakoto** [comment]
Hi @Wezea, it seems to me that this might be an issue related with `tsdx` more than Fabric. @kenotron what are your thoughts on this?

**Comment by khmakoto** [comment]
@Wezea we don't really have official support for tsdx, do you have a minimal repro of this happening in our officially supported configurations?
