### ISSUE TITLE
Dropdown: Support multiple selection

### ISSUE THREAD

**Issue by lszomoru** [OfficeDev/office-ui-fabric-react#1181]
Are there any plans to add support for multiple selection to the Dropdown component? Thanks! 

Ladislau

**Comment by nomadus** [comment]
If dropdown does not support multiple choice, how would someone create a tag component? I vote for this feature as well.

**Comment by fantua** [comment]
+

**Comment by lszomoru** [comment]
The other options could be to add an attribute to the tag component to display all the tags when the component gets focus. I will look at the code to tag component to see whether there is any way to do that.

**Comment by nomadus** [comment]
Any ETA for this feature?

**Comment by kristoferbrown** [comment]
Multi-select dropdowns exist now. The tagPicker can also be used in this scenario.

**Comment by russgove** [comment]
How do  I pre-select some items in a  Dropdown with Multi-select enabled.? defaultSelectedKey is defined as defaultSelectedKey?: string | number;. I need to pass in an array.

**Comment by kristoferbrown** [comment]
@russgove, in the current version of the `IDropdownProps` interface uses `string[] | number[]` for both 
`defaultSelectedKeys `and `selectedKeys`, so you can pass in an array. Take a look at the "Multi-Select uncontrolled example" on the doc site [here](https://developer.microsoft.com/en-us/fabric#/components/dropdown) if you want more guidance on this.

**Comment by russgove** [comment]
ah, time to upgrade again!
Thanks
