### ISSUE TITLE
'SearchBox' in 'farItems' take a 0 width on Edge

### ISSUE THREAD

**Issue by shadwamobdy** [OfficeDev/office-ui-fabric-react#11814]
### Environment Information

- **Package version(s)**: (7.1.4)
- **Browser and OS versions**: (Edge, Win10)

#### Actual behavior:

1. Try to search
2. When the search box is active the search icon will disappear and you will find the box like 1px width
![image](https://user-images.githubusercontent.com/38498675/73253958-2d720a80-41c6-11ea-881a-07953e88b029.png)

#### Expected behavior:
![image](https://user-images.githubusercontent.com/38498675/73254067-63af8a00-41c6-11ea-9213-80fc3494e1d4.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Blocking)

Products/sites affected: (Language Understanding Service "LUIS")

**Comment by khmakoto** [comment]
Hi @shadwamobdy, thanks for filing this issue! I can confirm that I can repro the bug and I'll work on a solution as soon as I can!

**Comment by khmakoto** [comment]
Hi @shadwamobdy, after tons of investigation I've arrived to the conclusion that this is probably a bug on Edge in how it handles flex elements. I'd suggest filing a bug with the Edge team. In the meantime, a workaround would be to provide a `width` or `minWidth` to the `SearchBox` like I've done [in this codepen](https://codepen.io/khmakoto/pen/xxbNxaX?editors=0010). I hope this information helps you!
