### ISSUE TITLE
CommandBar "Feature request"/Issue per khmakoto suggestion

### ISSUE THREAD

**Issue by mikezimm** [OfficeDev/office-ui-fabric-react#11840]
@khmakoto , just re-submitting my question per your suggestion here #11839 .

If you don't know the answer, just let me know and I can try posting again and hopefully it works.

I'm using the Fabric React UI Command Bar component.
I have "farItems" on the right as icon buttons.
On the far left, I'd like to have just a Label in the same row.

I have not been able to figure it out with a separate div.  So I was thinking of just having a single item in the "items" property that looks and feels like a label.

Using that approach, I have not been able to get it to look quite right (my current items array is defined below).

What I was thinking was to make it a white button (similar to the farItems), and NOT HAVE any onClick.  I also don't want it to change styles on hover.

I tried some variations of disabled, allowDisabledFocus & checked but all show the button style as grey'd out or disabled. 

I'm hoping I can do it with just the right combination of ICommandBarItemProps.

Thoughts?

```typescript
items = [
        {
          key: 'Topics',
          name: 'Topics',
          text: 'Button / Label text here',
          ariaLabel: 'Topics',
          disabled: false,
          allowDisabledFocus: true,
          checked: true, // Tells wether it is check or not by default.
          iconProps: {
            iconName: 'DoubleChevronLeftMedMirrored',

          },
          onClick: () => toggleLayout(),
        }
]
```

![CommandBarFormatQuestion](https://user-images.githubusercontent.com/49648086/73495709-10d00100-4385-11ea-811e-20861c6c02c0.png)

**Comment by khmakoto** [comment]
Hi @mikezimm, you can do this by adding a custom label as a `commandBarButtonAs` prop like I've done in [this codepen](https://codepen.io/khmakoto/pen/Powrpvq?editors=0010). Please let us know if there is anything else I can do to help!

**Comment by mikezimm** [comment]
@khmakoto , Thank you for putting together the codepen example, it really helped!

For some reason, I was not able to combine the **buttonAs** for custom styling default on all the other buttons AND get **commandBarButtonAs** to work on just one button... probably operator error on my part.

So what I ended up doing was using your example and adding **commandBarButtonAs** to each of my _farItems.  It added a few extra lines of code but it did work!

Thanks again!

```typescript
//Could not combine this
<CommandBar 
       buttonAs={customButton}
/>
//with custom button on one item
const _farItems: ICommandBarItemProps[] = [
{
     commandBarButtonAs: CustomButton
}];

```

**Comment by khmakoto** [comment]
No worries, glad it helped @mikezimm!!
