### ISSUE TITLE
Card API docs missing from website

### ISSUE THREAD

**Issue by ecraig12345** [OfficeDev/office-ui-fabric-react#11843]
Noticed while trying to show someone the Card docs that the API reference tables are missing. (I can potentially help with this, mainly logging issue as reminder.) 
https://developer.microsoft.com/en-us/fabric#/controls/web/card

**Comment by khmakoto** [comment]
I'll take a look, I wonder why they're missing.

**Comment by khmakoto** [comment]
Ok, I found the issue, I'll have a PR shortly.

**Comment by rmittal1421** [comment]
I have been playing around with cards and embedding them in my UI. Can I get an estimate onto how much time is going to take to get the documentation up?

**Comment by khmakoto** [comment]
Hi @rmittal1421 we have [a PR](https://github.com/OfficeDev/office-ui-fabric-react/pull/11844) out for it! I'm just waiting for an approval to merge it.
