### ISSUE TITLE
TagItem title renders `[object Object]` when children is not a string

### ISSUE THREAD

**Issue by onlyann** [OfficeDev/office-ui-fabric-react#11845]
### Environment Information

- **Package version(s)**: 7.85.0
- **Browser and OS versions**: All browsers

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/onlyann/pen/qBEzmQB

#### Actual behavior:

Hovering on the tag item displays _[object Object]_ when using a non string `children` prop to `TagPicker`.

#### Expected behavior:

Hovering on the tag item should either display the item name, or TagItem should allow title and aria-label to be passed in to override this behaviour.

The issue occurs because TagItem assumes that the `children` prop is a string and doesn't offer any way to specify our own title/aria-label

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes, if requested

Requested priority: Low

**Comment by khmakoto** [comment]
Hi @onlyann, thanks for filing this issue! I can confirm that I can repro this behavior. If you want to feel free to submit a PR to fix the issue, if not I'll be taking a stab at it as soon as I can. Thanks again!
