### ISSUE TITLE
How to run development build without karma?

### ISSUE THREAD

**Issue by fantua** [OfficeDev/office-ui-fabric-react#1184]
### Question

- __Package version(s)__: latest

I'm using `npm start` for development. Is there is possibility to run development build without karma? Build with karma is veeeery slow and it's running after any changes with livereload, so debugging process is unbearably slow.

**Comment by dzearing** [comment]
@fantua This is absolutely a known issue. Please be assured we are going to make this a lot better this week; right after the css modules migration, this is the most important thing that is slowing devs down that I'm addressing.

Some short term suggestions;

If you're working in office-ui-fabric-react, you can run:

```ts
gulp serve --production
```

This will skip tests and lint, and produce a localhost:4321/dist/office-ui-fabric-react.js bundle and keep it updated. That means you can literally just open codepen and reference this file and avoid building everything else. Here's a codepen example that hosts localhost scripts:

http://codepen.io/dzearing/pen/zZKywY

Yes, you can disable tests in individual gulpfile.js definitions. You can set them to disabled like so:

```ts
build.karma.isEnabled = () => false;
```

I am seeing most of the latency seems to stem from not just karma but from webpack bundling and typescript. As we build projects serially, just spinning up and tearing down node projects slows everything down as well.

The approach we're going to take is to invest in using webpack-dev-server in the npm start flow. CI can build the full everything, but for the inner loop we want not just tsc, but incremental bundling in memory. This will make the whole process of development so much less frictiony.

**Comment by micahgodbolt** [comment]
In our css-module branch we've already put `build.karma.isEnabled = () => true;` into the office-ui-fabric-react gulpfile, so it's easy to quickly turn off. But as David said, this should get better really soon.
