### ISSUE TITLE
Dialog changes dynamically from smaller to larger content 

### ISSUE THREAD

**Issue by jedmonsanto** [OfficeDev/office-ui-fabric-react#11855]
I think this is related to [#6493](https://github.com/OfficeDev/office-ui-fabric-react/pull/6493) feature, it's **Great** when your option is from Larger to Smaller content but how about from smaller to Larger, is there any way to set the props that will re-position the dialog?

**see below image from smaller to larger content:**
![image](https://user-images.githubusercontent.com/23548643/73669045-ca123c00-46e1-11ea-8887-5e26394b96c6.png)

![image](https://user-images.githubusercontent.com/23548643/73669465-705e4180-46e2-11ea-9ee2-2d37ec20eb38.png)

as you can see from the second snip, it's not centered anymore.

**Comment by xugao** [comment]
@jedmonsanto - i just checked and the dialog is adjusting the position dynamically when changing from smaller to larger content. see this - https://codepen.io/xugao/pen/wvBVZpZ

if you can provide a codepen to demo your case, that would help

**Comment by jedmonsanto** [comment]
thank you for your feedback, let me create a codepen then

**Comment by jedmonsanto** [comment]
@xugao i think removing the **topOffsetFixed** solve the issue in my end, accidentally copied in one of the example.

thanks
