### ISSUE TITLE
Any known issue with modal for iOS (using VoiceOver)?

### ISSUE THREAD

**Issue by Goopies** [OfficeDev/office-ui-fabric-react#11858]
### Environment Information

Safari and iOS with Voiceover

### Describe the issue:

We have an item using the modal component, in iOS the focus get stuck on the button and does not move to the modal window. 

### Please provide a reproduction of the issue in a codepen:

Not able to unfortunately, checking to see if this is a known issue. 

#### Actual behavior:

When the button is selected with a screen reader on, focus should move to modal window.

#### Expected behavior:

Focus gets stuck on the button, and continues to move through background elements.

### Documentation describing expected behavior

https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html

**Comment by xugao** [comment]
@Goopies - not any known issues, you can double check among all our issues [here](https://github.com/OfficeDev/office-ui-fabric-react/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+voiceover)

If you would like us to help you further, please provide more detailed repro steps and actual/expected behaviors

**Comment by Goopies** [comment]
I'm checking to see if I can get a codepen for this running with a working example. Getting more info from the developer.

**Comment by Goopies** [comment]
The issue happens with the Modal example, but in the specific instance we have the content takes a while to load. (Maybe a second, relatively long)

We're thinking that the order in which items load determine what is focused first, which can sometimes break when using iOS and VoiceOver. Is this a possibility?

**Comment by xugao** [comment]
@Goopies - do you have a codepen to demo the repro? also, do you repro this on desktop + VoiceOver?

**Comment by Goopies** [comment]
It only happens with iOS and VoiceOver. 

Here's a codepen which demonstrates the oddness which may be causing this:

https://codepen.io/Goopies/pen/vYOBBOb

If you open that with iOS and VoiceOver you'll notice a flicker of focus which goes from the close button to the Test Button.

Is that determined after load? Perhaps something could cause that focus to go to an unwanted object?

**Comment by xugao** [comment]
@Goopies - thanks for the info. i can confirm this is unfortunately a bug with Apple/VoiceOver.
you can repro this bug with any modal such as the example in https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html. 

I have filed a bug internally to later report it to Apple: https://dev.azure.com/Office/APEX/_workitems/edit/3942374

If you don't have further questions, I will go ahead close this issue

**Comment by Goopies** [comment]
Thanks for checking and reporting! Feel free to close.
