### ISSUE TITLE
why not Angular(ts, mvvm)?

### ISSUE THREAD

**Issue by zzz6519003** [OfficeDev/office-ui-fabric-react#11852]
For _how-to_ questions and other non-bugs, please use StackOverflow instead of Github issues. You can tag your questions with [office-ui-fabric](https://stackoverflow.com/questions/tagged/office-ui-fabric).

If you are a Microsoft employee you can also join the Microsoft UI Fabric teams channel.

**Comment by dzearing** [comment]
Duplicate of https://github.com/OfficeDev/office-ui-fabric-react/issues/11558
