### ISSUE TITLE
Dropdown: Tooltip placement for dropdown element is not on top of hovered item

### ISSUE THREAD

**Issue by gitReena** [OfficeDev/office-ui-fabric-react#11864]
### Environment Information

- **Package version(s)**: 7.84
- **Browser and OS versions**: All browsers.

### Please provide a reproduction of the bug in a codepen:
There is a repro in SPO RTE toolbar.

#### Actual behavior:

![image](https://user-images.githubusercontent.com/29931475/73707998-edbd8e00-46b1-11ea-9dbd-eda11ec3f4f0.png)

#### Expected behavior:

The tooltip placement of toolbar for items that have a dropdown should also be center-aligned and be on right top of the hovered item.

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal)

Products/sites affected: Sharepoint online

**Comment by xugao** [comment]
@gitReena - could you please provide me a minimal repro in a codepen, similar to [this](https://codepen.io/xugao/pen/xxGKXpJ)
