### ISSUE TITLE
Cleared Input Text is displaying again in People Picker with Edge Browser

### ISSUE THREAD

**Issue by zeedomD** [OfficeDev/office-ui-fabric-react#11865]
### Environment Information

- **Package version(s)**: Fabric React 7.88.0
- **Browser and OS versions**: Edge, windows 10

### Please provide a reproduction of the bug in a codepen:

This is issue can be repro in the demos in "https://developer.microsoft.com/en-us/fabric#/controls/web/peoplepicker".

1. Open https://developer.microsoft.com/en-us/fabric#/controls/web/peoplepicker with Edge browser.
2. Go to Normal People Picker.
3. Input any text (do not pick any person)
4. Then there is a "X" in the input textbox. (it will not show in Chrome, an old issue is tracking this issue https://github.com/OfficeDev/office-ui-fabric-react/issues/9032)
5. Click on the "X", it clears the input text.
6. Then click other places out of the input box.

#### Actual behavior:

The cleared string comes back and showing in the input box again.

#### Expected behavior:

The cleared string should not be displayed again in the input box.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by xugao** [comment]
@zeedomD - thanks for reporting! will get this fixed soon

**Comment by zeedomD** [comment]
Hi @xugao .

Thank you for working on this issue. When verifying this issue. We still can see this problem in our project.
In the Office Farbic React UI Demo, I didn't see the "x" button in People picker demo. But I still find it at https://developer.microsoft.com/en-us/fabric#/controls/web/pickers.
In the Custom Picker, we still can see the "x" in Edge browser (not the Edge Chromium), and when clear the input, then clicking on other place, the cleared text will show again. The issue is not fixed actually.
Could you help take a look?

Thank you
