### ISSUE TITLE
Set select name property on Dropdown

### ISSUE THREAD

**Issue by jmn** [OfficeDev/office-ui-fabric-react#11866]
#### Describe the feature that you would like added

Make it possible to set the `name=` property on Dropdown so that the select element will have it.
This seems to be possible at least with Textfield, although undocumented.

#### What component or utility would this be added to

Dropdown (and other input fields?)

#### Additional context/screenshots

I'd like to use a generic onChange function which relies on the input field having a `name` such as:
```
    private handleUserChange = evt => {
        const value = evt.target.value;
        this.setState({
            ...this.state,
            user: {
                ...this.state.user,
                [evt.target.name]: value,
            },
        });
    };
```

**Comment by xugao** [comment]
@jmn - I assume you meant our `ComboBox` component instead of `Dropdown`? If so, here is how you can set name: https://codepen.io/xugao/pen/dyobVLB. you can pass name using the `autofill` prop
