### ISSUE TITLE
Dropdown automatically selects first option if another focusable item is pressed

### ISSUE THREAD

**Issue by andrewhwng** [OfficeDev/office-ui-fabric-react#11873]
### Issue:
When the dropdown is open and nothing is selected, clicking on another focusable item (button, input, textarea, etc.) causes the first item in the dropdown to automatically select.

### Environment Information

- **Package version(s)**: 7.88.1

#### Actual behavior:

First item in the dropdown is selected.

#### Expected behavior:

No items are selected, placeholder is visible.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: OWA Calendar

**Comment by xugao** [comment]
@anandrajeswaran - thanks for reporting! Agree this is a bug. will work on a fix
