### ISSUE TITLE
MaskedTextField captures focus on re-render on Edge

### ISSUE THREAD

**Issue by gregoryfabry** [OfficeDev/office-ui-fabric-react#11871]
### Environment Information

- **Package version(s)**: 7.69.0
- **Browser and OS versions**: Microsoft Edge 44.17763.831.0
Microsoft EdgeHTML 18.17763

### Describe the issue:

On Edge, MaskedTextField recaptures focus after user leaves field if component is re-rendered.

#### Actual behavior:

On a page with a MaskedTextField:
1) Modify the MaskedTextField
2) Blur from the MaskedTextField
3) Take any other action that causes the MaskedTextField to rerender
4) **Focus has been set to the MaskedTextField**

#### Expected behavior:

On a page with a MaskedTextField:
1) Modify the MaskedTextField
2) Blur from the MaskedTextField
3) Take any other action that causes the MaskedTextField to rerender
4) **MaskedTextField is not focused**

### If applicable, please provide a codepen repro:

This behavior is related to the following code in MaskedTextField:

https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/TextField/MaskedTextField/MaskedTextField.tsx#L107-L112

I believe that it could be fixed by checking `this._isFocused` in the condition.

My understanding is that Edge (and IE, though I haven't tested it) set the focus to the input that setSelectionRange is invoked on, while Chrome and FF do not, resulting in the inconsistent behavior between browsers.

This should fix the following issues as well: https://github.com/OfficeDev/office-ui-fabric-react/issues/11835 https://github.com/OfficeDev/office-ui-fabric-react/issues/7580

**Comment by xugao** [comment]
@gregoryfabry - thank you for the detailed report (you even linked issues from the past, amazing :))
I can confirm reproing the bug. will look into fixing
