### ISSUE TITLE
Callout - position:fixed is relative to callout, not viewport

### ISSUE THREAD

**Issue by FlowIT-JIT** [OfficeDev/office-ui-fabric-react#11877]
### Environment Information

- **Package version(s)**: office-ui-fabric-core: 9.6.1, office-ui-fabric-react: 6.189.0
- **Browser and OS versions**: Chrome 79, macOS

### Please provide a reproduction of the bug in a codepen:

A Callout with light dismiss has a DOM structure like so:

![image](https://user-images.githubusercontent.com/10479064/73818498-ce2b8000-47ed-11ea-9fb2-147cf1cb7dff.png)

Notice how _d1_ has position:fixed and _d2_ has position:absolute. This changes the way position:fixed works for DOM elements contained in _d2_. Such elements will no longer be positioned relative to the viewport, but relative to _d2_. This likely breaks existing UI libraries relying on position:fixed. It does for us.
Could UI libraries use position:absolute instead? Well, there are good reasons for using position:fixed rather than position:absolute - position:fixed has the ability to "escape" overflow:scroll and overflow:hidden, allowing e.g. a DropDown to open outside of the scrollable or partially hidden area.

#### Actual behavior:

DOM elements within callout with position:fixed are not positioned relative to viewport as expected.

#### Expected behavior:

DOM elements within callout with position:fixed should be positioned relative to viewport.

### Solution and work around

**Work around**: Use Panel instead.

**Solution**: Move callout out of background layer - there is no need for these to be nested. They might just as well be structured like: `<d1></d1> <d2></d2>`

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: -

**Comment by xugao** [comment]
@FlowIT-JIT - you can force the callout to not layer by passing doNotLayer: true to the callout. This means that the callout will be a child of any element that it is hosted in. see [this pen] as example (https://codepen.io/xugao/pen/eYNYmmw?editable=true). As noted above this isn't the default behavior because now you'll need to worry about managing zindex and overflow, but it should enable the behavior you want.

**Comment by FlowIT-JIT** [comment]
Hi @xugao.
Thank you very much for your swift response - very much appreciated.
I'm sorry, I was not aware of this option. We will give it a try as soon as possible.
 - Thanks again :-)

**Comment by FlowIT-JIT** [comment]
@xugao, it turns out animation still prevents us from using position:fixed.
Using _animation_ or _transform_ creates a new containing block which affects positioning, just like the previously described DOM structure does.
I have changed the title of the issue to reflect the actual problem; not being able to use position:fixed in callouts.

**Comment by xugao** [comment]
@FlowIT-JIT - you can turn off the animation to fix your issue by passing styles prop to Callout. here is a demo: https://codepen.io/xugao/pen/gOpOzBK
Let me know if this solves :)

**Comment by FlowIT-JIT** [comment]
Of course - I didn't consider that. Hopefully that doesn't break in the future (fingers crossed).
Thank you :-)

**Comment by xugao** [comment]
@FlowIT-JIT - as discussed in referenced issue, we should provide way for user to turn off animation. but that is relatively long term. using `styles` prop is little fragile but i would say this scenario will unlikely to regress :)

**Comment by Jemt** [comment]
In case anyone else reads this;
I think I was mistaken in regards to the result of the example below.

```
<div style="position:fixed" id="d1">
    <div style="position:absolute" id="d2">
        <div style="position:fixed" id="d3">
```

At least I can no longer reproduce this nor find any documentation backing up this claim. So currently it seems only _transform_ or _animation_ creates a new containing block, meaning this problem can be resolved by just turning of animation. Disabling laying (doNotLayer) does not seem to be necessary.
