### ISSUE TITLE
Make the size/coinSize support string value

### ISSUE THREAD

**Issue by huiren-jiang** [OfficeDev/office-ui-fabric-react#11879]
#### Describe the feature that you would like added

Currently, the size/coinSize field of Persona props only supports number or PersonaSize as value type, which makes size value like "1em" impossible. Since the calculated size/coinSize is applied to width/height of Image which supports string type, is it also possible to make size/coinSize support string value?

#### What component or utility would this be added to

Persona and PersonaCoin

#### Have you discussed this feature with our team, and if so, who

N/A

#### Additional context/screenshots

The initials of Persona could be easily scaled by width/height of 'initials' styles using string value, while applying the same to 'image' styles has no effect even if size/coinSize is not set.

**Comment by xugao** [comment]
@huiren-jiang - in general, our library currently don't support changing size unit very well. in this specific case, it's not straight-forward to add the one-off support. reasons are:
1. We do internal calculation such as the presence icon size based on `coinSize`. 
2. We can probably change internal logic to handle # 1, however, i can't justify the exception since we don't support alternative unit everywhere.

Could you tell me if you are fully blocked on this?

**Comment by xugao** [comment]
@Markionium - any thoughts?

**Comment by huiren-jiang** [comment]
Got it. The `dimension` value calculated by `coinSize || sizeToPixels[size]` will decide the size of other elements such as font. These calculations make everything work fine if user don't want to care too much details about it.

The question here is, when `size` and `coinSize` are not given, the inner Image for user photo will use the default Image size 48. In this situation, the coin will even be bigger than the container element which is unexpected. So is it possible to do something as below?

1. Adapt the dimension of Image to the outer container div by calculating the `dimension` as `coinSize || sizeToPixels[size] || max(imageArea.width, imageArea.height)`.

2. Add a style for the inner Image and expose it in PersonaStyle. 

Any of the above changes could let user control the size of user photo arbitrarily just as initials and container div.

**Comment by xugao** [comment]
@huiren-jiang - the blocker here is not with PersonaCoin but PersonaPresence:
https://github.com/OfficeDev/office-ui-fabric-react/blob/a5bbc76367eb01e993f20796955569f422a538b2/packages/office-ui-fabric-react/src/components/Persona/PersonaPresence/PersonaPresence.base.tsx#L42

Do you set Presence in your use case? if not, i might be able to provide you a way to work around this
