### ISSUE TITLE
[Icon Tool] New Edge Logo?

### ISSUE THREAD

**Issue by jkipk** [OfficeDev/office-ui-fabric-react#11874]
Planning to use Fabric Core Icon set for our website, an independent news and information site focused on Microsoft. Edge (Chromium) has a new logo, yet it is not included in the icon set (for either Fabric Core or Fabric React). Any plans to include the new Edge icon?

Thanks,
Kip Kniskern

### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by xugao** [comment]
@Jahnp - any plan to add new Edge icon?

**Comment by xugao** [comment]
tracking all new icon requests in #11886. closing this one as dup
