### ISSUE TITLE
Module CSS: icon Button's height is changed.

### ISSUE THREAD

**Issue by MirandaGe** [OfficeDev/office-ui-fabric-react#1187]
### Bug Report

- __Package version(s)__: beta
- __Browser and OS versions__: any

#### Describe the issue:

In previous version, the width and height is 32px:
![image](https://cloud.githubusercontent.com/assets/16030290/23613541/d4ee3660-02ba-11e7-94bf-c385617ed6ea.png)

After update, the width and height becomes 40px:
see code in
https://github.com/OfficeDev/office-ui-fabric-react/blob/module-css-updates/packages/office-ui-fabric-react/src/components/Button/IconButton/IconButton.scss
```
  width: $button-iconButtonSize;
  height: $button-iconButtonSize;
```

#### Expected behavior:

keep 32px.

**Comment by dzearing** [comment]
Thanks. I will take a look.

**Comment by dzearing** [comment]
Reverted, published in beta8.
