### ISSUE TITLE
Disable active button focus

### ISSUE THREAD

**Issue by yalian-icom** [OfficeDev/office-ui-fabric-react#11881]
### Environment Information

- **Package version(s)**: 7.84.0
- **Browser and OS versions**: all browers

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/yalian-icom/pen/ExjYGZK

#### Actual behavior:

If I provide allowDisabledFocus property to button it's not set tabIndex="-1"

#### Expected behavior:

If I provide allowDisabledFocus property to button I will expect that the button being set tabIndex="-1"

**Comment by xugao** [comment]
@yalian-icom -
The purpose of `allowDisabledFocus` prop is "Whether the button can have focus in disabled mode"

So if you want to disallow focus when a button is disabled, here is the code to do that:
```
        <DefaultButton
          allowDisabledFocus={false}
          disabled
          onClick={() => alert("hello")}
        >
```

let me know if this answers you

**Comment by yalian-icom** [comment]
So that means that I cannot use allowDisabledFocus when the button is active? :(

**Comment by xugao** [comment]
@yalian-icom - no. but may i ask why you want to disable focus for the button if it's active?

**Comment by yalian-icom** [comment]
![Immagine](https://user-images.githubusercontent.com/59922213/73959637-e7295380-4909-11ea-8c88-e2ac4f7793cb.png)
In this case the ActionButton, I don't want the input take focus when the user press tab to change the input

**Comment by xugao** [comment]
@yalian-icom - you can pass `tabIndex={-1} ` prop to the component. see [example](https://codepen.io/xugao/pen/PoqoawX?editable=true)

**Comment by yalian-icom** [comment]
@xugao Working perfectly, thx, I will close the issue
