### ISSUE TITLE
Icons are not rendered anymore

### ISSUE THREAD

**Issue by fildahui** [OfficeDev/office-ui-fabric-react#11885]
I noticed that (custom) icons are not rendered anymore after updating to the latest version of fabric.
I then started rolling back the version until I found the last working one is 7.79.0.

Looking through the commit history v. 7.79.1 (https://github.com/OfficeDev/office-ui-fabric-react/pull/11556) introduced some changes about caching null/undefinedl icons when they're requested. I'm supposing nothing has changed in relation of how I should register icons, as the documentation is the same as before.

I created a sample app that uses two (fake) libs one build with fabric version 7.79.0 and the other with 7.79.1. I saw that the bundle created with version 7.79.1 does not contain the function `getIcon(iconName)` anymore and moreover this is what the `getIconContent` function looks like:

![image](https://user-images.githubusercontent.com/17295499/73851455-67c25400-4825-11ea-9d02-a1c310716580.png)

Instead this is how `getIconContent` looks like in the bundle when using fabric 7.79.0:

![image](https://user-images.githubusercontent.com/17295499/73851519-858fb900-4825-11ea-84c1-c763e0ca9f1b.png)

I also notice that if I do call `getIcon()` (without arguments) when registering the icons it "fixes" the issue, though I doubt that's meant to be used that way.

### Environment Information

- **Package version(s)**: 7.79.1 (and above)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

you can find a sample app [`here`](https://github.com/fildahui/icons-issue):
it's a simple react app which is using two libs (with the same exact code) one built with fabric v.7.79.0 and the other built with fabric v.7.79.1: the issue manifests itself only with version 7.79.1

Icons used are v.5.4.1 of font-awesome (free) but this applies to any custom fonts.

In this sample icons are used with the `IconButton` but the same behaviour applies to all the components that render icons.

#### Actual behavior:

Icons are not rendered

#### Expected behavior:

Icon should be rendered, as before

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

**Comment by xugao** [comment]
@fildahui - thanks for the repro. i can indeed see the issue here. The compiled code definitely seems wrong and I don't have a good explanation yet. Let me dig more

**Comment by xugao** [comment]
Comparing the 2 bundles:

![image](https://user-images.githubusercontent.com/1207059/73883287-8706b480-4818-11ea-8dce-e16d7dbf9194.png)

![image](https://user-images.githubusercontent.com/1207059/73883252-77876b80-4818-11ea-88c6-ecd6d63f567a.png)

also note, adding `import { getIcon } from 'office-ui-fabric-react/lib/Styling' brings in `getIcon` and fixes the problem

looked at the build setup [here](https://github.com/fildahui/icons-issue), nothing jumps out to me.

@kenotron - do you have some ideas here?

**Comment by fildahui** [comment]
Hi @xugao 
many thanks for the feedback. 

Yes, I had already compared the two bundles (the images in my first post come from the comparison of the two) and seen the `getIcon` function is missing in the bundle with v.7.79.1. 
I've also seen that when you import that function it fixes the issue, but I don't think I should explicitly import `getIcon` to make it work...

The thing is the rollup configs and the source files are all the same in both cases so I do not see why the output should be different when using v. 7.79.1 (as you can see in the righthand side of your images or in my first one)

**Comment by xugao** [comment]
@fildahui - I tried to repro such aggressive tree-shaking using rollup [here](https://rollupjs.org/repl/?version=1.31.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMnZhciUyMG5vcm1hbGl6ZUljb25OYW1lJTIwJTNEJTIwZnVuY3Rpb24lMjAobmFtZSklMjAlN0IlMjByZXR1cm4lMjBuYW1lLnRvTG93ZXJDYXNlKCklM0IlMjAlN0QlM0IlNUNuJTVDbmZ1bmN0aW9uJTIwZ2V0SWNvbihuYW1lKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjB2YXIlMjBpY29uJTIwJTNEJTIwdW5kZWZpbmVkJTNCJTVDbiUyMCUyMCUyMCUyMG5hbWUlMjAlM0QlMjBuYW1lJTIwJTNGJTIwbm9ybWFsaXplSWNvbk5hbWUobmFtZSklMjAlM0ElMjAnJyUzQiU1Q24lMjAlMjAlMjAlMjBuYW1lJTIwJTNEJTIwX2ljb25TZXR0aW5ncy5fX3JlbWFwcGVkJTVCbmFtZSU1RCUyMCU3QyU3QyUyMG5hbWUlM0IlNUNuJTIwJTIwJTIwJTIwaWYlMjAobmFtZSklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwaWNvbiUyMCUzRCUyMF9pY29uU2V0dGluZ3MlNUJuYW1lJTVEJTNCJTVDbiUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjByZXR1cm4lMjBpY29uJTNCJTVDbiU3RCU1Q24lNUNuY29uc3QlMjBnZXRJY29uQ29udGVudCUyMCUzRCUyMChpY29uTmFtZSklMjAlM0QlM0UlMjAlN0IlNUNuJTIwJTIwJTIwJTIwY29uc3QlMjAlN0IlMjBjb2RlJTJDJTIwc3Vic2V0JTIwJTdEJTIwJTNEJTIwZ2V0SWNvbihpY29uTmFtZSklMjAlN0MlN0MlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwc3Vic2V0JTNBJTIwJTdCJTdEJTJDJTVDbiUyMCUyMCUyMCUyMCUyMCUyMGNvZGUlM0ElMjB1bmRlZmluZWQlNUNuJTIwJTIwJTIwJTIwJTdEJTNCJTVDbiU1Q24lMjAlMjAlMjAlMjBpZiUyMCghY29kZSklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwcmV0dXJuJTIwbnVsbCUzQiU1Q24lMjAlMjAlMjAlMjAlN0QlNUNuJTVDbiUyMCUyMCUyMCUyMHJldHVybiUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBjaGlsZHJlbiUzQSUyMGNvZGUlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwaWNvbkNsYXNzTmFtZSUzQSUyMHN1YnNldC5jbGFzc05hbWUlMkMlNUNuJTIwJTIwJTIwJTIwJTIwJTIwZm9udEZhbWlseSUzQSUyMHN1YnNldC5mb250RmFjZSUyMCUyNiUyNiUyMHN1YnNldC5mb250RmFjZS5mb250RmFtaWx5JTVDbiUyMCUyMCUyMCUyMCU3RCUzQiU1Q24lMjAlMjAlN0QlM0IlNUNuJTVDbmdldEljb25Db250ZW50KCklMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==). but i cannot repro the level of extreme you saw. I am guessing this is a bug with rollup treeshaking. could you open an issue on their github to get further help?

**Comment by fildahui** [comment]
@xugao I saw your rollup sample but you're directly bundling 2 js functions in there, that's always going to work that way, it's completely different from what is happening in my samples.

Also if you think that the same exact code I have (same modules versions, same sources, same configs) is producing two different outputs only because of the fabric version used then I wouldn't be 100% sure it's _just_ rollup. 
Something has changed in your codebase that's (probably) causing the issue with rollup. I'll have another closer look tomorrow anyway

**Comment by xugao** [comment]
Yes. i do think us adding 
```
    if (!code) {
      return null;
    }
```
in [this PR](https://github.com/OfficeDev/office-ui-fabric-react/pull/11556/files) triggered this bug. 

rollup thinks `code` is falsy somehow and i can't think of a reason why. i do think this is a reasonable question to raise with rollup team. 

let me know if you have further findings

**Comment by fildahui** [comment]
Hi @xugao 
just an update, I opened an issue with rollup which has been tagged as `bug`. I'll wait for them to fix it. 
(anyway, if you're interested the issue is [here](https://github.com/rollup/rollup/issues/3382))
