### ISSUE TITLE
Detail List - SelectionMode.none having accessibility issue with custom checkbox column 

### ISSUE THREAD

**Issue by MdAmeerMind** [OfficeDev/office-ui-fabric-react#11889]
Actual Behavior:
1) Narrator/NVDA is pronounce checkbox selection in column with spacebar as "Space"
2) Checkbox check/uncheck is not happening by using enter key

Expected:
Narrator/NVDA should pronounce as checkbox select / Checkbox un-select on click on space bar.
Checkbox should be check/uncheck by using enter key .

Repro: https://codepen.io/mdameer/pen/gOpOoVB

Repro Step:
Use NVDA/Narrator , tab to row and move to checkbox.
Now press space bar, it pronounce as space bar also by using Enter key it is not performing any action.

**Comment by xugao** [comment]
@MdAmeerMind - in your case, you are rendering the checkbox yourself, that means you need to manage its state.

Did you intend to customize the checkbox rendering?
Why not use `selectionMode.single` and let us handle everything?

If you do need to customize the checkbox rendering, you can use `onRenderCheckbox` prop. here is [a demo how you do it](https://codepen.io/xugao/pen/oNXNMWr?editable=true)

**Comment by MdAmeerMind** [comment]
Hi @xugao ,
Thanks for your input,  The Demo you had shared is still having accessibility issue which I have raise . Like selection of Checkbox , NVDA is still pronounce as space for row selection.
Other issue like selection for checkbox not happen with mouse click.  Multiple selection are not working.

Our actual requirement for custom checkbox column is
1) we need checkbox column in details list at any column location( First or Last Column).
2) Bind value for checkbox from server side value. Our some checkbox in details list are by default selected/un-selected as per requirement once user lands on page.
3) We wont allow row selection on clicking on entire row as some column values are copied by user using mouse for other operation in application.

To achieve above requirement we have added custom column with checkbox rendering. It works fine for us except accessibility issue mention in this bug.

**Comment by xugao** [comment]
reopening this to triage further , closing #11914 since details are in this issue

**Comment by xugao** [comment]
@MdAmeerMind - after looking at your requirements, i am afraid these are not something `DetailsList` is designed to support. You might be able to achieve what you need by managing your own keyboard event (implement onKeyDown and manage the selected state for the checkbox). But this is quite hacky and I doubt you can get accessibility fully correct with your implementation. 

In general, `DetailsList` is packed with all kinds of functionalities now and unfortunately we can no longer accept feature requests towards this component

**Comment by MdAmeerMind** [comment]
Hi @xugao , Thank you for your input.
