### ISSUE TITLE
Dropdown text is not updating if defaultSelectedKey is set

### ISSUE THREAD

**Issue by chnldw** [OfficeDev/office-ui-fabric-react#11902]
### Environment Information

- **Package version(s)**: 7.90.0
- **Browser and OS versions**: Windows 10, Chrome, 79.0.3945.130

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/chnldw/pen/poJvRJP

#### Actual behavior:

If defaultSelectedKey is set to the Dropdown component
Dropdown text is not updating after new option selected.

#### Expected behavior:

Dropdown should show the new selected option

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/sites affected: (if applicable)

**Comment by xugao** [comment]
@chnldw - i can confirm the repro. will fix asap

**Comment by xugao** [comment]
@chnldw - checked again, this is actually bug in your pen. here is how to do the controlled dropdown correctly: https://codepen.io/xugao/pen/ExjaZWe
1. your `selectedItem` state was set and used incorrectly
2. also, you should not use both `defaultSelectedKey` and `selectedKey` . `defaultSelectedKey` is only for uncontrolled case

**Comment by chnldw** [comment]
@xugao Sorry, I forked this codepen from official document. I've removed the code to consume `selectedKey`. It still doesn't work. However it works after `onChange` is removed.
https://codepen.io/chnldw/pen/poJvRJP
`selectedKey={selectedItem ? selectedItem.key : undefined}`

**Comment by xugao** [comment]
@chnldw - ok i think there is a bug here when you re-render the dropdown component. it's not that you cannot pass `onChange`, it seems to be caused by state change inside `onChange`. if you comment out `setState` like [this](https://codepen.io/xugao/pen/ExjaZLG), it works. i will look into more

**Comment by xugao** [comment]
@chnldw - just looked into the code more. this is happening you are mutating `options`:
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx#L149

[Here](https://codepen.io/xugao/pen/zYGGzRj) is how you fix it.

Let me know if you have further questions
