### ISSUE TITLE
Add onRenderLabel property to Slider control

### ISSUE THREAD

**Issue by qxg** [OfficeDev/office-ui-fabric-react#11904]
#### Describe the feature that you would like added

Add onRenderLable property to Slider control so that we can customize Slider label.

#### What component or utility would this be added to

Slider

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

Most other controls with label provided onRenderLabel property. It's strange Slide doesn't have it.

**Comment by xugao** [comment]
@qxg - Agree on adding this support. Will work on this soon

**Comment by xugao** [comment]
@qxg - we are currently trying to move away from `onRender` props and exploring a different pattern. see similar issue: #10234. for now, you can customize rendering of the label [like this](https://codepen.io/xugao/pen/YzXXEWd). let me know if you have questions
