### ISSUE TITLE
Can I use office-ui-fabric-react for my commercial app completely not related to Office365 and Microsoft?

### ISSUE THREAD

**Issue by pavlelekic** [OfficeDev/office-ui-fabric-react#11905]
I really like the Fabric UI, I find it much better than Material UI or Semantic UI or any other open source UI library, and I want to use it for my commercial web app, is it legal to do so? The app has nothing to do with Office365 or any other Microsoft product.

**Comment by xugao** [comment]
@pavlelekic - Of course you can! We are [a open source software with MIT license](https://www.npmjs.com/package/office-ui-fabric-react) :)
