### ISSUE TITLE
CommandBar: command with subMenuProps should not require on

### ISSUE THREAD

**Issue by pablonete** [OfficeDev/office-ui-fabric-react#1190]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

**Comment by cschleiden** [comment]
Same as #1191?
