### ISSUE TITLE
how to use onRenderCheckbox api

### ISSUE THREAD

**Issue by lvybriage** [OfficeDev/office-ui-fabric-react#11906]
#### Describe the feature that you would like added

In this [demo](https://codepen.io/jdh-msft/pen/PowORgm?editors=0010), when I click each row selection button, the expand row will also reopen. 

wish:  when I click the selection button, I wish the expand row will be hidden and the row is selected.

I try use the `onRenderDetailsCheckbox` function to rewrite this function, it failed.

code: 
```
<DetailsRow
                        {...detailsProps}
                        onRenderDetailsCheckbox={(): any =>
                            <div onClick={(e: React.SyntheticEvent<EventTarget>): void => {
                                e.stopPropagation();
                                console.info('复选框点击了'); // eslint-disable-line
                            }}>
                                <Checkbox />
                            </div>}
                    />
```

**Comment by xugao** [comment]
@lvybriage -
>wish: when I click the selection button, I wish the expand row will be hidden and the row is selected.

If this is what you need to do, overriding the check box rendering is not what you need to do here.
Instead, you should be using `selection` prop and defined `onSelectionChanged` handler. see [example here](https://codepen.io/xugao/pen/zYGGzYd). in your `onSelectionChanged`, you can control what items you want to render in the list

**Comment by lvybriage** [comment]
Hi, @xugao 
fabric api is
```
export interface ISelectionOptions<TItem = IObjectWithKey> {
    onSelectionChanged?: () => void;
    /** Custom logic to generate item keys. Required if `TItem` does not have a `key` property. */
    getKey?: (item: TItem, index?: number) => string | number;
    canSelectItem?: (item: TItem, index?: number) => boolean;
    selectionMode?: SelectionMode;
}
```
my code is like this:
```
private getSelectedRows = new Selection({
       onSelectionChanged: (event?: React.SyntheticEvent<EventTarget>): void => {
            if (event !== undefined) {
                event.stopPropagation();
                console.info('test'); // eslint-disable-line
            }
            this.setState(() => ({ selectRows: this.getSelectedRows.getSelection() }));
        }
    });
```
because **onSelectionChanged?: () => void;** , so, it doesn't run event.stopPropagation(); console.info('test'); ？

**Comment by xugao** [comment]
@lvybriage - what are you trying to do by prevent the click event to propagate?
