### ISSUE TITLE
the list is not scrollable if it's hidden initially.

### ISSUE THREAD

**Issue by lzl124631x** [OfficeDev/office-ui-fabric-react#11903]
### Environment Information

- **Package version(s)**: (fill this out)

```
$ npm view office-ui-fabric-react version
7.90.0
```

- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/lzl124631x/pen/WNvbRXj?editors=0110

#### Actual behavior:

In the codepen, the focus zone was hidden initially and then shown. The list is not scrollable.

![image](https://user-images.githubusercontent.com/5824517/74075538-c293b100-49c7-11ea-8ef5-4a01e18a43c1.png)

#### Expected behavior:

It should be scrollable just like when you set the `active` to be `true` initially in the state.

![image](https://user-images.githubusercontent.com/5824517/74075530-b0197780-49c7-11ea-81db-48508bf922e5.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by xugao** [comment]
@lzl124631x - i cannot repro with [the pen](https://codepen.io/lzl124631x/pen/WNvbRXj?editors=0110) you provided. could you tell me your OS + Browser versions? 

To quickly unblock you (in case there is a bug here), you might be able to work around this by not changing the visibility of the `FocusZone`, instead, set on some other element

**Comment by lzl124631x** [comment]
I'm using win + Chrome (Version 79.0.3945.130 (Official Build) (64-bit)).

That's just the minimal repro example. In my real world scenario, the list is in a dropdown which is collapsed at the beginning and is only visible when the user opens the dropdown.

**Comment by xugao** [comment]
@lzl124631x - I see now. Setting visibility affects the measurement. What you can do is when you ready to display it, call `forceUpdate`. Example [here](https://codepen.io/xugao/pen/RwPPVwL)

**Comment by lzl124631x** [comment]
Thanks! It works :D
