### ISSUE TITLE
ToolTipHost has scroll issue, gets close on mouse scroll.

### ISSUE THREAD

**Issue by mahendrakulkarni177** [OfficeDev/office-ui-fabric-react#11907]
### Environment Information

- **Package version(s)**: (7.90.1) 
- **Browser and OS versions**: (Chrome latest version)

### Describe the issue:

if ToolTip host has come scroll then on mouse scroll tooltip get closed.

#### Actual behavior:

if ToolTip host has come scroll then on mouse scroll tooltip get closed.

#### Expected behavior:

if ToolTip host has come scroll then on mouse scroll content should scroll.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) - No

Requested priority: (Blocking, High, Normal, Low) - High

Products/sites affected: (if applicable) - Yes

NOTE - Any solution before you release your next version will be helpful.

**Comment by xugao** [comment]
related to fix #9749

**Comment by smhigley** [comment]
Just as a small a11y note: a scrolling tooltip will fail keyboard accessibility
