### ISSUE TITLE
Panel Fluent Style: Align the headerText and closeButton

### ISSUE THREAD

**Issue by wemmaling** [OfficeDev/office-ui-fabric-react#11912]
### Environment Information

- **Package version(s)**: 7.88.0
- **Browser and OS versions**: Chrome Version 79.0.3945.130

### Describe the issue:

![image](https://user-images.githubusercontent.com/16534682/74207325-18af6f80-4cba-11ea-95eb-3455f5d08743.png)

in the panel, the title ‘News link’ is rendered in panel navigation rather than panel header. So It will be not fluentized followed Fabric panel headerText. But by following Fabric Panel fluent style, the title and close button will not be aligned.
 It makes styles inconsistent.

#### Actual behavior:
The headerText and closeButton are not aligned.

![image](https://user-images.githubusercontent.com/16534682/74207365-41376980-4cba-11ea-891f-649e4e0a516a.png)

#### Expected behavior:

![image](https://user-images.githubusercontent.com/16534682/74207355-38df2e80-4cba-11ea-8609-956fac72f6d2.png)

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: SharePoint Sites - Home - New - New links

**Comment by xugao** [comment]
@wemmaling - i think this has something to do with the way you implemented. see our examples in [here](https://developer.microsoft.com/en-us/fabric#/controls/web/panel), which are aligned.

**Comment by wemmaling** [comment]
@xugao If Panel has onRenderNavigation, they wil not aligned, right?

**Comment by wemmaling** [comment]
@xugao I found that this change just checked in 24 days ago.(https://github.com/OfficeDev/office-ui-fabric-react/pull/11391) And we found the problem before that. Glad to see it has been fixed.
