### ISSUE TITLE
[DetailsList] Option to divide available width equally to columns (+ considering content)

### ISSUE THREAD

**Issue by lukasbash** [OfficeDev/office-ui-fabric-react#11915]
#### Describe the feature that you would like added

Adding fixed values (also min and max values) to every single column inside a table is very cumbersome (especially when coding multiple layouts for the application).
Therefore I would like to request a feature to 1.) equally divide the available width of the table for the rendered columns and 2.) reduce the size of a column as much as possible so that the content of the column does not have an overflow (i.e. "fit to content" for all columns).

#### What component or utility would this be added to

DetailsList (and any other table component that might exist at the point of implementation)

#### Have you discussed this feature with our team, and if so, who

\-

#### Additional context/screenshots

\-

**Comment by xugao** [comment]
related to issue #9643. 
@lukasbash - unfortunately we are no longer taking new feature requests on DetailsList at the moment
