### ISSUE TITLE
ShimmeredDetailsList and aria-busy

### ISSUE THREAD

**Issue by fildahui** [OfficeDev/office-ui-fabric-react#11916]
The `ShimmeredDetailsList` component is meant to be used when waiting for data to be loaded (like a busy state).
Looking at the source code, it's rendering a `DetailsList` and setting `isPlaceholderData` to `true` when the shimmer is enabled. Based on this property, then, the `aria-count` attribute is set on the grid div of the `DetailsList`.

I was wondering if there is a specific reason why you don't set `aria-busy="true"` when the shimmer is enabled.. I mean, it's supposed to be a busy state so why not setting that attribute too? Don't you consider that to be a valid usage?

for example, something like this:
```javascript
...
    <div
          role="grid"
          **aria-busy={isPlaceholderData}**
          aria-label={ariaLabelForGrid}          
          aria-rowcount={isPlaceholderData ? -1 : rowCount}
          aria-colcount={(selectAllVisibility !== SelectAllVisibility.none ? 1 : 0) + (adjustedColumns ? 
         adjustedColumns.length : 0)}
          aria-readonly="true"
   >
...
```
Just wondering if there's an appropriate reason I'm not seeing straight away

**Comment by xugao** [comment]
@fildahui - I don't have a great answer for you but couple things:
1. when `enableShimmer` is set to true, like [in this example](https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/shimmer), user can set `ariaLabelForShimmer` which will be the `aria-label` of the `div` you pointed out above. 
2. What is the bug you are experiencing here? If you can describe to me in details (actual vs. expected results), I might be able to assist you better

**Comment by cschlechty** [comment]
Yes, adding aria-busy="true" while shimmer is enabled would make sense. It ensures the screen reader ignores the inner content until ready.
