### ISSUE TITLE
ContextualMenu caused by collapsed SideBar prevents text inputs onChange from firing on first click

### ISSUE THREAD

**Issue by v-wihuyn** [OfficeDev/office-ui-fabric-react#11921]
### Environment Information

- **Package version(s)**: (fill this out)
business-app/fabric: 3.14.0
office-ui-fabric-react: 6.192.1

- **Browser and OS versions**: (fill this out if relevant)
Microsoft Edge 44.18362.449.0
Microsoft EdgeHTML 18.18363

Mozilla Firefox: 72.0.2 (64-bit)

Google Chrome: 80.0.3987.100 (Official Build) (64-bit)

#### Actual behavior:

Business App Fabric Sidebar component contains submenu with buttons with routes to other pages containing text inputs. When Sidebar is collapsed, submenu contents are displayed in a ContextualMenu

In Edge, when a user routes to a new page from a button in a ContextualMenu and clicks on any text input on the new page, the ContextualMenu closes, the element is focused, but its onChange will not fire until the user clicks a second time

In Firefox, when a user routes to a new page from a button in a ContextualMenu and clicks on any text input on the new page, the ContextualMenu closes but the element is NOT focused until the user clicks a second time.

#### Expected behavior:

In Chrome, when a user routes to a new page from a button in a ContextualMenu and clicks on any text input on the new page, the ContextualMenu closes, the element is focused, its onChange fires when the user types without having to click a second time.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)
Microsoft Power Virtual Agents

**Comment by xugao** [comment]
@v-wihuyn - do you have a codepen to repro the issue without dependency on `business-app/fabric` ?
Have you reported the issue first with owners of `business-app/fabric` package first to confirm the bug is caused by Fabric?
