### ISSUE TITLE
[SpinButton] Add errorMessage and onGetErrorMessage

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [OfficeDev/office-ui-fabric-react#11923]
#### Describe the feature that you would like added

There is no error state for the SpinButton like there is for TextField. I would like to use the `errorMessage` or `onGetErrorMessage` props to show an invalid state.

#### What component or utility would this be added to

SpinButton

#### Have you discussed this feature with our team, and if so, who

No

**Comment by xugao** [comment]
@a-b-r-o-w-n - we are tracking this issue in #7636. for the short term, you will need to implement this outside of `SpinButton` component in your application code
