### ISSUE TITLE
Content Hidden : DetailsList component content gets hidden on Edge and Firefox

### ISSUE THREAD

**Issue by adityavibhute** [OfficeDev/office-ui-fabric-react#11935]
### Environment Information

- **Package version(s)**: office-ui-fabric-react - 6.211.1
- **Browser and OS versions**:  Firefox (72.0.2 (64-bit))  Edge (44.18362.449.0)

#### Actual behavior:
Delete icon gets invisible after exceeding number of items
![image](https://user-images.githubusercontent.com/29267927/74329625-2d712d80-4db6-11ea-9e0e-fecb4c514cc7.png)

#### Expected behavior:
Delete icon should be visible clearly. But when we open and close Dev tools, it gets visible
![image](https://user-images.githubusercontent.com/29267927/74329694-4d085600-4db6-11ea-8a74-0c73d018b781.png)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Blocking

Products/sites affected: (if applicable)

**Comment by xugao** [comment]
@adityavibhute - could you provide a codepen/codesandox link with code which repros the issue?

**Comment by adityavibhute** [comment]
@xugao Please find the codepen snippet https://codesandbox.io/s/goofy-nobel-nmos0?fontsize=14&hidenavigation=1&theme=dark and let us know your feedback on this.

**Note** : Kindly open it in Edge or Firefox.

**Comment by xugao** [comment]
@adityavibhute - I can confirm this is an issue in Edge, but not FF (lastest version). I believe you are experiencing the same issue here as #9662. There are couple work around suggestions there, which you can try

**Comment by xugao** [comment]
@adityavibhute - another option for you to consider in addition to what was mentioned in #9662 is that you can set `<ScrollablePane scrollbarVisibility={ScrollbarVisibility.always}>` to always show the scroll bar since the resizing is caused by it
