### ISSUE TITLE
PeoplePicker: Allow to configure props for the rendered Personas

### ISSUE THREAD

**Issue by alex3683** [OfficeDev/office-ui-fabric-react#11932]
#### Describe the feature that you would like added

In the people picker I'm missing an option to pass props to the underlying persona components, as rendered in the selection list and the suggestion callout. Since I globally configured all other personas to look and behave the same, I'd expect to adjust these to my needs as well.
For example I disabled initials rendering and fading-in on all other personas.

I can see that there is something like `defaultProps` containing `personaProps` in the documentation, but I don't know how to configure it and every attempt in code failed. So maybe just some documentation is missing.

#### What component or utility would this be added to

Probably the `IPeoplePickerProps` interface of the `BasePeoplePicker`.

#### Have you discussed this feature with our team, and if so, who

nope

#### Additional context/screenshots

I guess this needs no further context or screenshots. If you think differently, I'd try to provide some.

**Comment by xugao** [comment]
@alex3683 - Maybe I didn't get your ask here? But you can certainly define `IPersonaProps` in peoplepicker since `defaultSelectedItems`, `selectedItems` and `onResolveSuggestions` are where you define what personas are being displayed in input box and in the suggestion list. Let me know if this answers you

**Comment by alex3683** [comment]
My bad. You are totally right. I was just focusing on the completely wrong part of the component ...
Sorry for bothering you 😳
