### ISSUE TITLE
How to use colors via JavaScript variables?

### ISSUE THREAD

**Issue by chryw** [OfficeDev/office-ui-fabric-react#11951]
I'm trying to follow this example:
https://developer.microsoft.com/en-us/fabric#/styles/web/colors/neutrals

```js
import { NeutralColors } from '@uifabric/fluent-theme/lib/fluent/FluentColors';

<div style={{ color: NeutralColors.gray10 }} />;
```

However I don't know which package I should be installing besides office-ui-fabric-react. I don't see `fluent-theme` in v7.93.0.
![image](https://user-images.githubusercontent.com/7075677/74501668-b0ba7e00-4e9f-11ea-8096-f921bd3b029a.png)

I also found this issue #9894 but still can't figure out the fix.

Can anyone help? Thanks!

**Comment by xugao** [comment]
@chryw - this is the package you should be using: https://www.npmjs.com/package/@uifabric/fluent-theme

Pls close the issue if this answers you :)

**Comment by chryw** [comment]
Thanks @xugao ! I thought I would get this when upgrading to Fabric 7 but looks like it doesn't come with that package (just like the icons). Could you put some notes in the docs? Thank you!
