### ISSUE TITLE
DetailsList renders twice after scrolling is finished

### ISSUE THREAD

**Issue by chce** [OfficeDev/office-ui-fabric-react#11953]
### Environment Information

- **Package version(s)**: 7.69.3
- **Browser and OS versions**: Chrome 80 / Windows 10

### Please provide a reproduction of the bug in a codepen:
The issue has been described here, but hasn't been given its own issue:
https://github.com/OfficeDev/office-ui-fabric-react/issues/8826

It can be reproduced on the example list, by running Chrome's performance tools and scrolling. You will see it causes a render after onAsyncIdle, and another after onScrollingDone:
https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist

#### Actual behavior:

onAsyncIdle and onScrollingDone are called in succession after scrolling is done, causing the list to be rendered twice

#### Expected behavior:

The list should only be rendered once. DetailsList doesn't actually expose the isScrolling boolean when rendering, which was the motivation for having isScrolling in the first place, see this PR:
https://github.com/OfficeDev/office-ui-fabric-react/pull/3547
There should either be an option to opt-out of this extra render(So onScrollingDone is not called if the parent component explicitly states it doesn't care about scrolling), or isScrolling should be exposed by DetailsList's onRenderRow and onRenderItemColumn so we can delay rendering of expensive columns. Having both would be optimal.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal
Products/sites affected: ?

**Comment by xugao** [comment]
@chce - thank you for the detailed report and being willing to provide PR.
@KevinTCoughlin - could you comment on @chce's suggested approaches before he/she spends time on making the code change?

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin - could you comment on @chce's suggested approaches before he/she spends time on making the code change?

Yes the setState call for `isScrolling` is a problem and causes unnecessary re-renders. It would be good to fix ideally in a backwards-compatible way.

**Comment by xugao** [comment]
@chce - pls go ahead issuing a PR
