### ISSUE TITLE
Memory Leak caused by __stylesheet__  in Fabric

### ISSUE THREAD

**Issue by SparshaSaha** [OfficeDev/office-ui-fabric-react#11955]
### Environment Information

- **Package version(s)**: (6.211.2)
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
 https://codesandbox.io/s/sparsha-sahadetailslistleak-shl1n?fontsize=14&hidenavigation=1&theme=dark

#### Actual behavior:

A memory leak caused by __stylesheet__ is noticeable when we render <DetailsList />. 

#### Expected behavior:

There should not be any memory leaks and once we unmount the list it should release the detached window object

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low)
Blocking

Products/sites affected: (if applicable)

**Comment by SparshaSaha** [comment]
@xugao It would be beneficial if you can go to the "Memory" tab. right after the "Performance" tab.
One Reaching there:-
1> Take a heapsnapshot.
2> Look for DetachedWindow
3> Expand the object to see the leaks

**Comment by SparshaSaha** [comment]
Here are steps with screenshots and explanations:
1. Open the sandbox in a new tab. you should be able to see a new "Untitled" window open up.
![image](https://user-images.githubusercontent.com/22150821/74729444-7f103100-526a-11ea-934e-486dcd314e2c.png)

2. Wait for some time. The window will close on its own and you will go back to the Tab with name "React App" as shown:
![image](https://user-images.githubusercontent.com/22150821/74729554-a404a400-526a-11ea-81a7-23df18d39439.png)

3. Once this happens. Open chrome dev tools and go to "Memory" tab.. 
![image](https://user-images.githubusercontent.com/22150821/74729638-c4346300-526a-11ea-9f04-3225e341047f.png)

4. Once you're there select  the top option named shl1n.csb.app click on "Take Snapshot"

5. Once the snapshot is taken search for "Detached CSS". and expand the objects as shown to find the Window\ leak.
![image](https://user-images.githubusercontent.com/22150821/74729907-386f0680-526b-11ea-972c-e65041a67feb.png)

Please get back to me if you face issues with reproduction of the leak. I will be happy to help :)

**Comment by xugao** [comment]
@SparshaSaha - i removed reference to DetailsList from your code pen [here](https://codesandbox.io/s/sparsha-sahadetailslistleak-jf226) and i see the same profiling result.

**Comment by SparshaSaha** [comment]
@xugao - I checked in the code pen updated by you. I do not any window leak after taking the screenshot.
We are looking for `Detached Window` in the heap snapshot..
Additionally you will not see a Detached CSSStylesheet object as well which comes up only once we render the <DetailsList /> component..

**Comment by xugao** [comment]
following up offline and waiting for a better repro demo

**Comment by xugao** [comment]
Based on my testing locally, this should be fixed by #12010. @SparshaSaha - pls verify and close this issue if it's fixed
