### ISSUE TITLE
Focus wont go inside tooltip link. how to provide focus ? And It should work with Narrator & NVDA.

### ISSUE THREAD

**Issue by v-jashr** [OfficeDev/office-ui-fabric-react#11952]
Current Behavior:
on hover tooltip appears but we have link inside tooltip and focus won't go inside tooltip link. how to provide focus.?

Expected Behavior:
Focus should go inside tooltip link. and It Narrator & NVDA should work provide info about it.

**Comment by xugao** [comment]
@v-jashr - that is expected. see [ARIA](https://www.w3.org/TR/wai-aria-practices-1.1/#tooltip)
>Tooltip widgets do not receive focus. A hover that contains focusable elements can be made using a non-modal dialog.

Dup w/ #11711
