### ISSUE TITLE
tslib update caused issue

### ISSUE THREAD

**Issue by lzl124631x** [OfficeDev/office-ui-fabric-react#11962]
### Environment Information

- **Package version(s)**: 7.93.0
- **Browser and OS versions**: (fill this out if relevant)

#### Actual behavior:

![image](https://user-images.githubusercontent.com/5824517/74574907-faf03d80-4f39-11ea-8320-d20147d985c3.png)
Removing `node_modules` and re-`npm install` doesn't help.

I have to run `npm install tslib` to get the build working.

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by xugao** [comment]
@lzl124631x - I cannot repro [here](https://codesandbox.io/s/throbbing-dream-idvdd). can you pls provide more details if you still think it's issue on our side:
1. npm package which contains minimal repro
2. what version of npm you are on
