### ISSUE TITLE
Toggle option is not visible while user is navigating with the help of keyboard in DetailsList Component

### ISSUE THREAD

**Issue by lavanya-kuda** [OfficeDev/office-ui-fabric-react#11967]
### Environment Information

- **Package version(s)**: office-ui-fabric-react - 6.211.0
- **Browser and OS versions**: Edge and chrome

### Describe the issue:
Toggle option is not visible while user is navigating with the help of keyboard in DetailsList Component
### Please provide a reproduction of the issue in a codepen:

https://codepen.io/lavanya-kuda/pen/PoqNdQw
#### Actual behavior:

Unable to access the toggle using keyboard

#### Expected behavior:

Should be able to access toggle using keyboard

**Comment by khmakoto** [comment]
Hi @lavanya-kuda, your codepen is not working, could you make sure your codepen renders things correctly? Thank you!
