### ISSUE TITLE
Touchmove event does not get fired for the DraggableZone component

### ISSUE THREAD

**Issue by katiearriagam** [OfficeDev/office-ui-fabric-react#11963]
### Environment Information

- **Package version(s)**: LTS
- **Browser and OS versions**: Chromium based browsers

#### Actual behavior:

Touchmove event doesn't get fired in the DraggableZone component, which means that dragging a modal with touch does not work.

**Dragging with touch - not working**
![Dragging with touch - not working](https://user-images.githubusercontent.com/14140121/74576933-def09a00-4f41-11ea-906e-b340bfe145f9.gif)

**Dragging with mouse - working**
![Dragging with mouse - working](https://user-images.githubusercontent.com/14140121/74576934-df893080-4f41-11ea-9dab-674ee43e6896.gif)

#### Expected behavior:

Touchmove event doesn't gets fired in the DraggableZone component.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: High (blocking for partner teams)

Products/sites affected: Office Online

**Comment by katiearriagam** [comment]
FYI: @jspurlin, @dzearing who apparently worked on the initial implementation for DraggableZone

**Comment by xugao** [comment]
@katiearriagam - will you be issuing a PR for fixing this?
