### ISSUE TITLE
Page component and loading overlay

### ISSUE THREAD

**Issue by tipantaz** [OfficeDev/office-ui-fabric-react#11968]
Created also a bug on azure, bug id 6165288

### Environment Information
https://businessappfabric.azurewebsites.net/#component=id__9

Currently on documentation page.

### Please provide a reproduction of the bug in a codepen:
https://businessappfabric.azurewebsites.net/#component=id__9

### Steps
Go to the page with loader active
Scroll the page

#### Actual behavior:
overlay scrolls as well.
Goes out of the view and you can see things that were supposed to be under it.
#### Expected behavior:
Overlay stays in place when scrolling and keeps covering page.
### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) 

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) Yes

**Comment by khmakoto** [comment]
Hi @tipantaz, please make a minimal repo of the component that's causing the issue that we can try, since looking at apps makes it difficult to determine if it is the fault of the component library or of the user of it.

**Comment by tipantaz** [comment]
Hey @khmakoto!
Thanks for taking a look at this.

Like I said though this is reproducible in the official demo page which does have the minimal.
https://businessappfabric.azurewebsites.net/#component=id__9

If you go to the Page component and enable the loader and then scroll you will see that the loader moves out of the view.

1)Go to the demo page https://businessappfabric.azurewebsites.net/#component=id__9
2)Enable the overlay
3)Scroll

Expected:
The overlay should not scroll

Actual:
The overlay scrolls out of view

If this is still a blocker I can try to create a codepen.
![image](https://user-images.githubusercontent.com/52921554/74822767-f5ae3c80-5305-11ea-8e44-4d68aa6ba061.png)

Thanks!

**Comment by aneeshack4** [comment]
@tipantaz the Page component doesn't look like Fabric's but the Overlay is Fabric's:
![image](https://user-images.githubusercontent.com/4161791/74883216-50a35c00-5325-11ea-89e4-5b76c0f997d0.png)
However the Fabric component out of the box does disable scrolling on mount: https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Overlay/Overlay.base.tsx#L18. As the Github said, if you can isolate this problem to just the Fabric Overlay component and still repro it, then we can take a look at this in more depth.

**Comment by tipantaz** [comment]
Hey @aneeshack4!
Thanks for the tip!
I though that the office-ui-fabric team also supported business fabric. That is my bad :(

Overlay works fine by itself. The problem appears only in this Page component by business fabric.
So it is not something that you should be bothered with.

Thanks again ans sorry to bother you!
