### ISSUE TITLE
DatePicker fires onSelectDate event twice when allowTextInput is set to true

### ISSUE THREAD

**Issue by 4Lexs4nder** [OfficeDev/office-ui-fabric-react#11978]
### Environment Information
- Packet version:  
  - 7.93.1

### Actual behavior:
- Set the DatePicker to have the initial date (set it's value property)
- Make sure allowTextInput is set to true
- Open datepicker and change it to some other date
- onSelectDate is fired twice with newly selected date value

Duplication of : [https://github.com/OfficeDev/office-ui-fabric-react/issues/7473](https://github.com/OfficeDev/office-ui-fabric-react/issues/7473) which was fixed but recently appeared again after some `npm update`

#### Expected behavior:
onSelectDate should be fired only ONCE.

### Priorities and help requested:
Requested priority: High 
_Requested priority reason: A lot of my pages are getting new data when this event is fired (currently i have set the allowTextInput to false)._

**Comment by khmakoto** [comment]
Hi @4Lexs4nder, thanks for filing this issue! I can confirm that this is indeed happening! I'll make a PR to fix this as soon as I can!
