### ISSUE TITLE
SwatchColorPicker component is not having aria-labels

### ISSUE THREAD

**Issue by lavanya-kuda** [OfficeDev/office-ui-fabric-react#11976]
### Environment Information

- **Package version(s)**: "office-ui-fabric-react": "6.211.0"
- **Browser and OS versions**: Edge and Chrome

### Describe the issue:
SwatchColorPicker is not handling aria-labels so when we focus on the branding color, it is not reading it.

### Please provide a reproduction of the issue in a codepen:
https://codepen.io/lavanya-kuda/pen/LYVZNxw

#### Actual behavior:

Unable to read the branding color when it is on focus

#### Expected behavior:

It should read the color when it is on focus.

**Comment by khmakoto** [comment]
Hi @lavanya-kuda, unfortunately, Narrator is reading the labels correctly for me. Can you check if that's the case for you with [this codepen](https://codepen.io/khmakoto/pen/XWbKqxV)? I checked in both Fabric 6 and 7 and it was working for me in both cases.
