### ISSUE TITLE
Allow DetailsList to render ghost items while the list is scrolling

### ISSUE THREAD

**Issue by chce** [OfficeDev/office-ui-fabric-react#11970]
#### Describe the feature that you would like added

Add ghost item rendering support to DetailsList by adding isScrolling to the arguments of the DetailsList render functions such as onRenderItemColumn. This is already possible for Lists, see:
https://developer.microsoft.com/en-us/fabric#/controls/web/list
"Rendering ghost items while the list is scrolling"

#### What component or utility would this be added to

DetailsList

#### Have you discussed this feature with our team, and if so, who

No

**Comment by xugao** [comment]
@chce  - I believe you can use [ShimmerDetailsList](https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/shimmer).
Pls kindly close the issue if this answers you.

**Comment by chce** [comment]
@xugao ShimmerDetailsList does not expose isScrolling in any of its render methods. Your linked example shows shimmering while retrieving data, but I am talking about delaying rendering of specific  columns while waiting for scrolling to stop.

**Comment by xugao** [comment]
@chce - is your ask to pass `isScrolling` state to `onRenderRow`?

**Comment by chce** [comment]
Sure for onRenderRow, but especially onRenderItemColumn, as it's usually a specific column you want to delay

**Comment by xugao** [comment]
@chce - Is this what you purposing in #11953 as well? Would you like to make a PR for it?

**Comment by chce** [comment]
Yes, pretty much. Just thought I'd make s separate issue as it seems like more of a feature than a bug fix to add this argument. I can try, yes.

**Comment by xugao** [comment]
@chce - do you still need this change since [your other change](https://github.com/OfficeDev/office-ui-fabric-react/pull/11969) is merged? We are actively trying to avoid unneeded changes in `DetailsList`, since it's already a very over-loaded component.

**Comment by chce** [comment]
I don't need it for my work, but it's a piece of functionality from List that would be useful to have in DetailsList too.
