### ISSUE TITLE
Dropdown label "for" attribute

### ISSUE THREAD

**Issue by scriby** [OfficeDev/office-ui-fabric-react#1197]
Is there a reason the label created by the Dropdown component doesn't have a "for" attribute?

I am trying to figure out how the label is going to get linked to the dropdown and am not seeing anything.

I tested it out in a few screenreaders and it looks like aria-label is saving the day and the label isn't really doing anything from an accessibility perspective.

I also have a curiosity why label is required for Dropdown but not other input controls.

**Comment by rickyp-ms** [comment]
Possibly fixed by https://github.com/OfficeDev/office-ui-fabric-react/issues/1194?

**Comment by fantua** [comment]
Take a look at my answer [here](https://github.com/OfficeDev/office-ui-fabric-react/pull/1189#discussion_r104775226), I hope I answered to your question.

**Comment by scriby** [comment]
Thanks, it looks like #1196 does include the for attribute on the label.

I'd also like to push on whether the label needs to be required. The reason I don't think it should be required (like TextField) is because it allows the consumer to provide their own label so they can position it as they please.

Even though consumers have no way to get the id of the rendered input field to set the "for" attribute, they can do an implicit association like this:

```
<label>
  Name
  <TextField ... />
</label>
```

That gives a little more flexibility in how the consumer sets up the label.

**Comment by scriby** [comment]
I'll go ahead and close this for now, I don't think it's that big of a deal.
