### ISSUE TITLE
NPM install fails - wrong dependency version

### ISSUE THREAD

**Issue by havri** [OfficeDev/office-ui-fabric-react#11971]
I am unable to install office-ui-fabric-react into blank project:

`npm install --save office-ui-fabric-react`

results into

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @uifabric/utilities@^7.12.1
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of '@uifabric/styling'
npm ERR! notarget
```

**Comment by havri** [comment]
While utilities is still 7.12.0: https://www.npmjs.com/package/@uifabric/utilities

**Comment by mirkori** [comment]
We get this too since ~1hour

**Comment by kevin7** [comment]
I'm having the same issue.

**Comment by jleck** [comment]
We could fix it by holding back a couple packages:

```ts
"@uifabric/react-hooks": "7.0.9",
 "@uifabric/styling": "7.10.8",
```

Looks like one of the packages hasn't been published.

**Comment by jafman** [comment]
Any solution yet, please?

**Comment by Gregghis** [comment]
The workaround suggested by jleck works for me.

**Comment by jafman** [comment]
> The workaround suggested by jleck works for me.

So how did you apply the fix?
Thanks

**Comment by Gregghis** [comment]
I updated the package.json file adding the dependecies
    "@uifabric/styling": "7.10.8",
    "@uifabric/react-hooks": "7.0.9",
in the dependencies section. Then I run npm i

**Comment by jafman** [comment]
> I updated the package.json file adding the dependecies
> "@uifabric/styling": "7.10.8",
> "@uifabric/react-hooks": "7.0.9",
> in the dependencies section. Then I run npm i

Thanks Man.
Worked like charm.

**Comment by jafman** [comment]
> We could fix it by holding back a couple packages:
> 
> ```ts
> "@uifabric/react-hooks": "7.0.9",
>  "@uifabric/styling": "7.10.8",
> ```
> 
> Looks like one of the packages hasn't been published.

Thanks

**Comment by cemkestek** [comment]
Same problem for us too.

**Comment by havri** [comment]
@uifabric/utilities 7.12.1 available, which fixed the bug -> closing.

**Comment by xugao** [comment]
this was bumped by PR #11974. this might be related to the NPM publishing outage last week
