### ISSUE TITLE
useReducedRowRenderer doesn't work for default row rendering on DetailsList

### ISSUE THREAD

**Issue by chce** [OfficeDev/office-ui-fabric-react#11979]
### Environment Information

- **Package version(s)**: 7.93.0
- **Browser and OS versions**: Chrome 80 / Win 10

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/chce/pen/MWweJLw
Run a performance profiler that can profile React events, and notice the many [update] renders
#### Actual behavior:

It looks like the function "styles" in the props of DetailsRow is causing a comparison miss when shouldComponentUpdate calls shallowCompare. This causes every currently rendered row to re-render when f.ex. scrolling down the list.

#### Expected behavior:

shouldComponentUpdate should return false when no props have changed, especially when I'm scrolling.

A workaround, if you don't need to use styles, is to provide an onRenderRow-function, that returns the following:
<DetailsRow {...props} styles={undefined} />
### Priorities and help requested:

Are you willing to submit a PR to fix? Yes, but I have no idea where to start, as this is caused by the styled-HOC and therefore probably not that simple to fix

Requested priority: Normal

Products/sites affected: DetailsList, ShimmeredDetailsList, DetailsRow

**Comment by xugao** [comment]
Looks like the re-render happens due to `columns` is not shallow equal on component update
doesn't seem to be an easy fix

**Comment by chce** [comment]
Could we resolve the styles functions and use the results of the functions in the comparison?
