### ISSUE TITLE
Dropdown ellipsis, overflow and adaptive width

### ISSUE THREAD

**Issue by dinoilic** [OfficeDev/office-ui-fabric-react#11996]
### Environment Information

- **Package version(s)**: 7.90.1
- **Browser and OS versions**:
  - Windows 10 Version 10.0.19041 Build 19041
  - Edge Version 81.0.416.3 (Official build) dev (64-bit)

### Describe the issue:

Hi! I'm having several issues/questions regarding the `Dropdown` component:

1. When I have a long string displayed in the `Dropdown` component, the string is not cut-off properly as seen in [this](https://codepen.io/dinoilic/pen/gOpMJgP) codepen. It works fine for Multi-select however Basic uncontrolled example does not work since the string goes out of bounds. I saw in the [implementation](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx#L657) of the `Dropdown` component that you use the `CommandButton` which in turn renders a `BaseButton` with a `<span>` as seen [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx#L296). If you open the inspect element in the codepen I provided you can see that the `<span>` does not respect the parent's width. Adding a `width: inherit;` to the `<span>` created by the `BaseButton` fixes the ellipsis problem. However, that element is inaccessible from the code that uses just the `Dropdown` component.
2. Similar issue comes when you use the customized dropdown which can be seen in [this](https://codepen.io/dinoilic/pen/MWwedvV) codepen. One issue is that the documentation does not reflect the code example since the `Dropdown` component is taking the `onRenderOption` method and there are no references to it in the documentation. The other issue can be seen if you open the `Dropdown` for the "Custom example". A really long text overflows to the next line and you can see the issues on hover as well. This happens because the custom `onRenderOption` doesn't render a `<span>` with the correct classes as seen [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx#L706). Instead a custom renderer needs to provide its own way of handling ellipsis (eg. on the `<div>` that's being rendered). This works but only if the bullet point 1. is satisfied (width: inherit on the BaseButton's `<span>`)
3. My third question is a feature question/feature request: I've seen several issues like #2228, #3263, #1521 and others mentioning problems with width. In case I want to create a `Dropdown` component which has a callout and an input fully stretched to its contents (widths are not necessarily equal), is that possible?. I know that the width is currently linked (input and callout are the same width) and you can change the width of the callout by using the `dropdownWidth` prop which only allows you to specify pixel values and not percentages? If there's a way of doing this, while keeping the custom `onRenderOption` please let me know.

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? **Yes**

Requested priority: **Normal**

Products/sites affected: **Microsoft Search**

**Comment by aneeshack4** [comment]
Hi @dinoilic thank you for reaching out to us! #1 and #2 are dupes of #11248 - the status on that is we're going to review work for this in the backlog as it's going to be a change that's quite involved. #3 is feature request which I'll speak with the component owner about once they're back in the office.

**Comment by dinoilic** [comment]
Hey! Thanks for the response. Any approximate ETA on #1 and #2? Any workarounds that can be done currently?

#3 is not just about percentages (I think it actually wouldn't work for my case) but rather about having the option for the callout to take the width of its widest child. Here's an example:

![ExampleDropdown](https://user-images.githubusercontent.com/4788533/74914070-11771880-53c2-11ea-872c-e8d9b2dd0f0f.png)

As you can see both the input and the callout has adaptive width. Is that possible currently? I know the width of the callout and the input are linked and if I change the input to take the width of the contents then the callout does the same.

**Comment by dinoilic** [comment]
@aneeshack4 any suggestions on my previous comment before closing this? Thanks!
