### ISSUE TITLE
PeoplePicker: Force resolve the input

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#1199]
1. When user types something like: contoso@microsoft.com without resolving it (Choose one item from suggestion list or Press TAB). 
or
2. When user types multiple person in one line (Might copy from other places) like: contoso@microsoft.com; contoso1@microsoft.com

Would it be desired feature for PeoplePicker to provide a way to force resolve all the unresolved people in the input?

![image](https://cloud.githubusercontent.com/assets/7711735/23651842/c73af3d0-0361-11e7-9e07-0e5a323dc1fd.png)
In the above case, when user click "Add profile" button, we can help user automatically resolve the persons. If they're all resolved, complete the action, show some errors if some person can't be auto-resolved.

**Comment by joschect** [comment]
I think that this is possible to do, but it would require a lot of specing out. Like would the picker make several calls to onresolvesuggestions for each "person" in the input? Or would it pass one string through to and it's up to the datasource to provide an array of items that should be added to the selected list.

**Comment by kristoferbrown** [comment]
@ipip2005, the PeoplePicker now supports force-resolving single items. The onValidateInput prop can be use to control whether or not the entered text is resolvable, resolvable with an error, or not resolvable.
