### ISSUE TITLE
[Keyboard Navigation - AML Data Drift - Datasets Monitors] "Start Date" calendar control is automatically getting expanded when the focus lands on it

### ISSUE THREAD

**Issue by kattepalli** [OfficeDev/office-ui-fabric-react#11994]
**User Experience:** 
Keyboard users will face the difficulty in navigating the controls if the controls expand automatically without using any key.

**Repro Steps:**
1. Open Url: https://master.ml.azure.com/data/monitor?wsid=/subscriptions/35f16a99-532a-4a47-9e93-00305f6c40f2/resourcegroups/data4ml-demo-rg/workspaces/data4ml-demo&tid=72f988bf-86f1-41af-91ab-2d7cd011db47 and login via a valid credential.
2. Dataset Monitors screen will open.​
3. Navigate to an already created Drift and select it.​
4. Drift overview screen will open.​
5 Navigate to Backfill button and select it​
6. Verify the issue.
 
**Actual Result:​**
"Start Date" calendar control is automatically getting expanded when the focus lands on it.

**Expected Result:​**
"Start Date" calendar control should not expand automatically when the keyboard focus lands on the calendar control. It should expand when user will activate it through any key.

![MAS3 2 1_Calender pop up is expanding automatically](https://user-images.githubusercontent.com/30458420/74822096-99114880-532a-11ea-8dfc-b1ac1f325942.png)

**Comment by kattepalli** [comment]
Issue can be seen in examples page:
https://developer.microsoft.com/en-us/fabric#/controls/web/datepicker

**Comment by khmakoto** [comment]
Hi @kattepalli, thanks for filing this issue!! I think this was a design decision made early in the process of creating the `DatePicker` since this behavior only occurs when text input is not allowed. @lorejoh12 what do you think about this issue?

**Comment by lorejoh12** [comment]
This was the existing behavior of the control when I inherited it. We left it in case there were consumers relying on it, but there have been numerous bugs opened against it. There is an optional prop that consumers can use to disable the behavior, `disableAutoFocus`, which is the usual suggestion.

That said, we might consider flipping the behavior- have the default behavior be to NOT open by default, but allow consumers to pass a prop that turns on the old behavior. This would be a breaking  change, so we wouldn't be able to do this until the next major version update I think.

**Comment by khmakoto** [comment]
Thanks @lorejoh12!

@kattepalli, does this help with your use case? As John commented, we wouldn't be able to change behavior until a major version bump.
