### ISSUE TITLE
Tooltip in office fabric doesn't respond when Esc is clicked

### ISSUE THREAD

**Issue by lavanya-kuda** [OfficeDev/office-ui-fabric-react#11991]
### Environment Information

- **Package version(s)**: "office-ui-fabric-react": "6.201.0"
- **Browser and OS versions**: Edge and Chrome

### Describe the issue:
Tooltip in office fabric doesn't respond when Esc keyboard key is clicked.

#### Actual behavior:

On Esc keyboard key click tooltip doesn't go away.

#### Expected behavior:

Expected that tooltip should go away when Esc is clicked

**Comment by khmakoto** [comment]
Hi @lavanya-kuda, thanks for filing this issue! I can confirm that this is indeed happening with Fabric 6. I'll make a PR as soon as I can to fix it!
