### ISSUE TITLE
Variant name change breaks code

### ISSUE THREAD

**Issue by corby** [OfficeDev/office-ui-fabric-react#11997]
You changed the button variant tags from all lower case to camel  case.
example:
xlarge -> xLarge

this was a code breaking change but you did not increase the major version number so we could catch it in the package.json file.
Please remember to increase the major version number on code breaking changes.

We will be abandoning fabric until development of the package is more stable.

**Comment by khmakoto** [comment]
Hi @corby, can you tell me what you mean by the button variant tags? I don't think button makes use of any tags such as that but if you could help me a little bit here maybe I could take a look at what happened. We definitely don't want to break anyone on a non-major version change so I'm very surprised to read that we broke you somehow.
