### ISSUE TITLE
Combobox - Enable filter options when typing

### ISSUE THREAD

**Issue by honb** [OfficeDev/office-ui-fabric-react#12011]
I expected that a property to show/open options when:

- User focus on combobox
- Update options (filtering or searching) when user types

I tried to use onPendingValueChanged to update options (filtering options by value) for the component but it does not work as expected.

**Comment by aneeshack4** [comment]
@honb Thanks for reaching out to us! #1 - when user focuses on the combobox, once they press ENTER, the options dropdown will open - this is by design #2 - duplicate, we're aware of this feature request and is being tracked in #6030
