### ISSUE TITLE
[DetailsList] Prop "checkboxCellClassName" does not apply on header cell

### ISSUE THREAD

**Issue by lukasbash** [OfficeDev/office-ui-fabric-react#12014]
### Environment Information

- **Package version(s)**: 6.211.4
- **Browser and OS versions**: macOS Catalina 10.15.3

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/lukasbash/pen/wvazrwa

#### Actual behavior:
When using the prop `checkboxCellClassName`, the class will only apply on actual rows and not the relative header cell.

#### Expected behavior:
The class should apply on the relative header cell as well.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

**Comment by aneeshack4** [comment]
@lukasbash This is by design I believe because we have `headerClassName` for the column cells within each header: https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.types.ts#L502
