### ISSUE TITLE
errorMessage for Checkbox and PeoplePicker

### ISSUE THREAD

**Issue by lafe** [OfficeDev/office-ui-fabric-react#12017]
#### Describe the feature that you would like added

Not all controls currently have an `errorMessage` property. It would be great to have the `errorMessage` property on all input controls so that we have an uniform experience and do not have to "roll our own" on some controls.

#### What component or utility would this be added to

- Checkbox
- NormalPeoplePicker

#### Have you discussed this feature with our team, and if so, who

No

#### Additional context/screenshots

Is related to #7636 and #6527

**Comment by aneeshack4** [comment]
Hi @lafe Thanks for reaching out to us. We have a MessageBar component: https://developer.microsoft.com/en-us/fabric#/controls/web/messagebar. Can you use that?

**Comment by lafe** [comment]
Sorry for the delayed response (I had a quick vacation). I know (and use) the MessageBar component, but it is not the ideal solution for displaying validation results. Those results should be displayed right next to the controls of a form itself.
