### ISSUE TITLE
Narrator announces unnecessary groups when we move to the column headers "User, Quota .." and the cell values

### ISSUE THREAD

**Issue by khansahab15** [OfficeDev/office-ui-fabric-react#12015]
Browser Versions: Microsoft Edge 44.18362.387.0,
Chrome Version 77.0.3865.120 (Official Build) (64-bit)
Windows Version: Windows10​​​
NVDA 2019.2

Repro Steps:​​
1. Hit the URL
2. Select application as "Sales hub" from the list of application.​
3. From the change area which is present in the bottom select "Sales"​
4. Navigate to "Site Map" and then Navigate to "Performance" and select "Forecast" ​
5. Forecast Grid Screen will appears.
7. Start narrator and navigate to the grid.

Actual:​
Narrator announces unnecessary groups when we move to the column headers "User, Quota .." and the cell values and it took extra caps + arrow navigation as well.

Same issue is observed with NVDA(Its announce blank).

Expected:​​
Narrator should not announce unnecessary groups and it should not take extra caps + arrow keys.

User Impact:​
Screen reader user will not be able to know the proper information about the control.

[12015_Bug.zip](https://github.com/OfficeDev/office-ui-fabric-react/files/4229692/12015_Bug.zip)

**Comment by aneeshack4** [comment]
@khansahab15 Can you provide an isolated repo of this? (isolated to the Fabric component itself not some site its used in)
