### ISSUE TITLE
PeoplePicker: When no people resolved, `home` key in input doesn't work

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#1201]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: any

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

#### Describe the issue:

When people picker has resolved some persons, use Home key will move focus to the first resolved person.
However, when people picker has NO resolved person, use Home key should work in the input box to move cursor to the start position of input.

Repro steps:
1. In a fresh people picker, type something "abcdefg"
2. Press "Home" key.

#### Actual behavior:

Cursor doesn't move.

#### Expected behavior:

Cursor move to position before character 'a'

**Comment by joschect** [comment]
This looks like it's an issue with focuszone not respecting input elements. I think that the focuszone should only try to control the focus of an input element based on arrow keys to help preserve stuff like home key presses. @dzearing How do you think that focus zone should handle cases like this.

**Comment by ipip2005** [comment]
#1803

**Comment by ipip2005** [comment]
Validated and fixed
