### ISSUE TITLE
[CheckBox] onContextMenu isn't support by CheckBox

### ISSUE THREAD

**Issue by stuartlong** [OfficeDev/office-ui-fabric-react#12021]
### Environment Information

- **Package version(s)**: 7

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/stuartlong/pen/VwLKOjg?editors=1111

#### Actual behavior:
`onContextMenu` attribute is not supported by checkbox.

#### Expected behavior:
`onContextMenu` should be support when present on a `Checkbox` component

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by xugao** [comment]
@stuartlong - thanks for reporting! 

I see couple issues here:
1. `export interface ICheckboxProps extends React.ButtonHTMLAttributes<HTMLElement | HTMLInputElement>` is wrong and should not extends button attributes. the correct way to pass the event handler should be via `inputProps`

2. Even if `onContextMenu` is passed from `inputProps`, it still doesn't work for some reason. `onClick` works though

**Comment by aneeshack4** [comment]
I don't see why a CheckBox needs a right click menu... there would be maybe 1 option in it at most (toggle to opposite state of current) and maybe 1 other like disable but that's a bit strange to let users disable a checkbox... @stuartlong we're discussing how our types should be fixed to not support all HTML attributes like onContextMenu - we'll update you

**Comment by stuartlong** [comment]
I see, so it's really a typing issue and not actually a supported feature.

 @aneeshack4 , we have some scenarios for right-clicking a check box where we expose extra functionality related to what the chexkbox represents through the context menu. However, with the checkbox not supporting it, we have to add an extra DOM node wrapper around the checkbox so that we can attach the context menu event handler.

**Comment by aneeshack4** [comment]
@stuartlong Yes the context menu on right click isn't a scenario this Checkbox will support. Fixing the types to have them be more restricted is a separate issue so I will close this.
