### ISSUE TITLE
Panel Body CSS Shift IE11

### ISSUE THREAD

**Issue by nkanaki** [OfficeDev/office-ui-fabric-react#12020]
### Environment Information

- **Package version(s)**: at least 7.86.0 and forward
- **Browser and OS versions**: IE11

### Please provide a reproduction of the bug in a codepen:
https://developer.microsoft.com/en-us/fabric#/controls/web/panel

Open any of the first two panels in IE11, you can see they are rendered completely unusable.
![image](https://user-images.githubusercontent.com/45470616/74988627-1f915d00-53f3-11ea-8eb0-a4037015bcb1.png)

![image](https://user-images.githubusercontent.com/45470616/74988645-320b9680-53f3-11ea-9653-46d91cab3931.png)

#### Actual behavior:

Inner content shifted outside of the panel
Unclear if this is the root cause, but by switching the css property in the class ms-Panel-header, margin-right: auto to margin-right:0px seems to at least display the content

#### Expected behavior:

All content displayed appropriately

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: Blocking / High

Products/sites affected: All Panel using sites, including SharePoint/MSIT

**Comment by phkuo** [comment]
The styles on the `ms-Panel-header` element don't make sense to me. This is using flexbox layout, it shouldn't have margins that are along the main axis. It should be using flex-grow on the header or space-between on the parent. Why does the parent justify by flex-end?

**Comment by xugao** [comment]
is this a recent regression or never worked?

**Comment by aneeshack4** [comment]
@xugao @phkuo @nkanaki @maxwellred Looks like a regression from #11391

**Comment by aneeshack4** [comment]
Working on finding a fix - Storybook doesn't work on IE11 so currently waiting on a full build of the `fabric-website-resources` package so I can get the old site to load locally and test out changes to Panel. @phkuo what do you mean by the main axis? are you saying we shouldn't be setting margin at all in the header styles? Also, flex-end only seems to be used under navigation, not the header... so perhaps that's inheriting...

**Comment by phkuo** [comment]
There's justify-content:flex-end on the parent of the header, which is the flexed nav element, which tells you how to position its children. It doesn't make sense to have margin left/right on a horizontally-laid out flexbox element. `justify-content` should be used for main axis alignment, while `align-items` is used for cross axis alignment.
