### ISSUE TITLE
link is not getting focus border

### ISSUE THREAD

**Issue by Shreya35** [OfficeDev/office-ui-fabric-react#12033]
### Environment Information

- **Package version(s)**: (7.95.0)
- **Browser and OS versions**: (all browsers)

### Describe the issue:

when we click tab on the link, it is not getting the focus border, if it's children is wrapped in div

### Please provide a reproduction of the issue in a codepen:

repo:- https://codesandbox.io/s/quirky-allen-v70me

#### Actual behavior:

the link is not getting focus border

#### Expected behavior:
the link should get focus border

**Comment by khmakoto** [comment]
Hi @Shreya35, thanks for filing this issue! This does seem like a strange bug, we'll investigate it further.

**Comment by Shreya35** [comment]
Hi @khmakoto what is the ETA to get this fixed.

**Comment by aneeshack4** [comment]
I don't think the Link component was meant to be used with `div` inside... @Shreya35 why do you want to use the div inside the Link? If you take it out, the focus works fine.

**Comment by Shreya35** [comment]
Hie, when the link is big ,the focus is getting multiple lines so for that we require div so that whole link gets focussed.
![image](https://user-images.githubusercontent.com/54526983/75511353-018bb400-5a14-11ea-8684-c88c60cbdfda.png)

**Comment by aneeshack4** [comment]
@Shreya35 As far as I understand about standards for the Link component across the web, it's not a common scenario to have text spanning multiple lines all pointing to one link. Usually if a link is embedded in text, it's limited to a few words - correct me if I'm wrong or missing something @khmakoto

**Comment by khmakoto** [comment]
@aneeshack4 you can definitely do this with the regular link as can be seen in [this codepen](https://codepen.io/pen?template=rEjZeV), so I don't think there's a reason why we shouldn't do it.

**Comment by aneeshack4** [comment]
Ah I see @khmakoto I think this might actually be due to the boxShadow not being applied: https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Link/Link.styles.ts#L37
I don't see it when I inspect and observe what happens during tabbing to focus... there don't seem to be any border styles actually: 
![image](https://user-images.githubusercontent.com/4161791/75595692-40d0f980-5a42-11ea-868d-98b60b424f21.png)
