### ISSUE TITLE
ChoiceGroup only able to select selectedKey or defaultSelectedKey on first paint

### ISSUE THREAD

**Issue by claudiordgz** [OfficeDev/office-ui-fabric-react#12032]
### Environment Information

- **Package version(s)**: "^7.84.1"
- **Browser and OS versions**: Chrome 80.0.3987.116 on Windows

#### Actual behavior:

* Here is a stackblitz of the issue: https://stackblitz.com/edit/office-ui-fabric-choice-group-wont-switch

#### Expected behavior:

* Choice changes when switching the `selectedKey` or `defaultSelected` prop so that I can switch it via `location` state.

### Priorities and help requested:

The current alternative is to not paint it until verifying the location state is available.

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: Statutory Reporting -> General Ledger -> Subledger Application (not in production yet).

**Comment by aneeshack4** [comment]
@Claudiazhaoya what are the exact repro steps? I don't see the problem...

**Comment by Claudiazhaoya** [comment]
I think I was tagged by accident... It should be @claudiordgz

**Comment by claudiordgz** [comment]
Hi @aneeshack4 

On the stackblitz demo you'll notice that when clicking the buttons switches the choice but the `ChoiceGroup` stays the same.

To Repro:

1. Use a `ChoiceGroup`
2. add a `selectedKey` as a variable that depends on a prop
3. change `selectedKey` via prop

**Comment by claudiordgz** [comment]
Hi @aneeshack4 

Tried out without persisting the state and it works, so I'll make sure I wire it differently
