### ISSUE TITLE
The BasePicker.props.onResolveSuggestions is not enough to represent full state.

### ISSUE THREAD

**Issue by lijunle** [OfficeDev/office-ui-fabric-react#1203]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Depends on the discussion result.)

Requested priority: High

#### Describe the issue:

Currently, the BasePicker has a prop named [`onResolveSuggestions`](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/pickers/BasePicker.Props.ts#L21) to generate the suggestion list candidates based on user input and selected persons. It is returning value is `T[] | PromiseLike<T[]>`.

When the returned value is a `Promise`, it shows [`loadingText`](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/pickers/BasePicker.Props.ts#L86) until the promise is resolved and get the result.

For the result, if it is empty array, it shows the [`noResultsFoundText`](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/pickers/BasePicker.Props.ts#L66), otherwise, it starts the logic to [`onRenderSuggestionsItem`](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/pickers/BasePicker.Props.ts#L16).

However, there is a case that, we don't want to resolve the result **until user input enough characters**. If we want to do so, the returning model `T[] | PromiseLike<T[]>` is not enough.

#### Workaround

Currently, we are setting the `noResultsFoundText` value dynamically in `onResolveSuggestions` method. It is bad because the `onResolveSuggestions` method is doing something not related to resolve suggestions.

#### Proposal

My suggestion is to extend the typing to `false | T[] | PromiseLike<T[]>`. The explicit `false` returning value indicate the resolver is not doing anything and hope the user to input more characters.

**Comment by joschect** [comment]
I think that idea makes a lot of sense, although maybe it might make more sense to allow it to return undefined? That would serve as a very similar check and not require another typing. To be more clear about your proposal, if false/undefined was returned the basepicker would take no other action.
