### ISSUE TITLE
"searchErrorText" property doesn't work on Pickers

### ISSUE THREAD

**Issue by modestfake** [OfficeDev/office-ui-fabric-react#12037]
I've found `searchErrorText` in [docs](https://developer.microsoft.com/en-us/fabric#/controls/web/pickers#ISuggestionsProps). I've tried to pass it like this:
```jsx
<TagPicker
  // ...
  onResolveSuggestions={fn}
  pickerSuggestionsProps={{
    // ...
    searchErrorText: 'Error text'
  }}
/>
```

It didn't show up and I couldn't figure out when it should be shown. I suppose it should appear when `onResolveSuggestions` handler will throw an error. I've tried to search for `searchErrorText` in the codebase but I couldn't find where it's rendered. It only appears in docs and types, [here are search results](https://github.com/OfficeDev/office-ui-fabric-react/search?q=searchErrorText&unscoped_q=searchErrorText).

Is this property deprecated? If not, how should I use it?

**Package version(s)**: `office-ui-fabric-react@7.96.0`

**Comment by khmakoto** [comment]
Hi @modestfake, I think there is no current use for that prop but I don't believe it is deprecated. I think the prop is there so that a user could take advantage of it when rendering the suggestions.

@joschect can you confirm what I said is correct or what's the story here if not?

**Comment by joschect** [comment]
@khmakoto As far as I can tell you're correct. It looks like it was partially removed or is no longer used. I believe that `noResultsFoundText` could be used for the same purpose.

**Comment by khmakoto** [comment]
@joschect should we go ahead and deprecate the prop?

**Comment by joschect** [comment]
@khmakoto Yep! That seems like a good plan.
