### ISSUE TITLE
Unnecessary comparison in shallowCompare

### ISSUE THREAD

**Issue by chce** [OfficeDev/office-ui-fabric-react#12030]
### Environment Information

- **Package version(s)**: 7.95.0
- **Browser and OS versions**: Chrome 80 / Win 10

### Please provide a reproduction of the bug in a codepen:

Go to packages/utilities/src/object.ts to see the function

Here's a comparison of the function with a proposed faster function
https://jsperf.com/checkproperties-vs-custom/1

#### Actual behavior:

shallowCompare performs too many unnecessary equality checks by calling checkProperties twice, thereby comparing the values of the same fields twice.

#### Expected behavior:

That we only check b[propName] === a[propName] once per shallowCompare

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) Yes, but you can just use the code from the jsperf snippet 

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) DetailsRow, ComboBox, Coachmark, CalloutContent

**Comment by khmakoto** [comment]
Hi @chce, thanks for filing this issue! I think this is definitely something we could and maybe should do.

@dzearing any objections to doing this? I think it makes sense.

**Comment by chce** [comment]
I'm thinking this could also be tagged with Performance. Should I go ahead with a PR?

**Comment by aneeshack4** [comment]
@chce Yes feel free to, thank you!
