### ISSUE TITLE
Dropdown - Add property for setting the number of items to be rendered

### ISSUE THREAD

**Issue by lszomoru** [OfficeDev/office-ui-fabric-react#1204]
It would be great if there would be a property to specify the number of items that should be rendered. Ex: my dropdown list has 10 items, but I would like only 5 of them to be rendered in the view port rather than all 10 of them.

**Comment by MLoughry** [comment]
Are you suggesting it only *render* X number of items, or that the Callout only be large enough to *show* X items without scrolling? If the former, what would be the mechanism for showing the other items?

**Comment by lszomoru** [comment]
I am asking for a setting that controls have many of the items are rendered. You can actually do this today using CSS to set the height of the HTML element containing the items but it would be great if there would be a setting for it. Let me know if you have any further questions or concerns. Thanks! 

Ladislau

**Comment by mikewheaton** [comment]
This should be fixed by #1756. You can now pass `calloutProps` to the dropdown to control things like the height of the callout.
