### ISSUE TITLE
_dismissOnOuterClick should be registered to PointerUp mouse event 

### ISSUE THREAD

**Issue by marrissa-hellesen** [OfficeDev/office-ui-fabric-react#12041]
#### Actual behavior:

In Edge and IE 11, when clicking outside the fabric Panel component, the first click event the handler receives is a PointerUp. _dismissOnOuterClick is not registered to that event, so the panel doesn't light dismiss. The second click outside the panel is a mousedown and that correctly light dismisses the panel. Chrome and Chromium edge have mousedown as the first event and work as expected.

#### Expected behavior:

First click outside of the panel light dismisses the fabric Panel in IE and Edge.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes
Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) Word/PPT/XLO

**Comment by aneeshack4** [comment]
@marrissa-hellesen Thanks for reaching out to us! Can you provide screenshots that show the differences in this behavior across browsers? I don't see what you mean right now when I try to repro this - both on Chrome and Edge, clicking outside doesn't dismiss.

**Comment by aneeshack4** [comment]
@marrissa-hellesen Actually, I see that the "Light dismiss" works on Edge, Chrome, and IE11... so this is not reproing
