### ISSUE TITLE
Question: should column name be announced by Narrator?

### ISSUE THREAD

**Issue by YingXue** [OfficeDev/office-ui-fabric-react#12056]
### Describe the issue:

When using Narrotor to go through the tables, Narrotor only annouce: <value>, column x of y, but the column name won't be annouced. Is it expected behavior?
I used Narrotor on the Office fabric's offical page: https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/basic

#### Actual behavior:

Narrotor only annouce: <value>, column x of y

#### Expected behavior:

Should column name also be annouced?

**Comment by xugao** [comment]
@YingXue - it is announced if you are in scan mode and navigating through each cell in a row

**Comment by YingXue** [comment]
Hi @xugao 
Thanks for the quick reply.
I've turned on scan mode, and the Narrtor is announcing 'column x of y, the value of the item selected', but it doesn't announce the name of the column.

![image](https://user-images.githubusercontent.com/5489222/75315227-07687600-5817-11ea-8401-2a51ae32de95.png)
For example, the narrator is announcing 'column 2 of three, item0' as above

**Comment by xugao** [comment]
@YingXue - did you actually navigate (by pressing down key) onto each cell? see #11931, note there is a bug in New Edge so this only works in Old Edge currently

**Comment by YingXue** [comment]
@xugao 
I see. Thanks for confirming it doesn't work in Chromium. We are building an electron app which is Chromium based.
I will let our testers know it is a Edge/Chromium bug.

**Comment by xugao** [comment]
@YingXue - sounds good. just to point out  here is the bug tracking on Edge side: https://microsoft.visualstudio.com/Edge/_workitems/edit/25257517
