### ISSUE TITLE
Question: Nav items showing controlType as Hyperlink

### ISSUE THREAD

**Issue by YingXue** [OfficeDev/office-ui-fabric-react#12055]
Using Nav control, the items are showing as 'HyperLink' type when running 'Accessibility Insights for windows'. 

#### Actual behavior:

Using Nav control, the items are showing as 'HyperLink' type when running 'Accessibility Insights for windows'. 

#### Expected behavior:

Should the Control Type be 'Tab item' instead of 'Hyperlink' or not?

### Documentation describing expected behavior
![image](https://user-images.githubusercontent.com/5489222/75285400-656f6c00-57cb-11ea-942f-22df8a101628.png)

**Comment by xugao** [comment]
@YingXue - if you look up the tree. the structure goes to be: list -> list item -> HyperLink
![image](https://user-images.githubusercontent.com/1207059/75292463-17f9fb80-57d9-11ea-8359-b81718742fe3.png)

**Comment by YingXue** [comment]
Thank for the clarification. Please feel free to close the bug.
