### ISSUE TITLE
Panel component breaks react-dropzone

### ISSUE THREAD

**Issue by dstaley** [OfficeDev/office-ui-fabric-react#12059]
### Environment Information

- **Package version(s)**: office-ui-fabric-react v7.97.0, react-dropzone v10.2.1

### Please provide a reproduction of the bug in a codepen:

[Minimal reproduction on StackBlitz](https://stackblitz.com/edit/react-vwbtdr)

#### Actual behavior:

Dragging a file over the text "Drag 'n' drop some files here, or click to select files" fails to change the `isDragActive` property. Dropping the files doesn't trigger the `onDrop` callback.

#### Expected behavior:

Dragging a file over the text "Drag 'n' drop some files here, or click to select files" changes the text to "Drop the files here ...". Dropping the files results in a log in the console.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes, with guidance on what's the root cause.

Requested priority: Normal

### Additional Info

Originally I suspected the incompatibility came from the fact that `Panel` is rendered in a React Portal, but I confirmed that `react-dropzone` works correctly when embedded in a Portal. I'm not sure what could be causing the dropzone to not receive its events correctly, but if someone identified the cause I could probably work out a solution!

**Comment by xugao** [comment]
@dstaley - if this is Fabric, my first guess was panel content (MyDropzone) was being re-mounted. but it doesn't seem to be the case. I think this issue is related to `react-dropzone` instead of Fabric. can you file issue there?

**Comment by dstaley** [comment]
@xugao I don't necessarily think this is an issue with `react-dropzone`. I think this is more an issue with `Panel` disrupting the normal behavior of drag and drop events. I've also tested this with `react-file-drop` and experience a slightly similar issue where dropping files doesn't trigger a drop handler.

**Comment by xugao** [comment]
@dstaley - let me dig more :)

**Comment by xugao** [comment]
@dstaley - could you help build a simpler repro (without dep. on react-drapzone) to demo `Panel` is interrupting the eventing, something like [this](https://codepen.io/xugao/pen/MWwpeoQ). I looked into the code a bit, nothing jumps out.

**Comment by dstaley** [comment]
@xugao sure! I'll take a look at what's going on in `react-dropzone` and see if I can pull out a minimal reproduction based on the event's they're listening for.

**Comment by dstaley** [comment]
@xugao I managed to create a minimal reproduction! It looks like it's something to do with React's synthetic event system. Essentially, inside the panel, the event's propagation is stopped, but not when it's outside of the panel. Furthermore inside the panel the event's propagation isn't stopped _until_ you try accessing the event after a Promise.

Hopefully this example is clear enough to work on finding a solution! Please let me know if there's anything else I can do to help.

[Reproduction](https://codepen.io/dstaley/pen/eYNvXQj?editors=1111)

**Comment by xugao** [comment]
@dstaley - uh actually what you need to do here is to pass `layerProps={{ eventBubblingEnabled: true }}` to panel, `Layer` is by default stopping event propagation. 
Here is [codepen](https://codepen.io/xugao/pen/rNVmmRy) to demo

**Comment by dstaley** [comment]
@xugao I just wanted to confirm that adding the layerProps fixes the issue!

That being said, it still seems to me that this is a bug. I went through the documentation for Panel and there's no mention of weird event behavior. However, in the documentation for Layer, I did find this:

> Events that propgate from within the content will not go through the Layer element as well.

This would lead me to believe that the events _within_ the panel should still work correctly without manually enabling `eventBubblingEnabled`. Could you confirm that the behavior described in the original issue is expected? If so, I'd be happy to open a new issue to hopefully improve the documentation to help others who find themselves in a similar situation!

**Comment by xugao** [comment]
@dstaley - i believe there was a legacy reason why things are this way.
if you look at the description for `eventBubblingEnabled`:
>When enabled, Layer allows events to bubble up from Layer content. Traditionally Layer has not had this behavior. This prop preserves backwards compatibility by default while allowing users to opt in to the new event bubbling functionality.

if we change this default behavior (which i think we should), that would be a breaking change and we cannot do that now
