### ISSUE TITLE
A controlled Virtualized Combobox with filtering capability.

### ISSUE THREAD

**Issue by sushmithaGayam** [OfficeDev/office-ui-fabric-react#12052]
#### Describe the feature that you would like added

I have a scenario where im using a Controlled single-select VirtualizedComboBox. So if a user types something combox should filter the values which start with what is typed in the conmbobox. 

#### What component or utility would this be added to

This should be added to combobox
#### Have you discussed this feature with our team, and if so, who

yes i have, we are currently creating our own component which does this, but if the combobox can do it, it would be great.

**Comment by xugao** [comment]
@sushmithaGayam - thanks for the suggestion. we have this issue tracked in #6030 (also related to #9682). Note - this is something we likely won't get to very soon.

**Comment by aneeshack4** [comment]
Closing this since it's being tracked in another issue.
