### ISSUE TITLE
The text of static control  will be read twice in my dialog(mfc)

### ISSUE THREAD

**Issue by Zuixi** [OfficeDev/office-ui-fabric-react#12066]
I am having weird issue, I used MFC to create a simple dialog , which just contains some static controls.Here is my code :

> IDD_MFCNARRATOR_DIALOG DIALOGEX  0, 0, 360, 200
STYLE DS_SHELLFONT | WS_POPUP | WS_VISIBLE | WS_CAPTION
 | WS_THICKFRAME
EXSTYLE WS_EX_APPWINDOW
CAPTION ""
FONT 9, "MS Shell Dlg"
BEGIN
    LTEXT           "Hello,Narrator!",
    IDC_STATIC, 6, 6, 266, 9
    LTEXT           "this sentence will be read twice, but i don't know reason",
    IDC_STATIC, 6, 26, 266, 9
    CONTROL         "", 998, "Static", SS_ETCHEDHORZ, 6, 47, 266, 1
    DEFPUSHBUTTON   "OK",IDOK,209,179,50,14
    PUSHBUTTON      "Cancel",IDCANCEL,263,179,50,14
END

# Expected behavior:
The text of static controls should be read one.
# Actual behavior:
In scan mode on narrator, the second sentence("this sentence will be read twice, but i don't know reason") will be read twice.

So is there any clever trick to this problem? Does anyone know how this can be solved?

**Comment by xugao** [comment]
@Zuixi - pls provide a codepen which has a repro.

**Comment by TravisSpomer** [comment]
Hi @Zuixi—Visual C++ problems should probably go to the [C++ Developer Community](https://developercommunity.visualstudio.com/spaces/62/). This project builds web UI controls for React.
