### ISSUE TITLE
Shimmer background does not work when shimmerElement is undefined

### ISSUE THREAD

**Issue by jesspagan** [OfficeDev/office-ui-fabric-react#12061]
### Environment Information

- **Package version(s)**: 7

### Codepen

https://codepen.io/jesspagan/pen/VwLpjKO

#### Actual behavior:

When shimmerElements prop is undefined, shimmerColor background does not get apply.

#### Expected behavior:

shimmerColor background should get apply regardless if shimmerElements is undefined or not.

Problem encountered while upgrating to Fabric 7 :
Current work around: define a shimmerElement as line type and width use 

![image](https://user-images.githubusercontent.com/3449831/75294355-00247680-57dd-11ea-8f97-904038115111.png)

**Comment by xugao** [comment]
@jesspagan - our [documentation](https://developer.microsoft.com/en-us/fabric#/controls/web/shimmer) explained the use case in `Shimmer styles customizations` section.

for your case, i think you should use `styles` prop like [this example](https://codepen.io/xugao/pen/LYVWZOo)

**Comment by jesspagan** [comment]
I did try using styles, but that does not fix the black corners I am getting when using the shimmer component with a custom theme.

**Comment by xugao** [comment]
@jesspagan , could you share me your code (which has the black corners) in a code pen?
similar to [mine](https://codepen.io/xugao/pen/LYVWZOo)

**Comment by jesspagan** [comment]
@xugao here you will see white corners as the default color from Fabric
https://codepen.io/jesspagan/pen/BaNWzMR

**Comment by xugao** [comment]
@jesspagan - I see the issue now. will look into a fix

**Comment by jesspagan** [comment]
@xugao thank you :)

FYI: I found the reason why we see the corners black and not white as the codepen, I think Fabric is actually reading the theme.palette.black instead of theme.palette.white as the documentation said. The reason why is because we where able to change the corners to white by change our theme:

![image](https://user-images.githubusercontent.com/3449831/75298596-c5740b80-57e7-11ea-977f-dfe6d2a0e45f.png)

**Comment by xugao** [comment]
We render these svg in the corner of each shimmer line and they are not properly styled. @Vitalius1 - any idea why we have these svg the first place?

@jesspagan - You can consider hide these corners as [a work around](https://codepen.io/xugao/pen/poJeNzz) while i follow up more

**Comment by xugao** [comment]
@jesspagan -
`semanticColors.bodyBackground` is the variable in theme to control the color of the corners:
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Shimmer/ShimmerLine/ShimmerLine.styles.ts#L23

If you cannot change your theme in your case, you can consider [this fix](https://codepen.io/xugao/pen/KKpWgYj) using `styles` prop

**Comment by jesspagan** [comment]
@xugao -
Thank you for taking the time to look at this 😃! We may be able to change the theme for a generic scenarios, but we also use the shimmer component in other places where the background color will not necessary match with `semanticColors.bodyBackground`.

In that case, we may need to implement a way were we can customize all corners through a prop to match background (similar of what you guys have in the code base), although will be a great feature to have from the component Fabric. 😄

**Comment by xugao** [comment]
@jesspagan - in this case, a more proper solution is to add a new theme slot such as `shimmerCornerBackgroundColor` in `ISemanticColor`. However I'd like to push back on such change since we have a way to work around your issue using `styles` prop. Reason is mentioned in our website [here](https://developer.microsoft.com/en-us/fabric#/controls/web/references/isemanticcolors):
>We plan to move completely to semantic slots and replace all usage of Fabric palette slots. We've been actively making some of these changes but still have a ways to go. At present, we're only adding slots if absolutely necessary because we are trying to avoid bloating the already sizeable offering. We're also working on a better solution for design tokens overall in our next iteration. We'll provide an update on this site when that's ready. Thank you for your patience.

If this is acceptable for you. pls kindly close the issue.

**Comment by jesspagan** [comment]
@xugao thanks for the documentation link, this is good to know specially since we use theming as well.
