### ISSUE TITLE
Add an optional styles prop for Calendar component

### ISSUE THREAD

**Issue by jesspagan** [OfficeDev/office-ui-fabric-react#12064]
#### Describe the feature that you would like added

An optional styles property for the Calendar component.

#### What component or utility would this be added to

Calendar component

#### Have you discussed this feature with our team, and if so, who

Haven't

**Comment by lorejoh12** [comment]
Check out @uifabric/date-time package. It has a refactored Calendar component that does, in fact, support the styles property.
