### ISSUE TITLE
Screen Reader Announce all the selected element of multiselect DropDown in scan mode

### ISSUE THREAD

**Issue by Sheepu-dev** [OfficeDev/office-ui-fabric-react#12072]
### Environment Information
- **Browser and OS versions**: Edge/Window10

### Describe the issue:
Screen Reader Announce all the selected element of multi-select DropDown in scan mode

### Please provide a reproduction of the issue in a codepen:

Codepen path:https://codepen.io/sheepu/pen/bGdqaBL

#### Actual behavior:
In scan mode, SR Announced all the selected elements of multi-select DropDown. If 100 of the value is selected in DropDown then it announces all the 100 values.

#### Expected behavior:
There should be a flag to stop announcing of SR for multi-select DropDown it should announce the first selected element, instead of all the elements.

**Comment by aneeshack4** [comment]
@Sheepu-dev Dropdown isn't meant to be used with large amounts of items. We don't offer a Virtualized Dropdown which is probably what you're looking for - you could get by with ComboBox as another option. But yeah this scenario isn't supported.

**Comment by Sheepu-dev** [comment]
@aneeshack4 same behavior repro in combo box. SR announce all the selected items.

**Comment by aneeshack4** [comment]
@Sheepu-dev this is by design - I've spoken with the component owner of both. Neither combobox nor dropdown is meant to be used with large lists of items. For those, use DetailsList because it has virtualization built in.
