### ISSUE TITLE
Dropdown labels are too close to the control

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#1207]
### Bug Report
Chrome and Edge

#### Priorities and help requested (not applicable if asking question):
Are you willing to submit a PR to fix? (Yes)

Requested priority: (Normal) 

#### Describe the issue:
The labels are too close to the top of the dropdown control

#### Expected behavior:
The labels should be to the design spec. Match the text field labels and we should be good. That is 8px from the bottom of the label, to the top of the dropdown.

**Comment by micahgodbolt** [comment]
Duplicate. #1196 should address this by using the proper <Label> component instead of a generic <label> tag.
