### ISSUE TITLE
Focus indicator is not clearly visible on the all the sides for the interactive links in the page.

### ISSUE THREAD

**Issue by SyedRehmanRazvi** [OfficeDev/office-ui-fabric-react#12079]
User Experience:
Low vision users are facing difficulty as focus indicator is not clearly visible on all the sides for the interactive links in the page.

Pre-Requisite:
Change the page to high contrast white/black mode.

Repro Steps:
Step 1: Open https://fabricweb.z5.web.core.windows.net/oufr/7.97.1/#/examples/link   in edge browser
Step 2: Navigate to the links in the page and verify whether focus indicator is visible on the all the sides in the page.

Actual:
Focus indicator is not clearly visible on the all the sides for the interactive links in the page.

Expected.
Focus indicator should clearly visible on the all the sides for the interactive links in the page.

![image](https://user-images.githubusercontent.com/53210862/75353353-42c77b00-58d1-11ea-9f84-690c7efd61b2.png)

**Comment by aneeshack4** [comment]
Hi @SyedRehmanRazvi, this doesn't repro for me on the latest master (https://developer.microsoft.com/en-us/fabric#/controls/web/link)
Edge - high contrast black:
![image](https://user-images.githubusercontent.com/4161791/75399888-63340d00-58b2-11ea-978b-121bab5175ae.png)
Edge - high contrast white:
![image](https://user-images.githubusercontent.com/4161791/75399912-72b35600-58b2-11ea-88b3-834d0a4ec791.png)
