### ISSUE TITLE
Cannot set id on Slider using buttonProps.id

### ISSUE THREAD

**Issue by kattepalli** [OfficeDev/office-ui-fabric-react#12080]
**Environment Information**

    Browser and OS versions: Edge + Narrator.

**Repro steps**

1. Navigate to slider control using tab key when Narrator is on.(To turn on Narrator use Ctrl + Win + Enter)
2. Verify narrator is reading the label places for slider or not.

**Code pin will be provided in comment section.**

**Actual:**
Narrator is reading only as "slider at 20 min 0 max 20" if the slider is at 20%.

**Expected:** 
Narrator should also read label information.
Ex: if the label placed is threshold then narrator should read as "Threshold slider at 20 min 0 max 20".

**Comment by evileagle** [comment]
What we want to do is add customized label with tooltip. To pass the accessibility test, we need to pass the Slider's id to customized label. But Slider doesn't have id in props, so the label can't associate with Slider. Here is our code:
`
          <Field
            label={LocStrings.Monitor.Config.Monitor.Threadhold.Label}
            tooltip={LocStrings.Monitor.Config.Monitor.Threadhold.Title}
          >
            <Slider
              min={0}
              max={100}
              step={5}
              defaultValue={this.props.monitor.threshold}
              showValue={true}
              onChange={this.onChangeThreshold}
              // tslint:disable-next-line: react-this-binding-issue jsx-no-lambda
              valueFormat={(value: number) => `${value}%`}
            />
          </Field>
`

What we want is just like TextField:
`
          <Field
            label={LocStrings.Monitor.Config.Monitor.Emails.Label}
            tooltip={LocStrings.Monitor.Config.Monitor.Emails.Title}
          >
            <TextField
              id={`${idPrefix}emails`}
              onChange={this.onEmailChange}
              placeholder="abc@example.com;bcd@example.com"
              value={this.props.monitor.emailAddresses}
              errorMessage={errorMessages.emailAddresses}
            />
          </Field>
`
