### ISSUE TITLE
When Nav link is clicked, the item is not selected. How to change the Selection ?

### ISSUE THREAD

**Issue by vikramdadwal** [OfficeDev/office-ui-fabric-react#12092]
For _how-to_ questions and other non-bugs, please use StackOverflow instead of Github issues. You can tag your questions with [office-ui-fabric](https://stackoverflow.com/questions/tagged/office-ui-fabric).

If you are a Microsoft employee you can also join the Microsoft UI Fabric teams channel.

#office-ui-fabric

**Comment by aneeshack4** [comment]
@vikramdadwal As it says in the issue you made, if you have a how to question/non-bugs, please use SO or the Microsoft UI Fabric channel on Teams if you're a Microsoft employee.
