### ISSUE TITLE
DetailsList pop up alerting on touch not double click on some touch devices

### ISSUE THREAD

**Issue by Leif-Frederiksen** [OfficeDev/office-ui-fabric-react#12094]
### Environment Information

- Chrome emulating iOS device on desktop
- Actual Chrome on iOS device

#### Actual behavior:

Go to https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/basic
Double click a line in the list.
Notice how an alert box pop up with info on the line clicked.
Now do the same thing on an iOS or Android device or in Chrome emulating some touch device.
Now pop up is coming when clicked/touching a line.

#### Expected behavior:

The expectation is that it is possible to trigger the onItemInvoked event on a tocuh based device.

### Priorities and help requested:

Are you willing to submit a PR to fix? (No)

Requested priority: (High)

**Comment by xugao** [comment]
seem to be related to #8858
However i can only repro in emulator. I tried with on my iOS (v13.3.1) phone  + Chrome & Safari, and I do not repro.

@Leif-Frederiksen - can you be more specific on what iOS (actual) device you tested on?

**Comment by aneeshack4** [comment]
@Leif-Frederiksen yeah I'm not reproing this either on Chrome or Safari on iOS - are you sure you're on the latest version? I only get the alert if I double tap not if I'm simply touching the line. It doesn't repro on Surface Book's touch screen either.
![image](https://user-images.githubusercontent.com/4161791/75478745-53203a00-5953-11ea-9f0e-07bb727a4086.png)

**Comment by Leif-Frederiksen** [comment]
This happens on an iPad with iOS v 13.3.1.
Same problem with Safari as well as with Chrome v 76.0.3809.123.
Instead of showing the alert, the paged is zoomed a little bit when double tapping the screen. On next double tap it zooms out again.

**Comment by xugao** [comment]
in the code, it is relaying on `onDoubleClick` event listener, which looks like it is not well supported - https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/ondblclick

**Comment by xugao** [comment]
@Leif-Frederiksen - i am going to mark this one as duplicate. let's follow up more in #8858

**Comment by aneeshack4** [comment]
Closing as this is a dupe
