### ISSUE TITLE
BasePicker: onBlur() is triggered when the user selects one of the items in the drop-down menu (intermittent issue)

### ISSUE THREAD

**Issue by biyua** [OfficeDev/office-ui-fabric-react#12110]
### Environment Information

- **Package version(s)**: office-ui-fabric-react: "7.90.0"
- **Browser and OS versions**: Microsoft Edge: 44.18362.449.0

#### Actual behavior:

BasePicker has two functions called onSuggestionClick() and onBlur(). In the working case, onSuggestionClick() will be invoked when we select one of the suggestions, but in a non-working vase, onBlur() will be called.

This only happens to one user so far, but the user can constantly repro this issue. I have only reproed the issue once, that's how I found the above behavior.

#### Expected behavior:

onSuggestionClick() should always be invoked in this case.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes.

Requested priority: Blocked

Products/sites affected: SharePoint Online: Microsoft region

**Comment by aneeshack4** [comment]
@biyua Thanks for reaching out to us! Can you please provide a codepen that has a consistent repro? It's hard for us to investigate this without that.
