### ISSUE TITLE
ITag interface

### ISSUE THREAD

**Issue by ben33** [OfficeDev/office-ui-fabric-react#12118]
Hi,

We are using your components and we try to abstract some components to use it more efficiently.
We've reach a problem, the ITag has the key type only as string and we want to have the key has a number as well (without transforming it and the ISelectableOption has the key as a string or a number)
Can you standardize it ?

Thanks guys and great job

**Comment by aneeshack4** [comment]
Hi @ben33, can you please provide more information? Which code are you referring to here? It'd help us answer your request if you fill out the template we've provided.

**Comment by ben33** [comment]
Sorry sorry.

1. the **office-ui-fabric-react** package, **TagPicker** component and more precisely the **ITag** interface in TagPicker.types.ts
2. ITag interface should (imho and as the ISelectableOption interface) be :

```
...
/**TagPicker.types.ts**/
export interface ITag {
  /** Name of the item. */
  name: string;

  /** Unique key for the item. */
  key: string | number; //<== Here the change
}
...
```

3. I can't have a tag with a number as key :

```
/**Example.tsx**/
<TagPicker
  options={[
    {
      key: 2,//error
      name: 'Two'
    }
  ]}
  {...otherProps}
/>
...
```
4. Confirmation... I think XD

Let me know if need more information.

**Comment by aneeshack4** [comment]
@ben33 I see thanks for the details. I'm down to make this change since it seems harmless enough/not breaking/wouldn't add overhead but before I do, have you considered doing something like this? https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/pickers/examples/TagPicker.Basic.Example.tsx#L27 to get numbers for the key?

**Comment by ben33** [comment]
I could but I would want a more straightforward way to use my API without the need to transform the type/ find key from text (yeah, I'm a bit lazy :p)
Thanks for your replies !
