### ISSUE TITLE
Show a point in Line chart component when there is only one data

### ISSUE THREAD

**Issue by kenibote** [OfficeDev/office-ui-fabric-react#12136]
#### Describe the feature that you would like added

We are internal users of this Package in MSFT. My alias is niwa. 
We are hoping someone can add a new feature or fix this bug in Line Chart component.

In @uifabric/charting LineChart component, when we have only one data pass to the component, the component shown nothing on UX just an empty chart. We are expecting the component to show up a point indicated this data on the line chart.

#### What component or utility would this be added to

Pls see the attached picture.
<img width="594" alt="WeChat Screenshot_20200302143714" src="https://user-images.githubusercontent.com/16734602/75651629-e929cc80-5c93-11ea-8536-084da27aaf90.png">

#### Have you discussed this feature with our team, and if so, who

No.

**Comment by Raghurk** [comment]
I will get this fixed.

**Comment by shivasai09** [comment]
hello @kenibote , could you please share us the data that you are passing to the chart, so that i could repro at my side and do the needful

**Comment by kenibote** [comment]
@shivasai09  Sure. For example, `<LineChart data={data} tickFormat={'%m%d'} tickValues={values}/>`
Here, the `data=[
    {
        data:[{x:'2020-02-02', y:90}],
        legend:'Your Point',
        color: '#0078D4'
    }
]`

**Comment by Raghurk** [comment]
This is resolved. Please take the latest charting package

**Comment by kenibote** [comment]
@Raghurk  @shivasai09 @xugao Truly thanks~
