### ISSUE TITLE
Grouped List: Possible to add custom elements to group headers ?

### ISSUE THREAD

**Issue by raj-crec** [OfficeDev/office-ui-fabric-react#12147]
Hi,

Say I want to add a drop-down/labels/input elements to group-headers in a grouped list. Is it possible to add the same as of today ?

Regards,
Raj Abhishek

**Comment by xugao** [comment]
@raj-crec - yes you can render your own header using `groupProps.onRenderHeader`

See "GroupedList example with custom header and footer" section in https://developer.microsoft.com/en-us/fabric#/controls/web/groupedlist

Pls kindly close the issue if this answers your question

**Comment by raj-crec** [comment]
Hi Thanks Xugao ! I replaced the <groupHeader> element with my own div. I was able to create custom-elements in group header, but the tree structure was lost. I need the tree structure too, so I added the new divs inside <GroupHeader></GroupHeader>. However, I got the tree structure back without my divs being honored.

**Comment by raj-crec** [comment]
Correction: 
**Hi Thanks Xugao ! I replaced the 'groupheader' element with my own div. I was able to create custom-elements in group header, but the tree structure was lost. I need the tree structure too, so I added the new divs inside  <GroupHeader></GroupHeader>. However, I got the tree structure back without my divs being honored.**

**Comment by raj-crec** [comment]
*added the new divs inside 'groupheader' elements.

**Comment by xugao** [comment]
@raj-crec - here is one potential option: in your onRenderHeader implementation, you can render `GroupHeader` component, similar to our internal implementation:
https://github.com/OfficeDev/office-ui-fabric-react/blob/8fa2d72cc6e242d0157aee8fda380042076ea2ff/packages/office-ui-fabric-react/src/components/GroupedList/GroupedListSection.tsx#L284

When using `GroupHeader`, you can see what props to pass to achieve your goal:
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/GroupedList/GroupHeader.base.tsx

I am guessing `onRenderTitle` is the one you need to customize

**Comment by raj-crec** [comment]
Hi @xugao - Thanks much for your support. I was working on something else. Tomorrow I'll check the feasibility of what you said, and get back to you. Please don't close this issue.

**Comment by raj-crec** [comment]
Hi @xugao , I tried using 'onRenderTitle', and it worked, except for the fact that styles are not getting honored. The same 'divs' with appropriate style ( flex-container ), are being rendered properly in 'onRenderCell', but not here in 'onRenderTitle'. Is it true we can't use styles in onRenderTitle ?

**Comment by raj-crec** [comment]
Possible for you to look into my code? I have attached it here. I have copied the basic example available on this website, and made changes to it to suit me. Once you run it, you will see what I want.
[GroupedList - Copy.txt](https://github.com/OfficeDev/office-ui-fabric-react/files/4310244/GroupedList.-.Copy.txt)

**Comment by raj-crec** [comment]
Basically, I am trying to have groupheaders as the same width as that of the rows below. Not sure how to define the width of the same.

**Comment by xugao** [comment]
@raj-crec - once you implement your own `_onRenderTitle`, styling is completely in your hand to control. you can apply any style you want on it. but be aware the style we apply on rest of the parts/ancestor nodes of the title, that might cascade onto the title and affect your styling. however, you should be able to style the title however you wanted

**Comment by raj-crec** [comment]
Thanks @xugao for all the help ! I'll see what I can do.
