### ISSUE TITLE
Question: How to print items not yet materialized in List component?

### ISSUE THREAD

**Issue by chryw** [OfficeDev/office-ui-fabric-react#1215]
### Question

- __Package version(s)__: (1.14.1)
- __Browser and OS versions__: (Edge, Windows 10)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Low) 

#### Describe the issue:

I'm using the List component to render large amount of items with images. The lazyload works great in browser. However my users may want to print the entire list (or at least more than what's materialized). Is there anyway in the List component to retain already rendered items?

**Comment by WesselKuipers** [comment]
I'd like to know about this as well.
Would it be possible to allow disabling the lazy load functionality?
