### ISSUE TITLE
In multi-select drop down screen readers are not announcing the selected option and total number of options available.

### ISSUE THREAD

**Issue by SainathBommisetty** [OfficeDev/office-ui-fabric-react#12151]
### Environment Information

Browser and OS versions: Chrome, Edge

### Describe the issue:

In multi-select drop down screen readers are not announcing the selected option and total number of options available. 

In EDGE selected option and number of options available is not reading by Narrator screen reader.
In Chrome, number of options is not reading by NVDA screen reader.

### Steps:

On focus of multi select drop down.

### Please provide a reproduction of the issue in a codepen:

https://developer.microsoft.com/en-us/fabric#/controls/web/dropdown

### Actual behavior:

Screen readers are not announcing the selected option and number of options available in multi select drop down.

### Expected behavior:

Screen readers should read the selected option and number of options available, same as single-select drop down.

**Comment by aneeshack4** [comment]
@SainathBommisetty thanks for reaching out to us. This doesn't repro for me - as you can see in the Narrator Buddy output, it's reading the selected options and the number of options available (7) and the position in the set (like 3 of 7, etc...)
![image](https://user-images.githubusercontent.com/4161791/75717176-774a8680-5c85-11ea-91ce-abb65ee40050.png)

**Comment by vasanthkumar258** [comment]
**Issue**:
In Chrome - NVDA, I could not navigate between the options using arrow keys in Multiselect Dropdown

**Screenshot**:
![image](https://user-images.githubusercontent.com/12809041/77192982-79289c80-6b03-11ea-9198-04ada8176c3a.png)

**Can be reproduced in** Multi-select uncontrolled example https://developer.microsoft.com/en-us/fabric#/controls/web/dropdown
