### ISSUE TITLE
Fela: inline-style-prefixer should be upgraded/downgraded

### ISSUE THREAD

**Issue by layershifter** [OfficeDev/office-ui-fabric-react#12162]
### Environment Information

- **Package version(s)**: `@fluentui/react@0.45.0`
- **Browser and OS versions**: any

### Please provide a reproduction of the bug in a codepen:

1. Try to open `Layout` guide: https://fluentsite.z22.web.core.windows.net/layout

#### Actual behavior:

Blank screen 💣 

#### Expected behavior:

Working page.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes
Requested priority: High

**Comment by layershifter** [comment]
A CodeSandbox with repro: https://codesandbox.io/s/elated-chatterjee-kro33

**Comment by jurokapsiar** [comment]
Tracking Reference: 6473
