### ISSUE TITLE
Calendar / CalendarDayGrid: Infinite Loop if navigatedDate is invalid

### ISSUE THREAD

**Issue by alex3683** [OfficeDev/office-ui-fabric-react#12179]
### Environment Information

- **Package version(s)**: 
  - @uifabric/date-time: 7.8.32
  - office-ui-fabric-react: 7.98.2
- **Browser and OS versions**: Google Chrome 80, Windows 10 Enterprise

### Please provide a reproduction of the bug in a codepen:

Screenshot when paused in the Chrome Debugger during the infinite loop:
![grafik](https://user-images.githubusercontent.com/768322/75865992-aaffea80-5e04-11ea-9081-9776aaf8f455.png)

In case you really need the codepen from me, I can provide one. But I guess the issue is rather obvious in there ;-)

#### Actual behavior:

In case the `navigatedDate` passed to the `calendarDayProps` is an invalid Date, the `_getWeeks` method of the `CalendarDayGrid` runs into an infinite loop, since the break condition of the while is never met.

#### Expected behavior:

Either:
The component throws an exception early before running into the loop.
Or:
A default date is used as `navigatedDate`.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: None

**Comment by aneeshack4** [comment]
Thanks for reporting this @alex3683 - will work on sending out a PR soon.
