### ISSUE TITLE
ContextualMenu may generate invalid section header element ID

### ISSUE THREAD

**Issue by ermercer** [OfficeDev/office-ui-fabric-react#12172]
### Environment Information

- **Package version(s)**: `office-ui-fabric-react` v7.79.0
- **Browser and OS versions**: Edge Anaheim / Windows 10

### Describe the issue:

When using Fabric `ContextualMenu` component, the ID is dynamically generated for the section header based on the `title` prop.

https://github.com/OfficeDev/office-ui-fabric-react/blob/9c9f9fc892cfded04327e76e46ae2d4530058ed9/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.base.tsx#L574

This can result in an invalid ID since the `title` value is a user-facing string that can contain invalid characters for an ID (such as whitespace, e.g. "Switch views"), resulting in accessibility issues for the menu items contained in the section.

### Please provide a reproduction of the issue in a codepen:

https://codepen.io/ermercer/pen/oNXePgQ

#### Actual behavior:

The section header menu item may have an invalid ID, which means the `aria-labelledby` attribute on the parent element with `role="group"` will not work and the menu items within the section will not have the section header announced by Narrator.

#### Expected behavior:

Fabric should generate a correct ID, either by cleansing the title attribute when generating the dynamic ID or else changing the logic to use the `getId` util.

### Documentation describing expected behavior

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id

**Comment by aneeshack4** [comment]
Hi @ermercer, thanks for reporting this. I think it's reasonable to add some checks on the title string. I'll see if I can get a PR out for this soon.

**Comment by ermercer** [comment]
Thanks @aneeshack4! That would be great so that my team can resolve an A11Y bug for our app 😊

**Comment by ermercer** [comment]
@aneeshack4 can we also tag this issue as `Area: Accessibility` given that invalid IDs prevent Narrator from correctly describing the items within the section due to not being able to identify the associated section header (which has `role="group"`)?
