### ISSUE TITLE
Button doesn't respect props when have rootProps

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#1217]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: any

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Blocking

#### Describe the issue:

In BaseButton https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx#L44
`this.props.rootProps || this.props,`
When Button uses rootProps, the props like onClick passed via react props will not take affect.

onClick doesn't work for the button below:

             <Button
                icon={ 'Cancel' }
                buttonType={ ButtonType.icon }
                onClick={ this._onCardClick }
                rootProps={
                  { 'aria-hidden': true } as React.HTMLProps<HTMLButtonElement>
                }
              />

This can probably cause a lot of regression when consumer's button is using rootProps.

#### Actual behavior:

The onClick doesn't work

#### Expected behavior:

The onClick passed should be working.

**Comment by ipip2005** [comment]
Add a codepen here:
http://codepen.io/ipip2005/pen/RpoOgo

Repro steps
1. Click the icon, nothing happens.
2. remove "rootProps" in IconButton.
3. Click the icon again, an alert dialog pops up.

Expected: In step 1, also pops up alert.
Actual: Nothing happens in step 1.

**Comment by lijunle** [comment]
This is a critical and blocking bug. Could we handle it ASAP? /cc @dzearing

**Comment by dzearing** [comment]
RootProps has been deprecated for a really lobg time. I can take a look but you should not use deprecated props.
