### ISSUE TITLE
Is it by design that ResizeGroupBase would unmount then remount new instances of elements? 

### ISSUE THREAD

**Issue by chandde** [OfficeDev/office-ui-fabric-react#12189]
### Environment Information

- **Package version(s)**: "office-ui-fabric-react": "^7.90.1"
- **Browser and OS versions**: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
here's my codepen repro link https://codepen.io/dengydongn/pen/yLNzYxO
1. a sample Content component for a button
1.1 Content has componentWillUnmount to print some log
2. a resizeGroup component which wrapps Content
3. render the resize group 

4. open chrome debugger, resize the window, you'll see Content::componentWillUnmount is called on every pixel reduction

This is very bad for performance, that destruct and construct all items in the group on every single pixel resize. Can someone confirm if this is on purpose, or something could be improved? thanks!

#### Actual behavior:

the component gets destructed and rebuilt on every single pixel width change

#### Expected behavior:
resizegroup would do some debounce so it won't happen on every pixel change? or use the same item instance and build a mechanic to notify the items (through callback)? 

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No) unfortunately I'm not sure what would be a good fix here

Requested priority: (Blocking, High, Normal, Low)
Normal

Products/sites affected: (if applicable)
ads.microsoft.com

**Comment by aneeshack4** [comment]
Hi @chandde, thanks for reaching out to us! Yes I believe this is by design and is explained here: https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ResizeGroup/ResizeGroup.base.tsx#L339.
