### ISSUE TITLE
`ContextualMenuSplitButton` doesn't invoke the `onRenderItem` callback.

### ISSUE THREAD

**Issue by dotnetjunky** [OfficeDev/office-ui-fabric-react#12196]
### Environment Information

- **Package version(s)**: 7.0.0
- **Browser and OS versions**: Edge (Chromium) on Windows

### Please provide a reproduction of the bug in a codepen:

I'm using the `<ContextualMenu>` control in my app. One of the `ContextualMenuItem` is a split button. I set the `onRenderIcon` prop to a custom function of my own. 

#### Actual behavior:
My custom function is not invoked. 

#### Expected behavior:

My custom function should be invoked so that I can render icon for the split button using my own logic. 

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by aneeshack4** [comment]
Hi @dotnetjunky, thanks for reaching out to us (Luan!) How are you using this ContextualMenu-SplitButton? If you could provide me a Codepen that illustrates this, I will have more context into your scenario. Here's an example of how `onRenderIcon` can be used with ContextualMenu: https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ContextualMenu/examples/ContextualMenu.Icon.Example.tsx#L27

**Comment by dotnetjunky** [comment]
Annesha, 

I modified your example to add the `split` property to `true`. Here's the  CodePen  https://codepen.io/dotnetjunky/pen/vYOeWVa?editors=0010

**Comment by aneeshack4** [comment]
Hi @dotnetjunky thanks for starting this codepen! I'm trying to debug to figure out if onRenderIcon is invoked or not but it looks like there's a bug with useConst so that might actually be the problem, not onRenderIcon...
![image](https://user-images.githubusercontent.com/4161791/76051921-28c11480-5f31-11ea-9c2b-db6a74240ab4.png)

**Comment by dotnetjunky** [comment]
@aneeshack4 Sorry, the codepen that I shared is not meant to be functional. I created the Pen from the default template. The CSS and HTML code from the Pen are invalid. 

Instead, you should copy the JS code in the Pen and paste it into the example that you shared https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ContextualMenu/examples/ContextualMenu.Icon.Example.tsx#L27
