### ISSUE TITLE
On hover so many times Callout wont appear or it is immediately dismissed.

### ISSUE THREAD

**Issue by v-jashr** [OfficeDev/office-ui-fabric-react#12198]
**Browser and OS versions**: Chrome , Edge on Windows x64

**Bug Description**
Current situation 
when we are hover / focus on icon some time callout appears but most of the time it won't.
it is immediately dismissed.

Expected
on hover / on focus  of  icon callout should always appear / visible to user . 

can you please provide a workaround.

**Comment by aneeshack4** [comment]
@v-jashr Please provide a codepen with repro steps showing how to repro this bug on the Fabric component.
