### ISSUE TITLE
JS Map, IE11, Unable to get property 'has' of undefined or null reference

### ISSUE THREAD

**Issue by jleck** [OfficeDev/office-ui-fabric-react#12205]
### Environment Information

- **Package version(s)**: office-ui-fabric-react, 7.73.0
- **Browser and OS versions**: WIndows 10, IE 11.592.18362.0

#### Actual behavior:

Throws error in classNamesFunction.js (_traverseEdge) as the `current` map is set to undefined. I get this as soon as a launch a dialog.

Using polyfill.io to provide map support in IE11. This worked up until a couple weeks ago, then stopped. I've tried pegging all the sub-dependencies back (e.g. @uifabric/utilities), to no avail.

#### Expected behavior:

Should always receive a valid map.

### Priorities and help requested:

Are you willing to submit a PR to fix? Yes, if I found the solution.

Requested priority: High

**Comment by jleck** [comment]
Update:

I can make it work by changing where it calls _traverseEdge to:

```js
_traverseEdge(current || new Map()...
```

**Comment by jleck** [comment]
Okay, I've narrowed this down to the polyfill provided by polyfill.io. Looks like this has a bug which stops it setting a blank string. I can make it work using @babel/polyfill instead.

Haven't digged into it enough to determine whether it should be able to set blank.

**Comment by aneeshack4** [comment]
@jleck sounds like you found a fix in babel/polyfill so is it ok if we go ahead and close this? Or are you still thinking there needs to be a case for "" added to the `_normalizeValue` function?

**Comment by jleck** [comment]
@aneeshack4 I think close. I haven’t checked, but I could imagine A key of `false` also breaking it (I assume the polyfill isn’t doing a strict type check). And there’s nothing in the map specs to see these values shouldn’t work.
