### ISSUE TITLE
Expand only one row in DetailsList - customitemrows

### ISSUE THREAD

**Issue by agarawalankur** [OfficeDev/office-ui-fabric-react#12235]
#### Describe the feature that you would like added

I am looking for a feature to expand only one row at a time

#### What component or utility would this be added to

I followed below issue and it worked but the problem here is that it is expanding multiple rows based on the selection.

https://github.com/OfficeDev/office-ui-fabric-react/issues/11598

Codepen - https://codepen.io/jdh-msft/pen/PowORgm?editors=0010

#### Have you discussed this feature with our team, and if so, who

N/A

#### Additional context/screenshots

![image](https://user-images.githubusercontent.com/23447511/76157767-f37e1780-6126-11ea-98d1-fa0693364d87.png)

**Comment by aneeshack4** [comment]
@agarawalankur You can use the Grouped DetailsList and have only one item in each group (row) https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/grouped

**Comment by agarawalankur** [comment]
@aneeshack4 thank you for the response, i doubt that this will solve my purpose as i already have grouping in my actual DetailsList.

![image](https://user-images.githubusercontent.com/23447511/76279698-f99c0180-62a8-11ea-9b67-f575c89d5518.png)

**Comment by aneeshack4** [comment]
@agarawalankur I don't understand - you can just each row in a separate group still...
