### ISSUE TITLE
FocusTrapCallout - How to Hide Callout on Click out side 

### ISSUE THREAD

**Issue by MdAmeerMind** [OfficeDev/office-ui-fabric-react#12240]
Actual Behavior: 
FocusTrapCallout is not hiding when user click out side to callout area. User needs to click Esc button

Expected Behavior:
Callout should hide when user clicks an out side as other element on page showing the mouse hover effect they have so it is confusing to the end user. 

Repro: 
[https://developer.microsoft.com/en-us/fabric#/controls/web/callout](https://developer.microsoft.com/en-us/fabric#/controls/web/callout)

Repro Step:
1) Open Above URL
2) Click on FocusTrapCallout button
3) Callout is open, now move mouse on other element on page like button or links on left side and hover on it. All component shows hover effect which pretend that we can click on it but click won't work on that.

**Comment by aneeshack4** [comment]
Hi @MdAmeerMind this is by design - you're able to mouse over but no action is allowed as focus is trapped inside the callout.

**Comment by MdAmeerMind** [comment]
Hi @aneeshack4 , Thank you for your feedback.
