### ISSUE TITLE
how set callout focus programmatically by reference?

### ISSUE THREAD

**Issue by yalian-icom** [OfficeDev/office-ui-fabric-react#12243]
For _how-to_ questions and other non-bugs, please use StackOverflow instead of Github issues. You can tag your questions with [office-ui-fabric](https://stackoverflow.com/questions/tagged/office-ui-fabric).

If you are a Microsoft employee you can also join the Microsoft UI Fabric teams channel.

**Comment by aneeshack4** [comment]
@yalian-icom as it says in the description, please use SO or the internal Teams channel for questions like this. Without more info, I can only guess the `target` prop or the `setInitialFocus` prop on Callout can be used for your purpose https://developer.microsoft.com/en-us/fabric#/controls/web/callout
