### ISSUE TITLE
Type 'IDropdownStyles' does not satisfy the constraint 'IStyleSet<IDropdownStyles>'

### ISSUE THREAD

**Issue by ahmedlhanafy** [OfficeDev/office-ui-fabric-react#12247]
After upgrading to the latest version of office fabric, I started getting this error: 
```
Type 'IDropdownStyles' does not satisfy the constraint 'IStyleSet<IDropdownStyles>'.
  Type 'IDropdownStyles' is not assignable to type '{ subComponentStyles?: { panel: IStyleFunctionOrObject<any, IStyleSet<any>>; label: IStyleFunctionOrObject<any, IStyleSet<any>>; multiSelectItem: IStyleFunctionOrObject<...>; }; }'.
    The types of 'subComponentStyles.panel' are incompatible between these types.
      Type 'IStyleFunctionOrObject<IPanelStyleProps, IPanelStyles>' is not assignable to type 'IStyleFunctionOrObject<any, IStyleSet<any>>'.
        Type 'Partial<IPanelStyles>' is not assignable to type 'IStyleFunctionOrObject<any, IStyleSet<any>>'.
          Type 'Partial<IPanelStyles>' has no properties in common with type 'Partial<IStyleSet<any>>'.ts(2344)
```
whenever I do 
```
const dropdownStyles = classNamesFunction<IDropdownStyleProps, IDropdownStyles>()({})
```
which used to work before I upgraded.

In fact, going to `Dropdown.types.d.ts` from office-fabric shows the same error on line:118. 

### Environment Information

- **Package version(s)**: 7.100.0
- **Browser and OS versions**: Chrome and windows
- **TS Version**: 3.7.4 and 3.8.3

**Comment by aneeshack4** [comment]
@ahmedlhanafy thanks for reaching out to us. I don't repro this - as you can see in this codepen I'm able to use the line 

> const dropdownStyles = classNamesFunction<IDropdownStyleProps, IDropdownStyles>()({})

https://codepen.io/aneeshack4/pen/vYOpqYL

**Comment by ahmedlhanafy** [comment]
@aneeshack4 The problem can't be reproduced in codepen because codepen doesn't show typescript error AFAIK. Here is an attached picture of the error in `Dropdown.types.d.ts`
![vs code](https://user-images.githubusercontent.com/7052827/76412136-c1292000-639b-11ea-9a0b-7a7ac5756617.png).

**Comment by aneeshack4** [comment]
@ahmedlhanafy I tried out this change locally and couldn't repro either - I just made a codepen bc it's shareable. I didn't make this change again this time but I checked my types file and that error doesn't exist - are you sure you've updated to latest master & built everything properly & have no other changes on your branch?
![image](https://user-images.githubusercontent.com/4161791/76471601-16c3f380-63c1-11ea-8819-51a8353c549d.png)
