### ISSUE TITLE
Tooltip never gets dismissed when moving focus to an element using keyboard

### ISSUE THREAD

**Issue by moizgh** [OfficeDev/office-ui-fabric-react#12255]
### Environment Information

- **Package version(s)**: office-ui-fabric-react@^7.59.0:
- **Browser and OS versions**: All, Windows 10

### Please provide a reproduction of the bug in a codepen: 
Repros on the fabric demo page

#### Actual behavior:
using keyboard, move focus to an element which has a tooltip.
The tooltip will render forever over the element as long as it has focus or until the user moves the mouse. This is causing problems with web driver automation because clicks are being intercepted by the tooltip instead of actual component it overlays.
Showing the tooltip as long as mouse is hovered over an element makes sense. But it poses a usability question when using keyboard to focus an element. 
Experimented by specifying the `closeDelay`value on the props but it looks like I misinterpreted how `closeDelay` is expected to work. It probably respects this delay value only after we have moved the mouse away from the element or moved keyboard focus away from it, rather than dismissing the tooltip after the specified delay value after initial render.

#### Expected behavior:
Tooltip should dismiss after a pre-determined or configurable amount of time after the user hovers over the element or uses keyboard to focus it.

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: Office web apps

**Comment by aneeshack4** [comment]
@moizgh I don't repro this - when I keyboard tab over to the an element with a tooltip, it shows up and when I tab to the next element or mouse to another element, the tooltip correctly disappears.

**Comment by moizgh** [comment]
@aneeshack4 
The issue is that as long as the focus remains on the same element, the tooltip never dismisses.
In the app, the New button always gets focus on default which causes the tooltip to appear. As you can see in the image below, the tooltip is covering the close button (X) partially. And it remains this way as long as the focus does not change.
Now in this state, if we attempt to programmatically click the close button, the tooltip swallows all the clicks. 
![image](https://user-images.githubusercontent.com/25937675/76374344-50d9ba80-6319-11ea-892e-9c3403fb02fa.png)

**Comment by aneeshack4** [comment]
@moizgh Ah I see what you mean now. So I spoke with the Tooltip component owner and they said this is by design - we're following the HTML spec which stays on screen til dismissed (doesn't dismiss on its own before). To have control over visibility, you can use Tooltip and not TooltipHost and set a timer on that Tooltip component itself.

**Comment by moizgh** [comment]
I see. Thanks @aneeshack4 
It sounds like making a feature request to add auto-dismiss capability on the tooltiphost may no longer be an option then?

**Comment by aneeshack4** [comment]
@moizgh Yeah this shouldn't be a feature request. That behavior isn't really the intention behind TooltipHost either - we're following the HTML spec - any further custom behavior can be handled by wrappers/etc. We likely won't build this into the component itself.
