### ISSUE TITLE
Dropdown: Get uncontrolled component value

### ISSUE THREAD

**Issue by lszomoru** [OfficeDev/office-ui-fabric-react#1225]
Is there a way to get the value of an uncontrolled dropdown component? Thanks! 

Ladislau

**Comment by dzearing** [comment]
Right now, it seems not. I'll see what can be done, this should be fixed.

Proposed: we add `selectedKey` getter to the component that gets the current selected key. We add a tests to validate that it works.

I tried doing this last night to quickly resolve this, but the @withResponsiveMode decorator is hiding it (it is not being hoisted to the wrapper component.) Will need to dig in a little more.

**Comment by lszomoru** [comment]
Thanks @dzearing!

**Comment by lszomoru** [comment]
Any update on this issue? Thanks!

**Comment by lszomoru** [comment]
It looks like selectedKey is working as expected in the 2.14.0 release. Closing the issue.

Ladislau

**Comment by lszomoru** [comment]
I accidentally closed the issue. It would be great if we could add selectedKey to the component.

**Comment by amadeogallardo** [comment]
Any updates? Is there now a supported way to get the value from the Ref?
