### ISSUE TITLE
Combobox: Windows Narrator with Edge reading "Combo Edit" role for non editable Combo box

### ISSUE THREAD

**Issue by MdAmeerMind** [OfficeDev/office-ui-fabric-react#12262]
Actual Behavior: 
When the Windows narrator is ON and focus set to combo box. Narrator reads as "Combo Edit" role for all types of Combo box

Expected Behavior:
If combo box is non editable then role "Combo Edit" should not provide by Windows Narrator

Repor: [https://developer.microsoft.com/en-us/fabric#/controls/web/combobox](https://developer.microsoft.com/en-us/fabric#/controls/web/combobox)

Repro Steps:
1) Open URL in Edge
2) Start Windows narrator
3) Focus on Combo-box of any one like "ComboBox with toggleable autoComplete and allowFreeform" combo box. 
4) Now observe that Narrator is reading all details along with "Combo edit" with other information.

**Comment by aneeshack4** [comment]
@MdAmeerMind thanks for reaching out to us. This doesn't repro - Narrator correctly reads out "combobox edit" on only the editable ones as you can see in this Narrator Buddy readout below - when the focus is on a non-editable combobox like a disabled one, it says read-only as it should:
![image](https://user-images.githubusercontent.com/4161791/76470897-854b8600-63ae-11ea-925d-c99a662e3761.png)

**Comment by MdAmeerMind** [comment]
Hi @aneeshack4 , Thank you for your feedback. 

Please consider case of Combo-box label name "ComboBox with static error Message" where user are able to select options by focusing and then using keyboard up/down but won't able to type anything inside Combo box considering (autocomplete ="off"). 

In this behavior Combo box is non editable but user can select option values from list. For this type of Combo box Windows narrator is also reading "Combo Edit" but Combo box is not editable.

Same behavior observe for Combo box Label Name "ComboBox with toggleable freeform/auto-complete" if AllowFreeForm option is Off.

<img width="631" alt="Combobox" src="https://user-images.githubusercontent.com/48435553/76492554-8801b600-6456-11ea-97db-1d4d0953cb6c.PNG">

In logs you have shared Narrator for Combo-box label name "ComboBox With static error Message" reads out 2 role "Combo Edit" and "Read only".

Expected Behavior here is, Windows Narrator should not read "Combo Edit" for these types of Combo box as those are non-editable.

**Comment by aneeshack4** [comment]
@MdAmeerMind discussed this with the component owner & found another issue where this is already being discussed #9837. So going to close this as a dupe - the owner said he's going to get design help & figure out the right behavior. Please see #9837 for future updates on this.
