### ISSUE TITLE
Fluent UI - Keyboard focus does not go to focusable MenuItem content

### ISSUE THREAD

**Issue by davyrwoo** [OfficeDev/office-ui-fabric-react#12273]
### Environment Information

- **Package version(s)**: Fluent UI 0.46.0
- **Browser and OS versions**: Chrome 80.0.3987.132, Windows 10

### Describe the issue:

This is an issue when using Menu or MenuButton with MenuItem's that have focusable content. For example, if the MenuItem content was a Checkbox.

When using keyboard arrow navigation in this menu, focus goes to the outside list item first. The user has to press the arrow key again to reach the content of the menu item.

I believe using the Menu component like this would be a fairly common use case, such as a Filter menu button with checkboxes as the list items.

### Please provide a reproduction of the issue in a codepen:

https://codesandbox.io/s/fluent-ui-example-nyenm?fontsize=14&hidenavigation=1&theme=dark

#### Actual behavior:

Focus only reaches the outside menu item, and not the focusable content.

#### Expected behavior:
Either:
1. Focus on the internal content, but also keep the screen reading role of list item from the menu item, so that screen readers are able to read that this is a menu item.
2. Focus on the menu item, but have screen readers read the content. Also, have keyboard event go into the content when activated on the menu item, and prevent focus on the internal content.

**Comment by jurokapsiar** [comment]
Hi @davyrwoo, according to [ARIA roles model](https://www.w3.org/WAI/PF/aria/roles), menuitem role  "act as standalone user interface widgets or as part of larger, composite widgets" and not as a composite widget. Therefore it is invalid to use checkbox inside of a menu item.

ARIA has specific roles - menuitemcheckbox and menuitemradio for this use case, these are however not yet supported in the Menu and MenuButton component. They are supported in the Toolbar component in the submenu.

Therefore it is currently not very streightforward to achieve this scenario, but it is still possible: https://codesandbox.io/s/fluent-ui-example-7no42

Please note:
- `Checkbox` has `accessibility` prop set to `null`, making it accessibility neutral and only using it for design purposes
- you will need to decide if clicking on one of the items should or should not close the menu, if yes, you can control the state of the menu from outside and pass that using `menuOpen` prop
- if the menu should be closed after clicking on the items, you need to set focus to an element that stays rendered on the screen, depending on your particular use case.

**Comment by KyleBastien** [comment]
@jurokapsiar Given this: 

> ARIA has specific roles - menuitemcheckbox and menuitemradio for this use case, these are however not yet supported in the Menu and MenuButton component. 

Would it make sense to open a separate issue for adding support for `menuitemcheckbox` and `menuitemradio` to `Menu`/`MenuButton`?
