### ISSUE TITLE
DetailsList component: need to be able to color entire row.

### ISSUE THREAD

**Issue by martlaboloa** [OfficeDev/office-ui-fabric-react#1228]
I need to color entire row depending on content of row, by content I mean one of element of items prop.
IColumn interface has className? prop but it's cell specific, and you can use it to color each cell, of row you want to color, on the same color but this way there is uncolored gap between cells, **entire** row is not colored.

**Comment by hross** [comment]
You should be able to wrap the row with whatever you want by using the onRenderRow property and  then calling DetailsRow from inside that wrapper. See [this codepen example for row coloring](http://codepen.io/pogostick_snowman/pen/RppypN).

**Comment by dzearing** [comment]
@hross awesome thanks for the codepen. Closing this, @martlaboloa let us know if you need anything else.
