### ISSUE TITLE
Checkboxes shrink and crop the check when selected in high contrast

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#1229]
### Bug Report

Edge and IE on Windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes)

Requested priority: (Normal) 

#### Describe the issue:

Go into high contrast
Open Fabric site on IE or Edge
Go to the checkbox page

#### Actual behavior:

Checkboxes are smaller when selected, and crop the check.

#### Expected behavior:

Don't resize and crop the check.

### If applicable, please provide a codepen repro:

![tinychecks](https://cloud.githubusercontent.com/assets/20363037/23761154/aab4be62-04a6-11e7-8a8d-22a670c2059d.png)

**Comment by dzearing** [comment]
@betrue-final-final nice catch!!! you're on a roll. Fix fast!

**Comment by micahgodbolt** [comment]
@betrue-final-final ping me if you need a hand with this fix

**Comment by gitjain** [comment]
This appears to be fixed.

![image](https://cloud.githubusercontent.com/assets/25333246/24171249/e5d7da6c-0e40-11e7-8291-5b67fe16f8ea.png)
