### ISSUE TITLE
Facepile: Support customization of the overflow button (icon and class)

### ISSUE THREAD

**Issue by fantua** [OfficeDev/office-ui-fabric-react#1230]
### Features Request

- __Package version(s)__: latest

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

#### Describe the issue:

1. I want to add ability to set custom `Icon` to the `overflowButtonType`. How this API must look like, my suggestion is to add `overflowButtonType.icon` and take `icon` prop from `overflowButtonProps `. Is that ok?

2. Also I want to have possibility to change color of `overflowButton` by adding `class`. Now it's blue: 

![blue](http://image.prntscr.com/image/fe0e677774e44643ac2c42f6a35b36f9.png)

**Comment by dzearing** [comment]
@fantua What if we add both `icon` for the simple case, for the `onRenderIcon?: IRenderFunction<IIconProps>` for the case where the icon to be used is actually an SVG or something totally other than a fabric icon?

**Comment by dzearing** [comment]
Also I think it might be better to call it `iconName` and deprecate `icon`. It is rather confusing what `icon` means at first glance. Thoughts?

**Comment by cschleiden** [comment]
@dzearing are we moving away from `IIconProps`? We use our own icon set (at least for now), so something like `iconName: string` would make it harder for us to use. Not sure how many others do that, though. Have we thought about something like 

`icon: string | IIconProps;`

?

**Comment by fantua** [comment]
`OverflowButtonType`:
- remove/deprecate `more` and `downArrow`, 
- add `icon` 

```js
export enum OverflowButtonType {
  /** No overflow */
  none = 0,
  /** +1 overflow icon */
  descriptive = 1,
  /** ... */
  icon = 2,
  /** @deprecated More overflow icon */
  more = 3,
  /** @deprecated Chevron overflow icon */
  downArrow = 4
}
```
```js
overflowIconProps?: IIconProps
```

Why in `_getIconElement` is using `Persona`?
