### ISSUE TITLE
Dropdown disappears if i add textfield component in sub menu or menu list

### ISSUE THREAD

**Issue by shubhamgautam** [OfficeDev/office-ui-fabric-react#12301]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**:  safari 13.0 ,  OS version -  13.3n

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by aneeshack4** [comment]
@shubhamgautam please provide repro steps and a codepen. We need actionable information.
