### ISSUE TITLE
Split Button primary action is clickable on divider, without a hover style

### ISSUE THREAD

**Issue by joshjcarrier** [OfficeDev/office-ui-fabric-react#12307]
### Environment Information

- **Package version(s)**: 7.83.0
- **Browser and OS versions**: Edge (Chromium) Version 81.0.416.31 (Official build) Beta (64-bit), Mac OS X Catalina 10.15.4 Beta 

### Please provide a reproduction of the bug in a codepen:

The `<DefaultButton>` renders a primary action button, divider, and menu button in `split: true` mode. The clickable portion of each button is signified by a hover style and change in pointer cursor. 

1. Mouse over the divider `|` of a split button with an enabled primary action button.
2. Over the divider, the cursor is an arrow (OS default) and no hover styles are enabled. 
    *Note: depending on prop `styles`, the dimensions of this area may become larger*
3. Primary mouse click.

https://codepen.io/joshjcarrier/pen/abOGpjM

![fabric_splitbutton_clicktarget](https://user-images.githubusercontent.com/526858/76716500-a6351380-66ed-11ea-962b-42f3ccb6f45e.gif)

This scenario can also be recreated on the [Split Button usage](https://developer.microsoft.com/en-us/fabric/#/controls/web/button) section of the Fabric documentation.

#### Actual behavior:

The mouse click activates the primary action button.

#### Expected behavior:

Either:
A. the hover style of the primary action button is set. Aligned with the current click behavior and a more accurate representation of what the user can expect will happen.

OR

B. the primary action is not invoked

### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

**Comment by aneeshack4** [comment]
@joshjcarrier thanks for reporting this! I'm able to confirm the repro. I'm talking with the component owner to brainstorm what could be causing this... the SplitButton render logic in [`BaseButton.tsx`](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx#L659) doesn't seem to indicate anything that would cause the divider's click target to be incorporated into the primary button and cause that to be clicked even while on the divider. And the hover [styles](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Button/SplitButton/SplitButton.styles.ts#L56 ) for the primary button have been set.

**Comment by aneeshack4** [comment]
Tried `zindex` & `pointerEvents: none` which @khmakoto suggested but didn't have much luck - he will look into this more later today.
