### ISSUE TITLE
[A11y][Narrator] Announced Component is read in scan mode

### ISSUE THREAD

**Issue by zachhats** [OfficeDev/office-ui-fabric-react#12323]
### Environment Information

- **Package version(s)**: 7.100.0
- **Browser and OS versions**: n/a

### Describe the issue:

When using the Announced component, the text is read in scan mode.

#### Actual behavior:

The text is read when navigating with arrow keys in scan mode.

#### Expected behavior:

The text is not read when navigating with arrow keys in scan mode.

### If applicable, please provide a codepen repro:
n/a

### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: powerqueryonline

**Comment by aneeshack4** [comment]
@zachhats Thanks for reaching out to us! Why should text not be read? Can you provide a codepen with repro steps on the isolated fabric component? Also if it's a scan mode issue, we're relying on Narrator to add more support of scan mode - until then, we can't really do anything our end if this behavior is correct when not in scan mode.

**Comment by zachhats** [comment]
@aneeshack4 i followed up with the a11y folks and i think this is actually desired behavior (going to take different route), feel free to close this as by design
