### ISSUE TITLE
Icon is not accessible using keyboard

### ISSUE THREAD

**Issue by zhr1130** [OfficeDev/office-ui-fabric-react#12324]
### Environment Information

- **Package version(s)**: V7.104.0
- **Browser and OS versions**: Chrome, Windows 10

### Describe the issue:

Icon component is not accessible using keyboard

### Please provide a reproduction of the issue in a codepen:

<!--
Providing an isolated reproduction of the issue in a codepen makes it much easier for us to help you. Here are some ways to get started:

 https://codepen.io/zhr1130/pen/zYGjmJd

#### Actual behavior:

Icon is not accessible using keyboard

#### Expected behavior:

Icon should be accessible using keyboard

**Comment by dzearing** [comment]
The Icon is a glyph component. This is by design. If you want it to be focusable, you need to use a focusable container such as a `PrimaryButton` or your own custom `button`.

**Comment by zhr1130** [comment]
Thanks David, replace with IconButton fixed my problem
