### ISSUE TITLE
 I CANNOT SELF ASSIGN LICENSES ERROR

### ISSUE THREAD

**Issue by apanca** [OfficeDev/office-ui-fabric-react#12373]
### Environment Information

- **Package version(s)**: (fill this out)
- **Browser and OS versions**: (fill this out if relevant)

### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)

Products/sites affected: (if applicable)

**Comment by apanca** [comment]
https://developer.microsoft.com/en-us/office/profile

I have a new Microsoft Office Dev subscription and when I want to assign myself a license it gives me this error

https://developer.microsoft.com/en-us/notification/api/v1/notifications?top=10&channels=Gleam&channels=Suggestion

![image](https://user-images.githubusercontent.com/57280363/77165904-37efa880-6a81-11ea-81bb-6fafa3e5a4ff.png)

**Comment by apanca** [comment]
help please

**Comment by aneeshack4** [comment]
Hi @apanca this is the Fabric repo, not general Office support. Please contact https://support.office.com/home/contact for help with your subscription.
