### ISSUE TITLE
People picker component cannot search on IE 11

### ISSUE THREAD

**Issue by mtringuyen** [OfficeDev/office-ui-fabric-react#125]
- Go to the People picker component demo page
- Type any name on the control.
- Click on **Search contact & directory**
  => it doesn't show Searching indicator!

**Comment by mikewheaton** [comment]
I think the design for this component is changing, so that it no longer has a spinning indicator. Let's check with the designers on this before fixing it.

![image](https://cloud.githubusercontent.com/assets/1382445/17724704/36cb6436-63f9-11e6-83bd-6b09e87289eb.png)

**Comment by dzearing** [comment]
This has been significantly revamped. I believe it should be much better now.
