### ISSUE TITLE
The selected picker item is overlap with selected ones.

### ISSUE THREAD

**Issue by lijunle** [OfficeDev/office-ui-fabric-react#1256]
### Bug Report

- __Package version(s)__: 2.0.1
- __Browser and OS versions__: Chrome, Safari, may be more.

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High

#### Describe the issue:

Found during testing @micahgodbolt 's [reply](https://github.com/OfficeDev/office-ui-fabric-react/issues/1024#issuecomment-285805402).

I tried to play with your codepen and find a strange issue. After select `aaaaaa`, then input `bbbb` and select, it cannot see `bbbb` in input box. However, after click `x` on `aaaaa`, it shows the `bbbb` again. It seems that, the `bbbb` locates *behind* `aaaaa` label.

There is error ouput in console:

![image](https://cloud.githubusercontent.com/assets/1296500/23848283/761ce026-0811-11e7-9136-8df46fe8b6be.png)

#### Actual behavior:

The `bbbb` item locates behinds the `aaaaa` label.

#### Expected behavior:

They should locate side by side.

### If applicable, please provide a codepen repro:

http://codepen.io/micahgodbolt/pen/jBBgYG?editors=1010

**Comment by micahgodbolt** [comment]
This doesn't appear to be an issue with the current code in our internal examples page (though that code is quite a bit more complex than the codepen example). 

It's possible our problem is one of documentation.

**Comment by gitjain** [comment]
There is an error in the codePen.

item.name needs to be replaced with item.primaryText

http://codepen.io/reenajain/pen/MmgGWW?editors=1010
