### ISSUE TITLE
PeoplePicker: cursor will disappear after selecting person

### ISSUE THREAD

**Issue by MirandaGe** [OfficeDev/office-ui-fabric-react#1261]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: IE or Edge

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

#### Describe the issue:

1. open http://dev.office.com/fabric#/components/peoplepicker with IE
2. type some words and select several name
3. sometimes the cursor will disappear after the person is selected, but the focus is still on input area since we can continue tying and select person

Seems it's not stable and we didn't figure out the reason.

**Comment by gitjain** [comment]
Issue has been fixed so updating the status
