### ISSUE TITLE
2-digit year format in DatePicker defaults to 19XX in Edge

### ISSUE THREAD

**Issue by kopgenorth** [OfficeDev/office-ui-fabric-react#1267]
### Bug Report

- __Package version(s)__: 2.3.0
- __Browser and OS versions__: Microsoft Edge 38.14393

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
Maybe, i haven't looked into the cause of the issue, just the sympoms.

Requested priority: (Blocking, High, Normal, Low) 
Normal
#### Describe the issue:

Using a dateFormat with a 2-digit year causes the year to be parsed as 19xx.  This only seems to happen on the second 'set' call once a user selects a date.  I'm not sure the purpose of the second call, it only seems to happen on edge.

#### Actual behavior:

Selecting a date in 2017 will be set as 1917.

#### Expected behavior:

Selecting a date in 2017 will keep the year 2017.

**Comment by gitjain** [comment]
@kopgenorth 
Can you share a code pen/ repro of the issue.

**Comment by MLoughry** [comment]
This is not due to Fabric. I'm not sure if we want to implement logic to handle this case.

http://dorkasaurusrex.blogspot.com/2013/02/two-digit-years-in-javascript.html

**Comment by aleksandrjPersonal** [comment]
Closing as a won't fix. This is an Edge bug.
