### ISSUE TITLE
TextField component calling onChanged twice

### ISSUE THREAD

**Issue by WesselKuipers** [OfficeDev/office-ui-fabric-react#1270]
### Bug Report

- __Package version(s)__: 2.4.0
- __Browser and OS versions__: Chrome 56.0.2924.87 (64-bit)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low) 
Normal

#### Describe the issue:

The TextField component has a callback the onChanged event which gets called whenever the value of of the textbox gets changed. It appears that after the changes made in #1142 / package version 1.14.1 the onChanged event gets fired twice regardless of whether you have input validation set or not.

This seems like unintended behaviour to me and could cause issues in certain applications.

#### Actual behavior:

onChanged event is being fired twice.

#### Expected behavior:

onChanged event should fire once.

### If applicable, please provide a codepen repro:

https://codepen.io/WesselKuipers/pen/PpKvvm

**Comment by mdahamiwal** [comment]
Thanks for reporting it. It happens since `this.state.value` is still older as setState call is async. Strange that it was not caught in the UTs.
