### ISSUE TITLE
Dropdown: onRenderTitle doesn't works

### ISSUE THREAD

**Issue by jamir0** [OfficeDev/office-ui-fabric-react#1276]
### Bug Report

- office-ui-fabric-react: 2.4.0
- Chrome

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: ( Normal) 

#### Describe the issue:

When i define custom renderer by property onRenderTitle
```
<Dropdown
   label=""
   selectedKey=""
   onRenderTitle={this.myRenderer}
   options={...}
/>
```

it doesn't change view (overrides how to render currently selected item in input) and even invokes it.
#### Actual behavior:

Render currently selected option as implemented inside the component

#### Expected behavior:

Use my renderer (this.myRenderer) instead of default renderer (_onRenderTitle).

i guess it's a bug. Or may be i should use another property?

**Comment by micahgodbolt** [comment]
Hey @jamir0 here's a codepen of it working. Does your render method look similar?

http://codepen.io/micahgodbolt/pen/xqPNMy?editors=0111

**Comment by micahgodbolt** [comment]
One guess is that you aren't passing `item` into your function. You can see the original function (and expected props) here https://github.com/OfficeDev/office-ui-fabric-react/blob/3c1f29c6b86630d5cb83661e423825cab963046b/packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx#L174

**Comment by jamir0** [comment]
Hi all,
i double checked this issue.
1) i try to use this renderer to display label inside the dropdown when nothing had been selected.
```
...
// example
renderer = (label) => (item) => (<span>{item.key=='A'?label:item.text}</span>);
...
<Dropdown
   label=""
   selectedKey=""
   onRenderTitle={this.renderer(label)}
   options={...}
/>

```
2) and renderer defined as a method of the class(with using this.renderer) it doesn't works, but if i move it out of class (with using renderer) as private method defined inside the module - it's works.

http://codepen.io/anon/pen/JWpbBp?editors=0111

**Comment by joschect** [comment]
@jamir0 Hi, there are a few problems with your example. `this.renderer(label) ` will immediately attempt to evaluate and will return an object. onRenderTitle is expecting to get a function back instead. 

Additionally onRenderTitle only knows how to pass item through, it doesn't know about label. So to fix this you can do the following.

```
let _id = 0;

class App extends React.Component {
  
  public renderer = (label, item) => (<span>{item.key=='A'?label:item.text}</span>);
  
  render() {
    return (
      <Fabric.Fabric>
        <Fabric.Dropdown
          onRenderTitle={(item) => this.renderer('Basic uncontrolled', item)}
          label='Basic uncontrolled example:'
          id='Basicdrop1'
          ariaLabel='Basic dropdown example'
          defaultSelectedKey={'A'}
          options={ [options removed to save space ]
          }
        />
      </Fabric.Fabric>
    );
  }
}
ReactDOM.render( 
  <App />,
  document.getElementById('content')
);
```

This is not a bug and everything is working as intended.
