### ISSUE TITLE
Overriding nested elements within a component

### ISSUE THREAD

**Issue by satbai** [OfficeDev/office-ui-fabric-react#1280]
### Bug Report
- __Package version(s)__: All

#### Priorities and help requested (not applicable if asking question):
Are you willing to submit a PR to fix? (Yes, No) No
Requested priority: (Blocking, High, Normal, Low) Normal

#### Describe the issue:
We are currently not able to correctly override styles in nested elements inside an Office Fabric component. The ideal solution would be having a way to specify your own class name for that particular DOM element and use it in your css but it’s not possible to do that today.

#### Actual behavior:
This is how we can currently override the styles. 
Override the button style inside CommandBar:
<CommandBar className="command-bar-area" { ... }  />

.command-bar-area {
    .ms-CommandBarItem-link {
        // override 
    }
}

#### Expected behavior:
I'm not sure what the best solution for this would be.

.command-bar-area {
    .command-bar-item-button {
        // override
    }
}

**Comment by micahgodbolt** [comment]
Command bar is in the middle of some revisions that should make it a lot more customizable.
