### ISSUE TITLE
BasePicker  componentWillReceiveProps() has incorrect signature?

### ISSUE THREAD

**Issue by panigrah** [OfficeDev/office-ui-fabric-react#1282]
The BasePicker componentWillReceiveProps has an extra argument `newState` that it uses to figure out if the state needs to be updated. Is this intentional? 

I cannot set the picker state after it has been rendered. Is this expected behavior?

`public componentWillReceiveProps(newProps: IBasePickerProps<T>, newState: IBasePickerState)`

**Comment by panigrah** [comment]
I can get the `items` property on the picker component to update the picker contents by changing the method to below. Would this work?

    BasePicker.prototype.componentWillReceiveProps = function (newProps) {
        if (newProps.items && newProps.items !== this.state.items) {
            this.selection.setItems(newProps.items);
            this.setState({ items: newProps.items });
        }
    };

**Comment by MLoughry** [comment]
Fixed in #1412
