### ISSUE TITLE
DetailsList is not resizeable after v2.5.0

### ISSUE THREAD

**Issue by notgiorgi** [OfficeDev/office-ui-fabric-react#1285]
DetailsList columns aren't resizeable after v2.5.0

Working version (2.4): https://codepen.io/notgiorgi/pen/EWwJJw

Broken version (2.5): https://codepen.io/notgiorgi/pen/VpMNRG

[this](https://github.com/OfficeDev/office-ui-fabric-react/commit/fc25dec84003547a08c8ef368a1badfca0b93e93#diff-19f69ffb94a855282237018a37fdbe03) might be what caused bug

**Comment by micahgodbolt** [comment]
I tracked down the bug. It was the addition of "button" scope to the styles, which doesn't work due to the sizer not being an actual button.
