### ISSUE TITLE
Dropdown className is not set on root div

### ISSUE THREAD

**Issue by bdgit** [OfficeDev/office-ui-fabric-react#1291]
### Bug Report

- __Package version(s)__:  1.14.3 and GitHub from 6 days ago.
- __Browser and OS versions__:  Windows 10, Chrome

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal 

#### Describe the issue:

I was attempting to target the label of the Dropdown for additional styling.  It doesn't look like render is putting className on the root div.  It is on a child div of the root div.

https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx

(I could be missing something.  Just a few days into learning this.)

#### Actual behavior:

`<div>`
  `<label id="Dropdown7-label" class="ms-Label">Team</label>`
  `<div data-is-focusable="true" id="Dropdown7" class="ms-Dropdown dropdown_3d906209 is-required" tabindex="0" aria-expanded="false" role="combobox" aria-live="assertive" aria-label="Team" aria-describedby="Dropdown7-option" aria-activedescendant="Dropdown7-list">`
    `<span id="Dropdown7-option" class="ms-Dropdown-title" aria-atomic="true"></span>`
    `<i class="ms-Dropdown-caretDown ms-Icon ms-Icon--ChevronDown"></i>`
  `</div>`
`</div>`

#### Expected behavior:

`<div class="ms-Dropdown dropdown_3d906209 is-required">`
  `<label id="Dropdown7-label" class="ms-Label">Team</label>`
  `<div data-is-focusable="true" id="Dropdown7"  tabindex="0" aria-expanded="false" role="combobox" aria-live="assertive" aria-label="Team" aria-describedby="Dropdown7-option" aria-activedescendant="Dropdown7-list">`
    `<span id="Dropdown7-option" class="ms-Dropdown-title" aria-atomic="true"></span>`
    `<i class="ms-Dropdown-caretDown ms-Icon ms-Icon--ChevronDown"></i>`
  `</div>`
`</div>`

**Comment by mdahamiwal** [comment]
Suggestion make sense. We should be fine in moving className to root div hoping it won't regress any styling overrides for other consumers.

**Comment by gitjain** [comment]
I've got a pull request that address this issue. We cannot move the ms-Dropdown class around in the DOM without possibly affecting other users, so I have added class names to the label and the overall container. Does this solve your problem?
