### ISSUE TITLE
ToDo Tutorial: how to integrate TypeScript component classes

### ISSUE THREAD

**Issue by javenu** [OfficeDev/office-ui-fabric-react#1294]
For those of us who are newer to React and TypeScript, it would be helpful to extend the [ToDo Tutorial](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/ghdocs/README.md) to include how to implement the Fabric component classes from https://dev.office.com/fabric#/components.

The Document Card demo doesn't address TypeScript configuration nor does it demonstrate how to import and integrate the code snippets / classes that are provided for each component.

Reverse engineering the Office UI Fabric React reference website seems like the best option, but it's rather complex for someone just learning React + Fabric + TypeScript. I ended up leveraging the example website to work with the components.  

Hopefully more documentation will be made available in the Tutorial to illuminate how to implement the Fabric TypeScript components per the code samples..

**Comment by MJomaa** [comment]
I'd appreciate that. A TypeScript+Office-UI-Fabric-React quickstart sounds awesome :)
