### ISSUE TITLE
Dropdown options not getting selected in single click

### ISSUE THREAD

**Issue by adharpicstore** [OfficeDev/office-ui-fabric-react#1295]
### Bug Report

- __Package version(s)__: 1.14.2
- __Browser and OS versions__: All browsers

#### Priorities and help requested (not applicable if asking question):

Requested priority: (High) 

#### Describe the issue:

Dropdown options are not getting selected in single click. On first click the options changes the direction from bottom to left and then finally we have to make second click to select the option

#### Actual behavior:

Dropdown option changes direction on click and two clicks are required to select an option

#### Expected behavior:

Dropdown option should get selected in single click

### If applicable, please provide a codepen repro:

![dropdown recording 1](https://cloud.githubusercontent.com/assets/24560365/24038060/e4d94b1e-0b25-11e7-8a69-ebde897b053f.gif)

**Comment by micahgodbolt** [comment]
There isn't anything broken with current standard dropdowns, even with multiple on the page http://codepen.io/micahgodbolt/pen/JWOqNv?editors=0110

Is this something you can repro and provide a link to?

**Comment by adharpicstore** [comment]
I think the issue is in thsi method:

private _onRenderItem(item: IDropdownOption): JSX.Element {
 +    let { onRenderOption = this._onRenderOption } = this.props;
 +    let id = this._id;
 +    return (
 +      <BaseButton
 +        id={ id + '-list' + item.index }
 +        ref={ Dropdown.Option + item.index }
 +        key={ item.key }
 +        data-index={ item.index }
 +        data-is-focusable={ true }
 +        className={ css('ms-Dropdown-item', { 'is-selected': this.state.selectedIndex === item.index }) }
 +        onClick={ () => this._onItemClick(item.index) }
 +        onFocus={ () => this.setSelectedIndex(item.index) }
 +        role='option'
 +        aria-selected={ this.state.selectedIndex === item.index ? 'true' : 'false' }
 +        aria-label={ item.text }
 +      > { onRenderOption(item, this._onRenderOption) }</BaseButton>
 +    );
 +  }

The problem here is the setSelectedIndex is getting called onFocus, which does not closes the dropdown. In latest code i found this line to removed:  "onFocus={ () => this.setSelectedIndex(item.index) }"

Is this fixed in some recent time. The office fabric version we are using still have this line and hence the issue. Can you please update in which version of office Fabric is this line removed ?

**Comment by cschleiden** [comment]
@adharpicstore you can use the History for the file? It was removed here https://github.com/OfficeDev/office-ui-fabric-react/commit/39deee70abb7fd60485df84a3b5a1c05a98871c4 with the CSS modules changes.

**Comment by adharpicstore** [comment]
@micahgodbolt Thanks for the commit. I am closing the bug for now. I will reactivate If I face similar issue in next release
