### ISSUE TITLE
DetailsList scrolling cutomization

### ISSUE THREAD

**Issue by nnikka** [OfficeDev/office-ui-fabric-react#1297]
### Bug Report

- __Package version(s)__: 2.4.0
- __Browser and OS versions__: All browsers

#### Priorities and help requested (not applicable if asking question):

Requested priority: (Blocking) 

#### Describe the issue:

It's impossible to make Parent component of DetailsList, with limited width, scrollable on X, if list item is longer than parent component.

#### Actual behavior:

DetailsList has scroll on X, but it's  bottom of the list. 
![ui](https://cloud.githubusercontent.com/assets/23611964/24044372/72ae424c-0b34-11e7-8f2a-38476ccb2c60.gif)

#### Expected behavior:

Parent component of DetailsList should be scrollable on X.

**Comment by dzearing** [comment]
It is possible :) Can you try this prop on DetailsList:

```ts
  constrainMode={ Fabric.ConstrainMode.unconstrained }
```

**Comment by dzearing** [comment]
http://codepen.io/dzearing/pen/gmWOQN?editors=0111

**Comment by dzearing** [comment]
Hope this helps, closing issue. let us know if you have any other issues.
