### ISSUE TITLE
Pickers: Specify maximum number of items to select

### ISSUE THREAD

**Issue by jquintozamora** [OfficeDev/office-ui-fabric-react#1304]
I´d like to suggest a new functionality on Tag Picker to allow handle both scenarios multiple selection and single selection, ideally configurable by a prop. By now (as I know) it only supports multiple tag selection.

Thanks!

**Comment by mdahamiwal** [comment]
Better to have a prop to limit selected picker items, similar to https://github.com/OfficeDev/office-ui-fabric-react/issues/652

**Comment by WesselKuipers** [comment]
You can kind of achieve this by disabling the underlying AutoFill component:
http://codepen.io/WesselKuipers/pen/ryYKod

This does however disable the option to remove selected items via the backspace button.

**Comment by jquintozamora** [comment]
Hi @mdahamiwal , Thanks for you answer. That could be good solution as well. 
Currently I am using other react picker control (https://github.com/JedWatson/react-select) in my solutions. 
But I would l like to replace by the office-ui-fabric-react one. One of the main features I miss is **single selection**, and other is the prop "**isLoading**" which internally loads spinner in the control meanwhile our react application is loading items async.

**Comment by cwdata** [comment]
@dzearing 
This should be considered a feature request for all picker controls. I'm using the people picker and missing a single selection property there as well and I think this is the case for all controls of that type.

**Comment by ohritz** [comment]
Is there any thoughts/decisions about implementing this? I couldn't  make out if it was on roadmap, and if its not,  do we have to wait till after v1? I wouldn't mind taking a crack at it. 
I'm building a taxonomypicker for SharePoint, where the concept of single / multi is crucial.

I imagine a maxItems: number; prop on the basepicker, and conditionally render the autofill input. which I think would still allow removing a selected tag, and thereby rerendering the autofill after amount of items is below the threshold?

**Comment by jquintozamora** [comment]
Hi @ohritz ,
I worked on something similar months ago, just in case it could be useful to you: https://github.com/jquintozamora/react-taxonomypicker

**Comment by ohritz** [comment]
Hi @jquintozamora, I've seen that, thanks :). I was actually going to use it, but then we realized we need the tree view picker like the SharePoint oob control as part of the component aswell. So I started building my own.
