### ISSUE TITLE
Dropdown - rendering issue

### ISSUE THREAD

**Issue by lszomoru** [OfficeDev/office-ui-fabric-react#1307]
### Bug Report

- __Package version(s)__: 1.14.0
- __Browser and OS versions__: Version 57.0.2987.98 (64-bit)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No
Requested priority: (Blocking, High, Normal, Low) High

#### Describe the issue:
I have a dropdown list that contains a very long list of items. If I place this dropdown on a page that is also long hence it has a scroll bar, I see something strange with how the dropdown is rendered. When I click on the dropdown, first it is rendered *under* the text field. When a select an item, it jumps to the *right side* of the text field, and when I click on the item one more time, the item gets selected and the dropdown disappears.

#### Actual behavior:
Dropdown is rendered twice, and the item needs to be selected twice. 

#### Expected behavior:
Dropdown should be rendered once, and the item should only be selected once.

**Comment by cschleiden** [comment]
I think this was fixed with at least version 2.0.1, I can't repro with latest.
