### ISSUE TITLE
ERROR: Error: The command failed with exit code 1

### ISSUE THREAD

**Issue by stephen-oconnor** [OfficeDev/office-ui-fabric-react#1314]
I am getting an issue when I run nmp install with office-ui-fabric-react:

ERROR: The command failed with exit code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! office-ui-fabric-react-repo@1.0.0 postinstall: `rush install && rush link`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the office-ui-fabric-react-repo@1.0.0 postinstall script 'rush install && rush link'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the office-ui-fabric-react-repo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rush install && rush link
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs office-ui-fabric-react-repo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls office-ui-fabric-react-repo
npm ERR! There is likely additional logging output above.

Process so far:
git clone https://github.com/OfficeDev/office-ui-fabric-react.git
npm install

Anyone know what might be causing this?

**Comment by micahgodbolt** [comment]
Do you have Rush installed?

**Comment by stephen-oconnor** [comment]
I didn't know I needed it... It doesn't say in the docs you need it. I'll install it and try again.

Thanks.

**Comment by stephen-oconnor** [comment]
I installed rush and I go the same error.

**Comment by micahgodbolt** [comment]
I'm sorry, I should have mentioned installing Rush globally.

**Comment by dzearing** [comment]
That shouldn't be required... I'm curious if this is an NPM issue.

Basically we install rush locally. Then we want to execute it.

**Comment by dzearing** [comment]
@stephen-oconnor I think installing globally will unblock you but we will fix this! I think we haven't heard about this because many people contributing had it installed and never noticed... maybe... or, they're using a different version of node than you which can handle the resolution maybe.

**Comment by dzearing** [comment]
@stephen-oconnor I've checked in a minor package.json script update to reference the local installed rush build. Can you sync up and make sure this is fixed for you?

**Comment by dzearing** [comment]
Hmm this change may not fix this issue; on reading the error again, I realized this is error code 1 returning from rush something, that's failing. If this still fails, can you provide your node/npm versions?

node -v
npm -v

**Comment by stephen-oconnor** [comment]
npm version - 4.4.1
node version - v6.10.0

Error this time around:

ERROR: The command failed with exit code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! office-ui-fabric-react-repo@1.0.0 _rushInstall: `node node_modules/@microsoft/rush/bin/rush install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the office-ui-fabric-react-repo@1.0.0 _rushInstall script 'node node_modules/@microsoft/rush/bin/rush install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the office-ui-fabric-react-repo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/@microsoft/rush/bin/rush install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs office-ui-fabric-react-repo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls office-ui-fabric-react-repo
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\stephen.oconnor\AppData\Roaming\npm-cache\_logs\2017-03-27T13_13_09_347Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! office-ui-fabric-react-repo@1.0.0 postinstall: `npm run _rushInstall && npm run _rushLink && npm run _rushBuildToFabric`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the office-ui-fabric-react-repo@1.0.0 postinstall script 'npm run _rushInstall && npm run _rushLink && npm run _rushBuildToFabric'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the office-ui-fabric-react-repo package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run _rushInstall && npm run _rushLink && npm run _rushBuildToFabric
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs office-ui-fabric-react-repo
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls office-ui-fabric-react-repo
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\stephen.oconnor\AppData\Roaming\npm-cache\_logs\2017-03-27T13_13_09_577Z-debug.log

**Comment by cschleiden** [comment]
Can we close this for now?

**Comment by stephen-oconnor** [comment]
We actually managed to get this working yesterday. Not really sure why it works now however, I am not complaining :) We updated npm and node, tried everything again with create-react-app and also as part of a SharePoint project and it seems to have worked.

Thanks.

**Comment by cschleiden** [comment]
Awesome, thanks for getting back.
