### ISSUE TITLE
Popup, et al: KeyboardEvent is not passed to 'onDismiss'

### ISSUE THREAD

**Issue by MLoughry** [OfficeDev/office-ui-fabric-react#1321]
### Bug Report

- __Package version(s)__: 2.0.2

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

#### Describe the issue:

`Popup`, as well as various controls (such as `Callout`) that use it, does not pass the Keyboard event to the `onDismiss` handler when the user closes the Popup via the 'Esc' key

#### Actual behavior:

`onDismiss` is called with no parameter

#### Expected behavior:

`onDismiss` is called with the triggering event

**Comment by joschect** [comment]
It looks like you've fixed this @MLoughry , I'm closing this for now.
