### ISSUE TITLE
TagPicker: Add prop for selected items

### ISSUE THREAD

**Issue by nikhilexe** [OfficeDev/office-ui-fabric-react#1323]
https://fabricreact.azurewebsites.net/fabric-react/master/#/examples/PeoplePicker#Implementation

![image](https://cloud.githubusercontent.com/assets/25940082/24198417/dc1dfefc-0f2b-11e7-8e1f-834f532ced12.png)

Currently tag picker takes defaultSelectedItems but it should also take selectedItems which we can pass. We have one scenario where we have couple of rows of tag picker and we can delete as well.

When we delete one of the row, then I see that TagPicker is not getting refreshed and showing stale data. For now to workaround the issue we are explicitly passing key so that all Tag component instances get  render on delete.

**Comment by panigrah** [comment]
@nikhilexe I changed the BasePicker to help me in my project see #1282

**Comment by ohritz** [comment]
This has been implemented about 4 months ago in  BasePicker: Make it able to be a controlled component (#2319).
Tis issue can be closed.
