### ISSUE TITLE
TextField: Allow me to set errorMessage without a promise and reset validation if onGetErrorMessage changes

### ISSUE THREAD

**Issue by hross** [OfficeDev/office-ui-fabric-react#1326]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

#### Describe the issue:

In this block in TextField, basically the update is stopped because the input value does not change:

    public componentWillReceiveProps(newProps: ITextFieldProps) {
    const { onBeforeChange } = this.props;

    if (newProps.value !== undefined && newProps.value !== this.state.value) {

However, I would like to be able to change the validation function and be sure that the validation will occur again.

Additionally, we have a lot of cases where we may want to perform additional steps outside of the component when things get validated. Because the only way to set the error message is with a promise, we have to latch onto the promise to do external validation, which makes our code complicated.

If we could set the error message directly we could externally validate without issue, but that option doesn't appear to exist yet.

This is something I will probably submit a PR for once I get some time to code it up. I think the solution is a relatively simple, non-contract breaking change, but I need to look at the code more to fully understand the impact.

**Comment by cschleiden** [comment]
> Because the only way to set the error message is with a promise

You can also return a `string` from ? 

> If we could set the error message directly we could externally validate without issue, but that option doesn't appear to exist yet.

Do you mean set validation state/error message as a prop for the `TextField`?

**Comment by hross** [comment]
@cschleiden I meant promise or method :). Either way it doesn't do the check. I created an initial PR and attached it to this ticket so it's more obvious. I will review it with our team tomorrow but take a look at let me know what you think.

**Comment by mdahamiwal** [comment]
>Because the only way to set the error message is with a promise

We have `errorMessage` prop on textField that can be set from container component. For such scenarios I would prefer having a wrapper component that attaches `onChanged`, validates the input and change the errorMessage. That will keep ongetErrorMessage cleaner. Thoughts ?

**Comment by hross** [comment]
I completely missed this on the prop definition. It's exactly what I was looking for. Looks like the comment is incorrect so I can fix that at least. Still it might be worth resetting validation when the error evaluation method changes, since I still think that is a bug in the component.

**Comment by hross** [comment]
The real issues here i just the documentation of errorMessage, so I fixed it and added an example.
