### ISSUE TITLE
CommandBar: broken styles

### ISSUE THREAD

**Issue by fantua** [OfficeDev/office-ui-fabric-react#1334]
### Bug Report

- __Package version(s)__: 2.6.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High

#### Describe the issue:

CommandBar got selection after click: 
![img](http://image.prntscr.com/image/fe6ba92b40854e4fbb5e35fcb74895ba.png)

**Comment by dzearing** [comment]
@aleksandrjPersonal will fix, was introduced in #1249 .

@aleksandrjPersonal Looks like there may have been other css tweaks to other components. Please test the focus borders on all of those and make sure you didn't affect any other components in that change.

**Comment by dzearing** [comment]
@fantua good catch; we'll try to get this in tonights publish :)

**Comment by dzearing** [comment]
Updated, codepen fixed. http://codepen.io/dzearing/pen/ENjKPy
