### ISSUE TITLE
DetailsList's Header 

### ISSUE THREAD

**Issue by nnikka** [OfficeDev/office-ui-fabric-react#1341]
### Bug Report

- __Package version(s)__: 2.4.0
- __Browser and OS versions__: all 

#### Priorities and help requested (not applicable if asking question):

Requested priority: (High) 

#### Describe the issue:

We need to make DetailsList's header always top of the List when we scroll down

#### Actual behavior:

When we scroll down, header scrolls down to.
![ui2](https://cloud.githubusercontent.com/assets/23611964/24284778/6f896176-1086-11e7-969a-ae76bbb2f28c.gif)

#### Expected behavior:

Header should be always top of the list.

**Comment by cschleiden** [comment]
This is tracked by https://github.com/OfficeDev/office-ui-fabric-react/issues/1146
