### ISSUE TITLE
Dialogue

### ISSUE THREAD

**Issue by laitang2000** [OfficeDev/office-ui-fabric-react#1342]
Latest from npm, the dialoge box does not hide when state changes..

**Comment by dzearing** [comment]
http://codepen.io/dzearing/pen/NbKwwy

I'm seeing it work just fine. 

You'll need to provide a repro of what you're observing, and perhaps more info as requested in the issue template such as browser, OS, and version information. Feel free to fork the codepen above if you can provide a repro of what you're doing.
