### ISSUE TITLE
Cross (x) icon of Error MessageBar is not vertically aligned with text . 

### ISSUE THREAD

**Issue by mee-1993** [OfficeDev/office-ui-fabric-react#1343]
### Bug Report

- __Package version(s)__: 1.14.2
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

#### Describe the issue:
The text is not properly vertically aligned with the cross icon . 
![image](https://cloud.githubusercontent.com/assets/14120930/24294104/03aa2fb4-10bb-11e7-85c7-f428f625b81c.png)

#### Actual behavior:

The text is not properly aligned with the cross icon (vertically).

#### Expected behavior:

The text should be inline with the cross icon .

**Comment by gitjain** [comment]
@mee-1993 
 This seems to be working fine with the latest builds in IE and Chrome. Sharing a codepen. 

 http://codepen.io/reenajain/pen/EWdojg

If you are still facing the issue, can you share more details.
