### ISSUE TITLE
[TextField][Browser:Edge] Not showing ellipsis for long text

### ISSUE THREAD

**Issue by nikhilexe** [OfficeDev/office-ui-fabric-react#1353]
TextField component doesn't show ellipsis on edge browser for the really long text, however it is working fine for the chrome browser.

**Comment by mdahamiwal** [comment]
It's browser specific behavior. I have raised a bug with Edge team for this issue. Will update this issue when I hear back from them.

**Comment by dzearing** [comment]
Closing as external.
