### ISSUE TITLE
Command bar does not respect onRender of it's items props

### ISSUE THREAD

**Issue by petdun2519** [OfficeDev/office-ui-fabric-react#1355]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) 

Products/sites affected: (if applicable)

#### Describe the issue:

if I specify on render in an IContextualMenuItem as a prop to command bar, command bar just tries to render the item as a button. Does not allow me to use the command bar for any other special controls like Toggle for example. Please fix!!!!!

#### Actual behavior:

Shows a button component no matter what

#### Expected behavior:

Would respect onRender, all you need to do here is check if the item has onRender function if so return that result

**Comment by dzearing** [comment]
@micahgodbolt actually is working on doing exactly this. It is important to us to solve this in a more generalized way.

**Comment by erichdev** [comment]
This has been implemented
