### ISSUE TITLE
ChoiceGroup: How to set the selected choice on component load?

### ISSUE THREAD

**Issue by hankanman** [OfficeDev/office-ui-fabric-react#1360]
### Bug Report

- __Package version(s)__: NPM version 2.8.0

#### Describe the issue:

The ChoiceGroup component has no parameter to say which key should be selected when the component is called. This means it cannot be used in an Edit Form scenario.

#### Expected behavior:

ChoiceGroup Component has member that allows the selected option to be set when called, such as when you wish to retrieve data and pre-populate a form so the data can be edited.

**Comment by dzearing** [comment]
...which component?

**Comment by hankanman** [comment]
Yes @dzearing , sorry i edited my report for clarity

**Comment by cschleiden** [comment]
@hankanman Did you look at this example? http://dev.office.com/fabric#/components/choicegroup ? 
As you can see, "Option B" is pre-selected when the component is rendered by setting the `checked` value.

**Comment by cschleiden** [comment]
We'll deprecate the `checked` option and make the control consistent with `Dropdown`

**Comment by hankanman** [comment]
@cschleiden Yes i have reviewed that. that will only set a 'Default' checked item, you are not able to programatically set the checked item when calling the component. Yes the control should be consistent with the dropdown component.

**Comment by dzearing** [comment]
@hankanman merged, with test coverage, supporting both uncontrolled and controlled scenarios. Hope that helps. Please let us know if that works. Will be published tonight.

**Comment by hankanman** [comment]
@dzearing realise i hadn't let you know, yes all works thank you for the prompt turn around
