### ISSUE TITLE
Usability: Best practice custom theming (font-family and custom colors)

### ISSUE THREAD

**Issue by Knacktus** [OfficeDev/office-ui-fabric-react#1368]
Hi all,

what's the recommended way to create a custom theme? I need to use our corporate fonts and colors ...

In the docs the classes `ms-fontColor-themePrimary` ... or `ms-font-xxl` ... are explained, but I don't know wether and where to override it.

For overriding a single component, I guess the className property is the way to go?

Cheers,

Jan

**Comment by cschleiden** [comment]
For now using a custom class name and overriden styles is unfortunately your best bet. There is ongoing work and investigation to provide a better customization and theming story:
https://github.com/OfficeDev/office-ui-fabric-react/issues/1329
https://github.com/OfficeDev/office-ui-fabric-react/issues/983

**Comment by micahgodbolt** [comment]
Going to call this closed. Feel free to reopen if you have further questions.

**Comment by Ryu36** [comment]
This topic is importend for me, too. I'd appreciate a good theming solution!
For now I go with:

`import { loadTheme } from "@microsoft/load-themed-styles";
loadTheme({themePrimary: "#00adcc"});`

It works as expected. Unfortunately I get a lot of warnings:
...
`Theming value not provided for "neutralPrimary". Falling back to "#333333".
Theming value not provided for "error". Falling back to "#a80000".
Theming value not provided for "neutralTertiary". Falling back to "#a6a6a6".
Theming value not provided for "neutralLight". Falling back to "#eaeaea".
Theming value not provided for "white". Falling back to "#ffffff".
Theming value not provided for "black". Falling back to "#000000".`
...
