### ISSUE TITLE
Command Bar onSearch?

### ISSUE THREAD

**Issue by ClickSimply** [OfficeDev/office-ui-fabric-react#1370]
Looking at the docs:

https://dev.office.com/fabric#/components/commandbar

It seems like the Command Bar's `search` feature has no trigger command built in.  Which is kind of odd, not sure how we're supposed to use a searchbox with no `onSearch` callback!

For now I'm just using this as a  workaround:
```ts
    public componentDidMount() {
        let searchBox = document.querySelectorAll(".parentContainer .ms-CommandBarSearch-input");
        if (searchBox.length) {
            let inputBox = searchBox.item(0) as HTMLInputElement;
            inputBox.onkeydown = (e: Event) => {
                // Do Search
            }
        }
    }

```

I might have missed something here, so let me know if that's the case.  Otherwise I have a feature request: add an `onSearch` property to the command bar.

**Comment by micahgodbolt** [comment]
We have plans to replace the command bar search bar with our search component. So if you have a working workaround we probably won't fix this.

**Comment by jselamy** [comment]
Any news on this matter ?

**Comment by hrc7505** [comment]
Any updates regarding `onSearch()`?
