### ISSUE TITLE
Dropdown: groups for dropdown items

### ISSUE THREAD

**Issue by saritwik** [OfficeDev/office-ui-fabric-react#1377]
Hi,

I want to introduce grouping for items in a drop down. I am thinking of using the grouping pattern that exists today for details list.

Sounds good ?

**Comment by saritwik** [comment]
Dunno how to set labels or assign it to me to this issue ?

**Comment by cschleiden** [comment]
Do you have any mockups for how it's going to look?

**Comment by micahgodbolt** [comment]
How about the design from  contextual menu?
![image](https://cloud.githubusercontent.com/assets/1434956/24621008/c4f7113c-1854-11e7-82f4-bf95f3c20b71.png)

**Comment by cschleiden** [comment]
You mean the nested menus? Personally, I find that too heavy for a plain combo box. I'd like to see something more in the direction of the native `optgroup` rendering:

![image](https://cloud.githubusercontent.com/assets/2201819/24621109/3faceb18-1855-11e7-927e-b9b9c383a4d5.png)

**Comment by saritwik** [comment]
yes nested menus is what I was looking for - thanks for the suggestion optgroup is what i need

**Comment by cschleiden** [comment]
@micahgodbolt this is done now, right?

**Comment by micahgodbolt** [comment]
haven't touched it yet.

**Comment by cschleiden** [comment]
No I mean, isn't this solved by the headers?

**Comment by betrue-final-final** [comment]
@cschleiden is correct. We have this design.

**Comment by cschleiden** [comment]
@betrue-final-final What do you mean? That's a screenshot from https://dev.office.com/fabric#/components, does this mean it's implemented or not? :)

**Comment by betrue-final-final** [comment]
I'm not sure. I thought it had been. Hopefully it isn't just in product and not in Fabric.
