### ISSUE TITLE
ContextualMenu has border between content and beak

### ISSUE THREAD

**Issue by martellaj** [OfficeDev/office-ui-fabric-react#1379]
### Bug Report

- __Package version(s)__: 2.7.1

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) Yes, but pretty booked right now.

Requested priority: (Blocking, High, Normal, Low) Low

#### Describe the issue:

The ContextualMenu with beak has a border around the menu itself, making the beak look a little detached. This is definitely a fit and finish type of bug; no functionality is lost here.

#### Actual behavior:

![image](https://cloud.githubusercontent.com/assets/1019478/24515429/7282903c-152c-11e7-9689-ebbb0d09b17a.png)

#### Expected behavior:

![image](https://cloud.githubusercontent.com/assets/1019478/24515488/a4bc56e6-152c-11e7-8661-c36c770c4e40.png)

No border around the menu bar. From my investigation, the border attribute is being added by the `.ms-ContextualMenu.is-open` rule, but I can't find it anywhere. I was able to workaround this by using the className property of ContextualMenu and adding a targeted rule to override, but I think it should be like this by default.

### If applicable, please provide a codepen repro:

I got to this point and now am unable to repro this issue in your CodePen... I'll submit the issue in case others have a similar issue as me and I'll work on figuring out what's causing it.

**Comment by micahgodbolt** [comment]
You're using the new 2.7.1 version? If so, there shouldn't be any styles applied directly to that class, all css should be applied via tokenized classes .rootIsOpen-jsl1j4l1h2 or whatever.

Do you have an old version of Fabric on the page as well? A pre 2.0 fabric had styles applied directly to the class names, so it'd pollute the CSS

**Comment by micahgodbolt** [comment]
FYI here is the link to a codepen showing it working properly today http://codepen.io/micahgodbolt/pen/PpxMWe?editors=0010

**Comment by martellaj** [comment]
Yeah, I made a comment in my bug report that I couldn't repro it in the CodePen and I'll try to figure out what's going on with my stuff. I'm working in a repo within `odsp-common`, so I should have the latest (barring no major bump to 3.0.0).

**Comment by martellaj** [comment]
I'm not sure which version of "Fabric" I have; are you talking about something different than office-ui-fabric-core/react?

**Comment by micahgodbolt** [comment]
@martellaj oh yeah, I saw your codepen comment, but if anyone else was wondering, I thought I'd link it there.

**Comment by micahgodbolt** [comment]
@martellaj  2.7.1 was referring to your "Package version(s): 2.7.1" at the top of the bug. Yeah, if you are on 2.7.1 you're using CSS modules. But if an older version of fabric is ALSO being loaded onto the page, it'd be applying styles to those components as well. You said the styles were coming from the `.ms-ContextualMenu.is-open` selector. 2.7.1 doesn't apply any styles directly to those class names. So it must be coming from another, older instance of styles being loaded (or some custom css).

**Comment by dzearing** [comment]
So. I don't think this is actually an issue in fabric. @martellaj if you identify a class in fabric causing this, please provide more info. I suspect this is not the case.
