### ISSUE TITLE
BaseButton onRenderMenu support isBeakVisible and other props

### ISSUE THREAD

**Issue by stephenzsy** [OfficeDev/office-ui-fabric-react#1382]
### Bug Report

- __Package version(s)__: 2.10.4
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No. It should be a easy fix.

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: (if applicable)

#### Describe the issue:

in component: packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx
has this line
        this.state.menuProps && onRenderMenu(menuProps, this._onRenderMenu)
which relies on menuProps from Props instead of State. This behavior can be easily achieved through onClick. onRenderMenu provides no additional benefit, i.e. anchor to the button.

In addition, 

the default onRenderMenu only uses items from the Props, other things like isBeakVisible can't be set from the props as it always use {true}
  @autobind
  protected _onRenderMenu(menuProps: IContextualMenuProps): JSX.Element {
    return (
      <ContextualMenu
        className={ css('ms-BaseButton-menuHost') }
        isBeakVisible={ true }
        directionalHint={ DirectionalHint.bottomLeftEdge }
        items={ menuProps.items }
        target={ this._buttonElement }
        labelElementId={ this._labelId }
        onDismiss={ this._onToggleMenu }
      />
    );
  }

#### Actual behavior:

this.state.menuProps && onRenderMenu(this.props.menuProps, this._onRenderMenu)

Not able to set isBeakVisible

#### Expected behavior:

this.state.menuProps && onRenderMenu(this.state.menuProps, this._onRenderMenu)

Able to set isBeakVisible from IButtonProps.menuProps.isBeakVisible

**Comment by dzearing** [comment]
hmm. not sure exactly what you're saying. You can do this...

```tsx
onRenderMenu={ (props, default) => <ContextualMenu isBeakVisible={ true } ... />
````

Can you provide more details?

**Comment by stephenzsy** [comment]
we want the custom render menu function to be able to have the target and onDismiss element provided in the parameter. If I want to use custom omRenderMenu, I still have to have the contextual menu in the parent state.
