### ISSUE TITLE
TextField: add Addon's support

### ISSUE THREAD

**Issue by fantua** [OfficeDev/office-ui-fabric-react#1383]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Blocking

#### Describe the issue:

Need to implement support input addon's like in [bootstrap](http://getbootstrap.com/components/#input-groups-basic). This feature priority is really blocking for me. Can someone provide styling for this and I'll implement component logic? 

#### Expected behavior:

- TextField with `before` addon
- TextField with `after` addon
- TextField with `before` & `after` addon
- TextField without addon

Addon content will accept string value or `Icon` I think.

Thx!

**Comment by micahgodbolt** [comment]
probably need some art direction on this as well.

**Comment by fantua** [comment]
@micahgodbolt I think we can take a look at `PeoplePicker` and create something like this: 

![img](http://image.prntscr.com/image/11ac66f3f3c544859793a901a0dd3eee.png)

Thoughts?

**Comment by fantua** [comment]
@micahgodbolt ping :)

**Comment by micahgodbolt** [comment]
Yup @fantua :) We've been chatting about design specifications in Teams. We've got confirmation that we should use : background color: #F4F4F4, type color: #666666, but we're debating on using any borders (like bootstrap) due to changing color of the input border.

I'm certainly leaning more towards your representation where the addon doesn't have a border.

**Comment by fantua** [comment]
@micahgodbolt yea, addon without border +1. Thx, waiting for styles.

**Comment by fantua** [comment]
@micahgodbolt how it's going?

**Comment by micahgodbolt** [comment]
This is going to take a bit more refactoring than I originally thought, though it's refactoring I want to do. As you can see with the bootstrap example, the input is actually a div with the addon and the input.

![image](https://cloud.githubusercontent.com/assets/1434956/25291923/d6ce38b2-2688-11e7-83c7-0b5f976b999d.png)

I DO want to do this for multiple reasons, but it's not a quick change.

**Comment by micahgodbolt** [comment]
I'll poke at it a bit today, but if it's too much to bite off I might need to get it on our backlog.

**Comment by micahgodbolt** [comment]
Okay, it's going pretty well. Got a PR ready.

**Comment by fantua** [comment]
@micahgodbolt, thanks! 👍 

One question, support for `after` addon was rejected?

**Comment by micahgodbolt** [comment]
after support gets kinda tricky as we currently support icons at the end of the textfield. We could do it, but it'd take a lot of design work to figure out all the variations. Like would it support both icon and addon, or would they be the same thing with/without background. Should the before addon have a no background state etc. Just gets complicated fast.

**Comment by fantua** [comment]
@micahgodbolt, looks like I missed icons support. Why `iconClass` not `IIconProps`?

Anyway for icons I think in some cases icons in start of the textfield will may sense. Same for `after` with addons. 

Maybe make sense to add `AddonProps`, which consists:

- `beforeAddonType` (string | icon)
- `beforeString` | `beforIconProps`
- ... same for after

thoughts?

**Comment by MaartenVerbaarschot** [comment]
@micahgodbolt About the variations with icon vs. after addon:

I would display the icon always in the 'editable' area of the component, keeping the addons on the outer sides. That way it doesn't get so complicated I think.

Is this still being worked on? If not, can I help out with a PR?

I would propose adding a `addonPosition` prop to the component that you can set to either 'before' or 'after'. Using both an icon and addon after would push the icon a bit to the left, keeping it always before the addon.

**Comment by micahgodbolt** [comment]
@MaartenVerbaarschot sorry about the delay, just back from vacation. I'd be happy to take a look at any PR you put together. I think the position idea makes sense, though moving it to the end means you need to worry about resizable textfields (as putting the icon after the text field will mean it's after the resize handle unless absolutely positioned).

**Comment by micahgodbolt** [comment]
This appears to be complete 

![image](https://user-images.githubusercontent.com/1434956/40247117-2ff69d22-5a80-11e8-9e61-309742c50829.png)


Feel free to reopen if the current design doesn't meet your needs.
