### ISSUE TITLE
MessageBar has style issues when displayed in a Fabric Dialog

### ISSUE THREAD

**Issue by lupine86** [OfficeDev/office-ui-fabric-react#1384]
### Bug Report

- __Package version(s)__: 2.10.3
- __Browser and OS versions__: (fill this out if relevant) tested with Chrome

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: VSTS

#### Describe the issue:

When using a MessageBar within a Dialog the icon is given a "line-height" style that causes an alignment issue with the text in the Message Bar.

#### Actual behavior:

Misaligned text and icon in MessageBar.

#### Expected behavior:

Aligned text and icon in MessageBar

### If applicable, please provide a codepen repro:
Code Pen repro shows the issue clearly.
http://codepen.io/lupine86/pen/YZdjJw

**Comment by micahgodbolt** [comment]
This might be a solution we fix with flexbox vs lineheight. Need to look at all of the various scenarios. Thanks for the codepen though, that helps a ton!

**Comment by micahgodbolt** [comment]
Ah, line-height is inherited from parent. So lineheight set on dialog is messing  with the message bars.

**Comment by micahgodbolt** [comment]
Line-height was added to dialog to fix some IE9 bugs. I can remove that overly broad line-height and you shouldn't have a problem

**Comment by micahgodbolt** [comment]
Removed the nasty extra line-height. Closing this one  down.

**Comment by lupine86** [comment]
@micahgodbolt Thanks for the quick investigation and turn around!
