### ISSUE TITLE
Icons not displayed on office ui fabric site

### ISSUE THREAD

**Issue by hankir** [OfficeDev/office-ui-fabric-react#1391]
I not find feedback button on site http://dev.office.com/fabric

Report here:
  http://dev.office.com/fabric#/styles/icons - not displayed
![bug](https://cloud.githubusercontent.com/assets/18185242/24585531/d19899cc-179d-11e7-829f-ae5f2b69122a.png)

**Comment by mikewheaton** [comment]
Sorry for the trouble you're having here, @hankir. We recently made some changes to the website that introduced a few bugs, and this is one of them. We're working on an update now that should be available in a couple of days. In the meantime, you may want to [build the documentation locally](https://github.com/OfficeDev/office-ui-fabric-react#view-the-docs).

**Comment by micahgodbolt** [comment]
Appears to be working now.

**Comment by hankir** [comment]
Thanks ;)
