### ISSUE TITLE
How to make search box to the right in CommandBar component

### ISSUE THREAD

**Issue by jckh1234** [OfficeDev/office-ui-fabric-react#1392]
Is it possible to make search box to the right hand side of CommandBar component?

**Comment by dzearing** [comment]
@jckh1234 Right now, your best bet is to use an actual SearchBox component and compose it next to the CommandBar in the place you expect. We are planning to deprecate the "built in" searchbox in command bar, as it's a redundant (and not well supported) copy of the SearchBox.

We're doing a largish refactoring of CommandBar to make it more composable for this sort of scenario.

@micahgodbolt Just as an fyi of a feature we should include examples of with OverflowSet.

**Comment by micahgodbolt** [comment]
Yup...Eventually command bar will just be an array of overflow sets and a search box could be passed in at any place, beginning or end. Overflow set is my dev focus this week.

**Comment by micahgodbolt** [comment]
I'm going to close this issue as there is a current workaround, and refactor of commandbar will provide support for these types of scenarios.
