### ISSUE TITLE
TooltipHost: tooltip truccated in caseof long text that is not space separated

### ISSUE THREAD

**Issue by vashit** [OfficeDev/office-ui-fabric-react#1393]
### Bug Report

- __Package version(s)__: using //cdnjs.cloudflare.com/ajax/libs/react/15.4.0/react.min.js
- __Browser and OS versions__: chrome

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal) 

#### Describe the issue:

consider a text containing a long name that is not space separated (use case could be slash separated path). hover over it so that tooltip is visible

#### Actual behavior:

first 51 characters shown in tooltip (english)

#### Expected behavior:

complete tooltip should be shown

### If applicable, please provide a codepen repro:

https://codepen.io/vashita/pen/oZmOrZ

**Comment by dzearing** [comment]
This is a css tweak to allow word breaks in the content.

**Comment by micahgodbolt** [comment]
@gitjain here's one for you. https://developer.mozilla.org/en-US/docs/Web/CSS/word-break

**Comment by gitjain** [comment]
Issue has been fixed and merged so updating the issue.
