### ISSUE TITLE
Input fields - consistent height

### ISSUE THREAD

**Issue by lszomoru** [OfficeDev/office-ui-fabric-react#1394]
Hello,

Apologies if I am missing something obvious from a design perspective but currently the height of the various input fields (TextField, Dropdown, Picker, DatePicker, SearchBox, etc.) are inconsistent. Some of them have a height of 32px, others 34px. Combining the various input fields in one form makes the form look visually unappealing. Thanks! 

Ladislau

**Comment by dzearing** [comment]
100% agree. @mikewheaton @micahgodbolt can you please work with Angela and make sure we are totally consistent here?

**Comment by micahgodbolt** [comment]
Let's do a quick audit of all of the input fields and gather all of the values we can. Might as well verify we have all of the values correct when roping Angela in.

**Comment by micahgodbolt** [comment]
Here is a quick pen of some of our various inputs. It highlights some of the sizing issues we need to address. 

http://codepen.io/micahgodbolt/pen/RpdGRR?editors=0010
