### ISSUE TITLE
[Tag picker] Overflowing long tags

### ISSUE THREAD

**Issue by nikhilexe** [OfficeDev/office-ui-fabric-react#1395]
When you have really long tag then it is overflowing the box, see this http://codepen.io/nikhilexe/pen/qrgzJw?editors=0110

Type r in the picker and select long tag....you'll observe that it overflowed the box. Ideally we should show ellipsis after some characters.

**Comment by dzearing** [comment]
This seems pretty simple to fix... like a max-width of 100% of the container with overflow: hidden / text-overflow: ellipsis.
