### ISSUE TITLE
[DropDown] Dropdown propagates the escape key press event after closing dropdown

### ISSUE THREAD

**Issue by adharpicstore** [OfficeDev/office-ui-fabric-react#1396]
### Bug Report

- __Package version(s)__: 2.10.3
- __Browser and OS versions__: Windows 10, All browsers

#### Describe the issue:

Click on drop-down. After drop-down opens press escape key. The escape key press event propagates to the parent elements in DOM after closing the drop-down. As a result of which the container components start reacting to Escape key press events. 

#### Actual behavior:

The Escape key press event on open drop-down propagates to parent DOM element.

#### Expected behavior:

On pressing escape on open drop-down the drop-down should close and escape key press event should stop propagation.

**Comment by dzearing** [comment]
Hmm. I tried reproing, but I don't see this happening.

http://codepen.io/dzearing/pen/GWeZdY?editors=0011

I console.logged events propagating up the hierarchy. If I press 'q' while focused in the dropdown, I see a log. I also log keypress events on document.body. If I press 'esc', I NEVER see it propagating.

I actually expected this behavior: propagate unhandled event (e.g. dropdown is not opened, and does nothing when you press esc), and to stop propagating when doing something (when its opened.)

But I see is ALWAYS stopping propagation which is the exact opposite of what you're describing is actual, and more in line with your expected.

Can you check out the code pen and tweak if necessary to illustrate your point? Are you using keypress? Are you capturing the event?
