### ISSUE TITLE
Blocking Dialogs announce typed characters multiple times when using NVDA.

### ISSUE THREAD

**Issue by lupine86** [OfficeDev/office-ui-fabric-react#1399]
### Bug Report

- __Package version(s)__: 2.10.4
- __Browser and OS versions__: Chrome 57 NVDA 2017.1 (does not occur on Edge or Firefox)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes (If i can figure it out)

Requested priority: Normal

Products/sites affected: VSTS

#### Describe the issue:

There is an accessibility issue when using Chrome with NVDA screen reader.  Blocking Dialogs with input fields output each typed character multiple times.  See Code Pen for reproduction of this issue.  The issue appears to be caused by the mechanism used to make the dialog blocking.

#### Actual behavior:

Typed characters are announced multiple times when typed inside of a blocking dialog.

#### Expected behavior:

Typed characters shouldn't be announced (or only announced once if "Speak typed characters" is enabled in NVDA.

### If applicable, please provide a codepen repro:

http://codepen.io/lupine86/pen/ZePpRZ

**Comment by erichdev** [comment]
Could not repro with latest version of Chrome, please reopen if the issue still occurs
