### ISSUE TITLE
[Overlay/Panel] - Update documentation - Describe best practices for avoiding content shifting

### ISSUE THREAD

**Issue by lszomoru** [OfficeDev/office-ui-fabric-react#1406]
Right now when showing an Overlay or a Panel on a page, the "msFabricScrollDisabled" CSS class is being applied to the body element. If the page has a scrollbar, the CSS class will hide the scrollbar so the layout of the page will shift right. When the Overlay or Panel is hidden the layout will jump back left. Is there a way to improve that so that the layout does not get shifted when an Overlay or Panel is shown? You can reproduce this issue on the Overlay sample page: https://dev.office.com/fabric#/components/overlay

Thanks! 
Ladislau

**Comment by micahgodbolt** [comment]
Think this is a PC bug specifically, as mac scroll bars hover over the content. Good catch though.

**Comment by micahgodbolt** [comment]
at the individual application level you could hide scroolbars, at least for IE/Edge

https://css-tricks.com/snippets/css/hide-scrollbar-in-edge-ie-1011/

Not sure if there is an effective way to do this for all browsers.

**Comment by lszomoru** [comment]
I would actually like to go the other way, and force the scroll bar to always show (overflow-y: scroll). The problem with this is that if I use an Overlay or Panel component on my page, it will hide the scroll bar so the layout will be shifted left and the Overlay/Panel is shows, and then shifted right when the Overlay/Panel is hidden.

**Comment by micahgodbolt** [comment]
It appears the solution we typically take is to not have the body scroll, but rather some content area inside of the body. This means that when overlay opens (and body is set to overflow: hidden !important) the content div doesn't lose it's scroll bar, but scrolling is disabled as the <body> is truncating any overflow.

Seems out website is not using that method properly, so you see that shift. We should update the site and add documentation about proper use to avoid content shifting. 


![image](https://cloud.githubusercontent.com/assets/1434956/24719946/67d21f04-19f0-11e7-87d9-f412e8a341b4.png)

**Comment by lszomoru** [comment]
Thanks @micahgodbolt for the clarifications. 
Updating the site, and providing documentation sounds great!

Ladislau
