### ISSUE TITLE
Panel type extraLarge broken

### ISSUE THREAD

**Issue by Ryu36** [OfficeDev/office-ui-fabric-react#1417]
### Bug Report

- __Package version(s)__: 2.13.0
- __Browser and OS versions__: n/a

#### Describe the issue:

After update to the last version my panel with type extralarge is broken.

#### Actual behavior:

The panel is shown on the left side as a small panel with a little overlay on the left and the underlying page on the right.

I switched to type large. That type is still fine.

#### Expected behavior:

A panel that opens from the right. Filling the full space except a little overlay on the left.

**Comment by micahgodbolt** [comment]
Good catch. Looks like a missing comma in a selector. Got a fix testing right now.

**Comment by dzearing** [comment]
Will be published tonight. Sorry about that.
