### ISSUE TITLE
Accessibility: DetailsList: Narrator can't read "textdata" in columns

### ISSUE THREAD

**Issue by yaananth** [OfficeDev/office-ui-fabric-react#1418]
Goto https://dev.office.com/fabric#/components/detailslist in microsoft edge.
Open "Narrator"
Bring focus on say the checkbox.
![image](https://cloud.githubusercontent.com/assets/12280011/24708916/4b06133a-19e6-11e7-8b55-788709569278.png)

Press CAPSLOCK+F3 (which is a shortcut to move to next column)
It just says "end of column".
Instead it's supposed to read the text in column.

I know there were discussions on making semantic list, this I believe will be solved if it's actually a table.

**Comment by kristoferbrown** [comment]
@yaananth, this appears to be working correctly in with Narrator in both Edge and IE11 now. If you still see this issue in the future please reopen this issue with more details.
