### ISSUE TITLE
SSR different on the client or server

### ISSUE THREAD

**Issue by rohmanhm** [OfficeDev/office-ui-fabric-react#1419]
### Bug Report

- __Package version(s)__: ^2.12.0
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (High) 

Products/sites affected: (if applicable)

#### Describe the issue:
I used fabric components on my React app with Server Side Rendering, but I got warning on my browser console.

#### Actual behavior:
It's throw 
> Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) e" aria-labelledby="0" aria-describedby=
 (server) e" aria-labelledby="426" aria-describedb

![image](https://cloud.githubusercontent.com/assets/7524911/24709761/323404ca-1a45-11e7-8683-0f25896797bc.png)

#### Expected behavior:
console still looks clean

**Comment by rrdelaney** [comment]
Add this line right before you render HTML on the server:

```js
process['__currentId__'] = 0
```

That resets how Aria id's are calculated, and should produce correct markup!

**Comment by battletoilet** [comment]
Thank you @rrdelaney for this fix. Since we haven't heard back from @rohmanhm we will close this issue out.
