### ISSUE TITLE
Compilation error due to missing type in warn.d.ts (@uifabric)

### ISSUE THREAD

**Issue by andikrueger** [OfficeDev/office-ui-fabric-react#1420]
### Bug Report

- __Package version(s)__: 1.5.0

#### Describe the issue:

Error in ...\node_modules\@uifabric\utilities\lib\warn.d.ts
(22,62): error TS7006: Parameter 'message' implicitly has an 'any' type.

The parameter 'message' any doesn't have a type,

#### Needed Change:

Line 22 warn.d.ts should be changed from:

`export declare function setWarningCallback(warningCallback: (message) => void): void;`

to

`export declare function setWarningCallback(warningCallback: (message:any) => void): void;`

**Comment by micahgodbolt** [comment]
Have you tried a rush rebuild yet? I had similar errors after pulling newest master.

**Comment by dzearing** [comment]
While I've addressed the missing typings, I don't really understand why you're hitting this. Are you running tslint in your project against files in your node_modules? What build setup are you running?

**Comment by dzearing** [comment]
Will be published tonight.

**Comment by andikrueger** [comment]
I faced this issue in a project using [create-react-app-typescript](https://github.com/wmonk/create-react-app-typescript). Don't know why this error came up. Thank you for the quick fix.
