### ISSUE TITLE
DetailsList: ability to make certain column align right

### ISSUE THREAD

**Issue by notgiorgi** [OfficeDev/office-ui-fabric-react#1425]
Sometimes we need a way to to align column based on some criteria. e.g. in excel numbers an aligned on the left.

**Comment by notgiorgi** [comment]
Now there is a way to do this, using `onRenderItemColumn` but it is not convenient.

```jsx
const onRenderItemColumn = () => (
        <span
            style={{
                display: 'block',
                textAlign: 'right',
            }}
        >
            {/* data */}
        </span>
)
```

**Comment by betrue-final-final** [comment]
@micahgodbolt, we do need to set color Lynn’s aligned right. Is this useful?

**Comment by micahgodbolt** [comment]
Putting this on @KevinTCoughlin's radar to see if this fits in his details list plans
