### ISSUE TITLE
TextField: add name prop

### ISSUE THREAD

**Issue by wellbeck190** [OfficeDev/office-ui-fabric-react#1426]
I see onGetErrorMessage, onChanged  only pass value for handler, it work well if I only one TextField and its handler.
But when I want to use one handler for many TextField to set value to state, problem occurred. I don't know name of value.

Sorry my English skill, I hope Fabric will solve this problem in future.

**Comment by lambertwang** [comment]
You can bind your onChanged handler before you pass it into your TextFields to differentiate which textfield is changing. [Example](https://codepen.io/anon/pen/rJVRWQ) If this doesn't work for you, let me know.
