### ISSUE TITLE
TextField needs to be simplified and refactored.

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#143]
It's way too complex for a simple TextField. We need to factor out a simple textfield and clean this up.

Right now it has added all of this async validation logic, which delays the change events unnecessarily by default, and when you set delays to 0 it stops firing change events. This is all totally unnecessary. It needs to be slimmed down and a new component for validation should be layered on top of it. That way people that need a simple, predictable textfield can use it, without being concerned with delays and promises.

**Comment by kmees** [comment]
@dzearing i can do a proposal if no one started working on this yet

**Comment by dzearing** [comment]
@kmees Sounds good!

Here are my notes on it:

First I wonder if we should really split out some root base atomic components with no fluff. InputText and TextArea maybe? They don't have a label or anything fancy; we may have InputType enum so that we can render the different variations.

For these atomic components, maybe THESE should be the ones that get the props mixed in, like you were advocating for. I very much would love to do this where it makes the most sense and is predictable.

For composite components like TextField, it would have a label + one of those atomic things. Useful for forms.

For validation scenarios we should have something like ValidatingTextField. Maybe this should be the promise based component. But even in its current state I think it's weird. The validation occurs by default behind a 250ms delay, which gives an unexpected delay, which i think is a totally unnecessary default behavior.

**Comment by kmees** [comment]
What benefit does an InputText or TextArea component have over `<input />` if there is no fluff? Some styles 'require' a label (i.e. underline) and I can't think of much other stuff to put into those atomic components. 

I'll just tinker around a bit end of week and do a PR with a proposal.

Also, what was the verdict on the rootProps discussion? I was on holiday and didn't really follow it.

**Comment by micahgodbolt** [comment]
from #264 "I've merged some of the cleanup changes in this PR in a separate PR; super sorry we took so long to get to this. I'm going to close this PR as it hasn't been updated in a while and is a little outdated now."
