### ISSUE TITLE
Ability to change spacing inside the Facepile

### ISSUE THREAD

**Issue by rickyp-ms** [OfficeDev/office-ui-fabric-react#1432]
Currently there is a 2px spacing between all elements in the Facepile but our designers are requesting 6px.

Overriding .ms-Facepile-members doesn't work because another class .members_c7f15ff5 supercedes it.

Also it's not possible to add a new className to get priority through specificity.

Just curious, what's the best way to go about this currently or will a change have to occur to add className to Facepile?

I think this request could be related to https://github.com/OfficeDev/office-ui-fabric-react/issues/1421 as manipulating the margins of all the elements would provide you a stacked look as well.

**Comment by rickyp-ms** [comment]
Just messing around with the CSS in chrome looks like I can do the following pretty easily:

![spacedwrapped](https://cloud.githubusercontent.com/assets/22225666/24816338/32c546bc-1b8d-11e7-97c4-be8a58938535.png)
// Increase spacing between heads
.ms-Facepile-members {
 margin: -6px;
}
.ms-Facepile-itemButton {
 margin: 6px;
}

![stacked](https://cloud.githubusercontent.com/assets/22225666/24816342/34f1cf46-1b8d-11e7-90fd-25f8696540b4.png)
// Creates a stacked look
.ms-Facepile-members {
 margin: -6px;
}
.ms-Facepile-itemButton {
 margin: 6px 0px;
}
.ms-Facepile-itemButton:not(:first-child) {
 margin-left: -6px;
}

The question that is still open for the stacked look is what happens with the elements wrap to the next line... I feel that if we do support a stacked look, should we think about:
 - Animating to other looks when the props change (e.g. on hover stacked spreads out to see more individual information or something) - This is why I messed specifically with margin and nothing else
 - If wrapping of elements in stacked mode is supported
 - Making this horizontally responsive to show the maximum amount of heads in the space provided if wrapping is turned off.

**Comment by atneik** [comment]
@rickyp-ms You should be able to override the `.ms-Facepile-itemButton` class and either make the faces stacked or make them more spaced out. Here is a codepen for that: http://codepen.io/atneik/pen/XRrPbd 

Make sure something else it not making the styles more specific (eg. Fabric styles being wrapped in some class). Let me know if it's still not working in your context.

And let's keep https://github.com/OfficeDev/office-ui-fabric-react/issues/1421 open in case we need to add that feature.

**Comment by rickyp-ms** [comment]
Only changing the margin-right means the last element in the facepile doesn't align with the right edge of the parent container.

http://codepen.io/anon/pen/ybBRzz
