### ISSUE TITLE
warn.d.ts has errors with tsc

### ISSUE THREAD

**Issue by juliusl** [OfficeDev/office-ui-fabric-react#1435]
### Bug Report

- __Package version(s)__: 2.10.3, 
- **Typescript Version**: 2.1.1
- __Browser and OS versions__: Windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Build breaks 

#### Describe the issue:

Running tsc@2.1.1 on a project with office-ui-fabric-react@2.10.3 results in build errors. I noticed at this time of writing @uifabric/utilities had changes pushed ~22 hours ago. This started happening today.

#### Expected behavior:

No errors.

#### Actual behavior:

The following errors: 
```
node_modules/@uifabric/utilities/lib/warn.d.ts(2,17): error TS1005: ']' expected.
node_modules/@uifabric/utilities/lib/warn.d.ts(2,18): error TS1005: ';' expected.
node_modules/@uifabric/utilities/lib/warn.d.ts(2,19): error TS1128: Declaration or statement expected.
node_modules/@uifabric/utilities/lib/warn.d.ts(3,1): error TS1128: Declaration or statement expected.
```

### If applicable, please provide a codepen repro:
1. Clone this project: https://github.com/juliusl/repro-proj
2. Run `npm install`
3. Run `.\node_modules\.bin\tsc`

### Workaround:
The workaround seems to be to upgrade to the latest typescript. I'm currently on typescript 2.1.1. 

The thing that is concerning here is that this started happening today. Our build/release servers are okay because they cache npm packages, but on an otherwise clean machine this would block builds.

**Comment by dzearing** [comment]
This issue is pretty old and likely is because of using an older version of TypeScript. Please upgrade to 2.4.x or above.
