### ISSUE TITLE
PeoplePicker: Add ability to limit size of resolved users area

### ISSUE THREAD

**Issue by martellaj** [OfficeDev/office-ui-fabric-react#1436]
My scenario is such that the PeoplePicker doesn't have much space, so the resolved user choices stack vertically. My problem is that as the user continues to select users, the height grows very quickly. I found that I could set the `max-height` of the FocusZone that holds all of the resolved users, but it isn't quite good enough because the div doesn't autoscroll as more users are selected. I think this needs to get added to the base picker itself.

If any of this is unclear, just let me know and I'll come by to chat.

**Comment by martellaj** [comment]
Pinging @joschect; just curious on your thoughts about this one. Is there already a solution for this? I saw that it's possible to pass a `className` to the `Suggestions` already; I'm thinking this would be a similar implementation.

**Comment by joschect** [comment]
I think that this should probably get added to the focuszone/ ms-basePicker-text as default. It doesn't make sense for it to not have the scrollbar if it doesn't fit.

**Comment by martellaj** [comment]
AFAIK, there's no max-height or anything on that element, so it technically always fits.
