### ISSUE TITLE
Horizontal scroll appears in Details List when there is vertical scroll-bar.

### ISSUE THREAD

**Issue by ronak-92** [OfficeDev/office-ui-fabric-react#1439]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: chrome, Edge, Firefox

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes, but not sure of the fix.

Requested priority: Normal

Products/sites affected: VSTS

#### Describe the issue:

Whenever there is a vertical scroll-bar, a horizontal scroll appears irrespective of the width of DetailsList container's component. This behavior can be seen in office fabric official site example as well. If you scroll to the bottom of the list a horizontal scroll can be seen. 

As a side effect even the selection appears to clipped since each row doesn't exactly fit within container's width.
below pic is from office fabric site where focus on row appears clipped on right.
![office_fabric_details_list_clipping](https://cloud.githubusercontent.com/assets/9554299/24797030/2f776cd6-1bad-11e7-90b1-8b62b2488f2f.PNG)

This gets fixed when we resize the browser.

#### Actual behavior:
It looks like extra width occupied by scroll bar is not taken into consideration while calculating row width which causes the issue.

#### Expected behavior:

The horizontal scroll should not appear and any row's width should not exceed DetailsList width.

### If applicable, please provide a codepen repro:

Since the issue can be seen in official-example, I haven't provided the repro. If needed I will add the repro as well.

**Comment by dzearing** [comment]
Fixed in #1500
