### ISSUE TITLE
toggle hit area wrong for short labels

### ISSUE THREAD

**Issue by tzapu** [OfficeDev/office-ui-fabric-react#1447]
Are you willing to submit a PR to fix? (Yes, No)
No
Requested priority: (Blocking, High, Normal, Low) 
Normal
Fabric UI React - Toggle Component
#### Describe the issue:
Toggle hit area is as big as text label above. If you have a short 3 letter label, you can't click on the right hand side of the toggle

**Comment by kristoferbrown** [comment]
Pull request #1461 resolves this issue.
