### ISSUE TITLE
css issue in ChoiceGroup in IE11

### ISSUE THREAD

**Issue by shyama1208** [OfficeDev/office-ui-fabric-react#1448]
Hi,
The ChoiceGroup css seems to have some issue in IE11.
![image](https://cloud.githubusercontent.com/assets/26054709/24862543/a3d71364-1e1a-11e7-833e-4ec921b9ea7a.png)

The selected item has alignment issue.

**Comment by battletoilet** [comment]
#1478 fixes this issue and this is now closed.
