### ISSUE TITLE
DetailsList: Go to row feature request

### ISSUE THREAD

**Issue by vaibhav1192** [OfficeDev/office-ui-fabric-react#1455]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low) 
High

Products/sites affected: visualstudio.com

#### Describe the feature:

In Details List, We require a "go to row" functionality.
In our scenario, we have a details list where rows have parent child relationship. We want to show goto parent/child node context menu items for each row of the details list. And clicking on these actions should focus in the apt row. Also we want to support keyboard shortcuts for these goto parent/child actions. 

As a workaround, I tried setting selection in selection tracker and then focussing in the row, but that didn't work out because of virtualization. As there was no element to focus in.

#### Expected behavior:
Updating the selected/goto index, should focus in the corresponding details list row. If it is a virtualized row, then the details list should scroll to the row. And then render and display it. And focus it as well so that it remains keyboard accessible.

**Comment by lambertwang** [comment]
a `ScrollToIndex` public function was added to DetailsList in [this PR](https://github.com/OfficeDev/office-ui-fabric-react/pull/2772). Let me know if that fits your need.
