### ISSUE TITLE
FocusZone doesn't play well when focusable item has a transform: scale under a focus selector.

### ISSUE THREAD

**Issue by justinmwarner** [OfficeDev/office-ui-fabric-react#1457]
### Bug Report

- __Package version(s)__: 2.10.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No - do not know this space

Requested priority: Low/Normal

Products/sites affected: N/A

#### Describe the issue:
When using a FocusZone, if you have a CSS selector like:
transform: scale(1.05);
on the item that is focusable, the arrow keys use is limited. Please see CodePen for example

#### Actual behavior:
Arrow keys use is limited

#### Expected behavior:
Arrow keys work as expected (Up/down and left/right in bidirectional)

### If applicable, please provide a codepen repro:

http://codepen.io/anon/pen/jmNaaQ

I have a comment above the problem CSS line. If removed, it works as expected

**Comment by battletoilet** [comment]
@justinmwarner, can you verify this is still an issue? It looks like your codepen is working as expected.
