### ISSUE TITLE
Facepile Component needs the size ramp: 16px, 24px, 28px, 32px, 40px

### ISSUE THREAD

**Issue by MichaelScottPierce** [OfficeDev/office-ui-fabric-react#1458]
### Bug Report

- __Package version(s)__: (n/a)
- __Browser and OS versions__: (n/a)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix?  (No)

Requested priority: (Normal) 

Products/sites affected: (n/a)

#### Describe the issue:

We are updating the naming and size ramping of Fabric component sizing to move away from "Extrasmall" etc. We now need to name them based on the sizing: 16px, 24px, 28px, 32px, 40px.

This bug is to create versions of the control with the persona at these 5 sizes.
<img width="414" alt="image" src="https://cloud.githubusercontent.com/assets/22697861/24920106/d3891898-1e9a-11e7-931e-1437a1f2c7f2.png">

**Comment by micahgodbolt** [comment]
we currently support the following
```
size28 = 7,
  size16 = 8,
  size10 = 9,
  size24 = 10,
  size32 = 11,
  size40 = 12,
  size48 = 13,
  size72 = 14,
  size100 = 15
```

Looks like this one can be closed up
