### ISSUE TITLE
DetailsList: Rows are selectable when using SelectionMode.none

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#147]
When a DetailsList is given `SelectionMode.none`, should it still render FocusZones around the rows? I'm attempting to use it for a simple, non-interactive table and the rows have a focus state:

![image](https://cloud.githubusercontent.com/assets/1382445/17724519/9834d2cc-63f7-11e6-877e-5f357bbd4563.png)

**Comment by dzearing** [comment]
Yes it should have focus rectangles (we don't remove the keyboarding accessibility when selection mode is none.) And you should wrap in ms-Fabric to make them look better. :)
