### ISSUE TITLE
Calendar: support wrap-around keyboard navigation in month panel

### ISSUE THREAD

**Issue by MLoughry** [OfficeDev/office-ui-fabric-react#1475]
When you press the right arrow while highlighting April, for example, nothing happens. This can be confusing for visually impaired users who can't see the grid layout.

Instead, we should implement wrap-around logic similar to what's implemented in the day panel

**Comment by kristoferbrown** [comment]
@MLoughry, this appears to be fixed in the current calendar. Please reopen if you still see issues here.
