### ISSUE TITLE
Not able to use ariaLabel props in PivotItem

### ISSUE THREAD

**Issue by satbai** [OfficeDev/office-ui-fabric-react#1480]
The PivotItem in the Pivot component is supposed to have an optional ariaLabel for the links ([see documentation](https://fabricreact.azurewebsites.net/fabric-react/master/#/examples/pivot)), but it appears to be broken at the moment. As you can see in the result image below, the aria-label attribute is not added to the tabs.

Implementation:
<PivotItem
    ariaLabel={"aria label"}
    linkText={"text"}
    ItemKey={"key"} />

Result:
![image](https://cloud.githubusercontent.com/assets/24945574/24929166/ea8d0198-1eb9-11e7-82ea-b183cdada65a.png)

**Comment by leddie24** [comment]
Fixed in #1485
