### ISSUE TITLE
Commandbar doesn't support custom render child element

### ISSUE THREAD

**Issue by rachelcl9** [OfficeDev/office-ui-fabric-react#1494]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: OWA

#### Describe the issue:
Commandbar in OWA supports split drop down button, which saves one click to execute the onClick command. 

![image](https://cloud.githubusercontent.com/assets/27024404/24934200/fa6ed25c-1ece-11e7-86e5-9eecf1ea2671.png)

#### Actual behavior:

However in current fabric, the commandbar control renders the commandbar items, which is an array of IContextualMenuItem. The IContextualMenuItem allows to specify the onRender function, but commandbar doesn't respect the customized function and always render the default ContextualMenuItem.

#### Expected behavior:

Same as ContextualMenu.tsx, Commandbar.tsx should respect child's element's onRender method.

**Comment by micahgodbolt** [comment]
this is done, and I've confirmed that it works in the new commandBar I'm working on.
