### ISSUE TITLE
ChoiceGroup: Add a way to provide icons (or other content) to render for individual items.

### ISSUE THREAD

**Issue by jakeaaronson** [OfficeDev/office-ui-fabric-react#15]
The  ChoiceGroup has an optional  imageSrc string parameter. How can I give it a Icon like the one below. 
`<i className='ms-Icon ms-Icon-star' />
`
let me know if the question is not clear.

**Comment by mikewheaton** [comment]
The `imageSrc` parameter is to specify a URL with an image to display, and doesn't support an icon element right now. It looks like the image area is always 50x50, so an icon option could be added. I'll mark this as a feature request that we can look into supporting.

**Comment by atneik** [comment]
Feature is added in https://github.com/OfficeDev/office-ui-fabric-react/pull/982; closing this request
