### ISSUE TITLE
Input item under DetailsList eating space button press

### ISSUE THREAD

**Issue by nikhilexe** [OfficeDev/office-ui-fabric-react#1503]
We have used Input item inside DetailsList and with recent release it stops honoring space. This was working fine with 1.14.2 release.
See this codepen: http://codepen.io/nikhilexe/pen/KmKwwL

**Comment by micahgodbolt** [comment]
1.14.2
![image](https://cloud.githubusercontent.com/assets/1434956/25012553/af6dfd84-2025-11e7-8b00-aaaffe99b20c.png)

2.10.4
![image](https://cloud.githubusercontent.com/assets/1434956/25012587/c4b8dd30-2025-11e7-9501-d1c368fbf006.png)

These don't look awfully different. Are you referring to the margin above/below the input?

**Comment by nikhilexe** [comment]
1.14.2
![image](https://cloud.githubusercontent.com/assets/25940082/25013654/1b1d5fd6-2092-11e7-9431-6c0552332b8e.png)

2.10.4
![image](https://cloud.githubusercontent.com/assets/25940082/25013691/424a66a8-2092-11e7-99cb-b3719add9f00.png)

**Comment by nikhilexe** [comment]
See, in 2.10.4 I am unable to write something with space

**Comment by micahgodbolt** [comment]
Haha, that's what I get for just bashing on the keyboard. Thanks!

**Comment by micahgodbolt** [comment]
Yeah, we made a change to support spacebar interacting with the list items. Seems spacebar presses are being eaten up even when made in text fields.

**Comment by micahgodbolt** [comment]
Fixed!
