### ISSUE TITLE
[Accessibility] [Command Bar]: Button that opens a dialog, when closed is loosing focus

### ISSUE THREAD

**Issue by yaananth** [OfficeDev/office-ui-fabric-react#1515]
A little gif that explains the problem:

![lostfocus](https://cloud.githubusercontent.com/assets/12280011/25028952/9cb07454-2086-11e7-95f0-e2b87514d3ff.gif)

For some reason, "delete folder" gets focus as expected, not the others, though all share same code.

They are all rendered through something like,
```
items.push({
            title: blahblah,
            onClick: () => {
                ReactDOM.render(<DialogHere showDialog={true} />, this._dialogElement);
            }
        });
```

I didn't look into commandbar code deep, but I guess it uses a `FocusZone`. 
Does it handle these cases?

**Comment by jordandrako** [comment]
Just to confirm, I'm having a difficult time reproducing this. Are you still having this issue?

**Comment by jordandrako** [comment]
We are currently closing out all issues preceding Fabric React v5. If you are still seeing the same issue, please open a new issue.
