### ISSUE TITLE
DatePicker does not return ISO8601 date format

### ISSUE THREAD

**Issue by hankanman** [OfficeDev/office-ui-fabric-react#1516]
#### Describe the issue:

There is no component member to return a ISO8601 compliant date format, or it isn't documented from what i can find

#### Actual behavior:

Component returns a 'Pretty' date value from the 'onSelectDate' member.

#### Expected behavior:

'onSelectDate' member should return ISO8601 compliant date that can be pushed on a form submit.
or a new member that returns an ISO8601 date should be added to the DatePicker component

**Comment by cschleiden** [comment]
DatePicker should return a `Date` object: 

```Typescript
 /**
   * Callback issued when a date is selected
   */
  onSelectDate?: (date: Date) => void;
```

You could format that any way you want?

**Comment by hankanman** [comment]
@cschleiden When calling the DatePicker using this: 

`<DatePicker
              label='Requested Change Time/Date'
              isRequired={true}
              firstDayOfWeek={DayOfWeek.Monday}
              placeholder='Select a date...'
              onSelectDate={(r) => {return newValues.Date = r;}}
/>`

I get a string returned: 'Fri Apr 14 2017 00:00:00 GMT+0100 (GMT Summer Time)' am i to manipulate this or am i doing something wrong?

**Comment by cschleiden** [comment]
See this codepen: http://codepen.io/cschleiden/pen/pPvQOK?editors=0010 The value is not a string. `Date` does have a `toString` method, however, that returns a pretty printed string. Are you using that by accident?

**Comment by hankanman** [comment]
@cschleiden if you change the alert to console log it will log a string not an object: [http://codepen.io/Hankanman/pen/gWbQEm](url)

**Comment by cschleiden** [comment]
Yes, it automatically uses `toString` as I just mentioned.

**Comment by hankanman** [comment]
okay, sorry still new to react, so how to return it skipping the 'toString' method?
