### ISSUE TITLE
Create a new Dialog-esque control for arbitrary content

### ISSUE THREAD

**Issue by MLoughry** [OfficeDev/office-ui-fabric-react#1538]
For OWA, we have some controls that we want to display in a centered modal popup, similar to `Dialog`, but without any of the inner chrome of that control. Just a centered popup (with overlay) that allows for arbitrary content.

**Comment by micahgodbolt** [comment]
Yeah, I've been wanting to break dialog up into a specific use of a new model component, kinda like how teaching bubble is a specific callout.
