### ISSUE TITLE
Problem with Panel and Safari scrolling (Mobile)

### ISSUE THREAD

**Issue by dsimoes** [OfficeDev/office-ui-fabric-react#1540]
### Bug Report

office-ui-fabric-core: 5.1.0
office-ui-fabric-react: 2.15.0

#### Describe the issue:

With a React Panel component opened, when trying to scroll the panel contents on an Apple mobile device (Safari), scroll will happen on the page under the Panel.

This can actually be replicated on the Panel demo page

#### Actual behavior:

Scrolling on Apple Mobile device (Safari) is occuring on the background page, instead of the Panel

#### Expected behavior:

Scroll should happen on the Panel, like other system / browsers

**Comment by mdahamiwal** [comment]
@dsimoes, are you using the non-modal panel (using `isBlocking = false`)?

**Comment by dsimoes** [comment]
@mdahamiwal , i'm using the modal one.
