### ISSUE TITLE
DetailsList: accessbility: Enter not working on links.(Regression)

### ISSUE THREAD

**Issue by bharay** [OfficeDev/office-ui-fabric-react#1542]
### Bug Report

- __Package version(s)__: latest

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Blocking.

Products/sites affected: VSTS.

#### Describe the issue:
 Pressing enter on links in office fabric details list doesnot trigger that link navigation. I guess its triggering the row event handler instead of  individual cell's handler. This is a blocker in almost all accessbility scenarios.

#### Actual behavior:
1. Go to "Rendering custom item columns with sorting" example of https://dev.office.com/fabric#/components/detailslist . 
2. Click on the name link in the first row. It takes us to the corresponding link.
3. Now go back and instead of clicking, navigate to that cell and press enter. It shows a popup instead of navigating.
4.This popup also shows when a row is clicked or enter is pressed when a row is selected. So I guess it's triggering the row event handler instead of individual cell's handler.

#### Expected behavior:
Instead of showing a popup in the step 3 above it should navigate to that url.

### If applicable, please provide a codepen repro:

Repro provided in officefabric site in above repro steps.

**Comment by micahgodbolt** [comment]
This is working as of yesterdays release. You can see it here. http://codepen.io/dzearing/pen/EgqMZq

**Comment by micahgodbolt** [comment]
Please feel free to ping me if this is still not working for you when you update to current release
