### ISSUE TITLE
2.18.0 + breaks <Button>

### ISSUE THREAD

**Issue by carruthe** [OfficeDev/office-ui-fabric-react#1546]
### Bug Report

- __Package version(s)__: 2.18.0 and 2.19.0
- __Browser and OS versions__: Mac O 10.12.4, Safari

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No): No

Requested priority: (Blocking, High, Normal, Low): Blocking

Products/sites affected: (if applicable)

Updating from 2.17.0 to 2.18.0 caused any page where I was using the <Button> component to crash, with the error:

`[Error] Exception in Layer.componentDidMount(): Exception in Layer.componentDidUpdate(): Button@https://localhost:3000/static/js/bundle.js:137094:26
https://localhost:3000/static/js/bundle.js:26494:32
measureLifeCyclePerf@https://localhost:3000/static/js/bundle.js:26274:15
_constructComponent@https://localhost:3000/static/js/bundle.js:26479:53
mountComponent@https://localhost:3000/static/js/bundle.js:26387:41
mountComponent@https://localhost:3000/static/js/bundle.js:18805:50
mountChildren@https://localhost:3000/static/js/bundle.js:25574:59
_createInitialChildren@https://localhost:3000/static/js/bundle.js:22569:46
mountComponent@https://localhost:3000/static/js/bundle.js:22388:35
mountComponent@https://localhost:3000/static/js/bundle.js:18805:50
mountChildren@https://localhost:3000/static/js/bundle.js:25574:59
_createInitialChildren@https://localhost:3000/static/js/bundle.js:22569:46
mountComponent@https://localhost:3000/static/js/bundle.js:22388:35
mountComponent@https://localhost:3000/static/js/bundle.js:18805:50
mountChildren@https://localhost:3000/static/js/bundle.js:25574:59
_createInitialChildren@https://localhost:3000/static/js/bundle.js:22569:46
mountComponent@https://localhost:3000/static/js/bundle.js:22388:35
mountComponent@https://localhost:3000/static/js/bundle.js:18805:50
performInitialMount@https://localhost:3000/static/js/bundle.js:26570:49
mountComponent@https://localhost:3000/static/js/bundle.js:26457:41
mountComponent@https://localhost:3000/static/js/bundle.js:18805:50
mountChildren@https://localhost:3000/static/js/bundle.js:25574:59
_createInitialChildren@https://localhost:3000/static/js/bundle.js:22569:46
mountComponent@https://localhost:3000/static/js/bundle.js:22388:35
mountComponent@https://localhost:3000/static/js/bundle.js:18805:50
mountChildren@https://localhost:3000/static/js/bundle.js:25574:59
_createInitialChildren@https://localhost:3000/static/js/bundle.js:22569:46
mountComponent@https://localhost:3000/static/js/bundle.js:22388:35
mountComponent@https://localhost:3000/static/js/bundle.js:18805:50
performInitialMount@https://localhost:3000/static/js/bundle.js:26570:49
mountComponent@https://localhost:3000/static/js/bundle.js:26457:41
mountComponent@https://localhost:3000/static/js/bundle.js:18805:50
mountChildren@https://localhost:3000/static/js/bundle.js:25574:59
_createInitialChildren@https://localhost:3000/static/js/bundle.js:22569:46
mountComponent@https://localhost:3000/static/js/bundle.js:22388:35
mountComponent@https://localhost:3000/static/js/bundle.js:18805:50
mountChildren@https://localhost:3000/static/js/bundle.js:25574:59
_createInitialChildren@https://localhost:3000/static/js/bundle.js:22569:46
mountComponent@https://localhost:3000/static/js/bundle.js:22388:35
mountComponent@https://localhost:3000/static/js/bundle.js:18805:50
performInitialMount@https://localhost:3000/static/js/bundle.js:26570:49
mountComponent@https://localhost:3000/static/js/bundle.js:26457:41
mountComponent@https://localhost:3000/static/js/bundle.js:18805:50
mountChildren@https://localhost:3000/static/js/bundle.js:25574:59
_createInitialChildren@https://localhost:3000/static/js/bundle.js:22569:46
mountComponent@https://localhost:3000/static/js/bundle.js:22388:35
mountComponent@https://localhost:3000/static/js/bundle.js:18805:50
performInitialMount@https://localhost:3000/static/js/bundle.js:26570:49
mountComponent@https://localhost:3000/static/js/bundle.js:26457:41
mountComponent@https://localhost:3000/static/js/bundle.js:18805:50
performInitialMount@https://localhost:3000/static/js/bundle.js:26570:49
mountComponent@https://localhost:3000/static/js/bundle.js:26457:41
mountComponent@https://localhost:3000/static/js/bundle.js:18805:50
mountComponentIntoNode@https://localhost:3000/static/js/bundle.js:31832:47
perform@https://localhost:3000/static/js/bundle.js:19824:25
batchedMountComponentIntoNode@https://localhost:3000/static/js/bundle.js:31854:23
_renderNewRootComponent@https://localhost:3000/static/js/bundle.js:32048:33
_renderSubtreeIntoContainer@https://localhost:3000/static/js/bundle.js:32129:56
componentDidUpdate@https://localhost:3000/static/js/bundle.js:136712:58
https://localhost:3000/static/js/bundle.js:132560:48
componentDidMount@https://localhost:3000/static/js/bundle.js:136682:33
https://localhost:3000/static/js/bundle.js:132560:48
measureLifeCyclePerf@https://localhost:3000/static/js/bundle.js:26274:15
https://localhost:3000/static/js/bundle.js:26463:32
notifyAll@https://localhost:3000/static/js/bundle.js:18680:27
close@https://localhost:3000/static/js/bundle.js:29700:36
closeAll@https://localhost:3000/static/js/bundle.js:19890:30
perform@https://localhost:3000/static/js/bundle.js:19837:25
perform@https://localhost:3000/static/js/bundle.js:19824:25
flushBatchedUpdates@https://localhost:3000/static/js/bundle.js:18518:27
flushBatchedUpdates@[native code]
closeAll@https://localhost:3000/static/js/bundle.js:19890:30
perform@https://localhost:3000/static/js/bundle.js:19837:25
dispatchEvent@https://localhost:3000/static/js/bundle.js:29427:35
dispatchEvent@[native code]
	onError (bundle.js:132575)
	(anonymous function) (bundle.js:132566)
	measureLifeCyclePerf (bundle.js:26274)
	(anonymous function) (bundle.js:26463)
	notifyAll (bundle.js:18680)
	close (bundle.js:29700)
	closeAll (bundle.js:19890)
	perform (bundle.js:19837)
	perform (bundle.js:19824)
	flushBatchedUpdates (bundle.js:18518)
	flushBatchedUpdates
	closeAll (bundle.js:19890)
	perform (bundle.js:19837)
	dispatchEvent (bundle.js:29427)
	dispatchEvent`

Switching to one of the more specialized buttons (e.g. DefaultButton) fixes the problem.

Thanks,

Nick

**Comment by micahgodbolt** [comment]
We made sure to continue to support <Button> in the most recent release, and you can see that it _should_ work either way, as you can see here. 

http://codepen.io/micahgodbolt/pen/NjGeLY

Was this a button in some other context/component? I'm not able to replicate with a simple example.

**Comment by micahgodbolt** [comment]
But in the other hand, if you can transition over to named buttons, that is our preferred method moving forward as menuType is deprecated.

**Comment by carruthe** [comment]
Your CodePen works for me too.  I am using React 15.5.4, which may be contributing.  However, when I change the references in your Codepen to 15.5.4, it still works fine.  It was simple enough to transition over to the other more specific button types, so it's not really a big deal, I guess.
