### ISSUE TITLE
Choice group wrong dot position at IE11

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#1551]
### Bug Report

- __Package version(s)__: 2.14.0
- __Browser and OS versions__: IE11

#### Priorities and help requested (not applicable if asking question):

Requested priority: High

Products/sites affected: Client Side webparts' property pane.

#### Describe the issue:

When image choice group is chosen in IE11, the position of the selection dot show up at the wrong positoon. It works well in Chrome.
![image](https://cloud.githubusercontent.com/assets/7711735/25168974/fb6148da-2517-11e7-8c9f-fce304cd0e9e.png)

#### Actual behavior:

Dot in wrong position

#### Expected behavior:
Dot right inside the circle

**Comment by micahgodbolt** [comment]
It's working correctly now.

![image](https://cloud.githubusercontent.com/assets/1434956/25347194/e7889362-28ce-11e7-85e1-a70da9ef4a24.png)

**Comment by micahgodbolt** [comment]
Pretty sure there was a PR for this recently. Feel free to reopen if it's still a problem once you've upgraded to newest.
