### ISSUE TITLE
Button property documentation inconsistency

### ISSUE THREAD

**Issue by r33kan** [OfficeDev/office-ui-fabric-react#1552]
### Bug Report

- __Package version(s)__: 2.20.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

#### Describe the issue:

When using IconButton component IButtonProps warns that icon?:string is deprecated and iconName should be used instead. 

The problem is that iconName property isn't actually provided as an option.

There is however a iconProps property provided and this has the iconName property.

#### Actual behavior:

Red squigglies and build failure when using iconName.

#### Expected behavior:

No squigglies and builds without error.

**Comment by micahgodbolt** [comment]
Updated docs and linked to IIconProps
