### ISSUE TITLE
TooltipHost: Add showOnOverflow option to props

### ISSUE THREAD

**Issue by hross** [OfficeDev/office-ui-fabric-react#1554]
There are a variety of methods to check for overflow here: http://stackoverflow.com/questions/6406843/detect-if-text-has-overflown

And we have our own ways in TFS (contentsOverflow in UI.ts for those looking at this).

In any case, a lot of times we use tooltips to show content that overflows *only* so it would be great to have this option the tooltip host so we don't have tooltip madness everywhere.

**Comment by hross** [comment]
Looks like the utilities might already exist here: https://github.com/OfficeDev/office-ui-fabric-react/blob/265217a4f00cf04a437a61c6ad4033fb52b1b525/packages/utilities/src/overflow.ts

**Comment by cschleiden** [comment]
Duplicate of https://github.com/OfficeDev/office-ui-fabric-react/issues/1433
