### ISSUE TITLE
Default "gap space" for the callout control should be 0, not 16.

### ISSUE THREAD

**Issue by dasanto** [OfficeDev/office-ui-fabric-react#1559]
The gap distance between the beak of the callout and the control it is pointing to is too large and becomes confusing on more densely populated pages.
![tooltip16demo](https://cloud.githubusercontent.com/assets/20359520/25201317/2a233802-2506-11e7-97b4-0579ff1c8fb8.png)
![tooltip16vsts](https://cloud.githubusercontent.com/assets/20359520/25201327/36f1f7a8-2506-11e7-8655-e5305dbb429a.jpg)

**Comment by navneet-g** [comment]
We require it for VSTS experiences, I can work on a change and submit a PR if no one has any objection.

**Comment by cschleiden** [comment]
This comes from VSTS.

I'm not sure whether we want to change the overall office fabric default. It was probably there for a reason? 

We might consider a VSTS only override. 

@dzearing Not everything in VSTS is React, yet, we don't have a common root node. So, this is not something we could use the customizer for, right?
