### ISSUE TITLE
Labels should have 8px of padding not 5px

### ISSUE THREAD

**Issue by aleksandrjPersonal** [OfficeDev/office-ui-fabric-react#1562]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) 

Products/sites affected: (if applicable)

**Comment by aleksandrjPersonal** [comment]
@micahgodbolt Why was this closed?

**Comment by micahgodbolt** [comment]
I saw the PR was merged in...Did that PR not solve the issue? If not, feel free to reopen.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by aleksandrjPersonal** [comment]
@micahgodbolt oh, I was just moving this discrete piece of work to a new task, and then a new PR when the work has been done. Reopening.
