### ISSUE TITLE
feature-request: Add required error message for Dropdown

### ISSUE THREAD

**Issue by YusongLiu** [OfficeDev/office-ui-fabric-react#1563]
Currently the `required` prop for Dropdown only add an indicator to the label but not actually checking the state of the Dropdown.

In DatePicker, we have the actual checking and will show the error message if no date is not selected.

Could we also add the checking and error message for Dropdown?

**Comment by micahgodbolt** [comment]
This is currently being addressed in #1499 and is basically a dup of #1097. I'm going to close this up.
