### ISSUE TITLE
Textfield: Updating defaultValue doesnot update the value in input.

### ISSUE THREAD

**Issue by bhrayala** [OfficeDev/office-ui-fabric-react#1564]
### Bug Report

- __Package version(s)__: (latest)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)
Requested priority: (Normal) 

#### Describe the issue:
Updating defaultValue of an uncontrolled component doesnot update the value in input. This causes issues in forms with a reset button or some form of external updates. I suppose simialar issue happens with defaultChecked or any other defaults in other components. 

React had a similar issue in their native components which was fixed. https://github.com/facebook/react/issues/4618. This issue has a lenghty discussion on possible ways to fix it for their native input component. 

#### Actual behavior:
Changing default value of Textfield should change the value of input.

#### Expected behavior:
Changing default value of Textfield doesnot change the value of input.

### If applicable, please provide a codepen repro:

http://codepen.io/bunny10245/pen/WjrVxp . Open the codepen in debug mode, in chrome, with react developer plugin, to see that although props of Textfield gets updated, the props of react input element doesnot get updated.

**Comment by javierordonezcastro** [comment]
Hi, I have the same problem. Did someone find a solution?
Thank you very much

**Comment by lafe** [comment]
I would also be interested in a solution - all workarounds I currently employ are pretty ugly...
