### ISSUE TITLE
Time Picker

### ISSUE THREAD

**Issue by jaitaiwan** [OfficeDev/office-ui-fabric-react#1565]
HI Guys,

There's a closed issue with a time picker but it hasn't been added to the react trello board. One way that could easily address this would be to create a "pokies" style incrementer component which could then be packaged together to create a new time picker component and give an alt version of the date picker:

![fabric timepicker](https://cloud.githubusercontent.com/assets/674765/25228501/05959bc8-2610-11e7-8305-a88fd5e05650.png)

This allows a ton of flexibility, adds a nice (and needed) counter component to fabric and gives a consistent ui for changing time-based values.

**Comment by HdHeini** [comment]
Still a good idea to have a time picker that is consistent with a date picker component, I would really appreciate it.

**Comment by jaitaiwan** [comment]
I'm going to close this issue as I don't think that it's getting any traction.
