### ISSUE TITLE
TagPicker - Add the ability to disable the control

### ISSUE THREAD

**Issue by lszomoru** [OfficeDev/office-ui-fabric-react#1569]
It would be great if a TagPicker component could be disabled. Thanks!

Ladislau

**Comment by aleksandrjPersonal** [comment]
@lszomoru Should all pickers be abled to be disabled or just TagPicker?

**Comment by lszomoru** [comment]
Sorry for not getting back to you on this but I just got back from vacation. Thanks for creating the pull request for this feature request. I see that you have added the property to the base class so that all pickers will have this capability!
