### ISSUE TITLE
"Search" label in SearchBox component is not localized

### ISSUE THREAD

**Issue by shyama1208** [OfficeDev/office-ui-fabric-react#1570]

**Comment by aleksandrjPersonal** [comment]
@micahgodbolt I am taking this bug to mean that we need to move the word 'Search'  into a reference that resolves to the correct translation of 'Search' per user language and country code. I am not seeing any obvious examples in the project doing this already. What are we using to localize our react strings?

**Comment by micahgodbolt** [comment]
@aleksandrjPersonal check out ICalendarStrings

https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Calendar/Calendar.Props.ts#L83

**Comment by aleksandrjPersonal** [comment]
@micahgodbolt Hmm, I see strings={ DayPickerStrings } but I don't see how these strings resolve and get translated to all the other languages. Nor do I see us calling out to a loc service to populate these strings, they appear to be hard coded? What am I missing?

**Comment by micahgodbolt** [comment]
You don't have to worry about the translations, you just have to make sure that the application using the component is able to pass in the proper, translated string


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by aleksandrjPersonal** [comment]
@micahgodbolt  oh, so add 'labelText' to ISearchBoxProps ?

**Comment by micahgodbolt** [comment]
Hah, and so it is! @shyama1208 are we missing something? What do you mean by "localized"? You are referring to the SearchBox component, right?

Sorry for the run around @aleksandrjPersonal. Move on to your next issue until we hear back.

**Comment by mdahamiwal** [comment]
@shyama1208 , fabric doesn't provide string localization yet. We generally pass a localized string to fabric controls wherever we consume. If you are part of VSTS team, refer to how we consume DatePicker control and pass localized strings.

**Comment by shyama1208** [comment]
Yes, I am using 'labelText' props as of now. Was not aware that fabric does not provide localization yet.
Thanks for your responses.
