### ISSUE TITLE
SearchBox does not implement onInput

### ISSUE THREAD

**Issue by r33kan** [OfficeDev/office-ui-fabric-react#1571]
### Bug Report

- __Package version(s)__:  2.21.0
- __Browser and OS versions__: IE11

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal) 

Products/sites affected: SearchBox

#### Describe the issue:

The input element in the SearchBox component still uses onChange instead of onInput (as TextField does #1077) resulting in missed keystrokes and warped input value when the app runs in IE11.

#### Actual behavior:

When typing "fast" keystrokes are missed due to change event handler

#### Expected behavior:

Input text value should be exactly as typed

**Comment by dzearing** [comment]
@mdahamiwal could you make the same change to SearchBox?

**Comment by satbai** [comment]
I am experiencing the same issue but with all browsers instead of just IE11. Also, if you start typing fast it ignores all of the other key strokes but the last one.
