### ISSUE TITLE
Panel: Example page references non-existent Pane control

### ISSUE THREAD

**Issue by MLoughry** [OfficeDev/office-ui-fabric-react#1573]
### Bug Report

- __Package version(s)__: 2.21.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal 

Products/sites affected: Example Fabric site

#### Describe the issue:

The example page for the Panel states the following under its "Don't":
````
Use for experiences where the user needs to interact with the app view. Use a Pane (which pushes content, doesn’t use an overlay, and sits on the same z-index as the rest of the UI) instead.
````

However, no such `Pane` component exists.

**Comment by micahgodbolt** [comment]
Yup. That's no good. Can anyone else think of a good Panel "dont" so that column doesn't have to be empty? @mikewheaton ?

**Comment by mikewheaton** [comment]
Don't modify it to act as a Pane – help us figure out how to properly create a Pane and then open a pull request? ;)

**Comment by kngrace** [comment]
I was attempting to find a Pane component to use in my SPFX webpart and noticed the same reference in the docs which lead me to here.

I'd love to see a pane component similar to the current SharePoint experience:

![image](https://user-images.githubusercontent.com/5940633/30500743-88aa05f8-9a14-11e7-9a66-9f956dfcf3fb.png)

[Here is an example of a built-in pane that is provided by SPFX apps](https://dev.office.com/sharepoint/docs/spfx/web-parts/basics/integrate-with-property-pane) to be used as a configuration pane. The underlying code may help inspire the creation of a Pane. (Note: I believe it's a 'full page' pane and thus doesn't work similarly to the above referenced experience).

My ultimate goal is to combine this Pane with the DetailList component that already exists.

**Comment by erichdev** [comment]
Closing since docs have been updated. @kngrace If you'd like, please open another issue for the feature request so it can be tracked separately.
