### ISSUE TITLE
Panel: allow the ability to interact with underlying surface

### ISSUE THREAD

**Issue by MLoughry** [OfficeDev/office-ui-fabric-react#1575]
I'm attempting to implement a Pane component for OWA that hosts arbitrary content in a pane that shoves aside the main app surface to make room, but still allows interaction with the main app surface.  Due to the architecture, we can't pass non-serializable data (such as a JSX.Element) to component living at the App root, and it's not feasible to force each user of the Pane to register their components next to the App root code.

To solve this, I was using Panel along with an underlying empty div (that only needed to know whether to render or not using serializable data). However, by default, the Panel doesn't allow interaction with the underlying surface due to its usage of FocusTrapZone.

I was able to work around this by setting `isLightDismiss={true}` and using CSS to set the `left` property of the Panel root to be flush with the Panel; however, this feels like a hack workaround.

Should we add a parameter or separate component to explicitly allow interaction with the underlying scenario?

**Comment by mikewheaton** [comment]
We've discussed adding a Pane component before but couldn't come up with a good design for how it should "push" the neighboring surface out of the way. This is definitely something we need to figure out, as we use Panes throughout our products.

**Comment by micahgodbolt** [comment]
Hmm, is there a need for Pane to be a separate control? The inside regions would be the same, it'd just be a difference in the placement in the DOM (and no drop shadow). Would we support the same widths/positions/close buttons etc.

**Comment by mikewheaton** [comment]
The main differences are that you can (optionally) drag to resize a Pane, and that it needs to have a child content area or interact with another component that responds when the Pane opens. As the Pane slides in, the content area needs to shrink at the same time.
