### ISSUE TITLE
Search Box: Pressing escape twice clears the search box text

### ISSUE THREAD

**Issue by vashit** [OfficeDev/office-ui-fabric-react#1579]
https://fabricreact.azurewebsites.net/fabric-react/master/#/examples/searchbox

Type something in search box and 
1) press escape - nothing happens
2) press escape again -  search text cleared

Expected:
on first escape press, focus out of search box. Do not clear the text

**Comment by mdahamiwal** [comment]
@vashit, what is the browser you are using its works fine for me on chrome and IE11.

**Comment by vashit** [comment]
@mdahamiwal  i am trying chrome as well (Version 58.0.3029.110 (64-bit)) reproable on Edge as well for me.

**Comment by erichdev** [comment]
@vashit Are you still experiencing this? I couldn't repro in Chrome or Edge

**Comment by erichdev** [comment]
Closing since I couldn't repro and there hasn't been updates. Please reopen if any issues remain.
