### ISSUE TITLE
MessageBar - Link has the correct styling but cannot be clicked

### ISSUE THREAD

**Issue by lszomoru** [OfficeDev/office-ui-fabric-react#1580]
### Bug Report

- __Package version(s)__: 2.21.0
- __Browser and OS versions__: 57.0.2987.133

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: (if applicable)

#### Describe the issue:

I have a Link component that is placed within a multi-line MessageBar. The Link component has the correct styling but but it cannot be clicked. I have tried replacing the Link component with an "<a>" tag but that results in the same behaviour.

#### Actual behavior:

User cannot click a Link component placed within a MessageBar component.

#### Expected behavior:

User should be able to click a Link component placed within a MessageBar component.

**Comment by micahgodbolt** [comment]
Yup. Pseudo element used for border didn't have proper pointer-events. PR up now.
