### ISSUE TITLE
Persona: Text is not truncated right in RTL

### ISSUE THREAD

**Issue by MirandaGe** [OfficeDev/office-ui-fabric-react#1581]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable)

#### Describe the issue:

Text truncate is not as expected:
![image](https://cloud.githubusercontent.com/assets/16030290/25329693/74387a12-290f-11e7-9c43-4d7c1032a388.png)

#### Expected behavior:

Expect to truncate the right side, not the left side.

### If applicable, please provide a codepen repro:

https://codepen.io/lingge/pen/zwKBGY

**Comment by micahgodbolt** [comment]
Wouldn't RTL only be used with an RTL language? RTL isn't just a way to flip the UI of elements.

**Comment by mikewheaton** [comment]
This is the default browser behavior and makes sense for languages that are read in the right-to-left direction. See [this CodePen](https://codepen.io/mikewheaton/pen/WjoGVx) for a demonstration.

**Comment by MirandaGe** [comment]
Got it. Thank you! 👍
