### ISSUE TITLE
Grouped DetailsList - on updating the row content and scrolling the row gets re-constructed and data is lost

### ISSUE THREAD

**Issue by kanchanverma2407** [OfficeDev/office-ui-fabric-react#1591]
### Bug Report

- __Package version(s)__: 2.20.2
- __Browser and OS versions__: Chrome and Edge

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes, but not sure about the right fix

Requested priority: Blocking

Products/sites affected: VSTS

#### Describe the issue:

In a grouped detailsList, update the row content after the list is rendered. We update the row content to show more content on a user's request. After the content of the row is updated to have some considerable amount of data and the user scrolls down through this content, this particular row is reconstructed and all the data that was updated at run time is lost.

While debugging we found that the virtualization logic which works on scroll to calculate the list pages which are visible, unmounts this particular row/list-page (though its visible and in the viewport at this point) and then reconstructs this row, so only the initial data gets populated and we lose the current state for this row.  (List._onAsyncScroll -> List._updatePages)

#### Actual behavior:

When the user scrolls, the row or list page that is visible on the screen is removed from the DOM and is then reconstructed. So whatever data was present in this row is lost.

#### Expected behavior:

As the user scrolls throw this row content, this row should remain visible and shouldn't be removed/unmounted and constructed again

### If applicable, please provide a codepen repro:

Here is a codePen showing the scenario. Press the “Update last item” button and the content for the last row will be updated to have more data. Now when you scroll down the data will be lost.
http://codepen.io/kverma/pen/OmRbgW?editors=0110

**Comment by cschleiden** [comment]
What do you mean, updated at run time? You should not modify the DOM yourself, that's the whole point of React. 

You want to have a custom component, that is rendered within the grid cell, and then - whenever your external trigger is triggered - that component re-renders itself with the updated information. Then, when the grid updates the row, the component just render its state again.

**Comment by kanchanverma2407** [comment]
Yes, that's what we do in the product code, just to demonstrate that the row is reconstructed instead of being re-rendered I updated the DOM in the codepen.

We have a custom component for the row and this custom component has a state. So, instead of re-rendering this custom component, it is unmounted and mounted again on scroll. Because of this the state of this component is reset to intial state.  It should be just re-rendered when the grid is updated and not unmounted and remounted.

**Comment by kanchanverma2407** [comment]
I have updated the codepen to use a custom component instead. 

http://codepen.io/anon/pen/wdoEGN?editors=0110
Please click on "Expand this row" and scroll down.
