### ISSUE TITLE
Breadcrumb: "Cannot read property 'key' of undefined" seen in console.

### ISSUE THREAD

**Issue by Hardhik** [OfficeDev/office-ui-fabric-react#1593]
### Bug Report

- __Package version(s)__: Current
- __Browser and OS versions__: Chrome, Win10 Creators Update

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: http://dev.office.com/fabric#/components/breadcrumb

#### Describe the issue:

"Cannot read property 'key' of undefined' errors seen in console log on clicking the icons in the breadcrumb. Can be seen at http://dev.office.com/fabric#/components/breadcrumb 

#### Actual behavior:

There are errors seen in the console in Chrome.

#### Expected behavior:

There shouldn't be any errors

### If applicable, please provide a codepen repro:

http://dev.office.com/fabric#/components/breadcrumb
Screenshot:

![image](https://cloud.githubusercontent.com/assets/2673006/25370080/e76e1eec-29a5-11e7-9dd3-61e4026fa1a0.png)

**Comment by mdahamiwal** [comment]
@Hardhik the last example is removed from the latest example pages https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Breadcrumb/examples/Breadcrumb.Basic.Example.tsx. It will reflect on next update to the site. I am closing this one as fixed, feel free to re-activate if it is an issue with component consumption.
