### ISSUE TITLE
Peoplepicker accessibility

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#1611]
Environment: IE11 and JAWS 18
Are you willing to submit a PR to fix? No. I need help
Requested priority: High
When you type, and suggestions appear, we should tell them there are suggestions available. Arrowing down can read the suggestions.

**Comment by betrue-final-final** [comment]
In Narrator, it reads the suggestion when they come up, but still doesn't say that there are any to go to.

**Comment by martellaj** [comment]
Share UI in ODSP is currently getting dinged for this issue.

**Comment by martellaj** [comment]
This issue is fixed everywhere, except for the combo of IE and Narrator.

**Comment by betrue-final-final** [comment]
No longer reproes.
