### ISSUE TITLE
Searchbox: Can't get to clear "X"

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#1616]
Environment: IE11 and JAWS 18
Are you willing to submit a PR to fix? No. I need help
Requested priority: High

Can't navigate to the clear X.
Arrowing right should put the clear X in focus. Let's also make sure that the X control says "Clear text button", or whatever prevailing patterns say.

**Comment by cschleiden** [comment]
Hm.. Escape is not enough?

**Comment by betrue-final-final** [comment]
The clear X clears the text, doesn't exit the control.

________________________________

**Comment by cschleiden** [comment]
Yes, just like Escape when you press it the first time.

When should it put this in focus? Arrow right in a text box is hard to intercept.

**Comment by betrue-final-final** [comment]
Escape should leave the control, not just clear the text. That's why we have that X.

________________________________

**Comment by cschleiden** [comment]
Hit Escape twice.. first time clears the control, second exits it.

**Comment by betrue-final-final** [comment]
I know that it's implemented that way, but there's a reason we have an explicit control. It's just poor design if it's not accessible.

________________________________

**Comment by scriby** [comment]
The screen reader user wouldn't even know there is an x button and would just delete the field contents directly. I don't really think this one needs to be addressed.

**Comment by cschleiden** [comment]
Okay, I understand.

Then back to, how would you reach the X? Tab stop isn't a great idea, imho. And "arrow right" in a textbox is difficult to intercept without messing with people's expectations.

**Comment by cschleiden** [comment]
Good point, can we close this then for now?

**Comment by betrue-final-final** [comment]
Equality is what were shooting for here. Making a screen reader user hit delete X times vs arrow then enter isn't equality.

________________________________

**Comment by betrue-final-final** [comment]
However escape does do this in the Google, so go ahead on this one.

________________________________

**Comment by scriby** [comment]
Screen reader users can use "ctrl + A" then "delete" to clear out the field. Surely anyone who uses the keyboard exclusively already knows this :)

**Comment by betrue-final-final** [comment]
Sure they can. However we really should be diligent in not just the ability to do the same things as sighted users, but also understandability and ease of use.
