### ISSUE TITLE
Dropdown component should have a prop which determines whether no selection is an error state

### ISSUE THREAD

**Issue by harshil93** [OfficeDev/office-ui-fabric-react#1623]
I would like to highlight the dropdown in red if no element from the dropdown is selected.

**Comment by micahgodbolt** [comment]
Do you see this red error state only showing up after the user tries to submit?

**Comment by betrue-final-final** [comment]
I think that the red element would be overkill for merely not filling it out. We have a state for a dropdown that is required to be filled out by the form, but not for just leaving one blank anywhere. Is that what you mean?

**Comment by amadeogallardo** [comment]
@micahgodbolt Possibly related: if the "errorMessage" prop is set, it displays even on initial form-load. Is there a way to control when the error message displays or not? (similarly to TextField, which provides a few handlers such as onGetErrorMessage, validateOnLoad, etc.)
