### ISSUE TITLE
TooltipHost: when tooltip is shown it breaks the word

### ISSUE THREAD

**Issue by madhuv402** [OfficeDev/office-ui-fabric-react#1629]
Tooltip has a style of word-break: break-all, due to this words are broken in between, if we have word-break: none, then this will not happen.

To give an example:
if the text of the tooltip is, This is an example string for tooltip to show.

This text, can be shown as based on the size of the tooltip. you can clearly see the tooltip is broken at the wrong place, let me know if you need a screenshot.
This is an example string for too
ltip to show.

check line 24 in the file
https://github.com/OfficeDev/office-ui-fabric-react/blob/c64c8dba39dc2b8fa35bbe185ae564753e649f16/packages/office-ui-fabric-react/src/components/Tooltip/Tooltip.scss

**Comment by micahgodbolt** [comment]
This was just fixed in #1630
