### ISSUE TITLE
CSS naming convention

### ISSUE THREAD

**Issue by wellbeck190** [OfficeDev/office-ui-fabric-react#1634]
Hi, I am developing a project based office-ui-fabric-react.
I want to know css naming convention of office-ui-fabric-react.

Help me, thanks!

**Comment by micahgodbolt** [comment]
We are currently using CSS Modules for applying css styles. So if you are writing a new component then css is automatically scoped to the component, so you'd be able to do the following...

```css
.root {}
.rootIsSelected{}
.labelIsActive {}
```
Basically, no need to have component name in class. Camel case everything. Modifiers are IsActive/IsOpen etc and should be combined with the element you are applying it to.

If you aren't writing new modules and only interacting with existing components, we use the following approach.

```css
.ms-Button
.ms-ColorPicker
.ms-ColorPicker-thumb
.ms-ChoiceField-innerField
```

All classes are prefixed with .ms-, and then we use a BEM style format. So Block name is camel case with first level capitalized. Then element name is regular camel case. 

Hope this helps!
