### ISSUE TITLE
Pickers, PeoplePicker, DatePicker : Click behaviour is inconsistent

### ISSUE THREAD

**Issue by bharay** [OfficeDev/office-ui-fabric-react#1635]
### Bug/Suggestion

- __Package version(s)__: (latest)

#### Priorities and help requested :

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal) 

#### Describe the issue:

Currently the pickers behave differently when clicked on them. For eg. the date picker opens the calender to choose a date, but Peoplepicker and other Pickers doesn't. So when these pickers are used together to create a set of filters, say datepicker to filter on date and peoplepicker to filter on author it makes the UX not so great.

Can they also be made to open on click, so that one can show the Most Recently Used people/documents/tags if they want. Basically a click on the picker combobox should toggle the dropdown like in datepicker.

**Comment by bharay** [comment]
Also, when text input is disabled for date picker, I expect it to work similar to dropdown. That clicking on the combobox opens the calender. And clicking again closes it. Currently it doesnot close.

**Comment by betrue-final-final** [comment]
I agree the “Zero click” suggestions menu would be nice.

**Comment by betrue-final-final** [comment]
That makes sense.

**Comment by kristoferbrown** [comment]
@bharay, the people picker now shows suggestions on first click. The base picker examples do not show suggestions because this isn't the default behavior for them, but this behavior is supported by base picker.

**Comment by bharay** [comment]
@kristoferbrown  Seems a small part of the request is missed. To make datepicker behave like dropdown when textinput is disabled. i.e, when datepicker is open and the combo box is clicked again close it.
