### ISSUE TITLE
DetailsList: broken borders in high contrast

### ISSUE THREAD

**Issue by prmittal** [OfficeDev/office-ui-fabric-react#1636]
DetailsList:
![image](https://cloud.githubusercontent.com/assets/11937034/25475815/a8bafde4-2b55-11e7-9be8-23b02b2f7cb3.png)

Dropdown **Fixed:**
![image](https://cloud.githubusercontent.com/assets/11937034/25475733/64105018-2b55-11e7-9d29-7fa3bef2dd31.png)

**Comment by hross** [comment]
The dropdown appears to have been fixed in this PR: #1718

**Comment by mdahamiwal** [comment]
Even the details list is fixed in latest master. Its not updated at https://dev.office.com/fabric#/components/detailslist

![image](https://cloud.githubusercontent.com/assets/12109362/25842167/afc2e7cc-34c0-11e7-9271-54e74fcad37b.png)

**Comment by betrue-final-final** [comment]
Alignment seems to be off in detailslist now. Is that part of the change?
