### ISSUE TITLE
DetailsList element selection doesn't remain in list's viewport after PageUp and PageDown

### ISSUE THREAD

**Issue by shaaradmsft** [OfficeDev/office-ui-fabric-react#1637]
### Bug Report

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: (if applicable)

#### Describe the issue:

In DetailsList, if there are large number of elements, scrolling through the elements with PageDown or PageUp doesn't change the selected element. e.g. if first list element is selected, and PageDown is pressed a few times, followed by down arrow for fine selection, the selection actually goes to second element and the list scrolls all the way up. This can be easily reproduced on https://dev.office.com/fabric#/components/detailslist

#### Actual behavior:

PageUp/PageDown doesn't change the selected row.

#### Expected behavior:

PageUp/PageDown should change the selected row everytime so that the selected row remains in the viewport always.

**Comment by cschleiden** [comment]
Why should page up/down change selection?

**Comment by shaaradmsft** [comment]
@cschleiden, First of all, this is from an accessibility perspective, especially keyboard-only navigation.

Because once you PageDown enough times, the selected element goes out of the currently shown items in the list. In a purely keyboard-driven selection approach, there is no easy way otherwise to select an element that's 100-200 elements away from the current selection apart from long-pressing the arrow keys.

If a change is made to always keep the currently selected element always among one of those currently being shown, it's very easy for a keyboard-only user to do few page downs and few down arrows to select any element quickly.

**Comment by Hardhik** [comment]
@cschleiden, Can you please update the tags and status.
