### ISSUE TITLE
Focus lost after Dialog close

### ISSUE THREAD

**Issue by benkaiser** [OfficeDev/office-ui-fabric-react#1651]
### Bug Report

- __Package version(s)__: (latest)
- __Browser and OS versions__: (all)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High

#### Describe the issue:

https://github.com/OfficeDev/office-ui-fabric-react/blob/78e462bc936350fee2806ee0e70d523e8deee9b5/packages/office-ui-fabric-react/src/components/Dialog/Dialog.tsx

This file looks for a bunch of FocusTrapZone props in it's props, but those props aren't defined on the Dialog component.

#### Actual behavior:

No control over focus after Dialog closes.

#### Expected behavior:

I should be able to pass these properties to control the FocusTrapZone:

```
elementToFocusOnDismiss
ignoreExternalFocusing
forceFocusInsideTrap
firstFocusableSelector
closeButtonAriaLabel
isClickableOutsideFocusTrap
```

**Comment by erichdev** [comment]
`IDialogProps` extends `IAccessiblePopupProps` to give Dialog access to those focus properties. Please reopen if there are any issues
