### ISSUE TITLE
Panel close button has large right margin and is not to design spec

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#1664]
### Bug Report
Are you willing to submit a PR to fix? (Yes)

Requested priority: (Low) 

- It's in a 40px box, when it should be 44px 
- There's an 8px right margin, when it should be 4px
- The size is 16px when it should be 20px.

**Comment by aleksandrjPersonal** [comment]
![panelspec](https://cloud.githubusercontent.com/assets/7284230/25597705/36aaeb3c-2e85-11e7-870d-51f2b8fdf529.png)
