### ISSUE TITLE
Pivot styling broken by Button refactorings

### ISSUE THREAD

**Issue by cschleiden** [OfficeDev/office-ui-fabric-react#1665]
Urgs.. that's a fun one:
 
![image](https://cloud.githubusercontent.com/assets/2201819/25592277/07413526-2e6d-11e7-8132-f043471f7ad0.png)

Notice how the underline is all wrong? This happens because the padding of the button isn't 8px as it's supposed to be, but 4px... Looking at the styles:
![image](https://cloud.githubusercontent.com/assets/2201819/25592286/16ab1824-2e6d-11e7-85c1-2f073435663e.png)

`link_b88..` is the Pivot style which should be applied. However, since the tab is now a `CommandButton` the CommandButton styles are also brought in: `.root_0bd..` .. in our product they seem to be placed in the document in a different order than on the fabric website, and since they have the same specificity, the order in the document matters, and here, unfortunately, `CommandButton` seems to win.

**Comment by micahgodbolt** [comment]
Seems to be fixed now. http://codepen.io/micahgodbolt/pen/bWrgEb

![image](https://cloud.githubusercontent.com/assets/1434956/25671538/4505e2b6-2fe5-11e7-8de6-4c6fd7ec624d.png)

**Comment by cschleiden** [comment]
@micahgodbolt Could you share the codepen? I see it with the AMD build

**Comment by micahgodbolt** [comment]
http://codepen.io/micahgodbolt/pen/bWrgEb

**Comment by cschleiden** [comment]
Repro case: https://codepen.io/cschleiden/pen/NjvamV

The order matters.. I can easily reproduce with AMD loading
