### ISSUE TITLE
Documentation for Types

### ISSUE THREAD

**Issue by fergiemcdowall** [OfficeDev/office-ui-fabric-react#1677]
### Bug Report

Documentation for `Types`. For example here: https://dev.office.com/fabric#/components/contextualmenu

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: API Documentation for Fabric UI: https://dev.office.com/fabric#/components

#### Describe the issue:

I am trying to work out how to position a contextual menu (right click -> menu pops up under cursor), however since API docs for IPoint (and all other `Types`) seem to be unavailable, there is no obvious way to find out how to do this.

#### Actual behavior:

When browsing https://dev.office.com/fabric#/components/contextualmenu I can see that I need to provide an `IPoint` to `targetPoint`. However IPoint is not linked to, and there doesn't seem to be any documentation available.

#### Expected behavior:

I expect to be able to

 * navigate to the API documentation for `IPoint`
 * find out how to use `targetPoint` to position a Component

**Comment by fergiemcdowall** [comment]
related: http://stackoverflow.com/questions/43741251/fabric-ui-how-do-i-position-a-contextmenu

**Comment by fergiemcdowall** [comment]
(In the meantime- it would be great to actually find out how to position a ContextMenu- either here or on the SO link above)

**Comment by micahgodbolt** [comment]
IPoint has it's own TS file at [packages/utilities/src/IPoint.ts](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/utilities/src/IPoint.ts). But I 100% agree. We are discussing how we can improve our documentation when so many types are defined outside of the component.
