### ISSUE TITLE
DetailsList: when focusing out, the focus css remains

### ISSUE THREAD

**Issue by satbai** [OfficeDev/office-ui-fabric-react#1690]
Repro steps:

1. Use the tab key to navigate to a list item - its background turns blue on focus
2. Click the focus away from the list
3. The list item is still blue

Expected behavior:
3. The list item that was blue on focus turns back to the color that it originally was

**Comment by micahgodbolt** [comment]
I can't seem to repro this. Can you supply a screenshot/animated gif of what your're seeing?

**Comment by satbai** [comment]
1. on focus through keyboard navigation:
![image](https://cloud.githubusercontent.com/assets/24945574/25672270/b27caf8a-2fe7-11e7-922f-82026d596285.png)
2. clicked the focus to a different component:
![image](https://cloud.githubusercontent.com/assets/24945574/25672239/962eef28-2fe7-11e7-9d71-c6b9507d09dd.png)


It looks like the is-selected class is still present when you've clicked the focus away.

**Comment by micahgodbolt** [comment]
I think the point is that the blue is not "focus" but, as the class implies, "selected". So if you click away, it should stay selected.  Does this make sense? I can check with a designer if you think this behavior is incorrect.

**Comment by satbai** [comment]
Ah, I see. If it's by design I'm also fine with it!
