### ISSUE TITLE
Dropdown: Bug-Bash

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#1700]
1. Placeholder text color? 333 or closer to browser input placeholder
2. Disabled is not focusable
3. Missing variants: 
  - in situ
  - Multichoice 
  - Multi choice with fill-in

**Comment by mikewheaton** [comment]
The multichoice variant now exists, but the in-situ variant is still missing. This is documented in the [Adobe XD toolkit](https://aka.ms/fabric-toolkit):

![image](https://user-images.githubusercontent.com/1382445/39604363-b65424d0-4ee0-11e8-937d-b762338ce960.png)

**Comment by yolena** [comment]
The in-situ variant for drop down component is missing from the code library. @mikewheaton, let us know how soon this can be resolved. We have a project that is currently relying on this component.
cid:image001.png@01D3E203.A41623D0
