### ISSUE TITLE
MarqueeSelection: Mobile is not supported

### ISSUE THREAD

**Issue by kristoferbrown** [OfficeDev/office-ui-fabric-react#1701]
### Bug Report

- __Package version(s)__: Current
- __Browser and OS versions__: Android Chrome and iOS Safari

#### Describe the issue:

Marquee selection does not work in mobile browsers. Discussion is needed to decide how to handle when to scroll and when to marquee select.

### If applicable, please provide a codepen repro:
Repros in current website.

**Comment by brodyberg** [comment]
Rough, I just belatedly discovered this. Is there something I can do to help?

**Comment by micahgodbolt** [comment]
It'd be useful to find examples of marquee selection worked in other mobile apps/websites.

**Comment by dzearing** [comment]
I don't think we plan on doing anything here. I don't know of any mobile apps that use marquee selection. Typically there is a selection model of press and hold to enable and tapping things to select.
