### ISSUE TITLE
Website: Button icon should only be displayed as a property, not example

### ISSUE THREAD

**Issue by angallison** [OfficeDev/office-ui-fabric-react#1703]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) 

Products/sites affected: (if applicable)

#### Actual behavior:
Standard and Primary Buttons screen capture:
https://1drv.ms/i/s!AgOQ8ZpN0-ilg9xliOBTdU_ILYW-jA

#### Expected behavior:
Icon should not be displayed as an example on the website. The standard button should not have an icon in the example. Can we display the icon as a property only?

**Comment by mikewheaton** [comment]
Agreed, we should remove the icon from the default button example.
