### ISSUE TITLE
Website: Button text not vertically-aligned in the button

### ISSUE THREAD

**Issue by angallison** [OfficeDev/office-ui-fabric-react#1706]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) 

Products/sites affected: (if applicable)

#### Describe the issue:

Here's a screen capture of the buttons from the Fabric Web site:
https://1drv.ms/i/s!AgOQ8ZpN0-ilg9xliOBTdU_ILYW-jA

#### Actual behavior:

Vertically center the text within the button

**Comment by micahgodbolt** [comment]
What browser are you using? It looks like this on mine 

![image](https://cloud.githubusercontent.com/assets/1434956/25684688/a69dc9a8-3017-11e7-9b0e-bfb23f74cba5.png)

**Comment by micahgodbolt** [comment]
Here is yours for comparison

![image](https://cloud.githubusercontent.com/assets/1434956/25684704/bd3cb138-3017-11e7-8a15-6293ebe35978.png)

**Comment by micahgodbolt** [comment]
Heh, seems to be happening on high rez screens. 

xps 13

![image](https://cloud.githubusercontent.com/assets/1434956/25684752/029f74fe-3018-11e7-9875-4008c6738bba.png)

dell monitor 

![image](https://cloud.githubusercontent.com/assets/1434956/25684758/0889aa1a-3018-11e7-8775-52978125baeb.png)

**Comment by kristoferbrown** [comment]
This also occurs on any resolution monitor if you Ctrl+/- to zoom in. Seems to me like this is a quirk with font rendering. All of our rules say it should be vertically centered, and at default zoom it IS vertically centered.

In Segoe UI, the text draws too low in the button. However, if I change the font to something else, say default sans-serif, the text draws a few pixels too high in the button. 

I don't think there is really much, if anything, we can do about this.

**Comment by micahgodbolt** [comment]
agreed. the joys of font rendering at multiple resolutions
