### ISSUE TITLE
Buttons: Add 'active state' prop for buttons

### ISSUE THREAD

**Issue by Dammic** [OfficeDev/office-ui-fabric-react#1717]
Hello,

I would like to know if the active state for buttons is somewhere on the radar.
It could work like in react-bootstrap: https://react-bootstrap.github.io/components.html#buttons-active
One would pass a prop which would define if the button is pressed or not (activated).

**Comment by micahgodbolt** [comment]
What's the usecase of specifying that a button is active?

**Comment by Dammic** [comment]
One could make icon buttons which would symbolize selected user options (like filters) in an user-friendly way (as an alternative to checkboxes)
Example usecase: buttons for video quality/length filters, which the user could toggle to active, in form of buttons.
Ex. [HD], [Short]
I personally think that would make a good addition.

**Comment by micahgodbolt** [comment]
Yup...now I remember that use case. 100% necessary for toggleble buttons. We're doing quite a bit of work on buttons, and I know that active state is one of the many things on our list. Hopefully we can get it in sooner than later.

**Comment by micahgodbolt** [comment]
looks like this was completed in  #1795
