### ISSUE TITLE
Items which come when we drop open the Dropdown have role="menu"

### ISSUE THREAD

**Issue by mee-1993** [OfficeDev/office-ui-fabric-react#1719]
### Bug Report

- __Package version(s)__: (2.20.3)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? ( No)

Requested priority: (Normal) 

Products/sites affected: (if applicable)

#### Describe the issue:
https://dev.office.com/fabric#/components/dropdown
The role assigned to dropdown items is "menu" . 

#### Expected behavior:
We should move to a role which is more appropriate .role should be "option"

**Comment by mdahamiwal** [comment]
@mee-1993, this is fixed in latest master. Must have been an intermittent issue.

**Comment by betrue-final-final** [comment]
Thank you so much.
