### ISSUE TITLE
CommandBar: Losing focus in CommandBar Items

### ISSUE THREAD

**Issue by bhaveshbhati** [OfficeDev/office-ui-fabric-react#1720]
### Bug Report

- __Package version(s)__: (2.23.3)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) 

Products/sites affected: (if applicable)

#### Describe the issue:
Actions are done via keyboard.
I have a scenario where the command bar item opens a dialog box. Now dialog box can directly be opened by a parent item or a child item. If the parent item (say Upload ) opens the dialog and closes it, focus stays on the parent item. But if the child item (say New -> Calendar Event) opens the dialog and closes it, focus goes to the first focusable item in the page (say I AM Button). Shouldn't it stay over (New) ?

![image](https://cloud.githubusercontent.com/assets/1016447/25698911/7ec9291e-30de-11e7-8e61-2b5b1bf97310.png)

[See codepen for more details]

#### Actual behavior:

Focus stays on the first focusable item in the page.

#### Expected behavior:

Focus stays on the parent command.

### If applicable, please provide a codepen repro:

http://codepen.io/anon/pen/ZKGRBQ

**Comment by dzearing** [comment]
We took a look at this and totally understand the requirement and shortcomings of not having generalized focus management out of the box. It seems completely worthy of solving in a generalized way.

I'd like to propose something like this:

In utilities, we expose a focus helper which does this:

`pushFocusableParent` - a method, called by things that are going to open menus and such. for example, menus and dialogs can, prior to mounting, note the active element and call the api.

When the menu or dialog disappears, focus goes to body. We detect this, and in a short throttled time of idling there, we try to restore focus. We start at the top of the stack, and if the element exists, we set focus. If not, we pop from the stack.

This logic could also be pretty elaborate; for example another case is say in a focus zone, we remove an element. The logic could track active focus, and on restoration, try to find an element in the same heirarchy/indexed position. If that item is focusable, focus is set. If not, it can then proceed with the stack traversal logic above.

I think that's the right way to address this sort of issue. You open a menu from a button. The button needs to be pushed on the stack as a focus candidate. From the menu, you open another submenu. The originating menu item needs to be pushed. From there, you open a dialog. Again, the originating menu item needs to be pushed. The dialog opens, the menus disappear. You close the dialog. Focus goes to body. The logic kicks in. There is no dialog. We start popping from the stack. There is no submenu 2. There is not submenu 1. There is only the originating button. Set focus to that.
