### ISSUE TITLE
Fabric react components styling

### ISSUE THREAD

**Issue by ecoukraine** [OfficeDev/office-ui-fabric-react#1742]
Hi guys,

would you be kind to consult me, how to style fabric with react.

The Fabric with React Get started documentation https://dev.office.com/fabric#react says I need only this fabric.min.css styles. 
The Fabric JS Get started documentation says I need  fabric.min.css and fabric.components.min.css.

When I tried to include fabric.components.min.css for Fabric with React, some components do not work correctly.

Should I also include fabric.components.min.css with Fabric React?

Thank you

**Comment by mikewheaton** [comment]
No, you should not include `fabric.components.min.css` when using Fabric React. That file contains the styles for [Fabric JS](https://github.com/OfficeDev/office-ui-fabric-js), which is a separate component project.

It looks like our documentation needs to be updated, as the [Get Started](https://dev.office.com/fabric#/get-started) page does not mention adding a reference to [Fabric Core](https://github.com/OfficeDev/office-ui-fabric-core) on the page. This is necessary for the fonts and icons to load.

Try adding this to your page:

```
<link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/5.1.0/css/fabric.min.css">
```

**Comment by ecoukraine** [comment]
Hi Mike, thank you.
