### ISSUE TITLE
TextField: broken font styles

### ISSUE THREAD

**Issue by fantua** [OfficeDev/office-ui-fabric-react#1763]
### Bug Report

- __Package version(s)__: latest

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Blocking

#### Describe the issue:

After update to latest version `TextField` font styles are broken.

#### Actual behavior:

Font size is 11px: http://prntscr.com/f6k9l7

#### Expected behavior:

14 px

**Comment by dzearing** [comment]
Patched and publishing now.
