### ISSUE TITLE
ChoiceGroup: Allow for custom rendering of options

### ISSUE THREAD

**Issue by MLoughry** [OfficeDev/office-ui-fabric-react#1765]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes. I need this before we ship, but we're pushing against a deadline; if someone is able to pick this up, I'd appreciate it. Otherwise, I can get to it later in our dev cycle.

Requested priority: Normal

#### Describe the issue:

I have need to display a dropdown within a ChoiceGroup choice, like so:
![image](https://cloud.githubusercontent.com/assets/20823465/25963838/9b573ebe-3637-11e7-9505-cde03cdb8e5f.png)

However, there's no way to do this currently. There should be a way to custom-render a choice.

**Comment by micahgodbolt** [comment]
@MLoughry take a look at #1836 and tell me if that'd work for you.

**Comment by micahgodbolt** [comment]
![image](https://cloud.githubusercontent.com/assets/1434956/26328907/c06145e0-3ef9-11e7-9a0f-9a021ce24f46.png)
