### ISSUE TITLE
PeoplePicker does not deal with promise properly

### ISSUE THREAD

**Issue by Fensterbank** [OfficeDev/office-ui-fabric-react#1774]
### Bug Report

- __Package version(s)__: any
- __Browser and OS versions__: any

#### Describe the issue:

`onResolveSuggestion` may return a promise.
If the promise is resolved while the PeoplePicker has already been unmounted, an exception `TypeError: this.input is null` is thrown.
This issue looks similar than #1045.

#### Actual behavior:

Error is thrown because this.input is not existing anymore in DOM if the promise is resolved after the component has been unmounted.

#### Expected behavior:

Component should use `componentWillUnmount` and deal with resolved promises at any time.

**Comment by erichdev** [comment]
Closing because it seems the root of this issue is discussed here https://github.com/OfficeDev/office-ui-fabric-react/issues/1202

Please reopen if this is a separate issue that still exists
