### ISSUE TITLE
DetailsRow needs to support NativeProps

### ISSUE THREAD

**Issue by shadyysf** [OfficeDev/office-ui-fabric-react#1775]
### Bug Report

- __Package version(s)__: (2.25.1)
- __Browser and OS versions__: (All browsers, Windows 10)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
Yes.

Requested priority: (Blocking, High, Normal, Low) 
High.

Products/sites affected: (if applicable)
Visual Studio Team Services/ Team Foundation Server.

#### Describe the issue:

[DetailsRow](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.tsx#L184) needs to support native properties so we can support different "aria-" attributes for accessibility for custom scenarios. I see this pattern is already implemented for other fabric components see [button](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx#L89) and the [prefixes](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/utilities/src/properties.ts#L230-L231).

#### Actual behavior:

There's not way to set arbitrary "aria-" attributes on DetailsRow.

#### Expected behavior:

I should be able to pass in bound property values for "aria-" attributes.

**Comment by shadyysf** [comment]
I really need aria-expanded so I would also be happy adding only this capability.

**Comment by cschleiden** [comment]
Sounds like a good change to me.
