### ISSUE TITLE
Add support for fabric tooltips in context menu

### ISSUE THREAD

**Issue by saritwik** [OfficeDev/office-ui-fabric-react#1777]
For accessibility title attributes in contextmenu needs to be replaced with a office fabric tooltip.

For this I want to wrap the content in each item with tooltip host component. Will create PR if approved..

**Comment by micahgodbolt** [comment]
This might need some design consideration. All those tooltips might make it hard to interact with the contextual menu.

**Comment by saritwik** [comment]
suggested code change - Wrapping the content inside li tag with tooltip host, see preview of change below, also added a gif of the behavior

![image](https://cloud.githubusercontent.com/assets/11751347/26019958/7b40c56c-372e-11e7-86a8-25da4a6d267b.png)

![](http://g.recordit.co/Qdo3KlO2Ul.gif)

**Comment by betrue-final-final** [comment]
Hi saritwik,
I'm the Fabric team accessibility champ, and I think that it's great that you are trying to think inclusively on our products! However, in this case, the tooltip will not add any more information than expected by screen reader or non-screen reader users. Tooltips in menus in fact tend to hamper those who have manual dexterity issues by getting in the way of other items. Having said this, I don't recommend adding these tooltips to context menus.

**Comment by saritwik** [comment]
thanks for your input. I will discuss this is with our accessibility champs and close on this.


Thanks

Ritwik


________________________________

**Comment by betrue-final-final** [comment]
Is there a particular reason why you would add tooltips? Is this for screen reader support?

**Comment by saritwik** [comment]
This has come from an org level push to replace title with office fabric tooltips. Screenreader is one of the reasons why


- Ritwik


________________________________

**Comment by cschleiden** [comment]
I strongly believe the fix here should not be an engineering fix, but a product change to just not require tooltips on context menus.

**Comment by betrue-final-final** [comment]
I don't think you need visual tooltips to have helper text read out by a screen reader. Help me understand what this thinking is? What do you mean by replacing the title? Who are your accessibility champs? I would love to discuss this with them.

**Comment by erichdev** [comment]
Seems the consensus is that adding Tooltips would not aid accessibility. Closing for now. @saritwik please reply if you have any updates and would like to continue discussion
