### ISSUE TITLE
DatePicker: Add support for limiting selectable dates

### ISSUE THREAD

**Issue by WesselKuipers** [OfficeDev/office-ui-fabric-react#1782]
Currently it's always possible to select any date when using the DatePicker.

In certain scenarios it's desirable to limit which dates can and can't be selected. 
This does however not seem to be supported currently.

Ideally the non-selectable dates would be greyed out, perhaps based on whether the validation method returns truthy or falsy or a range of dates.

**Comment by russgove** [comment]
+1 this feature request

**Comment by kristoferbrown** [comment]
The date picker supports limited date ranges now. See the example on the documentation page: https://developer.microsoft.com/en-us/fabric#/components/datepicker
