### ISSUE TITLE
Different dismiss behavior on callout for chrome and firefox

### ISSUE THREAD

**Issue by FrankLiuMS** [OfficeDev/office-ui-fabric-react#1797]
### Different dismiss behavior on callout for chrome and firefox.

- __Package version(s)__: (2.20.2)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? ( No)

Requested priority: (Normal) 

Products/sites affected: (if applicable)

#### Describe the issue:

 Put command bar inside callout, and click that command bar, it will trigger _dismissOnLostFocus in CalloutContent. Watch ev.target variable. In chrome, its type is window, while in firefox, it is HtmlDocument. The code in firefox will continue to call dismiss and cause the callout closing.

#### Actual behavior:

The callout closes when clicking command bar inside in firefox.

#### Expected behavior:

The callout stays open.

**Comment by erichdev** [comment]
Could not repro. Closing. Please reopen if you are still experiencing this issue, and please provide a Codepen if possible.
