### ISSUE TITLE
PeoplePicker: Home/End Key does not work in people picker

### ISSUE THREAD

**Issue by MirandaGe** [OfficeDev/office-ui-fabric-react#1803]
### Bug Report

- __Package version(s)__: any
- __Browser and OS versions__: any

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: People web part

#### Describe the issue:

Home/End key does not work in input area of people picker

### If applicable, please provide a codepen repro:

http://codepen.io/lingge/pen/MmgbBG

**Comment by micahgodbolt** [comment]
It's working for me. Are you expecting something else to happen?

![peoplepicker](https://cloud.githubusercontent.com/assets/1434956/26323693/b8260c86-3ee4-11e7-9274-706f7bb9119e.gif)

**Comment by ipip2005** [comment]
@micahgodbolt 
duplicate one
#1201

**Comment by MirandaGe** [comment]
When editing text, I am expecting the home/end key also works for edit text.

**Comment by MirandaGe** [comment]
Tested and found the issue has been fixed. Thank you!
