### ISSUE TITLE
Searchbox: border not visible in high contrast

### ISSUE THREAD

**Issue by savenkat** [OfficeDev/office-ui-fabric-react#1811]
**Bug Report**
•Package version(s): latest
•Browser and OS versions: IE11 and Edge

Searchbox has missing borders in High Contrast Black/White:
![searchbox_hc_black](https://cloud.githubusercontent.com/assets/24317620/26193937/64fe9914-3bd4-11e7-96dd-c9a20f98d722.PNG)

Although it works in High Contrast 1 or 2 modes
![searchbox_hc_1](https://cloud.githubusercontent.com/assets/24317620/26194010/97c8e9c6-3bd4-11e7-837a-4e45416fc1ba.PNG)

The issue can be seen in HC mode at https://fabricreact.azurewebsites.net/fabric-react/master/#/examples/searchbox

**Comment by micahgodbolt** [comment]
THis looks to be resolved in #1807
