### ISSUE TITLE
Custom header cell rendering in DetailsList

### ISSUE THREAD

**Issue by irvalchev** [OfficeDev/office-ui-fabric-react#1814]
It will be useful to have custom rendering of the column headers in the DetailsList

**Comment by micahgodbolt** [comment]
Can you be specific about what you'd like to change? The detailsHeader is a pretty complex child component. Are you looking for style changes only, or actual functionality?

**Comment by irvalchev** [comment]
Currently there are onRenderItemColumn and onRenderRow methods, so you can choose how to render the content. It will be useful to have similar onRenderHeader on a column level, so it is possible to specify how to render the header content.

**Comment by cbairy** [comment]
Any solutions on how to render html instead of string in column header?

**Comment by micahgodbolt** [comment]
Nothing yet @cbairy.

**Comment by cbairy** [comment]
We can solve this by overriding the IColumn interface, like
IColumnExtended extends IColumn {
    name: any;
}

And we can provide JSX component to column configuration like
{
    key: 'key1',
    name: (<span className="customClass">{nameOfHeader}</span>)
    fieldName: 'fieldName'
}

**Comment by hemao612** [comment]
i meet the same problem, are there any solution now?
