### ISSUE TITLE
Dropdown component border does not render properly in Edge on Win10 in high contrast mode

### ISSUE THREAD

**Issue by pkuma-msft** [OfficeDev/office-ui-fabric-react#1815]
### Bug Report

- __Package version(s)__: (Latest)
- __Browser and OS versions__: (Edge on Windows 10)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal) 

Products/sites affected: (Dropdown component in high contrast mode)

#### Describe the issue:

In high contrast mode, the dropdown components border does not render properly on Edge (running on Win10 in high contrast mode)

Steps:
1) Go to http://dev.office.com/fabric#/components/dropdown in Edge on Windows 10
2) Press left-Shift + left-Alt + PrintScreen to toggle high contrast mode
3) Notice the borders on Dropdown control, the borders are clipped near the chevron

#### Actual behavior:

Borders are clipped near the chevron

#### Expected behavior:

Border should render properly

#### Repro screenshot
![image](https://cloud.githubusercontent.com/assets/13727302/26203845/7186cc26-3bfa-11e7-9d9f-0a9a0dad15a4.png)

**Comment by betrue-final-final** [comment]
I thought this was just fixed. Is there a regression? 
Here's a previous completed PR https://github.com/OfficeDev/office-ui-fabric-react/pull/1718

**Comment by mdahamiwal** [comment]
@betrue-final-final, whats the frequency of updating http://dev.office.com/fabric#/components ? Looks like it is still running older fabric version. We really need an endpoint which gets updated with every fabric release. Even https://fabricreact.azurewebsites.net/fabric-react/master/ runs with older version. 

@pkuma-msft, this change is already pulled in VSTS latest master with recent fabric upgrade. It should be fixed.

**Comment by betrue-final-final** [comment]
I'm not sure how frequent it gets updated but my guess is weekly. @battletoilet would know more.

**Comment by pkuma-msft** [comment]
Thanks @mdahamiwal, @betrue-final-final .. I had assumed that http://dev.office.com/fabric is running the latest release. I will close this issue and verify in VSTS master.
