### ISSUE TITLE
SearchBox component: Border does not render in high contrast mode (high contrast + edge + win10)

### ISSUE THREAD

**Issue by pkuma-msft** [OfficeDev/office-ui-fabric-react#1830]
### Bug Report

- __Package version(s)__: (latest)
- __Browser and OS versions__: (Edge browser on Windows 10)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal) 

Products/sites affected: (SearchBox component)

#### Describe the issue:

Test environment: Edge browser running on Windows 10 in high contrast mode

**Repro steps**
1. Press left-Shift + left-Alt + PrtScreen to enable/toggle high contrast mode in Windows 10
2. Navigate to https://dev.office.com/fabric#/components/searchbox
3. Observe the search box border.. there is no border

#### Actual behavior:

There is no border for search box component
![image](https://cloud.githubusercontent.com/assets/13727302/26304473/271637e6-3f09-11e7-8e1a-0c996759cb51.png)

#### Expected behavior:

In high contrast mode, the search box control should show a border.

**Comment by micahgodbolt** [comment]
This was just addressed in #1816
