### ISSUE TITLE
Horizontal Scroll bar Never shown for detailsList

### ISSUE THREAD

**Issue by vashitaArora** [OfficeDev/office-ui-fabric-react#1832]
### Bug Report

- __Package version(s)__:2.10.3
- __Browser and OS versions__: All

Are you willing to submit a PR to fix? No. Dont know the fix. But this is a recent break

Requested priority: High 

#### Describe the issue:

- Create a Details List such that there is need of a horizontal scroll bar (or zoom in sufficiently)

#### Actual behavior:

- scroll bar not visible
- keyboard arrows dont work either

#### Expected behavior:

Horizontal scrollbar should come when required

### If applicable, please provide a codepen repro:

can be easily seen on Fabric demo site: 
https://fabricreact.azurewebsites.net/fabric-react/master/#/examples/detailslist
OR on codepen
http://codepen.io/anon/pen/eWbZLX?editors=0110

**Comment by micahgodbolt** [comment]
I went back as far is 2.0.1 and this appears to be the default behavior. Can you tell me at which release this was working as you expected?

http://codepen.io/micahgodbolt/pen/EmGmmM?editors=0110

**Comment by micahgodbolt** [comment]
This appears to be working as it has since at least 2.0

There isn't a scroll bar, but I was able to keyboard to the right, or use horizontal mouse scrolling. 

http://codepen.io/micahgodbolt/pen/EmGmmM?editors=0110

**Comment by vashitaArora** [comment]
i dont have the version number till when it worked (but it was definitely 2.x). but in the current example you shared, you are able to navigate because of menu button. remove all the menu buttons, say just a list of labels

http://codepen.io/anon/pen/eWbZLX?editors=0110


also if you can let me know if there is a way to use an older version of office fabric on codepen, i cna myself try some older versions and check. irrespective of previous behavior,we should have some way for the users to see columns out of viewport

**Comment by micahgodbolt** [comment]
You can set the fabric version in the unpkg URL string

![image](https://cloud.githubusercontent.com/assets/1434956/26366274/4c32e1f0-3f9f-11e7-900b-971d6b93cd9a.png)
