### ISSUE TITLE
office-ui-fabric-react not rendering SharePoint themes in SharePoint hosted app 

### ISSUE THREAD

**Issue by szulfiqar** [OfficeDev/office-ui-fabric-react#1839]
### Bug Report

- __Package version(s)__: (1.0)
- __Browser and OS versions__: (Chrome and Windows)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? ( No)

Requested priority: (High) 

Products/sites affected: (if applicable)

#### Describe the issue:

I am using office-ui-fabric-react in SharePoint hosted app, i have installed react, react-dom and office-ui-fabric-react packages using NPM, when i deploy it to my developer site and run my app, it opens up with components having blue color while my SharePoint theme has green color in it. While when i create same functionality app in SharePoint framework here office-ui-fabric-react is rendering components colors according to the theme. Attached is the image where  buttons, list and icons are in blue color, while they should be green. 

![issue](https://cloud.githubusercontent.com/assets/27857126/26343122/32e83bf4-3fb4-11e7-8e0f-a54466c6a650.PNG)
.

#### Actual behavior:
office-ui-fabric-react not rendering SharePoint themes in SharePoint hosted app 

#### Expected behavior:

office-ui-fabric-react should automatically apply my selected SharePoint theme coloring scheme to my components. 

### Here is my github repository:
 https://github.com/szulfiqar/SharePointApp3_ReactOfficeUIFabric

**Comment by dzearing** [comment]
Looping in the right people internally; it seems the page is not getting theme information. This is less of a fabric-react issue and more of a sharepoint issue.

**Comment by pixelhen** [comment]
Was there any update to this? anyone?

**Comment by garrytrinder** [comment]
I also see this message in the console, which could be related...

![image](https://user-images.githubusercontent.com/11563347/39544197-37b8830a-4e45-11e8-8051-a0288ecb3e30.png)

I'm taking a wild guess that theming.js is checking the `__theme_state___.theme` object which does not contain a key called "Light1"

**Comment by phkuo** [comment]
The theming in Classic and Modern SharePoint and inherently incompatible. They're basically speaking a different language (i.e. all the keys are different). If you set a theme via the Modern theming experience, the server will attempt to create a theme that will work in Classic.

However, theming must be invoked by global app/host code. Classic pages will trigger theming for Classic components, but not for Modern. There needs to be something on the page to invoke theming for the Fabric components, and as far as I know, that doesn't exist, unless the SPFX folks added it.

**Comment by aditima** [comment]
Hi, the core issue here seems to be that the documentMode is set IE10 in the SharePoint master page. Fabric does not support IE10 documentMode and the default documentMode for SP has recently been updated to Edge. If you are using a custom master page, please consider updating your documentMode to IE11 or Edge to work with Fabric.
