### ISSUE TITLE
CommandBar: Icon-only buttons

### ISSUE THREAD

**Issue by pablonete** [OfficeDev/office-ui-fabric-react#1840]
### Feature Request

Currently the guidance to create icon-only commands is to make `name` empty (see examples).
But this doesn't work well with overflow, as buttons will be rendered as an icon in the contextual menu. We also have other accessibility issues with buttons without name (see #1831).

Proposal: we should always provide a `name`, and hide it conditionally based on a property of IContextualMenuItem only when the command is displayed in the command bar and not in the overflow area (inside the ellipsis button). If a tooltip is not provided explicitly for the command, display this hidden name as a tooltip automatically.

Note: We've tried a workaround based on CSS to *none* display the `name` span in command bar but show it on overflow. This feels an abstraction leak that's prone to get broken as library evolves, so more a hack than a guidance IMO.

**Comment by micahgodbolt** [comment]
Command bar is in the middle of a revamp that will certainly support icon-only commands. 

You can follow the work on this branch https://github.com/micahgodbolt/office-ui-fabric-react/tree/command-bar-refactor

**Comment by pablonete** [comment]
Thank you for clarifying, @micahgodbolt

**Comment by micahgodbolt** [comment]
Currently got this working in my branch. Adding an 'iconOnly' prop to commandBarItem which suppresses the name in the bar, but leaves it in the overflow.


![commandbar](https://cloud.githubusercontent.com/assets/1434956/26695796/115d500a-46c1-11e7-835a-df5be59ed78d.gif)

**Comment by jcuenod** [comment]
If I should open a new issue for this, let me know.
In addition to icon only, it would be great to be able to hide the dropdown arrow (like next to "New" above).

The use case I am thinking of is when an icon like waffle/more is used. The icon itself indicates that a menu of some kind is associated with the icon button.

**Comment by micahgodbolt** [comment]
every button is completely customizable. i.e it'd be easy to override the render function of the dropdown arrow.
