### ISSUE TITLE
Persona Component -  onRenderSecondaryText prop doesn't work (never called) 

### ISSUE THREAD

**Issue by J0hnRoger** [OfficeDev/office-ui-fabric-react#1841]
### Bug Report

- __Package version(s)__: 1.14.3
- __Browser and OS versions__: Chrome & Win10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Low 

#### Describe the issue:

  On the react component **Persona** When I use the prop *onRenderSecondaryText* , the function is not called and nothing appen. 

#### Actual behavior:

The method 'onRenderSecondaryText' is never call (

My persona :

`const persona = {
    imageUrl: user.PictureUrl,
    imageInitials: '',
    primaryText: user.Title,
    secondaryText: 'Contacter',
    tertiaryText: 'In a meeting',
    onRenderSecondaryText: (props) => {
      return (
        <div>
          <i className='ms-Icon ms-Icon--Mail' aria-hidden='true'></i> Hello
        </div>
      )
    },
    size: PersonaSize.large
  }

  return (
    <div className='a5-people__user'>
      <Persona
        {...persona}
      />
    </div>
  )`

#### Expected behavior:
The function onRenderSecondaryText must be called with the value of the secondaryText, and return the HTML content

**Comment by micahgodbolt** [comment]
when I try your example my editor gives me this hinting error

![image](https://cloud.githubusercontent.com/assets/1434956/26365952/13a89d26-3f9e-11e7-80dd-7ab7ecc8c55d.png)


i.e. you're returning a variable, not a jsx string. Change it to `<div>Hello</div>` and it works.
