### ISSUE TITLE
Checkbox clicks propagate to parent elements

### ISSUE THREAD

**Issue by rickyp-ms** [OfficeDev/office-ui-fabric-react#1845]
### Bug Report

- __Package version(s)__: 2.20.0
- __Browser and OS versions__: All

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: tasks.officeppe.com

#### Describe the issue:

Imagine a Task Card with Checkbox elements on it. If you click the task card it opens a dialog with task details. If you click the checkbox, it simply enables or disables the checkbox.

Currently, it you stack these two clickable elements on another, clicking the checkbox will do both toggle the checkbox and open the details dialog.

#### Actual behavior:

Both clickable elements fire events

#### Expected behavior:

Only the checkbox should be affected

### If applicable, please provide a codepen repro:

N/A

### Suggested fix

When handling the click for the input element, just add a
event.stopPropagation();
event.preventDefault();

**Comment by rickyp-ms** [comment]
Added this as it's something I'm looking into but haven't had time to fix personally. My next opening will be coming up next Wednesday.

**Comment by rickyp-ms** [comment]
So honestly I'm not sure why this is actually happening. May just have to hack a fix by adding a wrapper element and executing event.stopPropagation() on the onclick.

**Comment by Katli95** [comment]
Had the same issue, the checkbox field was inside of a <form> element and submitted the form on each click :/
