### ISSUE TITLE
hover event on details list

### ISSUE THREAD

**Issue by russgove** [OfficeDev/office-ui-fabric-react#1847]
how can i wire up a hover event for  rows in a detailslist. i want to show a fallout when a user hovers ove a row.

**Comment by dzearing** [comment]
The whole row or just a particular column cell? 

Whole row, you can render a wrapper around each row to do what you need.

```tsx
onRenderRow={ (props, defaultRender) => <div onMouseEnter={ () => console.log('hovering over: ' + props.item.title)}>{defaultRender(props)}</div> }
```

You can also provide custom cell renderers in the column definitions which can allow you to scope your eventing to a particular column.

**Comment by dzearing** [comment]
Also see http://codepen.io/dzearing/pen/EgqMZq?editors=1011

I've updated it to console log on hover of a row.

**Comment by russgove** [comment]
awesome, thanks man! hey do you guys monitor anything on stackexchamge, or is here the best place to get answers?

**Comment by russgove** [comment]
works like a champ! thanks,
Now just to figure out that callout....

**Comment by thisisnaty** [comment]
Hi, I tried this solution but got an exception saying: Object expected... is there another way of attaching a hover event on a row?

**Comment by vasticles** [comment]
> The whole row or just a particular column cell?
> 
> Whole row, you can render a wrapper around each row to do what you need.
> 
> ```tsx
> onRenderRow={ (props, defaultRender) => <div onMouseEnter={ () => console.log('hovering over: ' + props.item.title)}>{defaultRender(props)}</div> }
> ```
> 
> You can also provide custom cell renderers in the column definitions which can allow you to scope your eventing to a particular column.

@dzearing 
Sorry to open an old issue. I'm struggling to get hover working on a specific column cell. I need the cell to render when its row is hovered on, otherwise render nothing. Is that achievable?
