### ISSUE TITLE
[SearchBox] Search icon is not coming back when clicked outside of the box

### ISSUE THREAD

**Issue by akashperfect** [OfficeDev/office-ui-fabric-react#1848]
### Bug Report

- __Package version(s)__: 2.32.0
- __Browser and OS versions__: Edge, Chrome, Windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) Internal site wherever search box is used

#### Describe the issue:
Once on clicking inside the search box the search icon vanishes for typing. But if we haven't typed anything and click outside of the search box. Ideally the search icon should be visible back inside the search box.

#### Actual behavior:
Search icon is not coming back on clicking outside of the box after selecting the search box

On selecting the search box
![image](https://cloud.githubusercontent.com/assets/2953096/26388100/f77cedd2-406f-11e7-8b93-228bca278374.png)

On clicking outside the search box
![image](https://cloud.githubusercontent.com/assets/2953096/26388116/0b06e934-4070-11e7-8d49-e41236f79bc8.png)

#### Expected behavior:
Search icon should come back on clicking outside of the box.
![image](https://cloud.githubusercontent.com/assets/2953096/26388126/1673def8-4070-11e7-8d51-d53c67e4f7b7.png)

**Comment by micahgodbolt** [comment]
The problem is that the icon will come back when the search box loses focus, and it seems that clicking outside of the search isn't triggering that properly. If you tab away, it works properly.

**Comment by micahgodbolt** [comment]
got a fix coming. wasn't too much work. Need the search to be working for my commandBar updates anyway
