### ISSUE TITLE
TextField is higher from v2.27.3 ?

### ISSUE THREAD

**Issue by lukred** [OfficeDev/office-ui-fabric-react#1849]
I have a website where I have a dropdown component next to the textField component.

![dropdown textbox](https://cloud.githubusercontent.com/assets/16718164/26391922/f51016ce-4064-11e7-994b-dc05ad326528.png)

Up to version 2.27.3 all looked fine as the height of both components were the same (32px).

However, since the v2.27.3 release, the TextField height is now 2 pixels higher.

Is that expected behavioiur or some side effect?

(btw: the release notes of the  v2.27.3 was following: "TextField: font size of textfield reverted to 14px.") 
?

**Comment by mdahamiwal** [comment]
Good catch!!, the field group in TexField doesn't include `box-sizing: border-box` which makes it 34px height including 1px border.

**Comment by SpoonsJTD** [comment]
I am new to react and ui fabric -- what is the recommended way to temporarily work around something like this until it's fixed?
