### ISSUE TITLE
DatePicker: go to today doesn't select current day

### ISSUE THREAD

**Issue by notgiorgi** [OfficeDev/office-ui-fabric-react#1850]
Right now if you press go to today in date picker, it will just move near the current date, and not choose it.

Is this expected behavior? Shouldn't go to today button select current date and close the datepicker?

**Comment by mdahamiwal** [comment]
Yes, it's by-design. @mikewheaton, @micahgodbolt, can you guys comment on the design considerations here ?

**Comment by johannao76** [comment]
We have a pull request out to change this behavior so the picker actually selects today's date.

**Comment by johannao76** [comment]
This issue has been fixed by commit 0e28d77 (see above pull request)
