### ISSUE TITLE
[DetailsList]: GridItem.Row is not properly defined in the windows inspect tool.

### ISSUE THREAD

**Issue by asranja** [OfficeDev/office-ui-fabric-react#1862]
Steps to repro:

- Open Edge browser
-  Go to http://dev.office.com/fabric#/components/detailslist 
-  Scroll down to "Simple DetailsList with 500 items, filtering, marquee selection" example.
-  Open the windows inspect tool (which is included as part of windows sdk)
-  Observe the GridItem.Row value for each DetailsList row item. 

It is observed that GridItem.Row value remains 1 for each row. Ideally, it should indicate the corresponding row number.

**Comment by micahgodbolt** [comment]
Do you know of any documentation that explains how this is implemented in HTML? This seems to be an OS level specification.

**Comment by mdahamiwal** [comment]
@asranja, can you provide a screenshot for where do you see 'griditem.row' property in Inspect?

**Comment by asranja** [comment]
![dl4](https://cloud.githubusercontent.com/assets/20986928/26778808/76900854-4a00-11e7-9f19-f0da9d54f901.PNG)

![dl3](https://cloud.githubusercontent.com/assets/20986928/26778733/2b5b3200-4a00-11e7-817f-5261e39b7b3b.PNG)

@mdahamiwal, please refer to the screenshots above.

**Comment by niadak** [comment]
@micahgodbolt Any update on this? This issue is only happening in edge. In IE, it is working fine.

**Comment by micahgodbolt** [comment]
If this works in IE but not Edge, is there a chance this is just an Edge bug?
