### ISSUE TITLE
CommandBar: `data-command-key` is set to index instead of key.

### ISSUE THREAD

**Issue by warmsea** [OfficeDev/office-ui-fabric-react#1870]
### Bug Report

- __Package version(s)__: 2.34.0 (latest master as of 2017/5/26)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes)

Requested priority: (High) 

#### Describe the issue:

`data-command-key` is set to internal index even if `key` is provided for a command.

#### Actual behavior:

`data-command-key` is set to internal index no matter if `key` of a command is provided or not.

#### Expected behavior:

If `key` of a command is provided, `data-command-key` should be set to `key`. Only when it is not provided, `data-command-key` can be set to the internal index.

**Comment by micahgodbolt** [comment]
Working on a new command bar, will put this in my list of "things to make sure are done correctly"

**Comment by warmsea** [comment]
That's great, Micah, thank you! Do you have any rough idea about the ETA for the new command bar?

**Comment by warmsea** [comment]
Hi, I've been waiting for 3 months and this bug is still there. So, I created a PR to fix it. Please help review. Thanks!

**Comment by micahgodbolt** [comment]
Thanks for the contribution @warmsea. CommandBar is taking longer than I hoped. It's in the experiments package right now going through it's paces with testing.

If you'd like to try it out and give feedback, I'd love to hear it! 

https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/experiments
