### ISSUE TITLE
Detail List: Support onDeleteKeyUp

### ISSUE THREAD

**Issue by carruthe** [OfficeDev/office-ui-fabric-react#1871]
In the `DetailsList` Control, it would be nice to be able to capture when the user presses the delete key (on Windows or Mac) while an item is selected - analogous to the `onItemInvoked` event that is fired when the user presses the `Enter` key.  This way, I could respond and delete the items that are selected.

Thanks!

**Comment by betrue-final-final** [comment]
I agree. That seems like a basic feature of a list. @dzearing is there a reason we don't expose that in the control?

**Comment by dzearing** [comment]
You don't really need DetailsList to do this. There is nothing preventing you from adding a key handler on the container, or even app, to do this. Having the DetailsList do it for you isn't making it that much easier.

**Comment by carruthe** [comment]
Very true, there are other ways to do it, but it would be more convenient to package it all within the component that contains the DetailList by adding a single event handler.
