### ISSUE TITLE
lack of functionality in TextField 

### ISSUE THREAD

**Issue by ashutosh1211** [OfficeDev/office-ui-fabric-react#1874]
TextField doesn't have following:
1) input type eg. password , number ...
2) major events like onBlur or onFoucsLost
3) don't have function to set or clear the value of TextField

**Comment by MarkGalloway** [comment]
Some tips:

1. You can pass down props, such as: `<TextField type="password">`

2. It looks like they will delegate to any passed down onBlur prop.
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/TextField/TextField.tsx#L231

3. Manage your own value using state.

**Comment by ashutosh1211** [comment]
Thanks @Markgalloway,. React documentation needs some improvements 😖
