### ISSUE TITLE
[Accesibility] Contextual Menu Items should show "LocalizedControlType" as menu item in windows inspect tool

### ISSUE THREAD

**Issue by kesane-msft** [OfficeDev/office-ui-fabric-react#1878]
### Bug Report

- __Package version(s)__: Latest
- __Browser and OS versions__:  Edge, Windows 10 Creators Update

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High 

Products/sites affected: 

#### Describe the issue:
1. Navigate to the [Contextual Menu](https://dev.office.com/fabric#/components/contextualmenu) control on the Office Fabric page.
2. Click on any menu and check the values for any menu item in Windows Inspect tool.

#### Actual behavior:
1. The value of LocalizedControlType is shown as **button**.

![image](https://cloud.githubusercontent.com/assets/28951219/26540486/4fe49b5c-446f-11e7-8023-70e03c6c09f6.png)

#### Expected behavior:
1. The value of LocalizedControlType should be set as **"menu item"**.

**Comment by mdahamiwal** [comment]
This got fixed in last update with https://github.com/OfficeDev/office-ui-fabric-react/pull/1868. check https://github.com/OfficeDev/office-ui-fabric-react/releases/tag/office-ui-fabric-react_v2.34.2
