### ISSUE TITLE
How to disp;ay nested objects in DetailsList

### ISSUE THREAD

**Issue by russgove** [OfficeDev/office-ui-fabric-react#1880]
Hi,
I am trying to create a details list that displays an object that has nested objects.
My DetailsList is defined like this:
 ```
<DetailsList
          layoutMode={DetailsListLayoutMode.fixedColumns}
          selectionMode={SelectionMode.none}
          items={this.state.timeSpents}
          setKey="Id"
          columns={[
            { key: "Id", name: "Id", fieldName: "Id", minWidth: 20, maxWidth: 200 },
            { key: "TR", name: "TR", fieldName: "TR.title", minWidth: 20, maxWidth: 200 },
            { key: "HoursSpent", name: "HoursSpent", fieldName: "HoursSpent", minWidth: 200 }
          ]}
        />
```
this.state.timeSpents looks like this
![timespent](https://cloud.githubusercontent.com/assets/2412956/26564161/a2f368c8-44ab-11e7-9e52-2371c925c431.PNG)

but TR.Title displays nothing

**Comment by dzearing** [comment]
you'll have to custom render the column using onRender. This will let you have complete control over what to access and how to render it. The `fieldName` prop is purely for convenience.

I modeled your example to illustrate here:

https://codepen.io/dzearing/pen/XRvXoL
