### ISSUE TITLE
Nav collapse on mobile

### ISSUE THREAD

**Issue by cobbs-totem** [OfficeDev/office-ui-fabric-react#1882]
### Bug Report

- __office-ui-fabric-react@4.0.0__: (fill this out)
- __Chrome 58.0.3029.110 (64-bit)__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: Normal

Products/sites affected: N/A

#### Describe the issue:

According to the Nav documentation:  https://dev.office.com/fabric#/components/nav

"In smaller configurations, the Nav may collapse into a skinnier version or be completely hidden until the user taps an icon."

However, I see no way of actually accomplishing this.  Is that part not a part of the functionality of Nav, and left as a CSS exercise to the end-user?

#### Actual behavior:

Nav items do not collapse into a skinnier version on smaller displays.

#### Expected behavior:

Nav items collapse into a skinner version on smaller displays.

**Comment by KeiraYang** [comment]
Hi. Do you find a solution with this issue? I want to use the collapse function too but also didn't find the implementation. I don't know if it is not implemented or just I didn't find where. Thank you!

**Comment by cobbs-totem** [comment]
It's left for an exercise to the user.  I just used common solutions and other 3rd party components to implement a responsive side nav.

**Comment by cobbs-totem** [comment]
I ended up using Material UI's Drawer and Hidden components, but I imagine you could also use Office UI's CSS classNames "ms-hidden" to render your side Nav/no side Nav based on the screen size.
