### ISSUE TITLE
Icon classes aren't right with 4.0.0 update

### ISSUE THREAD

**Issue by MLoughry** [OfficeDev/office-ui-fabric-react#1885]
### Bug Report

- __Package version(s)__: 4.0.0
- __Browser and OS versions__: Chrome, Windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Blocking

Products/sites affected: Outlook

#### Describe the issue:

Some of the IconClassName properties render incorrect icons

#### Actual behavior:

Using 'chevronDownMed' in the upper right, and 'reply' in the lower-left
![image](https://cloud.githubusercontent.com/assets/20823465/26609864/c6495a00-4558-11e7-95b3-3a0409a68a42.png)

#### Expected behavior:

![image](https://cloud.githubusercontent.com/assets/20823465/26609869/d34736be-4558-11e7-84cc-6c5ffd6eb687.png)

### If applicable, please provide a codepen repro: <https://codepen.io/MLoughry/pen/dWxybK> 
See the chevron entries in the repro

**Comment by dzearing** [comment]
Should be fixed.
https://codepen.io/dzearing/pen/ybmeqQ
