### ISSUE TITLE
Font changed since 4.x ?

### ISSUE THREAD

**Issue by lukred** [OfficeDev/office-ui-fabric-react#1888]
I'm using <Label> components in my website. 
In versions 3.x, all labels had nice "Segoe" font.
When I updated to 4.x, all fonts become ugly "Serif"

Do I have to add something in order to bring it back?

**Comment by dzearing** [comment]
@lukred can you wrap your content in a <Fabric> component?

```tsx
import { Fabric } from 'office-ui-fabric-react/lib/Fabric';

<Fabric>
   ...content
</Fabric>

**Comment by erichdev** [comment]
Closing since solution has been posted. Please open a new issue if you still experience font issues
