### ISSUE TITLE
ContextualMenu: Custom ClassName not being applied

### ISSUE THREAD

**Issue by atneik** [OfficeDev/office-ui-fabric-react#189]
In ContextualMenu customization example the class Charm-list is not being applied to the item's ContextualMenu.

Repro steps:
1. Go to ContextualMenu customization example
2. Click on button to get the parent ContextualMenu, and then on Charm.
3. Notice charms not is center aligned, as `.Charm-List` is not applied to charm item's context menu.

<img width="582" alt="screen shot 2016-08-23 at 4 11 41 pm" src="https://cloud.githubusercontent.com/assets/785361/17913077/7e9a3f6e-694c-11e6-96ae-6fc85aba691b.png">

**Comment by dzearing** [comment]
@atneik is this fixed now?

**Comment by dzearing** [comment]
Fixed.
