### ISSUE TITLE
Document the theming API

### ISSUE THREAD

**Issue by Boboliiiino** [OfficeDev/office-ui-fabric-react#1896]
This theme looks very wonderful, however it gives me a hard time getting it up.
The demos aren't working for me (and after some digging for some other people, too).
The tutorials aren't helpful since they are all for JavaScript and not TypeScript and/or create-react.

I don't know if a starter is planned, however to be able to use the theme, one have to reverse engineer the react demo app. (The dependency on the example base isn't helpful either).

**Comment by dzearing** [comment]
sorry about this @Boboliiiino; we're actually in the middle of refining the theme story. We just recently checked in a styling package, where we're working on a more formal theming api. We will have better documentation up within the month for customization techniques.
