### ISSUE TITLE
Each child in an array or iterator should have unique "Key" prop, Dropdown Header

### ISSUE THREAD

**Issue by awwong1** [OfficeDev/office-ui-fabric-react#1897]
### Bug Report

- __Package version(s)__: `office-ui-fabric-react:4.1.1`

#### Priorities and help requested

Requested priority: Normal

#### Describe the issue:

When using the Dropdown component with the Header item, React will show in console:

> Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `Dropdown`. See https://fb.me/react-warning-keys for more information.

Unique header keys need to be included when rendering the dropdown panel. 

https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx#L309

**Comment by malexandrum** [comment]
yup, bug is there, thanks for fixing.

**Comment by leddie24** [comment]
@dzearing , this is in pr #1846

**Comment by leddie24** [comment]
Fixed in #1846
