### ISSUE TITLE
[Button]: Disabled button can be triggered by keyboard enter

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#1909]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: Chrome, windows 10

#### Priorities and help requested (not applicable if asking question):

Requested priority: (High) 

Products/sites affected: (if applicable) Webparts

#### Describe the issue:

1. In Button's demo page http://dev.office.com/fabric#/components/button
2. Disable all the button by check the checkbox 
![image](https://cloud.githubusercontent.com/assets/7711735/26669691/6830b604-46e1-11e7-97db-216747bd17c2.png)
3. Tab to the button under Button Like Anchor, which is only focusable button when disabled.
![image](https://cloud.githubusercontent.com/assets/7711735/26669741/85482952-46e1-11e7-848f-b5979216f0d3.png)
4. Press enter

#### Actual behavior:

The button is triggered and page refreshed

#### Expected behavior:

Nothing should happen

**Comment by mikewheaton** [comment]
The `<a>` element doesn't support the `disabled` attribute we're using here. In the case where it's rendered as an `<a>` instead of a `<button>`, we should remove the `href` attribute entirely to be sure it can't be focused or acted on.
