### ISSUE TITLE
Dropdown: dropdown list buttons has conflicting padding styles

### ISSUE THREAD

**Issue by yaananth** [OfficeDev/office-ui-fabric-react#1916]
goto: http://dev.office.com/fabric#/components/dropdown 
Inspect dropdown option.

![image](https://cloud.githubusercontent.com/assets/12280011/26701793/69f28daa-46f0-11e7-85c9-19bf3e22a151.png)

It's applying conflicting padding styles from` .item_*` and `.root_*` classes.
Based on what loads first, that gets applied, it so happened that in one of my implementations, `.root_*` got precedence and that messes up the padding.

P.S: why does `.root_` has two different paddings anyway?

**Comment by kristoferbrown** [comment]
This should no longer be occurring. Reopen this issue if you see it again.
