### ISSUE TITLE
Fabric website: Need alt-text for Image component

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#1919]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes)

Requested priority: (Normal) 

I realize for our image component, we aren't providing alt-text. We should be doing this to represent a best practice. Should be pretty easy for a good win.

**Comment by Jahnp** [comment]
Fully agreed @betrue-final-final. We'll be looking at getting this fixed over the next week or two.
