### ISSUE TITLE
ContextualMenu: Update Charm variant/example to look like OWA

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#1921]
### Bug Report

- __Package version(s)__: Latest
- __Browser and OS versions__: All

#### Priorities and help requested (not applicable if asking a question):

Are you willing to submit a PR to fix? Possibly

Requested priority: Low

Products/sites affected: Unsure

#### Describe the issue:

From Angela: It looks like we're missing a selected menu item state, icons look off-center from IA states, need to remove a scrollbar. Calendar also shows 'None' as being selected by default before any icons have been selected. 

#### Actual behavior:

![image](https://cloud.githubusercontent.com/assets/1382445/26741828/dc2ee3d8-478f-11e7-8fc5-bfd895e75e3f.png)

#### Expected behavior:

![image](https://cloud.githubusercontent.com/assets/1382445/26741834/e29044a6-478f-11e7-9cd1-220655a3a6ca.png)

**Comment by erichdev** [comment]
See https://github.com/OfficeDev/office-ui-fabric-react/issues/2506
