### ISSUE TITLE
Cannot override colors for various components

### ISSUE THREAD

**Issue by rickyp-ms** [OfficeDev/office-ui-fabric-react#1926]
### Bug Report

- __Package version(s)__: 2.22.0 and Beyond
- __Browser and OS versions__: All

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: tasks.office.com

#### Describe the issue:

Our designers have decided to customize Fabric's colors quite extensively. For example
$ms-color-themePrimary:         #35749B !default;
$ms-color-themeSecondary:       #408AB7 !default;

This override of colors only works if developers use the 
@include ms-*Color-themePrimary; such as @include ms-bgColor-themePrimary;

Sadly in the code there are lots of references to
background-color: $ms-color-themePrimary;

These don't get overridden so now we have multiple colors going on in our system.

#### Actual behavior:

More colors than are expected

#### Expected behavior:

Our specified colors to be used everywhere

**Comment by mikewheaton** [comment]
We're actively working on theming support. You can find the documentation for the current system here: http://dev.office.com/fabric#/components/themes

**Comment by erichdev** [comment]
@rickyp-ms Are you still experiencing issues with colors? Theme support has improved since issue was opened

**Comment by erichdev** [comment]
Closing because no response. Please reopen if any issues remain.
