### ISSUE TITLE
Dropdown autoclose

### ISSUE THREAD

**Issue by jdaking90** [OfficeDev/office-ui-fabric-react#1932]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: Google Chrome Version 58.0.3029.110 (64-bit), Mac 10.12

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) Not sure what this is.

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) dev.office.com

#### Describe the issue:

"Only problem I ran into here (dev.office.com/fabric) is that if you scroll a long list on a desktop the fabric dropdown menu autocloses when you reach the bottom, making choosing the last item tricky."

#### Actual behavior:

autocloses menu when scrolling past bottom item in dropdown list.

#### Expected behavior:

Not autoclose the menu.

**Comment by dzearing** [comment]
hah, that's funny. So, i guess we may want to disable body scroll during the rendering of the dropdown.
