### ISSUE TITLE
Persona flicker issue

### ISSUE THREAD

**Issue by junciixn** [OfficeDev/office-ui-fabric-react#1934]
### Bug Report

- __Package version(s)__: (curent)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Possible)

Requested priority: (High) 

Products/sites affected: (OWA React)

#### Describe the issue:

Mount Persona will always render initial first then image. Even if we're sure that we're passing a valid blob image url and the image is already in browser cache, we cannot control to directly render the image. In OWA React, mount/unmount Persona and mount Persona again can happen in a very short time, which cause the visual flicker.

Repro:
If you go to OWA React and switch between two email conversations, you'll see the Persona flicker.

#### Expected behavior:

Having the option to directly show image in Persona.

**Comment by mikewheaton** [comment]
It sounds like if the `imageUrl` prop is provided, we should wait some time (or for the image loading to encounter an error) before showing the initials.

**Comment by junciixn** [comment]
Since Persona has an internal state "isImageLoaded", even the image is in browser cache, Persona still force to render initial first then the image. We want to have an option to control to directly render image.
