### ISSUE TITLE
High contrast mode doesn't seem to work on dev boxes

### ISSUE THREAD

**Issue by rickyp-ms** [OfficeDev/office-ui-fabric-react#1935]
### Bug Report

- __Package version(s)__: master branch
- __Browser and OS versions__: IE 11

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes... eventually

Requested priority: Normal

Products/sites affected: n/a

#### Describe the issue:

Developing high contrast scenarios is harder as running "npm start" on a dev box results in a website that seems to have issues. Here is the side by side of what I see on my dev box vs dev.office.com/fabric 
![untitled](https://cloud.githubusercontent.com/assets/22225666/26803263/62a43bec-49f8-11e7-81bd-2f2d20c0ead8.png)

#### Actual behavior:

See image

#### Expected behavior:

For both sites to have the same colors

**Comment by micahgodbolt** [comment]
Does this work for you in Edge?

**Comment by mikewheaton** [comment]
I'm not sure why the browser itself looks different between the two screenshots. These are on the same machine, with high contrast on, and in the same browser?

**Comment by dzearing** [comment]
@mikewheaton I imagine something in the css of the example-app-base is causing this? What was done special on the fabric-website?

**Comment by rickyp-ms** [comment]
This screen shot is the same browser (IE 11) at the same time, the two windows side by side.

The one on the right is what you get when you do npm start
The one on the left is dev.office.com/fabric
Which is why they look slightly different.

Sadly this is a Windows 2016 server box and the geniuses there didn't ship Edge with 2016.

**Comment by mdahamiwal** [comment]
This is caused due to addition of `-ms-high-contrast-adjust: none` in fabric core 7.0. I have raised  a PR https://github.com/OfficeDev/office-ui-fabric-core/pull/988 to correct this behavior.

**Comment by mdahamiwal** [comment]
The change is merged in fabric-core now. @mikewheaton, is there any reaction work required in fabric react to use fabric core 7.1.0?
