### ISSUE TITLE
Feature request: Disable icon font download

### ISSUE THREAD

**Issue by rickyp-ms** [OfficeDev/office-ui-fabric-react#1936]
General request... seems that within DefaultFontStyles.ts always makes a request to the full fabricmdl2icons font file. So if instead we create a subset font file (which is recommended) to decrease the size of the download, it doesn't matter because the full file is always downloaded on init.

**Comment by rickyp-ms** [comment]
@Jahnp Do you know of a good way to do this?

Also, wouldn't it make sense to just bite the download of the icon font file once but have all apps share the same url... that way the browser would just cache the font file?

**Comment by dzearing** [comment]
@rickyp-ms You can do this now! While it's a bit undocumented, we've added this workaround:

1. In your page, define this:

```js
window.FabricConfig = {
  fontBaseUrl: null
};
```

This will prevent the font from being downloaded. Code is at the bottom of `DefaultFontStyles.ts`.

We will need to document this better, but with @Jahnp 's work on icon subsetting coming in, we'll likely have a much more robust solution here in the future.

**Comment by rickyp-ms** [comment]
Thanks! Looks like that's working :-)
