### ISSUE TITLE
SearchBox: Add autocomplete suggestions functionality

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#1945]
#### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Unknown

#### Describe the issue:

The [documentation for SearchBox](https://dev.office.com/fabric#/components/searchbox) describes some autocomplete behavior, where a list of suggested search terms would appear below the SearchBox as the user types. This functionality doesn't exist.

#### Actual behavior:

No autocomplete behavior.

#### Expected behavior:

An optional Callout can appear while typing, providing suggestions for search terms.

**Comment by haifoo** [comment]
Any updates on this? would love for this feature to be implemented.

**Comment by petercutting** [comment]
I am also wondering when this will be available. The docs sais "As the user enters a query string, they are provided with a dropdown of autocomplete suggestions or disambiguation options.". I dont see any of that in the examples and the backing code doesnt seem to implement it. What is going on?

https://developer.microsoft.com/en-us/fabric#/components/searchbox

**Comment by juliosaenz** [comment]
how come this was closed?
the documentation's best practices still says we should do auto suggests, but has no indication on how to do it.
Seems like this would be a basic functionality that a searchbox would provide.
