### ISSUE TITLE
Message bar has wrong tab stop in firefox

### ISSUE THREAD

**Issue by erjohnms** [OfficeDev/office-ui-fabric-react#1947]
### Bug Report

- __Package version(s)__: 2.25.2
- __Browser and OS versions__: Firefox 53.0.3

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: vsts

#### Describe the issue:

When using the MessageBar component and using firefox, the span that has the class ms-MessageBar-innerTextPadding will receive tab stop focus. Perhaps something to do with its role as an aria live status? I don't know the reason for it but firefox's behavior here is different than other browsers unless this span is explicitly tabIndex -1 instead of undefined

#### Actual behavior:

Firefox focuses on the span mentioned above when tabbing. This span should not be a tab stop. Other browsers do not tab stop here.

**Comment by mdahamiwal** [comment]
@erjohnms , its a known issue with latest firefox version where elements with `overflow` set are tab stops. This should get fixed with next browser update.

**Comment by erjohnms** [comment]
ah, ok. Thanks
