### ISSUE TITLE
Picker: change order of selected items is not supported

### ISSUE THREAD

**Issue by grzegorzlademan** [OfficeDev/office-ui-fabric-react#1957]
Picker control does not have a way to change order off already selected items. If I choose multiple items and I would like to change order of list I have to remove all of them and start again - it is very annoying for customers. 
We are using TagPicker to select column name's which should be displayed in Excel worksheet. 
And it is very important that user can specify columns in particular order and that we display them in requested order.

Is there some way to achieve this? It will be nice feature to be able to change order of selected items.

**Comment by KEMiCZA** [comment]
Can this be reopened please? This is a very needed feature for a lot of use cases. The only way this is possible now is to remove the items from the picker and start adding them in the correct order. Imagine having a picker with +20 items and having to move item n2 to n1. A possible solution would be to implement arrows next to the cross "X" icon or even allow to drag & drop items to the correct order.

Please team make this happen :)! Would be much appreciated!
