### ISSUE TITLE
Console flooded with "whoops, illegal rule inserted" from sheet.js:134

### ISSUE THREAD

**Issue by ashutosh1211** [OfficeDev/office-ui-fabric-react#1971]

**Comment by dzearing** [comment]
These only occur in debug builds, and the root cause is logged here in glamor, which where the logging is occurring:

https://github.com/threepointone/glamor/issues/265

If you are using webpack, please add the define NODE_ENV as "production" and minify through UglifyJS to build production builds which don't have the spam.

```
    plugins: [
      new webpack.DefinePlugin({
        'process.env.NODE_ENV': JSON.stringify('production')
      }),
      new webpack.optimize.UglifyJsPlugin({
        minimize: true,
        compress: {
          warnings: false
        }
    ]
```

We are actively looking at what it would take to resolve this even in debug builds. Either we get a fix into glamor to remove the warning or fix the autoprefixing, or fork it.

**Comment by dzearing** [comment]
It does look like our prebunded minified script in /dist doesn't have this. I'll fix this one right now.

**Comment by dzearing** [comment]
The prebundle uber script we produce has been fixed. The glamor issue is still pending, but tracked elsewhere.

**Comment by erickpintor** [comment]
Glamor has closed the related issue without fixing it. I'm using fabric with the create-react-app boilerplate and my console is flooded with those warnings. Is there any workaround that I can do this fix it at this point?

**Comment by joechung-msft** [comment]
Is it possible to get a production build of the lib-amd scripts?  These generate the glamor warning spam as well.

**Comment by lednhatkhanh** [comment]
I'm also getting this issue and it's very annoying, is there any workaround?

**Comment by alirobe** [comment]
Because this issue is closed, it's unlikely anyone will look here. The glamor developer's reason for closing the issue is dreadful. The comment above the console.warn line is literally `// might need beter dx for this`. Sigh.

**Comment by alirobe** [comment]
It looks like a fix is coming in an upcoming version of office-ui-fabric-react 
https://github.com/OfficeDev/office-ui-fabric-react/issues/2310

**Comment by ashutosh1211** [comment]
+ addition of thin in latest 

Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Arabic/segoeui-light.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Arabic/segoeui-light.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Arabic/segoeui-semilight.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Arabic/segoeui-semilight.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Arabic/segoeui-regular.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Arabic/segoeui-regular.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Arabic/segoeui-semibold.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Arabic/segoeui-semibold.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Cyrillic/segoeui-light.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Cyrillic/segoeui-light.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Cyrillic/segoeui-semilight.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Cyrillic/segoeui-semilight.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Cyrillic/segoeui-regular.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Cyrillic/segoeui-regular.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Cyrillic/segoeui-semibold.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Cyrillic/segoeui-semibold.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/EastEuropean/segoeui-light.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/EastEuropean/segoeui-light.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/EastEuropean/segoeui-semilight.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/EastEuropean/segoeui-semilight.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/EastEuropean/segoeui-regular.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/EastEuropean/segoeui-regular.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/EastEuropean/segoeui-semibold.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/EastEuropean/segoeui-semibold.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Greek/segoeui-light.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Greek/segoeui-light.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Greek/segoeui-semilight.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Greek/segoeui-semilight.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Greek/segoeui-regular.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Greek/segoeui-regular.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Greek/segoeui-semibold.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Greek/segoeui-semibold.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Vietnamese/segoeui-light.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Vietnamese/segoeui-light.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Vietnamese/segoeui-semilight.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Vietnamese/segoeui-semilight.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Vietnamese/segoeui-regular.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Vietnamese/segoeui-regular.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Vietnamese/segoeui-semibold.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Vietnamese/segoeui-semibold.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/WestEuropean/segoeui-light.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/WestEuropean/segoeui-light.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/WestEuropean/segoeui-semilight.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/WestEuropean/segoeui-semilight.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/WestEuropean/segoeui-regular.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/WestEuropean/segoeui-semibold.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Thai/leelawadeeui-semilight.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Thai/leelawadeeui-semilight.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Thai/leelawadeeui-semilight.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Thai/leelawadeeui-semilight.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Thai/leelawadeeui-regular.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Thai/leelawadeeui-regular.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Thai/leelawadeeui-bold.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/Thai/leelawadeeui-bold.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/WestEuropean/segoeui-light.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/WestEuropean/segoeui-light.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/WestEuropean/segoeui-semilight.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/WestEuropean/segoeui-semilight.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/WestEuropean/segoeui-regular.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/WestEuropean/segoeui-semibold.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/WestEuropean/segoeui-light.woff2
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/WestEuropean/segoeui-light.woff
editor.main.js:31 Slow network is detected. Fallback font will be used while loading: https://cdn.vsassets.io/3rdParty/_fonts/TextFonts/WestEuropean/segoeui-semibold.woff
vss-bundle-view-vu8jXr9DFunNI16mkoSpaEdLhOnHVgW9mmX695iyHs50=:513 Slow network is detected. Fallback font will be used while loading: https://static2.sharepointonline.com/files/fabric/assets/fonts/leelawadeeui-thai/leelawadeeui-light.woff2
vss-bundle-view-vu8jXr9DFunNI16mkoSpaEdLhOnHVgW9mmX695iyHs50=:513 Slow network is detected. Fallback font will be used while loading: https://static2.sharepointonline.com/files/fabric/assets/fonts/leelawadeeui-thai/leelawadeeui-light.woff
vss-bundle-view-vu8jXr9DFunNI16mkoSpaEdLhOnHVgW9mmX695iyHs50=:513 Slow network is detected. Fallback font will be used while loading: https://static2.sharepointonline.com/files/fabric/assets/fonts/leelawadeeui-thai/leelawadeeui-semilight.woff2
vss-bundle-view-vu8jXr9DFunNI16mkoSpaEdLhOnHVgW9mmX695iyHs50=:513 Slow network is detected. Fallback font will be used while loading: https://static2.sharepointonline.com/files/fabric/assets/fonts/leelawadeeui-thai/leelawadeeui-semilight.woff
vss-bundle-view-vu8jXr9DFunNI16mkoSpaEdLhOnHVgW9mmX695iyHs50=:513 Slow network is detected. Fallback font will be used while loading: https://static2.sharepointonline.com/files/fabric/assets/fonts/leelawadeeui-thai/leelawadeeui-regular.woff2
vss-bundle-view-vu8jXr9DFunNI16mkoSpaEdLhOnHVgW9mmX695iyHs50=:513 Slow network is detected. Fallback font will be used while loading: https://static2.sharepointonline.com/files/fabric/assets/fonts/leelawadeeui-thai/leelawadeeui-regular.woff
