### ISSUE TITLE
TextField: underlined renders error in wrong place

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#1972]
Actual:

![image](https://user-images.githubusercontent.com/1110944/27012754-805c59fc-4e8b-11e7-89a6-7343aaf24c9e.png)

Expected, consistent with the default behavior;

![image](https://user-images.githubusercontent.com/1110944/27012779-353dfa24-4e8c-11e7-9893-d53973fa216d.png)

Codepen:

https://codepen.io/dzearing/pen/KqVbqY

**Comment by dzearing** [comment]
@mikewheaton @micahgodbolt thoughts? This was hit when trying to use the TextField in onedrive. This is a bug right?

**Comment by micahgodbolt** [comment]
ah yup...underlined should still have error message below it 
![image](https://user-images.githubusercontent.com/1434956/27293276-c5773a94-54ca-11e7-9a14-e4042221ca3e.png)
