### ISSUE TITLE
Callout loses target element on re-render

### ISSUE THREAD

**Issue by daweffe** [OfficeDev/office-ui-fabric-react#1977]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes
Requested priority: Normal 

Products/sites affected: Planner

#### Describe the issue:

When a callout is given a target by classname to track a react component, it is not searching for the element when react renders the callout.  When the target component was rendered with new data, the original no longer exists and the callout jumps to the top left corner.

#### Actual behavior:

Callout jumps to corner because it has not found the new react component.

#### Expected behavior:

Callout should find the new element and stay on it.

**Comment by atneik** [comment]
Not sure if Callout should be expected of that behavior. Would it be possible for you to reinitialize the component when target element is changed?
