### ISSUE TITLE
Dropdown: allow typing to filter options

### ISSUE THREAD

**Issue by malexandrum** [OfficeDev/office-ui-fabric-react#1979]
Requested priority: (High) 

#### Describe the issue:
Before starting to use Office UI Fabric React, we used a component that behaves like a dropdown but allows typing to filter options. An alternative is to use the Picker, but with the picker user has to type in order to get values, cannot just expand.
Any plans to extend the dropdown with this functionality?

**Comment by jair-cazarin** [comment]
There is an ongoing PR that is adding a ComboBox that might suit your needs: https://github.com/OfficeDev/office-ui-fabric-react/pull/1920

**Comment by atneik** [comment]
@malexandrum does ComboBox fixes this issue for you?

**Comment by malexandrum** [comment]
indeed it does! issue closed
