### ISSUE TITLE
[Toggle][DetailsList][Firefox][High Contrast] Inner circle not visible

### ISSUE THREAD

**Issue by ankitk94** [OfficeDev/office-ui-fabric-react#1983]
Browser and OS versions: Firefox

Describe the issue:

Toggle not showing inner circle to describe current state
Details list selected row not displayed with tick
Actual behavior:

Only outer area is visible.

Expected behavior:

Selected state should be visible for toggle
Details list should show selected row with checkmark

If applicable, please provide a codepen repro:

Scenario can be repro'd at:
https://dev.office.com/fabric#/components/toggle
https://dev.office.com/fabric#/components/detailslist

![image](https://user-images.githubusercontent.com/6390909/27068544-4aca5eb6-502e-11e7-85fb-27b66c2cb8e0.png)
![image](https://user-images.githubusercontent.com/6390909/27068562-5bd25a74-502e-11e7-94cb-b06fc60054e2.png)

**Comment by dzearing** [comment]
@phkuo can you please fix this?

**Comment by ankitk94** [comment]
@dzearing @phkuo Raised PR for toggle high contrast issue for Firefox

**Comment by ankitk94** [comment]
@phkuo Raised PR for details list check button also
