### ISSUE TITLE
CommandBar contextual Menu on dismiss eats up the focus event

### ISSUE THREAD

**Issue by AkshanshSrivastava03** [OfficeDev/office-ui-fabric-react#1984]
### Bug Report

- __Package version(s)__:^2.34.3-vsts.1
- __Browser and OS versions__: All browsers

#### Priorities and help requested (not applicable if asking question):

Requested priority: (Blocking, High, Normal, Low) 

Products/sites affected: (if applicable) VSTS

#### Describe the issue:
If there is a single button (disabled) in the overflow items (contextual menu) of the Command bar, and we open the Contextual menu then click on some button which is listening to focus events, it does not receive it as the _onContextMenuDismiss has event.stopPropagation and event.preventDefault which are eating up the focus event. The component trying to listen on focus does not receive the onFocus as it has been eaten up by Command Bar component

#### Actual behavior:
Command Bar eats up the focus event.

#### Expected behavior:
Command Bar should not eat up any event (like focus etc).

**Comment by AkshanshSrivastava03** [comment]
Is there any specific requirement why we eat up the event? As i see there is an If-check before stopping event propagation. Is there some scenario due to which we are avoiding it?
Also, this issue only happens if there is a single button in overflow (contextual menu) in disabled state.

**Comment by aadhars** [comment]
@dzearing I think we should not stop event propagation here. Also if event is null then as per code it will cause null reference exception. 
I was planning to remove this but once wants to confirm with you. Do you remember any reason why we are stopping the propagation here
