### ISSUE TITLE
Text not showing when peopleSuggestions are changed

### ISSUE THREAD

**Issue by HannesDel** [OfficeDev/office-ui-fabric-react#1997]
### Bug Report

- __Package version(s)__: 2.22.1
- __Browser and OS versions__: All

#### Describe the issue:

I have a component that fetches (with redux) the users from a server when the component mounted.
The defaultSelected is then picked out of this array of PersonaProps.

But, when the data is loaded, the default selected values are shown as empty boxes in the peoplePicker.

**Comment by jcoleman-pcprofessional** [comment]
Do your results/default selected have the primaryText set?  Only time I've seen an empty box was when the object did not have the required keys set.

I'm working on a project that has a people picker (pulling from SP) and just verified it's working correctly on the latest version of fabric react.

Here is an example of a default result that is working:
public managementServicesAdministrator: IPersonaProps[] = [
  {
    imageInitials: 'FL',
    primaryText: 'Last, First',
    secondaryText: 'email@address.com',
    tertiaryText: 'In a meeting',
    optionalText: 'Available at 4:00pm',
    presence: PersonaPresence.online
  }
];

**Comment by atneik** [comment]
@HannesDel if you're still facing the problem, would it be possible to create a Codepen to demonstrate the problem?

**Comment by erichdev** [comment]
Closing because there hasn't been any response from author. Please reopen if this issue still occurs.
