### ISSUE TITLE
Custom icon sizes for IconButton

### ISSUE THREAD

**Issue by jeremy-linchao** [OfficeDev/office-ui-fabric-react#1998]
could u provide the method to customize icon sizes for IconButton?

**Comment by jcoleman-pcprofessional** [comment]
This works:
{
                                key: 'boardLetter',
                                name: 'Board Letters',
                                iconProps: {
                                    iconName: 'Boards',
                                    width: 50,
                                    height: 50,
                                    style: {fontSize: 50}
                                },
}

For an image:
                                            imageProps: {
                                                width: 14,
                                                height: 14
                                            }

**Comment by jeremy-linchao** [comment]
it works, thank you  @jcoleman-pcprofessional
