### ISSUE TITLE
question about datepicker

### ISSUE THREAD

**Issue by jakeaaronson** [OfficeDev/office-ui-fabric-react#20]
regarding the date-picker
I can pragmatically change the value of the date picker by changing the value prop. Intuitively I would think I could set it to blank by giving it a null date. However this does not seem to make it blank. Is there a way to pragmatically reset the date-picker and make it blank.

**Comment by luhu** [comment]
This should be an issue. The PR to fix it is here and needed approval: https://github.com/OfficeDev/office-ui-fabric-react/pull/35

**Comment by dzearing** [comment]
This was merged. Should be fixed, please open a new issue if you're still having issues.
