### ISSUE TITLE
Layout as React Components

### ISSUE THREAD

**Issue by olemp** [OfficeDev/office-ui-fabric-react#2005]
Would be lovely to have layout grid as react components, `Grid`, `Row` and `Columns`.

Simple example:
```javascript
export interface IRowProps {
    hidden?: boolean;
    marginTop?: number;
    minHeight?: number;
    style?: React.CSSProperties;
    children: any;
}
export const Row = ({ hidden, marginTop, minHeight, style, children }: IRowProps) => {
    return (
        <div
            hidden={hidden}
            style={{
                ...style,
                minHeight: minHeight,
                marginTop: marginTop,
            }}
            className="ms-Grid-row">
            {children}
        </div>
    );
};

export interface IColumnProps {
    sm?: number;
    children: any;
}
export const Column = ({ sm = 12, children }: IColumnProps) => {
    return (
        <div className={`ms-Grid-col ms-u-sm${sm}`}>
            {children}
        </div>
    );
};

export interface IGridProps {
    children: any;
}
export const Grid = ({ children }: IGridProps) => {
    return (
        <div className="ms-Grid">
            {children}
        </div>
    );
};
```

**Comment by MaartenVerbaarschot** [comment]
I don't see the benefit of this to be honest. Looking at the current class based Grid API:

```
.ms-Grid
.ms-Grid-row
.ms-Grid-col
.ms-Grid-col.ms-{breakpoint}{colspan}
.ms-Grid-col.ms-{breakpoint}Push{colspan}
.ms-Grid-col.ms-{breakpoint}Pull{colspan}
.ms-Grid-col.ms-{breakpoint}Offset{colspan}
```

To me this is very readable, predictable yet flexable (e.g. combining with any other CSS classes on rows or columns, using other elements than divs, adding aria-* attributes).

Wrapping it in React components would pretty much duplicate an existing API from fabric-core, while it doesn't add any benefits (as in JavaScript behaviors, on top of the CSS implementation).  Two things to do the same thing does not sound good to me. Personally I like the transparency of fabric-core being purely class based, fabric-react being component based, without overlapping or duplicate APIs.
