### ISSUE TITLE
New Component: Upload

### ISSUE THREAD

**Issue by delesseps** [OfficeDev/office-ui-fabric-react#2012]
Any plans to release an upload component with the following features?

- Button to spawn the dialog
- Selected filename displayed 
- Drop zone for dragging on files
- Preview thumbnail if image
- Multiple file support

**Comment by ClickSimply** [comment]
I feel like this is outside the scope of fabric, especially since good libraries already exist to fill this role.

https://github.com/okonet/react-dropzone

**Comment by atneik** [comment]
Agree with @ClickSimply, this holistic component seems like out of scope for office-ui-fabric-react. You could wire some basic components such as Button, Dialog/Callout, Labels, etc. together to create the upload component.
