### ISSUE TITLE
Combobox: text move its position in Edge during up/down arrow

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#2020]
Just tried out the new combo-box in master branch, found one UI issue in Edge browser.

### Bug Report

- __Package version(s)__: The latest master branch
- __Browser and OS versions__: Edge and Windows 10

#### Describe the issue:

1. In Edge, Serves the fabric-react master branch in localhost and go to the combo-box page.
2. Focus on one of the combo-box and then press enter to trigger the selections.
3. Press down arrow key to move among items.

#### Actual behavior:

The text in input box will float up and down.

#### Expected behavior:

The text is always at same position as it did in Chrome.

#### gif
![combo-box](https://user-images.githubusercontent.com/7711735/27315719-c9fc7096-55ad-11e7-912c-efce93cc93db.gif)

**Comment by jair-cazarin** [comment]
@jspurlin
