### ISSUE TITLE
CommandBar: Should not call setState when the component has been unmounted.

### ISSUE THREAD

**Issue by jechayav** [OfficeDev/office-ui-fabric-react#2029]
### Bug Report

- __Package version(s)__: Office Fabric 4.9.0
- __Browser and OS versions__: All

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

#### Describe the issue:
We are using OfficeFabric CommandBar, with sub menu options.
When one of the sub menu is clicked, we dispose the component and navigate away from the page using XHR navigation.
Because the component has been disposed, there is console error "setState(...) can only update a mounted or mounting component" from CommandBar. 
The is because CommandBar _onContextMenuDismiss is being called and setState after the component has already unmounted.
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.tsx  (line 370)

#### Actual behavior:
console error "setState(...) can only update a mounted or mounting component" from CommandBar. 

#### Expected behavior:
Expected no error, and CommandBar should not call serState when its component has been unmounted.

**Comment by micahgodbolt** [comment]
This is not in the new commandBar. Contextual menus are controlled via the button's contextual menus, not as part of the command bar.
