### ISSUE TITLE
BreadCrumb: doesn't have tooltip when item is trimmed and ellipsized. No way to know full text.

### ISSUE THREAD

**Issue by b-priyank** [OfficeDev/office-ui-fabric-react#2034]
### Bug Report

- __Package version(s)__: 2.20.2
- __Browser and OS versions__: All browsers, windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: (Blocking, High, Normal, Low) 

Products/sites affected: VSOnline 

#### Describe the issue:

Default max-width of breadcrumb item is 160px. After that it shows ellipsis.
There is no tooltip or other means to know full text of the ellipsized breadcrumb item.

#### Actual behavior:

Default max-width of breadcrumb item is 160px. After that it shows ellipsis.
There is no tooltip or other means to know full text of the ellipsized breadcrumb item.

#### Expected behavior:

There should be some means to know full text of the ellipsized tooltip item.

### If applicable, please provide a codepen repro:

https://codepen.io/anon/pen/bRWyRB

**Comment by micahgodbolt** [comment]
I took a look at this, but it was difficult with current tooltip host, and the wrapping container block value. I think with the move to flexbox that I'm currently creating a PR for, it should be possible.

**Comment by b-priyank** [comment]
@micahgodbolt Is this issue fixed in office-fabric?

**Comment by micahgodbolt** [comment]
Not yet. The previous layout method used for breadcrumb made it difficult to wrap with a tooltip host. Now that we are using flex box I can take another crack at it.

________________________________
