### ISSUE TITLE
How to get "Browser Back" functionality in this package

### ISSUE THREAD

**Issue by pradeemi** [OfficeDev/office-ui-fabric-react#2038]
### Bug Report

- __Package version(s)__: v4.9.1
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Blocking 

Products/sites affected: Internal Site, not published yet

I want to get "Back" functionality in this package. I searched for few articles which says that "Router" has "Browser history" using which we can achieve this, but router which is used in this package does not have "Browser History", therefore I am not able to get back functionality, please help me to get the same. Please find more details below:

Code Location: "office-ui-fabric-react/apps/fabric-website/src/"
File Location: "office-ui-fabric-react/apps/fabric-website/src/root.tsx"

Code to import router: 
import { Fabric } from 'office-ui-fabric-react/lib/Fabric';
import { Route, Router } from 'office-ui-fabric-react/lib/utilities/router/index';

Actual behavior: No "Browser history"

Expected behavior: I want to know how to get "Back Button" functionality in this project.

**Comment by micahgodbolt** [comment]
I don't believe we ever expected the Router to be exported from this package, as it was simply for internal documentation use.  Am I correct here @mikewheaton ?

**Comment by vertonghenb** [comment]
@mikewheaton There quite some issues about the router functionality, they might need a merge? Any thought how we'd like to approach these issues?

**Comment by mikewheaton** [comment]
Yes, everything in `apps/fabric-website` is for the documentation site and wasn't intended for use in other projects. Although it is all open source. 😄 

@vertonghenb, I'd recommend you look into more widely documented routers like [react-router](https://www.npmjs.com/package/react-router) for your project. While we'd consider pull requests that improve our own router, we're not likely to add functionality to it or investigate bugs unless we're having issues with our documentation site.
