### ISSUE TITLE
ContextualMenu displays at a wrong place when click DetailsList column header

### ISSUE THREAD

**Issue by zeedomD** [OfficeDev/office-ui-fabric-react#2048]
### Bug Report

- __Package version(s)__: 4.8.1
- __Browser and OS versions__: Chrome

#### Priorities and help requested (not applicable if asking question):

Requested priority: (High) 

#### Describe the issue:

We are using DetailsList to show a list of information. We support users click on the DetailsList header for each column, and then a ContextualMenu will be displayed at the column position.
In this version, when we clicks on the column, the contextual menu will be displayed on the left-top of the browser, which looks like the target element is not found.

This issue can repro with office-ui-fabric-react  master breach.

1. git clone https://github.com/OfficeDev/office-ui-fabric-react.git
2. cd to 'office-ui-fabric-react'
3. run rush install; rush rebuild; npm start.
4. open "http://localhost:4321/#/examples/detailslist". clicks on the column header of Example "Advanced DetailsList of 5000 items, variable row heights"

#### Actual behavior:

The contextual menu is displayed at the left-top of the browser rather than the column user clicks.
![image](https://user-images.githubusercontent.com/20253660/27427157-8e6c3d94-5770-11e7-8447-1e2d096ea421.png)

#### Expected behavior:

The contextual menu should be displayed at the clicked column.

### If applicable, please provide a codepen repro:

The master branch could repro this issue.
https://github.com/OfficeDev/office-ui-fabric-react.git

The new added code looks like will force update the DetailsList header and then the target element will be removed.

    const {
      onRenderDetailsHeader = this._onRenderDetailsHeader
    } = this.props;

    const DetailsHeader = (props: IDetailsHeaderProps) => onRenderDetailsHeader(props, this._onRenderDetailsHeader);

**Comment by dzearing** [comment]
This is now resolved in 4.10.1
