### ISSUE TITLE
Delete icon missing

### ISSUE THREAD

**Issue by irvalchev** [OfficeDev/office-ui-fabric-react#2050]
The Delete icon is missing in styles/IconCodes which makes Icon component with iconClass set to "Delete" not working (including in Button and IconButton components)

**Comment by mikewheaton** [comment]
I'm not sure how this happened, but it appears to be called "trash" instead of "delete".

**Comment by fuocor** [comment]
I guess that I am not going insane... 
I lost a few hours on this one, trying to figure out why it was no longer displaying

**Comment by atneik** [comment]
@irvalchev @fuocor Apologies for the glitch. What version of @uifabric/styling are you using? Looks like "trash" was named "delete" briefly, and then reverted back. Using "trash" instead should fix it for now, and for future versions.
