### ISSUE TITLE
MessageBar: UI regression for multi-line message bar that without actions.

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#2056]
### Bug Report

- __Package version(s)__: latest master
- __Browser and OS versions__: Chrome

![image](https://user-images.githubusercontent.com/7711735/27468288-9c5cf9e2-581b-11e7-9ee4-947caeb9fbd3.png)

**Comment by ipip2005** [comment]
Btw, seems the demo page is not following up the latest master https://dev.office.com/fabric#/components/messagebar
I should pull the master branch and serve locally to verify the regression.

**Comment by edsirko** [comment]
My page has two message bars: one with the close button and one without - and they both have this problem.
![image](https://user-images.githubusercontent.com/29665922/27499326-3fad357a-5831-11e7-8707-1c7fd8f44954.png)

**Comment by pablonete** [comment]
Another related styling bug: the dismiss icon is not right aligned (see screenshot by @edsirko). In single-line mode the ms-MessageBar-text gets `flex: 1 1 auto;`, which doesn't happen in multi-line.
