### ISSUE TITLE
Table component with pager

### ISSUE THREAD

**Issue by Jenan** [OfficeDev/office-ui-fabric-react#2057]
Hello,

is it possible get some component like a table with pager? 

I have only found the component like List, but it exists only scroll loading data but not table layout with classical pager.

Thank you.

**Comment by dzearing** [comment]
Thanks for the request. We will add it to our backlog.

**Comment by micahgodbolt** [comment]
Would a generic pager component work? You pass a large array into a render function, and specify how many items of the array to render at a time. In this case your render function renders a table, but it could be used to paginate anything.
