### ISSUE TITLE
refs.root breaks between 4.9.0 and 4.9.1

### ISSUE THREAD

**Issue by carruthe** [OfficeDev/office-ui-fabric-react#2058]
**Bug report **

I rely on a saved ref from the <Fabric> component to do some layout formatting for my Excel add-in. I used the ref property of the <Fabric> component, and save a reference to alias.refs.root. Between 4.9.0 and 4.9.1, this functionality broke - alias.refs.root is no longer defined.

React Version: 15.4.2 up to 15.6.1
Browser: Reproduced on Safari and Chrome (MacOS), and Chrome (Windows)

Here is a CodePen reproducing the behavior:

https://codepen.io/tcarruthers/pen/vZJeaw

Thanks!

Nick

**Comment by atneik** [comment]
Thanks Nick!

@dzearing Do you think changes in Fabric.tsx in https://github.com/OfficeDev/office-ui-fabric-react/pull/2026 PR might be causing this?

**Comment by carruthe** [comment]
FYI - I found a CSS workaround to this, so I am no longer relying on the alias.refs.root to get the React-created wrapper div:

[Add CSS to React-Created Elements](https://stackoverflow.com/questions/41259244/add-css-to-react-created-elements-like-data-reactroot)

**Comment by erichdev** [comment]
Closing since workaround was found and because use of `this._resolveRef()` is [recommended ](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/ghdocs/BESTPRACTICES.md#for-gathering-refs-avoid-string-refs-use-resolve-functions). Please reopen if this is still an issue.
