### ISSUE TITLE
DetailsList and Groups confusion

### ISSUE THREAD

**Issue by cobbs-totem** [OfficeDev/office-ui-fabric-react#2064]
I'm making a DetailsList component, where the items may be grouped and even nested-grouped (one level).  There could be this scenario:

Group 1:
  - item 1
  - item 2
  - NestedGroup A
    - item 3
  - NestedGroup B
    - item 4

Group 2:
  - NestedGroup C
    - item 5
  - NestedGroup D
    - item 6

I'm to assume I have a total of 6 items and 6 groups to pass to DetailsList?  

I can render Group1 and its items just fine, by specifying a "count" of 2 for Group 1.  However a "count" of 0 for Group 2 results in the header not rendering at all and NestedGroup C/D left without a parent in the final results.  

If I include all "ancestor items" in the "count" then Group 1 has a count of 4, and items 3 and 4 get rendered in duplicate.  Not what I want, either.

Then there's the confusion of using the "children" property on each IGroup.  Why is there a "level" property as well as a "children" property.  Seems like if you specify one, then you know the other.  If I take the route of using the "children" property to nest the groups, then I can render Group 2 just fine, but Group 1 will not include "item 1" and "item 2".

The docs and examples are not clear on accomplishing this.

**Comment by ryanwilliamquinn** [comment]
@micahgodbolt did you ever sort this out? I have the same question.

**Comment by russgove** [comment]
Hi, I  git it working after a bunch of trial an error. It's easy to do with lodash. 
i documented how to do it at https://yetanothersharepointblog.wordpress.com/2017/06/23/using-the-office-ui-fabric-grouped-detailslist-in-react-bases-spfx-webparts/
