### ISSUE TITLE
Dialog not showing close button for blocking dialogs

### ISSUE THREAD

**Issue by stephenzsy** [OfficeDev/office-ui-fabric-react#2066]
### Bug Report

- __Package version(s)__: v4.10.2
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: (Blocking, High, Normal, Low) : High

Products/sites affected: (if applicable)

#### Describe the issue:

Blocking dialogs are not showing close button even as type set to be DialogType.close

#### Actual behavior:

Blocking dialogs are not showing close button when type is DialogType.close or showCloseButton set to be true in props

#### Expected behavior:

Blocking dialogs should be showing close button when DialogType is close or explicitly set in props.

in Dialog/Dialog.tsx
`
        {...dialogContentProps}
          showCloseButton={ isBlocking !== undefined ? !isBlocking : !modalProps.isBlocking }
          topButtonsProps={ topButtonsProps ? topButtonsProps : dialogContentProps.topButtonsProps }
`

**Comment by betrue-final-final** [comment]
What is the scenario? What does the dialog ask or say?

In general, if you need close, then you should either use a non-blocking dialog, or use a specific close button in the bottom area. 

The function of a blocking dialog is to just make sure that someone taps one of the commit buttons. Ideally, the person should make a choice, and one of them could just be close. It really depends on the purpose of the dialog. Some are informational, and a close may be the only button for example. The main function is to prevent accidental dismissal with light dismiss. They have to acknowledge it in some way. Of course many really want to force a choice, such as Delete or Cancel, for example.

Here are the two examples I speak of
![image](https://user-images.githubusercontent.com/20363037/27552397-1a733d40-5a5c-11e7-8d50-018a7574d7d7.png)
