### ISSUE TITLE
ContextualMenu & Dropdown: Height of row is not updated

### ISSUE THREAD

**Issue by atneik** [OfficeDev/office-ui-fabric-react#2067]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: (if applicable)

#### Describe the issue:

Height of a Contextual & Dropdown component is not updated

#### Actual behavior:

Height of their rows is set to 36px

#### Expected behavior:

Height of their rows should beset to 32px

**Comment by betrue-final-final** [comment]
This should also include dropdown.
