### ISSUE TITLE
Selection, find out selection index

### ISSUE THREAD

**Issue by martlaboloa** [OfficeDev/office-ui-fabric-react#2074]
**_Is there way to find out index of selected item(or items) out of the selection object._**

It has **getSelection** method but that only returns array of items, and there is no way to know which index is selected.

_Maybe you should add **getSelectedIndices**, or something like that._

**Comment by micahgodbolt** [comment]
The returned object should have a key, are you looking for a numerical index of the item's position in the parent array?

**Comment by martlaboloa** [comment]
yes. i need that to user in **setKeySelected** method.
