### ISSUE TITLE
GroupedList: Various fit and finish issues

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#2076]
### Bug Report

Are you willing to submit a PR to fix? (Yes)
Requested priority: (Normal) 

#### Describe the issue:

There are various issues with the current group item for a grouped list:

1. Expand arrow is too small
2. There is no space between the group name and count
3. The height is too tall, should be the same as a file
4. Margin is too close to left of selection circle

![image](https://user-images.githubusercontent.com/20363037/27598817-84bb3e86-5b1b-11e7-894a-5202e0d7574b.png)

**Comment by atneik** [comment]
@betrue-final-final if you could add redlines for the Design screenshot that will be awesome!
