### ISSUE TITLE
Fabric website shows "This component is missing properties."

### ISSUE THREAD

**Issue by siddhant92** [OfficeDev/office-ui-fabric-react#2078]
### Bug Report

- __Package version(s)__: (fill this out) Live website
- __Browser and OS versions__: (fill this out if relevant) Chrome 59, MacOS Sierra

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low) 
Normal

Products/sites affected: (if applicable)
https://dev.office.com/fabric#/components/facepile
https://dev.office.com/fabric#/components/breadcrumb

#### Describe the issue:

The live website of the Office UI Fabric has bugs, showing yellow boxes in many component interface blocks. Check links above for the example. 

#### Actual behavior:

"IFacepile interface: This component is missing properties. Please provide properties or remove the table from the example." Screenshot attached below. 

<img width="1536" alt="screen shot 2017-06-27 at 5 00 10 pm" src="https://user-images.githubusercontent.com/19247189/27615042-4224dc96-5b5a-11e7-9f97-4ad789351b68.png">

#### Expected behavior:

Not sure what the expected behaviour should be. But the live website definitely is missing properties as per the error being displayed.

**Comment by atneik** [comment]
@siddhant92 Thanks for reporting the issue. I suspect this is happening in components that have an empty interface (i.e. IComponent, which is majority of them). And we should just handle this while parsing for website and not show this warning.
