### ISSUE TITLE
MessageBar multiline without padding-right and padding-bottom

### ISSUE THREAD

**Issue by stephenzsy** [OfficeDev/office-ui-fabric-react#2080]
### Bug Report

- __Package version(s)__: v4.10.2
- __Browser and OS versions__: Chrome 59 on Windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: (if applicable)

#### Describe the issue:

MessageBar multiline=true, onDismiss=null, actions=null

#### Actual behavior:

No padding-bottom and no padding-right

#### Expected behavior:

consistent padding

### If applicable, please provide a codepen repro:

<img width="380" alt="capture" src="https://user-images.githubusercontent.com/1330448/27615314-26ea6fca-5b5c-11e7-96ee-e1195d51a8d8.PNG">

**Comment by micahgodbolt** [comment]
Can you create a codepen with this issue reproduced? It appears to be working on dev.office.com/fabric

![image](https://user-images.githubusercontent.com/1434956/27705130-ce8d173a-5cc1-11e7-838b-e45f9186f102.png)

**Comment by micahgodbolt** [comment]
Nevermind, I see it in master, and it hasn't reached website yet.
