### ISSUE TITLE
Type 'ISelectionZoneProps' has no properties in common with type 'IBaseProps'.

### ISSUE THREAD

**Issue by bwinkler-dg** [OfficeDev/office-ui-fabric-react#2093]
### Bug Report

- __Package version(s)__: 2.34.2

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: -

#### Describe the issue:

With the upgrade of the dependant package @uifabric/utilities to version 1.10.4 I get a lot of compiler errors of this kind: 

ERROR in [at-loader] ./node_modules/office-ui-fabric-react/lib/utilities/selection/SelectionZone.d.ts:14:58
    TS2559: Type 'ISelectionZoneProps' has no properties in common with type 'IBaseProps'.

#### Actual behavior:

Project does not compile.

#### Expected behavior:

Project does compile

**Comment by SpoonsJTD** [comment]
What version of typescript are you using? I upgraded to 2.4 and started getting the same issue. It seems 2.4 introduces some 'weak typing' checks that are causing quite a few issues with libraries that used to work. I downgraded to 2.3.4 and these "has no properties in common with type" errors went away.

**Comment by bwinkler-dg** [comment]
Yes, I can confirm it works with typescript 2.3.4. The upgrade to 2.4.1 caused the error.

**Comment by leddie24** [comment]
This should be fixed from #2186.  Feel free to reopen if this issue is still occurring.
