### ISSUE TITLE
Command bar buttons have double padding to left of text when no icon is present

### ISSUE THREAD

**Issue by annikanami** [OfficeDev/office-ui-fabric-react#2094]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) 

Products/sites affected: (if applicable)

**Comment by micahgodbolt** [comment]
This change has already been done in the new commandbar. It should be out with the next major release.

**Comment by micahgodbolt** [comment]
These are simple changes, we can push the fixes out in current product as next major release might still be a bit.

**Comment by erichdev** [comment]
Seems this is resolved, please reopen if it's still an issue
