### ISSUE TITLE
Remove margin between buttons in command bar

### ISSUE THREAD

**Issue by annikanami** [OfficeDev/office-ui-fabric-react#2096]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) 

Products/sites affected: (if applicable)

**Comment by micahgodbolt** [comment]
This change has already been done in the new commandbar. It should be out with the next major release.

**Comment by annikanami** [comment]
Can this change be pushed earlier than the next major release if there is a substantial delay between now and when OWA will receive the updates? Or do you have an eta on when we would get those changes?

**Comment by micahgodbolt** [comment]
I assigned @leddie24 to work on this in the current component. The new component is still in development, so it might be a little while until it reaches production.
