### ISSUE TITLE
Breadcrumbs overflow in wrong order

### ISSUE THREAD

**Issue by rrdelaney** [OfficeDev/office-ui-fabric-react#2104]
### Bug Report

- __Package version(s)__: 4.13.0
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Blocking

Products/sites affected: C3

#### Describe the issue:

Instead of overflowing the head of the items list, the tail of the items list get put into an overflow.

#### Actual behavior:

When I have the following items: `Item1, Item2, Item3, Item4` with a max render of two items, I get
the following breadcrumb layout:

```
..., Item1, Item2
```

#### Expected behavior:

When I have the following items: `Item1, Item2, Item3, Item4` with a max render of two items,
_should_ get the following breadcrumb layout:

```
..., Item3, Item4
```

### If applicable, please provide a codepen repro:

https://codepen.io/anon/pen/eRVExb

**Comment by micahgodbolt** [comment]
Good catch! Was using the same logic as in the command bar, which pulled links off the other side. PR incoming.

**Comment by micahgodbolt** [comment]
![image](https://user-images.githubusercontent.com/1434956/27747765-810d01bc-5d81-11e7-8ebb-8683db60b09b.png)

**Comment by rrdelaney** [comment]
Thanks! 😄

**Comment by micahgodbolt** [comment]
adding a test to make sure we don't mess up the order again

**Comment by micahgodbolt** [comment]
Eh, tests are being troublesome. I'll get the fix in and then work on the tests.
