### ISSUE TITLE
DocumentCard: errorImageSrc not working, deprecated but no alternatives

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#2107]
See the codepen example. https://codepen.io/anon/pen/EXQRzg?editors=0010

The `errorImageSrc` is not working for DocumentCard. Although I know from documentation that `errorImageSrc` has been deprecated. But I didn't find any alternative way to do it yet.

Is there something similar to the onLoadingStateChange in `Image` component?

**Comment by atneik** [comment]
I think we should remove `errorImageSrc` from DocumentCard props as it were to be removed removed at >= v2.0.0.

There is a onLoadingStateChange callback in `Image` component, which you can use to get `ImageLoadState` and check for `error` state.

**Comment by ipip2005** [comment]
Hi @atneik Can we also use this `onLoadingStateChange` in `DocumentCard`? Cuz if the `errorImageSrc` will be removed in `DocumentCard`, there will be no way for us to provide a backup image in `DocumentCard`.

**Comment by ipip2005** [comment]
Currently it looks like the feature of providing back image is `cut` in newer versions? Hope to have a way to do that!

**Comment by papigers** [comment]
Still no solution for this, `errorImageSrc` was removed, and can't use `onLoadingStateChange` on `DocumentCardPreview`. Solution?
