### ISSUE TITLE
Cannot navigate to browser bar with panel open

### ISSUE THREAD

**Issue by kcurlett** [OfficeDev/office-ui-fabric-react#2113]
### Bug Report

- __Package version(s)__: 4.12.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No, wouldn't know how. 

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) Outlook (In development)

#### Describe the issue:

When opening a panel, when tabbing through available elements I can sometimes navigate out of the panel to the browser bar, but with most panels the focus is trapped in the panel. I have tried using forceFocusInsideTrap={false}, but this did not enable navigation to the browser bar. 

#### Actual behavior:

The focus is often trapped in the panel. 

#### Expected behavior:

You should be able to navigate out of the panel to the browser bar for accessibility reasons. 

### If applicable, please provide a codepen repro: https://codepen.io/MLoughry/pen/BRWqyb
All panels on: https://dev.office.com/fabric#/components/panel

Currently unable to make a panel that doesn't trap focus, but I do have one in my product.

**Comment by atneik** [comment]
Definitely seems like an issue, where the focus gets trapped.

**Comment by micahgodbolt** [comment]
This appears to be our default behavior for many of our "modal" type elements. Dialog is the same thing. @betrue-final-final should we be able to tab out of a panel or dialog into the browser address bar?

**Comment by betrue-final-final** [comment]
No, if you tab out of a modal dialog, then you will get a blind user hopelessly lost. Esc should dismiss the dialog.

**Comment by betrue-final-final** [comment]
Or panel.

**Comment by micahgodbolt** [comment]
So then this is working as expected. Focus should be trapped in the panel/modal/dialog, and use should not be able to tab out of it. 

My only question would be about the times that focus does not get trapped. We certainly want our experience to be consistent. @kcurlett can you describe a time where focus is not trapped?

**Comment by betrue-final-final** [comment]
One other option would be that one could tab into the address bar, but tabbing into the page just returns to the dialog or panel. In no case do we ever want the ability to tab into the page below. 

I would say the general rule is "Z-order on a page can only move down with ESC, a Cancel, or Close button.

**Comment by kcurlett** [comment]
I agree with @betrue-final-final, that you shouldn't be able to tab to the page below but should be able to (perhaps only with a setting enabled) navigate to the address bar. 

The navigation to the address bar seems to happen when you add tabIndex={-1} to elements in your panel. Here is a codepen: https://codepen.io/anon/pen/yXqyze

I added a tabIndex={-1}, and now you can focus on elements in the panel using shift+tab (and focus is trapped in the panel with shift+tab), but tab without shift lets you navigate to the address bar, and to the content below. This seems like a bug, independent of the debate about navigation to address bar. 

I am no longer able to repro this in my actual code, but the behavior was similar to this codepen.

**Comment by betrue-final-final** [comment]
Yes, I realized that getting to the address bar could be important, and you still wouldn't have to get people lost. Thanks @kcurlett!

**Comment by micahgodbolt** [comment]
@betrue-final-final who should we contact to get final say on this? Is the ability to get to hit ctrl+L enough to get you back to the address bar? Or should it always be part of the tab rotation? This seems like a pretty big change in the functionality for an incredibly popular component. I wouldn't want to push this in without getting their feedback as well.

**Comment by betrue-final-final** [comment]
@cschlechty , @martellaj  should be a good second set of ears.

**Comment by cschlechty** [comment]
The WACs have trapped in regions and replied on F6 to move between region
and jump between page and address bar. I think this is pretty well
documented. We could add the notes to out repo.

**Comment by kcurlett** [comment]
Neither I nor the person who requested the ability to tab to the nav bar new about ctrl+L when making the request. 

There is still the bug of some panels being able to tab to the nav bar. I can close this and re-open as "Can navigate to browser bar with panel open" if that is desired.  But there should be some bug opened, since we should be consistent about if you can tab to the nav bar or not.

**Comment by wonskarol** [comment]
I'm using FocusTrapZone in my project and I noticed similar issue: sometimes focus gets out from the trap to the address bar, but with the next TAB it comes back to the trap.

Example 1 - FocusTrapZone works well: https://codepen.io/anon/pen/qXaxVM/
Example 2 - focus gets out when you hit switch button: https://codepen.io/anon/pen/gxwvJa
(in code pen iframe with preview will be focused, but on a blank HTML page it goes to address bar).

I think focus gets out from trap when the last activeElement disappears. Is there a way to force focus to be inside and focus first focusable element?
