### ISSUE TITLE
Panel jumps across screen on resize

### ISSUE THREAD

**Issue by kcurlett** [OfficeDev/office-ui-fabric-react#2114]
### Bug Report

- __Package version(s)__: 4.12.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No, wouldn't know how. 

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: (if applicable) Outlook

#### Describe the issue:

The panel jumps and does weird resizes when changing browser width. 

#### Actual behavior:

Take any panel that isn't small (medium, large, or xl panels), anchored to the right, and you resize your browser with the panel open, from a large window to a small one. As you shrink the browser the panel will eventually jump to the left, and resize itself. 

#### Expected behavior:

The panel shouldn't resize in this way, and definitely shouldn't jump like it does. 

### If applicable, please provide a codepen repro:
It happens to all the not-small panels on: https://dev.office.com/fabric#/components/panel

**Comment by atneik** [comment]
@kcurlett thanks for reporting. Looks like breakpoints are not ramping properly.

**Comment by micahgodbolt** [comment]
I can't seem to repro this problem in IE11 or chrome. Can you tell me what browser/version you are using and possibly a gif of the jumping?

**Comment by atneik** [comment]
@micahgodbolt if you open a medium+ panel and resize the window width, you'll notice that the panel width doesn't ramp up as width is reduced. The jumps from almost covering the window to half of it at 640px

**Comment by micahgodbolt** [comment]
I believe that is by design. Under a given breakpoint it changes from medium to full. I don't consider this a bug.

**Comment by kcurlett** [comment]
Here is a link of the effect in chrome (SharePoint would only let me set the permissions to Microsoft only, not everyone): 

https://microsoft-my.sharepoint.com/personal/kcurlett_microsoft_com/_layouts/15/guestaccess.aspx?guestaccesstoken=TZR08DqkiiRMaiomZ%2b85lPFwmKZ%2b370lpMhoq%2b78GXo%3d&docid=2_043b4efe3a97747efa5bcad228697b88c&rev=1

The problem I have is specifically with a medium panel on top of a large/xl panel. If your browser width is less than 1024px the medium panel jumps in size from 640px to (screenWidth - 50px). 

This causes an effect where if your browser is more than 1024px in width you have a nice overlay with the top panel on the right, and the bottom panel sticking out on the left, but if your screen is less than 1024px the top panel covers effectively the entire screen, and hides the panel underneath it.

**Comment by kcurlett** [comment]
If this is by design, it seems like the breakpoint is set at too large of a value. Many users do not have large screens, so we are limiting them to only one panel size. Is there a way to override this breakpoint?

**Comment by micahgodbolt** [comment]
Yeah, I can see how the medium panel jumps a bit. Diving into this component makes me want to revisit the entire sizing logic. I've got a feeling that with a little bit of flex box, and sizes determining nothing but flex-basis, it'd be much easier to support this component (and require fewer media queries).

**Comment by micahgodbolt** [comment]
Well that was a fun refactor. Still a little work to do, but thinking of the panel as a flex item makes this a ton easier.

**Comment by battletoilet** [comment]
The panels were setup this way so this is not considered a bug. But we will eventually look into this further.
