### ISSUE TITLE
MessageBar: Text needs flex-grow:1

### ISSUE THREAD

**Issue by milanvdmria** [OfficeDev/office-ui-fabric-react#2117]
### Bug Report

- __Package version(s)__: 4.13.2

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

#### Describe the issue:

MessageBar close Icon is not using position absolute in multiline

#### Actual behavior:

close icon is right after text

#### Expected behavior:

Close icon is on the same position as multiline false

### If applicable, please provide a codepen repro:

https://codepen.io/anon/pen/awYNRd

**Comment by micahgodbolt** [comment]
nice catch. we'd been testing with full length text, so didn't notice that the text field collapsed in. Solution will be flex-grow so that text takes up all the extra space.

**Comment by micahgodbolt** [comment]
![image](https://user-images.githubusercontent.com/1434956/27802485-e777c492-5fd8-11e7-97f4-99699a8099b6.png)
