### ISSUE TITLE
List View not working as expected

### ISSUE THREAD

**Issue by formanter** [OfficeDev/office-ui-fabric-react#2120]
### Bug Report

- __Package version(s)__: current master branch
- __Browser and OS versions__: all

The List View is not working when used as a control in a simple example as a react component. Although the generated HTML seems to be correct, the stylesheet is not used, so the pure HTML is displayed. 

In addition, a simple example on how to implement this component would be helpful, especially the "inbox" example.

**Comment by micahgodbolt** [comment]
What type of example are you looking for? I assume you've seen the code examples on https://dev.office.com/fabric#/components/list?

As far as styles, we are using CSS Modules so when you import the component into your application the styles should be printed to the page along with the component. You don't need to reference a css stylesheet.

**Comment by formanter** [comment]
I have seen the example for List on https://dev.office.com/fabric#/components/list, but unlike the other examples, this List example is not working, if I create a simple page with this code.

**Comment by formanter** [comment]
to be more concrete: I used the DocumentCard example from here https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/office-ui-fabric-react/src/components/DocumentCard and just inserted the sample code from above. Styles are not applied to the list component, just pure HTML is rendered.

**Comment by micahgodbolt** [comment]
The list component does not actually have any CSS associated with it. In our examples we are using some custom CSS to create that display

https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/List/examples/List.Basic.Example.scss

**Comment by formanter** [comment]
Ok, if I go to dev.office.com and read the documentation, it appears a bit different... anyway... but in the example for mailbox, the checkboxes are not clickable... is there still something missing? the pure JavaScript version is working instead...

**Comment by micahgodbolt** [comment]
@formanter the list component is ONLY meant to display a list of content. What you do with that content is up to you (styles and functionality). There is nothing built into the list component that allows you to automatically create clickable mail items. It's just an example of what  you could do.

**Comment by erichdev** [comment]
Closing since there hasn't been any response. Please open a new issue if you experience any problems
