### ISSUE TITLE
Updating to latest version

### ISSUE THREAD

**Issue by fantua** [OfficeDev/office-ui-fabric-react#2121]
### Bug Report

- __Package version(s)__: 2.30.1

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: Blocking

Products/sites affected: (if applicable)

#### Describe the issue:

In version 2.30.1 I was loading Office UI Fabric styles in my `Root` component in that way:
```js
import 'office-ui-fabric-react/dist/css/fabric.css';
```

Now I can't do that. How to load styles? I'am using this (from your README): 
```html
<link rel="stylesheet" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/5.0.1/css/fabric.min.css">
```
Is v.5.0.1 correct? Also after adding this styles I got [a lot of warrnings](https://image.prntscr.com/image/Z7gIvYVGTR21LkQMwzbIng.png) in console.

**Comment by fantua** [comment]
cc @dzearing @mikewheaton

**Comment by fantua** [comment]
guys? 😞

**Comment by nguyenhuuhanhlam** [comment]
I also encountered a similar case, hope it will be corrected in the future
