### ISSUE TITLE
DatePicker has a 17px margin making UI to appear incorrect

### ISSUE THREAD

**Issue by justinmwarner** [OfficeDev/office-ui-fabric-react#2122]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No - not 100% this is expected

Requested priority: Low

Products/sites affected: N/A

#### Describe the issue:
If we have a "form" of Textfield, DatePicker, Dropdown. We see the DatePicker has a 17px bottom margin that makes the UI appear incorrect

![image](https://user-images.githubusercontent.com/2288818/27799752-43359be6-5fcb-11e7-808f-e78dffa878a4.png)

#### Actual behavior:

Has a margin

#### Expected behavior:

The margin should be set by the consumer if they want one. The default appearance should be shared between all form-like controls (in my opinion)

**Comment by micahgodbolt** [comment]
Our current plan is to remove all input bottom margins in our next major release. This'll cause a bunch of visual regressions for those depending on those margins, so we wanted to address them all at one time.

**Comment by justinmwarner** [comment]
Thanks for the response @micahgodbolt 

I'd like to link our item with this.  Do you have an item tracking this or should I use this issue?

**Comment by micahgodbolt** [comment]
Here you go @justinmwarner  #2135
