### ISSUE TITLE
TextField: Narrator not reading the description and error field of TextField component

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#2130]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: Edge, Windows 10 prod build 15063, Narrator

#### Priorities and help requested (not applicable if asking question):

Requested priority: (Normal) 

Products/sites affected: web parts

#### Describe the issue:

When keyboard focus into the input of TextField component, the description is not read by Narrator

#### Actual behavior:

Narrator not reading the description field

#### Expected behavior:

Narrator should read the description field after label and input information.

### If applicable, please provide a codepen repro:

http://dev.office.com/fabric#/components/textfield
Open Narrator and try to access to the TextField with description or error message field.

**Comment by ipip2005** [comment]
Error is reading, but description still not reading

**Comment by jordandrako** [comment]
@ipip2005 I can't reproduce this, the narrator in edge reads the description. Can you confirm if you're still getting this bug?
