### ISSUE TITLE
Choice group: Narrator focus boundary is improper on the ChoiceGroup option

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#2131]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: 
-- Browser: Edge
-- OS build: 16215.rs_prerelease.170603-1840
-- Screen Reader: Narrator
-- Screen Reader version: NA
-- Platform (if needed): Web

#### Priorities and help requested (not applicable if asking question):

Requested priority: (Low) 

Products/sites affected: Web parts

#### Describe the issue:

When Narrator is opened, focus to the ChoiceGroup option. It shows:

![image](https://user-images.githubusercontent.com/7711735/27851371-c2f2a2c6-618c-11e7-848e-790194cf624a.png)

#### Actual behavior:

The Narrator focus is on a small box inside option.

#### Expected behavior:

The Narrator focus is around the whole option item.

### If applicable, please provide a codepen repro:

http://dev.office.com/fabric#/components/choicegroup

Try to access to any ChoiceGroup with Images by TAB key and see Narrator focus.

**Comment by atneik** [comment]
@ipip2005 Thanks for reporting this issue
