### ISSUE TITLE
Pivot content moving because PivotItem width changes when selected

### ISSUE THREAD

**Issue by Fensterbank** [OfficeDev/office-ui-fabric-react#2133]
### Bug Report

- __Package version(s)__: > 4.5.*
- __Browser and OS versions__: any

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Low

#### Describe the issue:

The width of a selected PivotItem differs from a unselected PivotItem.
This results in a moving content when interacting with a Pivot component.
Can be easily reproduced in the examples: http://dev.office.com/fabric#/components/pivot

It happens for all types, but the tab style example words "Foo", "Bar", "Baz" are too short to really see it.

#### Actual behavior:

Following PivotItems are moving when a PivotItem is selected or unselected.

#### Expected behavior:

All PivotItems should stay in the same position.

**Comment by atneik** [comment]
@Fensterbank Thanks for reporting this issue.

**Comment by aadhars** [comment]
This should get address with this PR: https://github.com/OfficeDev/office-ui-fabric-core/pull/658
