### ISSUE TITLE
How to Implement Features of Pivot

### ISSUE THREAD

**Issue by stephen-oconnor** [OfficeDev/office-ui-fabric-react#2134]
I don't have a bug to report, i just cannot get the Pivot component to do what it says it does.

From the [docs](https://dev.office.com/fabric#/components/pivot):
- Tapping on a pivot item header navigates to that header's section content.
- Swiping left or right on a pivot item header navigates to the adjacent section.
- Swiping left or right on section content navigates to the adjacent section.
- Pivots are stationary when all pivot headers fit within the allowed space.
- Pivots carousel when all pivot headers don't fit within the allowed space.

Is this functionality standard or is there something that needs to be done to activate/use it? Even on the docs site the pivots do not 'carousel when all pivot headers don't fit within the allowed space' for example.

Thanks.

**Comment by cschleiden** [comment]
I don't think this behavior has been implemented, unfortunately.

**Comment by stephen-oconnor** [comment]
Wow. That's really misleading then... If it has not been implemented and is not a feature I don't understand why it is in the docs.

I have since built my own tabs component using React, which was actually really beneficial, every cloud and all that, however, this text should not be in the docs if it is not available, I can't have been the only one who assumed it was part of the component.

**Comment by araver** [comment]
Can this be reopened? Or at least update the documentation.
