### ISSUE TITLE
TextField: onChanged is not fired for TextField on IE11 for IME input when confirming through keyboard

### ISSUE THREAD

**Issue by huang9** [OfficeDev/office-ui-fabric-react#2139]
### Bug Report

- __Package version(s)__: 4.14.1
- __Browser and OS versions__: win10 + IE11 (lower IE version or other platform not tested)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
Yes (working on it)

Requested priority: (Blocking, High, Normal, Low) 
High

Products/sites affected: (if applicable)

#### Describe the issue:
When using TextField, inputting IME and confirm IME input with keyboard (type a number or select with mouse), it does not fire onChanged event. So far only see this to repro on IE11 (other browser like Chrome/Edge/Firefox is fine)

1. Go to https://fabricreact.azurewebsites.net/fabric-react/master/#/examples/textfield
2. Also open debugger console
3. Go to "Default TextField" demo
4. Switch to Chinese input method (or other CJK input methods)
5. Type "nihao" (which is Chinese pingyin for 你好 (how are you)
6. When you see a little popup, select with keyboard by a number, or select without mouse to confirm the IME
7. Watch console

#### Actual behavior:
你好 is confirmed, and you also see 你好 in console

#### Expected behavior:
你好 is confirmed, but 你好 is not seen in console
This is because the onChanged is not fired when IME is confirmed

**Comment by huang9** [comment]
I feel like the issue is either rooted in IE11 or react Input is closest to take a workaround. Fabric control can also fix the issue by hooking on compositionend event and fires onChanged

**Comment by huang9** [comment]
I can take a stab on the issue. Can anyone assign this on me?

**Comment by huang9** [comment]
Looks like this is already addressed in https://github.com/OfficeDev/office-ui-fabric-react/pull/762. The demo page (https://fabricreact.azurewebsites.net/fabric-react/master/) seems a bit disconnected as the issue can still be reproduced there.

**Comment by atneik** [comment]
@huang9 The demo page above seems to be old. Can you please confirm this issue is fixed in latest bits and also it is not reproduced in documentation? I'll assign this to you. Thanks!

**Comment by huang9** [comment]
Confirmed that it is fixed through https://github.com/OfficeDev/office-ui-fabric-react/pull/762. Issue resolved.
