### ISSUE TITLE
Website: Link to brand guidelines PDF doesn't work

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#2140]
On the [Office brand icons](https://dev.office.com/fabric#/styles/brand-icons) page there is a link to brand guidelines that is broken. It's pointed at this URL: https://dev.office.com/files/OfficeBrandGuide_16Sep2016.pdf

**Comment by Jahnp** [comment]
This was fixed with #1712. The change just needs to be deployed. I'll follow up here when that's done.

**Comment by Jahnp** [comment]
This has been fixed.
