### ISSUE TITLE
Inconsistent icon names.

### ISSUE THREAD

**Issue by VincentBailly** [OfficeDev/office-ui-fabric-react#2146]
### Bug Report

- __Package version(s)__: 4.15.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes
Requested priority: Normal
Products/sites affected: LivePersonaCard

#### Describe the issue:

There is a missmatch of the icon names between these two files:
packages/styling/src/styles/IconCodes.ts
packages/office-ui-fabric-react/src/components/Icon/IconName.ts

This makes it impossible to use IconNames.ts to constrain the icon names we pass to the props of our Buttons. (In our case, trying to use the icon "Planner" results in a failing build while trying to use "PlannerLogo" does build but the icon does not work.

#### Actual behavior:

This makes it impossible to use IconNames.ts to constrain the icon names we pass to the props of our Buttons. (In our case, trying to use the icon "Planner" results in a failing build while trying to use "PlannerLogo" does build but the icon does not work.

#### Expected behavior:

We can use IconName.ts as a guide for what icon names we can use or not.

### If applicable, please provide a codepen repro:

https://codepen.io/VincentBailly/pen/eRjVKr

**Comment by atneik** [comment]
This seems like a bug. @mikewheaton can we have a single source for the icon names so that we don't have to maintain two sets of files?

**Comment by erichdev** [comment]
Believe this is resolved with the separate icons package, please reopen if this is still an issue
