### ISSUE TITLE
Dropdown: Keyboard focus is incorrect when menu is expanded

### ISSUE THREAD

**Issue by leddie24** [OfficeDev/office-ui-fabric-react#2152]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Low

Products/sites affected: (if applicable)

#### Describe the issue:

Repro steps:

1. Go to Customized Example
2. Select "Option a" via mouse control
3. Press Enter to expand the dropdown menu
4. Press up until "Option a" is selected. 
5. Pressing up once more will select the dropdown
6. Pressing up again will select "Option d"

#### Actual behavior:

See Repro steps

#### Expected behavior:

Dropdown should stop at Option a, or first valid option, and not selection the Dropdown on key up again.

**Comment by micahgodbolt** [comment]
I can't seem to replicate the issue in master. Can you demonstrate the problem you are seeing?

![dropdown](https://user-images.githubusercontent.com/1434956/28029214-20613ee8-6554-11e7-98e6-6bf43224b54a.gif)

**Comment by leddie24** [comment]
Looks like it's fixed, an unrelated change to FocusZone may have fixed this. It's not reproing for me anymore.
