### ISSUE TITLE
Pivots do NOT carousel when all pivot headers don't fit within the allowed space.

### ISSUE THREAD

**Issue by trevonmckay** [OfficeDev/office-ui-fabric-react#2165]
### Bug Report

- __Package version(s)__: office-ui-fabric-react 4.16.0
- __Browser and OS versions__: Safari 10.1 macOS 10.12.4

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Blocking 

Products/sites affected: (if applicable)

Human Resource Portal for our Enterprise isn't able to display all the required employee documents because many pivots are hidden.

#### Describe the issue:

The documentation states that Pivots will carousel when the headers cannot fit into the given space however this is not ture

#### Actual behavior:

The Pivot headers overflow and are hidden

#### Expected behavior:

The Pivots should be able to scroll horizontally in a carousel fashion

**Comment by quangleminhvn** [comment]
Hi guys
Any update for this ?

**Comment by dimipankratz** [comment]
Any recommendations or suggestions how to use pivot without the carousel? Are there any alternative ways, e.g., wrapping the items into the next line?
