### ISSUE TITLE
Need ability to control CommandBar's overflow menu contextual menu props

### ISSUE THREAD

**Issue by willsmythe** [OfficeDev/office-ui-fabric-react#2169]
We want all sub menus presented off a command bar to **not** have a "beak". This is possible with regular command bar items because `CommandBar` uses an item's `subMenuProps` (if provided) as props for the contextual menu that it presents:

```js
// regular command bar item "onClick"
this.setState({
   expandedMenuId: ev.currentTarget.id,
   expandedMenuItemKey: item.key,
   contextualMenuProps: this._getContextualMenuPropsFromItem(item), /* HAS CONTROL OF PROPS */
   contextualMenuTarget: ev.currentTarget 
});
```

However, the contextual menu props for the **overflow** menu are not controllable by consumers, which prevents us from controlling direction, beak visibility, etc to match our other command bar items.

```js
// overflow item "onClick"
this.setState({
  expandedMenuId: ev.currentTarget.id,
  expandedMenuItemKey: OVERFLOW_KEY,
  contextualMenuProps: { items: this.state.renderedOverflowItems }, // NO WAY TO CONTROL PROPS
  contextualMenuTarget: ev.currentTarget
});
```

### New `defaultSubMenuProps` prop on  `ICommandBarProps` 

Lets a consumer specify default contextual menu props for all contextual menus (both those for regular commands and the one for the overflow). This would make it easier to create consistency across all menus that get presented from command bar. In our case, we would do something like:

```tsx
let subMenuProps = {
    directionalHint: DirectionalHint.bottomLeftEdge,
    isBeakVisible: false,
};


<CommandBar
          items={ filteredItems }
          overflowItems={ filteredOverflowItems }
          farItems={ filteredFarItems }
          defaultSubMenuProps={ subMenuProps }
        />
```

###  New `overflowMenuProps` prop on  `ICommandBarProps`:

```typescript
export interface IContextualMenuProps extends React.Props<ContextualMenu>, IWithResponsiveModeState {
  
   ...

  /**
   * Default items to have in the overflow menu
   */
  overflowItems?: IContextualMenuItem[];

  /**
   * Properties to apply to a submenu to this item.
   */
  overflowMenuProps?: IContextualMenuProps;

  ...
}
```

One issue with this is potential confusion over where the overflow items come from since overflowMenuProps.items could potentially have items. Could be that items only come from overflowMenuProps if overflowMenuProps is specified. it might make sense to eventually deprecate `overflowItems` and just have one way to specify overflow items.

**Comment by micahgodbolt** [comment]
For any major commandBar changes, please refer to #2108 as this is the current PR to replace commandBar in 5.0.

We'll be taking small bug fixes to the current command bar until 5.0 comes out, but any major work should be focused on that PR, and trying to get it tested and approved as soon as possible.
