### ISSUE TITLE
Add option to choose library version on the Fabric documentation website

### ISSUE THREAD

**Issue by ghost** [OfficeDev/office-ui-fabric-react#2188]
I've updated Fabric in my app a couple of times since I started using it, and noticed several component APIs changing over time. https://dev.office.com/fabric currently only displays documentation for one version (which also seems to be an older one), which forced me to dive into the source code of a component in order to find out how to use the newer version.

Would be really nice to have a select box in the header or sidebar, to select the library version that you are using and have the site render the docs for that particular version. I've seen some other libraries solving it this way, for example [lodash](https://lodash.com/docs/4.17.4).

**Comment by micahgodbolt** [comment]
Certainly on our "like to do list".

**Comment by intnovaction** [comment]
Well, at least it would be useful to update the site to the latest version, it would be easier ;)
