### ISSUE TITLE
Add option to set panel footer to always use sticky location

### ISSUE THREAD

**Issue by kngrace** [OfficeDev/office-ui-fabric-react#2193]
**Current Behaviour:** When overflowing content would otherwise cause the footer to be pushed off the panel, the footer instead becomes 'sticky' to always be visible at the bottom of the panel and outside of the scrolling area. 

If content is not sufficient to cause overflowing, the footer instead appears immediately after the content end. So the location of the footer may be variable if a single panel has multiple or dynamic content (such as when using Pivots). 

**What I would like to do:** Is it possible for me to set the footer of the panel (set using onRenderFooterContent) to _always_ be sticky? Or more specifically, force it to align to the bottom of the panel?

**Note:** There are currently no [panel examples](https://dev.office.com/fabric#/components/panel) that highlight the optional onRenderFooterContent _(and many other optional members)_. It may be helpful to add more examples with optional bits instead of simply the basic sizes available.

**Comment by micahgodbolt** [comment]
Sorry this took a bit. All done!
