### ISSUE TITLE
Request: Add Stepper component or add stepper to Pivot's linkFormat options

### ISSUE THREAD

**Issue by kngrace** [OfficeDev/office-ui-fabric-react#2195]
I'm attempting to create a multi-step form (similar to a wizard with next/back buttons) in a panel and I'd like to represent the user's progress with a bar at the top. Pivot is the closest component because of its functionality and appearance but it's still far from perfect. 

I'd like something more similar in appearance to [this image of another React Stepper](https://raw.githubusercontent.com/mu29/react-stepper/master/example/example.png) but I want it to be part of the Office design family (and respects themes in SharePoint). 

Some expected functionality (ordered from most important to least):
- Can disable all navigation functionality from user interacting with component directly
- Each Stepper Item can individually change between common states (selected, disabled, and default)
- Can appear in header 
- Has at least 2 size options
- Able to set component to fill width of container
- Can customize colors
- Can customize other aspects (icons, line thickness, open or filled circle, etc)

**Comment by micahgodbolt** [comment]
Could this be something to do with progress bar? Adding milestones in the progress bar.

**Comment by kngrace** [comment]
I had initially considered progressIndicator but it felt heavily focused on being a non-interactive visual representation of a frequent updating status controlled by a background process (not the user). 

By contrast, the Pivot component allows clear and distinct chunks that support user interaction to navigate and content easily controlled to each distinct chunk. It's cleaner code for me to use Pivot than to replicate its functionality of a single panel with ordered pages tied to a 0..n key value. 

So while it _might_ make sense to add a stepper variant to progressIndicator (since a stepper at its heart is a way to indicate progress within a wizard), that variant would need to duplicate much of the functionality that Pivot already has such as: ordered items, current state, state navigation, labels.

**Comment by evantrimboli** [comment]
I would be interested in something like this as well. Here's an example of one included with Material UI:

https://material-ui.com/demos/steppers/

**Comment by gioce90** [comment]
This would be an interesting feature. You have some news?
