### ISSUE TITLE
TextField no longer supports required, type, placeholder or rows?

### ISSUE THREAD

**Issue by ClickSimply** [OfficeDev/office-ui-fabric-react#2203]
### Bug Report

- __Package version(s)__:4.18.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: Office UI

#### Describe the issue:

Just upgraded from 4.9.0 and got a TON of type errors because the Textfield props no longer support these features.

The following properties that I used previously are no longer available: 
rows: Used to set the height of a multi line text field.
type: Need this for password fields....
required: All fields are now optional...?
placeholder: I can't do placeholder text anymore?

The `min`, `max`, and `step` properties are also missing, usually needed for number text fields.

Am I missing something here?

**Comment by ClickSimply** [comment]
Ended up being a conflict with the typescript version, had to go all the way back to Typescript 2.2.2 to get things working.

I was getting dozens of errors that looked like this:
```
ERROR in ./src/app/components/import-csv.tsx
(175,37): error TS2339: Property 'rows' does not exist on type 'IntrinsicAttributes & IntrinsicClassAtNode; }> &...'.

ERROR in ./src/app/components/image-uploader.tsx
(228,33): error TS2339: Property 'placeholder' does not exist on type 'IntrinsicAttributes & Intrinsic: ReactNode; }> &...'.

ERROR in ./src/app/components/image-uploader.tsx
(337,44): error TS2339: Property 'type' does not exist on type 'IntrinsicAttributes & IntrinsicClassAteactNode; ...'.
```

**Comment by msgx** [comment]
I had the same issue. Got rid of it by sticking to particular versions of `@types/react` and `@types/react-dom` in `package.json`:
```
"dependencies": {
  "@types/react": "15.0.29",
  "@types/react-dom": "15.5.0",
  ...
  "office-ui-fabric-core": "^5.1.0",
  "office-ui-fabric-react": "^4.21.4",
  ...
  "react": "15.6.1",
  "react-dom": "15.6.1"
}
```
As you can see, also I have to stick to v15.6.1 for `react` and `react-dom`. Other dependencies and devDependencies can be safely updated to latest versions. For example:
```
"devDependencies": {
  ...
  "ts-loader": "^2.3.1",
  "typescript": "^2.4.2",
  "webpack": "^2.7.0"
}
```
I’ve tested this configuration in my project, and it works pretty well.

**Comment by LarsLiden** [comment]
Why is this issue closed?  Having to revert to an older version of Typescript seems like a workaround rather than fixing the bug

**Comment by ClickSimply** [comment]
It's not uncommon for UI libraries of this size to bake in features dependent on existing dependencies, then take a little while to upgrade those features to newer dependencies.

I was mostly concerned with getting my build system working again, then communicating how I got it working in case other folks ran into the same problem.

Someone should narrow down which dependencies/versions are actually causing the conflict and open a feature request issue tagging this one.
