### ISSUE TITLE
Icon delete is not shown on Callout buttons

### ISSUE THREAD

**Issue by sharpoverride** [OfficeDev/office-ui-fabric-react#2205]
### Bug Report

- __Package version(s)__: 4.14.0, 4.19.0
- __Browser and OS versions__: Chrome

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No
Requested priority: (Blocking, High, Normal, Low) 
Normal
Products/sites affected: (if applicable)
All
#### Describe the issue:

The icon='Delete' is not shown when you have a button in a Callout. icon='Brightness' works as expected

#### Actual behavior:

Got office-ui-fabric-react/src/components/Callout/examples/Callout.Cover.Example.tsx.
On line 110 after text='Click to dismiss' add the icon property and set it to Birghtness, notice that the brightness icon is properly shown on the UI.

Set the icon to Delete, no icon is shown

#### Expected behavior:

The Delete icon should be shown on the Button. This reproduces on menu items as well as inside a table.

**Comment by intnovaction** [comment]
I've found the same isue in all kind of buttons it seems that someone changed the icon name and nobody updated the docs nor the site :( , if I use "Trash" the correct icon appears.

**Comment by kristoferbrown** [comment]
This is a known issue at the moment. Currently both Delete/Trash and Switch/Switcher are both not matching the icon names on the documentation site.

**Comment by jcuenod** [comment]
It seems these are also not consistent:
- BoxAdditionSolid
- BoxCheckmarkSolid
- BoxMultiplySolid
- BoxPlaySolid
- BoxSubtractSolid

**Comment by jcuenod** [comment]
Is it useful to continue collating inconsistencies? My latest was:

 - QueryList

**Comment by erichdev** [comment]
Icons are now in a separate [package ](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/icons/src/IconNames.ts)which should provide consistency, please reopen if any issues remain
