### ISSUE TITLE
Cannot set src, width and height for Image-Component

### ISSUE THREAD

**Issue by LeopoldLerch** [OfficeDev/office-ui-fabric-react#2212]
### Bug Report

- __Package version(s)__: 4.19

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low) 
High

Products/sites affected: (if applicable)

#### Describe the issue:

When I want to use the Image-Component from Office-UI-Fabric-React, it states, that "src" is not a known attribute. If I delete it, it also denies width and height attributes. I am using the list-example  "List of 5000 variable height items" from the components-documentation on the fabric-website.

**Comment by dzearing** [comment]
Image component works.

https://codepen.io/dzearing/pen/pwYXBy

**Comment by dzearing** [comment]
If you have a code example, please provide it and re-open.

**Comment by LeopoldLerch** [comment]
Hy, it was not the js-Version, but the TypeScript Version. I digged it down
to have something to do with IImageProps and the (not) inherited properties
from HtmlImageElement. I am using TypeScript 2.4.1. TypeScript simply
didn´t recognize the properties that should come from HtmlImageElement
(src, width, height, ...) but only the ones directly defined in
IImageProps. So it didn´t even compile.

I will provide a code sample on Monday, but in fact, it is the same as
proposed as example for the list component as stated above.

regards
Leo


2017-07-15 18:40 GMT+02:00 David Zearing <notifications@github.com>:

**Comment by LeopoldLerch** [comment]
Hy, 
If I am using this sample:

`import * as React from 'react';
import { Image } from 'office-ui-fabric-react/lib/Image';
import { Label } from 'office-ui-fabric-react/lib/Label';

export class ImageDefaultExample extends React.Component<any, any> {
    public render() {
        return (
            <div>
                <p>With no imageFit property set, the width and height props control the size of the frame. Depending on which of those props is used, the image may scale to fit the frame.</p>
                <Label>Without a width or height specified, the frame remains at its natural size and the image will not be scaled.</Label>
                <Image src='http://placehold.it/350x150' />
                <br />
                <Label>If only a width is provided, the frame will be set to that width. The image will scale proportionally to fill the available width.</Label>
                <Image src='http://placehold.it/350x150' width={600} />
                <br />
                <Label>If only a height is provided, the frame will be set to that height. The image will scale proportionally to fill the available height.</Label>
                <Image src='http://placehold.it/350x150' height={100} />
                <br />
                <Label>If both width and height are provided, the frame will be set to that width and height. The image will scale to fill both the available width and height. <strong>This may result in a distorted image.</strong></Label>
                <Image src='http://placehold.it/350x150' width={100} height={100} />
            </div>
        );
    }
}`

Visual Studio Code tells me that there is no property src (if I delete that property, it is the same for width, height). In fact that it is the sample code provided by the components page. As Result I am not able to transpile the code.

As stated, I am using TypeScript 2.4.1 (maybe something to do with that, cause there were already other issues when using TypeScript 2.4.1) and the current Version of office-ui-fabric-react.

**Comment by NZainchkovskiy** [comment]
I have the same issue. Tried with Typescript 2.4.1 and 2.3.4. I think it is a problem with definitions. So now it's impossible to compile Image with typescript.
