### ISSUE TITLE
ComboBox: Make it compatible with strictNullChecks

### ISSUE THREAD

**Issue by christiango** [OfficeDev/office-ui-fabric-react#2216]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes,

Requested priority: Normal

Products/sites affected: (if applicable)

#### Describe the issue:

As part of the move to strictNullChecks, there were a bunch of type casts introduced into ComboBox (in the form of ! and as operators). Some of these are legitimate bugs and should be further examined. It would be nice to get rid of all type casts by null checking or being more strict on our types.

**Comment by jspurlin** [comment]
This has been fixed since 4.32.0, closing
