### ISSUE TITLE
Dropdown down arrow displaced when className is set to null or undefined

### ISSUE THREAD

**Issue by intnovaction** [OfficeDev/office-ui-fabric-react#2221]
### Bug Report

- __Package version(s)__: 4.21.0
- __Browser and OS versions__: Chrome 59.0.3071.115

#### Priorities and help requested (not applicable if asking question):
Are you willing to submit a PR to fix? No :(
Requested priority: Low

#### Describe the issue:

If in a dropdown you set className property to null or undefined, the down arrow is displaced to the top  of the container. It is problematic when you are composing components and the dropdown inherits the class name from the parent component properties.

#### Actual behavior:
The down arrow is displaced to the top of the container

#### Expected behavior:

The down arrow should stay in its place ;)

### If applicable, please provide a codepen repro:

https://codepen.io/Intnovaction/pen/MoRNoJ

**Comment by leddie24** [comment]
Looks like this bug is not limited to null or undefined classnames.   I'll file a PR in a bit 👍
