### ISSUE TITLE
People picker always selects the first entry in the results, irrespective of which one you select

### ISSUE THREAD

**Issue by arvind1234** [OfficeDev/office-ui-fabric-react#2224]
### Bug Report

- __Package version(s)__: 4.15.0
- __Browser and OS versions__: chrome windows

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Blocking (Hi Pri, blocking our release)

Products/sites affected: staffhub.ms

#### Describe the issue:

Have a normal people picker in your page. Start searching and select an item that is not the first one in the list. The picker always selects the first search result.

#### Actual behavior:

Have a normal people picker in your page. Start searching and select an item that is not the first one in the list. The picker always selects the first search result.

#### Expected behavior:

The picker should select the search result the user selects

### If applicable, please provide a codepen repro:
https://dev.office.com/fabric#/components/peoplepicker 

Video capture: https://1drv.ms/v/s!AgsF-JmM9dtAgyDCxyHfN20b4mDS

Type in a search query and select any entry, you will see the first one being selected

**Comment by arvind1234** [comment]
The selection works fine, if you select something without entering any query

**Comment by micahgodbolt** [comment]
this appears to be solved in the current release and only affecting some older releases.

**Comment by lrecknagel** [comment]
Related to my Bugreport #2187 and was closed with: [Release 4.21.1](https://github.com/OfficeDev/office-ui-fabric-react/releases/tag/office-ui-fabric-react_v4.21.1)
