### ISSUE TITLE
Dropdown width to fit its longest option width

### ISSUE THREAD

**Issue by artxach** [OfficeDev/office-ui-fabric-react#2228]
### Bug Report

- __Package version(s)__: (1.14.3)
- __Browser and OS versions__: (Firefox 54.0.1 , Windows 2012 Server)

#### Describe the issue:

When a dropdown has many options with different lengths its width is being changed when selecting some option. Also when the options' list is opened it has a current option's width, so if the shortest option is selected and you open options' list it can word-break longer options

#### Expected behavior:

Let the dropdown by default or by specifying a prop to fit its longest option.

**Comment by buckingj** [comment]
Would love to see this fixed.

**Comment by manasark** [comment]
Any update on this bug? We are using the dropdown component in many UI pages. Fixing this issue would improve the readability for the user.

**Package version(s)**: (5.64)
**Browser**: All browsers
**OS versions**: Windows 10

**Comment by lynamemi** [comment]
@artxach @manasark We investigated this bug and need more information to repro. Is it the width of the dropdown input field or the dropdown callout that you want to snap to the longest option? We are not seeing either width change based on which option is selected. The callout always snaps to the width of the input unless the 'dropdownWidth' prop is set. For really long options, the value can be read on hover.

I created this codepen for testing:
https://codepen.io/lynamemi/pen/wjapep

**Comment by lynamemi** [comment]
@manasark Still not completely clear on the expected behavior here. Is it:

1. Dropdown's callout width 
OR
2.  Dropdown's input field / container width

that you want to snap to the longest option's width?

**Comment by manasark** [comment]
@lynamemi option 2

**Comment by lynamemi** [comment]
Ok sounds good. That one will probably take a little more time than the other. I can try to get to it in the next couple of weeks, but if you have bandwidth to take it on, I can help with PRs.

**Comment by buckingj** [comment]
For what it's worth, don't we want both 1 and 2? 

If I have a dropdown with "foo", "bar", and "baseball" in it, and I select "foo" and then show the dropdown, the dropdown will only truncate that last entry to "bas...".

I suppose if we fix #2, that will also implicitly fix #1, right? Assuming that's the case, that would be ideal. Truncating strings looks terrible in a dropdown, and seeing the dropdown constantly change width depending on what is selected is also a bad experience.

**Comment by lynamemi** [comment]
@buckingj @manasark - It would be great if one of you submitted a PR for this change - I'm going to unassign myself. It sounds like there are a few different directions we could take that would help you out and a PR would be a great place to continue this conversation. I'm happy to help review.
