### ISSUE TITLE
Border less textfield is showing border in high contrast mode

### ISSUE THREAD

**Issue by shaikshavalis** [OfficeDev/office-ui-fabric-react#2230]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: Edge & IE 11

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? NO

Requested priority: Normal

Products/sites affected: VSTS

### If applicable, please provide a codepen repro:

![image](https://user-images.githubusercontent.com/9265381/28313100-30e11560-6bd3-11e7-9ae9-3e7dc908e0fc.png)

**Comment by micahgodbolt** [comment]
@betrue-final-final do you know if the border-less input is supposed to have a border in high contrast?

**Comment by betrue-final-final** [comment]
No, definitely not. High contrast is meant to give an equivalent experience with other contrast modes. If an object appears in non-hc, then it should appear in higher contrast, but we shouldn't add elements.
