### ISSUE TITLE
Placeholder in Textfield removed?

### ISSUE THREAD

**Issue by HannesDel** [OfficeDev/office-ui-fabric-react#2231]
I updated my version, now the placeholder prop is not available anymore on Textfield.

**Comment by micahgodbolt** [comment]
It appears to be working fine with the most recent release. Here's a codepen of the current release.

https://codepen.io/micahgodbolt/pen/owRQMZ

What version are you using, and are you seeing an error, or is the placeholder just not working?

**Comment by HannesDel** [comment]
I'm using version 4.21.1
And the error I'm getting is: [ts] Property 'placeholder' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<TextField> & Readonly<{ children?: ReactNode; }> &...'.

**Comment by dzearing** [comment]
This could be more of an issue with @types/react.

**Comment by HannesDel** [comment]
Any ideas how I could solve this? Revert to an older version of `@types/react` maybe?

**Comment by HannesDel** [comment]
I reverted @types/react to version 15.0.35 from version 15.0.38 and now it seems to work. Thanks @dzearing
