### ISSUE TITLE
FocusZone/ChoiceGroup: ChoiceGroup gets skipped over tabbing if first option is not selected

### ISSUE THREAD

**Issue by MLoughry** [OfficeDev/office-ui-fabric-react#2246]
### Bug Report

- __Package version(s)__: 4.21.1
- __Browser and OS versions__: Chrome 59, Firefox , Safari. This does *not* repro on Edge

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? In theory, but I'm not familiar with the code, and not sure when I'll have the time.

Requested priority: High

Products/sites affected: Outlook Web

#### Describe the issue:

This doesn't repro with every ChoiceGroup wrapped in a FocusZone; but in the repro CodePen provided, when the user attempts to tab to the second ChoiceGroup, the tabbing skips over the second ChoiceGroup if the first choice is not selected.

**Comment by dzearing** [comment]
Strange.

**Comment by MLoughry** [comment]
Bumped down to "low" priority, as we worked around the issue by not wrapping the ChoiceGroup controls in FocusZones.
