### ISSUE TITLE
Problem with <Text field type=password />

### ISSUE THREAD

**Issue by igorPhelype** [OfficeDev/office-ui-fabric-react#2247]
To see more details about this issue:
https://stackoverflow.com/questions/45177469/how-to-create-a-password-input-with-fabric-ui-react/45177817?noredirect=1#comment77325044_45177817

**Comment by micahgodbolt** [comment]
This was fixed sometime ago it seems. I have no trouble doing: 
```
<TextField type='password' label='Default TextField'  />
```

and getting this:

![image](https://user-images.githubusercontent.com/1434956/28377895-2a18128e-6c63-11e7-8807-3642a0f5bfc5.png)


If it's a typescript issue, we're working out some bugs with the most recent version of TS. Make sure you've updated to the most recent version of Fabric.

**Comment by chrsnagy** [comment]
Hi. I'm the person who is having this issue. The textfield works as expected and it covers the password, but Visual Studio Code still indicates the same error I mentioned on stackoverflow.

**Comment by leddie24** [comment]
Looks like #2334 fixed this issue.  Can you reopen the issue if you're still experiencing this problem?  Thanks!
