### ISSUE TITLE
Image Component not transpiling because of not inherited properties

### ISSUE THREAD

**Issue by LeopoldLerch** [OfficeDev/office-ui-fabric-react#2252]
Hy, 
If I am using this sample:

```
import * as React from 'react';
import { Image } from 'office-ui-fabric-react/lib/Image';
import { Label } from 'office-ui-fabric-react/lib/Label';

export class ImageDefaultExample extends React.Component<any, any> {
    public render() {
        return (
            <div>
                <p>With no imageFit property set, the width and height props control the size of the frame. Depending on which of those props is used, the image may scale to fit the frame.</p>
                <Label>Without a width or height specified, the frame remains at its natural size and the image will not be scaled.</Label>
                <Image src='http://placehold.it/350x150' />
                <br />
                <Label>If only a width is provided, the frame will be set to that width. The image will scale proportionally to fill the available width.</Label>
                <Image src='http://placehold.it/350x150' width={600} />
                <br />
                <Label>If only a height is provided, the frame will be set to that height. The image will scale proportionally to fill the available height.</Label>
                <Image src='http://placehold.it/350x150' height={100} />
                <br />
                <Label>If both width and height are provided, the frame will be set to that width and height. The image will scale to fill both the available width and height. <strong>This may result in a distorted image.</strong></Label>
                <Image src='http://placehold.it/350x150' width={100} height={100} />
            </div>
        );
    }
}
```

Visual Studio Code tells me that there is no property src (if I delete that property, it is the same for width, height). In fact that it is the sample code provided by the components page. As Result I am not able to transpile the code.

I am using TypeScript 2.4.1 (maybe something to do with that, cause there were already other issues when using TypeScript 2.4.1) and the current Version of office-ui-fabric-react.

**Comment by micahgodbolt** [comment]
src, width, height are all intrinsic values, i.e. they don't have to be specified in props, they are just part of the base element used. My guess is it's something 2.4.1 releated. Which version of fabric are you on? We've been fixing several TS related bugs recently.

**Comment by LeopoldLerch** [comment]
I am running on Typescript 2.4.1 and office-ui-fabric-react 4.21.2 (current release, also current typings). It seems to have something to do with the Inheritance of the IImageProps-Class, because even when I create a Object of IImageProps, the object doesn´t recognize the intrinsic values.
