### ISSUE TITLE
Could not find a declaration file for module 'prop-types'

### ISSUE THREAD

**Issue by jquintozamora** [OfficeDev/office-ui-fabric-react#2254]
### Error

ERROR in LandingMenu\node_modules\@uifabric\utilities\lib\Customizer.d.ts(2,28): error TS7016: Could not find a declaration file for module 'prop-types'. \node_modules\prop-types\index.js' implicitly has an 'any' type.
  Try `npm install @types/prop-types` if it exists or add a new declaration (.d.ts) file containing `declare module 'prop-types';`

#### Package.json

  "dependencies": {
    "@types/react": "15.0.35",
    "@types/react-dom": "15.5.1",
    "office-ui-fabric-react": "4.21.1",
    "react": "15.6.1",
    "react-dom": "15.6.1"
  },

 "typescript": "2.4.1",

Any help appreciated!!

**Comment by jquintozamora** [comment]
I was solved by installing @types/prop-types.

npm i -D @types/prop-types

Should that be added as a dependency for office-ui-fabric-react instead of devDependency?

**Comment by micahgodbolt** [comment]
@dzearing is prop-types needed for dev only? or is it required when using fabric?

**Comment by Feiyang1** [comment]
I'm facing the same issue. Though I'm able to resolve it by running npm install @types/prop-types, I think it needs to be a dependency of the library.

**Comment by micahgodbolt** [comment]
Yup, that should do it. Closing this down then.

**Comment by micahgodbolt** [comment]
@dzearing did we ever make a decision on moving prop-types to dependencies?
