### ISSUE TITLE
background color for headers changed in PR #1806 breaks accessibility

### ISSUE THREAD

**Issue by sandeepchads** [OfficeDev/office-ui-fabric-react#2261]
In the following PR https://github.com/OfficeDev/office-ui-fabric-react/pull/1806
The background color for headers was changed to white from transparent for disabled title headers. The new color selection breaks accessibility requirements since the colors do not follow the color contrast ratio of 4.5:1 .

Can you please fix this?

**Comment by micahgodbolt** [comment]
@leddie24 can you take a look at this?

**Comment by leddie24** [comment]
@sandeepchads, can you please upload a screenshot of the issue for context?  Thanks!

**Comment by erichdev** [comment]
Closing because no response. Please reopen if issues remain
