### ISSUE TITLE
Expose className property for Layer

### ISSUE THREAD

**Issue by ankitk94** [OfficeDev/office-ui-fabric-react#2262]
Our requirement is to show a node having z-index higher than OfficeFabric Layer component (so that it is highlighted when panel is opened). But if another dialog is opened, the node again comes above the new dialog (because we already made z-index of node higher than fabric layer component default z-index). Is there a way to increase or change the z-index of fabric layer component? One option might be to change it in className if className property for Layer can be exposed

**Comment by battletoilet** [comment]
Hey @ankitk94, would you mind posting an example of this in a codepen or something similar?
