### ISSUE TITLE
interface ITextFieldProps does not have placeholder property

### ISSUE THREAD

**Issue by fuocor** [OfficeDev/office-ui-fabric-react#2265]
ITextFieldProps extends React.HTMLAttributes<HTMLInputElement | HTMLTextAreaElement> which does not have the placeholder property.

the placeholder property is in AllHTMLAttributes, InputHTMLAttributes, and TextareaHTMLAttributes

rich

**Comment by LeopoldLerch** [comment]
seems to be the same issue with IImageProps mentioned in my issue

https://github.com/OfficeDev/office-ui-fabric-react/issues/2252

**Comment by fuocor** [comment]
it appears that react has updated the type definitions. I'm using:

    "@types/react": "^15.0.27",

**Comment by leddie24** [comment]
Looks like this is fixed in #2334
