### ISSUE TITLE
Buttons redundantly specify aria-labelledby, which sometimes doesn't even exist

### ISSUE THREAD

**Issue by trevorsg** [OfficeDev/office-ui-fabric-react#2270]
BaseButton.tsx creates a <button> element with aria-labelledby set to the id that is generated for the descendent <span> that acts as the button's label. This is redundant, since that element's text already serves as the button's label by default.

Furthermore, some buttons don't have a label (e.g. IconButton), so the aria-labelledby attribute refers to an element that doesn't even exist.

I plan to submit a fix tomorrow.

**Comment by battletoilet** [comment]
Thank you @trevorsg for submitting a fix!
