### ISSUE TITLE
multiline TextField does not inherit font-family

### ISSUE THREAD

**Issue by fuocor** [OfficeDev/office-ui-fabric-react#2276]
### Bug Report

- __Package version(s)__: 4.21.4
- __Browser and OS versions__: all

Are you willing to submit a PR to fix? No
Requested priority: High
Products/sites affected: All

#### Describe the issue:

define:

`                    <TextField
                        label={resources.description_label}
                        value={request.description}
                        multiline
                        autoAdjustHeight />
`
results in user agent default font-family

#### Expected behavior:

inherit font-family

The non multiline TextField works fine

rich

**Comment by htryggva** [comment]
@dzearing @battletoilet 
In Version 4.49.1 (and on the documentation website), it looks like this:

![image](https://user-images.githubusercontent.com/6515360/30813053-a22479dc-a20c-11e7-8578-efbed4387bcc.png)

It looks like this issue has regressed. Any chance of having multiline text boxes have the same font family as the non-multiline text boxes? :)
