### ISSUE TITLE
Dropdown: Enable a way to have icons for items

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#228]
Dropdown can't render icons with items. We had an ask to support this.

At a bare minimum we should enable the component to allow custom item renderers to be provided.

**Comment by rickyp-ms** [comment]
Our application would greatly appreciate this functionality! Adding this comment here so I get notifications about this issue.

**Comment by dzearing** [comment]
This is. Ow resolved with onRenderItem.
