### ISSUE TITLE
DatePicker: Using a datepicker in a panel causes unexpected dismissal behavior

### ISSUE THREAD

**Issue by abettadapur** [OfficeDev/office-ui-fabric-react#229]
The DatePicker does not dismiss properly when used in a Panel (and possibly other layer host components)
1. User clicks datepicker field, datepicker opens
2. User selects date, onSelected is successfully called
3. User clicks anywhere in the layer host, onSelected is called again with a null value
4. Date in datepicker field is reset to today

**Comment by dzearing** [comment]
Merged! thanks!
