### ISSUE TITLE
ChoiceGroup "disabled" prop no longer valid

### ISSUE THREAD

**Issue by OneCyrus** [OfficeDev/office-ui-fabric-react#2290]
### Bug Report

- __Package version(s)__: 4.21.4
- __Browser and OS versions__: all (typscript transpiler error)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/sites affected: internal app

#### Describe the issue:

#1967 broke the ChoiceGroup disabled prop. (may be not. i can't get it to work with older versions as well. probably something to do with an updated typescript version)

[ts] Property 'disabled' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ChoiceGroup> & Readonly<{ children?: ReactNode; }>...'.

#### Actual behavior:

"disabled" is no longer a valid prop on IChoiceGroupProps

#### Expected behavior:

"disabled" is a valid prop on IChoiceGroupProps

**Comment by micahgodbolt** [comment]
i believe this is a typescript issue. disabled should always be a valid prop (as it's an HTML prop). Pretty sure we're working on a solution.

**Comment by leddie24** [comment]
Closing issue, looks like this is solved from #2334
