### ISSUE TITLE
Property 'href' does not exist on type <Link>

### ISSUE THREAD

**Issue by ndelacour** [OfficeDev/office-ui-fabric-react#2291]
### Bug Report
- __Package version(s)__: (4.22.0)

Are you willing to submit a PR to fix? No

Requested priority: High

#### Describe the issue:
error TS2339: Property 'href' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Link> & Readonly<{ children?: ReactNode; }> & Read...'.

Code : <Link href='#'>{ fieldContent }</Link>

#### Actual behavior:
Compile error (since update towards new version)

#### Expected behavior:
Compile without errors

**Comment by micahgodbolt** [comment]
This is a typescript issue after a recent update. We're looking into it.

**Comment by leddie24** [comment]
Looks like this is fixed in #2334
