### ISSUE TITLE
Remove z-indexes from components

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#23]
Many of the components have `z-index` values baked in, which might work relative to other Fabric components but are often wrong for fitting into an existing app. I haven't dug into the Layer component but I understand it is an alternative to this. If not, we should at least provide an interface to every `z-index` so that developers can stack the components however their app requires.

**Comment by dzearing** [comment]
thanks for adding this!

**Comment by dzearing** [comment]
I think for the most part this has been done.
