### ISSUE TITLE
ComboBox Doesn't Update Options on Re-Render

### ISSUE THREAD

**Issue by Quiescent** [OfficeDev/office-ui-fabric-react#2301]
### Bug Report

- __Package version(s)__: office-ui-fabric-core: ^7.1.2, office-ui-fabric-react: ^4.21.1,
- __Browser and OS versions__: Slackware 14.2, Opera 45.0.2552.898

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: High

#### Describe the issue:

ComboBox s don't respect the options property the second time that they're rendered and every time there after.

#### Actual behavior:

If the options for a ComboBox  are set the first time it's rendered then they're visible.  If you only set them on the second render or any re render thereafter, then they're not updated.

#### Expected behavior:

A ComboBox should always render the supplied options.

### If applicable, please provide a codepen repro:

I've provided a github project which replicates the issue and demonstrates how a DropDown has the expected behavior here: https://github.com/Quiescent/replicate-combobox-issue/

(I wasn't aware of the preference to use codepen before I pushed up this project.)

**Comment by cobbs-totem** [comment]
I've noticed the same problem.  I populate my options from componentDidMount() and they do not update the ComboBox.  Looking through the ComboBox source, it seems you have to have a selectedKey in order for the props to be updated via their componentWillReceiveProps().  I don't understand why, but setting that makes the options work then.

**Comment by OneCyrus** [comment]
same problem with the latest version (4.34.0). it worked with 4.31.0 here.

**Comment by BizH** [comment]
Same problem here.
