### ISSUE TITLE
Illegal rule inserted warning seen when Fabric React components are used on page (imported)

### ISSUE THREAD

**Issue by adjalgao** [OfficeDev/office-ui-fabric-react#2310]
### Bug Report

- __Package version(s)__: 4.23.0
- __Browser and OS versions__: Chrome/Windows 10

#### Priorities and help requested (not applicable if asking question):
Help in fixing the issue on illegal rule warnings.

Are you willing to submit a PR to fix? (Maybe)

Requested priority: (Blocking, High, Normal, Low) 
Normal

Products/sites affected: (if applicable)

#### Describe the issue:
When i added the Office fabric react. I see several illegal rules that pop up on the console. Thought this was me doing something but i see the same exceptions on the dev office fabric website as well.
https://dev.office.com/fabric#/components/dropdown
Is this is a new issue.

#### Actual behavior:
On the browser Developer Tools window under console you will see illegal rules (see attached Screen shot)

#### Expected behavior:

No illegal rules should show on the console.

### If applicable, please provide a codepen repro:

![image](https://user-images.githubusercontent.com/30474686/28633481-d1ccab68-71e8-11e7-97a6-a06d7122c114.png)

**Comment by dzearing** [comment]
Please note, if you use webpack, you can remove these by using the DefinePlugin to define process. ENV as production.

These are coming from the glamor library. We are actively working on a replacement that will perform better, have less chatter in the console, and will be smaller in bundle size. I will leave this open to close once that's dropped.

**Comment by adjalgao** [comment]
Thanks, that took the errors away. Will be sure to keep a eye out to check on the new update.

**Comment by hmafzal** [comment]
@dzearing was there any update to fixing the console warnings? We'd prefer not to set the NODE_ENV to production.

**Comment by dzearing** [comment]
This is now fixed in the 5.0 release!
