### ISSUE TITLE
onChange function does not return/provide parameter with the caller proxy context

### ISSUE THREAD

**Issue by adjalgao** [OfficeDev/office-ui-fabric-react#2311]
### Bug Report

- __Package version(s)__: 4.23.0
- __Browser and OS versions__: Chrome/Windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/sites affected: (if applicable)
Yes, adding Office Fabric to our website is blocked based on this

#### Describe the issue:
Currently when the callback from the "onChange" or "onGetErrorMessage" etc. So any callback method that is triggered by a change on the fabric component sends only the changing "String" or "Value" that is entered on the component. Typically the "Proxy" of the calling component is sent with a set of functionality that can be performed on it.
Hence this is different than the actual React working 
https://facebook.github.io/react/docs/uncontrolled-components.html
https://facebook.github.io/react/docs/events.html
Does this also mean that none of the events are supported on the components?

For example for preventingDefault there is no way since its just text thats sent over and not the element.

Also, this causes the "Numeric TextBox" implementation that is currently present in the project to state with a error message "Not a number" but not restrict users from entering certain Characters. 

#### Actual behavior:
String sent over the onChange events

#### Expected behavior:
Component proxy should be sent over

### If applicable, please provide a codepen repro:

Screen shots of Fabric TextBox:
![image](https://user-images.githubusercontent.com/30474686/28637932-1adc5132-71f8-11e7-9abe-433ad10a822b.png)

Screen Shot of a normal React Text box with a onChange function:
![image](https://user-images.githubusercontent.com/30474686/28638015-71c57564-71f8-11e7-9daa-9ca19bc4a0bd.png)

**Comment by micahgodbolt** [comment]
Is it only textfield that you are having trouble with, or are there other instances of this?

**Comment by adjalgao** [comment]
@micahgodbolt 
I will have to test all components again to remember if its only textboxes but from what I do remember it was not just the textboxes i think other components also behave similarly where they return just the value that is changed and not the context of the element.
Thanks,
Aditya

**Comment by micahgodbolt** [comment]
@adjalgao Thanks for looking into that. I'm sorry that it took us so long to get back to you. If these types of bugs are keeping you from being able to adopt Fabric, we'd like to work towards fixing them.
