### ISSUE TITLE
Access is denied error on IE

### ISSUE THREAD

**Issue by salehaHussain** [OfficeDev/office-ui-fabric-react#2316]
### Bug Report

- __Package version(s)__: 4.23.0
- __Browser and OS versions__: Windows 10 IE 11

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: Yes

#### Describe the issue:

We are receiving reports of "Access is denied" error in IE while the page tries to access getLanguage in language utilities (https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/utilities/src/language.ts#L11)

#### Expected behavior:

In case localstorage or documentElement cannot be accessed or edited, the error should be handled gracefully and the language should default to en-US.

**Comment by joechung-msft** [comment]
I'm seeing this in Chrome 61 as well.

**Comment by micahgodbolt** [comment]
@salehaHussain can you confirm that it's a cookie blocking issue?

**Comment by erichdev** [comment]
This has been resolved, please reopen if any issues remain
