### ISSUE TITLE
PDF Icon does not work

### ISSUE THREAD

**Issue by rickyp-ms** [OfficeDev/office-ui-fabric-react#2322]
### Bug Report

- __Package version(s)__: 4.21.3
- __Browser and OS versions__: All

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal 

Products/sites affected: tasks.office.com, Project Web Access (SharePoint add on)

#### Describe the issue:

PDF Icons do not render

#### Actual behavior:

Nothing renders

#### Expected behavior:

Icon to be rendered

### If applicable, please provide a codepen repro:

https://codepen.io/anon/pen/rzOWEV?editors=0010

### Current workaround:

Add classname ms-Icon--PDF to the Icon component you are rendering

**Comment by Jahnp** [comment]
Try changing it from "PDF" to "pdf": https://codepen.io/jahnp/pen/mMevdP

This rendered the icon for me:
![image](https://user-images.githubusercontent.com/307118/28728633-3edc8430-737e-11e7-8fc9-8a1931e90830.png)

I'll go ahead and close for now, but feel free to re-open if that doesn't work or if there're any other issues you see with this.
