### ISSUE TITLE
Introducing too old office-ui-fabric-core on "Get started" page

### ISSUE THREAD

**Issue by nekoya** [OfficeDev/office-ui-fabric-react#2325]
This is a document problem.

https://dev.office.com/fabric#/get-started introduces to import office-ui-fabric-core 4.1.0 on `Get started with Fabric Core` section (refs [GetStartedPage.tsx](https://github.com/OfficeDev/office-ui-fabric-react/blob/b5c0fba73cc02669f9e025a228811840876e8bf7/apps/fabric-website/src/pages/GetStarted/GetStartedPage.tsx#L174))

After #1587, office-ui-fabric-react depends office-ui-fabric-core v7.

For example, [Grid layout](https://dev.office.com/fabric#/styles/layout) class names are updated, `ms-u-sm6` to `ms-sm6`. Unfortunately, `ms-sm6` does not works on office-ui-fabric-core 4.1.0.

We should update the version on `GetStartedPage.tsx`. Which is the appropriate one (latest 7.1.2, or another choise 7.1.0 or 7.0.0) ?

**Comment by Jahnp** [comment]
Hey @nekoya, that's a great catch, thanks for calling these out. There's a number of updates/fixes we need to make to the documentation website, including this one. We'll be doing a scrub soon, but haven't started yet; in the meantime, we'd happily welcome PRs fixing any of these you come across.

**Comment by nekoya** [comment]
I've confirmed the document was updated.

https://github.com/OfficeDev/office-ui-fabric-react/releases/tag/%40uifabric%2Ffabric-website_v4.7.3

I'm looking forward to updating actual site https://dev.office.com/fabric#/get-started!

**Comment by nekoya** [comment]
Sadly, Fabric website still provides [Get started with Fabric Core](https://dev.office.com/fabric#/get-started) a link for `4.1.0` yet...

**Comment by Jahnp** [comment]
Hey @nekoya, check out https://developer.microsoft.com/en-us/fabric#/get-started 😊

**Comment by nekoya** [comment]
Ah, that's it. I didn't know that. It seems nice.

I cannot find this site from Google, is this a primary site for office-ui-fabric-react?

If so, at first, let's update description of this repository.

**Comment by lynamemi** [comment]
Yes, @nekoya, this address officially became the primary site for office-ui-fabric-react at the end of last week. Thank you for pointing out we should fix the rep to point there, we definitely should!
