### ISSUE TITLE
[Accessibility] Name property empty for message bar dismiss

### ISSUE THREAD

**Issue by PrasadBhat** [OfficeDev/office-ui-fabric-react#2339]
### Bug Report

- __Package version(s)__: All
- __Browser and OS versions__: Windows Edge

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low)  High

Products/sites affected: (if applicable) Visually impaired people will be affected 

#### Describe the issue:

You can verify the issue by using windows inspect tool in edge browser. Office fabric message bar dismiss ( close ) has no name proprty.

**Comment by mdahamiwal** [comment]
There is already `dismissButtonAriaLabel` to set the label. There is no default due to localization issue.
