### ISSUE TITLE
DatePicker opens when focus is brought back to it

### ISSUE THREAD

**Issue by justinmwarner** [OfficeDev/office-ui-fabric-react#2342]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: Chrome, IE, Firefox - Windows

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: Demo site and others

#### Describe the issue:

Open a DatePicker. Now close it (ESC or click outside of it). Now ALT+TAB to another window and ALT+TAB back. Hover over the DatePicker. 

#### Actual behavior:

DatePicker opens again

#### Expected behavior:

Nothing should happen.

### If applicable, please provide a codepen repro:

Just go to Fabric demo site and do repro steps above.  
https://dev.office.com/fabric#/components/datepicker

**Comment by martellaj** [comment]
There's a prop (`disableAutoFocus`) that handles this scenario already, I believe.

**Comment by justinmwarner** [comment]
Closing this. I'm unsure if this is still needed by the team I was on. Thanks for the reply martellaj.
