### ISSUE TITLE
CommandBar Far Link background color has unexpectedly changed.

### ISSUE THREAD

**Issue by Oceanswave** [OfficeDev/office-ui-fabric-react#2347]
### Bug Report

- 4.26.0
- All

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High

#### Describe the issue:

CommandBar Far icon color has changed. In 4.26.0 the itemLink colors are now #dadada, previously they matched the CommandBar color

#### Actual behavior:

CommandBar Far ItemLink background color is now #dadada,

#### Expected behavior:

CommandBar Far itemLink colors match near ItemLink background color

### If applicable, please provide a codepen repro:

To repro, observe the Office UI Fabric documentation site. Specifically, compare the Icon colors here: https://dev.office.com/fabric#/components/commandbar with those from a recent build as the fabric documentation site is an older version that exhibits the expected behaviour.

Also compare items built in prod mode vs dev mode.

**Comment by Oceanswave** [comment]
Hacking my way through this, adding a root level style
```
.itemLink_99129b05.itemLinkIsExpanded_99129b05 {
  background-color: initial;
}
```
fixes the issue in prod mode.

**Comment by micahgodbolt** [comment]
Are you only concerned with the isExpanded background? Or the Far Items? Or the icon colors? I'm not quite following. Can you provide a few screenshots?

**Comment by Oceanswave** [comment]
Mostly the background color of the far items are being rendered with a darker background color.

But after pulling down today's latest, it looks like another change has fixed this for us, so, closing.
