### ISSUE TITLE
Screen readers is not reading out the title of Dialog component

### ISSUE THREAD

**Issue by ronak-92** [OfficeDev/office-ui-fabric-react#2350]
### Bug Report

- __Package version(s)__: 4.9.2
- __Browser and OS versions__: win 10 with all major browsers (Edge, Chrome, Firefox)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: VSTS

#### Describe the issue:
It is a regression, where on opening a dialog component, screen readers do not read out the title of the dialog. It looks like the regression was introduced in [this](https://github.com/OfficeDev/office-ui-fabric-react/commit/e71c3915f7dcb7ea37e332c06ee1461c7ca1387a?diff=split) commit where the Dialog component was split in two parts. The aria-labelled by property of the dialog stopped pointing to Dialog title.

#### Actual behavior:
Screen readers call out "Dialog" and not the dialog title, and then calls out the first focusable element in the dialog, if any.

#### Expected behavior:

Screen readers should read the title of dialog when opened.

### If applicable, please provide a codepen repro:
https://codepen.io/dzearing/pen/NbKwwy

In this repro, it should read "This is a title" which it does not

**Comment by micahgodbolt** [comment]
just waiting for PR tests to get fixed up before merging.
