### ISSUE TITLE
Nav: Add callback when expanded state changes

### ISSUE THREAD

**Issue by Oceanswave** [OfficeDev/office-ui-fabric-react#2354]
Currently, there isn't a way to be notified when an INavLink is expanded/collapsed. It would be great to have a callback that can be used in order to save the current state.

In the current code base, clicking on another INavLink resets the expanded state of all items in the nav.

**Comment by micahgodbolt** [comment]
Is this a feature you'd be willing to add? I'm happy to help you out with the PR.
