### ISSUE TITLE
BaseButton ariaDescription is not hidden on the page

### ISSUE THREAD

**Issue by abettadapur** [OfficeDev/office-ui-fabric-react#2356]
### Bug Report

- __Package version(s)__: 4.21.3
- __Browser and OS versions__: All

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) 

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

#### Describe the issue:
The ariaDescription prop on the BaseButton is rendered in a visible span on the page.
In the debugger, styles.screenReaderText is undefined

![image](https://user-images.githubusercontent.com/2415669/28836695-e28257a4-769e-11e7-8dee-85da26382bcf.png)

#### Actual behavior:
The span is displayed on the page
![image](https://user-images.githubusercontent.com/2415669/28836713-f6cd0b6e-769e-11e7-8c81-3ab91a84dba2.png)
![image](https://user-images.githubusercontent.com/2415669/28836730-03da97b8-769f-11e7-9a68-37c398bf49ed.png)

#### Expected behavior:
The span should be hidden

**Comment by micahgodbolt** [comment]
The problem is that BaseButton is by design unstyled, so that each variant has full control over the necessary styles. I think there IS value in keeping that span hidden though, as it is not really a style issue, but a content issue. I"ll see what options we have.
