### ISSUE TITLE
Contextual Menu and Split Buttons: checked (isChecked) are not applicable to menu items

### ISSUE THREAD

**Issue by AJIXuMuK** [OfficeDev/office-ui-fabric-react#2363]
### Bug Report

- __Package version(s)__: 4.27.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

#### Describe the issue:

`canCheck, checked, isChecked` are not applicable to menu items in buttons (Contextual Menu buttons or Split buttons)

#### Actual behavior:

`canCheck, checked, isChecked` are not applied to the menu item.

#### Expected behavior:

`canCheck` and either `checked` or `isChecked` are applied to the menu item, menu item is rendered with a checkmark.

### If applicable, please provide a codepen repro:

[codepen example](https://codepen.io/AJIXuMuK/pen/MvevGe)

**Comment by micahgodbolt** [comment]
Can you double check this. We just pushed out a fix that restored icons in contextual menus. It 'appears' that your codepen is now working.

![image](https://user-images.githubusercontent.com/1434956/28884602-5967e4b0-7767-11e7-97a8-174387414d61.png)

**Comment by AJIXuMuK** [comment]
@micahgodbolt yes, it is working now. Thanks!
