### ISSUE TITLE
DocumentCardActivity incorrectly extends base class BaseComponent

### ISSUE THREAD

**Issue by Jozeevis** [OfficeDev/office-ui-fabric-react#2364]
### Bug Report

- __Package version(s)__: 4.28.0

#### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority: Normal

#### Describe the issue:

After updating to the latest version of office-ui-fabric-react (4.28.0), I get this error whenever I try to run my webpart with gulp serve:

node_modules\office-ui-fabric-react\lib\components\DocumentCard\DocumentCardActivity.d.ts(2,21): error TS2415: Class 'DocumentCardActivity' incorrectly extends base class 'BaseComponent<IDocumentCardActivityProps, any>'.

**Comment by dzearing** [comment]
This is due to typescript 2.4.1 changes.

We have a fix to upgrade to 2.4.1 in PR.

**Comment by micahgodbolt** [comment]
2334 is merged. closeing this up.
