### ISSUE TITLE
Searchbox not accepting keystrokes after clear

### ISSUE THREAD

**Issue by nipunja** [OfficeDev/office-ui-fabric-react#2366]
Repro Steps:
1.     Click search box fill "a"
2.     Click "x" to delete the character and fill "a" again

Actual: "a" is not coming in search box
Expected: "a" should come in search box

Issue can be easily reproduced over here (https://dev.office.com/fabric#/components/searchbox)

**Comment by micahgodbolt** [comment]
what a weird bug...you can press any other key except 'a', and if you enter more than 1 character, the bug doesn't repro.

**Comment by micahgodbolt** [comment]
![search](https://user-images.githubusercontent.com/1434956/28883961-096f3e92-7765-11e7-80ef-b1b198562b8a.gif)
