### ISSUE TITLE
Feature Request:  ComboBox placeholder text

### ISSUE THREAD

**Issue by cobbs-totem** [OfficeDev/office-ui-fabric-react#2370]
Placeholder text is used for various other components, and it would be nice to have one for ComboBox as well.

**Comment by thechriskent** [comment]
I'd like to see this added as well since there is just an input underneath where this attribute could be set. Thanks!

**Comment by TheTedAdams** [comment]
If this issue needs activity to keep the stale-bot from closing it then consider this activity.

Was very surprised to find this missing.

**Comment by justinmwarner** [comment]
@JasonGore @micahgodbolt any update on this one?
