### ISSUE TITLE
Tons of errors when compiling client-side web part (typescript 2.4.1)

### ISSUE THREAD

**Issue by AJIXuMuK** [OfficeDev/office-ui-fabric-react#2382]
### Bug Report

- __Package version(s)__: 4.29.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High

#### Describe the issue:

There are tons of errors while compiling SPFx client-side web part with typescript v 2.4.1
React v 15.6.1
React-dom v 15.6.1

Error - typescript - node_modules\office-ui-fabric-react\lib\components\Button\Button.Props.d.ts(14,44): error TS2694: Namespace 'React' has no exported member 'AllHTMLAttributes'.
Error - typescript - node_modules\office-ui-fabric-react\lib\components\Button\Button.Props.d.ts(120,22): error TS2694: Namespace 'React' has no exported member 'ButtonHTMLAttributes'.
Error - typescript - node_modules\office-ui-fabric-react\lib\components\Button\Button.Props.d.ts(120,70): error TS2694: Namespace 'React' has no exported member 'AnchorHTMLAttributes'.
Error - typescript - node_modules\office-ui-fabric-react\lib\components\Checkbox\Checkbox.Props.d.ts(14,46): error TS2694: Namespace 'React' has no exported member 'ButtonHTMLAttributes'.
Error - typescript - node_modules\office-ui-fabric-react\lib\components\Checkbox\Checkbox.Props.d.ts(52,23): error TS2694: Namespace 'React' has no exported member 'ButtonHTMLAttributes'.
Error - typescript - node_modules\office-ui-fabric-react\lib\components\ChoiceGroup\ChoiceGroup.Props.d.ts(5,49): error TS2694: Namespace 'React' has no exported member 'InputHTMLAttributes'.
Error - typescript - node_modules\office-ui-fabric-react\lib\components\DocumentCard\DocumentCardActivity.d.ts(2,21): error TS2415: Class 'DocumentCardActivity' incorrectly extends base class 'BaseComponent<IDocumentCardActivityProps, any>'.
...

#### Actual behavior:

Client-side web part is not compiling because of the errors

#### Expected behavior:

Client-side web part is compiling without errors

**Comment by dzearing** [comment]
This is due to a major change in @types/react (which we can't control.) Can you please update your version to 15.0.38?

The release notes have been updated to more explicitly call this out. Please let us know if the problems go away.

https://github.com/OfficeDev/office-ui-fabric-react/releases/tag/office-ui-fabric-react_v4.29.0

**Comment by dzearing** [comment]
The `@types/react` 15.0.28 build (which you're likely on) also has a problem with `render` returning false. This was addressed in typings 15.0.29.

**Comment by AJIXuMuK** [comment]
@dzearing I'm on 0.14.46 for @types/react which is scaffolded by default with SPFx extensions.
If I try to update it to 15.0.29 or 16.0.0 then I'm getting 700 errors :) from practically everywhere :)
I'll try to investigate it deeply tomorrow.
But yes, it is not an Office UI Fabric issue. It's more like combining it with current version of SPFx.

**Comment by dzearing** [comment]
@AJIXuMuK Geez. Good luck. Hopefully they are not coming from Fabric. Let me know if there's something we need to change here.

**Comment by bateau** [comment]
owa-calendar is in the same boat.  We cannot update past 4.27.  We are on

 typescript 2.3.4
"@types/react": "15.0.27"
react@15.4.2

**Comment by AJIXuMuK** [comment]
yes, there is no way for now to use latest builds in SPFx.
@dzearing do you know if there is any previous build where `canCheck` and `isChecked (checked)` work for contextual menus in split button? It would be really helpful for me :)
I reported the bug about it on v 4.27.0 ([here](https://github.com/OfficeDev/office-ui-fabric-react/issues/2363))

Thanks!

**Comment by AJIXuMuK** [comment]
4.21.2 works for sure :)
