### ISSUE TITLE
TextField: text-overflow ellipsis 

### ISSUE THREAD

**Issue by veloiya** [OfficeDev/office-ui-fabric-react#2416]
### Bug Report

- __Package version(s)__: 4.17.1
- __Browser versions__: Firefox 54.0.1

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) VSTS

#### Describe the issue:

On text overflow inside the TextField, ellipsis sometimes do not appear.

#### Actual behavior:

[firefox-ellipsis.pptx](https://github.com/OfficeDev/office-ui-fabric-react/files/1206967/firefox-ellipsis.pptx)

#### Expected behavior:

On setting text-overflow: ellipses, ellipsis should always appear on overflow.

**Comment by erichdev** [comment]
@veloiya Are you still experiencing this? I wasn't able to repro

**Comment by erichdev** [comment]
Closing since there hasn't been an update and I'm unable to repro. Please reopen if any issues remain.
