### ISSUE TITLE
Rush tool's version doesn't meet the requirements.

### ISSUE THREAD

**Issue by zhangjingjingbupt** [OfficeDev/office-ui-fabric-react#2417]
### Bug Report
- __Package version(s)__: 4.30.1
- __Browser and OS versions__: all

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: can't run 'npm install' 

#### Describe the issue:
It will install rush tool of 3.0.7 version by default. This version doesn't meet the requirements. I think this issue is caused by the package-lock,json file. In the package-lock.json, the version of @microsoft/rush is set to '3.0.7'.

#### Actual behavior:
 The error is shown as follows:
 "Your rush tool is version 3.0.7, but rush.json requires version 3.0.11 or newer."

**Comment by qqli1209** [comment]
I got the same error today. I change the default version in `package-lock.json` to `3.0.11`. And I think they should change the default version in `package-lock.json` so that users can serve it correctly.

**Comment by dzearing** [comment]
@battletoilet @leddie24 This needs to be fixed asap.

**Comment by Jahnp** [comment]
It looks like @srideshpande's PR in #2413 addresses this.

**Comment by dzearing** [comment]
Removed the package-lock as well.
