### ISSUE TITLE
Dropdown mutates the arrays passed in options. {Selected: true} flags are not cleared.

### ISSUE THREAD

**Issue by ardallie** [OfficeDev/office-ui-fabric-react#2422]
### Bug Report

- __Package version(s)__: Dropdown: 4.30.0 Added multi-select support for dropdown (#2386)
- __Browser and OS versions__: all

#### Priorities 

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

#### Describe the issue:

Dropdown mutates the arrays passed in options by adding a property `selected: true` to each choice on selection. Also, it does not clear the `selected` flag after the user picked up a different choice. 
Deep cloning the array before passing to options prevented the unexpected state mutations.

#### Actual behavior:

```
 this.setState({
      dropOptions: [
        {key: 'A', text: 'Option a'},
        {key: 'B', text: 'Option b'}
      ]
    });

<Dropdown
  options={this.state.dropOptions}
/>
```

After selecting both options in GUI, the `console.log(this.state.dropOptions)` will output:

```
[
  {"key":"A","text":"Option a","itemType":0,"selected":true},
  {"key":"B","text":"Option b","itemType":0,"selected":true}
]
```

**Comment by fengyue1013** [comment]
This issue is very critical. When developer uses dropdown as a controlled element (using selectedKey props), the selection on a lower option won't trigger UI change.
Example: [A, B, C, D]. Current selection is A, when user selects D, dropdown still shows A

**Comment by micahgodbolt** [comment]
Fixed

**Comment by ardallie** [comment]
Thanks a lot!
