### ISSUE TITLE
Clicking on whitespace in DatePicker flyout causes control to unexpectedly expand (IE)

### ISSUE THREAD

**Issue by WasabiFan** [OfficeDev/office-ui-fabric-react#2426]
### Bug Report

- __Package version(s)__: `dev.office.com/fabric` version as of 8/8/2017
- __Browser and OS versions__: Internet Explorer 11 (11.483.15063.0)

#### Describe the issue:

In IE, clicking on any of the white space between month squares in the "date picker" control results in an odd expansion to occur:

![image](https://user-images.githubusercontent.com/3310349/29095284-2881b7da-7c45-11e7-8c57-88d9e6d856b1.png)

I can't tell what state change causes this; clicking again returns it to the normal layout.

This repros at https://dev.office.com/fabric#/components/datepicker.

**Comment by kellygorr** [comment]
This appears to be fixed in the current package version!

**Comment by erichdev** [comment]
Closing since this has been resolved. Note Fabric site has an issue in IE 11, the fix has been submitted and is pending deployment.
