### ISSUE TITLE
[DatePicker] Selected date / today's date is not distinguishable in High Contrast mode

### ISSUE THREAD

**Issue by martellaj** [OfficeDev/office-ui-fabric-react#2428]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal (a11y)

Products/sites affected: ODSP, any product that uses hosted share dialog

#### Describe the issue:

In high contrast mode, the selected date and today's date is not differentiated like it is normally. I expect the "special" dates to have some kind of distinguishable background in HC mode like it does in normal mode.

**Comment by martellaj** [comment]
@betrue-final-final Is it possible for you take a look? I investigated and can't make a background color show up. Is this just not a scenario that we can support?

**Comment by betrue-final-final** [comment]
Hmmm, well the rule of thumb is that backgrounds disappear in high contrast, but selection gets a background color for items in Windows.
![image](https://user-images.githubusercontent.com/20363037/29097487-e271113c-7c4e-11e7-97cb-78319fc9cb54.png)

I don't know how to make that work, but Windows did somehow. I would guess it's the browser's rules.
![image](https://user-images.githubusercontent.com/20363037/29097544-42e643b6-7c4f-11e7-8c65-194e4616abc9.png)

**Comment by betrue-final-final** [comment]
We could use the cyan/purple color for the border for selected, and white for today
![image](https://user-images.githubusercontent.com/20363037/29097671-f0d1f420-7c4f-11e7-902b-7e2f7571e291.png)
