### ISSUE TITLE
Feature Request: Add the filepicker component to fabric library

### ISSUE THREAD

**Issue by kngrace** [OfficeDev/office-ui-fabric-react#2431]
I realize there has been a lot of discussion back and forth about file pickers but since I recently had to create my own file picker in an SPFx app, I'd really like to request it again. 

Since my goal with using fabric react is to create a seamless experience for my end user, I'd like to use the similar looking, similar behaving components that the SharePoint product currently uses.

The below image is a filepicker contained within the new modern SharePoint site page. And yes, it is even called filepicker in the code snippet I've included below it. I believe it somewhat mimics the office open/save dialogue experience (I've included a screenshot from word below as an example). 

Essentially I'm looking for an easy way to activate a file picker (likely a panel) that allows me to to hook call backs for the file upon the user making their selection.

![image](https://user-images.githubusercontent.com/5940633/29098058-1d5145c6-7c52-11e7-8ea3-d0746c191a4c.png)

Code snippet: 

```
<div class="ms-Panel root_335ae920 filePicker_a1ab994b is-open rootIsOpen_335ae920 ms-Panel--xl rootIsXLarge_335ae920 ms-Panel--hasCloseButton rootHasCloseButton_335ae920">
  <div class="ms-Overlay root_ec9aca16 overlay_335ae920"></div>
  <div class="ms-Panel-main main_335ae920">
    <div class="ms-Panel-commands" data-is-visible="true">
      <button type="button"
              class="ms-Panel-closeButton ms-PanelAction-close closeButton_335ae920 ms-Button ms-Button--icon css-pkg9lh"
              data-is-visible="true" tabindex="0" aria-labelledby="126" data-is-focusable="true">
        <div class="ms-Button-flexContainer css-1myum7j"><i role="presentation" aria-hidden="true"
                                                            data-icon-name="Cancel"
                                                            class="ms-Icon css-liugll ms-Button-icon css-1f8up0l"></i>
        </div>
      </button>
    </div>
    <div class="ms-Panel-contentInner contentInner_335ae920">
      <div class="ms-Panel-header header_335ae920"><p
        class="ms-Panel-headerText headerText_335ae920 ms-screenReaderOnly" id="Panel40-headerText" role="heading">File
        Picker</p></div>
      <div class="ms-Panel-content content_335ae920">
        <div data-automation-id="sp-filepicker" class="focusTrapZone_a1ab994b">
          ......        
        </div>
      </div>
    </div>
  </div>
</div>
```

The above filepicker is activated from clicking on the add image to page title button within the editor for a modern SharePoint site page. See screenshot below for location:

![image](https://user-images.githubusercontent.com/5940633/29098055-15f5dd64-7c52-11e7-9b60-7d098aa0e222.png)

(Example of the file picker in Word when performing the Open command)
![image](https://user-images.githubusercontent.com/5940633/29098536-c26fd5ac-7c54-11e7-828b-da25a7b8d8de.png)

**Comment by nguyentoantuit** [comment]
👍 I am looking forward to seeing this component

**Comment by makafsal** [comment]
+1

**Comment by jonathanhotono** [comment]
Any news on this?
This has been asked on: 
https://github.com/SharePoint/sp-dev-docs/issues/504
https://github.com/SharePoint/sp-dev-docs/issues/396

I reckon this needs to be an official sharepoint react component that receives properties for options.

**Comment by makafsal** [comment]
+1

**Comment by yanckst** [comment]
+1

**Comment by keepWalking** [comment]
+1

**Comment by superigno** [comment]
+1

**Comment by kiefergrylls** [comment]
Any news about this feature ? Or a way to do a FilePicker like in an Office style ?

**Comment by KevinTCoughlin** [comment]
> Any news about this feature ? Or a way to do a FilePicker like in an Office style ?

We have two libraries for adding File Picker support to an application, they are:

1) [OneDrive File Picker](https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/?view=odsp-graph-online) - For a popup select file(s) work flow
2) [@microsoft/file-browser](https://www.npmjs.com/package/@microsoft/file-browser) - Embeds the same file / document library experience SharePoint / OneDrive uses in your React application. Soon to reach stable API.

Both of the above are composed of office-ui-fabric-react components.

**Comment by nguyentoantuit** [comment]
I implemented a custom filepicker using react-dropzone and office fabric UI. If you want to know the detailed implementation, pls see my post here  https://nguyentoanuit.wordpress.com/2017/11/12/react-dropzone/ 
Source code is in here https://github.com/nguyentoantuit/samples/tree/react-dropzone
