### ISSUE TITLE
TagPicker has an auto selection

### ISSUE THREAD

**Issue by JPeissker** [OfficeDev/office-ui-fabric-react#2435]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? 

Requested priority: (Normal) 

Products/sites affected: (if applicable)

#### Describe the issue:

With TagPicker, the first item is automatically selected
So that you have no chance nothing to choose.

**Comment by kristoferbrown** [comment]
@JPeissker, I'm not able to reproduce this issue. If you are still seeing this occur, please reopen this issue and add more details on how to get this issue to occur.
