### ISSUE TITLE
CommandButtons does not have border in high contrast

### ISSUE THREAD

**Issue by shyama1208** [OfficeDev/office-ui-fabric-react#2438]
All the buttons except commandButton have border in high contrast.
![image](https://user-images.githubusercontent.com/26054709/29116571-d28da940-7d18-11e7-9e8d-773606eeebf9.png)

**Comment by betrue-final-final** [comment]
This is by design. These buttons are meant to be used in a command bar, or standalone lightweight in an OWA message, and don't have a background or border in the rest state on non-high contrast. Please refer to the non-high contrast version of controls to understand what is needed in high contrast.

**Comment by shyama1208** [comment]
Yes, the commandButton does not have a border or background in non-high contrast mode. But even the IconButton does not have border in non-high contrast mode. However, IconButton has border in high-contrast mode.

**Comment by betrue-final-final** [comment]
That's a big on the icon button.
