### ISSUE TITLE
Detailslist interactive states are barely visible in high contrast

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#2443]
Are you willing to submit a PR to fix? (Yes)

Requested priority: (High) 

Products/sites affected: OneDrive, SharePoint

Going into high contrast, if you hover and/or select an item in the detailslist, you get a barely visible tiny check with some line-like goop around it. We used to have a very good high contrast visual here, where the checks and circles were visible, but that seems to have been removed. In the ideal case, we'd use the system color highlight, and highlighttext, to show selected items.

![image](https://user-images.githubusercontent.com/20363037/29130815-d1a42bfa-7cdf-11e7-93ed-f6baee996019.png)

**Comment by kristoferbrown** [comment]
@betrue-final-final, can you provide some guidelines/images for how this should look instead?
