### ISSUE TITLE
Quality check on "textboys" in personas

### ISSUE THREAD

**Issue by suztocco** [OfficeDev/office-ui-fabric-react#2464]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable)

#### Describe the issue:

The "initials" that show for small personas when there is no user photo looks very thin and unreadable. I am looking specifically at the size 24 persona but this may apply to other sizes. Also the initials do not really look centered horizontally in the circle.

#### Actual behavior:

font weight is too thin

#### Expected behavior:

a normal/regular font weight or whatever Ben Truelove or Angela Allison supplies from a design standpoint.

### If applicable, please provide a codepen repro:

![image](https://user-images.githubusercontent.com/20954039/29181280-6e76ee66-7daf-11e7-8e9b-0a9f5e715a9d.png)

![image](https://user-images.githubusercontent.com/20954039/29181352-aa09f054-7daf-11e7-8f64-63446b7565b2.png)

**Comment by kristoferbrown** [comment]
PR #2493 increased this font weight to regular.
