### ISSUE TITLE
Persona doesn't render initials for non-enu words

### ISSUE THREAD

**Issue by sulabh-msft** [OfficeDev/office-ui-fabric-react#2465]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix?  No

Requested priority: (Blocking, High, Normal, Low) 
Normal

Products/sites affected: (if applicable)

#### Describe the issue:
Persona doesn't render initials for non-enu words
Refer to the example provided in the office fabric site:
https://dev.office.com/fabric#/components/persona

![image](https://user-images.githubusercontent.com/13728069/29181554-3406d8b2-7e19-11e7-9cf2-99ee594cc867.png)

#### Actual behavior:

while we are getting initials generated for 
following names:
a. Kat Larrson
b. Annie Lindqvist

But we are not getting any initial for following:
宋智洋
남궁 성종
etc

#### Expected behavior:

We should get initial generated for non-enu words as well.

**Comment by erichdev** [comment]
Persona has prop `onRenderInitials` where you can pass a function to custom render initials, which you can use to handle other languages.
