### ISSUE TITLE
Dropdown in controlled mode (using IDropDownProps.selectedKey) mis-rendering current selection text when selecting 

### ISSUE THREAD

**Issue by fengyue1013** [OfficeDev/office-ui-fabric-react#2471]
### Bug Report

- __Package version(s)__: (4.31.0)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (High) 

Products/sites affected: (if applicable)

#### Describe the issue:

 When using selectedKey prop to render dropdown in the controlled patter, the dropdown current selection won't change according to user selection

#### Actual behavior:
 Selecting the second option, and then select the third(or 4th, 5th) option, the current selection text is still the second option

#### Expected behavior:
 The current selection text should be the third(or 4th, 5th) option

**Comment by micahgodbolt** [comment]
I wasn't able to repro this bug locally.

**Comment by chrisahhh** [comment]
I can repro for 4.30.0-4.32.0, if you're unable to repro feel to reach out to me chrbar@microsoft.com

**Comment by melvsparks** [comment]
This is creating a blocking problem within OWA Calendar. Can someone please explain to me how to use selectedKeys without having multiselect set to true. selectedKeys wont work correctly unless I set multiselect={true}.

**Comment by chrisahhh** [comment]
@melvsparks I was not able to get it to work

**Comment by micahgodbolt** [comment]
Okay! This is making more sense. slectedKey is not part of the DropdownProps, it is part of the inherited `ISelectableDroppableTextProps` which means it isn't the proper prop to use. If the problem is that you can use selectedKeys without setting multiSelect to true, we can fix that!

**Comment by micahgodbolt** [comment]
If you move the options into the component (rather than as a variable array) they work https://codepen.io/micahgodbolt/pen/gxoQgw?editors=1111

Mutability is fun, right!?!
