### ISSUE TITLE
[Dropdown][Query] Focus in high contrast for dropdown

### ISSUE THREAD

**Issue by ankitk94** [OfficeDev/office-ui-fabric-react#2474]
### Bug Report

- __Package version(s)__:  4.25.1002
- __Browser and OS versions__: Edge

#### Describe the issue:

Drop down is having type role as combo box, currently its text is highlighted like this:
![image](https://user-images.githubusercontent.com/6390909/29214471-1e82b8ba-7ec5-11e7-8b61-807de6dfe76d.png)

#### Expected behavior:

Currently we are expecting combo box to have following behavior on high contrast focus (text getting highlighted):
![image](https://user-images.githubusercontent.com/6390909/29214660-d820174a-7ec5-11e7-8504-9e8f4fe4fa2c.png)

**Comment by betrue-final-final** [comment]
This looks much better. @kristoferbrown, this can also align to using system variables.
