### ISSUE TITLE
Components Unicode character support - ü 

### ISSUE THREAD

**Issue by Cecildt** [OfficeDev/office-ui-fabric-react#2476]
### Bug Report

- __Package version(s)__: 4.31.0
- __Browser and OS versions__: All

#### Describe the issue:

When trying to use Unicode character in the CommandBar like ü it does not display the character. It only shows a ? mark.

#### Actual behavior:

Display ? character.

#### Expected behavior:

Should display Unicode character.

**Comment by Jahnp** [comment]
Hey @Cecildt, can you share more details of how and where you're using the CommandBar? Or what browser/device this is reproing in? 

By default, Segoe UI West European should be rendered, which definitely supports ü. Even if for some reason you aren't loading Segoe (e.g. if its download is blocked or if you choose for it to not be provided), all text *should* fall back to locally-installed fonts, which should also include ü.

I tested this locally on v4.32.0 by nuking all classes that set Segoe, and ü is still rendering--in my case falling back on Arial. Here's my highly-technical diagram illustrating this:
![image](https://user-images.githubusercontent.com/307118/29238439-8fe7cca0-7eea-11e7-812d-430567807757.png)

**Comment by PFAR** [comment]
Make sure you're not mixing up UTF-8 and Codepage 1252 encoding in text editor and charset (https://www.w3schools.com/html/html_charset.asp)

**Comment by Cecildt** [comment]
Thanks for the replies. The font is loading correctly. Looking at the js file that gets produced from webpack to compile the typescript to js I see the content is also wrong. I will first try to fix the output.
I think there is a problem related to the encoding of the final js output file.

{
        key: "newButton",
        name: "� Button � abc",
        icon: "AddTo",
        items: [],
        onClick: function (e) {
            e.preventDefault();
            return;
        }
    }

**Comment by Cecildt** [comment]
Some additional information: The problem was related to Visual Studio IDE not saving the files (.ts, .tsx) as UTF-8. This caused webpack to output the final JS file as ANSI. Always ensure your source files (.ts, .tsx) are saved with the file encoding UTF-8.

In VS IDE select the menu File -> Advanced Save Options to change the file encoding to Unicode (UTF-8 without signature) - Codepage 65001

**Comment by PFAR** [comment]
@Cecildt I would recommend to save it with signature (BOM byte order marker) so it's always clear for editors and compilers what the encoding is
