### ISSUE TITLE
[Details List] Double scrollbars in IE

### ISSUE THREAD

**Issue by ajaypantangi** [OfficeDev/office-ui-fabric-react#2480]
#### Describe the issue:
Details list show double scrollbars in IE 
![image](https://user-images.githubusercontent.com/5187165/29228011-fde74694-7e8c-11e7-9bb1-83bea1a9c4b7.png)

**Comment by Hardhik** [comment]
Also has scroll bars even where not needed. (in IE)
![scrollbar](https://user-images.githubusercontent.com/2673006/30794510-248009f4-a1e6-11e7-86a7-db5b9c9e064f.PNG)

**Comment by ramonitor** [comment]
I can confirm, this issue still exists. Even with the latest version (5.19.1 at time of writing).
