### ISSUE TITLE
Date picker that allows text input missing interaction on icon

### ISSUE THREAD

**Issue by suztocco** [OfficeDev/office-ui-fabric-react#2482]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: OWA

#### Describe the issue:

When I hover over the calendar icon no "hand" or interactive style appears to tell me that this is a clickable element even though it is. 

#### Actual behavior:

No visual indication of interaction

#### Expected behavior:

I would expect the "hand" to appear to tell me I can click on it. I am not sure what the "design" for this is but I could assume there may also be a change in the icon color for states (hover, press)

### If applicable, please provide a codepen repro:
You cannot see it below but a "text cursor" appears when I mouse over the calendar icon.

![image](https://user-images.githubusercontent.com/20954039/29233469-c12df82e-7ea5-11e7-9de2-69e1a203cc30.png)

**Comment by johannao76** [comment]
Which browser were you testing this on? I see a hand cursor in chrome, IE and firefox when hovering over the icon.

**Comment by enriquin** [comment]
In the official site: https://dev.office.com/fabric#/components/datepicker

- If you hover all the pickers except the one that allows the manual input, the cursor is the pointer. That's OK.
- If you hover the one that allows to enter the date (the one in the screenshot by @suztocco , the cursor is the default for textboxes (which is good), but when hovering the icon, it should be the pointer.

The generated HTML shows that the cursor css prop is set at the textfield level (so it's an all or nothing matter), but I think the icon should have its own cursor property to isolate from the behaviour of the textbox.

Tested in Chrome 60.0.3112.90 and Edge.

**Comment by johannao76** [comment]
Yeah, I see this now. Issue seems specific to the version that allows text input.
