### ISSUE TITLE
[Command bar] Command bar item has focus, but there is no visual indication of focus

### ISSUE THREAD

**Issue by ajaypantangi** [OfficeDev/office-ui-fabric-react#2483]
Command bar item has focus, but there is no visual indication of focus

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

**Comment by Jahnp** [comment]
Hey @ajaypantangi, can you provide a little more detail? Which version are you seeing this in? On both the Fabric website page for the [CommandBar](https://dev.office.com/fabric?id=1#/components/commandbar), as well as the local documentation for the latest version (v4.32.0), each item seems to have keyboard focus, as indicated by the inset grey border:
![image](https://user-images.githubusercontent.com/307118/29238157-95417f4a-7ee3-11e7-9799-4b7b96b619fa.png)

**Comment by erichdev** [comment]
Closing because no response. Please reopen if any issues remain
