### ISSUE TITLE
Don't have better font and css management  :(

### ISSUE THREAD

**Issue by ashutosh1211** [OfficeDev/office-ui-fabric-react#2484]
**1. CSS** 
Offical guide says **4.1.0-fabric.min.css** is latest but official site is using **7.1.0 - fabric.min.css**
Nowhere specified css versions.
when using 7.1.0 these are breaking changes like GRID.
7.1.0 don't have many grid classes like ms-lg* and ms-md*

**2. Font**

Don't have proper documentation for what font version to use , React fabric components not rendering latest fabricmdl2icons-2.38 icon font.

**Comment by ashutosh1211** [comment]
<CommandButton
                            data-automation-id='test'
                            iconProps={{ iconName: 'Delete' }}
                        >
                        Delete Selected
                        </CommandButton>

delete icon is not rendering, im refering to local fonts,

**Comment by enriquin** [comment]
Regarding the icon issue: Please refer to: https://github.com/OfficeDev/office-ui-fabric-react/issues/2205 There is an icon name mismatch, you should use Trash instead.

**Comment by enriquin** [comment]
Regarding the css, I'm currently using "https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/7.1.0/css/fabric.min.css" it has all the grid classes included.

Be aware, I think there were breaking changes in css class names between 4.1.0 and 7.1.0

**Comment by ashutosh1211** [comment]
TestBeaker icon not working in PivoteItem , its not rendering 😞

**Comment by BizH** [comment]
I can't get any of these new icons to show up on IconButons. For example:

```

                        <IconButton 
                            iconProps={{ iconName: "ArrowTallDownLeft" }}
                            />
```

does not render. If I change the iconName to the ones here: https://dev.office.com/fabric#/styles/icons, it works.
