### ISSUE TITLE
Button and toggle background changing colors randomly

### ISSUE THREAD

**Issue by holysnake91** [OfficeDev/office-ui-fabric-react#2485]
### Bug Report

- __Package version(s)__: 4.32.0
- __Browser and OS versions__: Chrome

#### Describe the issue:

I was using primary button, toggle in the component. The background color will random apply by green, pink or blue.

Expected the color will always  be blue.

What happen?

#### Actual behavior:
The color i get 
this apply the css class css-15f5vz1
![image](https://user-images.githubusercontent.com/15364241/29257953-765195fa-80e8-11e7-8f27-a069e3f4a421.png)

this apply the css class css-3pepvq
![image](https://user-images.githubusercontent.com/15364241/29258002-d6570688-80e8-11e7-9293-5645fcaed72b.png)

#### Expected behavior:

the correct css class was css-19sbuve
![image](https://user-images.githubusercontent.com/15364241/29258185-1ea8e342-80ea-11e7-9df9-296e8dd7d69d.png)

**Comment by micahgodbolt** [comment]
Are you manually adding the class name `css-15f5vz1` or is that the class name that has the background color?

There is nothing in our code that should be changing those backgrounds on their own. It appears that something in your application is overriding the themePrimary color.

**Comment by holysnake91** [comment]
Nope, those css class was generated by UI Fabric component and it has the background colour.

Below is the code i use for toggle
` <Toggle
                            id="arvsys-provt-tglApprover"
                            checked={this.state.requireAprv}
                            label=""
                            onText={strings.getString('yes')}
                            offText={strings.getString('no')}
                            onChanged={(value) => this.onRequireAprvChange(value)}
                        />`

` <Toggle
                            id="arvsys-provt-tglkeepPermission"
                            checked={this.state.keepPermission}
                            label=""
                            onText={strings.getString('yes')}
                            offText={strings.getString('no')}
                            onChanged={(value) => { this.setState({ keepPermission: value }); }}
                        />`

and this for the primary button 

` <PrimaryButton
                            id="arvsys-provt-btnBackEditPermission"
                            text={strings.getString('back')}
                            onClick={() => this.props.backStage(this.state.selectedTemplateID)}
                            type="button"
                        />`

`   <PrimaryButton
                            id="arvsys-provt-btnNextEditPermission"
                            text={this.props.action === 0 ? strings.getString('create') : strings.getString('update')}
                            disabled={this.btnDisable()}
                            onClick={() => this.submit()}
                            type="button"
                        />`

i didn't add any customize css class to those.

and the result for the html rendering, the css class name that have the background color was changing the name every time different deploy

for toggle
![image](https://user-images.githubusercontent.com/15364241/29300261-ff69fc1a-81a6-11e7-8a29-5d2b60be1826.png)

for primary button
![image](https://user-images.githubusercontent.com/15364241/29300345-72adb180-81a7-11e7-874c-9e396b5c456b.png)

**Comment by holysnake91** [comment]
And same code for another site, i get pink

for toggle
![image](https://user-images.githubusercontent.com/15364241/29300407-c6d0748c-81a7-11e7-8239-e06fbadd6051.png)

for button
![image](https://user-images.githubusercontent.com/15364241/29300432-e7b12368-81a7-11e7-8307-18e1af3467bc.png)
