### ISSUE TITLE
Expose css class properties on input element of search box.

### ISSUE THREAD

**Issue by nipunja** [OfficeDev/office-ui-fabric-react#2488]
We are hosting search box on top of panel. Our requirement is to move focus on search box when panel loads. The panel supports firstFocusableSelector props which expects a class name of a focusable element. However, we cannot use this property as search box does not allow you to give input class names.

**Comment by micahgodbolt** [comment]
firstFocusSelector is just a string that gets prepended with a period. So you can pass in a custom parent selector + the classname on the input.

https://codepen.io/micahgodbolt/pen/wqryaW

**Comment by nipunja** [comment]
@micahgodbolt  Is it ok to take dependency on "ms-SearchBox-field" on input ([reference](https://github.com/OfficeDev/office-ui-fabric-react/blob/3a198d4811b76f491acce31efa358c9c95740a63/packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.tsx)). I thought "ms-SearchBox-field" class name can be changed and it is not safe to take dependency on office fabric internal class names.

**Comment by micahgodbolt** [comment]
I don't think we could ever realistically get rid of those class names. The main thing we want to discourage is using class names to apply styles.

**Comment by erichdev** [comment]
Closing since question has been answered, please reply if any issues remain
