### ISSUE TITLE
Checkbox not getting focused on click

### ISSUE THREAD

**Issue by piyusing** [OfficeDev/office-ui-fabric-react#2489]
### Bug Report

- __Package version(s)__: (4.25.1001)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) 

Products/sites affected: (if applicable)

#### Describe the issue:
I see this is regressed because of this [commit]https://github.com/OfficeDev/office-ui-fabric-react/commit/9440c73f17ce503100d8f908db0d44a5adac5b0a#diff-c67edd8cc40e32a606cf1597c95dad82L123)

#### Actual behavior:
Focus is not shifting to checkbox when one clicks on it.
#### Expected behavior:
The checkbox is supposed to get the focus on clicks.

**Comment by whykushal93** [comment]
Is there a reason this issue is closed ? Do you think this is expected behavior ?
