### ISSUE TITLE
Border of TextField will be inconsistent when I change the zoom level of browser

### ISSUE THREAD

**Issue by YusongLiu** [OfficeDev/office-ui-fabric-react#2500]
- __Package version(s)__: 4.30.0
- __Browser and OS versions__: Chrome latest version

#### Describe the issue:

http://dev.office.com/fabric#/components/textfield

When I change the zoom level, the border of the TextField will be inconsistent. Sometimes the left and top borders are bold and somtimes the left and bottom borders are bold.
![image](https://user-images.githubusercontent.com/15144072/29301676-7562c862-81b0-11e7-96c0-ad2f4c2b5f17.png)

#### Actual behavior:

The border of the TextField will be inconsistent when I change the zoom level of browser.

#### Expected behavior:

The border should always be consistent when I change the zoom level.

**Comment by kristoferbrown** [comment]
This appears to just be a consequence of how browsers render things at different zoom levels. We have the borders consistently set to 1px, and this is how the browser is deciding to render 1px at different zoom levels.

I don't think there is anything we can do to improve this issue.

**Comment by YusongLiu** [comment]
@kristoferbrown If we add a 1px border to a plain div, there is no this issue. The issue seems only happens for TextField.
