### ISSUE TITLE
ContextualMenu: Icon picker component not to spec

### ISSUE THREAD

**Issue by suztocco** [OfficeDev/office-ui-fabric-react#2506]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable)

#### Describe the issue:

This component does not look to spec. 

#### Actual behavior:

-The size of the hovered backgrounds looks too large
- Icons are not centered
- I believe we would not center the icons in the gallery but they would be flush left
- There is no "retained" state showing
- I would think there may be a divider between the "none" and icon gallery.

This just doesn't seem like a component this is up to design spec. 

#### Expected behavior:

To feel more balanced and retain selected state

### If applicable, please provide a codepen repro:

![image](https://user-images.githubusercontent.com/20954039/29327519-478de43c-81a4-11e7-9b2e-90e3a104c995.png)

Example of design I worked on (we use our theme for selected state though)
![image](https://user-images.githubusercontent.com/20954039/29327643-b3d37288-81a4-11e7-81cf-5194c2ec4cf9.png)

**Comment by lynamemi** [comment]
@MLoughry I started working on a fix for this bug, but @Jahnp mentioned you might be a good OWA resource for this variant. Would you want to take this on? Or I can work on a PR and add you as a reviewer / code owner?

**Comment by MLoughry** [comment]
I'd be fine reviewing a change, but I don't have the bandwidth to make the change myself. I can see if the stakeholders on OWA Calendar would be able to contribute a fix.

**Comment by lynamemi** [comment]
Great! Keep me posted. If no bandwidth in OWA, I can move forward with it and add you as a reviewer.
