### ISSUE TITLE
DatePicker: Clicking on go to today doesnot take the focus to today.

### ISSUE THREAD

**Issue by bharay** [OfficeDev/office-ui-fabric-react#2516]
### Bug Report

- __Package version(s)__: Current version.

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No.

Requested priority: (Normal) 

Products/sites affected: (if applicable)

#### Describe the issue:

Clikcing on go to today, although takes us to today, doesnot look like it is taking us to today, as the keyboard focus border doesnot show up on today. I can confirm it actually takes you to today since pressing enter selects today's date.

**This behaviour is present in VSTS and https://dev.office.com/fabric#/components/datepicker but not in https://fabricreact.azurewebsites.net/fabric-react/master/#/examples/datepicker**

#### Actual behavior:
Keyboard focus border doesnot show.

#### Expected behavior:
Keyboard focus should come like in fabric azurewebsite.

**Comment by johannao76** [comment]
This issue has been fixed by commit 0e28d77 (see above pull request)
