### ISSUE TITLE
Panel - IE11 Content Overflow Y stretching past bottom of screen, no scroll bar.

### ISSUE THREAD

**Issue by HughWood** [OfficeDev/office-ui-fabric-react#2517]
### Bug Report

- __Package version(s)__: 2.34
- __Browser and OS versions__: IE11 <, Windows 10/8

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: SharePoint Online, SPFX

#### Describe the issue:

When there is enough content in a Panel component to create a scroll bar, the scroll bar isn't showing on IE11 without adding a height attribute in order to fix.

I'm not sure if there are other contributing factors the layout of the content was:

{values.map =>
div 
 label anchor input anchor
div}

This sometimes in a couple of cases pushed more inputs that could be displayed into the panel, this was then creating an overflow on Y.

This worked in all other tested browsers as intended.

#### Actual behavior:

Overflow-Y not adding scroll bar in IE11

#### Expected behavior:

Scroll bar appearing when content overflows on Y

**Comment by erichdev** [comment]
@HughWood Are you still having this issues? I'm unable to repro

**Comment by HughAJWood** [comment]
@erichdev I don't have access to the environment to see if this behaviour is still being exhibited. 

I found the panel height to be stretching to fit to the content off the bottom of the page and becoming hidden.

To fix I had to add and ieFix.css which contains:

.ms-Panel-content {
  height:90%;
}

**Comment by erichdev** [comment]
Thanks for the update. Since you have a workaround and I couldn't repro the issue, I'm going to close this. If you still experience this, feel free to reopen
