### ISSUE TITLE
There is no Maximize button for UI Fabric dialog style with close button

### ISSUE THREAD

**Issue by webdroidco** [OfficeDev/office-ui-fabric-react#2519]
#### Priorities and help requested :

I am using Microsoft UI Fabric Dialog style. But I need to add maximize button which will make the dialog full screen beside close button. I searched everywhere on internet but all in vain. I am not a pro developer and at the start of my degree. 
I know everyone here is professional and don't give attention to this minor task but please I really need some help here.

Thanks

**Comment by mikewheaton** [comment]
Hi @webdroidco, thanks for opening an issue here. You mentioned in your last email that you're using the [Office Add-in Dialog API Example](https://github.com/OfficeDev/Office-Add-in-Dialog-API-Simple-Example). I'm not familiar with this code, but from [this code](https://github.com/OfficeDev/Office-Add-in-Dialog-API-Simple-Example/blob/master/SimpleDialogSampleWeb/Dialog.html#L14) it looks to be using [Fabric JS](https://github.com/OfficeDev/office-ui-fabric-js) and not Fabric React. I know all of the various Fabric options can be confusing.

I see you've opened an [issue on the sample repo](https://github.com/OfficeDev/Office-Add-in-Dialog-API-Simple-Example/issues/4) so let's continue the discussion over there and see if we can figure this out. 😄
