### ISSUE TITLE
Deprecation warnings should not happen in production

### ISSUE THREAD

**Issue by pablonete** [OfficeDev/office-ui-fabric-react#2521]
Just like React, the deprecation warnings should only happen on the debug version. Any plans to disable this checking in production?

**Comment by dzearing** [comment]
You can disable them today:

```ts
import { setWarningCallback } from 'office-uifabric-react/lib/Utilities';

setWarningCallback(() => undefined);
```

I'm worried that if we key off `process.env.NODE_ENV === production` as other libraries do to strip commenting, it creates some friction for custom bundling partners (like OneDrive and VSTS).

I think the friction would be that you'd need to define the variable manually, something like this:

https://codepen.io/pen/?editors=1111

**Comment by dzearing** [comment]
Let me know in mail or chat if it is reasonable for us to use process.env.NODE_ENV. If so I will see what we can do.

**Comment by pablonete** [comment]
@dzearing The codepen link is empty, but I kind of get your point so I'll follow up with my team and come back with my findings.
