### ISSUE TITLE
[DetailsList] Impossible to trigger the click event of a child of a cell in the DetailsHeader

### ISSUE THREAD

**Issue by jessicabarns-umaknow** [OfficeDev/office-ui-fabric-react#2524]
### Bug Report

- __Package version(s)__: 2.31.0
- __Browser and OS versions__: Internet Explorer 11.540.15063.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/sites affected: SharePoint Framework Webpart/DetailsList component

#### Describe the issue:

In IE, in the DetailsList component, in the DetailsHeader, it is not possible to trigger an onClick event on a child of a cell (example: I want a contextual menu to open when I click the dropdown chevron). I even tried to bind an onClick event on the element with jquery, but I can't click on the icon. If I move the icon outside of it's parent, the click event works. It works in Chrome. I tried to remove the custom css, but it doesn't change anything. I tried to put the z-index of the icon to the max, but it doesn't work.

**IE**

![image](https://user-images.githubusercontent.com/20684514/29373130-3b5ba69a-827b-11e7-8d7b-58570109c4a9.png)

**IE if I move the chevron outside of the cell**

![image](https://user-images.githubusercontent.com/20684514/29373302-c67da19c-827b-11e7-862b-7bc5442b62c4.png)

**Chrome**

![image](https://user-images.githubusercontent.com/20684514/29373208-7c474876-827b-11e7-810a-92b174df738d.png)

#### Actual behavior:

Impossible to trigger the click event of a child of a cell in the DetailsHeader in the DetailsList component.

#### Expected behavior:

When I click on a child of a cell in the DetailsHeader in the DetailsList component, it should trigger it's onClick event.

**Comment by erichdev** [comment]
DetailsList now has the prop `onRenderDetailsHeader` that allows you to customize the header, including click events. Please reply if there are still any issues
