### ISSUE TITLE
Pin the left menu when scroll the main content

### ISSUE THREAD

**Issue by Hongbo-Miao** [OfficeDev/office-ui-fabric-react#2525]
Please pin the left menu when scroll the main content.

For example,
http://dev.office.com/fabric#/components/contextualmenu

When you scroll down, you need scroll back to use the menu.

**Comment by dzearing** [comment]
100% agree.

@battletoilet is there someone that can tweak the website?

**Comment by lynamemi** [comment]
I have been wanting to do this. I'll take a stab at it and see if we can get design on board with the change.
