### ISSUE TITLE
[Choice group] Style issue: Focus border overlapping the radio button.

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#2530]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: Chrome

#### Priorities and help requested (not applicable if asking question):

Requested priority: (Low) 

Products/sites affected: (Web part property pane)

#### Describe the issue:

The focus border can overlap with the text in Choice group.

#### Actual behavior:

![image](https://user-images.githubusercontent.com/7711735/29395016-b63bbd3a-8340-11e7-9f83-6e1822c95ae1.png)

#### Expected behavior:

![image](https://user-images.githubusercontent.com/7711735/29395045-d69b4118-8340-11e7-91c4-d2a0aaee0860.png)

### If applicable, please provide a codepen repro:

https://codepen.io/mikewheaton/pen/OjOXVj

Focus on second radio button repro the issue.

**Comment by MLoughry** [comment]
This seems to have been fixed at some point, judging by the fact that your CodePen no longer repros the issue.

![image](https://user-images.githubusercontent.com/20823465/31194851-3d52bc2e-a8fd-11e7-9c21-4af6a4b04af4.png)
