### ISSUE TITLE
Checkbox is able to change its state on single click

### ISSUE THREAD

**Issue by nipunja** [OfficeDev/office-ui-fabric-react#2532]
Checkbox is able to change its state on single click on EDGE browser.

https://dev.office.com/fabric#/components/checkbox

**Comment by kristoferbrown** [comment]
This is already fixed in the codebase, there's just a delay between that and the live documentation site. See here to test this issue in a more recent build: https://officedevcentersite-devx.azurewebsites.net/fabric#/components/checkbox
