### ISSUE TITLE
[Breadcrumb] Overflow button style is broken

### ISSUE THREAD

**Issue by htryggva** [OfficeDev/office-ui-fabric-react#2533]
### Bug Report

- __Package version__: office-ui-fabric-react 4.34.0

#### Priorities and help requested:

Requested priority: Blocking

#### Describe the issue:

The style of the context menu button to access the overflow items is broken.
Version 4.27.0 did not have this issue. We are unable to upgrade until this issue is fixed.

#### Actual behavior:

![image](https://user-images.githubusercontent.com/6515360/29403296-310b5bf0-8338-11e7-8831-82fad0941e01.png)

#### Expected behavior:

The button should have the style from package version 4.27.0

![image](https://user-images.githubusercontent.com/6515360/29403495-be206d8c-8338-11e7-9ddf-50d904242a32.png)

**Comment by micahgodbolt** [comment]
I've got this.
