### ISSUE TITLE
[Picker] Update documentation describing selectedItems prop

### ISSUE THREAD

**Issue by Fensterbank** [OfficeDev/office-ui-fabric-react#2535]
Since Pickers are now controlled components thanks to the great PR https://github.com/OfficeDev/office-ui-fabric-react/pull/2319, the [documentation and examples](http://dev.office.com/fabric#/components/pickers) should be updated by adding the prop `selectedItems` to the list.

**Comment by kristoferbrown** [comment]
This has already been updated in the code, there is just a delay before it reaches the live documentation website. It should be visible soon.
