### ISSUE TITLE
Create standalone fabric-react package to be used in a codepen.

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#254]
Could we provide a build of Fabric React that can be used directly in a simple app, without any NPM dependencies, build process, etc? I'm anticipating that we'll get questions like this from developers who are working on simple add-ins and want to just drop a reference in and start using it.

**Comment by dzearing** [comment]
I think this is just bundling work. It wouldn't be difficult to export all the stuff in a global namespace so that we can just load from cdn in a codepen.

**Comment by kmees** [comment]
The [webpack.lib.config](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/webpack.lib.config.js) is already configured for library output but it doesn't work (`ReactFabric` isn't globally available for whatever). The externals declaration is also kinda weird (declaring itself as an external dependency?)

Anyway, [this is the config](https://github.com/react-fabric/react-fabric/blob/master/webpack.config.js) that i used for my lib which should work if you add the typescript loader stuff. It also extracts the css module stuff in a seperate stylesheet.

I can try to get this working if you want

**Comment by mikewheaton** [comment]
That would be very helpful, @kmees!

**Comment by dzearing** [comment]
This is now complete. I've adjusted the bundle to export Fabric variable, so that you can make codepens like this one:

http://codepen.io/dzearing/pen/EgqMZq?editors=0110
