### ISSUE TITLE
No "Comment" icon in IconCodes.ts

### ISSUE THREAD

**Issue by benkaiser** [OfficeDev/office-ui-fabric-react#2550]
### Bug Report

- __Package version(s)__: master
- __Browser and OS versions__: any

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: SharePoint

#### Describe the issue:

Using an <IconButton> (or <Icon> for that matter) with the icon type 'Comment' (which is valid in Fabric core, and is listed on the fabric website), the icon is blank. A class seems to fail to be added because it doesn't exist in IconCodes.ts:

 https://github.com/OfficeDev/office-ui-fabric-react/blob/c66fa123e9533644a1e1401005c8dc8a425aa448/packages/styling/src/styles/IconCodes.ts#L689

#### Actual behavior:

Result on page:

![image](https://user-images.githubusercontent.com/608054/29482181-6698837e-8441-11e7-869d-e7f95dfea7ed.png)

#### Expected behavior:

Result on page:

![image](https://user-images.githubusercontent.com/608054/29482184-78936c9c-8441-11e7-9e17-1af13cfbf79d.png)

### If applicable, please provide a codepen repro:

https://codepen.io/anon/pen/PKQdgd

**Comment by mikewheaton** [comment]
Hey @benkaiser, this icon hasn't yet been included in `IconCodes.ts`. There's a new icon solution being worked on and right now Fabric React is behind Fabric Core. Could you submit a PR to add this icon? Here's [a similar PR](https://github.com/OfficeDev/office-ui-fabric-react/pull/2352) showing the files that need to be edited.

**Comment by benkaiser** [comment]
PR Submitted: #2569
