### ISSUE TITLE
question: changing default font size (to be smaller)?

### ISSUE THREAD

**Issue by aappddeevv** [OfficeDev/office-ui-fabric-react#2554]
How do you change the default font size that is used throughout the components?

I see its easy to change the color palette if you use loadTheme but after looking at the code, there does not appear to be a way to set the "default" font and I have tried setting it directly in a bunch of places but "medium" keeps getting used.

**Comment by vertonghenb** [comment]
I'm also wondering how to change the default font size, any easy way to do this instead of manipulating all the CSS?

**Comment by fidabhittani** [comment]
Anything on this...?

**Comment by fidabhittani** [comment]
What I did was, `.Fabric > * { font-Size: 12px   }` but some conrols stills retains its original fonts. to fix that I made it important which led to have all the children have 12 px even my custom classses..

**Comment by aappddeevv** [comment]
I think the new styling model is suppose to help with this but I'm not sure it's a "set it in one place" type of approach which is what I was looking for.
