### ISSUE TITLE
Persona: Can we self-define the persona image area width and height?

### ISSUE THREAD

**Issue by MirandaGe** [OfficeDev/office-ui-fabric-react#2558]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: High

Products/sites affected: People web part

#### Describe the issue:

We want to have a Persona with very large persona image:
![image](https://user-images.githubusercontent.com/16030290/29511239-21bd5106-8691-11e7-9914-9b7b6d9b1039.png)

Can we have a way to define the size of persona image ourselves?

**Comment by micahgodbolt** [comment]
extraLarge already goes up to 100px. Do you need larger?

**Comment by MirandaGe** [comment]
Yes, could better allow us to self-define the size or the whole Image component. The designer want to have a size like 182*182.
