### ISSUE TITLE
Dropdown [Multi-Select] - First option not selected

### ISSUE THREAD

**Issue by gunjandatta** [OfficeDev/office-ui-fabric-react#2573]
### Bug Report

- __Package version(s)__: 4.35.1
- __Browser and OS versions__: IE, Edge, Chrome

Are you willing to submit a PR to fix? (Yes, No)
Yes, but not sure how to branch in order to submit a pull request.

Requested priority: (Blocking, High, Normal, Low) 
Blocking

Products/sites affected: (if applicable)
Release of upgraded library using the multi-select option of the dropdown component.

#### Describe the issue:
The options will set the first index to 0. Line 441 of the Dropdown.tsx file sets the isItemSelected value. The logic if(item.index) -> if(0) will be false, so the first option won't be checked.

#### Actual behavior:
First option is not checked, but the title is updated

#### Expected behavior:
First option to be checked.

### Code Fix:
lines 440-442 of the Dropdown.tsx _renderOption method:

Old Code:
    if (this.props.multiSelect) {
      isItemSelected = **item.index** && selectedIndexes ? selectedIndexes.indexOf(item.index) > -1 : false;
    }

New Code:
    if (this.props.multiSelect) {
      isItemSelected = **item.index != null** && selectedIndexes ? selectedIndexes.indexOf(item.index) > -1 : false;
    }

**Comment by micahgodbolt** [comment]
@gunjandatta please fork the repo, then create a branch name of your choosing. Make the fix, run `npm run change` to create a change file, then create  PR with your changes the the changefile. 

If you have any other questions feel free to hit me up!

**Comment by gunjandatta** [comment]
Completed. Thank you for the help on my first pull request :)

**Comment by micahgodbolt** [comment]
Happy to help!
