### ISSUE TITLE
Issue with styles per component after version 4.18

### ISSUE THREAD

**Issue by mlp73** [OfficeDev/office-ui-fabric-react#2574]
### Bug Report

- __Package version(s)__: 4.35.1
- __Browser and OS versions__: all

#### Priorities and help requested (not applicable if asking question):
Are you willing to submit a PR to fix? No
Requested priority: Blocking 

#### Describe the issue:

Since upgrading to 4.35.1, the office-fabric-ui components implemented in our application appear without style. The issue didn't occur in previous version of fabric ui. It seems like we need to add something to adapt to the new architecture.

#### Actual behavior:
The components (Dialog, Panel, Checkbox, probably all of them) appear unstyled.
Example of component import:
import {
    Dialog,
    DialogType,
    ChoiceGroup,
    IPersonaProps,
    IDropdownOption,
    Spinner,
    Label,
    SpinnerSize
} from "office-ui-fabric-react";
 
The following core style is present in the head:
<link id="" rel="stylesheet" type="text/css" href="https://static2.sharepointonline.com/files/fabric/office-ui-fabric-core/5.1.0/css/fabric.min.css"/>

#### Expected behavior:
The component should appear with its styles. If an extra import is now necessary in this version, which one and how? (Note: we are using Less as a compiler)

**Comment by olemp** [comment]
Can this be related to https://github.com/OfficeDev/office-ui-fabric-react/issues/2562 @mlp73?

**Comment by mlp73** [comment]
Thanks! Yes. It is related. The styles are fine again when blocking require.js.
But...what now... :/

**Comment by olemp** [comment]
Blocking the file https://spoprod-a.akamaihd.net/files/odsp-next-prod_ship-2017-08-11-sts_20170818.001/listviewdataprefetch-784d3572.js makes the components render correctly for me, but that's not a fix.

This is relevant: https://dev.office.com/blogs/RequireJS-On-First-Release-Tenants

**Comment by dzearing** [comment]
Closing this as we're tracking in #2562, which should now be resolved for you!

**Comment by dzearing** [comment]
...and as mentioned in the other issue listed, this was an issue not with a specific version of Fabric, but with a performance optimization added to classic SharePoint pages which created a custom loadStyles method for load-themed-styles, which Fabric relies on. The optimization has been disabled, so you should be good now with no changes to Fabric or your usage.
