### ISSUE TITLE
[DetailsList] When header click doesn't have an action, header role shouldn't be "button"

### ISSUE THREAD

**Issue by satbai** [OfficeDev/office-ui-fabric-react#2594]
### Bug Report

- __Package version(s)__: all

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

#### Describe the issue:

The DetailsList header's role is always a button. Button makes sense when the header does sorting, but when it's just a header, the role shouldn't be a button.

#### Actual behavior:

header role=button
![image](https://user-images.githubusercontent.com/24945574/29636621-2a895dc2-8806-11e7-9221-e4e5756ec323.png)

#### Expected behavior:

Header role shouldn't be a button if clicking it does nothing.

**Comment by dzearing** [comment]
@ThomasMichon you've been tweaking things in this area

**Comment by erichdev** [comment]
The header is given a role of 'button' only if the column is not defined as disabled:

https://github.com/OfficeDev/office-ui-fabric-react/blob/8e5a33aca736718ff5a8b5b22606d51809c222fe/packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.tsx#L256

@satbai Closing for now, please reply if issues remain
