### ISSUE TITLE
withViewport: if content is initialized hidden, it is never rendered when shown.

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#260]
If you render the DetailsList in a hidden DIV, and then do something that causes the DIV to become visible, the withViewport decorator is never made aware of the change, so it doesn't re-render.

Consider a solution like:

https://www.npmjs.com/package/element-resize-event

**Comment by dzearing** [comment]
...or have an option in List/DetailsList to at least render some content in scenarios that can't be measured (hidden div, server side rendering, etc)

**Comment by aleksandrjPersonal** [comment]
Starting on this

**Comment by gitjain** [comment]
Looks like we have closed the issue so updating the status to close.
