### ISSUE TITLE
SpinButton, ComboBox

### ISSUE THREAD

**Issue by DennisKuhn** [OfficeDev/office-ui-fabric-react#2600]
#### Describe the issue:
I created a new SPFx webpart with using `yo @microsoft/sharepoint` version `1.1.3`. `ComboBox` and  `SpinButton` seem to be missing.

#### Actual behavior:

    import { SpinButton } from 'office-ui-fabric-react/lib/SpinButton';

gives the error

    Cannot find module 'office-ui-fabric-react/lib/SpinButton'.

Same for the ComboBox, "all" other components seem to work.

**Comment by DennisKuhn** [comment]
I am using version `2.31` wich seems old compared to `4.36`.  (How) can I update the office-ui-fabric-react part?

    npm ls office-ui-fabric-react
        i-logger-webpart@0.3.0 D:\spfx\iLogger-webpart
        `-- @microsoft/sp-webpart-base@1.1.1
          `-- office-ui-fabric-react@2.31.0

**Comment by dzearing** [comment]
@iclanton when is sp-webpart-base going to get updated? 2.31.0 is very old.

**Comment by iclanton** [comment]
We'll be releasing another drop this week. Hopefully today or tomorrow.

**Comment by DennisKuhn** [comment]
Thanks for your reply @iclanton wasn't there one just released?

    > npm update:
    +-- @microsoft/sp-build-web@1.2.0
    +-- @microsoft/sp-core-library@1.2.0
    +-- @microsoft/sp-module-interfaces@1.2.0
    +-- @microsoft/sp-webpart-base@1.2.0
    +-- @microsoft/sp-webpart-workbench@1.2.0
    `-- @types/react@15.0.38

    > npm ls office-ui-fabric-react
    `-- @microsoft/sp-webpart-base@1.2.0
      `-- office-ui-fabric-react@4.32.0

The `ComboBox` and `SpinButton` seem to be there. Or are you talking about another update?

**Comment by iclanton** [comment]
Ah you're right. Sorry I didn't realize it had already been published. Edited my comment.
