### ISSUE TITLE
Focus for DetailsList inside another DetailsList

### ISSUE THREAD

**Issue by veloiya** [OfficeDev/office-ui-fabric-react#2608]
### Bug Report

- __Package version(s)__: 4.17.1

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) VSTS

#### Describe the issue:

If one DetailsList is present inside another DetailsList, the inner DetailsList elements are not keyboard accessible.
This can be fixed by providing "isInnerZoneKeystroke" as a prop for the FocusZone in DetailsRow.

#### Actual behavior:

For a DetailsList inside another DetailsList, items in inner DetailsList are not keyboard accessible.

#### Expected behavior:

If any item in DetailsList has sub items, the sub items should also be keyboard accessible.

### If applicable, please provide a codepen repro:

https://codepen.io/ronaka/pen/jyZXwy

**Comment by erichdev** [comment]
Closing per comments on PR. Please reply if there are any updates or if this warrants additional discussion
