### ISSUE TITLE
Warnings when doing webpack

### ISSUE THREAD

**Issue by LeopoldLerch** [OfficeDev/office-ui-fabric-react#2610]
After todays update of package (currently 4.37.1) i am getting many warnings in the form of

WARNING in ./node_modules/@uifabric/utilities/lib/warn.js
(Emitted value instead of an instance of Error) Cannot find source file '../src/warn.ts': Error: Can't resolve '../src/warn.ts' in 'C:\Projekte\DA
P\DAP\Webkomponenten\node_modules\@uifabric\utilities\lib'
 @ ./node_modules/@uifabric/utilities/lib/index.js 32:21-38
 @ ./node_modules/office-ui-fabric-react/lib/Utilities.js
 @ ./Banner/Banner.tsx
 @ ./BodyStartSeite/BodyStartSeite.tsx
 @ multi ./BodyStartSeite/BodyStartSeite

when doing webpack

already deleted node_modules and reinstalled, but still the same error

**Comment by dzearing** [comment]
On it. Found the issue, it's related to sourcemaps. Re publishing a new patch asap!

**Comment by dzearing** [comment]
This should be published and fixed in 4.37.4.
