### ISSUE TITLE
[PeoplePicker] "Delete" keypress event is not stopped from propagating

### ISSUE THREAD

**Issue by martellaj** [OfficeDev/office-ui-fabric-react#2613]
### Bug Report

- __Package version(s)__: 4.30.0
- __Browser and OS versions__: Affects all browsers

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: ODSP

#### Describe the issue:

When a user deletes a selected person in the `PeoplePicker`, the "delete" key is not stopped from propagating, like other keys in the picker are. Is this by design or an oversight when it was added?

Offending code:
https://github.com/OfficeDev/office-ui-fabric-react/blob/c3dcef2f6aaa12705dec55b9fd60476daf6dbb31/packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx#L423-L433

#### Actual behavior:

"Delete" keypress event propagates and user is prompted to delete the file or folder that they have selected in ODSP.

#### Expected behavior:

"Delete" keypress event doesn't get propagated, and only the selected item is deleted from the picker.

**Comment by martellaj** [comment]
@joschect @kristoferbrown Ping.

**Comment by joschect** [comment]
I think that makes sense to do. I'll try and find some time to do that. Is it also expected that backspace will behave in the same manner?

**Comment by kristoferbrown** [comment]
Maybe the right thing to do would be to have an `event.stopPropagation` at the start of `onKeyDown()` so that no keys propagate up from this component at all?

**Comment by joschect** [comment]
Maybe, I think I'd rather have it be explicit for now.
