### ISSUE TITLE
SearchBox: Esc event should be bubbled instead of clear text when empty

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#2624]
We tried to use SearchBox in a Modal, but the SearchBox will block the esc event, so user can't close the modal dialog by pressing esc in the SearchBox.

My propositions:
1. Bubble the `esc` event when the text is already empty.
2. Provide a prop to disable the feature `pressing esc to clear the text in SearchBox`

**Comment by ipip2005** [comment]
Any suggestions on this issue?

We currently have to use keyboard event in capture level to work around this.

**Comment by micahgodbolt** [comment]
I'm not a huge fan of allowing for bubbling when it is empty, as that might have unexpected side effects. But it'd be pretty easy to override both escape and enter functions, or to replace the entire onKeyDown function.

**Comment by ipip2005** [comment]
That should help!
That only means we need to do the clear logic ourselves which is not hard to do
