### ISSUE TITLE
DetailList poor performance in rendering

### ISSUE THREAD

**Issue by ashutosh1211** [OfficeDev/office-ui-fabric-react#2627]
Im have only 576 records in details list to show , when I scroll the list items are rendering really very slow 😞 

Any suggestion for improvement of render performance of detailList

**Comment by ashutosh1211** [comment]
![image](https://user-images.githubusercontent.com/4639147/29725520-05fb2eb4-89ea-11e7-9902-60f274de020e.png)

As you can see frame drops as I scrolled

**Comment by dzearing** [comment]
Can you try using a production version of react? The debug version can be slower.

@jijizz may have a few other tricks that you can try.

**Comment by dzearing** [comment]
Also a variety of things can cause slow performance. Many of the examples render thousands of records with acceptable performance, so it could be how you have yours configured. If you could share a project that has the repro in isolation that would help.

**Comment by erichdev** [comment]
Closing because no response. Please reopen if any issues remain
