### ISSUE TITLE
Base button glamor font-family (in Fabric.styles.ts) overrides custom button font-family

### ISSUE THREAD

**Issue by jspurlin** [OfficeDev/office-ui-fabric-react#2628]
### Bug Report

- __Package version(s)__: 14.10.1

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? es

Requested priority: Normal

#### Describe the issue:

Trying to set the font-family on the root of a button does not get applied because Fabric.styles.ts has a base rule "<classname> button" which is more specific than the just classname selector that glamor creates on the button

#### Actual behavior:

the font-family is not applied

#### Expected behavior:

the font-family to be applied

**Comment by micahgodbolt** [comment]
@dzearing seems we should move these down to the individual components. Not sure why we were applying this to buttons in the first place.
