### ISSUE TITLE
For IconButton, provide a parameter to customize the iconname to replace the chevron-down icon

### ISSUE THREAD

**Issue by leoowen19** [OfficeDev/office-ui-fabric-react#2640]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) 

Products/sites affected: (if applicable)

**Comment by dzearing** [comment]
```tsx
<Fabric.IconButton 
        iconProps={{ iconName: 'Snow'}}
        menuProps={{ items: [] }} 
        menuIconProps={{ iconName: 'ChevronUp' }} 
      />
```
