### ISSUE TITLE
Detailslist check is too small

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#2662]
Are you willing to submit a PR to fix? (Yes)

Requested priority: (Normal) 

The current 20px check is too large for our lists, especially now with the compact list. Outlook and ODSP have agreed to make the check 18px instead.
18px check:
![image](https://user-images.githubusercontent.com/20363037/29828507-be58a208-8c91-11e7-8914-adaf0aac1af9.png)

**Comment by dzearing** [comment]
Correction, it is too small (it is currently 16px).

**Comment by betrue-final-final** [comment]
Thank you David! small != large
