### ISSUE TITLE
Dropdown control: Interactive colors wrong

### ISSUE THREAD

**Issue by suztocco** [OfficeDev/office-ui-fabric-react#2668]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable)

#### Describe the issue:

In the Design XD file the colors for the interaction are different than what I see in the build. For instance the "hover" outline color is the neutral grey/black but in the build it is "theme". 

#### Actual behavior:

The colors do not match the XD spec. Please sync with Ben or Angela as to the proper colors. 

#### Expected behavior:

To match design spec and be consistent with other form controls.

### If applicable, please provide a codepen repro:

![image](https://user-images.githubusercontent.com/20954039/29840062-7ec2fd54-8cb5-11e7-9c32-7645b2fc1dd4.png)

**Comment by Jahnp** [comment]
@lynamemi, could you take a look at this as part of your component page documentation clean-up?
