### ISSUE TITLE
Calendar: Navigation arrows not working when month picker only

### ISSUE THREAD

**Issue by kellygorr** [OfficeDev/office-ui-fabric-react#2670]
### Bug Report
Inline Calendar with month picker and no day picker (second to the last example on the calendar page).  The arrow navigations don't change the year in the header.  
![img](https://user-images.githubusercontent.com/25463697/29845445-b2b5a88e-8cc7-11e7-9607-c4dfdeff8aea.jpeg)

- __Package version(s) 1.0.0: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
This wasn't affecting the calendar team, so I don't have time to fix it!  I was told to submit a bug for it.

Requested priority: Low

Products/sites affected: (if applicable)

#### Describe the issue:
Navigation arrows now working when month picker only is enabled.
When the date picker and month are both enabled it does work.

#### Actual behavior:

When the navigation arrows are clicked the year stays at 2017

#### Expected behavior:

When the arrow buttons are clicked it should navigate to the next and previous years

**Comment by erichdev** [comment]
For reference, when the arrow is clicked, `navigatedDate` is not updated if only the month picker is shown. 

https://github.com/OfficeDev/office-ui-fabric-react/blob/0e28d77ec626cac7a3b4b923fe4411879fae5225/packages/office-ui-fabric-react/src/components/Calendar/Calendar.tsx#L188
