### ISSUE TITLE
[Documentation][CommandBar] Missing scss file in Fabric React with customized rendered items

### ISSUE THREAD

**Issue by gregdegruy** [OfficeDev/office-ui-fabric-react#2673]
## Describe the issue:

The [CommandBar example](https://dev.office.com/fabric#/components/commandbar
) in Fabric React refers to a file `import styles = require('./CommandBar.Example.scss');`. . . but

But does not provide the file to the developer or an example of the how this `.scss` could be constructed. 

I've found the `.scss` file [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/CommandBar/examples/CommandBar.Example.scss) I think and request it be included in the docs for the [CommandBar example with customized renderred items](https://dev.office.com/fabric#/components/commandbar
) in Fabric React.

### Bug Report

- __Package version(s)__:
```
"dependencies": {
    "@types/react": "^16.0.5",
    "@types/react-dom": "^15.5.4",
    "office-ui-fabric-react": "^4.37.6",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-scripts": "1.0.12"
  },
```

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? **Yes**

Requested priority: **Normal**

**Comment by dzearing** [comment]
I think that once we've published `merge-styles`, we will convert the examples to use styling via javascript and they can get included with the samples.

Another alternative is that we're working on codepen hosting for the examples. That would allow the examples to include code/css/html.

**Comment by micahgodbolt** [comment]
The current commandBar is going to be replaced shortly, and does not use additional external CSS for the example.

In general, example css is just use to pretty up the examples, and should never be required for actual production use.
