### ISSUE TITLE
DetailsList: activeRows overwritten when pushing new item 

### ISSUE THREAD

**Issue by cduvarney** [OfficeDev/office-ui-fabric-react#2676]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
Yes
Requested priority: (Blocking, High, Normal, Low) 
Normal
Products/sites affected: (if applicable)
VSTS TFS
#### Describe the issue:
this._activeRows in DetailsList.tsx currently overwrites the first element if a new item gets pushed. Doesn't keep track of added or removed rows.

#### Actual behavior:
Elements in active rows get overwritten

#### Expected behavior:
Elements get pushed to the front of this._activeRows and when removed, correct indices are applied to all other rows

**Comment by cschleiden** [comment]
Don't we re-render all rows when `items` change so `activeRows` should be updated? Could you provide a codepen with a repro?

**Comment by cduvarney** [comment]
When items changes, we do not do a full re-render. All rows mount only when the page is initially loaded. If a row is added or deleted, _onRowDidMount or _onRowWillUnmount is called only for the added or removed row, respectively. This means that _activeRows is not maintained correctly and the keys do not correlate directly to indices. This results in discontinuity in keys when a row is delete and overwriting the initial row when a new row is added. If you want to see this effect, it's visible in the current Rules for Work Item Types implementation in VSTS. Try adding or deleting a rule and see if _activeRows gets updated. I am unsure how to use codepen or what you would be looking to actually have uploaded. If you have an example for my to mirror that would be great and I'd be happy to do that.
