### ISSUE TITLE
TextField AutoAdjustHeight doesn't work in Edge 41.16193.1001.0

### ISSUE THREAD

**Issue by rickyp-ms** [OfficeDev/office-ui-fabric-react#2681]
### Bug Report

- __Package version(s)__: 4.21.3
- __Browser and OS versions__:
Edge version: Microsoft Edge 41.16193.1001.0
Microsoft EdgeHTML 15.16193
On a Surface Pro 3

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: tasks.office.com

#### Describe the issue:

An odd behavior has started to happen with the multiline resizable textfield e.g.
                <TextField
                    autoAdjustHeight={ true }
                    className="edit"
                    multiline={ true }
                    placeholder={ TaskDetailsEditorResx.DescriptionPlaceholder }
                    value={ this.state.updatedDescription }
                    resizable={ true }
                    onBeforeChange={ this.onDescriptionChanged.bind(this) }
                    onKeyDown={ this.taskDescriptionKeyPress.bind(this) }
                    onBlur={ this.taskDescriptionUpdate.bind(this) }
                    styleType={ "dialog" }
                    maxLength={ TaskDetails.DescriptionMaxLength }
                />

We have had a customer who complained about only being able to see 2 lines of text even though they had 15-20 lines of data inputted into the field

#### Actual behavior:

Seems the autoAdjustHeight doesn't work for this very specific version of edge. We have tried 40.15063.0.0 and it didn't have any issues

#### Expected behavior:

AutoAdjustHeight to work for all browsers

#### Note

This may very clearly be a Edge bug... feel free to close this and link it to one of theirs if it is!

**Comment by micahgodbolt** [comment]
Can you possibly get this into a codepen so that we can reproduce the issue?

**Comment by mdahamiwal** [comment]
@rickyp-ms , are you on insider builds? I tested this on relatively recent builds and it works as expected, might be an intermittent issue.

OS - Version 1703, (OS build 16279.1006)
Microsoft Edge 41.16279.1006.0
EdgeHTML 16.16279

**Comment by rickyp-ms** [comment]
Just had Amy who noticed the issue retry this and it didn't repro. She is on insider builds so that maybe the issue. Overall though, I think this is no longer an issue.
