### ISSUE TITLE
CheckBox receives focus on first click and doesn't change

### ISSUE THREAD

**Issue by DennisKuhn** [OfficeDev/office-ui-fabric-react#2683]
### Bug Report

- __Package version(s)__: 4.32.0
- __Browser and OS versions__: Chrome, Win 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Blocking, High, Normal, Low) 

Products/sites affected: (if applicable)

#### Describe the issue:

When clicking on the CheckBox the first time, it receives the focus spanning the label, the rectangle appears, but it doesn't change. It changes on the second and more clicks.

Other components like the `Toggle` and `DefaultButton` work directly. I am writing a SPFx webpart.

I noticed in the Chrome debugger, that an `::After` Element appears on the "ignored" first click and disappears when loosing focus.
![image](https://user-images.githubusercontent.com/992724/29913932-c52ea8d4-8e8a-11e7-852d-7c72b161aa3f.png)

#### Actual behavior:

Click on Checkbox, a rectangle around the tick and label appears. Click on it again the tick value changes.

#### Expected behavior:

Click on Checkbox, the value changes

**Comment by mdahamiwal** [comment]
Its seems to be working as expected at https://dev.office.com/fabric#/components/checkbox. I verified locally for latest version as well. Are you using it as controlled or uncontrolled component?

**Comment by micahgodbolt** [comment]
Is your code wrapped in a <Fabric> component? That single wrapper manages whether an element gets focus styles on click, or just on keyboard navigation. Not sure if that'd cause this issue, but it's worth asking.

Otherwise checkboxes are working fine for me chrome/win10 in 4.39.0 (latest master).

**Comment by DennisKuhn** [comment]
Maybe it is an issue in` 4.32.0` and is already fixed. `4.32.0` ships with the latest SharePoint builder. I just tested with the same result.

1. `yo @microsoft/sharepoint`
2. edit `components/HelloWorld.tsx`:
```
    import { Checkbox } from 'office-ui-fabric-react';
    ....
    <p className="ms-font-l ms-fontColor-white">
        <Checkbox label={'Test'} />
    </p>
```

3. run `gulp serve --nobrowser`
4. Open Chrome and navigate to [my hosted workbench](https://trustpaeroa.sharepoint.com/sites/pcst/spfxtest/_layouts/15/workbench.aspx)
5. Add `HelloWorld` WebPart and switch to `Preview` mode
![cb 1](https://user-images.githubusercontent.com/992724/29997382-a822fb1e-9065-11e7-8a3d-cad129acfdeb.PNG)
6. Click on the `Checkbox` the first time
![cb 2](https://user-images.githubusercontent.com/992724/29997389-c6ba555e-9065-11e7-96e6-4f2b4743eddb.PNG)
7. Click on it the second time
![cb 3](https://user-images.githubusercontent.com/992724/29997390-cbd72f4e-9065-11e7-8db0-4eee2a136c65.PNG)

**Comment by erichdev** [comment]
@DennisKuhn Are you still experiencing this issue?

**Comment by erichdev** [comment]
Closing because unable to repro. Please reopen if you still experience issues.

**Comment by balajilaxmanpastapure** [comment]
I am experiencing this issue, what is the solution?

**Comment by luke-oakes** [comment]
This might help someone else...

This was also happening to me, and it was because the value was 0, but the checkbox uses true and false. The first click (I assume), changed it from 0 to false, and the second click went to true.

I fixed it by adding two attributes to the checkbox component  false-label='0' true-label='1' (they're in the documentation)

**Comment by micahgodbolt** [comment]
@luke-oakes can you repro this issue outside of sharepoint? You can quickly make a codepen by going to the checkbox page and click on "Export to Codepen" 

https://developer.microsoft.com/en-us/fabric#/components/checkbox

**Comment by luke-oakes** [comment]
Haha, whoops.
I just realised I commented on the wrong project (which has exactly the same issue). Not quite sure how I got here!
You can ignore my last post, sorry.
