### ISSUE TITLE
version of office-ui-fabric-react with ComboBox that will work with SPFX RC0

### ISSUE THREAD

**Issue by russgove** [OfficeDev/office-ui-fabric-react#2708]
Hi ,
I have an spfx webpart using office-ui-fabric-react 2.34.2. I need to add a combobox, but thats not in 2.34.2. So i upgraded to 4.32.0 and got a bunch of errors.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(18,59): error TS1005: ',' expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(18,61): error TS1005: '>' expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(18,63): error TS1109: Expression expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(18,65): error TS1109: Expression expected.
Error - typescript - node_modules\office-ui-fabric-react\node_modules\@uifabric\utilities\lib\BaseComponent.d.ts(23,62): error TS1109: Expression expected

Is there a version that has the Combobox and is compatible with spfx (RC0)?

**Comment by spmcmanus** [comment]
Did you get this resolved?  I'm having the same issue.

**Comment by lszomoru** [comment]
Same here. I am running into this issue when trying to upgrade from 2.34.2 to 4.0.0. When I was seeing the errors I was using TypeScript 2.2.2. I just switched to TypeScript 2.5.3 and these errors went away but others appeared :)

**Comment by russgove** [comment]
Turns out the combobox does not work as I had hoped. Wen a user types the fist character , say "M; it scrolls to the  items in the list beginning with 'M'. But when he types the scrond character , Say 'O", it scrolls to the items in the list beginning with O. It really ought to scroll to the items beginning with 'MO'. I could not get that to work. 

Turns out the TagPicker control works great for this. Just set the itemLimit  to 1 and it can be used instead of the DropDown or the Combo Box.

**Comment by manishgarg1** [comment]
Hi @russgove, is this still an issue? If not could you please close?

**Comment by russgove** [comment]
closing issue
