### ISSUE TITLE
[Question] Missing components in website? (Tooltip, calendar)

### ISSUE THREAD

**Issue by enriquin** [OfficeDev/office-ui-fabric-react#2720]
Hello,

In the issues and in the source code, I see references to Tooltip and Calendar components. But there is no reference of them in the website (https://dev.office.com/fabric#/components).

Are they "production ready"? Only for internal use?

**Comment by micahgodbolt** [comment]
We just have a lag between creating new components and getting them onto the website. They are production ready, we just need to do the work to get them up there.

We DO have a new experiments package where we'll be keeping non-production ready components.
