### ISSUE TITLE
Unable to install via npm package

### ISSUE THREAD

**Issue by shubh54** [OfficeDev/office-ui-fabric-react#2722]
When I try to install the npm package in an existing project using 
npm install --save office-ui-fabric-react

I get following error 
npm ERR! Darwin 16.6.0
npm ERR! argv "/Users/gupta.shubham/.nvm/versions/node/v5.7.0/bin/node" "/Users/gupta.shubham/.nvm/versions/node/v5.7.0/bin/npm" "install" "--save" "office-ui-fabric-react"
npm ERR! node v5.7.0
npm ERR! npm  v3.6.0
npm ERR! code E404

npm ERR! 404 Not found : @uifabric/utilities
npm ERR! 404
npm ERR! 404  '@uifabric/utilities' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'office-ui-fabric-react'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by dzearing** [comment]
Npm must have had an outage. I just installed 4.42.0 no problem. Please check your .npmrc if it repros, you may have a custom registry setting as well.

**Comment by shubh54** [comment]
Yes, I was having a custom registry, adding the following to npm config fixed the issues.
@microsoft:registry=https://registry.npmjs.org
@uifabric:registry=https://registry.npmjs.org

Thanks.
