### ISSUE TITLE
Regression in DetailsList: Horizontal scroll in justified mode : 4.37.7 - 4.38.0

### ISSUE THREAD

**Issue by enriquin** [OfficeDev/office-ui-fabric-react#2724]
- __Package versions: 4.38.0 +
- __Browser and OS versions__: Chrome 60.0.3112.113, Microsoft Edge 40.15063.0.0 both in windows. **Seems to work ok in Mac Safari**

Are you willing to submit a PR to fix? No :(

Requested priority: High? (it's a regression)

#### Describe the issue:

After updating to 4.38.0 (and afterwards) there is an horizontal scrollbar in the body of the DetailsList

#### Actual behavior:

There is an unnecessary horizontal scroll bar, that wasn't in 4.37.7

#### Expected behavior:

No horizontal scrollbar

### If applicable, please provide a codepen repro:
You can see it here:

https://codepen.io/Intnovaction/pen/xLBwze

### Suggestion (my 2c)
Since the quick release rate (great!) of fabric UI makes introducing regressions more likely, it would be nice to have more examples in the website (or links to codepen with the examples), that way, it would be easier to spot regressions and guide the mantainers.

**Comment by dzearing** [comment]
@pablonete @leddie24 @ThomasMichon 

Can one of you please see if your recent changes would have affected this?

Expectation:

The DetailsHeader should be the same width as any DetailsRow. 

Result:

I see +4px on rows compared to header. I see a number of potential culprits; rows seem to be flexbox now, I see "minWidth" rather than width set... It could be recent changes to the width of the Check which caused this, I'm not sure.

**Comment by pablonete** [comment]
Checkbox column renders with 40px, while in code we expect 36px to calculate justified columns:
https://github.com/OfficeDev/office-ui-fabric-react/blob/d52a454962cbbcec7774e163f86052175cf075f1/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.tsx#L52

Who is right?

**Comment by enriquin** [comment]
Now you're having a look at the columns width, it would be great if justified columns had the same width when it's not explicitly specified, it seems that the first column without width takes as much space as it can.

Thanks!! ;)

**Comment by enriquin** [comment]
It seems fixed in 4.40!!
