### ISSUE TITLE
DetailsList borders occassionally dissapear after hover on Edge

### ISSUE THREAD

**Issue by zhangjingjingbupt** [OfficeDev/office-ui-fabric-react#2729]
When using DetailsList in Edge, as move mouse up over the list of sites, the horizontal lines between them disappear.

It looks like this:
![image](https://user-images.githubusercontent.com/30819290/30065840-c5d926f4-9288-11e7-9d59-beaeb3028646.png)

https://dev.office.com/fabric#/components/detailslist

**Comment by dzearing** [comment]
I can't repro this.

@zhangjingjingbupt Are you zoomed? I know that edge has quirks with zooming. This also could be a driver issue. Please try on another machine if you can, to confirm.

**Comment by zhangjingjingbupt** [comment]
I am not zoomed. It will disappear also if mouse move up in normal speed. Yes. I have tried in two machine. They all have this issue.
Thanks,
Jingjing




发自网易邮箱大师
On 09/06/2017 00:07, David Zearing wrote:

I can't repro this.

@zhangjingjingbupt Are you zoomed? I know that edge has quirks with zooming. This also could be a driver issue. Please try on another machine if you can, to confirm.

**Comment by micahgodbolt** [comment]
I was able to repro. Probably retina vs non retina screens and some rounding error.

**Comment by micahgodbolt** [comment]
Yup, confirmed. Repros on my big 27" monitor, but not my high rez 13" laptop screen.

**Comment by dzearing** [comment]
@micahgodbolt is this something fixable? Or just a quirk with Edge? I don't think this is fixable. If you have a repro and can identify a tweak, then, cool. But if not we should close.

**Comment by micahgodbolt** [comment]
I'd say close. It's a subpixel rendering bug in edge for sure.

________________________________
