### ISSUE TITLE
SearchBox: Add optional onClearClick to props.

### ISSUE THREAD

**Issue by kcurlett** [OfficeDev/office-ui-fabric-react#2739]
SearchBox has an "x" to clear search, clicking this calls "onClearClick()", which clears the text in the search box. In outlook.com we are using SearchBox and want to preform additional actions when this happens, in particular clear out of our search state. To do this we want to pass in our own onClearClick as a prop to SearchBox. 

Proposal: Make an optional prop "onClearClick: () => void;" in searchBoxProps, and add 

"if (this.props.onClearClick) {
    this.props.onClearClick();
}"

to the end of the onClearClick method in search box. 

Are you willing to fix: Yes.

**Comment by micahgodbolt** [comment]
@kcurlett i already tackled something like this for the onEscape, and wanted to take a similar approach for onClearClick. Take a look at my PR and example. The main difference here is that the onClear event is still accessible to the function, so that you can still perform the default action.
