### ISSUE TITLE
TextField validation - not always validating & box not going red

### ISSUE THREAD

**Issue by douglas-redplan** [OfficeDev/office-ui-fabric-react#2752]
### Bug Report

- __Package version(s)__: (3.10.10 - installed as part of `@microsoft/generator-sharepoint`)
- __Browser and OS versions__: (Windows 10 / chrome)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal)

#### Describe the issue:

I'm using the @microsoft/generator-sharepoint package to develop a web part for SharePoint.
Part of this web part is a form with text fields that require validation.

2 issues:
- The validation error message is removed on key press, but validation is not run if the underlying value of the TextField on not changed
- The TextField does not get a red border when validation fails 

#### Actual behavior:

To re-create the issue:
- Bring a TextField into focus and enter an __invalid__ value and leave the field, resulting in:
![image](https://user-images.githubusercontent.com/30898018/30116014-3fb8d6c8-9314-11e7-924c-94836c8d1c22.png)

- Go back into the TextField and type any character, resulting in:
![image](https://user-images.githubusercontent.com/30898018/30116780-53241cac-9316-11e7-95c5-7c150cc47282.png)

- Delete the entered character and leave the TextField - __no validation occurs__:
![image](https://user-images.githubusercontent.com/30898018/30116711-3004f3f4-9316-11e7-999b-b90de07dfd77.png)

#### Expected behavior:

The expected behaviour is that invalid values would result in the validation message being shown.

**Comment by erichdev** [comment]
@douglas-redplan Are you still experiencing this issue? If so, could you create a Codepen repro?

**Comment by erichdev** [comment]
Closing because unable to repro. Please reopen if you still experience issues.
