### ISSUE TITLE
DetailList: isCollapsable is ignored for first two columns

### ISSUE THREAD

**Issue by DennisKuhn** [OfficeDev/office-ui-fabric-react#2759]
### Bug Report

- __Package version(s)__: 4.32 (Still in current code)

#### Priorities and help requested (not applicable if asking question):
Are you willing to submit a PR to fix? (Maybe)
Requested priority: (Normal) 

#### Describe the issue:
When specifying `isCollapsable` for the first two columns, it has no effect.

#### Actual behavior:
The `isCollapsable` property is ignored for the first two columns, because the collapsing while loop goes from the upperBound down to **> 1** instead of **>= 0**.
```
    // Remove collapsable columns.
    while (lastIndex > 1 && totalWidth > availableWidth) {
      let column = adjustedColumns[lastIndex];

      if (column.isCollapsable) {
        totalWidth -= column.calculatedWidth! + DEFAULT_INNER_PADDING;
        adjustedColumns.splice(lastIndex, 1);
      }
      lastIndex--;
    }

    // Then expand columns starting at the beginning, until we've filled the width.

```

#### Expected behavior:
That any column can be specified as `isCollapsable`. In my case especially the second column is big and doesn't need to be displayed when not much space is available.

https://github.com/OfficeDev/office-ui-fabric-react/blob/19c7d3ad379a5f9c10f16e9a2a4e2726db21bd45/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.tsx#L612

**Comment by micahgodbolt** [comment]
Can you reproduce this error so that we know when we've fixed it? A codepen would be perfect https://aka.ms/fabric-starter-pen

**Comment by DennisKuhn** [comment]
Here is the [CodePen / pWzxda](https://codepen.io/denniskuhn/pen/pWzxda/left). The fourth column collapses nicely, while the second always remains.
