### ISSUE TITLE
[MessageBar] Text overflow for very long words

### ISSUE THREAD

**Issue by ankitk94** [OfficeDev/office-ui-fabric-react#2765]
### Bug Report

- __Package version(s)__: 4.35.1002
- __Browser and OS versions__: (fill this out if relevant)

#### Describe the issue:

Message bar allows overflow if a very long word is entered outside of message bar

#### Actual behavior:

When long words are rendered, they overflow from message bar

#### Expected behavior:

Message bar should have word break to take care of long words

### If applicable, please provide a codepen repro:

https://codepen.io/ankhokha/pen/LjogpG

**Comment by micahgodbolt** [comment]
got a solution for this...will commit shortly
