### ISSUE TITLE
Callout: support staying when opening another callout

### ISSUE THREAD

**Issue by bateau** [OfficeDev/office-ui-fabric-react#2769]
### Bug Report

- __Package version(s)__: 4.42
- __Browser and OS versions__: All

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: [owa-calendar](https://outlook-sdf.office.com/mail/calendar)
#### Describe the issue:

Go to [OWA Calendar](https://outlook-sdf.office.com/mail/calendar).
Click on any meeting on your calendar.  Observe Callout showing up with event details.
Click on organizer's name/photo.  

#### Actual behavior:

Persona Card will open in pop-out and dismiss event details.

#### Expected behavior:

Persona Card to open while keeping event details callout open.  
However, we do need to allow for stack of callout/pop-ups to dismiss if user clicks outside of the parent.

**Comment by micahgodbolt** [comment]
Hmmm, i think this is currently possible. https://codepen.io/micahgodbolt/pen/ZJdWzV?editors=1111

Need to see why it's not working in this example.

**Comment by micahgodbolt** [comment]
@bateau do you want to keep this open? Seems you've got an approach to evaluate.

**Comment by erichdev** [comment]
Closing since it seems this has been resolved when testing with the OWA link above. Please reply if any issues remain
