### ISSUE TITLE
ComboBox: Resolving ref doesn't return combo box instance

### ISSUE THREAD

**Issue by yaananth** [OfficeDev/office-ui-fabric-react#2775]
This issue applies to all components with decorators.
Combox uses a decorator `customizable`
So `_resolveRef` returns `ComponentWithInjectedProps` instead of `ComboBox`
Typical scenario would be to take ref from component and call for example - `focus`, since now we don't get the original component back, we can't trigger `focus `directly (other than wrapping it in a div and finding `input` and trigger focus on `HTMLInputElement `directly)

Did this come up before?

**Comment by dzearing** [comment]
Use `componentRef` to access the interface of a component. If the interface it returns is missing a method, please add it.

**Comment by yaananth** [comment]
Awesome! Yep didn't realize it's there, thanks!
