### ISSUE TITLE
DatePicker: Cannot select month, year, header etc. when placed inside react bootstrap modal

### ISSUE THREAD

**Issue by javedsha** [OfficeDev/office-ui-fabric-react#2785]
### Bug Report

- __Package version(s)__: 4.43.0

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low)  Blocking

Products/sites affected: (if applicable) Microsoft Internal

#### Describe the issue:

DatePicker component when used inside react bootstrap model, I am unable to select month, year etc. The date picker opens properly (though i have to set higher z-index), but once i try to click anywhere inside the date picker, it closes. The method '_calendarDismissed' is called immediately. **I have attached the callstack/
![datepickercallstack](https://user-images.githubusercontent.com/11423719/30217515-450fd4aa-94ae-11e7-840e-b0211c6e4052.JPG)
**

I am able to use the component properly if not placed inside the Modal component.

#### Actual behavior:

Date picker closes when clicked anywhere inside the date picker

#### Expected behavior:

Day, month, year should get selected and date picker should not get closed until and unless the day is selected.

**Comment by erichdev** [comment]
@javedsha I'm not sure what the conflict is with React Bootstrap's modal, but Fabric has its own Modal and Dialog components. I [tested with Dialog](https://codepen.io/erichdev/pen/VMVPbd) and did not experience this issue. Could you use Fabric's Dialog instead?

**Comment by erichdev** [comment]
Closing because no response and this may be an issue with React Bootstrap. Please reopen if you still experience issues.
