### ISSUE TITLE
[Accessibility] DetailsList - add aria labels for the sort button

### ISSUE THREAD

**Issue by daweffe** [OfficeDev/office-ui-fabric-react#2786]
### Bug Report

- __Package version(s)__: 4.21.3
- __Browser and OS versions__: all

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal) 

Products/sites affected: Planner

#### Describe the issue:

The upper left corner of the DetailsList table allows the user to sort the items.  It needs an aria label to explain what is being sorted by, and ascending or descending.

This button is confusing even for sighted users.  There is no indication of what the items are being sorted by.  It needs at least a tooltip or something.  Maybe also put the arrow in the column header being used for sorting.

The other column headers should also include ascending/descending in the aria label when appropriate.

#### Actual behavior:

It has no ARIA label.

**Comment by betrue-final-final** [comment]
Alright, breaking this down. You can sort by any column header just by tapping. Once you do, an arrow appears that shows the sort order on that column.

Fixes I see here:
1. A tooltip would be useful
2. An ARIA label saying what if it's sorting A-Z, Z-A, etc...I assume though that as a generic control we just need to put in "ascending" and "descending" as a stub, though those descriptions aren't very well understood by most people except mountain climbers, skiers and computer scientists.

**Comment by daweffe** [comment]
bump

**Comment by JasonGore** [comment]
ARIA has an [`aria-sort`](https://www.w3.org/TR/wai-aria-1.1/#aria-sort) property defined for this purpose. DetailsList makes use of this property and has for some time.

**Comment by JasonGore** [comment]
It's not clear how much of this issue is related to Accessibility vs. UI concerns but I do believe this addresses the Accessibility portion. If there is a UI concern I think the best thing to do at this point is create a new issue.
