### ISSUE TITLE
[DetailsList] Selection UI is broken in IE

### ISSUE THREAD

**Issue by martellaj** [OfficeDev/office-ui-fabric-react#2792]
### Bug Report

- __Package version(s)__: Reproing in master branch
- __Browser and OS versions__: IE, Chrome on iOS

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No (I'm on call)

Requested priority: High

Products/sites affected: ODSP (but all)

#### Describe the issue:

Here are screenshots:

![row selected](https://user-images.githubusercontent.com/1019478/30232821-de65961a-94a6-11e7-84c5-b50a96ed00e3.PNG)
![row unselected](https://user-images.githubusercontent.com/1019478/30232822-e0ff12fc-94a6-11e7-9537-4e1a9c908a9f.PNG)
![tile selected](https://user-images.githubusercontent.com/1019478/30232824-e251f55c-94a6-11e7-8575-34e3ef99250c.PNG)
![tile unselected](https://user-images.githubusercontent.com/1019478/30232825-e3705b72-94a6-11e7-8dbe-88f8dd1194f8.PNG)

**Comment by martellaj** [comment]
Seems like the "justify-content" property can be adjusted in ".Check_root_2ROvP" class. "flex-start" instead of "center" gets it closer, but then messes with the alignment in Chrome.

**Comment by dzearing** [comment]
@martellaj  i'm having a hard time reproing.
