### ISSUE TITLE
Tooltip OverflowMode.Parent is unreliable because we incorrectly calculate oveflow

### ISSUE THREAD

**Issue by aaronyzhou** [OfficeDev/office-ui-fabric-react#2816]
### Bug Report

- __Package version(s)__: (fill this out) Master
- __Browser an(fill this out if relevant)__: Edge/Chrome

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, HiNormal, Low) High

Products/sites affected: (if applicable) VSTS

#### Describe the issue:

Using tooltiphost with the TooltipOverflowMode.Parent option does not work reliably. Sometimes
the tooltip shows when it shouldn't and sometimes it does not show when it should. This is because the
way we calculate overflow is unreliable.

#### Actual behavior:

![image](https://user-images.githubusercontent.com/7392105/30348193-6e96e33c-97c3-11e7-8d9e-70cc019e1d10.png)
Edge. The link is smaller than the box and should not show a tooltip

![image](https://user-images.githubusercontent.com/7392105/30348271-a8da6672-97c3-11e7-8ba4-81a27e81a588.png)
Chrome. There is no tooltip evethough there should be. 

### If applicable, please provide a codepen repro:

https://codepen.io/aaronyzhou/pen/veBape

**Comment by erichdev** [comment]
@aaronyzhou Are you still experiencing this issue? I couldn't repro on my machine with your Codepen, even when using older versions of Fabric

**Comment by erichdev** [comment]
Closing because unable to repro. Please reopen if you still experience issues.
