### ISSUE TITLE
Facepile - add setting to allow it to not be focusable

### ISSUE THREAD

**Issue by daweffe** [OfficeDev/office-ui-fabric-react#2820]
### Bug Report

- __Package version(s)__: 4.21.3
- __Browser and OS versions__: all

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal) 

Products/sites affected: Planner

#### Describe the issue:

On task cards, we show a facepile of assigned users.  I do not want the facepile to be in the tab order at all in this view. 

In general usage of FocusZone is not recommended. Screen reader users usually have no idea when they need to switch to using the arrow keys to navigate.  Even if they do know that, it does not fit in well with screen readers because the user frequently switches between navigating with tab and navigating with the arrow keys and a virtual cursor.  So adding our own arrow navigation is confusing and makes it difficult for users.  When it is used, the aria label should end with instructions to use the arrow keys for navigation.

#### Actual behavior:

The first persona has tabIndex = 0, putting it in the tab order.

#### Expected behavior:

I want to optionally disable all focus on the facepile.

**Comment by daweffe** [comment]
bump

**Comment by natalieethell** [comment]
@daweffe so sorry for the late response here. The PR referenced above might satisfy your request!

**Comment by xugao** [comment]
@daweffe - this seems to be fixed now. can you double check your scenario?
