### ISSUE TITLE
Large dialogs do not scroll

### ISSUE THREAD

**Issue by rickyp-ms** [OfficeDev/office-ui-fabric-react#283]
In our application we have several very large dialogs of which on small windows would require scroll bars (vertical mainly as we try to have the contents variable up to 250px).

Seems the current instance of the dialog as of ^0.47.0 doesn't support scrolling dialogs.

![dialognotscrolling2](https://cloud.githubusercontent.com/assets/22225666/18566907/b24c4a86-7b4a-11e6-899a-0e5ac13f790a.png)

**Comment by rickyp-ms** [comment]
Note this is in all current browsers

**Comment by dzearing** [comment]
this has been resolved.
