### ISSUE TITLE
TagPicker component - Input box takes space on the screen even when component is in disabled state

### ISSUE THREAD

**Issue by techninja24** [OfficeDev/office-ui-fabric-react#2832]
### Bug Report

- __Package version(s)__: 4.44
- __Browser and OS versions__: All Browsers on windows 10

Are you willing to submit a PR to fix?  Yes

Requested priority: (Blocking, High, Normal, Low) Normal

#### Describe the issue:

Change the tagpicker component state to disabled. 
The input box still takes space on the screen

I want to use this as a readonly mode displaying a list of tags.

#### Actual behavior:
Change the tagpicker component state to disabled. 
The input box still takes space on the screen

#### Expected behavior:

Input box should not be rendered when the component is in disabled state

**Comment by erichdev** [comment]
@techninja24 Am I understanding correctly -- when disabled, you don't want the input box to show at all; instead, you want all the tags to be displayed?  If so, why not render another component, like a List?

**Comment by erichdev** [comment]
Closing because no response. Please reopen if any issues remain.
