### ISSUE TITLE
Styling bug: PrimaryButton does not color right hand side if used as a split button

### ISSUE THREAD

**Issue by wygoodin** [OfficeDev/office-ui-fabric-react#2833]
### Bug Report

- __Package version(s)__: 4.41.0
- __Browser and OS versions__: Chrome latest

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low)
Low

#### Describe the issue:

When a PrimaryButton is used as a split button, the right hand side of the split button is styled gray, while the left hand side is properly the primary button color.

![image](https://user-images.githubusercontent.com/30271291/30384804-2817137c-985a-11e7-85d8-c494c0d34d6a.png)

#### Actual behavior:

A split PrimaryButton has primary button coloring on the left, and neutral coloring on the right.

#### Expected behavior:

The whole split PrimaryButton should be the primary color.

### If applicable, please provide a codepen repro:

https://codepen.io/anon/pen/eGmYEX

**Comment by dzearing** [comment]
@micahgodbolt maybe this was missed

**Comment by micahgodbolt** [comment]
Here's the thing.....I Don't think primary button ever worked :) 

I was trying to figure out how it was done in the past, so I went a few commits before my button changes and voila!

![image](https://user-images.githubusercontent.com/1434956/30439122-ca368340-9927-11e7-9e9f-cc92e1a157c0.png)

**Comment by micahgodbolt** [comment]
Much better https://github.com/OfficeDev/office-ui-fabric-react/pull/2845
