### ISSUE TITLE
DetailsList column resizing jumpy in Edge

### ISSUE THREAD

**Issue by labrose** [OfficeDev/office-ui-fabric-react#2837]
### Bug Report

- __Package version(s)__: Unknown
- __Browser and OS versions__: Microsoft Edge 40.15063.0.0 Microsoft EdgeHTML 15.15063
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No, not a dev :)
Requested priority: Normal
Products/sites affected: Anyone using a DetailsList in Edge. Reproduces in VSTS (where I work) and also in O365 sites like SharePoint that are using it.

#### Describe the issue:

When you are dragging to resize columns, there is a noticeable delay between the mouse movement and the column resizing.

#### Actual behavior:

[See gif for VSTS](http://recordit.co/4QfYypPz4B).
[See gif for SharePoint](http://recordit.co/IetEpybwTX)

#### Expected behavior:

I would expect this to be a smoother transition (like in Chrome). [See gif
](http://recordit.co/THO4prYCAA)

**Comment by malinkody** [comment]
This is still an issue in the current version (6.157.2). Resizing columns on the DetailsList in Edge has a very noticeable delay. It makes sudden jumps instead of moving smoothly. Works fine in Chrome and Firefox. Have there been any updates since this issue was posted?
