### ISSUE TITLE
Selection example in website does not work

### ISSUE THREAD

**Issue by enriquin** [OfficeDev/office-ui-fabric-react#2838]
### Bug Report

- __Package version(s)__: 4.45?
- __Browser and OS versions__: Latest Chrome on windows, IE 11, etc.

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: ?

#### Describe the issue:

The selection example in the website does not seem to work. If you click Select All, nothing happens

### If applicable, please provide a codepen repro:

https://dev.office.com/fabric#/components/selection

**Comment by kristoferbrown** [comment]
This was fixed by PR #2429, it just looks like it hasn't made it into the live website yet.
