### ISSUE TITLE
Large dialog starts in the middle of the page

### ISSUE THREAD

**Issue by rickyp-ms** [OfficeDev/office-ui-fabric-react#284]
IE 11 bug only (all other browsers fail much more gracefully it seems)

With a large dialog that would usually require a scroll bar, it seems that due to IE 11's poor implementation of flex-box the dialog is always centered in the middle which means the top and bottom of the dialog get cut off.

This is in ^47.0.0

![dialogstartsinmiddle](https://cloud.githubusercontent.com/assets/22225666/18567076/6565d420-7b4b-11e6-8a09-dd92ceece8f8.png)

**Comment by rickyp-ms** [comment]
Looks like the fix is to possibly remove the following css values:
.ms-Dialog {
   display: flex;
   align-items: center;
}

and replace it with this:
.ms-Dialog {
   display: block;
}

All other values in that css style should stay the same.

**Comment by dzearing** [comment]
I believe this was resolved.
