### ISSUE TITLE
Checkbox in Edge: box shrinks if checked and text wraps

### ISSUE THREAD

**Issue by jon-klein** [OfficeDev/office-ui-fabric-react#2843]
### Bug Report

- __Package version(s)__: 2.34.3
- __Browser and OS versions__: Edge 38.14393.1066.0, Windows 10

Also currently reproduces on fabric site:  https://dev.office.com/fabric#/components/checkbox
(as of today 09/13/2017)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: Microsoft internal site, probably others

#### Describe the issue:

If checkbox is checked when control/page loads, then checkbox text/label is wrapped to multiple lines or window size is reduced so text begins to wrap, the checkbox becomes more narrow.
This was reported in similar issue #1229 03-09-17 then was closed 03-21-17, but it still happens in Edge.

#### Actual behavior:

https://dev.office.com/fabric#/components/checkbox
Before text wrap:
![checkbox snp1](https://user-images.githubusercontent.com/31938983/30406879-8ff4b68a-98a9-11e7-8322-8bdf8c546d3c.PNG)

After text wrap (made window more narrow):
![checkbox snp2](https://user-images.githubusercontent.com/31938983/30406864-7665d604-98a9-11e7-8513-f952929defde.PNG)

#### Expected behavior:

Checkbox is always the same, square, full size.

**Comment by micahgodbolt** [comment]
This is currently fixed in the current version of Fabric. The checkbox was missing flex-shrink: 0 which you can see was added here

https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Checkbox/Checkbox.styles.ts#L61
