### ISSUE TITLE
Contextual Menu: Right to Left Submenus Open to the Right

### ISSUE THREAD

**Issue by Boris-Em** [OfficeDev/office-ui-fabric-react#2847]
### Bug Report

- __Package version(s)__: 5.0
- __Browser and OS versions__: Firefox, Safari, Chrome, Edge

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Low

#### Describe the issue:

When rendered in RTL, the contextual menu opens its sub-menus on the right side by default.

#### Actual behavior:

![screen shot 2017-09-14 at 12 35 23 pm](https://user-images.githubusercontent.com/4613643/30452054-4982815a-9949-11e7-8290-5d0771f54733.png)

#### Expected behavior:

When rendered in RTL, the contextual menu should open to the left side by default.

**Comment by erichdev** [comment]
This has been fixed as of 5.4.0. Please reply if any issues remain.
