### ISSUE TITLE
Modal: Right to Left Title Padding

### ISSUE THREAD

**Issue by Boris-Em** [OfficeDev/office-ui-fabric-react#2849]
### Bug Report

- __Package version(s)__: 5.0
- __Browser and OS versions__:  Safari, FF, Chrome, Edge

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Low

#### Describe the issue:

The title on the modal components when in RTL don't have a gap with the edge of the view.

#### Actual behavior:

![screen shot 2017-09-14 at 2 02 10 pm](https://user-images.githubusercontent.com/4613643/30455674-9d9b71c8-9955-11e7-9550-84a4959475fb.png)

#### Expected behavior:

There should be a padding between the title and the edge of the modal, just like in LTR.

**Comment by micahgodbolt** [comment]
These styles are actually coming from the example styles, not the component itself. But yes, it makes for a unpolished looking demo, and promotes bad practice.
