### ISSUE TITLE
Remove Textfield's min-width of 180px and/or make the min-width a public variable

### ISSUE THREAD

**Issue by rickyp-ms** [OfficeDev/office-ui-fabric-react#285]
Looks like the css class ms-TextField-field has a min-width of 180px. This is slightly annoying for those of us who have slim controls who may need a much smaller space (e.g. a numerical input box which only goes up to 99).

The other issue is to make the min-width value public. In my code I have 4 fields, some dropdowns and some text inputs. I want them all to be the exact size so I used flexbox. I originally had

.parent {
   display: flex;
   flex-direction: row;
   flex-wrap: wrap;
}
.parent > * {
   flex: 1 1 150px;
}

But due to the min-width on the text input, the 150 got overridden and it ended up being 180 only for those fields. Since it's not a public variable, I can't change my flex values to so all my sizes match which would be like so:

.parent > * {
   flex: 1 1 max($minWidthOfTextField, $minWidthOfDropdown, $minWidthOfDatepicker);
}

But to be honest, to skip all this complexity, if we could just remove the min-width field, that would be better.

**Comment by dzearing** [comment]
This has been resolved.
