### ISSUE TITLE
Details List with Grouping OnGroupExpanded event

### ISSUE THREAD

**Issue by russgove** [OfficeDev/office-ui-fabric-react#2862]
Hi, 

I have a details list that is using groups. When A user expands one of the groups and selects an Item in that group my code processes the item and then  removes it from the list. The component then redraws. When It re-renders, the group is appearing collapsed. I want the group to stay expanded after it re-renders.

I figured i would just save the expanded group so that I could set the group up with isCollapsed:false on the re-render, but i cant seem to find an was looking for an OnGroupExpanded event. Is there a way to accoumplish what i am after? 
Also , is there a way to force a grouped details list to only allow one group to be opened?
Thanks
Russell

**Comment by russgove** [comment]
anbody?

**Comment by NikiSpassov** [comment]
I have absolutely the same issue, has anyone dealt with this?

**Comment by Zoman** [comment]
I'd appreciate some help on this too.

**Comment by cristuballa** [comment]
I also have same issue

**Comment by xugao** [comment]
@russgove - is `onToggleCollapse` what you looking for?
