### ISSUE TITLE
Collision between SharePoint OOB Styles and Office UI Fabric

### ISSUE THREAD

**Issue by mgordic** [OfficeDev/office-ui-fabric-react#2893]
#### Describe the issue:

I have a react app that's hosted on SharePoint Online in Content Query Webpart.
I notice that input elements has doubled borders and general element styling is not good, since it's applying OOB border styles from SharePoint and Fabric at the same time.

#### Actual behavior:

Both OOB Styles and Fabric styles are applied to TextField, and so on.

#### Expected behavior:

My expectation is that styles should not be applied at the same time. I see that only way to solve this is to disable OOB styles for input elements and so on...

**Comment by lynamemi** [comment]
Do you have any screen shots to help clarify the issue you are seeing?

**Comment by mgordic** [comment]
![react form](https://user-images.githubusercontent.com/4919036/31076813-51a2cce6-a77c-11e7-939e-9770ddadf3f6.PNG)
Hi,

here is a screenshot. Borders on input elements are doubled, dropdown is missing down arrow and so on...

Did I missed something in office-ui-react configuration?

thank you in advance!

**Comment by janopn** [comment]
Hi! I'm having the same problem right now... General styling is having lots of problems with collides.
I've been trying removing my own styles and react-fabric ones but cannot achieve the same result i achieve running the app in a local way.

**Comment by mgordic** [comment]
Hi,

I solve it by resetting OOB input element styles:

`input[type=password], input[type=text], input[type=file], select, textarea, .sp-peoplepicker-topLevel, .sp-peoplepicker-topLevelDisabled, .sp-peoplepicker-autoFillContainer, .ms-inputBox{
  border: solid 0px transparent !important;
}`

Also, Dropdown and Calendar icons were missing and I found that I need to call initializeIcons() function (although that's missing in documentation as requirement)

**Comment by lynamemi** [comment]
Thanks for figuring things out on the OOB side @mgordic !  We are working on getting the initializeIcons() documentation up on the website very soon. For now, you can reference the documentation for the Icons package: https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/icons
