### ISSUE TITLE
error indication for ComboBox and TextField should be similar

### ISSUE THREAD

**Issue by shyama1208** [OfficeDev/office-ui-fabric-react#2894]
How error is shown in ComboBox:
![image](https://user-images.githubusercontent.com/26054709/30639864-43d891a2-9e1e-11e7-94e9-9326b629285d.png)

How error is shown in TextField:
![image](https://user-images.githubusercontent.com/26054709/30639877-567ff20a-9e1e-11e7-8b59-1bf990fbdfa6.png)

There should be consistency in the style used here.
- The space between the component and the error message is more in case of ComboBox.
- The error icon for both the components should be same.

**Comment by betrue-final-final** [comment]
There should be no icon at all actually, and the distance from the control to the message should be 5px.
![image](https://user-images.githubusercontent.com/20363037/30658708-76ef5db0-9df0-11e7-9da0-51b72a29767f.png)
