### ISSUE TITLE
DetailsList: Allow resizing columns wider than maxWidth in justified layout 

### ISSUE THREAD

**Issue by jayspadie** [OfficeDev/office-ui-fabric-react#2902]
### Bug Report

- __Package version(s)__: 4.35.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: VSTS

#### Describe the issue:

minWidth and maxWidth are used in the initial rendering of column widths in the DetailsList using justified layout.  Previously, a user could still resize the column width wider than the initially rendered maxWidth to better view the content, but this ability was lost with [DetailsList: resizing justified columns #2418](https://github.com/OfficeDev/office-ui-fabric-react/pull/2418).  minWidth and maxWidth should still be respected to produce a reasonable initial column rendering, but a user should be able to override these with column resizing.

#### Actual behavior:

Users cannot resize columns less than minWidth or greater than maxWidth.  That might be OK if we could specify a larger maxWidth for the column of interest without unintended side effects, but that will result in the initial column layout using that maxWidth and being too wide in most cases.

#### Expected behavior:

Users should be able to resize columns outside the bounds of minWidth and maxWidth.

**Comment by hross** [comment]
Since this might break existing layouts who are now expecting the justified column resize behavior, maybe we should add another layout mode [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/ed78bd102529ecb5dc0500aaadd720a3b95e2a71/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.Props.ts)
