### ISSUE TITLE
Link should inherit the font-size of its parent

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#294]
The link is smaller than the surrounding text, when it should be the same size:

![image](https://cloud.githubusercontent.com/assets/1382445/18617782/04db119e-7d8d-11e6-8e6c-62f1a91ea900.png)

**Comment by dzearing** [comment]
Ha! I ran into this this morning as well. I added this to Link.scss in my changelist. Feel free to submit a smaller PR for just this.

```css
BUTTON.ms-Link {
  font-size: inherit;
}
```

**Comment by dzearing** [comment]
I believe this has been resolved.
