### ISSUE TITLE
Cannot copy text in Panel

### ISSUE THREAD

**Issue by Vivihung** [OfficeDev/office-ui-fabric-react#2954]
### Bug Report

- __Package version(s)__: 
    "office-ui-fabric-core": "5.1.0",
    "office-ui-fabric-react": "4.48.0"

- __Browser and OS versions__: 
Apply to all browsers

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
Yes

Requested priority: (Blocking, High, Normal, Low) 
Normal

Products/sites affected: (if applicable)

#### Describe the issue:
User cannot copy text in Panel.

#### Actual behavior:
You cannot select any string by mouse in Panel

#### Expected behavior:
User should be able to select and copy text in Panel.

### If applicable, please provide a codepen repro:
It can be repro in the documentation example
https://developer.microsoft.com/en-us/fabric#/components/panel

**Comment by dzearing** [comment]
This is now fixed in 5.0.1!
