### ISSUE TITLE
Dropdown CaretDown icon mising

### ISSUE THREAD

**Issue by holysnake91** [OfficeDev/office-ui-fabric-react#2967]
### Bug Report

- __Package version(s)__:5.0.1
- __Browser and OS versions__: Chrome

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? ( No)

Requested priority: (High) 

#### Describe the issue:

The CaretDown icon in Dropdown was missing
![image](https://user-images.githubusercontent.com/15364241/30908579-94fee0c6-a3b0-11e7-9611-ba51136cb5f4.png)

#### Actual behavior:

I used the Dropdown inside a Panel.
When render out the UI of Dropdown, the icon CaretDown was missing.
I was using the default Dropdown setting.

If compare the html in your site with the one i have render there is different in the component

![image](https://user-images.githubusercontent.com/15364241/30908339-e6faa802-a3af-11e7-85c8-fe082ddae5b1.png)
this from https://developer.microsoft.com/en-us/fabric#/components/dropdown

![image](https://user-images.githubusercontent.com/15364241/30908435-2498568c-a3b0-11e7-9c50-8527487bb82e.png)
this from mine render

from mine render the "i" was wrapped in a "span"

#### Expected behavior:

Dropdown with the CaretDown icon.

**Comment by eNeRGy164** [comment]
Do you get a warning in the console like 

> The icon "caretdown" was referenced but not registered.

Maybe you need to add `initializeIcons();` to your code
See https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/icons/README.md

**Comment by dzearing** [comment]
Yes, please call initializeIcons() in your application startup. This will let you either use the default CDN, or provide your own if you want to host the fonts in your CDN.

**Comment by holysnake91** [comment]
Yes, after add initializeIcons() , the icon was appear.
Please add the information on the website as this is a manual work needed by developer.
Currently i can't find any information for this in the website.
