### ISSUE TITLE
Will Fabric 4 still be maintained?

### ISSUE THREAD

**Issue by LeopoldLerch** [OfficeDev/office-ui-fabric-react#2968]
How long will the "old" version 4 of office ui fabric react will be maintained together with version 5? Is there any plan?

**Comment by dzearing** [comment]
Yep! so all master PRs go into 5. If there is a patch required for 4, you can create a PR that targets the 4.0 branch and we can publish patches.

I highly recommend moving to 5 as soon as you can but also recognize there are a few points of friction to address so there will be some delay.
