### ISSUE TITLE
DropDown does not render when updating selectedKeys with empty array.

### ISSUE THREAD

**Issue by aklepaker** [OfficeDev/office-ui-fabric-react#2971]
### Bug Report

- __Package version(s)__: 5.0.1
- __Browser and OS versions__: Chrome 61.0.3163.100 - Windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal) 

Products/sites affected: (if applicable)

#### Describe the issue:

I try to clear the selection in a multiselect DropDown list updating the variable (this.props.selectedGroups) in selectedKeys property as a empty array. 

```
            <Dropdown
              placeHolder="Custom placeholder"
              label="Custom example:"
              id="Customdrop1"
              ariaLabel="Custom dropdown example"
              onChanged={option => this.props.updateSelectedGroups(option.key)}
              selectedKeys={this.props.selectedGroups}
              multiSelect={true}
              multiSelectDelimiter=","
              options={this.props.groupItems}
            />
```

#### Actual behavior:

When updating selectedKeys there are no re-rendering of the DropDown component.

A **unqualified** guess gives DropDown.componentWillReceiveProps blocks the update since it's only validating newProps.selectedKey.

#### Expected behavior:

When providing an empty array of keys to selectedKeys i expect no selections in the DropDown component.

**Comment by MLoughry** [comment]
Wow... to be blunt, I'm not sure how this was ever even merged in this state. Controlled multi-select simply does not work; it reverts to uncontrolled when in multi-select.

I should have a PR with a fix by EOD.
