### ISSUE TITLE
List: Support ghosting experience while scrolling

### ISSUE THREAD

**Issue by markuskr** [OfficeDev/office-ui-fabric-react#2997]
The `List` component should support ghosting while the user scrolls. 

In my usecase I want to show a list of people with profile pictures who are loaded once the list entry becomes visible. Loading the profile pictures requires a network call, therefore I only want to do the call if the user is not scrolling through the list. Instead I want to display a ghosting experience. 

`react-virtualized` solves this by adding the `flag` is scrolling to the `renderCell` method (https://github.com/bvaughn/react-virtualized/blob/master/docs/List.md)

**Comment by erichdev** [comment]
@cschleiden Are you working on something like this?

**Comment by betrue-final-final** [comment]
This is a valuable feature for slow loading and large lists. We should have a design for this to work with several configurations.

**Comment by cschleiden** [comment]
No, not yet. But I think it could be a valuable addition.
