### ISSUE TITLE
SPFx - How to install latest version of Office-UI-React for SPFx v1.0.2

### ISSUE THREAD

**Issue by geogikk92** [OfficeDev/office-ui-fabric-react#3010]
How to install latest version of Office-UI-React for SPFx v1.0.2 for On-Premise server?

I can not use the latest version, what else to use as a framework like Office-UI-React

This is error when installed last version of Office-UI-React: 
![untitled](https://user-images.githubusercontent.com/14110861/31112882-14d96e8e-a81f-11e7-9ea2-4aff34daca17.png)

**Comment by Sohryu7** [comment]
got the same problem - gulp build uses ts version 2.2.2, tried to upgrade but failed :(
so same err for me

**Comment by geogikk92** [comment]
Is there anybody here?

**Comment by Sohryu7** [comment]
i ended up uninstalling (npm uninstall -g @microsoft/generator-sharepoint) and reinstalling (npm install -g @microsoft/generator-sharepoint@latest) and now it works for me :)

**Comment by Sohryu7** [comment]
that one really helped me: [https://today.collab365.community/story/deploy-sharepoint-framework-client-side-web-parts-to-sharepoint-2016-on-premises/](url)

**Comment by dzearing** [comment]
@iclanton Can you help here?

**Comment by dzearing** [comment]
The problem is that you need updated TypeScript to 2.4.x or above. However this is more of an SPFX question.

**Comment by rgylesbedford** [comment]
SPFx doesn't allow us to control which version of typescript is used. When using SPFx with SharePoint 2016 on-prem, we are stuck with an older version of typescript.

**Comment by michaelangotti** [comment]
@manishgarg1 @aditima Can you or someone from your team take a look at this to see if it is still valid? Thanks!

**Comment by HeToC** [comment]
up

**Comment by Netbah** [comment]
up

**Comment by JasonGore** [comment]
@geogikk92 I've heard newer versions of SPFx support newer versions of TypeScript. Is this still an issue for you?
