### ISSUE TITLE
Dropdown controlled versions are not working

### ISSUE THREAD

**Issue by hbsts** [OfficeDev/office-ui-fabric-react#3011]
### Bug Report

- __Package version(s)__: Current examples at developer.microsoft.com/en-us/fabric#/components/dropdown
- __Browser and OS versions__: IE 11, Chrome 61.0.3163.100 - Win 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/sites affected: https://developer.microsoft.com/en-us/fabric#/components/dropdown

#### Describe the issue:

Dropdown "controlled" versions are not working:

In IE 11 page is not loaded. May be this is a temporarily issue. 

In Chrome page is loaded, but the "Controlled" examples are not working: 
- "Controlled example" is working not at all (no selection possible). 
- "Multi-Select controlled example" seems to work, but does not really: F12 Developer Tools show following error: Uncaught TypeError: Cannot read property 'state' of undefined

#### Actual behavior:
- "Controlled" examples are not working resp. not working correctly. 
- Page is not loaded in IE 11

#### Expected behavior:
- No error messages in Developer Tools for controlled versions.
- Page is working in IE 11

**Comment by MLoughry** [comment]
Looks like it's a bug in the example page, and not the control itself. I will have a PR with a fix shortly.

**Comment by hbsts** [comment]
@MLoughry 
Exceptions (Cannot read property 'state' of undefined) are still thrown for 'Controlled example' and 'Multi-Select controlled example' at https://developer.microsoft.com/en-us/fabric#/components/dropdown
Could you please check?

**Comment by MLoughry** [comment]
It doesn't look like the website has been updated with my changes. I'm not sure of the cadence for such things: @micahgodbolt, do you?

**Comment by hbsts** [comment]
@MLoughry 
Now the behavior is different: 
1/ "Multi-Select controlled example" is working without exception in Chrome Dev Tools.
2/ Controlled example" is throwing exceptions: "TypeError: Cannot read property 'text' of undefined"
3/ In IE 11 the page is not loadding at all: "Promise is undefined". 
Could you check with Chrome and IE 11?

**Comment by hbsts** [comment]
@MLoughry
Thanks for the update.
Now the behavior is different:
1/ "Multi-Select controlled example" is working without exception in Chrome.
2/ Controlled example" is throwing exceptions: "TypeError: Cannot read property 'text' of undefined"
3/ In IE 11 the page is not loadding at all: "Promise is undefined". 
Could you please check the page in IE 11?

at 2/ 
'selectedItems' is used in onChangeMultiSelect and in changeState.
I did some minor changes and now it works in my SPFx Webpart. Even though I did not get the current exception at the examples page. Hope the following code saves time.

constructor() {
  super();
  this.state = {
...
    selectedSingleItem: null
...
  };
}

<Dropdown
  className='Dropdown-example'
  label='Controlled example:'
  selectedKey = { selectedSingleItem && selectedSingleItem.key}
  onChanged={ this.onChangeSingleSelect }
...
/>

@autobind
public onChangeSingleSelect(item: IDropdownOption) {
  this.setState({ 
    selectedSingleItem: item 
  });
}

**Comment by hbsts** [comment]
@MLoughry
Thanks for the update.
Now the behavior is different:
1/ "Multi-Select controlled example" is working without exception in Chrome.
2/ Controlled example" is throwing exceptions: "TypeError: Cannot read property 'text' of undefined"
3/ In IE 11 the page is not loading at all: "Promise is undefined".

at 2/
'selectedItems' is used in onChangeMultiSelect and in changeState.
I did some minor changes and now it works in my SPFx Webpart. Even though I did not get the current exception at the examples page. Hope the following code saves time.

constructor() {
super();
this.state = {
...
selectedSingleItem: null
...
};
}

<Dropdown
  className='Dropdown-example'
  label='Controlled example:'
  selectedKey = { selectedSingleItem && selectedSingleItem.key}
  onChanged={ this.onChangeSingleSelect }
/>

@autoBind
public onChangeSingleSelect(item: IDropdownOption) {
this.setState({
selectedSingleItem: item
});
}

**Comment by hbsts** [comment]
@MLoughry
Thanks for the update.
Now the behavior is different:
1/ "Multi-Select controlled example" is working without exception in Chrome.
2/ Controlled example" is throwing exceptions: "TypeError: Cannot read property 'text' of undefined"
3/ In IE 11 the page is not loading at all: "Promise is undefined".

at 2/
'selectedItems' is used in onChangeMultiSelect and in changeState.
I did some minor changes and now it works in my SPFx Webpart. Even though I did not get the current exception at the examples page. Hope the following code saves time.

constructor() {
super();
this.state = {
...
selectedSingleItem: null
...
};
}

..Dropdown..
  className='Dropdown-example'
  label='Controlled example:'
  selectedKey = { selectedSingleItem && selectedSingleItem.key}
  onChanged={ this.onChangeSingleSelect }


@autoBind
public onChangeSingleSelect(item: IDropdownOption) {
this.setState({
selectedSingleItem: item
});
}

**Comment by MLoughry** [comment]
The IE11 issue is unrelated to my changes. I've opened #3070 to track that issue.

**Comment by abdulkhaliquem9** [comment]
Please update this in documentation, As the onChange is not working for controlled Dropdown for "office-ui-fabric-react": "^6.27.0",.
I am making use of the deprecated  onChanged() callback currently. It is working fine.

**Comment by BenedictRasmussen** [comment]
I had this issue while using `"office-ui-fabric-react": "6.187.1"`. I also could not get the `onChange` vs `onChanged` workaround to work. I solved the issue by updating to `"office-ui-fabric-react": "^7.4.2"`
