### ISSUE TITLE
BasePicker does not have space/enter as an activate button

### ISSUE THREAD

**Issue by carsonal** [OfficeDev/office-ui-fabric-react#3013]
If using a selection picker, on key press enter should activate the picker popup if the picker popup is not currently up. 

The current behavior is that the picker pop-up only shows when a search is typed

Expected behavior is that enter should activate the picker popup with the default search query (aka no search and the top results)

**Comment by erichdev** [comment]
@carsonal I think what you're looking for is the `onEmptyInputFocus` prop. This takes a callback for when the user clicks the input and there's no search query. See the PeoplePicker docs for an example: https://developer.microsoft.com/en-us/fabric#/components/peoplepicker

Closing this, please reply if there are still issues
