### ISSUE TITLE
ChoiceGroup selection not working in 5.2.1

### ISSUE THREAD

**Issue by limefrogyank** [OfficeDev/office-ui-fabric-react#3015]
### Bug Report

- __Package version(s)__: 5.2.1  with React 15.4.2
- __Browser and OS versions__:  latest chrome & edge in Windows 10 build 16299

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/sites affected: n/a

#### Describe the issue:

ChoiceGroup doesn't allow any interactions for selecting an option whether using just text or an image.  The onChange event is not being invoked.  You can select an item via the `selectedKey` property and the `ChoiceGroup` responds to mouse hover by darkening the borders of the selection, but the actual click doesn't do anything.

#### Actual behavior:

Click on any option in a `ChoiceGroup` and the choice is NOT selected.

#### Expected behavior:

Clicking on a choice should cause a selection to occur.

**Comment by limefrogyank** [comment]
Well, crap... seems to be fixed in 5.3.0

**Comment by gongiskhan** [comment]
Hey,
This one seems to be back on react 16.2.0 with 5.3.0 and 5.47.0
Just try to bump the react version and you'll see it happening.
