### ISSUE TITLE
Fabric Core: Document grid nesting and offsets

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#3016]
The documentation doesn't cover nesting the Grid component or using offset classes. See [issue #855 on Fabric Core](https://github.com/OfficeDev/office-ui-fabric-core/issues/855) for details.

**Comment by michaelangotti** [comment]
@mikewheaton What is the status with this one?

**Comment by mikewheaton** [comment]
Doesn't look like it's been documented. When it is, this is the page it should go on: https://developer.microsoft.com/en-us/fabric#/styles/layout

**Comment by mikewheaton** [comment]
This is still a valid issue, Stalebot.

**Comment by micahgodbolt** [comment]
@mikewheaton where should this go? close it? Put it in a backlog? Really isn't in the Fabric React realm at all.

**Comment by mikewheaton** [comment]
@micahgodbolt We had been putting any documentation-related issues in Fabric React, since the website is in this repo. But it's probably best to move this to Fabric Core. I'll file a new issue there and close this one.
