### ISSUE TITLE
Fabric Core: Update documentation for how to use RTL styles

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#3017]
See [pull request #1029](https://github.com/OfficeDev/office-ui-fabric-core/pull/1029) for details on the change.

**Comment by michaelangotti** [comment]
@mikewheaton What is the status of this one?

**Comment by mikewheaton** [comment]
Looks like the [localization page](https://developer.microsoft.com/en-us/fabric#/styles/localization) has not yet been updated. I'm seeing some other issues there where icon class names overlap.

**Comment by mikewheaton** [comment]
This is still a valid issue, Stalebot.
