### ISSUE TITLE
ComboBox does not show suggestions immediately

### ISSUE THREAD

**Issue by abettadapur** [OfficeDev/office-ui-fabric-react#3019]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: all

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

#### Describe the issue:

Combo box should have a property which allows me to see the suggestions immediately after focusing the text box

**Comment by abettadapur** [comment]
We need a different behavior, closing this issue

**Comment by IanVS** [comment]
For what it's worth, I agree that focusing the text in the combobox should show the dropdown.  I think it could be unclear to users that they must click the chevron to see suggestions.
