### ISSUE TITLE
Controlled SpinnerButton, more precisions

### ISSUE THREAD

**Issue by naydnabil** [OfficeDev/office-ui-fabric-react#3023]
in the documentation, under the spinnerButton section : There is no difference between the source code example you provide for the "Basic SpinButton" and the "Stateful SpinButton"..
How to create a controlled spinnerButton?
how to get the value using refs? when i try giving a ref and retreiving the value proprety i get undefined
You say :
>  value = The value of the SpinButton. Use this if you intend to pass in a new value as a result of onChange events.
>  This value is mutually exclusive to defaultValue. Use one or the other.

witch onChange events?
Thank you

**Comment by dzearing** [comment]
@jspurlin @christiango fyi

**Comment by jspurlin** [comment]
The issue is that the code referenced for the controlled SpinButton Example is actually pointing at the basic example code... I'll fix this
