### ISSUE TITLE
Pickers. Make onItemSelected cancellable

### ISSUE THREAD

**Issue by Ridlsan** [OfficeDev/office-ui-fabric-react#3036]
Can u fix code of onItemSelected of BasePicker.
If onItemSelected returns null, then dont do anything. So we can check if item already selected and cancel adding without error

**Comment by dzearing** [comment]
@joschect Can you look?

**Comment by joschect** [comment]
@Ridlsan Definitely, I think that should be pretty easy. That said, what should happen to the displayvalue? Does that still clear out normall? Or should it keep whatever value is set there. For instance I enter the name of a person who has already been been added, and then click that person. Should the menu just not dismiss at at all and the name remain in the input field? Or should the suggestions disappear as normal and the input field get cleared even though no new person is added.

**Comment by Ridlsan** [comment]
@joschect i think just disapear, like it was selected.

**Comment by sortegamartin** [comment]
It would be nice that when the function returns null, the code would not be error and also that the element will not be added to the array of selectedItems. Right now I have to control the duplicate elements from the onchange function.
