### ISSUE TITLE
Question - How to retrieve checkbox label ?

### ISSUE THREAD

**Issue by OverkillTV** [OfficeDev/office-ui-fabric-react#3037]
Hi all,
This is not an issue. It's just a small question since I couldn't find where to post this.
If I have a Checkbox like this:
<Checkbox
                      defaultChecked={false}
                      label={"ABC check"}
                      onChange={ this._onCheckboxChange }
                      />

How do I get the checkbox label inside the _onCheckboxChange method ?

Thanks,

**Comment by erichdev** [comment]
Checkbox has the prop `onRenderLabel` where you can use a custom render function for the label, which means you can set a ref for the label, connect it to state, etc

**Comment by OverkillTV** [comment]
Thanks @erichdev ! I'll try it out.
