### ISSUE TITLE
Feature request: PeoplePicker - Allow expansion of PDL/groups 

### ISSUE THREAD

**Issue by amyngu** [OfficeDev/office-ui-fabric-react#3044]
Currently there is no way to allow expansion for PDLs/groups 

Priorities and help requested (not applicable if asking question):
Are you willing to submit a PR to fix? Yes!
Requested priority: Normal

**Comment by Jahnp** [comment]
@amyngu first, is this still a feature that you need? Second, can you share some more details on the exact functionality you're looking for? It's not clear how this would be a front-end fix, and this isn't on the core Fabric Team's immediate roadmap. It sounds more like a feature that would be implemented by the host, but it'd be good to know what exactly you're looking for.

**Comment by amyngu** [comment]
This actually isn't something that I need anymore. This can be closed.

**Comment by Jahnp** [comment]
Great, thank you!
