### ISSUE TITLE
HoverCard Scroll broken

### ISSUE THREAD

**Issue by chaofeng2014** [OfficeDev/office-ui-fabric-react#3046]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) 

Products/sites affected: (if applicable)

#### Describe the issue:

Recent change in ExpandingCard.styles.ts set "expandedCard overflowY" as hidden, which disable the scroll function in expand card

**Comment by dzearing** [comment]
@leddie24 or @atneik Could one of you investigate?
