### ISSUE TITLE
GroupedList group with items and children doesn't show the items.

### ISSUE THREAD

**Issue by EduardoN** [OfficeDev/office-ui-fabric-react#3051]
### Bug Report

- __Package version(s)__: (2.20.0)
- __Browser and OS versions__: (Chrome / WIn 10)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (High) 

Products/sites affected: (if applicable)

#### Describe the issue:

If a group name A has count 7 and startIndex 5 and has children B with count 3 and startIndex 7, I get a  tree with A containing B and B containing 3 items but the other 4 items inside A are not shown.

#### Actual behavior:

Items are not shown side by side with children

#### Expected behavior:

Items are shown side by side with children

**Comment by cschleiden** [comment]
Could you provide a codepen repro?

**Comment by michaelangotti** [comment]
@EduardoN We are currently closing out all issues preceding Fabric React v5. If you are still seeing the same issue, please open a new issue.

@aditima for visibility.
