### ISSUE TITLE
Webpage Colors style color code is wrong

### ISSUE THREAD

**Issue by limefrogyank** [OfficeDev/office-ui-fabric-react#3052]
### Bug Report

- __Package version(s)__: NA
- __Browser and OS versions__: 

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)  No

Requested priority: (Blocking, High, Normal, Low)  Low

Products/sites affected: (if applicable)  https://developer.microsoft.com/en-us/fabric#/styles/colors

#### Describe the issue:

The color code that describes the 'themeLight' color (main blue theme) is wrong.

#### Actual behavior:

Color listed as '#c730f4' for 'themeLight'

#### Expected behavior:

Color should be listed as '#c7e0f4' for 'themeLight'

### If applicable, please provide a codepen repro:

NA

**Comment by lynamemi** [comment]
We recently tackled this issue so this might be a regression. I will look into it.  Thank you!
