### ISSUE TITLE
Demo-Page not working in IE11

### ISSUE THREAD

**Issue by LeopoldLerch** [OfficeDev/office-ui-fabric-react#3053]
Hy,

don´t really know if I am at the right place here, but the demo page

https://developer.microsoft.com/en-us/fabric#/components

does not work anymore in IE11. Console writes an error about Promise is not defined (of course, its IE11 *g*). Maybe there is a polyfill missing?

No single component description is clickable. Chrome works fine

**Comment by lynamemi** [comment]
@dzearing  Someone posted this in the Office UI Fabric / General / Teams channel, too, and I was able to repro it. Looks like it might be traceable to es6-promise?

**Comment by lynamemi** [comment]
Also referenced in: #3070

**Comment by lynamemi** [comment]
Resolved: https://github.com/OfficeDev/office-ui-fabric-react/pull/3090

**Comment by LeopoldLerch** [comment]
However, still not working

**Comment by lynamemi** [comment]
@LeopoldLerch the master branch in the repo has the fix, but it won't make it onto the website until we next deploy. Hopefully by next week.
