### ISSUE TITLE
ComboBox sends bad onChanged after backspacing all characters

### ISSUE THREAD

**Issue by IanVS** [OfficeDev/office-ui-fabric-react#3055]
### Bug Report

- __Package version(s)__: 5.5.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No, probably not (sorry)

Requested priority: Normal

Products/sites affected: Nutshell CRM Outlook add-on

#### Describe the issue:

I am using an uncontrolled ComboBox on a form, `allowFreeform` set to `true`.  I have found that when I backspace out all of the characters one at a time and then press enter, the `value` argument that is provided to `onChanged` is the last letter that was backspaced (the first letter of the original contents).  See Provided codepen for a demonstration.

#### Actual behavior:

`onChanged` is called with a single character in the `value` argument.

#### Expected behavior:

`onChanged` is called with an empty string.

### If applicable, please provide a codepen repro:

https://codepen.io/IanVS/pen/wryoby

**Comment by dzearing** [comment]
@jspurlin

**Comment by fidabhittani** [comment]
Any update on this issues ... Any work arounds?

**Comment by michaelangotti** [comment]
@jspurlin Is this still on your radar?

**Comment by sebraddo** [comment]
Also running into this issue, has anyone found a workaround for clearing combobox input?

**Comment by aslanovsergey** [comment]
Same here. Please increase priority some of my core features relies on this component

**Comment by kenotron** [comment]
I thought I could do a quick fix on this, but the fix is VERY involved based on how this was actually coded.

**Comment by jspurlin** [comment]
FYI, I've got a local fix for this. Need to finish testing and then will have a PR sent out
