### ISSUE TITLE
ComboBox newly created freeform item is cleared with escape key

### ISSUE THREAD

**Issue by IanVS** [OfficeDev/office-ui-fabric-react#3061]
### Bug Report

- __Package version(s)__: 5.5.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Perhaps, if pointed in the right direction.

Requested priority: Normal

#### Describe the issue:

I am having some difficulties with freeform-entered options in uncontrolled ComboBoxes.  Specifically, after creating an option by typing it in and pressing enter, if I open the dropdown and press the escape key to close the dropdown/blur, the selection disappears.  I've made a codepen to illustrate the issue.

#### Actual behavior:

Freeform-entered options can be cleared, leaving a blank field.  `onChanged` does not fire, but the field remains blank.

#### Expected behavior:

Pressing escape would not clear out the selection, and would behave just as it does when choosing an option from the dropdown, opening the dropdown, and pressing escape.

### If applicable, please provide a codepen repro:

https://codepen.io/IanVS/pen/YrexLg?editors=0011

**Comment by michaelangotti** [comment]
@jspurlin Is this one on your radar or should we close it?

**Comment by JasonGore** [comment]
With this same CodePen I'm also seeing this issue where showing the dropdown and just clicking elsewhere on the page adds a phantom option. There may be a race condition or improperly call callbacks calling this issue.

![combobox2](https://user-images.githubusercontent.com/26070760/44118600-8e7f5272-9fcb-11e8-8fc2-1756b5aa1ab7.gif)
