### ISSUE TITLE
Combobox aria-activedescendant should update as you arrow up/down the list, not after you commit the change

### ISSUE THREAD

**Issue by philipzloh** [OfficeDev/office-ui-fabric-react#3063]
### Bug Report

- __Package version(s)__:  5.50

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority:  Normal

Products/sites affected: Anyone using Combobox for accessibility

#### Describe the issue:

Open Combobox, arrow key up/down. It is easier to see the problem when you use Narrator on Edge.

#### Actual behavior:

The blue bounding box of Narrator stays in the text input box and doesn't follow the dropdown's arrow keys. Also, Narrator does not read the 'selected' item.

#### Expected behavior:

Narrator's blue box should follow the arrow keys, and Narrator should naturally read the 'selected' item.

### If applicable, please provide a codepen repro:

Just use the Fabric example site.

**Comment by philipzloh** [comment]
My proposed fix changes

     aria-activedescendant={ (isOpen && (selectedIndex as number) >= 0 ? (id + '-list' + selectedIndex) : null) }

into

    aria-activedescendant={
              isOpen &&
              (this.state.currentPendingValueValidIndex as number) >= 0
                ? id + "-list" + this.state.currentPendingValueValidIndex
                : null
            }

**Comment by amyngu** [comment]
@jspurlin if you don't have bandwidth to fix this, I can go ahead and take it. 

@dzearing for FYI

**Comment by jspurlin** [comment]
@amyngu , yes feel free to make the fix for this

**Comment by jspurlin** [comment]
This was fixed by PR: https://github.com/OfficeDev/office-ui-fabric-react/pull/3738
