### ISSUE TITLE
Suggestion: Documentation request for break-point debugging & publishing production code

### ISSUE THREAD

**Issue by limefrogyank** [OfficeDev/office-ui-fabric-react#3066]
First, most of the documentation is **excellent**.  I am a complete noob when it comes to anything about node.js and React.  I've worked with TypeScript before and incorporated it into Web Apps created using the templates from VS Studio, so I knew the programming part... I just knew nothing about anything else.  I was able to take the Yeoman office generator and start learning how to do React stuff in VS Code.  Even the JSX/TSX was brand new to me.  I have a fully-functioning Office Add-in and it only took a couple hours a day for a week or so.  

Where I ran into problems was debugging with break points and actually publishing the finished code for a client-side rendered app.  I never figured out break-point debugging (used a LOT of `console.log`) but I managed to figure out how to modify the webpack config files to build an appropriate version.

I realize this is not exactly under your purview as you only supply the components for React.  However, given all of the other excellent instructions here and on the main office dev website, it would be nice to have better ones for the points that I brought up.  Thanks again!

**Comment by dzearing** [comment]
There are a ton of tutorials on the web for debugging web pages and JavaScript. Hope these help:

I highly recommend this for starting a sample app!
[TypeScript React starter pack using create-react-app](https://github.com/Microsoft/TypeScript-React-Starter)

Once you have set up a project using that, add `office-ui-fabric-react` by running `yarn add office-ui-fabric-react`. This will install the library and give you intelisense in VSCode.

Running `npm start` will run the code in the web browser, and modifications to the code will update the scripts loaded by the web page and automatically refresh it.

You can use the built in browser tools to debug; most browsers have a debugger built in. Edge does, Firefox, Safari, and Chrome all do. I personally use Chrome!

Here's a helpful article for learning some basics of Chrome debugging:

[Debugging React with Chrome](https://medium.com/@DcKesler/debugging-react-with-chrome-871f59229f62)

**Comment by dzearing** [comment]
I'm closing as this isn't really a library issue. If you however run into any problems using the library don't hesitate to reopen an issue.
