### ISSUE TITLE
Testing docs are outdated

### ISSUE THREAD

**Issue by IanVS** [OfficeDev/office-ui-fabric-react#3071]
### Bug Report

- __Package version(s)__: master

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Low

#### Describe the issue:

The testing docs at https://github.com/OfficeDev/office-ui-fabric-react/blob/6373316a067e101fb196e3fc4364d45d08f7e62e/ghdocs/TESTING.md (which is linked from the README) seem to be outdated, since they mention Mocha and Chai, but https://github.com/OfficeDev/office-ui-fabric-react/pull/3005 updated the codebase to use Jest.

#### Actual behavior:

Docs are outdated and mention Mocha & Chai.

#### Expected behavior:

Jest should be mentioned in the docs, and the examples should use jest expect syntax.  Enzyme could also be mentioned and linked to, since it seems to be used as well.

### If applicable, please provide a codepen repro:

N/A

**Comment by dzearing** [comment]
@IanVS Thanks for calling out. I've updated them. Feel free to submit PRs if you'd like to add content!

**Comment by IanVS** [comment]
Looks great, thanks!
