### ISSUE TITLE
Place holder for NormalPeoplePicker

### ISSUE THREAD

**Issue by nguyentoantuit** [OfficeDev/office-ui-fabric-react#3076]
Hi all,

Could you please show me how can I add place holder for NormalPeoplePicker?

Thanks,
Toan

**Comment by dzearing** [comment]
@joschect Maybe you could help here?

**Comment by joschect** [comment]
@nguyentoantuit What do you mean by placeholder? Do you mean placeholder text like: 
![image](https://user-images.githubusercontent.com/20801176/31521099-1c032796-af5d-11e7-8df7-2fe87d43cc17.png)

If that's what you want then you can pass in the placeholder you want to the inputProps property.

**Comment by nguyentoantuit** [comment]
@joschect Yes, exactly. We have this option in TextField, but in people picker (NormalPeoplePicker), I don't see that property.

**Comment by erichdev** [comment]
@nguyentoantuit PeoplePicker has prop `inputProps` that takes an object of input properties, so to apply a placeholder, it'd be

```tsx
<NormalPeoplePicker
    items={items}
    inputProps={
        { placeholder: 'Placeholder text' }
    }
/>
```

Closing issue, please reply if you still have questions about the placeholder
