### ISSUE TITLE
Dropdown does not jump to option on keyboard input

### ISSUE THREAD

**Issue by IanVS** [OfficeDev/office-ui-fabric-react#3077]
### Bug Report

- __Package version(s)__: 5.5.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes, if pointed in the right direction

Requested priority: High

#### Describe the issue:

Normal select boxes on the web will jump to a row when the user types with the keyboard while the select box is open.  (Think of every "State" field on every address form you've ever filled out).  Dropdown does not have this behavior.

https://github.com/OfficeDev/office-ui-fabric-react/issues/1979 is a _similar_ issue, although it sounded like that user wanted the suggestions to filter.  That's not standard select element functionality, so in that case ComboBox probably is a better choice.

The fact that ComboBox has a similar functionality and might be able to be made to behave the way I'm asking does not mean that Dropdown shouldn't behave as a standard select box out-of-the-box.  

#### Actual behavior:

Typing on the keyboard while a Dropdown is open has no effect.

#### Expected behavior:

As the user types, the selection should change to the "closest" possible option (alphabetically).  After they stop typing for a short time, then additional keyboard inputs should be treated as a new string.  For example, in a list of states, typing "ut" would select "Utah", then after a short pause (unsure of the exact time), typing "oh" would select "Ohio".

### If applicable, please provide a codepen repro:

The current behavior can be seen on the Fabric website examples.

**Comment by dzearing** [comment]
Dropdown is simply missing this feature! If you'd like to take a stab at making it work, it would be very welcome. The ComboBox and Dropdown are very similar and really I do wish they would share more code.

**Comment by fidabhittani** [comment]
Is there any update on this issue?

**Comment by IanVS** [comment]
I haven't had a chance to work on it so far, and honestly I don't foresee having too much time in the next month or so, unfortunately.

**Comment by fidabhittani** [comment]
I have cloned the code. And may may try to do this. If you have suggestion on how we are gonna do t. I was thinking of Taking the isOpen through props. Because now when i see it its in State. By taking it through props will allow the User to manage it through onBlur onfocus or how they like... what do u say..

**Comment by fidabhittani** [comment]
Anything yet?

**Comment by micahgodbolt** [comment]
you can use combobox for this funcationality

**Comment by vipinshr** [comment]
anything yet for the dropdown?

**Comment by micahgodbolt** [comment]
this is available with combobox. We're considering adding this to dropdown in the future (merging the two controls) but not currently planned for.

**Comment by jgage176** [comment]
Why did this get closed? This is an obvious missing feature that lacks parity with the corresponding native dropdown elements.

**Comment by micahgodbolt** [comment]
This is a combo box feature. Our goal is to eventually merge combobox and dropdown as they have WAY too much overlapping functionality.
