### ISSUE TITLE
Spinner is not rotating in IE 11

### ISSUE THREAD

**Issue by hbsts** [OfficeDev/office-ui-fabric-react#3088]
### Bug Report

- __Package version(s)__: office-ui-fabric-react@5.3.0
- __Browser and OS versions__: IE 11

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: (if applicable)

#### Describe the issue:

Spinner is rotating in Chrome, but not in IE 11. In IE 11 there is just a static image of the spinner.

#### Actual behavior:

Spinner is rotating in Chrome, but not in IE 11. 

#### Expected behavior:

Spinner is rotating in IE 11. 

### If applicable, please provide a codepen repro:
No codepen existing. I am sorry.

**Comment by dzearing** [comment]
Using the latest oufr Spinner, I am seeing it spin. Here's a codepen.

https://codepen.io/dzearing/pen/EwpYob

**Comment by dzearing** [comment]
Note: Please reopen if this doesn't work for you! maybe you can provide more details and a repro.

**Comment by hbsts** [comment]
@dzearing 
Hi David,
thanks a lot for the codepen. Spinner is rotating in my IE 11, too. I created a simple VS Code react project and it worked there, too.

I forgot to mention (sorry for this), that the issue relates to an SPFx WebPart. I investigated a bit more. When switching the mode from IE 10 to IE 11 in IE Dev tools, it works in SPFx, too. It seems, that SPFx Workbench needs IE 11 mode to make the spinner spinning. 

Anyway, the issue seems to be SPFx related. Thanks again for your help.

**Comment by lafe** [comment]
We have the same issue in IE11 as well. Unfortunately, the page is hosted in SharePoint 2013 (long story...) and SharePoint enforces "Document Mode" 10 - if I manually set the Document Mode to "Edge", it works. However, as SharePoint needs "Document Mode" 10, this is not a feasible work around.
