### ISSUE TITLE
ErrorMessage in datepicker

### ISSUE THREAD

**Issue by enriquin** [OfficeDev/office-ui-fabric-react#3089]
Hi all,

I think the datepicker control should have an "errorMessage" property, just like all the other data-entry controls. Is there any way to show an error message when (for example) the value is not valid?

Also, when you set the isRequired property, an error message with no text and an icon is shown:

![image](https://user-images.githubusercontent.com/30507975/31448364-89ef6f6c-aea4-11e7-998c-3168d0d00313.png)

Thanks!

**Comment by erichdev** [comment]
DatePicker has prop `strings` which takes `IDatePickerStrings`. One of the properties of `IDatePickerStrings` is `invalidInputErrorMessage`, which allows you to pass a custom error message. e.g. 
```tsx
<DatePicker  strings={{invalidInputErrorMessage:'Invalid date'}}/>
```

The icon was the standard prefix for the error message, and the * is the default error message if no custom error is passed in. Note that in Fabric 5.0, the icon is removed.
