### ISSUE TITLE
publish current docs somewhere

### ISSUE THREAD

**Issue by luisrudge** [OfficeDev/office-ui-fabric-react#310]
it'd be nice to have this published to gh-pages or something like that.

BTW, this is awesome! Thanks! ❤️

**Comment by ericthompson** [comment]
An all-new [Fabric site](http://dev.office.com/fabric) is coming very, very soon which will have tons of great info 😄 

Glad to hear the project is helpful - please file issues/contribute as you work with it!

**Comment by dzearing** [comment]
@luisrudge 

Check out http://dev.office.com/fabric

Looks like it's live. :)

**Comment by luisrudge** [comment]
Holy crap. That's awesome!
