### ISSUE TITLE
Slider: should round value

### ISSUE THREAD

**Issue by ambar** [OfficeDev/office-ui-fabric-react#3112]
### Bug Report

- __Package version(s)__: latest(5.3.0)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) 

Products/sites affected: (if applicable)

#### Actual behavior:

![image](https://user-images.githubusercontent.com/105919/31531788-ca2f82be-afae-11e7-809a-0b8a9f21d75a.png)

#### Expected behavior:

`1.7`

### If applicable, please provide a codepen repro:

```js
<Slider
  min={1}
  max={3}
  step={0.1}
/>
```

**Comment by dzearing** [comment]
Yuck! gross bug.

**Comment by dzearing** [comment]
@erichdev can you make a quick pr for this?

**Comment by dzearing** [comment]
I've noticed also that the label width is just not adequate. If you have max={10000}, it can't render that, even without the rounding issue.
