### ISSUE TITLE
Feature Request: Don't close Callout when clicking outside

### ISSUE THREAD

**Issue by timura1992** [OfficeDev/office-ui-fabric-react#3113]
Can you add a property to Callout which prevents closing it by clicking outside? (similar to the preventDismissOnScroll property) This would prevent to close the Callout unintentionally. 

A close button like this: 

![image](https://user-images.githubusercontent.com/25741401/31547718-a43a797c-b028-11e7-8c8c-75c3d07320fd.png)

could still trigger isBeakVisible

Priorities and help requested (not applicable if asking question):
Are you willing to submit a PR to fix? Yes!
Requested priority: Normal

**Comment by dzearing** [comment]
I believe by default it does not dismiss when you click outside. You have to implement it. How are you using it? Can you provide a codepen?

Here's one to fork.
https://codepen.io/dzearing/pen/bojpgX

**Comment by timura1992** [comment]
Thank you! you're right
