### ISSUE TITLE
Allow clicking commandbar context menu item without dismissing the menu

### ISSUE THREAD

**Issue by avnikp** [OfficeDev/office-ui-fabric-react#3140]
### Bug Report

- __Package version(s)__: 5.0.1
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) 
High

Products/sites affected: (if applicable)
Owa mail command bar Move to menu

#### Describe the issue:

Overriding onDismiss for a context menu item of command bar should allow an option to not dismiss the menu. Right now it calls onDismiss callback but still dismisses the menu by calling setState.
We have a requirement to add menu items in owa mail command bar's Move to menu for -
1) New Folder - Clicking this will replace the menu item with a text box where user can enter new folder name. On enter it should dismiss the menu.
2) More Folders - Clicking on this menu item should not dismiss the Move to menu. It will replace the folder list with full folder list in the same menu (not open a submenu).

    CommandBar.prototype._onContextMenuDismiss = function (ev) {
        if (!ev || !ev.relatedTarget || !this.refs.commandSurface.contains(ev.relatedTarget)) {
            var contextualMenuProps = this.state.contextualMenuProps;
            if (contextualMenuProps && contextualMenuProps.onDismiss) {
                this.state.contextualMenuProps.onDismiss(ev);
            }
            this.setState({
                expandedMenuItemKey: undefined,
                contextualMenuProps: undefined,
                contextualMenuTarget: undefined
            });
        }
        else {
            ev.stopPropagation();
            ev.preventDefault();
        }
    };

#### Actual behavior:

Clicking on an item always dismisses the context menu

#### Expected behavior:

Do not dismiss the menu onDismiss callback

**Comment by micahgodbolt** [comment]
Sorry, should have kept this open.
