### ISSUE TITLE
Strange GallatinLogo icon

### ISSUE THREAD

**Issue by compulim** [OfficeDev/office-ui-fabric-react#3145]
### Bug Report

- __Package version(s)__: fabricmdl2icons-2.47.woff2
- __Browser and OS versions__: Edge 16 and Chrome 61

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: https://developer.microsoft.com/en-us/fabric#/styles/icons

#### Describe the issue:

When browsing thru https://developer.microsoft.com/en-us/fabric#/styles/icons, a very wide rectangular brand icon appear.

#### Actual behavior:

A very wide rectangular brand icon appear on https://developer.microsoft.com/en-us/fabric#/styles/icons.

#### Expected behavior:

An icon that is a square and brand-neutral (except Microsoft).

### If applicable, please provide a codepen repro:

![image](https://user-images.githubusercontent.com/1622400/31698519-c53a6536-b372-11e7-883d-b157ffac75db.png)

**Comment by dzearing** [comment]
Weirdness! What is this? @mikewheaton @Jahnp

**Comment by Jahnp** [comment]
That icon has been in the font in that form for a long time and was likely on request from a product team. We can follow up to clarify its usage but I wouldn't classify it as a bug.
