### ISSUE TITLE
[Fabric Website] Clicking any links in component header doesn't link properly

### ISSUE THREAD

**Issue by martellaj** [OfficeDev/office-ui-fabric-react#3150]
Screenshot in case my title doesn't make sense:
![image](https://user-images.githubusercontent.com/1019478/31743859-886bb1e2-b411-11e7-9e1c-2816ed82bfcc.png)

It's true for each of those menu items.

Original link: https://developer.microsoft.com/en-us/fabric#/components/contextualmenu
Link after clicking "Variants": https://developer.microsoft.com/en-us/fabric#Variants

**Comment by lynamemi** [comment]
Just got this PR through! Will deploy the new changes soon :)
https://github.com/OfficeDev/office-ui-fabric-react/pull/3139
