### ISSUE TITLE
SPFx

### ISSUE THREAD

**Issue by akburns72** [OfficeDev/office-ui-fabric-react#3151]
### Bug Report

- __Package version(s)__: Using the yo generator sharepoint React
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)Yes

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)All

#### Describe the issue:

I am building a SPFx webpart, React scaffolding with Yeoman.   If I do a simple call out example with a React component, it works just fine.

If I try to incorporate the Dialog component, I get an error around the autobind reference that is in the Office React UI Utilities.
import { autobind } from '../../../Utilities';   It tells me it cannot find the module.

How do I make the correct reference to this file in order to use @autobind in a SPFx React webpart?

#### Actual behavior:

Cannot find the Utilities reference, therefore cannot bind the example controls to open a dialog box

**Comment by joelfmrodrigues** [comment]
Hi @akburns72 ,

I assume you have copied that import statement from the Office UI Fabric website samples as the import is looking for a module local to the project?
You have to import it from the external office-ui-fabric-react module installed in the project
import { autobind } from 'office-ui-fabric-react/lib/Utilities';

**Comment by michaelangotti** [comment]
Sounds like the above will have solved this issue. Closing.
