### ISSUE TITLE
How to change the base color?

### ISSUE THREAD

**Issue by fidabhittani** [OfficeDev/office-ui-fabric-react#3164]
I am new to the Fabric-ui. I very much like it, Now as we see the basic colors in UI is standard `white` and `Blue`. Is there any chance if I may change the `base-color` which may affect all the ui by using the derivatives of the base color?
like lets say If use base-color: red.

**Comment by vertonghenb** [comment]
It's quite straightforward actually, you can just override the base-colors. 
More information can be found in the following link: https://developer.microsoft.com/en-us/fabric#/components/themes

**Comment by fidabhittani** [comment]
Thanks, Silly me, How can I miss that. :)
