### ISSUE TITLE
Details List Selection Object question

### ISSUE THREAD

**Issue by russgove** [OfficeDev/office-ui-fabric-react#3178]
Hi, 
How Do I set the initially selected items in a details list.  I see there is a ISelection object that has a bunch of methods on it to do things with the selections , but I am unsure how to use it in an react spfx webpart. The docs say that i can pass thh Selection object to the details list. Do I have to create that class, with all those members . Or do I somehow get the slection object from my details list.
TIA
Russell

**Comment by russgove** [comment]
I found my answer in someone else;s issue. 
Import Selection from Fabric
Create a new selection object
Pass the selection object into the detailslist.


I could not find that documented anywhere!
We should open source the docs for fabric, like we did for spfx

**Comment by russgove** [comment]
OK, I see how I can set an item to be selected, but where would I do that, From my main window. I am opening a panel which shows the detailslist. (user clicks a button that sets showpanel to true. This causes the panel to render with the details list. Where would I put code to set selected items? I'm guessing OnRowWillMount might be suitable. Is there somewhere more appropriate?

**Comment by screenpunch** [comment]
I have a very similar question.

I have a button that calls setKeySelected on the Selection object, clicking it correctly updates the selected item in the DetailsList.

When I first show the DetailsList, I want to have some items selected by default, calling setKeySelected in componentDidMount does nothing.

**Comment by bva999** [comment]
I do it in render method, before return DetailsList. And it works for me. 
`public render(): React.ReactElement < IExpertsListProps > {
    if (this.state.items.length > 0) {
        this._setSelectedItems();
      }
    return(
      <div>
        <DetailsList
          items={this.state.items}
          setKey="items"
          columns={this.state.columns}
          layoutMode={DetailsListLayoutMode.justified}
          onRenderMissingItem={(index) => this._onDataMiss}
          selection={this._selection}
          onItemInvoked={this._onItemInvoked}
          onColumnHeaderClick={this._onColumnClick}/>
      </div>
    );
  }

  private _setSelectedItems(): void {
    let selectedItems: any = pnp.storage.session.get("selectedExperts");
    if (selectedItems) {
      this._selection.setChangeEvents(false, true);
      this._selection.setItems(this.state.items);
      selectedItems.forEach(selectedItem => {
          this._selection.setKeySelected(selectedItem.Id, true, false);
        });
      this._selection.setChangeEvents(true, true);
    }
  }`

**Comment by michaelangotti** [comment]
It looks like this has been answered. Closing.
