### ISSUE TITLE
CommandBar replacing menu, option to open groups on hover?

### ISSUE THREAD

**Issue by clechner77** [OfficeDev/office-ui-fabric-react#3189]
For a horizontal menu, it looks like the choice is clearly the CommandBar, which is really one of the go to fabric compotents.  That said, am I simply overlooking a convenient way to open submenus/grouped buttons/commands on hover?

**Comment by vertonghenb** [comment]
If i'm not mistaken the commandbar is under "maintenance" since it was recently added to the package. You can find more on-going/done issues in the project: https://github.com/OfficeDev/office-ui-fabric-react/projects/6

**Comment by aditima** [comment]
The CommandBar does support showing submenus with commands. Please refer to this example: https://developer.microsoft.com/en-us/fabric#/components/commandbar 

The submenu shows up on click instead of on hover.

**Comment by ja3bhende** [comment]
I am looking for sub-menus showing on mouse hover instead of click. It does show 3rd level menus on mouse hover, but we have to click header menu for viewing 2nd level menu. This is so inconsistent. Please help

**Comment by betrue-final-final** [comment]
It appears that this is a no repro for contextual menu on the Fabric site. It does show all submenus on hover, but it is SLOW. Sounds like a perf issue.
