### ISSUE TITLE
Persona detail region UI is not good under Safari

### ISSUE THREAD

**Issue by MirandaGe** [OfficeDev/office-ui-fabric-react#3191]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: Safari

#### Priorities and help requested (not applicable if asking question):

Requested priority: Normal

#### Describe the issue:

Open demo page with Safari: https://developer.microsoft.com/en-us/fabric#/components/persona,

check the persona size with extra large and customize coin size, the detailed region is covered by persona image.

If I add style `flex: 0 0 auto` to `ms-personaCoin` CSS class, the card UI recovers.

**Comment by michaelangotti** [comment]
Is this Windows Safari or Mac?

**Comment by betrue-final-final** [comment]
Mac. Safari does not exist for Windows.

**Comment by betrue-final-final** [comment]
Wow, I guess there used to be.

**Comment by michaelangotti** [comment]
@MirandaGe Is this still an issue?
