### ISSUE TITLE
TooltipHost to be shown based on parent component provided conditions

### ISSUE THREAD

**Issue by aakash-johari** [OfficeDev/office-ui-fabric-react#3193]
There are two modes that are provided today with TooltipHost to show it conditionally based on whether the parent or the tooltip itself has overflow. I'd like to have a more flexible control to the consumer. Probably a boolean to control the visibility of the tooltip.

**Comment by erichdev** [comment]
TooltipHost wraps Tooltip with the logic to control the visibility of Tooltip. If you'd like more flexibility with the visibility conditions, you can render Tooltip directly and write your own conditions for visibility. Would that work for you?

**Comment by erichdev** [comment]
Closing due to no response. Please reopen if any issues remain.
