### ISSUE TITLE
How to reference colors of SASS variables output of the Theme Generator

### ISSUE THREAD

**Issue by ramonitor** [OfficeDev/office-ui-fabric-react#3201]
How can you reference the colors in the SASS variables the Theme Generator generates? Is this some kind of new(er) list syntax? 

The output in the current beta version of the Theme Generator looks like this;

> $themePrimaryColor: "[theme: themePrimary, default: #0078d7]";
$themeLighterAltColor: "[theme: themeLighterAlt, default: #eff6fc]";
$themeLighterColor: "[theme: themeLighter, default: #deecf9]";
$themeLightColor: "[theme: themeLight, default: #c7e0f4]";
$themeTertiaryColor: "[theme: themeTertiary, default: #71afe5]";
<snip>

**Comment by phkuo** [comment]
@ramonitor  what's your scenario? office-ui-fabric-react already provides these SASS variables in https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/common/_themeOverrides.scss
