### ISSUE TITLE
Nav: The `forceAnchor` property in `INavLink` stopped working.

### ISSUE THREAD

**Issue by warmsea** [OfficeDev/office-ui-fabric-react#3210]
### Bug Report

- __Package version(s)__: 5.9.2

#### Describe the issue:

The `forceAnchor` property in `INavLink` stopped working. The link renders the same no matter `forceAnchor` is set to `true` or `false`.

```
  /**
   * (Optional) By default, any link with onClick defined will render as a button.
   * Set this property to true to override that behavior. (Links without onClick defined
   * will render as anchors by default.)
   */
  forceAnchor?: boolean;
```

When a link is rendered as an anchor, the color of the text is black. When rendered as a button, it becomes blue. We need `forceAnchor` to work because sometimes we add `onClick` only for telemetry purpose. We don't want to change the style and the fact that it is still a link.

**Comment by cicciodm** [comment]
I will take this.
This is caused by my change to the `Nav` component, and an interesting edge case.

**Comment by warmsea** [comment]
Thanks @cicciodm !
