### ISSUE TITLE
Icons are not displayed in user controls

### ISSUE THREAD

**Issue by viliuscicenas** [OfficeDev/office-ui-fabric-react#3211]
After I upgraded from '2.34.2' version to '5.9.0' (tried '5.12.0' and '5.13.0' too) nonce of components displays icons (at least in select and date picker controls).

**Comment by lynamemi** [comment]
As of Fabric 5.0, we have a new api for the icons package. Checkout [this documentation](https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/icons). You will need to use itinializeIcons() in your app. Please reopen if you still have issues.
