### ISSUE TITLE
[Question] Icon subset tool?

### ISSUE THREAD

**Issue by IanVS** [OfficeDev/office-ui-fabric-react#3218]
I saw in the [PR for 5.0.0](https://github.com/OfficeDev/office-ui-fabric-react/pull/2943) a mention of an Icon subset tool, which allows the creation of an inline icon bundle:

>Custom icons! Use the icon subset tool to choose the exact set of icons to register and build your own icon registration code. You can even choose to use inlined icons and include them with your JavaScript bundle.

This would be awesome for my own use case, but I can't seem to find any instructions on where to find it or how to use it.  Is it available somewhere?

**Comment by lynamemi** [comment]
Not sure whether it's ready for public consumption yet. I can check with @Jahnp when he's back from vacation in a couple of weeks.

**Comment by Jahnp** [comment]
Hey @IanVS, we do indeed have a tool for this, but it's not yet ready for external usage. We don't have a specific timeline just yet, but I'd like to have it out by January. There are legal and costing considerations I need to figure out and lock down and it's hard to say how long it'll take for those. Like @lynamemi says, I'll be back from vacation the first week of November and will be assessing this as one of the top projects when I return. I'll leave this open for now until we have more conclusive details.

**Comment by michaelangotti** [comment]
@Jahnp Are we planning on doing work or can we close this issue?

**Comment by Jahnp** [comment]
Yes, we should definitely keep this open. We're actively doing work on this now and plan to have something to share at or before SPCNA in May.

**Comment by lynamemi** [comment]
I'm pretty sure has been released! @Jahnp what's the official external link?

**Comment by Jahnp** [comment]
I was just going to respond myself! This has indeed been released, and can be access at https://aka.ms/uifabric-icons (resolves to https://uifabricicons.azurewebsites.net).

**Comment by Jahnp** [comment]
Since this tool has been released, I'm going to go ahead and close this.

**Comment by IanVS** [comment]
This is great news!  Thanks for sharing.

**Comment by matthewrobertson** [comment]
It seems like icon subset tool is not currently available. Is that intentional or is it a bug? Assuming it is a bug should we update the external documentation to link to it? For example a link here would be helpful: https://github.com/OfficeDev/office-ui-fabric-react/wiki/Fabric5#notes-on-icons

**Comment by Jahnp** [comment]
Hey @matthewrobertson , the tool is available here: https://uifabricicons.azurewebsites.net/

But you're right, its usage isn't documented on the wiki or anywhere else. This is known and captured here: https://github.com/OfficeDev/office-ui-fabric-react/issues/5469

**Comment by matthewrobertson** [comment]
@Jahnp thanks for the quick reply! I got a 500 the first time I tried to load that URL. Seems to be working now though.

**Comment by Jahnp** [comment]
I pushed an update recently which may have caused a brief interruption when loading the page again. Good to know it works now! Also, I've added a few links to the tool throughout the section of the wiki you shared. There are still more places it needs to be documented, but that should be a good start.
