### ISSUE TITLE
How can I open reactjs project  in Visual Studio 2017 Professional

### ISSUE THREAD

**Issue by hengchengfei** [OfficeDev/office-ui-fabric-react#3223]
I created project by  the command of 'create-react-app' and 'yo office'(https://dev.office.com/docs/add-ins/excel/excel-add-ins-get-started-react)

I want to develop it by Visual Studio 2017 Professional,How can I do it?

Thank you.

**Comment by erichdev** [comment]
If you're using Fabric, please see the [documentation on how to get started](https://developer.microsoft.com/en-us/fabric#/get-started). Feel free to open a new issue if you have specific questions about Fabric components. 

If you have questions about developing Excel addins, those questions would be better suited for [Stackoverflow](https://stackoverflow.com/questions/tagged/office-js).
