### ISSUE TITLE
Getting following accessibility issue on dropdown

### ISSUE THREAD

**Issue by mdmdakbar** [OfficeDev/office-ui-fabric-react#3224]
Getting below error when testing it with "Keros for Web" tool

Error: Certain ARIA roles must contain particular children - 

![image](https://user-images.githubusercontent.com/19491487/31997357-57bfef52-b9a9-11e7-8608-0ee7f8cf799e.png)

**Comment by KevinTCoughlin** [comment]
@mdmdakbar I think this has been fixed by https://github.com/OfficeDev/office-ui-fabric-react/issues/3319.

As far as I can tell, now the structure is:

```html
<div role="combobox" aria-owns="Basicdrop1-list" />
...
<div id="Basicdrop1-list" role="listbox" />
  <button role="option" />
```

Which conforms to https://www.w3.org/TR/wai-aria-1.1/#combobox. I believe this issue can be closed.
