### ISSUE TITLE
Close X is in the wrong place on Panel

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#3227]
Are you willing to submit a PR to fix? (No)

Requested priority: (High) 

Reproes in Edge and IE11, but not Chrome.

Products/sites affected: OneDrive, SharePoint, and anything that uses a panel

The close X is on the left, and should be on the right

![image](https://user-images.githubusercontent.com/20363037/32011251-17221802-b969-11e7-9273-71d1134950d9.png)

This isn't even close to spec.
![image](https://user-images.githubusercontent.com/20363037/32011294-3cd37d16-b969-11e7-9780-a40ba2192c1b.png)

**Comment by micahgodbolt** [comment]
ok. it's a load order issue. buttons are position relative (not sure why) which sometimes overrides the position absolute used in the panel
