### ISSUE TITLE
[question] How to deep link to react single page app

### ISSUE THREAD

**Issue by cwoess** [OfficeDev/office-ui-fabric-react#3235]
I have a Sharepoint single page app in react with routing that sends out emails to users. On receiving an email the user needs to be able to click a link and be redirected back to a deep link within the app. Something like .../sharepoint.com/sites/myApp/SitePages/Hjemmeside.aspx#/app/4 
How can I accomplish this? The login page only redirects to the apps main page.
thanks for any help

**Comment by cobbs-totem** [comment]
Are you using react-router?

**Comment by cwoess** [comment]
Hi,

Yes we’re using react-router, redux and redux-thunk middleware

Cheers,

Chris

Sent from my iPhone

On 26 Oct 2017, at 21:41, cobbs-totem <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you using react-router?

**Comment by cobbs-totem** [comment]
I think part of my mis-understanding is that you're using Sharepoint (which I don't know anything about), where-as I'm using my own standalone app.  I can simply create a <Route> to link a props.match.url to an individual React component inside my app.

**Comment by cwoess** [comment]
Sharepoint lofin intercepts tje request and then the deep link part is lost

Sent from my iPhone

On 27 Oct 2017, at 17:10, cobbs-totem <notifications@github.com<mailto:notifications@github.com>> wrote:


I think part of my mis-understanding is that you're using Sharepoint (which I don't know anything about), where-as I'm using my own standalone app. I can simply create a to link a props.match.url to an individual React component inside my app.

**Comment by erichdev** [comment]
Redirecting on Sharepoint login is outside the scope of Fabric. This would be a better question for [StackOverflow](https://stackoverflow.com/questions/tagged/sharepoint) or the [MSDN forums](https://social.msdn.microsoft.com/forums/office/en-us/home?category=sharepoint). Please feel free to open new issues related to Fabric components
