### ISSUE TITLE
Dropdown not displaying anything when first option is selected

### ISSUE THREAD

**Issue by mdmdakbar** [OfficeDev/office-ui-fabric-react#3236]
Products/sites affected: (if applicable) VSTS

I am using enum as the options to dropdown and selected key is one of that enum. When I select the first option whose enum value is 0, it is not getting displayed. When I investigated into this, I found that selectedKey is used in if condition and when selectedKey is 0, its taking as false value and not selecting anything.

Please refer the image below :

![image](https://user-images.githubusercontent.com/19491487/32050868-133561e2-ba70-11e7-967e-1010bd24c00b.png)

**Comment by erichdev** [comment]
What version of Fabric are you on? This was fixed by PR https://github.com/OfficeDev/office-ui-fabric-react/pull/3216, which shipped with 5.14.0

**Comment by erichdev** [comment]
Closing, please reopen if any issues remain
