### ISSUE TITLE
Styling via classnames not working

### ISSUE THREAD

**Issue by Nimelrian** [OfficeDev/office-ui-fabric-react#3237]
### Bug Report

- __Package version(s)__:
  - office-ui-fabric-react: 5.15.0
  - react: 16.0.0
  - react-dom: 16.0.0
- __Browser and OS versions__: Chrome Version 62.0.3202.62 / Windows 10 Pro Version 1703

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No, due to lack of knowledge regarding Fabric's inner workings

Requested priority: High

#### Describe the issue:

The steps I took:

1. create project using create-react-app
2. install fabric
3. change App.js to

```js
import React, { Component } from "react";
import { Fabric } from "office-ui-fabric-react/lib/Fabric";
import { DefaultButton } from "office-ui-fabric-react/lib/Button";

class App extends Component {
  render() {
    return (
      <Fabric>
        <span className="ms-font-su ms-fontColor-themePrimary">Big blue text</span>
        <DefaultButton>I am a button!</DefaultButton>
      </Fabric>
    );
  }
}

export default App;
```

#### Actual behavior:

The span has default styling.

#### Expected behavior:

The span should have the theme's primary color and a font-size of 42px according to the [official docs](https://developer.microsoft.com/en-us/fabric#/styles/typography)

**Comment by ramonitor** [comment]
@Nimelrian, did load the Fabric Core CSS? That is required to get the CSS classes in your project.

**Comment by Nimelrian** [comment]
1. That should probably be listed in the docs then
2. If I do include the CSS from the CDN, it automatically loads the webfonts, which I do not want (due to the license terms).

It would be better if
1. Fabric would come with the core CSS included in the npm package
2. would load it automatically on initialization or by importing a module (I favor the latter)
3. Would offer 2 different CSS files (and initialization modules), one which includes the webfonts and one which does not.

**Comment by ramonitor** [comment]
@Nimelrian, I could not agree more on better documentation for this project. 

The CSS requirement is listed here btw; [https://github.com/OfficeDev/office-ui-fabric-react/blob/master/ghdocs/README.md](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/ghdocs/README.md). ITs not mentioned on the Office UI Fabric public website which is kinda confusing. 

Preventing the font loading is something I looked into myself as well. It appears to be possible via:

```
window.FabricConfig = {
    fontBaseUrl: ''
};
```
I did not get it to work though.

**Comment by Nimelrian** [comment]
The FabricConfig only works with the Fabric-internal styling. So if you don't include the CSS explicitly, but set the `fontBaseUrl` it will work. Note that you have to set the config before Fabric gets initialized, not only before it's rendered. Sticking it into the HTML head-section is a good way to ensure that.

In the meantime (and by digging through the public APIs) I have found the solution. The React Fabric package creates the class names dynamically. By importing the `@uifabric/styling` package, one can use the enums contained in it to use these class names:

```js
import { ColorClassNames, FontClassNames } from "@uifabric/styling";
const HugeSpan = () => (
  <span className={`${FontClassNames.mega} ${ColorClassNames.themePrimary}`}>
    I'm huge and blue (by default)!
  </span>
);
```

But again, the docs are in desperate need of an update, I shouldn't have to look at a project's source to find out what I can use.

Closing issue since problem has been solved.
