### ISSUE TITLE
Dropdown: Selected text is black, should be neutralPrimary

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#3243]
Right now when a value is selected, the text color is #000000, when it should be neutralPrimary #333333
![image](https://user-images.githubusercontent.com/20363037/32083003-76c6c210-ba74-11e7-88c0-7351eec0c736.png)

**Comment by betrue-final-final** [comment]
Actually updated to neutralDark in PR #3270

**Comment by suztocco** [comment]
Has this been fixed and added to the master fabric code repository?

adding @melvsparks for visibility

**Comment by suztocco** [comment]
@betrue-final-final - Ben is this in the official fabric site now?
- The color still looks really dark
- Also no "hand" shows when I hover on the dropdown chevron.

**Comment by betrue-final-final** [comment]
The second issue is no repro on the live site
![image](https://user-images.githubusercontent.com/20363037/32755875-2b5c20e2-c88c-11e7-83fb-674e7c1966df.png)
 Checking the first issue

**Comment by betrue-final-final** [comment]
I'm not seeing that in the master
![image](https://user-images.githubusercontent.com/20363037/32756424-da017e60-c88e-11e7-81de-10a523113750.png)

or the live site
![image](https://user-images.githubusercontent.com/20363037/32756439-ed755a20-c88e-11e7-841e-ba6171f21c6f.png)

**Comment by suztocco** [comment]
@betrue-final-final Here is what I see compared to the XD spec

![image](https://user-images.githubusercontent.com/20954039/32796324-47db5020-c923-11e7-9fc1-8e7c60cef0f3.png)
  And mouse over the chevron, not the blank space
