### ISSUE TITLE
DatePicker/dropdown not to visual spec

### ISSUE THREAD

**Issue by suztocco** [OfficeDev/office-ui-fabric-react#3251]
### Bug Report

- __Package version(s)__: https://developer.microsoft.com/en-us/fabric#/components/datepicker
- __Browser and OS versions__: Chrome Mac

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal 

Products/sites affected: Calendar

#### Describe the issue:

What i see in the coded component is not what is in the design spec. In the design spec it looks like the text and icons change color based on state.  Also there should be a "Hand" cursor when the user mouses over the chevron icon.

![image](https://user-images.githubusercontent.com/20954039/32116628-4837ba80-bb00-11e7-9297-adfaec6b4069.png)

Design:
![image](https://user-images.githubusercontent.com/20954039/32116659-6b02ae62-bb00-11e7-90ed-d4125dfcf1f7.png)

I do not want to list every piece that is off but if you look at the design spec it should be pretty clear what the color is for the text and icon for each state.

#### Actual behavior:

Does not match spec

#### Expected behavior:

Match spec

**Comment by suztocco** [comment]
Is this fixed now and updated in the master fabric code base?

Adding @melvsparks (our dev) for visibility

**Comment by betrue-final-final** [comment]
Yes, with PR #3270
