### ISSUE TITLE
Combo box should align better to dropdown

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#3252]
Are you willing to submit a PR to fix? (Yes)

Requested priority: (Normal)

There's a number of things that are different for no reason betwixt combo box and drop down
 
	•	the chevron is huge compared to the normal dropdown
	•	the chevron turn theme on some interactive states (doesn't match other controls)
	•	no "hand" is showing on hover on the chevron to show interactivity (I notice this also happens on the normal dropdown chevrons)

Ben Truelove 
 
Ben - I do not see a spec for the combobox control but what I see in the code version does not look right.
 
	•	the chevron is huge compared to the normal dropdown
	•	the chevron turn theme on some interactive states (doesn't match other controls)
	•	no "hand" is showing on hover on the chevron to show interactivity (I notice this also happens on the normal dropdown chevrons)

Screenshot to follow

**Comment by lynamemi** [comment]
Here's some more context:
https://github.com/OfficeDev/office-ui-fabric-react/issues/3242

**Comment by kristoferbrown** [comment]
@lynamemi, did your previous PR completely fix this issue, or can you clarify which items still need adjustment?

**Comment by lynamemi** [comment]
Yes these should all be fixed. @betrue-final-final if you find any other discrepancies, feel free to open a new issue!
