### ISSUE TITLE
DatePicker menu shouldn't have scrollbar

### ISSUE THREAD

**Issue by suztocco** [OfficeDev/office-ui-fabric-react#3255]
### Bug Report

- __Package version(s)__: https://developer.microsoft.com/en-us/fabric#/components/datepicker
- __Browser and OS versions__: Chrome Mac

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Calendar OWA

#### Describe the issue:

The window showing menu options for the date picker shows a scrollbar. This looks unprofessional. It may have something to do with the second window that appears. But still to the user this isn't good.

![image](https://user-images.githubusercontent.com/20954039/32127337-f7dda704-bb2a-11e7-8f42-8af9fba153ee.png)

![image](https://user-images.githubusercontent.com/20954039/32127381-4dbcad46-bb2b-11e7-9eaf-4a5869e0ae7f.png)

#### Actual behavior:

Scrollbar shows

#### Expected behavior:

No scrollbar

**Comment by suztocco** [comment]
@taggie05 Is there any way to get an ETA on this fix if possible?
## We are shipping our Outlook Web Calendar React Beta to consumers in a few weeks and this is a main component. 


@melvsparks for visibility (our developer)

**Comment by taggie05** [comment]
@suztocco  I submitted a pull request with the issue fixed.

**Comment by suztocco** [comment]
Great! So I will be informed when the official site is updated?

**Comment by suztocco** [comment]
Can you let me know when I can see this change in Fabric or on our Calendar Beta product?

Thanks

**Comment by johannao76** [comment]
@Kelly Gorr<mailto:kegorr@microsoft.com> already fixed this in fabric, she is working today on making the corresponding change in React to consume the new version of fabric with the change.

-J
________________________________

**Comment by suztocco** [comment]
Thanks. It is hard to track because many time the fabric site is not up to date.
For instance, I do not see the update here: https://developer.microsoft.com/en-us/fabric#/components/datepicker

[cid:image001.png@01D37B15.09C0DB40]

**Comment by johannao76** [comment]
Literally this was committed yesterday and yeah, the site is a bit laggy in getting the latest.​
________________________________
