### ISSUE TITLE
DropDown List cutting of elements when no width specified

### ISSUE THREAD

**Issue by LeopoldLerch** [OfficeDev/office-ui-fabric-react#3263]
I am displaying multiple Dropdowns side-by-side using display:inline-block

however, now the dropdown-list is messed up. The DropDown itself is rendered with the width of its label. But when I click on the dropdown to view its elements, they (especially the callout) are set to a fixed with according to the dropdown itself. Everything inside it (and that is mostly all) is cut off at the boundaries. 

![image](https://user-images.githubusercontent.com/28888039/32176676-a78d6626-bd88-11e7-9ae2-9ff4e0d1a2b3.png)

Would expect to show all the options at its width. Even if the Drowdown itself doesn´t fit its width to its largest Option, it would be nice, if the Dropdownlist would expand accordingly.

**Comment by erichdev** [comment]
You can pass prop `dropdownWidth` intoDropdown to specify the width of the options. Would that work for your situation?

**Comment by Jahnp** [comment]
Hi @LeopoldLerch , @erichdev 's suggestion should fix the issue, so we're going to go ahead and close this. Please let us know if you're still seeing this issue and we can revisit.

**Comment by LeopoldLerch** [comment]
a fixed with in pixel would not solve my problem. if i set a just such a fixed with, the width will be too much in some cases (cause the values in the dropdown would be much lesser), or still too small (there might be longer values in future). Thing is, that the values in the dropdown are not to be predicted.

currently i am overwriting the dropdown (the callout that is displaying it) using css
