### ISSUE TITLE
ChevronDown icon is missing in DropDown and ComboBox components

### ISSUE THREAD

**Issue by futurfutur** [OfficeDev/office-ui-fabric-react#3265]
### Bug Report

- __Package version(s)__: 5.17.0
- __Browser and OS versions__: Chrome Version 61.0.3163.100 (Official Build) (64-bit)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High 

#### Describe the issue:

ChevronDown icon is missing in DropDown and ComboBox components
#### Actual behavior:

ChevronDown icon is missing in DropDown and ComboBox components

#### Expected behavior:

ChevronDown icon on the right side of component and on selected items

![image](https://user-images.githubusercontent.com/20656290/32186103-339d27cc-bdb2-11e7-86ad-0d5512986d81.png)
![image](https://user-images.githubusercontent.com/20656290/32186160-69df03d2-bdb2-11e7-86b3-14520b05ae70.png)

**Comment by lynamemi** [comment]
My suspicion is that you need an initializeIcon() call.  Checkout this documentation, updated with the Fabric 5.0 release: https://github.com/OfficeDev/office-ui-fabric-react/wiki/Using-icons

**Comment by futurfutur** [comment]
Wow! Icons are back. Thanks a lot for a quick responce! Shouldn't be this unobvious method call mentioned on components' pages?

**Comment by lynamemi** [comment]
Glad to hear it! Yes, a lot of folks have been running into this issue. Component page would definitely be a good place to link info. We'll be taking a look at website documentation improvements soon, this will definitely be a priority.
