### ISSUE TITLE
Details List vertical scrolling is not enabled on more rows

### ISSUE THREAD

**Issue by CaptainSadaf** [OfficeDev/office-ui-fabric-react#3267]
### Bug Report
Requested priority: (High) 
#### Describe the issue:
Fabric details does not provide vertical bar scroll feature within Grid to show more rows. it's just increase the size of Grid row instead to adjust all rows within fixed size of Details List.

https://developer.microsoft.com/en-us/fabric#/components/detailslist

**Comment by cschleiden** [comment]
I don't understand the issue, I see scrollbars just fine on that page? 

Do you host your `DetailsList` in a container with `data-is-scrollable` set to true?

**Comment by CaptainSadaf** [comment]
@cschleiden 
i'm still unable to solve the issue because when are multiple records (above 1000 rows ) then Details List does not compact to any fixed height .
this is my code for 10000 records details List

 <div>
                <div>{selectionDetails}</div>
                <MarqueeSelection selection={this._selection}>
                    <DetailsList
                        items={items}
                        columns={_columns}
                        setKey='set'
                        layoutMode={DetailsListLayoutMode.fixedColumns}
                        selection={this._selection}
                        selectionPreservedOnEmptyClick={true}
                        onItemInvoked={this._onItemInvoked}
                        compact={true}
                        data-is-scrollable={true}
                    />
                </MarqueeSelection>
</div>

![issue](https://user-images.githubusercontent.com/30376711/32343701-a914a014-bfc1-11e7-91fd-99ba2fa91453.PNG)

**Comment by CaptainSadaf** [comment]
here is code for Details List
 <div>
                <div>{selectionDetails}</div>
                <MarqueeSelection selection={this._selection}>
                    <DetailsList
                        items={items}
                        columns={_columns}
                        setKey='set'
                        layoutMode={DetailsListLayoutMode.fixedColumns}
                        selection={this._selection}
                        selectionPreservedOnEmptyClick={true}
                        onItemInvoked={this._onItemInvoked}
                        compact={true}
                        data-is-scrollable={true}
                    />
                </MarqueeSelection>
            </div>

**Comment by CaptainSadaf** [comment]
here is code
![issue2](https://user-images.githubusercontent.com/30376711/32343810-0a83744c-bfc2-11e7-82c9-aeb985052585.PNG)

**Comment by CaptainSadaf** [comment]
i just fixed the height of Details List with css
.ms-MarqueSelection{
minHeight:"500px"
}

this is not correct for all screens and Data length can be dynamic

**Comment by cschleiden** [comment]
The structure should be
```
<div data-is-scrollable={true} style={ maxHeight: "800px",  overflow: "auto" }>
    <DetailsList ... />
</div>
```

**Comment by CaptainSadaf** [comment]
this is not good way to assign static height to Grid, 
i already done in that way with style 
.ms-MarqueSelection{
maxHeight:"500px"

}

**Comment by CaptainSadaf** [comment]
it should be responsive to adjust height according screen size

**Comment by cschleiden** [comment]
`maxHeight` is obviously just an example since I don't know how your page is structured. The `div` I added should be styled to have the size you want it to have.

You don't want to style `ms-MarqueeSelection` for that.
