### ISSUE TITLE
DetailList and List should support fetching data on need basis

### ISSUE THREAD

**Issue by hesawant** [OfficeDev/office-ui-fabric-react#3272]
Currently `DatailList` and `List` both support virtualization of DOM by rendering only those rows that are immediately visible. But it requires all the list items be provided before hand.

But in case the list to be displayed has large number items, say in the range of 30K - 50K then its a problem because fetching that many items over n/w takes time. 

A possible workaround for this is to fetch items in parts and keep updating the `items` props passed but this creates a problem for accessibility. The list reads out a number that is size of `items` props at a given time and this number keeps updating till all the items are fetched, thus confusing the user.

Here is something that I am hoping to have:
1. Make `items` props optional.
2. Add another prop `count` that indicates the total number of items in list.
3. A callback function that takes the start index of item and count of items to fetch from start index.
 And expects a Promise as return value that provides requested items.
4. While the promise is still unresolved the list can show placeholder ghost rows, either default or custom provided by user.

Are you willing to submit a PR to fix? **Yes** (will need guidance)
Requested priority: **Normal**
Products/sites affected: **Yes**

**Comment by cschleiden** [comment]
We already have callbacks to render items/pages, you could just fill `items` with dummy items (e.g., `null`) and then fetch on demand. 

The list even has a `renderCount` property, wouldn't that work?

**Comment by hesawant** [comment]
`renderCount` is a property of `List`, can it be exposed in `DetailsList` because that's what we are using.
Then I can fill `null` items in the `items` array and restrict the number of `items` that are rendered.

Question: Will `DetailsList` read `items.length` (including null and non-null items) as count as part of aria description when using `renderCount`?

**Comment by hesawant** [comment]
Was looking at the code and just realized that passing `renderCount` is possible through `DetailsList`'s `listProps` property. I will give it a try.

@cschleiden thanks for the help.

**Comment by cschleiden** [comment]
No problem. Let me know if you can make it work, could be an addition for the docs
