### ISSUE TITLE
MessageBar: Doesn't match design

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#328]
At a quick glance, it looks like the padding and button colors are off.

![image](https://cloud.githubusercontent.com/assets/1382445/18810396/ae5adf4a-8249-11e6-94a1-26af0e51d4d2.png)

**Comment by dzearing** [comment]
@ericthompson this has been open for a while; could you maybe assign to someone on your team?

I don't think it would be very difficult.

**Comment by dzearing** [comment]
Or, @justinmwarner maybe you could address.

**Comment by justinmwarner** [comment]
@mikewheaton and @dzearing 

The buttons are specified by the consumer.  It's not something we specify in the MessageBar.

Also, in the redlines given, it says "Uses standard button".  I'm not sure what this means.  What is a standard button if not the default button Fabric uses?

As for padding, I'll look into this.
