### ISSUE TITLE
DetailsList : row containing Link and tabindex: click event is not fired

### ISSUE THREAD

**Issue by vashitaArora** [OfficeDev/office-ui-fabric-react#3283]
### Bug Report

- __Package version(s)__: 5.9.0
- __Browser and OS versions__: Chrome

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix?  No

Requested priority: Blocking 

Products/sites affected: (if applicable)

#### Describe the issue:

for details list with rowsize huge enough to not accomodate in viewport and containing an anchor link, on click event does not get fired when link is clicked (instead the list scrolls up trying to focus the current row)

#### Actual behavior:

on click event does not get fired when link is clicked (instead the list scrolls up trying to focus the current row)
#### Expected behavior:

onclick event should be honored 

### If applicable, please provide a codepen repro:

https://codepen.io/vashita/pen/QObeoG?editors=0110

make sure  the block 
"I am a link with an href.
1
2
3
4
5
6
7"
is not completely in the view port (only the first lines are)

try clicking(try mouse click only , keyboard works fine) on "I am a link with an href.", instead of redirecting to href, list scrolls up. second click works fine

Happening only on chrome.  
this commit seems to be the cause: https://github.com/OfficeDev/office-ui-fabric-react/commit/5a1d787d64a053d6ab882c2b6cadfa3c56b8005b

commenting out 
if (target && isElementTabbable(target)) {
     this._setActiveElement(target);
}
in FocusZone ::_onMouseDown

OR

just removing 
this._activeElement.focus(); 
from FocusZone  _setActiveElement()

 makes things fine

**Comment by cschleiden** [comment]
@pablonete Could you take a look if it was  your commit?

**Comment by pablonete** [comment]
This might be a side effect of that commit, but I won't be able to look deeper and confirm till next week (of 13th).
