### ISSUE TITLE
Contravariant parameter types with --strictFunctionTypes breaks IBaseProps

### ISSUE THREAD

**Issue by fuocor** [OfficeDev/office-ui-fabric-react#3285]
### Bug Report

- __Package version(s)__: 5.17.1

- __Browser and OS versions__: all

Are you willing to submit a PR to fix? No

Requested priority: Blocking 

#### Describe the issue:

using tsc strictFunctionTypes (2.6.1) for components deriving from BaseComponent breaks the IBaseProps constraint for componentRef if the property is not signed exactly as in IBaseProps.

so defining 
`export interface IMyProps extends React.InputHTMLAttributes<HTMLInputElement> {`
`    componentRef?: (ref: IMyComponent | null) => (void | IMyComponent );`
`...`
`}`

and defining MyComponent that extends BaseComponent and implements IMyComponent  fails compilation.

#### Actual behavior:

tsc: error TS2344: Type 'IMyProps' does not satisfy the constraint 'IBaseProps'

#### Expected behavior:

no compiler error

Given the circular relationship between IBaseProps and BaseComponent, I'm not sure how IBaseProps can be templated to pass this check

**Comment by Syntarex** [comment]
+1

**Comment by WHKFZYX-Tool** [comment]
+1

**Comment by lednhatkhanh** [comment]
Hey, any news on fixing this issue?

**Comment by Jahnp** [comment]
Sorry for the hassle here. Are you still seeing this issue with the latest package (v5.80.0 as of this writing)? TypeScript support has been updated a few times since this was opened. @manishgarg1 for FYI as we were discussing this in triage.

**Comment by dzearing** [comment]
I just tried this with the latest bits and can build a `Foo` component  just fine using `strictFunctionTypes`, subclassing `BaseComponent`, and implementing `IFoo` which extends `IBaseProps`. I can use the `Foo` component in a render, and everything builds correctly.

Closing as no repro, but please re-open if you still have friction!
