### ISSUE TITLE
PeoplePicker fails to select item when itemLimit is 1

### ISSUE THREAD

**Issue by m-sadegh-sh** [OfficeDev/office-ui-fabric-react#3297]
### Bug Report

- __Package version(s)__: 5.17.1
- __Browser and OS versions__: Chrome v61.0.3163.100, Windows Server 2016 DC

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

#### Describe the issue:

When I use PeoplePicker and set itemLimit to 1, after selecting one of suggestions, It tries to set item.selected property to true. Signature of items I pass to component is below:

    return { key: receiver.letterReceiverId, primaryText: receiver.receiverEmail, secondaryText: receiver.receiverDisplayName, type: receiver.type, presence: PersonaPresence.none };

This error is thrown: Cannot add property selected, object is not extensible.

After I change my items to below:

    return { key: receiver.letterReceiverId, primaryText: receiver.receiverEmail, secondaryText: receiver.receiverDisplayName, type: receiver.type, presence: PersonaPresence.none, selected: false };

This error is shown: Cannot assign to read only property 'selected' of object '#<Object>'

I knew that react makes props readonly using [Object.preventExtensions()](https://github.com/facebook/react/pull/9054/files). But I'm not sure if this case is related to react, Is it a bug in PeoplePicker or my usage was incorrect.

**Comment by michaelangotti** [comment]
We believe this issue has been fixed and will close. If it still repros for you, please open a new bug.
