### ISSUE TITLE
DetailsList: Hovering over header hides bottom line

### ISSUE THREAD

**Issue by cschleiden** [OfficeDev/office-ui-fabric-react#3299]
Not sure if a bug or by design, looks odd.

Chrome 100%, Windows 125% DPI scaling:

![image](https://user-images.githubusercontent.com/2201819/32334733-72158d94-bfa8-11e7-855d-bb3378563370.png)

**Comment by kristoferbrown** [comment]
Looks like it's a bug to me, it's being caused by the background color of .cellIsActionable

**Comment by davsm** [comment]
I'm using this workaround until the bug fix is accepted:

.ms-DetailsList {
  .ms-DetailsHeader {
    box-sizing: content-box;
  }
}

**Comment by davsm** [comment]
Thanks for the quick turnaround! Works perfect
