### ISSUE TITLE
Date picker should have an option to not loose focus on click and a better way to change years

### ISSUE THREAD

**Issue by ab18556** [OfficeDev/office-ui-fabric-react#3300]
Hi,

I am dealing with old random dates and the way the date picker behave at the moment makes it barely usable.

Picking up a birth date with the picker is really annoying. You have to click on the little arrows up to 90 times when you want to pick an old birth date. The year should be a text field or maybe it could be clickable like react widgets' date picker do (https://jquense.github.io/react-widgets/api/DateTimePicker/).

Also, with allowTextInput and disableAutoFocus set to true, the focus jumps to the calendar as soon as it open. I think it would be nice to have an option to keep the focus on click. It would be even better to have an option to open the calendar only when the Icon is pressed.

Thanks

**Comment by Jahnp** [comment]
This seems like a reasonable request, but I'd look to the DatePicker codeowners on if this is something on their radar as well. @lorejoh12 @sathi23 , can you take a look at this? Thank you!

**Comment by lorejoh12** [comment]
We've gotten some feedback about allowing a decade picker, but it's currently low on our backlog. We'd love to do a code review if someone wants to make a PR for it though!

as far as autofocusing on the calendar component when disableAutoFocus=true after a click, that actually looks like a bug to me. I'll take a look.
