### ISSUE TITLE
Error in the documentation for overwriting theme colors

### ISSUE THREAD

**Issue by VinozzZ** [OfficeDev/office-ui-fabric-react#3305]
### Bug Report

- __Package version(s)__: 5.9
- __Browser and OS versions__: chrome

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix?  Yes

Requested priority: Normal

Products/sites affected: (if applicable)

#### Describe the issue:

The documentation on the github is different from the one on the website

#### Actual behavior:

import { loadTheme } from 'office-ui-fabric-react/lib/Styling';

loadTheme({
  colors: {
    themePrimary: 'red'
  }
});

#### Expected behavior:
import { loadTheme } from 'office-ui-fabric-react/lib/Styling';

loadTheme({
  palette: {
    'themePrimary': 'red'
  }
});

**Comment by Jahnp** [comment]
Thanks for reporting this @VinozzZ. I've opened #3768 to address this.
