### ISSUE TITLE
DatePicker: convert to use a Callout like Dropdown so that it has same positioning behavior

### ISSUE THREAD

**Issue by PhantomPayne** [OfficeDev/office-ui-fabric-react#331]
The DatePicker doesn't popup when near the bottom of the screen.  I did some digging and it looks like if the DatePicker is near the bottom of the screen focusing it will scroll the popup into view, but the DatePicker dismisses on scroll so it looks like it's doing nothing.

Removing `this._events.on(window, 'scroll', this._dismissDatePickerPopup);` from `componentDidMount()` seemed to fix it for me.

I observed this behavior in both Chrome 53 and Edge. I didn't test with anything else.

**Comment by dzearing** [comment]
This is now complete.
