### ISSUE TITLE
Inconsistent behavior of search icon in CommandBar and in SearchBox

### ISSUE THREAD

**Issue by stanleyxu2005** [OfficeDev/office-ui-fabric-react#3310]
When I focus the SearchBox control, the icon will be removed after an animation is played. But in CommandBar control, the icon will always be there. I hope developer can make the behavior consistent. I'm more prefer to hide the icon when the search box is focused. Thank you.

**Comment by micahgodbolt** [comment]
The searchbox in commandbar is being deprecated. In the 6.0 release of Fabric we'll have a new commandBar that allows you to render a SearchBox component inline which will be much more consistant.

**Comment by stanleyxu2005** [comment]
@micahgodbolt Can I ask when can we access the 6.0 beta and when will be the release date?

**Comment by micahgodbolt** [comment]
You can start testing out the new command bar via @uifabric/experiments/lib/CommandBar. We're shooting late January for a release. Lots of people gone over the holidays.

**Comment by michaelangotti** [comment]
We believe this  issue has been resolved and will  close this issue. If it still repros for you, please open a new bug.
