### ISSUE TITLE
 Can Microsoft Fabric UI be used for non-Microsoft commercial products?

### ISSUE THREAD

**Issue by konsoltech** [OfficeDev/office-ui-fabric-react#3312]
I have been working with Fabric UI which is an open source toolkit. I am wondering if this can be used in a non-Microsoft commercial product?

**Comment by Jahnp** [comment]
Hey @konsoltech, good question! Long story short: it depends. 

Fabric's **assets** (fonts, icons, and product logos) are part of Microsoft's brand, and can only be used in apps & services--including commercial ones--that connect with Microsoft products. These include [Add-ins for Office](http://dev.office.com/docs/add-ins/design/add-in-design), [web parts for SharePoint](https://dev.office.com/sharepoint/docs/spfx/web-parts/get-started/use-fabric-react-components), and other extensions for Microsoft products. This applies to usage of the assets in application code itself as well as any designs produced by the toolkit.

However, all of Fabric's **code** (JS, CSS, etc.) is MIT-licensed and can be used in non-Microsoft commercial products. There's even first-class support for [Selawik](https://github.com/Microsoft/Selawik), an open source drop-in substitute for  Segoe UI. There is not a substitute for the icon font today, however.

Hope this helps! I'll go ahead and close this for now, but please feel free to re-open the issue or reach out if you have more questions.

**Comment by Jahnp** [comment]
Also--I should note that for the icons, in almost every component where Icons are used, you can pass in your own render method via `onRenderIcon`. What this means is that though the components come with Fabric's icons by default, you can override them with your own assets (e.g. from fontawesome), allowing you to use Fabric's code without using its assets.

**Comment by fidabhittani** [comment]
Well, may be this is buggy or something. It doesn't displays ICONS . I have tried using line-awesome

**Comment by fidabhittani** [comment]
And some components are way too rigid in icon configs. Like DatePicker and ComboBoxes.  I dont think DatePicker Icon and DatePicker callout Icons change would be easy

**Comment by Fensterbank** [comment]
@fidabhittani You can use `registerIcons` to override the default icons.
I did not test it with your example, but I think this would also effect the icons used by DatePickers etc.

With FontAwesome it could look like this:
```
import { registerIcons } from '@uifabric/styling';
import Icon from '@fortawesome/react-fontawesome';

registerIcons({
    icons: {
        'Home': <Icon icon={['fal', 'home']} />,
        'HomeSolid': <Icon icon={['fas', 'home']} />,
        'FavoriteStar': <Icon icon={['fal', 'star']} />,
        'FavoriteStarFill': <Icon icon={['fas', 'star']} />,
    },
});
```
