### ISSUE TITLE
Dropdown: Add type-ahead keyboard support

### ISSUE THREAD

**Issue by luisrudge** [OfficeDev/office-ui-fabric-react#333]
Steps to reproduce:
- go to http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select
- click the `<select>` element
- type the first letter of an option ('s', for example)
- the `Saab` option will be selected
- go to http://dev.office.com/fabric#/components/dropdown
- click the first `Dropdown` component
- type the first letter of an option ('o', for example)
- nothing happens

**Comment by mereagan** [comment]
How is this coming? I'd like to be able to use this feature as well. Thanks..

**Comment by gunjandatta** [comment]
Is this feature similar to the textbox dropdownlist component? It would be nice to have an option to filter by the text entered.

**Comment by erikleo** [comment]
Also would really like to have this feature.  Specifically looking to filter the list based on what is typed rather than just the first letter.  

Basically looking to reproduce the functionality of:

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_datalist

but using MS Fabric

**Comment by micahgodbolt** [comment]
issue closed. combobox would be a better fit.
