### ISSUE TITLE
Unable to capture clicks outside non-modal panel

### ISSUE THREAD

**Issue by LarsLiden** [OfficeDev/office-ui-fabric-react#3333]
### Bug Report

- __Package version(s)__: "^4.47.0"
- __Browser and OS versions__: Chome

#### Describe the issue:
Office Fabric has the concept of a "non-modal" panel: https://developer.microsoft.com/en-us/fabric#/components/panel

A non-modal panel does not show an shaded overlay over the rest of the panel, and the buttons in the non-modal area will react to hover events, however they do not respond to clicks (in the sample either)

I'm not clear on the purpose of a non-modal panel if this is not the case.

#### Expected behavior:

Is this intentional?  Or is there a way to respond to clicks in the area outside the non-modal?

**Comment by oengusmacinog** [comment]
Should be solved by PR #4305 - please reopen if still having issues.
