### ISSUE TITLE
Prevent changes from being committed without a changefile

### ISSUE THREAD

**Issue by MLoughry** [OfficeDev/office-ui-fabric-react#3335]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? _Maybe; the build system is rather unique_

Requested priority: _High_

Products/sites affected: All

#### Describe the issue:

#3203 made changes to both oufr and the utilities package; however, it was merged with change files for oufr, but not for the utilities package. As such, oufr 5.18.0 (and later) depended on functionality that simply did not exist in a published version of `@uifabric/utilities`

There should be a task, run during PR builds, that breaks the build if there are code changes in a package without a corresponding change file for that package.

**Comment by dzearing** [comment]
This is done.
