### ISSUE TITLE
Hover color for ComboBox and TextField/Dropdown/DatePicker do not match

### ISSUE THREAD

**Issue by abettadapur** [OfficeDev/office-ui-fabric-react#3350]
### Bug Report

- __Package version(s)__: (fill this out) latest
- __Browser and OS versions__: (fill this out if relevant) all

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low)  Normal

#### Describe the issue:

Hover color for the ComboBox and the TextField/Dropdown/DatePicker controls do not match. ComboBox uses $primary as the hover color, the others use black.

![image](https://user-images.githubusercontent.com/2415669/32620259-1eb74608-c532-11e7-9fa7-59c248abbe28.png)

![image](https://user-images.githubusercontent.com/2415669/32620275-29a18cea-c532-11e7-971b-dc93b159cc5f.png)

![image](https://user-images.githubusercontent.com/2415669/32620289-335d827a-c532-11e7-8a36-3829459418d4.png)

#### Expected behavior:

Unsure which color they should be, but they should match

**Comment by lynamemi** [comment]
I'm working on this as we speak :)

**Comment by abettadapur** [comment]
@lynamemi Any update on the status of this issue?

**Comment by lynamemi** [comment]
@abettadapur The PR that it's in, noted above, is a big one. Those usually take a little longer to get reviewed. I'll ping a couple folks tomorrow if I don't see any progress.
