### ISSUE TITLE
TextField: Move asterisk outside of fieldGroup

### ISSUE THREAD

**Issue by lynamemi** [OfficeDev/office-ui-fabric-react#3351]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

#### Describe the issue:

I recently added support for a required TextField with no label to get an asterisk pseudo element added to the end of the fieldGroup, just like it would to the end of the TextField label if it had one. We need a way to show that field is required if it doesn't have a label.
![image](https://user-images.githubusercontent.com/16619843/32622180-e9ea2dc8-c536-11e7-90fc-0a06406a2104.png)

#### Actual behavior:

This has been causing conflicts with other TextField props, like iconProps and the proposed appended addon prop. 

For example:
![image](https://user-images.githubusercontent.com/16619843/32622094-b3df45ce-c536-11e7-9e65-a943d97d47ae.png)

#### Expected behavior:

If the required asterisk is outside of the fieldGroup it would have fewer conflicts with other props.
![image](https://user-images.githubusercontent.com/16619843/32622215-0d07e6a6-c537-11e7-94de-b6bcce27deeb.png)

Will work with @betrue-final-final on the design.

**Comment by betrue-final-final** [comment]
Here's the specs:
![image](https://user-images.githubusercontent.com/20363037/32622951-7d6349ca-c539-11e7-9f38-9983e0f73d25.png)
