### ISSUE TITLE
TS2339: Property 'href' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Link> & Readonly<{ children?: ReactNode; }> & Read...

### ISSUE THREAD

**Issue by lszomoru** [OfficeDev/office-ui-fabric-react#3359]
### Bug Report

- __Package version(s)__: 5.20.2
- __Browser and OS versions__: Not relevant

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: (Blocking, High, Normal, Low) Blocking

Products/sites affected: Not applicable 

#### Describe the issue:
I have created a new ASP.NET Core project using the "React" template that is included in Visual Studio 2017. The full source code of the template can be found [here](https://github.com/aspnet/templating/tree/dev/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/React-CSharp). Here is a direct link to the [package.json](https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/React-CSharp/package.json), and [tsconfig.json](https://github.com/aspnet/templating/blob/dev/src/Microsoft.DotNet.Web.Spa.ProjectTemplates/content/React-CSharp/tsconfig.json). 

I have added `office-ui-fabric-react` version `5.20.2`, and `@types/prop-types` version `15.5.2` to package.json. 

#### Actual behavior:
I have added a "Spinner" component to one of the pages and that worked fine, but when I add a "Link" component to the page the TypeScript compiler throws the following error message:
_ClientApp/components/FetchData.tsx(33,19): error TS2339: Property 'href' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Link> & Readonly<{ children?: ReactNode; }> & Read...'.
node_modules/office-ui-fabric-react/lib/components/Link/Link.Props.d.ts(7,43): error TS2694: Namespace 'React' has no exported member 'AllHTMLAttributes'._ 

#### Expected behavior:
Code should compiler without any errors.

**Comment by dzearing** [comment]
This is a problem with your @types/react. Which version are you using? Can you try updating it?

**Comment by lszomoru** [comment]
Thanks for getting back to me on this. At the moment the project is using `15.0.35`. I started going through each version and I was able to successfully compile the project using `15.0.37`. I will take a look at the even newer versions of the type definition now. Thanks for your help!

**Comment by DmitryEfimenko** [comment]
I still get the same error
https://stackblitz.com/edit/react-ts-8givce?embed=1&file=index.tsx
