### ISSUE TITLE
Layers: Support a way to ensure some layered components go above other layered components.

### ISSUE THREAD

**Issue by justinmwarner** [OfficeDev/office-ui-fabric-react#336]
If a Dialog is added to the LayerHost, and a Panel afterwards, the Panel will appear on top of the Dialog.

As discussed on Slack, a potential solution would be to have two LayerHosts, one for Popup/Callout/Panel/etc. and another specifically for ModalDialog

Potential problem(s): 
If a Callout is rendered on a Dialog, the Callout should share the LayerHost as the Dialog.
A Callout rendered from a Panel should share the same LayerHost, but the Callout should appear above the Panel.

**Comment by dzearing** [comment]
This is definitely something we should consider. Another simple fix would be that Layer elements can have an isModal flag, false by default. Dialogs turn it on. LayerHost orders layers in order of injection, but sorted by isModal (pushing modal above non modal layers.)

**Comment by justinmwarner** [comment]
I don't think the proposed solutions will work 100% of the time.

We're currently breaking up one of our Panels into sub-components.  While doing so, the render order on our side is effectively the same, however the ContextMenu is being rendered under the Panel.

Another proposed solution: 
App-level: Dialog, Panel
Contextual: Generally everything else (Callout, Teaching, ContextMenu, etc.)

Each App-level component has its own LayerHost (Where order matters; Dialogs are above Panels at all times).  Every Contextual component will know who started rendering it and uses its LayerHost, always putting the Contextual components on top of its App-level ownee component.  The ones that weren't mounted off a App-level component (ie: you have a ContextMenu that pops up with no targetElement) would be at the bottom most level.

**Comment by justinmwarner** [comment]
I think this is very out of date. Closing.
