### ISSUE TITLE
DetailsList: add the ability to style rows at and *above* the currently-hovered row in a hovered style

### ISSUE THREAD

**Issue by elliottsj** [OfficeDev/office-ui-fabric-react#3364]
I'm using a custom `ISelection` instance in a DetailsList which is permanently anchored to the top of the list. i.e. when you select a row, all of the rows above that row become selected too. I'd like to also render these rows in a "hover" style when hovering over a row, to indicate that they will be selected upon clicking.

**Comment by Jahnp** [comment]
Closing since the associated PR indicates that @elliottsj is implementing this in their own project.
