### ISSUE TITLE
loss of selection state if state is modified inside Selection onSelectionChange callback

### ISSUE THREAD

**Issue by aappddeevv** [OfficeDev/office-ui-fabric-react#3366]
### Bug Report

- __Package version(s)__: 4.5.1
- __Browser and OS versions__: chrome latest

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Blocking

Products/sites affected: Dynamics webresource

#### Describe the issue:

When managing the Selection directly for a DetailsList, the selections are not maintained if you modify the component's state (of the parent containing DetailsList) e.g. setState

#### Actual behavior:
The selection is made. Then then the selection is removed e.g. the callback returns [].

Example:
1) Check an item in the DetailsList
2) There is a brief flicker and the item is selected.
3) Your callback is called. Within the callback, you set the state of the parent component say, using the data derived from getSelecttion(). The state change can be completely unrelated to the selection object you are managing.
4) The callback is called again unsetting the selection you just made. getSelection() returns [].

It is impossible to maintain selection with this situation or use the selection to set the state using data derived from the selection in your application when the selection changes.

#### Expected behavior:

The selection is correctly maintained even with the set state request. 

If i remove everything that modifies the state in the callback, the blue checkbox shows up fine. The items list was not changed when clicking on the DetailsRow.

It does not matter if the state is set through setState or through redux (which calls a re-render when it's state changes). This behavior is observed even if you wrap the state change call with setChangeEvents calls. This behavior is also observed if you use the `BaseComponent._events.on(...)` approach to receiving the event. What's strange is that the DetailsRow component sets its state in its callback handler if its selection changes.

Component hierarchy is: `<MyComponent><DetailsList/><AnotherComponent/></MyComponent>`

setItems is called twice in this setup. Once in the constructor with clear = false, and once in the componentWillReceiveProps if the two item arrays are different. componentWillReceiveProps is not called when the behavior above was observed. The selection is maintained as a component instance variable and not kept in the component's state, per the examples in the project.

You can see this behavior more clearly if you use a setInterval to call setState. On its own, the little blue circle is checked, then after the delay it is unchecked, once the state is set.

This seems related to focus/needing a forced update due to the Selection object keeping state on its own. I called forceUpdate() as the first function in my callback handler and without setting state, I observed the same behavior. So I think that by setting the state in the callback handler, something is getting short-circuited. I looked at BaseSelectedItemsList in experiments but it did not help resolve this issue.

**Comment by aappddeevv** [comment]
It looks like part of the issue is that if you manage your own selection and track the selected items in your state (component or redux), then you have to turn off your selection changed handler when you are updating the selection on component mount or change in props. Otherwise, there is a nasty feedback loop.

I still have the problem where even after the set of selected keys is applied (and hence properly maintained in *my* state) between component mounts, etc. the little checkmarks are not appearing on their own.

**Comment by aappddeevv** [comment]
Alright, I think this is resolved. There was a skew in my getKey between components. It looks like the key issue is to break the cycle between your state and the handler set into the Selection object when your component is updating the selection. Essentially, I added some non-component state (not in the state object) to my component to track when the selection object should be updated *and* not issue selection change events.

**Comment by tylerjwatson** [comment]
I know this issue is closed, but I have just spent hours upon hours ripping my hair out over this problem before I stumbled upon this issue, so thank you @aappddeevv for your hints.

To be clear, you need to set `getKey` and `setKey` props on your `DetailsList` to generate keys for your items when overriding `onSelectionChanged`.  An example is provided below:

```js
          <DetailsList
            setKey={'banana'}
            getKey={item => item.id}
            selection={this.selection}
            onItemInvoked={item => this.chdir(item)}
            selectionPreservedOnEmptyClick={true}
            enterModalSelectionOnTouch={true}
            columns={columns}
            items={_.sortBy(folderItems, 'Folder', 'Updated')}
            constrainMode={ConstrainMode.unconstrained}
            dragDropEvents={this.gridDragDropEvents}
          />
```

**Comment by sambluesam** [comment]
Thanks @tylerjwatson ! I even put my setKey as 'banana' in your honor.
