### ISSUE TITLE
Picker 'Diabled' Property Ignored

### ISSUE THREAD

**Issue by gunjandatta** [OfficeDev/office-ui-fabric-react#3372]
### Bug Report

- __Package version(s)__: 5.21.0
- __Browser and OS versions__: IE/Edge/Chrome

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) Known bug until fixed

#### Describe the issue:

The "x" icon to remove the persona from the NormalPeoplePicker component is still visible when the "disabled" property is set to 'true'.

#### Actual behavior:

The user is able to "remove" the persona when the component is disabled.

#### Expected behavior:

The "x" icon and ability to remove personas should not be present when the "disabled" property is set to "true".

**Comment by gunjandatta** [comment]
### Suggested Code Fix
File: SelectedItemDefault.tsx [pickers/PeoplePicker/PeoplePickerItems]

Include the "disabled" property
```
  let {
    disabled,
    item,
    onRemoveItem,
    index,
    selected,
    removeButtonAriaLabel
  } = peoplePickerItemProps;
```

Update the Icon Button to render based on the value
```
      {
        disabled ? null :
          <IconButton
            onClick={ () => { if (onRemoveItem) { onRemoveItem(); } } }
            iconProps={ { iconName: 'Cancel', style: { fontSize: '12px' } } }
            className={ css('ms-PickerItem-removeButton', styles.removeButton) }
            ariaLabel={ removeButtonAriaLabel }
          />
      }
```

**Comment by Grinzzekatze** [comment]
Hi.
Has the property also been introduced for the CompactPeoplePicker? How do I include it?

`  disabled={this.props.disabled} ` does not work for me. The "x" is still selectable.

Thanks for your help!

**Comment by gbminnock** [comment]
seems to only work when onClick method is also be used.

**Comment by Jahnp** [comment]
@gunjandatta had a PR associated with this (#3373), but it lost traction and was closed. If @gunjandatta or someone else would like to pick this up again, we'd be happy to take a look at a PR. Else, I don't think we have immediate plans to implement this. @joschect for FYI as Pickers codeowner.

**Comment by michaelangotti** [comment]
Closing for now. If someone wants to open a PR for it, we can readdress.
