### ISSUE TITLE
Refreshing PeoplePicker Suggestion Store Actively

### ISSUE THREAD

**Issue by fanch2** [OfficeDev/office-ui-fabric-react#3374]
#### Describe the issue:

Hi All, as I am dealing with large amount of people in my organization which it is not applicable to retrieve all user information during the web-part initialization. I think of handle this in another way: after user input, it uses httpclient to look up, which returns a list of users with display name starting with input text(i.e. if user input 'BE', the function would return list of users starting with BE like Ben, Benny, Becky), however, I found that the suggestion list cannot update promptly. Is it possible to update the suggestion list actively?

#### Actual behavior:

The store(suggestion list) not yet refresh until I remove all text and click elsewhere and then click on the picker again

#### Expected behavior:

The suggestion list can be refresh actively after a new query returned.

**Comment by kristoferbrown** [comment]
Have you tried something similar to the how the example PeoplePicker works with "Delay Suggestion Results" turned on? Is implementing something similar to that sufficient for your needs, or did I misunderstand your request?

https://developer.microsoft.com/en-us/fabric#/components/peoplepicker

**Comment by Jahnp** [comment]
Hi @fanch2, did you get a chance to take a look at @kristoferbrown's suggestion? Since this is an old issue, we'll go ahead and close for now, but let us know if you still need help. @joschect for FYI as PeoplePicker codeowner.
