### ISSUE TITLE
A label rendered by/below a ChoiceGroup option is padded due to CSS rules

### ISSUE THREAD

**Issue by Nimelrian** [OfficeDev/office-ui-fabric-react#3376]
### Bug Report

- __Package version(s)__:
  - office-ui-fabric-react: 5.20.3
  - react: 16.0.0
  - react-dom: 16.0.0
- __Browser and OS versions__: Chrome Version 62.0.3202.89 / Windows 10 Pro Version 1703

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

#### Describe the issue:

Using a ChoiceGroupOption's onRender property to customize rendering leads to automatically padded labels when a label is rendered somewhere in the option's subtree. This is caused by [this CSS rule](https://github.com/OfficeDev/office-ui-fabric-react/blob/64a091e1a353e3587c8f67b4bdf5f7f49c74dbbe/packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroup.scss#L56-L59).

#### Actual behavior:

Using ChoiceGroupOption's onRender property and rendering a <Label> somewhere in the option's component tree automatically applies a 26px left padding to the label element.

#### Expected behavior:

The label should not be padded just because it's rendered below a ChoiceGroupOption.

### If applicable, please provide a codepen repro:

CodeSandbox instead of codepen, but does the same job:

https://codesandbox.io/s/jnjj56rx33

**Comment by Jahnp** [comment]
Sorry for the delay @Nimelrian--thanks for reporting. 

Adding @srideshpande as ChoiceGroup codeowner and @lynamemi as FYI. Could you take a look at this when you have a chance? It *definitely* feels wrong to use `:global(.ms-Label)` here--though that spacing is definitely an intentional part of the design.

**Comment by JasonGore** [comment]
Although `ChoiceGroup` was converted to use JS styling, it appears `ChoiceGroupOptions` styling (which applies the padding) is not accessible to consumers of `ChoiceGroup` to change the styling. This bug still exists in a fashion for JS styling. The `ChoiceGroupOptions` styles prop should be exposed somehow, either via `options` prop or `subComponentStyling` method.

[Here is a CodePen](https://codepen.io/jasongore/pen/BPEbry) attempting to use ChoiceGroupOptions styling that doesn't currently work properly.
