### ISSUE TITLE
DetailsList: No data shown after n items, "pages" do not render if .ms-List height set to make header "sticky" 

### ISSUE THREAD

**Issue by aappddeevv** [OfficeDev/office-ui-fabric-react#3378]
### Bug Report

- __Package version(s)__: 5.21.0
- __Browser and OS versions__: chrome, latest version

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: Dynamics application

#### Describe the issue:

In order to keep the DetailsList header in one place and allow scrolling on the "list", I set the ".ms-List" height to the total height - list header height (~30px or so).

However, upon doing this with a long list, the list no longer rendered any pages so scrolling through the list fairly quickly produces "blank" information even though the scroll bar is still scrolling.

Removing the explicit height on the List shows normal display behavior however the header now scrolls with the data which is what we were trying to avoid. Setting listProps.renderCount does not help.

#### Actual behavior:
Data is not rendered and no data is show past the initial set of pages in the page cache.

#### Expected behavior:
The header should stay put and the pages should be generated so that scrolling shows the data.

**Comment by roofs-runner** [comment]
Is there any progress with this issue? Because my long list is not fully rendered even if I set isHeaderVisible to false. Although, if I click the list near the white, blank space, a new portion of items is added.

**Comment by aappddeevv** [comment]
The setting of the height was only to force a scroll of the list body. However, we can use ScrollablePane now per #1146.

**Comment by roger-green** [comment]
I've taken the example code and inserted into a simple create-react-app app. However, I just can't get the sticky's to stick inside the scroll area (they stick to the top of the page instead). This certainly looks like a CSS issue, but I am stumped. If anyone has any ideas, this would be really appreciated! I've uploaded a simple test project here :

https://rockgobyx@bitbucket.org/rockgobyx/fabric-react-test.git

(I can fudge it using some absolute position values, but I would like to find a better solution)

![stickyish](https://user-images.githubusercontent.com/34266849/37817997-9016c024-2e70-11e8-88fe-698caac2f0ef.png)

**Comment by aappddeevv** [comment]
You can make the header sticky if you ensure that you have “positioned”
parents, then the header will be in the right place. Check out some of them
other issues open on this topic as there are other problems.
