### ISSUE TITLE
Adding jquery dialog from office fabric dialog wont handover focus

### ISSUE THREAD

**Issue by carsonal** [OfficeDev/office-ui-fabric-react#3382]
#### Describe the issue:

If a dialog is created through an office fabric dialog, it is impossible to interact with said dialog. Focus is stolen on the page and there is no way to "transfer ownership"

#### Expected behavior:

Focus should move to newly created dialog or there should be a way to stop focus control on dialogs

**Comment by michaelangotti** [comment]
@carsonal Are you talking about Office-UI-Fabric-React or Office-UI-Fabric-JS?

**Comment by michaelangotti** [comment]
Closing this. Lack of activity and probably in the wrong repo.
