### ISSUE TITLE
Icons won't render anymore after package update

### ISSUE THREAD

**Issue by LeonidasFettikus** [OfficeDev/office-ui-fabric-react#3397]
Hi guys,

After updating my packages to latest version, none of the Icons will render. 

```
<Button 
    id='myTextField'
    name='bar'
    iconProps={{ iconName: "Delete" }}
    text='Delete Icon'           
    onClick={() => alert("clicked")}  />
```

will render as: 
![image](https://user-images.githubusercontent.com/8888670/32840104-f22e2874-ca16-11e7-88fd-593d7f8b6b1f.png)

I also noticed that the rendered `<i></i>` tag doesn't have any inner HTML. 

![image](https://user-images.githubusercontent.com/8888670/32840240-63e0b482-ca17-11e7-8548-0607bfb31f47.png)

Anybody got any ideas? It worked fine before the update.

**Comment by lynamemi** [comment]
The way Fabric handles icons changed in v5.0. Check out the updated documentation:
https://github.com/OfficeDev/office-ui-fabric-react/wiki/Using-icons

I'm guessing you need the initializeIcons() call.

**Comment by LeonidasFettikus** [comment]
I facepalmed at myself for once again completely ignoring documentation in favor of trial and error. Thank you for the hint, it solved my problem!

**Comment by lynamemi** [comment]
It's ok, there's a lot of documentation to sift through! Glad it worked for you.
