### ISSUE TITLE
Fabric UI needs to be updated with latest design from Discoverability Framework

### ISSUE THREAD

**Issue by zzchua** [OfficeDev/office-ui-fabric-react#3401]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low) 
High

Products/sites affected: (if applicable)
Outlook.com (Beta)

#### Describe the issue:
Teaching Bubble flyouts in React currently do not follow the new design guidelines: https://fabricreact.azurewebsites.net/fabric-react/master/#/examples/teachingbubble

Some of the changes required include:
1. Need functionality to place images on left/bottom/right/top of the bubble 
2. Remove white border around flyout
3. Font sizes are wrong
4. Padding-bottom between header and body for Condensed is wrong

See discoverability-framework document for more details (link in Teams)

**Comment by betrue-final-final** [comment]
@michaelangotti, for some reason I can’t @mention Angela, but something she should investigate. I’m unfamiliar with this network he speaks of.

**Comment by michaelangotti** [comment]
@angallison Can you look into or comment on this one?

**Comment by micahgodbolt** [comment]
@zzchua can you confirm that this is still an issue?
