### ISSUE TITLE
Dropdown scrolling glitch on IE 11

### ISSUE THREAD

**Issue by mdanielcristian** [OfficeDev/office-ui-fabric-react#3405]
### Bug Report

- __Package version(s)__: 5.18.0
- __Browser and OS versions__: Windows, IE 11. Works as expected in chrome

#### Describe the issue:

Dropdown with many entries, when scrolling down, after moving the mouse it goes back to the top of the list.

#### Actual behavior:

Dropdown list goes back to top when scrolling. It is impossible to get to the entry you need.

#### Expected behavior:

Should be able to scroll down and select any option in the dropdown list

### If applicable, please provide a codepen repro:

![ddl_scroll_issue](https://user-images.githubusercontent.com/30260770/32879626-6f03b368-cab3-11e7-8b47-c0e4d053094b.gif)

**Comment by dzearing** [comment]
@joschect can you test this?

**Comment by dzearing** [comment]
repro:
https://codepen.io/dzearing/pen/XgrRGX

**Comment by joschect** [comment]
This appears to have been caused by #3274 . The menu only actually scrolls back when you move the mouse.

**Comment by mdanielcristian** [comment]
@dzearing anything new on this?

**Comment by mdanielcristian** [comment]
@joschect any updates? is this going to be fixed, or should I try to fix it myself?

**Comment by mdanielcristian** [comment]
@joschect anything new? should I expect a fix or should I look for one myself?

**Comment by magellantoo** [comment]
It seems to be a bug (feature?) in IE where focusing a div causes the parent to scroll to the top of the child element being focused. 
In our case, the onMouseLeave handler for DropDown items calls `focus` on the dropdown's listwrapper.  
In IE and Edge, there is a `setActive` function which behaves similarly to `focus` but does not scroll the parent element.  
[Vanilla HTML repro](https://codepen.io/anon/pen/LeYXVM)

**Comment by sud2903** [comment]
Hi Folks,
I have a GWT application that has some drop downs created using divs.
and I'm also facing the same issue(drop down scrolls to top) in IE while it is working fine in chrome,Edge & firefox.
Please help
