### ISSUE TITLE
Focus getting lost while using input in DetailsList

### ISSUE THREAD

**Issue by bhaveshbhati** [OfficeDev/office-ui-fabric-react#3406]
### Bug Report

- __Package version(s)__: office-ui-fabric-react v5.21.2
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)  High

Products/sites affected: (if applicable)

#### Describe the issue:

We recently updated our OfficeFabric version. We are observing that if you use input inside DetailsList, while user is typing something in the input focus is getting lost, instead it goes back to the row. It used to work on the older version.

It is very annoying for the user. It has caused regression in multiple component in our code where we use input inside DetailsList.

#### Actual behavior:

Focus inside input getting lost while user is typing.

#### Expected behavior:

Focus should not be lost.

**Comment by elliottsj** [comment]
I've attempted a fix in #3425; please try the demo codepen and let me know if this fixes your issue.
