### ISSUE TITLE
Enable modification of choice group button color

### ISSUE THREAD

**Issue by melvsparks** [OfficeDev/office-ui-fabric-react#3410]
### Feature Request

Enable modification of choice group radio button color by implement IStyles for the choice group, so the styling can be updated inline.

**Comment by jordandrako** [comment]
It's on my near-future to-do list to convert ChoiceGroup to mergeStyles which will enable the getStyles API and themes. The [styling wiki entry](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Styling) for more details. I'll close this for now.

**Comment by melvsparks** [comment]
@jordandrako Can you keep me up to date on when the work on this starts? We need this functionality for our OWA Calendar React release?
