### ISSUE TITLE
onClick for ITag

### ISSUE THREAD

**Issue by veloiya** [OfficeDev/office-ui-fabric-react#3438]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) VSTS

#### Describe the issue:
Need onClick in ITag props.
We have a requirement that on clicking on a tag we want some actions to be performed.

**Comment by michaelangotti** [comment]
@veloiya Poking this issue one more time. Is this still needed? If not, we will close in a few days since there hasn't been any activity. Thanks.
