### ISSUE TITLE
MessageBar: able to override the aria-live value

### ISSUE THREAD

**Issue by salehaHussain** [OfficeDev/office-ui-fabric-react#3455]
### Feature Request

Set Message bar aria-live only when focus in side a certain element.

### Requirement
I have a page with a message bar to denote actions of a specific element. The aria-polite reads the message  on page load itself. Can there be a way to specify a parent element in the Message Bar, to read the message only when focus comes inside the parent element.

**Comment by micahgodbolt** [comment]
if we expose announcementPriority as a prop, you could change/remove the aria-polite value when it is called, based on the location of focus. Is this doable for you? I'm not sure we want to bake in focus logic into a component if we don't have to.

**Comment by salehaHussain** [comment]
This is fair. Please do.

**Comment by aditima** [comment]
@micahgodbolt - do you want to add this functionality like you suggested above?

**Comment by micahgodbolt** [comment]
@dzearing should I add a announcementPriority, or aria-live prop to allow custom aria-live values....or is this something that'll be handled by the announcement component on a global scale?

**Comment by dzearing** [comment]
hmm, why wouldn't we just mix in native props provided the user, so aria-* and such can be mixed into the component root? That way if the caller provides `aria-live=""` that can effectively blank it out or use something else? And support any other container attribute we need to add?

**Comment by micahgodbolt** [comment]
@natalieethell this might be a scenario where announced is used. Can you look into if that would be the correct pattern vs controlling the aria-live value.

**Comment by natalieethell** [comment]
@micahgodbolt I think it's fair that the user would want to control the aria-live region and I agree that the "focus" logic should stay out of the MessageBar component.

It might be best to mix in native props as David mentioned above, as I'm not sure that this would be the right scenario for the Announced component. The only props that Announced take in are `id` and `message`, which is the message string that the screen reader will read out. 

Unless we pull the aria-live region or Announced component outside of the MessageBar component to allow the user to control the rendering logic, there will be no way to specify something like "only render the region when this area is focused".
