### ISSUE TITLE
Global theme overrides

### ISSUE THREAD

**Issue by CDoughty08** [OfficeDev/office-ui-fabric-react#3458]
I may just be missing it, but I have had no luck thus far searching previous issues and/or documentation.

When creating an element with fabric I am able to override styles on a component. i.e.
```ts
<IconButton
  styles={{
    root: {
      color: this.theme.palette.neutralTertiaryAlt
    },
    rootHovered: {
      color: 'rgba(200, 0, 0, 0.87)'
    },
    rootPressed: {
      color: 'rgba(200, 0, 0, 0.57)'
    },
    rootDisabled: {
      backgroundColor: 'transparent'
    }
  }}
  iconProps={{ iconName: 'Delete' }}
/>
```

Is there a way to do these override at a global level, similar to how `loadTheme` over-rides all base colors?

Currently I am wrapping them in higher order components, but it feels messy.
Thank you for your time.

**Comment by micahgodbolt** [comment]
Fabric does support global level customization of component types, though i'm not 100% sure the current status of the project (might be limited at the moment). @dzearing has been doing most of the work in this area, and the 6.0 release should greatly improve the themeing support.

**Comment by jordandrako** [comment]
You can create your own variant component using the `styled` function. See the [styling wiki](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Styling#styled-higher-order-component) for more details. Closing for now, reopen if you feel this is still an issue.

**Comment by jordandrako** [comment]
If you just need to override styles in one or two cases and don't want to create a full variant, you should use [the `getStyles` function](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Styling#getstyles-function).

**Comment by CDoughty08** [comment]
Thanks, it seems the the wiki has come quite a ways since November, looks like exactly what I was looking for!
