### ISSUE TITLE
Additions to new CommandBar API

### ISSUE THREAD

**Issue by staylo8** [OfficeDev/office-ui-fabric-react#3462]
### Desired additions to new CommandBar API:

- Right aligned items 
![image](https://user-images.githubusercontent.com/33881401/33284147-ecfd8822-d362-11e7-8c08-25dfa9373657.png)

- Left item drop off on resize
![image](https://user-images.githubusercontent.com/33881401/33284164-f6e6ec02-d362-11e7-98e6-b6a8241b6724.png)

- Name only in overflow menu (same idea as, but opposite of, iconOnly)

**Comment by micahgodbolt** [comment]
fixed in #3463
