### ISSUE TITLE
React v16

### ISSUE THREAD

**Issue by unindented** [OfficeDev/office-ui-fabric-react#3464]
Any plans to migrate to React v16? Or at least relax the peer dependencies to allow it?

**Comment by dzearing** [comment]
yup. I've just updated typescript first, react is next.

**Comment by SimplerSoftware** [comment]
Just ran into this... looking forward to a release supporting v16!

**Comment by dzearing** [comment]
I believe the peer dependencies include v16. @unindented can you point out where it is too restrictive?

**Comment by unindented** [comment]
@dzearing just checked, and they do include `^16.0.0`... I saw a warning on my project and for some reason I thought it was this package. I'm so sorry.

**Comment by unindented** [comment]
Should I close?

**Comment by micahgodbolt** [comment]
this will auto close when the PR gets merged.
