### ISSUE TITLE
[Fabric website] scrollablepane's docs display wrong title

### ISSUE THREAD

**Issue by kanufy** [OfficeDev/office-ui-fabric-react#3468]
### Bug Report

- web site: https://developer.microsoft.com/en-us/fabric#/components/scrollablepane

#### Describe the issue:
![image](https://user-images.githubusercontent.com/8322617/33307283-4e56cb96-d459-11e7-8350-bad272d29ec5.png)

Actual: Title is the 'SearchBox'
Expected:  Title is the 'ScrollablePane'

I seem that the first rendering is 'ScrollablePane', but it is overwritten to 'SearchBox'.

Thanks.

**Comment by Jahnp** [comment]
Oops, that's a really great catch. Thanks @kanufy--we'll get this fixed asap.

**Comment by Jahnp** [comment]
Thanks for the quick fix @leddie24!
