### ISSUE TITLE
Charting

### ISSUE THREAD

**Issue by crossan007** [OfficeDev/office-ui-fabric-react#347]
A single set of themed / styled charts (simliar to https://learn-powershell.net/2016/09/18/building-a-chart-using-powershell-and-chart-controls/) would be neat to have in the Office Fabric.

Maybe integration / sharing with the PowerBI team

**Comment by dzearing** [comment]
I would love this. :) But...before we add more and more components to an already massive library, we'll probably need to tackle splitting the package into sub packages where each can version independently. Will keep this open so that we can add to our internal backlog and address if time permits.

**Comment by luisrudge** [comment]
Victory is a super nice chart library! https://formidable.com/open-source/victory/

**Comment by dzearing** [comment]
For now we are going to close this. We have feature requests archived so as we grow the library, we will consider this in our backlog.
