### ISSUE TITLE
Fabric UI Core Grid Layout DOES NOT WORK

### ISSUE THREAD

**Issue by michel-fornaris** [OfficeDev/office-ui-fabric-react#3473]
I have a very simple HTML page that in summary includes the Fabric UI CSS file and has a body (body.ms-Fabric) with

```
<div class="ms-Grid">
    <div class="ms-Grid-row">
        <div class="ms-Grid-col ms-sm12 ms-u-md4 ms-lg2">
            Column 1
        </div>
        <div class="ms-Grid-col ms-sm12 ms-md8 ms-lg10">
            Column 2
        </div>
    </div>
</div>
```

but is displaying two rows instead of the expected two columns

What am I doing wrong?

Am I missing any other CSS include or class?

Thanks

**Comment by dzearing** [comment]
this would be related to office-ui-fabric-core css stylesheet, which is a separate thing.
