### ISSUE TITLE
Horizontal and vertical scrollbars on DetailsList

### ISSUE THREAD

**Issue by LeonidasFettikus** [OfficeDev/office-ui-fabric-react#3485]
**Package version**: 5.21.1
**Affected browser versions**: IE 11

**Actual behavior:**

We use an OUI DetailsList in a SharePoint 2013 solution (CSR templates). Scrollbars are displayed in IE 11 even though content should fit inside page/container.

This is how it looks:

![image](https://user-images.githubusercontent.com/8888670/33438060-0cd2efdc-d5ea-11e7-91c4-bb8aa4b32c5f.png)

**Expected behavior**:

Because content fits into page, there should be no visible scrollbars.

This is how it should look (correct behavior inside Chrome):

![image](https://user-images.githubusercontent.com/8888670/33438188-5fe6bc8a-d5ea-11e7-8e44-ddb818d7ec64.png)

**Comment by mdanielcristian** [comment]
Had the same issue, fixed it by setting constraintMode DetailsList property to ConstrainMode.unconstrained
`<DetailsList {...this.props}
    items={this.state.viewItems}
    columns={this.state.columns}
    onRenderItemColumn={this.renderItemColumn}
    onColumnHeaderClick={this.onSortOrderChanged}
    constrainMode={ConstrainMode.unconstrained} />`

**Comment by LeonidasFettikus** [comment]
Although I only tested it superficially, it seems to have solved my problem. Will test it further when I get to work on the project again. Thanks!

**Comment by derek-smith** [comment]
I had the same issue and this fixed it for me. Thanks

**Comment by daveamol** [comment]
For me the horizontal bar moves to the bottom of the page instead but still is visible

**Comment by LeonidasFettikus** [comment]
I will close this for now as my issue was resolved when applying `constrainMode={ConstrainMode.unconstrained}`.
