### ISSUE TITLE
New Component: Pagination

### ISSUE THREAD

**Issue by Supaibo** [OfficeDev/office-ui-fabric-react#349]
Hi all,

I would like to implement react fabric pagination component but actually we haven't. Could you implement this control ?

It would be great if we could have this option directly on the list component or just the HTML tag with CSS class in order to integrate in our custom component.

Thank you

**Comment by quangleminhvn** [comment]
Hi all,

May I know the status of this feature? I really need to apply it to our project. Or can you suggest is there any control has pagination that we can apply?

Thank you

**Comment by andybandy89** [comment]
Hi, 
I'd also like to know the status of this feature request? Are there plans for an implementation?

**Comment by koltyakov** [comment]
Any update on this?

**Comment by lebbar** [comment]
Hi,
Pagination is really essential, we need it for detailsList.
I think without pagination the component is really useless.
It would be great to work on it because we are waiting it from 2016...
TY
Regards

**Comment by OverkillTV** [comment]
Or At least integrate the pagination with DetailList !!

**Comment by reecreatepatrik** [comment]
I created a simple fabric style pagination control on top of react-ultimate-pagination if anyone needs a quick solution while this component gets implemented:
https://www.npmjs.com/package/office-ui-fabric-react-pagination

**Comment by betrue-final-final** [comment]
I'm trying to understand how Detailslist is useless without pagination? It incorporates virtualization. Pagination would be an extra layer on top of that. @dzearing, can you chime in?

**Comment by OverkillTV** [comment]
I think most of the time when the DetailsList is used it was meant to used with lot of items/rows so without a pagination it would not be user friendly.

**Comment by betrue-final-final** [comment]
But that's the point, it's virtualized so it should be responsive to scrolling. If the scenario is to add specific jump points between, instead of arbitrary pages, there are lots of ways to precisely slice and dice the data by meaningful metadata, such as sorting, filtering, and grouping. Pagination is forcing people to hunt and peck, not to mention it's so 1997.

**Comment by betrue-final-final** [comment]
Actually you can have "paging" behind the scenes on the server.

**Comment by d0tkom** [comment]
Yes but there is no straightforward way to do it atm. (Or I just don't know about it) The best way would be I think is to have an 'onMore' event that fires once the user gets to the bottom of the list, so we could load the next chunk.

**Comment by betrue-final-final** [comment]
@dzearing might have some ideas.

**Comment by dzearing** [comment]
This is how @d0tkom:

0. Implement a simple loader item which onRender of a give item, kicks off a network request in your data flow. (e.g. executes a redux action.)

1. Use a null placeholder + onRenderMissingItem and render the placeholder.

If you know your items have "more" (e.g. you have a paging token), leave a null placeholder and use onRenderMissingItem to render "loading" and kick off the next request in your datamodel.

2. Use a special item + onRenderRow.

If you encounter your special item (e.g. item.type === 'loading'), render your placeholder.

The solution is not super clear and especially the documentation needs improvement here, but it is indeed very possible as we do this in a number of products today.

Codepen example here which uses the paginated reddit api to render a subreddit:

https://codepen.io/dzearing/pen/EgqMZq

**Comment by dzearing** [comment]
Lots of up-votes, we'll add this component shortly.

**Comment by dzearing** [comment]
@betrue-final-final  just for visibility; lots of upvotes for this component. :) Would be great to add soon, even in experiments.

**Comment by rohmanhm** [comment]
Hi @reecreatepatrik where's your public repo for https://www.npmjs.com/package/office-ui-fabric-react-pagination ?

**Comment by betrue-final-final** [comment]
I’ll be working on a design spec this month.

**Comment by betrue-final-final** [comment]
Here's the design spec: https://microsoft.sharepoint.com/:u:/t/odspux/Ef8XQfRMxMFHkL108TztUmkB0KuR51P8TqJ6UGcZoiycmg?e=CbDFXC

**Comment by caradong** [comment]
@dzearing @betrue-final-final As part of the M365Analytics project, I have implemented a pagination control  for the project and I put together this checkin to add this component to the experiment packages. https://github.com/OfficeDev/office-ui-fabric-react/pull/6532 Please take a look and I would love to work with you guys to finish this control. I aslo have unit tests for this component and will create follow up checkins.
