### ISSUE TITLE
Button State Colors Wrong

### ISSUE THREAD

**Issue by peacokle** [OfficeDev/office-ui-fabric-react#3497]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal) 

Products/sites affected: (All)

#### Describe the issue:

Fabric button colors are wrong.

Primary hover button should be:
bg color: themeDarkAlt

Primary pressed button should be:
bg color: themeDark

#### Expected behavior:

![image](https://user-images.githubusercontent.com/10996777/33462595-3aa8910c-d5ed-11e7-93ce-986eac3fb329.png)

**Comment by dzearing** [comment]
@betrue-final-final

**Comment by StfBauer** [comment]
I know I wasn't mentioned. Just one thought. What will happen when the themePrimary color is white or light grey and the text-color: is white.

**Comment by betrue-final-final** [comment]
The idea is that the themes are set up so the primaries all pass contrast requirements against white. 

If you decide to set a custom theme that uses s light color that will break this, our theme generator should build in safeguards to warn or prevent this from happening. @phkuo, we should sync on this and setup a new issue.

There could also be summer smarts that invert the text color, but I'm not sure how we would do that.

**Comment by dzearing** [comment]
The contrast validation should all be done at theme generation level, not so much at the component level.

I am really excited to have @phkuo's work complete, so that we have a complete and user-friendly story for creating themes.

**Comment by betrue-final-final** [comment]
Yes @dzearing!

**Comment by MLoughry** [comment]
To get back on topic, @betrue-final-final, should the proposed changes be made to the code?

**Comment by betrue-final-final** [comment]
In terms of this PR, it all looks correct except for the focus ring, which should be neutralSecondary, and not themeDark.
