### ISSUE TITLE
Facepile - add option to put showAddButton on right side

### ISSUE THREAD

**Issue by huntwj** [OfficeDev/office-ui-fabric-react#3506]
Currently it seems it can only go on the left, but it would be nice to have the option to put it on the right. Often that is more semantically meaningful as the left-to-right ordering often reflects the order of added items.

**Comment by aditima** [comment]
@betrue-final-final - running this by you to make sure this would be a good add?

**Comment by jordandrako** [comment]
@betrue-final-final as @aditima  said above, is this something we would want to implement?

**Comment by jordandrako** [comment]
I spoke with @betrue-final-final offline and we do not want to support this behavior.
