### ISSUE TITLE
Accessibility: Narrator is not reading the name of dialog.

### ISSUE THREAD

**Issue by Sachin077** [OfficeDev/office-ui-fabric-react#3508]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: TFS

#### Describe the issue:

Accessibility: Narrator is not reading the name of dialog.

#### Actual behavior:

Narrator announces as "Alert focus on close button".

#### Expected behavior:

Narrator should announce as "<Dialog title> alert dialog, focus on close button.

![name of the alert-inspect](https://user-images.githubusercontent.com/7456601/33547037-b9781354-d908-11e7-9a2e-88c1c5004e58.png)
![narrator not reading name of alert](https://user-images.githubusercontent.com/7456601/33547044-bb6ca972-d908-11e7-9396-ade1a3170ac8.png)

**Comment by betrue-final-final** [comment]
Not repro. It now announces itself as a dialog.
