### ISSUE TITLE
The Fabric component should be well documented.

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#351]
We should have documentation for the Fabric component which will:
- Ensure DIR attribute is populated
- Add ms-Fabric-isFocusVisible classname

We should make is super clear to the user that it is a requirement that they use the Fabric wrapper, or that at minimum they have DIR populated, because otherwise components will look broken when they first try it.

``` ts
const App = () => (
<Fabric>
  { children }
</Fabric>
);
```

**Comment by dzearing** [comment]
Additionally, none of the icons will work out of the box, without either:

1. Including fabric.css
2. Using the sass import and bundling fabric with it.

These also need documentation!

**Comment by mikewheaton** [comment]
I thought we already included fabric.css, so that all of the Fabric Core classes are available on a page using Fabric React. Or are we just importing it to reference variables and mixins with no output classes?

**Comment by dzearing** [comment]
@mikewheaton If you import the Dropdown, which references an animation class like ms-animateDown60 or whatever, that is not defined unless you add the fabric css or you import the sass definition.

**Comment by battletoilet** [comment]
Closing.
