### ISSUE TITLE
custom list form using Office-ui-fabric react components

### ISSUE THREAD

**Issue by hasan-abul** [OfficeDev/office-ui-fabric-react#3514]
Hello All,

I am very new to this environment, i am trying to create custom list form web-part using Office-ui-fabric-react components. Could you please share me with any example. I am trying to use various components like colorpicker, dialog etc., with that form.

Please help me here.

Many thanks

**Comment by kristoferbrown** [comment]
Have you reviewed our documentation website? It has examples of how to implement all of the components. Here are all of the dialog examples: https://developer.microsoft.com/en-us/fabric#/components/dialog

Feel free to reopen this issue if these are not the kind of examples you're looking for.
