### ISSUE TITLE
People Picker single selection issue

### ISSUE THREAD

**Issue by mdanielcristian** [OfficeDev/office-ui-fabric-react#3520]
### Bug Report

- __Package version(s)__: 5.16.0
- __Browser and OS versions__: any browser

Requested priority: blocking

#### Describe the issue:

`<NormalPeoplePicker
                onResolveSuggestions={onFilterChanged}
                getTextFromItem={getTextFromItem}
                pickerSuggestionsProps={suggestionProps}
                className={'ms-PeoplePicker'}
                key={'normal'}
                removeButtonAriaLabel={'Remove'}
                itemLimit={props.allowMultiple ? undefined : 1}
                onChange={onChange}
                defaultSelectedItems={props.defaultSelectedPersons && props.defaultSelectedPersons.length > 0 ?
                    props.defaultSelectedPersons.map((person) => {
                        return {
                            primaryText: person.name,
                            secondaryText: person.email,
                            tertiaryText: person.id.toString()
                        };
                    }) : []}
            />`
Normal ppl picker in the case when itemLimit = 1. 
1. Write something in the ppl picker
2. See suggestions
3. First one is automatically highlighted. 
4. Click on the form, outside the picker or the suggestions so that the ppl picker loses focus

#### Actual behavior:

5. The suggestion box is left open on the top left of the page, by clicking on any suggestion, nothing happens, and you can't do anything except refresh the page

Exception in NormalPeoplePicker.render(): TypeError: Unable to get property 'inputElement' of undefined or null reference 
 at BasePicker.prototype.renderSuggestions

#### Expected behavior:

5. Highlighted suggestion is selected and the suggestion box opens

I don't have the time to provide a code repro, but if needed I can create a gif so you can see the behahiour, although, it should be easy to reproduce

**Comment by erichdev** [comment]
Should be fixed by PR referenced above, please reopen if issues remain
