### ISSUE TITLE
Allow explicitly setting focus on DatePicker

### ISSUE THREAD

**Issue by hellonavneet** [OfficeDev/office-ui-fabric-react#3523]
1) DatePicker should have a prop to focus on it when rendering, 
2) IDatePicker should focus method to allow consumers to set focus explicitly on DatePicker. Similar to what IButton.focus() does.

**Comment by aditima** [comment]
@lorejoh12 - could you please take a look at this?

**Comment by lorejoh12** [comment]
We'll pick this up in May/June, and go with solution 2, adding an imperative .focus() function for a consumer that has the component ref to be able to call.
