### ISSUE TITLE
Picker-based components and rejected Promises

### ISSUE THREAD

**Issue by m-sadegh-sh** [OfficeDev/office-ui-fabric-react#3528]
PeoplePicker and other Picker-based components should be able to understand errors when resolving items using Promise-based calls. Currently these components know nothing to do when a Promise rejects and just spins infinitely. I have to manually use Promise.catch and return empty result, By doing this it will show no-results messge. It's better to add another option to Picker.pickerSuggestionsProps to provide a message when error occurred. Also another solution may would be closing callout and show our message somewhere else, But I can't find a method to close/hide callout,

**Comment by aditima** [comment]
@joschect - could you please take a look?
