### ISSUE TITLE
Some icon previews for docs are currently broken

### ISSUE THREAD

**Issue by gscottolson** [OfficeDev/office-ui-fabric-react#3535]
https://developer.microsoft.com/en-us/fabric#/styles/icons

<img width="1828" alt="2017-12-06-screenshot" src="https://user-images.githubusercontent.com/220979/33690176-40df8202-da97-11e7-8793-1a3e7d25097d.png">

**Comment by lynamemi** [comment]
Thanks for tracking this! A fix has been merged with master and should make it onto the website soon.
