### ISSUE TITLE
Keyboard accessibility in pivot is broken

### ISSUE THREAD

**Issue by mdmdakbar** [OfficeDev/office-ui-fabric-react#3569]
- __Package version(s)__:  5.29.0

Requested priority: (Blocking, High, Normal, Low) High

Products/sites affected: (if applicable) VSTS

### Actual behaviour:
Pressing tab on pivot items is not taking the focus to child (which has focusable elements) but taking focus to first pivot item(always) 

#### Expected behavior:
Ideally pressing tab on pivot item should move the focus to first focusable element of its child.

###Codepen repro:
https://codepen.io/mdmdakbar/pen/YYPPWG

I cannot repro this issue on latest office-fabric-react so it may have got fixed.
But I can't find the PR or any issue related to this.

Can you please get me the reference to the PR of this fix.

**Comment by erichdev** [comment]
I believe it was this PR https://github.com/OfficeDev/office-ui-fabric-react/pull/3527

**Comment by kristoferbrown** [comment]
Appears to be fixed in the current build.
