### ISSUE TITLE
DatePicker: Default value should be undefined, not new Date

### ISSUE THREAD

**Issue by abettadapur** [OfficeDev/office-ui-fabric-react#3574]
### Bug Report

- __Package version(s)__: latest

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

#### Describe the issue:
DatePicker sets the default `selectedDate` to `new Date()` if no value is passed via props. Then, if the consumer passes the current date (`new Date()`) in props, the text box does not update because the `selectedDate` is the same as the value passed in props. This is unexpected, the default `selectedDate` should be undefined

**Comment by nguyentoantuit** [comment]
@abettadapur Have you had any information about this issue? I have another issue (#3683) that I believe it will be fixed as well if this bug was fix.

**Comment by abettadapur** [comment]
@nguyentoantuit This is the same issue that led me to submit the PR, so it should be fixed
