### ISSUE TITLE
TS Typings: DetailsList's IColumn interface wrongly defines fieldName as non-optional string

### ISSUE THREAD

**Issue by Nimelrian** [OfficeDev/office-ui-fabric-react#3592]
### Bug Report

- __Package version(s)__:
  - office-ui-fabric-react: 5.34.1
  - typescript: 2.6.2
- __Browser and OS versions__: Not relevant since TS typing error

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal 

#### Describe the issue:

The IColumn interface in the DetailsList typings defines the [`fieldName` property as a non-optional string](https://github.com/OfficeDev/office-ui-fabric-react/blob/ea4bff02f8bb841f24a75ee9e89ed2f5f0b7c9c8/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.types.ts#L226-L230). In truth, it is optional when an `onRender` callback is supplied. This causes TypeScript to throw an error when `fieldName` is omitted

#### Actual behavior:

```ts
const column: IColumn = {
  key: "foo",
  name: "Foo",
  minWidth: 100,
  onRender: (item, index, column) => "Foo",
}

TypeScript error: 'Type '{ key: string; name: string; minWidth: number; onRender: (item: any, index: number, col: IColumn)...' is not assignable to type 'IColumn'.
  Property 'fieldName' is missing in type '{ key: string; name: string; minWidth: number; onRender: (item: any, index: number, col: IColumn)...'.'
```

#### Expected behavior:

```ts
const column: IColumn = {
  key: "foo",
  name: "Foo",
  minWidth: 100,
  onRender: (item, index, column) => "Foo",
}

// Should transpile without errors
```

**Comment by aditima** [comment]
Hi @Nimelrian , this is an entirely legitimate ask. However, fixing this in the current release as a patch might result is build-breaks for consumers if they have the strictNullChecks tsconfig setting. So, we are fixing this in the next major release 6.0 instead.
Hope this works for you!

**Comment by Nimelrian** [comment]
Hey @aditima! Sounds good. I also took a look into the commit. Wouldn't it be possible to do something like this, to get rid of all the `|| ''` fallbacks in the examples, which will surely look confusing to people picking up Fabric:

```ts
interface IBaseColumn {
	key: string;
	name: string;
	className?: string;
	minWidth: number;
	ariaLabel?: string;
	isRowHeader?: boolean;
	maxWidth?: number;
	columnActionsMode?: ColumnActionsMode;
	iconName?: string;
	isIconOnly?: boolean;
	iconClassName?: string;
	isCollapsable?: boolean;
	isSorted?: boolean;
	isSortedDescending?: boolean;
	isResizable?: boolean;
	isMultiline?: boolean;
	isFiltered?: boolean;
	onColumnClick?: (ev?: React.MouseEvent<HTMLElement>, column?: IColumn) => any;
	onColumnContextMenu?: (column?: IColumn, ev?: React.MouseEvent<HTMLElement>) => any;
	isGrouped?: boolean;
	data?: any;
	calculatedWidth?: number;
	currentWidth?: number;
	headerClassName?: string;
	isPadded?: boolean;
}

export interface IPropertyColumn extends IBaseColumn {
	fieldName: string;
}

export interface IRenderCallbackColumn extends IBaseColumn {
	onRender: (item?: any, index?: number, column?: IColumn) => any;
}

export type IColumn = IPropertyColumn | IRenderCallbackColumn

export function isRenderCallbackColumn(column: IColumn): column is IRenderCallbackColumn {
	return (column as IRenderCallbackColumn).onRender != null;
}
```

`buildColumns` would then return `IPropertyColumn[]`. As such, the need for the fallback defaults would be gone.
