### ISSUE TITLE
ExampleCard: Some code examples are causing errors

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#360]
I've been trying to get the example code showing for the dark variant of the Overlay. It builds fine, and then the site won't render and the console gives this error:

*react.js:20145Uncaught Invariant Violation: Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `Highlight`.*

Looking into it, this seems to be caused by Highlight being passed an object instead of a string. Which makes no sense because `OverlayDarkExampleCode` is imported in the same way as `OverlayLightExampleCode` (which works) and the dark example was copied directly from the light one.

```
const OverlayDarkExampleCode = require('./examples/Overlay.Dark.Example.tsx');

<ExampleCard title='Dark' code={ OverlayDarkExampleCode }>
  <OverlayDarkExample />
</ExampleCard>
```

Any idea what's going on here?

**Comment by leddie24** [comment]
Hey Mike just made a PR for this at #379.  I can't seem to repro the bug you described though.  Is it happening when you pull from my branch also?
