### ISSUE TITLE
Are dom typings required?

### ISSUE THREAD

**Issue by nayomitchell** [OfficeDev/office-ui-fabric-react#3601]
We're currently not using dom typings in our tsconfig.json. We do have a couple of dom typings defined in our own lib.d.ts, but upon installing the Office React package, we're receiving errors like 

`node_modules/office-ui-fabric-react/lib/components/Callout/CalloutContent.d.ts(10,26): error TS2304: Cannot find name 'ClientRect'.
calloutElementRect?: ClientRect;`

`node_modules/office-ui-fabric-react/lib/components/ScrollablePane/ScrollablePane.d.ts(23,73): error TS2304: Cannot find name 'ClientRect'.
 subscribe: (handler: (headerBound: ClientRect, footerBound: ClientRect) => void) => void;`

We got around these errors by adding ClientRect to our typings, but I was wondering if there is an alternative, I feel that we shouldn't need to add in dom typings to get it working but I could be wrong.

Thanks in advance!

**Comment by michaelangotti** [comment]
@nayomitchell Is this still an issue? If so, we will investigate further.

**Comment by dzearing** [comment]
In our tsconfig.json, we use

```json
    "lib": ["es2017", "dom"],
```

This seems to solve the issue.
