### ISSUE TITLE
ComboBox: useComboBoxAsMenuWidth should default to true

### ISSUE THREAD

**Issue by abettadapur** [OfficeDev/office-ui-fabric-react#3613]
### Bug Report

- __Package version(s)__: latest

Are you willing to submit a PR to fix? (Yes, No) Yes 

Requested priority: (Blocking, High, Normal, Low)  Normal

Products/sites affected: (if applicable)

#### Describe the issue:

ComboBox recently gained the `useComboBoxAsMenuWidth` prop, which defaults to false. This regressed the ComboBox because anyone who does not provide this property has the Callout appear incorrectly sized.
This property should default to true

**Comment by natalieethell** [comment]
Hey @abettadapur, just wondering in what scenario you're hoping to have a wider Callout when `useComboBoxAsMenuWidth` is unspecified? Would it be possible for you to pass in true to the `useComboBoxAsMenuWidth` prop?

There are some consumers that expect the menu to not be the width of the ComboBox when `useComboBoxAsMenuWidth` in undefined.

**Comment by abettadapur** [comment]
We can close this bug if it's by design, but I would expect the width to match the combobox as the default behavior

**Comment by natalieethell** [comment]
I just discussed this a bit with @jspurlin offline and we've decided to maintain the current behavior. Users can get either behavior with the right props, and this new change may break some consumers that don't expect that menu to be the width of the ComboBox. Feel free to open this issue again if you have any other concerns, but I'm going to go ahead and close it.
