### ISSUE TITLE
Aria attribute in spinner is throwing error

### ISSUE THREAD

**Issue by ssingh28** [OfficeDev/office-ui-fabric-react#3619]
### Bug Report
Below is how my package.json looks like below:
"devDependencies": {
"@microsoft/sp-build-web": "~1.1.0",
"@microsoft/sp-module-interfaces": "~1.1.0",
"@microsoft/sp-office-ui-fabric-core": "^1.3.4",
"@microsoft/sp-webpart-workbench": "~1.1.0",
"@types/chai": ">=3.4.34 <3.6.0",
"@types/mocha": ">=2.2.33 <2.6.0",
"gulp": "~3.9.1"
},

Package-lock.json looks like below:
 
"@microsoft/office-ui-fabric-react-bundle": {
"version": "1.1.0",
"resolved": "https://registry.npmjs.org/@microsoft/office-ui-fabric-react-bundle/-/office-ui-fabric-react-bundle-1.1.0.tgz",
"integrity": "sha1-ar84pi9JImr7jswkt0K/bZ8tcYs=",
"requires": {
"@types/react": "0.14.46",
"@types/webpack-env": "1.13.0",
"office-ui-fabric-react": "2.31.0",
"react": "15.4.2",
"react-dom": "15.4.2"
},
 
"@microsoft/sp-loader": {
"version": "1.1.1",
"resolved": "https://registry.npmjs.org/@microsoft/sp-loader/-/sp-loader-1.1.1.tgz",
"integrity": "sha1-xF3KOJyX5QPcuwHHDnmk6sRM2DE=",
"requires": {
"@microsoft/office-ui-fabric-react-bundle": "1.1.0",
"@microsoft/sp-core-library": "1.1.0",
"@microsoft/sp-lodash-subset": "1.1.0",
"@microsoft/sp-module-interfaces": "1.1.1",
"@microsoft/sp-odata-types": "1.1.0",
"@microsoft/sp-polyfills": "1.1.0",
"@types/es6-collections": "0.5.29",
"@types/es6-promise": "0.0.32",
"@types/react": "0.14.46",
"@types/react-dom": "0.14.18",
"@types/requirejs": "2.1.29",
"@types/webpack-env": "1.13.0",
"es6-collections": "0.5.6",
"es6-promise": "3.1.2",
"office-ui-fabric-react": "2.31.0",
"react": "15.4.2",
"react-dom": "15.4.2",
"requirejs": "2.1.20",
"whatwg-fetch": "0.11.0"
},

"@microsoft/sp-webpart-base": {
"version": "1.1.1",
"resolved": "https://registry.npmjs.org/@microsoft/sp-webpart-base/-/sp-webpart-base-1.1.1.tgz",
"integrity": "sha1-960aj2XwZ7IF/05XM8HDhY/LDwU=",
"requires": {
"@microsoft/decorators": "1.1.0",
"@microsoft/load-themed-styles": "1.4.0",
"@microsoft/office-ui-fabric-react-bundle": "1.1.0",
"@microsoft/sp-component-base": "1.1.0",
"@microsoft/sp-core-library": "1.1.0",
"@microsoft/sp-http": "1.1.1",
"@microsoft/sp-loader": "1.1.1",
"@microsoft/sp-lodash-subset": "1.1.0",
"@microsoft/sp-module-interfaces": "1.1.1",
"@microsoft/sp-page-context": "1.1.0",
"@types/enzyme": "2.5.39",
"@types/es6-collections": "0.5.29",
"@types/es6-promise": "0.0.32",
"@types/react": "0.14.46",
"@types/react-dom": "0.14.18",
"@types/webpack-env": "1.13.0",
"office-ui-fabric": "2.6.1",
"office-ui-fabric-react": "2.31.0",
"react": "15.4.2",
"react-dom": "15.4.2"
},
 
 
 
"office-ui-fabric-react": {
"version": "2.31.0",
"resolved": "https://registry.npmjs.org/office-ui-fabric-react/-/office-ui-fabric-react-2.31.0.tgz",
"integrity": "sha1-cOuk53NRw3Mza8ZKVJyUTmn4SU8=",
"requires": {
"@microsoft/load-themed-styles": "1.4.0",
"@uifabric/utilities": "1.10.4"
}
},

"@microsoft/sp-webpart-workbench": {
"version": "1.1.0",
"resolved": "https://registry.npmjs.org/@microsoft/sp-webpart-workbench/-/sp-webpart-workbench-1.1.0.tgz",
"integrity": "sha1-C06DL7zZlhqISMlUPJBevkuixIk=",
"dev": true,
"requires": {
"@microsoft/gulp-core-build-serve": "2.1.3",
"@microsoft/office-ui-fabric-react-bundle": "1.1.0",
"@microsoft/sp-application-base": "1.1.1",
"@microsoft/sp-build-core-tasks": "1.1.2",
"@microsoft/sp-client-preview": "1.1.1",
"@microsoft/sp-core-library": "1.1.0",
"@microsoft/sp-loader": "1.1.1",
"@microsoft/sp-lodash-subset": "1.1.0",
"@microsoft/sp-module-interfaces": "1.1.1",
"@microsoft/sp-webpart-base": "1.1.1",
"@types/enzyme": "2.5.39",
"@types/es6-collections": "0.5.29",
"@types/es6-promise": "0.0.32",
"@types/react": "0.14.46",
"@types/react-dom": "0.14.18",
"@types/webpack-env": "1.13.0",
"office-ui-fabric-react": "2.31.0",
"react": "15.4.2",
"react-dom": "15.4.2"
},

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Blocking

#### Describe the issue:

Hi Team i am trying to implement a spinner in my webpart using react which has valid aria attributes but if I use the ones mentioned here https://developer.microsoft.com/en-us/fabric#/components/spinner  my webpart throws typescript error for arialabel attribute. The error goes like this: "error TS2339: Property 'ariaLabel' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Spinner> & ISpinnerProps & { children?: ReactNode; }'".  

And if i try to update the version of office-ui-fabric-react by running npm install --save office-ui-fabric-react  i start getting all sorts of typescript errors in node modules like 
 
Error - typescript - node_modules\office-ui-fabric-react\lib\components\Label\Label.types.d.ts(4,43): error TS2694: Namespace 'React' has no exported member 'LabelHTMLAttributes'.
Error - typescript - node_modules\office-ui-fabric-react\lib\components\Layer\Layer.d.ts(3,35): error TS2314: Generic type 'BaseComponent<P>' requires 1 type argument(s).
Error - typescript - node_modules\office-ui-fabric-react\lib\components\Layer\LayerHost.d.ts(3,39): error TS2314: Generic type
'BaseComponent<P>' requires 1 type argument(s).
Error - typescript - node_modules\office-ui-fabric-react\lib\components\Link\Link.d.ts(3,34): error TS2314: Generic type 'BaseComponent<P>' requires 1 type argument(s).
Error - typescript - node_modules\office-ui-fabric-react\lib\components\Link\Link.types.d.ts(6,42): error TS2694: Namespace 'React' has no exported member 'AllHTMLAttributes'.
Error - typescript - node_modules\office-ui-fabric-react\lib\components\List\List.d.ts(33,34): error TS2314: Generic type 'BaseComponent<P>' requires 1 type argument(s).
Error - typescript - node_modules\office-ui-fabric-react\lib\components\MarqueeSelection\MarqueeSelection.d.ts(14,46): error TS2314: Generic type 'BaseComponent<P>' requires 1 type argument(s).

**Comment by ssingh28** [comment]
Hi Team,

I have mentioned that this is a blocking issue. Can you please look into this asap and provide some response on this.

Thanks,
Saurabh Singh.

**Comment by erichdev** [comment]
Hi @ssingh28 not sure if you saw the response on Teams, but have you tried updating @types/react and @types/react-dom?

**Comment by manishgarg1** [comment]
Hi @ssingh28, any updates on the issue? did it get fixed for you?

**Comment by aditima** [comment]
@ssingh28 - Closing this since we haven't heard from you on this in a while. Please reopen if you still need this fixed.
