### ISSUE TITLE
[ChoiceGroup With Icon] Text overflow when label of choice group item is big

### ISSUE THREAD

**Issue by aadhars** [OfficeDev/office-ui-fabric-react#3623]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: All OS

#### Priorities and help requested (not applicable if asking question):

Requested priority: (Blocking, High, Normal, Low) : High

Products/sites affected: (if applicable) VSTS

#### Describe the issue:

When the label of choice group item is big the choice group clips the label for that item.
![image](https://user-images.githubusercontent.com/29277148/34256900-8163857a-e67d-11e7-8f42-bdfc646fb5f8.png)

#### Actual behavior:

Width and height of choice group item should not be fixed. If we use imageSrc it work fine as there is no pre set height and width.

Here is the code which causes issue:
https://github.com/OfficeDev/office-ui-fabric-react/search?utf8=%E2%9C%93&q=choiceFieldIsIcon&type=

https://github.com/OfficeDev/office-ui-fabric-react/search?utf8=%E2%9C%93&q=ms-choiceField-iconField-size&type=

#### Expected behavior:

Width of item should increase and not be constrained to 96 px

**Comment by lynamemi** [comment]
@betrue-final-final What's the desired design for this scenario?

**Comment by lynamemi** [comment]
From the toolkit, it looks like the width should stay fixed but the text should wrap:
![image](https://user-images.githubusercontent.com/16619843/35241033-0b2bd38e-ff6a-11e7-8ab3-733310a46ed5.png)

**Comment by betrue-final-final** [comment]
You are correct @lynamemi. If you have further questions, Adam Ford may be able to answer them.
