### ISSUE TITLE
Accessibility [Combobox]:  Inspect: "Value.Value" property value is empty for combo box .

### ISSUE THREAD

**Issue by Sachin077** [OfficeDev/office-ui-fabric-react#3627]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: All browsers

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: TFS

#### Describe the issue:

Accessibility [Combobox]:  Inspect: "Value.Value" property value is empty for combo box .

#### Actual behavior:

 Inspect: "Value.Value" property value is empty for combo box .

#### Expected behavior:

"Value.value" property value for the combo box should be the selected value in the combo box.

![capture1](https://user-images.githubusercontent.com/7456601/34288703-c79777bc-e714-11e7-95ac-12afbed37453.JPG)

**Comment by jspurlin** [comment]
The value is being appropriately set, this seems like a browser bug.

**Comment by michaelangotti** [comment]
This looks like a browser bug to us. If this is blocking you, please open a new issue.
