### ISSUE TITLE
Feature: Custom class name and dismiss hook for CommandBar context menu

### ISSUE THREAD

**Issue by adriantran** [OfficeDev/office-ui-fabric-react#3630]
There are currently no properties to allow us to give a class name to the context menu used by the commandbar, nor know when the menu is dismissed.

**Comment by michaelangotti** [comment]
@micahgodbolt Checking back on this one. Is there any update on whether this function will be available in the new CommanBar?

**Comment by micahgodbolt** [comment]
The new command bar uses a button as the overflow button/menu. So anything you can pass to button you can pass to menuButtonProps https://github.com/OfficeDev/office-ui-fabric-react/blob/6.0/packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.types.ts#L47

And that certainly includes menuProps, which are all of the props button passes to the contextualMenu. You'd even be able to get to  menuProps.calloutProps.... turtles all the way down.

**Comment by adriantran** [comment]
I have changes to add overflowMenuProps to the current command bar
