### ISSUE TITLE
Problem with installing _rushInstall

### ISSUE THREAD

**Issue by pmashchenko** [OfficeDev/office-ui-fabric-react#3635]
Can some one help me use office-ui-fabric-react with hash not version?
#### Describe the issue:

Trying to install office-ui-fabric-react with some hash 
"office-ui-fabric-react": "https://github.com/OfficeDev/office-ui-fabric-react.git#404d663cd52c79b56d0904678e744b1201f0316b",

#### Actual behavior:

Output:
> office-ui-fabric-react-repo@1.0.0 _rushInstall .../ui-module/node_modules/office-ui-fabric-react
> node node_modules/@microsoft/rush/bin/rush install -c

module.js:538
    throw err;
    ^

Error: Cannot find module '.../ui-module/node_modules/office-ui-fabric-react/node_modules/@microsoft/rush/bin/rush'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! office-ui-fabric-react-repo@1.0.0 _rushInstall: `node node_modules/@microsoft/rush/bin/rush install -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the office-ui-fabric-react-repo@1.0.0 _rushInstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/pavel/.npm/_logs/2017-12-26T20_13_22_702Z-debug.log

#### Expected behavior:

Expected the same result if I'm install by version 
"office-ui-fabric-react": "5.30.2",

My versions:
npm -> 5.6.0
node -> v8.9.3

**Comment by msadahiro** [comment]
I believe that I'm having a similar issue.
I've forked the repo and I went into my local project and placed as a dependencies as this:
"office-ui-fabric-react": "git://github.com/msadahiro/office-ui-fabric-react.git",
when I run NPM install this is the error that I get. 

> office-ui-fabric-react-repo@1.0.0 postinstall /Users/michaelsadahiro/Documents/Microsoft/testing/node_modules/office-ui-fabric-react-repo
> npm run _rushInstall && npm run _rushBuildToFabric


> office-ui-fabric-react-repo@1.0.0 _rushInstall /Users/michaelsadahiro/Documents/Microsoft/testing/node_modules/office-ui-fabric-react-repo
> node node_modules/@microsoft/rush/bin/rush install -c

module.js:487
    throw err;
    ^

Error: Cannot find module '/Users/michaelsadahiro/Documents/Microsoft/testing/node_modules/office-ui-fabric-react-repo/node_modules/@microsoft/rush/bin/rush'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! office-ui-fabric-react-repo@1.0.0 _rushInstall: `node node_modules/@microsoft/rush/bin/rush install -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the office-ui-fabric-react-repo@1.0.0 _rushInstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michaelsadahiro/.npm/_logs/2018-02-04T22_55_26_913Z-debug.log
npm WARN testing@1.0.0 No description
npm WARN testing@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! office-ui-fabric-react-repo@1.0.0 postinstall: `npm run _rushInstall && npm run _rushBuildToFabric`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the office-ui-fabric-react-repo@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/michaelsadahiro/.npm/_logs/2018-02-04T22_55_27_188Z-debug.log


Any help with getting started with the amazing package would be amazing.

Thank you

**Comment by davsm** [comment]
+1 the repo is setup so it cannot be used as an NPM source directly. The repo name isn't actually "office-ui-fabric-react", so the source code can't be used as a package.

**Comment by jordandrako** [comment]
This repo isn't *only* the office-ui-fabric-react npm package source code, it's all the peer packages source code such as merge-styles, etc. You may want to try using the packages/office-ui-fabric-react directory. But, this repo uses [@microsoft/rush](https://www.npmjs.com/package/@microsoft/rush) to build all the necessary packages to work locally, so I'm not sure if this method will work.

Also, I wouldn't recommend using the source code as a package in production. office-ui-fabric-react is currently updated daily, or even multiple times a day so the package will almost always be up to date with the source code. Closing for now, please re-open if this use case persists.
