### ISSUE TITLE
Read-only rating control has inconsistent tab behavior

### ISSUE THREAD

**Issue by kesane-msft** [OfficeDev/office-ui-fabric-react#3639]
### Bug Report

- __Package version(s)__: 5.29.0
- __Browser and OS versions__: Chrome, Windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

#### Describe the issue:

We have used a read only rating control in a detailed list. The tabbing behavior of the control is inconsistent.

#### Actual behavior:

The control is accessible via tab / arrow keys the first time. Then once the control goes out of focus it is not accessible via keyboard.
On debugging, noticed that the tab index is 0 for the first time and post focus change tab index gets set to -1.

#### Expected behavior:

The keyboard navigation should be consistent. Either we cannot navigate or we can always navigate.

**Comment by lambertwang** [comment]
Repro:
https://codepen.io/anon/pen/opGWEj
