### ISSUE TITLE
GroupedList and multiple levels with items

### ISSUE THREAD

**Issue by ramonitor** [OfficeDev/office-ui-fabric-react#3657]
I'm trying to use the GroupedList component with grouping and items (data) on multiple grouping levels.  Example of what I'm trying to display with the GroupedList component:

![levels](https://user-images.githubusercontent.com/3415499/34522528-50f7e2bc-f093-11e7-8ec8-90c0b839cc5e.png)

If I'm correct, the only way to control what items are displayed on what level is the count and startIndex properties where count on the parent level is the number of items on all sub levels combined. Since the sample provided by UI Fabric for React only displays data on the deepest level, I'm wondering if at all possible to use the GroupedList component to display the structure in the screenshot provided.

**Comment by Jahnp** [comment]
@aditima, any thoughts on this? I'm pretty sure I've seen implementations of GroupedList with the behavior @ramonitor is describing but I'm not the expert on the limitations here.

**Comment by ramonitor** [comment]
Any updates on this?

**Comment by aditima** [comment]
I believe the key ask here is to allow group headers and individual items to be siblings of each other, right? Our GroupedList implementation does not support this today. It's defined to either have all groups or all items in any given level.
That said, I feel like what you are asking for is a TreeView control, and we have a pending feature request on it already. We'll make note of one more ask for that control.

**Comment by ramonitor** [comment]
@aditima, yes a TreeView like control is what we would like to have. Moreover, a component that is able to display additional columns (TreeGrid like component) would be even better, since we would like to display additional columns with data in the same view.

**Comment by aditima** [comment]
As noted before, we already have requests for a TreeView control in our backlog. However, the work is not funded yet - we'll need to prioritize it against everything else and schedule the work. Closing the issue since this is not something we can immediately address.

**Comment by willramsey** [comment]
Here's a codepen of my workaround for this issue: [https://codepen.io/wramsey/pen/pmxJJw?editors=0010](url)

Basically, for single items I create a group with that item as its only child. Not the best UX but it works.

Also, if you're using nested data and need to transform it into items and groups to work with the GroupedList component, check out the helper methods.
