### ISSUE TITLE
For multiline messageBar, shouldn't the button be on the same line when there is actually only one line

### ISSUE THREAD

**Issue by shyama1208** [OfficeDev/office-ui-fabric-react#3663]
![image](https://user-images.githubusercontent.com/26054709/34555776-98b3672c-f159-11e7-90e7-7bc644b0d9cd.png)

For multiline messageBar when the text is actually only single line, it does not look good as there is too much of empty space between the text and the button.
Can the button be moved to the same line?

**Comment by betrue-final-final** [comment]
It looks like it's aligned bottom. Aligning top or middle should fix this.

**Comment by lynamemi** [comment]
You can achieve this with the props we currently have. If you specify `isMultiline={ false }`, the button will shift up.  Currently this prop defaults to true. Here's an example from the website:

![image](https://user-images.githubusercontent.com/16619843/35172339-15a964ac-fd1c-11e7-8016-2a4f65e9d40a.png)
