### ISSUE TITLE
Touch screen devices - Content is scrollable under surface components

### ISSUE THREAD

**Issue by dylankil** [OfficeDev/office-ui-fabric-react#3665]
Package version: (fill this out)
Browser and OS versions: iOS, Android

Are you willing to submit a PR to fix?
Yes, but I need to be properly on-boarded to the Office UI Fabric repo before this can happen.

Requested priority: Normal 

Products/sites affected: https://onenote.com/learningtools

#### Describe the issue:

Non blocking callouts and dialogs allow content under the ms_Layer to be scrolled.

#### Actual behavior:

Non blocking callouts and dialogs allow content under the ms_Layer to be scrolled.

#### Expected behavior:

Non blocking callouts and dialogs should not allow content under the ms_Layer to be scrolled.

### If applicable, please provide a codepen repro:

on a mobile device open a private browser and go to:

https://onenote.com/learningtools

Click the try it now button
You should see the Immersive Reader FRE
Scroll the content while FRE callout is open

**Comment by dzearing** [comment]
@dylankil See what you mean. In this case, you have a scrollable div which is accepting scroll panning even when behind an overlay I believe. Should we be preventDefaulting pointerdown events in the overlay here?

**Comment by dzearing** [comment]
Maybe needs `touch-action: none`
