### ISSUE TITLE
External css applied for border is not rendered properly on zoom-out when borderless prop is true in TextField component.

### ISSUE THREAD

**Issue by mdmdakbar** [OfficeDev/office-ui-fabric-react#3673]
Product affected- VSTS

Codepen link - https://codepen.io/anon/pen/zpPNvO

On rendering TextField with borderless prop as true and applying some border css on the div wrapping TextField, border is inconsistent on Zoom-out.
My screen resolution is 2560*1440. Also, on changing the resolution, you can see variations in the border width

On zoom 75% -
![textbox](https://user-images.githubusercontent.com/19491487/34638135-a995d050-f2eb-11e7-9ed3-359d68a7dc9a.PNG)

On zoom 50%
![textbox2](https://user-images.githubusercontent.com/19491487/34638173-3b258efc-f2ec-11e7-813c-1acfbd0c1aea.PNG)
On zoom 25%
![textbox3](https://user-images.githubusercontent.com/19491487/34638174-3dd5f86c-f2ec-11e7-8999-959592faa02f.PNG)

In our product -
![timeout](https://user-images.githubusercontent.com/19491487/34638179-497d08a4-f2ec-11e7-980d-8351db86363f.png)

**Comment by Jahnp** [comment]
Hey @mdmdakbar, I have a feeling this is largely something out of Fabric's control without changing the design to include larger borders. See this SO post for a brief discussion of what I mean: https://stackoverflow.com/questions/47349990/border-disappears-on-zoom-out-in-in-all-browser 

Basically, how 1px borders show up will depend on the *device's* pixel density and how the OS/browser handle sub-pixel rendering, which you see when zooming in and out. To this point, I can actually repro the issue in your Codepen at 50% zoom on my low-DPI external 27" monitor, and at 33% zoom on my high-DPI (2x) laptop monitor.

My sense is this is not something we should target to fix, so I'll go ahead and close for now--but please feel free to reopen if you disagree or have an idea for a solution.
