### ISSUE TITLE
Read error message tied to text box on click of a button.

### ISSUE THREAD

**Issue by ssingh28** [OfficeDev/office-ui-fabric-react#3685]
Requested priority: (Blocking, High, Normal, Low) : Blocked, accessibility issue

Products/sites affected: (if applicable):Webpart dev on  Microsoft Tenant site Collection 

#### Describe the issue:

I am creating a webpart on sharepoint using typescript and reactjs where by in the configuration pane when a mandatory text field if not filled and the save button is clicked the error message is not read by narrator screen reader. This is an accesssiblity issue and needs immediate fix.

#### Actual behavior:

The narrator does read out the error message on load of the configuration pane because that loaded for the first time but if the save button is clicked it doesn't pick the error message again.

#### Expected behavior:
The narrator must pick the error message or success messages what is associated with the button click.

**Comment by ipip2005** [comment]
I think this one needs more details and reproduces as the reading works for me with Edge + Narrator on the "Quick Chart web part" where I type a invalid number e.g. "abc" in a value textbox.

**Comment by ssingh28** [comment]
@ipip2005 : The issue is related to the scenario where if an invalid value is entered in the textbox and the button is clicked the screen reader should read out the error message. Can you please share the webpart where you find this is working so i can have a look.

**Comment by aditima** [comment]
@ssingh28 - this sounds related to how the TextField interacts with the surrounding context in your pane. Narrator does read out the error message in the TextField demo page. https://developer.microsoft.com/en-us/fabric#/components/textfield
Can you please share a repro (either codepen or your MS site)?

**Comment by aditima** [comment]
As I noted before, I wasn't able to repro this. Please reopen with a repro if you are still seeing this.
