### ISSUE TITLE
[TagPicker][Accessibility][HighContrast]Tag Picker shows incomplete borders in Edge

### ISSUE THREAD

**Issue by salehaHussain** [OfficeDev/office-ui-fabric-react#3687]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: Edge, High Contrast White

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: VS Marketplace

#### Describe the issue:

When navigating the Tags names in Edit field, keyboard focus is partially visible.

![image](https://user-images.githubusercontent.com/13566481/34717007-9b784d36-f557-11e7-9fe0-0347f36b0d72.png)

#### Expected behavior:

The border should be complete

This behavior can be observed right now on the Office Fabric page - https://developer.microsoft.com/en-us/fabric#/components/pickers

**Comment by lambertwang** [comment]
Setting the line-height of the `x` icon to 100% fixes this issue. It seems that the line-height was previously being inherited from the root element. In this case, the line-height was set to match the element height (`26px`).  
The box-sizing of the root element was inherited from its container which was set to `border-box`. As a result, the when the outline was added in from the high-contrast mode, the `x` was rendered with a line height larger than the inner-border height of the element.
