### ISSUE TITLE
FocusTrapZone is not properly trapping focus.

### ISSUE THREAD

**Issue by SpencerLynn** [OfficeDev/office-ui-fabric-react#3689]
### Bug Report

- __Package version(s)__: 5.6.0
- __Browser and OS versions__: Windows 10. Chrome. I believe this also reproduces on macOS and in other browsers.

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes, if some pointers as to where the issue could be.

Requested priority: High

Products/sites affected: N/A

#### Describe the issue:

FocusTrapZone component is not properly trapping focus. However, if I first shift-tab backwards in the focus trap zone, then the trap zone properly retains focus even when tabbing forwards through the trap zone. This has to be done each time the trap zone is freshly rendered for the first time (i.e. in a Callout this must be done each time the Callout is opened.

#### Actual behavior:

When the last tab-sequenced element is active in the focus trap zone and the tab key is pressed, tab escapes the trap zone.

#### Expected behavior:

Tabbing through the FocusTrapZone should force focus inside the trap zone, without having to shift-tab through the zone first.

### If applicable, please provide a codepen repro:

https://codepen.io/spencerlynn/pen/JMpMmy?editors=0111

**Comment by erichdev** [comment]
Please see https://github.com/OfficeDev/office-ui-fabric-react/issues/2437
