### ISSUE TITLE
Button component should have a type="button" attribute by default

### ISSUE THREAD

**Issue by arheom** [OfficeDev/office-ui-fabric-react#369]
I am having lots of problems with the Button component (mostly indirect usages). I am developing SPFx web part in React (to be used inside SharePoint Online). 

The main problem is the following: the button renders the markup without the type="button" attribute, so it will automatically make a post-back (I suppose has by default the behavior of type submit). 

This makes lots of components behave in a strange way, like the SearchBox component: has the clear icon as a button, so when one user types something in the SearchBox and presses Enter (like the normal usage), the page posts-back. And his stuff is lost. I have workaround for the Button component used directly (adding the type="button" on the button, but not for the ones used indirectly (like SearchBox and more).

**Comment by dzearing** [comment]
technically you can do this right now. But it is not ergonomic.

```ts
<Button rootProps={{ type: 'button' }} />
```

Instead I'm eager to move back to just taking in native button props and directing them to the right place.

```ts
<Button type='button' />
```

I have a change list to deprecate rootProps and move to this model. Sound good?

**Comment by arheom** [comment]
Does this work also with components using the button? Cos I am using this for the buttons I am adding to the components, But buttons already added in built in components (like SearchBox) does not have this. So my problem is really with the SearchBox component (might also be in other components I am not aware, so thats why I opened the bug with Button).

**Comment by dzearing** [comment]
No doesn't work for searchbox. I will change the title and mark as a feature request.

**Comment by dzearing** [comment]
This is now resolved and you can provide `type` as an option in `button`.
