### ISSUE TITLE
Feature Request: Query Builder

### ISSUE THREAD

**Issue by ryhumble** [OfficeDev/office-ui-fabric-react#3690]
I'm porting over the request for a Query Builder component from the old Trello [board](https://trello.com/c/CEAR6LvG/11-query-builder-component).

My team has built one for our internal product right now and want to talk about contributing it to Office Fabric.

Are you willing to submit a PR to fix? Yes
Requested priority: Normal

**Comment by betrue-final-final** [comment]
Is there a designer working on this?

**Comment by ryhumble** [comment]
We had some input from a vendor designer, but nothing from a Microsoft designer.

It's built from mostly Fabric components with a feature set pretty similar to <http://querybuilder.js.org/>.

**Comment by betrue-final-final** [comment]
That's a pretty complex pattern. Do you have a designer available to help?

**Comment by ryhumble** [comment]
Unfortunately no. As we are internal only, we don't have permanent design resources.

**Comment by betrue-final-final** [comment]
You only create internal tools? There still should be guidance here if you're going to contribute a Fabric component. I would suggest building something and put it in the experiments repo for now. Let's see if we can get you some help. Maybe Tracy Childers?

**Comment by ryhumble** [comment]
@Jahnp , I don't have a codepen or anything, nor would I quickly be able to whip one up. Our QB currently has a couple hard dependencies on some other components/tech we're using.

As I mentioned earlier in the thread, our team builds internal-only tooling right now, so I don't have a public site for you to view either. I can sync with you offline about a quick demo, code walkthrough, etc. though.

I definitely want to explore contributing this component, and we'll have some bandwidth to cut those hard links if this is something worth contributing.

**Comment by micahgodbolt** [comment]
@cschleiden and @ryhumble, any updates on your query builders? A component of this complexity might make sense to live in its own package, rather than in Fabric proper.

**Comment by cschleiden** [comment]
@joezha @paterasMSFT do you have any updates? I know one team was working on a React query editor, would this be something to contribute?

**Comment by joezha** [comment]
It is still on our backlog. We have a prototype built by @ostreifel but it's very feature specific version and we need to make a generic version and contribute to our framework library.

**Comment by xijio** [comment]
any chance you can share an update or the prototype @ostreifel or @joezha?

@cschleiden do you know which team was looking at React?  We were considering something similar

@ryhumble are you willing to offer the same demo to our team?

**Comment by joezha** [comment]
Hi @xijio , @ostreifel created the prototype a while ago during the hackthon but we haven't started the work to bring it to production yet (yes, our team owns the experiences from Azure Boards and was looking at it). I think maybe we can connect offline to share more about that.

**Comment by micahgodbolt** [comment]
sounds like this control is a bit out of scope for Fabric. Seems connections have been made so I'll close this down.
