### ISSUE TITLE
SearchBox component cannot be used in non find on type scenarios

### ISSUE THREAD

**Issue by arheom** [OfficeDev/office-ui-fabric-react#370]
I am developing some SPFx web parts for SharePoint Online and I am using now the SearchBox component.

I have some troubles to integrate it with the solution we have because only supports find on type scenarios. The component has one handler: onChange -> which will give the new value added in the search box and nothing else. Unfortunately we cannot implement find on type in this solution, cos will put quite some load on search service and also does not fit the solution.

What would be necessary for us it to be used also outside of find on type scenarios (which I find it also hard to use, cos will trigger the onChange event every time a key is pressed, so will stress the server quite a lot not having any delay like most of the autocomplete plugins available):
- visually - would be nice to be able to allow the user to notify us he finished entering his value (like a search button)
- technically - either a mode on the SearchBox component itself (like FindOnType mode vs Standard mode) and the events to handle this 2 types of modes, either some key-pressed event (passing the event from javascript to us, so we can implement the required functionality outside of the component)

Is it a plan to have this functionality included in the SearchBox component or the only purpose of the SearchBox is to be used in the very specific case of find on type with no delay and we would have to implement this component internally?

Thanks!

**Comment by dzearing** [comment]
It is incredibly easy for you to add your own debouncing. It is not so easy to "remove" debouncing from one we'd inject.

Maybe something like this would help your scenario, if you didn't want to implement your own solution:
https://github.com/bvaughn/debounce-decorator

Then the event can be fired as many times as necessary, but your code will only execute once every X milliseconds.
