### ISSUE TITLE
is It Possible to Add Custom Button to Default Command bar after Webpart is added in Modern Page

### ISSUE THREAD

**Issue by vamsi981** [OfficeDev/office-ui-fabric-react#3706]
Is there a way to add SPFX Custom Actions to add into default Sharepoint CommandBar instead of new commad Bar for the webpart

**Current behaviour**
![defaultcommandbar](https://user-images.githubusercontent.com/881555/34809218-abd929a8-f6b9-11e7-842c-05f720a1c051.PNG)

**Required behaviour**
![custom commad](https://user-images.githubusercontent.com/881555/34809283-036b0ee8-f6ba-11e7-8e45-4abfc38103de.PNG)

**Comment by Jahnp** [comment]
@manishgarg1 this looks like an issue within SharePoint, definitely Fabric. I'm going to go ahead and close this, but do you know how/if @vamsi981 would be able to achieve this? Or if there's a better place to log issues of this kind?
