### ISSUE TITLE
PeoplePicker Validation to the Form Validation Examples

### ISSUE THREAD

**Issue by vamsi981** [OfficeDev/office-ui-fabric-react#3722]
Is there any example to add PeoplePicker Form Validation like textbox and Dropdown Validations in the below Samples.
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/experiments/src/components/Form/examples/Form.Validation.Example.tsx

**Comment by Jahnp** [comment]
This seems like a reasonable scenario to add examples for. @joschect, thoughts? None of the PeoplePicker examples explicitly demo validation.

**Comment by joschect** [comment]
@vamsi981 and @Jahnp right now the pickers don't have validation. I'll look into adding it.

**Comment by Jahnp** [comment]
@joschect just to be clear, do you mean PeoplePicker doesn't support validation at all? Or just that there aren't examples of it? The interfaces on [PeoplePickers page](https://developer.microsoft.com/en-us/fabric#/components/peoplepicker) suggest that it does support validation (`onValidateInput`, `ValidationState` enum, etc.), though I haven't looked into it closely myself.

**Comment by joschect** [comment]
@Jahnp it kinda supports it, but not in the way the Forms do. It let's the consumer specify a function to determine if specific text isn't allowed. If that text isn't allowed it's up to the consumer to change style/add an error message. This is different than the form elements in that they manage that error state themselves. So it is feasible to use a picker with error logic, but in order to have the error appear the consumer would need to do some more work.

**Comment by Jahnp** [comment]
@joschect gotcha--thanks for the detail, makes perfect sense. Just checking, did you have a chance to look into adding this functionality? Thanks!

**Comment by butchmarshall** [comment]
Not stale - definitely still an issue.  No meaningful support for error messages on PeoplePicker.

**Comment by hoainam3003** [comment]
The people picker should support required validation like others. For now, I have to validate the empty value and show invalid indicator manually.

**Comment by NigelWit** [comment]
Hard to believe this is still an issue - major problem with the Fabric components is the lack of validation routines and different methods/properties for implementing them (e.g. TextBox - 'required' property, DatePicker - 'isRequired' property).

Please, can we get all controls to have validation hooks AND examples of how to use them

Thanks!
