### ISSUE TITLE
Background color incorrect in DetailsList control when used in the grouped mode.

### ISSUE THREAD

**Issue by carruthe** [OfficeDev/office-ui-fabric-react#3729]
### Bug Report

- __Package version(s)__:  15.39.1
- __Browser and OS versions__: macOS, Windows, Commodore 64, all browsers

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? ( No) 

Requested priority: (High to Normal) 

#### Describe the issue:

When using the DetailsList control in grouped mode, the background of the indent 'ms-GroupSpacer' is hardcoded to white (based on the 'root_d5765b36' class in my instance), rather than inheriting the class that I specify in the control 'className' attribute (or 'headerClassName' and 'className' attributes of the individual columns.

### If applicable, please provide a codepen repro:

Here is a repro of the problem using React 16.2.0 and office-ui-fabric-react 15.39.1

[https://codepen.io/tcarruthers/pen/zZBGvP](https://codepen.io/tcarruthers/pen/zZBGvP)

**Comment by battletoilet** [comment]
@aditima would have some time to take a look at this?

**Comment by aditima** [comment]
Hi @carruthe - 

I modified your codepen slightly to get this working: https://codepen.io/aditima/pen/jZjyge 

The crux was to override the row rendering to add our custom className:
                      `onRenderRow={ (props, defaultRender) => {
                            let newProps = {  ...props,  className: 'myBackgroundColor' };
                            return defaultRender(newProps);
                        }}`
Also cleaned up a few unnecessary overrides, and needed to override specificity for the root of the DetailsList.

This is not ideal, and we should rethink the interfaces. But hopefully this will unblock you.

Thanks!

**Comment by aditima** [comment]
Hi @carruthe - Closing this now. Please feel free to reopen if the above solution did not work for you.
