### ISSUE TITLE
Details List not resetting selection state after items are reloaded 

### ISSUE THREAD

**Issue by vamsi981** [OfficeDev/office-ui-fabric-react#3755]
Details list  Not Resetting selection state after items are reloaded, selection state is maintained same once the item is removed from the existed items list it is selecting old index.

```
<MarqueeSelection selection={ this._selection }>
      <DetailsList
      items={ this.props.Items }
      columns={ this.props.Columns }
      setKey='set'
      layoutMode={ DetailsListLayoutMode.justified }
      isHeaderVisible={ true }
      selection={ this._selection }
      selectionPreservedOnEmptyClick={ true }
      />
  </MarqueeSelection>
```

**Comment by aditima** [comment]
Hi @vamsi981, it would be great if you can share a codepen or a repro illustrating your scenario.

You probably need to pass in a new array when your items list updates, and/or use a setKey to identify your items list, so that we end up calling the selection.setItems() with the new items array.

Look at the componentWillReceiveProps method in DetailsList:
  public componentWillReceiveProps(newProps: IDetailsListProps) {
  ......
    let shouldResetSelection = (newProps.setKey !== setKey) || newProps.setKey === undefined;
....
    if (newProps.items !== items) {
      this._selection.setItems(newProps.items, shouldResetSelection);
    }
....
}

Hope this helps.

**Comment by vamsi981** [comment]
Hi @aditima thanks for the reply, we followed as you suggested and it worked, it would be great if such examples are created at the components page

**Comment by michaelangotti** [comment]
It looks like this issue has been answered/resolved. Closing this issue.

**Comment by RangelBorene** [comment]
Hi @vamsi981, @aditima, @michaelangotti! 
You can use hooks in this way:
---
    const [selectionState] = React.useState(new Selection({
        onSelectionChanged: () => {
            setSelectedCount(selectionState.getSelectedCount());
        }
    }));
---
                    <ShimmeredDetailsList
                        items={itemsData}
                        columns={columns}
                        setKey="set"
                        layoutMode={DetailsListLayoutMode.fixedColumns}
                        constrainMode={ConstrainMode.unconstrained}
                        onRenderDetailsHeader={onRenderDetailsHeader}
                        selection={selectionState}
                        enableShimmer={enableShimmer}
                        selectionPreservedOnEmptyClick={true}
                        listProps={{ renderedWindowsAhead: 0, renderedWindowsBehind: 0 }}
                        ariaLabelForSelectionColumn="Toggle selection"
                        ariaLabelForSelectAllCheckbox="Toggle selection for all items"
                        onItemInvoked={onItemInvoked}
                    />
---
