### ISSUE TITLE
[Search Box] The search box text appears dark black on IE 11 as compared to other browsers like chrome

### ISSUE THREAD

**Issue by akashperfect** [OfficeDev/office-ui-fabric-react#3756]
### Bug Report

- __Package version(s)__: 5.4.1
- __Browser and OS versions__: IE 11 Version (11.192.16299.0)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Internal Sites

#### Describe the issue:

The search box text appears dark black on IE 11 as compared to other browsers like chrome

#### Actual behavior:

This snapshot is taken from IE 11
![image](https://user-images.githubusercontent.com/2953096/35219102-2644b96a-ff97-11e7-83ee-cecace3ade38.png)

#### Expected behavior:

This is snapshot is taken from chrome 
![image](https://user-images.githubusercontent.com/2953096/35219260-e8ff6bee-ff97-11e7-88c5-0d8cb341e9e5.png)

**Comment by lynamemi** [comment]
We aren't specifying placeholder text color, the browser is handling that. @betrue-final-final Are you ok with letting the browser handle this or should we adapt components with placeholders (SearchBox, TextField, etc) to a consistent, specified color?

**Comment by betrue-final-final** [comment]
I would expect that we set it ourselves for the consistency reasons you mention. You never know what you'll get with a browser.

**Comment by lynamemi** [comment]
@betrue-final-final I'm seeing some examples in the toolkit where neutralSecondary is used as the placeholder color and some where neutralPrimary is used. What's the final word?

**Comment by betrue-final-final** [comment]
Wow, neutralSecondary please
