### ISSUE TITLE
[TextField] It's would be nice if we support mask attribute for TextField

### ISSUE THREAD

**Issue by nguyentoantuit** [OfficeDev/office-ui-fabric-react#3769]
Hi all,

There some library that implement mask attribute on input element 
 such as [react-input-mask](https://www.npmjs.com/package/react-input-mask) but it is not able to integrate with Fabric UI.
Do we have any plan to support mask attribute on TextField?

Thank in advance,
Toan

**Comment by Jahnp** [comment]
This seems like a reasonable feature to support. I don't believe there are current plans, but I'll check in with the broader team to see if it's on anyone's radar.

**Comment by nguyentoantuit** [comment]
Thanks @Jahnp 
Looking forward to seeing this option available on TextField.

**Comment by lynamemi** [comment]
I think someone has a PR for this one out already! #3783
