### ISSUE TITLE
DetailsList can render custom elements?

### ISSUE THREAD

**Issue by szmarci** [OfficeDev/office-ui-fabric-react#3773]
Is it possible somehow that the `<DetailsList/>` component renders custom components inside its cells?
I want to make a grouped detailslist with input fields inside the cells.
Thanks!

**Comment by szmarci** [comment]
Well, nevermind. I just found out that for the item I can give any value, not just string.

**Comment by Jahnp** [comment]
Great to see you found the solution yourself, @szmarci. For those who may be looking for this functionality, you can check out the `DetailsList` docs page here: https://developer.microsoft.com/en-us/fabric#/components/detailslist

When defining the columns that you pass to `DetailsList`, you can provide an `onRender` that allows you to pass whatever you want. Here's a snippet from that page: 
```tsx
...
onRender: (item: IDocument) => {
          return (
            <img
              src={ item.iconName }
              className={ 'DetailsListExample-documentIconImage' }
            />
          );
        }
...
```
If it's alright, I'm going to go ahead and close this for now, but feel free to reopen if you have more questions, comments, or issues.

**Comment by szmarci** [comment]
@Jahnp Thanks for your answer.
I tried your solution, but that renders the same value in each cell in a row (rows have different values, but the cells inside them are the same).
My goal is to have individual elements in each cell.
So what I did for the `items` (IDetailsListProps) was:
```
{ 
  name: name,
  key: 'item-' + i,
  monday: <input value={1}/>,
  tuesday: <input value={2}/>,
  wednesday: <input value={3}/>,
  thursday: <input value={4}/>,
  friday: <input value={5}/>,
  saturday: <input value={6}/>,
  sunday: <input value={7}/>
}
```
That rendered the cells like this: [1,2,3,4,5,6,7].
But when I tried yours:
```
{ 
  name: name,
  key: 'item-' + i,
  monday: 'monday',
  tuesday: 'tuesday',
  wednesday: 'wednesday',
  thursday: 'thursday',
  friday: 'friday',
  saturday: 'saturday',
  sunday: 'sunday',
  value: Math.floor(Math.random()*10)
}
```
With onRender in IColumn:
```
var obj: IColumn = {
  key: i ? days[i] : 'name',
  name: i ? days[i] : 'Projects',
  fieldName: i ? days[i] : 'name',
  minWidth: i ? 75 : 300,
  maxWidth: i ? 75 : 300,
  className: days[i],
  onRender = (item: any) => {
      return (
        <input type='number' value={item.value}/>
      );
   }
}
```
Lets say the random number from item was `5`, then a row looked like: [5,5,5,5,5,5,5].

There is something wrong with my application of your solution or is it supposed to work like that?

**Comment by szmarci** [comment]
Sorry, I have figured out how `onRender` works.
However I found a strange issue with that here: #3790 
Do you know why `onRender` called on every scroll event?
