### ISSUE TITLE
Type compilation failures on TypeScript 2.7 RC

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [OfficeDev/office-ui-fabric-react#3778]
### Bug Report

- __Package version(s)__: 5.29.2, 5.41.2
- __TypeScript version__: 2.7.0-dev.20180122

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Blocking

Products/sites affected: Sway

#### Describe the issue:

When compiling with TypeScript 2.7's RC, we get:

```typescript
node_modules/office-ui-fabric-react/lib/components/Callout/Callout.types.d.ts:6:10 - error TS2305: Module '"C:/Code/My-Repo/node_modules/office-ui-fabric-react/lib/utilities/positioning"' has no exported member 'ICalloutPositionedInfo'.

6 import { ICalloutPositionedInfo } from '../../utilities/positioning';
           ~~~~~~~~~~~~~~~~~~~~~~


node_modules/office-ui-fabric-react/lib/components/Callout/CalloutContent.d.ts:6:10 - error TS2305: Module '"C:/Code/My-Repo/node_modules/office-ui-fabric-react/lib/utilities/positioning"' has no exported member 'ICalloutPositionedInfo'.

6 import { ICalloutPositionedInfo } from '../../utilities/positioning';
           ~~~~~~~~~~~~~~~~~~~~~~


node_modules/office-ui-fabric-react/lib/components/SpinButton/SpinButton.types.d.ts:3:10 - error TS2305: Module '"C:/Code/My-Repo/node_modules/office-ui-fabric-react/lib/utilities/positioning"' has no exported member 'Position'.

3 import { Position } from '../../utilities/positioning';
           ~~~~~~~~
```

Here's the corresponding `tsconfig.json`:

```typescript
{
  "compilerOptions": {
    "allowJs": true,
    "experimentalDecorators": true,
    "forceConsistentCasingInFileNames": true,
    "jsx": "react",
    "lib": [
      "es2015"
    ],
    "module": "commonjs",
    "moduleResolution": "node",
    "noImplicitReturns": true,
    "noImplicitThis": true,
    "noImplicitAny": true,
    "outDir": "build/dist",
    "rootDir": "src",
    "strict": true,
    "strictFunctionTypes": false,
    "sourceMap": true,
    "suppressImplicitAnyIndexErrors": true,
    "target": "es5",
    "pretty": true
  },
  "exclude": [
    "node_modules",
    "build",
    "scripts",
    "acceptance-tests",
    "webpack",
    "jest"
  ],
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx"
  ]
}
```

**Comment by JoshuaKGoldberg** [comment]
This is odd. Using `SpinButton.types.d.ts`' complaint about `Position` as an example:

* `Position` is declared in `utilities/positioning/positioning.types.d.ts`
* `utilities/positioning/index.d.ts` has `export * from './positioning.types'
* utilities/positioning.d.ts` has `export * from './positioning/index'.

In `utilities/positioning.d.ts`, adding...

```typescript
export { Position } from './positioning/index';
```

...gives `[ts] Circular definition of import alias 'Position'.`.

If we change `SpinButton.types.d.ts` to `import { Position } from '../../utilities/positioning/positioning.types'`, it works fine.

**Comment by JoshuaKGoldberg** [comment]
Errors don't show up with `typescript@2.7.0-dev.20180116` but do starting in `typescript@2.7.0-dev.20180118`.

**Comment by mhegazy** [comment]
@JoshuaKGoldberg what are the steps i need to reproduce this locally?

**Comment by JoshuaKGoldberg** [comment]
1. Create a new blank project with the tsconfig from the linked OfficeDev issue
2. `npm install office-ui-fabric-react`
3. In a .ts file, `import { loadTheme } from "office-ui-fabric-react";`

There should be some typing issues there. If not I can email you (not open) source code.

**Comment by JoshuaKGoldberg** [comment]
Being fixed in TypeScript. Closing here as external.
