### ISSUE TITLE
DropDown: Uncaught (in promise) TypeError: props.options.forEach is not a function

### ISSUE THREAD

**Issue by ecoukraine** [OfficeDev/office-ui-fabric-react#3788]
Hi guys,

I'm using office-ui-fabric-react npm package with React.
I've used version "office-ui-fabric-react": "2.34.2" with TypeScript 2.2.2 - everything worked as expected.

Now I'm updating React to the 15.6.0 (going to update to 16.0 after) and updated "office-ui-fabric-react" to the latest 5.42.0

After that I get an exception in browser console:
_Uncaught (in promise) TypeError: props.options.forEach is not a function
    at new Dropdown (Dropdown.tsx:57)_

Print screen attached: 
![image](https://user-images.githubusercontent.com/11150186/35338468-b75cd00a-0126-11e8-8700-8113c5a99b8a.png)

Would you be kind to look into it, how it can be fixed?
Looking forward to hearing from you

**Comment by oengusmacinog** [comment]
@ecoukraine are you still getting this issue after updating to React v16.0?

**Comment by ecoukraine** [comment]
Hi Brian,

I've just reverted back to older version.

Should I update Fabric UI to some latest version? If yes, please write to which one?

Thank you

[https://ipmcdn.avast.com/images/icons/icon-envelope-tick-round-orange-animated-no-repeat-v1.gif]<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>    Virus-free. www.avast.com<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>

On Mon, Jan 29, 2018 at 10:58 PM, Brian Garland <notifications@github.com<mailto:notifications@github.com>> wrote:

@ecoukraine<https://github.com/ecoukraine> are you still getting this issue after updating to React v16.0?

**Comment by battletoilet** [comment]
@ecoukraine, please update to the latest version of Fabric.

**Comment by oengusmacinog** [comment]
I'm going to go ahead and close this ticket. Please feel free to reopen or open another issue if you are still having this problem with the latest version.

**Comment by lisapalathingal** [comment]
Were you able to fix this issue? Please let me know how you fixed it as I am currently having the same issue (even after updating to latest version)

**Comment by ecoukraine** [comment]
Hi guys,

I've try the latest "office-ui-fabric-react": "5.106.1-hotfix.1" - result the same:
![image](https://user-images.githubusercontent.com/11150186/40708204-88b93c60-63fb-11e8-83a8-5adbcee58a56.png)

Could you please suggest what should I do to successfully upgrade my React to 16.x?

Thank you
