### ISSUE TITLE
Horizontal scrollbar doesn't appear on Detailslist when screen is too small

### ISSUE THREAD

**Issue by Nurleyanti** [OfficeDev/office-ui-fabric-react#3789]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No
Requested priority: (Blocking, High, Normal, Low) 
Normal
Products/sites affected: (if applicable)

#### Describe the issue:

The Detailslist doesn't show a horizontal scrollbar when the screen is too smalll to fit all the columns. The other columns are gone and can't be seen.

#### Actual behavior:

The Detailslist is only showing the columns that fit the screen.

#### Expected behavior:

Even though the other columns don't fit the screen, there should be a horizontal scrollbar to make them appear

**Comment by battletoilet** [comment]
@Nurleyanti Try using the DetailsListLayoutMode enum to resolve this issue.

**Comment by jordandrako** [comment]
Closing this issue for now. If the above advice doesn't solve this for you feel free to reopen.

**Comment by BizH** [comment]
The most likely cause of this is enclosing it in a div (or any parent element like body) that has overflow-x explicitly set to hidden.
