### ISSUE TITLE
Cannot find module '@microsoft/load-themed-styles' from 'theme.js'

### ISSUE THREAD

**Issue by unindented** [OfficeDev/office-ui-fabric-react#3812]
### Bug Report

- __Package version(s)__: `office-ui-fabric-react@=5.34.0`
- __Browser and OS versions__: irrelevant

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: High 

Products/sites affected: Yammer.com

#### Describe the issue:

Builds have started failing today with the error:

```
ERROR in ./node_modules/@uifabric/styling/lib/styles/theme.js
Module not found: Error: Can't resolve '@microsoft/load-themed-styles' in '/Users/daniel/Code/yammer-clients-new/projects/yammer-web/node_modules/@uifabric/styling/lib/styles'
 @ ./node_modules/@uifabric/styling/lib/styles/theme.js 7:27-67
 @ ./node_modules/@uifabric/styling/lib/styles/index.js
 @ ./node_modules/@uifabric/styling/lib/index.js
 @ ./node_modules/office-ui-fabric-react/lib/Styling.js
 @ ./node_modules/yamui/dist/util/fabric/theme.js
 @ ./node_modules/yamui/dist/yamui.js
 @ ./node_modules/yamui/dist/components/Fabric/Fabric.js
 @ ./node_modules/yamui/dist/components/Fabric/index.js
 @ ./src/bootstrap/2-render/renderer.tsx
 @ ./src/bootstrap/2-render/index.ts
 @ ./src/bootstrap/0-entry/bootstrap.ts
 @ ./src/bootstrap/0-entry/main.ts
```

```
    Cannot find module '@microsoft/load-themed-styles' from 'theme.js'

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:191:17)
      at Object.<anonymous> (node_modules/@uifabric/styling/lib/styles/theme.js:7:28)
```

#### Actual behavior:

Error.

#### Expected behavior:

No error.

### If applicable, please provide a codepen repro:

Not applicable.

**Comment by unindented** [comment]
Ha, weird. It looks like npm is installing an empty `@microsoft/load-themed-styles` module:

<img width="267" alt="screen shot 2018-01-25 at 8 21 38 pm" src="https://user-images.githubusercontent.com/69485/35425136-6ebec348-020d-11e8-9d52-bae23abc0122.png">

Sounds like an issue on their end. They recently had problems with other packages disappearing.

**Comment by myleftshoe** [comment]
Me too! I even uninstalled node.js and npm, reinstalled node 9.4 (npm 5.6) and create-react-app, then followed the instructions in the readme.md to the letter to create DocumentCardBasic with same error reported above. 
(Windows 10 Pro 17025)

**Comment by jimmywim** [comment]
Any idea how to work around this? Our packages.json in our project specifically references 5.38.1, however VSTS build seems to be getting whatever's the latest version regardless, which is this broken build.

**Comment by jimmywim** [comment]
Related bug in another package: https://github.com/Microsoft/web-build-tools/issues/511

**Comment by myleftshoe** [comment]
Cheers jimmywim! 
Installed previous version and it works!
`npm install --no-save @microsoft/load-themed-styles@1.7.25`

**Comment by nickpape-msft** [comment]
Looks like there was a hiccup in the release process yesterday. I went ahead and unpublished 1.7.26, so you should be getting 1.7.25 when you `npm install @microsoft/load-themed-styles@latest`. Let me know if you are experiencing the problem with any other packages.

**Comment by micahgodbolt** [comment]
closing this down as it appears resolved. feel free to open if problem persists.

**Comment by paterasMSFT** [comment]
I ran into this today. Had to manually run "npm install @microsoft/load-themed-styles@latest" against a fresh clone to get "npm install" to complete.
