### ISSUE TITLE
Not compatible with TypeScript 2 typings of React (@types/react)

### ISSUE THREAD

**Issue by kollster** [OfficeDev/office-ui-fabric-react#382]
office-ui-fabric-react is not compatible with TypeScript 2 typings for React. When you use TypeScript 2 and install the typings for React (`npm install --save-dev @types/react`) you get a lot of errors. The errors I have found are because office-ui-fabric-react uses old typings for react. A lot of the react events and event handlers use generics in the new typings. 

For an example, when you import the office-ui-fabric-react `Button ` in an app, you get the following TypeScript compiler error: 

> ERROR in node_modules\office-ui-fabric-react\lib\components\Button\Button.Props.d.ts                                                         
> (34,15): error TS2314: Generic type 'MouseEventHandler' requires 1 type argument(s).

Old react typings that office-ui-fabric-react uses:
```
    //
    // Event Handler Types
    // ----------------------------------------------------------------------

    interface EventHandler<E extends SyntheticEvent> {
        (event: E): void;
    }

    type ReactEventHandler = EventHandler<SyntheticEvent>;

    type ClipboardEventHandler = EventHandler<ClipboardEvent>;
    type CompositionEventHandler = EventHandler<CompositionEvent>;
    type DragEventHandler = EventHandler<DragEvent>;
    type FocusEventHandler = EventHandler<FocusEvent>;
    type FormEventHandler = EventHandler<FormEvent>;
    type KeyboardEventHandler = EventHandler<KeyboardEvent>;
    type MouseEventHandler = EventHandler<MouseEvent>;
    type TouchEventHandler = EventHandler<TouchEvent>;
    type UIEventHandler = EventHandler<UIEvent>;
    type WheelEventHandler = EventHandler<WheelEvent>;
```

New event handlers from @types/react
```
    interface EventHandler<E extends SyntheticEvent<any>> {
        (event: E): void;
    }

    type ReactEventHandler<T> = EventHandler<SyntheticEvent<T>>;

    type ClipboardEventHandler<T> = EventHandler<ClipboardEvent<T>>;
    type CompositionEventHandler<T> = EventHandler<CompositionEvent<T>>;
    type DragEventHandler<T> = EventHandler<DragEvent<T>>;
    type FocusEventHandler<T> = EventHandler<FocusEvent<T>>;
    type FormEventHandler<T> = EventHandler<FormEvent<T>>;
    type KeyboardEventHandler<T> = EventHandler<KeyboardEvent<T>>;
    type MouseEventHandler<T> = EventHandler<MouseEvent<T>>;
    type TouchEventHandler<T> = EventHandler<TouchEvent<T>>;
    type UIEventHandler<T> = EventHandler<UIEvent<T>>;
    type WheelEventHandler<T> = EventHandler<WheelEvent<T>>;
    type AnimationEventHandler = EventHandler<AnimationEvent>;
    type TransitionEventHandler = EventHandler<TransitionEvent>;
```

**Comment by unindented** [comment]
Same here, encountered this while going through the [Get started](http://dev.office.com/fabric#/get-started#react) example:

```
./node_modules/office-ui-fabric-react/lib/components/Button/Button.Props.d.ts
(34,15): error TS2314: Generic type 'MouseEventHandler' requires 1 type argument(s).
```

**Comment by dzearing** [comment]
Thanks guys. We have done the work already to move to TS2, but we found a few breaking changes slowing our move down. E.g. TS2 introduces readonly attributes in the d.ts files which TS1 can't understand. But we aggressively want to move to TS2 so this will happen very soon and this will be cleaned up. I'll assign to myself to ensure we're not blocked.

**Comment by Djemel** [comment]
Is there a temporary workaround for this issue ?

**Comment by unindented** [comment]
@dzearing how is progress looking? Anything we can do to help?

**Comment by dzearing** [comment]
PR is here.
https://github.com/OfficeDev/office-ui-fabric-react/pull/443

**Comment by dzearing** [comment]
Merged, published as 0.62.0. @unindented @kollster let me know if you see any issues.

**Comment by unindented** [comment]
@dzearing this is working fine for me. Thank you very much for your hard work! 😄

**Comment by hitendramalviya** [comment]
Hi @unindented  how did you get this working I am still getting issues:
`ERROR in D:\git\sampleApp\node_modules\office-ui-fabric-react\node_modules\@types\react\in
dex.d.ts
(2473,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'data' must be of
 type 'HTMLProps<HTMLElement>', but here has type 'HTMLProps<HTMLElement>'.
 
ERROR in D:\git\sampleApp\node_modules\office-ui-fabric-react\node_modules\@types\react\in
dex.d.ts
(2474,13): error TS2403: Subsequent variable declarations must have the same type.  Variable 'datalist' must b
e of type 'HTMLProps<HTMLDataListElement>', but here has type 'HTMLProps<HTMLDataListElement>'.
`

**Comment by unindented** [comment]
@hitendramalviya What version of `@types/react` are you using?

**Comment by hitendramalviya** [comment]
I am using `"@types/react": "^15.0.1"` anyway with latest version of `office-ui-fabric-react` they have removed typing of react from dependency so no problem now there is only one type definition for react i.e.  `@types/react`.

**Comment by turbo** [comment]
Still getting these errors with Docker CE on ubuntu. Not with Docker on Windows though! Built a React project, using office fabric based on the node:latest image.
