### ISSUE TITLE
[Meta] How can we contribute to office-ui-fabric-react/wiki?

### ISSUE THREAD

**Issue by russgove** [OfficeDev/office-ui-fabric-react#3823]
I forked the repo, bit the wiki dies not come with it. I'd like to contribute some  docs on what I have learned so far to make it easier for others getting started

**Comment by Jahnp** [comment]
Hey @russgove, sorry for the delay! We'd love for you to be able to share your learnings as well, but unfortunately the wiki is not quite set up for non-collaborator contributions just yet. We may need to look into doing something like [what VSCode did for their wiki](http://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html), which would involve setting up a separate repo that syncs with office-ui-fabric-react's wiki. We'll look into this soon! Thanks so much for looking for ways to contribute to Fabric :)

**Comment by russgove** [comment]
any update on this

**Comment by Jahnp** [comment]
Hi @russgove, sorry for the delay--unfortunately not yet. We'd still like to get to this but I can't commit to a timeline right now.
