### ISSUE TITLE
Persona pill icon/profile pic alignment is wrong

### ISSUE THREAD

**Issue by AsaPefferman** [OfficeDev/office-ui-fabric-react#3830]
### Bug Report

- __Package version(s)__: firefox and chrome, potentially others
- __Browser and OS versions__: mac
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? 
No

Requested priority:
low

Products/sites affected:
Sharepoint

#### Describe the issue:

The circular icon/profile picture in the persona pill is not aligned correctly to the rest of the pill. 

#### Actual behavior:

![image](https://user-images.githubusercontent.com/35933779/35528559-1337bb6e-04e3-11e8-8404-8516231fd06e.png)

#### Expected behavior:

According to the XD file the icon should be flush with the entire height of the pill

**Comment by battletoilet** [comment]
Hi @AsaPefferman, thanx for the issue. We are looking into it.

**Comment by lynamemi** [comment]
I'll try to find a mac to look into this. There is also a PR out that tweaks Persona Coin root size - I'll look to see if that makes an impact.

**Comment by lynamemi** [comment]
@betrue-final-final is going to help me check it out

**Comment by lynamemi** [comment]
@mikewheaton too!

But first will see if this change helps:
https://github.com/OfficeDev/office-ui-fabric-react/pull/3845

**Comment by mikewheaton** [comment]
I'm unable to repro this on macOS using Chrome, Firefox, or Safari. To attempt to repro I'm just adding a person to the [PeoplePicker](https://developer.microsoft.com/en-us/fabric#/components/peoplepicker).

**Comment by AsaPefferman** [comment]
I just double checked to make sure that some update hadnt fixed it and I am still seeing the problem in chrome, firefox, and safari on mac.

This instance is a SP list form if that makes a difference.

![untitled-2](https://user-images.githubusercontent.com/35933779/35696800-496a68c4-073d-11e8-887d-be53cfaacaf1.png)

**Comment by betrue-final-final** [comment]
This could be a SharePoint issue. @stanleyymsft?

**Comment by betrue-final-final** [comment]
@stanleyymsft, looks like we have a font substitution on "Add attachments".

**Comment by oengusmacinog** [comment]
I am not able to repro in the latest version of Fabric.  Closing for now, but if you see this issue again please open a new issue.
