### ISSUE TITLE
Provide types for string literals such as "Waffle"

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [OfficeDev/office-ui-fabric-react#3841]
```tsx
import { IconButton } from "office-ui-fabric-react";

<IconButton iconProps={{ iconName: "Waffle" }} />
```

The "Waffle" context there doesn't give much intellisense. I'd be useful to instead have some sort of constant list so we can view them all in our IDEs and get auto-complete.

```tsx
import { IconButton, iconNames } from "office-ui-fabric-react";

<IconButton iconProps={{ iconName: iconNames.waffle }} />
```

**Comment by dzearing** [comment]
Hey @JoshuaKGoldberg . We've evaluated this a few times and haven't found a great solution that has no consequences.

If we include the IconNames dictionary to make this more straightforward, it ends up adding about 5k of bundle bulk. People do want type safety and simplicity, but also performance. We have been aggressive about reducing overall bloat, so dropping in a giant enum when you only need one string doesn't make a lot of sense.

If you have a handful of icon names you use, you're welcome to put these in your own consts, which will result in a smaller bundle size.

**Comment by JoshuaKGoldberg** [comment]
What about const enums?

```typescript
const enum IconButton {
    Waffle = "Waffle",
}

console.log(IconButton.Waffle);
```

**Comment by dzearing** [comment]
We already have these in this location:

```tsx
import { IconNames } from '@uifabric/icons';
console.log(IconsNames.Waffle);
```

But it seems that referencing the definitions from d.ts only does not inline the result and you end up with a runtime error where IconNames is undefined.

**Comment by dzearing** [comment]
I had tested using these from awesome-typescript-loader and ran into issues, but then tried using tsc and all's well. I believe there may be some settings required in webpack loaders to expand const enums into literals.

**Comment by hmafzal** [comment]
@dzearing do you know what those settings may be? I'm trying to use IconNames but during runtime IconNames seems to be undefined

**Comment by dzearing** [comment]
https://github.com/s-panferov/awesome-typescript-loader/issues/137

**Comment by dzearing** [comment]
You can also import these like so: 

```tsx
import { IconNames } from 'office-ui-fabric-react/lib/Icons';
```

**Comment by dzearing** [comment]
I tried this in our `apps/todo-app` and it resolves correctly. I believe this is the magic:

tsconfig.json:
```json
    "preserveConstEnums": true,
```

**Comment by dzearing** [comment]
Going to close this one, please let us know again if you have issues.
