### ISSUE TITLE
DetailsList: Very slow performance when there are multiple instances.

### ISSUE THREAD

**Issue by jordandrako** [OfficeDev/office-ui-fabric-react#3853]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: Windows, chrome, edge, IE11

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High

#### Describe the issue:

On the [DetailsList example page](https://developer.microsoft.com/en-us/fabric#/components/detailslist) or where there are many instances of DetailsList, the performance is taking a huge hit. This may be relevant https://github.com/OfficeDev/office-ui-fabric-react/issues/3790#issuecomment-360213990

#### Actual behavior:

Page slows down, clicks are delayed, resizing takes forever, etc.

#### Expected behavior:

Better performance

**Comment by ProTip** [comment]
Looking at the example page now this appears to be resolved?

**Comment by jordandrako** [comment]
The page is still jittery and slow to load virtualized pages within details list, but we figure it's because there are a lot of examples with many thousands of rows being calculated, so there is currently a PR to separate the examples into sub-pages to see if that fixes it. I'll close this if it does.

**Comment by OneCyrus** [comment]
well there is something broken with the re-rendering logic. there are way too many rerenderings while scrolling in a list.
