### ISSUE TITLE
[Picker][TagPicker][Firefox] Focus does not visible on editable combo box once you add a tag

### ISSUE THREAD

**Issue by aadhars** [OfficeDev/office-ui-fabric-react#3859]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: Firefox

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable): All consumers of Tag picker on firefox

#### Describe the issue:

After adding tags, keyboard focus is not visible on "Tags" editable combo box field when navigating through keyboard.

Repro:(In firefox only)

1.Go to Tag picker
2. Add a tag.
3. Navigate out of picker by pressing tab.
4. Now try to reach back to picker through shift+Tab
5 Focus is not visible the focus is on editable combo box

#### Actual behavior:

After adding tags, keyboard focus is not visible on "Tags" editable combo box field when navigated through keyboard

#### Expected behavior:

Keyboard focus should be visible on "Tags" editabled combo box after adding tags too.

### If applicable, please provide a codepen repro:

https://developer.microsoft.com/en-us/fabric#/components/pickers

![image](https://user-images.githubusercontent.com/29277148/35666555-89399c50-0750-11e8-8609-599b827e6576.png)

**Comment by lambertwang** [comment]
I'm failing to reproduce the issue. What version of Firefox are you on and what how does the picker appear for you on different browsers?
![fail to repro](https://user-images.githubusercontent.com/6496608/35696516-98e45c4e-073c-11e8-9857-8ef67fc6d134.png)

**Comment by michaelangotti** [comment]
@aadhars We believe this was a temporary issue at the time it was opened and will  close the issue at this time. If it still repros for you, please open a new bug.
