### ISSUE TITLE
Disabled command button still shows hand cursor when user hovers over it

### ISSUE THREAD

**Issue by junchen1** [OfficeDev/office-ui-fabric-react#386]
I'm using react fabric version 56.0.

**Comment by dzearing** [comment]
I don't repro this.

Can you trace down the css style causing the issue you're seeing and make a PR?

**Comment by junchen1** [comment]
Please login you ms account using:https://outlook-sdf.office.com/owamail/?branch=junchen2016-junchen-react3

Find an email with two attachments & see the label button under two attachments

**Comment by dzearing** [comment]
So i used chrome, inspected it, and it seems there is this rule somewhere:

```css
button {
  background: transparent;
  cursor: pointer!important;
}
```

This is defined in `https://owamail.blob.core.windows.net/owamail-branch/junchen2016-junchen-react3/resources/styles/style.min.css`

I see only 1 single "!important" in all the fabric-react css in MessageBar. (And that should be removed!)

I suspect this is somewhere in your product code. Can you search for "!important"?

**Comment by junchen1** [comment]
Thanks a lot for catching it! Yep, it is caused by a wrong global css. I'll remove it.
