### ISSUE TITLE
Why lack of pagination the must-have basic component?

### ISSUE THREAD

**Issue by sackery** [OfficeDev/office-ui-fabric-react#3861]
It's hard to imagine that frontend ui package absence pagination!
Most of react ui compnent packages must include most basic component it's pagination.
like: bootstrap, semantic-ui.

Fabric is good, but without pagination and some other simple concept, such Sidebar, Navbar, Pagination...

**Comment by betrue-final-final** [comment]
Hey @sackery, we'd love to know exactly what you mean by pagination. Do you mean a standalone page control, or something integrated into one of the other components? We do have a Nav component https://developer.microsoft.com/en-us/fabric#/components/nav

**Comment by lambertwang** [comment]
Closing due to duplicate issue: New Component: Pagination #349
