### ISSUE TITLE
Spinner: Reduce specificity of styles

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#3865]
### Bug Report

- __Package version(s)__: Latest
- __Browser and OS versions__: All

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Maybe

Requested priority: Low

Products/sites affected: Unsure

#### Describe the issue:

The [styles for Spinner](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Spinner/Spinner.scss#L23) use a parent selector:

```
.root {
  > .circle {
```

There is no comment to indicate if/why this is needed, and it results in overly-specific CSS that is difficult to override.

### If applicable, please provide a codepen repro:

https://codepen.io/mikewheaton/pen/gvaZjz?editors=0110

**Comment by michaelangotti** [comment]
@mikewheaton This should no longer be an issue. Will close this issue.
