### ISSUE TITLE
Nav: Keyboard support

### ISSUE THREAD

**Issue by tx4x** [OfficeDev/office-ui-fabric-react#3871]
Hi,
are there any plans to add keyboard support to <Nav> and <CommandBar> ? If not, do you have some pointers how to add this myself ? I am not sure about the other components since I am a newbie to fabric-ui but I guess I need a general solution to add this everywhere.

Thanks in advance!

**Comment by betrue-final-final** [comment]
Thanks for teaching out. All Fabric components should have keyboard support. This one in particular should use arrow keys for navigating between items.

What exactly is missing?

**Comment by tx4x** [comment]
@betrue-final-final you're right, something was wrong on my end. thanks for the heads up!
