### ISSUE TITLE
Allow customization of ChoiceGroup styles

### ISSUE THREAD

**Issue by nappy** [OfficeDev/office-ui-fabric-react#3872]
The ChoiceGroup component should accept a styles prop, allowing to override internal styles (such as root, choiceField, choiceFieldWrapper etc.) like the CheckBox component does. Ideally for each field individually as well.

Currently, its not possible to change for example the the margins between the fields.
Also I am having the issue that I cant make the wrapper 100% width for my use case.

**Comment by hungdluit** [comment]
+1
same issue in my case.

**Comment by nappy** [comment]
Since this is still an issue for me, I pleasantly provide some activity. ;)

**Comment by manubamba** [comment]
I have just started work on passing `styles` to choiceGroup. Hope to have a PR out soon.

**Comment by Jahnp** [comment]
That's awesome @manubamba! Although heads-up--I believe someone here (not sure of their GitHub alias) is working on converting ChoiceGroup to `mergeStyles`, which should help here. Also adding @srideshpande as ChoiceGroup codeowner.

**Comment by Jahnp** [comment]
Confirmed, it sounds like @FalseLobster is working on this.
