### ISSUE TITLE
Can no longer edit controlled TextField

### ISSUE THREAD

**Issue by amygl** [OfficeDev/office-ui-fabric-react#3876]
### Bug Report

- __Package version(s)__: office-ui-fabric-react v5.45.2
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: Planner

#### Describe the issue:

After syncing to office-ui-fabric-react v5.45.2 no longer able to edit controlled text fields.
Looks like the cause is https://github.com/OfficeDev/office-ui-fabric-react/commit/b17a45fe057f50aa489be21d3e517d783b40b9e1
This change was released as a patch change but the commit description said it was a breaking change.

#### Actual behavior:

Controlled text fields are readonly

#### Expected behavior:

Controlled text fields should be editable.

**Comment by mikewheaton** [comment]
This was later reverted in another PR: https://github.com/OfficeDev/office-ui-fabric-react/pull/3854

I'm not sure if the latest release includes the reversal, or if you'll need to wait for the next version.
