### ISSUE TITLE
mergeStyles: lineHeight: 1 outputs line-height: 1px.

### ISSUE THREAD

**Issue by jordandrako** [OfficeDev/office-ui-fabric-react#3879]
### Bug Report

- __Package version(s)__: latest

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: Fabric mergeStyles

#### Describe the issue:

When converting scss with line-height properties without a unit such as `line-height: 1`, into `lineHeight: 1`, mergeStyles appends 'px' units.

#### Actual behavior:

`lineHeight: 1` returns `line-height: 1px;`
`lineHeight: '1'` returns `line-height: 1;`

#### Expected behavior:

`lineHeight: 1` should return `line-height: 1;`

### If applicable, please provide a codepen repro:

https://codepen.io/jordandrako/pen/pagOEO?editors=1111

**Comment by mikewheaton** [comment]
Reopening this issue, as #3886 had to be reverted.
