### ISSUE TITLE
[DetailsList] Error: Objects are not valid as a React child (found: object with keys {}). when rendering undefined element in groupedList

### ISSUE THREAD

**Issue by akashperfect** [OfficeDev/office-ui-fabric-react#3888]
### Bug Report

- __Package version(s)__: 5.46.0
- __Browser and OS versions__: Windows10, Chrome

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/sites affected: VSTS

#### Describe the issue:

**DetailsList** component has this prop to provide a callback when missing item is rendered called (onRenderMissingItem). 
Usage: We are appending an undefined element at the end of our list of items to be shown in detailsList groupedBy Date (something of this sort 
![image](https://user-images.githubusercontent.com/2953096/35849798-d4e6792e-0b48-11e8-974f-38508488f44b.png)
)

Lately from past 3 weeks there is an error coming when the following events occur in order
- the undefined element gets rendered along with group
- onRenderMissingItem callback is called
- using setState to remove the undefined element from itemsList and render the list with available results

```
Error: Objects are not valid as a React child (found: object with keys {}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `List`.
at r (VM17643 react-dom.min.js:15)
    at o (VM17643 react-dom.min.js:15)
    at i (VM17643 react-dom.min.js:15)
    at Object.instantiateChildren (VM17643 react-dom.min.js:13)
    at h._reconcilerInstantiateChildren (VM17643 react-dom.min.js:14)
    at h.mountChildren (VM17643 react-dom.min.js:14)
    at h._createInitialChildren (VM17643 react-dom.min.js:13)
    at h.mountComponent (VM17643 react-dom.min.js:13)
    at Object.mountComponent (VM17643 react-dom.min.js:14)
    at h.mountChildren (VM17643 react-dom.min.js:14)
```

#### Actual behavior:

On appending an undefined element to the list groupedBy colors its giving an error. _Please open console in below codepen to see the error occuring_
Codepen example: https://codepen.io/anon/pen/qxNwQW
![image](https://user-images.githubusercontent.com/2953096/35850048-99803720-0b49-11e8-8f99-6cfd7a1b8b13.png)

#### Expected behavior:

There should be no error, it should just render the list without the undefined element as that is removed from the final list.

### codepen repro:

https://codepen.io/anon/pen/qxNwQW

**Comment by lambertwang** [comment]
Changing the return of the `onRenderMissingItem` callback from `{}` to `undefined` seems to stop the error.

**Comment by akashperfect** [comment]
The given suggestion resolved the issue, what seems to have regressed is because of React update
