### ISSUE TITLE
Dropdown - Uncaught Exception in Layer.componentDidMount()

### ISSUE THREAD

**Issue by vaalgrind** [OfficeDev/office-ui-fabric-react#3890]
### Bug Report

- Package version(s): "^5.46.0"
- _Browser and OS versions_: (All)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Blocking) 

#### Describe the issue:

I copy dropdown example from documentation. When I clicked it, in console appear error.
![przechwytywanie](https://user-images.githubusercontent.com/16843232/35853971-4c9c9634-0b2f-11e8-97a3-e85b41d0c2d9.PNG)

Gif with behavior: https://giphy.com/gifs/3ohjUUB6nR9WCtzStG/fullscreen
My package.json
[https://ideone.com/RUK59F](url)

My tsconfig:

[https://ideone.com/FHcAFn](url)

Is problem with my project settings or this component ? 
Cheers

**Comment by KevinTCoughlin** [comment]
@vaalgrind thank you for your report. I'm unable to repro this behavior in `5.126.0` with the `<Dropdown/>` component. Here is the Codepen I'm using to test: https://codepen.io/kevintcoughlin/pen/bxymYG?editors=1010

Are you able to still repro? If so can you advise me how to get a repro in isolation, ideally in a Codepen.
