### ISSUE TITLE
[TextField]  Custom value for attribute componentId  don't work in TextField

### ISSUE THREAD

**Issue by IASamoylov** [OfficeDev/office-ui-fabric-react#3895]
### Bug Report

- __Package version(s)__: 5.24.0
- __Browser and OS versions__:  all

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes)

Requested priority: Normal

#### Describe the issue:

In [Docs](https://developer.microsoft.com/en-us/fabric#Implementation) props [ITextFieldProps](https://github.com/OfficeDev/office-ui-fabric-react/blob/hotfix/office-ui-fabric-react/5.29.2/packages/office-ui-fabric-react/src/components/TextField/TextField.types.ts) contains attribute "componentId", but in component [TextField](https://github.com/OfficeDev/office-ui-fabric-react/blob/hotfix/office-ui-fabric-react/5.29.2/packages/office-ui-fabric-react/src/components/TextField/TextField.tsx) attribute "componentId"  always replaced of the this._id (line 151)

#### Actual behavior:

`const renderProps: ITextFieldProps = { ...this.props, componentId: this._id };`

#### Expected behavior:

```
let {
    componentId = this._id
} = this.props;

const renderProps: ITextFieldProps = { ...this.props, componentId };
```

### If applicable, please provide a codepen repro:

- [jsFiddle bug](https://jsfiddle.net/u4wez9qv/1/)
- [jsFiddle fix](https://jsfiddle.net/e0s16Lyg/)

**Comment by lambertwang** [comment]
Sorry, I probably should've asked this question before I made the PR.  
Do we want to expose the internal componentId and allow users to set it via props, or do we want to keep componentId internal and remove it from the props?

**Comment by IASamoylov** [comment]
@lambertwang, I think logic written in docs doesn't need any changes

**Comment by IASamoylov** [comment]
@lambertwang, and I think it's right to let developers install IDs from the elements. It can be useful for auto tests.
