### ISSUE TITLE
SPFx -Error when use last version of Office-UI-React with SPFX 1.4.0

### ISSUE THREAD

**Issue by geogikk92** [OfficeDev/office-ui-fabric-react#3908]
I want to use last version of Office-UI-React with SharePoint Framework v 1.4.0 with TypeScript Version 2.2.2.

When i install last version office-UI-React have following error:

![untitled](https://user-images.githubusercontent.com/14110861/35912482-64f15784-0c05-11e8-841f-3487006945ef.png)

**Comment by manishgarg1** [comment]
Hi @geogikk92, can you please try to upgrade the typescript version and see if that fixes the issue? We believe this error could be related to the typescript version you have.

**Comment by rgylesbedford** [comment]
When using SPFx for SharePoint 2016, we are stuck with an older version of typescript. SPFx will not allow us to upgrade to a newer version.
