### ISSUE TITLE
List: re-evaluate windows on element resize

### ISSUE THREAD

**Issue by SumiranAgg** [OfficeDev/office-ui-fabric-react#3917]
### Bug Report

- __Browser and OS versions__: Microsoft Edge 41.16354.1001.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: VSTS

#### Describe the issue:

On zoom (>=200%), few items are missing at the end of the list. (Usually few ms-List-pages are missing from the end)
This also results in wrong SizeOfSet value in inspect tool to the observer, as only few items are visible and SizeOfSet shows actual list size.

#### Actual behavior:

Few items are missing and blank space appears instead.

#### Expected behavior:

All items should be visible.

**Comment by jordandrako** [comment]
I'm not seeing this behavior on our [example page](https://developer.microsoft.com/en-us/fabric#/components/list). I do see the container frames add their own scrollbars, though, resulting in having to scroll more than one box to get to the end of the list. Is that maybe what you're referring to?

If not, could you provide an example?

**Comment by Jahnp** [comment]
@cschleiden can you help us understand if this is an issue with the List or with VSTS? We're having a tough time reproing, both on the Fabric site and in a few lists in VSTS.

**Comment by cschleiden** [comment]
@Jahnp I can't repro either. @SumiranAgg can you please provide more details?

**Comment by SumiranAgg** [comment]
@Jahnp The issue appears when there is no vertical scrollbar.
For instance in first example on link: https://developer.microsoft.com/en-us/fabric#/components/list
If you remove max-height prop div class "ExampleCard-example x-hidden-focus", only 143 items are visible from 4999 items.

**Comment by cschleiden** [comment]
If you do this, the list doesn't know that its viewport changed.

**Comment by SumiranAgg** [comment]
So is it recommended to use max-height if the list is large?

**Comment by dzearing** [comment]
It is possible to use element resize to get a javascript callback when this occurs. But this could introduce other perf issues.

**Comment by dzearing** [comment]
https://unpkg.com/element-resize-detector@1.1.14/dist/element-resize-detector.js
