### ISSUE TITLE
CommandBar: Clicking Top Level Item In List Refreshes The Page

### ISSUE THREAD

**Issue by TBag** [OfficeDev/office-ui-fabric-react#392]
Issue:
Implement a command bar and add more than one child item to a top level item. Click a top level item in the command bar and see the child items appear, then the the page immediately refreshes. 

Expected behavior:
Implement a command bar and add more than one child item to a top level item. Click a top level item in the command bar and see the child items appear. 

Fabric Core version:  4.0.0.0
Office UI Fabric React Components Version: 0.56.1

Code to replicate issue:

```
.commandBar i{
display: none;
}

const commandBarItems = this._generateCommandBarItems();

public render(): JSX.Element {
return (
      <div className={styles.opportunityTracker}>
        <div className={styles.container}>
          {/* filter bar */}
          <div className="ms-Grid-row">
            <div className={css("ms-Grid-col ms-u-sm12", styles.commandBar)}>
              <CommandBar
                isSearchBoxVisible={ false }
                searchPlaceholderText='Search...'
                elipisisAriaLabel='More options'
                items={ this.state["commandBarItems"] }
                />
            </div>
          </div>

private _generateCommandBarItems(): Array{
const contextualMenuItems: Array = [];

//Sort
contextualMenuItems.push({
  key: 'Sort',
  name: 'Sort',
  icon: 'sortLines',
  onClick: (item: IContextualMenuItem, ev: React.MouseEvent) : void => {ev.preventDefault();},
  items: [
    {
        key: 'ALPHABETICAL',
        name: 'ALPHABETICAL',
        onClick: (item: IContextualMenuItem, ev: React.MouseEvent) : void => {
          this.setState({
            //replace setting the state with react add-ons update
            //npm i react-addons-update
            //let update = require{'react-addons-update'};
            opportunities: this._sortAndFilterOpportunities(item.key, this.state["statusSelectedKey"], this.state["ownerSelectedKey"]),
            sortedBySelectedKey: item.key
          });
          ev.preventDefault();
        }
    },
    {
        key: 'FORECAST DATE',
        name: 'FORECAST DATE',
        onClick: (item: IContextualMenuItem, ev: React.MouseEvent) : void => {
          this.setState({
            opportunities: this._sortAndFilterOpportunities(item.key, this.state["statusSelectedKey"], this.state["ownerSelectedKey"]),
            sortedBySelectedKey: item.key
          });
          ev.preventDefault();
        },
        isChecked: true
    }
  ]
});
```

**Comment by TBag** [comment]
@joschect Here's the new issue for the page refresh issue we discovered yesterday.

**Comment by TBag** [comment]
@joschect Notice the two parameters of the onClick event in the screenshot below, the definition of the event is “(ev?: React.MouseEvent, item?: IContextualMenuItem) => void”,  but actually the sequence is opposite as we fixed it in the second screenshot.  It works after our fix but it doesn’t make sense that the input parameter type is different from the interface definition.  Is this a bug in the Office UI React Component code?

![392-1](https://cloud.githubusercontent.com/assets/1407310/19221215/d0c4649c-8e0c-11e6-875b-b2b6e60a7298.png)

![392-2](https://cloud.githubusercontent.com/assets/1407310/19221216/d6c4a1a4-8e0c-11e6-9200-251860054c93.png)

**Comment by joschect** [comment]
@TBag Hey! This isn't a bug, although it is confusing and probably needs some cleanup. The ContextualMenuItems are different from the command bar items. The code you javascript snippet you posted from the developers console is on the [CommandBar](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/src/components/CommandBar/CommandBar.tsx). The onClick function you posted below that goes into the [ContextualMenu](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/src/components/ContextualMenu/ContextualMenu.tsx). The command bar items appear to be executing the clicks with item, event, while the contextual menu item does ev, item. 

Again this definitely needs to be more standard.

-Jon

**Comment by TBag** [comment]
@joschect Gotcha.  Thanks for explaining it.  Do you think you will make them both the same in the future?  I think we can close this issue now.  Do you agree?

**Comment by joschect** [comment]
@TBag Yes, I think it is likely that we will try to make them the same in the futre. I do think that we can close this issue!

-Jon

**Comment by joschect** [comment]
@TBag I was mistaken, since it's an internal onClick that's being called it won't always be of the form ev, item. It's only for outward facing onClicks (like in props) that we'll always have ev, item.

-Jon
