### ISSUE TITLE
Broken Roadmap link on Contributing Readme

### ISSUE THREAD

**Issue by paterasMSFT** [OfficeDev/office-ui-fabric-react#3920]
The [Contributing Readme](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/ghdocs/CONTRIBUTING.md) says:

>Right now, the project is in a pre-v1 state, so we're mainly driving torwards the goals outlined in the [roadmap](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/ghdocs/ROADMAP.md). With this in mind, feel free to file bugs but new components or additional features will probably not be considered to be executed on until after the v1 state is reached.

The link to the roadmap is broken. I noticed that the above was removed from the home Readme ([see here](https://github.com/OfficeDev/office-ui-fabric-react/pull/2264)). Should the same be done on the contributing document, as well? If not, that link should be fixed.

I'd be happy to submit a PR, either way.

**Comment by jordandrako** [comment]
I think that's a reasonable change, feel free to submit a PR. Thanks!

**Comment by paterasMSFT** [comment]
Tried pushing a remote branch. Seems I lack permissions. Do I need to be added as a contributor or something?

**Comment by Jahnp** [comment]
Thanks for reporting this, @paterasMSFT! For now, we went ahead and cleaned up that whole paragraph (it was a little out of date), and will be adding an updated roadmap soon. I'll go ahead and close this for now.
