### ISSUE TITLE
Make Pivot a controlled component

### ISSUE THREAD

**Issue by justinmwarner** [OfficeDev/office-ui-fabric-react#3931]
### Bug Report

- __Package version(s)__: 5.39.0
- __Browser and OS versions__: N/A

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes - just need sign off

Requested priority: Low

Products/sites affected: Analytics

#### Describe the issue:

We have CheckBox which is controllable by props. I'd like to add this same functionality to the Pivot so we can completely control it via props.

#### Actual behavior:

The callback for when a pivot item is selected gets called after the state. The Pivot control also doesn't take prop as a trump value, instead state always wins so we can never control it.

#### Expected behavior:

State only wins when the prop isn't being controlled.

### If applicable, please provide a codepen repro:

N/A

**Comment by justinmwarner** [comment]
@dzearing is this okay to start? Currently we're using a hack to get around this limitation and it seems this would follow much of what Fabric already does.  Thanks!

**Comment by michaelangotti** [comment]
@justinmwarner I think you can start working on this one.

**Comment by justinmwarner** [comment]
This is a no-op. It works as expected in the current version and an example is also checked in of it working. Not sure why we couldn't get it working before. Closing.
