### ISSUE TITLE
Icon button: Need primary button

### ISSUE THREAD

**Issue by suztocco** [OfficeDev/office-ui-fabric-react#3933]
### Bug Report

- __Package version(s)__: N/A
- __Browser and OS versions__: N/A

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Any workload that wants a simple primary button
#### Describe the issue:

Right now there is only 1 icon button. It starts as neutral then goes to a darker theme and then lighter theme (not sure why it goes lighter on press....). Anyways, we would like a "Primary"version of this button.

#### Actual behavior:

Button does not exist

#### Expected behavior:

To have a primary icon button that starts as the "theme" color and has proper interactive color states.

### If applicable, please provide a codepen repro:

Icon button today: 

![image](https://user-images.githubusercontent.com/20954039/36007002-2360a39c-0cf5-11e8-9058-0670ce0787f3.png)

New button requested: Ben Truelove to provide pure spec

![image](https://user-images.githubusercontent.com/20954039/36007018-3db32120-0cf5-11e8-87c2-2df66705d5b2.png)

**Comment by suztocco** [comment]
Can someone work on this so it isn't closed by the bot?

**Comment by betrue-final-final** [comment]
We still need this. @suztocco since you commented, it's no longer stale.

**Comment by Jahnp** [comment]
Just a heads-up--is being addressed in #4695. Thanks @Markionium! I'm going to assign this to you for when that PR is merged.
