### ISSUE TITLE
[Nav] Expand icon hides item icon

### ISSUE THREAD

**Issue by IRRDC** [OfficeDev/office-ui-fabric-react#3945]
#### Describe the issue:
When a link is expandable icons are not displayed. The expand/collapse icon is in the same position as the icon of the item and only one is displayed.

#### Actual behavior:
Only the expand/collapse icon is visible.

![actual](https://user-images.githubusercontent.com/11270504/36090548-0dfa1760-0fe1-11e8-8aa5-8d34d92a589f.png)

#### Expected behavior:
The expand/collapse icon and the icon set for the item should be visible next to each other.

![expected](https://user-images.githubusercontent.com/11270504/36090549-0e20b9d8-0fe1-11e8-8b92-d8551bcdcedd.png)

**Comment by lyyjohn45** [comment]
I have the same exact repo. this is super annoying.

**Comment by curtisrutland** [comment]
Has there been any motion on this? My thoughts are, if you accept an icon as an input, you should render that icon.

**Comment by frevds** [comment]
I suspect the "fix" for this issue caused this new issue: 

![image](https://user-images.githubusercontent.com/5341447/56624031-35998a00-6637-11e9-9e9f-6858e4c89a5a.png)

I'm posting a separate bug report for this one..
