### ISSUE TITLE
Strange tab positioning issues when focused and arrowing

### ISSUE THREAD

**Issue by lavanyasiv** [OfficeDev/office-ui-fabric-react#395]
Deployed the documentation locally, and saw this keyboard behavior (in chrome)

![reacttabs](https://cloud.githubusercontent.com/assets/22689654/19209287/0b732f9e-8cbc-11e6-909f-3ceaf18228ab.gif)

**Comment by dzearing** [comment]
Could you provide info on browser/os/version of fabric-react?

**Comment by dzearing** [comment]
Nevermind, repro'd, found it, fix is now checked in and will be published on the next bump > 0.59.0

**Comment by lavanyasiv** [comment]
Great, thank you David!
