### ISSUE TITLE
Disabled Dropdown text is not following high contrast color scheme in Firefox browser

### ISSUE THREAD

**Issue by niadak** [OfficeDev/office-ui-fabric-react#3958]
Bug Report
Package version(s): (fill this out)
Browser and OS versions: (fill this out if relevant)
Priorities and help requested (not applicable if asking question):
Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)
Normal
Products/sites affected: (if applicable)
VSTS

Describe the issue:
Disabled Dropdown text is not following high contrast color scheme in Firefox browser

**Comment by michaelangotti** [comment]
Firefox does not support High Contrast. Closing this issue.
