### ISSUE TITLE
ContextualMenu style overrides are missing and/or not working

### ISSUE THREAD

**Issue by MLoughry** [OfficeDev/office-ui-fabric-react#3966]
### Bug Report

- __Package version(s)__: 5.49.3

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Maybe, not familiar with writing the custom styles

Requested priority: Normal

Products/sites affected: OWA

#### Describe the issue:

A few issues with the custom styles for ContexualMenu
- All of `IContextualMenuStyles`'s properties are required, rather than being optional
- Regardless of above, styles passed in using the `styles` property are not actually applied
- While `IMenuItemStyles` is defined, there's no way to pass in a set of style overrides to `ContextualMenu` and have them apply to all items
    - Additionally, all of its properties are required, rather than optional.

**Comment by michaelangotti** [comment]
Closing this as it is a dup of #4169
