### ISSUE TITLE
[CommandBar] When disabled button is hovered, no message is shown

### ISSUE THREAD

**Issue by ankitk94** [OfficeDev/office-ui-fabric-react#3971]
### Bug Report

- __Package version(s)__: 5.48.1

#### Describe the issue:

We have a requirement to disable a button in command bar based on a condition and and we will be showing the cause why button was disabled using a tootip when user hovers over the button, which is shown if "title" is provided for items.

This is working fine if the button is enabled. But if the button is disabled, no tooltip or message is shown on hover.

#### Actual behavior:

![image](https://user-images.githubusercontent.com/6390909/36200952-52945d30-11a4-11e8-8b90-44ca1d30f540.png)

![image](https://user-images.githubusercontent.com/6390909/36200975-6757dab2-11a4-11e8-9fdf-21319586de9d.png)

No message shown when hovered on disabled button

### If applicable, please provide a codepen repro:

https://codepen.io/ankhokha/pen/dzBbyG?editors=1111

**Comment by Jahnp** [comment]
@lambertwang  can you take a look at this? Seems like this could be solved if you could remove `pointer-events: none` when the button has no `href` attribute.
