### ISSUE TITLE
onSelectionChanged not fired

### ISSUE THREAD

**Issue by tx4x** [OfficeDev/office-ui-fabric-react#3973]
Hi,
I am not sure I understood this right: 

```ts
this._selection = new Selection({
            onSelectionChanged: this._onSelectionChanged
});
```
won't fire this method when click an item, or move the keyboard focus within a list. Do I have to implement this behaviour myself ? 

thanks,
g

**Comment by aappddeevv** [comment]
It does work like that. Is your cb bound correctly?

**Comment by Jahnp** [comment]
@aappddeevv is right. You should be able to use the `@autobind` decorator to set the right scope for `this`. I'll go ahead and close this for now, but feel free to reopen if you feel there's a real issue here. Thanks!
