### ISSUE TITLE
Selection.onSelectionChanged should be mutable with getter/setters instead of only in the constructor

### ISSUE THREAD

**Issue by aappddeevv** [OfficeDev/office-ui-fabric-react#3974]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Y

Requested priority: Low

#### Describe the issue:
Sometimes I need to create the Selection object in different parts of the react lifecycle, I can't always get my callback handler into the right place when it has to be in the "constructor" of the Selection object. Since Selection is mutable anyway and there is no real logic tied to the callback, it would be nice to make this with a set/get so it can be manipulated/chained easier.

**Comment by dzearing** [comment]
For now we are going to pass on this one.

If you really need this, you can do this easily in your app code.

```tsx
class MyThing {
  constructor() {
    this._selectionChanged = () => {};
    this._selection = new Selection({ onSelectionChanged: () => this._selectionChanged() }); 
  }
```

Now at any point you can change your callback. I'm not sure it's necessary to expose a way to do this, it ends up just adding bytes to the code unnecessarily.
