### ISSUE TITLE
[SearchBox] should use the prop named placeholder instead of labeltext.

### ISSUE THREAD

**Issue by cslecours** [OfficeDev/office-ui-fabric-react#3977]
### Bug Report

- __Package version(s)__: 5.47.0
- __Browser and OS versions__: Any

Are you willing to submit a PR to fix? Yes

Requested priority: Low

Products/sites affected: The SearchBox Component

#### Describe the issue:

This doesn't work but compiles without error : 
`<SearchBox placeholder="My PlaceHolder" />`

But this works: 
`<SearchBox labelText="My PlaceHolder" />`

The placeholder is inherited from HTMLInputElement

`export interface ISearchBoxProps extends React.InputHTMLAttributes<HTMLInputElement> `

#### Actual behavior:

The placeholder prop is present, but doesn't do anything. The component rely on labelText which is different from what you would expect from an input component.

#### Expected behavior:

The SearchBox Component should use placeholder  prop.

**Comment by Jahnp** [comment]
This is a great catch, thanks for reporting @cslecours . We should be consistent with native input prop names here. What we should do is add `placeholder` and deprecate `labelText`. We'd welcome a PR if you're willing to the fix!

**Comment by cslecours** [comment]
@Jahnp  : Should I explicitely add placeholder to ISearchboxProps? For documentation purposes I think it would be better than relying on the HTMLInputElement interface.

**Comment by Jahnp** [comment]
Yeah, that sounds right, thanks for clarifying. I more meant that generally, we should make sure that prop names map as closely as possible to native prop names--helps ensure a consistent developer experience.
