### ISSUE TITLE
Narrator always speaking aloud table, grid details for Date time picker component

### ISSUE THREAD

**Issue by AkshanshSrivastava03** [OfficeDev/office-ui-fabric-react#3981]
### Bug Report

- __Package version(s)__: 5.46.1002
- __Browser and OS versions__: Edge + Narrator

#### Describe the issue:
When you go to the office fabric page for Date time picker component, the narrator, irrespective of where the focus is, speaks up the number of rows/columns etc. This is wrong behavior from accessibility point of view as narrator needs to speak this data only when the focus goes to this control.

#### Actual behavior:

 the narrator, irrespective of where the focus is, speaks up the number of rows/columns etc

#### Expected behavior:

 narrator needs to speak this data only when the focus goes to this control.

**Comment by Jahnp** [comment]
@betrue-final-final, can you take a look at this when you have a chance?

**Comment by betrue-final-final** [comment]
I tried this on the live site, and in master and didn't find the behavior described. Narrator spoke what I expected, when I expected it and no tables or cells were mentioned. If you see this again, feel free to reopen with more specific repro steps. Here is my Narrator Buddy output:
Select a date..., collapsed, menu,
Select the first day of the week, editable combo box,
Sunday, collapsed,
Sunday, <say-as interpret-as="spell">1</say-as> of <say-as interpret-as="spell">7</say-as>, selected, 
Select the first day of the week, editable combo box,
Show code, button,
Dialog Calender focus on February 16, 2018, selected, ,  
Tab
Calender, Go to today, button,
Select a date..., collapsed, menu,
Select a date..., collapsed, menu,
Select the first day of the week, editable combo box,
Windows
Exiting Narrator

**Comment by johannao76** [comment]
Adding @John Lorenz<mailto:jolore@microsoft.com>

________________________________

**Comment by AkshanshSrivastava03** [comment]
Hi 
As soon as I landed on the office fabric homepage, I was able to see this behavior in Narrator buddy:

Table Grid, has <say-as interpret-as="cardinal">46</say-as> rows, <say-as interpret-as="cardinal">20</say-as> columns,, <say-as interpret-as="spell">F4</say-as>, selected, editable, True / False, Row <say-as interpret-as="cardinal">5</say-as> of <say-as interpret-as="cardinal">46</say-as> Column <say-as interpret-as="cardinal">7</say-as> of <say-as interpret-as="cardinal">20</say-as> 
Home - Office UI Fabric, Hide code, button,
Scan Off
Enter
Enter
Table Grid, has <say-as interpret-as="cardinal">46</say-as> rows, <say-as interpret-as="cardinal">20</say-as> columns,, <say-as interpret-as="spell">F4</say-as>, selected, editable, True / False, Row <say-as interpret-as="cardinal">5</say-as> of <say-as interpret-as="cardinal">46</say-as> Column <say-as interpret-as="cardinal">7</say-as> of <say-as interpret-as="cardinal">20</say-as> 


My issue is that when I am not even at the date picker component, why is this information provided to me by the assistive technology. This information makes sense only if I am focussed on the date picker component which I am not as I have my focus on Show/Hide code button.
