### ISSUE TITLE
Styling: fillOpacity gets incorrectly convert to a px value

### ISSUE THREAD

**Issue by jspurlin** [OfficeDev/office-ui-fabric-react#3983]
### Bug Report

- __Package version(s)__: 5.50.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Office Online

#### Describe the issue:

When defining fillOpacity in a styles file, the number value gets incorrectly converted to a pixel value

#### Actual behavior:
`fillOpacity: 0.5` gets compiled to `fill-opacity: 0.5px`

#### Expected behavior:
`fillOpacity: 0.5` to get compiled to `fill-opacity: 0.5`

**Comment by Jahnp** [comment]
@jspurlin FYI you should be able to just use a string value for this, but @dzearing will be fixing this anyway.

**Comment by dzearing** [comment]
fixed
