### ISSUE TITLE
SpinButton styling is inconsistent with TextField

### ISSUE THREAD

**Issue by fuocor** [OfficeDev/office-ui-fabric-react#3984]
### Bug Report

- __Package version(s)__: 5.43.1
- __Browser and OS versions__: all
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No
Requested priority: Blocking
Products/sites affected: internal
#### Describe the issue:

the SpinButton input is rendered at 26px high when TextField's inputs are 30px.
additionally the input in the TextField as a 12px left and right pad but the SpinButton has a 4,4,3,3 pad

**Comment by Jahnp** [comment]
Seems reasonable--feels like those should be consistent. @jspurlin, is this something you could fix? @betrue-final-final for FYI

**Comment by betrue-final-final** [comment]
Makes sense. Also the pressed color of the tiny buttons should not be theme color, but the same as button's pressed state color.

**Comment by betrue-final-final** [comment]
![image](https://user-images.githubusercontent.com/20363037/36284554-e73ffc56-125c-11e8-90e1-27f3f9ef6a86.png)
