### ISSUE TITLE
ScrollablePane using setTimeout instead of _async.setTimeout

### ISSUE THREAD

**Issue by antonafMSFT** [OfficeDev/office-ui-fabric-react#3993]
### Bug Report

- __Package version(s)__: All versions
- __Browser and OS versions__: N/A

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: Anyone using the `ScrollablePane` component

#### Describe the issue:

When a `ScrollablePane` is unmounted before the timeout callback that is set in `componentDidMount` gets a chance to run, the callback will attempt to access `refs`, which are `null`, causing an exception to be thrown.
This does not break the app because the component has been unmounted already, but it does clutter the console and any exception handlers.

#### Actual behavior:

The global `setTimeout` is used, causing the timeout to run even if component has been unmounted already.

#### Expected behavior:

`_async.setTimeout` is used, ensuring the timeout is cleared when the component is unmounted.

### If applicable, please provide a codepen repro:

https://codepen.io/antonafMSFT/pen/VQrmOX?editors=1010
Repro:
Ensure console is open.
Click the Show/Hide button several times in a very quick succession.
Observer the null-reference exception.
The esception happens because the callback of `setTimeout` that is set in `componentDidMount` executes after the component has actually unmounted and the refs are all null.

**Comment by dzearing** [comment]
Great catch!

@battletoilet make sure to review.

**Comment by davsm** [comment]
This is the same issue as: https://github.com/OfficeDev/office-ui-fabric-react/issues/4012

PR to use _async.setTimeout: https://github.com/OfficeDev/office-ui-fabric-react/pull/4039#pullrequestreview-98066393

**Comment by antonafMSFT** [comment]
Never mind. Another change has been approved that does this same thing while this one was waiting for approval.
