### ISSUE TITLE
Experimental components setup

### ISSUE THREAD

**Issue by aslanovsergey** [OfficeDev/office-ui-fabric-react#3999]
Hello,

This is just a question. I found experimental component 'Form' which I would like to try to use it my SharePoint Framework WebPart project.
https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/experiments
But I can't make out how to set (install, configure) it for use. Readme at the page above says I need 
_import { ComponentName } from '@uifabric/experiments/lib/ComponentName';_
but my @uifabric module's folder doesn't contain 'experiments' sub folder (Is there any npm package for that?). I copied components from github rep to @uifabric folder and added them to my WebPart. After all I couldn't run the project because of many errors arising sequentially .

**Comment by oengusmacinog** [comment]
Hello, @aslanovsergey! We don't actually encourage the use of any of the components in the experiments package.  To be clear these are not beta components, they are actually in an experimental state. We do not support the use of these, and I strongly encourage you not to use this in a production app.

If there are features in the experiment you would like to see in Fabric, please feel free to open an issue about a feature request and it might help pushing that feature through to production.  Closing this issue for now.
