### ISSUE TITLE
Multiple warnings with React/React-Dom 15.2.1

### ISSUE THREAD

**Issue by mike-morrison** [OfficeDev/office-ui-fabric-react#4]
There appears to be issues when trying to use the library with 15.2.1.  I was getting a bunch of warnings in my app that were not appearing in the demo (gulp serve) app.  I bumped up the version of react and react-dom the demo is downloading from the CDN from 0.14.7 to 15.2.1 and the demo app started throwing the same warnings.

![image](https://cloud.githubusercontent.com/assets/6625993/17078768/989874f6-50c1-11e6-8f30-b4110ee1e2ed.png)

If I track it down, I'll post more info. So far the warnings are just cluttering up my console, nothing broken.  The warnings seem to be throwing across multiple pages so a lot of files might need to be updated.  The one page that I looked at appeared like the code was written exactly like the latest react docs said it should be written, but that was just a quick glance.

[Link to warning page in react docs](https://facebook.github.io/react/warnings/unknown-prop.html)

**Comment by mike-morrison** [comment]
Also a big :-1: on React showing me warnings in red.  I was having an issue and thought these were errors, so I started troubleshooting.  My eyes skipped the word Warning and went right for the error message.  So really my fault for not reading, but I am hard-coded to make red go away as soon as I see it.   

Turned out I had my TextField trying to use the onchange event instead of onchanged.  Onchange did nothing and onchanged works.  Figured that out by looking at the API docs included in the demo, so thank you for that.  :100: for having pretty solid docs and a very well written demo app at this early stage.

**Comment by dzearing** [comment]
Thanks for the heads up. We will keep this open to track. Right now we have been testing against 0.14.7 because we initially saw some performance concerns with 15.0.1. We will re-evaluate and address the warnings.

**Comment by dzearing** [comment]
All warnings from Button, Checkbox, and FocusZone have been addressed. We still have TextField left.

**Comment by dzearing** [comment]
These have been resolved.
