### ISSUE TITLE
Toggle not rendering correctly

### ISSUE THREAD

**Issue by ghempton** [OfficeDev/office-ui-fabric-react#400]
On Chrome 53.0.2785.143 (64-bit) and version `0.56.2` of this package, the `<Toggle>` component shows strange rendering behavior:

![image](https://cloud.githubusercontent.com/assets/8994/19251012/19d8318c-8ef2-11e6-8a6f-183e7f69fe46.png)

![image](https://cloud.githubusercontent.com/assets/8994/19251016/1e8c6496-8ef2-11e6-963e-6e76336f8ea0.png)

```
<div>
          <Toggle
            label="Toggle Test"
            onText="On"
            offText="Off"
            defaultChecked={true}
            />
        </div>
```

I am using browserify (via Systemjs) to consume the library. Is there something I am missing? I have also tried this on IE 11 and a few previous version of the library (going back about 2 months) and I am still seeing this issue.

**Comment by dzearing** [comment]
Do you have DIR='ltr' on your html element?

We require a dir attribute to be specified and to have either 'ltr' or 'rtl' specified to support left-to-right or right-to-left languages.

**Comment by dzearing** [comment]
Alternatively, import the "Fabric" component and wrap your app in that. That would be the recommended approach and will ensure the dir is provided.

https://github.com/OfficeDev/office-ui-fabric-react/issues/351

**Comment by ghempton** [comment]
That worked. Thanks, 👍 on more docs.
