### ISSUE TITLE
[BasePicker] onBlur prop isn't used

### ISSUE THREAD

**Issue by martellaj** [OfficeDev/office-ui-fabric-react#4000]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

#### Describe the issue:

There's a `onBlur` prop for `BasePicker`, but it doesn't seem to be respected. I looked at the `BasePicker` code, and I can't find any reference to it. Was it recently removed from component code, but not from the props interface? If so, was that intentional?

**Comment by martellaj** [comment]
@joschect I know you've done picker stuff recently. Aware of any changes that might be related?

**Comment by joschect** [comment]
It looks like it was added here https://github.com/OfficeDev/office-ui-fabric-react/commit/741bf74775697aa459121b4b1b81af7e44138991#diff-c88a174b6c194e2d439942d05cb8fb6c but never used. I don't believe it was removed recently.

**Comment by bratukham** [comment]
It seems like this event has never been raised.
Any updates when it will be fixed?
