### ISSUE TITLE
Tabbing through <TextField>-s in a <DetailsList> component

### ISSUE THREAD

**Issue by szmarci** [OfficeDev/office-ui-fabric-react#4001]
I have a `<DetailsList>` component with custom `<TextField>` cells inside.
I want to be able to tab to the next cell. I tried supplying `tabindex` property to `<TextField>`  with an incremential index number, but when it was rendered to the DOM the numbers became either `0` or `-1`.
How can I make these fields tab-able?

Thanks!

**Comment by dzearing** [comment]
You can arrow into cell content using the right arrow, but other than that, you would have to do custom row rendering.
