### ISSUE TITLE
How to use with create-react without typescript?

### ISSUE THREAD

**Issue by PrinzTu** [OfficeDev/office-ui-fabric-react#4002]
How can I use the Components along with Styling just with a "create-react" installation with no typescript. I get errors because of the imports of scss a

**Comment by nigelskeels** [comment]
Can you please provide examples that don't use typescript.
It's an unnecessary hurdle to using MS Fabric with react.

**Comment by michaelangotti** [comment]
@PrinzTu  This is on our radar and will be updated in a future release. Closing for now.

**Comment by jordandrako** [comment]
@PrinzTu @nigelskeels I've been working on both typescript and non-typescript codesandbox examples. Here is a quick example of PrimaryButton https://codesandbox.io/s/xo146lklyp

**Comment by nigelskeels** [comment]
Thanks Jordandrako
