### ISSUE TITLE
[Autofill] Add support for custom styles

### ISSUE THREAD

**Issue by martellaj** [OfficeDev/office-ui-fabric-react#4003]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

#### Describe the issue:

I'm in the process of making a custom picker component. In doing so, I want to style the input box (`Autofill` component), but there doesn't seem to be any support for that. Is there any reason why we can't add a `className` prop to allow overriding styles here? If not, I can do that work (and then will create a separate issue to allow styling the `Autofill` component in the context of `BasePicker`.

**Comment by michaelangotti** [comment]
@martellaj Would you be willing to submit a PR for this?

**Comment by michaelangotti** [comment]
@martellaj Checking in on this one. Are you still willing to open a PR?
