### ISSUE TITLE
ScrollablePane tries to getComputedStyle(root), but root is undefined (this.refs.root)

### ISSUE THREAD

**Issue by davsm** [OfficeDev/office-ui-fabric-react#4012]
### Bug Report

- __Package version(s)__: 5.50.0
- __Browser and OS versions__: chrome, windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes
Requested priority: Medium - only breaks tests, but is blocking our adoption of Fabric
Products/sites affected: internal MS

#### Describe the issue:

ScrollablePane._resizeContainer is using this.refs.root to call getComputedStyle(root), without checking for root for undefined, causing an exception.

The error occurs while running a QUnit acceptance test, with JSX code that is based on the DetailsList sticky header example.
```
render() {
    return (
        <Fabric.ScrollablePane ref="scrollablePane">
          <Fabric.MarqueeSelection selection={this.selection}>
            <Fabric.DetailsList
              items={this.state.items}
              columns={this.columns}
              setKey='set'
              selectionMode={Fabric.SelectionMode.single}
              onRenderDetailsHeader={this.stickyHeader}
              layoutMode={Fabric.DetailsListLayoutMode.justified}
              selection={this.selection}
              selectionPreservedOnEmptyClick={true}
            />
          </Fabric.MarqueeSelection>
        </Fabric.ScrollablePane>
    );
  }

```
#### Actual behavior:

office-ui-fabric-react.js:31188 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at ScrollablePane._resizeContainer (office-ui-fabric-react.js:31188)
    at office-ui-fabric-react.js:31092

#### Expected behavior:

Should not throw the exception 
(should not try to resize the container when this.refs.root is undefined)
(should probably also check if stickyContainer is undefined)

```
  private _resizeContainer() {
    const { stickyContainer, root } = this.refs;
    const { borderTopWidth, borderLeftWidth } = getComputedStyle(root);
    stickyContainer.style.height = root.clientHeight + 'px';
    stickyContainer.style.width = root.clientWidth + 'px';
    if (borderTopWidth) {
      stickyContainer.style.top = root.offsetTop + parseInt(borderTopWidth, 10) + 'px';
    }
    if (borderLeftWidth) {
      stickyContainer.style.left = root.offsetLeft + parseInt(borderLeftWidth, 10) + 'px';
    }
  }
```

**Comment by MertenK-HV** [comment]
+1 same issue here, please fix this
