### ISSUE TITLE
ComboBox box-sizing broken the bottom border

### ISSUE THREAD

**Issue by stephenzsy** [OfficeDev/office-ui-fabric-react#4015]
### Bug Report

- __Package version(s)__: 5.46
- __Browser and OS versions__: Chrome 64

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/sites affected: (if applicable)

#### Describe the issue:

looks this change https://github.com/OfficeDev/office-ui-fabric-react/commit/5c71bd92894505214a9a6df8c4fb9d8e43472d98 changed the box-sizing from "content-box" to "border-box" which causes the rending broken.

![image](https://user-images.githubusercontent.com/1330448/36347199-2c88bbae-1406-11e8-91b7-80bba56d8d7d.png)

**Comment by stephenzsy** [comment]
It is visible on the office fabric page now

**Comment by lynamemi** [comment]
We changed to border-box to align to TextField and Dropdown and to better support high contrast mode styles. I'll look into where that overlap is coming from.
