### ISSUE TITLE
TextField type=number does not display value 0

### ISSUE THREAD

**Issue by tommarien** [OfficeDev/office-ui-fabric-react#4019]
### Bug Report

- __Package version(s)__: office-ui-fabric-react@4.37.5
- __Browser and OS versions__: not relevant

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (High) 

#### Describe the issue:

When you set a value to a textfield type numeric of 0 it does not display, related to TextField.tsx the way it threats falsy values see

https://github.com/OfficeDev/office-ui-fabric-react/blob/33ea0dfb5d5fcb07e5a4f96ff278cf9149cbffee/packages/office-ui-fabric-react/src/components/TextField/TextField.tsx#L77

#### Actual behavior:

Textfield is empty or ''

#### Expected behavior:

Textfield shows value 0

**Comment by dzearing** [comment]
This is low hanging fruit and should be fixed.
