### ISSUE TITLE
Accessibility: Fix Contrast Ratio

### ISSUE THREAD

**Issue by Khushveerkaur** [OfficeDev/office-ui-fabric-react#4025]
### Bug Report

- __Package version(s)__: Latest
- __Browser and OS versions__: NA

#### Describe the issue:
During the Keros testing of our page for accessibility, it was found that the "ms-link"s do not meet the contrast ratio required for accessibility.

#### Actual behavior:

Foreground: #0078d7 
Background: #ffffff 
Contrast ratio: 4.49 
Text size: 9.8pt (regular)

#### Expected behavior:

Regular text must have a contrast ratio of at least 4.5:1.

![image](https://user-images.githubusercontent.com/36656468/36412885-0dcadec0-1642-11e8-89dc-6fc7fc84a6d0.png)
![image](https://user-images.githubusercontent.com/36656468/36412899-1b29072c-1642-11e8-80a3-8f9e615edec8.png)

**Comment by lynamemi** [comment]
I think this fix is in progress - @betrue-final-final , can you confirm?

**Comment by betrue-final-final** [comment]
This is a larger project that needs coordination from lots of partners. We'll send an ETA later.

**Comment by yaananth** [comment]
FYI This creeps into multiple places like checkbox's checkmarks, primary buttons text etc.,

**Comment by yaananth** [comment]
Actually #3682 concludes -

> We actually had a long conversation about this earlier, involving a number of accessibility experts. It's actually 4.495:1. Our contrast experts stated making change to make it 4.5:1 is imperceptible to the naked eye. This color is the brand color for Outlook and one we use extensively in many of our components. Changing this would have a huge impact on many teams for little to no benefit other than a reading on a tool. Here is the comparison of these two colors, and also directly next to each other.

In any case if we pick `#0078D4` that will fix it...

**Comment by betrue-final-final** [comment]
Yes, but this change needs to be coordinated with many other teams. We’ll roll this out properly by December.
