### ISSUE TITLE
Padding on SpinButton seems to have not the correct padding on the right

### ISSUE THREAD

**Issue by LokiMidgard** [OfficeDev/office-ui-fabric-react#4028]
### Bug Report

- __Package version(s)__: 5.45.0
- __Browser and OS versions__: observed with Firefox 58.0.2 and Chrome 64.0.3282.167 Windows 7

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: (if applicable)

#### Describe the issue:

The SpinButton is bigger than its container.

#### Actual behavior:

The Buttons of the SpinButton on the right are drawn over the containing box

![grafik](https://user-images.githubusercontent.com/389101/36431749-a906875c-1658-11e8-8bc8-f7fe5130a2c5.png)

#### Expected behavior:

The control has the same padding on the left as on the right.  *(The css actualy says that it has a padding of 2 on all sides)*

### If applicable, please provide a codepen repro:

A [sample](https://codesandbox.io/s/x2475rz6vw) that draws a box around the SpinButton

**Comment by dzearing** [comment]
merged, should be fixed in monday's build.
