### ISSUE TITLE
DetailsList: Ungrouped items not rendered

### ISSUE THREAD

**Issue by paterasMSFT** [OfficeDev/office-ui-fabric-react#4029]
### Bug Report

- __Package version(s)__: 5.52.0
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Low

#### Describe the issue:

If you group some items, but not not all, the ungrouped items aren't rendered. So if I have a list of 10 items, and provide groupings for items 2-4 and 6-8, items 1, 5, 9, and 10 won't be rendered.

This is mot pronounced with nested groups, wherein ungrouped child items are still counted towards the total of a group, but not rendered.

Here is an example, modifying the [DetailsList vr-test story](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/apps/vr-tests/src/stories/DetailsList.stories.tsx) (unmodified on the left, reproduced issue on the right):

![image](https://user-images.githubusercontent.com/35780775/36434957-4f40c8d8-162e-11e8-86ab-11d8af421f23.png)

#### Actual behavior:

In the above example, the 1st, 2nd, and 4th items of the blue group aren't rendered, even though the group says it has 4 items total.

#### Expected behavior:

Ungrouped items would be rendered, alongside their sibling groups (when applicable).

**Comment by cobbs-totem** [comment]
I think I had this same question a while back:

https://github.com/OfficeDev/office-ui-fabric-react/issues/2064

I think what we're both trying to achieve is a "TreeView" component, which I'm lead to believe is in the works, maybe?

**Comment by aditima** [comment]
Same as #3657 . Closing as a duplicate.

We have a pending feature request on the TreeView control already. We'll make note of one more ask for that control.
