### ISSUE TITLE
Office Fabric website Nav component page broken

### ISSUE THREAD

**Issue by pkothare** [OfficeDev/office-ui-fabric-react#4030]
### Bug Report

- __Package version(s)__: v5/5.3.0, based on the stack trace observed
- __Browser and OS versions__: Edge/Windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: Office Fabric website

#### Describe the issue:

Open a browser and browse to https://developer.microsoft.com/en-us/fabric#/components/nav
The nav component documentation doesn't load correctly.

#### Actual behavior:

The main container of the page is blank. The following error was logged to the console (used F12 Developer Tools):

```
description: "Object.setPrototypeOf: argument is not an Object and is not null"
message: "Object.setPrototypeOf: argument is not an Object and is not null"
number: -2146823281
stack: "TypeError: Object.setPrototypeOf: argument is not an Object and is not null at i
(https://static2.sharepointonline.com/files/fabric/fabric-website/dist/fabric-sitev5.min.js?date=2018-2-20:1:1507) at Anonymous function 
(https://static2.sharepointonline.com/files/fabric/fabric-website/dist/fabric-sitev5.min.js?date=2018-2-20:22:20953) at i 
(https://static2.sharepointonline.com/files/fabric/fabric-website/dist/fabric-sitev5.min.js?date=2018-2-20:22:20874) at Anonymous function 
(https://static2.sharepointonline.com/files/fabric/fabric-website/dist/fabric-sitev5-5.3.0-0-1518730139704.min.js:1:512963) at t 
(https://static2.sharepointonline.com/files/fabric/fabric-website/dist/fabric-sitev5.min.js?date=2018-2-20:1:89) at Anonymous function 
(https://static2.sharepointonline.com/files/fabric/fabric-website/dist/fabric-sitev5-5.3.0-0-1518730139704.min.js:1:511041) at t 
(https://static2.sharepointonline.com/files/fabric/fabric-website/dist/fabric-sitev5.min.js?date=2018-2-20:1:89) at Anonymous function 
(https://static2.sharepointonline.com/files/fabric/fabric-website/dist/fabric-sitev5-5.3.0-0-1518730139704.min.js:1:413967) at t 
(https://static2.sharepointonline.com/files/fabric/fabric-website/dist/fabric-sitev5.min.js?date=2018-2-20:1:89) at Anonymous function 
(https://static2.sharepointonline.com/files/fabric/fabric-website/dist/fabric-sitev5-5.3.0-0-1518730139704.min.js:1:668111)
```

#### Expected behavior:

The page should load correctly and error free so that I can read the nav component documentation.

### If applicable, please provide a codepen repro:

N/A

**Comment by Jahnp** [comment]
Thanks for reporting this--we've been looking at this from this morning. We aren't reproing it locally and have a hunch that it may have been related to `master` being in a not great state at the time of last deploy. We'll check the latest state of `master` against our test environment and hopefully have a fix out today or tomorrow. @lynamemi for FYI (who's actually doing all the hard work here)

**Comment by Meffjuw** [comment]
Just wanted to add that the Breadcrumb component page looks broken too.

**Comment by lynamemi** [comment]
Resize group is having the same issue:
https://github.com/OfficeDev/office-ui-fabric-react/issues/4093
