### ISSUE TITLE
Please add type="button" attribute to <Rating /> buttons

### ISSUE THREAD

**Issue by ardallie** [OfficeDev/office-ui-fabric-react#4032]
Hello. 
I use Office-UI Fabric React with a custom front-end hosted on Office 365 SharePoint. The `<Rating />` component reloads the page after a star button has been clicked. 

In the context of SharePoint server, the  `<Button class='ms-Rating-button'` acts as a submit button that triggers the page reload when clicked.

May I suggest that the **type="button"** attribute is added to the `<Button class='ms-Rating-button'` elements in the `<Rating />`? It prevents the page reload.
```
<div class="ms-Rating-star">
  <button class="ms-Rating-button" id="Rating77-star-0" 
          type="button">
  </button>
</div>
```

[Related issue on SO](https://stackoverflow.com/questions/9846211/sharepoint-button-elements-perform-an-unwanted-reload-of-the-page)

Thank you in advance for looking into it.

**Comment by dzearing** [comment]
Fixing.
