### ISSUE TITLE
Unable to turn off checkbox column on DetailsList 

### ISSUE THREAD

**Issue by vivmaha** [OfficeDev/office-ui-fabric-react#406]
I would like to use the DetailsList, but I do not want the checkbox column (especially for my single item selection).

Can this column be optional?

**Comment by dzearing** [comment]
It's a feature request we can consider. We do turn it off when selection mode is none. Really what you want is "single selection with no check boxes".

**Comment by vivmaha** [comment]
@dzearing Please note that I do not need this anymore. I was under the false impression that i needed to turn on selection to get keyboard navigation. Since I do not need to turn on selection, I do not have this checkbox column. Hope this helps with triage.

**Comment by dzearing** [comment]
Good to hear. Thanks for the heads up @vivmaha

**Comment by yaananth** [comment]
I think the checkmark should be there for accessibility... color-blind people should be able to say that a row is selected, checkmark would help in that regard.

**Comment by betrue-final-final** [comment]
Yaanath is correct, we need to be able to indicate to people besides color that an item is selected. David, I have some thoughts which we can discuss around single select.

**Comment by dzearing** [comment]
I will close this for now then.
