### ISSUE TITLE
Slider component doesn't work well with Windows Narrator on Microsoft Edge browser

### ISSUE THREAD

**Issue by dylankil** [OfficeDev/office-ui-fabric-react#4064]
Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low)  Normal

Products/sites affected: OneNote Learning Tools Immersive Reader

#### Describe the issue:

Slider component doesn't work with Narrator

#### Actual behavior:

Narrator reads min and max value as 0-10

#### Expected behavior:

Narrator reads min and max value contextually (in our case it's the font size mapped to the step), not by logical step value

**Comment by betrue-final-final** [comment]
This is valid.

**Comment by mikewheaton** [comment]
It looks like the `ariaValueText` prop was added for this purpose:

> A text description of the Slider number value for the benefit of screen readers. This should be used when the Slider number value is not accurately represented by a number.

Given a number value you can give it a custom string to read out, for example translating "5/10" to "24 pixels".
