### ISSUE TITLE
React Image never calls onLoad event handler

### ISSUE THREAD

**Issue by Gustavogbs** [OfficeDev/office-ui-fabric-react#407]
I am passing a handler and it never gets called after the image gets loaded

**Comment by dzearing** [comment]
I beleive the expectation is that we mix in img element props into the img element. Fixed, updated one of the examples to log to console on load.

https://github.com/OfficeDev/office-ui-fabric-react/pull/437

**Comment by dzearing** [comment]
This fix has been merged and will be published in the next build >0.60.0
