### ISSUE TITLE
DetailsList shouldn't list event and column as optional

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [OfficeDev/office-ui-fabric-react#4080]
### Bug Report

- __Package version(s)__: 5.52.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: Sway

#### Describe the issue:

In `DetailsList.types.d.ts`:

```typescript
/**
 * If provided, will be executed when the user clicks on the column header.
 */
onColumnClick?: (ev?: React.MouseEvent<HTMLElement>, column?: IColumn) => any;
```

Why are `ev` and `column` potentially undefined? Is Fabric ever going to call the callback with them not defined?

**Comment by Jahnp** [comment]
Hey @JoshuaKGoldberg , just checking, is this blocking you for any reason? The reason we have those set to optional is that there are cases where as the consumer you may wish to pass a `void` to `onColumnClick` without using `ev` and `column`, and a consumer may have TSlinting rules on which don't allow for unused arguments (e.g. `ev` and `column`). These values will always have a value and never be undefined, but a consumer shouldn't be forced to use them in their method. I'm going to go ahead and close this as we don't think this is something we want to fix, but please feel free to reopen if you disagree. @aditima for FYI

**Comment by JoshuaKGoldberg** [comment]
I can't reopen (not a member of OfficeDev, only Microsoft) but I do disagree :)

If the consumer doesn't need `ev` or `column`, they can just pass a function that takes no arguments.

```
const props: DetailsListProps = {
    onColumnClick: () => { console.log("Hello world!"); },
}
```

This is breaking basic TypeScript compiles for us in Sway when we switch on the newer TS `--strictFunctionTypes` flag.

**Comment by Jahnp** [comment]
Hmmm @dzearing / @aditima / @manishgarg1 -- thoughts on this? @JoshuaKGoldberg What would be your proposed change? I'll go ahead and reopen this.

**Comment by JoshuaKGoldberg** [comment]
My proposal would be to make the parameters non optional.
