### ISSUE TITLE
OverflowSet.types.d.ts shouldn't use any for its types

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [OfficeDev/office-ui-fabric-react#4081]
### Bug Report

- __Package version(s)__: 5.5.2

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal 

Products/sites affected: Sway

#### Describe the issue:

In `OverflowSet.types.d.ts`:

```typescript
/**
 * Rendering method for overflow button and contextual menu. The argument to the function is
 * the overflowItems passed in as props to this function.
 */
onRenderOverflowButton: IRenderFunction<any[]>;
```

This doesn't play well with TypeScript's `--strictFunctionTypes`, as that flag won't allow passing functions with more specific types than `any[] | undefined` as the render function. The type it takes in should instead be `IOverflowSetItemProps[]`.

**Comment by aditima** [comment]
Thanks @JoshuaKGoldberg - this would be a great fix to have. My only concern is this is a contract change, so it's more suitable for a major release.
@dzearing - can you help with steps needed to create a PR for the 6.0 branch?

**Comment by JoshuaKGoldberg** [comment]
Ok! I'll send a PR and list this as a major change, and can update as recommended.

**Comment by JoshuaKGoldberg** [comment]
Ehh, no stale label please?
