### ISSUE TITLE
ReactDevTools shows 'Unknown' as the name of styled components

### ISSUE THREAD

**Issue by fpintos** [OfficeDev/office-ui-fabric-react#4084]
### Bug Report

- __Package version(s)__: 5.44.0
- __Browser and OS versions__: Chrome

Are you willing to submit a PR to fix? Yes
Requested priority: Low 
Products/sites affected: OWA

#### Describe the issue:

[React Dev Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?utm_source=chrome-app-launcher-info-dialog) shows up the hierarchy of React components in a page. 

Straightforward components appear with their proper names, ex Foo.
Components tagged with @customizable() also show a proper name, ex CustomizedFoo.
But components wrapped with styled() end up showing as Unknown.
It would be helpful during debug sessions for these to show up with a proper name, such as StyledFoo.

https://hackernoon.com/improving-component-names-in-react-developer-tools-4894247510c5 has more details on this.

#### Actual behavior:

Install React DevTools in Chrome and open a page with debug code of a Fabric application.
Expand the component tree and you'll see "Unknown"/"CustomizedFoo"/"Foo" pairs. Ex:
![image](https://user-images.githubusercontent.com/4239171/36619254-08660442-18a3-11e8-9348-cb16443691c5.png)

#### Expected behavior:

For the name of styled() components to reference the original control.

**Comment by oengusmacinog** [comment]
@fpintos Thanks for calling this out. Do you have any ideas on the best approach to fix? We would welcome a PR!

**Comment by dzearing** [comment]
I will look into a fix!

**Comment by dzearing** [comment]
@erichdev beat me to it. Thanks!!
