### ISSUE TITLE
Fabric React Button a11y: color contrast is not high enough between focus border and background of primary button

### ISSUE THREAD

**Issue by fengyue1013** [OfficeDev/office-ui-fabric-react#409]
![primary button contrast](https://cloud.githubusercontent.com/assets/12523937/19387458/dd6a2738-924c-11e6-9820-7ed062000a29.png)

The screen shot is taken from the fabric-react demo page.
When primary button is focused, the background color is `themeDark` and border is gray. 
When theme is blue, we can see that the contrast is not high enough.
It is not friendly in terms accessibility.

I haven't check all button styles or all theme colors. There may be similar issues

**Comment by dzearing** [comment]
@betrue-final-final

**Comment by dzearing** [comment]
I've resolved.

![image](https://cloud.githubusercontent.com/assets/1110944/22576008/0091c888-e96e-11e6-8df6-24e1503382dd.png)
