### ISSUE TITLE
[Docs] ResizeGroup Documentation Page Broken

### ISSUE THREAD

**Issue by cjsheets** [OfficeDev/office-ui-fabric-react#4093]
### Bug Report

- __Package version(s)__: prod
- __Browser and OS versions__: chrome / firefox

#### Describe the issue:

The developer docs for Resize Group are presently crashing.

[https://developer.microsoft.com/en-us/fabric#/components/resizegroup](https://developer.microsoft.com/en-us/fabric#/components/resizegroup)

`TypeError: Object prototype may only be an Object or null: undefined at setPrototypeOf (<anonymous>)`

#### Actual behavior:

The docs are still navigable (though firefox struggles with the "failed" script). The page under the ResizeGroup heading is empty.

**Comment by lynamemi** [comment]
Closing this here, we're tracking this issue for a couple of other pages in #4030.
