### ISSUE TITLE
TextField RTL is not aligned correctly

### ISSUE THREAD

**Issue by Caseyyu2** [OfficeDev/office-ui-fabric-react#4097]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
Maybe

Requested priority: (Blocking, High, Normal, Low) 
Normal

Products/sites affected: (if applicable)
N/A

#### Describe the issue:

When rendering required text field rtl style, the error message doesn't align correctly with the textfield
The issue only repros in Chrome.

#### Actual behavior:
![image](https://user-images.githubusercontent.com/8844898/36694150-4e421a2c-1af2-11e8-99d5-8acd1b5f50b3.png)

#### Expected behavior:

Align it correctly

**Comment by lambertwang** [comment]
This doesn't repro for me. Can you provide some specifics regarding your scenario? (browser, site, version, etc?)

**Comment by Caseyyu2** [comment]
@lambertwang I figured out the issue, so this does *not* on official fabric website (since the styling is different), but when local developer runs npm start, in rtl localhost env, it will repro.

The reason for that is on ms-app-content, we added translate(0)  'tricking' the GPU to think that an element is 3D to have perf gain, but in rtl chrome, this cause the layout issue.

We should probably take it out when it's RTL env in localhost, so that it wouldn't confuse developers that they break the textfield component, or whichever component that users text field.

**Comment by Jahnp** [comment]
@Caseyyu2 Thanks for the clarification. Is this affecting any actual product scenarios that you're aware of, or just the demo environment? We're going to assume the latter, so we'll go ahead and close this for now--but please feel free to re-open if you are seeing this repro elsewhere.
