### ISSUE TITLE
High Contrast hover/selected states on drop downs

### ISSUE THREAD

**Issue by AsaPefferman** [OfficeDev/office-ui-fabric-react#4100]
### Bug Report

- __Package version(s)__: Current?
- __Browser and OS versions__: Windows 10/Edge

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Sharepoint Forms
#### Describe the issue:

The hover states in edge make the text totally unreadable, and the selected states from multi-select dropdowns do the same thing.

#### Actual behavior:

See image
![drowpdown](https://user-images.githubusercontent.com/35933779/36699086-88d6a12c-1b00-11e8-9049-451598e1c39e.png)
![multi-select](https://user-images.githubusercontent.com/35933779/36699100-90886d24-1b00-11e8-89c1-09c34cccbcf7.png)

#### Expected behavior:

See Image
![dropdown-expected](https://user-images.githubusercontent.com/35933779/36699110-952d47d2-1b00-11e8-9ae2-491fe93fc871.png)
![multi-select_expected](https://user-images.githubusercontent.com/35933779/36699113-99550566-1b00-11e8-80e8-8838d230e745.png)

I could be wrong on the expected behaviors, just wanted to flag how unusable the current behaviors are.

**Comment by betrue-final-final** [comment]
Not seeing this either. @AsaPefferman, either your machine is in a bad state or you have some old build somehow.
![image](https://user-images.githubusercontent.com/20363037/36741282-89cd562c-1b99-11e8-8e04-f5aba28ceee8.png)

However I did find a bug with the checkboxes inside.
![image](https://user-images.githubusercontent.com/20363037/36741319-a11c6494-1b99-11e8-8c41-db36f385e03b.png)
