### ISSUE TITLE
Toggle weirdness in High Contrast mode

### ISSUE THREAD

**Issue by AsaPefferman** [OfficeDev/office-ui-fabric-react#4101]
### Bug Report

- __Package version(s)__: Current
- __Browser and OS versions__: Windows 10/ Edge

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Sharepoint forms

#### Describe the issue:
Toggle looks weird, is misaligned 

#### Actual behavior:

![toggle-bad](https://user-images.githubusercontent.com/35933779/36699876-ebf03d98-1b02-11e8-8b77-5b55d222e6b6.png)

#### Expected behavior:

![toggle-good](https://user-images.githubusercontent.com/35933779/36699880-eef06f68-1b02-11e8-8c5c-a651dd97cb2d.png)

**Comment by betrue-final-final** [comment]
I'm not seeing this. It looks like you may be on an older build somehow?
![image](https://user-images.githubusercontent.com/20363037/36741063-ff5142f6-1b98-11e8-93d8-8ead67e38a25.png)
