### ISSUE TITLE
Fade in high contrast mode doesn't invert

### ISSUE THREAD

**Issue by AsaPefferman** [OfficeDev/office-ui-fabric-react#4103]
### Bug Report

- __Package version(s)__: Current
- __Browser and OS versions__: Windows 10/Edge

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Sharepoint

#### Describe the issue:
The fade on a list of options in a table doesnt invert with the rest of the page in highcontrast mode

#### Actual behavior:

![fade](https://user-images.githubusercontent.com/35933779/36700538-e14fa4e4-1b04-11e8-91b6-21b40fabd18e.png)

#### Expected behavior:

![white fade-inverted](https://user-images.githubusercontent.com/35933779/36700549-e6c974b8-1b04-11e8-9bd0-17da49938adb.png)

**Comment by betrue-final-final** [comment]
Good bug. @lynamemi, want a fun bug to fix?

**Comment by mikewheaton** [comment]
Shouldn't this fade be hidden entirely for high-contrast?

**Comment by betrue-final-final** [comment]
Yes, but for reversed themes it should show up.

**Comment by betrue-final-final** [comment]
Let's fix this issue by removing the gradient in high contrast themes. I'll file a separate issue for dark themes.

**Comment by betrue-final-final** [comment]
I filed a new issue for dark themes #4112

**Comment by betrue-final-final** [comment]
Not a Fabric bug
