### ISSUE TITLE
Multiline TextField with placeholder fires onChanged-event after mount in IE11

### ISSUE THREAD

**Issue by reddor** [OfficeDev/office-ui-fabric-react#4107]
### Bug Report

- __Package version(s)__: current
- __Browser and OS versions__: Internet Explorer 11 

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: LPC Contact Editor

#### Describe the issue:

A (disabled) multiline TextField with placeholder text fires an onChanged event after mounting in IE11. 

#### Actual behavior:

An onChanged-event is fired when it shouldn't

#### Expected behavior:

nothing

### If applicable, please provide a codepen repro:

https://codepen.io/anon/pen/vdQWdP

alternatively:
<TextField multiline disabled={true} onChanged={() => alert("peekaboo")} placeholder={"hello"} />

**Comment by erichdev** [comment]
I believe https://github.com/OfficeDev/office-ui-fabric-react/pull/3883 will fix this

**Comment by dzearing** [comment]
This should be fixed onced published tonight.
