### ISSUE TITLE
Sticky tries to getBackground

### ISSUE THREAD

**Issue by obiwan007** [OfficeDev/office-ui-fabric-react#4108]
### Bug Report

- __Package version(s)__: 55.2
- __Browser and OS versions__: (Chrome 64.0.3282.167, Windows 10 1709)

Requested priority: (Blocking) 

Inside ScrollablePane we set a Sticky header.
Unfortunately this will lead to a crash of the app:

Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'

It looks like that this.root is undefined. window.getComputedStyle(undefined) is then failing.
Location: 

`// Gets background of nearest parent element that has a declared background-color attribute
    Sticky.prototype._getBackground = function () {
        **var curr = this.root;**
        while (window.getComputedStyle(curr).getPropertyValue('background-color') === 'rgba(0, 0, 0, 0)' ||
`

Example code in our app:
` <ScrollablePane>
                    <DetailsList
                      className='app-persona-group'
                      items={groups}
                      columns={this.getColumns(1)}
                      checkboxVisibility={CheckboxVisibility.hidden}
                      selectionMode={SelectionMode.single}
                      selection={this.selectionGroups}
                      selectionPreservedOnEmptyClick={true}
                      onRenderDetailsHeader={
                        // tslint:disable-next-line:jsx-no-lambda
                        (detailsHeaderProps: IDetailsHeaderProps, defaultRender: IRenderFunction<IDetailsHeaderProps>) => (
                          <Sticky>
                            {defaultRender({
                              ...detailsHeaderProps,
                              onRenderColumnHeaderTooltip: (tooltipHostProps: ITooltipHostProps) => <TooltipHost {...tooltipHostProps} />,
                            })}
                          </Sticky>
                        )}
                    />
                  </ScrollablePane>
`

Testing  the ScrollablePane demo leads to crash of the app too.

Last working version was 53.0.

**Comment by aappddeevv** [comment]
Just hit this as well. It's a show stopper for me. I'm rending into an iframe if that makes any difference.

**Comment by obiwan007** [comment]
Seems to be working now in version 5.56.0
