### ISSUE TITLE
Fadient doesn't invert in dark themes.

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#4112]
Bug Report
Package version(s): Current
Browser and OS versions: Windows 10/Edge
Priorities and help requested (not applicable if asking question):
Are you willing to submit a PR to fix? No
Requested priority: Normal
Products/sites affected: Sharepoint
Describe the issue:
The fade on a list of options in a table doesn't invert with the rest of the page in dark themes.

Actual behavior:
![image](https://user-images.githubusercontent.com/20363037/36740767-47679cda-1b98-11e8-841d-b241a486e10b.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/20363037/36740780-4f63d70a-1b98-11e8-8ff3-66a86c1d707d.png)

**Comment by jordandrako** [comment]
@lynamemi Have you checked into this and #4103 yet? I can take care of it if you haven't.

**Comment by betrue-final-final** [comment]
This is actually not a Fabric big.
