### ISSUE TITLE
Docs site is broken

### ISSUE THREAD

**Issue by gscottolson** [OfficeDev/office-ui-fabric-react#4126]
https://developer.microsoft.com/en-us/fabric#/components/nav

Errors are filling up the web dev console:

```
Uncaught TypeError: Cannot read property 'internal' of null


TypeError: Object prototype may only be an Object or null: undefined
```

**Comment by lynamemi** [comment]
Thanks for reporting! We are currently tracking here: https://github.com/OfficeDev/office-ui-fabric-react/issues/4030
