### ISSUE TITLE
is-selected missing on ms-Nav-link

### ISSUE THREAD

**Issue by obiwan007** [OfficeDev/office-ui-fabric-react#4143]
### Bug Report

- __Package version(s)__: 5.56.0
- __Browser and OS versions__: all Browsers

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal) 

#### Describe the issue:
In previous versions, the is-selected class was added to a selected nav element. So overriding the applied css styling was rather easy.
This seems not to be possible now as the style is internally calculated and just the theme colors are applied. As we need to style a dark/light Nav menu we could not just override the theming.
I thing it would be easy to add the is-selected class again during the selection.

#### Actual behavior:
No is-selected is applied to a given nav item.

#### Expected behavior:
is-selected (or another class) should be applied to nav elements.

**Comment by oengusmacinog** [comment]
We just converted the Nav components styles to mergeStyles and this may have been missed.  I will look into it.
