### ISSUE TITLE
Indeterminate ProgressIndicator overflows Dialog  

### ISSUE THREAD

**Issue by daniel-white** [OfficeDev/office-ui-fabric-react#4146]
### Bug Report

- __Package version(s)__: 5.57.0
- __Browser and OS versions__:  IE11, Chrome

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No (only if I knew where to fix it)

Requested priority: Normal

Products/sites affected: N/A.

#### Describe the issue:

When placing an indeterminate `ProgressIndicator` in a `Dialog`, there is an overflow when animation reaches the end, causing the dialog to scroll horizontally.

```
import React from 'react';
import { render } from 'react-dom';
import { Fabric, Dialog,ProgressIndicator } from 'office-ui-fabric-react';

const App = () => (
  <Fabric>
    <Dialog hidden={false} dialogContentProps={{ title: "Hello world" }}>
      <ProgressIndicator />
    </Dialog>
  </Fabric>
);

render(<App />, document.getElementById('root'));
```

#### Actual behavior:

The dialog puts up a scrollbar.

#### Expected behavior:

It shouldn't overflow.

#### Repro:
https://codesandbox.io/s/74kzv1z3l0

**Comment by daniel-white** [comment]
Actually, I found it so I'll get a PR up for it.

**Comment by dzearing** [comment]
That's sad. And happy that you fixed it. I will figure out how this got there, and also get your PR in!

Thanks @daniel-white
