### ISSUE TITLE
[BasePicker] null reference exception thrown when tabbing away after suggestions are dismissed

### ISSUE THREAD

**Issue by martellaj** [OfficeDev/office-ui-fabric-react#4150]
### Bug Report

- __Package version(s)__: Latest

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: BasePicker

#### Describe the issue:

User can dismiss Callout with suggestions and then TAB away. However, when TAB is pressed, there's an attempt to read `this.suggestionElement` even though it may not exist, causing a null exception to be thrown.

https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx#L458

**Comment by sortegamartin** [comment]
- __Package version(s)__: ^5.11.0
- __Browser and OS versions__: Chrome and Windows 10

I have the same error:

![image](https://user-images.githubusercontent.com/33054287/36874579-bac0248e-1dac-11e8-80fc-1ac0dc920d57.png)
