### ISSUE TITLE
BasePicker throw error "Cannot read property 'focus' of null" when resetFocus

### ISSUE THREAD

**Issue by sortegamartin** [OfficeDev/office-ui-fabric-react#4156]
### Bug Report

- __Package version(s)__: ^5.11.0
- __Browser and OS versions__: Chrome and Windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority:  Normal

#### Describe the issue:
When in the BasePicker the focusInput is changed and the resetFocus is launched, the following error is thrown:

![image](https://user-images.githubusercontent.com/33054287/36875054-aab2c090-1dae-11e8-9c67-d6e4daf280ba.png)

#### Actual behavior:

Console error is thrown

#### Expected behavior:

No console error should be thrown.

**Comment by bratukham** [comment]
Probably relates somehow to #3873 ?

**Comment by dzearing** [comment]
@joschect for visibility

**Comment by michaelangotti** [comment]
@sortegamartin Are you still reproing in the latest (5.94.0)?

**Comment by yaananth** [comment]
There is a new bug here.
![image](https://user-images.githubusercontent.com/12280011/39607315-41893ff0-4f08-11e8-8c7a-293f9cdcf57c.png)

If there are NO items, and if user can't add items, then that code blows up!
We should check the length before we mark the property as `selected`....

**Comment by micahgodbolt** [comment]
This is an old bug. Can anyone confirm if this still exists in the 6.x branch?

**Comment by joschect** [comment]
@micahgodbolt I can confirm that this was fixed. Now selection is managed through the selection component entirely.
