### ISSUE TITLE
Bug: Calendar component showing week of year 

### ISSUE THREAD

**Issue by jmmartinez84** [OfficeDev/office-ui-fabric-react#4162]
### Bug Report

- __Package version(s)__: 5.55.0
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: (if applicable)

#### Describe the issue:
Calendar component does not show correct week of the year if firstDayOfWeek is set on Monday. Example year 2015.

#### Actual behavior:

getWeekOfYearFullDays always take as firstDayOfWeek=0 (Sunday)

#### Expected behavior:

getWeekOfYearFullDays should take firstDayOfWeek set in component props.

![office-ui-fabric-issue](https://user-images.githubusercontent.com/1647121/36907791-cbf4f198-1e39-11e8-8967-80e42536aa21.png)

**Comment by dzearing** [comment]
@johannao76 for visibility

**Comment by johannao76** [comment]
We will take a look in the coming sprint, thanks for reporting

**Comment by johannao76** [comment]
@jmmartinez84: We are unable to repro this issue, can you provide a codepen or similar with a repro? Thanks!
![image](https://user-images.githubusercontent.com/11838969/36918283-40abcd30-1e0e-11e8-8aaf-1535a94b85d6.png)

**Comment by jmmartinez84** [comment]
Sorry, I've found a configuration that meets with my region. Setting up this parameter works fine for me.
`firstWeekOfYear = { FirstWeekOfYear.FirstFourDayWeek }`

I apologize for wasting your time.
