### ISSUE TITLE
Convert ContextualMenuItem to css-in-js

### ISSUE THREAD

**Issue by essar123** [OfficeDev/office-ui-fabric-react#4169]
**Bug Report**
Describe the issue:
A few issues with the custom styles for IContextualMenuItem 

IContextualMenuItem accepts a style: React.CSSProperties but its seems like its never used in code, also the method provided for customStyling of `IContextualMenuItem`

```ts
getItemClassNames?: (theme: ITheme,
    disabled: boolean,
    expanded: boolean,
    checked: boolean,
    isAnchorLink: boolean,
    knownIcon: boolean,
    itemClassName?: string,
    dividerClassName?: string,
    iconClassName?: string,
    subMenuClassName?: string) => IMenuItemClassNames;
```

is not supportive either, to implement this method in consuming code your code needs to know lot about office-ui-fabric-code.

**Problems with implementing getItemClassNames in consuming repo.**
1.  `IMenuItemClassNames` type is required to implement this method which is non importable from package.
2.  To implement this method you need to copy paste `getContextualMenuClassNames` in `ContextualMenu.classNames.ts` and make changes to desirable properties.

**Suggestion:
style property should be of type `IContextualMenuStyles` which should be merged with default styles.**

**Comment by oengusmacinog** [comment]
stay alive

**Comment by d-khoury** [comment]
Any update on this?

**Comment by oengusmacinog** [comment]
@d-khoury Currently in progress actually so there should be a PR in the next week if all goes smoothly.

**Comment by d-khoury** [comment]
@oengusmacinog Thank you, can you update this thread when the PR is completed?

**Comment by oengusmacinog** [comment]
@d-khoury absolutely, the PR will autoclose this issues actually

**Comment by d-khoury** [comment]
@oengusmacinog Is there a way I can get automatically notified when the issue is resolved?

**Comment by philipzloh** [comment]
@d-khoury it looks like @oengusmacinog didn't actually fix this; the PR #5461 has an explicit comment saying

> Note only ContextualMenu has been converted, not ContextualMenuItem due to time constraints.

@oengusmacinog what is your plan for finishing this? @cliffkoh had a very astute comment in the PR...

> Should we really check in stuff halfway? It makes it really confusing as to the state and usability of the API (personally, I don't even check it in in 2 parts because of this problem).

**Comment by oengusmacinog** [comment]
I won't be able to do the `ContextualMenuItem`.  @micahgodbolt do you know who might be able to pick this up?

**Comment by micahgodbolt** [comment]
I can make sure it gets done. I don't know if I'll have the time to dive into it right now.

**Comment by cliffkoh** [comment]
Setting as pri 1 because the component is in a halfway state atm, which is bad :(

**Comment by micahgodbolt** [comment]
@KevinTCoughlin said he could dive into this. There's several questions about implementation though. As a child we could use subComponentStyles, or the contextualMenuItemAs, OR pass a styles prop through each item.....and the solution is probably a combination of the 3

**Comment by KevinTCoughlin** [comment]
I was going to take a look at TextField and any other components that support a similar rendering paradigm and figure it out. Pointers welcome.. been some time since I looked at this, but I think I can figure it out.

**Comment by micahgodbolt** [comment]
scenarios to support:
Single styles function to style entire contextualMenu
Ability to apply custom styles per item
Ability to style differently based on what type of item it is (header, divider, regular etc)

**Comment by KevinTCoughlin** [comment]
Work:

- [ ] Get working example w/ ContextualMenuItem styled via item props (styles, className, classNames)
- [ ] Get working example w/ `contextualMenuItemAs` & custom styles / classNames
- [ ] Consider using `subComponentStyles` like in `TextField.types.ts` if necessary to properly style child given parent state -- Think Label & TextInput scenario
- [ ] Refactor Item styles & props logic into Item Base component as expected w/ mergeStyles approach
- [ ] Ensure above scenarios supported with refactor
- [ ] Verify public API same i.e. no breaking changes
- [ ] If breaking changes / deprecations deemed necessary -- apply them

**Comment by KevinTCoughlin** [comment]
I've raised a PR, but am going thru the various modes of styling once more to make sure we're covered prior to merge. Getting close..

**Comment by KevinTCoughlin** [comment]
Thanks for your patience and for the initial report @essar123. I've converted `ContextualMenu` to use `getStyles` for itself as well as the `ContextualMenuItem`(s). This comment goes over the various ways to use `getStyles` https://github.com/OfficeDev/office-ui-fabric-react/pull/6094#issuecomment-417423698.

For styling various aspects of the menu, you can provide a `styles?` prop as part of `menuProps`:

```ts
const getMenuStyles = (): Partial<IContextualMenuStyles> => {
  return {
    root: {
      background: 'blue'
    }
  };
};

...

menuProps={{
  shouldFocusOnMount: true,
  styles: getMenuStyles,

...
```

For styling individual items within a menu, you can provide a [styles?](https://github.com/OfficeDev/office-ui-fabric-react/blob/4d3546641b967072b05815e8f52b13d4ddff5ac0/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItem.types.ts#L34) within [itemProps?](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.types.ts#L394) per `IContextualMenuItem` definition:

```ts
const getMenuItemStyles = (): Partial<IContextualMenuItemStyles> => {
  return {
    linkContent: {
      color: 'white'
    }
  };
};

...

menuProps={{
  shouldFocusOnMount: true,
  items: [
    {
      key: 'newItem',
      text: 'New',
      onClick: () => console.log('New clicked'),
      styles: getMenuItemStyles
    },

...

More information about the `styles` prop can be find in our Wiki -- https://github.com/OfficeDev/office-ui-fabric-react/wiki/Component-Styling#styles-prop
