### ISSUE TITLE
5.59.0 crashing in <ImageBase>

### ISSUE THREAD

**Issue by KyleFoleyImajion** [OfficeDev/office-ui-fabric-react#4174]
### Bug Report

- __Package version(s)__: 5.59.0

#### Priorities and help requested (not applicable if asking question):

Requested priority: Blocking

#### Describe the issue:

Updated to 5.59.0 from 5.54.0, getting a blocking error when running npm start on my react project. I then downgraded to 5.54.0 and it worked perfectly fine. Updated back to 5.59.0, same blocking error.

#### Actual behavior:

When I run npm start on my react project, I get this error - `TypeError: ImageBase_1._svgRegex is undefined`. Looking at my console window in the browser, it looks as if it's an issue with rendering PersonaCoin. Here's where the error occured  - `The above error occurred in the <ImageBase> component:`

#### Expected behavior:

It should run my react project.

**Comment by oengusmacinog** [comment]
@KyleFoleyImajion This was converted to mergeStyles and static variables and functions seem to have broken.  I'm looking into it now.
