### ISSUE TITLE
Tabbing when PeoplePicker has focus generates an exception

### ISSUE THREAD

**Issue by nero120** [OfficeDev/office-ui-fabric-react#4177]
Can be recreated on the [Fabric UI website](https://developer.microsoft.com/en-us/fabric#/components/peoplepicker):

1. Click on People Picker field so it has focus
2. Select 'Annie Lindqvist' from the suggestions dropdown
3. Press the'tab' key to leave the field, an exception is now visible in the developer tools console:

```
TypeError: Cannot read property 'hasSuggestedActionSelected' of null
```

I've also recreated this issue on my project which uses v5.50.0.

**Comment by michaelangotti** [comment]
@nero120 What browser are you using? We are not able to repro this error.

**Comment by nero120** [comment]
Thanks @michaelangotti, I've just tried recreating the issue on the Fabric UI website and on my project and I was unsuccessful so it looks like it was a temporary issue, possibly my browser!
