### ISSUE TITLE
Accessibility in Facepile

### ISSUE THREAD

**Issue by marichinn** [OfficeDev/office-ui-fabric-react#4179]
I'm using the Facepile component and found an accessibility bug using Keros:

<img width="462" alt="facepilebug" src="https://user-images.githubusercontent.com/37083639/36993656-55eb1f28-2063-11e8-8156-7ab968c48325.PNG">

This is in reference to how the ariaDescribedBy prop is assigned. Is this something that can be looked at? The learn more links here: https://dequeuniversity.com/rules/axe/2.6/aria-valid-attr-value

**Comment by dzearing** [comment]
@mattlind

**Comment by dzearing** [comment]
The issue is that we are including `aria-describedby` even when no `ariaDescription` value has been offered.

To remove the warning, it just means we need to conditionally add `aria-describedby` only when `ariaDescription` is provided. Simple fix.
