### ISSUE TITLE
Icons not showing

### ISSUE THREAD

**Issue by tonymobster** [OfficeDev/office-ui-fabric-react#418]
I followed the getting started tutorial for the documentcardbasic-demo which works fine, however icons are not showing up for a few additional components I added, specifically CommandBar, CommandButton, IconButton and an icon.

I've referenced the fabric css and added the dir tag to my html element as stated in the documentation. I've wrapped my app component in a Fabric component yet still no dice. Is there any step i'm missing? Some other css file to reference?

![image](https://cloud.githubusercontent.com/assets/1521177/19467090/cd2cf4ae-94fe-11e6-92de-240f58158213.png)

**Comment by dzearing** [comment]
what version of fabric css? you need 4 I believe

**Comment by tonymobster** [comment]
I was just about to close this. I fixed the issue. 

The bundled css '../node_modules/office-ui-fabric-react/dist/css/fabric.min.css' worked, whereas the linked one in the tutorial 'https://appsforoffice.microsoft.com/fabric/2.2.0/fabric.min.css' didn't.
