### ISSUE TITLE
[DetailsList] Override background on row click after disabling Selection.

### ISSUE THREAD

**Issue by MaronMariusz** [OfficeDev/office-ui-fabric-react#4180]
Hi,

is there some elegant way to totally override background on DetailList row after click ?

What I did is just disable at all selection by prepare: `new Selection({ canSelectItem: () => false, selectionMode: SelectionMode.none })`

but it still keep some light grey background after clicking on row that overrides my background that I modified by `defaultRender({ ...props, className })` in onRenderRow prop.

If someone could help I will be thankful.
Cheers!

**Comment by jordandrako** [comment]
@aditima Can you give some insight on styling DetailsRow selection?

**Comment by lszomoru** [comment]
I would have expected that `SelectionMode.none` would disable the click event handler on the row.

**Comment by jordandrako** [comment]
@MaronMariusz This is what the `onRenderRow` prop is used for. See the [DetailsList documentation](https://developer.microsoft.com/en-us/fabric#/components/detailslist) and scroll to the "Rendering custom item rows" section for an example on how to use `onRenderRow` prop to change the row props, such as className.

Closing for now, if this is still an issue, feel free to re-open.

**Comment by MaronMariusz** [comment]
Hi, I am afraid that this not resolve the issue.
I would like to use DetailsList or DetailRow component because their styles are OK for me and fit to my page but I can't totally drop selection after clicking on the row. That's the issue.

For what `selectionMode` and `selection` props are ? For me it means if I drop the selectionMode then I would expect that after clicking on details row there is no selection at all ;) But in fact there is small light grey colour selection that overrides my styles after click :)

**Comment by fedesantamarina** [comment]
`  private _onRenderRow = (props: IDetailsRowProps): JSX.Element => {
    props.className = "";
    return <DetailsRow {...props} />;
  }`
Still the same
