### ISSUE TITLE
[Searchbox] defaultValue is never used

### ISSUE THREAD

**Issue by cslecours** [OfficeDev/office-ui-fabric-react#4181]
### Bug Report

- __Package version(s)__: 5.58.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? If the decided outcome is simple to implement.

Requested priority: (Blocking, High, Normal, __Low__) 

Products/sites affected: (if applicable)

#### Describe the issue:

The prop `defaultValue` defined in `SearchBox.types.ts` is never used in `SearchBox.base.tsx`. 

#### Actual behavior:

Defining `defaultValue` does nothing.

#### Expected behavior:

Either `defaultValue` should be removed from props, or actually do something.

**Comment by jordandrako** [comment]
I think I will deprecate it until we are ready to implement uncontrolled text fields.
