### ISSUE TITLE
[High contrast] Button focus is not visible in HCW

### ISSUE THREAD

**Issue by AkshanshSrivastava03** [OfficeDev/office-ui-fabric-react#4190]
### Bug Report

- __Package version(s)__: 5.55.1002
- __Browser and OS versions__: EDGE + High contrast mode

#### Describe the issue:
The focus on the command button is not visible in high contrast modes.
![image](https://user-images.githubusercontent.com/24951429/37021291-12d5a8ec-2145-11e8-8d93-7d2a4f812325.png)

Same behavior is seen in cross button of Panels too:
![image](https://user-images.githubusercontent.com/24951429/37021371-51de43dc-2145-11e8-81b2-7e5307b1f086.png)

Once you focus on these buttons, one cannot find out where the focus it.

#### Actual behavior:
Focus in high contrast mode is not visible clearly

#### Expected behavior:
Focus should be easily noticeable to disabled users.

This is easily seen on the office fabric main site too, so code pen is not needed

**Comment by betrue-final-final** [comment]
@lynamemi, I feel like we took care of this, but it is indeed broken on the live site.

**Comment by lynamemi** [comment]
Found the other issue - we can track this there:
https://github.com/OfficeDev/office-ui-fabric-react/issues/3419
