### ISSUE TITLE
Fabric Panel focus order is improper with choice group in the panel

### ISSUE THREAD

**Issue by AkshanshSrivastava03** [OfficeDev/office-ui-fabric-react#4191]
### Bug Report

- __Package version(s)__: 5.55.1002
- __Browser and OS versions__: Chrome

#### Describe the issue:
Panel focus order is improper when choice group is rendered within the Panel.

#### Actual behavior:
Suppose you have choice group with options "a" and "b" in the panel.

The focus first goes to cross button of the panel, then the choice group option "a", then tabbing will make you focus the page title/window etc.

If you select option "b" my moving key down, then the focus will remain inside the Panel which is the expected behavior. But by default, as "a" is selected, the focus goes out of the Panel

#### Expected behavior:
Focus order should remain inside the panel ony

### If applicable, please provide a codepen repro:
https://codepen.io/AkshanshSrivastava03/pen/mXZpwp

**Comment by KevinTCoughlin** [comment]
@AkshanshSrivastava03 is this still an issue? In testing this today, focus order seems to be:

["a", "b", "X (close cross)"]

https://s.codepen.io/AkshanshSrivastava03/debug/mXZpwp/DqADdEOJEXwA

Once a choice group item is selected UP/DOWN is required to toggle the selection similar to a standard radio group.

**Comment by KevinTCoughlin** [comment]
@AkshanshSrivastava03, I'm going to close as this seems to not be an issue (provided an example). Please re-open if I misunderstood so that we can address properly. Thanks for using the library and for your feedback :).

**Comment by AkshanshSrivastava03** [comment]
@KevinTCoughlin The code pen which you have attached has the repro. After radio button focus, tab should take me to the close button of the panel and not to the address bar. 
Get the focus on radion button "a", then press tab the focus goes to address bar (which is incorrect behavior). If you select "b", then the focus remains to move inside panel only (which is correct behavior)

**Comment by SumiranAgg** [comment]
+1
