### ISSUE TITLE
ScrollablePane with DetailsList and Sticky Header is overpainting scrollbar

### ISSUE THREAD

**Issue by obiwan007** [OfficeDev/office-ui-fabric-react#4205]
### Bug Report

- __Package version(s)__: 5.60.0
- __Browser and OS versions__: Chrome

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: (Normal) 

Products/sites affected: (if applicable)
Demo App for ScrollablePane

#### Describe the issue:

The Header is shown correctly on first draw - even if it is a bit overpainted from the scrollbar (making the header slightly narrower would be great).
If the scrollbar is used, the Sticky header is repainting itself. As it is as wide as the container it is overwriting the scrollbar at the top.

#### Actual behavior:

Scrollbar is overwritten from sticky header in DetailsList after scroll has taken place.

#### Expected behavior:

Scrollbar is visible completely in all cases.
Header is completely visible even if scrollbar is shown.

### If applicable, please provide a codepen repro:

See fabric component demo in ScrollablePaneDetailsListExample.

**Comment by obiwan007** [comment]
Unfortunately this issue is still not fixed.
![microsoft edge 11 04 2018 09_37_01](https://user-images.githubusercontent.com/12936285/38602863-491f4f3c-3d6c-11e8-9c82-df6fa1b250a2.png)

**Comment by aditima** [comment]
@leddie24 - you are already working on something very similar. Maybe this will be taken care of by your new fix?

**Comment by leddie24** [comment]
This is fixed from #4491
