### ISSUE TITLE
[Accessibility][ChoiceGroup] Provide field for aria label on IChoiceGroupOption 

### ISSUE THREAD

**Issue by daweffe** [OfficeDev/office-ui-fabric-react#4209]
### Bug Report

- __Package version(s)__: 5.49.
- __Browser and OS versions__: all

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal 

Products/sites affected: Planner

#### Describe the issue:

We need to be able to define the aria label on the ChoiceGroup radio buttons.

**Comment by mdahamiwal** [comment]
We already have labels against each choice option and we are using `htmlFor` to bind it which makes them accessible. If the requirement is to have a different `aria-label` compared to text, we can look into it but then the label can be different for impaired users.

**Comment by daweffe** [comment]
We have a bug open that the choiceGroup is not working with VoiceOver. Narrator seems to find the text ok, but I have not tested it on a mac with voiceover yet. In the DOM I see the input element has the aria-labelledBy field set with the ID of that input element, but the text is in the label element that is not a child of that input element. If voiceover is having trouble, I suspect that this is the cause.

**Comment by oengusmacinog** [comment]
@daweffe thanks for the extra info, I will test this out specifically in VoiceOver and see what I can find out
