### ISSUE TITLE
Support a read-only version of Calendar

### ISSUE THREAD

**Issue by fpintos** [OfficeDev/office-ui-fabric-react#4210]
In order to support Calendar Print in OWA we need a read-only, static version of the mini-calendar.

It should not support any kind of user input or focus - right now I've accomplished that with a disabled FocusZone around it.
Navigation buttons should be hidden - this can be accomplished with min/max dates.

An issue left is that it should not highlight the current date and selected dates.

**Comment by Jahnp** [comment]
Thanks for this @fpintos. @johannao76 for FYI--is this something on your team's radar? Is this something that needs design input?

**Comment by Jahnp** [comment]
Oops--didn't realize you two were teammates :) Let me ask a different question, both of you: is this something someone from your team would be willing to fund?

**Comment by johannao76** [comment]
It seems like our team can implement, though it looks like Fabio already got our scenario working using the focus zone. Fabio, is this a matter of adding the FocusZone in fabric itself? We can schedule the work to do this in fabric if we foresee other consumers of the mini-calendar will need this functionality too.

________________________________

**Comment by fpintos** [comment]
I'm thinking all we need is a readOnly flag in the control, which will cause it to not apply the highlight on selected dates and disable all sorts of user input handlers.

I've worked around the user input with the FocusZone  to block keyboard input and a transparent DIV covering the controls, to block touch/mouse/pen input. FocusZone is already from Fabric, so we're good from that perspective.

**Comment by Jahnp** [comment]
That flag makes sense to me. Glad to hear you were able to resolve locally, @fpintos. Do we want to keep this issue open in the meantime, then? If so, do you have a sense on when you'd be able to schedule the work to add this? Just trying to keep on top of open/active issues. Thanks!

**Comment by fpintos** [comment]
Hi @Jahnp, we can close the issue as having a workaround.
If more applications need it, then the read-only flag might be a nice addition and we open it up again.

For the record: I was able to get a completely read-only view by using the disabled FocusZone around the control and then applying the following style overrides in the CSS of my parent control's IStyle:

```typescript
  '& .ms-DatePicker-dayBackground, & .ms-DatePicker-day--highlighted': {
      // Override the background color of highlighted days.
      // Need both selectors as they both set the color, and need !important
      // because the color gets applied by the private class after the public class.
      backgroundColor: 'inherit !important',
  },
  '& .ms-DatePicker-monthComponents': {
      // Kill the container that shows the up/down buttons.
      display: 'none',
  },
  '& .ms-DatePicker-header': {
      // Centralize the remaining header content.
      width: '100%',
      display: 'flex',
      justifyContent: 'center',
  },
  '& .ms-DatePicker-monthAndYear': {
      // Remove padding and marging from the header text, so it centralizes properly.
      marginLeft: 0,
      marginRight: 0,
      padding: 0,
  },
```
