### ISSUE TITLE
Persona should implement focus() and expose via IPersona

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#4214]
This is a feature request to add the focus implementation for Persona control and expose the method through IPersona interface so consumer can easily focus on the Persona element.

There isn't any `focus` implementation on the Persona control. Previously, as a workaround, we can pass down `ref` to get the actual react instance of Persona and call `ReactDOM.findDOMNode` to find the DOM node to manually focus on the Persona element.

However, after recent change, we can no longer pass down `ref` to Persona. (Try to implement focus logic for Persona in a consumer place, it will be hard.)

As a replacement, we can only use `componentRef` that callbacks `IPersona`. But `IPersona` is defined empty right now.

**Comment by Jahnp** [comment]
This sounds reasonable to me, but as codeowners for Persona it's be good to hear thoughts from @mtennoe and @jakob101. Also tagging @dzearing , @aditima , and @manishgarg1 for FYI in case there are any concerns from a patterns perspective around exposing this.

@ipip2005, assuming we get clarity on a path forward here, is this something you'd be willing to submit a PR for?

**Comment by mtennoe** [comment]
This definitely makes sense to me. Sounds like we regressed on this functionality, so we should ensure this works again, and going the focus() call route makes it easier for component consumers

**Comment by jakob101** [comment]
+1! :)

**Comment by dzearing** [comment]
e.g.
```tsx
<Button ref={ buttonRef } >
  <Persona ... />
</Button>
```

Then you call `buttonRef.current.focus()`.

The other alternative is that we introduce a `renderAs` to render the `Persona` as something else which can receive focus? Maybe?

**Comment by dzearing** [comment]
But @Jahnp @mtennoe I'm not sure why this makes any sense. We should reserve focus for actual interactive elements (buttons, anchors, and inputs) and not for things which have no interactive behavior. Please correct me if i'm wrong.

@ipip2005 Can you please explain your scenario as to why you want this?

**Comment by Jahnp** [comment]
@dzearing Ahh good catch--for some reason I thought I recalled Personas being intrinsically interactive vs just vanilla `div`s. Yes, in that case afaik focus *should* just be a concern for the composer, such as in your example. Curious to hear more on why this is desired for persona.

**Comment by mtennoe** [comment]
@dzearing - Ah yes, a misunderstanding form my side as well, thanks for clearing things up!

**Comment by jordandrako** [comment]
Thanks for clearing that up. Let me know if there are any leftover actionables here.

**Comment by ipip2005** [comment]
@dzearing I'm bit confused that as long as Persona can accept native HTML props, why it can't be directly focused? HTML div element also has `.focus()` function isn't it?

Wrapping a button looks like a work around for me which means i have to assign a11y attributes to the button instead of Persona like below.
      <Persona
        aria-label={this._ariaLabel}
        aria-posinset={this.props.index + 1}
        aria-setsize={this.props.itemsCount}
      />
