### ISSUE TITLE
Feature Request:Could release information include what's in the release in addition to not in release? 

### ISSUE THREAD

**Issue by liang2zhu1** [OfficeDev/office-ui-fabric-react#4223]
Using example here https://github.com/OfficeDev/office-ui-fabric-react/releases/tag/office-ui-fabric-react_v5.46.0 , I'm befuddled why it gives me commits since the release but not what are the commits in the release? 
This was very confusing , to me , as usually a release or build would tell what's in it (since last release). 
I think it's still useful information to know what's not in the release but I'd rather think it's more popular to know "I'm moving to a newer version of Office Fabric because I need a feature/fix and want to ensure one or more particular change is included"

**Comment by mikewheaton** [comment]
The 'minor changes' and 'patches' sections describe what's changed in that release as compared to the last one. But I do wonder if it would be possible to link to the actual PRs for each of those comments. @dzearing knows more about the automated release process.

**Comment by dzearing** [comment]
Done. Spent some weekend time refining `scripts/updateReleaseNotes.js` to attach PR/commit/author links to each change.

**Comment by mikewheaton** [comment]
Wow, just saw the [latest release notes](https://github.com/OfficeDev/office-ui-fabric-react/releases/tag/office-ui-fabric-react_v5.63.0) and this is so much better!
