### ISSUE TITLE
Async Debounce Should Provide Option for executing pending actions on disposal

### ISSUE THREAD

**Issue by ianw89** [OfficeDev/office-ui-fabric-react#4229]
Scenario:
You have components that use _async.debounce for delaying update actions. When the user navigates to a different part of your UI, this component gets cleaned up, but it still had pending debounce actions. Today they will all be disposed and not resolve. We should provide an option so that when you setup a debounce the disposal behavior can be to resolve the code before cleaning it up, so the change isn't lost.

**Comment by michaelangotti** [comment]
It looks like this issue has been answered/resolved. Closing this issue.
