### ISSUE TITLE
add "click/focus to edit" example, helps show how to use components/component properties together e.g. FocusZone, TextField and Label

### ISSUE THREAD

**Issue by aappddeevv** [OfficeDev/office-ui-fabric-react#4242]
Enhancement request that only needs to be applied to a few examples. This seems like a useful use-case to illustrate.

**Comment by aappddeevv** [comment]
Thanks! I'm still having trouble with and cannot seem to get clicking, editing, and "tabbing/return/esc" to work using this combo (as a target use case). I setup something where you can tab/click to go to a TextField to edit but tabbing to go to another TextField goes crazy and jumps to something outside the FocusZone. I could really use a great example since capturing data input across multiple inputs and having a great user experience is important.

**Comment by micahgodbolt** [comment]
This feature was added via 'open in codepen'.

**Comment by aappddeevv** [comment]
@micahgodbolt Thanks! I'll take a look!
