### ISSUE TITLE
Pivot component renders nothing after updating to version 5.63.0

### ISSUE THREAD

**Issue by m-sadegh-sh** [OfficeDev/office-ui-fabric-react#4249]
### Bug Report

- __Package version(s)__: 5.63.0
- __Browser and OS versions__: Windows Server 2016, Chrome 64.0.3282.186

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/sites affected: (if applicable)

#### Describe the issue:

After upgrading package from 5.52.0 to 5.63.0, Pivot component stops rendering. Before upgrade everything works just fine. There is no error/warning in console related to Office UI Fabric.

Here is the output:

`<div><div role="presentation" class="ms-FocusZone" data-focuszone-id="FocusZone45"><ul class="ms-Pivot root_48cb954b" role="tablist"></ul></div><div role="tabpanel"></div></div>`

It seems that Pivot items is empty. But I've defined them as below.

`<Pivot>
                            <PivotItem
                                linkText={translate('role-form.tabs.letter.link-text')}
                                itemIcon="Mail">
                                <div
                                    className="ms-Grid-row">...
                                </div>
                            </PivotItem>
                            <PivotItem
                                linkText={translate('role-form.tabs.portal.link-text')}
                                itemIcon="ViewDashboard">
                                <div
                                    className="ms-Grid-row">...
                                </div>
                            </PivotItem>
                        </Pivot>`

#### Actual behavior:

Renders nothing.

#### Expected behavior:

Render two pivot items with their contents.

**Comment by michaelangotti** [comment]
@m-sadegh-sh Can you provide a repro?

**Comment by OneCyrus** [comment]
same issue here. rendering something simple as this doesn't work:

`<Pivot><PivotItem linkText="Customized Rendering" itemIcon="Globe" itemCount={ 10 }>test</PivotItem></Pivot>`

**Comment by OneCyrus** [comment]
it looks like the issue is in combination with react-hot-loader here

**Comment by OneCyrus** [comment]
the issue here is from type comparison in Pivot.base.tsx

https://github.com/gaearon/react-hot-loader/issues/954#event-1605189675
https://github.com/gaearon/react-hot-loader/issues/938

Probably changing to something like this should fix it:
`if (typeof child === 'object' && child.type === typeof(PivotItem)) {`

**Comment by michaelangotti** [comment]
@dzearing  Since there is a PR for this, can you please look at it?

**Comment by dzearing** [comment]
We should have a few more tests here. Katherine can help push the PR through.
