### ISSUE TITLE
Panel Component React: custom style className not applied in SPFx web part.

### ISSUE THREAD

**Issue by hbrigui** [OfficeDev/office-ui-fabric-react#4250]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: High 

Products/sites affected: SharePoint client side web parts.

#### Category
- [ ] Question
- [ ] Typo
- [x] Bug
- [ ] Additional article idea

#### Describe the issue:

Panel not affected when i use className={styles.CustomStyle} also for components introduced into Panel.

#### Actual behavior:

Panel and its components cannot use className custom styles

#### Expected behavior:

The custom styles should be possible for Panel and Modal Component

### If applicable, please provide a codepen repro:

i share with you code example which is employed in Spfx WebPart :

```
<Panel
           isLightDismiss={true}                          
           isBlocking={true}
           isOpen={this.state.showUsersListPanel}
           onDismiss={this.setshowUsersListPanel(false)}
           type={PanelType.medium}
           className={ styles.MarginPanel } /* this styles not loading and not working for Panel*/
           closeButtonAriaLabel='Close'>
<DetailsList
      className={ styles.DetailListSites } /* this styles not loading and not working for this component*/
      items={this.state.spPermissionsSiteInfo.usersList}
       selectionMode={SelectionMode.none}
       columns={[....]}
       onRenderItemColumn={ this._onRenderItemColumn }
  />
</Panel>
```

**Comment by Jahnp** [comment]
@hbrigui thanks for reporting and sharing the code sample. A few questions:
- What version of Fabric React are you seeing this behavior in?
- Does this only happen when applied within web parts?
  - Can you repro from a CodePen with a recent version of Fabric?

@manishgarg1 for FYI in case this is an issue with SPfx. Please loop in others as appropriate. Thanks!

**Comment by hbrigui** [comment]
@Jahnp  thanks for commented, so to answer your questions:     

- Office fabric ui used version is 1.4.3.
- For the time being I tested only on SPfx Web Part and I have never tested it for another case
         -> Ok, i will try to repro it on CodePen with recent version Fabric

Thanks !

**Comment by manishgarg1** [comment]
Hi @hbrigui, any updates on the codepen? it would be great to see a repro.

**Comment by harshdamaniahd** [comment]
Yes i can confirm , this is not working

**Comment by harshdamaniahd** [comment]
is this still not working ?

**Comment by micahgodbolt** [comment]
The className is passed the most outer div of the panel. You can pass a className to the 'main' section using the styles prop

https://codepen.io/micahgodbolt/pen/LMjggd
