### ISSUE TITLE
DetailsList {selectionMode={SelectionMode.none} bad first column width

### ISSUE THREAD

**Issue by stephenzsy** [OfficeDev/office-ui-fabric-react#426]
The first column width is to fit the content instead of a fixed width column when DetailsList has SelectionMode.none. Please fix.

**Comment by dzearing** [comment]
I definitely repro'd issues with the advanced example, which i will fix, but when i set selectionmode none, i don't see a bad first column width.

Is there a small isolated snippet you could provide? E.g. maybe modify one of the examples in the project.

**Comment by stephenzsy** [comment]
I think what I encountered is if I only set the minWidth but not maxWidth, I get the width of individual cells = max(content width, minWidth), instead of all cells in the column have the same width.

**Comment by dzearing** [comment]
Could you just pass in max being the same value?

The justified rendermode tries the size all the columns to fit in the visible space. So i believe passing in no max will stretch the columns to fit in the given space, and try to drop off columns if they cant fit.

If you would like something fixed here please provide some more detail. Repro steps, and a screenshot of what you're seeing would help.

**Comment by dzearing** [comment]
Closing this issue. Please re-open there is a specific bug that should be addressed and include more information (screenshots, repro).
