### ISSUE TITLE
High contrast black focus is hard to see on default button

### ISSUE THREAD

**Issue by RegexEmpire** [OfficeDev/office-ui-fabric-react#4271]
### Bug Report

- __Browser and OS versions__: Edge Win10

#### Priorities and help requested (not applicable if asking question):

Requested priority: Normal

Products/sites affected: VSTS

#### Describe the issue:

Focus cannot be seen after navigating to a default button in high contrast black.

Focused:
![image](https://user-images.githubusercontent.com/5342645/37421106-b4a12dd2-2775-11e8-802b-cd5d2e6f2342.png)
Not Focused:
![image](https://user-images.githubusercontent.com/5342645/37421130-c02db742-2775-11e8-967c-386ffbee73ee.png)

Repro can be seen on the office fabric components page

**Comment by lynamemi** [comment]
Thanks for reporting! I have a PR open to fix this here: #4221 , and we're tracking the bug here: #3419
