### ISSUE TITLE
Jasmine Tests Blowing Up on Pulling in Newer Fabric Version

### ISSUE THREAD

**Issue by alxHenry** [OfficeDev/office-ui-fabric-react#4277]
### Bug Report

- __Package version(s)__: 5.64.1
- __Browser and OS versions__: PhantomJS

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes. The culprit is BaseButton.tsx method _onRenderDescription the description is pulled off this.props instead of the passed in props object.

Requested priority: High

Products/sites affected: Yammer

#### Describe the issue:

Oddly when we try to pull our UI library that uses a new Fabric version into our front end codebase, our jasmine unit tests blow on with the following error:
```
    >> :9747 logCapturedError
    >> TypeError: undefined is not an object (evaluating 'this.props') at
    >> undefined:186 _onRenderDescription
    >> :161 _onRenderTextContents
    >> :0
    >> :133 _onRenderContent
    >> :110 render
```

...a bunch of stack trace

```
   >> The above error occurred in the <BaseButton> component:
    >>     in BaseButton (created by Button)
    >>     in Button
    >>     in Provider
```

#### Expected behavior:

Not to blow up when we import the new version.

**Comment by alxHenry** [comment]
It looks like the last change there was just a whitespace change. It hasn't really changed for 10 months, so I have no idea why this is exposed for us all of a sudden

**Comment by Jahnp** [comment]
@micahgodbolt for BaseButton.
