### ISSUE TITLE
DatePicker - Extra required indicator (*)

### ISSUE THREAD

**Issue by vollmerr** [OfficeDev/office-ui-fabric-react#4278]
### Bug Report

- __Package version(s)__: 5.64.1
- __Browser and OS versions__: Chrome, windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: DatePicker component

#### Describe the issue:

Required DatePicker fields are displaying an additional required indicator (*) after the right side of the field. This is inconsistent with other fields (TextField, etc)

#### Actual behavior:

Displaying a * after the DatePicker field. (In addition to the one after the label, which should be there)

#### Expected behavior:

Not displaying the * after the DatePicker field for required fields / only displaying the * after the label.

### If applicable, please provide a codepen repro:

Using the Required DatePicker Example:
https://codesandbox.io/s/p7983w20wm

**Comment by Jahnp** [comment]
This seems reasonable, but I'm not sure if there are cases where we'd want a required indicator when a label *isn't* there. That may not be a common or supported scenario, though. @johannao76 , @fpintos -- thoughts? Should the extra asterisk be removed from the input field?

![image](https://user-images.githubusercontent.com/307118/37446642-3a25a626-27db-11e8-8e14-b64bbdd7feba.png)

**Comment by lynamemi** [comment]
For TextField, we have logic to show the * only after the label, if there is a label. If there is no label specified, we render it after the input field.

**Comment by kevinkid** [comment]
If there isn't a handler for error messages the * is also shown. 

![](https://user-images.githubusercontent.com/9988671/37725433-01d44890-2d44-11e8-99d4-bca2639f3283.png)

**Comment by kevinkid** [comment]
If there isn't a handler for error messages the * is also shown. 

![](https://user-images.githubusercontent.com/9988671/37726457-760d2e8c-2d46-11e8-8bf5-51ece0ad74ef.png)

**Comment by petercutting** [comment]
yep, I am also getting 2 required asterisks on date field. 1 after the label and 1 after the field. Would prefer only 1, after label for consistency
