### ISSUE TITLE
List/DetailsList: support rendering some content in hidden scenarios.

### ISSUE THREAD

**Issue by Mustachoman** [OfficeDev/office-ui-fabric-react#428]
I am trying to use the Details list from the [Fabric UI test component](http://dev.office.com/fabric#/components/detailslist) however I noticed that the onRenderItemColumn is never called.

After playing with the inspect method suddenly the list appeared.

I can now recreate this by just loading the page where the list is supposed to render and then opening and/or closing the inspect function.

Wanted to post an issue with the list not rendering but found this so I think it is just a bug.

**Comment by dzearing** [comment]
Adjusting the title to be specific to DetailsList.

Are you rendering the list in a hidden element? The DetailsList requires being rendered in a visible container so that it can measure which columns should be rendered.

**Comment by Mustachoman** [comment]
Sorry for the late reply.

It is indeed in a panel which is hidden. Will try to add it to a visible page.

Update coming today then. ;)

**Comment by Mustachoman** [comment]
Okido, so as @dzearing said, the list renders on visible object only. 

Don't know if it is used much but lists do not work in things like panels then? Because the panel is not visible when loading the app?

**Comment by dzearing** [comment]
Yeah it's an unfortunate limitation. It's possible we could tweak the logic to say something like "if we are hidden, at least render 1 page of items". We may have this need for supporting SSR scenarios where you have nothing to measure.

I will change this to a feature request for List in general.

**Comment by dzearing** [comment]
The major problem we have is that we don't have a clean way to detect when the div becomes visible, so if we render not enough content to cover the screen, we don't get an opportunity to evaluate that so we end up a bit buggy.

Maybe something like this could be of use.

https://www.npmjs.com/package/element-resize-event

**Comment by Mustachoman** [comment]
@dzearing Awesome! Thanks for the help! :)

**Comment by dzearing** [comment]
Related bug: https://github.com/OfficeDev/office-ui-fabric-react/issues/260

**Comment by dzearing** [comment]
Actually i'll close this one and track with https://github.com/OfficeDev/office-ui-fabric-react/issues/260
