### ISSUE TITLE
Using office-ui-fabric-react styles in my component

### ISSUE THREAD

**Issue by aslanovsergey** [OfficeDev/office-ui-fabric-react#4281]
#### Describe the issue:

I am trying to create my own component using an example as blueprint 
https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/office-ui-fabric-react/src/components/pickers/TagPicker

The problem is with scss file
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/pickers/TagPicker/TagItem.scss

I can't find a replacement for this line
`@import '../../../common/common';`

and if I don't import it I can't use these
```
@include focus-border();

@include high-contrast {
   border: 1px solid WindowFrame;
}
```

**Comment by michaelangotti** [comment]
@dzearing Is there a good way to access common styles from the package?

**Comment by aslanovsergey** [comment]
I mean React component. This is a SharePoint framework web part solution. I took this example https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/office-ui-fabric-react/src/components/pickers/TagPicker copied and customized it slightly.

**Comment by aslanovsergey** [comment]
Could you say please where I can find this mixins

`@include focus-border();`

```
    @include high-contrast {
      border: 1px solid WindowFrame;
    }
```

**Comment by cliffkoh** [comment]
Hi @aslanovsergey are you still stuck on this? You can get the mixin from office-ui-fabric-core but our general guidance now is to move to JS styling. Let me know if you need a concrete example.

**Comment by Wezea** [comment]
Hi @cliffkoh, as you mentioned the general guidance is now to move to JS styling. I recently saw [this ](https://www.youtube.com/watch?v=Gznkmi4_KYc&t=38m29s) video, it shows, starting from minute 38, how to use the core styles by importing mixins. Are there already JS mixins for the core styles available?

**Comment by cliffkoh** [comment]
Of the top of my head, yes. @Vitalius1 is much more tuned-in here though and should be able to provide a more definitive guidance.
