### ISSUE TITLE
PeoplePicker: align suggestions to field width

### ISSUE THREAD

**Issue by Basek** [OfficeDev/office-ui-fabric-react#4282]
It would be great to have property like useComboBoxAsMenuWidth in ComboBox especially for case with itemLimit=1.

**Comment by Jahnp** [comment]
@joschect FYI--could you take a look at this when you have a chance? Thank you!

**Comment by oengusmacinog** [comment]
PeoplePicker, or the pickers in general, are designed as a multi-selection tool, as a result they are usually implemented quite wide so a prop like useComboBoxAsMenuWidth from ComboBox has not been implemented on it.

I am not sure about your exact requirements but this issue coupled with the other one you opened really makes it sound like the component you want is actually ComboBox and not PeoplePicker.  That component is designed for selecting one item yet allowing a lot of customization of the items in the dropdown/callout; You can use the Persona component to set up ComboBox to look like the PeoplePicker dropdown if that is what is desired.

I'm going to go ahead and close this issue.  If you run into any issues implementing ComboBox for your requirement feel free to open a new issue.

**Comment by Basek** [comment]
@oengusmacinog, ComboBox don't provide any property to change it appearance and I can't make it look like Persona. And I think it would be bad user experience if behavior for chosen one and many person will be different.
