### ISSUE TITLE
PeoplePicker: usability improvement for itemLimit=1

### ISSUE THREAD

**Issue by Basek** [OfficeDev/office-ui-fabric-react#4283]
It is necessary to remove selected person from picker before you can choose another person. It is normal behavior for multi-select case but in case with itemLimit=1 it become strange. It would be great to remove old one on click.

**Comment by Jahnp** [comment]
@joschect FYI--thoughts on this?

**Comment by oengusmacinog** [comment]
@Basek I spoke with a designer and it sounds like this would be a bit confusing in the context of the PeoplePicker.  It sounds like you may want to set up the ComboBox component to be a single person picker.  That component is set up to select one item from a group and can be set up to use Persona component and etc, which the pickers in general are designed so you can select multiple items in a group.

I am going to go ahead and close this issue, hopefully ComboBox will server your purpose better.
