### ISSUE TITLE
DatePicker usability when compared to non-React version

### ISSUE THREAD

**Issue by donaldallen** [OfficeDev/office-ui-fabric-react#4289]
I'm curious as to why the UI for the Fabric React DatePicker does not follow the same conventions as set in the non-React Fabric DatePicker?

![2018-03-15 13_02_38-office ui fabric js](https://user-images.githubusercontent.com/453784/37485484-2fbbaca0-2851-11e8-90db-c2e311c71e17.png)
Fabric DatePicker

vs

![2018-03-15 13_04_23-home - office ui fabric](https://user-images.githubusercontent.com/453784/37485568-7312cbbe-2851-11e8-80d9-f4de7444ea65.png)
Fabric React DatePicker

The up and down arrows feel wrong here. When I click down, it should select the previous year. However, it selects the next year. Up = increase, Down = decrease. Maybe this makes sense if you visualize the years in a dropdown list in numerical order, so you would go up or down in that case.

I also realize that this might be a Microsoft convention, because it's how the calendar works in Windows 10:

![2018-03-15 13_07_27-nvidia geforce overlay](https://user-images.githubusercontent.com/453784/37485760-fba843c8-2851-11e8-8b68-1d9e97e0147e.png)

However, Outlook uses left/right arrows:

![2018-03-15 13_08_55-calendar](https://user-images.githubusercontent.com/453784/37485801-173363a2-2852-11e8-9071-acdae4ab2c9c.png)

Google Calendar uses left/right arrows:

![2018-03-15 13_10_36-google calendar - march 2018](https://user-images.githubusercontent.com/453784/37485872-5524e96a-2852-11e8-910c-164b5498758d.png)

The most popular datepickers also use left/right arrows:

![2018-03-15 13_11_17-datepicker _ jquery ui](https://user-images.githubusercontent.com/453784/37485893-6606c2d0-2852-11e8-8afb-4a3e41cfe7ab.png)

![2018-03-15 13_11_53-dbushell_pikaday_ a refreshing javascript datepicker lightweight no dependenc](https://user-images.githubusercontent.com/453784/37485915-746bce92-2852-11e8-9127-4a25d7708479.png)

I know there's no right or wrong way here, but the way Fabric React bucks the trend here might warrant some user-testing. I tested this with a couple devs (by no means a thorough study at all), and the first click did not have the result they were expecting, causing slight confusion.

**Comment by michaelangotti** [comment]
@betrue-final-final Do you know why the design was changed?

**Comment by betrue-final-final** [comment]
Hi @donaldallen! I love your enthusiasm for doing what's right for humans. This is a case where we are actually improving the experience. 

1. Moving the arrows to the right side allows the "title" of the picker to align left and sit in a natural reading order. I don't think you thought that aspect was an issue though.
2. Why do the arrows move up and down? It's actually how the calendar is oriented. If you look at the calendar control, and most print calendars for that matter, the next month "peeks" out below the current one.
![image](https://user-images.githubusercontent.com/20363037/38584962-fd0cd9a6-3ccc-11e8-8466-ddf8d71460cd.png)
If you extend that to years, then it's just a bigger jump down the list.

I hope this help, and keep on contributing!

**Comment by gitfish** [comment]
Are you guys implementing extended year selection (available in the non-react version of fabric - and probably alluded to somewhere above)? i.e. a user clicks on the year and they get the lovely year navigation.

**Comment by betrue-final-final** [comment]
Hey @gitfish , why don't you log a fresh issue so we can track it?
