### ISSUE TITLE
Error by ScrollablePane and Sticky

### ISSUE THREAD

**Issue by Vintaurus** [OfficeDev/office-ui-fabric-react#4293]
### Bug Report

- __Package version(s)__: 5.64.0 - 5.64.3

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: 
I also copied the example from https://developer.microsoft.com/en-us/fabric#/components/scrollablepane "DetailsList Locked Header"

#### Describe the issue:
The solution is using without SharePoint Framework, just only JavaScript-File, HTML-Page, and web part Content Editor. In IE I cannot see the solution and got an error message. In Google Chrome I can see the component, but the ScrollablePane and Sticky don't work. 

The error message in IE 11 (11.0.49): 
SCRIPT5009: "Set" ist undefiniert
Datei: ScrollablePane.base.js, Zeile: 14, Spalte: 9

#### Actual behavior:

Sticky and Scroll don't work. 
#### Expected behavior:
Like the example from https://developer.microsoft.com/en-us/fabric#/components/scrollablepane "DetailsList Locked Header"

### If applicable, please provide a codepen repro:
Use an example from https://developer.microsoft.com/en-us/fabric#/components/scrollablepane "DetailsList Locked Header". Save as JavaScript-File, add to HTML-Page, upload to the Site Assets Library, use with the web part content editor.

**Comment by KevinTCoughlin** [comment]
@Vintaurus this seems like an ES6 compatibility issue with [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set), though IE 11 should have basic support. I can't repro the error standalone with IE 11 on https://developer.microsoft.com/en-us/fabric#/components/scrollablepane. There must be some issue with the specific setup on a SharePoint site. Are you still facing this in IE11?

FWIW I was using IE @ `11.0.44`.

**Comment by Vintaurus** [comment]
Hi Kevin, there is no issue on SharePoint site. I just tested also directly with Safari without SharePoint site. The problem also exists with Chrome. I'm using different components of Office UI Fabric and there are working fine, except Sticky and Scroll. Maybe the issue is by webpack, isn't it?

tsconfig.json: 
{
    "compilerOptions": {
        "outDir": "./dist/",
        "sourceMap": true,
        "noImplicitAny": false,
        "removeComments": true,
        "module": "commonjs",
        "target": "es5",
        "jsx": "react",
        "allowJs": true,
        "experimentalDecorators": true
    },
    "include": [
        "src/**/*"
    ],
    "exclude": [
        "node_modules",
        "**/*.spec.ts"
    ]
} 

package.json:
{
  "name": "ebrs_ui",
  "version": "0.0.1",
  "description": "eBRS 2.0 Frontend",
  "main": "webpack.config.js",
  "scripts": {
    "show": "webpack-dev-server --open --config webpack.dev.js",
    "build": "webpack --config webpack.prod.js",
    "dev": "webpack --config webpack.dev.js"
  },
  "author": "Vincent Rothländer",
  "license": "ISC",
  "dependencies": {
    "@types/react": "^15.6.7",
    "@types/react-dom": "^15.5.6",
    "npm": "^5.8.0",
    "react": "^15.6.2",
    "react-dom": "^15.6.2",
    "react-intl": "^2.4.0",
    "typescript": "^2.7.2"
  },
  "devDependencies": {
    "@microsoft/sp-core-library": "^1.4.1",
    "@types/node": "^9.4.6",
    "@types/react-intl": "^2.3.4",
    "@uifabric/icons": "^5.6.0",
    "awesome-typescript-loader": "^5.0.0-1",
    "axios": "^0.18.0",
    "clean-webpack-plugin": "^0.1.19",
    "copy-webpack-plugin": "^4.5.0",
    "css-loader": "^0.28.9",
    "es6-promise": "^4.2.4",
    "file-loader": "^1.1.11",
    "html-webpack-plugin": "^3.0.6",
    "intl": "^1.2.5",
    "jsnlog": "^2.26.1",
    "node-sass": "^4.7.2",
    "office-ui-fabric-react": "^5.64.3",
    "package": "^1.0.1",
    "prop-types": "^15.6.0",
    "react-custom-scrollbars": "^4.2.1",
    "sass-loader": "^6.0.6",
    "source-map-loader": "^0.2.3",
    "style-loader": "^0.20.1",
    "tslint": "^5.9.1",
    "tslint-react": "^3.5.1",
    "url-loader": "^1.0.1",
    "uuid": "^3.2.1",
    "webpack": "^4.1.1",
    "webpack-cli": "^2.0.12",
    "webpack-dev-server": "^3.1.1",
    "webpack-merge": "^4.1.2"
  }
}

webpack.common.js:
const path = require('path');
const webpack = require('webpack');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');

module.exports = {
    entry: {
        sp: './src/index_sp.tsx'
    },
    output: {
        filename: 'scripts/[name].ebrs20.js',
        path: __dirname + "/dist"
    },
    resolve: {
        // Add '.ts' and '.tsx' as resolvable extensions.
        extensions: [".ts", ".tsx", ".js", ".json"]
    },
    module: {
        rules: [
            // All files with a '.ts' or '.tsx' extension will be handled by 'awesome-typescript-loader'.
            { test: /\.ts(x?)$/, loader: "awesome-typescript-loader",  exclude: /node_modules/ },
            // All output '.js' files will have any sourcemaps re-processed by 'source-map-loader'.
            { enforce: "pre", test: /\.js$/, loader: "source-map-loader" },
            //{ test: /\.(png|svg|jpg|gif)$/, use: ['file-loader']},
            { test: /\.(png|jpg|jpeg|gif|svg)$/, loader: "url-loader?limit=100000" },
            {
                test: /\.(css|scss)$/,
                use: [{
                    loader: "style-loader" // creates style nodes from JS strings
                }, {
                    loader: "css-loader" // translates CSS into CommonJS
                }, {
                    loader: "sass-loader" // compiles Sass to CSS
                }]
            },
            //{ test: /\.xml$/, loader: 'xml-loader' } // will load all .xml files with xml-loader by default
        ]
    },
    plugins: [
        new CleanWebpackPlugin(['dist']),
        new CopyWebpackPlugin([
            { from: './node_modules/office-ui-fabric-react/dist/css/fabric.min.css', to: 'css/' },
            { from: './clientconfig.txt', to: '.' },
        ]),        
    ],
    // When importing a module whose path matches one of the following, just
    // assume a corresponding global variable exists and use that instead.
    // This is important because it allows us to avoid bundling all of our
    // dependencies, which allows browsers to cache those libraries between builds.
    externals: {
        "react": "React",
        "react-dom": "ReactDOM"
    }
};

webpack.dev.js:
const webpack = require('webpack');
const merge = require('webpack-merge');
const common = require('./webpack.common.js');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = merge(common, {
    mode: "development",
    // Enable sourcemaps for debugging webpack's output.
    //devtool: "source-map",
    //devtool: "inline-source-map",
    devServer: {
        contentBase: './dist',
        index: 'index_sp.html',
        openPage: 'index_sp.html?dCtx=654987',
        // incompatible with IE11, so wie have to disable HotModuleReplacement
        hot: false,
    },
    plugins: [
        new HtmlWebpackPlugin({
            filename: 'index_sp.html',
            template: 'index_sp.dev.html',
        }),
        new CopyWebpackPlugin([
            { from: './node_modules/react/dist/react.js', to: 'scripts/' },
            { from: './node_modules/react-dom/dist/react-dom.js', to: 'scripts/' },
        ]),        
        new webpack.NamedModulesPlugin(),
        // incompatible with IE11, so wie have to disable HotModuleReplacement
        //new webpack.HotModuleReplacementPlugin()
    ],
});

Let's me know, if you need more information.
