### ISSUE TITLE
ChoiceGroup focus order is incorrect in backwards keyboard navigation

### ISSUE THREAD

**Issue by satbai** [OfficeDev/office-ui-fabric-react#4298]
### Bug Report

- __Package version(s)__: Office Fabric 5.55.1
- __Browser and OS versions__: Edge

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

#### Describe the issue:
Keyboard navigation backwards is incorrect. Interesting detail is that after changing the selection it works as expected.

#### Actual behavior:
Going forward it's correct and focuses on the option that's selected. Going backwards the focus is on the last option instead of the selected option. 

Correct behavior forward
![image](https://user-images.githubusercontent.com/24945574/37535723-cce3d304-2905-11e8-90ce-4629ff66228e.png)

Incorrectbehavior backwards:
![image](https://user-images.githubusercontent.com/24945574/37535654-a273f66c-2905-11e8-8332-f04c97ec8d14.png)

#### Expected behavior:
![image](https://user-images.githubusercontent.com/24945574/37535755-eba51262-2905-11e8-82fc-2d44d78597ce.png)

I also have a question. Since the '5 seconds' dropdown is a part of one of the options, is it correct behavior for it to be focusable even when the option is not selected? When a screen reader sets focus on the dropdown they can't know that it's a part of the option in the choice group.

**Comment by dzearing** [comment]
I think this is technically correct. Each of the choice group options aren't tab stops. The choice group itself is a tab stop. A combo box is nested with it.

**Comment by dzearing** [comment]
Just to understand the native dom focus, I codepened this:

https://codepen.io/dzearing/pen/rdyJXx

@mikewheaton Not sure if you have background on choicegroup, but there seems to be something off here.

**Comment by dzearing** [comment]
I am closing, as this is not reproing on current Edge builds.
