### ISSUE TITLE
Update position of month paging arrows

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#4300]
To make the datepicker more readable and usable, as well as fix the reading order for screen readers, move the name of the month to the left and arrows to the right.

![image](https://user-images.githubusercontent.com/20363037/37545095-b4230e2e-2924-11e8-9db2-fa31b46868f8.png)

**Comment by lynamemi** [comment]
Talked to the calendar team, and they will plan to get to this May / June.
