### ISSUE TITLE
Input multiline inside Panel doesn't compatible with the auto spell check by Grammarly extension

### ISSUE THREAD

**Issue by quangleminhvn** [OfficeDev/office-ui-fabric-react#4305]
### Bug Report

- __Package version(s)__: office-ui-fabric-react v.5.41.2
- __Browser and OS versions__: Google Chorme v.64.0.3282.186

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: N/A

#### Describe the issue:

Step1: Install Grammarly extension. Restart Google Chorme browser .

Step2: Create a panel. Inside it, create an input multiline (text area).

Step3: Open that panel and fill any wrong word. Ex: contigiuration.

Step4:  Upon hovering the mouse on the wrong spelling words, it shows the correct word. Now click on the correct word twice to insert the word.

#### Actual behavior:

That word didn't change.

#### Expected behavior:

That word should change when click on the correct word

### If applicable, please provide a codepen repro:

https://codepen.io/write/input-inside-panel-doesn-t-compatible-with-the-auto-spell-check-by-grammarly-extension

![image](https://user-images.githubusercontent.com/16194968/37591947-bcaa5bc4-2b9f-11e8-8ddb-9d520834d0fd.png)

**Comment by quangleminhvn** [comment]
yeah - this codepen link just a code written in TSX of component Panel ( inside is an input) - please check the code

**Comment by oengusmacinog** [comment]
@quangleminhvn I am having trouble consistently reproducing.  Do you have a working codepen? I am having trouble getting Grammarly to even apply to this one [https://codepen.io/oengusmacinog/pen/BrOKjz](https://codepen.io/oengusmacinog/pen/BrOKjz) even though the same code works on my local build.

**Comment by quangleminhvn** [comment]
@michaelangotti @oengusmacinog 
Sorry guys - I've just created an app.
Please check this out: https://grammarly-bug.herokuapp.com/
I think Codepen doesn't work since the output is an iframe
