### ISSUE TITLE
DetailsList: Columns not resizing

### ISSUE THREAD

**Issue by erichdev** [OfficeDev/office-ui-fabric-react#4309]
### Bug Report

- __Package version(s)__: >=5.63.0

#### Describe the issue:

Columns aren't resizing. This can be reproed in the docs site. Also have a simple example in this Codepen: https://codepen.io/erichdev/pen/JLEday If you set it to a version below 5.63.0, column resize will work. 

Not sure if related to #4292 but this occurs even with non-grouped lists and even the headers aren't resizing.

**Comment by caradong** [comment]
Found the same issue with 5.63.0

**Comment by dzearing** [comment]
This was introduced with the `createRef` changes. There wasn't good unit test coverage around this scenario, so I have fixed the issue and added coverage. And a snapshot test around `DetailsHeader` while i was there.

**Comment by dzearing** [comment]
Will be published overnight.
