### ISSUE TITLE
[Persona] getStyles doesn't work

### ISSUE THREAD

**Issue by martellaj** [OfficeDev/office-ui-fabric-react#4315]
### Bug Report

- __Package version(s)__: Latest

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable)

#### Describe the issue:

getStyles prop doesn't add styles for Persona component.

### If applicable, please provide a codepen repro:

https://codepen.io/micahgodbolt/pen/LdxVoQ

**Comment by dzearing** [comment]
@mikewheaton You added the prop but never actually implemented it. Can you please finish the work?

**Comment by jordandrako** [comment]
@dzearing I'm taking over and working on this now.
