### ISSUE TITLE
Update Fabric XD Toolkit to version 4.0.0

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#4322]
We need to update the Fabric toolkit to the latest version, 4.0.0.
This will be the first semantically versioned Fabric toolkit. The new file can be found here:
https://microsoft.sharepoint.com/:u:/t/odspux/EaxyKH1AX_VLqZ6H4RyowsgBFEbkyZztFJJ2FE7gCKiGNQ?e=Hmh5i9

Changes include:

**Toggle**
- Increased size of focus to wrap label. This matches closer to checkbox and radio buttons, as well as aligns with Windows toggle.
- Fixed unselected toggle to match size of selected toggle. The border is a centered stroke which adds 1px width and height. Now both toggle shapes use a 2px stroke, with the unselected stroke being grey and the selected stroke matching the fill.

**Dropdown** 
- Consolidated focus, hover and pressed state text colors to neutralDark.
- Added caret to hover state of underline dropdown.
- Corrected multi-select version to checks to match Choice Group styles.

**Contextual menu** - Changed item height to 32px from 36px

**Added Indeterminate progress** - Element and guidance added to toolkit by @Rebhagat

**Message Bar**
- Fixed left margin bug in dismissible single line case
- Fixed contrast issue with icons
  - Change icon color to neutralSecondary
  - SevereWarning - Change icon color to redDark
  - Warning - Change icon color to neutralSecondary

**Checkbox and Choice Group** - Changed active border color to neutralSecondary from neutralPrimary

**Contextual Menu** - Changed section divider from neutralLight to neutralTertiaryAlt

**Message Bar** - Changed single line case to match button case height. (48px)

**Text field** - Changed "To:" label to neutralPrimary

**Tokens** - Corrected tag padding to be 8px instead of 12px

**Date picker**
- Updated date picker to match current Outlook design
- Moved month title to the left, and arrows to right, to increase readability, and accessibility.

**Tag picker** - Fixed height. Was 31px, needed to be 32px

**Face pile**
- Removed presence from 16px
- Corrected presence border in 24px

**Compound button blocking dialog**
- Corrected pressed state of compound button
- Corrected color of default button
- Corrected hover and pressed text colors

**File picker** - Corrected text colors and weights of site names

**Command Button** - Corrected menu item heights to 32px

**Theme primary color** - Updated to #0078d4 from #0078d7 to meet pass WCAG AA contrast for accessibility.

**Progress and loaders** - Changed filled color for determinate and indeterminate to themeDarkAlt and the track to neutralLighter to pass contrast.

**Comment by jordandrako** [comment]
Does this file live on the Fabric CDN?
