### ISSUE TITLE
CDN is missing icons from UI website.

### ISSUE THREAD

**Issue by jakelfield** [OfficeDev/office-ui-fabric-react#4333]
"The @uifabric/icons packages can resolve over 1000 different icons, and will download from the 10+ font partitions, minimizing download overhead. We also include the most common icons in the first partition, optimizing for the basic scenarios. If there are commonly used icons missing in there, please file an issue so that we can evaluate adjusting the primary partition"

Why is the CDN missing so many icons from https://developer.microsoft.com/en-us/fabric#/styles/icons#icons?

Is there a CDN that we should be using other than @uifabric/icons to get icons like 'Transition'?

**Comment by mikewheaton** [comment]
All of the icons you see there should be on the CDN. Are you getting an error, or the icon just isn't showing up? Here's a [CodePen demo of the Transition icon](https://codepen.io/mikewheaton/pen/GxWVMJ).

**Comment by jakelfield** [comment]
The icon "transition" was used but not registered. See http://aka.ms/fabric-icon-usage for more information.

Meanwhile, icons like Accept, PeopleRepeat, and others work fine.

I'm calling the icon via this in return method:
Calling icon via:
<Icon iconName='Transition' />

I declare the icon like so:
import { initializeIcons } from '@uifabric/icons';
initializeIcons();

**Comment by jakelfield** [comment]
Also, are you aware of how this web page loads via chrome vs edge:
![image](https://user-images.githubusercontent.com/27309532/37717390-7634664e-2cee-11e8-8ae1-fcf07e0975ad.png)

**Comment by mikewheaton** [comment]
Just to be sure, you're using `Transition` with an uppercase T, right? The icon names are case sensitive.

@lynamemi Do we have a bug for the issue with the icon grid in Chrome?

**Comment by lynamemi** [comment]
I got both Chrome and Edge to load the icon grid fully in reasonable time.

**Comment by jakelfield** [comment]
@mikewheaton 
Yes, iconName='Transition'

**Comment by jakelfield** [comment]
I made a mistake and didn't have the latest @uifabric/icons. After updating to 5.6.0, it started working. This should  have been the first thing that I checked.

**Comment by lynamemi** [comment]
Great, glad it's working now!
