### ISSUE TITLE
DetailsList not supporting high contrast for links inside it

### ISSUE THREAD

**Issue by Kanupriya9898** [OfficeDev/office-ui-fabric-react#4338]
### Bug Report

- __Browser __: Edge

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Blocking

#### Describe the issue:

For Office Fabric details list, if you go to high contrast mode, the links are not visible if the details list is in focus mode. The issue is not letting us use details list with links inside it. 

#### Actual behavior:

Under normal contrast this is the list:
![image](https://user-images.githubusercontent.com/31690904/37753534-6ef516aa-2dc3-11e8-8a6b-1cace9dea0ef.png)

Under high contrast white we have:
![image](https://user-images.githubusercontent.com/31690904/37753594-a9902962-2dc3-11e8-953c-fbd020586a39.png)

#### Expected behavior:

Links should be visible in focus mode also.

### If applicable, please provide a codepen repro:

https://codepen.io/dzearing/pen/LbORXM?editors=0010

**Comment by Kanupriya9898** [comment]
@michaelangotti Let me know if this will be fixed by the end of this week or not. Else we will have to look for some fix from our side.

**Comment by aditima** [comment]
@Kanupriya9898 - I am planning to work on this this week.

**Comment by Kanupriya9898** [comment]
I am a little confused as to why we have used >a to give the style. It would apply the style only to direct a children of the cell right. The style is not getting applied if there are some divs inside the detailsrowcell and then an a tag within them.
Please let me know if there is some reason as to why the style is applied this way.
