### ISSUE TITLE
how can i import table css in my react spfx solution

### ISSUE THREAD

**Issue by harshdamaniahd** [OfficeDev/office-ui-fabric-react#4341]
this is my tsx file :
import * as React from 'react';
import styles from './Reactform.module.scss';
import { IReactformProps } from './IReactformProps';
//import { escape } from '@microsoft/sp-lodash-subset';
import { TextField } from 'office-ui-fabric-react/lib/TextField';
import { DefaultButton } from 'office-ui-fabric-react/lib/Button';
import { Dropdown } from 'office-ui-fabric-react/lib/Dropdown';
import { Slider } from 'office-ui-fabric-react/lib/Slider';

import {
  Spinner,
  SpinnerSize
} from 'office-ui-fabric-react/lib/Spinner';
import { default as pnp, ItemAddResult } from "sp-pnp-js";
export interface IProduct {
  Product_x0020_Category: string;
  Title: string;
  Product_x0020_Quantity: number;
  Product_x0020_Cost: number;

}
export class CProduct {
  public ProductCategory: string;
  ProductName: string;
  ProductQuantity: number;
  ProductCost: number;
  constructor(item: IProduct) {
    this.ProductName = item.Title;
    this.ProductCategory = item.Product_x0020_Category;
    this.ProductQuantity = item.Product_x0020_Quantity;
    this.ProductCost = item.Product_x0020_Cost;
  }
}
export default class Reactform extends React.Component<IReactformProps, any>  {

  private CatgoryArray: Array<object> = [
    { key: 'Grocery', text: 'Grocery' }, { key: 'Office Products', text: 'Office Products' },
    { key: 'Electronics', text: 'Electronics' },
  ];

  constructor(props: any) {
    super(props);
    this.state = (
      {
        SProdName: '',
        SProdCost: '',
        ButtonText: 'Save',
        SStatus: '',
        SProdCategoryDropDownBind: this.CatgoryArray,
        SProductSelectedItem: '',
        SProdQuantity: '',
        visible: false,
        ProductItems: [],
      });
  }

  public render(): React.ReactElement<IReactformProps> {
    
    
    return (

      <div className={styles.reactform}>

       <table className='ms-Table'><thead><tr>
         <td>Name</td>
         <td>Category</td>
         <td>Cost</td>
         <td>Quantity</td>
         </tr></thead><tbody>
       {this.state.ProductItems.map((item: CProduct) => {
            return(
              <tr key={item.ProductName}>
              <td>{item.ProductName}</td>
              <td>{item.ProductCategory}</td>
              <td>{item.ProductCost}</td>
              <td>{item.ProductQuantity}</td>
              </tr>
            )
       })
      }
         </tbody></table>

        <div className='docs-TextFieldExample'>
          <TextField
            placeholder='Product Name'
            ariaLabel='Please enter text here'
            label="Enter Product Name"
            name="Field1"
            value={this.state.SProdName}
            onChanged={e => this.setState({ SProdName: e })}
          />
          <Slider
            label='Enter Quantity'
            min={1}
            max={100}
            step={1}
            defaultValue={1}
            showValue={true}
            value={this.state.SProdQuantity}
            onChange={e => this.setState({ SProdQuantity: e })}
          />
          <TextField
            className='NumberTextField-textField'
            label="Product Cost"
            value={this.state.SProdCost}
            onChanged={e => this.setState({ SProdCost: e })}
            onGetErrorMessage={this._validateNumber}
          />
          <Dropdown
            placeHolder='Select an Option'
            label='Category'
            id='Basicdrop1'
            ariaLabel='Category'
            options={this.state.SProdCategoryDropDownBind}
            onChanged={e => this.setState({ SProductSelectedItem: e })}
          />
          <br />
          <DefaultButton
            primary={true}
            data-automation-id='save'
            text={this.state.ButtonText}
            onClick={this.handleClick.bind(this)}
          />
          <div>
            <Spinner size={SpinnerSize.xSmall} className={this.state.visible ? styles.visiblityTrue : styles.visiblityFalse} />
          </div>

        </div>
        <p>{this.state.SStatus}</p>
      </div>

    );
  }
  public componentDidMount() {
    this._getProductItems()
  }
  private _validateNumber(value: string): string {
    return isNaN(Number(value))
      ? `The value should be a number, actual is ${value}.`
      : '';
  }
  private _getProductItems(): void {
    pnp.sp.web.lists.getByTitle("Product Inventory").items.get().then((items: any[]) => {
      debugger;
      let prodCollection = items.map(item => new CProduct(item));
      this.setState({ ProductItems: prodCollection });
    }

    )
  }
  private handleClick(this): void {
    this.setState({ visible: true });
    pnp.sp.web.lists.getByTitle("Product Inventory").items.add({
      'Title': this.state.SProdName,
      'Product_x0020_Category': this.state.SProductSelectedItem.text,
      'Product_x0020_Quantity': Number(this.state.SProdQuantity),
      'Product_x0020_Cost': Number(this.state.SProdCost),
    }).then((iar: ItemAddResult) => {
      this.setState({ SStatus: "Data Saved Successfully...." });
      this.componentDidMount();
      this.setState({ SStatus: '' });
      this.state = (
        {
          SProdName: '',
          SProdCost: '',
          ButtonText: 'Save',
          SStatus: '',
          SProdCategoryDropDownBind: this.CatgoryArray,
          SProductSelectedItem: '',
          SProdQuantity: '',
          visible: false,
          ProductItems: [],
        });
      this.setState({ visible: false })
    })
  }
}

**Comment by michaelangotti** [comment]
@manishgarg1 Can you look into this?
