### ISSUE TITLE
checkmark icon in the CheckBox control should have user-select: none

### ISSUE THREAD

**Issue by tpasi** [OfficeDev/office-ui-fabric-react#4345]
### Bug Report

- __Package version(s)__: 5.17.1

Requested priority: Low

#### Describe the issue:
I have changed the theme to use black as default background for the checkboxes when I click the checkbox multiple times I can see that there is a blue square around the checkmark icon
when I set 'user-select: none' then I don't have the blue square anymore

The icon should not be selectable inside the checkbox

**Comment by dzearing** [comment]
good call!
