### ISSUE TITLE
[Dropdown][Accessibility] Narrator says "editable combo box" for static dropdowns

### ISSUE THREAD

**Issue by AkshanshSrivastava03** [OfficeDev/office-ui-fabric-react#4360]
### Bug Report

- __Package version(s)__: office-ui-fabric-react@5.55.1004
- __Browser and OS versions__: Microsoft Edge

#### Describe the issue:
Narrator and Inspect tool show that dropdown's isReadOnly value is set to false, due to which narrator says editable combo box, although the dropdown component is not editable.

#### Actual behavior:
Editable combo box is a wrong role/value for narrator to speak.

#### Expected behavior:
Narrator should not say editable combo box

### If applicable, please provide a codepen repro:
This is present on https://developer.microsoft.com/en-us/fabric#/components/dropdown

#### Here is the narrator buddy text
Tab
Basic dropdown example, editable combo box,
Select an Option, collapsed,

**Comment by dzearing** [comment]
https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/#Listbox

**Comment by daweffe** [comment]
Yes, this needs to be a listbox. There is a bug opened on Planner by the accessibility team.
