### ISSUE TITLE
Missing release notes

### ISSUE THREAD

**Issue by daniel-white** [OfficeDev/office-ui-fabric-react#4361]
It appears that the release notes aren't being populated in Github. I really depended on those as a nice change log.

**Comment by lynamemi** [comment]
@dzearing it looks like this step is disabled in the release build definition - was that intentional?

**Comment by kanufy** [comment]
The release note is empty, but commits contains change logs. If this is intended, it will be hard to read the release information in the future.

![image](https://user-images.githubusercontent.com/8322617/37942615-07fed450-31af-11e8-95c9-a23ff3b05d20.png)

**Comment by dzearing** [comment]
Sorry all, they are temporarily disabled while our build service (which the release notes are sent from) is being update to support node 8. I'll manually run the update script in the mean time.
