### ISSUE TITLE
Unintuitive order for MessageBar and dismiss buttton

### ISSUE THREAD

**Issue by daniel-white** [OfficeDev/office-ui-fabric-react#4362]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority:  Normal 

Products/sites affected: Normal

#### Describe the issue:

The dismiss button for single line `MessageBar`s that have actions is in an odd/unintuitive place. On Windows and Office, the dismiss button is on the outer edge, to help with Fitt's Law.

#### Actual behavior:

On left to right the order is:

```
(Icon) Message               X  [Action]
```

![image](https://user-images.githubusercontent.com/735269/37916366-a0719af4-30e9-11e8-8f07-874fdbf9c1cb.png)

#### Expected behavior:

```
(Icon) Message              [Action]  X 
```

**Comment by betrue-final-final** [comment]
Can you provide an actual screenshot?

**Comment by daniel-white** [comment]
@betrue-final-final updated.

**Comment by betrue-final-final** [comment]
Ah, I see. That's definitely a bug, as you draw it how we designed it. I think that variant hadn't been included or tested in samples and needs to be corrected and added to the page. Thanks!

**Comment by betrue-final-final** [comment]
![image](https://user-images.githubusercontent.com/20363037/37918157-0dfa7434-30d5-11e8-90f3-0f3d221039d8.png)
