### ISSUE TITLE
[Tooltip Host] Not showing ellipsis in overflowing text

### ISSUE THREAD

**Issue by akashperfect** [OfficeDev/office-ui-fabric-react#4363]
### Bug Report

- __Package version(s)__: latest (5.70.0)
- __Browser and OS versions__: Chrome (any), Windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No, Reverting #3594 might help.

Requested priority: Blocking

Products/sites affected: VSTS

#### Describe the issue:

In case if overflowMode is not specified the tooltip is not being displayed.
Regression caused by: PR [#3594](https://github.com/OfficeDev/office-ui-fabric-react/pull/3594)

#### Actual behavior:

The tooltip is not being displayed when overflowMode is not specified in ToolTip component.

#### Expected behavior:

The tooltip should be displayed if even if overflowMode is not specified. Reason being I have a case where actual text is different then the tooltip text. As a result I always need to have a tooltip displayed. 
However, setting an overflowMode will display tooltip only when there is an overflow.

_This partially fixed for people using overflowMode: #3911_

### If applicable, please provide a codepen repro:

https://codepen.io/anon/pen/rdJvmR

**Comment by michaelangotti** [comment]
@lambertwang Need your input on this issue. Either need to revert or come up with another option.

**Comment by lambertwang** [comment]
I suppose if my changes were breaking, then we can revert them and accept that tooltip positioning will not work for IE11 since tooltip positioning not working isn't a breaking bug.

**Comment by akashperfect** [comment]
Hi, any updates on this? Its a blocking bug for our release. Can we take this change or propose something new?
