### ISSUE TITLE
`npm start`: Can't resolve 'awesome-typescript-loader'

### ISSUE THREAD

**Issue by warmsea** [OfficeDev/office-ui-fabric-react#4375]
### Bug Report

- __Package version(s)__: latest master (v5.71.0)
- __Browser and OS versions__: Windows and Mac

#### Priorities and help requested (not applicable if asking question):

Requested priority: Blocking

#### Describe the issue:

Pull the latest master (v5.71.0), run `npm install` and `npm start`, it shows the following error message:

```
ERROR in multi (webpack)-dev-server/client?http://localhost:4322 ./src/demo/index.tsx
Module not found: Error: Can't resolve 'awesome-typescript-loader' in '/Users/susu/GitHub/office-ui-fabric-react/packages/office-ui-fabric-react'
 @ multi (webpack)-dev-server/client?http://localhost:4322 ./src/demo/index.tsx
```

**Comment by dzearing** [comment]
I have checked in the fix to npm-start. We moved to `ts-loader`, but there was still a remaining reference to `awesome-typescript-loader`.
