### ISSUE TITLE
DetailsList: Accessibility - While navigating in the Table, focused row is getting selected.

### ISSUE THREAD

**Issue by caradong** [OfficeDev/office-ui-fabric-react#4381]
This is an accessibility bug.

### Bug Report
- __Package version(s)__: 5.70.0
- __Browser and OS versions__: Chrome, Edge and other browsers

#### Describe the issue:
Go to a table using DetailsList component,
Start navigating using Up/Down arrow key. The example on the official website contains the issues. https://developer.microsoft.com/en-us/fabric#/components/detailslist

#### Actual behavior:
While navigating using up/down arrow keys, currently focused ROW is getting selected. 

#### Expected behavior:
While navigating using up/down arrow keys, currently focused ROW should not be getting selected until user presses SPACE key.

**Comment by michaelangotti** [comment]
@caradong This is by design. If you hold down the control key while navigating up or down, it will change the focus.

**Comment by caradong** [comment]
Thank you @michaelangotti for your response. We received this bug from a MS internal accessibility testing team. I will circle back your comment.

**Comment by xarv** [comment]
@michaelangotti is there anyway to override this behaviour ?
