### ISSUE TITLE
[ComboBox] Issue with person picker implementation

### ISSUE THREAD

**Issue by Basek** [OfficeDev/office-ui-fabric-react#4383]
According to [issue 4282](https://github.com/OfficeDev/office-ui-fabric-react/issues/4282) I'm trying to implement person picker using ComboBox but it doesn't provide any property to change it appearance and I can't make it look like Persona. And I think it would be bad user experience if behavior for chosen one and many person (PeoplePicker) will be different.

**Comment by michaelangotti** [comment]
@oengusmacinog Can you advise?

**Comment by Basek** [comment]
any updates?

**Comment by oengusmacinog** [comment]
@Basek we are planning to do this as a feature request, but as of right now there is no time frame.  Is this a blocking issue on a particular project?

**Comment by Basek** [comment]
It isn't blocking issue for now. We made a couple of crutches to cover it but it would be great to remove them and use native support. I will have some time soon and could try to implement it if you explain your vision of it.

**Comment by oengusmacinog** [comment]
Stay alive!

**Comment by oengusmacinog** [comment]
Rounding back to this one.  @Basek are you still open to contributing through a PR? @betrue-final-final does this need design?  There's is a bit of UI/UX to this one that makes it a bit of a complicated feature.

**Comment by Basek** [comment]
Sorry, I won't have time for this in nearly future

**Comment by micahgodbolt** [comment]
@jspurlin is this something you've considered doing for the combo box? Maybe using the itemAs syntax, or some other custom render?

**Comment by philipzloh** [comment]
Does this do what you want, by the way? @Basek 
https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/office-ui-fabric-react/src/components/FloatingPicker

**Comment by jspurlin** [comment]
I'm slightly confused by this bug. @Basek , does the People Picker component not do what you are wanting?

Regarding the custom rendering of comboBox items,  yes, itemAs would be the right approach here... Better yet, it'd be good to investigate converting the custom Callout the comboBox uses to a ContextualMenu. If I remember correctly there, at least used to be, some behaviors on the ContextualMenu which prevented this

**Comment by Basek** [comment]
@jspurlin I had discussion about using it in [issue 4282](https://github.com/OfficeDev/office-ui-fabric-react/issues/4282)

**Comment by Basek** [comment]
@philipzloh I will check it but we are using 5 version of fabric for now.
