### ISSUE TITLE
When I close the Panel, the ms-layer and ms-panel elements are not removed from <body>

### ISSUE THREAD

**Issue by YusongLiu** [OfficeDev/office-ui-fabric-react#4396]
### Bug Report

- __Package version(s)__: 5.69.0
- __Browser and OS versions__: Chrome

#### Actual behavior:

The ms-layer and ms-panel elements are not removed from `<body>`

#### Expected behavior:

The whole ms-layer element should be removed from `<body>`

**Comment by michaelangotti** [comment]
@ThomasMichon Is this expected? cc:@dzearing

**Comment by michaelangotti** [comment]
@ThomasMichon Can comment on the above query? Thanks!

**Comment by JasonGore** [comment]
I tried reproducing this issue [here](https://developer.microsoft.com/en-us/fabric#/components/panel) but when as I open and close each panel the elements are being added and removed from `<body>`. I'm not sure if this was a problem that was resolved, but I will close for now. If you are still seeing an issue please feel free to reopen, providing a CodePen if at all possible. Thanks!
