### ISSUE TITLE
Date Picker position issue.

### ISSUE THREAD

**Issue by pavan2920** [OfficeDev/office-ui-fabric-react#4397]
Hi Guys, 

We are using Date picker control in our application. 

There is an request where we need to Freeze a Column in a table(Title in below image). We are able to do it using Position:sticky, But the Date Picker control is not stacking behind the fixed column(Behind title column). 

![image](https://user-images.githubusercontent.com/10346150/38078069-bd4877e4-3358-11e8-8ec9-b6b0f011960b.png)

Can any one help with the solution? 

Regards, 
Pavan.

**Comment by michaelangotti** [comment]
@pavan2920 Can you provide repro? Thanks!

**Comment by michaelangotti** [comment]
@lorejoh12 Can you look into this one?
