### ISSUE TITLE
Panel not showing and blocking user interactions in IOS under "-webkit-overflow-scrolling: touch"

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#4398]
### Bug Report

- __Package version(s)__: Latest
- __Browser and OS versions__: Safari, IOS, iPad or iPhone.

#### Priorities and help requested (not applicable if asking question):

Requested priority: Blocking

Products/sites affected: SharePoint mobile page, SharePoint mobile native apps.

#### Describe the issue:

1. Add this CSS style to body element: “-webkit-overflow-scrolling: touch”.
2. Open the page which can open <Panel /> in IOS devices with Safari.

#### Actual behavior:

Panel is not rendered.

#### Expected behavior:

Panel is rendered.

### If applicable, please provide a codepen repro:

I used this codepen example first: https://codepen.io/dzearing/pen/Rxxber
I can successfully open the panel at the right side.

Then I used this codepen that only changes one line of previous one (by addinng "-webkit-overflow-scrolling: touch;" to the body element) https://codepen.io/anon/pen/WzMyxm
I can no longer open the Panel.

**Comment by seriewe** [comment]
We observe the same  Issue  on modern SharePoint Online Sites with iPhone / iPad (Safari, Edge and  Chrome) the React Panel is not visible the overlay is transparent and user is kind of blocked. But for us it works if we disable -webkit-overflow-scrolling: touch on the body tag. Do somebody (Microsoft) know what the style is for?

![image](https://user-images.githubusercontent.com/10572013/39764510-0ea9a7b0-52e0-11e8-804f-939721616f85.png)

**Comment by ipip2005** [comment]
@natalieethell  we also had workaround by below overwritten:
```
  .ms-Layer-content > div {
    overflow-y: visible !important;
  }
```
We hope it can be fixed from component level so we don't need to hack everywhere using Panel

**Comment by natalieethell** [comment]
Hey @seriewe could you link a repro of this issue or perhaps a screen capture? And is your question regarding why the CSS style "-webkit-overflow-scrolling: touch" is specifically in the body tag, or why it's used at all?

@ipip2005 Good catch. It's such an odd bug. I'll investigate this further to check that your proposed change doesn't break anything else and see if that's something we can add.

**Comment by robpearmain** [comment]
@ipip2005 

Where in the webpart scss do I put

  .ms-Layer-content > div {
    overflow-y: visible !important;
  }

It seems dialogs are not showing on Sharepoint webparts on iOS either

**Comment by unowiz** [comment]
@robpearmain @ipip2005 
I added the style to as a global but as i wasn't sure the styles string route would apply to panel
//my component or webpart scss file
:global {
  .ms-Layer-content > div {
    overflow-y: visible !important;
  }
}
I had a last minute surprise with the office ui fabric dropdown control where on small device screen like iphone 5c, the dropdown didn't work due to panel issue.
