### ISSUE TITLE
SearchBox.types.d.ts error TS2307: Cannot find module '../Button'

### ISSUE THREAD

**Issue by cnshenj** [OfficeDev/office-ui-fabric-react#4402]
### Bug Report

- __Package version(s)__: 5.69.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

#### Describe the issue:

When module system is "amd" in tsconfig.json, compiling a project that imports SearchBox will generate this error.

#### Actual behavior:

Error TS2307

#### Expected behavior:

No error or warning.

**Comment by dzearing** [comment]
There is not enough information here. Do you have a project to share? Otherwise this is a needle in a haystack.

**Comment by michaelangotti** [comment]
@cnshenj Closing this until more information is provided.

**Comment by cnshenj** [comment]
Here is a project to repro the issue: https://github.com/cnshenj/playground
