### ISSUE TITLE
DestailsList: accessibility, up key does not move to the previous item when navigating in the table

### ISSUE THREAD

**Issue by caradong** [OfficeDev/office-ui-fabric-react#4406]
This is an accessibility bug.
### Bug Report

- __Package version(s)__:  5.70.0
- __Browser and OS versions__:  Chrome, Edge and other browsers

#### Describe the issue:

Go to a table using DetailsList component,
Start navigating using Up/Down arrow key.  The Down arrow moves to the next item in the table, but the up arrow key does not moves to the previous item.

The example on the official website contains the issues. https://developer.microsoft.com/en-us/fabric#/components/detailslist

#### Actual behavior:

The Down arrow takes moves to the next item in the table, but the up arrow key does not moves to the previous item.

#### Expected behavior:

The Down arrow moves to the next item in the table; the up arrow key should moves to the previous item.

**Comment by KevinTCoughlin** [comment]
Hmm I can't seem to repro this issue w/ `5.74.0` on https://developer.microsoft.com/en-us/fabric#/components/detailslist. I tried Edge, Chrome, & FF. Is this still happening for you @caradong?

My attempted repro steps were to focus an item in the table and then navigate items using Up/Down.

**Comment by michaelangotti** [comment]
@KevinTCoughlin We cannot repro this either. If you can provide a codepen that replicates this, we can reopen. Here's a codepen to start with: https://codepen.io/dzearing/pen/XRvXoL

**Comment by caradong** [comment]
I tried again on the official website and looks like this is fine now. Thank you guys for looking into this.
