### ISSUE TITLE
PageHeaderLinks scroll disabled

### ISSUE THREAD

**Issue by kevinkid** [OfficeDev/office-ui-fabric-react#4412]
### Bug Report

- __Package version(s)__: v5.66.0
- __Browser and OS versions__: Firefox/Chrome

#### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)

Yes , but i wish to on-board the office fabric team.

Requested priority: Normal (Blocking, High, Normal, Low)

#### Products/sites affected:

Office UI Fabric documentation site for react.

#### Describe the issue:

A while back when you clicked on the PageHeaderLink component the scroll animation happens then you couldn't scroll using the mouse. Now the scroll has been disabled except for Edge browser which works fine.

#### Actual behavior:

Animation scroll does not happen

#### Expected behavior:

When user clicks any of the PageHeaderLinks i.e `[ Overview, Best Practices, Variants, Implementation ]` it should scroll the target into view.

### If applicable, please provide a codepen repro:

[https://developer.microsoft.com/en-us/fabric#/components/commandbar#Implementation](https://developer.microsoft.com/en-us/fabric#/components/commandbar#Implementation)

**Comment by Jahnp** [comment]
@kevinkid can you confirm if this is still reproing for you? There was an issue with the site a few days ago that may have impacted this behavior, but no one in triage was able to repro. I'm going to go ahead and close this for now, but let us know if you're still seeing the issue. Thanks!
