### ISSUE TITLE
ContextualMenu: add ability to support icon URL's (onRenderItem for items to  render inside button )

### ISSUE THREAD

**Issue by yaananth** [OfficeDev/office-ui-fabric-react#442]
Hello,

The contextual menu (components/ContextualMenu/ContextualMenu) allows a list of items (IContextualMenuItem) to be sent.
An item takes property "icon", which by deefault is considered as a className, but there could be some cases where "icon" is a complete url for the image.
In which case, we should be rendering img tag.

In short:

```
<li role="menuitem" class="ms-ContextualMenu-item">
  <button class="ms-ContextualMenu-link" ...>
    <div class="ms-ContextualMenu-linkContent">
      <span class="ms-ContextualMenu-icon ms-Icon ms-Icon-- "></span> //<--- Ability to make this img tag or append img as a child to this
      <span class="ms-ContextualMenu-itemText ms-fontWeight-regular"></span>
    </div>
  </button>
</li>
```

Creating this issue as a feature ask, I will look at adding it myself if there's time, but putting it out there to track.
Since because of this, we are hacking up some code to render img tags, we definitely would like to pull the hack code out.

**Comment by dzearing** [comment]
I believe the items have an onRender. it's possible you could avoid the whole thing by rendering custom items with onRender and injecting img, svg or whatever you want.

**Comment by yaananth** [comment]
But can we call default onRender somehow? I don't want to loose click bindings etc.,
may be expose something like buildItems or something...

**Comment by dzearing** [comment]
You won't... see the ContextualMenu customization example for reference.

It will render content within the button. The "charms" sample renders custom icons.

```ts
  private _renderCharmMenuItem(item: any) {
    return <i className={ css('ms-Icon', 'ms-ContextualMenu-customizationExample-icon', 'ms-Icon--' + item.name) } />;
  }
```

Note that the charms still have hover/clicks.

**Comment by yaananth** [comment]
but would that also have submenu items and all that good stuff? I remember doing that, but click binding was gone.
I believe that's because it does this -

```
private _renderMenuItem(item: IContextualMenuItem, index: number, hasCheckmarks: boolean, hasIcons: boolean) { 
   if (item.onRender) { 
    return item.onRender(item); 
   } 
   // If the item is disabled then it should render as the button for proper styling. 
   if (item.href) { 
     return this._renderAnchorMenuItem(item, index, hasCheckmarks, hasIcons); 
   }
   return this._renderButtonItem(item, index, hasCheckmarks, hasIcons); 
} 

```

so I would miss other bindings if i have my own onRender isn't it?

**Comment by dzearing** [comment]
You're right! Oops.

I'm going to label as a feature request. We want onRenderItem that renders content inside the button.

**Comment by dzearing** [comment]
If you need this urgently, please do submit a PR. I've assigned to @joschect but he may not get to it soon.

**Comment by yaananth** [comment]
We have hack code that manipulates DOM to do the job for now, but I definitely would like to see this working, adding onRenderItem is probably the right feature ask here other than asking to support Icon URL's, I will edit the issue to be accurate, will get to this when I can.
Thanks!

**Comment by joschect** [comment]
@yaananth Hey, this was added recently. Instead of using icon, you can use iconProps to pass in any HTMLElement props to the icon. For icon name you'll want to pass in IconName.None and then you should be able to pass in styles as well which would include your iconurl. For example: `items=[{
                  key: 'newItem',
                  iconProps: {
                    iconName: IconName.None,
                    style: {
                      backgroundImage: 'url(\'<Your URL>')',
                      backgroundSize: '32px 32px',
                      width: '32px',
                      height: '32px',
                    }
                  }]`
would pass in 1 item with a custom icon sized to 32px by 32px.

**Comment by yaananth** [comment]
cool!! thanks, I will close this, I will verify later and reopen if there any issues. Thanks!

**Comment by yaananth** [comment]
I can confirm, that change made life easier. (Added backgroundImage, but added a css class name instead to handle other styles)
