### ISSUE TITLE
Distrusted SSL certificate for icons hosted by SharePoint Online CDN

### ISSUE THREAD

**Issue by joechung-msft** [OfficeDev/office-ui-fabric-react#4425]
### Bug Report

- __Package version(s)__: 5.63.0
- __Browser and OS versions__: Chrome, Windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low)
Normal (High when Chrome M70 lands)

Products/sites affected: (if applicable)

#### Describe the issue:

When using icons from the SharePoint online (SPO) CDN, Chrome reports this warning:

> The SSL certificate used to load resources from https://spoprod-a.akamaihd.net will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.

#### Actual behavior:

A warning is generated about deprecating request fulfillment from servers using deprecated SSL certificates in Chrome M70.  Requests for icons will be blocked once Chrome M70 lands.

#### Expected behavior:

No warning should be generated.  Requests for icons won't be blocked once Chrome M70 lands.

**Comment by manishgarg1** [comment]
After some internal investigation, it turns out that Akamai plans to roll out new certs before Chrome M70 is released.
