### ISSUE TITLE
The cursor is not displaying properly in the TextField in the Panel 

### ISSUE THREAD

**Issue by quangleminhvn** [OfficeDev/office-ui-fabric-react#4428]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: Iphone 5 (iOS 11.2.2)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix: No

Requested priority: Normal

#### Describe the issue:

- Open https://apple-cobbler-31745.herokuapp.com/ on the browser.
- Try to focus on start to end text field in the form and scroll the browser.

#### Actual behavior:

The cursor is not displaying exactly on the input. It's following the scroll action.

#### Expected behavior:

The cursor must display properly

### If applicable, please provide a codepen repro:

https://apple-cobbler-31745.herokuapp.com/

**Comment by Jahnp** [comment]
@quangleminhvn can you please provide more detail/repro steps on the issue? We tested the page you sent on an iPhone 7 Plus with the same OS version and weren't able to see any errant behavior.

**Comment by quangleminhvn** [comment]
Hi @Jahnp please try with iPhone 5 or 6 - after focus on the field at bellow - and then try to scroll the content - the cursor follows the scroll and not stick in the text field.

**Comment by newtonsheikh** [comment]
i checked this on my iPhone 5, looks like there is a rubber band like effect on the cursor. the cursor will follow the scroll but when you let go the cursor will go back to the text field. The effect is not that butter smooth may be that can be improved.

**Comment by quangleminhvn** [comment]
Hi guys -  please check it
![cursor-bug](https://user-images.githubusercontent.com/16194968/38347983-26190d4a-38c9-11e8-8a89-32c19033709a.gif)
Thanks!

**Comment by Jahnp** [comment]
Oh man--that's nasty. Thanks for sharing the video. Does it still allow text input as you would expect? 

It looks more like a browser/rendering issue than something that'd be easily solvable within the control, but we'll discuss/investigate what may be causing this.

@michaelangotti --it'd be good for us to discuss this at the next triage.

**Comment by quangleminhvn** [comment]
@Jahnp Yes, it does. We can enter text input as we expected

**Comment by michaelangotti** [comment]
@Jahnp  I will put this on the agenda for this mornings triage.

**Comment by natalieethell** [comment]
Update: it looks like this has been a known WebKit-specific issue for roughly 3 years: https://bugs.webkit.org/show_bug.cgi?id=138201. Investigating further to see if we can find a workaround!

**Comment by aditima** [comment]
@quangleminhvn - this sounds like a known webkit issue that Fabric doesn't have much control on. Closing.
