### ISSUE TITLE
[Dropdown][Firefox][HighContrast] Checkbox and list items don't follow high contrast standards

### ISSUE THREAD

**Issue by yaananth** [OfficeDev/office-ui-fabric-react#4435]
https://developer.microsoft.com/en-us/fabric#/components/dropdown 

**Expected Behavior:**
Check boxes and list items should follow the HC Standards.
It should be 
In HCB:
Text is in Black color with blue background.
In HCW:
Text is in White color with violet background.

Edge HCB (Valid):
![image](https://user-images.githubusercontent.com/12280011/38212310-44cd8864-368b-11e8-859c-33bdda5e53d5.png)

Edge HCW (valid):
![image](https://user-images.githubusercontent.com/12280011/38212363-83d95466-368b-11e8-975b-b3bb821fd647.png)

**Actual Behavior:**
Check boxes and list items are not following the HC Standards
In HCB:
Text is in White color in blue background.
In HCW:
Text is in black color in violet background.

Firefox HCB  (Issue):
![image](https://user-images.githubusercontent.com/12280011/38212324-58514b50-368b-11e8-85c7-98b860cb6c8d.png)

Firefox HCW (issue):
![image](https://user-images.githubusercontent.com/12280011/38212384-94a011cc-368b-11e8-96d8-31dcf2c31658.png)

Relevant high contrast issue #3570 (firefox button doesn't follow high contrast standards)

**Comment by michaelangotti** [comment]
@yaananth We have concluded that we cannot reasonably support Firefox HighContrast. We do have PR's open to address this Edge and IE. Will close this for now, but will revisit in the future.
