### ISSUE TITLE
[Accessibility][ContextualMenu] We need the ability to choose between checkbox and radiobutton control types

### ISSUE THREAD

**Issue by daweffe** [OfficeDev/office-ui-fabric-react#4437]
### Bug Report

- __Package version(s)__: 5.57.0
- __Browser and OS versions__: all

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Planner

#### Describe the issue:

Planner uses the checked property on ContextualMenuItems in a couple of places. For one, they are true check boxes, where any number can be controlled independently. In another menu, they are used more like a radio button, where only one can be selected at a time. 

We are happy with the visual UI, but need the ability to have control type for the menu items be "radio button" for some menus and "checkbox" for others. This would control the role attribute on the items.

This was filed as an MAS bug on Planner.

**Comment by angallison** [comment]
@daweffe - Will you please share screens that show the two menus?

**Comment by betrue-final-final** [comment]
@angallison, 
The menus look the same. Its the ARIA role that is different.

**Comment by dzearing** [comment]
ohhhh I think we misunderstood the ask. That makes sense. Allow role to be adjustable on a contextualmenuitem.

**Comment by michaelangotti** [comment]
@angallison @dzearing Shaking the tree on this one. What are the next steps?

**Comment by angallison** [comment]
@michaelangotti - It sounds like this is related to the ARIA role and is a code issue and no design is work needed.

**Comment by micahgodbolt** [comment]
@KevinTCoughlin is this a tweak you can make while you're in the ContextualMenuItem? Otherwise, I can work on this after you finish your css-in-js refactor.

**Comment by KevinTCoughlin** [comment]
@micahgodbolt I'll take it while I'm in there for #4169

**Comment by KevinTCoughlin** [comment]
@daweffe, I believe we already support the scenario of customizing `ContextualMenuItem`'s `role=` attribute via 

https://github.com/OfficeDev/office-ui-fabric-react/blob/4fe527471862ad3c83da9074a0cbcfcf07942c82/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.types.ts#L429

Here's a [Codepen example](https://codepen.io/kevintcoughlin/pen/NBmWbx) using the above. Does that unblock you or am I misunderstanding the ask?

**Comment by daweffe** [comment]
Thanks for the help. That should meet our needs.

Darin

**Comment by KevinTCoughlin** [comment]
Closing as the above API suggestion unblocks the scenario.
