### ISSUE TITLE
Long string is not truncated caused by .value cant access the element.

### ISSUE THREAD

**Issue by qianghuang94** [OfficeDev/office-ui-fabric-react#4439]
### Bug Report

- __Package version(s)__: 5.77.0

#### Priorities and help requested (not applicable if asking question):

Requested priority: (High) 

Products/sites affected: (ODSP)

#### Describe the issue:
When using document card with long string, the string should be truncated and at most with two lines.
```
<DocumentCard onClickHref='http://bing.com' type={DocumentCardType.compact}>
        <DocumentCardPreview { ...previewProps } />

        <DocumentCardTitle
          title='Large_file_name_with_underscores_used_to_zxcxzcxzcxzcxzseyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyxcxzcxzcxzcxzseparate_all_of_the_words_and_there_are_so_many_words_it_needs_truncating.pptx'
          shouldTruncate={ true }
        />
        <DocumentCardActivity
          activity='Created a few minutes ago'
          people={
            [
              { name: 'Annie Lindqvist', profileImageSrc: "https://www.bing.com/images/search?view=detailV2&ccid=AXsUAimc&id=C44396A18703294AD33F87CEC13CF2A971FFA808&thid=OIP.AXsUAimcTivdYp9gFcXUcwHaF6&q=image&simid=608046403537602042&selectedIndex=11"}
            ]
          }
        />
      </DocumentCard>
```

#### Actual behavior:

The third line displayed and not fully displayed.
![image](https://user-images.githubusercontent.com/15025186/38229543-deea845a-373b-11e8-81f6-9879ee1552be.png)

#### Expected behavior:

The long string should be truncated and at most two lines.

#### Changes that Introduced the bug
https://github.com/OfficeDev/office-ui-fabric-react/commit/856989f01186c078741a64fb3bf7c6371b6439bd#diff-0b04456ff15834b983faa2ba7da712c1

```
     // Save the width we just started truncation at, so that later we will only update truncation if necessary
-    this._truncatedTitleAtWidth = this._titleElement.clientWidth;	
+    if (this._titleElement.value) {
+      this._truncatedTitleAtWidth = this._titleElement.value.clientWidth;
+    }
```
The `.value` of `this._titleElement` cant access the `this._titleElement`.
Don't know why it is added, so cant open a PR to fix it by removing the `.value`

The screenshot of debugging the titleElement
![1](https://user-images.githubusercontent.com/15025186/38229750-b6909200-373c-11e8-8dd3-8f8c3fcdca3d.png)

**Comment by qianghuang94** [comment]
Check this out https://developer.microsoft.com/en-us/fabric#/components/documentcard
The sample even are not truncated correctly.

**Comment by Markionium** [comment]
The if check was added so that we handle the case where the reference is not set. 

Returning `false` here seems incorrect. But we can not access the scrollHeight of an element when we do not have a reference to this element yet.

**Comment by qianghuang94** [comment]
@Markionium Yep, the key is we should check the `this._titleElement` not the `this._titleElement.value`

**Comment by Markionium** [comment]
Well the `.value` would reference the dom element in this case (since it's a Reference object). So i think the .value is actually correct, but there is something else that is wrong. :)

```ts
private _titleElement = createRef<HTMLDivElement>();
```
