### ISSUE TITLE
Improve text field control to show different states of the input below the text field - Right now only Error is supported

### ISSUE THREAD

**Issue by StfBauer** [OfficeDev/office-ui-fabric-react#4440]
#### Describe the issue:
With the TextField component, you have the possibility to show an error message below the text field. Sometimes it might be useful to have a success message coupled to the text field too. This is currently not possible.

#### Actual behavior:
Setting the error message shows a red error message but I'd like to be able to show different messages based on the data put in the TextField.

#### Expected behavior:
Multiple options for:
- Error
- Success
- Warning

**Comment by aditima** [comment]
@betrue-final-final - do we want something like this? Wanted to hear your opinion here...

**Comment by StfBauer** [comment]
@betrue-final-final If you implement it like this, then you are right, but this is not a typical use case.. ;)

It is more an option not a must to follow your argumentation even the error message doesn't make sense because potentially you could have error messages everywhere.

It is more additional options show a different kind of state if needed.

On some fields, I like to evaluate and give instant feedback I can write the message in the error field that everything is correct, but then it is coloured red not green. ;)

The only way right now is to use an additional label for success messages next to the field and colour the text green. If this is the way to go it works but does the error message then makes sense either if it is not applicable for all fields? I don't think so. A more common case but to have it on the control. I doubt that.

**Comment by betrue-final-final** [comment]
I'm not sure I understand your response.  The image I shared is a success message attached to the specific control, which is what I thought you needed. 

Can you describe an end user scenario, where the shown success message doesn't work? Is it that you just want it to be green?

**Comment by StfBauer** [comment]
Well honestly I don't know which component you are referring to:

Like mentioned in the Title I refer to TextField as shown in the documentation:
https://developer.microsoft.com/en-us/fabric#/components/textfield

**Comment by StfBauer** [comment]
Well, and thanks for the bot ;) Would be nice to get any kind of feedback.

**Comment by betrue-final-final** [comment]
Apologies! I just saw this again. Your request seems reasonable after looking at this again. @dzearing, is this doable?

**Comment by dzearing** [comment]
I would prefer to keep this out of the TextField, honestly. Reasoning is that the author is free to implement status around TextField to render anything they want. Even in the Save example above, it has a green icon next to blue text. Is that the design for every status message?

All that said, we are going to refactor TextField to simplify and provide layered abstractions for this behavior in #6827. We should consider this for the new version and perhaps create a wrapper around TextField.

Closing this issue and tracking TextField work there.

**Comment by StfBauer** [comment]
Perfect. Sounds great to me.
