### ISSUE TITLE
How to change the Font size of Breadcrumb? 

### ISSUE THREAD

**Issue by pavan2920** [OfficeDev/office-ui-fabric-react#4442]
Hi Guys, 

I am using Breadcrumb(https://developer.microsoft.com/en-us/fabric#/components/breadcrumb)

Here i want to control(reduce) the font size, how can i do it? by default its 21px. 

![image](https://user-images.githubusercontent.com/10346150/38245778-20c06b9e-375d-11e8-85c2-84dacaaca3f8.png)

And default styles as below

![image](https://user-images.githubusercontent.com/10346150/38245821-453b293c-375d-11e8-8276-1bcba09eaf16.png)

Regards, 
Pavan.

**Comment by mahesh087** [comment]
Hey,

Try using custom render item method.

![breadcrumb](https://user-images.githubusercontent.com/38038844/38247828-2cbf12e0-3764-11e8-8820-b3c1da37e48a.JPG)

Cheers!

**Comment by pavan2920** [comment]
Hey thanks manhes, works. :)
