### ISSUE TITLE
Inline TextField and DefaultButton

### ISSUE THREAD

**Issue by Drakota** [OfficeDev/office-ui-fabric-react#4451]
#### Describe the issue:
Hi, I'd like to display a TextField with a DefaultButton on the right side. I'd like to know what would be the best "Fabric" way to do this. In Bootstrap you have InputGroups, but I can't find the same for Fabric. Why is that? I've looked in the docs and I can't seem to find what I'm looking for.

**Comment by oengusmacinog** [comment]
@Drakota Fabric React has some ready-made components for specific situations like date-picking, etc that you can see here: https://developer.microsoft.com/en-us/fabric#/components/textfield#ImplementationExamples.  There is not currently any open-ended features exactly like Bootstraps input group, but you can wrap the DefaultButton and Textfield with a wrapper and style it with any custom CSS you like.
