### ISSUE TITLE
NavLink and Link component always provide tooltips and aria labels even when explicitly asked not to

### ISSUE THREAD

**Issue by sidroopdaska** [OfficeDev/office-ui-fabric-react#4453]
### Bug Report

- __Package version(s)__: 5.78.0
- __Browser and OS versions__: All browsers

Are you willing to submit a PR to fix? **Yes**

Requested priority: **High** as its a poor A11y experience 

Products/sites affected: It's still being developed internally at Microsoft

#### Describe the issue:
A **tooltip** and **aria-label** are provided for both NavLink and Link components even when the user explicitly specifies not to. 
 
#### Actual behavior:
This results in a poor a11y experience since the content is read out many times.

#### Expected behavior:
Should only be provided when the developer explicitly specifies to do so.

**Comment by michaelangotti** [comment]
@sidroopdaska Checking in on this one. Is there a solution or can you please open a PR for it? Thanks!
