### ISSUE TITLE
Context Menu Items are misaligned due to check marks

### ISSUE THREAD

**Issue by jdrush89** [OfficeDev/office-ui-fabric-react#4457]
### Bug Report

- __Package version(s)__: 5.66
- __Browser and OS versions__: Chrome

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low)  Normal

#### Describe the issue:

Header Items in context menus are misaligned if any item in the menu has a checkmark while other items use a custom onRender.  It looks like if any item has a checkmark, the header will render a placeholder icon for the checkmark.  This will align the header with a choicegroup, but any other sections that have items with custom onRenders will be misaligned.  Either headers need to ignore checkmarks and stay left aligned, or hasCheckmarks needs to be passed in to item.onRender so it can handle rendering a placeholder icon.

How it used to be:
<img width="185" alt="contextmenuheaderleftaligned" src="https://user-images.githubusercontent.com/955442/38327109-6805183e-3815-11e8-8ea6-9d31c3b77676.png">

How it is now:
<img width="157" alt="contextmenuheadermisaligned" src="https://user-images.githubusercontent.com/955442/38327118-7267f166-3815-11e8-9e70-4155634ea93e.png">

#### Actual behavior:

Items with custom onRender functions are misaligned from their headers

#### Expected behavior:

Headers and items should be consistently aligned

**Comment by michaelangotti** [comment]
@joschect  We should make sure there is a visual regression test for this if there isn't already.

**Comment by jdrush89** [comment]
@joschect @michaelangotti Do you know which solution you prefer (either keeping the headers left aligned for check marks or passing hasCheckmarks to item.onRender)?  I think the second solution would look a little nicer but requires work from everyone already using a custom onRender.
