### ISSUE TITLE
DetailsList drag and drop is not keyboard accessible

### ISSUE THREAD

**Issue by satbai** [OfficeDev/office-ui-fabric-react#4459]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: all

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

#### Describe the issue:

DetailsList dragDropEvents props does not make dragging accessible by keyboard. I believe the common key combination to drag and drop would be holding Ctrl key down and using the arrow keys to move the element.

#### Actual behavior:
Changing the order of the DetailsList rows is not possible by using only keyboard.

#### Expected behavior:
Dragging and dropping should be possible using a keydoard if it's possible using a mouse. 

### If applicable, please provide a codepen repro:
https://developer.microsoft.com/en-us/fabric#/components/detailslist
![image](https://user-images.githubusercontent.com/24945574/38327550-58fbaf64-37fd-11e8-8510-0e0418f56b31.png)

**Comment by betrue-final-final** [comment]
Great issue. I just got back from CSUN where there was a great presentation on supporting this.

**Comment by Jahnp** [comment]
We talked about this and agree this is a useful scenario, but it's not something that would be intrinsic to the DetailsList itself--it would need to be added as a higher-order component. Right now we don't have plans to add a formal implementation for this, but if this is something you need, you should have the tools to implement this as a higher-order component in your application.

**Comment by betrue-final-final** [comment]
Good point Peter. I was also thinking about if this is a sorting vs. a moving scenario. The accessible UX patterns for that can be quite different.
