### ISSUE TITLE
Provide official codepen playground.

### ISSUE THREAD

**Issue by lijunle** [OfficeDev/office-ui-fabric-react#4471]
**THIS IS NOT A TECHNICAL ISSUE.**

Every time I want to check some new features or technical issue in fabric-react, it is hard to bootstrap the environment locally or online.

If we check [React tutorial](https://reactjs.org/tutorial/tutorial.html), it provides the codepen playground on each step. Fabric-react should do the similar thing.

I know that the [fabric website](https://developer.microsoft.com/en-us/fabric#/components/button) has examples on each component, but that is far from enough.

AFAIK, @dzearing has a [personal collection](https://codepen.io/collection/DQGpGm/#) on some components. But that is a little bit out of dated and hard to find. We should prompt them in the tutorail and in home page as React did.

Ideas or concerns?

**Comment by KevinTCoughlin** [comment]
Codepen templates might shine here -- https://blog.codepen.io/documentation/api/templates/

Personally, I've been forking @dzearing's personal collection.

**Comment by JasonGore** [comment]
We have a feature that has just been merged with #5897 that will expose an `Export to Codepen` feature on many of Fabric's components such as [Label](https://developer.microsoft.com/en-us/fabric#/components/label). We won't get 100% coverage but this will cover the majority of components. I'll close this issue as resolved for now but feel free to reopen or add comments as needed.

![image](https://user-images.githubusercontent.com/26070760/44178718-7acceb80-a0a8-11e8-8662-1a8d99c3e0fa.png)
