### ISSUE TITLE
Using arrow keys(up/dn) on context menu, one can focus on disabled items.

### ISSUE THREAD

**Issue by shankyty** [OfficeDev/office-ui-fabric-react#4472]
### Bug Report

- __Package version(s)__: 5.66.1001

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
**No**
Requested priority: (Blocking, High, Normal, Low) 
**Low**
Products/sites affected: (if applicable)

#### Describe the issue:
When user selects context menu using up/dn keys. It focuses on disabled items in menu.

![image](https://user-images.githubusercontent.com/5140562/38356284-f54d7c82-38dc-11e8-91a8-8faedba4e51c.png)

#### Actual behavior:

![image](https://user-images.githubusercontent.com/5140562/38356284-f54d7c82-38dc-11e8-91a8-8faedba4e51c.png)

#### Expected behavior:
While cycling through context menu items using up/dn keys, skip disabled items. 

### If applicable, please provide a codepen repro:

**N/A**

**Comment by michaelangotti** [comment]
@shankyty This is by design in order for screen readers to more easily readout disabled items.
