### ISSUE TITLE
Icon button has imperceptible interaction states

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#4479]
It's nearly impossible to see if you are successfully hovering over an icon button, and it should align to our other button states. Which one is being hovered?
![image](https://user-images.githubusercontent.com/20363037/38426312-32921c9a-396b-11e8-97d5-7191a6102cb9.png)

It's the one on the right! Anyway we should do interactive states like this:
![image](https://user-images.githubusercontent.com/20363037/38426456-8c26b8d8-396b-11e8-9564-2b7ae4e14cf4.png)

**Comment by aditima** [comment]
@Jahnp @michaelangotti - this seems a fair ask. Can you please assign this to a design dev to fix?

**Comment by Jahnp** [comment]
Makes sense to me. @jordandrako can you work with @betrue-final-final on the fix for this?

**Comment by jordandrako** [comment]
For sure, I'll take a look.
