### ISSUE TITLE
Error when DialogFooter contains exactly one child.

### ISSUE THREAD

**Issue by ronaldborman** [OfficeDev/office-ui-fabric-react#448]
When I use a DialogFooter component with exactly one button:
`<DialogFooter>`
  `<Button>Ok</Button>`
`</DialogFooter>`
I receive the error "Object doesn't support property or method 'map'". When using two or more children there is no problem.

Looking at https://github.com/OfficeDev/office-ui-fabric-react/blob/master/src/components/Dialog/DialogFooter.tsx I think the problem is that this.props.children in the method _renderChildrenAsActions must always be an array.

Although not crystal clear in the Facebook React documentation, this.props.children can be several types, based on the usage. In the case of a single child component, it doesn't seem to be an array but a single element (that doesn't have a method map).

**Comment by dzearing** [comment]
@micahgodbolt when you get a chance can you take a look?

**Comment by micahgodbolt** [comment]
@dzearing and @ronaldborman - yup, can't do .map on an object. Instead of splitting the logic and having 2 different returns I just made sure that children is always an array, even if just an array of 1 object.
