### ISSUE TITLE
Loading a partial custom theme changes some default Fabric colors

### ISSUE THREAD

**Issue by trevorsg** [OfficeDev/office-ui-fabric-react#4480]
### Bug Report

- __Package version(s)__: styling@master

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No - I think someone with a bit more knowledge of how this works should fix, or at least walk me through it.

Requested priority: normal - workaround available

Products/sites affected: VSTS

#### Describe the issue:

Calling `loadTheme()` from the OfficeFabric/Styling package will change more than you ask for. If you pass in an object for semantic colors that does not contain all colors, it will augment the object by filling in defaults. However, the defaults it uses seem to be hard-coded in this file, and they are different than the defaults used when loadTheme is not used at all.

See: https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/styling/src/styles/theme.ts

Specifically, "errorText" becomes "redDark" (line 135) but if you look at https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/common/_themeOverrides.scss you will see the default is supposed to be #333333.

#### Actual behavior:

When `loadTheme()` is called with a partial semantic theme, as long as `errorText` is not specified, error MessageBar components will have red text instead of dark gray.

#### Expected behavior:

Calling `loadTheme` does not affect semantic values that are omitted.

**Comment by Jahnp** [comment]
@phkuo I assume this isn't expected behavior, right? Could you take a look at this when you have a chance?

**Comment by michaelangotti** [comment]
@Jahnp @phkuo Just getting this back on your radars so we can (hopefully) resolve.
