### ISSUE TITLE
error: no mixin named focus-border office ui fabric react.Issue when referring common

### ISSUE THREAD

**Issue by harshdamaniahd** [OfficeDev/office-ui-fabric-react#4492]
Requested priority: (Blocking, High, Normal, Low)  : High
#### Describe the issue:
I have created a sharepoint react framework solution.This solution uses List Component.I now want to use the (https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/List/examples/List.Basic.Example.scss) in my solution.
@import '../../../common/common';

:global {
  .ms-ListBasicExample-itemCell {
    @include focus-border();

    min-height: 54px;
    padding: 10px;
    box-sizing: border-box;
    border-bottom: 1px solid $bodyDividerColor;
    display: flex;
  }

  .ms-ListBasicExample-itemCell:hover {
    background: #EEE;
  }

  .ms-ListBasicExample-itemImage {
    flex-shrink: 0;
  }

  .ms-ListBasicExample-itemContent {
    @include margin-left(10px);
    overflow: hidden;
    flex-grow: 1;
  }

  .ms-ListBasicExample-itemName {
    @include ms-font-xl;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }

  .ms-ListBasicExample-itemIndex {
    font-size: $ms-font-size-s;
    color: $ms-color-neutralTertiary;
    margin-bottom: 10px;
  }

  .ms-ListBasicExample-chevron {
    align-self: center;
    @include margin-left(10px);
    color: $ms-color-neutralTertiary;
    font-size: $ms-font-size-l;
    flex-shrink: 0;
  }
}
So i created a file called list.module.scss and copied the code above.
But it gives an error
![image](https://user-images.githubusercontent.com/11780473/38486904-03d27240-3bfc-11e8-9713-812d0fb6d1ac.png)

Any help will be appreciated.

**Comment by mikewheaton** [comment]
Could we update it to use the [directionality mixins in Fabric Core](https://github.com/OfficeDev/office-ui-fabric-core/blob/master/src/sass/mixins/_Directionality.Mixins.scss)?

**Comment by harshdamania** [comment]
Hi all,
This is what i implemented
1. Copied all css from List example https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/List/examples/List.Basic.Example.scss
2. Remove @import '../../../common/common';
3.Added the line@import '~office-ui-fabric-react/dist/sass/Fabric.scss';
$bodyDividerColor: "[theme:bodyDivider, default: #c8c8c8
4.added ms- as prefix whereever we have  @include focus-border(); which changes to this  @include ms-focus-border();
5.gulp build and yes it works.

But I received this warnings during build
![image](https://user-images.githubusercontent.com/11780473/38550152-4d1baa84-3cd3-11e8-89aa-fd11f993877e.png)


Is this the best practice to follow ? 
What are the best practices 
Also what are the best practices to  overwrite the css.

**Comment by harshdamania** [comment]
Any updates

**Comment by harshdamaniahd** [comment]
any updates ?

**Comment by kenotron** [comment]
So this appears to be a question of usage of fabric-core. Sharepoint webparts devs have hit this issue before in areas like this: https://github.com/SharePoint/sp-dev-docs/issues/1110

Microsoft doc page for UIFabric usage inside webparts is here: https://docs.microsoft.com/en-us/sharepoint/dev/spfx/office-ui-fabric-integration#office-ui-fabric-react

So, these warnings seem to be innocuous. But should be fixed it seems... the Fabric 6.x way of doing styling is through [mergeStyles](https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/merge-styles). We have yet to update all the examples to use the mergeStyles way to styling so you're seeing the older way of styling which relies on global css class names.

**Comment by kenotron** [comment]
I'm closing this since there are workarounds - albeit a bit ugly. Please re-open if you have any new information to add to this thread.
