### ISSUE TITLE
DetailsList - Selection onSelectionChanged fires when DetailsList is rendered

### ISSUE THREAD

**Issue by lszomoru** [OfficeDev/office-ui-fabric-react#4493]
### Bug Report

- __Package version(s)__: 5.79.1
- __Browser and OS versions__: 65.0.3325.181 
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

#### Describe the issue:
I have a page in which I am using a DetailsList component using a filter box similar to the DetailsList sample page. What I have noticed is that after the page renders, I execute the first search, and when the results of the search are bound to the DetailsList, the selections' onSelectionChanged fires. When I run my second search the the selections' onSelectionChanged does not fire. Is this expected behavior? 

#### Actual behavior:
In some cases the selections' onSelectionChanged fires while rendering the DetailsList component.

#### Expected behavior:
Consistent behavior of the selections' onSelectionChanged event handler.

**Comment by aditima** [comment]
Hi @lszomoru - can you please share a codepen demonstrating the repro?

**Comment by aditima** [comment]
When the DetailsList receives a new set of items (with the same setKey), we attempt to maintain the previous selection state and if we are able to do that onSelectionChanged event handler does not fire.

It should fire if the selection state cannot be restored or the items are from a different set (identified by a different setKey). If the items you are rendering in the first render are completely unrelated to the second render, consider passing a different setKey with each item set.

**Comment by lszomoru** [comment]
@aditima, thanks for getting back to me on this. Let me do some more debugging based on the information and see what I can find. Based on what you are saying, it looks like during the first search the setKey changes, and that is why the onSelectionChanged event fires. In subsequent searches the setKey stays the same and that is why the onSelectionChanged event does not fire.

**Comment by lszomoru** [comment]
Debugging into the `Selection` code, I see that the during the first search, the event is being raised in `setAllSelected` [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/a5eea239e21a0d41bf31e850e23d112aaf2890da/packages/office-ui-fabric-react/src/utilities/selection/Selection.ts#L273). The event is raised because `this._isAllSelected` is `undefined`. On the second pass, during the second search `this._isAllSelected` is `false` as it was set during the first pass, so the event is not raised. Debugging further...

**Comment by lszomoru** [comment]
I believe I was able to get to the bottom of the behavior that I was seeing. In my repro you can see that I am not setting the `setKey` for the detail list. After taking a closer look at the samples, I have set the `setKey` for the detail list component and now the events are fired as expected. I would suggest that we update the documentation to explicitly call out the importance of setting the `setKey` property. Thanks again for your help! Closing out this issue.
