### ISSUE TITLE
Allow  some CommandBar Contextual Menu Items to not be rendered on the overflow menu

### ISSUE THREAD

**Issue by cmenekse** [OfficeDev/office-ui-fabric-react#4494]
Currently in the experiments when the command bar gets resized all menu items are sent to the overflow menu when they are not displayed. 
like in the following
![commandbarcurrentbehaviour](https://user-images.githubusercontent.com/4938741/38509148-f28d8586-3bd5-11e8-80d5-c77e6802a68c.PNG)
![commandbarresized1](https://user-images.githubusercontent.com/4938741/38509150-f65f0c70-3bd5-11e8-9005-6f58abd7da3a.PNG)

although it is probably a very rare use case, there might be a need to **not put** certain items to the overflow menu. Then it would look like 
![commandbarresized2](https://user-images.githubusercontent.com/4938741/38509199-13d4261e-3bd6-11e8-986f-df11252d13bb.PNG)

For the screenshot purposes I added a property `renderInOverflow` to the `ICommandBarItemProps`  and filtered items to render in OverflowMenu in the render of the command Bar.  Since I am not familiar with the code base I am not sure that is the way to go , also I am not sure that this is a needed feature but just wanted to mention it as a possible suggestion. Thank you

**Comment by aditima** [comment]
Hi @cmenekse - how important is this functionality for you? What is the scenario that's blocked? More specifically, if you are okay showing an item given enough space, why would you want to hide it in the overflow scenario? This doesn't feel very consistent with our overall design, and as such, we are inclined to not fix this...

**Comment by aditima** [comment]
Please reactivate with more scenario details if you really need this...

**Comment by cmenekse** [comment]
Hi @aditima I do agree with you, the only case I can think this might be useful is like the one's in the screenshots - a dummy menu item "|" that acts as a vertical bar - . Is there a recommended way to implement the similar functionality without making "|" as a menu item? Besides that I too cannot think any other scenario this can be useful.
