### ISSUE TITLE
Tooltip host is ignoring maxWdith setting

### ISSUE THREAD

**Issue by bpovlich** [OfficeDev/office-ui-fabric-react#4497]
### Bug Report

- __Package version(s)__: 5.79.1
- __Browser and OS versions__: Windows 10, Chrome All Versions

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable)

#### Describe the issue:

TooltipHost does not appear to use the "maxWidth" property, despite the documentation.

#### Actual behavior:

Text within the tooltip has a width of 346px

#### Expected behavior:

Text within the tooltip has a width of <= what was set as the maxWidth

### If applicable, please provide a codepen repro:

https://codepen.io/anon/pen/MVZdVj

**Comment by lynamemi** [comment]
maxWidth should be set in prop tooltipProps instead of the main ToolTip host's props. I agree that the website documentation is not clear about that, we should fix that.

**Comment by aditima** [comment]
Thanks @lynamemi for looking at this. Could you please fix the documentation?

@bpovlich - could you please confirm if this works for you?

**Comment by bpovlich** [comment]
That works for me, thanks

**Comment by Jahnp** [comment]
Per [codeowners](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/.github/CODEOWNERS#L106), it'd be great if @micahgodbolt could take a look at this as well--do you have any thoughts on how we could document this better?

**Comment by lynamemi** [comment]
On the example page, we're only importing TooltipProps to the properties table. If we import TooltipHostProps, also, it will be much clearer.

**Comment by micahgodbolt** [comment]
Once we move Fabric to React 16+ I'd love to do a refactor here.

1. There's a TON of overlap between tooltip and host. They have a lot of props in common, which are just passed from parent to child (but not all of them obviously). 
2. Once we have React.fragment support, we can remove the wrapping div provided by the host

So yeah, for now, some better documentation explaining whats available in the host and what is only available on the tooltipProps.

In the future maybe we make the host props extend the tooltip, or we do a MUCH better job of keeping host seperate from tooltip.

**Comment by lynamemi** [comment]
Sounds like a solid plan, @micahgodbolt ! I submitted the docs PR for the quick fix.
