### ISSUE TITLE
Will there be a built-in filter in DetailList?

### ISSUE THREAD

**Issue by thinkman99** [OfficeDev/office-ui-fabric-react#4502]
Will there be a built-in filter in DetailList?
Like this [screenshot](http://prntscr.com/j373dq)

**Comment by Laapi** [comment]
Yes. This is a very importable feature!

**Comment by Jahnp** [comment]
Just to be clear, are you talking about supporting filtering functionality (which DetailsList does today), or adding explicit UI affordances for filtering (like comboboxes/checkboxes, etc)? I don't quite understand the desired behavior from that screenshot.

In the second case, this is something that could be handled by an HOC/implementation of DetailsList/DetailsHeader. Have you seen the filtering examples on the [DetailsList page](https://developer.microsoft.com/en-us/fabric#/components/detailslist)? Those should help inform how you can implement your own filter UI. Right now, we don't have any plans for a formal implementation of this. See #4459 --we want to be very careful about overloading DetailsList's core functionality.

@aditima, @dzearing would love your thoughts on this as well. I'm inclined to close for now but want to make sure I'm not missing something. @michaelangotti for triaging FYI.

**Comment by Laapi** [comment]
Thanks for the answer. Yes, you correctly understood, I would like to be able to filter like this: number or string (simple input) boolean data (checkbox), enumeration data (drop-down menu),
date (datepicker), etc...

**Comment by aditima** [comment]
@micahgodbolt - Micah, I think this is a fair ask, and one to add to our backlog.

**Comment by micahgodbolt** [comment]
It's a feature worth considering for sure. Would require a bit of design first to determine the correct approach. I'll add it regardless to track.

**Comment by thinkman99** [comment]
Hello again. What's news?

**Comment by nealYangVic** [comment]
Can you guys provide an example how we can implement it with current version

**Comment by nealYangVic** [comment]
ok, I think we can use contextmenu for this problem too with official example Variable row height
just use onrender, I believe it should be workable....
![image](https://user-images.githubusercontent.com/38148709/54721858-59d9e680-4b20-11e9-95d4-9143a1b2f450.png)
