### ISSUE TITLE
DetailList inside ScrollablePane don`t  render rows

### ISSUE THREAD

**Issue by thinkman99** [OfficeDev/office-ui-fabric-react#4503]
In example placed at https://developer.microsoft.com/en-us/fabric#/components/scrollablepane DetailList inside ScrollablePane don`t  render all rows. Same trouble in my project...

**Comment by obiwan007** [comment]
More detailed issue here: #4204

**Comment by michaelangotti** [comment]
Closing as this is a dup of #4204
