### ISSUE TITLE
className Property for ICalendarProps

### ISSUE THREAD

**Issue by lafe** [OfficeDev/office-ui-fabric-react#4514]
Currently, the Calendar control does not support custom styling due to the missing `className` property on the `ICalendarProps` interface. It would be great, if this can be added, because currently a global style for the "Button" element breaks the layout of the month selection in the Calendar Control. As we do not have control over that global style, the easiest fix is to apply the change directly to the Calendar.

**Comment by lafe** [comment]
As you can see, I submitted a PR, but unfortunately the automatic build task did not run successfully. As I do not have further information than the Travis log, I cannot analyze the issue that caused the build process to fail further. From what I can gather, it seems to be a problem with the build infrastructure itself and not with the changes I made.

**Comment by KevinTCoughlin** [comment]
@lafe it looks to be failing during TSLint via the Travis CI log:

```shell
/home/travis/build/OfficeDev/office-ui-fabric-react/packages/office-ui-fabric-react/src/components/Calendar/Calendar.test.tsx:176:21
ERROR: 176:21  quotemark  " should be '
ERROR: 258:41  quotemark  " should be '
ERROR: 259:41  quotemark  " should be '
[office-ui-fabric-react 16:37:28] Error: tslint (20.303s): Error: Command failed: node /home/travis/build/OfficeDev/office-ui-fabric-react/scripts/node_modules/tslint/lib/tslint-cli --project /home/travis/build/OfficeDev/office-ui-fabric-react/packages/office-ui-fabric-react/tsconfig.json -t stylish -r /home/travis/build/OfficeDev/office-ui-fabric-react/common/temp/node_modules/tslint-microsoft-contrib
```

So if you change the quotemarks from double to single it should pass. Hope that helps!

**Comment by lorejoh12** [comment]
David is this finished now? Would love to close this, thanks for the fix you guys!

**Comment by JasonGore** [comment]
`className` was added to `ICalendarProps` in #4680, so I will close this issue.
