### ISSUE TITLE
Duplicated @uifabric imports 

### ISSUE THREAD

**Issue by Markionium** [OfficeDev/office-ui-fabric-react#4520]
### Bug Report

- __Package version(s)__: 
- office-ui-fabric-react@5.77.0 
-  uifabric/merge-styles@5.14.0
-  uifabric/styling@>=5.11.0
-  uifabric/utilities@>=5.19.1

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low) Normal?

Products/sites affected: (if applicable) LPC

#### Describe the issue:

When bundling our JS we saw a sudden increase in bundle size. I tracked down the issue to the following. 

In our product we import oufr components as follows

```ts
import { ActionButton } from "office-ui-fabric-react/lib/Button";
```

and stuff from uifabric.
```ts
import { mergeStyleSets } from "@uifabric/merge-styles";
```

Since the webpack 4 integration #4320 our webpack 3 picks up the `@uifabric` files from `@uifabric/lib-es2015` however oufr imports these same files from `@uifabric/lib/` as it references them directly. 

This means we end up with files from both `lib` and `lib-es2015`.
![image](https://user-images.githubusercontent.com/2134901/38626375-b768b588-3dac-11e8-83e3-814de9844dfb.png)

I have resolved the issue temporarily by using the webpack alias to find the correct files but i'm looking for a better approach or perhaps someone who solved the same problem differently :)

```js
var webpackConfig = {
    resolve: {
        modules: [path.resolve(__dirname, "node_modules"), "node_modules"],
        extensions: [".web.js", ".js", ".less", ".css", ".scss"],
        alias: {
            "@uifabric/styling/lib": "@uifabric/styling/lib-es2015",
            "@uifabric/utilities/lib": "@uifabric/utilities/lib-es2015",
            "@uifabric/merge-styles/lib": "@uifabric/merge-styles/lib-es2015"
        }
    },
};
```
This gives me the following bundle output 
![image](https://user-images.githubusercontent.com/2134901/38626895-e6250858-3dad-11e8-9c8d-cb58bb179840.png)

Any feedback or tips welcome :)

**Comment by dzearing** [comment]
Propose we remove the module entries in 5.0 and stick with lib, until 6.0.

**Comment by dzearing** [comment]
I have removed them. I am closing this and will track the 6.0 update separately.
