### ISSUE TITLE
@Question: Should I upgrade spfx project as its using older version of 'office-ui-fabric-react'?

### ISSUE THREAD

**Issue by gbminnock** [OfficeDev/office-ui-fabric-react#4521]
@Question
Hi, I am using office-ui-fabric react in my spfx webpart. I used yeoman with the @microsoft/sharepoint generator to create the project. 

The version of office-ui-fabric seems to be 5.21.0 but the latest version is 5.80.0. I've noted some issue whereby there are some missing functionalities from components and some mismatches from the documentation. 

Is it recommended to upgrade office-ui-fabric-react independently of the yeoman generator? 

Thanks,
Gary

**Comment by michaelangotti** [comment]
@manishgarg1 Can you help answer this one?

**Comment by manishgarg1** [comment]
Hi @gbminnock, are you following the guidance in this document? https://docs.microsoft.com/en-us/sharepoint/dev/spfx/office-ui-fabric-integration. If yes, then you should be able to upgrade office-ui-fabric-react independent of SPFx. Please do let us know if you face issues.

**Comment by aditima** [comment]
@gbminnock - hopefully this solved your issue. Closing this now, please feel free to reopen if you have more questions.
