### ISSUE TITLE
ColorPicker does not update upon text field changes when alphaSliderHidden=true

### ISSUE THREAD

**Issue by wutonghao** [OfficeDev/office-ui-fabric-react#4525]
### Bug Report

- __Package version(s)__: 5.29.4

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? 
No

Requested priority: Blocking

Products/sites affected: Excel

#### Describe the issue:

Color is not updated when we manually change red/green/blue value when alphaSliderHidden=true.
By looking into ColorPicker.tsx and debugging, I noticed that although color picker allows the option of hiding alpha control, it does not take care of this option at all when the value of text field (red/green/blue/alpha) changes. When color picker detects value change of any text field(red/green/blue/alpha), it tries to construct the new color (in ColorPicker.tsx:170 onRGBAChanged()) while using the alpha field that is actually undefined in this case, and this leads to the update failure. 

#### Actual behavior:

color is not updated when we manually change red/green/blue value when alphaSliderHidden=true

#### Expected behavior:

color can be updated, just like what we have when alphaSliderHidden is not set

Simple repro:
 1. add color picker with alphaSliderHidden=true:
        <ColorPicker 
                    color="#ffffff"
                    alphaSliderHidden={true}
                />
2. manually change the value of red/green/blue text field

Potential fix:
In ColorPicker.tsx:170
  private _onRGBAChanged() {
    this._updateColor(getColorFromRGBA({
      r: Number(this.rText.value),
      g: Number(this.gText.value),
      b: Number(this.bText.value),
      a: Number(this.aText.value)
    }));
  }
We can add an additional check here "if(!this.props.alphaSliderHidden)"; If the flag is true, we may pass a default value (ex. 100) to "a".

**Comment by Jahnp** [comment]
Thanks for reporting this @wutonghao . Your proposed fix looks reasonable to me, but would love @phkuo's thoughts. @wutonghao , would you be willing to submit a PR?

**Comment by wutonghao** [comment]
@Jahnp I can submit a PR if the proper fix is as simple as what I proposed (since I'm not very familiar with the color picker). If @phkuo also agrees with my fix, I can go ahead and submit a PR. Thx!
