### ISSUE TITLE
Split Buttons in Contextual Menu: Enforcing a sub menu option that does what the primary button does

### ISSUE THREAD

**Issue by chang47** [OfficeDev/office-ui-fabric-react#4532]
### Bug Report

- __Package version(s)__: 5.80.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

#### Describe the issue:

Now that we're introducing touch for better split buttons inside contextual buttons (overflow) from this PR: https://github.com/OfficeDev/office-ui-fabric-react/pull/4353. We can no longer trigger the primary button in exchange for being able to more easily expand the sub menu.

While this is the correct thing to do in a accessibility standpoint, we're missing the next part where all primary actions in a split button should be available in the sub-menu.

There should be some work that needs to be done that should dynamically add the primary action as a button in the sub-menu that will be created.

**Comment by michaelangotti** [comment]
@betrue-final-final Is this something we want to do?
