### ISSUE TITLE
Components need to support mouse hover in high contrast

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#4533]
These controls currently do not respond to mouse hover in high contrast themes:

1. Button - Needs to change the border to system color "highlight"
2. Breadcrumb - See above. I believe this will inherit from Button
3. Checkbox - See Button. Also technically it would be better if the background and checkmark reversed colors on selection.
4. Coachmark has all kinds of problems in HC
5. ChoiceGroup - See Button
6. Link - underline on hover would be great
7. Pivot - Should show underline on hover
8. Rating - Stars should change to system color "highlight" on hover
9. Searchbox - See button
10. Spin button - Remove horrific dashed line. How did that get through?
![image](https://user-images.githubusercontent.com/20363037/38704155-4c050914-3e5a-11e8-863e-18bfb21b00cd.png)
11. Toggle - See Button

**Comment by lynamemi** [comment]
ChoiceGroup: https://github.com/OfficeDev/office-ui-fabric-react/pull/4572

**Comment by lynamemi** [comment]
I'm going to split checkmark and coachmark into separate issues to be done in separate PRs, as those are a bit more complex. Therefore, when #4728 is merged, we can close this issue.
