### ISSUE TITLE
DropDown: Uncaught (in promise) TypeError: props.options.forEach is not a function

### ISSUE THREAD

**Issue by cythomli** [OfficeDev/office-ui-fabric-react#4535]
I'm receiving the above error even after updating react and office-ui-fabric-react to latest version. Please let me know how to fix this.

**Comment by michaelangotti** [comment]
@lisapalathingal We need a little more information on this one. What Browser and OS version are you using? Can you also provide a repro or code sample?

**Comment by ecoukraine** [comment]
Hi guys,

I see it's the same issue I have #3788 - it's marked as closed but I still have no luck with it.
![image](https://user-images.githubusercontent.com/11150186/40708882-402d9a0c-63fd-11e8-89eb-279c8bcbcd52.png)

Would you be kind to help with this one

Thank you

**Comment by NidhiSinghala** [comment]
I have the same issue with the dropdown component.  I am using version Office-ui-fabric-react version 6.13.2

**Comment by licythom** [comment]
I had no luck with using dropdown. I used ComboBox instead and it worked fine!

**Comment by micahgodbolt** [comment]
do you have an example of the code you are using to render the Dropdown? Can you possible put it in a CodePen? https://codepen.io/FabricReact/pen/NvBvWx
