### ISSUE TITLE
Selection: For single selection mode, clearSelection doesn't work if items are updated for same selection instance

### ISSUE THREAD

**Issue by yaananth** [OfficeDev/office-ui-fabric-react#454]
For single page navigation,
using our own [selection ](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/src/utilities/selection/Selection.ts)  instance for [DetailsList](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/src/components/DetailsList/DetailsList.tsx)...
as user navigates, we change the items, so `setItems` is being called on `Selection`.
Since we set the mode to single selection, `_onItemSurfaceClick` calls `_clearAndSelectIndex`.
Which would then call `selection.setAllSelected(false)`
But the problem is `_unselectableCount `is based on previous items and current items.
so,
`var selectableCount = this._items ? (this._items.length - this._unselectableCount) : 0`
that would be negative in all cases ( say initial items are 10 and all can be selected, so `_unselectableCount` count would be 10, when we update items to say 4, all can still be selected, note that we never set `_unselectableCount` to zero, it is just being incremented, so it would be 14...)

With that, though we mention single selection mode, it would allow us to select multiple items, this is really confusing since the first time it works as expected, but when items are updated, it would let user select multiple items.

I guess the fix is to set `_unselectableCount` to zero on setItems?

**Comment by dzearing** [comment]
@yaananth are you on an older version? In the current bits we did fix this:

selection.ts:
```ts
public setItems(items: IObjectWithKey[], shouldClear = true) {
    let newKeyToIndexMap: { [key: string]: number } = {};
    let newUnselectableIndices: { [key: string]: boolean } = {};
    let hasSelectionChanged = false;

    this.setChangeEvents(false);

    // Reset the unselectable count.
    this._unselectableCount = 0;
```

**Comment by dzearing** [comment]
If there is a current bug, can you find it in the code and maybe make a PR?

We have selection.test.ts as well and can add a test around the area if it's missing.

**Comment by yaananth** [comment]
ah, yes we are using older version, then it's probably fixed in new versions, we are from VSTS (Visual studio team services), hopefully soon we will update react in our web platform code. Thanks for the info!
