### ISSUE TITLE
CommandBar Items with href passes undefined item in onClick handler

### ISSUE THREAD

**Issue by trevonmckay** [OfficeDev/office-ui-fabric-react#4556]
### Bug Report

- __Package version(s)__: 5.80.0
- __Browser and OS versions__: Google Chrome 65.0.3325.181 on Windows 10 1803

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: High 

Products/sites affected: (if applicable)

#### Describe the issue:

The onClick handler for IContextualMenuItem passes an instance of the item that was clicked when the href property is not used. When the href property is used the item is undefined in the handler.

#### Actual behavior:

The onClick handler for IContextualMenuItem receives an undefined item

#### Expected behavior:

The onClick handler for IContextualMenuItem receives the item that invoked the handler

**Comment by KevinTCoughlin** [comment]
Thanks for the report @trevonmckay. I can repro this and am close to a fix. Will raise a PR shortly. Seems reasonable to want to be able to trigger some action via callback even if the `href` property is set.

**Comment by trevonmckay** [comment]
Thanks @KevinTCoughlin for your speedy resolution on this.
