### ISSUE TITLE
Hover card should set focus to it self after card is opened.

### ISSUE THREAD

**Issue by MirandaGe** [OfficeDev/office-ui-fabric-react#4582]
### Bug Report

- __Package version(s)__: recent
- __Browser and OS versions__: all

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? If I have time...

Requested priority: Normal

Products/sites affected: SharePoint onprem People web part

#### Expected behavior:

After hover card is opened by hover/click, I expect the focus should goes into the card

**Comment by KevinTCoughlin** [comment]
@MirandaGe I think I have a fix that will enable the behavior you're looking for.

**Comment by atneik** [comment]
@MirandaGe are we sure people card which is probably used in people web part is using this Fabric hover card? Last time I check they were yet to transition to it.
