### ISSUE TITLE
actionButton onClick fires for every row in DetailsList at initialisation

### ISSUE THREAD

**Issue by petercutting** [OfficeDev/office-ui-fabric-react#4583]
I have put an actionButton (or any Button) in each row of a DetailsList. The Buttons appear correctly, one on each row.

Each button's onClick event seems to be called spuriously when the DetailsList is initialised. I get one onClick event for each row in the list.
 
```
_renderItemColumn = (item, index, column) => {
...
      case 'EditBookingButton':
        return <ActionButton onClick={this.props.editBooking(item.BookingId)}>EDIT</ActionButton>

```

**Comment by michaelangotti** [comment]
It looks like this issue has been answered/resolved. Closing this issue.

**Comment by jordandrako** [comment]
@a-tarasyuk has the right fix!
