### ISSUE TITLE
Virtual scroll with groups

### ISSUE THREAD

**Issue by cordasfilip** [OfficeDev/office-ui-fabric-react#4591]
### Bug Report

- __Package version(s)__:  9.6.0
- __Browser and OS versions__: Edge Win 10
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Low 

Products/sites affected: https://developer.microsoft.com/en-us/fabric#/components/detailslist

#### Describe the issue:

I have been looking at DetailsList demo web site and the demo  Rendering custom group headers doesn't seam to work correctly.  Scrolling all the rows down first time seams to work as it should(But the I haven't spent time looking at different group sizes and numbers so there might be some problems there as well). Bu one you start scrolling back the groups start doing wiled jumps and the index number of items change in an unexpected manner. The scroll up problems some times happen on Advanced DetailsList of 5000 items, variable row heights as well. The jumps also happen when you start dragging the scroll up and down with the mouse.

#### Actual behavior:

The virtualization is not scrolling as a normal scroll should. 
#### Expected behavior:

There shouldn't be a difference between rendering all the elements in the scroll and doing virtualization. Should always be on the right row no jumps

I am pretty sure this is reproducible every ware use the code from https://developer.microsoft.com/en-us/fabric#/components/detailslist  Rendering custom group headers

**Comment by michaelangotti** [comment]
@cordasfilip This issue is already on our radar and we are looking into fixing performance issues within the DetailsList.
