### ISSUE TITLE
DatePicker control state should be resetable

### ISSUE THREAD

**Issue by AlexVSTS** [OfficeDev/office-ui-fabric-react#4599]
### Bug Report
- __Package version(s)__: 5.79.1(and master also)
#### Priorities and help requested (not applicable if asking question):
Are you willing to submit a PR to fix? (Yes)
Requested priority: (Normal) 
#### Actual behavior:

- Create empty DatePicker control
- User enters an invalid value (say "aaa") and then focus'es away
- DatePicker displays an error message that the value is invalid & updates its state specifying that the error message should display. 
- Now user presses a separate "Reset fields" button that is suppose to reset all fields. The press causes the Form to remove the existing DatePicker and create a new empty one. However the error remains on the DatePicker. Even if re-rendering the component React thinks that it's the same component and preserves its state. 
The work-around is to delete the DatePicker, render the form, then add an empty DatePicker which will now have a blank state. Of course this will cause flickering so It's not an actual work-around.

#### Expected behavior:
There should be a way to reset the DatePicker control error status.

@lorejoh12 @sathi23

**Comment by lorejoh12** [comment]
Did you try changing the Key of the DatePicker while rerendering it? React should only keep the state of the component if the key stayed the same, so that might be a potential workaround also.

That being said I have nothing against adding a property for setting the state of the react component during a render to have the error state reset until the next validate step, if you need it.

**Comment by AlexVSTS** [comment]
Yes, changing the key was considered as a solution, but tracking / managing that would be somewhat difficult and hack-ish so that was decided as not an acceptable solution though it will work indeed.

**Comment by dzearing** [comment]
@AlexVSTS could you use the DatePicker as a controlled component?

That is, pass in the date through `value`. And in `onSelectDate`, push it back to a container state. On reset, clear the state.

Example:

https://codepen.io/dzearing/pen/vjEzMd

**Comment by dzearing** [comment]
I think it's also possible for us to add a `reset` method to `IDatePicker` to provide an imperative method to use.

**Comment by lorejoh12** [comment]
We agree with the approach to add an imperative reset method, but don't have that on our radar at the moment. Would love to do a code review for it and add it if you'd like to submit a PR for that though!
