### ISSUE TITLE
Lists rendered inside a ScrollablePane fail to render pages as they are scrolled into view

### ISSUE THREAD

**Issue by elliottsj** [OfficeDev/office-ui-fabric-react#4601]
### Bug Report

- __Package version(s)__: 5.82.4
- __Browser and OS versions__: macOS 10.13.4, Chrome 65

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: onedrive.live.com

#### Describe the issue:

A bug was introduced in #4055 which prevents a virtualized List rendered inside a ScrollablePane from rendering pages as they're scrolled into view.

#### Actual behavior:

Render a `List` or `DetailsList` inside a `ScrollablePane`, e.g.
```jsx
<ScrollablePane>
  <DetailsList
    items={ items }
    columns={ columns }
    setKey='set'
    selection={ this._selection }
  />
</ScrollablePane>
```

Observe that, when there is a large number of `items`, pages below the fold are not rendered as they are scrolled into view. e.g. run `npm start` and visit http://localhost:4322/#/examples/scrollablepane:

![kapture 2018-04-18 at 13 34 50](https://user-images.githubusercontent.com/2177366/38956966-0b4a4886-430e-11e8-8e31-5060fe7ab943.gif)

#### Expected behavior:

Pages in the list should be rendered as they are scrolled into view.

**Comment by jordandrako** [comment]
Duplicated of #4204

**Comment by LarsLiden** [comment]
I'm using 7.25.0 and still seeing this issue  (@elliottsj / @jordandrako )
