### ISSUE TITLE
office Fabric React - Grid layout

### ISSUE THREAD

**Issue by cskr11** [OfficeDev/office-ui-fabric-react#4605]
Hi, I have been struggling with getting grid layout to work in office fabric react.
The div(s) are not rendered adjacent to one another.
I am importing fabric css (I don't know how other way to refer) in my fabriccomponent.js like 
import 'office-ui-fabric-react/dist/css/fabric.css';

The component is defined like this:

```jsx
import React, { Component } from 'react';
import 'office-ui-fabric-react/dist/css/fabric.css';
import './fabriccomponent.css';

const fabriccomponent = () => {
    return(
        <div className="ms-Grid">
            <div className="ms-Grid-row">
                <div className="ms-Grid-col ms-sm6 ms-md4 ms-lg2">FIRST COLUMN</div>
                <div className="ms-Grid-col ms-sm6 ms-md8 ms-lg10">SECOND COLUMN</div>
            </div>
        </div>
       
    );
}
```
Could someone please help in this regard?

Also, Can we use Office Fabric UI with pure react library (not using typescript  at all?

**Comment by dzearing** [comment]
While we do have plans to add a dedicated `Grid` react component (tracked in another issue), it should be possible to use the fabric-core css in your React projects.

The fabric core repo is here: https://github.com/OfficeDev/office-ui-fabric-core

So if you have fabric-core specific questions, that's a great place.

I took a look at your example and you're missing a `dir="ltr"` attribute, which I believe the css depends on. If you add that, you should get the result you expect.

I made a codepen to illustrate here.

https://codepen.io/dzearing/pen/ZMXxoK?editors=0010
