### ISSUE TITLE
Feature Request: Provide loverly extended year selection for the Calendar component

### ISSUE THREAD

**Issue by gitfish** [OfficeDev/office-ui-fabric-react#4610]
Hi,

It'd be loverly (as a start) to replicate the extended year selection available in the non-React version of fabric (see attached images) to the React version of fabric.

![calendar-year-selection](https://user-images.githubusercontent.com/610312/38966975-3b7609ae-43c8-11e8-98f6-1c2e25fd3fbc.png)
![calendar-year-selection-open](https://user-images.githubusercontent.com/610312/38966976-3bb1019e-43c8-11e8-82e9-bbbde58f9ac7.png)

If I get time I'll hack something into a fork myself (ugh).

Just wanted to say thanks for open saucing fabric and for the work you guys are doing.

Cheers.

**Comment by Jahnp** [comment]
Thanks for suggesting this, @gitfish . This seems like essential functionality--it's a huge pain to navigate large year ranges otherwise. @lorejoh12 , is this functionality on your team's radar? Feels like a super valuable scenario for Calendar.

**Comment by lorejoh12** [comment]
We evaluated this feature and while a great use case, this is currently low on our backlog. We'd love to do a code review for it if someone else has the bandwidth to add the feature though!
