### ISSUE TITLE
TooltipHost does not accept the props it says it does

### ISSUE THREAD

**Issue by Pajn** [OfficeDev/office-ui-fabric-react#4612]
### Bug Report

- __Package version(s)__: latest (can be seen i master as well)
- __Browser and OS versions__: N/A

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Only if that would make time to a fix in a release quick

Requested priority: Normal

Products/sites affected: ?

#### Describe the issue:

TooltipHost have types specifying that it accept all props from  `React.HTMLAttributes<HTMLDivElement | TooltipHost>` when in reality it ignore basically all of them. For example `style` is accepted by the types but is not rendered

#### Actual behavior:

Accepted props are not rendered

#### Expected behavior:

Accepted props are rendered like this: https://github.com/OfficeDev/office-ui-fabric-react/compare/master...Pajn:patch-1

### If applicable, please provide a codepen repro:

N/A

**Comment by Pajn** [comment]
This seems to be quite a common thing throughout the library, now I had the same problem with PivotItem.

If this is a bug that affects all or near all components of the library I would state that this is prio High instead.

**Comment by micahgodbolt** [comment]
calloutContent isn't passing getNativeProps(this.props, divProperties) down to the enclosed popup (or wrapping div, if that makes more sense).

Popup is already set up to print nativeProps just fine.
