### ISSUE TITLE
Please provide non typescript examples for office-ui-fabric-react 

### ISSUE THREAD

**Issue by nigelskeels** [OfficeDev/office-ui-fabric-react#4616]
Thanks for your excellent Fabric UI but can you please provide examples that don't use Typescript.
It's an unnecessary hurdle to using MS Fabric with react.

**Comment by nigelskeels** [comment]
Hi Joshua,

Its the people picker that I am having particular trouble with...

https://developer.microsoft.com/en-us/fabric#/components/peoplepicker#Implementation

Thank you,

**Comment by jordandrako** [comment]
I've been looking into switch our documentation code examples to CodePen embeds which would enable a sort of interactive playground. We can possibly look into doing examples in typescript and vanilla js. @dzearing thoughts?

**Comment by michaelangotti** [comment]
Looks like this is resolved as an issue. We will close for now.
