### ISSUE TITLE
DatePicker: pressing space/Enter on Previous/Next month/year arrow buttons goes 2 months at a time

### ISSUE THREAD

**Issue by edsirko** [OfficeDev/office-ui-fabric-react#4620]
### Bug Report

- __Package version(s)__: 5.79.1 and 5.46.0, but not 5.39.1
- __Browser and OS versions__: Chrome, probably all browsers

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal) 

Products/sites affected: (VSTS)

#### Describe the issue:

When keyboard navigating through the DatePicker, if you focus the up/down arrow to navigate to previous or next month (or year) and then hit spacebar or enter, you will actually navigate 2 months/years forward or back.  This seems to have regressed between 5.39.1 and 5.46.0.

#### Actual behavior:

You will actually navigate 2 months/years forward or back.

#### Expected behavior:

You should navigate 1 month/year forward or back.

**Comment by KevinTCoughlin** [comment]
:wave:,

I ran `git bisect` and it looks like this commit may have caused the regression https://github.com/OfficeDev/office-ui-fabric-react/commit/fd2206f8041ba6aca3b61a67a8552652e67d4954

The button click handler seems to be firing twice with keyboard input hence the 2x moth or year change as reported above. We'll still want buttons for accessibility reasons, but need to circumvent that 2x behavior.

Will look into a fix unless @jordandrako wants to take it.

**Comment by jordandrako** [comment]
@KevinTCoughlin Thanks for finding the issue. Feel free to take it.
