### ISSUE TITLE
Documentation: Layer code sample is not showing correct code sample

### ISSUE THREAD

**Issue by sumboxcar182** [OfficeDev/office-ui-fabric-react#4621]
Hello,

I was looking through the documentation and found that the code sample for the section "Using Customizer to control the default layer behavior" under the Layer component does not have the correct code. It is currently showing the previous sections's code. 

The url where this is occurring is  [here](https://developer.microsoft.com/en-us/fabric#/components/layer) and if there's any other info you need please let me know!

**Comment by dzearing** [comment]
Thanks for letting us know! This has been resolved in code and will be deployed on the next site update.
