### ISSUE TITLE
DatePicker steals focus on dismiss

### ISSUE THREAD

**Issue by abettadapur** [OfficeDev/office-ui-fabric-react#4623]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__:  all

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low)  Normal

#### Describe the issue:
1. Have a form with multiple inputs
2. Open the datepicker calendar
3. Change your mind and move to edit another input on the form. Click that input
4. DatePicker calendar closes, but the DatePicker input is now focused, not the input I clicked

**Comment by abettadapur** [comment]
@lorejoh12 This seems like behavior that might have looked like a good idea, but is probably undesired

**Comment by abettadapur** [comment]
Introduced by Issue #1266

**Comment by lorejoh12** [comment]
This is definitely a bug, I'm working on fixing this hopefully this week or next week.
