### ISSUE TITLE
IContextualMenuItem isDisabled state is not enforced in CommandBar

### ISSUE THREAD

**Issue by chripi** [OfficeDev/office-ui-fabric-react#463]
We should be able to enforce it as it is a property that we expose in that object.

**Comment by mihaelams1** [comment]
@chripi - by "not enforced" do you mean that the IContextualMenuItem is being styled as enabled regardless of the value of the isDisabled prop? Because this is what I noticed today, even down to the pointer cursor. I would label this as a bug, if you don't mind.

**Comment by chripi** [comment]
Yes, a bug is fine too :)

**Comment by dzearing** [comment]
Should be `disabled` flag.

**Comment by mihaelams1** [comment]
Just found the place where the IContextualMenuItems are rendered in the CommandBar, and neither `disabled` nor `isDisabled` are being used. See `_renderItemInCommandBar()` from CommandBar.tsx.

**Comment by joschect** [comment]
Disabled does translate correctly onto the command bar item, however there is no css styling to indicate that the button is disabled. getNativeProps will pick up disabled as it is a native property to button.

**Comment by dzearing** [comment]
published 0.71.1

**Comment by mihaelams1** [comment]
Thank you for addressing it so fast! :)
