### ISSUE TITLE
Module not found: Can't resolve '@uifabric/utilities/lib/inputMask'

### ISSUE THREAD

**Issue by KyleFoleyImajion** [OfficeDev/office-ui-fabric-react#4632]
### Bug Report

- __Package version(s)__: 5.85.0
- __Browser and OS versions__: Firefox v. 59.0.2, Windows 10 v. 1709

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Blocking

#### Describe the issue:
The file @uifabric/utilities/lib/inputMask is not in node_modules. Will not let my app start. 
```Can't resolve '@uifabric/utilities/lib/inputMask' in 'x:\xxxx\xxxx\node_modules\office-ui-fabric-react\lib\components\TextField\MaskedTextField'```

#### Actual behavior:
Crashed webapp

#### Expected behavior:
Webapp does not crash, file is present in `uifabric/utilities/lib`

**Comment by jonathanhotono** [comment]
Got the same issue here with spfx and same version. I had to downgrade the package into specific version before 5.85.0 to get this working..

**Comment by wygoodin** [comment]
Same issue here. Would it be an option for office fabric to depend on specific versions to avoid this happening again?

**Comment by dzearing** [comment]
Investigating what happened. Will resolve ASAP.

**Comment by lambertwang** [comment]
A new build was just queued. Once that completes, a new version of @uifabric/utilities should be available which should have inputMask.ts

**Comment by lambertwang** [comment]
We're having some issues publishing the new version of `@uifabric/utilities`, so the best option right now is to use `office-ui-fabric-react@5.85.0`.

**Comment by lambertwang** [comment]
The package updates suceeded. Please use `office-ui-fabric-react@5.86.0` and ensure that your version of `@uifabric/utilities` is at least `5.26.0`.
