### ISSUE TITLE
[Drag Drop] how to drag from one list and drop in another

### ISSUE THREAD

**Issue by panigrah** [OfficeDev/office-ui-fabric-react#4644]
Drag drop documentation is not very detail - so I am trying to figure out how it works using the example. I need help. 

In the example published - the dragged item is being stored as a global / local variable. This works if the drag and drop is on the same component.

However if the drag and drop have to work across different components - what is the best way that the onDrop event can get the draggedItem?

**Comment by panigrah** [comment]
Approach 1
1. push selections to a store (redux?) on the 
`onDragStart() { dispatch({type: 'DRAG_START', payload: selection}) }`
2. `onDrop() { get the selections from redux store }` and process

Approach 2 - only works if there is one element being dragged. in the DetailsList set the onRenderRow
`onRenderRow={ (props) => <DetailsRow id={someuniqueid from props.item} ...props /> }`

then in the `onDrop(item, event)` you can get the id from `event.dataTransfer.getData('id'))`

**Comment by panigrah** [comment]
@aditima I used redux to handle multiple element drag and drop. The OnDragStart pushes the list of selected items into redux and the OnDrop reads from redux.

**Comment by aditima** [comment]
@panigrah - your Approach 1 above sounds reasonable to me.
