### ISSUE TITLE
TextField: IE11 placeholder is not shown when the TextField is focused

### ISSUE THREAD

**Issue by abettadapur** [OfficeDev/office-ui-fabric-react#4652]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: IE11

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

#### Describe the issue:
IE11 does not show the TextField placeholder when then TextField is focused. All other browsers continue to show the placeholder, even when focused

From the Fabric site:
Firefox:
![image](https://user-images.githubusercontent.com/2415669/39142064-6b637bce-46de-11e8-9cda-26ab31a843ec.png)

IE11: 
![image](https://user-images.githubusercontent.com/2415669/39142073-71be5534-46de-11e8-88b5-c86077a67580.png)

Behavior can be see here: https://developer.microsoft.com/en-us/fabric#/components/textfield

**Comment by Jahnp** [comment]
This is default browser behavior for `placeholder` in IE11. I'm pretty confident we don't want to do weird things to TextField to force UX consistency in this case. I'm going to go ahead and close unless you feel strongly about this @abettadapur.

**Comment by abettadapur** [comment]
@Jahnp That's fine if its the default behavior (its bad behavior, but ok :) )

Thanks for investigating
