### ISSUE TITLE
ChoiceGroup mutates its props.

### ISSUE THREAD

**Issue by Javier-Rotelli** [OfficeDev/office-ui-fabric-react#4653]
### Bug Report

- __Package version(s)__: 5.56.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: High

#### Describe the issue:

when I pass a ChoiceGroup an array of props as its options it mutates the array, which is something that shouldn't be happening. 
https://reactjs.org/docs/components-and-props.html#props-are-read-only
>React is pretty flexible but it has a single strict rule:
>**All React components must act like pure functions with respect to their props.**

this is a big nope in react components, because it breaks all kinds of code that operate on the assumption that the props are not going to be modified. 

#### Actual behavior:

the array I send as a prop of ChoiceGroup is mutated.

#### Expected behavior:

Props should be read only for the components

### If applicable, please provide a codepen repro:

https://codepen.io/javier-rotelli/pen/rvxvKQ?editors=0010

**Comment by Jahnp** [comment]
Thanks for reporting @Javier-Rotelli. It looks like you're willing to submit a PR to fix--did you have a solution in mind you'd want to share? @srideshpande as ChoiceGroup codeowner and @lynamemi as FYI having worked on ChoiceGroup recently.

**Comment by Jahnp** [comment]
Also @Javier-Rotelli, can you share why you feel this is a high priority? Is this affecting a project you're working on?

**Comment by Javier-Rotelli** [comment]
Hi! 
@Jahnp i haven't looked at the code closely enough. but my intuition is that the component should either encapsulate the options in a new data structure, or make a copy of the options and keep it in it's own state.  but i'm talking from a really quick check of the source, i'd need to understand it better if i want to send a good PR. 
also, for me this is high priority because it's an unintuitive behaviour for most of react devs. 
my team and I lost a couple of hours trying to debug a problem that arised because some of the options in a ChoiceGroup were part of a redux store and it was changing without the app knowing it.
