### ISSUE TITLE
Add card for SharePoint site

### ISSUE THREAD

**Issue by pschaeflein** [OfficeDev/office-ui-fabric-react#4654]
Provide a card for a SharePoint site as shown on the SharePoint home page (<tenant>.sharepoint.com/_layouts/15/sharepoint.aspx)

![image](https://user-images.githubusercontent.com/8008013/39149357-67e5800c-4704-11e8-9aff-0c54b0b741ad.png)

**Comment by KevinTCoughlin** [comment]
Seems similar to `DocumentCard` except that there are multiple actions per entity which may violate the existing "Don't" blocks under Best Practices:

> Don’t use the DocumentCard in views where the user is likely to be performing bulk operations in files, or when the list may get very long. Specifically, if you are showing all the items inside an actual folder, a card may be overkill because the majority of the items in the folder may not have interesting metadata.

> Don’t use the DocumentCard if space is at a premium or you can’t show relevant and timely commands or metadata. Cards are useful because they can expose on-item interactions like “Share” buttons or view counts. If your app does not need this, show a simple grid or list of items instead, which are easier to scan.

Definitely need Design to weigh-in here. My concern would be UX overload since that many actions result in a lot of truncated text making the card less actionable.

**Comment by pschaeflein** [comment]
The component is obviously in use already. I was hoping to not re-create it.

**Comment by aditima** [comment]
@pschaeflein - just to clarify, are you looking for a card with actual data-connection to SharePoint? Or just the UX piece that looks like the SharePoint site card. 

Fabric is by definition a backend agnostic UX-only repo, so the former component doesn't belong here.

**Comment by aditima** [comment]
That said, if you really want a SP-connected site card, we can make note of a request for that High-Value Component.

**Comment by pschaeflein** [comment]
I was thinking the UX piece. I have an app that works in the context of a unified group and want to link off to the site. I was hoping to put something pretty there instead just a link.

(But that High-Value-Component sounds interesting. :)  Are there other HVCs? I would love to learn more.)

**Comment by aditima** [comment]
Adding @dzearing for his thoughts on the potential UX-only piece. Should this just be a variant of the DocumentCard? There is some overlap with the ChicletCard as well. 
These are really all different UX representations of a generic Item - with potentially a picture, title, secondary/tertiary texts and some variable 'action' area that could host activities, command buttons, or even custom components.

@pschaeflein - regarding HVCs, yes, we do have a few in production and more in progress. Some of the notable examples are the PeopleCard (appears on hover on a person in various O365 apps like SharePoint, OWA) or the sharing control (used in OneDrive and SharePoint).

**Comment by pschaeflein** [comment]
Part of my issue, I think, may be the documentation or lack thereof. 

I agree the card for a SharePoint site could just be form of document card, with differing backgrounds for preview/title. But the Document Card documentation is quite strong abut using it only for documents. (Compare this to an Office 365 Card or Adaptive Card which are quite clear about their flexibility.)

HVC is an entirely new term. (As is ChicletCard.) Neither are on the Components page of the site. But their existence peaks my interest. I guess i would say that my expectations are that I can do everything that O365 does, but that is not yet the case. 

Lastly, please don't view this feedback as critical or negative. I love the components, just am struggling to use them since I am new to React. But, I plan to share this struggle on various platforms to help others.

**Comment by aditima** [comment]
@micahgodbolt - another feature request that needs us to revisit and rationalize our *Card components. Good candidate to add to our backlog I think.

**Comment by micahgodbolt** [comment]
We try to steer clear of adding app specific UI to Fabric. But we do want to do is make your implementation of a 'card' be nothing but Fabric components combined together.

What is it that you are suggesting we add to Fabric to make your UI easier to create?

**Comment by pschaeflein** [comment]
I think the thread is clear about what I was looking for. At this point, it seems I need to inject CSS to force a DocumentCardTitle to have a non-white background, and DocumentCardLogo + DocumentCardActions with a higher z-index and positioning attributes to put them over the styled DocumentCardTitle.

**Comment by micahgodbolt** [comment]
We are looking at creating a "Card" component that would be flexable and themable to support these types of scenarios. I've added that to our backlog. https://github.com/OfficeDev/office-ui-fabric-react/issues/5322

Until then, overriding DocumentCard via CSS will be your best bet.
