### ISSUE TITLE
Add a card for SharePoint News item

### ISSUE THREAD

**Issue by pschaeflein** [OfficeDev/office-ui-fabric-react#4655]
Provide a card for a SharePoint news as shown on the SharePoint home page (.sharepoint.com/_layouts/15/sharepoint.aspx)

![image](https://user-images.githubusercontent.com/8008013/39149439-a93f01ea-4704-11e8-9f2f-e58bd6192afa.png)

**Comment by lambertwang** [comment]
Does a [DocumentCard](https://developer.microsoft.com/en-us/fabric#/components/documentcard) fit your needs?

**Comment by pschaeflein** [comment]
The component is obviously in use already. I was hoping to not re-create it.

**Comment by Jahnp** [comment]
This usage is what the DocumentCard is meant for. Since the feature already exists, I'm going to go ahead and close this, unless there's some specific functionality you're looking for that DocumentCard doesn't provide today @pschaeflein . Thanks!
