### ISSUE TITLE
Inconsistent brand icon names

### ISSUE THREAD

**Issue by pschaeflein** [OfficeDev/office-ui-fabric-react#4659]
The name of the icon for OneDrive is different than other products:
- OutlookLogo
- SharePointLogo
- WordLogo

- OneDrive

**Comment by KevinTCoughlin** [comment]
Quick note, its useful to us to follow our [Issue Template](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/.github/ISSUE_TEMPLATE.md) when creating an issue so that we can triage it appropriately given impact and other factors. Regardless, we appreciate the reports 🙇.

**Comment by aditima** [comment]
@Jahnp - looking for your opinion on this...

**Comment by Jahnp** [comment]
Closing the loop here as this has been resolved in #4872. See [here](https://github.com/OfficeDev/office-ui-fabric-react/pull/4872/files#diff-8114584ae8cbf6d2d4f10b168284dabaL128). We added an [alias for the old OneDrive icon](https://github.com/OfficeDev/office-ui-fabric-react/pull/4872/files#diff-b36e4a5648e686196a6b7cffe458405cR4) to ensure existing users can carry forward unbroken.
