### ISSUE TITLE
Checkbox and FabricMDL2Icons dependency

### ISSUE THREAD

**Issue by malekpour** [OfficeDev/office-ui-fabric-react#466]
Currently Checkbox is using tick glyph form [office-ui-fabric-core](https://github.com/OfficeDev/office-ui-fabric-core) which itself depends on `FabricMDL2Icons` font. Due to https://github.com/OfficeDev/office-ui-fabric-core/issues/807 the font is proprietary and has to be loaded from the designated website.

So far this is the only hard dependency to `office-ui-fabric-core` project and would be great if Checkbox uses an alternative way to display check mark (preferably SVG).

**Comment by mikewheaton** [comment]
All of the icons in Fabric React come from Fabric Core, along with the web fonts and variables for type ramp, colors, etc. It's dependent on Core and that's intentional. Are you having problems with the CDN?

**Comment by malekpour** [comment]
This is more licencing issue. Dependency on `office-ui-fabric-core` is fine since it's licence is MIT but the font's licence makes thing complicated.

Currently you can create an offline electron package with `office-ui-fabric-core` and `office-ui-fabric-react` but the font has to be downloaded as far as I understand.

**Comment by mikewheaton** [comment]
Yes, this is an unfortunate consequence of how our web fonts (both Segoe UI and the icon font) are licensed. @ericthompson may have some more insight here but my understanding is that they can't be download or hosted elsewhere without violating the license terms.

Is it really just the checkmark icon that you're needing? If so, you could substitute it with another icon font (e.g. [Font Awesome](http://fontawesome.io/)) that has a similar symbol. Or create an SVG for this one instance. Not the ideal solution, but worth looking into.

**Comment by ericthompson** [comment]
@mikewheaton is correct - licensing prevents us from making the font available outside the CDN. I would definitely look into some alternatives if the system Fabric provides won't suit you. Font Awesome would probably do the job.

**Comment by malekpour** [comment]
Other than Fabric Core icons, [src/components/Checkbox/Checkbox.scss#L75](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/src/components/Checkbox/Checkbox.scss#L75) is the only location this project using the font. Even for online web projects doesn't seem optimal to depend on a 67KB font only for a check mark.

I will override the style likely with an svg alternative in my project. But please consider using a more opensource friendly font or try to change the font license.

**Comment by codepunkt** [comment]
> @mikewheaton is correct - licensing prevents us from making the font available outside the CDN. I would definitely look into some alternatives if the system Fabric provides won't suit you. Font Awesome would probably do the job.

Microsoft has been a good open source citizen lately. What's preventing you from also open sourcing this font/the icons under a commonly usable OSS license?
