### ISSUE TITLE
DetailsList isResizable column option doesn't work

### ISSUE THREAD

**Issue by manasark** [OfficeDev/office-ui-fabric-react#4672]
### Bug Report

- __Package version(s)__: (5.64.1)
- __Browser and OS versions__: (All browsers and Windows 10)

#### Priorities and help requested (not applicable if asking question):

Requested priority: (High) 

Products/sites affected: (IRIS Studio)

#### Describe the issue:

 isResizable column option in DetailsList  doesn't work.

#### Actual behavior:

We cannot resize the column header.

#### Expected behavior:

We should be able to resize the column header.

**Comment by KevinTCoughlin** [comment]
Will re-open with repro

**Comment by manasark** [comment]
@KevinTCoughlin We are currently using version 5.64.1. Can you please confirm if this issue doesn't exist in this version?
