### ISSUE TITLE
ToolTip doesn't go away while scrolling and not moving the cursor. 

### ISSUE THREAD

**Issue by twarzo** [OfficeDev/office-ui-fabric-react#4673]
### Bug Report
- __Browser and OS versions__: 
IE and Windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? 
No

Requested priority: 
Normal

Products/sites affected: 
VSTS

#### Describe the issue:

ToolTip doesn't go away while scrolling and not moving the cursor. 

#### Actual behavior:

ToolTip doesn't go away while scrolling and not moving the cursor. 

#### Expected behavior:

It should go away when we are scrolling. 

### If applicable, please provide a codepen repro:
Attached the GIF. 

![tooltiphost](https://user-images.githubusercontent.com/2266283/39241008-29fc3dc6-48a3-11e8-8a4f-28f78b4bd579.gif)

**Comment by KevinTCoughlin** [comment]
@twarzo, Our browser support matrix can be found @ https://github.com/OfficeDev/office-ui-fabric-react/blob/master/ghdocs/Testing/BrowserSupport.md.

In IE 11 the tooltip seems to go away better on-scroll than in the GIF you have for IE 10. Unfortunately, unless you find the behavior in IE 11 unacceptable I don't think we'll tackle this. Older versions of IE have different scroll and focus behaviors and debouncing which is likely to blame here.

**Comment by KevinTCoughlin** [comment]
Actually sorry @twarzo, I misread. Are you seeing this in IE11 or earlier? Because in IE11 it seems to go away reasonably well.. certainly not as long as your GIF.

**Comment by KevinTCoughlin** [comment]
I can't repro this in IE 11 on either a desktop or laptop w/ touch screen setup. I saw that the repro has mouse focus near the tool-tip and the scroll is done via touch. When I try that on my laptop in IE 11 the tool-tip immediately disappears. So this makes me think its a version < IE 11. I'm inclined to close this soon without more information.
