### ISSUE TITLE
GroupedList or how to sell a fraud?

### ISSUE THREAD

**Issue by OskarSol** [OfficeDev/office-ui-fabric-react#4674]
#### Category
- [x] Question
- [ ] Typo
- [ ] Bug
- [ ] Additional article idea

#### Expected or Desired Behavior

Expected: Office UI Fabric component GroupedList to work as expected: you have items organized in groups and the component renders like in the example. 

#### Observed Behavior

You have items;
You have groups;
Display all groups; 
At the lowest level of each group add a fixed amount of items from the items-collection!

#### Steps to Reproduce

Check the example: https://developer.microsoft.com/en-us/fabric#/components/groupedlist
And don't forget to check the implementation of the helper functions (createListItems and createGroups):  https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/example-app-base/src/utilities/data.ts 

Maybe I'm doing something wrong but if not you should remove this "_Component_" from your documentation, because in the current implementation it is completely useless.

**Comment by OskarSol** [comment]
Same here: Grouped DetailsList https://developer.microsoft.com/en-us/fabric#/components/detailslist

**Comment by michaelangotti** [comment]
@OskarSol Checking in on this one since it's been almost a month. Can you provide a codepen/example on the above?

**Comment by dzearing** [comment]
Closing.
