### ISSUE TITLE
TextField error message flickering using onGetErrorMessage

### ISSUE THREAD

**Issue by Feiyang1** [OfficeDev/office-ui-fabric-react#4685]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

#### Describe the issue:
In the TextField component, when error message is displayed and user keeps typing, the error message disappears and reappears causing flickering. 

#### Actual behavior:
In the TextField component, when error message is displayed and user keeps typing, the error message disappears and reappears causing flickering. 

#### Expected behavior:
the error message should stay instead of disappearing and reappearing when user is typing until a valid input is detected.

### If applicable, please provide a codepen repro:
see the number text field example at
https://developer.microsoft.com/en-us/fabric#/components/textfield

**Comment by oengusmacinog** [comment]
@Feiyang1 are you experiencing this issue on your own implementation?  As in not just on the example page?

**Comment by Feiyang1** [comment]
@oengusmacinog yep, I'm experiencing the same issue in my application.
