### ISSUE TITLE
How to apply the primary style to an iconButton?

### ISSUE THREAD

**Issue by lling1105** [OfficeDev/office-ui-fabric-react#4688]
The iconButton default style is "Standard" with gray background color and black text color. what i wanna do is change the iconButton style to "Primary" and how? 
i tried to change the className but doesn't work, below is the react codes.

```
import React, {Component} from 'react';
import {
    ColorClassNames,FontClassNames
} from '@uifabric/styling';
import { IconButton, IButtonProps } from 'office-ui-fabric-react/lib/Button';
var classNames = require('classnames');

export default class extends React.Component<IButtonProps> {
    render() {
        return (
            <div >
                <IconButton
                    iconProps={ { iconName: 'Add'}}
                    className={classNames(ColorClassNames.white,ColorClassNames.themePrimaryBackground,ColorClassNames.themePrimaryBackgroundHover) }
                    title='Add'
                    ariaLabel='Add'
                />
            </div>
        );
    }
}
```

**Comment by Markionium** [comment]
It should probably be as easy as just adding `primary={true}`? But unfortunately that does not work :( 

https://codepen.io/mpolak/pen/qYqKRJ?editors=0010#0

**Comment by micahgodbolt** [comment]
Yeah, we haven't done primary='true' for all buttons. The button refactor coming up should make this much clearer, but for now you can apply styles via the styles interface of buttons. 

https://codepen.io/micahgodbolt/pen/wRqQJM?editors=1010
