### ISSUE TITLE
Nav: onRenderItem behavior, child components and onClick / hover

### ISSUE THREAD

**Issue by Fensterbank** [OfficeDev/office-ui-fabric-react#4691]
I have an issue with the `onRenderItem` method of the `Nav` component.
My idea was to use `onRenderItem` to render an own `MainMenuLink` component, which contains the text and a clickable icon with hover effect.

The icon is faded in when the item is hovered and should be used, to add or remove the item from the user's favorites.
![grafik](https://user-images.githubusercontent.com/1684826/39359347-f849fd36-4a19-11e8-88f4-c588701e51a6.png)

I set `opacity: 0.5` on `.ms-Button:hover` (so the icon is visible when the menu item is hovered) and wanted to set `opacity: 1` on `.MenuItem i:hover` (so the icon gets more visible when it is hovered).
Additionally I have set an `onClick` method.

Unfortunately it does not work as expected.
In Mozilla Firefox, only `opacity: 0.5` is set on menu item hover, but hovering the star icon or clicking it does nothing. 
In Google Chrome, sometimes it works as expected, but sometimes not. If I clicked a star icon once, then it's like it was in Firefox. It's weird.
Since my app doesn't work on Microsoft Edge at the moment, I could not test the behavior there.

This is the created DOM structure:
The highlighted `MainMenuLink` is the component which is returned by `onRenderItem`.
![grafik](https://user-images.githubusercontent.com/1684826/39359626-0567d6cc-4a1b-11e8-8747-a430f09784b4.png)

I think the main question here is:

- Should `onRenderItem` be used the way I do it at all? Is it supported, to render components with own logic there?
- Is there a better way, to achieve my overall goal?
- Do we have a bug?

Thanks for sharing your thoughts!

**Comment by oengusmacinog** [comment]
@Fensterbank are you getting any specific console errors?

**Comment by Fensterbank** [comment]
@oengusmacinog No, there are no console errors.

I built an example to show what I mean: https://codesandbox.io/s/mornj9oymx
For every menu item I have three events:
`onLinkClick` as prop for `Nav` when a link is clicked.
`onItemClick` when the root item of the element rendered by `MainMenuLink` is clicked.
`onStarClick` when the favorite star is clicked.

**I notice the following:**
- Hovering the star will work.
- When I click a link, `onItemClick` and `onLinkClick` are triggered and the item gets the active state.
- When I click the star, `onStarClick`, `onItemClick` and `onLinkClick` are triggered and the item gets the active state.

**When the item is in active state:**
- Hovering the star does not work anymore.
- Clicking the star or the item is not registered in the element rendered by `MainMenuLink`. Only `onLinkClicked` which is managed by the Office UI component itself is triggered.

**So following questions are staying:**
- Is it supported by the component what I try to achieve here?
- Could I trigger the `onStarClick` event without triggering the others (e.g. event.preventDefault(), return false, etc)
- Why does hovering/clicking the star does not work when the item is selected? It's the same css selector and nothing relevant changed.

**Comment by Fensterbank** [comment]
So after some research and talking with friends I come to the conclusion that the thing I try is not supported.
Technically, buttons are supposed to grab all mouse events and act as a unified clicking surface, so child elements of `<button>` aren't part of hit testing.
Since it works partly, there definiteley are several issues in browsers when having interactive elements inside of `<button>`s.

Since this issue only occurs because I use `onRenderLink` where I place interactive elements inside of a `NavLink`, it's not a bug of Office UI Fabric itself, it's more kind of a _don't do it please_.

Closing it… 🍪
