### ISSUE TITLE
Typo on README

### ISSUE THREAD

**Issue by juancortez** [OfficeDev/office-ui-fabric-react#4692]
https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/styling
Typo on **themeSecondary**

```javascript
import {
  loadTheme({
    palette: {
      themePrimary: 'red',
      themeSeconary: 'blue'
    }
  });
}
```

**Comment by Markionium** [comment]
Thanks for reporting @juancortez  :D I've created a PR to fix it
