### ISSUE TITLE
Empty modules for TS files with only interfaces

### ISSUE THREAD

**Issue by cschleiden** [OfficeDev/office-ui-fabric-react#4694]
Because files like https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/utilities/src/IRenderFunction.ts are `.ts`, we generate empty modules for them: https://unpkg.com/@uifabric/utilities@5.29.0/lib-amd/IRenderFunction.js

Shouldn't we convert those to `.d.ts` so that no `.js.` module is generated by the compiler?

**Comment by cliffkoh** [comment]
It's a bit better in ES6 https://unpkg.com/@uifabric/utilities@5.29.0/lib-es2015/IRenderFunction.js

My only worry is about semantics of .d.ts though.. These files are not quite what I would traditionally associate a TS declaration file to be.

If we were to do this, wouldn't all the `.types.ts` file then become `.types.d.ts`, except if they had enums?
https://unpkg.com/office-ui-fabric-react@5.92.1/lib-amd/components/ActivityItem/ActivityItem.types.js

**Comment by cschleiden** [comment]
@cliffkoh Yep. We use `.d.ts` files in VSTS without problems. No module emitted, TS is happy.

**Comment by dzearing** [comment]
I'm a bit confused. This is just TypeScript output. What should be we doing differently? Cleaning up for TypeScript?

**Comment by dzearing** [comment]
Per discussion, will close.
