### ISSUE TITLE
Text is required on Checkbox

### ISSUE THREAD

**Issue by mike-morrison** [OfficeDev/office-ui-fabric-react#47]
The text field should be optional.  If I get some time, I will submit a PR, but customers are keeping me busy.

I am doing ````<Checkbox text="" />```` as workaround.

**Comment by mikewheaton** [comment]
Can you provide a screenshot to show where you're using a checkbox without a label?

**Comment by mike-morrison** [comment]
![image](https://cloud.githubusercontent.com/assets/6625993/17347472/b8e67264-58d5-11e6-868d-eb18d3c08d3d.png)

Like that with better alignment..

**Comment by cschlechty** [comment]
Rather than having no text, should we allow passing a label equivalent
instead so we can assure these controls are associated correctly?

**Comment by mikewheaton** [comment]
@cschlechty: That's my concern as well. If no label is provided, how do we make sure that whatever control is used (in this case, a text field) is associated correctly with the input?

What we're seeing for "Print images" is the ability to edit the text of a task? Or create a new one? It's not clear how to get into that state or commit the change.

**Comment by mike-morrison** [comment]
It is trying to mimic the [todomvc](http://todomvc.com) examples.  With this, double clicking a checkbox label, should change the label into a edit box with the current value.  Hitting enter should commit the change.  I just noticed there is a todo example in the source of this project, so I am going to check that out.

**Comment by dzearing** [comment]
I believe this has been resolved. There is no `text` property; only an optional `label`.
