### ISSUE TITLE
Grouped List - How to make use of Load More Functionality

### ISSUE THREAD

**Issue by prakashchetan001** [OfficeDev/office-ui-fabric-react#4704]
- __Package version(s)__: 5.88.0
- __Browser and OS versions__: Chrome

Are you willing to submit a PR to fix? (Yes, No)

Requested priority:  Normal

Products/sites affected:  Staffhub

#### Describe the issue:
**Background:**
The grouped list has mentioned specification where the developer can configure the same to render **'Load More/ Show all'** feature. The handling of the show more can also be controlled by adding the callback function. On click of the '' callback I want to add more Items to the particular group. Passing the new Items List is not getting reflected on click of add more. Looking at some of source the new items does not seem to be passing down the props

#### Actual behavior:
As soon as user hits Load More/ Show All Link in the footer of any group, the Grouped List gets Blank

#### Expected behavior:
The List under the group should be updated with the new set of Items.

### If applicable, please provide a codepen repro:
https://codepen.io/prakashchetan001/pen/OZmxPo?editors=1010

**Comment by aditima** [comment]
Hi @prakashchetan001 - I tried out a codepen example to render a partially fetched set of items in a grouped list, then click on 'Show All' link to fetch remaining items and update the list:
https://codepen.io/aditima/pen/WyOWrY

Hopefully this will help you. Thanks!

**Comment by aditima** [comment]
Hi @prakashchetan001 - Closing this now. Please reopen if you have more questions. Thanks!
