### ISSUE TITLE
Dropdown className is applied to inner div, not the outer ms-Dropdown-container

### ISSUE THREAD

**Issue by aappddeevv** [OfficeDev/office-ui-fabric-react#4705]
I'm not sure this is intentional or not but IDropdownProps.className is applied to ms-Dropdown which is inside ms-Dropdown-constainer. That was different than my expectations and makes it difficult to style the inner dropdown without having to set the width explicitly. I assume that's why the IDropdownProps.dropdownWidth exists though to get around this.

**Comment by michaelangotti** [comment]
@aappddeevv This is already in our backlog to be updated in a future release. We will close this issue for now.
