### ISSUE TITLE
ContextualMenu Local Dev Example Page Broken in IE

### ISSUE THREAD

**Issue by KevinTCoughlin** [OfficeDev/office-ui-fabric-react#4712]
### Bug Report

- __Package version(s)__: 5.92.0
- __Browser and OS versions__: IE11 and lower versions

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Low

Products/sites affected: Local Dev, http://localhost:4322/#/examples/contextmenu

#### Describe the issue:

The local dev examples page for ContextualMenu is broken in IE11 and lower due to the usage of `String.prototype.includes` which is unsupported.

#### Actual behavior:

The examples page for ContextualMenu @ http://localhost:4322/#/examples/contextmenu throws a console error and fails to render.

#### Expected behavior:

The examples page should load for ContextualMenu @ http://localhost:4322/#/examples/contextmenu w/o error.

### If applicable, please provide a codepen repro:

Not necessary, look at http://localhost:4322/#/examples/contextmenu with the solution running locally via `npm start`

**Comment by KevinTCoughlin** [comment]
Hmm now this no longer repros? Let me investigate further.

**Comment by KevinTCoughlin** [comment]
FWIW this for sure repros in local dev with

```
SCRIPT438: Object doesn't support property or method 'includes'
ComponentPage.js (207,13)
```

Which is also how I ran into this. Thought I saw it on the example Fabric site as well, but am unable to repro right now.

**Comment by lynamemi** [comment]
@KevinTCoughlin the Fabric website is probably a bit behind the ouifr releases.

**Comment by KevinTCoughlin** [comment]
@lynamemi yea must be.. tho I thought I ran into it earlier. Might be a cache at play. Definitely can repro locally across a number of components. Easy fix.. will PR shortly.
