### ISSUE TITLE
TooltipHost and ChoiceGroup components mutate props

### ISSUE THREAD

**Issue by JasonGore** [OfficeDev/office-ui-fabric-react#4715]
### Bug Report

- __Package version(s)__: 5.92.00
- __Browser and OS versions__: N/A

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
Yes

Requested priority: (Blocking, High, Normal, Low) 
Normal

Products/sites affected: (if applicable)

#### Describe the issue:

TooltipHost mutates calloutProps object before passing it to Tooltip as a prop.

#### Actual behavior:

TooltipHost mutates calloutProps with assign() call when used as prop for Tooltip.

```
            calloutProps={ assign(calloutProps, {
              onMouseEnter: this._onTooltipMouseEnter,
              onMouseLeave: this._onTooltipMouseLeave
            }) }
```

#### Expected behavior:

TooltipHost should not mutate external prop object. It should create a new object if it wants to change it before passing it to Tooltip.

**Comment by JasonGore** [comment]
I searched the codebase for similar issues and only found one other potential instance. I was hoping @micahgodbolt could comment on this change to see whether or not it should be changed so that it doesn't mutate options prop:

https://github.com/micahgodbolt/office-ui-fabric-react/commit/b47e1aa3c52271c5d0198c71b09369ffaa4d26d7#diff-3a29493b697d7f97a559b7bfb2f8b3fdR81

**Comment by micahgodbolt** [comment]
Any code I wrote more than a year ago is ripe for changing 😊
If it's causing problems I have no problem with others making adjustments to it, as long as original functionality is maintained.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by JasonGore** [comment]
It turns out this is a more complicated issue requiring a refactor due to IChoiceGroupOption  "output" props labelId, checked, and id which are documented as being maintained by the component. Props should be inputs to components only and any required outputs should be passed through prop callbacks.

Since this is a more complicated change I will create a new issue and close this one.
