### ISSUE TITLE
Panels should trap keyboard focus

### ISSUE THREAD

**Issue by eliblock12** [OfficeDev/office-ui-fabric-react#472]
Currently when tabbing through a Panel, focus does not stay within the Panel overlay and moves outside the modal UI into the rest of the page. Panels should use a FocusTrapZone to keep the focus constrained, as in other modal UI like Dialogs.

**Comment by dzearing** [comment]
That's not always true... it would depend on the type of panel.

**Comment by dzearing** [comment]
As a consumer you can always use a trap zone

**Comment by dzearing** [comment]
Maybe "overlays" should. and if a panel uses the overlay, then it would be weird to have focus behind the overlay.

**Comment by eliblock12** [comment]
Panels always have overlays just like dialogs. Consumers can't use trap zones because it prevents focusing on the Panel's close button or optional command bar.

**Comment by eliblock12** [comment]
#485 Added PR with fix.
