### ISSUE TITLE
ComboBox Question

### ISSUE THREAD

**Issue by cobbs-totem** [OfficeDev/office-ui-fabric-react#4734]
Is there anyway in the ComboBox component to show the list of options available as the user types (similar to how TagPicker works)?  And if so, a way control that filtered list as the user types?  

Right now, when the user types, it only seems to use a "startsWith" match, but I'd like to resolve the "available options" with mixed case and "contains".

**Comment by michaelangotti** [comment]
We do not support this functionality yet. @dzearing  @Jahnp  Is this something we want to schedule in the short term?

**Comment by jordandrako** [comment]
Is something like this the kind of functionality you're looking for? https://jordandrako.github.io/JavaScript30/06%20-%20Type%20Ahead/index-FINISHED.html

**Comment by cobbs-totem** [comment]
Yes, that looks like what I'm after.  Another good example is the "Auto Complete" component in Material UI.  See the "Filters" part, specifically:

https://www.material-ui.com/#/components/auto-complete

**Comment by michaelangotti** [comment]
@dzearing @Jahnp Thoughts on this one?

**Comment by dzearing** [comment]
I think the pickers would be a better component for this. https://developer.microsoft.com/en-us/fabric#/components/pickers
