### ISSUE TITLE
Is it possible to set the datepicker to be always visible?

### ISSUE THREAD

**Issue by blandine** [OfficeDev/office-ui-fabric-react#4735]
I searched in the docs but I couldn't find a way to set the datepicker to be always visible.
I'd like to avoid an extra click on the input.

Is it already implemented or should I fill a feature request?
Thanks for your time

**Comment by blandine** [comment]
Thanks for your quick answer.
I'd like to have an input with the datepicker (some users are faster if they can write the numbers directly).
I will look into using the calendar component with a custom input bound to it and see how it goes.

**Comment by michaelangotti** [comment]
@blandine Did the calendar component solve your issue? If so, we'd like to close this one for now.
