### ISSUE TITLE
PeoplePicker issue

### ISSUE THREAD

**Issue by Cazeu64** [OfficeDev/office-ui-fabric-react#4750]
### Bug Report

- __Package version(s)__: 1.4.1
- __Browser and OS versions__: Chrome

Requested priority: Normal

#### Describe the issue:

When using PeoplePicker, it is working fine, but I still got two issues in the browser log : 
`Uncaught TypeError: Cannot read property 'value' of null
    at NormalPeoplePicker.BasePicker.updateSuggestionsList (BasePicker.tsx:319)
    at NormalPeoplePicker.BasePicker.updateValue (BasePicker.tsx:292)
    at NormalPeoplePicker.BasePicker.onInputChange (BasePicker.tsx:371)`

And the second one :
`Uncaught (in promise) TypeError: Cannot read property 'value' of null
    at NormalPeoplePicker.BasePicker.resolveNewValue (BasePicker.tsx:359)
    at BasePicker.tsx:332`

I can't get them off

The null field is :
`this.input` in BasePicker.tsx

#### Actual behavior:

Working but logging issues

#### Expected behavior:

Remove thoses issues

Thanks in advance !

**Comment by jordandrako** [comment]
The current version of office-ui-fabric-react is v5.94.x. Are you sure you're using v1.4.1? If so, try updating to a newer version to see if you're still having this issue.

**Comment by michaelangotti** [comment]
@Cazeu64 Did updating the version solve your issue? If so, we'd like to close this one.

**Comment by Cazeu64** [comment]
Yeah, sorry, I thought I already reply there, but I was wrong. I was using 5.21 versions. Updating the version fixed the issue.

Can be close, thanks !
