### ISSUE TITLE
DialogFooter fails to render when it only has one child.

### ISSUE THREAD

**Issue by justinmwarner** [OfficeDev/office-ui-fabric-react#476]
Simple test:

In Dialog.Basic.Example.tsx, remove:

`<Button onClick={this._closeDialog.bind(this)}>Cancel</Button>`

In gulp serve, notice how none of the Dialog examples work.

When only one child is given, this.props.children is equal to that object, not an array.  So .map doesn't work.

Possible solutions:

1. 
```
    return [].concat(this.props.children).map(child =>
      <span key={ key++ } className='ms-Dialog-action'>{ child }</span>
    );
```

Not as performant, but only slightly.

2.
```
    let children = this.props.children;
    if (!(Object.prototype.toString.call(this.props.children) === "[object Array]")) {
      children = [this.props.children];
    }
    return children.map(child =>
      <span key={ key++ } className='ms-Dialog-action'>{ child }</span>
    );
```

3. 
```
    let children = this.props.children;
    if (!Array.isArray(this.props.children)) {
      children = [this.props.children];
    }
    return children.map(child =>
      <span key={ key++ } className='ms-Dialog-action'>{ child }</span>
    );
```

I'll be doing a PR with option 3 as it is more readable.  It's not available in older browsers, so if that's an issue, let me know.

**Comment by dzearing** [comment]
I think this does work... can you modify this codepen to repro?

http://codepen.io/dzearing/pen/NbKwwy
