### ISSUE TITLE
Standardize on "text", "secondaryText", and "tertiaryText"

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#4772]
A number of components have inconsistent naming conventions for rendering the text.

We have internally discussed and agreed we want to standardize all things:

Proposal:

Text should be rendered with the `text` prop.
Secondary text should be rendered with the `secondaryText` prop.

Work:

Persona: currently has "primaryText". This should be deprecated in favor of "text".
ContextualMenuItem: currently uses "name", deprecate in favor of "text"
Button: currently uses "description", deprecate in favor of "secondaryText"
ComboBox items: currently uses "value", deprecate in favor of "text"

These should be cleaned up, warnings added, and examples updated.

**Comment by dzearing** [comment]
While we are doing this, let's make sure our documentation in ghdocs includes instructions on the property way to deprecate things.

**Comment by JasonGore** [comment]
I've done the work for ContextualMenuItem, but as it affects CommandBar impl (which needs modifications to support new 'text' prop), I will wait to merge until 6.0's new CommandBar implementation is merged into mainline.

https://github.com/JasonGore/office-ui-fabric-react/tree/jagore/deprecate-contextualmenu-name
