### ISSUE TITLE
Firefox: HighContrast: disabled choce group option is not adhering to high contrast colors

### ISSUE THREAD

**Issue by b-priyank** [OfficeDev/office-ui-fabric-react#4774]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: Firefox 59.0.2 in Windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) 

Products/sites affected: visualstudio.com

#### Actual behavior:
In Firefox,
Disabled choice group option in high contrast is not shown in green color for "white on black" high contrast mode. Similarly, in "black on white" mode, in respective color.

#### Expected behavior:
In Firefox,
Disabled choice group option in high contrast should be shown in green color for "white on black" high contrast mode. Similarly, in "black on white" mode, in respective color.

### If applicable, please provide a codepen repro:

https://codepen.io/dzearing/pen/rWWZPW

**Comment by michaelangotti** [comment]
@b-priyank Firefox does not support High Contrast modes or does so inconsistently. We only support the high-contrast mode on IE/Edge. Closing this issue.
