### ISSUE TITLE
Multiple Instances of ToolTipHost on the same view

### ISSUE THREAD

**Issue by EA12** [OfficeDev/office-ui-fabric-react#4775]
### Bug Report
Package version: "office-ui-fabric-react": "5.21.0"
Browser and OS versions: Edge and Windows 10

Are you willing to submit a PR to fix? (No)

Requested priority: (High) 

Describe the issue:
Multiple instances of the ToolTipHost on the same view does not show the ellipsis, no ToolTip and does not truncate the text. 

I used the [Demo ](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Tooltip/examples/Tooltip.Overflow.Example.tsx) which does work fine.

The question is: How to implement a second Instance in the same view?
Can state vars be reused?
overflow: false,
isTooltipVisible: false

And how to assign the `onTooltipToggle={ (isTooltipVisible: boolean) => this.setState({ isTooltipVisible }) }` for the second instance?

And a related question: Is it supported to add a-TAG to the aria-describedby?

`<TooltipHost
                                                            content={ this.props.file.fileName }
                                                            id={ this.fileNameTooltipId }
                                                            overflowMode={ TooltipOverflowMode.Parent }
                                                            onTooltipToggle={ (isTooltipVisible: boolean) => this.setState({ isTooltipVisible }) }>
                                                            <span aria-describedby={ this.props.isTooltipVisible ? this.fileNameTooltipId : undefined }>
                                                                <a  target='_blank' className={styles.itemLink} href={this.props.serverRedirectedURL}>{ this.props.file.fileName }</a>
                                                            </span>
                                                        </TooltipHost>`

#### Actual behavior:
Does nothing

#### Expected behavior:
Should show the tooltip, truncate the text and show the ellipsis.

**Comment by micahgodbolt** [comment]
Is it possible to provide a repro of the bug in codepen? 

Here's a start of one. https://codepen.io/micahgodbolt/pen/vjWzZP

**Comment by micahgodbolt** [comment]
If you need to render an additional tooltip, you can use the tooltip instead of tooltipHost and provide your own state management. If you are able to provide a codepen demo, I'd be happy to try and dig in further.
