### ISSUE TITLE
Image: portrait/landscape size toggling with ImageFit.contain should adjust centering

### ISSUE THREAD

**Issue by Gustavogbs** [OfficeDev/office-ui-fabric-react#478]
I have implemented an image viewer using ImageFit.contain, with left and right arrows where I refresh my main component when the source of the image is changed. The problem is that after my 1st image, my current displayed image has always the CSS (ms-Image-image--landscape or ms-Image-image--portrait) of my previous image, then when I change the image the CSS changes to the right one, but then at this point it gets applied to the new image being displayed.

**Comment by dzearing** [comment]
Repro:
http://codepen.io/dzearing/pen/ENPzYM

**Comment by dzearing** [comment]
@yiminwu May affect some of your scenarios. Could you investigate?

**Comment by dzearing** [comment]
This is now merged and will be published shortly.
