### ISSUE TITLE
configureLoadStyles does not work

### ISSUE THREAD

**Issue by joerneu** [OfficeDev/office-ui-fabric-react#4789]
### Bug Report

- Package versions:

 - "office-ui-fabric-react": "5.96.0"
 - "microsoft/load-themed-styles": "1.7.56"
 - "aspnet-prerendering": "3.0.1"
 - "react": "16.3.2"

Are you willing to submit a PR to fix? (No)

Requested priority: Normal

#### Describe the issue:

According to the [documentation](https://github.com/OfficeDev/office-ui-fabric-react#server-side-rendering), we can use configureLoadStyles to collect styles while rendering on the server.

Even if I only render:

```
  <Fabric>
    <DefaultButton>
      I am a button.
    </DefaultButton>
  </Fabric>

```

the callback of configureLoadStyles is never called.

#### Actual behavior:

The callback that is passed to configureLoadStyles is never called and no styles are collected.

#### Expected behavior:

We should be able to collect the styles to send to the client.

Also see issue: [Server side rendering?](https://github.com/OfficeDev/office-ui-fabric-react/issues/616)

**Comment by ascot31** [comment]
+1 I am using this with Next.js but having same problem with

Package version:

next 6.0.6
office-ui-fabric-react 5.106.1

**Comment by dzearing** [comment]
We will track this issue with #616. We have a working solution that is far better than configureLoadStyles.
