### ISSUE TITLE
DetailsList fail to render the data as it is scrolled

### ISSUE THREAD

**Issue by manasark** [OfficeDev/office-ui-fabric-react#4793]
### Bug Report

- __Package version(s)__: (5.64.1)
- __Browser and OS versions__: (All browsers and Windows 10)

#### Priorities and help requested (not applicable if asking question):

Requested priority: ( High ) 

Products/sites affected: (IRIS Studio)

#### Describe the issue:

Scrolling down the items in DetailsList does not show all items. Instead the list will stay blank after a first 20 items.

#### Actual behavior:

As we scroll down to the bottom of the items, it shows empty page. Please find attached screen shot.

#### Expected behavior:

As we scroll down the to the bottom of the items, it should render new items.

![detailslist](https://user-images.githubusercontent.com/38311970/39691464-7c3861a8-5192-11e8-98c2-9f0365bcc7fb.jpg)

**Comment by KevinTCoughlin** [comment]
Hey @manasark, thanks for the report. Is it possible for you to provide an isolated repro in [Codepen](https://codepen.io/) or something similar? It will help us debug and solve whatever you are facing. Given your report I'd expect to see the same on the main site, https://developer.microsoft.com/en-us/fabric#/components/detailslist. However, it seems to be working as expected there.

**Comment by manasark** [comment]
@KevinTCoughlin Yes, if the DetailsList is spanning the entire page, then we dont have any issue. However, if the DetailsList is constrained to a section of the page (attached screen shot), then we notice this issue.
![detailslist-2](https://user-images.githubusercontent.com/38311970/39799437-14091784-5319-11e8-96f6-3e141af1043b.jpg)

**Comment by ipip2005** [comment]
I observed same issue in "List" component when rendering items with same size

**Comment by natalieethell** [comment]
Hey @manasark thanks for submitting this issue and @ipip2005 thanks for noting that you see the issue in `List`, too! 

I haven't been able to repro. I'm seeing that while scrolling, the list is blank for maybe half a second as the items are rendered, but it does seem to render pretty quickly. 

Could either of you potentially provide a repro in CodePen for us, maybe forking from this [DetailsList CodePen](https://codepen.io/dzearing/pen/EgqMZq)? That would make it easier for us to debug the issue. Thanks.

**Comment by Platzer** [comment]
@manasark as a workaround i put `onShouldVirtualize={() => false}` on my DetailsList as mentioned in #4204.

**Comment by davidhenley** [comment]
Same issue here.  onShouldVirtualize={() => false} fixes it.
