### ISSUE TITLE
ContextualMenuButton and ContextualMenuAnchor should be combined into one file

### ISSUE THREAD

**Issue by kelseyyoung** [OfficeDev/office-ui-fabric-react#4800]
### Bug Report

- __Package version(s)__: 5.96.1
- __Browser and OS versions__: N/A

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes (assigned to myself)

Requested priority: Normal

Products/sites affected: None

#### Describe the issue:

Recently ContextualMenuButton and ContextualMenuAnchor were created as their own separate components (see PR [here](https://github.com/OfficeDev/office-ui-fabric-react/pull/4741)). The differences between the two are very small and should be combined into one file where we take in a 'tag' prop to create the correct HTML element. Some of the differences are due to missing content in one or the other when they should exist in both

**Comment by michaelangotti** [comment]
@kelseyyoung Can this be closed?

**Comment by kelseyyoung** [comment]
@michaelangotti the work hasn't been done yet, it was spun off from that PR referenced

**Comment by dzearing** [comment]
@kelseyyoung I'd like to assign this to you as you opened it; would you have time to address? If not, we should consider closing unless you feel like this will add some value.

**Comment by JasonGore** [comment]
Based on comments and agreement that files can be kept as-is, I will close this issue for now.
