### ISSUE TITLE
Infinite loop on focusing input control inside of Dialog control

### ISSUE THREAD

**Issue by Solwo** [OfficeDev/office-ui-fabric-react#481]
The 'Uncaught RangeError: Maximum call stack size exceeded.' exception  raised when I put some text input control inside of Dialog control.

Chrome 54.0.2840,   "office-ui-fabric-react": "^0.65.1"   (reproduced on 0.63.3)
```
<div>
                <Dialog
                    isOpen={true}
                    type={DialogType.largeHeader}
                    title="myTitle"
                    isBlocking={ false }
                    isDarkOverlay={true}
                    containerClassName="edit-device-dialog fix-top" >
 
                <SearchBox value={text} onChange={ (c) => { typeSearchKeyword(c); } }/>
                <Button onClick={ () => { searchDevice(text) } }>Search</Button>

                   <DialogFooter>
                        <SetDeviceButton {...this.props} deviceId={this.props.deviceId}  />
                        <CancelButton {...this.props}  />
                    </DialogFooter>
             </Dialog>
</div>

```

   It seems the source, the FocusTrapZone.focus method calls _firstFocusableChild.focus(); and then both functions FocusTrapZone.prototype._forceFocusInTrap and FocusTrapZone.prototype._forceClickInTrap are called in sequence in loop until exception throwed. 

   When I set the Dialog property forceFocusInsideTrap={false},  exception did not throwed.

![stackoverflow](https://cloud.githubusercontent.com/assets/5130663/19949563/6d8f3356-a163-11e6-8d26-71d8d4f5b507.png)

**Comment by dzearing** [comment]
I'm trying to repro your issue... can you try and modify this codepen?

http://codepen.io/dzearing/pen/jVOMgO

**Comment by Solwo** [comment]
Hmm, for now I can't reproduce this issue, even on the original project. It seems, it depends on some timings. Let's close this issue for now. In case when I reproduce this issue in minimalist environment, I'll post details. 
    I've used the 'redux' and react-routing libraries. The page hosted on the SharePoint web part. Typing in the SearchBox control should immediately update the redux store which will cause to refresh the Dialog control.  Issue appeared when I clicked to anything in the dialog box or in the SearchBox, before typing any character. 
   Sometimes, when I set breakpoints in the browser on the focus-related events, issue did not appear. 

So, I'll close issue until it reproduced by somebody else or me,

**Comment by yaananth** [comment]
+1 to the issue. Can we reopen it?
Setting breakpoints as you said will make the issue not repro :(

This is what I did...
Launch a dialog from another dialog, then close the launched one.

![image](https://cloud.githubusercontent.com/assets/12280011/20118555/eecceeb8-a5d2-11e6-8711-7767453b04e9.png)

![image](https://cloud.githubusercontent.com/assets/12280011/20118569/fcd7f11a-a5d2-11e6-875c-ca05026df9a0.png)

![image](https://cloud.githubusercontent.com/assets/12280011/20118638/44101d14-a5d3-11e6-9cf6-371a0931b365.png)


FocusTrapZone.js:64 Uncaught RangeError: Maximum call stack size exceeded.(…)FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137FocusTrapZone.focus @ FocusTrapZone.js:64FocusTrapZone._forceFocusInTrap @ FocusTrapZone.js:88processElementEvent @ EventGroup.js:137Popup.componentWillUnmount @ Popup.js:29obj.(anonymous function) @ BaseComponent.js:148unmountComponent @ react.js:6644unmountComponent @ react.js:14799unmountChildren @ react.js:4644unmountChildren @ react.js:13162unmountComponent @ react.js:8295unmountComponent @ react.js:14799unmountComponent @ react.js:6654unmountComponent @ react.js:14799updateChildren @ react.js:4628_reconcilerUpdateChildren @ react.js:12997_updateChildren @ react.js:13101updateChildren @ react.js:13088_updateDOMChildren @ react.js:8251updateComponent @ react.js:8069receiveComponent @ react.js:8027receiveComponent @ react.js:14845updateChildren @ react.js:4607_reconcilerUpdateChildren @ react.js:12997_updateChildren @ react.js:13101updateChildren @ react.js:13088_updateDOMChildren @ react.js:8251updateComponent @ react.js:8069receiveComponent @ react.js:8027receiveComponent @ react.js:14845_updateRenderedComponent @ react.js:6982_performComponentUpdate @ react.js:6960updateComponent @ react.js:6879receiveComponent @ react.js:6773receiveComponent @ react.js:14845updateChildren @ react.js:4607_reconcilerUpdateChildren @ react.js:12997_updateChildren @ react.js:13101updateChildren @ react.js:13088_updateDOMChildren @ react.js:8251updateComponent @ react.js:8069receiveComponent @ react.js:8027receiveComponent @ react.js:14845_updateRenderedComponent @ react.js:6982_performComponentUpdate @ react.js:6960updateComponent @ react.js:6879performUpdateIfNecessary @ react.js:6787performUpdateIfNecessary @ react.js:14877runBatchedUpdates @ react.js:16743perform @ react.js:19056perform @ react.js:19056perform @ react.js:16682flushBatchedUpdates @ react.js:16765close @ react.js:16640closeAll @ react.js:19122perform @ react.js:19069perform @ react.js:16682flushBatchedUpdates @ react.js:16765closeAll @ react.js:19122perform @ react.js:19069batchedUpdates @ react.js:10666batchedUpdates @ react.js:16690dispatchEvent @ react.js:11643
![image](https://cloud.githubusercontent.com/assets/12280011/20118623/355f83c2-a5d3-11e6-965e-5bf00faae455.png)

**Comment by dzearing** [comment]
I've re-opened. I will ask the devs who worked in this area to take a look.

If you see an obvious fix here, feel free to submit a PR to speed up the process.

**Comment by dzearing** [comment]
ping.

**Comment by yaananth** [comment]
On latest, I don't seem to repro this...

**Comment by dzearing** [comment]
Thanks for the followup. I will close this, please re-open if you see a clear repro.
