### ISSUE TITLE
Teaching Bubble close icon on hover

### ISSUE THREAD

**Issue by marichinn** [OfficeDev/office-ui-fabric-react#4812]
#### Describe the issue:

The close icon on the teaching bubble turns white on hover instead of remaining blue. This is reproducible on the office fabric doc page. <a>https://developer.microsoft.com/en-us/fabric#/components/teachingbubble</a>

**Comment by aditima** [comment]
@dzearing - this seemed like a good first bug to fix, so assigned to Katherine. Please reassign if you need to.
