### ISSUE TITLE
ContextualMenuButton sets aria-checked attribute even if role is not menuitemcheckbox

### ISSUE THREAD

**Issue by peterdur-msft** [OfficeDev/office-ui-fabric-react#4814]
### Bug Report

- __Package version(s)__: 5.91.0
- __Browser and OS versions__: Chrome 66.0.3359.139, Win10 1709 

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal) 

Products/sites affected: (Detected by and in [Keros for Web](https://aka.ms/keros))

#### Describe the issue:

- Go to https://developer.microsoft.com/en-us/fabric#/components/contextualmenu
- Click on first "Click for ContextualMenu" button (under Variants > Default ContextualMenu)
- Contextual menu pops up
- Right-click first menu item (New), choose Inspect

#### Actual behavior:

- See following markup is generated for button
````
<button name="New" class="ms-ContextualMenu-link root-80" aria-label="New" aria-checked="false" aria-posinset="1" aria-setsize="7" aria-disabled="false" role="menuitem" tabindex="0"><div class="ms-ContextualMenu-linkContent linkContent-83"><span class="ms-ContextualMenu-itemText label-88 x-hidden-focus">New</span></div></button>
````
- Note markup contains `aria-checked="false"` and `role="menuitem"`

#### Expected behavior:

- `aria-checked="false"` should not be set; it is not applicable to the `menuitem` role (it is applicable to `menuitemcheckbox`, but the menu items here are not checkable)
- See www.w3.org/TR/wai-aria-1.1/#aria-checked for more details

#### Fix notes

This appears to be a regression. The behavior does not appear in Office Fabric 5.79.1. [ContextualMenuButton.tsx](https://github.com/OfficeDev/office-ui-fabric-react/blob/daa7b6966c7fc0e52cdfd9e7ac8ab902a3810f9d/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenuItemWrapper/ContextualMenuButton.tsx) currently says ` 'aria-checked': !!isChecked` whereas [older versions](https://github.com/OfficeDev/office-ui-fabric-react/blame/3628c32bef64366f39f051d95ca6d352dc4b7286/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx) said `'aria-checked': isChecked`. `isChecked` is set a few lines above:
````
const isChecked: boolean | null | undefined = getIsChecked(item);
const canCheck: boolean = isChecked !== null;
const defaultRole = canCheck ? 'menuitemcheckbox' : 'menuitem';
````
Note that in this code, the `defaultRole` is set to `menuitem` iff `isChecked` is null. It is therefore reasonable that `aria-checked` should not be set if `isChecked` is null, which is the behavior of the older code.

The fix may then be as simple as removing the `!!` from ` 'aria-checked': !!isChecked` here and in any similar locations.

**Comment by michaelangotti** [comment]
@joschect Do you recall why this code was changed?

**Comment by peterdur-msft** [comment]
Still tracking as issue 1255589 in mseng.

**Comment by KevinTCoughlin** [comment]
It looks like this may have been fixed as I can't repro on `master`:

**Checkable**:

![image](https://user-images.githubusercontent.com/706967/45113194-871ff380-b0fe-11e8-98a9-538315a64642.png)


**Not Checkable**:

![image](https://user-images.githubusercontent.com/706967/45113179-7e2f2200-b0fe-11e8-950a-3f652c467df5.png)

Note the absence of `aria-checked` when `role="menuitem"`

@peterdur-msft do you still see this issue? Regardless, I've got some tests I can add to make sure we don't regress.

**Comment by KevinTCoughlin** [comment]
@peterdur-msft thanks for following up and linking. I'm going to close this since the issue on our side is fixed. Keros is an awesome tool btw!
