### ISSUE TITLE
pivot examples don't render

### ISSUE THREAD

**Issue by matt-erhart** [OfficeDev/office-ui-fabric-react#4827]
Tried running a few of the pivot examples and didn't get any errors but couldn't get anything to show up. I see there have been some recent pivot changes, are the examples up to date? Are they copy/pastable or is there some provider needed to get them working? I tried  wrapping it in a <Fabric>.

**Comment by OneCyrus** [comment]
probably the same issue like here. I made a PR for this https://github.com/OfficeDev/office-ui-fabric-react/pull/4751
just waiting for @dzearing to review it.

**Comment by michaelangotti** [comment]
@matt-erhart We aren't able to repro this. Can you provide a code pen?

**Comment by dzearing** [comment]
The change was merged and should be good now.

**Comment by dzearing** [comment]
Hmmm. I have a suspicious there is some webpack stuff going on here. I tested in codepen and I see the pivot in non minified, but not in minified. Let me dig a little deeper.

**Comment by dzearing** [comment]
@OneCyrus figured it out. 

![image](https://user-images.githubusercontent.com/1110944/40039513-81f51f70-57cb-11e8-930e-7cbdcd58021f.png)

Not quite sure this change will work in minified.

**Comment by dzearing** [comment]
https://codepen.io/dzearing/pen/NpNjad

Works now! Hopefully this should also work with react hot loader, which I believe was the problem scenario.
