### ISSUE TITLE
document new styled() HOC in the merge-styles README.md

### ISSUE THREAD

**Issue by aappddeevv** [OfficeDev/office-ui-fabric-react#4829]
It seems that a major pattern is to use the `styled` HOC with the component broken out into a `C.base.tsx` and `C.tsx` (which uses `styled`). This is a request to document in the [merge-styles](https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/merge-styles) page. It seems  like the pattern should be described there. There is alot of abstraction coming out of the new styling approach and the merge-styles doc is a good document.

**Comment by dzearing** [comment]
I do think documentation is good. I don't think the merge-styles docs are the ideal place to do it.

We're in discussion of evolving the `styled` hoc to be more robust and to support stateless functional components. That's coming after 6.0 is complete.

In the meanwhile, all of the styling docs are available here:

https://github.com/OfficeDev/office-ui-fabric-react/blob/master/ghdocs/BestPractices/Styling.md
