### ISSUE TITLE
ChoiceGroup - aria-labelledby="" is getting added even if there no group label.

### ISSUE THREAD

**Issue by arunarokk** [OfficeDev/office-ui-fabric-react#4836]
### Bug Report

- __Package version(s)__: (5.96.0)
- __Browser and OS versions__: (chrome & edge windows 10)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? ( No)

Requested priority: (Normal) 

Products/sites affected: (if applicable)

#### Describe the issue:

For Choicegroup if there is no group label associated, aria-labelledby="" is getting added on the div. Keros tool showing this as error - Invalid Attribute value for aria-labelledby. 

#### Expected behavior:

Aria labelledby should not be added if there no group label associated with choice group

**Comment by michaelangotti** [comment]
@FalseLobster @arunarokk Can this be closed?

**Comment by FalseLobster** [comment]
AFK right now, but yea feel free to close. I addressed with my getStyles PR

Alicia
________________________________
