### ISSUE TITLE
Narrator reads non-selected when clicking on details list rows even in non-selection mode

### ISSUE THREAD

**Issue by ronak-92** [OfficeDev/office-ui-fabric-react#4848]
### Bug Report

- __Package version(s)__:  5.91.0
- __Browser and OS versions__: Narrator on Edge
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? If required, yes, but don't know the fix

Requested priority: High

Products/sites affected: VSTS

#### Describe the issue:
When clicking on any row in details list with selection mode set to none, narrator reads out **non-selected** after reading the row content. It works fine with NVDA + firefox

User with visual impairments will not be able to know that the data rows are non interactive elements
#### Actual behavior:

IsSelectionItemPatternAvailable property is true for the non interactive data rows in details list
Narrator is announcing '\<row content\>, **non-selected**,'
#### Expected behavior:

IsSelectionItemPatternAvailable property should be False for the non interactive data rows in details list. Narrator should not announce the data row as **selected** or **non selected**

### If applicable, please provide a codepen repro:

https://codepen.io/ronaka/pen/RyybXw
same behavior could be observed on Fabric official samples page.

**Comment by JasonGore** [comment]
Issue officially documented for Edge: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14844849/
