### ISSUE TITLE
LayerPage: Can't scroll on website until after dismiss of example

### ISSUE THREAD

**Issue by lynamemi** [OfficeDev/office-ui-fabric-react#4861]
This example: 'Using Customizer to control the default layer behavior' has a panel popped up on page load. Until you dismiss it, you can't scroll the page.

**Comment by lynamemi** [comment]
@ThomasMichon assigning this one to you since it look like you're codeowner for Layer

**Comment by natalieethell** [comment]
It looks like this issue was fixed with this PR: #5692! I'll close this out.
