### ISSUE TITLE
Hyperlink clicks aren't selecting items in SelectionZone (Disabled in PR 4544)

### ISSUE THREAD

**Issue by biranchipanda** [OfficeDev/office-ui-fabric-react#4866]
Changes in PR #4544 is preventing hyperlinks in SelectionZone from clobbering interactive sub-elements. An attribute to allow this would be much helpful to existing implementations. 

#### Actual behavior:

click on a hyperlink is no longer selecting the item.

#### Expected behavior:

Hyperlink click should propagate selections. As discussed, "data-selection-auto-select='true'" on the button (or any element nested in the button or on its own) and should ensure that mousedown selects the item before propagating the handler.

**Comment by JasonGore** [comment]
Resolved by #4907.
