### ISSUE TITLE
Screen Reader  is Reading role property of contextual menu twice

### ISSUE THREAD

**Issue by arunnagar15** [OfficeDev/office-ui-fabric-react#4869]
**Bug Report**

**Describe the issue:**

Narrator is Reading role of contextual menu twice:
I have used the Details List with contextual menu and did accessibility testing on it using Screen Reader and found the following issue:

**Issue Details:** 
 When Narrator reaches to Contextual menu and enter is pressed than popup of action opens and focus is set to the popup and Narrator reads the role property twice.

**Actual behavior:**
Narrator read Contextual Menu role property twice.

**Expected behavior:**
Narrator should read Contextual Menu reads role property one time

**Comment by kkjeer** [comment]
@arunnagar15 could you please provide a CodePen for this issue?

**Comment by arunarokk** [comment]
verified in latest version this issue not repro.

**Comment by arunnagar15** [comment]
Issue not reproing in latest version , so closing this issue
