### ISSUE TITLE
ProgressIndicator has invalid aria-valuenow="NaN" when using Indeterminate / no percentComplete

### ISSUE THREAD

**Issue by ian-craig** [OfficeDev/office-ui-fabric-react#4871]
### Bug Report

- __Package version(s)__: 5.100.0
- __Browser and OS versions__: Chrome / Win10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: High

#### Describe the issue:

`<ProgressIndicator />` uses the indeterminate UI when `percentComplete` prop isn't specified, but the resulting HTML still has `aria-value` attributes. The `aria-valuenow="NaN"` is invalid.

```html
<div class="ms-ProgressIndicator-progressBar progressBar-45" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="NaN"></div>
```

#### Actual behavior:

`aria-valuenow="NaN"`

#### Expected behavior:

Exclude `aria-valie

**Comment by dzearing** [comment]
This seems like a pretty simple change; we can hold off looking into this if you plan to have a PR to address shortly! Let us know!
