### ISSUE TITLE
Link focus outline breaks on links that wrap across lines

### ISSUE THREAD

**Issue by BrendanMcK** [OfficeDev/office-ui-fabric-react#4883]
### Bug Report

- __Package version(s)__: Latest 
- __Browser and OS versions__: Any

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No; unclear what right fix is for Fabric

Requested priority: Normal

#### Describe the issue:

Focus outlines for links breaks when the link wraps around a line. (Also, the outline box can obscure the initial character if it's something like an I or l.).

#### Actual behavior:

![image](https://user-images.githubusercontent.com/1754373/40096917-130464c8-5888-11e8-9586-20cd61c85609.png)

The problem is that the focus outline is provided via an absolutely-positioned ::after pseudo-element: but that approach only works for block content, not inline content that wraps lines. 

#### Expected behavior:

Would expect similar to the browser default, where each of the disjoint spans of the link get their own outline:
![image](https://user-images.githubusercontent.com/1754373/40097024-afce3928-5888-11e8-8457-024986275eff.png)

Can repro this on the Link component page, though depending on the browser, may have to add padding text so that the link text ends on column boundary.

**Comment by lambertwang** [comment]
After testing, it looks like the behavior is inconsistent across browsers.
![multiline anchor element](https://user-images.githubusercontent.com/6496608/40442276-fee18c64-5e77-11e8-8787-51d8a4638b41.png)
On IE11 and Chrome, the link outline is broken in the same way. On Firefox, the outline no longer obscures text, but it still doesn't work quite as intended.  

One fix we could try is to add `display: inline-block` to the anchor element links. This is currently how button links are rendered. This forces the link to never be split across line breaks.
![multiline anchor inline-block](https://user-images.githubusercontent.com/6496608/40445160-34b5ab92-5e80-11e8-8be6-8e67c35a6160.png)

**Comment by BrendanMcK** [comment]
Changing display to inline-block though ends up looking really ugly from a design POV. I'm not at all convinced that this is the correct fix.

My take is that there may really be two different use-cases here - inline-links, and non-inline links - and they may need different approaches. Inline links *should* wrap - but will need some other form of focus outline since the positioned overlay block won't work there.

**Comment by BrendanMcK** [comment]
For what it's worth, the approach we've been using with links in Yammer so far is that for inline text links, we use an inset box shadow to get a thin outline that's consistent across browsers, and which works nicely with wrapping, and avoids the focus clipping that often happens with the default focus on webkit browsers. It also picks up the natural text color, so gets us good contrast. (IIRC, we do need a HC-specific rule to ensure this is also visible in HC mode, as ISTR that HC will otherwise remove box-shadow.)

But for cases where a link contains a block component instead of just text (eg link containing image that covers the entire surface area of the link), then we add a utility class/style to do something similar to the positioned ::after highlight used in Fabric.

(Would be awesome if the component itself could figure out what's appropriate rather than relying on the code author to do so; though unsure how viable it is to do this robustly. Could a link reliably introspect its contents to determine the appropriate focus style? Not convinced this is reliably doable though.)

One of the annoying things about HTML/CSS here is how some functionality is coupled to layout policy. Navigability *also* gets you one layout policy; but clickability/action-ness gets you a *different* layout policy.

**Comment by BrendanMcK** [comment]
Another side-effect of using the overlay-style focus on inline links is that it can obscure some of the text at the start/end - see related (issue 4945)[https://github.com/OfficeDev/office-ui-fabric-react/issues/4945]. Box inset works a touch better here.

**Comment by betrue-final-final** [comment]
@lynamemi?

**Comment by micahgodbolt** [comment]
@BrendanMcK can you point me to your link styles? Curious to see how it looks. Seems there's still a bit of clipping using inset.

**Comment by micahgodbolt** [comment]
I can do this with 
```
selectors: {
          ':focus': {
            margin: '0 -1px',
            border: '1px solid' + theme.palette.white,
            outline: '1px solid' + theme.palette.neutralSecondary
          }
        }
```

![image](https://user-images.githubusercontent.com/1434956/43027360-ad679434-8c2e-11e8-9acd-82a21bd5c7a9.png)

**Comment by micahgodbolt** [comment]
which looks a bit differnet when blown up/run into each other.

![image](https://user-images.githubusercontent.com/1434956/43027414-e808dbfc-8c2e-11e8-953a-f30dc21803b3.png)

**Comment by BrendanMcK** [comment]
We have something similar to:

a:focus {
    outline: 0;
    box-shadow: inset 0 0 0 1px;
}

![image](https://user-images.githubusercontent.com/1754373/43027606-3ffd5f4e-8c30-11e8-976d-2b5bae4c74e2.png)

Works nicely for inline text; and unlike border, doesn't affect size or position. But for links that contain other content - notably links wrapped around images, it can get covered/hidden by the content - so we use a different style in those situations. We essentially have our links default to inline behavior, and need a flag specified for when they are behaving more like block containers.

**Comment by micahgodbolt** [comment]
Does that work alright in high contrast mode?


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by BrendanMcK** [comment]
We re-state the same rule in a HC selector to support HC mode on IE/Edge - so full version looks more like:

```
*:focus {
  box-shadow: inset 0 0 0 1px;
}
@media screen and (-ms-high-contrast: active) {
  *:focus {
    box-shadow: inset 0 0 0 1px;
  }
```

This only works on IE/EDGE, not Firefox. We just don't support HC mode on Firefox, as it doesn't provide a good set of tools to let us work with it - ie system colors, media query + ability to override.

Another nice feature of this technique is that the box shadow picks up the text color: so if the text has a good contrast ratio, the outline does too.

**Comment by micahgodbolt** [comment]
awesome. I'll play around with that. In the past we have done a border+outline combination to better support highcontrast. If this does the trick, maybe we can simplify our own styles.

**Comment by BrendanMcK** [comment]
FWIW, we currently have something of a 'toolkit' of focus styles in Yammer - brief summary of how these are used follows:

- default focus style is the one outlined above. Most of our links are text links - notably user/group permalinks, so this works great as a default *for us*.

- we do have some buttons where we want the focus to be inset a bit extra in HC mode, notably for flat buttons that gain a border in HC mode; we want the focus outline to be distinct from the border vs being right adjacent to it. We add an yj-use-inset-focus utility class to trigger this within a HC media query - and the impl uses stacked inset boxes:

```
    box-shadow: inset 0 0 0 1px Window, inset 0 0 0 2px;
```

- when we have links that contain content - images, or cards - then we have another utility class - yj-use-overlay-focus - that explicitly trigger the ::after pseudo-element-based outline that sits on top of the children. This is similar to Fabric's current default focus - though we only pull it when we explicitly needed.

```
.yj-use-overlay-focus:focus::after {
  content: '';
  position: absolute;
  width: 100%;
  height: 100%;
  top: 0;
  left: 0;
  box-shadow: inset 0 0 0 1px white, inset 0 0 0 2px black, inset 0 0 0 3px white;
  pointer-events: none;
}
@media screen and (-ms-high-contrast: active) {
  /* Use thicker version in high contrast mode, so that it's visually distinct from
   * a regular box border.
   */
  body.yj-acc-show-outlines .yj-use-overlay-focus:focus::after {
    box-shadow: inset 0 0 0 1px Window, inset 0 0 0 3px WindowText, inset 0 0 0 4px Window;
  }
}
```

**Comment by BrendanMcK** [comment]
One caveat with box-shadow - and that is that if the link contains block content, it must itself be block (vs inline). If you have an inline element containing block content, the inline element gets split into two, and you end up with two tiny inline bits before and after the block, and no visible border/outline around the actual content block.

**Comment by micahgodbolt** [comment]
This would be a good issue to revive @KevinTCoughlin. There's still a little discussion left on the right way to do it, but it'd be nice to work with @BrendanMcK to align on a consistent solution to this problem.
