### ISSUE TITLE
Slider: Cannot set default value as 0

### ISSUE THREAD

**Issue by Leko** [OfficeDev/office-ui-fabric-react#4886]
### Bug Report

- __Package version(s)__: 5.95.0
- __Browser and OS versions__: 

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: (Blocking, High, Normal, Low) 

Products/sites affected: (if applicable)

#### Describe the issue:
I want to use Slider as below:

```js
        <Slider
          label='Brightness:'
          min={-100}
          max={100}
          step={1}
          defaultValue={0}
          showValue
          onChange={...}
        />
```

But default value is not working.

#### Actual behavior:
<img width="246" alt="screen shot 2018-05-16 at 21 31 08" src="https://user-images.githubusercontent.com/1424963/40116987-7b957068-5950-11e8-9e38-6a5b34ca8d89.png">

https://github.com/OfficeDev/office-ui-fabric-react/blob/694cb08865394dd94afd938c5524775ecd7ebab4/packages/office-ui-fabric-react/src/components/Slider/Slider.tsx#L53

I think it is bug.
`0` is falsy but corrected value.

#### Expected behavior:
Check value is `null` or `undefined`, not falsy. like,

```
const value = props.value != null ? props.value : props.defaultValue != null ? props.defaultValue : props.min; 
```

### If applicable, please provide a codepen repro:

https://codepen.io/L_e_k_o/pen/odabZO

**Comment by aditima** [comment]
@Leko - Thanks for reporting! We'd appreciate a PR to fix this.
