### ISSUE TITLE
Close button on TeachingBubble has glaring background on hover

### ISSUE THREAD

**Issue by MLoughry** [OfficeDev/office-ui-fabric-react#4888]
### Bug Report

- __Package version(s)__: 5.100.0, 6.0.0-beta4

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes, if there's a redline from design

Requested priority: Normal

#### Describe the issue:

The TeachingBubble's close button has a bright grey background on hover that contrasts with the blue callout background and washes out the white `X` icon

![image](https://user-images.githubusercontent.com/20823465/40132806-a5107eb4-58f2-11e8-9fd9-14d44b2475a7.png)

**Comment by jordandrako** [comment]
@betrue-final-final @Jahnp This seems to be another broken contract from the IconButton change I made a while back. Are we agreed that I should revert?
