### ISSUE TITLE
SearchBox: the "clear" button does weird things.

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#489]
http://codepen.io/dzearing/pen/jVOMgO

1. it should not cause the searchbox to grow and shrink.
2. if you press tab while in the searchbox, it goes to a mystery location.

**Comment by dzearing** [comment]
Eddie maybe you can take a look?

**Comment by leddie24** [comment]
Hey @dzearing,

1.  Looks like .ms-Dialog-main has a min-width and max-width set, but not an explicit width set if the window width is > 480px.  This allows .ms-SearchBox-field to grow/shrink with the extra (LTR) padding on focus.  I I think our 2 solutions are either set a width on .ms-Dialog-main for window width > 480px, or (the less ideal solution) remove the LTR padding.  I'll try to find another solution without changing Dialog in the meantime.

2. What's the expected output for this?  From checking document.activeElement, it looks like it goes back to <body>

**Comment by dzearing** [comment]
This is fixed.
