### ISSUE TITLE
'DetailsList Locked Header' bug with horizontal scroll

### ISSUE THREAD

**Issue by IASamoylov** [OfficeDev/office-ui-fabric-react#4890]
### Bug Report

- __Package version(s)__: (5.100.0)
- __Browser and OS versions__: (chrome/firefox/safari windows 7/macos)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal) 

#### Describe the issue:

If the width of content  more than width of the container, then sticky header does not scroll with content.

#### Actual behavior:

![epwNV_](https://media.giphy.com/media/4NkqCAYDZkbLE6Pwk5/giphy.gif)

#### Expected behavior:

sticky of headers scroll with content

### If applicable, please provide a codepen repro:

npm start
go to [http://localhost:4322/#/examples/scrollablepane](http://localhost:4322/#/examples/scrollablepane)

**Comment by aditima** [comment]
@leddie24 - we discussed this, and the suggested fix is add a scroll listener on the DetailsHeader so that we can sync with the body scroll and scroll the header automatically.
Also, on the ScrollablePane demo page, a separate scroll bar appears for the header. We definitely do not want that.

**Comment by leddie24** [comment]
Closed via #5169
