### ISSUE TITLE
TextField type="password"

### ISSUE THREAD

**Issue by fabianhussl** [OfficeDev/office-ui-fabric-react#490]
Hi, 
we are starting with office ui fabric react and want to realize a login-screen (user & password).
How can I get a TextField like <input type="password" />?

Regards,
Fabian

**Comment by dzearing** [comment]
Hi @fabianhussl i played with it here:

http://codepen.io/dzearing/pen/ZBEVzw

And realized passing through type doesn't work. So I made a PR here:

https://github.com/OfficeDev/office-ui-fabric-react/pull/492

Will be published with the next build.

**Comment by dzearing** [comment]
This has been merged.

**Comment by fabianhussl** [comment]
hi @dzearing,
thank you for your quick reaction! 
If I set package.json dependecies to `"office-ui-fabric-react": "=0.66.0"` it still don' work with `<TextField type='password' />`. 

I do not know myself so well, but can it be that this change is not yet included in the npm package?

**Comment by japrogramer** [comment]
How did you handle an on submit event, did you change the state of the component onChange for the field? can I see
