### ISSUE TITLE
Some icons not displaying

### ISSUE THREAD

**Issue by bpringe** [OfficeDev/office-ui-fabric-react#4902]
### Bug Report

- __Package version(s)__: 1.4.1
- __Browser and OS versions__: Chrome - 66.0.3359.181. Windows 10 v10.0.16299 Build 16299

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

#### Describe the issue:

Some icons not displaying. Specifically I have noticed the TimeEntry and TimeSheet icons do not display. Other icons I have tried have worked.

#### Actual behavior:

Icons do not display.

#### Expected behavior:

Icons should display.

I've created a web part SPFx project with the SharePoint yeoman generator. In the render method of the main component I add icons like below and all of the ones I have tried work except the TimeSheet and TimeEntry icons. Perhaps the Icons documentation has the wrong name for them?

`<i className="ms-Icon ms-Icon--TimeSheet" aria-label="Manager Dashboard"></i>`

**Comment by lynamemi** [comment]
@bpringe this looks like a FabricCore issue. Could you open in that repo? Thanks!
https://github.com/OfficeDev/office-ui-fabric-core

**Comment by bpringe** [comment]
Ah, yes. My apologies!
