### ISSUE TITLE
[TextField] Error message does not hide after typing when "validateOnFocusOut" attribute is set.

### ISSUE THREAD

**Issue by IASamoylov** [OfficeDev/office-ui-fabric-react#4903]
### Bug Report

- __Package version(s)__: (5.104.0)
- __Browser and OS versions__: (all)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes)

Requested priority: (Low) 

#### Describe the issue:

Error message does not hide after typing when "validateOnFocusOut" attribute is set.  This bug appears since version 5.97.0

#### Actual behavior:

![epwNV_](https://media.giphy.com/media/20DUCpoqzt6UdVkHZB/giphy.gif)

#### Expected behavior:

![epwNV_](https://media.giphy.com/media/w8DIurNbUY5rQvNsNM/giphy.gif)

### If applicable, please provide a codepen repro:

https://jsfiddle.net/6ugj050n/1/

**Comment by oengusmacinog** [comment]
@IASamoylov if you reference the [documentation](https://developer.microsoft.com/en-us/fabric#/components/textfield#Implementation) the `validateOnFocusOut` prop will as the description says "Run validation only on input focus out".  So when you stop typing nothing will happen.  Validation only occurs on the field when you focus out.  Unless I am misunderstanding, this feature is working as it was designed.

**Comment by IASamoylov** [comment]
@oengusmacinog  Yes, you right. But i'm say about another case. I'm expected behavior of version 5.97.0

[5.96.0](https://jsfiddle.net/Lo26dkfm/1)

| User action                   | Behavior of component     |
|-------------------------------|---------------------------|
| look to input                 | Error message is hidden   |
| typing incorrect value        | Error message is hidden   |
| input focus out               | Error message is shown    |
| **typing incorrect value**      | **Error message is hidden**   |
| input focus out               | Error message is shown    |

[5.104.0](https://jsfiddle.net/6ugj050n/1/)

| User action                   | Behavior of component     |
|-------------------------------|---------------------------|
| look to input                 | Error message is hidden   |
| typing incorrect value        | Error message is hidden   |
| input focus out               | Error message is shown    |
| **typing incorrect value**      | **Error message is shown** |
| input focus out               | Error message is shown    |

**Comment by oengusmacinog** [comment]
Hi @IASamoylov.  After talking with our design team, we have decided the new functionality is the best and most consistent UX option.  By default, the **TextField** component will validate when you stop typing so it is a more consistent experience to not clear out the error message until valid input is entered in the field.  If you are choosing to utilize the `validateOnFocusOut` prop to only validate on focus out, then it makes sense to be consistent and only remove the error once the valid input is detected on focus out.  If you want more immediate validation the default behavior of validating when the user stops typing may be a better option.

For now, I am closing this issue, but please feel free to reopen if you would like to suggest a specific use case you think would be a better universal UX flow with Fabric TextField validation.
