### ISSUE TITLE
Fabric Panel focus order is improper with choice group in the panel

### ISSUE THREAD

**Issue by AkshanshSrivastava03** [OfficeDev/office-ui-fabric-react#4912]
### Bug Report

- __Package version(s)__: 5.55.1002
- __Browser and OS versions__: Chrome

#### Describe the issue:
Panel focus order is improper when choice group is rendered within the Panel.

#### Actual behavior:
Suppose you have choice group with options "a" and "b" in the panel.

The focus first goes to cross button of the panel, then the choice group option "a", then tabbing will make you focus the page title/window etc.

If you select option "b" my moving key down, then the focus will remain inside the Panel which is the expected behavior. But by default, as "a" is selected, the focus goes out of the Panel

#### Expected behavior:
Focus order should remain inside the panel ony

### If applicable, please provide a codepen repro:
https://codepen.io/AkshanshSrivastava03/pen/mXZpwp

This is dup of this bug
#4191 @KevinTCoughlin

**Comment by michaelangotti** [comment]
Closing this one as it is a dup of #3666
