### ISSUE TITLE
[DetailsList][Accessibility] aria-rowindex property is zero-based, which is not supported

### ISSUE THREAD

**Issue by daweffe** [OfficeDev/office-ui-fabric-react#4915]
### Bug Report

- __Package version(s)__: 5.54.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: wasabi

#### Describe the issue:

The details list rows have the aria-rowindex property filled out with 0-based indices. According to the WAI-ARIA spec: 

Authors MUST set the value for aria-rowindex to an integer greater than or equal to 1, greater than the aria-rowindex value of any previous rows, and less than or equal to the number of rows in the full table. For a cell or gridcell which spans multiple rows, authors MUST set the value of aria-rowindex to the start of the span.

The parent of these rows with role="grid" should also have the aria-rowcount property set.

See: https://www.w3.org/TR/wai-aria-1.1/#aria-rowindex

**Comment by JasonGore** [comment]
This was resolved by #4515 which is merged into [v5.82.0.](https://github.com/OfficeDev/office-ui-fabric-react/releases/tag/office-ui-fabric-react_v5.82.0)
