### ISSUE TITLE
SearchBox's clear icon doesn't work when input has a focus

### ISSUE THREAD

**Issue by sadomovalex** [OfficeDev/office-ui-fabric-react#4917]
### Bug Report

- __Package version(s)__: 5.21.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

#### Describe the issue:

When input element of SearhcBox has focus onClear event is not triggered. As result SearchBox is not cleared. Here is the possible reason of this behavior:
when focus is not in input element SearchBox has the following elements:
[magnifier][input][X]
when we set focus to input - magnifier got hidden:
[input][X]
If in this case we click [X] input element losts focus and we again have 3 elements:
[magnifier][input][X]

i.e. [X] div is shifted to the right on the same size as width of [magnifier] div (and they both have 32px width) and mouse click event's (x, y) coordinates is not in [X] div anymore. So probably because of that browser doesn't trigger event in this case.

Expected behavior is to have onClear even triggered both when focus is in and out of input element.

We used the following workaround: override css styles so magnifier div became always visible (both with and without focus in input element). In this case onClear event works regardless of focus.

**Comment by micahgodbolt** [comment]
can you try this with a more recent version of Fabric? I don't seem to have any problems in this codepen (unless you can explain repro steps) 

https://codepen.io/micahgodbolt/pen/GQpPGx

**Comment by sadomovalex** [comment]
In those version which is used in codepen example the issue is not reproduced: clear button works when input field has a focus. So issue may be closed.
