### ISSUE TITLE
backgroundSize property missing from the IRawStyleBase interface

### ISSUE THREAD

**Issue by nali** [OfficeDev/office-ui-fabric-react#4920]
### Bug Report

- __Package version(s)__: 5.106.1

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: OWA

#### Describe the issue:

[`backgroundSize`](https://developer.mozilla.org/en-US/docs/Web/CSS/background-size) is missing from the [IRawStyleBase type definition](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/merge-styles/src/IRawStyleBase.ts).

**Comment by micahgodbolt** [comment]
give me a shout if you want a hand with this PR.
