### ISSUE TITLE
How to inline edit and add action icons to nav items?

### ISSUE THREAD

**Issue by somecoder2019** [OfficeDev/office-ui-fabric-react#4925]
I am trying to show a list of files in Nav. I want to provide functionality for users to edit the names and delete the files. I want the below behavior (taken from the nav example https://developer.microsoft.com/en-us/fabric#/components/nav).

Is there an easy way to add the icons (delete icon in this case) when user hovers the mouse over an item? Also want a way to edit the item. 

![capture](https://user-images.githubusercontent.com/38018965/40264114-09f9bc56-5ad2-11e8-8c83-60b7d31b2a55.JPG)

**Comment by somecoder2019** [comment]
Hi,

Any help on this? This is a fairly common scenario. For example, in VSTS I see the three dotted extended menu. 

![capture](https://user-images.githubusercontent.com/38018965/40938349-82c0a18c-67f6-11e8-9112-6c2e94d43ac0.PNG)

**Comment by JasonGore** [comment]
The only way to do this with Nav currently is to make use of the `onRenderLink` , but that requires you to provide the content for the entire row. This is most likely what VSTS is doing. I did a super basic CodePen here (without justification): https://codepen.io/jasongore/pen/XYdKXE

We are currently working on a newer, more composable version of Nav starting with [CollapsibleSection,](https://github.com/OfficeDev/office-ui-fabric-react/pull/5063). It should make customized scenarios like the one you are asking for much easier and composable.  

I will close this for now, but if I haven't addressed your question, please let me know. Thanks!

**Comment by sunny-lan** [comment]
@JasonGore could you put the example CodePen in a more permanent location? The link seems to go to the wrong code.

Thanks!
