### ISSUE TITLE
Overide default size of Fabric UI components

### ISSUE THREAD

**Issue by CaptainSadaf** [OfficeDev/office-ui-fabric-react#4928]
I have been working with Fabric UI and i have tried to set the 12px font size to ms-fabric class but it does not applied to all nested components.

I have override the font size of ms-Command Bar by using .ms-CommandBar class and it's working but margin and padding is not working fine.
Do i need to copy all fabric css classes and then override all nested level classes or is any other optimal solution for that purpose? How i can set the 12px fontSize to all fabric components instead of 14px.

To identify and copy all nested fabric classes is very time consuming and lazy solution. is any proper way to adjust the components once i override the fonSize of fabric Component.

Currently Fabric provides 14px default font size but components seems too big and occupying some extra space too.

**Comment by CaptainSadaf** [comment]
@dzearing please would you like to help me ?

**Comment by JasonGore** [comment]
This is a goal of #5035 so I will close this issue as a duplicate (subset) of #5035.
