### ISSUE TITLE
Datepicker variant - No input text box

### ISSUE THREAD

**Issue by amygl** [OfficeDev/office-ui-fabric-react#493]
Need a datepicker variant that will launch the datepicker when clicking on a button. This is in a scenario where there isn't space for the input box.

Something like below:
![image](https://cloud.githubusercontent.com/assets/10605976/20021810/cc185a88-a294-11e6-853e-58a25cf316e3.png)

**Comment by dzearing** [comment]
I agree. I don't think it would be a difficult refactor but it makes sense to me. If you'd like to take a stab at a PR we'd gladly take a look.

**Comment by ericthompson** [comment]
@amygl - could we get a screenshot showing the whole view? We're just trying to get a sense of the context.

**Comment by amygl** [comment]
Here's a screenshot of the existing view using jquery datepicker. We are working on migrating over to using Office Fabric React. We have a quick date picker that can quickly launch from a card and want to use fabric's date picker here.  The full date picker (with input box) is seen on a details pane.
![image](https://cloud.githubusercontent.com/assets/10605976/20356721/4218b46e-abda-11e6-9097-587372a79dfa.png)

**Comment by dzearing** [comment]
This is now available as the `<Calendar />` component.
