### ISSUE TITLE
Close button for the Message Bar is not visible properly in the High Contrast Black mode.

### ISSUE THREAD

**Issue by adimittal91** [OfficeDev/office-ui-fabric-react#4936]
### Bug Report

- __Package version(s)__: 5.76.0
- __Browser and OS versions__: 
OS Version: 1803 (Build 17666.1000)
Browser: Internet Explorer 11.1000.17666.0, Edge 42.17666.1000.0
AT: High Contrast Black

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) 
Normal

Products/sites affected: (if applicable)
PowerBI Visio Visual

#### Describe the issue:

Close button for the Message Bar is not visible properly in the HC Black mode.

User Impact:

Visually Impaired users may not be able to visualize the mentioned button.

#### Actual behavior:

Close button for the Message Bar is not visible properly in the HC Black mode.

#### Expected behavior:

Close button for the Message Bar adapts to the HC Black mode. (White with a black background.)

**Comment by adimittal91** [comment]
![high contrast closebutton](https://user-images.githubusercontent.com/13768392/40373817-5db9695a-5e05-11e8-99e9-a5dcb47f548e.png)

**Comment by betrue-final-final** [comment]
Thanks! @lynamemi, I suspect that the close X needs some love. It should be white.

**Comment by BrendanMcK** [comment]
Note that while it should likely be white in the Black HC theme, the color to use depends on the specific HC theme: so it may need to be a different color in some of the other HC theme modes.

**Comment by betrue-final-final** [comment]
Thanks @brendanmck, we will use windowtext color for it. "White" was just short hand between @lynamemi and I.

**Comment by BrendanMcK** [comment]
Given that it's interactive, is WindowText the correct value? This is a button, right?

**Comment by betrue-final-final** [comment]
In non-high contrast, the icon is grey, just like the text in the message bar. Therefore, it should be windowText.
