### ISSUE TITLE
Navigation through Tab key does not go to to disabled UI controls

### ISSUE THREAD

**Issue by anjali2408** [OfficeDev/office-ui-fabric-react#4937]
### Bug Report

- __Package version(s)__: 5.76.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable) Power BI Visio Visual

#### Describe the issue:

Navigation through Tab key does not go to to disabled UI controls.

#### Actual behavior:

Navigation through Tab key skips disabled UI controls

#### Expected behavior:

Navigation through Tab key should not skip disabled UI elements. As an Accessibility requirement, the Tab naviagation should be same for all users including accessible users. Accessibility documentation at [MAS 5](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/Doc.aspx?sourcedoc=%7BB3C14341-5E68-4FFD-BC3E-92FCD2E8FED2%7D&file=MAS%2005%20-%20Focus%20Order.docx&action=default&mobileredirect=true )

This document states requirement as: “Support a focus order that is aligned with the meaning or operation of the UI”
Since we are disabling and not hiding the UI for these fabric controls, this requirement is valid.

**Comment by betrue-final-final** [comment]
@dzearing, @jspurlin, @Jahnp, @aditima, @michaelangotti this relates to our current discussion. I'll set up a meeting next week with Peter so we can decide on the course of action.

**Comment by jspurlin** [comment]
@betrue-final-final I believe @dzearing and is currently working with an engineer on this for buttons.

**Comment by micahgodbolt** [comment]
@betrue-final-final has a meeting been set up for this yet, and if not can I join. I'm created a backlog item in VSTS to track this work. I believe this should be a larger effort to support this functionality across many components.

**Comment by micahgodbolt** [comment]
button now supports `  allowDisabledFocus?: boolean;`
