### ISSUE TITLE
ChoiceGroup: Focus order in Fabric Panel is not working with Narrator on

### ISSUE THREAD

**Issue by ssingh28** [OfficeDev/office-ui-fabric-react#4938]
- __Package version(s)__: 
microsoft/sp-core-library: ~1.4.1
  office-ui-fabric-react: ^5.86.0
        react:^15.6.2
react-dom: ^15.6.2
- __Browser and OS versions__: Win 10, Microsoft Edge version 41.16299.402.0

Requested priority: (Blocking, High, Normal, Low) : High

Products/sites affected: (if applicable)

#### Describe the issue:
If i keep the narrator running and try to shift focus between different choice group options on a panel,
the focus is not getting transferred to the correct elements and the narrator is not able to identify the choice group options. The same issue can be re pro at the office fabric site for choice group on edge + narrator

https://developer.microsoft.com/en-us/fabric#/components/choicegroup

### If applicable, please provide a codepen repro:

open below link in Edge with Narrator on and try to navigate from one choice group option to another.

https://developer.microsoft.com/en-us/fabric#/components/choicegroup

**Comment by JasonGore** [comment]
Narrator seems to be working fine and vocalizing the ChoiceGroup options correctly. The navigation conforms to the [ARIA spec](https://www.w3.org/TR/wai-aria-practices-1.1/#radiobutton). Here is an [ARIA radio group reference example](https://www.w3.org/TR/2017/WD-wai-aria-practices-1.1-20170628/examples/radio/radio-1/radio-1.html) that may help serve as a reference point for navigation and Narrator behavior.

The only minor difference I could find is the highlight area Narrator shows. Are you talking about this?

![image](https://user-images.githubusercontent.com/26070760/40944998-bf157e86-680b-11e8-90cd-9d5430368f3f.png)

I am not seeing any other differences in behavior as of v.6.3.0.

**Comment by dzearing** [comment]
@ssingh28 can you respond to @JasonGore 's question?

**Comment by dzearing** [comment]
Closing due to no traction. This does not appear as a bug in the Fabric ChoiceGroup at all.
