### ISSUE TITLE
Developer tools in chrome gets hanged while debugging for dropdown on panel

### ISSUE THREAD

**Issue by ssingh28** [OfficeDev/office-ui-fabric-react#4939]
### Bug Report
microsoft/sp-core-library: ~1.4.1
  office-ui-fabric-react: ^5.86.0
        react:^15.6.2
react-dom: ^15.6.2
- __Browser and OS versions__: Win 10, Chrome Version 66.0.3359.181 (Official Build) (64-bit)

Requested priority: (Blocking, High, Normal, Low) : High

#### Describe the issue:

If i have a drop down on panel and i open developer tools in chrome and set a debug point in render of my drop down, chrome developer tools will hang and nothing works. I have to again reload the page and the debug session is no longer valid. Causes waste in productivity.

**Comment by dzearing** [comment]
This has nothing to do with Fabric! Please avoid opening bugs that can't actually be 
addressed in Fabric.

I did try debugging the render of Dropdown in Chrome. I was able to hit a breakpoint.

It is far more likely that you're in an environment (SharePoint page) that is loading a ton of content which is overloading chrome debugger. It also might be how the scripts are injected/loaded. If they're eval'd for example, (you use webpack with "eval" mode), Chrome might have a different debugging experience than if it's loading via array index evaluation.

But this is all controlled within your SharePoint page. None of this has anything to do with the Dropdown or any Fabric component.
