### ISSUE TITLE
Let BaseComponent._Async.throttle Become Cancelable like lodash did

### ISSUE THREAD

**Issue by qianghuang94** [OfficeDev/office-ui-fabric-react#4960]
Hi Team,
Recently i am try to use the throttle function that provided by this._async inside BaseComponent, the [code link](
https://github.com/OfficeDev/office-ui-fabric-react/blob/3d06688daa90a5f2b037cef48539ccc3b9176a15/packages/utilities/src/Async.ts#L251)

Is there any plan to add cancelable to the throttle function like lodash did?

Thanks,
Qiang

**Comment by micahgodbolt** [comment]
adding to our VSTS backlog. I'll close this issue for now, but will update if/when we have updates.
