### ISSUE TITLE
reactxp and office-ui-fabric-react ?

### ISSUE THREAD

**Issue by pawelmod** [OfficeDev/office-ui-fabric-react#4961]
Hello, 
Is [reactxp](https://github.com/Microsoft/reactxp/issues/new) compatible with [office-ui-fabric-react](https://github.com/OfficeDev/office-ui-fabric-react#advanced-usage)?
In other words: do we have out-of-the-box Android and iOS views for mobile and "office look" for Windows / Web?

If not: could it be **future request** to have it compatible?

**Comment by micahgodbolt** [comment]
No specific plans yet for an 'out of the box' Android/iOS compatible Fabric, but it's certainly something we're discussing. We'll take a peak at reactxp as well! Thanks for the tip.
