### ISSUE TITLE
Context menu lacking customizable tooltips

### ISSUE THREAD

**Issue by suztocco** [OfficeDev/office-ui-fabric-react#4966]
### Bug Report

- __Package version(s)__: Current
- __Browser and OS versions__: 

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? NO

Requested priority: LOW

Products/sites affected: CALENDAR/MAIL

#### Describe the issue:

I was told by the fabric designers that we should only show a tooltip "if" text is truncated and we needed a way to show full text. Not to show a tooltip on text that is visible within the context menu items. 

#### Actual behavior:

I believe either tooltips are "on" or "off". So either a tooltip shows for every text item or it does not show for any text item. 

#### Expected behavior:

I expect to see a tooltip if I hover over a truncated text item only.

You can see here that the non truncated text is showing a tooltip

![image](https://user-images.githubusercontent.com/20954039/40447344-1ad528f4-5e87-11e8-9d0d-c925032cef99.png)

and then for other menus no tooltips show  (because it's set to off...?)
![image](https://user-images.githubusercontent.com/20954039/40447410-50fe0bd0-5e87-11e8-8544-02614d54eb77.png)

**Comment by satishkumaragarwal** [comment]
I think the Command Bar component needs to expose a interface to customize the tooltip.

**Comment by micahgodbolt** [comment]
this is as much the contextual menu as it is the command bar. I agree that any truncated item should automatically get a tooltip, and that we should provide a way to specify tooltip props.

**Comment by khmakoto** [comment]
Closing in favor of #10681.
