### ISSUE TITLE
Changing command bar color

### ISSUE THREAD

**Issue by somecoder2019** [OfficeDev/office-ui-fabric-react#4967]
Hi,

How do I change the command bar color from default?

I am following the documentation for command bar. I do not want to change the theme overall (I saw some examples for this). I want to render the main command bar in blue color and white text (like the outlook email for example)

I can simply add override colors, but the text color seems to not change accordingly. 

https://developer.microsoft.com/en-us/fabric#/components/commandbar

**Comment by micahgodbolt** [comment]
Not sure if this was already discussed via email, but here is an example of being able to style the commandbar bg in our new 6.0 release

https://codepen.io/dzearing/pen/zzOzKZ

**Comment by somecoder2019** [comment]
Thanks @micahgodbolt, this worked.
