### ISSUE TITLE
the JSON variables output of the Theme Generator is not ISO with loadTheme palette interface

### ISSUE THREAD

**Issue by PooLP** [OfficeDev/office-ui-fabric-react#4986]
### Bug Report

- __Package version(s)__: office-ui-fabric-react : 5.107.0 and office-ui-fabric-core : 9.6.0
- __Browser and OS versions__: All and All

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: (High) 

#### Describe the issue:

the JSON variables output of the Theme Generator is not ISO with loadTheme palette interface (IPalette).
If you use the default json ouput of theme generator, some variable don't not work :

JSON default output :
```json
{
  "themePrimary": "#0078d4",
  "themeLighterAlt": "#eff6fc",
  "themeLighter": "#deecf9",
  "themeLight": "#c7e0f4",
  "themeTertiary": "#71afe5",
  "themeSecondary": "#2b88d8",
  "themeDarkAlt": "#106ebe",
  "themeDark": "#005a9e",
  "themeDarker": "#004578",
  "neutralLighterAlt": "#f8f8f8",
  "neutralLighter": "#f4f4f4",
  "neutralLight": "#eaeaea",
  "neutralQuaternaryAlt": "#dadada",
  "neutralQuaternary": "#d0d0d0",
  "neutralTertiaryAlt": "#c8c8c8",
  "neutralTertiary": "#c2c2c2",
  "neutralSecondary": "#858585",
  "neutralPrimaryAlt": "#4b4b4b",
  "neutralPrimary": "#333",
  "neutralDark": "#272727",
  "black": "#1d1d1d",
  "white": "#fff",
  "primaryBackground": "#fff",
  "primaryText": "#333",
  "bodyBackground": "#fff",
  "bodyText": "#333",
  "disabledBackground": "#f4f4f4",
  "disabledText": "#c8c8c8"
}
```
primaryBackground, primaryText, bodyBackground, bodyText, disabledBackground, disabledText are not in IPalette interface.

Result in VS Code :

![theme](https://user-images.githubusercontent.com/582733/40532829-0b28ccfa-6001-11e8-9d2d-43c774a9af92.png)

#### Expected behavior:

A update of theme genrerator.

Thanks.

**Comment by micahgodbolt** [comment]
@phkuo looks like primaryBackground/primaryText had a todo to say remove. Are these ready to be removed from the theme generator?

**Comment by phkuo** [comment]
@micahgodbolt unfortunately not, large portions of sp-client copied-and-pasted a bunch of old code and they're using that in a lot of places. Now that I've got SASS variables exporting from here, I've asked them to update the copied code to reference the exports instead, which will get them off the old slots.

@PooLP what error is VSCode giving you? ```palette``` just implements IPalette, so it should allow for additional members on it without issue.

**Comment by PooLP** [comment]
I have this error :
```
[Ts]
The argument of type '{palette: {"themePrimary": string; "themeLighterAlt": string; "themeLighter": string; "themeLig ..." is not attributable to the parameter of type 'IPartialTheme'.
   The types of the 'palette' property are incompatible.
     Can not assign type '{"themePrimary": string; "themeLighterAlt": string; "themeLighter": string; "themeLight": string ... 'to type' Partial <IPalette> '.
       An object literal can only specify known properties, and '"primaryBackground"' does not exist in the type 'Partial <IPalette>'.
```
I think that the JSON theme generator should be the right one, we should not have to add additional members, even if it's possible.

**Comment by phkuo** [comment]
Theoretically the theme generator is agnostic of the slots we choose to use for the Fabric theme. It's supposed to be extensible to anyone to define their own slots and make their own rules. In practice, it's really only used for Fabric theming. I've removed non-IPalette members (see attached PR), I'll keep this discussion in mind going forward about how practical/useful it is to keep it separate from Fabric theming.
