### ISSUE TITLE
The recommended way to use a custom font ?

### ISSUE THREAD

**Issue by PooLP** [OfficeDev/office-ui-fabric-react#4987]
Hi,

What's the recommended way to use a custom font ? by React/Typescipt (loadTheme), SASS, another way ?

Thanks.

**Comment by dzearing** [comment]
Right now, we are in a half and half state. We are closely tracking this however and will have this resolved shortly once 6.0 ships, as customizability is our #1 ask.

Tracking in #5035

**Comment by PooLP** [comment]
Thanks for response, it's a good news !
