### ISSUE TITLE
TagPicker: onEmptyInputFocus not working in IE

### ISSUE THREAD

**Issue by qazqwertish** [OfficeDev/office-ui-fabric-react#4988]
### **Bug Report**

- Package version(s): ^5.76.0 (Tested also with 5.111.0)
- Browser and OS versions: Internet Explorer 11

**Describe the issue:**

We use the function "onEmptyInputFocus" to show all the possible options when clicking on the input. It works perfect in Chrome but not in IE. 

When debugging we see that the function is called, and it returns all the values, but then it gets stuck (code is not stopped anywhere) and nothing appears.

To make the suggestions appear in IE these are the steps we follow:
1. Click on the input
2. Open another window (like the Windows Explorer to see a folder)
3. Go back to the browser (Then it appears)

Our picker is:
` <TagPicker ref='tagPicker' 
onItemSelected={this.onItemSelected}
onEmptyInputFocus={this.onEmptyInputFocus}
onResolveSuggestions={this.onResolveSuggestions}
onRenderItem={this.onRenderItem}
onRenderSuggestionsItem={this.onRenderSuggestionsItem}
getTextFromItem={this.getTextFromItem}
pickerSuggestionsProps={suggestionCfg}
onDismiss={this.onDismiss}
inputProps={{ placeholder: 'Search {0}...'.format(this._displayName) }}
/>`

And the function:
`private onEmptyInputFocus(): ITag[] | Promise<ITag[]> {
        return this._pickerItems;
    }`

Do someone experienced the same issue before? Thanks in advance!
Ismael

**Comment by qazqwertish** [comment]
Found what generates this behavior: the placeholder. **If you set the placeholder in the inputProps it will make this error appear in IE for the TagPicker.**

Removing the placeholder can be a workaround, but I think it is something that worth to check for future releases.

**Comment by oengusmacinog** [comment]
Hi @qazqwertish! Could you please provide a repro of the issue using [codepen](https://codepen.io/) or something similar?

**Comment by qazqwertish** [comment]
Hello @oengusmacinog, here I created a basic example with 2 TagPickers. As you can see the one on the bottom has a placeholder and in IE11 does not show the suggestions with the OnEmptyInputFocus.

[https://codepen.io/qazqwertish/pen/BVNMeW](https://codepen.io/qazqwertish/pen/BVNMeW)

**Comment by JasonGore** [comment]
Still reproing. Anybody who looks at this issue may have to make their own fork of the CodePen on their account before CodePen will let you view it in IE11.
