### ISSUE TITLE
Dropdown menu lacking customizable tooltips

### ISSUE THREAD

**Issue by suztocco** [OfficeDev/office-ui-fabric-react#4993]
**Bug Report**
**Package version(s):** Current
**Browser and OS versions:**

**Are you willing to submit a PR to fix?** NO

**Requested priority:** LOW

**Products/sites affected:** CALENDAR/MAIL

**Describe the issue:**
I was told by the fabric designers that we should only show a tooltip "if" text is truncated and we needed a way to show full text. Not to show a tooltip on text that is visible within the context menu items.

**Actual behavior:**
I believe either tooltips are "on" or "off". So either a tooltip shows for every text item or it does not show for any text item.

**Expected behavior:**
I expect to see a tooltip if I hover over a truncated text item only.

You can see here that the non truncated text is showing a tooltip
![image](https://user-images.githubusercontent.com/20954039/40557520-3e05926c-6005-11e8-994a-ce920914f1ee.png)

**Comment by dzearing** [comment]
I already have a PR out for this! :)

**Comment by dzearing** [comment]
https://github.com/OfficeDev/office-ui-fabric-react/pull/4983/files

**Comment by dzearing** [comment]
#4974 Tracking. Resolving dupe.

**Comment by suztocco** [comment]
Nice, does that affect the Context menus as well?
