### ISSUE TITLE
Cursor location is incorrect for textfields with multiline placeholder in Edge

### ISSUE THREAD

**Issue by dcowen91** [OfficeDev/office-ui-fabric-react#4994]
### Bug Report

- __Package version(s)__:  5.111.1 
- __Browser and OS versions__: Microsoft Edge 42.17134.1.0 

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Workplace Analytics

#### Describe the issue:

In Edge Browser, the cursor location when focusing into a multi-line Textfield with multi-line placeholder is incorrect.

#### Actual behavior:

The cursor is placed on the last line of the placeholder. When the user enters any input, the cursor will jump to the first line.

#### Expected behavior:

The cursor is placed on the first line, where the actual input will start.

### If applicable, please provide a codepen repro:

https://codepen.io/anon/pen/RyzOEp

**Comment by dzearing** [comment]
This has nothing to do with UI Fabric. This is an Edge bug.

https://codepen.io/dzearing/pen/dKbaOG?editors=0010

**Comment by dcowen91** [comment]
Ah, you are right. Closing.

**Comment by dzearing** [comment]
@dcowen91 Just an fyi! I cycled with the Edge team. They are aware of the issue and are tracking a fix. Thought I'd pass along.

**Comment by dcowen91** [comment]
Awesome, good to know. I appreciate the FYI, Thank you!
