### ISSUE TITLE
Split button control not to spec

### ISSUE THREAD

**Issue by suztocco** [OfficeDev/office-ui-fabric-react#4997]
### Bug Report

- __Package version(s)__: Not sure but referencing this PR https://github.com/OfficeDev/office-ui-fabric-react/pull/4922

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? NO

Requested priority: NORMAL

Products/sites affected: CALENDAR, PEOPLE, probably others

#### Describe the issue:

The split button does not seem to be quite to visual spec

#### Actual behavior:

Not to spec

#### Expected behavior:

To be to spec

Issues I see. @betrue-final-final as design back up to check this

Visual:

- The arrow looks to be too small
- Press state bg color doesn't seem to be showing for the chevron (only after I've pressed)
- I don't think the chevron is getting darker on the hover/press states
- The selected hover state is missing for the chevron (but for Mail/Cal we are looking to do away with this state)

**Comment by suztocco** [comment]
@micahgodbolt - Just wanted to check on status on this.

**Comment by micahgodbolt** [comment]
I'll be on shield duty in a couple weeks. I'll try to take a look then.

**Comment by suztocco** [comment]
Sounds good

**Comment by Jahnp** [comment]
@suztocco is this still an issue for you? We're revisiting component styles with the Fluent updates and I wonder if we can address any issues here as a part of that work.

cc @Vitalius1 @betrue-final-final for visibility and who may know more about the issues involved (I don't have the toolkit in front of me)

**Comment by Vitalius1** [comment]
We have all the states in the toolkit. I think this is a valid bug that needs to be fixed with the fluent work I do. We might wanna then port them to the current master for users on Fabric 6.

**Comment by Jahnp** [comment]
That's great, thanks Vitalie--makes sense to me. We can prioritize the Fluent work and plan to do a backport separately. I'll assign this to you for now and we can talk about transferring if it makes sense.

**Comment by khmakoto** [comment]
Let's have this be part of #6134, which covers a wider array of button-related issues.
