### ISSUE TITLE
Types extending React.Props have direct dependency on Components causing large bundle size

### ISSUE THREAD

**Issue by pchandoria** [OfficeDev/office-ui-fabric-react#5006]
### Bug Report

Are you willing to submit a PR to fix? Yes, already submitted

Requested priority: Normal

Products/sites affected: Any consumer using this library might be impacted depending upon usage scenario

#### Describe the issue:

If any component depends merely upon the types exported from fabric, it causes hard dependency on corresponding Component class due to extend React.props<ComponentName> pattern. This causes extra bytes of code for the bundle size which just refers to the type. 

#### Actual behavior:

Bundle size is large when depending upon types

#### Expected behavior:

Bundle size impact should be zero when just depending upon types

**Comment by dzearing** [comment]
This is not true.

As mentioned in mail, using a component purely as a typing does not impact bundle size whatsoever.

Please check `lib/Button.types.js` as an example. The TypeScript version refers to `ContextualMenu` as a type, but no imports actually import code in the produced javascript.
