### ISSUE TITLE
Is there a nuget package?

### ISSUE THREAD

**Issue by amithegde** [OfficeDev/office-ui-fabric-react#5008]
We don't use npm for internal projects, instead we use nuget. Is there a nuget package for Fabric React (core and components)?

**Comment by dzearing** [comment]
There are no current plans to publish a Nuget package. If there is enough need, we could consider it. But given even React 16 itself is nowhere to be found there, we would have to first address that.

https://www.nuget.org/packages/react.js/
https://www.nuget.org/packages/react

**Comment by random65537** [comment]
https://reactjs.net/ is version 16.

Is there a tutorial on how to use Office-React with MVC?
