### ISSUE TITLE
How can we modify a control's CSS for eg : CommandBar

### ISSUE THREAD

**Issue by harshdamaniahd** [OfficeDev/office-ui-fabric-react#5009]
I am using CommandBar as global Navigation in SharePoint Modern Site : 
I need to customize CSS to meet branding needs
![image](https://user-images.githubusercontent.com/11780473/40586602-ff242fe8-61e1-11e8-993d-2591199605b7.png)

Now if i modify one css it affects the other CommandBar on page on page : For eg I may require to change text color, hover background color etc 
![image](https://user-images.githubusercontent.com/11780473/40586562-4f46e282-61e1-11e8-90cc-72f1b5a870fb.png)

So in this case I identified that if i directly change css it affects the other section of page , so the other
possible way is 
![image](https://user-images.githubusercontent.com/11780473/40586549-1c8f3ac4-61e1-11e8-8355-c11f69e36b5e.png)

But is this the right solution

I think CommandBar should have option to change SubMenu , MainMenu CSS which is missing ?

Is the ID generated for each CSS once for an solution ?

**Comment by JasonGore** [comment]
Now that CommandBar supports JS styling as of 6.0, you should be able to use JS styling to accomplish this. Here are a few examples:
* https://codepen.io/dzearing/pen/PeNrzB
* https://codepen.io/dzearing/pen/EpWMqp

I will close this issue for now. If you have any issues please feel free to comment or reopen. Thanks!
