### ISSUE TITLE
ContextualMenu, Callout, etc: add targetSelector

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#501]
Right now it's a royal pain to use "targetElement" to target a contextual menu at something. Instead please support "targetSelector" so we can do stuff like:

```jsx
<Button id='foo'>Hi</Button>
<ContextualMenu targetSelector='#foo' items={ ... } />
```

**Comment by joschect** [comment]
Hey,

I think I'm going to just change the targetElement property to accept types of either HTMLElement or string so that we can reduce prop clutter.

**Comment by joschect** [comment]
This has been completed.
