### ISSUE TITLE
How can I change Persona text color

### ISSUE THREAD

**Issue by AdrianM20** [OfficeDev/office-ui-fabric-react#5010]
Hello! I wanted to use the Persona component in my page header so it would be an entry point to a users profile and at the same time show the logged in person but for almost 4 days now, I;m struggling changing the Persona text color. Can anyone tell me how can I do it? I tried assigning CSS classes to the component using className but they only apply to the top level HTML Element containing the Persona and inside are over 5 elements that have their own classes. Is there any way to do it? I think the design of this component is messed up. you cannot change it's child elements at all.

![screenshot_4](https://user-images.githubusercontent.com/23298456/40589191-e4cbf544-61f1-11e8-958b-06ef7fd3638e.png)

**Comment by AdrianM20** [comment]
Thank you a lot! This really helped me :D I wish you the best of luck in further development. This UI library is extraordinary. Looking forward for all the docs :D.

**Comment by michaelangotti** [comment]
Closing since question has been answered. Thanks!
