### ISSUE TITLE
Dialog jumps abruptly when content changes dynamically

### ISSUE THREAD

**Issue by b-priyank** [OfficeDev/office-ui-fabric-react#5012]
### Bug Report

- __Package version(s)__: office-ui-fabric-react v5.111.1
- __Browser and OS versions__: any

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal) 

Products/sites affected: (visualstudio.com)

#### Describe the issue:

We've a case where we want to show some description based on the option selected in visualstudio.com. 
This description varies in size. When user clicks between options, it resizes and aligns to the center which looks abrupt and jumpy. 

#### Expected behavior:

Dialog should have top offset fixed once opened and expand from the bottom only. 

### If applicable, please provide a codepen repro:

https://codepen.io/anon/pen/GGKNdy/

**Comment by b-priyank** [comment]
@betrue-final-final : Is there any update on this issue ?

**Comment by betrue-final-final** [comment]
Thank you for the note, @b-priyank, you are correct. @lynamemi, is this something you can check out?

**Comment by lynamemi** [comment]
I briefly checked this out, and agree that it's desirable to fix this, but I don't have the bandwidth right now to come up with a solution. Probably it needs to be an 'opt-in' solution (using a prop) with some js positioning math done after first load.

**Comment by natalieethell** [comment]
It looks like we'll be able to do this by adding an optional prop to IModalProps: `topOffsetFixed` and two states to IDialogState: `hasBeenOpened` and `modalRectangleTop`. 

`hasBeenOpened` can be set in componentWillReceiveProps on a re-render after the modal has already been opened once. `modalRectangleTop` can be calculated and set in componentDidUpdate following the first render of the modal. We can store this as the original top value, which we'll use as an offset in getStyles for all of the re-rendering with different content.

In getStyles, we can set align-items to flex-start and top to `modalRectangleTop` if `topOffsetFixed` and `hasBeenOpened` are both true.

I'll send a PR out for this today!
