### ISSUE TITLE
Focus lost when item disabled in CommandBar

### ISSUE THREAD

**Issue by SumiranAgg** [OfficeDev/office-ui-fabric-react#5014]
### Bug Report
OS: Windows 10 RS3
OS version: build 16354.1001
Browser: Microsoft edge browser
Edge version: Microsoft Edge 41.16354.1001.0
Version:20180418T183508

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low) 
Normal

Products/sites affected: (if applicable)
VSTS

#### Describe the issue:

When a lost of items is passed to it which have disable/enable capability. If on click of one button (say "Save"), it gets disabled, focus is lost.

#### Actual behavior:

Focus shifts to start of page in Edge

#### Expected behavior:

Focus should shift to next active element (maybe next commanBar item.

**Comment by micahgodbolt** [comment]
once #4716 is merged, this should provide support for the 6.0 commandBar to support this feature.

**Comment by micahgodbolt** [comment]
we don't have any precedence for automatically moving focus upon user actions. This is probably best left to the application to implement via their onClick functionality.
