### ISSUE TITLE
custom panel width alignment issue

### ISSUE THREAD

**Issue by hrc7505** [OfficeDev/office-ui-fabric-react#5015]
### Bug Report

- __Package version(s)__: ^5.101.2-hotfix.1
- __Browser and OS versions__: Chrome with  66.0.3359.181 having windows 10 Pro

#### Describe the issue:
I have tried the customWidth=500px but when browser width is less then 1024px panel getting aligned to left side. this is not a nice behavior and this is happening because of following media query where `left:auto` is override by `left:48px`,

```
@media (min-width: 768px){
[dir='ltr'] .root_4ec27794.rootIsMedium_4ec27794 .main_4ec27794, [dir='ltr'] .root_4ec27794.rootIsLarge_4ec27794 .main_4ec27794, [dir='ltr'] .root_4ec27794.rootIsXLarge_4ec27794 .main_4ec27794, [dir='ltr'] .root_4ec27794.rootIsCustom_4ec27794 .main_4ec27794 {
    left: 48px;
}
```

#### Actual behavior:
![image](https://user-images.githubusercontent.com/17545364/40656012-a9385c32-6360-11e8-8429-0cf22b01934f.png)

#### Expected behavior:
![image](https://user-images.githubusercontent.com/17545364/40656097-fa43d4bc-6360-11e8-8621-027dd4fc100d.png)

**Comment by michaelangotti** [comment]
@hrc7505 Can you provide a codpen?

**Comment by hrc7505** [comment]
yes you can check this pen, [Panel with custom width](https://codepen.io/hardik-chaudhary/pen/ZRWXjL).

**Comment by hrc7505** [comment]
@michaelangotti  any progress to this issue ?

**Comment by kkjeer** [comment]
Blocked by #5823

**Comment by hrc7505** [comment]
Thank you!
