### ISSUE TITLE
Changing css display on element containing detailsview causes detailsview not to render

### ISSUE THREAD

**Issue by billytrend** [OfficeDev/office-ui-fabric-react#5019]
### Bug Report

- __Package version(s)__: 5.90.0
- __Browser and OS versions__: chrome macOs

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: (if applicable)

#### Describe the issue:

DetailView does not render content if it is in a div which had display: none and is changed to display: block. 

#### Actual behavior:

DetailView does not render content

#### Expected behavior:

DetailView shouldrender content

### If applicable, please provide a codepen repro:

press toggle display (nothing will be rendered) then resize window to force render

https://codepen.io/anon/pen/gKOjQQ

**Comment by michaelangotti** [comment]
@billytrend It would be great if you could open a PR. Let us know if you need help.

**Comment by billytrend** [comment]
@michaelangotti I opened a PR #5020 but unfortunately it relies on a feature only available in chrome right now ([https://caniuse.com/#feat=resizeobserver](https://caniuse.com/#feat=resizeobserver)). Would you suggest implementing with a check for this feature and thereby fix the bug for only chrome users? I can't think of an alternative without looking deeper into the code

**Comment by michaelangotti** [comment]
@micahgodbolt Can you chime in on this one? Should @billytrend still move forward with the fix or should we look into this issue more?

**Comment by micahgodbolt** [comment]
will forceUpdate work? 
![image](https://user-images.githubusercontent.com/1434956/40813054-d415d50e-64ed-11e8-91cd-4e2f2fb0b097.png)

**Comment by billytrend** [comment]
forceUpdate might work but it seems to be more a question of how it's triggered: it needs to be triggered when the containing div is resized not just when the window is resized.

**Comment by micahgodbolt** [comment]
Your example was when changing from display none to display block, so I assumed you were doing that via some event handler (which could also trigger the forceUpdate). Is your scenario more complicated than this?

**Comment by billytrend** [comment]
No you're right that's exactly my scenario. My work around for now is to trigger the window resize event from my event handler since it would be a pain to get a reference to the DetailsList into my event handler. It would be nice to not require direct access though.

**Comment by billytrend** [comment]
I'm also not 100% sure how compatible this hack is 

`
if (Event) {
      window.dispatchEvent(new Event("resize"));
}
`

**Comment by micahgodbolt** [comment]
with your example I noticed that after you change the width of the window the hide/show button works fine. Could you allow the component to mount before you hide it?
