### ISSUE TITLE
Enable localization support for File Picker

### ISSUE THREAD

**Issue by samyaktelsang** [OfficeDev/office-ui-fabric-react#5029]
In lieu of an effort to improve globalization/localization of the products that we build, 0365 and SharePoint enable us to localize our files and custom fields. 

However, while using a FilePicker class, there isn't an option to provide the button's display name. It resorts to a default text such as "Choose File" in Chrome or "Upload" on Edge. 
I find that this makes it hard for developers to localize text based on the users AAD context or O365 language preference settings.
If we were allowed to set the button's display name/text ourselves, then it would enable us to localize the strings in a definition file as we have standardized across our project.
Are there any plans of ensuring we can select the text that shows up on the button while using a FilePicker component ourselves? If not, could we please ensure that we can in an effort to improve globalization/localization of the products/solutions that we build.

**Comment by KevinTCoughlin** [comment]
@samiyaakhtar we hope to support this soon and are tracking this. We understand this is a frustrating limitation of the current picker. Stay tuned.

**Comment by KevinTCoughlin** [comment]
Closing this issue as it is tracked in https://github.com/OneDrive/onedrive-api-docs/issues/905 and unrelated to `office-ui-fabric-react`.
