### ISSUE TITLE
DirectionalHint: should have near/far values, ContextualMenu default should be bottomNearEdge

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#503]
It is a burden to have every scenario check RTL flags to do the right thing, so we should have near/far values rather than left/right.

Also, ContextualMenu defaults to `rightCenterEdge` which is totally wrong and should default to `bottomNearEdge` or `bottomAutoEdge`.

**Comment by dzearing** [comment]
1. DirectionalHint would be modified to deprecate all things that say left/right.
2. We would add `start` and `end` replacements for those.
3. Modify all code which uses directionalhint to refer to start/end.

**Comment by dzearing** [comment]
Per discussions, we'll close this for now until needed.

**Comment by benkaiser** [comment]
For reference here, there's been an ask for this from @antonlabunets
