### ISSUE TITLE
Is there a timeframe for Forms to graduate from experiments?

### ISSUE THREAD

**Issue by tavish-fostermoore** [OfficeDev/office-ui-fabric-react#5041]
Hi,

Happy fabric user here! We're stoked with how easy it is to use fabric for our new-build app for a government client.

As a new project, we've been fumbling around a bit for the best way to handle forms. The current approach we're using doesn't seem to work that well. We noticed the fabric forms "experiment": https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/experiments/src/components/Form

We'd love if there was a recommended and/or supported way of implementing forms with fabric, and we're wondering if/when the forms experiment might graduate to production ready? We'd certainly be keen to give feedback and contribute anything we might come up with.

Thanks!

**Comment by michaelangotti** [comment]
@tavish-fostermoore We're happy to hear you're stoked with Fabric. Tagging @dzearing who might be able to answer your question and look into this crystal ball on the future of Forms.

**Comment by dzearing** [comment]
This actually goes for all of our experiments. I'm going to assign to micah at the moment, but I believe our plan will be to separate out a form components package so that i can be independently released.

**Comment by micahgodbolt** [comment]
@abettadapur How stable would you consider this component right now? Are you still making API changes or would this be ready for a major release (knowing that any breaking changes would have to wait until a major release of Fabric)

**Comment by abettadapur** [comment]
I am not making any breaking changes right now.
The only thing I would want to do it have this use the new context API, but that is an implementation detail.

I would be glad to see this promoted :)

**Comment by micahgodbolt** [comment]
Okay, last things we'll want to clarify is packaging: is this an atomic pieces that should be in Fabric package or as David mentioned, should it go in its own package? Also, would other components possibly join it in another package.

Secondly, who is going to be responsible for the bugs and feature requests made towards this component? Is this component something that your team relies highly upon and are willing to continue to support?

Right now we're trying to have that bug/feature work funded by the team that is contributing the code (i.e. if you hadn't shared it, and it was sitting in your own repo, you'd own those bugs).

**Comment by micahgodbolt** [comment]
For the time being, Forms is going to stay in experiments. We have some more ambitious goals for forms and feel that graduating this into Fabric will make those goals more difficult. You are free to continue to use the one in experiments or fork this code and keep a copy for yourself. We won't be doing any further work on this version of the Forms component.

**Comment by micahgodbolt** [comment]
The progress of the new form component can be tacked here

https://github.com/OfficeDev/office-ui-fabric-react/issues/5582
