### ISSUE TITLE
Complete rectangle focus not visible in panel content.

### ISSUE THREAD

**Issue by SumiranAgg** [OfficeDev/office-ui-fabric-react#5043]
### Bug Report

OS: Windows 10 RS3
OS version: build 16299.371
Browser: Firefox
Firefox version: 59.0.2 (32-bit)
Version:20180413T115929

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low) 
Normal

Products/sites affected: (if applicable)
VSTS

#### Describe the issue:

Component name: Panel
Complete focus rectangle not visible on panel content. See screenshot below:
![image](https://user-images.githubusercontent.com/8316321/40775048-c326df8a-64e4-11e8-937e-e924abe06d3e.png)

#### Actual behavior:

Complete rectangle focus is not visible.

#### Expected behavior:

Either complete rectangle should be visible or content should not be focused at all. Later can be accomplished by adding "tabIndex=-1" to "ms-Panel-content" class.

**Comment by micahgodbolt** [comment]
@SumiranAgg is it possible to get a codepen version of this? The typical panel has padding around the edges, so a full width button still has focus rect visible. You might just need to leave room for your own rectangle if you removed that padding.

![image](https://user-images.githubusercontent.com/1434956/50492352-f5e5cd00-09cb-11e9-89c7-0f4a923d32c2.png)
