### ISSUE TITLE
Page automatically reloading when clicked on context menu in command Bar

### ISSUE THREAD

**Issue by vamsi981** [OfficeDev/office-ui-fabric-react#5045]
#### Priorities and help requested (not applicable if asking question):
Requested priority: (High) 

Products/sites affected: (if applicable)
**office365**

#### Describe the issue:
We have build a custom Application and using fabric Command bar in the classic page when we click on new dropdown the page Automatically redirecting, due to button type is not defined and in classic pages form automatically reloading when the dropdown is clicked.

#### Actual behavior:
Context Menu in Command Bar should open without page reload.

**Comment by michaelangotti** [comment]
@vamsi981 Are you able to provide us with a Codepen or Repro so we can investigate further? Also, please let us know what Fabric version and browser you are using. Thanks!

**Comment by micahgodbolt** [comment]
command bar doesn't do anything special regarding routing. you need to handle any onClick or href click yourself.
