### ISSUE TITLE
Property 'isSearchBoxVisible' does not exist on type 'IntrinsicAttributes & ICommandBarProps'.

### ISSUE THREAD

**Issue by Perneel** [OfficeDev/office-ui-fabric-react#5046]
### Bug Report

- __Package version(s)__: 6.1.2

#### Describe the issue:

Properties missing from ICommandBarProps

````
<CommandBar
     isSearchBoxVisible={false}
     searchPlaceholderText="Search..."
     elipisisAriaLabel="More options"
     items={[]}
     farItems={items}
/>
````

#### Actual behavior:

react\containers\ActionBar\ActionBar.tsx(161,25): error TS2339: Property 'isSearchBoxVisible' does not exist on type 'IntrinsicAttributes & ICommandBarProps'.

`isSearchBoxVisible, searchPlaceholderText, elipisisAriaLabel` are not defined in CommandBar.types.d.ts

#### Expected behavior:

Properties are known as described on https://developer.microsoft.com/en-us/fabric#/components/commandbar

**Comment by Perneel** [comment]
Ok, after going through the release notes, version >6 has CommandBar revamped. Is there any information/examples on how to use it now?

**Comment by micahgodbolt** [comment]
There's a little styling work to do, but this is how to render something in command bar https://codepen.io/micahgodbolt/pen/JZZYwE
