### ISSUE TITLE
Nav - Expand arrow is unlabeled

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#5047]
Repro:

1. Use Narrator
Go to the Nav component page
Tab to the component

Result: Button is unlabeled and just says "Button expanded"
Expect: Should say "Expand or collapse <item name>, <state>"

Existing VSTS bug: 1759152. Link to follow.

**Comment by natalieethell** [comment]
Nav currently does have an optional `expandButtonAriaLabel` prop that can be used to fix this. 

As for setting a default string in Fabric:

In June, we had a brief discussion about a common localization model and how we could all benefit from it. As @aditima has mentioned, right now, if we just put en-us default strings in our code, we're creating mandatory work for our partners who, if they do nothing, end up shipping en-us strings on all locales. 

So, depending on if we've starting to work on plans for this localization effort we can either put in the default en-us string, or stick to just having the optional aria label prop for the expand button for now (we can still fix the demo page on our website).

@dzearing @micahgodbolt what is the best thing to do in the interim? And @iclanton I remember Aditi mentioning you would be involved with this, do you have any scheduled work for this effort yet?
