### ISSUE TITLE
Hover card first focus is auto set

### ISSUE THREAD

**Issue by chaofeng2014** [OfficeDev/office-ui-fabric-react#5049]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) 

Products/sites affected: (if applicable)

#### Describe the issue:

When hover card is opened by hover behavior, the first focus is set, this is not expected, only when hover card is opened by hotkey, the first focus should be set. If you want to customize the behavior, you should add a property and pass a value.

#### Actual behavior:

When hover card is opened by hover behavior, the first focus is set.

#### Expected behavior:

When hover card is opened by hover behavior, focus should not be changed.

**Comment by michaelangotti** [comment]
@micahgodbolt Do we want to support this feature?

**Comment by micahgodbolt** [comment]
this sounds reasonable. We should consult with design on preferred default behavior, and allow a prop to override/optout of that behavior.

**Comment by micahgodbolt** [comment]
this is now fixed. you can now opt in to setInitialFocus
