### ISSUE TITLE
ComboBox dropdown doesn't float to top when there is not enough space below it

### ISSUE THREAD

**Issue by vivianhoang** [OfficeDev/office-ui-fabric-react#5054]
### Bug Report

- __Package version(s)__: 5.106.1
- __Microsoft Alias__: vihoang

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Low

Products/sites affected: (if applicable)

#### Describe the issue:
My team is currently using the ComboBox component - it has almost 100 options to select from and it's difficult scrolling through each item:

![image](https://user-images.githubusercontent.com/20330957/40816475-0e3b5b5a-6502-11e8-9eba-b80973c59c6d.png)

**This is very similar to this open issue (and a few other ones) with the Dropdown component, so I'm guessing this might be the same issue:** https://github.com/OfficeDev/office-ui-fabric-react/issues/3719

#### Actual behavior:

The dropdown doesn't drop "up" when the dropdown is at the bottom of the page, so there it's almost impossible to click on values. The list is unusable when the dropdown doesn't have any space left to render.
#### Expected behavior:
The dropdown will drop "up" when there isn't enough space.

#### If applicable, please provide a codepen repro:

"Just open the Office Fabric React **ComboBox** Samplepage and resize the browser so that there is a little gap between the control and your browser chrome. Then click the dropdown."

![image](https://user-images.githubusercontent.com/20330957/40816376-6a89331a-6501-11e8-93fe-d1e9f0065ea4.png)

**Comment by micahgodbolt** [comment]
Added to vsts backlog...thanks for pointing this out!

**Comment by JllyGrnGiant** [comment]
I don't believe this should be the permanent answer for folks, but as a temporary workaround I was able to restore the correct behavior by adding the following to my combobox props:
```
calloutProps: {
    directionalHintFixed: false // Allows the dropdown to render above the text box when there is too little room to render the options well
}
```
