### ISSUE TITLE
when i am implementing office ui fabric react people picker the suggestions are coming on the top left corner?

### ISSUE THREAD

**Issue by prabhat9999** [OfficeDev/office-ui-fabric-react#5071]
![40847204-0552153c-65bc-11e8-8888-2e0e804b537b](https://user-images.githubusercontent.com/36052078/40887204-41b093e8-6745-11e8-917f-5bf845d772e2.png)

**Comment by Markionium** [comment]
This looks like a bug.

Could you share a minimal repro that you have already or create one using codepen? 

You could fork this codepen template to get started https://codepen.io/mpolak/pen/PebaGo

**Comment by dzearing** [comment]
@joschect as any FYI.

@prabhat9999 please try and get it reproing in a codepen.

**Comment by JasonGore** [comment]
I will close this for now for lack of response. If you are still having issues please feel free to reopen (ideally with CodePen repro.) Thanks!
