### ISSUE TITLE
multi-line Textfield show redundant empty bottom space on IE 11.

### ISSUE THREAD

**Issue by hxltinh** [OfficeDev/office-ui-fabric-react#5075]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: Window - IE11

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes)

Requested priority: (Normal) 

#### Describe the issue:

redundant empty bottom space appear on IE11

#### Actual behavior:

It shows empty bottom space on IE11 (seem like it happens when width of the text-area is below 132px)

#### Expected behavior:

It should not show empty bottom space on IE11

![capture png](https://user-images.githubusercontent.com/8114730/40909067-dadf1db4-6812-11e8-9cf2-a04869b1203d.png)

**Comment by micahgodbolt** [comment]
seems this is fixed. looks the same in IE11 and Firefox now 

![image](https://user-images.githubusercontent.com/1434956/45278360-934edc80-b481-11e8-9108-24b4028ccfb3.png)

**Comment by hxltinh** [comment]
@micahgodbolt Great work, thanks
