### ISSUE TITLE
DragDropHelper: minimum pixel and manual events issues

### ISSUE THREAD

**Issue by laxmikankanala** [OfficeDev/office-ui-fabric-react#5077]
Issues in DragDropHelper:
1. Current logic of minimum pixel to start the drag is not working if we set it to a high value, as the browser start the drag events regardless of this check. And once drag events start coming, we will not be getting any mouse move events from browser.
2. Currently, in mousemove event we start the drag(call to onDragStart), but in few cases browser start the drag event without any mouse move events. In such cases we never get to call the dragstart
3. Manual raising of the drag events(Ex:DragEnter after starting the drag in mousemove), is resulting the inconsistent _dragEnterCounts.

Repro steps:
In the dragdrop example of DetailsList page, mousedown on any row and move just for a pixel, wait for 2,3 secs, and try to drag and drop at a new index. It looks like the drag is happening, but after dropping nothing changes in the items order.
May need to repeat it few times to repro the issue.

**Comment by michaelangotti** [comment]
I can't repro in Edge or IE (both work as expected), but Chrome does repro the issue noted above.

**Comment by aditima** [comment]
@ThomasMichon - could you please look at this?
