### ISSUE TITLE
Grid system for react is missing in the new documentation!

### ISSUE THREAD

**Issue by MobileAppVault** [OfficeDev/office-ui-fabric-react#5081]
Hi,

you forgot to add sample code about the grid system and how to use it with react in your new documentation. 

Could you please add this information to the documentation?

Many Thanks!
Marcus

**Comment by dzearing** [comment]
The `Grid` component is missing in Fabric. We want to add this. We are also adding `Stack`. @kkjeer will be helping to drive these efforts.

**Comment by MobileAppVault** [comment]
Ok thanks! Will be very helpful to have at least the grid component as soon as possible in the component library. Want to avoid that we have to redesign a lot of components in future.

**Comment by dzearing** [comment]
Tracking in #5418, closing this issue.

Stack (abstraction on flexbox) is coming shortly. It's already in experiments, closing down on last few items.
