### ISSUE TITLE
TagPicker: onResolveSuggestions re-rendered after selecting item in IE11

### ISSUE THREAD

**Issue by qazqwertish** [OfficeDev/office-ui-fabric-react#5082]
### Bug Report

- Package version(s): ^5.76.0 (Tested also with 6.3.0)
- Browser and OS versions: Internet Explorer 11

**Describe the issue:**

We selecting an option from the suggestions picker it executes again the method "onResolveSuggestions" and it makes the suggestions appear again.

Can be checked here: [https://codepen.io/qazqwertish/pen/BVjeVB](https://codepen.io/qazqwertish/pen/BVjeVB)

**Comment by micahgodbolt** [comment]
i don't see any behavior difference between FF and IE11. Here's an updated codepen with newest fabric/React. 

https://s.codepen.io/micahgodbolt/debug/ZVJmqo/LDAmdPqxdGDr
