### ISSUE TITLE
Grouped DetailsList has unexpected scrolling bevaviour when virtualized

### ISSUE THREAD

**Issue by elliottsj** [OfficeDev/office-ui-fabric-react#5094]
### Bug Report

- __Package version(s)__: office-ui-fabric-react@6.4.0
- __Browser and OS versions__: Chrome 67 on macOS
- __Microsoft Alias__: spelliot

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: OneDrive web

#### Describe the issue:

When rendering many (hundreds) of items in a grouped DetailsList, scrolling does not behave as expected. Upon scrolling quickly to a point mid-list, the list will often get into a state where items are rendering and re-rendering on an infinite loop. At the same time, the list height is continually readjusting, which causes the scroll bar to jump between positions:

![kapture 2018-06-04 at 16 26 37](https://user-images.githubusercontent.com/2177366/40946746-17775aec-6814-11e8-8a0d-5a6e48142031.gif)

#### Actual behavior:

As described above.

#### Expected behavior:

The list renders normally.

### If applicable, please provide a codepen repro:

[![Edit pj0l36v81m](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pj0l36v81m)

**Comment by michaelangotti** [comment]
@elliottsj Thanks for bringing this to our attention. I also tested in IE and Edge and, while it doesn't go into a re-render loop in those, the scroll bar does perform erratically.

**Comment by elliottsj** [comment]
I'm going to start working on a fix for this today

**Comment by elliottsj** [comment]
After some investigation, my understanding is that this bug is due to the way the virtualized List component works at a fundamental level.

At a high level, List works by first rendering its items, then once they're rendered to the DOM, it measures the actual heights of its children within the viewport and _re-renders_ as necessary until all of the items which can fill the viewport are materialized.

GroupedList is essentially a List with nested Lists as items. We have the scroll jumping issue because, at the time the outer List decides to measure the height of its child items, the nested Lists have not yet rendered _their own items_ to the DOM.

So we end up stuck in a strange state where the inner List is initially empty, so the outer List readjusts its page heights to account for the small height of the empty inner List. This causes subsequent inner Lists to render as they're brought into view, which repeats the above steps.

**Comment by elliottsj** [comment]
I have a fix over at #5204. It's not a complete fix since it requires that users pass in a `getGroupHeight` prop, but it at least prevents this issue in cases where group heights can be calculated based on the `IGroup`.
