### ISSUE TITLE
Breadcrumb: Focus rect is wrong

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#510]
When you click on an item in breadcrumb, it shows a focus rectangle, when it should only be doing this if the keyboard is pressed (it is not using the mixin)

![image](https://cloud.githubusercontent.com/assets/1110944/20089173/ec502b80-a539-11e6-85f2-f17dfeee594f.png)

If you arrow left/right, it shows a weird fat 2px focus rectangle:

![image](https://cloud.githubusercontent.com/assets/1110944/20089192/0ba96848-a53a-11e6-85c7-26e45cc4ef48.png)

**Comment by ericthompson** [comment]
Waaaayyyy too big!

**Comment by leddie24** [comment]
Fixed in #860, removed outline from ms-Breadcrumb-itemLink's focus state
