### ISSUE TITLE
[bug] - Pivot onLinkClick

### ISSUE THREAD

**Issue by PascalSenn** [OfficeDev/office-ui-fabric-react#5101]
### Bug Report

- __Package version(s)__:  5.107.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

#### Describe the issue:

onLinkClick is not triggered.  

I guess it's caused by react-hot-loader, but I'm not sure. It could also be caused by an extension.

Anyway, the problem is this comparison
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Pivot/Pivot.base.tsx#L285

Compare

![image](https://user-images.githubusercontent.com/14233220/40975356-f69df800-68ca-11e8-92f0-00b45fd1efb9.png)
To
![image](https://user-images.githubusercontent.com/14233220/40975695-08416e88-68cc-11e8-9945-548eb8fc5fcb.png)
Results in 
![image](https://user-images.githubusercontent.com/14233220/40975707-15201f46-68cc-11e8-8f89-b5d06f8a31ec.png)

The reason the comparison is false is caused by a Proxy Component:
![image](https://user-images.githubusercontent.com/14233220/40975762-48f2f960-68cc-11e8-8e03-c4c3ddf55a80.png)

For me it's anyway a bad idea to compare types like this in Javascript. 
It  probably makes more sense to compare the names of the types.

Fix is on the way.

#### Actual behavior:

`onLinkClick` is not triggered

#### Expected behavior:

`onLinkClick` is triggered

**Comment by aditima** [comment]
Thanks for the PR @PascalSenn.

**Comment by PascalSenn** [comment]
My pleasure. 
The build is somehow failing though.
