### ISSUE TITLE
Breadcrumb: if an item doesn't have an onClick it still looks clickable.

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#511]
We should be rendering non-clickable entities as non-clickable. Instead it has a hover state and cursor treatment.

**Comment by dzearing** [comment]
I think non clickable things should render as divs/spans or whatnot, rather than buttons. Clickable things should be buttons.

**Comment by ericthompson** [comment]
Could we get a screenshot?

**Comment by dzearing** [comment]
Just try it. Here's a bunch of breadcrumbs that don't have onClicks.

http://codepen.io/dzearing/pen/QGNLVZ?editors=0010
