### ISSUE TITLE
onRenderText methods in Persona doesn't provide/honor a defaultRender function passed in parameters

### ISSUE THREAD

**Issue by pKalaga** [OfficeDev/office-ui-fabric-react#5111]
### Bug Report

- __Package version(s)__: current
- __Browser and OS versions__: All

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: SharePoint Sites and Lists

#### Describe the issue:

onRenderPrimaryText / onRenderSecondaryText in Persona are of IRenderFunction Type but donot honor the contract / pass through the defaultRender parameter. 
Due to this there could be styling mismatches if one wants to just wrap the text with another div or decorate the text with an icon.

**Comment by natalieethell** [comment]
Hey @pKalaga would you still be up for submitting a PR to fix this issue?

**Comment by shagra-ms** [comment]
Changes were taken up by [Swapnil Vaibhav](https://github.com/s-vaibhav) and were [merged](https://github.com/OfficeDev/office-ui-fabric-react/pull/5870) on August 13.

**Comment by natalieethell** [comment]
That's great, thanks for the update @shagra-ms! I'll close out this issue.
