### ISSUE TITLE
ScrollablePane with DetailsList cannot scroll fixed header with list content

### ISSUE THREAD

**Issue by luckyyd** [OfficeDev/office-ui-fabric-react#5116]
### Bug Report

- __Package version(s)__: 5.106
- __Browser and OS versions__: Chrome, Windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No
Requested priority: (Blocking, High, Normal, Low) 
High
Products/sites affected: (if applicable)

#### Describe the issue:

When using DetailsList within Scrollable Pane, if the DetailsList has more columns that exceeds the div width, when scroll below, both column header and detailslist appears both horizontal scroll bar, but cannot scroll together:
Scroll to the top:
![image](https://user-images.githubusercontent.com/12855573/41050748-dfcc0c1c-69e6-11e8-9c2b-9eacd56d01f7.png)
Scroll down
![image](https://user-images.githubusercontent.com/12855573/41050696-b9aff1ce-69e6-11e8-9b18-621c3bf6cbc3.png)

#### Expected behavior:

The sticky header should scroll with detailslist together.

### If applicable, please provide a codepen repro:

Code:
![image](https://user-images.githubusercontent.com/12855573/41051357-7cde093c-69e8-11e8-8d4b-9042d13eda39.png)

**Comment by kirankumarmanku** [comment]
Hi, 
I am also facing the similar issue with DetailsList with ScrollablePane. Is there any temporary workaround for this?

**Comment by kirankumarmanku** [comment]
Hi, 
Following fix worked for me. I have added onScroll event for the div containing ScrollablePane and attached the following method. 

  ```
private handleScroll(event) {
    let element = document.querySelector("[class*='stickyAbove-']");
    if(element != null)
        element.scrollLeft = event.target.scrollLeft;
  }

```

I am returning following element. 
```

     <div style={ {
          height: '100%',
          position: 'relative',
          maxHeight: 'inherit'
        } }
          onScroll = {this.handleScroll}
         >
              <ScrollablePane>
                <DetailsList
                  items={ sortedItems as any[] }
                  columns={ columns }
                  compact={false}
                  ariaLabel= "List of data"
                  setKey='items'
                  className = {styles.myclass}
                  layoutMode={ DetailsListLayoutMode.fixedColumns }
                  onRenderDetailsHeader={
                    // tslint:disable-next-line:jsx-no-lambda
                    (detailsHeaderProps: IDetailsHeaderProps, defaultRender: IRenderFunction<IDetailsHeaderProps>) => (
                      <Sticky 
                      stickyPosition={StickyPositionType.Header} >
                        { defaultRender({
                          ...detailsHeaderProps,
                           onRenderColumnHeaderTooltip: (tooltipHostProps: ITooltipHostProps) => <TooltipHost {...tooltipHostProps} />
                        }) }
                      </Sticky>
                    ) }
                  selectionMode={SelectionMode.none}
                  constrainMode = {ConstrainMode.unconstrained}
                  onColumnHeaderClick={ this.onColumnClick }
                />
              </ScrollablePane>
         </div>
```

**Comment by coreyroth** [comment]
I have found that you also need to capture the scroll event on the Sticky as well in case the user scrolls the header.  I registered a scroll event with the following:

`public componentDidMount(): void {
    let stickyElemrent = document.querySelector("[class*='stickyAbove-']")
    if (stickyElemrent != null) {
      stickyElemrent.addEventListener('scroll', this.hnadleStickyScroll);
    }
  }`

Then I used a similar event handling method:

`private hnadleStickyScroll(event) {
    let gridElement = document.querySelector("[class*='ms-DetailsList']");
    if (gridElement)
      gridElement.scrollLeft = event.target.scrollLeft;
    event.preventDefault();
  }`

I wrote more on it in this [post](http://www.dotnetmafia.com/blogs/dotnettipoftheday/archive/2018/10/03/fixing-horizontal-scrolling-in-your-detailslist-using-scrollablepane-and-sticky.aspx).

**Comment by nealYangVic** [comment]
StickyPositionType.Both will make it work directly....
