### ISSUE TITLE
Breadcrumb: Hover states don't match OneDrive

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#512]
Hover state:
![image](https://cloud.githubusercontent.com/assets/1110944/20089273/8ce9a116-a53a-11e6-954c-4ce26552b169.png)

OneDrive hover:
![image](https://cloud.githubusercontent.com/assets/1110944/20089286/9fd6beda-a53a-11e6-81bf-5b55109c2a37.png)

**Comment by ericthompson** [comment]
Yep - this isn't right. Looking into it.
