### ISSUE TITLE
New React Context API vs Panel

### ISSUE THREAD

**Issue by trsvax** [OfficeDev/office-ui-fabric-react#5123]
I created a Help component that provides context to Guide components that allows guided help in an application. The Help component provides an isHelping context to let the Guide components know when to turn on and off. I used the new React 16.3 context api to do this and it works fine except there is no context inside the Panel component. For example

<Help>
<Guide><button/>/Guide> works
<Panel>
<Guide><button/>/Guide> context is undefined
</Panel>
</Help>

Looking at the debugger it appears Panel creates a CustomizedFabric that is outside the hierarchy and I'm guessing this is causing the problem. If I use the old unsupported context api everything works. Ideally the new api would be compatible with the old but from what I can tell this is not the case. I don't think this is a bug per say but an unfortunate combination of features. The question is what's the right set of features to make this work?

**Comment by cobbs-totem** [comment]
Identical to the issue I opened and it was being addressed post 6.0:

https://github.com/OfficeDev/office-ui-fabric-react/issues/4911#issuecomment-391802328

**Comment by dzearing** [comment]
Reopening the #4911 issue to track, assigned to a dev, we will fix.
