### ISSUE TITLE
Nav: selection state can't be controlled by the consumer

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#513]
The Nav control has no way to control selection state from the consumer's perspective. All of the hash change logic in the Nav should either be removed or overrideable.

Take this codepen example:
http://codepen.io/dzearing/pen/ZBGNQg

Click on an item. Then click another. Then another. Notice selection state is changing. Why? I don't know. I didn't change anything.

We should allow the consumer to specify something like `ILinkProps` takes `onIsSelected` method, or the whole `Nav` does, or both.

**Comment by dzearing** [comment]
@cmalonzo fyi

**Comment by aleksandrjPersonal** [comment]
This may need additional clarification before starting. Repro steps, expected vs. actual behavior, etc.

"Click on an item. Then click another. Then another. Notice selection state is changing. Why? I don't know. I didn't change anything." < This line is particularly confusing as clicking on a nav item it would not be unexpected expected to change state.

**Comment by dzearing** [comment]
This is now resolved.
