### ISSUE TITLE
Applying new css rules in overflow set

### ISSUE THREAD

**Issue by v-kanuli** [OfficeDev/office-ui-fabric-react#5132]
I want to apply custom css for the overflow set ellipse icon that is provided by the overflow set. How can I accomplish this?

**Comment by micahgodbolt** [comment]
if you are running an older version of Fabric, you can always target ms-OverflowSet-overflowButton 
![image](https://user-images.githubusercontent.com/1434956/41430375-ae971be4-6fc4-11e8-991e-2bf7b2cee5a5.png)

In the most recent versions of Fabric (6.x) you can target it via the styles prop.

<OverflowSet styles={{overflowButton: {background: 'green'}}} />

**Comment by j-te** [comment]
How can we neatly apply a className to an instance of overflowButton? CSS style required due to use of :fullscreen

**Comment by micahgodbolt** [comment]
There's actually a bug that I just ran across that keeps that from working

https://github.com/OfficeDev/office-ui-fabric-react/issues/8441

**Comment by micahgodbolt** [comment]
Seems this fixes the issue https://codepen.io/micahgodbolt/pen/MxZZoe?editors=1010
