### ISSUE TITLE
ContextualMenu: No way to make icons colored.

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#514]
Expected: 
`iconProps` on `IContextualMenuItem`

Resulted:
no way to colorize icons without onRender

**Comment by serkan-inci** [comment]
It would also be great if making coloring was optional. We have our own icons where some of them specify their own colors using css. However, this styles are overridden by the blue color specified by ```ms-ContextualMenu-icon```.

**Comment by dzearing** [comment]
Turns out that this is doable:

http://codepen.io/dzearing/pen/WovrbX

However it's fragile and I don't think I'd recommend this as the recommended pattern.

You can add classNames to individual items and target the icon like so:

```css
.shareItem .ms-Icon {
  color: red;
}
```

**Comment by serkan-inci** [comment]
Your suggestion wouldn't work for us because we already have a lot of icons defined like:

    .icon-add { color: green; }
    .icon-delete, .icon-cancel { color: red; }
    ...

I can add !important to all of them but this is not what I want to do. Anyway, I'll think more to see what can be done here.

**Comment by dzearing** [comment]
I see, yes you really want `iconProps` like i suggested above. It's not hard to add! Feel free to make a PR if you want it in relatively soon. We can get it published same day.

**Comment by joschect** [comment]
Hey, I've started on a PR already, will you need anything otherthan style for the icon? It seems like most of the other props would be unnecessary for now.

**Comment by dzearing** [comment]
I think it would make sense if you're adding an `Icon` component, which uses `IIconProps`, then we just let you pass that through here. That would ensure that if we add other icon props in the future it extends here.

**Comment by dzearing** [comment]
This is now published in 0.70.0. You can now pass in iconProps in contextualmenuitems. Thanks @joschect !

**Comment by joschect** [comment]
@serkan-inci Hey! quick note too, since icon is now deprecated, you should use iconName in IconProps to specify which icon you want to use. Definitely let me know if you run into any issues!

**Comment by serkan-inci** [comment]
@dzearing @joschect 

This is a nice improvement but still doesn't solve our issue because ContextualMenu still dictates the blue color for the icons. We have a lot of icons where we display custom color for them through css which are global css entries.

I came up with something in my mind which may probably solve this issue. Please let me know if that does not make any sense.

Here is the commit: https://github.com/serkan-inci/office-ui-fabric-react/commit/0bddb9a80b42a9a06c9abe1622b7e19f1f36d337

With this change, i can specify:

    { iconName: 'None', className: 'my-icon' }

Thanks
