### ISSUE TITLE
Pivot -> PivotItem editing of content seems to be caching

### ISSUE THREAD

**Issue by arunkumarperumal** [OfficeDev/office-ui-fabric-react#5144]
### Bug Report

- __Package version(s)__: 5.103.0
- __Browser and OS versions__: Chrome, Windows
Other Details : SPFx React WebPart
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Blocking

Products/sites affected: (if applicable)

#### Describe the issue:

We are using tinymce editor for enabling editing of contents within the PivotItem. Using properties to share the information. On Change of the editor we are storing the content in the editor to the properties.

But when we navigate between tabs(PivotItems) on clicking of the tabs content is reverted back to the previous state before the content editing. 

#### Actual behavior:

Content passed to the pivot item seems to be persisted and on refresh of the page the contents are shown.

#### Expected behavior:

On click of Tabs(PivotItems) while editing the content should reflect the latest changes.

**Comment by micahgodbolt** [comment]
We don't specifically support TinyMCE in our components, but if you've found a reproducable bug, we'd be happy to take a look at it. Are you able to repro the bug without TinyMCE? 

Here's a Codepen Template you can use to repro. https://codepen.io/FabricReact/pen/NvBvWx
