### ISSUE TITLE
People picker unable to select multiple persons without leaving

### ISSUE THREAD

**Issue by nguyentoantuit** [OfficeDev/office-ui-fabric-react#5145]
Hi all,

It is not possible to select multiple person without leaving the field first (click outside of field).
Do you have any idea or workaround solution for this issue?

Thank in advance,
Toan

**Comment by nguyentoantuit** [comment]
I have check the source code in BasePicker.tsx and realize that onSuggestionClick we force close suggestion list:
`  @autobind
  protected onSuggestionClick(ev: React.MouseEvent<HTMLElement>, item: any, index: number) {
    this.addItemByIndex(index);
    this.setState({ suggestionsVisible: false });
  }`
Can we provide a prop to keep the suggestion list still open when an item is selected?

**Comment by michaelangotti** [comment]
@betrue-final-final Can you advise if this is something we want to add?

**Comment by joschect** [comment]
@nguyentoantuit Do you mean that you want to allow for multiple selections while suggestions is open? I just want to make sure that there isn't a bug that prevents you from selecting more than one person in general in the picker.

**Comment by nguyentoantuit** [comment]
@joschect I mean that the suggestions is only closed if click to next elements or another area. Currently, the suggestion list is closed immediately when I select a person. If I want to select multiple persons I need to follow these steps:
1. Click on people picker
2. Suggestion list is opened, select a person
3. Suggestion list is closed immediately, the focus is still in people picker 
4. To make the suggestion open again we need to
   4.1. Either type some text, the suggestions will be shown again. But you have to type correct name at least of a person if not the suggestions will show nothing (No results found).  In other words, I need to remember the name of users
![image](https://user-images.githubusercontent.com/6096518/41449151-8bef9a38-7089-11e8-99d5-81aea94ee80d.png)
   4. 2. Or lose focus on people picker component by click to another field, or other areas, and then click back on people picker to show suggestion list again.

It is quite annoying to make suggestion list show up again.

**Comment by betrue-final-final** [comment]
The current behavior is consistent with other people picking controls such as in Outlook. 

What you're suggesting is a new feature more like the experience when you click the "To" button in Outlook. 

The people picker is meant to be a lighter experience in the midst of complex UX.
