### ISSUE TITLE
[bug] - Textfield not empty if value undefined

### ISSUE THREAD

**Issue by PascalSenn** [OfficeDev/office-ui-fabric-react#5146]
### Bug Report
Package version(s): 5.107.0
### Priorities and help requested (not applicable if asking question):
Requested priority: Normal

#### Describe the issue:
render gets not triggered when value changes to undefined

https://github.com/OfficeDev/office-ui-fabric-react/blob/3ccea373457639519f55d9762c862d44ae4da36c/packages/office-ui-fabric-react/src/components/TextField/TextField.tsx#L125

#### Actual behavior:

Textfield does not reset

#### Expected behavior:

Textfield should be empty

### If applicable, please provide a codepen repro:

https://codepen.io/anon/pen/KeNrgP

**Comment by PascalSenn** [comment]
i guess on null and undefined textfield reset should be triggered

**Comment by natalieethell** [comment]
While debugging, it seems that neither `onChange` nor `onInput` is triggered when TextField's value is changed to undefined, which is what would call `_onInputChange` and as a result, set the state. I'll investigate these events a little more and see if there's a good workaround for this.
