### ISSUE TITLE
DetailsList focusToIndex scroll is even happening if the focusable Index is in viewport

### ISSUE THREAD

**Issue by anushkumarkorukonda** [OfficeDev/office-ui-fabric-react#5153]
### Bug Report

- __Package version(s)__: 5.111.2
- __Browser and OS versions__: Chrome/FireFox

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low)  High (A kind of Blocker)

Products/sites affected: (if applicable)

#### Describe the issue:

 I am having a details list with some rows and having show more functionality. Each row is having a button for example in real time scenario (Pin Your document). So if I click on that button that document will be moved out and the list will be refreshed. So in this scenario I want the focus to be on the current row or the before row(if I pin the document in last row and I am not having any more items). In this scenario I am having the index where to move the focus. I am sending that index to focusIndex method. Here the index what I need to focus will always appear in the view port. After the pin click action is triggered, I am setting the focus and refreshing the list. In case of lower resolution or if I am at the bottom of the screen(If I am having some data at top of the page) since this focusIndex method is also having scroll by default I am getting a kind of scroll behavior from top to bottom for fraction of second after using this focusIndex method. That's why I am asking whether there is anyway to only focus on a particular row with out scroll

I tried even after moving focus logic to componentDidUpdate so that I can update the the detailslist once after refreshing the list is done with new items (The items which are hidden can be added to the list since it is having show more functionality). I am still having the same kind of jump behavior.

I have debugged the code and found one statement which is triggering this scroll to top of the page. Inside List.prototype.scrollToIndex there is a for loop which is having scroll logic. There is a logic in if condition for measureItem. If measureItem is not defined immediately after this if condition there is a statement this._scrollElement.scrollTop = scrollTop; which is triggering this scroll to top of the page (In scrollElement the top level element div of the page is getting populated her and scrollTop=0) by default. 

#### Actual behavior:

The page should is scrolling to the parent div of details list whose overflow-y is auto/scroll and then focus is being set even in case if the focusable element is in the view port.

#### Expected behavior:

The page should not scroll in case if the focusable element is in the view port.

**Comment by micahgodbolt** [comment]
@anushkumarkorukonda are you still having this issue? Can you provide a codepen repro showing this issue?
