### ISSUE TITLE
Dialog is not visible on iOS device and blocks user input 

### ISSUE THREAD

**Issue by robpearmain** [OfficeDev/office-ui-fabric-react#5156]
### Bug Report

- __Package version(s)__: 1.4.1
- __Browser and OS versions__: 11.4

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: (Blocking, High, Normal, Low) 

Blocking

Products/sites affected: (if applicable)

Sharepoint Framework on Sharepoint online

Dialog does not show, and the user can no longer interact with the page

#### Actual behavior:

Dialog Is invisible and blocks user touch

#### Expected behavior:

Dialog to be visible and not block user touch

**Comment by michaelangotti** [comment]
Known issue 4398. Will close this dup.
