### ISSUE TITLE
Support custom search icons in SearchBox

### ISSUE THREAD

**Issue by prabhatmuroor** [OfficeDev/office-ui-fabric-react#5159]
### Bug Report

- __Package version(s)__: 5.106.1002
- __Browser and OS versions__: Chrome/All

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: High

#### Describe the issue:
Office fabric searchbox, lets us change the icon, by ISearchBoxStyles here: https://developer.microsoft.com/en-us/fabric#/components/searchbox#Variants 

But icon has been hardcoded here: https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.base.tsx line 81.. 

#### Actual behavior:
Overriding style for SearchBox doesnt work

#### Expected behavior:
Overriding style for SearchBox should work

**Comment by micahgodbolt** [comment]
@prabhatmuroor what are you trying to do to the search icon that you cannot do?

https://codepen.io/micahgodbolt/pen/jvqgMm?editors=1010

**Comment by dcowen91** [comment]
@micahgodbolt  I'm not the original author of the issue, but the missing behavior that I see is the ability to specify a different icon to be rendered. Some other Fabric components accept iconProps where you can specify which icon will be used, not just the styles to be applied to the icon. 

This could be a by-design issue though, if you don't want to allow the Searchbox Component to render a different icon than what it does currently.

**Comment by redoz** [comment]
I'd like to be able to use a different icon (the `Filter` one specifically) will you take a PR for this?
If so, what approach is preferred:
1. Exposing an enum property `searchIcon` of type  `enum SearchBoxIcon { search, filter }`
2. Adding a `searchIconName?: string` property.
3. Adding a `searchIconProps?:  IIconProps` property (this would be more inline with what is done for the `clearButtonProps` property.
4. Something else?

**Comment by micahgodbolt** [comment]
yeah, that's a valid ask. A single prop for iconProps?: IIconProps would allow people to cheaply tweak the icon without a full onRender.

I'm good with that. just go iconProps, as calling it 'search' kinda indicates that it's always search icon
