### ISSUE TITLE
ContextualMenu: onDismiss not called on touch event outside of menu.

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#516]
Open on iphone.

http://codepen.io/dzearing/pen/WovrbX

Tap on button to expand
Tap anywhere outside of menu/button

Expected:
onDismiss called

Resulted:
nothing

**Comment by kristoferbrown** [comment]
FYI, this does not repro for me on Android. Seems to be an iOS specific issue.

**Comment by joschect** [comment]
@dzearing I cannot reproduce this but it looks like safari might not handle some things correctly.
