### ISSUE TITLE
How to get search box in `CommandBar` after update to Fabric 6

### ISSUE THREAD

**Issue by micnyk** [OfficeDev/office-ui-fabric-react#5161]
I've updated Fabric to version 6.6.1 and noticed that property `isSearchBoxVisible` is missing in `CommandBar` component.

How to substitute it? I widely use it in my app.

**Comment by micahgodbolt** [comment]
You can use an items 'onRender' to add any components you want, including a searchbox https://codepen.io/micahgodbolt/pen/zaGwee

**Comment by hrc7505** [comment]
@micnyk You can check [here ](https://codepen.io/hardik-chaudhary/pen/ejdoeY?editors=0110)that how we can use the `<SearchBox/>` in `<Commandbar/>` using `onRender()` method.
