### ISSUE TITLE
In Scan Mode, Screen Reader is not reading the DetailsList's column header information associated with the cells correctly.

### ISSUE THREAD

**Issue by kmrrakesh** [OfficeDev/office-ui-fabric-react#5164]
### Bug Report

- Package version(s) : (5.98.0)
- Browser and OS versions : (browser- chrome, edge and windows 10)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (High) 

Products/sites affected: (powerapps, cds-portal and BAF)

#### Describe the issue:

When selectionmode is single for the detailslist, screen-reader's scan-mode is not reading the column header information associated with cells value. Used narrator with browser edge version 42, with scan-mode "ON" reached to row of detailslist cell to check.

#### Actual behavior:

When selectionmode is single for the detailslist, screen reader scan-mode is not reading the column header information associated with cells value correctly.

#### Expected behavior:

Screen-reader's scan-mode should read the column header information associated with cells value.

**Comment by natalieethell** [comment]
Hey thanks for submitting this issue! This seems to be related to issue #4813 . I'll send out a PR today that should fix both.

**Comment by arunarokk** [comment]
I'm able Repro this issue in Fabric version 6.38.

Below detailslist has selection mode – single
When the Narrator scan mode is on ( up/ down arrow keys), while announcing the row values, for Version 1 value , announces column header of contextual menu ( … ) , for 3‎/‎9‎/‎2018‎ ‎10‎:‎29‎:‎53‎ ‎AM announces column header as Modified by… etc

**Comment by natalieethell** [comment]
I have an idea of why this could be happening and I’ll take a closer look soon.

**Comment by natalieethell** [comment]
Thanks for catching this @arunarokk! 

It looks like the issue was due to my removal of `role='columnheader'` for the "select all" checkbox when the detailslist has selection mode single. I anticipate that we can fix this column header issue by keeping the "select all" checkbox as a columnheader, but I still need to look more into how column indices should work when in single selection mode.

**Comment by natalieethell** [comment]
Also discovered another bug where the hidden "select all" checkbox still works in single selection mode. Adding a fix for this as well.
