### ISSUE TITLE
Using Customizer with Nav Component

### ISSUE THREAD

**Issue by wongJonathan** [OfficeDev/office-ui-fabric-react#5165]
### Bug Report

- __Package version(s)__: 6.8.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)
No
Requested priority: (Blocking, High, Normal, Low) 
Normal
Products/sites affected: (if applicable)

#### Describe the issue:

I'm trying to use the customizer to edit the styles of the Nav components. Currently I'm not sure if I'm using the customizer incorrectly or the feature is not yet available.

```
const NavStyles = {
    root: {
        background: 'red',
        color: 'brown'
    },
    navItem: {
        color: 'purple',
        background: 'blue'
    },
    navItems: {
        color: 'purple',
        background: 'blue'
    },
    link: {
        color: 'green',
        background: 'yellow'
    },
    chevronButton: {
        color: 'pink',
        background: 'pink'
    },
    compositeLink: {
        background: 'green',
        color: 'red'
    },
    linkText: {
        color: 'red',
        background: 'green'
    },
    group: {
        color: 'red',
        background: 'green'
    },
    groupConent: {
        color: 'red',
        background: 'green'
    },
};

const NewStyles = {
    Nav: {
        styles: NavStyles
    }
};

export class MenuButtonComponent extends React.Component<{}, {}> {

    constructor(props: any) {
        super(props);

    }

    render() {
        return (
            <Customizer scopedSettings={NewStyles}>
                <Nav
                    groups={
                        [{
                            links: [
                                { name: 'home', url: '', key: '1' },
                                { name: 'settings', url: '', key: '2' },
                                { name: 'menu', url: '', key: '3' }
                            ]
                        }]
                   }
                 />

            </Customizer>
        );
    }
}
```

I tried using all the Nav properties in hope of getting some type of response but after running it nothing had changed. Any help will be appreciated!

**Comment by oengusmacinog** [comment]
Hi @wongJonathan! Just submitted a PR with the change needed.  The way the styles are applied changed and this component still needed an update to work that way.  I tested with your example code and saw the bright customized color, so once the PR merges you should be all set!

**Comment by wongJonathan** [comment]
@oengusmacinog Hey sorry for the late reply, but thank you so much for the fix! I honestly thought I was missing something small, but I guess I'm not crazy after all. Thanks again!
