### ISSUE TITLE
Webpack stuck at 95% emitting

### ISSUE THREAD

**Issue by smoak** [OfficeDev/office-ui-fabric-react#5167]
### Bug Report

- __OS version__: macOS 10.13.3
- __Node version__: 8.11.2
- __Npm version(s)__: 5.6.0, 6.1.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Don't know the fix

Requested priority: Blocking

Products/sites affected: N/A

#### Describe the issue:

Following the README:

1. `git clone https://github.com/OfficeDev/office-ui-fabric-react.git`
2. `npm install`
3. `npm start`

Webpack stalls at 95% emitting. I've left this running for 5 minutes, 10 minutes, 30 minutes, and even a few hours. No progress gets made.

#### Expected behavior:

Webpack to not stall at 95%

### Repro:

Following the README:

1. `git clone https://github.com/OfficeDev/office-ui-fabric-react.git`
2. `npm install`
3. `npm start`

**Comment by smoak** [comment]
If I comment out `WebpackNotifierPlugin` here https://github.com/OfficeDev/office-ui-fabric-react/blob/16109440946077583269fe7bda0274d8703b9ffe/scripts/tasks/webpack-resources.js#L150 it works for me.

**Comment by kenotron** [comment]
I believe this is already fixed with the exact fix that @smoak suggested here.
