### ISSUE TITLE
[Feature Request] Dropdown: It should have a property to show min no of menu items

### ISSUE THREAD

**Issue by b-priyank** [OfficeDev/office-ui-fabric-react#5177]
Height of Dropdown - "menu items callout" keeps shrinking when enough space is not available below it. Even though, space is available on the top, it open downwards. 

Feature Request: 
Dropdown should have a property which takes how many minimum number of options we need to show. If enough space is not available below the dropdown then it should open "menu items callout" above the Dropdown. Currenlty this callout opens above the dropdown only if there's not enough space for 1 item. Ask here is to provide an option to take input 'n' instead of this 1 item.

CodePenRepro: https://codepen.io/anon/pen/qKmpPp

**Comment by micahgodbolt** [comment]
we already have plans to make dropdown act more like the windows UI, displaying above input when there isn't enough room below. But the idea of min no of items is creative as well. I'll add it to our backlog item.


#3719
