### ISSUE TITLE
SearchBox component causes page reload on clear input button click

### ISSUE THREAD

**Issue by DariuS231** [OfficeDev/office-ui-fabric-react#518]
In some cases, when the the clear input button is clicked, the page gets reloeaded

**Comment by dzearing** [comment]
Definitely a bug when nesting in a form. Repro here:

http://codepen.io/dzearing/pen/WovWLy

**Comment by dzearing** [comment]
In PR.

**Comment by dzearing** [comment]
This is now resolved and published, along with a number of other searchbox issues. Please let us know if you see any additional issues.

**Comment by DariuS231** [comment]
Awesome!!! Thank you, I haven't been able to test it in my environment though. 

I'm having some issues after upgrading the package version from 0.60.0 to 0.68.0. Was there a mayor dependency change on version 0.61.0 that I need to apply on mi project as well??

**Comment by dzearing** [comment]
Typescript 2 compiler.
