### ISSUE TITLE
Tabbing/scrolling issues in dialog containing choicegroup example

### ISSUE THREAD

**Issue by BrendanMcK** [OfficeDev/office-ui-fabric-react#5183]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: Chrome on Mac, EDGE on PC

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: Unknown; issue repros on Fabric demo site

#### Describe the issue:

Visit Fabric dialog page here:
https://developer.microsoft.com/en-us/fabric#/components/dialog

...scroll down to the "Dialog with large header and ChoiceGroup" area, and click the "Open Dialog" button.

Use Tab to move focus forwards through the items in the dialog; then use Shift-tab to cycle focus backwards through the same elements.

#### Actual behavior:

Tabbing forwards, focus moves as follows:
* Save button
* Cancel button
* Option A item
...back to Save button.

Shift-Tabbing forwards, focus moves as follows:
* Cancel button
* Save button
* Action B item
* Action A item - at this point, the background document scrolls to the bottom of the page
...back to Cancel button.

#### Expected behavior:

When tabbing forwards, focus should move as follows:
* Save button
* Cancel button
* Option B item
...back to Save button.

When tabbing into the choice group, the currently selected item - Option B - should take focus. Instead, the first item - Option A - is incorrectly taking focus.

Shift-Tabbing forwards, focus should move as follows:
* Cancel button
* Save button
* Action B item
...back to Cancel button.

The Action A item should not take focus, and the background should not scroll.

It seems that the logic in the Modal for keeping focus within the lightbox is not taking the special rules for radiobuttons / ChoiceGroup into account here. Unclear what's causing the unexpected scrolling though.

**Comment by JasonGore** [comment]
I am seeing expected behavior [here](https://developer.microsoft.com/en-us/fabric#/components/dialog) and think this may have been resolved with #5842. If you are still seeing issues, please feel free to reopen.
