### ISSUE TITLE
neutralSecondaryAlt has been deprecated for a while and should be removed

### ISSUE THREAD

**Issue by phkuo** [OfficeDev/office-ui-fabric-react#5194]
### Bug Report

- __Package version(s)__: all

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Partially... each individual control owner should fix it

Requested priority: High

Products/sites affected: SPList

#### Describe the issue:

neutralSecondaryAlt was deprecated several months ago, we should remove any instances of it.

#### Actual behavior:

Several places in code are still using it:
https://github.com/OfficeDev/office-ui-fabric-react/search?q=ms-color-neutralsecondaryalt&unscoped_q=ms-color-neutralsecondaryalt
Also search for just neutralSecondaryAlt

This causes bad behavior, like text in columns in the detailList not theming because it's using a deprecated slot.

![image](https://user-images.githubusercontent.com/20691641/41383790-51b44412-6f27-11e8-8c30-13eb991610b6.png)

**Comment by cliffkoh** [comment]
@phkuo  Looks like only 3 components are reproing this? Pivot/DocumentCard/DetailsList.

It feels like this isn't per se so much a fix for codeowners, but more requiring design signoff for what the right color should be (and in turn, @betrue-final-final to approve the changes in screener).

**Comment by dzearing** [comment]
maybe faster to just make a fix for the 3 places?

**Comment by JasonGore** [comment]
I didn't know about this when I did #5324 (where I added `neutralSecondaryAlt` to `IPalette`), so I'll tag it here as a work item.

**Comment by betrue-final-final** [comment]
Yes, we should get rid of this color.

**Comment by Vitalius1** [comment]
I will make the fix for now only for DetailsList as it has a bigger impact and create a separate issue for removing the remaining instances of it's use.

**Comment by KevinTCoughlin** [comment]
> 
> 
> Oops, I missed the comment about a new issue (but don't see a link to it here so will follow up.)

Linked now 👍
