### ISSUE TITLE
FocusZone gets stuck in a disabled ComboBox

### ISSUE THREAD

**Issue by paterasMSFT** [OfficeDev/office-ui-fabric-react#5198]
\### Bug Report

- __Package version(s)__: 6.9.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Normal

Products/sites affected: TFS

#### Describe the issue:

Users cannot use the arrow keys to escape a disabled ComboBox (or theoretically any readOnly input) within a FocusZone.

#### Actual behavior:

Pressing left/right/up/down when focused on a readonly combobox does nothing.

#### Expected behavior:

Left/right or up/down (depending on FocusZoneDirection) should move the focus to the next item.

### If applicable, please provide a codepen repro:

https://codepen.io/paterasMSFT/pen/yEozOO

**Comment by dzearing** [comment]
@jspurlin I see `data-is-interactable` on the ComboBox. Shouldn't this be `data-is-focusable="false"`?

This would allow focuszone to skip over it. That may or may not be the expectation.

Alternatively, we could modify FocusZone to skip over `readonly` elements.

**Comment by jspurlin** [comment]
No, the comboBox should still be focusable when disabled to allow for users to be able to copy the content in the input (font name, for example). The FocusZone can move out of the input with TAB, although I think the FocusZone may need handleTabKey set to FocusZoneTabbableElements.inputOnly

**Comment by paterasMSFT** [comment]
We still want the combobox visitable so screen readers can read its contents.

I was thinking we could [whitelist the arrow keys on disabled ComboBoxes](https://github.com/OfficeDev/office-ui-fabric-react/blob/d2edbbc6c069f8cb8d2936a8d982aa50be0613e1/packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx#L1482), and [always have readOnly inputs ready to lose input](https://github.com/OfficeDev/office-ui-fabric-react/blob/d2edbbc6c069f8cb8d2936a8d982aa50be0613e1/packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.tsx#L776).

I tested this locally and it works well.

**Comment by jspurlin** [comment]
Not sure if I agree with that, it makes the way a user interacts with comboBoxes different depending on if they are disabled or not which breaks consistency in the overall navigation model.

**Comment by paterasMSFT** [comment]
Because the ComboBox will scroll its parent? That seems to be the only impact.

If that's a dealbreaker, how do we address the FocusZone issue?

**Comment by jspurlin** [comment]
No, because arrow keys will leave the comboBox in one case and will not in the other case

**Comment by paterasMSFT** [comment]
Only if they're in a FocusZone. If it's not, disabled ComboBoxes will remain the same as other controls when you press the arrow keys. It scrolls its parent container, but remains focused.

You can see the behavior in action if you build and run [this branch](https://github.com/paterasMSFT/office-ui-fabric-react/tree/DisabledComboBoxExample), if you want. Just go to the ComboBox page, I added a few test scenarios.

**Comment by paterasMSFT** [comment]
Thoughts? We're blocked on this.

**Comment by jspurlin** [comment]
I think at most it should be a prop to allow arrow keys to leave when disabled. Focus zone has a callback `shouldInputLoseFocusOnArrowKey` where the builder can control when arrow keys should leave... That's another alternative for this scenario.

Also, can you go into more details on what the scenario is?

**Comment by paterasMSFT** [comment]
I do not believe shouldInputLoseFocusOnArrowKey will help, as [_shouldInputLoseFocus](  private _shouldInputLoseFocus(element: HTMLInputElement, isForward?: boolean) {) does not get called when the ComboBox is disabled.

Our secenario is simply that there's a button in a FocusZone that cannot be reached via keyboard if a ComboBox is disabled. In the [aforementioned branch](https://github.com/paterasMSFT/office-ui-fabric-react/tree/DisabledComboBoxExample), there's an example of the scenario. It looks like this:

![image](https://user-images.githubusercontent.com/35780775/41621287-32d048a4-73da-11e8-81c5-7942b2aefcc0.png)

When a user tabs to the Focus Zone, they press right once to go from "I'm a button" to the ComboBox, and then right again to reach "I'm the other button". If the ComboBox is disabled, the second button is unreachable.

Shall I submit a PR with a prop for allowing arrow keys when disabled?

**Comment by paterasMSFT** [comment]
@jspurlin does [this PR](https://github.com/OfficeDev/office-ui-fabric-react/pull/5272) address your concerns?
