### ISSUE TITLE
NPM is not installing latest version of office-ui-fabric-react

### ISSUE THREAD

**Issue by keydoubleu** [OfficeDev/office-ui-fabric-react#5199]
- __Package version(s)__: 5.112.0
- __Browser and OS versions__: Windows 7

Are you willing to submit a PR to fix? No
Requested priority:  Low

#### Describe the issue:

When I run the command **npm install office-ui-fabric-react**, it installs package version 5.112.0 instead of the latest version (v6.9.0).

#### Expected behavior:

**npm install office-ui-fabric-react** should install the latest version.

**Comment by dzearing** [comment]
```
npm dist-tag ls office-ui-fabric-react
hf: 5.106.1-hotfix.2
latest: 6.9.0
next: 6.0.0-beta6
styling: 4.0.0-styling6
```
I am seeing latest marked as 6.9.0. I ran locally just to validate, and indeed see 6.9.0 installed.

If you run into this you could have:

1. A lockfile forcing you to a specific version.
2. Something wrong in your npm cache perhaps.
3. Or, we really do have a package tagging problem!

Just to rule out #3, run the `npm dist-tag ls office-ui-fabric-react` command from above. It will tell you what the latest is, according to npm.
