### ISSUE TITLE
Investigate removing dropdown since comboBox is a super-set of dropdown functionality

### ISSUE THREAD

**Issue by jspurlin** [OfficeDev/office-ui-fabric-react#5205]
### Bug Report

- __Package version(s)__: 6.9.0

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: Normal 

Products/sites affected: (if applicable)

#### Describe the issue:
Right now comboBox and dropdown both exist but comboBox contains all the functionality (and more) that dropdown does. The result are confused engineers and two components that must continue to be updated when changes are made.

#### Actual behavior:
There's two components...

#### Expected behavior:
There should only be comboBox

**Comment by micahgodbolt** [comment]
Dropped this into our backlog as well. Would love to see this happen. 
https://uifabric.visualstudio.com/UI%20Fabric/_workitems/edit/256

hope that link works.

**Comment by JasonGore** [comment]
I agree that there should be consolidation, but ComboBox also seems to currently have more open issues than Dropdown currently. Will add to our Backlog milestone.

**Comment by JasonGore** [comment]
Give the number of outstanding issues we have with CombBox (encapsulated by #5929) I'm going to also escalate this issue to PRI1 as a possible resolution.

**Comment by ecraig12345** [comment]
Unless someone objects, I'd like to close this issue in favor of #6030 since the issues are very similar and that one has a bit more discussion/planning.

**Comment by micahgodbolt** [comment]
closing this down and tracking work on #6030
