### ISSUE TITLE
SearchBox: with Narrator scan mode, focus is not going inside of the search box text field to enter text 

### ISSUE THREAD

**Issue by arunarokk** [OfficeDev/office-ui-fabric-react#5216]
### Bug Report

- office ui fabric react Package version(s) 5.118.0
-Edge  Win 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal) 

Products/sites affected: (if applicable)

#### Describe the issue:

when using narrator in scan mode ( up , down arrow keys), focus goes to searchbox, narrator announces it as menubar and but focus doesn't go to the text field to enter  search text, this is not happening when we navigate backwards  

you can verify the this behavior in here
https://developer.microsoft.com/en-us/fabric#/components/searchbox

**Comment by JasonGore** [comment]
Can you see if #5210 resolves the behavior you're seeing? Thanks

**Comment by JasonGore** [comment]
#5210 has been merged and should resolve this issue.
