### ISSUE TITLE
TooltipHost: Renders in wrong position in IE11  and can be dismissed unexpectedly

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#5223]
### Bug Report

- __Package version(s)__: Last
- __Browser and OS versions__: IE11

#### Priorities and help requested (not applicable if asking question):

Requested priority: (Normal) 

Products/sites affected: (Modern web parts)

#### Describe the issue:

Go to [Tooltip demo page](https://developer.microsoft.com/en-us/fabric#/components/tooltip) and hover on the "Hover over Me" button.
Tooltip renders in wrong position in IE and causes tooltip being unexpectedly dismissed.

#### Actual behavior:

In IE, tooltip is rendered inside the target button:
![image](https://user-images.githubusercontent.com/7711735/41464245-36ae630e-70cc-11e8-8e01-598cd949a055.png)

And if hover on the up-center position of the button, the tooltip will move to a weird position:
![image](https://user-images.githubusercontent.com/7711735/41464325-797e5c5c-70cc-11e8-9866-a6d55f686e7d.png)

#### Expected behavior:

In chrome, tooltip is rendered above the target button:
![image](https://user-images.githubusercontent.com/7711735/41464224-2653a546-70cc-11e8-988f-80f9c9279711.png)

### If applicable, please provide a codepen repro:

https://developer.microsoft.com/en-us/fabric#/components/tooltip

**Comment by dzearing** [comment]
Hmmm. I am not reproing this.

![image](https://user-images.githubusercontent.com/1110944/41783272-50b90680-75f1-11e8-8954-f3277cb32d4d.png)

**Comment by dzearing** [comment]
@ipip2005 Are you on a specific OS or IE build?

**Comment by ipip2005** [comment]
@dzearing from your screenshot, you're actually seeing the "Actual" issue where the tooltip position is different than chrome

**Comment by micahgodbolt** [comment]
Not quite sure why this issue was closed. @ipip2005 can you provide a concrete set of repro steps? Codepen + browser/OS version etc. If this is still an issue we really want to fix it
