### ISSUE TITLE
Make 'npm install' work with npm 6.1.0 on Windows

### ISSUE THREAD

**Issue by kenotron** [OfficeDev/office-ui-fabric-react#5227]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: Windows

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) Yes

Requested priority: (Blocking, High, Normal, Low)  Low

Products/sites affected: (if applicable)

#### Describe the issue:

On the Windows platform, if developer elected to upgrade their npm version to 6.x series, they will encounter #5174. There's a workaround of either:

1. downgrade to npm 5 with (npm i npm@5.6.0) 
2. use rush install && build directly instead of npm install

Given there are pretty viable workarounds, I believe this bug is of low-priority. We should probably update our README.md with this information separately.

- [ ] Update README.md
- [ ] Make sure npm install works on Windows against npm 6.x

**Comment by qingbolove** [comment]
hey, any updates about this issue? some webpack plugins are requiring 6.1.0 npm version, I am now blocking on this issue now...

**Comment by jordandrako** [comment]
There are concerns from ODSP security about the security and vulnerabilities in some of our repos' dependencies. Can we bump up the priority on this so it's easier to run audits (introduced with npm v6)?

**Comment by KevinTCoughlin** [comment]
I ran into this earlier today with `npm@6.3` but once I fixed git on my PATH and restarted I've been OK... strange.

**Comment by kenotron** [comment]
Okay, so here's my thoughts on this one - upgrading the package manager client isn't in the scope of this bug. I just wanted to make sure the bootstrapping package manager isn't busted on Windows + npm 6.x. It seems like @KevinTCoughlin has given confirmation on this. So I think security / vulnerability issues aside, we should really just close this one. We'll probably investigate the use of pnpm / yarn after this is closed in the foreseeable future (Rush doesn't support npm 6 at the moment without some broken features like rush update being busted by npm 5 & 6).
