### ISSUE TITLE
Broken link to advanced documentation

### ISSUE THREAD

**Issue by smirnowld** [OfficeDev/office-ui-fabric-react#5240]
### Bug Report

Not an issue with this repository per se, but the link to advanced documentation from https://developer.microsoft.com/en-us/fabric#/get-started is broken. 

The link under paragraph **Other ways to get Fabric React** takes you to https://github.com/OfficeDev/office-ui-fabric-react/blob/master/ghdocs/ADVANCED.md which doesn't seem to exist. I believe the correct target for the link should be https://github.com/OfficeDev/office-ui-fabric-react/wiki/Advanced-Usage

I didn't find a better place to log this bug, if I should raise it elsewhere, please let me know.

**Comment by micahgodbolt** [comment]
This was fixed just a few days ago. The website doesn't auto publish, so the changes aren't live yet. https://github.com/OfficeDev/office-ui-fabric-react/pull/5203
