### ISSUE TITLE
Nav: Add onRenderIcon

### ISSUE THREAD

**Issue by Fensterbank** [OfficeDev/office-ui-fabric-react#5254]
**Describe the feature that you would like added**
In most cases it is possible to use custom icon libraries e.g. by using `onRenderIcon` methods or overwrite default icons with `registerIcons`.
In our project we are rendering a dynamic NavMenu (based on a service's json response) with dynamic icons while using FontAweseme icons.

Since `NavLink` does not contain an `onRenderIcon` method, the only way to use this with a custom icon library is to register _every possible_ icon name upfront using `registerIcons` instead of just rendering an own icon component.

**What component or utility would this be added to**
NavLink

**Have you discussed this feature with our team, and if so, who**
No

**Additional context/screenshots**
https://github.com/OfficeDev/office-ui-fabric-react/blob/cfa7a19ec1d6f98c13f822a828e0751f64507dbd/packages/experiments/src/components/Nav/NavLink.tsx#L40

**Comment by JasonGore** [comment]
I have added this as part of #5815.

**Comment by micahgodbolt** [comment]
This is now a duplicate to #5815. Closing this to keep everything in 1 place.
