### ISSUE TITLE
Show Password button is not accessible using keyboard

### ISSUE THREAD

**Issue by gykuma** [OfficeDev/office-ui-fabric-react#5263]
### Bug Report 

- __Browser and OS versions__: Microsoft Edge 42.17677.1000.0
 
#### Priorities and help requested:
  
Requested priority: (Normal) 
 
Products/sites affected: (VSTS)
 
#### Describe the issue:
 
1. Navigate to a TextField component of type password  `<TextField type='password' />` and type something
2. Try to view password while you type by accessing 'Show password' button using keyboard
 
#### Actual behavior:
 
Show password icon is not accessible using keyboard
 
#### Expected behavior:
 
Users who rely on Keyboard should be able to see typed characters in 'Secret' field using keyboard.

**Comment by dzearing** [comment]
This would be an Edge issue. This has nothing to do with Fabric, but is a built into the browser. You are welcome to file Edge issues here:

https://issues.microsoftedge.com/
