### ISSUE TITLE
DropDown: control type is defined as list

### ISSUE THREAD

**Issue by satbai** [OfficeDev/office-ui-fabric-react#5266]
### Bug Report 
 
- __Package version(s)__: latest
- __Browser and OS versions__: all
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
#### Describe the issue:
 I believe the control type of the Dropdown should be combo box, at least that's what it used to be. If the current control type is correct, please provide details why.

![image](https://user-images.githubusercontent.com/24945574/41671050-d9fb271c-746a-11e8-98e8-a01600c17549.png)

### If applicable, please provide a codepen repro:
https://developer.microsoft.com/en-us/fabric#/components/dropdown

**Comment by dzearing** [comment]
Needs some investigation.

**Comment by cliffkoh** [comment]
Hi @satbai , could you please add more information on what is the expected and actual state, from a HTML markdown POV?

**Comment by satbai** [comment]
Hi @cliffkoh , 

The role attribute in the HTML element will change the control type. The current role is "listbox" and narrator will say: 

> Basic dropdown example, Select an Option, selected, selection contains 0 items,

With the role "combobox" the narrator says:

> Basic dropdown example, Select an Option, editable combo box,

https://www.w3.org/TR/wai-aria-practices/#combobox 
https://www.w3.org/TR/wai-aria-practices/#Listbox

Since this bug got raised by our vendor test pass and I have a meeting with them tomorrow, I can ask what the correct role for this should be to make sure we're not changing the roles back and forth. It looks like the roles have been changed a few times.

Some related closed issues:
https://github.com/OfficeDev/office-ui-fabric-react/issues/4262
https://github.com/OfficeDev/office-ui-fabric-react/issues/4360
https://github.com/OfficeDev/office-ui-fabric-react/issues/2335

**Comment by cliffkoh** [comment]
Hi @satbai, looking at the specs you linked to, it says that:

Combobox:
> A combobox is a widget made up of the combination of two distinct elements: 1) a single-line textbox, and 2) an associated pop-up element for helping users set the value of the textbox.

Listbox:
>A listbox widget presents a list of options and allows a user to select one or more of them. A listbox that allows a single option to be chosen is a single-select listbox; one that allows multiple options to be selected is a multi-select listbox.

Our Dropdown does not have a listbox in it (we do have a separate ComboBox component that does have the textbox). As such, the current role should be correct.

**Comment by cliffkoh** [comment]
Please also look at #5354 where I discuss the `role` at greater depth.
