### ISSUE TITLE
DropDown: Narrator announces 'selection contains 0 items' on item selection

### ISSUE THREAD

**Issue by gykuma** [OfficeDev/office-ui-fabric-react#5270]
### Bug Report 
 
- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (Microsoft Edge 42.17134.1.0)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (Normal) 
 
Products/sites affected: (VSTS)
 
#### Describe the issue:
 
While using [Dropdown](https://developer.microsoft.com/en-us/fabric#/components/dropdown) control, on selecting any item, the narrator announces as _**'selected, selection contains 0 items'**_ which is misguiding for screen reader users.

**Comment by betrue-final-final** [comment]
This has been coming up in several accessibility reviews. @michaelangotti, is this something @lynamemi or someone can look at?

**Comment by lynamemi** [comment]
I also was able to reproduce this. The general aria layout looks correct so I will have to find time to dig in more.

**Comment by lynamemi** [comment]
Closing this in favor of the catch-all Dropdown accessibility issue: #5354
