### ISSUE TITLE
How do I dynamically style DetailsRow

### ISSUE THREAD

**Issue by NigelWit** [OfficeDev/office-ui-fabric-react#5299]
I am using the DetailsList component for rendering out a list of tasks, and I want to style the rows based on the task status. I tried using an onRenderRow handler to add a className to the DetailsRow, but that seems to be ignored:

_onRenderRow = (props) => {
    return <DetailsRow {...props} className={"overdueTask"} />;
  }

I guess I could use the onRenderColumn and style each column of the row, but that seems unnecessarily complicated and limiting. Am I missing something obvious?

Maybe this would make a good example to be added to 'office-ui-fabric-react/src/components/DetailsList/examples'?

Thanks!

**Comment by dzearing** [comment]
You have a couple of options:

Your column can take in a classname (so if you want to style a particular cell, you can use that.)

You can use onRenderRow and override defaults. What you suggested should work fine. However, you might fight css specificity. I just tried it here, and had to do some specificity fighting to get the overriding.

https://codepen.io/dzearing/pen/wXjore?editors=0110

**Comment by NigelWit** [comment]
Ok thanks a lot David - love your work!
