### ISSUE TITLE
CommandBar needs a way to take overflowMenuProps

### ISSUE THREAD

**Issue by staylo8** [OfficeDev/office-ui-fabric-react#5300]
### Bug Report 
 
- __Package version(s): 6.0
- __Browser and OS versions: N/A
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
Yes
 
Requested priority: (Blocking, High, Normal, Low) 
Normal
 
Products/sites affected: (if applicable)
Owa Mail
 
#### Describe the issue:
 
The CommandBar in 6.0 has a lingering OverflowMenuProps prop that isn't read. This prop was added to the experiments CommandBar to allow users to pass all props except items to the overflow menu button. This prop was intended to be removed, thinking the consumer could use OverflowButtonProps.menuProps, however, menuProps requires items. The consumer should not pass items via overflowButtonProps.menuProps because they do so via the CommandBar's overflowItems prop. 
 
#### Actual behavior:
 
OverflowMenuProps not respected.
 
#### Expected behavior:
 
OverflowMenuProps respected.
 
### If applicable, please provide a codepen repro:
 
https://codepen.io/anon/pen/MXGeVY

**Comment by micahgodbolt** [comment]
we can either mix items into overflowButtonProps.menuProps (which would require dummy items data), we could support overflowMenuProps (which feels unnecessary) or create a new interface that Excludes the typical menuProps and replaces it with Partial<IConetextualMenuProps> which unfortunatly would minbar us to TS 2.8
