### ISSUE TITLE
IContextualMenuItem's title doesn't work in IE on CommandBar component

### ISSUE THREAD

**Issue by tailwu** [OfficeDev/office-ui-fabric-react#5310]
We are using CommandBar component, and its item type is IContextualMenuItem. We assigned value to IContextualMenuItem's title.
In Chrome, it will call out the message, but in IE, it won't call out the message.
![image](https://user-images.githubusercontent.com/40489540/41770112-e96c4476-7643-11e8-9ae6-7a36e3f4fc39.png)
![image](https://user-images.githubusercontent.com/40489540/41770167-0f01b978-7644-11e8-8763-6b7f0cafd651.png)

**Comment by micahgodbolt** [comment]
Works for me in edge and IE11 using Fabric 5.110.0 https://codepen.io/micahgodbolt/pen/zaGwee

![image](https://user-images.githubusercontent.com/1434956/41800741-bbcc9ef2-762b-11e8-9f9a-fd4df31120e8.png)



Please doublecheck, provide browser and Fabric version and a codepen if the above code does not fit your situation.

**Comment by tailwu** [comment]
If the item’s “disabled” property is true, the callout doesn’t work in IE. Could you please try again? Thanks.

**Comment by micahgodbolt** [comment]
![image](https://user-images.githubusercontent.com/1434956/42352029-f0a38ea6-806c-11e8-92c4-71062aa98741.png)

Sorry for the delay. It still appears to work when disabled. Can you create a reproable example?

**Comment by tailwu** [comment]
Hi,

Could you please visit https://codepen.io/micahgodbolt/pen/zaGwee in IE instead of Edge? And make sue “disabled” property is true.
I still can repro this issue in IE.
[cid:image002.png@01D4150E.DD0D0350]

Thanks

**Comment by micahgodbolt** [comment]
I do see this is a bug, though I doubt we'll have time to fix it. It's an old version of the command bar (6.0 has a completely new one), and it only happens on a single browser under a very specific situation.
