### ISSUE TITLE
Need hex values for components that use mergestyles

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#5318]
Scenario: You're a person responsible for the design of a component. You need to find the hex value.

Repro:

1. Go to a component page with mergestyles
2. Right click > Inspect element
3. Look for hex color

Result: Only can get an RGB value
Expect: Get a hex color like our colors are specified in and we've always done.

**Comment by cliffkoh** [comment]
Resolved offline as being a Chrome devtools thing (shift+click to toggle between formats).
