### ISSUE TITLE
ComboBox: Add name prop

### ISSUE THREAD

**Issue by FallingSnow** [OfficeDev/office-ui-fabric-react#5321]
### Bug Report 
 
- __Package version(s)__: 6.18.0
- __Browser and OS versions__: Firefox Nightly 62.0a1, Linux 64bit
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Low
 
Products/sites affected: -
 
#### Describe the issue:
 
ComboBoxes do not pass the name property to the inner input. This impares it's usage in forms, especially with HTML5 Formdata.
 
#### Actual behavior:
 
No name property on the inner input tag.
 
#### Expected behavior:
 
Matching name property on the inner input tag.

**Comment by mikewheaton** [comment]
I also can't see a way to provide a `name` attribute to the `input` that ComboBox renders. It would be useful to have a prop specifically for this purpose or to be able to pass in a full set of props to the TextField within.

**Comment by micahgodbolt** [comment]
Adding this to #6030, which is our meta issue for the consolidation of dropdown and comobobox
