### ISSUE TITLE
CommandBarItem shouldFocusOnMount is not respected

### ISSUE THREAD

**Issue by amyngu** [OfficeDev/office-ui-fabric-react#5323]
### Bug Report 
 
- __Package version(s)__: 6.15.0+ 
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low): Normal
 
Products/sites affected: (if applicable) OWA
 
#### Describe the issue:
 
shouldFocusOnMount = false is no longer respected
 
#### Actual behavior:
 
After context menu is opened the menu gets focused automatically
 
#### Expected behavior:
 
After context menu is opened, the menu does not get focused automatically
 
### If applicable, please provide a codepen repro:
 https://codepen.io/anon/pen/BVVjmX

**Comment by amyngu** [comment]
@kelseyyoung I think this might be from your change? https://github.com/OfficeDev/office-ui-fabric-react/pull/5185 I'm seeing shouldFocusOnMount is being overwritten to true each time

**Comment by micahgodbolt** [comment]
just to clarify, this only happens when using keyboard navigation, not mouse click

**Comment by kelseyyoung** [comment]
Just to understand your codepen correctly, for both mouse and keyboard the background should be yellow in the menu?

If that's the case and this issue is only for keyboard, I think it's because the _toggleMenu method in BaseButton is taking the default value (true) always when it's piped through keyboarding. I can make this change Monday. Sorry about that

**Comment by kelseyyoung** [comment]
About to send out a PR, I also wanted to point out that the shouldFocusOnMount prop should be in the subMenuProps in your codepen example. You'll see in the code I'll be checking the button's menuProps because shouldFocusOnMount is defined there, not on the button itself
