### ISSUE TITLE
SpinButton: className prop is not applied

### ISSUE THREAD

**Issue by JllyGrnGiant** [OfficeDev/office-ui-fabric-react#5327]
### Bug Report 
 
- __Package version(s)__: 5.112.0 (and probably more recent releases)
- __Browser and OS versions__: All
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
Maybe
 
Requested priority: (Blocking, High, Normal, Low)
Normal
 
Products/sites affected: (if applicable)
VSTS

#### Describe the issue:
 
Consumer specified className for the SpinButton component is ignored despite being a part of the interface in [SpinButton.types.ts](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/SpinButton/SpinButton.types.ts).
 
#### Actual behavior:
 
Class is not applied.
Using getClassNames is not a desired option as it seems to completely eliminate other styling on the control when all I want is to add my own class to the SpinButton.
 
#### Expected behavior:
 
Class is applied to the outermost element of the component
 
### If applicable, please provide a codepen repro:
[Repro](https://codepen.io/anon/pen/bKKwdJ)

**Comment by micahgodbolt** [comment]
@jspurlin are you able to make this fix, or is there someone else on your team that can pick up this work?

**Comment by micahgodbolt** [comment]
@JllyGrnGiant have you migrated to 6.x yet? We'd initially be targeting that branch.

**Comment by micahgodbolt** [comment]
Yeah, className is totally missing from the root div, or passing into getClassNames, or even this.props deconstruction. Should be a quick fix though.

![image](https://user-images.githubusercontent.com/1434956/45133043-3208cf80-b148-11e8-8515-80481f027aee.png)

**Comment by kenotron** [comment]
this looks like an easy one for shield, so i'll take this one :)

**Comment by micahgodbolt** [comment]
yeah, that's why I put it in shield :D
