### ISSUE TITLE
Editable list

### ISSUE THREAD

**Issue by aslanovsergey** [OfficeDev/office-ui-fabric-react#5329]
It would be nice to have editable list as a separate component or as a feature of the list or the detailedList components

**Comment by micahgodbolt** [comment]
Can you describe this a bit more? Do you have en example in the wild we can look at?

**Comment by aslanovsergey** [comment]
Ok, there is a vivid example - sharepoint list in quick edit mode
![image](https://user-images.githubusercontent.com/22150933/42154756-41ebda6e-7def-11e8-9c94-bb7f9f8919d8.png)

**Comment by aslanovsergey** [comment]
Here is an example
![image](https://user-images.githubusercontent.com/22150933/44972184-f7910e00-af60-11e8-8caf-1908d3a4e525.png)

**Comment by andrew-buckley** [comment]
A way to edit a list item inline would be great. Or is this functionality already offered?

**Comment by micahgodbolt** [comment]
We've got this captured in #6840. Closing down this duplicate.
