### ISSUE TITLE
TimePicker Component

### ISSUE THREAD

**Issue by Parataku** [OfficeDev/office-ui-fabric-react#533]
I would like to request some kind of TimePicker, or maybe a TimePicker mode for the DatePicker.

**Comment by mikewheaton** [comment]
I've added this to our [Trello board](https://trello.com/c/PTliciJ8), where we track requests for features and components.

**Comment by mmichaelbiz** [comment]
Can this be revived? Would be a nice addition to the Fabric 7 launch. Also related #1565.

**Comment by micahgodbolt** [comment]
This is really a design driven effort, not an engineering one. Until there is some design momentum to solving this with a new component, I don't believe we have any plans to create it.

**Comment by mmichaelbiz** [comment]
Shame. A good time and timestamp selector is useful.
