### ISSUE TITLE
TextField should show tooltip on hover if the content overflows

### ISSUE THREAD

**Issue by shyama1208** [OfficeDev/office-ui-fabric-react#5330]
Issue: When user enter a long text in the textfield, the text gets truncated and shows ellipses.
The textfield should also show the entire text as tooltip when user hovers on it.

**Comment by micahgodbolt** [comment]
I don't see textfield showing an elipsis, can you demo this? I'm not sure if this is expected behavior

![image](https://user-images.githubusercontent.com/1434956/42048126-1bbb56f2-7ab7-11e8-8598-e32ca60c7717.png)

**Comment by shyama1208** [comment]
TextField is showing ellipses only on Chrome.
Open https://developer.microsoft.com/en-us/fabric#/components/textfield
 and type in some long text in any of the textfield and focus out.

![image](https://user-images.githubusercontent.com/26054709/42074205-8fe3ddc0-7b88-11e8-9564-7c2485430790.png)

**Comment by micahgodbolt** [comment]
So it does! Thanks chrome for having a different implementation than FF or Edge. 

I believe the desired experience is no truncation, but simply pushing previous content to the left, and keeping the last character written on the right. (and no tooltip).

Definately a bug, hopefully we can force chrome to align with other browsers.

**Comment by shyama1208** [comment]
I feel we should also be showing tooltip on hover. Otherwise, how would one be able to view the entire content of the textfield?

**Comment by micahgodbolt** [comment]
I'm a bit baffled. Seems if you drop in a default value, both FF and Chrome will truncate and elipsis (and edge never does). But if you type into the input then remove focus, only Chrome jumps back to the left and adds the elipsis. FF just leaves it as is.

But if you use the mouse/keyboard to go back to the first character in the input, then drop focus, it'll add elipsis. So the difference in behavior is what happens on loss of focus. FF keeps input as is, chrome rewinds back to the first words entered. 

Nothing I'm seeing affects that behavior (telling chrome to stop rewinding, or FF to rewind). So @betrue-final-final , what are your feelings on tooltips here? It does appear to break with windows UI, so should we just leave this difference as something for the browser vendors to figure out?

**Comment by betrue-final-final** [comment]
I agree that if you lose focus and return, that it should have the insertion bar after the last character typed. Showing ellipses is very non-standard and can be confusing as it may imply that someone typed the ellipses. 
As for tooltips, that would be nice to have. Not sure if it's a deal breaker though.

**Comment by micahgodbolt** [comment]
Chrome:
![input](https://user-images.githubusercontent.com/1434956/42233874-98762016-7ea7-11e8-8e2c-cd1b35835bde.gif)

Firefox:

![input_ff](https://user-images.githubusercontent.com/1434956/42233882-9de4eff0-7ea7-11e8-91db-d8e70cc3652b.gif)

**Comment by micahgodbolt** [comment]
I've opened up a bug with chromium. For now, we're calling this working as expected, and that Chrome is out of alignment with standards.

https://bugs.chromium.org/p/chromium/issues/detail?id=860024&can=2&q=component%3AUI%3EInput%3EText%20%20os%3DWindows&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified
