### ISSUE TITLE
Checkbox component has wrong style in IE

### ISSUE THREAD

**Issue by tailwu** [OfficeDev/office-ui-fabric-react#5331]
In IE, if the label is very long, will have scroll bar because all content will be in one line.
In Chrome, it will be shown correctly via new line.
Sample codes:
<Dialog
    hidden={false}
    dialogContentProps={{
        title: 'test',
        subText:'test'
    }}
    >
<Checkbox label="aaaaaaaaaaaaaaaaaaaaaaaaaa bbbbbbbbbbbbbbb ccccccccccccccccccc" />
</Dialog>

In IE:
![image](https://user-images.githubusercontent.com/40489540/41841811-d2c761a6-789b-11e8-85a1-c80234fd0ef4.png)

In Chrome: 
![image](https://user-images.githubusercontent.com/40489540/41841792-c905b190-789b-11e8-85f1-5c7c96163d16.png)

**Comment by cliffkoh** [comment]
Hi @tailwu, in the latest version of OUFR, the behavior across all 3 browsers are the same when word-wrapping does not come into the picture.

![image](https://user-images.githubusercontent.com/1003246/42199543-e1aecc4c-7e43-11e8-8af3-8f422d5515c3.png)

A scrollbar does not appear.

They do differ when word-wrapping is applicable.

![image](https://user-images.githubusercontent.com/1003246/42199581-0e9e4516-7e44-11e8-8180-91b3bf63f19e.png)

@betrue-final-final, would you be able to advise on what the correct state is?

**Comment by micahgodbolt** [comment]
Pretty sure this was fixed recently. We cannot repro.
