### ISSUE TITLE
Pivot: Ctrl+number doesn't work in Firefox to switch tabs if Pivot is focused

### ISSUE THREAD

**Issue by pablonete** [OfficeDev/office-ui-fabric-react#5332]
### Bug Report 
 
- __Package version(s)__: 5.112
- __Browser and OS versions__: Firefox Quantum v.60.0.1 (64-bits)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) Maybe
 
Requested priority: (Blocking, High, Normal, Low) Normal
 
Products/sites affected: (if applicable) VSTS
 
#### Describe the issue:
 
Ctrl-number is a browser shortcut to switch between tabs.
While focus is on any Pivot header, this shortcut won't work in Firefox.
 
#### Actual behavior:
 
1. Open Firefox
2. Open a second tab.
3. Open https://developer.microsoft.com/en-us/fabric#/components/pivot
4. Click on any Pivot header (like "Shared with me" and leave focus there).
5. Use Ctrl-1 to go to the original tab. It won't work.
 
#### Expected behavior:
 
Ctrl-number navigation should work. It does in Chrome.
 
I suspect of this logic in [Pivot.base.tsx:263](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Pivot/Pivot.base.tsx#L263):
```ts
  private _onKeyPress(itemKey: string, ev: React.KeyboardEvent<HTMLElement>): void {
    ev.preventDefault();
    if (ev.which === KeyCodes.enter) {
...
```
Should `preventDefault` go inside the if branch?

**Comment by micahgodbolt** [comment]
confirmed bug, looks like simple solution. it's eating all of the keypresses, and firefox takes that literally!

**Comment by micahgodbolt** [comment]
@pablonete i'd be happy to review a PR if you want to drop that preventDefault into the if statement and verify that this fixes it

**Comment by pablonete** [comment]
Thanks, @micahgodbolt. PR is ready for review: #5434
