### ISSUE TITLE
How can I only use one component instead of whole office-UI-fabric 

### ISSUE THREAD

**Issue by qingbolove** [OfficeDev/office-ui-fabric-react#5343]
hi,
I want to reuse **Calendar** component in our project, and I do not want to bring in a lot of dependency, could I only import one component(and its dependency)? Hope you provide a way to split components to seperate packages instead of make them as a whole.

Or could you provide a way for me to do this?

Thanks.

**Comment by kenotron** [comment]
The answer is highly dependent on how you're bundling your application. Some options are:

##webpack 4 - Be sure to turn on tree-shaking support##
1. make sure you're bundling ES6 imports / exports - there are some specifics about how to do that either in Typescript or Babel
2. turn on [ModuleConcatentationPlugin in webpack.config.js](https://webpack.js.org/plugins/module-concatenation-plugin/)
3. feel free then to do `import {Calendar} from 'office-ui-fabric-react'`

##webpack 1 / 2 - Be sure to import specific component## 
1. do `import {Calendar} from 'office-ui-fabric-react/lib/components/Calendar'`

Please reply with more information about your environment if the above answer doesn't address your needs!

**Comment by kenotron** [comment]
Re-open if you need more help!
