### ISSUE TITLE
How to fix the list of items of the Dropdown Component in a specific div?

### ISSUE THREAD

**Issue by 11302240** [OfficeDev/office-ui-fabric-react#5344]
I am using the component Dropdown, when I click on the icon I have the list of options, it is a div ms-layer which is add just before the end of body and it is remove when I click on the Dropdown to hide the list of options.

What I want to do, it's to put this div ms'layer in a specific div, for example, just after the div of Dropdown and not just before the end of body.

This is my code :
```
import * as React from 'react';
import {Dropdown, IDropdownOption} from 'office-ui-fabric-react/lib/Dropdown';

public render(): React.ReactElement<Props> {
return (
  <div>
          <Dropdown placeHolder={'Placeholder'} onChanged={this.handlefunction}
                    options={[
            {key: 'A', text: 'A'},
            {key: 'B', text: 'B'},
            {key: 'C', text: 'C'},]}/>
  </div>);
}
```

**Comment by Walium** [comment]
UP +1

**Comment by 11302240** [comment]
You have to define the selector of the function : Layer.setDefaultTarget(selector)

**Comment by Walium** [comment]
Thank you
