### ISSUE TITLE
Integrate PureComponent and debug-only safeguards

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#5346]
We have historically avoided PureComponent for a number of reasons. We're considering revisiting, or at minimum having a wiki page describing the pitfalls we'd hit doing so.

**Comment by micahgodbolt** [comment]
@kkjeer i know we talked about this a bit in the past, is there a followup here? Or just close the issue.

**Comment by kkjeer** [comment]
@micahgodbolt I don't think there is anything actionable here.
