### ISSUE TITLE
Datepicker: Convert to css-in-js

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#5365]

**Comment by micahgodbolt** [comment]
@bennettclark is this datepicker work just the input, or are you working on the calendar as well? If you are just focused on the picking portion, we also have an issue for the calendar.

#5307

**Comment by bennettclark** [comment]
@micahgodbolt per my conversation with @oengusmacinog who spoke with @Jahnp it doesn't sound like I'm the appropriate person to convert the calendar component to MergeStyles. The datepicker component is just limited to the input; the calendar component will require much more of a time commitment to convert.

**Comment by micahgodbolt** [comment]
No, I agree that this should be something tackled by the calendar team if possible. I reached out to @lorejoh12, but they don't currently have the work on their backlog. I"ll reach out to their PM to see if they have any plans to look at it.
