### ISSUE TITLE
Add icon looks terrible at 14px but ok at 15px within ContextualMenu and CommandBar

### ISSUE THREAD

**Issue by ericthompson** [OfficeDev/office-ui-fabric-react#537]
Comes from [this closed issue in Fabric Core](https://github.com/OfficeDev/office-ui-fabric-core/issues/835):

**Filed by @dzearing on November 7th, 2016**

ContextualMenu and CommandBar seem to use 14px, which looks like this:
![image](https://cloud.githubusercontent.com/assets/1420854/20228006/1a23bb68-a804-11e6-93ca-d47c30885055.png)

If I bump it to 15px (or 17 or 19 but not 13) it is clear:
![image](https://cloud.githubusercontent.com/assets/1420854/20228010/204b01c2-a804-11e6-8d17-57a48f5e7ac7.png)

But then the Upload icon has the opposite effect (clear at 14, blurry at 15...)

Anything that can be done at the font level? It's really ugly.

**Comment by dzearing** [comment]
I'm not really sure this makes sense to track here since there's nothing to change at this layer. Could we keep the issue tracked in core? (If we want to track.)

**Comment by dzearing** [comment]
Closing this one.
