### ISSUE TITLE
Callout not closing on clickout or scroll

### ISSUE THREAD

**Issue by danieloc** [OfficeDev/office-ui-fabric-react#5372]
### Bug Report 
 
- __Package version(s)__: 6.21.1
- __Browser and OS versions__: Chrome
 
#### Priorities and help requested:
 
Requested priority: Normal
 
#### Describe the issue:
 
The Callout Component is not closing on click out or scroll.
 
#### Actual behavior:
 
The Callout Component is not closing on click out or scroll.
 
#### Expected behavior:
 
Unless the props - preventDismissOnLostFocus or preventDismissOnScroll are set to true - the Callout should call `onDismiss` when scroll occurs or clickout occurs. 
 
### CodeSandbox
https://codesandbox.io/s/k53y5z8olr

**Comment by micahgodbolt** [comment]
You need to bubble up the onDismiss to where you are modifying state (in the index file). 

https://codesandbox.io/s/l3r25x21mm

**Comment by danieloc** [comment]
Thanks for the quick response, and sorry about the silly mistake. I've no idea how I did not see that.
