### ISSUE TITLE
Sticky TypeError cause Fabric UI render failed

### ISSUE THREAD

**Issue by luckyyd** [OfficeDev/office-ui-fabric-react#5383]
### Bug Report

- __Package version(s)__: 5.106.1
- __Browser and OS versions__: Chrome v67 and Edge 42

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable) MS privacy PDAM tool

#### Describe the issue:

There are cases when fabric ui failed to render icon and display incorrect style. 

#### Actual behavior:

![issue](https://user-images.githubusercontent.com/12855573/42068986-b27d2aaa-7b81-11e8-85b0-b3170448b04b.png)

#### Expected behavior:

![expected](https://user-images.githubusercontent.com/12855573/42069027-e942d95e-7b81-11e8-899a-04e182986be6.PNG)

**Comment by lynamemi** [comment]
It looks like you're having some css loading issues in general. Can you tell us more about when the styles / icons show up and when they don't?

**Comment by dzearing** [comment]
Please provide a network trace as well.

**Comment by luckyyd** [comment]
Hi @lynamemi, @dzearing 
I took some time to investigate why css loading failed. It turned out the error does not come from woff font file fetch issue, it is the Sticky component that cause the error. Sorry for the previous disturbing caused.

I used a DetailsList component with Sticky component as the header to stay in fixed position when scroll down. The error was shown when first loading the page sometimes (not every time, but still happened often, quiet tricky to repro), when reload the page (F5), the error disappeared.

![sticky](https://user-images.githubusercontent.com/12855573/42253384-1ded404a-7f74-11e8-8335-e5392f1c0f60.PNG)

When the error prompt, the icons will not render correctly.
Expected:
![icon render succeed](https://user-images.githubusercontent.com/12855573/42253458-8d765370-7f74-11e8-94fc-50b04f981533.PNG)

Actually:
![icon render failed](https://user-images.githubusercontent.com/12855573/42253414-479b7420-7f74-11e8-8264-d9a863ed59ba.PNG)

Hope you can help me investigate this issue, thanks!

**Comment by luckyyd** [comment]
Code snippet:
The basic way to use detailsList locked header:
![snippet](https://user-images.githubusercontent.com/12855573/42254145-e3b7b00a-7f77-11e8-980d-29498afff662.PNG)

**Comment by dzearing** [comment]
@leddie24 This would be your area.

**Comment by natalieethell** [comment]
@leddie24 thanks for tagging me in this, yes it should be! The error was due to a missing null check. I'll close this issue.
