### ISSUE TITLE
New Component: Text

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#5386]
### Code mockup/example

__Code Sample__

```

```

__Types__

| Name      | Type     | Default Value | Description |
|-----------|----------|---------------|-------------|
| className | string   |               | Optional class name to be added to the root |

## Steps

- [x] Themable (Component.base/Component.styles)
- [x] Unit tests
- [x] Visual tests
- [x] Documentation and examples
- [x] Keyboard Accessible
- [x] High Constrast Support
- [x] RTL Support
- [x] Design Review
- [x] API review
- [x] Public Preview
- [x] Ready for Publishing

**Comment by natalieethell** [comment]
The promotion of Text to the office-ui-fabric-react package is just waiting on some theming work, which should hopefully be covered in [this PR](https://github.com/OfficeDev/office-ui-fabric-react/pull/7325).

**Comment by micahgodbolt** [comment]
@natalieethell can you update this issue, mark off completed steps and add any next step todos?

**Comment by natalieethell** [comment]
@micahgodbolt will need @dzearing 's input before moving forward with this work.

**Comment by natalieethell** [comment]
Text was promoted to office-ui-fabric-react in this PR: https://github.com/OfficeDev/office-ui-fabric-react/pull/8070.

I'll work on adding some tests for it next!

**Comment by natalieethell** [comment]
I'll open a PR with the Text tests once PR https://github.com/OfficeDev/office-ui-fabric-react/pull/8265 is merged. Once that's merged, everything else is done!

One note: Text is only keyboard accessible when it renders an HTML element that is keyboard accessible.

**Comment by natalieethell** [comment]
Adding tests in this PR: https://github.com/OfficeDev/office-ui-fabric-react/pull/8286.
