### ISSUE TITLE
TextField `onChange` handler does not forward the `event`

### ISSUE THREAD

**Issue by justinwilaby** [OfficeDev/office-ui-fabric-react#5391]
If I want a single `onChange` event handler for multiple `TextField` components, I am unable to determine which component triggered the event since the [only argument is the value](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/TextField/TextField.tsx#L444)

This creates a black box that requires the developer to create multiple handlers or bound handlers to determine trivial info about the event. Also, this prevents the developer from using `event.preventDefault()`. Furthermore, it does not make a distinction between `onInput` and `onChange` which are fundamentally unique and mutually exclusive.

**Comment by Arthaclarius** [comment]
This is funny. 

The added "onChanged" to get only the values when it changes (onChange/onInput don't work), but if you put onKeyup you can register the event.

I mean, Why did they bind the onKeyup event to the input but no the onChange/onInput? 

It just doesn't make sense

**Comment by stewartadam** [comment]
Note the link above is now broken, [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/d061be9b4d5af089b29d045a3eda38736dd2ec8f/packages/office-ui-fabric-react/src/components/TextField/TextField.tsx#L444) is a working link from Git history and [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/TextField/TextField.base.tsx#L438) is the current location of said code.

**Comment by dzearing** [comment]
Yeah, not great! This should be fixed as far

Recommendations;

Add `onChange(ev: HTMLInputEvent, value: val)`, which lets you handle ev, and provides the current value if you want it.

Mark onChanged as deprecated.
