### ISSUE TITLE
Constraint Validation Not Reasonably Possible With Fabic Form Controls

### ISSUE THREAD

**Issue by justinwilaby** [OfficeDev/office-ui-fabric-react#5398]
[Constraint validation](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/HTML5/Constraint_validation) is not possible with the Fabric form elements thus creating a requirement on JS to do this lifting.

The `pattern` property on `input` elements is not accessible which makes the `oninvalid` event and the HTMLFormElement.reportValidity() impossible without gaining direct element access.

When a submit event is fired on a `<form>` element, calling `event.target.reportValidity()` returns true  even if form elements are invalid. I would have expected the `ITextFieldProps` to contain a `pattern` property that is then passed to the <input> element.

**Comment by natalieethell** [comment]
Hey @justinwilaby! So we do have a component called MaskedTextField that allows you to pass in a `mask` prop, where you can specify a masking string to define the mask's behavior. Here is an example on CodePen: https://codepen.io/naethell/pen/PBdKLP. We figure that this offers the same functionality as a `pattern` prop would offer.

I'll go ahead and close this issue, but let us know if you have any further questions and feel free to reopen the issue if the MaskedTextField does not seem sufficient to you.
