### ISSUE TITLE
[Feature Request] Provide better ways of styling a Dropdown (styles prop?)

### ISSUE THREAD

**Issue by Nimelrian** [OfficeDev/office-ui-fabric-react#5401]
**Describe the feature that you would like added**
Currently, styling a `Dropdown`'s elements via style overrides can only be done by overriding the individual onXRender functions. This is cumbersome, verbose, and reduces maintainability. Instead, like most other top level components, `Dropdown` should accept a `styles` prop to allow for style changes of individual child elements.

**What component or utility would this be added to**
Dropdown

**Have you discussed this feature with our team, and if so, who**
No

**Additional context/screenshots**
\-

**Comment by cliffkoh** [comment]
Closing as duplicate of #5366
