### ISSUE TITLE
Panel: Footer bottom is cut on Safari / iOS

### ISSUE THREAD

**Issue by samuelmtimbo** [OfficeDev/office-ui-fabric-react#5423]
### Bug Report 
 
- __Package version(s)__: v6.25.0
- __Browser and OS versions__: Safari / iOS
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes, but I need guidance on the ideal solution.
 
Requested priority: Normal
 
Products/sites affected: All
 
#### Describe the issue:

On Safari / iOS, the area of the layer is bigger than the visible browser area, which renders the bottom of the Panel cut. Check out the [Panel - Footer](https://developer.microsoft.com/en-us/fabric#/components/panel) example on OF official website using an iPad Pro:

![img_0004 3](https://user-images.githubusercontent.com/5302127/42192362-51ab33d6-7e1d-11e8-88e9-bfbd8cf4120d.PNG)

In Safari, the viewport size (`height: 100vh`) is bigger than the actual visible part of the page. [This seems to be a problem ever since 2015. ](https://nicolas-hoizey.com/2015/02/viewport-height-is-taller-than-the-visible-part-of-the-document-in-some-mobile-browsers.html)

**Comment by kkjeer** [comment]
Blocked by #5804
