### ISSUE TITLE
OfficeFabric/Link when converted to button does not follow the High Contrast Standards

### ISSUE THREAD

**Issue by nebhagat** [OfficeDev/office-ui-fabric-react#5431]
#### Describe the issue:
 
OfficeFabric/Link when converted to button, does not follow The high contrast standards.

Screenshot in high contrast is off
![normallink](https://user-images.githubusercontent.com/40790634/42210734-612a803e-7ecf-11e8-9ce1-c6cd6d17ac42.PNG)

Screenshot when high contrast white
![hcwlink](https://user-images.githubusercontent.com/40790634/42210790-878a93e0-7ecf-11e8-9c4f-30646404c5df.PNG)

Expected Behavior:
As per High Contrast Black Theme:
Links should be in yellow color.
As per High Contrast White Theme:
Links should be in blue color.

Actual Behavior:
In High Contrast Black Theme:
Link looks like normal text.
In High Contrast White Theme:
Link looks like normal text.

**Comment by micahgodbolt** [comment]
looks like this was fixed in #5392
