### ISSUE TITLE
FocusZone: bidirectional not working correctly in RTL

### ISSUE THREAD

**Issue by aishuiyer2001** [OfficeDev/office-ui-fabric-react#5438]
### Bug Report 
 
- __Package version(s)__: office-ui-fabric-react 6.25.0
- __Browser and OS versions__: Chrome 67.0.3396.99 (Official Build) (64-bit) and IE 11.2312.14393.0
 
 #### Requested priority: High
 
 #### Describe the issue:

On the 'FocusZone' component, setting the 'direction' attribute to 'FocusZoneDirection.bidirectional' does not work as expected for RTL languages (dir="RTL" has been set on the parent 'Fabric' component).

We have a grid of tiles very similar to the grids under 'Variants' here - https://developer.microsoft.com/en-us/fabric#/components/focuszone

Set focus on the first tile by clicking on it (first tile = first row, 'last' col - since this is RTL).
Hit right arrow - Nothing happens (expected since there is nothing on the right)
Hit left arrow - Focus shifts to tile below, rather than the tile on the left (<= BUG).

On the other hand, when you click on some tile in the middle (any tile with tiles on the left and right), then hitting the left arrow key takes you left, and right arrow key takes you right. (works as expected)
 
#### Expected behavior:
 
Setting focus on the first tile (first tile = first row, 'last' col - since this is RTL) and then
hitting 'left' arrow key - should shift focus to the left tile (and not to the tile below)

Just as a side note and if it helps at all - Changing the 'direction' to 'FocusZoneDirection.horizontal' fixes this (left arrow key) issue and displays the expected behavior for left and right arrow keys (but this option does not support vertical navigation - which is expected). 

But our use case requires both horizontal and vertical navigation to work and hence the bug report on 'FocusZoneDirection.bidirectional'.

**Comment by natalieethell** [comment]
Thanks for submitting this issue @aishuiyer2001! Looking into this. Here's a CodePen repro for reference: https://codepen.io/naethell/pen/wEgawK.

**Comment by natalieethell** [comment]
Just made a couple edits to my original comment above (I swapped LTR and RTL :)). It looks like the `targetRect.top` and `activeRect.bottom` issue may only be for LTR. RTL may have something different going on. Looking into this.
