### ISSUE TITLE
DetailsList: Narrator announces incorrect row count 

### ISSUE THREAD

**Issue by arunarokk** [OfficeDev/office-ui-fabric-react#5443]
### Bug Report 
 
- __Package version(s)__: (5.118.0)
- __Browser and OS versions__: (Edge & Win 10)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (High) 
 
Products/sites affected: (if applicable)
 
#### Describe the issue:
 
In Detailslist, rowcount is incorrectly announced by narrator, if table has 500 rows, it announces as 501 rows.
 
### If applicable, please provide a codepen repro:
 
https://developer.microsoft.com/en-us/fabric#/components/detailslist

**Comment by micahgodbolt** [comment]
This is by design as it is includeing the header.

https://github.com/OfficeDev/office-ui-fabric-react/issues/3067
