### ISSUE TITLE
Primary button is not adapting to high contrast

### ISSUE THREAD

**Issue by kmrrakesh** [OfficeDev/office-ui-fabric-react#5446]
### Bug Report 
 
- __Package version(s)__: (5.66.0)
- __Browser and OS versions__: (Edge and Windows 10)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)

Requested priority: (Normal) 
 
Products/sites affected: (PowerApps)

#### Describe the issue:
 
Primary button is not adapting the changes against High Contrast settings.

#### Actual behavior:
 
High Contrast Black - Button text Black and background White

High Contrast White -  Button text White and background Black

#### Expected behavior:
 
High Contrast Black - Button text White and background Black

High Contrast White - Button text Black and background White[](url)

**Comment by micahgodbolt** [comment]
High contrast Black

![image](https://user-images.githubusercontent.com/1434956/42335193-6fbe970a-8034-11e8-9a79-6a63d247b5dc.png)

high contrast white

![image](https://user-images.githubusercontent.com/1434956/42335222-7e48c0d4-8034-11e8-9555-d719c9a294f4.png)

I believe these are the expected styles, @betrue-final-final can you confirm these are correct? The expected colors you mention are applied to our standard button....we reverse those colors to make the primary variant different than the standard.

**Comment by betrue-final-final** [comment]
Yes, the current button is correct.
