### ISSUE TITLE
Dropdown with options having long text should have horizontal scrollbar when expanded

### ISSUE THREAD

**Issue by rajatagrawal-dev** [OfficeDev/office-ui-fabric-react#5448]
### Bug Report 
 
- __Package version(s)__: Latest
- __Browser and OS versions__: Edge, Chrome
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: High
 
Products/sites affected: Visual Studio Team Services
 
#### Describe the issue:
 
Dropdowns with long text options should have a horizontal scrollbar (when dropdown is in expanded state) so that complete option is visible.
Right now there doesn't seem to be any way to see the complete option text (either through scroll, tooltip, etc.). This behavior conflicts with accessibility requirements.
 
#### Actual behavior:
 
Options are truncated with the ellipsis if the text overflows, disabling the user to view the full text. 

#### Expected behavior:
 
A horizontal scrollbar for options will enable user to view the complete text.

**Comment by betrue-final-final** [comment]
Dropdowns need to be sized horizontally to fit the content. In the unlikely case that it doesn't have room, you may consider a different control, such as a choice group. The idea is for this control to be compact, and adding a horizontal scroll bar would make it very difficult to use.
