### ISSUE TITLE
TeachingBubble affects other component :focus background.

### ISSUE THREAD

**Issue by virulentt** [OfficeDev/office-ui-fabric-react#5449]
### Bug Report 
 
- __Package version(s)__: 6.25.2 - Bug has been introduced with 6.1.0
- __Browser and OS versions__: CEF v3239 / Windows 10 Latest version
 
#### Describe the issue:
 
Whenever i open a TeachingBubble, other component such as IconButton and Nav are affected as their :focus background gets set to the same blue as the TeachingBubble.
 
#### Actual behavior:

 Behavior only appears once the TeachingBubble is triggered, and it affects all "button".
Other components have a blue background when focused.
 
#### Expected behavior:
 
Other components should not be affected by the TeachingBubble.

[app-sample.zip](https://github.com/OfficeDev/office-ui-fabric-react/files/2164179/app-sample.zip)

**Comment by micahgodbolt** [comment]
We just did the conversion to styles, appears that the :focus style added by the teaching bubble isn't scoped to the teaching bubble's button, therefore adds style to anything focusing on the page.

https://codepen.io/micahgodbolt/pen/pKmXVG

![image](https://user-images.githubusercontent.com/1434956/42334604-909a93a4-8032-11e8-8bda-1deaf0fa2af8.png)

**Comment by dzearing** [comment]
We just merged a change and are in progress of publishing a new patched version. Sorry for the bug! We area also adjusting our css tooling to avoid this category of problem completely.
