### ISSUE TITLE
MessageBar not reflecting MessageBarType not changing div class when value is changed

### ISSUE THREAD

**Issue by danieloc** [OfficeDev/office-ui-fabric-react#5453]
### Bug Report 
 
- __Package version(s)__: (6.21.1)

NOT A BUG IN VERSION 6.2.0 so this was broken somewhere in between.

Edit - I looked and it's broken on 6.16->6.17
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (Low) 
 
#### Describe the issue:
 
MessageBar can be red when it is a MessageBarType.Success (Not at first but After dynamically changing type)
MessageBar can be green when it is a MessageBarType.Error (Not at first but After dynamically changing type)
The icons are correct, the props of the message bar show that it is of the correct MessageBarType but the class on the div does not reflect the state/props.
 
#### Actual behavior:
 
MessageBar should be green when it is a MessageBarType.Success
MessageBar should be red when it is a MessageBarType.Error
 
#### Expected behavior:
 
The messageBar can be the wrong color after changing the type. (I found this after changing a success message after logging out of app to a error message after bad login attempt).
 
### If applicable, please provide a codepen repro:
 
https://codesandbox.io/s/xojmp1m11o

**Comment by dzearing** [comment]
I repro'd this! This seems super confusing. I'll debug in.

**Comment by dzearing** [comment]
Found and fixed, will be merged shortly.

**Comment by danieloc** [comment]
:+1: Thanks
