### ISSUE TITLE
Commandbar: when the searchbox is added as faritems of the commandbar, its counted as menuitem

### ISSUE THREAD

**Issue by arunarokk** [OfficeDev/office-ui-fabric-react#5460]
### Bug Report 
 
- __Package version(s)__: (5.118.0)
- __Browser and OS versions__: (Edge & win 10)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (High) 
 
Products/sites affected: (if applicable)
 
#### Describe the issue:
When the searchbox is added as faritems of the commandbar, its counted as menuitem, but screen reader not reading its position when focused.
Example:
I ave added 3 menuitems in commandbar & searchbox as faritem, screen reader reading menuitems with total count 4, but when focused on searchbox its not reading its position as 4 of 4.

**Comment by micahgodbolt** [comment]
we have a completely new command bar in 6.0. Do you have plans to upgrade to that release soon? If so we'd like to make sure that we create a good solution for you in a non deprecated component.

**Comment by arunarokk** [comment]
@micahgodbolt , Yes we have plans to upgrade to 6.x soon.

**Comment by micahgodbolt** [comment]
5.x and 6.x are very different in the way they handle items on the commandbar. If this issue persists in 6.0 I can take a look at how better to support this screen reader scenario.
