### ISSUE TITLE
BasePicker mutates props

### ISSUE THREAD

**Issue by allobast** [OfficeDev/office-ui-fabric-react#5463]
### Bug Report 
 
- __Package version(s)__: 6.9.0
 
#### Describe the issue:
 
`BasePicker` component mutates the props it receives. It happens in `resetFocus` function on the line that does `items[items.length - 1].selected = true;`. It should copy items before assigning them to state/mutating them.
 
#### Actual behavior:
 
Because of that when using Redux store and passing items from the store to `BasePicker`, error about store mutation is thrown - the items that `onChange` method receives have been mutated.
 
#### Expected behavior:
 
`onChange` function should receive not mutated original `items` array.

**Comment by allobast** [comment]
Hello @dzearing, wonder if you could take a look at it please? Thank you!

**Comment by dzearing** [comment]
Gross. @joschect this is an antipattern. Could you please fix?

**Comment by joschect** [comment]
Yeah I'll take a look.

**Comment by joschect** [comment]
This is definitely a bug that we should get fixed.
