### ISSUE TITLE
An overflow button of details list doesnot disappear on closing of the menu

### ISSUE THREAD

**Issue by esshreem** [OfficeDev/office-ui-fabric-react#5467]
### Bug Report 
 
- __Package version(s)__:All
- __Browser and OS versions__: All

#### Priorities and help requested:

Are you willing to submit a PR to fix? No

Requested priority:Medium

Products/sites affected: Details List component .Please refer to microsoft one drive .
 
#### Describe the issue:

Attached the video .
I have attached the video for one drive but same happens in our application also.
The overflow button should disappear when we close the overflow menu of the details list
[Recording #3.zip](https://github.com/OfficeDev/office-ui-fabric-react/files/2170072/Recording.3.zip)

But it doesnot disappear.

#### Actual behavior:

Attached the video

#### Expected behavior:

The overflow button should disappear on closing of the overflow menu

**Comment by dzearing** [comment]
This has nothing to do with the DetailsList. You are clicking on the button, and therefore setting focus on it, which keeps it visible, as it should be for accessibility reasons. But this button isn't even provided by Fabric. The product team has to add it, so you should be investigating and addressing your own behavior that makes sense for your scenario.
