### ISSUE TITLE
ListOverview (Documentation for List Component) needs updating

### ISSUE THREAD

**Issue by JGibson2019** [OfficeDev/office-ui-fabric-react#5476]
**Describe the feature that you would like added**
I want the List Overview to describe how to format items when passing to IListProps when you opt not to use onRenderCell. All current examples use onRenderCell despite this being an optional member of the props; no examples feature a List created using just required props members. 

**What component or utility would this be added to**
List
**Have you discussed this feature with our team, and if so, who**
No
**Additional context/screenshots**
N/A

**Comment by natalieethell** [comment]
It looks like you solved this issue in your PR: #5489. Thanks @JGibson2019! I'll close this.
