### ISSUE TITLE
Theming: implement named settings in customizer, update styled/createComponent to reference named customizations

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#5480]
In a single "light" theme, you might have a dark header and a grey nav area. You might also have TeachingBubbles which turn the background `themePrimary` colored.

To make things more interested, in the `themePrimary` colored scenario, specific components take on specific overrides that might go beyond colors. DefaultButtons for example become outlined.

Customizer currently gives us a lot of flexibility you can provide global default prop values, or prop values scoped to a particular component type.

We want to extend this so that you can have a set of customizations that apply when requested by name.

For example, in the "light" themed example, you have the previous areas. Each area needs a different `ITheme` object, but potentially different `style` props, which might again be scoped to particular instances.

I would like us to be able to provide multipled named sets of customizations, and to request a specific customization by name. Here's a code example:

```
const LightThemeCustomizations = {
  default: { // name of the set
    settings: {
      theme: createTheme({ background: 'white' }),
      }
    }
  },

  inverted: {
    settings: {
      theme: createTheme({ background: 'black' })
    },
    scopedSettings: {
      DefaultButton: {
        styles: {
           root: {
             ...
        }
     }
   },

  themeColored: {
    settings: {
      theme: createTheme({ background: 'themePrimary' })
    }
  }
};

<Customizer set={LightThemeCustomizations}>
   ...
  <Header settingsName='inverted'>...</Header>
  <TeachingBubble settingsName='themeColored'>...</TeachingBubble>
</Customizer>
```

This allows us to avoid having a large number of styling overrides in particular sections of the application (see TeachingBubble styling as an example; "if default button is rendered inside, add a specific outline to it.")

This also means the entire set of customizations can be defined in one object, without wrapping individual components with Customizers.

**Comment by dzearing** [comment]
@phkuo would like to discuss this. Basically I want to enable your scenario without you having to wrap individual parts of the app in customizers.

**Comment by phkuo** [comment]
You have a comment that says `default` is the "name of the set" but in `<Customizer...>` you say `set={LightThemeCustomizations}`.

If the goal is to just remove the `<Customizer>`s everywhere, then can we not just mimic what resourceScope does? 
`
// somewhere in setup code
Customizations.applySettings({ 'headerEmphasisTheme': emphasisTheme });
...
// somewhere in a component
const themeToUse = Customizer.consume('headerEmphasisTheme');
Customizer.expose({ theme: themeToUse });
`

**Comment by phkuo** [comment]
Regarding theming customizations and TeachingBubble stuff, that is a separate discussion. Suffice to say, all such customizations should be encapsulated in the variants project. i.e. All a teaching bubble should do is pass in `getStrongVariant(theme)` instead of just `theme`.
