### ISSUE TITLE
Dropdown not showing tooltip on hover

### ISSUE THREAD

**Issue by mdmdakbar** [OfficeDev/office-ui-fabric-react#5482]
- __Package version(s)__: 5.112.1003
- __Browser and OS versions__: Chrome, Edge (I tried only on this)

Requested priority: High, blocking TFS 2018 U3 tenet signoff

Products/sites affected: (if applicable) VSTS

#### Describe the issue:

Dropdown title and dropdown options are not showing tooltip on hover when content is overflowing.
![image](https://user-images.githubusercontent.com/19491487/42434480-eda835f6-8370-11e8-98d1-296ccfd754cc.png)

#### Actual behavior:

Dropdown not showing tooltip when content overflows

#### Expected behavior:

Dropdown should show tooltip when content overflows

Codepen repro:

https://codepen.io/mdmdakbar/pen/dJeYeb (Codepen repro with version = 5.112.1003)

Also tried with latest office fabric version 6.27.0 but same issue is happening there too.

**Comment by cliffkoh** [comment]
@mdmdakbar In this specific scenario, since the width of each item is the same (or so it looks like), would setting a fixed width on the dropdown/callout be viable (thereby avoiding the overflow) as a mitigation?

**Comment by mdmdakbar** [comment]
Sure. But there are lot of places where this issue is coming and bug is being filed. Hope this will be fixed soon. Thanks

**Comment by natalieethell** [comment]
Hey @mdmdakbar! The changes I made in this PR should fix your issue: https://github.com/OfficeDev/office-ui-fabric-react/pull/5780. I'll go ahead and close this.
