### ISSUE TITLE
Split button Accessibility 

### ISSUE THREAD

**Issue by suztocco** [OfficeDev/office-ui-fabric-react#5494]
### Bug Report

- __Package version(s)__: Current
- __Browser and OS versions__: Not sure

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: OWA

#### Describe the issue:

**We did an accessibility review recently for Calendar and this issue came up:**

Unexpected behaviour for the split button when using a keyboard for non-sighted users.

#### Actual behavior:

When user activates reply all button observe instead of expanding the dropdown reply all option is triggered and redirected to reply all window which is inappropriate. The dropdown is getting expanded with Alt+down arrow which is not the way to interact with button and user can never use that keystroke. 

#### Expected behavior:

Expected is when user hits enter or space key on reply all button, dropdown should be expanded.

**Comment by natalieethell** [comment]
Hey @suztocco thanks for submitting this issue! I just spoke offline with @chang47 about the original change me made to support these keyboard events in [this PR](https://github.com/OfficeDev/office-ui-fabric-react/pull/4222/files#diff-ce8bee21b5adb504f4b308d824bb195eR558). 

Our accessibility expert says that alt + down arrow is an industry standard for expanding menus. So, we will maintain the behavior that we have, with enter triggering the primary action. 

I'll go ahead and close this issue, but feel free to let us know if you have any further questions.

**Comment by suztocco** [comment]
@natalieethell Thank you for following up.
