### ISSUE TITLE
Dropdown: List appears on top right corner for width < 480px

### ISSUE THREAD

**Issue by atneik** [OfficeDev/office-ui-fabric-react#55]
Repro steps:

1. Reduce width of screen < 480px
2. Open a dropdown
3. Dropdown list appears in top right corner

<img width="480" alt="screen shot 2016-08-03 at 12 22 22 pm" src="https://cloud.githubusercontent.com/assets/785361/17379047/64544816-5975-11e6-92cb-8b61addc570f.png">

**Comment by atneik** [comment]
This issue is not reproducing in MDL2 fixes

**Comment by dzearing** [comment]
I believe this has been fixed.
