### ISSUE TITLE
Dropdown label existed even didn't assign it

### ISSUE THREAD

**Issue by kkzhang** [OfficeDev/office-ui-fabric-react#550]
Dropdown's label behave differently compare to TextInput.
When no "label" provide to TextInput, label element is disappeared, but dropdown still preserve an empty label element, which take some spaces.

**Comment by dzearing** [comment]
Addressed in PR https://github.com/OfficeDev/office-ui-fabric-react/pull/551

**Comment by dzearing** [comment]
Published.
