### ISSUE TITLE
details list is setting  aria-colindex properties starting from 0 instead of 1

### ISSUE THREAD

**Issue by niadak** [OfficeDev/office-ui-fabric-react#5500]
### Bug Report 
 
- __Package version(s)__: 5.112.0
- __Browser and OS versions__: All Browser, Windows 10
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: VSTS
 
#### Describe the issue:
details list is setting aria-rowindex, and aria-colindex properties starting from 0 instead of 1. 
As per ARIA guideline "Authors MUST set the value for aria-colindex to an integer greater than or equal to 1".

Refer to https://www.w3.org/TR/wai-aria-1.1/#aria-colindex for details. Screen readers, inspect tools are 
misbehaving in terms of column number.
 
#### Actual behavior:
 
Column index is starting from 0 in DetailsList
 
#### Expected behavior:
 
Column index should start from 0 in DetailsList

**Comment by natalieethell** [comment]
It looks like the PR fixed the issue. I'll close this!
