### ISSUE TITLE
ComboBox Autofill empty string values

### ISSUE THREAD

**Issue by aslanovsergey** [OfficeDev/office-ui-fabric-react#5501]
### Bug Report 
 
- __Package version(s)__: (5.83.0)
- __Browser and OS versions__: (Google Chrome Version 67.0.3396.99, Windows 10)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (High) 
 
Products/sites affected: (App in enterprise)
 
#### Describe the issue:

When I use ComboBox in a table as cells and I have several items in this table and some of them have the same value for a column, for example empty string (I use custom values besides options).
For instance I want to change a value in ComboBox in the first row from "" to "Hi" then I sort the table and if another item with value "" turns out to be at the top of the table ComboBox shows value "Hi" instead of "" although value set to "". 
I looked at the children components states and found Autofill component having displayValue: "Hi"

**Comment by natalieethell** [comment]
Hey @aslanovsergey thanks for submitting this issue! I'm having a little trouble understanding the issue you're having. Is this using the `autoComplete` and/or `allowFreeform` props? Could you describe it in a little more detail, perhaps providing a CodePen? 

Here's a CodePen I've made if you'd like to work off this one: https://codepen.io/naethell/pen/BPvZbY.

Additionally, could this at all be related to this issue? https://github.com/OfficeDev/office-ui-fabric-react/issues/5778

**Comment by aslanovsergey** [comment]
Hi @natalieethell, thanks for template but I couldn't manage how to run the demo there so I created a new react app demo, you can find it here https://github.com/aslanovsergey/demo-for-office-ui-about-combobox-in-table

**Comment by kkjeer** [comment]
@aslanovsergey thanks for the demo! The issue with the Age column is that it passes a number to the ComboBox instead of a string. I changed line 24 in TableEditCell.tsx to `text={this.props.customValue.toString()}` (the `value` property is deprecated, please use the `text` property instead) and the Age column works the same way as the rest of the columns for me.

**Comment by aslanovsergey** [comment]
Hi @kkjeer, thanks for response.

Now we are getting closer, this time I added more people with empty age values, please take a look at my last commit https://github.com/aslanovsergey/demo-for-office-ui-about-combobox-in-table

To reproduce the issue just sort the age column until some people's empty age field get filled with someone's value

**Comment by micahgodbolt** [comment]
I was able to convert his repo into a codepen. Hope this helps the discussion. 

https://codepen.io/micahgodbolt/pen/RYrReb?editors=1010

**Comment by natalieethell** [comment]
Sorry for the delay here. Thanks @micahgodbolt ! @aslanovsergey it looks like the issue might lie in your `createOptionsForComboBox` method. Is there a reason you're populating the ComboBox values with values from all columns?

**Comment by aslanovsergey** [comment]
Hi @natalieethell because I want to provide options for every field in a row to choose from. That's exactly as I wanted. Why do you think this could case the issue?

**Comment by aslanovsergey** [comment]
> I was able to convert his repo into a codepen. Hope this helps the discussion.
> 
> https://codepen.io/micahgodbolt/pen/RYrReb?editors=1010

@micahgodbolt I took a look at the demo you build and doesn't have the issue? Did it have when built it?

**Comment by dzearing** [comment]
Given this is fixed in fabric 6, I will close. The SPFX upgrading to Fabric 6 is a separate issue being tracked on the SPFX end. This requires the team to upgrade to a newer React (16.3.1 or above) and (more importantly) TypeScript version (2.8 or above)

**Comment by dzearing** [comment]
Actually; if we can pinpoint the exact fix that changed the behavior, we could potentially cherrypick it into version 5 and get an update sooner.

@natalieethell could you maybe see if you can pinpoint the fix that addressed, and see if it is something we can cherrypick?

**Comment by natalieethell** [comment]
Thank you for your patience @aslanovsergey!

@dzearing It looks like it was this commit that updated ComboBox to allow for an empty string to be submitted: https://github.com/OfficeDev/office-ui-fabric-react/commit/491fb1b63c1c8b2554a9e5b5ccf4328e90e919e4. I just tried cherry picking it into v5, but got quite a few merge conflicts as there were several other changes made to ComboBox prior to this fix. It might be hard to cherry pick unless we want to take in the other changes too.

**Comment by dzearing** [comment]
(talking offline about options on how feasible it is to pick out the changes in 5.0)
