### ISSUE TITLE
TextField clearing value and validating on submit of containing form

### ISSUE THREAD

**Issue by kevinbargary** [OfficeDev/office-ui-fabric-react#5518]
### Bug Report 
 
- __Package version(s)__: 6.2.0 (can repro with  6.32.0 also)
- __Browser and OS versions__: Chrome 67.0.3396.99
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: N/A
 
#### Describe the issue:

When using the `TextField` component in a form, I'm noticing a new (didn't notice this two days ago) issue with the form. When state is set in the submit of the form, the `TextField` clears its content and re-validates even though I'm using `e.preventDefault` in `onSubmit` function
 
#### Actual behavior:

 On submitting a form the `TextField` component re-renders, clears the input value and re runs validation of the TextField
 
#### Expected behavior:

As with a normal input type the value should not be cleared on submit (once preventing default submit behavior) and the validation shouldn't re-run.
 
### If applicable, please provide a codepen repro:
 
https://codesandbox.io/s/llkk1qqj4q

**Comment by JasonGore** [comment]
This regression appears to have been introduced by #5349.
