### ISSUE TITLE
ComboBox with numeric key zero does not work

### ISSUE THREAD

**Issue by joerneu** [OfficeDev/office-ui-fabric-react#5520]
### Bug Report 
 
- __Package version(s)__: 6.23.0
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (High) 
 
#### Describe the issue:
 
The ComboBox is not usable with items with an numeric key of zero.
 
#### Actual behavior:
 
ComboBox is blank when `selectedKey={0}`.
 
#### Expected behavior:
 
A ComboBox with an entry with numeric key 0 should display the item.
 
### If applicable, please provide a codepen repro:

https://codepen.io/anon/pen/gjbdgM

**Comment by micahgodbolt** [comment]
we need to cast the number as a string internally
`key: string | number;`

need to update tests with a failing test (pass in 0), then fix it.

**Comment by dzearing** [comment]
This definitely is a bug, but you can work around it by providing a string key.

**Comment by micahgodbolt** [comment]
Seems #5705 is already a good starting point to finish this.
