### ISSUE TITLE
Persona with coinSize over 100 doesn't change initials size and alignment

### ISSUE THREAD

**Issue by dagoltz** [OfficeDev/office-ui-fabric-react#5521]
### Bug Report 
 
- __Package version(s)__: 6.22.0
- __Browser and OS versions__: Chrome 67 on MacOS X
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: High
 
Products/sites affected: Microsoft Cloud App Security and Azure Advanced Threat Protection
 
#### Describe the issue:
 
Using Persona component with a custom coin size (we need 150px) and initials.

#### Actual behavior:
 When an image is not available,  the initials are not properly sized nor aligned.
 They appear in the top of the coin with a smaller size.

 
#### Expected behavior:
 
Initials should be in a proper size to use with custom coin size or there should be a way to externally provide a size for the initials (the current "size" props is only good for up to 100px). 
### If applicable, please provide a codepen repro:
 
https://codepen.io/dagoltz/pen/VBYGXv

**Comment by micahgodbolt** [comment]
![image](https://user-images.githubusercontent.com/1434956/42660658-b88e219c-85e0-11e8-8ac6-d943d2b497e8.png)

**Comment by micahgodbolt** [comment]
Hey @Markionium can you take a quick look at this? If this is a regression lets make sure to add some visual tests.

**Comment by Markionium** [comment]
Yep I'll have a look over the weekend. Not sure if it is a regression (did we used to support custom sizes?) afaik the largest coin I've seen so far is 100.

**Comment by dagoltz** [comment]
This issue is also relevant for sizes lower than 100 that are custom.
For example: when coinSize is set to 60, you can't adjust the initials to fit - it's either 48 that is too small or 72 that is too big.

![image](https://user-images.githubusercontent.com/5446526/42712229-72489bfe-86f3-11e8-9f18-166752c457c8.png)

**Comment by Markionium** [comment]
@dagoltz It seems the current Persona component does not support rendering custom sizes outside of the supported ones. You can however provide a custom render function for the initials where you can size them the way you want. 

See the following codepen that is a modification of yours.
https://codepen.io/mpolak/pen/qyOGZe?editors=0010

That said I do think the fact that you can provide a custom coinSize but the text does not scale with it is confusing/unexpected behaviour. We should either scale the text or not allow you to provide non supported values.

I'll have a look to see if i can support that in a backwards compatible way :)

**Comment by dagoltz** [comment]
@Markionium thanks for the reply!
It seems that Persona doesn't support custom sizes at all so I don't really understand why it accepts coinSize.

Your approach will send me re-implementing Persona myself as now I see both the initials and the "showUnknownPersonaCoin" are broken when using coinSize:

![image](https://user-images.githubusercontent.com/5446526/42724959-9c065a26-8784-11e8-9bb6-25b50d989cce.png)

**Comment by Markionium** [comment]
Yep, i'm not saying you should do that, i provided that as a temporary fix as your put the urgency as high ;) You could use this if you need a temporary alternative and can't wait for a proper fix :)

I forgot to put the size override on `return <Icon iconName="Help" />;` in the snippet, if you do that the unknown persona will work. 

I agree it's weird that it takes any arbitrary number as the coinSize but then only supports a specific set of values :)
