### ISSUE TITLE
Breadcrumb last node should not be clickable

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#5522]
The last node of a breadcrumb is the location you are in, and should not be clickable.
When you are in the root of a library or OneDrive this causes that to register as an extra clickable element, causing issues with keyboarding and screenreader navigation.

**Comment by micahgodbolt** [comment]
If you don't provide a URL it won't be clickable. Is this just a OneDrive concern?
