### ISSUE TITLE
Refactor getFocusStyle() arguments into a options object.

### ISSUE THREAD

**Issue by jordandrako** [OfficeDev/office-ui-fabric-react#5525]
**Describe the feature that you would like added**

The function `getFocusStyle()` now has 7 arguments/options. 
https://github.com/OfficeDev/office-ui-fabric-react/blob/8afb6dcede9f9056357ce1d23e06197f458730c3/packages/styling/src/styles/getFocusStyle.ts#L20-L28
In order to change the last option, you need to put a lot of `undefined`s in, which starts turning into really ugly and hard to read code.
```js
getFocusStyle(theme, undefined, undefined, undefined, undefined, undefined, false)
```

Turning this into an options object would make it clearer to read and write, but would be a *breaking change*. I propose it be changed like so:

```js
export interface IGetFocusStyleOptions {
  theme: ITheme;
  inset?: number;
  position?: 'relative' | 'absolute';
  highContrastStyle?: IRawStyle;
  borderColor?: string;
  outlineColor?: string;
  isFocusedOnly?: boolean;
}

export function getFocusStyle( options: IGetFocusStyleOptions ): IRawStyle {
  const {
    theme,
    inset = 0,
    position = 'relative',
    highContrastStyle,
    borderColor = theme.palette.white,
    outlineColor = theme.palette.neutralSecondary,
    isFocusedOnly = true
  } = options;

  return {...}
}
```

This would turn the above example into:

```js
getFocusStyle({ theme: theme, isFocusedOnly: false })
```

**What component or utility would this be added to**

`getFocusStyle()`

**Have you discussed this feature with our team, and if so, who**

@phkuo 

**Additional context/screenshots**

https://github.com/OfficeDev/office-ui-fabric-react/pull/5399#issuecomment-403619784

**Comment by micahgodbolt** [comment]
@jordandrako still on your radar? Or decided to go another route?

**Comment by jordandrako** [comment]
@micahgodbolt I think I should target this for v7.0 since it's a breaking change, agreed?

**Comment by micahgodbolt** [comment]
Is it possible to create a new function and deprecate the old? We usually like to give people the ability to transition to the new approach vs a hard breaking change.

**Comment by jordandrako** [comment]
@micahgodbolt Definitely, the hardest part will be naming the new function :)

**Comment by micahgodbolt** [comment]
always is :-\
