### ISSUE TITLE
Styling utilities are, contrary to the docs, not utilizing memoization, leading to unnecessary style recomputations

### ISSUE THREAD

**Issue by Nimelrian** [OfficeDev/office-ui-fabric-react#5534]
### Bug Report 
 
- __Package version(s)__: 6.22.0
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal 
 
#### Describe the issue:
 
A lot of the styling utilities of Fabric are designed to minimize (or avoid) unnecessary recomputations. For example, `getClassNames` is ([according to the docs](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Component-Styling#styled-higher-order-component)) memoized. However, I just implemented a really simple custom component (see codepen link below) and realized that styles are always recomputed, even though the props don't change.
 
#### Actual behavior:
 
Passing the same styleProps n times causes my `getStyles` function to get called n times.
 
#### Expected behavior:
 
Passing the same styleProps causes my `getStyles` function to get called once
 
### If applicable, please provide a codepen repro:
 
https://codepen.io/nimelrian/pen/LBVGKV

**Comment by dzearing** [comment]
We'll update the docs. There is some re-computation currently. We started memoizing, but found significant issues with mutable objects/array comparison.s
