### ISSUE TITLE
DatePicker: should work without props

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#554]
```tsx
<DatePicker />
```

doesn't work.

**Comment by leddie24** [comment]
Hey @dzearing, could you clarify on expectations here?  Right now the only required prop for DatePicker is strings, which is (for the most part) the same for all DatePicker component examples.  Should we set the default props to be equal to that then? e.g: 

default props for strings should be equal to 
const DayPickerStrings = {
  months: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December'
  ],

  shortMonths: [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec'
  ],

  days: [
    'Sunday',
    'Monday',
    'Tuesday',
    'Wednesday',
    'Thursday',
    'Friday',
    'Saturday'
  ],

  shortDays: [
    'S',
    'M',
    'T',
    'W',
    'T',
    'F',
    'S'
  ],

  goToToday: 'Go to today'
};

**Comment by leddie24** [comment]
Fixed in #960
