### ISSUE TITLE
Separate Minified js and css into two separate files

### ISSUE THREAD

**Issue by craftytrickster** [OfficeDev/office-ui-fabric-react#5540]
Currently, in the office-ui-fabric-react.js bundled files, there seems to be a lot of embedded css, bloating the file size.

CSS and JavaScript files are different concerns, so it seems like they should be in different files. By combining them, you reduce the flexibility the end users have with their build process. If the end user of this library wants to have the files combined into a single entry, they can handle that themselves with their bundling tool.

**Comment by dzearing** [comment]
Thanks for the suggestion.

Are you using webpack? The current approach we have with css means:

You import { Spinner } from 'office-ui-fabric-react/lib/Spinner';

Only the spinner code and css will be in your bundle. The Toggle css will not be downloaded.

Using the pre-bundled files is possible, but not recommended. You aren't using every component in the library, likely, so why download everything? I'd only suggest using it for purposes where you don't care about your page load time (PLT), such as codepen examples. You should be using a modern bundler like webpack 4, which can support tree-shaking, to get the best PLT possible.

**Comment by craftytrickster** [comment]
I should have clarified. Yes, I am using webpack 3.x to bundle my project, and I am using fabric in the way you mentioned.

In the Spinner case, I would not expect to see any css in the file, it seems like it should be separated into a different css file. However, when I check my final webpack bundle, the fabric related css is added directly in the JS file, and I do not seem to have any control over it.

It is debatable whether users need the flexibility, but. in my case, it would definitely be helpful. Perhaps you can add some kind of optional build flag that, when toggled, prevents the css from being automatically inlined, giving the user the ability to import the required css files themselves

**Comment by dzearing** [comment]
@craftytrickster Just curious, what exactly is your use case? I'd like to better understand what you are trying to do before we figure out what the best solution is.

Thank you for your patience. :)

**Comment by craftytrickster** [comment]
@dzearing our bundle size is a bit big, and a decently large portion of it is due to fabric components. To be fair, fabric does a lot of the work for us, so the fact there is a lot of code implementing it is not surprising. 

Nevertheless, I was trying to experiment with ways to speed up our application startup and one possibility is to separate the css / js into different files, since browsers may be able to parse the css and js faster in parallel, then trying to parse everything in JS. I have not confirmed whether or not this would make a noticeable different, but it would be interested to be able to do so. 

I am currently on the 5.x line, perhaps in the new 6.x this may be less of an issue.
