### ISSUE TITLE
NormalPeoplePicker unique key

### ISSUE THREAD

**Issue by iliesalex89** [OfficeDev/office-ui-fabric-react#556]
Hello. I'm using "NormalPeoplePicker" component and after selecting an item from suggestions list, I receive this common react warning:

Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `NormalPeoplePicker`. See https://fb.me/react-warning-keys for more information.
    in Unknown (created by NormalPeoplePicker)

Let me know please if there is a workaround or something at this moment.

**Comment by joschect** [comment]
@iliesalex89 Hey! Thanks for pointing this out. I have a pr in now that will fix this. It should be in the next version.

**Comment by dzearing** [comment]
Published.
