### ISSUE TITLE
DetailsList does not load in AMD

### ISSUE THREAD

**Issue by joechung-msft** [OfficeDev/office-ui-fabric-react#5562]
### Bug Report 
 
- __Package version(s)__: 6.35.0
- __Browser and OS versions__: 
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No
 
Requested priority: (Blocking, High, Normal, Low) Blocking
 
Products/sites affected: (if applicable) Microsoft Flow, Azure Logic Apps
 
#### Describe the issue:
 
DetailsList does not load when loaded as an AMD module with require.js.

The Checkbox import in DetailsList.Basic.Example should be:
`import { Checkbox } from '../../../Checkbox';` (or `office-ui-fabric-react/lib/Checkbox`)

The Shimmer import in ShimmeredDetailsList.base should be:
`import { Shimmer, ShimmerElementsGroup, ShimmerElementType, IShimmerElement } from '../../Shimmer';` (or `office-ui-fabric-react/lib/Shimmer`)

The dragdrop import in DetailsHeader.base should be:
`import { DragDropHelper } from '../../utilities/dragdrop/index';`

#### Actual behavior:
 
Uncaught JavaScript errors thrown by require.js:
- `Uncaught Error: Script error for "office-ui-fabric-react/lib", needed by: office-ui-fabric-react/lib/components/DetailsList/examples/DetailsList.Basic.Example`
- `Uncaught Error: Script error for "office-ui-fabric-react/lib/components/Shimmer", needed by: office-ui-fabric-react/lib/components/DetailsList/ShimmeredDetailsList.base`
- `Uncaught Error: Script error for "office-ui-fabric-react/lib/utilities/dragdrop", needed by: office-ui-fabric-react/lib/components/DetailsList/DetailsHeader.base`
 
#### Expected behavior:
 
The details list should load and render correctly.
 
### If applicable, please provide a repro:
 
````html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://unpkg.com/office-ui-fabric-react@6.35.0/dist/css/fabric.min.css">
    <script src="https://unpkg.com/babel-polyfill/dist/polyfill.min.js"></script>
    <script src="https://unpkg.com/babel-standalone/babel.min.js"></script>
</head>
<body>
    <div id="app"></div>
    <script src="https://unpkg.com/requirejs/require.js"></script>
    <script type="text/babel" data-presets="es2015,react">
        require.config({
            packages: [
                { name: '@microsoft/load-themed-styles', location: 'https://unpkg.com/@microsoft/load-themed-styles/lib-amd', main: 'index.js' },
                { name: '@uifabric/icons', location: 'https://unpkg.com/@uifabric/icons/lib-amd', main: 'index.js' },
                { name: '@uifabric/merge-styles', location: 'https://unpkg.com/@uifabric/merge-styles/lib-amd', main: 'index.js' },
                { name: '@uifabric/styling', location: 'https://unpkg.com/@uifabric/styling/lib-amd', main: 'index.js' },
                { name: '@uifabric/utilities', location: 'https://unpkg.com/@uifabric/utilities/lib-amd', main: 'index.js' }
            ],
            paths: {
                'office-ui-fabric-react/lib': 'https://unpkg.com/office-ui-fabric-react@6.35.0/lib-amd',
                'prop-types': 'https://unpkg.com/prop-types/prop-types.min',
                'react': 'https://unpkg.com/react/umd/react.production.min',
                'react-dom': 'https://unpkg.com/react-dom/umd/react-dom.production.min',
                'tslib': 'https://unpkg.com/tslib/tslib'
            }
        })([
            'react',
            'react-dom',
            'office-ui-fabric-react/lib/components/DetailsList/examples/DetailsList.Basic.Example',
            'office-ui-fabric-react/lib/Fabric',
            'office-ui-fabric-react/lib/Icons'
        ], (
            React,
            { render },
            { DetailsListBasicExample },
            { Fabric },
            { initializeIcons }
        ) => {
            initializeIcons();

            function App() {
                return (
                    <Fabric>
                        <DetailsListBasicExample />
                    </Fabric>
                );
            }

            render(<App />, document.getElementById('app'));
        });
    </script>
</body>
</html>
````

**Comment by dzearing** [comment]
fixing.
