### ISSUE TITLE
SelectedItemsList does not load in AMD

### ISSUE THREAD

**Issue by joechung-msft** [OfficeDev/office-ui-fabric-react#5576]
### Bug Report 
 
- __Package version(s)__: 6.35.0
- __Browser and OS versions__: 
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No
 
Requested priority: (Blocking, High, Normal, Low) Normal
 
Products/sites affected: (if applicable) 
 
#### Describe the issue:
 
SelectedItemsList does not load when loaded as an AMD module with require.js.

The ExtendedPicker import in SelectedPeopleList.Basic.Example should be:
`import { people, groupOne, groupTwo } from '../../../ExtendedPicker';` (or `office-ui-fabric-react/lib/ExtendedPicker`)

The Persona import in ExtendedSelectedItem should be:
`import { Persona, PersonaSize } from '../../../../Persona';` (or `office-ui-fabric-react/lib/Persona`)

The Button import in ExtendedSelectedItem should be:
`import { IconButton } from '../../../../Button';` (or `office-ui-fabric-react/lib/Button`)

The Persona import in ExtendedPicker/examples/PeopleExampleData should be:
`mport { PersonaPresence } from '../../../Persona';` (or `office-ui-fabric-react/lib/Persona`)

#### Actual behavior:
 
Uncaught JavaScript errors thrown by require.js:
- `Uncaught Error: Script error for "office-ui-fabric-react/lib/components/ExtendedPicker", needed by: office-ui-fabric-react/lib/components/SelectedItemsList/examples/SelectedPeopleList.Basic.Example`
- `Uncaught Error: Script error for "office-ui-fabric-react/lib/components/Persona", needed by: office-ui-fabric-react/lib/components/SelectedItemsList/SelectedPeopleList/Items/ExtendedSelectedItem`
- `Uncaught Error: Script error for "office-ui-fabric-react/lib/components/Button", needed by: office-ui-fabric-react/lib/components/SelectedItemsList/SelectedPeopleList/Items/ExtendedSelectedItem`
- `Uncaught Error: Script error for "office-ui-fabric-react/lib/components/Persona", needed by: office-ui-fabric-react/lib/components/ExtendedPicker/examples/PeopleExampleData`
 
#### Expected behavior:
 
The selected items list should load and render correctly.
 
### If applicable, please provide a repro:
 
````html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://unpkg.com/office-ui-fabric-react@6.35.0/dist/css/fabric.min.css">
    <script src="https://unpkg.com/babel-polyfill/dist/polyfill.min.js"></script>
    <script src="https://unpkg.com/babel-standalone/babel.min.js"></script>
</head>
<body>
    <div id="app"></div>
    <script src="https://unpkg.com/requirejs/require.js"></script>
    <script type="text/babel" data-presets="es2015,react">
        require.config({
            packages: [
                { name: '@microsoft/load-themed-styles', location: 'https://unpkg.com/@microsoft/load-themed-styles/lib-amd', main: 'index.js' },
                { name: '@uifabric/icons', location: 'https://unpkg.com/@uifabric/icons/lib-amd', main: 'index.js' },
                { name: '@uifabric/merge-styles', location: 'https://unpkg.com/@uifabric/merge-styles/lib-amd', main: 'index.js' },
                { name: '@uifabric/styling', location: 'https://unpkg.com/@uifabric/styling/lib-amd', main: 'index.js' },
                { name: '@uifabric/utilities', location: 'https://unpkg.com/@uifabric/utilities/lib-amd', main: 'index.js' }
            ],
            paths: {
                'office-ui-fabric-react/lib': 'https://unpkg.com/office-ui-fabric-react@6.35.0/lib-amd',
                'prop-types': 'https://unpkg.com/prop-types/prop-types.min',
                'react': 'https://unpkg.com/react/umd/react.production.min',
                'react-dom': 'https://unpkg.com/react-dom/umd/react-dom.production.min',
                'tslib': 'https://unpkg.com/tslib/tslib'
            }
        })([
            'react',
            'react-dom',
            'office-ui-fabric-react/lib/components/SelectedItemsList/examples/SelectedPeopleList.Basic.Example',
            'office-ui-fabric-react/lib/Fabric',
            'office-ui-fabric-react/lib/Icons'
        ], (
            React,
            { render },
            { PeopleSelectedItemsListExample },
            { Fabric },
            { initializeIcons }
        ) => {
            initializeIcons();

            function App() {
                return (
                    <Fabric>
                        <PeopleSelectedItemsListExample />
                    </Fabric>
                );
            }

            render(<App />, document.getElementById('app'));
        });
    </script>
</body>
</html>
````

**Comment by dzearing** [comment]
fixing
