### ISSUE TITLE
DetailsList with JAWS: reads incorrect row number and column number

### ISSUE THREAD

**Issue by paraggangil** [OfficeDev/office-ui-fabric-react#5578]
### Bug Report 
 
- __Package version(s)__: (fill this out)
- __Browser and OS versions__: Chrome with JAWS screen reader
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: (if applicable)

**Comment by drunde13** [comment]
FYI this may be a Jaws regression. I see a similar behavior on Sencha grids in IE11 and Jaws where it's reading column headers with 65535 etc and not the labels. Using jaws 2018.1805.33 it repros, but using version 1710.42 it does not.

**Comment by prandall1122** [comment]
I was also facing this issue and am able reproduce this issue using a plain html table. 

https://s.codepen.io/prandall1122/debug/MLEaQL/DqkDdKzpENGk
