### ISSUE TITLE
react-scripts missing after install office-fabric

### ISSUE THREAD

**Issue by jiehu567** [OfficeDev/office-ui-fabric-react#5597]
### Bug Report 
 
- __Package version(s)__: office-ui-fabric-react@6.36.0
- __Browser and OS versions__: Chrome, windows 10
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (High) 
 
Products/sites affected: (if applicable)
 
#### Describe the issue:
 
follow the tutorial https://github.com/OfficeDev/office-ui-fabric-react/wiki/Sample-App
after install with:
`npm install office-ui-fabric-react --save`
 

#### Actual behavior:
 
npm start
will return ERROR:

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.

#### Expected behavior:
 
npm start will run successfully and open the web automatically.

**Comment by JasonGore** [comment]
This is due to a missing `npm install` step. I've updated [the wiki](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Sample-App) to address.
