### ISSUE TITLE
npm install fails during tests with "Enzyme Internal Error: configured enzyme adapter did not inherit from the En zymeAdapter base class"

### ISSUE THREAD

**Issue by lafe** [OfficeDev/office-ui-fabric-react#5598]
### Bug Report 
 
- __Package version(s)__: Commit 9370bcefb7252c96258825f97b7b9c9cd0d5c741
- __Browser and OS versions__: Windows 10 Enterprise (1803), npm Version 5.6.0, node 8.11.1
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
No, as I do not know where to start ;)
 
Requested priority: (Blocking, High, Normal, Low) 
High

Products/sites affected: (if applicable)
 
#### Describe the issue:
 
I am trying to install/build Office UI Fabric myself, so that I have a good environment to browse the source code in VS Code and to test things as well. I followed the commands on the main page:
```Bash
git clone https://github.com/OfficeDev/office-ui-fabric-react.git
npm install
```
The first steps of the `npm install` script work, but in step 4, there are errors that fail the whole build process:
```Bash
[@uifabric/utilities 11:30:55] Starting: jest
[ 'C:\\Code\\git\\office-ui-fabric-react\\scripts\\tasks\\jest-setup.js',
  'C:\\Code\\git\\office-ui-fabric-react\\packages\\utilities\\config\\tests.js'
 ]
 FAIL  src/autobind.test.ts
  ● Test suite failed to run

    Enzyme Internal Error: configured enzyme adapter did not inherit from the En
zymeAdapter base class

       8 |
       9 | // Configure enzyme.
    > 10 | configure({ adapter: new Adapter() });
         | ^
      11 |

      at validateAdapter (../../common/temp/node_modules/enzyme/build/validateAd
apter.js:17:11)
      at merge (../../common/temp/node_modules/enzyme/build/configuration.js:24:
42)
      at Object.<anonymous> (config/tests.js:10:1)
```

This crashes the whole build and stops the `npm install` command.
 
#### Actual behavior:
 
Build fails
 
#### Expected behavior:
 
`npm install` command completes successfully.

**Comment by cliffkoh** [comment]
@lafe sorry you're hitting this. Could you try this on another machine? You could also edit the validateAdapter.js and comment out line 17 (which does the throw) to see if this unblocks you.

(The last time someone hit this, the edit was good enough to get around this problem but the user hit a ton of other unit test failures which no one else encounters... in the end said user resorted to wiping the machine and after that, said user did not encounter any more problems).

**Comment by cliffkoh** [comment]
I am going to close this issue because I don't think there is anything we can do specifically here >.< (it does not help that we are unable to repro and therefore be able to investigate). Fabric is built daily on Windows/Mac/Linux boxes and this issue is not generally encountered...
