### ISSUE TITLE
ContexualMenu: Appears in top left corner upon keyboarding

### ISSUE THREAD

**Issue by atneik** [OfficeDev/office-ui-fabric-react#56]
Repro steps:
1. Keyboard to a interaction that brings up ContexualMenu
2. Hit Space/Enter
3. ContexualMenu appears in top left corner

<img width="1051" alt="screen shot 2016-08-03 at 12 23 05 pm" src="https://cloud.githubusercontent.com/assets/785361/17379322/b7e17142-5976-11e6-8850-b02f5f00f831.png">

**Comment by dzearing** [comment]
This has been resolved
