### ISSUE TITLE
Show initials / icon before image is loaded in Persona

### ISSUE THREAD

**Issue by dagoltz** [OfficeDev/office-ui-fabric-react#5601]
Sometimes it takes time for an image to load. We should display the user initials/user icon until the user image is loaded.
This exact behavior is in place in OWA.

This will be added to PersonaCoin
This was discussed with @micahgodbolt 

Original issue:
https://stackoverflow.com/questions/51351192/is-it-possible-to-have-initials-show-before-image-loads

**Comment by micahgodbolt** [comment]
My initial thought was a Boolean to turn this behavior on. Something like 

showInitialsUntilImageLoads

I'm guess we wouldn't want this behavior on by default as it might conflict with some of the image loading options, and would add a flash of rerendering in situations where its not necessary.

**Comment by dagoltz** [comment]
@micahgodbolt  sounds good, should this work when using imageShouldStartVisible?
It seems that you can only set one of them.

**Comment by micahgodbolt** [comment]
I'd have to really dig in to answer that 100%, but it seems there will be some mutually exclusive features. It might make sense to combine them all together (if you pass in all 3 mutually exclusive props, which one wins?). If you find there are 3 related, exclusive image treatment options, take a look at creating a single prop and deprecating the old ones.
