### ISSUE TITLE
Command Bar Item no text visible

### ISSUE THREAD

**Issue by Rainson12** [OfficeDev/office-ui-fabric-react#5602]
### Bug Report 
 I used `yo @microsoft/sharepoint` to create my project including fabric ui react components
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No): No
 
Requested priority: (Blocking, High, Normal, Low): Normal

 
#### Describe the issue:
When using the command bar control there is no text visible on the command bar buttons. Only the icon will be shown. 

 
#### Actual behavior:
Text of the command bar buttons is not visible 

 
#### Expected behavior:
 Text of the command bar button should be visible
 
Sample Code:
`export default class HelloWorld extends React.Component<IHelloWorldProps, {}> {
  public render(): React.ReactElement<IHelloWorldProps> {
    return (
      <CommandBar  items={[{ key: '1', text: 'asdf' }, { key: '2', text: 'asdf' }]} />
    );
  }
}
`

will result in 
![bug](https://user-images.githubusercontent.com/13119203/42830816-d82f26ee-89ec-11e8-8463-41822c31badc.png)

**Comment by micahgodbolt** [comment]
@Jahnp do we know which version of Fabric the sharepoint generator is using?

**Comment by Jahnp** [comment]
I'm not familiar with the @microsoft/sharepoint package. Adding @aditima and @pgonzal—thoughts on this?

**Comment by micahgodbolt** [comment]
@Rainson12 are you still having issues with this?

**Comment by paddymccallan** [comment]
The deprecated option for 'text' is 'name'. Solved the problem for me.
