### ISSUE TITLE
Need a way to invoke tooltip on demand.

### ISSUE THREAD

**Issue by piyusing** [OfficeDev/office-ui-fabric-react#5612]
**Describe the feature that you would like added**
We want to invoke tooltip, when the container holding the text overflows, upon certain user interaction.
In otherwords, having a ref to tooltip host exposing "invoke tooltip" kind of functionality would be useful. That way a user defined component using tooltip can invoke the exposed method - Using the reference to the underlying tooltiphost, to bring up tooltip as and when required.

**What component or utility would this be added to**
TooltipHost

**Have you discussed this feature with our team, and if so, who**

**Additional context/screenshots**

**Comment by micahgodbolt** [comment]
#5541 this functionality might be useful in our refactoring of the tooltip to include a tooltipmanager
