### ISSUE TITLE
New Component: Announcement

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#5615]
## Component Details

We need an announcement component to provide screen reader output for objects like progressIndicator, Spinner, and indeterminate progressIndicator.

#### Intended Package
OUFR

#### Code mockup/example

```

```

#### Component Ownership
Tactical Team

## Steps

- [x] initial implementation
- [ ] has unit tests
- [ ] has snapshot tests
- [ ] has documentation and examples
- [ ] Design/Accessibility Review
- [ ] API review
- [ ] Published to Fabric
- [ ] ProgressIndicator comments refer to Announced

**Comment by micahgodbolt** [comment]
@dzearing is this another instance where we'd want an announcement manager similar to what we want to do with tooltips?

**Comment by dzearing** [comment]
The idea would be to add an `Announced` component, which abstracts the guidance here:

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Live_Regions

We will provide clear documentation on when to have this read out, and how strings are provided. Right now, baking in aria live regions into atomic components is not the best idea, as:

1. The announcement needs to be localized.
2. We have no idea what the context is, or, if it makes sense to announce (for example, metadata like "storage remaining" ProgressIndicator usage might be not useful to read on page load.)
3. Anything done at the atomic component layer would be guessing, and could be the wrong guess which ends up making accessibility work worse.

**Comment by philipzloh** [comment]
Will the Announcement component be suitable for a toast notification in addition to a progress bar?

**Comment by micahgodbolt** [comment]
@philipzloh this is an accessibility component I believe. It wouldn't render any actual UI on the page.

**Comment by micahgodbolt** [comment]
Rank 1 because this is causing a11y issues that we don't have any other solutions for.

**Comment by micahgodbolt** [comment]
@natalieethell can you update this issue with the current status of this component?

**Comment by natalieethell** [comment]
Definitely! We have the initial prototype and documentation checked into the experiments package. It contains 3 scenario examples. @betrue-final-final and I are working on finalizing the documentation. Once we have that, I anticipate that the examples will be updated, and soon after a design/accessibility review we will port the component to the office-ui-fabric-react package.

I'm not sure yet what unit tests and snapshot tests will look like for Announced, but that's something we'll need to figure out as well.

**Comment by micahgodbolt** [comment]
@natalieethell please update this issue so we know what work is left before announcement graduates to OUFR.

**Comment by natalieethell** [comment]
@micahgodbolt Ben is still finalizing the documentation for Announced. After that, we can move forward with the other work.

**Comment by natalieethell** [comment]
Announced was promoted to OUFR in PR #8147.
