### ISSUE TITLE
Deprecate inactive prop in command bar, it is no longer being used

### ISSUE THREAD

**Issue by caradong** [OfficeDev/office-ui-fabric-react#5620]
### Bug Report 
- __Package version(s)__: 6.26.0
- __Browser and OS versions__: Chrome
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)
#### Describe the issue:
 Create an IContextualMenuItem in the Commandbar with **inactive: true** does not change the button to readonly.
 
Create an IContextualMenuItem: 
`private commandBarItems(): IContextualMenuItem[] {
let items: IContextualMenuItem[] = [];
items.push({
          key: 'totalItemsString',
          name: totalItemsString,
          inactive: true
        });
}
`

Create an command bar with this item:
`public render() {
return (
<CommandBar items={this.commandBarItems()} />
);
}`

As shown in this screenshot:

![image](https://user-images.githubusercontent.com/20460495/42908055-a8084b0a-8a94-11e8-9a02-7d34a0ae171d.png)

#### Actual behavior:
With inactive: true or without, the button is rendered same, i.e., not a readonly button
#### Expected behavior:
 With inactive: true, the button should be readonly with proiperties such as no hover effect, no pointer cursor, button should be disabled etcs.

**Comment by dzearing** [comment]
Preference:

Deprecate this feature. (Add `@deprecated` to comment)
Always make menu items focusable in a disabled state.

**Comment by micahgodbolt** [comment]
to followup, you can use 'allowDisabledFocus' from the button.types.ts to make the command bar buttons be disabled yet focusable (will need to add disabled as well).

**Comment by micahgodbolt** [comment]
https://codepen.io/micahgodbolt/pen/ZjBeQP

**Comment by caradong** [comment]
@micahgodbolt @dzearing thank you for the quick response.
