### ISSUE TITLE
using office-ui-fabric within dotnet core &&react application

### ISSUE THREAD

**Issue by afifoperantic** [OfficeDev/office-ui-fabric-react#5630]
I have a dotnet core && react application , in which I'd like to use Office-ui-fabric library .

**package.json**

    {
      "name": "app_fabric_test",
      "private": true,
      "version": "0.0.0",
      "devDependencies": {
        "@types/history": "4.6.0",
        "@types/react": "15.0.35",
        "@types/react-dom": "15.5.1",
        "@types/react-hot-loader": "3.0.3",
        "@types/react-router": "4.0.12",
        "@types/react-router-dom": "4.0.5",
        "@types/webpack-env": "1.13.0",
        "aspnet-webpack": "^2.0.1",
        "aspnet-webpack-react": "^3.0.0",
        "awesome-typescript-loader": "3.2.1",
        "bootstrap": "3.3.7",
        "css-loader": "0.28.4",
        "event-source-polyfill": "0.0.9",
        "extract-text-webpack-plugin": "2.1.2",
        "file-loader": "0.11.2",
        "isomorphic-fetch": "2.2.1",
        "jquery": "3.2.1",
        "json-loader": "0.5.4",
        "react": "15.6.1",
        "react-dom": "15.6.1",
        "react-hot-loader": "3.0.0-beta.7",
        "react-router-dom": "4.1.1",
        "style-loader": "0.18.2",
        "typescript": "2.4.1",
        "url-loader": "0.5.9",
        "webpack": "2.5.1",
        "webpack-hot-middleware": "2.18.2"
      },
      "dependencies": {
        "office-ui-fabric-react": "^6.37.1"
      }
    }

It works until I start to use the lib, I tried to import 

    import { DefaultButton, PrimaryButton } from 'office-ui-fabric-react/lib/Button';

So I get this result :

[![app][1]][1]

It seems that the page works fine in background, but it is hidden by the error message popup.

So How can I fix this problem ? otherwise how can I avoid this type of errors to be shown ?

thanks,

  [1]: https://i.stack.imgur.com/jAfvq.png

**Comment by dzearing** [comment]
A number of your other dependencies are quite old. Specifically, I believe the typescript build is very old.

Can you update:

typescript to 2.8 or greater
react
react-dom
@types/react
@types/react-dom
webpack to 4+

**Comment by afifoperantic** [comment]
Thank u @dzearing i tried but it didn't work . Can u please give me a valid package.json

**Comment by srfconsultores** [comment]
This problem has been fixed in update asp.net core 2.1 and visual studio 15.7
