### ISSUE TITLE
DetailsList doesn't have a way to render with a transparent background

### ISSUE THREAD

**Issue by paul-otten** [OfficeDev/office-ui-fabric-react#5635]
**Describe the feature that you would like added**
I would like to have a way to render DetailsList with a transparent background.

**What component or utility would this be added to**
DetailsList

**Have you discussed this feature with our team, and if so, who**
Discussed with Thomas Michon

**Additional context/screenshots**
Modern Sharepoint sites can have themes that set the background color of the page. Web parts do not have a way to access this background color. When web parts with a DetailsList component are rendered, the DetailsList doesn't look very good with the default white background. For an example of how this can be accomplished, I have already created a PR: https://github.com/OfficeDev/office-ui-fabric-react/pull/5634

**Comment by cliffkoh** [comment]
cc @kenotron

**Comment by KevinTCoughlin** [comment]
I tried to render a transparent `DetailsList` earlier. It is difficult if not impossible to do right now. One has to use custom renderers for row, header, and perhaps cell components in addition to `styles` on `DetailsList`. This is because each child component defines a background color that needs to be overridden for the entire component to be transparent. Perhaps themes would work here cc: @JasonGore which I admittedly haven't tried yet.

**Comment by JasonGore** [comment]
Sure, here's a method I was able to use with a theme and `Customizer`:
```tsx
const transparentTheme = createTheme({
  palette: {
    white: '#0',                 // used for default background color
    neutralLighter: '#0',        // used for hover background color
    neutralLight: '#0',          // used for selected background color
    neutralQuaternaryAlt: '#0'   // used for selected hover background color
  }
});
```
In the render function:
```tsx
<Customizer settings={{ theme: transparentTheme }}>
  <DetailsList
    items={items}
    columns={columns}
  />
</Customizer>

```

[Here is a CodePen](https://codepen.io/jasongore/pen/ReegZa) making use of this theme to make the various backgrounds transparent. I wrapped the whole example in a div with a red background, so if you comment out any of the theme lines or remove the `Customizer`, you can see the non-transparent background take effect. 

Now you could say that maybe `DetailsList` shouldn't be using palette for these colors (and I'd agree with you), but this is a method that will let you make the backgrounds transparent with `DetailsList` as implemented currently.

**Comment by JasonGore** [comment]
I'm sorry, I totally missed that this was a Fabric 5 issue until I saw the comment further down below.

**Comment by JasonGore** [comment]
The PR referenced above was created against officedev when it was 6.0, however, so I'm a bit confused. @paul-otten is this of any help for your question?

**Comment by paul-otten** [comment]
This was originally opened when fabric was in 6.0, but the question was to see if we could backport similar functionality to fabric 5. I think we can close this issue though since I have found a work around until we upgrade to fabric 6 soon.

**Comment by JasonGore** [comment]
Ok, thanks for following up. If you could provide a description of your workaround, I think it may be helpful if anybody else is searching for a resolution to this issue and comes across this one. Thanks!

**Comment by paul-otten** [comment]
The (fairly hacky) workaround was to create a CSS class that set the background to transparent and apply it to the parent element of the DetailsList. The CSS class was created in a way that it would have a high specificity and would over-write the background for any child elements. I did this by using the !important flag and by using some arbitrary CSS selectors to give it a high enough specificity that the style would override the styles of the element's children.

The downside to this is that it removes the hover highlighting for when users mouse over the rows in the DetailsList.
