### ISSUE TITLE
Fabric DropDown className should be on root element

### ISSUE THREAD

**Issue by chadsowald** [OfficeDev/office-ui-fabric-react#5636]
**Describe the feature that you would like added**
I added the className attribute to the Fabric Dropdown component.  When it renders, the className I added is on an element inside of the root of the Dropdown.  I expected it to be at the root and would request it moved there.  Since the className gets put inside the root, I cannot style the entire Dropdown without wrapping it in another element, which seems to defeat the purpose of supporting the className prop in the first place.

**What component or utility would this be added to**
Fabric DropDown: https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx#L212

**Have you discussed this feature with our team, and if so, who**
Nope

**Usage**
`<Dropdown className="myCustomClass" />`

**Dropdown code in question**
```
 <div className={css('ms-Dropdown-container')}>  <-- This should include the className passed to the component.
        ....
        <KeytipData keytipProps={keytipProps} disabled={disabled}>
          {(keytipAttributes: any): JSX.Element => (
            <div
              ....
              className={css(
                'ms-Dropdown',
                styles.root,
                className,      <--- This should be moved to be on the ms-Dropdown-container
                isOpen && 'is-open',
                disabled! && 'is-disabled ' + styles.rootIsDisabled,
                required! && 'is-required'
              )}
```

**Comment by micahgodbolt** [comment]
At this point, moving the location the className gets printed would cause some serious breaks for people that already ready on it, but we can support adding a custom className through our styles prop.

The dropdown is currently being converted to css-in-js by @cliffkoh.

Cliff, can you make sure the container gets a styling hook as well.

Once cliff is done you can do

```
<Dropdown styles={{
  container: [
    'my-container-classname',
    { background: 'blue' }
  ]
}} />
```
#5366

**Comment by micahgodbolt** [comment]
this is a dup of #5366 then. Closing this down.

**Comment by cliffkoh** [comment]
Reopening this because it isn't strictly a duplicate and doing a pure JS conversion would not have the hook be added.

**Comment by cliffkoh** [comment]
@chadsowald Thanks for reporting this. It is now formally fixed in #5661. "root" now points to the container and not to the Dropdown.

**Comment by chadsowald** [comment]
Thanks @cliffkoh!   Any idea when this change will land into the stable release and be available via npm update essentially?

**Comment by cliffkoh** [comment]
We publish weekdays at 3am PST, so the next 3am after the PR is merged.

**Comment by chadsowald** [comment]
@cliffkoh Feel free to close this issue whenever you're ready.  I'm good on my end.  Many thanks again.
