### ISSUE TITLE
NavBar component?

### ISSUE THREAD

**Issue by halallahh** [OfficeDev/office-ui-fabric-react#564]
No Navbar component?

**Comment by mikewheaton** [comment]
The [CommandBar](http://dev.office.com/fabric#/components/commandbar) can be used for both navigation and commanding. Does this suit your needs?

**Comment by willtrking** [comment]
I would imagine the component is closer to a Panel which floats left, and can be minified depending on screen size, and doesn't force every click externally to the panel to highlight the close button.

**Comment by ericthompson** [comment]
@willtrking - I think [this nav component](http://dev.office.com/fabric#/components/nav) may encompass what you're thinking of.

@halallahh - would that suit your needs?

**Comment by halallahh** [comment]
I think CommandBar suit what I need now just confused about the name. Thanks all.

**Comment by mikewheaton** [comment]
Glad to hear that, @halallahh – I'll close this issue. 😄
