### ISSUE TITLE
Add a hook to render a "no content" message when there are no items.

### ISSUE THREAD

**Issue by evantrimboli** [OfficeDev/office-ui-fabric-react#5653]
**Describe the feature that you would like added**
Add a way to render an empty message for List/DetailsList when there is no content. For example, if the user executes a search that returns no results in the details list, I would like to be able to display a message under the headers "No matches found".

**What component or utility would this be added to**
List/DetailsList

**Have you discussed this feature with our team, and if so, who**
N/A

**Additional context/screenshots**
From looking through the documentation it doesn't appear as though there's a rendering hook for when there are no items to render. I think if it were something similar to `onRenderDetailsHeader` for the body that would work well.

**Comment by dzearing** [comment]
I was just wondering if it makes sense here, if if you'd rather just replace the whole UI with no items experience, which just means you conditionalize the DetailsList rendering.

**Comment by evantrimboli** [comment]
I would expect the headers to render, somewhat similar to what Windows does with an empty folder, see attached:

![empty_folder](https://user-images.githubusercontent.com/197184/43106975-4aaeb2d0-8f1e-11e8-962c-19690bc4d885.png)

**Comment by dzearing** [comment]
Given this is immensely easy to do external to the component, and there is no value the detailslist would provide in rendering another div, and it has way too many props already, I'm close this one.

You can achieve the look above with your own conditional: https://codepen.io/dzearing/pen/RqVWEb
