### ISSUE TITLE
SearchBox autocomplete

### ISSUE THREAD

**Issue by richardzcode** [OfficeDev/office-ui-fabric-react#5660]
This is a question or feature request.

In docs, https://developer.microsoft.com/en-us/fabric#/components/searchbox, there is a section in best practices about Autocomplete.

> As the user enters a query string, they are provided with a dropdown of autocomplete suggestions or disambiguation options.

However I am not seeing anything in example and source code about autocomplete. I suppose it is not available out-of-box? If so, can we make a feature request for it?

Thanks,
Richard

**Comment by aramkoukia** [comment]
Any updates on this? I was also looking for a sample that does the autocomplete search, not just a textbox with the word 'Search' as placeholder!

**Comment by bishwenduk029** [comment]
I take this up and work on it for a new React component AutoComplete textbox

**Comment by IlyeniaMaksim** [comment]
Hi @bishwenduk029 Any news? Is it completed work?

**Comment by bishwenduk029** [comment]
@IlyeniaMaksim , so can i go ahead and create a new React Component altogether and push the same here? Any suggestions if you have on approaching the issue please do share with me, it would be of great help to me....thanks

**Comment by aramkoukia** [comment]
what I was looking for was Picker: [https://developer.microsoft.com/en-us/fabric#/components/pickers](https://developer.microsoft.com/en-us/fabric#/components/pickers)

So I don't need this search autocomplete

**Comment by darewreck54** [comment]
Hi, @bishwenduk029 I was wondering if you made any progress with this.  It's something that I'm looking interested in.  It seems that it's a common use case where whenever you do a search there is an associated auto suggestion.

It seems like it would be a merge of the picker logic into the search box.  Taking the logic that create the dropdown box from picker and all the associated actions. Perhaps also handle some level of debounce built into the component.

Thanks,
Derek

**Comment by bishwenduk029** [comment]
Hi, @darewreck54 I will continue working on the same, I got sidetracked assuming it is no longer needed, I think I understand what you are trying to implement, I will update ASAP...

**Comment by darewreck54** [comment]
It’s kind of a combination of the picker auto suggest but within search box and with debounce.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by darewreck54** [comment]
@bishwenduk029  By any chance do you have an ETA?

Thanks,
Derek

**Comment by bishwenduk029** [comment]
By Monday morning PST I will be able to share a working version.

**Comment by bishwenduk029** [comment]
Hello @darewreck54 , would Wednesday evening  PST do ? By then I will be able have a draft working version.

**Comment by bishwenduk029** [comment]
@darewreck54 as you suggested I am taking the logic from DropDown.base.tx for creating the dropdown when user enters a text into the input box. Should the trigger logic be invoked when clicks/enters, or as the user continues to type the dropdown should show result list? I am focusing the latter. Please do let me know in case this current approach needs changes

**Comment by darewreck54** [comment]
Choosing the latter is fine.  I would also include a prop parameter to specify the time for the debounce.  This will give the user the flexibility to control how many request are sent out.  Also a prop for the method that will be trigger to retrieve the results for the suggestion.  

Are you extending the existing SearchBox logic?

**Comment by bishwenduk029** [comment]
Yes derek with an additional prop to to activate the drop-down view of
results.

**Comment by bishwenduk029** [comment]
To put more specifically, activate the autosuggestion functionality based
on the props.

**Comment by darewreck54** [comment]
@bishwenduk029  Yeah, let me know when you have a version.  I'll be happy to test it out with the project i'm working on and give feedback! Thanks!

**Comment by bishwenduk029** [comment]
Hello @darewreck54 , while working on the SearchBox enhancement I just had an idea, if we leverage the idea of render props, then we can enhance the BasePicker component itself to accept any any kind of input target as props and render the same along with the suggestions triggered when user starts entering values into the input target.

Currently <BasePicker /> is tightly coupled with the Autofill input UI. Making this input as render props and passed from client code could improve its usability

We can modify the debounce logic in picker, to give control to the client via props. 
```
<BasePicker
    renderInputTarget={<SearchBox />}
   ...aditionalProps
>
<BasePicker>
```
Can you please review this logic once and let me know if this could be a viable solution?

**Comment by darewreck54** [comment]
I tired what you suggested but that doesn’t work. It looks like the renderinput target has no effect. The styling gets overrided by the basepicker style. You are basically left with the basepicker look and feel.



On Nov 20, 2018, at 6:41 PM, Bishwendu Kundu <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @darewreck54<https://github.com/darewreck54> , while working on the SearchBox enhancement I just had an idea, if we leverage the idea of render props, then we can enhance the BasePicker component itself to accept any any kind of input target as props and render the same along with the suggestions triggered when user starts entering values into the input target.

Currently is tightly coupled with the Autofill input UI. Making this input as render props and passed from client code could improve its usability

We can modify the debounce logic in picker, to give control to the client via props.

<BasePicker
    renderInputTarget={<SearchBox />}
   ...aditionalProps
>
<BasePicker>


Can you please review this logic once and let me know if this could be a viable solution?

**Comment by darewreck54** [comment]
perhaps a better route, is creating a component that has a Search Box and a callout/dropdown attached.  Then implement debounc and all that logic.

**Comment by bishwenduk029** [comment]
Hello Derek sorry but I am still continuing some build errors are impeding
me from raising a PR. Apologies for the inconvenience, I am working on
removing the build errors should have some working version by tomorrow

**Comment by darewreck54** [comment]
No worries. I actually started looking at how to possible implement as well. It seems that if you could possible take the code of a drop down and change the inner workings to use a search box. This has some advantages since the picker doesn’t have the style support that the search box has. Then move over some logic in the picker. The Dropbox uses a callout.

Someone pointed out that the big difference is the picker allows a user to pick more hen one item whereas a search only does one.
The picker logic still needs to be updated to support theming.

Let me know when you have the pr out and I can take a look.

Thanks
Derek


On Nov 21, 2018, at 7:51 PM, Bishwendu Kundu <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello Derek sorry but I am still continuing some build errors are impeding
me from raising a PR. Apologies for the inconvenience, I am working on
removing the build errors should have some working version by tomorrow

**Comment by AhmedAnwarHafez** [comment]
Any updates on this issue?

**Comment by Frost-on-Web** [comment]
This feature is waited by much of us.
(BTW I really really dislike this MS auto-bot behavior.)

**Comment by darewreck54** [comment]
I just wrote my own custom widget based off the search component and a callout with a list. 

Ill post the code later on but it won’t be till next week since I’m pretty busy.

**Comment by Frost-on-Web** [comment]
I thought about to make it myself too.

Personally I have used : https://github.com/reactjs/react-autocomplete
(sample here : https://jsbin.com/mipesawapi/edit?js,output)

It's working and easy to use.

But it seems obvious to me that feature should be natively in the "SearchBox" Office-Ui component. =/

Thanks for your help.

**Comment by somsharp** [comment]
I had a similar requirement and finally I created a custom component based on SearchBox and Callout. Source code and Sample can be found here https://github.com/somsharp/UIFabricAutoComplete

**Comment by ethanroday** [comment]
Just wanted to resurface this - it would be great if autocomplete were included as a part of the SearchBox component.
