### ISSUE TITLE
Add the Using Icons docs to website

### ISSUE THREAD

**Issue by atneik** [OfficeDev/office-ui-fabric-react#5669]
Now that we don't include Fabric icons by default in the bundle, its getting convoluted to use Icons. The request is to add [Using Icons](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Using-icons) information to the website too. I think it would be helpful to at least mention the default and point to the wiki at [Icon component](https://developer.microsoft.com/en-us/fabric#/components/icon) and [Icon Documentation](https://developer.microsoft.com/en-us/fabric#/styles/icons) 

The bug came from a partner who requested better documentation.

**Comment by Jahnp** [comment]
Feels like this could be collapsed into #5469, which tracks documenting the Fabric icons tool (including how to use icons) on both the wiki and the website. Thoughts?

**Comment by atneik** [comment]
Sounds good to me! I'll close this one and add the request to the #5469
