### ISSUE TITLE
Dropdown on changed keep initial selection when call setState() in parent component 

### ISSUE THREAD

**Issue by kkzhang** [OfficeDev/office-ui-fabric-react#567]
A component like this:

                    <Dropdown onChanged={this.onContentChange.bind(this, 'operator')}
                        options={
                            [
                                {key: "", text: "请选择"},
                                {key: "dianxin", text: "电信"},
                                {key: "liantong", text: "联通"},
                                {key: "yidong", text: "移动"},
                            ]
                        }
                    />

And this is the `onContentChange`

```
onContentChange(name, ...args){
    this.setState({[name]: args[0].key};
}
```

In this case, the dropdown alwasy show the intial option, which key is -1, although i have selected another option.
The weird thing is, the `args` in onContentChange was the right option we selected, it seems that when we call setState, the whole component re-render, and the Dropdown component incorrectly reset its own view to inital option.

The workaround is, re-assign selected option key to Dropdown's props `selectedKey`. But i think it is  an unexpected behavior, may be a bug.

**Comment by dzearing** [comment]
http://codepen.io/dzearing/pen/RoowBg?editors=0010

**Comment by dzearing** [comment]
@eliblock12  I just made a quick repro linked above. Can you take a look?

Hint; change the CDN url to fabric react to point to localhost:4321/dist/ and you can see if your fix addresses :)

**Comment by dzearing** [comment]
Will be published in next batch.
