### ISSUE TITLE
Upgrade to Rush 5

### ISSUE THREAD

**Issue by cliffkoh** [OfficeDev/office-ui-fabric-react#5670]
We should be staying evergreen with Rush. Hopefully, this will also get us Rush 5 improvements particularly around the scenarios involving `rush generate`.

**Comment by cliffkoh** [comment]
This has been done :)

**Comment by cliffkoh** [comment]
This has been done :)

**Comment by kkjeer** [comment]
Please close this issue.

**Comment by cliffkoh** [comment]
That sounds logical.

**Comment by cliffkoh** [comment]
Test
