### ISSUE TITLE
CI Improvement: Validate consumption of Fabric with a specific minbar of Typescript

### ISSUE THREAD

**Issue by cliffkoh** [OfficeDev/office-ui-fabric-react#5671]
We need to validate that the emitted Typescript code from OUFR is consumable downstream with a specified minbar of Typescript that we support.

**Comment by micahgodbolt** [comment]
Current suggestion is to drop the ts level in our vr test package to the min bar. Anything keeping that from working?

**Comment by cliffkoh** [comment]
Well, first of all, vr-tests doesn't actually do ANYTHING to build at the moment when we run rush-build. Maybe it will block screener if there's an incompatibility - but it would be storybook process that hits the issue and storybook has really bad console output...

The second issue is that it is unclear what side effects/problems will occur from having multiple versions of Typescript in the repo.

**Comment by micahgodbolt** [comment]
moving to modern TS in 7.0, this is a low pri. Closing.
