### ISSUE TITLE
`getGlobalClassNames` usage in JS styling is a bit of a ticking time bomb

### ISSUE THREAD

**Issue by cliffkoh** [OfficeDev/office-ui-fabric-react#5672]
#### Describe the issue:

There is widespread use of global classnames in selectors at the moment. The whole point of using `getGlobalClassNames` from `oufr/lib/Styling` is so that users can choose to turn off globalClassNames at a single point. This however would cause widespread breakage because the global classnames are used in many component's base JS styles in selectors (given we lack a better mechanism around this atm).
 
#### Expected fix:
 
One possible fix is that when `getGlobalClassNames` is turned off, we should not return an empty string but return a system generated string instead.

**Comment by dzearing** [comment]
Thanks for picking this up!

**Comment by micahgodbolt** [comment]
adding these to UI fabric project for better visibility
