### ISSUE TITLE
Text fields focus/edit issue in DetailsList

### ISSUE THREAD

**Issue by irvalchev** [OfficeDev/office-ui-fabric-react#5675]
### Bug Report 
 
- __Package version(s)__: 6.39.1 and previous
- __Browser and OS versions__: IE, Edge, FF
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Low
 
#### Describe the issue:

 The content of text fields (input or textarea) inside of a details list cell cannot be selected. Two issues:

- The mouse place selection only works for the initial click. Additionally, it is not possible to select parts of the content.
- The right/left keys select the sibling input elements and it is not possible to navigate in the content of the field.
 
In Chrome the first point is not a problem. A workaround for the second is to disable the event propagation of the right/left arrows click.

I was not able to find a way to fix it (esp the 2nd point). It appears to be related with the FocusZone, but I was not able to find out what exactly happens.

**Comment by jlubben** [comment]
seconded I am putting text inputs inside of my detailslist and can not tab between them. I believe focuszone is also the cause.

I've noticed that when tabbing through a website that uses a detailslist table, I am able to tab to the top left corner component, and then to the left most column on the first row. Beyond that, hitting tab goes to the next table. I can't even access the second row via tabbing? weird.

**Comment by irvalchev** [comment]
> For point two, generally one tabs to controls, but inside of controls you use arrow keys. If this weren't the case you would get an indeterminate amount of tab stops, resulting in horrible navigation.

I am not sure that I understand what you are saying. The issue at the moment is that the left/right keys actually tab to the next input element instead of navigating inside of the text field

**Comment by betrue-final-final** [comment]
So you are using the word "tab" for arrow keys? Tab is a very specific action and I would say "move" to reduce confusion.

I'll take a look at the bug and see if I can figure out what you mean.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dzearing** [comment]
https://codepen.io/dzearing/pen/wEGRjJ?editors=1010

This appears to be working fine now.
