### ISSUE TITLE
MessageBar text not inheriting `fontFamily` from <Fabric> component

### ISSUE THREAD

**Issue by kevinbargary** [OfficeDev/office-ui-fabric-react#5676]
### Bug Report 
 
- __Package version(s)__: 6.39.2
- __Browser and OS versions__: Chrome (67.0.3396.99) & Windows 10
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix?  No
 
Requested priority: Normal
 
Products/sites affected: (if applicable)
 
#### Describe the issue:
 
Trying to remove usage of the Segoe UI font for components using the `<Fabric>` component to set the `fontFamily`
 
#### Actual behavior:
 
MessageBar inner text does not inherit font-family
 
#### Expected behavior:
 
To be able to inherit `fontFamily` for all sub-components of `<Fabric>` to remove _all_ usages of the Segoe UI font
 
### If applicable, please provide a codepen repro:
 
https://codesandbox.io/s/z6vnvz7024

**Comment by kkjeer** [comment]
MessageBar does not inherit from fonts set by CSS. Instead, it uses the small font defined in the theme (theme.fonts.small). To change the font family of the MessageBar text, you can use:

`import { loadTheme } from '@uifabric/styling';`
`loadTheme({ fonts: { small: { fontFamily: 'Comic Sans MS' } } });`

@dzearing what is our approach here? Should MessageBar inherit fonts from CSS or from the theme? Some of our components (e.g. BaseButton, Persona) use the font family provided by the theme, and some (e.g. DefaultButton, Label) inherit from CSS.

**Comment by khmakoto** [comment]
@kevinbargary I don't think this is an issue anymore. Could you confirm if you are still encountering this?
