### ISSUE TITLE
Datepicker: Warning: `value` prop on `input` should not be null

### ISSUE THREAD

**Issue by kkzhang** [OfficeDev/office-ui-fabric-react#568]
When click Datepicker component, an warning shows:

> Warning: `value` prop on `input` should not be null. Consider using the empty string to clear the component or `undefined` for uncontrolled components.

version: "office-ui-fabric-react": "^0.70.0"

**Comment by dzearing** [comment]
This was fixed in today's published bits.

**Comment by dzearing** [comment]
See issue https://github.com/OfficeDev/office-ui-fabric-react/issues/541
See PR: https://github.com/OfficeDev/office-ui-fabric-react/pull/553

published in 70.1 and above. :)

**Comment by kkzhang** [comment]
@dzearing 
After upgraded to 70.1, error messages were disappeared, but a new bug comes out. TextField in Datepicker didn't show current selectd value, looks like a same symptom of #567

**Comment by dzearing** [comment]
I believe this is tracked in a separate bug I opened. We'll sort this out.
