### ISSUE TITLE
merge-styles: should properties like background/backgroundColor conflate?

### ISSUE THREAD

**Issue by cliffkoh** [OfficeDev/office-ui-fabric-react#5687]
#### Describe the issue:

A component's baseStyles defines `{ background: 'red' }`

A user provides props styles of `{ backgroundColor: 'green' }`
 
#### Actual behavior:
 
`background: red` wins and background color is red.
 
#### Expected behavior:
 
User provided style to win - background color is green.
 
This can be really surprising and unintuitive to the user, and basically forces the user to use `background` as well...

### If applicable, please provide a codepen repro:
Let me know if you truly need a codepen repro ;)

**Comment by micahgodbolt** [comment]
not going to do this...it'll be up to the user to work this out (per david)
