### ISSUE TITLE
Loading a new theme does not update components that return false on shouldComponentUpdate

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#5691]
We are seeing with the new `styled` helper that they will pull the theme from context. However, if the contextual theme mutates, we aren't getting re-rendered when components are hosted within a parent which avoids a re-render (like `List`). This ends up breaking scenarios where we chose a live theme and expect the page to render with that theme.

Proposal:

We effectively make the theme observable (through change callback) and allow styled components to observe and repaint when needed.

It's not perfect, and I hate the word "observable". We need to research why something depending on context isn't repainting.

It might be resolvable with the new context, I'm not 100% sure if the problem only exists in legacy context.

Codepen repro:
https://codepen.io/dzearing/pen/PeNrzB

**Comment by dzearing** [comment]
We're blocked on enzyme updating to consume the new react context.

**Comment by phkuo** [comment]
@dzearing Is there an ETA on this? It would be great if we could get this in by the end of August.

**Comment by micahgodbolt** [comment]
waiting on converting layer over to portals before we can make this switch, otherwise we lose theming in anything inside a layer. Layer conversion is happening at #4849
