### ISSUE TITLE
Panel: isBlocking attribute doesn't remove overlay

### ISSUE THREAD

**Issue by willtrking** [OfficeDev/office-ui-fabric-react#570]
As the title states the isBlocking Panel attribute doesn't correctly remove the overlay. It looks like the overlay is hardcoded into the render function of the Panel, even though a few lines above there is a check for the blocking attribute.

https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Panel/Panel.tsx#L114

From there you can see the Overlay being returned, and the ```overlay``` variable declared a few lines above being ignored.

**Comment by dzearing** [comment]
I'm not 100% sure what the expectation here is. I looked at the code mentioned and am confused by it. Matt could you maybe take a look?

**Comment by dzearing** [comment]
This should be resolved in the next publish.
