### ISSUE TITLE
DetailsList onRenderColumnHeaderTooltip does not work beyond version 6.18.0

### ISSUE THREAD

**Issue by kadevu** [OfficeDev/office-ui-fabric-react#5703]
### Bug Report 
 
- __Package version(s)__: 6.18.1
- __Browser and OS versions__: All browsers
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal
  
#### Describe the issue:
 
We have used the DetailsList and used the **onRenderDetailsHeader** (which internally calls **onRenderColumnHeaderTooltip**) to customize the header to add a tooltip. It worked when I was using officefabric version **6.1.2** but when upgraded to version beyond 6.18.1 the implementation is broken and I am not able to see the tooltip.
 
#### Actual behavior:
 
Not able to customize the header using onRenderDetailsHeader 
 
#### Expected behavior:
 
Should be able to customize the tooltip in the header using onRenderDetailsHeader prop

**Comment by kadevu** [comment]
I digged into the code and found that the issue is in file **https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.base.tsx** line 267, where onRenderColumnHeaderTooltip props is not being sent to DetailsColumn.

**Comment by dzearing** [comment]
If you'd like to submit a PR to address, please do.

**Comment by KevinTCoughlin** [comment]
@kadevu I'm unable to get this working as you've described in `office-ui-fabric-react@6.1.2`. Here's a Codepen using OUIFR **6.1.2**: https://codepen.io/kevintcoughlin/pen/QZZNRv?editors=1010.

Can you fork that Codepen and add the code you were using to get the tooltip to work `office-ui-fabric-react@6.1.2`? It would greatly help me track-down the regression and understand the default behavior. I'm not yet sure its a prop propagation issue, but rather a change in defaults / conditionals.

On latest `master`, I'm able to render the tooltip **iff** `onRenderColumnHeaderTooltip` && `ariaLabelForSelectAllCheckbox` are supplied when custom rendering the `DetailsHeader` via `onRenderDetailsHeader`.

```diff
diff --git a/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Basic.Example.tsx b/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Basic.Example.tsx
index a4f13c48d..9eb649ea1 100644
--- a/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Basic.Example.tsx
+++ b/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Basic.Example.tsx
@@ -4,6 +4,9 @@ import { DetailsList, DetailsListLayoutMode, Selection, IColumn, IDetailsList }
 import { MarqueeSelection } from 'office-ui-fabric-react/lib/MarqueeSelection';
 import { Checkbox } from 'office-ui-fabric-react/lib/Checkbox';
 import { createRef } from 'office-ui-fabric-react/lib/Utilities';
+import { IDetailsHeaderProps } from '../DetailsList.types';
+import { DetailsHeader } from '../DetailsHeader';
+import { ITooltipHostProps, TooltipHost } from '../../Tooltip';
 
 const _items: any[] = [];
 
@@ -81,6 +84,7 @@ export class DetailsListBasicExample extends React.Component<
         <MarqueeSelection selection={this._selection}>
           <DetailsList
             componentRef={this._detailsList}
+            onRenderDetailsHeader={this._renderCustomHeader}
             items={items}
             columns={_columns}
             setKey="set"
@@ -103,6 +107,17 @@ export class DetailsListBasicExample extends React.Component<
     }
   }
 
+  private _renderCustomHeader(props: IDetailsHeaderProps): JSX.Element {
+    return (
+      <DetailsHeader
+        {...props}
+        // tslint:disable-next-line:jsx-no-lambda
+        onRenderColumnHeaderTooltip={(tooltipHostProps: ITooltipHostProps) => <TooltipHost {...tooltipHostProps} />}
+        ariaLabelForSelectAllCheckbox="Toggle selection for all items"
+      />
+    );
+  }
+
   private _getSelectionDetails(): string {
     const selectionCount = this._selection.getSelectedCount();
 ```

Here's the code in question at `6.1.2` and `master`:

* **6.1.2**: https://github.com/OfficeDev/office-ui-fabric-react/blob/d72775e16645c063517af1b79a33628064cd23ec/packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.tsx#L168
* **master**: https://github.com/OfficeDev/office-ui-fabric-react/blob/0880b0d495ff0b671df5af4a469a9276786a76dc/packages/office-ui-fabric-react/src/components/DetailsList/DetailsHeader.base.tsx#L255

**Comment by KevinTCoughlin** [comment]
Re-opening as this is _still_ occurring. The tooltips should render for both the "Select all" column header cell AND other data field column header cells. It _currently_ only renders when provided for the "Select all" column header cell using the diff mentioned above.

**Comment by KevinTCoughlin** [comment]
Thanks for raising this issue @kadevu. I've opened a PR to fix this regression.

**Comment by kadevu** [comment]
Apologies for missing out on the earlier conversation, my outlook rules are messed up. Thank you @KevinTCoughlin for the fix.
