### ISSUE TITLE
SearchBox: When rendered with a panel, onFocusCapture never fires

### ISSUE THREAD

**Issue by quanglefed** [OfficeDev/office-ui-fabric-react#5704]
### Bug Report 
 
- __Package version(s)__: 5.84.0
- __Browser and OS versions__: FireFox
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: High
 
Products/sites affected: https://grammarly-bug.herokuapp.com/
 
#### Describe the issue:
 We lose Searchbox animinations and focus/active state

 
#### Actual behavior:
 When we focus to Searchbox, their animations are not played - and not display the cursor 

 
#### Expected behavior:
 When we focus to Searchbox, their animations are played - and display the cursor 

 
### If applicable, please provide a codepen repro:
 https://grammarly-bug.herokuapp.com/

Note: it works properly if we remove 'isHiddenOnDismiss' option
Thanks

**Comment by micahgodbolt** [comment]
Any chance you can put this into a codepen? That way we can see exactly what code you used to create this .

**Comment by quangleminhvn** [comment]
Hi @micahgodbolt, please take a loot a codepen as below:
https://codepen.io/quanglefed/pen/gjopPJ
on FF the cursor disappears
on Chrome and FF - the animation is not displayed

**Comment by micahgodbolt** [comment]
Searchbox uses onFocusCapture to trigger the 'hasFocus' state. That state drives the UI change. Seems the panel is blocking that event from triggering. 

![image](https://user-images.githubusercontent.com/1434956/43408132-60ab7ca6-93d5-11e8-8ed3-80ecabb3cd88.png)

**Comment by natalieethell** [comment]
I can investigate this issue a little more. It seems like the FocusTrapZone within the Panel is messing with the focus of the SearchBox. When I add `focusTrapZoneProps={{ forceFocusInsideTrap: false }}` to the Panel's props, the SearchBox animation works properly. I'll see if we can get around this problem.
