### ISSUE TITLE
ReactJS is available in Nuget for MVC/Core. Please add Fabric as a Nuget as well

### ISSUE THREAD

**Issue by RedBlue1776** [OfficeDev/office-ui-fabric-react#5712]
The following was closed based on the incorrect theory that ReactJS doesn't exist on Nuget.
https://github.com/OfficeDev/office-ui-fabric-react/issues/5008

Here is the link to the Nuget with instructions on how to make it run on MacOS Core (Visual Studio is an option too)
https://reactjs.net/guides/chakracore.html

Since the prerequisite is there, can we get a Nuget package (or some instruction) on how to integrate Fabric into our Visual Studio projects?

**Comment by micahgodbolt** [comment]
The example app linked to from that chackracore page has a package.json file with dependencies. Are you able to add Fabric there?
