### ISSUE TITLE
loadTheme doesn't change global CSS

### ISSUE THREAD

**Issue by papigers** [OfficeDev/office-ui-fabric-react#5713]
Not really sure if this is a bug or intended behavior.

### Bug Report 
 
- __Package version(s)__: 6.39.1
- __Browser and OS versions__: Chrome 68.0.3440.75 Windows 10
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal
 
#### Describe the issue:
 
Calling loadTheme to change the default theme doesn't affect page CSS.
 
#### Actual behavior:
 
Page CSS doesn't get affected. See [example](https://codepen.io/papigers93/pen/OwOMre). Body's background color doesn't get changed.
 
#### Expected behavior:
 
Theme change should change page CSS to match the theme, like in the official website's [Theme Generator](https://developer.microsoft.com/en-us/fabric#/styles/themegenerator).
I would expect at least the <Fabric /> container to change its background color, if not the whole page.
 
### If applicable, please provide a codepen repro:
 https://codepen.io/papigers93/pen/OwOMre

**Comment by micahgodbolt** [comment]
I believe that the background changing in that generator page is something done manually (using inline styles). It's not something that automatically happens. i.e. loadTheme doesn't create any global styles it only creates a theme object that each of the components use when being rendered. If you'd like to use that background value in your own application, you can. But it doesn't drop a body { color: red } on the page for you.
