### ISSUE TITLE
Focus is not coming to Tagpicker component inside DetailListView

### ISSUE THREAD

**Issue by RoshanKumarMicrosoft** [OfficeDev/office-ui-fabric-react#5715]
### Bug Report 
 
- __Package version(s)__: All version
- __Browser and OS versions__: All browser
 
#### Priorities and help requested:
 
Requested priority: Blocking
 
Products/sites affected: Deployment Group target page
 
#### Actual behavior:
We are using [TagPicker](https://github.com/OfficeDev/office-ui-fabric-react/tree/d29def64eb30bbe047c0dbffbc2fd52a9351bacc/packages/office-ui-fabric-react/src/components/pickers/TagPicker) component inside DetailListView (ListView) for deployment group target page. But focus is not coming to TagPicker component through keyboard. Screenshot [Link](https://drive.google.com/file/d/1e6bbgBZhKS4A_1M3meEAVIKjD9c_COxu/view)

To solve this case we wrapped Tagpicker component inside Button to bring focus on it .
Now focus is coming through keyboard button :- Screenshot[ Link](https://drive.google.com/file/d/16L9neLZKuNoC-X3MZLy1wdjoSPuYAAnL/view) But when we using inspect tool it will not able to read name property of tags inside TagPicker component.
Bug [Link](https://mseng.visualstudio.com/VSOnline/_workitems/edit/1167158)

This is happening due to focus zone in base picker component [link](https://github.com/OfficeDev/office-ui-fabric-react/blob/d29def64eb30bbe047c0dbffbc2fd52a9351bacc/packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx#L189)

#### Expected behavior:
Please suggest some way So either focus should directly goes inside TagPicker Component or it should able to read name property of tags inside TagPicker Component

**Comment by RoshanKumarMicrosoft** [comment]
@cliffkoh  Can you please look this one on priority? We are blocked on this.

**Comment by cliffkoh** [comment]
To help @joschect investigate, can you create a reduced repro such as on Codepen?

**Comment by joschect** [comment]
@RoshanKumarMicrosoft yeah a repro would really help me figure out what's going on! If you have a codepen that'd be awesome.

**Comment by Vitalius1** [comment]
@joschect do you have any context on this issue? Were you able to look into it without the codepen?
