### ISSUE TITLE
Datepicker header is vertical only in safari

### ISSUE THREAD

**Issue by woofton** [OfficeDev/office-ui-fabric-react#5723]
### Bug Report 
 
- __Package version(s)__: 6.26.0
- __Browser and OS versions__: safari, high sierra
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)  No
 
Requested priority: (Blocking, High, Normal, Low) Normal
 
Products/sites affected: (if applicable)  
 
#### Describe the issue:
 
Only on Safari, the headers within the Datepicker becomes vertical.  I have tracked it down to that the class name 'table_c754aea6'  for the table element is causing the issue.  
 
#### Actual behavior:
 
![datepicker 2](https://user-images.githubusercontent.com/11826995/43415676-14004290-93eb-11e8-8ba4-7634160694b4.png)

 
#### Expected behavior:
 
Datepicker should look the same across Chrome, Edge, and Safari.

**Comment by kenotron** [comment]
<img width="462" alt="screen shot 2018-07-30 at 1 09 09 pm" src="https://user-images.githubusercontent.com/34725/43420828-d5021c08-93f9-11e8-9da6-1e1cc57399db.png">

This is what I see on master... @woofton, can you create a minimal repro somehow on a codepen or something?

**Comment by cliffkoh** [comment]
Hi @woofton, we will close as not able to repro for now. Please feel free to re-open if you are able to provide more details on a repro.
