### ISSUE TITLE
Unable to disable the header/tab Link for the Pivot

### ISSUE THREAD

**Issue by dhavalshah01** [OfficeDev/office-ui-fabric-react#5728]
### Bug Report 
 
- __Package version(s)__: 1.5.1
- __Browser and OS versions__: Chrome
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes)
 
Requested priority: (Blocking) 
 
Products/sites affected:
 
#### Describe the issue:
 
We are unable to disable the link for the Pivot tabs or headers. As per doc, linkIsDisabled property should disable the link on the header. But there is no way we can use this interface IPivotStyleProps.
 
#### Actual behavior:
 
Link is not getting disabled. 

#### Expected behavior:
 
Link should be disabled

**Comment by dzearing** [comment]
The LinkItem should have a `disabled` prop, if you'd like to submit a PR please free free!

**Comment by tylerjwatson** [comment]
This is affecting me too.  In addition, conditionally removing `PivotItem` instances causes the `Pivot` control to crash:

![image](https://user-images.githubusercontent.com/5001408/43762699-fcf4a118-9a6b-11e8-9d83-111dc58b7627.png)

Consider the following Pivot use-case:

```jsx
render() {
  return (
     <Pivot>
        {this.props.item.isNew && <PivotItem>
            ...content
        </PivotItem>
     </Pivot>
  )
}
```

Pivot.base.jsx is trying to dereference the type property on `null`.  `typeof child === 'object'` is not a safe method of checking an object exists, as `null` is an object.  The unfortunate inflexibility is blocking us at the moment.  I am more than happy to submit a PR if OP doesn't have the time.

**Comment by mvahsen** [comment]
Any news how to remove the links from the tabs of the Pivot component?
I just want to go from tab to tab via a button below and disable the links in the component.

**Comment by micahgodbolt** [comment]
looks like pivot uses 'headerButtonProps' to pass typical button props in. We'll probably change this in the future to allow disabled to be on the item itself, but for now this works.

https://codepen.io/micahgodbolt/pen/GBQyRW#settings-js
