### ISSUE TITLE
Mobile: Avoid sticky hover scenarios

### ISSUE THREAD

**Issue by AgnieszkaBajek** [OfficeDev/office-ui-fabric-react#5734]
### Bug Report 
 
- __Package version(s)__: 6.21.1
- __Browser and OS versions__: mobiles (Chrome on Android and Safari on iPhone)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Low 
 
Products/sites affected: (if applicable)
 
#### Describe the issue:
 
When user checks option in multiselect dropdown and then unchecks it tick still appears
 
#### Actual behavior:
1. User checks option (Option b):
![img_0084](https://user-images.githubusercontent.com/40884253/43457156-40a1ca72-94c6-11e8-8136-835c556a64d4.PNG)

2. User unchecks option:
![img_0085](https://user-images.githubusercontent.com/40884253/43457169-4a17836c-94c6-11e8-9c84-577bebc9fb64.PNG)

3. Tick is still visible

 
#### Expected behavior:
 
Tick should be deleted after unchecking option.

**Comment by natalieethell** [comment]
It looks like this issue is due to a sticky hover effect for buttons on touch devices.

**Comment by JasonGore** [comment]
Per discussions on #5882 we need to tackle a more systemic solution to this problem while keeping components easily styleable.

**Comment by gregwhitworth** [comment]
This is the related CRBug for this: https://bugs.chromium.org/p/chromium/issues/detail?id=924669 - if you all can please star it to show your interest

**Comment by khmakoto** [comment]
This is an issue with Chromium and was resolved as `Resolution: External` but the bot didn't close it for some reason. Closing it now.
