### ISSUE TITLE
TextField control does not support password type 

### ISSUE THREAD

**Issue by pradeepna** [OfficeDev/office-ui-fabric-react#574]
We use TextField in our web application and we have a requirement to represent an input that accepts passwords. However, the latest implementation of the text field does not allow to set that property.

The office fabric version we are using is 0.66.0.

**Comment by dzearing** [comment]
http://codepen.io/dzearing/pen/ZBEVzw?editors=0010

Just add `type=password`. Please use the latest builds, this was also fixed recently.
