### ISSUE TITLE
Do not override event handlers provided in component mixin props

### ISSUE THREAD

**Issue by stewartadam** [OfficeDev/office-ui-fabric-react#5744]
### Bug Report 
 
- __Package version(s)__: 6.41.1
- __Browser and OS versions__: Chrome 68.0.3440.75 on MacOS 10.13.6
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
#### Describe the issue:
 
Certain Office React Fabric components' event handlers behave unexpectedly compared to standard React (i.e. lack of an `event` object passed through) due to React Fabric overriding the event handlers, as described in #5391. Since the mixin props [are merged prior](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/TextField/TextField.base.tsx#L379) to the definition of the Office React Fabric event handlers, they are impossible to attach to in order to obtain normal React behavior for event handlers.

This was discussed some time ago [here](https://github.com/OfficeDev/office-ui-fabric-react/issues/54#issuecomment-237513825), but it looks like several issues were reported at once in that issue and it has been closed without addressing the `onChange` vs `onValueChange` for all components.
 
#### Actual behavior:
1. `onChange` cannot be provided via mixin
2. `onChanged` does not follow convention and only provides the changed value, not `event`
 
#### Expected behavior:
1. Deviation from convention in event handlers should be done via a new event name (e.g. onChange -> onValueChanged), as described [here](https://github.com/OfficeDev/office-ui-fabric-react/issues/54#issuecomment-237513825) 
2. Since many Office React Fabric components have an internal callback that needs to be associated to a change event, this private event should call any mixin'd event handlers after their own internal ones to preserve conventional behavior (e.g. [_onInputChange](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/TextField/TextField.base.tsx#L379) should call the passed in function from an `onChange` prop
 
### If applicable, please provide a codepen repro:
 

https://codepen.io/stewartadam/pen/YjeJMB

**Comment by stewartadam** [comment]
Glancing at the component list I think the following are affected:
* ComboBox (onChange)
* TextField (onChange)
* Toggle (onChange, onClick may be useful to have?)
* Dropdown (onChange)
* SearchBox (onChange, onSearch)

**Comment by ecraig12345** [comment]
Looks like this was fixed for TextField by #5764.

**Comment by ecraig12345** [comment]
Slider has a related problem too:
```

**Comment by ecraig12345** [comment]
Closing this since I see it's been fixed for ComboBox, Dropdown, and Toggle by #5983.

SearchBox unfortunately has an `onChange` prop with signature `(newValue: any) => void`, so we can't add the event as the first parameter until the next major version. That work is tracked by #5982.

**Comment by stewartadam** [comment]
Thanks!
