### ISSUE TITLE
SearchBox should clear when 'Escape' key is hit while searching 

### ISSUE THREAD

**Issue by pradeepna** [OfficeDev/office-ui-fabric-react#575]
The user should be able to clear the search box by using 'escape' key when typing a term in the search box.

**Comment by dzearing** [comment]
What version are you using? this was fixed recently.

http://codepen.io/dzearing/pen/WovWLy

**Comment by pradeepna** [comment]
Super.  Thanks for the super quick reply. We are using 0.66. 

Regards,
Pradeep

**Comment by dzearing** [comment]
no problem :)

**Comment by lijunle** [comment]
Hi, we are using search box inside a dialog/model. The escape behavior is conflict with the closing dialog/modal behavior. Our team don't think it is a meaningful behavior to capture ESC in searchbox and clear the text. Use `Ctrl+A -> End` is much intuitive and general to all text area in the world. Why do you think it makese sen to ESC to clear the text?
