### ISSUE TITLE
Searchbox's field is not respecting changes to theme

### ISSUE THREAD

**Issue by cliffkoh** [OfficeDev/office-ui-fabric-react#5758]
### Bug Report 
 
- __Package version(s)__: 5.37.0

Products/sites affected: OWA
 
#### Describe the issue:
 
In #5478, it removed the backgroundColor property from the `field` of SearchBox, resulting in the default browser input styling taking effect. The net result is that Searchbox fields always have a white background.

**Comment by dzearing** [comment]
hmmm. but he added `backgroundColor: transparent` to field?

**Comment by cliffkoh** [comment]
Are we looking at the same thing?

![image](https://user-images.githubusercontent.com/1003246/43498112-53dff92c-94fa-11e8-9a23-3a86db99ce87.png)

**Comment by dzearing** [comment]
woops, he added it on the clear button. Yeah yuck.

**Comment by jordandrako** [comment]
Oh whoops!
I'll do a quick PR.
