### ISSUE TITLE
DetailList: CheckboxVisibility.always does not always display checkboxes

### ISSUE THREAD

**Issue by ndoiselet** [OfficeDev/office-ui-fabric-react#5761]
### Bug Report 
 
- __Package version(s)__: 6.42.0
- __Browser and OS versions__: all
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
#### Describe the issue:
When setting `checkboxVisibility={CheckboxVisibility.always}`on a DetailsList, the checkboxes are only visible on hover.

#### Expected behavior:
The checkboxes should be always visible.

**Comment by cliffkoh** [comment]
Codepen repro: https://codepen.io/cliffkoh-the-styleful/pen/jpzxNY

**Comment by cliffkoh** [comment]
Should be fixed in #5912.
