### ISSUE TITLE
ChoiceGroup is throwing exception while changing choice in IE11

### ISSUE THREAD

**Issue by RupamSarkar** [OfficeDev/office-ui-fabric-react#5784]
### Bug Report 
 ChoiceGroup component is throwing exception because array.find() is not supported in IE11 . This is the [commit](https://github.com/OfficeDev/office-ui-fabric-react/blob/9c95e9b92f8caa1fe5ffb9da769ce0921a5272ed/packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroup.tsx) in which the ChoiceGroup doesn’t have the find() but this [commit](https://github.com/OfficeDev/office-ui-fabric-react/blob/d0edbe9d58738d825177d520cc1f2ef8b8f54ebf/packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroup.base.tsx) has the find() at line number 159 . 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: High
Products/sites affected: Sharepoint online site is affected due to this .
 
#### Expected behavior:Choice Group should work
 
Snapshot:
![bug](https://user-images.githubusercontent.com/17047049/43611109-bba1a2aa-96c5-11e8-9668-42a21f900bc7.png)

**Comment by micahgodbolt** [comment]
This works fine on https://developer.microsoft.com/en-us/fabric#/components/choicegroup using IE11. Any non conforming JS will get transpiled to IE11 compatible code. Are you using our sourcecode and not properly building it with an ES5 target?

**Comment by micahgodbolt** [comment]
Sorry about the earlier comment. I wasn't getting that error popping up, but I see it in the console

**Comment by RupamSarkar** [comment]
ChoiceGroup.base.tsx file still has array.find() for which it is again failing for our feature in IE11 . For us it doesn't even render now ...

const firstEnabledOption = disabled || options === undefined ? undefined : options.find(option => !option.disabled);
^this is the line which is currently causing the issue while rendering  in IE11 .

Couldn't reopen the issue because i don't have permission .+

**Comment by RupamSarkar** [comment]
PR  where the line was introduced : https://github.com/OfficeDev/office-ui-fabric-react/pull/5842

**Comment by Markionium** [comment]
@micahgodbolt, I'm reopening this one.

@JasonGore we should probably stay away from using `.find` or find a way to use it with a helper or some other solution that does not break IE.

**Comment by JasonGore** [comment]
Yes, we're talking about a way to avoid these types of usages at compile time instead of run-time, or at the very least, having IE11 screener tests.

I already resolve this in #5958 yesterday, so I'll close this one.
