### ISSUE TITLE
Unable to see LineChart x-axis if height property is set to below 190

### ISSUE THREAD

**Issue by nishikaza** [OfficeDev/office-ui-fabric-react#5785]
### Bug Report 
 
- __Package version(s)__: 6.0.0
- __Browser and OS versions__: (fill this out if relevant)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 No

Requested priority: (Blocking, High, Normal, Low) 
 Normal

Products/sites affected: (if applicable)
 
#### Describe the issue:
 
When height property of LineChart is set to below 190, the x-axis becomes not visible (see below). In the image below, my height for each graph is set to 150.
 
#### Actual behavior:
 
![image](https://user-images.githubusercontent.com/20346461/43613507-7e718d98-9664-11e8-8e01-11a32bf409ac.png)
 
#### Expected behavior:
 
Scaling based on the inputted height property rather than not being able to see elements of graph such as axis

**Comment by cliffkoh** [comment]
@nishikaza this is for charting package right?

**Comment by nishikaza** [comment]
@cliffkoh yes, this is for the LineChart in the charting package!

**Comment by kkjeer** [comment]
@samiyaakhtar the issue seems to be with line 35 in LineChart.styles.ts: 

`transform: translate(${xOffset}px, ${height}px)`

The x-axis is being translated all the way to the bottom of the chart and thus is not visible.
