### ISSUE TITLE
Details Header ColumnDragDrop CSS issues

### ISSUE THREAD

**Issue by laxmikankanala** [OfficeDev/office-ui-fabric-react#5791]
DetailsHeader column drag drop issues:
1. Border fade out is not working, which was working before.
2. Gripper ICON on hover of draggable columns is not coming

https://developer.microsoft.com/en-us/fabric#/components/detailslist
In above link, in drag drop example, after enabling column reorder, drag any column, the border will be faded out automatically. But its not happening in the current code. And on hover, gripper ICON is also missing, which was visible before.

Snapshot of production experience:
![image](https://user-images.githubusercontent.com/39089979/43629393-f474dde0-96b1-11e8-8763-b454f56db27c.png)

Snapshot of current experience(with issues mentioned above):
![image](https://user-images.githubusercontent.com/39089979/43629429-1572a14e-96b2-11e8-8ce8-e358068d3a92.png)

Requested priority: High

I think the bug has been introduced as part of this PR:
https://github.com/OfficeDev/office-ui-fabric-react/pull/5490

**Comment by kenotron** [comment]
I'm seeing the fade out of the border here. I wanted to see if this is browser specific. I can repro the grippy not showing up, which I can fix.

**Comment by laxmikankanala** [comment]
@kenotron , border fade out is happening on drop, but it is supposed to fadeout after starting the drag. So while dragging, it should not have border as shown in ss1(column:key)

**Comment by kenotron** [comment]
@laxmikankanala in fact, I've never been able to repro the "expected" behavior on that top link. Are you sure it has ever worked??

**Comment by KevinTCoughlin** [comment]
FWIW I see the <-> icon on drag with the border being dragged faded-in while resizing. When its released the border fades-out in both Firefox & Edge.

**Comment by kenotron** [comment]
I can see the intention. There is some weirdness with mergestyles and animation. I am going to go back to the old animation shorthand syntax (seems like breaking it out makes it so the fade out "reset" to the border after fading out).
