### ISSUE TITLE
Button: Disabled icon button colors are wrong

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#58]
Here is the current disabled state of the icon-only button:

![image](https://cloud.githubusercontent.com/assets/1382445/17381020/ce974454-597e-11e6-8876-25efd1d8ddd3.png)

It should instead use neutralTeriaryAlt (#C8C8C8) for the icon color, and have no background color. There should also be no change to the button's background color when hovering over a disabled button.

**Comment by dubunin** [comment]
Pretty sure I already fixed this. https://github.com/OfficeDev/office-ui-fabric-react/pull/13
