### ISSUE TITLE
DetailsList: Wrong width of last column header with CheckboxVisibility hidden 

### ISSUE THREAD

**Issue by pablonete** [OfficeDev/office-ui-fabric-react#581]
### Bug Report

- __Package version(s)__: 0.69.0
- __Browser and OS versions__: N/A

#### Describe the issue:

With CheckboxVisibility.hidden, the last column header in a DetailsList doesn't get all the available space. There's a gap at the right end.

### Codepen repro:

http://codepen.io/pablonete/pen/dONmzy

**Comment by mikewheaton** [comment]
It looks like [line 532 of DetailsList.tsx](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.tsx#L532) looks for a `none` value for the `SelectionMode` prop, but doesn't check the `checkboxVisibility` prop. @dzearing, should it check for both conditions?

**Comment by dzearing** [comment]
Yes! good catch.
