### ISSUE TITLE
Checkbox: Alignment issue when text wraps to multiple lines

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#5816]
### Bug Report 
 
- __Package version(s)__: Latest
- __Browser and OS versions__: N/A
 
#### Describe the issue:
 
When the label for a Checkbox wraps across multiple lines, the box is vertically aligned in the center.
 
#### Actual behavior:

![screen shot 2018-08-06 at 10 37 10 am](https://user-images.githubusercontent.com/1382445/43731855-b30af866-9964-11e8-8841-03602b074e7d.png)

#### Expected behavior:
 
![screen shot 2018-08-06 at 10 37 55 am](https://user-images.githubusercontent.com/1382445/43731884-cd31b0cc-9964-11e8-93af-29cadb54f583.png)

**Comment by JasonGore** [comment]
This will cause alignment issues for single line, text of varying sizes, and non-text content. For example:

![image](https://user-images.githubusercontent.com/26070760/43806830-77371922-9a5a-11e8-884e-4737ce888b05.png)

Are we sure we want this behavior?

**Comment by cliffkoh** [comment]
@JasonGore would setting a line height on the checkbox itself alleviate this behavior you observed?

**Comment by JasonGore** [comment]
How would you calculate a line height based on user styling and content before render? I don't see a static fix. All the fixes I can think of are hacking styling values after initial layout, which would require another layout pass.
