### ISSUE TITLE
Slider: use type='button' on thumb to avoid form submits.

### ISSUE THREAD

**Issue by guzmonne** [OfficeDev/office-ui-fabric-react#582]
### Bug Report

- __Package version(s)__: ^0.69.0

#### Describe the issue:

The Slider component uses a button tag to encapsulate the different elements that compose the slider. By default, this component does not have set its type, which means that it takes the default value: submit.

This behaviour generates problems inside of my forms (built using react-redux) because every time a change events is generated on the slider, the form is submitted. Playing with Chrome Dev Tools, I set the button type to be "button", and the problem went away.

Is there any reason why the button type was left to its default?

#### Actual behavior:

It submits the form on every `change` event.

#### Expected behavior:

It should just update the slider value.

### If applicable, please provide a codepen repro:

Can provide one if needed.

**Comment by dzearing** [comment]
This is now resolved and will be published today.
