### ISSUE TITLE
Coachmark: isCollapsed, when set to false, only allows TeachingBubble's beak to show up

### ISSUE THREAD

**Issue by IntOwl** [OfficeDev/office-ui-fabric-react#5822]
### Bug Report 
 
- __Package version(s)__: 0.0.144
- __Browser and OS versions__: Chrome, Windows 10
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal 
 
Products/sites affected: N/A
 
#### Describe the issue:
 
The isCollapsed condition defaults to true. However, when set to false and paired with a TeachingBubble, only the beak of the TeachingBubble will show up, instead of all of the content within it as well.
 
#### Actual behavior:
 
isCollapsed, when set to false in the Coachmark, causes the page to only render the beak of the TeachingBubble, instead of the entire TeachingBubble.
 
#### Expected behavior:
 
isCollapsed, when set to false in the Coachmark, allows the rendering to bypass the Coachmark and simply display all the TeachingBubble content within it.
 
### If applicable, please provide a codepen repro:
 
No Codepen, but here's my code:

`{this.state.isCoachmarkVisible && (`
`            <Coachmark`
`              target={this._coachButtonElement.current}`
`              positioningContainerProps={{`
`                directionalHint: DirectionalHint.bottomRightEdge`
`              }}`
`              beaconColorOne={this.state.themeColor}`
`              beaconColorTwo="white"`
`              color={this.state.themeColor}`
`              isCollapsed={false}`
`            >`
`              <TeachingBubbleContent`
`                headline="An error occurred."`
`                hasCloseIcon={true}`
`                onDismiss={this._onMemCoachDismiss}`
`              >`
`                Oops. `
`                <div className={styles.header}>`
`                  <DefaultButton onClick={this._endProcess}> End Process </DefaultButton>`
`                  <DefaultButton onClick={this._setShowPanel(true)}>Go to Performance Manager</DefaultButton>`
`                </div>`
`              </TeachingBubbleContent>`
`            </Coachmark>`
`          )}`

**Comment by kenotron** [comment]
an example here: https://codepen.io/anon/pen/bxBJPE?editors=0010
