### ISSUE TITLE
DetailsList Selection modal gets disabled when !this.count

### ISSUE THREAD

**Issue by karinaderbez** [OfficeDev/office-ui-fabric-react#5829]
**Bug Report**
Package version(s): latest
Browser and OS versions: n/a

**Priorities and help requested:**
Are you willing to submit a PR to fix? (Yes)
Requested priority: high
 
#### Describe the issue:
 When selection is set to Modal if the count is 0 the Modal is set to false. 

#### Actual behavior:
 **Enable Modal**
![image](https://user-images.githubusercontent.com/3847977/43746559-dcbaac94-9999-11e8-9659-c12c2d1e0b15.png)
**Select item**
![image](https://user-images.githubusercontent.com/3847977/43746584-03446f4e-999a-11e8-891a-cd4930a08884.png)
**Deselect Item**
![image](https://user-images.githubusercontent.com/3847977/43746642-4e2004a6-999a-11e8-8558-742edf361956.png)

 
#### Expected behavior:
**Enable Modal**
![image](https://user-images.githubusercontent.com/3847977/43746559-dcbaac94-9999-11e8-9659-c12c2d1e0b15.png)
**Select Item**
![image](https://user-images.githubusercontent.com/3847977/43746584-03446f4e-999a-11e8-891a-cd4930a08884.png)
**Deselect Item**
![image](https://user-images.githubusercontent.com/3847977/43746559-dcbaac94-9999-11e8-9659-c12c2d1e0b15.png)

**Comment by JasonGore** [comment]
Repro at http://localhost:4322/#/examples/detailslist.

**Comment by JasonGore** [comment]
This regression was introduced by #5571.

**Comment by JasonGore** [comment]
Actually I should have clarified the fix. The fact that modal gets deselected when the last item gets deselected is how the example is intended to work. If at any point the number of selected items goes from non-zero to zero, then modal mode will disable itself.

The issue I fixed was related to a change where rows would not render together, which would result in rows being out of sync such as shown here:

![image](https://user-images.githubusercontent.com/26070760/43867070-cbb14424-9b1c-11e8-8d6f-479f9d88e8ce.png)
