### ISSUE TITLE
ChoiceGroup: disabled attribute does nothing (options' does)

### ISSUE THREAD

**Issue by pablonete** [OfficeDev/office-ui-fabric-react#583]
### Bug Report

- __Package version(s)__: CDN latest (?) see codepen
- __Browser and OS versions__: N/A

#### Describe the issue:

Options can be disabled individually in ChoiceGroup, but `disabled` attribute doesn't work in order to disable the entire component. My use case is to disable all components in a view while saving, and doing at the component level would be cleaner than doing it per option.

#### Actual behavior:

`disabled={true}` or just `disabled` does nothing on the ChoiceGroup

#### Expected behavior:

Disable all options when `disabled` attribute is present.

It feels like a bug because the component supports the `disabled` attribute, although I can see how this is a missing feature.

### codepen repro:

http://codepen.io/pablonete/pen/NbpNKm
(I just added `disabled` to the ChoiceGroup from dzearing codepen template).

**Comment by dzearing** [comment]
@joschect can you check

**Comment by joschect** [comment]
@dzearing Yep, this is a bug, should be a pretty easy fix I think.

**Comment by dzearing** [comment]
Fix is published.
