### ISSUE TITLE
React "Layer" component: documentation page doesn't work

### ISSUE THREAD

**Issue by alirobe** [OfficeDev/office-ui-fabric-react#5831]
### Bug Report 
 
(React Fabric Documentation broken)

- __Package version(s)__: 6.46
- __Browser and OS versions__: Chrome 68 (no extensions), Windows 10 1803
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix?: No
Requested priority: High 
Products/sites affected: Fabric UI Documentation
 
#### Describe the issue:

https://developer.microsoft.com/en-us/fabric#/components/layer#Overview
This documentation page **does not scroll** in Chrome, Edge, or Firefox. It seems to be broken.

**Comment by Jahnp** [comment]
@cliffkoh don't worry! A fix is on the way *very* soon. Long story short, we have an outdated build/deploy pipeline for the site (and the CDN that serves its files) that had a myriad of breaking issues, preventing a non-manual deploy. I've fixed that pipeline, so we should now be able to have website updates *far* more frequently. However, the pipeline is pretty crude and inefficient, and is missing a bunch of features you'd expect from a modern site deploy system (e.g. versioning, specifying releases, etc)

The better news is that we have a much-improved pipeline in the works for an internal version of the website that solves a bunch of the problems with the current system. That pipeline is about 90% complete, and soon, we'll update the public Fabric site to use the same mechanism. This should help the site stay far more up-to-date than it has been--but with the confidence of knowing we can roll back easily. I'd expect that change to be done over the next few months.

**Comment by dzearing** [comment]
Layer page is now fixed and is live. Thank you for reporting!
