### ISSUE TITLE
onColumnHeaderClick not invoked in Sticky Header Detailslist within ScrollablePane

### ISSUE THREAD

**Issue by obiwan007** [OfficeDev/office-ui-fabric-react#5832]
### Bug Report 
 
- 6.47.0 : (fill this out)
- Chrome, Windows 10: (fill this out if relevant)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (High) 
 
Products/sites affected: (if applicable)
 Sorting not possible anymore if header is sticky inside a DetailsList

#### Describe the issue:
If I use a DetailsList with a custom rendered header with Sticky - no clicks will be received:
- in onColumnClick in columns list
- in onColumnHeaderClick directly on DetailsList props.

#### Actual behavior:
No click action happens. 
Header item has no hover effect (even if columnActionsMode: ColumnActionsMode.enabled).
 
#### Expected behavior:
Click function called.
Header item has hover effect if columnActionsMode: ColumnActionsMode.enabled.

### If applicable, please provide a codepen repro:
not working:
 `
 <ScrollablePane>
        <DetailsList
          componentRef={(r) => this.detailsList = r}
          enableShimmer={this.props.isLoading}
          onRenderMissingItem={ComponentHelper.onRenderMissingItem}
          layoutMode={DetailsListLayoutMode.fixedColumns}
          onShouldVirtualize={() => true}
          {...this.props}
          items={this.props.isLoading ? [] : this.props.items}
          onColumnHeaderClick={(data) => console.log('CoulmnHeaderClick', data)}
          onRenderDetailsHeader={
            // tslint:disable-next-line:jsx-no-lambda
            (detailsHeaderProps: IDetailsHeaderProps, defaultRender: IRenderFunction<IDetailsHeaderProps>) => (
              <Sticky stickyPosition={StickyPositionType.Header}>
                {defaultRender({
                  ...detailsHeaderProps,
                  onRenderColumnHeaderTooltip: (tooltipHostProps: ITooltipHostProps) => (
                    <TooltipHost {...tooltipHostProps} />
                  ),
                })}
              </Sticky>              
            )
          }
        />
      </ScrollablePane >
`
Working (but no sticky header anymore:

`
 <ScrollablePane>
        <DetailsList
          componentRef={(r) => this.detailsList = r}
          enableShimmer={this.props.isLoading}
          onRenderMissingItem={ComponentHelper.onRenderMissingItem}
          layoutMode={DetailsListLayoutMode.fixedColumns}
          onShouldVirtualize={() => true}
          {...this.props}
          items={this.props.isLoading ? [] : this.props.items}
          onColumnHeaderClick={(data) => console.log('CoulmnHeaderClick', data)}
          onRenderDetailsHeader={
            // tslint:disable-next-line:jsx-no-lambda
            (detailsHeaderProps: IDetailsHeaderProps, defaultRender: IRenderFunction<IDetailsHeaderProps>) => (
               <>
                 {defaultRender({
                   ...detailsHeaderProps,
                   onRenderColumnHeaderTooltip: (tooltipHostProps: ITooltipHostProps) => (
                     <TooltipHost {...tooltipHostProps} />
                   ),
                 })}
                </>
            )
          }
        />
      </ScrollablePane >
`

**Comment by magicmikex** [comment]
I also ran into this issue and can repro it. 

I think this is occurring because the scrollable pane is rendering a div with the height of the content. When I scroll down at all this div is set to a height of 0 and the functions work as expected.

I'm not sure what the purpose of this div is. If I manually set it to 0 height everything works as expected. I am just trying to get the list headers to stick. 

Examples from the dom:

scroll at top:
![image](https://user-images.githubusercontent.com/26942465/43932597-d2d8661e-9bf9-11e8-9a9c-3be66f1303e3.png)

scroll down any:
![image](https://user-images.githubusercontent.com/26942465/43932585-c36278d2-9bf9-11e8-936a-ff9e8510580e.png)

**Comment by natalieethell** [comment]
Hey thanks for submitting an issue @obiwan007! I can't seem to repro. I just created the following CodePen, where `onColumnHeaderClick` seems to work as expected with the Sticky header: https://codepen.io/naethell/pen/jvWbgG

Hover also seems to be working correctly on the column headers. 

Am I missing something here?

**Comment by micahgodbolt** [comment]
This seems similar to #6006

**Comment by obiwan007** [comment]
It seems to be fixed in one of the latest releases. So it could be closed I guess.
