### ISSUE TITLE
Combobox doesn't autocomplete with non-english characters

### ISSUE THREAD

**Issue by NZainchkovskiy** [OfficeDev/office-ui-fabric-react#5834]
### Bug Report

- __Package version(s)__: 6.39.2
- __Browser and OS versions__: latest Chrome, Windows Server 2016

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Blocking) 

#### Describe the issue:

I have Combobox with options containing non-english (russian) words. 
`
<ComboBox
    allowFreeform={false}
    autoComplete="on"
    options={this.props.store!.budgetArticles.map(x => ({ key: x.Id, text: x.Title }))}
/>
`
By typing I can choose only options with english text. Russian text doesn't appears and options not selected.
#### Actual behavior:

Can't type russian characters and therefore select options with russian text

#### Expected behavior:

Can use any language for selection in combobox.

**Comment by natalieethell** [comment]
Hey @NZainchkovskiy thanks for submitting this issue! I just tried creating a ComboBox with Russian words in this CodePen: https://codepen.io/naethell/pen/zLMEYP?editors=1010, and I was able to see autocomplete work normally. Am I missing something else you were hoping to see? 

![image](https://user-images.githubusercontent.com/14134000/43871187-515ce8c2-9b30-11e8-9cca-89f19ee8f8b5.png)

Thanks!

**Comment by natalieethell** [comment]
Update: Just dug into this issue a little more. It looks like the Russian keyboard is working fine when `allowFreeform` is true, but not when `allowFreeform` is false. For some reason, `_processInputChangeWithFreeform` is taking in the correct Russian character, while `_processInputChangeWithoutFreeform` is taking in input as if it's an English keyboard.

**Comment by NZainchkovskiy** [comment]
Thank you, @natalieethell. You are right, issue is with allowfreeform=false. I hope it will be fixed soon. Now is blocking issue to use this scenario.

**Comment by JasonGore** [comment]
Pulling off Shield and putting into Backlog since this is included as high priority issue #5929

**Comment by micahgodbolt** [comment]
Dug in a little, and initial findings are that `String.fromCharCode(ev.which)` always return latin characters, even if your keyboard is in russian. Therefore you can't type a string that matches any russian  character options.
