### ISSUE TITLE
ColorPicker: Round alpha value

### ISSUE THREAD

**Issue by Fensterbank** [OfficeDev/office-ui-fabric-react#5848]
### Bug Report 
 
- __Package version(s)__: latest
- __Browser and OS versions__: all
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? If I've time
 
Requested priority: Low
 
#### Describe the issue:
 
When using the ColorPicker component and changing the alpha value, it is displayed with many decimal places.
Finally I have e.g. the value **69.58955223880598** in the TextBox for alpha value.
The resulting color is **rgba(46, 2, 155, 0.6958955223880598)**.

![grafik](https://user-images.githubusercontent.com/1684826/43820017-3893a042-9ae5-11e8-8dfd-f03f19b1567d.png)

I don't think browser will have that precision for alpha values and I think for user experience it's better to round that value shown in the text box to maximum one decimal place, so it fits in the space.
Would result in a visible alpha value of **69.6** and a color value of **rgba(46, 2, 155, 0.696)**
 
See also here: https://stackoverflow.com/questions/19478737/precision-of-alpha-value-in-rgba

#### Actual behavior:
 
Not-rounded alpha value with with many decimal places.
Does not fit the text box.
 
#### Expected behavior:
 
Rounded alpha value with with one decimal places in the text box and therefore three decimal places in the rgba color.
Does fit the text box.

**Comment by KevinTCoughlin** [comment]
For a comparison, `<input type="color" />` rounds to the nearest whole number https://codepen.io/kevintcoughlin/pen/LBgrqY. Perhaps we should do the same.

**Comment by natalieethell** [comment]
This makes sense to fix.
