### ISSUE TITLE
@uifabric/dashboard installation/css build issue

### ISSUE THREAD

**Issue by obiwan007** [OfficeDev/office-ui-fabric-react#5849]
### Bug Report 
 
- @uifabric/dashboard 0.13.0 
 
#### Priorities and help requested:

Are you willing to submit a PR to fix? (Yes, No)
 no
Requested priority: (Blocking, High, Normal, Low) 
Normal
 
Products/sites affected: (if applicable)
 
#### Describe the issue:
 
Compiling the dashboard components like <Card> or <DashboardGridLayout> fails during css transpilation. compilation.
 
#### Actual behavior:
 
css-loader seems to be unhappy about an internal css import of the dashboard component.
I will receive an error like:

`Failed to compile.

./node_modules/react-resizable/css/styles.css (./node_modules/@uifabric/dashboard/node_modules/css-loader!./node_modules/style-loader!./node_modules/css-loader!./node_modules/react-resizable/css/styles.css)
Module build failed (from ./node_modules/@uifabric/dashboard/node_modules/css-loader/index.js):
CssSyntaxError: C:\Workspaces\git\azure\pkg\frontend\pkg\node_modules\style-loader\index.js!C:\Workspaces\git\azure\pkg\frontend\pkg\node_modules\css-loader\index.js!C:\Workspaces\git\azure\pkg\frontend\pkg\node_modules\react-resizable\css\styles.css:2:1: Unknown word
    at Input.error (C:\Workspaces\git\azure\pkg\frontend\pkg\node_modules\@uifabric\dashboard\node_modules\postcss\lib\input.js:65:21)
    at Parser.word (C:\Workspaces\git\azure\pkg\frontend\pkg\node_modules\@uifabric\dashboard\node_modules\postcss\lib\parser.js:184:30)
    at Parser.loop (C:\Workspaces\git\azure\pkg\frontend\pkg\node_modules\@uifabric\dashboard\node_modules\postcss\lib\parser.js:61:26)
    at Object.parse [as default] (C:\Workspaces\git\azure\pkg\frontend\pkg\node_modules\@uifabric\dashboard\node_modules\postcss\lib\parse.js:21:12)
    at new LazyResult (C:\Workspaces\git\azure\pkg\frontend\pkg\node_modules\@uifabric\dashboard\node_modules\postcss\lib\lazy-result.js:54:42)
    at Processor.process (C:\Workspaces\git\azure\pkg\frontend\pkg\node_modules\@uifabric\dashboard\node_modules\postcss\lib\processor.js:30:16)
    at processCss (C:\Workspaces\git\azure\pkg\frontend\pkg\node_modules\@uifabric\dashboard\node_modules\css-loader\lib\processCss.js:170:24)
    at Object.module.exports (C:\Workspaces\git\azure\pkg\frontend\pkg\node_modules\@uifabric\dashboard\node_modules\css-loader\lib\loader.js:21:15)`
 
Here is an excerpt from our webpack 4 config for the rules section:

`{
        test: /\.scss$/,
        use: [
          {
            loader: '@microsoft/loader-load-themed-styles', // creates style nodes from JS strings
          },
          {
            loader: 'css-loader', // translates CSS into CommonJS
            options: {
              modules: true,
              importLoaders: 2,
              localIdentName: '[name]_[local]_[hash:base64:5]',
              minimize: true,
            },
          },
          {
            loader: 'postcss-loader',
            options: {
              plugins: function () {
                return [require('autoprefixer')];
              },
            },
          },
          {
            loader: 'sass-loader', // compiles sass to CSS
          },
        ],
      },
      { test: /\.css$/, 
        loader: 'style-loader!css-loader' 
      },`

#### Expected behavior:
 
Just compile the css correctly or provide a vialble WebPack config on how to setup the required loader.

**Comment by kenotron** [comment]
This file causes these issues: `DashboardGridLayout.tsx`:

```
require('style-loader!css-loader!react-grid-layout/css/styles.css');
require('style-loader!css-loader!react-resizable/css/styles.css');
require('style-loader!css-loader!./DashboardGridLayout.css');
```

By having this AND webpack config's loader definition, you run into this issue:
https://github.com/webpack-contrib/css-loader/issues/295#issuecomment-231510027

So, the solution is to delete those inline loaders. We should never do that! In addition, I'm not a fan of having random third party libraries embedded inside our codebase - this adds a third party dependency that we don't necessary want to impose on our users.

**Comment by kenotron** [comment]
Attn: @samiyaakhtar I believe you had worked on this code.

**Comment by nick-khoury** [comment]
I have the same problem. Will there be a fix anytime soon?

**Comment by turbo** [comment]
Same, please take a look.

**Comment by dzearing** [comment]
@Raghurk Suggest you do not import css files this way and just move the styling into the styles file in that folder. It can not only guarantee that consumers can import things correctly without special bundler/loader dependencies, but also that RTL and theming work.

**Comment by obiwan007** [comment]
Any news regarding this issue? Holidaytime it seems.

**Comment by obiwan007** [comment]
Is there any workaround on how to get this to work? What kind of webpack.config are you guys using in getting this to work?

**Comment by kenotron** [comment]
Since @samiyaakhtar hadn't had a chance to look at this since so long ago, and I'm on this week's shield rotation, I'm going to propose a change inside our code to address this.

@obiwan007, the workaround is sad, but it is workable in webpack.config. You can have a SEPARATE css rule that includes only @uifabric/dashboard, and you'll have to add an exclude on your existing css rule to exclude @uifabric/dashboard.

It is not ideal, but is a workaround until I can get a PR merged for this.
