### ISSUE TITLE
Cannot disable button in CommandBar

### ISSUE THREAD

**Issue by pablonete** [OfficeDev/office-ui-fabric-react#585]
### Bug Report

- __Package version(s)__: CDN latest

#### Describe the issue:

`isDisabled` property is ignored by CommandBar. It works in ContextualMenu.

#### Actual behavior:

Button with `isDisabled` property shows up enabled.

#### Expected behavior:

It shows up disabled.

### codepen repro:

http://codepen.io/pablonete/pen/pNeWWg?editors=0010

### Side question
Should `IContextualMenuItem.isDisabled` be renamed as `disabled` to match components' property?

**Comment by dzearing** [comment]
1. It IS renamed to disabled.
2. It does respect the flag. It was recently fixed. the CDN latest isn't updating as fast as publishing is, which is a bit of a misleading issue. You can always repoint a codepen url to `localhost:4321/dist/...` and gulp serve to see the latest in action. But @joschect just fixed it and I just tested it. :)

**Comment by pablonete** [comment]
Thank you, @dzearing!

Another side question: can you guys add a version comment at the beginning of the CDN js file, so we can check which version `latest` is? For reference see react.js, even the min.js displays the version number first thing on the file.
