### ISSUE TITLE
ActivityItem is buggy in IE 11

### ISSUE THREAD

**Issue by cliffkoh** [OfficeDev/office-ui-fabric-react#5856]
#### Describe the issue:
 
ActivityItem's CompactPersonas is busted in IE 11

IE 11:

![image](https://user-images.githubusercontent.com/1003246/43866535-e582cc62-9b1a-11e8-9044-4765d9eb439f.png)

 Chrome:

![image](https://user-images.githubusercontent.com/1003246/43866546-f1405588-9b1a-11e8-87fc-ff126d0dc96d.png)

Edge:

![image](https://user-images.githubusercontent.com/1003246/43866556-f985fd6a-9b1a-11e8-9029-0e96270b8d51.png)

**Comment by natalieethell** [comment]
This looks like an issue with screener. The `testWrapper` seems to be cutting off the CompactPersonas when I inspect the DOM. ActivityItem looks normal in IE 11 without the wrapper.

**Comment by natalieethell** [comment]
Here's what I'm seeing in IE 11: 

![image](https://user-images.githubusercontent.com/14134000/43918418-df0ebbc2-9bc7-11e8-96fe-3aeddacb1665.png)

I'll close this issue, as these screener-specific fixes for IE 11 are covered in this issue: https://github.com/OfficeDev/office-ui-fabric-react/issues/5869.
