### ISSUE TITLE
ContextMenu should declare a font color instead of inheriting

### ISSUE THREAD

**Issue by phkuo** [OfficeDev/office-ui-fabric-react#5864]
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes, but not for a few weeks
 
Requested priority: Low
 
Products/sites affected: SP emphasized headers, context menus are no emphasized but pick up emphasized text colors
 
The context menu has its own background color, therefore it should also declare its own foreground/text colors. Otherwise it could inherit text color from a highlighted section of the page that has white text, which would be illegible.

**Comment by KevinTCoughlin** [comment]
I have the fix for this, just waiting for #5942 to merge for cleaner PR. Assuming we want this defined on `linkContent` as that made the most sense to me -- could be wrong tho.

**Comment by phkuo** [comment]
@KevinTCoughlin I would put it on the root, sometimes menus have subheaders too (not sure if ours does though). It just makes sense since if you declare a background, you should declare the foreground too.
