### ISSUE TITLE
Stamping fabric version into Fabric object similar to React.version

### ISSUE THREAD

**Issue by cliffkoh** [OfficeDev/office-ui-fabric-react#5868]
**Describe the feature that you would like added**
If one uses the pre-bundled Fabric (UMD) bundle, we should be able to get access to version number similar to React.

Scenarios this will unblock:
1. Help investigate/diagnose issues in codepens and other situations by being able to easily identify version of Fabric that is powering the components
2. Allow us to easily added support for having version number prominently displayed on website

The only problem? I think it is a lot of work to get this done and properly integrated.

**Comment by cliffkoh** [comment]
@micahgodbolt which project should this be added to?

**Comment by micahgodbolt** [comment]
Future for now. But if it's high priority we might try to pull it into an iteration sooner than later. But without knowing the amount of work (you think it might be high) I'd rather not commit to it yet.

**Comment by micahgodbolt** [comment]
Great idea though. Would help out in many situations.

**Comment by cliffkoh** [comment]
What does Future mean? Milestone future but not be put in any project?

**Comment by micahgodbolt** [comment]
Projects are planned work, the "future" milestone is just a bucket of issues that we'd like to prioritize, discuss, and eventually plan to do. It's based off of Typescripts approach.

https://github.com/Microsoft/TypeScript/milestone/29

If you think "Backlog" makes more sense, I'm good with that.

**Comment by dzearing** [comment]
This is now available with `__packages__` with @kenotron added.
