### ISSUE TITLE
Enable IE 11 screener tests

### ISSUE THREAD

**Issue by cliffkoh** [OfficeDev/office-ui-fabric-react#5869]
The actual support for IE 11 is really easy to add. The problem is that we would have to scrub all screener tests to make sure they can run in IE 11 (not using a selector or method that is not supported in IE 11) and fix all the components that presently have bugs in IE 11.

This might take a bit of time to get through the scrubbing. Exactly how much time is hard to predict.

Value:
Help catch IE 11 regressions (we have a lot of IE 11 regressions), compounded by the fact that very very few folks have eyes on Fabric on IE 11 on a regular basis.

**Comment by cliffkoh** [comment]
@micahgodbolt similarly, which project should this be added to?

**Comment by micahgodbolt** [comment]
Looks like a good September piece of work.

**Comment by micahgodbolt** [comment]
https://github.com/screener-io/screener-storybook

**Comment by dzearing** [comment]
Not doing this.
