### ISSUE TITLE
SearchBox "type" property - for mobile units

### ISSUE THREAD

**Issue by jbb4play** [OfficeDev/office-ui-fabric-react#5891]
**Describe the feature that you would like added**
The SearchBox is amazing, but there is one important feature (property) missing, and that is the ability to decide which virtual keyboard is shown when typing into the SearchBox on a mobile unit.
examples: 
- If i use the search box in a seaching context, i would like the virtual keyboard to say "search" (instead of the current "return")
- If i use the search box in a telephone number context, i would like to show a virtual keyboard relevant only for telephonenumbers and not letters.

**What component or utility would this be added to**
I would like for this feature to be added to the SearchBox component.

**Have you discussed this feature with our team, and if so, who**

**Additional context/screenshots**
Using the HTML5 standard - we see there is a "type" property, and this is the property i would like implemented into the searchbox react component.

HTML5: 
https://dev.office.com/fabric-js/Components/SearchBox/SearchBox.html

**Comment by kenotron** [comment]
More info for the implementer: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search

**Comment by KevinTCoughlin** [comment]
It looks like [ISearchBoxProps](https://github.com/OfficeDev/office-ui-fabric-react/blob/06d20af3b6f9e79d28208bddc8659bd5d51d923f/packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.types.ts#L18) extends `React.InputHTMLAttributes<HTMLInputElement>` so we just need to make sure as you suggested the `type` attribute is piped to the Input element to support this. Not sure why it currently is not when I tried here -- https://codepen.io/kevintcoughlin/pen/xJMwQv.

Perhaps we're missing a spread for those native props on the `<input/>` in https://github.com/OfficeDev/office-ui-fabric-react/blob/06d20af3b6f9e79d28208bddc8659bd5d51d923f/packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.base.tsx#L93

**Comment by KevinTCoughlin** [comment]
I believe we can close this now that #6477 has been merged.
