### ISSUE TITLE
Theme colours not getting set

### ISSUE THREAD

**Issue by Toonshorty** [OfficeDev/office-ui-fabric-react#5894]
### Bug Report 
 
- __Package version(s)__: 6.48.0
- __Browser and OS versions__:
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: Sharepoint Framework Webparts
 
#### Describe the issue:
 
The style/theme mixins are not using theme overrides and instead just using the defaults from _Color.scss.

The issue can be recreated by creating a new SharePoint Framework web part and installing office-ui-fabric-react with `npm i office-ui-fabric-react`.

If you run `gulp serve --nobrowser` and load the web part in a SharePoint site workbench, the web part will render the .row element in the correct theme colour.

Now replace the existing import for SPFabricCore with `@import '~office-ui-fabric-react/dist/sass/_References.scss` as per the instructions on the [SharePoint dev docs](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/office-ui-fabric-integration#office-ui-fabric-react).

Reload the SharePoint workbench and the element will now be the default blue rather than using the site theme.
 
#### Actual behavior:
 
The background colour of the element will always be #0078d4 as defined in `_Color.varibles.scss`. Adding a themed component (e.g. PrimaryButton) does render with the correct theme colour however.
 
#### Expected behavior:
 
The background colour of the element should match the primary colour of the site theme.

**Comment by micahgodbolt** [comment]
We've moved almost everything to css in js theming now, so this sass based approach of theming is probably the best long term solution for theming your webpart. What exactly are you trying to accomplish? We might need to reach out and update those sharepoint docs.
