### ISSUE TITLE
Panel: Medium Panel size increases when screen width is reduced to less than 1024px

### ISSUE THREAD

**Issue by caradong** [OfficeDev/office-ui-fabric-react#5898]
### Bug Report 
 
- __Package version(s)__: v6.48.0 (latest as of Aug 10, 2018)
- __Browser and OS versions__: Chrome
 
 
#### Describe the issue:

Open a Panel with PanelType.medium, resize your browser to lower than 1024 px and the panel size increase. The same issue happens on the office UI Fabric site.
 
![image](https://user-images.githubusercontent.com/20460495/43972581-aaa37d6a-9c89-11e8-9277-e18dd1b52794.png)

#### Actual behavior:
The panel size increases
#### Expected behavior:
The panel size should not increase 
 
A repro here: 
 https://codepen.io/caradong/pen/BPMNra

**Comment by KevinTCoughlin** [comment]
Seems like a legit bug and media query related. Thank you for the report @caradong

**Comment by micahgodbolt** [comment]
@Vitalius1 this appears to be a pretty straight forward shield bug. Do you have room to add it to your queue?

**Comment by Vitalius1** [comment]
Yes. Preparing a PR for a different issue and will get to this one next... or next week)))

**Comment by Vitalius1** [comment]
Yes. Preparing a PR for a different issue and will get to this one next... or next week)))
