### ISSUE TITLE
Icon button doesn't theme color

### ISSUE THREAD

**Issue by phkuo** [OfficeDev/office-ui-fabric-react#5910]
Are you willing to submit a PR to fix? Yes, but not anytime soon since I'm on call
 
Requested priority: High
 
Products/sites affected: SP
 
#### Describe the issue:
 
The IconButton does not declare a color. Because it is a `<button>` element, it doesn't inherit the font color automatically and uses the browser's default styles. In dark themes, this makes it nearly invisible since it's black on black.

**Comment by dzearing** [comment]
@phkuo Would the proposal then be to add a semanticColor for ... `iconButtonIcon` ? Or, should the icon button use the button text color?

**Comment by betrue-final-final** [comment]
I would think button text color. Adding a new color seems unnecessary.

**Comment by phkuo** [comment]
@dzearing I left out a very important word: "Because it is a BUTTON element...."
@dzearing @betrue-final-final It must not use the buttonText slot, because it is a clickable icon that appears on bodyBackground, instead of on a buttonBackground. It should use link or actionLink or bodyText. I think actionLink makes sense here?

**Comment by betrue-final-final** [comment]
Right...is action link blue on rest? I think that Outlook consumes this and would expect that?

**Comment by phkuo** [comment]
What does "on reset" mean?
Action link is the neutral colored one, it is never blue. IIRC it starts neutralPrimary and goes black on hover? Do we need an icon button that switches between that and normal link colors (shades of theme)?
From a scenario perspective, I'm seeing this break in the 'back' arrow button on panels.

**Comment by phkuo** [comment]
Oops, I see.

link is themePrimary on rest, slightly darker on hover.
actionLink is neutralPrimary on rest, slightly darker on hover.
Both consistently stay within their color space.
