### ISSUE TITLE
treeshaking still imports too many modules

### ISSUE THREAD

**Issue by OneCyrus** [OfficeDev/office-ui-fabric-react#5913]
### Bug Report 
 
webpack 4.16.5 and typescript 3.0.1
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
#### Describe the issue:

this simple react app imports 104 office-ui-fabric-react modules with 170kb minified JS for a primary button

```
import * as React from "react";
import * as ReactDOM from "react-dom";
import { PrimaryButton } from "office-ui-fabric-react/lib/components/Button/PrimaryButton/PrimaryButton";

const rootEl = document.getElementById("App");

ReactDOM.render(<PrimaryButton />, rootEl);
```

![image](https://user-images.githubusercontent.com/7747800/43989957-53d8244c-9d54-11e8-967e-aa83d50c6467.png)

 
#### Actual behavior:
 
we see imports from modules which shouldn't have dependencies as far as i can tell (e.g. popup, callout, ..)
 
#### Expected behavior:
 
bundle size should be a lot smaller (number of module imports reduced)

**Comment by kenotron** [comment]
We have an experimental thing that will turn some of the "hard" imports we have to be automatically turn into "dynamic" imports: https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/webpack-utils

It would be good to see a treemap of what in OUFR got imported by PButton. We should see ContextualMenu, etc which is a good chunk of the bytes. Likely Fabric team needs to have a concerted effort to throw all these UI code to be loaded behind the scenes for you if we know those pieces are behind a user interaction (context menu, dropdown, combo box, etc)

**Comment by kenotron** [comment]
@OneCyrus - also, would you mind throw together a repo we can use to analyze this? We could always use more use cases so we can improve perf.

**Comment by OneCyrus** [comment]
didn't had time to investigate more yet.

@dzearing 
i don't think sideEffects: false does anything outside of dependencies. (at least i couldn't see a difference with this flag). but I'll try to break down and compare to the test button app. maybe it's really a configuration issue.

@kenotron 
yes, you're right. the contextualmenu is one of the larger imports. I'll post a treemap and will create a minimal repo to have another example.

as far as the webpack loader goes. is this already working (ready for a try)?

**Comment by kenotron** [comment]
You can try it out - I'm not aware of production usage of this yet. But it is very simple in its purpose. It will replace ContextualMenu with react-loadable automatically for you.
