### ISSUE TITLE
No good way to override header margins in Panel

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [OfficeDev/office-ui-fabric-react#5914]
### Bug Report 
 
- __Package version(s)__: 
* `"office-ui-fabric-react": "6.30.0"
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: Sway
 
#### Describe the issue:
 
There is a lot of margin above the header in `Panel`s:

![image](https://user-images.githubusercontent.com/3335181/44005464-b2cbc632-9e28-11e8-8b59-28525899784f.png)

We'd like to be able to provide a class or style that reduces the amount of margin-top above the header. 
+1 for using a lot of whitespace 😊 but we'd like to fit more into the panel.
 
#### Actual behavior:
 
There is a `headerClassName: string` in `IPanelProps` but providing a `margin` or `margin-top` there can get overridden by the generated, coincidentally more specific styles.

![image](https://user-images.githubusercontent.com/3335181/44005490-40d7e0b4-9e29-11e8-9878-aade81cf9458.png)
 
#### Expected behavior:
 
A few other components have props interfaces that allow a `styles` object, so we could provide our own styles object to be merged on top of the default styles. Can this one have that as well?

**Comment by micahgodbolt** [comment]
This is now unblocked and should be capable via css in js styles, and the `styles` interface.

**Comment by micahgodbolt** [comment]
This is pretty easy now with css-in-js style. Just add this to your panel.

```js
styles={{
  header: {
    marginTop: 0
  }
}}
```
