### ISSUE TITLE
ComboBox: Multi-select and other input issues

### ISSUE THREAD

**Issue by JasonGore** [OfficeDev/office-ui-fabric-react#5929]
### Bug Report 
 
 
- __Package version(s)__: 6.49.0
- __Browser and OS versions__: Chrome
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)
 
#### Describe the issue:
 
On the [6.49.0 Fabric site](http://fabricweb.z5.web.core.windows.net/oufr/6.49.0/#/examples/ComboBox), the following behavior occurs:

![combobox](https://user-images.githubusercontent.com/26070760/44103464-2883fd4e-9fa1-11e8-9cfe-bf1ef777ee6e.gif)

#### Actual behavior:
 
Input often does not update as user selects and collapses dropdown.

There are other issues related to input, so I'm going to reference them here as the cause or fix may be similar: #5917, #3061, #3055, #5834
 
#### Expected behavior:
 
Input updates as user selects and collapses dropdown.
 

### If applicable, please provide a codepen repro:
Provided fixed version link above.

**Comment by JasonGore** [comment]
We should think about how we prioritize and approach #5205 given these outstanding issues.

**Comment by natalieethell** [comment]
While trying to debug #5834, it was also made apparent that ComboBox is not working properly in the most basic scenario when `allowFreeform` is false and `autoComplete` is true. I've included a screen capture below using the example on the demo page (courtesy of @kysedate):

![comboboxbug](https://user-images.githubusercontent.com/14134000/44162980-cd8daf80-a076-11e8-80ce-ff6956951b28.gif)


When trying to type Arial Black or Times New Roman, it types in all caps (and doesn't autocomplete). It also does not allow text deletion, which forces a user to select a different option to start over.

**Comment by NZainchkovskiy** [comment]
Any updates on this and related issues?
Combobox is broken in many scenarios, and it's lasting a few months now.
This component is not supported any more?

**Comment by JasonGore** [comment]
We need to revisit ComboBox holistically as there are numerous issues with it combined with the context of #5205, so I'll mark this blocked for now.

**Comment by dcokely7** [comment]
There is a very similar behavior where when you have a controlled multi-select Combobox and supply a selectedkey prop, when the component renders the selected keys dont display until you give the combobox focus then click off of it.  You can see this behavior on the Fabric Documentation site:
https://developer.microsoft.com/en-us/fabric#/components/ComboBox

![image](https://user-images.githubusercontent.com/17841245/49097049-f4dd4680-f239-11e8-8cbd-7b50be1caa96.png)

But when you click the dropdown, you see it does in fact have items selected:

![image](https://user-images.githubusercontent.com/17841245/49097241-5dc4be80-f23a-11e8-8378-5399f4203d56.png)

I can file a separate bug if that makes more sense.

**Comment by StanTempAccount** [comment]
Please address this issue asap.

**Comment by ShiboRain** [comment]
Hey @ all,

there is another unwanted behaviour. If I type in some letters I get a suggestion which item matches the letters I typed in. In ComboBox without multiselect it selects and shows automatically the suggested item if I click outside the input field (onBlur event). In multiselect it seems to be selected but its not shown in the input field as a selection and i cannot fix this issue not even by providing a selectedKey.

Thanks for your help in advance!

**Comment by micahgodbolt** [comment]
We've done a bunch of updates to the ComboBox recently. Would be good to see if this issue is still value.
