### ISSUE TITLE
Typo inside Popup.tsx

### ISSUE THREAD

**Issue by guzmonne** [OfficeDev/office-ui-fabric-react#593]
### Bug Report

There is a typo on the following file:

office-ui-fabric-react/packages/office-ui-fabric-react/src/components/Popup/Popup.tsx

Specifically the #66 line

https://github.com/OfficeDev/office-ui-fabric-react/blob/afd7c7d644a0674f69a6598d151f1dc3b5375a53/packages/office-ui-fabric-react/src/components/Popup/Popup.tsx#L66

This typo on the Panel `render` method makes React throw an error because it can't define the prop `aria-desribedby`.

**Comment by dzearing** [comment]
http://codepen.io/dzearing/pen/qqWXYP

I see the warning... new in 15.4.0 of React. Confused, because this is a valid attribute.

**Comment by dzearing** [comment]
This is now fixed and will be published in the next batch of changes. Good catch.

https://github.com/OfficeDev/office-ui-fabric-react/commit/b20c82d2af8e8defadadeac42f8e23ca71025703
