### ISSUE TITLE
Panel is dimissing immediately after being opened.

### ISSUE THREAD

**Issue by TCambre** [OfficeDev/office-ui-fabric-react#5935]
### Bug Report 
 
 
- __Package version(s)__: 6.42 (Also tried 6.48)
- __Browser and OS versions__: Windows 10, Chrome OS. (This seems to repro on every browser except Firefox)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: High
 
Products/sites affected: Microsoft Flow
 
#### Describe the issue:
 
The scenario is made up of two components:
1. DetailsList
2. Panel

When selecting (single click) an item inside of details list (where only a single item can be selected at a time) a panel opens to further display information about the item. This is done via a Selection passed into DetailsList and opening the panel via onSelectionChanged or it repros with just using onActiveItemChanged and not passing a Selection in.

**The problem is that when opening the panel via selection the panel is being dismissed _immediately_ when it's opened.**
 
#### Actual behavior:

When selecting item in the details list, the panel animates to open, but then immediately animates to close. When holding the mouse down on selecting an item the panel stays open but releasing the press closes the panel.
 
I noticed when onSelectionChanged is invoked and the state is changed to open the panel, the panel's onDismissed callback is being called twice.
 
#### Expected behavior:
 
A single click to select an item in detailsList should open the panel.
 
### If applicable, please provide a codepen repro:
https://codepen.io/tcambre/pen/jpoMQx

**Comment by JasonGore** [comment]
I had trouble reproducing this at first until I realized it's very particularly about where you actually click. Here's an image showing the difference in behavior between regions:

![panel](https://user-images.githubusercontent.com/26070760/44156677-56012656-a065-11e8-8641-fac3bf932288.gif)

**Comment by achappey** [comment]
This bug is still present in the 5.0 branch
