### ISSUE TITLE
Modularize the PeoplePicker examples

### ISSUE THREAD

**Issue by sliminality** [OfficeDev/office-ui-fabric-react#5937]
The [PeoplePicker documentation](https://developer.microsoft.com/en-us/fabric#/components/peoplepicker) provides examples of several picker variants, which is great!

Unfortunately, the example is organized in a rather confusing way. There is a single "variant" heading, and the example component includes a drop-down menu. Users select a variant ("normal," "compact," "preselected items," etc.) from this menu, and the example re-renders accordingly.

Grouping all the examples together like this makes the **sample code _really_ hard to read**. Namely, the sample code includes:

- Separate rendering methods for all seven variants,
- A bunch of property definitions used by specific variants, and
- All of the type definitions, control logic, and rendering logic for the dropdown menu and switcher.

This last bullet point comprises a substantial portion of the example code. Sometimes I just want to make a simple picker, not get hit by a 23-line `switch` statement in `render()`. 😛 

Suggested changes:

- Adopt the organizational approach taken by most other component pages, such as [SearchBox](https://developer.microsoft.com/en-us/fabric#/components/searchbox). Each variant gets listed separately, with its own subheading and example code.
- Eliminate any part of the example not directly related to rendering the picker, which is already quite a complex component.

**Comment by JasonGore** [comment]
Great feedback! You also have a very good analysis so I wanted to encourage you to create a PR for this if you're so inclined. 😄

**Comment by shahidroofi** [comment]
It's been three days I'm only struggle and not able to use people picker using this code for onprem react based new project.

It's unlike other components

First of all most dependent files are not there. I downloaded and pasted in node_modules\office_ui_react to resolve lot of errors.

Still after errors are gone, it won't run. Gulp serve reports tons of other missing items that I'm unable to locate

**Comment by butchmarshall** [comment]
Is it possible to use this as a controlled input?
