### ISSUE TITLE
Textfield's is not calling method passed for onGetErrorMessage prop for every re-render

### ISSUE THREAD

**Issue by iashishmittal** [OfficeDev/office-ui-fabric-react#594]
### Bug Report

- __Package version(s)__: 0.66.0
- __Browser and OS versions__: Chrome(latest) and Windows 10

#### Describe the issue:

I am using office fabric text box for displaying variable names.

 
![image](https://cloud.githubusercontent.com/assets/16335581/20512814/e5cb23d6-b0a7-11e6-8deb-bcc48aeb1175.png)

For my case, both variable name cannot be same. So if the variable names are duplicate I’m showing the Error like following:

 
![image](https://cloud.githubusercontent.com/assets/16335581/20512817/ec2f9022-b0a7-11e6-9bca-7bfad55f702b.png)

Problem is arising when I am changing the first variable name to avoid the duplication and second variable’s error message is not getting removed. 

 
![image](https://cloud.githubusercontent.com/assets/16335581/20512822/efe5f850-b0a7-11e6-8095-de94e788769c.png)

I checked in office fabric’s textField component code and it looks like  _validate method is the one responsible to run the method passed for prop onGetErrorMessage to check for error.
If the value in the textfield is not changed then on re-render, the validate method is not getting called.
In my case, onGetErrorMessage method is looking into all the variables then figuring out if it duplicate or not.

#### Actual behavior:
On re-rendering, method passed for onGetErrorMessage prop is not getting called for 2nd variable so error is not getting removed.

#### Expected behavior:
Since text field is dependent on externally injected prop for onGetErrorMessage, so it should be called for each re-render case and not only for onChange event.

**Comment by mdahamiwal** [comment]
@iashishmittal , @dzearing  I don't see any reason to trigger `onGetErrorMessage` on re-render even though their is no change in its `value`. Note that a validation can be a hefty operation (we even support promises) and doing it without any checks can be overwhelming. `TextField` already support other props that can solve this scenario. IMO, we should take care of any such validation in the parent component. Something like http://codepen.io/mdahamiwal/pen/WRbzKL

**Comment by mdahamiwal** [comment]
@iashishmittal, did you get a chance to try the suggestion above. We should close the issue if the requirements have changed.

**Comment by iashishmittal** [comment]
Hi Manish,

Thanks for providing the work around.
I was not able to check the workaround as we have moved to a completely
different implementation to show variables for my applications which is not
using TextField.
You can close the issue.

Thanks
Ashish

On Mon, Jan 23, 2017 at 12:28 PM, Manish Dahamiwal <notifications@github.com
