### ISSUE TITLE
Contextual Menu Example w/ Charm Menu has broken styles

### ISSUE THREAD

**Issue by KevinTCoughlin** [OfficeDev/office-ui-fabric-react#5943]
### Bug Report 
 
- __Package version(s)__: 6.47
- __Browser and OS versions__: All
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Low
 
Products/sites affected: Fabric Site
 
#### Describe the issue:

Noticed while working thru #5942 that the customized `ContextualMenu` example w/ a charms grid sub-menu is broken i.e. not displaying its icons in a grid.

#### Actual behavior:
 
![image](https://user-images.githubusercontent.com/706967/44170220-865de980-a08b-11e8-8863-9cc0568d783a.png)
 
#### Expected behavior:
 
Menu items in the above sub-menu grid should be visible.
 
### If applicable, please provide a codepen repro:
 
See Fabric Site or image above.

**Comment by micahgodbolt** [comment]
@KevinTCoughlin is this related to the work you're doing now?

**Comment by KevinTCoughlin** [comment]
It's been broken in `master` for a bit. I didn't want to forget about it since its a tad deceiving while testing `<ContextualMenu/>` changes. I'll pick it up once the mergeStyles changes are in.
