### ISSUE TITLE
Filter DetailsList

### ISSUE THREAD

**Issue by licypal** [OfficeDev/office-ui-fabric-react#5946]
Can anyone please let me know how to filter a DetailsList? For instance, let’s say I have the following list:

![list](https://user-images.githubusercontent.com/6519992/44175816-4f440400-a09c-11e8-986f-6e3f04828b9f.JPG)

How do I filter the list such that when I type “Reject”, it will only show items with Status “Reject”

I tried the code from the documentation https://developer.microsoft.com/en-us/fabric#/components/detailslist). It didn't work though.

private _onChangeText = (text: any) => {
    this.setState({ items: text ? this.state.items.filter(i => 
    i.Status.indexOf(text) > -1) : this.state.items });
}

<TextField
  label="Filter by name:"
  onChanged={this._onChangeText}
/>

Thanks!

**Comment by kenotron** [comment]
I made a codepen that proves that it works okay: https://codepen.io/anon/pen/GBaaNE

I would watch out a few things - using a textfield to filter approve vs reject seems overkill. Should probably be a toggle / dropdown. Also, you're filtering based on EXACT text, so it could be that you're filtering based on lower cased stuff and it doesn't work for you.

**Comment by kenotron** [comment]
I think this should address the issue for you... feel free to reopen if you can create another minimal repro in a codepen, etc.

**Comment by KevinTCoughlin** [comment]
Also answered @ https://stackoverflow.com/questions/51867040/filter-office-ui-fabric-detailslist

**Comment by licypal** [comment]
Thank you @kenotron 

@KevinTCoughlin  Appreciate your help. Your solution worked for me. I have a question though. Is it possible to filter by checking values in just one column instead of all the column values? For example, with your current code, if I type 'A', it will return all the items with value 'A'. Let's say one item's Name is 'abc' and Status is 'Reject', it will return that as well. Instead of that, how would I just check 'Status' column values and return result based on that? Thanks!
