### ISSUE TITLE
Toggle: No way to specify class name for top level DOM element

### ISSUE THREAD

**Issue by serkan-inci** [OfficeDev/office-ui-fabric-react#595]
### Bug Report

- __Package version(s)__: 0.74.0
- __Browser and OS versions__: Any browser, Windows 10

#### Describe the issue:
Class name you specify for a component usually applies to top level DOM element but for Toggle, it's applied to inner button. 

This makes overriding styles difficult where we now need to have something like below in our css which seems fragile (once you switch to css modules):
    
    .container {
        .ms-Toggle {
            margin-bottom: 0;
        }
    }

If I can specify my own class ```my-toggle```, then I can do below:
   
    .container {
        .my-toggle {
            margin-bottom: 0;
        }
    }

#### Actual behavior:

Class name applied to inner button.

#### Expected behavior:

Class name applied to top level div.

**Comment by dzearing** [comment]
Also fixed this. 100% agree with the thought, it seems like a bug that className isn't on the container.

**Comment by dzearing** [comment]
Fix will be published shortly.
