### ISSUE TITLE
Spinner shake in embedded WebBrowser in WPF

### ISSUE THREAD

**Issue by keepWalking** [OfficeDev/office-ui-fabric-react#5952]
### Bug Report 
 
 
- __Package version(s)__: 6.12.0
- __Browser and OS versions__: WebBrowser in WPF (based on IE kernel v11+)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (High) 
 
Products/sites affected: (if applicable)
 
#### Describe the issue:

**Developing a desktop application based on React, loading web page in System.Windows.Controls.WebBrowser in WPF.**

The spinner will shake in such a container, while in other browsers, it's stable.

Its behavior differs from different container:
Chrome browser: Normal
IE browser: Normal
Embedded web Browser in WPF: **Abnormal**

 
#### Actual behavior:
 Only the spinner in the page will shake.
Sorry no place to upload video/gif, only following snapshot, you cannot observe the issue. :(

![image](https://user-images.githubusercontent.com/4075786/44202295-2431e100-a17e-11e8-9253-28a2dd3c0678.png)

 
#### Expected behavior:
 Stable rotate as in other browsers.

**Comment by JasonGore** [comment]
Animated GIFs are supported in the markup, I've used [ScreenToGif](https://www.screentogif.com/) personally and attach images as comments in issues like #5935. 

There is still the issue of reproduction. Is there an easy way to create an Web Browser in WPF environment for reproduction and verifying fixes? 

Also, if you are a Microsoft employee, can you add your github account to the Microsoft org for account aliasing and internal comms? Thanks.

**Comment by micahgodbolt** [comment]
As far as I know, we don't actively test, nor support WPF browser. Our support commitment is Edge and IE11, in which the spinner appears to be working as expected. If this is a bug with the WPF browser about the way that it handles animations or css transforms, I don't believe there is much that we'd be able to do to help.
