### ISSUE TITLE
DatePicker no chance to clear in IE browser but Chrome do

### ISSUE THREAD

**Issue by keepWalking** [OfficeDev/office-ui-fabric-react#5953]
### Bug Report 
 
 
- __Package version(s)__: 6.12.0 
- __Browser and OS versions__: IE v11 and Edge
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (High) 
 
Products/sites affected: (if applicable)
 
#### Describe the issue:
 Refer to official tutorial on "DatePicker allows input date string", add a DatePicker into ScrollablePane.
First click on DatePicker input textfield, the "Date option" dialog will pop up.
Second click on DatePicker input textfield, the "Date option" dialog will disappear, but meanwhile, the ScrollablePane will re-render and go to the top, in this case, "DatePicker" hide in the ScrollablePane bottom, which no chance to clear any more.
![image](https://user-images.githubusercontent.com/4075786/44203390-4f69ff80-a181-11e8-9bfc-a375550bd4fe.png)

 
#### Actual behavior:
 Second click on DatePicker input textfield cause ScrollablePane re-render

 
#### Expected behavior:
 Second click on DatePicker input textfield, the "Date option" dialog will disappear, and ScrollablePane will not re-render itself, so user can clear the DatePicker textfield input.

**Comment by JasonGore** [comment]
Since `DatePicker` is a child component, it can't directly force `ScrollablePane` to rerender. [Here is a CodePen](https://codepen.io/jasongore/pen/bjPZoJ) showing that to be the case. When you perform the steps you described in this CodePen, the `ScrollablePane` doesn't scroll.

It's more likely there is an issue with how the `DatePicker` callbacks are tied back to the `ScrollablePane` that is triggering `ScrollablePane` to re-render when they are called. If you want to put the code exhibiting the issue in a CodePen (or modify the one I have above), I can take a look. But I don't think this is directly an issue with `ScrollablePane` or `DatePicker`, so I will close this issue for now.

**Comment by keepWalking** [comment]
@JasonGore thanks for your reply, when I try to share the sample in CodePen, I found another blocking issue: the feature of "allows input date string" in DatePicker is not supported in IE11, right? I tried to open  this link: https://developer.microsoft.com/en-us/fabric#/components/datepicker in Chrome/Edge/IE11 browser, only IE11 cannot render normally.

**Comment by JasonGore** [comment]
There are some other elements on the page that may be causing issues. When I open the [CodePen](https://codepen.io/jasongore/pen/bjPZoJ) I pasted above in IE11 it loads properly for me.

Opening CodePens in IE11 is a bit tricky. First make sure you're logged into your CodePen account in IE11. Then fork the CodePen in Chrome, open it in Chrome, switch to `Debug View` in Chrome, then copy the resulting URL in IE11.

![image](https://user-images.githubusercontent.com/26070760/44282796-08c3e600-a211-11e8-8ea0-a9e3a80bb3e3.png)

**Comment by keepWalking** [comment]
Yes, this DatePicker in Debug mode/Full Page view at IE11 can work well, so do you know the difference between Debug and Editor view? How could I resolve this issue if I want to support IE11? Thx.

**Comment by keepWalking** [comment]
I tried to open your shared codepen in browsers:
1. Editor view:  Chrome - work, Edge - work, IE11 - cannot open
2. Full page/Debug view: IE11 can render normally.

**Comment by JasonGore** [comment]
I think one of the only ways we can resolve this is for you to make a CodePen out of the code that's exhibiting the behavior you're seeing. I described above but I believe it may be an issue of callbacks affecting `ScrollablePane` rendering.

**Comment by keepWalking** [comment]
I will share you the repro env offline, thx

**Comment by keepWalking** [comment]
@kkjeer yes, they are the same issue.

**Comment by Ridlsan** [comment]
In Firefox you can edit it, but carret is invisible, fix it too please!
