### ISSUE TITLE
Toggle: Make label optional

### ISSUE THREAD

**Issue by serkan-inci** [OfficeDev/office-ui-fabric-react#596]
We don't want to have any label and specify empty string. However, an empty DOM element still added to the tree and it takes up some space too.

It would be great label was optional.

I can work on this if you're OK with this feature request.

**Comment by mikewheaton** [comment]
The label is optional for other form components like [TextField](http://dev.office.com/fabric#/components/textfield) and [ChoiceGroup](http://dev.office.com/fabric#/components/choicegroup), so it seems reasonable to make it optional on Toggle as well.

And yes, we're always happy to receive pull requests. 😄  If you follow the example of TextField and ChoiceGroup it should be no problem to get it in.

**Comment by dzearing** [comment]
I thought this was already there! I fixed it for ya and added some tests to validate.

The test forced me to realize that label is a required param (and then re-read your comments, which you stated that) so I fixed that too. Yay tests!

PR: https://github.com/OfficeDev/office-ui-fabric-react/pull/597

**Comment by dzearing** [comment]
Will be published shortly.
