### ISSUE TITLE
Coachmark: Prevents other components from receiving focus

### ISSUE THREAD

**Issue by JasonGore** [OfficeDev/office-ui-fabric-react#5960]
### Bug Report 

- __Package version(s)__: 6.49.4 
- __Browser and OS versions__: n/a
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) High
 
Products/sites affected: (if applicable)
 
#### Describe the issue:
 
When Coachmark appears, even when collapsed, it prevents any other component on the page from getting focus. 
 
#### Actual behavior:
 
Coachmark is preventing other components from receiving focus.
 
#### Expected behavior:
 
Should not prevent focus on other components on page.
 
### If applicable, please provide a codepen repro:

Reproduces on Fabric page:
https://developer.microsoft.com/en-us/fabric#/components/coachmark

**Comment by JasonGore** [comment]
I'm still seeing [this issue on master](https://fabricweb.z5.web.core.windows.net/oufr/6.62.0/#/examples/coachmark) (v6.62 most recent at time of writing.) It seems focus sometimes works, but most of the time it still doesn't. If I either mouse over or tab to `Show Coachmark`, wait for it to appear, then attempt to tab, I cannot focus on other elements on the page. (In the case of tabbing to `Show Coachmark`, you can see that it appears to grab focus from the button when selected.)

**Comment by kenotron** [comment]
@leddie24 looks like this still repros
