### ISSUE TITLE
Dialog shows scrollbars in IE but not in Firefox or Chrome.

### ISSUE THREAD

**Issue by MarcWUW** [OfficeDev/office-ui-fabric-react#5976]
### Bug Report 
 
In IE 11 the Surfaces > Dialog component shows horizontal and vertical scrollbars when they are not needed. Firefox and IE do not show scrollbars.
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal 

 
#### Describe the issue:
 
I am using the react fabric ui dialog in a SharePoint site to confirm an action and in IE there are horizontal and vertical scrollbars that obscure the content.
 
#### Actual behavior:
 
There should not be scrollbars because they are not needed. The content is small and the dialog works in other browsers.
 
#### Expected behavior:
 
A nice dialog without scrollbars.

**Comment by MarcWUW** [comment]
The text entered using dialogContentProps.subText does not wrap in IE, causing the scrollbars.

**Comment by MarcWUW** [comment]
I fixed the bug in my case using:

.ms-Dialog-subText {
    width: 250px !important;
}

**Comment by JasonGore** [comment]
I am not seeing this behavior [this CodePen](https://codepen.io/jasongore/pen/jpgKra) in IE11. `subText` appears to be wrapping correctly and I don't see any scrollbars.

I will close this issue for now but feel free to reopen if you have a CodePen repro. Thanks!

![image](https://user-images.githubusercontent.com/26070760/44286987-f3a28380-a21f-11e8-986f-a5394c6a4459.png)

**Comment by MarcWUW** [comment]
Thanks for looking. CodePen does not work in IE 11.0.96 where I am seeing the issue. I get an error message saying "CodePen doesn't work in this browser." Then more details.

I am using Windows 7 Enterprise.

**Comment by JasonGore** [comment]
Yeah, there is a trick to that. CodePen only allows opening in IE11 when they're your CodePens and they are in `Debug Mode`. In Chrome, do the following: fork the issue, switch to `DebugMode` via `Change View`, then copy the resulting URL in IE11. You'll have to be logged in to your CodePen account on IE11 as well.
