### ISSUE TITLE
DetailsList throws Check the render method of `DetailsColumnBase`

### ISSUE THREAD

**Issue by mjonila** [OfficeDev/office-ui-fabric-react#5985]
### Bug Report 
 
 
- __Package version(s)__: 6.50.1 
- __Browser and OS versions__: Chrome, Windows
 
#### Describe the issue:
 
I have SPFx SharePoint component with Panel in it. All works fine, but when I use DetailsList example code from https://developer.microsoft.com/en-us/fabric#/components/detailslist  it starts throwing this:
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check the render method of `DetailsColumnBase`.
    in DetailsColumnBase (created by StyledDetailsColumnBase)
    in StyledDetailsColumnBase (created by DetailsHeaderBase)
    in div (created by FocusZone)
    in FocusZone (created by DetailsHeaderBase)
    in DetailsHeaderBase (created by StyledDetailsHeaderBase)
    in StyledDetailsHeaderBase (created by DetailsListBase)
    in div (created by DetailsListBase)
    in div (created by DetailsListBase)
    in div (created by DetailsListBase)
    in DetailsListBase (created by WithViewportComponent)
    in div (created by WithViewportComponent)
    in WithViewportComponent (created by StyledWithViewportComponent)
    in StyledWithViewportComponent (created by EmployeeDocsField)
    in div (created by MarqueeSelectionBase)
    in MarqueeSelectionBase (created by StyledMarqueeSelectionBase)
    in StyledMarqueeSelectionBase (created by EmployeeDocsField)
    in div (created by EmployeeDocsField)
    in div (created by Panel)
    in div (created by Panel)
    in div (created by FocusTrapZone)
    in FocusTrapZone (created by Panel)
    in div (created by Panel)
    in div (created by Popup)
    in Popup (created by Panel)
    in div (created by FabricBase)
    in FabricBase (created by StyledFabricBase)
    in StyledFabricBase
 
#### Actual behavior:
 
DetailsList is not displayed and throws error.
 
#### Expected behavior:
 
Should display DetailsList

**Comment by KevinTCoughlin** [comment]
Hmm not sure, could it be due to this? Are you able to repro locally outside of the SharePoint component? If so that would help me debug.

https://github.com/OfficeDev/office-ui-fabric-react/blob/a9878d29db805343eed98e1e2c53722a0154a371/packages/office-ui-fabric-react/src/components/DetailsList/DetailsColumn.base.tsx#L65

**Comment by jhholm** [comment]
I think this is an issue with Sharepoint Framework (Spfx) as it still uses react@15 and react-dom@15.
I can reproduce this in a normal javascript project if using react@15.

I suppose only version 16 and up is supported with the current version of office-ui-fabric-react (6.51.0)?

**Comment by jhholm** [comment]
Yes. Looking at the [office-ui-fabric-react 6.0 release notes](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/6.0_RELEASE_NOTES.md), it requires react 16+. React 16 is not yet officially supported with SharePoint Framework. Support should be arriving with version 1.6 that should release in the next few months.

**Comment by kkjeer** [comment]
@mjonila I created a basic Codepen with a DetailsList inside a Panel, please feel free to build on it to get a repro. https://codepen.io/kkjeer/pen/JajNye

**Comment by coreyroth** [comment]
This issue is really affecting me right now.  This has forced me to go back to LTS to get the DetailsList working.  Unfortunately, that means there are other things that I can't do as well as deal with other issues.  I am kind of surprised this component took a dependency on React 16 when SPFx is so far away from supporting it.

**Comment by jhholm** [comment]
As far as I can tell, the next version of spfx (1.6) should provide react 16 support otb

**Comment by sboyd** [comment]
I had this issue too, what I ended up having to do was use the office-ui-fabric-react lib that comes bundled with SPFx. It happens to be an older version of the that library too. Unfortunately the release of SPFx 1.6 doesn't support react 16+ so installing office-ui-fabric-react directly via npm will not work.
