### ISSUE TITLE
MaskedTextField's maskChar prop doesn't work properly

### ISSUE THREAD

**Issue by keydoubleu** [OfficeDev/office-ui-fabric-react#5988]
### Bug Report 
 
- __Package version(s)__: 6.50.1
- __Browser and OS versions__: Chrome Windows 7
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Low
 
#### Describe the issue:
 
The maskChar attribute of MaskedTextField doesn't work properly.
 
#### Actual behavior:
 
maskChar outputs a placeholder for MaskedTextField, but the output is not formatted properly at all.
 
#### Expected behavior:
 
maskChar is supposed to output a properly formatted placeholder for MaskedTextField.
 
### If applicable, please provide a codepen repro:
 https://codepen.io/anon/pen/JaPMZv?editors=1010

**Comment by kkjeer** [comment]
@keydoubleu thank you for the codepen! The maskChar prop is intended to be one character that acts as a placeholder, e.g. '_'. I made a fork of the codepen showing a different maskChar, as well as a MaskedTextField with a value. https://codepen.io/kkjeer/pen/wEvdwB
