### ISSUE TITLE
Narrator reading out aria-description twice for PrimaryButton

### ISSUE THREAD

**Issue by saurabhsuniljain** [OfficeDev/office-ui-fabric-react#5990]
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal 
 
#### Describe the issue:
 
I am using PrimaryButton component and passing ariaDescription as follows :

`
<PrimaryButton ariaDescription={this.props.ariaDescription} >
    {this.props.buttonText}
</PrimaryButton>}
`

the corresponding created HTML is as follows : 
`
<a class="ms-Button ax-message-button ms-Button--primary root-148" aria-describedby="id__298">
    <div class="ms-Button-flexContainer flexContainer-134">
        <div class="ms-Button-textContainer textContainer-135">
            <div class="ms-Button-label label-140" id="id__296">View extensions</div>
        </div>
        <span class="ms-Button-screenReaderText screenReaderText-128" id="id__298">Some text</span>
    </div>
</a>
`

It is reading aria-description twice as follows: 
    1. Once for the span element (ms-Button-screenReaderText)
    2. Once for parent div where id of span element is passed as aria-describedby.

#### Actual behavior:
 
Aria description for PrimaryButton is being read-out twice.
 
#### Expected behavior:
 
Aria description for PrimaryButton should be read-out once.

**Comment by kkjeer** [comment]
@saurabhsuniljain thank you for submitting an issue! Could you specify what you are passing in as the `ariaDescription` (i.e. what is `this.props.ariaDescription`) and the button text (i.e. what is `this.props.buttonText`) in your example and what text Narrator is reading?

It is expected behavior for Narrator to read both the text within the button as well as the ariaDescription text. In this example from the [website](https://developer.microsoft.com/en-us/fabric#/components/button), Narrator reads "Aria Description This is aria description used for screen reader."

`<div className={css(classNames.example)}>
        <PrimaryButton
          data-automation-id="test"
          disabled={disabled}
          checked={checked}
          ariaDescription="This is aria description used for screen reader."
        >
          Aria Description
        </PrimaryButton>
      </div>`

**Comment by saurabhsuniljain** [comment]
`this.props.ariaDescription`: "Analytics extension is disabled. You need to enable Analytics extension to use this feature. View Extensions"
`this.props.buttonText`: "View Extensions"
Narrator is reading out : "View Extenstions. Analytics extension is disabled. You need to enable Analytics extension to use this feature. View Extensions. Link Anlytics extension is disabled. You need to enable Analytics extension to use this feature. value : `this.props.buttonUrl`"

**Comment by kkjeer** [comment]
@saurabhsuniljain could you please create a codepen for this issue? I have so far been unable to repro it locally.

**Comment by saurabhsuniljain** [comment]
I have created a CodePen for this :  https://codepen.io/saurabhsuniljain/pen/qMdKrp

**Comment by kkjeer** [comment]
@saurabhsuniljain thank you for the codepen! For me, narrator reads out: "View Extenstions. Analytics extension is disabled. You need to enable Analytics extension to use this feature. Link http://localhost:8080/tfs/DefaultCollection//_admin/_extensions. Analytics extension is disabled. You need to enable Analytics extension to use this feature. Value: http://localhost:8080/tfs/DefaultCollection//_admin/_extensions.

I created a codepen showing a simple PrimaryButton example with an ariaDescription. https://codepen.io/kkjeer/pen/aavZoY 

Narrator reads out "Button Text aria description". It seems like the difference is that your example is wrapped inside a link, and Narrator is reading the extra properties associated with the link. Please let me know if there are any issues with the PrimaryButton example.
