### ISSUE TITLE
People picker occupies 70KB in production build

### ISSUE THREAD

**Issue by lijunle** [OfficeDev/office-ui-fabric-react#5991]
### Bug Report 
 
- __Package version(s)__: 6.50.2 
- __Browser and OS versions__: Windows 10 + Edge
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? **Yes**
 
Requested priority: Normal
 
Products/sites affected: A couple. This is performance issue.

#### Describe the issue:
 
I built an app only using people picker component. In production build, it increase around 70KB to support people picker, which is too big.

![capture](https://user-images.githubusercontent.com/1296500/44353358-465a9480-a4d9-11e8-8cd0-ac41ff6197e2.PNG)

### If applicable, please provide a codepen repro:
 
Test code: https://github.com/lijunle/test-fabric-react/blob/people-picker-bundle-size/src/App.js

/cc @dzearing @joschect

**Comment by dzearing** [comment]
do you have a treemap of the bundle content?

**Comment by lijunle** [comment]
Here it goes: [analysis.zip](https://github.com/OfficeDev/office-ui-fabric-react/files/2304556/analysis.zip)

**Comment by cliffkoh** [comment]
The obvious issue is that React-dom is in your bundle.. The Picker alone with all supporting OUFR utilities is 44.08kb.

I recommend externalizing React-DOM.

**Comment by micahgodbolt** [comment]
Is there an actionable issue here? Or is this just to kick off discussion.

**Comment by cliffkoh** [comment]
Closing because I believe the issue has been resolved.
