### ISSUE TITLE
Subtly off alignment for command bar icon buttons

### ISSUE THREAD

**Issue by billytrend** [OfficeDev/office-ui-fabric-react#5992]
### Bug Report 
 
- __Package version(s)__: 6.49.3
- __Browser and OS versions__: all
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal
 
Products/sites affected: (if applicable)
 
#### Describe the issue:
 
Alignment in the command bar looks weird for buttons with icons.
 
#### Actual behavior:
 
![image](https://user-images.githubusercontent.com/6671020/44353957-70dc2b80-a4a0-11e8-9da7-a886245d1df2.png)

![image](https://user-images.githubusercontent.com/6671020/44354070-c1ec1f80-a4a0-11e8-942e-1bfc6ffe8194.png)

![image](https://user-images.githubusercontent.com/6671020/44354991-39bb4980-a4a3-11e8-914d-c50a649388b1.png)

 
#### Expected 

More like this:

![image](https://user-images.githubusercontent.com/6671020/44353937-6326a600-a4a0-11e8-895d-6c700b559c1d.png)
 
![image](https://user-images.githubusercontent.com/6671020/44354346-869e2080-a4a1-11e8-8f29-0f925c9f981e.png)

### If applicable, please provide a codepen repro:
 
you can reproduce the fix by going to https://developer.microsoft.com/en-us/fabric#/components/commandbar and setting

`.flexContainer-46 {
    height: unset;
    align-items: unset;
}`

through developer tools (this will make some buttons look better and will break others so it is not a complete fix)

**Comment by billytrend** [comment]
(I'm aware this issue is very subtle but to me, the text looks like it should be higher in order to be properly aligned with the icon)

**Comment by billytrend** [comment]
perhaps this will make it clearer: 

![image](https://user-images.githubusercontent.com/6671020/44354655-50ad6c00-a4a2-11e8-8d0e-d4fa98236495.png)

**Comment by micahgodbolt** [comment]
with the 100% height that flexContainer is a lovely 38.1334 pixels tall. This probably causes some rounding errors in the layout

![image](https://user-images.githubusercontent.com/1434956/44434303-469d7300-a55f-11e8-80bb-f63c1acaeeea.png)

**Comment by micahgodbolt** [comment]
It's a box-sizing issue where 100% of the height when using border-box means parent height minus border.  Switch to content-box and 100% height includes the border.

**Comment by micahgodbolt** [comment]
One problem is that a Button can be rendered as an anchor tag when given an href, and buttons and anchors have different base styles. Buttons by default enter their children, but anchors do not....so removing height would mean that links no longer vertically center (i changed right example to link and bumped up height)

![image](https://user-images.githubusercontent.com/1434956/44434788-d04e4000-a561-11e8-8acd-56d83d99d290.png)

**Comment by micahgodbolt** [comment]
The solution appears to be removing the 100% height and changing button base to be inline-flex instead of inline-block.

Unfortunately this is bound to cause some css regressions for downstream partners.

**Comment by dzearing** [comment]
@micahgodbolt is there a low hanging solution here, or is this a won't fix? @mikewheaton might also have some suggestions.

**Comment by micahgodbolt** [comment]
not lineheight issue, it's the way that 100% calculates height (returns fractional when parent has 1px border) and how flexbox has rounding difference between two items of different height.

Actually, maybe we can force the icon to be the same height as the text...but this is a bit of a hack as well.


The best solution is to remove that 100% height and position the flexcontainer in the center at its default height.....but this requires converting the button to inline-flex

**Comment by billytrend** [comment]
Thanks for looking at this! Let me know if I can contribute to the fix although I probably don't have the context to understand the knock-on effects that you have mentioned

**Comment by micahgodbolt** [comment]
One possible fix (though again a bit of a hack) is to modify the icon height/lineheight to make it match up with the text next to it. Problem is that this will only work with the default button styles. Any custom styles would make this fix ineffective. 

The thing that baffles me right now is why when we set border width to 1px, we get a fractional width actually rendered

![image](https://user-images.githubusercontent.com/1434956/44535724-82dfe900-a6af-11e8-961f-e7956fa44d01.png)

**Comment by micahgodbolt** [comment]
@billytrend can you confirm what browser you are using? I'm noticing a different behavior in this fractional border issue between firefox and Chrome. Firefox seems to render borders fractionally smaller than specified, whereas chrome renders them at the exact width (therefore, we shouldn't have this subpixel rendering issues in chrome). I'm on win10 btw.

**Comment by billytrend** [comment]
I used chrome on macos to make these screenshots, however I also saw the issue in a screenshot someone sent me from edge a while ago

**Comment by micahgodbolt** [comment]
Those edge screenshots look odd. Looking at our current build in edge, everything looks pretty good. 

![image](https://user-images.githubusercontent.com/1434956/44612501-e0faf200-a7bd-11e8-824b-bcf1c82bf788.png)


At this point, I don't think I want to mess with the display value of our buttons, and while your height unsetting fixes buttons, it breaks our Button styled links (buttons get vertical centering for free). 

Right now, this doesn't feel high pri enough to warrant making a change the could possibly break a ton of downstream partners. I'm happy to keep investigating, or trying to isolate the issues, but for now I don't feel we should make any changes.
