### ISSUE TITLE
DetailsList item links blocked when Selection.setModal(true)

### ISSUE THREAD

**Issue by goodoldneon** [OfficeDev/office-ui-fabric-react#5994]
### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/goodoldneon/full/yxLMZa

### Bug Report 
 
- __Package version(s)__: 6.50.1
- __Browser and OS versions__: Chrome 68.0.3440.106
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: (if applicable)
 
#### Describe the issue:
 
For a `DetailsList` when `Selection.setModal(true)` is set, links rendered in the items are unclickable. They are blocked because checkCover span has `display: block`.

I assume the `display: block` is necessary to provide a clickable element for the modal, however sometimes elements inside the item should take priority over item selection.
 
#### Actual behavior:
 
Links rendered using an item's `onRender()` method are not clickable when `Selection.setModal(true)` is set.
 
#### Expected behavior:
 
A way to allow an item's element to be selectable, even when modal selection is enabled. Maybe via a a new attribute, like `data-selection-modal-pierce`?

**Comment by kkjeer** [comment]
Updated codepen: https://codepen.io/kkjeer/pen/xaxXWm

**Comment by goodoldneon** [comment]
That codepen doesn't solve the issue. It only seems like it does because the `Selection` object resets its `_modal` to `false` for some reason, which seems to be another issue.

Here's an updated codepen demonstrating the `_modal` reset:

https://codepen.io/goodoldneon/full/Jajpvx

**Comment by KevinTCoughlin** [comment]
I can confirm that `Selection.setModal(true)` blocks mouse interaction until reset (2nd click), but I'm confused about the use case and can't find a good example with our existing components. 

@goodoldneon why do you need to `setModal(true)` on your `<DetailsList/>`? I'd like to better understand that prior to attempting to fix this. Selection likely expects there to be a modal present for at least one click and therefore captures mouse events.

**Comment by goodoldneon** [comment]
On a Mac, I can't do a non-sequential multi-select (command-click) without `setModal(true)`. However, this type of select works on my Windows machine (with Ctrl-click).

**Comment by goodoldneon** [comment]
I think my original issue with the modal setting was a red herring. The real issue is that the meta key state is not checked during selection. PR #6301 fixes the meta key behavior in the DetailsList.

Sorry for making this confusing with my modal "problem" nonsense!
