### ISSUE TITLE
Sticky Header in DetailsList blocks the DetailsHeader untill scrolled down

### ISSUE THREAD

**Issue by basovic88** [OfficeDev/office-ui-fabric-react#6006]
### Bug Report

- __Package version(s)__: 6.23
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: (if applicable)

#### Describe the issue:

See the codepen example @ https://codepen.io/basovic88/pen/KxKLJX

I have a DetailsList with a Sticky Header. Initially the DetailsHeader is blocked. That is, you cannot click/sort/resize any columns. Only as soon as you start scrolling -- and the Sticky header is triggered -- the DetailsHeader is unblocked.

After checking the HTML, it seems that there is a placeholder element inside 'stickyAbove-83' with a z-index of 1 that blocks the DetailsHeader. After scrolling this placeholder element is hidden, and thus the header becomes accessible.

#### Actual behavior:

(1) I want to resize a column -- not possible.
(2) I scroll down a bit. Now I can resize columns.

#### Expected behavior:

(1) I want to resize a column. Not only after scrolling.

### Codepen repro:

https://codepen.io/basovic88/pen/KxKLJX

**Comment by kkjeer** [comment]
@basovic88 thank you for providing a codepen! Could you clarify the browser you're using and the exact steps you're taking? Unfortunately I haven't been able to repro this issue in Chrome.

**Comment by micahgodbolt** [comment]
I wasn't able to repro in windows 10 firefox either.

**Comment by basovic88** [comment]
Hi guys, thanks for checking. I can't reproduce the issue anymore either.... 
Whatever it was, it has cost me a lot of time. But most certainly the root cause of the issue lies outside of Fabric.

Issue closed.
