### ISSUE TITLE
Type 'IStyleSet' is not generic

### ISSUE THREAD

**Issue by hjodr** [OfficeDev/office-ui-fabric-react#6007]
### Bug Report 

Here is my package.json:

> "dependencies": {
>     "react": "16.4.2",
>     "react-dom": "16.4.2",
>     "office-ui-fabric-react": "6.50.2"
>   },
>   "devDependencies": {
>     "@types/history": "4.6.0",
>     "@types/react": "16.4.2",
>     "@types/react-dom": "16.0.7",
>     "@types/react-hot-loader": "3.0.3",
>     "@types/react-router": "4.0.12",
>     "@types/react-router-dom": "4.0.5",
>     "@types/webpack-env": "1.13.0",
>     "aspnet-webpack": "^2.0.3",
>     "aspnet-webpack-react": "^3.0.0",
>     "awesome-typescript-loader": "3.2.1",
>     "bootstrap": "3.3.7",
>     "css-loader": "0.28.4",
>     "event-source-polyfill": "0.0.9",
>     "extract-text-webpack-plugin": "2.1.2",
>     "file-loader": "0.11.2",
>     "isomorphic-fetch": "2.2.1",
>     "jquery": "3.2.1",
>     "json-loader": "0.5.4",
>     "react-hot-loader": "3.0.0-beta.7",
>     "react-router-dom": "4.1.1",
>     "style-loader": "0.18.2",
>     "typescript": "2.4.1",
>     "url-loader": "0.5.9",
>     "webpack": "2.5.1",
>     "webpack-hot-middleware": "2.18.2"
>   }
 
#### Describe
 Trying to build my project using npm (v 4.6.0) and webpack on Windows 10
 I'm getting the same error for a lot of uifabric libs.
 It looks like:    

>     ERROR in [at-loader] ./node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts:16:21 
>         TS2456: Type alias 'IStyleSet' circularly references itself.
>     
>     ERROR in [at-loader] ./node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts:16:49 
>         TS2315: Type 'IStyleSet' is not generic.
>     
>     ERROR in [at-loader] ./node_modules/@uifabric/merge-styles/lib/IStyleSet.d.ts:20:83 
>         TS2315: Type 'IStyleSet' is not generic.

**Comment by cliffkoh** [comment]
Recommend you upgrade to at least Typescript 2.8, preferably just directly to Typescript 3.0 :)

**Comment by hjodr** [comment]
Thank you for advice! It just broke all other modules that work with typescript, but I can fix it.
