### ISSUE TITLE
Cannot edit text input in Office-ui-fabric-react datepicker

### ISSUE THREAD

**Issue by naveenprasaths** [OfficeDev/office-ui-fabric-react#6008]
Hi,

I have created a date picker with Office-ui-fabric-react. I have enabled the "allowTextInput" property. I can able to edit the text input in Chrome, but its not working in IE 11. 

Observed behavior:
Chrome: Working fine in both Keyboard Navigation and in Mouse click.
IE 11: Working fine in Keyboard Navigation, but cannot able to edit on mouse click. 

Can someone help me on this?

**Comment by kkjeer** [comment]
Possibly related to #5953

**Comment by keepWalking** [comment]
Could we have any ETA here?

**Comment by naveenprasaths** [comment]
Any updates on this?

**Comment by micahgodbolt** [comment]
This may be down in the TextField component that's used by DatePicker, so i'll have our shield devs look at it.

**Comment by micahgodbolt** [comment]
After a little triage, it seems it may be related to the role="button" that we place on the input

**Comment by cschlechty** [comment]
Role="button" should have no usability impact, do you mean type="button"? I could see how that'd mess with things. You likely want a text input which launches a menu. I'll take a look later this afternoon if needed.

**Comment by micahgodbolt** [comment]
The prop I noticed was role="button", and it appears that removing it allows IE11 to edit the value in the input (which is what the OP is asking for). If I can simply remove it entirely, that's an easy fix.

![image](https://user-images.githubusercontent.com/1434956/44930118-2796a200-ad12-11e8-9060-bdf40206e2cd.png)

**Comment by cschlechty** [comment]
You may need to removed aria-expanded then and look at other ways to indicate the menu has opened. It looks like input isn't a supported element which is likely why the button role was added https://www.w3.org/TR/wai-aria-1.1/#aria-expanded It should maybe be a combo box with an owned dialog of the date menu..?

**Comment by kenotron** [comment]
Found an article listing this as a solution. I think that's what @cschlechty  is referring to:

```
<div aria-label=”Tag” role=”combobox” aria-expanded=”true” aria-owns=”owned_listbox” aria-haspopup=”listbox”>
  <input type=”text” aria-autocomplete=”list” aria-controls=”owned_listbox” aria-activedescendant=”selected_option”>
</div>
<ul role=”listbox” id=”owned_listbox”>
  <li role=”option”>Zebra</li>
  <li role=”option” id=”selected_option”>Zoom</li>
</ul>
```

**Comment by kenotron** [comment]
There's more info here: https://www.w3.org/TR/wai-aria-practices/examples/combobox/aria1.1pattern/listbox-combo.html
