### ISSUE TITLE
Poor documentation

### ISSUE THREAD

**Issue by newtonsheikh** [OfficeDev/office-ui-fabric-react#6009]
I find the office UI react fabric documentation poor/incomplete.

Forexample in the component <DetailList />

[https://developer.microsoft.com/en-us/fabric#/components/detailslist](url)
there is this code
`setKey="set"`
but it is no where explained what it does! The entire grid option Dokumention is missing or too cryptic to understand.

**Comment by kkjeer** [comment]
@newtonsheikh thank you for submitting an issue! The `setKey` property, along with all other properties, is documented in the `IDetailsListProps` interface in the "Implementation" section. `setKey` is "A key that uniquely identifies the given items. If provided, the selection will be reset when the key changes.".

Please feel free to reopen this issue or submit a new one if you have any further suggestions about how we can improve our documentation!

**Comment by newtonsheikh** [comment]
Are you sure its documented under IDetailsListProps? well i dont see it. 

I looked for i didnt find it. If its really missing please add it. 

![githubcomap](https://user-images.githubusercontent.com/5118869/44456628-ac9cff80-a61e-11e8-9d0b-044a1b880246.jpg)
