### ISSUE TITLE
TextField throws Textarea react warning in React 15.4.0

### ISSUE THREAD

**Issue by cliffkoh** [OfficeDev/office-ui-fabric-react#601]
### Bug Report

- 0.64.0

#### Describe the issue:

When `TextField` component is used to render a Textarea, the following warning occurs in console EVEN if a `defaultValue` was passed to `TextField`.

#### Actual behavior:
react-dom.js:18109 Warning: Textarea elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled textarea and remove one of these props. More info: https://fb.me/react-controlled-components

**Comment by dzearing** [comment]
Confirmed. Probably an easy fix.

http://codepen.io/dzearing/pen/ZBEVzw
