### ISSUE TITLE
Support [index:string] as prop name in documentation parser

### ISSUE THREAD

**Issue by AntyfrizZz** [OfficeDev/office-ui-fabric-react#6010]
There is a typo on that page https://developer.microsoft.com/en-us/fabric#/components/link

![image](https://user-images.githubusercontent.com/6909862/44398973-80b24900-a54e-11e8-8fb9-f7d1eb3d65d5.png)

**Comment by kkjeer** [comment]
This is due to the documentation parser only eating up until the first colon; it doesn't account for a property having a colon in it (in this case, [index: string]).
