### ISSUE TITLE
Command bar split button not to spec

### ISSUE THREAD

**Issue by suztocco** [OfficeDev/office-ui-fabric-react#6018]
- __Package version(s)__: Current 
- __Browser and OS versions__: Not sure
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? NO
 
Requested priority: NORMAL
 
Products/sites affected: OWA
 
#### Describe the issue:
 
The command bar split button does not seem to spec. 
- the chevron is too large. 
- it looks like the interactive font colors may not be correct (usually the icon and text get darker on hover/press).

I did not design this but would consult with Ben or the Fabric Sketch Design file for the Design spec.

 
#### Actual behavior:
 
![image](https://user-images.githubusercontent.com/20954039/44434516-579ab400-a560-11e8-97e4-2f9ed8505a85.png)
![image](https://user-images.githubusercontent.com/20954039/44434531-6aad8400-a560-11e8-9cb5-b0d6215cc699.png)
 
#### Expected behavior:
 
To look like the other command buttons

**Comment by suztocco** [comment]
@micahgodbolt - for you:)

**Comment by betrue-final-final** [comment]
Yes, @suztocco is correct. The split button should have identical styles to the dropdown, with the addition of a vertical line and margin. Can it just inherit?

**Comment by kenotron** [comment]
The "Reply All" Button doesn't show up for me in OWA mail conversation. Where can I see this in the CommandBar, @suztocco ?

**Comment by kenotron** [comment]
After looking at the OWA code, I noticed all the styles are overridden inside the OWA app itself, please follow up with Calendar team on this. I'm gonna take this offline and close this one.

**Comment by kenotron** [comment]
Per @micahgodbolt, Fabric side will fix the command bar icon sizing issue.

**Comment by suztocco** [comment]
@micahgodbolt  @kenotron 
Ken- If you take off Conversation mode in Mail and click on a message you will see the reply all in the command bar.

![image](https://user-images.githubusercontent.com/20954039/44689254-b4d4b080-aa0b-11e8-9f4d-9e6c38ac18ca.png)
