### ISSUE TITLE
ContextMenuItem: Strange rendering of Persona item

### ISSUE THREAD

**Issue by basovic88** [OfficeDev/office-ui-fabric-react#6022]
### Please provide a reproduction of the bug in a codepen:
 
Codepen example here:
https://codepen.io/basovic88/pen/Eeaeqm

### Bug Report 
 
 
- __Package version(s)__: 6.23
- __Browser and OS versions__: Firefox (latest)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
#### Describe the issue:
 
I render a Persona inside a ContextualMenuItem via the onRender prop.

By default the Persona does not display any text, only the initials. This is not the default behaviour when rendering the Persona in a vanilla div for instance.

Only after setting `showSecondaryText={true}` it shows `text` and `secondaryText`, **but still no `tertiaryText`**, eventhough the size is set to 72.
 
#### Expected behavior:

By default, show text/secondaryText/tertiaryText (if the size prop allows it) when the Persona is rendering inside a ContextualMenuItem.

**Comment by natalieethell** [comment]
Investigating this a little further, but it looks like the `lineHeight` attribute on the list styling is what's causing the issue:
https://github.com/OfficeDev/office-ui-fabric-react/blob/0f6c8f38ba0af3fac00c87a48911a46db6804885/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.styles.ts#L39-L48
