### ISSUE TITLE
ChoiceGroup focus() not taking focus to the selected choice #4049

### ISSUE THREAD

**Issue by shyama1208** [OfficeDev/office-ui-fabric-react#6025]
### Bug Report 
 
 
- __Package version(s)__: (5.112.1004) 
- __Browser and OS versions__: (fill this out if relevant)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? ( No)
 
Requested priority: (Normal) 
 
Products/sites affected: (VSTS)
 
#### Describe the issue:
 
Programmatically calling focus() on the choice group does not take focus to the selected key. Instead it takes focus to the last option in the choice group.
 
#### Actual behavior:
 

![image](https://user-images.githubusercontent.com/26054709/44452848-3942c000-a615-11e8-819b-25e9ebafd19c.png)

 
#### Expected behavior:
 
Focus should go back to the selected key

This issue was filed earlier which got auto closed #4049

**Comment by natalieethell** [comment]
Hey @shyama1208 thanks for submitting an issue! Could you provide reproduction of the bug in a CodePen? I'm having some trouble reproducing this behavior. Feel free to work off of this one: https://codepen.io/naethell/pen/oPbxGG.

**Comment by shyama1208** [comment]
Below is the codePen link with the repo.
https://codepen.io/shyama1208/pen/NLNvpj

Steps to repro - 
1. Select any option in the choice group.
2. Press 'Shift + tab' to get the focus on button.
3. Press enter.
4. Observe that the last item in the choiceGroup 'Month1' gets a black border.
