### ISSUE TITLE
enableShimmer only works on DetailsList, when "groups" prop is undefined

### ISSUE THREAD

**Issue by lafe** [OfficeDev/office-ui-fabric-react#6026]
### Please provide a reproduction of the bug in a codepen:
 
- [Working list with shimmer](https://codepen.io/anon/pen/dqPxYO)
- [Broken shimmer with just an additional `group` statement](https://codepen.io/anon/pen/eLmqRY)

### Bug Report 

- __Package version(s)__: 6.52.0
- __Browser and OS versions__: All tested combinations so far (IE 11, Edge, Chrome; Windows 7, Windows 10)
 
The `enableShimmer` flag is only passed to the `List`, if the `group` property evaluates to `false`. See [line 436](https://github.com/OfficeDev/office-ui-fabric-react/blob/eb8a15573c926c613d12a665fd6e5257455794ee/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.base.tsx#L436) as well as the differences between [line 441](https://github.com/OfficeDev/office-ui-fabric-react/blob/eb8a15573c926c613d12a665fd6e5257455794ee/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.base.tsx#L441) and [line 460](https://github.com/OfficeDev/office-ui-fabric-react/blob/eb8a15573c926c613d12a665fd6e5257455794ee/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.base.tsx#L460) in DetailsList.base.tsx.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No (unreliable build process and unsure about expectations - should the groups be rendered or not?)
 
Requested priority: (Blocking, High, Normal, Low) Low (can be fixed by making sure that the groups are only set when data is available)
 
Products/sites affected: (if applicable)
 
#### Describe the issue:
 
Shimmer is enabled in code for the `DetailsList`, but shimmer is not rendered.
 
#### Actual behavior:
 
Shimmer is not rendered.
 
#### Expected behavior:
 
Shimmer is rendered.

**Comment by natalieethell** [comment]
Hey @lafe, just spoke offline with @Vitalius1 who enabled Shimmer in DetailsList. 

Basically, we're eventually going to deprecate Shimmer in DetailsList and shift over to fully using ShimmeredDetailsList -- code [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/DetailsList/ShimmeredDetailsList.base.tsx) and example in the Shimmered Details List section [here](https://developer.microsoft.com/en-us/fabric#/components/shimmer). 

Additionally, it is not expected that `enableShimmer` will work for groups in DetailsLists, but what you can leverage is `onRenderMissingItem`, as demonstrated in an example in experiments: https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/experiments/src/components/Shimmer/examples/Shimmer.Application.Example.tsx.

What is your use case here? Would that work for you? Feel free to let us know if you have any other questions and I'm sure Vitalie could chime in as well.

**Comment by natalieethell** [comment]
Yeah, thanks for checking with us! I'll close this issue then.
