### ISSUE TITLE
Callout: Anything using Callout will auto dismiss if positioning is offscreen and focus is set within

### ISSUE THREAD

**Issue by kmees** [OfficeDev/office-ui-fabric-react#603]
### Bug Report

- __Package version(s)__: 0.76.0
- __Browser and OS versions__: Chrome 54 / OS X

#### Describe the issue:

When clicking a dropdown while the page is scrolled, the page will scroll to center the dropdown but not show any items

*scrolled*:
![scrolled](https://i.gyazo.com/7c65076e1b5e168d95517fc5c64613dd.gif)

*not scrolled* (removed all dom elements above with dev tools):
![not scrolled](https://i.gyazo.com/5bb90016aabb4861c753c1c768d0d89e.gif)

#### Actual behavior:

Clicking a dropdown only scrolls the page when the page is already scrolled

#### Expected behavior:

Clicking a dropdown shows the items

### If applicable, please provide a codepen repro:

Can be reproduced on the official docs page https://dev.office.com/fabric#/components/dropdown

**Comment by dzearing** [comment]
that's funny...

It seems related to nesting overflow areas inside each other.

**Comment by dzearing** [comment]
I'm changing the title of this bug because it's a more general issue with Callout, which affects many things. If we set focus to something within callout, and the callout is rendered offscreen, a scroll event is generated which causes dismiss to be called.

**Comment by dzearing** [comment]
Isolated repro
http://codepen.io/dzearing/pen/xRGXaL

**Comment by dzearing** [comment]
The issue is that LayerHost is not being position fixed, but it seems the positioning code assumes that.

**Comment by mibes** [comment]
Build 0.77.1 fixes this issue on Chrome (54.0.2840.98) and Firefox (50.0) on OSX. 

Unfortunately Safari (10.0.1) still demonstrates the same behaviour. The same is true for the embedded browser in Word.
