### ISSUE TITLE
Tooltip positions incorrectly on absolutely positioned element

### ISSUE THREAD

**Issue by evantrimboli** [OfficeDev/office-ui-fabric-react#6040]
### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/evantrimboli/pen/OoVEaL

### Bug Report 
 
 
- __Package version(s)__: "office-ui-fabric-react": "^6.33.0", 
- __Browser and OS versions__: Seems to apply to all browsers tested (FF/Chrome/Edge)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: N/A
 
#### Describe the issue:
 
Hover over the icon in the test case. The tip is not placed near the icon.
 
#### Actual behavior:
 
The tip displays away from the icon.
 
#### Expected behavior:
 
The tip should display near the icon.

**Comment by micahgodbolt** [comment]
Tooltip is going to be relative to the root, not the icon itself. You need to set the root to absolute if you want the tooltip to move with it.

**Comment by evantrimboli** [comment]
Can you clarify what you mean by "the root"? Does that refer to the `Fabric` element?

I had a mess around with a few different options, I would have expected setting the `Fabric` component to position: 'relative' would be enough.

Please see: https://codepen.io/evantrimboli/pen/qMOrmO

Is there a "better" way to do this?

**Comment by evantrimboli** [comment]
Sorry, I see what you're saying now: https://stackoverflow.com/questions/51995102/correctly-position-tooltip-for-absolutely-positioned-element
