### ISSUE TITLE
Add custom content on top/bottom of a ContextualMenu

### ISSUE THREAD

**Issue by basovic88** [OfficeDev/office-ui-fabric-react#6041]
**Describe the feature that you would like added**

I would like to add custom content to the top (or bottom) of a ContextualMenu.

Use cases are:
* showing a SearchBox on top of the menu so that the menu items can be easily filtered.
* showing favorites are last picked items (as tags) on the bottom of the menu

Currently I can add custom content by adding items with a custom onRender() function. However this content is part of the items and is thus not 'Sticky' in case the user scrolls through the items.

**What component or utility would this be added to**

The ContextualMenu is essentially a Callout. The Callout in turn is a Popup with scrollable content.

Perhaps two props can be added to the ContextualMenu (which have to be passed through to the Callout and ultimately the Popup): `onRenderAboveContent` and `onRenderBelowContent`.

**Have you discussed this feature with our team, and if so, who**

No.

**Additional context/screenshots**

Because the ContextualMenu is available in Buttons, Dropdown, Combobox and TextField it could greatly enhance the usability of all these components.

**Comment by micahgodbolt** [comment]
It looks like you're wanting to drop content before/after the ContexualMenuList. If you were to add an onRenderMenuList, you could add items before or after the default render. If you'd like to take a stab at creating that PR i'd be happy to review.

The list you'd need to pull into a render function can be found at 

https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.base.tsx#L313
