### ISSUE TITLE
Add whitespace and/or align viewcount on DocumentCard

### ISSUE THREAD

**Issue by Remi749** [OfficeDev/office-ui-fabric-react#6043]
**Describe the feature that you would like added**
On the DocumentCard there is a viewcount, the current position of the viewcount is a litte bit off, Underneath is a proposed design.

**What component or utility would this be added to**
DocumentCard

**Additional context/screenshots**
![image](https://user-images.githubusercontent.com/28678468/44520379-fe519280-a6cf-11e8-9625-998608934b10.png)

**Comment by kkjeer** [comment]
Spoke offline with @betrue-final-final the spacing between the icon and the view count text should be 8px.
