### ISSUE TITLE
Panel: Way to control escape key

### ISSUE THREAD

**Issue by nikhilexe** [OfficeDev/office-ui-fabric-react#6051]
I have hosted Monaco editor in panel which provides Find widget through 'Ctrl + F' shortcut. Currently if I press Escape key, it closes both Find widget and Panel as well. I want to close panel with Escape key only if Find widget is not there. 

Monaco editor give way to add specific key and check condition whether FindWidget is open or not. So basically now I want control when to close on escape key pressed. It would be good to expose some props for this.

**Comment by micahgodbolt** [comment]
Currently dismiss is being called as a callback within the Popup. Popup supplies the event to the function, but we're currently not using it.

![image](https://user-images.githubusercontent.com/1434956/44755362-bf11b000-aada-11e8-8594-8b0f0aa84c7f.png)

This wouldn't be a tough change, the prop is already there. Need to call 'onDismiss' before line 218, and pass in the event. User could call event.preventDefault if they wanted to (such as in the case of escape key and widget being open), and then we'd need to conditionally set state based on if e.defaultPrevented was true.

`if (this.state.isOpen && !ev.defaultPrevented)`
