### ISSUE TITLE
[Feature Request] Show tooltip near to mouse pointer

### ISSUE THREAD

**Issue by nikhilexe** [OfficeDev/office-ui-fabric-react#6052]
**Describe the feature that you would like added** Show tooltip near to my mouse pointer instead of showing in the middle of the element. If I have big text on which i want to show tooltip and my mouse pointer is in the beginning of the text, it doesn't look good to have tooltip far from the mouse pointer hanging in the middle of the text.

**What component or utility would this be added to** Tooltip

**Comment by j-te** [comment]
This feature may encourage non-responsive design, how would a mobile device see this?

You can anchor TooltipHost to any element, may I suggest rendering an IconButton that opens the Tooltip, or style your text in a way that encourages interaction.

**Comment by khmakoto** [comment]
@nikhilexe sorry for the long delay in answering! However, this goes against our design guidelines for the `Tooltip` component, so I'm going to resolve this issue as "Resolution: By Design". Please let us know if there is anything else we can do to help!
