### ISSUE TITLE
Unable to Load Fabric Components in SPFx

### ISSUE THREAD

**Issue by heythisispaul** [OfficeDev/office-ui-fabric-react#6054]
### Please provide a reproduction of the bug in a codepen:
 
The issue is only happening in SPFx - In both the offline and and online workbenches. 

### Bug Report 
 
 
```
{
  "name": "uwqueue",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "~1.4.1",
    "@microsoft/sp-lodash-subset": "~1.4.1",
    "@microsoft/sp-office-ui-fabric-core": "~1.4.1",
    "@microsoft/sp-webpart-base": "~1.4.1",
    "@pnp/common": "^1.1.4",
    "@pnp/graph": "^1.1.4",
    "@pnp/logging": "^1.1.4",
    "@pnp/odata": "^1.1.4",
    "@pnp/sp": "^1.1.4",
    "@types/react": "15.6.6",
    "@types/react-dom": "15.5.6",
    "@types/webpack-env": ">=1.12.1 <1.14.0",
    "axios": "^0.18.0",
    "office-ui-fabric-react": "^6.53.0",
    "react": "15.6.2",
    "react-dom": "15.6.2",
    "request": "^2.88.0"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.4.1",
    "@microsoft/sp-module-interfaces": "~1.4.1",
    "@microsoft/sp-webpart-workbench": "~1.4.1",
    "gulp": "~3.9.1",
    "@types/chai": ">=3.4.34 <3.6.0",
    "@types/mocha": ">=2.2.33 <2.6.0",
    "ajv": "~5.2.2"
  }
}
```
- __Browser and OS versions__: Browser is Chrome 68 and Windows 7.
 
#### Priorities and help requested:

Requested priority: Normal
 
Products/sites affected: (if applicable)
 
#### Describe the issue:

Inserting Fabric UI React components into an existing SPFx project causes what appears to be a webpack issue. Removing the components causes everything to return to normal.

#### Actual behavior:
 
I receive the following error message: 
Original error: ***Failed to load entry point from component "b6f2cfce-0ad5-4812-8c81-0ff49f7d7d20" (UwqueueWebPart).
Original error: Error loading https://component-id.invalid/b6f2cfce-0ad5-4812-8c81-0ff49f7d7d20_0.0.1
	__WEBPACK_IMPORTED_MODULE_1_react__.createContext is not a function

***INNERERROR:
***Failed to load entry point from component "b6f2cfce-0ad5-4812-8c81-0ff49f7d7d20" (UwqueueWebPart).
Original error: Error loading https://component-id.invalid/b6f2cfce-0ad5-4812-8c81-0ff49f7d7d20_0.0.1
	__WEBPACK_IMPORTED_MODULE_1_react__.createContext is not a function
***CALLSTACK:
Error
    at SPLoaderError.SPError [as constructor] (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:10183:24)
    at new SPLoaderError (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:4211:28)
    at Function.ErrorBuilder.buildErrorWithVerboseLog (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:3821:21)
    at Function.ErrorBuilder.buildLoadComponentError (https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:3743:21)
    at https://localhost:4321/node_modules/@microsoft/sp-loader/dist/sp-loader-assembly_en-us.js:7952:38
 
#### Expected behavior:
 
To have components render within the SPFx web part.

**Comment by dzearing** [comment]
It seems that SPFX is serving you React 15, while Fabric 6 requires React 16. This is more of an SPFX issue that can occur with ANY library you use which depends on React 16 API.

I am following up with the SPFX guys to identify when they plan to support React 16. In the meantime, your safest action is to downgrade to Fabric 5.x (which will always support React 15.) Or, you can stick with your last working version (before the Customizer React 16 change.)

We are temporarily reverting the React 16 context usage, because we found that we also need to upgrade Layers to use React 16 Portals, which support the new context usage. Pretty tricky to follow a moving target. :) But this will come back shortly, which could break your SPFX scenario until SPFX officially supports React 16.

**Comment by dzearing** [comment]
Related: https://github.com/SharePoint/sp-dev-docs/issues/1315

**Comment by dzearing** [comment]
Being this isn't an issue with Fabric specifically, and is a problem with SPFX not supporting anything externalizing react, and requiring react 16, we should use the Sharepoint/sp-dev-docs bug to track. Closing here.
