### ISSUE TITLE
Sticky TypeError cause Fabric UI render failed

### ISSUE THREAD

**Issue by luckyyd** [OfficeDev/office-ui-fabric-react#6056]
Bug Report
Package version(s): 5.106.1
Browser and OS versions: Chrome v67 and Edge 42
Priorities and help requested (not applicable if asking question):
Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: (if applicable) MS privacy PDAM tool

Describe the issue:
There are cases when fabric ui failed to render icon and display incorrect style.
I used a DetailsList component with Sticky component as the header to stay in fixed position when scroll down. The error was shown when first loading the page sometimes (not every time, but still happened often, quiet tricky to repro), when reload the page (F5) sereral times, the error disappeared.

Actual behavior:
![image](https://user-images.githubusercontent.com/12855573/44561068-5d251380-a785-11e8-9024-c525dbc93b4a.png)

![image](https://user-images.githubusercontent.com/12855573/44561102-82b21d00-a785-11e8-8945-003ebc6b21bc.png)

Expected behavior:
![image](https://user-images.githubusercontent.com/12855573/44561082-657d4e80-a785-11e8-8ed5-7995435d3d93.png)

**Comment by natalieethell** [comment]
Hey thanks for submitting this issue! Looks like currElem needs another null check. I'll submit a PR with the fix.
