### ISSUE TITLE
[merge-styles] Processed style sets' subcomponent properties cannot be passed as styles prop due to type mismatch.

### ISSUE THREAD

**Issue by Nimelrian** [OfficeDev/office-ui-fabric-react#6060]
### Please provide a reproduction of the bug in a codepen:
 
Codepen doesn't provide TS typechecking, so here's a reproduction repository: https://github.com/Nimelrian/OfficeFabric-SubComponentStyles-bug

Just clone it, run yarn / npm install and either compile it using yarn / npm build or open it in VS Code. App.tsx shows the typing error.

### Bug Report 
 
 
- __Package version(s)__:
  - @uifabric/merge-styles: 6.7.0
  - office-ui-fabric-react: 6.53.0
  - typescript: 3.0.1
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: (Blocking, High, Normal, Low): High, as it renders subComponentStyles useless
 
#### Describe the issue:
 
The helper type `IProcessedStyleSet` maps all properties of a `Styles` interface's `subComponentStyles` to `IStyleFunction<any, IStyleSet<any>>`. This causes type mismatches when trying to pass these to other components via the `styles` prop.

#### Behavior prerequisites:
The following code is given:
```ts
interface IStyles {
  root: IStyle
  subComponentStyles: {
    choiceGroup: IStyleFunctionOrObject<IChoiceGroupStyleProps, IChoiceGroupStyles>;
  }
}

const getStyles = (): Partial<IStyles> => ({
  root: {
    background: "red"
  },
  subComponentStyles: {
    choiceGroup: {
      root: {
        background: "green"
      }
    }
  }
})

const getClassNames = classNamesFunction<{}, IStyles>();

class App extends React.Component {
  public render() {
    const classNames = getClassNames(getStyles);
    return (
      <div className={classNames.root}>
        <ChoiceGroup
          options={[{ key: "1", text: "1" }, { key: "2", text: "2" }]}
          styles={classNames.subComponentStyles.choiceGroup}
        />
      </div>
    );
  }
}
```

#### Actual behavior:
 
A typing error occurs at the `styles` prop of `ChoiceGroup`:
```
Type 'IStyleFunction<any, IStyleSet<any>>' is not assignable to type 'IStyleFunction<IChoiceGroupStyleProps, IChoiceGroupStyles> | Partial<IChoiceGroupStyles> | undefined'.
  Type 'IStyleFunction<any, IStyleSet<any>>' is not assignable to type 'IStyleFunction<IChoiceGroupStyleProps, IChoiceGroupStyles>'.
    Type 'Partial<IStyleSet<any>>' has no properties in common with type 'Partial<IChoiceGroupStyles>'.
```
 
#### Expected behavior:
 
No typing errors occur.

#### Proposal:
Change the typing of IProcessedStyleSet to automatically infer the types of the StyleFunctions. I'll create a PR for this and refer this issue from there.

**Comment by dzearing** [comment]
@cliffkoh can you take a look?

**Comment by cliffkoh** [comment]
It would be great if we can infer but you can at present do a cast from IStyleFunction<any, any> to `IStyleFunction<IChoiceGroupStyleProps, IChoiceGroupStyles>`.

So 
```ts
class App extends React.Component {
  public render() {
    const classNames = getClassNames(getStyles);
    return (
      <div className={classNames.root}>
        <ChoiceGroup
          options={[{ key: "1", text: "1" }, { key: "2", text: "2" }]}
          styles={
            classNames.subComponentStyles.choiceGroup as IStyleFunction<
              IChoiceGroupStyleProps,
              IChoiceGroupStyles
            >
          }
        />
      </div>
    );
  }
}
```

Of course it would be better if this cast isn't necessary...

**Comment by cliffkoh** [comment]
As mentioned in the PR the main reason we never inferred was because we were trying to avoid a hard dependency on TS 2.8 :) But I think that TS 2.8 is old enough that we should be good with using conditional types by now... (at the end of the day, the concern here is that it mandates our downstream consumers also upgrade to TS 2.8+, as opposed to us not trusting TS 2.8's stability).
