### ISSUE TITLE
[TextField] Using text field styles in subComponentStyles of another style interface causes typing issues

### ISSUE THREAD

**Issue by Nimelrian** [OfficeDev/office-ui-fabric-react#6066]
### Please provide a reproduction of the bug in a codepen:
 
Codepen doesn't provide TS typechecking, please refer to the code below and try it yourself locally.

### Bug Report 
 
 
- __Package version(s)__:
  - @uifabric/merge-styles: 6.7.0
  - office-ui-fabric-react: 6.53.0
  - typescript: 3.0.1
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes (If the reason for this issue is found and a fix can be made)
 
Requested priority: (Blocking, High, Normal, Low): High
 
#### Describe the issue:
 
When using a style interface which has a `subComponentStyles` property for a text field, typing errors occur when trying to pass the interface to e.g. IStyleFunction.

#### Behavior prerequisites:
The following code is given:
```ts
interface IStyles {
  root: IStyle
  subComponentStyles: {
    choiceGroup: IStyleFunctionOrObject<ITextFieldStyleProps, ITextFieldStyles>;
  }
}

type Test = IStyleFunction<{}, IStyles>;
```

#### Actual behavior:
 
A typing error occurs whenn supplying the IStyles interface as second parameter to IStyleFunction:
```
Type 'IStyles' does not satisfy the constraint 'IStyleSet<IStyles>'.
  Type 'IStyles' is not assignable to type '{ subComponentStyles?: { choiceGroup: IStyleFunctionOrObject<any, IStyleSet<any>>; } | undefined; }'.
    Types of property 'subComponentStyles' are incompatible.
      Type '{ choiceGroup: IStyleFunctionOrObject<ITextFieldStyleProps, ITextFieldStyles>; }' is not assignable to type '{ choiceGroup: IStyleFunctionOrObject<any, IStyleSet<any>>; }'.
        Types of property 'choiceGroup' are incompatible.
          Type 'IStyleFunctionOrObject<ITextFieldStyleProps, ITextFieldStyles>' is not assignable to type 'IStyleFunctionOrObject<any, IStyleSet<any>>'.
            Type 'IStyleFunction<ITextFieldStyleProps, ITextFieldStyles>' is not assignable to type 'IStyleFunctionOrObject<any, IStyleSet<any>>'.
              Type 'IStyleFunction<ITextFieldStyleProps, ITextFieldStyles>' is not assignable to type 'IStyleFunction<any, IStyleSet<any>>'.
                Type 'Partial<ITextFieldStyles>' is not assignable to type 'Partial<IStyleSet<any>>'.
                  Types of property 'subComponentStyles' are incompatible.
                    Type 'ITextFieldSubComponentStyles | undefined' is not assignable to type '{ [x: string]: IStyleFunctionOrObject<any, IStyleSet<any>>; } | undefined'.
                      Type 'ITextFieldSubComponentStyles' is not assignable to type '{ [x: string]: IStyleFunctionOrObject<any, IStyleSet<any>>; }'.
                        Index signature is missing in type 'ITextFieldSubComponentStyles'.

```
 
#### Expected behavior:
 
No typing errors occur.

**Comment by cliffkoh** [comment]
This will work

```ts
interface IStyles extends IStyleSet<IStyles> {
    root: IStyle
    subComponentStyles: {
      choiceGroup: IStyleFunctionOrObject<ITextFieldStyleProps, IStyleSet<ITextFieldStyles>>;
    }
  }
  
  type Test = IStyleFunction<{}, IStyles>;
```

**Comment by Nimelrian** [comment]
Strangely enough it does. This seems weird to me, since ITextFieldStyles already defines itself as extending `IStyleSet<ITextFieldStyles>`.

Things working again aside, why do I have to add the `IStyleSet` wrapper for the TextField styles, but not for e.g. `IChoiceGroupStyles`, where everything works out of the box?

Closing since the original issue has been solved.

**Comment by redoz** [comment]
I'm still running into this, changing it to `IStyleSet<ITextFieldStyles>` makes `classNamesFunction` happy, but now it won't accept that there is an 'errorMessage' style:
```
Type '{ errorMessage: { display: string; }; }' is not assignable to type 'IStyleFunctionOrObject<ITextFieldStyleProps, IStyleSet<ITextFieldStyles>>'.
  Object literal may only specify known properties, and 'errorMessage' does not exist in type 'IStyleFunctionOrObject<ITextFieldStyleProps, IStyleSet<ITextFieldStyles>>'.ts(2322)
```

This is what I have now:
```
export interface EditorStyleProps {
    className?: string;
    width: number | string;
    theme: ITheme;
}

export interface EditorSubComponentStyles {
    textField: IStyleFunctionOrObject<ITextFieldStyleProps, IStyleSet<ITextFieldStyles>>;
    dealDescription: IStyleFunctionOrObject<ILinkStyleProps, ILinkStyles>;
}

export interface EditorStyles {
    root: IStyle;
    subComponentStyles: EditorSubComponentStyles;
}
```
Why do some of the style types in OUFR extend `IStyleSet<T>` and some don't? 
And in the same vein, is there an example that shows current best practices, it seems like guidance has evolved over time but not all components have been brought forward, and I'm finding it difficult to know what the current recommendation is. 

@cliffkoh Not sure what the thought is on commenting on closed issues,  should I create a new one instead?
