### ISSUE TITLE
Using styles for list items

### ISSUE THREAD

**Issue by trickydisco78** [OfficeDev/office-ui-fabric-react#6072]
The code examples you have list

`import './List.Ghosting.Example.scss';`

I notice in 
`office-ui-fabric-react/lib/List/examples/`

you have got some styles listing in a js file. How do i use these in my fabric components?

For example i want the corresponding classes for these
```

    <div className="ms-ListBasicExample-itemCell" data-is-focusable={true}>
        <Image
          className="ms-ListBasicExample-itemImage"
          src={item.thumbnail}
          width={50}
          height={50}
          imageFit={ImageFit.cover}
        />
        <div className="ms-ListBasicExample-itemContent">
          <div className="ms-ListBasicExample-itemName">{item.name}</div>
          <div className="ms-ListBasicExample-itemIndex">{`Item ${index}`}</div>
          <div className="ms-ListBasicExample-itemDesc">{item.description}</div>
        </div>
        <Icon className="ms-ListBasicExample-chevron" iconName={getRTL() ? 'ChevronLeft' : 'ChevronRight'} />
      </div>
```

How do i pull in ms-ListBasicExample-itemCell and other classes in my component?

**Comment by kkjeer** [comment]
Hi @trickydisco78, unfortunately we don't expose our class names from example .scss files. We are working on making the styling in our examples easier to incorporate. Thank you for bringing this to our attention!
