### ISSUE TITLE
Persona: Add 20px size

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#6074]
**Describe the feature that you would like added**
The new Fluent toolkit includes a 20px Persona. This size does not exist currently.

**What component or utility would this be added to**
Persona

**Have you discussed this feature with our team, and if so, who**
This is in the Fluent toolkit.

**Additional context/screenshots**
![image](https://user-images.githubusercontent.com/1382445/44606122-db42e380-a7a0-11e8-84a7-ebfe51924bf9.png)

**Comment by micahgodbolt** [comment]
@mikewheaton has this been added yet? was your team planning on doing it?

**Comment by mikewheaton** [comment]
@micahgodbolt I completed an audit of the Fluent toolkit, Fabric React, and the website and found many inconsistencies. This was right before the holidays and we haven't discussed it yet to come up with a plan.

**Comment by xugao** [comment]
@mikewheaton - what's the latest on this? is this still relevant? the issue has been one year old :)
