### ISSUE TITLE
FormDropdown "selectedKey" not working

### ISSUE THREAD

**Issue by leugene-microsoft** [OfficeDev/office-ui-fabric-react#6077]
### Bug Report 
 
 "office-ui-fabric-react": "^6.52.0",
 
#### Priorities and help requested:
 
Requested priority: High - Normal
 
Products/sites affected: Feedback Hub on the web
 
#### Describe the issue:
 
FormDropdown "selectedKey" not working
 
#### Actual behavior:
 
Using "selectedKey" doesn't do anything.
Eg:

<FormDropdown
          key={"0"}
          id={"0"}
          title={"Device:"}
          options={[
            {
              key: "PC",
              text: "PC"
            },
            {
              key: "Mobile",
              text: "Mobile"
            },
            {
              key: "HoloLens",
              text: "HoloLens"
            }
          ]}
          selectedKey="PC"
        />
 
#### Expected behavior:
 
Using "selectedKey" should update the dropdown accordingly.

**Comment by micahgodbolt** [comment]
FormDropdown is an experiment checked in several months ago, but no longer maintained by the original author. We expect to remove it in the future. If you'd like to use it in a project I'd recommend forking the code and maintaining it locally. 

Is there a way we can better communicate the state of experimental components? We never intended for them to make their way into production, as they have no service guarantee.

**Comment by leugene-microsoft** [comment]
For clarification FormDropdown is my wrapper around Dropdown. The issue is with the Dropdown component.
