### ISSUE TITLE
is-focusVisible is still used by ChoiceGroupOption.styles.ts

### ISSUE THREAD

**Issue by angelo-mollame** [OfficeDev/office-ui-fabric-react#6080]
Apparently initializeFocusRects.ts transitioned from the "ms-Fabric is-focusVisible" class to the "ms-Fabric--isFocusVisible" class, with [this commit](https://github.com/OfficeDev/office-ui-fabric-react/commit/2bbc7950bd9f10ea1e792dcb1155c625aa8e8f4f#diff-02f63d70a330ea6c7423fd3a167b4517).

However:
- there is still a reference to "is-focusVisible" in a comment in initializeFocusRects.ts
- ChoiceGroupOption.styles.ts still uses "is-focusVisible"

**Comment by micahgodbolt** [comment]
Good catch. That will cause some issues as the selector would never match.

![image](https://user-images.githubusercontent.com/1434956/44680295-30296880-a9f2-11e8-9a63-830a5e2b03a6.png)
