### ISSUE TITLE
Dropdown label has 8px extra bottom margin

### ISSUE THREAD

**Issue by enriquin** [OfficeDev/office-ui-fabric-react#6082]
The dropdown label has 8px extra margin at the bottom and it breaks the layouts, since the fields are not aligned vertically anymore.

Here is a codepen showing the extra margin: https://codepen.io/Intnovaction/pen/EePqGq

You can see that the label pushes down the dropdown and breaks the alignment between the Dropdown and the text filed, which should be vertically aligned.

Are you willing to submit a PR to fix? NO
 
Requested priority: Normal

Thanks!

**Comment by dzearing** [comment]
@betrue-final-final Just a heads up here, this one would move some pixels. I _think_ after inspecting it and comparing it with textfield and combobox, the 8px is wrong and that we should remove it for consistency. What do you think?

**Comment by betrue-final-final** [comment]
I agree. The extra 8px should be removed.
