### ISSUE TITLE
ComboBox input field is empty while dropdown is visible

### ISSUE THREAD

**Issue by petercutting** [OfficeDev/office-ui-fabric-react#6084]
When the dropdown is dismissed (TAB) then all my dropdown selections (multiSelect) get listed in the input field. Great

But when I click on the down carret to bring up the dropdown again then the input field is cleared. Why is this? seems wrong to me. I would like the input field to reflect what is currently selected in the visible dropdown

**Comment by petercutting** [comment]
I forgot to mention that I dont want editing in the input field so I have allowFreeform false.  I think a visual cue could indicate read only in the input field

**Comment by jspurlin** [comment]
Seems like there's something wonky going on with pending multi-select values. Adding @stanleyymsft who added multiselect functionality to comboBox

**Comment by micahgodbolt** [comment]
@stanleyymsft @jspurlin any updates on this issue?

**Comment by Vitalius1** [comment]
@petercutting closing this issue in favor of #7558 which is a duplicate of yours but has a little bit more fresh info and discussion from the developer who implemented the multi-select feature in `ComboBox`.
