### ISSUE TITLE
MessageBar: JAWS + NVDA not announcing the message inside message bar component

### ISSUE THREAD

**Issue by mdmdakbar** [OfficeDev/office-ui-fabric-react#6085]
Products/sites affected: VSTS
 
#### Describe the issue:
 
JAWS and NVDA are not announcing the message inside the component on the other hand narrator is behaving properly.
 
My configurations:
JAWS+Chrome (Not working)
NVDA+Chrome (Not working)
Narrator+Edge (Working)

Codepen:
https://codepen.io/mdmdakbar/pen/NLGOyZ
 
At every places in our product where it is being used is broken.

**Comment by mdmdakbar** [comment]
Yes, I tried the messageBar component and in codepen you can see the implementation of it where JAWS is not reading. 
I tried something like putting role="status" aria-live="assertive" on a simple div element
to test if JAWS work fine with aria live or not but there everything works fine. 

Refer codepen: https://codepen.io/mdmdakbar/pen/NLNapL for more info.

I tried to figure out why but didn't get any thing which can help me to debug further

**Comment by dzearing** [comment]
@aneeshack4 could you take a look and determine if this is a bug or not?

**Comment by aneeshack4** [comment]
@dzearing yup!

**Comment by aneeshack4** [comment]
Hi @mdmdakbar, thank you for reporting this. Apologies for the delayed response. I finally got some time to circle back to this. Narrator + Edge and Narrator + Chrome both work as you can see from the "This is an error message" in the Narrator output highlighted below. (the first image is Chrome, second is Edge). 
![image](https://user-images.githubusercontent.com/4161791/49970800-50b5f980-fee1-11e8-844b-806145942a61.png)
![image](https://user-images.githubusercontent.com/4161791/49970968-d46fe600-fee1-11e8-9ed7-019fa3346053.png)
I tested NVDA+Chrome and NVDA+Edge on your codepen and they're both being read out also (I don't know of any tool like NarratorBuddy for NVDA so I can't show the output). So I don't think this repros anymore. Marking not repro but if you still find that there's a problem please let me know!
