### ISSUE TITLE
Cursor wrap around issue in MaskedTextField

### ISSUE THREAD

**Issue by jlubben** [OfficeDev/office-ui-fabric-react#6092]
When using MaskedTextField:
`<MaskedTextField label="This is a label" mask="(9999" />`
A user can keep hitting backspace/delete and get to the string "(____" and the cursor remains in the right spot.

However, using MasktedTextfield with a mask of only masked characters is where problems begin to form:
`<MaskedTextField label="This is a label" mask="9999" />`
A user can keep hitting backspace and the cursor wraps around. So instead, if the cursor is at the bar position "_|___" for an empty string, and a user hits backspace, the cursor moves to "____|".

There is a working condition for if the cursor is in "|____" for an empty string and hitting backspace, it stays at "|____".

Having the cursor at position 1 is where the bug is.

**Comment by micahgodbolt** [comment]
Can you repro this in a codepen?

**Comment by jlubben** [comment]
[https://codepen.io/anon/pen/gdryxP#anon-login]

In the second example, if you click in the middle of the text and keep hitting backspace, the cursor wraps around because it never reaches the 0 position.

If you click directly at the 0 position, it does not wrap around.

**Comment by micahgodbolt** [comment]
![cal](https://user-images.githubusercontent.com/1434956/44747437-0b042b00-aac2-11e8-8e7a-3ef52c802407.gif)
