### ISSUE TITLE
Customizable foregoes type-safety

### ISSUE THREAD

**Issue by richardtagger** [OfficeDev/office-ui-fabric-react#6102]
### Bug Report 

`customizable` is typed such that customized components return `any` thus disabling TypeScript's type safety.

We're unable to do this without losing types:-
```ts
export default customizable('MyComponent', ['theme'])(MyComponent);
```

Current workaround is doing something like:-
```ts
const customComponent: ComponentType<CardProps> = customizable('MyComponent', ['theme'])(MyComponent);
export default customComponent;
```

Offending line https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/utilities/src/customizable.tsx#L16

**Comment by micahgodbolt** [comment]
@JasonGore do we have good guidance around this? Is it a TS version limitation?

**Comment by dzearing** [comment]
Can you not use customizable as a decorator? That was the intent.

```tsx
@customizable('Button', [...])
class Button ...
```
