### ISSUE TITLE
codepen-example-transform is printing the component code twice

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#6103]
codepen-example-transform is printing the component code twice

![image](https://user-images.githubusercontent.com/1434956/44693205-6f1fe400-aa1b-11e8-92c9-b25ab40988fc.png)

**Comment by micahgodbolt** [comment]
saw this duplication when looking at a users submitted issue/codepen. But on the plus side, it looks like people are using them!

**Comment by kenotron** [comment]
I know the source of this issue... it's probably in the jscodeshift API ...
