### ISSUE TITLE
onChange prop duplicated and inconsistent between Dropdown and SelectableDroppableText

### ISSUE THREAD

**Issue by NullMDR** [OfficeDev/office-ui-fabric-react#6104]
### Please provide a reproduction of the bug in a codepen:

It's a ts compile error so not applied.
 

### Bug Report 
 
 
- __Package version(s)__: 6.56.0
- __Browser and OS versions__: N/A
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) Yes
 
Requested priority: (Blocking, High, Normal, Low) Normal
 
Products/sites affected: (if applicable) N/A
 
#### Describe the issue:
 
When build my project with webpack, typescript, and office-ui-fabric-react, the typescript compiler drops error messages on fabric ui typescript definitions:

```
ERROR in C:/myproject/node_modules/office-ui-fabric-react/lib/components/Dropdown/Dropdown.types.d.ts(13,18):
TS2430: Interface 'IDropdownProps' incorrectly extends interface 'ISelectableDroppableTextProps<HTMLDivElement>'.
  Types of property 'onChange' are incompatible.
    Type '((event: FormEvent<HTMLDivElement>, option: IDropdownOption, index?: number | undefined) => void) | undefined' is not assignable to type '((event: FormEvent<HTMLDivElement>, option?: ISelectableOption | undefined, index?: number | undefined) => void) | undefined'.
      Type '(event: FormEvent<HTMLDivElement>, option: IDropdownOption, index?: number | undefined) => void' is not assignable to type '(event: FormEvent<HTMLDivElement>, option?: ISelectableOption | undefined, index?: number | undefined) => void'.
        Types of parameters 'option' and 'option' are incompatible.
          Type 'ISelectableOption | undefined' is not assignable to type 'IDropdownOption'.
            Type 'undefined' is not assignable to type 'IDropdownOption'.
```

tsconfig.json
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "module": "esnext",
    "moduleResolution": "node",
    "target": "es5",
    "jsx": "react",
    "experimentalDecorators": true,
    "sourceMap": true,
    "skipDefaultLibCheck": true,
    "strict": true,
    "types": [ "webpack-env" ],
    "importHelpers": true,
    "lib": ["dom", "es2017"],
    "paths": {
      "~/*": [ "ClientApp/*" ]
    },
    "typeRoots": [
      "ClientApp/models"
    ]
  },
  "exclude": [
    "bin",
    "node_modules"
  ]
}
```

typescript: 3.0.1
ts-loader: 4.5.0
webpack: 4.17.1

It could be mitigated with `"skipLibCheck": true` in tsconfig.json.

#### Actual behavior:
 
My build breaks on typescript.
 
#### Expected behavior:
 
Build should pass without error.

**Comment by NullMDR** [comment]
Confirmed that it is caused by mismatched typescript version, as this library uses 2.8.4 and I use 3.0.1

**Comment by joechung-msft** [comment]
It isn't a TypeScript version issue; it's a strict mode issue.  It's because of the mismatch between these two types:

Dropdown.types.d.ts
````ts
export interface IDropdownProps extends ISelectableDroppableTextProps<HTMLDivElement> {
    /**
     * Callback issued when the selected option changes.
     */
    onChange?: (event: React.FormEvent<HTMLDivElement>, option: IDropdownOption, index?: number) => void;
````

SelectableDroppableText.types.d.ts
````ts
export interface ISelectableDroppableTextProps<T> extends React.HTMLAttributes<T> {
    /**
     * Callback issued when the selected option changes.
     */
    onChange?: (event: React.FormEvent<T>, option?: ISelectableOption, index?: number) => void;
````

The `option` parameter is required in `option: IDropdownOption` but optional in `option?: ISelectableOption`.

**Comment by micahgodbolt** [comment]
Seems neither dropdown, nor combobox (which use that interface) actually rely on it for onChange. ComboBox even has a 4th param, so not even close.

Since we don't export ISelectableDroppableTextProps in our package, it should be safe to pull that onChange out.
