### ISSUE TITLE
ComboBox input not styled when using themes

### ISSUE THREAD

**Issue by joechung-msft** [OfficeDev/office-ui-fabric-react#6105]
### Please provide a reproduction of the bug in a codepen:
https://codepen.io/joechung-msft/pen/vzKKrV

### Bug Report 
 
 
- __Package version(s)__: 6.56.0
- __Browser and OS versions__: 
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No
 
Requested priority: (Blocking, High, Normal, Low) Normal
 
Products/sites affected: (if applicable)
 
#### Describe the issue:
 
The combo box does not style its input field when themes are used.

As a workaround, I have set styles to this:
````ts
let styles = {
  input: {
    backgroundColor: theme.palette.bodyBackground, // getTheme().semanticColors.bodyBackground
    color: theme.palette.bodyText // getTheme().semanticColors.bodyText
  }
};
````
 
#### Actual behavior:
 
The combo box input field is not styled. 
![image](https://user-images.githubusercontent.com/26208574/44701831-6ba15280-aa45-11e8-9bf6-424f28042ad0.png)

#### Expected behavior:

The combo box input field should be styled in accordance with the theme. 
![image](https://user-images.githubusercontent.com/26208574/44701817-5fb59080-aa45-11e8-8bb1-0e46bd8339ae.png)

**Comment by micahgodbolt** [comment]
Yeah, seems the input background color isn't being specified at all

![image](https://user-images.githubusercontent.com/1434956/44737956-485bbf00-aaa8-11e8-9d4d-59e69c57ee44.png)
