### ISSUE TITLE
Slider onChange event should be triggered when the mouse click has been released

### ISSUE THREAD

**Issue by blandine** [OfficeDev/office-ui-fabric-react#6108]
### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/anon/pen/KxMxmW

### Bug Report 

- __Package version(s)__: 6.19.0
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Maybe
 
Requested priority: Normal
 
#### Describe the issue:
 
An onChange event is fired for any mouse movement when the user is "sliding".  In the codepen, a console.log is displayed for any movement of the mouse when the user chooses a number.

The onChange event should be fired when the user has released the mouse.
Or maybe it could be nice to have some kind of onBlur event?

Thanks

**Comment by micahgodbolt** [comment]
We certainly don't want to change the existing behavior, as users are certainly relying on the current onChange event firing. onBlur is certainly feasible though if you only wanted to poll the data when the user was finished with the slider.
