### ISSUE TITLE
ChoiceGroup: Circle is out of alignment in Fluent experiment

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#6116]
### Bug Report 
 
- __Package version(s)__: Latest experiment
- __Browser and OS versions__: All
 
#### Describe the issue:
 
The selected circle is not centered:
![image](https://user-images.githubusercontent.com/1382445/44744495-21a68400-aaba-11e8-9326-cf4dbde816d7.png)

**Comment by Vitalius1** [comment]
Closed in #6739
