### ISSUE TITLE
Fluent Experiment: Button colors are incorrect

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#6117]
### Bug Report 
 
- __Package version(s)__: Latest experiments package
- __Browser and OS versions__: All
 
#### Describe the issue:
 
![image](https://user-images.githubusercontent.com/1382445/44744615-66cab600-aaba-11e8-9062-4a0de0220e5c.png)
![image](https://user-images.githubusercontent.com/1382445/44744673-85c94800-aaba-11e8-89c9-8b0e8b3d58ac.png)

**Comment by Jahnp** [comment]
Closing as this has been resolved with #6361.
