### ISSUE TITLE
Color utility in @uifabric/styling

### ISSUE THREAD

**Issue by Vitalius1** [OfficeDev/office-ui-fabric-react#6121]
**Describe the feature that you would like added**

Would be useful to start a color utility module in the Styling package similar to the one we have in OUFR/utilities folder. Maybe even consider moving the entire folder from OUFR and leave an entry point reexporting it from styling package. Need to know if the OUFR bundle size will be detrimentally affected by this.

**What component or utility would this be added to**

Should be included in `@uifabric/styling` package.

**Have you discussed this feature with our team, and if so, who**

Philip Kuo (@phkuo )

**Additional context/screenshots**

After adding a new function into the Styling package with this [PR](https://github.com/OfficeDev/office-ui-fabric-react/pull/6115) I had to create a small helper function for converting a color from a hex code to rgb which already exists in OUFR utilities, but because OUFR is not a dependency of `@uifabric/styling` I couldn't reuse it which brings to duplication of the same code in 2 different places.

**Comment by dzearing** [comment]
If there is a specific need, we'd need to be explicit about which methods are being added and to which package. 

I do think there is an overarching themability item we're working which might require some additional color utilities. We have some in `color.ts` already.

Closing this to trim off ambiguous work.
