### ISSUE TITLE
Coachmark icon support

### ISSUE THREAD

**Issue by nickdurak** [OfficeDev/office-ui-fabric-react#6129]
Need the coachmark to support icons formatted like the below images (IconOnLeft.png and IconOnTopLeft.png):

<img width="468" alt="icononleft" src="https://user-images.githubusercontent.com/2531806/44802158-d189f900-ab6f-11e8-8791-6039584d878e.png">
<img width="298" alt="iconontopleft" src="https://user-images.githubusercontent.com/2531806/44802160-d353bc80-ab6f-11e8-8c58-0c6afd96ff39.png">

We do not want it to look like this (undesiredIconOnLeft.png):
<img width="585" alt="undesiredicononleft" src="https://user-images.githubusercontent.com/2531806/44802176-da7aca80-ab6f-11e8-975c-e2eacb009cfb.png">

The current behavior observed is (CurrentIconBehavior.png):
![currenticonbehavior](https://user-images.githubusercontent.com/2531806/44802202-ecf50400-ab6f-11e8-9eb5-3d97bfc21e6a.png)

Above screenshot (CurrentIconBehavior.png) was taken from the following code:

public render() {
        const calloutProps: ICalloutProps = {
            doNotLayer: true
        };
        const teachingBubble: ITeachingBubbleBindingOptions = this._observables.unwrap(this.props.command.teachingBubble);
        const teachingBubbleCampaign: ITeachingBubbleCampaign = teachingBubble.campaign();
        const teachingBubbleImage: IImageProps = { src: 'http://placehold.it/364x140' };
 
        return (
            <Coachmark
                target={ this.props.target }
                positioningContainerProps={ {
                    directionalHint: DirectionalHint.bottomCenter
                } }
                onAnimationOpenEnd={ this.markCoachmarkAsSeen }
            >
                {
                    <TeachingBubbleContent
                        illustrationImage={ teachingBubbleImage }
                        headline={ teachingBubbleCampaign.title }
                        calloutProps={ calloutProps }
                        hasCloseIcon={ teachingBubbleCampaign.isDismissable }
                        closeButtonAriaLabel={ TeachingBubbleStrings.closeButton }
                        onDismiss={ this.onDismiss }
                    >
                        { teachingBubbleCampaign.bodyCopy }
                    </TeachingBubbleContent>
                }
            </Coachmark>
        );
    }

**Comment by micahgodbolt** [comment]
@nickdurak can you get this example into a codepen to see if there's a way to support your current need.

Also, are you interesting in writing a PR to resolve this new feature?
