### ISSUE TITLE
changing 'disabled' prop doesn't changed the state of Dropdown.

### ISSUE THREAD

**Issue by biogenez** [OfficeDev/office-ui-fabric-react#613]
#### Describe the issue:
changing 'disabled' prop doesn't affect to the component (after the first render).

There is no check for the new value of property **disabled** (only for deprecated **isDisabled**) in the func **componentWillReceiveProps**:

     if (newProps.isDisabled !== this.props.isDisabled) {
      this.setState({
        isDisabled: newProps.isDisabled !== undefined ? newProps.isDisabled : newProps.disabled
      });

There should be something like:

     if (newProps.isDisabled !== this.props.isDisabled || newProps.disabled !== this.props.disabled) {
      this.setState({
        isDisabled: newProps.isDisabled !== undefined ? newProps.isDisabled : newProps.disabled
      });

**Comment by dzearing** [comment]
Fixed, will be published tomorrow.
