### ISSUE TITLE
Unnecessary scrollbar in DatePicker when showGoToToday is false and showMonthPickerAsOverlay is true

### ISSUE THREAD

**Issue by janormanms** [OfficeDev/office-ui-fabric-react#6131]
### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/janormanms/pen/YOGMrd

### Bug Report 

- __Package version(s)__: 6.42.0
- __Browser and OS versions__: Chrome, Win10 latest
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: Outlook Web
 
#### Describe the issue:
 
Trying to hide the Today button for an end date selector if today is before the start date, doing so by setting showGoToToday to false and having showMonthPickerAsOverlay set to true on the DatePicker results in a scrollbar:
 
![image](https://user-images.githubusercontent.com/40806783/44804357-f2ede380-ab75-11e8-8f33-a79846187fbb.png)

#### Actual behavior:
 
Scrollbar
 
#### Expected behavior:
 
Callout is sized to show all of the calendar with appropriate border/padding

**Comment by micahgodbolt** [comment]
yuck. that shouldn't have slipped through. Let's be sure to get a visual test on this variant

![image](https://user-images.githubusercontent.com/1434956/44805012-ef5b5c00-ab77-11e8-8c05-e9486a963b11.png)

**Comment by micahgodbolt** [comment]
clicking on the month you get to the month picker....it also has the padding bug 
![image](https://user-images.githubusercontent.com/1434956/44805078-1ade4680-ab78-11e8-80da-0a20c8a8f1ff.png)
