### ISSUE TITLE
[TagPicker] Borders don't have same width

### ISSUE THREAD

**Issue by yaananth** [OfficeDev/office-ui-fabric-react#6141]
https://developer.microsoft.com/en-us/fabric#/components/pickers

Look at bottom border after the tag, it looks like very thin line where as others are solid
![image](https://user-images.githubusercontent.com/12280011/44818833-5ac51e00-abb8-11e8-8d01-062681a8e322.png)

![image](https://user-images.githubusercontent.com/12280011/44818854-69133a00-abb8-11e8-9d24-4f1fe6810a4c.png)

**Comment by micahgodbolt** [comment]
i believe it's the joy of subpixel rounding in many browsers. If you bump up the browser zoom, the borders don't have to go sub pixel, and everything hits whole numbers, and looks much better. 

![image](https://user-images.githubusercontent.com/1434956/44821198-3f064b80-aba9-11e8-8029-35d62cb00831.png)
