### ISSUE TITLE
jest-serializer-merge-styles: @keyframes breaks _serializeRules

### ISSUE THREAD

**Issue by ikiyou** [OfficeDev/office-ui-fabric-react#6149]
### Please provide a reproduction of the bug in a codepen:
 
Not sure how to repro jest snapshot testing online. If there's an example you can point me to, I'll gladly try to repro the issue.

### Bug Report 
 
- __Package version(s)__:  "@uifabric/jest-serializer-merge-styles": "6.0.4" (latest)
- __Browser and OS versions__: Not relevant

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Possibly, as long as I can keep the scope of the fix to the keyframes issue I'm seeing (i.e. possibly not fixing other rules where this is breaking as well).
 
Requested priority: Normal. My team will need to disable `jest-serializer-merge-styles` for components that are using `keyframes`.
 
Products/sites affected: N/A
 
#### Describe the issue:

When using `jest-serializer-merge-styles`, there are certain CSS rules like `keyframes` (probably, haven't tested this with other rules) that cause the serializer to break. For example, with `keyframes`:

CSS:
```
@keyframes foo {
    from {opacity:0;}
    to {opacity:1;}
}
```

ruleSet in `jest-serializer-merge-styles`:
```
ruleSet
Array(2) ["keyframes", "from{opacity:0;}to{opacity:1;}"]
- length: 2
- __proto__: Array(0) [, …]
- 0: "keyframes"
- 1: "from{opacity:0;}to{opacity:1;}"
```

[So starting in L41 of the source](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/jest-serializer-merge-styles/src/index.ts#L41),  when the above is passed in, `insertedRules.split(';').sort` returns:

```
Array(3) ["from{opacity:0", "}", "}to{opacity:1"]
- length:3
- __proto__:Array(0) [, …]
- 0:"from{opacity:0"
- 1:"}"
- 2:"}to{opacity:1"
```

then *here's the actual bug/error that occurs:* in [line 53](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/jest-serializer-merge-styles/src/index.ts#L53), since one of the rules is "}", there is no `value` from [line 46](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/jest-serializer-merge-styles/src/index.ts#L46), hence I get the following stacktrace:

```
TypeError: Cannot read property 'split' of undefined
    at C:\repos\OfficeIdeas\node_modules\@uifabric\jest-serializer-merge-styles\src\index.ts:53:38
    at Array.forEach (<anonymous>)
    at _serializeRules (C:\repos\OfficeIdeas\node_modules\@uifabric\jest-serializer-merge-styles\src\index.ts:44:10)
    at Object.print (C:\repos\OfficeIdeas\node_modules\@uifabric\jest-serializer-merge-styles\src\index.ts:11:18)
    at printPlugin (C:\repos\OfficeIdeas\node_modules\pretty-format\build\index.js:194:108)
    at printer (C:\repos\OfficeIdeas\node_modules\pretty-format\build\index.js:228:12)
    at printObjectProperties (C:\repos\OfficeIdeas\node_modules\pretty-format\build\collections.js:140:21)
    at printComplexValue (C:\repos\OfficeIdeas\node_modules\pretty-format\build\index.js:187:169)
    at printer (C:\repos\OfficeIdeas\node_modules\pretty-format\build\index.js:236:10)
    at printListItems (C:\repos\OfficeIdeas\node_modules\pretty-format\build\collections.js:105:35)
... (more)
```

#### Actual behavior:

Doesn't serialize / serializer throws an exception.
 
#### Expected behavior:
 
Not sure how this should be serialized. For CSS like:

```
@keyframes foo {
    from {opacity:0;}
    to {opacity:1;}
}
```

Seems from what we're given the best we can serialize it to is something like:
```
@keyframes {
    from{opacity:0;}
    to{opacity:1;}
}
```
that is, we would just lose the animation name.
 
Again, I wouldn't mind implementing this specific fix (i.e. just for keyframes), but if you want something generic, then I wouldn't be able to provide that.

**Comment by micahgodbolt** [comment]
We currently have keyframe animation on several components (including the [progress bar](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ProgressIndicator/ProgressIndicator.styles.ts#L22)). The keyframe appears to be creating snapshots without failure. Is this a different scenario?

**Comment by ikiyou** [comment]
If I understood your question correctly, the scenario you're referring to is strictly with OUFR components which are using `merge-styles`? In my scenario, the component we're creating a snapshot for is composed of both Office UI Fabric React components and custom components which use `glamor` as its CSS-in-JS tool. It might be that `glamor` is inserting rules into the stylesheet in a way that `jest-serializer-merge-styles` doesn't expect? OTOH, we've been using `jest-serializer-merge-styles` with plenty of components that use `glamor` and haven't seen this issue before...

In any case, it looks like there's a possibility for rules without a ":" to get into the forEach logic. Seems at the very least that should be handled somehow? Then maybe we can dig into the exact form and source of the offending rule?

**Comment by ikiyou** [comment]
@micahgodbolt bump!

**Comment by micahgodbolt** [comment]
@dzearing is the issue here that glamor doesn't have a serializer like merge-style does?

**Comment by ikiyou** [comment]
@dzearing bump!

**Comment by mikewheaton** [comment]
@ikiyou Have you been able to isolate this issue and verify that Glamor rules aren't handled correctly by jest-serializer-merge-styles?

**Comment by dzearing** [comment]
hrm.. sorry for the delay, this issue got lost on everyones'  radars. Trying to repro right now.

**Comment by dzearing** [comment]
@micahgodbolt this has nothing to do with glamor... it's very easy to repro, just by adding a test that uses the serializer:

```
  it('works w keyframe', () => {
    const fadeInClassName = keyframes({
      from: { opacity: 0 },
      to: { opacity: 1 }
    });
    expect(renderer.create(<div className={fadeInClassName} />).toJSON()).toMatchSnapshot();
  });
```
