### ISSUE TITLE
Button: Do not combine modifier with component class

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#615]
### Bug Report

- __Package version(s)__: 0.77.1
- __Browser and OS versions__: All

#### Describe the issue:

The Button component has various modifier classes (e.g. `.ms-Button--icon`) that are used for the button types. The way that these selectors have been written creates more specificity than is necessary, which makes it hard to style the buttons by passing in a `className` prop.

Below you can see how the `.ControlPanel-closeButton` class is unable to override the Button's default styles, as the specificity is higher than it needs to be.

![image](https://cloud.githubusercontent.com/assets/1382445/20644186/64d24d80-b3e1-11e6-80c3-4617f1cc1c96.png)

#### Actual behavior:

The Button's modifier classes are written like so:

```
.ms-Button.ms-Button--icon { }
```

#### Expected behavior:

They should be simply:

```
.ms-Button--icon { }
```

**Comment by dzearing** [comment]
thx!
