### ISSUE TITLE
Replace react-loadable because of possible license change

### ISSUE THREAD

**Issue by kenotron** [OfficeDev/office-ui-fabric-react#6154]
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) Yes
 
Requested priority: (Blocking, High, Normal, Low) High
 
Products/sites affected: (if applicable) Unknown
 
#### Describe the issue:

We need to remove the usage of react-loadable ASAP because of the license change by the author:
https://github.com/jamiebuilds/react-loadable/commit/c3272b3132e4fe25937c3610b7cd0dd2da48c5e9

**Comment by kenotron** [comment]
@christiango - do you have any suggestions for replacements?

**Comment by christiango** [comment]
I say we roll our own.

**Comment by kenotron** [comment]
Okay, @ThomasMichon had a PR a while ago that solves that need for us. We voted to use react-loadable at the time. But now we can use this again: #4154

**Comment by Vitalius1** [comment]
@kenotron are we moving with this one to any direction?

**Comment by kenotron** [comment]
The urgency level went down a bit after react-loadable changed back to MIT for all license. But the issue is remains that we have an open #4154 item that needs to be addressed.

**Comment by mikewheaton** [comment]
Are the next steps clear here, or does this need more discussion? It sounds like a feature request moreso than a bug, given the change back to an MIT license.

**Comment by kenotron** [comment]
Yes, this is now a feature request

**Comment by kenotron** [comment]
Not sure if we need it anymore.
