### ISSUE TITLE
Keytip: Clean up example page

### ISSUE THREAD

**Issue by cliffkoh** [OfficeDev/office-ui-fabric-react#6156]
https://fabricweb.z5.web.core.windows.net/oufr/6.59.0/#/examples/keytips

![image](https://user-images.githubusercontent.com/1003246/44869512-a02e2d80-ac42-11e8-95e7-c4403e4cd6fa.png)

**Comment by micahgodbolt** [comment]
did it look better in the past? Or just general messiness?

**Comment by kenotron** [comment]
@cliffkoh is this Edge? it looks okay in Chrome.

**Comment by cliffkoh** [comment]
Both Edge and Chrome when I took the screenshot

**Comment by cliffkoh** [comment]
I can still repro with the link above

**Comment by kenotron** [comment]
can you draft up a quick mock of what you want on that page, @micahgodbolt ?

**Comment by micahgodbolt** [comment]
maybe some vertical spaceing up top

![image](https://user-images.githubusercontent.com/1434956/45228184-57e0c200-b277-11e8-8c28-acf6ac79f5b5.png)

and some breathign room on the pivot

![image](https://user-images.githubusercontent.com/1434956/45228273-9f674e00-b277-11e8-8902-98fdf420fb75.png)

As I look at the page, one oddity is that the titles don't stand out very well. Seems they used ms-font-l in the past, but there are no styles loaded for that classname. Are those titles supposed to be bigger?

![image](https://user-images.githubusercontent.com/1434956/45228397-ef461500-b277-11e8-8013-ddad8f541fdc.png)

**Comment by micahgodbolt** [comment]
Oh yeah, seems fabric.min.css isn't being loaded into those demo sites like it is our public website

![image](https://user-images.githubusercontent.com/1434956/45228450-10a70100-b278-11e8-96c4-2a7756056821.png)

**Comment by micahgodbolt** [comment]
I'd say start with getting that same css into our internal demo pages before trying to clean up some of that spacing

**Comment by cliffkoh** [comment]
Hmm actually the main concern is that the pivot 1 example looks busted. Specifically this:
![image](https://user-images.githubusercontent.com/1003246/45248099-e4b06d80-b2c1-11e8-9a25-b5122a18fbda.png)

**Comment by cliffkoh** [comment]
Do you not see the Dropdown being clipped?

**Comment by micahgodbolt** [comment]
No, I've never seen that clipping. Its just a single component being rendered there. If there was a bug it'd be there, not just on keytips page

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by KevinTCoughlin** [comment]
Just adding another data-point: The clipping I see on this page is the `<Pivot>` control clipping its tab contents _sometimes_ in Edge. I say sometimes, because if you mouseover the input it will stop clipping.

This is what I see in Edge, the other browsers don't clip:

![image](https://user-images.githubusercontent.com/706967/45975545-5b0ada80-bff9-11e8-9508-34ac4f3a8d2b.png)

Anyway seems like some padding/margin would do the trick here w.r.t clipping.
