### ISSUE TITLE
CommandBar should stop the propagation of keydown ENTER

### ISSUE THREAD

**Issue by angelo-mollame** [OfficeDev/office-ui-fabric-react#6159]
A div containing a CommandBar will still catch bubbled up keydown ENTER events even if they are handled by the CommandBar.

**Comment by micahgodbolt** [comment]
do you have a repro of this happening? All of the events in command bar  are handled by the button component. So having a command bar should be nothing more than having a group of DefaultButtons on the page.

**Comment by angelo-mollame** [comment]
https://codepen.io/anon/pen/KxazdW

**Comment by micahgodbolt** [comment]
This is working as expected. This is the default behavior of any HTML button.
