### ISSUE TITLE
Change CommandBarButtons to use whitespace: no-wrap

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#6168]
CommandBar buttons with multiple words can wrap during space testing, so measurements can be a bit off. We should force those buttons into a single line via whitespace: no-wrap

https://codepen.io/anon/pen/MqJgwv

**Comment by micahgodbolt** [comment]
can probably do this inside of command bar vs the button itself, as you might use the button outside of the command bar, in which case wrapping isn't an issue

**Comment by kenotron** [comment]
@FalseLobster - this is a good one for you to dig into
