### ISSUE TITLE
Searchbox working different in both chrome and microsoft edge

### ISSUE THREAD

**Issue by hrc7505** [OfficeDev/office-ui-fabric-react#6177]
I have used to searchbox component inside commandbar using onRender. But it is working different in both edge and chrome. It width gets reduced in edge. 

Here a codepen: [Searchbox with commndbar](https://developer.microsoft.com/en-us/fabric)

**Comment by redoz** [comment]
@hrc7505 that codepen link is broken, it links to the Fabric website instead.

**Comment by micahgodbolt** [comment]
https://codepen.io/micahgodbolt/pen/gdMZmO

So it does! It's a flex issue. Not sure if it'd call it a bug in search as much as guidance on using inline-block items in a flex region like commandBar. let me check how you can solve this.

**Comment by micahgodbolt** [comment]
I updated the codepen. I'd recommend setting a length on the SearchBox anyway. It solves the Edge scenario, and fixes other browsers where the search changes width when the icon animates out.

**Comment by micahgodbolt** [comment]
Closing this up as it's not a searchbox/commandbar issue, just how CSS works with inputs/inline elements in a flex region.

**Comment by hrc7505** [comment]
Thank you! @micahgodbolt
