### ISSUE TITLE
Issue introduce with overflow auto on Dialog component

### ISSUE THREAD

**Issue by kevinbargary** [OfficeDev/office-ui-fabric-react#6180]
### Bug Report 
 
 
- __Package version(s)__: 6.53.0 +
- __Browser and OS versions__: (fill this out if relevant)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: High
 
Products/sites affected: Fabric UI React Dialog Component
 
#### Describe the issue:
 
From what we can deduce introduced as part of this commit (https://github.com/OfficeDev/office-ui-fabric-react/commit/882a50c5ae8d6e4521b21842d5f68723ba4f9d2e)

Dialog with text / component with small width is affected by `div` with style of `overflow:auto`
 
#### Actual behavior:
 
Content within `div` is not full width of `Dialog` component
 
#### Expected behavior:
 
Content within `div` is full width irrespective of children width

Sandbox available [here ](https://codesandbox.io/s/lrvn67yrmz)

**Comment by micahgodbolt** [comment]
Looks like that wrapper div is missing flex grow, so it's not taking up 100% of the parent width if the content doesn't require it.

Adding flex-grow in there will fix it.

![image](https://user-images.githubusercontent.com/1434956/44925690-e8f9eb00-ad03-11e8-9f17-590e5d5d6689.png)
