### ISSUE TITLE
p Tag in Body of Teaching

### ISSUE THREAD

**Issue by maggiepint** [OfficeDev/office-ui-fabric-react#6189]
### Bug Report 
 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by micahgodbolt** [comment]
duplicate of #6190
