### ISSUE TITLE
Allow block elements in body of teaching bubble

### ISSUE THREAD

**Issue by maggiepint** [OfficeDev/office-ui-fabric-react#6190]
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal
 
Products/sites affected: Microsoft internal tool
 
#### Describe the issue:

It is not possible to display tabular data in a teaching bubble. 

#### Actual behavior:
 
[Based on this code](https://github.com/OfficeDev/office-ui-fabric-react/blob/248b46e8886f0715a0aa728d8880b94b59288bea/packages/office-ui-fabric-react/src/components/TeachingBubble/TeachingBubbleContent.base.tsx#L102), teaching bubble bodies are always wrapped by a `<p>` tag.

Because of this, one cannot embed a List component from this library, a table, or any other block level element inside of a teaching bubble.
 
#### Expected behavior:

Even if the body defaults to a  `<p>` tag, I would expect to be able to override with a different react component.

Apologies- this is one of those things that treads the line between bug and feature. It's clearly by-design, but it prevents me from using the bubble to display the data I want to display.

If you feel an override property for 'body component' is reasonable - I'm happy to submit a fix. Alternately, one could just change the `<p>` tag to a div - but this may be breaking.

**Comment by micahgodbolt** [comment]
Nah, this is a legitimate request. We're dropping children into a <p> tag. If it were a string prop, this might be okay, but children has an expected type of JSX.Element, which when dropped into a P tag, might not work the best.

We could probably look at the type of the child, and if it's a string, wrap it in a p tag, otherwise use a div.
