### ISSUE TITLE
HoverCard's cardHeight props aren't typed broadly enough

### ISSUE THREAD

**Issue by bengry** [OfficeDev/office-ui-fabric-react#6197]
### Reproduction in CodeSandbox (CodePen was giving me issues at the time):
[![Edit Fabric-React HoverCard compact height type](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/mzqlyj3k6x)
### Bug Report 
 
 
- __Package version(s)__: 6.61.2
- __Browser and OS versions__: non-relevant
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? **Yes**
 
Requested priority: **Low**
 
 
#### Describe the issue:
 
The `IExpandingCardProps` has a property `compactCardHeight`, which is of type `number`, even though that in runtime it accepts anything that `IStyle['height']` accepts.
To word this differently - the type of `IExpandingCardProps[compactCardHeight]` (and `IExpandingCardProps[expandedCardHeight]`) should be `IStyle['height']` (which is really `string | number` in this case, but also contains other values that are acceptable).
This causes the height of the card to have a fixed height, and doesn't allow a dynamic one based on the height of the inner component.

This is also true for the width (fixed width), but the issues are unrelated, technically.

 
#### Actual behavior:
Card width can only be typed as a `number`
 

 
#### Expected behavior:
Card width can be typed as a `string | number`

**Comment by kenotron** [comment]
I dug into the code. Realized that the ExpandedCard calculates finalHeight based on the heights passed in. The intention for this component seem to be surrounding fixed heights. If we allow for dynamic heights, then we'd have to render off screen, measure and then place that value in the component. This is, of course, very expensive. Closing this as won't fix.

**Comment by bengry** [comment]
@kenotron Can you refer me to the code that does this? I tried looking at the code of the `Callout` component but didn't find anything that specifically relies on the fixed height. I might've just missed it, but would appreciate a (more specific) pointer. Thanks.

**Comment by Vitalius1** [comment]
@bengry This PR should help solving your issue. Introduces a new BasicCard which will take the size of the content you put in. The fixed height @kenotron mentioned is needed for the animation on the expanding card to work with Callout.
