### ISSUE TITLE
Deprecate "toggled" property in Button.types.ts

### ISSUE THREAD

**Issue by joechung-msft** [OfficeDev/office-ui-fabric-react#6199]
### Bug Report 
 
 
- __Package version(s)__: 6.61.2
- __Browser and OS versions__: (fill this out if relevant)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No
 
Requested priority: (Blocking, High, Normal, Low) Low
 
Products/sites affected: (if applicable)
 
#### Describe the issue:
 
The Button types file defined an unused "toggled" prop with a comment copied from the "data" prop.

Lines 219-227, Button.types.ts
````ts
  /**
   * Any custom data the developer wishes to associate with the menu item.
   */
  toggled?: boolean;

  /**
   * Any custom data the developer wishes to associate with the menu item.
   */
  data?: any;
````

The "toggle" prop actually uses the "checked" prop to implement "toggle button" functionality (setting the "aria-pressed" attribute).

Lines 198 and 516, BaseButton.tsx
````ts
  'aria-pressed': toggle ? !!checked : undefined // aria-pressed attribute should only be present for toggle buttons
````

There is no broken behavior to report.  It just caused a little bit of confusion when I was trying to implement a toggle button a couple days ago.

**Comment by KevinTCoughlin** [comment]
Thanks for the report -- easy fix :)
