### ISSUE TITLE
Searchbox usage in CommandBar

### ISSUE THREAD

**Issue by kchiragowni** [OfficeDev/office-ui-fabric-react#620]
### Bug Report
No documentation on how to hook SearchBox events in CommandBar.

#### Describe the issue:
Nothing happens when text is entered or hit enter in SearchBox in CommandBar.

#### Expected behavior:
Hooks callbacks to SearchBox events

**Comment by dzearing** [comment]
The

**Comment by dzearing** [comment]
Closing this one and using #662 to track deprecating SearchBox in favor of TextField to promote consistency.

**Comment by kchiragowni** [comment]
Thanks @dzearing for forking this into #662

**Comment by pjatacsukb** [comment]
So the searchbar within CommandBar is not usable yet?

**Comment by WesselKuipers** [comment]
Looks like further development for this will be tracked at https://github.com/OfficeDev/office-ui-fabric-react/issues/94

**Comment by jonathanhotono** [comment]
So should we separate the searchBox with the commandBar for the time being?
