### ISSUE TITLE
How do we display Select Application Role *  text using label in office fabric drop down in react js

### ISSUE THREAD

**Issue by DineshSuram** [OfficeDev/office-ui-fabric-react#6202]
My requirement is to display the text as shown in image .
![capture](https://user-images.githubusercontent.com/42933680/44982983-35a82500-af95-11e8-939b-82db07f92875.PNG)
.Iam using office fabric-ui-dropdown. It contains label property which indicates the title of dropdown.Iam unable to apply css for *( which should be in red colour).Please help me how can i fix this  issue.

**Comment by kschio** [comment]
Hi,

you want to add the required property to the dropdown:
`<Dropdown label="Lorem ipsum" required="true" .../>`

Hope this helps :)

**Comment by micahgodbolt** [comment]
this is a question for the https://github.com/OfficeDev/office-ui-fabric-js repo
