### ISSUE TITLE
On Hover issue in swatch color picker

### ISSUE THREAD

**Issue by RupamSarkar** [OfficeDev/office-ui-fabric-react#6205]
### Bug Report 

- __Package version(s)__: 6.55.0
- __Browser and OS versions__: (fill this out if relevant)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? 
 
Requested priority: Normal
 
Products/sites affected: (if applicable)
 
#### Describe the issue:
For Swatch Color picker if there is a white color cell and that cell is not at the rightmost end -  then if we hover over on the white cell , all the other colors(on the right of the white ) move 1-2 px to the left .

#### Actual behavior:
In our scenario , we have a white cell at the first(left most) position in a swatch color picker , Due to this issue all the color cells on its right(columns/rows) are moving to 1-2 px to left on hover .
 
#### Expected behavior:
Color cells should not move on hover 

Sample GIF :
![bug](https://user-images.githubusercontent.com/17047049/44995740-1a9fda00-afc2-11e8-8c92-d89c8d9f42a7.gif)

**Comment by micahgodbolt** [comment]
Looks like when the item 'isWhite' there'a an extra pixel of margin that dissapears when you hover. Remove that pixel and it'll like up better (tiny wiggle, but not as noticable).

**Comment by KevinTCoughlin** [comment]
Thanks @micahgodbolt :) helped me find the off by 1 error fairly quickly 🎉
