### ISSUE TITLE
GroupedList footer sets global styles for .ms-Link

### ISSUE THREAD

**Issue by jordandrako** [OfficeDev/office-ui-fabric-react#6218]
### Please provide a reproduction of the bug in a codepen:
 
Repros on the demo site: https://developer.microsoft.com/en-us/fabric#/components/link

### Bug Report 
 
 
- __Package version(s)__:  6.49.2
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: Demo site/internal site
 
#### Describe the issue:
 
`.ms-Link` has a font size of 12px. It was introduced in https://github.com/OfficeDev/office-ui-fabric-react/commit/50afbc71bc286bf38f617fa588121265be4854a6#diff-40a480fc0eed282889dca270e35ffe9fR20

#### Actual behavior:
 
Overrides the link font size globally.
 
#### Expected behavior:
 
Should only override link font size in that scope.

**Comment by micahgodbolt** [comment]
yeah, this is an unqualified selector, it needs to simply be links inside of this root

`[`:global(.${classNames.link}`]: {`

**Comment by micahgodbolt** [comment]
https://github.com/OfficeDev/office-ui-fabric-react/wiki/Component-Styling#using-a-styleable-component

**Comment by micahgodbolt** [comment]
`& .className` works fine. :global specifically pulls the selector out of the parent scope

**Comment by kenotron** [comment]
`& :global(classNames.link)` right? otherwise we need to do the subcomponent stuff i think

**Comment by kenotron** [comment]
subcomponent is not useful here because the children are just any jsx element there...

**Comment by micahgodbolt** [comment]
Yeah, the only way to add content to the footer is through children. So this style is just there in case they happen to pass through links. It's a kinda hacky old way of ensuring styles. I'd say we just totally remove it if it wasn't going to break a bunch of people who rely on it.

**Comment by jordandrako** [comment]
Links inherit font size, so what's the use case where links specifically have to be 12px if the other text is a different size?

**Comment by micahgodbolt** [comment]
good question......guessing the expectation is that other content isn't affected? I'm sure some design comp somewhere wanted a link in that footer to be smaller....
