### ISSUE TITLE
Broken Release (maybe?)

### ISSUE THREAD

**Issue by jleck** [OfficeDev/office-ui-fabric-react#6237]
#### Describe the issue:
 
After installed the current release (6.64.0), I am unable to include any components due to a compile error. This can be recreated using create react app and typescript.

It's been a long day at work so hopefully it's nothing obvious on my end!
 
#### Actual behavior:
 
```
./node_modules/office-ui-fabric-react/lib/components/FocusZone/FocusZone.js
100:44-58 '../../Utilities' does not contain an export named 'getNextElement'.
```
 
#### Expected behavior:
 
Compile correctly.

**Comment by micahgodbolt** [comment]
So far I haven't had any trouble with a new create-react-app instance and 6.64. Can you try to blow out your node modules and install again? Could be that utilities didn't get properly updated.

**Comment by jleck** [comment]
Thanks for the quick reply!

I think I rebuilt my node modules a couple times, but I’ll try again once I’m back at work tomorrow. You never know! If it still doesn’t work I’ll push up a repo to recreate the issue.

Will keep you updated!

**Comment by jleck** [comment]
D'oh, rebuild all the node modules worked. Apologies for the false report!
