### ISSUE TITLE
Dropdown/DatePicker are not working on Safari when near the bottom of the page

### ISSUE THREAD

**Issue by mibes** [OfficeDev/office-ui-fabric-react#624]
Follow-up on #603 

This pen demonstrates the dropdown issue: http://codepen.io/mibes/pen/PbJQRK
It uses build 0.78.1.

The issue only manifests itself (for me) when the dropdown is near the bottom of the page. The fix that was included in build 0.77 works on both Chrome (v.54.0.2840.98) and Firefox (v.50.0), but the issue remains on Safari (v.10.0.1) -- all on OSX.

### Additional detail
If you disable closing the dropdown in `onDismiss` in the Dropdown.js it shows the different behaviour in Safari:

` Dropdown.prototype._onDismiss = function () { `
` // this.setState({ isOpen: false }); `
` }; `

With this function disabled: in Safari when you click a Dropdown near the bottom of the page, it scrolls to the top of the page and then shows the Dropdown content at the bottom of the window. The scrolling triggers the onDismiss and hence the Dropdown is closed again.

**Comment by dzearing** [comment]
Found the issue. It seems we're setting focus before the callout is positioned.

The callout positioned in an offscreen location first, and then sets the correct positioning and size. We need to delay focus setting until this is complete. This avoids the scroll.

Additionally if scroll events do occur before positioning is complete, we shouldn't ever try to dismiss.

I have this fixed and will be addressed today, but I do have some reservations that dismiss on scroll is a good idea. It may be a better solution to completely disable scrolling while a callout is visible.

**Comment by mibes** [comment]
Great! I can confirm the dropdown issue has been fixed in build 0.79 in Safari and the embedded browser in Word (v15.28). 

Unfortunately the fix did not address the DatePicker that had the same behaviour. (I should have mentioned that). Not sure if there are other components that use the same Callout. 

I'll update the code pen to use build 0.79 and include a DatePicker.

With regards to dismiss behaviour; the current behaviour seems acceptable (to me). On the Mac scrolling with the touchpad is prevented when the cursor is over the dropdown. When you scroll outside of the dropdown the dropdown is dismissed. Seems unobtrusive.

**Comment by mibes** [comment]
A quick work-around to resolve the DatePicker issues, is to change line 135 in `DatePicker.tsx`. Change `shouldFocusOnMount={ true }` to `shouldFocusOnMount={ false }`. This fixed the DatePicker not opening issue for me on Safari. Chrome and Firefox seemed fine as well.

**Comment by dzearing** [comment]
Thanks, will be fixed today.

**Comment by mibes** [comment]
Fixed in v0.81. Thanks!
