### ISSUE TITLE
DocumentCard component crashes the browser with infinite loop

### ISSUE THREAD

**Issue by arheom** [OfficeDev/office-ui-fabric-react#625]
### Bug Report

- __Package version(s)__: 0.72.1
- __Browser and OS versions__: Chrome 54.0.2840.99 m and Windows 7

#### Describe the issue:

I have on one SharePoint Online page few client side web parts, 2 of them having a list of DocumentCard elements. They are integrated using Redux with another component which searches in both of them (SearchBox). The document cards are simple, looks like:
```
<DocumentCard key={index} onClickHref={document.OriginalPath}>
  <DocumentCardPreview {...previewProps} />
  <DocumentCardTitle title={document.Title} shouldTruncate={true} />
  <DocumentCardActivity activity={createdOn} people={people} />
  <DocumentCardActions actions={[]} views={document.ViewsLifeTime} />
</DocumentCard>
```

#### Actual behavior:

When I am using the SearchBox to filter them (actually when they need to re-render, cos I have another test just which pushes a re-render), the browser crashes with the following error (looks like going into an infinite loop):

> Uncaught RangeError: Maximum call stack size exceeded

and the loop is between the functions:

> close	@	ReactUpdates.js:47
> closeAll	@	Transaction.js:206
> perform	@	Transaction.js:153
> perform	@	ReactUpdates.js:89
> flushBatchedUpdates	@	ReactUpdates.js:172
> close	@	ReactUpdates.js:47

Everything works well when not using the DocumentCard component to show the list of elements. Also works well when I only show few DocumentCards per component (5 is the magic number in my case). I debugged more inside React and looks like the DocumentCard components are always marked as Dirty, somehow, rendering one DocumentCard, makes Dirty another instance of DocumentCard and so on...

#### Expected behavior:

To have the list of document cards working well also on re-rendering / filtering.

**Comment by mikewheaton** [comment]
Could you try this with the `shouldTruncate` prop set to `false`? I think that's the only function that loops within the DocumentCard.

**Comment by arheom** [comment]
Looks like this is the problem. After setting the `shouldTruncate `prop to `false`, it works well.

**Comment by mikewheaton** [comment]
@arheom: I've set up a [CodePen with multiple DocumentCards on the page](http://codepen.io/mikewheaton/pen/vydRJX?editors=0010) and am not able to repro the issue. Truncation looks to be working on each of them.

**Comment by mikewheaton** [comment]
Unable to repro so I'm going to close this for now.

**Comment by arheom** [comment]
I think might be a bit more complicated to reproduce it. I only managed to reproduce it with Redux and having at least 2 components subscribing to Redux which generates cards both of them. But I will investigate it on my environment and will check why it happens and will post it here.
