### ISSUE TITLE
Dropdown: Does not open in Chrome on Fabric React website, the page scroll position jumps to the top and back down

### ISSUE THREAD

**Issue by sompylasar** [OfficeDev/office-ui-fabric-react#626]
### Bug Report

- __Package version(s)__: 0.69.0 (from fabric-website)
- __Browser and OS versions__: Chrome 54.0 on Android 6.0, Chrome 54.0 on macOS 10.12

#### Describe the issue:

Dropdown does not open when I tap (touchscreen) or click (desktop) on it.

#### Actual behavior:

The page scroll position jumps to the top and back down.

#### Expected behavior:

The dropdown opens, the items are visible, the page scroll does not change (or probably scrolls down to fit the opened items into screen).

### If applicable, please provide a codepen repro:

It's on the demo website as of today, 11/29/2016, and fabric-website 4.1.0: http://dev.office.com/fabric#/components/datepicker

Please see the screen recording: 
![screenrecord_2016-11-29-07-40-15](https://cloud.githubusercontent.com/assets/498274/20716880/8e4e098c-b608-11e6-8912-018385d665a6.gif)

The same happens in desktop Chrome.

**Comment by mikewheaton** [comment]
Thanks for reporting this, @sompylasar. It should be fixed by a new release of Fabric React, which will contain PR #605. An updated website using this latest version should be online within the next few days. I'll leave this issue open and assigned to myself until we've verified the fix.

**Comment by sompylasar** [comment]
Okay, thanks! 👍

**Comment by dzearing** [comment]
This has been resolved.

**Comment by mikewheaton** [comment]
The bug in Fabric React has been resolved, but I've been keeping this open to verify the fix on the live site. That hasn't been deployed yet and is still broken on [the dropdown page](http://dev.office.com/fabric#/components/dropdown).

**Comment by mikewheaton** [comment]
Actually yes, let's close the issue. The work is done and the fix has been verified in a test build of the Fabric website (deployed to a server, not locally). It's fixed and should go live sometime this week. 😄
