### ISSUE TITLE
MessageBar: Icon props are not defined to set the icon or no icon

### ISSUE THREAD

**Issue by arunarokk** [OfficeDev/office-ui-fabric-react#6281]
### Bug Report 
 
 
- __Package version(s)__: (6.38.0) 
- __Browser and OS versions__: (fill this out if relevant)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (High) 
 
Products/sites affected: (if applicable)
 
#### Describe the issue:
 
With the current implementation: 
no way to either have no icon, to have an “in progress” state, or to specify a custom icon prop to show on the message bar
 

 
#### Expected behavior:
 
Icon props should be defined to set icons on message bar , for example if we want show In-progress message bar with sync icon. if you can introduce In-progress styled MessageBar.

**Comment by micahgodbolt** [comment]
can you provide a codepen of what you're trying to do?

**Comment by keydoubleu** [comment]
@micahgodbolt 

Currently the messageBarType prop accepts a set of predefined values ( for example MessageBarType.error or MessageBarType.blocked ), but we should be able to pass in a custom SVG icon to the messageBarType prop. 

Currently, if you do not include the messageBarType prop, the "info" icon will be displayed by default. There should be an option to not display any icons.

This is important for people like me who are using Office UI Fabric React for non-Microsoft related projects, this way we won't violate the [ assets license agreement](https://static2.sharepointonline.com/files/fabric/assets/microsoft_fabric_assets_license_agreement_sept092017.pdf)

**Comment by keydoubleu** [comment]
@micahgodbolt 
Oh wow! I had no clue unregisterIcons() even existed, that's so awesome! Thank you so much for pointing that out.

I can only imagine how many hidden little treasures like this exist in Office UI Fabric React.

**Comment by micahgodbolt** [comment]
I'm working on trying to document them all! Does this solution work for you?

**Comment by keydoubleu** [comment]
It absolutely does, thank you once again! And I am so happy to hear that you are working on the docs, we really need them in order to harness the full power of this wonderful library!
