### ISSUE TITLE
Using an onRender in a ContextualMenuItem gives a 'needs key' warning

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#6289]
https://codepen.io/micahgodbolt/pen/ZMaoqo?editors=1010#

![image](https://user-images.githubusercontent.com/1434956/45245782-bc6d4280-b2b2-11e8-8d98-b651ac5cb240.png)

![image](https://user-images.githubusercontent.com/1434956/45245787-c3945080-b2b2-11e8-94a8-0e47989538fc.png)

**Comment by kenotron** [comment]
Non minified:
<img width="967" alt="screen shot 2018-09-08 at 12 51 43 pm" src="https://user-images.githubusercontent.com/34725/45258066-0105e600-b366-11e8-9e77-b6a2f6821bcf.png">
