### ISSUE TITLE
New Component: File Picker

### ISSUE THREAD

**Issue by rickyp-ms** [OfficeDev/office-ui-fabric-react#629]
I was just curious if there were any plans to make a shared file picker control that would integrate into 3rd party services (data provided through props so it's just focusing on the UI).

We are already debating making something as OneDrive's file picker isn't React based, it's slow and also doesn't scale down to 300px making it hard to use on mobile sites. Just a question of should we put it here if you think it would be useful for multiple people.

**Comment by dzearing** [comment]
It isn't something that we've been focused on but i think it would be a really good project.

**Comment by rickyp-ms** [comment]
I think we are looking into to be able to upload files to OneDrive, good to know that is already somewhere.

I'll check with my designers and get back to you... keeping this open for now depending on the response....

**Comment by rickyp-ms** [comment]
Clearing up any opened bugs... This was basically dealt with using the DetailsList component so that works.

**Comment by MarkStokes-outlook** [comment]
@rickyp-ms can you point us in the right direction here. I am also looking for a Office styled file picker to go in my app, but don't see anything in the DetailsList component that we can use?

Is this still only for your internal use?

**Comment by ImenTurki** [comment]
hello ,please any one found a solution for office-ui-fabric-react for upload file ? 
how do you satisfy this .
