### ISSUE TITLE
scroll behaviour on contextmenus (dropdown, combobox, ...)

### ISSUE THREAD

**Issue by OneCyrus** [OfficeDev/office-ui-fabric-react#6292]
![scroll](https://user-images.githubusercontent.com/7747800/45253006-d87aed80-b35f-11e8-9222-e16390fcee0a.gif)

### Bug Report 
 
 
- __Package version(s)__: latest version on the demo site
- __Browser and OS versions__: chrome 69 (and looks like it hapopens in all browsers)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal 
  
#### Describe the issue:
 
when opening the context menu and scrolling with e.g. the mouse wheel the context menu doesn't stay open and doesn't move with the page. it just closes.
 
#### Actual behavior:
 
opening a contextmenu closes when scrolling the page
 
#### Expected behavior:
 
contextmenu stays open and only closes when user selects something or clicks outside of the contextmenu

**Comment by keydoubleu** [comment]
As a website user, I think it would be bad UX to have the drop-down menu following me around as I scroll down/up. The only improvement would be to keep the drop-down menu open until I manually close it (by clicking outside of it), but I think the ComboBox UX is pretty good as it is right now.

**Comment by micahgodbolt** [comment]
I certainly agree that the menu shouldn't follow you around, if anything it should stay attached to it's parent element. With menus sitting in layers this is difficult as we calculate the position on render, and it would be expensive to continue to track that position as the user scrolled. 

It may be possible to support this behavior, but we'd probably need to not put the menu on its own layer, but rather keep it inline in the DOM and attach it via position absolute.

**Comment by OneCyrus** [comment]
yes, the contextmenu shouldn't stay at the same position (on the screen). it should be "fixed" to the control (e.g. combobox) and move with the page. we have some comboboxes with larger lists (options) where we see this issue happening unintentionally to a lot of people.

**Comment by betrue-final-final** [comment]
This is expected behavior for menus in general. Look at both Windows and OSX.
