### ISSUE TITLE
IconButton focus style is not working in IE11

### ISSUE THREAD

**Issue by huanwang111** [OfficeDev/office-ui-fabric-react#6295]
IconButton focus style is not working in IE11, but workings in Chrome.

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/huanwang111/full/xapmRY/
I suppose codepen is using the latest fabric version, and codepen is not working in IE11. 

### Bug Report 
 
 
- __Package version(s)__: (fill this out) 6.61.2
    "@uifabric/styling": "^6.5.0",
    "office-ui-fabric-react": "^6.61.2",

- __Browser and OS versions__:  IE11 and windows server 2012 R2 and windows server 2016
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
Requested priority: Blocking  
Products/sites affected: (if applicable): SharePoint Migration Tool
 
#### Describe the issue:
 
IconButton focus style is not working in IE11, and it will impact SharePoint Migration tool accessibility review, and blocking the release.
 
#### Actual behavior:
 
No styling if the IconButton got focus
![iconbutton-ie11](https://user-images.githubusercontent.com/43128677/45284537-64138c00-b4d0-11e8-98a2-922ec3823d97.PNG)

 
#### Expected behavior:
 
Focus style should display as in Chrome
![iconbutton-chrome](https://user-images.githubusercontent.com/43128677/45284463-2f9fd000-b4d0-11e8-88a7-a11ad871c72a.PNG)

**Comment by joechung-msft** [comment]
You need a <Fabric> element to contain the icon buttons.  That's also why the "Standard" label is in a serif, instead of a sans serif, font.

**Comment by micahgodbolt** [comment]
Seems to be working now with your updated pen 
![image](https://user-images.githubusercontent.com/1434956/45562437-5414e880-b7ff-11e8-876a-d83a2137b893.png)
