### ISSUE TITLE
How to redirect from one component to another 

### ISSUE THREAD

**Issue by piyumi25** [OfficeDev/office-ui-fabric-react#6296]
I created office outlook addin and  I need to redirect to a separate component when button is clicked. I have used route for above senario but I got this error.
![route error](https://user-images.githubusercontent.com/33615108/45292382-ae1d6180-b512-11e8-8d51-f962a3fc1492.PNG)

**Comment by kenotron** [comment]
I think this is a router question, not a Fabric issue. Please contact the dev who implemented the router in your repo to get your question answered. Please feel free to close this issue if you agree with this assessment.
