### ISSUE TITLE
Datepicker not closing 

### ISSUE THREAD

**Issue by realhoffi** [OfficeDev/office-ui-fabric-react#6297]
Technologies: Typescript, Webpack

Requested priority: Blocking
 
The current date picker control has a bug. if i select a date from the opened date popup, then the popup is not closing.
 
#### Actual behavior:
 
Datepicker "select Date" Popup is not closing after date selection
 
#### Expected behavior:
 Datepicker "select Date" Popup is closing after date selection

package.conf

  "sideEffects": false,
  "license": "MIT",
  "dependencies": {
    "axios": "^0.18.0",
    "babel-polyfill": "^6.26.0",
    "bluebird": "^3.5.2",
    "lodash.clonedeep": "^4.5.0",
    "lodash.debounce": "^4.0.8",
    "office-ui-fabric-react": "^6.67.0",
    "react": "^16.5.0",
    "react-dom": "^16.5.0",
    "react-router-dom": "^4.3.1",
    "uuid": "^3.3.2"
  },
  "devDependencies": {
    "@types/axios": "^0.14.0",
    "@types/bluebird": "^3.5.24",
    "@types/jasmine": "^2.8.8",
    "@types/lodash.clonedeep": "4.5.4",
    "@types/microsoft-ajax": "0.0.33",
    "@types/node": "^10.9.4",
    "@types/react": "16.4.13",
    "@types/react-dom": "^16.0.7",
    "@types/react-router": "4.0.30",
    "@types/react-router-dom": "4.3.0",
    "@types/requirejs": "^2.1.31",
    "@types/uuid": "^3.4.4",
    "awesome-typescript-loader": "^5.2.1",
    "clean-webpack-plugin": "^0.1.19",
    "compression-webpack-plugin": "^2.0.0",
    "copy-webpack-plugin": "^4.5.2",
    "jasmine": "^2.99.0",
    "jasmine-core": "^3.2.1",
    "source-map-loader": "^0.2.4",
    "ts-loader": "^5.1.0",
    "tslint": "^5.11.0",
    "tslint-loader": "^3.6.0",
    "typescript": "^3.0.3",
    "webpack": "^4.17.2",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-cli": "^3.1.0",
    "webpack-notifier": "^1.6.0"
  }

**Comment by micahgodbolt** [comment]
confirmed https://codepen.io/micahgodbolt/pen/WgMXmB

@KevinTCoughlin can you take a look?
