### ISSUE TITLE
Slider Control UI element off my 2px

### ISSUE THREAD

**Issue by chiubacca** [OfficeDev/office-ui-fabric-react#630]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: 
Safari, Chrome, MacOS El Capitan/Sierra

#### Describe the issue:

Circular slider control is too far up by 2px 
https://dev.office.com/fabric#/components/slider

#### Actual behavior:

![slider](https://cloud.githubusercontent.com/assets/7328988/20730845/82897120-b63c-11e6-84b0-08d7f8d2a929.png)

#### Expected behavior:

![slider-centered](https://cloud.githubusercontent.com/assets/7328988/20730825/6e9ff6b6-b63c-11e6-8511-c0b718d424b9.png)

**Comment by dzearing** [comment]
I'm not reproing it here:
http://codepen.io/dzearing/pen/GNZMgq

**Comment by dzearing** [comment]
Is your browser zoomed?

**Comment by dzearing** [comment]
Nope nevermind, I've repro'd it *only on the Fabric site*, because the site is added some global box-sizing: border-box rules that affect this. This is not apparent when actually using the slider.

**Comment by dzearing** [comment]
Closing issue, change will be published in the next build of fabric-react and will be picked up by the docs site next week.
