### ISSUE TITLE
DetailsList columnReorderOptions not updating when state updates

### ISSUE THREAD

**Issue by goodoldneon** [OfficeDev/office-ui-fabric-react#6311]
### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/goodoldneon/pen/xaYJBg

### Bug Report 
 
 
- __Package version(s)__: 6.67.1
- __Browser and OS versions__: Chrome 68.0.3440.106 and macOS 10.13.6
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? I'll try
 
Requested priority: Normal
 
Products/sites affected: N/A
 
#### Describe the issue:
 
Toggling `DetailsList` prop `columnReorderOptions` via state breaks column reordering.
 
#### Actual behavior:
 
1. On initial load, column reordering works.
1. After toggling `columnReorderOptions` off, the columns still appear reorder-able but can't actually be reordered. In other words, they have the reorder icon and can be dragged.
1. After toggling `columnReorderOptions` on again, the columns no longer have any appearance of reorder-ability.
1. Future toggles keep appearing like steps 2 and 3.
 
#### Expected behavior:
 
Toggling `columnReorderOptions` off should prevent columns from being reordered, and toggling on should enable reordering.

**Comment by goodoldneon** [comment]
The issue appears to be caused by assigning `columnReorderProps` to `this._columnReorderProps` in `componentDidUpdate()`. Since `this._columnReorderProps` is used in the `render()` method, `columnReorderProps` is always one render "behind".

I fixed this by putting `columnReorderProps` into `state`, and updating it using the `getDerivedStateFromProps()` lifecycle method. You can find the changes [in my fork](https://github.com/goodoldneon/office-ui-fabric-react/tree/fix-6311). I haven't sent a PR since tests are failing when I run `npm run build`. I'm a new developer, so I'd appreciate any help getting my build working. I'd love to contribute more to this amazing project!

Additionally, I think the logic in `componentWillReceiveProps()` needs to be moved to `getDerivedStateFromProps()` in preparation for React 17. However, I didn't want to make any changes that were outside the scope of this issue.

**Comment by KevinTCoughlin** [comment]
Nice find!
