### ISSUE TITLE
Native props not supported in Panel Interface

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#6321]
### Bug Report 
 
- __Package version(s)__: latest
 
#### Priorities and help requested:

Requested priority: High
 
Products/sites affected: SharePoint PageSettingsPanel
 
#### Describe the issue:
 
Still unable to assign aria-describedby prop to Panel component.
Bug [3634](https://github.com/OfficeDev/office-ui-fabric-react/issues/3634) was opened and was closed by this [code fix](https://github.com/OfficeDev/office-ui-fabric-react/pull/4626) . Although the fix add support of native props to Panel, but didn't update the typing of IPanelProps so we still cannot pass native props like `aria-describedby` to Panel component.

**Comment by KevinTCoughlin** [comment]
What would be the most flexible solution? Can we swap `React.Props<T>` for `React.HTMLProps<T>`? 

```diff
diff --git a/packages/office-ui-fabric-react/src/components/Panel/Panel.types.ts b/packages/office-ui-fabric-react/src/components/Panel/Panel.types.ts
index e4fce545f..ffe9f61f9 100644
--- a/packages/office-ui-fabric-react/src/components/Panel/Panel.types.ts
+++ b/packages/office-ui-fabric-react/src/components/Panel/Panel.types.ts
@@ -16,7 +16,7 @@ export interface IPanel {
    */
   dismiss: (ev?: React.KeyboardEvent<HTMLElement>) => void;
 }
-export interface IPanelProps extends React.Props<PanelBase> {
+export interface IPanelProps extends React.HTMLAttributes<PanelBase> {
   /**
    * Optional callback to access the IPanel interface. Use this instead of ref for accessing
    * the public methods and properties of the component.
```

There's a mismatch with `type` if we did that. I'm trying to avoid having to define the native props as we need them.

**Comment by micahgodbolt** [comment]
I think we'd be fine with HTMLProps. If we used `InputHTMLAttributes` we'd have trouble with that 'type' prop.
