### ISSUE TITLE
Don't select DetailsList row on click

### ISSUE THREAD

**Issue by willtrking** [OfficeDev/office-ui-fabric-react#633]
Is it possible to ONLY allow a DetailsList row to be selected by clicking on the selection checkbox, and not on the entire row? Or perhaps prevent the selection if the click is in a certain column? This would be useful to prevent row selection when entering data into a TextField or clicking a Button in the DetailsList

Thanks!

**Comment by dzearing** [comment]
It's possible we could add a `data-selection-disabled={true}` attribute support. Then you could render a custom column where if the focus is within there, selection doesn't react to input.

Would that solve your problem?

**Comment by willtrking** [comment]
Yes, that would be extremely helpful!

**Comment by dzearing** [comment]
I've created a PR to support this, will talk with folks tomorrow to get it in.

**Comment by dzearing** [comment]
This has been checked in and will be published tonight.
