### ISSUE TITLE
customizable typings

### ISSUE THREAD

**Issue by VincentBailly** [OfficeDev/office-ui-fabric-react#6337]
### Bug Report 

- __Package version(s)__: 6.67.2

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal
 
#### Describe the issue:
customizable.tsx:
  - should accept a React.ComponentType<T> instead of `new (props:p .....` so that we can use it with a functional component
  - should not return any but React.ComponentClass<...>

**Comment by cliffkoh** [comment]
Makes sense to me!
