### ISSUE TITLE
Display a message when a multiselect dropdown in office ui fabric is collapsed

### ISSUE THREAD

**Issue by licypal** [OfficeDev/office-ui-fabric-react#6345]
Is there a way to know when a multiselect dropdown is collapsed? I have a multiselect dropdown as show here:

![multiselect dropdown](https://user-images.githubusercontent.com/6519992/45450455-2871f100-b68d-11e8-957d-444e0c9eef4e.JPG)

On unselecting all options, the dropdown still remains expanded as shown in the above image. On clicking somewhere else in the screen outside dropdown, it collapses. I need to perform some actions (for example, display a message when dropdown collapses). Is there a way to know when a multiselect dropdown is collapsed? Thanks!

**Comment by KevinTCoughlin** [comment]
Perhaps this property `onMenuDismissed` would help notify you of when the ComboBox's menu is dismissed.

https://github.com/OfficeDev/office-ui-fabric-react/blob/02814cbe9b8d3994b40c9afc6825625e078bd3fe/packages/office-ui-fabric-react/src/components/ComboBox/ComboBox.types.ts#L79

**Comment by licypal** [comment]
Thanks @KevinTCoughlin Is this property available for Dropdown?

**Comment by licypal** [comment]
I see this error on using OnMenuDismissed in Combobox:

![image](https://user-images.githubusercontent.com/6519992/45459488-59fab480-b6ad-11e8-8f62-0eea8802593a.png)

**Comment by KevinTCoughlin** [comment]
> Thanks @KevinTCoughlin Is this property available for Dropdown?

`<Dropdown/>` has `onDismiss` available as part of `IDropdownProps`:

https://github.com/OfficeDev/office-ui-fabric-react/blob/02814cbe9b8d3994b40c9afc6825625e078bd3fe/packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.types.ts#L39

**Comment by KevinTCoughlin** [comment]
> I see this error on using OnMenuDismissed in Combobox:
> 
> ![image](https://user-images.githubusercontent.com/6519992/45459488-59fab480-b6ad-11e8-8f62-0eea8802593a.png)

Can you show more of your code, the TS error call-out is masking the component structure so its difficult for me to offer advice. But you should be able to write a function like:

```tsx
<Dropdown
  onDismiss={ () => console.log('dismissed') }
  ...
  />
```

**Comment by licypal** [comment]
![image](https://user-images.githubusercontent.com/6519992/45459769-c6c27e80-b6ae-11e8-98d1-5e32da5a8b6c.png)

**Comment by licypal** [comment]
Am I missing any import?

**Comment by KevinTCoughlin** [comment]
@licypal that should work as I have it working in [this Codepen](https://codepen.io/kevintcoughlin/pen/YOvvbM). You'll see the dismissal logs printed to the console.

**Comment by licypal** [comment]
I saw your code. Not sure why it is showing error when I add onDismiss property. Do I have to import anything else other than Dropdown and IDropdownOption?

**Comment by licypal** [comment]
I was able to use onBlur instead. But, I need to click outside Dropdown twice in order to print the message.

<Dropdown
options={[
            { key: 'A', text: 'Option a' },
            { key: 'B', text: 'Option b' },
            { key: 'C', text: 'Option c' }
          ]}
multiSelect={true}
onBlur={this.onFilterDropDownDismiss}	
/>

private onFilterDropDownDismiss = (): void => {
    console.log("Dismissed");
}

**Comment by licypal** [comment]
@KevinTCoughlin How will I share my code with you?

**Comment by KevinTCoughlin** [comment]
I think the issue here is that the version of OUIFR is `4.43.1` which predates https://github.com/OfficeDev/office-ui-fabric-react/pull/3087

**Comment by licypal** [comment]
I installed office-ui-fabric-react@5.124.0 and now I can use onDismiss property. Thank you @KevinTCoughlin.
