### ISSUE TITLE
Property to check if dropdown is expanded or collapsed

### ISSUE THREAD

**Issue by licypal** [OfficeDev/office-ui-fabric-react#6348]
Is there a way to check if dropdown is expaned or collapsed? Similar to isOpen/onDismiss for Panel?

**Comment by KevinTCoughlin** [comment]
Hey @licypal,

There is `isOpen` on `IDropdownState` but I'm not sure if that will work for you?

https://github.com/OfficeDev/office-ui-fabric-react/blob/02814cbe9b8d3994b40c9afc6825625e078bd3fe/packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx#L45

**Comment by licypal** [comment]
I see this error on using isOpen in Dropdown:

![image](https://user-images.githubusercontent.com/6519992/45459428-228c0800-b6ad-11e8-9f5f-f5b25c2d3ea6.png)

**Comment by KevinTCoughlin** [comment]
Yea, its not available as a `prop` only on the component's state.

**Comment by licypal** [comment]
Could you please let me know what does this error indicate?

**Comment by KevinTCoughlin** [comment]
> Could you please let me know what does this error indicate?

A Component's `state` is internal to itself so you can't access it via `props` (the attributes on the JSX element). The TS error you are facing above is showing that `isOpen` is not available on `IDropdownInternalProps` which is the interface for the Dropdown Component's props.

To check if the dropdown is closed, I'd still advocate using `onDismiss` which for some reason isn't working for you as detailed here: https://github.com/OfficeDev/office-ui-fabric-react/issues/6345#issuecomment-421149355.

That said, I haven't found a great way of knowing if the `Dropdown` is open aside from hooking into a `focus` event.

**Comment by licypal** [comment]
Got it fixed by updating office-ui-fabric-react version to 5.124.0. Thank you @KevinTCoughlin!
