### ISSUE TITLE
Some styles are not applied for button types 

### ISSUE THREAD

**Issue by biogenez** [OfficeDev/office-ui-fabric-react#635]
Button's type specific css styles are not works after the changeset:
[Reduce specificity of button modifiers](https://github.com/OfficeDev/office-ui-fabric-react/commit/e20fd424fb278fa090cddb6417915a47a83024cf) 
They are overriden by ms-Button class
![7e69c8e4-b72a-11e6-9a8b-5b067f955427](https://cloud.githubusercontent.com/assets/4600781/20772105/ddf95926-b754-11e6-8d47-06254d3bf0ca.PNG)
.

**Comment by mikewheaton** [comment]
Thanks for catching this, @biogenez. I'll go in and fix the hover states for the buttons.

**Comment by dzearing** [comment]
This has been merged and will be published tonight.
