### ISSUE TITLE
Grouped list - display items between group and their children

### ISSUE THREAD

**Issue by veeramanx** [OfficeDev/office-ui-fabric-react#6367]
Hi,

is it possible to display items between group and their children. Please see the screenshot for the reference

![image](https://user-images.githubusercontent.com/36476607/45547268-212b1e80-b818-11e8-8811-2836f9c1bf54.png)

**Comment by veeramanx** [comment]
I don't think what i am after is possible with grouped list control. are their any plans to implement tree view control in office UI Fabric react ? thanks.

**Comment by micahgodbolt** [comment]
A proper tree view has been discussed several times, but hasn't been prioritized yet. Very hard to do right (in a way that scales), so often easier to implement locally.

**Comment by fljiang** [comment]
How do you implement it locally?

**Comment by micahgodbolt** [comment]
@fljiang I just mean product teams implement it in their own application vs having a shared version in fabric.
