### ISSUE TITLE
Allow rendering of icon on either side of text in buttons

### ISSUE THREAD

**Issue by bpringe** [OfficeDev/office-ui-fabric-react#6368]
**Describe the feature that you would like added**
When adding a button, such as an ActionButton, I can specify an iconName in the Icon props, but I would like to be able to render the icon on the right for some buttons. For example, if I have previous and next buttons that use the Previous and Next icons, I want the Next icon rendered to the right of the text "Next" that I place in the button.

**What component or utility would this be added to**
This would be added to the ActionButton component, and I guess other button components that support IconProps.

**Have you discussed this feature with our team, and if so, who**
I have not.

**Additional context/screenshots**
![previous_next aspx](https://user-images.githubusercontent.com/12722744/45557168-9f7cc600-b802-11e8-8d5f-b2eecbc978ea.png)
This is what I was referring to. I would like that Next icon to display to the right of the "Next" text, and I'd like to be able to do that with the button components like ActionButton, maybe by setting a 'iconSide' property to 'right' or something, maybe using an enum for that value.

**Comment by micahgodbolt** [comment]
You can already do this in one of two ways. You can add menuIconProps (though the menu icon is styled smaller so this might be annoying), or you can simply flip the flex direction on the flexContainer

https://codepen.io/micahgodbolt/pen/zJLdoV?editors=1010

**Comment by bpringe** [comment]
Reversing the flex direction works for me. I was unfamiliar with CSS flexbox. Thank you.
