### ISSUE TITLE
Pressing enter in spin button doesn't highlight text anymore

### ISSUE THREAD

**Issue by chang47** [OfficeDev/office-ui-fabric-react#6376]
### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/JoshChang47/pen/qMyMXO

### Bug Report 
 
 
- __Package version(s)__: Fabric Core 9.6.0 and Fabric React 6.49.2
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Low
 
Products/sites affected: All
 
#### Describe the issue:
 
If a user presses enter in a spin button after changing values, the text doesn't get selected
 
#### Actual behavior:
 
Nothing happens
 
#### Expected behavior:
 
Text in the input gets selected

**Comment by micahgodbolt** [comment]
I'm assuming it was because of #6363 right? Is this issue just to track that issue? It seems like @jspurlin was suspicious 6363 might affect this behavior.

**Comment by chang47** [comment]
@micahgodbolt actually it's not, I was able to reproduce this problem without my change. I even cloned the main Fabric repro and tested the behavior and I ran into the same problem

**Comment by micahgodbolt** [comment]
@chang47 oh gotcha! Thanks for the clarification. We'll try to dive in as well. Tell us if you find anything.

**Comment by micahgodbolt** [comment]
@chang47 I think the main question is "whats the expected behavior". @jspurlin probably has the best context on that. TBH, i'm not sure if any of our inputs have this behavior of selecting the input upon hitting enter. So maybe it was intentional? Would have to track down when this code change occurred to see if there was a rationale for the change.

**Comment by micahgodbolt** [comment]
@jspurlin do you have any documentation about expected behavior when 'enter' key is pressed? Should it select the current value or not?

**Comment by khmakoto** [comment]
Hi @chang47, sorry for the long time it has taken to reply again to this issue! If you look at the number-typed input in html it doesn't have this behavior, as you can see in [this codepen](https://codepen.io/khmakoto/pen/QWbWEBm), so I don't think there's any expectations for us to do that. Let us know if there is anything else we can do to help!
