### ISSUE TITLE
Printing with fabric react

### ISSUE THREAD

**Issue by PSchicht** [OfficeDev/office-ui-fabric-react#6379]
Hi!

I wrote an application that has a print form. At the moment, when i try to print, no css is included. Do you have some guidance on how to include the application (Fabric Core, ...) css for printing or implement printing capabilities in general?

Thanks a lot!
Pascal

**Comment by SibeeshVenu** [comment]
@PSchicht I am also trying to add a print functionality but it seems to be not working. Do you mind sharing what worked for you? Are you using any custom packages?

**Comment by micahgodbolt** [comment]
Printing to PDF seems to work fine for me 
![image](https://user-images.githubusercontent.com/1434956/50523901-7584a200-0a87-11e9-9150-55ace0497cbc.png)
