### ISSUE TITLE
It does not read Dropdown role from Narrator and Edge

### ISSUE THREAD

**Issue by jayleems2018** [OfficeDev/office-ui-fabric-react#6381]
### Bug Report 
 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)
 
#### Describe the issue:
 
It does not read Dropdown role from Narrator.
 
#### Actual behavior:
 
It does not read control role as dropdown
 
#### Expected behavior:
 
It should read control role as dropdown

**Comment by micahgodbolt** [comment]
is it currently reading "listbox", or is it just not saying anything at all?

**Comment by jayleems2018** [comment]
No.  It is not reading role as "listbox".

**Comment by Vitalius1** [comment]
Closing as it's duplicating #5752
