### ISSUE TITLE
Dialog Enforced Max-Width Update

### ISSUE THREAD

**Issue by gblunden** [OfficeDev/office-ui-fabric-react#6383]
Hi Team,

Has there been a recent update to enforce max-width on a Dialog component?

We are using Dialog in SPO to display list items using the ms-grid and it appears external styling has been enforced to restrict the width of **.ms.Dialog.main** to **480px**.

Thanks,
Gary

**Comment by micahgodbolt** [comment]
Until just recently the Dialog had the following props, but didn't actually use them:

![image](https://user-images.githubusercontent.com/1434956/45637326-072f4d00-ba5f-11e8-879a-f591238445a1.png)

So the maxWidth styles should not have changed, but if you had passed in a maxWidth prop in the past, it is now working properly.

**Comment by micahgodbolt** [comment]
i.e. if you need to remove the maxWidth of your dialog, you can pass in `maxWidth='none'`
