### ISSUE TITLE
Bug: SelectionZone infinity while loop 

### ISSUE THREAD

**Issue by biogenez** [OfficeDev/office-ui-fabric-react#639]
**Bug**
If the height of the body element is less then a page height, any click on the area outside of the body element (for example: at the bottom of the page) causes an infinite loop.

File: [SelectionZone.tsx](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/utilities/selection/SelectionZone.tsx)

Wrong code:

`private _isNonHandledClick(element: HTMLElement): boolean {  
    let doc = getDocument();  
    if (doc && element) {  
      while (element !== doc.body) {  
        if (isElementTabbable(element)) {  
          return false;  
        }  
        element = getParent(element);  
      }  
    }  
    return true;  
  }`

p.s.: chrome & ie (+edge) are crashed in this case. And only the firefox browser showed a reason. 
p.s.2: that killed my day )))

**Comment by mikewheaton** [comment]
Thank you for the bug report and tracking down where this issue is coming from. We'll take a look.

**Comment by biogenez** [comment]
Example:
![capture](https://cloud.githubusercontent.com/assets/4600781/20807787/f2156846-b808-11e6-878f-c2746ccf3c51.PNG)

**Comment by dzearing** [comment]
Will be fixed and published today.

**Comment by dzearing** [comment]
Merged. Published 8pm PST tonight.
