### ISSUE TITLE
Command Bar items render as an ellipsis

### ISSUE THREAD

**Issue by ALaveault** [OfficeDev/office-ui-fabric-react#6393]
### Bug Report 
 
- __Package version(s)__: 5.112.0
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority:  High
 
Products/sites affected: Microsoft Dynamics 365 Project Service Solution
 
#### Describe the issue:
 
We have multiple controls using the CommandBar component. Those controls are each in iframe. When updating the commandBar, and navigating to another control (in another iframe) the items render under an ellipsis icon.

We've done some investigation and it seems that it is a combination of  _commandBarRegion.current.clientWidth is less than or equal to 0 and _commandBarRegion.current is null.

Note that the farItems seem to always render correctly and this only apply to the items on the commandBar.
 
#### Actual behavior:
 
Command Items render under an ellipsis icon.
![commandbarellipsis](https://user-images.githubusercontent.com/40213434/45650431-1de79b00-ba83-11e8-9215-91dbf4720d8a.png)

#### Expected behavior:
 
Command Items should render correctly even when the CommandBar is not in the view port.

**Comment by micahgodbolt** [comment]
Is there any possibility of migrating to the 6.0 branch? We completely rewrote the command bar in 6.0.

**Comment by ALaveault** [comment]
The 6.0 branch uses React 16 correct? We are still using React 15 and need a thorough investigation before we can move forward with React 16.

**Comment by micahgodbolt** [comment]
Yes, it's using React 16. You might be able to get by pulling the new CommandBar from our older experiments package. That might be a decent stopgap until you are able to migrate (or at least confirm if 6.x command bar works for you).

**Comment by micahgodbolt** [comment]
have you had any luck updating to 6.x or finding a workaround? The 5.x command bar is no longer being maintained.

**Comment by ALaveault** [comment]
We are in the middle of the transition to react 16 and 6.x and should have some more feedback after the holidays.
