### ISSUE TITLE
"title" tooltip in context menus does not appear when focusing via keyboard

### ISSUE THREAD

**Issue by hoovercj** [OfficeDev/office-ui-fabric-react#6398]
### Please provide a reproduction of the bug in a codepen:
https://codepen.io/anon/pen/eLQmqb 

### Bug Report 

- __Package version(s)__: All 
- __Browser and OS versions__: Windows 10 with Edge 
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low) 
High
 
Products/sites affected: (if applicable)
Microsoft product. Can discuss on TEAMS

#### Describe the issue:
 
Edge displays "title" information via a tooltip when focusing on elements. As seen in the attached codepen, tabbing to the context menu trigger and the other "button", a tooltip appears. however, when activating the context menu, the tooltip for individual context menu items ("new" and "rename") are only available via mouseover.

I can see that context menu items are buttons that are inside lists, so I built a small example of that manually and could see that it still works, so the issue is oviously elsewhere. 

This has been reported to us by accessibility test vendors as a violation of MAS 2.1.1 – Keyboard (36)

**Comment by KevinTCoughlin** [comment]
@hoovercj Wow! I've never seen this before.. it seems like behavior custom to Edge w.r.t the [title](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title) attribute based off of this http://jsfiddle.net/538cfrzn/1/

**Comment by micahgodbolt** [comment]
This one is really interesting. The titles get to the DOM (both the list item AND the button). But it seems the focus applied by focus zone isn't activating this tooltip. @KevinTCoughlin do you think it's more a focus zone issue? I wonder if other items in focus zones have the same issue.

**Comment by hoovercj** [comment]
Yes, now that Edge is moving to Chromium, any mitigations done by the office fabric team will stop working later this year. I'll close this bug and discuss alternatives with my team.
