### ISSUE TITLE
ContexualMenu, Callout Example: Direction issue during RTL

### ISSUE THREAD

**Issue by atneik** [OfficeDev/office-ui-fabric-react#64]
ContexualMenu doesn't change it's direction when in RTL

**Left to Right, Right Center**
Excepted: Right Center
<img width="932" alt="screen shot 2016-08-03 at 7 13 43 pm" src="https://cloud.githubusercontent.com/assets/785361/17388113/a993b180-59ae-11e6-8fc5-b506fe91f04b.png">

**Right to Left, Right Center**
Expected: Left Center, but it's Right Center
<img width="752" alt="screen shot 2016-08-03 at 7 14 02 pm" src="https://cloud.githubusercontent.com/assets/785361/17388114/ac27878c-59ae-11e6-9688-c3e2b42d46dc.png">

**Comment by dzearing** [comment]
I'm not sure this is a bug. @atneik Maybe a better naming convention would be near/far. Then we could flip it automatically. It's possible we could add those, so if you say left, you mean LEFT, but if you say near, you mean left/right in ltr/rtl.

**Comment by dzearing** [comment]
This works as intended.
