### ISSUE TITLE
SearchBox in CommandBar Issue?

### ISSUE THREAD

**Issue by kevinbargary** [OfficeDev/office-ui-fabric-react#6400]
Hey,
I'm not sure if this is a bug with `CommandBar` but when a `SearchBox` is added to an `OverflowSet` the styles are OK out of the box. When a `SearchBox` is added to a `CommandBar` there is immediately an alignment issue with the `SearchBox`.

![image](https://user-images.githubusercontent.com/467355/45686072-577fdb00-bb43-11e8-8d44-7232ae1bca79.png)

Sandbox [here ](https://codesandbox.io/s/o5w2jyjqj6)

**Comment by micahgodbolt** [comment]
Regular buttons and searchboxes have a fixed standard height. So toss them into a overflowSet and they look fine. But CommandBar has a height taller than buttons/searchbox, so when you drop a fixed height item into it, it won't automatically snap. 

You can see this if you add some height and background to your overflowSet exmple.

![image](https://user-images.githubusercontent.com/1434956/45716235-302d0c00-bb4b-11e8-8182-2971cf11361f.png)

So not a bug really. Many components will need additional styling if you drop them into something like the commandbar or other command surfaces. 

So not a bug, but I could see us adding a feature that makes these components drop in easier.

**Comment by kevinbargary** [comment]
@micahgodbolt thanks for the response. I figured as much, I just wanted to see if I could escape without having to write CSS myself 😉 I'm trying to keep tampering to a minimum. Might just use the `OverFlowSet` for my use case. I'll close this "bug" so. 👍
