### ISSUE TITLE
Swatch Color Picker - White color border issue

### ISSUE THREAD

**Issue by RupamSarkar** [OfficeDev/office-ui-fabric-react#6401]
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) : High
 
Products/sites affected: (if applicable)
 
#### Describe the issue: 
 In Swatch Color Picker the border for white color does not appear in case of rgba(0,0,0,0) value . We are using rgba values for our scenarios and can't use fixed value(#FFFFFF) .  The border isn't coming because I think the check is missing in line number 105 for rgba(0,0,0,0)  of this [file ](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/SwatchColorPicker/ColorPickerGridCell.base.tsx) .

 
#### Actual behavior:

![sssss](https://user-images.githubusercontent.com/17047049/45687731-1c929d00-bb6d-11e8-8ccd-782efdc866d4.png)

 
#### Expected behavior:
 The border should appear for white - rgba(0,0,0,0) also .

**Comment by KevinTCoughlin** [comment]
@RupamSarkar thanks for the report. I'll take this unless you want it since I was recently in here for #6222.

**Comment by KevinTCoughlin** [comment]
@RupamSarkar `rgba(0, 0, 0, 0)` is technically transparent which would be noticeable if your container background is non-white. We can check `rgb(255, 255, 255)` and `rgba(255, 255, 255, 1)`.. would that work? I'll look into a more robust solution for checking `isWhite`.

![image](https://user-images.githubusercontent.com/706967/45721646-bbaf9880-bb5d-11e8-8211-0aa04a71f9a0.png)

**Comment by KevinTCoughlin** [comment]
I think `#FFF` will also break the comparison.

**Comment by RupamSarkar** [comment]
Yes I think we should do more robust solution for checking White , As there are multiple ways to show a white color . Also if we have a button for No Color (Transparent )  that should also have the border , right ?

**Comment by RupamSarkar** [comment]
@KevinTCoughlin  Hi Kevin , Sorry for late reply - 

We have to implement a color picker like this - 
![colorpicker](https://user-images.githubusercontent.com/17047049/46007084-c37bb980-c0d6-11e8-9ce6-851f847641b1.png)

As you can see , there are borders for each of the 4 colors in first row . I think it would be better if we have prop to control the border(color,width etc) as you mentioned . Because in dark background the picker should look like this -

![colorpickerdark](https://user-images.githubusercontent.com/17047049/46007268-4270f200-c0d7-11e8-8eb2-7f07fc462250.png)
