### ISSUE TITLE
Dropdown: Fluent experiment

### ISSUE THREAD

**Issue by Vitalius1** [OfficeDev/office-ui-fabric-react#6412]
Design ready, may need to convert to CSS-in-JS before styling.

**Comment by mikewheaton** [comment]
Assigning to @betrue-final-final for design review.

**Comment by betrue-final-final** [comment]
This looks great, except for a couple of unusual things:

1. In error state, on hover the placeholder text is changing color. There should be no color change.
2. Selected menu item on hover gets blue text and should not.
3. Disabled menu item text is still gray60, should be gray90

**Comment by betrue-final-final** [comment]
Looks good!
