### ISSUE TITLE
DetailsList: add callback to get column widths on resize

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#6413]
This feature will help us support overflowSets inside of columns. So rather than using a resizeGroup, or manually measuring column widths, if the DetailsList can report the widths it has determined for each column, we can manually adjust the items in the overflowSet.

**Comment by micahgodbolt** [comment]
This is needed to unblocked a Flows scenario.

**Comment by micahgodbolt** [comment]
Rank 1 for is blocked scenario with no reasonable workaround

**Comment by KevinTCoughlin** [comment]
@micahgodbolt is this callback invoked per column resize or on list resize?

**Comment by micahgodbolt** [comment]
good point, there's both situations, page resize and user resize. I'd suggest both would be necessary. The situation we're trying to support is an overflowSet inside of a column, and being able to adjust the number of icons shown after a column resize.

**Comment by KevinTCoughlin** [comment]
Following up off-line to see if a proposed solution unblocks Flow: https://github.com/OfficeDev/office-ui-fabric-react/compare/master...KevinTCoughlin:keco/on-column-resize-cb.

If so will raise PR.

**Comment by KevinTCoughlin** [comment]
I spoke with @dliu120 offline. The above proposed change _should_ work for the Flows scenario. There is an initial concern regarding how often the `onColumnResize` callbacks are invoked on resize. `_adjustColumns` is invoked every `16ms` as defined in: https://github.com/OfficeDev/office-ui-fabric-react/blob/6505775ab433ec7e1fca27621be96dd6c026796d/packages/office-ui-fabric-react/src/components/List/List.tsx#L156

However, I'm wondering if OUIFR needs to make that delay configurable OR if the consumers of this API can debounce the `onColumnResize` callback themselves.

@dliu120 can you verify that perf is an issue. If so I'd be interested to know if you're able to debounce the callbacks to address the perf issue. If not perhaps we'll need to explore making it configurable within the library.

**Related:** #6567

**Comment by micahgodbolt** [comment]
I was just about to say "this sounds familiar". Yes, I think being able to tweak the delay to balance performance.
