### ISSUE TITLE
MessageBar in dark theme isn't accessible

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#6414]
Many of the 'isInverted' colors are still way too light to work with white text. Also text might be white, but the links are still dark. It's hard to find a color that supports both.

![image](https://user-images.githubusercontent.com/1434956/45732739-8e311200-bb92-11e8-8851-b72c729c1f2a.png)
 

https://codepen.io/micahgodbolt/pen/bxQPWZ?editors=1010

**Comment by micahgodbolt** [comment]
@phkuo is there an expected way to create a dark themed message bar? Is the text not supposed to be white or something?

**Comment by phkuo** [comment]
@micahgodbolt The background colors are partially transparent and are meant to go on a dark background in inverted themes.

**Comment by phkuo** [comment]
No, the text is supposed to be warningText, which is either #333 or #fff, depending on isInverted.
See here: https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/styling/src/interfaces/ISemanticTextColors.ts#L63

The background colors are all partially transparent, you need to set the body's background to bodyBackground.
![image](https://user-images.githubusercontent.com/20691641/45773623-95423980-bbff-11e8-885c-3aa74d7624ac.png)

**Comment by micahgodbolt** [comment]
Oh I gotcha! Thanks.

**Comment by micahgodbolt** [comment]
Way better, though the links are still pretty hard to read. Obivously i could change link color in the theme. Is that what I'd need to do?

**Comment by phkuo** [comment]
Yes, right now we have links matching themePrimary. We may need a new slot for links on top of these message bar backgrounds though...
Also the designers have only looked at black and white backgrounds, they haven't really considered non-grayscale backgrounds, so having a slightly yellow or slightly red background might not work out well.

**Comment by micahgodbolt** [comment]
looks like links are intentionally set to themeDark. We could switch that to something else if isInverted is selected

**Comment by phkuo** [comment]
links on bodyBackground should be themePrimary in normal AND inverted
we probably chose themeDark because the background is a bit lighter, which would work well in light themes but worse in dark, but in any case it should be fine for now

**Comment by micahgodbolt** [comment]
Okay, I'll update the pen and call it good.
