### ISSUE TITLE
Styling the Panel component

### ISSUE THREAD

**Issue by hohenp** [OfficeDev/office-ui-fabric-react#6427]
How do you recommend to style the React Panel component.
I need to apply styles to the header, content and footer divs within the contentInner div
As I am using css modules I cannot easy apply styles to the static class names ms-Panel-Header, ms-Panel-Content and ms-Panel-footer.

Is there a way to overwrite the Header_hash, Content_hash, footer_hash classes?
Any other suggestions?

Thanks
Pascal

**Comment by micahgodbolt** [comment]
You can target specific areas of the panel via the styles prop like this:

https://codepen.io/micahgodbolt/pen/RYvzpg

Check out the panel's IPanelStyles interface for other areas.

**Comment by KevinTCoughlin** [comment]
To piggyback, additional resources related to styling can be found in our wiki:

- https://github.com/OfficeDev/office-ui-fabric-react/wiki/mergeStyles
- https://github.com/OfficeDev/office-ui-fabric-react/wiki/Component-Styling

Always open to improvements to our docs, so please share if you have any 😃.
