### ISSUE TITLE
TextField loses focus when dynamically switching to multiline

### ISSUE THREAD

**Issue by thejurassic** [OfficeDev/office-ui-fabric-react#6437]
### Please provide a reproduction of the bug in a codepen:
 https://codepen.io/thejurassic/pen/ZMPEBZ

### Bug Report 
 
 
- __Package version(s)__: ^6.43.0
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yea but not sure if I can fix it.. willing to try though.
 
Requested priority: High
 
Products/sites affected: Internal corporate applications
 
#### Describe the issue:
 
Switching a TextField component to multiline dynamically causes the components input to lose focus.
Must be becuase the textfield is switched between a <input> and <textarea> and so the focus was previously on the input, then the switch is made, but focus is not brought to the <textarea>
 
#### Expected behavior:
 
If the TextField is switched to multiline while the input was in focus, then the input should remain in focus. In the provided code-pen you can see if you type in the textfield and then the component is switched to multi-line while typing (in the code-pens case by typing a semi-colon) then the input loses focus and the user has to re-focus the input to continue typing.

**Comment by micahgodbolt** [comment]
so, if the component receives new props, and the props change it to/from multiline, if the component has focus, reset focus after component has been re-rendered?

**Comment by thejurassic** [comment]
Yea exactly.   Re-add the focus back to the component if it had focus before the re-render.

**Comment by micahgodbolt** [comment]
This fix isn't super high priority for us (as you can simulate it by changing the prop and then calling the focus method again). So if you're interested in trying to tackle it, I'd be happy to review it.

**Comment by ecraig12345** [comment]
I just joined the team and was assigned to look over all the open TextField bugs. Since this one is pretty simple, I made PR #7058 with a fix.
