### ISSUE TITLE
SearchBox does not pass props to the input element

### ISSUE THREAD

**Issue by hoovercj** [OfficeDev/office-ui-fabric-react#6440]
### Bug Report 
 
- __Package version(s)__: All
- __Browser and OS versions__: All
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: High
 
Products/sites affected: n-a
 
#### Describe the issue:
 
The `SearchBox` component accepts properties such as `autoComplete`, `maxLength`, `spellCheck`, `autoCorrect`, etc. but does not pass them to the `Input` component. To set these properties, we have to get a ref to the `SearchBox` element and find the child input element and set the properties manually.

I propose two different methods for fixing this:
* Add an `inputProps` property to `ISearchBoxProps` to explicitly pass down input properties to the `Input` component
* Use [getNativeProps](https://github.com/OfficeDev/office-ui-fabric-react/blob/5d0930647e631482b6016e0017aae0b5167b9f13/packages/office-ui-fabric-react/src/components/TextField/TextField.tsx#L407) similar to how `TextFIeld` uses it to extract the native input props and pass them to the `Input` component

**Comment by hoovercj** [comment]
Related: #5321

**Comment by micahgodbolt** [comment]
Seeing as ISearchBoxProps is InputHTMLAttributes, we should probably do getNativeProps.

**Comment by micahgodbolt** [comment]
@hoovercj if you're interested in doing this, I'm happy to take a look a the PR.

**Comment by micahgodbolt** [comment]
Also, getNativeProps approach requires no interface change. so thumbs up to that.

**Comment by hoovercj** [comment]
Thanks for the reply. My team is currently on version 5.52.0 so I may also need this on the latest 5.x branch. Is there any special process for that? Or just submit a PR to the 5.0 branch?

I don't know if I can get time to move us to 6.x just for this fix :-)

**Comment by micahgodbolt** [comment]
Anything we add to 5.x needs to be added to 6.x first. We don't want to create more friction for people trying to upgrade. 

If you can get it into 6.0 I can give you a hand backporting it.

**Comment by hoovercj** [comment]
For sure, sorry I wasn't clear. I'm just being optimistic and hoping it is a small fix that I could submit simultaneously to both branches. But if the backporting process is more complicated than opening a new PR, I'll wait and just focus on getting into 6 first

**Comment by micahgodbolt** [comment]
grabbing props, filtering them out via getNativeProps and passing them in shouldn't be too much work. And once done, the 5.x version isn't that much different. Is there a possibility of your team getting to the most recent version of 5.x?

**Comment by KevinTCoughlin** [comment]
@hoovercj once we merge #6477 into `master` would you want to cherry-pick the change into `5.0` branch?
