### ISSUE TITLE
DetailsList: clicking on disabled columns triggers onColumnHeaderClick 

### ISSUE THREAD

**Issue by fildahui** [OfficeDev/office-ui-fabric-react#6445]
### Please provide a reproduction of the bug in a codepen:

https://jjoz66k1ly.codesandbox.io/ 

### Bug Report 
 
 
- __Package version(s)__: 6.72.0 
- __Browser and OS versions__: Chrome 69 / IE 11 / Edge 42 / FF 60 on Windows 10
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No
 
Requested priority: (Blocking, High, Normal, Low) Normal
 
Products/sites affected: (if applicable)
 
#### Describe the issue:
 

When defining column objects we can set the columnActionsMode property to one of:
- ColumnActionsMode.disabled
- ColumnActionsMode.clickable
- ColumnActionsMode.hasDropdown

These values are defined as (in DetailsList.types.ts):
- **disabled**: "Renders the column header as disabled"
- **clickable**: "Renders the column header is clickable"
- **hasDropdown**: "Renders the column header as clickable and displays the dropdown cheveron"

When a column is set to be clickable (or hasDropdown) the onColumnHeaderClick function is executed upon column click.

The onColumnHeaderClick function, however, is executed also when clicking on disabled columns.

#### Actual behavior:
 

onColumnHeaderClick function is executed when clicking on disabled columns.

#### Expected behavior:
 

onColumnHeaderClick function **should not** be executed when clicking on disabled columns.

**Comment by Vitalius1** [comment]
This should be a quick fix: In [this handler](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/DetailsList/DetailsColumn.base.tsx#L215-L223) we need to make a check for the type of `ColumnActionMode`
