### ISSUE TITLE
Dropdown not showing tooltip on selected option

### ISSUE THREAD

**Issue by acamargob** [OfficeDev/office-ui-fabric-react#6449]
### Please provide a reproduction of the bug in a codepen:
 

https://codepen.io/anon/pen/ZMPwjx
### Bug Report 
 
 
- __Package version(s)__: 6.61
- __Browser and OS versions__: NA
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal
 
Products/sites affected: outlook.com
 
#### Describe the issue:
 
[An earlier bug](https://github.com/OfficeDev/office-ui-fabric-react/issues/5482) that's been fixed added a tooltip for options in the dropdown. 
The dropdown is not showing the same tooltip for the selected option.

![image](https://user-images.githubusercontent.com/3342902/45905552-9ca34780-bda5-11e8-844d-d001e505062b.png)
 
#### Actual behavior:
 
Tooltips are shown in the drop down, but not in actual field (selected option up top)
![image](https://user-images.githubusercontent.com/3342902/45905628-daa06b80-bda5-11e8-8d4e-e31d7cad7fd0.png)
 
#### Expected behavior:

Tooltip should also show on hover for the selected option in both collapsed and expanded states.

**Comment by KevinTCoughlin** [comment]
We likely just need to add a `title` to the selected option element which I believe is a `<div>` or `<span>` currently.

**Comment by micahgodbolt** [comment]
@acamargob if you're interested in doing this work, I'd be happy to help give you some scope on how it should be done, and then review your PR.

The gist is that we shouldn't be using the displayText as the title for every item anyway. We should only use displayText when the text is truncated, and then use our Tooltip to render the text. Fortunately out Tooltip can already render only if the parent is truncated.

**Comment by acamargob** [comment]
I am interested. I can probably get it next week.

**Comment by micahgodbolt** [comment]
it appears that dropdowns now pull title values from text OR title (title preferred). I'm glad title value is now working, but not sure if long term we'd want title automatically set to the text value. We're doing some significant updates to dropdown in #6030, we'll take a look at normalizing this behavior there.
