### ISSUE TITLE
Office Fabric Webiste not loading

### ISSUE THREAD

**Issue by iswanj** [OfficeDev/office-ui-fabric-react#6453]
visit: https://developer.microsoft.com/en-us/fabric#/components

**Expected:** Should show fabric component list
**Actual:** Broken page

![screenshot_2018-09-22_12-34-05](https://user-images.githubusercontent.com/7093947/45914528-da66a580-be63-11e8-92e1-af7f774e83c3.png)

**Comment by vadistic** [comment]
Adding mine stack trace just in case.
`Chrome latest & Win 64 Home` (and my mobile too)
```
Uncaught TypeError: i.createContext is not a function
    at Object.<anonymous> (versionTemplate.txt:1)
    at i (bootstrap:54)
    at Object.<anonymous> (ContextualMenuItem.tsx:18)
    at i (bootstrap:54)
    at Object.<anonymous> (BaseComponent.ts:129)
    at i (bootstrap:54)
    at Object.<anonymous> (versionTemplate.txt:1)
    at i (bootstrap:54)
    at Object.<anonymous> (root.tsx:146)
    at i (bootstrap:54)
```

**Comment by SebaBoler** [comment]
Chrome, Safari, and Firefox = this same result. Good Github working :)

**Comment by frevds** [comment]
Thanks for posting the issue, it's like that since Friday, some new React issue. I wonder how this gets by unnoticed at deployment, given it seems to be the only documentation site around. You should maybe adjust the title to draw more attention. 

Fortunately at least somebody made an alternative listing of the **icons** page at https://developer.microsoft.com/en-us/fabric#/styles/icons - FYI: https://codepen.io/MistaTwist/pen/BoNLEG (not affiliated).

**Comment by vbarche** [comment]
I am trying to read documentation about Commandbar components. 
Looks **like the documentation website not working** (link: https://developer.microsoft.com/en-us/fabric#/components/commandbar)issue is not resolved. 

**can someone post the update about this issue.?**

![officefabricuidocumentationwebsiteloadingissue](https://user-images.githubusercontent.com/18709734/45938582-198a1900-bf80-11e8-9216-a7ae656c8ddc.JPG)

**Comment by killedbymemory** [comment]
For the time being you can always read the raw documentation while waiting for official fix. For example for `Checkbox` component, the raw documentation can be accessed here: https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/office-ui-fabric-react/src/components/Checkbox

There is a `doc` directory underneath for overview, do, and donts parts.

Cheers.

**Comment by ganeshrvel** [comment]
They have already fixed the issue.

**Comment by iswanj** [comment]
The Office Fabric website is now working and closing this issue. Thanks to everyone.

**Comment by frevds** [comment]
No it's still not, at least not for me, same error (checked in Edge and Firefox on Win10 after clearing the cache). Am I the only one seeing this now? 

![image](https://user-images.githubusercontent.com/5341447/45967202-8a3b3f00-c02d-11e8-93c6-8f3faabf1954.png)

**Comment by frevds** [comment]
@vadistic You're right, must have been caching. It's on now :)

> Big thanks for bringing it back 👍

Thank goes to the guys who repaired it ;)

**Comment by kempjeng** [comment]
This is still present for me, can any one else confirm?  Multiple browsers, and operating systems tested.  Cleared caches.

**Comment by frevds** [comment]
@kempjeng  Also works for me, already since 10 days. Strange, are you within some network with a caching proxy? Try from another location.

**Comment by kempjeng** [comment]
apologies the issue was my fault.

I had setup a hosts file `static2.sharepointonline.com` redirect to 127.0.0.1.
This was setup when I was trying to use different fonts for licensing reasons.

Thank you all for your help.
