### ISSUE TITLE
copyArray method in Office UI Fabric Dropdown example

### ISSUE THREAD

**Issue by licypal** [OfficeDev/office-ui-fabric-react#6463]
I was going through the documentation on Office UI Fabric Dropdown (https://developer.microsoft.com/en-us/fabric#/components/dropdown). It includes an example as follows:

```
public onChangeMultiSelect = (item: IDropdownOption): void => {
    const updatedSelectedItem = this.state.selectedItems ? this.copyArray(this.state.selectedItems) : [];
    if (item.selected) {
      // add the option if it's checked
      updatedSelectedItem.push(item.key);
    } else {
      // remove the option if it's unchecked
      const currIndex = updatedSelectedItem.indexOf(item.key);
      if (currIndex > -1) {
        updatedSelectedItem.splice(currIndex, 1);
      }
    }
    this.setState({
      selectedItems: updatedSelectedItem
    });
  };

  public copyArray = (array: any[]): any[] => {
    const newArray: any[] = [];
    for (let i = 0; i < array.length; i++) {
      newArray[i] = array[i];
    }
    return newArray;
  };
```

I am not able to understand what is the requirement of copyArray() as its return value is same as this.state.selectedItems. I tried updating the code to 

```const updatedSelectedItem = this.state.selectedItems ? this.state.selectedItems : [];```

 and it is not working as expected. Could someone please let me know? Thanks!

**Comment by micahgodbolt** [comment]
That copyArray allows you to pass in an array and return a new one, that is to say, an array with the same values, but not the SAME array.

`a=[1,2,3]`

`b = copyArray(a) // b is [1,2,3]`

`c = a`

`a === b returns false`
`c === a returns true`

**Comment by micahgodbolt** [comment]
updatedSelectedItem is checking if state has selecteditems (plural). If true return a copy of the selected items (not the actual state, just a copy of it). If state doesn't have any selected items do the rest of the logic below.

**Comment by licypal** [comment]
Thank you @micahgodbolt
