### ISSUE TITLE
TextField: Fix positioning of icon within the field

### ISSUE THREAD

**Issue by mibes** [OfficeDev/office-ui-fabric-react#647]
### Bug Report

- __Package version(s)__: 0.80
- __Browser and OS versions__: Safari (10.0.1), Firefox (50.0.1), Chrome (54.0.2840.98) on OSX

#### Describe the issue:

When a long label is used on the DatePicker the calendar icon is not properly aligned vertically. Long meaning a label that wraps within the div.

#### Actual behavior:

Calendar icon is positioned north of the DatePicker box. 

#### Expected behavior:

Calendar icon should be aligned within the DatePicker box.

### If applicable, please provide a codepen repro:

See codepen: http://codepen.io/mibes/pen/aBEQVz

**Comment by mikewheaton** [comment]
The icon is absolutely positioned with a `top` position, which only works when the label text doesn't wrap to multiple lines. A quick fix would be to use `bottom` instead, as the field itself is always the same height and at the bottom.

**Comment by mibes** [comment]
Looks good. 

For people who want to have a quick intermediate fix. Add this to your CSS:

```
.ms-DatePicker-event--with-label {
  top: auto;
  bottom: 6px !important;
}
```

**Comment by mikewheaton** [comment]
Waiting for an answer to #650 before fixing. If TextFields should support an icon on the right side like this then I will build it into the TextField itself, otherwise we should remove the icon from TextField and create/position the icon only within DatePicker.

**Comment by mikewheaton** [comment]
Confirmed: We want to support an (optional) icon in every TextField. Ready to proceed here with a fix.

**Comment by mikewheaton** [comment]
Unassigning myself for now. There's an audit of all the components being done and new designs are coming soon.
