### ISSUE TITLE
Documentation not clear

### ISSUE THREAD

**Issue by masters3d** [OfficeDev/office-ui-fabric-react#6472]
### Please provide a reproduction of the bug in a codepen:
 

![image](https://user-images.githubusercontent.com/6539412/46048331-a26a9700-c0dd-11e8-83b5-012e6eea177a.png)

### Bug Report 
 
 
https://github.com/OfficeDev/office-ui-fabric-react/wiki/TypeScript-Guidelines#open-curly-braces-always-go-on-the-same-line-as-the-code-that-requires-the-brace
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Low
 
 
#### Describe the issue:
 
Not sure what is bad or good. Where do I edit wikies?
 
#### Actual behavior:
 
no clear. 
#### Expected behavior:
 
clear

**Comment by KevinTCoughlin** [comment]
Thanks for reporting this @masters3d. I wasn't sure if you had edit access to the wiki so I went ahead and made the quick fix https://github.com/OfficeDev/office-ui-fabric-react/wiki/TypeScript-Guidelines/#bad-1.

We appreciate you bringing this to our attention 👍.

If you have access to the wiki you'll see an "Edit" button like this:

![image](https://user-images.githubusercontent.com/706967/46109683-31d38100-c196-11e8-808c-045aa735d294.png)

We're in the process of making our wiki even more collaborative. Stay tuned! Closing the issue in the meantime as the typo has been fixed.
