### ISSUE TITLE
What is the correct way to use it calendarProps ?

### ISSUE THREAD

**Issue by alexgwolff** [OfficeDev/office-ui-fabric-react#6483]
```
<DatePicker label={this.props.label}
                placeholder={"Selecione uma data"}
                value={new Date(date)}
                showMonthPickerAsOverlay={true}
                showWeekNumbers={false}
                onSelectDate={this.onSelectDate}
                calendarProps={{ isDayPickerVisible: false, isMonthPickerVisible: true }}
                formatDate={date => new Intl.DateTimeFormat('pt-BR').format(date)} 
                strings={DayPickerStrings} />)
```

is not rendering as expected

**Comment by KevinTCoughlin** [comment]
@alexgwolff I'm rendering your `calendarProps` in this Codepen: https://codepen.io/kevintcoughlin/pen/vzwVyz?editors=1010

Which seems to render correctly (only the month picker is shown):

![image](https://user-images.githubusercontent.com/706967/46116777-85ec5e80-c1b2-11e8-8efd-cec290286035.png)

However when I use `showMonthPickerAsOverlay={true}` the day picker seems to be rendered. Perhaps that prop is taking precedence. That might be a bug.

Mind sharing your desired render output? Do you only want the month picker visible?

**Comment by alexgwolff** [comment]
Yes, only month.
I try removed showMonthPickerAsOverlay={true} and now this is working.
it's a bug?
For now I'll leave this property out


Thanks, bro
