### ISSUE TITLE
Inline style prevents override of css in ResizeGroup and thus CommandBar

### ISSUE THREAD

**Issue by brandonthomas** [OfficeDev/office-ui-fabric-react#6487]
### Please provide a reproduction of the bug in a codepen:

https://codepen.io/anon/pen/aRovXj

### Bug Report 
- __Package version(s)__: 6.73.0
- __Browser and OS versions__: all
 
#### Priorities and help requested:
Are you willing to submit a PR to fix? Yes if necessary but I have a lot of other work dependent on this so ideally not.
 
Requested priority: Blocking
 
Products/sites affected: MAC
 
#### Describe the issue:
Inline styles are overriding everything set on the root of CommandBar due to the changes made in ResizeGroup. Specifically I cannot override the display or position of the root on either control. This is a big deal as the design I need to achieve has sticky properties.

Caused by: https://github.com/OfficeDev/office-ui-fabric-react/pull/6389
 
#### Actual behavior:
 Position and display properties are essentially hard coded on ResizeGroup and any CommandBar (since it relies on ResizeGroup.
 
#### Expected behavior:
I'd expect to be able to override what I need to in a non-hacky way. I'm basically forced to get a ref right now and override the properties on each render. Not good.

**Comment by brandonthomas** [comment]
Problem code: https://github.com/OfficeDev/office-ui-fabric-react/blob/418fe4c38c2e18719446e1c53ebfdc544aac1d53/packages/office-ui-fabric-react/src/components/ResizeGroup/ResizeGroup.base.tsx#L360

**Comment by KevinTCoughlin** [comment]
Added @micahgodbolt when he's back to follow-up

**Comment by micahgodbolt** [comment]
Ok, so it's the effect of moving the styles inline (and increasing specificity) that is the issue.  Sorry about the delay. Let's find a solution for this quickly.

**Comment by micahgodbolt** [comment]
What about if we mixed our styles into the divProps allowing the user to provide their own 'styles' if necessary.

**Comment by micahgodbolt** [comment]
@christiango How do you feel about moving the position relative into the measured area? This way, if the ResizeGroup is actually fixed/sticky etc the measured div will be inside a relative parent the same width as the onRenderData


![image](https://user-images.githubusercontent.com/1434956/46365707-279a0280-c62e-11e8-9f95-df9c78bf2494.png)

**Comment by christiango** [comment]
So the initial measure happens inside the root div and not a measured div as a performance optimization, so we need to make sure the initial measure is still correct. 

Is there any other regression risk?

**Comment by micahgodbolt** [comment]
The only reason for the position relative is to make sure that the hiddenDivStyles (which is absolute) doesn't have a static displayed parent. i.e. if the parent were display static the hiddenDiv would be rendered inside the resizeGroup's parent container, which might be a different width.

So as long as that initial measure doesn't require a non static parent, it should be fine. 

The only possible problem is that durring measuring there is a 2nd non absolute div inside the resizeGroup root. Same number of siblings (2), but now the 2nd is relative instead of absolute.

**Comment by brandonthomas** [comment]
for now my work around is a div wrapper but that's not really ideal. I tend to shy away from DOM when it shouldn't be necessary. Have you guys figured out if there's a way we can fix this while keeping the bundle size down?

**Comment by micahgodbolt** [comment]
Two options I see moving forward. Allow the display of the ResizeGroup to be configurable, or move the display: relative onto the measured div only and test for regressions. 

I'm more included to do the latter, and move the display relative. Would be nice to not have to think/worry about the display property at the command bar level. 

@christiango if I pushed out a beta release with that change, would it be possible to quickly test that branch in the ribbon?

**Comment by christiango** [comment]
Yup, just let me know the package version and I can have someone on our team take a look

**Comment by brandonthomas** [comment]
While we're in here can we also look at why we have duplicate classNames (see image below). I pass a className prop to CommandBar and it shows on the focus zone and on the main div. This seems like another bug?

![image](https://user-images.githubusercontent.com/7529639/47177013-0d1d8580-d2cc-11e8-9ced-82a498d66674.png)

**Comment by brandonthomas** [comment]
This looks to be the culprit.
https://github.com/OfficeDev/office-ui-fabric-react/blob/4b2e44d41e1cba8d4ca5e7542d3cc66f961e0b43/packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.base.tsx#L67
`this._classNames = getClassNames(styles!, { theme: theme!, className });`

**Comment by brandonthomas** [comment]
Fine if we fix the duplicate class name issue as another bug.

**Comment by brandonthomas** [comment]
File the following issue for the duplicate classNames:
https://github.com/OfficeDev/office-ui-fabric-react/issues/6828
