### ISSUE TITLE
List: scroll to row

### ISSUE THREAD

**Issue by pablonete** [OfficeDev/office-ui-fabric-react#649]
### Feature request

We need some nice way to scroll List and DetailList to the selected item. Something like scrollToIndex prop in react-virtualized: https://bvaughn.github.io/connect-tech-2016/#/26/3

We are working around this by using refs and DOM scrollToView. Is there a better approach that we may be missing? Or is there something in the backlog to add this functionality?

**Comment by dzearing** [comment]
This has been implemented before but we haven't needed it and I may have removed this code. I'll look into adding it back.

**Comment by cschleiden** [comment]
We have a similar requirement. Due to virtualization, refs and `scrollIntoView` is not an alternative, unfortunately. 

Do we still have that old code anywhere? Could help to bring it back.

**Comment by pablonete** [comment]
For reference, this feature existed as a method instead of a prop, and was removed on this commit: https://github.com/OfficeDev/office-ui-fabric-react/commit/b3a92fef2007e2a85de3608873ed7a093dee3f66
