### ISSUE TITLE
Cannot scroll right to view rightmost columns of the ms-list using keyboard when zoomed 200% on Edge.

### ISSUE THREAD

**Issue by raveenone** [OfficeDev/office-ui-fabric-react#6491]
### Bug Report 
 
 
- __Browser and OS versions__: Microsoft Edge 41.16299.665.0
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: https://dev.azure.com
 
#### Describe the issue:
 
1. Set screen resolution to 1024x768.
2. Navigate using the Edge browser to any page which uses the ms-list component. The "All" Test Plans page in Azure Dev Ops for example, (https://dev.azure.com/mseng/VSOnline/_testManagement/mine)
    or "Assigned to me" work items page (https://dev.azure.com/mseng/VSOnline/_workitems/assignedtome/).
3. Zoom in 200%.
4. Try and view the rightmost columns of the details list using only the keyboard.
5. As you can see the keyboard scroll does not go to the rightmost column.
 
#### Actual behavior:
 
Cannot scroll right to view rightmost columns of the ms-list using keyboard when following the steps described above.
 
#### Expected behavior:

User should be able to view all columns of the details list using only keyboard navigation at all zoom levels.

**Comment by Vitalius1** [comment]
@raveenone does this manifest only in Edge? Did you try on all other major browsers?
