### ISSUE TITLE
Edge browser panel sizing issue

### ISSUE THREAD

**Issue by acdickin** [OfficeDev/office-ui-fabric-react#6498]
### Bug Report 
 
 
- __Package version(s)__: "^6.74.0"
- __Browser and OS versions__: (fill this out if relevant)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) Yes
 
Requested priority: (Blocking, High, Normal, Low)  Normal
 
Products/sites affected: (if applicable)  Modern Experiences
 
#### Describe the issue:
 Panel is not sizing properly on Edge browser. 

 
#### Actual behavior:
 
![panel-edge](https://user-images.githubusercontent.com/6342062/46178588-5306a100-c26c-11e8-8682-138a3aadc2e6.PNG)
 
#### Expected behavior:
 Should have a height of 100% instead of 200px
![panel-chrome](https://user-images.githubusercontent.com/6342062/46178587-5306a100-c26c-11e8-9a36-81d4d7d7d969.PNG)
 
#### My Fix:

.ms-Panel-contentInner{
  height: calc(-44px + 100%);
}
.ms-Panel-content {
  height: 100%;
}

**Comment by KevinTCoughlin** [comment]
@acdickin thanks for the bug report. Would you be able to put together a quick Codepen showing this behavior so that we can debug? You can fork this one as a template: https://codepen.io/caradong/pen/BPMNra

**Comment by micahgodbolt** [comment]
Edge seems to handle scrolling and footer content alright. Do you have a specific usecase that isn't working?

![image](https://user-images.githubusercontent.com/1434956/50525658-c26d7600-0a91-11e9-9dbf-2688005ff981.png)
