### ISSUE TITLE
TextField: Fix positioning of icon

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#650]
The TextField has an option to specify an `iconClassName`, which looks like this with a standard icon:

![image](https://cloud.githubusercontent.com/assets/1382445/20863277/6b1e02bc-b97a-11e6-9dd7-ae48baf6ca71.png)

That doesn't look terribly useful. In the [DatePicker](http://dev.office.com/fabric#/components/datepicker) we've added additional styles to make the icon look like this:

![image](https://cloud.githubusercontent.com/assets/1382445/20863264/218377e0-b97a-11e6-960c-a534c11d7f5d.png)

Should that be the default for all TextFields? Or is the DatePicker a special case and typical TextFields should not have an icon option at all?

**Comment by dzearing** [comment]
I think `TextFields` should support a standard icon and also a clear button and we should remove `SearchBox`.

**Comment by mikewheaton** [comment]
We'll have to discuss more with the designers. It seems like there might be a case for a searchable TextField being different than a SearchBox, if the SearchBox has a distinct appearance and entirely different use cases.

Regardless of what happens with SearchBox, we should fix TextField so that it positions the icon similar to DatePicker. I'm not so sure on the clear button because it seems like it should also be on the right side – is it a case of choosing one or the other?

**Comment by mikewheaton** [comment]
After discussing with design, the outcome is to:

- Leave the SearchBox component as-is for now. There will be updated designs coming next month.
 - Support an (optional) icon in any TextField, which will be positioned on the right side. This can be used to create a searchable TextField, which is just a typical TextField with a search icon and no differences in behavior.
 - Not add a 'clear' icon to TextField.

**Comment by dzearing** [comment]
I think we can track this with one bug #647
