### ISSUE TITLE
neutralSecondaryAlt color needs to be replaced across the repo

### ISSUE THREAD

**Issue by Vitalius1** [OfficeDev/office-ui-fabric-react#6500]
### Bug Report 

- __Package version(s)__: all
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes as long as we have replacement colors from designers
 
Requested priority: (High) 

 
#### Describe the issue:
 
neutralSecondaryAlt was deprecated several months ago, we should remove any instances of it.
First step of removing it was in #6499 as it had a real impact on the themed SPList.
Most likely will be needed designers to provide a replacement color for where it's used.

**Comment by KevinTCoughlin** [comment]
Linking original issue: #5194

**Comment by Vitalius1** [comment]
@betrue-final-final 
It seems these color is still used in:

- DocumentCard
- Pivot
- GroupHeader

What we should replace it with? Is it safe to just go with neutralSeconadry?

**Comment by betrue-final-final** [comment]
Here's what we discussed:
DocumentCard - neutralSecondary for activities
Pivot - neutralSecondary...use the focus semantic slot.
GroupHeader - neutralSecondary

**Comment by Vitalius1** [comment]
@dzearing there is already a PR in by Natalie...
