### ISSUE TITLE
Having border as a prop for SwatchColorPicker

### ISSUE THREAD

**Issue by RupamSarkar** [OfficeDev/office-ui-fabric-react#6505]
**Describe the feature that you would like added**
We have to implement a swatch color picker :  

In light theme which looks like this -
![light](https://user-images.githubusercontent.com/17047049/46199755-76ddeb80-c32d-11e8-9af4-817c984e9743.png)

and in dark theme -
![colorpicker](https://user-images.githubusercontent.com/17047049/46193845-26f72880-c31d-11e8-8441-6989b149aa97.png)

As we can see , there are borders for each of the 4 color cells in first row . I think it would be better if we have a prop to control the border(color,width etc) . As , In light theme if the 1st color is No Color(transparent) then there is no way to distinguish the that color and in Dark theme it is hard to distinguish all the 4 colors in first row . Currently border only shows if the color isWhite . 

**What component or utility would this be added to**
SwatchColorPicker

**Have you discussed this feature with our team, and if so, who**
Discussed this with @KevinTCoughlin

**Comment by RupamSarkar** [comment]
@shagra-ms for visibility

**Comment by KevinTCoughlin** [comment]
To add some additional context:

We currently check whether or not to add the border based on `_isWhiteCell`:

https://github.com/OfficeDev/office-ui-fabric-react/blob/92f15b7e3dffa730e7544e1407e885e5dd8b9b6b/packages/office-ui-fabric-react/src/components/SwatchColorPicker/ColorPickerGridCell.base.tsx#L104

That logic works with the assumption that the picker is present on a `#ffffff` background. But if the picker is rendered against a themed background, then non-white colors could blend and would require a border. So an improvement for developers might be to make the border and its properties configurable.

**Comment by RupamSarkar** [comment]
Hi , any update on this ? @KevinTCoughlin

**Comment by micahgodbolt** [comment]
@RupamSarkar this control now accepts a styles prop. This would allow you to add borders if you prefer. Not sure if we'd bake this in because if you had a blue background you'd want borders around any swatch close to blue, not black or white.

**Comment by RupamSarkar** [comment]
@micahgodbolt Can we add borders selectively to few cells using the styles prop ? As our color picker needs border only in the 1st row cells .

**Comment by micahgodbolt** [comment]
No, as of now the only indicator we have is 'isWhite'. You'd have to apply the same border to all swatches.

It's possible that you could add passing 'color' to IColorPickerGridCellStyleProps and this would let you make per color style differences.
