### ISSUE TITLE
FocusTrapZone: Enable home/end key to focus to first/last focusable item

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#6508]
**Describe the feature that you would like added**
Add an option to enable home/end key to focus on first/last focusable item inside FocusTrapZone.
When FocusTrapZone wrap elements in a linear vertical/horizontal order, it makes a lot sense to use home/end key to focus elements. It might not be straightforward when elements are not in line vertical/horizontal order so I guess this feature should be optional.

**What component or utility would this be added to**
FocusTrapZone

**Have you discussed this feature with our team, and if so, who**
No

**Comment by dzearing** [comment]
`FocusTrapZone` purpose is to trap focus, not to change tabbing behavior, whereas `FocusZone` change tabbing to directional, and it already supports home/end.

You're free to wrap content in a FocusZoine, if it makes sense.
