### ISSUE TITLE
Limit items in PeoplePicker (& Picker) 

### ISSUE THREAD

**Issue by biogenez** [OfficeDev/office-ui-fabric-react#652]
How can I limit max number of the added items in PeoplePicker (or Picker)?

**Comment by dzearing** [comment]
Needs guidance or possibly a feature add.

**Comment by dzearing** [comment]
@joschect friendly ping

**Comment by joschect** [comment]
@dzearing thanks, I'll get going on this.

**Comment by gitjain** [comment]
Solution has been merged so updating the status.
