### ISSUE TITLE
TagPicker: textbox shown wrong position

### ISSUE THREAD

**Issue by nguyentoantuit** [OfficeDev/office-ui-fabric-react#6520]
### Please provide a reproduction of the bug in a codepen:

 https://codepen.io/anon/pen/pxvxVO?editors=0110

### Bug Report 
 
 
- __Package version(s)__: office-ui-fabric-react@6.74.2
- __Browser and OS versions__: Chrome
 
#### Describe the issue:
 

Create a TagPicker with these options as suggestions
[
      { key: '1', name: 'Short item'},
      { key: '2', name: 'Verrrrrry long description to test width 1'},
      { key: '3', name: 'Verrrrrry long description to test width 2'},
      { key: '4', name: 'Verrrrrry long description to test width 3'}]

#### Actual behavior:
When we select all options in suggestion list, the textbox is shown in strange position.
![image](https://user-images.githubusercontent.com/6096518/46253663-c813e980-c4ab-11e8-8e85-4234bd2f65c1.png)
Addition, the selected items are not display well (see above image)
 
#### Expected behavior:
 The textbox should be displayed at the bottom of tagpicker control.

 #### Reason:
We group all selected items in a span element (selected-items-id__4)
![image](https://user-images.githubusercontent.com/6096518/46253689-846daf80-c4ac-11e8-804c-efcef85b9229.png)

**Comment by Vitalius1** [comment]
From the initial investigation and after confirming with the designer we believe indeed it has to be at the bottom.
@aneeshack4 this looks like a quick change by adding `align-self: flex-end` to the pickerInput class in:
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/pickers/BasePicker.scss#L21
