### ISSUE TITLE
Shimmer is absent in package 1.5.1

### ISSUE THREAD

**Issue by Krak86** [OfficeDev/office-ui-fabric-react#6523]
### Bug Report 
 
 
- __Package version(s)__: "@microsoft/sp-office-ui-fabric-core": "1.5.1" (npm)
- __Browser and OS versions__: windows 10
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (Normal) 
 
Products/sites affected: (spfx webpart in sharepoint online)
 
#### Describe the issue:
 
Shimmer component is absent in office fabric library using path 'office-ui-fabric-react/lib/Shimmer' as other components. I checked library itself and really didn't find this component there. Maybe it is removed from 1.5.1 version or renamed, but I couldn't find any similar name.
 
#### Actual behavior:
 
Shimmer component is absent in office fabric.
 
#### Expected behavior:
 
According to office fabric Shimmer component should be presented.

**Comment by Krak86** [comment]
I think **Shimmer** label could be added

**Comment by dzearing** [comment]
I'm not sure I understand this.

https://unpkg.com/@microsoft/sp-office-ui-fabric-core@1.6.0/package.json

This does not depend on fabric-react.

Please log fabric core issues here: https://github.com/officedev/office-ui-fabric-core

Thank yo!

**Comment by Krak86** [comment]
Added issue here https://github.com/OfficeDev/office-ui-fabric-core/issues/1146
