### ISSUE TITLE
Always use fonts defined in the theme for components (remove Fabric component dependency)

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#6528]
Expected:

render any Fabric component, renders the correct fonts.

Resulted:

times new roman

**Comment by aneeshack4** [comment]
#6632 only does this for the Slider control - not for all Fabric controls @dzearing can we please reopen this? I tried to do it for all the controls at first by intentionally removing the Fabric component wrapper from FabricDecorator.tsx and breaking a bunch of screener scenarios but that proved too much to do all at once so I did Slider only first to get feedback. Now that it seems like I got Slider correct I'll do all the others in 1 PR.
