### ISSUE TITLE
FacepileButton always uses getStyles(getTheme())

### ISSUE THREAD

**Issue by tabrumle** [OfficeDev/office-ui-fabric-react#6537]
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Facepile/FacepileButton.tsx
 

**Describe the feature that you would like added**

Change FacepileButton to allow for custom styling to be passed in instead of overriding it with a default style.

**What component or utility would this be added to**
FacepileButton

**Have you discussed this feature with our team, and if so, who**
No

**Additional context/screenshots**
You are unable to pass in a custom styles prop back to FacepileButton. It will always be overridden by styles={getStyles(getTheme())} being passed inline right after passing in {...this.props}. You can pass in styles inline through the style prop still, but there is no way to pass in IButtonStyles through styles without it being overridden.

**Comment by Vitalius1** [comment]
Investigated a little and seems like it needs some reorder of the props but also there are some specificity issues here: https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Facepile/Facepile.styles.ts#L27-L28 which also needs some rework.

@tabrumle Can you provide some scenario or a codepen repro of what you are trying to achieve?

**Comment by tabrumle** [comment]
<p data-height="265" data-theme-id="0" data-slug-hash="NvBvWx" data-default-tab="js,result" data-user="FabricReact" data-pen-title="Fabric React Starting Template" class="codepen">See the Pen <a href="https://codepen.io/FabricReact/pen/NvBvWx/">Fabric React Starting Template</a> by Microsoft UI Fabric (<a href="https://codepen.io/FabricReact">@FabricReact</a>) on <a href="https://codepen.io">CodePen</a>.</p>
<script async src="https://static.codepen.io/assets/embed/ei.js"></script>

**Comment by tabrumle** [comment]
<p data-height="265" data-theme-id="0" data-slug-hash="MPKarL" data-default-tab="js,result" data-user="tabrumle" data-pen-title="Fabric React Starting Template" class="codepen">See the Pen <a href="https://codepen.io/tabrumle/pen/MPKarL/">Fabric React Starting Template</a> by tabrumle (<a href="https://codepen.io/tabrumle">@tabrumle</a>) on <a href="https://codepen.io">CodePen</a>.</p>
<script async src="https://static.codepen.io/assets/embed/ei.js"></script>

**Comment by Vitalius1** [comment]
Thanks! This really helps with debugging the issue plus your initial investigation might set a good direction to look into.
