### ISSUE TITLE
Coachmark component is broken

### ISSUE THREAD

**Issue by cliffkoh** [OfficeDev/office-ui-fabric-react#6538]
### Please provide a reproduction of the bug in a codepen:
 
https://fabricweb.z5.web.core.windows.net/oufr/6.75.0/#/examples/coachmark

### Bug Report 
 
 
- __Package version(s)__: 6.75.0
- __Browser and OS versions__: Edge/Win 10
  
#### Describe the issue:
 
Coachmark does not show in the example.
 
#### Expected behavior:
 
Coachmark example working (it does in CommandBar)

**Comment by micahgodbolt** [comment]
Can you give some more repro steps? The coachmark is rendering in both Edge and FF. Are you on edge insider? 
![image](https://user-images.githubusercontent.com/1434956/46363674-86f51400-c628-11e8-9233-f80562b7e827.png)

**Comment by cliffkoh** [comment]
I can repro on Chrome too. Katherine reproed last week as well.

**Comment by cliffkoh** [comment]
Nevermind figured out what must be wrong - there is a really long delay before it opens...

**Comment by dzearing** [comment]
There is a 2 second delay.
