### ISSUE TITLE
No space between item count and title on PivotItem

### ISSUE THREAD

**Issue by cschleiden** [OfficeDev/office-ui-fabric-react#655]
### Bug Report

- __Package version(s)__: master

#### Describe the issue:

When using `itemCount` on PivotItems there is no space between pivot title and the count element, unless the `large`modifier is used.

#### Actual behavior:
Behavior without `large` modifier, no space between title and count:

`Links(1)`

![image](https://cloud.githubusercontent.com/assets/2201819/20902946/4e10f7ea-baee-11e6-9d23-07333fbc7df2.png)

#### Expected behavior:

`Links (1)`

Similar to the behavior with `large`:
![image](https://cloud.githubusercontent.com/assets/2201819/20902935/43a99bc2-baee-11e6-8866-40bdfb0ca0d5.png)

A 4px left-margin is added here: https://github.com/OfficeDev/office-ui-fabric-react/blob/78e462bc936350fee2806ee0e70d523e8deee9b5/packages/office-ui-fabric-react/src/components/Pivot/Pivot.scss#L134 

Should there be similar spacing (maybe at least some `&nbsp;`) for the normal mode?

**Comment by mikewheaton** [comment]
There should definitely be a space there, either using `margin` or by adding a space with `{' '}`.
