### ISSUE TITLE
Issue with loadTheme and fonts. loadTheme({fonts: { large: {fontFamily: "Lato"}...}}) doesn't seem to work

### ISSUE THREAD

**Issue by Promhize** [OfficeDev/office-ui-fabric-react#6550]
### Bug Report 
 
 
- __Package version(s)__: 
uifabric/styling - 5.31.0, 
microsoft/sp-office-ui-fabric-core - 1.4.1, 
office-ui-fabric-core - 9.6.1

- __Browser and OS versions__: Chrome
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) High
 
Products/sites affected: (if applicable) Sharepoint (Office 365)
 
#### Describe the issue:
 
Hi Guys, awesome work.

Using the loadTheme function to update colors work as expected but doesn't seem to work with fonts.
That is, using `loadTheme({fonts: { large: {fontFamily: "Lato", fontSize: "36px"}}})` for example doesn't update the `ms-font-l` class.
Maybe I'm missing something with this
 
#### Actual behavior:
 
Nothing happens
 
#### Expected behavior:
 
Font styling should be updated

**Comment by Vitalius1** [comment]
@dzearing @phkuo can you reply?

**Comment by phkuo** [comment]
If this is in CSS (as opposed to the CSS-in-JS stuff), it has to go through legacyLoadTheme() here:
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/styling/src/styles/theme.ts#L79
which currently is only doing colors.

**Comment by dzearing** [comment]
Hmm. @phkuo nobody should call that API.

The call to the legacy behavior is abstracted in `loadTheme` api, which is the current contract for loading the theme. (Abstracting legacy behaviors lets us remove it once it's no longer needed without breaking partners.)

Here is an example of using courier new for the fontFamily.

https://codepen.io/dzearing/pen/wYGbqV?editors=1010

I do see a couple of problems here that could be hurting your scenario:

1. There is a bug in DetailsList header which isn't picking up the font. I have a PR open to fix this. #6564

2. If you call loadTheme AFTER you render content, it isn't causing a re-render and thus isn't re-evaluating styles. We'll need to address this separately, but for now you can either load the theme first before you start rendering content (which is the performant thing to do anyway) or trigger a re-render manually.

3. Even with loadTheme, it will only affect Fabric components, and won't touch global CSS styles such as ms-font-l. I can certainly see how this would be pretty nice, but... messing with global rules have unexpected consequences, so we have avoided that so far. We can consider it, but as a better approach, we have a `Text` theme-aware component being ramped up to ship with Fabric, which can abstract rendering text in the right font. That way you're not tied to global class names and you get nice things like intellisense.
