### ISSUE TITLE
getGlobalClassNames can be more resilient to suboptimal code from consumers

### ISSUE THREAD

**Issue by cliffkoh** [OfficeDev/office-ui-fabric-react#6551]
### Please provide a reproduction of the bug in a codepen:

If a consuming app writes code like this:

![image](https://user-images.githubusercontent.com/1003246/46432608-81b8c780-c703-11e8-91b9-566b8dcc1a83.png)

This causes the memorization presently in `getGlobalClassNames` (https://github.com/OfficeDev/office-ui-fabric-react/blob/dc8006f130300a6dee7831e3e0166a4da8ff84a8/packages/styling/src/styles/getGlobalClassNames.ts#L17) to fail because on each render pass, the "`disableGlobalClassNames` method in the screenshot above is invoked to create a new theme object.

One improvement that can be made while preserving backwards compatibility is to memorize `theme.disableGlobalClassNames` in `getGlobalClassNames` instead of the entire `theme` object which will make it more resilient to such errors in the future.

(Fabric Tactical members - for more details, look for email titled "Memoization bug" in Fabric Tactical)
 

### Bug Report 
 
 
- __Package version(s)__: 6.76.0

 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Low
 
Products/sites affected: LPC

**Comment by Vitalius1** [comment]
@cliffkoh assigning you as you stated 'Yes' in the willing to submit a PR section 😄

**Comment by cliffkoh** [comment]
That is true, but it will take me a while though before I can context-switch to work on this :) I recommend leaving it unassigned - it is a simple change that any secondary shield can pick up.

**Comment by cliffkoh** [comment]
Side note: what contributes to the problem in the repro above is that Customizer itself seemingly is always generating a new object (and incurring the runtime cost of the spread) on every render pass - which makes memorizing `disableGlobalClassNames` from the very first post not a viable mitigation. 

![image](https://user-images.githubusercontent.com/1003246/46496557-37038200-c7cd-11e8-9f97-baee9122c013.png)

The way to successfully mitigate is to memorize the `theme` object generated in `disableGlobalClassNames ` instead.

**Comment by dzearing** [comment]
I'm looking at spinning up a codepen to try and repro. It's pretty tough to assess what the right thing to do is without that.

**Comment by dzearing** [comment]
https://codepen.io/dzearing/pen/VEjbMd
