### ISSUE TITLE
List: Make debounce for asyncResize configurable

### ISSUE THREAD

**Issue by dliu120** [OfficeDev/office-ui-fabric-react#6567]
**Describe the feature that you would like added**
For large lists such as the DetailsList, resizing the window can be quite slow. We would like a way to increase the debounce interval on the list.

**What component or utility would this be added to**
List / DetailsList

**Have you discussed this feature with our team, and if so, who**
No

**Additional context/screenshots**
![image](https://user-images.githubusercontent.com/2090090/46492767-67deb980-c7c3-11e8-9b88-e72bb8c3f855.png)

**Comment by Vitalius1** [comment]
@KevinTCoughlin @ThomasMichon  any input on this?

**Comment by KevinTCoughlin** [comment]
Exposing this as a prop on `IListProps` is easily achievable. And the `DetailsList` component already exposes `listProps` so there's no API change required there. We likely chose `16ms` to map to `60fps`, but I can see exposing it as a prop for advanced use cases. Adding @micahgodbolt for his thoughts re: the API.

**List.types.ts**

```diff
diff --git a/packages/office-ui-fabric-react/src/components/List/List.types.ts b/packages/office-ui-fabric-react/src/components/List/List.types.ts
index 816df8356..3221d60b4 100644
--- a/packages/office-ui-fabric-react/src/components/List/List.types.ts
+++ b/packages/office-ui-fabric-react/src/components/List/List.types.ts
@@ -150,6 +150,8 @@ export interface IListProps extends React.HTMLAttributes<List | HTMLDivElement>
    * Override this to control how cells are rendered within a page.
    */
   onRenderPage?: (pageProps: IPageProps, defaultRender?: IRenderFunction<IPageProps>) => React.ReactNode;
+
+  resizeDelay?: number;
 }
 
 export interface IPage {

```

**List.tsx**

```diff
diff --git a/packages/office-ui-fabric-react/src/components/List/List.tsx b/packages/office-ui-fabric-react/src/components/List/List.tsx
index 551e1557b..61a46788e 100644
--- a/packages/office-ui-fabric-react/src/components/List/List.tsx
+++ b/packages/office-ui-fabric-react/src/components/List/List.tsx
@@ -143,6 +143,8 @@ export class List extends BaseComponent<IListProps, IListState> implements IList
     // Track the measure version for everything.
     this._measureVersion = 0;
 
+    const { resizeDelay = RESIZE_DELAY } = props;
+
     // Ensure that scrolls are lazy updated.
     this._onAsyncScroll = this._async.debounce(this._onAsyncScroll, MIN_SCROLL_UPDATE_DELAY, {
       leading: false,
@@ -153,7 +155,7 @@ export class List extends BaseComponent<IListProps, IListState> implements IList
       leading: false
     });
 
-    this._onAsyncResize = this._async.debounce(this._onAsyncResize, RESIZE_DELAY, {
+    this._onAsyncResize = this._async.debounce(this._onAsyncResize, resizeDelay, {
       leading: false
     });
 ```

**Example DetailsList Usage**

```diff
diff --git a/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Basic.Example.tsx b/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Basic.Example.tsx
index 677a6d46a..0defb2664 100644
--- a/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Basic.Example.tsx
+++ b/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Basic.Example.tsx
@@ -1,12 +1,6 @@
 import * as React from 'react';
 import { TextField } from 'office-ui-fabric-react/lib/TextField';
-import {
-  DetailsList,
-  DetailsListLayoutMode,
-  Selection,
-  IColumn,
-  IDetailsList
-} from 'office-ui-fabric-react/lib/DetailsList';
+import { DetailsList, DetailsListLayoutMode, Selection, IColumn, IDetailsList } from 'office-ui-fabric-react/lib/DetailsList';
 import { MarqueeSelection } from 'office-ui-fabric-react/lib/MarqueeSelection';
 import { Checkbox } from 'office-ui-fabric-react/lib/Checkbox';
 import { createRef } from 'office-ui-fabric-react/lib/Utilities';
@@ -96,6 +90,7 @@ export class DetailsListBasicExample extends React.Component<
             ariaLabelForSelectionColumn="Toggle selection"
             ariaLabelForSelectAllCheckbox="Toggle selection for all items"
             onItemInvoked={this._onItemInvoked}
+            listProps={{ resizeDelay: 100 }}
           />
         </MarqueeSelection>
       </div>
```

There are a few other hard-coded async constants in use that we may want to expose as configurable if we decide to do this.

**Comment by dliu120** [comment]
Thanks @KevinTCoughlin  Being able to adjust the debounce from 16ms to 500ms now allows us to resize the browser without it locking up, but it looks like there is some other weirdness going on under the hood.

The below timings show several _onAsyncResize calls behind fired from List and from WithViewportComponent. This was from just resizing the browser once, within the 500ms delay.

![image](https://user-images.githubusercontent.com/2090090/46511696-ec056100-c804-11e8-9995-ec6e62299579.png)

**Comment by micahgodbolt** [comment]
Is this still an issue in light of the change in #6413 ?

**Comment by KevinTCoughlin** [comment]
> 
> 
> Is this still an issue in light of the change in #6413 ?

Yea, the scope needs tweaking, but the underlying problem here is _one of_ if not _the major_ DetailsList performance issue. I was planning to track that work here, but we can close and reference in a different issue once opened. This is my perf top priority of Q1.

**Comment by micahgodbolt** [comment]
Lets go with a new issue. No need to spam the OP unless the work you are doing specifically resolves this issue.

**Comment by dliu120** [comment]
We can close this since the underlying issue is captured. Thanks!
