### ISSUE TITLE
Pivot: RTL support for count text

### ISSUE THREAD

**Issue by cschleiden** [OfficeDev/office-ui-fabric-react#657]
### Bug Report

- __Package version(s)__: master

#### Describe the issue:

Pivot with a count like this:

![image](https://cloud.githubusercontent.com/assets/2201819/20904424/534ffe4e-baf4-11e6-9aca-7af897d01bd8.png)

will show up like this with `dir=rtl`:

![image](https://cloud.githubusercontent.com/assets/2201819/20904435/615facd2-baf4-11e6-9202-48e80ad1c10e.png)

Not sure if maybe we should add &lrm or &#x200e; to the count, so that it looks like:

![image](https://cloud.githubusercontent.com/assets/2201819/20906234/e536b4ae-bafb-11e6-8944-43fd56200e0c.png)

Example: http://codepen.io/anon/pen/dOmmZP

**Comment by mikewheaton** [comment]
That is so strange that it moves the last round bracket to the beginning of the line in RTL. Just to confirm, this is a common issue and nothing specific to what we're doing as this [StackOverflow issue](http://stackoverflow.com/questions/5741522/brackets-displays-wrongly-for-right-to-left-display-style) shows.

So yes, the correct fix seems to be to add the `&lrm;` [left-to-right mark](https://en.wikipedia.org/wiki/Left-to-right_mark) after the count to indicate that this string should stay the same in RTL.

**Comment by dzearing** [comment]
hmm not sure that localizes well. You don't want to do that in RTL languages, right?

**Comment by mikewheaton** [comment]
The `&ltrm;` should exist after the count, for both LTR and RTL users. It tells the browser not to do anything funky with the round brackets. The actual string (e.g. 'Recent' or 'My Files') that needs to be localized is separate.

**Comment by cschleiden** [comment]
But do we want to move the whole number string to the left/right? Like
ltr: `Recent (42)` 
rtl: `(42) Recent`?

**Comment by dzearing** [comment]
What I think is a better approach is that the tab content renders 2 `span` elements and maybe they're inline-blocked. Then it renders like so:

![image](https://cloud.githubusercontent.com/assets/1110944/20907047/8cb178be-bb00-11e6-9077-abd9a34b4ccd.png)

So the real requirement here I think is that the consumer can render custom content in the pivot headers.

**Comment by mikewheaton** [comment]
But is **(12) My Files** correct, or should it be **My Files (12)**? My assumption was that the badge is part of the string and shouldn't be re-arranged, but I'm not certain on that.
