### ISSUE TITLE
Link buttons don't wrap

### ISSUE THREAD

**Issue by aneeshack4** [OfficeDev/office-ui-fabric-react#6571]
### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/aneeshack4/pen/jerrVm

### Bug Report 
 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) Yes
 
Requested priority: (Blocking, High, Normal, Low) Low
 
Products/sites affected: (if applicable) 
 
#### Describe the issue:
 
Links that are buttons don't word wrap - may just have to get rid of using buttons in links; maybe use spans instead.
 
#### Actual behavior:

![image](https://user-images.githubusercontent.com/4161791/46502769-d16bc180-c7dd-11e8-98e2-04cd07782bdd.png)
(button's individual text doesn't wrap the whole button wraps)

#### Expected behavior:
The button's individual text should wrap.

**Comment by Vitalius1** [comment]
Do we know why we even offered this option?

**Comment by aneeshack4** [comment]
@Vitalius1 not sure... I guess the default is buttons if you don't provide a href and we want to support that but it looks like for the wrapping case, that's not possible.

**Comment by Vitalius1** [comment]
I am almost inclined to just make sure we emphasize this two cases of how the link is rendered and how it might impact the design and not make this breaking change. As an alternative we could just add the `as` prop pattern to give consumers a choice on either to use `<a/>` or `<button/>` or `<span/> and than add some logic to support backward compatibility with the current implementation.

**Comment by micahgodbolt** [comment]
Supporting wrapable buttons might be something to look at in #6134

**Comment by micahgodbolt** [comment]
closing this issue down to reduce duplication
