### ISSUE TITLE
neutralSecondaryAlt color removal final one!

### ISSUE THREAD

**Issue by Vitalius1** [OfficeDev/office-ui-fabric-react#6575]
### Bug Report 
This is to track the removal of the remaining of usage of `neutralSecondaryAlt` color across the repo as continuation of #5194 and #6500.
I consider that this last issue should be the final cleanup and should be proceeded to only when we have answered the questions bellow.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal
 
#### Describe the issue:
 
Here is where it can still be seen:

- `fabric-website` - should be as simple as confirming with designers on a replacement
- `example-app-base` - same as above
- `experiments` - most likely can be removed without breaking changes (it's experimental 😄 )
- `styling` - @phkuo can this be removed? I assume not as it will break downstream but can you confirm?
- `office-ui-fabric-react` - in [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/common/_themeOverrides.scss) and [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ThemeGenerator/ThemeRulesStandard.ts#L42) not sure if it needs to be left in this places. @phkuo do you have any context in here too?

**Comment by micahgodbolt** [comment]
@Vitalius1 any progress on this?

**Comment by phkuo** [comment]
It can be removed from the SASS variables (those weren't being exported until after the deprecation anyways), leave it in code where it is now for backwards compatibility.

**Comment by Vitalius1** [comment]
@phkuo I am a little bit confused on what do you mean by

> ...leave it in code where it is now...

Do you mean that anything in a `.scss` file can be removed and in cases of it being used in a `.ts` file should be left as is?

**Comment by phkuo** [comment]
I mean that it should be removed anywhere it is being consumed in Fabric components, but remain in place in the theming infrastructure code. i.e. deprecated but still technically supported

**Comment by Vitalius1** [comment]
#8098 is bringing back from deprecation `neutralSecondaryAlt` palette slot so this issue is no longer valid. Closing!
