### ISSUE TITLE
TextField: onChange event not working in excel task pane add-in

### ISSUE THREAD

**Issue by manish-shukla01** [OfficeDev/office-ui-fabric-react#6578]
### Please provide a reproduction of the bug in a codepen:
 it works in codepen and regular browser. something weird that it does not work in excel
### Bug Report 
 Here is how i have put the Textfield in my app div.
```
<TextField
  label="field1"
  value={this.state.value1}
  onChange={(event) => this.handleChange(event,1)}
  required
/>
```

**Handle change event looks like this**
```
handleChange(event, fieldnum) {
  if(fieldnum==1) {
    this.setState({value1:event.target.value});
  } else {
    this.setState({value2:event.target.value});
  }
```
**State looks like this**
```
this.state = {
  value1: 'value1',
  value2:'value2',
  message:'Helloooo'
};
```
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 No
Requested priority: (Blocking, High, Normal, Low) 
 Blocking
Products/sites affected: (if applicable)
 
#### Describe the issue:
 
Do we have any example of TextField component working in actual excel. I am trying to do something very simple. Textfield will take a user entry and on click of a button, i woudl like to populate data in excel based on user entry in textfield. SO i need to make this textfield a controlled component so i can get teh value of the state and use it to populate data in excel. Obviously it works in codepen.

 
#### Actual behavior:
 
Look above. I think onChange is not getting registered. 
 
#### Expected behavior:
 
onChange shoudl get fired.

**Comment by JasonGore** [comment]
Is there any way you could share an Excel spreadsheet that exhibits this behavior? This would help us triage the issue quite a bit. Thanks!

**Comment by ecraig12345** [comment]
We're happy to help, but without any way to reproduce this or any info about the affected version of Fabric, there's not much we can do here.

**Comment by zakhan4** [comment]
Hello, I'm facing the same error. Though I have tried it on Word Task Pane Add-in. Even the 'onChanged' event is working but 'onChange' is not. I'm using Word 2016 Version 1811 (Build 11010). I'm also attaching the word file if that helps. 
[Document2.docx](https://github.com/OfficeDev/office-ui-fabric-react/files/2615198/Document2.docx)


> We're happy to help, but without any way to reproduce this or any info about the affected version of Fabric, there's not much we can do here.
