### ISSUE TITLE
DetailsList: drag and drop onDrop event not firing

### ISSUE THREAD

**Issue by aaronyzhou** [OfficeDev/office-ui-fabric-react#658]
### Bug Report

- __Package version(s)__: master

#### Describe the issue:

I'm trying to implement drag and drop on a details list and there is no onDrop event being fired.
I don't see any code that calls the onDrop method of the callback.

https://github.com/OfficeDev/office-ui-fabric-react/search?utf8=%E2%9C%93&q=onDrop&type=Code

**Comment by dzearing** [comment]
Investigated. Will work with people on our end to get it fixed.

**Comment by dzearing** [comment]
We will add:

1. A sample illustrating drag/drop support.
2. Fix for the missing onDrop callback.
3. Add some tests.

**Comment by sideyuan** [comment]
We are waiting for this fix. Are you still in holidays? ;) @dzearing

**Comment by cschleiden** [comment]
@aaronyzhou will this be fixed with your PR?
