### ISSUE TITLE
Picker: After selecting a user, the menu flashes in the upper left hand corner

### ISSUE THREAD

**Issue by msadahiro** [OfficeDev/office-ui-fabric-react#6583]
### Bug Report 
 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 No
Requested priority: (Blocking, High, Normal, Low) 
High
 
Products/sites affected: (if applicable)
Azure Blockchain Workbench
#### Describe the issue:
 
When typing in a user, and selecting user with 'enter' the menu flashes in the upper left corner. 
 
#### Actual behavior:
 
When typing in a user, and selecting user with 'enter' the menu flashes in the upper left corner.
 
#### Expected behavior:
 
When selecting a user, the menu does not flash OR menu stays next to the input field. 
![flashing_menu](https://user-images.githubusercontent.com/24423105/46553856-798f9200-c893-11e8-80ef-262b69088d51.gif)

**Comment by micahgodbolt** [comment]
@joschect any idea why the picker flashes quickly on keyboard selection? I can repro a quick flash on our basic demo, though it's not as noticable as this one as it's still in the same place as the normal one.

**Comment by micahgodbolt** [comment]
Seems to be solved in latest release
