### ISSUE TITLE
Multiline TextField resizable to below minimum height on webkit browsers 

### ISSUE THREAD

**Issue by TubanMicrosoft** [OfficeDev/office-ui-fabric-react#6586]
### Please provide a reproduction of the bug in a codepen:
 https://codepen.io/TuckerBane/pen/NORNeK

### Bug Report 
 
 
- __Package version(s)__: (6.78.1, 6.78.0, possibly more) 
- __Browser and OS versions__: Chrome (Uses Webkit only feature)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
No
Requested priority: (Blocking, High, Normal, Low) 
Normal
Products/sites affected: (if applicable)
PowerApps (minor issue)
#### Describe the issue:
 
The icon you drag to resize multi-line TextFields can be moved past the minimum height of the TextField. 
 
#### Expected behavior:
 
TextField resizing stops when it reaches it's minimum height

#### Local fix:
 Giving the actual text field element min-height:"inherit" fixes the issue. Fixable by the end user, but better if it's fixed here.

### image of the issue happening

![badlookingtextfield](https://user-images.githubusercontent.com/40703337/46563950-37794700-c8b9-11e8-862b-b2ee1b6906a8.PNG)

**Comment by Vitalius1** [comment]
@TubanMicrosoft thanks a lot for catching this bug and also for providing a solution.
The fix should go [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/TextField/TextField.styles.tsx#L254)
