### ISSUE TITLE
tab key failed on combo box rendering

### ISSUE THREAD

**Issue by jayleems2018** [OfficeDev/office-ui-fabric-react#6596]
### Bug Report 
The scenario is there are two combo boxes.  One depends another.  That says it can only happen at rendering.  The example will be: Combox box A has item a,b,c.  Now in Combo box B it is depends on input of Combo A.  
Let's say a has a1,a2,a3 if enter a in Combo A. b in Combo A has b1,b2,b3,b4,b5.  c in Combo A has c1,c2. 

If user select b in combo A, it will not go to Combo b as next control. 

I believe the issue here is, we have to render Combo B in render function.  There is no way we can make it outside of render function since combo B depends on combo A.  
 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by Vitalius1** [comment]
@jayleems2018 would be really helpful if you could provide a repro of this bug in codepen. [Here](https://codepen.io/vitalius1/pen/aRmmmg) is a starter for you to begin. It's really hard to debug without having a use scenario. Thanks!
