### ISSUE TITLE
[merge-styles] justifyContent definition in IRawStyleBase is not complete

### ISSUE THREAD

**Issue by markuskr** [OfficeDev/office-ui-fabric-react#6597]
### Please provide a reproduction of the bug in a codepen:
 
CSS grid introduces `stretch` as a valid value for `justifyContent` which is missing in `IRawStyleBase`: 

`justifyContent?: ICSSRule | 'flex-start' | 'flex-end' | 'center' | 'space-between' | 'space-around' | 'space-evenly';`

Formal definition from MDM: https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content#Formal_syntax
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal

**Comment by dzearing** [comment]
Easy fix, go for it!
