### ISSUE TITLE
Focus is not reaching to "chevron down" icon(scan-mode), in commandbar, if split property is true

### ISSUE THREAD

**Issue by kmrrakesh** [OfficeDev/office-ui-fabric-react#6598]
### Please provide a reproduction of the bug in a codepen:
https://codepen.io/anon/pen/KGNybW 

### Bug Report 
- __Package version(s)__: ">= 6.0.0 < 7" 
 - __Browser and OS versions__: Edge and Windows 10
 
#### Describe the issue:
Focus is not reaching to "chevron down" icon, in commandbar, if split property is true
It is occurring in both of the cases of scan-mode On and Off

 
#### Actual behavior:
Focus is not reaching to "chevron down" icon, in commandbar, if split property is true
 
#### Expected behavior:
Focus should reach to "chevron down" icon, in commandbar, if split property is true

**Comment by dzearing** [comment]
@jspurlin I believe this is by design, because the keyboard shortcut for expanding a splitbutton menu is alt/command down arrow. Can you confirm?

**Comment by jspurlin** [comment]
@dzearing, correct this is by design. We got direct user feedback that this is expected behavior for a splitButton.

**Comment by dzearing** [comment]
Thank you @jspurlin! @kmrrakesh this is by design.
