### ISSUE TITLE
DetailsList: Column widths not calculated correctly, if property maxWidth not specified.

### ISSUE THREAD

**Issue by biogenez** [OfficeDev/office-ui-fabric-react#660]
### Bug Report
- __Package version(s)__: 0.81.2
- __Browser and OS versions__: All

#### Describe the issue:
Column widths not calculated correctly, if property **maxWidth** not specified.
Since  the property **maxWidth** is not required, there is a wrong calculation in the code below 
(file [DetailsList.tsx):](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.tsx)
function **_getJustifiedColumns**: 

![capture](https://cloud.githubusercontent.com/assets/4600781/20929519/12a7b938-bbd3-11e6-90f7-8527c534981a.PNG)

Then we have exception in DetailsHeader.tsx and wrong columns width:
**warning.js:36 Warning: `NaN` is an invalid value for the `width` css style property. Check the render method of `DetailsHeader`.**

**Comment by dzearing** [comment]
Easy fix. I'll fix it if someone doesn't beat me to a PR.

**Comment by joschect** [comment]
@biogenez This should be fixed now, let me know if it's not!
