### ISSUE TITLE
loadTheme: some components built with `styled` are not re-rendered when a new theme becomes available.

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#6603]
The `loadTheme` api will use the Customizations singleton to define the global theme. The singleton has an `observe` method to observe global customization settings.

I believe `styled` needs to observe these changes so that it can re-evaluating styling when loadTheme is called. I am a little nervous about a perf issue here, so we would only want a re-render to occur when the theme actually changes.

You can observe the bug that is caused here:

https://codepen.io/dzearing/pen/xyZGmM

If you remove the wrapped `Customizer` in the markup, you'll notice that the theme isn't flipping (select some items.) For some reason, just adding the `Customizer` wrapper fixes this. Not sure why. Perhaps because `Customizer` is observing global state changes.

**Comment by JasonGore** [comment]
I'm sure this problem affects `createComponent` as well since it is modeled after `styled` and nothing observes global customization changes.

**Comment by dzearing** [comment]
cool beans

**Comment by micahgodbolt** [comment]
appears to be fixed via #7088
