### ISSUE TITLE
Theming: direction should be provided through theme

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#6604]
Right now, the direction is provided through the html dom. This implies 2 problems:

1. Changing the `<html rtl='true'` attribute does not retrigger a re-render so any calculated values won't be re-evaluated.

2. There is no contextual direction, so for example, an email client rendered in LTR can't render an inbox mail in RTL.

Proposal:

Provide `rtl` setting in ITheme. This means that:

1. `loadTheme` can be used to define the overall page direction.
2. `Customizer` can be used to override a subsection of the ui.

Alternatives:
Provide direction via a dedicated context helper.

Additional thoughts:

This might require that we reassess all usage of `getRTL`.

**Comment by micahgodbolt** [comment]
Looks like the getRTL function will need to accept the current theme from where the function is called, and return the theme RTL setting if set, or return the global value if not set.
