### ISSUE TITLE
Disabled Dropdown has no aria-label on screen reader

### ISSUE THREAD

**Issue by mowei8** [OfficeDev/office-ui-fabric-react#6605]
### Bug Report 
 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No
 
Requested priority: (Blocking, High, Normal, Low) Normal
 
Products/sites affected: (if applicable)
 
#### Actual behavior: When it gets to a disabled dropdown, the screen reader (Narrator) will just read "1 of 2, selected: can view". It will not read that the dropdown is disabled.

![image](https://user-images.githubusercontent.com/39922684/46624588-10538d00-cae6-11e8-8001-f1c3889ad8c9.png)

**Comment by natalieethell** [comment]
Hey thanks for submitting this issue @mowei8! Digging into this, I found something interesting. When the `multiSelect` prop is set to true, "disabled" is read out by the screen reader. When it's not set, it defaults to false and "disabled" is not read out. I'm going to investigate this more.

**Comment by natalieethell** [comment]
It looks like `aria-activedescendant` may be the culprit here.
