### ISSUE TITLE
How high level is this library supposed to get?

### ISSUE THREAD

**Issue by rickyp-ms** [OfficeDev/office-ui-fabric-react#661]
Most of the stuff in this library is pretty low -> medium level (dialogs, dropdowns, etc).

Across newer office applications there are some other commonalities such as (what we call) TopHeader
![topheader](https://cloud.githubusercontent.com/assets/22225666/20942404/1c5fe842-bbb0-11e6-8b35-8d1c0d996089.png)

It's currently in use in Skype and will be in Planner with the next iteration. 

Would this control too high level for this library?

Also, I was curious if a abstracted filepicker control was of any interest. The control itself wouldn't connect to any specific services but instead provide a consistent UI that can connect to one or many services to allow links to be generated to those external services.

**Comment by mikewheaton** [comment]
We're generally looking for components that could be included in a wide variety of apps. We want to avoid the confusion of having multiple components that serve similar purposes, but which originally came from different apps. Having more broadly-applicable components also means more usage, more developers, more issues files, and more bug fixes.

That said, if you have any components you'd like to contribute back please open an issue with some screenshots (or a live demo if possible) and we'll make sure the designers see them and consider including them. Thanks!
