### ISSUE TITLE
Add headerContainer style location in DetailsList

### ISSUE THREAD

**Issue by brandonthomas** [OfficeDev/office-ui-fabric-react#6611]
We need to be able to declaratively set the styling on the container of the header within DetailsList to support sticky (using css sticky) behavior. I currently use a work around involving refs and finding the parent but this isn't ideal and causes some issues around timing (we sometimes see styles added after initial paint). 

**What component or utility would this be added to**
DetailsList

**Have you discussed this feature with our team, and if so, who**
Yes, Micah Godbolt

**Comment by Vitalius1** [comment]
@brandonthomas if you are trying to achieve a sticky header of the `DetailsList` I recommend looking [HERE](https://developer.microsoft.com/en-us/fabric#/components/scrollablepane) for an example using our `ScrollablePane` with `Sticky` components. Also, soon there is coming a modification of that example to use a sticky header and footer with a `DetailsList`.

**Comment by brandonthomas** [comment]
We don't want scrollable pane or sticky. It has a lot of jank and it's smooth. We want to use position: sticky.

**Comment by brandonthomas** [comment]
Not only that but we need to support horizontal sticky as well. So this is why native is what we need.

**Comment by brandonthomas** [comment]
Fixing typo error in title. Should be DetailsList not DetailsPane.

**Comment by brandonthomas** [comment]
Currently targeting 6.72.1 but will be moving to current after I put in a work around for another issue I filed.

Attached is the screenshot requested. The highlighted div is the one I need. I have a custom classname on it now but i had to get it by putting a ref on my custom header element and grabbing its parent. This is the containing div that the custom header content is placed in and a child of the actual grid content itself.
![image](https://user-images.githubusercontent.com/7529639/46983488-9ac36000-d095-11e8-8382-4fc39f2a21a4.png)
