### ISSUE TITLE
TooltipHost/Tooltip does not respect user input id prop

### ISSUE THREAD

**Issue by qqli1209** [OfficeDev/office-ui-fabric-react#6616]
### Please provide a reproduction of the bug in a codepen:
https://codepen.io/qianl/pen/mzRKgX
 

### Bug Report 
 
 
- __Package version(s)__: (latest) 
- __Browser and OS versions__: (all)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (Normal) 
 
Products/sites affected: (all)
 
#### Describe the issue:
 
 `TooltipHost`/`Tooltip` has an `id` prop, but after I give it a valid value, the generated HTML file will not have any element with the given id.
 
#### Actual behavior:
 
There is no element have the given `id`(here is `"myID"`). As the `id` value is used for `aria-describedby`, as a result we have no valid value for `aria-describedby`.

![image](https://user-images.githubusercontent.com/13404320/46665496-9fe86100-cbf6-11e8-92e0-1d69325785bd.png)

#### Expected behavior:
 
There should be an element have the given `id`.

**Comment by micahgodbolt** [comment]
getNativeProps passes all divProps down to the tooltip itself. The tooltip pulls the ID out and applies it to the div wrapping the tooltips content 

https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Tooltip/Tooltip.base.tsx#L60

**Comment by micahgodbolt** [comment]
its possible the ID is there, but it's hard to spot as it dissapears as soon as you try to inspect it

**Comment by qqli1209** [comment]
@micahgodbolt  Yes, and the problem we meet is that if not hover on it, the **id** is not valid. As a result, the screen reader will not read the content in the div with the **id**. It would be great if you can put the content that you want screen reader to read into an other element, with some **css** to hide to from normal users.

**Comment by qqli1209** [comment]
Can I re-open the issue? @micahgodbolt  After I reply, the issue closed automatically.

**Comment by micahgodbolt** [comment]
The ID is getting rendered, though it's not quite at the root of the tooltip as i'd expect. https://codepen.io/micahgodbolt/pen/aRVydo

**Comment by qqli1209** [comment]
Yes, the ID is getting rendered only when the content of Tooltip/ToolTipHost is rendered.  It would be great if we put the content that we want screen reader to read into an other element, with some **css rules** to hide it from normal users.

**Comment by micahgodbolt** [comment]
you can pass the 'hidden' prop to calloutProps that will render the tooltip on page render, then just hide/show it when needed. Does that work for you?

**Comment by qqli1209** [comment]
@micahgodbolt Thanks for your help! It works for me. As the bug has no user impact, I will close it.
