### ISSUE TITLE
TextField: Add clear button and icon support, deprecate SearchBox

### ISSUE THREAD

**Issue by cschleiden** [OfficeDev/office-ui-fabric-react#662]
`TextField` supports a `focus` method which sets focus to the wrapped input element, `SearchBox` is missing such functionality.

**Comment by dzearing** [comment]
Funny you brought that up. We're considering collapsing `SearchBox` into `TextField`. They really aren't THAT different. If TextField had an optional clear button and an info icon, they'd be identical. So we are considering just deprecating it all together and adding a few features to TextField.

What do you think? Also can you provide some use cases where you're using `SearchBox`? (A screenshot would help our designers to consider your scenario.)

**Comment by cschleiden** [comment]
Yep, that would make perfect sense for us. 

Right now we are looking at a scenario where we use either `SearchBox` or `TextField` depending on the type of a field being edited, and instead of switching between the two controls, I could see us just changing placeholder/icon. 

Some *very* early explorations in that direction: 
![image](https://cloud.githubusercontent.com/assets/2201819/20951115/c2d252dc-bbd8-11e6-9b3e-31e50bbbbe2e.png)
![image](https://cloud.githubusercontent.com/assets/2201819/20951125/cfc9611a-bbd8-11e6-9009-3c03f033a78d.png)

**Comment by dzearing** [comment]
Renaming the item to replace SearchBox with TextField so there is way less inconsistency and confusion.

**Comment by mikewheaton** [comment]
Flagging as 'needs-design' to make sure we discuss this in a future design meeting. As far as the designers are concerned, TextField (even with a search icon and used in a search experience) is distinct from SearchBox. How this gets implemented is up to us, so we might have a TextField variant or use TextField within SearchBox, but we need to find out more about the requirements before making any changes to SearchBox.

We have another bug to [fix the positioning of icons in TextField](https://github.com/OfficeDev/office-ui-fabric-react/issues/650) and I've confirmed that TextField **should not have a clear button**.

**Comment by cschleiden** [comment]
So from #650, there will be no merge of text- and searchbox? Do we still need this item as a "needs-design" reminder or can I change it back to the original issue? I need that `focus` method :)

**Comment by mikewheaton** [comment]
@cschleiden: Let's get the `focus` method added to SearchBox, but hold off on merging these components until we've had a chance to discuss with the design team. Thanks!

**Comment by battletoilet** [comment]
Search box has been revamped since this issue was opened. As of now this is not something we will pursue.
