### ISSUE TITLE
Suggest removing Button Swap with Focus State example - unclear purpose, not accessible

### ISSUE THREAD

**Issue by BrendanMcK** [OfficeDev/office-ui-fabric-react#6634]
- __Package version(s)__:  6.49.2
- __Browser and OS versions__: n/a
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No
 
Requested priority: (Blocking, High, Normal, Low) Low 
 
Products/sites affected: (if applicable) N/A
 
#### Describe the issue:
 
The [docs for the Button component](https://developer.microsoft.com/en-us/fabric#/components/button) have a rather odd "Button Swap with Focus State" example.

There's a few issues with this:

* It's unclear what the actual use-case for this is. Clicking just toggles between primary and secondary button styles

* The behavior on the doc page makes this looks like it might make a good on/off toggle button; however it *can't* be used as-is for that purpose, because the current state is not conveyed in any accessible manner.

Suggest adding additional documentation to clarify the purpose of this demo item and point any caveats (such as the a11y issue mentioned above); or if there's no good use case, delete it.

**Comment by micahgodbolt** [comment]
It's also not necessary any longer. I'm happy to see it removed.
