### ISSUE TITLE
Split button keyboard accessibility

### ISSUE THREAD

**Issue by erjohnms** [OfficeDev/office-ui-fabric-react#6642]
### Bug Report 
 
Split Buttons, by default, only allow for alt+down to expand the menu of the split button. I'm aware there is a menuTriggerKeyCode to make it whatever I want and I've started adding just 'down' as a key to expand these menus because otherwise we get pinged for not meeting keyboard accessibility guidelines.

I think its pretty weird that we have to add down as an option to all of our split buttons in order to meet the Aria guidelines of down arrow opening things like combo boxes and menus.

I don't know the history of why only alt+down is the default. But I feel like just allowing down would be a better default?

example:
https://www.w3.org/TR/wai-aria-practices-1.1/#combobox

- [ComboBox] It is displayed when the Down Arrow key is pressed or the show button is activated, possibly with a dependency on the content of the textbox.

- [MenuBar] Down Arrow: When focus is on a menuitem in a menubar, opens its submenu and places focus on the first item in the submenu.

 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix?
 
Requested priority: Low
 
Products/sites affected: Azure DevOps (but I've fixed it for us by using menuTriggerKeyCode)

**Comment by micahgodbolt** [comment]
something to consider in #6134

**Comment by dzearing** [comment]
I believe the reasoning here is that it avoids conflicts with FocusZone scenarios where you want to arrow between buttons, some being split.

@jspurlin any take on this?

**Comment by dzearing** [comment]
I've started a mail thread with the right folks.

**Comment by micahgodbolt** [comment]
what's the expectation of split buttons in vertical navigation. As I arrow down each item in the list would we need to prevent the behavior in that scenario?

**Comment by jspurlin** [comment]
I agree with David and the reasoning he provided

**Comment by dzearing** [comment]
I am going to close this, as the default should not be down arrow, but we have an email thread going and if we deem changes are required in that thread we will reopen.
