### ISSUE TITLE
FocusTrapZone: Not trapped in focus zone when one of the choice group item is focused programmatically

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#6653]
### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/anon/pen/jemZGY?editors=1010

### Bug Report 
- __Package version(s)__: latest
- __Browser and OS versions__: chrome
 
#### Priorities and help requested:
 
Requested priority: (High) 
 
Products/sites affected: (SharePoint publishing pages)
 
#### Describe the issue:
 
When ChoiceGroup is the last focusible element in FocusTrapZone, and if one of the non-selected item being focused, TAB will go out of FocusTrapZone instead of keeping trapped inside.

#### Repro steps:
1. Go to [demo](https://codepen.io/anon/pen/jemZGY?editors=1010)
2. Click on button "noop A"
3. Press TAB to focus on button "Press enter to focus on first radio button".
4. Press enter, observe the focus is on Option A while Option B is being selected.
5. Press TAB
 
#### Actual behavior:
 
Focus jumps to button "noop B"
 
#### Expected behavior:
 
Focus remains on Option A or
Focus jumps to Option B

**Comment by Vitalius1** [comment]
It could be similar to #4649

**Comment by dzearing** [comment]
I looked into this. The issue is because there is logic that says "is this the last focusable element in the zone?" which returns false as there is another radio button after it. However, due to how radio buttons have a peculiar tabbing behavior where they act like a focus zone, tabbing skips this element, causing the focus to exit the trap.

Not quite sure what the best fix here is.

**Comment by dzearing** [comment]
Actually, while technically this is a bug with radio buttons, a workaround is to set focus correct.

@ipip2005  you're reaching into the choicegroup to manually set focus on a specific dom element. Instead, you can use the focus() component method, which will set focus on the CORRECT choicegroup. This ensures the selected option is focused. I have updated the codepen here:

https://codepen.io/dzearing/pen/JmNaeB

1. use createRef
2. pass the ref into the `componentRef` prop.
3. when needed, call `this._ref.current.focus()` to set focus.

**Comment by ipip2005** [comment]
@dzearing Thank you for quick response and workaround. Unfortunately, it cannot applied to our case as in SPFX property pane.
We programatically focus on the first focusable item when the property pane is opened. The issue happens when there is only one choice group in the property pane.
But we'll never know what components will be added by developers to the property pane.

**Comment by ipip2005** [comment]
@dzearing Just wonder if there will be a fix for this bug. I can certainly apply some workaround to mitigate the issue by moving DOM sequences of our property pane close button to the last element. But I believe the issue will still persist with SHIFT + TAB

**Comment by cliffkoh** [comment]
Ping @dzearing

**Comment by JasonGore** [comment]
@ipip2005 I'm curious about one thing: if you don't know which components will be added by developers to property pane, how can you reach in even further to select a particular child of it (in this case a specific ChoiceGroup)? If you can select an element of the ChoiceGroup , can't you select the ChoiceGroup parent itself?

**Comment by ipip2005** [comment]
We use method like `getFirstFocusableChild` to get the first focusable html element in the property pane. I guess what you meant about "ChoiceGroup parent itself" is the React component right? However, in our infrastructure, we don't even know if the component rendered inside is react component or not.

**Comment by JasonGore** [comment]
OK, that makes sense. What is the implementation of `getFirstFocusableChild` and how is it determining an element is focusable?

Within `ChoiceGroup` (and many of our components), we use an attribute called `data-is-focusable` to determine if an element is focusable. For the first element in your example, this attribute is false. I'm curious if one option is for your `getFirstFocusableChild` element to check for the presence of this attribute?
