### ISSUE TITLE
scrollElement in List component is set beyond the intended parent when using the component in a modern page on SharePoint online

### ISSUE THREAD

**Issue by Damdan** [OfficeDev/office-ui-fabric-react#6655]
### Please provide a reproduction of the bug in a codepen:
 
Performed on SharePoint Online using SPFx framework.

### Bug Report 
 
No logs, no errors.
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 No
Requested priority: (Blocking, High, Normal, Low) 
 Low
Products/sites affected: (if applicable)
 SharePoint Online using modern sites
#### Describe the issue:
 
When using the List component inside a modern site, scroll activity is set way out into the pagelayout div tags (the whole web page) because of a data attribute (data-is-scrollable="true"). The parent of the overflowing list is ignored and only detects scrolling on the irrelevant element.

Applying the data attribute : data-is-scrollable="true" on the intended parent will fix the issue when using this component on SP Online.
 
#### Actual behavior:
 
Scroll state is set to listen on a different element than expected

**Comment by dzearing** [comment]
Just trying to understand the problem; is `data-is-scrollable` being set on the wrong element? And if so, is this in SharePoint, or is this something you control?

Or, is it missing on an element?

**Comment by Damdan** [comment]
Not being set but is already there since Modern sites on SP Online were built with react. So the page itself already has an app root element and my root components reside inside. I explicitly didn't set anything to my List component:

`<div>
        <List
          className="ms-ListGridExample"
          items={this.props.items}
          onRenderCell={this._onRenderCell}
        />
</div>`

When initialized in somehow finds some other element which had the data attribute already there. In my case it was the element right at the root app of the page itself. So when I scroll the whole page, the list component reacts to that action.

**Comment by mikewheaton** [comment]
The findScrollableParent function and its use in List have both been there since the initial commits of those files. @dzearing, should we document that `data-is-scrollable` is required on the scrollable parent of a List?

**Comment by dzearing** [comment]
Sorry for the slow response; yes `data-is-scrollable` is a performance optimization to look for the scrollable parent. Otherwise we'd have to getComputedStyle to figure this out, which is really slow. I'll see about adding some content to List documentation.

**Comment by dzearing** [comment]
Updated the readme.
