### ISSUE TITLE
DetailsList: Horizontal scroll always visible if  SelectionMode.single

### ISSUE THREAD

**Issue by biogenez** [OfficeDev/office-ui-fabric-react#666]
### Bug Report
- __Package version(s)__: 0.81.3

#### Describe the issue:
The button "Select all" is hidden if SelectionMode is *single*.
The css rule added left padding in the DetailsHeader, to correctly show headers.
But this css rule added horizontal scroll

**Css rule**
![image](https://cloud.githubusercontent.com/assets/4600781/21002495/df17cd8a-bd2e-11e6-9b9f-0c9908a09907.png).

**Issue**
![image](https://cloud.githubusercontent.com/assets/4600781/21002641/7b334622-bd2f-11e6-8ba3-27a84e6b6d3a.png)

**Fix**
Add padding-left rule for **ms-DetailsHeader-cellWrapper** if selectionMode == single as on the screenshot below:

![image](https://cloud.githubusercontent.com/assets/4600781/21002769/252f7f9c-bd30-11e6-92af-50e568f75180.png)

**Comment by dzearing** [comment]
i can investigate.

**Comment by dzearing** [comment]
Fixed in #1500
