### ISSUE TITLE
CSS Grid Properties missing from IRawStyleBase

### ISSUE THREAD

**Issue by joetheday** [OfficeDev/office-ui-fabric-react#6663]
### Bug Report 
 
 
- __Package version(s)__: 6.83.0
- __Browser and OS versions__: (fill this out if relevant)
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal
 
Products/sites affected: M365 Admin Center
 
#### Describe the issue:
 
Only part of the CSS Grid spec is implemented in IRawStyleBase. As a result, there are key pieces of the spec that a customer might need that are not there. 
 
#### Actual behavior:
 
Adding `gridRowGap` or `gridColumnGap` to any style rule results in a type error. 
 
#### Expected behavior:
 
It should be a valid CSS property

**Comment by micahgodbolt** [comment]
Hey @joetheday give me a shout when your have a PR, happy to get this in ASAP

**Comment by dzearing** [comment]
Grid gap isn't supported in IE11; you may have some issues there

**Comment by micahgodbolt** [comment]
@dzearing do you mean in adding it to IRawStyleBase, or in using it in M365 Admin Center? I can certainly see some IE11 fallbacks being written.

**Comment by dzearing** [comment]
Was talking with Levi about this today: https://css-tricks.com/css-grid-in-ie-css-grid-and-the-new-autoprefixer/

**Comment by joetheday** [comment]
@dzearing how do you envision autoprefixer working? Part of Fabric? Or part of the app that consumes it?

**Comment by micahgodbolt** [comment]
@dzearing you can write css targeting IE11 and Edge separately using @supports. So while IE11 might not support gap syntax,  you can write other CSS to accomplish something similar/usable.
