### ISSUE TITLE
Dropdown is not correctly set data-is-focusable attribute

### ISSUE THREAD

**Issue by lijunle** [OfficeDev/office-ui-fabric-react#667]
### Bug Report

- __Package version(s)__: As of 0.78.0
- __Browser and OS versions__: whatever

#### Describe the issue:

There is an issue about Fabric-React dropdown `data-is-focusable` attribute. [The current implementation](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.tsx#L84) is not right:
 
```html
data-is-focusable={ disabled }
``` 

Which should be (notice the “!”)
 
```html
data-is-focusable={ !disabled }
```

It is affecting the `FocusZone` and `FocusTrapZone` which are base on `data-is-focusable` attribute to change `tab-index` attribute.

---
 
BTW, it is NOT safe to use such a way to assign _Boolean_ value. React behavior differently on `undefined` and `false`. See this demo: http://codepen.io/lijunle/pen/WoyrbX  
 
The value `undefined` will make React NOT render this attribute, while value `false` will make React render the attribute with value `false` for _value attribute_. The _value attribute_ means the attribute NOT likes `checked`, `disabled` which only need to appear to work. (notice the difference between `data-focusable` and `disabled` when `false` is selected in the codepen).
 
It means, even if the above logic is right, we should write as the following two syntax to convert the value to `true`/`false` explicitly.
 
```htm
data-is-focusable={ !!disabled }
data-is-focusable={ Boolean(disabled) }
```

**Comment by dzearing** [comment]
Now resolved and will be published in the next build.
