### ISSUE TITLE
Checkbox on Safari iOS shows check after unchecked

### ISSUE THREAD

**Issue by banguero** [OfficeDev/office-ui-fabric-react#6672]
### Bug Report 
 
-Open https://developer.microsoft.com/en-us/fabric#/components/checkbox on Safari on an iOS device.

Initially the standard checkbox looks like this:

![image](https://user-images.githubusercontent.com/1873511/46850767-fcd84880-cda9-11e8-897a-e9f1e956b6da.png)

then if you tap on it, it looks like this:

![image](https://user-images.githubusercontent.com/1873511/46850797-111c4580-cdaa-11e8-9773-94f65230418b.png)

so far so good, but then if you tap it again to uncheck it, it looks like this:

![image](https://user-images.githubusercontent.com/1873511/46850813-242f1580-cdaa-11e8-815b-2082b6e1c799.png)

notice how a check is still shown. Not sure if it has always been like this or if it is a recent regression.  On regular web you also see that when you hover the checkbox.

#### Priorities and help requested:
 
Products/sites affected: (if applicable)

it was reported by a someone using the OneDrive Share dialog inside the Office Word iPad app.
 
#### Actual behavior:
 
A check with white background  is shown after you deselect the checkbox 
 
#### Expected behavior:
 
No check is shown

**Comment by micahgodbolt** [comment]
I know this is a dup of another issue. Having trouble finding it though. I believe it's an issue with touch events and hover

**Comment by dzearing** [comment]
yes ios locks in a hover unpredictably.

https://stackoverflow.com/questions/2741816/is-it-possible-to-force-ignore-the-hover-pseudoclass-for-iphone-ipad-users

Possible we could disable hover for... ios?

And hope you never have a mouse on ios... ?

If anyone has a suggestion on how to address, other than disabling hovers for everything on ios... please chime in :)

**Comment by mikewheaton** [comment]
This looks to be related to the issue in #5734.
