### ISSUE TITLE
PeoplePicker: Change from 28px to 24px Persona

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#6675]
### Bug Report 
 
 
- __Package version(s)__: Latest
- __Browser and OS versions__: All
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal
 
Products/sites affected: Reported by O365 Admin
 
#### Describe the issue:

The inner padding for TextField and PeoplePicker is inconsistent. This causes their content to be out of alignment when the fields are displayed on top of one another. Reported by Dieter and confirmed by @betrue-final-final.

![image](https://user-images.githubusercontent.com/1382445/46879425-e9a19900-cdfa-11e8-9313-bc4b0a3f2eb5.png)

![image](https://user-images.githubusercontent.com/1382445/46879440-f8884b80-cdfa-11e8-9b13-39f94053753e.png)

#### Expected behavior:
 
The inner horizontal padding of all fields should be 8px.

**Comment by micahgodbolt** [comment]
@mikewheaton just making sure this is on your radar.

**Comment by mikewheaton** [comment]
After discussing this with @betrue-final-final, we identified two issues:

### Horizontal alignment
![image](https://user-images.githubusercontent.com/1382445/51148332-a64c3180-1812-11e9-8836-56db846f1a2f.png)

PeoplePicker places its content much closer to the left than other fields do. The latest component designs reduce that gap to 8px for the others, which makes PeoplePicker look aligned (see below). So there will be **no change for now**.

![image](https://user-images.githubusercontent.com/1382445/51148398-e4e1ec00-1812-11e9-8e09-130b496268d7.png)

### Vertical alignment
![image](https://user-images.githubusercontent.com/1382445/51148514-5d48ad00-1813-11e9-8d8e-d9ea78397556.png)

The other fields are 32px tall, while the PeoplePicker is 36px tall. The designs actually call for a smaller 24px Persona to be used there. This will result in a consistent height for all inputs (see previous image).

I'll rename this issue to be clear that we **need to change the size of the Persona**so this is consistent.
