### ISSUE TITLE
Optionally disable displaying group.count in <GroupHeader />

### ISSUE THREAD

**Issue by goodoldneon** [OfficeDev/office-ui-fabric-react#6676]
**Describe the feature that you would like added**

Optionally disable displaying `group.count` in `<GroupHeader />`.

**What component or utility would this be added to**

GroupHeader

**Have you discussed this feature with our team, and if so, who**

No

**Additional context/screenshots**

It'd be convenient to disable displaying the group count within the `DetailsList.groups` prop.

**Comment by KevinTCoughlin** [comment]
For now, as a workaround you may be able to hide the count via `styles`, specifically the target: `headerCount`.

https://github.com/OfficeDev/office-ui-fabric-react/blob/e83f082e86ab8a599f298dc1dfe343981bbebee5/packages/office-ui-fabric-react/src/components/GroupedList/GroupHeader.base.tsx#L179

**Comment by KevinTCoughlin** [comment]
I'm going to mark this as "Needs: Author Feedback" to be closed by the bot unless we feel strongly that an _additional_ prop is ideal for hiding the group count. Given the expansive props API for these controls (DetailsList, etc.), I think its reasonable to suggest using `styles` here.

**Comment by goodoldneon** [comment]
I'm able to hide it via CSS, though that feels a little hacky. However, if I'm the only person requesting this feature then it isn't worth adding a prop for me.

**Comment by KevinTCoughlin** [comment]
> 
> 
> I'm able to hide it via CSS, though that feels a little hacky. However, if I'm the only person requesting this feature then it isn't worth adding a prop for me.

I appreciate your flexibility here @goodoldneon.

I agree this is worthy of consideration, but first think we need to audit the current *List component API surfaces as part of the next major release before adding more. Particularly if the behavior is achievable through existing methods.

Given the above, I'm going to close this for now. But we will revisit.
