### ISSUE TITLE
[Screen Reader - Power Apps Admin - Select a Template] In scan mode narrator focus does not moves to the checkbox available, on the Select a template blade. 

### ISSUE THREAD

**Issue by sonimishra** [OfficeDev/office-ui-fabric-react#6691]
### Please provide a reproduction of the bug in a codepen:

User Experience:
If, in scan mode narrator focus is not moving to the checkbox available on the table then the users who depends on narrator for navigation might get affected and does not able to get the information of that control. 

MAS Ref:
MAS 4.2.10 - Tracking of Focus and Selection Attributes (33J)

Keros statement : Check out Keros! - Identify accessibility bugs before check-in and make bug fixing faster and easier.   

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)
 
#### Describe the issue:

Pre-Requisite:
1. Turn on narrator by pressing Ctrl + window + ENTER combination.

Repro Steps:
1. Navigate to https://admin.powerplatform.microsoft.com/ext/DataIntegration  and login with intusr.
2. Navigate to the Data Integration menu item on the left bar and select it.
3. Navigate to "+New Project" on the top right corner and select it.
4.New Data integration project screen with Connection tab item selected opens.
5. Navigate on the connection radio button and select it.
6. Navigate to Next button on bottom and select it.
7. Select a template screen appears. Navigate to controls of the screen.
8. Navigate with the narrator in scan mode on table and reach 'Shared'  .
Verify whether the narrator focus in scan mode moves to the checkbox or not.

 #### Actual behavior:
When user navigate over the table with the narrator in scan mode and reach 'Shared' then the focus of the narrator does not moves to the checkbox available on the table.  The focus of the narrator moving to cell value 'Abcd' of the table. 

 #### Expected behavior:
Whenever, user navigates over the table with the narrator in scan mode and reach 'Shared' then the focus of the narrator should moves to the checkbox available on the table.
 
Note:
1. This issue does not exist with Chrome + JAWS cursor mode.

**Comment by JasonGore** [comment]
In order to help troubleshoot root cause we need some additional information implementation regarding the specific Fabric components used. Can you provide a CodePen that reproduces the issue? Thanks!
