### ISSUE TITLE
Searchbox Component - Placeholder values not getting set

### ISSUE THREAD

**Issue by AvniBhatt** [OfficeDev/office-ui-fabric-react#6694]
I am using SPFx with React. I used Searchbox with following markup:
<SearchBox               
                  placeholder="Search by Name"
                  onSearch={newValue => console.log('value is ' + newValue)}
                  onFocus={() => console.log('onFocus called')}
                  onBlur={() => console.log('onBlur called')}
                  onChange={() => console.log('onChange called')}
                />

Everything is working fine, just the Placeholder value does not change. Console.log message changes are also reflected successfully.

**Comment by KevinTCoughlin** [comment]
@AvniBhatt when you say that the placeholder value does not change, do you mean it is not rendered initially? A [Codepen](https://codepen.io/#) with a repro case would be helpful for us to debug.
