### ISSUE TITLE
The expand/collapse buttons on the DetailsList Component currently only expand/collapse the first level of groups. 

### ISSUE THREAD

**Issue by nishila2** [OfficeDev/office-ui-fabric-react#6695]
The expand/collapse buttons on the DetailsList Component currently only expand/collapse the first level of groups.  The expectation would be to expand/collapse buttons will expand/collapse the whole "tree" of groups(Nested groups too).

**Comment by dzearing** [comment]
I'm not sure if this is a bug or a limitation. I would expect a similar behavior. We will dig in and see what's up.

**Comment by nishila2** [comment]
@dzearing Thank you for your reply. When I can expect this? or Can I do anything using `onColumnClick` event of  `DetailsHeader`.

**Comment by mikewheaton** [comment]
Moving to 'Ready for Engineering', as it seems like the issue and desired behavior is clear. Let me know if a repro would be helpful here.

**Comment by natalieethell** [comment]
Hey @nishila2 thanks for submitting this issue! I'm having trouble reproducing the behavior you're describing. Here's a [CodePen](https://codepen.io/naethell/pen/EdqBLq) with a Grouped DetailsList. I'm able to collapse all nested groups by just collapsing the first level. 

I'll close this issue but feel free to re-open it if you're still experiencing this issue.

**Comment by nishila2** [comment]
What I meant was, when we expand/collapse the DetailsList by clicking the expand or collapse button at the top left it will only open the First level of the tree. I am expecting it will open all child tress too. not only the first level. that means if click that button it will open all the groups. is it clear for you @natalieethell? please re-open this issue.

**Comment by natalieethell** [comment]
@nishila2 is the top left expand/collapse button in the CodePen repro not expanding and collapsing all groups for you like this? Are you expecting other behavior? 
![detailslist groups expand collapse](https://user-images.githubusercontent.com/14134000/47924928-2ef53b80-de7a-11e8-913b-6987eb44046f.gif)
