### ISSUE TITLE
Spinner component is "shaking" in Microsoft Edge 44.17763.1.0

### ISSUE THREAD

**Issue by dlannoye** [OfficeDev/office-ui-fabric-react#6697]
### Please provide a reproduction of the bug in a codepen:
 
Load the spinner page in the latest version of Microsoft Edge 44.17763.1.0 which shipped with Windows 10 October 2018 Update.
https://developer.microsoft.com/en-us/fabric#/components/spinner

### Bug Report 
 
 
- __Package version(s)__: 6.49.2 for the uifabric.io, but have seen on 6.83.0
- __Browser and OS versions__: Microsoft Edge 44.17763.1.0
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: (Blocking, High, Normal, Low) High
 
Products/sites affected: (if applicable) All sites using spinner when visited with this version of Microsoft Edge
 
#### Describe the issue:
 The spinner will appear shake

 
#### Actual behavior:
The spinner appears to shake
![spinner](https://user-images.githubusercontent.com/1383720/46968683-b5331480-d068-11e8-889b-81a73e5a380f.gif)

 
#### Expected behavior:
 The spinner should appear as it does in other browsers.

**Comment by cliffkoh** [comment]
Further reduction: https://codepen.io/cliffkoh-the-styleful/pen/Rejdjw?editors=1100

**Comment by cliffkoh** [comment]
This is bug 19318726 reported to the Edge team. Closing as external.

**Comment by cliffkoh** [comment]
Reopen as Edge team suggested a workaround. I will submit a PR for this.
