### ISSUE TITLE
Callout: Out Of the Box Experience (OOBE), Close button, Peek

### ISSUE THREAD

**Issue by atneik** [OfficeDev/office-ui-fabric-react#67]
- This Callout could be used to draw attention to one aspect of the application during a product tour.

<img width="268" alt="screen shot 2016-08-04 at 2 05 34 pm" src="https://cloud.githubusercontent.com/assets/785361/17418364/0d575624-5a4d-11e6-8710-78b23bcbdea1.png">

- Peek: A small callout for action
- Close button to bring parity

**Comment by aksingh** [comment]
It would be great to have this particular component for building product tours conforming to a common design language!

**Comment by micahgodbolt** [comment]
This is a teaching bubble and has just recently been merged in #278
