### ISSUE TITLE
Breadcrumb: Fluent experiment

### ISSUE THREAD

**Issue by Vitalius1** [OfficeDev/office-ui-fabric-react#6701]
Update the Breadcrumb fluent styles in experiments package following the latest fluent toolkit

**Comment by betrue-final-final** [comment]
It looks like we now have an underline, because of the change to Link. Is there any way to suppress that here?
![image](https://user-images.githubusercontent.com/20363037/47365115-b4fdcf00-d68f-11e8-8813-2bd7c867307d.png)
Also note that at the small breakpoint the text weight is reduced to 300, which is in effect semilight, and the size doesn't seem to change from 18px.
![image](https://user-images.githubusercontent.com/20363037/47365225-f4c4b680-d68f-11e8-8482-810d85fc15d4.png)

**Comment by Vitalius1** [comment]
@betrue-final-final 
I fixed the underline and the font-weight. But I remember we discussed offline about font-size not changing from 18px after you talked with Christopher. Let me know if this changed as I have the breakpoints in place to make the scaling work.

**Comment by betrue-final-final** [comment]
Nice work.

**Comment by marygans** [comment]
### Fluent Updates
**Update line height for text**
- **Current**: Font size / Line-height: 18px / 36px
- **Expected (based on toolkit):** 18px / 24px 
- **ContexualMenu dropdown:** 
    - Current: Font Size / Line height: 14px / 36px
    - Expected: Font Size / Line height: 14px / 20px

**Toolkit states/variants missing (exists on site):** 
- Hover/Focus/Pressed states
- Breadcrumb with blue links
- Breadcrumbs with custom divider icons

@betrue-final-final I see that Vitalie made some font size / line height changes please confirm that I need to update to what is in the toolkit?

**Comment by betrue-final-final** [comment]
Generally Vitalie's changes were based on the realities of code, and are meant to reflect what we want visually.
Update line height for text
Font size / Line-height: 18px / 36px

ContexualMenu dropdown:
Current: Font Size / Line height: 14px / 36px

Toolkit Hover/Focus/Pressed states tracked here: https://tasks.office.com/microsoft.onmicrosoft.com/en-US/Home/Task/_EMm1z7E6UGbUiMHCBpYz5UAMt-h?Type=TaskLink&Channel=Link&CreatedTime=636967388084127238 

Items not needed in toolkit. This is by definition not toolkit work.
Breadcrumb with blue links -Not meant for toolkit as it is custom.
Breadcrumbs with custom divider icons - Not meant for toolkit by definition as it is custom.
