### ISSUE TITLE
farItems in commandbar is not working with responsive layout

### ISSUE THREAD

**Issue by shivam-dev** [OfficeDev/office-ui-fabric-react#6708]
Hi, 

I am unable to get responsive layout for commandbar, farItems are not getting collapse in mobile viewport.

In Desktop View port:

![image](https://user-images.githubusercontent.com/8074205/47014250-51434580-d167-11e8-80e7-f2ec000b0bbe.png)

In Mobile View port:

![image](https://user-images.githubusercontent.com/8074205/47014368-b1d28280-d167-11e8-812b-d9fb26f87ffb.png)

![image](https://user-images.githubusercontent.com/8074205/47014386-bf880800-d167-11e8-9fe6-c721a6b48eaf.png)

**Comment by micahgodbolt** [comment]
CommandBar doesn't have any built in collapsing of the right side items. You can either provide different items data based on your screen width, or create custom onReduceData/onGrowData to change how the command bar makes room for smaller screens (i.e. search might be the first thing to change before dropping other things into the overflow).
