### ISSUE TITLE
Slider: Fluent experiment

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#6710]
Verify that the styles checked in to the experiments package match the latest design, then assign to Ben to double-check.

**Comment by mikewheaton** [comment]
Turns out that this was in the wrong column. Design is complete, but development hasn't started yet. Unassigning it for now.

**Comment by betrue-final-final** [comment]
Looks good.

**Comment by marygans** [comment]
### Fluent Updates Needed: 
**Add slider pressed state:** 
- Current behavior: Hover and Pressed states are exactly the same (#0078d4)
-  Expected (based on toolkit): Pressed state should be a darker blue (#106ebe) than hover state (#0078d4)
