### ISSUE TITLE
Toggle: Fluent experiment

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#6712]
Verify that the styles checked in to the experiments package match the latest design, then assign to Ben to double-check.

**Comment by betrue-final-final** [comment]
Hey, just found a couple of issues.
The state text should be regular weight, not semibold.
![image](https://user-images.githubusercontent.com/20363037/47305179-81626c80-d5dd-11e8-8b5c-1fd6032a0092.png)

The thumb on unchecked hover should be #201f1e (I think that's neutralDark)

**Comment by betrue-final-final** [comment]
This looks good, except is there some way to skooch the thumb a little closer so it looks less uneven on the right or left edge? It might just be the pixels don't work out that way, but checking.
![image](https://user-images.githubusercontent.com/20363037/47368706-f47be980-d696-11e8-9133-3d3a1a84e87c.png)

**Comment by mikewheaton** [comment]
This is tricky because there is variation between browsers/platforms and so much depends on the resolution of the display. Here's what it looks like for me at 4px and 3px:

![image](https://user-images.githubusercontent.com/1382445/47376323-2b59fb80-d6a7-11e8-8be0-cb722b8cfe16.png)

**Comment by betrue-final-final** [comment]
3px looks better. Do you agree?

**Comment by betrue-final-final** [comment]
Looks good!

**Comment by marygans** [comment]
### Fluent Updates Needed: 

**Add focus to entire toggle element** 
- Current: Focus is only on the toggle switch
- Expected: Focus should be on the toggle switch + label

 **Update border color on hover Toggle OFF** 
- Current: #323130
- Expected: #201f1e (this will match the toggle thumb color)

**Label on top**
- Current: No property exist in code
- Toolkit: property exists

**Addressable existing open issue** 
- https://github.com/OfficeDev/office-ui-fabric-react/issues/6753
