### ISSUE TITLE
ITextField::blur

### ISSUE THREAD

**Issue by be5invis** [OfficeDev/office-ui-fabric-react#6713]
I am wondering why there is only `ITextField::focus` but not `ITextField::blur`...

**Comment by KevinTCoughlin** [comment]
It seems like that's because we only ever programmatically invoke `focus`. However, `ITextFieldProps` extends `React.AllHTMLAttributes<HTMLInputElement | HTMLTextAreaElement>` so `onFocus` and `onBlur` can be used via props.

**Comment by be5invis** [comment]
@KevinTCoughlin Well I do want to manually blur a text field, mainly a search box: after you hit "enter", it releases the focus.

**Comment by KevinTCoughlin** [comment]
> 
> 
> @KevinTCoughlin Well I do want to manually blur a text field, mainly a search box: after you hit "enter", it releases the focus.

Change was easy enough so I raised a PR #6856 which adds support for programmatic `blur`. Would like to add a unit test prior to merge, but otherwise should fulfill your needs.
