### ISSUE TITLE
ExampleCard: Provide prop to remove theme override

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#6716]
The ExampleCard now contains options to set a theme for the example:
![image](https://user-images.githubusercontent.com/1382445/47043465-8d17e400-d142-11e8-9ddf-8dcdfc74ddbe.png)

For the Fluent components example page (within experiments), we have the entire page wrapped in a Customizer that applies the Fluent theme. This broke recently with the addition of themes to ExampleCard, as it applies the DefaultTheme to each example and overrides the Fluent theme. I've made a quick fix for this in PR #6715.

I'd like to propose adding a prop to ExampleCard that would disable the theme functionality, allowing the parent theme to be applied as it was previously. The default behavior would be to show the theme dropdowns as they are now. Do you see any issues with this, @JasonGore?

**Comment by JasonGore** [comment]
Actually I'm not seeing a visible regression.. the tabs should be mixing in page themes and giving them priority since they're more localized. As far as I can tell the pages before and after your PR look the same. Can you show an example of a regression? Thanks

**Comment by mikewheaton** [comment]
The color changes are very slight, so you may not notice a visual change without inspecting. The way to tell the old colors from the new is that the old colors are 'pure' grays with equal amounts of red, green, and blue, while the new colors have more red.

I'm not able to build the project locally right now to confirm, but you should see the issue if you reverse the changes made in [the PR](https://github.com/OfficeDev/office-ui-fabric-react/pull/6715/files) so that ExampleCard is _inside_ Customizer. This causes the ExampleCard's theme to override the Fluent theme we had applied to the whole page.

And yes, we do want the Fluent styles to mix with themes and schemes. At some point the Fluent colors will be the default set, which could then be overridden with dark/strong/etc. We might even want to make Fluent an option in the themes dropdown, although it's a bit complex because it's both a color theme and a set of component overrides (e.g. rounded corners).

**Comment by JasonGore** [comment]
The [dropdown themes](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/experiments/src/demo/customizations.ts) are using scopedSettings and style variables, as well, so it shouldn't be a problem to add Fluent. 

I do have a fix to disable the dropdowns for the Fluent page, but the alternate solution is just to add Fluent to the dropdowns. This will affect all components, but would not appear on the live site. What do you think?
