### ISSUE TITLE
DatePicker: Add reference to input

### ISSUE THREAD

**Issue by realhoffi** [OfficeDev/office-ui-fabric-react#6727]
Requested priority: High
 
 
The Id of the Datepicker Div can be set. It was inserted by another feature of me! 
But you need to set "id"-property of the input element, to make your label with the attribute "htmlfor" working.
This is needed for good HTML and programming style like for HTMLFOR attribut in label.

So what is needed is the follwoing;

You need to make a property for the input properties of the textbox, where the date value is stored. 
So when you click the label, the datepicker dialog is opened.
this is actually already working, if you use the default label property of the control, but we have another label component.

**Comment by realhoffi** [comment]
the default label in this component is doing this :)

**Comment by JasonGore** [comment]
@realhoffi I took a look at this but I'm not sure how `DatePicker` supports a custom label. I see a hardcoded `Calendar` icon but I'm not sure how you're using a label to replace it. I'm also not sure how the default label exposes a ref as I don't see anything like that. 

Could you create a CodePen that shows an example of what you're looking for? An example of one that works (using default) and one that doesn't work (what you're looking for) would be ideal. Thanks.

**Comment by realhoffi** [comment]
The DatePicker supports the custom label by using the "label" property of your control :)

<DatePicker
          label="testlabel"
          key={this.props.inputKey}
          showWeekNumbers={true}
          firstDayOfWeek={DayOfWeek.Monday}
          value={this.state.currentValue}
          onSelectDate={this.onSelectKuendigungsdatum}
          formatDate={this.onFormatDate}
        />

**Comment by JasonGore** [comment]
It's not, however, exposing a ref, which is what I'm confused on. Again, a CodePen would really help clarify what you're looking for here (and help make sure it gets resolved.) [Here](https://codepen.io/dzearing/pens/public/?grid_type=list) are a bunch of sample CodePens to help. Thanks!

**Comment by realhoffi** [comment]
@JasonGore  i'll try actually codepen :) it's not that simple for the first time ^^

**Comment by JasonGore** [comment]
Perfect! That shows the issue perfectly, thanks.

**Comment by realhoffi** [comment]
no problem )

**Comment by JasonGore** [comment]
The PR has been merged, so [this CodePen](https://codepen.io/jasongore/pen/GYwved?editors=1010) should start working after the next release after 6.93.0. I wanted to provide an example to show that when you specify `htmlFor` you have to append `-label` to whatever `id` you pass in to `DatePicker`.

**Comment by rborosak** [comment]
@JasonGore  I know this issue is closed but this approach of adding "-label" internally is in my opinion wrong. 
I'm using DatePicker with Formik. In order for Formik to know which value to update I need to pass "name" or "id" attribute to my input. Since DatePicker does not contain "name" prop I'm left with id which in my case is worthless because the component adds a '-label' suffix. Is there any way to avoid this suffix?

**Comment by cliffkoh** [comment]
Hi @rborosak, could you open a new issue to help ensure your enquiry gets the right amount of attention? You can link to this issue in your new issue.
