### ISSUE TITLE
Website not loading in IE11

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#6728]
### Bug Report 

- __Package version(s)__: Latest
- __Browser and OS versions__: Windows IE 11
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Blocking
 
Products/sites affected: Fabric website
 
#### Describe the issue:
 
The Fabric website is not loading in IE 11 because we're using [object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) somewhere. Here is the console error: 

`Object doesn't support property or method 'assign'`

I recall this coming up before and thought it was fixed, but haven't been able to find an issue for that to re-open. It's also possible that this was fixed and just hasn't been deployed yet.
 
#### Actual behavior:
 
The website doesn't load.
 
#### Expected behavior:
 
The website loads.

**Comment by cliffkoh** [comment]
@mikewheaton FYI Rank is for features, Priority is for bugs :)

**Comment by cliffkoh** [comment]
On my machine, it looks like the error comes from tslib but that should not be the cause.. Otherwise, peoplepicker.types,example is the only direct object.assign usage but that has been there for over a year...

**Comment by cliffkoh** [comment]
Hey @mikewheaton  @Jahnp , the website is super duper old (over 2 months). Looking at the existing code, this should not happen. In fact, the local copy works fine with IE 11.

Did you know if we roll backed to 6.49.2 recently? I think we hit this problem before and @JasonGore had deployed a fix before..

**Comment by Jahnp** [comment]
Hey @cliffkoh , we rolled back during the last week of September since the site infra had not yet been updated to use React 16.3, which caused the site to not render in any browser. Those updates went through on Monday, and we're in the process of actually updating the site to use the new pipeline. I'd expect it to be updated within the next few hours; I'll revisit this issue then.

**Comment by Jahnp** [comment]
This was also brought up in #6668 , which we closed due to imminent updates that took a little longer than expected. I'm going to keep this open until I've verified the latest is published.

**Comment by mikewheaton** [comment]
The site has been updated and I've verified that it's loading in IE11. Thanks, @Jahnp!
