### ISSUE TITLE
ContextualMenu: Update examples to better show component usage

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#6729]
Currently contextual menu examples are just <Button>s with menuProps. While this provides simplified code and demos a good way to take advantage of the control, it's not a very good example for those wanting to learn about the control.

I'd like to have the following:

1. A contextual menu rendered to the page. No state, no target. Just Show what it looks like.
2. A simple stateful example of showing/hiding a contextual menu
3. An example of a contextual menu via Button with MenuProps (so people know they dont' have to manage the state themselves if they just need a button with a menu) - Maybe even show multiple button types and how a contextual menu looks on those different types.

**Comment by khmakoto** [comment]
This has already been fixed, most recently by #11736.
