### ISSUE TITLE
Slider: Use up and down arrow keys to change number of slider should also work (blind user can’t see that the control is horizontal).

### ISSUE THREAD

**Issue by gggjtgxing** [OfficeDev/office-ui-fabric-react#674]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Describe the issue:

 Slider: Use up and down arrow keys to change number of slider should also work (blind user can’t see that the control is horizontal).

#### Actual behavior:

User can only use left and right arrow keys to change number of Slider,

#### Expected behavior:

Use up and down arrow keys should also work

### If applicable, please provide a codepen repro:

**Comment by dzearing** [comment]
This was published in 0.82.0.
