### ISSUE TITLE
Dialog: Fluent theme

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#6742]

**Comment by betrue-final-final** [comment]
Alright, change list:
Bottom margin > 24px
Left margin > 24px
Right margin for buttons > 24px
Right margin for Close X > 14px
Close X dimensions > 32x32px
Close X glyph color > PaletteColors.neutralSecondary
The color one might be an issue as it's using icon button I believe.

**Comment by betrue-final-final** [comment]
Looks good.

**Comment by maxwellred** [comment]
### Fluent Updates

- I'm assuming all the dimension diffs are correct live but I thought i'd flag them for updating in the toolkit.

**Toolkit Issues**
- **Title Top Padding:** Live = 16px / TK = 14px
- **SubText Left/Right Padding:** Live = 24px / TK = 22px
- **SubText Bottom Margin:** Live = 20px / TK = 19px
- **Large Header Example:** Live but not found in toolkit
     - Live under "Dialog" > "Variants" > "Dialog with large header and ChoiceGroup"
![Screen Shot 2019-06-27 at 2 59 18 PM](https://user-images.githubusercontent.com/13246181/60303787-3a571480-98ec-11e9-9bb9-49be10831c40.png)

**Dialog Panel conversion at 320-479px breakpoint**
- In Dialog toolkit under "Small"
- I'm not seeing this as part of the code

@betrue-final-final please let me know which of these changes are required
