### ISSUE TITLE
Link: Fluent theme

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#6746]

**Comment by marygans** [comment]
TODO:  Update disabled state text to gray as design toolkits reflect a gray vs. current blue state
![disabled-link-mismatch](https://user-images.githubusercontent.com/38991459/58512083-0eac0780-8151-11e9-994e-b2266e475073.png)
color

**Comment by khmakoto** [comment]
This has been fixed. Closing.
