### ISSUE TITLE
ComboBox: Fluent theme

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#6748]
Add styles to the Fluent theme for ComboBox.

**Comment by mikewheaton** [comment]
Looks like @Vitalius1 already made the style updates here and it's ready for design review.

**Comment by betrue-final-final** [comment]
This looks good.

**Comment by Vitalius1** [comment]
@betrue-final-final 
@mikewheaton and I were just looking at ComboBox and it looks like it's not fluentized completely. We are pulling it from done and throw back on building column.

**Comment by Vitalius1** [comment]
@betrue-final-final 

1. ComboBox does not have a way to know where it renders the callout, on top or below the input, so I rounded all 4 corners for now. 
2. I noticed an issue with the shadow on ComboBox and Dropdown. If the callout is on top of the input, because the fluent shadow it's bigger at the bottom edge of the callout, you can see how it overlaps on the input. Don't know if this is an issue or not...
3. Also, notice how the chevron button on the ComboBox has it's own hover/active background states which is not present in the dropdown. Do we need to change either of them to be consistent?

**Comment by betrue-final-final** [comment]
This looks fine.

**Comment by maxwellred** [comment]
### Fluent Updates

- Just a friendly reminder that per our conversation, I've done the code comparison off of the Dropdown toolkit

**Code diff Issues**

-**Border color in "-Focus" state:** Live = 0078d4 / TK = A19F9D
-**Text color in "-Focus" state:** Live = 323103 / TK = 201F1E 
-**Border color in "-Hover" state:** Live = 000000 / TK = 0078d4
-**Text color in "-Pressed" state:** Live = 323130 / TK = 201F1E
-**Border color in "-Open" state:** Live = 0078d4 / TK = a19f9d
-**Border color in "-Error" state:** Live = d13438 / TK = c50f1f
-**Chevron icon color in "-Error" state:** Live = 605e5c / TK = a19f9d
-**Error message color in "-Error" state:** Live = a4262c / TK = a8000
-**Error message font size in "-Error" state:** Live = 14px / TK = 12px
-**Callout menu header font size** Live = 14px / TK = 12px
-**Callout menu box-shadow** Live = elevation16 / TK = elevation8
-**Checkbox list item background in "-Hover" state** Live = f3f2f1 / TK = white
-**Checkbox list item text color in "-Pressed/Selected" and "-Selected Hover" state** Live = 323130 / TK = 201f1e
-**Checkbox list item border color in "-Focus" state** Live = none / TK = 605e5c (on the checkbox standalone component, however, there is a border)
-**Checkbox list item behavior** When you tab to a check box, select it (with Enter), you cant toggle it off without navigating up or down (with arrow keys) to a different checkbox and then back and pressing enter again. This also causes a background highlight as if it's being hovered on. Is this intended behavior?
-**CommandButton list item text color in "-Focus" state** Live = black / TK = 323130
-**CommandButton list item text color in "-Selected" state** Live = black / TK = 201f1e

-**IconButton menu button:** Should I be comparing against the menu button in the Dropdowns and Text Fields > Dropdown toolkit or the Buttons > Icon Dropdown toolkit?

**Toolkit Issues**

- **Border color in "Standard" and "Standard with label" variants is listed as pure black and is this supposed to be 323130? (location = Basic Inputs > Dropdowns and Text Fields > Dropdown)

@betrue-final-final  please let me know which of these changes are required
