### ISSUE TITLE
ContextualMenu: Fluent theme

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#6749]

**Comment by Vitalius1** [comment]
@betrue-final-final 
I have a PR for ContextualMenu. I have a lot of tiny tweaks in the attempt to follow the toolkit so a very granular check would be much appreciated.
Also, if you look on the example page we have a couple ones that are not covered by the toolkit like `secondaryText`, the color of the item text if it has a subMenu and it's expanded, split button with a pipe divider. In case I need to change anything for this uncovered cases let me know and I will update this PR with them.

**Comment by betrue-final-final** [comment]
We'll definitely want an update for secondary text and for the split button case. The current Master has a misalignment for example:
![image](https://user-images.githubusercontent.com/20363037/48229764-e2b86880-e35d-11e8-82db-b198bd7e0c11.png)

**Comment by Vitalius1** [comment]
@betrue-final-final 
Let me know when you have an update in the toolkit for the secondary text and for the the alignment you mentioned above (are we moving the chevron of the split button or the other ones?). I will submit a separate PR for it along with the fixes for Pivot animation timing.

**Comment by betrue-final-final** [comment]
Done, for posterity, even though we talked about this last week!

**Comment by marygans** [comment]
### Fluent Updates found in Breadcrumb
ContexualMenu dropdown:
Current: Font Size / Line height: 14px / 36px
Expected: Font Size / Line height: 14px / 20px

**Comment by Vitalius1** [comment]
@marygans I believe the line height is there to keep the total heigh of the contextual menu item. Same was done I think in Breadcrumb..., but I will be happy to review the changes you would make to fix this. It might not be worth it if it brings more complexity to styles because if you make the line height smaller you'll have to deal with centering the text. Let me know and we can take a look together.

**Comment by marygans** [comment]
Thanks @Vitalius1 for providing further context on this! I agree that we shouldn't be adding complexity to styles. I believe @maximus12793 will be working on this item for Fluent updates. Either way, we'll make sure you're looped in.

**Comment by maxwellred** [comment]
### Fluent Updates

**Diffs between Toolkit (TK) and Live**

-**List Item Split Button:** When primary button of split button checked, hover no longer results in background color change. Intended functionality?
-**List Item Split Button:** Hover State highlights entire list item. Would you rather it mimic the split button variant of the button component where the primary button is the only component highlighted?

** Toolkit Error **

-**Pressed-Selected State Icon Color:** Location: "Menu Selection Group With Icons" - Currently #0078D4 -> Should be?: #005A9E
-**Pressed-Selected State Check Color:** Location: "List Item Selection With Icon  (Size: M-S)" - Currently #323130 -> Should be?: #000000
-**Arrow Icon Colors:** Location: "List Item Split Button" - TK Colors in various states inconsistent

@betrue-final-final please let me know which of these changes are required

**Comment by betrue-final-final** [comment]
-List Item Split Button: When primary button of split button checked, hover no longer results in background color change. Intended functionality? **This is correct.**
-List Item Split Button: Hover State highlights entire list item. Would you rather it mimic the split button variant of the button component where the primary button is the only component highlighted? **Yes, and I'll correct the toolkit.**

** Toolkit Error ** Tracked here: https://tasks.office.com/microsoft.onmicrosoft.com/en-US/Home/Task/jkbjd2AinkO1pjuEnWnG4JUAEn7p?Type=TaskLink&Channel=Link&CreatedTime=636967377164912923 

-Pressed-Selected State Icon Color:  #005A9E
-Pressed-Selected State Check Color: #323130 - Correct in TK
-Arrow Icon Colors: Location: "List Item Split Button" Rest: #605E5E, Hover, Pressed #323130
