### ISSUE TITLE
Dropdown: unable to be notified when an item has been reselected

### ISSUE THREAD

**Issue by janormanms** [OfficeDev/office-ui-fabric-react#6759]
### Bug Report 
 
- __Package version(s)__: 6.74.0
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal
 
Products/sites affected: Outlook
 
#### Describe the issue:
 
In single select mode Dropdown only calls onChanged when the selected index has actually changed (first if block in Droddown.setSelectedIndex).

For our UI we'd like to be notified whenever an index is selected, even if the user is reselecting the current value.
 
#### Actual behavior:
 
User selects a value from a Dropdown, onChanged is called
User re-selects that value, no callback exists to be notified of that selection
 
#### Expected behavior:
 
Some way to be notified whenever an item is selected, even if it is the same value. Either a new callback or a notifyOnReSelect: bool in the props which can allow onChanged to be called.

**Comment by cliffkoh** [comment]
Please feel free to submit a PR :) I might put this change in behavior behind a flag though, just in case there are some teams already depending on the fact it does not notify on reselect.
