### ISSUE TITLE
@uifabric/charting folder does not exist

### ISSUE THREAD

**Issue by vasdhara** [OfficeDev/office-ui-fabric-react#6770]
### Please provide a reproduction of the bug in a codepen:
 `Module not found: Can't resolve '@uifabric/charting/lib/LineChart'`

### Bug Report 
 
- __Package version(s)__: 6.88.0 
- __Browser and OS versions__: not relevant
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Blocking
 
Products/sites affected: not applicable
 
#### Describe the issue:
 
 After adding office-ui-fabric-react using npm --save install office-ui-fabric-react the @uifabric folder under node_modules does not have a charting folder and hence none of the components are found
 
#### Actual behavior:
 
Module not found: Can't resolve '@uifabric/charting/lib/LineChart'
 
#### Expected behavior:
 Line Chart should display with component loaded

**Comment by cliffkoh** [comment]
You should install, i.e. `npm install --save @uifabric/charting`, anything you're directly using as a first class dependency.

If hypothetically `@uifabric/charting` was also installed, this would be what the Rush team calls a "phantom dependency" that is extremely fragile.

**Comment by micahgodbolt** [comment]
Charting is not a dependency of office-ui-fabric-react. As cliff said, you need to install it directly into your application.
