### ISSUE TITLE
Panel: Support custom 'near' Panel

### ISSUE THREAD

**Issue by hamedy** [OfficeDev/office-ui-fabric-react#6772]
hi, I need to set the styling on Panel so that it slides in from the left side. IPanelStyleProps has a property called isOnRightSide that I believe would do it. But I can't figure out how to implement it. Can someone provide an example please?

**Comment by hamedy** [comment]
yes, but I need custom width, and the only option for custom width is sliding from the right side. And in general I find this interface that's used for Styles on a lot of components quite confusing:
IStyleFunctionOrObject<IPanelStyleProps, IPanelStyles>

can't figure out how to use it. how would one create a simple object that implements IPanelStyleProps and set a property like isOnRightSide? 

Appreciate your help :)

**Comment by micahgodbolt** [comment]
Yeah, looks like custom is on the 'far' side. We'd need to change the component to be able to support this. We probably need a customNear type, since supporting every 'type' with 'near/far' is probably a large refactor.

**Comment by hamedy** [comment]
what would you say is the better way to make the smallfixednear type a bit wider?

**Comment by micahgodbolt** [comment]
blast, nevermind….even each of the individual sizes has media queries in them....

**Comment by micahgodbolt** [comment]
Ok, without a major rewrite of a bunch of panel innards I'd say a customNear is the best approach. You could easily put a regular 'custom' on the left hand side...but the drop shadow would be wrong

**Comment by hamedy** [comment]
could you explain how, please?

**Comment by jumpmanjay** [comment]
I set some css to override-

`.root-59 .main-103 {
  width: 500px;
}`

But it's a bit janky as the animation isn't smooth. A proper fix would be great.

**Comment by MarcOne68** [comment]
I had the same issue.
I resolved using **styles** property and **IPanelStyles** interface setting

`main: { width: '600px !important' }`

**Comment by MarcOne68** [comment]
I had the same issue and I resolved using **PanelType.smallFixedNear** and setting styles property to 

`{ main: { width: '500px !important' } }`

You must work only on the media queries

**Comment by micahgodbolt** [comment]
similar to #6658 i think panel needs to be split into a generic container and the Panel as it is today. This will allow the underlined panel base to support any position while the Panel control will contain styles required to support positions described in our style guide.

**Comment by xugao** [comment]
closing this as it's tracked in #7625
