### ISSUE TITLE
Website: Feedback button styles are conflicting with UHF styles

### ISSUE THREAD

**Issue by lynamemi** [OfficeDev/office-ui-fabric-react#6782]
### Bug Report 
 
We've historically had problems with buttons as links picking styles up from stylesheets the UHF brings with it. Looks like it struck again.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable) Demo website
 
#### Describe the issue:
 
![screen shot 2018-10-19 at 4 20 18 pm](https://user-images.githubusercontent.com/16619843/47247872-0ae62480-d3bb-11e8-9762-38fbbf4fca1f.png)

Text in the button should be white

**Comment by Jahnp** [comment]
Apologies for the delay here. The bug is a result of MWF styling bleeding into that specific button, which happens to be on every control page 😊 I've sent mail to the developer.microsoft.com team asking for a fix. I'll follow up when I learn more.

**Comment by lynamemi** [comment]
Yeah, previously I was adding specific selectors to every link on the website, which is not ideal in the least! Hopefully they'll finally get a fix for you.

**Comment by micahgodbolt** [comment]
does #6960 fix this issue? it still seems to be dark text

![image](https://user-images.githubusercontent.com/1434956/50529448-b5f51780-0aa9-11e9-985d-39dad4a89766.png)

**Comment by Jahnp** [comment]
Yup, this unfortunately does still repro. Turns out the overrides I submitted weren't high enough priority. I've submitted another, #8122, that should hopefully address the issue.
