### ISSUE TITLE
No Footer in Panel with V6.89.0 in IE10

### ISSUE THREAD

**Issue by hohenp** [OfficeDev/office-ui-fabric-react#6786]
The Footer in Panels is not visible with IE10 at Version 6.89.0
It was correct in Version 6.72.0, I assume the scrollable Feature causes side affects.

Thanks
Pascal

**Comment by micahgodbolt** [comment]
IE 10 is not one of our supported browsers. Are you able to reproduce this bug in IE11?

https://github.com/OfficeDev/office-ui-fabric-react/wiki/Browser-Support
