### ISSUE TITLE
Pickers: Tag picker menu text is incorrectly blue on hover

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#6790]
Fabric 6.0
Repro:
1. Go to Pickers 
2. Type in the Tag Picker
3. Hover over an item 

Result: Text turns blue
Expect: Text should remain neutral
![image](https://user-images.githubusercontent.com/20363037/47311906-ce4f3e80-d5ef-11e8-8abe-40744c8dabc6.png)

@joschect believes this is because it uses buttons.

**Comment by cliffkoh** [comment]
Co-assigning @khmakoto because this might be a good one for him to investigate and work on as well.

**Comment by joschect** [comment]
@cliffkoh I got this one, I already fixed in 5.0 and I'll fix it here too.
