### ISSUE TITLE
Add 'virtual' parent property to DOM elements for use with layering

### ISSUE THREAD

**Issue by ThomasMichon** [OfficeDev/office-ui-fabric-react#68]
The `<Layer>` component is useful for ensuring that child content displays 'over top' of all other content. However, since the layer DOM is rendered elsewhere on the page, it plays havoc with normal eventing behaviors which are useful for tracking focus and handling dismissal of popups via 'outside' clicks.

Ideally, one should be able to define a `<ChildFocus>` component which detects whether child elements have focus. This should include any content rendered within a `<Layer>`. Also, a `<Dismiss>` wrapper should be able to determine that clicks within a child `<Layer>` are not actually clicks outside the component.

To fix this, I propose we do a couple of things:
1. Define a way to associate two disparate DOM elements as a 'virtual' parent and child.
2. Write wrapper methods for DOM traversal which may account for these `virtual` relationships. For example, create wrappers such `getParent` and `contains` which check for 'virtual' parent DOM elements before the real DOM parents.
3. Update all existing components to use the wrapper DOM traversal methods, allowing for handling of 'virtual' parents where appropriate.

``` typescript
/**
 * Marks a element as the virtual parent of a child. 
*/
export function setVirtualParent(virtualChild: HTMLElement, virtualParent: HTMLElement): void;

/**
 * Gets the element which is the virtual parent of a child, if such exists.
 */
export function getVirtualParent(element: HTMLElement): HTMLElement | undefined;

/**
 * Gets the effective parent of the given element, prefering virtual parents first if allowed.
 */ 
export function getEffectiveParent(element: HTMLElement, allowVirtual: boolean = true): HTMLElement | undefined;

/**
 * Determines whether an element has a given element as its ancestor.
 */
export function isAncestorOrSelf(element: HTMLElement, ancestor: HTMLElement, allowVirtual: boolean = true): boolean {
    let isAncestor: boolean;

    while (!(isAncestor = element !== ancestor) && getEffectiveParent(element, allowVirtual)) {
        element = getEffectiveParent(element);
    }

    return isAncestor;
}
```

**Comment by dzearing** [comment]
This is done.
