### ISSUE TITLE
Moving the mouse outside the dropdown container, the drop down list autoscrolls

### ISSUE THREAD

**Issue by lampropoi** [OfficeDev/office-ui-fabric-react#6803]
I have a list with many options and I render it by using the `Dropdown` component. 

When, I have the drop down list open then scroll down and afterwords hover on the `.ms-Dropdown-title` item or at the bottom of the container, the list auto-scrolls so as any item that is half visible, to be displayed. 

There are also times that the list auto-scrolls almost half the options' container height. This seems to happen when you have selected an option from the list and you mouse out the container. 
 
Can we somehow stop that auto-scroll cause the overall experience is distrusting for the eye?

Version of  `office-ui-fabric-react: 6.91.0`

Thank you!

**Comment by lampropoi** [comment]
Cool, I found the solution :D
I had to override the styling of the class `.ms-Callout-main` 

Closing the issue!

**Comment by cliffkoh** [comment]
Hi Lampropoi, I cannot repro the behavior you describe. Could you please provide more information including the browser, operating system as well as providing a GIF which captures the behavior you're seeing?
