### ISSUE TITLE
Making a group header a row 

### ISSUE THREAD

**Issue by assafushy** [OfficeDev/office-ui-fabric-react#6804]
Hi all,
i am implementing groupList  in my app(vsts extension). 
is there a way to make the group header, a regular row like the vsts lists.

![image](https://user-images.githubusercontent.com/7502687/47368544-82cd8b00-d6ea-11e8-94e4-5278d1ac95c9.png)

**Comment by micahgodbolt** [comment]
If you have access to teams, look for Microsoft UI Fabric team, that's a great place for question as well. 1000+ people in there. Feel free to ping me there if you post the question. I have a few followup questions of my own.

As cliff mentioned, our issue queue is focused on bugs and feature requests.

**Comment by assafushy** [comment]
thnks guys....
posted on stackoverflow if you can help i will appricate it:

https://stackoverflow.com/questions/52955902/react-fabric-ui-grouplist-component-getting-the-header-to-look-and-act-like-r
