### ISSUE TITLE
DetailsList documentation does not mention onRenderItemColumn

### ISSUE THREAD

**Issue by petercutting** [OfficeDev/office-ui-fabric-react#6805]
I am looking here
https://developer.microsoft.com/en-us/fabric#/components/detailslist#Implementation

**Comment by cliffkoh** [comment]
I see it here: 
![image](https://user-images.githubusercontent.com/1003246/47381036-bc36d400-d6b3-11e8-9c53-a6721e2683d7.png)

**Comment by KevinTCoughlin** [comment]
> 
> 
> I see it here:
> ![image](https://user-images.githubusercontent.com/1003246/47381036-bc36d400-d6b3-11e8-9c53-a6721e2683d7.png)

Same

**Comment by petercutting** [comment]
Yes I see it now in FireFox but for some reason its not appearing in Chrome

**Comment by KevinTCoughlin** [comment]
> Yes I see it now in FireFox but for some reason its not appearing in Chrome

If you run into it again please let us know. Perhaps it is a regression in the browser. Chrome `Version 69.0.3497.100` rendered it OK for me.

We appreciate the report @petercutting 👍.
