### ISSUE TITLE
ComboBox: Convert to new CSS-in-JS pattern

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#6806]
**Describe the feature that you would like added**
ComboBox currently uses the `@customizable` decorator, instead of the new `styled` function with a `ComboBox.base.tsx` file. I'm going to convert it to the new pattern so that it can be overridden with the Fluent theme in #6748.

**What component or utility would this be added to**
ComboBox

**Comment by JasonGore** [comment]
In light of #5205, consider merging ComboBox and Dropdown to resolve this issue.

**Comment by mikewheaton** [comment]
I'm going to close this issue, as it was opened because I mistakenly thought that components using `@customizable` couldn't be overridden with the Fluent them. They can, so there's no need to convert it as part of this project.
