### ISSUE TITLE
[Checkbox] - key repeat allows rapid update of control

### ISSUE THREAD

**Issue by daweffe** [OfficeDev/office-ui-fabric-react#6811]
### Bug Report

- __Package version(s)__: 6.55
- __Browser and OS versions__: all

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: High

Products/sites affected: Planner

#### Describe the issue:

When the checkbox is selected, holding down the enter key results in rapid updates of the control. In Planner, this resulted in a customer queuing updates such that we were unable to fail over our service. THIS IS A HIGH PRIORITY because it could keep us from failing over in the case of an outage.

#### Actual behavior:

Click on check box and hold down enter - update repeats

#### Expected behavior:

Update should not repeat if key is held down.

**Comment by dzearing** [comment]
This looks due to Checkbox rendering using a native `button` rather than `input type='checkbox'`. The `button` default supports rapid fire `onClick` calls, whereas `input` elements do not react to the enter key.

**Comment by daweffe** [comment]
So should I change to input type='checkbox'? We probably still want the enter key to work, just only once per press.

**Comment by daweffe** [comment]
Hmm, doing that breaks a lot of behavior we get for free with button.

**Comment by KevinTCoughlin** [comment]
As a workaround is it possible for the implementer to _throttle_ the callback?

**Comment by dzearing** [comment]
Yes @daweffe you should work around this by just debouncing your API call for sure. I'm not sure we should fix the checkbox here; it could potentially break partners.

You're free to use `Async.debounce` in `@uifabric/utilities` to create a debounce callback.

**Comment by dzearing** [comment]
It's possible we could change to an `input` but it's pretty risky.

**Comment by daweffe** [comment]
Yeah I could probably do that. It's not great, but I understand how risky this change could be. Could we update documentation to indicate that the onChange callback should be debounced? We could also consider debouncing it here in fabric.

**Comment by micahgodbolt** [comment]
Sorry...jumped the gun on the title rewrite. Should this simply be docs, or do we want to consider adding debounce to the component?

**Comment by micahgodbolt** [comment]
@daweffe were you able to fix this with a debounce?

**Comment by daweffe** [comment]
I did not get around to fixing this on our end.

**Comment by cliffkoh** [comment]
#7521 has a permanent fix for this issue. Debounce is no longer necessary.
