### ISSUE TITLE
Buttons: Fluent experiment

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#6813]
The design is ready in the latest toolkit. I'm putting these two components into one issue because they are treated as variants of a single component by the designers.

**Comment by mikewheaton** [comment]
While there are several button components, they all inherit styles from the default button and need to be done at once. I'm going to close the related issues and use this to track all Fluent button styles.

**Comment by betrue-final-final** [comment]
Looks good.
