### ISSUE TITLE
DetailsList: onRenderRow is never passed defaultRender

### ISSUE THREAD

**Issue by cschleiden** [OfficeDev/office-ui-fabric-react#683]
### Bug Report

- __Package version(s)__: master

#### Describe the issue:

`onRenderRow` is defined as 

```
  /**
   *  If provided, will allow the caller to override the default row rendering.
   */
  onRenderRow?: (props: IDetailsRowProps, defaultRender?: (props: IDetailsRowProps) => JSX.Element) => JSX.Element;`
```

in the .props file. `defaultRender`, however, is never passed at [runtime](https://github.com/OfficeDev/office-ui-fabric-react/blob/5332954b1127f5d1528eac95b5efaf8094fcb91f/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.tsx#L348).

Either we should pass `defaultRender`, or remove this parameter from the `.props` file. Given that there is the `DetailsListRow` component, I'd say to remove the `defaultRender` parameter.

**Update**: or maybe switching over to the `IRenderFunction` interface and actually passing `defaultRender` would align better with the rest of the components.

**Comment by dzearing** [comment]
100% agree. We'll fix the example as well here.
