### ISSUE TITLE
ActionButton: Add primary variant

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#6833]
**Describe the feature that you would like added**
The designs for ActionButton call for a Standard and Primary variant, as well as two different sizes of icon:

![image](https://user-images.githubusercontent.com/1382445/47446704-a3402880-d770-11e8-89cc-314d1af257cb.png)

**What component or utility would this be added to**
ActionButton

**Have you discussed this feature with our team, and if so, who**
Ben and Christopher

**Comment by micahgodbolt** [comment]
Good candidate for #6134

**Comment by mikewheaton** [comment]
I completed a full audit comparing the Fluent toolkit to Fabric React and found many issues like this one. Speaking to design, it's not clear which variants are actually intended to be in Fabric and which are product-specific modifications. I'm going to close this for now since it's unclear what should be done. I've suggested we treat identifying and fixing these gaps between design documentation and Fabric React as its own project.
