### ISSUE TITLE
Button: Add support for style props/functions

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#6837]
**Describe the feature that you would like added**
@Vitalius1 and I have been investigating adding button styles to the Fluent theme. These styles need to use colors from the theme palette, which is being applied via a Customizer.

Most components have a `styles` prop of type `IStyleFunctionOrObject<IComponentStyleProps, IComponentStyles>`. This allows us to provide a function to override the component's styles, and that function has access to the current theme.

Button has a `styles` prop of type `IButtonStyles`, which takes an object that is not aware of the current theme. It looks to us like the button components need to be updated to support the same style functions as the other components. 

**What component or utility would this be added to**
All of the Button components (PrimaryButton, DefaultButton, CompoundButton, etc.)

**Additional context/screenshots**
See the repro here: https://codesandbox.io/s/qq09y2w0vj

**Comment by mikewheaton** [comment]
I've run into this issue again for `CompoundButton`, where I want to apply styles specific to the case where the `primary` prop is `true`. My workaround for now is to use selectors to target the modified class name, but we should have a way to do this without targeting class names.

Here's a repro: https://codesandbox.io/s/n079nl6vl0

**Comment by micahgodbolt** [comment]
This issue is already part of the button refactor that @dzearing is working on. #6134
