### ISSUE TITLE
DatePicker: infinity loop if set InvalidDate value

### ISSUE THREAD

**Issue by biogenez** [OfficeDev/office-ui-fabric-react#685]
#### Describe the issue:
Infinity loop occurs, if set Invalid Date as value for DatePicker.

**Example**
```js
let d = new Date("beer"); //=> Invalid Date
...
<DatePicker value={d} strings={DayPickerStrings} placeholder='Select a date...' onSelectDate={this._onDateChanged} />
```

**Bug row**
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx#L180

**Infinity loop**
```
  // Cycle the date backwards to get to the first day of the week.
    while (date.getDay() !== firstDayOfWeek) {
      date.setDate(date.getDate() - 1);
    }
```
date.getDay() is NaN

**Check if date is invalid** 
```js
IsNaN(d) // true
```

**Comment by dzearing** [comment]
@amygl or @MLoughry could one of you take a quick look

**Comment by MLoughry** [comment]
I'll take it
