### ISSUE TITLE
[Functional- Power Apps Admin - Table] No horizontal scroll bar is present to scroll page horizontally with mouse on DATA integration screen.

### ISSUE THREAD

**Issue by sonimishra** [OfficeDev/office-ui-fabric-react#6860]
### Bug Report 

User Experience:  
Mouse user will not be able to scroll horizontally if there is no horizontal scroll bar present. Hence mouse user will not be able to access complete information on the table.
 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low)  Blocking
 
Products/sites affected: (if applicable)
 
#### Describe the issue:
 Repro Steps:
1.  Navigate to https://admin.powerplatform.microsoft.com/ext/DataIntegration  and login with intusr.
2. Navigate to the Data Integration menu item on the left bar and select it.
3. Navigate on the controls of data integration page thus opened. Navigate through the screen and the table.
4. Verify if there is a 'horizontal' scroll bar present to scroll page horizontally. 

 #### Actual behavior:
 No horizontal scroll bar is present to scroll page horizontally with mouse. No other way is present to horizontaly scroll the screen via mouse.

 #### Expected behavior:
 Horizontal scroll bar should be present so that user using mouse can scroll the screen to access complete information on the table

Note:
This issue also exist with Chrome.

**Comment by micahgodbolt** [comment]
@sonimishra can you ping me in teams? my Alias is mgodbolt.

**Comment by sonimishra** [comment]
+Prateek
