### ISSUE TITLE
DefaultButton: Styles don't apply correctly when 'primary' prop is used

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#6867]
### Bug Report 

- __Package version(s)__: Latest
- __Browser and OS versions__: All
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Maybe
 
Requested priority: Normal
 
Products/sites affected: Fluent theme
 
#### Describe the issue:
 
In the examples we create a primary button like so:

```
<DefaultButton primary={true} .../>
```

This usually gives the same result as using the `PrimaryButton` component. However, when a theme is set that applies styles to default and primary buttons, the styles are not mixed correctly for a `DefaultButton` where `primary` is true.

See the [repro here](https://codesandbox.io/s/wwwklx6nnw).

Is this a bug, or should we just update the docs to use the `PrimaryButton` component instead of this prop?
 
#### Actual behavior:
 
![image](https://user-images.githubusercontent.com/1382445/47579079-e1b81d80-d8ff-11e8-8353-1897a321bb3b.png)
 
#### Expected behavior:

![image](https://user-images.githubusercontent.com/1382445/47579103-f4caed80-d8ff-11e8-8ddf-b649e188a959.png)

**Comment by cliffkoh** [comment]
Assigning to @dzearing as he most recently took stock of the state of the buttons and rewrote buttons in experiments.

**Comment by dzearing** [comment]
@mikewheaton Should we make styles the function as stated above? Then you could customize DefaultButton and target props.primary. If you don't need this as a short term solution, let's close the bug and focus on shipping the rewrite. Otherwise we'll prioritize a targeted fix here.

**Comment by mikewheaton** [comment]
@dzearing This is preventing the Fluent theme from delivering on the promise of 'just wrap a Customizer around your existing app'. WIthout a fix, developers will have to replace `<DefaultButton primary={true} .../>` with `<PrimaryButton .../>`.

I'm not sure how much effort is required for a targeted fix, but unless it's going to take a lot of work and the new button is nearly ready to ship I think it's worthwhile to make the fix.

**Comment by dzearing** [comment]
We will make a workaround here for a short term fix.
