### ISSUE TITLE
Calendar - "Go to Today" button doesn't do anything when on current month

### ISSUE THREAD

**Issue by amygl** [OfficeDev/office-ui-fabric-react#6873]
### Environment Information 

Repro: 
https://fabricweb.z5.web.core.windows.net/oufr/6.93.0/#/examples/calendar

#### Actual behavior:

If on a different month the "Go to Today" button will navigate calendar to current month. But if on the month that contains today, clicking the button will do nothing.

This came up during an accessibility test pass. Narrator announces the "Go to Today" as a button "but it is non-interactable, this will confuse users who are unable to select with the keyboard." Note, this is not being tracked as an accessibility bug, it is for usability.
 
#### Expected behavior:
 
The "Go to Today" button will be disabled or hidden on the current month.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No
 
Requested priority: (Blocking, High, Normal, Low) Normal
 
Products/sites affected: (if applicable) Planner

**Comment by JasonGore** [comment]
This bug needs action but we need to determine whether the resolution is to disable or hide the button. Chatting with @lorejoh12 for the Calendar designers to determine whether the resolution is to hide or disable the button.

**Comment by dzearing** [comment]
@JasonGore @lorejoh12 Looks like this bug fell off the radar; any updates here?

**Comment by lorejoh12** [comment]
Sorry about that! We actually fixed this quite a while ago, looks like we forgot to link this bug to the PR. 

commit: 6ec50ae10f305a68c60220764745e8d971af28d7 #6938

**Comment by dzearing** [comment]
Closing the issue; @amygl let us know if you run into this again. :)
