### ISSUE TITLE
Slider step calculation is wrong

### ISSUE THREAD

**Issue by Rafaelki** [OfficeDev/office-ui-fabric-react#6877]
### Please provide a reproduction of the bug in a codepen:

https://codepen.io/rafaelki/pen/QZoWRG
 
#### Actual behavior:
 
Min, Max and Step values being ignored when Step is not is not a multiple of Max, even if Step is multiple of (Max - Min).

In the codepen example, the attributes are Min=18, Max=48, Step=10 but the control renders a minimum of 20 (thumb is not in the left border) and maximum of 50 (thumb is outside in the slider!)
 
#### Expected behavior:
 
The slider should render a minimum of 18, a maximum of 48 and have steps of 10, ie. the possible values should be 18, 28, 38 and 48.

**Comment by JasonGore** [comment]
Well, that certainly was easy to repro, thanks for the CodePen!
