### ISSUE TITLE
Link: Focus border doesn't wrap properly for links that span multiple lines

### ISSUE THREAD

**Issue by luhu** [OfficeDev/office-ui-fabric-react#688]
### Bug Report

- __Package version(s)__: (0.78.2~latest)
- __Browser and OS versions__: (Chrome, IE 10+, Edge, FF)

#### Describe the issue:

The focus border of the link can't wrap all text of the link if the text of the Link displays more than 1 line.

#### Actual behavior:

The focus border wraps part of the link text.
![link-focus-issue](https://cloud.githubusercontent.com/assets/781143/21103298/cfe68e82-c0bc-11e6-9f43-2a79f7989a9a.png)

#### Expected behavior:

The focus border wraps all the link text.

### If applicable, please provide a codepen repro:

http://codepen.io/luhu/pen/JbaOBL

1. Inside the preview, press 'tab' to focus the link.
2. See the focus border wraps part of the link text.

**Comment by mikewheaton** [comment]
The [`focus-border()` mixin](https://github.com/OfficeDev/office-ui-fabric-react/blob/78e462bc936350fee2806ee0e70d523e8deee9b5/packages/office-ui-fabric-react/src/common/_focusBorder.scss) uses absolute positioning for the border, but this requires a block or inline-block element. Links are `display: inline` by default.

It works if the link is `display: inline-block`: http://codepen.io/mikewheaton/pen/xRajRy

However, using the mixin to change the `display` value is likely to result in some layout issues, and it would require JS to make sure we only change elements that are `display: inline`. To leave the layout intact we may need to measure inline elements and set the width of the focus border.



https://github.com/OfficeDev/office-ui-fabric-react/blob/78e462bc936350fee2806ee0e70d523e8deee9b5/packages/office-ui-fabric-react/src/common/_focusBorder.scssHaving the mixin change the `display` value is likely to result in some layout issues, so I suspect we'll have to get JS involved here to measure inline elements

**Comment by MirandaGe** [comment]
### inline multiple link unexpected behavior
I also realized there may be some case that we just want to show an inline link, and would like to add some additional information here:

* Actual behavior:
the focus border warps part of the link text:
![image](https://cloud.githubusercontent.com/assets/16030290/21124864/6753c6ae-c11c-11e6-9204-1e6a88d5d2d0.png)
* Expected behavior:
This is the default behavior of `<a>`
![image](https://cloud.githubusercontent.com/assets/16030290/21125011/4ee086ec-c11d-11e6-9c94-0657be0874fa.png)

**Comment by mikewheaton** [comment]
Very good point. I think the best solution here is to not use the `focus-border()` mixin for the Link component. Instead, we can use the standard `outline` property to get this result:

![image](https://cloud.githubusercontent.com/assets/1382445/21147180/f7915d94-c108-11e6-85f4-db3584e98e37.png)
[CodePen demo](http://codepen.io/mikewheaton/pen/BQqQLd)

**Comment by dzearing** [comment]
@mikewheaton do you have a PR for this?

**Comment by mikewheaton** [comment]
@dzearing I've assigned this to myself, should have a PR in tomorrow. 😊

**Comment by dzearing** [comment]
Sounds good, thanks!
