### ISSUE TITLE
Panel shadows are shorter than the panel itself

### ISSUE THREAD

**Issue by dagoff** [OfficeDev/office-ui-fabric-react#6888]
### Environment Information 
 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
 
You can see this just by going to https://developer.microsoft.com/en-us/fabric#/components/panel

 
#### Actual behavior:
 

 
The box-shadow is: -30px 0px 30px -30px

The -30px on the end is making it too short, I think. In the attached image, I've darkened the shadow to make it easier to see. As you can see, it doesn't reach the top.

![image](https://user-images.githubusercontent.com/22626425/47687328-f6fda800-db9c-11e8-8ba7-6fd0e6ff67b3.png)

#### Expected behavior:
 
The box-shadow should probably be: 0px 0px 30px 0px

The shadows should stretch all the way to the top and bottom.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Yes

Requested priority: (Blocking, High, Normal, Low) 
 
Low

Products/sites affected: (if applicable)
 
I've received complaints about it from designers.

**Comment by cliffkoh** [comment]
Looks really straightforward :)

**Comment by micahgodbolt** [comment]
@betrue-final-final do you have any background on why this specific shadow was chosen?

**Comment by JasonGore** [comment]
Just confirmed with @betrue-final-final that this wasn't intentional. It's ok to make this fix assuming Panel can continue to be overridden by styles functions.
