### ISSUE TITLE
Invalid aria-role nesting in picker

### ISSUE THREAD

**Issue by BrendanMcK** [OfficeDev/office-ui-fabric-react#6891]
### Environment Information 
 
- __Package version(s)__: (fill this out) 6.86.0
- __Browser and OS versions__: (fill this out if relevant) n/a
 
#### Actual behavior:

Inspect the structure of any of the [first two Topic pickers in the Fabric docs page](https://developer.microsoft.com/en-us/fabric#/components/pickers):

* One element is a `div` with `role=list`
* This has a child `input` with `role=combobox`

This is not valid per [aria-role spec](https://www.w3.org/WAI/PF/aria/roles#list); `list` may only contain `listitem` children, which is not the case here. 
 
![image](https://user-images.githubusercontent.com/1754373/47698570-0c8ac600-dbcd-11e8-8976-16c1707dc19c.png)

#### Expected behavior:
 
Unclear what the intent is here - should the `role=list` be a sibling of the `input`? A common pattern for combos seems to have a `input` that has a following `div role=list`, which the `input` `aria-owns`.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by JasonGore** [comment]
This bug can also be verified by running accessibility checkers against the provided link.

**Comment by natalieethell** [comment]
Spoke with Jon and James offline, and I think we've come up with an easy fix.
