### ISSUE TITLE
Add onItemClick to ComboBox

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#6898]
Teams has a request to be able to evoke a callback when an item is clicked, regardless of if the selected value actually changes (onChange only fires if value changes).

An onItemClick would allow user to add callback to any click on the menu, and even disable the default behavior under particular conditions.

**What component or utility would this be added to**

ComboBox

**Have you discussed this feature with our team, and if so, who**

Teams

**Additional context/screenshots**

![image](https://user-images.githubusercontent.com/1434956/47739490-b7819b00-dc32-11e8-8712-db2bb0917868.png)

**Comment by KevinTCoughlin** [comment]
> 
> 
> I've got the working updates, though blocked on API linting if someone can push this through.
> 
> https://github.com/micahgodbolt/office-ui-fabric-react/tree/combobox-onItemClick

Ack!

**Comment by micahgodbolt** [comment]
Yeah....I thought we solved the linting issue last week. Wasn't sure if it was an issue with my new dev setup, or needing to build certain projects or what.
