### ISSUE TITLE
Provide a way to override the default layer host for integration with other frameworks

### ISSUE THREAD

**Issue by ThomasMichon** [OfficeDev/office-ui-fabric-react#69]
Presently, `<Layer>` relies on a default, static implementation of a `<LayerHost>` in order to render layers. This ensures that all layers are rendered in a `<div>` at the end of the DOM.

However, the frameworks in host applications may already provide a layering mechanic. In which case, `office-ui-fabric-react`'s layering mechanic will interfere because it cannot interleave layers with the ones provided by the host framework.

`<Layer>` can be used by any React component, so it would be incorrect to require the consumer of any `<Layer>` to accept an override for the current `LayerHost`. I would propose that `<Layer>` should first check the React `context` for a `LayerHost` before defaulting to the static singleton instance.

This would allow a host app to expose an override for the `LayerHost` via context before rendering child React components.

**Comment by dzearing** [comment]
This was done.
