### ISSUE TITLE
DetailsList- Nested Detail List possible?

### ISSUE THREAD

**Issue by RituChawla** [OfficeDev/office-ui-fabric-react#6902]
I need to create a nested Detail List Ui for the following scenario:

Detail List 1 items- product name, product price, product rating

Detail List2 items - for each product in first DetailList, on click of the row, show product feedback title and feedback description, on the next row

- product 1 ( on click expand rows for feedback)
- product 1 feedback 1
- product 1 feedback 2

- product 2
- product 2 feedback 1
- product 2 feedback 2

Is it possible with DetailList or do I need to use any other fabric UI component to achieve the same?

Detail List 1-item1
   Detail List 2-item1
   Detail List2-item2
Detail List 1- item2
   Detail List 2 -item1
   Detail List 2- item 2

Thanks.

**Comment by JasonGore** [comment]
There may be two possible options here:
1. [Custom Group Headers example](https://developer.microsoft.com/en-us/fabric#/components/detailslist/customgroupheaders) supports headers that may be useful for product info
1. [GroupedList](https://developer.microsoft.com/en-us/fabric#/components/groupedlist) may also be of use here

Can you take a look and let me know if either of these look like a good fit and if not, why? Thanks!

**Comment by piotrsucharski** [comment]
Hi,

I have a simillar issue. I followed same logic as you did here, so I used Custom Group Headers and rendered a DetailsRow as a group header. 

The issue that comes later is problem with selecting list items. They are double selected due to list items indexes (So I select first subitem and first main item is selected as well.)
Another issue is I can't select main items that doesn't contain children.
-	Child items are fetched dynamically after expanding a group.
-	I don’t use any custom Selection

My render method of detailsList:

` <div className='detailList-container'>
                <DetailsList
                    items={this.props.items}
                    groups={this.props.groups}
                    columns={this.state.columns}
                    selectionMode={SelectionMode.single}
                    groupProps={{
                        onRenderHeader: props => {
                            let newProps = Object.assign({}, props);

                            newProps.item = props.group;

                            return (
                                <div key={props.groupIndex} className="DetailsListExample-customHeader">
                                    <div className='icon-expander'>
                                        {newProps.item.isExpandable ?
                                            <Icon iconName={props.group.isCollapsed ? "ChevronRightSmall" : "ChevronDownSmall"} onClick={this._onToggleCollapse(props)} />
                                            : ''}
                                    </div>
                                    <DetailsRow
                                        SelectionMode={SelectionMode.single}
                                        itemIndex={props.groupIndex}
                                        onClick={this._onToggleSelectGroup(props)}
                                        {...newProps}
                                        className='group-row'
                                        aria-busy={false}
                                    />
                                </div>
                            );
                        },

                        showEmptyGroups: true
                    }}
                    onRenderRow={this._onRenderRow}
                    viewport={{
                        width: 1200 //TODO change to calc dynamically
                    }}
                    ariaLabelForSelectionColumn="Toggle selection"
                    ariaLabelForSelectAllCheckbox="Toggle selection for all items"
                />
            </div>`

**Comment by JCMoriarty** [comment]
> There may be two possible options here:
> 
> Custom Group Headers example supports headers that may be useful for product info
> GroupedList may also be of use here
> 
> Can you take a look and let me know if either of these look like a good fit and if not, why? Thanks!



> There may be two possible options here:
> 
> Custom Group Headers example supports headers that may be useful for product info
> GroupedList may also be of use here
> 
> Can you take a look and let me know if either of these look like a good fit and if not, why? Thanks!

If I want to show the nesting list below:
List:{
{
name：X
ID：1
Detail：{
{
recordID：1
spend：100
}
{
recordID：2
spend：50
}
}
},
{
name：Y
ID：2
Detail：{
{
recordID：1
spend：30
}
{
recordID：2
spend：200
}
}

}
},
I want to show a nesting detaillist, and the first detaillist will show name and ID(can expand and collapse)
if it is expand, it will show another detaillist  recodeID and spend.

I think Custom Group Headers and GroupedList are not fit
