### ISSUE TITLE
Package Organization: Experiments, Pre Releases, Alpha Release etc

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#6903]
We want to make it 100% clear to our users if the component they are taking a dependency on is API locked and will have no breaking changes within major releases.

## Current Situation

We currently have these 4 component packages, and their associated versions

- OUFR 6.95.0

Our main package states in the readme that we follow semantic versioning and won't break existing functionality without a major release.

- Charting 0.26.1
- Dashboard 0.31.0

These two packages are < 1.0 , which __implies__ new versions may not be backwards compatible. The Charting package warns this in its readme, but if you only consume via NPM you may never read this. It's also not 100% clear that < 1.0 release implies that we might break a contract at any point.

- Experiments 6.40.0

Experiments is an odd mixed bag. We have a 6.40.0 version on it to keep it lock step with other packages like merge-styles and utilities. Inside of experiments we have a variety of component states

1. 100% experiment - LayoutGroup was something I created months ago to play around without a layout component. This should probably be completely removed from experiments soon as it was never meant for production
2. OUFR experiment - Stack is a funded project that has a roadmap and a dedicated developer. It'll be added to OUFR in the near future, but could still undergo naming/functionality tweaks that would be breaking
3. External experiment - Signals, Tile, TilesList, FolderCover are all components in development for by a single product team. While these components could have API breaking changes, those changes need to be carefully executed as these controls are currently used in production.

## Problem 1

With a large number of people committing/reviewing code it is often difficult to know if a breaking change to a non OUFR component is going to break a partner's application. 

### Current solutions

We have made sure to add Code Owners to all the controls that we are currently aware are being used in production. This will mean that this Code Owner will need to review, and sign off on any PR made against that component.

This is a good first step, but not all experiments with code owners are used in production, so it's not 100% 1 to 1. Also, unless you are looking at a pull request, finding if a control has a code owner is a bit of a manual process.

## Problem 2

How does a developer know which components they can take dependencies on, and which might change on them from minor to minor release.

### Current solutions

One approach to this issue is to use semantic versioning to imply that any sub 1.0 package is unstable, and could change at any time. This works well, but only if you a) are paying attention to the version and b) understand what a sub 1.0 package implies. Also, this solution has zero effect on a developer who is simply importing components from an already installed package. 

The other approach has been to put non stable components into an 'experiments' package so that anytime you try to use a component you have to explicitly import from a package called `@uifabric/experiments`. It'd be very difficult for a dev to say "I thought this component was 100% stable". Of course, this approach starts to break down a bit when devs are told to use __some__ experimental components in their product (those with Code Owners).  

So in the end, from a developer standpoint, it is still very difficult to know, without a doubt, if they can depend on any given component outside of OUFR.

## Proposed solutions

1. Have 3 levels of packages for all components. `Experiments -> Pre-Release -> released package (like OUFR)`. This affects file paths for PR review, and import package for end user
2. Product group based packages - let each product manage their own set of experiments components. This could even be within the experiment folder (published to its own package). Final destination might still be OUFR, or another package.
3. Have more granular packages (like Item Scope) for all of the related components. Start with 0.0.1 and move to 1.0.0-alpha.01 when it starts to become used in production.

**Comment by dzearing** [comment]
We should think about package naming and path conventions. 

Couple of questions in my head:

Should packages be granular or grouped? (1 package per component vs component groups)

Should platform be in the package name? (e.g. react vs reactnative vs vue)

It was suggested that team ownership could be in the package name (e.g. outlook-people-picker). I would really not want to do this. I'd like things to be clean and general and not have proprietary concerns or even implications that there are proprietary decisions in the code.

It was also suggested that maybe status should be in the package name. E.g. "experiments" technically is a status rather than a descriptive component grouping. If we split out a "forms" experimental package, my preference would be to keep package status as described in the version number following semantic versioning. Pre 1.0 implies experimental rules; 1.0.0-alpha implies alpha rules, 1.0.0 and beyond implies production rules.
