### ISSUE TITLE
JAWS 18 read confusing instruction for Dropdown 

### ISSUE THREAD

**Issue by luhu** [OfficeDev/office-ui-fabric-react#691]
### Bug Report

- __Package version(s)__: (latest)
- __Browser and OS versions__: (IE 11 and JAWS 18)

#### Describe the issue:

When focusing Dropdown in IE 11 with JAWS 18, the screen reader reads out "Use JAWS key + Alt + m to move to control element. To change the selection, use the arrow keys". 

The message "Use JAWS key + Alt + m to move to control element" is confusing.

#### Actual behavior:

JWAS 18 reads out  "Use JAWS key + Alt + m to move to control element"

#### Expected behavior:

JAWS 18 only reads out "To change the selection, use the arrow keys."

### If applicable, please provide a codepen repro:

https://fabricreact.azurewebsites.net/fabric-react/master/#/examples/dropdown

**Comment by aleksandrjPersonal** [comment]
@battletoilet Downloading Trial JAWS. Do we have a license? JAWS is ~$1000

**Comment by aleksandrjPersonal** [comment]
Master: JAWS says :
OnFocus: nothing
OnEnter : "Enter"
OnArrowKey: nothing
OnShiftArrowKey "Selected"

module-css-updates: JAWS says:
OnFocus: nothing
OnEnter : "Enter"
OnArrowKey: nothing
OnShiftArrowKey "Selected"


I am going to close this out as not reproing
