### ISSUE TITLE
Text: Should Text support palette colors?

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#6918]
The Text component (in experiments) has an interface that says it supports both palette and semnatic colors:

![image](https://user-images.githubusercontent.com/1382445/47808346-6ab5c700-dcfb-11e8-8c87-34afdc204181.png)

However, in the code it only checks semantic colors for the value:

![image](https://user-images.githubusercontent.com/1382445/47808334-62f62280-dcfb-11e8-9521-c96f5858819c.png)

Because of this, I'm not able to set a value like `neutralSecondary` or `red` for the text.

**Comment by dzearing** [comment]
This was intentional. Palette colors have no meaning for text but semantic colors do. Let's chat through this

**Comment by mikewheaton** [comment]
Then the interface should be updated, right? It autocompletes values from the palette but then those doesn't work at runtime.

@leddie24 and I are building a new component in the experiments package and wanted to try out the Text component. The designers haven't specified which semantic slots should be used, and it's possible that new semantic slots would need to be created. So I had been hoping to use a palette color so that it's themeable without having to figure out semantic colors at this time.

**Comment by xugao** [comment]
@mikewheaton - this issue has been open for a while. just checked, i don't think this is relevant anymore. Let me know if otherwise. thanks!
