### ISSUE TITLE
TagPicker items stack vertically rather than flowing to end of line

### ISSUE THREAD

**Issue by jalo-ms** [OfficeDev/office-ui-fabric-react#6921]
### Environment Information 
 
 
- __Package version(s)__: 6.92.1
- __Browser and OS versions__: N/A

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/anon/pen/GYVRvE

 
#### Actual behavior:
 
TagPicker items are all individually on their own line.
 
#### Expected behavior:
 
TagPicker items should flow to the end of the TagPicker control and then wrap to the next line.

![image](https://user-images.githubusercontent.com/30671397/47816579-c0e13500-dd10-11e8-9b28-d09c9027cab7.png)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal
 
Products/sites affected: N/A

It appears this was a regression in #5981, specifically [on this line](https://github.com/OfficeDev/office-ui-fabric-react/blob/2ce6c5ac3ccf4e62d4866841317b4aa55b8fb541/packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx#L203). By wrapping the TagItems in a `<span>`, they no longer respect the `flex` layout of the surrounding `.ms-BasePicker-text`.

The PeoplePicker control however works fine because it applies `display: inline-flex` to its PickerItem instance. Adding

```
.ms-TagItem {
  display: inline-flex;
}
```

to the CodePen above similarly fixes the issue.

**Comment by JasonGore** [comment]
Also reproes on Pickers example. TagPicker [before](https://fabricweb.z5.web.core.windows.net/oufr/6.52.0/#/examples/pickers) and [after](https://fabricweb.z5.web.core.windows.net/oufr/6.53.0/#/examples/pickers) appears to confirm this regression was introduced by #5981. 

@joschect Do you see an easy fix? Thanks.
