### ISSUE TITLE
How to restyle DetailsList?

### ISSUE THREAD

**Issue by DiandianWendy** [OfficeDev/office-ui-fabric-react#6923]
I am using DetailsList component, but find that it is hard to restyle it, as styles property is not available . Currently I directly override some ms-* class in css file as a work around. Is there any other solutions?

Thanks,

**Comment by JasonGore** [comment]
DetailsList does have a [`styles` property](https://developer.microsoft.com/en-us/fabric#/components/detailslist) available. Can you check and see if it has what you need? What exactly are you trying to style?

**Comment by DiandianWendy** [comment]
Ok. I will update the package to see if I could use styles property.
Thanks,
Wendy

**Comment by JasonGore** [comment]
I will close this issue for now. If you have any questions regarding styling please feel free to continue commenting and posting to this thread. Thanks!
