### ISSUE TITLE
GroupedList: Rows don't extend to full width

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#693]
### Bug Report

- __Package version(s)__: 0.69.0
- __Browser and OS versions__: Chrome on MacOS

#### Describe the issue:

The rows in GroupedList don't extend to the full width of the list. This is most noticeable when hovering across the list.

#### Actual behavior:

![image](https://cloud.githubusercontent.com/assets/1382445/21153775/cddb88ae-c120-11e6-968f-4422f9c67bf9.png)

#### Expected behavior:

![image](https://cloud.githubusercontent.com/assets/1382445/21153768/c44d04a2-c120-11e6-8cb9-70c21823c642.png)

### Likely fix

Adding `width: 100%;` to `.ms-DetailsRow` fixes this issue.

**Comment by dzearing** [comment]
This caused a regression where the rows no longer expand the full row width in scenarios where you horizontally scroll, so reverting change and re-activating.

**Comment by kristoferbrown** [comment]
Appears to be fixed now.
