### ISSUE TITLE
Datepicker:[Keros bug]:ARIA attributes must conform to valid values

### ISSUE THREAD

**Issue by neeraj-khanna** [OfficeDev/office-ui-fabric-react#6931]
### Environment Information 
 
- __Package version(s)__: 6.92.0
- __Browser and OS versions__: chrome version 69.0.3497.100 and OS version windows 10

### Please provide a reproduction of the bug in a codepen:

Bug repro URL: <https://developer.microsoft.com/en-us/fabric#/components/datepicker>
![4979cdb8](https://user-images.githubusercontent.com/14049149/47851958-3546d180-de00-11e8-9f16-8a94a0b7ba77.PNG)

 
#### Actual behavior:
 
keros issue : ARIA attributes must conform to valid values
 
#### Expected behavior:
Keros should not give any issue.

**Comment by JasonGore** [comment]
Duplicated on [OUFR v6.97.1](http://fabricweb.z5.web.core.windows.net/oufr/6.97.1/#/examples/datepicker) and issue doesn't seem to be covered by existing DatePicker a11y Pass.

**Comment by natalieethell** [comment]
@aftab-hassan will take this one.
