### ISSUE TITLE
Picker:[Keros bug]: Certain ARIA roles must contain particular children

### ISSUE THREAD

**Issue by neeraj-khanna** [OfficeDev/office-ui-fabric-react#6932]
### Environment Information 

- __Package version(s)__:  6.92.0
- __Browser and OS versions__:  chrome version 69.0.3497.100 and OS version windows 10

Bug repro URL: <https://developer.microsoft.com/en-us/fabric#/components/pickers>
![34037f8](https://user-images.githubusercontent.com/14049149/47852711-a6878400-de02-11e8-94ab-e8434360eab5.PNG)

#### Actual behavior:

Keros issue : Certain ARIA roles must contain particular children
 
#### Expected behavior:
 
keros should not give any issue

**Comment by JasonGore** [comment]
Closing as duplicated of #6891.
