### ISSUE TITLE
Grouped DetailsList Uses Group Name as a key Instead of the Provided key

### ISSUE THREAD

**Issue by canmenekse** [OfficeDev/office-ui-fabric-react#6940]
Codepen Reproduction : 
[Codepen Link](https://codepen.io/anon/pen/jQNWdO)
#### Actual behavior:
 Grouped List creates divs where it uses the name of the groups as keys. It throws duplicate key errors in the console ( it happens in the codepen provided too)
 
#### Expected behavior:
 Grouped List should use the key provided to the group as the key
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, **No**): I don't know how to fix it yet
 
Requested priority: (Blocking, High, **Normal**, Low) 

tagging @KevinTCoughlin

**Comment by JasonGore** [comment]
The source of the problematic key is `_getPageSpecification()` in `GroupedList.base.tsx` which only uses `pageGroup.name` to generate the key. A potential fix is to use `pageGroup.key` if present and only fall back to `pageGroup.name` if key is not present.

**Comment by KevinTCoughlin** [comment]
> 
> 
> The source of the problematic key is [`_getPageSpecification()` in `GroupedList.base.tsx`](https://github.com/OfficeDev/office-ui-fabric-react/blob/6990bab342ff4181034af6d9775a43665602a0b0/packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.base.tsx#L283) which only uses `pageGroup.name` to generate the key. A potential fix is to use `pageGroup.key` if present and only fall back to `pageGroup.name` if key is not present.

Thanks @JasonGore, made implementing the fix super easy 👍. Adding unit tests now and will PR.

```tsx
return {
  key: pageGroup && (pageGroup.key || pageGroup.name)
};
```
