### ISSUE TITLE
Dialog/Modal: Unable to set Layer:eventBubblingEnabled

### ISSUE THREAD

**Issue by stues** [OfficeDev/office-ui-fabric-react#6946]
### Environment Information 
 
 
- __Package version(s)__:  6.97.0
- __Browser and OS versions__: Chrome@70.0.3538.77, Windows 10

### Please provide a reproduction of the bug in a codepen:
 

 
https://codepen.io/stues/pen/rQBJJG

#### Actual behavior:
All events which are triggered from a Component which is rendered within a Dialog get swallowed by the Layer Component which is created by the Dialog.

If one wants to listen to events (e.g. dnd drop events) in a upper level of the DOM (as react-dnd does it), no events will be received.

Therefore it should be possible to set the Layer behavior when creating a Dialog component.
 
#### Expected behavior:
It should be possible to modify the Layer settings when creating a Dialog. At least enableEventBubbling should be exposed to the DialogProps

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: High

**Comment by JasonGore** [comment]
I think this is a sensible request. It looks like it only needs to be exposed in `Modal` and then it will also be accessible in `Dialog` via the `modalProps` prop. This could be considered a feature but is fairly simple to implement so I will add to Shield board.
