### ISSUE TITLE
Fabric Modal: Disable focus on the first focusable, or configured, child in focus trap zone

### ISSUE THREAD

**Issue by espenmadsen** [OfficeDev/office-ui-fabric-react#6948]
I have a use case where i have a ChoiceGroup  component inside a modal where the first radiobutton gets  focus. Is it possible to override the focus set by Fabric?

**Comment by JasonGore** [comment]
Where do you want focus set to? Can you set up a CodePen showing your desired scenario?

**Comment by espenmadsen** [comment]
The first radiobutton in the ChoiceGroup automatic gets focus when I open the Modal, is it possible to disable this focus when the modal opens ?
  
https://codepen.io/espenmadsen/pen/OaVKom

**Comment by JasonGore** [comment]
I've [tweaked the CodePen](https://codepen.io/jasongore/pen/vQNGqR) a bit for analysis. `Modal` uses a `FocusTrapZone` which traps focus, inherently giving it to an item within its region. In this case it ends up being `ChoiceGroup`. However, what I'm not sure of is if there is a way for `FocusTrapZone` to "grab" focus without setting it to another item. I don't think it is, though. 

@kenotron what do you think?

**Comment by kenotron** [comment]
I just added a dummy thing to be focused and it allows you to disable focus...
https://codepen.io/anon/pen/NExjBB

**Comment by JasonGore** [comment]
@espenmadsen Does the solution of using `firstFocusableSelector` in Ken's CodePen work for you?

**Comment by espenmadsen** [comment]
Great `firstFocusableSelector` solved my issue, thank you @kenotron  @JasonGore  :)
