### ISSUE TITLE
DatePicker: No validation after Enter pressing in pop up

### ISSUE THREAD

**Issue by rlocus** [OfficeDev/office-ui-fabric-react#6949]
<!-- 🚨 STOP 🚨 𝗦𝗧𝗢𝗣 🚨 𝑺𝑻𝑶𝑷 🚨
In case when I type any custom date string to input
my date is not applied in the calendar popup, only if I change the focus (on blur) it will be changed with new date value

**Comment by JasonGore** [comment]
We have an issue template, please fill it out. We use this information to triage and resolve. Thanks!

**Comment by dzearing** [comment]
Please feel free to reopen a new issue which follows the template. The details are super useful. E.g. codepen? What validation/behavior were you expecting?

**Comment by rlocus** [comment]
I mean when I use parseDateFromString property and then I type any value to text input the callback expected, but it happens only on blur event

**Comment by cliffkoh** [comment]
Hi @rlocus, recommend you open an new issue that adheres to the issue template to ensure it is properly investigated. Thanks!
