### ISSUE TITLE
Grouped DetailsList Blinking When Scrolled to the End too Fast

### ISSUE THREAD

**Issue by canmenekse** [OfficeDev/office-ui-fabric-react#6953]
### Environment Information 
 Chrome only, works fine on edge and firefox

### Please provide a reproduction of the bug in a codepen:
[Codepen Repro](https://codepen.io/anon/pen/vQBbGz)

#### Actual behavior:
When all of lists are expanded. If scrolled fast to the bottom( either scroll down fast with the mouse wheel or drag the scrollbar to the end really fast). The list just keeps blinking/flashing until the scrollbar is moved again
it prints a lot of:
[Violation] 'setTimeout' handler took <N>ms  in the console
Issue does not happen on small lists.

#### Expected behavior:
 It should not do flash/blinking
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, **No**)

**Comment by JasonGore** [comment]
Definitely easy to see the issue with your CodePen. Thanks!

**Comment by canmenekse** [comment]
FYI: I think this is the same thing as the issue below, I did not see it when I was opening the issue 
https://github.com/OfficeDev/office-ui-fabric-react/issues/5094

**Comment by KevinTCoughlin** [comment]
@canmenekse can you try the proposed workaround mentioned in https://github.com/OfficeDev/office-ui-fabric-react/issues/5400#issuecomment-467629497?

**Comment by canmenekse** [comment]
great.It works with the workaround.
Here is the same list after (with the getGroupHeight):
[https://codepen.io/anon/pen/XGbYWb](https://codepen.io/anon/pen/XGbYWb)

**Comment by KevinTCoughlin** [comment]
> great.It works with the workaround.
> Here is the same list after (with the getGroupHeight):
> https://codepen.io/anon/pen/XGbYWb

Happy to hear @canmenekse! You can close this or keep it open and once merged my PR will auto-close the issue. Sorry for the delay... this was a tricky one.

**Comment by KevinTCoughlin** [comment]
Closing this issue giving the report above and the fact that the PR which makes the workaround the default behavior has been merged, see https://github.com/OfficeDev/office-ui-fabric-react/pull/8125.

Thank you for the report!
