### ISSUE TITLE
Strange behavior on people picker

### ISSUE THREAD

**Issue by lijunle** [OfficeDev/office-ui-fabric-react#696]
### Bug Report

- __Package version(s)__: v0.82.1
- __Browser and OS versions__: N/A

#### Describe the issue:

The `HOME` and `END` key in the people picker input box behavior strange. When I typed a wrong name in the input name and get no response, I expect `SHIFT+HOME` to select the text and delete it. However, it does not work. 

#### Actual behavior:

Nothing is happened. The `SHIFT+HOME` is ignored.

#### Expected behavior:

Expect `SHIFT+HOME` to select the text.

### If applicable, please provide a codepen repro:

Try it on the Fabric-React demo page: http://dev.office.com/fabric#/components/peoplepicker

**Comment by lijunle** [comment]
Another strange behavior on BACKSPACE keys. The auto-suggestion list is **suddenly** fill into the input box, and as a user I **completely cannot** predict what is going to happen when press LEFT, RIGHT or BACKSPACE.

It goes into very bad situation for accessibility. The blind people will get lost with his/her actions. Hope to get some ideas from @ipip2005 

![strange](https://cloud.githubusercontent.com/assets/1296500/21252843/3e6c94b6-c395-11e6-93ca-03b0d3324197.gif)

**Comment by joschect** [comment]
@lijunle Thanks for pointing this out. I'll get it fixed!

**Comment by joschect** [comment]
@lijunle Hey, I just put in some changes to the baseautofill, which peoplepicker uses. If you want to pull down the branch and try it out you should see it being much improved.
