### ISSUE TITLE
MessageBar Codepen link isn't working

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#6961]
### Environment Information 
 
 
- __Package version(s)__: 6.98.1
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
 
The message bar codepen link does not produce working code

https://developer.microsoft.com/en-us/fabric#/components/messagebar

**Comment by kenotron** [comment]
Apparently this applies to the Label component as well.
