### ISSUE TITLE
Add code owners for API files

### ISSUE THREAD

**Issue by kkjeer** [OfficeDev/office-ui-fabric-react#6964]
### Environment Information 
 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:
 
API files for packages have no code owners.
 
#### Expected behavior:
 
API files have Fabric Tactical members as code owners.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) Yes
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by micahgodbolt** [comment]
is this still desired? it seems the API files are changing quite often, and the normal component author is already getting pinged due to them.

**Comment by kkjeer** [comment]
This isn't technically necessary. It was part of the original plan for API extractor integration so I opened the issue. It depends on how strict we want to be about API updates - if normal component author approval is sufficient then this can be closed.
