### ISSUE TITLE
How to change the different style properties of Nav

### ISSUE THREAD

**Issue by rohitrewa** [OfficeDev/office-ui-fabric-react#6972]
I am trying to change the background color and on select color for the Nav items. Can someone please share a code snippet.

`<Nav
    onLinkClick = {(ev, item) => this.onLinkClick(ev, item)}
    groups={[
        {
            links: [
                { name: 'Home', key: 'Home', url: '' },
                { name: 'Activity', key: 'Activity', url: '' },
                { name: 'News', key: 'News', url: '' },
                { name: 'Documents', key: 'Documents', url: '', className:'item' }
            ]
        }
    ]}
/>`

**Comment by kenotron** [comment]
I would refrain from creating a one-off background color changes in your app. I would recommend you to work through the theming system to do the background color changes. These are achieved through theming with these colors:

```
color: palette.themePrimary,
backgroundColor: palette.neutralLighter
```

You can create a theme with code provided on our theme generator page:
https://developer.microsoft.com/en-us/fabric#/styles/themegenerator

There you would copy and paste that code overriding the themePrimary and neutralLighter values to what you want. Or you can use the same object from above and create a new theme via the `createTheme` API and apply it to the Nav component with the Customizer component:

```
<Customizer settings={{theme: newlyCreatedNavTheme}}>
  <Nav />
</Customizer>
```

Marking this as closed - please reopen if you still have issues with the provided approaches.

**Comment by kenotron** [comment]
Feel free to commend if you have further questions, @rohitrewa
