### ISSUE TITLE
How should merge-styles handle commas in selectors?

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#6975]
When using selectors in merge-styles, the selector is usually appended to become a child selector:

```
selectors: {
  '.ms-Button-label': {
    color: 'white'
  }
}
```

```
.root-75 .ms-Button-label { color: white; }
```

However, when a comma is used in the selector it produces both a child selector and a global style:

```
selectors: {
  '.ms-Button-label, .ms-Button-text': {
    color: 'white'
  }
}
```

```
.root-75 .ms-Button-label { color: white;}
.ms-Button-text { color: white; }
```

Is this by design? It was not what I expected to happen. It should be difficult (impossible?) to create a global selector from within a component's styles as this could lead to unintentionally breaking an app.

Here's a CodeSandbox demonstration: https://codesandbox.io/s/4wr10wrjqx

**Comment by kenotron** [comment]
This is not expected, but is actually a feature request since the mergestyles didn't handle it before. I've got a local change that will address this. However, I'll need to test it out a bunch since it's such a core piece of logic. PR forthcoming
