### ISSUE TITLE
Theming: Convergence

### ISSUE THREAD

**Issue by JasonGore** [OfficeDev/office-ui-fabric-react#6978]
This is a blanket issue for discussing how we can converge ongoing theming initiatives.

The current list of actions we can take to help converge include:

| Action | Rationale | Issue |
|--------|-----------|------|
| Theming Terminology | Quantify and define terminology to reduce ambiguity and encourage consistency. | #6980 |
| Investigation | Transform unknowns into knowns affecting HLFs. | #7002 |
| High Level Features | Quantify and define a common set of high level features that all theming initiatives hope to achieve. | #6989 |
| Theming Types & Structures | Quantify common theme typing and interface naming. Incorporate or separate theming structure depending on whether it can be done in a platform and theming / styling solution agnostic way (i.e. no implementation dependencies.) | |
| Documentation | Create a common set of documentation that applies to all initiatives and / or their dependencies. Create an interactive site with theming that can be applied to all initiatives. Clear design patterns and tutorials (ideally editable inline) for all elements of theming and styling. | #7001 |

**Comment by kenotron** [comment]
Please add notes about React Hooks

**Comment by JasonGore** [comment]
React Hooks added to #7002 .

**Comment by JasonGore** [comment]
Since most of these things have solidified and we have the project board I'm going to close this epic.
