### ISSUE TITLE
Content awared crop on Image component under Cover mode.

### ISSUE THREAD

**Issue by lijunle** [OfficeDev/office-ui-fabric-react#698]
The Image component under Cover mode is useful to crop the image to fix my container. It could be better to make it smarter. 😺 

There is a JavaScript library named [smartcrop.js](https://29a.ch/sandbox/2014/smartcrop/examples/testsuite.html) to do content awared crop to get the cool part. 

It could be awesome if Fabric-React can intergarte it or do a adpotion layer for it!

(If you want this, please vote up with `+1` reaction. Thank you!)

**Comment by dzearing** [comment]
I think it would be better to create a subclass or separate component that has this complexity. We should keep the `Image` basic to prevent package size from being bloated.

**Comment by dzearing** [comment]
BTW the tech is awesome but 73ms per image is too large a price to pay for a bunch of thumbnails. A better solution would be to do this on the server at upload time and download crop centering coords at rendering time. Then the feature ask for `Image` simply becomes "provide x/y centering percentage".
