### ISSUE TITLE
Controlled multi select ComboBox has very strange behavior 

### ISSUE THREAD

**Issue by dushajni** [OfficeDev/office-ui-fabric-react#6993]
### Environment Information 
 
 
- __Package version(s)__: 6.99
- __Browser and OS versions__: All browsers, Windows

#### Actual behavior:
 
1. Controlled multi select ComboBox doesn't show preselected value at input bar. You have to click on combobox, then click somewhere else to show it. 
2. It's not possible to select/deselect some option with clicking. Only way to select option is by typing value in input field.
3. Controlled multi select combobox had bugs even before last version but with last version it is imposible to use this component. 

It even doesnt work at your official website.
 
#### Expected behavior:
 
1. Default (preselected) value shown at combobox
2. Possibility to select/deselect options with click.

**Comment by kenotron** [comment]
Codepen example to follow here...

**Comment by dushajni** [comment]
I thought that codepen example is not needed since example on [fabric ui official web page](https://developer.microsoft.com/en-us/fabric#/components/ComboBox) for "Basic controlled ComboBox multi-select " doesnt work well.

**Comment by kenotron** [comment]
Wow, this bug is really bad, I'm adding higher priority to this than others. The component just isn't working!

**Comment by kenotron** [comment]
Okay this is a bug introduced here: #6927. I am going to consult with @KevinTCoughlin about what that bug fix was doing before proceeding ... https://github.com/OfficeDev/office-ui-fabric-react/pull/6927/files#diff-b60e1ee604d9b7cd364db34e3dd65befR1349

**Comment by kenotron** [comment]
Warm handing off to @KevinTCoughlin - feel free to ask me to review PRs

**Comment by KevinTCoughlin** [comment]
Thanks for catching and reporting this @dushajni!

**Comment by dushajni** [comment]
Even before this bug ComboBox was behaved very strange (I had issue with default selected value) Let's hope that all those bugs will be fixed with next release :)

**Comment by dushajni** [comment]
@KevinTCoughlin @kenotron Thnx for fix. But problem under number 1. from my first post is still present. I tried with selectedKey property. Option is preselected but if you want to see it in input bar, you have to click on it to show dropdown and to click somewhere else. It is also present at [official page - Basic controlled ComboBox multi-select example](https://developer.microsoft.com/en-us/fabric#/components/ComboBox)
