### ISSUE TITLE
MessageBar: Unable to identify the error message in High contrast black and white modes

### ISSUE THREAD

**Issue by jescrich** [OfficeDev/office-ui-fabric-react#6994]
On Edge explorer MessageBar Unable to identify the error message in High contrast black and white modes.

Expected Result:
Error message should be in such a way that, user should be able to identity the message immediately. The color of message should different from other text.

User Impact:
Keyboard/Low vision users face difficulty in using application if error message is not highlighted.
![bug_1257713_error message in high contrast black mode](https://user-images.githubusercontent.com/6641490/48078764-cd5e0580-e1c8-11e8-9b0b-4483d550187f.png)

**Comment by kenotron** [comment]
I agree that the messagebar high contrast mode is not very easily spotted. I'm not an accessibility expert, however, so I'll defer the wisdom to our design team. 

@betrue-final-final maybe can chime in?

Perhaps @jescrich, you have a suggestion of what it should look like? do we make it inverted or something? Or can we use another color?

**Comment by jescrich** [comment]
Color show be as accessibility guidelines if it exists.
I thinkg that the color of message should different from other text. Not sure if it's been managed by Edge or we have a chance to customize the css based on the high contrast mode.

**Comment by micahgodbolt** [comment]
@betrue-final-final were you interested in doing this PR? Otherwise I can kick it back to our devs.

**Comment by betrue-final-final** [comment]
If this isn't done I could tackle it. Back tomorrow.

**Comment by betrue-final-final** [comment]
Have a PR out
