### ISSUE TITLE
Define some baseline encapsulation for value update callbacks

### ISSUE THREAD

**Issue by ThomasMichon** [OfficeDev/office-ui-fabric-react#70]
Many components in `fabric-react` consume `props` which have initial values as well as callbacks for when those values change. However, since these are all passed separately the relationships are not always crystal clear.

For example:

``` typescript
interface IColorSliderProps {
    ...
    initialValue?: number;
    onChanged?: (newValue: number) => void;
}

interface ITextFieldProps {
    ...
    value?: string;
    onChanged?: (newValue: any) => void; // Bug: this is 'any' but the type should be 'string'
}
```

I propose that we adopt a loose concept for subscribable values, such as `IValueHandler<T>`:

``` typescript
interface IValueHandler<T> {
    initial?: T;
    onBeforeChange?: (newValue: T) => void;
    onChange?: (newValue: T) => void;
}
```

Then, `props` nicely clean up to this:

``` typescript
interface IColorSliderProps {
    color?: IValueHandler<number>;
}

interface ITextFieldProps {
    text?: IValueHandler<string>;
}
```

One could then write some utility methods to read and write `IValueHandler<T>` instances, so components do not have to handle all the cases themselves:

``` typescript
export function updateValueHandler<T>(handler: IValueHandler<T> = {}, value: T): void {
    let {
        onChange
    } = handler;

    if (onChange) {
        onChange(value);
    }
}
...
updateValueHandler(this.props.color, newColor);
```

What is nice about this pattern is that components would not need to store the callbacks from props, and could handle changes and updates to the callbacks. The callbacks would always be grouped and type-matched to their values.

**Comment by dzearing** [comment]
Say that I wanted to use a TextField. Is this what you're suggesting?

Before:

```typescript
return (
  <TextField defaultValue='foo' onChange={ this.onChange } />
);
```

After:

```typescript
return (
  <TextField value={ { initial: 'foo', onChange: this.onChange } } />
);
```

**Comment by ThomasMichon** [comment]
Yes.

From a data-flow perspective, there is no difference. But from an organization and comprehension perspective, it becomes clear that `onChange` is for that value only, not other properties.

**Comment by kmees** [comment]
The react 'standard' is `value`/`onChange` props. If you have multiple properties its either additional `color`/`onColorChange` props or `value` becomes complex type, i.e `{ color: '#ffffff', other: 1 }`.

Having the `onChange` handler defined on the `value` is really unintuitive and no other react component framework does it like that. The props should be consistent across all (input) components though

**Comment by dzearing** [comment]
This is my concern. It seems pretty non standard and id like to strive for ergonomics and predictability as much as possible.

**Comment by dzearing** [comment]
Closing for now. We will stick with the standard.
