### ISSUE TITLE
API/Component of drag-drop

### ISSUE THREAD

**Issue by be5invis** [OfficeDev/office-ui-fabric-react#7000]
The requested feature is something like [react-draggable](https://github.com/mzabriskie/react-draggable), that used the code for drag-drop in Fabric to help users to build an application that supports dragging/panning/pen.

Related UI interactions:
- Dragging
- Dropping
- Panning
- Scale or rotation
- Stylus (pen, etc)

Related devices:
- Mouse
- Touch screen
- Touchpad
- Pens
- Gamepad

**Comment by kenotron** [comment]
Putting backlog review label tag on. @be5invis are you looking for some deeper integration that react-draggable itself cannot provide for you?

**Comment by be5invis** [comment]
@kenotron `react-draggable` is more like dragging graphics around, rather than drag-drop data.

**Comment by kenotron** [comment]
I really don't think we have plans for this yet. I would recommend looking at more generic DnD react library: https://github.com/react-dnd/react-dnd ...

**Comment by micahgodbolt** [comment]
is this still a desired feature, or do we just want to recommend using react-dnd. if dnd does what we want, seems silly to recreate it.
