### ISSUE TITLE
Foundation & Theming: Documentation

### ISSUE THREAD

**Issue by JasonGore** [OfficeDev/office-ui-fabric-react#7001]
Theming Documentation

| Action | Description| Related Issues |
|--------|-----------|------|
| Icon Usage | Discuss how to customize icons from both a global perspective as well as a contextual and per-component perspective. Registering and using icons should be well documented in customization section on website. | |
| Theme Generators | Create tools to allow users to easily create themes covering all aspects: colors, typography, etc. |
| Theming Usage | How to create and load themes and schemes. Customizer, loadTheme, etc.| |
| Styling | Style variables vs. style objects / functions vs. CSS. Styling fonts, background colors, etc. | #5610, #5035 |
| Component Design | Create component script usage. Inherit styling by default. Proper use of slots & tokens. | |
| Slots & Tokens | How to make use of slots and tokens in components that implement them. |
| App Sample | A sample app showing how to lay out all pieces of theming, styling and component usage. |
  - Inline Objects
    - Inline objects mutate on every render, causing perf hits with PureComponents.
    - Document care should be taken and give examples of how slot prop options, such as component and render, can be declared const or declared with createComponent / extendsComponent to make it harder for inline object creation to impact perf.
  - How to style sections that you don't want to expose as a slot?
    - May be ok to promote as-is assuming there will be an API compatible fix for this issue.
  - Make sure ISlotProp and factory declarations are included with comments telling user to specify shorthand prop
    - Document reasoning and rationale for needing factory functions.
    - Perhaps there should be a template unit test using component as a slot with some kind of pass/fail confirming factory availability?
  - Reconsider view tests.
    - View tests don't include styling, which makes it hard to identify styling regressions.
    - View tests should probably be limited to view-only props that are hard to exercise from state or full component.
  - Consider simplyifying viewprops altogether just to be a union of component props and view props with helper type.
    - It'll be up to developers to use or not use appropriate props in view but FAR less simpler to declare and understand in types.
    - Consider TViewProps derivation.. perhaps Exclude instead of explicit include to include StyleableComponentProps by default (classname, etc.)
      - Beware of circular references here.. may need helper type for this
      - See Toggle.types for example of this
      - Even more complicated if view has slots differing from component
  - Convention that components should not render output unless their props call for it
    - This allows them to easily be used as slots without the containing component having to do props checks to see if slot should be rendered
  - Render Functions
    - Address lambda issue colliding with tslint rules.
      - Is performance really impacted?
      - What approaches (if any) can people take to avoid using lambdas?
      - This might be particularly tricky for render functions that use render as a prop for async rendering, requiring a closure to capture ComponentType
        - See Slots.Async.Example usage of AsyncData's render prop for example
        ```tsx
        const titleTextRender: ICollapsibleSectionTitleProps['text'] = render =>
          render(
            (ComponentType, props) => (
              <AsyncData
                data="done"
                // tslint:disable-next-line:jsx-no-lambda
                render={data => (data ? <ComponentType {...props} /> : <Spinner styles={{ root: { alignItems: 'flex-start' } }} />)}
              />
            ),
            'Title loaded'
          );
        ```
    - Take care to preserve and/or append children (if desired) from props.
      - If children are spred but then you are conditionally rendering nested children in JSX, even a 'false' boolean reuslt will overwrite props.children.
      ```tsx
      <ComponentType {...props}>
        {/* props.children is overwritten here in either case: when data is false due to Spinner, and when data is true due to resulting 'false' value */}
        {!data && <Spinner styles={{ root: { alignItems: "flex-start" } }} />}
      </ComponentType>
      ```
      - Children can be preserved in ways like the following:
      ```tsx
      <ComponentType {...props}>
        {data ? <Label>{props.children}</Label> : <Spinner styles={{ root: { alignItems: 'flex-start' } }} />}
      </ComponentType>
      ```

**Comment by mltejera** [comment]
Hey @JasonGore - Would love to help out on this one for the theming related stuff.

**Comment by lafe** [comment]
What is the current state of this?

I am setting up a new application at the moment, and the documentation of the styles is one major obstacle:

- The relationship between Office UI Fabric React and Office UI Fabric Core is unclear - do we have to include the Fabric.min.css or is this all included in the React components? If so, how to use the responsive layout? The official documentation does state "Fabric Core is primarily meant for non-React applications or static pages." but as far as I can tell there are no React components that implement the responsive grid.
- The [layout](https://developer.microsoft.com/en-us/fabric#/styles/web/layout) page of the official documentation does not have a full example, so the reader has to figure out what component/css/etc. to load (this is related to the previous point, that it is unclear where the React project ends and where the Core project starts)
- Adding a custom theme and using it afterwards in a custom component is not easily explained and the information is on different pages. It is pretty easy once you figure it out - unfortunately, the figuring out part took me a while and involved a deep dive in the documentation, in the issues on GitHub, the Wiki and StackOverlow. In my opinion, one issue is that the use of `getTheme` is explained in the [styles-section of the documentation](https://developer.microsoft.com/en-us/fabric#/styles/web/colors/theme-slots) whereas the setting of the Theme is explained [in the controls-section (in the "Utilities" submenu)](https://developer.microsoft.com/en-us/fabric#/controls/web/themes).

**Comment by JasonGore** [comment]
Fabric Core has been deprecated for some time and isn't required to use Fabric React.

That said, this issue as written (including theming) is regarding what is mostly experimental features and I will close it for now. We plan on taking a different approach for the next major release.

**Comment by lafe** [comment]
@JasonGore If it is deprecated, why it is featured prominently on the ["Get started" page](https://developer.microsoft.com/en-us/fabric#/get-started) of the official website? There it says:

> **Fabric Core**
> Fabric Core is an open-source collection of CSS classes and Sass mixins that give you access to Fabric's colors, animations, fonts, icons and grid. Get started with Fabric Core

It also has its own [setup guide on that page](https://developer.microsoft.com/en-us/fabric#/get-started#fabric-core). Neither of these passages mention that it is deprecated. Furthermore, you cannot use some of the features mentioned on the official page without referencing the Core style sheets (responsive grid being the most obvious for me at the moment).

**Comment by JasonGore** [comment]
Sorry, I shouldn't have used the word deprecated. I meant that it is more of a style set that allows you to use Fabric styling without using React.
