### ISSUE TITLE
Theming: Investigation

### ISSUE THREAD

**Issue by JasonGore** [OfficeDev/office-ui-fabric-react#7002]
| Item | Description | Issue | PR |
|--------|-----------|------|-----|
| React Roadmap | How do Hooks and other React features affect Foundation's current and future approach? | #7014 |
| Common App Playground | Create an app playground for using elements of all theming initiatives for analyzing feature completeness as well as a bridge towards converging common dependencies. | |
| Slot Investigation | Do we adopt slots and / or factory pattern? | #7012 |
| Props Convention | Component standards for defining props. Props accessible via theming definitions. | #7005 |
| Agnostic Approach | Validate agnostic approach is effective for supporting other styling providers. Resolve if not. Solidify Foundation API. | | #7356 |
| State Components | <li>Finalize source of truth and controlled behavior. Truth on read? Truth on write? How do state component devs access and use?</li><li> Standardize transforms, HOC or otherwise. BaseState transform introduced in #5799 was later removed. Revisit other methods listed in that PR. Most likely solution may be a composite transform layer similar to what was created in #5799 but implemented as an optional HOC around createComponent. Consider potential obsolescence with React Hooks. </li> | |
| Theme Storage | Global vs. contextual storage and access and perf implications. | #7003 |
| Schemes | Should schemes contain all theme data? If not, should scheme be renamed to colorScheme for clarity? | |

**Comment by micahgodbolt** [comment]
I'm pretty curious about the playground. Will this replace what we see when we 'npm start'? Will it be used to replace our current public facing site?

As for solutions. ReactStyleGuideIst and Storybook come to mind. I know that Stardust has a pretty robust setup, so that'd be another great place to look. It'd be great to create a solution that will scale across anyone building React components in microsoft.

**Comment by JasonGore** [comment]
Elements listed here have been resolved or covered by other issues.
