### ISSUE TITLE
CommandBar: Fluent theme

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#7007]

**Comment by Vitalius1** [comment]
@mikewheaton Pausing on this one as more design discussion necessary around the height and lateral padding.

**Comment by Vitalius1** [comment]
@betrue-final-final do we have a decision on default height and lateral padding so that I can submit the changes for review?

**Comment by mikewheaton** [comment]
If at all possible, we should avoid changing the outer dimensions of a component via the theme. This could potentially break layouts if assumptions were made around the size. How much different is the height in the toolkit than the current height?

**Comment by betrue-final-final** [comment]
It goes from 40 to 44px.

**Comment by betrue-final-final** [comment]
Looks good.
