### ISSUE TITLE
SearchBox: Fluent theme

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#7008]
Ben creating separate drawings in toolkits

ON REST: 
1.) Color of magnifying glass icon mismatch- TOOLKIT: #106EBE; WEBSITE: #0078D4 
2.) border color mismatch: TOOLKIT:#A19F9D; WEBSITE:#8A8886 
3.) Close button mismatch: WEBSITE: #0078D4(blue) w/ hover background:#F3F2F1; TOOLKIT:#000 & no hover state; 

ON FOCUS:
1.) Magnifying glass mismatch TOOLKIT: icon still visible; WEBSITE: icon disappears w/ animation; 
2.) WEBSITE: focus border color:#8A8886 then hover on focus state updates to #0078D4; TOOLKIT: focus border color: #106EBE; 

ON HOVER: 
1.)Border Color - WEBSITE: #201F1E; TOOLKIT:#323130 

MISSING STATES: disabled and underlined states in toolkit

**Comment by mikewheaton** [comment]
Turns out the design is not yet ready for this.

**Comment by maxwellred** [comment]
Closing per above PR #9611
