### ISSUE TITLE
Pivot: Fluent theme

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#7009]

**Comment by betrue-final-final** [comment]
Let me know if there's any way to do the sliding animation. Otherwise it looks good.

**Comment by betrue-final-final** [comment]
That should work fine.

**Comment by marygans** [comment]
### Fluent Updates

**Update selected hover state**
- Current: no change in background hover color; border animation in place currently.
- Expected(based on toolkit): background color #f3f2f1

**Comment by betrue-final-final** [comment]
Yes, that is correct. Background color should be Gray20 (#f3f2f1)
