### ISSUE TITLE
IE 11: Panel fails to open after it's been closed three times

### ISSUE THREAD

**Issue by wdo3650** [OfficeDev/office-ui-fabric-react#701]
### Bug Report

- __Package version(s)__: 0.82.1
- __Browser and OS versions__: IE11

#### Describe the issue:

Observed in Panel. The Panel fails to open after its been closed three times. Looking in the DOM, the overlay is not removed when the Panel is closed and in the console an error is thrown because of the use of remove() in Overlay. The method remove() is not available in IE11.

#### Actual behavior:

After the third close the Panel will fail to open.

#### Expected behavior:

The Panel should open whenever a user tries to open it.

**Comment by joschect** [comment]
this should be fixed now.
