### ISSUE TITLE
Nav: Fluent theme

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#7010]
explicitly call out changes to 3rd parties because we'll have gray and white themes

**Comment by Vitalius1** [comment]
Why is this one blocked? And why `Component: Pivot` label?

**Comment by mikewheaton** [comment]
The pivot label was a mistake. It's blocked because the design is still being worked on (according to the spreadsheet) and I also think this needs discussion, as the design may be for a new component that's replacing the existing Nav. @betrue-final-final, do you know if that's the case?

**Comment by gnanavelum** [comment]
any updates on the Fluent Nav?

**Comment by xugao** [comment]
checked with @marygans - this work is no longer relevant. closing
