### ISSUE TITLE
Theming: Slots

### ISSUE THREAD

**Issue by JasonGore** [OfficeDev/office-ui-fabric-react#7012]
* Should we adopt slots and slot props? 
  * Can we eliminate styles interfaces? 
    * Style interfaces are in many ways redundant with subcomponent structure. If we expose subcomponents via other props we should also introduce styles via those props and reduce interface friction by eliminating the styles interface.
  * What role would a `wrapper` prop play? 
  * How would slots be used for Button experiment which makes use of `HorizontalStack`?
* Factory pattern
  * Do we adopt the factory pattern with the various methods for creating slots? 
  * What are the various options? 
    1. string
    1. JSX
    1. (component, props) => render
    1. slotted component props? styling?
    1. ??
* What is the impact of slots on:
  * Foundation?
  * Styled?
  * Backwards compatibility for existing components? (Preserving style interfaces)
  * Themes / Theme Provider / Customizer? (currently only supports specific props)

**Comment by micahgodbolt** [comment]
![image](https://user-images.githubusercontent.com/1434956/50530266-a200e400-0ab0-11e9-84ea-dbb48cbe0ab6.png)

**Comment by JasonGore** [comment]
Due to the various PRs introducing slots I'm going to close this as resolved for now. Future work will be captured in new issues.
