### ISSUE TITLE
DetailsListLayoutMode always uses fixedColumns

### ISSUE THREAD

**Issue by aaronyzhou** [OfficeDev/office-ui-fabric-react#702]
### Bug Report

- __Package version(s)__: master

#### Describe the issue:

On our detail list, we set DetailsListLayoutMode to 'justified', however it always renders using fixed 
columns view.

https://github.com/OfficeDev/office-ui-fabric-react/blob/78e462bc936350fee2806ee0e70d523e8deee9b5/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.tsx

In onColumnsResized, we pass in DetailsListLayoutMode.fixedColumns to _adjustColumns, 
![image](https://cloud.githubusercontent.com/assets/7392105/21280323/1f338f64-c39a-11e6-8b13-3d9b36098e84.png)
so the highlighted code never gets called and we always used fixedColumns.

**Comment by dzearing** [comment]
I tried reproing what you're saying but i couldn't quite get it. Are you setting the right propery?

**Comment by aaronyzhou** [comment]
We are experiencing a lot of issues with the justified layout mode.
When the first column has no 'maxWidth' property, the entire detailslist gets squished. When we do
have a 'maxWidth' for the first column, the details list does not respect the 'maxWidth' parameter for the
other column. We can also resize both columns to be larger than maxWidth.

http://codepen.io/anon/pen/OWXZrx?editors=0110

**Comment by battletoilet** [comment]
Closing as of now, we can reopen this at a later time if we find this issue still valid.
