### ISSUE TITLE
Split IconButton chevron is too close to vertical separator

### ISSUE THREAD

**Issue by phistuck** [OfficeDev/office-ui-fabric-react#7029]
### Environment Information 
- __Browser and OS versions__: Chrome 70, Edge 18

### Please provide a reproduction of the bug in a codepen:
Straight from the documentation -
https://developer.microsoft.com/en-us/fabric#/components/button
Look for "Custom Split Button".

#### Actual behavior:
 
![image](https://user-images.githubusercontent.com/184400/48212934-56ba3700-e385-11e8-9df6-9145463754a1.png)

 
#### Expected behavior:
 
![image](https://user-images.githubusercontent.com/184400/48213155-d6480600-e385-11e8-9a5f-9310e03843a8.png)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No. I am not using Fabric, just happened to notice it in the documentation
 
Requested priority: Normal or High, it looks ugly and makes you look bad.
 
Products/sites affected: No idea
 

Looks like this was hand-written here -
https://github.com/OfficeDev/office-ui-fabric-react/commit/8a8c240b39c3ba12effab2c6c8e7021c3bc9cea9#diff-1f5d0000157d4792321a75bdfeb0455aR8
So maybe this is just an example issue.

**Comment by micahgodbolt** [comment]
There's also a messiness where this example is inside a file with the other split button code, so the example code shows WAY more than just this single IconButton.

**Comment by micahgodbolt** [comment]
The divider is positioned absolute, so just tweaking the right value seems to work fine. 
![image](https://user-images.githubusercontent.com/1434956/48214847-b5f05b00-e335-11e8-8755-51c8c743a4db.png)

**Comment by kenotron** [comment]
This is example code bug. The style comes from a "custom split button" - the style in the component itself is okay.
