### ISSUE TITLE
Change Sass file generation to support rollup, fusebox and browserify

### ISSUE THREAD

**Issue by jeremy-coleman** [OfficeDev/office-ui-fabric-react#7055]
please fix this, it's been broken for months. 

![image](https://user-images.githubusercontent.com/25135855/48277271-312a3d80-e418-11e8-9d16-4fa765f5ee79.png)

![image](https://user-images.githubusercontent.com/25135855/48277242-1f489a80-e418-11e8-946f-3d44c003427d.png)

**Comment by kenotron** [comment]
This issue needs more context. I cannot tell what is wrong with that import. It works as expected if you're using Webpack + the right loader configuration. These failures from the 1st screenshot looks like it came from the public website's theme generator... it works fine on my end:

https://developer.microsoft.com/en-us/fabric#/styles/themegenerator

Perhaps you could help by either putting up a set of repro steps?

**Comment by jeremy-coleman** [comment]
the line that is highlighted in the second picture importing a ./file.scss, but there's no scss file in the folder. it "works" if you use webpack, however breaks with fusebox , rollup and browserify or just tsc.

**Comment by kenotron** [comment]
I see, we would have to switch to Commons require statement in that case.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jeremy-coleman** [comment]
I should have specified, that is the office ui fabric folder inside the node_modules directory , not my workspace. You mentioned it was originally a *.scss.js file? Imo using multiple dots in a file name is a bad practice, it causes problems with mime type checking and behaves differently under different platforms/shells. 

*unrelated*While on the subject of build tools, node is moving to a url query system for the fs , It seeks like .... import namespace?query=componentName is going to be the convention and will purposefully load multiple instances of the same module (es only, not cjs) if queried multiple times. Any thoughts on that breaking webpack?

**Comment by micahgodbolt** [comment]
Calendar has been converted to css in js (though still in beta in the date-time package). We will be converting remaining controls asap, so there is no need to change how we serve up those files. (i.e. spending dev cycles removing sass vs fixing how we serve sass).

**Comment by erikdao** [comment]
Just open this issue again to see if there has been any update or workaround for this problem. I'm using `fusebox` and have the exact same problem while trying to use the `DatePicker` component (`Calendar.scss` can't be resolved.)
