### ISSUE TITLE
BasePicker: Fluent theme

### ISSUE THREAD

**Issue by Vitalius1** [OfficeDev/office-ui-fabric-react#7068]
Blocked - uses sass styles and needs mergeStyles conversion which is tracked in #5411

**Comment by KevinTCoughlin** [comment]
> 
> 
> @mikewheaton @betrue-final-final What is FilePicker? I assume this is just a custom implementation of BasePicker more product oriented. If so, we should just rename it to BasePicker and wait for it's conversion to mergeStyles.

FWIW I've only ever heard of File Picker in reference to https://docs.microsoft.com/en-us/onedrive/developer/controls/file-pickers/js-v72/?view=odsp-graph-online
