### ISSUE TITLE
DatePicker: Fluent theme

### ISSUE THREAD

**Issue by Vitalius1** [OfficeDev/office-ui-fabric-react#7070]

**Comment by Vitalius1** [comment]
This one seems is composed of a `TextField` which is already fluentized and a `Callout` holding a `Calendar`. So the most work should be done in fluentizing the `Calendar`.

**Comment by mikewheaton** [comment]
@Vitalius1, would you mind opening bugs in Azure DevOps for the toolkit issues above?

**Comment by betrue-final-final** [comment]
Looks like hover state is an old background color and font color.
![image](https://user-images.githubusercontent.com/20363037/48575018-9c1abf00-e8c5-11e8-8baa-166fceca167b.png)

**Comment by Vitalius1** [comment]
Date picker fluent changes were made only the for the input and the callout holding the `Calendar` when open. The `Calendar` needs CSS-in-JS conversion and only then we could proceed with fluentization.

**Comment by mikewheaton** [comment]
I've moved this to the Building column and labeled it as blocked, as it's waiting on #5307 and #7071.

**Comment by Vitalius1** [comment]
@mikewheaton I wonder if we need this issue open... We could probably close it as soon as @betrue-final-final approves the changes to the Callouts borderRadius and shadow. When the `Calendar` gets converted and fluentized `DatePicker` will automatically pick up the change. So I don't think there is going to be more work on this issue.

**Comment by mikewheaton** [comment]
There shouldn't be any more work needed, but I'd still rather track is as incomplete so that teams using the Fluent theme have the right expectations on what will work.

**Comment by micahgodbolt** [comment]
calendar has been converted to css-in-js over in the date-time package. It's not 100% stable yet, but should be close enough to start building up a Fluent theme.

**Comment by mikewheaton** [comment]
@micahgodbolt Is that Calendar meant to replace the one in the main office-ui-fabric-react package? Do you know if anyone is using it in production?

**Comment by micahgodbolt** [comment]
the new one JUST got published, so no one is using it yet. The calendar team and power apps team will be driving most of the work. They are added as codeowners, and will start to dogfood it as soon as they feel its ready.

**Comment by mikewheaton** [comment]
Okay, sounds like it's likely to be production ready before the existing Calendar gets converted to CSS-in-JS. @Vitalius1, think we should try styling the new component? Even if it's not ready in time and we need to convert the existing calendar, I'd expect the styles should be mostly transferable.
