### ISSUE TITLE
Callout/Popup onDismiss doesn't fire when removed from the react tree

### ISSUE THREAD

**Issue by PPatBoyd** [OfficeDev/office-ui-fabric-react#7079]
### Environment Information 
 
 
- __Package version(s)__: 6.21.1 and earlier (long standing issue)
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:
 
 https://codesandbox.io/s/0x63pzx42n

This example uses the Hidden parameter for the Callout.  It could be created other ways, such as:

{showCallout && 
    <Callout>
    ...
    </Callout>
}
.. but is a bit redundant since that's how Hidden is implemented by Callout using the Popup control.

Repro steps: 
1. Click the 'Show' button to show the callout.
2. Click outside the callout to dismiss -- onDismiss is called, as shown by the required asterisk appearing for the second Text control.
3. Click 'Show' to show the callout again.
4. Click the 'Hide' button to hide the callout.

ACTUAL BEHAVIOR: onDismiss is not called

 
#### Expected behavior:

EXPECTED BEHAVIOR after step 4: onDismiss is called

I believe the fix would be to fire onDismiss during componentWillUnmount.  
 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) 
No
 
Requested priority: (Blocking, High, Normal, Low)
Normal
 
Products/sites affected: (if applicable)  
All?

**Comment by cliffkoh** [comment]
Thanks for filing an issue @PPatBoyd :)

**Comment by aneeshack4** [comment]
I've been discussing the right solution for this offline in a thread with @PPatBoyd @JasonGore and @dzearing - I've started on a fix but it's hard to repro this on https://developer.microsoft.com/en-us/fabric#/components/callout so testing whether my fix is actually working has been hard...

**Comment by JasonGore** [comment]
If you have a branch pushed, you could modify the `package.json` of the CodeSandbox to use it. If you can easily convert it to a CodePen, you can also run `npm run codepen` command.

**Comment by aneeshack4** [comment]
Spoke offline a bunch about this - thank you to everyone for your time! I believe we're in agreement now that this is by design because as @JasonGore said, onDismiss is a request and doesn't necessarily mean that the callout has been dismissed. And if we change the onDismiss callback to be triggered due to prop value changes, it would be called multiple times. I think the conclusion is we'll look into how tooltips are managed and see if we can pull from that to callout.
