### ISSUE TITLE
SwatchColorPicker: styles not following redlines

### ISSUE THREAD

**Issue by Vitalius1** [OfficeDev/office-ui-fabric-react#7086]
### Environment Information 
 
 
- __Package version(s)__: Latest
- __Browser and OS versions__: Chrome latest

### Please provide a reproduction of the bug in a codepen:
 The behavior present on the demo site

 
#### Actual behavior:
The default styles of the SwatchColorPicker are not following multiple redlines of the Fabric toolkit.
Here is how it roughly looks now on some different states:
![screen shot 2018-11-12 at 6 46 31 pm](https://user-images.githubusercontent.com/29514833/48388571-ab73ef80-e6ae-11e8-91fc-2f8b6393333b.png)

A couple things that are not aligned (still need an audit of the rest styles):

- On focusing the outline needs to be offset by -1px
- On focusing the gray border should not be visible
- On hovering or selecting the white border separating the color from the border seems of different sizes. (This might be due to the toolkit supposing only two sizes of the swatches while in code we can have multiple sizes... so this might need designers input).

 
#### Expected behavior:
And here is a screenshot from the toolkit:
![screen shot 2018-11-12 at 7 02 04 pm](https://user-images.githubusercontent.com/29514833/48388588-baf33880-e6ae-11e8-829e-04a60e827a58.png)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? If no code-owner then perhaps yes.
 
Requested priority: Low

**Comment by betrue-final-final** [comment]
Yes, that is correct. What she shows is accurate.

**Comment by Vitalius1** [comment]
@aneeshack4 Talked to designers and will put this one on hold till next week as there is a need for some discussion on the white border sizing.

**Comment by micahgodbolt** [comment]
@Vitalius1 any update on the white border sizing?

**Comment by Vitalius1** [comment]
Will restart the discussion with the designer owning this component and see if I can get some specs for that white divider for different sizes. Before holidays have been very busy with pickers conversion and fluent-theme. Next weeks I am on Shield so will see if can be done quickly.
