### ISSUE TITLE
ProgressIndicator: Fluent theme

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#7089]

**Comment by Vitalius1** [comment]
Closing as no changes necessary for the fluent theme. Talked to @betrue-final-final and confirmed that no changes for the animation timings necessary at this moment.

**Comment by marygans** [comment]
### Fluent Updates

**Update bar indicator small label description font size**
- Current: font size: 10px
- Expected(based on toolkit):font size: 12px

**Comment by betrue-final-final** [comment]
Yes please. Make small label description 12px.

**Comment by betrue-final-final** [comment]
Is there a PR associated with this @marygans?
