### ISSUE TITLE
Shimmer: Fluent theme

### ISSUE THREAD

**Issue by Vitalius1** [OfficeDev/office-ui-fabric-react#7093]

**Comment by Vitalius1** [comment]
@betrue-final-final 
Shimmer is using two neutral color to form it's linear gradient wave.
`neutralLighter` -> `neutralLight` -> `neutralLighter`.
Both colors are mapped to the the fluent colors of `gray20` and `gray30`. If this is a good color choice then I can close the issue as I don't see what other things could be fluentized in here.

**Comment by betrue-final-final** [comment]
Makes sense.

**Comment by Vitalius1** [comment]
K. Closing this issue due to not having fluent work to do.
