### ISSUE TITLE
Signal icon(NewSignal) are not aligned with other signals in the left side

### ISSUE THREAD

**Issue by gggjtgxing** [OfficeDev/office-ui-fabric-react#7097]
### Environment Information 
 
 
- __Package version(s)__: ^5.45.1 || ^6.41.0
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:
 
Singal icon(NewSignal) are not aligned with other signals in the left side

![image](https://user-images.githubusercontent.com/17696563/48450850-acfbf100-e75c-11e8-8c0b-ba667579d55f.png)

Fabric experiment example page:
![image](https://user-images.githubusercontent.com/17696563/48450879-c866fc00-e75c-11e8-8bc2-d1d8c4474155.png)
 
#### Expected behavior:
 
NewSignal has same alignment with other signals

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
No 
Requested priority: (Blocking, High, Normal, Low) 
High 
Products/sites affected: (if applicable)
 https://microsoft.sharepoint-df.com/teams/ECMandSearchinODSP/SitePages/Forms/ByAuthor.aspx

**Comment by aneeshack4** [comment]
@gggjtgxing Which Fabric example page is the 2nd screenshot from? It's unclear because there's no Signal component page on the Fabric website...

**Comment by betrue-final-final** [comment]
This is by design. The new signal is meant to emulate a "gleam".

**Comment by gggjtgxing** [comment]
@aneeshack4  I serve that example page from my local repo

**Comment by aneeshack4** [comment]
@gggjtgxing This was closed by @betrue-final-final as you can see in the previous comment because it's by design. If you still have an issue please reopen and provide more information like a CodePen that repros the bug or specific steps to repro on the Fabric [documentation site](https://developer.microsoft.com/en-us/fabric#/components).
