### ISSUE TITLE
Pivot control should have '.' dot next to linktext if the pivot item needs attention

### ISSUE THREAD

**Issue by RajuRoopani** [OfficeDev/office-ui-fabric-react#7103]
**Describe the feature that you would like added**

Pivot view should be able to show big dot next to pivot item if the pivot item needs attention so that user can click on that pivot item
Example: If there are new items shared with me, i should be able to see dot next to pivot item link text so that its more easy for me to know that something is new in that pivot view

**What component or utility would this be added to**

Pivot view should be customized to have extra dot next to pivot item name to indicate something is new in that pivot tab

**Have you discussed this feature with our team, and if so, who**
Not yet
**Additional context/screenshots**

![ad](https://user-images.githubusercontent.com/19251539/48482187-05eb8800-e836-11e8-94a4-b44a8bc289a2.JPG)

**Comment by aneeshack4** [comment]
@micahgodbolt I looked at git history of Pivot.base.tsx because there doesn't seem to be a codeowner and no one main contributor but this looks like a feature request. Could you take a look at it and see if it makes sense for Pivot? If it does, I guess we can schedule work for it.

**Comment by micahgodbolt** [comment]
https://codepen.io/micahgodbolt/pen/bQWPJp?editors=1010

You can add an icon via the onRender method. There's also an 'itemIcon' prop, but that puts the icon before the pivot. Either way, this is 100% doable without a codechange.
