### ISSUE TITLE
PeoplePicker: className of inputProperties is not merged

### ISSUE THREAD

**Issue by realhoffi** [OfficeDev/office-ui-fabric-react#7104]
<PeoplePicker
                        inputProperties={{
                          placeholder: 'Bitte einen Benutzer angeben...',
                          id: 'pckSelectedUser',
                          className: 'testclass '
                        }}
                      />

Properties "placeholder" + "id" are working correctly! className is not merged in the control :(

**Comment by aneeshack4** [comment]
Btw @realhoffi I made a codepen with what you provided so far - if you want to just add on to that to show the repro, feel free https://codepen.io/aneeshack4/pen/BGWXxm

**Comment by realhoffi** [comment]
hi, thx @aneeshack4 !
i edited the codepen.
what you expect is, that the "input"-Control (the textbox) MUST! implement the classname "testclass", which is not the case here :(

**Comment by realhoffi** [comment]
https://codepen.io/anon/pen/XygVvQ

**Comment by realhoffi** [comment]
no problem at all :) but thx for feedback!

**Comment by cliffkoh** [comment]
Thanks for the codepen. There is a small typo (`inputProps`, not `inputProperties`) but it was really easy to see the issue with your codepen. 

Fix is in #7151 along with unit test.
