### ISSUE TITLE
DocumentCard: Fluent theme

### ISSUE THREAD

**Issue by Vitalius1** [OfficeDev/office-ui-fabric-react#7108]
Blocked - uses sass styles and needs mergeStyles conversion which is tracked in #5408

**Comment by mikewheaton** [comment]
This is unblocked thanks to #7584

**Comment by mikewheaton** [comment]
I've confirmed that the DocumentCard is now picking up the Fluent theme. Marking it as complete since there are no Fluent-specific designs for this component.

**Comment by marygans** [comment]
### Updates: 

**Title:**
Current: font-size: 18px; font weight: regular
Expected(based on toolkit): font-size: 16px ; font weight: semibold
Secondary title variant exists in code but not toolkit - Need new secondary font size value in code with this update.

**Card width:** 
Current: 320px
Expected(based on toolkit):254px 

box shadow:
Current: none
Expected(based on toolkit):4px elevation

OnHover:
Current: #c8c6c4 outline
Expected(based on toolkit):8px elevation
