### ISSUE TITLE
Update selected item : onRenderRow() in Details list component in button click event

### ISSUE THREAD

**Issue by spfx-dev-ang** [OfficeDev/office-ui-fabric-react#7111]
If I select/edit an item and click on update/delete button, 'status' column for selected item should be updated with 'Deleted/Updated'. But, remaining items must not change.

 Thanks in advance, I'd appreciate any pointers as I am new to spfx and react.

**Comment by aneeshack4** [comment]
This will be fixed by @kenotron's const enum work.

**Comment by KevinTCoughlin** [comment]
> 
> 
> If I select/edit an item and click on update/delete button, 'status' column for selected item should be updated with 'Deleted/Updated'. But, remaining items must not change.
> 
> Thanks in advance, I'd appreciate any pointers as I am new to spfx and react.

@spfx-dev-ang thanks for the report. Can you provide an isolated Codepen repro for me to debug? Without one this is difficult for me to debug given the number of combinations possible when using `DetailsList`. 

We had an issue reported awhile ago where components rendered within a row are not updated unless an event such as `resize` causes the `DetailsList` to re-render. I'm wondering if this is a similar problem.
