### ISSUE TITLE
HoverCard: Fluent theme

### ISSUE THREAD

**Issue by Vitalius1** [OfficeDev/office-ui-fabric-react#7120]
Fluent changes are to be made only to the `Callout` holding whatever user is providing to render inside of it.

**Comment by betrue-final-final** [comment]
The deploy link isn't working for me

**Comment by Vitalius1** [comment]
Looks like the PR was merged 😲 (hmm...). So you can test the changes by pulling a fresh master and build it.

**Comment by betrue-final-final** [comment]
Seems ok.
