### ISSUE TITLE
Spinner: Fluent theme

### ISSUE THREAD

**Issue by Vitalius1** [OfficeDev/office-ui-fabric-react#7121]

**Comment by Vitalius1** [comment]
@betrue-final-final @mikewheaton 
Beside the label position and the wrong color used in the toolkit (which I created issues on Ben's backlog), it seems there is not much work here regarding fluentization. So I am closing this issue and if you think it needs to be reopened, feel free to do so.

**Comment by maxwellred** [comment]
### Fluent Updates

**Diffs between Toolkit (TK) and Live**

-**Border Width:** Live = 1.5px / TK = 2px
-**Border Color:** Live = #C7E0F4 / TK = #CDE6F7
-**Label Font Size:** Live = 14px / TK = 12px
-**Label Spacing:** Live = 10px / TK = 8px

@betrue-final-final please let me know which of these changes are required

**Comment by betrue-final-final** [comment]
-Border Width:  2px
-Border Color:  #CDE6F7
-Label Font Size: 12px
-Label Spacing:  8px
