### ISSUE TITLE
JAWS is not announcing the column header associated with the cell value in DetailsList

### ISSUE THREAD

**Issue by TCambre** [OfficeDev/office-ui-fabric-react#7123]
### Environment Information 
 
 
- __Package version(s)__: repros on lastest
- __Browser and OS versions__:  repros on Chrome, Edge, Firefox, IE (one's I've tried so far)

### **This repros on office fabric site!**

Same issue as https://github.com/OfficeDev/office-ui-fabric-react/issues/5164 but for JAWS as it works with Narrator
 
#### Actual behavior:
 
When navigating over cells in DetailsList using JAWS in cursor mode it only says the value of the cell.
 
#### Expected behavior:
 
When navigating over cells in DetailsList using JAWS in cursor mode it should say the column name and cell information along with the value of the cell **same as Narrator.**

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: High
 
Products/sites affected: Microsoft Flow / BAF

**Comment by natalieethell** [comment]
Hey @TCambre are you still experiencing this issue? I just tried out JAWS on the [DetailsList Basic Example](https://developer.microsoft.com/en-us/fabric#/components/detailslist/basic) and when navigating over the cells using the down arrow key, it's reading out the following

**checkbox, not checked
Name, column 2, Item 0
Value, column 3, 0**

Maybe JAWS updated its behavior recently?

**Comment by TCambre** [comment]
@natalieethell JAWS just messed up my devbox somehow so I had to reimage... I'm going to take your word for it and revisit this soon when we re-implement the list in our redesign, we have already filed an exception for it since I created this issue.

**Comment by natalieethell** [comment]
@TCambre ah sorry about that, but sounds good! Feel free to close this issue if you're happy with this new behavior.
