### ISSUE TITLE
HoverCard: expandingCard style selector has a wrong target.

### ISSUE THREAD

**Issue by Vitalius1** [OfficeDev/office-ui-fabric-react#7128]
### Environment Information 
 
- __Package version(s)__: Lates 
- __Browser and OS versions__: All of them.

`HoverCard` has a selector in its expandingCard and plainCard styles which are not applied as intended. Looked in the git history and it looks like this issue existed at least since Fabric 5.0 release when `selectors` were introduced. Before that, it was used in a different way so no way to tell if this existed since the component was created.

#### Actual behavior:
 
https://github.com/OfficeDev/office-ui-fabric-react/blob/f067e5d479d320afd3715ebbf4bb5d62bbe99f88/packages/office-ui-fabric-react/src/components/HoverCard/ExpandingCard.styles.ts#L18-L35

The selector is trying to target a child of the `root` area which has a className `ms-Callout`. I assume the intent was to remove the `Callout`'s border and give it a different shadow.

On inspecting the DOM we can see that the styles were not applied and the reason of that being we pass the `root` styles to the className of the `Callout` which then attaches the `ms-ExpandingCard-root root-***` to the same element with the `ms-Callout` class on it.

![screen shot 2018-11-15 at 6 08 54 pm](https://user-images.githubusercontent.com/29514833/48593581-3dc00180-e902-11e8-9012-7ae268a955f5.png)

 
#### Expected behavior:
 
Removing the selector completely gives us the desired result but needs to be confirmed with the designers since this looks like persisted for a very long time. Tried to find the redlines in the Fabric toolkit and there were none to find 🤔 . @betrue-final-final to comment on this one.

Also, would be very helpful to have some screener stories written for this to eliminate a future regression after we have some designers input on how this should look.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Low

**Comment by KevinTCoughlin** [comment]
Nice find @Vitalius1!
