### ISSUE TITLE
DetailsList: Fluent theme

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#7137]

**Comment by betrue-final-final** [comment]
Looks good.

**Comment by maxwellred** [comment]
### Fluent Updates

**Code diff Issues**

-**Row Background in "-Focus" state:** Live = neutralLight/ TK = white
-**Row Header font color in "-Hover" state:** Live = 323103 / TK = 201F1E
-**Row "-Focus on Column" state:** in TK but not live
![Screen Shot 2019-07-18 at 5 41 13 PM](https://user-images.githubusercontent.com/13246181/61501220-43835080-a983-11e9-8b0c-bb2c6ccbe125.png)
-**Checkbox size :** Live = 16 / TK = 18
-**GroupHeader title font size:** Live = 17px(compact) | 21(large) / TK = 14 | 16
-**GroupHeader Arrow font size :** Live = 15(compact) | 18(large) / TK = 12 (I don't see a design comp for "large" )
-**GroupHeader Arrow background color in "-Hover on Arrow" state:** Live = edebe9 | TK = e1dfdd
![Screen Shot 2019-07-18 at 5 35 00 PM](https://user-images.githubusercontent.com/13246181/61501053-6f520680-a982-11e9-931b-0883f0eaa192.png)

**Toolkit Issues**

-**GroupHeader Row height :**  TK = 43 (should be 42 I'm assuming)
-**GroupHeader Arrow background:** There isn't a design comp that shows a desired background color for (i'm just naming it this) "-Hover on Arrow when Selected" state but the state is live. Background changes to #d2d0ce (neutralQuarternary)
![Screen Shot 2019-07-18 at 5 32 52 PM](https://user-images.githubusercontent.com/13246181/61500954-2306c680-a982-11e9-92a6-19888362de8b.png)

@betrue-final-final please let me know which of these changes are required
