### ISSUE TITLE
style helper

### ISSUE THREAD

**Issue by jeremy-coleman** [OfficeDev/office-ui-fabric-react#7139]
hi friends, I recently came across and successfully used this awesome little script for converting css/scss (or any other by compiling to css first) to typestyle, thought it may be useful for your refactoring needs (just replace $nest with 'selectors')
https://github.com/gcazaciuc/tsconvert

just wanted to share, please feel free to close this as a non-issue

**Comment by KevinTCoughlin** [comment]
Closing as non-issue, but it _is_ an interesting tool. The output nearly matches what we expect for `merge-styles`. Thanks for sharing.
