### ISSUE TITLE
Detailslist: Invalid aria-describedby value on columnheader when used onRenderColumnHeaderTooltip

### ISSUE THREAD

**Issue by arunarokk** [OfficeDev/office-ui-fabric-react#7142]
### Environment Information 
 
 
- __Package version(s)__: (6.102.0) 
- __Browser and OS versions__: (chrome and win 10)

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/arunarokk/pen/NEveMb
 
#### Actual behavior:
 
we have keros bug for invalid aria attribute value on column header, aria-describedby = "header1-name-tooltip" - element is not available in DOM

![image](https://user-images.githubusercontent.com/38989707/48667362-c7014080-ea88-11e8-9fb7-ab070aa2e5e4.png)

 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (Normal)

**Comment by KevinTCoughlin** [comment]
Perhaps related to #7013
