### ISSUE TITLE
Modal: Fluent theme

### ISSUE THREAD

**Issue by Vitalius1** [OfficeDev/office-ui-fabric-react#7148]
`Modal` is used as a host for some other components. Currently, it's used only in `Dialog` component. Fluent changes necessary are the `box-shadow` with a depth of 64 and rounded corners.

**Comment by Vitalius1** [comment]
Not sure if there is anything to review as Modal is mostly a host for other content in here. I removed the indirect styling of the Modal in the Dialog styles and instead added them in here.

**Comment by betrue-final-final** [comment]
Seems good.

**Comment by marygans** [comment]
Modal component to be moved to "Utilities"
