### ISSUE TITLE
Callout: Fluent theme

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#7156]
- reopening in order to match component styles to current toolkit

**Comment by betrue-final-final** [comment]
Code looks good.

**Comment by maxwellred** [comment]
### Fluent Updates

**Diffs between Toolkit (TK) and Live**

-**Title Font Size:** Live = 21px / TK = 20px
-**Title Font Weight:** Live = 300 / TK = 600
-**Line Height:** Live = N/A / TK = 22px
-**Padding Top:** Live = 18px / TK = 17px
-**Padding Bottom:** Live = 20px / TK = 17px
-**Padding Left / Right:** Live = 24px / TK = 28px
-**Height :** Live = 165px / TK = 172px
-**Width:** Live = 300px / TK = 293px
-**CommandBar Separator:** Live = NONE / TK = width:256px, height: 1px, color: #EDEBE9

**In toolkit only**

-**Callout with quick actions:** Title Color = black / other two are #323130

@betrue-final-final please let me know which of these changes are required

**Comment by betrue-final-final** [comment]
Here's what we want:
-Title Font Size: 20px
-Title Font Weight:  600
-Line Height:  22px
-Padding Top:  18px 
-Padding Bottom:  18px
-Padding Left / Right: 28px
-Height :  172px 
-Width:  293px (not including beak)
-CommandBar Separator:  width:256px, height: 1px, color: #EDEBE9

In toolkit only

-Callout with quick actions: Title Color = #323130

**Comment by maxwellred** [comment]
Closing because the changes I had found were actually per the example not that actual component.
