### ISSUE TITLE
Tooltip: Fluent theme

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#7157]
- confirmed tooltip styling conforms to current fluent styles as provided in sketch toolkit

**Comment by betrue-final-final** [comment]
Checked the code and it looks right.

**Comment by maxwellred** [comment]
### Fluent Updates

**Diffs between Toolkit (TK) and Live**

-**Box Shadow:** Live = effects.elevation16 / TK = effects.elevation8
-**Line Height:** Live = N/A / TK = 16px (looks right though)

@betrue-final-final please let me know which of these changes are required

**Comment by betrue-final-final** [comment]
I'm seeing an elevation of 16 in the toolkit. Also 16px line height works.

**Comment by maxwellred** [comment]
Closing per PR above #9572
