### ISSUE TITLE
TeachingBubble: Unable to style via Customizer

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#7159]
### Environment Information 
- __Package version(s)__: Latest
- __Browser and OS versions__: All

### Please provide a reproduction of the bug in a codepen:
 
https://codesandbox.io/s/yk056zrkqj

#### Actual behavior:
 
I'm trying to style the TeachingBubble using the Customizer's `scopedSettings` prop. As seen in the repro link above, this works correctly for DefaultButton but not for TeachingBubble.
 
#### Expected behavior:
 
It should be possible to style TeachingBubbles via the Customizer.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes, if someone can point me in the right direction
 
Requested priority: Normal
 
Products/sites affected: Blocks #7138

**Comment by KevinTCoughlin** [comment]
@JasonGore any clues as to why this may be happening for `TeachingBubble`?

**Comment by JasonGore** [comment]
I don't see anything obvious. TeachingBubble is registering the name `TeachingBubble` with `styled` and applying `classNames.root`. This will require some deeper troubleshooting.

**Comment by Vitalius1** [comment]
@KevinTCoughlin I took a quick look and narrowed the search direction as being the styles are not passed to the `root` area. Every other area is getting the customizations. The `root` area is the one passed to the `Callout` and there is a TODO note in there... maybe it's time `to do`:
https://github.com/OfficeDev/office-ui-fabric-react/blob/7fa794c6069b30692d9eb8b8e1aa2e3e436a28de/packages/office-ui-fabric-react/src/components/TeachingBubble/TeachingBubble.styles.ts#L105-L124

**Comment by KevinTCoughlin** [comment]
@mikewheaton let me know if the API signature I've described in https://github.com/OfficeDev/office-ui-fabric-react/pull/7179#issue-232510308 works for you. Its using `subComponentStyles` so it involved a slight modification of your `styles` object.
