### ISSUE TITLE
ms-ListGhostingExample can not find

### ISSUE THREAD

**Issue by piyumi25** [OfficeDev/office-ui-fabric-react#7163]
![code](https://user-images.githubusercontent.com/33615108/48769096-cb279b00-ece0-11e8-9d92-3586dc07a7e0.PNG)
I am trying to use list component to show list of records. But given scss files can not find. I got folloeing error.
![error](https://user-images.githubusercontent.com/33615108/48769011-93205800-ece0-11e8-8ef7-ea3155be793f.PNG)

**Comment by KevinTCoughlin** [comment]
Hey @piyumi25, the code you are attempting to import is _example_ code for the `List` component. You can view it by performing the following steps:


1. Clone the repo
1. Install the repo's dependencies via `npm install`
1. Start the local web dev server via `npm start`
1. Navigate to http://localhost:4322/#/examples/list
1. Scroll to the bottom of the page to find the example labeled "Rendering ghost items while the list is scrolling".

It should look like the following:

![ouifr_list_ghost](https://user-images.githubusercontent.com/706967/48795606-49207d80-ecb2-11e8-9b33-91e5adfb6c97.gif)

If you are building components, I would advise you to _only_ use the [List.Ghosting.Example.tsx](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/List/examples/List.Ghosting.Example.tsx) code as an example. As an example, it is not meant to be imported directly to aid with the development of a component. Does that make sense?
