### ISSUE TITLE
Check component is not using styles prop in getClassNames

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#7168]
https://codepen.io/vitalius1/pen/oQoooY?editors=1010

```
import { getStyles } from './Check.styles';
...
    const classNames = getClassNames(getStyles!, { theme: theme!, className, checked });
```

**Comment by KevinTCoughlin** [comment]
> 
> 
> https://codepen.io/vitalius1/pen/oQoooY?editors=1010
> 
> ```
> import { getStyles } from './Check.styles';
> ...
>     const classNames = getClassNames(getStyles!, { theme: theme!, className, checked });
> ```

Thanks for the helpful debug info :). I believe I have the fix, testing now then will PR.
