### ISSUE TITLE
Slider is broken in IE 11 because it uses parseFloat

### ISSUE THREAD

**Issue by cliffkoh** [OfficeDev/office-ui-fabric-react#7192]
### Environment Information 
 
 
- __Package version(s)__: 6.106.2
Browser: IE 11

### Please provide a reproduction of the bug in a codepen:
 
https://fabricweb.z5.web.core.windows.net/oufr/6.106.2/#/examples/slider
#### Actual behavior:
 
Slider control does not work in IE 11.
 
#### Expected behavior:
 
Slider control works

**Comment by cliffkoh** [comment]
BTW this problem was discovered when testing Horizontal/VerticalStack in IE 11, which exposed the slider bug.

**Comment by KevinTCoughlin** [comment]
LoC -- my bad:

https://github.com/OfficeDev/office-ui-fabric-react/blob/6201a23592b457c0e391a3aae3af581487bdd8f4/packages/office-ui-fabric-react/src/components/Slider/Slider.base.tsx#L230
