### ISSUE TITLE
Context Menu - Need to override the z-index value

### ISSUE THREAD

**Issue by aygarg** [OfficeDev/office-ui-fabric-react#72]
Currently ContextMenu control does not provide a way to override the z-index of the main div inside of the context menu control causing it to be overlapped by other components in our application. Please provide a way similar to what we did for the dialog. (Refer Pull Request #16 )
![contextmenu](https://cloud.githubusercontent.com/assets/16211561/17420853/5da584fe-5a5a-11e6-970a-fb6f41756677.png)

**Comment by ThomasMichon** [comment]
We should really fix the issue where a `<Layer>` cannot be used inside of another `<Layer>`. That would be preferable to any `z-index` workarounds.

**Comment by dzearing** [comment]
I believe this is now fixed. Please re-open if you are still experiencing issues.
