### ISSUE TITLE
Check mark selection issue with details list

### ISSUE THREAD

**Issue by hrc7505** [OfficeDev/office-ui-fabric-react#7206]
### Environment Information 
 
 
- __Package version(s)__: (^6.79.0) 

### Please provide a reproduction of the bug in a codepen:
 [Codepen example](https://codepen.io/hardik-chaudhary/pen/dQdgWq)

 
#### Actual behavior:
I have taken the selection object of details list. You can do following things and can get the actual behavior. 
1. Check all the records it will show the check mark on header too.
2. According to my example, now I am clicking on "Show loading" button.
3. Now click on "Hide loading".
4. All records are showing in the list with check mark which is fine but the check mark of header not showing there.
 
#### Expected behavior:
 If list showing all records checked then the header should have the check mark as well. 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
  - No

Requested priority: (Blocking, High, Normal, Low) 
  - High

**Comment by KevinTCoughlin** [comment]
I need to dig-in more, but _at a glance_ this does seem like a bug where on render `DetailsList` does not retain its _ALL_ selection state when using `selection` prop. Marking it as such since it seems like a minor fix (fingers crossed).

**Comment by hrc7505** [comment]
One more thing related with checkbox selection you can see in the same [Codepen example](https://codepen.io/hardik-chaudhary/pen/dQdgWq)
Two different behaviors :

-------------(1)--------------
1. Select all records with from the check mark of  header.
2. Now click on add record button.
3. Newly added record comes selected by default! (it should not be selected and also all check mark from header should get removed!)

-------------(2)--------------
1. Select all records manually (not from header!)
2. Now click on add record button.
3. Newly added record does not selected it is okay but header check mark is still showing which is an issue.

**Comment by KevinTCoughlin** [comment]
I have a fix for the original issue reported here where `Selection#isAllSelected()` is not respected when rendering the component. Raising a PR momentarily.
