### ISSUE TITLE
DetailsList- Details row as a group headers not selectable

### ISSUE THREAD

**Issue by piotrsucharski** [OfficeDev/office-ui-fabric-react#7207]
Hi,

I have a simillar issue to: https://github.com/OfficeDev/office-ui-fabric-react/issues/6902. 
I followed same logic as you did there, so I used Custom Group Headers and rendered a DetailsRow as a group header. 

The issue that comes later is problem with selecting list items. They are double selected due to list items indexes (So I select first subitem and first main item is selected as well.)
Another issue is I can't select main items that doesn't contain children.
-	Child items are fetched dynamically after expanding a group.
-	I don’t use any custom Selection
-	I use version 6.95.0

I also tried nesting one DetailsList inside another, but it has same problem with indexes.

My render method of detailsList:

` <div className='detailList-container'>
                <DetailsList
                    items={this.props.items}
                    groups={this.props.groups}
                    columns={this.state.columns}
                    selectionMode={SelectionMode.single}
                    groupProps={{
                        onRenderHeader: props => {
                            
                            let newProps = Object.assign({}, props);
                            newProps.item = props.group;

                            return (
                                <div key={props.groupIndex} className="DetailsListExample-customHeader">
                                    <div className='icon-expander'>
                                        {newProps.item.isExpandable ?
                                            <Icon iconName={props.group.isCollapsed ? "ChevronRightSmall" : "ChevronDownSmall"} onClick={this._onToggleCollapse(props)} />
                                            : ''}
                                    </div>
                                    <DetailsRow
                                        SelectionMode={SelectionMode.single}
                                        itemIndex={props.groupIndex}
                                        onClick={this._onToggleSelectGroup(props)}
                                        {...newProps}
                                        className='group-row'
                                        aria-busy={false}
                                    />
                                </div>
                            );
                        },
                        showEmptyGroups: true
                    }}
                    onRenderRow={this._onRenderRow}
                    ariaLabelForSelectionColumn="Toggle selection"
                    ariaLabelForSelectAllCheckbox="Toggle selection for all items"
                />
            </div>`

**Comment by KevinTCoughlin** [comment]
@piotrsucharski have you considered using `GroupedList` for this nested list scenario (also advised in https://github.com/OfficeDev/office-ui-fabric-react/issues/6902#issuecomment-434512072)?

It seems better suited for your use case of nested lists and using it may avoid some of the issues you've mentioned above. If it doesn't work for your needs I would be interested to know why.
