### ISSUE TITLE
How to render Breadcrumb item with custom item field?

### ISSUE THREAD

**Issue by gsbelarus** [OfficeDev/office-ui-fabric-react#7209]
The task is very simply. I want to use a react router **NavLink** component inside renderer of **Breadcrumb** item. Firstly, I have added a **link** field to items object. But how could I access this added field later inside renderer function? Seems that it defined in such way that only **IBreadcrumbItem** allowed. Of course, I can type cast to any, but this seems like an ugly way. The whole code in question is below:

```
        <Breadcrumb
          onRenderItem = { (props, defaultRenderer) => 
            <NavLink to={(props as any).link}>
                                   ^^^^^^^^^^^
                                   ugly moment to access link field  

               {defaultRenderer!(props)}
            </NavLink> }
          items = {
            breadcrumbs.map((breadcrumb: BreadcrumbsProps) => (
              {
                key: breadcrumb.key,
                text: breadcrumb,
                link: breadcrumb.props.match.url
                ^^^^^^^^^^^^^^^^^^^^^
                 I have added link field to send it later to NavLink component
              }
            ))
          }
        />
```

**Comment by KevinTCoughlin** [comment]
@gsbelarus can you populate the `IBreadcrumbItem`'s `href` with the link you want to use?

https://github.com/OfficeDev/office-ui-fabric-react/blob/b0994eb17054737576842ed03847773363e3110a/packages/office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.types.ts#L90
Then you _should_ be able to write something similar to:

```tsx
onRenderItem={(props: IBreadcrumbItem, defaultRenderer?: any) => {
    return <NavLink href={props.href}>{defaultRenderer!(props)}</NavLink>;
}}
```

**Comment by gsbelarus** [comment]
Ok, I will try `href` property. 

Thanks!
