### ISSUE TITLE
PeoplePicker item removed event? 

### ISSUE THREAD

**Issue by Taerarenai** [OfficeDev/office-ui-fabric-react#7212]
So my question is simple. Is there such a thing?

We have onItemSelected in the PeoplePicker which i am using to create a state array of selected people. We can also remove the selected people by clicking on the X in the input field (next to the selected persons name), but i can't find any event that i can use for when that happens.

What i want is to remove the person from my array as well after i remove it from the input. 

P.S: Is the teams channel for the fabric team only (do i need an invitation), or can any MS employee join it? If any employee can join it can you perhaps let me know how (seems like its asking for a code). Rather new to Teams.

**Comment by KevinTCoughlin** [comment]
Hey @Taerarenai, 

Regarding your Teams channel question:

>P.S: Is the teams channel for the fabric team only (do i need an invitation), or can any MS employee join it? If any employee can join it can you perhaps let me know how (seems like its asking for a code). Rather new to Teams.

The Teams channel is currently internal to Microsoft. If you are an employee feel free to reach out and I can share a link to you. I was unable to find your alias.

**Comment by Taerarenai** [comment]
I gave `onChange `a try and it looks like it has what i need! 

Now on the inverse of `onItemSelected`...While in my case `onChange `is enough having the ability to call an action when item is removed would help in other situations such as dialogs with information about the removed item. 
That and the fact that it doesnt make much sense to have `onItemSelected` without its counterpart (if you can call an event when a person was added, why not call another when the person is removed?
While `onChange `might do the trick in most of the cases, a event such as `onItemRemoved `would give developers more freedom in how they customize their people pickers.

Thanks!

**Comment by KevinTCoughlin** [comment]
Hmmm... I'm having second thoughts after reading the implementation and doc comments of `onItemSelected` @Taerarenai. I'm unsure if adding `onItemDeselected` or similar is useful just for consistency sake. The reason being that `onItemSelected` is meant for _processing_ or _transforming_ the item when selected.

```tsx
  /**
   * A callback to process a selection after the user selects a suggestion from the picker.
   * The returned item will be added to the selected items list
   */
  onItemSelected?: (selectedItem?: T) => T | PromiseLike<T>;
```

https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ExtendedPicker/BaseExtendedPicker.types.ts#L100-L104

Is there a clear use-case where we want to _transform_ the item when deselected? I worry that adding the inverse method may increase the complexity of this interface and lead to _more_ confusion.

cc: @amyngu @joschect for their thoughts

**Comment by joschect** [comment]
@KevinTCoughlin You're correct! "onItemSelected" is perhaps misnamed, it's not really a callback that for when something was added, it's a callback to change the selection. A good example would be if you want to make an additional call to get data to completely resolve the item.

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin You're correct! "onItemSelected" is perhaps misnamed, it's not really a callback that for when something was added, it's a callback to change the selection. A good example would be if you want to make an additional call to get data to completely resolve the item.

I see, that makes sense. Thank you @joschect!

@Taerarenai would you be alright if we closed this? Perhaps contingent on adding a comment to better explain the use-case for `onItemSelected`?

**Comment by Taerarenai** [comment]
@KevinTCoughlin Sorry for the delay, i'm on a different timezone. Well except what i already wrote i dont have any real working examples. I was using `onItemSelected` to populate the `currentSelectedPeople `array  with the people and added info on them (transforming them to be more exact). That can also be done easily by modifying the `SharepointUser `interface.

`onItemDeselected `would be usefull if you need to have a record of "removed people". For example lets say we have a form with the people picker already containing 3 people. If i remove one of them and want to keep a record of that i would simply call `onItemDeselected `and populate the `deselectedPeopleArray`. This could also be done by checking what was changed from the array, but i'd find it easier to use `onItemDeselected `if it existed.

As i said there are ways to do that without having the inverse of `onItemSelected` so you can go ahead and close this if you think it is not needed//not related to the actual use of `onItemSelected`

Thanks for your time!

**Comment by KevinTCoughlin** [comment]
> 
> 
> @KevinTCoughlin Sorry for the delay, i'm on a different timezone. Well except what i already wrote i dont have any real working examples. I was using `onItemSelected` to populate the `currentSelectedPeople `array with the people and added info on them (transforming them to be more exact). That can also be done easily by modifying the `SharepointUser `interface.
> 
> `onItemDeselected `would be usefull if you need to have a record of "removed people". For example lets say we have a form with the people picker already containing 3 people. If i remove one of them and want to keep a record of that i would simply call `onItemDeselected `and populate the `deselectedPeopleArray`. This could also be done by checking what was changed from the array, but i'd find it easier to use `onItemDeselected `if it existed.
> 
> As i said there are ways to do that without having the inverse of `onItemSelected` so you can go ahead and close this if you think it is not needed//not related to the actual use of `onItemSelected`
> 
> Thanks for your time!

@Taerarenai, thank you for providing the above rationale, however given the current complex Picker API surface (particularly w.r.t naming) I'm hesitant to add this inverse method. I believe it may lead to more confusion than the utility it provides. Particularly because it conflicts with the true implementation of `onItemSelected` as @joschect described above.

What I would recommend is to use the existing methods to maintain that array of "deselected" items as you mention. If you find this cumbersome, I would be happy to tag folks on a PR or consider auditing the current API to enable support for these methods in a major release. Perhaps you can add this consideration to our issue tracking `7.0` asks, https://github.com/OfficeDev/office-ui-fabric-react/issues/7023.

I do truly appreciate your feedback here. I hope that we can evolve the library to support your needs more easily. However, for now I'm going to close this issue.
