### ISSUE TITLE
Fabric component not inheriting style anymore

### ISSUE THREAD

**Issue by fildahui** [OfficeDev/office-ui-fabric-react#7215]
We use the `<Fabric>` component in order to inherit the font style to avoid using the SegoeUI font family.

Since version 6.84.1, however, many components do not seem to inherit the style anymore (TextField, Link, Label). Looking at the generated css the inherited style it's there but it looks like it's being overridden by the actual component's style (which before had no font styles in it)

### Environment Information 
 
 
- __Package version(s)__: from 6.84.1
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:
 
From version **6.84.1**, some components do not inherit style as before
[See sandbox here](https://codesandbox.io/s/6jqwmj1q8z)

You'll see a Label, a TextField and a Link with the SegoeUI font applied, though I wrapped everthing within a `<Fabric>` component that should apply `Roboto` font
 
#### Expected behavior:
 
As of version **6.84.0** components were inheriting style when wrapped inside the `<Fabric>` component.
[Example with version 6.84.0](https://codesandbox.io/s/38993k523m)

You'll see a Label, a TextField and a Link using the inherited font family (Roboto)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority:  High
 
Products/sites affected: (if applicable)

**Comment by aftab-hassan** [comment]
Looks related to the changes introduced by this commit - https://github.com/OfficeDev/office-ui-fabric-react/pull/6647
Looking into it.

**Comment by aneeshack4** [comment]
I think this will be resolved by this PR I currently have out & I'm working on fixing some of the regressions on Screener that include TextField & Link. You can see from the screener results that Label doesn't seem to have any more failures so it's likely been fixed already with the current PR https://screener.io/v2/states/ryQqxfIYZ.OfficeDev-office-ui-fabric-react/fabric_dependency

**Comment by dzearing** [comment]
The `Fabric` component right now is not a very reliable way to provide themed fonts. The issue we have had is that people often do not include it, and then wonder why some things (not all) are rendered in Times New Roman.

To mediate, we wanted to make sure all components render the themed font, regardless of using the `Fabric` component. You can override the default fonts through the theme using `loadTheme`. Here is an example of using Courier New everywhere:

https://codepen.io/dzearing/pen/YROWBR

Relevant code:
```
const DefaultFont = {
  fontFamily: 'Courier New'
};

loadTheme({
  fonts: {
    tiny: DefaultFont,
    xSmall: DefaultFont,
    small: DefaultFont,
    smallPlus: DefaultFont,
    medium: DefaultFont,
    mediumPlus: DefaultFont,
    large: DefaultFont,
    xLarge: DefaultFont,
    xxLarge: DefaultFont,
    superLarge: DefaultFont,
    mega: DefaultFont,
  }
});
```

**Comment by dzearing** [comment]
Let us know if that helps, if you have more questions. :)

**Comment by dzearing** [comment]
I've updated your sandbox to use the inherit fontFamily, as you were doing before:

https://codesandbox.io/s/lyo543j2r7

**Comment by kunKun-tx** [comment]
Thank you @dzearing for providing the solution. Would you mind adding this to the [doc](https://github.com/OfficeDev/office-ui-fabric-react/blob/a6221962c23ff48cebe654f89ecde0e2956f80cf/packages/office-ui-fabric-react/src/components/Theme/docs/ThemesOverview.md) page?

Also, is there any where we can see the full list of options we can use to override the default theme? I am really new to this lib and haven't find it in the source code.
