### ISSUE TITLE
Panel doesn't handle onOuterClick

### ISSUE THREAD

**Issue by tmszyman** [OfficeDev/office-ui-fabric-react#7218]
### Environment Information 
 
 
- __Package version(s)__: 6.106.3
- __Browser and OS versions__: Chrome 70, Windows 10

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/anon/pen/jQpamP
 
#### Actual behavior:
 
Panel doesn't handle onOuterClick function. Nothing happened after clicks outside the component.
 
#### Expected behavior:
 
Panel handle onOuterClick function after clicks outside this component.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: High
 
Products/sites affected: (if applicable)

**Comment by aftab-hassan** [comment]
I am working on the fix

**Comment by aftab-hassan** [comment]
@tmszyman Thanks for the repro steps. As per the current implementation, the observed behavior is not a bug. 

`private _dismissOnOuterClick(ev: any): void {
    const panel = this._panel.current;
    if (this.state.isOpen && panel) {
      if (!elementContains(panel, ev.target)) {
        if (this.props.onOuterClick) {
          this.props.onOuterClick();
          ev.preventDefault();
        } else {
          this.dismiss();
        }
      }
    }
  }`

As per the implementation above, if there is a click when the panel is open, and the target is not part of the panel, the event then gets fired. 

Panel generally covers the whole page. But it has an option to cover only a certain region, which is likely what you would want to implement. This is done by passing in a `layerProps` property. [Here](https://codepen.io/micahgodbolt/pen/KBbmwV?editors=1010) is an example.

The `onOuterClick `only fires if you are using a hostID other than the default, which is window.

**Comment by tmszyman** [comment]
@aftab-hassan Thank you for the response. It seems you are right. Issue can be closed, thanks.
