### ISSUE TITLE
TypeScript Guidelines: Typo in "Bad" Example

### ISSUE THREAD

**Issue by aleury** [OfficeDev/office-ui-fabric-react#7231]
I believe there is a typo in the [Quotes](https://github.com/OfficeDev/office-ui-fabric-react/wiki/TypeScript-Guidelines#bad-2) section.

The **Bad** example should have single quotes.

#### Actual behavior:
 
`<Foo bar="bar" />`
 
#### Expected behavior:
 
`<Foo bar='bar' />`

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Low

**Comment by dzearing** [comment]
I've updated the docs, thanks for the callout!
