### ISSUE TITLE
Can we use css modules for office ui fabric components?

### ISSUE THREAD

**Issue by piyumi25** [OfficeDev/office-ui-fabric-react#7239]
/* Button.css */
.button {
  background-color: black;
}

.disabledButton {
  composes: button;
  opacity: .5;
}

/* Button.tsx */
import styles from './Button.css';

 <PrimaryButton
            className="lgn-btn"
            data-automation-id="test"
            disabled={this.state.disabled ? true : false}
            text="Login"
            onClick={this.submitLogin}
            onKeyDown={this.loginKeyDown} styles={styles.disabledButton }
          />

**Comment by aftab-hassan** [comment]
@piyumi25 You would need to ensure that the output of `styles.disabledButton` is a Javascript object, and target the specific subsections with key-value pairs as below.

Have styles as follows
```
const buttonStyles = {
  backgroundColor: 'black'
}
const disabledButtonStyles = {
  opacity: .5
}
```

And use the button as

`<PrimaryButton text="Default button" styles={{ root: buttonStyles, rootDisabled: disabledButtonStyles }} />`

You could also take a look at the [basic usage section](https://github.com/OfficeDev/office-ui-fabric-react/wiki/mergeStyles#basic-usage), where we have examples documented, with regard to styling.
