### ISSUE TITLE
Incorrect list of Callout deprecated properties.

### ISSUE THREAD

**Issue by ronaldborman** [OfficeDev/office-ui-fabric-react#724]
The Callout documentation at https://dev.office.com/fabric#/components/callout states that there are 16 deprecated properties.

AFAICS currently only 'beakStyle' is really deprecated.

**Comment by mdahamiwal** [comment]
Thanks for catching it :) its a bug in property definition parser.

**Comment by micahgodbolt** [comment]
Great catch. Deprecated values need to be pushed to the bottom of our props list. Fixed!
