### ISSUE TITLE
Pivot Control change css

### ISSUE THREAD

**Issue by harshdamaniahd** [OfficeDev/office-ui-fabric-react#7240]
![image](https://user-images.githubusercontent.com/11780473/49152308-aea7e600-f312-11e8-8039-8ef32bcc0d9f.png)

Hi i want to add my own custom css in the ul tag.Is it possible ?

**Comment by KevinTCoughlin** [comment]
@harshdamaniahd yes, by using our CSS-in-JS approach. Here is an example: https://codepen.io/kevintcoughlin/pen/bQOEvX?editors=1010

Note the `blue` `background-color` of the `ul` element of the `Pivot` control. More information regarding our component styling approach can be found in our wiki, https://github.com/OfficeDev/office-ui-fabric-react/wiki/mergeStyles#basic-usage

**Comment by harshdamaniahd** [comment]
Thanks
