### ISSUE TITLE
TeachingBubble: Usage documentation is woefully inadequate

### ISSUE THREAD

**Issue by Jahnp** [OfficeDev/office-ui-fabric-react#7243]
### Environment Information 
- __Package version(s)__: @uifabric/fabric-website@6.8.0
- __Browser and OS versions__: N/A

### Please provide a reproduction of the bug in a codepen:
 The docs can be seen on both the live Fabric site: https://developer.microsoft.com/en-us/fabric#/components/teachingbubble

And on the dev site (here at the 6.106.3 snap): https://fabricweb.z5.web.core.windows.net/oufr/6.106.3/#/examples/teachingbubble
 
#### Actual behavior:
The usage docs for TeachingBubble are essentially absent, and don't help consumers differentiate it from similar components like Callout, Tooltip, or Coachmark. The TeachingBubble is a very specific kind of Callout that is meant to be used in tandem with a Coachmark, to call attention to a part of a page. It was specifically designed to educate users about new features, and shouldn't be thought of as a helper for assistive text.

This can lead to cases where the control is used in contexts that it wasn't designed for, and where another control may be more appropriate.
 
#### Expected behavior:
The usage docs for TeachingBubble should be expanded, and should likely borrow from Coachmark to differentiate its use case.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal
 
Products/sites affected: N/A

**Comment by KevinTCoughlin** [comment]
@Jahnp while you're in there perhaps you can adjust the placeholder image size for this example:

![image](https://user-images.githubusercontent.com/706967/49181321-e9f2e680-f30b-11e8-8aad-d0ccdc717149.png)

It clips :(

**Comment by Jahnp** [comment]
@KevinTCoughlin  Oh, gross... Good catch. Yeah, we can definitely look into that.

**Comment by Jahnp** [comment]
Closed by #7266.
