### ISSUE TITLE
[DevExp] Automate the registration of new public @uifabric packages

### ISSUE THREAD

**Issue by kenotron** [OfficeDev/office-ui-fabric-react#7253]
**Describe the feature that you would like added**

Whenever we create a published package, we almost always forget to follow up on the steps to pre-register the @uifabric/foo private package before actually publishing. This brought OUFR releases several times. We should seek to automate this away so it is not a problem anymore.

The error shows up like this:
```
You must sign up for private packages : @uifabric/date-time
``` 

**What component or utility would this be added to**

**Have you discussed this feature with our team, and if so, who**

**Additional context/screenshots**

**Comment by kenotron** [comment]
@aftab-hassan - this is a feature request, and I realized you're on shield. If you feel confident, feel free to take a stab at it. However, I think @cliffkoh or I can probably take a stab at some point if you're busy.

**Comment by cliffkoh** [comment]
@kenotron I don't think @aftab-hassan should add this to his plate. He already has an overwhelming amount to work through (if you take a look at the incoming issue rate).

We should be doing what we can to help @aftab-hassan deal with working on all these Fabric issues for the first time, and not add to his plate at this time.

**Comment by cliffkoh** [comment]
I assigned it to myself and @kenotron. One of us will get to it :) 

It's amazing how @dzearing has manually done this for years now :p

**Comment by aftab-hassan** [comment]
@cliffkoh thanks Cliff. If we still have this open after next week, I can definitely take it up.

**Comment by dzearing** [comment]
Well I mean... once or twice every 6 months isn't exactly hasn't been screaming at me as much as the 10000 other things... :)

The thing that's broken is that it needs `npm publish --access public`. The public access flag being missing I think it causing the process to break.

**Comment by cliffkoh** [comment]
Thanks @aftab-hassan. Focus on the (many) other issues you have first. Remember that next week, you'll have a pile of PRs to work through as well. I hope to be able to help you take care of this here, unless @kenotron gets to this before me.

**Comment by cliffkoh** [comment]
I plan to work on developing a fix for this tomorrow. Already opened an issue for this in Rush.

**Comment by KevinTCoughlin** [comment]
> 
> 
> I plan to work on developing a fix for this tomorrow. Already opened an issue for this in Rush.

I commandeered this from Cliff to get my "feet wet" with Rush. See the above linked issue for discussion and _eventual_ implementation.
