### ISSUE TITLE
Documentation is missing for button

### ISSUE THREAD

**Issue by rfrerebe** [OfficeDev/office-ui-fabric-react#7258]
Hello,

Wen reading documentation for Button :
https://developer.microsoft.com/en-us/fabric#/components/button

I was expecting to find documentation for IButtonProps
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Button/Button.types.ts#L34-L291

Basically all available props for a button, but there is only
* IButton interface
* ElementType enum
* ButtonType enum
* IButtonStyles interface

Those are interesting, but it seems that IButtonProps is the most important for button.
Is it normal ? or am i missing something ?

Thanks

**Comment by micahgodbolt** [comment]
Oh yeah, that seems to be a bug!

**Comment by dzearing** [comment]
@cliffkoh Is there a small issue with the processing that's causing this? There is just one Button.types.ts file which has the interface and it's not showing up after parsing.
