### ISSUE TITLE
Set Focus correctly in iframe (active element issue)

### ISSUE THREAD

**Issue by nkanaki** [OfficeDev/office-ui-fabric-react#7260]
### Environment Information 
 
 
- __Package version(s)__: 6.106.3
- __Browser and OS versions__: all

### Please provide a reproduction of the bug in a codepen:
 
Website: https://microsoft.sharepoint.com/
 
#### Actual behavior:
 
1) Tab to Create Site, hit enter (to open up a Panel, with an iframe inside of it)
2) Hit enter (on Team Site)
3) Notice focus is set to Site Name
4) Hit escape, opening up a Dialog
5) Tab to `No`, hit enter
6) Focus is lost from Site Name
 
#### Expected behavior:

1-5 )+ Focus is set to site name
 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes, with guidance
 
Requested priority: Normal
 
Products/sites affected: Any site with a iframe and a Popup being launched.

Additional Details:
In Popup.tsx, it tries to determine the active element of the site by getting the current documents active element, via a call to the utilities.

```
this._originalFocusedElement = getDocument()!.activeElement as HTMLElement;
```
where `getDocument()` is `return rootElement && rootElement.ownerDocument ? rootElement.ownerDocument : document;`

The issue with that is if there is a frame, the active element will be e reference to the head of the frame, instead of the elements within it.

See: https://stackoverflow.com/questions/25420219/find-focused-element-in-document-with-many-iframes

I have confirmed that `getDocument()!.contentWindow.document.activeElement` is the correct element to be focused on, in case of 1 iframe being present (as is the case mentioned above).

**Comment by aftab-hassan** [comment]
@nkanaki thanks for the repro steps and sharing details, Naman. I'll be working on this.

**Comment by dzearing** [comment]
@aftab-hassan any update?

**Comment by aftab-hassan** [comment]
@nkanaki @dzearing sorry for the delay in responding. I am working on this, let's check back here for updates.
