### ISSUE TITLE
Define component interfaces for style props and styles

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#7262]
**Describe the feature that you would like added**
As suggested in [this comment](https://github.com/OfficeDev/office-ui-fabric-react/pull/7250#issuecomment-442901140), we could improve the components' style functions (that take style props and return a styles object) by adding interfaces like this:

```
export interface ICalloutContentComponent {
    styles?: (props: ICalloutContentStyleProps) => Partial<ICalloutContentStyles>;
}
```

**What component or utility would this be added to**
All components with styles.

**Have you discussed this feature with our team, and if so, who**
Suggested by @JasonGore in [this comment](https://github.com/OfficeDev/office-ui-fabric-react/pull/7250#issuecomment-442901140).

**Comment by JasonGore** [comment]
I thought it may be something worth doing in the context of that PR, but maybe not as a separate blanket item since we are anticipating component conversions that would make this effort redundant.

**Comment by micahgodbolt** [comment]
@JasonGore do you still feel this is worth doing considering the changes we're looking to make in foundation etc?

**Comment by JasonGore** [comment]
No, that was what I meant by my comment above.
