### ISSUE TITLE
Signal: does not support adding className to signal

### ISSUE THREAD

**Issue by gggjtgxing** [OfficeDev/office-ui-fabric-react#7278]
### Environment Information 
 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
 

 
https://github.com/OfficeDev/office-ui-fabric-react/blob/d0caaa94fae3456740d69d84cc4fe4fabb7eb763/packages/experiments/src/components/signals/SignalField.tsx

#### Actual behavior:

` <span className={SignalFieldStyles.signalFieldValue}>{props.children}</span>`
 
#### Expected behavior:

` <span className={css(SignalFieldStyles.signalFieldValue, props.className)}>{props.children}</span>`
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by kkjeer** [comment]
@gggjtgxing thank you for opening this issue! The experimental SignalField component has not yet been converted to use the `mergeStyles` utility. However, the `className` prop is applied to the root span:
```
className={css(
    SignalFieldStyles.signalField,
    {
      [SignalFieldStyles.wide]: signalsFieldMode === 'wide',
      [SignalFieldStyles.compact]: signalsFieldMode === 'compact'
    },
    className
  )}
```
so the inner span (`<span className={SignalFieldStyles.signalFieldValue}>{props.children}</span>`) can be styled using selectors. For example, if you have the following CSS rule:
```
.mySignalClass > span {
    color: red;
}
```
and use `<SignalField className="mySignalClass" />`, then the inner span should have the style `color: red` applied.

**Comment by gggjtgxing** [comment]
@kkjeer  the problem is I have multiple spans, I don't want to override all span styles

**Comment by kkjeer** [comment]
@gggjtgxing can you create a codepen showing multiple spans? Depending on your setup, CSS selectors can still be used to style the desired span (e.g. by using `:first-child`).

**Comment by gggjtgxing** [comment]
@kkjeer  if there's a beforeSignal, it's not first span

**Comment by kkjeer** [comment]
@gggjtgxing if there is a beforeSignal, the `:nth-child` selector can be used (e.g. `:nth-child(2)`).

This is not an ideal way to style Fabric components, but given that this is an experimental component, I'm not sure if it will be converted to mergeStyles. I'm following up with the component owners to see if it can be updated.

**Comment by gggjtgxing** [comment]
@kkjeer , I mean beforeSignal is also optional, it's hard to tell if it's first or second child when rendering.

**Comment by kkjeer** [comment]
@gggjtgxing if you are passing a beforeSignal to the component, you can pass something like `className="signalWithBefore"` and use `.signalWithBefore > span:nth-child(2)` to style. Signals without a beforeSignal property can use, e.g. `className="signalWithoutBefore"` and `.signalWithoutBefore > span:first-child`.

Again, this is a somewhat unideal workaround, but hopefully you can achieve your desired outcome even if we do not update the Signal component.

**Comment by ThomasMichon** [comment]
@gggjtgxing The purpose of `SignalField` and `Signal` is to enforce standardized representation of the signal icons, colors, and alignment. So we want to be careful regarding our support for style overrides here. I would avoid using specialized selectors to override styles, as they are likely to break without warning in a subsequent update. Note that this is still in 'experiments', so no guarantees on supportability here here.
