### ISSUE TITLE
Persona: Fluent theme

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#7282]

**Comment by betrue-final-final** [comment]
The toolkit has a breakpoint from 40 > 56px.
The title and secondary text change size there from 14/12 to 20/14 respectively. 
There seems to be a second breakpoint in code and uses 16/12. Is that what it's been?

**Comment by mikewheaton** [comment]
You'll find all of the existing sizes here: https://developer.microsoft.com/en-us/fabric#/components/persona

We're not able to add/remove sizes via the theme, so I did my best to interpret the toolkit against what's in code. Could you look at the PR (#7285) and let me know if any adjustments are needed? Thanks!

**Comment by maxwellred** [comment]
### Fluent Updates

**Diffs between Toolkit (TK) and Live**

- **ALL "Personas Colors" do not match any shown in TK**
- **ALL Presence colors do not match any shown in TK (except for OOF)**
- **ALL PersonaCoin initial font-weight:** Live = 400 / TK = 600
- **PersonaCoin initial font-size for size 16:** Live = 11px / TK = 10px
- **PersonaCoin initial font-size for size 24:** Live = 11px / TK = 10px
- **PersonaCoin initial font-size for size 28:** Live = 11px / TK = 12px
- **PersonaCoin initial font-size for size 48:** Live = 17px / TK = 16px
- **Persona details primary text font-size for size 48:** Live = 16px / TK = 14px
- **Secondary Text color for sizes: 100 and 48:** Live = 605E5C / TK = 797775
- **Padding between coin and Persona details for sizes 48 and 40:** Live = 16px / TK = 12px
- **Padding between coin and Persona details for size 32:** Live = 16px / TK = 8px
- **Padding between coin and Persona details for size 28 and 24:** Live = 12px / TK = 8px

**Toolkit Issues**

- **Padding between coin and Persona details for size 8:** TK = 5px
- **Secondary and Tertiary persona details text colors:** TK = 797775 (for sizes 56 and 72 it's 605E5C and i'm assuming thats the intended color)
- **No design comp provided for unknown persona**
![Screen Shot 2019-07-02 at 11 10 53 AM](https://user-images.githubusercontent.com/13246181/60552634-6c99b500-9ce4-11e9-8f78-263eb5bb0826.png)

**"Interactive States"**

- In Persona toolkit under "Interactive States"
- I'm not seeing this as part of the code. Is there a discussion thread discussing how this should be implemented?

@betrue-final-final please let me know which of these changes are required
