### ISSUE TITLE
Facepile: Fluent theme

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#7284]

**Comment by mikewheaton** [comment]
I'm not seeing any differences between the default theme and Fluent. @betrue-final-final, could you confirm and move this to the 'Approved by design' column if so?

**Comment by betrue-final-final** [comment]
Overflow buttons just need to use the right grays.

**Comment by betrue-final-final** [comment]
@mikewheaton, just need to change the grays to the Fluent ones and we're good here.
