### ISSUE TITLE
How to use ContextualMenuItem together with React-Router Link?

### ISSUE THREAD

**Issue by gsbelarus** [OfficeDev/office-ui-fabric-react#7286]
I'm trying to attach Contextual Menu to Icon Button and combine it with React Router by overriding `contextualMenuItemAs` as seen below. It doesn't work. Seems that `ContextualMenuItem` deprive `Link` component of all mouse click events.

What else should I do in order to force ContextualMenuItem work with React Router Link?

```ts
<IconButton
  iconProps={{ iconName: 'Contact'}}
  styles={{
    rootHovered: {
      color: 'lightblue'
    },
    menuIcon: {
      display: 'none'
    }
  }}
  className="RoundIcon"
  menuProps={{
    shouldFocusOnMount: true,
    gapSpace: 2,
    isBeakVisible: true,
    contextualMenuItemAs: (props: IContextualMenuItemProps) => {
      return props.item.link ? <Link to={props.item.link}><ContextualMenuItem {...props} /></Link> : <ContextualMenuItem {...props} />;
    },
    items: [
      {
        key: 'profile',
        text: 'Profile...',
        iconProps: {
          iconName: 'ContactInfo'
        },
        link: `${match.url}/account`
      },
   ...
```

**Comment by kkjeer** [comment]
@gsbelarus I created a codepen with ContextualMenuItems that link to some sample webpages: https://codepen.io/kkjeer/pen/EOJxXe

I passed an `href` in each item through the `items` array, and removed the `contextualMenuItemAs` prop. This example does not include React router, but I can continue to work on an example with the router. Please let me know if this method does not work for your project.

**Comment by gsbelarus** [comment]
The problem is to use ContextualMenuItem with React-Router's <Link> tag. Could you provide an example? I didn't find a way by myself and retreated to defining `OnClick` and using `history.push`. It works but it is not how it is supposed to be from React-Router's point of view.

**Comment by kkjeer** [comment]
Hi @gsbelarus, I updated the codepen (https://codepen.io/kkjeer/pen/EOJxXe) to show usage with React-Router. Please let me know if there are any issues with this approach. Thanks!

**Comment by gsbelarus** [comment]
Problem is not solved.  Try your example and you will see that menu commands don't work. For example, try to switch to Profile... page.

I think, the problem here is that `<ContextualMenuItem>` stopping propagate mouse clicks up to outer `<Link>` component.

**Comment by kkjeer** [comment]
![commandbaritem-reactrouter](https://user-images.githubusercontent.com/6687333/49752229-9914b380-fc64-11e8-9d1b-d99382087c99.gif)

@gsbelarus which browser are you using? The above shows the codepen behavior in Chrome.

**Comment by gsbelarus** [comment]
Indeed, it works in Chrome and doesn't work in latest Firefox 63.0.3. Seems like a bug on their side.

But there is still a problem even in Chrome. Dropdown menu is not closing after user have selected item. It remains on screen until user clicks somewhere outside of it.

**Comment by kkjeer** [comment]
I updated the codepen to use the `onItemClick` property. From our [documentation](https://developer.microsoft.com/en-us/fabric?example=#/components/contextualmenu): "Click handler which is invoked if onClick is not passed for individual contextual menu item. Returning true will dismiss the menu even if ev.preventDefault() was called."

The dismiss behavior works as expected without `onItemClick` when ContextualMenuItem components are wrapped in other HTML elements (`<a><ContextualMenuItem /></a>`, `<span><ContextualMenuItem /></span>`, etc.). Perhaps the react-router `Link` component calls `ev.preventDefault`, but adding the `onItemClick` property with `return true;` dismisses the menu when a link is clicked.

**Comment by gsbelarus** [comment]
As it works with Chrome and Edge I think it is something wrong on Firefox side. I filled a bug issue with them:

https://bugzilla.mozilla.org/show_bug.cgi?id=1513457

Thank you for the help!
