### ISSUE TITLE
Datepicker value is clearing on clicking on another control

### ISSUE THREAD

**Issue by ymihir** [OfficeDev/office-ui-fabric-react#7289]
[DatePicker](https://developer.microsoft.com/en-us/fabric#/components/datepicker) is clearing value when I click on another control. Same thing is also happening in the examples given in the MS Docs. 
Eg. Select date from date picker and select the weekday then date picker value is clearing automatically. 

#### Actual behavior:
 Datepicker value is coming blank when we click on another control 
#### Expected behavior:
 Datepicker value should be there even if we click on another html control

**Comment by sureshnote** [comment]
Hi kkjeer, I have the scenario. That I have created a DatePicker dynamically. That case its not working. Please suggest me on this. 
this._myFields.push(<DatePicker label={field.Title} value={this.state['Approved Date'] !== undefined ? this.state['Approved Date']['value'] : ''}  onSelectDate = {this.setInputValue.bind(this,field.Title,field.TypeAsString , field.InternalName)} isRequired={field.Required} allowTextInput={true} formatDate={this._onFormatDate}></DatePicker>);

**Comment by kkjeer** [comment]
Hi @sureshnote, could you please create a CodePen that shows the behavior you're observing? Please feel free to fork my CodePen above (https://codepen.io/kkjeer/pen/wQZwQv) as a starting point that uses the DatePicker component. Thanks!

**Comment by sureshnote** [comment]
Hi kkjeer, this issue exists in my current dev environment. I'm unable to reproduce the issue in the codepen.
https://codepen.io/sureshnote/pen/XLgxZj. Anyway thanks for your support.

**Comment by sureshnote** [comment]
npm install office-ui-fabric-react@5.124.0 --save (Going back to the older version of this resolves the issue). :-(
