### ISSUE TITLE
Searchbox traps focus on self when a user's input is present. Unable to 'Tab' out.

### ISSUE THREAD

**Issue by davidprejban** [OfficeDev/office-ui-fabric-react#7291]
### Environment Information 

- __Package version(s)__: 
6.110.0
6.94.0

- __Browser and OS versions__: 
Windows Server 2016 1607 build 14393.2608

Chrome 70.0.3538.110 (Official Build) (64-bit)
Firefox 63.0.3 (64-bit)
IE 11.2608.14393.0

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/davidprejban/pen/PxgZga

Steps to reproduce:
1. Open codepen link
2. Set focus first searchbox
3. Enter at least 1 character (Example: 'a')
4. Press 'Tab' on the keyboard
 
#### Actual behavior:
Focus stays on current searchbox.
 
#### Expected behavior:
Focus moves on to the next searchbox or the next item in the tab index order.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
Yes
 
Requested priority: (Blocking, High, Normal, Low) 
High - due to the impact on accessibility for keyboard users
 
Products/sites affected: (if applicable)
 N/A

#### Notes
Shift + Tab still works as expected where the focus goes on previous tab index item.

**Comment by micahgodbolt** [comment]
Can confirm this bug. Looks like focus is flipping back and forth a bit.


![image](https://user-images.githubusercontent.com/1434956/49410669-996bf680-f71a-11e8-9c9d-9262ac910194.png)

**Comment by kkjeer** [comment]
It looks like the issue is in the callback to `setState` in `_onFocusCapture` in line [159](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/SearchBox/SearchBox.base.tsx#L159), which was introduced as a fix for #7035. I'll follow up offline to see if we can get a workaround.
