### ISSUE TITLE
clicking on the circle doesn't return button's attributes 

### ISSUE THREAD

**Issue by kirilligum** [OfficeDev/office-ui-fabric-react#7295]
### Environment Information 
 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

 https://codepen.io/kirilligum/pen/EOJmQm

```javascript
let { Toggle, Fabric } = window.Fabric;

class ToggleBasicExample extends React.Component {
  state = {nn:'yey',ch:true}
  render(){
    return (
      <div style={{ padding: '2px' }}>
        <Toggle
          defaultChecked={true}
          name={this.state.nn}
          label="aa"
          onChange={this._onChange}
        />
      </div>
      )
    }
  _onChange = (ev, checked) => {
    this.setState({ch:this.state.ch?false:true})
    console.log(ev.target.name,'toggle is ' + (checked ? 'checked' : 'not checked'));
  }
}


ReactDOM.render(<ToggleBasicExample />, document.getElementById('content'));
```

Click inside the circle. and look at the console

 
<p data-height="265" data-theme-id="0" data-slug-hash="EOJmQm" data-default-tab="js,result" data-user="kirilligum" data-pen-title="Fabric Example Pen" class="codepen">See the Pen <a href="https://codepen.io/kirilligum/pen/EOJmQm/">Fabric Example Pen</a> by Kirill Igumenshchev (<a href="https://codepen.io/kirilligum">@kirilligum</a>) on <a href="https://codepen.io">CodePen</a>.</p>
<script async src="https://static.codepen.io/assets/embed/ei.js"></script>

#### Actual behavior:
 undefined "toggle is not checked"

 
#### Expected behavior:
 "yey" "toggle is not checked"

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Blocking
 
Products/sites affected:

#### notes:

When clicking inside the circle, ev event gets 
```html
<div class="ms-Toggle-thumb thumb-75"></div>
```
instead of `<button>`

**Comment by joechung-msft** [comment]
Did you try `ev.currentTarget.name`?

**Comment by kkjeer** [comment]
Thanks for the suggestion @joechung-msft. I have a codepen using `ev.currentTarget.name` that outputs "yey toggle is not checked": https://codepen.io/kkjeer/pen/vQwLbx

**Comment by kirilligum** [comment]
Works. thank you!
