### ISSUE TITLE
How to get the selected checkbox value?

### ISSUE THREAD

**Issue by piyumi25** [OfficeDev/office-ui-fabric-react#7297]
I am trying to implement a function to get the selected checkbox value in onchange event of the check box.

this is how I create list of checkboxes
 <div className="ms-Grid" dir="ltr">
        {props.attributeList.map(item => (
          <div className="ms-Grid-row" key={item.Value}>
            <div className="ms-Grid-col ms-sm12 ms-md12 ms-lg12">
              <Checkbox
                label={item.Value}
                onChange={this.onCheckboxChange.bind(this)}
                value={item.Value}
              />
            </div>
          </div>
        ))}
      </div>

so I need to get the selected value. I tried as follows. but cannot get

onCheckboxChange = (ev, checked) => {
let selectedValue = ev.currentTarget.value;
}

**Comment by kkjeer** [comment]
Hi @piyumi25 could you please create a codepen for this issue? This would be very helpful in getting a quicker resolution. Thanks!

**Comment by piyumi25** [comment]
thank you very much for your reply and it works for me.
