### ISSUE TITLE
Impossible to scroll the page on iPad mini after Dialog/Modal window is closed

### ISSUE THREAD

**Issue by ecoukraine** [OfficeDev/office-ui-fabric-react#7298]
### Environment Information 
 
 
- __Package version(s)__: 6.95.0 
- __Browser and OS versions__: iPad mini, OS - iOS 9.3.5

#### Actual behavior:
After, the office-ui-fabric-react package was updated to the 6.95.0 version,
next behaviour appears:

1. Open a web-page with content to be scrolled 
2. Page can be scrolled
3. Open Dialog/Modal 
4. Close Dialog/Modal
5. Page cannot be scrolled
 
The update to the latest 6.110.0 did not help

#### Expected behavior:
 
Page should be scrolled

#### Priorities and help requested:
 
Requested priority: High

**Comment by kkjeer** [comment]
Hi @ecoukraine, is there a particular webpage that shows this behavior? Unfortunately I haven't been able to see a repo on our demo site for version 6.110.1: https://fabricweb.z5.web.core.windows.net/oufr/6.110.1/#/examples/modal

**Comment by ecoukraine** [comment]
Hi guys,

sorry for the late answer.
I've tried to reproduce the issue on a demo you provided
https://fabricweb.z5.web.core.windows.net/oufr/6.110.1/#/examples/modal
it's reproduced on iPad mini, OS - iOS 9.3.5
