### ISSUE TITLE
Factor out a 'light-dismiss' wrapper component

### ISSUE THREAD

**Issue by ThomasMichon** [OfficeDev/office-ui-fabric-react#73]
In general, layered components have a 'light-dismiss' mechanic by which user action outside the layer content should trigger a dismissal of the layer, either immediately or after a short period of time.

At present, each `fabric-react` component implements this mechanic independently, preventing standardization of this behavior as well as making it more difficult to handle issues such as 'virtual' parents (see #68).

The 'light-dismiss' behavior should be factored into a `<LightDismiss>` component which wraps content and tracks user interaction that only occurs outside all wrapped content. This should properly handle child and nested `<Layer>` elements by making use of the 'virtual'-aware `isAncestorOrSelf` methods.

``` typescript
<LightDismiss
    onDismiss={ this._onDismiss }
    >
    // Clicking on the button will *not* dismiss the popup, since it is within the <LightDismiss>
    <TextField text={ onChange: this._onTextChange } />
    <Dropdown>
        <ul>
            ...
        </ul>
    </Dropdown>
</LightDismiss>
```

The purpose of `<LightDismiss>` is to allow parent content to be treated as still in the 'active' zone, so that clicking outside the layer onto a sibling element does not automatically dismiss the layer.

One thing that `<LightDismiss>` could supply, in addition to rendering the content and wiring up the event handlers, is a hidden 'close' button, that is both focusable and visible to screen readers. This would improve accessibility in such situations.

**Comment by dzearing** [comment]
I believe we have this with `Popup`.
