### ISSUE TITLE
TextField: Enhancement: Add support for auto adjust height

### ISSUE THREAD

**Issue by mdahamiwal** [OfficeDev/office-ui-fabric-react#730]
#### Enhancement request:
Provide an option for TextField to auto-expand vertically. There are some cases where this is needed.

**Comment by mdahamiwal** [comment]
Can someone review [f29efee](https://github.com/mdahamiwal/office-ui-fabric-react/commit/f29efeecb0946da731ea179852472b18e316c11b ) for changes ?

**Comment by mikewheaton** [comment]
Looks reasonable to me. In your PR, could you include an example? It would be added here: https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/office-ui-fabric-react/src/demo/pages/TextFieldPage

**Comment by mdahamiwal** [comment]
Hi @mikewheaton, I think I added in the earlier [commit](https://github.com/mdahamiwal/office-ui-fabric-react/commit/f29efeecb0946da731ea179852472b18e316c11b) itself, under office-ui-fabric-react/src/demo/pages/TextFieldPage/examples/TextField.Basic.Example.tsx

**Comment by mikewheaton** [comment]
Ahh perfect, I missed that. Thanks!

**Comment by dzearing** [comment]
Looks committed, closing. thanks!
