### ISSUE TITLE
Documentation not parsing entirely some enums

### ISSUE THREAD

**Issue by Vitalius1** [OfficeDev/office-ui-fabric-react#7309]
### Environment Information 
 
- __Package version(s)__: latest
- __Browser and OS versions__: all

### Please provide a reproduction of the bug in a codepen:

When running locally or directly on the demo website the documentation parser does not output all the enums values when they are strings as opposed to numbers. One good example is here:
https://github.com/OfficeDev/office-ui-fabric-react/blob/09f1011e7355358023bb8ec712defbe62f786475/packages/office-ui-fabric-react/src/components/HoverCard/HoverCard.types.ts#L137-L159
Here we have 2 enums. One is using numbers as values and the other one is using strings. The output of the documentation parser is this
![screen shot 2018-12-05 at 11 41 20 am](https://user-images.githubusercontent.com/29514833/49540698-980b0d00-f885-11e8-9ac7-c8dc0a9a7da8.png)

#### Actual behavior:
 
The enums having strings as values in the documentation are displayed only partialy.
 
#### Expected behavior:
 
Should display all the values of the enum.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Maybe. Need to investigate how the parser works first. If there is anyone already knowing its internals probably they should handle it quicker.
 
Requested priority: Low
 
Products/sites affected: (if applicable)
Demo website https://developer.microsoft.com/en-us/fabric

**Comment by Vitalius1** [comment]
@aftab-hassan you just had a PR merged with some fixes in that area. Would you mind taking a quick look?

**Comment by Vitalius1** [comment]
@micahgodbolt not sure about the plans on re-doing the Implementation section mentioned in #6780, so if the plan is to drop the usage of the current parser in favor of the api-extractor and TSDoc, feel free to close the issue.

**Comment by cliffkoh** [comment]
This is because when the enumParser was written, string enums were not a thing. 

This will be fixed by @natalieethell's work integrating @pgonzal's API Extractor 7 and tsdoc.

**Comment by Vitalius1** [comment]
@natalieethell If you think this issue is sorted out as part of API Extractor and TSDoc integration work, feel free to close it. Or leave it open for tracking purposes. I will leave it to you 😄 to decide.

**Comment by pgonzal** [comment]
What do these enum definitions look like in the .d.ts file? API Extractor does not look at the .ts source files.

**Comment by cliffkoh** [comment]
The right thing. :)

```ts
export declare enum HoverCardType {
    /**
     * Plain card consisting of one part responsive to the size of content.
     */
    plain = "PlainCard",
    /**
     * File card consisting of two parts: compact and expanded. Has some default sizes if not specified.
     */
    expanding = "ExpandingCard",
}
```

**Comment by pgonzal** [comment]
Cool, then yeah this will be fixed when API Extractor docs are turned on.
