### ISSUE TITLE
Rating icon property is completely ignored

### ISSUE THREAD

**Issue by thechriskent** [OfficeDev/office-ui-fabric-react#7312]
### Environment Information 

- __Package version(s)__: 2.6.1 (although this appears to be true in the latest as well)

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/thechriskent/pen/jQjZvR
 
#### Actual behavior:
 
Setting the `icon` property of the Rating control has no effect. The default value is supposed to be `FavoriteStar` but is actually `FavoriteStarFill`

You can see in the code it's not used at all: https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Rating/Rating.base.tsx
 
#### Expected behavior:
 
Setting the `icon` property of the Rating control should use the specified UI Fabric Icon. The default icon should either be `FavoriteStar` or the documentation should be updated to indicate the actual default.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal

**Comment by kkjeer** [comment]
Thanks for reporting this, @thechriskent!
