### ISSUE TITLE
Any example for using redux-form fields

### ISSUE THREAD

**Issue by keerthinathganjam** [OfficeDev/office-ui-fabric-react#7314]
Any Example for using redux-form using office facric controls, similar to this

https://redux-form.com/6.7.0/examples/material-ui/

**Comment by kkjeer** [comment]
Hi @keerthinathganjam, we do not currently have examples with redux-form. Based on the example that uses material-ui, something like this should work:

```
import { Checkbox } from "office-ui-fabric-react"

const renderCheckbox = ({input, label}) => (
  <Checkbox
    label={label}
    checked={input.value ? true : false}
    onChange={input.onChange}
  />
);

...

<div>
    <Field name="employed" component={renderCheckbox} label="Employed" />
</div>

...
```

In addition to GitHub issues, our [StackOverflow](https://stackoverflow.com/questions/tagged/office-ui-fabric) page is a good resource for questions.
