### ISSUE TITLE
Dropdown defaultSelectedKey doesn't work when options are loaded async

### ISSUE THREAD

**Issue by Rafaelki** [OfficeDev/office-ui-fabric-react#7315]
#### Reproduction of the bug in a codepen:

<https://codepen.io/rafaelki/pen/gQVPQM>

#### Actual behavior:
When the options of the combo are provided asynchronously (from the state), the default option is not selected by using defaultSelectedKey (uncontrolled).
Using selectedKey (controlled) the combo shows the right selected value. 

 #### Expected behavior:
 
After setting the state and re-render, the combo should display the default option provided by defaultSelectedKey (uncontrolled).

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: (Normal)

**Comment by cliffkoh** [comment]
Thanks for reporting this and providing a codepen repro.
