### ISSUE TITLE
Custom Dropdown onRenderList has aggressive setFocus in Chrome 

### ISSUE THREAD

**Issue by katshew** [OfficeDev/office-ui-fabric-react#7318]
### Environment Information 
 
- __Package version(s)__: 6.90.0
- __Browser and OS versions__: Chrome Version 71.0.3578.80 (Official Build) (64-bit)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/katshew/pen/aQeKNg
 
#### Actual behavior:
 
Aggressive scroll to top behavior when attempting to override the onRenderList function on a dropdown. Does not seem to occur in Firefox. See link for video with more details.

https://microsoft-my.sharepoint.com/:v:/p/katshew/EcsWVkDqcvZPkBtIoagoImoBYtYXQD0stT1q2GXVTRTlZQ?e=CUWAHS

#### Expected behavior:
 
Searchbar and add button would be treated at part of the scrollable list, rather than excluded from list focus zone.

#### Priorities and help requested:
 
No
 
Requested priority: (Blocking, High, Normal, Low) 
 
Normal

**Comment by KevinTCoughlin** [comment]
Unrelated, but that's an awesome OneDrive/SharePoint URL.

**Comment by cliffkoh** [comment]
Thank you for the codepen repro and the video recording :)
