### ISSUE TITLE
Nav renders link as button

### ISSUE THREAD

**Issue by raix** [OfficeDev/office-ui-fabric-react#733]
I want to use react-router with the Nav, I wanted to use the `onClick` to intercept the default behaviour.

Expected no layout changes when adding the `onClick` handler to a link with an `url`

Actually renders as a button since it assumes some js action

Suggested solution might be to assume it being a button if `onClick` is set but not `url`.

```js
{ !!link.onClick && !link.url ? this._renderButtonLink(link, linkIndex) : this._renderAnchorLink(link, linkIndex, nestingLevel) }
```

or..

Use react to define `NavGroup`, `NavLink` and `NavButton` - flexibility / transparent.

Ref: [src/components/Nav/Nav.tsx#L134](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Nav/Nav.tsx#L134)

**Comment by dzearing** [comment]
@inateeg can you take a look? Seems like a simple improvement.

**Comment by panigrah** [comment]
How do I use react-router Link components inside the Nav component? @raix hoping you can help. 

I could use onLinkClick and `history.push()` to do this, is there another way. Could I use onRenderLink somehow? thanks!

**Comment by raix** [comment]
@panigrah I basically just used the router context and used a transistionTo (mind I'm on V4)

I just realized I didn't finalize a pr. https://github.com/raix/office-ui-fabric-react/tree/enhancement/733-nav-render-link-as-button (I'll see if I can get the time to add changelog etc..)

**Comment by panigrah** [comment]
@raix how do you stop propagating the event after transitionTo in the onclick? I tried event.stopPropagation() but it still resulted in a click thru.

**Comment by raix** [comment]
Stop default

**Comment by micahgodbolt** [comment]
Blocked, waiting for #5815

**Comment by micahgodbolt** [comment]
React Router support should be added with this PR

https://github.com/OfficeDev/office-ui-fabric-react/pull/7006
