### ISSUE TITLE
Android: After updated a date from calendar, it reads weird strings.

### ISSUE THREAD

**Issue by yumikohey** [OfficeDev/office-ui-fabric-react#7335]
### Environment Information 
Android Version : 8.1.0 
Android: Nexus 6 & Pixel 2 XL

### Please provide a reproduction of the bug in a codepen:
This is an accessibility bug.
If you open Fabric's Date Picker component from sample [website](https://developer.microsoft.com/en-us/fabric#/components/datepicker) via an Android phone, you will be able to repro the issue to have talkback on.

After it says "{Date1} replaced {Date2}", it reads "Capital Sunday space capital nov space 18". 
![android talkback calendar](https://user-images.githubusercontent.com/3360621/49666550-4b523e00-fa0d-11e8-8977-9bccaee2d838.PNG)

#### Actual behavior:
After it says "{Date1} replaced {Date2}", it reads "Capital Sunday space capital nov space 18". 
 
#### Expected behavior:
It should only read "{Date1} replaced {Date2}"

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) Normal
 
Products/sites affected: Onedrive

**Comment by kkjeer** [comment]
Hi @yumikohey, thanks for opening this issue! Currently we offer support for Narrator and JAWS. If you are familiar with Android screen reader and you'd be willing to create a pull request to fix this issue, we would be happy to review and merge your pull request.

**Comment by yumikohey** [comment]
@kkjeer I tested on a bootstrap date picker example, it actually behaves the same, so I think it's an Android built in issue. Should we close this issue?
Thanks.

**Comment by kkjeer** [comment]
@yumikohey thanks for testing! If this is built in to Android I think it makes sense to close this issue. Please feel free to close if you agree.
