### ISSUE TITLE
How do I get the element id of the date picker element at the onSelectDate function?

### ISSUE THREAD

**Issue by piyumi25** [OfficeDev/office-ui-fabric-react#7347]
<DatePicker
                className={labelTxt}
                label={item.Label + " : "}
                //className={dateTxt}
                strings={DayPickerStrings}
                showWeekNumbers={true}
                firstWeekOfYear={1}
                showMonthPickerAsOverlay={true}
                placeholder="Select a date..."
                ariaLabel="Select a date"
                key={index}
                onSelectDate={this.onRRDateChanged}
                id={item.Label}
              />
 this is the code I have used.

onRRDateChanged = (date: Date | null | undefined) => {
    console.log(date);
  };

**Comment by khmakoto** [comment]
Could you provide a more detailed description of what you intend to achieve as well as a codepen of what you have so far?

Thank you.

**Comment by piyumi25** [comment]
here I am creating date fields in a loop. So to identify each element I need to get the id of the element.

**Comment by khmakoto** [comment]
Can you provide a codepen with the code you have so far so that I can better see exactly what you want?

**Comment by piyumi25** [comment]
here is my code pen link.
https://codepen.io/piyumi28/pen/REPBZa I need to get this item value on SelectDate event

**Comment by khmakoto** [comment]
@piyumi25 the following [codepen](https://codepen.io/khmakoto/pen/KbVaPN) builds up on what you provided and logs both the `string` specified on your `dateItems` constant that relates to the selected `DatePicker` element, as well as the DOM `id` of the `DatePicker` itself.

Please let me know if this was what you were looking for or if you need anything else.
