### ISSUE TITLE
Convert ResizeGroup to new context API

### ISSUE THREAD

**Issue by ecraig12345** [OfficeDev/office-ui-fabric-react#7364]
As part of removing deprecated constructs in preparation for future React versions (see [this issue comment](https://github.com/OfficeDev/office-ui-fabric-react/issues/4613#issuecomment-446413003)), we need to remove usage of the legacy context API.

ResizeGroup is using legacy context via the `provideContext` utility function (see `packages/utilities/src/Context`). I'll make a change deprecating the utility function, but the component owner will need to update to use the new API.

See [the React docs](https://reactjs.org/docs/context.html) for more info about the new context API.

**Comment by micahgodbolt** [comment]
depending on the scope of this change, I might look to @christiango for help, as he did most of the heavy lifting on this control.

**Comment by christiango** [comment]
So the usage of context was added with https://github.com/OfficeDev/office-ui-fabric-react/pull/3718. I have depended used this "is measured" capability, so we might need @brwatt to drive this.

**Comment by brwatt** [comment]
The plan is to just switch to the new context API right? What information do you need from me?

**Comment by christiango** [comment]
I think your team is the only one use this feature, so we just want to make sure this doesn't break you.

**Comment by jdhuntington** [comment]
05ce7c263348168d0d59f91eef4cb4e72744258e
