### ISSUE TITLE
Layer tests and example are using legacy context API

### ISSUE THREAD

**Issue by ecraig12345** [OfficeDev/office-ui-fabric-react#7367]
As part of removing deprecated constructs in preparation for future React versions (see [this issue comment](https://github.com/OfficeDev/office-ui-fabric-react/issues/4613#issuecomment-446413003)), we need to remove usage of the legacy context API. 

The Layer component itself doesn't use legacy context, but for some reason (historical reasons?) some tests and an example do. Those should eventually either be converted to the new API, or have the context usage removed entirely.

**Comment by dzearing** [comment]
Because this is in a test, validly testing that old context works with layers based on portals, we should just keep it for now.
