### ISSUE TITLE
TextField component does not honor the "rows" attribute

### ISSUE THREAD

**Issue by prmittal** [OfficeDev/office-ui-fabric-react#737]
#### Actual behavior:
The input box created is of height 60px (since the height in "ms-TextField-field" is set to 32 px and min-height in ".ms-TextField.ms-TextField--multiline .ms-TextField-field" is set to 60px)

#### Expected behavior:
Height of box should be based on the row count provided

### Repro:
http://codepen.io/anon/pen/YNzRga

**Comment by dzearing** [comment]
It seems that the style selector `.ms-TextField.ms-TextField--multiline .ms-TextField-field` needs:

```css
height: auto
```

**Comment by dzearing** [comment]
Will be published in next batch.
