### ISSUE TITLE
DetailList - Screen reader is not passing the ascending/descending sorting information

### ISSUE THREAD

**Issue by saini-ankish** [OfficeDev/office-ui-fabric-react#7372]
### **Environment Information**

- Package version(s): (6.111.2)
- Browser and OS versions: (chrome and win 10)

### **Please provide a reproduction of the bug in a codepen:**
[https://codepen.io/anon/pen/YdXbQR](https://codepen.io/anon/pen/YdXbQR)

- Here we just adding tool-tips on header using **onRenderDetailsHeader**.
- In normal scenario it's having an addition Label tag containing the values for filterAriaLabel, sortAscendingAriaLabel or sortDescendingAriaLabel. Here it's not the same

### Actual behavior:
Screen reader is not passing the ascending/descending sorting information when we navigate on the column headers of the table.

### Expected Result:
Screen reader should pass the ascending/descending sorting information for the column headers. It should read it as" Account Name Column Header Collapsed, Data sorted in Ascending Order".

**Comment by khmakoto** [comment]
Already being tracked by bug #6646.

Closing as duplicate.
