### ISSUE TITLE
Is it possible to change scrollbar css in List Component 

### ISSUE THREAD

**Issue by harshdamaniahd** [OfficeDev/office-ui-fabric-react#7381]
Looking for some way to change default scrollbar look and feel

**Comment by khmakoto** [comment]
Can you be more specific about what you want to achieve and, if possible, provide a codepen with some initial code to build on? There are indeed some ways to style components, but a little more context will help us better answer your question.

**Comment by KevinTCoughlin** [comment]
> 
> 
> Looking for some way to change default scrollbar look and feel

The short answer is not easily as far as I know and this resides outside of the scope of OUFR. OUFR uses the browser's scrollbar and therefore the only customization you can do is override what the browser allows to be overridden. This varies browser to browser. Here's one resource which talks about scrollbar customization, https://css-tricks.com/almanac/properties/s/scrollbar/.

**Comment by harshdamaniahd** [comment]
@khmakoto https://css-tricks.com/almanac/properties/s/scrollbar/ this is what i was looking for.
But i think its good to kept it default, as it is an issue with all browsers

**Comment by KevinTCoughlin** [comment]
> 
> 
> @khmakoto https://css-tricks.com/almanac/properties/s/scrollbar/ this is what i was looking for.
> But i think its good to kept it default, as it is an issue with all browsers

Going to close given the author's response above. Please ping us here if you think this should be re-opened. However, I agree that it is best to keep the browsers default scrollbar styling.
