### ISSUE TITLE
Typescript error in IStyleFunction after upgrade

### ISSUE THREAD

**Issue by saicharanp** [OfficeDev/office-ui-fabric-react#7392]
I recently upgraded `office-fabric-react-ui` and  `@uifabric/merge-styles`  to latest version and I am getting a typescript error in the `IStyleFucntion`

```
import { IStyleFunction } from '@uifabric/merge-styles/lib';
import { IButtonStyles } from 'office-ui-fabric-react';
getStyles?: IStyleFunction<ITreeListSearchStyleProps, ITreeListSearchStyles>;

export interface ITreeListSearchStyles {
  root?: IStyle;
  header?: IStyle;
  headingLabel?: IButtonStyles;
}
```
Type IButtonStyles is not assignable to type IStyle​​​​​​​. 

It was working fine previously in version `5.132.0`.  

I tried updating typescript and it didn't work. I need to cast `headingLabel`  or `ITreeListSearchStyles` to `any` to make it work and it defeats the purpose of `typescript`.

**Comment by micahgodbolt** [comment]
Are you saying you upgraded to 6.x? Or did you upgrade to the latest version of the 5.x branch?

**Comment by saicharanp** [comment]
> Ah....I believe the change is that you'll need to use subComponentStyles for this
> 
> https://github.com/OfficeDev/office-ui-fabric-react/wiki/Component-Styling#icomponentstyles
> 
> I believe this was to fix a bug in which those button styles weren't actually working correctly.

Thanks for the reply.
Can you please tell me how do I refactor this? I tried the following and it is not working: 
``
export interface ITreeListSearchStyles {
  root?: IStyle;
  header?: IStyle;
subComponentStyles: {
   headingLabel?: IButtonStyles; 
  }
}
```

**Comment by micahgodbolt** [comment]
Would it be possible to mock this up in a codesandbox? Without seeing the code and the errors its hard to know what might be wrong.
