### ISSUE TITLE
swiping pivot doesn't work on smartphones

### ISSUE THREAD

**Issue by kirilligum** [OfficeDev/office-ui-fabric-react#7395]
### Environment Information 
 https://developer.microsoft.com/en-us/fabric#/components/pivot

on chrome browser on Note9 and iphone 6 plus
 

### Please provide a reproduction of the bug in a codepen:
  swiping left and right on the header or on the content

 
#### Actual behavior:
 nothing happens

 
#### Expected behavior:
 change of the content

#### Priorities and help requested:
 
I'm not sure how to debug it

Are you willing to submit a PR to fix? No
 
Requested priority: Blocking

**Comment by micahgodbolt** [comment]
I don't believe this functionality was ever present, please correct me if I'm wrong.

**Comment by kirilligum** [comment]
In the documentation


- Swiping left or right on a pivot item header navigates to the adjacent section.
- Swiping left or right on section content navigates to the adjacent section.

https://developer.microsoft.com/en-us/fabric#/components/pivot

Would be nice to have. Don't know if it was present. It's my first time trying

**Comment by micahgodbolt** [comment]
Hah, good catch :D I wonder if the docs simply got ahead of our implementation. Either way, there's a bug in docs or the control. Thanks!

**Comment by micahgodbolt** [comment]
And yeah, after a quick look at the code, we never wrote any functionality around swiping, so this just needs to be removed from the docs. @khmakoto will get that fixed. Maybe we can leave this issue open as a feature request when it's done.

**Comment by kirilligum** [comment]
that would be nice. if it works, I can just use pivot as a carousel for images. 

if someone had thought about it and can give me a rough roadmap, i can code it up

**Comment by micahgodbolt** [comment]
@betrue-final-final, do you know if touch navigation was ever considered/designed for the pivot? Is there a spec we could go off of to add it in?

**Comment by micahgodbolt** [comment]
lets be sure to create a new issue tracking adding swiping as a feature request
