### ISSUE TITLE
Compact controls

### ISSUE THREAD

**Issue by be5invis** [OfficeDev/office-ui-fabric-react#7397]
The current height (and spacing) of most controls are 32px, which is OK for most UI, but for UI requiring more density, it is less effective.

Therefore is it possible to introduce a new control size for professional applications that requiring more information density?

**Comment by betrue-final-final** [comment]
That is something we've been looking at in Design. This seems like a good place to inform of status once we figure that out.

**Comment by micahgodbolt** [comment]
This same question just came across via email, so I'm guessing this issue is related? I put together a quick PEN showing how it can be done today using each controls style prop. This can be done via customizer or directly into the control.

https://codepen.io/micahgodbolt/pen/NeNNjJ?editors=1010

The goal for the future is to move to a token based approach that will look more like this:

```
scopedSettings: {
   TextField: { tokens : {height: 26}},
   ComboBox: { tokens : {height: 26}},
   Dropdown: { tokens : {height: 26}}
 }
```

**Comment by Jahnp** [comment]
@micahgodbolt totally--we should take this approach for creating something like a "compact theme" or otherwise making compact versions of controls. To @betrue-final-final 's point, there will be more than just height involved, but enabling dense/compact/"complex" scenarios is *super* valuable.

**Comment by micahgodbolt** [comment]
if we leverage some type/spacing ramps in typography, we could pretty easily do this framework wide.

TextField default height = theme.spacing.default X 2 (i.e. twice the height of default text).

**Comment by be5invis** [comment]
@micahgodbolt Not really. Sometimes we want to just reduce the spacing, without sacrificing text size.

**Comment by micahgodbolt** [comment]
@be5invis yeah, i'd typically suggest typeRamp and spacingRamp to be different, though it's a valid question as to which one a TextField should use for it's line height.....Padding/margins would always use a spacing ramp.

**Comment by betrue-final-final** [comment]
We'll need some design work done here as it's an information design exercise. @micahgodbolt is correct, this could involve just padding, but occasionally text size on a case by case basis.
