### ISSUE TITLE
Styling choice group items

### ISSUE THREAD

**Issue by JoshuaLamusga** [OfficeDev/office-ui-fabric-react#7403]
It doesn't seem possible to provide styles for choice items. A choice group has these properties for styling:
> applicationRole
> flexContainer
> label
> root

None of these apply to choice items passed via the options prop. In the IChoiceGroupOption interface, there is no mention of any styling-related value we can pass to change the styles. I shouldn't have to use onRenderField() to redefine the layout any time I want to set styles.

Am I missing something?

### Environment Information 
 office-ui-fabric-react at ^6.87.0 with npm
 
Requested priority: **Normal**

**Comment by khmakoto** [comment]
Hi @JoshuaLamusga, ideally you'd be able to use the `style` native prop to provide styling for choice group options. However, while trying to ready a codepen on how this would be done, I've come to notice that this approach doesn't work right now. I'm opening an issue for this bug (#7430). Once that is fixed I'll provide a codepen to illustrate how styling could be done in this way.

**Comment by khmakoto** [comment]
Hi @JoshuaLamusga, if you take a look in [`ChoiceGroupOption.types.ts`](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroupOption/ChoiceGroupOption.types.ts) there is a `styles` prop defined with which you can style the different elements of a choice group option that are defined in the `IChoiceGroupOptionStyles` interface. Targeting `choiceFieldWrapper` should allow you to provide styling to choice group options. @micahgodbolt created a codepen illustrating this which you can find [here](https://codepen.io/micahgodbolt/pen/gZLNKj?editors=1010).

Please let us know if you need any more help.

**Comment by JoshuaLamusga** [comment]
That looks promising, khmakoto. I'll have to implement it tomorrow and see. I see choiceFieldWrapper defined under ChoiceGroupOption.styles.ts, but no styles under IChoiceGroupOption on the master branch right now.

**Comment by khmakoto** [comment]
Hi @JoshuaLamusga, I wasn't referring to `IChoicGroupOption` defined on `ChoiceGroup.types.ts` but to `IChoiceGroupOptionStyles` defined on `ChoiceGroupOption.types.ts`. The provided codepen should be pretty self-explanatory on how to implement styling.

Let me know if there is anything else I can help with.

**Comment by JoshuaLamusga** [comment]
Thanks Micah and khmakoto. I think that solves my problem and hopefully this question will be seen by someone looking to style choice items in the future.
