### ISSUE TITLE
Update the Teaching Bubble's default animation to use the new motion specs

### ISSUE THREAD

**Issue by bigbadcapers** [OfficeDev/office-ui-fabric-react#7413]
### Environment Information 
 
- __Package version(s)__: latest
- __Browser and OS versions__: any

### Please provide a reproduction of the bug in a codepen:
 
Invoke a teaching bubble and notice the animation, it's too bouncy. 
 
#### Expected behavior:
 
The teaching bubble's "stage entrance" should be designed to be noticeable, but the current animation curve has too many bounces and the acceleration in the final moments makes it feel like it's facing some unseen resistance, like molasses, which is unnerving. 

#### Priorities and help requested:
 
Requested priority: Normal 
 
Please replace the standalone teaching bubble's entrance animation with the animation used to reveal the teaching bubble in the moment when the mouse gets close to the coachmark. 

This is the resolution of https://github.com/OfficeDev/office-ui-fabric-react/issues/5874

**Comment by bigbadcapers** [comment]
@Jahnp fyi

**Comment by ecraig12345** [comment]
@Jahnp Can I assign this to you or one of the other design devs?

**Comment by bigbadcapers** [comment]
@ecraig12345 yeah this issue is the right resolution to #5874 - we dont want to overexpose too-granular animation controls for the teachingBubble unless the demand remains after fixing the broken animation.  should I close that other issue?

**Comment by Jahnp** [comment]
Adding @marygans who will be taking this one on!

**Comment by bigbadcapers** [comment]
> Adding @marygans who will be taking this one on!

WOOT! Hey Mary, this is carlos btw, im so sorry for my unfortunate github handle and welcome!! Lmk if i can help with anything here.

**Comment by nero120** [comment]
@marygans so glad you're sorting out this animation, looking forward to getting it!

**Comment by marygans** [comment]
Hi @bigbadcapers and @nero120 ! I would like to let you know that the TeachingBubble has been updated to a more subtle animation. I'm wondering if this resolves your issue?

**Comment by nero120** [comment]
That looks much, much better, thank you @marygans! 🙇
