### ISSUE TITLE
 ColorPicker does not update upon text field changes when alphaSliderHidden=true

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#7426]
Same issue #4525 happened before but it looks like regressed again in the latest version. 
When "alphaSliderHidden={true}" is removed, it works fine

### Environment Information 
 
 
- __Package version(s)__: Latest
- __Browser and OS versions__: Chrome

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/anon/pen/wRzWGN
 
#### Actual behavior:
 
The color is not changed after a text field change
 
#### Expected behavior:

The color is changed after a text field change

#### Priorities and help requested:
 
Requested priority: (High) 
 
Products/sites affected: SharePoint web parts

**Comment by ecraig12345** [comment]
Thanks for reporting this and providing a codepen! I'll work on a fix sometime in the next couple days.

**Comment by Nasicus** [comment]
Any updates on this?
