### ISSUE TITLE
Keystrokes are missed while typing in TextField control in IE11

### ISSUE THREAD

**Issue by nipunja** [OfficeDev/office-ui-fabric-react#744]
### Bug Report
- __Package version(s)__: 15.4.0
- __Browser and OS versions__: Internet explorer 11

#### Describe the issue:
Keystrokes are missed in TextField control while typing in IE11.

#### Actual behavior:
Keystrokes are missed while typing.

#### Expected behavior:
Keystrokes should not be missed.

### If applicable, please provide a codepen repro:
http://codepen.io/anon/pen/ggbWGr (Try it on IE11)

**Comment by mdahamiwal** [comment]
Its one of the known issue with React + IE11 if `onChange` is bind to a debounced delegate. In case of TextField, we have default deferred validation of 200ms and we miss the keystrokes during validation execution. 
I could fix this using `onInput` instead of `onChange`. [Check this codepen](http://codepen.io/mdahamiwal/pen/QdwaMw).

**Comment by nipunja** [comment]
Thanks manish for the update. The fix that you did in office fabric layer worked.  Is there any database where we can search all such known issues as we spent considerable time in discovering this issue.

**Comment by mdahamiwal** [comment]
@nipunja, its not exactly a fabric issue but an issue with React + IE11 combo. You can refer to https://github.com/facebook/react/issues/7027 for details. This seems to be fixed but will be released only with React 16 which will take some time. For now using `onInput` seems the only way to get around it. @mikewheaton, can we take this change [IE11 fix](https://github.com/mdahamiwal/office-ui-fabric-react/commit/b0f8c2993e1f3d32b135cea0aa8e52514941e147) ?

**Comment by dzearing** [comment]
@mdahamiwal it seems reasonable to me.

**Comment by nipunja** [comment]
Thanks @mdahamiwal for quickly fixing the issue.
