### ISSUE TITLE
Impossible to scroll the page on iPad mini after Modal window was opened and closed

### ISSUE THREAD

**Issue by ecoukraine** [OfficeDev/office-ui-fabric-react#7440]
### Environment Information 
 
 
- __Package version(s)__: 6.110.1 
- __Browser and OS versions__: iPad mini, OS - iOS 9.3.5

#### Actual behavior:

1. Open a web-page https://fabricweb.z5.web.core.windows.net/oufr/6.110.1/#/examples/modal on an iPad mini
2. Page can be scrolled
3. Open Modal 
4. Close Modal
5. Page cannot be scrolled

#### Expected behavior:
 
Page should be scrollable after Modal close

#### Priorities and help requested:
 
Requested priority: High

**Comment by ecraig12345** [comment]
Thanks for reporting! I can't repro this on my iPhone or Mac, so I'll have to figure out how to get ahold of an iPad for testing.

@ecoukraine Are you using Safari, or some other browser? Also, do you happen to know if this issue is specific to the iPad mini or does it happen with a full-size iPad too?

**Comment by ecraig12345** [comment]
@ecoukraine One more thing, are you closing the modal using the button or by tapping outside of it?

**Comment by ecoukraine** [comment]
Hi @ecraig12345, thank you for your answer. 

I also cannot reproduce it on iPhone/Mac/iPod/iPad(big one). 
It can be reproduced only on iPad MINI using Safari browser.

Looking forward to hearing from you

**Comment by ecoukraine** [comment]
@ecraig12345 ,

it's does not matter how you close the modal window: I've tried the CLOSE button and tapping near the Modal. The page cannot be scrolled in both cases.

**Comment by micahgodbolt** [comment]
@ecoukraine you say this only repros on the iPad mini? If it works on the bigger iPad it makes me wonder if there is a browser difference. The size of the device/screen shouldn't have any affect on the modal.

**Comment by ecraig12345** [comment]
I just tried this using BrowserStack on an iPad mini running iOS 11 and a simulated iPad Mini running iOS 9 and wasn't able to repro on either of them (though I did notice that the website looked funny on iOS 9). That makes me wonder, @micahgodbolt do you know if we even support iOS 9 any more? 

![image](https://user-images.githubusercontent.com/5864305/50574741-08894900-0db4-11e9-8f37-7af5659c97b2.png)

**Comment by micahgodbolt** [comment]
![image](https://user-images.githubusercontent.com/1434956/50601967-beaf6a00-0e6a-11e9-92b8-9c1c24fe1630.png)

We should be supporting iOS 12 and 11. @ecoukraine if your ipad has an older version of iOS, try upgrading.

**Comment by ecoukraine** [comment]
@micahgodbolt thank you, will try.
