### ISSUE TITLE
Improve dev experience when doing work in @uifabric/experiments

### ISSUE THREAD

**Issue by cliffkoh** [OfficeDev/office-ui-fabric-react#7444]
As far as I'm aware, we don't presently have documentation for how to do work in `@uifabric/experiments`. The NPM scripts also will not work since they only build to `office-ui-fabric-react`. 

Users will today either have to utilize rush to do `rush build --to @uifabric/experiments` or `rush build` without arguments, which requires that they have rush globally installed. The alternative is to utilize the install_run_rush.js script but that is extremely unintuitive.

Regardless, we need to have a more cohesive (and documented) story here.

Related: #7442

**Comment by khmakoto** [comment]
I've found that `npm run buildfast` does build the `experiments` package, so that's another alternative.

**Comment by cliffkoh** [comment]
`buildfast` does `install_run_rush build` so that would work :) We just need to document this then.

**Comment by khmakoto** [comment]
Yeah, adding documentation for `buildfast` should also help in other regards since it's also the way to do incremental builds. I can take up the task of updating documentation, just unsure of where to put all this. Should I add it as part of the 'Setup' page or should we add a separate 'Building' page to the Wiki?

**Comment by ecraig12345** [comment]
I don't quite understand why the default install task only builds up to office-ui-fabric-react (also why it does a full build not incremental)--why not change it to build up to experiments? Also, I don't think it's unreasonable to ask people to have Rush installed globally as long as we document it.

**Comment by micahgodbolt** [comment]
seems like adding some npm scripts would do the trick right? We want to make it easy for devs to launch the experimental controls

`npm run experiments`

Is there more to this than creating this alias?

**Comment by cliffkoh** [comment]
This would work too. @khmakoto has volunteered to take up this task (it's not a lot of work :))

**Comment by cliffkoh** [comment]
Most of the work would be writing the documentation in the wiki!

**Comment by khmakoto** [comment]
Yes, all of this seems like good things to discuss adding/add to the wiki. Will do that once I come back.

**Comment by ecraig12345** [comment]
Was just talking to David about this and he suggested that instead of adding a new alias, we update the default postinstall script to build up to experiments instead of office-ui-fabric-react. Thoughts? (This would also fix #7454.)

**Comment by ecraig12345** [comment]
IIRC `npm start` doesn't work after the default build because foundation and/or experiments hasn't been built...if that's correct, the first run experience is already broken. (Verifying right now.)

**Comment by ecraig12345** [comment]
Hmm never mind it does work...maybe I was thinking of npm start in experiments? Regardless, I don't think the impact of building to experiments is that bad--it's only two additional packages.

**Comment by cliffkoh** [comment]
Would you be able to get actual timings to quantify the exact impact? We need this data anyway if we're doing it so we're completely eyes open on the trade off/impact/side effects.

**Comment by khmakoto** [comment]
@cliffkoh running the current `npm install` that builds to oufr my computer took 2 minutes 9.8 seconds.

When updated so that `npm install` builds to experiments it took it 2 minutes 16.6 seconds.

**Comment by khmakoto** [comment]
#7529 documents `buildfast` in the `README`, but we still need a smarter solution for this. I will talk with @kenotron to see what we can do.

**Comment by khmakoto** [comment]
Per a discussion with @dzearing, will make npm install build to experiments and close this issue, and maybe later separately think about a smarter way of providing this.
