### ISSUE TITLE
Search box re-render when value is null leads to TypeError

### ISSUE THREAD

**Issue by srinidhiprabhu96** [OfficeDev/office-ui-fabric-react#7449]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Normal) 

Products/sites affected: (if applicable)

#### Issue:

Use a SearchBox inside another React component.
Do not type anything into the SearchBox.
Update the React component (without updating the SearchBox). This leads to re-render of the SearchBox.

#### Actual behavior:
The re-rendering causes this error:
TypeError: Cannot read property 'length' of null

#### Expected behavior:

There should be no error. The SearchBox component must normalize null or undefined to empty string on component update.

In the code, we see that if 'null' or 'undefined' is passed in the beginning, the constructor handles it and normalizes it to an empty string. However, there is no normalizing done when the component is re-rendered.

**Comment by ecraig12345** [comment]
Hi @srinidhiprabhu96, thanks for reporting this. Would you mind sharing a link to a page where this repros, or [creating a codepen](http://aka.ms/fabricpen) to demonstrate?

**Comment by srinidhiprabhu96** [comment]
You can find the codepen [here](https://codepen.io/srinidhiprabhu96/pen/dwNxEQ).

**To Repro:**
Click on the "Click Me" button.

**Expected:**
 The text on the button changes to "Hello".

**Actual:**
The button and search box are no longer displayed.
We get an error in the console: Uncaught TypeError: Cannot read property 'length' of null
