### ISSUE TITLE
BasePicker: add description and errorMessage props

### ISSUE THREAD

**Issue by laiprorus** [OfficeDev/office-ui-fabric-react#7457]
Add description, errorMessage, and possibly onGetErrorMessage props on Picker components (especially PeoplePicker).
Those props a present TextField and only provide additional text below the input box. Since Pickers are similar input boxes, they could be used in a form with descriptions and validation rules.
![issue](https://user-images.githubusercontent.com/33106132/50350614-ec79e200-053f-11e9-84b4-0f85812101fb.jpg)

**Comment by ecraig12345** [comment]
Hi @laiprorus, thanks for reaching out and for using Fabric! This is definitely something we can consider adding, but unfortunately the people who'd be in the best position to evaluate or help implement this are out for the holidays. So we can come back and discuss it more in January. (If you want to try adding it yourself and submitting a pull request, you're welcome to do that too!)

**Comment by Vitalius1** [comment]
cc: @joschect

**Comment by dzearing** [comment]
The idea would be to create a general wrapper component which renders label/error that can wrap any form component.

Could use a codepen.

**Comment by ThreadPitt** [comment]
Yes, this is really needed...

**Comment by khmakoto** [comment]
Closing this in favor of #3620.
