### ISSUE TITLE
Skinny Nav component on small screens - HOWTO?

### ISSUE THREAD

**Issue by panigrah** [OfficeDev/office-ui-fabric-react#747]
how do I get the Nav component to become skinny on small screens as suggested in the documentation?

The documentation says;

the Nav is always on-screen, usually on the left of the view. In smaller configurations, the Nav may collapse into a skinnier version or be completely hidden until the user taps an icon.

thanks,

**Comment by mikewheaton** [comment]
Sorry for the confusion here, it looks like [Nav component](http://dev.office.com/fabric#/components/nav) is intended to be narrower on small screens, but this functionality hasn't been implemented yet. I'll reach out to our designers to see if we have designs for this.

In the meantime, `.ms-Nav` will expand to fill whatever container it is placed in, so you could use a media query to shrink its parent container on smaller screens. This wouldn't change the design so the amount you can shrink it by would be limited, but it may help. Here's a [CodePen example of how to do that](http://codepen.io/mikewheaton/pen/PWwdGX).

**Comment by panigrah** [comment]
Thanks @mikewheaton. What's the recommended way to close the nav on small screens and have it slide open on click of icon?

**Comment by mikewheaton** [comment]
@panigrah: The container that holds the Nav will need to be shown and hidden when the button is clicked. You can use one of the [Fabric animation classes](http://dev.office.com/fabric#/styles/animations) such as `ms-u-slideRightIn10` to get a nice slide and fade in effect.

**Comment by panigrah** [comment]
thanks @mikewheaton. I put a Nav into a Panel instead of using the animation class.

**Comment by dzearing** [comment]
I am closing this; let us know if you need anything else. :)
