### ISSUE TITLE
ContextualMenu calloutProps usage?

### ISSUE THREAD

**Issue by liuyangc3** [OfficeDev/office-ui-fabric-react#7470]
calloutProps dose not expose in `IContextualMenuProps`
but use in code

https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.base.tsx#L226

so it can be uesd in jsx but not tsx?

**Comment by atneik** [comment]
I don't fully understand the problem you're facing. Is it possible to replicate the problem in a codepen? [`IContextualMenuProps` does contain `calloutProps` ](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.types.ts#L198), that could be used to set custom callout props.

**Comment by liuyangc3** [comment]
as you said, IContextualMenuProps does contain calloutProps.  I got it wrong.
