### ISSUE TITLE
Selected nav item stops event add on it

### ISSUE THREAD

**Issue by liuyangc3** [OfficeDev/office-ui-fabric-react#7476]
### Environment Information 
 
 
- __Package version(s)__: 6.117.2
- __Browser and OS versions__: Chrome

### Please provide a reproduction of the bug in a codepen:
 
https://codesandbox.io/s/ol9p37znr9
 
#### Actual behavior:
 
contextmenu event did not fire out on an selected item
 
#### Expected behavior:
 
event runs

**Comment by atneik** [comment]
Hi Yang! If I understand correctly, there is minor bug in your code. Check if this does the job: https://codesandbox.io/s/7wp2461v0q. In `span` I think you meant `onClick` instead of `onContextMenu`

**Comment by liuyangc3** [comment]
Hi @atneik  I konw what I am using,   `onContextMenu` is a SyntheticEvent which  react  (supported)[https://reactjs.org/docs/events.html#supported-events],  I want to `RightClick` on a NavItem, then fire a mouse event.

the reason than mouse  event can not fire is because a when item is `selected`, a css pseudo-element  `:after`  overrides `span`. and I think this is a bug.

**Comment by atneik** [comment]
Thanks for the above explanation. Here is the PR to fix the issue: #7495
