### ISSUE TITLE
Cannot focus on commandbar item correctly. Get wrong ref from by using componentRef attribute in commandbar item.

### ISSUE THREAD

**Issue by KeiraYang** [OfficeDev/office-ui-fabric-react#7481]
### Environment Information 
 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by KeiraYang** [comment]
Get wrong commandbar button ref. I use componentRef of command bar item and extend focus for getting focus to commandbar item when something in the page lose focus. But just found I get the ref for the <div> which has attribute visibility: hidden. And after get the ref for hidden command bar button element to focus to the button, the button will be unmounted soon. There are two <div> both are commandbar from ResizeGroup.base.tsx

**Comment by micahgodbolt** [comment]
Here's an example of component refs to command bar. If this doesn't answer your question, can you fork/update the pen to describe your issue?

https://codepen.io/micahgodbolt/pen/BOpMPz

**Comment by KeiraYang** [comment]
![image](https://user-images.githubusercontent.com/28148759/50534045-582c0280-0b71-11e9-854e-c33b0fb1433d.png)

I also get the null ref when using the codepen -> open the dev tools -> click on the 'Open Command Bar Item'.

**Comment by micahgodbolt** [comment]
I'm sorry, seems there was some loading order issue on the javscript. I've updated the pen and it is working as expected now.

https://codepen.io/micahgodbolt/pen/BOpMPz?editors=1010
