### ISSUE TITLE
Combobox get stuck when trying to load more than 50000 items

### ISSUE THREAD

**Issue by piyumi25** [OfficeDev/office-ui-fabric-react#7489]
for my case there are nearly 50000 items in the list. so when click on combobox it is getting stuck and addin time out.

**Comment by atneik** [comment]
Hi @piyumi25 thanks for reporting the issue. Are you using a `VirtualizedComboBox`? I'll recommend it over a usual `ComboBox` for large number of items.

I tried reproducing it in [this codepen](https://codepen.io/atneik/pen/roGmEy) with no luck. It will help us investigate if you could reproduce the issue in an isolate environment (feel free to fork the codepen).

**Comment by micahgodbolt** [comment]
I can repro the issue if you switch back to a non virtualized comobobox. Yeah, virtualized is the way to go there.

**Comment by micahgodbolt** [comment]
we're looking at updating combobox/dropdown. I'll make mention to consider adding this feature as a prop vs a different component (which we aren't promoting very well) #6030.

**Comment by piyumi25** [comment]
thank you very much for your reply and this solute my problem
