### ISSUE TITLE
Dropdown selects an option when navigating with arrow keys

### ISSUE THREAD

**Issue by satbai** [OfficeDev/office-ui-fabric-react#749]
### Bug Report
- __Package version(s)__: 0.82.3

#### Describe the issue:
Dropdown component fires onChange event every time arrow keys are used to navigate through options. This causes problems in certain cases, e.g. wanting to fire an Action on selected option that re-renders the component.

#### Actual behavior:
Arrow down selects the next option.

#### Expected behavior:
Arrow down focuses on the next option, and enter key selects the option.

**Comment by dzearing** [comment]
@eliblock12 can you take a look I agree with this; it should read it aloud in the screen reader, it should set focus to the item, but shouldn't change the actual selection until committing.

**Comment by aleksandrjPersonal** [comment]
This appears to be fixed in the module-css-update branch. Repros in master, not in module-css-updates. Closing as already fixed.

**Comment by satbai** [comment]
Thanks! @aleksandrjPersonal or @dzearing or someone else who knows, which version will this be in (and available in production)? We had an accessibility run with a blind person and one of the pain points was that the selection happened before clicking enter (or space?).
