### ISSUE TITLE
Interactive in a custom row column render not trigger DetailsList update

### ISSUE THREAD

**Issue by jayliang701** [OfficeDev/office-ui-fabric-react#7490]
I try to use onRenderItemColumn to custom DetailsList's cell render.  There is a onClick in a cell content: 
<pre><code> //render method
&lt;DetailsList 
  ....
  items={this.state.items}
  onRenderItemColumn={ (item, index, column) => {
    if (column.key === 'selector') {
      console.log('render cell --> ', index, column.key);
      return &lt;span onClick={(evt) => this.updateItem(item, true)}&gt;update&lt;/span&gt;;
     } else {
       return item[column.fieldName];
     }
    }
  } 
  ...
/&gt;</code></pre>

"updateItem" method will update the name value of the row's data. But DetailsList doesn't update view as my expect. The strange thing is:
1. when I click the "<span>update</span>" cell in second row, "onRenderItemColumn" method will be executed.
2. then execute "updateItem" method.
3. DetailsList doesn't update view ("onRenderItemColumn" method doesn't be triggered).
4. when I click the "<span>update</span>" cell in first row, "onRenderItemColumn" method will be executed. Now I can see the new value in second row.

Please check the demo on codepen:
[https://codepen.io/anon/pen/pqWoBp?editors=0011](url)

and check the console's output.

**Comment by atneik** [comment]
Hi Jay! DetailsList doesn't re-render if an item is updated in a given array. You could either copy and provide a new array while `setState` ([here is the codepen](https://codepen.io/atneik/pen/QzqMEO)) or call `forceUpdate` on the component itself (both of them are expensive and should be used sparingly). If you're curious you can check out the conditions below that will actually cause a re-render:

https://github.com/OfficeDev/office-ui-fabric-react/blob/410922aad2271f96e3c01dd600028128ffa38eaa/packages/office-ui-fabric-react/src/components/List/List.tsx#L324

I hope this help.
