### ISSUE TITLE
Collapsible Section should allow other components in title instead of just text

### ISSUE THREAD

**Issue by testgithubd** [OfficeDev/office-ui-fabric-react#7493]
**Describe the feature that you would like added**
I had a look at the experiments folder and the Accordion and Collapsible Section components specifically. Currently they allow just text as title. A useful addition would be to make it more generic and accept other components as well.

**What component or utility would this be added to**
Accordion and Collapsible Section

**Have you discussed this feature with our team, and if so, who**

**Additional context/screenshots**
An example would be if I want to build something like below:
![image](https://user-images.githubusercontent.com/45836381/50524933-656fc100-0a8d-11e9-8e84-1b4ad1a30f81.png)

Or If I want to add dropdowns and textboxes to my section headers.

**Comment by micahgodbolt** [comment]
yeah, this is already in progress. @JasonGore is having fun adding slots to the control. Don't worry, it'll be much more full featured when launched.
