### ISSUE TITLE
Update Pivot component with semantic slots

### ISSUE THREAD

**Issue by bennettclark** [OfficeDev/office-ui-fabric-react#7496]
**Describe the feature that you would like added**
There are new redlines for the Pivot fabric component that specify semantic slots.

https://microsoft.sharepoint.com/teams/WebPartTheming/Shared%20Documents/Forms/AllItems.aspx?id=/teams/WebPartTheming/Shared%20Documents/Redlines/Navigation/navigation-pivot-redlines.pdf&parent=/teams/WebPartTheming/Shared%20Documents/Redlines/Navigation&p=true&slrid=64fdad9e-f0be-0000-b690-3dfab39cf474

**What component or utility would this be added to**
Pivot component

**Have you discussed this feature with our team, and if so, who**
@JasonGore advised me to open this issue

**Comment by atneik** [comment]
I labeled this one a backlog item as I notice, looking at the spec, it will require some design updates (pressed & selected hover states) along with semantic slots.

@bennettclark do you happen to know who is the design contact on this?

**Comment by bennettclark** [comment]
The design contact is Sirena Myint.
