### ISSUE TITLE
Pivot: Show icon in PivotItem link

### ISSUE THREAD

**Issue by cschleiden** [OfficeDev/office-ui-fabric-react#750]
We have a requirement to show an icon next to/instead of the PivotItem link text.
I was thinking of just adding an `itemIcon` property, similar to the one in `Button` to the `PivotItem` props. 

Example from my branch how it would look like, with different combinations of text/count/icon:

![image](https://cloud.githubusercontent.com/assets/2201819/21701175/0a445196-d359-11e6-9cf3-e9b64e1d779a.png)

![image](https://cloud.githubusercontent.com/assets/2201819/21701180/10059b6c-d359-11e6-99fe-36b83b93c5da.png)

RTL:
![image](https://cloud.githubusercontent.com/assets/2201819/21701190/159d3080-d359-11e6-9890-d266512638d4.png)

**Comment by dzearing** [comment]
Another approach would be to allow the tabs to be customized. That way the icon could be a font icon or an image, or some other component.

```ts
onRenderTab?: IRenderFunction<TabProps>;
```

But icon addition might be a simpler to consume approach.

**Comment by cschleiden** [comment]
Hm, yes, valid point. I thought adding an icon would be simple enough to implement and usable in enough scenarios that an extra property would be worth it.

**Comment by cschleiden** [comment]
Talked to the designers, we want to bring it to the design meeting next week, I'll wait for that, and then make changes depending on the outcome.

**Comment by dzearing** [comment]
Do you mind closing out the PR if you don't want to check it in? I'm going to move a bunch of stuff to the new repo location this weekend so i'm trying to clean up PRs.
