### ISSUE TITLE
Nav onRenderLink not fullfill link area

### ISSUE THREAD

**Issue by liuyangc3** [OfficeDev/office-ui-fabric-react#7502]
### Environment Information 
 
 
- __Package version(s)__: 6.118.2
- __Browser and OS versions__: Chrome

### Please provide a reproduction of the bug in a codepen:
 
https://codesandbox.io/s/ol9p37znr9
 
#### Actual behavior:
 
clicking on red zone not fire custom event defined in `onRenderLink`

![image](https://user-images.githubusercontent.com/6705844/50578478-cc1e2180-0e75-11e9-88d4-13714cdb0316.png)

 
#### Expected behavior:
 
`span` fullfill  red zone

**Comment by cliffkoh** [comment]
Hi @liuyangc3, thanks for the codesandbox repro which helped me help you.

I was able to resolve the issue you're experiencing with a slight modification to your code:

From line 55 (your `onRenderLink` function), I changed it to the following.

```ts
 onRenderLink = link => {
    return (
      <div
        onClick={e => {
          alert(2);
        }}
        onContextMenu={e => this.onContextMenu(e, link)}
        style={{
          "flexGrow":1,
          "textAlign": "left"
        }}
      >
        {link.name} 123
      </div>
    );
  };
```

**Comment by liuyangc3** [comment]
@clikkoh thanks，I think this is the right way to do it.
