### ISSUE TITLE
[Screen Reader - Filter Dropdown]: "Selected/Non-Selected" State property is not defined for 'Menu items' under "Filters runs" Pane.

### ISSUE THREAD

**Issue by sonimishra** [OfficeDev/office-ui-fabric-react#7504]
User Experience:
If the State Properties of control is not defined, then screen reader dependent user will not be able to interact with it properly.

Check out Keros! - Identify accessibility bugs before check-in and make bug fixing faster and easier.

Pre-Requisite:
Multiple Runs should be available for Flow.

Repro Steps:
1. Open URL :https://preview.flow.microsoft.com and sign in using valid credentials.
2. Navigate to "My Flows" menu item on the left navigation pane and select it.
3. My Flows list page opens, navigate to any flow (with multiple runs) and select it.
4. Flow Description page appears, navigate to Run History tile  and select "See all>" button.
5. Run History page opens, navigate to Runs Filter on top right and select it.
6.  Dropdown with multiple filter option appears, navigate on dropdown.
7. Open Developer tool and inspect the "menu items" under Drop down.
8. Observe the issue.

Actual Result:
"Selected/Non-Selected" State property is not defined for 'Menu items' under "Filters runs" Pane.

Expected Result:
"Selected/Non-Selected" State property should be defined for Menu items under "Filters runs" Pane. It should read it as "Successful runs menu item 2 of 7 Selected".

![mas4 1 2_filter dropdown](https://user-images.githubusercontent.com/30456910/50591556-56867580-0eb6-11e9-828a-44a4c545ae99.png)

**Comment by cliffkoh** [comment]
Hi @sonimishra, it appears you're using the Fabric CommandBar component, which takes in an object that extends IContextualMenuItemProps for the `farItems`. These are in turn able to take in any HTML attributes, including relevant aria properties to indicate that an item is selected (Contextual Menu itself does not manage selection state).

There is no bug in Fabric components - this is a bugfix that should be taken at the app side.

Please also make sure to create a reduced repro in the future in a codepen/codesandbox or via a link to a Fabric example page (at https://aka.ms/fabricdemo).

**Comment by cliffkoh** [comment]
I made a mistake in my original triage where I mistakenly looked at `IContextualMenuItemProps` as opposed to `IContextualMenuItem`.

`IContextualMenuItem` has the concept of whether an item is checked or not, but not if it is selected or not. If you pass in the `checked` props (https://github.com/OfficeDev/office-ui-fabric-react/blob/636413fa17e8a1d030870abafba6d84431de200b/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.types.ts#L330), it should at least set the `aria-checked` attribute on it.

**Comment by cliffkoh** [comment]
Spoke with Anubhav Aggarwal offline - he will check if using `checked` results in a satisfactory experience for this specific scenario.
