### ISSUE TITLE
How to make CommandBar vertical 

### ISSUE THREAD

**Issue by liuyangc3** [OfficeDev/office-ui-fabric-react#7512]
like VSCode
![image](https://user-images.githubusercontent.com/6705844/50622664-f6d9aa00-0f49-11e9-9553-49e63d926d41.png)

add `flex-direction: column` not work

**Comment by cliffkoh** [comment]
Vertical layout is not a support feature of command bar. @micahgodbolt can confirm.

**Comment by liuyangc3** [comment]
is there a componet can do this except overflowset @cliffkoh

**Comment by micahgodbolt** [comment]
Vertical overflow set and command bar buttons makes a great vertical sidebar. Normal command bar has a ton of logic to make it fit horizontally.

**Comment by micahgodbolt** [comment]
We are also working on a Leftnav control to cannonize this pattern. Should be a few more months still.
