### ISSUE TITLE
BasePicker onInputFocus called on wrong component when there are multiple Pickers

### ISSUE THREAD

**Issue by xli1000** [OfficeDev/office-ui-fabric-react#7524]
### Environment Information 
 
- __Package version(s)__: 6.119.0
Downgrading to 6.118.0 got rid of this issue.
- __Browser and OS versions__: (fill this out if relevant) Chrome 70.0.3538.67 and Windows 7

### Please provide a reproduction of the bug in a codepen:
 
Add two pickers that extend BasePicker.  Focus the first picker and then the second one. Focus the first one again. 
 
#### Actual behavior:
`onInputFocus` will be called on the second picker when the first picker is focused. It seems that it is being called from `resetFocus`; I think this was likely introduced by #7487.
 
#### Expected behavior:
`onInputFocus` should not be called on the second picker when the first picker is focused.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No
 
Requested priority: (Blocking, High, Normal, Low) Normal
 
Products/sites affected: (if applicable)

**Comment by cliffkoh** [comment]
@joschect

**Comment by joschect** [comment]
@xli1000 that PR should have only impacted controlled pickers, do you have a codepen as an example?
