### ISSUE TITLE
Allow number format for slider

### ISSUE THREAD

**Issue by ethanroday** [OfficeDev/office-ui-fabric-react#7526]
Let's say I have a slider that goes from 0% to 100%, like so:

![image](https://user-images.githubusercontent.com/896670/50703350-a2493400-1008-11e9-8f30-674d446265c3.png)

### Current Behavior

As is, I need to have a separate element that displays the value, since I can't format the value of the slider.

Slider component:
```jsx
<div className="slider-row">
  <div className="slider">
    <Slider min={0} max={100} step={1} value={value} showValue={false} onChange={onChange} />
  </div>
  <div className="slider-value">{`${value}%`}</div>
</div>
```

Styles:
```sass
.slider-row {
  display: flex;
  align-items: center;

  .slider {
    flex: 1;
  }

  .slider-value {
    padding-left: 12px;
  }
}
```

### Desired Behavior

I would love to just be able to do this:

```jsx
<Slider
  min={0}
  max={100}
  step={1}
  value={value}
  showValue={true}
  valueFormat={value => `${value}%`}
  onChange={onChange}
/>
```

**Comment by atneik** [comment]
Issue merged and released in :tada:`office-ui-fabric-react@v6.120.0`
