### ISSUE TITLE
ActionButton outline on focus gets clipped

### ISSUE THREAD

**Issue by avenezia** [OfficeDev/office-ui-fabric-react#7528]
### Environment Information 
 
 
- __Package version(s)__: 6.112.0
- __Browser and OS versions__: Chrome 71.0.3578.98

### Please provide a reproduction of the bug in a codepen:
 https://codepen.io/avenezia/pen/YdexRm

 
#### Actual behavior:
 
Depending on the value of the overflow property of the parent container, the outline on focus of the ActionButton gets clipped. 
 
#### Expected behavior:
 
The outline on focus should be visible like, for example, for the DefaultButton.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: Power Query Online

**Comment by cliffkoh** [comment]
Funny thing is that it doesn't repro on the dev site

![image](https://user-images.githubusercontent.com/1003246/50723286-62c62a80-1090-11e9-979e-cb5d02f2fdc8.png)
https://fabricweb.z5.web.core.windows.net/oufr/6.119.0/#/examples/button
