### ISSUE TITLE
Command bar flickers on resize

### ISSUE THREAD

**Issue by Adjective-Object** [OfficeDev/office-ui-fabric-react#7532]
### Environment Information 
 
- __Package version(s)__: 6.119.0
- __Browser and OS versions__: Repro'd in chrome Version 71.0.3578.98, Firefox 64.0 on Windows

### Please provide a reproduction of the bug in a codepen:
 
https://fabricweb.z5.web.core.windows.net/oufr/6.119.0/#/examples/commandbar 
Scroll down to the example and resize the browser window slowly when it is thinner than the max width of the command bar

#### Actual behavior:
 When resizing a command bar, command bar flickers the next visible item (an items is shown for a single frame, then disappears).

See https://youtu.be/Wtwo3dqRD2I

#### Expected behavior:
 Command bar should not show the next item when all widths during resize are too small to allow the item to show

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) Yes, but I'm not sure where to look for a fix.
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by cliffkoh** [comment]
Thanks for reporting issue, and in particular thank you for the detailed repro steps (the video recording helped!)

@micahgodbolt, is this something you can take a look at, given that this bug is purely within Command Bar?

**Comment by micahgodbolt** [comment]
it appears that the copy of the command bar that is used for measurement is being displayed. It should be invisible.

**Comment by micahgodbolt** [comment]
oddly though, i'd expect the issue to also be on resizeGroup (as it does the duplicating and hiding, but it appears to be working fine).

**Comment by micahgodbolt** [comment]
Ok, last observation. It only happens on grow (not shrink).

**Comment by micahgodbolt** [comment]
@christiango any thoughts why command bar would be displaying the 'measured div' on grow data?

**Comment by christiango** [comment]
Seems strange. We don't see that for the Ribbon, which uses ResizeGroup directly instead of command bar. Were there any recent changes to command bar or resize group?

**Comment by cliffkoh** [comment]
Just adding co-assignees. I will still stay assigned as well.

**Comment by christiango** [comment]
@micahgodbolt , wow, that was awesome how quickly you were able to go back and find the regression!

**Comment by micahgodbolt** [comment]
yeah, would have taken forever without all of those prebuilt versions.

**Comment by kenotron** [comment]
I'm struggling to figure how removing aria attributes or even the cache key thing could affect it like that...
