### ISSUE TITLE
DetailsList: Items data with html tag. How to render 

### ISSUE THREAD

**Issue by komal4364** [OfficeDev/office-ui-fabric-react#7535]
Hi,
I am using office-ui-fabric-React. We are detailsList component, which is used to display the items in list.
The data is received from the REST API Call, Some of the column data, has html tags associated with it.
We want to show user only the content in html tags, not html tags, and highlight the text in html.
How to handle that in DetailsList Component.
In angular, this can be solved using [innerHTML]="data" (Ref: https://stackoverflow.com/questions/34936027/angular-2-how-do-you-render-html-from-a-json-response-without-displaying-the-ta/34937279 )

The following is the example I referred. In that, the sortedItems has column data which has html tags in it.
https://github.com/OfficeDev/office-ui-fabric-react/blob/2ce6c5ac3ccf4e62d4866841317b4aa55b8fb541/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.CustomColumns.Example.tsx

**Comment by KevinTCoughlin** [comment]
I'm in agreement with @Vitalius1.

@komal4364, you'll likely get more traction for this question on [StackOverflow](https://stackoverflow.com/questions/tagged/office-ui-fabric). We encourage you to post this question there either using the `office-ui-fabric` and / or the `reactjs` tag.

**Comment by komal4364** [comment]
I have spoken to Vitalius1 (I am a Microsoft employee). Recommendation is to customize the rendering of column using RenderItemColumn prop of DetailsList. Will try it. Thanks Vitalius1.
