### ISSUE TITLE
Command Bar does not honour subMenuProps for sub menu items

### ISSUE THREAD

**Issue by AkshanshSrivastava03** [OfficeDev/office-ui-fabric-react#754]
### Bug Report

- __Package version(s)__: ^0.82.3
- __Browser and OS versions__: (fill this out if relevant)

#### Describe the issue:
**[Command Bar issue]:**
As use of "Items" under IContextualMenuItem has been deprecated and use of submenuProps is advised, creating "submenu items for an item" in Command bar does not work. It does not work fine with submenuprops as its _onItemClick function fills the state with item.items only (where Items has been deprecated) and not checked for submenuProps (using hasSubmenuItems function) which leads to empty "items" under the submenu of Command bar.

#### Actual behavior:

Nothing shows up in the dropdown of for an item containing submenu items

#### Expected behavior:

I should be able to see and select the sub menu items for an item in Command bar

**Comment by dzearing** [comment]
@joschect or @MLoughry can you take a look?

**Comment by joschect** [comment]
It definitely doesn't make use of the submenuProps. Should be pretty easy to add.

**Comment by MLoughry** [comment]
I have a fix, I'm just trying to get the regression tests for it working.

**Comment by joschect** [comment]
@MLoughry Awesome. Thanks!

**Comment by dzearing** [comment]
Thanks @MLoughry !
