### ISSUE TITLE
TagPicker: suggestion list is shown strangely

### ISSUE THREAD

**Issue by nguyentoantuit** [OfficeDev/office-ui-fabric-react#7543]
### Environment Information 
- __Package version(s)__: 6.119.0

If I set both value 
...
onEmptyInputFocus={() => _testTags}
selectedItems={[_testTags[0]]}
...

#### Actual behavior:
The suggestion list will auto show when I check then uncheck the checkbox **Disable Tag Picker**
 
#### Expected behavior:
Only show suggestion list when we focus on picker.

**Comment by nguyentoantuit** [comment]
Please note that this issue didn't occur in version 6.118.0

**Comment by Vitalius1** [comment]
@joschect looks like #7487 is mentioned again in an issue. Can you take look into this and see if a regression was introduced by it? Thanks.

**Comment by joschect** [comment]
Yes, this appears to be a regression. Should be an easy fix.

**Comment by Vitalius1** [comment]
Would you be willing to look into it real quick as you already have context with the issue and the PR introduced it? Thanks!

**Comment by joschect** [comment]
Yep! already looking at it!

**Comment by Vitalius1** [comment]
@joschect any progress on this?
