### ISSUE TITLE
Navigation List Expand and Collapse only Up/Down it has no feature Left/Right

### ISSUE THREAD

**Issue by shahprashant1990** [OfficeDev/office-ui-fabric-react#7544]
**Currently, Expand/Collapse working only up/down way not as Left/Right direction**

URL: https://developer.microsoft.com/en-us/fabric#/components/nav

**Comment by Vitalius1** [comment]
@micahgodbolt is this something `Nav` component is planned to support?

**Comment by micahgodbolt** [comment]
so, like a command bar? are we talking about changing the orientation of the nav? Do you have a visual example?

**Comment by micahgodbolt** [comment]
Do you just mean multiple levels of nesting? 
![image](https://user-images.githubusercontent.com/1434956/50843547-bef1ae80-131d-11e9-80f6-3c7ccf4fec6e.png)

If you have a visual mockup of what you want, that'd really help.

**Comment by shahprashant1990** [comment]
I need orientation of collapse/expand as below image and user can experience left/right collapse/expand functionality. 

![output_pk2dgm](https://user-images.githubusercontent.com/40460701/50879178-051f3e80-1400-11e9-9f33-2358049f9799.gif)

But in Navigation component there is no feasibility to have left/right collapse/expand functionality. Kindly see below image & URL for same:

![output_q1zllu](https://user-images.githubusercontent.com/40460701/50879331-90003900-1400-11e9-90b3-564de7447344.gif)

https://developer.microsoft.com/en-us/fabric#/components/nav

**Comment by Vitalius1** [comment]
@shahprashant1990 I am still confused by your demo what is the exact visual representation of what you are trying to achieve.

Could [this](https://gyazo.com/0da2111d773f9db8ada84c907f96392e) be of a better representation of what you are looking for?
![2019-01-09 16 31 14](https://user-images.githubusercontent.com/29514833/50938375-c5bb1700-142c-11e9-95bb-3ac43c11ea09.gif)
