### ISSUE TITLE
Calendar/ContextualMenu: Focus gets trapped on up/down arrows when calendar is placed in contexual menu

### ISSUE THREAD

**Issue by nikhilpuria** [OfficeDev/office-ui-fabric-react#7546]
### Environment Information 
 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

 https://codepen.io/nikhilpuria/pen/KbRwOa?editors=0010

 
#### Actual behavior:
 dates of the **Calendar** component are not accessible using keyboard when Calendar is used inside a CommandBar / ContextMenu

 
#### Expected behavior:
 Dates of Calendar component should always be accessible

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
No (Not sure of the fix for this) 

Requested priority: (Blocking, High, Normal, Low) 
High

Products/sites affected: (if applicable)
Microsoft Teams

**Comment by micahgodbolt** [comment]
btw, i don't think the best approach for putting a calendar in a menu is to use a contextual menu. Here's an example of the calendar in a custom callout.  https://codepen.io/micahgodbolt/pen/MZGMqR?editors=0010

But this does bring up the question of multiple focus zone items inside of a contextual menu item, though that might be a much lower priority bug if the above solution works.

**Comment by micahgodbolt** [comment]
in the command bar https://codepen.io/micahgodbolt/pen/roKBgZ?editors=0010

**Comment by nikhilpuria** [comment]
The above codepen looks good .The only potential issue is that I am not able to dismiss the callout on pressing esc

**Comment by micahgodbolt** [comment]
Oh, you'll see there is an onDimiss there calling the closeMenu. You might need to tweak that a bit.

**Comment by Vitalius1** [comment]
https://codepen.io/vitalius1/pen/vvrYMZ
@nikhilpuria I added the componentRef to the calendar button item and now the `onDismiss` works. I believe this solution is optimal and I agree with @micahgodbolt that `contextualMenu` is not the best approach.

@nikhilpuria @micahgodbolt should we consider this issue good to be closed?

**Comment by micahgodbolt** [comment]
hah! totally missed the componentRef didn't I :D

**Comment by micahgodbolt** [comment]
I'm fine closing this. I think there might be some discovery to be done with multiple focus zones in a contextual menu item, but then again, it's not something we'd often recommend doing (maybe a searchbox, but not much more complex than that).

**Comment by Vitalius1** [comment]
Agree on that. A contextualMenu with items being highly interactive seems wrong in using it. The purpose of that menu is to choose an item from a list. So your approach with a callout is best in this case.

**Comment by Vitalius1** [comment]
Closing it as it looks like the author got a working solution from Micah.
