### ISSUE TITLE
DetailsList component crash the browser tab

### ISSUE THREAD

**Issue by fantua** [OfficeDev/office-ui-fabric-react#755]
### Bug Report

- __Package version(s)__: 0.77.1
- __Browser and OS versions__: Chrome, macOS

#### How to reproduce:

1. Create page with DetailsList component: http://prntscr.com/ds5065
2. 

- Click on empty place of page: http://prntscr.com/ds50y2
- Or on some padding of element: http://prntscr.com/ds51l3

3. Tab crashed: http://prntscr.com/ds53sj

The problem is in method [_isNonHandledClick](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/utilities/selection/SelectionZone.tsx#L444), condition for while is incorrect. When we click on empty place of page or on element padding, the [element](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/utilities/selection/SelectionZone.tsx#L453) is html, as we all know html has no parent so there are no exit from while: http://prntscr.com/ds56lx

#### My hot fix: 
```js
      while (element && element !== doc.documentElement && element.parentElement) {
        if (isElementTabbable(element)) {
          return false;
        }

        element = getParent(element);
      }
```

If that is ok, I can create a pull request.

**Comment by dzearing** [comment]
I believe this was fixed in version 0.80.1, with this change:

https://github.com/OfficeDev/office-ui-fabric-react/commit/b704394736cdeef996cb7cf4f8e67b7dae7856ba
