### ISSUE TITLE
Context menu sub-links don't expand on hover if all links have href

### ISSUE THREAD

**Issue by hamedy** [OfficeDev/office-ui-fabric-react#7562]
got a fix for a bug I reported initially but found a new bug on the same component, case has been reopened but it's being ignored for some reason. 

https://github.com/OfficeDev/office-ui-fabric-react/issues/7419

can we have a simple menu component that works? can I not be let down and disappointed by Microsoft for once in my life? 

thanks, 
Hamed

**Comment by Vitalius1** [comment]
@ecraig12345 do you mind looking into this as you already did the fix once and have more context? It looks like the author is still having issues in IE.

**Comment by Vitalius1** [comment]
@hamedy I will close the issue as it seems it's remainings from the #7419 fix and @ecraig12345 already reopened it.
