### ISSUE TITLE
Styles prop is not showing in Dropdown component?

### ISSUE THREAD

**Issue by piyumi25** [OfficeDev/office-ui-fabric-react#7564]
I am trying to use dropdown and I need to change the font family of label text. So I tried to use styles prop for that. but it shows following error.
Property 'styles' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Dropdown> & Pick<Readonly<{ children?: ReactNode; }>

what should be the reason for this?

**Comment by Vitalius1** [comment]
@piyumi25, it would really help if you could provide a codepen with the issue you are facing. It might be very possible that you are not applying the prop correctly and a repro would help us catch that.

With that said here is a quick [codepen](https://codepen.io/vitalius1/pen/qLymyy) which should illustrate how to pass styles to label accompanying the Dropdown. If this answers your question feel free to close the issue.

And again, I would like to reiterate the importance of following our template when filing an issue. You can find links in the template to some already built codepens for various components which can help you in a demoing a quick repro of your issue.

P.S. In helping us to help you we would be able to provide a solution much faster.

Thanks for using Fabric and filing issues 😄

**Comment by piyumi25** [comment]
This is issue I got.
![dropdown](https://user-images.githubusercontent.com/33615108/50876395-d77fc880-13f2-11e9-94dc-5e033961eff9.png)

**Comment by Vitalius1** [comment]
Wait... I don't get it from the screenshot. Are you passing anything to styles at all? Also, the way you are trying to style it through `style` not `styles` I don't think it will work.

Anyway, I hope you see now the value of having a repro in codepen so that we can play around with it and see what is that you are doing wrong. Does the codepen I provided solves your issue with label styling?

**Comment by piyumi25** [comment]
my issue is when I am trying to use styles it shows an error.

**Comment by Vitalius1** [comment]
Hmmm... what is the Fabric version you are using? Also, what is the TypeScript version? (again, this questions should not be happening if the issue template is filled with all the necessary info).
