### ISSUE TITLE
Fabric Website: Add support for versioned documentation

### ISSUE THREAD

**Issue by aditima** [OfficeDev/office-ui-fabric-react#7570]
We need to have the ability to select a specific Fabric release version and view documentation for that version, instead of just the latest.

This is an ask from SharePoint customers, tracked here: https://github.com/SharePoint/sp-dev-docs/issues/3217

**Comment by Jahnp** [comment]
Hey @aditima , I think #7269 has some more details for the work required. For the sake of tracking history, do you mind if we re-opened and renamed that issue to track this?

**Comment by Jahnp** [comment]
You bet! Done and done. Closing this for now. Thanks @aditima !
