### ISSUE TITLE
Contextual Menu Section Headers not announced via narrator

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#7572]
Not 100% sure how these should be announced, but needed to take a look at this for the bug below.

This can be reproed on our website.

@betrue-final-final any examples of other UI where narrator properly speaks section headers?

Internal work item
https://office.visualstudio.com/OC/_workitems/edit/2588494

**Comment by Vitalius1** [comment]
@micahgodbolt we are currently skipping the Section Headers when using VoiceOver on Mac. Are you going to look yourself into this issue? If not, then to whom should I assign the issue? I don't not much experience with readers plus I don't have the environment setup on my machine (Mac) to use the narrator.

**Comment by betrue-final-final** [comment]
That's a tricky question I've been trying to figure out. In scan mode they will be read on normal down arrow navigation probably as a menu item, which is incorrect. Out of scan mode it will be skipped.
I wonder if the first item in the section can be "<name>, menu item, first item in <section name> section"?

**Comment by Vitalius1** [comment]
@micahgodbolt @betrue-final-final 
In Narrator scan mode, when navigating to the section header it reads out `Contains 0 items, *section name*`, so it's definitely a bug that needs to be investigated.

**Comment by Vitalius1** [comment]
@betrue-final-final @micahgodbolt can we restart the discussion on this topic? Do we read out the section headers and if yes what should be read?

**Comment by Vitalius1** [comment]
🤔 hmmm... anyone?

**Comment by micahgodbolt** [comment]
Crickets I know. Honestly not 100% sure the solution here. It's design driven, that's for sure.

**Comment by jspurlin** [comment]
FYI, this was fixed by https://github.com/OfficeDev/office-ui-fabric-react/commit/978edb71c86f2c4a32411b7b78097a26fb6e9044#diff-570dcaf84c12ad2593f547152a02ba16
