### ISSUE TITLE
Controlled multi-select ComboBox not working properly

### ISSUE THREAD

**Issue by criticalbyte** [OfficeDev/office-ui-fabric-react#7579]
### Environment Information 

- __Package version(s)__: 6.121.0
- __Browser and OS versions__: All browsers, Windows

### Please provide a reproduction of the bug in a codepen:

 See https://codepen.io/criticalbyte/full/NeBXRB
 
#### Actual behavior:
 
1. Controlled multi select ComboBox won't allow you to select multiple options using your mouse.
2. After deselecting the checked option, strangely some other option gets selected by itself.
 
#### Expected  behavior:

1. User must be able to select multiple options using mouse and see the check boxes get checked.
2. After deselecting a checkbox another checkbox must not get selected by itself. 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: High

**Comment by Vitalius1** [comment]
@ecraig12345 seems like it's related to #6030 epic issue. Should we consider closing this issue due to the upcoming refactor of ComboBox/Dropdown? Or if you want we can keep it open and assign it to you.

**Comment by ecraig12345** [comment]
The codepen is copied from the multi-select part of `ComboBox.Controlled.Example.tsx`, and it's possible that the bug is fully/partially due to the example code...in which case we should fix the example. :) It's also quite possible that both the example and the ComboBox itself have bugs. Either way I think it's worth keeping open as a separate issue for the time being.

**Comment by Vitalius1** [comment]
As you are already looking into ComboBox refactor/rewrite/merge with Dropdown, would you mind having this issue assigned to you?

**Comment by ecraig12345** [comment]
That's fine for now, though it's possible I'll be moving to different work soon and won't actually be the one to do the refactor.

**Comment by Vitalius1** [comment]
@criticalbyte there is some major work planned to do with ComboBox in the nearest future. We apologize for the inconvenience and we expect this bug to be fixed with that work, but it might take some time. Have you tried using Dropdown multi-select?

**Comment by criticalbyte** [comment]
> @criticalbyte there is some major work planned to do with ComboBox in the nearest future. We apologize for the inconvenience and we expect this bug to be fixed with that work, but it might take some time. Have you tried using Dropdown multi-select?

no i have not, i need the free form functionality of the ComboBox which does not seem to be available with the Dropdown component.

can't we have a hot-fix for it?

**Comment by ecraig12345** [comment]
Potentially, but I'm pretty busy at the moment, so I won't have time to even look into the feasibility of an intermediate fix right away.

**Comment by criticalbyte** [comment]
@ecraig12345 how long will it take to be fixed?

**Comment by micahgodbolt** [comment]
This is now fixed. 

6.121.0

![combo](https://user-images.githubusercontent.com/1434956/71689623-63eb6f80-2d57-11ea-9163-14169b1ca1c1.gif)

as of 7.78.0

![combo](https://user-images.githubusercontent.com/1434956/71689677-84b3c500-2d57-11ea-89e8-549613bc59f7.gif)
