### ISSUE TITLE
SetState in MaskedTextFields moves focus between fields in IE and breakes Edge's tab

### ISSUE THREAD

**Issue by IvanTurashov** [OfficeDev/office-ui-fabric-react#7580]
### Environment Information 
 
 
- __Package version(s)__: 6.121.0
- __Browser and OS versions__: Edge 17, IE11, Windows 10

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/IvanTurashov/pen/gZGdzW?editors=1010

 
#### Actual behavior:

 IE 11: 
- I fill part of first field
- I fill part of second field. All is ok
- I return to first and start continue input
- First symbol inputed in first field, and focus jumps to second field

![](http://g.recordit.co/CdSxWIL6Pv.gif)

Edge: if I move focus from first to second, then browser's tab will break.
 
#### Expected behavior:
 
Any number of fields will filled correctly, like as in Chrome

#### Priorities and help requested:
 
It works correctly without setState in onChange.

Are you willing to submit a PR to fix? No
 
Requested priority: Blocking

**Comment by Vitalius1** [comment]
@lambertwang any ideas? Can you look into this?

**Comment by lambertwang** [comment]
Huh, that's really strange. It doesn't repro in FF or Chrome for me, so I'm guessing there's some undefined or undocumented IE api that is causing this behavior. I will try to take a look this evening

**Comment by Vitalius1** [comment]
@lambertwang thanks 👍

**Comment by Jahnp** [comment]
@lambertwang just checking, is this something you were able to look into? Thanks!

**Comment by Vitalius1** [comment]
@ecraig12345 tagging for FYI

**Comment by bdeterling** [comment]
Here is another example in Safari 13.0.4. Click in the masked field, then type in the non-masked field and the focus moves back to the masked field on every keystroke. Works fine in Chrome.

https://codepen.io/bdeter/pen/gObKBgw

**Comment by Vitalius1** [comment]
@ecraig12345 assigning to you as the code owner of TextField.
