### ISSUE TITLE
Fetch values from textfields in order on button click?

### ISSUE THREAD

**Issue by xyz92** [OfficeDev/office-ui-fabric-react#7590]
I have a UI as follows:

[![!\[enter image description here][1]][1]

The fields are coming from an API call response. The number of fields coming from API response can vary. In the image, it is 3. It can vary. Please see my code in:

https://codepen.io/lipalath/pen/dwqNXr
     
On clicking OK button, how do I get values from textboxes in order such that textbox1 value is for Name, textbox2 value is for Age, textbox3 value is for Gender?

Note: I didn't receive any response from StackOverflow: https://stackoverflow.com/questions/53566744/fetch-values-from-textfields-in-order-on-button-click
That's why I am posting my question here. Please let me know if you have any solution on the same. Thank you!

  [1]: https://i.stack.imgur.com/LKWIi.jpg

**Comment by xyz92** [comment]
@Vitalius1 Thank you so much! What version of office ui fabric are you using? I see error on componentRef:

![untitled](https://user-images.githubusercontent.com/6519992/50984147-fb581280-14b5-11e9-935d-dffe3371b3bf.jpg)

I wonder if this because I'm using a lower version of office ui fabric. I'm using 5.124.0. Please let me know what version you are using. 

Also where should I import IRefObject from?

![untitled](https://user-images.githubusercontent.com/6519992/50984275-55f16e80-14b6-11e9-8fe3-c05816971a50.jpg)

Please let me know. Thank you!

**Comment by Vitalius1** [comment]
@xyz92 I did take a look and can confirm because you are on 5.124.0 is the reason why you can not use the componentRef the same way I did. And for the same reason, you can not import `IRefObject` as it didn't exist in that version.

Is there anything stopping you from upgrading to the latest Fabric 6 which is 6.124.0 as of today? The example I provided you is using this version.

**Comment by xyz92** [comment]
@Vitalius1 Thank you so much! I don't see error after upgrade. One more question about the code. Is there a way to know which value belongs to which field? For example, push both field_name and field_value into inputValues array? –

**Comment by Vitalius1** [comment]
@xyz92 I updated the https://codepen.io/vitalius1/pen/OroprE. You can find a good start in there for what you are looking for but keep in mind that is something I quickly tried to demo and should not be taken as a final solution for production code 🙄 . Feel free to close the issue if it solves your scenario.

**Comment by xyz92** [comment]
@Vitalius1 Thank you!
