### ISSUE TITLE
Facepile: maxDisplayablePersonas doesn't accept 0 as a value

### ISSUE THREAD

**Issue by tabrumle** [OfficeDev/office-ui-fabric-react#7601]
### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/tabrumle/pen/Vqxodx
 
#### Actual behavior:
 
Passing in 0 to maxDisplayablePersonas returns a facepile with all the personas rendered as coins
 
#### Expected behavior:
 
Passing in 0 to maxDisplayablePersonas returns a Facepile with no personas. This case could be used for scaling logic when the browser is shrunk and we want to reduce the Facepile to just an overflow button.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal 
 
Products/sites affected: WAC

**Comment by Vitalius1** [comment]
@tabrumle 
Thanks for filing the issue. I see you are willing to submit a PR in fixing this. Thanks for that too. Let us know if you need any help.
