### ISSUE TITLE
Panel height has probably regressed

### ISSUE THREAD

**Issue by soorajcodehub** [OfficeDev/office-ui-fabric-react#7606]
### Bug Report

    "office-ui-fabric-react": "6.117.1",
chrome (all)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low)  Normal

Products/sites affected: (if applicable)
SharePoint 

#### Describe the issue:
All panel have height issues. 
![image](https://user-images.githubusercontent.com/7365681/51001013-8bf91780-14e3-11e9-8261-a8dff473df0e.png)

![image](https://user-images.githubusercontent.com/7365681/51001085-c5318780-14e3-11e9-8f06-36898f6bcc9c.png)

![image](https://user-images.githubusercontent.com/785361/51001804-1773a800-14e6-11e9-91b3-a948fa71d72f.png)

#### Actual behavior:

The height being set on panel content seems to have changed. It seems to add scroll bars, when not necessary, or wrap its inner content when not necessary. The content doesn't seem to fill the panel

#### Expected behavior:

In SharePoint, as soon as we switched from 5 to 6 we noticed this breaking behaviour. 
This PR could be the cause : https://github.com/OfficeDev/office-ui-fabric-react/pull/6614

**Comment by dzearing** [comment]
@kkjeer One person's bug is another person's feature :) Could you take a look and see if we need to revert? or, is there something we could help instruct here?

@soorajcodehub you cut the browser off in your screenshots, which browser/platform?

**Comment by soorajcodehub** [comment]
It was chrome on windows

**Comment by dzearing** [comment]
@soorajcodehub thank you. We will get a fix out asap once people are in the office in the morning.

**Comment by soorajcodehub** [comment]
I think it looks okay in the codepen. Is there a way we can test if in
realy scenarios.

Thanks
Sooraj

**Comment by kkjeer** [comment]
@soorajcodehub I didn't make any changes to Fabric code for the codepen (or this codepen for the second example: https://codepen.io/kkjeer/pen/WLYwJm). These would be changes you would make to the styles in your codebase. Please let me know if the styles in the codepen don't work with your code.

**Comment by soorajcodehub** [comment]
Oh I see. I mean we can override styles at our end and make it work. But
every downstream use of xxl panel is busted. I am not aware of the issue
you were referring to, but might be a good idea to make a base change that
fixes both issues, if a plain revert isn't possible.

**Comment by kkjeer** [comment]
If you are willing to create a codepen with your current Panel styling, that would be very helpful to me in trying to find a fix. Otherwise, I'm not sure how to go about making changes in Fabric that could mitigate this.

**Comment by atneik** [comment]
Here is a codepen which might help investigating the issue: https://codepen.io/atneik/pen/oJRROO

The problem seems to be in `contentInner` which changed in v6:

v5:
![capture-panel-old](https://user-images.githubusercontent.com/785361/51356969-88c8d300-1a71-11e9-9f79-f8d074f76ade.PNG)

v6:
![capture-panel](https://user-images.githubusercontent.com/785361/51356964-849cb580-1a71-11e9-8308-6fb23151b646.PNG)

**Comment by soorajcodehub** [comment]
does Aniket's codepen help? Thanks!

**Comment by kkjeer** [comment]
By adding `flex-grow: 1` to .ms-Panel-contentInner, v6 and v5 look the same in the codepen: https://codepen.io/kkjeer/pen/bzdqwV

Without a codepen demonstrating your scenario, I don't know if this would fix the issue you're seeing. Could you please either:
1. Create a codepen that reproduces your issue, or:
2. Try adding `flex-grow: 1` to .ms-Panel-contentInner in your styles and see if that fixes the issue?

Thanks!

**Comment by kkjeer** [comment]
@atneik I'm not sure whether `flex-grow: 1` would fix this issue. I can try it and if it doesn't cause any other breaking changes to our existing tests, we can check it in and see if that fixes this issue. Otherwise, I would say that v5 to v6 is a breaking change for Panels.
