### ISSUE TITLE
Can I focus out from the combobox using code?

### ISSUE THREAD

**Issue by piyumi25** [OfficeDev/office-ui-fabric-react#7611]
I need to focus out from the combobox in the onMenuDismiss event. Is it possible to do it?

**Comment by Vitalius1** [comment]
Can you elaborate more your scenario? Maybe even provide a codepen ([starter codepen](https://codepen.io/vitalius1/pen/PXyOeq)). It's really hard to help you if you don't provide enough context. Thanks!

**Comment by piyumi25** [comment]
this is my code pen https://codepen.io/piyumi28/pen/xmypVe?editors=1111
I am creting comboboxes dynamically and until focus out from the combobox the value is not appeared. I think if I can focus out when menu is dismissed the value may be show in the text box.

**Comment by Vitalius1** [comment]
Not sure if it's a bug or not. Needs more eyes from someone familiar with the component. @jspurlin @stanleyymsft @ecraig12345 FYI.

**Comment by Vitalius1** [comment]
@piyumi25 I modified the codepen you provided (https://codepen.io/vitalius1/pen/GPeBaB) and it looks like everything is working except the issue where you don't see the options while selecting (tracked in #7558 as a feature request).
There were a couple of things wrong in the usage of multiple `ComboBoxes` on the same page. I left some comments to make clear what was wrong.

Will mark it as not an issue. Feel free to close the issue or leave it and it will be closed automatically by the bot.

**Comment by piyumi25** [comment]
thanks for your help.
