### ISSUE TITLE
Independently scroll ms-Grid-col similar to mdContent from angular material

### ISSUE THREAD

**Issue by panigrah** [OfficeDev/office-ui-fabric-react#763]
How do I vertical scroll the content inside a ms-Grid-col independently of the other columns? Is there a component like the mdContent directive in angular material?

https://material.angularjs.org/latest/api/directive/mdContent

This component expands to take up all the space and anything content inside it scrolls independently of other content.

thanks,

**Comment by cschleiden** [comment]
Can't you just set the `overflow` property of your column `div` to `auto` or `scroll`?

**Comment by dzearing** [comment]
Yes agree. Define a css rule for a scrollable div.

Please reopen if you need more help.
