### ISSUE TITLE
CommandBar custom render element not aligned

### ISSUE THREAD

**Issue by liuyangc3** [OfficeDev/office-ui-fabric-react#7633]
### Environment Information 
 
 
- __Package version(s)__: 6.119.0
- __Browser and OS versions__: Chrome

### Please provide a reproduction of the bug in a codepen:
```
<CommandBar
     items={[
      {
        key: 'test',
        name: 'test',
        iconProps: {
          iconName: 'AddFavorite'
        },
      },
      {
        key: 'test1',
        onRender: item => <Dropdown ... />
      },
      {
        key: 'test2',
        onRender: item => <SearchBox placeholder="Search" />
      },
    ]}
/>
```
 
#### Actual behavior:
 

![image](https://user-images.githubusercontent.com/6705844/51109458-406ea280-1830-11e9-82ad-ab37982b4ab0.png)

 
#### Expected behavior:
 

![image](https://user-images.githubusercontent.com/6705844/51109753-24b7cc00-1831-11e9-8dc4-fba7b2adcd93.png)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by micahgodbolt** [comment]
Can you provide a codepen example of this? In general, custom elements aren't automatically aligned. You might have to do some work to get fixed height elements to fit into a command bar that's taller than most of our inputs. 

On the flipside of that, if there's something simple we can do to make elements align better, I'm all for it.

**Comment by liuyangc3** [comment]
@mikewheaton, @micahgodbolt   thanks,  `alignItems: 'center'`  works well
