### ISSUE TITLE
custom tabIndex in custom column rendering of detailedList overwritten

### ISSUE THREAD

**Issue by Rainson12** [OfficeDev/office-ui-fabric-react#7634]
#### Actual behavior:
 
when setting the tabIndex of a custom rendered element in an IColumn the tabIndex is being overwritten with -1
 
```
{
    key: 'from',
    name: 'from',
    fieldName: 'from',
    maxWidth: 64,
    minWidth: 64,
    tabIndex: 0,
    onRender: item => (<input type="text"  tabIndex={0} />)
  } as IColumn
```

#### Expected behavior:
 
tabIndex shouldn't be overwritten

**Comment by mikewheaton** [comment]
Could you provide a repro of this issue so we can take a closer look? Here's a CodePen that serves as a good starting point: https://aka.ms/fabricpen
