### ISSUE TITLE
ChoiceGroup: data-is-focusable not set on selected option

### ISSUE THREAD

**Issue by haonliu** [OfficeDev/office-ui-fabric-react#7644]
### Environment Information 
 
 
- __Package version(s)__: 6.121.0
- __Browser and OS versions__: Win10 Chrome

### Please provide a reproduction of the bug in a codepen:
 

 https://codepen.io/anon/pen/PXVJwG
#### Actual behavior:
 none of the radio button has data-is-focusable = true

#### Expected behavior:
  the first radio button should have data-is-focusable = true

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) Yes.
 
Requested priority: (Blocking, High, Normal, Low) Normal.
 
Products/sites affected: (if applicable)

**Comment by mikewheaton** [comment]
Thanks for the CodePen repro. I found a comment in the code that confirms the first enabled option should be set to focusable:

```
// In cases where no option is checked, set focusable to first enabled option so that ChoiceGroup remains focusable.
```

I'll look into this and see where the logic is failing.

**Comment by dzearing** [comment]
https://codepen.io/dzearing/pen/MZxQeQ

The `data-is-focusable` attribute is useful for FocusZone scenarios. This codepen illustrates the effect that happens when it's not present (you can't arrow to the choice group.)
