### ISSUE TITLE
DetailsList example snapshots are incomplete

### ISSUE THREAD

**Issue by ecraig12345** [OfficeDev/office-ui-fabric-react#7651]
In the snapshots generated by ComponentExamples.test.tsx of the examples for DetailsList and GroupedList (and probably anything else using `@withViewport`), all the examples just show up like this, which is not very helpful for catching regressions:

https://github.com/OfficeDev/office-ui-fabric-react/blob/7936641bfbc8e9d201cddb36be14aebccd85466e/packages/office-ui-fabric-react/src/components/__snapshots__/DetailsList.CustomRows.Example.tsx.shot#L4-L12

To fix, we'd need to either pass the prop `skipViewportMeasures: true` to all the relevant examples somehow (kind of like what ComponentConformance.test.tsx does), or make the viewport decorator detect when a test is running and automatically skip measurement.

**Comment by KevinTCoughlin** [comment]
Thanks for following up here @ecraig12345 🙇. I want to fix this problem in some way.

`@withViewport` has been half of the reason for my resize performance woes with `DetailsList`. We should evaluate if its worth keeping the component before investing further (my opinion).

For additional context, I've taken two approaches at consolidating `resize` calls into one in my local dev. They are:

1) Refactor `withViewport`'s `resize` handler logic into `DetailsList` and remove `withViewport` entirely.
    - This is a significant change and required modifying some call flows to get the column adjustments to fire correctly.
2) Keep `withViewport`, but _optionally_ disable the `resize` logic in `List.tsx`.
    - This was a less invasive code change, but modifies the public API and feels a tad hacky.

Will follow-up in the AM with additional info and branches.

**Comment by ecraig12345** [comment]
@KevinTCoughlin Thanks for the context! Could I assign this to you since you've worked a lot with DetailsList and you're already thinking about withViewport issues?

**Comment by KevinTCoughlin** [comment]
> 
> 
> @KevinTCoughlin Thanks for the context! Could I assign this to you since you've worked a lot with DetailsList and you're already thinking about withViewport issues?

Sure, that makes sense.

**Comment by ecraig12345** [comment]
One idea I had for a fix was to try something like this in `ComponentExamples.test.tsx` `beforeAll` (then revert in `afterAll`):
```
const origDetailsListDefaultProps = DetailsListBase.defaultProps;
DetailsListBase.defaultProps = {
  ...(origDetailsListDefaultProps || {}),
  skipViewportMeasures: true
};
// same for GroupedListBase
```

Another idea is setting a global variable like `__IS_RUNNING_TEST` in the test, and if it's true, `withViewport` always sets `skipViewportMeasures` to true. This is simpler, but not sure if it's a pattern we consider acceptable.

**Comment by KevinTCoughlin** [comment]
Closing as this should have been resolved with the above linked PRs which contain the updated snapshot files.
