### ISSUE TITLE
Option to display TextField in error state without rendering error message.

### ISSUE THREAD

**Issue by redoz** [OfficeDev/office-ui-fabric-react#7652]
**Describe the feature that you would like added**
I'd like to be able to indicate an error with the TextField without rendering the error message.
The reason for this is that the error message is displayed elsewhere in the UI.
From reading the source it seems the approach with least impact would be to add a error message render function (`onRenderError`?) to the properties so it can be overridden from the outside (in my case with a noop).

**What component or utility would this be added to**
TextField and probably all other input components that have the same behavior.

**Have you discussed this feature with our team, and if so, who**
No.

**Additional context/screenshots**
![image](https://user-images.githubusercontent.com/1670030/51186579-386b3d00-18da-11e9-83bf-ba207504bfa0.png)

I'd like to be able to not-show the error message underneath the input box, while keeping the "error state" of it (e.g. the red outline).

**Comment by dzearing** [comment]
@kkjeer Is the bot ok?

**Comment by dzearing** [comment]
@ecraig12345 something to think about IRT what the contract may look like to support this.

**Comment by redoz** [comment]
Would you consider a PR that adds an optional `onRenderError` property that lets you override the default render behavior as a quick work-around? Or would hacking it out with CSS be the only appropriate option for now?

**Comment by khmakoto** [comment]
Hi @redoz, sorry for never coming back to this. I'm glad you found styling that helped you get what you wanted. Given that, are you fine with closing this issue?

**Comment by redoz** [comment]
@khmakoto well, I think the request is still valid, but I'm no longer working on that project so for me, right now, it doesn't matter. So feel free to close it :)

**Comment by khmakoto** [comment]
Sounds good! Will reopen if it's requested again later. Thanks!

**Comment by Zhephyr54** [comment]
Hi @khmakoto, actually I am in the same situation as the OP for one of my project.
Furthermore, I think that an `onRenderError` function would totally make sense regarding the fact that there already are such functions for description, label, prefix and suffix (`onRenderDescription`, etc.).
What do you think?

**Comment by khmakoto** [comment]
Hi @Zhephyr54, this work is being tracked by #3620.
