### ISSUE TITLE
PeoplePicker: personas should truncate the names if they can't fit

### ISSUE THREAD

**Issue by MirandaGe** [OfficeDev/office-ui-fabric-react#766]
### Bug Report

- __Package version(s)__: all
- __Browser and OS versions__: all

#### Describe the issue:

The persona card of selected people doesn't perform properly when the browser window width is narrow.

#### Actual behavior:

1. open the example of people picker, input 'a' and select 'Another A Name (So Many A Names!)'.
2. narrow the window still the width of browser is less than that of persona tag in input area.
The outcome is like:
The delete button cannot be seen and click; Also, there are some CSS style problem-the border of input is partly lost at the right side of persona card.
![image](https://cloud.githubusercontent.com/assets/16030290/21772827/c3838aac-d6c7-11e6-83be-00ccc899b01e.png)

#### Expected behavior:

The delete button can be seen;
The name of the persona card is partly shown;
The border of the input area is complete.

**Comment by joschect** [comment]
This should be fixed now @MirandaGe , let me know if it's still not working!

**Comment by MirandaGe** [comment]
Checked and it works good now, thank you!

**Comment by MirandaGe** [comment]
Hi @joschect , I tried it again on Fabric React demo page and also in codepen with latest version, still I can't see the delete button of selected person and the selected persona tag exceeds the input area:
 
![image](https://cloud.githubusercontent.com/assets/16030290/23014211/f7b6faa2-f468-11e6-8c1e-81a2b207f486.png)

Here is the codepen link: 
http://codepen.io/lingge/pen/MJBzjG
