### ISSUE TITLE
HoverCard: remove empty div wrapper 

### ISSUE THREAD

**Issue by gggjtgxing** [OfficeDev/office-ui-fabric-react#7663]
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:
```
return (
      <div className={this._classNames.expandedCard} ref={this._expandedElem}>
        <div className={this._classNames.expandedCardScroll}>
          {this.props.onRenderExpandedCard && this.props.onRenderExpandedCard(this.props.renderData)}
        </div>
      </div>
    );
```
 
#### Expected behavior:
 ```
if (this.props.onRenderExpandedCard) {
return ...
}
```

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by mikewheaton** [comment]
@gggjtgxing Can you provide more details on the problems these divs are causing? It looks like they both have styles associated with them and the outer one is a reference. Changing these would likely cause problems and be a breaking change.
