### ISSUE TITLE
Checkbox grouped

### ISSUE THREAD

**Issue by aminezemzemi** [OfficeDev/office-ui-fabric-react#7669]
Hi,
I searched in the documentation and I didn't find explanation for grouping checkboxes. How can we do it ?
Cordially

**Comment by mikewheaton** [comment]
Have a look at this CodePen: https://codepen.io/mikewheaton/pen/vvMxpz?editors=0010

To group the checkboxes together as a single input for a form submission, you can use a shared `name` attribute between them. And a `styles` prop can be used to add some space between them in the layout.

**Comment by aminezemzemi** [comment]
@mikewheaton Thank your for your help, did you know if we can set add required property like ChoiceGroup Component.
