### ISSUE TITLE
sendkeys

### ISSUE THREAD

**Issue by nickersd** [OfficeDev/office-ui-fabric-react#7671]
**Describe the feature that you would like added**
Ability to insert mail merge tags, I believe also known as field codes.  In word pressing "ctrl-F9" results
in a mail merge tag. Pressing "alt-F9" will show/hide the codes.

Alternatively - Add the sendKeys command.  I'm thinking if I send {^F9} it would have the same result

**What component or utility would this be added to**

**Have you discussed this feature with our team, and if so, who**
I have not. 
**Additional context/screenshots**

**Comment by mikewheaton** [comment]
Could you provide some more details on what you're looking for? I'm not clear on how mail merge tags relate to the Fabric React components.

**Comment by nickersd** [comment]
I've been tasked with creating a tool to make it easier to create letter templates.  I'm still playing around with ideas but the current approach is to write a word add in that would have a list of available mail merge tags (list generated from our DB).  The user could click on a tag in the add in, and it would be inserted into the document. I've used Fabric react to create the beginnings of the add in.   I can easily insert text into the document, but a mail merge tag is handled differently. 

In Word, clicking ctrl-F9 inserts a tag, that's why I was thinking I could maybe use SendKeys to achieve the same result but I don't see SendKeys support.

**Comment by mikewheaton** [comment]
Thanks for clarifying that. It sounds like a question specific to the Office Add-ins APIs. Unfortunately, I don't think you'll find an answer here as we're focused on the Fabric React components themselves. You may be able to find some resources [here](https://docs.microsoft.com/en-us/office/dev/add-ins/).
