### ISSUE TITLE
Tooltip has scrollbar after normalize.css is applied

### ISSUE THREAD

**Issue by chnldw** [OfficeDev/office-ui-fabric-react#7674]
### Environment Information 
 
- __Package version(s)__: 
6.126.0
- __Browser and OS versions__: 
Chrome Windows

### Please provide a reproduction of the bug in a codepen:
Tooltip has scrollbar after normalize.css is applied.
https://codepen.io/chnldw/pen/robGPq

 
#### Actual behavior:
 ![image](https://user-images.githubusercontent.com/1989690/51268345-c0058a00-1974-11e9-9685-28db09f8539d.png)
 
#### Expected behavior:
 
![image](https://user-images.githubusercontent.com/1989690/51268399-e1ff0c80-1974-11e9-97e0-5b235ca7ff88.png)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix?
No
 
Requested priority:
Normal
 
Products/sites affected: (if applicable)

**Comment by mikewheaton** [comment]
The `hideOverflow` prop can be used as a quick fix. See this CodePen: https://codepen.io/mikewheaton/pen/bOJabO

I'm not entirely sure which style Normalize.css is applying that causes this scroll. I thought it was line height, but setting that to 1 didn't fix it. I'll have to investigate more here. It can be tricky to anticipate global styles that might interfere with the components, but it does seem reasonable to cover commonly-used ones like Normalize.
