### ISSUE TITLE
New component: Rating

### ISSUE THREAD

**Issue by cschleiden** [OfficeDev/office-ui-fabric-react#768]
We are in need of a `Rating` component similar to this one in mwf:
http://getmwf.com/components/content/rating.html

We'll build it anyway, do you think something like this is generic enough to be included in office fabric? If so, we'd be happy to contribute back.

**Comment by dzearing** [comment]
Love it, yeah IMO it's an easy addition.

**Comment by rickyp-ms** [comment]
Should this only do whole integers (1,2,3,4,5/5) or also handle partial 4.654/5?

**Comment by cschleiden** [comment]
I restricted it to whole integers for now, since we initially focused on the input part. Another step will be to show an aggregate score in addition to allowing the user to input, for that we will also support "half stars".

**Comment by dzearing** [comment]
In use cases in SharePoint for rating, it does support half star scenarios. Would definitely be nice to consider supporting floating point. Not very difficult.

**Comment by cschleiden** [comment]
Not saying that it can't be done, just that we only focused on input for now. For accessibility, the control is built using radio buttons (i.e., discrete), so I think for input it would make sense to restrict to 0.5 increments.

For display, I agree, if we use a div with some `overflow: hidden`, it'd be relatively easy to calculate the required width to display floating point.
