### ISSUE TITLE
In React 16, List.tsx will throw string refs error

### ISSUE THREAD

**Issue by qianghuang94** [OfficeDev/office-ui-fabric-react#7690]
### Environment Information 
 
- __Package version(s)__: 6.x

### Please provide a reproduction of the bug in a codepen:

 https://codepen.io/qianghuang94/pen/qLGaEq

#### Actual behavior:
 ![image](https://user-images.githubusercontent.com/15025186/51315566-6a70d080-1a8d-11e9-9074-a74f40bdbe50.png)
```
Warning: A string ref, "page-0", has been found within a strict mode tree. String refs are a source of potential bugs and should be avoided. We recommend using createRef() instead.

    in div (created by t)
    in div (created by t)
    in t
    in StrictMode
    in div

Learn more about using refs safely here:
https://fb.me/react-strict-mode-string-ref
```

#### Related codes:

https://github.com/OfficeDev/office-ui-fabric-react/blob/1de46953ecc8320e6fbb341ab0608fb62b09228b/packages/office-ui-fabric-react/src/components/List/List.tsx#L412

#### Expected behavior:
 
No warnings.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (I will see if i have time to fix it)
 
Requested priority: (High) 
 
Products/sites affected: SharePoint Online

**Comment by dzearing** [comment]
@KevinTCoughlin this might be a pretty easy fix here.

**Comment by KevinTCoughlin** [comment]
> 
> 
> @KevinTCoughlin this might be a pretty easy fix here.

Mostly, I just need to figure out how to swap the lookup by `page.key` we currently do:

https://github.com/OfficeDev/office-ui-fabric-react/blob/1710fbd11247be06624e79f4098679877ea4287a/packages/office-ui-fabric-react/src/components/List/List.tsx#L666

**Comment by KevinTCoughlin** [comment]
Re-opening this issue since we had to revert the change in https://github.com/OfficeDev/office-ui-fabric-react/pull/8237 due to runtime errors in certain scenarios.

**Comment by micahgodbolt** [comment]
The codepen no longer renders or produces an error. Can you update the codepen to repro the bug?

![image](https://user-images.githubusercontent.com/1434956/71691404-2e955080-2d5c-11ea-9a83-6b0e29fd363e.png)
