### ISSUE TITLE
Move wiki content into the repo so that we can take PR contributions

### ISSUE THREAD

**Issue by dzearing** [OfficeDev/office-ui-fabric-react#7702]
The Wiki is right now using the github wiki support. This is somewhat convenient for repo contributors but makes it impossible for readers to submit requests for changes.

Let's move the wiki content into the repo and set up a nightly job to push the changes into the github wiki branch. That way people can submit PRs to modify things.

**Comment by Jahnp** [comment]
I think #6780 captures this but suggests moving the content to a separate repo. I'm not sure if there are any pros/cons to keeping it in this repo or another one, just wanted to point out the spirit of this has been captured elsewhere.

**Comment by dzearing** [comment]
Dupe of #7183

**Comment by dzearing** [comment]
Thx @Jahnp !
