### ISSUE TITLE
Text: Add token support

### ISSUE THREAD

**Issue by khmakoto** [OfficeDev/office-ui-fabric-react#7714]
Now that Foundation components have been converted to use slots, we need to assess whether they should use tokens or not. `Text` is one of these components.

**Comment by dzearing** [comment]
Can you update this bug with the tokens which will be added? We should discuss which tokens make sense globally.

**Comment by khmakoto** [comment]
@dzearing Yeah, it would probably be good to have this discussion.

CCing @natalieethell since she is promoting `Text`.

**Comment by khmakoto** [comment]
Per discussions with @dzearing and @natalieethell we have determined that there aren't any tokens we should add to `Text`, unless we decide on the approach of a core set of tokens for all components.

Will be closing the issue now.
