### ISSUE TITLE
Dashboard - get rid of github commit based dependency

### ISSUE THREAD

**Issue by kenotron** [OfficeDev/office-ui-fabric-react#7718]
### Environment Information 
 
- __Package version(s)__: @uifabric/dashboard@master
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:

The problematic line in question: https://github.com/OfficeDev/office-ui-fabric-react/blob/55a1455c10f510902c08fc0ab0f5af162838815f/packages/dashboard/package.json#L13
 
We have a dependency in the dashboard project that is based on a github commit. This puts all the npm install's on yet another infra - github.com. And that service isn't as reliable as the CDNs provided by the npmjs registry. It also means rush cannot do its verification on this dependency.

Related to #7707 - that one points to the kind of problem this causes.
 
#### Expected behavior:
 
Use a real package & dependency version. Work with the original author of `react-grid-layout` to add the missing API.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by yumikohey** [comment]
I couldn't have it build successfully for the past whole week; need this to be fixed asap. Thank you.

**Comment by mikewheaton** [comment]
@samiyaakhtar Are you aware of this issue?

**Comment by yumikohey** [comment]
@mikewheaton I think we can close this ticket now?
https://github.com/OfficeDev/office-ui-fabric-react/issues/7707
