### ISSUE TITLE
How to separately set the direction of coach mark and teaching bubble?

### ISSUE THREAD

**Issue by KeiraYang** [OfficeDev/office-ui-fabric-react#7722]
Hi team,
Thank you for your great efforts on build this good coach mark component. I need some help from you.
I'm encountered an issue that I have a coach mark and when hover mouse to it, the teaching bubble will be expanded. I want to set the DirectionalHint of coach mark and teaching bubble for different way. But I cannot set it by pass the a DirectionalHint to Coachmark positioningContainerProps and another DirectionalHint to TeachingBubbleContent calloutProps. 
Here is some piece of code.
```
<Coachmark
        {...this.props}
        positioningContainerProps={{
          directionalHint: DirectionalHint.bottomLeftEdge,
          directionalHintForRTL: DirectionalHint.bottomRightEdge
        }}
        teachingBubbleRef={this._teachingBubbleContent}
      >
        <div>
          <TeachingBubbleContent
            {...this.props.teachingBubbleProps}
            calloutProps={directionalHint: DirectionalHint.bottomAutoEdge,}
          >
            {this.props.content}
          </TeachingBubbleContent>
        </div>
      </Coachmark>
```
TeachingBubbleContent didn't set direction. Is there anyway I can do the two DirectionalHint for coach mark and teaching bubble separately?
I'll be very grateful if any of you can help. Thanks!

**Comment by mikewheaton** [comment]
Could you create a CodePen showing the issue? https://aka.ms/fabricpen

**Comment by mikewheaton** [comment]
I've taken a closer look at this. Unfortunately, I don't see a simple way to position the Coachmark differently than the TeachingBubble. The Coachmark actually animates to become the frame of the TeachingBubble, so they are both contained in the same PositioningContainer. TeachingBubble doesn't have any positioning logic of its own.

Could you provide some more details on why you need the content to be anchored to a different edge than the Coachmark is? This might be a feature we can add if it's clear when it's appropriate.

One hacky solution I can think of is to have two separate Coachmark components attached to the same element. You could hide the second one initially. Then use the `onAnimationOpenStart` event of the first Coachmark to hide it and show the second Coachmark, with `isCollapsed: false` to have it be open.

**Comment by mikewheaton** [comment]
Ah, I see the issue here. There is an `isPositionedForced` prop on Coachmark that will prevent it from going out of view or being too narrow. Would that meet your needs? Here's what it looks like:

![image](https://user-images.githubusercontent.com/1382445/51619578-863d0200-1ee5-11e9-9199-da24e4d6d137.png)

**Comment by mikewheaton** [comment]
Glad to hear it!
