### ISSUE TITLE
Cannot load theme when using Parcel as bundler

### ISSUE THREAD

**Issue by danmarshall** [OfficeDev/office-ui-fabric-react#7728]
Hello, when using [Parcel](https://github.com/parcel-bundler/parcel) as my bundler, I am not able to call `loadTheme`. 

Here is a sample repo to show my setup:
https://github.com/danmarshall/office-ui-button

### Environment Information 
 
- __Package version(s)__: 6.128.0

### Please provide a reproduction of the bug in a codepen:

```js
import * as React from "react";
import * as ReactDOM from "react-dom";
import { DefaultButton } from "office-ui-fabric-react/lib/Button";
import { loadTheme } from "office-ui-fabric-react";

loadTheme({
  palette: {
    themePrimary: "#0078d4",
    themeLighterAlt: "#eff6fc",
    themeLighter: "#deecf9",
    themeLight: "#c7e0f4",
    themeTertiary: "#71afe5",
    themeSecondary: "#2b88d8",
    themeDarkAlt: "#106ebe",
    themeDark: "#005a9e",
    themeDarker: "#004578",
    neutralLighterAlt: "#f8f8f8",
    neutralLighter: "#f4f4f4",
    neutralLight: "#eaeaea",
    neutralQuaternaryAlt: "#dadada",
    neutralQuaternary: "#d0d0d0",
    neutralTertiaryAlt: "#c8c8c8",
    neutralTertiary: "#c2c2c2",
    neutralSecondary: "#858585",
    neutralPrimaryAlt: "#4b4b4b",
    neutralPrimary: "#333333",
    neutralDark: "#272727",
    black: "#1d1d1d",
    white: "#ffffff"
  }
});

ReactDOM.render(
  <DefaultButton onClick={e => alert("clicked")}>I am a button.</DefaultButton>,
  document.getElementById("app")
);
``` 

Hopefully I am calling this correctly, if not please let me know!

Also, please note that `loadTheme` does not need to be called to get this error. You can also change the `import` to an `export` without calling `loadTheme()`:

```
export { loadTheme } from "office-ui-fabric-react";
```
 
#### Actual behavior:
 
```
Uncaught TypeError: Cannot redefine property: ChoiceGroupOption
    at Function.defineProperty (<anonymous>)
    at office-ui-button.f69400ca.js:98379
    at Array.forEach (<anonymous>)
    at Object.parcelRequire.node_modules/office-ui-fabric-react/lib/index.js../ActivityItem (office-ui-button.f69400ca.js:98377)
    at newRequire (office-ui-button.f69400ca.js:49)
    at localRequire (office-ui-button.f69400ca.js:55)
    at Object.parcelRequire.index.tsx.react (office-ui-button.f69400ca.js:99201)
    at newRequire (office-ui-button.f69400ca.js:49)
    at office-ui-button.f69400ca.js:81
    at office-ui-button.f69400ca.js:107
```
 
#### Expected behavior:
 Themed button on page.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal

**Comment by danmarshall** [comment]
This could possibly be a bug in Parcel, which seems to trigger only when `loadTheme` is added.

**Comment by leddie24** [comment]
Hey @danmarshall, thanks for submitting an issue.  I can repro this with your github repro.  I'm not sure why there's a TypeScript error that occurs (especially with the random component of ChoiceGroupOption), but I found that importing `loadTheme` from `office-ui-fabric-react/lib/Styling` instead of from the root of `office-ui-fabric-react` has solved the issue for me.  Can you try that and see if that solves your problem?  Feel free to reopen the issue if you're still experiencing this. Thanks!

```
import { loadTheme } from "office-ui-fabric-react/lib/Styling";
```

**Comment by danmarshall** [comment]
Fantastic! Thanks you @leddie24 ! 🥇

**Comment by denkristoffer** [comment]
This seems to happen with every named import from Fabric when using Parcel, not just `loadTheme`. Is this a bug in Parcel or in Fabric?

**Comment by chuanqisun** [comment]
Hitting the same error when I call `import { Customizer } from "office-ui-fabric-react";`. Is there a similar workaround?

**Comment by denkristoffer** [comment]
@chuanqisun This is what I ended up doing to use the fluent theme mentioned in the README with Fabric 6:

```jsx
import { Customizer } from 'office-ui-fabric-react/lib/Utilities'
import { FluentCustomizations } from '@uifabric/fluent-theme/lib/FluentCustomizations'


const App = () => (
  <Customizer {...FluentCustomizations}>
    // ...
  </Customizer>
)

```

**Comment by chuanqisun** [comment]
Thanks for the tip! So I guess the work around is to drill all the way into the origin of the export.

**Comment by flipswitchingmonkey** [comment]
Has anyone ever worked out whether this is an issue with Parcel or Fabric? The workaround works, but who knows what other side effects this may end up having?
