### ISSUE TITLE
use "loadTheme" method will include the whole "office-ui-fabric-react" lib

### ISSUE THREAD

**Issue by jayliang701** [OfficeDev/office-ui-fabric-react#7730]
I try to change theme following official doc, likes:
`import { loadTheme as setup } from 'office-ui-fabric-react';`

But this line will make the whole "office-ui-fabric-react" lib bundled by webpack. My app.js file is up to 3MB+. 

Can I improve this? What is the best way to do it?

**Comment by cslecours** [comment]
You should use : 
`import { loadTheme } from 'office-ui-fabric-react/lib/Styling';`

Source : https://github.com/OfficeDev/office-ui-fabric-react/blob/master/apps/fabric-website-resources/src/components/pages/ColorsPage.tsx#L5

**Comment by leddie24** [comment]
Thanks for chiming in @cslecours.  This should fix your issue @jayliang701, feel free to re-open the issue if it doesn't.

**Comment by jayliang701** [comment]
Thank you guys!
