### ISSUE TITLE
DetailsList Columns Do Not Align When Scrolling Horizontally With A Sticky Header

### ISSUE THREAD

**Issue by canmenekse** [OfficeDev/office-ui-fabric-react#7731]
### Environment Information 
 
- __Package version(s)__: 6.128.0
- __Browser and OS versions__: Chrome/Edge/Firefox

### Please provide a reproduction of the bug in a codepen:
 Similar to #7059
[https://codepen.io/anon/pen/REXVOd](https://codepen.io/anon/pen/REXVOd)

1. Make the window small enough so vertical scrollbars are enabled
2. Scroll down
3. Make the window small enough so horizontal scrollbars are enables
4. Scroll horizontally, You are going to see that the columns are not aligned

#### Actual behavior:
 
Columns of the StickyHeader do not align with the content

![columnalignment](https://user-images.githubusercontent.com/42455391/51430264-69df5380-1bcd-11e9-81cc-275883e87db2.PNG)
 
#### Expected behavior:
 
Columns of the StickyHeader to align with the content

**Comment by canmenekse** [comment]
Ah never mind After I saw the [https://developer.microsoft.com/en-us/fabric#/components/scrollablepane](https://developer.microsoft.com/en-us/fabric#/components/scrollablepane) I resolved my issue.

For anyone wondering, adding the following props to the DetailsList seems to fixed the issue:
` constrainMode={ConstrainMode.unconstrained}`
 ` layoutMode={DetailsListLayoutMode.fixedColumns}`

**Comment by leddie24** [comment]
Looks like you found the solution, thanks for submitting it!  Closing the issue now.
