### ISSUE TITLE
Cannot Disable CommandBar Items on modern page

### ISSUE THREAD

**Issue by russgove** [OfficeDev/office-ui-fabric-react#7732]
Expected or Desired Behavior
Setting the disabled attribute of an IContecutalMenuItem should render the item in a disabled state

Observed Behavior
Setting the disabled attribute of an IContecutalMenuItem renders the item in an enabled statestate

Steps to Reproduce
build a react webpart and add this to the render method:
let itemsNonFocusable: IContextualMenuItem[] = [
{
key: "Disabled",
name: "Disabled",
icon: "TriggerApproval",
disabled: true
},
{
key: "Enabled",
name: "Enabled",
icon: "TriggerApproval",
disabled: false
}]

return (
  <div className={styles.test}>
    <CommandBar
      isSearchBoxVisible={false}
      items={itemsNonFocusable}

    />
  </div>
);
If you deploy the webpart to a modern page both menu items appear enabled. It worls fine on a classic page.

**Comment by leddie24** [comment]
Hi @russgove , thanks for submitting an issue.  Unfortunately, it's really difficult for us to repro bugs on SharePoint;  can you please submit a codepen that demonstrates the issue?  If we can isolate the problem to fabric react, then we can rule out any possible differences that may be there between a Modern and Classic environment.
