### ISSUE TITLE
GroupedList forgets current toggle state when re-rendering

### ISSUE THREAD

**Issue by hemure** [OfficeDev/office-ui-fabric-react#7735]
### 
Chrome : 71.0.3578.98 (Official Build) (32-bit)
FabricUI react : 6.114.0 

#### Actual behavior:
 I'm updating the groups and/or items arrays and calls forceUpdate().
The component updates the content, but collaps all groups in the process.
 
#### Expected behavior:
It should retain the current state of collapsed and open groups.
Preferably it should provide addGroup and addItem ( also update and delete) functions to perform dynamic updates to the list content.
 
#### Priorities and help requested:
If there's a workaorund or if I'm just misunderstanding things, please help me out :-)
 
Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low) 
Normal

Products/sites affected: (if applicable)

**Comment by leddie24** [comment]
Hi @hemure , thanks for submitting an issue.  Could you please submit a codepen demonstrating the bug?  I'm having difficulty reproing this on our documentation page.  Thank you!

**Comment by KevinTCoughlin** [comment]
@hemure, would it be possible to isolate this repro in a Codepen? You may fork this `GroupedList` starter template if you find that helpful, https://codepen.io/kevintcoughlin/pen/zeGpZp?&editable=true/.

It will help us debug and provide a fix. Thank you for the report!
