### ISSUE TITLE
Sticky header in details list not moving with scroll

### ISSUE THREAD

**Issue by hrc7505** [OfficeDev/office-ui-fabric-react#7742]
### Environment Information 
 
- __Package version(s)__: (6.129.0) 
- __Browser and OS versions__: (Chrome  71.0.3578.98 - Windows 10)

### Please provide a reproduction of the bug in a codesendbox:
 <a href="https://codesandbox.io/s/vm56j1qx80">
  <img alt="Edit DetailsList - compact" src="https://codesandbox.io/static/img/play-codesandbox.svg">
</a>

 
#### Actual behavior:
 Sticky header is not moving with the horizontal scroll. Only list is moving header not moving so creating problem to see columns with appropriate values. Scroll comes at the end of list items.

 
#### Expected behavior:
 Sticky header should move with the scroll. Scroll(V and H) should be available to the container.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 No
Requested priority: (Blocking, High, Normal, Low) 
 High
Products/sites affected: (if applicable)

**Comment by leddie24** [comment]
Hi @hrc7505 , thanks for submitting an issue.  You can solve this by adding these props to the `DetailsList` component.
```
layoutMode={DetailsListLayoutMode.fixedColumns}
constrainMode={ConstrainMode.unconstrained}
```

I've forked your codepen to demonstrate it in effect.

https://codesandbox.io/s/lx8n8vz55z
