### ISSUE TITLE
Coachmark hover/click support not working on demo site

### ISSUE THREAD

**Issue by benkaiser** [OfficeDev/office-ui-fabric-react#7750]
### Environment Information 

Tested Chrome and Firefox on Windows 10.

### Please provide a reproduction of the bug in a codepen:

Attempted to repro with most recent versions on:
https://aka.ms/fabricdemo however I can only repro this issue on the example website here:
https://developer.microsoft.com/en-us/fabric#/components/coachmark

#### Actual behavior:
 
Viewing the documentation for coachmark, and running the example successfully shows the coachmark but does not respond to hover / mouse events. Enter key / Alt + C do work correctly.

Screen recording: http://recordit.co/CEmqNvdlH2
 
#### Expected behavior:
 
Hovering on coachmark should open the coachmark to it's contents. This behavior works correctly on the fixed links to versions: https://fabricweb.z5.web.core.windows.net/oufr/6.129.1/#/examples/coachmark

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal (bad experience for people trying to experience the component behavior for the first time on the website, may think it is broken).
 
Products/sites affected: https://developer.microsoft.com/en-us/fabric#/components/coachmark

**Comment by leddie24** [comment]
Thanks for catching this bug @benkaiser! I'll come up with a proper fix in the upcoming week(s).
