### ISSUE TITLE
Create an Expander component: Extract GroupHeader functionality from Nav and DetailsList

### ISSUE THREAD

**Issue by basovic88** [OfficeDev/office-ui-fabric-react#7764]
Currently, in both Nav and DetailsList an Expander-like component is integrated. In the DetailsList it is used to group rows. The group header is clickable and is used to show or hide a collection of rows. This is supported by a nice animation of both the chevron icon and the content. Likewise, the same functionality is available in the Nav component to show/hide/group a collection of links.

I would like to use this Expander-functionality outside of these components, to show/hide random content such as a graph, a picture or a large text.

Since the code is already there, I suggest to extract the common GroupHeader/Expander code from the Nav and DetailsList component and move it to a new component, the Expander.

**Comment by micahgodbolt** [comment]
We already have this in experiments as CollapsibleSection. We're hoping to graduate it once we get some other foundational work done (slots, createComponent etc).

**Comment by basovic88** [comment]
OK. I will check out this experiments/ColapsibleSection component. Thanks for your reply.
