### ISSUE TITLE
Dropdown: When focus on Dropdown not expanded and press 'ESC', this key event is trapped in dropdown and wont go up to higher level. 

### ISSUE THREAD

**Issue by gggjtgxing** [OfficeDev/office-ui-fabric-react#777]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Describe the issue:
when dropdown is expanded, press 'ESC' to close the expended list.
but when dropdown is not expanded, and press 'ESC', dropdown should do nothing and propagate this event to upper level. 
example case:
`<dialog><dropdown/></dialog>`
When focus on dropdown not expanded and press 'ESC', they probably want to quit the dialog since dropdown is already closed.

**Comment by dzearing** [comment]
@eliblock12 can you take a look?

**Comment by mdahamiwal** [comment]
Nice Catch!! This applies to other keys as well for which Dropdown doesn't provide any behavior but may trigger some behavior in parent components. Currently `_onDropdownKeyDown`, always does `ev.stopPropagation()` even if dropdown doesn't handle the key event.

**Comment by joschect** [comment]
@gggjtgxing since it looks like you fixed this (thank you!) I'm going to close this issue.
