### ISSUE TITLE
Dropdown: When tab to a dropdown with selected option, it won't read out current selected item.

### ISSUE THREAD

**Issue by gggjtgxing** [OfficeDev/office-ui-fabric-react#778]
### Bug Report
screen reader: JAWS Version 17.0.2619
browser: Internet Explorer 11
os: window server 2012 R2

#### Describe the issue:
When tab to a dropdown which has selected option, screen reader should read out what is current selected item.

**Comment by dzearing** [comment]
@eliblock12 another dropdown issue, Not sure if this is a real issue or a flakey screen reader.

@gggjtgxing can you provide info on the screen reader/os/browser you're using?

**Comment by gggjtgxing** [comment]
I added browser and OS versions to bug report field. but I don't think they're relevant.
maybe it's a regression issue caused by my last code change, and I'll look at this.

**Comment by mdahamiwal** [comment]
@gggjtgxing , I wanted to point out this issue in the you last PR where you marked the option label as live-region to announce option change. Unfortunately, the comment remained unposted :), my bad, we just need to use describe by 'option_label' on the focusable container for first focus option announcement. Hope that helps. Thanks
