### ISSUE TITLE
Issue with slider and toggle components in Narrator Scan mode

### ISSUE THREAD

**Issue by bowenqiang** [OfficeDev/office-ui-fabric-react#7781]
### Environment Information 
 
- __Package version(s)__: 5.52.0 
- __Browser and OS versions__: Edge, windows 10 1809, Narrator

### Please provide a reproduction of the bug in a codepen:
Use Fabric UI official example pages
https://developer.microsoft.com/en-us/fabric#/components/slider
https://developer.microsoft.com/en-us/fabric#/components/toggle
 
### Repro Steps:
1. Open the link, Turn on windows Narrator.
2. Turn on Scan Mode (Caps + Space).
3. Use arrow down to select the slider bar, highlight box correctly show on the slider bar indicator.
4. Keep using the arrow down to select next element.
5. Use arrow up to select the previous slider bar.

#### Actual behavior:
highlight box not showing on the slider bar indicator when using arrow up.
similar issue with toggle button.

 
#### Expected behavior:
 highlight box should show

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (Normal) 
 
Products/sites affected: (if applicable)

**Comment by leddie24** [comment]
Hi @bowenqiang.  I'm not sure how to repro this issue.  I've done a screen recording (linked below) with Narrator turned on and in Scan Mode and it seems to skip over the Slider components.  The only way I can get to them is via tabbing, which I believe is the intended behavior.  Can you show a video demonstrating the repro on your machine please?

https://streamable.com/lbba2

**Comment by bowenqiang** [comment]
Dear Liu
Here are the videos are you asking.
https://jumpshare.com/v/RN9Jcypxw6rW8QcucySg   toggle

https://jumpshare.com/v/uLZZ9XqB5IJ3nkOlZ8Om      slider

Wenqiang


Sent from my iPhone

On Jan 25, 2019, at 1:48 PM, Eddie Liu <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @bowenqiang<https://github.com/bowenqiang>. I'm not sure how to repro this issue. I've done a screen recording (linked below) with Narrator turned on and in Scan Mode and it seems to skip over the Slider components. The only way I can get to them is via tabbing, which I believe is the intended behavior. Can you show a video demonstrating the repro on your machine please?

https://streamable.com/lbba2

**Comment by bowenqiang** [comment]
Make sure you turn on the scan mode.

Sent from my iPhone

On Jan 25, 2019, at 1:48 PM, Eddie Liu <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @bowenqiang<https://github.com/bowenqiang>. I'm not sure how to repro this issue. I've done a screen recording (linked below) with Narrator turned on and in Scan Mode and it seems to skip over the Slider components. The only way I can get to them is via tabbing, which I believe is the intended behavior. Can you show a video demonstrating the repro on your machine please?

https://streamable.com/lbba2

**Comment by JasonGore** [comment]
This also appears to happen with the [ARIA slider reference](https://www.w3.org/TR/wai-aria-practices/examples/slider/slider-1.html) and thus doesn't seem to be particular to Fabric. This indicates it could be a Narrator or Edge issue.

![slider](https://user-images.githubusercontent.com/26070760/51779034-c94fce80-20b9-11e9-95e9-e9d845706893.gif)

**Comment by leddie24** [comment]
Yeah, I'm not sure this is a bug on our end.  Like Jason mentioned, this is likely an issue with Narrator and/or Edge.  Here's a log from my narrator that logs what it's saying.  I ensure that scan mode was turned on, but it skipped over the slider.  


```
 Show code, button,
Scan Off
Scan
<mark name="0 Id:7"/>Show <mark name="1 Id:7"/>code<mark name="ContinuousReadingEnd Id:7"/>
<mark name="0 Id:8"/>Basic <mark name="1 Id:8"/>example:<mark name="ContinuousReadingEnd Id:8"/>
<mark name="0 Id:9"/>2<mark name="ContinuousReadingEnd Id:9"/>
<mark name="0 Id:10"/>Disabled <mark name="1 Id:10"/>example:<mark name="ContinuousReadingEnd Id:10"/>
<mark name="0 Id:11"/>300<mark name="ContinuousReadingEnd Id:11"/>
<mark name="0 Id:12"/>Controlled <mark name="1 Id:12"/>example:<mark name="ContinuousReadingEnd Id:12"/>
<mark name="0 Id:13"/>0<mark name="ContinuousReadingEnd Id:13"/>
<mark name="0 Id:14"/>Example <mark name="1 Id:14"/>with <mark name="2 Id:14"/>formatted <mark name="3 Id:14"/>value:<mark name="ContinuousReadingEnd Id:14"/>
<mark name="0 Id:15"/>0%<mark name="ContinuousReadingEnd Id:15"/>
Narrator Buddy window,
Scan Off
Exiting Narrator
```

**Comment by leddie24** [comment]
I'm going to close this issue for now.  I don't believe it's something that is reproducible on our end, nor specific to Fabric React.

**Comment by JasonGore** [comment]
I'm going to reopen this issue to give the reporter a chance to respond. @leddie24 please check Toggle too.

**Comment by leddie24** [comment]
Hey @JasonGore, I couldn't find a simple clear-cut example on the w3.org site, but I found this Codepen demonstrating Toggle.  Using scan mode, the toggle highlights itself when traversing down, but not on the way back up.

https://codepen.io/SaraSoueidan/full/jpBbrq

**Comment by bowenqiang** [comment]
It seems to be a bug with narrator or edge. Maybe the coming windows 19h1 will fix it.
