### ISSUE TITLE
[QUESTION] Use React-Devtools with Office add-in

### ISSUE THREAD

**Issue by donpinkus** [OfficeDev/office-ui-fabric-react#7792]
Apologies for posting this question to the _fabric-react repo_, but it seems like the only possible communication channel where I'll get a quality answer. (Also posted on StackOverflow a few days ago).

How can you use React DevTools while developing a Microsoft add-in? Has anyone done this successfully?

**Comment by leddie24** [comment]
Hey @donpinkus, I don't have extensive experience with React DevTools.  I believe if your app can be developed in a browser, the you can simply debug with it in Chrome.  I can ask around my team and try to connect you to the right people in Office Add-Ins

**Comment by Jahnp** [comment]
@Rick-Kirkham , is there someone in the extensibility team who'd be able to help here?

**Comment by donpinkus** [comment]
@leddie24 - thanks for the quick reply! 

Being connected to someone on your team who can answer questions about debugging React in Microsoft Add-ins would be great. I'd happily help write a blog post / update GitHub Readme's with the info once we figure it out. I'm sure debugging React in add-in's is a common enough task ;)

We're building a Word add-in, so unfortunately the app can't be built in a stand-alone browser like Chrome. 

Word only allows you to inspect elements with Safari (on Mac) or IE / Edge (on Windows), neither of which support React-DevTools.

@Jahnp - A better channel for asking Office-Addin / React related questions would be great. Again, I'm sure we're not the first team to be using React in an Add-in and wondering how to use the standard react-devtools :)

**Comment by leddie24** [comment]
Hey @donpinkus, wanted to circle back to you on this question, did you get a chance to connect with @Rick-Kirkham or someone on the extensibility team?  Feel free to close this issue if so.  If not, I can try to help in connecting.
