### ISSUE TITLE
React Router support for Command Bar items

### ISSUE THREAD

**Issue by arun-cm** [OfficeDev/office-ui-fabric-react#7799]
**Add [*react-router-dom*](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-dom) support for Command Bar component**

**What component or utility would this be added to**
1) Command Bar
2) Nav
3) Pivot
4) Breadcrumb
5) OverflowSet

**Or please provide a workaround to implement the same**

**Comment by khmakoto** [comment]
Hi @arun-cm, sorry for the delay in replying! @ecraig12345 recently did an example on how to achieve React Router support in `CommandBars` [here](https://github.com/OfficeDev/office-ui-fabric-react/issues/10737#issuecomment-540838825). Please let us know if you need anything else!
