### ISSUE TITLE
CommandBar: arguments missing when calling the onClick callback

### ISSUE THREAD

**Issue by cvoijen** [OfficeDev/office-ui-fabric-react#78]
The CommandBar components does not apply the clicked item and event as the arguments to the onClick callback. Currently the ``_onItemClick`` function is:
```
if (item.onClick) {
      item.onClick();
    }
```
while it should be
```
if (item.onClick) {
      item.onClick(item, ev);
    }
```
to match the definition in ``IContextualMenuItem``
```
/**
   * Callback issued when the menu item is invoked
   */
  onClick?: (item?: IContextualMenuItem, ev?: React.MouseEvent) => void
```

**Comment by dzearing** [comment]
Good catch! I've patched it.

https://github.com/OfficeDev/office-ui-fabric-react/pull/83

**Comment by dzearing** [comment]
This is now resolved.
