### ISSUE TITLE
Details List: column always has aria-expanded property even when not necessary

### ISSUE THREAD

**Issue by waabid** [OfficeDev/office-ui-fabric-react#7813]
![image](https://user-images.githubusercontent.com/32555133/51779770-31081880-20be-11e9-99fe-dfe9d3904c21.png)

https://developer.microsoft.com/en-us/fabric#/components/detailslist

### Environment Information 
 
Using NVDA with Chrome
 
#### Actual behavior:
 
Has aria-expanded attribute that is read out by screen reader.
 
#### Expected behavior:
 
Should not have aria-expanded attribute when there is nothing to expand or collapse.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) Yes
 
Requested priority: (Blocking, High, Normal, Low)  Normal
 
Products/sites affected: (if applicable)

**Comment by KevinTCoughlin** [comment]
Thanks for the report @waabid. I believe this is the line-of-code in question above:

https://github.com/OfficeDev/office-ui-fabric-react/blob/cb4c10bf66aa74f02ce1b19adf3274846337ef85/packages/office-ui-fabric-react/src/components/DetailsList/DetailsColumn.base.tsx#L101

Recently modified in https://github.com/OfficeDev/office-ui-fabric-react/pull/7646 by @ahackettms as FYI. Unsure if this problem existed prior to that change set.
