### ISSUE TITLE
DetailsList - Selection requires setting undocumented prop to work properly

### ISSUE THREAD

**Issue by lyptt** [OfficeDev/office-ui-fabric-react#7817]
### Bug Report

- __Package version(s)__: 6.129.4
- __Browser and OS versions__: FF 64.0.2

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No - prevented due to contractual reasons

Requested priority: Normal

Products/sites affected: N/A

#### Describe the issue:

I've noticed with DetailsList that you need to set the `setKey` prop in order for selection state to be preserved. If you don't do this, the selection will immediately clear after selecting a list item.

I haven't found a reference to this in the [docs](https://developer.microsoft.com/en-us/fabric#/components/detailslist), so it may be worth adding that in.

**Comment by natalieethell** [comment]
Hey @lyptt thanks for opening this issue! While looking at the reference documentation, I actually noticed that not all of the properties of IDetailsListProps seem to render on first page load. It leaves a huge gap below, where all of the props that come after `onRenderDetailsHeader` alphabetically should be, including `setKey`.

<img width="1147" alt="screen shot 2019-01-28 at 10 22 15 am" src="https://user-images.githubusercontent.com/14134000/51857555-6e032380-22e7-11e9-8fd8-5d1d1bbd0531.png">

When I resize the browser window, however, they seem to show up. Is this what you were referring to? Or the definition of the prop `setKey` when the page loads correctly? I think there's definitely room for improvement in both.

**Comment by natalieethell** [comment]
For now I'll tag this with "documentation", as I believe there are improvements we can make in that area and I'll track the Fabric website issue (seems to be a DetailsList issue, actually) separately.

**Comment by lyptt** [comment]
Hey @natalieethell, that did the trick, thanks! I was searching with Cmd+F which won't work when the props list is virtualised, so that was half of the issue. The other half was as you described - some props were rendered as blank space until I resized the browser.

Looking at the documentation for that key, it seems fairly innocuous, but the underlying issue I describe above leads me to believe it's much more essential, as selection state is actually broken unless you set the identifier.

With that being the case, maybe it's worth highlighting the importance of that prop by including it in one of the examples, or as prose further up the page? I'm sure I won't be the first to be caught out by it.

Also, thanks for taking a look so quickly. I appreciate the fast response!

**Comment by natalieethell** [comment]
@lyptt agreed that the prop's importance should be better highlighted. I'll keep this tracked under "documentation", then. Thank you for bringing this to our attention!

**Comment by natalieethell** [comment]
Looking at this again, we do now specify `setKey` on the DetailsList examples, so I think this may be okay as is. I'll close this issue.
