### ISSUE TITLE
Column header content moves up by 1px after Drop

### ISSUE THREAD

**Issue by gasharm** [OfficeDev/office-ui-fabric-react#7821]
### Environment Information 
 
- __Package version(s)__: Latest 
- __Browser and OS versions__: All

### Please provide a reproduction of the bug in a codepen:

Referring to the column drag drop on Detailslist demo available on https://developer.microsoft.com/en-us/fabric#/components/detailslist/draganddrop

Things are working fine on the demo, but the column header text can be seen moved by 1px after a certain amount of time in related sites (mentioned below). Currently things are working in the demo because there's a CSS hack for that. We need to improve the solution for fixing this issue.

 

 
#### Actual behavior:
 Column header text is moving by 1px up after certain timeout.

 
#### Expected behavior:
 Column header text should remain fixed after the drag drop is finished completely.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal 
 
Products/sites affected: SP Lists

**Comment by KevinTCoughlin** [comment]
> 
> 
> Raised the PR #7822

Wow, Nice find @gasharm and thanks for providing a fix for review!
