### ISSUE TITLE
Globals with multiple selectors are not represented properly

### ISSUE THREAD

**Issue by brandonthomas** [OfficeDev/office-ui-fabric-react#7827]
Regression caused by https://github.com/OfficeDev/office-ui-fabric-react/commit/034ac9dad6f8687da78fb358db9da0c43d976fbc#diff-3a392abb2f69786b5a705929314c2557
 
- __Package version(s)__: all  merge-styles > 6.15.1

Reduction: https://codepen.io/anon/pen/ErydBR

#### Actual behavior:
 the CSS output includes ":global" instead of the class name. Essentially this regresses https://github.com/OfficeDev/office-ui-fabric-react/commit/31d07a04207a554ac7375c567bbe49942f2f65b1#diff-3e729e204829f5d68dee4230f2efe115

`:global(.class1, .css-47 class2, .css-47 .class3){top:140px;}`
 
#### Expected behavior:
 CSS output is properly formatted CSS without :global in output and all selectors are represented

`.class1, class2, .class3{top:140px;}`

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No, regressor should fix.
 
Requested priority: Blocking 
 
Products/sites affected: M365 Admin Center

**Comment by brandonthomas** [comment]
There's no good work around for this if you use the aliased modules in office-ui-fabric-react since OUFR uses a ranged version. It always pulls the latest between 6 and 7 so I'm stuck with this bug until a new version comes out. My only other recourse is to update 200+ files to pull from @uifabric/merge-styles which isn't feasible either.

**Comment by dzearing** [comment]
This unit test repros. This might be Ken's bug, or perhaps Mark, or perhaps both. Not sure. @Markionium can you maybe take a look?

Here is a unit test that repros for `stylesToClassName.test.ts`:

```
  it('can register multiple selectors within a global wrapper', () => {
    const className = styleToClassName({
      selectors: {
        ':global(.class1 .class2 .class3)': { top: 140 }
      }
    });

    expect(className).toEqual('css-0');
    expect(_stylesheet.getRules()).toEqual('.class1, .class2, .class3{top:140px;}');
  });
```

**Comment by dzearing** [comment]
@kenotron just a heads up here. I looked at the issue and it might be that yours and Mark's fixes are colliding.

**Comment by Markionium** [comment]
I'm taking a look at fixing this

**Comment by kenotron** [comment]
Right, any fixes here that doesn't include an honest to goodness selector parser is probably going to be a bandaid at best. Brandon told me he has a work around LOCALLY by changing how he writes the `:global()` selector - basically copy & pasting ...

**Comment by Markionium** [comment]
The fix i'll be doing will definitely be a bandaid. Since i'm traveling at the moment i won't have enough time to invest in exploring the options for a parser.

**Comment by Markionium** [comment]
Found some that reverting the PR mentioned won't work as the selector in the Brandon's example would still not be correct.

When changing to the version before the fix in the codepen
```
<!-- could point to local version -->
<script src="//unpkg.com/office-ui-fabric-react@6.129.1/dist/office-ui-fabric-react.min.js"></script>
```

The css output will not have the correct classes and there is an invalid `)`
```
Here's some bad CSS:
.class1, .css-47 class2, .css-47 .class3){top:140px;}
```

**Comment by dzearing** [comment]
Ah so I think this really was introduced by Ken's comma split. But thank you for stepping up anyway, even on your vacation!!!

**Comment by kenotron** [comment]
@Markionium thanks for fixing while traveling! Was gonna take a look today, but you already fixed it :P

**Comment by brandonthomas** [comment]
Thanks @Markionium!!! I thought I had it rooted to your change but my mistake! Really appreciate the quick turn around!
