### ISSUE TITLE
Disable items in <Nav /> component 

### ISSUE THREAD

**Issue by Koniksan** [OfficeDev/office-ui-fabric-react#7835]
Add please in <Nav /> component possibility to add 'disable' property for link, specifically in INavLink props
Thanks

**Comment by natalieethell** [comment]
This sounds like a reasonable ask to me! @betrue-final-final what do you think? Have we thought about allowing links in a Nav to be disabled?

**Comment by KevinTCoughlin** [comment]
The implementation seems to be a `<button />`. If that's the case, then I think this request makes sense. Perhaps another use-case for `getNativeProps` if it'll solve similar cases. Only glanced at the source though.

**Comment by natalieethell** [comment]
Spoke to @betrue-final-final offline about this request, and we agree that it sounds reasonable! I'll try to create a PR with the changes today or tomorrow.

**Comment by natalieethell** [comment]
Sorry for the delay here! We originally anticipated this addition would be quick and easy, but it involves a little more work with the styling, since Nav links override button styling and the disabled button styling is what we'd want to use.

**Comment by natalieethell** [comment]
Since this work involves more in-depth discussion of the styling for several different types of links within a Nav, to make sure it gets the time and attention it needs and deserves, I'm going to add this to the backlog. Thanks for your patience here!

**Comment by Koniksan** [comment]
@natalieethell  Hi, how is going ? :)

**Comment by natalieethell** [comment]
@Koniksan Hey thanks for checking in! Since this is now in backlog review, @micahgodbolt and @dzearing would know more about the status. Have we gotten a chance to review this feature request yet?

**Comment by winperec** [comment]
@natalieethell Hey, we glad to contribute to the office ui fabric! I hope my PR help all of us with this issue :)
