### ISSUE TITLE
TextField: Support 'add on' on right side of field

### ISSUE THREAD

**Issue by rickyp-ms** [OfficeDev/office-ui-fabric-react#784]
When generating email addresses often times (in O365) the email address is always in the domain. To make things easier we would like to have it so the user only has to input the alias.

Our designer gives the following as an example... I'm curious how hard you think it would be to write the css for this and have it be maintainable. I've been thinking on it but could use some second opinions.

![emailaddresstextbox](https://cloud.githubusercontent.com/assets/22225666/21831890/28bae44e-d75c-11e6-8c7e-3e927ca34813.JPG)

**Comment by dzearing** [comment]
Couldn't you take the border off the TextField with css, and then render it within a DIV that flexboxes the TextField and the div containing the domain and check glyph?

**Comment by rickyp-ms** [comment]
Is that still valid for rtl? If I were to make this part of the control, should I call it prefix/suffix? I see the email scenario being used quite a bit and would love to make it easier and consistent across all products. Especially when people generally have to keep writing their domain address when we already know it.

**Comment by rickyp-ms** [comment]
Looks like someone added an addon for the front. Just need to add a prop to say if the addon should be at the start or end of the textbox and it should be done!

**Comment by battletoilet** [comment]
Please see prefix and suffix props.
