### ISSUE TITLE
TeachingBubble component will not move when target element is moving. 

### ISSUE THREAD

**Issue by KeiraYang** [OfficeDev/office-ui-fabric-react#7846]
Hi,
I'm using TeachingBubble component but met with an issue.
Codepen to repro:
[https://codepen.io/keirayang/pen/XONNwg](https://codepen.io/keirayang/pen/XONNwg)
Click button to show teaching bubble, scroll down the page, the teaching bubble will not follow the target. 
My situation is not exactly this one but similar with this situation. I have a page, the target element will be mounted in the page first. Then teaching bubble will be shown up directly when the element is mounted. But the css styles are not apply now, after css applied to the element, the position of the element is changed. But teaching bubble doesn't follow the target to move.

Is there a simply way to fix this? I'm very grateful for your help and effort. Thanks!

**Comment by natalieethell** [comment]
@KeiraYang thanks for submitting this issue! 

@micahgodbolt it looks like in PR https://github.com/OfficeDev/office-ui-fabric-react/pull/870 @mdahamiwal added functionality to dismiss the Tooltip on scroll. 

Does it make sense for TeachingBubble to have the same behavior? Should it also dismiss on scroll?

**Comment by KeiraYang** [comment]
Yes, there is an interface to set the preventDismissOnScroll as false, it can dismiss the teaching bubble when scroll page. But this doesn't fix this issue when I don't want to dismiss the teaching bubble when scroll the page.

**Comment by micahgodbolt** [comment]
typically tooltips and other floating elements are placed on a layer at the root of the document so that you don't have to worry about clipping that might occur if the tooltip was placed in a overflow: none scenario. 

unfortunatly, due to this placement there isn't a way for the tooltip to travel with the parent, we only use the parent for initial placement. you can display tooltips inline, which will travel with the parent, but then you have to deal with the possibility of clipping. This is why we usually dismiss those items on scroll.

**Comment by natalieethell** [comment]
@KeiraYang based on Micah's response above/the control's implementation, it sounds like this is expected behavior. Let us know if we can answer any other questions for you, though!

**Comment by natalieethell** [comment]
@KeiraYang no problem! Yes, that should be expected behavior, because clicking outside the TeachingBubble moves focus outside the TeachingBubble. Does that make sense?

**Comment by KeiraYang** [comment]
`if (
      !preventDismissOnLostFocus &&
      ((!this._target && clickedOutsideCallout) ||
        (ev.target !== this._targetWindow &&
          clickedOutsideCallout &&
          ((this._target as MouseEvent).stopPropagation ||
            (!this._target || (target !== this._target && !elementContains(this._target as HTMLElement, target))))))
    ) {
      this.dismiss(ev);
    }`

As the logic, when the ev.target is contained inside the target element. The teaching bubble will not be dismissed? Just confirm. Because as we want, we want to dismiss the teaching bubble when user click outside of teaching bubble and **click on the target element as well.**

**Comment by natalieethell** [comment]
I'm not sure if I entirely understand your question, so do let me know if this doesn't answer it, but the condition above will only be true if `clickedOutsideCallout` is true, where `clickedOutsideCallout` is 

```tsx
const clickedOutsideCallout = this._hostElement.current && !elementContains(this._hostElement.current, target);
```

So, as you can see on the TeachingBubble demo page, if you click inside a TeachingBubble, `_dismissOnLostFocus` of CalloutContentBase does not call `this.dismiss(ev)`.

**Comment by natalieethell** [comment]
@KeiraYang ah yes, I understand! Thanks for clarifying. 

Usually, to display and/or dismiss a teaching bubble, you need the target element to change the state. I would recommend doing what it looks like you have in your CodePen, which is setting the onClick method of the DefaultButton (target button) to flip the `isTeachingbubbleVisible` boolean. That's what we have in our examples on the [TeachingBubble page](https://developer.microsoft.com/en-us/fabric#/components/teachingbubble) as well.

Here's a code snippet from one of the example files. You can see that the `onClick` method flips the isVisible state that determines whether the TeachingBubble is rendered.

https://github.com/OfficeDev/office-ui-fabric-react/blob/30929a19bd471440af88dd355fca7894d32dc5a7/packages/office-ui-fabric-react/src/components/TeachingBubble/examples/TeachingBubble.Basic.Example.tsx#L33-L59

Let me know if this answers your question!

**Comment by KeiraYang** [comment]
Hi @natalieethell. Sorry for delay reply. I got your idea. Thank you for this! I've understood.

**Comment by KeiraYang** [comment]
@natalieethell  Could you please take a look at the dismiss teaching bubble action when click the 'X' button. It doesn't work now even in the example [ https://developer.microsoft.com/en-us/fabric#/components/teachingbubble]( https://developer.microsoft.com/en-us/fabric#/components/teachingbubble)

**Comment by natalieethell** [comment]
@KeiraYang yes! I'm currently working on a fix for that, actually - it was due to my change last week. I'm hoping to push a fix asap.

**Comment by natalieethell** [comment]
@KeiraYang it's being tracked here! https://github.com/OfficeDev/office-ui-fabric-react/issues/7820

**Comment by KeiraYang** [comment]
Good! Thank you!

**Comment by natalieethell** [comment]
@KeiraYang sorry for the delayed response - that issue was fixed in this PR! https://github.com/OfficeDev/office-ui-fabric-react/pull/7981
