### ISSUE TITLE
DetailsList: Inappropriate column width after column header drag drop

### ISSUE THREAD

**Issue by gasharm** [OfficeDev/office-ui-fabric-react#7847]
### Environment Information 
 
- __Package version(s)__: Latest 
- __Browser and OS versions__: All OS/Browsers

### Please provide a reproduction of the bug in a codepen:
 

In the demo provided at https://developer.microsoft.com/en-us/fabric#/components/detailslist/draganddrop . Change number of frozen columns to 0 and then try dragging any column at very first index.
 
#### Actual behavior:
 

Assuming we dragged 'name' column to the first position, the 'name' column will have the width of 'thumbnail' column and 'thumbnail' column will take the width of 'name' column.
 
#### Expected behavior:
 

After the drag drop operation is completed, all the affected columns should retain their original width irrespective of where they have been dropped.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal
 
Products/sites affected: All sites using UI Fabric.

**Comment by gasharm** [comment]
@shagra-ms

**Comment by KevinTCoughlin** [comment]
>After the drag drop operation is completed, all the affected columns should retain their original width irrespective of where they have been dropped.

Interesting.. I'm not sure we've considered this behavior before cc: @aditima.

**Comment by shagra-ms** [comment]
One more observation - if the column has been resized before moving it around, it retains it's width.

**Comment by gasharm** [comment]
@KevinTCoughlin Not sure about the rational of existing behavior. But, whenever a user is increasing the column width, it's because of the **more width demand** of data content of that column. When we rearrange the column by drag drop, I don't think that demand changes and that's why I suggest we should retain the column width even after rearrangements. 

For design sign-off, I think @betrue-final-final should be able to help here.

**Comment by shagra-ms** [comment]
CC: @naveedahmed

**Comment by naveedahmed** [comment]
> After the drag drop operation is completed, all the affected columns should retain their original width irrespective of where they have been dropped.

I second @betrue-final-final

**Comment by natalieethell** [comment]
Spoke offline with @gasharm and he is still willing to submit a PR to fix the issue! I'll assign him.
