### ISSUE TITLE
OverflowSet onRenderItem prop is required but never gets called. what is the use of it, make it optional?

### ISSUE THREAD

**Issue by gnanavelum** [OfficeDev/office-ui-fabric-react#7858]
....

 <OverflowSet onRenderItem={this.onRenderItem} overflowItems={contextMenus} onRenderOverflowButton={this.onRenderOverflowButton} className={styleSet.overflowSet} />;

  .... 
 
  // This is public to help code coverage :( or it needs to goto helper.
  // This function is never called or used by fabric overflowset control but a required prop, bug to fabric
  public onRenderItem = (item: IOverflowSetItemProps): JSX.Element => {
    return <IconButton iconProps={{ iconName: item.icon }} title={item.name} onClick={item.onClick} />;
  };

**Comment by natalieethell** [comment]
Hey @gnanavelum! I do see the `onRenderItem` prop getting used here:

https://github.com/OfficeDev/office-ui-fabric-react/blob/af108d4db1db03c0497f477054743e3bac52070a/packages/office-ui-fabric-react/src/components/OverflowSet/OverflowSet.base.tsx#L145-L156

Am I missing something?

**Comment by gnanavelum** [comment]
i do see that code that has the caller... my overflowset works but the onRenderItem never got called, no coverage. if i return null on the onRenderItem still works. feel free to ping me gnamun… i can show the code.

**Comment by jnavaskhan** [comment]
Here are scenario:

I have used overflow set like as follows:
```

<OverflowSet
            overflowItems={ofItems)}
            onRenderOverflowButton={this.onRenderOBtn}
            onRenderItem={onRenderItem}
          />
```

where onRenderItem defined like as follows:

```
export function onRenderItem(item: IOverflowSetItemProps): JSX.Element | undefined {
  return undefined;
};
```
In this case, onRenderItem never gets called. Note, I did not specified `Items` props as Items is optional and as I want to render only overflow items.

In this case, why we have onRenderItem can be optional.

I think, this is the scenario @gnanavelum  also refering too.
