### ISSUE TITLE
Confusing docs on ExtendedPicker

### ISSUE THREAD

**Issue by Adjective-Object** [OfficeDev/office-ui-fabric-react#7860]
https://github.com/OfficeDev/office-ui-fabric-react/blob/1b9405b3b64839975e16ee1fad04d7868d9e3b99/packages/office-ui-fabric-react/src/components/ExtendedPicker/docs/ExtendedPeoplePickerDonts.md

The don'ts for this component say:
> - Use the ExtendedPeoplePicker to select something other than people
> - Use the ExtendedPeoplePicker to only display people

Which looks like a contradiction to me. Is it kosher to use the picker for items that aren't people or not?

**Comment by KevinTCoughlin** [comment]
> 
> 
> https://github.com/OfficeDev/office-ui-fabric-react/blob/1b9405b3b64839975e16ee1fad04d7868d9e3b99/packages/office-ui-fabric-react/src/components/ExtendedPicker/docs/ExtendedPeoplePickerDonts.md
> 
> The don'ts for this component say:
> 
> > * Use the ExtendedPeoplePicker to select something other than people
> > * Use the ExtendedPeoplePicker to only display people
> 
> Which looks like a contradiction to me. Is it kosher to use the picker for items that aren't people or not?

Hey @Adjective-Object! I can see how the wordage here is confusing. My read of it is that one should avoid using `ExtendedPeoplePicker` to _only_ display people without providing a way to un/select them.

We accept contributions to the documentation and would be happy to review one which clarifies intent here.
