### ISSUE TITLE
FocusTrapZone does not work as expected in Safari

### ISSUE THREAD

**Issue by kelseyyoung** [OfficeDev/office-ui-fabric-react#7862]
### Environment Information 
 
- __Package version(s)__: Latest published (Used demo site) 
- __Browser and OS versions__: Safari, tested with 12.0

### Please provide a reproduction of the bug in a codepen:
 

See below GIFs, can reproduce on demo site
 
#### Actual behavior:
 
Pressing tab inside a FocusTrapZone does not go to the next expected element (the hyperlink), instead it goes all the way down to the implementation dropdown arrow

![focustrapzonesafari](https://user-images.githubusercontent.com/4252452/52097326-81302080-257f-11e9-86a0-0b80be62b75b.gif)
 
#### Expected behavior:
 
Pressing tab inside the FocusTrapZone goes to the next element inside (the hyperlink), gif shown is using Chrome

![focustrapzonechrome](https://user-images.githubusercontent.com/4252452/52097302-5b0a8080-257f-11e9-9aa1-ce2825325a02.gif)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Not very familiar with this component but could help investigate
 
Requested priority: High
 
Products/sites affected: None right now, planning on starting experimentation on a feature which is affected by this bug in the next few weeks

**Comment by natalieethell** [comment]
Hey @kelseyyoung! Interesting, I just tested this out in Safari 12.0.1 and saw the behavior you have in the Chrome gif. 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/14134000/52150803-eb9b9c00-2625-11e9-89c8-ba6cdf4fbc6f.gif)

Do you have "Press tab to highlight each item on a webpage" set in Safari preferences?

<img width="772" alt="screen shot 2019-02-01 at 1 02 14 pm" src="https://user-images.githubusercontent.com/14134000/52149471-ac6b4c00-2621-11e9-8c78-688f2a97b57b.png">

**Comment by kelseyyoung** [comment]
@natalieethell thanks for taking a look. You're right that option seems to fix it, however I tested on 3 different Mac machines and this option is off by default. Is this known? (in terms of how Safari functions, I have a Mac laptop at home but obviously I mostly work on Windows machine) Also, if you turn that option off do the repro steps work for you? (Just to verify that it is indeed that option causing the weirdness)

I think it's a non-fix then, but I guess I'm very surprised if this is Safari's default

**Comment by natalieethell** [comment]
@kelseyyoung just doing a quick search, it looks like a couple people have started discussions online about this strange default. I don't get the same behavior as you, but something just as strange - I'm actually not able to tab outside of the TextField at all. 

Even when rendering two native HTML button elements, they are not tabbable in Safari unless that option is on, as you can see in this CodePen: https://codepen.io/naethell/pen/aXWNXv.

Given that, I would agree that this seems like a Safari issue, not a Fabric issue.

**Comment by natalieethell** [comment]
If you have any other questions, let us know! Otherwise, feel free to close this issue.
