### ISSUE TITLE
Is there a codepen example for how to use the new component under dashboard file?

### ISSUE THREAD

**Issue by KeiraYang** [OfficeDev/office-ui-fabric-react#7865]

**Comment by natalieethell** [comment]
Hey @piyumi25! For future reference, we kindly request that all questions be directed to [StackOverflow](https://stackoverflow.com/questions/tagged/office-ui-fabric). We'd like to keep issues limited to feature requests and bugs. 

I'm not aware of any CodePen examples, but you can find examples of how to use components in the `@uifabric/dashboard` package by cloning the office-ui-fabric-react package, going to packages/dashboard, and running `npm start` after completing a build. 

Here is one Donut Chart example: https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/dashboard/src/components/Card/examples/Card.Chart.Donut.Example.tsx

Thank you!
