### ISSUE TITLE
Sensible defaults for ExtendedPeoplePicker

### ISSUE THREAD

**Issue by Adjective-Object** [OfficeDev/office-ui-fabric-react#7871]
**Describe the feature that you would like added**

The only example for ExtendedPeoplePicker is 300 lines of what mostly looks like boilerplate and state management code.

I'm currently working on PR to add some more simple examples. I feel like having sensible defaults (e.g. for the headers / footers) could make component consumption easier to read/understand/adopt.

**What component or utility would this be added to**

ExtendedPeoplePicker

**Have you discussed this feature with our team, and if so, who**

not yet! opening this issue to talk about it more

**Additional context/screenshots**

**Comment by kenotron** [comment]
Feel free to get an email thread going with the Fabric crew!

**Comment by khmakoto** [comment]
Hi @Adjective-Object, is it okay to close this issue in favor of #7941 that you opened? Seems like that one has more concrete information and is linking to this one either way.
