### ISSUE TITLE
Can't set children on Modal using TypeScript 3.3.1

### ISSUE THREAD

**Issue by dlannoye** [OfficeDev/office-ui-fabric-react#7874]
### Environment Information 
 
- __Package version(s)__: 6.132.0

### Please provide a reproduction of the bug in a codepen:
Try to compile the following code using Typescript 3.3.1
```
import { Modal} from 'office-ui-fabric-react/lib/Modal';
import * as React from 'react';

export const MyModal: React.SFC = () => {
    return (
        <Modal>
            <div>hello world</div>
        </Modal>
    );
}
``` 

 
#### Actual behavior:
 
Compile error
```
index.tsx:6:10 - error TS2559: Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & IModalProps'.

6         <Modal>
           ~~~~~


Found 1 error.
```
 
#### Expected behavior:
 
No compile error

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: High
 
Products/sites affected: (if applicable)

**Comment by asmundg** [comment]
Looks like TS 3.3's TSX checks that it can pass children as part of the component props (the output js passes everything in createElement's props argument).

This probably means that functional components need to include children in their props interface (IModalProps in this case).

The FunctionComponent in newer @types/react versions explicitly adds children to the accepted props:
```
    interface FunctionComponent<P = {}> {
        (props: P & { children?: ReactNode }, context?: any): ReactElement<any> | null;
        propTypes?: ValidationMap<P>;
        contextTypes?: ValidationMap<any>;
        defaultProps?: Partial<P>;
        displayName?: string;
    }
```

**Comment by bagau** [comment]
I spent many time to understand where I should set this declare module.

> ```
> declare module 'office-ui-fabric-react/lib/Modal' {
>  const Modal: React.StatelessComponent<IModalProps>;
> }
> ```

May be some people doesn't understand too.
This code I pasted to react-app-env.d.ts file and now it's working.

**Comment by Paul-Colucci** [comment]
I am also experiencing this issue.  How do I resolve this?

**Comment by Paul-Colucci** [comment]
Updating to the latest version of  office-ui-fabric-react  (v6.166.0) worked for me

**Comment by juanpvy** [comment]
Yes, version office-ui-fabric-react (v6.166.0)  works fine
