### ISSUE TITLE
Sticky: Loses focus on scroll

### ISSUE THREAD

**Issue by nuh1234** [OfficeDev/office-ui-fabric-react#7875]
### Environment Information 
 
- __Package version(s)__: (Current) 
- __Browser and OS versions__: (Any)

#### Actual behavior:
 
When tab focused on a sticky element upon scroll the focus gets lost. This is because Sticky is actually creating a new phantom element and therefore needs to put focus on that element 
 
#### Expected behavior:
 
When tab focused on a sticky element upon scroll the focus should stay on the element 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: ( Normal) 
 
Products/sites affected: (if applicable)

**Comment by HalcyonPride** [comment]
N.B. This is causing an Accessibility Bug in ODB.
