### ISSUE TITLE
Text for selected/hovered item in dropdown is not displayed in high contrast

### ISSUE THREAD

**Issue by prmittal** [OfficeDev/office-ui-fabric-react#788]
![image](https://cloud.githubusercontent.com/assets/11937034/21847193/984c9194-d820-11e6-9cd3-9f2958dd51c8.png)

The screen shot is taken from the fabric-react demo page.

Also, the border above and below the drop icon is hidden.

**Comment by mdahamiwal** [comment]
Its a bug with Edge browser. You shouldn't see this in IE11 or any other browser. We have a tracking issue with Edge team to fix this.

**Comment by mdahamiwal** [comment]
being tracked with #1273
