### ISSUE TITLE
Deep-linking on the developer.microsoft.com OUIFR site doesn't work.

### ISSUE THREAD

**Issue by iclanton** [OfficeDev/office-ui-fabric-react#7888]
Copy+paste+sending a deep link to a page/subpage on the fabric website renders a blank page. For example, visit https://developer.microsoft.com/en-us/fabric, select Components --> Colors --> Themes --> Output, copy the URL in the address bar (https://developer.microsoft.com/en-us/fabric#/customizations/colors#Output), open a new tab, and navigate to that URL.

#### Actual behavior:
 
A blank page is rendered:
![image](https://user-images.githubusercontent.com/5010588/52163463-37d2f480-2697-11e9-8cd5-24b55c567fc2.png)
 
#### Expected behavior:
 
The page manually navigated to is rendered:
![image](https://user-images.githubusercontent.com/5010588/52163473-5b963a80-2697-11e9-9c37-5411abaa7af7.png)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? **Yes** (but I don't have a ton of time right now, and this issue is a little embarrassing)
 
Requested priority: **Normal**
 
Products/sites affected: https://developer.microsoft.com/en-us/fabric
 
-----

As a separate issue, it's worth noting that the site still has a fairly large border on the left when rendered in a small window (see image under **Expected behavior**)

**Comment by kenotron** [comment]
This is caused by the lack of a trailling slash. I've fixed this on the github.com description. 

This works, for example.
https://developer.microsoft.com/en-us/fabric/#/components/colorpicker
