### ISSUE TITLE
Redirect when selecting a Dropdown item

### ISSUE THREAD

**Issue by philippe-entringer** [OfficeDev/office-ui-fabric-react#7889]
I 'm using the Dropdown example but I would like to handle href link 
Whe a user clicks on a item, How could we redirect to the href link  ?

 `<div className="docs-DropdownExample">
        <Dropdown
          placeholder="Select an Option"
          label="Basic uncontrolled example:"
          id="Basicdrop1"
          ariaLabel="Basic dropdown example"
          options={[
            { key: 'Header', text: 'Actions', itemType: DropdownMenuItemType.Header },
            { key: 'A', text: 'https://bing.com', title: 'I am option a.', href:"https://bing.com"} ,
            { key: 'B', text: 'Option bb',href:"https://bing.com" },
            { key: 'C', text: 'Option c', disabled: true },
            { key: 'D', text: 'Option d' },
            { key: 'E', text: 'Option e' },
            { key: 'divider_2', text: '-', itemType: DropdownMenuItemType.Divider },
            { key: 'Header2', text: 'People', itemType: DropdownMenuItemType.Header },
            { key: 'F', text: 'Option f' },
            { key: 'G', text: 'Option g' },
            { key: 'H', text: 'Option h' },
            { key: 'I', text: 'Option i' },
            { key: 'J', text: 'Option j' }
          ]}
          onFocus={this._log('onFocus called')}
          onBlur={this._log('onBlur called')}
        />
        </div>`

Thanks for your help !!

**Comment by kenotron** [comment]
I'm working on this at this codepen: https://codepen.io/anon/pen/GzvqWv

**Comment by kenotron** [comment]
Basically you just need to add a `onChange`:

```
onChange={(evt, option) => {
   window.location.href = option.href
}}
```

BTW, there's an internal MSFT Teams chat that can help you with this sort of question a lot quicker. Just search for Fabric team in the org.

**Comment by kenotron** [comment]
I believe this should answer your question here. Feel free to close at your convenience.

**Comment by philippe-entringer** [comment]
thanks for the feedback.
It works well on https://codepen.io/anon/pen/GzvqWv
but the OnChange method did not compiled in my Env.


`[ts] Impossible d'assigner le type '(evt: any, option: any) => void' au type '(event: FormEvent<HTMLDivElement>) => void'. [2322]
index.d.ts(795, 9): The expected type comes from property 'onChange' which is declared here on type 'IntrinsicAttributes & IntrinsicClassAttributes<Dropdown> & Readonly<{ children?: ReactNode; }> & Readonly<IDropdownInternalProps>'
(JSX attribute) onChange?: (event: React.FormEvent<HTMLDivElement>) => void`

thanks for your help

**Comment by kenotron** [comment]
I'm sorry, without a bit more code I can't tell you what's wrong in your env. Please list out these things:

@types/react version
react version
office-ui-fabric-react version
node version
webpack version
typescript version

And if you can, maybe paste in the exact code you're using to consume this component...

**Comment by kenotron** [comment]
I don't think this is a bug in Fabric. I would encourage you to post this issue on StackOverflow with the `[office-ui-fabric]` tag to get a wider community to assist you in your question.
