### ISSUE TITLE
Unable to check a checkbox within a Panel with scrollable content

### ISSUE THREAD

**Issue by jhholm** [OfficeDev/office-ui-fabric-react#7891]
Not sure if a bug or "works as intended", but I've noticed an issue with FocusTrapZone with Panel component when I upgraded to the latest version. Could not reproduce issue with 6.37.1, which was the version I was upgrading from. You need to explicitly set focusTrapZoneProps.forceFocusInsideTrap to false to be able to check a Checkbox within a scrollable panel. Is this a bug or an intended feature?

### Environment Information 
 
- __Package version(s)__: (6.133.0, latest) 
- __Browser and OS versions__: (Chrome 71.0.3578.98, FireFox 67.0a1 Nightly, Windows 10 1809)

### Please provide a reproduction of the bug in a codepen:

Create a Panel with enough content to make content scrollable. Add a Checkbox that you need to scroll down to be able to check. Try to check the checkbox with your mouse. You can check it via keyboard.

Example with reproduction guide in textfields:
https://codepen.io/anon/pen/wNeZbM
 
#### Actual behavior:
 
Trying to check the checkbox with a mouse will scroll the pane content back up and force focus to the first element. You are unable to check the checkbox with a mouse with Panel default focustrapzone properties.
 
#### Expected behavior:
 
You should be able to check the checkbox with a mouse.

#### Priorities and help requested:
 
Requested priority: (Low)

**Comment by kenotron** [comment]
@dzearing - I just did a bunch of back versioning with the reported codepen. Looks like it started "failing" after 6.132.0 (6.131.0 still worked) which coincides with that focus change that you did here:

https://github.com/OfficeDev/office-ui-fabric-react/pull/7818/files

Can you take a look?

**Comment by kenotron** [comment]
Correction, from more digging, it's probably this:
https://github.com/OfficeDev/office-ui-fabric-react/commit/ba23368320b3922a98956ca3f2acf0cb1de9480c
