### ISSUE TITLE
Automate testing Fabric consumption

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#7892]
Make sure controls can be consumed in various modes and Typescript versions.

**Comment by micahgodbolt** [comment]
create react app
TS range
AMD

**Comment by kenotron** [comment]
I'm wrestling whether to have this be a PR gate or a post publish & notify on break kind of thing

**Comment by micahgodbolt** [comment]
Yeah, at least for now we don't need this to break builds, but we should be aware of it happening as soon as possible. 

We can at least break publishing so that we have time to look back and fix the problem before a release.

**Comment by kenotron** [comment]
I actually implemented this with an internal Devops build definition. So there's no code to show here, so I'm close this one.
