### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by HeToC** [OfficeDev/office-ui-fabric-react#79]
Just created sample react+redux app using yo aspnetcore-spa  and added office-ui-fabric-react
And ive occured with a strange problem after adding a button from the sample
import { Button } from 'office-ui-fabric-react/lib/Button';
<Button>Office UI Fabric button</Button>

Exception: Call to Node module failed with error: ReferenceError: document is not defined
at registerStyles (C:\Projects\IMS\node_modules\load-themed-styles\lib\index.js:152:16)
at applyThemableStyles (C:\Projects\IMS\node_modules\load-themed-styles\lib\index.js:45:9)
at Object.loadStyles (C:\Projects\IMS\node_modules\load-themed-styles\lib\index.js:33:5)
at Object.<anonymous> (C:\Projects\IMS\node_modules\office-ui-fabric-react\lib\components\Button\Button.scss.js:3:22)
at Module._compile (module.js:541:32)
at Object.Module._extensions..js (module.js:550:10)
at Module.load (module.js:458:32)
at tryModuleLoad (module.js:417:12)
at Function.Module._load (module.js:409:3)
at Module.require (module.js:468:17)

Exception: Call to Node module failed with error: ReferenceError: document is not defined at registerStyles (C:\Projects\IMS\node_modules\load-themed-styles\lib\index.js:152:16) at applyThemableStyles (C:\Projects\IMS\node_modules\load-themed-styles\lib\index.js:45:9) at Object.loadStyles (C:\Projects\IMS\node_modules\load-themed-styles\lib\index.js:33:5) at Object.<anonymous> (C:\Projects\IMS\node_modules\office-ui-fabric-react\lib\components\Button\Button.scss.js:3:22) at Module._compile (module.js:541:32) at Object.Module._extensions..js (module.js:550:10) at Module.load (module.js:458:32) at tryModuleLoad (module.js:417:12) at Function.Module._load (module.js:409:3) at Module.require (module.js:468:17)

**Comment by dzearing** [comment]
Hmm... is this code running in Node? or in a browser?

**Comment by HeToC** [comment]
Im using AspNetCore and Visual Studio 2015 to start the server on iisexpress i guess.

**Comment by HeToC** [comment]
Well guys ive solved this problem month ago but was a little bit lazy to post workaround here
finally...
the problem was with enable server side prerendering feature, so i have to disable it. ofc this is not a good solution just a simple workaround.

**Comment by dzearing** [comment]
There are teams requesting ssr support, so it is something we are investigating, but currently is not being actively validated.

Thanks for the followup!
