### ISSUE TITLE
"Search keyword" in Search box is not aligned on IE11

### ISSUE THREAD

**Issue by nipunja** [OfficeDev/office-ui-fabric-react#790]
### Bug Report

- __Browser and OS versions__: IE11

#### Describe the issue:

"Search keyword" in Search box is not aligned on IE11
![image](https://cloud.githubusercontent.com/assets/11870255/21847660/15db2876-d823-11e6-8e5b-11aec552711c.png)

#### Actual behavior:

"Search keyword" in Search box is not aligned on IE11

#### Expected behavior:

"Search keyword" in Search box should be aligned

### If applicable, please provide a codepen repro:
https://fabricreact.azurewebsites.net/fabric-react/master/#/examples/searchbox (open on IE11)

**Comment by mdahamiwal** [comment]
Already fixed with https://github.com/OfficeDev/office-ui-fabric-react/commit/a8a6792be4f44cc4b6a3317616f7154aae83925f. Can you check with latest fabric version?

**Comment by mdahamiwal** [comment]
Verified with latest bits and confirm it is fixed.
