### ISSUE TITLE
Icons disappeared from SPFx web parts on classic Sharepoint sites

### ISSUE THREAD

**Issue by sadomovalex** [OfficeDev/office-ui-fabric-react#7900]
### Environment Information 
 
- __Package version(s)__: 5.131.0

#### Actual behavior:
 
This morning (5 Feb 2019) UI fabric icons which are used inside office-ui-fabric-react components (e.g. inside SearchBox) disappeared from SPFx web parts running on classic Sharepoint sites. On modern sites icons are still shown.

The issue is reproduced on all tenants where we use SPFx web parts on classic pages.
 
#### Expected behavior:
 
Icons are shown both on classic and modern sites like it was before today.

#### Workaround
 
So far we have found the following workaround: in SPFx web part add the following lines:
```javascript
import { initializeIcons } from '@uifabric/icons';
initializeIcons();
```
With this fix icons are displayed both on classic and modern pages. But before today's they were displayed on both sites types without this fix.

**Comment by SanjivKrSharma1** [comment]
We are also facing same issue.  Applied the work-around provided in this thread an it is working now.

Thanks @sadomovalex

**Comment by kenotron** [comment]
I'm pretty sure this is caused by this change: 
https://github.com/OfficeDev/office-ui-fabric-react/blob/5.0/packages/office-ui-fabric-react/CHANGELOG.md#5150

> **Minor changes**
> Removing the `initializeIcons` call from the top level import. The bundle in the dist folder used in codepens will still continue to have it, so that codepens don't stop rendering icons.

This change from Fabric over a year ago. @sadomovalex - would you mind filing a bug here instead: https://github.com/SharePoint/sp-dev-docs/issues

I don't believe we will revert this change since it's been live for the 5.x branch for such a long time.

**Comment by sadomovalex** [comment]
I can post the bug to the mentioned page also but it is still not clear why the issue has appeared yesterday without any actions from our side. And today on some environments icons appear again without applying mentioned fix with explicit call of initializeIcons() method. Something went wrong yesterday - but what was that? If this minor mentioned fix was done about 1 year ago - why it appeared only now. I wonder because this issue may appear again if we won't know the reason.

**Comment by rog1fly** [comment]
Thanks, I'll try to find and define some ends to deads wisdow. guess i'll
no when or what appears best . roger

**Comment by kenotron** [comment]
Thanks @sadomovalex
