### ISSUE TITLE
Stack.Item doesn't allow for conditional rendering with logical &&

### ISSUE THREAD

**Issue by redoz** [OfficeDev/office-ui-fabric-react#7901]
### Environment Information 
 
- __Package version(s): @uifabric/experiments 6.54.2 (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:
```jsx
<Stack>
   <Stack.Item>
      { false && <DefaultButton>hello</DefaultButton> }
   </Stack.Item>
</Stack>
```
Produces this error:
```
Type 'false' is not assignable to type 'string | ReactElement<IStackItemProps> | (string | ReactElement<IStackItemProps>)[] | (string & {}) | (string & ReactElement<any>) | (string & ReactNodeArray) | (string & ReactPortal) | ... 14 more ... | undefined'.ts(2322)
StackItem.types.d.ts(21, 5): The expected type comes from property 'children' which is declared here on type 'IntrinsicAttributes & IStackItemProps & { children?: ReactNode; }'
```
   

 
#### Expected behavior:
I expected `<Stack.Item>` to be able to hold all children items that react allows for.
It seems the `children` property definition on `IStackItemProps` is too strict: `children?: (React.ReactElement<IStackItemProps> | string)[] | React.ReactElement<IStackItemProps> | string;`

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? If I knew what the correct fix was, sure.
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by kenotron** [comment]
@khmakoto - this component is STILL experimental, but there seems to be some typing issues. Can you take this on?

**Comment by khmakoto** [comment]
This does seem like a bug, will discuss with @dzearing what's the correct approach to take here.

**Comment by kenotron** [comment]
I suppose this looks more like a feature to support typing correctly since this component isn't even out.
