### ISSUE TITLE
Picker input is pushed to next line when tag picker goes multiline 

### ISSUE THREAD

**Issue by sumboxcar182** [OfficeDev/office-ui-fabric-react#7910]
### Environment Information 
 
- __Package version(s)__: 6.124.2
- __Browser and OS versions__: Not relevant i believe, but windows 10, chrome 

### Please provide a reproduction of the bug in a codepen:

The codepen is below and note that i was testing on a 1920x1080 screen, and the second row of items was about half way into the input. 
https://codepen.io/sumboxcar182/pen/KJXOqj  

 
#### Actual behavior:
 
The tag picker is rendering the cursor always at the next line, even when there is a lot of space present on the current line. 
 
#### Expected behavior:
 
Previous versions of the Tag Picker (tested @ 6.25.1) always kept the cursor next to the last tag.  Here's a codepen of what it was doing previously https://codepen.io/sumboxcar182/pen/qgVWNY 

Looking at the code itself, it looks like there is a new span that wraps the selected items, and it does not have the input inside of it, so it ends up causing the input to be pushed to the next line when you get to the next row of tags. 

When i placed the input into that span it was fixed and brought back the previous functionality, but i'm not sure if this is something that fabric wants.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? If my suggested fix sounds ok i can look at getting a pr up. 
 
Requested priority: (Blocking, High, Normal, Low) : Low
 
Products/sites affected: (if applicable): My company's website (unsure if i'm allowed to say, my apologies).

**Comment by kenotron** [comment]
I have a PR going with your suggested fix. Please check it out!

**Comment by sumboxcar182** [comment]
Hey @kenotron ! Thank you so much for looking at this so quickly! I just saw the discussion that happened, and i completely understand the reasoning why the input was moved out at least.

**Comment by kenotron** [comment]
Apologize about the issue. However, without a pretty big rewrite of this component, I don't think we can achieve what you want (though it is sad that we had it working the other way). We always have to weigh our UX against accessibility standards. @joschect made a really good point about it as you had mentioned. I'm going to resolve this by design. Thanks for reporting this!

**Comment by sumboxcar182** [comment]
No worries about apologizing i cannot thank you enough for helping to resolve this! I spoke with my pm too and explained what's going on and they are completely on board with keeping things as is too, so i'm going to close down this issue if that's ok. Especially making things more accessible is always the way to go!

Again thank you so much for looking into this!
