### ISSUE TITLE
Fabric panel does not close when clicking overlay

### ISSUE THREAD

**Issue by corriespondent** [OfficeDev/office-ui-fabric-react#7911]
On the Office UI Fabric Panel description from https://developer.microsoft.com/en-us/fabric#/components/panel

"Panels are paired with the Overlay component, also known as a Light Dismiss. The Overlay blocks interactions with the app view until dismissed either through clicking or tapping on the Overlay or by selecting a close or completion action within the Panel."

However, clicking the Overlay does not actually close the panel in any of the examples on the page.

**Comment by micahgodbolt** [comment]
Light dismiss needs to be enabled to make this work

![image](https://user-images.githubusercontent.com/1434956/52384052-afef4080-2a30-11e9-8cd8-560bb69c0f55.png)

This above example is working for me. If it isn't working for you, can you tell me the os/browser you are on?

**Comment by corriespondent** [comment]
Thanks so much, @micahgodbolt! I obviously overlooked that example. My bad!
