### ISSUE TITLE
Custom rendered Seletion items in FloatingPeoplePicker push the remove button out of view

### ISSUE THREAD

**Issue by Adjective-Object** [OfficeDev/office-ui-fabric-react#7912]
### Environment Information 
 
- __Package version(s)__: 6.135.0
- __Browser and OS versions__: All browsers? (tested on FF 64 and Chrome 71 on Windows)

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/adjective-object/pen/MLOmqv

Search "An" in personas on this pen
 
#### Actual behavior:
 
Wide rendered custom item buttons push the close button out of the picker

https://youtu.be/553z89TcMvY
 
#### Expected behavior:
 
The close button should always be visible

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: (Blocking, High, Normal, Low) 
 
Normal

Products/sites affected: (if applicable)
 
Outlook

**Comment by kenotron** [comment]
So when I looked at your implementation, you are arbitrarily setting the width as opposed to a single width like here: https://github.com/OfficeDev/office-ui-fabric-react/blob/d89394a2c35c7c8cf1b3a47ae5b8dfd8965e2c00/packages/office-ui-fabric-react/src/components/FloatingPicker/PeoplePicker/PeoplePicker.scss#L12

I think if you applied that 180px (or some other width, just not `auto`), it would work.

**Comment by kenotron** [comment]
Feel free to close if this addresses your issue. Contributions are welcome here, but likely to be a bit more involved and could break some other scenarios.

**Comment by Adjective-Object** [comment]
A fixed width doesn't work for our scenario on Outlook; Since the close button is mounted adjacent to the item button, the item button would have to be small enough that there is always room for the close button.

(which is why this hasn't come up in fabric-only scenarios because Personas have a small fixed width).

**Comment by Adjective-Object** [comment]
I'm curious what scenarios this might break. If the current behavior only works if itemButton components have a small enough fixed width that there's room for the close button, then this shouldn't affect them.

**Comment by kenotron** [comment]
My first instinct is to encourage you to write your own custom SuggestionItem if the one from Fabric doesn't work out for you to quickly unblock. We can investigate how to refactor things so that it works inside that floating box.

**Comment by kenotron** [comment]
I've adding a `overflow-x` in a key place. It should actually make this work out for you.

**Comment by kenotron** [comment]
#7914 should address this instead.
