### ISSUE TITLE
Remove button on FloatingPeoplePicker is not keyboard accessible

### ISSUE THREAD

**Issue by Adjective-Object** [OfficeDev/office-ui-fabric-react#7913]
### Environment Information 
 
- __Package version(s)__:  6.135.0

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/adjective-object/pen/YBEQry

Focus to the button and press tab a few times. Contrast with hovering

#### Actual behavior:
 
Keyboard-only users should be able to press the Remove buttons
 
#### Expected behavior:
 
The only way to access the remove button is by using a mouse

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal
 
Products/sites affected: Outlook

**Comment by micahgodbolt** [comment]
Yeah, the X next to person 1 only shows up on hover, but not focus. 

![image](https://user-images.githubusercontent.com/1434956/52429801-a5c55480-2ab9-11e9-9e08-716ed456cb6a.png)

**Comment by Adjective-Object** [comment]
> We need this to be distinguished from just selecting based on mouse or something so the remove button doesn't show up for those cases as before

Wouldn't it show anyway if you were trying to select via mouse? because of the hover effect?

**Comment by micahgodbolt** [comment]
@Adjective-Object is this feature still active? Your codepen is currently broken and our internal demo example doesn't show the 'remove' button. Any idea how I get those to show up?

**Comment by micahgodbolt** [comment]
And of course, as soon as I ask, I find it!

**Comment by micahgodbolt** [comment]
Digging in and it appears that there is a keyboard accessible way to remove items, which is to press shift + delete. This shift key was added in #7274. 

Not going to argue if that is the best way to delete or not, but it does resolve this issue it seems.
