### ISSUE TITLE
Documentation: Direction attribute is required for Fabric Core icons

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#7923]
### Environment Information 
 
- __Package version(s)__: Latest 
- __Browser and OS versions__: N/A

#### Actual behavior:
 
The [icons documentation](https://developer.microsoft.com/en-us/fabric#/styles/icons) does not mention that `<body dir='ltr'>` (or `rtl`) is required for directional icons to work.

This results in an issue that can be seen in this CodeSandbox: https://codesandbox.io/s/vovq1k7q5

And is fixed here: https://codesandbox.io/s/xpl8nznq6q

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal

**Comment by kenotron** [comment]
Sweet, @mikewheaton, if you can fix it, I can just assign this to you!

**Comment by kenotron** [comment]
Ping @mikewheaton? If you still want to tackle, feel free to continue on it. I'm putting it in the backlog for now.
