### ISSUE TITLE
Allow a different first column in DetailList instead of forcing to have a checkbox column

### ISSUE THREAD

**Issue by vandancd** [OfficeDev/office-ui-fabric-react#7938]
**Describe the feature that you would like added**
The **DetailList** component forces us to have a check box as the very first column (if we need to).  There is no way for me to add a different column before the checkbox.  For someone who is using the detailList for a complex or a say an overloaded content list we did like to add a menu before the checkbox that allows to take an action on a specific item in the list. Currently my option is to have it after the checkbox which kind of feels a weird User Experience.  

**What component or utility would this be added to**
DetailList

**Have you discussed this feature with our team, and if so, who**
No

**Additional context/screenshots**
-NA-

**Comment by ambroisebellec** [comment]
+1

**Comment by devancp** [comment]
+1 please

**Comment by micahgodbolt** [comment]
Thoughts on this feature add? How easy would this be?

**Comment by sahil6814** [comment]
+1

**Comment by mjkozicki** [comment]
+1

**Comment by sming** [comment]
+1 would be great.

**Comment by akpowell** [comment]
love it! 👍
