### ISSUE TITLE
MessageBar doesn't look right on strong colored backgrounds

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#7939]
MessageBar uses semi-transparent colors which were designed for either white, or black backgrounds. When there is a strong color behind them, these colors wash out and don't look right. Only the grey background works, all others are inaccessible.

![image](https://user-images.githubusercontent.com/20363037/52506478-8b67a580-2ba3-11e9-81dd-ff0d1e8110f1.png)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes)
 
Requested priority: (High) 
 
Products/sites affected: SharePoint

**Comment by kenotron** [comment]
@Jahnp hey there, need some help here to address this issue with this

**Comment by Jahnp** [comment]
Ack, thanks @kenotron. 

@betrue-final-final how would you like to proceed here? I'm not familiar enough with how MessageBar's colors are constructed to have a POV for a fix. cc @mikewheaton and @Vitalius1 who may have more thoughts here. I know we haven't picked up MessageBar's Fluent styles yet--perhaps we can address this as a part of that project.

**Comment by micahgodbolt** [comment]
@JasonGore's variants approach might help this. Though I've always wondered the reasoning behind transparent colors and the challenge if message bars are on top of dark colors.

**Comment by JasonGore** [comment]
I'm assuming by variants you mean schemes. The original example actually seems to be rendered using a strong scheme already and changing colors:

<img width="806" alt="screen shot 2019-02-08 at 1 32 35 pm" src="https://user-images.githubusercontent.com/26070760/52512417-bbfe0e00-2ba8-11e9-906d-b251836832ac.png">
<img width="796" alt="screen shot 2019-02-08 at 2 05 09 pm" src="https://user-images.githubusercontent.com/26070760/52512739-98d45e00-2baa-11e9-9b09-a947e45d01eb.png">

I don't see any examples styles in these particular examples, so it appears the styling within the component is changing based on the scheme calculated by @phkuo's variants package.

There is an assumption by these example pages, however, that the background will be a darker color. This is an explicit decision on my part to lay these examples on a background that's dark, but that may not necessarily be a valid use case for all components.

And yet another step back, I also second Micah's question to the actual use cases of message bar, and if they should ever expected to be overlaid on dark backgrounds (and should they be opaque if so.)

**Comment by mikewheaton** [comment]
I'm not sure why those colors were semi-transparent in the first place since I can't think of any scenarios where we would want them to adapt to the background color or show content behind them. Am I missing something? If not, I'd suggest we just grab the hex values from a screenshot (if this aren't in our shared palette) and use them.

**Comment by Vitalius1** [comment]
@betrue-final-final any thoughts here?
