### ISSUE TITLE
Need a way to limit number of characters entered in ComboBox

### ISSUE THREAD

**Issue by ArpitaGhattuMicrosoft** [OfficeDev/office-ui-fabric-react#7944]
**I am trying to limit the entered text in a ComboBox with a certain amount of characters. ComboBox having an input field needs to support max-length attribute. TextField today supports it.**

**What component or utility would this be added to -- ComboBox**

**Comment by kenotron** [comment]
There isn't an existing path to expose the `<input>` props all the way up to combobox. Will add an `autofillProps` prop for combobox to allow you to do this...

**Comment by ArpitaGhattuMicrosoft** [comment]
Thanks Kenneth!

Regards,
Arpita
