### ISSUE TITLE
IDs used in examples should be unique

### ISSUE THREAD

**Issue by ecraig12345** [OfficeDev/office-ui-fabric-react#7946]
Many of the doc pages have elements with duplicate IDs due to people copy-pasting examples and not updating the IDs. This causes problems for screen readers and is just generally bad practice.

A copy-paste-proof solution would be to change all examples using IDs to generate the IDs using `getId()` and save them in private members.

**Comment by ecraig12345** [comment]
@engineersamuel, something else to look out for when you're cleaning up examples. 

Here's a very contrived codepen demonstrating the proposed fix.
https://codepen.io/anon/pen/KJQZQx

**Comment by kenotron** [comment]
The problem here is that if we introduced yet another function, it makes for really bad copy & paste experience for consumers of examples.

**Comment by kenotron** [comment]
I don't think this would be TOO much work, but I don't feel that we have a really good picture of how to make this clean for users who are looking for succinct example code. Kind of wondering if there's a compile time solution (validation of examples?) that doesn't require extra functions to be used.

**Comment by ecraig12345** [comment]
That creates a lot more problems than it solves. Instead of being able to just use our controls on a normal page, we'd have to write tooling to call the codesandbox API to create the examples.

I just made #7953 as a sample of converting to `getId()` (and removing some IDs that are entirely unneeded).
