### ISSUE TITLE
Give simple example for HoverCard

### ISSUE THREAD

**Issue by pcherkasova** [OfficeDev/office-ui-fabric-react#7948]
Can you please provide Hello World example for HoverCard? I mean, something like i click 'hello', and 'world' will pop up.

**Comment by JasonGore** [comment]
Have you seen the [various HoverCard examples](https://developer.microsoft.com/en-us/fabric#/components/hovercard)? They have `Export to Codepen` options that should let you play with the various HoverCard examples displayed on that page. Is this what you are looking for?
