### ISSUE TITLE
Apply css for options when options are loading dynamically

### ISSUE THREAD

**Issue by piyumi25** [OfficeDev/office-ui-fabric-react#7949]
I am trying to create choice group with dynamic options. also I need to change the styles of each option. I tried it using classname but it was not success.Can some one help for this?

let numbers = [];
    for(let i=0;i<10;i++){
    numbers.push({
    key:i,text:i,checked: false
    });
    }

    <ChoiceGroup className="numbers" key="numbers" options={numbers} onChanged={this.onRecentMatterChanged}/>

**Comment by JasonGore** [comment]
It doesn't sound like you're reporting an issue against OUFR. Similar to some of your [previous](https://github.com/OfficeDev/office-ui-fabric-react/issues/7491) [requests](https://github.com/OfficeDev/office-ui-fabric-react/issues/7864), @piyumi25, we kindly request that all questions be directed to [StackOverflow](https://stackoverflow.com/questions/tagged/office-ui-fabric). We'd like to keep issues limited to feature requests and bugs. Thank you!

If you are reporting an issue, please fill out our template including a [CodePen](https://aka.ms/fabricpen).
