### ISSUE TITLE
GroupedList missing focusIndex

### ISSUE THREAD

**Issue by PFAR** [OfficeDev/office-ui-fabric-react#7962]
GroupedList sometimes requires a forceUpdate, in that case the scrollbar goes back to the top. 
Either forceUpdate should have an option to preserve scroll position, or there should be an option to move an item back to focus similar to DetailsList. This is a duplicate of #2757 but it was closed due to inactivity.

**What component or utility would this be added to**
GroupedList - focusIndex/getStartItemIndexInView

We use GroupedList more as a treeview component. Perhaps it's the moment to invest in a specialized treeview control.

**Comment by JasonGore** [comment]
Actually #2757 was closed due to merged PR #2772 which added `scrollToIndex`. Does `scrollToIndex` not provide the functionality you are looking for? If not, why?

**Comment by PFAR** [comment]
Hmm then it's a documentation issue, scrollToIndex is not shown here: https://developer.microsoft.com/en-us/fabric#/components/groupedlist

**Comment by JasonGore** [comment]
Yeah, the reason for that is because the documentation does not show elements in inherited interfaces (in this case `IList`) but we are currently making improvements to address that separately.

Does `scrollToIndex` address your issue?

**Comment by PFAR** [comment]
Yes it will, you can close this. 

Sounds great to have inherited functionality added to the documentation, I assume you'd have some sort of table with a column indicating where it's coming from, otherwise you'd have a real challenge finding your methods and properties in all the different interface lists.

**Comment by JasonGore** [comment]
Our current plan is to have links to inherited interfaces to make it clear where each prop is coming from. Thanks for responding, I will go ahead and close this.
