### ISSUE TITLE
Expose checkbox of DetailsList or add options to render checkbox

### ISSUE THREAD

**Issue by didii** [OfficeDev/office-ui-fabric-react#7963]
**Describe the feature that you would like added**

Either expose the predefined checkbox that is used in a `DetailsList` when you specify its `selectionMode` to `single` or `mutliple` or add an option to the group header to still render the default checkbox button even if you override `groupProps.onRenderHeader` of the `DetailsList`.

**What component or utility would this be added to**

It should be new component or added as option to the component `DetailsList`.

**Additional context/screenshots**

Currently, when you use `groupProps.onRenderHeader` property of a `DetailsList`, all rendering is overridden by this method. Meaning both the checkbox and the collapse all button. It would be nice to be able to show a custom header without having to re-implement and style the select group and collapse all buttons again.
The collapse all is pretty easy, but the checkmark is nowhere to be found in the library and has some finnicky css. So I'd rather not touch it myself.

Relevant code:

```jsx
render() {
    return <DetailsList
        items={this.items}
        groups={this.groups}
        groupProps={{onRenderHeader: this.onRenderHeader}}
    />;
}

onRenderHeader(props) {
    return <div>{props.group.name}</div>;
}
```

This is also shown in the documentation: https://developer.microsoft.com/en-us/fabric#/components/detailslist/customgroupheaders

**Comment by didii** [comment]
I completely forgot. I'm creating a webpart which uses outdated libraries. The version of ui-fabric I'm using from my `package.json`:

> "office-ui-fabric-react": "~5.135.0"

So my request might be moot since I won't be able to use it myself anyway.

**Comment by KevinTCoughlin** [comment]
> I completely forgot. I'm creating a webpart which uses outdated libraries. The version of ui-fabric I'm using from my `package.json`:
> 
> > "office-ui-fabric-react": "~5.135.0"
> 
> So my request might be moot since I won't be able to use it myself anyway.

Are you able to upgrade OUFR to `6.x`?

**Comment by agg23** [comment]
This would also be useful if you want to change the checkbox styling to match the standard square checkbox component.

**Comment by KevinTCoughlin** [comment]
This seems like a scenario we should support, tagging as backlog. However, I'm happy to review a pull-request if someone else gets to it first!

**Comment by KevinTCoughlin** [comment]
This is currently in PR https://github.com/OfficeDev/office-ui-fabric-react/pull/8469. Working to resolve review comments and merge.

**Comment by KevinTCoughlin** [comment]
Somewhat related customization ask: https://github.com/OfficeDev/office-ui-fabric-react/issues/7938
