### ISSUE TITLE
New Component/Utility: Text Truncation

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#798]
There are several places in SharePoint that call for "maximum of X lines where the last line truncates if necessary". This functionality has been built by @leddie24 and @battletoilet and I've used it in other contexts as well. This would be a helpful utility/component to bring to Fabric React for wider use.

Example:
![image](https://cloud.githubusercontent.com/assets/1382445/21871559/c6ce356c-d817-11e6-9e88-eccf2c90b947.png)

How I see it being used:

```
<div style="height: 48px; line-height: 24px;">
  <TruncatedText
    text='This is a really long string of text that may span multiple lines.'
    maximumLines={ 2 }
    recalculateOnWindowResize={ true }
    />
</div>
```

In this case it would fit the parent container (both width and height) and then truncate the text until it fits. We could also support a single line of truncated text, which can be handled with pure CSS.

**Comment by cschleiden** [comment]
We have built something similar because we had the requirement to left-truncate text. For content like `"Project\Some area path\Another level\Team\Feature Area X"` the right-most part is more important, so we need ellipsis on the left. 

Might be something that could be incorporated into such a component. We'd use it.

**Comment by mikewheaton** [comment]
That's a good point, @cschleiden. Now that I think of it, we've also done center truncation in the DocumentCard. The idea there is that in a long filename the beginning and end are most important so "Planning Committee Meeting Notes December 14 2017 (Revised).docx" becomes "Planning Committee Meeting ... (Revised).docx".
