### ISSUE TITLE
Fluent styles should use palette colors

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#7983]
### Environment Information 
 
- __Package version(s)__: Latest
- __Browser and OS versions__: N/A

#### Description
 
The Fluent styles include colors like `CommunicationColors.primary` and `NeutralColors.gray160`, which are **not themeable**. These should be replaced with `palette.themePrimary` and `palette.neutralPrimary`.

We weren't able to do this before because buttons didn't accept a style function, but it should now be possible thanks to #7748.

#### Next steps
- [x] @betrue-final-final to update the designs to remove instances of Gray120, Gray110, and Gray80, which aren't in the neutral palette.
- [x] Update all button components to accept style functions, so we can access the palette.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal
 
Products/sites affected: Outlook has run into theming issues

**Comment by Vitalius1** [comment]
@mikewheaton by:

> Update all button components to accept style functions, so we can access the palette.

... you mean update the fluent style objects for buttons to be style functions?

**Comment by Vitalius1** [comment]
1. We are updating `gray120` to use the `palette.neutralSecondary` which is mapped to `gary130`.
2. Almost for sure, we are updating the `gray80` to `gray90` but waiting on the designers' approval.
3. `gray110` is used in `Button` so @betrue-final-final will have to review this carefully... so waiting on his decision.

**Comment by Vitalius1** [comment]
For `gray110` talked to Ben and probably we will bring the `neutralSecondaryAlt` palette slot for this color as there is too much of a gap in between `gray90` and `gray130` for the closest mapped colors in the palette and `gray110` fits perfectly within that slot.

**Comment by Vitalius1** [comment]
I do have a branch started for this issue and almost have it all done... just waiting on some final decisions.
