### ISSUE TITLE
Button: width of icon button is not set correctly in Safari

### ISSUE THREAD

**Issue by MirandaGe** [OfficeDev/office-ui-fabric-react#799]
### Bug Report

- __Package version(s)__: all
- __Browser and OS versions__: Safari

#### Describe the issue:

The width of icon button (80px) is larger than the expected size(32px).
The reason is `min-width: auto` is not supported in Safari.

#### Actual behavior:

<img width="929" alt="screen shot 2017-01-12 at 4 43 39 pm" src="https://cloud.githubusercontent.com/assets/16030290/21887855/b9c996a0-d8fc-11e6-855c-c98555d6c1e7.png">

#### Expected behavior:

set `min-width: 32px` for icon button.

### If applicable, please provide a codepen repro:

check the width of Icon Button in http://dev.office.com/fabric#/components/button under Safari

**Comment by mikewheaton** [comment]
Thanks for the bug report, @MirandaGe. I'll get this fixed.

**Comment by mikewheaton** [comment]
Which version of Safari are you using? I've tested on 10.0.2 (12602.3.12.0.1) and `min-width: auto;` is working as expected:

![image](https://cloud.githubusercontent.com/assets/1382445/21901328/163f0362-d8ac-11e6-82d6-c703b11ccd70.png)

![image](https://cloud.githubusercontent.com/assets/1382445/21901307/03ebc7c2-d8ac-11e6-9d4a-ff91bc6c7fdb.png)

**Comment by MirandaGe** [comment]
Thank you Mike!
I use a Version of 9.1.2(11601.7.7)

**Comment by mikewheaton** [comment]
Fixed and merged.

In this case it was an easy fix, but for future reference we only support the two latest major versions of browsers, as determined by [CanIUse](http://caniuse.com/). For Safari that's versions 10.2 and 9.3.
