### ISSUE TITLE
Modal A11y Pass

### ISSUE THREAD

**Issue by awalia13** [OfficeDev/office-ui-fabric-react#7990]
Tracking all of the issues brought up with the 2/13 accessibility pass on Modal Control
Details on individual bugs can be found on [Sharepoint](https://microsoft-my.sharepoint.com/:x:/p/v-amaver/EWKexiitxhJHoxtcuFBidtcBH-kr9UDz-G9I4R3OZhbXiQ?rtime=ECIKDAGS1kg)

- ~~Bug1: [Accessibility][Programmatic access]: ARIA attributes must conform to valid values.~~
    - JG, 9/19/2019: Following steps in [Sharepoint](https://microsoft-my.sharepoint.com/:x:/p/v-amaver/EWKexiitxhJHoxtcuFBidtcBH-kr9UDz-G9I4R3OZhbXiQ?rtime=ECIKDAGS1kg), bug does not repro on [Fabric 7.35](https://developer.microsoft.com/en-us/fabric#/controls/web/modal) and Accessibility Insights for Web v2.9.2.
- ~~Bug2: [Accessibility][Keyboard Navigation]: Title of the modal is not defined as heading.~~
    - JG, 9/19/2019: I'm not sure what is meant by 'heading' here, but [ARIA dialog](https://www.w3.org/TR/wai-aria-1.1/#dialog) has no heading attribute. It does say `aria-labelledby` should exist, however, which `Modal` adds via the `titleAriaId` prop. It is present in [these examples](https://developer.microsoft.com/en-us/fabric#/controls/web/modal). Narrator and MS Edge also dictate the "heading" in this case. I'm going to cross this out "not an issue" for now.
![image](https://user-images.githubusercontent.com/26070760/65272143-68a35500-dad3-11e9-96b4-e6c5472f041e.png)

- ~~Bug3: [Accessibility][Usable] : Narrator is narrating the title of the modal and close button twice.~~
    - JG, 9/19/2019: This is Narrator behavior and can also be seen in [ARIA modal reference examples](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html). I've found similar issues in the Narrator repo saying this is expected behavior as Narrator is reading both information about the window and then dictating the document element it lands on. I will cross this issue out as "not an issue" for now.
- ~~Bug4: [Accessibility][Usable] : Modal do not close with ESC key while navigating in scan mode.~~
    - JG, 9/19/2019: I'm not sure where this requirement comes from, but [ARIA modal reference examples](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html) also exhibit this behavior. If this is an issue then it appears to be one with Narrator or MS Edge. I will not create an issue at this time since I don't know where this requirement comes from. I will cross this issue off as "not an issue / external" for now.

Component: Modal
@micahgodbolt

**Comment by JasonGore** [comment]
@awalia13 Can you please report browser version? This is particularly important when reporting Narrator issues. Thanks.

**Comment by awalia13** [comment]
Hi Jason, We are using Edge browser. Please find below version.
Microsoft Edge 44.18334.1.0
Microsoft EdgeHTML 18.18334

**Comment by JasonGore** [comment]
I do not see any actionable issues here so I will mark needing Author Feedback and let this issue close unless more feedback is added.

**Comment by 999-Dev** [comment]
Bug1: [Accessibility][Programmatic access]: ARIA attributes must conform to valid values.
We verify those bugs in below Test Enviourment and found issue is not repro'ing. Hence closing the bug.

Test Environment:
OS: Version: RS5_Prerelease(1903 OS Build 18990.1)
URL: https://fabricweb.z5.web.core.windows.net/oufr/7.35.0/#/examples/modal
Edge Browser Version:
Microsoft Edge: 44.18990.1.0
Microsoft EdgeHTML: 18.18990
Chrome Browser Version:
Chrome Version: 76.0.3809.132

**Comment by 999-Dev** [comment]
Bug2: [Accessibility][Keyboard Navigation]: Title of the modal is not defined as heading.

We verify those bugs in below Test Enviourment.

"It is good to defined heading on model dialog for better usability. But as per comment closing the bug."

Test Environment:
OS: Version: RS5_Prerelease(1903 OS Build 18990.1)
URL: https://fabricweb.z5.web.core.windows.net/oufr/7.35.0/#/examples/modal
Edge Browser Version:
Microsoft Edge: 44.18990.1.0
Microsoft EdgeHTML: 18.18990
Chrome Browser Version:
Chrome Version: 76.0.3809.132

**Comment by 999-Dev** [comment]
Bug3: [Accessibility][Usable] : Narrator is narrating the title of the modal and close button twice.

We verify those bugs in below Test Enviourment and found it's working fine. Hence closing the bug.

Test Environment:
OS: Version: RS5_Prerelease(1903 OS Build 18990.1)
URL: https://fabricweb.z5.web.core.windows.net/oufr/7.35.0/#/examples/modal
Edge Browser Version:
Microsoft Edge: 44.18990.1.0
Microsoft EdgeHTML: 18.18990
Chrome Browser Version:
Chrome Version: 76.0.3809.132
