### ISSUE TITLE
TextField and SearchBox in Dialog require 2 clicks to regain focus 

### ISSUE THREAD

**Issue by cnshenj** [OfficeDev/office-ui-fabric-react#7992]
### Environment Information 
 
- __Package version(s)__:
    "office-ui-fabric-react": "^6.138.1",
    "react": "^16.8.1",
    "react-dom": "^16.8.1",

- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
https://codesandbox.io/s/91oz23zj64
1. Click the `TextField` in the `Dialog` to focus
2. Click outside the `TextField` (e.g. empty Dialog area) to move focus out
3. Click the `TextField` again

#### Actual behavior:
The `TextField` doesn't have focus, doesn't accept typing.
Click the `TextField` one more time, it will then regain focus.

The `TextField` outside the `Dialog` is not affected. 
 
#### Expected behavior:
After step 3, the `TextField` should have focus

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
Maybe
 
Requested priority: (Blocking, High, Normal, Low) 
Normal
 
Products/sites affected: (if applicable)

**Comment by JasonGore** [comment]
This is odd in how much the behavior varies. I've also created [a CodePen](https://codepen.io/jasongore/pen/YBJKPB?editors=1010) which also shows this issue occurring, but with varying frequency:
1. Is not an issue when focus is still within "application" window or `Modal`.
1. Is an issue when moving focus into CodePen IDE area and back into TextField.
    1. However even in this instance it appears to work occasionally (~10% of the time)
1. Does not appear to be an issue at all in CodePen's "Debug mode", even when moving focus to browser menu or outside browser.

This obviously has something to do with DOM hierarchy and may also have an async component to it.

**Comment by JasonGore** [comment]
This and #8011 appear to be regressions caused by #7906.

**Comment by kenotron** [comment]
This #7906 was a fix proposed by @dzearing and addressed the issue raised. I am not sure what the right fix would be - if we revert, we would break something else...

**Comment by JasonGore** [comment]
[This CodePen](https://codepen.io/jasongore/pen/bzJQWy) shows that this issue appears to have been fixed due to the merge of #8053 and release of v6.142.0. Please let me know if you see any other issues. Thanks!

**Comment by cnshenj** [comment]
This is fixed in 6.143.0
