### ISSUE TITLE
Button: ariaDescription prop not readout by JAWS 18.

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#800]
### Bug Report

- __Package version(s)__: latest
- __Browser and OS versions__: IE 11 and JAWS 18

#### Describe the issue:

The prop ariaDescription of Button component is not working correctly with JAWS 18.

#### Actual behavior:

The string passed to ariaDescription is not read.

#### Expected behavior:

The string passed to ariaDescription is read.

### If applicable, please provide a codepen repro:

Focus on the last button on the page
https://fabricreact.azurewebsites.net/fabric-react/master/#/examples/button

**Comment by ipip2005** [comment]
Is currently preparing a fix, will move the description text outside the button element.

**Comment by mdahamiwal** [comment]
Works for me with IE11, Edge or firefox with NVDA or narrator screen reader. Can you try with some other browser ?

**Comment by ipip2005** [comment]
Thanks for reproducing with other ATs.
It's probably an JAWS regression of aria description.
I tested with old version of JAWS 17, it's working properly.
But for JAWS 17 latest version and JAWS 18, it's not working.

**Comment by ipip2005** [comment]
I've reported the issue to JAWS team with a reproduce http://jsbin.com/gaqukufobi/1/edit
Should this issue keep open until JAWS fixed this?

**Comment by dzearing** [comment]
I think we should close this, as there is nothing we can do here.
