### ISSUE TITLE
Dropdown options not read by JAWS in Edge

### ISSUE THREAD

**Issue by kimberlyly** [OfficeDev/office-ui-fabric-react#8006]
### Environment Information 
 
- __Package version(s)__: 6.131.1
- __Browser and OS versions__: Edge 44.17763.1.0

#### Actual behavior:
 
JAWS is reading "Blank" when going through the options in Edge. 

#### Expected behavior:
 
JAWS should read the text of the option.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No
 
Requested priority: (Blocking, High, Normal, Low) Normal
 
Products/sites affected: (if applicable)

**Comment by JasonGore** [comment]
I am not sure what you mean by "go through options". Can you clarify? Do you mean expanding dropdown and scrolling through items, rotating through them with arrow key, or something else?

When I use Microsoft Edge with Narrator on your provided CodePen, everything seems to work fine. I do not see "Blank" being output at any time:

![dropdown](https://user-images.githubusercontent.com/26070760/52822738-6c678880-3067-11e9-9559-4ce7506f0335.gif)

If you can reproduce this with Narrator, please let me know. If this only happens with JAWS, please report the issue against JAWS. Thanks!

**Comment by kimberlyly** [comment]
Thanks for responding Jason! Yes, it works with Narrator but not JAWS, so I'll post this issue there instead.
