### ISSUE TITLE
New Component: Selectable Treeview

### ISSUE THREAD

**Issue by martinalbrektson** [OfficeDev/office-ui-fabric-react#801]
When developing in Office 365 and SharePoint there is, sooner or later, a need to let the user pick items in a SharePoint term set that often is a hierarchical structure.
Since we do not want to make product (SharePoint) specific components we should instead focus on a component that is far more generic. So what is needed is a component that can handle a hierarchical structure and where a user can choose one or more items. For functionality see the image below. (I’m aware that the UI interface should be completely different)

![image](https://cloud.githubusercontent.com/assets/25080616/21892291/5ada5966-d8d6-11e6-8b34-48ff64e0964a.png)

**Comment by webtechy** [comment]
Agree this is needed +1
