### ISSUE TITLE
Tooltip should not render on touch device

### ISSUE THREAD

**Issue by zoarif** [OfficeDev/office-ui-fabric-react#8010]
### Bug Report

- __Package version(s)__: 6.136.0
- __Browser and OS versions__: IOS (Safari on IPad)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Normal

Products/sites affected: (if applicable)

#### Describe the issue:

If you wrap tooltip around any button, it causes you to double tap in IOS. It should not render if touch is enabled since it is a hover only element 

#### Actual behavior:

Tooltip renders in touch causing double tap behaviour

#### Expected behavior:
Tooltip should not render in touch devices.

**Comment by JasonGore** [comment]
Sticky hover in mobile scenarios is a known issue that affects several components. It is covered by #5734.
