### ISSUE TITLE
TagItem 'text-overflow' does not work properly

### ISSUE THREAD

**Issue by Koniksan** [OfficeDev/office-ui-fabric-react#8030]
http://joxi.ru/MAjo5V6Ujk17pr 

I think that something goes wrong here, maybe there need additional property 'white-space: nowrap' for .ms-TagItem-TextOverflow selector
Thanks !

P.S. Still really looking forward to solving this problem #7835

**Comment by aneeshack4** [comment]
@Koniksan Hello! Can you make a codepen that repros this? Because right now, I'm unable to repro, this is what I get when I try in Edge:
![image](https://user-images.githubusercontent.com/4161791/53049299-9ea02e00-344b-11e9-8600-aa2383f19a1d.png)

**Comment by Koniksan** [comment]
https://codepen.io/anon/pen/mvgyRJ?editors=1010

**Comment by aneeshack4** [comment]
I still don't see the problem - what is the expected behavior here? It looks fine to me...
![image](https://user-images.githubusercontent.com/4161791/53135025-6e7d8b80-352e-11e9-939e-aff19cc2370d.png)

**Comment by Koniksan** [comment]
@aneeshack4  Hi 
I am trying to tell you that I don`t understand why do you use this properties for `.ms-TagItem-TextOverflow `

I mean this ones :
- text-overflow: ellipsis;
- overflow: hidden; 

http://joxi.ru/a2XZNywfw4gNyr

They are wont work without property  `white-space: nowrap;`
I am expecting something like that
https://codepen.io/anon/pen/mvgyRJ

Thanks !

**Comment by aneeshack4** [comment]
@Koniksan Thank you for providing further details. I haven't worked with Pickers so I don't know have much knowledge around this but maybe @joschect or @Lego6245, who have worked with Pickers, do?

**Comment by aneeshack4** [comment]
@Vitalius1 helped explain this more to me and I think I get it - sent out a PR #8141. @Koniksan I don't understand what you're saying about the title attribute though - can you elaborate?

**Comment by Koniksan** [comment]
@aneeshack4  Thanks for update, nice to work with you :)
