### ISSUE TITLE
Year button in datepicker not working with keyboard navigation

### ISSUE THREAD

**Issue by Anschur** [OfficeDev/office-ui-fabric-react#8034]
### Environment Information 
 
- __Package version(s)__: What ever is on the Fabric demo page.
- __Browser and OS versions__: Edge and Chrome

### Please provide a reproduction of the bug in a codepen:
 

 
1. Go to the first example on the datepicker demo page or https://codepen.io/anders-sch-rmann/pen/omVbxK?&editable=true
2. Use keyboard and tab to navigate to the year button (2019)
3. Press Enter

#### Actual behavior:
 
Nothing happens (Narrator will say "2019 button"
 
#### Expected behavior:
 
Open a year selection dialog. Similar to what happens when clicking it with a mouse.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: (if applicable)

**Comment by aneeshack4** [comment]
Thank you for reporting this! I'm able to repro it so I'll start on a fix for this.

**Comment by Anschur** [comment]
Great! Thanks :)

**Comment by Anschur** [comment]
Is there any progress on getting this fixed?

**Comment by lorejoh12** [comment]
This bug does not affect the new date-time Calendar, but I just opened a PR that should fix the issue for the OUFR version.
