### ISSUE TITLE
Upgrade to TypeScript 3.3.3

### ISSUE THREAD

**Issue by jdhuntington** [OfficeDev/office-ui-fabric-react#8040]
Upgrade all packages to depend on TypeScript `3.3.3`.

**Comment by khmakoto** [comment]
Bug #7874 should be fixed by the work done for this. In general, it seems that we will have to update all the components that can have `children` but don't have the specific `children` prop in their type definition.

**Comment by jdhuntington** [comment]
Update: 4fca804a1 (presently part of the `fabric-7` branch) builds everything up to and including OUFR with TypeScript 3.3.3. There are several temporary workarounds in place that are being tracked with the comment `FABRIC7VALIDATE` and `FABRIC7TODO`, but it is possible for someone to build. Also targets React 16.8.3 (cc #8041 )

**Comment by jdhuntington** [comment]
Also tracking https://github.com/Microsoft/TypeScript/issues/30050 , which is currently being triggered by a set of things in `BaseComponent`, `FocusZone`, and `FocusZone.types`
