### ISSUE TITLE
Remove deprecated APIs

### ISSUE THREAD

**Issue by jdhuntington** [OfficeDev/office-ui-fabric-react#8042]
Fabric 6 contains several deprecated APIs. In Fabric 7, these will be removed entirely. 

In order to assist consumers through the adoption process, tooling will be provided which will make the necessary changes where possible.

**Comment by KevinTCoughlin** [comment]
@jdhuntington awesome! Is there a branch we can target with deprecated API removals per component. I'd be happy to contribute a few, example:

https://github.com/OfficeDev/office-ui-fabric-react/blob/ecc33a7ee4aa7c21aefc920e043b42a775d2e899/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.types.ts#L368

**Comment by jdhuntington** [comment]
@KevinTCoughlin Thanks! After our discussion today, I'd like to make sure we have a friction-free story for consumers to upgrade. I'm hoping to use #8116 to prototype this pattern and will update this thread as soon as we have a clear story going forward.

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin Thanks! After our discussion today, I'd like to make sure we have a friction-free story for consumers to upgrade. I'm hoping to use #8116 to prototype this pattern and will update this thread as soon as we have a clear story going forward.

Makes sense to me! Keep me posted. We have a few easy examples of deprecated props in `DetailsList` that might be good test cases for the code mod(s).
