### ISSUE TITLE
No way to set ariaDescription on SpinButton or ComboBox

### ISSUE THREAD

**Issue by Dalimil** [OfficeDev/office-ui-fabric-react#8045]
**Describe the feature that you would like added**
We would need either `ariaDescription` prop (same as BaseButton) or `ariaDescribedBy` prop (same as Checkbox) added to SpinButton and ComboBox

**What component or utility would this be added to**
SpinButton and ComboBox

**Comment by aneeshack4** [comment]
@Dalimil Can you please provide more context around this? Why do you want to set ariaDescription on spinbutton and combobox? The ARIA spec doesn't define aria-description as a required property of [spinbutton](https://www.w3.org/TR/wai-aria-1.1/#spinbutton) or [combobox](https://www.w3.org/TR/wai-aria-1.1/#combobox).

**Comment by Dalimil** [comment]
@aneeshack4 It's an optional one. I would need to set ariaDescribedBy (aria-describedby in HTML) in the same way the Fabric Checkbox allows me to. But I believe currently if I set the aria-describedby prop on spinbutton or combobox, the prop is thrown away and not used at all.

**Comment by aneeshack4** [comment]
Ah I see - thank you for adding this & sending out a PR for it!
