### ISSUE TITLE
Keros error: listitem: <li> elements must be contained in a <ul> or <ol> 

### ISSUE THREAD

**Issue by DhirajKhot** [OfficeDev/office-ui-fabric-react#8048]
### Environment Information 
 
- __Package version(s)__: 6.129

### Please provide a reproduction of the bug in a codepen:
 Bug Repro: https://developer.microsoft.com/en-us/fabric#/components/facepile
![image](https://user-images.githubusercontent.com/20378231/53087873-324a2b00-352e-11e9-8177-c975cf1c4a1a.png)

 
#### Actual behavior:
 
Keros issue : "listitem: \<li> elements must be contained in a \<ul> or \<ol>"
 
#### Expected behavior:
 
Keros should not give any issue

**Comment by aneeshack4** [comment]
@DhirajKhot Which part of this example exactly is this error on? The code shows that the <li> elements are in fact inside a <ul> as you can see below:
![image](https://user-images.githubusercontent.com/4161791/53119384-319c9f00-3504-11e9-97ee-d1d681845332.png)

**Comment by DhirajKhot** [comment]
@aneeshack4 Please run the Keros Fast Pass for the given page. You will be able to see the error.

**Comment by aneeshack4** [comment]
I see the error also when I run Keros Fast Pass but it makes no sense because when you inspect the code, you can clearly see that these personas' `<li>`s are inside a `<ul>` I'm following up with the Keros team.

**Comment by DhirajKhot** [comment]
That would help. Thanks.
