### ISSUE TITLE
PeoplePicker - long names go beyond the boundries

### ISSUE THREAD

**Issue by rhalaly** [OfficeDev/office-ui-fabric-react#8050]
### Environment Information 
 
- __Package version(s)__: Latest Fabric UI React
- __Browser and OS versions__: Chrome + Edge in Windows 10

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/anon/pen/LqvVvL
 

 
#### Actual behavior:
 
The names go beyond the PeoplePicker container
![image](https://user-images.githubusercontent.com/8597700/53091698-4d5f6f80-351b-11e9-9715-db0da3c881f9.png)
 
#### Expected behavior:
 
The names should be cut to fit its container. 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: High
 
Products/sites affected: Internal Microsoft Product

**Comment by aneeshack4** [comment]
thanks for reporting this! I'm working on a fix.

**Comment by aneeshack4** [comment]
Worked with @joschect to try and [test a fix](https://github.com/OfficeDev/office-ui-fabric-react/pull/8185) on this by reproing locally and couldn't get a repro but Jon's able to so handing this over to him.

**Comment by rhalaly** [comment]
But I've left a codepen link with a repro.

**Comment by aneeshack4** [comment]
@rhalaly yes thank you for doing that - we are able to see the repro on codepen but we can't test our fix on the codepen, we need to be able to repro and test it locally (for some reason npm start wasn't picking up on the changes I was making to get the repro but Jon is able to get a repro locally so he's going to test the fix and send out a PR for it)

**Comment by Vitalius1** [comment]
@joschect any progress on this?

**Comment by joschect** [comment]
@Vitalius1 Hey! This had fallen off my radar. I think I can get a fix in by eod tomorrow.

**Comment by rhalaly** [comment]
Thank you!
