### ISSUE TITLE
Improve Persona Component documentation

### ISSUE THREAD

**Issue by GreyMana-git** [OfficeDev/office-ui-fabric-react#8063]
The persona documentation is missing some clauses for the tertiary and optional text (see https://developer.microsoft.com/en-us/fabric#/components/persona). See "Persona.styles.ts" for the rules when they apply.

Proposed property documentation changes for properties:
Location: 
\- tertiaryText | string | Tertiary text to display, usually the status of the user.
\+ tertiaryText | string | Tertiary text to display, usually the status of the user. The tertiary text will only be shown when using Size72 or Size100.

\- optionalText | string | Optional text to display, usually a custom message set.
\+ optionalText | string | Optional text to display, usually a custom message set. The optional text will only be shown when using Size100.

**Comment by aneeshack4** [comment]
@GreyMana-git This makes sense to me - please feel free to open a PR with your proposed changes; looks like you just have to change the comments in Persona.types.ts.

**Comment by cliffkoh** [comment]
Thanks for reporting this! PR created at #8076.
