### ISSUE TITLE
Nav: link text is clipped by drop-icon when switched to RTL mode

### ISSUE THREAD

**Issue by mdahamiwal** [OfficeDev/office-ui-fabric-react#808]
### Bug Report
- __Package version(s)__: master

#### Describe the issue:
In RTL mode the expandable navigation link text is clipped by drop icon on first load. Morover, the indentation for other elements is also affected. Check level 1 elements.
![image](https://cloud.githubusercontent.com/assets/12109362/21921213/6d575e0c-d98c-11e6-9fbf-fc3ed8871b49.png)

However, once we interact with the nav it goes away. Its an issue with the way padding is applied to Nav anchors. In this particular case we apply style through JS code in _renderAnchorLink() method and it doesn't trigger re-render if we switch from LTR to RTL mode.
Might not be an issue if browser is already set to RTL.

#### Expected behavior:
![image](https://cloud.githubusercontent.com/assets/12109362/21921315/553f1886-d98d-11e6-9a4c-06580a595b04.png)

### If applicable, please provide a codepen repro:
https://fabricreact.azurewebsites.net/fabric-react/master/#/examples/nav

**Comment by gitjain** [comment]
@mdahamiwal 
I tried to repro the issue and seems it's working fine in IE and Chrome . Can you check and let me know if you are still facing the issue.
