### ISSUE TITLE
PeoplePicker - Korean Characters issue in IE11.

### ISSUE THREAD

**Issue by yumikohey** [OfficeDev/office-ui-fabric-react#8082]
### Environment Information 
Windows 10, IE11.

### Please provide a reproduction of the bug in a codepen:
Since last fix in IE11, it works great in BasePicker.
![basepicker-korean](https://user-images.githubusercontent.com/3360621/53259281-8e729380-3683-11e9-9b31-2a354458a3b3.gif)

However, in people picker, due to loading list of components and autofilter, before Korean Characters composition is end, characters are being swallowed.
![peoplepicker-korean](https://user-images.githubusercontent.com/3360621/53259351-bbbf4180-3683-11e9-8b94-7cb10617907e.gif)

Repro Steps: 
1.      `npm start`, run `localhost:4322` with IE 11. ( Chrome is not repro. )
2.      Go to PeoplePicker, active input field, to show list of available contacts,
3.      Typing Korean Character as you can faster like below sample.
A.      Test Option 1. : “t” -> “h” -> “f”  -> “t” -> “h” -> “f”  -> “t” -> “h” -> “f” 
It should display “솔솔솔” but, sometimes display “솔솔ㅗ”
B.      Test Option 2 : “r” -> “h” -> “f”  -> “r” -> “h” -> “f”  -> “r” -> “h” -> “f” 
C.      Test Option 3 : “r” -> “h” -> “c”  -> “r” -> “h” -> “c”  -> “r” -> “h” -> “c” 
 
#### Actual behavior:
It should display “솔솔솔” but, sometimes display “솔솔ㅗ”

#### Expected behavior:
 It should display “솔솔솔”

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking) 
 
Products/sites affected: Sharepoint and OneDrive

**Comment by aneeshack4** [comment]
Thank you for reporting this @yumikohey! Adding @Lego6245, @joschect, and @amyngu who own Pickers - any of you know why these characters are being swallowed?
