### ISSUE TITLE
TeachingBubble A11y Pass

### ISSUE THREAD

**Issue by awalia13** [OfficeDev/office-ui-fabric-react#8088]
Tracking all of the issues brought up with the 2/22 accessibility pass on TeachingBubble fabric control
Details on individual bugs can be found on [Sharepoint](https://microsoft-my.sharepoint.com/:x:/r/personal/v-amaver_microsoft_com/_layouts/15/Doc.aspx?sourcedoc=%7B2f27d6ee-4e41-49bd-8216-6ca26df23f17%7D&action=default&uid=%7B2F27D6EE-4E41-49BD-8216-6CA26DF23F17%7D&ListItemId=1837&ListId=%7B395E1ECB-5002-440E-81C5-6A090E98077C%7D&odsp=1&env=prodbubble)
- [ ] Bug1: [Accessibility][Programmatic access]: Name is not defined for close button in the TeachingBubble dialog. 
- [ ] Bug2: [Accessibility][Keyboard Navigation]: Title of the TeachingBubble dialog is not defined as heading. 
- [ ] Bug3: [Accessibility][Programmatic access]: Alt attribute is not defined for image inside the TeachingBubble dialog.
- [ ] Bug4: [Accessibility][Usable]: TeachingBubble dialog is not getting closed with ESC key.
- [ ] Bug5: [Accessibility][Keyboard Navigation]: Focus moves to top of the browser in forward navigation instead of staying in the TeachingBubble dialog.
- [ ] Bug6: : [Accessibility][ Supporting the platform]: 'Try it Out' button present in the TeachingBubble dialog is not adopting high contrast  settings. 
- [ ] Bug7: [Accessibility][Usable]: Screen does not scroll down along with keyboard focus in Backward navigation.
- [ ] Bug8: [Accessibility][Usable]: Screen reader is not reading the entire content of dialog box  when the dialog opens.

**Comment by jdhuntington** [comment]
All bug level items opened as discrete items; closing this issue as a dupe.
