### ISSUE TITLE
How to set `name` prop on ChoiceGroup?

### ISSUE THREAD

**Issue by notgiorgi** [OfficeDev/office-ui-fabric-react#809]
### Bug Report 
> (more of a `Help Wanted` type)

- __Package version(s)__: (0.82.4)

I want to have `ChoiceGroup` component in my form, and I need (I'm using redux-form) to set `name` prop on it:

```jsx
    <ChoiceGroup options={options} name="myChoiceGroup"/>
```

But instead of having `"myChoiceGroup"` as name, component ends up with some random generated string.

I looked at source code and cannot find the way to override this behavior:
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroup.tsx#L81

**Comment by notgiorgi** [comment]
Same is true for `TextField` component and _I suppose_ for every form element

**Comment by notgiorgi** [comment]
https://github.com/OfficeDev/office-ui-fabric-react/issues/54

**Comment by notgiorgi** [comment]
#54

**Comment by dzearing** [comment]
@notgiorgi Just tried `TextField` and name attribute works fine. That was fixed a while ago.

http://codepen.io/dzearing/pen/ZBEVzw

`ChoiceGroup` and `Checkbox` are both screwing up the name attribute, which is a terrible oversight that we should fix ASAP. @mikewheaton or @micahgodbolt can one of you fix this so that we can use these components in forms?

**Comment by mikewheaton** [comment]
You can assign it to me, but I'm swamped at the moment so likely won't get to it until next week. Are you available any sooner @micahgodbolt?

**Comment by dzearing** [comment]
Or @leddie24

**Comment by dzearing** [comment]
@leddie24 did you already start on this? Jon can address this pretty quickly, can you take a look at the persona bleeding an outline one?

**Comment by dzearing** [comment]
This is now merged and will be published in this evening's build. Please let us know if you have any issues!

**Comment by notgiorgi** [comment]
Thanks for such a fast feedback and fix 🎉
