### ISSUE TITLE
Controlled Dropdown doesn't update state when selectedKey is undefined

### ISSUE THREAD

**Issue by isabelacmor** [OfficeDev/office-ui-fabric-react#8093]
### Please provide a reproduction of the bug in a codepen:
 https://codepen.io/isabelacmor/pen/bzXdEw
 
#### Actual behavior:
Setting Dropdown's selectedKey to undefined doesn't update the items selected in `selectedIndices`

#### Expected behavior:
`selectedIndices` is updated when selectedKey is undefined.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: High
 
Products/sites affected: All Dropdowns

#### Root cause:
setState is ignored when selectedKey is undefined.
(thanks to @brandonthomas for finding the root cause!)

```
if (newProps[selectedKeyProp] !== undefined && (newProps[selectedKeyProp] !== this.props[selectedKeyProp] || didOptionsChange)) {
this.setState({
selectedIndices: this._getSelectedIndexes(newProps.options, newProps[selectedKeyProp])
});
}
```
 
https://github.com/OfficeDev/office-ui-fabric-react/blob/867c9f9237ca6d802a7fb2e5401868dbff434988/packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx#L131

**Comment by aneeshack4** [comment]
@ecraig12345 is going to take a look at this since it's about controlled/uncontrolled behavior

**Comment by brandonthomas** [comment]
It looks like if we pass an empty array to selectedKey it works which seems odd. This is more of a dev experience bug at this point since we have a work around but it took us a while to sort out that it was possible.
