### ISSUE TITLE
Clearing PeopleList Items in single click

### ISSUE THREAD

**Issue by venk120soft** [OfficeDev/office-ui-fabric-react#8100]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Blocking, High, Normal, Low) 

Products/sites affected: (if applicable)

**Comment by prauveenn** [comment]
This might not be the correct way though!!

I got the similar requirement where I need to refresh the form content on data submit, for people picker control I am unable to do it.. But I have jQuery imported in my spfx webpart,,, I used the click function on people picker cancel icon to clear the control.. it served my purpose. luckily I don't have any other icon realted classes in that form.

code:  $(".ms-Button-icon").click();

**Comment by khmakoto** [comment]
@venk120soft, can you fill the issue template so that I can better understand this issue? Thanks!

**Comment by venk120soft** [comment]
@khmakoto , Its been a long time I've raised the issue.  I don't remember the details. seems I have used some work around for that by the time.

**Comment by khmakoto** [comment]
@venk120soft, sorry for the long wait in responding! Would you be fine with closing this issue then?

**Comment by venk120soft** [comment]
you can close it @khmakoto

**Comment by khmakoto** [comment]
Thanks @venk120soft!
