### ISSUE TITLE
Can't set maxWidth for DatePicker

### ISSUE THREAD

**Issue by jayleems2018** [OfficeDev/office-ui-fabric-react#8101]
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:
There is no way to adjust width of Datepicker.  I tried your sample under 
https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/office-ui-fabric-react/src/components/DatePicker/examples

It does not work.  It complains:
validation(css 4.0): "global" is not a valid pseudo-class

 

 
#### Expected behavior:
 Need to be able to override the adjust width of DatePicker to meet UI specs

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by leddie24** [comment]
Hi @jayleems2018  can you elaborate on which max width you're trying to change. Can you post a mockup of your intended changes in mind please?

**Comment by jayleems2018** [comment]
sure you can add following control to any DatePicker as
<label>Text box: </label>
          <input type = "text"
                 id = "myText"
                 value = "text here" size="65" />
My question is, could you adjust size for DatePicker to align with length of input field?

You can play with DatePicker on https://codepen.io/anders-sch-rmann/pen/omVbxK

**Comment by jayleems2018** [comment]
any input box as
<label>Text box: </label>
          <input type = "text"
                 id = "myText"
                 value = "text here" size="65" />

**Comment by jayleems2018** [comment]
you could find mine there: https://codepen.io/jayleems2018/pen/gEOEBm

**Comment by jayleems2018** [comment]
My input tag is added before DatePicker tag

**Comment by leddie24** [comment]
After looking at the suggested component usage, it doesn't seem like it's intended to be resized by design.

`Don't attempt to force resize the control in any way.`

@lorejoh12 can you confirm?

**Comment by jayleems2018** [comment]
To be clear, I don't know if user can resize DatePicker.  I think this is a bug and this is failed based on our design spec if it has to show a long length field by default, that forced to show a horizontal scrollbar in our case.  Please address.

**Comment by jayleems2018** [comment]
Finally, I figured out a working sample as on https://codepen.io/jayleems2018/pen/rROWxN.  Could you make DatePicker align with input field on right?

**Comment by leddie24** [comment]
Hi @jayleems2018, thanks for the reply.  I want to make sure we're on the same page; your codepen show a basic text `input` field above the `DatePicker` control that can be variable in width.  You want the `DatePicker` control to align with that text `input` and either grow or shrink in size (in conjunction) with the text `input` box correct?  Currently, with the DatePicker's usage guidelines, we generally recommend **not** modifying the width of the container or the picker itself, since the layout isn't designed to be resized dynamically.

That being said, it would be great to understand more about your UI spec and how/why the current DatePickerbehavior feels buggy and doesn't suit your projects needs.  Can you share more details about your UI spec; maybe we can find an interim solution.

**Comment by leddie24** [comment]
@jayleems2018 messaged me offline on Teams.  Here's the example of his UI usage:

![microsoftteams-image](https://user-images.githubusercontent.com/1291968/53903215-fcaa4500-3ff7-11e9-955e-53fa565cdf03.png)

@jayleems2018: I'm not experiencing that when I implement a `DatePicker` in a `Panel` on my end.  I just dropped `DatePicker` in the basic small right side example of `Panel` and it shrinks/grows to fit the `Panel` width.  

![image](https://user-images.githubusercontent.com/1291968/53903274-27949900-3ff8-11e9-9c55-815752ddaae5.png)


Do you have any custom CSS that may be overriding the `DatePicker` width?  Is there a repro site that you can share via Teams?
