### ISSUE TITLE
ScrollbarVisibility and isScrollSynced Properties Showing Error.

### ISSUE THREAD

**Issue by virender1164** [OfficeDev/office-ui-fabric-react#8105]
We are trying the to use the scrollablePane and sticcky components in a web part with SPFx 1.7.1. But we are not able to import the property ScrollbarVisibility in ScrollablePane and isScrollSynced property in Sticky is not working. The errors are as below.

'ScrollbarVisibility' is declared but its value is never read.ts(6133)
Module '"../../../../../../../SharePoint/WebPartName/node_modules/office-ui-fabric-react/lib/ScrollablePane"' has no exported member 'ScrollbarVisibility'.

**Comment by leddie24** [comment]
Hi @virender1164.  Is there a CodePen that you can share that can reproduce this error?  This sounds more like an issue with your dev environment rather than Fabric React; if we can reproduce this in a CodePen, I can help investigate the issue easier.  Thanks!
