### ISSUE TITLE
Improve design of aka.ms/fabricdemo

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#8106]
## Current design
From the [live site](http://aka.ms/fabricdemo):

![image](https://user-images.githubusercontent.com/1382445/53358297-c62c4600-38e4-11e9-962b-9a4eb615c22d.png)

## Proposed design
From the [CodeSandbox for a redesign](https://codesandbox.io/s/4zjmxxjkl4):

![image](https://user-images.githubusercontent.com/1382445/53357402-b14eb300-38e2-11e9-8da0-7c3a472b7e3a.png)

### Goals
* Emphasize the most common action for this page, which is to view a demo of the latest release.
* Increase the target size for each release for faster use.
* Give the version numbers more prominence as the most important piece of information.
* Basic visual polish (type, colors, shadows) to match the [PR deployed sites page](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/8099/merge/)

### Potential issues
* The list has less density than beforeand this results in more scrolling to find an old release.
  * Consider adding a filter for the releases to quickly locate one.
* The date is shown as a tooltip on hover. It seems like extra information to me; am I missing a scenario where locating a release by date is essential?
* We could do more to separate major, minor, and patch releases. For example, by using bold for the portion of the version number that has changed:  6.**96**.0, 6.**97**.0, 6.97.**1**
* The page is gray on gray on gray and, while functional, could use some personality.

**Comment by mikewheaton** [comment]
FYI @Jahnp and @ecraig12345

**Comment by ecraig12345** [comment]
> Consider adding a filter for the releases to quickly locate one.

I like this idea, and it shouldn't be very hard to implement.

> The date is shown as a tooltip on hover. It seems like extra information to me; am I missing a scenario where locating a release by date is essential?

I think it would be nice to have the date visible by default--maybe next to the release notes link?

**Comment by Jahnp** [comment]
This is awesome @mikewheaton ! Also flagging @cliffkoh for his feedback too.

My $0.02:
- Overall, this is a great improvement over the existing page. The improvements to the hit target size and alignment to the PR deployed sites page are nice.
- +1 to filtering releases!
- IMO the date could be considered essential. Sometimes I'll use this page when debugging to understand which releases came out during a particular time period.
Visualizing this could be straightforward:
![image](https://user-images.githubusercontent.com/307118/53358910-6767cc00-38e6-11e9-9baf-e44196e1c4b0.png)

For brevity, you could also just use the "Date" text with the "Release notes" link, though another date format might be better.
![image](https://user-images.githubusercontent.com/307118/53359351-8c107380-38e7-11e9-80b0-f883309acbec.png)

**Comment by ecraig12345** [comment]
Should have added, nice work! :)

**Comment by cliffkoh** [comment]
Great job. 

Only little request is if we can have a major version selector somewhere as well. Once we have version 7 (or if we back-publish Fabric 5), it would be great if the page doesn't show more than 1 major version (for performance reasons as well).

**Comment by cliffkoh** [comment]
Agree with @Jahnp on displaying the date. It is an important piece of the puzzle when troubleshooting/debugging :)

**Comment by mikewheaton** [comment]
Great idea, @Jahnp, I've added the date to the release note text. I'll look at adding a version filter and a way to quickly jump to a major release.

**Comment by ecraig12345** [comment]
Maybe pivots would be appropriate for separating out major releases?

**Comment by mikewheaton** [comment]
I've added a pivot to select the major version, and a filter for the releases:

![image](https://user-images.githubusercontent.com/1382445/53433381-21277100-39a9-11e9-9171-ee1332eb8e5e.png)

I'm not entirely convinced on the placement of the Pivot; maybe a Dropdown would work better there.

**Comment by mikewheaton** [comment]
I've assigned this to Peter and marked it as needing backlog review, so it can be determined who's going to implement this in the actual site. 😄

**Comment by KevinTCoughlin** [comment]
Excellent work @mikewheaton! Thank you 🙇

**Comment by cliffkoh** [comment]
Assigning to myself and @ecraig12345 (who previously volunteered).

**Comment by cliffkoh** [comment]
Done!
