### ISSUE TITLE
Persona: Textboy background bleeds through edges of photo

### ISSUE THREAD

**Issue by MLoughry** [OfficeDev/office-ui-fabric-react#812]
### Bug Report

- __Package version(s)__: 0.87.1
- __Browser and OS versions__: Chrome, Windows 10

#### Describe the issue:

The background color of the `Persona` textboy bleeds around the edges of the photo (if present). You can see this on the demo page.

#### Actual behavior:

Almost imperceptible border of red around the photo:

![image](https://cloud.githubusercontent.com/assets/20823465/21946677/55c4310c-d996-11e6-8a3d-2001e5be81a5.png)

#### Expected behavior:

The photo completely overlays the underlying initials and background.

**Comment by dzearing** [comment]
interesting, I think easy to fix by perhaps using a smaller circle or transparent bg color after photo loads. @leddie24 Perhaps you could help?

**Comment by dzearing** [comment]
or @MLoughry 

seems pretty simple.

**Comment by joschect** [comment]
@dzearing @MLoughry  Hi, I think that this is the same as https://github.com/OfficeDev/office-ui-fabric-react/issues/637 . I looked into it and from the css perspective it was not simple. The best solution would be to likely to have the transparent color set, or maybe even don't display the initial color sphere.

**Comment by MLoughry** [comment]
I concur with @joschect that it's hard to do with CSS from my investigation. I've opened a PR to do it programmatically, if that's acceptable.

**Comment by MLoughry** [comment]
This was resolved by #816
