### ISSUE TITLE
PropertyPaneCheckbox remains unchecked by default

### ISSUE THREAD

**Issue by RamaKaryam** [OfficeDev/office-ui-fabric-react#8121]
### Environment Information 
 
- __Package version(s)__: 1.7
- __Browser and OS versions__: IE11,Edge,Chrome; Windows 8.1, 10

### Please provide a reproduction of the bug in a codepen:
 
The below code doesn't render the checkbox in property pane as checked by default.
PropertyPaneCheckbox('Dashboard', {
                  text: 'Dashboard',
                  checked: true
                }),
 
#### Actual behavior:
 
The checkbox is unchecked even if i set 'checked:true' in the settings like above.
 
#### Expected behavior:
 
When we add the webpart to the page the first time, the above checkbox should be checked.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: High

**Comment by RamaKaryam** [comment]
I had to do this
https://techcommunity.microsoft.com/t5/SharePoint-Developer/PropertyPaneCheckbox-default-state-issue/td-p/75946

**Comment by leddie24** [comment]
Hi @RamaKaryam  can you elaborate on your issue? I don't believe we have a PropertyPaneCheckbox component in Fabric React.  If this is a fabric related issue, can you please submit a codepen demonstrating the issue at hand? Thank you!
