### ISSUE TITLE
CommandBar sometimes doesn't render in Safari12 Mojave MacOS

### ISSUE THREAD

**Issue by amyngu** [OfficeDev/office-ui-fabric-react#8123]
### Environment Information 
 
- __Package version(s)__: Not sure if this is _actually_ relevant, but OWA was using Fabric 6.103.1 the first time this was reported
- __Browser and OS versions__: (fill this out if relevant) All reported users have been using Safari 12 on Mojave macOS

#### Actual behavior:
 Unable to get a reliable repro, but users were reporting that components in OWA that use the CommandBar are not showing up.

When inspecting the elements in the DOM the CommandBar div is wrapped in `<div data-automation-id="visibleContent" style="position: fixed; visibility: hidden;">` (the invisible div that is used for command bar measurement calculation). The measurement phase doesn't seem to be finishing and the actual content doesn't render

Video of repro and DOM inspection: [outlook no buttons.mov](https://microsoft-my.sharepoint-df.com/:v:/p/mattcox/Ea_OW4PqI4tAsVEkCpDWjQoB9Gw9g-d-xJCpnytp_-eplw?e=CbIqmU)

Video of repro and refresh (CommandBar does not return on app refresh): [outlook no buttons refresh fail.mov](https://microsoft-my.sharepoint-df.com/:v:/p/mattcox/EYkRelzmXDpPjSGRBzGSD0UB9GMoBGi44YvF6bdIP5nXZw?e=1HhG82)

Snapshot of DOM inspection:
![image](https://user-images.githubusercontent.com/31973030/53445394-52ae3580-39c5-11e9-822d-4056fe6c5d16.png)

 
#### Expected behavior:
 CommandBar is visible

Link to OWA tracking bug [#40879](https://outlookweb.visualstudio.com/Outlook%20Web/_queries/edit/40879/?triage=true)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) High
 
Products/sites affected: (if applicable) OWA

**Comment by micahgodbolt** [comment]
Eddie if you can get our browserstack credentials, hopefully we can at least confirm this bug in the specific OS/browser combo. I'm not 100% sure if we'll be able to DO anything, but we can at least verify the bug in this browser release, and test in future releases.

**Comment by KevinTCoughlin** [comment]
Does the wrapper element have `visibility: hidden` applied in-line in the above screen-shot? How is it getting there?

**Comment by micahgodbolt** [comment]
yeah, it's hard coded in there. the resize group renders the UI twice....once to measure (always invisible), and once for the user to see.

**Comment by amyngu** [comment]
@micahgodbolt @leddie24 Is there and update on this? It's been a month with no traction.

**Comment by micahgodbolt** [comment]
Hey @amyngu, neither eddie or I were able to repro this issue with our out of the box command bar in Mojave/Safari. 

![image](https://user-images.githubusercontent.com/1434956/55503775-3aed5100-5604-11e9-88b5-ced9dd58377d.png)

Do you want to schedule some time to pair and take a look at your curent code? There are situations where command bar will colapse if a sibling element is greedily taking up space.

**Comment by micahgodbolt** [comment]
i see that your command bar is a flex item next to a 100% width element. This means that if the command bar shrinks, the parent will take up the extra space, which means that if you then make your window wider the command bar won't reappear because the sibling is taking up all of the space.  You might be able to resolve this with a flex-shrink:0 on the command bar. If this doesn't work, you can consider making the entire row a single command bar, and put the person/date information in a customized 1st item (therefore its included in the resize calculations)
