### ISSUE TITLE
PeoplePicker accessibility: In JAWS VC mode, focus gets stuck in text input field

### ISSUE THREAD

**Issue by denniscoh** [OfficeDev/office-ui-fabric-react#8132]
### Environment Information 
 
Win10 Enterprise
Chrome: 72.0.3626.109
JAWS 17.0.2729

### Please provide a reproduction of the bug in a codepen:

https://fabricweb.z5.web.core.windows.net/oufr/6.146.0/#/examples/PeoplePicker
 
1.  Launch Chrome and JAWS screenreader
1a.  Enable Virtual Cursor mode in JAWS
2.  Navigate to the PeoplePicker demo page
3.  Choose "Controlled Picker" people picker type
4.  Navigate to the text input combo box
5.  Hit enter to activate / set focus into the text input box
6.  Attempt to navigate to the PeoplePicker's items using up/down arrow keys

#### Actual behavior:
 
Focus is stuck inside the text input box

Not repro with JAWS VC mode disabled
Not repro with PeoplePicker using other modes

My guess is that the People Picker control is still activating some people list dropdown mode when the text input field gets focus, so the arrow key navigation gets stuck inside that hidden dropdown.
 
#### Expected behavior:
 
Focus should move to the picker items when hitting down arrow from the text input box

#### Priorities and help requested:
 
Requested priority:  Normal
 
Products/sites affected: (if applicable):  Microsoft Teams - Shifts Web app

**Comment by leddie24** [comment]
Hey @denniscoh  thanks for submitting this issue.  After doing some investigation, it looks like this is more of a JAWS specific issue rather than an issue with our control.  I will get in touch with a contact on the JAWS team to see if they can triage and fix this issue on their side.

**Comment by awalia13** [comment]
Logged Bug with JAWS Team.
