### ISSUE TITLE
ContextualMenu accessibility: In JAWS VC mode, focus drops out of the ContextualMenu when a SearchBox is included

### ISSUE THREAD

**Issue by denniscoh** [OfficeDev/office-ui-fabric-react#8133]
### Environment Information 
 
Win10 Enterprise
Chrome: 72.0.3626.109
JAWS 17.0.2729

### Please provide a reproduction of the bug in a codepen:
 
https://fabricweb.z5.web.core.windows.net/oufr/6.146.0/#/examples/contextmenu

* Launch Chrome and JAWS screenreader
  1a.  Enable Virtual Cursor mode in JAWS
* Navigate to the ContextualMenu demo page
* Use the ContextualMenu example with the SearchBox input box inside the menu:
"ContextualMenu with custom rendered menu list that renders a search box to filter menu items"
* Hit enter to launch the ContextualMenu
* Initial focus will be inside the text input box
* Attempt to navigate to the context menu's other items using up/down arrow keys

#### Actual behavior:

When trying to navigate inside the context menu in VC mode, focus drops out to the main page instead of navigating within the context menu.

- This appears to repro when a SearchBox is added as an IContextualMenuItem to the ContextualMenu component.
- Focus appears to work correctly with regular tab focus navigation, but not with VC mode.

#### Expected behavior:
 
Focus should stay within the context menu and move to the other context menu's items when hitting down arrow from the text input box

#### Priorities and help requested:
 
Requested priority: Normal

Products/sites affected: (if applicable): Microsoft Teams - Shifts Web app

**Comment by leddie24** [comment]
Hey @denniscoh thanks for submitting this issue. After doing some investigation, it looks like this is more of a JAWS specific issue rather than an issue with our control. I will get in touch with a contact on the JAWS team to see if they can triage and fix this issue on their side.

**Comment by awalia13** [comment]
Not Repro with Latest JAWS. So good to close.

**Comment by awalia13** [comment]
Revalidate the bug with Latest JAWS and foudn that it still repro. We have logged a JAWS bug.
