### ISSUE TITLE
[Accessibility] Focus is going out of the Calendar control while tabbing

### ISSUE THREAD

**Issue by skunani** [OfficeDev/office-ui-fabric-react#8136]
### Environment Information 
 
- __Package version(s)__: 6.129.0 
- __Browser and OS versions__: Windows 10, EDGE / Chrome

### Repro steps
 
1. Goto https://developer.microsoft.com/en-us/fabric#/components/datepicker 
2.Tab till first date picker under Default DatePicker
3.Verify focus order after expanding the calendar control while pressing Tab

#### Actual behavior:
 
While tabbing inside the calendar the focus is going outside. Focus move to URL in the addressbar
 
#### Expected behavior:
 
The focus should move within the calendar until selection is done.​

#### User Impact:
 
Keyboard only users will find difficult while working through the application, if there are focus order issues​

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? ( No)
 
Requested priority: (High) 
 
Products/sites affected: (if applicable)

**Comment by leddie24** [comment]
Hi @skunani, thanks for submitting this issue.  After talking with @JasonGore, it sounds like this is actually the ideal, intended behavior of `DatePicker`.  We don't want to prevent users for accessing browser functions (e.g: accessing the browser navigation bar), and doing so would be an accessibility issue).

**Comment by JasonGore** [comment]
This is also consistent with mouse clicking behavior. If a user clicks outside of the document (browser menus, browser footer/debugger) we don't want to grab focus from these elements.

**Comment by skunani** [comment]
This behavior is not consistant.
In the same page https://developer.microsoft.com/en-us/fabric#/components/datepicker
Tab to the "DatePicker with week numbers"
Here the focus is trapped on Date picker until the date is selected
Why there is a change in the behavior here.

**Comment by JasonGore** [comment]
@leddie24 It's true we should at least be consistent. I would treat this as a bug and settle on one way or another.

**Comment by leddie24** [comment]
@JasonGore, does your FocusZone refactor PR fix this issue? For our current component, it looks like simply commenting out the logic for `_lastTabbableChild` in `_onKeyboardHandler` (lines 190 - 192) fixes this issue and allows FocusTrapZone to escape and visit the nav bar, but your PR looks like it's removing that whole code block entirely.

**Comment by JasonGore** [comment]
I think it does, actually. [Here is the new DatePicker](http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/8216/merge/fabric-website-resources/dist/index.html#/examples/datepicker) based on my changes in #8216. It seems to behave more correctly than the master version of the same page.

**Comment by JasonGore** [comment]
@skunani If you see any problems with the link I provided in the previous post, please let us know. I'll mark #8216 as fixing this issue for now.

**Comment by leddie24** [comment]
Ok gotcha, here's a video of it in action.  It seems to keep the focus in the DatePicker to be consistent with the other variants.

https://streamable.com/zc06v

However, this does prevent the user from accessing the URL/browser functions as mentioned before.

**Comment by skunani** [comment]
@JasonGore 

> @skunani If you see any problems with the link I provided in the previous post, please let us know. I'll mark #8216 as fixing this issue for now.

The behavior is consistant here. Thank you for fixing this
