### ISSUE TITLE
Nav selection is broken when using url fragment identifier

### ISSUE THREAD

**Issue by michaelmaillot** [OfficeDev/office-ui-fabric-react#8137]
### Environment Information 
 
- __Package version(s)__: 5.134.0

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/anon/pen/MxwmeW
 
#### Actual behavior:
 
Selection is broken when still in the same page but using url property in NavLink with fragment identifiers. When clicking on a NavLink, then on another one, the previous is still selected.
 
#### Expected behavior:
 
Selection must be functional when clicking on the different NavLink items (according to me 🙂).

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: (Low) 
 
Products/sites affected: (if applicable)

**Comment by leddie24** [comment]
Hmm this bug is weird.  I can see the repro on your Codepen, but it's difficult to debug the issue by trying to repro in localhost documentation, since using your code verbatim will actually cause a redirect instead of staying on the same page.  I tried using the following code below, but it doesn't seem to repro for me on localhost documentation.

@micahgodbolt do you have any suggestions on how to approach this issue?


```
<Nav groups={[{
          links: [
            {
              key: 'ActivityItem',
              name: 'ActivityItem',
              url: '#/examples/nav?test1'
            },
            {
              key: 'Breadcrumb',
              name: 'Breadcrumb',
              url: '#/examples/nav?test2'
            },
            {
              key: 'Button',
              name: 'Button',
              url: '#/examples/nav?test3'
            }
          ],
          name: 'Basic components'
        }]} />
```

**Comment by micahgodbolt** [comment]
it appears that state gets updated when clicking on a nav item, but the previously selected item still seems to have the original styles. new styles aren't getting calculated in this case?

**Comment by leddie24** [comment]
From investigating, I think `location.href` isn't updated at the same time (it still thinks the page is on the old URL) as state, which results in showing 2 items as being selected.  I think the proper fix here is to only check `location.href` if `this.state.selectedKey` is `undefined`, unless you have another suggestion? I'll create a PR soon.
