### ISSUE TITLE
TooltipHost position is wrong when wrapped component uses absolute position

### ISSUE THREAD

**Issue by yajiex** [OfficeDev/office-ui-fabric-react#8149]
Here is the repro link: https://codepen.io/anon/pen/QojjBd. There is a button and wrapped with `TooltipHost`, the button's `position` is `absolute`. When hovering on the button, the tooltip shows at wrong position.

### Environment Information 
 
- __Package version(s)__: latest version (not specified)
- __Browser and OS versions__: any browser

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/anon/pen/QojjBd
 
#### Actual behavior:
 
Tooltip's position is wrong.
 
#### Expected behavior:
 
Tooltip should be near the button.

#### Priorities and help requested:
 
 
Requested priority: Blocking

**Comment by leddie24** [comment]
Hi @yajiex, thanks for submitting this issue.  After digging around on the component and getting some assistance from @joschect on this, you can fix this issue by adding an `id` to the button (or whatever you're positioning absolute), and then adding that ID as a `target` in the `calloutProps` of `TooltipHost`.

See codepen here:

https://codepen.io/leddie24/pen/NJxWJN

**Comment by yajiex** [comment]
Thanks, the workaround looks good to me. Do you think it's a bug or by design?

**Comment by leddie24** [comment]
Hey @yajiex , sorry for the bot closing this issue prematurely.  This is certainly not an issue, and seems more like a bug.  However, with the workaround in place, I don't think it's something worth pursuing to fix when there are easy fixes.  We can update the documentation in the future to showcase this scenario.

**Comment by yajiex** [comment]
Thanks, updating the doc sounds good!
