### ISSUE TITLE
Removal of @uifabric/utilities/lib/dom.js breaks AMD imports

### ISSUE THREAD

**Issue by ThomasMichon** [OfficeDev/office-ui-fabric-react#8165]
It looks like the recent version of `@uifabric/utilities` removed `dom.ts` and replaced it with `dom/index.ts`. This is a breaking change because AMD imports do not automatically resolve `dom` to `dom/index`.

A proxy `dom.ts` still must exist for compatibility with existing consumers.

The break was caused by #8032.

**Comment by leddie24** [comment]
@dzearing, I'm not sure how to approach/fix this issue, it looks like it was caused by your PR #8032.  Is this something you want to fix, or can you connect offline to help walk me through this issue?

**Comment by dzearing** [comment]
This was already resolved, as dom.js was added here:

https://github.com/OfficeDev/office-ui-fabric-react/releases/tag/%40uifabric%2Futilities_v6.30.0
