### ISSUE TITLE
ContextualMenu's onMenuClose should check is _isFocusingPreviousElement before setting focus to last active element

### ISSUE THREAD

**Issue by makopch-ms** [OfficeDev/office-ui-fabric-react#8170]
### Environment Information 
 
- __Package version(s)__: latest
- __Browser and OS versions__: all

### Please provide a reproduction of the bug in a codepen:
1. Have contextual menu w/ hidden prop
2. Click on another piece of UI to cause CalloutContentBase.prototype._dismissOnLostFocus to run
3. ComponentWillUpdate runs causing ContextualMenu's onMenuClosed to be run
4. onMenuClosed should check for this._previousActiveElement && _isFocusingPreviousElement when setting focus to the last active element.
 
#### Actual behavior:
 
On Clicks, _previousActiveElement.Focus() can run after, another components sets focus, putting it in the wrong spot
 
#### Expected behavior:
 
We don't call _previousActiveElement.Focus() for clicks.  In ContextualMenu.Base.tsx, the decision when to set focus during unmounting is also gated by _isFocusingPreviousElement , which is only updated on keyboard actions.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal
 
Products/sites affected: Office

**Comment by aftab-hassan** [comment]
The fix would be similar to what we have [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/5d90f5a63f57ff69cd13f5ccae4cc37d34228479/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.base.tsx#L183) 
@makopch-ms would like to contribute a fix for this. Please reach out, if we can help.

**Comment by KevinTCoughlin** [comment]
@makopch-ms, I wonder if this is related at all to https://github.com/OfficeDev/office-ui-fabric-react/issues/8261. Note that only occurs in non-WebKit browsers...

**Comment by aftab-hassan** [comment]
Discussed offline. @makopch-ms is aware of the fix and working on it. Will reach out if there are any questions.
