### ISSUE TITLE
Combo-box placeholder not displaying

### ISSUE THREAD

**Issue by joshburnssp** [OfficeDev/office-ui-fabric-react#8176]
#### Describe the issue:

Using a combo-box and want to set a placeholder within the dropdown box, seen the code on the Fabric UI site. When setting the placeholder property, it doesn't display anything. I have tried setting the placeholder in the code and also via properties and in the property pane

#### Actual behavior:

`  <ComboBox
          allowFreeform
          autoComplete="on"
          placeholder="Select an office"
          onChanged={this.changeState}
          options={this.state.OfficelistData}
        ></ComboBox>`

![image](https://user-images.githubusercontent.com/30901352/53741475-660e4480-3e8e-11e9-87a2-68cbbbefd34e.png)

![image](https://user-images.githubusercontent.com/30901352/53741500-72929d00-3e8e-11e9-8d96-bc6ae2a5bf4a.png)

#### Expected behavior:

[https://developer.microsoft.com/en-us/fabric#/components/ComboBox](url)

Want to get the ComboBox with placeholder text

![image](https://user-images.githubusercontent.com/30901352/53741458-5bec4600-3e8e-11e9-848e-c1b6d044c21a.png)

**Comment by aftab-hassan** [comment]
@joshburnssp Is this behavior you are expecting to see?
![image](https://user-images.githubusercontent.com/8922176/53757599-ee7dec80-3e70-11e9-8424-0749ec3fb9c1.png)


Here is a codepen
https://codepen.io/aftab-hassan/pen/Mxjjvj

Please confirm and we'll take it from there.

**Comment by joshburnssp** [comment]
That is what i am expecting to see.

I am seeing nothing though :(

**Comment by aftab-hassan** [comment]
> That is what i am expecting to see.
> 
> I am seeing nothing though :(

@joshburnssp Could you please take a look at this codepen which sets a placeholder.
https://codepen.io/aftab-hassan/pen/Mxjjvj

If the scenario that does not work for you is different, would you be able to provide us a codepen that captures the issue? That would help us understand better and get back. Look forward to helping fix this.

**Comment by joshburnssp** [comment]
Here is a [codepen](https://codepen.io/joshburnssp/pen/vPgOGv), can't get it too work on there either...

am i doing something wrong?

**Comment by aftab-hassan** [comment]
@joshburnssp 

Looks like `React` was not defined in your codepen. By adding `React` to your codepen, I am able to get the place holder text, and the options you expect to see.

Please take a look at this updated `codepen` (code is same as the one you shared, with React added)

https://codepen.io/aftab-hassan/pen/pYdLJG

<img width="956" alt="combobox-placeholder" src="https://user-images.githubusercontent.com/8922176/54245111-c3d50900-44ec-11e9-85c8-50e2cf99d7a0.PNG">
