### ISSUE TITLE
Update browser support documentation

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#818]
The [browser support documentation](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/ghdocs/BROWSERSUPPORT.md) here in the GitHub repo shows that we support IE10. Now that 🎉  SharePoint Online is dropping IE10 support 🎉 , I'm assuming we can do the same in Fabric?

Also, is it really just Firefox where we support the last major release? I thought we supported the two most recent major releases of each browser.

**Comment by dzearing** [comment]
@mikewheaton yes IE11 should be minbar. We use flexbox and IE10 may have issues.
