### ISSUE TITLE
Foundation: PureComponent / React.memo

### ISSUE THREAD

**Issue by JasonGore** [OfficeDev/office-ui-fabric-react#8182]
Add opt-in PureComponent support via IComponentOptions boolean. This feature should wrap component in PureComponent and provide optimizations to short-circuit as much code as possible while ensuring changes to theme, style and context props still propagate.

As a possible alternative to PureComponent and shouldComponentUpdate, also investigate use of React.memo.

**Comment by KevinTCoughlin** [comment]
cc: @ThomasMichon who may be interested in tracking this work :)

**Comment by khmakoto** [comment]
Closing due to newer efforts that'll address this issue.
