### ISSUE TITLE
Tree shaked theme

### ISSUE THREAD

**Issue by bengry** [OfficeDev/office-ui-fabric-react#8193]
### Environment Information 
 
- __Package version(s)__: 6.148.1
- __Browser and OS versions__: Chrome 72, macOS (irrelevant - happens in other environments too).

### Please provide a reproduction of the bug:

1. Clone this repo: https://github.com/Microsoft/angular-react
2. `git checkout fabric/upgrade-office-ui-fabric-react`
3. `npm install`
4. `ng serve demo --prod`

You'll see an error in the console at runtime about a missing prop on the `Checkbox` component:
![image](https://user-images.githubusercontent.com/260431/53806570-f6638c80-3f55-11e9-82a5-62eafdb79981.png)
 
We see similar errors with other components for `theme` etc. basically anything that I'd expected calling `styled()` to fill in.

#### Expected behavior:

No error at runtime, components behave as expected and get injected the `theme`.

#### More info & background:
I am the main maintainer of [`@angular-react`](https://github.com/Microsoft/angular-react) - a library that lets you use React components inside Angular (2+) applications. The main implementation of which is built upon `office-ui-fabric-react` and is being used in several applications both within and outside Microsoft.

In one of the latest versions `office-ui-fabric-react` (or rather, one of its dependencies) broke things for us when using Angular's AOT build (basically a wrapper over Webpack's tree shaking, with some more stuff being optimized - mainly component templates etc.). in JIT mode everything works fine, but the final bundle is bigger and heavier on the enduser (some of the compilation happens at runtime instead of build time).

We were able to make things work again by locking `@uifabric/styling` to version `6.42.0` (we're using `office-ui-fabric-react@6.110.0` at the moment, but the same happens with newer versions of it).

What's going on probably is that the AOT build is tree-shaking away something that sets props on components, but we couldn't pinpoint what exactly is - I was hoping you could help pinpoint exactly what was changed in recent version(s) of `@uifabric/styling` or its dependencies in order for us to debug it further and see how to prevent it from happening.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) Yes
 
Requested priority: (Blocking, High, Normal, Low) High
 
Products/sites affected: (if applicable) WDATP

**Comment by dzearing** [comment]
Looking at this. We made a change in the `@uifabric/styling` package to turn sideEffects to an allow list. I'm assuming this is the root cause, but the real question is why... why are there things which are being shaken out that you didn't expect? It implies that nothing referenced those exports, which we need to trace through. If there is an implicit dependency here (side effect), we need to add those files to the side effects list in the package.json.

**Comment by dzearing** [comment]
Hey @bengry I want to make sure I'm fixing your bug. I am pretty sure this is related to `/styles/theme.js` not being included in the side-effects list, where it need to register a default theme for things to consume. I am adding that right now but want to make sure I repro your scenario so there isn't something else we're missing.

**Comment by bengry** [comment]
Looks good in my repro with the new version. @dzearing thanks for the quick turnaround!
