### ISSUE TITLE
Single vs double quotes for jsx attributes

### ISSUE THREAD

**Issue by kmees** [OfficeDev/office-ui-fabric-react#82]
Is there a reason that jsx attributes use single quote marks? I haven't seen any other React library that does it that way (and it looks weird :)). Guess that is also a problem of coding conventions vs HTML conventions?

The [tslint rule](http://palantir.github.io/tslint/rules/quotemark/) supports different rules for jsx attributes and string literals.

**Comment by dzearing** [comment]
We just care about being consistent. There are nits with rules and various people will have strong different opinions on.

Primarily we are trying to stay consistent in the code throughout: use single quotes, or back tick, unless absolutely required to use double quotes (json files). It's good to know there is a lint rule to special case it for JSX content.

There are a few rules we've stuck with. We also include spaces inside of the curly brackets for props, this has also come up being a little inconsistent from other projects. The reasoning is that it's consistent then with other situations like destructuring or imports, where we include spaces in between the brackets and same-line content within.

**Comment by kmees** [comment]
Fair enough, also as it doesn't leak into the public api it doesn't really matter. It's just that muscle memory is a bitch :D
