### ISSUE TITLE
ChoiceGroup: Add checkedKey prop

### ISSUE THREAD

**Issue by fantua** [OfficeDev/office-ui-fabric-react#820]
### Bug Report

- __Package version(s)__: 0.88

#### Describe the issue:

For ChoiceGroup there is no prop **checkedKey**(value) to control his state with onChanged. 

#### Expected behavior:

Add checkedKey prop as in [Dropdown](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.Props.ts#L22) component.

**Comment by leddie24** [comment]
Hey @dzearing @fantua, can you clarify on what the ask is here?  In IChoiceGroupOption and IDropdownOption there is a checked/selected prop; should checkedKey take precedence over the checked/selected prop for the component?  What's the purpose of having a checked/selected prop for options if the parent component specifies what is selected/checked?

**Comment by fantua** [comment]
@leddie24, IDropdownProps has selectedKey and defaultSelectedKey, for IChoiceGroupProps the same needed.

**Comment by fantua** [comment]
Also, will be good to add **required** prop to the [input](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroup.tsx#L79).

**Comment by micahgodbolt** [comment]
@fantua i merged in the 'required' input. does that close this issue or is there still more to do?

**Comment by fantua** [comment]
@micahgodbolt still need checkedKey prop. Maybe I'll create PR for that.

**Comment by fantua** [comment]
Implemented in #1364. Thanks to @dzearing
