### ISSUE TITLE
Update deprecation maps for all components

### ISSUE THREAD

**Issue by mikewheaton** [OfficeDev/office-ui-fabric-react#821]
@cschleiden made a [suggestion](https://github.com/OfficeDev/office-ui-fabric-react/pull/817#discussion_r96130956) while reviewing a PR that we should log a console warning when deprecated props are used:

> General question about deprecation: should we log a console warning if this is used? Otherwise existing consumers might not know that this is being deprecated (not everyone reads release notes...) and their sites will just break once removed.
>
> Ideally this would only be done in a non-minified/debug build, not sure how that would work when people bundle themselves.

We haven't discussed quite when we're going to go ahead and delete all of the deprecated functionality, but when we do we'll want to be sure that developers have had plenty of warning.

**Comment by mikewheaton** [comment]
Turns out we already have this. @dzearing is going to update the [best practices documentation](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/ghdocs/BESTPRACTICES.md) and then we can assign this to someone (I'll likely be able to do it) to go through and make sure we have warnings for all deprecated properties.

**Comment by cschleiden** [comment]
Sounds good. I'll also have a look at how it's implemented.On Jan 15, 2017 15:17, Mike Wheaton <notifications@github.com> wrote:Turns out we already have this. @dzearing is going to update the best practices documentation and then we can assign this to someone (I'll likely be able to do it) to go through and make sure we have warnings for all deprecated properties.

**Comment by mikewheaton** [comment]
@cschleiden Do we want to close this? I was thinking we should go through the components and make sure we're deprecating them consistently and with a console warning.

**Comment by cschleiden** [comment]
@mikewheaton k, changed the title. I thought since we discovered that deprecation map functionality this was obsolete.

**Comment by dzearing** [comment]
If there are specific things missing a deprecation map that can be fixed, please reopen and provide a list.

Not all deprecation scenarios can be fixed, but it would be good to just fix anything specific we missed.
