### ISSUE TITLE
[Accessibility] Dropdown with custom list rendering incorrectly sets aria-activedescendant

### ISSUE THREAD

**Issue by preetriti1** [OfficeDev/office-ui-fabric-react#8211]
### Environment Information 
 
- __Package version(s)__: 6.151.0
- __Browser and OS versions__: Windows 10, Chrome - 72.0.3

### Please provide a reproduction of the bug in a codepen:
 https://codepen.io/preetriti1/pen/bZByQB

#### Actual behavior:
![image](https://user-images.githubusercontent.com/48265693/53862537-8d533780-3f9c-11e9-9a44-c418e688af2b.png)
aria-activedescendant is incorrectly set for the dropdown when onRenderList is passed into the props.
 
#### Expected behavior:
 
 Aria-activedescendent should only be set when options rendering inside listbox is initiated by the fabric component. When custom rendering is passed in for onRenderList, aria-activedescendant should not be set since its value is dynamically calculated by component.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: Azure LogicApps accessibility

**Comment by KevinTCoughlin** [comment]
@preetriti1 is this because of ID mismatch when custom rendering is used?
