### ISSUE TITLE
All ContextualMenu samples rely on the Button component.

### ISSUE THREAD

**Issue by redoz** [OfficeDev/office-ui-fabric-react#8212]
It would be nice to have some samples on how to use the  `ContextualMenu` outside the context of a `Button`.

**Comment by KevinTCoughlin** [comment]
@redoz what are your thoughts regarding this ask: https://github.com/OfficeDev/office-ui-fabric-react/issues/7162 as a solution to the above?

**Comment by redoz** [comment]
@KevinTCoughlin Yeah that's what I was trying to do, I figured it out after a bit of poking around, and I opened this issue because I thought it would've been nice to have a sample of using the ContextualMenu as an actual context menu. It would've saved me a few minutes of tinkering at least. Feel free to close this as a duplicate if you want.

**Comment by KevinTCoughlin** [comment]
@aftab-hassan, let's close as dupe and tackle via https://github.com/OfficeDev/office-ui-fabric-react/issues/7162 soonish, hopefully this week. I have another example for SearchBox to add.
