### ISSUE TITLE
FocusZone doesn't focus correctly with callouts/ListPeoplePickers with lots of items

### ISSUE THREAD

**Issue by Xander667** [OfficeDev/office-ui-fabric-react#8215]
<!--  
Thanks for contacting us! We're here to help.

Before you report an issue, check if it's been reported before:

  * Search: https://github.com/OfficeDev/office-ui-fabric-react/search?type=Issues
  * Search by area or component: https://github.com/OfficeDev/office-ui-fabric-react/issues/labels
  
Please provide a reproduction of the bug in a codepen, if possible. Here’s how:
I struggled getting the code working in the codepen with the ListPeoplePickerBase.

I'll share the simplest repro I could create in my codebase:
<div>
                            <Callout
                                className="share-roadmap-callout"
                                directionalHintFixed={true}
                                setInitialFocus={false}
                                target={this.shareIconRef}
                                alignTargetEdge={true}
                            >
                                <FocusTrapZone isClickableOutsideFocusTrap={true}>
                                    {
                                        <div className="member-picker">
                                            <ListPeoplePickerBase
                                                ref={this.resolveRef(this, "testPicker2")}
                                                selectedItems={peeps}
                                                onResolveSuggestions={this.onFilterChanged}
                                            />
                                        </div>
                                    }
                                </FocusTrapZone>
                            </Callout>
                        </div>

### Environment Information 
 
- __Package version(s)__: 6.132 (I tried the latest hotfix branch too but no luck)
- __Browser and OS versions__: Win 10 and Chrome/Edge probably all

### Please provide a reproduction of the bug in a codepen:
In our app we have places where we have callouts with focuszone and then pickers inside. We found the bug that in one of the pickers if it has 11 or more items, the focusing doesn't work. 
I have some gifs I can share, basically as I tab into the list items, the next tab jumps me out to the browser nav bar.

I made a simpler repro than in our app with the same three components which is listed above, in that repro the focus didn't work even with 5-6 items in the list.

#### Actual behavior:
I can focus into the list but then lose focus after than by it going to the nav bar
 
#### Expected behavior:
 I have a focus loop within the focus zone and the focus flicks between the few points in the loop, instead it jumps out of the loop.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (High) - It definitely doesn't block the scenario, as if our case if the user interacts when in the list items, the focus loop is maintained, or if they backtrack from the beginning once it works fine as well. Also when they are redirected out, they can find themselves again and correct themselves - so we didn't mark this as blocking accessibility bug in our triage.
 
Products/sites affected: MS Project

**Comment by aftab-hassan** [comment]
@Xander667 could you please provide a codepen for this, or update the description with details of the issue?
