### ISSUE TITLE
Enable option to continue showing beak when Coachmark is expanded

### ISSUE THREAD

**Issue by orokanasaru** [OfficeDev/office-ui-fabric-react#8221]
**Describe the feature that you would like added**

We're using a Coachmark with TeachingBubbleContent, but our designers want to keep showing the beak when the teaching bubble expands. As of #6158, the beak is only rendered when collapsed. There should be an option for this behavior.

**What component or utility would this be added to**

Coachmark

**Have you discussed this feature with our team, and if so, who**

From Vitalie Braga, "This is actually something that needs to be fixed in the default behavior because the design redlines are leaving the beak in place after expansion. So feel free to file an issue on Github and the Shield engineer will take care of it)))"

**Additional context/screenshots**

**Comment by aftab-hassan** [comment]
@kenotron @micahgodbolt The [PR](https://github.com/OfficeDev/office-ui-fabric-react/pull/6158) linked to, above, adds an `isCollapsed` check for showing the beak.

The requested behavior here, is to have the beak as an option, so as to keep showing it, even when expanded. What is the behavior we would like to go with? Would like to get your thoughts.

**Comment by micahgodbolt** [comment]
beak visibility is a prop setting. so we probably just need to make sure that this prop is accessible from the coachmark.

**Comment by KevinTCoughlin** [comment]
Yea, we should add this as a prop. Shouldn't be too difficult. If we're conditionally rendering it currently then we can't provide styling as a workaround.

**Comment by micahgodbolt** [comment]
Oh hah....It looks like Coachmark has a custom beak because it's not actually using a callout. This should just be a prop added to Coachmark. 

@orokanasaru can you provide a screenshot of the finished design you're shooting for. I want to make sure we make the correct change.

**Comment by AndrewCraswell** [comment]
Is this still under consideration? I'd like to use the functionality too. It was confusing to me reading the documentation that a Coachmark contains a TeachignBubble inside, and while TeachingBubbles have a beak after opening, the Coachingmark does not.

**Comment by micahgodbolt** [comment]
Michael send over a design and yeah....now that I see it, I wonder why they decided to omit the beak.

**Comment by micahgodbolt** [comment]
The beak only shows in collapsed mode because of this condition.


![image](https://user-images.githubusercontent.com/1434956/54954020-e7457e00-4f06-11e9-91ed-31ce0bd8b5ae.png)

If you remove that, you get this

![coach](https://user-images.githubusercontent.com/1434956/54953979-c8df8280-4f06-11e9-8a40-5dd70cddd3f4.gif)

So it wouldn't be hard to turn that test on and off via a prop. @aftab-hassan, does that work for you? Certainly add some visul tests for this as well.
