### ISSUE TITLE
Floating Picker Suggestion Header ClassName Props

### ISSUE THREAD

**Issue by YuningB** [OfficeDev/office-ui-fabric-react#8223]
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)
 @Adjective-Object 
This is a bug I discussed with Max offline. The className prop is not pass to SuggestionsHeaderFooterItem.

**Comment by Adjective-Object** [comment]
The details are:
When className is passed to SuggestionsHeaderFooterItem, it does not render with that className on the suggestion headerfooter div.

See 
https://github.com/OfficeDev/office-ui-fabric-react/blob/3551e64e93e56e7df1488041b7695ab75a97ebc5/packages/office-ui-fabric-react/src/components/FloatingPicker/Suggestions/SuggestionsControl.tsx#L29-L48
