### ISSUE TITLE
Accessibility blocker: Calendar control: Tabbing inside control unexpectedly tabs to top of page

### ISSUE THREAD

**Issue by lukehumphrey** [OfficeDev/office-ui-fabric-react#8225]
This bug is preventing Project from passing a PWD usability test and has been identified as a MAS bug.

repro:
Use Edge 
Open calendar control with month picker shown.
Tab 7 times inside control

Expected: Tab cycles inside control.
Actual: Tab reset to the browser address bar. Shift+tab does not exhibit this behavior (works as expected). Only forward tabs are broken here.

Can this be fixed in the short-term?
Contact PM lukehum@microsoft.com for more qs.

**Comment by aftab-hassan** [comment]
@lukehumphrey thanks for reporting. Able to see this bug.

**Comment by JasonGore** [comment]
This is a possible duplicate of #8134 which has been resolved.

**Comment by aftab-hassan** [comment]
@lukehumphrey As @JasonGore's mentions, this was fixed.

Here is a video of it action while @leddie24 was reviewing it
https://streamable.com/zc06v

Thanks for letting us know @JasonGore
