### ISSUE TITLE
Floating Picker Suggestions List Width

### ISSUE THREAD

**Issue by YuningB** [OfficeDev/office-ui-fabric-react#8231]
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)
@Adjective-Object 
The floating picker suggestion list width is set to 300px instead of take the same width of callout; so when a customized calloutWidth is set, the picker will look like:  
![image](https://user-images.githubusercontent.com/48068901/53925233-08b3f800-4034-11e9-8868-10ef6a973211.png)

**Comment by aftab-hassan** [comment]
@YuningB @Adjective-Object could you provide a codepen where you can duplicate the issue.

Looking at the issue description, this is what I see when I try to reproduce.
![floating-people-picker](https://user-images.githubusercontent.com/8922176/54380168-12e38100-4648-11e9-8303-0c4c65abc7c6.PNG)

**Comment by Adjective-Object** [comment]
@YuningB as the reporter

**Comment by YuningB** [comment]
I'm a little bit confused... Please refer to the fabric code [here](https://github.com/OfficeDev/office-ui-fabric-react/blob/8a471edeec02db18f201db9790da374c573f9f2b/packages/office-ui-fabric-react/src/components/FloatingPicker/BaseFloatingPicker.tsx#L154) and I think this is the place where set the suggestion list width to 300px in[ .scss file](https://github.com/OfficeDev/office-ui-fabric-react/blob/8a471edeec02db18f201db9790da374c573f9f2b/packages/office-ui-fabric-react/src/components/FloatingPicker/BaseFloatingPicker.scss), and not able to take customized className, no matter what the calloutWidth prop value is. Not sure how we're able to change in the people picker.

**Comment by micahgodbolt** [comment]
we could probably change this to min width to resolve this issue quickly. This component is in need of conversion to css-in-js as well, which would make it easier to set that value without resorting to using CSS.

**Comment by micahgodbolt** [comment]
![image](https://user-images.githubusercontent.com/1434956/54787701-d389d700-4be9-11e9-8098-5749d66cc4f0.png)
 (hard code the callout to be 500px and you can see that this style restrics the width of the suggestions

![image](https://user-images.githubusercontent.com/1434956/54787735-f0260f00-4be9-11e9-811d-f06ab7e98a35.png)

**Comment by YuningB** [comment]
@micahgodbolt Agreed. I was wondering if we can have a minWidth as 300px and width as 100%.

**Comment by micahgodbolt** [comment]
if it's already display block it shouldn't need a width value.
