### ISSUE TITLE
Logging 4 chars when mask is "999" on MaskedTextField

### ISSUE THREAD

**Issue by HeinPauwelyn** [OfficeDev/office-ui-fabric-react#8236]
## Environment Information 
 
- __Package version(s)__: `@microsoft/sp-office-ui-fabric-core` = 1.7.1
- __Browser and OS versions__: not relevant

## Actual behavior
 
I've created a masked text field using the mask `999`, because I'll have maximal 3 numbers. The problem that I've is when the user enters 4 numbers by mistake _(eg. 1234)_, the console logs `"1234"`. That are 4 numbers instead of maximal 3.

See [this code pen](https://codepen.io/HPawelyn/pen/qvrodQ?editors=1011) and image below for the strange behavior.
 
![image](https://user-images.githubusercontent.com/16222780/53963202-18434780-40ed-11e9-979e-f35db52269da.png)

By every change it logs the change two times. First with 3 chars, a second time with 4 chars. I think this last is wrong.

## Expected behavior

Logging `"123"` just one when entering 1234.

## Priorities and help requested
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal

**Comment by aftab-hassan** [comment]
@HeinPauwelyn thanks for the codepen. Tagging as `bug`.

**Comment by dzearing** [comment]
This should be fixed. `onChange` should be used as `onChanged` should be deprecated.

But the behavior there is the same as reported. The `onChange` event should only fire if the value is actually intended to be changed; not in the case where we intend to keep it the same.

**Comment by xugao** [comment]
the issue doesn't repro with latest Fabric, see [this codepen](https://codepen.io/xugao/pen/qBdOJKR). closing down this issue
