### ISSUE TITLE
Adding icon support for Dialog title

### ISSUE THREAD

**Issue by YaokaiYang-assaultmaster** [OfficeDev/office-ui-fabric-react#8238]
**Describe the feature that you would like added**

For now the `Dialog`'s title can only be string. Can we support adding `Icon` to a title?

**What component or utility would this be added to**

`dialogContentProps.title` of `Dialog`

**Have you discussed this feature with our team, and if so, who**
Not yet

**Additional context/screenshots**

Like this:
![image](https://user-images.githubusercontent.com/18135477/53982480-e5d42300-40c9-11e9-8189-215c16a82116.png)

**Comment by dzearing** [comment]
@aftab-hassan this is related to Dialog, not Icon.

**Comment by dzearing** [comment]
We are looking at converting to use a slots pattern, which we could then consider this for the title slot. Every slot in a composite component should take in jsx.

@JasonGore for heads up.

**Comment by tedfordtf** [comment]
It would be very beneficial for our team (Power platform) too. It provides contextual feedback and it also allows our users to feel a sense of accomplishment of fulfilling a task done in a dialog

**Comment by ravikiranr26** [comment]
Seems like i too had a same requirement, to show the Icon in title.

**Comment by dzearing** [comment]
By just changing the type to also allow JSX, this should enable your scenario.

**Comment by agg23** [comment]
I would say #8405 only partially addresses this scenario, as the parent element for the title is `<p>`. This prevents adding children such as `<div>`, which removes some of the usefulness.
