### ISSUE TITLE
Publish CDN for fabric-react and codepen template.

### ISSUE THREAD

**Issue by lijunle** [OfficeDev/office-ui-fabric-react#825]
I am trying to repro a bug with codepe.

However, I don't find the CDN location for fabric-react. A better solution is provide a simple fabric-react hello world to get start. [Here](https://facebook.github.io/react/docs/installation.html#trying-out-react) is how React works.

**Comment by dzearing** [comment]
@mikewheaton or @battletoilet Can we add a section in the official site about CDN locations or at least a link to an official codepen?

**Comment by dzearing** [comment]
@lijunle you can look here:

http://codepen.io/dzearing/pens/public/?grid_type=list

**Comment by mikewheaton** [comment]
The [get started page](http://dev.office.com/fabric#/get-started#react) has this:

![image](https://cloud.githubusercontent.com/assets/1382445/21994362/3a8206ae-dbd4-11e6-8e29-dd7b95f0e917.png)

That would be a good spot to mention that it's available via CDN, with a CodePen link to demonstrate how that can be used.

**Comment by notgiorgi** [comment]
I use [unpkg](https://unpkg.com/office-ui-fabric-react@0.88.0/dist/) for my jsbins/pens

**Comment by dzearing** [comment]
@notgiorgi This is awesome, never saw this! thanks!

**Comment by dzearing** [comment]
@mikewheaton how about switching the docs to use unpkg

**Comment by mikewheaton** [comment]
I don't think we can recommend unpkg for production apps; we've had long discussions about this in the past). However, it makes sense to use for CodePen since there's no delay between publishing a release and being able to demo/repro code with it.

**Comment by dzearing** [comment]
I've updated my codepens. :)
