### ISSUE TITLE
With ContextualMenu open, clicking in SearchBox does not properly focus SearchBox

### ISSUE THREAD

**Issue by SpencerLynn** [OfficeDev/office-ui-fabric-react#8261]
### Environment Information 
 
- __Package version(s)__: 6.143.1
- __Browser and OS versions__: All (different behaviors in each)

### Please provide a reproduction of the bug in a codepen:
 
1. Open this [CodeSandbox](https://codesandbox.io/s/8llkop3wo2).
2. Click on the button to open the context menu
3. Click on the SearchBox

 
#### Actual behavior:
 
**Chrome:** Search box is focused, but does not show focus borders and the 'search' icon does not disappear. However, user is able to type in search box still.
**Edge:** Search box does not show focus borders and 'search' icon does not disappear. However, use is NOT able to type in the search box, despite the browser showing a blinking cursor.
**Firefox:** Search box does not show focus borders, 'search' icon does not disappear, no blinking cursor, User is unable to type.
 
#### Expected behavior:
 
Search box focuses (and shown with focus borders and search icon disappearing) and user is able to type

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes, but may not have time
 
Requested priority: Normal
 
Products/sites affected: (if applicable)

**Comment by KevinTCoughlin** [comment]
Thanks for the [repro](https://codesandbox.io/s/8llkop3wo2) @SpencerLynn! I can verify the behaviors you've listed above and added Firefox:

- **Chrome**: Search box is focused, but does not show focus borders and the 'search' icon does not disappear. However, user is able to type in search box still.
- **Edge**: Search box does not show focus borders and 'search' icon does not disappear. However, use is NOT able to type in the search box, despite the browser showing a blinking cursor./
- **Firefox**: Search box does not show focus borders, 'search' icon does not disappear, no blinking cursor, User is unable to type.

It looks to me that the `ContextualMenu` is not relieving focus upon dismissal. I'll debug further as this is a bad usability bug.

**Comment by SpencerLynn** [comment]
I agree @KevinTCoughlin. What I found is that the `ContextualMenu` is trying to return focus to the element that previously had focus when it closes. However, it does this on a timer, which I suspect could adding to the complexity here.

Thanks for the extra info!

**Comment by KevinTCoughlin** [comment]
Additional note that this repros on the local dev and production site:

![image](https://user-images.githubusercontent.com/706967/54167268-2f07d800-4426-11e9-9b89-09baee878d38.png)

- http://localhost:4322/#/examples/contextmenu
- https://developer.microsoft.com/en-us/fabric#/components/contextualmenu

**Comment by micahgodbolt** [comment]
Another example from #11502
https://codepen.io/megha21K/pen/OJPbEEa
