### ISSUE TITLE
Dropdown: Should remove IDropdownOption from onRenderTitle's parameter type

### ISSUE THREAD

**Issue by yenchanghsieh** [OfficeDev/office-ui-fabric-react#8263]
### Environment Information 
 
- __Package version(s)__: 6.118.1 
- __Browser and OS versions__: All

#### Actual behavior:
 
onRenderTitle in Dropdown component can't handle IDropdownOption well.
It currently only accepts IDropdownOption[] as input type since taking the output of _getAllSelectedOptions().
 
#### Expected behavior:
If it only accepts array now,  we should remove IDropdownOption from onRenderTitle's input type.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal
 
Products/sites affected: (if applicable)

**Comment by KevinTCoughlin** [comment]
@yenchanghsieh, although I'm not the most familiar with this component I do think I agree with you that we currently only ever invoke `onRenderTitle` with an `IDropdownOption[]`.

https://github.com/OfficeDev/office-ui-fabric-react/blob/d206093d1976603974a4fffea80caba32280471f/packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.types.ts#L53

See some of the usages within this source code query:

https://github.com/OfficeDev/office-ui-fabric-react/search?utf8=✓&q=onRenderTitle&type=

@JasonGore what do you think about @yenchanghsieh's suggestion as I understand it:

```diff
diff --git a/packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.types.ts b/packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.types.ts
index e9883d4e9..b11c6c300 100644
--- a/packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.types.ts
+++ b/packages/office-ui-fabric-react/src/components/Dropdown/Dropdown.types.ts
@@ -50,7 +50,7 @@ export interface IDropdownProps extends ISelectableDroppableTextProps<IDropdown,
   /**
    * Optional custom renderer for selected option displayed in input
    */
-  onRenderTitle?: IRenderFunction<IDropdownOption | IDropdownOption[]>;
+  onRenderTitle?: IRenderFunction<IDropdownOption[]>;
 
   /**
    * Optional custom renderer for chevron icon
```

Specifically regarding backwards-compatibility. It seems like it can be a safe change for `6.x`.

**Comment by KevinTCoughlin** [comment]
@yenchanghsieh I've raised a PR with you included (linked above). :)

**Comment by yenchanghsieh** [comment]
@KevinTCoughlin Thanks for quick fix.
