### ISSUE TITLE
Github Issues Feature on Component Pages not working

### ISSUE THREAD

**Issue by JasonGore** [OfficeDev/office-ui-fabric-react#8276]
### Environment Information 
 
- __Package version(s)__: n/a
- __Browser and OS versions__: n/a

### Please provide a reproduction of the bug in a codepen:
 
https://developer.microsoft.com/en-us/fabric#/components/choicegroup
 
#### Actual behavior:
 
Page is throwing an exception and Github Issues feature is not working. Issue seems to be in `FeedbackList` attempting to use `created_at` property of Github query results.

![image](https://user-images.githubusercontent.com/26070760/54221881-8c953680-44b1-11e9-834e-88c3fd8e6f14.png)

 
#### Expected behavior:
 
Github Iussue list feature appears.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by KevinTCoughlin** [comment]
Investigating 👀
