### ISSUE TITLE
ISpinButtonProps has `label` as required when it is actually optional

### ISSUE THREAD

**Issue by stmillMSFT** [OfficeDev/office-ui-fabric-react#8278]
In `ISpinButtonProps`, `label` is marked as a required field in both the type and online documentation, however `label` is not actually required since it is also defined in `defaultProps`.  Current typescript versions are smart enough to determine this and show it as optional when using `SpinButton` in JSX, but if you try to use the `ISpinButtonProps` type directly, it becomes required.  

### Environment Information 
 
- __Package version(s)__: latest master (6.155.0)
 
#### Actual behavior:
 
`label` is marked as required in the `ISpinButtonProps`
 
#### Expected behavior:
 
`label` should be optional since it is also defined in defaultProps

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Low
 
Products/sites affected: internal

**Comment by KevinTCoughlin** [comment]
Thanks @stmillMSFT, I've raised a PR to address this linked above.

**Comment by stmillMSFT** [comment]
wow, that was fast! thanks!
