### ISSUE TITLE
DetailsList selection reset when clicked outside anywhere in DOM such that the target element is non-tabbable

### ISSUE THREAD

**Issue by piyusing** [OfficeDev/office-ui-fabric-react#828]
### Bug Report

- __Package version(s)__: (.88)

#### Describe the issue:
Due to recent changes in SelectionZone.tsx, in method componentDidMount, empty clicks are now handled specially. Due to which the selection which a user has already made in detailslist is cleared out if the click is made on any non-tabbable element in the DOM.
#### Actual behavior:
After making selection in DetailsList click any where on the DOM such that the target element is non-tabbable(any div which doesn't not recieve focus). Observe that the selection made by the user is reset.

#### Expected behavior:
The requirement is to retain the selection which the user has already made even if the click is outside the selection zone of details grid.

See link 376 of SelectionZone.tsx here is the snippet

private _tryClearOnEmptyClick(ev: MouseEvent) {
    if (this._isNonHandledClick(ev.target as HTMLElement)) {
      this.props.selection.setAllSelected(false);
    }
  }

**Comment by dzearing** [comment]
We have conflicting requirements here. What is the scenario where a click on a non clickable entity should preserve the selection? Could you get more details?

**Comment by piyusing** [comment]
We have scenarios where we show the details corresponding to a clicked(activated) result listed as rows of detailslist. The details pane loads the preview data upon clicking a relevant row. A user is free to update the details presented and then either reject or save them. In doing so it might happen that a user clicks on a non-clickable entity resetting the selection in the list as per the current behavior. Making it difficult to correlate as to which particular row in list has the details pane opened, as there is no visual indication to infer the same.

**Comment by dzearing** [comment]
I see. it is possible we could provide an override which could be piped through to avoid clearing. something like `preserveSelectionOnEmptyClicks: true`

It's a bit verbose but I think that would help your situation.

**Comment by dzearing** [comment]
If you'd like to contribute the fix to expedite it, please feel free to submit a PR.

**Comment by dzearing** [comment]
This was added as a feature. Closing.
