### ISSUE TITLE
 Spelling errors in the document of Image Component Page

### ISSUE THREAD

**Issue by tiyee** [OfficeDev/office-ui-fabric-react#8296]
![1552464184988](https://user-images.githubusercontent.com/2190710/54262760-04df2300-45aa-11e9-9e2e-2161760fe70a.jpg)

https://developer.microsoft.com/en-us/fabric#/components/image

**Comment by KevinTCoughlin** [comment]
Thanks for the report @tiyee. The same typo existed for `height` below it, both fixed in the above linked PR.

Feel free to fix these as you see them if you wish, we welcome contributions :).
