### ISSUE TITLE
Cannot read property roundedCorner2 of undefined when using loadTheme() function

### ISSUE THREAD

**Issue by SimSpfx** [OfficeDev/office-ui-fabric-react#8299]
### Environment Information 
   "@microsoft/decorators": "~1.4.1",
    "@microsoft/sp-application-base": "~1.4.1",
    "@microsoft/sp-core-library": "~1.4.1",
    "@microsoft/sp-dialog": "~1.4.1",
    "@microsoft/sp-office-ui-fabric-core": "^1.6.0",
    "@pnp/common": "^1.0.5",
    "@pnp/logging": "^1.0.5",
    "@pnp/odata": "^1.0.5",
    "@pnp/sp": "^1.0.5",
    "@pnp/spfx-controls-react": "^1.2.2",
    "@types/webpack-env": ">=1.12.1 <1.14.0",

    "moment": "^2.22.2",
    "office-ui-fabric-core": "^9.4.0",
    "office-ui-fabric-react": "^5.65.0"

### Please provide a reproduction of the bug in a codepen:
 import {loadTheme} from 'office-ui-fabric-react/lib/Styling';

![image](https://user-images.githubusercontent.com/47321821/54297972-3232cd80-45b8-11e9-889e-b7181639809f.png)

Try to apply a default theme created by the sharepoint them generator
Where the theme is based on the next structure: 
![image](https://user-images.githubusercontent.com/47321821/54298197-99e91880-45b8-11e9-9854-a84d20d8949b.png)

This used to work until a few days ago. 

#### Actual behavior:
 
![image](https://user-images.githubusercontent.com/47321821/54298413-f9dfbf00-45b8-11e9-9c5d-e72676b852c2.png)

 
#### Expected behavior:
 
loading the theme without error.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix?
If i can help out i will.
 
Requested priority: high
 
Products/sites affected: yes

**Comment by dzearing** [comment]
Note that this is for Fabric 5. I don't know of changes here that could have changed this.

But also, I don't know what those interfaces are from. That's not what loadTheme takes.

**Comment by KevinTCoughlin** [comment]
@SimSpfx can you isolate this repro to a [Codepen](https://codepen.io/) or [CodeSandbox](https://codesandbox.io/)?

As David mentioned above, OUFR hasn't made a related change to the `5.x` branch to have caused this  to my knowledge. So to debug we would need to have this isolated to fully understand what differs.

**Comment by Jahnp** [comment]
Also tagging @phkuo for FYI/thoughts. `roundedCorner2` is from a newer version of `ITheme` supporting supports [`IEffects`](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/styling/src/interfaces/IEffects.ts), which doesn't exist on Fabric 5's [default theme object](https://github.com/OfficeDev/office-ui-fabric-react/blob/5.0/packages/styling/src/interfaces/ITheme.ts). I'm also not sure how that would result in this error but perhaps worth noting.

**Comment by phkuo** [comment]
I'm guessing this was a recent sp-client evergreen build that brought in the header that uses roundedCorner2 from odsp-shared-react. I thought all of sp-client was on Fabric 6 now?
Can you start an email thread? This is not a OUFR issue, but an internal one.
To work around this, add `theme.effects.roundedCorner = '0px'` to the theme object that you're passing to loadTheme().

**Comment by SimSpfx** [comment]
It did not solve the problem, but i know in what direction to search for the solution thanks!

**Comment by SimSpfx** [comment]
You can solve the problem by reselecting a new theming option and than reapply your theme again. 
Best to first save your themes.  No code changes needed.
