### ISSUE TITLE
TextField does not honour text-overflow scenarios for IE11/Edge

### ISSUE THREAD

**Issue by AkshanshSrivastava03** [OfficeDev/office-ui-fabric-react#831]
### Bug Report

- __Package version(s)__: ^0.87.1
- __Browser and OS versions__: IE11/IE Edge

#### Describe the issue:
Put a big text in the text-field and then click outside the text field input box. Ellipsis do not appear for the overflowing text.

#### Actual behavior:
IE Edge/11- Ellipsis do not show up for overflowing text

#### Expected behavior:

Chrome- Ellipsis show up correctly

**Comment by mdahamiwal** [comment]
`<input>` s in IE11 and Edge don't honor `text-overflow: ellipsis` and there is no simple way to fix it. https://www.w3.org/TR/css-ui-3/#text-overflow talks about text overflows but in case of input its actually the `value` that changes so its implemented differently in these browsers. There are ways people have work around it with adding `readonly` attribute with `onBlur` and removing it with `onFocus`.  Check [example](https://frontendtricksandmagic.wordpress.com/2015/03/07/how-to-make-text-overflow-ellipsis-work-for-inputs-in-ie/), but that may regress other behavior, so it sad but we may have to live with it. @dzearing, thoughts?

**Comment by dzearing** [comment]
I think this is browser behavior. Closing.
