### ISSUE TITLE
Keros Error: IDs of active elements are not unique for NavToggler

### ISSUE THREAD

**Issue by nikita0905** [OfficeDev/office-ui-fabric-react#8314]
### Environment Information 
 
- __Package version(s)__: @uifabric/dashboard: 0.42.1
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
When NavToggler component is collapsed, two active elements are rendered with the same NavLink key passed (<a> for NavSlimItemRoot and NavFloatingRoot)

 
#### Actual behavior:
 
Document has active elements with the same id attribute.
 
#### Expected behavior:
 
IDs of active elements must be unique.
![image](https://user-images.githubusercontent.com/11412027/54345588-54d0ef00-4669-11e9-9398-7fbe09589514.png)

**Comment by KevinTCoughlin** [comment]
@Raghurk can you please triage the above `@uifabric/dashboard` accessibility issue as area owner

**Comment by nikita0905** [comment]
Could someone share an update on this?

**Comment by ecraig12345** [comment]
Closing this because the dashboard package has moved to a new location.
