### ISSUE TITLE
DropDown auto-selects first item on expansion

### ISSUE THREAD

**Issue by redoz** [OfficeDev/office-ui-fabric-react#8318]
### Environment Information 
 
- __Package version(s)__: 6.156.0
- __Browser and OS versions__: 

### Please provide a reproduction of the bug in a codepen:
 Reproducible here: https://developer.microsoft.com/en-us/fabric#/components/dropdown

#### Actual behavior:
Expanding the DropDown auto-selects the first item. Even if I dismiss the DropDown by clicking elsewhere it will select the first item. 

![oufr_dropdown](https://user-images.githubusercontent.com/1670030/54353897-7922d080-4655-11e9-877e-6c4801d0d7e4.gif)

#### Expected behavior:
 
I expect it to work like this: (from [XAML Controls Gallery](https://www.microsoft.com/en-us/p/xaml-controls-gallery/9msvh128x2zt)):
![dropdown](https://user-images.githubusercontent.com/1670030/54353129-9787cc80-4653-11e9-90c8-90d1d7a4c6f3.gif)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes, depending on the fix required.
 
Requested priority: High

**Comment by KevinTCoughlin** [comment]
@Raghurk can you please triage the above `@uifabric/dashboard` accessibility issue as area owner

**Comment by cliffkoh** [comment]
Duplicate of #5473. Please take a look at that thread for a context of why (short answer: accessibility requirements).

In that thread are suggestions for workarounds as well as the ways we're welcoming PRs to provide an escape hatch for this behavior.

**Comment by Anschur** [comment]
The same will also happen if you tab through with keyboard navigation. As soon as the dropdown is focused the first item is selected (even if you don't expand it).

**Comment by redoz** [comment]
@cliffkoh In my defense I did search before creating the issue, guess I must've used the wrong keywords, apologies, will close it now.

**Comment by cliffkoh** [comment]
No worries at all @redoz, there was no blame intended :) Thanks for taking the time to report this issue - this also helps others find the issue with a different set of terms.

**Comment by redoz** [comment]
@cliffkoh No blame was inferred either, but I should've been able to find the original issue and instead I created extra work for you all :)

I did read through the other issue though, and I'm not super excited by the proposed work-arounds (they don't restore the placeholder for one) I think I can take a hammer to it and make it work well enough for what I need. And as you can't "unselect" a DropDown option anyway, I guess the current behavior makes some logical sense, even though it's not what I would expect, especially not the "on focus" behavior.

**Comment by cliffkoh** [comment]
I completely empathize with and hear you here.

One option is to do a bit of feature work to provide an escape hatch where you explicitly opt-out of the keyboard up-down, which would allow the Dropdown to disable this auto selection behavior whilst still adhering to the W3C accessibility standards.
