### ISSUE TITLE
Focussing on a textfield in a dialog box

### ISSUE THREAD

**Issue by ankitk94** [OfficeDev/office-ui-fabric-react#832]
When a dialog is opened, I want to set the default focus to a TextField created using office fabric.
The issue is to do that, I need to provide the className of the element as value to "firstFocusableSelector" prop of dialog. But in case of TextField, OfficeFabric creates it like this:

<div>
  <input />
</div>

That property requires the value as className of input and not div, but by current behaviour of TextField component, I can only provide className to the "div" and not "input".

**Comment by mdahamiwal** [comment]
@ankitk94, there is a property `inputClassName` on TextField, have you tried that?

**Comment by ankitk94** [comment]
It worked. Thanks.
