### ISSUE TITLE
API Breaking Changes for Fabric 7

### ISSUE THREAD

**Issue by JasonGore** [OfficeDev/office-ui-fabric-react#8328]
These issues contain API breaking changes that we would like to get done for Fabric 7 release:

| Issue | Title | Status |
|-------|------|--------|
| #7014 | Foundation: Finalize State & React Hooks | ✅  |
| #8823 | Foundation: Evolution of styled helper | :x: |
| #8331 | Foundation: Extend Component | :x: |
| #8334 | Foundation: 'as' Props | ✅ |
| #8335 | Foundation: Render Functions | ✅  |

**Comment by khmakoto** [comment]
@JasonGore should we close this issue since work on Foundation has stopped?

**Comment by khmakoto** [comment]
Closing due to newer efforts that'll address this issue.
