### ISSUE TITLE
Image: Load state is erroneously set as loaded when changing the src prop

### ISSUE THREAD

**Issue by asmundg** [OfficeDev/office-ui-fabric-react#833]
### Bug Report

- __Package version(s)__: 1.0.0
- __Browser and OS versions__:

#### Describe the issue:

When changing the src prop without remounting the Image component, _imageElement is a ref to the existing img tag and _evaluateImage() will claim that the image has loaded even if the new src has not loaded. This is particularly obvious when the second src is a broken URL.

#### Actual behavior:

Broken img URL icon is displayed. class is is-loaded.

#### Expected behavior:

img should be invisible, class should be is-notLoaded.

### If applicable, please provide a codepen repro:

http://codepen.io/anon/pen/appzdE

**Comment by dzearing** [comment]
Validated it is now fixed:
http://codepen.io/dzearing/pen/LxzZLq
