### ISSUE TITLE
DetailsList: Introduce onRowChecked & onRowUnchecked or similar (selection) convenience callbacks

### ISSUE THREAD

**Issue by bmckilligan** [OfficeDev/office-ui-fabric-react#8347]
**Describe the feature that you would like added**
Event Handling For Unchecking of a row

currently an item that has been checkedon on can be handled via
onItemInvoked or a list of all selected items can be retrieved with ISelection.onSelectionChanged
but there is no way to get the item that has been unChecked

**What component or utility would this be added to**
DetailsList

**Have you discussed this feature with our team, and if so, who**

**Additional context/screenshots**

**Comment by KevinTCoughlin** [comment]
I believe we've discussed this in the past, I'll need to review previous issues and get back to you shortly.

@bmckilligan is the ask to be able to have _some_ callback which receives an `item` when it is _individually_ selected / unselected (checked / unchecked)?

**Comment by bmckilligan** [comment]
@KevinTCoughlin   yes some call back that returns the item or some reference to the item such as the key or index

**Comment by KevinTCoughlin** [comment]
@bmckilligan, I implemented your ask given our current prop surface to see what all would be involved. Here's the working Codepen: https://codepen.io/kevintcoughlin/pen/wOxGjO?editors=1010

I'll add surfacing convenience props `onRowChecked` & `onRowUnchecked` to our component backlog. Since this can be accomplished today without much additional code, I think its best we wait until we clean-up the existing `DetailsList` API surface prior to introducing more.

Let me know if the above unblocks you for the time-being.

cc: @aditima @natalieethell

**Comment by bmckilligan** [comment]
@KevinTCoughlin 
Thanks for the solution, I had to make the following changes to  _onSelectionChange and _getDeltaItems  before things would work,   I have pre selected items that I want to show aschecked   and I  needed to call 
`this._selection.setKeySelected`
in the render function, also this is needed if all items are toggled off and on off 

```
private _onSelectionChanged = () => {
    const { onRowChecked, onRowUnchecked } = this.props;
    const newSelectedItems = this._selection.getSelection();

     if (newSelectedItems.length  !== 0 || this._selectedItems.length !== 0) {
          let deltaItems = this._getDeltaItems(newSelectedItems, this._selectedItems);
      
         if (deltaItems.itemsAdded.length > 0) { onRowChecked(deltaItems.itemsAdded); }  

         if(deltaItems.itemsRemoved.length > 0 )  { onRowUnchecked(deltaItems.itemsRemoved); }
    }
  }

private _getDeltaItems = function (newItems , oldItems) { 

        let itemsAdded = newItems.filter(x =>  !oldItems.includes(x) );

        let itemsRemoved = oldItems.filter(x => !newItems.includes(x) );
        
        return {
            itemsAdded: itemsAdded,
            itemsRemoved: itemsRemoved
        };
    }
```
 
in addition there was a nasty render loop that would keep going if the DetailsList prop setKey wasn't assigned as an arbitrary string   

```
<DetailsList  
          setKey={"someKeyHere"}  
            ....
 />
```
