### ISSUE TITLE
ContextualMenu: Default not prevented after handling keydown

### ISSUE THREAD

**Issue by trevorsg** [OfficeDev/office-ui-fabric-react#835]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: All

#### Describe the issue:

ContextualMenu: Default not prevented after handling keydown

#### Expected behavior:

Default is prevented so the parent doesn't decide to handle the event.

**Comment by trevorsg** [comment]
I was going to submit a pull request, but I don't have time to complete the entire checklist. In ContextualMenu.tsx, the line `ev.preventDefault();` should be included in the _onItemKeyDown method, inside the if-statement.

**Comment by dzearing** [comment]
@trevorsg if you could submit a PR, we can take a look and help with the missing checkboxes. @joschect FYI

**Comment by dzearing** [comment]
Merged, published tomorrow.
