### ISSUE TITLE
DocumentCard in compact layout has 1px blank line below preview image

### ISSUE THREAD

**Issue by fengyue1013** [OfficeDev/office-ui-fabric-react#8353]
### Environment Information 
 
- __Package version(s)__: (6.156.0) 
- __Browser and OS versions__: (chrome 72.0.3626.121)

### Please provide a reproduction of the bug in a codepen:
 It could be observed on the demo page:
https://developer.microsoft.com/en-us/fabric#/components/documentcard
#### Actual behavior:
![image](https://user-images.githubusercontent.com/12523937/54514202-7812db80-4994-11e9-89c0-d438fea7a9dd.png)
There is one-pixel blank line below the preview image

#### Expected behavior:
 
There is no blank line below the preview image

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (High) 
 
Products/sites affected: (SharePoint)

**Comment by fengyue1013** [comment]
The preview has height [106px + border-top/botttom = 108px](https://github.com/OfficeDev/office-ui-fabric-react/blob/79997dce092bf1a444754ab6e58a9f1a437a2842/packages/office-ui-fabric-react/src/components/__snapshots__/DocumentCard.Compact.Example.tsx.shot#L42), while the document card has height [109px](https://github.com/OfficeDev/office-ui-fabric-react/blob/29f7007cbf79d47a9c9373a6b2ecf0d0e36f9841/packages/office-ui-fabric-react/src/components/DocumentCard/DocumentCard.styles.ts#L64).

So there is one-pixel blank. Is this by-design??

**Comment by khmakoto** [comment]
@yiminwu it seems you are the codeowner for `DocumentCard`. Is this by design or is it a bug that requires a simple fix?

**Comment by KevinTCoughlin** [comment]
Seems like a bug. Can confirm with design's red lines, but I doubt this is intentional.

Screener should catch this, but its difficult to see unless you look at computed tab. Has happened to me.

**Comment by khmakoto** [comment]
@KevinTCoughlin I doubt this is intentional too, but I want to double check before going in and making changes. Do you know who to contact for this?
