### ISSUE TITLE
Parsing through a DetailsList.

### ISSUE THREAD

**Issue by craigdcorrea25** [OfficeDev/office-ui-fabric-react#8354]
While tabbing into a DetailList, initially the focus is on the Headers, followed by the entire row (which is completely read out by NVDA). When using up or down arrow, I am able to go from one complete row to the other complete row. With NVDA on, and while parsing through the headers using the Up and Down Arrows, the screen reader now starts to read the entire DetailsList cell wise instead of row wise.

**Comment by khmakoto** [comment]
Hi @craigdcorrea25, can you provide a codepen where this is reproing? Or does this also repro on the official site? Just want to make sure I have an environment in which I can dig into this deeper.

**Comment by craigdcorrea25** [comment]
Hi @khmakoto , it is also reproed in the official site. I've tested it on the [variants ](https://developer.microsoft.com/en-us/fabric#/components/detailslist#Variants) section. Go to the Filter By Name text box and with NVDA on, click on tab. Now, while on the icon, click the right arrow key. And now click on down arrow key. You will be parsing through the DetailsList cell-wise. Also, there is no way to go back to row-wise parsing. 
Please note that this does not happen if I do not click the right arrow key while on the DetailsList header.

**Comment by khmakoto** [comment]
@craigdcorrea25 I played with the example in the live site and I can't seem to replicate what you're experiencing. I did the exact steps you did and I could always go back to row-wise parsing as long as I tabbed out of the table and in again, even tabbing back to the headers worked. Can you check if this works on your side?
