### ISSUE TITLE
Components using FocusZone immedidiately crash

### ISSUE THREAD

**Issue by JakeStanger** [OfficeDev/office-ui-fabric-react#8355]
### Environment Information 
 
- __Package version(s)__: 6.157.0
- __Browser and OS versions__: Firefox 65 and Chrome 73, Windows 10

#### Actual behavior: 
React crashes, `Object(...) is not a function` in `FocusZone.js`.
 

 
#### Expected behavior: 
Dropdown opens, Pivot renders, etc...
 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: High
 
Products/sites affected: A customer's SharePoint site.
 
Chrome claims the error is with this:
```javascript
// Manage componentRef resolution.
initializeComponentRef(_this);
```

Full error traces:
```
Uncaught TypeError: Object(...) is not a function
    at new FocusZone (FocusZone.js:206)
    at constructClassInstance (react-dom.development.js:6801)
    at updateClassComponent (react-dom.development.js:8336)
    at beginWork (react-dom.development.js:8982)
    at performUnitOfWork (react-dom.development.js:11814)
    at workLoop (react-dom.development.js:11843)
    at HTMLUnknownElement.callCallback (react-dom.development.js:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:138)
    at invokeGuardedCallback (react-dom.development.js:187)
    at replayUnitOfWork (react-dom.development.js:11318)
FocusZone @ FocusZone.js:206
constructClassInstance @ react-dom.development.js:6801
updateClassComponent @ react-dom.development.js:8336
beginWork @ react-dom.development.js:8982
performUnitOfWork @ react-dom.development.js:11814
workLoop @ react-dom.development.js:11843
callCallback @ react-dom.development.js:100
invokeGuardedCallbackDev @ react-dom.development.js:138
invokeGuardedCallback @ react-dom.development.js:187
replayUnitOfWork @ react-dom.development.js:11318
renderRoot @ react-dom.development.js:11885
performWorkOnRoot @ react-dom.development.js:12449
performWork @ react-dom.development.js:12370
performSyncWork @ react-dom.development.js:12347
interactiveUpdates @ react-dom.development.js:12597
interactiveUpdates @ react-dom.development.js:1958
dispatchInteractiveEvent @ react-dom.development.js:4259
react-dom.development.js:9643 
```
```
The above error occurred in the <FocusZone> component:
    in FocusZone (created by DropdownBase)
    in div (created by DropdownBase)
    in div (created by Popup)
    in Popup (created by CalloutContentBase)
    in div (created by CalloutContentBase)
    in div (created by CalloutContentBase)
    in CalloutContentBase
    in StyledCalloutContentBase (created by Callout)
    in div (created by FabricBase)
    in FabricBase
    in StyledFabricBase (created by LayerBase)
    in span (created by LayerBase)
    in LayerBase
    in CustomizedLayer
    in StyledCustomizedLayer (created by Callout)
    in Callout (created by DropdownBase)
    in div (created by DropdownBase)
    in DropdownBase (created by WithResponsiveMode)
    in WithResponsiveMode
    in StyledWithResponsiveMode (created by SPFieldChoiceEdit)
    in SPFieldChoiceEdit (created by FormField)
    in FormField (created by ListForm)
    in div (created by ListForm)
    in div (created by ListForm)
    in div (created by ListForm)
    in div (created by ListForm)
    in ListForm
```

**Comment by khmakoto** [comment]
@dzearing does this have to do with your recent PR? It is related to `initializeComponentRef`.

**Comment by khmakoto** [comment]
@JakeStanger can you provide a codepen with a scenario similar to the one the error is happening in even if it isn't reproing the error?

**Comment by dzearing** [comment]
@JakeStanger here's a starter: https://codepen.io/dzearing/pen/daqMzx

We aren't seeing the repro, but that doesn't mean it's not there. If we can repro; then we can make sure it's somewhere in the library that we can fix. We are trying different things on our end, but if you can adjust the codepen to do what you're doing and we have it reproing, that would help us isolate where the issue is.

**Comment by JakeStanger** [comment]
Your starter contains enough to cause it and more. I've added my usage of the Pivot component which also created a crash. As you can see it's the very bare usage.

[https://codepen.io/jakestanger/pen/ZPjGgB](https://codepen.io/jakestanger/pen/ZPjGgB)

**Comment by khmakoto** [comment]
@JakeStanger I checked the codepen in Edge, Chrome and Firefox and cannot seem to repro the issue. Is there any way we can repro this? It's kind of hard to check and make a fix if we cannot see how the bug behaves in the first place.

**Comment by JakeStanger** [comment]
I have no idea how to reproduce this myself unfortunately. If I get time tomorrow I'll play around and see if I can isolate/discover anything about the issue.

**Comment by khmakoto** [comment]
Perfect, In the meantime I'll try to isolate the bug too. Are there any specific props you're passing that we should be aware of? Or is the codepen you provided pretty much on par with the scenario where the bug is reproducing?

**Comment by JakeStanger** [comment]
That codepen is on par. It really was the simplest of setups causing the issue. I'm wondering if some other dependency or webpack are contributing to the issue.

**Comment by JakeStanger** [comment]
Whelp, I deleted my `node_modules` and used another developer's yarn.lock file as he wasn't having the issue on the project, and it fixed it. Possibly some very edge case dependency resolution bug?

**Comment by khmakoto** [comment]
It's great to know that you found a fix! I'll add `Resolution: Not an issue` tag for now, but feel free to reply back if you encounter other problems.

**Comment by dzearing** [comment]
Also feel free to close the issue @JakeStanger if you're good to go. We are happy to help if you need anything else.

**Comment by JakeStanger** [comment]
Cheers for the help guys and sorry it was a bit of a dead end. I'll re-open it if it ever occurs again or I find out more.

**Comment by JakeStanger** [comment]
I just came across this issue again, this time it was Dropdowns rather than FocusZones. It occured after upgrading my SPFx component from 1.8.0 to 1.8.2. 

Same fix of deleting node_modules & lock file fixed it. If I was clever I would have backed up the old lockfile and diffed them. I don't think this issue needs reopening at the moment but it's definitely something to keep an eye on even if it isn't an issue directly with this package.
