### ISSUE TITLE
DetailPanel should be shown in https://developer.microsoft.com/en-us/fabric

### ISSUE THREAD

**Issue by JoshuaLamusga** [OfficeDev/office-ui-fabric-react#8357]
The DetailPanel control is not featured or mentioned anywhere on developer.microsoft.com/.../fabric. Please add it. My team has a dependency on the control and the names for the props, such as "currentL2Id" to name one, warrant an easily-accessible description. It will benefit anyone else relying on the detail panel.

**Comment by Jahnp** [comment]
Hi @JoshuaLamusga , DetailPanel appears to be part of the @uifabric/dashboard package which is not planned to be documented on the website. Tagging @kenotron / @ecraig12345 who I believe have been helping with the "internal-ization" of the dashboard package and may have info on if there is docs for it (e.g. maybe there's an internal site?)

**Comment by khmakoto** [comment]
Hi @JoshuaLamusga, from what I can see the `DetailPanel` component is in the `dashboard` package. From my understanding, we don't currently host components that are not in the `office-ui-fabric-react` package on our website.

CCing @micahgodbolt who might have more insight on this.

**Comment by micahgodbolt** [comment]
For now you can preview the dashboard package on all of our PR builds

http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/8360/merge/dashboard/dist/index.html

As Peter mentioned, this package will eventually be going internal source and will be maintained by the dashboard team themselves.

**Comment by khmakoto** [comment]
I'll be closing this per the comments above.

**Comment by JoshuaLamusga** [comment]
Thanks! My mistake.
