### ISSUE TITLE
FocusZone doesn't restore focus correctly with virtual parents

### ISSUE THREAD

**Issue by Dalimil** [OfficeDev/office-ui-fabric-react#8366]
### Environment Information 
 
- __Package version(s)__: 6.146.1

#### Actual behavior:
 
Start with FocusZone that contains a few buttons... If one of them opens a ContextualMenu, and it is closed after moving focus to it, the focus is not restored. This is because FocusZone keeps track of the `_lastIndexPath` where the focus should be restored. It saves this path if it detects that an elementContains the focusedElement. This is true for ContextualMenu because it is a valid parent (virtual) in React, but not in DOM. The result path is saved but since the element was never the actual DOM parent this path is not valid and restores the focus incorrectly.

**Comment by dzearing** [comment]
Thanks for the report @Dalimil! We will investigate.

**Comment by dzearing** [comment]
https://codepen.io/dzearing/pen/oVMerL

I am not reproing. @Dalimil can you take a look at the codepen and tweak it until you can repro? That would help us understand the root issue.

**Comment by Dalimil** [comment]
@dzearing It's somewhat hard to set up because it assumes you destroy the menu, the focus goes to body and you enter this condition branch of the focus zone with an invalid focus restoration path array: 
![image](https://user-images.githubusercontent.com/4202539/54633116-bd8ae380-4a3c-11e9-90a6-c6fb29434832.png) 
But if you look at this codepen: https://codepen.io/dahajek/pen/QoVKvM?editors=1010

Open it, open devtools (F12), and then click on the `I am a menu` button. Don't move mouse afterwards, leave the menu open and watch dev console. It is logging the focus restoration path. But the path is clearly invalid with child indexes containing value `-1` which will result in an unexpected behavior during focus restoration.

**Comment by Dalimil** [comment]
The Focus Zone will try to restore the focus wrong. This is not immediately obvious, because the context menu itself is also doing the focus restoration. Contextual Menu is restoring the focus correctly but since there is an async delay, this can cause a brief focus jump from the place where focus zone restored it to the correct place where context menu restored it.
This is caused by this line: https://github.com/OfficeDev/office-ui-fabric-react/blob/f476aa80a93b0a69dbe5066a858840e6fdfb0aca/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.base.tsx#L173

An alternative solution would be to fix the setTimeout in the code above. But the path restoration in focus zone is invalid regardless.
