### ISSUE TITLE
Incorrect number of rows are being read out by screen reader while reading a DetailsList.

### ISSUE THREAD

**Issue by craigdcorrea25** [OfficeDev/office-ui-fabric-react#8374]
While using NVDA, the screen reader is reading the number of rows visible in the DetailsList plus the headers, thus giving wrong information to the user. 
This issue is seen on the official site under [variants](https://developer.microsoft.com/en-us/fabric#/components/detailslist#Variants) section. There are 500 rows, but the screenreader is reading as 501 rows.

**Comment by khmakoto** [comment]
I have checked that this does repro on the official site. I'll check to see if we can fix this if it's a problem on our side or if this is a problem on NVDA's side.

**Comment by khmakoto** [comment]
@KevinTCoughlin I've checked and this also reproes in Narrato+Edge. Are we including the headers in the row count by design or should we change this behavior?

**Comment by KevinTCoughlin** [comment]
Announcing the header row as part of the row count is intended behavior and to specification _to my knowledge_.

As reference, see **Example 2** on the W3 ARIA official data grid example which announces the table header row as "Row 1" at https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html.

**Narrator output**

```shell
Table Transactions January 1 through January 7, has 8 rows, 6 columns,, Date, button, Column Header, Row 1 of 8 Column 1 of 6 
01-Jan-16, non-selected, editable, Column Header Date, Row 2 of 8
```

**Comment by craigdcorrea25** [comment]
If this is expected behaviour, then you can go ahead and close this bug.
Thanks a ton.

**Comment by khmakoto** [comment]
Thank you @craigdcorrea25!! I'll close the bug then!
