### ISSUE TITLE
[Accessibility]In case if the Menu item in Commandbar is a drop down (having submenuprops), then it is narrated as "Submenu" and not "Menu"

### ISSUE THREAD

**Issue by v-khkuma** [OfficeDev/office-ui-fabric-react#8377]
Bug Report

-Package version(s): [https://developer.microsoft.com/en-us/fabric#/components/commandbar ](url)
- Browser and OS versions: Chrome+NVDA

**Actual Behaviour:**
In case if the Menu item in Commandbar is a drop down (having submenuprops), then it is narrated as "Submenu"

**Expected:**
if the Menu item in Commandbar is a drop down (having submenuprops), then it is narrated as "Submenu" and not "Menu"

If applicable, please provide a codepen repro:
[https://codepen.io/micahgodbolt/pen/zaGwee](url)

**Comment by khmakoto** [comment]
Hi @v-khkuma, thank you for filing the issue! I'll take a look at this later today to check if I can get it to repro.

**Comment by v-khkuma** [comment]
> Hi @v-khkuma, I don't think I'm fully understanding you, do you mean when you enter into the dropdown menu it's narrated as `Menu` right now instead of as `Submenu` and it should reading `Submenu` instead?

Hi @khmakoto , When i enter the dropdown, it should be narrated as "Menu".
