### ISSUE TITLE
Add extensible buttons to Dialog's topButtons section (next to the close button)

### ISSUE THREAD

**Issue by rickyp-ms** [OfficeDev/office-ui-fabric-react#838]
### Bug Report

- __Package version(s)__: 1.0.0
- __Browser and OS versions__:  All

#### Describe the issue: 
We would like to have the ability to add extra buttons to the top buttons section of a dialog

#### Actual behavior:
Currently only one button is allowed (close)

#### Expected behavior:
Extensible button arrangement

### If applicable, please provide a codepen repro:
Code review coming soon...

**Comment by rickyp-ms** [comment]
See https://github.com/OfficeDev/office-ui-fabric-react/pull/839

**Comment by dzearing** [comment]
What is the use case? Do you have a screenshot of what you're trying to do?

**Comment by rickyp-ms** [comment]
Something like this...
![dialogtopbuttonexample](https://cloud.githubusercontent.com/assets/22225666/22089161/1ce4f40a-dd9e-11e6-8503-f994352d7362.png)

**Comment by rickyp-ms** [comment]
That way the delete button is a bit hidden so the user's first attempt isn't to delete the object (for us a task). Other useful things up there would be links to external workflows such as
 - View the conversation for this object
 - View the files for this object
 - View the Skype team for this object
etc.

**Comment by rickyp-ms** [comment]
Fixed in 839
