### ISSUE TITLE
ISliderStyles lineContainer and thumb are clobbered at runtime

### ISSUE THREAD

**Issue by dylankil** [OfficeDev/office-ui-fabric-react#8386]
### Environment Information 
 
6.151.0

### Codepen:
 
https://codepen.io/anon/pen/rRZmrV
 
#### Actual behavior:
 
custom styles are overwritten by dynamic css path
 
#### Expected behavior:
 
custom styles should not be overwritten

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No, unfortunately don't have any free dev cycles.
 
Requested priority: Normal
 
Products/sites affected: Immersive Reader

**Comment by khmakoto** [comment]
Hi @dylankil, I think the custom styles are not being overwritten, but rather that they're being applied incorrectly. Please take a look at [this codepen](https://codepen.io/khmakoto/pen/Mxqogw) that has the styling you provided applied correctly.

Please let me know if there is anything that's not easily understandable on the approach I took or if there's anything else I can help with.

**Comment by dylankil** [comment]
Ah, thanks. Is there a way I can access the pseudo selector properties too? Hover, After, etc.?

**Comment by khmakoto** [comment]
Yes, you can do it pretty much the same way, I've modified the [codepen](https://codepen.io/khmakoto/pen/Mxqogw) to show how this can be done on hover for example.

Please let me know if there is anything else I can do to help.

**Comment by dylankil** [comment]
Sweet - This was the new feature request I logged. I guess my ask would be to update the docs.
