### ISSUE TITLE
Style Props Members Should Be Optional And Allow Pseudo Selector Properties

### ISSUE THREAD

**Issue by dylankil** [OfficeDev/office-ui-fabric-react#8387]
Currently all members of IStyleProps are required in typed global variables. All members should be optional to save lines of code. Also, Devs should be able to style all pseudo selector properties like focus, hover, before, after... as parents of each exposed member.

**Comment by khmakoto** [comment]
Hi @dylankil, I'm confused in what you mean by all of this. What exactly do you mean in this case by typed global variables? `IStyleProps` are required because they are the building parts for styling in our components. If you could provide some clarification on this it would be great. Thanks!

**Comment by dylankil** [comment]
Styles are shared in the Immersive Reader, therefore it's not sufficient to repeat the styles of each element. We do something like this in a shared .ts file:

```
// Office UI Fabric Overrides
export const CalloutStyles: ICalloutContentStyles = {
    beak: { /* required */ },
    beakCurtain: {
        margin: '-4px',
        border: '4px solid' + ' ' + cssVariables.darkThemeFontColor,
        borderRadius: '4px'
    },
    calloutMain: {
        overflowY: 'hidden'
    },
    container: { /* required */ },
    root: {
        animation: 'none',
        border: '4px solid white',
        borderRadius: '4px'
    }
};
```
Note how I need to pass in unused selectors as required.

We should also have the ability to style the visual states of each component. e.g. &:hover, &:before, &:after, etc.

**Comment by dylankil** [comment]
It would be a lot more performant as the g-zipped payload would be smaller - to customize the pseudo selector properties in shared JS than wrapper specific SCSS. Maybe something like this:

https://twitter.com/jlongster/status/1103684127197405184

**Comment by khmakoto** [comment]
You should be able to style the visual states of each component as follows:

```ts
// Office UI Fabric Overrides
export const CalloutStyles: ICalloutContentStyles = {
    beak: { /* required */ },
    beakCurtain: {
        margin: '-4px',
        border: '4px solid' + ' ' + cssVariables.darkThemeFontColor,
        borderRadius: '4px'
    },
    calloutMain: {
        overflowY: 'hidden'
    },
    container: { /* required */ },
    root: {
        animation: 'none',
        border: '4px solid white',
        borderRadius: '4px',
        selectors: {
            ':hover': {
                border: '4px solid lightgray'
            }
        }
    }
};
```

**Comment by dylankil** [comment]
Very cool, Would be excellent to omit beak, container and other unused lines of JS.

**Comment by JasonGore** [comment]
@dylankil Can you use `Partial` here? i.e.
```tsx
export const CalloutStyles: Partial<ICalloutContentStyles> = {
  ...
};
```

We use this approach widely within our the repo. Additionally, starting with Fabric 7 we'll be introducing new ways of defining styles functions and objects that will abstract this concern away.

**Comment by dylankil** [comment]
Yes, thanks!

**Comment by JasonGore** [comment]
Ok, if you are satisfied with the resolution please close the issue. Thanks!
