### ISSUE TITLE
28x is not valid css

### ISSUE THREAD

**Issue by highpowerxh** [OfficeDev/office-ui-fabric-react#8407]
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Calendar/Calendar.scss#L298

### Environment Information 
 
- __Package version(s)__: n/a
- __Browser and OS versions__: n/a

#### Actual behavior:
 
28x
 
#### Expected behavior:
 
28px

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
Too much for fixing a typo, any one can bundle this with any PR or misc fixes
 
Requested priority: (Low) 
 
Products/sites affected: (if applicable)

**Comment by khmakoto** [comment]
Thanks @highpowerxh, I'll make the fix when I have some time.
