### ISSUE TITLE
[GroupedListSection] role=grid but no rowgroup or row underneath in the dom

### ISSUE THREAD

**Issue by bryanchen-d** [OfficeDev/office-ui-fabric-react#8410]
This issue is similiar to issue #1672, that one was gone as the default role in GroupedList and list items have been changed to "presentation".

However the GroupedListSection has a case in which it render a &lt;List /&gt; with role set to "grid" while there are no rowgroup or row underneath. This is causing accessibility warnings while I am integrating react-axe. 

From what I can see, a possible solution might be in office-ui-fabric-react/packages/office-ui-fabric-react/src/components/GroupedList/GroupedListSection.tsx, changing the role of &lt;List /&gt; from "grid" to "presentation" same as other grouped list items.

**Comment by khmakoto** [comment]
@micahgodbolt @JasonGore This does seem like an omission on our part since `GroupedListSection` items do not have role `rowgroup` or `row` underneath. Should we change the role to `presentation`?

**Comment by KevinTCoughlin** [comment]
@bryanchen-d, the W3 ARIA specification states that child elements with either `role="row"` or `role="rowgroup"` are acceptable "Required Owned Elements" under `role="grid"`, see https://www.w3.org/TR/wai-aria-1.1/#grid.

Looking at the default `GroupedList` example, we seem to have that hierarchy:

![image](https://user-images.githubusercontent.com/706967/54960323-4d3b0100-4f19-11e9-926f-3c03412fb302.png)

---

>However the GroupedListSection has a case in which it render a <List /> with role set to "grid" while there are no rowgroup or row underneath. This is causing accessibility warnings while I am integrating react-axe.

Is the issue you're referring to when the group is empty and hence renders an empty `List` which in turn is invalid?

If so, https://github.com/OfficeDev/office-ui-fabric-react/pull/8337 should resolve that, but we should confirm.

**Comment by KevinTCoughlin** [comment]
@bryanchen-d it would be awesome if you were able to provide a Codepen repro of the issue to help us debug and triage more efficiently :).
