### ISSUE TITLE
Windows Defender reports trojan in NPM package

### ISSUE THREAD

**Issue by jsurbaitis** [OfficeDev/office-ui-fabric-react#8420]
### Environment Information 
 
- __Package version(s)__: 6.158.0 (older had this issue too)
- __Browser and OS versions__: Windows 10.0.17763

#### Actual behavior:
 
After installing the office-ui-fabric-react package (`npm install --save office-ui-fabric-react`), Windows Defender complains about a trojan in some of the files:
![image](https://user-images.githubusercontent.com/1388144/54775151-9104d200-4bca-11e9-9162-4652944f96ef.png)

This has affected me and several colleagues starting yesterday afternoon (PST).
 
#### Expected behavior:
 
No trojans found 😃 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? n/a, willing to help
 
Requested priority: Blocking development

**Comment by amygl** [comment]
I just saw this as well. I'm using 6.150.0

**Comment by khmakoto** [comment]
Thanks for raising awareness on this! We're investigating the issue right now working with the Windows Defender team to see what's happening since we believe this to be a false positive.

**Comment by ecraig12345** [comment]
If anyone would like to inspect the code for themselves, here are some links for convenience. (Definitely no trojans, just standard boring code.)

https://unpkg.com/office-ui-fabric-react@6.158.0/lib/components/ExtendedPicker/PeoplePicker/ExtendedPeoplePicker.doc.js
https://unpkg.com/office-ui-fabric-react@6.158.0/lib-amd/components/ExtendedPicker/PeoplePicker/ExtendedPeoplePicker.doc.js
https://unpkg.com/office-ui-fabric-react@6.158.0/lib/components/Nav/Nav.doc.js
https://unpkg.com/office-ui-fabric-react@6.158.0/lib-amd/components/Nav/Nav.doc.js

**Comment by dzearing** [comment]
Engaging with the Windows Defender team.

**Comment by dzearing** [comment]
They have resolved on their side. We are following up on an ETA of how soon customers should see the fix.

**Comment by micahgodbolt** [comment]
Ok, this should be resolved now. If you continue to experience the error, try clearing the Defender's cache:

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender   
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”  
3. Run “MpCmdRun.exe -SignatureUpdate”

Can the OP please confirm this is working for them?

**Comment by jsurbaitis** [comment]
@micahgodbolt that works! Thank you all for the quick turnaround on this.
