### ISSUE TITLE
Slider: Renders improperly without a explicit direction property specified.

### ISSUE THREAD

**Issue by geoffreyyip** [OfficeDev/office-ui-fabric-react#844]
### Bug Report

- __Package version(s)__: 1.2.0
- __Browser and OS versions__: Observed in Firefox + Chromium on Ubuntu 16.04 LTS

#### Issue:

Slider component will not render properly unless the `dir` property is explicitly set in the `<html>` tag. If the global tag says something like `<html lang="en" dir="ltr">`, then the Slider component will display just like the Microsoft docs show. But if the global tag says something like `<html lang="en">`, then the Slider line won't render.

I suspect it's because of the following CSS:

    html[dir=ltr] .ms-Slider-line span {
        float: left;
    }

Turning this float property off causes the actual behavior listed below. This `html[dir=ltr]` requirement isn't documented on the [Office UI Fabric page](https://dev.office.com/fabric#/components/slider).

#### Actual behavior:

![default](https://cloud.githubusercontent.com/assets/15312106/22119904/501dcb0a-de4b-11e6-9377-1c02208a9788.png)

#### Expected behavior:

![ltr](https://cloud.githubusercontent.com/assets/15312106/22119883/42d6af5c-de4b-11e6-9585-f086e1486ebf.png)

**Comment by geoffreyyip** [comment]
P.S. I solved another visual issue with ChoiceGroup when I replaced `<html lang='en'>` with `<html lang='en' dir='ltr'>`. 

#### Without `dir` specified

![radio flawed](https://cloud.githubusercontent.com/assets/15312106/22121034/417c0ecc-de50-11e6-9360-09803c79200e.png)

#### With `dir="ltr" specified

![proper](https://cloud.githubusercontent.com/assets/15312106/22121048/4f34c6a8-de50-11e6-832d-3ef2cf4166a5.png)

Perhaps it's just that [create-react-app](https://github.com/facebookincubator/create-react-app) (Facebook's official boilerplate project for React) fails to specify a `dir="ltr"` property in its index.html files, but I feel that better documentation of the `dir="ltr"` requirement would be useful.

**Comment by dzearing** [comment]
Can you wrap your app in the <Fabric> component? This will do it for you.
