### ISSUE TITLE
CommandBar: Cannot pass menuProps to overflowButtonProps

### ISSUE THREAD

**Issue by micahgodbolt** [OfficeDev/office-ui-fabric-react#8441]
### Environment Information 
 
- __Package version(s)__: Latest
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/micahgodbolt/pen/MxZZoe?editors=1010
 
#### Actual behavior:
 
Cannot pass menuProps to overflowButtonProps without getting error
 
#### Expected behavior:
 
should not get error, className should be passed through

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? maybe
 
Requested priority: normal
 
Products/sites affected: Yammer

**Comment by khmakoto** [comment]
This is not an issue, what happened was that you wrote `overflowButtonProps` twice, which made the component break. [This codepen](https://codepen.io/khmakoto/pen/jJgGmX?editors=1010) shows it rendering correctly with `menuProps` passed.

**Comment by micahgodbolt** [comment]
Ahh, I remembered the issue was that you HAVE to pass through items if you pass through menuProps. So this works

https://codepen.io/micahgodbolt/pen/MxZZoe?editors=1010
