### ISSUE TITLE
Slider Right-To-Left: ms-Slider-Thumb is out-of-sync with ms-Slider-Line

### ISSUE THREAD

**Issue by geoffreyyip** [OfficeDev/office-ui-fabric-react#845]
### Bug Report

- __Package version(s)__: 1.2.0
- __Browser and OS versions__: Observed in Firefox + Chromium on Ubuntu 16.04 LTS

#### Describe the issue:

When a right-to-left direction property is specified on the html tag,  `<html dir="rtl">` it reverses the ms-SliderLine, but not the thumb. The line fills in from right to left, consistent with RTL, but the thumb still goes from left to right.

#### Actual behavior:

![rtl1](https://cloud.githubusercontent.com/assets/15312106/22120555/2c468db8-de4e-11e6-969f-61c7974fe36d.png)
![rtl2](https://cloud.githubusercontent.com/assets/15312106/22120560/32b6da90-de4e-11e6-8e12-9113fbd312b4.png)
![rtl3](https://cloud.githubusercontent.com/assets/15312106/22120562/341217e2-de4e-11e6-8559-51608ae1c9a8.png)
![rtl4](https://cloud.githubusercontent.com/assets/15312106/22120566/35933830-de4e-11e6-8a7d-9759cabbba74.png)
![rtl6](https://cloud.githubusercontent.com/assets/15312106/22120568/3703a7b8-de4e-11e6-8a38-cbff015a7698.png)

**Comment by dzearing** [comment]
I am not reproducing.

**Comment by dzearing** [comment]
Ok I believe I understand;

First, you can do this right now to unblock:

```ts
import { setRTL } from 'office-ui-fabric-react/lib/Utilities';

setRTL(true);
```

I will check in a patch to read it in case you have it initialized as dir=rtl. However it will read one time only and cache, so you can't change it during page execution without calling the method above.
