### ISSUE TITLE
DetailsRow- animation causing significant delay

### ISSUE THREAD

**Issue by tharshada** [OfficeDev/office-ui-fabric-react#8457]
### Environment Information 
 
- __Package version(s)__: 6.159.1
- __Browser and OS versions__: Google Chrome Version 73.0.3683.86 (Official Build) (64-bit), Windows Server 2012 R2

### Please provide a reproduction of the bug in a codepen:
 [Repro in CodePen](https://codepen.io/anon/pen/eXXMaa)

 Repro steps:

1. Expand/collapse a group, animation is causing detailsList footer row to flicker. 
It doesn't provide a good UX.

#### Actual behavior:
 [See this](https://microsoft-my.sharepoint.com/:v:/p/hatrived/EXCRAAk4EdJLlYG2HHUvnvkBHN_mHplPo3eN2dor18JOdw?e=DMdmfR)

![image](https://user-images.githubusercontent.com/41147089/54923600-977bac80-4f30-11e9-9b33-da290f513c79.png)

 
#### Expected behavior:
 https://codepen.io/anon/pen/wOOJmN

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by dzearing** [comment]
I don't believe this is something we would want to change. The animation should not be blocking the UI thread; it simply happens asynchronously, and for the most part is a pleasant transition. There could be optimizations AROUND the animation to make it smoother, e.g. if we are spinning on javascript executing too long that could be worth optimizing. We do have some styling calculation optimizations coming in the pipeline. 

I tried your repro and am not seeing a performance concern here although it would be highly sensitive to browser and machine type. Could you list these things?

**Comment by dzearing** [comment]
@tharshada If you'd like to dig into perf around the animation to make it work better for your environment, please do and suggest some fixes.

Otherwise, I don't see a way for us to conditionally remove the animation based on system perf.

There are some tangential changes coming in the pipeline that could reduce some of the work being done in the script execution, but looking at your flame graph, I don't see the animation competing with the script.

**Comment by tharshada** [comment]
> @tharshada If you'd like to dig into perf around the animation to make it work better for your environment, please do and suggest some fixes.
> Otherwise, I don't see a way for us to conditionally remove the animation based on system perf.
> There are some tangential changes coming in the pipeline that could reduce some of the work being done in the script execution, but looking at your flame graph, I don't see the animation competing with the script.

I'll get back with more details.

**Comment by dzearing** [comment]
@tharshada Thank you :)
