### ISSUE TITLE
Why are there very specific selectors in some styles?

### ISSUE THREAD

**Issue by nshoes** [OfficeDev/office-ui-fabric-react#8464]
First off, great work, this library is awesome, our team is really enjoying it. My coworker [asked a question on SO with no response](https://stackoverflow.com/questions/55285173/why-is-checkbox-text-not-using-theme-font-size), so I'm attempting to ask here.

Also, hello  @micahgodbolt 👋.

### Environment Information 
 
- __Package version(s)__: `office-ui-fabric-react@6.157.3`
 
#### Actual behavior:

I expect my `<ChoiceGroup />` label will respect my themes font size, or at least the font size set by the `root` style key. Sometimes though there are styles that are referenced inline or through [_very_ specific selectors](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroupOption/ChoiceGroupOption.styles.ts#L216).

 
#### Expected behavior:
 
I expect that I can style all things through a custom theme or the root style key.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Low

**Comment by micahgodbolt** [comment]
Yeah, that's a bit wacky. We should probably add a 'label' target in `IChoiceGroupOptionStyles` and target that directly. I don't see any specific reason we're using a descendent selector for that font style. Might have simply been an oversight during conversion to css-in-js.

@nshoes /waves

**Comment by nshoes** [comment]
Cool! I think I'll create PR's as we go through using different components and spot these specific selectors. Closing out 📕
