### ISSUE TITLE
Clicking on Checkbox triggers two onClick events

### ISSUE THREAD

**Issue by KarthikJeyabalan** [OfficeDev/office-ui-fabric-react#8466]
* Goto https://codepen.io/anon/pen/BbqOrK for a starting codepen 
  * Open Developer tools (F12)
  * click on check box, onClick event gets triggered twice. You will see 2 entries in the console log
 
#### Actual behavior:
 
Got 2 onClick event calls
 
#### Expected behavior:
 
Only one onClick event is expected

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No
 
Requested priority: (Blocking, High, Normal, Low)  High
 
Products/sites affected: Power Query Online, probably lots of other that has dependency on this.

**Comment by micahgodbolt** [comment]
What browser are you on? I only see one (or am I just not seeing it right)

![image](https://user-images.githubusercontent.com/1434956/54961065-790bb600-4f1c-11e9-8512-3052cecef2a4.png)

**Comment by KarthikJeyabalan** [comment]
Seems like you have clicked on the "label" part of checkbox.  Please click on the checkbox itself.
I have tried it on edge, chrome, new edge.

**Comment by micahgodbolt** [comment]
ah! Thanks. Got it. Also good to note for troubleshooting that the behavior only happens when clicking directly on the check box.

**Comment by dzearing** [comment]
This is the browser generating the extra click from the label click. For example, this markup also generates 2 clicks:

```html
<div id="foo">
  <div>
    <input type="checkbox" id="checkbox-4" />
    <label for="checkbox-4">I am a native label</label>            
  </div>
 </div>
```

You can see for yourself in this codepen:
https://codepen.io/dzearing/pen/RdOGLL

But also, this isn't really the right way to listen for state changes on the checkbox. A better approach would just to be to listen to the onChange event. What exactly are you trying to do with this onClick handler?

**Comment by cliffkoh** [comment]
Fixed a minor typo in David's codepen over here: https://codepen.io/anon/pen/pYBNBP

**Comment by KarthikJeyabalan** [comment]
In the same code above two clicks are generated when clicked on the label, while clicking on the checkbox generates just one.

However, in the example I presented, two clicks are generated when click on the actual checkbox and just one click event when clicking on the label.

**Comment by dzearing** [comment]
The "box" part of the checkbox is part of the label styling, rather than the input box.

I believe changing the styling could let you do what you're talking about.

I also think an even simpler solution would be to push onClick prop to the input element itself. This would generate one click and perform a little more intuitively.

**Comment by dzearing** [comment]
There is a way to do this already though it's less intuitive, but your case is pretty special.

https://codepen.io/dzearing/pen/RdOGLL?editors=1111

Basically use `inputProps` to move the onClick to the input element:

```
<Checkbox label="foo" inputProps={{ onClick: this._onClick }} />
```

This should achieve what you want. Would this be ok?

**Comment by KarthikJeyabalan** [comment]
That works. thx.
