### ISSUE TITLE
DetailsList groupProps : IsAllGroupedCollapsed issue

### ISSUE THREAD

**Issue by msdhana** [OfficeDev/office-ui-fabric-react#8473]
### Environment Information 
 
- __Package version(s)__: 6.117.2
- __Browser and OS versions__: Edge an Chrome

#### Actual behavior:
 
Grouped details  component with **isAllGroupsCollapsed** show always with expand mode after changing the property value

https://codepen.io/vitalius1/pen/QoRbqW
 
#### Expected behavior:
It should behave based on the property value 

#### Priorities and help requested:
 Yes
Are you willing to submit a PR to fix? (Yes, No)
 No
Requested priority: (Blocking, High, Normal, Low) 
 High
Products/sites affected: (if applicable)

**Comment by Vitalius1** [comment]
@KevinTCoughlin I discussed this issue with @msdhana offline and when trying to use `isAllGroupCollapsed` prop on the `DetailsList` set to true from the very beginning all we see is the collapse all chevron button in the header is in a collapsed position, but no effect over the groups. Looking into the interfaces where it's defined it looks like it's in `IGroupRenderProp` interface. Are we trying to use this prop in an incorrect way? Setting `isCollapsed` on all the groups we pass is working but wanted to see your opinion on `isAllGroupCollapsed` prop purpose as it seems it's not used anywhere except the DetailsListHeader.

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin I discussed this issue with @msdhana offline and when trying to use `isAllGroupCollapsed` prop on the `DetailsList` set to true from the very beginning all we see is the collapse all chevron button in the header is in a collapsed position, but no effect over the groups. Looking into the interfaces where it's defined it looks like it's in `IGroupRenderProp` interface. Are we trying to use this prop in an incorrect way? Setting `isCollapsed` on all the groups we pass is working but wanted to see your opinion on `isAllGroupCollapsed` prop purpose as it seems it's not used anywhere except the DetailsListHeader.

This could be a bug. I remember a recent issue or PR recently about this functionality. Let me take a look thru the archive and get back to you soonish.

**Comment by KevinTCoughlin** [comment]
I'm not saying this is the _correct fix_, but one "solution" is at the `GroupListSection` layer:

```diff
diff --git a/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Grouped.Example.tsx b/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Grouped.Example.tsx
index e5c9fa0a4..9180eec85 100644
--- a/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Grouped.Example.tsx
+++ b/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Grouped.Example.tsx
@@ -93,6 +93,7 @@ export class DetailsListGroupedExample extends BaseComponent<{}, IDetailsListGro
           ariaLabelForSelectionColumn="Toggle selection"
           onRenderDetailsHeader={this._onRenderDetailsHeader}
           groupProps={{
+            isAllGroupsCollapsed: true,
             showEmptyGroups: true
           }}
           onRenderItemColumn={this._onRenderColumn}
diff --git a/packages/office-ui-fabric-react/src/components/GroupedList/GroupedListSection.tsx b/packages/office-ui-fabric-react/src/components/GroupedList/GroupedListSection.tsx
index 699510bc4..00f86eeba 100644
--- a/packages/office-ui-fabric-react/src/components/GroupedList/GroupedListSection.tsx
+++ b/packages/office-ui-fabric-react/src/components/GroupedList/GroupedListSection.tsx
@@ -125,6 +125,10 @@ export class GroupedListSection extends BaseComponent<IGroupedListSectionProps,
 
     this._id = getId('GroupedListSection');
 
+    if (group && props.groupProps && props.groupProps.isAllGroupsCollapsed !== undefined) {
+      group.isCollapsed = props.groupProps.isAllGroupsCollapsed;
+    }
+
     this.state = {
       isDropping: false,
       isSelected: selection && group ? selection.isRangeSelected(group.startIndex, group.count) : false
```

The problem here is that the `isAllGroupsCollapsed` flag is only used to determine chevron state. The `GroupedList` and its inner component `GroupListSection` only check `group.isCollapsed` to determine what to render, see: 

https://github.com/OfficeDev/office-ui-fabric-react/blob/0c04b004f69676a2a0aba9219d76caf98961dd84/packages/office-ui-fabric-react/src/components/GroupedList/GroupedListSection.tsx#L219

When the expand and collapse chevrons are clicked, we iterate thru the groups and toggle `group.isCollapsed` in `GroupedList`, see:

https://github.com/OfficeDev/office-ui-fabric-react/blob/0c04b004f69676a2a0aba9219d76caf98961dd84/packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.base.tsx#L121

So we need to determine at what layer we make this call. The `groupProps` is passed all the way down to `GroupListSection`, hence why I thought we might want to respect the flag there. Mutating the props aren't great, but its how this is currently coded.

I'm not sure this flag has worked in the past. I think its also worth noting via doc comment that the flag only sets _initial_ state, else you'd never be able to toggle the groups collapsed state.

cc: @aditima @natalieethell @Vitalius1 for ideas

**Comment by natalieethell** [comment]
@KevinTCoughlin what if we put the logic in GroupedList.base instead? We could add the following logic:

```tsx
public componentDidMount(): void {
  const { groupProps, groups } = this.props;
  if (groupProps && groupProps.isAllGroupsCollapsed) {
    if (groups !== undefined) {
      for (let group of groups) {
        group.isCollapsed = true;
      }
    }
  }
}
```

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin what if we put the logic in GroupedList.base instead? We could add the following logic:
> 
> ```ts
> public componentDidMount(): void {
>   const { groupProps, groups } = this.props;
>   if (groupProps && groupProps.isAllGroupsCollapsed) {
>     if (groups !== undefined) {
>       for (let group of groups) {
>         group.isCollapsed = true;
>       }
>     }
>   }
> }
> ```

Also a valid solution! I'm honestly unsure which solution to advise. My only concern is how `groupProps` is passed thru each layer down to `GroupedListSection`.

**Comment by Vitalius1** [comment]
Agree on that top-most level is best with the current code, but with that said this is something that needs to be cleaned up as from what it looks like to me it's a pattern of prop mutation which might hide some other issues underneath.

**Comment by KevinTCoughlin** [comment]
> Agree on that top-most level is best with the current code, but with that said this is something that needs to be cleaned up as from what it looks like to me it's a pattern of prop mutation which might hide some other issues underneath.

Indeed.. we both were unable to come up with a solution given the current code that does not mutate props without breaking backwards compat. Open to ideas!
