### ISSUE TITLE
MaskedTextField - Is it possible to allow positive numbers only and prefix $?

### ISSUE THREAD

**Issue by honb** [OfficeDev/office-ui-fabric-react#8492]
I'm trying to use MaskedTextField as a number field (positive numbers only), looks like "mask" property does not support.
Is there a way for me to do this with MaskedTextField?

Thanks in advance!

**Comment by Vitalius1** [comment]
Hi @honb, it would really help to have a starting playground like a codepen where you are demoing what exactly you are trying to achieve and where it fails. Here is a [codepen](https://codepen.io/vitalius1/pen/GebvKp) to start with.

**Comment by honb** [comment]
Thanks @Vitalius1 . The mark what I tried is "$ ^[0-9]" (I'm not sure about this mark format). because I don't want underline in textbox & no max value there. Just like a normal textbox, something like NumberTextField

**Comment by Vitalius1** [comment]
@honb https://codepen.io/vitalius1/pen/GebvKp is this what you are looking for? The second field is replacing the underline with a space char. Also, note that you would want to limit how many numbers a user is allowed to type in case that number will be used in some calculations and exceeds the JS max safe number.
Let me know if you meant something different and I will be willing to help as long as there is a clear question with some examples of what you are trying to achieve.

**Comment by Vitalius1** [comment]
@honb I updated the codepen to have the `$` prefix. From your thumbs up reaction, I get that it solved your issue. If that is the case feel free to close the issue or you can leave it as is and our bot will soft close it in about a week or so.

**Comment by honb** [comment]
Thank you!
I think thats enough for me. It would be nice if there is an option for minValue and no max value

**Comment by Vitalius1** [comment]
@honb I will close the issue then. Thanks for posting the question as it might help someone searching for the same answer.

With that said, we do have a [SpinButton](https://developer.microsoft.com/en-us/fabric#/components/spinbutton) component which is more suitable for handling numbers in comparison to TextField. It can handle minVal and maxVal.
