### ISSUE TITLE
Split button not clickable in Mobile View

### ISSUE THREAD

**Issue by craigdcorrea25** [OfficeDev/office-ui-fabric-react#8497]
Greetings.
Basically in a split button there are 2 clickable parts to the button.
Either clicking on the main button, or clicking on the arrow besides the button.

While testing the split button in Mobile View, I am not able to click on the main button. The arrow besides the button works fine.

I have reproduced this issue on the office fabric site in the [Buttons](https://developer.microsoft.com/en-us/fabric#/components/button) section under sub-section 
split buttons.

I have tested this in Google Chrome.

**Comment by dzearing** [comment]
This is, I believe, by design. @jspurlin for FHI.

As I understand, in touch, the "split" part can be a very small hit target; so the design across applications has been for touch devices to simply resort to the menu. The "action" portion of the split should always be accessible in the menu.

**Comment by adityapelluri** [comment]
@dzearing Is there a way that we can overwrite this behaviour? Like changing the target part only to the chevron and keep the primary button functionality as it is?
