### ISSUE TITLE
[Accessibility]TextField - extra tab with keyboard navigation on textfield file control

### ISSUE THREAD

**Issue by arunarokk** [OfficeDev/office-ui-fabric-react#8502]
## Codepen demonstrating the issue
https://codepen.io/arunarokk/pen/rREGJx

## Actual behavior:
while navigating with keyboard , focus goes two times on this control, one for whole control and another on browse button. It repro's only on Edge, works fine on Chrome
## Expected behavior:
while navigating with keyboard, focus should go to browse button only.
## Documentation describing expected behavior
we have accessibility MAS bug created for this issue

**Comment by Vitalius1** [comment]
It seems to me that this is a browser specific implementation. Different browsers are implementing the input of type file in different ways. As an example, this is how it looks in in Chrome:
![Screen Shot 2019-03-27 at 3 20 07 PM](https://user-images.githubusercontent.com/29514833/55116316-13e2cc80-50a4-11e9-8625-ee91b5c74e70.png)

They basically recreate the input as being an input of type button with the help of shadow dom. Unfortunatley there is no support for shadow dom in Edge. Will try to look if there is any alternatives with styles in hiding the input and leaving only the button.

**Comment by Vitalius1** [comment]
Also, here is a [codepen](https://codepen.io/vitalius1/pen/NJZyoZ) with the native input doing the exact same thing in Edge. It first focuses on the input as a whole and then on the button. But it looks like there is no way to dissect it in the developer tools.

**Comment by Vitalius1** [comment]
@ecraig12345 you are listed as code owner on TextField. Any ideas?

**Comment by Vitalius1** [comment]
A suggestion would be to create a custom input of type file that will have the same behavior but styled from the ground by us so it looks the same for every browser. 

A few simple styling approaches would be demoed here:
http://css-workshop.com/css-custom-input-file-in-internet-explorer-chrome-and-firefox/
https://css-tricks.com/snippets/css/custom-file-input-styling-webkitblink/

**Comment by ecraig12345** [comment]
I was just recently added as the codeowner for TextField, so no ideas offhand, sorry.

**Comment by dzearing** [comment]
This is a browser quirk. Not a Fabric issue.
