### ISSUE TITLE
DetailsList focus lost

### ISSUE THREAD

**Issue by caiomontei** [OfficeDev/office-ui-fabric-react#8503]
Hi, I have a question about the DetailsList component.

Let's say I am interacting with the headers of the list, like dragging the headers and changing the order of the columns.

When doing so in chrome, even if a render occurs at the page, the focus/tab position is preserved and we can continue keyboard navigation from where it was before. While in Edge, the tab position is lost and keyboard navigation starts at the beginning of the page.

Any ideas on why this is happening?

**Comment by Vitalius1** [comment]
@caiomontei thanks for filing an issue.
I tried to reproduce in this [codepen](https://codepen.io/vitalius1/pen/WmqzVp) the issue you are seeing and could not see it happening. The selection is preserved and I am able to tab further from where I left. Can you try and repro it in the codepen I gave you and then get back to us with the exact steps to repro so we can look into it? Thanks!

**Comment by caiomontei** [comment]
Hi @Vitalius1 . Yes, your codepen works as expected. We are trying to repro the issue in the codepen and will let you know if we manage to sucdeed.

Thanks for the help
