### ISSUE TITLE
Detail Panel: Escape does not trigger dismiss props

### ISSUE THREAD

**Issue by JoshuaLamusga** [OfficeDev/office-ui-fabric-react#8520]
The prop **onDetailPanelDimiss** for detail panel has no light dismiss handling. It also has a typo in the name. The panelSettings prop does include a light dismiss handler, but it's not available to the detail panel, so it doesn't get used.

This is a problem in my app because I manage my state with redux and I set the flyout closed state when onDetailPanelDimiss fires, but it never does for light dismissal. Currently I'm using componentWillUnmount as a workaround.

BaseContainer takes onLightDismiss from props, but it's not being passed onLightDismiss by DetailsPanel.Base. I think a new prop for light dismiss handling would be the best solution.

Are you willing to submit a PR to fix? **No**
Requested priority: **High**

**Comment by Vitalius1** [comment]
@Raghurk this looks like it's about the dashboard package. Feel free to assign the issue to whoever is going to look into it. Thanks!

**Comment by JoshuaLamusga** [comment]
Updating to high priority for myself. It's blocking me at the moment.

**Comment by timtong1982** [comment]
Thanks Joshua,

https://github.com/OfficeDev/office-ui-fabric-react/pull/8632
here the PR to fix the typo

for light dismiss, this is already supported in today's version, please use 
```
panelSetting={{
            isLightDismiss: true,
            onLightDismiss: () => {
              console.log('light dismiss triggered');
              this.setState({ show: false });
            }
          }}
```
I've updated the example file

**Comment by JoshuaLamusga** [comment]
I tried again, but it still fails.

![image](https://user-images.githubusercontent.com/30244654/56167795-01b2ca80-5f8e-11e9-8953-7e0377d9ab93.png)

I only get 'DISMISS CALLED' when clicking away or closing the flyout via the X button. If I try to press escape, I don't get an alert. That means this issue isn't about light dismiss not working, but more specifically escape not counting as a light dismiss (or not triggering somehow). I'll update the title.

**Comment by Vitalius1** [comment]
@Raghurk due to `dashboard` package being moved out of this repo, can you please close all the issues related to it and point the authors to the new location and the process of filing an issue there? Thanks!

**Comment by ecraig12345** [comment]
Closing this because the dashboard package has moved to a new location.
