### ISSUE TITLE
Detail Panel: Two onPivotLinkClick areas

### ISSUE THREAD

**Issue by JoshuaLamusga** [OfficeDev/office-ui-fabric-react#8521]
There are two places you can have onPivotLinkClick. You can define it in mainContent and as a direct prop to <DetailPanel />. It looks like the intent was to omit it from mainContent props and define it directly under DetailPanel because it’s an important prop, In this case the mainContent’s typescript interface should Omit<> the onPivotLinkClick prop. We depend on it in M365 and maybe external users too, so I think it should be deprecated for now.

Can submit a PR? **No**

**Comment by Vitalius1** [comment]
@Raghurk another one for dashboard package.

**Comment by ecraig12345** [comment]
Closing this because the dashboard package has moved to a new location.
