### ISSUE TITLE
Detail Panel: IActionButton doesn't take a prop for being disabled

### ISSUE THREAD

**Issue by JoshuaLamusga** [OfficeDev/office-ui-fabric-react#8523]
The IActionButton interface that's related to the onGetL2ActionBar prop passed into DetailPanel doesn't define a disabled prop, so it doesn't allow for disabled buttons. This is relevant for the primaryButton prop in IActionButton that acts as a save button. It's a very important scenario that the save button may be disable-able.

Without this, I wouldn't be able to use the DetailPanel's sub-flyout support even though it handles pivots and other scenarios I need.

**Comment by Vitalius1** [comment]
There are 3 issues in regards to the `dashboard` package. @Raghurk I assigned them to you as area code owner and leave it up to you to triage. Thanks!

**Comment by ecraig12345** [comment]
Closing this because the dashboard package has moved to a new location.
