### ISSUE TITLE
Facepile persona coin image shifts after load

### ISSUE THREAD

**Issue by vivekmogalapalli** [OfficeDev/office-ui-fabric-react#8530]
### Environment Information 
 
- __Package version(s)__: Latest
- __Browser and OS versions__: Chrome, Edge (Windows 10 and Windows Server 2016, didn't test  the others)

### Please provide a reproduction of the bug in a codepen:

The bug can be reproduced at Fabric's official page:
https://developer.microsoft.com/en-us/fabric#/components/facepile 

In the Variant section of Facepile's official page, dragging the slider to increase the number of personas shows the second person, displays their image and then slightly shifts it to the right.

NOTE: It repros at all zoom levels below 110%

 
#### Actual behavior:

The following gif illustrates the behavior on office fabric's official page:
https://developer.microsoft.com/en-us/fabric#/components/facepile 

![FacepileImagePopFabric](https://user-images.githubusercontent.com/49001484/55203775-d5bfd880-5189-11e9-90a8-d5745bf1394c.gif)

 
#### Expected behavior:
 

The image of a person in should never shift after load

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
No
 
Requested priority: (Blocking, High, Normal, Low) 
Blocking

Products/sites affected: (if applicable)
Word Online
Excel Online
Powerpoint Online
(Potentially everyone using the Facepile component)

These apps reuse the facepile component to show display all coauthors when when multiple people are collaborating on a single document.
The following gif illustrates the behavior on Word Online: 
www.word.office.com

![FacepileImagePopWord](https://user-images.githubusercontent.com/49001484/55204239-7367d780-518b-11e9-8ae8-79a53514b9d0.gif)

**Comment by dzearing** [comment]
Thanks for the report, will investigate asap.

**Comment by Vitalius1** [comment]
@dzearing I looked real quick at this issue and it appears this has something to do with the FadeIn animation in the `Image` component. If removing the animation the issue goes away. I tested moving the FadeIn animation on the wrapping element of the <img> tag and it looks like the bug goes away and we still keep the fade in effect.

**Comment by Vitalius1** [comment]
Hmm... I tried setting the animation on the parent element and the issue didn't really go away. So far I pinpointed that it has something to do with the fade in animation: You can see it from this gifs:
![2019-03-29 18 57 49](https://user-images.githubusercontent.com/29514833/55269798-a9bd5980-5254-11e9-80d9-66c3fef06b2b.gif)
![2019-03-29 18 58 13](https://user-images.githubusercontent.com/29514833/55269801-ab871d00-5254-11e9-909d-67adbaf48452.gif)

**Comment by Vitalius1** [comment]
Adding `backfaceVisibility: hidden` on the image helped but at the same time blured the image adn could not find a solution to fix it. Maybe all this findings might help you give it a try.
