### ISSUE TITLE
FocusZone: make "park" behavior opt in

### ISSUE THREAD

**Issue by brwatt** [OfficeDev/office-ui-fabric-react#8533]
If there are no commands provided for the CommandBar component, then is should not be accessible. Being able to focus an empty menubar can be confusing. The FocusZone, role attribute, and aria label should all be removed if there are no commands provided.

## Codepen demonstrating the issue
https://codepen.io/brwatt/pen/KYPMXp

## Actual behavior:
When empty, the commandbar is still visible, focusable, and read by a screen reader.

## Expected behavior:
When empty, the commandbar should be visible, but not focusable nor read by a screen reader.

**Comment by dzearing** [comment]
I'm going to repurpose this issue to make the "focus parking" feature an opt in. Right now it's a baked in behavior but clearly there are cases where it does not make sense.

@ThomasMichon as an fyi

**Comment by micahgodbolt** [comment]
hmm...i can't repro this (assuming i should be able to tab focus to the empty command bar)
