### ISSUE TITLE
Spinner A11y Pass

### ISSUE THREAD

**Issue by awalia13** [OfficeDev/office-ui-fabric-react#8534]
Tracking all of the issues brought up with the 3/26 accessibility pass on Spinner control
Details on individual bugs can be found on[Sharepoint](https://microsoft-my.sharepoint.com/:x:/r/personal/v-amaver_microsoft_com/_layouts/15/Doc.aspx?sourcedoc=%7B22781383-a835-4d88-b37d-79bf5cf01248%7D&action=default&uid=%7B22781383-A835-4D88-B37D-79BF5CF01248%7D&ListItemId=1905&ListId=%7B395E1ECB-5002-440E-81C5-6A090E98077C%7D&odsp=1&env=prodbubble)
- [ ] Bug1:[Accessibility][Screen Reader]: Screen reader announces the same info about the spinner twice.
- [ ] Bug2:[Accessibility][Usable]: Screen does not scroll down along with keyboard focus in scan mode.

**Comment by dzearing** [comment]
I think bug1 is real. We have both a label, but there is also this polite aria-live section which is causing the duplication.
