### ISSUE TITLE
Shimmer A11y Pass

### ISSUE THREAD

**Issue by awalia13** [OfficeDev/office-ui-fabric-react#8536]
Tracking all of the issues brought up with the 3/29 accessibility pass on Shimmer control
Details on individual bugs can be found on[Sharepoint](https://microsoft-my.sharepoint.com/:x:/r/personal/v-amaver_microsoft_com/_layouts/15/Doc.aspx?sourcedoc=%7B4c64e020-7be8-40cb-bcb8-8d0c27cb6cbc%7D&action=default&uid=%7B4C64E020-7BE8-40CB-BCB8-8D0C27CB6CBC%7D&ListItemId=1912&ListId=%7B395E1ECB-5002-440E-81C5-6A090E98077C%7D&odsp=1&env=prodbubble)
- [ ] Bug1:[Accessibility][Screen Reader]: Screen Reader is not able to detect shimmer, it keeps on reading 'blank'.
- [ ] Bug2:[Accessibility][Usable]: Screen does not scroll down along with keyboard focus in scan mode.

**Comment by dzearing** [comment]
Shimmer is a presentational non-focused component. It is up to the parent element to provide localized label indicators if needed. It would be irritating for a blind user to have this be a stop.
