### ISSUE TITLE
Detail Panel: No way to pass props to detail panel's pivot

### ISSUE THREAD

**Issue by JoshuaLamusga** [OfficeDev/office-ui-fabric-react#8541]
In DetailPanelPivotBody.tsx, no generic set of props is passed to the pivot it renders. This is the file used by detail panel, so I can't style the pivot individually.

**Comment by Vitalius1** [comment]
@Raghurk there are a couple of issues filed regarding the `dashboard` package. Assigning to you for triage. Thanks!

**Comment by ecraig12345** [comment]
Closing this because the dashboard package has moved to a new location.
