### ISSUE TITLE
Office UI Fabric Dropdown not displaying options list

### ISSUE THREAD

**Issue by lutherdexter** [OfficeDev/office-ui-fabric-react#8547]
Environment:
My dev environment:
-  TypeScript React 3.3.3
- Office UI Fabric 6.157.0
- Node.js
- Browser - IE11, Google Chrome Version 73.0.3683.86 and Edge

- Visual studio code

I haven't been able to reproduce the behaviour in codepen, see the same working as expected  [here](https://codepen.io/lutherdexter/pen/oOvBKP).

#### Actual behavior:
 
The chevron in the Office fabric UI dropdown control doesn't show the options list. I can scroll through items using my up/down arrow keys when the control is onFocus
 
#### Expected behavior:
 
Clicking the chevron should reveal the list of options associated to the dropdown control

#### Priorities and help requested: 
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: Blocking
 
Products/sites affected: Enterprise production site

**Comment by kkjeer** [comment]
Hi @lutherdexter, if the behavior is not replicable in a CodePen, then that unfortunately makes it difficult to debug the underlying issue. I forked your CodePen [here](https://codepen.io/kkjeer/pen/yryzEE) (I had to add React scripts in order for the pen to render), and I'm seeing the expected behavior (the options are shown when I click on the chevron). If Dropdown behaves as expected in the CodePen, on the Fabric website, and in other places where Dropdown is being used, then the problem may be elsewhere in your environment.

I'm also seeing the `onChange` callback called as expected (I see "here are the things updating..." in the console when I select an option).

**Comment by dzearing** [comment]
Same here, did the same thing https://codepen.io/dzearing/pen/QPwOGZ?editors=1010

**Comment by lutherdexter** [comment]
Hi @kkjeer,

Thanks for coming back to me.

Which react scripts did you have to add to get it to work? That's probably what I'm missing in my environment...The chevron icon in my dropdown control doesn't work  and appears somewhat distorted in positioning when my app is on desktop form factor but it does when I resize my browser to a mobile/tablet size. This behaviour is consistent for all the dropdown controls in my form (5 of them)

**Comment by dzearing** [comment]
Are you importing from `/lib/` folders? If so, icons don't get automatically added to your bundle.

Can you add this to your app?

```
import { initializeIcons } from 'office-ui-fabric-react/lib/Icons';
initializeIcons();
```

This will pull full icon support into your bundle. More details here:

https://github.com/OfficeDev/office-ui-fabric-react/wiki/Using-icons

**Comment by dzearing** [comment]
@lutherdexter also you can take a look at my codepen above, which added these:

```html
<script type="text/javascript" src="//unpkg.com/react@16/umd/react.development.js"></script>
<script type="text/javascript" src="//unpkg.com/react-dom@16/umd/react-dom.development.js"></script>

```

**Comment by dzearing** [comment]
(I highly recommend using the latest react build, at least 16.8.1 or greater.)

**Comment by lutherdexter** [comment]
Thanks David. Yes I'm importing and initialising the icons. I was however doing these on my apps.tsx file as opposed to importing in every component file where I use fabric controls.  

I'm using react build 16.8.3

I'll try importing & initialising from one of my component files and will let you know if the issue persists. 

Do I need to reference those scripts in your codepen?

**Comment by dzearing** [comment]
oh no i did mean just do that once in your app.tsx. If you are already doing that and icons aren't showing up, check network traffic in debug tools and see if there are any failures to download.

If you're building with react, you should be good to go. If you put your project on a github location, I'm happy to clone to see what you're seeing.

**Comment by lutherdexter** [comment]
I can see the chevron icon in the dropdown control. The icon just appears distorted and the control reveal dropdown options when I click it on a desktop. The only scenario where the dropdown options appear is when I resize the browser to a mobile screen size

**Comment by lutherdexter** [comment]
its on github

**Comment by dzearing** [comment]
Do you have a link to the repo?

**Comment by lutherdexter** [comment]
here [https://github.com/lutherdexter/kats/invitations](url)

**Comment by lutherdexter** [comment]
just shared access with you

**Comment by dzearing** [comment]
Ran `npm install` and `npm start` in the kats folder, and got:

```
Error: Actions must be plain objects. Use custom middleware for async actions.
dispatch
C:\git\kats\kats\node_modules\babel-loader\lib\index.js??ref--6-oneOf-2!C:\git\kats\kats\node_modules\redux\es\redux.js:200
```

**Comment by dzearing** [comment]
if you have a fix, lmk and i'll pull

**Comment by lutherdexter** [comment]
just fixed it. You are going to need use dummy data for the dropdown controls

**Comment by dzearing** [comment]
pulled, now i see this:
```
TypeError: Cannot read property 'ticket' of undefined
```

![image](https://user-images.githubusercontent.com/1110944/55679076-98f68e80-58b9-11e9-8f28-cf48f6714fed.png)
