### ISSUE TITLE
ColorPicker: external color functions library breaks AMD consumption

### ISSUE THREAD

**Issue by serkan-inci** [OfficeDev/office-ui-fabric-react#855]
- __Package version(s)__: 0.87.2
- __Browser and OS versions__: Any browser/OS

#### Describe the issue:

Getting below error when trying to use it:
Uncaught Error: Module name "color-functions/lib/css-color" has not been loaded yet for context: _

css-color library seems to be not compliant with AMD.

#### Actual behavior:

Nothing rendered.

#### Expected behavior:

ColorPicker rendered correctly.

**Comment by dzearing** [comment]
This makes sense and is a reasonable bug.

What you could do to unblock yourself:

1. Make a simple webpack project.
2. Make an index.ts that exports * from 'office-ui-fabric-react/lib/ColorPicker';
3. Bundle into an AMD bundle, and use that in your project bundling.

For us to make it purely compatible, we could also consider moving the color functions in within the color package. Convert it to typescript, let typescript produce AMD. I think we would want to split out the color-picker as its own package anyway.

This is an unfortunate side effect of many different module flavors. We have gone through the same pain in OneDrive.

I will leave this open as a bug to see what we can do about typescriptifying the color functions.

**Comment by dzearing** [comment]
This is now merged. Please feel free to try again after tomorrow's publish.
