### ISSUE TITLE
DetailsList : navigate between items and invoke them outside the component

### ISSUE THREAD

**Issue by FullStackRafik** [OfficeDev/office-ui-fabric-react#8550]
Do you have any good suggestion to navigate between items and invoke them outside the component, from a button for example.

Thanks

**Comment by kkjeer** [comment]
Hi @FullStackRafik, I'm afraid I'm not sure what you're asking. Could you provide more detail, or ideally a CodePen that illustrates what you're trying to accomplish? Thanks!

**Comment by KevinTCoughlin** [comment]
Hey @FullStackRafik, this question may be better fielded on the SharePoint Developer Documentation repository: https://github.com/SharePoint/sp-dev-docs/issues since it involves webparts and routing.

**Comment by FullStackRafik** [comment]
@kkjeer : Here is what I want to do:
DetailsList component and button, I need when I click button I can navigate between the items of the DetailsList.
@KevinTCoughlin : It's not related to Webpart and routing(please forget about that), it's related to the Fabric UI DetailList componenet and if there is a property that can set the current index like for example "initialFocusedIndex".

**Comment by KevinTCoughlin** [comment]
@FullStackRafik, if you need to programmatically set selection similar to `initialFocusedIndex` (I'm assuming given your response above) then you'll need to look at the `selection?: ISelection` prop of `DetailsList`:

https://github.com/OfficeDev/office-ui-fabric-react/blob/ce9d7d57c847078fbc0c97deb89f1c71299739ff/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.types.ts#L92

The `ISelection` interface allows one to programmatically set, toggle, clear selection among other things.

https://github.com/OfficeDev/office-ui-fabric-react/blob/ce9d7d57c847078fbc0c97deb89f1c71299739ff/packages/office-ui-fabric-react/src/utilities/selection/interfaces.ts#L44

**Comment by FullStackRafik** [comment]
Thanks for your answer, can you please give me an example about using that?

**Comment by FullStackRafik** [comment]
@KevinTCoughlin 
Butr this method doesn't trigger "_onItemInvoked".

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin
> Butr this method doesn't trigger "_onItemInvoked".

`_onItemInvoked` is only invoked on keyboard event as per its doc comment:

```ts
/** Callback for when a given row has been invoked (by pressing enter while it is selected.) */
```

Since you're programmatically controlling selection, can you also programmatically invoke `_onItemInvoked` or whichever method you need?

**Comment by FullStackRafik** [comment]
Here is my navigate function:
 navigate(direction:string)
 { 
   if (direction=="up" && this.state.lastSelected<this.state.items.length) {
     this.state.lastSelected=this.state.lastSelected+1
     // alert(this.state.lastSelected)
   }
   else  if (direction=="down" && this.state.lastSelected>0){
        this.state.lastSelected=this.state.lastSelected-1
      // alert(this.state.lastSelected)
   }
    this.Selection.setIndexSelected(this.state.lastSelected, true, true)
   this.Selection.setChangeEvents(true);
  }

-I can navigation between items by clicking a button but there are some issues, sometimes when I click "up" it goes "down" and sometimes it doesn't move.
-I don't know how can I get the item to trigger it, there is no indication about the HTMLElement in the selection object.

**Comment by FullStackRafik** [comment]
I resolved the first issue, now I can navigation between items by clicking a button (up and down), but I still don't know how can I get the item to trigger it.

**Comment by FullStackRafik** [comment]
I resolved my issues, now I can navigation between items by clicking a button (up and down), and I triggered programmatically _onItemInvoked method.

**Comment by kkjeer** [comment]
@FullStackRafik glad to hear it! If you don't have any other questions, please feel free to close this issue. Thanks!
