### ISSUE TITLE
FocusZone can sometimes not set tab-index

### ISSUE THREAD

**Issue by cnamal** [OfficeDev/office-ui-fabric-react#8551]
Hey folks,

In some cases, I noticed that the `FocusZone` doesn't set the `tab-index` to 0 correctly, as in this simple repro: https://codepen.io/namal-ms/pen/pBzbbo

Here's a summary of my investigations:

- When the children of `FocusZone` isn't initially rendered, eg by using a `List`, `FocusZone` relies on a handler it sets on the whole `window` to capture `TAB` and update the `tab-index`es.
- The handler on `window` isn't set all the time, and has the following check `_outerZones.size === 1`, where `_outerZones` is a global variable of `FocusZone`.
- The `DetailsList` has nested `FocusZone`s. For each of them, it adds itself in the global variable `_outerZones`. However, it **doesn't** remove itself from `_outerZones`, meaning `_outerZones.size > 1`. This leads to all future `FocusZone`s not adding the `window` handler.

I believe this is after the following change: https://github.com/OfficeDev/office-ui-fabric-react/pull/8421 (sorry for the blame :/, just want to make it easier for y'all)
The bug doesn't repro on 1.158.0

I believe the following code

```ts
if (!this._isInnerZone) {
  _outerZones.add(this);
}
```

should be after the while loop of `componentDidMount`, where `this._isInnerZone` is set. Something like:

```ts
while (parentElement && parentElement !== document.body && parentElement.nodeType === 1) {
  if (isElementFocusZone(parentElement)) {
    this._isInnerZone = true;
    break;
  }
  parentElement = getParent(parentElement, ALLOW_VIRTUAL_ELEMENTS);
}

>>>>Added code
if (!this._isInnerZone) {
  _outerZones.add(this);
}
>>>>

if (windowElement && _outerZones.size === 1) {
  this._disposables.push(on(windowElement, 'keydown', this._onKeyDownCapture, true));
}
```

## Codepen demonstrating the issue
https://codepen.io/namal-ms/pen/pBzbbo

This is a bug for a Microsoft website we work on, though we can work around it by setting the `tab-index` to 0 ourselves on the first element.

**Comment by dzearing** [comment]
@cnamal Thank you for the report! Investigating immediately.

**Comment by dzearing** [comment]
I believe i have a fix, but setting up a test to try and repro before i get this checked in.

**Comment by dzearing** [comment]
Validated both with a test and with your codepen. Thanks again. Will be published tonight.

**Comment by cnamal** [comment]
Awesome! Thanks @dzearing for the quick fix :)
