### ISSUE TITLE
Modal's FocusTrapZone, with FocusTrapCallout child, not behaving as expected

### ISSUE THREAD

**Issue by cnamal** [OfficeDev/office-ui-fabric-react#8552]
Hi folks,

We have a `FocusTrapCallout` inside a `Modal`, similar to what's in the following codepen: https://codepen.io/namal-ms/pen/LvEOOb

As you can see, the `FocusTrapZone` of the `Modal` doesn't work as expected, and tab focus doesn't cycle through the couple buttons in the modal, and you can get to the background button.

Is this normal? The "Dialog nested in a Panel" example in the `FocusTrapZone` [documentation](https://developer.microsoft.com/en-us/fabric#/components/focustrapzone) leads me to believe it isn't expected, but I'm not sure.

When looking for workarounds, I noticed giving the `doNotLayer` prop to the `Callout` solves the issue. Could someone please explain the implications of setting `doNotLayer` to `true`? 🙂
I'm not well versed in the layering system of Fabric unfortunately.

Apologies if this isn't the right forum for this. If so, please let me know where I should send my questions (Microsoft employee, if that changes anything ^^)

## Codepen demonstrating the issue
https://codepen.io/namal-ms/pen/LvEOOb

**Comment by JasonGore** [comment]
This looks like a recent regression with `FocusTrapZone` changes. [v6.142.0](https://codepen.io/jasongore/pen/wZaOPp) seems to work as expected.

**Comment by JasonGore** [comment]
Ok, I've done more investigation and have a clearer picture of what's going on here.

There are basically two FocusTrapZones active in the provided CodePen: one in `Modal` and one in `FocusTrapCallout`. In this case, `FocusTrapCallout` has no content, so it's trying to grab focus but has no content to put focus on. As a result, both versions _appear_ to act oddly: OUFR v6.142.0 focus falls back from FocusTrapCallout to Modal (also arguably not valid behavior) and OUFR current version lets focus wander around the page. 

However, I'm not sure this is a valid case: With a `FocusTrapCallout` having no content, what *should* be focused? `FocusTrapCallout` is demanding focus, but has nothing to focus. I'm not sure that this is a valid use case. Can you provide more details as to your use case here? 

As soon as I put some content into FocusTrapCallout, both [master](https://codepen.io/jasongore/pen/RORoox) and [v6.142.0](https://codepen.io/jasongore/pen/WWxoGP) seem to work consistently by trapping focus within `FocusTrapCallout` content.

**Comment by cnamal** [comment]
Apologies for not providing a good enough example :(. Here is a closer example to what we have: https://codepen.io/namal-ms/pen/QPEdbj

In our code, a button of the `Modal` triggers the `hidden` prop of the `Callout`

**Comment by cnamal** [comment]
Here's a repro that's even closer to our code: https://codepen.io/namal-ms/pen/xeOgyy

**Comment by JasonGore** [comment]
Hmm, I think this may be an issue with `FocusTrapCallout`. If it is `hidden`, it is still rendering the `FocusTrapZone`, which causes the breaking behavior we're seeing. I don't think `FocusTrapCallout` should be rendering the `FocusTrapZone` when `hidden` is `true`.

I've modeled how this should really behave [in this CodePen](https://codepen.io/jasongore/pen/PgzprE) where I just prevent the entire `FocusTrapCallout` (including the underlying `FocusTrapZone`) from being rendered when `isCalloutHidden` is `true`. Does this behave as you expect?

@atneik It looks like you made `FocusTrapCallout`. Do you know if there is a reason to render `FocusTrapZone` when the call out is hidden? I think it could cause navigation issues like the one reported here.

**Comment by atneik** [comment]
@JasonGore I don't think I considered this case. I don't see any issue if we prevent rendering `FocusTrapZone` if `hidden` is set to `true`

**Comment by cnamal** [comment]
@JasonGore that is indeed the workaround we are trying to implement currently, but it causes our UI tests to fail, for some obscure reason.

Could this have performance issues? In our code, the callout has a list of elements, which in theory should be short, but the user can potentially have a very long list.

**Comment by JasonGore** [comment]
We would have to implement this in a way where perf is not impacted, similar to base `Callout`. If we can't remove `FocusTrapZone` entirely without affecting perf, then we have to investigate another method for `FocusTrapCallout` to use, such as trying to disable `FocusTrapZone` via props when `hidden` is `true`.
