### ISSUE TITLE
CommandBar: Href does not work

### ISSUE THREAD

**Issue by russgove** [OfficeDev/office-ui-fabric-react#856]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Describe the issue:
I have the floowing Component
import * as React from 'react';
import { IContextualMenuItem, CommandBar } from 'office-ui-fabric-react';
import styles from './ReactNavbar.module.scss';
import { IReactNavbarProps } from './IReactNavbarProps';
export default class ReactNavbar extends React.Component<IReactNavbarProps, void> {
  private menuitems: Array<IContextualMenuItem>;
  public render(): React.ReactElement<IReactNavbarProps> {
    this.menuitems = [
      {
        key: "1",
        href: "https://mytenenat.sharepoint.com/teams/IT/BPU/",
        name: "BPI",
        title: "BPI",
      }
    ];
    return (
          <CommandBar items={this.menuitems} >
          </CommandBar>
    );
  }
}

When run the BPI item displays oin the commandbar, but is not clickable. I looked at the renderd html and it snot an href.

#### Actual behavior:

Item that gets rendered in not a link

#### Expected behavior:

Item that gets renderewd should be a link to the href

**Comment by russgove** [comment]
Hi Sourcecode got messed up above. Here it is
import * as React from 'react';
import { IContextualMenuItem, CommandBar } from 'office-ui-fabric-react';
import styles from './ReactNavbar.module.scss';
import { IReactNavbarProps } from './IReactNavbarProps';
export default class ReactNavbar extends React.Component<IReactNavbarProps, void> {
  private menuitems: Array<IContextualMenuItem>;
  public render(): React.ReactElement<IReactNavbarProps> {
    this.menuitems = [
      {
        key: "1",
        href: "https://mytenenat.sharepoint.com/teams/IT/BPU/",
        name: "BPI",
        title: "BPI",
      }
    ];
    return (
          <CommandBar items={this.menuitems} >
          </CommandBar>
    );
  }
}

**Comment by russgove** [comment]
So I see this issue was closed. Was it resolved? If so , how do I get the update?

**Comment by graham-sportsmgmt** [comment]
It's not working for me :(
