### ISSUE TITLE
Add some kind of opened / transitionend event to layer / panel / ...

### ISSUE THREAD

**Issue by alex3683** [OfficeDev/office-ui-fabric-react#8562]
**Describe the feature that you would like added**
I'd like to have an event, that fires in case a Layer (for example of a Panel) has finished its opening transition and is visible in a stable state (e.g. *onLayerOpened*). The reason is, that opening a Panel with some complex content opens with long delay and choppy in some older browsers (actually it's IE11 ...), because rendering runs in parallel with the transition.
So in order to improve user experience I'd like to open the empty Panel first and then start rendering the child components. This way the user gets instant feedback to his click and the application feels more responsive.

**What component or utility would this be added to**
Current demand comes from the Panel component, but actually this could be used wherever an animated Layer is involved.

**Have you discussed this feature with our team, and if so, who**
No.

**Additional context/screenshots**
If further information is needed, feel free to ask me :)

**Comment by kkjeer** [comment]
Hi @alex3683, would the layer prop `onLayerDidMount` work for your use case? I made a CodePen showing a simple usage of the prop (when the Panel is opened, you should see "Layer opened!" in the console). https://codepen.io/kkjeer/pen/MRwMPR

The relevant prop is passed to the Panel through its `layerProps` property:
```
<Panel
    layerProps={{onLayerDidMount: this._onLayerOpen}}
>
    Hello Panel
</Panel>
```

with the `_onLayerOpen` just making the console.log call:

```
private _onLayerOpen = (): void => {
    console.log("Layer opened!");
};
```

**Comment by alex3683** [comment]
Hi @kkjeer , I already tried that, but it fires to early. The event already occurs when the layer is mounted but still invisible. What I need is an event, that occurs when the layer is mounted and the opening animation of the layer has finished.
Your example is too simple to reproduce this, even for IE ;-)

**Comment by kkjeer** [comment]
@alex3683 thanks for the clarification. I'll keep investigating.

**Comment by kkjeer** [comment]
@JasonGore is this something that would make sense to add to the Layer component?

**Comment by JasonGore** [comment]
I'm not sure. Layer itself doesn't have any animations. If there needs to be a distinction between knowing when children are mounted and when animation ends, it may not make sense for Layer to have this capability. 

@alex3683 Is it possible to render a placeholder child and tell when it's mounted and trigger off that?

**Comment by kkjeer** [comment]
@alex3683 does @JasonGore's suggestion work for you? Otherwise, I can look into adding props like `onOpen` and `onOpened` to Panel (analogous to the existing `onDismiss` and `onDismissed`.

**Comment by alex3683** [comment]
@JasonGore @kkjeer I guess (and confirmed by testing it) a child component is mounted as soon as the Panel is starting to open, hence at the start of the opening animation. This is also true for the props `onLayerDidMount` and `onLayerMounted` of the layer. So this won't help me in this case.

I like the idea of the `onOpen` and `onOpened` props, since they should solve my problem and they are fitting counterparts to `onDismiss` and `onDismissed`. But I just saw that for Dialog, the `onDismissed` callback was deprecated. Do you know, why? Just wanted to call your attention to it, for the sake of library consistency.

**Comment by kkjeer** [comment]
@alex3683 thanks for testing and for looking at the Dialog props (appreciate your calling attention to this!) The reason the Dialog's `onDismissed` property is deprecated is that it was replaced with `modalProps.onDismissed` (so you can still pass an `onDismissed` callback to Dialog, it's just passed as part of the Dialog's `modalProps` property now).
