### ISSUE TITLE
Change the CSS of callout request

### ISSUE THREAD

**Issue by piyumi25** [OfficeDev/office-ui-fabric-react#8565]
I am using a callout as a dropdown . The callout is shown when click on the target div element. I need to remove the css of root element. How do I do that? I tried by putting styles. but not successful.
![callout](https://user-images.githubusercontent.com/33615108/55397936-fa8ac600-5564-11e9-8a47-de49a46e1288.png)

**Comment by kkjeer** [comment]
Hi @piyumi25, the CSS `style` property on the root div sets the `top` and `left` attributes based on the position of the Callout relative to its target element. It is not intended to be changed via CSS or the `styles` property, but if you truly need to override it, you can try something like this:

```
<Callout
    styles={{ root: { top: '250px !important', left: '300px !important' } }}
>
    {/*Callout children go here*/}
</Callout>
```

If this doesn't work for you, please create a CodePen to help us debug.

**Comment by piyumi25** [comment]
Thank you for your reply. when I am going to use styles I got this error.

![callout-styles](https://user-images.githubusercontent.com/33615108/55451478-b218ea00-55f0-11e9-96cb-d19ac9362436.png)

**Comment by kkjeer** [comment]
@piyumi25 which version of Fabric are you using? The `styles` Callout prop has been available since pull request #4844, version [6.0.0-beta3](https://github.com/OfficeDev/office-ui-fabric-react/releases/tag/office-ui-fabric-react_v6.0.0-beta3)

**Comment by piyumi25** [comment]
I am using this version - 5.128.2

**Comment by kkjeer** [comment]
Can you update to the latest version (or at least 6.0?)

**Comment by piyumi25** [comment]
Hi, I am creating outlook addin using office ui  fabric react. I used yeoman generator to create the addin. The default version is 5.128.2 and when I am trying to update the version using "npm update office-ui-fabric-react@latest --save" I got lot of errors. Can you help me to get rid of this?

**Comment by piyumi25** [comment]
OK thank you

**Comment by kkjeer** [comment]
Let me know if the update doesn't work for you, or please feel free to close the issue if updating fixes the problem!

**Comment by piyumi25** [comment]
I able to fix the problem after updating the office ui fabric react package. Thank you for your help.
