### ISSUE TITLE
PersonaCard component?

### ISSUE THREAD

**Issue by unindented** [OfficeDev/office-ui-fabric-react#857]
Fabric used to provide a `PersonaCard` component:

<img width="374" alt="screen shot 2017-01-20 at 16 59 56" src="https://cloud.githubusercontent.com/assets/69485/22157983/eb1fbc26-df31-11e6-9cb3-4edf202c38b7.png">

Is there a reason why it isn't included in `office-ui-fabric-react`? Should I just build it myself?

**Comment by dzearing** [comment]
It's because in O365 there is a new contact card available which is still iterating. There are plans to make it available in the component library, but I don't have an ETA.

**Comment by madhavsharmaagra** [comment]
Still no PersonaCard. Any updates on it?

**Comment by hasannaqvi83** [comment]
Guys,
Can this be used in SPFx React?
https://developer.microsoft.com/en-us/fabric-js/components/personacard/personacard
