### ISSUE TITLE
Make Toggle text clickable

### ISSUE THREAD

**Issue by ArrayKnight** [OfficeDev/office-ui-fabric-react#8577]
**Describe the feature that you would like added**

I (and several team members and test users) keep expecting to be able to click on the label of the Toggle element, as you would a radio button or checkbox. It would be great if this was the default behavior or at the very least an onRenderLabel entry point so as to be able to implement this ourselves. (similar to the onRenderHeader/Title on the GroupedDetailsList)

**What component or utility would this be added to**

Toggle

**Have you discussed this feature with our team, and if so, who**

No

**Comment by kkjeer** [comment]
Hi @ArrayKnight, clicking on the Toggle label currently changes the state of the Toggle. However, clicking the on or off text does not.

Example where clicking on the Toggle label ("Enabled and checked") toggles the Toggle:
![toggle-label](https://user-images.githubusercontent.com/6687333/55441233-f360b980-555e-11e9-9b1e-02f1a929121a.gif)

Here is a potential change where clicking on the On/Off text toggles the Toggle:
![toggle-on-off-2](https://user-images.githubusercontent.com/6687333/55441648-599a0c00-5560-11e9-82db-3e09f1a61b3e.gif)

The reason that the on/off text does not currently change the state of the Toggle is that is does not have the `htmlFor={this._id}` set (unlike the Toggle label which does). Adding `htmlFor={this._id}` to the on/off text is one potential fix, but I need to test to make sure this would not cause regressions or accessibility issues.

**Comment by ArrayKnight** [comment]
@kkjeer Sorry for the incorrect terminology (label vs text), but I'm glad you understand what I was getting at.

This seems like a good potential solution, except that I don't believe I would have access to this._id outside of the component. Maybe with some sort of ref workaround, but that would be a hassle.

And you might run into an issue with multiple competing things being the "for", but I'm eager to see what you learn.

Thanks for looking into it!

**Comment by kkjeer** [comment]
Hi @ArrayKnight, in case you're curious, my proposed fix (in pull request #8597) is to add the "for" attribute to the text as described. Having both the label and the text be "for" the same Toggle button initially produced some undesired screen reader behavior since the on/off text was read instead of the label. I mitigated this by adding "aria-labelledby" to the Toggle button to ensure that screen readers read the correct thing.

**Comment by ArrayKnight** [comment]
@kkjeer Thank you for getting this taken care of so quickly and easily
