### ISSUE TITLE
Nav: INavLinkGroup.collapseByDefault is not fully applied as expected to existing groups

### ISSUE THREAD

**Issue by gnanavelum** [OfficeDev/office-ui-fabric-react#8582]
collapseByDefault state is cached by the Nav control, doesn't always reflect what the props collapseByDefault state.

please ping me if you need a repro, I can show in the product. 

look at the screenshot red highlighted comment, (question to that comment, wondering why there is a cache(isGroupCollapsed) in place? and why it is only take state changes for new groups, what about existing groups? my fix would be to simply remove any conditioning around that isGroupCollapsed state or do a full mapping, respect all groups state changes)

![image](https://user-images.githubusercontent.com/2680177/55442345-0aa1a600-5563-11e9-8e44-1347a4e0aa85.png)

Per this code, the 'last month(24)' groups new state of false never gets picked up.

Requested priority: High, as this has bad experience in core experience of our product.

Are you willing to submit a PR to fix? Yes, send me steps to build and verify.

**Comment by jdhuntington** [comment]
Thanks @gnanavelum  - agree that this is odd behavior. 

> question to that comment, wondering why there is a cache(isGroupCollapsed) in place

I don't believe there is any longer a good reason for this. Removing the caching on component initialization seems like a great approach to fixing.

**Comment by kkjeer** [comment]
Thanks @jdhuntington! @gnanavelum if you're willing to submit a pull request with your fix, please take a look at the guidelines for cloning, building, and testing Fabric: https://github.com/officedev/office-ui-fabric-react#building-the-repo and let us know if you have any questions!

**Comment by jdhuntington** [comment]
Will be fixed by #9099 .
