### ISSUE TITLE
[Screen Reader - PowerApps - Recent Apps] In scan mode, Multiple navigation steps appears on image control under home pane

### ISSUE THREAD

**Issue by sonimishra** [OfficeDev/office-ui-fabric-react#8586]
User Experience:
User depending on screen reader might get affected as he would face difficulty while navigating and it would take time to navigate all the controls on blade if focus remains on same control also which could confuse the user about the desired elements .

Re-pro Steps:
1. Open URL: https://preview.web.powerapps.com and login using valid credentials.
2. Power Apps Homepage opens, navigate to Hamburger menu button on left and select it.
3. Pane with menu options(Home, learn, apps, create etc.) appears, navigate to home menu item and select it.
4. Page with apps appears, navigate to recent Apps tab item and select it.
5. Navigate to the app appearing under Recent Apps.
6. Verify the issue.
-->

## Actual behavior:
In scan mode, Multiple navigation steps appears on image control. When narrator focus is on image control and press down arrow key, focus remains on image control.

## Expected behavior:
In scan mode, Multiple navigation steps should not appear on image control. When narrator focus is on image control and press down arrow key,focus should move on next control and it should announce it as 'Test Mihaea name column header'.

Note:
This issue also exists with Chrome browser with JAWS in cursor mode.
This issue also exists for Apps> Org apps->Table column header.
This issue exists throughout the application.

Test Environment |  
-- | --
OS   Build: Version 1809 (OS build 17134.167)
Browser:   Edge, Chrome
Screen   Reader: Narrator, JAWS

![MAS4 2 10MultipleNavigation](https://user-images.githubusercontent.com/30456910/55458764-80f9e300-560b-11e9-936d-3e6645ccefaf.png)

**Comment by kkjeer** [comment]
Hi @sonimishra, we can't use powerapps to debug. Could you create a CodePen that demonstrates the behavior you're seeing on the affected Fabric component(s)? Thanks!

**Comment by sonimishra** [comment]
codepen sample can be  https://developer.microsoft.com/en-us/fabric#/components/detailslist.

**Comment by KevinTCoughlin** [comment]
@natalieethell has had similar feedback about column header and assistive technology navigation. I wonder if this is related?

How does this map to the [W3 ARIA spec](https://www.w3.org/TR/wai-aria-1.1/)? I want to fix this if its blocking users.

**Comment by natalieethell** [comment]
@KevinTCoughlin ah, I haven't seen any issues like this one brought up before. The column header bugs I've seen are a little different.

Looking into it a bit, though, it seems like this behavior might be a result of the screen reader. 

This [data grid example on the W3C site](https://www.w3.org/TR/2017/NOTE-wai-aria-practices-1.1-20171214/examples/grid/dataGrids.html) has similar behavior for the "Description" cells that contain a link. It takes two navigation steps to get through this cell. DetailsList has the same behavior for cells with links, too (ex: the "name" cells in [this DetailsList example](https://developer.microsoft.com/en-us/fabric#/components/detailslist/variablerowheights)).
