### ISSUE TITLE
Add support for style in SetupBanner's props.

### ISSUE THREAD

**Issue by DanteMustDie** [OfficeDev/office-ui-fabric-react#8587]
I am using SetupBanner to implement a frontend user experience. I found that not like other components, SetupBanner does not have a "style" in its props and it makes me hard to set my own styles. Hope it can support style in props.

**Comment by kkjeer** [comment]
Hi @DanteMustDie, could you clarify which Fabric component you're using? I don't see a SetupBanner component in our documentation (https://developer.microsoft.com/en-us/fabric#/components). Thanks!

**Comment by DanteMustDie** [comment]
Hi @kkjeer, it is under office-ui-fabric-react/packages/dashboard/src/components/SetupBanner/

**Comment by kkjeer** [comment]
@DanteMustDie thanks for the clarification. I'll reach out to dashboard developers to see if there is a plan to support styled components. In the meantime, could the `className` property be useful for your scenario? Something like:

```
<SetupBanner className={mergeStyles({background: 'red'})}>...</SetupBanner>
```

**Comment by DanteMustDie** [comment]
@kkjeer thanks for your reply. I will try. Only using className will not cover all the inside divs if the css selector is limited to classname selector.
