### ISSUE TITLE
In high contrast, Panel isn't distinguishable from the background 

### ISSUE THREAD

**Issue by cnamal** [OfficeDev/office-ui-fabric-react#8588]
Hi folks,

When in high contrast, it appears that the Panel isn't distinguishable from the main content.

Expected:
![image](https://user-images.githubusercontent.com/9625284/55479174-ccb58800-561d-11e9-94d9-ece2d6ee9a43.png)
(image taken from https://github.com/OfficeDev/office-ui-fabric-react/pull/7155)

Actual:
![image](https://user-images.githubusercontent.com/9625284/55479256-f79fdc00-561d-11e9-8859-2f8b30af1182.png)

As you can see, the border of the Panel isn't visible. The regression came in [6.141.0](https://github.com/OfficeDev/office-ui-fabric-react/releases/tag/office-ui-fabric-react_v6.141.0), though I haven't investigate any further. 

Thanks :)

**Comment by cnamal** [comment]
@betrue-final-final maybe the thicker border you mentioned in https://github.com/OfficeDev/office-ui-fabric-react/pull/7155#issuecomment-479558719 could be done as part of the fix for this bug? Not a hard requirement, just an FYI :)

**Comment by kkjeer** [comment]
Thanks for reporting this @cnamal. This seems to be a recent regression; I'll follow up to look for a fix.
