### ISSUE TITLE
Callback for changing month when both DayPicker & MonthPicker is visible 

### ISSUE THREAD

**Issue by paddymccallan** [OfficeDev/office-ui-fabric-react#8592]
**Describe the feature that you would like added**
When the DayPicker and MonthPicker are both set to visible; the DayPicker has priority for the callback onSelectDate. Selecting the month when DayPicker is not visible triggers the callback successfully. Feature would be to have a callback that is triggered when either one is selected.

**What component or utility would this be added to**
Calendar

**Have you discussed this feature with our team, and if so, who**
No

**Comment by micahgodbolt** [comment]
@lorejoh12 Is this something you've considered or come across?

**Comment by lorejoh12** [comment]
We've never had a use case for this. The Calendar component was designed such that if both the month picker and day picker are visible, the user is trying to select a specific day. If they select a month, that's more of an internal navigation- it'll change the date range shown inside the Calendar, but you haven't actually "selected" a specific date yet, so no callbacks fire.

When in month picking mode (so only month picker is visible), you ARE selecting a month when you click on it, hence the callback.

What's the use case for having a callback when internal navigation happens?
