### ISSUE TITLE
reselect row with onActiveItemChanged detaillist

### ISSUE THREAD

**Issue by nealYangVic** [OfficeDev/office-ui-fabric-react#8593]
How to reselect a row with onActiveItemChanged , for example I want to open a model again. What's the best way to do it?

**Comment by nealYangVic** [comment]
Basically after you click a row with onActiveItemChanged, the row get focused, you cannot use onActiveItemChanged to trigger the same row again.

For example, I want to open a modal when click specific row, after click it once, open modal, close modal. I cannot click that row to trigger onActiveItemChanged again

**Comment by KevinTCoughlin** [comment]
> For example, I want to open a modal with specific row data when click specific row, after click it once, open modal, close modal. I cannot click that row to trigger onActiveItemChanged again

@nealYangVic Codepen repros as per our issue template help us triage and unblock you. Can you provide one perhaps by forking this DetailsList example: https://codepen.io/kevintcoughlin/pen/MxByGw

I need to understand your scenario better before recommending a solution. Specifically what your intent is by triggering `onActiveItemChanged` a _second time_. Perhaps that is not the correct method to use for your use case.

**Comment by nealYangVic** [comment]
@KevinTCoughlin here we go, https://codepen.io/nealyangvic/pen/KYVmWV
I use onActiveItemChanged to control the panel, 

current behavior: when I click one item like item 2 to open the panel, then close panel, then click item 2, cannot open the panel or trigger onActiveItemChanged again.

expect behavior: after close panel and click item 2, panel should reopen (onActiveItemChanged should be triggered)

**Comment by nealYangVic** [comment]
I feel like this should be very normal behavior for a grid, when I click a row I want to open a modal

**Comment by kkjeer** [comment]
Hi @nealYangVic, this codepen (https://codepen.io/kkjeer/pen/WWwxqX) shows a workaround using a function that renders each row with an `onClick` handler to open the Panel when a row is clicked. We're investigating a modification to DetailsList that would enable this behavior by default, but hopefully this is an acceptable workaround in the meantime.

**Comment by nealYangVic** [comment]
@kkjeer Thanks for the answering, based on this answer I look document more, find out onRenderRow maybe more appropriate for this, because onRenderItemColumn could be rewritten by detail render https://codepen.io/nealyangvic/pen/yrOVYL 

Thanks!
