### ISSUE TITLE
[RTL - CommandBar] Items and overflow menu is not showing in reverse direction and all items in RTL for some languages

### ISSUE THREAD

**Issue by raghavendra-kodimala** [OfficeDev/office-ui-fabric-react#8607]
### Environment Information 
 
- __Package version(s)__: (5.122.3) 
- __Browser and OS versions__: (Chrome: 72.0.3626.121 (Official Build) (64-bit), Microsoft Edge: 44.17763.1.0, Microsoft Windows 1809)

#### Actual behavior:
 CommandBar Items is not displayed in reverse direction in Hebrew language and some of the items are moved to overflow menu, though the items in the overflow menu, is defined. 
Note: It is displayed correctly in Arabic.
#### Expected behavior:
 All the items to be displayed in reverse direction in all RTL languages. No extra item to be moved to overflow menu

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (o)
 
Requested priority: (High) 
 
Products/sites affected: (if applicable)

**Comment by micahgodbolt** [comment]
Is it possible to use the new 6.0 command bar? It was completely refactored and should better support RTL.
