### ISSUE TITLE
Non-blocking Panel is blocking text from being entered into search box

### ISSUE THREAD

**Issue by rslavey** [OfficeDev/office-ui-fabric-react#8625]
### Environment Information 
 
- __Package version(s)__:   

- __Browser and OS versions__: Chrome / Windows 10

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/randyslavey/pen/mgERoy
 
#### Actual behavior:
 
When isBlocking is set to false on a Panel, expected behavior is to be able to interact with elements in page. While buttons are clickable, entering text in a search box is not.
 
#### Expected behavior:
 
Able to type in a search box while a non-blocking panel is up. I'm not sure if this is an issue with the search box or with the panel.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: SharePoint Online / spfx

**Comment by kkjeer** [comment]
@rslavey thanks for reporting; this definitely seems like a bug. I'll keep investigating to see if I can find a fix.
