### ISSUE TITLE
Move Nav to legacy components package

### ISSUE THREAD

**Issue by jdhuntington** [OfficeDev/office-ui-fabric-react#8627]

**Comment by FuturistiCoder** [comment]
Hello,
I want to know which component should I use instead if Nav is moved to legacy.
I tried to find the guideline for fabric 7 without success.

**Comment by jdhuntington** [comment]
@FuturistiCoder For the initial release of Fabric 7 the `@uifabric/legacy`'s `Nav` component is still the one to use. The syntax/API remains the same as with the current version of Fabric (6.x), but we expect to release one after the initial release of Fabric 7 that is more composable. Does this package breakout cause any issues for you?

**Comment by FuturistiCoder** [comment]
@jdhuntington No. I just want to try Fabric 7. Thanks for the info.
