### ISSUE TITLE
Flexbox settings don't work in List component. Seems to not fill the available container vertically.

### ISSUE THREAD

**Issue by Rick-Kirkham** [OfficeDev/office-ui-fabric-react#8631]
The List component ignores flexbox settings when rendering child items. Notice in the CodePen below: 
(1) although both `justifyContent` and `alignItems` are set to `align-end`, the items are not in the lower right of the container as they should be. Setting them to `center` does not center the items.
(2) Although the List is set to `flex: 1` it does not fill up the container vertically with red. In fact, if you add another item to the items, it expands the container downward, which indicates that it is treating the vertical height of the container as just the sum of the heights of the child items. That's exactly what `flex: 1` is supposed to prevent.

### Environment Information 
 
- __Package version(s)__: **How do I find this?**
- __Browser and OS versions__: (Edge, Windows 10 build 17763)

### Please provide a reproduction of the bug in a codepen:

[Flex List](https://codepen.io/micahgodbolt/pen/zbVzLj?editors=1010)
 
#### Actual behavior:
 
flexbox settings are ignored in List component
 
#### Expected behavior:
 
flexbox works in List component

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No 
 
Requested priority: High
 
Products/sites affected: Microsoft NDA, so I can't say.

**Comment by micahgodbolt** [comment]
the style tag is applied to the root element. The children are placed into another child div. I THINK you should be able to use `getPageStyle` to apply styles in this case. We could certainly make this easier and more consistent using slots.

**Comment by dzearing** [comment]
This `List` component is for rendering virtualized content; it will divide the rendered items up into pages. Are you trying to position the `List` itself, or the items it renders?

You can always use flexbox on each individual cell. Or, if you're not rendering many items, just use a `forEach` loop instead of a `List` to have a more fixed DOM structure without the pages inbetween the container and children.

**Comment by kkjeer** [comment]
Hi @Rick-Kirkham, I forked your CodePen (https://codepen.io/kkjeer/pen/pBNPBm) and changed some of the styles. In the screenshot below, the List has its items in the lower right corner, and it expands to fill the height of its parent div (I set the height of the parent div to 400px).

<img width="870" alt="list-codepen" src="https://user-images.githubusercontent.com/6687333/55748791-6309f500-59f4-11e9-93e2-1e7b9a662ae6.png">
