### ISSUE TITLE
Fabric UI react upgrade issues

### ISSUE THREAD

**Issue by FullStackRafik** [OfficeDev/office-ui-fabric-react#8637]
When I upgrade the package to the latest versions:
npm i office-ui-fabric-react@latest
 I get some errors like:
DefaultButton doesn't have properties: id, style, onClick...

**Comment by jdhuntington** [comment]
Hi @FullStackRafik - Sorry you're running into this issue. Would you be willing to share the details of your project, specifically:
 - Typescript version from `package.json`
 - Which version of office-ui-fabric-react was installed (again from `package.json`) and which version you were previously using
 - The import statement you are using for `DefaultButton`

Thanks!

**Comment by FullStackRafik** [comment]
Hi @jdhuntington 
Here is the package.json:
{
  "name": "Crud-Solution",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "~1.1.0",
    "@microsoft/sp-lodash-subset": "~1.1.0",
    "@microsoft/sp-office-ui-fabric-core": "^1.4.1",
    "@microsoft/sp-webpart-base": "~1.1.0",
    "@pnp/common": "^1.3.1",
    "@pnp/logging": "^1.3.1",
    "@pnp/odata": "^1.3.1",
    "@pnp/sp": "^1.3.1",
    "@types/es6-promise": "0.0.33",
    "@types/react": "0.14.46",
    "@types/react-addons-shallow-compare": "0.14.17",
    "@types/react-addons-test-utils": "0.14.15",
    "@types/react-addons-update": "0.14.14",
    "@types/react-dom": "0.14.18",
    "@types/rx-lite": "^4.0.6",
    "@types/webpack-env": "1.13.1",
    "@uifabric/styling": "^6.45.2",
    "bootstrap": "^4.3.1",
    "core-js": "^3.0.1",
    "jquery": "^3.3.1",
    "moment": "^2.24.0",
    "react": "15.4.2",
    "react-accessible-accordion": "^2.4.5",
    "react-bootstrap-table": "^4.3.1",
    "react-dom": "15.4.2",
    "react-icons": "^3.5.0",
    "reactstrap": "^7.1.0",
    "rx-lite": "^4.0.8"
  },
  "resolutions": {
    "@types/react": "0.14.46"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.1.0",
    "@microsoft/sp-module-interfaces": "~1.1.0",
    "@microsoft/sp-webpart-workbench": "~1.1.0",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1",
    "typescript": "^3.3.4000"
  }
}
- The import statement you are using for DefaultButton:
import  DefaultButton from 'office-ui-fabric-react/lib/Button'; 
    <DefaultButton id="CancelBtn"  
                style={{display: 'none' }}
                onClick={() =>this.cancel() }
                >  
                <span className={styles.label}>Cancel</span>
              </DefaultButton>  

Now I want to upgradeoffice-ui-fabric-react to 6.x.x.x.x.

Thanks

**Comment by joschect** [comment]
@FullStackRafik it looks like you're not depending directly on office-ui-fabric-react, instead you're depending on sp-office-ui-fabric-core which is a bundled subset of office-ui-fabric-react, do you know which version that is on?

**Comment by joschect** [comment]
@FullStackRafik Actually I don't think that oufr is included in that core bundle, do you know where it is being included from?

**Comment by FullStackRafik** [comment]
@joschect said:
> It looks like you're not depending directly on office-ui-fabric-react, instead you're depending on sp-office-ui-fabric-core which is a bundled subset of office-ui-fabric-react, do you know which version that is on?
1.4.1

@joschect said

> Actually I don't think that oufr is included in that core bundle, do you know where it is being included from?
What do you mean by your question?

Knowing that I'm using SP2016 on-premises, What package I should use in this case?

Thanks

**Comment by joschect** [comment]
I think that you want office-ui-fabric-react-bundle but I'm not sure. Someone on your team more familiar with sp-client might be able to give you a better idea.

**Comment by FullStackRafik** [comment]
@joschect I'm the technical lead of the project that's why I'm asking about that.

**Comment by FullStackRafik** [comment]
I installed  office-ui-fabric-react, here is my **package.json**:
```
{
  "name": "crud-project",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "~1.1.0",
    "@microsoft/sp-lodash-subset": "~1.1.0",
    "@microsoft/sp-webpart-base": "~1.1.0",
    "@pnp/common": "^1.3.1",
    "@pnp/logging": "^1.3.1",
    "@pnp/odata": "^1.3.1",
    "@pnp/sp": "^1.3.1",
    "@types/es6-promise": "0.0.33",
    "@types/react": "0.14.46",
    "@types/react-addons-shallow-compare": "0.14.17",
    "@types/react-addons-test-utils": "0.14.15",
    "@types/react-addons-update": "0.14.14",
    "@types/react-dom": "0.14.18",
    "@types/rx-lite": "^4.0.6",
    "@types/webpack-env": "1.13.1",
    "bootstrap": "^4.3.1",
    "core-js": "^3.0.1",
    "jquery": "^3.3.1",
    "minimatch": "^3.0.4",
    "minimist": "0.0.8",
    "mkdirp": "^0.5.1",
    "moment": "^2.24.0",
    "office-ui-fabric-react": "^6.165.0",
    "popper.js": "^1.14.7",
    "react": "15.4.2",
    "react-accessible-accordion": "^2.4.5",
    "react-bootstrap-table": "^4.3.1",
    "react-dom": "15.4.2",
    "react-icons": "^3.5.0",
    "rx-lite": "^4.0.8"
  },
  "resolutions": {
    "@types/react": "0.14.46"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "~1.1.0",
    "@microsoft/sp-module-interfaces": "~1.1.0",
    "@microsoft/sp-webpart-workbench": "~1.1.0",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1",
    "typescript": "^2.2.2"
  }
}

```
But I have always the same problems.
Any help please?

**Comment by FullStackRafik** [comment]
I think that the the latest stable versionof oufr is v5.122.1 and in this case compatible with React 15 which is what SPFx uses.

**Comment by joschect** [comment]
@FullStackRafik I did a local install with the packages that you provide. In the package.json.lock I noticed that there are a bunch of different versions of office-ui-fabric-react being loaded. It looks like some are coming from microsoft/sp-webpart-workbench and @microsoft/office-ui-fabric-react-bundle and the version that's required is 2.31.0 which is really low. There are a few other places that I see that version being imported and it's likely that the multiple versions is causing the issue that you're experiencing.

**Comment by FullStackRafik** [comment]
@joschect said:
>  it's likely that the multiple versions is causing the issue that you're experiencing

Yes, I know that is about packages versions, but I need to know which packages are causing the issue.

@microsoft/sp-webpart-workbench and @microsoft/office-ui-fabric-react-bundle are created byt SPFx when I generate the project in the first time.

**Comment by joschect** [comment]
@FullStackRafik this isn't an issue with office-ui-fabric-react. Rather it's a problem with upgrading in  SPFx since it relies on packages that depend on older versions of office-ui-fabric-react. Those dependencies will need to get upgraded to the latest version of office-ui-fabric-react if you want the entire package to use latest. You can go through and find those packages by looking through something like the package.lock or package.shrinkwrap file. 

You can ask on the Sharepoint [stackoverflow](https://sharepoint.stackexchange.com/) for help troubleshooting issues with SPFx. If SPFx does not upgrade to a newer version of office-ui-fabric-react then a newer version cannot be used with it.
