### ISSUE TITLE
Support null value for onRenderHeader in Panel (or other render functions)

### ISSUE THREAD

**Issue by brandonthomas** [OfficeDev/office-ui-fabric-react#8649]
This is mostly about dev experience so I understand if you guys won't fix it. Ideally, if I don't want to render an area of a component it would be great if I could simply pass in null as a value. The current behavior requires a function that returns null.

**What component or utility would this be added to**
Panel brought this up but I could see other features using this.

**Have you discussed this feature with our team, and if so, who**
Nope

**Comment by JasonGore** [comment]
I worry that `null` values aborting default render behavior is subtle and not easily distinguishable from `undefined` values that don't abort default render behavior. We've had partners in the past passing in `null` in a similar manner to `undefined` and I think this could lead to subtle insidious bugs.

Could you define a helper that returns null and just pass that in? That'll avoid the need of you having to do anonymous functions everywhere. For example:

```tsx
const NullRender = () => { return null; }

public render() {
  return (<Panel onRenderHeader={NullRender} />);
}
```

**Comment by brandonthomas** [comment]
Yah, at the moment that's essentially what we're doing. We need to move ours to a central place and then evangelize it. To me making sure everyone knows that there is a central one is the hardest part. Whereas `null `is pretty well known (I'd hope). I understand that many folks don't understand the nuances between `undefined `and `null `though so that's a valid point.

**Comment by joschect** [comment]
@brandonthomas Thanks for the input! It's a good idea that's worth considering. For the short term I don't think that we're going to switch over as it would require a lot of changes to different components. We're also looking into [slots](https://github.com/OfficeDev/office-ui-fabric-react/pull/7308) which will possibly replace the onRenderMethods in the future.
