### ISSUE TITLE
Scroll bar is appearing for More actions available for groups in IE11 browser only

### ISSUE THREAD

**Issue by shivasai09** [OfficeDev/office-ui-fabric-react#8653]
### Environment Information 

- __Browser : IE11 only
- __office-ui-fabric-react :"^6.164.2"

### reproduction of the bug:
 
1. Login to WUS portal https://wusportalprv.office.com/adminportal/home#/groups 
2. Go to Groups
3. Select any group
4. Click More action(3 dots) and notice

#### Actual behavior:
 
Scroll bar is appearing for More action
 
#### Expected behavior:
 
Scroll bar should not appear

#### Priorities and help requested:
 
 
Requested priority: Low
 
Products/sites affected: https://wusportalprv.office.com/adminportal/home#/groups

![image](https://user-images.githubusercontent.com/33802398/55800004-4e128c00-5af0-11e9-92aa-c5a673359c46.png)

**note**: component used to  render popup in the above picture is Callout

**Comment by joschect** [comment]
@shivasai09 Thanks for submitting this! Do you know if this happens to all callouts in IE, or only in this specific instance?

**Comment by joschect** [comment]
Also @shivasai09 could you reproduce this in a codepen?

**Comment by shivasai09** [comment]
@joschect  , as far as my knowledge it is only happening at that specific instance.
as you asked here's a codepen:-  https://codepen.io/anon/pen/eovvyW

**note**: codepen will not work properly in IE , though it shows the output. so to see the the code which i have written, open the above url in the browser other that IE. and also note that i have made some css changes , to replicate the exact scenario.

**Comment by joschect** [comment]
@shivasai09 thanks for adding the codepen! However, when I open it in codepen it works as expected, I don't see a scrollbar. (See screenshot) https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcodepen.io%2Fanon%2Fpen%2FeovvyW&data=02%7C01%7Cjoschect%40microsoft.com%7C47a8df120e4746b0b14b08d6bda9c095%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636904934110924206&sdata=qO%2BEygfAkkntGn615Lbn%2Fdg41Iq20Wtwr%2BotXKwm7d4%3D&reserved=0

**Comment by shivasai09** [comment]
hey @joschect  i will share you the diff file instead of codepen. hope this will help you.

```diff
diff --git a/packages/office-ui-fabric-react/src/components/Button/examples/Button.Action.Example.tsx b/packages/office-ui-fabric-react/src/components/Button/examples/Button.Action.Example.tsx
index 17d7ac4d2..f2c8ae2d3 100644
--- a/packages/office-ui-fabric-react/src/components/Button/examples/Button.Action.Example.tsx
+++ b/packages/office-ui-fabric-react/src/components/Button/examples/Button.Action.Example.tsx
@@ -9,7 +9,7 @@ export class ButtonActionExample extends React.Component<IButtonProps> {
   }
 
   public render(): JSX.Element {
-    const { disabled, checked } = this.props;
+    // const { disabled, checked } = this.props;
 
     const getClassNames = classNamesFunction<IButtonBasicExampleStyleProps, IButtonBasicExampleStyles>();
     const classNames = getClassNames(getStyles, {});
@@ -17,14 +17,86 @@ export class ButtonActionExample extends React.Component<IButtonProps> {
     return (
       <div className={css(classNames.example)}>
         <ActionButton
-          data-automation-id="test"
-          iconProps={{ iconName: 'AddFriend' }}
-          allowDisabledFocus={true}
-          disabled={disabled}
-          checked={checked}
-        >
-          Create account
-        </ActionButton>
+          split={false}
+          iconProps={{ iconName: 'MoreVertical' }}
+          menuProps={{
+            onRenderMenuList: (menuListProps: any, defaultRender: any): JSX.Element => {
+              menuListProps.items.map((menuItem: any) => {
+                menuItem.onRender = (item: any, dismissMenu: () => void): JSX.Element => {
+                  item.onItemClick = (event: React.MouseEvent<HTMLElement>): void => {
+                    dismissMenu();
+                    // menuItem.onItemClick && menuItem.onItemClick(actionItem.item, event);
+                  };
+                  return (
+                    <ActionButton
+                      split={false}
+                      iconProps={item.iconProps}
+                      title={item.title}
+                      ariaDescription={item.text}
+                      aria-label={item.text}
+                      onClick={item.onItemClick}
+                      data-is-focusable={true}
+                    >
+                      {item.text}
+                    </ActionButton>
+                  );
+                };
+              });
+
+              return <div>{defaultRender(menuListProps)}</div>;
+            },
+            items: [
+              {
+                key: 'Editgroupsname',
+                text: 'Edit group name',
+                title: 'Edit group name',
+                iconProps: {
+                  iconName: 'AccountManagement'
+                }
+              },
+              {
+                key: 'Editgroupdescription',
+                text: 'Edit group description',
+                title: 'Edit group description',
+                iconProps: {
+                  iconName: 'Assign'
+                }
+              },
+              {
+                key: 'Editgroupmembers',
+                text: 'Edit group members',
+                title: 'Edit group members',
+                iconProps: {
+                  iconName: 'Assign'
+                }
+              },
+              {
+                key: 'Editgroupowners',
+                text: 'Edit group owners',
+                title: 'Edit group owners',
+                iconProps: {
+                  iconName: 'Assign'
+                }
+              },
+              {
+                key: 'DeleteGroup',
+                text: 'Delete group',
+                title: 'Delete group',
+                iconProps: {
+                  iconName: 'Delete'
+                }
+              },
+              {
+                key: 'StarGroup',
+                text: 'Star',
+                title: 'Star this group',
+                iconProps: {
+                  iconName: 'FavoriteStar'
+                }
+              }
+            ]
+          }}
+        />
       </div>
     );
   }
```
**SCREEN CAPTURE**

![scroll](https://user-images.githubusercontent.com/33802398/55933689-d9546480-5c4b-11e9-9a3f-6f077e8de0fd.gif)

**Comment by joschect** [comment]
@shivasai09 is the issue with ContextualMenu or callout? The example you have is modifying contextualmenu.

**Comment by joschect** [comment]
@shivasai09 I can reproduce this problem using the code that you pasted in, however, I'm still investigating to get to the root of the issue. I'm not sure if the problem is in the buttons, the menu, or in the way that they're being combined.

**Comment by shivasai09** [comment]
@joschect  may be this link might just help you.
https://github.com/philipwalton/flexbugs

**Comment by shivasai09** [comment]
@joschect  any update on this?

**Comment by micahgodbolt** [comment]
BTW, codepen editor doesn't work in IE11. If you create (or fork) a codepen, you can open it in debug mode, and this works in IE11. Note though that debug links don't last forever, so I'm not going to post one here.

![image](https://user-images.githubusercontent.com/1434956/71699550-eafb1080-2d74-11ea-9cc4-ae138c23093d.png)


But in checking this out I don't see any current issue with IE11 in 7.78.0.

![ie11](https://user-images.githubusercontent.com/1434956/71699566-fb12f000-2d74-11ea-9785-6c6a586c12ef.gif)
