### ISSUE TITLE
Name of the dialog is read twice upon opening the dialog box

### ISSUE THREAD

**Issue by SriNandiniG** [OfficeDev/office-ui-fabric-react#8673]
## Actual behavior:
Dialog box name must be read only once
## Expected behavior:
Currently, the name of the dialog is read twice please refer to the code snippet mentioned.
Its reading dialog box name twice followed by close button button close
[DialogBoxSnippet.txt](https://github.com/OfficeDev/office-ui-fabric-react/files/3062877/DialogBoxSnippet.txt)

**Comment by joschect** [comment]
@SriNandiniG thanks for including the code snippet! Would you mind putting it into a codepen to help our investigation? Thanks!

**Comment by joschect** [comment]
I've tried to reproduce it in a basic [codepen](https://codepen.io/slimemold/pen/qwrQxa) and I was unable to reproduce the issue.
