### ISSUE TITLE
DetailsList checkbox column not reading

### ISSUE THREAD

**Issue by jamilihari** [OfficeDev/office-ui-fabric-react#8675]
### Bug Report

Are you willing to submit a PR to fix?  Yes

Requested priority: Normal 

Products/sites affected: NA

#### Describe the issue:

Here we used Fabric.DetailsList Grid, In that Grid we have checkbox in first column which is not reading by Narrator/NVDA but in the sample given in Fabric.DetailsList it is reading the checkbox in the first column.

please check the my attached code snippet .

#### Actual behavior:

Narrator/NVDA is not reading the Checkbox present in the Fabric.DetailsList as "column1 checkbox".
Narrator is not reading as "column1 checkbox"
but NVDA reading as "column1"

#### Expected behavior:

[DetailsList code.txt](https://github.com/OfficeDev/office-ui-fabric-react/files/3063398/DetailsList.code.txt)
Narator/NVDA will be read as "column1 Checkbox" from the DetailsList.Fabric

**Comment by joschect** [comment]
@jamilihari Thanks for submitting this, while we look into this could you create a codepen that demonstrates this?
