### ISSUE TITLE
DetailsList column header sorting order is not Reading in NVDA

### ISSUE THREAD

**Issue by jamilihari** [OfficeDev/office-ui-fabric-react#8676]
### Description

Here we used Fabric.DetailsList, the sorting order is not mentioning for every click of space on column Headers of DetailsList in NVDA Screen Reader.
I attached code snippet, please check it,.

 
#### Actual behavior:
 
For Fabric.DetailsList we have columns when we navigate to each column header through clicking on Tab button ,once Tab entered to the DetailsList  then i used down Arrow key to navigate to the column Headers and after clicking space on column header, grid is sorting but not reading everytime by NVDA when we click as sorting in Ascending order or Descending order, NVDA reading sometimes only and sorting order is changing every click of space.

#### Expected behavior:
 
NVDA should read Sorting order(Ascending/Descending) of column for every click of space on column header of Fabric.DetailsList.
[SortingOrderNotMentioning_NVDA.txt](https://github.com/OfficeDev/office-ui-fabric-react/files/3063922/SortingOrderNotMentioning_NVDA.txt)
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: NA

**Comment by joschect** [comment]
@jamilihari Hey! Thanks for submitting this issue. Would you be able to make a codepen that demonstrates this? If you want one codepen could be used for this issue and #8675 so you don't have to make 2 separate ones. It would help us investigate!

**Comment by jamilihari** [comment]
Hi Team,
we don't use codepen to implement our UI
hence its unable to share codepen link for that

But I can explain scenario step by step.

Here we are using Fabric.DetailsList, in that we have columns.
For that columns I added aria labels for column ascending and descending orders as "sortAscendingAriaLabel" and "sortDescendingAriaLabel".

Then we are using Narrator and NVDA Screen Readers for readings, if move Near to these columns through Tab and Arrow buttons. Screen Readers are not reading aria labels for Sorting.

**Comment by KevinTCoughlin** [comment]
> Hi Team,
> we don't use codepen to implement our UI
> hence its unable to share codepen link for that
> 
> But I can explain scenario step by step.
> 
> Here we are using Fabric.DetailsList, in that we have columns.
> For that columns I added aria labels for column ascending and descending orders as "sortAscendingAriaLabel" and "sortDescendingAriaLabel".
> 
> Then we are using Narrator and NVDA Screen Readers for readings, if move Near to these columns through Tab and Arrow buttons. Screen Readers are not reading aria labels for Sorting.

@jamilihari thank you for the explanation. We ask for Codepen repros as it helps isolate the problem and expedites triage and debug of the issue. You might consider forking this Codepen and adding the pieces that you've described above: https://codepen.io/kevintcoughlin/pen/zXRmKQ

Some follow-up questions:

What browser? I assume Narrator + Edge and NVDA w/ Chrome?
