### ISSUE TITLE
Dropdown: flag to override mobile layout

### ISSUE THREAD

**Issue by abhishek1214** [OfficeDev/office-ui-fabric-react#8678]
**Describe the feature that you would like added**

**What component or utility would this be added to**
Dropdown

**Have you discussed this feature with our team, and if so, who**
Mica Godbolt
**Additional context/screenshots**

I think there should be a way to opt out of this layout if required in mobile for a dropdown. We are catering to group of audience who are to computing and this layout may seem a bit daunting to them.

 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/7584903/55898056-6e6d4400-5bdf-11e9-90c8-b8976eaa4432.png)

**Comment by micahgodbolt** [comment]
Thanks for logging this! We'll take a look at the work involved here. If it's something we can quickly tackle we will, otherwise we'll get it on our backlog and get a dev asigned to it for future development.

**Comment by joschect** [comment]
@abhishek1214 It looks like we should already have a property that can handle this. The dropdown supports `responsiveMode` as a prop and the description has it as being able to override the default behavior. However it doesn't look like it's working as designed. I think we need to put a fix in and then you should be able to just use that to achieve the same effect!

**Comment by joschect** [comment]
Here's the [codepen](https://codepen.io/slimemold/pen/BERBYQ?editors=1111) which demonstrates how the prop should work and how it doesn't seem to work as commented.

**Comment by micahgodbolt** [comment]
reponsiveMode :D 

![image](https://user-images.githubusercontent.com/1434956/55921514-fd636780-5bb1-11e9-853b-9b824a1d09f1.png)

The bottom one works.

**Comment by joschect** [comment]
@micahgodbolt do I not know how to spell? lol

**Comment by joschect** [comment]
@abhishek1214 `responsiveMode={2}` is the equivalent of `responsiveMode={ResponsiveMode.large}` when using the ResponsiveMode enum.
