### ISSUE TITLE
SwatchColorPicker hover issue for ColorPickerGridCell

### ISSUE THREAD

**Issue by Dalimil** [OfficeDev/office-ui-fabric-react#8681]
In the current SwatchColorPicker, hovering over the exact border between the color and the background makes it flicker between selected/unselected states very fast.

I believe this might be due to the fact that each cell is a border-box with 50% border radius. Adding padding + border on hover makes it relayout itself and this causes the sudden flicker between the selected-unselected states.

Can be reproduced here: https://developer.microsoft.com/en-us/fabric#/components/swatchcolorpicker

![demo](https://user-images.githubusercontent.com/4202539/55917641-ed915680-5ba4-11e9-9c0a-2b4cd9e4136f.gif)

**Comment by joschect** [comment]
@Dalimil Thanks for submitting this! It's pretty clearly a bug. Since you're being awesome and working on a fix I'll go ahead and assign it to you! Thanks a bunch!

**Comment by micahgodbolt** [comment]
I can't seem to repro this in current release. Are you still experiencing the issue on our site?

![colorpicker](https://user-images.githubusercontent.com/1434956/71693721-0b6d9f80-2d62-11ea-9f0a-d328f89a8d79.gif)

**Comment by xugao** [comment]
@Dalimil - i can't repro either like micah said. pls confirm

**Comment by Dalimil** [comment]
@xugao @micahgodbolt Yep, I think it has already been fixed.
