### ISSUE TITLE
PivotBase item null check bug

### ISSUE THREAD

**Issue by frevds** [OfficeDev/office-ui-fabric-react#8695]
There is a bug here: 

![image](https://user-images.githubusercontent.com/5341447/55949295-8df18480-5c52-11e9-9a10-9ac7f15cb17b.png)

If a PivotItem is null instead of undefined (e.g. by using conditional statement such as the following), a runtime NullReferenceException occurs, because typeof(null) === "object" by definition. 

![image](https://user-images.githubusercontent.com/5341447/55949450-eaed3a80-5c52-11e9-87aa-4e6c2ee246d3.png)

I can imagine this bug can sit on several other places in the code base.

**Comment by joschect** [comment]
@frevds Thanks for submitting this issue! I'm currently unable to reproduce this in a [codepen](https://codepen.io/slimemold/pen/QPgWqr?editors=1111). Would you mind taking a look and trying to repro it? 

To help with our investigation could confirm what version of office-ui-fabric-react  you're using?

**Comment by frevds** [comment]
@joschect - Yes, in the latest Fabric this issue does not happen, because the children are filtered out earlier. 

In _getPivotLinks, in my (older) version I find this line, iterating over the children directly: 
```    React.Children.map(props.children, (child: any, index: number) => {```

The latest codebase reads like this instead: 
```    React.Children.map(React.Children.toArray(props.children), (child: any, index: number) => {```

This does not return falsey values, so the problematic line does not run into a problem. 

However, the next line still contains a bug, stricly speaking, and should be fixed (even though it won't cause an error), because typeof(null) is always object, and you cannot access a member on a null-object (the compiler should complain here, apparently the necessary check has been disabled). Also, this issue could then be found elsewhere. 

```      if (typeof child === 'object' && child.type === PivotItemType) {```

But good to know the latest Fabric won't immediately run into an issue here.

**Comment by frevds** [comment]
PS: I'm using the version that comes with SharePoint Framework SPFx 1.8.0, so others might run into that problem. Anyhow, it is apparently fixed, so I'm closing the issue. Thanks though for your reply.
