### ISSUE TITLE
ChoiceGroup not maintaining checked values across pages after migrating to spfx 1.8 with office-ui-fabric-react version 6.143.0

### ISSUE THREAD

**Issue by pk091990** [OfficeDev/office-ui-fabric-react#8696]
Hi Team,

Recently I've migrated my custom webpart to SPFX 1.7.1 to 1.8 with office-ui-fabric-react 5.131.0 to 6.143.0, react 16.7.0 and typescript 3.3.4. It seems that ChoiceGroup is not maintaining selected radiobutton values across pages.

In the below image, Suppose this is my 1st Question , If I'll select any option(Yes/No) of the 1st Question, click Next button. Select any option of 2nd question, click Previous, then previously selected option of 1st Question is not maintained which was not the case earlier.
Could you please confirm if any changes has been done in the component in the latest release.

![image](https://user-images.githubusercontent.com/46436213/55951823-cb1b3e00-5c75-11e9-9d7c-f6ebff6020fe.png)

**Comment by joschect** [comment]
@pk091990 Hi, can you clarify a little bit more about what you mean when you say "pages"? Is that using something in react? Or a different custom component. Could you add a codepen that includes a reproduction of this?

There have been a lot of changes to ChoiceGroup since 5.131.0.
