### ISSUE TITLE
Accessibility issue in FocusTrapZone

### ISSUE THREAD

**Issue by cnamal** [OfficeDev/office-ui-fabric-react#8697]
[Accessibility insights](https://accessibilityinsights.io/docs/en/web/overview/) shows the following error with `FocusTrapZones`:
>[aria-hidden-focus](https://dequeuniversity.com/rules/axe/3.2/aria-hidden-focus?application=msftAI): ARIA hidden element must not contain focusable elements  [WCAG 4.1.2](https://www.w3.org/WAI/WCAG21/Understanding/name-role-value.html)

I believe the issue is on the following line:
https://github.com/OfficeDev/office-ui-fabric-react/blob/24937f2580a0bd608c7114d1afd43b4536f8c74d/packages/office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx#L74

I don't think the `aria-hidden` is necessary since the `div`s it's applied to are empty, though I might be mistaken.

**Comment by joschect** [comment]
@cnamal Thanks for submitting this ticket! I'll take a look and see if I can figure out why that got added in the first place.

**Comment by joschect** [comment]
Looks like this was added in #8274

**Comment by joschect** [comment]
This was added because scan mode should not be stopping at the bumpers. I'll test and verify that it needs to be there

**Comment by cnamal** [comment]
Resolved by #9019
