### ISSUE TITLE
TextField has no onKeyDown event? how to detect enter key

### ISSUE THREAD

**Issue by peterremote1980** [OfficeDev/office-ui-fabric-react#8699]
Hi
   TextField has no onKeyDown event? how to detect enter key
thanks
Peter

**Comment by joschect** [comment]
@peterremote1980 thanks for your question! Textfield does support onKeyDown, it passes the native events through automatically. It doesn't show up in the documentation but you can use it. See this [codepen](https://codepen.io/slimemold/pen/VNWwvL?editors=1111) as an example!
