### ISSUE TITLE
Panel OnDismiss is called twice

### ISSUE THREAD

**Issue by dcowen91** [OfficeDev/office-ui-fabric-react#8701]
### Environment Information 
 
- __Package version(s)__: Latest (6.165.1)
- __Browser and OS versions__:  Chrome 73, Windows 10

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/anon/pen/vMmoJR?&editable=true

#### Actual behavior:

When closing a panel, the onDismiss function is called twice. Once before dismissing and once after.
 
#### Expected behavior:
 
OnDismiss is only called once.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
Requested priority: Normal

**Comment by joschect** [comment]
@dcowen91  Thanks for submitting this issue and for including the codepen! This looks like it's a problem, I'll dig into a bit more and see if I can figure out why!

**Comment by joschect** [comment]
Looks like it was introduced in #8274
