### ISSUE TITLE
VerticalDivider is not themeable via context

### ISSUE THREAD

**Issue by swese44** [OfficeDev/office-ui-fabric-react#8702]
### Environment Information 
 
- __Package version(s)__: 6.153.0

### Please provide a reproduction of the bug in a codepen:
 
VerticalDivider uses global `getTheme()` instead of customizable. If an app uses Customizer to set theme via React Context then the VerticalDivider is unable to pick up the app's theme.
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Divider/VerticalDivider.tsx#L7

#### Actual behavior:
VerticalDivider is not themeable via Customizer theme
 
#### Expected behavior:
VerticalDivider should use the theme provided on React Context

#### Priorities and help requested:
Are you willing to submit a PR to fix? No
 
Requested priority: Low (we have a workaround)
 
Products/sites affected: Yammer

**Comment by joschect** [comment]
@swese44 thanks for submitting this! This is definitely a good request, we'll get it added to our backlog since the divider should be themeable.

**Comment by Vitalius1** [comment]
@swese44, you might wanna try and see if the `Separator` [component](https://developer.microsoft.com/en-us/fabric#/components/separator) can replace the `VerticalDivider` for your use case. It uses the proper theme color and it offers you more features if needed 😄
