### ISSUE TITLE
SearchBox onSearch popup action blocked by IE11 popup blocker

### ISSUE THREAD

**Issue by rocketraman** [OfficeDev/office-ui-fabric-react#8703]
### Environment Information 
 
- __Package version(s)__: 6.165.1
- __Browser and OS versions__: IE11, Windows 10

### Please provide a reproduction of the bug in a codepen:
 
This is only a problem on IE11. Here is the codepen:

https://codepen.io/anon/pen/qwjERm?editors=1111
 
#### Actual behavior:
 
When typing something into the search box and hitting enter, the IE11 popup blocker triggers.

In Chrome, the popup blocker does not trigger and the expected behavior is fine.
 
#### Expected behavior:
 
When typing something into the search box and hitting enter, it should open www.google.com and run the search.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No
 
Requested priority: (Blocking, High, Normal, Low)  High

**Comment by joschect** [comment]
@rocketraman I have tested this out locally and I cannot reproduce this issue. I wasn't able to get codepen to show the searchbox in ie so I used npm start. Is it still reproing for you? Most browser have a way to allow popups from known sites.

**Comment by rocketraman** [comment]
@joschect Ok, this is so weird... now that I try it again, with exactly the same code, it is working fine. The only thing that changed is that I applied a bunch of Windows updates. Super-weird. In any case, I'll go ahead and close this, and re-open if it happens again. Sorry for the noise.

**Comment by rocketraman** [comment]
@joschect  Reopening, as I can reproduce. When you tried your repro, were you typing into the search box and hitting enter to search and were you running against a real host instead of localhost?

I have attached a repro project you can run with `npm start`. Note that it doesn't block popups when running against `localhost:3000`, so you need to map that to a real host name. A fast way to do that is via `ngrok http 3000`.

Full repro:

```
yarn install
set BROWSER=iexplore
yarn start
ngrok http 3000
// go to ngrok https URL
// type into the search bar and hit enter
```

Note that, yes, I'm aware I can ask the user to allow popups, but this code is actually running inside Office as an add-in, so the user experience is very badly affected with the IE popup blocker.

[fabric-issue-searchbox-8703.zip](https://github.com/OfficeDev/office-ui-fabric-react/files/3087967/fabric-issue-searchbox-8703.zip)

**Comment by KevinTCoughlin** [comment]
@rocketraman, in the Codepen above, the code is using `window.open` which causes a location change on the host frame (browser tab) that IE11 blocks. Is that correct?

If so, that code invoking `window.open` is in the application layer not the UI library. I'm unsure how we can resolve this.

**Comment by rocketraman** [comment]
@KevinTCoughlin yes, that's right. It is possible this is a bug in IE and not in Fabric. The way a browser pop-up blocker is supposed to work is that it is supposed to allow the action if it is in direct response to a user action. And in fact, in Chrome that is exactly the way it works. Clicking either the button, or tapping Enter, are both user actions, and thus Chrome allows the window to open without being blocked.

However, in IE, clicking the button opens the popup without any issue, but tapping Enter does not, even though the latter is clearly a user-initiated action.

If this is a bug in IE, and there is no workaround possible in Fabric, then that is fine, and this can be closed. Ideally, you would raise a bug internally with the IE team though, to correct this behavior.

**Comment by joschect** [comment]
@rocketraman I believe IE 11 is only accepting security critical fixes at this point since it is being sunset and replaced by Edge. This definitely seems to be a problem with the IE browser since all other browsers, including Edge, work as expected.

**Comment by rocketraman** [comment]
@joschect And good riddance to IE11 :-) However, unfortunately Office 365 still uses it for its task pane display :-( Perhaps you should advocate internally for Office 365 desktop applications to use Edge instead of IE?

**Comment by dzearing** [comment]
So, this is what we should do here:

SearchBox is soaking enter keypresses even when not used. We will fix this to only call `stopPropagation` if we've done work (called the `onSearch` callback.)

This should enable you to use a `<form>` element to achieve the behavior you want:

https://www.w3schools.com/html/html_forms.asp

```tsx
        <form action='http://lmgtfy.com/' method="get" target='_blank'>
            <SearchBox name="q" label="Label" />                           
        </form>
```

IE11 will have no problem with this because it's user initiated, unlike javascript which could execute without the user's permission. @joschect is making a fix right now.
IE11 will

**Comment by dzearing** [comment]
@rocketraman hope this addressed your issue. Sorry for the delay.
