### ISSUE TITLE
ExtendedPeoplePicker loses keyboarding when hitting itemLimit

### ISSUE THREAD

**Issue by lorejoh12** [OfficeDev/office-ui-fabric-react#8704]
### Environment Information 
 
- __Package version(s)__: latest (codepen will be from 6.165.1) 
- __Browser and OS versions__: Edge and Chrome at least

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/anon/pen/oOwjvK?&editable=true
took the controlled ExtendedPeoplePicker from https://fabricweb.z5.web.core.windows.net/oufr/6.165.1/#examples/extendedpeoplepicker, and added a single prop, itemLimit={1}
 
#### Actual behavior:
 
Type text in input, select person in dropdown
focus is still in the input well, arrow right to select the newly-added person
use Delete key to remove them
focus is still in input well- type letter "a" and see popup with suggestions. Try to arrow up and down between the suggestions, can't.
 
#### Expected behavior:
 
Expect that arrowing still works

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes, but I'd like some discussion on what the expected behavior is here to make sure I don't accidentally break something
 
Requested priority: Normal
 
Products/sites affected: OWA (weather location lookup uses this component and is affected by this bug)

some extra details:
based on my investigation, this is caused by the removal/adding of the <input> element in BaseExtendedPicker.tsx when the itemLimit is reached.

BaseFloatingPicker has a reference to the input, and when it gets initialized, it adds its own "keydown" event listener, and sets a "didBind" state.

However, when you get to the itemLimit (in this case 1), the BaseExtendedPicker rerenders and removes the input element. When you delete the item, the input element comes back, but the BaseFloatingPicker never saw that- it still has didBind=true in it's state. So on next rerender, it avoids adding a new eventListener because it thinks the old one still exists.
 
Possible solution might be to notify the BaseFloatingPicker when its props.inputElement gets invalidated (so it can set the state back to didBind: false).

**Comment by joschect** [comment]
@lorejoh12 Thanks for submitting this and including a codepen! This definitely repro's, we'll get it into our backlog and take a look at it.

**Comment by joschect** [comment]
This appears to have been fixed in the latest version of fabric. The [codepen](https://codepen.io/slimemold/pen/xxxyEro?editors=0010) no longer reproduces it.
