### ISSUE TITLE
Icons not updating when sent from Script#

### ISSUE THREAD

**Issue by ZacharyBabbitt** [OfficeDev/office-ui-fabric-react#8716]
### Environment Information 
 
- __Package version(s)__: 6.159.0

### Please provide a reproduction of the bug in a codepen:
 

Due to Script# nature of this bug, I am not sure how to create a repro in codepen

When sending icons in the data parameter from Script#, combo boxes won't update their icons correctly. This is due to shallowCompare not returning true when the icons are updated and therefore not re-rendering the icon. 

#### Actual behavior:
 
Icons are not updated when changed via Script#, rather they are only updated when combobox item is being hovered over with the cursor
 
#### Expected behavior:
 
Icons change when updated via Script# code, instead they only change when hovered over

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal
 
Products/sites affected: Excel Online

Note: I'll be submitting a PR shortly against this issue

**Comment by joschect** [comment]
@ZacharyBabbitt Thanks for submitting a pr and this issue! Since it seems like you're on top of this I went ahead and assigned it to you.
