### ISSUE TITLE
Tooltip: doesn't dismiss for disabled button

### ISSUE THREAD

**Issue by ezambra** [OfficeDev/office-ui-fabric-react#872]
### Bug Report

- __Package version(s)__: master
- __Browser and OS versions__: Issue repros on Microsoft Edge and Chrome browsers. It does NOT repro on Firefox.

#### Describe the issue:

On a disabled button, a tooltip does not get dismissed after moving the mouse pointer out of the button.

#### Actual behavior:

Tooltip does not get dismissed on a disabled button.

#### Expected behavior:

Tooltip gets dismissed on a disabled button after mouse pointer has been moved out of the element.

### If applicable, please provide a codepen repro:

Here's the code that repros the issue from the Office UI Fabric React examples included in the demo pages:
![code](https://cloud.githubusercontent.com/assets/25305030/22216324/7b6ab1fa-e153-11e6-8693-5d1b21949fa2.PNG)

**Comment by micahgodbolt** [comment]
Can't currently repro this in Edge or Chrome

https://codepen.io/micahgodbolt/pen/rjvBLr

**Comment by ezambra** [comment]
Confirmed bug is now fixed in office-ui-fabric-react_v1.3.7-9-ge12b5e4 for Chrome, Firefox and Edge.
