### ISSUE TITLE
Fix deprecated lifecycle methods

### ISSUE THREAD

**Issue by jdhuntington** [OfficeDev/office-ui-fabric-react#8743]
- [ ] apps/fabric-website/src/components/App/App.tsx
- [ ] date-time/src/components/Calendar/Calendar.base.tsx
- [ ] date-time/src/components/Calendar/CalendarDay/CalendarDay.base.tsx
- [ ] experiments/src/components/Chiclet/Chiclet.base.tsx
- [ ] experiments/src/components/Shimmer/Shimmer.base.tsx
- [ ] experiments/src/components/Tile/Tile.tsx
- [ ] experiments/src/components/TilesList/TilesList.tsx
- [ ] experiments/src/components/VirtualizedList/VirtualizedList.tsx
- [ ] experiments/src/utilities/BaseComponentMin.ts
- [ ] experiments/src/utilities/BaseState.tsx
- [X] ~legacy/src/components/Nav/Nav.base.tsx~ (wontfix)
- [ ] office-ui-fabric-react/src/components/Autofill/Autofill.tsx
- [ ] office-ui-fabric-react/src/components/Autofill/Autofill.types.ts
- [x] office-ui-fabric-react/src/components/Breadcrumb/Breadcrumb.base.tsx
- [ ] office-ui-fabric-react/src/components/Calendar/Calendar.tsx
- [ ] office-ui-fabric-react/src/components/Calendar/CalendarDay.tsx
- [ ] office-ui-fabric-react/src/components/Callout/CalloutContent.base.tsx
- [x] office-ui-fabric-react/src/components/Checkbox/Checkbox.base.tsx
- [ ] office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroup.base.tsx
- [ ] office-ui-fabric-react/src/components/Coachmark/Coachmark.base.tsx
- [ ] office-ui-fabric-react/src/components/Coachmark/PositioningContainer/PositioningContainer.tsx
- [ ] office-ui-fabric-react/src/components/ColorPicker/ColorPicker.base.tsx
- [ ] office-ui-fabric-react/src/components/ColorPicker/ColorRectangle/ColorRectangle.base.tsx
- [ ] office-ui-fabric-react/src/components/ColorPicker/ColorSlider/ColorSlider.base.tsx
- [ ] office-ui-fabric-react/src/components/ComboBox/ComboBox.tsx
- [ ] office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.base.tsx
- [ ] office-ui-fabric-react/src/components/DatePicker/DatePicker.base.tsx
- [ ] office-ui-fabric-react/src/components/DetailsList/DetailsList.base.tsx
- [x] office-ui-fabric-react/src/components/DetailsList/DetailsList.test.tsx
- [ ] office-ui-fabric-react/src/components/DetailsList/DetailsRow.base.tsx
- [ ] office-ui-fabric-react/src/components/DocumentCard/DocumentCardTitle.base.tsx
- [ ] office-ui-fabric-react/src/components/Dropdown/Dropdown.base.tsx
- [ ] office-ui-fabric-react/src/components/ExtendedPicker/BaseExtendedPicker.tsx
- [ ] office-ui-fabric-react/src/components/FloatingPicker/BaseFloatingPicker.tsx
- [ ] office-ui-fabric-react/src/components/FloatingPicker/Suggestions/SuggestionsControl.tsx
- [ ] office-ui-fabric-react/src/components/FocusTrapZone/FocusTrapZone.tsx
- [ ] office-ui-fabric-react/src/components/GroupedList/GroupHeader.base.tsx
- [ ] office-ui-fabric-react/src/components/GroupedList/GroupedList.base.tsx
- [ ] office-ui-fabric-react/src/components/Image/Image.base.tsx
- [ ] office-ui-fabric-react/src/components/Layer/Layer.base.tsx
- [ ] office-ui-fabric-react/src/components/List/List.tsx
- [x] office-ui-fabric-react/src/components/List/ListPage.tsx
- [ ] office-ui-fabric-react/src/components/Modal/Modal.base.tsx
- [ ] office-ui-fabric-react/src/components/OverflowSet/OverflowSet.base.tsx
- [ ] office-ui-fabric-react/src/components/Persona/PersonaCoin/PersonaCoin.base.tsx
- [ ] office-ui-fabric-react/src/components/Popup/Popup.tsx
- [ ] office-ui-fabric-react/src/components/Rating/Rating.base.tsx
- [ ] office-ui-fabric-react/src/components/ResizeGroup/ResizeGroup.base.tsx
- [ ] office-ui-fabric-react/src/components/SearchBox/SearchBox.base.tsx
- [ ] office-ui-fabric-react/src/components/SelectedItemsList/BaseSelectedItemsList.tsx
- [ ] office-ui-fabric-react/src/components/Shimmer/Shimmer.base.tsx
- [ ] office-ui-fabric-react/src/components/Shimmer/Shimmer.test.tsx
- [ ] office-ui-fabric-react/src/components/SpinButton/SpinButton.tsx
- [ ] office-ui-fabric-react/src/components/SwatchColorPicker/SwatchColorPicker.base.tsx
- [ ] office-ui-fabric-react/src/components/TextField/MaskedTextField/MaskedTextField.tsx
- [ ] office-ui-fabric-react/src/components/TextField/TextField.base.tsx
- [x] office-ui-fabric-react/src/components/Toggle/Toggle.base.tsx
- [ ] office-ui-fabric-react/src/components/pickers/BasePicker.tsx
- [ ] utilities/src/hoist.ts

**Comment by KevinTCoughlin** [comment]
FYI @jdhuntington I don't think the following line item is applicable, but rather a reference in an in-line comment:

```
office-ui-fabric-react/src/components/DetailsList/DetailsList.test.tsx
```

https://github.com/OfficeDev/office-ui-fabric-react/blob/ef7ccb8a9f91fe0829a7cf7e1fb7a2e4c58f62b0/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.test.tsx#L407

**Comment by JasonGore** [comment]
Replaced by #4613.
