### ISSUE TITLE
Selection count is undefined by default

### ISSUE THREAD

**Issue by speray** [OfficeDev/office-ui-fabric-react#8747]
### Environment Information 
 
- __Package version(s)__: 6.167.1 

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/anon/pen/BEYmwE
 
#### Actual behavior:
 
```js
const selection = new Selection();
const count = selection.count; // count is undefined
 ```

#### Expected behavior:
 
count is 0.
If this is expected, typescript definition should report count as number | undefined.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Low

**Comment by micahgodbolt** [comment]
This is the interface the OP is refering to:

https://github.com/OfficeDev/office-ui-fabric-react/blob/e4e90ac74e1eb66844765437438bfb7cfa0df03c/packages/office-ui-fabric-react/src/utilities/selection/interfaces.ts#L14

Selection implements ISelection. So we either need to change this to number | undefined, or have some starting value for count. 

![image](https://user-images.githubusercontent.com/1434956/56308049-2f695200-60fb-11e9-9ac3-9c34ae8754e8.png)

**Comment by ecraig12345** [comment]
This seems like a bug--I see no reason count shouldn't be initialized to 0. My only question (since I'm not familiar with Selection) is whether there's any case where items can be initially selected when the Selection is created, and therefore count should be > 0.

**Comment by KevinTCoughlin** [comment]
> This seems like a bug--I see no reason count shouldn't be initialized to 0. My only question (since I'm not familiar with Selection) is whether there's any case where items can be initially selected when the Selection is created, and therefore count should be > 0.

It seems like Selection initializes the selected items array as an empty array:

https://github.com/OfficeDev/office-ui-fabric-react/blob/e4e90ac74e1eb66844765437438bfb7cfa0df03c/packages/office-ui-fabric-react/src/utilities/selection/Selection.ts#L55

So zero _should be_ a safe value to initialize as. cc: @ThomasMichon
