### ISSUE TITLE
Why does Scrollable pane have zindex of 1

### ISSUE THREAD

**Issue by LiangMingChen** [OfficeDev/office-ui-fabric-react#8757]
### Environment Information 
https://github.com/OfficeDev/office-ui-fabric-react/blob/e83f082e86ab8a599f298dc1dfe343981bbebee5/packages/office-ui-fabric-react/src/components/ScrollablePane/ScrollablePane.styles.ts#L17

That make every thing very hard to try to other people to have loading indicator on top of it.
 

- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by LiangMingChen** [comment]
![image](https://user-images.githubusercontent.com/3789716/56334705-4f763100-614e-11e9-9eb7-60ddefd72018.png)

**Comment by joschect** [comment]
@LiangMingChen thanks for submitting this! It looks like it's a bug and we're already working on a fix!

**Comment by LiangMingChen** [comment]
Note that have zindex is a force layering from blink (chrome rendering engine.)
https://en.wikipedia.org/wiki/Blink_(browser_engine)

It also force developer who use it to have to counter act on the layering. (that is everything on top it to avoid DOM removal, Say you want to show search result is no item. when you need to hid it without destroying the whole table. (thus couple hundreds of DOM need delete and recreate it back then Scrollable will have to reculated again.

**Comment by KevinTCoughlin** [comment]
@LiangMingChen, z-index doesn't invoke hardware-acceleration, right? That's the only rationale I can think of for this being there in the first place. But to my knowledge the transform and similar CSS properties are the only ones that do that.

**Comment by LiangMingChen** [comment]
It create a new layer that rendering engine need to go through.  And once you are there, every component start to do n+1, n+2.  n + 10 etc. It is a slipper slop. it quickly become unmanageable.  It is best to avoid to do zindex in the first place. 
chrome used to have layer paneling view (not sure they remove it or hide it somewhere.,
https://www.google.com/search?q=chrome+developer+tools+3d+view
https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/reference#layers

Yes, it is on a different core/thread than javascript engine.  But it is still consuming the CPU and Memory
If you need more information, it is worthwhile to contact new Edge team ...

it is best to use implicit DOM order. (that latter DOM Element will render on top of earlier DOM Element).
Especially in the component level.   Reuseable components are  best not to use it and Application to composed it base on implicit DOM order. 
On rare situation then Application Author have a chance to managed it.

For the reference.
https://github.com/OfficeDev/office-ui-fabric-react/blob/14c515ba0c134a9bed877751972bc0071bd849d5/packages/styling/src/styles/zIndexes.ts#L2

So if I want to over lay a Div, while Nav DOM is buidling up (so user can't click on it.), Application author have to use Zindex >=1 .  If it is 2, then it create another layer   It is not only slower to render, and 
Case and point.
I can't image there is actually a z index of 1,000,000
https://github.com/OfficeDev/office-ui-fabric-react/blob/14c515ba0c134a9bed877751972bc0071bd849d5/packages/styling/src/styles/zIndexes.ts#L6

Then Oh, I need to beat it, so I have anohter , 1000,000 + 1
https://github.com/OfficeDev/office-ui-fabric-react/blob/14c515ba0c134a9bed877751972bc0071bd849d5/packages/styling/src/styles/zIndexes.ts#L7
