### ISSUE TITLE
Get the default value of Persona.initialsColor that is automatically assigned from text

### ISSUE THREAD

**Issue by nikpan** [OfficeDev/office-ui-fabric-react#8770]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: (Normal) 

Products/sites affected: (if applicable)

#### Describe the issue:

We can set the background color for the initials in Persona and PersonaCoin. If not set it will automatically pick a color based on the text. Currently, there is no way to look at what the automatically assigned color is.
An example use case scenario for this would be- You have multiple users active on a document and you want to show their cursor position in the document using the color assigned to their persona.

**Comment by joschect** [comment]
@nikpan Do you want to have the color returned from something like a callback? If you want to have that level of control you can always just pass them all down from the top so that way you know about it.

**Comment by ecraig12345** [comment]
There's a function `initialsColorPropToColorCode` in `packages/office-ui-fabric-react/src/components/Persona/PersonaInitialsColor` which appears to be used internally to get the color. However, it's not currently exported at the top level and therefore not recommended for use by external consumers (things not exported at the top level may be moved/renamed within a minor version bump). We could consider exporting either that function, or something similar with a more generic name/signature.

**Comment by nikpan** [comment]
Exporting initialsColorPropToColorCode would work. That way the caller can keep up with the changes coin color themes.

**Comment by ecraig12345** [comment]
Thinking about this more, I'm not sure exporting the function is the best approach. A possibly-better approach would be to add a `color` property (or similar) to the `IPersona` and `IPersonaCoin` which returns the current color. (It might also be appropriate to return undefined if the color isn't being used in the UI.)

@Markionium @mtennoe @jakob101 Any thoughts on which approach you'd prefer? And do you know how the `color` property approach would be implemented with the new Persona/PersonaCoin in experiments?

@nikpan Any thoughts on which way would be easier for you to consume?

If I do export the function, I'd update the name and signature as follows (could also use named parameters):
```ts
function getPersonaInitialsColor(props: Pick<IPersonaProps, 'primaryText' | 'text' | 'initialsColor'>): string;
```

**Comment by mtennoe** [comment]
I am not sure which I prefer. Exposing a callback or property for retrieving the set color on the component has the clear benefit that it hides the internal calculation of the color, which can change since there is no external contract on the color selection (as an example we will update the color pallette in fabric 7). However, it is also a question on when the consumer should call this callback, depending on property changes, etc, which needs to be handled with life cycle functions. This is ofc. solvable by the consumer, but that means it might be nicer to just export `getPersonaInitialsColor` and let the consumer call it. I am currently leaning towards the callback solution though

**Comment by nikpan** [comment]
In my scenario the properties do not change. I would prefer a function like `getPersonaInitialsColor` because that way I can set the property tree in my container once and just look at the property tree for values whenever I need them.

**Comment by mtennoe** [comment]
Exposing `getPersonaInitialsColor` also has the benefit of being more easily testable (with the most basic unit tests) and a more expected pattern overall. Would love to hear some input from @Markionium and @jakob101 as well

**Comment by ecraig12345** [comment]
Finally made PR #9225 to address this issue--so sorry about the delay!
