### ISSUE TITLE
Add variant of BaseComponent which extends React.PureComponent

### ISSUE THREAD

**Issue by ipip2005** [OfficeDev/office-ui-fabric-react#8798]
**Describe the feature that you would like added**
I have some components that extend BaseComponent, and I want them to leverage React.PureComponent for performance boost. But BaseComponent by default extends React.Component. We want to avoid writing customized code in "shouldComponentUpdate". Is it possible for OUIFR to add a variant of BaseComponent which extends React.PureComponent? 

**What component or utility would this be added to**
BaseComponent

**Have you discussed this feature with our team, and if so, who**
No

**Comment by Vitalius1** [comment]
adding @dzearing as I know there is work being done towards deprecating the `BaseComponent`.

**Comment by dzearing** [comment]
That's right, we're trying to remove usage of BaseComponent, and have been going to down the list of components to kill usage a bit at a time.

If you have specific components you'd like us to prioritize and/or think shoudl be subclassing PureComponent (or using React.memo in latest react), let us know.

**Comment by dzearing** [comment]
Closing issue, as we won't be adding a wrapper around PureComponent, and instead will be removing BaseComponent usage.
