### ISSUE TITLE
Detail List: Allow flexibility to not show shadow on hover of Headers

### ISSUE THREAD

**Issue by AkshanshSrivastava03** [OfficeDev/office-ui-fabric-react#880]
### Bug Report

- __Package version(s)__: 1.2.2
- __Browser and OS versions__: NA
#### Describe the issue:
Hovering on Details list header shows me a shadow. Is there any means to get rid of that?

#### Actual behavior:
Shadow comes on hover

**Comment by dzearing** [comment]
You shouldn't see a shadow on hover... can you provide more info? Browser/OS/screenshot would really help. If you could inspect the DOM in chrome, you might find the culrpit css selector that you're talking about; that would help even more.

Also if you'd like to customize the headers, have a couple of options:

1. custom headers; you can throw anything you want in the header content. There is a sample of doing that in the docs.

2. css overrides; you can do things like:
```css
.ms-GroupHeader:hover {
  background: red;
}
```

**Comment by cschleiden** [comment]
@AkshanshSrivastava03 we have some problems with leaking styles in VSTS and OfficeFabric. If you ping me at cschleid we can look at it together.
