### ISSUE TITLE
DetailsList set selection with keyboard

### ISSUE THREAD

**Issue by emkessle** [OfficeDev/office-ui-fabric-react#8808]
My DetailsList needs to be keyboard accessible. I am using selection={this._selection} to manage selection with mouse clicks and that is working correctly. I can use the up and down arrow keys to move focus between the items in the list but pressing space and enter does not fire the selection event. I have tried using onItemInvoked which fires correctly on Enter, but there is no way to set the Selection object's selected value. It won't update the 'selected' item's styles. 

I need to make this component keyboard accessible but I'm not sure how to make the Selection object work for both mouse click and keyboard click.

**Comment by KevinTCoughlin** [comment]
Hey @emkessle, thanks for your report. Have you taken a look at some of the DetailsList examples that maintain their own `Selection` instance? One example being https://codepen.io/kevintcoughlin/pen/XQPmBG?editors=0010

In the above example, I can select multiple items via `CTRL + SHIFT + SPACE` on Windows. If you are still facing problems, can you fork the above Codepen and provide a repro of your scenario?

**Comment by emkessle** [comment]
Hi @KevinTCoughlin, that codepen example does help demonstrate my issue (I'm just using a SelectionMode.single list). If you press Enter when using the arrow keys to navigate to an item, the onItemInvoked method is triggered but the state doesn't get updated like it does with a mouse click. I need Enter to be treated the same as click in order to be accessible. And currently, Enter doesn't update the this._selection.getSelection()[0] value.

**Comment by KevinTCoughlin** [comment]
> I need Enter to be treated the same as click in order to be accessible.

Interesting, I know a number of W3 ARIA examples treat `SPACE` as the command to un/select items, not `ENTER`. So it might be worth reviewing that requirement. 

Unfortunately, W3 ARIA's "Advanced Data Grid w/ Selection" remains unimplemented, https://www.w3.org/TR/wai-aria-practices/examples/grid/dataGrids.html.

The W3 ARIA's Listbox multi-select example only un/selects on `SPACE`, tho it is not a 1-1 comparison, see https://www.w3.org/TR/2017/WD-wai-aria-practices-1.1-20170628/examples/listbox/listbox.html.

Anyway, let me see if there's a workaround for `DetailsList` if you do indeed need to support this..

**Comment by KevinTCoughlin** [comment]
@emkessle does this modified Codepen unblock you? https://codepen.io/kevintcoughlin/pen/XQPmBG?editors=0010

I've modified `onItemInvoked` to toggle selection via `Selection`'s `toggleIndexSelected` method:

https://github.com/OfficeDev/office-ui-fabric-react/blob/5153c8096c10d9c87221733d0aec9c141324cb06/packages/office-ui-fabric-react/src/utilities/selection/Selection.ts#L386

**Comment by emkessle** [comment]
It would certainly be better if the selection was only set on Enter and not on every up and down arrow action but I think this example should meet the basic Accessibility standards. Thank you for your help! I didn't know about this._selection.toggleIndexSelected().

**Comment by KevinTCoughlin** [comment]
> It would certainly be better if the selection was only set on Enter and not on every up and down arrow action

@emkessle, this is supported in my testing using `selectionZoneProps`, here's the modified Codepen: https://codepen.io/kevintcoughlin/pen/XQPmBG?editors=0010 and associated diff:

```diff
diff --git a/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Basic.Example.tsx b/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Basic.Example.tsx
index 0365d2c11..f9d02e997 100644
--- a/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Basic.Example.tsx
+++ b/packages/office-ui-fabric-react/src/components/DetailsList/examples/DetailsList.Basic.Example.tsx
@@ -73,6 +73,7 @@ export class DetailsListBasicExample extends React.Component<{}, IDetailsListBas
             setKey="set"
             layoutMode={DetailsListLayoutMode.fixedColumns}
             selection={this._selection}
+            selectionZoneProps={{ isSelectedOnFocus: false, selection: this._selection }}
             selectionPreservedOnEmptyClick={true}
             ariaLabelForSelectionColumn="Toggle selection"
             ariaLabelForSelectAllCheckbox="Toggle selection for all items"
```

https://github.com/OfficeDev/office-ui-fabric-react/blob/108330f1118fafab4a13a8a2d18a0cd6bdf8639d/packages/office-ui-fabric-react/src/utilities/selection/SelectionZone.tsx#L51

We should probably document this better. I believe @natalieethell's work will help here.

**Comment by KevinTCoughlin** [comment]
I'm going to let the bot close this issue since a solution has been provided and we're tracking improving visibility for the future.
