### ISSUE TITLE
Checkbox: Unexpected Hover/Click behaviour

### ISSUE THREAD

**Issue by canmenekse** [OfficeDev/office-ui-fabric-react#8818]
### Environment Information 
 
- __Package version(s)__: 6.168.0 
- __Browser and OS versions__: Chrome, Edge, Firefox

### Please provide a reproduction of the bug in a codepen:
same example from the documentation:
 https://codepen.io/anon/pen/ROYqbX?&editable=true
 
#### Actual behavior:
 Hover to the right of the checkbox text, the check mark is going to appear but, checkbox is not clickable/interactive
 
![hover_click](https://user-images.githubusercontent.com/42455391/56594200-44cdf880-65a1-11e9-8a08-a4825fdf1db6.PNG)

My mouse is at the blue square, check mark appears but It does not allow me to interact with it.

#### Expected behavior:

1. Not show the checkmark on hover ( so we know that it is not interactable).
or
2. Allow user to interact when checkmark appears.

**Comment by apneer** [comment]
Thank you for pointing this behavior. This is a bug. I'll workin on fixing this.
