### ISSUE TITLE
Pointer events missing from baseElementEvents list

### ISSUE THREAD

**Issue by ltackett** [OfficeDev/office-ui-fabric-react#8822]
It appears that [PointerEvents](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events) (eg. `onPointerUp`, `onPointerOver`, etc.) are not getting passed to the native HTML elements.

### Environment Information 
 
- __Package version(s)__: `6.117.0`
- __Browser and OS versions__: Any

### Please provide a reproduction of the bug in a codepen:
 
Here is a codepen with repro example:
https://codepen.io/ltackett/pen/XQxraM
 
#### Actual behavior:
 
The Fabric component does not pass native pointer events through to the native HTML element.
 
#### Expected behavior:
 
The fabric component should pass native pointer events through to the native HTML element.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix?  
Yes.
 
Requested priority:  
Normal
 
Products/sites affected:  
Anyone who wants to use `PointerEvents`, 😄

**Comment by micahgodbolt** [comment]
Yeah, seems we're filtering out onPointerUp during `getNativeProps`. Do you have a definitive list of events that need to be added? Or is it just `onPointerUp`? 

https://github.com/OfficeDev/office-ui-fabric-react/blob/cfa7a19ec1d6f98c13f822a828e0751f64507dbd/packages/utilities/src/properties.ts#L8

**Comment by micahgodbolt** [comment]
Ah, just saw the link to pointer events:

![image](https://user-images.githubusercontent.com/1434956/56689377-cac86d00-668f-11e9-8e10-8151eb49004e.png)

**Comment by micahgodbolt** [comment]
@ltackett looks like just updating that properties.ts file. Are you up for creating a PR?

**Comment by ltackett** [comment]
@micahgodbolt sure thing!
