### ISSUE TITLE
Foundation: Evolution of styled helper

### ISSUE THREAD

**Issue by JasonGore** [OfficeDev/office-ui-fabric-react#8823]
Consider the following:

## Fabric 7

| Action | Status | Note | 
|--------|---------|-------|
| Add API change policy to foundation. | ✅  | #8846 |
| Export `styled` as `legacyStyled` from foundation. | ✅ | #8846 |
| Remove `createComponent` export from OUFR. | ✅  | #8846 |
| Move `styled` to new legacy-styled package. (Probably should remove `legacyStyled` from experiments.) | ❌ | |
| Stop exporting `styled` from utilities and OUFR. | ❌ | |
| Make codemod to change people from OUFR/utilities to legacy-styled | ❌ | |
| Codemod to support name change and importing from new location. | ❌ | |
| Change `createComponent` API to easily allow quick component prototyping and customization, like `createComponent(view, { options });` | ✅  | #9072 |
| Deprecate `styled`?  | ❌  | Would also deprecate `legacyStyled`, causes build errors in charting and other packages using `styled`. |

## `createComponent` parity with `styled`

| Action | Status | Note | 
|--------|---------|-------|
| `defaultProps`, `getProps` and `fields` support as applicable. | ❌ |
| loadTheme observable support (#7088) | ❌ |
| Perf and functionality improvements (#8797, #8843) | ❌ |

## Improvements
* Simple Scenarios
  * Is there any way use of `withSlots` can be removed or made optional?
  * Is there a way not to require use of `getSlots` for simple component scenarios?
    * In this case, how would style sections be created automatically? Require users to use `getClassNames` in this case similar to `styled`?

## Fabric 8

| Action | Status | Note | 
|--------|---------|-------|
| Remove `styled` (or at least move to foundation.) Remove `styled` export from OUFR. | ❌  |
| Rename `createComponent` to `styled` | ❌ |

**Comment by khmakoto** [comment]
@JasonGore should we close this as well?

**Comment by JasonGore** [comment]
Closing due to newer efforts that'll take an alternative approach to styled.
