### ISSUE TITLE
Overlay: Prevents scrolling in contained components.

### ISSUE THREAD

**Issue by abhishek1214** [OfficeDev/office-ui-fabric-react#8855]
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
  https://codepen.io/anon/pen/QPZQLP

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/7584903/56786486-c4b0c880-6816-11e9-91e4-a41f927e8222.png)

#### Actual behavior:
 1. The menu of the dropdown is not scrollable on touch device, (for ex: I am using a surface pro).

This happens because Overlay calls "[disableBodyScroll](https://github.com/OfficeDev/office-ui-fabric-react/blob/2894062b1d0515055c29061dfc6f586f918ca41c/packages/office-ui-fabric-react/src/components/Overlay/Overlay.base.tsx#L9)" when mounted. This fixes an iOS bug that occurs anytime a dialog/modal is open. 
 

 
#### Expected behavior:
  1. One should be able to scroll the menu on a touch screen, for example i have a surface pro device.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
Yes

Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by apneer** [comment]
Thank you for bringing this to our attention. I confirm missing feature. We'll work on getting this prioritized.

**Comment by dzearing** [comment]
This sounds like a bug more than a feature request. @joschect can you please take a look?

**Comment by joschect** [comment]
@abhishek1214 can you confirm that this is still an issue? I tried to reproduce using my phone and I was able to scroll fine.

**Comment by v-dhiraj** [comment]
@joschect I work with @abhishek1214 , and we are still not able to make the dropdown work on mobile phone browsers. Please let us know if you have any fix.

**Comment by abhishek1214** [comment]
@joschect we recently upgraded to office-fabric v6.176.0. We are still facing this issue on touch devices. We have Panel with a dropdown to be more specific.

**Comment by joschect** [comment]
@v-dhiraj and @abhishek1214 Are you using a stylus or something like this? I tried using the codepen you provided and it worked without issue on my android device. You mentioned using a Surface, are there any other devices you've tested with that don't work?

**Comment by v-dhiraj** [comment]
@joschect We tested it on an iPhone safari and chrome and the scroll did not work. I am not able to scroll it on chrome in my MI(Android) device either.

**Comment by dzearing** [comment]
@joschect Have you been able to repro?

**Comment by joschect** [comment]
@dzearing I have been able to, I had to set the responsiveMode=large. I'll see if I can figure out a fix.

**Comment by joschect** [comment]
@dzearing I've figured out the issue, this will happen in any component that uses Overlay. It looks like overlay is explicitly disallowing scroll events. I'll get a fix in.

**Comment by pingj** [comment]
Thanks, Jon! Just wanted to mention that it's not only the contained components inside Overlay, but also any component on top of it (i.e. suite nav dropdown, or sth added through <Layer> etc)

**Comment by v-dhiraj** [comment]
@joschect Hi, could you help us and let us know what is the solution that we can apply ?

**Comment by joschect** [comment]
@v-dhiraj This fix ended up being a bit more complicated than I had first thought. I haven't had a chance to get it completed. I'll try to see if I can make more progress tomorrow and come back with an update.

**Comment by v-dhiraj** [comment]
@joschect Could we have a update on this ?

**Comment by joschect** [comment]
@v-dhiraj I think I'll be able to get a fix in this week. I had gotten pulled away on some things but I've got a good idea on how to complete this.

**Comment by dzearing** [comment]
@joschect any updates?

**Comment by joschect** [comment]
@dzearing I should have replied earlier but I've tried a lot of things, none of which work. I'm not convinced that there is a solution other than allowing background scrolling on ios.

**Comment by laiprorus** [comment]
@joschect To solve my issue #10982 that had different problem but partly caused by the same disableBodyScroll function, i submited PR #11339 that makes body scroll block to be optional in Overlay. Not a full solution but a workaround to not fully rollback the disableBodyScroll.

**Comment by micahgodbolt** [comment]
Does `allowTouchBodyScroll` from #11339 solve this issue @abhishek1214

**Comment by micahgodbolt** [comment]
I pulled out my SurfaceBook and confirmed with the demo that adding `allowTouchBodyScroll` resolves this issue and makes the dropdown scrollable.
