### ISSUE TITLE
BasePicker: Strange results after applying styles property 

### ISSUE THREAD

**Issue by JFish63** [OfficeDev/office-ui-fabric-react#8856]
### Environment Information 
 
- __Package version(s)__: 6.169.0
- __Browser and OS versions__: Firefox 66.0.3 64bit

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/basovic88/pen/EJGzqN
 
#### Actual behavior:
 
Default styling is not applied correctly, when providing custom styling overrides via 'styles' property.
 
#### Expected behavior:
 
Apply default styling plus any overrides that are provided via 'styles' property.

#### Priorities and help requested:
 
No
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: Normal. We have an (ugly) work around in place.

**Comment by joschect** [comment]
@basovic88 That's pretty interesting, I definitely see your result. I'm not sure why it doesn't work for this case but works in the case of the TagPicker. I'm looking into it.

**Comment by JFish63** [comment]
This is solved. According to the documented examples you must wrap BasePicker<T,T> in styled<> and use the getStyles from BasePicker.styles. Then it works.
