### ISSUE TITLE
The Month Grid in the Date Picker reads each month as being in row 1 of the grid, regardless of which row it is in

### ISSUE THREAD

**Issue by jamesedj** [OfficeDev/office-ui-fabric-react#8862]
## Codepen demonstrating the issue

1. go to https://developer.microsoft.com/en-us/fabric#/components/datepicker
2. Navigate to the date picker with narrator turned on and scan mode turned off
3. Activate the date picker, then Navigate to the month grid using tab
4. Use the arrow keys to navigate the gird and observe which row narrator announces the cells in

## Actual behavior:
Narrator announces each month as being in row 1 regardless of which row it is in. This will cause confusion for screen reader users, especially because the down arrow navigates between rows

## Expected behavior:
Narrator should correctly announce which row a specific grid cell is in. Alternatively, this could be coded as a [radiogroup](https://www.w3.org/TR/wai-aria-1.1/#radiogroup) since only one can be selected at any time, which would be simpler experience for screen reader users (see comment below for more information)

## Documentation describing expected behavior
ARIA documentation for grids https://www.w3.org/TR/wai-aria-1.1/#grid
ARIA documentation for radiogroup: [https://www.w3.org/TR/wai-aria-1.1/#radiogroup](https://www.w3.org/TR/wai-aria-1.1/#radiogroup)

**Comment by jamesedj** [comment]
I think coding this as a [radiogroup](https://www.w3.org/TR/wai-aria-1.1/#radiogroup) would make the most sense and would also resolve #8736. The code used to make the visual layout could stay the same, only the aria roles and some tweaking of the keyboard functionality would have to be changed (down arrow would need to advance to the next option regardless of the row and options would become selected when they receive focus)

In general to me announcing this as a grid to screen reader users would be confusing in any case because they would not have a sense of which row a given month is in without seeing the interface, so if the radiogroup model doesn't work I would recommend making this a linear set of buttons from a screen reader and keyboard perspective (but it could still have the same visual layout). Gird semantics are better when what row something is in communicates something about it (such as in the calendar grid, where each row represent a given week in the calendar)

**Comment by jamesedj** [comment]
I just talked with Chris Schlechty on this, and we realized that because the month buttons come after the calendar in the focus order, they would change the selections the user made if they were treated as radio buttons. In this case a series of buttons (such as in a list) would be the better semantics so that the user would have to make an affirmative action to make the change. But it still makes sense to use a simpler semantic approach than grids

**Comment by dzearing** [comment]
@lorejoh12 Would you mind sync'ing offline with @jamesedj and @cschlechty on this one? Is this a problem with the new DatePicker or the old one? If it is a fixable issue, is there a simple fix which could be applied in both current and next?

**Comment by lorejoh12** [comment]
This is an issue only in the old Calendar component. I've actually already fixed this in the new date-time calendar. I didn't make any accessible property changes, I just changed the layout to wrap each row of items in a separate div with role="row", which allows all the existing functionality to still work while still recognizing the separate rows.

I really don't like the idea of changing the keyboarding to only allow arrowing left and right. While it might make more sense from a non-sighted perspective, it makes no sense from a sighted one; if I see a grid control visually, I expect the down arrow to take me down by one cell, not to the right. I'd rather optimize for the sighted case and make the non-sighted one work reasonably (by announcing rows and columns correctly, I believe there's enough relevant information there). In addition, the functionality of just arrowing continuously to the left or right does actually still work, so we'd only be removing functionality from sighted users.

To resolve this issue, we can either leave it alone and tell people to upgrade to the new date-time calendar, or if this is high enough priority I can do the same bug fix I did to wrap rows of buttons in a role="row" div.

If you feel strongly that this arrowing story is not sufficient and needs a change, I can loop in our PM who owns the control and we can discuss the best way to solve this going forward.

**Comment by Anschur** [comment]
Does the new date-time calendar also handle the issue in #8736 ?

**Comment by cschlechty** [comment]
Can we do the row fix on the old calendar? That way we don't need to rush adoption of a new one to stay green.

**Comment by qqli1209** [comment]
Hi @lorejoh12 , the old calendar still has a great many users. And we should keep the component downward compatible. Could you please also update the old one? Thanks!
