### ISSUE TITLE
Unexpected error when using Pivot with DetailsList

### ISSUE THREAD

**Issue by captainsafia** [OfficeDev/office-ui-fabric-react#8867]
### Environment Information 
 
- __Package version(s)__: office-ui-fabric-react v6.146.1, React 16.8.2
- __Browser and OS versions__:  Chrome 73.0.3683.103  on Windows 10

#### Actual behavior: 
 
Pivot does not render and throws a "The children of a Pivot component must be of type PivotItem to be rendered." error.

#### Expected behavior:
 
I'm unfortunately not able to reproduce this on a CodePen, so I'll try my best to provide as much information as possible before.

I'm attempting to render a Pivot that looks like this:

```
<Pivot>
    <PivotItem headerText="My project">
        <ProjectList projects={projects || []} />
    </PivotItem>
</Pivot>
```

The `ProjectList` component is a wrapper around the `DetailsList` component with some custom columns defined. When I render the page, the Pivot throws the warning above. I put a breakpoint in the related line in the Pivot class and ran through the following in the dev console.

![image](https://user-images.githubusercontent.com/1857993/56868390-7be44580-69b7-11e9-9917-86babddbf04e.png)

As noted, the deep equality check between the child (the PivotItem) and the PivotItemType fails. A less strict check also fails.

Happy to provide more information or stack traces as I wasn't able to get a reproduce on CodePen. Thanks! 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Normal
 
Products/sites affected: N/A

**Comment by atneik** [comment]
Given the above `<Pivot>` and `<PivotItem>` relationship, its really weird that the check is failing. Does it work if you use `DetailsList` instead of `ProjectList`, just to isolate the issue?

I did try having a wrapped DetailsList component in Pivot but no luck with a repro: https://codepen.io/atneik/pen/EJJdYR

![image](https://user-images.githubusercontent.com/785361/56934802-7d3e6c80-6aa2-11e9-96b3-5bbe04321a8c.png)

**Comment by captainsafia** [comment]
I was able to reproduce the issue with the following code snippet.

```
<Pivot>
    <PivotItem>
        <DetailsList items={[]} />
    </PivotItem>
</Pivot>
```

And was able to reproduce the problem.

![image](https://user-images.githubusercontent.com/1857993/56984220-22ad1b00-6b4b-11e9-92f6-a4a4e6c9b042.png)

I also tried swapping out the `DetailsList` component with a simple header tag and was able to reproduce the problem there as well.

**Comment by atneik** [comment]
The above code snippet still doesn't generate that warning for me. I'm afraid I can't be of much help unless we can repro this in an isolated environment, such as in https://codesandbox.io/s/qxyl77zqw9 or above codepen. 

I'm curious how does the hierarchy look if you inspect them using [React Dev Tools](https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) on your side?

**Comment by jeremy-coleman** [comment]
The details list doesnt export all of its child components unless you import directly from office/lib/detailx ie: the header. Will fail on cjs or importing from only ouifr . Its been broken for about 2 years

**Comment by atneik** [comment]
@captainsafia did it work for you? Do you face this issue only when `DetailsList` is a child of `PivotItem`?

@jeremy-coleman how is `DetailsList` export issue related to this one? @KevinTCoughlin though I do see `DetailsList` doesn't list all its components in its index.ts file.

**Comment by atneik** [comment]
@captainsafia I'll close this one for now until we can repro the issue you're facing.

@jeremy-coleman PR #9058 will be fixing the issue you mentioned.

**Comment by ecraig12345** [comment]
In case anyone is still following this, @akoltz opened #10785 with a repro. Further discussion there.
