### ISSUE TITLE
Improve performance of DocumentCardTitle

### ISSUE THREAD

**Issue by qianghuang94** [OfficeDev/office-ui-fabric-react#8869]
**Describe the feature that you would like added**
The performance of DocumentCardTitle is poor. In the code, it used a loop to truncate title characters by characters and always calling `element.ClientWidth` which will trigger reflow/layout/calc styles. And also, it triggered side-effects in render phrase, which is an anti-pattern of the react 16.
**What component or utility would this be added to**
DocumentCardTitle
**Have you discussed this feature with our team, and if so, who**
Nope
**Additional context/screenshots**
See the screenshot.
![image](https://user-images.githubusercontent.com/15025186/56878767-52dfb580-6a88-11e9-8693-6884b5baa7c7.png)

I will send out an PR to address the issue

**Comment by dzearing** [comment]
@atneik The crazy truncation logic should really be in a separated component, not in the DocumentCard, and honestly should just be avoided (e.g. single line truncation, or faked multiline, but not measured multiline.) 

With the new Card that @khmakoto is working on, can we replace DocumentCard?
