### ISSUE TITLE
Combo Box doesn't loose focus when clicking away

### ISSUE THREAD

**Issue by PatoBeltran** [OfficeDev/office-ui-fabric-react#8874]
### Environment Information 
 
- __Package version(s)__: 6.147.0
- __Browser and OS versions__: Chrome/Windows 10

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/PatoBeltran/pen/yrrPdN

#### Actual behavior:
 
When having multiple combo box in the same page. If you open one, select an option and directly click to open another one, the focus styles on the first one stay and there's no way to remove them (as if the combo was focused at all times).

#### Expected behavior:

The combo box should loose focus as soon as the user clicks away from it.

#### Priorities and help requested:
 
Requested priority: (Blocking, High, Normal, Low) High

**Comment by atneik** [comment]
Thanks @PatoBeltran for reporting this issue. To repro I had to open and select the other combo box in a specific way:

1. **Use the chevron down button** on first combo box to open the list of option
2. Select an option 
3. Select another combo box by clicking **on the input field**.

Issue: The first combo box still shows the blue selected border.

If I follow any other way to open or select it doesn't repro; is that your experience too? Is it limiting the functionality in any way i.e. focusing/keyboarding or is it only a visual bug?

**Comment by PatoBeltran** [comment]
@atneik you are right, it is related to the chevron down button... Another way to repro it is by dismissing the combo box by clicking on the chevron.

This seems to be only a visual bug
