### ISSUE TITLE
Can't type in Colorpicker hex input

### ISSUE THREAD

**Issue by Exolun** [OfficeDev/office-ui-fabric-react#8876]
#### Actual behavior:
1. Start typing into the colorpicker hex field - (Example: FEB808, 'Microsoft yellow')
2. At the 3rd character, some other hex is filled!

#### Expected behavior:
 It should let me type the whole hex string!

Here is a link to the colorpicker component - it should readily reproduce here:
[https://developer.microsoft.com/en-us/fabric#/components/colorpicker](https://developer.microsoft.com/en-us/fabric#/components/colorpicker)

**Comment by dzearing** [comment]
@ecraig12345 didn't you work on this?

**Comment by ecraig12345** [comment]
Yes, I can look into it.

**Comment by ecraig12345** [comment]
@Exolun Thanks for reporting this! I made a PR #8877 which should fix the issue.
