### ISSUE TITLE
Multi-select ComboBox options

### ISSUE THREAD

**Issue by khmakoto** [OfficeDev/office-ui-fabric-react#8882]
There's currently no good way of getting the selected values/indices of a multi-select `ComboBox`. Right now, the ways to do it involve listening to `onChange` (which seems really hacky) or get the selected indices directly out of the state (also hacky).

Having talked about this with @ecraig12345 we think that the best way to do this would be adding a `selectedOptions` prop to `IComboBox` of type `IComboBoxOption[]` that returns an array with the list of selected options in a multi-select `ComboBox`.

**Comment by ecraig12345** [comment]
I added @atneik back to the assignees too since I think this is a simple enough change that it could be done during shield--if that turns out not to be the case, feel free to revert that.

**Comment by atneik** [comment]
@khmakoto wouldn't you also want a similar method for `Dropdown`?

**Comment by khmakoto** [comment]
@atneik at the time I didn't check what the implementation of `Dropdown` looked like. But if it doesn't offer something like this then sure, I'd also want it for `Dropdown`.

**Comment by atneik** [comment]
I think a more React way would be to include all options in the `onChange` handler. So the signature will change from 

`onChange?: (event: React.FormEvent<IComboBox>, option?: IComboBoxOption, index?: number, value?: string) => void;`

to 

`onChange?: (event: React.FormEvent<IComboBox>, option?: IComboBoxOption, index?: number, value?: string, options?:  IComboBoxOption[]) => void;`

@khmakoto @ecraig12345 what do you think?

**Comment by ecraig12345** [comment]
Sorry about the delay responding, was super busy working on the new website. Given how complex the signature for `onChange` is already, I'm not sure we ought to add another option. So I'd still prefer a `selectedOptions` getter on `IComboBox`/`IDropdown`. This also has the benefit of allowing people to pull the value whenever they want instead of having to listen for changes.

**Comment by atneik** [comment]
Won't you still have to rely on `onChange` to know when to pull those values? But I am fine with any approach; I'll update my PR

**Comment by ecraig12345** [comment]
You need to use a ref to access the ComboBox itself.
https://codepen.io/ecraig12345/pen/eYORzJZ?editors=0011

**Comment by patrickeibl** [comment]
Appreciated, thanks!
