### ISSUE TITLE
Not able to add tooltip for PivotItem in Pivot component

### ISSUE THREAD

**Issue by caradong** [OfficeDev/office-ui-fabric-react#8885]
#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

#### Describe the issue:

Not able to add a tooltip for a pivot item in pivot component

#### Actual behavior:

No pivot item is rendered when pivot item is wrapped by tooltip host

#### Expected behavior:
Tooltip should be able to added to a pivot item

### If applicable, please provide a codepen repro:

https://codepen.io/caradong/pen/ROOexW

**Comment by atneik** [comment]
Hi @caradong! `<Pivot>` expects only `<PivotItem>` as its children, anything other type is ignored with a warning. But the good thing is you can use `onRenderItemLink` to create a custom item. Here is a codepen: https://codepen.io/atneik/pen/yrrRwx

Let me know if this works for you.

**Comment by caradong** [comment]
@atneik thank you for your quick reply. That works.

**Comment by atneik** [comment]
Great! I'll close this issue then
