### ISSUE TITLE
Add ability to customize label on dropdown/combo box

### ISSUE THREAD

**Issue by PatoBeltran** [OfficeDev/office-ui-fabric-react#8892]
I want to be able to add some info button on the dropdown label to accomplish something like the following:

![tooltip](https://user-images.githubusercontent.com/2132567/56993568-a833c980-6b51-11e9-8993-f8dd5e3143d9.PNG)

I don't see any support in the dropdown for adding a custom label, or passing a component instead of a string.

**Comment by atneik** [comment]
Hi @PatoBeltran! Thanks for the request. Though I think we can certainly add an `onRender*` method for label in a Dropdown/ComboBox, but I don't see the value in adding that customization where a developer can easily not set any value for label and simply stack a custom component on top. Similar to this: https://codepen.io/atneik/pen/axrQzr

I'll keep this one on backlog review for team to make a call together.

**Comment by PatoBeltran** [comment]
Hey @atneik thanks for the workaround! The only downside of this is that I would need to manage the `require` by myself and loose any other functionality that the field would provide in the label.

**Comment by atneik** [comment]
You might actually still end up handling visual indicator for `require` on your own, as we can't guarantee that developer needs a red color * at the end of the custom label component.

**Comment by Xizt** [comment]
This workaround is cool. Although it might be great to have an onRenderLabel as prop as we have for TextField. In my case I do not want the title to be displayed in bold so I use onRenderLabel for TextFields. I could pass on the same function to the dropdown as well as it as well have the Label prop.

**Comment by jdhuntington** [comment]
I believe this type of interface will be achievable with slots, which is a feature on our near-term roadmap. Ultimately it will mean that consumers manage their own `require` statements as that is what helps fabric achieve smaller bundle sizes. Until slots releases however, this seems like the best temporary workaround.

**Comment by atneik** [comment]
Thanks for your input @jdhuntington. Slots will definitely open up more customization. Closing this one for now.
