### ISSUE TITLE
Support hidden options in Dropdown/combo

### ISSUE THREAD

**Issue by PatoBeltran** [OfficeDev/office-ui-fabric-react#8895]
Normal select fields in HTML support having `hidden` options, which basically mean that the option is there, but the user cannot see or select them. This could be solved in different ways, were the easiest would be to add a `display: none` to the hidden option.

Fabric doesn't support any way to add this attribute to an option in a dropdown. (Not even with styles, since the dropdown options don't have their own styles, they are controlled in general at the dropdown level.)

**Comment by atneik** [comment]
HTML does support `hidden` attributes on I guess all the elements. In JSX, I fail to understand the need for such prop when you can simply exclude the component from rendering or filter the data (options in this case).

We do have `disabled` prop in case you want user to see but not select. In case of no see and no select, I'd just exclude that option from the `options` array. Is this somehow not working for you?

**Comment by PatoBeltran** [comment]
Excluding the option from the array doesn't work, if I pass something to `selectedKey` that is not in the options, the text in the dropdown appears empty. The scenario I'm looking to have is similar to `disable` just a different experience.

I have a `none` option that is selected by default, but once the use changes the option I don't want the user to be able to choose it again. I'm aware that this might also be possible by having a placeholder in the dropdown, but this doesn't seem like the right approach for that.

**Comment by atneik** [comment]
I see, so you'd like to set that option yourself but not let user set it or even see it. This makes sense to me now.  Would you be willing to add this feature? If yes, that be so awesome and I'll assign it to you or else I'll add it our backlog.

**Comment by PatoBeltran** [comment]
hey @atneik, I just submitted a PR for this (https://github.com/OfficeDev/office-ui-fabric-react/pull/8921), please let me know if I missed something. I also don't know where/if I have to add tests.

**Comment by atneik** [comment]
@PatoBeltran thanks for the PR! A test will be a great addition, esp. to test your scenario where a disabled option can't be selected by user but it can be set by the developer. Then you rest assured your use case won't be broken in future.
