### ISSUE TITLE
Support autofocus on combo/dropdown

### ISSUE THREAD

**Issue by PatoBeltran** [OfficeDev/office-ui-fabric-react#8896]
HTML fields have the concept of `autofocus`, which basically means that if a user opens the page, the focus and cursor will be set to that specific element on the page.

Combo Box and Dropdown don't expose any way to add this behavior.

**Comment by atneik** [comment]
I'm personally not a fan of `autofocus` attribute as it can be unreliable in certain circumstances when you have multiple elements with them on a page and also in case of lazy loading components. It is also not compatible with Safari on iOS.

Does your scenario work with calling `focus` method on Dropdown/ComboBox, which in my opinion could be a more reliable approach? 

Here is a codepen to focus upon component mount: https://codepen.io/atneik/pen/ZZNVLb
ReactJS doc for Ref along with some Autofocus examples: https://reactjs.org/docs/refs-and-the-dom.html

**Comment by PatoBeltran** [comment]
I believe this might do it, nevertheless how would this play if it's inside a form where another element has autofocus? In theory, if multiple elements have autofocus enabled, the focus will go to the first one and ignore the rest. This approach seems like it would override any HTML autofocus present on the page.

**Comment by atneik** [comment]
Yes, it will run after DOM is done `autoFocus`, hence overriding. If you handle focus on JS side, it will give you more control. 

Is your scenario some sort of a platform where you are provided with HTML with no control over it? I can see how correctly focusing an element can be more complicated in this case.

**Comment by PatoBeltran** [comment]
I don't love the idea that this approach would override any HTML autofocus, but then again, a given page should only pass autofocus to a single element, so it shouldn't be that bad. Nevertheless, I feel like fabric shouldn't force me to use one approach or the other, it would be nice if it can handle both and give me the option to choose knowing the pros and cons of each one.

In my specific scenario I do have control over the HTML, nevertheless all my current form fields support autofocus via HTML, therefore rewriting everything to use JS will be a bigger task.

**Comment by atneik** [comment]
We could possibly add an `autoFocus` prop which on component mount will execute `focus()`, but then we will have to add this to each and every component just to be consistent (could be an overkill). On positive side developers wouldn't have to deal with `ref` for most common use case of focusing (autoFocus/focus on mount). I'm on the fence for this one, so I'll mark as "Needs: Discussion" just to get other opinions.

**Comment by jdhuntington** [comment]
On closer inspection, I'm not sure we could reliably support an `autofocus` prop, at least in the case of `Dropdown`. Since fabric renders the dropdown without using a `<select>`, the autofocus behavior would have to be handled in react and would end up overriding the browser's interpretation of `autofocus`.

**Comment by atneik** [comment]
Thanks for your input @jdhuntington. Closing this one for now. @PatoBeltran hopefully above solution won't be too much trouble.
