### ISSUE TITLE
DetailsList: Scroll selection into view

### ISSUE THREAD

**Issue by Leif-Frederiksen** [OfficeDev/office-ui-fabric-react#8908]
I have a use case where I have a detailslist with some items, and next to it is a map where all of the items are marked with pushpins. When I click a pushpin on the map I want to have the corresponding item in the list selected and scrolled into view.
Getting the item selected works fine, but it does not automatically scroll into view.
The ISelection interfaces defines setIndexSelected(index,isSelected,shouldAnchor) but I cannot find any documentation on the shouldAnchor parameter. I have tried giving it both true and false in the hope that "anchoring" had something with "scrolling into view" to do.
Apparently it did not.
How can I programaticcaly scroll a given index into view?

**Comment by atneik** [comment]
@Leif-Frederiksen have you tried using `focusIndex` method in [`DetailsList`](https://developer.microsoft.com/en-us/fabric#/components/detailslist)?

**Comment by Leif-Frederiksen** [comment]
Hi Aniket,

Yes I tried that one. It seems to only affect the initial rendering.

/Leif

Den ons. 1. maj 2019 kl. 18.52 skrev Aniket Handa <notifications@github.com

**Comment by atneik** [comment]
Let me tag @KevinTCoughlin who might know better how to get this to work.

**Comment by KevinTCoughlin** [comment]
@Leif-Frederiksen, I think you'll need to do some combination like I've done in the following Codepen: https://codepen.io/kevintcoughlin/pen/EJqmzR?editors=0010. Does that work for you?

It looks like `ISelection`'s `shouldAnchor` is misleading. Perhaps we should clarify in documentation. I thought that parameter would achieve the behavior you were looking for also.

Thanks for the tag @atneik.

**Comment by Leif-Frederiksen** [comment]
That was exatly what I needed @KevinTCoughlin!

The "componentRef" to get access to underlying method was new to me - thanks for helping :-)

Regards
Leif

**Comment by KevinTCoughlin** [comment]
> That was exatly what I needed @KevinTCoughlin!
> 
> The "componentRef" to get access to underlying method was new to me - thanks for helping :-)
> 
> Regards
> Leif

Glad to hear! I'm going to close this as resolved and take another look at `shouldAnchor` documentation as part of #8864.
