### ISSUE TITLE
Rest border colors do not meet WCAG 2.1 requirements - Textfield, Dropdown, Spinbutton, Combobox – 

### ISSUE THREAD

**Issue by betrue-final-final** [OfficeDev/office-ui-fabric-react#8910]
Current Fluent border colors for Textfield, Dropdown, Spinbutton and Combobox do not meet WCAG 2.1 requirement for non-text contrast. It is currently 2.15:1 (Gray 80)
![image](https://user-images.githubusercontent.com/20363037/57032400-1a161c80-6bff-11e9-995e-a5e86d45abff.png)

Expected They must be 3:1 against background. Gray110 is the lightest color that will pass, but in our theming system we would need to use Gray130.

**Comment by atneik** [comment]
@betrue-final-final In Fluent palette, I do see Gray110 (neutralSecondaryAlt), would you prefer that over Gray130 (neutralSecondary) for border colors?

**Comment by atneik** [comment]
@betrue-final-final Also what about border color in SearchBox and Pickers component? I think we should treat them similarly.

**Comment by betrue-final-final** [comment]
I thought those used the text field component anyway, but yes those should also change.
