### ISSUE TITLE
[Performance] Should import es6 module version of load-themed-styles

### ISSUE THREAD

**Issue by orokanasaru** [OfficeDev/office-ui-fabric-react#8926]
Webpack bails out of optimization for non es6 modules. The load-themed-styles package ships with es6 modules, but Fabric is importing the cjs version.

#### Actual behavior:
 
Importing 'from @microsoft/load-themed-styles'
https://github.com/OfficeDev/office-ui-fabric-react/blob/152411e0ffe90d99488f955396926dba15150589/packages/styling/src/styles/theme.ts#L6
 
#### Expected behavior:
 
Importing 'from @microsoft/load-themed-styles/lib-es6'

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)

Yes
 
Requested priority: (Blocking, High, Normal, Low) 
 
Low

**Comment by atneik** [comment]
Hi @orokanasaru. Sounds like a great perf improvement. I see that you're willing to submit a PR, that's awesome! Will you be able to create a PR and hopefully we can look at a metric for perf improvement on the standard package. Thanks

**Comment by atneik** [comment]
@orokanasaru are you planning on working on this?
