### ISSUE TITLE
ChoiceGroup doesn't respect element ID

### ISSUE THREAD

**Issue by dfisenko** [OfficeDev/office-ui-fabric-react#8939]
### Environment Information 
 
- __Package version(s)__: 6.173.0

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/anon/pen/JVgBPm
 
#### Actual behavior:
 
ChoiceGroup component doesn't respect provided element ID. For example Component 
```
<ChoiceGroup  id={"foo"} ... />
 ```
rendered as html containing internal input elements with id's like *ChoiceGroup1-B*. Id 'foo' is completely ignored. This behavior is inconsistent with other components where ID is assigned to the inner *input* or wrapper elements.
#### Expected behavior:
 
element id should not be dropped and assigned to wrapper element

#### Priorities and help requested:
  
Requested priority: High

**Comment by atneik** [comment]
Hi @dfisenko! Thanks for reporting this. Would you be able to help with this contribution?

**Comment by dfisenko** [comment]
@atneik sure, I will

**Comment by atneik** [comment]
Great!

**Comment by atneik** [comment]
@dfisenko are you still thinking of working on this one? Thanks!
