### ISSUE TITLE
Add badge support for IButtonProps

### ISSUE THREAD

**Issue by lalicari** [OfficeDev/office-ui-fabric-react#8943]
**Describe the feature that you would like added**
Apologies if this has already been requested, but it would be awesome if there was badging support for icons/buttons.

**What component or utility would this be added to**
I assume this would be under IButtonProps?

**Have you discussed this feature with our team, and if so, who**
No

**Additional context/screenshots**
I was imagining it would be something like [Material UI's badging API](https://material-ui.com/api/badge/)

I guess if there's no API for it, is it possible to add a badge to button?

**Comment by KevinTCoughlin** [comment]
Interesting request! To save a few clicks, here's the desired output:

![image](https://user-images.githubusercontent.com/706967/57150169-6dfd3e80-6d82-11e9-98ed-c6729d2f89f3.png)

**Comment by lalicari** [comment]
@KevinTCoughlin do you think there's a way to get the desired output with the current API? I'm trying to think of features in Office that might use this, but I'm having a hard time thinking of any. If there's no use for it in Office I understand why you might close this, but was wondering what your opinion was.

**Comment by atneik** [comment]
@lalicari You can always use `onRender*` methods on `Button` component to get desired output without compromising on functionality that the component brings. A quick & dirty codepen: https://codepen.io/atneik/pen/rgBmOe

**Comment by lalicari** [comment]
Sweet! I thought it'd have to be more hacky than that, but that's way simpler than I imagined. Thanks! If it's that simple, feel free to ignore this request, unless you feel like exposing this functionality more would be useful.

**Comment by atneik** [comment]
Glad that will work for you. I'll close this request for now and lets keep an eye if more developers / design need something like this.
