### ISSUE TITLE
Return value type incorrect for CommandBar.types.ts onReduceData

### ISSUE THREAD

**Issue by daveparslow** [OfficeDev/office-ui-fabric-react#8948]
In CommandBar.types.ts

    /**
     * Custom function to reduce data if items do not fit in given space. Return `undefined`
     * if no more steps can be taken to avoid infinate loop.
     */
    onReduceData?: (data: ICommandBarData) => ICommandBarData;

It clearly should be the following based on the documentation
```
    onReduceData?: (data: ICommandBarData) => ICommandBarData | undefined
```

### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Expected behavior:
 
Should be able to pass a function that has the return type of undefined to onReduceData

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) Yes
 
Requested priority: (Blocking, High, Normal, Low) Normal
 
Products/sites affected: (if applicable)

**Comment by atneik** [comment]
@daveparslow this makes sense, esp. when we have the same definition in `Breadcrumb.types.ts`. I see that you're willing to a PR, that will be a great contribution!
