### ISSUE TITLE
Suite Nav control?

### ISSUE THREAD

**Issue by rickyp-ms** [OfficeDev/office-ui-fabric-react#897]
Just curious if there are any plans to work with the Suite Nav team to move their control into this library. Or if there is any want to do that?

![suitenav](https://cloud.githubusercontent.com/assets/22225666/22354271/71291db6-e3d9-11e6-8388-18490a59dff4.png)

**Comment by dzearing** [comment]
@rickyp-ms This component is not owned by us, but we are reaching out with the nav team to see what options we have.

**Comment by dzearing** [comment]
I will leave this open until we understand the plans.

**Comment by rickyp-ms** [comment]
Already reached out. I'll give more details offline but basically it wouldn't be part of this library currently.
