### ISSUE TITLE
Broken page for documentation for DetailsList - LargeGrouped

### ISSUE THREAD

**Issue by vasticles** [OfficeDev/office-ui-fabric-react#8991]
## Actual behavior:
Failure to load while trying to access the documentation page for DetailsList - LargeGrouped.

## Expected behavior:
Page loads and documentation is accessible.

I tried accessing the page on Chrome and Safari, but the browsers choke each time. The website seems to become inaccessible for 5-10 mins after that.

![image](https://user-images.githubusercontent.com/5666413/57264366-82ba2a80-703f-11e9-85d6-203554ed3590.png)

**Comment by jdhuntington** [comment]
@vasticles thanks for reporting, and sorry you're running into this. Will get this figured out.

**Comment by jdhuntington** [comment]
cc @ecraig12345

**Comment by ecraig12345** [comment]
Thanks for reporting this! I just made a PR #8993 which will fix the issue and prevent any similar future issues from causing infinite loops.
