### ISSUE TITLE
DetailsList: Horizontal scrollbar visible in IE11/Firefox

### ISSUE THREAD

**Issue by fildahui** [OfficeDev/office-ui-fabric-react#8996]
I'm "re-opening" an existing issue (which wasn't closed, by the way): [#6546](https://github.com/OfficeDev/office-ui-fabric-react/issues/6546).

That issue was included first in February 2019 and then March 2019 milestones but it's still open and the problem is still present in the latest version of Fabric.

You can see it on your own website (viewing it with Firefox or IE11):
https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/basic
https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/compact

Scroll to the bottom of the list and you'll see the horizontal scrollbar.
As soon as you resize the page the scrollbar disappears.

This doesn't happen in Chrome.

### Environment Information 
- __Package version(s)__: latest
- __Browser and OS versions__: FireFox / IE11 / Edge

### Please provide a reproduction of the bug in a codepen:

https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/basic
https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/compact

#### Actual behavior:
 
Scroll to the bottom of the list, the horizontal scrollbar is present.
 
#### Expected behavior:

The horizontal scrollbar should not be present.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Blocking

**Comment by jdhuntington** [comment]
@fildahui Thanks for the report. Unfortunately the milestone labels didn't correspond to actual releases, and we still haven't sorted out the issue entirely.
I will focus on #6546 and see what we can get moved forward; in the meantime are you willing to close one of the issues so that we only have 1 open issue tracking this bug?

**Comment by fildahui** [comment]
Hi @jdhuntington 
I was looking at the latest version of fabric and this issues seems to have been resolved. 
Could you confirm that it's been fixed? 

thank you!

**Comment by jdhuntington** [comment]
Hi @fildahui - sorry for the late follow up. I do believe this was fixed with #9343 , which is included from v7.1.0 onwards. Sorry for not updating this thread; I had not realized that this PR fixed the scrollbar issue until I saw your comment.

**Comment by jdhuntington** [comment]
Closing as resolved.
