### ISSUE TITLE
Component dropdown links won't collapse after navigation on the documentation site.

### ISSUE THREAD

**Issue by noon-otter** [OfficeDev/office-ui-fabric-react#8999]
Component dropdowns on the side navigation panel remain frozen after clicking the link to a specific component. 

Steps to reproduce:

1. Go to: [https://developer.microsoft.com/en-us/fabric#/controls/web](https://developer.microsoft.com/en-us/fabric#/controls/web)
2. Expand "Basic Inputs" on the right side navigation bar.
3. Click "Button," navigating to the documentation page for the button component.
4. "Basic Inputs" remains expanded post rendering. Clicking the carrot won't collapse the basic inputs menu.

I'm using Chrome Version 74.0.3729.131 (Official Build) (32-bit) on Windows 10.

**Comment by jdhuntington** [comment]
Thanks @noon-otter ! In this case, I believe the navigation links are working as intended, as it's important to make sure readers are able to quickly scan and find their current context. This is why other sections can be opened/closed, but not the section containing the currently viewed page. On the subsections for details list, for example (https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/variablerowheights) there are multiple levels of navigation that are kept visible.
Does this make sense? Would you expect it to work another way?

**Comment by noon-otter** [comment]
@jdhuntington I'd expect the same behavior before and after navigation, since the sidebar doesn't change by clicking. Your explanation makes sense though. From a UX perspective, it seemed like a bug to me.

Before navigating to a component -- clicking chevron toggles the submenu to aid in navigation.
After navigating to a component -- submenu is open and locked, hindering intentional navigation.
Expectation after navigating -- submenu is open and toggle-able.

I expect navigation components to change in appearance after use, but not change in functionality.

**Comment by jdhuntington** [comment]
Makes sense - that is indeed good precedent. @jordandrako Are you able to comment on this behavior?

**Comment by jordandrako** [comment]
The left navigation is using an experimental control. It has been updated since I implemented it, so I'll take another look and see if I can make it behave more predictably.
