### ISSUE TITLE
TextField multiple-line errorMessage support

### ISSUE THREAD

**Issue by iamchangming** [OfficeDev/office-ui-fabric-react#9000]
**Describe the feature that you would like added**
multiple-line errorMessage support

**What component or utility would this be added to**
TextFieldBase

**Have you discussed this feature with our team, and if so, who**
no

**Additional context/screenshots**
![image](https://user-images.githubusercontent.com/12876367/57323199-33fda680-70ba-11e9-87ea-6aa827098c82.png)

**Comment by jdhuntington** [comment]
@iamchangming I think the most flexible solution would be to allow the `errorMessage` prop to accept JSX in addition to a string instead of parsing out `\n` characters.

This codepen shows how I think it might be able to work: https://codepen.io/jdh-msft/pen/BeNrBq

Would you be willing to send a PR making this change? Would take place in `packages/office-ui-fabric-react/src/components/TextField/TextField.types.ts`

**Comment by iamchangming** [comment]
Yes, could you please share the procedure to create that PR?

**Comment by jdhuntington** [comment]
Thanks! Yes, the procedure is laid out at https://github.com/OfficeDev/office-ui-fabric-react/wiki/Contributing (more details at https://github.com/OfficeDev/office-ui-fabric-react/wiki/Bug- Fixes ); happy to help answer any more questions as well.

**Comment by iamchangming** [comment]
When I looked at this again, I found some potential issue with this solution.

What I really wanted is multiple line support with onGetErrorMessage.
So in TextField.base.tsx I will need to test if " 'then' in result ".

I will also need to change the types for onGetErrorMessage and onNotifyValidationResult.
Not sure if that will be compatible with the previous version.
```
onNotifyValidationResult?: (errorMessage: string | JSX.Element, value: string | undefined) => void;
onGetErrorMessage?: (value: string) => string | JSX.Element | PromiseLike<string> | PromiseLike<JSX.Element> | undefined;
```

**Comment by jdhuntington** [comment]
Good question. In this case, since you are making the API more permissive and allowing everything that worked before I don't believe there are any issues.

Might also be convenient to declare a `type` for error that would make other changes more obvious.

For instance:

```jsx
type ErrorMessage = string | JSX.Element;

// later, the types could be...
onNotifyValidationResult?: (errorMessage: ErrorMessage, value: string | undefined) => void;
onGetErrorMessage?: (value: string) => ErrorMessage | PromiseLike<ErrorMessage> | undefined;
```
