### ISSUE TITLE
Foundation: createComponent exported twice

### ISSUE THREAD

**Issue by aldoreno** [OfficeDev/office-ui-fabric-react#9007]
As stated in the title `createComponent` are exported twice in [`@uifabric/foundation`'s index](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/foundation/src/index.ts):

```
export * from './createComponent';
export * from './createComponent';
export * from './IComponent';
export * from './IHTMLSlots';
export * from './ISlots';
export * from './slots';
export * from './ThemeProvider';

import './version';
```

It might not an issue for many but I happen to use older version of Webpack and it unable to handle the situation properly and ended up unable to resolve all exported keys from Foundation.

I have tried to manually removed one of the export and then it works just fine.

@JasonGore probably the right person to fix this. Thank you so very much. 🙇

**Comment by jdhuntington** [comment]
Thanks @aldoreno - will get this sorted out.
