### ISSUE TITLE
DetailsList - selection changes on Up/Down arrow navigation

### ISSUE THREAD

**Issue by sugandhi-ms** [OfficeDev/office-ui-fabric-react#9011]
## Codepen demonstrating the issue
https://codepen.io/anon/pen/byVKeR?editors=1011

## Actual behavior:
If selection mode is Single or Multiple, hitting Up/Down arrow keys changes the selection to the next/previous row. 

## Expected behavior:
According to WAI-ARIA guidelines, arrow keys should change focus (not selection) of the rows. 

## Documentation describing expected behavior
https://www.w3.org/TR/wai-aria-practices-1.1/#dataGrid

**Comment by jdhuntington** [comment]
@sugandhi-ms Thanks for reporting.

Looking at the best practices, I'm not sure that I see a clear expectation for what up arrow and down arrow should do when in selection mode.
The DetailsList does follow the best practices when using "Shift +" and expands the selections. In cases where a modifier is not held, I believe we do our best to follow the standard set by other Microsoft applications. For example, the File Explorer behaves the same way as the DetailsList when checking multiple options then arrowing up/down.

cc @KevinTCoughlin

**Comment by sugandhi-ms** [comment]
@jdhuntington It would be more organic if arrows (without a modifier) change just the focus (and not selection). 
e.g. in our use case, selection of a row shows up a command bar at the top of the grid. The expected accessibility behavior for this case is that on selection (using keyboard), the focus moves to the first action in the command bar.
With the current implementation of details list, if we try to implement this behavior, the focus will move to the command bar actions even when arrow navigation is happening (which is a bad user experience in case the user is actually trying to just navigate up/down the rows of the grid). How do we differentiate navigation from selection then?

**Comment by KevinTCoughlin** [comment]
@sugandhi-ms have you taken a look at a similar recent issue opened here: https://github.com/OfficeDev/office-ui-fabric-react/issues/8808#issuecomment-487230767

>According to WAI-ARIA guidelines, arrow keys should change focus (not selection) of the rows.

Regarding the above, OneDrive / SharePoint and other products have passed accessibility passes with the existing behavior. As for a way to disable that behavior and my more thorough explanation, please see the above linked issue.

I hope that unblocks you!

**Comment by sugandhi-ms** [comment]
Thanks for the response @KevinTCoughlin . This is exactly what I needed. This resolves my issue!

**Comment by KevinTCoughlin** [comment]
> Thanks for the response @KevinTCoughlin . This is exactly what I needed. This resolves my issue!

Awesome, thanks for the follow-up @sugandhi-ms. I'm going to close this as resolved.
