### ISSUE TITLE
Will it be usable on React-Native for iOS, Android and UWP?

### ISSUE THREAD

**Issue by hmheng** [OfficeDev/office-ui-fabric-react#9022]
Will it be usable on React-Native for iOS, Android and UWP?

**Comment by jdhuntington** [comment]
The code in this repository will remain focused on browser based components for the web. We do have some specific projects that implement Fluent for iOS and Android however, though there is not [yet] a perfect overlap of provided components.
Android Fabric: https://github.com/OfficeDev/ui-fabric-android
iOS Fabric: https://github.com/OfficeDev/ui-fabric-ios

**Comment by michaelspeed** [comment]
we could really use some of the components for react native
