### ISSUE TITLE
ButtonProps affect the entire slider instead of the thumb

### ISSUE THREAD

**Issue by billyjacobs2014** [OfficeDev/office-ui-fabric-react#9023]
Reproduction:

https://codepen.io/billyjacobs2014/pen/zQrpBw.

You can see here that the buttonProps set on the slider affect the entire slider.

#### Actual behavior:
 
The slider component has a buttonProps prop which says that it will allow additional props for the thumb part of the component. However the props get applied to the entire slider and not the thumb
 
#### Expected behavior:
 
buttonProps will modify the thumb portion of the slider component and not the entire slider.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Blocking

**Comment by jdhuntington** [comment]
@billyjacobs2014  Sorry this isn't working as expected.

Looking at the implementation of the slider, there are a few possible workarounds. Is your goal to drive behavior (such as `onClick`), or are you more interested in altering the styling of the thumb?

**Comment by billyjacobs2014** [comment]
More interested in styling the thumb. I was able to style it by overriding the existing styles but that is a bit tedious. See this pen for how I overrode the css.

https://codepen.io/billyjacobs2014/pen/eaJyGW

**Comment by jdhuntington** [comment]
@billyjacobs2014 I believe your workaround is the best solution possible at the moment. I've opened #9073 to track improving this going forward, and believe we have a much better solution actively in the works.

Possibly of note, it's also possible to pass styles this way:
```jsx
class Example extends React.Component<any, any> {
  public render(): JSX.Element {    
    const sliderStyles = {
      slideBox: {
        selectors: {
          '.ms-Slider-thumb': {
            borderColor: 'red'
          }
        }
      }
    };
    
    return (
      <div>
        <Slider
          label="Basic example"
          min={1}
          max={5}
          step={1}
          defaultValue={2}
          showValue={true}
          styles={sliderStyles}
        />
      </div>
    );
  }
}

```

It ends up doing the same thing as your example, but will scope styles to that specific control, so might be something to consider if it makes organizing your styles easier.
