### ISSUE TITLE
Cannot display selected office fabric ui dropdown value dynamically retrieved from componentDidMount function

### ISSUE THREAD

**Issue by harrychen1** [OfficeDev/office-ui-fabric-react#9026]
### Environment Information  
"@microsoft/sp-office-ui-fabric-core": "^1.7.1",

We are using Office React Fabric UI package to display SharePoint list item. One column is using Dropwdown component, it's not able to display the value already set.

I've prepared a simple test code. 

1. Add a private variable

  private defaultOptionList: IDropdownOption[] = [
    {
      key: '0',
      text: 'None',
      isSelected: false
    },
    {
      key: '1',
      text: 'Encore/Review Publication',
      isSelected: true
    },
    {
      key: '2',
      text: 'Non-Scientific',
      isSelected: false
    }
  ];

2. Set one state variable submissionContentListState2  through constructor.
  constructor(props) {

    super(props);
    this.state = {
      submissionContentListState2: [] = this.defaultOptionList,  // Set in constructor    
      submissionContentListState4: []                            // Set in componentDidMount
    };

  }

3. Set another state variable submissionContentListState4  through componentDidMount.
  public  componentDidMount() {
 
          this.setState({            
            submissionContentListState4: this.defaultOptionList
          });
  }

4. Display both state variable in Dropdown component.
submissionContentListState2 can display the selected value  
submissionContentListState4  cannot display the selected value but have the all options available.

The testing code and details are in https://sharepointconnoisseur.blogspot.com/2019/04/cannot-display-selected-office-fabric.html.

I also tried to use "selectedKeys" and "defaultSelectedKeys" without luck.

The final goal is we need to retrieve the SharePoint item value from PnP JS in the componentDidMount function. This issue prevent us to display the Dropdown value.

I can send the whole test package if you give me a way to attach.

Thanks in advance for your help!!!

**Comment by jdhuntington** [comment]
@harrychen1 Does this example look similar to what you're trying to accomplish? https://codepen.io/jdh-msft/pen/rgxqev?editors=0010

If so, I'm afraid I am not able to reproduce. I wonder if the problem might be in `Child`, but I can't say as I don't have that code.

As a next step, it would help if you could "fork" the example at https://codepen.io/jdh-msft/pen/rgxqev?editors=0010 and modify to be inline with the issue you are encountering in your own application.

Thanks!

**Comment by harrychen1** [comment]
Thanks for the quick response. You are correct, the issue can be reproduce if you have React parent and child component.

If the value is been passed from parent as pros to child, you can reproduce this issue. Here is the parent and child code.

import * as React from 'react';
import { ILoopUpProps } from './ILoopUpProps';
import { IDropdownOption } from "office-ui-fabric-react";
import { Child } from "./Child";
import { SPFacade } from "./SPFacade";

export default class LoopUp extends React.Component<ILoopUpProps, 
{
  submissionContentListState2: IDropdownOption[];
  submissionContentListState4: IDropdownOption[];
}
> {

  private defaultOptionList: IDropdownOption[] = [
    {
      key: '0',
      text: 'None',
      isSelected: false
    },
    {
      key: '1',
      text: 'Encore/Review Publication',
      isSelected: true
    },
    {
      key: '2',
      text: 'Non-Scientific',
      isSelected: false
    },
    {
      key: '3',
      text: 'Assay Method',
      isSelected: false
    },
    {
      key: '4',
      text: 'Research Data',
      isSelected: false
    },
    {
      key: '5',
      text: 'PK/Tox Data',
      isSelected: false
    },
    {
      key: '6',
      text: 'Clinical Data',
      isSelected: false
    },
    {
      key: '7',
      text: 'Clinical Study Design',
      isSelected: false
    },
    {
      key: '8',
      text: 'Clintrials.gov Posting',
      isSelected: false
    }

  ];

  constructor(props) {

    super(props);
    this.state = {
      submissionContentListState2: [] = this.defaultOptionList,  // Set in constructor    
      submissionContentListState4: []                            // Set in componentDidMount
    };

  }


  // Get the itemId received form the parent and display attachment if itemId is not NaN
  public  componentDidMount() {
 
          this.setState({            
            submissionContentListState4: this.defaultOptionList
          });
  }


  public render(): React.ReactElement<ILoopUpProps> {

    SPFacade.logOptions(this.state.submissionContentListState2, "Parent Rendor submissionContentListState2");
    SPFacade.logOptions(this.state.submissionContentListState4, "Parent Rendor submissionContentListState4");
    return (
      <Child
      defaultOptionListParent2={this.state.submissionContentListState2} // This is in constructor
      defaultOptionListParent4={this.state.submissionContentListState4} // This is in componentDidMount
      />

    );
  }





}

Here is Child code.
import * as React from 'react';
import styles from './LoopUp.module.scss';
import { ILoopUpProps } from './ILoopUpProps';
import { Dropdown, IDropdownOption } from "office-ui-fabric-react";
import { SPFacade } from "./SPFacade";

export class Child extends React.Component<any,
  {

    //submissionContentListState: IDropdownOption[];

  }
  > {

  
    constructor(props) {
      // Required step: always call the parent class' constructor
      super(props);
  
    }
  
     
    public render(): React.ReactElement<ILoopUpProps> {

        SPFacade.logOptions(this.props.submissionContentListState2, "Child Rendor submissionContentListState2");
        SPFacade.logOptions(this.props.submissionContentListState4, "Child Rendor submissionContentListState4");
      return (
        <div className={ styles.loopUp }>
          <div className={ styles.container }>


            <div className={ styles.row }>
              <div className={ styles.column }>
              <Dropdown
                  placeHolder="Select a content type"
                  required={true}
                  label="Lokup values from parent props set in constructor - working"
                  options={this.props.defaultOptionListParent2}
              />
              </div>
            </div>


            <div className={ styles.row }>
              <div className={ styles.column }>
              <Dropdown
                  placeHolder="Select a content type"
                  required={true}
                  label="Lokup values from parent props set in componentDidMount - not working"
                  options={this.props.defaultOptionListParent4}
              />
              </div>
            </div>


          </div>
        </div>
      );
    }



  }
  

Thanks again for your help!!!

**Comment by jdhuntington** [comment]
Added the `Child` component, and I'm still not able to reproduce: https://codepen.io/jdh-msft/pen/BejeQz?editors=0010

What behavior are you looking to get? If you're able, please fork the codepen and highlight the issue there. Thanks!

**Comment by harrychen1** [comment]
You just reproduced the issue.

Please check the value selected for the Dropdown from the first and second components. 

The first component is set to **"Encore/Review Publication"** as in codepen.

The second component ask users **"Select a content type"** even we have set the same value that should be displayed.

Thanks.

**Comment by harrychen1** [comment]
Our final goal is to display the value that is coming from SharePoint list item. The code is to pass the static array to demonstrate the issue.

Thank you so much to spend time on this. Appreciate your effort and help!

**Comment by westleyMS** [comment]
Just to clarify, harrychen1 wants to have the IDropDownOption collection to show the item with the selected: true to show as the selected option when passed into the options at render, or after the componentDidMount() fires (after the render).

It seems the DropDown control doesn't change the selection when the options change, but is seems they should.

**Comment by jdhuntington** [comment]
@harrychen1 The example with child was not passing a selected key to the dropdown, it was just showing that the list does populate. I believe the only thing you might be missing is the option to control the selected key itself. see https://codepen.io/jdh-msft/pen/BejeQz?editors=0010

**Comment by harrychen1** [comment]
This is exactly what I'm looking for. I was not able to make it work using selected key.

Thank you so much for the effort!!!

Please close the case.
