### ISSUE TITLE
Positioning issue of Dropdown's options list in RTL context

### ISSUE THREAD

**Issue by abdullahsalem** [OfficeDev/office-ui-fabric-react#9029]
## Issue Summary 
**In RTL context**, when the dropdown's options list is configured to be positioned **top** or **bottom** and there are not enough spaces for both sides, the dropdown's options list **will always be positioned to the right side even if the suitable side (left) has enough space**.

#### Codepen sample
https://codepen.io/abdullahsalem/pen/qGNmjJ

## Reproduction Steps:
- Create RTL page
- Create a Dropdown component
- In some way, make the **options list** long so that it neither can be positioned top nor bottom. In other words, make the dropdown’s options list exceeds both top or bottom bounds

### Actual behavior:
The dorpdown's options list is positioned on the right side.
![ouf-positioning-issue](https://user-images.githubusercontent.com/177020/57478909-d6797d80-72a4-11e9-8765-7d6d1beaf8fb.png)

### Expected behavior:
According to the normal flow of the RTL page, elements are expected to appear orderly from the right to left, so the dropdown’s options list should appear next to the relative element (left side).
![ouf-positioning-issue-suitable-position](https://user-images.githubusercontent.com/177020/57478978-045ec200-72a5-11e9-9159-21a2475d26d0.png)
 

## Priorities and help requested:
 
Are you willing to submit a PR to fix? **Yes**
 
Requested priority: **High**

**Comment by abdullahsalem** [comment]
I've already figured out where the issue is, and I am setting up a PR..

**Comment by jdhuntington** [comment]
> I've already figured out where the issue is, and I am setting up a PR..
Thanks!

**Comment by abdullahsalem** [comment]
The issue has been fixed here #9041
