### ISSUE TITLE
People Picker renders X on right-side in Edge

### ISSUE THREAD

**Issue by JoshuaLamusga** [OfficeDev/office-ui-fabric-react#9032]
### Environment Information 
 
- __Package version(s)__: 6.164.2
- __Browser and OS versions__: Edge 44.17763.1.0 on Windows 10

You can test this bug here: https://developer.microsoft.com/en-us/fabric#/controls/web/peoplepicker

1. Focus on the PeoplePicker.

2. Start typing. On Edge, you will see an X on the right-hand side.
![image](https://user-images.githubusercontent.com/30244654/57482603-e5870e00-7259-11e9-84a9-92c478d536d0.png)

This does not repro in Chrome. I'm assuming it shouldn't be in Edge. There is no hand icon for the cursor when hovering over the X button. Clicking the X will clear the picker, but when the focus changes, the content will come back. So I believe this isn't an expected feature.

#### Actual behavior:
 
You can see an X on the right-hand side of the picker which shouldn't be present.
 
#### Expected behavior:
 
There is no X on the right-hand side of the picker OR the functionality of the X button is fixed, made accessible, and made available in all browsers.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? **No**
Requested priority: **Normal**

**Comment by jdhuntington** [comment]
Thanks @JoshuaLamusga for the report. Will get this sorted out.
