### ISSUE TITLE
Contextual menu scroll bar is hiding right arrow

### ISSUE THREAD

**Issue by lju** [OfficeDev/office-ui-fabric-react#9034]
### Environment Information 
 
- __Package version(s)__: Latest
- __Browser and OS versions__: Edge

### Please provide a reproduction of the bug in a codepen:
 
https://developer.microsoft.com/en-us/fabric#/controls/web/contextualmenu > example "ContextualMenu which is persisted in the DOM" or in outlook web app right click on a mail list item.
 
#### Actual behavior:
 
The scroll bar hides the right arrow to see submenu items.

![image](https://user-images.githubusercontent.com/3344951/57487244-ee311180-7264-11e9-825e-e2b670ee6dec.png)
 
#### Expected behavior:
 
The scroll bar does not hide the right arrow.

![image](https://user-images.githubusercontent.com/3344951/57487409-5849b680-7265-11e9-856e-4b5c41975403.png)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Maybe
 
Requested priority: Normal
 
Products/sites affected: Outlook web app (and anyone else who has long context menus and/or users with small browser window heights)

**Comment by jdhuntington** [comment]
Looks like an issue specifically with persisted menus. Associated PR will fix.
