### ISSUE TITLE
Event.target.id for ComboBox onChange callback is inconsistent

### ISSUE THREAD

**Issue by khannasushant** [OfficeDev/office-ui-fabric-react#9047]
### Environment Information 
 
- __Package version(s)__: (fill this out) 6.164.0
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/anon/pen/yWOLrB?editors=1111
 
#### Actual behavior:
 
The id returned by event.target.id is not consistent. 
On selecting a value from dropdown the value returned is "" (empty)
On writing a new value the value returned is "myId-input" (input is appended at the end)
 
#### Expected behavior:
 
The id returned must be "myId" in all the cases

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) I don't know much about coding the component
 
Requested priority: (Blocking, High, Normal, Low) Blocking
 
Products/sites affected: (if applicable) Creating a new AddIn for Visio

**Comment by khannasushant** [comment]
the package version is "6.164.0"

**Comment by jdhuntington** [comment]
@khannasushant Sorry you're running into this. Will look at getting a fix in the next few days. Thanks.

**Comment by jdhuntington** [comment]
@khannasushant Upon further investigation, I'm afraid this change may not be possible as we are sending events based on the items chosen which themselves are valid `targets`. 

Can I ask what you are hoping to do with the ID? Perhaps there might be a workaround by wrapping the onChange value in another callback or using a ref to get the same result.

**Comment by khannasushant** [comment]
Actually I have different dropdowns in my App. So I want to see for which comboBox the value got changed. Like for dropDown onChange event I get the correct ID,

**Comment by jdhuntington** [comment]
@khannasushant Would something like this work for you? https://codepen.io/jdh-msft/pen/GaEEbe?editors=0011#0 Since you know the ID when you create the on-change callback, you can pass that information to the callback ahead of time.

**Comment by khannasushant** [comment]
Yes @jdhuntington this will work. Thanks :)

**Comment by jdhuntington** [comment]
Thanks @khannasushant - I have also created #9152 to track this specific request for future work in the ComboBox, as it shouldn't be difficult to handle with and updated callback API.
