### ISSUE TITLE
Checkbox doesn't show outline box when using keyboard

### ISSUE THREAD

**Issue by voidsteed** [OfficeDev/office-ui-fabric-react#9048]
### Environment Information 
 
- __Package version(s)__: (regression ) 
- __Browser and OS versions__: (Chrome and Win10)

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/voidsteed/pen/vwLoBR
 

 
#### Actual behavior:
 using tab key go to DetailList Component, and when selected the first row of list, using right arrow key to navigate in column, the link in Post column will be focused with outline box, and if you hit right arrow key 2 times to checkbox, the outline box is not showing up around CheckBox component

 
#### Expected behavior:
 the outline box is showing up around CheckBox component

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 Yes
Requested priority: (Blocking, High, Normal, Low) 
 Blocking
Products/sites affected: (if applicable)
A Microsoft internal site

Adding @KevinTCoughlin, since I talked with him about this issue offline. Thank you!

**Comment by KevinTCoughlin** [comment]
Thanks to @cliffkoh for surfacing the PR which introduced this: https://github.com/OfficeDev/office-ui-fabric-react/pull/8828

We should consider reverting the above to mitigate if there isn't a clear fix for both scenarios.

**Comment by cliffkoh** [comment]
This works before 6.170.0, e.g. in https://fabricweb.z5.web.core.windows.net/oufr/6.169.0/
