### ISSUE TITLE
DetailsRow not rendering custom cell when column has onRender method

### ISSUE THREAD

**Issue by nsoeth** [OfficeDev/office-ui-fabric-react#9049]
### Environment Information 
 
- __Package version(s)__: 6.156.0
- __Browser and OS versions__: Chrome, Windows

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/anon/pen/rgejMg
 
#### Actual behavior:
 
When a column has a custom "onRender" method, the footer "onRenderItemColumn" method isn't called
 
#### Expected behavior:
 
overwrite the column "onRender" method

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
Haven't found a solution yet
 
Requested priority: (Blocking, High, Normal, Low) 
Normal

**Comment by nsoeth** [comment]
My quick and dirty solution was as follows:

```
const columns: IColumn[] = [];
detailsFooterProps.columns.forEach((column: IColumn): void => {
  const newCol = { ...column, onRender: undefined };
  columns.push(newCol);
});

return (
  <DetailsRow
	{...detailsFooterProps}
	columns={columns}
	onRenderItemColumn={(item: ITop, index: number, column: IColumn): JSX.Element => {
	  if (column.fieldName !== 'MyFieldIWantToDisplayDifferent') return null;

	  return (
		<div className='bold'>{column.fieldName}</div>
	  );
	}}
	item={{}}
	itemIndex={-1}
  />
);
```

I copied the columns to a new array (important to copy, otherwise all other rows are affected aswell) and then set the onRender method for each column on "undefined".

**Comment by jdhuntington** [comment]
Unfortunately it is the intent of `onRender` to be the highest priority callback for rendering a cell, and `onRenderItemColumn` is indeed a fallback if `onRender` is not provided.

Do I understand correctly you would like to override this behavior in the footer only? Your workaround might be the best option available, but I can ask around and see if anyone has other potential patterns to suggest.

**Comment by nsoeth** [comment]
Yes exactly. It was a little bit confusing because I thought I was in a "seperate container" (the footer) which will override the column's onRender method as it was deeper nested (thinking a little bit like in CSS with the nested attributes having a higher attribute than higher in the order ;-) ).

But thanks, I understand it now and with my workaround, it works.

**Comment by jdhuntington** [comment]
@nsoeth Please let me know if I can provide any further assistance. Also will keep this specific case in mind as we continue to iterate the details list. Thanks
