### ISSUE TITLE
DatePicker :Out of Bounds error getting cleared on focus

### ISSUE THREAD

**Issue by saidas3524** [OfficeDev/office-ui-fabric-react#9050]
### Environment Information 
- __Package version(s)__: the same version from the web portal [here](https://developer.microsoft.com/en-us/fabric#/controls/web/datepicker)
- __Browser and OS versions__: Chrome, windows

### Please provide a reproduction of the bug in a codepen:
  https://codepen.io/saidas3524/pen/MdybMP?editors=0011

Repro Steps:
follow the steps in codepen
1) Select any date on datepicker1 
2) Select any date on datepicker2 > date1
3) Change date1 now to be > date2
4) out of bounds error appears 
5) just focus/click on datepicker2 and 
6) out of bounds error disappears.

 
#### Actual behavior:
 1) Error message is removed.

 
#### Expected behavior:
 1) Error message should stay as the date1< date2 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No
 
Requested priority: (Blocking, High, Normal, Low)  Normal
 
Products/sites affected: (if applicable) https://microsoftoem.com

**Comment by jdhuntington** [comment]
Thanks for the report @saidas3524 ! Will get this sorted out.

**Comment by evlevy** [comment]
[There's a condition](https://github.com/OfficeDev/office-ui-fabric-react/blob/56cd0b49be95e536a0f503a32fbe113d3b8e8b17/packages/office-ui-fabric-react/src/components/DatePicker/DatePicker.base.tsx#L437) that skips validation if the text of the date has not changed. One option would be to make sure this check returns false if there is a date boundary present.

**Comment by saidas3524** [comment]
Thanks, it's working as expected.
