### ISSUE TITLE
MessageBar:- In scan mode focus is going to sensory icon and doesn't provide any information while navigate using Up/Down arrow key.

### ISSUE THREAD

**Issue by ndlganeshu** [OfficeDev/office-ui-fabric-react#9051]
## Actual behavior:
In scan mode focus going to sensory "(i)" icon and doesn't provide any information while navigate using Up/Down arrow key.

## Expected behavior:
In scan mode focus should not go to sensory "(i)" icon while navigate using Up/Down arrow key. 

![sensory_icon](https://user-images.githubusercontent.com/5468766/57529632-00897900-7353-11e9-86f2-f541a0ed22e2.png)

## Documentation describing expected behavior
In MessageBar component we are using the "Icon" component for this

issue repro with IE + Jaws Version : 2019.1904.29 ILM

**Comment by jdhuntington** [comment]
Thanks for the report @ndlganeshu - Will look into this today!
