### ISSUE TITLE
is Fabric 7 released ? 

### ISSUE THREAD

**Issue by asith-w** [OfficeDev/office-ui-fabric-react#9069]
I could see new UI here https://developer.microsoft.com/en-us/fabric#/get-started/web . but need to confirm   that Fabric 7 released or not . because following link still says it is released  around the first part of May 2019
https://github.com/OfficeDev/office-ui-fabric-react/wiki/Fabric-7

**Comment by JasonGore** [comment]
There are a couple of ways you can use these changes now.

There is [a link](https://developer.microsoft.com/en-us/fabric#/controls/web/fluent-theme) shown on that page that goes into more detail about the Fluent Theme changes.

There are also [beta builds of Fabric 7](https://www.npmjs.com/package/office-ui-fabric-react) being published that you can also try. As of writing, the most current release is `alpha019` which you could try: 

`npm i --save 'office-ui-fabric-react@7.0.0-alpha019`

We're looking at the end of May for Fabric 7 release and I've updated [the Fabric 7 page](https://github.com/OfficeDev/office-ui-fabric-react/wiki/Fabric-7) to reflect that. Thanks for calling it out!
