### ISSUE TITLE
Dialog close button shadow

### ISSUE THREAD

**Issue by ankitk94** [OfficeDev/office-ui-fabric-react#907]
### Bug Report

fabric version : 0.87.1

#### Describe the issue:

For dialog component, close button shadow is seen when button is hovered. Is there any workaround for this? 
One way is to provide styling to save button, but currently no way to provide the styling.

**Comment by mikewheaton** [comment]
Which browser are you using? Could you include a screenshot? I'm not seeing a shadow when I hover on the example on the [Dialog page](http://dev.office.com/fabric#/components/dialog).

**Comment by mdahamiwal** [comment]
This is a focus treatment for close button as X button is the default focusable element on dialog open.

**Comment by ankitk94** [comment]
If by default another element is focused, then also when I hover on "close" button, shadow is seen. The requirement is to remove the button shadow on hover (or focus via keyboard).

**Comment by dzearing** [comment]
It seems the close button is not an IconButton and therefore isn't getting the correct focus treatment.

The correct treatment is that the focus rectangle shows up only when the user interacts with the keyboard.

We have the `<Fabric>` component which abstracts adding the right root classes to enable focus rectangles. The focus mixin prefixes selectors with the `.ms-Fabric-isFocusVisible` flag.

**Comment by dzearing** [comment]
@leddie24 dig in, let me know if you need help

**Comment by cschleiden** [comment]
@ankitk94 are you using the dialog on a VSTS page? This looks very much like a local issue we have. Could you ping me at cschleid? I can help you resolve this.

@dzearing @leddie24 don't think this is a problem with OfficeFabric itself.

**Comment by ankitk94** [comment]
Yes, I am using it on VSTS page. Sure will ping you up

**Comment by ankitk94** [comment]
Adding class "bowtie-fabric" fixed the issue of button shadow in dialog, but created another issue.

It is forcing other non-fabric components to behave like fabric:

![image](https://cloud.githubusercontent.com/assets/6390909/22815721/6c23e73c-ef83-11e6-84c4-48283fcfea21.png)

The blue background appearing on hover is undesirable. Moreover, it affected the styling for all components which were used from VSSF.
