### ISSUE TITLE
Will there be an office ui fabric angular?

### ISSUE THREAD

**Issue by xtianus79** [OfficeDev/office-ui-fabric-react#9071]
For _how-to_ questions and other non-bugs, please use StackOverflow instead of Github issues. You can tag your questions with [office-ui-fabric](https://stackoverflow.com/questions/tagged/office-ui-fabric).

Will there be an office UI fabric for Angular instead of material?

**Comment by JasonGore** [comment]
We get this question occasionally, so I've added a response to this question on [our FAQ](https://github.com/OfficeDev/office-ui-fabric-react/wiki/FAQ#q-will-there-a-ui-fabric-react-for-angular). Please let me know if this doesn't address your question. Thanks!
