### ISSUE TITLE
Slider - Provide ability to style thumb

### ISSUE THREAD

**Issue by jdhuntington** [OfficeDev/office-ui-fabric-react#9073]
`Slider` accepts `buttonProps` which the documentation states:

> Optional mixin for additional props on the thumb button within the slider.

However, it is not clear what the "thumb button" actually *is*, and is surprisingly the entire slider and thumb widget. 

It should be possible to pass props for the thumb widget only.

See #9023

**Comment by khmakoto** [comment]
This is a non-issue, the `thumb` can be perfectly styled via the `styles` prop as shown in [this codepen](https://codepen.io/khmakoto/pen/JjdYjRp?editors=1010).
