### ISSUE TITLE
Link component has potential XSS vulnerability

### ISSUE THREAD

**Issue by prashkan90** [OfficeDev/office-ui-fabric-react#908]
### Bug Report

- __Package version(s)__: 1.2.2
- __Browser and OS versions__: Google Chrome 55.0.2883.87

#### Describe the issue:

Link component has potential XSS vulnerability. 
   ` <Link href='javascript:alert("test")'>I am a link with an href.</Link>`

#### Actual behavior:

Click on link triggers an alert popup

#### Expected behavior:

href input is sanitized.

I'm not sure if the expectation is that users should sanitize their strings before passing them to components - if so, please resolve.

**Comment by dzearing** [comment]
This is by design and is no different than what a simple `<A>` tag would allow as well. We do not add code to the page weight to scrub hrefs. This should be the implementers' concern, and likely a server side gate that prohibits users from trying to save malicious links.
