### ISSUE TITLE
DetailsList+MarqueeSelection selection does not work due to onSelectionChanged called twice

### ISSUE THREAD

**Issue by BigYu** [OfficeDev/office-ui-fabric-react#9088]
### Environment Information 
 
- __Package version(s)__: 6.143.0(also repro on 6.181.0)
- __Browser and OS versions__: Windows Chrome Version 74.0.3729.131 (Official Build) (64-bit)

### Please provide a reproduction of the bug in a codepen:
 

https://codepen.io/Yucong/pen/mYOVjp?editors=1112 

#### Actual behavior:
 

After clicking to select one or more rows, there is nothing selected.
Checking the console output you can see the onSelectionChanged triggered twice. The first call is the expected. I have no idea about how the second call was triggered to clear the selection.
 
#### Expected behavior:
 

Only the first expected call of onSelectionChanged triggered to select the row correctly.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: High
 
Products/sites affected: Not applicable

**Comment by JasonGore** [comment]
I looked at your CodePen and see the issue you described. However, there is [a similar example](http://localhost:4322/#/examples/detailslist/basic) which when [exported to a CodePen](https://codepen.io/jasongore/pen/MdJwwg?editors=0010) seems to work as expected with only one call to `selection` prop. I think there's a lot of other code in your CodePen that's obfuscating the implementation and suspect there could be an issue there causing the duplication.
