### ISSUE TITLE
File Type Icons are not up to date

### ISSUE THREAD

**Issue by RobPethick** [OfficeDev/office-ui-fabric-react#9090]
### Environment Information 
 
- __Package version(s)__: @uifabric/file-type-icons
- __Browser and OS versions__: all

### Please provide a reproduction of the bug in a codepen:
 
Not managing to produce a codepen as it relies on the @uifabric/file-type-icons package and I can't work out how to access that within there
 
#### Actual behavior:
 
File type icons are not current office icons - see update here
https://news.microsoft.com/europe/2018/11/29/say-hello-to-microsofts-new-office-icons/
 
#### Expected behavior:
 File type icons updated as office icons are updated

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No) I think this will require updating the CDN with the icons etc.
 
Requested priority: High
This seriously makes it hard to produce decent UI experiences with the icons being very different to the current office icons
 
Products/sites affected: (if applicable)

**Comment by JasonGore** [comment]
Spoke with @Jahnp  who will work on an approach for implementing and communicating. Will assign to him for now.

**Comment by Jahnp** [comment]
Indeed, thanks @JasonGore ! 

Hi @RobPethick, thanks for bubbling this up. We've actually been working behind the scenes for a few months on making this ready, and you can actually use the new Fluent item types today like this:

```ts
initializeFileTypeIcons(https://spoprod-a.akamaihd.net/files/fabric/assets/item-types-fluent)
```

Starting with Fabric 7, we'll make this the default CDN URL so you don't need to opt into the assets like this. I'll be updating docs to reflect this soon.

**Comment by Jahnp** [comment]
Reopening as I think this got auto-closed a bit too aggressively :)

**Comment by JasonGore** [comment]
PR #9105 says `Fixes #9090` and that's what triggers a close of the associated issue. You can prevent that by deleting the `Fixes` keyword in PRs. :)

**Comment by Jahnp** [comment]
@JasonGore I see, thank you, I knew there was a trigger in the PR itself to auto-close associated issues, but didn't realize it keyed off `Fixes`. Keeping a note for future PRs :)

**Comment by RobPethick** [comment]
Thanks @JasonGore and @Jahnp - the cdn is working well for me and I'm glad to have cleaner icons!

**Comment by Jahnp** [comment]
Great! Closing this now as I think we're good to go since Fabric 7 is out with the new icons.
