### ISSUE TITLE
Required visual hint not showing on DropDown when label is null

### ISSUE THREAD

**Issue by enriquin** [OfficeDev/office-ui-fabric-react#9119]
The "required" visual hint (*) is not shown on dropdown when the label is null (and hidden).

The proper behaviour should be just like in TextField: The hint is shown in the label, and if the label is not shown the hint is shown after the field.

### Environment Information 
 
- __Package version(s)__:  Latest
- __Browser and OS versions__: Chrome

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/Intnovaction/pen/xNqaLB

#### Expected behavior:
 
The visual hint (*) should be shown just as in TextField

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by JasonGore** [comment]
I'm marking this as a feature request but I think it should be relatively simple to implement. I already have a change working locally.
