### ISSUE TITLE
Switch between items in Combo Box options using keyboard

### ISSUE THREAD

**Issue by Vaikesh** [OfficeDev/office-ui-fabric-react#9120]
In a normal **Combo Box**, if we have multiple items starting with the same character, we must be able to jump to each item by keep on pressing the same character multiple times.

For example, if we have a list of items starting with A, (say Apple, April, Astro). By keeping on tapping A multiple times we must be able to jump from one selected item to another. 

![Combox_New_Feature_Request](https://user-images.githubusercontent.com/12531760/57847859-2c927780-77f5-11e9-862e-a4355b30baae.gif)

**Comment by JasonGore** [comment]
I think this would also apply to Dropdown. I'm going to tag this as a feature request. We should be able to consider it as a part of our [ComboBox/Dropdown refactor](https://github.com/OfficeDev/office-ui-fabric-react/issues/6030) and have added it to that issue.

**Comment by aneeshack4** [comment]
When we eventually get to the combobox/dropdown refactor, this would be a good thing to consider @joschect

**Comment by micahgodbolt** [comment]
This is not the current design of the combo box. Our autocomplete allows you to type more than just the first character, so we wouldn't support this mode.
