### ISSUE TITLE
There is circular dependency in ContextualMenu.tsx

### ISSUE THREAD

**Issue by chenxinyanc** [OfficeDev/office-ui-fabric-react#9122]
### Environment Information 
 
- __Package version(s)__: 6.156.0
- __Browser and OS versions__: Edge dev 76.0.152.0 on Windows 10

### Please provide a reproduction of the bug in a codepen:
There is currently no minimal test case that can repro this bug. We are consuming this package with Webpack, and when we use `webpack --mode development` to build the project, everything works fine, but when we use `webpack --mode production`, we will see runtime exception.
 
#### Actual behavior:
We see runtime exception with the following stack trace
```
TypeError: Cannot read property 'displayName' of undefined

(anonymous) (styled.tsx:64)
u (styled.tsx:60)
(anonymous) (ContextualMenu.tsx:9)
n (bootstrap:19)
(anonymous) (asap.ts:1)
n (bootstrap:19)
(anonymous) (pipe.ts:26)
n (bootstrap:19)
(anonymous) (_wks.js:11)
n (bootstrap:19)
(anonymous) (Button.types.ts:300)
n (bootstrap:19)
(anonymous) (MessageBar.types.ts:179)
n (bootstrap:19)
(anonymous) (Notebook.tsx:4)
n (bootstrap:19)
(anonymous) (index.tsx:7)
n (bootstrap:19)
(anonymous) (bootstrap:83)
(anonymous) (bootstrap:83)
…
```
The line with error is Line 9 below
https://github.com/OfficeDev/office-ui-fabric-react/blob/74739d7e4154985c44ecd024d535d3a0b3b96627/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.tsx#L1-L14
where `ContextualMenuBase` is `undefined`.

Actually, there is a cyclic reference in `ContextualMenu.tsx` with `ContextualMenu.base.tsx`
https://github.com/OfficeDev/office-ui-fabric-react/blob/3da6cfad12c7ccb7030e047d48438b1c50217d9c/packages/office-ui-fabric-react/src/components/ContextualMenu/ContextualMenu.base.tsx#L36-L38
 
#### Expected behavior:
There should be no exception even with `webpack --mode production`.

#### Priorities and help requested:

Are you willing to submit a PR to fix? Yes

I have done a [hot fix on ContextualMenu.js and ContextualMenu.base.js](https://github.com/OfficeDev/office-ui-fabric-react/files/3187250/ContextualMenu.zip), moving `ContextualMenu` definition into ContextualMenu.base.js and revmoving the cyclic imports. It works locally. However, I'm not able to run `npm install` in the root of this repo. I keep seeing the following error
```
registry.npmjs.org/node-sass/4.10.0      | postinstall$ node scripts/build.js
(node:17636) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
registry.npmjs.org/node-sass/4.10.0      | postinstall: gyp ERR! not ok
registry.npmjs.org/node-sass/4.10.0      | postinstall: Build failed with error code: 1
registry.npmjs.org/node-sass/4.10.0      | postinstall: Exited with 1
 ERROR  node-sass@4.10.0 postinstall: `node scripts/build.js`
Exit status 1
at Error: node-sass
at <anonymous>       Users/xinychen/.rush/node-v12.2.0/pnpm-2.19.2/node_modules/pnpm/lib/node_modules/@zkochan/npm-lifecycle/index.js:301     var er = new Error('Exit…
at emit              events.js:196
at <anonymous>       Users/xinychen/.rush/node-v12.2.0/pnpm-2.19.2/node_modules/pnpm/lib/node_modules/@zkochan/npm-lifecycle/lib/spawn.js:55  cooked.emit('close', cod…
at emit              events.js:196
at maybeClose        internal/child_process.js:1011
at <anonymous>       internal/child_process.js:416
at emit              events.js:196
at <anonymous>       net.js:586
```
I would be appreciate it if you can help to fix this issue.

Requested priority: Normal

Products/sites affected: N/A

**Comment by chenxinyanc** [comment]
It seems that my node version (v12) is too high and [node-sass v4.10.0](https://github.com/sass/node-sass/releases/tag/v4.10.0) does not have pre-built binary for me. Locally hacked node-sass to use [v4.12.0](https://github.com/sass/node-sass/releases/tag/v4.12.0) and packages installed successfully.

**Comment by JasonGore** [comment]
Thanks for the PR!
