### ISSUE TITLE
Coachmark render bug Safari - teaching bubble content text size is reduced

### ISSUE THREAD

**Issue by pleb** [OfficeDev/office-ui-fabric-react#9129]
### Environment Information 
 
- __Package version(s)__: 6
- __Browser and OS versions__: Safari (Mac Majave 10.14.4) and iPhone (12.2)

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/anon/pen/gJWdLb

 
#### Actual behavior:
 
After a short time, approximately 1-2 seconds, the text reduces in size.

![Image from iOS (1)](https://user-images.githubusercontent.com/595869/57907012-5617d580-78bf-11e9-8e0d-d59acef0736d.jpg)
 
#### Expected behavior:
 
![Image from iOS](https://user-images.githubusercontent.com/595869/57906991-43050580-78bf-11e9-8a77-e32652289386.jpg)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes, but I would need help in identifying the issue. It could also possibly be a rendering bug within Safari.
 
Requested priority: Normal

**Comment by v-dhiraj** [comment]
testing

**Comment by v-dhiraj** [comment]
testing

**Comment by v-dhiraj** [comment]
testing

**Comment by JasonGore** [comment]
I see this happening on the [Coachmark component page](https://developer.microsoft.com/en-us/fabric#/controls/web/coachmark) as well (with a cutoff that's a separate website issue):

<img width="689" alt="Screen Shot 2019-05-17 at 2 50 00 PM" src="https://user-images.githubusercontent.com/26070760/57957967-14812d80-78b3-11e9-9145-d6245d7b4e14.png">

**Comment by aneeshack4** [comment]
Both the codepen & the example page look fine now... possible doesn't repro anymore... @pleb is this happening for you? 

I tested on Firefox & Chrome:
![image](https://user-images.githubusercontent.com/4161791/59226983-1c1db480-8b89-11e9-8509-ebbfdc7a28d2.png)
![image](https://user-images.githubusercontent.com/4161791/59226993-22139580-8b89-11e9-8bf8-3dda783dad34.png)

**Comment by pleb** [comment]
@aneeshack4 Sorry, but I'm no longer working for the client who had this issue. So, I can't easily test if it's fixed. I did notice though, you mentioned testing with Firefox and Chrome, but the render bug is a Safari only issue.

**Comment by aneeshack4** [comment]
@pleb no worries! I just checked and it looks fine on Safari too: 
![image](https://user-images.githubusercontent.com/4161791/59369518-73d92e80-8cf5-11e9-9691-60aabf1dbd18.png) so I'll go ahead & close this. If it comes up again, please feel free to reopen.
