### ISSUE TITLE
Image: Does not handle loaded event correctly in Edge

### ISSUE THREAD

**Issue by AbhinavSTeotia** [OfficeDev/office-ui-fabric-react#913]
### Bug Report

- __Package version(s)__: "0.74.0"
- __Browser and OS versions__: Edge on Win10

#### Describe the issue:

ChoiceGroup options accepts imageSrc. In one of the cases imageSrc is CDN url.

The the image is never shown on first load, this happens only in following condition

Browser is edge. Works fine on chrome/FF
Hard refresh(ctrl+f5) is done (browser cache off)

#### Actual behavior:

Image is never loaded, the css of element remains "is-notLoaded". Although we can observe network request being made and fulfilled with 200 response.

On debug, the image load works fine, hence stuck on root-causing it further. Relevant src - Image.js -> Image.render.

#### Expected behavior:

As in case of chrome/ff, the image should show up when load is complete.

### If applicable, please provide a codepen repro:

http://codepen.io/abhinavsinghteotia/pen/YNeyqe/

Clear browser cache

**Comment by AbhinavSTeotia** [comment]
Same issue as tracked here : https://github.com/OfficeDev/office-ui-fabric-react/issues/694
Not able to re-open, hence creating new issue.

**Comment by dzearing** [comment]
@dagoff Please try to repro again.

**Comment by mikewheaton** [comment]
I'm only able to repro with an SVG, not a PNG or JPG. As far as I can tell the browser's `load` event is triggered regardless of the image format. I'm having trouble getting breakpoints to work in Edge to actually see the event fire though.

**Comment by mikewheaton** [comment]
Here's another CodePen that includes an `onLoad` prop to test the load event: http://codepen.io/mikewheaton/pen/BpYwNZ?editors=0011

What I'm seeing is that:
- on initial page load, the `load` event is triggered but it isn't shown
- on subsequent page loads, when the image is already cached, it shows as expected

**Comment by dzearing** [comment]
This should now be resolved.
