### ISSUE TITLE
IconButton gets white background when disabled

### ISSUE THREAD

**Issue by alex3683** [OfficeDev/office-ui-fabric-react#9131]
### Environment Information 
 
- __Package version(s)__: office-ui-fabric-react: 6.182.1, @uifabric/fluent-theme: 0.16.9
- __Browser and OS versions__: probably irrelevant, but: Chrome 74.0.3729.157, Windows 10

### Please provide a reproduction of the bug in a codepen:
 
Reproduction possible on current component documentation page for the button control: https://developer.microsoft.com/en-us/fabric#/controls/web/button
 
#### Actual behavior:
 
If the IconButton is set to disabled via property, it receives a white background-color. On the documentation page this can be validated by using the browser's element inspector. If not disabled, it has a transparent background.

Enabled:
![iconbutton-enabled](https://user-images.githubusercontent.com/768322/57915133-682e4f80-7890-11e9-9111-cf6d27f45129.PNG)

Disabled:
![iconbutton-disabled](https://user-images.githubusercontent.com/768322/57915158-754b3e80-7890-11e9-88db-4933207cfd6c.PNG)

 
#### Expected behavior:
 
If the IconButton is set to disabled via property, it should remain having the transparent background-color by default. The ActionButton has this behavior.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: not yet

**Comment by JasonGore** [comment]
@Vitalius1 did a similar fix for Button's styling on our Fabric 7 preview branch and said he could fix for Fabric 6. Thanks!
