### ISSUE TITLE
Hover card jump

### ISSUE THREAD

**Issue by chaofeng2014** [OfficeDev/office-ui-fabric-react#9132]
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:
 
The hover card is "jumping" if user move mouse into the card when the card is rendering
![fabric_hovercard_jump](https://user-images.githubusercontent.com/6550896/57948416-71bab600-7896-11e9-8709-5e8b31cfa3f8.gif)

Reproable on fabric display site: https://developer.microsoft.com/en-us/fabric#/controls/web/hovercard 
 
#### Expected behavior:
 
The card should not "jump" when it is rendering

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by chaofeng2014** [comment]
![fabric_hovercard_jump](https://user-images.githubusercontent.com/6550896/57948356-4a63e900-7896-11e9-8fcd-f483d498c562.gif)

**Comment by chaofeng2014** [comment]
![hovercard_jump_bug](https://user-images.githubusercontent.com/6550896/57948372-564fab00-7896-11e9-9fe3-2d949216f92f.gif)

**Comment by JasonGore** [comment]
I had trouble reproducing this at first, and then found two distinct cases:

### Case 1: When the mouse is moved into the card after it is expanded:

![HovercardJump1](https://user-images.githubusercontent.com/26070760/57949753-1f7b9400-789a-11e9-87fd-1ba85cc5cf7a.gif)

### Case 2: When the rendered card has little space to render relative to the bottom, it jumps down regardless of mouse movement:

![HovercardJump2](https://user-images.githubusercontent.com/26070760/57949711-0246c580-789a-11e9-9395-52b4fa131c69.gif)

**Comment by gggjtgxing** [comment]
Hi, any update here, when can we expect this issue get fixed, thanks

**Comment by JasonGore** [comment]
Hopefully early this week. We're testing a fix right now. Thanks!

**Comment by gggjtgxing** [comment]
Hi, we have more people complain about the card jump issue, it's very obvious and kind of annoying,
@sopranopillow  I saw you closed that PR, are you going to have a another fix ?

**Comment by sopranopillow** [comment]
Hi, sorry about taking long. I found a fix and will do a PR for it. This should fix it.

**Comment by atneik** [comment]
@sopranopillow I was wondering if the fix worked? Let me know if I could help

**Comment by dzearing** [comment]
@ecraig12345 reping.

**Comment by JasonGore** [comment]
This issue appears to have been introduced with #8688.

**Comment by joschect** [comment]
@dzearing and @JasonGore I'll hop on this.

**Comment by dzearing** [comment]
@joschect status on this one?

**Comment by dzearing** [comment]
This has precedence over other work.
