### ISSUE TITLE
Monorepo setup

### ISSUE THREAD

**Issue by jeremy-coleman** [OfficeDev/office-ui-fabric-react#9143]
Update here https://github.com/jeremy-coleman/office-react-mono-simplified/tree/jss-only?files=1

example setup here: https://github.com/jeremy-coleman/office-react-mono-simplified
was done quickly just to give an idea, it builds kind of. memory issues with tsc on my end

I previously brought this issue up, but the focus of the discussion shifted to bundle size and webpack, which is neither the point nor relevant. 

As background, I have been struggling to get fabric working with multi target setups and bundlers. I understand why it doesnt work in each case, the problem is logically trying to find a solution that fixes all cases simultaneously.

Currently , i alias the ouifr and resolution in package json and have a postbuild script that repackages and bundles it into the official package names. It works really well for my needs actually.

I understand your consumer base is broad , and meeting your requirements to integrate with 20+ products is not an easy task. I believe the following changes will ease that burden. The goal is to have only 1 package.json for dev. 

1. Move all @uifabric sub projects inside of the office ui fabric folder. They are all requirements of the react lib, they all use context and are mostly bound to a react implementation. This also means each published version of office ui fabric has a dependency on each fabric package with a random semver that does not match the parent or peer packages in anyway. Theres no reason to ever install any of them independently, because by installing the office package they will be included. Including any @uifabric/* package in your package has no practical use, and will only lead to potential duplications.

2. Remove all references to office/lib and office/lib-commonjs . Its certainly ok to publish using that format, but consumers nor any component usage should ever import from the build folders, this is major reason fabric doesnt work correctly with gatsby/next/other build tools.

3. Publish all packages under the same semver. There is no reason at all to have different versions. Office react and fabrics only dependencies are react, prop types, and tslib and 1 file from @microsoft/load themed styles, so theres no underlying reliance on vendors that would neccesitate different packages, the different versioning is arbitrary. Imagine if angular published @angular/core 6.5 and @angular/http 7.3 for the same release. Thats essentially what is happening.

4. Move test and doc related code outside of the source code. Also delete all the entry component.ts files, just export everything from index.ts and the same office/lib/component paths to the corresponding folders with an index.ts of the public exports.

5 include the @microsoft/load themed styles internally. Its 1 file and their build is broken. The package json doesnt have a module field , and the lib es6 bundle uses __assign from tslib without importing it. Its just 1 file, copy and paste does the trick.

Thats it, it probably took me longer to type that out than it would take to implement the changes. You can still publish as many package implementations as you want, its just you will create the package.json used for publishing separately from the one used for development. Because you have no dependencies, this is exceptionally easy to do without issue. The package configs just change from (many -> many) to (1->many)

If you make a folder labeled @fabric inside the main office ui folder , copy/paste the fabric sources inside and rename each ‘src’ to the corresponding fabric package name without the org identifier, then set the baseUrl in .tsconfig to ./src , everything should resolve without any further changes

**Comment by kenotron** [comment]
Would you mind explaining a bit more about your goals and problem? So far, from this issue alone, I can only gather that you're having issues with:

> I have been struggling to get fabric working with multi target setups and bundlers.

I'm quite familiar with bundlers and build systems in a large scale (am contributor #1 in OWA), and would love to help you get to a solution. It would be instructive if you can maybe create a repo that demonstrates the problem in CONSUMING the OUFR packages that makes you struggle with multi-target / bundlers.

In this case, it seems like you're proposing a sweeping change in how we package / bundle / set up monorepo (which is no small undertaking I assure you due to all the fall out with build defs, release CI / CD steps). I think I've seen the other issue you mentioned before, but like you said the discussion went on tangents.

**Comment by jeremy-coleman** [comment]
Thanks for your willingness to help Ken, but im not sure there is a fix. Personally, the two main issues that usually arise come from referencing a module from lib/ then switching from client side (cra) to node (next or electron) . Also the x.scss.ts files baffle me. Fixing is easily done with postinstall scripts to rebundle and also required for my use case to expose internal apis to all env targets.

The purpose of my suggestions above are just my thoughts on how to improve the lib and drastically simplify the needlessly complex dependency graph and build , did you try running the bundle i linked above? I cant get tsc to compile defs without memory fails:/ its been happening the last month or so, and not ouif specific

**Comment by jeremy-coleman** [comment]
@kenotron I updated some file paths , among a few other things. also ran the remaining .scss files through a conversion script, they need a look though. 
converted files here.
https://github.com/jeremy-coleman/office-react-mono-simplified/tree/wip-may23/styles/ts

general updates here - still having memory problems running the typescript compiler. not sure what's going on there. 
https://github.com/jeremy-coleman/office-react-mono-simplified/tree/wip-may23

notable changes:
merged the utilities folder and @uifabric/utilities
moved all imports of IStyleFunctionOrObject to merge-styles. 
moved common folder interfaces into @uifabric/utilities. The only reason the common folder is still 
  included is for the ~10 scss files (which are also close to fixed)
added loadLegacyTheme / to @uifabric/utilities

**Comment by jeremy-coleman** [comment]
For reference
https://github.com/microsoft/TypeScript/issues/31553#issuecomment-495443846

**Comment by jeremy-coleman** [comment]
@kenotron 
working example with all major packages included and a very small demo . im afraid to look at the calendar and picker components  (but at least no scss)
ts 3.5 fixes issues with react types above 16.8.12 as well - and introduces some new error types
https://github.com/jeremy-coleman/office-react-mono-simplified
yarn -> yarn start

**Comment by kenotron** [comment]
Thanks Jeremy for the feedback and the simplified repo. 

Some thoughts after having an offline discussion with @dzearing: I realize our layout isn't ideal, but I'm going to close this due to the fact that sweeping repo changes are probably just going to come in the form of some planned work item going forward. Investment in the medium to long term for this repo is likely going to be in build tooling and maybe switching to a different mono repo management system. I'm marking this as "not an issue" for a faster bot closure.

**Comment by jeremy-coleman** [comment]
I will close, also to share, i flattened out the component folder locally, and removed the outdated pickers components, bundle size down to 650kb including the fabric deps. Could probably get it down to 400
