### ISSUE TITLE
Missing import files "IDetailsRowStyles" in office-ui-fabric-react

### ISSUE THREAD

**Issue by SuganthanMathivanan** [OfficeDev/office-ui-fabric-react#9147]
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by kenotron** [comment]
Can you come up with a small repo with a repro here? 

```ts
import { IDetailsRowStyles } from "office-ui-fabric-react";
```

Seems to work for me

**Comment by AnjaniChallamcherla** [comment]
I am having the same issue.
![image](https://user-images.githubusercontent.com/42473451/59416289-00025900-8dbd-11e9-9eed-c4a826c9e0c1.png)

@kenotron I added the same line of code you mentioned above, but still getting the same error. Do I need to install anything more?
