### ISSUE TITLE
ComboBox: onResolveOptions receives wrong type of options

### ISSUE THREAD

**Issue by basovic88** [OfficeDev/office-ui-fabric-react#9149]
### Environment Information 
 
- __Package version(s)__: 6.183.0

### Please provide a reproduction of the bug in a codepen:

No relevant.
 
#### Actual behavior:
 
onResolveOptions receives options as an Object instead of `IComboBoxOption[]`.

For instance, we now get:

```
{
   0: { key: 0, text: "foo", selected: true },
   1: { key: 1, text: "bar" }
}
```
Instead of the expected:
```
[
   { key: 0, text: "foo", selected: true },
   { key: 1, text: "bar" }
]
```
 
#### Expected behavior:
 
onResolveOptions receives options as `options: IComboBoxOption[]` in accordance with its type definition `onResolveOptions?: (options: IComboBoxOption[]) => IComboBoxOption[] | PromiseLike<IComboBoxOption[]>`.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Blocking
 
Products/sites affected: (if applicable)

**Comment by kenotron** [comment]
Subtle, but this is the bug:
```ts
{...[1,2,3]}
```
vs

```ts
[...[1,2,3]]
```
