### ISSUE TITLE
ComboBox onChange callback should include reference to combobox

### ISSUE THREAD

**Issue by jdhuntington** [OfficeDev/office-ui-fabric-react#9152]
**Describe the feature that you would like added**

ComboBox should pass reference to self to the onChange callback

**What component or utility would this be added to**

ComboBox

**Additional context/screenshots**

#9047

**Comment by jdhuntington** [comment]
cc @joschect

**Comment by joschect** [comment]
@jdhuntington seems reasonable!

**Comment by ecraig12345** [comment]
I don't think our other onChange callbacks do this? So I don't see why the ComboBox should be any different.

**Comment by joschect** [comment]
That's a good point @ecraig12345 . I think we could make the argument that it is easy to add an identifier to the callback in the combobox's parent. 
Something like:
`<Combobox onChange={(ev)=> this._onComboBoxChange(ev, id)}`
Or a simple combobox wrapper could take care of this pretty easily too like [this](https://codepen.io/slimemold/pen/wbrYmo?editors=1111)

**Comment by ecraig12345** [comment]
Yeah, based on patterns used within our codebase, I think that's "right"/canonical way to achieve what the original issue author wanted--no need for additional API surface. (Especially additional API surface that would eventually need to be duplicated in other components and callbacks for consistency.)
