### ISSUE TITLE
Mobile scrolling disabled when overlay component present

### ISSUE THREAD

**Issue by pingj** [OfficeDev/office-ui-fabric-react#9155]
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)
Safari/Chrome on iPhone, or android

### Please provide a reproduction of the bug in a codepen:
 https://codepen.io/jp_apple/pen/vweewG
 
This is the fabric change that caused this issue: https://github.com/OfficeDev/office-ui-fabric-react/pull/5804

#### Actual behavior:
Scroll-able component on top of the overlay does not scroll in mobile device. 
Related bug in SharePoint modern pages: 
Incident 116980638 : [PROD] Online: Zones (13507600) - **Reproduceable** Long navigation sub-menu on a Sharepoint site unable to scroll on mobile browsers 
 
#### Expected behavior:
When overlay present, we understand the page does not scroll, but the components on top of the overlay should still scroll. 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 No
Requested priority: (Blocking, High, Normal, Low) 
 Normal
Products/sites affected: (if applicable)
All SharePoint modern pages. We've check in a workaround to overwrite the change added in https://github.com/OfficeDev/office-ui-fabric-react/pull/5804 when the event happens not directly on the overlay components.

**Comment by kenotron** [comment]
Thanks @joschect, for taking a look!

**Comment by joschect** [comment]
This is pretty closely related to #8855 , I've added it there so we can track it all in one place!

**Comment by cliffkoh** [comment]
Sorry, reopen this issue to let it close in a way that adheres to our standard process.

@pingj please feel free to close the issue ahead of time if you're happy with the resolution, if not our bot will close it.
