### ISSUE TITLE
DetailsList + ScrollablePane + Sticky : Only one scroll bar at the time works

### ISSUE THREAD

**Issue by Termit1975** [OfficeDev/office-ui-fabric-react#9161]
### Environment Information 
 
- __Package version(s)__: 6.180.0
- __Browser and OS versions__: Chrome 74.0.3729.157

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/Termit1975/pen/yWPeEe
 
#### Actual behavior:

When the window fits the entire width of the DetailsList, the vertical scrollbar is fine and there is no horizontal scrollbar. THIS IS FINE.

When the window fits the entire height of the DetailsList, the horizontal scrollbar is fine and there is no vertical scrollbar. THIS IS FINE.
 
When both scrollbars are needed, the horizontal scrollbar has the following bugs:

- Visible only when you scroll down to the bottom.
- You cannot interact with the horizontal scrollbar (disabled).
 
#### Expected behavior:
 
When both scrollbars are needed : 

- They should be both visible.
- They should not be disabled.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)  
Requested priority: (High)  
Products/sites affected: (Our main product in order to adopt this library)

**Comment by Termit1975** [comment]
NOTE: If I remove the Sticky and ScrollablePane parts. The horizontal scrollbar is still only visible when the vertical scroll reach the end. This time the scrollbar is not disabled.

**Comment by marygans** [comment]
@KevinTCoughlin It seems like this issue might be similar/related to this open [horizontal scrolling bar](https://github.com/OfficeDev/office-ui-fabric-react/issues/8589) issue. Are you already working on it?

**Comment by Termit1975** [comment]
Hi, since I don't have any footer for the Sticky component, I added stickyPosition={StickyPositionType.Header}, now I can interact with the scrollbar.

**Comment by marygans** [comment]
Hi @Termit1975 Im glad you were able to figure it out!

Do you have any more concern related to this issue? Please feel free to close the issue if you're happy with the resolution that you found.

**Comment by Termit1975** [comment]
No, horizontal scrollbar should be visible at all time. In my case removing the footer from the sticky, made the scrollbar interactable.

**Comment by kenotron** [comment]
Seems like the desired behavior isn't reached here yet... @marygans can you take another look at this? @KevinTCoughlin can you also respond to Mary's question about the other issue?

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin It seems like this issue might be similar/related to this open [horizontal scrolling bar](https://github.com/OfficeDev/office-ui-fabric-react/issues/8589) issue. Are you already working on it?

Sorry, lost track of this while I was OOF. 

If I'm understanding the issue properly as shown in https://codepen.io/Termit1975/pen/yWPeEe when the window is resized so that _both_ `overflow-y` and `overflow-x` are `scroll` then this looks like a legitimate issue.

It does not look related to https://github.com/OfficeDev/office-ui-fabric-react/issues/8589 which is describing a race condition that causes the horizontal scrollbar to unnecessarily render when the viewport is large enough to _not_ `overflow-x: scroll`.

**Comment by Termit1975** [comment]
if I add:  constrainMode={ConstrainMode.unconstrained} to the DetailsList, the bug goes away. I guess I had to RTFM.
