### ISSUE TITLE
CommandBar renders old items

### ISSUE THREAD

**Issue by goodoldneon** [OfficeDev/office-ui-fabric-react#9172]
### Environment Information 
 
- __Package version(s)__: 6.184.0
- __Browser and OS versions__: Chrome 74.0.3729.157 and OSX 10.14.4

### Please provide a reproduction of the bug in a codepen:
 
Unfortunately, I'm not able to reproduce this bug in CodePen.
 
#### Actual behavior:
 
The `items` prop passed to `CommandBar` changes a few times very quickly (within 100 ms). Sometimes (maybe 10% of the time), `CommandBar` renders the `items` prop from a previous render.

This only happens during a URL change. I wonder whether there's a race condition that's exacerbated when a lot of painting is happening.

The following image demonstrates the stale `items`. Each line has the component and its function (e.g. `CommandBarBase.render`) and the unique ID of the `items` array. The problem:

**`renderedData` is outdated which is causing the `CommandBarBase._onRenderData` to render old data.**

![image](https://user-images.githubusercontent.com/20100586/58144693-6b716480-7c1d-11e9-81f7-bf81b1b1ba1b.png)

In `ResizeGroupBase`, why is `onRenderData(dataToMeasure)` or `onRenderData(renderedData)` called? This seems like it causes old state to render. Should `onRenderData(this.props.data)` be called instead?

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: High
 
Products/sites affected: (if applicable)

**Comment by goodoldneon** [comment]
Also, this problem is "fixed" when I force an another render in `MyComponent`. But that's hacky.

```js
useEffect(() => {
  update();
}, [items.length]); // eslint-disable-line react-hooks/exhaustive-deps
```

**Comment by kenotron** [comment]
@christiango has a version of this that uses `useLayoutEffect` and `useEffect` to achieve measurement without this jank. I'm not sure how to completely fix this one, so I'm gonna calling the experts here - @micahgodbolt (listed code owner)

I think the component's main job is to ensure what's rendered has been measured. So it might show some discrepancy during that 10% of the time for you. Maybe a feature here is to integrate that hooks based version in Fabric 7+ when we have hooks support.

**Comment by micahgodbolt** [comment]
The reason that `dataToMeasure` is use in the render function is that this.props.data is only the initial data passed into the control. The resizeGroup initially sets dataToMeasure to this.props.data, but if that data doesn't fit within the space, it modifies the state (using the onReduceData function) and then measures again. This can happen several times before all of the content fits in the given space. So the final rendered items come from state, not from props.

**Comment by goodoldneon** [comment]
@kenotron, is there a way I can try out the new version? I installed the beta for version 7, but it looks like `ResizeGroup` isn't updated yet.

@micahgodbolt, that makes sense. But could you put `renderedData` in a ref instead of state, to keep it from getting outdated? But you'd need to manually trigger a render, since refs don't trigger a render.

**Comment by micahgodbolt** [comment]
Is the problem that you are updating props quickly and we're having async issues? Do we need to monitor for those new incoming props and make sure to interrupt the current calculations?

One possible option might be to change the "onReduceData" to simply () => undefined. This basically short circuits the resizing logic and says to use what's being given. Then once data has been updated, remove that onReduceData. Worth a shot at least.

**Comment by goodoldneon** [comment]
> Is the problem that you are updating props quickly and we're having async issues? Do we need to monitor for those new incoming props and make sure to interrupt the current calculations?

I don't think my issue is purely an async issue, since I can't reproduce it in CodePen. This "old items" issue only happens on a route change (I'm using `react-router`). This is the pen where I tried to repro the bug, but couldn't:

https://codepen.io/goodoldneon/pen/XwzxWg

<hr />

> One possible option might be to change the "onReduceData" to simply () => undefined. This basically short circuits the resizing logic and says to use what's being given. Then once data has been updated, remove that onReduceData. Worth a shot at least.

Tried that, but the issue still happens.

<hr />

I feel bad creating this ticket for an issue I can't repro in CodePen, since that makes it a goose chase.

**Comment by micahgodbolt** [comment]
yeah, happy to help where we can, but without a repro it's really hard for us to dig in and investigate. could be a react router bug for all we know.

**Comment by goodoldneon** [comment]
Understandable. I'll close the issue.
