### ISSUE TITLE
On Chrome for Android, the picker text field does not clear after selecting a suggestion

### ISSUE THREAD

**Issue by jacksonv1lle** [OfficeDev/office-ui-fabric-react#9175]
### Environment Information 
 
- __Package version(s)__: 6.184.0 
- __Browser and OS versions__: Chrome for Android

### Please provide a reproduction of the bug in a codepen:
 This bug can be reproduced on the [People Picker component page](https://developer.microsoft.com/en-us/fabric#/controls/web/peoplepicker). 

- On Chrome for Android, click on the People Picker text field.
- Type 'c' 
- Select a persona item from the suggestions

#### Actual behavior:
 
The suggestions list disappears briefly and the selected persona appears in the selected items list but the text field still contains the 'c' character.
The suggestion list then automatically re-open again.

#### Expected behavior:

The suggestions list disappears and the selected persona appears in the selected items list.
The 'c' character should be removed from the text field (as per desktop browser functionality) and the suggestions list remains closed until another key is pressed.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal 
 
Products/sites affected: (if applicable) N/A

**Comment by kenotron** [comment]
I got a hold of an Android phone and was able to repro this! Now onto investigating why this is happening...

**Comment by kenotron** [comment]
OH MY GOSH! I found the issue... it's an async timing bug!

**Comment by jacksonv1lle** [comment]
Great! Thanks for your service
