### ISSUE TITLE
TextField Placeholder Font-Size

### ISSUE THREAD

**Issue by SudharsanSukumar** [OfficeDev/office-ui-fabric-react#9181]
### Bug Report

- __Package version(s)__: 6.180.0
- __Browser and OS versions__: (all)

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: High

Products/sites affected: Microsoft Planner

#### Describe the issue:

Setting a font-size on a text field via css does not affect the placeholder size. This used to work as expected but I think this PR: https://github.com/OfficeDev/office-ui-fabric-react/pull/8018 changed the behavior by setting the font-size via ::placeholder in TextField.styles.tsx. 

#### Actual behavior:

Setting font-size: 28px on a TextField sets the text font-size to 28px but the placeholder font-size remains the default 14px

#### Expected behavior:

Setting a font-size of input text and placeholder should be the same.

### If applicable, please provide a codepen repro:

https://codepen.io/anon/pen/EzodgX

**Comment by kenotron** [comment]
I modified the CSS to add a `::placeholder` there to up the size of the placeholder. Seems like a pretty minor workaround. Would this solve your issue?

https://codepen.io/anon/pen/MdrPLv

**Comment by SudharsanSukumar** [comment]
That workaround would fix this issue but other places where we set the input font-size would need this fix as well which may end up being many files (not to mention it's hard to find all the places we do this)

**Comment by kenotron** [comment]
I think it would make sense if the input::placeholder has a fontsize inherit rather than a hardcoded value, right?

**Comment by kenotron** [comment]
I'm going to make it inherit from the input and then for the cases where we need to override, those would be exceptions. I think that would address your concern.

**Comment by kenotron** [comment]
This is right, we unnecessarily overrode the ::placeholder. I'm going to remove that override. It should address your needs.
