### ISSUE TITLE
Problem with nestingDepth to nestingDepth?

### ISSUE THREAD

**Issue by HollowYourDreams** [OfficeDev/office-ui-fabric-react#9187]
Hi, guys! 

Trying to start ur GroupedList example and have a npm Error (nestingDepth: number, item: IExampleItem, itemIndex: number) cannot be assigned to (nestingDepth?: number, item?: IExampleItem, itemIndex?: number)

How can I fix this? Using C# .Net Core 
Project from ur git(by the "Get started")

**Comment by kenotron** [comment]
Okay, this is a little vague. Would you please attach a codepen example of this issue as suggested by the bug template? It would help expedite a fix / address your question. Further, you can tap into a larger community if this is a usage question by submitting this question in stackoverflow with the office-fabric tag: https://stackoverflow.com/questions/tagged/office-fabric
