### ISSUE TITLE
Nesting styled components no longer works

### ISSUE THREAD

**Issue by brandonthomas** [OfficeDev/office-ui-fabric-react#9189]
- __Package version(s)__: >=6.185 due to dependency on 6.39 of utilities package
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
Working: https://codepen.io/anon/pen/gJoJjN
Not working: https://codepen.io/anon/pen/eayaLE

- Wrap existing styled component in another styled component and inject default styling
 
#### Actual behavior:
 Styling is not preserved or injected and component acts like it's default without additional styling

#### Expected behavior:
 Styling through all levels should be preserved

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Unfortunately I don't have time
 
Requested priority: (Blocking, High, Normal, Low)  Blocking
 
Products/sites affected: (if applicable) Admin controls package, M365 Admin Center, SCC, potentially others.

**Comment by brandonthomas** [comment]
https://github.com/OfficeDev/office-ui-fabric-react/pull/8761

**Comment by brandonthomas** [comment]
https://github.com/OfficeDev/office-ui-fabric-react/commit/cc3ff2379bd7df5fa55800f97ec83d2242d9a11e#diff-cb9bad5cba07095f248057b371037ca9R71

**Comment by brandonthomas** [comment]
@dzearing @JasonGore

**Comment by JasonGore** [comment]
I'm on it today. We'll either have a fix or revert it for the next release.

**Comment by brandonthomas** [comment]
Thanks for getting on this so quick guys!
