### ISSUE TITLE
Dialog component should read out title and subText when dialog is opened.

### ISSUE THREAD

**Issue by KeiraYang** [OfficeDev/office-ui-fabric-react#9190]
## Actual behavior:
![image](https://user-images.githubusercontent.com/28148759/58225822-8693bf80-7d56-11e9-869b-125162d15f5b.png)
When dialog opened, only the title is readed. The content inside is never been read out when focus on any element in the dialog.
## Expected behavior:
The content should be read out when dialog is opened.

**Comment by micahgodbolt** [comment]
this issue has already been captured in #8061

@betrue-final-final should a modal always read the entire contents when opened? Do you know what the guidance is here?
