### ISSUE TITLE
[DetailsList] Focused row checkmark needs to be clicked twice to unselect

### ISSUE THREAD

**Issue by rhublard** [OfficeDev/office-ui-fabric-react#9191]
### Environment Information 
 
- __Package version(s)__: 6.185.0
- __Browser and OS versions__: Chrome, Firefox, IE 11

### Please provide a reproduction of the bug in a codepen:
 
[https://codesandbox.io/s/focuscheckboxdetailslist-829hr](https://codesandbox.io/s/focuscheckboxdetailslist-829hr)

 #### Actual behavior:

When navigating through the list and a row is selected on focus, if the user wants to unselect  the currently focused row by clicking on the check-mark, he has to click once to remove the focus and click a second time to unselect the row.

Steps to reproduce :

1. Select first row
1. Press `down arrow` to go to the second row
1. Click once on the focused row's check-mark to remove the focus
1. Click a second time on the row's check-mark to unselect the item.

I noticed that it was due to the selected row having a style adding an empty string content through `:focus::after` and some  border styling to it. 

#### Expected behavior:
 
The user should be able to unselect with one click on the checkmark.

The sandbox contains an attempt at fixing the issue by setting this content to `none` and adding the border styling to the row.

#### Priorities and help requested:
 
Requested priority: (Blocking, High, Normal, **Low**), it is an uncommon scenario we encountered 
 
Thank you

**Comment by kenotron** [comment]
Thanks so much for the detailed codesandbox. I am always really appreciative of bugs with such details! This helps the team get to a fix so much faster 👍 Okay, I'm on it!

**Comment by kenotron** [comment]
@KevinTCoughlin - this actually seems like the default behavior for `Selection` for a list in general. Is the bug describing the correct behavior?

**Comment by rhublard** [comment]
Here's the actual behavior (I took time to find how to do a gif, my apologies), I don't know if it's expected for the user to have to click twice to unselect when the row is in focus when navigating using the keyboard.
![actualbehvior](https://user-images.githubusercontent.com/40246041/58279091-60d9db00-7d95-11e9-8bf8-c2cc3dac58d8.gif)

The second list has a quirky fix to allow to unselect with one click.

I hope it answers your question !

**Comment by kenotron** [comment]
I realize what the issue is, @rhublard - but to fix this, it might take more than a cursory fix... I'm thinking I should put this on the backlog since it's a bit low priority.

**Comment by rhublard** [comment]
It is fine, I wanted to know if it was a real issue or something I did wrong. Thank you for the fast answer !
