### ISSUE TITLE
Page scrolls when clicking button in Safari/Chrome on ios

### ISSUE THREAD

**Issue by ChristianOlsson** [OfficeDev/office-ui-fabric-react#9192]
### Please provide a reproduction of the bug in a codepen, if possible. Here’s how:
Test url - only reproes on ios:
https://y7f89.codesandbox.io/
To see the code:
https://codesandbox.io/s/flamboyant-dream-y7f89

### Environment Information 
 
- __Package version(s)__: 6.184.0
- __Browser and OS versions__: Safari/chrome - ios 12.2

### Please provide a reproduction of the bug in a codepen:
1. Using an iphone and chrome or Safari go to https://y7f89.codesandbox.io/
2. Scroll down to the bottom of the page
3. Click a button

#### Actual behavior:
The page scrolls to the top and the click is sometimes not registered
 
#### Expected behavior:
The page should not be scrolling when clicking a button and as a minimum the click should be registered. The expected funtionality can be achieved by replacing the office-ui-fabric buttons with the native html button.

#### Priorities and help requested:
Are you willing to submit a PR to fix? I would need help with why all the focus logic is needed on the component. I think a button component should be simple and not have all of the focus logic.
 
Requested priority: (Blocking, High, Normal, Low) High, since the button does not support fixed headers for ios
 
Products/sites affected: (if applicable)
All sites using office-ui-fabric buttons that has a fixed header - for users with iphones

**Comment by kenotron** [comment]
This is actually not Fabric's bug. This is an iOS behavior it appears. I have reduced your repro to use normal buttons - I've further REMOVED OUFR as a dep and it appears to behave the same as your repro.

https://qty43.codesandbox.io/
https://codesandbox.io/s/epic-field-qty43

Resolving this for now. Please close this bug at your earliest convenience.

**Comment by ChristianOlsson** [comment]
@kenotron you are very right, this is not a Fabric bug. It was easier to repro with Fabric buttons, but you are right, it did also repro with native buttons, even though I could not repro initially. Sorry for creating this issue.
