### ISSUE TITLE
Adding mouseover and mouseout events to Rating component

### ISSUE THREAD

**Issue by gladiatorAsh** [OfficeDev/office-ui-fabric-react#9199]
**Describe the feature that you would like added**
mouseover and mouseout events on Rating component
**What component or utility would this be added to**
Rating
**Have you discussed this feature with our team, and if so, who**
No
**Additional context/screenshots**
_

**Comment by marygans** [comment]
Hi @gladiatorAsh ! Do you mind providing additional context on what the expected behavior you would like for the events? If there are additional visual expectations in addition to what already exists in the component, it would need to go through design input/approval.  
Thanks!

**Comment by gladiatorAsh** [comment]
@marygans The expectation is that when I hover over the rating I can display corresponding text on what that rating denotes. From a UI perspective, no change is needed. It's just that these events are not exported.

**Comment by marygans** [comment]
Hi this is a good point, I was able to reproduce the [bug](https://codepen.io/gwiz0210/pen/wbboap). I will have a fix for this today. Thanks!
