### ISSUE TITLE
Site cards from SharePoint

### ISSUE THREAD

**Issue by simkessy** [OfficeDev/office-ui-fabric-react#9206]
Hey, I'm looking for this style of cards, is this available anywhere? 

![image](https://user-images.githubusercontent.com/5871660/58289987-f44ae600-7d6c-11e9-9a38-a2ebd6f4de21.png)

**Comment by kenotron** [comment]
It's not built-in to Fabric. But you can compose this with ```Stack```, or ```Card```. I would direct non-bug/feature questions to here with the [office-ui-fabric] tag: https://stackoverflow.com/questions/tagged/office-ui-fabric
