### ISSUE TITLE
Slider onChange should be triggered upon value changes even when the slider doesn't move.

### ISSUE THREAD

**Issue by andrew-buckley** [OfficeDev/office-ui-fabric-react#9211]
### Environment Information 
 
- __Package version(s)__: 6.84.1
- __Browser and OS versions__: Windows 10, Chrome Version 74.0.3729.169 (Official Build) (64-bit)

### Please provide a reproduction of the bug in a codepen:
 

 
https://codepen.io/anon/pen/YbazKd (Open console to see the slider onchange logs)

The above repro shows an example of the minimum of one slider being bound to the value of a different slider. When the value of the first slider changes it may change the value of the second slider if it's current value is below the new minimum.

#### Actual behavior:
 
The value on the left of Slider 2 is changing but the onSlider2Change callback is not getting fired and is only changed if the slider is used to change the value.
 
#### Expected behavior:
 
Whenever the value of the slider changes the onChange callback should fire even if the slider wasn't used to change the value.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: Normal (no workaround considered yet)
 
Products/sites affected:

**Comment by kenotron** [comment]
It's really a feature we hadn't coded up yet. Feel free to contribute here! I'm slammed with tons of bugs, so I'll place this in a backlog for feature requests.

**Comment by ecraig12345** [comment]
I'm not sure this is a behavior change we should make. In general, `onChange` should **not** be called when a component's `value` prop is updated by the consumer. (A few of our components currently call `onChange` in this case, but that's incorrect and should be fixed.) It's a little less clear-cut whether `onChange` should be called when the component's value is indirectly updated due to other prop changes, but I'd still lean towards saying it should not be called, and this is something that the consumer needs to monitor themselves.

**Comment by andrew-buckley** [comment]
Hm, that's interesting. What are the scenarios where `onChange` should be called? And if `onChange` shouldn't be called in this scenario, I'm wondering what is the recommended way to subscribe to component value changes if not through `onChange`? I think the only way the user would be able to monitor the `value` prop is in the scenario where they directly update the components `value` prop. I wonder if the case you described is the only case where `onChange` shouldn't be called because the user already has the value.

**Comment by dzearing** [comment]
`onChange` should be called when user interaction occurs only. It gives the parent an opportunity to decide if the change merits a state update (in a controlled component scenario.) Firing it in indirect cases where value is clamped might end up creating more bugs and unexpected circumstances.

The best way to code the example would be to control the limits manually in higher order state approach. Do your own clamping, provide the right value.
