### ISSUE TITLE
TeachingBubble directionalHint seems not work

### ISSUE THREAD

**Issue by chaofeng2014** [OfficeDev/office-ui-fabric-react#9213]
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:
 
Not sure what the default directionalHint is for TeachingBubble, but the pointer/beak is in different place every time when the Teachingbubble is rendered. 
It is in the mid at the first 2 times, then go to top. And after scroll, it repro again.
![teaching bubble directionalhint bug](https://user-images.githubusercontent.com/6550896/58295371-cae98480-7d83-11e9-8830-fb439487ceb7.gif)

#### Expected behavior:
 
At least, the pointer/beak should be in the same place when TeachingBubble is rendered every time.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by chaofeng2014** [comment]
Since the directionalHint not work as expected, so there is a bug in ODSP when render the teaching bubble: 
![teaching bubble jump](https://user-images.githubusercontent.com/6550896/58295472-4ea37100-7d84-11e9-8231-543815dd83c4.gif)
TeachingBubble recalculated and jump for a bit.

**Comment by kenotron** [comment]
@micahgodbolt, @joschect - I think this is related to timing. I don't think this is a quick fix for shield. Maybe you can regroup and try to come up with a solution here.

**Comment by micahgodbolt** [comment]
This issue has been addressed in the current version. 

![teaching](https://user-images.githubusercontent.com/1434956/71699360-ee41cc80-2d73-11ea-9bfd-2b325fd59983.gif)
