### ISSUE TITLE
Enable font-display:swap property for Segoe UI Fonts

### ISSUE THREAD

**Issue by adhithyar** [OfficeDev/office-ui-fabric-react#9214]
**Describe the feature that you would like added**
`font-display:swap` is a CSS property that can be used to instruct the browser to not block on rendering text or not render white text until the Segoe UI fonts are loaded. Instead, the browser will use a system font to render the text and then will swap it out for the correct Segoe UI font once the font is loaded. This is a progressive enhancement and the feature is supported in all browsers except IE 11. https://caniuse.com/#search=font-display. This has the potential to improve first contentful paint. 

**What component or utility would this be added to**
Fonts

**Have you discussed this feature with our team, and if so, who**
No

**Additional context/screenshots**

**Comment by kenotron** [comment]
Cool feature request. Putting this in the backlog to schedule it with any other perf work. If you feel up for it, feel free to contribute to this.

**Comment by kenotron** [comment]
Probably needs discussion as well as to where to place this... (inside Fabric component? Or auto injected the first time you use something that renders with Fabric?)

**Comment by unindented** [comment]
@kenotron where should we discuss this? We're seeing heavy Flash of Invisible Text when using Fabric in our app.
