### ISSUE TITLE
Keyboarding behavior for ChoiceGroup is different on Chrome and Edge

### ISSUE THREAD

**Issue by srinidhiprabhu96** [OfficeDev/office-ui-fabric-react#9215]
## Codepen demonstrating the issue
https://codepen.io/srinidhiprabhu96/pen/YbeoKd

Focus on one of the inputs. Hit the left key.

## Actual behavior:
On Edge, note that a cursor appears and the cursor moves from character to character.

## Expected behavior:
Focus shifts to one of the choices. Note that on Chrome the selection changes to the previous choice, which is acceptable.

**Comment by kenotron** [comment]
I can't repro this. Edge works fine for me here as well.
![norepro](https://user-images.githubusercontent.com/34725/58352605-ebb3e780-7e20-11e9-9197-fdc39716a02c.gif)

**Comment by srinidhiprabhu96** [comment]
Are you doing this on the new chromium based Edge?
This is what happens on my browser
![edge keyboarding](https://user-images.githubusercontent.com/16191789/58356673-fd9b8780-7e2c-11e9-8a36-8f87adb0d32a.gif)

**Comment by kenotron** [comment]
Then this is a bug with edge - please file this bug with them. We've got same working behavior for both current Edge and Chrome. Thanks!

**Comment by srinidhiprabhu96** [comment]
Thanks :)

**Comment by kenotron** [comment]
Marking as "Needs: Author Feedback" allows our bot to close this issue automatically. Or if you would like, please close it yourself.
