### ISSUE TITLE
Tag picker menu does not open when it already has focus

### ISSUE THREAD

**Issue by kopgenorth** [OfficeDev/office-ui-fabric-react#9222]
### Environment Information 
 
- __Package version(s)__: (6.181.0) 

### Please provide a reproduction of the bug in a codepen:
 
You can see the behavior on the documentation site:
https://fabricweb.z5.web.core.windows.net/oufr/6.72.0/#/examples/pickers
 
#### Actual behavior:
 
Selecting an item from the menu adds the selected item, then the focus moves to the input box.  This is fine if you want to type a new value, but if the user wants to make another selection from the menu, they have to click outside the input area and then click inside again.
 
#### Expected behavior:
 
Either clicking the input area opens the menu regardless if the input already has focus, or a prop exists to keep the menu open on selection.

#### Priorities and help requested:
 My additional request is that there's a prop to tell the picker whether to keep its menu open after a selection is made.  If the user wants to make many selections from a single search it's currently very tedious.

Are you willing to submit a PR to fix? (Yes, No) 
Maybe.
 
Requested priority: (Blocking, High, Normal, Low) 
 Normal

Products/sites affected: (if applicable)
 Workplace Analytics

**Comment by kenotron** [comment]
It's a bit of a change in behavior. Not likely something I can finish very quickly - so I'm putting this in a backlog to be reviewed.

**Comment by kenotron** [comment]
@joschect - I might be missing something really obvious here... maybe a prop override. If you have some cycles, please do comment with a solution!

**Comment by xugao** [comment]
@kopgenorth - apologize that we have not been able to prioritize your request. since it's been a while, could you confirm if you still need this fix?
