### ISSUE TITLE
Grid system not working in SPFx app

### ISSUE THREAD

**Issue by simkessy** [OfficeDev/office-ui-fabric-react#9228]
If I need to use something like the grid system do I use this or core?

**Comment by sitepodmatt** [comment]
You use Stack component.  The documentation and blog posts talking about import core css are out of date.  This had me confused too.

**Comment by dzearing** [comment]
`Stack` can work to solve most needs. See docs here:

https://developer.microsoft.com/en-us/fabric#/controls/web/stack

Having css grid support is something we'd like to have, but IE11 does not support some of the key features like templates and gap size. Some build time tech will help there, but we don't really have the luxury.

**Comment by simkessy** [comment]
Does that mean I shouldn't be using this classes: `ms-grid / ms-grid-row / ms-grid-col ms-{sm/md/lg)}` etc

**Comment by sitepodmatt** [comment]
Yes, you should not be using those class names from the underlying library, unless absolutely required, Stack (a flexbox abstract) should take care of that. Admittedly the documentation for fabric is an absolute disgrace and the limited amount of supporters their blog posts are worth sweet fall. We will probably go back to ant design

**Comment by simkessy** [comment]
> Look at grow attribute on stack.item to achieve what you propose, or fcuk it all off and go to proper a ui framework

I'll take a look but fuck this is ridiculous. I'd rather just load in Bootstrap add the classes and move on with my life.

**Comment by sitepodmatt** [comment]
If your just after grid then fabric react is overkill, however if you are using react components it's easier to embrace Stack and leave all the manual css behind

**Comment by dzearing** [comment]
You are certainly welcome to bring your own css. Or load bootstrap. Or use Fabric core. Lots of options.
