### ISSUE TITLE
Cannot find Nav module in 7.0.0-alpha023

### ISSUE THREAD

**Issue by dioklecijan** [OfficeDev/office-ui-fabric-react#9230]
### Environment Information 
 
- __Package version(s)__: 7.0.0-alpha023

There is no `Nav` component.
Statement  `import { Nav } from "office-ui-fabric-react/lib/Nav";` fails.

I can't file `Nav.ts` nor `Nav.js`  in `lib`, `lib-commonjs`and `lib-amd` directories.

**Comment by dioklecijan** [comment]
More info:

Version `7.0.0-alpha022` has the same issue. 
`7.0.0-alpha003` (installed as `office-ui-fabric-react@next) looks good.

**Comment by leddie24** [comment]
@jdhuntington, any ideas here?  I haven't been working a lot in Fabric 7 and am not sure why this has been removed for this version.

**Comment by jdhuntington** [comment]
Sorry for the trouble @dioklecijan - it has been moved to a separate package, but clear notes on how to grab the new one are not yet in the release notes.

The nav component now lives in `@uifabric/legacy`; to get it add `@uifabric/legacy` version  `7.0.0-alpha023` to your dependencies, then change any import statements to import have from there. (ie `import { Nav } from '@uifabric/legacy` )

**Comment by dioklecijan** [comment]
Thanks. It works. Closing issue.
