### ISSUE TITLE
Parcel build fails

### ISSUE THREAD

**Issue by jeremy-coleman** [OfficeDev/office-ui-fabric-react#9231]
purpose of this issue is just to show the existence of build problems in the simplest of scenarios

![image](https://user-images.githubusercontent.com/25135855/58444946-66526080-80c8-11e9-9417-edab58dd6f74.png)

these are the only imports of a single component 'app'  failing to build with parcel.
this 'app' isnt even using the components that are causing the error

it's likely caused by exporting mutliple variables with the same name using 'const' or possibly related to the personaPresence and PersonaPresence (enum) naming conflicts? More generally, stuff like this is caused from re-exporting things everywhere instead of just importing from the source

**Comment by kenotron** [comment]
Does this same thing occur if you were to compile it straight up with Typescript (tsc)?

**Comment by dzearing** [comment]
It would be awesome to get a parcel test in the `apps` folder, just to validate.

**Comment by jeremy-coleman** [comment]
Im not sure what youre looking for ken? Do you mean compiling that 1 file with tsc then running parcel? Or just tsc that file then use a static file server to serve that file + react and office react directly from node modules? Or i can tsc that 1 file and try to load with electron so i have require available on window

**Comment by kenotron** [comment]
I'm not familiar with Parcel and not sure how it differs with the official tsc compiler. I am pretty familiar with consumers being able to just npm install / yarn add OUFR and use it with webpack + ts-loader or even just to compile with it directly with tsc. What I'm looking for is compilation of 1 file + 1 tsconfig.json with OUFR in node_modules...

**Comment by jeremy-coleman** [comment]
https://github.com/jeremy-coleman/parcel-office-fail

**Comment by edoai** [comment]
@kenotron hi, any progress with this issue?

**Comment by kenotron** [comment]
I think this is external - Parcel doesn't support the "module" field so there's little we can do other than having to publish duplicates (oufr-esm and a oufr-commonjs) package which we likely wouldn't do.

**Comment by jeremy-coleman** [comment]
not the cause of this problem, but this file causes es builds to fail because the load themed styles package is published incorrectly. should just copy and paste it into the folder (and delete const enums) to fix the problem.
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/styling/src/styles/theme.ts
