### ISSUE TITLE
how can i use the sidebar component on https://portal.office.com/AdminPortal

### ISSUE THREAD

**Issue by siminture** [OfficeDev/office-ui-fabric-react#9232]
this sidebar is look very nice for admin portal website, how can i get it or how to custom the Nav component to same style?

[https://raw.githubusercontent.com/siminture/resources/master/office_admin.PNG](https://raw.githubusercontent.com/siminture/resources/master/office_admin.PNG)

**Comment by micahgodbolt** [comment]
The admin package has moved internal. The package has been updated with contact instruction.

https://www.npmjs.com/package/@uifabric/dashboard

**Comment by siminture** [comment]
get it, thanks.
