### ISSUE TITLE
DetailsListBase: In case of using this list with pagination, the spacer is getting added by default

### ISSUE THREAD

**Issue by v-khkuma** [OfficeDev/office-ui-fabric-react#9233]
### Environment Information 
 
- __Package version(s)__: 6.141.1
- __Browser and OS versions__: Chrome and Windows 10

 
#### Actual behavior:
Change the pagination page size (>100)-> click on F12 -> Observe the spaces
The Spacer is getting added in case we are changing page in pagination or decreasing the screen
 
#### Expected behavior:
 
There should be no spaces added by default.

#### Priorities and help requested:
  
Requested priority: High 
 
![DetailsList](https://user-images.githubusercontent.com/48505433/58459119-45c9eb00-8148-11e9-9d18-e8bea5fe445e.jpg)

**Comment by micahgodbolt** [comment]
Can you provide a repro of this issue in a codepen or describe how to observe the issue on our website?
