### ISSUE TITLE
Pivot component is not responsive on mobile view

### ISSUE THREAD

**Issue by SuganthanMathivanan** [OfficeDev/office-ui-fabric-react#9235]

**Comment by SuganthanMathivanan** [comment]
some buttons getting hide when you see in a mobile view. Need to use horizontal scrollbar.

**Comment by micahgodbolt** [comment]
duplicate of #4066

**Comment by micahgodbolt** [comment]
pivot wasn't created for this scenario. We have the feature in our backlog.
