### ISSUE TITLE
Combo Box : Not able to clear selected text using Back space.

### ISSUE THREAD

**Issue by Vaikesh** [OfficeDev/office-ui-fabric-react#9236]
**Environment Information**
- Package version(s): Latest master
- Browser and OS versions: Chrome

[_CodePen Sample_](https://codepen.io/vaikesh/pen/MdBJjW)

**Steps to reproduce:**

1.  Select an item from combo box options
2.  Click on the text view
3. Try clearing all the selected item using back space
4. Most of the time selected item can't be cleared from text view.
5. Select a item and try clicking the textview to select the item, click delete.

![Combox_Selection_Bug_request](https://user-images.githubusercontent.com/12531760/58466409-4158fe80-8157-11e9-834f-a80595d49a82.gif)

**Expected behavior:**
The selected text should be able to clear using backspace, or clear fully by clicking delete key.

**Priorities and help requested:**
Requested priority: Medium

**Comment by micahgodbolt** [comment]
Yeah, this behavior is REALLY inconsistent. I went back a few dozen releases and this still repros. @joschect is there anything we can do short term to address this? I know you are working on a large refactor of combobox and dropdown.

**Comment by joschect** [comment]
I'll take a look and see if there is a quick fix.

**Comment by micahgodbolt** [comment]
This is now working as expected.
