### ISSUE TITLE
PanelProps styles property returns an array of IStyleFunctionOrObject

### ISSUE THREAD

**Issue by SuperCiacho** [OfficeDev/office-ui-fabric-react#9237]
Environment Information
Package version(s): 6.186.1
Browser and OS versions: Chrome 70.0.3538.102, Windows 10 64-bit

### Please provide a reproduction of the bug in a codepen:
 
I have a custom panel header renderer and passing it as a onRenderHeader property of Panel.
Logic reuses Panel's styles (IPanelProps.styles). 
After update to 6.186.1, styling stopped working.
I found out it's because styles property provides an array of function objects/functions instead of single function/object.

![image](https://user-images.githubusercontent.com/5670702/58467071-4019d880-813b-11e9-91b6-819c474f96c6.png)

#### Actual behavior:
 
IPanelProps styles property returns returns **an array** of **IStyleFunctionOrObject<IPanelStyleProps, IPanelStyles>** objects

#### Expected behavior:
 
IPanelProps styles property returns **IStyleFunctionOrObject<IPanelStyleProps, IPanelStyles>**

#### Priorities and help requested:
 
Requested priority: High/Normal

**Comment by JasonGore** [comment]
Related PRs: #8761 and #9203

**Comment by JasonGore** [comment]
@SuperCiacho I'm exploring several different options for moving forward, some of which may be type changes. I'm curious what your use case is. More specifically, how did styling break? I'm curious how the styles prop was being used in the custom callback. Can you provide a code snippet or modify [this CodePen](https://codepen.io/jasongore/pen/dEjxbK)? Thanks!

**Comment by SuperCiacho** [comment]
@JasonGore 
Please find my CustomHeader on [this codepen](https://codepen.io/superciacho/pen/MdqEjG)

**Comment by andrehag** [comment]
I made [this codepen](https://codepen.io/anhag/pen/WBgRPq) that shows how the styled HOC changed the type of the styles-prop between release 6.184 and 6.185. I assume this is the same issue.

**Comment by JasonGore** [comment]
@SuperCiacho I tried your CodePen but it looks like it has a syntax error on line 120. Could you double check it? I wanted to make sure your use case gets covered as well. Thanks!

**Comment by SuperCiacho** [comment]
@JasonGore I'm sorry for that. Code is fixed.

**Comment by JasonGore** [comment]
Closing this issue as resolved. I created #9285 to track reintroduction of perf fixes in case anybody would like to subscribe to that issue.
