### ISSUE TITLE
Export smaller objects from AnimationStyles.ts

### ISSUE THREAD

**Issue by hjonasson** [OfficeDev/office-ui-fabric-react#9238]
We were using [AnimationStyles](https://github.com/OfficeDev/office-ui-fabric-react/blob/2ce6c5ac3ccf4e62d4866841317b4aa55b8fb541/packages/styling/src/styles/AnimationStyles.ts) to get `AnimationStyles.fadeIn100`. That comes with so much code that I don't feel good taking a dependency on `@uifabric/styling/...etc` and copied the code instead. This reduced my bundle size by 26kb.

Although it looks clean to just call `AnimationStyles.<necessary props>` this comes at a cost that shouldn't be ignored. I propose to export each variable individually when that can be done in a non-breaking way, such as by exporting both `AnimationStyles`, and each prop from it.

**Comment by micahgodbolt** [comment]
You should be able to use webpack to import only the individual data that you need. What are you currently using for tree shaking?
