### ISSUE TITLE
PeoplePicker BasePicker

### ISSUE THREAD

**Issue by Mukesh2085** [OfficeDev/office-ui-fabric-react#9239]
I am using Fabric React PeoplePicker in simple react-app (jsx) and populating with results from SharePoint people search. Same App works fine in SharePoint Online. While it throws exception on SP2016 On-Premise site when trying to search text is entered. I am using NormalPeoplePicker.

Error is coming at BasePicker.js line 561 (line 742 in Browser Virtual DOM JS file) where it is unable to find _this.currentPromise.

var promise_1 = (this.currentPromise = suggestionsPromiseLike);
            promise_1.then(function (newSuggestions) {
                
                if (promise_1 === _this.currentPromise) {
                    _this._updateAndResolveValue(updatedValue, newSuggestions);
                }
            });

While debuggin in SP Online value for _this.currentPromise is still undefined but somehow code works but not in SP2016. Is there any version incompatibility with SP OnPrem. Kindly suggest.

**Comment by micahgodbolt** [comment]
Do you know which version of Fabric is being used? This forum is for support on Fabric controls, not SPFX. If we can reproduce the bug in the version of Fabric you are using, we can look at a fix.

**Comment by Mukesh2085** [comment]
@micahgodbolt I am using react 5.8 i think and this is not with SPFX. I have used npm create-react-app module on top of which I am using office fabric UI libraries.
