### ISSUE TITLE
Disable pivot item

### ISSUE THREAD

**Issue by simkessy** [OfficeDev/office-ui-fabric-react#9247]
I want to disable a Pivot item. Is that possible?

**Comment by leddie24** [comment]
Hi @simkessy, after looking through the code, it doesn't seem like it's an available option.  We can add this to our backlog as a feature request if it's something that you would like to have.  @jdhuntington, as a Pivot code owner can you confirm/deny this?

**Comment by simkessy** [comment]
@leddie24 , I think it would be useful. Thanks.

**Comment by jdhuntington** [comment]
Thanks @simkessy - we will add this to our backlog.
In coming up with a plan, a few thoughts that come to find:
- What should happen if a `disabled` Pivot is also passed in as active pivot? Should it display an empty pane?
- How is a disabled pivot reflected visually?

We will likely will not be able to implement this feature in the immediate future, though would be happy to accept pull requests.

**Comment by j-te** [comment]
@simkessy it is currently possible; by using `headerButtonProps`, you can pass a prop. You'll have to manage the style though. 
[Codepen](https://codepen.io/anon/pen/WBaVjq)
```js
<PivotItem 
  headerText="Recent"
  headerButtonProps={{
    'disabled': true,
    'style': {color: 'grey'}
    }}
>
```

**Comment by simkessy** [comment]
@j-te ill try that out!

**Comment by leddie24** [comment]
@simkessy did @j-te's solution ended up working for you?

**Comment by tylerjwatson** [comment]
I'm also in need of this feature.  I believe the disabled state should only disable user interaction; if it's passed in as active, or programmatically changed it should obey such behavior and leave it up to the developer to handle those cases gracefully. 

I would also think that a grey disabled style should suffice, in the same vein as disabled buttons, but without modifying any backgrounds.

I'm happy to implement this if need be.

**Comment by gioce90** [comment]
> @simkessy it is currently possible; by using `headerButtonProps`, you can pass a prop. You'll have to manage the style though.
> [Codepen](https://codepen.io/anon/pen/WBaVjq)
> 
> ```js
> <PivotItem 
>   headerText="Recent"
>   headerButtonProps={{
>     'disabled': true,
>     'style': {color: 'grey'}
>     }}
> >
> ```

Hi.
I tried and 

> 'disabled': true,

works, but the style don't.

**Comment by j-te** [comment]
> Hi.
> I tried and
> 
> > 'disabled': true,
> 
> works, but the style don't.

@gioce90 Seems to be working on ver 7.25.0. Happy to help if you can show us your code.
