### ISSUE TITLE
DetailsList: Sticky/fixed header

### ISSUE THREAD

**Issue by sharpoverride** [OfficeDev/office-ui-fabric-react#925]
It should be possible to have the header fixed. I explored the documentation and I'm unable to find a property to handle this.

At the moment I need to go through a lot of ugly hacks to get to the header component.

```
const detailsList = refs.detailsList as any;
const header = detailsList._composedComponentInstance.refs.header.refs.root;
```

**Comment by dzearing** [comment]
yeah that's not great. :) We've wanted a sticky header feature for a while so this is a great feature ask.

**Comment by mikewheaton** [comment]
Closing as a duplicate of #1146.
