### ISSUE TITLE
Bind SP List data to the Default Button(Split Button)

### ISSUE THREAD

**Issue by srinivasravila** [OfficeDev/office-ui-fabric-react#9258]
I am working on the SPFx React and now am using Office UI Fabric React components like button drop down. Right now we are facing issue with binding SP list data to the Split Button.

I have Split Button
```
 <DefaultButton
                    data-automation-id="menuButton"
                    iconProps = {{iconName:"Contact"}}   
                    split={true}
                    onRenderMenuIcon= {this.userRoles.bind(this)}                    
                    text = {this.state.activeRoles[0]}
                    aria-roledescription={'split button'}
                    style={{ height: '35px' }}
                    menuProps={{
                                 items: [     {key:this.state.activeRoles[0], text:this.state.activeRoles[0]},
                                                  {key:this.state.activeRoles[1], text:this.state.activeRoles[1]}
                                           ]
                                         }}
                />
```

I have to bind dynamic data to the `menuProps` and as well to the `text`. and on selection change i have to change the text part dynamically.

Please provide me the guidance on this

**Comment by leddie24** [comment]
Hey @srinivasravila, thanks for submitting this issue.  It's a bit hard to reproduce and debug this issue without knowing how your code works.  Can you try creating a CodePen to repro this error? That way we can isolate the issue to Fabric React, rather than something in your code.

Here's a starter template:
https://codepen.io/pen?template=NvBvWx

Changing the text of a button based off component states seems to have no errors for me:
https://codepen.io/leddie24/pen/zQJQZm

**Comment by srinivasravila** [comment]
Hi Team,

Thanks for quick response. 
I have resolved it. bind data to the split button and onclick of the menu options also text will change

For Reference
public options:any[]=[];
    public categories; 
    public async componentDidMount(): Promise<void> {
        this.categories = await SpService.GetuserRoles();    
        this.categories.forEach(c => {           
            this.options.push({key:c.Title,text:c.Title,onClick:this.handleClick.bind(this,c.Title)});
        })
      } 
	private handleClick(Title) {
        this.setState({displayText:Title})
      }
