### ISSUE TITLE
Breadcrumb: Navigation and keypress event handling.

### ISSUE THREAD

**Issue by Hardhik** [OfficeDev/office-ui-fabric-react#927]
- __Package version(s)__: Current one 
- __Browser and OS versions__: Chrome Win10

When the focus is on one of the breadcrumb's elements and we press alt+right OR alt+left the default behavior should be that of the browser ( navigate forward OR backward in history).
This is not honored currently. 

I guess the problem is in the keypress event handler where we stop the propagation of keypress events. We might want to allow for propagation in scenarios where modifier keys(alt, shift, ctrl) are present.

#### Expected behavior:

The browser's behavior should be honored.

Can be seen here too:
http://dev.office.com/fabric#/components/breadcrumb#Variants

**Comment by dzearing** [comment]
Good catch, easy fix. Assigning to @leddie24

**Comment by gitjain** [comment]
Issue is been fixed. updating the status.
