### ISSUE TITLE
Sidebar colors property has no effect

### ISSUE THREAD

**Issue by lidermanrony** [OfficeDev/office-ui-fabric-react#9278]
### Environment Information 
 
- __Package version(s)__: "@uifabric/experiments": "6.76.2",
- __Browser and OS versions__: N/A

### Please provide a reproduction of the bug in a codepen:
 

 I don't know how to create a codepen for experimental components, but the core issue is the following line:
    this._colors = this.props.colors ? this.props.colors : SidebarColors.Light;	
zero is a valid value  of the colors enum (which stands for dark), but in the case it's 0 the condition will always evaluate to false.
The fix is as simple as checking equality with undefined.
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? **Yes**
Requested priority: (Blocking, High, Normal, **Low**) 
 
Products/sites affected: (if applicable)

**Comment by leddie24** [comment]
Hi @lidermanrony, good catch! Thanks for filing a PR for this, we'll get it merged in soon.
