### ISSUE TITLE
DatePicker errormessage not shown

### ISSUE THREAD

**Issue by imran6029** [OfficeDev/office-ui-fabric-react#9282]
### Environment Information 
 
- __Package version(s)__: 6.184.0
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:
 
The date is set as invalid by the React state(01/01/2019) and the minDate is set as (01/01/2020).The error message is not shown on the screen. The error message get displayed only when the DatePicker field is changed by keyboard to some invalid date.Although the datepicker value is invalid the error message is not shown.:Look at the codepen link below for reproduction of the bug.
  
#### Expected behavior:
 
The error message should be displayed validating the date is set by "value" attribute of DatePicker field.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No
 
Requested priority: (Blocking, High, Normal, Low) High
 
Products/sites affected: (if applicable) 

codepen: https://codepen.io/imran6029/pen/eaPMgo

**Comment by leddie24** [comment]
Hi @imran6029, thanks for submitting this issue! I can indeed repro this; I will have a fix ready sometime this or next week to solve this.
