### ISSUE TITLE
DatePicker errorMessage not shown while submitting the form

### ISSUE THREAD

**Issue by imran6029** [OfficeDev/office-ui-fabric-react#9283]
### Environment Information 
 
- __Package version(s)__: 6.184.0
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:
 
When the Datepicker field is set a default value(01/01/2019) by the "value" attribute and mindate as(01/01/2020).When I try to submit the form with this datepicker field.It is not able to submit the form and the error message is also not conveyed to the user.The user is blocked and cant proceed further.

#### Expected behavior:
 
The user should be prompted with the error message.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)No
 
Requested priority: (Blocking, High, Normal, Low) High
 
Products/sites affected: (if applicable)

codepen: https://codepen.io/imran6029/pen/eaPMgo

**Comment by leddie24** [comment]
Closed via #9290
