### ISSUE TITLE
Example web site is annoying in that too many links navigate away from the page

### ISSUE THREAD

**Issue by amirburbea** [OfficeDev/office-ui-fabric-react#9284]
How hard is it to make all the buttons simply pop up alerts or something.  It's very hard to play with the examples site when everything I click wants to navigate to msn.com or something like that.

Also, a lot of the examples are rendered in a bad code editor that makes it look like half the code is commented out.  You guys should reuse the monaco js editor in a readonly mode or something to prevent that.

**Comment by dpierangeli** [comment]
Yes, the example site 'navigation away' is not the best experience,

**Comment by leddie24** [comment]
Hi @amirburbea, thanks for filing this issue.  I can help file a PR to remove the navigation links and replace them with console logs or alerts.  Your second suggestion would require more work; do you mind filing another bug re: code editor so we can track these issues separately please? Thanks!

**Comment by KevinTCoughlin** [comment]
> I can help file a PR to remove the navigation links and replace them with console logs or alerts.

@leddie24 I think specifically the Nav examples are guilty here. Perhaps navigation is still useful, but we open those links to a new tab.

**Comment by amirburbea** [comment]
That would be a good starting point. Sorry about the manner in which this
ticket was started I was just frustrated because everything I touched made
me lose my place and have to rescroll. Pop-up windows or a toast are better

(Speaking of which what is the recommended manner in which my app should
display a toast. Ie which components put together would do that best)

**Comment by leddie24** [comment]
@amirburbea , to help save me some time, do you remember what components were providing navigation redirection besides Nav?  

Re: toast notification.  I don't know if we have an out of the box solution with Toast notification.  The closest thing I can think of is using a Callout with a beak width of 0, and having it anchored to fixed position element where ever you want  the notification to exist. 

Here's a codepen for example:

https://codepen.io/leddie24/pen/PvXqJY?editors=1111

**Comment by amirburbea** [comment]
Thanks for the sample.

A quick glance found links in the document card samples (all open to
bing.com when clicking the conversation cards), breadcrumbs, the upload
button in the command bar samples, all the navs (which already popped up an
alert - I think that's kind of sufficient), the example focus trap call out
Etc ...

I think just grep the code for bing.com. They seem to love linking to that

**Comment by amirburbea** [comment]
> Hi @amirburbea, thanks for filing this issue. I can help file a PR to remove the navigation links and replace them with console logs or alerts. Your second suggestion would require more work; do you mind filing another bug re: code editor so we can track these issues separately please? Thanks!

I'll open a second bug now.  Thanks

**Comment by leddie24** [comment]
Hey @amirburbea , I just made a PR to address this issue.  One thing I couldn't fix in this PR is `DocumentCard` examples.  It looks like that component is handling links with its own prop rather than using the native html `target` prop.  I can file a PR later to allow `DocumentCard` to open links in a new window.

**Comment by amirburbea** [comment]
That's great. I guess we'd need a prop for document card to set target
(like window.open) so by default it won't break backward compatibility

**Comment by amirburbea** [comment]
When will the examples site be updated?

Just clicked on a document card example (view and share files) and it
navigated the entire page to Bing.com
