### ISSUE TITLE
Initial column width in DetailsList

### ISSUE THREAD

**Issue by dioklecijan** [OfficeDev/office-ui-fabric-react#9287]
### Environment Information 
 
- __Package version(s)__: 6.187.1 
- __Browser and OS versions__:  Edge 76.0.174.0 (Official build) Canary (64-bit),  Chrome 74.0.3729.169 (Official Build) (64-bit), macOS 10.14.4 
 
#### Actual behavior:

I can't find the way to set initial column width for DetailsList.
 
```
const cols: IColumn[] = [
  {
    key: 'someColumn',
    name: 'Some column',
    fieldName: 'someColumn',
    isResizable: true,
    minWidth: 100,
    maxWidth: 500,
//  playing with these settings:
    // className: mergeStyles({ width: '250px' }), // no effect
    // className: mergeStyles({ width: '250px !important' }), // cells respect, but header doesn't 
    // currentWidth: 250, // no effect
  },
```
I tried with both DetailsList layout modes (`DetailsListLayoutMode` prop.)
 
#### Expected behavior:
 
Ideally `initialColumnWidth` (or `defaultColumnWidth`) should be defined in `IColumn`.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No, just started with fabric)
 
Requested priority: (Normal) 
 
Thank you.

**Comment by leddie24** [comment]
Hi @dioklecijan, thanks for submitting this issue!  I'll look into this for you; I can't find a way to do so, I can submit a PR to add in this feature for you soon.

@KevinTCoughlin @natalieethell @aditima, do you guys know off hand if this is possible?

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin @natalieethell @aditima, do you guys know off hand if this is possible?

Currently, the only way I know how to support this is by setting the `IColumn` values for `minWidth` and `maxWidth` to the same value.

Here's an example: https://codepen.io/kevintcoughlin/pen/gJZMYP

Cell padding can be adjusted via:

https://github.com/OfficeDev/office-ui-fabric-react/blob/4ac2f2bacea133918bc0b3d2e781131b768147f1/packages/office-ui-fabric-react/src/components/DetailsList/DetailsRow.types.ts#L60

Definitely an unintuitive API that needs to be improved for this exact scenario.

Does the above unblock you in the short-term @dioklecijan?

**Comment by dioklecijan** [comment]
Thank you @KevinTCoughlin , but it covers only case when `minWidth` is equal to `initialWidth`. If you set `isResizable: true` you can expand column width over `maxWidth`, but you can't reduce it below `minWidth`.  

The real-life problem is to let the user resize column and reuse that width on the next load. I think it should be supported width `minWidth`, `maxWidth` and `initialWidth`.

Thanks.

**Comment by KevinTCoughlin** [comment]
> The real-life problem is to let the user resize column and reuse that width on the next load.

I agree it is odd and the existing props are misleading. I'm unsure of the timeline for when we'll add this feature and wrangle the existing props API.

I'm going to add to the backlog for now. Will happily guide a code contribution and review pull-requests.

@Vitalius1

**Comment by Katli95** [comment]
Yeah, this feature would be amazing. I was pretty surprised when I saw that it wasn't there already :/ Kind of a requirement for controlling the width's of the columns manually. Still, kudos for the great work!
