### ISSUE TITLE
Update project install steps to include rush install

### ISSUE THREAD

**Issue by aleksandrjPersonal** [OfficeDev/office-ui-fabric-react#929]
### Bug Report

- __Package version(s)__: (fill this out)
- __Browser and OS versions__: (fill this out if relevant)

**Comment by dzearing** [comment]
Hmm. @aleksandrjPersonal this should be done by npm install at the root.

```json
  "scripts": {
    "postinstall": "rush install && rush link",

```

**Comment by mikewheaton** [comment]
@aleksandrjPersonal, I forget the exact issues that we saw with your install. Could you try cloning down a fresh copy of the repo and following the install directions? I thought it was just that our documentation was out of date, but I guess not.

**Comment by dzearing** [comment]
Please re-open if you hit any issues!
