### ISSUE TITLE
IconProps for Buttons don't render placeholders when empty names are passed

### ISSUE THREAD

**Issue by andrewhwng** [OfficeDev/office-ui-fabric-react#9292]
### Environment Information 
 
- __Package version(s)__: 6.182.0

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/anon/pen/byQeBY
 
#### Actual behavior:
 
When passing in empty strings as the iconName for iconProps in Buttons, the placeholder does not get rendered. Passing in a random string that does not match an icon name renders the placeholder however.
 
#### Expected behavior:
 
Passing in empty strings as iconNames should render the placeholder icons.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes
 
Requested priority: Low
 
Products/sites affected: OWA Calendar

**Comment by micahgodbolt** [comment]
Yeah, good catch. The way we set up icons is that an empty string will render a placeholder:

https://github.com/OfficeDev/office-ui-fabric-react/blob/61ffe7ba8a1f40a61a8335ac9ef9fb6e4dc30fd7/packages/office-ui-fabric-react/src/components/Icon/Icon.types.ts#L36

But the button only renders the icon if the icon passes the following test

https://github.com/OfficeDev/office-ui-fabric-react/blob/a2dd64cfd3a5540ced0dae0799d282fe574b90e6/packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx#L316

which will come back negative for an empty string.

My only caution here is that this change might have unintended side effects for anyone passing in an empty string expecting nothing to show up. We'll need to provide some communication around this change when it occurs. Make sure to ping me when this is fixed.
