### ISSUE TITLE
Dropdown: Fluent Updates

### ISSUE THREAD

**Issue by marygans** [OfficeDev/office-ui-fabric-react#9305]
- [x] Update component current hover state (gray110) to reflect toolkit (cyanBlue10) -> double check with Ben

- [x] Update component current focus state(gray160) to reflect toolkit (black) -> double check with Ben

**Comment by marygans** [comment]
@betrue-final-final the current Sketch toolkit has the rest border color of gray90 and was updated to gray110 by Aniket in this fairly recent [accessibility issue](https://github.com/OfficeDev/office-ui-fabric-react/issues/8910), and eventually needs to be updated in the toolkit.

**Comment by betrue-final-final** [comment]
Yes, you are correct about the rest state. I have a toolkit branch created to deal with visibility of focus. This means I am looking at Focus to be themePrimary and 2px.

**Comment by betrue-final-final** [comment]
![image](https://user-images.githubusercontent.com/20363037/58739993-7d43cc00-83c2-11e9-8173-579dee35447a.png)
