### ISSUE TITLE
Ability to disable the out-of-the-box browser's autocomplete for the SearchBox

### ISSUE THREAD

**Issue by spplante** [OfficeDev/office-ui-fabric-react#9311]
**Describe the feature that you would like added**

Ability to disable the out-of-the-box browser's autocomplete feature

**What component or utility would this be added to**

The SearchBox component

**Have you discussed this feature with our team, and if so, who**

No

**Additional context/screenshots**

I am building an "AutoCompleteSearchBox" component which uses the SearchBox and renders suggestions below the SearchBox, everything works fine except the fact that I also get the Chrome's autocomplete in the way...

I tried setting autocomplete="off" on the SearchBox component but it gets ignored.

**Comment by dpierangeli** [comment]
Welcome in the world of Chrome Autocomplete hell!

That is a Chrome problem, there are a couple of workarounds (until Google Engineers decide to visit the real world) :
- try to use a custom 'autocomplete' value
- set the autocomplete='off' with a timer

Check 
https://stackoverflow.com/questions/15738259/disabling-chrome-autofill

and don't forget to comment here:
https://bugs.chromium.org/p/chromium/issues/detail?id=587466

**Comment by spplante** [comment]
@dpierangeli, I tried most of these workarounds with no success, because no matter what I try to put in the « autocomplete » property of the SearchBox component, the component does not use this property internally when rendering it’s input field...

So before trying some stuff with the autocomplete, the SearchBox actually has to expose and use the property. Right when inspecting the control with the debugger, it is ignored completely by the component.

I ended up replacing the SesrchBox by a Texfield, which specifically exposes the « autocomplete » property and applies it correctly to it’s underlying input element, and everything works perfectly.

**Comment by aneeshack4** [comment]
@spplante We currently don't have any plans for the SearchBox component (regarding implementing using a new property internally) and this seems to be mostly a Chrome problem so I'll close this.

**Comment by spplante** [comment]
@aneeshack4 well it’s not a Chrome issue it’s just a matter of exposing the property and setting it to the underlaying input, juste like the TexField does (and it works), but ok if the SearchBox isn’t going to evolve anyway I will stick with my tweaked TextBox
