### ISSUE TITLE
Teaching bubble should read "Alert dialog" when teaching bubble is popped up.

### ISSUE THREAD

**Issue by KeiraYang** [OfficeDev/office-ui-fabric-react#9312]
## Actual behavior:
When teaching bubble is opened, only the content on the teaching bubble is read out. Users may don't know what it is.
## Expected behavior:
Teaching bubbles don’t announce what they are. (Should say “alert dialog”.)

**Comment by aneeshack4** [comment]
@KeiraYang Is this on Narrator? What browser does this repro on? Please provide more details.

**Comment by KeiraYang** [comment]
Hi @aneeshack4 , I test the accessibility by Edge + Narrator.

**Comment by micahgodbolt** [comment]
@KeiraYang can you give us an example of how this should work? We typically avoid putting any strings into a component. Is there an aria/narrator specific way to have the alert spoken?

**Comment by aneeshack4** [comment]
@KeiraYang If you look at the reference example in the alert dialog's role documentation, the text inside any element marked with role="alertdialog" gets read as soon as it gets focus, with no announcement: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alertdialog_role#Examples. Here's a codepen to illustrate this that @micahgodbolt made from the above docs' example code: https://codepen.io/micahgodbolt/pen/JqqEvL

**Comment by KeiraYang** [comment]
Yes. You're right. But I cannot add the role to the teaching bubble component when consuming it. Can this be fixed inside the component?

**Comment by micahgodbolt** [comment]
@KeiraYang is there some aria spec that describes how this behavior works? I.E. is there a role we need to add for narrator to say those words, or do we need to provide that string to the component?

We don't provide any strings with our controls, they need to be provided by the user for the given language. So if it's up to the component to speak that string, you'll need to provide it yourself.

**Comment by aneeshack4** [comment]
@KeiraYang here's a Codepen that @micahgodbolt made: https://codepen.io/micahgodbolt/pen/QXbNwe?editors=1010 you can see that he's able to pass in role="alertdialog" and if you inspect, you can see it gets applied. When I run Narrator on it, it doesn't announce it as "Alert Dialog" because the ARIA spec doesn't dictate that... this is the best we can do with what the ARIA spec allows us. If you want a custom string read, you'll have to pass that in. 
![image](https://user-images.githubusercontent.com/4161791/59375799-c4f01f00-8d03-11e9-9e50-c46799925114.png)

**Comment by KeiraYang** [comment]
Hi @aneeshack4 , with the role passed, it doesn't read the role still. I think something should be fixed. As I tested the alert dialog as W3C given, https://w3c.github.io/aria-practices/examples/dialog-modal/alertdialog.html. It will read the alert dialog. We just wants to get the alert dialog rule to be read when dialog is opened but without customize the string. I also tested the callout component in https://developer.microsoft.com/en-us/fabric#/controls/web/callout with alertdialog role. But still no alert dialog assert when callout is shown up.

**Comment by micahgodbolt** [comment]
In that dialog example, upon clicking "discard" narrator simply reads the "Confirmation" string because the alertdialog is labelledby that H2 tag

```html
<div id="alert_dialog" role="alertdialog" aria-modal="true" aria-labelledby="dialog_label" aria-describedby="dialog_desc" class="default_dialog">
  <h2 id="dialog_label" class="dialog_label">Confirmation</h2>
</div>
```

These are all values provided by the user, its nothing we bake into the control.

**Comment by KeiraYang** [comment]
I get your idea. But I cannot add the id reference to teaching bubble title and content. Thus I'm trying to add "Alert dialog" to ariaLabel in calloutProps which could work. Thank you for help!

**Comment by micahgodbolt** [comment]
If all we need is titleProps that's an easy fix. I think it might be worth while to look into making that association automatic, but adding those props is an easy fix we can do today. @Ben Truelove<mailto:betrue@microsoft.com> what do you feel about teaching bubbles always using
role="alertdialog" and the title being the described by? Is that a good default? Or too noisy and should be set up on a case by case basis?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
