### ISSUE TITLE
[Coachmark] If color prop is not specified it will default to DefaultPalette instead of the current theme

### ISSUE THREAD

**Issue by riosn-n** [OfficeDev/office-ui-fabric-react#9313]
### Environment Information 
 
- __Package version(s)__: 6.187.2
- __Browser and OS versions__: All

If the "color" prop is not specified it will default to DefaultPalette.palette.themePrimary instead of palette.themePrimary of the current theme.

#### Actual behavior:
 
Uses the themePrimary color of the DefaultPalette
 
#### Expected behavior:
 
Uses the themePrimary color of the current theme

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Low
 
Products/sites affected: PowerApps

**Comment by aneeshack4** [comment]
It actually looks like it's getting the current theme: it's being set to `theme.palette.themePrimary`: https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/Coachmark/Coachmark.styles.ts#L147. 

Where do you see that it's getting the DefaultPalette's themePrimary?

**Comment by riosn-n** [comment]
That code is for the pulsating animation. For the actual coachmark, it uses the DefaultPalette as per the code below:

[https://github.com/OfficeDev/office-ui-fabric-react/blob/382ec4fe6678eef91be9bc7e66091b11ff92e0a2/packages/office-ui-fabric-react/src/components/Coachmark/Coachmark.base.tsx#L119](https://github.com/OfficeDev/office-ui-fabric-react/blob/382ec4fe6678eef91be9bc7e66091b11ff92e0a2/packages/office-ui-fabric-react/src/components/Coachmark/Coachmark.base.tsx#L119)

**Comment by aneeshack4** [comment]
Ah I see we shouldn't be pulling from defaultPalette. We should actually be pulling from semanticSlots so I'll go ahead and fix this. Thanks for reporting this!
