### ISSUE TITLE
Teaching Bubble Overflowing and Swapping Sides

### ISSUE THREAD

**Issue by JuhiB** [OfficeDev/office-ui-fabric-react#9316]
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:
 
The bubble loads to the left of a folder in the rightmost column (and overflows off the page) before correcting itself and jumping to the right of the folder. This is the overflow screenshot:
![TeachingBubbleError](https://user-images.githubusercontent.com/18145534/58818414-be1a2b80-85e2-11e9-95f1-ed8c2dbb4daa.png)

 
#### Expected behavior:
 
The bubble should render without overflowing.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by aneeshack4** [comment]
@JuhiB could you provide a repro of this on codepen? It's hard to repro this exact same overflow and the example page doesn't have a similar scenario https://developer.microsoft.com/en-us/fabric/#/controls/web/teachingbubble
