### ISSUE TITLE
ContextMenu: shouldFocusOnMount doesn't have any effect

### ISSUE THREAD

**Issue by cschleiden** [OfficeDev/office-ui-fabric-react#932]
### Bug Report

- __Package version(s)__: master
- __Browser and OS versions__: *

#### Describe the issue:

If I'm not mistaken, `shouldFocusOnMount` doesn't have any effect on the context menu.

**Comment by mdahamiwal** [comment]
Have you tried with latest bits? 
![contextmenu](https://cloud.githubusercontent.com/assets/12109362/22548168/36583036-e96b-11e6-8686-73da435206ca.gif)

**Comment by cschleiden** [comment]
@mdahamiwal I looked at the code, I can't find any usage of the prop in ContextMenu

**Comment by dzearing** [comment]
@joschect ?

**Comment by joschect** [comment]
@dzearing This is a bug, it's an easy fix. It should get passed through to Callout via "setInitialFocus". I'll have a pr shortly.

**Comment by dzearing** [comment]
Merged :)
