### ISSUE TITLE
DetailsList header title is reading a hidden element after the highlighted title

### ISSUE THREAD

**Issue by sashokk2** [OfficeDev/office-ui-fabric-react#9322]
## Codepen demonstrating the issue
https://codepen.io/anon/pen/OYgOJZ?&editable=true

## Actual behavior:
Virtual cursor focus on, moves to the hidden elements and reads them after the column header. For instance the Name header when press down key (virtual cursor mode on) reads the hidden element after the header.
## Expected behavior:
Virtual cursor focus on, in DetailsList should only read the header title when that is highlighted.

**Comment by aneeshack4** [comment]
@sashokk2 Which screenreader are you using and on which browser?
