### ISSUE TITLE
Installation fails behind firewall with content blocking

### ISSUE THREAD

**Issue by sympmarc** [OfficeDev/office-ui-fabric-react#9335]
### Bug Report

- __Package version(s)__: 1.15 -> 1.21
- __Browser and OS versions__: Chrome on Windows

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No)

Requested priority: (Normal) 

Products/sites affected: Office365 CLI

#### Describe the issue:

When installing the Office 365 CLI from behind a firewall, in some cases, download of the tgz file is blocked.

#### Actual behavior:

When installing, this is the output:
```
npm i -g @pnp/office365-cli
npm ERR! code E403
npm ERR! 403 Forbidden: @pnp/office365-cli@latest

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\anderma\AppData\Roaming\npm-cache\_logs\2019-06-04T14_55_25_392Z-debug.log
```
#### Expected behavior:

I know this is solvable by downloading the tgz file manually and installing, but it would be great if there were a more clear error an also instructions on the [Getting Started](https://pnp.github.io/office365-cli/) page for this situation.

**Comment by kenotron** [comment]
I think this issue should be filed here instead: https://github.com/pnp/office365-cli

Also, this sounds like a problem with your firewall configuration that you probably need your sys admin's permission to solve... probably not a problem from the side of the package maintainers (or even npmjs.org for that matter).

**Comment by sympmarc** [comment]
Sorry - wrong repo!
