### ISSUE TITLE
PR #9295 caused regression in menu icon disabled state for Buttons

### ISSUE THREAD

**Issue by makopch-ms** [OfficeDev/office-ui-fabric-react#9344]
PR: https://github.com/OfficeDev/office-ui-fabric-react/pull/9295
### Environment Information 
 
- __Package version(s)__: 6.188.0
- __Browser and OS versions__:  all

#### Actual behavior:
 
For FlyoutAnchor's the menu icon doesn't look disabled when the Button control is disabled
 
#### Expected behavior:
 
The menu icon matches the rest of the button control and has disabled styles

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes/No - The PR just need to be reverted.
 
Requested priority: (Blocking, High, Normal, Low) : Blocking
 
Products/sites affected: Office Online

**Comment by makopch-ms** [comment]
@GitHubMaxwell

**Comment by GitHubMaxwell** [comment]
@makopch-ms Thanks for opening this issue. I have opened #9350 reverting back to SplitButton's original state while investigating the proper fix.

**Comment by GitHubMaxwell** [comment]
@makopch-ms Hi Matt, just wanted let you know that the fix has been made and will show up in the next release. Thanks again for raising the issue!
