### ISSUE TITLE
CheckBox: selection is not visible in high contrast

### ISSUE THREAD

**Issue by ronak-92** [OfficeDev/office-ui-fabric-react#935]
### Bug Report

- __Package version(s)__: (0.87.0)
- __Browser and OS versions__: (Explorer and win10)

#### Describe the issue:

In high contrast - whether you select or unselect - you will only see the white circle with no difference.

#### Actual behavior:

![image](https://cloud.githubusercontent.com/assets/9554299/22540734/f7895718-e947-11e6-9894-999795362c39.png)

#### Expected behavior:

The check mark should be visible inside the circle to distinguish whether the row is selected or not.

### If applicable, please provide a codepen repro:
This behaviour is can be seen in official documentation of office-fabric as well.
>https://dev.office.com/fabric#/components/detailslist

**Comment by dzearing** [comment]
@mikewheaton want to assign?

**Comment by mikewheaton** [comment]
There is a pull request in Fabric Core that should resolve this issue once it's released and used by Fabric React: https://github.com/OfficeDev/office-ui-fabric-core/pull/913

I've assigned this issue to myself to track.

**Comment by micahgodbolt** [comment]
seems to be working now 
![image](https://cloud.githubusercontent.com/assets/1434956/23816311/fb41bd6c-05a0-11e7-9fc6-80565015d7d5.png)

**Comment by ronak-92** [comment]
@mikewheaton @micahgodbolt 
I tried checking with on all Hight contrast-1, 2, black, white themes, but on selection the background colour of row is not changing. I tried it on Internet explorer, edge and firefox.
