### ISSUE TITLE
For multiselect dropdown do we have readonly feature implemented?

### ISSUE THREAD

**Issue by dhanMS** [OfficeDev/office-ui-fabric-react#9358]
For multiselect dropdown disabled does not shows the all selected keys, can we have readonly props added which displays the dropdown with all the options and selected keys in readonly mode

**Comment by aneeshack4** [comment]
@dhanMS can you please provide a codepen with a repro? And on what browser? Are you talking about the controlled or the uncontrolled states? Both of these examples on the Fabric site show all the selected keys so based off the info you've given so far, this doesn't repro. https://developer.microsoft.com/en-us/fabric/#/controls/web/dropdown
