### ISSUE TITLE
Unable to specify textAnchor property in IRawStyle object

### ISSUE THREAD

**Issue by cikuITreti** [OfficeDev/office-ui-fabric-react#9361]
### Environment Information 
 
- __Package version(s)__: 6.189.0
- __Browser and OS versions__: not relevant
- __Typescript__: 3.5.1
#### Actual behavior:

When using TS 3.5.1 specifying an unknown property, like textAnchor, in the IRawStyle interface, throws an error:

![image](https://user-images.githubusercontent.com/1935814/59024238-5512fd80-8806-11e9-87e6-5fb7fd511f28.png)

#### Expected behavior:
I would like to be able to specify the textAnchor style property as part of a IRawStyle object as following:
```
const style: IRawStyle = {
    strokeWidth: 2,
    fill: axis.tickText,
    fontWeight: 600,
    textAnchor: "middle"
};
```
It's a bit weird other SVG style properties as fill or strokeWidth are declared as part of the IRawStyle interface while textAnchor is missing.
 
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) Yes
 
Requested priority: (Blocking, High, Normal, Low)  Low

**Comment by aneeshack4** [comment]
@cikuITreti It looks like this property isn't implemented on any browser yet so it doesn't seem worth it add it IRawStye right now - why do you need this property/where is it working?
![image](https://user-images.githubusercontent.com/4161791/59621986-47525780-90e5-11e9-97d1-3bd940e42257.png)
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/text-anchor#Browser_Compatibility
