### ISSUE TITLE
Teams ui rewrite

### ISSUE THREAD

**Issue by jeremy-coleman** [OfficeDev/office-ui-fabric-react#9364]
I rewrote the teams ui component lib a while ago, removing prop types, updating to hooks and react context provider, proper spelling of palette(lol). I could port it over to use merge styles instead of typestyle if it would be useful to integrate parts of it in the office ui libs

**Comment by aneeshack4** [comment]
@jeremy-coleman What is your question with regards to Fabric here? It'd be helpful if you could please fill out our issue template - that's what makes issues actionable for us.

**Comment by jeremy-coleman** [comment]
do you want a copy of the teams ui converted to merge styles?

**Comment by khmakoto** [comment]
@JasonGore @dzearing adding you as I think you are the ones with most knowledge and most involved in this conversation.

**Comment by aneeshack4** [comment]
Also, @jeremy-coleman which Teams UI are you talking about exactly?

**Comment by dzearing** [comment]
@jeremy-coleman link your git repo, not enough context.

pss ... Also, add me on linkedin if possible so you can send me chat messages!
