### ISSUE TITLE
Open callout by clicking in the People Picker

### ISSUE THREAD

**Issue by JoshuaLamusga** [OfficeDev/office-ui-fabric-react#9373]
**Discussion**
Consider this scenario:

1. The user goes to a people picker component. The suggestions box comes up.
2. The user select a user. The user is added and the suggestions close.
3. The user doesn't remember what to type next, so the user wants the suggestions box to pop up again.
4. The user tries to get it to pop up by clicking again. Nothing happens.

The consensus in my team is that no. 4 is a common enough scenario that this should be supported. I'd like to have a small design discussion here to cover these points:
- Are there any clear technical limitations to showing the callout on click?
- Are there any design considerations in favor of or against this approach?
- Should there be an equivalent keyboard button to show suggestions?

**What component or utility would this be added to**
Base Picker, People Picker

**Comment by aneeshack4** [comment]
@JoshuaLamusga If you just click outside the picker and then click in again the suggestions box pops up again... were you aware of this?

**Comment by JoshuaLamusga** [comment]
I'm aware, but this does not occur if the user clicks while focus already exists, which is part of point no. 4. We think it's disruptive to require users to click in, select, click out repeatedly in the case that they don't immediately start typing (or if they're on a mobile device).

**Comment by aneeshack4** [comment]
Ah I see we can file this a feature request then.

**Comment by JoshuaLamusga** [comment]
@joschect @micahgodbolt could I get your input?

For BasePicker.tsx, there are two props to set suggestions:
* `onResolveSuggestions` (required)
* `onEmptyInputFocus`

There are 3 scenarios for displaying suggestions on user input (last is the new scenario):
1. Show suggestions when the user types
2. Show suggestions when the user clicks, shifting focus to the input
3. Show suggestions when the user clicks, not shifting focus to the input

There is a little ambiguity in which list should be displayed in scenario 3.

**Approach 1 (bad)**
If I use the list from `onResolveSuggestions`, then we get this scenario:

1. The user tabs to or clicks the picker for the first time. List from `onEmptyInputFocus` is shown.
2. The user presses escape, or selects an item.
3. The user clicks within the textbox without changing focus. List from `onResolveSuggestions` is shown.
4. The user is confused because they got a different list.

**Approach 2 (seems okay)**
If I use the list from `onEmptyInputFocus`, then the prop name should be deprecated and renamed to something like `onResolveClickSuggestions`. Also, we get this scenario:

1. The user tabs or clicks the picker for the first time. List from `onEmptyInputFocus` is shown.
2. The user starts typing a name. List from `onResolveClickSuggestions` is shown.

Approach 2 seems fair. If `onEmptyInputFocus` is defined, show those suggestions. Otherwise, show suggestions from onResolveClickSuggestions. It stays as consistent to the user as the current behavior. The other alternative is to make a new prop for this, but I don't think this behavior should be an option as it's too fine-grained and technical.

**Comment by jacksonv1lle** [comment]
I would like for the suggestions to only appear when the user types. Is it possible to prevent the callout from appearing on click?
