### ISSUE TITLE
Link control text color is not rendering as blue in SharePoint Collaboration sites

### ISSUE THREAD

**Issue by mahesh2005** [OfficeDev/office-ui-fabric-react#9375]
I am using UI Fabric controls in SharePoint Framework Extension. 
It is a simple React control that renders the following fabric control
`  <MessageBar messageBarType={ MessageBarType.severeWarning }>
       Warning Message.
        <Link  href="https://www.microsoft.com" target="_blank">See this link for additional details. 
        </Link>
    </MessageBar>`

The issue is that the Link control does not render(Link color is not in blue color) as expected in a SharePoint collaboration site, it looks fine in a communication site. You can see the difference in the screen shot below:
![LinkIssue](https://user-images.githubusercontent.com/22297919/59122030-4409df80-891f-11e9-8830-707809a4cd21.jpg)

I am deploying the SharePoint Framework Extension to a SharePoint online demo tenant.

**Comment by aneeshack4** [comment]
This seems like a problem with the styling being added on the Collaboration site... not anything to do with the Fabric Link component itself. Please contact the team responsible for that.

**Comment by mahesh2005** [comment]
Both the sites are out of the box Office 365 SharePoint online sites. I guess i will just use a custom anchor tag to resolve my issue but i think SharePoint online collaboration sites and Office fabric ui are not completely compatible.
