### ISSUE TITLE
Picker: refresh suggestions

### ISSUE THREAD

**Issue by oleg-mtr** [OfficeDev/office-ui-fabric-react#9376]
I need `picker.refreshSuggestions()` because I do AJAX after `onResolveSuggestions` prop call to load dynamically suggestions as auto-complete, but there is no way to make `onResolveSuggestions` execute again after AJAX finish.

Currently I am doing this hack:

```js
const picker = this.pickerRef.current;
// @ts-ignore
const currentInputValue = picker.input.current.state.displayValue;
// @ts-ignore
picker.updateValue(currentInputValue);
```

https://github.com/OfficeDev/office-ui-fabric-react/blob/131c028a3b3ba75f1349cc83c662c65d5cb1d216/packages/office-ui-fabric-react/src/components/pickers/BasePicker.tsx#L392-L394

**Comment by aneeshack4** [comment]
Hi @oleg-mtr, you should be able to put the ajax call into a promise. https://www.taniarascia.com/how-to-promisify-an-ajax-call/

**Comment by oleg-mtr** [comment]
@aneeshack4 How is this related to my request?
It doesn't matter how I do the AJAX, at the end I need to manually trigger suggestions refresh.

**Comment by joschect** [comment]
@oleg-mtr Could you explain your scenario a bit more? Why does the ajax need to trigger suggestions refresh? If you could add a codepen with an example that might help clear things up. Here is a people picker [codepen](https://codepen.io/slimemold/pen/oZOvWW) to get things started

**Comment by oleg-mtr** [comment]
I made `<TagPicker>` behave like an API autocomplete.

Here is the main idea of my code _(I can't make a codepen from my component because it's complicated and will take a lot of time)_

```js
<TagPicker
    onResolveSuggestions={onSuggestions}
    resolveDelay={300}
/>

const tagPickerReference = ...;

let suggestions = [];

const onSuggestions = (search: string, selectedTags: ITag[]): ITag[] => {
    const matchedSuggestions = getMatchedSuggestions(search, suggestions);

    doAjax(search);

    return matchedSuggestions;
}

const doAjax = (search: string): void => {
    const suggestionsFromAjax = ...;

    suggestions = [...suggestionsFromAjax, ...suggestions];

    tagPickerReference.refreshSuggestions(); // I need this
}
```

I don't think this is useful and just makes things confusing. I just need `picker.refreshSuggestions()`.

**Comment by joschect** [comment]
It's pretty core to the way that the picker works that all things should go through onSuggestions. You can accomplish your goal by doing something like
``` 
const onSuggestions = (search: string, selectedTags: ITag[]): ITag[] => {
    const matchedSuggestions = getMatchedSuggestions(search, suggestions);

    return doAjax(search);
}

const doAjax = (search: string): Promise<ITag[]> => {
    return new Promise(() => {
        ajaxCallBack = (suggestionsFromAjax) =>   resolve([...suggestionsFromAjax, ...suggestions]);
        ajaxCall(ajaxCallBack /** success callback */, reject /** failureCallback */);
        });
}
```

**Comment by oleg-mtr** [comment]
I missed that promise in return type. Nice!
Thank you @joschect

**Comment by oleg-mtr** [comment]
Hmm, I use redux-saga to do the ajax so the promise solution will not work, because ajax is happening somewhere deep in the application then in my component is rerendered and I just receive the new suggestions as prop and I detect if suggestions are different then I need to call
`picker.refreshSuggestions()`.

So, can you add `picker.refreshSuggestions()`?

**Comment by joschect** [comment]
@oleg-mtr We could add the ability for you to pass your own suggestions through as a prop, making the picker more controlled than it already is, but that would mean that the parent component would need to control a lot more than it already does. The pickers are, unfortunately, pretty tightly connected to the resolveSuggestions callback and changing that will likely have to wait until we refactor the pickers, which we are starting work on. 

You can get it to work, although you'll wind up doing potentially bad things with promises, like in [this codepen](https://codepen.io/slimemold/pen/oZOvWW)

**Comment by oleg-mtr** [comment]
@joschect I don't ask for refactor and new props. Why is adding this method is such a big deal?

```js
public refreshSuggestions() {
  const currentInputValue = input.current ? input.current.state.displayValue : "";
  this._onResolveSuggestions(currentInputValue);
}
```

**Comment by joschect** [comment]
@oleg-mtr I am hesitant to add more methods. React wants props to flow down, rather than interact via refs. IMO the correct fix for this would be to move state to a higher level and have the suggestions be passed in via prop rather than by updating the pickers state. 

Outside of the workaround that I provided above, you have another option that will work.

While we are currently working to refactor the pickers so they no longer have inheritance, you could accomplish your goal by extending the base picker and using that. 

This is not recommended, but this code snippet will add what you want, and you can go from there. You should also be able add this to specific pickers if you don't want it added to base picker.

```
export class NewPicker<T,P extends IBasePickerProps<T>> extends BasePicker<T, P> {

  public refreshSuggestions() {
    const currentValue = this.input.current ? this.input.current!.value : "";
    this.updateValue(currentValue);
  }

}
``` 
or

```
export class NewNormalPeoplePickerBase extends NormalPeoplePickerBase {
  public refreshSuggestions() {
    const currentValue = this.input.current ? this.input.current!.value : '';
    this.updateValue(currentValue);
  }
}

```

**Comment by oleg-mtr** [comment]
I will continue using my hack. If you will release a major update I will adapt my code. I will not bother you anymore with this feature request. Thanks
