### ISSUE TITLE
ContextMenu with split button and the width not automatic does not handle text wider than the dropdown well

### ISSUE THREAD

**Issue by jgage176** [OfficeDev/office-ui-fabric-react#9384]
### Environment Information 
 
- __Package version(s)__: 6.189.2 
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
 
Repro by going to https://fabricweb.z5.web.core.windows.net/oufr/6.189.2/#/examples/contextmenu and on the ContextualMenu with checkable menu items and toggleable split button change the width of the ms-ContextualMenu to 223px (mimicking constrained with the useTargetWidth option) and you will see the last menu item is not correctly centered and the split button is not correct. If you delete an the ms-Icon-placeHolder from one of the menu items with the split (which will be how it is if you don't have icons) and make the text a fair bit longer you will see how it it runs off both sizes and pushes the split arrow off the side.

#### Actual behavior:

Text is cut off on both sides and the arrow on the right is pushed off the screen
 
#### Expected behavior:
 
Text is correctly pruned with the ellipsis as happens without the split menu.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) Maybe, I haven't looked into the code closely on this issue yet.
 
Requested priority: (Blocking, High, Normal, Low) Normal. We are GA with the feature using this on June 13th, but it only affects long strings. Not sure how to workaround it yet, but it doesn't make the feature unusable, but it is a bad experience for the user if the text is too long.
 
Products/sites affected: (if applicable) www.microsoftpartnerconnect.com

**Comment by natalieethell** [comment]
Hey @jgage176 thanks for opening this issue! This definitely looks like a bug. Here's a screenshot of what I'm seeing for reference.

![image](https://user-images.githubusercontent.com/14134000/59215289-bc65e000-8b6d-11e9-8669-6dcfb9388ff7.png)


I'll discuss this behavior with the team and get back to you!

**Comment by jgage176** [comment]
I added this to my css and it fixes up the issue quite nicely:

[class*="splitContainer"] [class*="splitPrimary"] {
    width: calc(100% - 28px);
}

The 28px is the min-width of the split menu arrow so it goes quite nice with it. I tried a lot of other css fixes, but this one seems to work flawlessly at every size for a very small change.

**Comment by jgage176** [comment]
Side note is that below ~180px in width the split menu starts disappear - feels like some sort of min-width issue, but I don't see it right off:

![image](https://user-images.githubusercontent.com/29739628/59230087-38255400-8b91-11e9-991b-41b20874764a.png)

Probably needs a separate bug.

**Comment by jgage176** [comment]
On the last note I realized that this is the base minWidth of components and is probably okay. They really shouldn't go smaller than that and if they do it is probably okay to start cutting it off. At some point it has to say: this is all the smaller I get, otherwise you would just have … for all the menu items.
