### ISSUE TITLE
Performance: Stack.Horizontal.Wrap.Example.tsx has bad CSS example lead to bad browser performance.

### ISSUE THREAD

**Issue by LiangMingChen** [OfficeDev/office-ui-fabric-react#9385]
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:
I am Code Reviewing peer's change and flag the browser render engine (Edge, Blink, Trident) potential rendering engine over head,  He point out he copy that from the Sample code. 

https://github.com/OfficeDev/office-ui-fabric-react/blob/1b705beb1cad712f93da2954511b7d6a1d583797/packages/office-ui-fabric-react/src/components/Stack/examples/Stack.Horizontal.Wrap.Example.tsx#L22

This is out of experience from working with Edge perf lead.
In general, CSS should avoid &lt;tag&gt; name. It is especially worst when it is last of the CSS rule.
1. Browser tend to optimize for div/span with class name (Hash)
2.  Browser tend eval the rule to apply form right to left. 
      --- when you specified rule end with &lt;span&gt;  that lead to Hash look up failed, end up gather every &lt;span&gt; on the page!! then leading down to bad browser performance.

This example happen to hit both.  In general, example should avoid performance pitfall.
 

 
#### Expected behavior:
Change to the last &lt;span&gt; a class name 
 
https://github.com/OfficeDev/office-ui-fabric-react/blob/1b705beb1cad712f93da2954511b7d6a1d583797/packages/office-ui-fabric-react/src/components/Stack/examples/Stack.Horizontal.Wrap.Example.tsx#L22

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by Rajeev-K** [comment]
@LiangMingChen thank you for reporting this issue! This is a valid concern and we are looking into this.
