### ISSUE TITLE
Keyboard focus is visible on disabled contextual menu item

### ISSUE THREAD

**Issue by caiomontei** [OfficeDev/office-ui-fabric-react#9397]
## Codepen demonstrating the issue
https://codepen.io/anon/pen/agbzJJ?&editable=true

## Actual behavior:
Keyboard focus is possible on disabled items.
## Expected behavior:
Keyboard focus should not be possible on disabled items.
## Documentation describing expected behavior
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc=%7b3b98b04f-4fab-4d3e-81af-a0906a34849c%7d

**Comment by Rajeev-K** [comment]
@caiomontei thank you for reporting this issue. We are able to reproduce the problem and we are investigating.

**Comment by Rajeev-K** [comment]
@caiomontei this behavior is intended. Screen-reader users and even power users rely heavily on memory and muscle memory to navigate. By having disabled items be a tabstop, we can ensure that commands are always at the same position. So, for example, if the user has to press down arrow 5 times to get to a specific command, we want that to always be 5 times, even if some other command above is disabled.

**Comment by Rajeev-K** [comment]
@caiomontei If you have any questions or concerns, let us know! Otherwise feel free to close this issue.

**Comment by caiomontei** [comment]
Got it, thanks!
