### ISSUE TITLE
Customizable icons in Message bar

### ISSUE THREAD

**Issue by srinidhiprabhu96** [OfficeDev/office-ui-fabric-react#9398]
**Feature Request:**

Is it possible to have a customizable icon for message bar. This way I could use the message bar to display other kinds of messages that require different icons.

Specifically, I want to be showing a message bar when values are loading (with a spinner), and I would like to use the MessageBar component for this

**Comment by natalieethell** [comment]
Hey @srinidhiprabhu96 thanks for opening this issue! This feature request seems valid to me and it sounds like it's been brought up before: https://github.com/OfficeDev/office-ui-fabric-react/issues/6281#issuecomment-420711448. I'll discuss it with the team to see if we've thought more about what we want to do here and report back!

**Comment by natalieethell** [comment]
Spoke with the team - we'll add this feature request to the backlog. Thanks!
