### ISSUE TITLE
Picker: "removeButtonAriaLabel"  don't have  access to corresponding tag

### ISSUE THREAD

**Issue by pandey11** [OfficeDev/office-ui-fabric-react#9407]
Is there any way get corresponding tag  for closing button. Currently we can add only generic value for all.

**Comment by natalieethell** [comment]
Hey @pandey11 thanks for opening an issue! We do ask when opening an issue that you please provide a [CodePen](https://codepen.io/) sample of the issue you're facing so we can better understand or if you have a question that you direct it to [StackOverflow](https://stackoverflow.com/questions/tagged/office-ui-fabric). Thanks!

**Comment by pandey11** [comment]
![image](https://user-images.githubusercontent.com/19817488/59292089-e9afac80-8c99-11e9-97d5-f9a06bb2ff6b.png)

Here first and second closing button should announce corresponding tag text.
 <TagPicker
                removeButtonAriaLabel= "This property is expecting a string. There is no way to dynamically assign corresponding tag text"
  />

**Comment by joschect** [comment]
@pandey11 you can actually do this already! Check out this [codepen](https://codepen.io/slimemold/pen/YoPWBp). You can pass in a custom renderer that takes in all the props and returns a custom label for each item!

**Comment by joschect** [comment]
@pandey11  Line 46 in the codepen is the bit that does the work of adding a dynamic label.

**Comment by pandey11** [comment]
@joschect cool thanks
