### ISSUE TITLE
DetailsList selection not updating on items sort

### ISSUE THREAD

**Issue by j-te** [OfficeDev/office-ui-fabric-react#9408]
*Posted as a bug since CodePen / examples do not handle re-selecting.*

I believe **DetailsList** should handle re-sorting of the current selection. This applies to single and multi-select mode. If this isn't agreed as a fix then maybe an example of how to handle it would be handy. For discussion...

### Environment Information 
 
- __Package version(s)__: 6.187.1

### Please provide a reproduction of the bug in a codepen:
 
[Default DetailsList CodePen](https://codepen.io/anon/pen/GbRYPJ)
 
#### Actual behavior:
 
Sorting by column header click does not re-select previous items.
 
#### Expected behavior:
 
Either:
 - a deselect all
 - *or* re-selection of current items

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (Normal)

**Comment by Rajeev-K** [comment]
@j-te thank you for reporting this issue. We are investigating.

**Comment by KevinTCoughlin** [comment]
Currently, it looks like default behavior is to maintain selection by index which is not desirable for obvious reasons in the Codepen above.

The answer up until now is likely that folks need to implement their own `ISelection` interface which is non-trivial. Perhaps we can accommodate in current code or provide some guidance in documentation.

**Comment by Rajeev-K** [comment]
@j-te in scenarios where the items in the array supplied to DetailsList can change, the getKey prop must be supplied. Here's a codepen with a working example: https://codepen.io/krajeev/pen/RzNoLO I only made two small changes to our existing sample code: First, In _generateDocuments I am assigning a key to each document. The document's key does not change even when the items array is sorted. Second, I am also supplying getKey prop to DetailsList. We will be updating our sample code and documentation to reflect this.

**Comment by KevinTCoughlin** [comment]
Awesome debugging @Rajeev-K! Looking forward to the fix.
