### ISSUE TITLE
Add back 'clip' to IRawStyleBase 

### ISSUE THREAD

**Issue by chrismohr** [OfficeDev/office-ui-fabric-react#9413]
Would you accept a PR to add `clip` back to `IRawStyleBase`?

Looks like it was removed here:
https://github.com/OfficeDev/office-ui-fabric-react/pull/2948

We still use it for achieving screenreader text.

```ts
mergeStyleSets({
    root: {
      wordWrap: 'normal',
      textTransform: 'none',
      border: 0,
      clip: 'rect(0 0 0 0)',
      height: '1px',
      margin: '-1px',
      overflow: 'hidden',
      padding: 0,
      position: 'absolute',
      width: '1px',
      display: 'block',
      zIndex: 1,
    },
    focused: {
      position: 'absolute',
      left: '0px',
      top: '0px',
      width: 'auto',
      height: 'auto',
      margin: '10px',
      padding: '6px 10px',
      textAlign: 'left',
      backgroundColor: '#ffe7b8',
      border: 'solid 1px #ffc56c',
      borderRadius: '2px',
      fontSize: '12px',
      lineHeight: '16px',
      clip: 'auto',
    },
  })
```

Error:
Object literal may only specify known properties, and 'clip' does not exist in type 'IRawStyle | IStyleBaseArray'.

**Comment by khmakoto** [comment]
From my understanding, we removed `clip` from `IRawStyleBase` because the feature was removed from web standards (@dzearing might have more info on this). Given that you were using it for screenreader text, it might be good to take a look to the [Announced](https://developer.microsoft.com/en-us/fabric#/controls/web/announced) component.

From the component description:
>The Announced component aims to fill several of the accessibility gaps that exist in various web application experiences. It provides text for the screen reader in certain scenarios that are lacking comprehensive updates, particularly those showing the completion status or progress of operation(s).

Please let us know if that helps with the issue and if not we can talk more about what the correct fix would be here.

**Comment by dzearing** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/clip

Is there a better way to do what you want? `display: none` or `visibility:hidden` for example?

**Comment by KevinTCoughlin** [comment]
What about https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path?

However IE support looks non-existent https://caniuse.com/#feat=css-clip-path.

Another idea would be a span with the properties @dzearing mentioned or even the `hidden` attribute (I think).

**Comment by dzearing** [comment]
or `opacity: 0`... it seems like there are a lot of alternatives. What is special about `clip`?
