### ISSUE TITLE
The quick brown fox jumped over the lazy should be The quick brown fox jumps over the lazy dog

### ISSUE THREAD

**Issue by ahnguyen03** [OfficeDev/office-ui-fabric-react#9416]
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by ahnguyen03** [comment]
I assume the text inside https://developer.microsoft.com/en-us/fabric#/controls/web/text was going for a sentence with every letter which The quick brown fox jumped over the lazy doesnt work as its missing "s" and should be The quick brown fox jumps over the lazy dog

**Comment by ahnguyen03** [comment]
http://www.fun-with-words.com/pangrams.html reference

**Comment by natalieethell** [comment]
Hey @ahnguyen03 thanks for opening an issue! We'd encourage you to open your own PR with this change. Here are some Contributing guidelines to get you started: https://github.com/OfficeDev/office-ui-fabric-react/wiki/Contributing.
