### ISSUE TITLE
Website is not working properly

### ISSUE THREAD

**Issue by Wezea** [OfficeDev/office-ui-fabric-react#9420]
### Bug Report

https://developer.microsoft.com/en-us/fabric#/controls/web

Is not showing the components overview.

Are you willing to submit a PR to fix? (Yes, No)
No

Requested priority: (Blocking, High, Normal, Low) 
High

#### Describe the issue:

Website is not showing components examples and documentation.

**Comment by KevinTCoughlin** [comment]
Sorry about that @Wezea and thanks for the report! Can you clear your browser cache and try again? https://developer.microsoft.com/en-us/fabric#/controls/web/button

**Comment by Wezea** [comment]
It's working now 👍

**Comment by ckoutsiaris** [comment]
Hi, I have the same issue. I cleared the cache, tried different browser etc. but still no luck. Only the "Get Started" works.

![Screenshot 2019-06-12 at 15 04 34](https://user-images.githubusercontent.com/44162302/59357917-8ec29780-8d23-11e9-9017-2e0767d90796.png)

**Comment by mdg357** [comment]
Also seeing this issue. Confirmed it occurs in Chrome (74.0.3729.169) and Edge (77.0.187.0). Tried clearing cache and reloading, but site still appears broken. Seeing the same errors in the console reported by @ckoutsiaris

**Comment by PrimeHydra** [comment]
Same here, getting error shown in ckoutsiaris's screenshot. Cleared cache. Tried Chrome, Firefox and Edge.

**Comment by natalieethell** [comment]
Hey everyone, so sorry for this! We're working on it.

**Comment by dustjones** [comment]
It appears that due to the Fabric webpack build listing React as an external in https://github.com/OfficeDev/office-ui-fabric-react/blob/master/apps/fabric-website/webpack.serve.config.js, the page can load an incompatible version of the library and break the package.  In this case, the package relies on React 16.7+, but the page is loading 16.3.

**Comment by natalieethell** [comment]
Hey everyone - the site should be back up and running! Try clearing your browser cache and loading the site again. Sorry for the trouble!

**Comment by ckoutsiaris** [comment]
Adding a couple of e2e tests in your ci/cd would probably prevent this from happening again 👍 
Thanks for your quick response!
