### ISSUE TITLE
Shimmer accessibility reads table has 11 rows when shimmer is in loading state

### ISSUE THREAD

**Issue by Xizt** [OfficeDev/office-ui-fabric-react#9421]
Issue: Using narrator for accessibility, when navigating to the first column, the narrator reads that table has 11 rows and 9 columns... This issue is when the shimmer is still in loading state. As there are 11 animations while loading narrator reads 11 rows which is not the actual case. I feel it should read  that the rows are being loaded. Once loaded, it reads properly the exact number of rows.

## Codepen demonstrating the issue
Navigate to https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist/shimmer
Use the first example to and Export to Codepen for Repro of the issue

## Actual behavior:
When the shimmer loads, and when you navigate to the column, the narrator reads Table has 11 rows, 9 columns.... 

## Expected behavior:
As the table is being loaded it should read, Table has 9 colums(as they are pre-defined and visible) and rows are being loaded or something similar...

**Comment by KevinTCoughlin** [comment]
cc: @Vitalius1

**Comment by Xizt** [comment]
Any updates on this?

**Comment by Rajeev-K** [comment]
@Xizt thank you for reporting the issue. We are investigating.
