### ISSUE TITLE
Slider: onChanged is not fired on keyUp

### ISSUE THREAD

**Issue by wutonghao** [OfficeDev/office-ui-fabric-react#9426]
### Environment Information 
 
- __Package version(s)__: 6.157.0
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
 https://codepen.io/wuthao/pen/WqvrNJ (Open console to see how onChange & onChanged is fired)
 
#### Actual behavior:
onChanged is not fired on keyUp when we use keyboard to change slider value, but it's fired on mouseUp 
 
#### Expected behavior:
onChanged is fired on keyUp when we use keyboard to change slider value, which is consistent with mouseUp behavior; Only firing onChange for keyboard event does not satisfy our need, especially when the slider range is big and we only want to process the new value in onChanged instead of onChange.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Maybe. I need to get familiar with the code.
 
Requested priority:  High
 
Products/sites affected: We are working on a project that will be shipped soon in Excel Online, and this is one of the issues we target to resolve before shipping.

**Comment by natalieethell** [comment]
Hey @wutonghao thanks for opening an issue! Looking into it.

**Comment by natalieethell** [comment]
Hey @wutonghao just to confirm, you want `onChanged` instead of `onChange` because you only want the Slider value after the user is done changing it? Instead of while the value is changing?

**Comment by wutonghao** [comment]
@natalieethell Yes. In our project, we only want to send API request to process the new value when the user is done changing. If we send API request in every onChange call while value is changing, there will be too many requests for our server to process. That's why we need onChanged to be fired on KeyUp, just like on MouseUp.

**Comment by natalieethell** [comment]
@wutonghao got it, thanks for confirming. The team will discuss a potential change here.
