### ISSUE TITLE
DetailsList not rendering in Callout in Edge browser specifically

### ISSUE THREAD

**Issue by rcasto** [OfficeDev/office-ui-fabric-react#9430]
### Environment Information 
- __Package version(s)__: We use **6.155.0** currently, but appears to affect latest as well, as can be seen from codepen below

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/anon/pen/zVGqBZ
 
#### Actual behavior:
DetailsList does not render in Callout in Edge browser
![image](https://user-images.githubusercontent.com/869330/59383105-199b9600-8d14-11e9-9dc5-269b758e85f5.png)
 
#### Expected behavior:
 DetailsList should render in Callout. Below is image from Chrome browser
![image](https://user-images.githubusercontent.com/869330/59383184-464fad80-8d14-11e9-9d5c-3196bdbf7400.png)

#### Priorities and help requested:
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: Virtual Agent for Customer Service (https://va.ai.dynamics.com)

**Comment by KevinTCoughlin** [comment]
Thanks for reporting this @rcasto, the team will take a look! I wonder #9343 might help this by chance...

**Comment by natalieethell** [comment]
@rcasto looks like it's working on latest now! It could have been fixed be @KevinTCoughlin's PR referenced above. Here's a screenshot from Edge. Let me know if you're seeing something different.

![image](https://user-images.githubusercontent.com/14134000/59461418-2ed8f900-8dd6-11e9-8027-246f3f162940.png)

@KevinTCoughlin should we backport your changes into 6.0?

**Comment by KevinTCoughlin** [comment]
> @KevinTCoughlin should we backport your changes into 6.0?

Yea, I plan to once merges into `6.0` branch are working. I'm watching https://github.com/OfficeDev/office-ui-fabric-react/pull/9437 as a reference...

**Comment by rcasto** [comment]
Yup, just checked and it does in fact seem to be working in Edge now. I'll wait for an updated 6.0 package and integrate from our side. Thanks guys!

**Comment by natalieethell** [comment]
We'll make sure to tag this issue in Kevin's PR targeting `6.0`

**Comment by KevinTCoughlin** [comment]
Fixed and available in `office-ui-fabric-react@v6.190.0`! Going to close as resolved. @rcasto, if not please open a new issue. Thanks!
