### ISSUE TITLE
Missing "IDetailsRowStyles" in office fabric

### ISSUE THREAD

**Issue by AnjaniChallamcherla** [OfficeDev/office-ui-fabric-react#9443]
When I try to use "DetailList" in office fabric, everything is working fine except "IDetailsRowStyles".
Getting the below error, kindly suggest
![image](https://user-images.githubusercontent.com/42473451/59417019-5f149d80-8dbe-11e9-9124-5fc375aaa504.png)

**Comment by KevinTCoughlin** [comment]
Sorry for the friction @AnjaniChallamcherla. Which version of OUFR are you using? I see the symbol publicly exported in our API file:

```shell
// @public (undocumented)
export interface IDetailsRowStyles {
    // (undocumented)
    cell: IStyle;
    // (undocumented)
    cellMeasurer: IStyle;
    // (undocumented)
    cellPadded: IStyle;
    // (undocumented)
    cellUnpadded: IStyle;
    // (undocumented)
    check: IStyle;
    // (undocumented)
    checkCell: IStyle;
    // (undocumented)
    checkCover: IStyle;
    // (undocumented)
    fields: IStyle;
    // (undocumented)
    isMultiline: IStyle;
    // (undocumented)
    isRowHeader: IStyle;
    // (undocumented)
    root: IStyle;
}
```

https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/etc/office-ui-fabric-react.api.md

**Comment by AnjaniChallamcherla** [comment]
I am using OUIF version 1.8.1

**Comment by natalieethell** [comment]
You are using office-ui-fabric-react version 1.8.1? We currently are on Fabric 7 - you may want to consider upgrading to version 6 or 7.

**Comment by KevinTCoughlin** [comment]
> I am using OUIF version 1.8.1

@AnjaniChallamcherla, I believe that version is your SPFx version. Can you run the following command in your repository which should tell us the version of `office-ui-fabric-react` your project is dependent on: `npm list office-ui-fabric-react`

Here is example output from a test repo:

```shell
~\test> npm list office-ui-fabric-react
test@1.0.0 ~\test
`-- office-ui-fabric-react@7.2.0
```

**Comment by AnjaniChallamcherla** [comment]
@KevinTCoughlin Yes Kevin, That was my SPFx version. My OUIF version is 5.13.0

**Comment by AnjaniChallamcherla** [comment]
I downgraded my SPFx to 1.6.0 and I have my OUIF 5.120.0

Now I am not getting any errors. Was the issue because of my SPFx version as 1.8.1?

This is my package.json
`{
  "name": "search",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/sp-core-library": "1.6.0",
    "@microsoft/sp-lodash-subset": "1.6.0",
    "@microsoft/sp-office-ui-fabric-core": "1.6.0",
    "@microsoft/sp-webpart-base": "1.6.0",
    "@pnp/common": "^1.2.3",
    "@pnp/logging": "^1.2.3",
    "@pnp/odata": "^1.2.3",
    "@pnp/sp": "^1.2.3",
    "@types/es6-promise": "0.0.33",
    "@types/react": "15.6.6",
    "@types/react-dom": "15.5.6",
    "@types/webpack-env": "1.13.1",
    "react": "15.6.2",
    "react-dom": "15.6.2",
    "timeago-react": "^2.0.0",
    "uuid": "^3.3.2"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.6.0",
    "@microsoft/sp-module-interfaces": "1.6.0",
    "@microsoft/sp-webpart-workbench": "1.6.0",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2",
    "gulp": "~3.9.1",
    "tslint-microsoft-contrib": "~5.0.0"
  }
}
`

**Comment by natalieethell** [comment]
@AnjaniChallamcherla in your previous comment, I see errors from the `@uifabric/merge-styles` package. I also see that in your package.json, you're using rush-stack-compiler-2.7. Try upgrading to rush-stack-compiler-2.8 and let me know if that fixes it for you!

**Comment by AnjaniChallamcherla** [comment]
@natalieethell Sorry for late reply
I upgraded rush-stack-compiler to 2.8
Still couldn't fix the error.
My OUIF version: 6.143.0

Below is my package.json:
`{
  "name": "rw-projects",
  "version": "0.0.1",
  "private": true,
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "build": "gulp bundle",
    "clean": "gulp clean",
    "test": "gulp test"
  },
  "dependencies": {
    "@microsoft/rush-stack-compiler-2.8": "^0.1.5",
    "@microsoft/sp-core-library": "1.8.1",
    "@microsoft/sp-dialog": "^1.8.2",
    "@microsoft/sp-lodash-subset": "1.8.1",
    "@microsoft/sp-office-ui-fabric-core": "1.8.1",
    "@microsoft/sp-property-pane": "1.8.1",
    "@microsoft/sp-webpart-base": "1.8.1",
    "@pnp/common": "^1.3.2",
    "@pnp/logging": "^1.3.2",
    "@pnp/odata": "^1.3.2",
    "@pnp/sp": "^1.3.2",
    "@types/es6-promise": "0.0.33",
    "@types/react": "16.4.2",
    "@types/react-dom": "16.0.5",
    "@types/webpack-env": "1.13.1",
    "office-ui-fabric-react": "^5.135.0",
    "react": "16.7.0",
    "react-dom": "16.7.0",
    "react-timeago": "^4.4.0"
  },
  "resolutions": {
    "@types/react": "16.4.2"
  },
  "devDependencies": {
    "@microsoft/sp-build-web": "1.8.1",
    "@microsoft/sp-tslint-rules": "1.8.1",
    "@microsoft/sp-module-interfaces": "1.8.1",
    "@microsoft/sp-webpart-workbench": "1.8.1",
    "@microsoft/rush-stack-compiler-2.7": "0.4.0",
    "gulp": "~3.9.1",
    "@types/chai": "3.4.34",
    "@types/mocha": "2.2.38",
    "ajv": "~5.2.2"
  }
}
`
Do I need to downgrade SPFx or OUIF or any other?

**Comment by natalieethell** [comment]
@AnjaniChallamcherla in your package.json, I see office-ui-fabric-react version 5.135.0. Is that up to date?

**Comment by AnjaniChallamcherla** [comment]
Yes, its up to date

**Comment by KevinTCoughlin** [comment]
@AnjaniChallamcherla, the fix for this missing type is not available in `office-ui-fabric-react` versions `5.x`. However _it is available_ in versions `6.x` and greater. Looking at your `package.json` in https://github.com/OfficeDev/office-ui-fabric-react/issues/9443#issuecomment-506292596, your project has `office-ui-fabric-react` pinned to a version that does not contain the fix:

````json
    "office-ui-fabric-react": "^5.135.0",
```

Can you change that line to:

```json
    "office-ui-fabric-react": "6.192.1"
```

Then install dependencies and re-build your project to see if you still face the issue?
