### ISSUE TITLE
[Details List] - In scan mode, extra navigation step is encountered while navigating from checkbox to header name

### ISSUE THREAD

**Issue by Harish9450** [OfficeDev/office-ui-fabric-react#9465]
### Environment Information 
 
- __Package version(s)__: Office-fabric v6.40.1
- __Browser and OS versions__: Edge & Win-10

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/v-harc/pen/RzWdjz
 
#### Actual behavior:
In scan mode, extra navigation step is encountered while navigating from checkbox to column name. When narrator focus is on check box and user press down arrow key, it announces 'table has 55 rows 5 column, non selected, read only column header,checkbox unchecked, select all , read only' and focus goes to hidden label.
 
#### Expected behavior:
In scan mode, extra navigation step should not encountered while navigating from checkbox to header name. When narrator focus is on check box and user press down arrow key, focus should move to first column name of details list.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? ( No)
 
Requested priority: (Normal) 
 
Products/sites affected: (if applicable)

**Comment by Rajeev-K** [comment]
@Harish9450 thank you for reporting the issue. Can you confirm the hidden label you mention is the one with the text "Toggle selection for all items"?

**Comment by Harish9450** [comment]
![MAS4 2 10_Extra-navigation-step](https://user-images.githubusercontent.com/38786340/59600317-7a650d00-911e-11e9-837b-d4417b49eb0c.gif)

**Comment by natalieethell** [comment]
So one way of improving this experience would potentially be to add `aria-hidden=true` to that label element in that extra navigation step. In some initial testing, it seems like the label, "Toggle selection for all items", is still read out when focused on the checkbox (good) and I am able to navigate directly to the first column header without stopping at the label. We'll do some more investigation to see if this is a reasonable solution.

**Comment by Harish9450** [comment]
> @Harish9450 thank you for reporting the issue. Can you confirm the hidden label you mention is the one with the text "Toggle selection for all items"?

Yes, focus is moving on hidden label i.e "Toggle selection for all items"
