### ISSUE TITLE
Styling not being applied to Text component in Fabric 7

### ISSUE THREAD

**Issue by askast** [OfficeDev/office-ui-fabric-react#9469]
- __Package version(s)__: 7.2.0
- __Browser and OS versions__: Chrome/Edge

https://codepen.io/askast/pen/ydegaa
This shows the Text being rendered with the wrong font. 

 https://codepen.io/askast/pen/rExjNj
It shows the expected behavior - Font being rendered properly, with version 6.174.0

Its an issue that I noticed first with v7.0.0

**Comment by natalieethell** [comment]
Hey @askast thanks for reporting an issue! From what I'm seeing, it looks like the Fluent styles are actually now being applied to the Text control, which is expected. In Fabric 7, Fluent styles are applied by default to all controls. So now, the mega text variant has font size 68px and font weight 600, whereas before it had font size 72px and font weight 100. It looks like the correct font family, Segoe UI, is being applied as well.

Let me know if that makes sense!

**Comment by natalieethell** [comment]
You can see the new default font styles defined here: https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/styling/src/styles/fonts.ts#L71

**Comment by askast** [comment]
Ok. That makes sense. But the font didn't have the 600 weight by default when i used Fluent Customization with a Customizer in version 6. Which is why i was confused.

**Comment by natalieethell** [comment]
No problem! Let me know if you have any other questions, otherwise feel free to close this issue.
