### ISSUE TITLE
Placeholder text color not honored in Edge

### ISSUE THREAD

**Issue by joechung-msft** [OfficeDev/office-ui-fabric-react#9478]
### Environment Information 
 
- __Package version(s)__: 6.190.0 
- __Browser and OS versions__: Edge 44.18362.1.0, Windows 10.0.18362.175 (May 2019 Update)

### Please provide a reproduction of the bug in a codepen:

https://codepen.io/joechung-msft/pen/vqGJGo
 

 
#### Actual behavior:
 
Placeholder text styles are not applied in Edge.

![image](https://user-images.githubusercontent.com/26208574/59574273-7af09b80-906b-11e9-8eca-71e9d526c4ed.png)
 
#### Expected behavior:
 
Placeholder text styles should be applied in Edge.

![image](https://user-images.githubusercontent.com/26208574/59574288-8774f400-906b-11e9-9ac0-7671a4e8a3cc.png)

The `::-ms-input-placeholder` pseudo-class should also be used to style input placeholders in newer versions of Edge.  `:-ms-input-placeholder` applies for Internet Explorer (and possibly older versions of Edge).

https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/TextField/TextField.styles.tsx#L287-L293

This issue might also apply for the `SearchBox` component.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No
 
Requested priority: (Blocking, High, Normal, Low) Normal
 
Products/sites affected: (if applicable)

**Comment by aftab-hassan** [comment]
@joechung-msft Thank you for reporting this. I can see the placeholder text not adhering to styles in `Edge`. 

In the latest `Edge Dev` version, however, the placeholder text does show styles as expected. I am using `Version 76.0.182.6 (Official build) dev (64-bit)` of `Edge Dev`.

@micahgodbolt would this be a fix from the fabric side, or one for the `Edge` team ?

**Comment by micahgodbolt** [comment]
Nah, this is a legit bug. 

IE11 uses `:ms-input-placeholder` and Edge uses `::ms-input-placeholder`

With both of those browsers in our support matrix, we need to output both it seems.

**Comment by micahgodbolt** [comment]
also note that edge supports ::webkit-input-placeholder.

**Comment by aftab-hassan** [comment]
> Nah, this is a legit bug.
> 
> IE11 uses `:ms-input-placeholder` and Edge uses `::ms-input-placeholder`
> 
> With both of those browsers in our support matrix, we need to output both it seems.

@micahgodbolt noticed that too, and tested that the additional colon fixes for all browser. I'll have a PR out for this.

**Comment by joechung-msft** [comment]
Can this fix be backported to 6.x?

**Comment by aftab-hassan** [comment]
> Can this fix be backported to 6.x?

Here is the PR for the backport. https://github.com/OfficeDev/office-ui-fabric-react/pull/9789
