### ISSUE TITLE
Summary field for SearchBox result

### ISSUE THREAD

**Issue by mm90849491** [OfficeDev/office-ui-fabric-react#9485]
**Describe the feature that you would like added**
A place holder to display search result information upon search text change or after search.
It could be a short text, such as a result count, or a complex component showing a preview of search items.

**What component or utility would this be added to**
SearchBox

**Have you discussed this feature with our team, and if so, who**
No

**Additional context/screenshots**
Right now my implementation is using a TextField to mimic a search box with a suffix printing the total number of available items or match out of total if there is any input. The text could be somewhere else like right under the SearchBox as additional label  (when underlined?).
Code snippet:
```
        <TextField
          styles={{ suffix: { backgroundColor: 'transparent' } }}
          suffix={countText}
          placeholder={'Search'}
          value={this.state.filterText}
          onBeforeChange={this._onFilterChanged}
        />
```

**Comment by aftab-hassan** [comment]
Hey @mm90849491 thanks for opening this issue! 

I'd like to get some more clarity on the feature you are requesting. Upon change of text on the `SearchBox` , were you intending to see a short text such as "Found 4 items", or a `DetailsList` result of the items found upon search?

Could you provide us a screenshot or a design of the component you'd like to see ?

**Comment by mm90849491** [comment]
Hi aftab-hassan,

Thanks for the fast response!
I attached two of my current design which are for Excel task-pane size. Your fabric-react/fluent team usually has a better design than my own implementation so I was intended to leave the idea more open.
 If it is not so hard to maintain, leaving the content as a customisable field would be great (like how Callout or Modal components work).

![default](https://user-images.githubusercontent.com/10732375/59634869-9491f180-9104-11e9-8297-953fa919c2af.png)
![underlined](https://user-images.githubusercontent.com/10732375/59634870-952a8800-9104-11e9-83d4-5efaf3dbb2e1.png)

**Comment by aftab-hassan** [comment]
@mm90849491 thank you for providing a design! It helps ensure we are on the same page regarding what the feature should do.

I'll discuss with the team to get their thoughts on this feature, and report back here.

**Comment by aftab-hassan** [comment]
@micahgodbolt wanted to get your thoughts here. Is this a feature request we have previously received for `SearchBox` ? Are we good with adding this to `Backlog review` ?

**Comment by micahgodbolt** [comment]
So it looks like the ask here is to support suffix in search, just like the Textfield is doing. My only hesitation here is that our current design for search includes an X at the far right to clear the search contents. Adding this would certainly remove that clear button, and this might cause accessibility issues. 

i.e. this isn't an unreasonable ask, but I'd want to make sure this change was design driven, and that design accounted for the removal of that clear button.

**Comment by micahgodbolt** [comment]
I think for now, if the Textfield is working properly, they should stick with that solution. Our searchbox doesn't leave room for that suffix, and removing the "X" would have negative accessibility impact. 

i.e. it's a good idea for the backlog, but not something we'd prioritize right now.
