### ISSUE TITLE
CommandBar with item set as `iconOnly` and `name` causes UI crash on hover (issue with DelayedRender created by TooltipBase) - 7.4.0

### ISSUE THREAD

**Issue by glennflanagan** [OfficeDev/office-ui-fabric-react#9493]
CommandBar with item set as `iconOnly` and `name` causes UI crash on hover (issue with DelayedRender created by TooltipBase)

![image](https://user-images.githubusercontent.com/5485364/59696813-a3e86c00-91e4-11e9-8bcf-3d7664f8644c.png)

### Environment Information 
 
- 7.4.0
- MacOS - Chrome 75.0.3770.90, Firefox 66.0.5

### Please provide a reproduction of the bug in a codepen:
 [Codesandbox Link here](https://codesandbox.io/embed/fancy-browser-mtvcy) demonstrating the issue

1. Create a CommandBar with a single item, that item should have `iconOnly` set to `true` and `name` set to any string.
2. Hover over the icon button
3. Observe error in browser console
 
#### Actual behavior:
 
Ui crashes after mouse is hovered over the icon button
 
#### Expected behavior:
 
Tooltip should display and UI should not crash.

**Comment by glennflanagan** [comment]
Also occurs in 7.3.0 https://codesandbox.io/embed/fancy-http-7sikw

**Comment by aftab-hassan** [comment]
@glennflanagan Thanks for reporting the issue and providing a codesandbox link of the issue. I can see UI crashing upon mouse hover. Marking as bug, and taking a look at it.

**Comment by natalieethell** [comment]
Hey @glennflanagan thanks for opening an issue! We reverted the change that was causing this issue, so it should be fixed in Fabric v7.4.1. Let us know if that works for you!

**Comment by aftab-hassan** [comment]
@natalieethell thanks natalie

@glennflanagan this was fixed in this [PR](https://github.com/OfficeDev/office-ui-fabric-react/pull/9495) You should not be hitting the issue now, if you could move to `7.4.1`.

**Comment by glennflanagan** [comment]
Amazing! Thank you so much for the speeeeeeed!
