### ISSUE TITLE
Website: Point to Fabric 7

### ISSUE THREAD

**Issue by lynamemi** [OfficeDev/office-ui-fabric-react#9497]
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:
 
Right now the fabric website is pointing to Fabric 6. It should be updated to point to Fabric 7.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) No (it's already on @ecraig12345 's radar)
 
Requested priority: (Blocking, High, Normal, Low) Normal
 
Products/sites affected: (if applicable)

**Comment by ecraig12345** [comment]
This should finally be done--so sorry about the delay! Let me know if you see any issues.
