### ISSUE TITLE
Is it possible to control the Context Menu with component state?

### ISSUE THREAD

**Issue by jacksonv1lle** [OfficeDev/office-ui-fabric-react#9507]
Hi there,

I am trying to control the show/hide of the context menu using component state and the 'hidden' property of the IContextualMenuProps but this is not working for me.

Please see this [CodePen](https://codepen.io/ijackson/pen/orYbdP) example.

**Comment by aftab-hassan** [comment]
Thank you for posting the issue @jacksonv1lle

We see the issue, but would need to look at it a bit deeper. Marking as `bug` for now, and looking at it. Please check back here for updates.

Thanks for the codepen!

**Comment by aftab-hassan** [comment]
@jacksonv1lle [Here](https://codepen.io/aftab-hassan/pen/mZOXvE?editors=0010) is an updated codepen which would solve your issue.

Here are the diffs from your codepen
1. If `menuProps` are passed in, then we end up [invoking](https://github.com/OfficeDev/office-ui-fabric-react/blob/d4e05a01bc75ed3ce8d4522734e822810ba356bf/packages/office-ui-fabric-react/src/components/Button/BaseButton.tsx#L652)  the `onMenuClick` function. Changed your codepen to call the same. 

2. You were setting the `hidden: false` inside the `render` function irrespective of the state (probably a typo)

Please let us know if this solves your issue. Un-marking from `bug`

**Comment by jacksonv1lle** [comment]
Hey. Thanks for your help. I didn't see the `onMenuClick` function so now that's allowing me to invoke my click handler as expected. 

But the context menu is still not controlled by the state. If you open the menu and then click away, the menu will close but the state will not change.

**Comment by aftab-hassan** [comment]
@jacksonv1lle, thanks for pointing that out. Another issue to add to the one you mentioned is that the default state of `isHidden` is set to false, but the `ContextualMenu` still shows up.  

@joschect is currently investigating this (took a brief look and feels it could be related to having to set `state` in  `onMenuOpened` and `onMenuClosed`).

**Comment by micahgodbolt** [comment]
The button maintains it's own state by default to simplify creating a contextual menu button. If you want to simply own state, and show/hide a separate contextual menu, you are certainly welcome to. This is how you'd do it if we hadn't baked menu into the button.  i.e. the only reason to use the internal button contextual menu is to avoid having to set state yourself.

**Comment by micahgodbolt** [comment]
This is probably something we should consider when looking at the new button as well, @khmakoto

**Comment by khmakoto** [comment]
Hi @jacksonv1lle, sorry for the long time before replying again. What @micahgodbolt suggested back in June is one way you could achieve this. Did you have a chance to play with that idea?
