### ISSUE TITLE
Can not close Fabric 7 multi select dropdown when screen size is set to mobile size

### ISSUE THREAD

**Issue by asith-w** [OfficeDev/office-ui-fabric-react#9508]
## Codepen demonstrating the issue
 
https://codepen.io/anon/pen/ydVOLo 
## Actual behavior:
when i resize the screen to mobile view, there is no way to close the panel. dropdown menu takes full width of screen where fabric ui 6 dropdown menu (mobile view )only takes percentage and able to dismiss the menu  
## Expected behavior:
there are should be close button or additional space to dismiss the dropdown menu similar to fabric ui 6
## Documentation describing expected behavior

![image](https://user-images.githubusercontent.com/5784846/59767661-63f6b700-92c0-11e9-9e2f-f97e3f12764b.png)

![image](https://user-images.githubusercontent.com/5784846/59767128-3cebb580-92bf-11e9-87e3-fa99f4100c00.png)

**Comment by aftab-hassan** [comment]
@asith-w, thank you for posting the issue and providing a codepen.

 I verified that the issue occurs in `Fabric 7` and does not in `Fabric 6` (Tested using `6.190.0`). We are looking into it.

**Comment by micahgodbolt** [comment]
Seems the @6 version had the panel only come half way out 
![image](https://user-images.githubusercontent.com/1434956/59800091-942b5f00-929a-11e9-8650-205fe2657f4c.png)

**Comment by micahgodbolt** [comment]
appears that his media query is not firing 
![image](https://user-images.githubusercontent.com/1434956/59800206-d785cd80-929a-11e9-90eb-de71c5d98b54.png)

**Comment by aftab-hassan** [comment]
This was fixed in this [PR](https://github.com/OfficeDev/office-ui-fabric-react/pull/8937/files) but we lost these changes when moving to `Fabric 7`. Don't see a history of when this was removed. 

The fix would be to bring back this change.
