### ISSUE TITLE
Textbox Component OnChange called twice + this._async.debounce not working

### ISSUE THREAD

**Issue by realhoffi** [OfficeDev/office-ui-fabric-react#9522]
nice breaking change...

What is not working anymore:

- Async on "OnChange"
- Onchange is called twice without the Async Function...

```
<TextField
        {...this.props.textFieldProps}
        id={this.props.inputKey}
        key={this.props.inputKey}
        value={this.state.currentValue}
        onChange={this._async.debounce(this.onChange, this.props.debounceInterval || ControlConstants.DEFAULT_DEBOUNCE_INTERVAL)}
        errorMessage={this.state.currentError}
        multiline={true}
      />

private onChange = (event: React.FormEvent<HTMLInputElement | HTMLTextAreaElement>, value: string): void => {
    const validationResult = this.validateValue(value);
    this.setState(
      (prevState: IBaseInputControlState<string>) => {
        prevState.isValid = validationResult.isValid;
        prevState.currentError = validationResult.errorMessage;
        prevState.currentValue = value;
        return prevState;
      },
      () => {
        // && this.state.currentValue !== this.props.value
        if (this.props.onValueHasChanged) {
          this.props.onValueHasChanged(this.props.inputKey, this.state.currentValue);
        }
      }
    );
  };
```

**Comment by ecraig12345** [comment]
Thanks for reporting this. For debugging, it would be helpful if you could provide a codepen reproducing the issue. You can start from the template at http://aka.ms/fabricpen or by clicking "Export to CodePen" on one of the [TextField examples](https://developer.microsoft.com/en-us/fabric#/controls/web/textfield).

**Comment by aftab-hassan** [comment]
Thanks for noticing this and taking a look, @ecraig12345 !

**Comment by aftab-hassan** [comment]
@realhoffi also, if you could kindly confirm the version, whether `Fabric 6` or `Fabric 7`, that would be useful too.

**Comment by realhoffi** [comment]
hi, it is Version 7.4.2

**Comment by ecraig12345** [comment]
Could you provide a codepen (instructions in previous comment) reproing the issue? Without a repro, I'm not sure what you mean about `onChange` getting called twice--just the fact that we use the object version of setState instead of the callback version shouldn't cause that.

**Comment by pitric** [comment]
Having the same issue. In the following simple example the forEach loop runs twice.

```typescript
import * as React from 'react';
import { TextField } from 'office-ui-fabric-react/lib/TextField';

function OnchangeTwice() {
    const listNumbers = (event: React.FormEvent<HTMLInputElement | HTMLTextAreaElement>, text: string | undefined) => {
        const numbers: Array<string> = ['ONE', 'TWO', 'THREE'];
        numbers.forEach(element => {
            console.log('Each element in numbers...' + element);
        });
    }
    return (
        <TextField
            onChange={listNumbers}
        />
    );
}
export default OnchangeTwice;
```

**Comment by TomekPi** [comment]
Having the same issue, `onChange` event if fired twice on every key stroke.

Isn't that because it's pinned to both `input` and `change` native events which in react are actually the same (`change` event occurs immediately after element change, not after loosing focus)?

**Comment by elly0t** [comment]
Have just encountered the same issue, any plan on fixing this?

My current solution is downgrading the library to `6.195.1` where `onChange` won't be triggered twice.

**Comment by zhongyn** [comment]
same issue, onchange triggered twice for every key press

**Comment by elly0t** [comment]
the version I'm using - `"office-ui-fabric-react": "7.15.0"`

Tried to downgrade to v6 and the `onChange` method fired only *once*, which is the desired behaviour from most of us. However I need to stay on v7 for the new styling.

Apparently lots of us are experiencing the same issue. I'm wondering if there's any plan on having this fixed or clarified? As stated by @TomekPi,

> Isn't that because it's pinned to both `input` and `change` native events which in react are actually the same (`change` event occurs immediately after element change, not after loosing focus)?

I don't really see the need of `onChange` being triggered twice by `input` and `change`, which in React is basically the same?

For others who are actively seeking a solution, place a line of `if (event.type === "change")` in front of your `onChange` logic should suffice: 
```ts
<TextField
  ...
  onChange={this._onChange}
  ...
/>

_onChange = (
  event: React.FormEvent<HTMLInputElement | HTMLTextAreaElement>,
  value: string | undefined
) => {
  if (event.type === "change") {
    //...HERE COMES YOUR CODE...
  }
}
```

A visually cleaner solution would be wrapping `TextField` with your own component (say `MyTextField`) where the custom `_onChange` method is placed within. Unfortunately this is just a workaround, where one of the doubly fired events is ignored so only one event is received on your end.

**Comment by elly0t** [comment]
The version I'm using - `"office-ui-fabric-react": "7.15.0"`

Tried to downgrade to v6 and the `onChange` method fired only once, which is the desired behaviour from most of us. However I need to stay on v7 for the new styling.

Apparently lots of us are experiencing the same issue. I'm wondering if there's any plan on having this fixed or clarified? As stated by @TomekPi,

> Isn't that because it's pinned to both input and change native events which in react are actually the same (change event occurs immediately after element change, not after loosing focus)?

I don't really see the need of onChange being triggered twice by the events `input` and `change`, which in React are basically the same?

For others who are actively seeking a solution, place a line of `if (event.type === "change")` in front of your `onChange` logic should suffice:
```ts
<TextField
  ...
  onChange={this._onChange}
  ...
/>

_onChange = (
  event: React.FormEvent<HTMLInputElement | HTMLTextAreaElement>,
  value: string | undefined
) => {
  if (event.type === "change") {
    //...HERE COMES YOUR CODE...
  }
}
```
A visually cleaner solution would be wrapping `TextField` with your own component (say `MyTextField`) where the custom _onChange method is placed within. Unfortunately this is just a workaround, where one of the doubly fired events is ignored so only one event is received on your end. Hopefully this can be of any help @zhongyn @pitric.
