### ISSUE TITLE
ResizeGroup throws TypeError: lib.b.getInstance(...).onReset is not a function

### ISSUE THREAD

**Issue by pmcgannon22** [OfficeDev/office-ui-fabric-react#9531]
### Bug Report

- __Package version(s)__: @uifabric/utilities v6.41.2
- __Browser and OS versions__: all

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? Yes

Requested priority: Potentially High. We can use an older package, but this may be affecting others.

#### Describe the issue:

TypeError: lib.b.getInstance(...).onReset is not a function

Above error is thrown when ResizeGroup is being used. It does not happen every time. Still am working on why it happens in certain circumstances.

It seems likely that the precautionary change from this [this pull request](https://github.com/OfficeDev/office-ui-fabric-react/pull/5253/files/f6f05f1a10df911a1dd579cc83aaf00eef236298#diff-45d78b91d1d9caa41185567f7ea32fb4) needs to be applied to [this change.](https://github.com/OfficeDev/office-ui-fabric-react/commit/cc3ff2379bd7df5fa55800f97ec83d2242d9a11e#diff-f54ad9f9382abc55381380772310f361)

**Comment by aftab-hassan** [comment]
@pmcgannon22, thanks for raising your first issue, and willing to contribute. 

Would you mind providing a stable `repro` as part of your pull request for this issue ?

We'd be happy to have it reviewed by one of the `codeowners`.

Here are some Contributing guidelines to get you started: https://github.com/OfficeDev/office-ui-fabric-react/wiki/Contributing

**Comment by aftab-hassan** [comment]
@pmcgannon22, there is a new release of `@uifabric/utilities v6.41.3` where the issue you reported should be handled. 

Could you try upgrading to the newest release and let us know if you are still facing issues ? https://github.com/OfficeDev/office-ui-fabric-react/releases/tag/@uifabric/utilities_v6.41.3
