### ISSUE TITLE
Clean up Contextual Menu examples

### ISSUE THREAD

**Issue by aftab-hassan** [OfficeDev/office-ui-fabric-react#9535]
Examples in ContextualMenu. possibly other components as well, can benefit from cleanup.

Specifically, I see

1. Unused state variables, like for example, [this](https://github.com/OfficeDev/office-ui-fabric-react/blob/659b57cc432a37173324eb06f22ea7a918ecff36/packages/office-ui-fabric-react/src/components/ContextualMenu/examples/ContextualMenu.Basic.Example.tsx#L10) one
2. Unnecessary class components
3. Unused css class names

**Comment by cliffkoh** [comment]
cc @ecraig12345 @joschect

**Comment by ecraig12345** [comment]
Aftab talked to me about this and said he was planning on working on it.
