### ISSUE TITLE
Office fabric Modal component - Call out the text in ariaLabel when popup opened

### ISSUE THREAD

**Issue by PavanJagini** [OfficeDev/office-ui-fabric-react#9543]
## Actual behavior:
Office Fabric Modal does not callout the text given in ariaLabel when popup is opened

## Expected behavior:
Office Fabric Modal should callout the text given in ariaLabel when popup is opened.
- Our project Bug reference for understanding:  
_(removed)_
- Issue identified in tools:  Keros, NVDA

**Comment by aftab-hassan** [comment]
@PavanJagini thank you for posting an issue. 

I followed the steps in the work item you linked to. However, I wasn't able to reproduce the issue since I don't have anything under _Pending Actions_.

Could you kindly provide us a codepen so we can better understand the issue ?

Also, I have made a note of the `PBI` you have open for this (and stays on GitHub comment history as well). We recommend not posting internal links, being a public repository. Editing the original 
comment.

**Comment by PavanJagini** [comment]
Sure, will get back to you with the details in sometime

**Comment by aftab-hassan** [comment]
> Sure, will get back to you with the details in sometime

Sounds good, thank you!

**Comment by aftab-hassan** [comment]
@PavanJagini  and I spoke offline. The request is to be able to have the screen reader read out a string such as "Justification popup opened" passed in as a prop to `Modal`, upon opening the `Modal`. 

Thank you for walking me through the desired behavior. We are looking in to this.

**Comment by aftab-hassan** [comment]
@PavanJagini, we discussed this within the team, and feel that the `Modal` announcing a custom string is not a supported use case, and also not uniform with the rest of the components. 

Instead, we recommend using the `Announced` component and embedding the announcement, as part of the inner content of the `Modal`. Here is the link to the documentation for `Announced` component.   https://developer.microsoft.com/en-us/fabric#/controls/web/announced

@cschlechty, thanks for the discussion, and if you had anything to add, please feel free.

**Comment by cschlechty** [comment]
When AT encounters changes of context, like modals it'll often announce the entire contents of the modal region, similar to a fresh page navigation. Given this behavior and the ARIA standard, adding additional announcing would likely be a regressions. In your modal, are you shifting focus to it? If it is truly transient and doesn't require action, it should be some control other than modal (not taking focus) which acts as an alert/announced thing.

**Comment by PavanJagini** [comment]
- Hey @aftab-hassan & @cschlechty , Thanks a lot for your inputs. I shall try the options suggested by you and try to fix the issue.

- Coming to your point @cschlechty, the reason for going to modal box/ popup is to show the comments to admin which will have users explanation requesting why the user needs access to the application. Max length of this input is around 600 chars. Hence we had to opt for the modal box. 
Admin would open, read and close the popup and move with his action by rejecting or approving the user request. 
And as you suggested, I shall try moving the focus to the popup and check by having div with aria-label. Hope that works. I will update here once tried.
Once again, thanks a lot to both of you for jumping in and assisting me.

**Comment by aftab-hassan** [comment]
@PavanJagini , thank you and let us know how it goes.

**Comment by PavanJagini** [comment]
@aftab-hassan , Thanks for waiting. With tabindex as 1 and aria-label added to the popup heading content div, upon open of the div, screen reader readout mentioning the content.

**tabIndex="1" aria-label="Justification popup opened"**
