### ISSUE TITLE
Persona component displaying blank images

### ISSUE THREAD

**Issue by lalena205** [OfficeDev/office-ui-fabric-react#9556]
### Environment Information 
 
- __Package version(s)__: 7.4.3
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
 
We ( https://to-do.microsoft.com ) are trying to use Persona component for displaying members of a shared list. These are all users with an exchange mailbox. The avatar URL is set on the Service side, and it seems that it sometimes providing broken links (users have no avatar set) . Plaese check the attached video
[PersonaBug.mov.zip](https://github.com/OfficeDev/office-ui-fabric-react/files/3320766/PersonaBug.mov.zip)

https://codepen.io/lalena205/pen/RzgPqE

 
#### Actual behavior:
 
Loading a Persona with a broken or pointing-to-none imageUrl is displaying blank avatar
 
#### Expected behavior:

Loading a Persona with a broken or pointing-to-none imageUrl will display initials or a default image *or* there is an available callback that I can use to check the loaded image

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) *YES*
 
Requested priority: (Blocking, High, Normal, Low)  *HIGH*
 
Products/sites affected: (if applicable)
https://to-do.microsoft.com

**Comment by micahgodbolt** [comment]
I did a quick reduced test case (your example won't work in codepen as is). The persona is working properly if you pass in an invalid image URL

https://codepen.io/micahgodbolt/pen/dBRNxy?editors=0010

![image](https://user-images.githubusercontent.com/1434956/60033878-47f76a80-965e-11e9-939b-fc645d8882ee.png)


We'd be happy to try and figure out what's going wrong, but I don't believe it is the persona's logic when passed a bad image URL.

**Comment by KevinTCoughlin** [comment]
Thanks @micahgodbolt. To add to the above, the relevant LoC is: https://github.com/OfficeDev/office-ui-fabric-react/blob/cceec3b0ad44e2a5d47db0b55c6ca898c6413235/packages/office-ui-fabric-react/src/components/Persona/PersonaCoin/PersonaCoin.base.tsx#L96

**Comment by lalena205** [comment]
Sorry, my bad in having investigated better & reporting proper repro steps. It seems that the url is not broken,  as you can see by checking this one (this is one of the failing ones)
https://storage.live.com/users/0x1EAA72BE25A4BBE5/myprofile/expressionprofile/profilephoto:UserTileMedium/avatar?ck=1&ex=1&fofoff=1
What happens is that it resolves by returning a 1x1 gif. Making a HEAD request previously and checking the content-length does no work since the response is `type: opaque` . What would help is either a check o your side or maybe exposing (some of) the props of the image before rendering it.

**Comment by Markionium** [comment]
In LPC (LivePeopleCard) we have the same problem with the 1x1 picture. We have written some logic around the Persona that checks if the image is 1x1 in size and not pass in the URL.

We basically load the image in an off screen `Image` and onload check if it is a 1x1 image. If not we set the imageUrl on the `<Persona />`.

I think that this is more of an issue of strange behaviour by the image endpoint. I don't think we should put logic like this in the Fabric Persona coin to compensate for such cases. 

Ideally the resource where you try to get the photo should return a 404 if the photo can not be found. It should not return a 1x1 picture if there is no image for that person.

Feel free to reach out on Teams (my alias is `mapol`) if you need more context

**Comment by micahgodbolt** [comment]
Thanks @Markionium, I agree that it's odd how instead of a 404 you're getting a valid 1x1 image. Sounds like the solution for now is to validate that you have an actual image before setting that image URL on the persona.
