### ISSUE TITLE
GroupedList : 'Show All' does not work

### ISSUE THREAD

**Issue by dliu120** [OfficeDev/office-ui-fabric-react#9561]
### Environment Information 
 
- __Package version(s)__: 6.187.0

### Please provide a reproduction of the bug in a codepen:

'Show All' does not appear to work for GroupedList
https://codepen.io/anon/pen/gNmKWJ?editors=0010
 
#### Actual behavior:
 
Clicking 'Show All' does not expand the list.
 
#### Expected behavior:
 
It should expand the list

#### Priorities and help requested:
 
Are you willing to submit a PR to fix?

No
 
Requested priority:

Normal

**Comment by KevinTCoughlin** [comment]
Hrmm thanks for the report @dliu120, this should most definitely work. We'll take a look and circle-back.
