### ISSUE TITLE
Announced - Quick Actions demo does not read for consecutive renames/deletes

### ISSUE THREAD

**Issue by efrack** [OfficeDev/office-ui-fabric-react#9562]
## Codepen demonstrating the issue
The demo on:
https://developer.microsoft.com/en-us/fabric#/controls/web/announced/quickactions

## Actual behavior:
Narrator reads the first delete/rename action in a row and does not read anything if the same action type is repeated consecutively, even after long waits.

## Expected behavior:
If the user deletes multiple times in a row, it would announce each delete.  The Announced control and/or demo should reflect this behavior and not drop announcements (perhaps by resetting the message on a timer?).

**Comment by KevinTCoughlin** [comment]
@natalieethell, seeking your guidance regarding the above issue -- thank you!

**Comment by natalieethell** [comment]
@efrack thanks for opening this issue! This is definitely a bug and your suggestion to reset the message seems like the best move. I'll work on something today/tomorrow!
