### ISSUE TITLE
latest version on npm is 5.135.1

### ISSUE THREAD

**Issue by MarcOne68** [OfficeDev/office-ui-fabric-react#9567]
HI, why the latest version on npm is 5.135.1 ?

**Comment by KevinTCoughlin** [comment]
> HI, why the latest version on npm is 5.135.1 ?

@MarcOne68 I see latest on NPM listed as `7.5.2`:

![image](https://user-images.githubusercontent.com/706967/60115231-56ab5380-972a-11e9-964c-92e9904730aa.png)

https://www.npmjs.com/package/office-ui-fabric-react

**Comment by Toonshorty** [comment]
@KevinTCoughlin I can vouch that when I checked yesterday the latest version was 5.135.1, this had overwritten the 7.5.1 release as the latest. It looks like the 7.5.2 release has resolved this though.

**Comment by KevinTCoughlin** [comment]
As always we appreciate the report and will keep an eye out. I'm not sure what happened there. I'm going to close since this seems to be resolved from our end.
