### ISSUE TITLE
[Panel] Header text doesn't gracefully handle long texts with no spaces

### ISSUE THREAD

**Issue by riosn-n** [OfficeDev/office-ui-fabric-react#9576]
### Environment Information 
 
- __Package version(s)__: (7.5.2) 

### Please provide a reproduction of the bug in a codepen:
 
https://codepen.io/anon/pen/PrKaje
 
#### Actual behavior:
 
Scrollbar appears.
 
#### Expected behavior:
 
Title is broken into multiple lines.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes)
 
Requested priority: (Normal) 
 
Products/sites affected: (if applicable)
 
PowerApps, Dynamics CRM

Possible fix:

Adding this set of styles to headerText in Panel.styles solves the problem:

        overflowWrap: 'break-word',
        wordWrap: 'break-word',
        wordBreak: 'break-word',
        hyphens: 'auto'

**Comment by KevinTCoughlin** [comment]
Thanks for your report @riosn-n! I think your ask can be supported using styles for the header element. I will attempt to do that and provide an example to you. Then we can consider if those styles should be default behavior or better documented.

**Comment by KevinTCoughlin** [comment]
Oh I just fully read your report where you note that this is possible i.e. https://codepen.io/kevintcoughlin/pen/XLaPVO.

Can you clarify your ask @riosn-n? Is it that these styles be the default for `headerText`?

That seems reasonable, but I'd have to check with @kkjeer if there are any cases where that would break existing partners.

**Comment by riosn-n** [comment]
Thanks, @KevinTCoughlin. As you mentioned, styling the header element eliminates the problem. See above the list of style rules I'm using to fix it. The reason for opening this issue is not to unblock myself, but to call out that the Panel doesn't behave the same when there are spaces and when there are no spaces in a long title. IMO we should consider adding those styles by default.

**Comment by KevinTCoughlin** [comment]
@kkjeer do you know if the handling of long text with and without spaces is intentional? Should we normalize the behavior to overflow ellipsis as suggested by @riosn-n?

We can discuss offline if need be.

**Comment by KevinTCoughlin** [comment]
Started a thread, let's see what the conclusion is. I'm in favor of adding the styles by default. The justification makes sense.
