### ISSUE TITLE
document Panel - Navigation example bug

### ISSUE THREAD

**Issue by x73x63** [OfficeDev/office-ui-fabric-react#9581]
### Environment Information 
 
- __Package version(s)__: 7.5.2
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:

1. Copy Panel - Navigation code to PanelNavigationExample.tsx

2. import use PanelNavigationExample component

3. Failed to compile

 Type '(props: IPanelProps, defaultRender: IRenderFunction<IPanelProps>) => Element' is not assignable to type 'IRenderFunction<IPanelProps>'.
  Types of parameters 'props' and 'props' are incompatible.
    Type 'IPanelProps | undefined' is not assignable to type 'IPanelProps'.
      Type 'undefined' is not assignable to type 'IPanelProps'.  TS2322

**Comment by KevinTCoughlin** [comment]
Thanks for your report @x73x63. Do you mind sharing what version of TypeScript you were using when you saw the above compiler error?

**Comment by x73x63** [comment]
Thank you for your help, Has nothing to do with TypeScript vsrsion, The problem is compiler-options.

create-react-app --typescript default tsconfig.json
`{"strict": true,}`

strict": true //Failed to compile

strict": false //OK

**Comment by x73x63** [comment]
strictFunctionTypes": true  //Enable strict checking of function types.  Failed to compile

**Comment by KevinTCoughlin** [comment]
> strictFunctionTypes": true //Enable strict checking of function types. Failed to compile

Thank you, that is useful information as part of the issue report :). I will discuss with the team and get back to you soonest.

**Comment by KevinTCoughlin** [comment]
```diff
diff --git a/packages/office-ui-fabric-react/src/components/Panel/examples/Panel.Navigation.Example.tsx b/packages/office-ui-fabric-react/src/components/Panel/examples/Panel.Navigation.Example.tsx
index b377021d0..681883b20 100644
--- a/packages/office-ui-fabric-react/src/components/Panel/examples/Panel.Navigation.Example.tsx
+++ b/packages/office-ui-fabric-react/src/components/Panel/examples/Panel.Navigation.Example.tsx
@@ -39,7 +39,7 @@ export class PanelNavigationExample extends React.Component<
     this.setState({ showPanel: false });
   };
 
-  private _onRenderNavigationContent = (props: IPanelProps, defaultRender: IRenderFunction<IPanelProps>): JSX.Element => {
+  private _onRenderNavigationContent = (props?: IPanelProps, defaultRender?: IRenderFunction<IPanelProps>): JSX.Element => {
     const theme = getTheme();
 
     return (
@@ -106,7 +106,7 @@ export class PanelNavigationExample extends React.Component<
             iconName: 'MoreVertical'
           }}
         />
-        {defaultRender(props)}
+        {defaultRender!(props)}
       </React.Fragment>
     );
   };
```

The quick "fix" for this issue is more or less the above, tho we should prefer to guard rather than use a non-null assertion.

My concern with the above patch is that this is an issue with the underlying typing of `IRenderFunction<P>`. The incompatibility with `strictFunctionTypes` with respect to `IRenderFunction<P>` spans the codebase and should be fixed wholesale if at all.

@JasonGore @ecraig12345 do either of you have opinions here?

**Comment by x73x63** [comment]
I found other components example code also have similar problems.

Enable all strict type checking options.  test all example code.

**Comment by joschect** [comment]
@x73x63 I've submitted a fix for the problem with Panel Navigation Example, I've also made an issue that's just focused on enabling strict type checking, we'll discuss it there and decide where to go next. #10226
