### ISSUE TITLE
[Narrator] Can't invoke DetailsList items in scan mode

### ISSUE THREAD

**Issue by cnamal** [OfficeDev/office-ui-fabric-react#9582]
Go to https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist
Start Narrator
Tab until you get to the first item _Lorem ipsum.accdb_
Hit Enter-> alert is opened saying `Item invoked: Lorem ipsum.accdb`
Hit Enter to close the dialog
Start Scan Mode
Hit Enter
**Expected:** alert is opened like in normal mode
**Actual:** nothing happens

**Comment by KevinTCoughlin** [comment]
I'm unsure that all interactive behaviors need to be exposed when Narrator is in scan mode as the primary use-case (my understanding) of scan mode is to discover elements within a page. We have a thread offline discussing on where the line is w.r.t scan mode. I will reply once we have resolution on the thread.
