### ISSUE TITLE
Can't have placeholder with a multiline TextField

### ISSUE THREAD

**Issue by rcasto** [OfficeDev/office-ui-fabric-react#9588]
### Environment Information 
 
- __Package version(s)__: 6.190.0
- __Browser and OS versions__: Chrome

### Please provide a reproduction of the bug in a codepen:
https://codepen.io/anon/pen/BgwVMO?&editable=true
 
#### Actual behavior:
 It appears a multiline TextField cannot have a placeholder
 
#### Expected behavior:
A multiline TextField should render with a placeholder, if specified.

#### Priorities and help requested:

Are you willing to submit a PR to fix? No, not as familiar with code at the moment
 
Requested priority: Normal
 
Products/sites affected: Virtual Agent Designer

**Comment by KevinTCoughlin** [comment]
This seems like a reasonable request. @ecraig12345 do you have any concerns regarding the above before I work on an implementation?

**Comment by ecraig12345** [comment]
The placeholder is just a native prop which we pass through to the `<input>` or `<textarea>`, but apparently for `<textarea>` (multiline) it [should be supported](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea) but isn't getting passed through because `placeholder` is missing from `textAreaProperties` in `packages/utilities/src/properties.ts`. (Thanks @rcasto for including a codepen to make this easy to debug!)

**Comment by rcasto** [comment]
Just curious, would this fix get ported to a 6.x.x package release? Not sure exactly how that works

**Comment by ecraig12345** [comment]
Thanks so much for fixing this! Porting doesn't happen automatically, someone has to cherry-pick the change into a branch based on the `6.0` branch, then make a PR into `6.0`. If you don't mind porting the change, that would be great! Otherwise @KevinTCoughlin or I can do it.

**Comment by ecraig12345** [comment]
I'll reopen this until the port is done.

**Comment by rcasto** [comment]
Went ahead and tried my hand at porting to the `6.0` branch

**Comment by KevinTCoughlin** [comment]
This issue can be closed now that the port to `6.x` was completed in https://github.com/OfficeDev/office-ui-fabric-react/pull/9609.
