### ISSUE TITLE
ScrollablePane-Accessibility: Narrator can't read the Sticky headers in Scan Mode

### ISSUE THREAD

**Issue by HalcyonPride** [OfficeDev/office-ui-fabric-react#9597]
## Codepen demonstrating the issue
https://developer.microsoft.com/en-us/fabric#/controls/web/scrollablepane
See Default example under 'Usage'.

## Actual behavior:
In Scan Mode, Narrator skips the header and reads the content immediately instead.

## Expected behavior:
In Scan Mode, Narrator reads the header and then the content.

## Documentation describing expected behavior
The actual non-Sticky headers don't render until they're visible in the Pane... that's why Narrator can't read them unless the user has scrolled up/down.

![image](https://user-images.githubusercontent.com/8681794/60219795-c0118c00-9828-11e9-97d1-a1d1ac6188b2.png)

**Comment by KevinTCoughlin** [comment]
Seems like a legitimate accessibility issue. I will need to dig and see what would be involved to fix cc: @tharshada.

Will get back to you on this soonest.

**Comment by micahgodbolt** [comment]
@KevinTCoughlin i was going to take a look at this issue. Do you (or @leddie24 ) have any context here?

**Comment by micahgodbolt** [comment]
Talked to @Jahnp and @leddie24, and they think they have a good solution for this. Eddie is going to quick prototype to validate the idea, then I offered to do full integration and get the PR over the line.
