### ISSUE TITLE
Fabric UI DetailsList should allow me to change circle check boxes to square check boxes

### ISSUE THREAD

**Issue by jaimereyesmx** [OfficeDev/office-ui-fabric-react#9598]
**Describe the feature that you would like added**
I can't easily change circle check boxes in a Detailslist to be square check boxes.

**What component or utility would this be added to**
DetailsList

**Have you discussed this feature with our team, and if so, who**
First time reporting this issue, didn't find any documentation on how to change the circle check boxes

**Additional context/screenshots**
![image](https://user-images.githubusercontent.com/12244548/60222790-7ed2a980-9833-11e9-9622-c6afa6ed1fde.png)

**Comment by KevinTCoughlin** [comment]
Hey @jaimereyesmx, thank you for raising this issue. IIRC there is a way to customize the checkbox in the way that you desire, but it is a bit involved. I will try to put together an example and get back to you. If it works we should document it.

One of the issues is selection behavior needs to be handled if not using the default check render, but I think that is solvable last we tried this.

**Comment by jaimereyesmx** [comment]
Hi @KevinTCoughlin,

I was wondering if you were able to come up with an example to customize the checkbox.

**Comment by KevinTCoughlin** [comment]
> Hi @KevinTCoughlin,
> 
> I was wondering if you were able to come up with an example to customize the checkbox.

@jaimereyesmx, does the following Codepen work for you as a sample?

https://codepen.io/kevintcoughlin/pen/LKKMdG?editors=1010

It is overriding the render method for the _default_ `DetailsList` checkbox to render a native `<input type="checkbox" />`. You should be able to achieve what you want using `onRenderCheckbox`.

https://github.com/OfficeDev/office-ui-fabric-react/blob/167f840c525153e587c2712d7bdda767ceb30645/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.types.ts#L216

**Comment by jaimereyesmx** [comment]
Thank you @KevinTCoughlin! I was able to render the square check boxes.

**Comment by KevinTCoughlin** [comment]
> Thank you @KevinTCoughlin! I was able to render the square check boxes.

Glad to hear! I'm going to close this issue as resolved.
