### ISSUE TITLE
Expose onKeyDown for Dialogs

### ISSUE THREAD

**Issue by SavannahBourgeois** [OfficeDev/office-ui-fabric-react#9615]
**Describe the feature that you would like added**
It would be great if you could expose onKeyDown from the dialog props so we could listen to keydown events on the dialog.

**What component or utility would this be added to**
Dialog

**Have you discussed this feature with our team, and if so, who**
nope

**Additional context/screenshots**

**Comment by KevinTCoughlin** [comment]
@kkjeer thoughts on the above feature request before I approach implementation?

**Comment by KevinTCoughlin** [comment]
@SavannahBourgeois would you mind explaining the use case a bit further before we make the change to support? We can follow-up offline if you wish.

**Comment by SavannahBourgeois** [comment]
Thanks Kevin. I started thinking about this more and I am going to close this out because I don't think we want it. Initially I was trying to implement behavior where hitting "enter" when focused on dialog content would execute a default button. It turns out I only want the onKeyDown listener on the dialog content (I need to exclude the button area) so I don't think my request makes sense any more. Thanks1

**Comment by KevinTCoughlin** [comment]
No worries, I'm glad you an agreeable solution and are unblocked!
