### ISSUE TITLE
Overlay component IOverlayProps interface add onOverlayDidMount and onOverlayWillUnmount properties

### ISSUE THREAD

**Issue by x73x63** [OfficeDev/office-ui-fabric-react#9631]
**Describe the feature that you would like added**
IOverlayProps interface add onOverlayDidMount and onOverlayWillUnmount properties

**What component or utility would this be added to**
Allow parent component setting whether to hide the scroll bar

**Have you discussed this feature with our team, and if so, who**

**Additional context/screenshots**

**Comment by khmakoto** [comment]
Hi @x73x63, thanks for filing the issue!

@kkjeer this seems like an easy fix that I could tackle, but I wanted to ask you, as the code owner for `Overlay`, if you think it makes sense to add these properties?

**Comment by kkjeer** [comment]
@khmakoto these seem like reasonable properties to add!

**Comment by khmakoto** [comment]
@x73x63 Do you think Kevin's approach in #9670 might work for you?

**Comment by khmakoto** [comment]
I'll close this in favor of #9784 given that it more specifically describes the problem that we're trying to solve.
