### ISSUE TITLE
IPanelProps interface add overlayProps properties

### ISSUE THREAD

**Issue by x73x63** [OfficeDev/office-ui-fabric-react#9632]
**Describe the feature that you would like added**
IPanelProps interface add overlayProps properties

**What component or utility would this be added to**
Optional props to pass to the Overlay component hosting the panel.

**Have you discussed this feature with our team, and if so, who**

**Additional context/screenshots**

**Comment by khmakoto** [comment]
Thank you for filing the issue @x73x63! This seems to be related to your recent issue #9631.

@kkjeer, same as with the other issue, just want to confirm if this is something we want to do before moving forward on making the fix.

**Comment by kkjeer** [comment]
@khmakoto makes sense to me; this seems similar to Panel's existing `focusTrapZoneProps` and `layerProps`.
