### ISSUE TITLE
Buttons styling not using corresponding semanticColors

### ISSUE THREAD

**Issue by rhublard** [OfficeDev/office-ui-fabric-react#9636]
### Environment Information 

- __Package version(s)__: 7.6.2

### Please provide a reproduction of the bug in a codepen:
 
Here's an example in [Codepen ](https://codesandbox.io/s/button-styling-4v24g) with some attempt to underline what is updating the button styles and what is not. (I apologize for the choices of colors, I tried to make it relevant)

https://codesandbox.io/s/button-styling-4v24g 

#### Actual behavior:

We are looking to update the styles of our buttons globally by editing the theme. We noticed that what we thought were used to update the button elements colors (i.e. any `semanticsColors ` value with `button` in its name) were not. For example, the default button background color is directly using `palette.white` instead of `semanticColors.buttonBackground`.

A few are used like `semanticColors.buttonText`.

#### Expected behavior:
 
Should the button styles use the specific semanticColors value like `buttonBackground` or is there something we are doing wrong? 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority:  Normal
 
Thank you

**Comment by khmakoto** [comment]
Hi @rhublard! Thanks for filing this issue! There is indeed a lot of `palette` colors used on the `Button` component that should be updated to use `semanticColors`. I'll make a PR shortly to solve this issue.

**Comment by khmakoto** [comment]
Hi @rhublard, I've started a PR on this that alleviates some of the issues. However, we are currently on an ongoing effort to overhaul our `semanticSlots` usage tracked in #9431. Until that gets finalized I'm afraid what I'm doing on my PR is probably the closest we'll get to having the correct set of `semanticColors` in the `Button` component.

**Comment by rhublard** [comment]
Hi @khmakoto, thank you for the quick fix! We will wait for your PR to be done then and look back at this when semantic slots overhaul is finalized.
