### ISSUE TITLE
[Accessibility][Screen-reader]: Narrator reading irrelevant information when user expand dropdown on panel.

### ISSUE THREAD

**Issue by v-hegoel** [OfficeDev/office-ui-fabric-react#9637]
## Codepen demonstrating the issue
<https://codepen.io/anon/pen/RzMWxV>

## Actual behavior:
Narrator reading irrelevant information when user expand dropdown on panel, which create confusion for screen reader user. 
## Expected behavior:
Narrator should read relevant information when user expand dropdown on panel.

**Comment by khmakoto** [comment]
Hi @v-hegoel! Can you provide more information on the issue you are encountering such as what irrelevant information is being said by the screenreader? When I try your codepen I don't hear any irrelevant information when expanding the `Dropdown` component.

This is what I hear: `"Select one, select 1, one of two, selected"`

**Comment by v-hegoel** [comment]
Hi **@khmakoto** when pressing the enter key on the dropdown. Then narrator read: page details, browser details, dropdown details.

**Comment by khmakoto** [comment]
Hi @v-hegoel, after following your steps I can confirm that this is indeed what's happening. I'll investigate to see if it's a bug on our side, Narrator or Edge. Thanks again!

**Comment by khmakoto** [comment]
Just wanted to give an update here that I'm still waiting for a response from the Narrator team regarding this issue.

**Comment by khmakoto** [comment]
Hi, I just got a response this morning indicating that there are bugs filed for this in both Narrator's and Edge's sides which are causing Narrator to identify a context change in this type of scenarios. I'll be resolving this as an external issue given the circumstances.
