### ISSUE TITLE
DetailsList: Better auto-sizing for columns

### ISSUE THREAD

**Issue by cc0rk** [OfficeDev/office-ui-fabric-react#9643]
**Describe the feature that you would like added**
It'd be great if we could somehow specify that all columns should, by default, be given equal widths unless manually overridden. I know we can set the max-width to a specific number of  pixels, but it'd be nice to have all the columns dynamically sized so that they fill the entire width of the table AND retain that ratio when the viewport is resized. 

There's a link below that shows the existing behavior vs desired behavior. 

**What component or utility would this be added to**
Detailslist
**Additional context/screenshots**
Code sandbox containing 3 datagrids: [Link to sandbox](https://codesandbox.io/embed/react-table-vs-detailslist-1z582)
- DetailsList with justified columns: no matter what I do, the first column is always enormous, and it's the only one that changes size when I resize the viewport. That's...weird. 
- DetailsList with fixed columns: Is there a way to make the columns fill the width of the table? 
- React Table: This is a non-fabric component that dynamically resizes all the columns when the viewport size changes. The columns are also all given equal space and fully extend the width of the table. If a column width is manually changed, it retains that width when the viewport is resized.

**Comment by khmakoto** [comment]
Hi @cc0rk! Thanks for bringing this up! This seems like it would require a substantial amount of work in order to be supported in the way you want. @micahgodbolt and @KevinTCoughlin, what are your thoughts on this? To me it seems like it is probably a backlog item given the engineering effort involved.

**Comment by micahgodbolt** [comment]
Yeah, nice feature for sure.

**Comment by KevinTCoughlin** [comment]
I've spoken with @ThomasMichon as part of #9457 and later #9646 about our various layout modes. There likely is room for an additional layout mode which overflows horizontally and does not try to best-fit. There is probably room for a best-fit layout algorithm as you requested above. The task is doable, but not a priority given our specific scenarios (fixed and justified) across OneDrive and SharePoint.

If you wish to propose a design and later an implementation, we would be happy to review both. The majority of work will likely be in the column size calculations. Example:

https://github.com/OfficeDev/office-ui-fabric-react/blame/bcd515ea9fe6b1a3bb6e69d468a105da172fadf6/packages/office-ui-fabric-react/src/components/DetailsList/DetailsList.base.tsx#L819

**Comment by thoo1** [comment]
kind of a related question.. I notice that when you double click the header column resizers, it resizes the column to fit the content, is there a way to make programmatically do this behaviour? Tried looking through the documentation but didn't find anything :(
