### ISSUE TITLE
Text Field: error message shows for valid default values

### ISSUE THREAD

**Issue by beccaroskill** [OfficeDev/office-ui-fabric-react#9644]
### Bug Report

- __Package version(s)__: 6.189.4
- __Browser and OS versions__: Chrome on Windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (No)

Requested priority: (Low) 

#### Describe the issue:

When using the defaultValue and errorMessage props together, an error message is displayed for a valid defaultValue.

#### Actual behavior:

If defaultValue is valid according to the definition of errorMessage, an error message is still displayed under the text field.

#### Expected behavior:

If defaultValue is valid according to the definition of errorMessage, no error message should be displayed under the text field.

**Comment by beccaroskill** [comment]
Meant to refer to onGetErrorMessage rather than errorMessage

**Comment by khmakoto** [comment]
Hi @beccaroskill! Thank you for letting us know about this issue! Can you provide a reproduction of the bug? I tried reproing it in [this codepen](https://codepen.io/khmakoto/pen/NZMwmM?editors=0010) but I find that the error message is not displayed if the default value is valid according to its definition.
