### ISSUE TITLE
Primary button on click on mobile device is making the flyout to toggle in Split Button

### ISSUE THREAD

**Issue by adityapelluri** [OfficeDev/office-ui-fabric-react#9653]
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen:
 
https://developer.microsoft.com/en-us/fabric/#/controls/web/button#feedback
 
#### Actual behavior:
 
I tried to use the split button using an iPad. When i clicked on the primary button, it is toggling the flyout button  
 
#### Expected behavior:
 
 It should perform the onClick action of the primary button. but currently the onClick action is only executed by clicking and holding the primary button for more than a second. 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (No)
 
Requested priority: (High) 
 
Products/sites affected: (if applicable)

**Comment by adityapelluri** [comment]
issue only reproduces on a touch device. Browser works fine

**Comment by khmakoto** [comment]
Hi @adityapelluri! I can confirm I was able to repro this issue when trying your scenario on my phone. I'll work on getting a fix as soon as possible. Thanks!

**Comment by adityapelluri** [comment]
@khmakoto  Thank you for the response

**Comment by adityapelluri** [comment]
@khmakoto  Is there any update regarding the fix of this ?

**Comment by khmakoto** [comment]
I'm still investigating the issue. Still don't know why this is happening only on touch devices.

**Comment by adityapelluri** [comment]
Hi   @khmakoto  , sorry about getting back on this again. Any info about the fix yet?

**Comment by adityapelluri** [comment]
@khmakoto any update regarding the fix ?

**Comment by adityapelluri** [comment]
@dzearing can you help in here please

**Comment by dzearing** [comment]
This is by design on touch entries.

@jspurlin can provide background, but ultimately it's because:

1. The split menu should have all options available including the primary action;
2. The touch target is not large enough to only execute the menu, so to resolve the ambiguity all split buttons react to touch this way (act as a menu button.)

**Comment by adityapelluri** [comment]
@dzearing do we have any workaround or override the functionality by declaring any additional inputs ?

**Comment by khmakoto** [comment]
@adityapelluri I don't think we offer any workaround unfortunately.
