### ISSUE TITLE
[Accessibility][Breadcrumb-Screen reader]:  'More option button' must have discernible text.

### ISSUE THREAD

**Issue by v-doku** [OfficeDev/office-ui-fabric-react#9657]
[Accessibility][Breadcrumb-Screen reader]:  'More option button' must have discernible text.

Detailed description of this issue can be found here [SharePoint](https://microsoft-my.sharepoint.com/:x:/r/personal/v-amaver_microsoft_com/Documents/Fabric%20Control/Fabric%20Controls%202nd%20Phase/BreadCrumb/Fabric%20Control%20Bugs-Breadcumb.xlsx?d=w7b84a10d785d48448bac4e46e0610420&csf=1&e=EbZe3s)

**Comment by khmakoto** [comment]
Hi @v-doku, I can confirm that this is indeed an issue and will be working towards getting a fix soon. Thanks!
