### ISSUE TITLE
[Accessibility] Details list div has empty role

### ISSUE THREAD

**Issue by satishkumaarponnusamy** [OfficeDev/office-ui-fabric-react#966]
Hi,

DetailsList adds empty role which is invalid, refer to [Aria role](https://dequeuniversity.com/rules/axe/2.1/aria-roles)

You can inspect it in [detailslist](http://dev.office.com/fabric#/components/detailslist)
```
<div class="ms-DetailsList is-horizontalConstrained" data-automationid="DetailsList" data-is-scrollable="false" role="" data-reactid=".0.1.3.0.0.1.0.1.2.1.0.2.0.2.0.0">...</div>
```

Thanks,
Satish

**Comment by sandeepchads** [comment]
+1 Just checking whether we have an ETA for this bug closure?

**Comment by dzearing** [comment]
Is the empty role causing some sort of problem?

**Comment by dzearing** [comment]
This has been addressed in this PR and will be published shortly.
https://github.com/OfficeDev/office-ui-fabric-react/commit/10920866c206c4e3e8045db3c2b076a2ae213cdd
