### ISSUE TITLE
 Remove the dependency on React library for @uifabric/icons

### ISSUE THREAD

**Issue by fhljys** [OfficeDev/office-ui-fabric-react#9660]
I just want to use uifabric/icons library and I am not a React APP. There is an API named getIconClassName in '@uifabric/styling'. I can use it and I can render the icon successfully. 
But to use it, I have to install React library as well. 
Otherwise, build will fail with:

ERROR in ./node_modules/@uifabric/utilities/lib/styled.js
Module not found: Error: Can't resolve 'react' in 'D:\DataIntegrationApp\Product\node_modules\@uifabric\utilities\lib'
ERROR in ./node_modules/@uifabric/utilities/lib/asAsync.js
Module not found: Error: Can't resolve 'react' in 'D:\DataIntegrationApp\Product\node_modules\@uifabric\utilities\lib'
ERROR in ./node_modules/@uifabric/utilities/lib/DelayedRender.js
Module not found: Error: Can't resolve 'react' in 'D:\DataIntegrationApp\Product\node_modules\@uifabric\utilities\lib'
ERROR in ./node_modules/@uifabric/utilities/lib/BaseComponent.js
Module not found: Error: Can't resolve 'react' in 'D:\DataIntegrationApp\Product\node_modules\@uifabric\utilities\lib'
ERROR in ./node_modules/@uifabric/utilities/lib/customizations/customizable.js
Module not found: Error: Can't resolve 'react' in 'D:\DataIntegrationApp\Product\node_modules\@uifabric\utilities\lib\customizations'
ERROR in ./node_modules/@uifabric/utilities/lib/customizations/CustomizerContext.js
Module not found: Error: Can't resolve 'react' in 'D:\DataIntegrationApp\Product\node_modules\@uifabric\utilities\lib\customizations'
ERROR in ./node_modules/@uifabric/utilities/lib/customizations/Customizer.js
Module not found: Error: Can't resolve 'react' in 'D:\DataIntegrationApp\Product\node_modules\@uifabric\utilities\lib\customizations'

Is it possible to remove the dependency of React? Can we just make it a pure Icon Library?

**Comment by khmakoto** [comment]
Hi @fhljys. I understand your ask and I think it is worth discussing. @dzearing @micahgodbolt what do you think about this? Is there something we can do in the short term? Who are the correct people to involve in this discussion?

**Comment by micahgodbolt** [comment]
100% worth discussing. Might be a question to pass to @Jahnp as well, if he's been considering this idea.

**Comment by Jahnp** [comment]
Hmm—from doing a quick search through the code, it actually seems React isn't used directly by either `@uifabric/styling` or `@uifabric/icons`. The dependency may have been left over from copying when the package was created, and I imagine it'd be safe to remove from both.

@dzearing , any concerns with that? I may take a crack at it this week if I have the time.
