### ISSUE TITLE
Implementation documentation needs cleaned up

### ISSUE THREAD

**Issue by graham-sportsmgmt** [OfficeDev/office-ui-fabric-react#967]
There are a lot of errors in the Implementation section of the documentation, and it should be cleaned up.

Some examples:

- The Button Class lists focus() as the only required member, but not one of the code samples for Button use focus
- IContextualMenuItem under CommandBar has 18 deprecated members, and we have to search through the Description field to see what to use as the actual members haven't been moved into the Optional section
- Optional members all seem to be followed by question marks
- Copying the text seems to be disabled in Edge and Chrome (haven't checked Firefox)
- The Type is  cut off for most onClick events (reading "(ev?: React.MouseEvent<H..." which seems to be cut off)

**Comment by kristoferbrown** [comment]
None of these specific issues appear to exist anymore. @graham-sportsmgmt, feel free to reopen this issue with more details if you see any specific issues.
