### ISSUE TITLE
Set a date without `allowTextInput` and `parseDateFromString`

### ISSUE THREAD

**Issue by weijia-ai** [OfficeDev/office-ui-fabric-react#9672]
**Set a date without `alowTextInput`**
I'm trying to change the date value of datepicker based on other options on page without enabling `alowTextInput`. I can somehow hack `parseDateFromString` but I don't want to do that.

Looks like setting `value` will only change the initial date of datepicker and it can't be changed after datepicker has been rendered.

**What component or utility would this be added to**
Datepicker

**Have you discussed this feature with our team, and if so, who**
No

**Additional context/screenshots**
![image](https://user-images.githubusercontent.com/52427362/60552290-0d877080-9ce3-11e9-8ec6-1b7c8fc31b53.png)
I'm trying to change datepicker2 in the picture while the first one being set up. 
According to the doc [here](https://uifabric.azurewebsites.net/#/controls/web/datepicker), it doesn't seem to be possible. Am I missing anything?
Thanks!

**Comment by khmakoto** [comment]
Hi @weijia-ai, I'll make some tests to see if I can get this to work in a non-hacky way. In the meantime, can someone from @OfficeDev/uifabric-calendar take a look at this issue and confirm if this is possible?

**Comment by weijia-ai** [comment]
@khmakoto Thank you Khmakoto! Feel free to ping me if you need any details

**Comment by khmakoto** [comment]
Hi @weijia-ai, [here is a codepen](https://codepen.io/khmakoto/pen/GbVPGr?editors=0010) where each `DatePicker` is being changed depending on the value that is chosen for the other `DatePicker` (move start date if new end date is before and move end date if new start date is after).

Please let me know if this helps or if there is anything else I can do for you!

**Comment by weijia-ai** [comment]
@khmakoto Thank you! I missed the obvious part and that sample is super helpful. Thanks!

**Comment by khmakoto** [comment]
@weijia-ai For sure! I'm glad the codepen is helpful! If there's anything else I can help you with please let me know! And feel free to close this issue as well if you think it is solved 😄

**Comment by weijia-ai** [comment]
Yeah, sure. :)
