### ISSUE TITLE
Button: Broken styles

### ISSUE THREAD

**Issue by fantua** [OfficeDev/office-ui-fabric-react#968]
### Bug Report

- __Package version(s)__: 1.5.5

#### Describe the issue:
Disabled IconButton

#### Actual behavior:

![actual](http://image.prntscr.com/image/b39390982b8c4f0a9871d05729407739.png)

#### Expected behavior:

![expected](http://image.prntscr.com/image/aec39a57d7af4feeb530dde613c68e90.png)

Also, how can I use Hero Button? Now it's look like:  
![hero](http://image.prntscr.com/image/fa3b74cb5e2f492cae6d8e007a958a82.png)

**Comment by dzearing** [comment]
The icon disabled button is now addressed.

@mikewheaton Hero buttons are deprecated, correct?

@fantua If you have a use case where you were using hero buttons, could you provide a screenshot for us to better understand your case?

**Comment by mikewheaton** [comment]
Yes, the Hero button is deprecated. There are some discussions happening with design around creating a similar button pattern, but I don't think anything is finalized there yet. It would be very helpful to see where @fantua is wanting to use this.

**Comment by fantua** [comment]
@dzearing @mikewheaton for me, in that case it's look good:

![hero](http://image.prntscr.com/image/ccd64cddc17b45cd91024ba05cd9051d.png)

much better, than this:

![without-hero](http://image.prntscr.com/image/69fd5d0a535d456097f0e1780fb0dbff.png)
