### ISSUE TITLE
Filter items in Combobox  when user is searching.

### ISSUE THREAD

**Issue by B-Esmaili** [OfficeDev/office-ui-fabric-react#9682]
Currently when we type in the Combobox input to search after items it doesn't filter items (doesn't remove unmatched items) to make it easy to pick from.

![demo](https://user-images.githubusercontent.com/9152515/60574290-97d8de80-9d8e-11e9-94e2-9456b2a763f6.jpg)

as you can see in the screenshot i have typed in 'Option A' but other options still appear in the list whereas they had to disappear to let user pick from options more easily.Between when we start typing drop-down should  popup so that users be able to see similar options as they are typing but is stays closed and only benefit you get is word suggestion.

**Comment by khmakoto** [comment]
Hi @B-Esmaili, thanks for filing this, seems like a great feature request! @joschect and @micahgodbolt, maybe something to think about adding in the long run?

**Comment by micahgodbolt** [comment]
Yeah, i think this is on our backlog of things to add. 
This issue is a duplicate for #6565, but for the combobox. 

The plan is to eventually merge the two controls as they overlap so much. That epic is #6030

**Comment by khmakoto** [comment]
@B-Esmaili I've added a reference to this issue in #6030. I'll be closing this issue as a duplicate since the work is already being tracked there and in #6565.

Thanks!
