### ISSUE TITLE
Panel closes if user swipes out of panel

### ISSUE THREAD

**Issue by Sbearlin** [OfficeDev/office-ui-fabric-react#9683]
### Bug Report

- __Package version(s)__: SPFX & sp-office-ui-fabric-core - 1.7.1 
- __Browser and OS versions__: Chrome, Internet Explorer tested. However I think it is all browsers

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? No

Requested priority: Normal

Products/sites affected: SharePoint Online - Modern View. Panels in general

#### Describe the issue:

When using the Panel component ([Link](https://developer.microsoft.com/en-us/fabric#/controls/web/panel)) Office UI Fabric with SPFx 1.7.1 there is (I would believe so) unintended behavior when swiping from inside the panel and out. I causes the panel to close/dismiss. This is replicated by pressing and holding left mouse button inside the panel, dragging the mouse outside the panel and then releasing the left mouse button.
Appearently doing this triggers the onOuterClick event, but clicking outside the panel does not trigger this event.
This is problematic if a user is e.g. marking a text field by holding down the left mouse button and is swiping left (to mark everything) but "over swipes" and releases the left mouse button outside the panel.
This is also applicable to SharePoint Online Modern Experience when going to a custom list, selecting an item and pressing Edit in the command bar.

Image of code to override the onOuterClick event so the panel doesn't close:
![image](https://user-images.githubusercontent.com/9077258/60578773-1713e580-9d82-11e9-83d5-8ecf84b9f123.png)

![panelclose-bug](https://user-images.githubusercontent.com/9077258/60579216-f0a27a00-9d82-11e9-8513-3ff3c241554b.gif)

#### Actual behavior:

Upon "swiping" out of the Office UI Fabric component Panel, the event onOuterClick event is triggered. 

#### Expected behavior:

onOuterClick should not be triggered by this behavior, especially considering the name of the event.

**Comment by khmakoto** [comment]
Hi @Sbearlin, thanks for filing the issue!

I tried replicating it in [this codepen](https://codepen.io/khmakoto/pen/xozWKJ?editors=0010) and I found that `onOuterClick` is not even being called. @kkjeer, can you take a quick look at my codepen and confirm this behavior? I'll take a stab at fixing this issue once you confirm it.

**Comment by kkjeer** [comment]
@khmakoto I am also able to see this behavior in your codepen, where `onOuterClick` is not called.

**Comment by Sbearlin** [comment]
Hi @khmakoto 
No problem!
I can see that the onOuterClick does not fire in your codepen example as well. However I can also see that the bug is not replicated in the example, which is interresting. Can it be that it is a newer version of UI Fabric which does not have the error with the "swipe"?
I know it is normally supposed to be codepen only, but you can also try and replicate this behavior in SharePoint Online (description tells how-to replicate)

**Comment by khmakoto** [comment]
Hi @Sbearlin, do you know which version of Fabric is SharePoint Online using? That could help with both replicating the issue and getting a fix for it.

**Comment by Sbearlin** [comment]
As far as I can see in my package.json the module: `"@microsoft/sp-office-ui-fabric-core": "1.7.1"` is the one responsible for getting Office UI Fabric. And when I reference a React component, like the panel, the library of `office-ui-fabric-react` is referenced.
When looking into the node_modules folder the package.json for office-ui-fabric-react is noting following version: `"version": "5.131.0"`.

[package.zip](https://github.com/OfficeDev/office-ui-fabric-react/files/3372454/package.zip)

I've attached the package.json for the library

**Comment by khmakoto** [comment]
Thanks @Sbearlin! I can use this information to continue investigating this bug. I'll keep you updated on my findings.

**Comment by khmakoto** [comment]
I've traced down the introduction of this behavior to version 5.116.1 and PR #5580, which is a cherrypick from #5552. I'll check to see where this was fixed so that I can cherrypick it into Fabric 5.

As a side note, it seems that the bug that was occurring in Fabric 7 where `onOuterClick` was not being called is fixed now, so we can relax on that for now.
