### ISSUE TITLE
Modal component add Overlay props

### ISSUE THREAD

**Issue by x73x63** [OfficeDev/office-ui-fabric-react#9684]
**Describe the feature that you would like added**
Modal component add Overlay props

**What component or utility would this be added to**
Optional props to pass to the Overlay component hosting the Modal.

#9631 
#9670 

**Have you discussed this feature with our team, and if so, who**

**Additional context/screenshots**

**Comment by khmakoto** [comment]
Hi @x73x63, I see that this is a similar ask to the ones you filed yesterday. I'll have a PR shortly for this.
