### ISSUE TITLE
[Accessibility][Screen reader-Button]: Screen reader is reading information twice for "button" under default button controls

### ISSUE THREAD

**Issue by dollykumari5** [OfficeDev/office-ui-fabric-react#9685]
Detailed description of this issue can be found here [SharePoint](https://microsoft-my.sharepoint.com/:x:/p/v-amaver/ES4u1n2IVNNPuoO2dU5gywIBdNy61RcmtbihpLEKSTfzyA?e=M7f2Dv)

Component:Button

**Comment by khmakoto** [comment]
Hi @dollykumari5, thanks for filing the issue. This is not a bug per se given that Narrator is first reading the text inside the `Button` and then the actual type of control, which is `Button`. I'll make a PR to change the text so that it is not confusing.
