### ISSUE TITLE
[Accessibility][Screen reader-Breadcrumb]: Narrator focus moves twice on the first element of context menu in scan mode. 

### ISSUE THREAD

**Issue by dollykumari5** [OfficeDev/office-ui-fabric-react#9690]
Detailed description of this issue can be found here [SharePoint](https://microsoft-my.sharepoint.com/:x:/p/v-amaver/EY0Apc7qTg1Bj4Doi06KgiwBBuzA5wMGhmv4TtYpvrVTiw?e=4gUNmO)

Component:Breadcrumb

**Comment by khmakoto** [comment]
Hi @dollykumari5, thanks for filing this! I'll investigate the issue to see if this is something on our part, on Narrator's part or by design in scan mode given how it breaks from author's intent in dictation and navigation.

**Comment by khmakoto** [comment]
Hi @dollykumari5, I've confirmed that this is by design in scan mode. This is what the Narrator team has told me:

>This is by design from Scan mode (to stop on individual controls and text).
>
>Narrator tries to prioritize reading text content over element/control properties (if they provide the same information) as text provides more detailed information about content (text attributes).
>
>Which means that technically whenever Narrator reads a control, it should try to read the control **and** every `label` element. Depending on the content, this might make Narrator jump between different parts of the content surface.

Please let me know if you need anything else or if you want any clarification.
