### ISSUE TITLE
PersonaCoin initial colors are inconsistent due to differences between versions 6 and 7

### ISSUE THREAD

**Issue by idijan** [OfficeDev/office-ui-fabric-react#9691]
This is an issue observed in OwaReact SDF.

There are persona coins shown on the page, eg. email senders.
Hovering or clicking on them opens a profile card.
Profile card code comes from a separate package (LPC).

Until recently, both LPC and OWA were on Fabric React 6.
Then OWA upgraded to version 7. Due to changes in [#8905](https://github.com/OfficeDev/office-ui-fabric-react/pull/8905) that resulted in a color difference which breaks our coherence principles.

**Comment by khmakoto** [comment]
Hi @idijan! I see that you have a PR up for fixing this issue. Thanks a lot!

**Comment by idijan** [comment]
The new colors in Fabric 7 were part of wide improvements and adherence to fluent theme.
Therefore, we're not going to regress them back to old palette from v6.

I'll close this issue.
The inconsistency in the specific apps will be solved within them, by passing the color using initialsColor property.
