### ISSUE TITLE
GroupedList incorrect value for parameter nestingDepth in onRenderCell 

### ISSUE THREAD

**Issue by known-as-bmf** [OfficeDev/office-ui-fabric-react#9693]
To compute the nestingDepth passed as argument to `onRenderCell`, the GroupedList component only traverses the first (leftmost) "branch" of the group tree and uses this value for every item (every call to `onRenderCell`).

There are 2 problems here:
* all items share same depth
* depth of the leftmost branch is used

Maybe this code should somehow use the `level` property declared on the IGroup interface.

Code is here: https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/GroupedList/GroupedList.base.tsx#L247

### Environment Information 
 
- __Package version(s)__: office-ui-fabric-react 7.5.1
- __Browser and OS versions__: not relevant

### Please provide a reproduction of the bug in a codepen:
 
expand all groups and check left margin of items
both examples are identical, except for the ordering of the groups

https://codepen.io/anon/pen/BgVwjb
https://codepen.io/anon/pen/ydEzXO

 
#### Actual behavior:
 
item depth incorrect
 
#### Expected behavior:
 
items to have margin corresponding to their depth

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority:  Normal
 
Products/sites affected: ?

**Comment by khmakoto** [comment]
Hi @known-as-bmf, thanks for filing the issue! Could you elaborate on how the margins are wrong in the codepens? I'm not as familiar with the `GroupedList` component, so I'm failing to see what is wrong and what you expect from the control.

**Comment by known-as-bmf** [comment]
here are two images to illustrate the issue:

* On the right is the group "tree" of the GroupedList and on the left is the result
* Red line is the computed nesting depth (for all nodes of the GroupedList)
* Green line is the expected depth for specific rows

![image](https://user-images.githubusercontent.com/11721166/60810475-84ae8000-a18d-11e9-93ad-bec9aaf9410b.png)

![image](https://user-images.githubusercontent.com/11721166/60810548-adcf1080-a18d-11e9-938d-e3dec1ca1a42.png)

The problem here is that the GroupedList only computes on depth for the whole List (the group tree leftmost branch depth)

Is this helpful ?

**Comment by khmakoto** [comment]
Thanks @known-as-bmf! That is really helpful. I'll take a stab to fix this issue.
