### ISSUE TITLE
Tooltip Persists After Scrolling

### ISSUE THREAD

**Issue by chrismohr** [OfficeDev/office-ui-fabric-react#9694]
### Environment Information 
 
- __Package version(s)__: > 6.184.0
- __Browser and OS versions__: Chrome 75.0.3770.100, macOS 10.14.5

#### Actual behavior:
 
I'm seeing 2 variations of this issue.

**With Tab Focus**
1. With tab focus on a tooltip host, scroll the page.
2. Observe that the tooltip continues to show until focus changes.
![tooltip_with_tab_focus](https://user-images.githubusercontent.com/601657/60604343-559ea580-9d6c-11e9-8ce8-e842183b8630.gif)

**Without Tab Focus**
1. Hover cursor over tooltip host and scroll the page.
2. Observe that the tooltip continues to show until scrolling stops.
![tooltip_without_tab_focus](https://user-images.githubusercontent.com/601657/60609414-7835bc00-9d76-11e9-81de-b7bba84372c7.gif)

Tooltip continues to show after page scrolling starts, and appears disconnected from the tooltip host. 
 
#### Expected behavior:

Tooltip should disappear the instant that scrolling starts. 

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Maybe.  With strong guidance.
 
Requested priority: Normal
 
Products/sites affected: Yammer

**Comment by khmakoto** [comment]
Hi @chrismohr, thanks for filing this issue! I can confirm both cases are indeed happening.

@micahgodbolt any idea why this might be happening? I'm going to get to this next week, but I figured I might as well ask for guidance before diving into the issue.

**Comment by redraushan** [comment]
Hi @chrismohr,
Thanks for reporting. I believe there could be two ways to fix the issue:
1. Tooltip scrolls along with the host element and stays glued together.
2. Tooltip gets closed as soon as scrolling starts.

I can take this one if we are clear about expected behaviour.
Thanks

**Comment by dzearing** [comment]
The tooltip technically is supposed to dismiss on scroll. Something is preventing it in these cases. Why are these scenarios special? That's what we need to dig into.

**Comment by micahgodbolt** [comment]
This repros in the current release as well:

https://fabricweb.z5.web.core.windows.net/oufr/7.8.0/#/examples/tooltip

Lots of broken logic in there. Tooltip should automatically dissapear on scroll (removing any delay). There is also a bug where if you hover over the tooltip and scroll, the events are eaten up.
