### ISSUE TITLE
HoverCard:  Separate the 'anchor' for the card from the card's hover-target

### ISSUE THREAD

**Issue by gggjtgxing** [OfficeDev/office-ui-fabric-react#9702]
**Describe the feature that you would like added**
currently hover card has a `target` props to tag hover card on, focus/hover on any element within that target will trigger a `mouseenter` event and open the card. but in that target element we have some buttons that we don't want to launch the card if user hover on.

**What component or utility would this be added to**
HoverCard
**Have you discussed this feature with our team, and if so, who**
No
**Additional context/screenshots**
![image](https://user-images.githubusercontent.com/17696563/60637109-f8d3d700-9dcd-11e9-959a-dd6515702c6e.png)

we have the name field (red box) as hover card target so we can anchor the Hover Card to the right of that target element. but we don’t want the hover card to be launched if the user put their cursor over the 3 buttons at the right side.
you may want to say we can make the text field only as target, the problem is the text fileld element changes size based on mouseover, then the hover card will wind up moving depending on the cursor location, screenshot for this problem

![Moving Hover Card](https://user-images.githubusercontent.com/17696563/60637751-7ac4ff80-9dd0-11e9-92b5-272226e6d1a8.gif)

Are you willing to submit a PR to fix? (Yes, No)
Yes

**Comment by khmakoto** [comment]
Hi @gggjtgxing, thanks for filing this issue. I don't know if this will solve your issue but an idea that occurs to me is to use `ev.stopPropagation()` on those three buttons when they detect a `mouseenter` so that it is not passed propagated to the entire name field. I'm not entirely sure how it would behave if you had already entered then name field though. Could you try this approach and come back to report what kind of results you got? Thanks!

**Comment by gggjtgxing** [comment]
https://github.com/OfficeDev/office-ui-fabric-react/pull/9723/files
![hovercard_target](https://user-images.githubusercontent.com/17696563/60749948-5c890c00-9f56-11e9-9c30-7c7a9b264174.gif)

**Comment by atneik** [comment]
@gggjtgxing I'm curious, why does text field changes its size upon hover? Is that a feature?

**Comment by gggjtgxing** [comment]
because hero buttons on the right side only show up upon mouseOver
![image](https://user-images.githubusercontent.com/17696563/60835961-5030c900-a179-11e9-9204-278809ebb81d.png)

![image](https://user-images.githubusercontent.com/17696563/60836015-722a4b80-a179-11e9-9a89-badbd9ea978f.png)
