### ISSUE TITLE
componentRef for Dialog does not return reference to component

### ISSUE THREAD

**Issue by jackiecorn** [OfficeDev/office-ui-fabric-react#9703]
Dialog's componentRef is expected to return a reference to the component, but instead it is returning a current object of null.

**Comment by khmakoto** [comment]
Hi @jackiecorn, thanks for filing this issue! I'll try to repro it in a codepen to start investigating what's happening.

**Comment by dzearing** [comment]
The `IDialog` interface which componentRef returns is empty. Technically componentRef should be removed. What are you trying to access?

**Comment by jackiecorn** [comment]
> The `IDialog` interface which componentRef returns is empty. Technically componentRef should be removed. What are you trying to access?

A reference to the Dialog component element, similar to that of the Panel component.

**Comment by dzearing** [comment]
`componentRefs` are designed to return a specific, limited interface. Like exposing a "focus" method to focus a button.

What on the Dialog component are you trying to access? Returning you IDialog would be returning you an empty object.

**Comment by jackiecorn** [comment]
I was trying to render the Dialog's HTML element(minus the overlay background and absolute positioning) in a specific div on the page (think of it as a preview of what the dialog would look like when opened). I wanted to use the componentRef to access the dialog element so when there were more than one dialogs on the page I'd have a way to differentiate and render them separately.

**Comment by dzearing** [comment]
I believe you could use a `ref` to access the component itself. However, maybe another solution would be better.

The Dialog can be rendered in a specific div on the page:

https://codepen.io/dzearing/pen/MMPBww

The important part is:

```tsx
modalProps={{ layerProps: { hostId: 'id of div' } }}
```

You can also provide a classname on the modal to replace the position fixed with static. Not perfect, but maybe that's what you're trying to achieve.

**Comment by jackiecorn** [comment]
Yes that does it for me.
I just wanted to point out that the componentRef doesn't return anything useful.
If it was not intended to have a componentRef prop, please remove it from the docs to avoid confusion.
Thanks!

**Comment by dzearing** [comment]
Totally agreed, it should have been deprecated. Thank you @jackiecorn!
