### ISSUE TITLE
[Accessibility][Screen Readers-Calendar]: Information about the change of week is not narrated by screen reader whenever user press Enter on previous/next button

### ISSUE THREAD

**Issue by dollykumari5** [OfficeDev/office-ui-fabric-react#9706]
Detailed description of this issue can be found here [SharePoint](https://microsoft-my.sharepoint.com/:x:/p/v-amaver/EfQzz15i5S1MuFJ1F1X9xDgBaNTpsu3jvO_wgE-gVh-6Eg?e=gE9Ij5)

Component: Calendar

**Comment by khmakoto** [comment]
Hi @dollykumari5, thanks for filing this issue! This seems to be a duplicate of Bug 5 in #8349, so I'll be closing this since the issue is already being tracked there. Thanks again!
