### ISSUE TITLE
[Accessibility][Keyboard Navigation-Calendar]: Upon Selecting the Go to Today control,focus moves to the arrow present in the click for calendar button

### ISSUE THREAD

**Issue by dollykumari5** [OfficeDev/office-ui-fabric-react#9707]
Detailed description of this issue can be found here [SharePoint](https://microsoft-my.sharepoint.com/:x:/p/v-amaver/ET00KVncv5pEq3TJu4US4JYBePRo_bzAbI1O2f4oyOoi6w?e=cmfqyk)

Component: Calendar

**Comment by khmakoto** [comment]
Hi @dollykumari5, thanks for filing this issue! I don't seem to be able to repro this on our website, can you try again and check if you're still encountering this scenario or if it's been solved already? Thanks!

**Comment by khmakoto** [comment]
Just wanted to give an update here that I'm waiting for a response from the Narrator team regarding this issue.

**Comment by khmakoto** [comment]
I finally got a response from the Narrator team and this seems to be a bug on Edge because, even with Narrator off, the system focus moves to the arrow. I've filed a bug to Edge so they can take care of this. Given that, I'll mark this as `Resolution: External` for now. Thanks!
