### ISSUE TITLE
[Accessibility][Usable-Calendar]: Role=Application is used for calendars.

### ISSUE THREAD

**Issue by dollykumari5** [OfficeDev/office-ui-fabric-react#9708]
Detailed description of this issue can be found here [SharePoint](https://microsoft-my.sharepoint.com/:x:/p/v-amaver/EakH150kSwRGpKnSl9WocPABBf8DajkaRRcue8qWxOiQmQ?e=ifeol6)

Component: Calendar

**Comment by khmakoto** [comment]
Hi @dollykumari5, thanks for filing this issue! This seems to be a duplicate of Bug 10 in #8349, so I'll be closing this since the issue is already being tracked there. Thanks again!
