### ISSUE TITLE
GridList bottom border line is disappearing on 90% zoom 

### ISSUE THREAD

**Issue by omerquyyum12** [OfficeDev/office-ui-fabric-react#9710]
when we zoom browser page to 90% gridlist bottom border line is disappearing. you can check this behavior on this page [https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist](https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist)
![list](https://user-images.githubusercontent.com/52535075/60666106-af43c480-9e7f-11e9-9094-ab5f5a43ec44.PNG)

**Comment by khmakoto** [comment]
Hi @omerquyyum12, thanks for filing this! I don't seem to be able to replicate this issue.

On Edge:

![image](https://user-images.githubusercontent.com/7798177/60744908-e8863e00-9f2c-11e9-9470-ac7ae7224cd0.png)


On Chrome:

![image](https://user-images.githubusercontent.com/7798177/60744912-f1770f80-9f2c-11e9-8274-c79b5a292c27.png)


Can you try again and check if this is still happening to you? Thanks!

**Comment by omerquyyum12** [comment]
Hi @khmakoto  this issue is only producing on standard laptop screen 1920x1080 resolution.
![list](https://user-images.githubusercontent.com/52535075/60791587-66d91f00-a17d-11e9-8c2f-c64467416931.PNG)

**Comment by khmakoto** [comment]
@omerquyyum12, could you tell me which browser are you using?

**Comment by omerquyyum12** [comment]
@khmakoto  i am using chrome and here is image for my work. u can see lines are hiding on 90% zoom.
![list](https://user-images.githubusercontent.com/52535075/61027529-de9e8800-a3cf-11e9-8e2c-3ffe6adc60dd.PNG)
on 100%
![list 2](https://user-images.githubusercontent.com/52535075/61027603-0988dc00-a3d0-11e9-8a43-6f5608ca6536.PNG)

**Comment by khmakoto** [comment]
I'll continue investigating in different resolutions to see if I can repro this.

**Comment by khmakoto** [comment]
Hi @omerquyyum12 I've tried on three different resolution and dpi configurations and multiple browsers and I haven't been able to repro your situation. I'll mark it as `Not An Issue` for now since I can't repro it.

**Comment by omerquyyum12** [comment]
Hi @khmakoto  you can see that it is producing in my UI and also in Fabric UI .  one of my task is depend upon this fix :-)

**Comment by micahgodbolt** [comment]
I can see it too. Not 100% sure what our options are. Just comes down to subpixel rendering in that browser.

**Comment by micahgodbolt** [comment]
I'd probably consider this a browser bug and leave it at 'wont fix'.

**Comment by khmakoto** [comment]
@omerquyyum12 I guess you could bump of the line to be 2px instead of 1px. Otherwise, your best bet would be to file an issue in Chrome.

Hopefully this helps at least a little bit. I'll close the issue for now.
