### ISSUE TITLE
All dates selected before 1915-11-01 in the calendar return the previous day

### ISSUE THREAD

**Issue by adambowles** [OfficeDev/office-ui-fabric-react#9714]
Playing around with the controls on the [demo site](https://developer.microsoft.com/en-us/fabric#/controls/web/calendar), any date selected before 1915-11-01 will return the previous day

### Environment Information 
 
- __Package version(s)__: Whatever version is on the demo site
- __Browser and OS versions__: (fill this out if relevant)

#### Actual behavior:
 
- Click 31/10/1915
- 30/10/1915 returned

All dates selected before 1915-11-01 return the previous day
 
#### Expected behavior:
 
- Click 31/10/1915
- 31/10/1915 returned

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Low 
 
Products/sites affected: https://developer.microsoft.com/en-us/fabric#/controls/web/calendar

**Comment by adambowles** [comment]
Can't replicate it again 🤔

**Comment by adambowles** [comment]
Reloaded the page and it is indeed replicatable (on the "Calendar launched from a button" calendar)

**Comment by khmakoto** [comment]
Hi @adambowles, thanks for filing this issue! I can confirm that I can repro this on our webpage. This seems like a really weird bug. Can someone in @OfficeDev/uifabric-calendar take a look at this?

**Comment by khmakoto** [comment]
Hi @adambowles it seems I can't repro it anymore. I'll be adding the `Can't Repro` label here and, if I encounter it again, then I'll open the issue again.

**Comment by adambowles** [comment]
I'm encountering it again:

![2019-07-22 17 21 36](https://user-images.githubusercontent.com/10128574/61647467-4ba1ff80-aca5-11e9-98f2-bddfe742fa3a.gif)

Safari Version 12.1.1 (14607.2.6.1.1)
macOS Version 10.14.5 (18F132)
