### ISSUE TITLE
DropdownBase : Cannot read property 'focusElement' of null

### ISSUE THREAD

**Issue by sylvain-hamel** [OfficeDev/office-ui-fabric-react#9715]
### Environment Information 
 
- __Package version(s)__: 7.5.0
- __Browser and OS versions__: Chrome 75.0.3770.100, Windows 10

### Please provide a reproduction of the bug in a codepen:

I have an e2e test that clicks a dropdown and clicks an item. Because this is automated, it happens very fast.

#### Actual behavior:
 
The test fails intermittently here in `DropdownBase`:

```
        _this._onPositioned = function (positions) {
            if (_this._focusZone.current) {
                // Focusing an element can trigger a reflow. Making this wait until there is an animation
                // frame can improve perf significantly.
                _this._requestAnimationFrame(function () {
                    var selectedIndices = _this.state.selectedIndices;
                    if (selectedIndices && selectedIndices[0] && !_this.props.options[selectedIndices[0]].disabled) {
                        var element = Object(_Utilities__WEBPACK_IMPORTED_MODULE_2__["getDocument"])().querySelector("#" + _this._id + "-list" + selectedIndices[0]);
                        _this._focusZone.current.focusElement(element);
                    }
                    else {
                        _this._focusZone.current.focus();
                    }
                });
            }
            if (!_this.state.calloutRenderEdge || _this.state.calloutRenderEdge !== positions.targetEdge) {
                _this.setState({
                    calloutRenderEdge: positions.targetEdge
                });
            }
        };
```
 
This line is not safe 
```
_this._focusZone.current.focusElement(element);
```` 
Apparently the ref is `null` when the `_requestAnimationFrame` calls back

#### Expected behavior:
 
Should perform a null check on `_focusZone.current` before using it.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix?
No
 
Requested priority: 
Normal. The workaround is to put a `cy.wait(150)` in my test but it's ugly.

**Comment by khmakoto** [comment]
Hi @sylvain-hamel, thanks for filing this issue!

@joschect what do you think about this? I think it is a reasonable request since the value of `current` could become `null` while we wait for the callback inside `requestAnimationFrame` to be called. Just wanted to run this by you before fixing it.

**Comment by dzearing** [comment]
Calling RAF means async code is being called which isn't being canceled on unmount. We should be using `safeRequestAnimationFrame` instead. And probably adding a tslint rule to warn against using RAF, setInterval, or setTimeout directly in code.

@khmakoto Please fix this correctly by canceling the async running operation using the safe* methods in `@uifabric/utilities`.

**Comment by khmakoto** [comment]
@dzearing looking at the code, it seems to be using `safeRequestAnimationFrame`, since `_requestAnimationFrame` is defined in line 70 as

```ts
private _requestAnimationFrame = safeRequestAnimationFrame(this);
```

So it seems there's some other weird thing happening here.

**Comment by dzearing** [comment]
oops, sorry about that. Hmm. Not sure why RAF callback would be called when ref is nulled.

**Comment by khmakoto** [comment]
I think they are separate issues, because, based on my understanding, RAF callback only checks for safety on `this` whereas this issue is dealing with safety on `this._focusZone.current`, which I think can be null.
