### ISSUE TITLE
@autobind and UI Fabric 7

### ISSUE THREAD

**Issue by PooLP** [OfficeDev/office-ui-fabric-react#9717]
Hi,

@autobind decorator is removed from UI Fabric 7.
Is there a substitute or should we use the good old .bind (this)?

Thanks

**Comment by khmakoto** [comment]
Hi @PooLP, thanks for filing this issue!

@jdhuntington do you know why this was removed from Fabric 7 and what can we use as a substitute?

**Comment by dzearing** [comment]
Don't use `autobind`. Instead, use lamdas:

```ts
class Foo {

  // Bad: this function is not bound to this, so using it on a button's onClick would result in
  // the wrong thing.
  private _onClick(ev) {
     console.log(this.foo);
  }

  // Good: This function can reference "this" correctly, as it will be bound to "this".
  private _onClick = (ev) => {
  };
```

The `autobind` decorator is not necessary anymore and just adds overhead to the bundle. Using oldschool `bind` also is not recommended as it makes the code messy.

**Comment by dzearing** [comment]
Let us know if we can help further, feel free to close otherwise. :)

**Comment by dzearing** [comment]
BTW @khmakoto this is mentioned in the coding guidelines wiki; I double checked to make sure we have it covered:

https://github.com/OfficeDev/office-ui-fabric-react/wiki/TypeScript-Guidelines#use-arrow-functions-instead-of-bind

**Comment by PooLP** [comment]
Thanks for response. I close this issue.
