### ISSUE TITLE
Still clueless, how can we implementation of ITheme style in the react project?

### ISSUE THREAD

**Issue by guptarajesh001** [OfficeDev/office-ui-fabric-react#9719]
Still clueless, how can we implement ITheme style in the SPFx framework project, using React? It would be great, if you share with us any sample of using Theme for above project.
Another question, will it support classic SharePoint Online site?

**Comment by khmakoto** [comment]
Hi @guptarajesh001, thanks for filing this issue!

@Jahnp @Vitalius1 is this related to the `MDL2` theme effort that is ongoing right now?

**Comment by Vitalius1** [comment]
@khmakoto doesn't look like it is.

@guptarajesh001, can you you be more specific to what you are referring, please? What do you mean when you say: _...implement ITheme style..._? Is the question about using custom styling for Fabric components through `styles` prop and CSS-in-JS approach or something else?

Also, you might wanna consult these resources:
1. SPFx dev docs have several pages related to styling and themes: [Work with CSS](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/css-recommendations), [Themes and colors](https://docs.microsoft.com/en-us/sharepoint/dev/design/themes-colors), [Use themes](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/use-theme-colors-in-your-customizations) and [Fabric integration](https://docs.microsoft.com/en-us/sharepoint/dev/spfx/office-ui-fabric-integration).
2. Open an issue in one of the SharePoint Github repos listed [here](https://github.com/sharepoint) as it looks like your question relates more to SPFx integration with Fabric which most of our devs are not familiar enough to help. @patmill, would appreciate if you could point to the right direction and also enlighten about the classic sites author mentioned. Thanks!

**Comment by guptarajesh001** [comment]
Thanks for explanation, however, we want to implement theming of SPFx webpart in the classic as well as modern pages of SharePoint online.

**Comment by KevinTCoughlin** [comment]
> Thanks for explanation, however, we want to implement theming of SPFx webpart in the classic as well as modern pages of SharePoint online.

@guptarajesh001 which version of `office-ui-fabric-react` does your web-part depend on? Our theming solution depends on the version of our library you are pinned to.

Once the above is provided, I should be able to provide guidance for you. Thanks!

**Comment by guptarajesh001** [comment]
@KevinTCoughlin, Kindly find versions we have used in our project:    

NodeJs - v8.14.1
npm -6.4.1
@types/react - ^16.8.18
@microsoft/sp-office-ui-fabric-core- ^1.8.0
office-ui-fabric-react - ^6.176.3

**Comment by KevinTCoughlin** [comment]
@guptarajesh001, I have a Github repo that serves as a sample SPFx webpart using Fabric 6's theming system at https://github.com/KevinTCoughlin/spfx-oufr-theme-sample.

Can you take a look at the code and see if that makes sense for your use-case?

The file most relevant to your ask should be https://github.com/KevinTCoughlin/spfx-oufr-theme-sample/blob/master/src/webparts/helloWorld/components/HelloWorld.tsx#L9.

**Comment by KevinTCoughlin** [comment]
I should add that if the above sample doesn't help you, please let us know why. We've been looking to document this better so I'd like your experience to inform that work. Mainly:

Is the sample relevant or missing information you'd find useful?
