### ISSUE TITLE
Nav control focus invisible in high contrast mode

### ISSUE THREAD

**Issue by rohitrewa** [OfficeDev/office-ui-fabric-react#9724]
### Bug Report

- __Package version(s)__: 7.7.1
- __Browser and OS versions__: IE

Are you willing to submit a PR to fix? (Yes, No) No

Requested priority: (Blocking, High, Normal, Low) Accessibility bug -> High

Products/sites affected: (if applicable) Microsoft Visio Data Visualizer

#### Describe the issue:

Invisible focus on Nav bar in high contrast mode

#### Expected behavior:

Nav bar should differentiate focused element 

![image](https://user-images.githubusercontent.com/4102247/60753731-d1ab1e80-9ff4-11e9-9762-2777c7a43237.png)

**Comment by Vitalius1** [comment]
@betrue-final-final what is the expected color to be used in HC mode when focusing a nav item?

**Comment by betrue-final-final** [comment]
The problem here is that there are boxes around all the items. There should be no boxes around them, and the focus rectangle should be color_WindowText (white in HC Black)

**Comment by rohitrewa** [comment]
@Vitalius1 @betrue-final-final For planning purpose, we would like to understand when can we see this fix in npm.

**Comment by Vitalius1** [comment]
@rohitrewa , I am running the CI on the PR again and as soon as it's merged into master next day's morning we will have a release containing the fix. You will be also be notified in the thread of this issue when that happens and what version to use to have it available in your app.
