### ISSUE TITLE
Suggestions in BasePicker should not specify empty string for ref

### ISSUE THREAD

**Issue by rlanda-msft** [OfficeDev/office-ui-fabric-react#9731]
When rendering the Suggestions list on a people picker, a single item will either get a ref object prop, or have it set to empty string. The code in question is the ref prop below:

```
   return (
      <div
        className={this._classNames.suggestionsContainer}
        id={suggestionsListId}
        role="listbox"
        aria-label={suggestionsContainerAriaLabel}
      >
        {suggestions.map((suggestion, index) => (
          <div
            ref={suggestion.selected ? this._selectedElement : ''}
            // tslint:disable-next-line:no-string-literal
            key={(suggestion.item as any)['key'] ? (suggestion.item as any)['key'] : index}
            id={'sug-' + index}
            aria-selected={suggestion.selected}
            role="option"
            aria-label={suggestion.ariaLabel}
          >
            <StyledTypedSuggestionsItem
              suggestionModel={suggestion}
              RenderSuggestion={onRenderSuggestion}
              onClick={this._onClickTypedSuggestionsItem(suggestion.item, index)}
              className={suggestionsItemClassName}
              showRemoveButton={showRemoveButtons}
              removeButtonAriaLabel={removeSuggestionAriaLabel}
              onRemoveItem={this._onRemoveTypedSuggestionsItem(suggestion.item, index)}
            />
          </div>
        ))}
      </div>
    );
```

in https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/pickers/Suggestions/Suggestions.tsx 

This causes as issue with multiple react roots and react throws https://reactjs.org/warnings/refs-must-have-owner.html at render time. Rather than an empty string, undefined should be provided as the default instead.

### Please provide a reproduction of the bug in a codepen:

Currently unable to repro in a codepen as it needs multiple react roots.
 
#### Actual behavior:
 
Crashes on rendering the ref with an empty string.
 
#### Expected behavior:
 
Renders properly

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes (though I am having trouble setting up the enlistment)
 
Requested priority: Blocking (Preventing feature rollout)
 
Products/sites affected: Word-Online

**Comment by JasonGore** [comment]
This also seems like it could be an issue in `SuggestionControl`, `SuggestionsCore` in both `FloatingSuggestions` and `FloatingPicker` components.

**Comment by Vitalius1** [comment]
@JasonGore I have a PR up just for `Suggestions` in pickers folder. I looked over the other 2 files you suggested but in there the ref is handled by `_resolveRef` coming from `BaseComponent` that receives only a string type argument and then handles it by returning an empty object in case the string is empty. So perhaps there needs to be a dipper fix. For now we need to unblock the product rollout.
