### ISSUE TITLE
onIncrement and onDecrement don't work on SpinButton

### ISSUE THREAD

**Issue by jackiecorn** [OfficeDev/office-ui-fabric-react#9740]
`onIncrement` and `onDecrement` don't work on SpinButton, even when returned a string value.

e.g. adding this prop stops the value from updating on pressing the up key:
`onIncrement={value => value}`

**Comment by Vitalius1** [comment]
Hi @jackiecorn, I put together a [codepen](https://codepen.io/vitalius1/pen/QXJJWY) real quick based on the example called `Stateful SpinButton` we have on our [documentation website](https://developer.microsoft.com/en-us/fabric#/controls/web/spinbutton) and it looks like everything is working as it's supposed to.

Let me know if you have any other questions or I am missing something.
Also, could you please let me know what version of Fabric you are using in case my codepen doesn't help you so I can investigate further. Thanks for submitting the issue.

**Comment by jackiecorn** [comment]
I only realized the value passed into the callback function was the value BEFORE the increment/decrement and not after the increment/decrement.
I had never thought I'd have to do the math inside the function, basically bypassing the step prop and return the calculated value as a string.
Now I see it's not really a bug so feel free to close this. However I wish the documentation was more clear on that.
