### ISSUE TITLE
ChoiceGroup label style does not follow disabled state

### ISSUE THREAD

**Issue by Tinathnath** [OfficeDev/office-ui-fabric-react#9744]
### Environment Information 
 
- __Package version(s)__: current

### Please provide a reproduction of the bug in a codepen:
 
[Codepen](https://codepen.io/anon/pen/ZdVOJG?&editable=true)
 
#### Actual behavior:
 
The ChoiceGroup main label (at the thop) does not follow disabled state like other components (like Textfield) do.
 
#### Expected behavior:
 
Main label to follow disabled state.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal

**Comment by Vitalius1** [comment]
@Tinathnath thanks for submitting the issue. I have looked into it and indeed there is no scenario on how to disable the main top label. This is a quick fix and a PR will follow shortly

**Comment by Vitalius1** [comment]
@betrue-final-final, do we mark the top label on a disabled `ChoiceGroup` as also disabled? Here is the before and after:
### Before: 
![Screen Shot 2019-07-09 at 14 02 17](https://user-images.githubusercontent.com/29514833/60922733-3c0cca80-a252-11e9-9d1d-8706fb54e287.png)

### After:
![Screen Shot 2019-07-09 at 14 02 30](https://user-images.githubusercontent.com/29514833/60922743-44650580-a252-11e9-9df2-bc01eb4fc942.png)

**Comment by Tinathnath** [comment]
@Vitalius1 Thanks for the reply. For our current project we did a quick css hack but I'll have a look at the PR for the proper fix :)

**Comment by betrue-final-final** [comment]
Marking the label as disabled makes sense.

**Comment by betrue-final-final** [comment]
Looks like dropdown, slider and spin button also have this issue.
