### ISSUE TITLE
color: shades class has clamp function commented out, with no reason stated?

### ISSUE THREAD

**Issue by alirobe** [OfficeDev/office-ui-fabric-react#9753]
### Environment Information 
 
- __Package version(s)__: master, commit 9c95e9b
- __File__: `packages/office-ui-fabric-react/src/utilities/color/shades.ts`

### Issue

- The clamp function is commented out, with no reason stated. This might result in negative, or impossible values. 

### Suggested fix

- Suggest a quick git blame to contact the author so the the function can be removed, or fixed, or the comment could be explained.

### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Low
 
Products/sites affected: All Microsoft 365 Products

**Comment by Vitalius1** [comment]
@phkuo I believe the author is referring to this line:
https://github.com/OfficeDev/office-ui-fabric-react/blob/e8bbf18a4b8fd9b3ce378f92bb9f5274cba76fdd/packages/office-ui-fabric-react/src/utilities/color/shades.ts#L78

Do you know what action should be taken with that comment? Do we need to cleanup the extra 2 arguments of the function and remove the commented part?

**Comment by phkuo** [comment]
I don't remember. It should be fine to just uncomment it. I might have been testing it (possibly testing perf, since this would run many many times each time you change a base color), or the inputs to it were in such a way that you'd never get impossible numbers.
