### ISSUE TITLE
[Dropdown] onRenderLabel method for dropdown component

### ISSUE THREAD

**Issue by srinidhiprabhu96** [OfficeDev/office-ui-fabric-react#9755]
**Describe the feature that you would like added**
Having an onRenderLabel method for the dropdown component.

**What component or utility would this be added to**
Dropdown

**Have you discussed this feature with our team, and if so, who**
No

**Additional context/screenshots**
The onRenderLabel method would help in customizing the label of the dropdown. This would be needed if, for example, an info button needs to be shown next to the label.

**Comment by Vitalius1** [comment]
Thanks @srinidhiprabhu96 for submitting this feature request. Will investigate the possibility of adding this to the `Dropdown` control and follow up with findings. Meanwhile, it seems to be a very simple thing to implement so if you feel you can tackle this addition we welcome your contribution and happy to review your PR. There are plenty of examples on other components that can give you an idea on how to do it.
