### ISSUE TITLE
DetailsList building errors

### ISSUE THREAD

**Issue by aslanovsergey** [OfficeDev/office-ui-fabric-react#9757]
- __Package version(s)__: (6.143.0)

#### Describe the issue:

I use webpack to bundle my app. In project I use typescript 3.1.6.

When run build I get following errors:

`
ERROR in [at-loader] ./node_modules/office-ui-fabric-react/lib/index.d.ts:77:1 
    TS2308: Module './DetailsList' has already exported a member named 'IObjectWithKey'. Consider explicitly re-exporting to resolve the ambiguity.

ERROR in [at-loader] ./node_modules/office-ui-fabric-react/lib/index.d.ts:77:1 
    TS2308: Module './DetailsList' has already exported a member named 'ISelection'. Consider explicitly re-exporting to resolve the ambiguity.

ERROR in [at-loader] ./node_modules/office-ui-fabric-react/lib/index.d.ts:77:1 
    TS2308: Module './DetailsList' has already exported a member named 'ISelectionOptions'. Consider explicitly re-exporting to resolve the ambiguity.

ERROR in [at-loader] ./node_modules/office-ui-fabric-react/lib/index.d.ts:77:1 
    TS2308: Module './DetailsList' has already exported a member named 'SELECTION_CHANGE'. Consider explicitly re-exporting to resolve the ambiguity.

ERROR in [at-loader] ./node_modules/office-ui-fabric-react/lib/index.d.ts:77:1 
    TS2308: Module './DetailsList' has already exported a member named 'Selection'. Consider explicitly re-exporting to resolve the ambiguity.

ERROR in [at-loader] ./node_modules/office-ui-fabric-react/lib/index.d.ts:77:1 
    TS2308: Module './DetailsList' has already exported a member named 'SelectionDirection'. Consider explicitly re-exporting to resolve the ambiguity.

ERROR in [at-loader] ./node_modules/office-ui-fabric-react/lib/index.d.ts:77:1 
    TS2308: Module './DetailsList' has already exported a member named 'SelectionMode'. Consider explicitly re-exporting to resolve the ambiguity.
`

Here is my tsconfig

`{
  "compilerOptions": {
    /* Basic Options */
    "target": "es5",                         
    "module": "commonjs",                   
    "lib": [
      "es5",
      "dom",
      "es2017"
    ],     
    "jsx": "react",                    
    "outDir": "./lib",                         
    "moduleResolution": "node",          
    "esModuleInterop": true                
  },
  "include": [
    "src"
  ]
}`

**Comment by KevinTCoughlin** [comment]
I believe this is related to #9661

**Comment by aslanovsergey** [comment]
Thanks @KevinTCoughlin is there any workaround until it's fixed?

**Comment by Vitalius1** [comment]
There is a PR #9750 which is trying address this issue but needs some more investigation on the possible effects on some partners.

**Comment by aslanovsergey** [comment]
I mean maybe from typescript option we can disable  something so that it builds

**Comment by Vitalius1** [comment]
@kenotron, @ecraig12345 any ideas?

**Comment by ecraig12345** [comment]
Maybe add `skipLibCheck: true` in the tsconfig? Downside is that's kind of a sledgehammer--it skips type checking for everything in node_modules.

**Comment by aslanovsergey** [comment]
> Maybe add `skipLibCheck: true` in the tsconfig? Downside is that's kind of a sledgehammer--it skips type checking for everything in node_modules.

Pity is that I already have it

**Comment by Vitalius1** [comment]
@aslanovsergey after many discussions and investigations on possible breaking some partners it appears that your issue should be resolved with #10024 . According to @jdhuntington’s [comment](https://github.com/OfficeDev/office-ui-fabric-react/issues/9661#issuecomment-517813749) the fix should be available from the release 7.19.1 and up. Can you please verify and confirm that it indeed solved your issue. Apologies for taking so long 😄 .

**Comment by Vitalius1** [comment]
Also, in regards to your [stack-overflow question](https://stackoverflow.com/questions/57349218/dialog-scrolls-when-open) I would recommend opening an issue here as it feels like a bug that needs to be fixed.
