### ISSUE TITLE
Help: How to simulate changing a Dropdown in tests with enzyme.

### ISSUE THREAD

**Issue by chadsowald** [OfficeDev/office-ui-fabric-react#9767]
#### Describe the issue:

I'm having trouble testing the Dropdown component.  I want to simulate changing/selecting an option.  To do that, I have code like this:

**in render:**
<Dropdown
...
  onChange={ this.onChange }
...
/>

**in component:**
private onChange= (e: React.FormEvent<HTMLDivElement>, option: IDropdownOption) =>
{
  this.somePrivateMember = option.key;
}

**in test:**
wrapper.find('StyledWithResponsiveMode').simulate('change', { target: { value: 'some value' } });

#### Actual behavior:

The test fails because option.key is not defined, specifically option is not defined.

#### Expected behavior:

I would expect my test to succeed based on suggestions like https://github.com/airbnb/enzyme/issues/389#issuecomment-219052914

How am I supposed to simulate changing an option with Fabric UI?  I looked at the .Test file for Dropdown, but it uses something called "ReactTestUtils", which I do not.

**Comment by chadsowald** [comment]
A little more guesswork and I was able to figure it out:

`wrapper.find('StyledWithResponsiveMode').simulate('change', { target: { value: 'does not matter'} }, { key: 'the value you want to test with!', text: 'test text' });`

Wish there were examples of this already or that it was more clear in the documentation.

**Comment by Vitalius1** [comment]
@chadsowald glad you were able to figure it out.

> Wish there were examples of this already or that it was more clear in the documentation.

You mean examples and documentation of `enzyme` library or ours? I don’t believe we document any of our tests.

**Comment by chadsowald** [comment]
@Vitalius1 Thanks for asking.  I think it would have to be in Fabric UI docs/tests since it's specific to how the Fabric Dropdown calls the onChange handler.  You're right that I don't ever see documentation on how to test Fabric components.  In the past, I've found the source code test files to be helpful, but they weren't in this case.  I guess otherwise people find help here or on StackOverflow.  If the component documentation pages ever get test writing examples, this seems like a good candidate.  Thanks again!
