### ISSUE TITLE
"Callout directional example" moves with webpage.

### ISSUE THREAD

**Issue by MitchBodmer** [OfficeDev/office-ui-fabric-react#980]
### Bug Report

- __Package version(s)__: N/A
- __Browser and OS versions__: Firefox 51, Edge 40, Chrome 56

#### Describe the issue:

Go the the Callout directional example on the website. Click the "Show callout" button. Scroll. The callout will move along with you as you scroll.

#### Actual behavior:

Callout follows you.

#### Expected behavior:

Callout stays put relative to the element it's calling out.

**Comment by ecoukraine** [comment]
Hi guys,

I've the same problem - the Callout is scrolling with the page instead of being near the target.

Would you be kind to advice how to make the Callout to be positioned near the target?
