### ISSUE TITLE
CommandBar item.disabled props does not always update

### ISSUE THREAD

**Issue by mtone** [OfficeDev/office-ui-fabric-react#9806]
### Environment Information 
 
- __Package version(s)__: 7.9.0
- __Browser and OS versions__: Chrome 75 & Firefox 68, Windows 10 1903

### Please provide a reproduction of the bug in a codepen:
 
Codepen: https://codepen.io/mtone/pen/bPyeaR

#### Actual behavior:
 
Changing ICommandBarItemProps.disabled in <CommandBar items={items}> is not always re-rendered correctly. 

In the Codepen, I reproduced by calling setState(disabled) in useEffect hook. I believe React will call it immediately after render -- effectively a wasted render of the original prop, but this triggers the issue. Using a setTimeout (even with just 1ms) to change the prop doesn't trigger the issue.

Regular HTML button and Fabric PrimaryButton don't exhibit this problem.

As a workaround, wrapping my child component in React.memo / useCallback to avoid wasted renders fixed the problem, but that should be a performance optimization.

#### Expected behavior:
 
The CommandBar should always be (re-)rendered to match the latest props.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Normal
 
Products/sites affected: n/a

**Comment by joschect** [comment]
@mtone Thanks for including the codepen! I can definitely see that this is a bug. I don't see any obvious reason that this is happening yet, we'll investigate and get it fixed.

**Comment by mtone** [comment]
Thanks!
I noticed it also works if I modify the array/item instead of creating a new one on every render. I think  generating items dynamically should be OK though. https://codepen.io/mtone/pen/EBBROv

**Comment by joschect** [comment]
@mtone That makes sense, since you're modifying a reference it will propagate through even though new props/an update isn't explicitly being made.

**Comment by mtone** [comment]
CodePen works now, issue appears fixed.
