### ISSUE TITLE
Not able to programatically set the styles of a cell inside DetailsList component

### ISSUE THREAD

**Issue by rgurusankar** [OfficeDev/office-ui-fabric-react#9822]
### Environment Information 
 
- __Package version(s)__: 7.0.0
- __Browser and OS versions__:  Windows OS and Chrome browser

#### Actual behavior:
 
Not able to change the style of a cell in DetailsList component programatically. For ex: add margin, padding etc to a cell in the table on click of a button

#### Expected behavior:
 
should be able to add margin, padding etc to a cell in the table on click of a button

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by joschect** [comment]
@rgurusankar Thanks for submitting your question! I think you should be able to achieve this already by using the `onRender` prop in `IColumnProps`. It lets you pass in your own custom renderer to render each cell how you want. From there you can add or change padding depending on the props. For even more control you can provide your own `rowFieldsAs` prop in `IDetailsRowBaseProps` which lets you specify even more about the cell.

For a very rough example using onRender check out this [codepen](https://codepen.io/slimemold/pen/xovMKG?editors=0011).
