### ISSUE TITLE
Request: Enable rendering of callout without rendering dropdown box itself

### ISSUE THREAD

**Issue by candiceye** [OfficeDev/office-ui-fabric-react#9829]
**Describe the feature that you would like added**
A feature that would enable me to trigger an event that renders a callout without having to create a dropdown box in the first place. For example, clicking on some text would render my callout. No dropdown box is visible throughout this whole process.

**What component or utility would this be added to**
Dropdown component

**Have you discussed this feature with our team, and if so, who**
No

**Additional context/screenshots**

**Comment by joschect** [comment]
@candiceye To confirm what you are asking, it sounds you like you want the dropdown menu to be able to be rendered without the dropdown button itself, is that correct? 

If that is the case can you describe your scenario a bit more? Would you still need keyboard and all other dropdown functionality?
