### ISSUE TITLE
Backspace on ComboBox is inconsistent when AllowFreeform:T

### ISSUE THREAD

**Issue by acamargob** [OfficeDev/office-ui-fabric-react#9831]
### Environment Information 
 
- __Package version(s)__: Latest (7.10.0)
- __Browser and OS versions__: Tested in Chrome and Edge on Windows

### Please provide a reproduction of the bug in a codepen:
 
https://fabricweb.z5.web.core.windows.net/oufr/7.10.0/#/examples/ComboBox
 
#### Actual behavior:
 
1. Click on first combobox example in the link above
2. Select all text with Ctrl+A
3. Hit backspace. **The entire value is cleared**
4. Select another option via keyboard or mouse
5. Tab forward into the next control
6. Tab backwards into the first combobox **The entire value is highlighted**
7. Hit backspace **The selection is cleared, but the actual value remains**
 
#### Expected behavior:
 
The outcomes of steps 3 and 7 above should be consistent

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)

Yes, provided I get some guidance on how to fix
 
Requested priority: (Blocking, High, Normal, Low) 
 
Normal

Products/sites affected: (if applicable)

OWA Calendar/Event compose form/Time and Time Zone fields

**Comment by joschect** [comment]
@acamargob Thanks for submitting this and including a codepen! I can reproduce this easily and it's pretty obviously a bug. We'll take a look.
