### ISSUE TITLE
TextField component with Error Message doesn't read out error message correctly

### ISSUE THREAD

**Issue by Hardhik** [OfficeDev/office-ui-fabric-react#9834]
Using Win10 Narrator + Edge browser

Official examples here: https://developer.microsoft.com/en-us/fabric/#/controls/web/textfield#usage

## Codepen demonstrating the issue
https://codepen.io/anon/pen/LwPzEp

## Actual behavior:
1) Focus is on the TextField component with error message in it. Navigate using Caps Lock + Arrow keys.
This is what the component reads (got text from Narrator Buddy):
"
With error message, 
With error message, edit, Invalid, 
Press Space to edit.
end of line
group, 
alert, 
Error message, 
"

## Expected behavior:
The error message should be read without the "group" and as a single focusable element.

## Documentation describing expected behavior
Can be checked with NVDA + Chrome. It reads out the error message correctly along with the TextField content.

**Comment by joschect** [comment]
@Hardhik thanks for submitting this accessibility problem! Could you confirm the repro steps? When I use narrator I hear it read out "Editing, invalid, with error message"
