### ISSUE TITLE
Column handles in DetailsList break after one resize event.

### ISSUE THREAD

**Issue by carruthe** [OfficeDev/office-ui-fabric-react#985]
### Bug Report

- __Package version(s)__: 1.5.5
- __Browser and OS versions__: OS X Sierra, Safari 10.0.3

#### Describe the issue:

I am using the DetailsList component like this:

        <div className='ms-bgColor-themeLighterAlt'>
                <MarqueeSelection selection={this._selection}>
                    <DetailsList
                        items={listItems}
                        selection={this._selection}
                        selectionPreservedOnEmptyClick={true}
                        onItemInvoked={(item) => console.log(`Item invoked: ${item.name}`)}
                        onRenderItemColumn={this._onRenderItemColumn}
                        columns={[{ name: 'CPT', minWidth: 50, key: 'col_CPT', fieldName: 'CPT', isResizable:true },
                        { name: 'Description', minWidth: 100, key: 'col_description', fieldName: 'description', isMultiline: true, isResizable:true },
                        { name: 'Category', minWidth: 50, key: 'col_category', fieldName: 'category', isResizable:true }
                        ]}
                    />
                </MarqueeSelection>
            </div>

A couple of things are happening - The first column is being rendered at nearly 75% of the width of the control despite what I put in for `minWidth` (is this pixels?).  The main problem is that when trying to resize the columns, the behavior of the resizing handles is erratic.

#### Actual behavior:

Column handles are not reset after the user resizes a column.

#### Expected behavior:

Column handles should match the new column widths.

### If applicable, please provide a codepen repro:

See this video for a demo of the problem
[Demo of Problem](https://youtu.be/xInrGBcYwMs)

**Comment by carruthe** [comment]
Looks like my first issue (the initial sizing of the columns) is fixed by adding

`layoutMode={ DetailsListLayoutMode.fixedColumns }`

to the DetailsList control.  The other problem with the handles not relocating remains, though.

Thanks!

**Comment by dzearing** [comment]
@carruthe weirdness! Is this specific to Safari? Do you repro elsewhere?

**Comment by dzearing** [comment]
I tried setting up your code in a codepen repro here:

http://codepen.io/dzearing/pen/ygrqwB?editors=0110

I set `maxWidth` on the columns as well. This let's them size to max size and then condense if there isn't enough space.

On windows chrome, I don't repro. I'll go over to mac safari really quick and try there.

**Comment by carruthe** [comment]
@dzearing - Good question - I quickly tried it on Firefox and Chrome (OS X), and did not get the same error (i.e. it worked as expected).  Using your CodePen on Safari gave me the same error as I originally described.

Thanks for looking in to it!

Nick

**Comment by dzearing** [comment]
Yes I repro'd! This is definitely a browser quirk.

It can definitely be fixed if we make the parent container of the style position relative, but as a side effect the divider lines would not extend the full height of the list. This might be OK with our designers. That was the reason they were not `position: relative`. They would absorb the default left/top positioning, but the height could then be set to 100% which is 100% of the closes relative ancestor element which is the surface. It seems the Safari's default left/top position for the absolute element is not updated after the layout.
