### ISSUE TITLE
 DetailedList - Grouped: Adding all the column values to the group header.

### ISSUE THREAD

**Issue by gokuldhanvanthri** [OfficeDev/office-ui-fabric-react#9850]
Feature Requirement: Adding all the column values to the group header.
Example: Adding color value to the group groupred0 & the same value displayed as part of respective column
groups: [
                {key: 'groupred0', name: 'Color: "red"', **color: 'red',** startIndex: 0, count: 2},
]

Component: DetailedList - Grouped

This as part of the requirement, looking for an alternative to the treetable component, DetailedList-Grouped has all the features of the treetable component except that of the mentioned issue.

Do Find the required highlighted in the attachement.
![InkedDetailedList-Grouped](https://user-images.githubusercontent.com/39094609/61449913-98b76600-a973-11e9-907f-588f5d3e46a9.jpg)

**Comment by joschect** [comment]
@gokuldhanvanthri Thanks for submitting this. I want to make sure that I'm understanding what you're asking for, do you want to be able to group by multiple columns? Or do you just want the values from other columns to appear in the group header?

**Comment by gokuldhanvanthri** [comment]
@joschect, Its the second one, I want the values from other columns to appear in the header.

**Comment by gokuldhanvanthri** [comment]
@joschect, hope you are clear with the requirement. Do let me know if you have any queries.
Can I expect this requirement to be added in the near future? Your answer will help me in deciding the component for the application.

**Comment by joschect** [comment]
@gokuldhanvanthri Hey, sorry for the slow response. I was working on a [codepen](https://codepen.io/slimemold/pen/oKgrPe?editors=1111) to demonstrate how you could achieve this already. If this doesn't work for you we can add it to the backlog but it would require fairly substantial changes that might take quite a while.

**Comment by gokuldhanvanthri** [comment]
@joschect, thanks for the reply.
I saw your codepen demo & noted that you have added a custom header for the group field which solves the problem of adding values to other columns in the group header. 

But there are some issues which i see in this approach :
1. Aligning the column data correctly with the respective columns considering the resolution size.
2. Automatically updating the data position whenever user changes the width of the column.

Please let me know whether this is possible anyway with the custom header approach?

**Comment by KevinTCoughlin** [comment]
> Please let me know whether this is possible anyway with the custom header approach?

Consider forking @joschect's Codepen above to achieve the behavior you are looking for. It might be possible, but you'll likely need to write custom code as the current column measurement data may not be available outside of the component.

If the above is not possible, then this will likely have to go on our backlog. We would be receptive in reviewing a design and corresponding changes to support it. That design would likely have to include extracting the measurement logic for other consumers to use such as yourself.

**Comment by gokuldhanvanthri** [comment]
Thanks @KevinTCoughlin, I feel this will be too much of maintenance on the component from the application perspective. Anyway, I will talk to my team and take a decision regarding this & update if we are able to achieve it.
Still, it will be great if you include this feature/component as part of the fabric framework because treetable is one of the most commonly used component to showcase the hierarchical data in UI.

**Comment by KevinTCoughlin** [comment]
> Still, it will be great if you include this feature/component as part of the fabric framework because treetable is one of the most commonly used component to showcase the hierarchical data in UI.

Agreed. Let's have the discussion of introducing a "Tree" component in #7597 and soft-close this issue in the meantime.

Similar request #8942.

**Comment by marwankhalili** [comment]
I ran into this problem recently. I believe that using a custom `onRenderHeader` function is sufficient.

Figured I'd share my solution in case it could be of any use to someone stumbling upon this later. In my case, I replaced the default group header with a `DetailsRow` on top of the `GroupHeader` [(see codepen example)](https://codepen.io/marwankhalili/pen/PowwNqm)
