### ISSUE TITLE
Example 

### ISSUE THREAD

**Issue by manuelkpro** [OfficeDev/office-ui-fabric-react#9851]
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by KevinTCoughlin** [comment]
Hey @manuelkpro, it looks like you omitted content from the issue template. Please open a new issue with the necessary information for your specific scenarios or requests.

Closing this as not actionable in its current state.
