### ISSUE TITLE
Test setup should not ignore the legit error.

### ISSUE THREAD

**Issue by LiangMingChen** [OfficeDev/office-ui-fabric-react#9854]
### Environment Information 
 
- __Package version(s)__: (fill this out) 
- __Browser and OS versions__: (fill this out if relevant)

office-ui-fabric-react@^6.181.1, office-ui-fabric-react@^6.184.0, office-ui-fabric-react@^6.185.0:
  version "6.185.0"

#### Actual behavior:
this depot's test setup should not ignore the Null ref error cause the components like &lt;List&gt; a lot harder to test.

Specifically
https://github.com/OfficeDev/office-ui-fabric-react/blob/f31e6a0fd26fdefc9d00df5a03f31153f1975620/scripts/jest/jest-setup.js#L6

This is just swallow all possible null ref. when any error striang match 'error boundary.)

It is best practice to capture all console error on individual test and snapshot such that null ref will be descover as part of it.
If you take a look at the following 
![image](https://user-images.githubusercontent.com/3789716/61479350-7fe58b00-a948-11e9-9144-2248f7563423.png)

The error match 
https://github.com/OfficeDev/office-ui-fabric-react/pull/9343#issuecomment-499304103

As you notice, that Error is swallowed just because it match 
  + Consider adding an error boundary to your tree to customize error handling behavior.
  + Visit https://fb.me/react-error-boundaries to learn more about  **error boundaries**

That "error boundaries" cause null ref error to get ingnored in this depot.

It is not reasonable to ask all depot to find out &lt;List&gt; is not testable just because this depot test force to ignore any error string with 'error boundary'  (note originally is a warning.) but now is swallow the actually null-ref.

The test that throw exception should spyOn console.error instead.

 
#### Expected behavior:
 
* of undefined or * of null (NullRef)  should be capture for any test and snap shot. Instead of ignore it.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No)
 
Requested priority: (Blocking, High, Normal, Low) 
 
Products/sites affected: (if applicable)

**Comment by joschect** [comment]
@LiangMingChen Thanks for your submission. This is a good suggestion and we'll look into handling these errors more appropriately. 

However, the issue you are encountering should have been fixed and it should no longer be a problem to test in react 7.1.0, the fix was also backported into fabric 6.190.0 . If you bump up to that later version you shouldn't have issues with it.

**Comment by joschect** [comment]
@dzearing do you know why that line, https://github.com/OfficeDev/office-ui-fabric-react/blob/f31e6a0fd26fdefc9d00df5a03f31153f1975620/scripts/jest/jest-setup.js#L6 , was added?

**Comment by joschect** [comment]
@LiangMingChen It looks like @ecraig12345 just checked in a fix for the issues with error handling. Let us know if that doesn't fix it for you!

**Comment by LiangMingChen** [comment]
I am not sure the fix address the consumer depot which use the component here.
Any time, any code access native DOM element, which test render basic doesn't is a potential for the null ref crash.

for the  reference, we need to do a lot to work around FocusZone which use by detail list where it blindly assume element is there and call addEventListener, or ScrollView call element.getAttribute()

in Snapshot test (in our case ExplorationsPage.snapshot.tsx, the test goal obviously is not listen or access dom Element attribute, but to make sure DetailList or List to call onRenderCallback correctly. thus the snapshot does thing correctly.  (rather the throw, then it basically have not call onRenderCell call.)

![image](https://user-images.githubusercontent.com/3789716/61750512-78641e80-ad5a-11e9-9e9f-2f7d45637647.png)

This obviously doesn't scale, since we have no idea whether when FocusZone or Scrollable view will not access addEventListener.

**Comment by joschect** [comment]
@LiangMingChen I am confused, Elizabeth's fix explicitly removed the line that you had highlighted earlier. 

To clarify, what do you mean by consumer depot? Are you talking about this github code repository?

Also there was a fix put in sot that the details list will render correctly because it wasn't rendering the views. Have you pulled the latest and tried it again?
