### ISSUE TITLE
Facepile: Selection after click

### ISSUE THREAD

**Issue by fantua** [OfficeDev/office-ui-fabric-react#986]
### Bug Report

- __Package version(s)__: 1.5.5

#### Describe the issue:

Facepile got selection after click on more button.

![facepile](http://image.prntscr.com/image/da76124eb8734d87929c0aac77fdc8a2.png)

**Comment by micahgodbolt** [comment]
Yeah, this happens because that one is rendered as a button. Looking at using the BaseButton component instead, which will come with default styles removing that outline (as well as leverage everything we have in BaseButton)
