### ISSUE TITLE
Demo page for Layers Won't Close

### ISSUE THREAD

**Issue by malisbad** [OfficeDev/office-ui-fabric-react#9866]
### Environment Information 
 
- __Package version(s)__: 1.57.4 (I think)
- __Browser and OS versions__:

Google Chrome | 75.0.3770.100 (Official Build) (64-bit)
-- | --
Revision | cd0b15c8b6a4e70c44e27f35c37a4029bad3e3b0-refs/branch-heads/3770@{#1033}
OS | Mac OS X 

#### Actual behavior:
 
When using the "Using Customizer to control the default layer behavior" example on the documentation page, if you use "show panel" without having "trap panel" selected, the panel will open with the overlay and be unable to close. The overlay blocks access to the "show panel" toggle, and the cancel button does not close the panel as it should (according to the docs)

The same behaviour is seen when "trap panel" is selected, but it doesn't render the site unusable.
 
#### Expected behavior:
 
The panel should close when the cancel button is clicked, as documented.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Low 
 
Products/sites affected: [Fabric > Controls > Web > Layer](https://developer.microsoft.com/en-us/fabric#/controls/web/layer)

**Comment by joschect** [comment]
@malisbad thanks for submitting this! It's an easy bug fix which I've just put into pr.
