### ISSUE TITLE
Module not found: 'react'

### ISSUE THREAD

**Issue by graham-sportsmgmt** [OfficeDev/office-ui-fabric-react#987]
### Bug Report

- __Package version(s)__: 1.5.5
- __Browser and OS versions__: Win 10 Pro X64, VS Code, Chrome, Firefox, Edge

Node:
```
{ metrics: '0.1.0',
  npm: '3.10.8',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.9.0',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '5.1.281.84',
  zlib: '1.2.8' }
```

#### Describe the issue:

I used react-create-app to create an application yesterday, and installed fabric using npm.  I have one page that requests a CommandBar, and this is the output in the console:

```
Failed to compile.

Error in ../~/office-ui-fabric-react/lib/components/CommandBar/CommandBar.js
Module not found: 'react' in C:\code\node_modules\office-ui-fabric-react\lib\components\CommandBar

 @ ../~/office-ui-fabric-react/lib/components/CommandBar/CommandBar.js 21:12-28

Error in ../~/office-ui-fabric-react/lib/components/FocusZone/FocusZone.js
Module not found: 'react' in C:\code\node_modules\office-ui-fabric-react\lib\components\FocusZone

 @ ../~/office-ui-fabric-react/lib/components/FocusZone/FocusZone.js 21:12-28

Error in ../~/office-ui-fabric-react/lib/components/ContextualMenu/ContextualMenu.js
Module not found: 'react' in C:\code\node_modules\office-ui-fabric-react\lib\components\ContextualMenu

 @ ../~/office-ui-fabric-react/lib/components/ContextualMenu/ContextualMenu.js 21:12-28

Error in ../~/office-ui-fabric-react/lib/components/Icon/Icon.js
Module not found: 'react' in C:\code\node_modules\office-ui-fabric-react\lib\components\Icon

 @ ../~/office-ui-fabric-react/lib/components/Icon/Icon.js 11:12-28

Error in ../~/@uifabric/utilities/lib/BaseComponent.js
Module not found: 'react' in C:\code\node_modules\@uifabric\utilities\lib

 @ ../~/@uifabric/utilities/lib/BaseComponent.js 7:12-28

Error in ../~/@uifabric/utilities/lib/DelayedRender.js
Module not found: 'react' in C:\code\node_modules\@uifabric\utilities\lib

 @ ../~/@uifabric/utilities/lib/DelayedRender.js 7:12-28

Error in ../~/office-ui-fabric-react/lib/components/Image/Image.js
Module not found: 'react' in C:\code\node_modules\office-ui-fabric-react\lib\components\Image

 @ ../~/office-ui-fabric-react/lib/components/Image/Image.js 16:12-28

Error in ../~/office-ui-fabric-react/lib/components/Callout/Callout.js
Module not found: 'react' in C:\code\node_modules\office-ui-fabric-react\lib\components\Callout

 @ ../~/office-ui-fabric-react/lib/components/Callout/Callout.js 15:12-28

Error in ../~/office-ui-fabric-react/lib/components/Callout/CalloutContent.js
Module not found: 'react' in C:\code\node_modules\office-ui-fabric-react\lib\components\Callout

 @ ../~/office-ui-fabric-react/lib/components/Callout/CalloutContent.js 14:12-28

Error in ../~/office-ui-fabric-react/lib/components/Layer/Layer.js
Module not found: 'react' in C:\code\node_modules\office-ui-fabric-react\lib\components\Layer

 @ ../~/office-ui-fabric-react/lib/components/Layer/Layer.js 8:12-28

Error in ../~/office-ui-fabric-react/lib/components/Layer/Layer.js
Module not found: 'react-dom' in C:\code\node_modules\office-ui-fabric-react\lib\components\Layer

 @ ../~/office-ui-fabric-react/lib/components/Layer/Layer.js 9:15-35

Error in ../~/office-ui-fabric-react/lib/components/Layer/LayerHost.js
Module not found: 'react' in C:\code\node_modules\office-ui-fabric-react\lib\components\Layer

 @ ../~/office-ui-fabric-react/lib/components/Layer/LayerHost.js 15:12-28

Error in ../~/office-ui-fabric-react/lib/components/Popup/Popup.js
Module not found: 'react' in C:\code\node_modules\office-ui-fabric-react\lib\components\Popup

 @ ../~/office-ui-fabric-react/lib/components/Popup/Popup.js 15:12-28

Error in ../~/office-ui-fabric-react/lib/components/Fabric/Fabric.js
Module not found: 'react' in C:\code\node_modules\office-ui-fabric-react\lib\components\Fabric

 @ ../~/office-ui-fabric-react/lib/components/Fabric/Fabric.js 15:12-28
```

#### Actual behavior:

Numerous errors in the command prompt, no pages served.

#### Expected behavior:

App should start without errors

### If applicable, please provide a codepen repro:

Not sure how I could do that.

**Comment by panigrah** [comment]
* Does the app run if you don't import any of the office-ui-fabric modules?
* did you install office-ui-fabric as a global package or local package? 

I installed react using react-create-app and then `npm install -g ofice-ui-fabric-react` and have no issues importing `CommandBar` into the sample app. It is likely a problem with your setup.

**Comment by muraray** [comment]
![image](https://user-images.githubusercontent.com/826984/35431864-306f38fa-02b9-11e8-88f6-a532d510b9f5.png)

debug.log file info as follows

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   'ofice-ui-fabric-react' ]
2 info using npm@5.0.3
3 info using node@v8.1.2
4 verbose npm-session 973efbb7655cb637
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 404 https://registry.npmjs.org/ofice-ui-fabric-react 2408ms
8 silly fetchPackageMetaData error for ofice-ui-fabric-react@latest 404 Not Found: ofice-ui-fabric-react@latest
9 verbose stack Error: 404 Not Found: ofice-ui-fabric-react@latest
9 verbose stack     at fetch.then.res (C:\Program Files\nodejs\node_modules\npm\node_modules\pacote\lib\fetchers\registry\fetch.js:41:19)
9 verbose stack     at tryCatcher (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\util.js:16:23)
9 verbose stack     at Promise._settlePromiseFromHandler (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:512:31)
9 verbose stack     at Promise._settlePromise (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:569:18)
9 verbose stack     at Promise._settlePromise0 (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:614:10)
9 verbose stack     at Promise._settlePromises (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\promise.js:693:18)
9 verbose stack     at Async._drainQueue (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:133:16)
9 verbose stack     at Async._drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:143:10)
9 verbose stack     at Immediate.Async.drainQueues (C:\Program Files\nodejs\node_modules\npm\node_modules\bluebird\js\release\async.js:17:14)
9 verbose stack     at runCallback (timers.js:800:20)
9 verbose stack     at tryOnImmediate (timers.js:762:5)
9 verbose stack     at processImmediate [as _immediateCallback] (timers.js:733:5)
10 verbose cwd D:\Others\Samples\UI\Fabric\office-ui-layout
11 verbose Windows_NT 10.0.15063
12 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "ofice-ui-fabric-react"
13 verbose node v8.1.2
14 verbose npm  v5.0.3
15 error code E404
16 error 404 Not Found: ofice-ui-fabric-react@latest
17 verbose exit [ 1, true ]

**Comment by cschleiden** [comment]
`of_f_ice` not `ofice`

**Comment by AnjaniChallamcherla** [comment]
@muraray I had the same error
I ran `npm i lts office-ui-fabric-react`
and everything fixed
Hope it helps

**Comment by ebouJ** [comment]
+1
