### ISSUE TITLE
Support to set custom attributes on Spin button or ComboBox components

### ISSUE THREAD

**Issue by pagaur** [OfficeDev/office-ui-fabric-react#9871]
We need a way to allow DOM custom attributes on SpinButton and ComboBox fabric components.

   https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html

**Describe the feature that you would like added**
To associate a custom attribute by accessing the domElement.setAttribute one has to use findDomNode API which is discouraged, and the same can be done in reacty fashion by putting the custom attribute as part of props to the component. 
      BaseButton which covers majority of commands allows passing the custom attribute to <button.. element, on the same note we should allow setting custom attribute on SpinButton and ComboBox components.
    
  We want to show UI-fabric commands as suggestion in SearchBox control. The SearchBox control suggestions menu (designed by FAST team is not a ui-fabric contextual menu) and supports a custom attribute 'data-nav' to be set on commands to allow keyboard navigation between the commands (the same behavior already exists for SearchBox suggestions shown in Office.com and sharepoint sites).

**What component or utility would this be added to**
SpinButton, ComboBox

**Have you discussed this feature with our team, and if so, who**

**Additional context/screenshots**

**Comment by joschect** [comment]
@pagaur thanks for submitting the ticket and doing a fix!
