### ISSUE TITLE
DetailsList with specific height expands with no bound

### ISSUE THREAD

**Issue by SarhadSalam** [OfficeDev/office-ui-fabric-react#9877]
### Environment Information 
 
- Package version(s): 
- Browser: Chrome Version 75.0.3770.142 (Official Build) (64-bit)
- OS version: Windows 10 Enterprise Version 1903

### Please provide a reproduction of the bug in a codepen:
 https://codepen.io/sarhadSalam/pen/eqmXWY

#### Actual behavior:
 
When height of `DetailsList` is set to pixel values, and `DetailsList` is a child of `Stack.Item` the `DetailsList` width keeps expanding, and expands beyond the screen width. The `DetailsList` doesn't respect the width set forward by `Stack.Item`.

Ways to stop the expansion of `DetailsList`:
1. Set a pixel width value, but this breaks the responsive behavior of `Stack.item`.
2. Set `overflow-y` to `hidden` instead of `scroll/auto`. (This is weird, because `overflow-y` is required with specific height but setting it causes the expansion past `Stack.Item` auto calculated width)
 
#### Expected behavior:
 
When `DetailsList` height is set, the component should render with the width of the parent `Stack.item` without expanding.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? Yes, but I do not know how the internals of `DetailsList` work
 
Requested priority: Normal

**Comment by joschect** [comment]
@SarhadSalam Thanks for the ticket and including a codepen! This seems like a bug, we'll look into it and try to get a fix.

**Comment by SarhadSalam** [comment]
I just noticed, this seems to happen in Chrome but the bug is prevented in Edge

**Comment by xugao** [comment]
This seems to be related to `withViewport` logic in `DetailsList`

@SarhadSalam - another option for you might be setting `layoutMode={DetailsListLayoutMode.fixedColumns}` for the `DetailsList`, if that works for your case. see [open](https://codepen.io/xugao/pen/OJVMmBE)
