### ISSUE TITLE
Selection.onSelectionChanged callback should take ISelection as an arg

### ISSUE THREAD

**Issue by aappddeevv** [OfficeDev/office-ui-fabric-react#9882]
I've run into the case where I need to access the ISelection object to obtain the selection inside the callback e.g. to obtain the selected items. However, the callback does not take the ISelection object so technically, you can't reference the object you are creating inside the callback to obtain the selection. Some of the recent react hooks patterns become awkward due to this problem.

**Comment by ecraig12345** [comment]
Thanks for filing this. Could you provide an example of some code (especially with hooks) where not having access to the selection becomes a problem?

**Comment by aappddeevv** [comment]
If Selection is really an instance variable vs something that drives state...

```javascript
function HookComponent({blah}) {
   const selectionRef = React.useRef(new Selection({
      onSelectionChanged: () => { /* need to access selection here to do something with it */ }
  })
  <div>
    <DetailsList ...
        selection = selectionRef.current
     />
  </div>
}
```
Typed this in but did not check syntax, etc.

**Comment by aappddeevv** [comment]
``javascript
function MyComponent({notifyFunc}) {
  const selection = React.useMemo(() =>
    new Selection({ onSelectionChanged: () => { /* need access to selection so I can call notifyFunc */ }})
  }, [notifyFunc])

  <div> ...use selection in DetailsList... </div>
}
```
I can't use a useRef because useRef has a strict value and hence would create a Selection object each time. It's also not part of state. If notifyFunc from the parent changes, then Selection needs to be recreated.

Or at least that's where I have landed in trying to get this to work.

**Comment by ecraig12345** [comment]
Asked my teammates for suggestions and here's what @JasonGore had to say:

> I've been playing around and I think I'm siding with their view because I'm having trouble finding even a cumbersome way to do this. `Selection` has an embedded `onSelectionChanged` callback and any useful implementation of this callback needs its parent `Selection` container as well as the `notifyFunc` prop. It's easy with classes because you can just store the Selection as a class member and call the current `notifyFunc` prop value, even as it mutates.
>
> With hooks, we can store `Selection` as an instance variable (with either `useState` or `useRef`) and create a memoized callback based on `notifyFunc`'s value, but we can't combine the two without making new `Selection` objects. There's no way to make a constant callback that just calls the current value of `notifyFunc` like a class can, and `Selection` doesn't allow us to change `onSelectionChanged`.
>
> It seems like this would all be quite a bit easier if `Selection` was an argument in `onSelectionChanged` callback, or you could at the very least update the `onSelectionChanged` callback in an existing `Selection` instance. (Right now it's only taken in with the constructor and otherwise inaccessible.) Mutating the object's callback seems smelly though, so I think it'd be best if `Selection` was an argument in the `onSelectionChanged` callback.
>
> My messy way of trying various things is here in case you want to try anything: https://codepen.io/jasongore/pen/QejepR

@ThomasMichon Since IIRC you worked on Selection in the past, do you have any thoughts about whether it would be reasonable to add the current `ISelection` as an argument to the `onSelectionChanged` callback?

**Comment by flavogov** [comment]
@ThomasMichon any thoughts on the potential API change?

**Comment by aappddeevv** [comment]
@ThomasMichon any thoughts on the potential API change?

**Comment by ThomasMichon** [comment]
One thing I should point out is that anyone can subscribe to the `change` event of a `Selection` object after it has been created, though the interface is non-obvious:
```ts
const selection = new Selection();

const events = new EventGroup();
events.on(selection, 'change', () => {
  // Selection changed.
});

// events.dispose();
```
This means that to subscribe to a `Selection`, you don't *need* to pass `onSelectionChanged` as a prop when you create the instance; it's only there for convenience.

With the above, it's easy enough to accept callbacks that take the `ISelection`:

```tsx
function Foo(props: {
  onSelectionChanged: (selection: ISelection) => void;
}): JSX.Element {
  const [selection] = React.useState(() => new Selection());
  
  React.useEffect(() => {
    const events = new EventGroup();
    events.on(selection, 'change', () => {
      props.onSelectionChanged(selection);
    });
    return () => events.dispose();
  }, [selection, props.onSelectionChanged]);

  return (
    <div />
  );
}
```

**Comment by ecraig12345** [comment]
Thanks! @aappddeevv, does this work for you?

**Comment by aappddeevv** [comment]
That should work and solves the immediate issue.

I will point out that it took a few lines of code and its complexity is much higher and as pointed out, non-obvious, than just passing the ISelection object into the callback.

But I guess we pull all of that into another hook :-).

As a counter argument to taking the simplest approach I mentioned, I'll point out that the constructor subscription approach in general may result in more pilot errors as the subscription may not be properly terminated for any given render cycle if a programmer creates the Subscription object and attaches the callback in a way that does not properly support the hooks model i.e. all of this probably needs more baking time.
