### ISSUE TITLE
Need to show tool tip on command bar having both text and icon-only:true props

### ISSUE THREAD

**Issue by muthubalu** [OfficeDev/office-ui-fabric-react#9886]
### Bug Report

- __Package version(s)__: 7.5.0
- __Browser and OS versions__: Edge 44 , Chrome and Windows 10

#### Priorities and help requested (not applicable if asking question):

Are you willing to submit a PR to fix? (Yes, No) : No

Requested priority: (Blocking, High, Normal, Low)  : High

Products/sites affected: (if applicable)

#### Describe the issue:
Tool tip should visible for both icon and icon with text element also
fabric doesn't show tool tip for the combined elements (Icon with text )

#### Actual behavior:

![image](https://user-images.githubusercontent.com/22934196/61617771-08d22e80-ac89-11e9-9c3c-fb20f8e90f97.png)

#### Expected behavior:
Here we need the tool tip to be available for element with  + icon with new text (+ New) 

![image](https://user-images.githubusercontent.com/22934196/61618150-d83ec480-ac89-11e9-8f1b-a10904d5d13a.png)

**Comment by ecraig12345** [comment]
Thanks for filing this. @micahgodbolt or @joschect do you think this sounds like a reasonable request?

**Comment by micahgodbolt** [comment]
This should be pretty easy to accomplish with a custom render'ed button. Buttons are usually self explanatory (unless they are icon only), so we did not add them to all of the buttons.

**Comment by micahgodbolt** [comment]
Either use ButtonAs
https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/components/CommandBar/CommandBar.types.ts#L63

Or each item in your items array can accept an 'onRender' prop

**Comment by ecraig12345** [comment]
@muthubalu Will this workaround work for you?
