### ISSUE TITLE
Cannot disable an option in ComboBox when multiselect is on

### ISSUE THREAD

**Issue by jfcourtois** [OfficeDev/office-ui-fabric-react#9888]
If you look here: 
https://fabricweb.z5.web.core.windows.net/oufr/7.12.0/#/examples/ComboBox 
... you can see in the example that "Option F" sets "disabled: true" and yet in the UI, the option is still enabled where the ComboBox is in multiselect mode.

The ComboBox MultiSelect mode should have the same behavior as singleSelect for disabled options.

**Comment by ecraig12345** [comment]
Thanks for reporting this! I feel like it used to work properly in the past, so I'm not sure what happened... Fixing in #9897.
