### ISSUE TITLE
Shared color documentation doesn't clearly explain how to reference SharedColors

### ISSUE THREAD

**Issue by danielgwilson** [OfficeDev/office-ui-fabric-react#9894]
The docs page found at https://developer.microsoft.com/en-us/fabric#/styles/web/colors/shared (`apps/fabric-website/src/pages/Styles/Colors/docs/web/ColorsShared.md`) doesn't correctly reference how to use SharedColors; instead, the sample incorrectly shows:

```javascript
import { CommunicationColors } from '@uifabric/fluent-theme/lib/fluent/FluentColors';

<div style={{ color: CommunicationColors.primary }} />;
```

This applies to the NeutralColors page as well.

**Comment by ecraig12345** [comment]
Thanks for noticing this! Fixing in #9919.
