### ISSUE TITLE
FocusZone hardcodes role="presentation" even when the default tag is overriden

### ISSUE THREAD

**Issue by brandonthomas** [OfficeDev/office-ui-fabric-react#9898]
We have a case where we want our FocusZone to be rendered as a UL. In this case list role should come for free due to the semantics of the tag we're using. However, because role is set to presentation we have to explicitly set role to list when we're using a list tag. Can we remove role="presentation" when a user specifies a tag?

https://github.com/OfficeDev/office-ui-fabric-react/blob/ffd15a72949fdfefd4ceb46ecf124c124c68567a/packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.tsx#L215

## Actual behavior:
role="presentation" is set regardless of the tag used to render FocusZone.

## Expected behavior:
Semantics of the tag I use are respected.

Semi-related to #4971

**Comment by ecraig12345** [comment]
That seems like a reasonable request. I can see some different possible ways to implement it:
1. If a tag is provided, never set `role="presentation"` (downside: what if they want a different tag but `role="presentation"` anyway?)
2. Make the role configurable, defaulting to "presentation" (downside: how can the user specify *not* to set a role? passing in null or empty string maybe?)
3. Add a flag to disable setting `role="presentation"`: `disableRole`, `noRole`, etc

@JasonGore Do you have any thoughts about which of these would be the best option?

**Comment by JasonGore** [comment]
It seems `FocusZone` [already gives this capability](https://codepen.io/jasongore/pen/pMyvRB). Doing:

```
<FocusZone role={undefined} ... >
```
Results in: 

![image](https://user-images.githubusercontent.com/26070760/61748252-aba3af00-ad54-11e9-95ad-e6e7a159a13f.png)

User props [are spread 3 lines lower](https://github.com/OfficeDev/office-ui-fabric-react/blob/ffd15a72949fdfefd4ceb46ecf124c124c68567a/packages/office-ui-fabric-react/src/components/FocusZone/FocusZone.tsx#L218) and an explicit `role` value of `undefined` value will overwrite the component default.

**Comment by brandonthomas** [comment]
Yah the role can be overriden already. The main point with my issue is that I shouldn't have to do that if I already spent the effort of specifying semantics through my own tag. I would think #1 would be appropriate.

**Comment by JasonGore** [comment]
The concern we have is that we can't safely assume somebody wants a non-presentational component simply because the `as` prop having a value. What happens if someone uses a `span`, for example? Such a change would now make they're previously presentational components non-presentational. We are leaning towards making this behavior explicit rather than incorrectly assume intent through the presence of the `as` prop.

**Comment by ecraig12345** [comment]
Just made a PR #10020 removing the default role entirely, based on discussion with David and on the original issue #4971.
