### ISSUE TITLE
.focus method of choicegroup doesn't focus on checked Item

### ISSUE THREAD

**Issue by satyamamit** [OfficeDev/office-ui-fabric-react#9901]
we have a requirement of setting focus on choicegroup checked item on component load but in focus() method element focus is only set when data-is-focusable is set to true, which I am not sure how to do it. 

I tried changing below line in code 

```
 if (elementToFocus && elementToFocus.getAttribute('data-is-focusable') === 'true') {

          elementToFocus.focus(); // focus on checked or default focusable key

          return;

        }
```

to this and things started working.

```
 if (elementToFocus && elementToFocus.checked === true) {

          elementToFocus.focus(); // focus on checked or default focusable key

          return;

        }
```

Please look into this issue.

## Actual behavior:
calling .focus() method on choicegroup doesn't focus checked item of choicegroup.
## Expected behavior:
calling .focus() method should set focus on currently checked Item.

**Comment by ecraig12345** [comment]
@natalieethell added the behavior of focusing on options in #6224, but it looks like for that to work, you'd have to manually set `'data-is-focusable': true` when defining the list of `IChoiceGroupOption`s. Natalie, do you remember if there was a reason that you wanted the behavior of focusable options to be opt-in? (Also, the fallback behavior is to focus on `this._inputElement.current`, but that ref is never even set!)

**Comment by natalieethell** [comment]
It looks like the line adding the 'data-is-focusable' attribute to options (originally [here](https://github.com/natalieethell/office-ui-fabric-react/blob/fdf07cbb642af91ba75284a0a646e95a1bb55645/packages/office-ui-fabric-react/src/components/ChoiceGroup/ChoiceGroup.base.tsx#L88)) was removed. @JasonGore's PR back in August (https://github.com/OfficeDev/office-ui-fabric-react/pull/5842) added `data-is-focusable` to either the checked option or the first non-disabled element when no options are checked, which resulted in the behavior we're looking for.

Soooo, that explains the break. I'm still trying to figure out when that line was removed. I'll update this issue when I do.

**Comment by natalieethell** [comment]
It looks like it was removed in @dzearing's PR https://github.com/OfficeDev/office-ui-fabric-react/pull/8053 due to some issues with ChoiceGroup in FocusZone. One option for a fix is to basically do the check that the initial 'data-is-focusable' was doing, which is checking if an option is checked or the default focusable option.
