### ISSUE TITLE
Narrator is not providing information about "no.of results found" after performing a will card search in Search Box"

### ISSUE THREAD

**Issue by SyedRehmanRazvi** [OfficeDev/office-ui-fabric-react#9908]
**User Experience:** 
Users who rely on screen readers are getting affected as Narrator is not providing information about "no.of results found" displayed after performing search.

**Test Environment:** 
OS: Win 10 
OS Version: 1903 (OS Build 18323.1000) 
Browser: Edge
URL: https://fabricweb.z5.web.core.windows.net/oufr/7.14.0/#/examples/searchbox 
Screen Reader: Narrator

**Repro Steps:** 
Step 1: Start Narrator
Step 2: Open above URL using EDGE browser 
Step 3: Navigate to "SearchBox with fixed width and custom event handling" edit field.
Step 4: Verify narrator is providing information about "no.of results found" when searching

**Actual:** 
Narrator is not providing information about "no.of results found" when searching

**Expected:** 
Narrator should provide information about "no.of results found" when searching
![image](https://user-images.githubusercontent.com/53210862/61691280-d2f47f00-ad48-11e9-908a-0e464339d7bd.png)

**Comment by ecraig12345** [comment]
I'm not sure this is something the SearchBox itself can or should provide. The SearchBox control is basically just a text field with a search icon and a clear button; it doesn't know anything about the results. So if you want to announce the number of results, you'd have to add that in your code which consumes the SearchBox.
