### ISSUE TITLE
DetailsList: Dynamically adding & deleting rows

### ISSUE THREAD

**Issue by BjornVanWettere** [OfficeDev/office-ui-fabric-react#991]
#### Describe the issue:

I am using this component together with the 'Add row'-button, so I'm dynamically creating rows with Keys/Id's. On every row I have a 'Delete row'-button, which passes the ID so that I can delete the item in the items-list. These rows consist of TextFields, buttons, images, labels, etc. 
When I click this button, an item indeed gets removed. However, the content of the last row always seem to get removed, even though I delete an other item. 
The issue has nothing to do with the items-array I provide, since that one is correctly deleting the correct ID.

Could this be, because there is no 'Key' property set on the rows individually? Because I've experienced this with React before. 

#### Expected behavior:

I would expect the correct line to be removed, with it's content. Leaving the other lines alone.

**Comment by dzearing** [comment]
hmm I made a codepen of removing rows in a detailslist and have not experienced this.

http://codepen.io/dzearing/pen/WRKROd

Can you provide a codepen?

**Comment by BjornVanWettere** [comment]
You're doing it in a different way, and your way looks better. I'll try it out later today, and let you know my results. Thank you for investigating!

**Comment by dzearing** [comment]
@BjornVanWettere feel free to open in another issue if you have any more questions.
