### ISSUE TITLE
Footer Panel not positioned correctly even with isFooterAtBottom={true}

### ISSUE THREAD

**Issue by C1rdec** [OfficeDev/office-ui-fabric-react#9913]
### Environment Information 
 This behaviour appears in 7.11.0.
Prior 7.11.0 the panel footer is rendered at the bottom. 

(You can test it out with the Code Sand Box)

### Please provide a reproduction of the bug in a codepen:
 [This Code Sand Box](https://codesandbox.io/s/office-fabric-ui-sd1dy)

#### Actual behavior:
 
The footer is not position at the bottom even with isFooterAtBottom={true}

![image](https://user-images.githubusercontent.com/5436436/61739653-dc86e280-ad5a-11e9-8fae-7e8a70059313.png)

#### Expected behavior:
 
The footer should be in the bottom.

![image](https://user-images.githubusercontent.com/5436436/61739694-f9bbb100-ad5a-11e9-86a2-eeb89f7810d2.png)

**Comment by ecraig12345** [comment]
I suspect this was introduced by @nickdurak's change in #9780. @nickdurak or @Vitalius1 do you have suggestions for an alternative fix which handles both the issue reported here and the IE scenario #9780 was meant to address?

**Comment by cliffkoh** [comment]
This problem repos in @nickdurak 's PR: http://fabricweb.z5.web.core.windows.net/pr-deploy-site/refs/pull/9780/merge/fabric-website-resources/dist/index.html#/examples/panel

**Comment by cliffkoh** [comment]
But not before his PR: https://fabricweb.z5.web.core.windows.net/oufr/7.10.0/#/examples/panel

Confirmed this is a regression caused by #9780
