### ISSUE TITLE
How to Add New Persona into Facepile using people picker?

### ISSUE THREAD

**Issue by panigrah** [OfficeDev/office-ui-fabric-react#992]
Hi,

The Facepile react documentation page on the office UI fabric pages says

> Another variant is to use an input field with placeholder text instructing the user to add a person. See the PeoplePicker component for the menu used to add people to the Facepile list.

Does anybody have an example of how to get a PeoplePicker component and Facepile work together? 

thanks

**Comment by joschect** [comment]
@panigrah I don't believe that we have a specific example of this yet. I made this codepen which I think does what you're asking about.

http://codepen.io/slimemold/pen/ygmRMe

**Comment by panigrah** [comment]
Thank you @joschect  - I made a composite and operated in reverse. 

`
// use like so  <EditablePersona persona={people[0]} onResolveSuggesstions={this._onFilterChanged} />

import React from 'react'
import { Persona } from 'office-ui-fabric-react/lib/Persona'
import { NormalPeoplePicker } from 'office-ui-fabric-react/lib'

class EditablePersona extends React.Component {
  constructor (props) {
    super(props)
    this.state = {
      editing: false,
      loading: false,
      disabled: false,
      invalid: false,
      persona: {}
    }
    this._onKeyDown = ::this._onKeyDown
  }

  componentDidMount () {
    this.setState({ persona: this.props.persona })
  }

  componentWillReceiveProps (nextProps) {
    if (nextProps.persona !== this.state.persona) {
      this.setState({ persona: nextProps.persona, editing: false })
    }
  }

  startEditing = () => {
    this.setState({ editing: true })
  };

  finishEditing = () => {
    this.cancelEditing()
  };

  cancelEditing = () => {
    this.setState({ editing: false, invalid: false })
  };

  keyDown = (event) => {
    if (event.keyCode === 13) { this.finishEditing() }          // Enter
    else if (event.keyCode === 27) { this.cancelEditing() }     // Escape
  }

  _onChanged = (newPersona) => {
    this.setState({ persona: newPersona[0] })
    this.props.onChangeFulfiller(newPersona[0])
    this.cancelEditing()
  }

  _onKeyDown = (event) => {
    // trap escape key and close window
    if (event.keyCode === 27) this.cancelEditing()
    if (event.keyCode === 13 && this.editingComponentRef.value) this._onChanged({})
  }

  _onBlur = (event) => { this.cancelEditing() }

  renderEditingComponent = () => {
    return (
      <div onKeyUp={this._onKeyDown}>
        <NormalPeoplePicker {...this.props}
          inputProps={{ placeholder: 'Find a Fulfiller' }}
          defaultSelectedItems={[]}
          ref={(input) => { this.editingComponentRef = input; if (input) input.focus() }}
          onChange={this._onChanged} />
      </div>)
  }

  renderNormalComponent = () => {
    /* select between this.state.newValue, this.props.value */
    return (<Persona {... this.props}
      onFocus={this.startEditing}
      onClick={this.startEditing}
      {...this.state.persona} />)
  };

  render () {
    if (this.state.editing) {
      return this.renderEditingComponent()
    } else {
      return this.renderNormalComponent()
    }
  }
}

EditablePersona.propTypes = {
  onChangeFulfiller: React.PropTypes.func,
  persona: React.PropTypes.object,
  filterForPersonas: React.PropTypes.func
}

export default EditablePersona
`

**Comment by joschect** [comment]
@panigrah awesome! Looks really cool. Glad I could help.
