### ISSUE TITLE
JAWS shortcuts do not work when FocusZone has focus

### ISSUE THREAD

**Issue by brandonthomas** [OfficeDev/office-ui-fabric-react#9921]
Repro:
1. Go to https://developer.microsoft.com/en-us/fabric#/controls/web/focuszone
2. Open JAWS screen reader
3. Press 'H' to move between headers (should work).
4. Move focus to the FocusZone area
5. Press 'h'

## Actual behavior:
Nothing happens, shortcuts don't work.

## Expected behavior:
Keyboard shortcuts are able to be used when focus is within a FocusZone.

**Comment by brandonthomas** [comment]
Wondering if there's something in there calling stopPropagation or preventDefault and if that's the culprit.

**Comment by brandonthomas** [comment]
There's a number of internal accessibility bugs related to this BTW

**Comment by brandonthomas** [comment]
@dzearing can we have someone look into this?

**Comment by dzearing** [comment]
@aneeshack4 can you help @ecraig12345 on this one?

**Comment by dzearing** [comment]
hmm. I don't think focuszone itself ever would stop/prevent.

**Comment by aneeshack4** [comment]
It looks like this isn't a problem with preventDefault() or stopPropagation - this is a JAWS bug. I know we spoke offline a bit @brandonthomas sounds like you might have to speak with your a11y folks to file a bug with JAWS...
