### ISSUE TITLE
[Nav] Item Groups option to not expand on click

### ISSUE THREAD

**Issue by graham-sportsmgmt** [OfficeDev/office-ui-fabric-react#993]
I have a Nav structure where I don't want my parent ItemGroups navigating to a new page or picking up the Active style as they are purely categories and I want the user selecting something under them to proceed.  The current behavior (as of 1.7.0) is to only expand an Item Group when the accompanying arrow is clicked and the Active status is set to true on click.

I'd like to propose an option for the ItemGroup that puts it into a mode where:

1. Clicking anywhere on the object area (i.e. arrow or label) will toggle the isExpanded status
2. The Active flag will stay false

This would be in line with other Web UI frameworks such as Bootstrap or Foundation.

**Comment by inateeg** [comment]
Nav component actually support TRUE group header just for category and owning child links.  Then each link can be level 1 (parent) link or level 2 (child) link.  

Just in SP UX LeftNav, design choose not to show Group Header and only Level 1 and Level 2 links.  My question to you is that you wish SP LeftNav can host level 1 "link" that only serve as heading not real link?

**Comment by inateeg** [comment]
Or you are talking about Nav component used elsewhere in general?

**Comment by inateeg** [comment]
INavLinkGroup currently is serve what you are asking just it is not used in our SP modern page LeftNav.  That is why I am asking if you are asking for SP UX leftNav can support you with this heading or Nav component in general Level 1 link can be just header with no navigation on click?

**Comment by graham-sportsmgmt** [comment]
Yes, I'd like to have a group header to be only a header and not navigate.  How does that work?  I don't see anything in the documentation that addresses that.

I'm not sure what you're asking here though, could you please reword it?

> I am asking if you are asking for SP UX leftNav can support you with this heading or Nav component in general Level 1 link can be just header with no navigation on click?

**Comment by inateeg** [comment]
INavLinkGroup is only header. Not a link.

[cid:image001.png@01D28790.EA143940]

**Comment by graham-sportsmgmt** [comment]
The documentation is really unclear on how this works.  Could we add more detail to that page to explain this?

**Comment by inateeg** [comment]
OK  I will try to update if you got to below link
https://fabricreact.azurewebsites.net/fabric-react/master/#/examples/nav

Fabric sample page.  The LeftNav here is organized under Group headers that seem what you are looking for?

**Comment by graham-sportsmgmt** [comment]
I get this error when I try to visit that link:

> Sorry, but we’re having trouble signing you in. 
> We received a bad request.

I am using Edge with an Azure AD account.

**Comment by inateeg** [comment]
<Nav groups={ exampleGroups } onLinkClick={ this._onLinkClick } onRenderLink={(link) => ([ ... ]) }    />

exampleGroups: INavLinkGroup[]  /// those are group headers if given name prop value, the group header here only support expand and collapse, not navigation function;

exampleGroups[0].links: INavLink[]     /// those are links under each group header, each link can have children links.  Every link here is on click for navigation.

**Comment by graham-sportsmgmt** [comment]
Is there any way to see an example?  I'm using ES6 and not TypeScript btw.

**Comment by inateeg** [comment]
https://dev.office.com/fabric#/components/nav

try this link?

**Comment by graham-sportsmgmt** [comment]
Yes, that link works.  I didn't see any specific examples of what you were mentioning on that page.

Here is how I'm defining my groups, how can I change this to reflect a Group header without link?

```
let groups = [{
              links: [
                {
                  name: 'A',
                  icon: 'Stopwatch',
                  links: [{
                    name: 'A1',
                    key: 'key1'
                    },
                    {
                      name: 'A2',
                      key: 'key2'
                    }
                  ]
                },
                {
                  name: 'B',
                  icon: 'Edit',
                  links: [{
                    name: 'B1',
                    key: 'key1'
                    },
                    {
                      name: 'B2',
                      key: 'key2'
                    }
                  ]
                },
                {
                  name: 'C',
                  icon: 'People',
                  links: [{
                    name: 'C1',
                    key: 'key1'
                    },
                    {
                      name: 'C2',
                      key: 'key2'
                    }
                  ]
                }
              ]
            }];
```

**Comment by inateeg** [comment]
Try this out if you add a group name, it will render group header.

**Comment by graham-sportsmgmt** [comment]
Thank you, that changed the output to match the "Navigation menu used in this Fabric React demo app" example.  However, I see four key formatting problems:

1. The text is all caps which doesn't meet our UX guidelines,
2. I can no longer display an icon next to the label,
3. There is a lot of white space below the last item in a group, and
4. Every item starts expanded and doesn't respond to the isExpanded property

The Office 365 Admin portal is what I'm trying to emulate.  It is very intuitive, is nice and simple to use, and looks great too:

https://portal.office.com/adminportal/home#/homepage

**Comment by inateeg** [comment]
I am looping in David.  We can adjust group header style since we did not get a lot feedback or you can override css style of group header.  As for icon, I am not sure what you mean the link with icon?

**Comment by dzearing** [comment]
@graham-sportsmgmt I will talk with @inateeg . I believe i understand what you're saying. We'll either translate this into a codepen, or get a feature request going.

**Comment by graham-sportsmgmt** [comment]
Thanks, I think that the feature request could be as simple as giving us the ability to configure Nav to work exactly like the Office 365 Admin portal's left hand navigation.

**Comment by inateeg** [comment]
[cid:image001.png@01D2883F.FAF0D4D0]

Is this what you are asking?

**Comment by graham-sportsmgmt** [comment]
I don't see any attachments, although it looks like you did try to add one.

**Comment by inateeg** [comment]
https://portal.officeppe.com/account/#settings  you meant this page?  this one?

**Comment by graham-sportsmgmt** [comment]
I can't access that page.  This is the page I'm referring to:

![untitled](https://cloud.githubusercontent.com/assets/16939733/23079165/793513ec-f500-11e6-91e6-1248e6b154f4.png)

**Comment by inateeg** [comment]
All those are doable but we need office-fabric clear design spec on what pattern and how many patterns this Nav component is designed to serve?  Should involve designer team in this conversation?
