### ISSUE TITLE
Pivot headerText not correctly center aligned

### ISSUE THREAD

**Issue by larnera** [OfficeDev/office-ui-fabric-react#9931]
### Environment Information 
 
- __Package version(s)__:  Fabric 7.7.2
- __Browser and OS versions__: Window 10 Enterprise 1803 17134.829

https://codepen.io/anon/pen/voKjpg

#### Actual behavior:
 
The default pivot examples on the Fabric site doesn't show the headerText correctly center aligned, they appear left aligned. This is more noticeable when the pivot is selected and the pivot is underlined.

#### Expected behavior:
 
Pivot header center aligned. This can be fixed by adding: 

``` css
.ms-Pivot-linkContent {width: 100%}
```
#### Priorities and help requested:
 
Are you willing to submit a PR to fix? No
 
Requested priority: Low
 
Products/sites affected: Fabric - Pivot

**Comment by ecraig12345** [comment]
I'm not quite sure what you mean, sorry. What part of the pivot should be center aligned, and relative to what other part? As far as I can tell, toggling the change you proposed on/off doesn't make anything look more or less centered, unless it's an extremely subtle difference.

**Comment by larnera** [comment]
It is really subtle and barely noticable. Sorry!

![example](https://user-images.githubusercontent.com/2369339/61914123-61c6ee80-af37-11e9-86db-7155d73eb06d.png)

**Comment by ecraig12345** [comment]
Thanks, that helps! I'll have to check with someone who's more familiar with the Pivot's styling to be sure, but it seems like a reasonable change. (The change will probably be done in the core Pivot.styles.ts rather than just in the examples, since it's applicable to all Pivots.)

**Comment by Vitalius1** [comment]
This can be fixed in 2 ways. One is what the issue author suggested or making the `justify-content: center` style of the Button flex container where the link content is rendered in. I will investigate a little bit more and have a PR later today. Thanks for submitting the issue because according to the design specs it should be centered.

**Comment by larnera** [comment]
Thanks guys!
