### ISSUE TITLE
Combobox with multi select giving error with SPFx react

### ISSUE THREAD

**Issue by ymihir** [OfficeDev/office-ui-fabric-react#9936]
When I follow [the article to create combobox](https://developer.microsoft.com/en-us/fabric#/controls/web/combobox) with multiselect I am getting error. 
Below is my code.
![image](https://user-images.githubusercontent.com/7568187/61893048-ca5b9e80-af2a-11e9-9c08-54f1a54c8485.png)

Below is error:
```
Type '{ multiSelect: true; defaultSelectedKey: any; label: string; allowFreeform: true; autoComplete: "on"; options: IComboBoxOption[]; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<ComboBox> & Readonly<{ children?: ReactNode; }> & Readonly<IComboBoxProps>'.
  Property 'multiSelect' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<ComboBox> & Readonly<{ children?: ReactNode; }> & Readonly<IComboBoxProps>'.ts(2322)
```

**Comment by ecraig12345** [comment]
What version of SPFx and Fabric are you using? Some versions of SPFx come with an extremely old Fabric version which didn't have multiselect ComboBoxes yet.

**Comment by ymihir** [comment]
I am using 1.4.0 for SPOnline and SPOnprem versions. Can I update the fabric version? If I update fabric version will it break anything in solution?

**Comment by ecraig12345** [comment]
Which specific version on SP on-prem are you targeting?

Also, can you check the specific version of Fabric you're using by running `npm ls office-ui-fabric-react`?

**Comment by ymihir** [comment]
My target onprem version in SP2019. Below is my office-ui-fabric-react version
![image](https://user-images.githubusercontent.com/7568187/62042808-98915300-b21c-11e9-8df7-df60cdf3e4fc.png)

**Comment by ymihir** [comment]
@ecraig12345  Any update on this?

**Comment by ecraig12345** [comment]
Talked to some coworkers about this. It sounds like upgrading the Fabric version isn't possible with SPFx 1.4.0, but there are a couple other options.

If you just want the ComboBox's multi-select mode, you can upgrade to a minimum of SPFx 1.5.1, which includes Fabric 5.83 (multi-select was added in 5.69).

To get the ability to bundle any custom Fabric version, you can upgrade to SPFx >= 1.8.2. (If you go this route, it's recommended to static bundle using lib-based imports in the webpart, to reduce the bundle size.)

Does that help?

**Comment by ymihir** [comment]
If i upgrade spfx version to 1.8.2 it won't support in SP 2019 On-Premises right!

**Comment by ecraig12345** [comment]
Unfortunately yeah--I wasn't aware of that (and it wasn't clear in my coworker's original message), but shortly after I replied on GitHub they sent a follow-up email pointing out that issue.

**Comment by ecraig12345** [comment]
If you really want a multi-select ComboBox, the best workaround for the on-prem situation might be to copy the multi-select ComboBox control from a later version of Fabric into your code.

**Comment by ymihir** [comment]
Not only checkbox, even styles are not applying for modal dialogs. This is really disappointing. What should I do for my requirement? I need to stop using SPFx with react?
