### ISSUE TITLE
Tooltip hidden hover area is too large

### ISSUE THREAD

**Issue by kelseyyoung** [OfficeDev/office-ui-fabric-react#9947]
### Environment Information 
 
- __Package version(s)__: (fill this out) 7.10.0+
- __Browser and OS versions__: (fill this out if relevant)

### Please provide a reproduction of the bug in a codepen: 
https://codepen.io/anon/pen/QeKKyO
 

 
#### Actual behavior:
 
In the above codepen, hovering over certain parts of the button hides the tooltip (specifically, the bottom part because the tooltip is anchored to the bottom). I believe this is because the :after element recently added overlaps with the button and a "mouseleave" event is seen, hiding the tooltip. Introduced by this PR: https://github.com/OfficeDev/office-ui-fabric-react/pull/9775

Gif:
![TooltipBug](https://user-images.githubusercontent.com/4252452/61910114-93fd2f80-aee8-11e9-829b-2b5a3f10d8ce.gif)

#### Expected behavior:
 
From the above codepen, you should be able to hover over any part of the button and see the tooltip

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) Not sure what the correct fix is here. I don't know why the extra area was seemingly hardcoded to 15px. I would think that perhaps it should be the "height" of the beak, but there may be corner cases (e.g. no beak). I'm not very familiar with the Tooltip component
 
Requested priority: (Blocking, High, Normal, Low) Blocking a bump in Fabric for Word Online; in this case it is even worse because you can get in a constant mouseenter/mouseleave cycle which causes the tooltip to flicker (I think this may be related to how things are being re-rendered in Word Online specifically, but the underlying cause is the same)

![WordOnlineTooltip](https://user-images.githubusercontent.com/4252452/61910286-0bcb5a00-aee9-11e9-893e-daad86727e18.gif)
 
Products/sites affected: (if applicable) Word Online, pinning to 7.8.2 currently

**Comment by kelseyyoung** [comment]
@kysedate For FYI

**Comment by jspurlin** [comment]
@ecraig12345 FYI, this is a blocking issue for office online

**Comment by ecraig12345** [comment]
@khmakoto Since you did PR #9775 which introduced this, can you help with the fix (or at least advise what to do)?

**Comment by khmakoto** [comment]
@ecraig12345 sure, I'll take a look into the issue.
