### ISSUE TITLE
No way to return focus to last element when dialog closes with Voiceover iOS

### ISSUE THREAD

**Issue by suchk** [OfficeDev/office-ui-fabric-react#9957]
When closing a dialog box, the focus should return to the last focused element, e.g. the button that opened the dialog. This works fine for most scenarios, so initially I thought it was an issue with VoiceOver iOS. However, I tested with the example aria page for [dialogs](https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html) and it actually worked there.

I saw a [similar bug](https://github.com/OfficeDev/office-ui-fabric-react/issues/1651) that was closed, and tried out the suggested elementToFocusOnDismiss prop, but that didn't work.

I extracted the code out to two codepens to hopefully help isolate the issue.

This is using the Fabric dialog, which does not work:
https://codepen.io/anon/pen/WVxxWX

This is using the example page referenced above, which does work:
https://codepen.io/anon/pen/QeEEXa

**Comment by aneeshack4** [comment]
@suchk I tried VoiceOver on iOS on both of these codepens and they have the same behavior on close - as in the focus rect returns to the last element that was focused. Are you sure you're on the latest version of iOS? I tried this on Safari - are you on a different browser?

**Comment by suchk** [comment]
Sweet, I updated to iOS 12.4 and wasn't able to repro either. I tried in both Safari and Chrome and it worked. Thanks Aneesha.
