### ISSUE TITLE
[Accessibility] "Color as a meaning test" clears the whole page except top navigation bar. 

### ISSUE THREAD

**Issue by taparikh** [OfficeDev/office-ui-fabric-react#9962]
## Codepen demonstrating the issue
https://codepen.io/taparikh/pen/RXoGJR 

The above codepen just shows the CentralGrid component (DetailsList) which completely disappers when this test is performed. 

## Actual behavior:
Here are a few screenshots showcasing this behavior when "grayscale mode" is turned on in Google Chrome. 
![image](https://user-images.githubusercontent.com/51679982/61987492-ecf1c400-afcb-11e9-8ffc-a6b46eb5b797.png)

![image](https://user-images.githubusercontent.com/51679982/61987499-f7ac5900-afcb-11e9-98fe-dc092a44c142.png)

## Expected behavior:
When the same test was run on the office ui fabric website page > DetailsList -  the result is as expected. 
![image](https://user-images.githubusercontent.com/51679982/61987548-61c4fe00-afcc-11e9-92ca-030c3fff6458.png)

## Documentation describing expected behavior

Accessibility Insights Tool > Assessment > Sensory > Color as a meaning
The visual helper for this requirement displays the target page in grayscale.

- Examine the target page to identify any instances where color is used to communicate meaning, such as:
Communicating status
Prompting a response
Identifying an error
- For each instance, verify that at least one of these visual alternatives is also provided:
- On-screen text that identifies the color itself and/or describes the meaning conveyed by the color
- Visual differentiation (e.g., shape, position, size, underline) and a clear indication of its meaning
- Record your results:
If you find any failures, select Fail, then add them as failure instances.
Otherwise, select Pass.

**Comment by marygans** [comment]
Hi @taparikh! It looks like the accessibility bug is within the `CentralGrid` component or within Accessibility insights tool, considering when I try to[ repro](https://codepen.io/gwiz0210/full/aepeWK) the bug, the results are as expected, following the accessibility insights steps. You might wan to file an issue on the [Accessibility Insights tool](https://github.com/microsoft/accessibility-insights-web) instead?

**Comment by taparikh** [comment]
Hi @marygans  I have filed an issue with the Accessibility Insights team https://github.com/microsoft/accessibility-insights-web/issues/988
