### ISSUE TITLE
ComboBox: suggestedDisplayValue property of comboBoxState is not getting reset on clearing selectedKeys

### ISSUE THREAD

**Issue by pandey11** [OfficeDev/office-ui-fabric-react#9965]
#### Actual behavior:
I'm trying this code where formValidator.form.profile.value is a state and getting reset on click of a button.

Current Issue. When i'm trying to select value of comboBox using key board it is setting suggestedDisplayValue. But even if i'm clearing selectedKey to null it is not resetting suggestedDisplayValue and in turn text getting displayed in comboBox
`<ComboBox
    label="profile?"
    onChange={onComboBoxChange}
    options={profiles}
    required
    selectedKey={formValidator.form.profile.value}
/>` 
#### Expected behavior:
 It should clearComboBox if selectedKey gets reset

#### Priorities and help requested:

 Requested priority: (Blocking, High, Normal, Low)  High
 
Products/sites affected: Yes

**Comment by marygans** [comment]
Hi @pandey11! Thanks for reporting this. Could you provide a codepen example of this issue you are having? You ca start by clicking the "export to codepen" button on this [combobox example](https://fabricweb.z5.web.core.windows.net/oufr/7.18.0/#/examples/ComboBox).

**Comment by pandey11** [comment]
Hi @marygans, I have shared the recording of repro steps over email. Please let me know if needed more info.

**Comment by pandey11** [comment]
@ecraig12345 @marygans  any update on this ??

**Comment by marygans** [comment]
Hi @pandey11 my apologies on the delay here! I was able to view the video and was not able to repro the bug you see on the ms referral site locally. I will share the video repro with my colleagues and get back to you shortly!

**Comment by micahgodbolt** [comment]
I put together a quick codepen and trying to simulate your issue, but so far no luck:

https://codepen.io/micahgodbolt/pen/aeEdEo?editors=0011

While i see there is a suggestedDisplayValue 

![image](https://user-images.githubusercontent.com/1434956/62490984-96c91180-b77f-11e9-897b-f547d8d7d58f.png)


As soon as I select an option via keyboard, that state is removed. Can you fork this Pen and try to repro your isse?

**Comment by pandey11** [comment]
Hi @micahgodbolt please try this https://codepen.io/anon/pen/XvVaNo?editors=0011
 `onClick={() => {
              if (_basicComboBox.current) {
                setKey(null);
                // _basicComboBox.current.focus(true);
  }`
defining callback function inline somehow re-render the and component and cause performance issue.

**Comment by pandey11** [comment]
Repro step:
1. expand combo box. 
2. press d key of keyboard.
3. move you cursor outside of options pen so that combo box collapse.
4. Now hit reset combo box and check console

**Comment by micahgodbolt** [comment]
Ok I see. Repro is even easier. If you open the dropdown and then close it by clicking outside of the dropdown, setting the 'selectedKey' to null does not change the value.

![combo](https://user-images.githubusercontent.com/1434956/62555636-275b2c80-b828-11e9-8340-081f55e3746c.gif)

**Comment by pandey11** [comment]
This is creating illusion to user that required field is provided and but application is blocks to proceed.it's a high severity issue for our application

**Comment by micahgodbolt** [comment]
@pandey11 our shield devs are balancing a number of incoming issues. We'll take a look into as soon as we can. As an open source project, if you are able to find the offending logic (probably in the onDismiss callback) and create a PR, we'd be happy to review and get it merged ASAP

**Comment by pandey11** [comment]
@marygans i think the latest version is not working properly, can you please try with combobox which have key as string type

**Comment by marygans** [comment]
> @marygans @micahgodbolt i think the latest version is not working properly, can you please try with combobox which have key as string type,it's working with options having key as integer

Hi @pandey11, I just tested again and it is working fine for me, can you provide your example?

**Comment by micahgodbolt** [comment]
I'll reopen again until we can determine if there's still an issue here.

**Comment by jspurlin** [comment]
@marygans Did the previous fix not fix this issue? If not, is there active work on this?

**Comment by marygans** [comment]
Hi @pandey11 Below is what I see when I repro'd with strings. Can you share a bit more of your scenario via codepen or similar?
#### See below

![after-01](https://user-images.githubusercontent.com/38991459/62738299-d6ddfd80-b9e6-11e9-9951-ac60f31c2c43.gif)

_(React state in DOM now updates here)_
![after-02](https://user-images.githubusercontent.com/38991459/62738303-da718480-b9e6-11e9-8d84-416e4d4941ec.gif)


Thanks!

**Comment by pandey11** [comment]
@marygans Can we sync up over team, sometime tomorrow(Redmond time will also work).I am able to repro this in my application but  struggling to repro it with codepen.

**Comment by marygans** [comment]
@pandey11,  yeah sure. I will set up some time!

**Comment by marygans** [comment]
Closing this issue as I spoke with @pandey11 offline a few weeks regarding the issue in product application vs this repo. Feel free to re-open for any further questions
