### ISSUE TITLE
CSS in Js library

### ISSUE THREAD

**Issue by joehillerman** [OfficeDev/office-ui-fabric-react#9966]
Which css-in-js library do you use in OUFR? If it is a custom library, where can I find detailed documentation of how to use it?

**Comment by Kesshi** [comment]
https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/merge-styles

**Comment by marygans** [comment]
Thanks @Kesshi  for your quick response! @joehillerman does the reference to this [package ](https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/merge-styles)answer your question?
