### ISSUE TITLE
[DetailsList] Focus on wrong item when keyboard navigation

### ISSUE THREAD

**Issue by tipantaz** [OfficeDev/office-ui-fabric-react#9968]
Hello! I have been encountering the same issue, but no necessarily by clicking as this closed report.
https://github.com/OfficeDev/office-ui-fabric-react/issues/9176

Version: "office-ui-fabric-react": "7.5.0"
Chrome,Edge and windows.

## Codepen demonstrating the issue
I can reproduce it in your example.
https://developer.microsoft.com/en-us/fabric#/controls/web/detailslist

## Actual behavior:
Use tab to get to the list header (for example "Name"), use arrow down to get to the first row and press arrow key down one more time to get to the second.

Second one is selected but first one still has focus.

## Expected behavior:
Either focus following selection, or no focus.

**Comment by marygans** [comment]
Hi @tipantaz thanks for submitting this and referencing the example! This is a bug and we'll work on getting it fixed.

**Comment by marygans** [comment]
HI @tipantaz! I tried to repro your issue here again in this codepen and not seeing the issue anymore: https://codepen.io/gwiz0210/full/MWWKKjz. Can you confirm that this is still an issue for you?

**Comment by tipantaz** [comment]
Hi @marygans! I cannot reproduce it as well in the official examples, so I am guessing it is gone with your latest push. Thanks a lot for following up!
