### ISSUE TITLE
Solution fails at shrink wrap after newly published version of @uifabric/utilities

### ISSUE THREAD

**Issue by ishanisuchak** [OfficeDev/office-ui-fabric-react#9969]
### Environment Information
 
- __Package version(s)__: 6.143.0
 
#### Actual behavior:

Solution build fails when trying to run npm shrink wrap.
The observed behavior is that the office-ui-fabric-react version 6.143.0 installs @types/react-dom version 16.0.5. And it expects the dependency **@uifabric/utilities's** version to lie between **>=6.29.3 and <7.0.0**

But with the newly published **version 6.41.6 of @uifabric/utilities**, @uifabric/utilities now expects @types/react-dom to lie between **>=16.3.0 and <17.0.0**.

This causes an internal mismatch of the dependent versions.
 
#### Expected behavior:
 
A) **@uifabric/utilities's** latest version should be compatible with v16.0.5 of **@types/react-dom** 
**OR**
B) **office-ui-fabric-react v6.143.0** should downgrade and limit the dependent @uifabric/utilities version to avoid internal mismatch of @types/react-dom.

#### Priorities and help requested:

Requested priority: Blocking

### References

[oob React SPFx web part broken from yo due to Fabric 7 references](https://github.com/SharePoint/sp-dev-docs/issues/4147)

**Comment by ishanisuchak** [comment]
We are facing a similar issue again. This time it seems it is the @uifabric/utilities dependency for @types/react-dom. We saw that a new version has been published for the package, which now expects a version for @types/react-dom to lie between >=16.3.0 <17.0.0. It was earlier installing version 16.0.5 for the @types/react-dom and we now get an error saying it requires there are invalid peer dependencies.
Attaching the error screen.
![error](https://user-images.githubusercontent.com/25173209/61866740-59e55b00-aef3-11e9-97cb-8e9434087e9c.PNG)

**Comment by kenotron** [comment]
We cannot back out the @types/react-dom from 16.3.0 on 6.0 branch because that branch is using the new Context API which depends on React 16.3. I believe it would be an easy fix on the consumer side to upgrade @types/react-dom & @types/react to 16.3 without much issues because react generally has a backwards compatible API surface.

How much work would it be for you to upgrade @types/react on your end, @ishanisuchak ?
