### ISSUE TITLE
Underlying element is getting Hover state retained in IE11 after clicking on context menu option.

### ISSUE THREAD

**Issue by anushkumarkorukonda** [OfficeDev/office-ui-fabric-react#9970]
### Environment Information 
 
- __Package version(s)__: 6.190.1
- __Browser and OS versions__: IE11

### Please provide a reproduction of the bug in a codepen:

The underlying component hover state is retained if the contextual menu option is clicked.
This issue is happening in IE11.

https://codepen.io/anush9625/pen/qzeEJb
 
In the above link created there are three divs one after the other. The div color will change to blue on hover. If left click is done on any of the div contextual menu is opened. 
Left click on first div. Contextual menu will open and it will be shown on the top of other divs visually if there are more options. 
Now click on the option which fall in second div so that click target is inside the second div. Move away the mouse from the second div after click. Hover state of second div will retain.

#### Actual behavior:
 
The hover state of the underlying div is retained after clicking the contextual menu option. The hover state is going away after moving the mouse inside and out of the div.
 
#### Expected behavior:
 
The hover state of the underlying div should not retain after clicking the contextual menu option.

#### Priorities and help requested:
 
Are you willing to submit a PR to fix? (Yes, No) 
 
Requested priority: (Blocking, High, Normal, Low)  Normal
 
Products/sites affected:

**Comment by micahgodbolt** [comment]
## IE11

![ie11](https://user-images.githubusercontent.com/1434956/62081966-9624fe00-b208-11e9-8bbb-4fa81a5cc1cf.gif)

## Chrome

![chrome](https://user-images.githubusercontent.com/1434956/62082030-c371ac00-b208-11e9-8a66-7d3c6075ebf0.gif)

From what I can see, IE11 and Chrome perform the same way. Am I missing the issue here?

**Comment by anushkumarkorukonda** [comment]
@micahgodbolt After pressing the contextual menu option which is on top of the second div move the cursor immediately away from the second div. The hover state will be retained for second div in IE11 and in chrome it will go away.

**Comment by micahgodbolt** [comment]
Thats not what I'm seeing in IE11 (gif above).

**Comment by anushkumarkorukonda** [comment]
@micahgodbolt After clicking the context menu option move the cursor immediately out of the div without any delay. In the above gif there was small delay in moving out of the cursor. Then you can see the hover state retained for second div in IE 11 and in chrome it will work fine.

**Comment by micahgodbolt** [comment]
i simply can't repro this in IE11

**Comment by micahgodbolt** [comment]
![chrome](https://user-images.githubusercontent.com/1434956/62153337-320e4280-b2b9-11e9-9f80-4f4a435f5b7e.gif)

**Comment by anushkumarkorukonda** [comment]
@micahgodbolt  I have created two code pens one with list and one without list. 

Context Menu with List: https://codepen.io/anush9625/pen/pMpGdM
Conext menu without list: https://codepen.io/anush9625/pen/mNELpm

I am able to repro this issue in first link and the same can be reproduced consistently with the integration in our application.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/40074621/62629672-41d9f680-b94b-11e9-80b9-479cdccc0cdf.gif)

**Comment by micahgodbolt** [comment]
ok, wow. I was able to repro. 

It seems that IE11 has a bug where the hover pseudo selector gets stuck

![image](https://user-images.githubusercontent.com/1434956/62645152-80968f00-b900-11e9-9fc6-ec0c24326aec.png)

tbh, i don't think this is a fabric bug. These aren't fabric controls that are failing.

**Comment by anushkumarkorukonda** [comment]
@micahgodbolt Can you please help how can we proceed forward on this issue?

**Comment by anushkumarkorukonda** [comment]
@micahgodbolt  Can you please suggest how can be proceed further on this issue?

**Comment by micahgodbolt** [comment]
log a bug with the IE team

**Comment by marygans** [comment]
Hi @anushkumarkorukonda just wondering if you were able to successfully log a bug with the IE team?

**Comment by anushkumarkorukonda** [comment]
@marygans  I tried reaching IE team for raising this issue. But I am not able to get right contact or right place to log this issue. Can you please help to file this issue if possible?

**Comment by marygans** [comment]
@anushkumarkorukonda If you have already reached out to them I'd recommend giving some time to get back to you. I will soft close this issue with` Not an issue` label. If you have more questions, feel free to to ask and I will reopen it. Thanks for submitting the issue!
