### ISSUE TITLE
Missing "height: 100%" on ms-Panel-scrollableContent class breaks add-ins in Outlook Web on Safari

### ISSUE THREAD

**Issue by modestfake** [OfficeDev/office-ui-fabric-react#9972]
Hello there!

Sorry in advance, I report a bug which may not be related to a library directly.
Recently we've noticed that all Outlook add-ins inoutlook.com are broken on Safari, the content is truncated.
![image](https://user-images.githubusercontent.com/16977959/62055169-bca46280-b223-11e9-8520-bc6b2be9500c.png)

### Environment Information 
 
- Safari Version 12.1.1 and MacOS 10.14.5
- Outlook Web (outlook.com)

### Please provide a reproduction of the bug in a codepen:
 
Install any Outlook add-in from AppSource (for example [Slack for Outlook](https://appsource.microsoft.com/en-us/product/office/WA104382088), open it and you will see that the content is truncated.
 
#### Actual behavior:
 
I've found that if I add `height: 100%` to an element with class `ms-Panel-scrollableContent`, this fixes the issue. I believe Outlook uses `Panel` component to show the content. So it might be a problem with `Panel` component.
*Before*
![image](https://user-images.githubusercontent.com/16977959/62058062-718d4e00-b229-11e9-9dbb-f70bfe25c319.png)

*After*
![image](https://user-images.githubusercontent.com/16977959/62058098-810c9700-b229-11e9-90eb-1583893c4e31.png)

*Note:* I've added a background color to show that the content is truncated.
 
#### Expected behavior:
 
The inner content of iframe shouldn't be truncated

#### Priorities and help requested:
 
Requested priority: Blocking (it breaks every Outlook add-in on Safari)
 
Products/sites affected: Outlook add-ins

**Comment by marygans** [comment]
Hi @modestfake! Thanks you for filing this. There have been a few recent changes to Panel in the past weeks. Can you try and use the `isFooterAtBottom={true}` and see if that works? [Panel footer](https://uifabric.azurewebsites.net/#/controls/web/panel)  is an example of how it's used and below is a screenshot: 
<img width="1024" alt="Screen Shot 2019-07-29 at 1 48 25 PM" src="https://user-images.githubusercontent.com/38991459/62081510-a4bee580-b207-11e9-86f0-0c5065d2ca62.png">

If this doesn't work as a solution for you then we can try to create a repro on [CodePen](https://codepen.io/pen?template=NvBvWx) using the Fabric Components.

 Thanks!

**Comment by modestfake** [comment]
Hi @marygans. Thanks for the response!
Unfortunately, I can't try this. I'm an add-in developer and the only code I can manage is the code inside iframe. This problem is in the `Panel` which opens a taskpane in Outlook and which includes our iframe. So we have no control there. Probably I need to report this to Outlook team as well but I can't find the way to reach them out directly.

And thanks for `isFooterAtBottom={true}`, I didn't know about this. We will definitely find where to use this.

**Comment by modestfake** [comment]
Sorry, I should've mentioned that this happens only in "new Outlook experience".

**Comment by marygans** [comment]
Hi @modestfake ! 

I tried debugging the problem in the same way that you did (inspecting the iframe on Safari devTools) as I also do not have access to their code.  I tried to reproduce the bug using only the Fabric components and opening it in Safari but was unsuccessful. I would suggest reaching out to the folks at Outlook and I will do some digging on my side to get in touch with them!

I tried to [replicate it here](https://s.codepen.io/gwiz0210/debug/LwyVyw/GnrnbNQORemr) in a similar way that they did by not including `headerText` and getting rid of `commandBar` but still didn't get the scrolling issue in Safari. 

Below is what I found:

**Outlook on safari**
<img width="1250" alt="Screen Shot 2019-07-30 at 11 12 56 AM" src="https://user-images.githubusercontent.com/38991459/62154197-1a37be00-b2bb-11e9-9d1f-27aebdb81cbe.png">


**CodePen example**
<img width="1062" alt="Screen Shot 2019-07-30 at 11 26 21 AM" src="https://user-images.githubusercontent.com/38991459/62155133-fecdb280-b2bc-11e9-96cd-7b940b249515.png">

My initial hypothesis was that this could've been a potential issue in Panel's `scrollable-content ` div but I see that the styling in outlook is different and all the contents of the panel seems to be in the `content` div. So this is not an issue for this repo directly :)

**Comment by modestfake** [comment]
Thank you @marygans for your time. I've contacted Outlook support. Well... I hope I found the right way to report this :)
Do you think we can close this ticket or is it better if I get a response from the support and then update this ticket?

**Comment by marygans** [comment]
@modestfake, I was told that this is might already be a known issue, but feel free to leave this thread open for tracking purposes until it's confirmed!

**Comment by marygans** [comment]
@modestfake  I confirmed with the team that a fix was pushed for this issue last week and It should go live in a week.

**Comment by modestfake** [comment]
Thank you @marygans. I think we can close this issue then.
