### ISSUE TITLE
onColumnHeaderClick and onColumnClick not triggered for isIconOnly or empty/whitespace 'name'

### ISSUE THREAD

**Issue by eeccker** [OfficeDev/office-ui-fabric-react#9978]
### Environment Information 
 
- __Package version(s)__: 7.18.0
- __Browser and OS versions__: Chrome/Firefox Windows 10

### Please provide a reproduction of the bug in a codepen:

I don't see documentation outlining this behavior as expected so I'm assuming it's a bug.
 
[https://codepen.io/anon/pen/VopYJZ](https://codepen.io/anon/pen/VopYJZ)

1. Click on the column headers
 
#### Actual behavior:
 
onColumnHeaderClick and onColumnClick are NOT invoked when isIconOnly = true OR name is empty/whitespace

 
#### Expected behavior:

onColumnClick and onColumnHeaderClick should be invoked for all three columns.

**Comment by marygans** [comment]
Hi @eeccker thanks for submitting this. I played around with your[ codepen](https://codepen.io/gwiz0210/pen/wVpGZV?editors=1010) and you have to add the `iconName` prop (and a valid `iconName`) to have the functions trigger. It is intended behavior for the empty column to not click without a name or icon present.
