### ISSUE TITLE
Icon: Should not contain role='presentation' if it has any label

### ISSUE THREAD

**Issue by HalcyonPride** [OfficeDev/office-ui-fabric-react#9999]
## Codepen demonstrating the issue

See lines 48-55 in `Icon.base.tsx`.

## Actual behavior:

`role='presentation'` is applied even if `alt` or `aria-labelledby` is provided via `imageProps`.

## Expected behavior:

Do not apply `role='presentation'` when any label is provided, similar to the case where `ariaLabel` is provided, since assistive technology can interact with the label.

## Documentation describing expected behavior
https://www.w3.org/TR/wai-aria-1.2/#presentation

**Comment by HalcyonPride** [comment]
@leddie24, this is related to #8820.

**Comment by marygans** [comment]
Hi @HalcyonPride thanks for submitting this and referencing the related PR! 
@leddie24 do you think you can you help with the fix (or I can and run it by you)?

**Comment by marygans** [comment]
Hi @HalcyonPride this issue should've been addressed in the PR: #10526 so I will soft close this issue. If you have more questions, feel free to to ask and I will reopen it. Thanks for submitting the issue!
